### ISSUE TITLE
"integrated chat" on status bar non functional

### ISSUE THREAD

**Issue by marcdumais-work** [gitpod-io/gitpod#1]
Yesterday, using the service from my home machine, I tried to use the chat feature, but clicking on the button had no effect. Other status bar button were working as expected. 

That was with the Brave browser.

**Comment by marcdumais-work** [comment]
BTW it did seem to work when I previously tried on my work laptop, using Chrome.

**Comment by svenefftinge** [comment]
I could reproduce with brave. It worked after I removed some restrictions (pop up blocker)

**Comment by marcdumais-work** [comment]
ok, I will try again, after disabling the pop-up blocker, thanks!

**Comment by svenefftinge** [comment]
Note, that the icon is currently only there after initializeLoad. On reload it vanishes due to the recent change to not store the status bar state.

**Comment by svenefftinge** [comment]
Not seen anymore, please reopen if this happens again.
