### ISSUE TITLE
Cleanup DB state after #7171

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#10001]
Original issue: https://github.com/gitpod-io/gitpod/issues/7171

It seems we still have some users with a bad DB state. We should cleanup those duplicates.

Identify users by counting subscriptions per user, and display those with more than 10 should turn up the one in bad state.

**Comment by AlexTugarev** [comment]
closing as dup of https://github.com/gitpod-io/gitpod/issues/10002
