### ISSUE TITLE
Revert Investigate #9924 and re-apply

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#10008]
- [x] Temporary revert: https://github.com/gitpod-io/gitpod/pull/10006
 - [x] Investigate why #9924 breaks prebuilds, fix it, and re-apply

**Comment by andrew-farries** [comment]
Working in preview environment https://af-test-noae1a9bf075.preview.gitpod-dev.com/. This is off main but with https://github.com/gitpod-io/gitpod/pull/10006 reverted (ie the bug should be reproducible there)

* Created a new project from https://github.com/andrew-farries/gitpod-playground
* A prebuild was created in `PENDING` state
* Watching the logs of the prebuild we saw the image build logs followed by the prebuild logs, but the state never left `PENDING`.
* After the prebuild was complete, the UI did not transition to the workspace.
* Reloading the page did not transition to the workspace either, just reloaded the prebuild view
* Starting a new workspace also just led to the prebuild logs view
* By hitting 'skip prebuild', we were able to get to the workspace
