### ISSUE TITLE
PSA: Cannot read property 'sha' of undefined ?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1000]
**Describe the bug**

For some reason i can't open a gitpod on this repository https://github.com/Kreyren/gitpod-tests even when i am using a config grabbed from a 'working' repo.

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/11302521/70744774-b8846780-1d22-11ea-8d75-96887ea85900.png">

Gitpod works on: https://github.com/Kreyrock/Kreyrock
Fails on: https://github.com/Kreyren/gitpod-tests

**To Reproduce**

Open https://gitpod.io/#https://github.com/Kreyren/gitpod-tests and expect `Error: Cannot read property 'sha' of undefined` error.

Open https://gitpod.io/#https://github.com/Kreyrock/Kreyrock and notice that the configuration is same and working.

**Additional info**
I tried to remove the instance from workspaces which doesn't affect it

relevant: https://github.com/gitpod-io/gitpod/issues/643
relevant: https://github.com/gitpod-io/gitpod/issues/692
relevant: https://github.com/gitpod-io/gitpod/issues/717

=== UPDATE ===

I solved this while writing this issue, submitting it as PSA assuming that Gitpod should output a better message.

This was caused by having a file `gitpod.Dockerfile` instead of `.gitpod.Dockerfile`

**Comment by jankeromnes** [comment]
Oops, yes that would be https://github.com/gitpod-io/gitpod/issues/717. Sorry about that, we should really improve the feedback here.

Thank you for reporting problems! 💯
