### ISSUE TITLE
Workspace fails to open after a few hours of not using it

### ISSUE THREAD

**Issue by RossComputerGuy** [gitpod-io/gitpod#1001]
**Describe the bug**
Cannot open workspace after opening Chromebook a few hours of not using the workspace

**To Reproduce**
Open a workspace after not using it for a few hours.

**Expected behavior**
The workspace to load

**Additional Information**
![image](https://user-images.githubusercontent.com/19699320/70750258-f3ff4180-1ce2-11ea-8799-0c6a628e8a00.png)

**Comment by JesterOrNot** [comment]
Sounds like a Kubernetes issue
