### ISSUE TITLE
I don't understand how to install plug-ins?

### ISSUE THREAD

**Issue by bbhxwl** [gitpod-io/gitpod#10023]
I don't understand how to install plug-ins?
Why is this the plug-in installed in c#.
```
vscode:
  extensions:
    - muhammad-sammy.csharp
```
Not this?

```
vscode:
  extensions:
    - C#
```

**Comment by andymac4182** [comment]
There is many extensions that can be installed to support a single language. The docs covers how to get the id of the extension that you need to use. Also not all extensions are available at this point as this uses a different extension marketplace to the Microsoft copy of VSCode.


https://www.gitpod.io/docs/ides-and-editors/vscode-extensions

**Comment by bbhxwl** [comment]
> There is many extensions that can be installed to support a single language. The docs covers how to get the id of the extension that you need to use. Also not all extensions are available at this point as this uses a different extension marketplace to the Microsoft copy of VSCode.
> 
> https://www.gitpod.io/docs/ides-and-editors/vscode-extensions

Do I need to install the plug-in configuration file? I install it manually once, so I don't need to install it in the future?
