### ISSUE TITLE
Billing Says 98.5 of 100 hours remaining:  All of it spent waiting for Workspace to load!

### ISSUE THREAD

**Issue by quixotictech-dev** [gitpod-io/gitpod#10021]
### Bug description

For two days I have been unable to load a workspace for whatever possible reason.  Is load time supposed to count against plan hours?  Because you sure seem to require a lot of it and often end up not loading at all.  Fingers crossed that this is a bug and not Modus Operandi.  This program is no where near solid enough to expect someone to buy their load time.  Maybe if 20-30 seconds was the max for average load time, but I have never experienced anything less than 50 seconds averaging 90-240 seconds.  I haven't even been on a workspace for this block yet I'm down an hour an a half.

### Steps to reproduce

1)  Buy plan

2)  Add repository to project.

3)  Click create workspace

4)  wait

5)  wait

6)  restart after timeout

7)  wait

8)  check billing statement for all the productive waiting time

### Workspace affected

quixotictec-quixoticcan-jfkl1b2gjz2

### Expected behavior

...

3)  Click create workspace

4)  Work in said space.

**Comment by bbhxwl** [comment]
So I bought unlimited time, but there is no Asian region, which is a pity.

**Comment by pawlean** [comment]
> So I bought unlimited time, but there is no Asian region, which is a pity.

Hi @bbhxwl! It's worth tracking this here: https://github.com/gitpod-io/gitpod/issues/5534

**Comment by axonasif** [comment]
@quixotictech-dev is this still happening?

**Comment by axonasif** [comment]
@quixotictech-dev is this still happening?
