### ISSUE TITLE
gp init returns "internal server error"

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10036]
**Steps to replicate:** 
1. Go to blank repo (or without `.gitpod.yml` / delete it - `rm .gitpod.yml`) in a gitpod workspace
2. Execute `gp init`
3. See output

**Expected result**
* No output

**Actual result**
* `2022/05/16 09:58:12 500 Internal Server Error `

**Note:** No network request appears to be made at the time. 

![image](https://user-images.githubusercontent.com/5528307/168568127-b5d95eba-e27d-4078-b7b3-8935ac0bbee4.png)

**Comment by gtsiolis** [comment]
@loujaybee I could not reproduce this using VS Code latest or not using Browser or Desktop. 🤷 

Do you have [a minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) or repository for this?

**Comment by loujaybee** [comment]
@gtsiolis, hrm, I'm not getting the response anymore 🤔 

I'll close, if I see it again, will re-open 🙏 !
