### ISSUE TITLE
Question: Better preview of HTML ?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1003]
I'm using gitpot on https://github.com/RXT067/cheatsheets where i'm able to preview the website using firefox on vnc image:

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/11302521/70830571-c9031380-1df0-11ea-9e7e-cc21b343c49e.png">

Is there a way to open-up the html page only on full screen of preview so that developers woudn't have to search around for the window?

### Steps to reproduce
- Open https://gitpod.io/#https://github.com/RXT067/cheatsheets
- Run `make -B _site`
- Wait for site to build
- Invoke `firefox _site/foo.html` (replace foo with any html file in `_site/`)
- Check the website in the window.

### Tried solutions
- I tried to download https://marketplace.visualstudio.com/items?itemName=hdg.live-html-previewer  and https://marketplace.visualstudio.com/items?itemName=daiyy.quick-html-previewer which doesn't open-up:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/11302521/70831419-d28d7b00-1df2-11ea-8883-dabb2e68b233.png">

**Comment by Kreyren** [comment]
Solved: Gitpod already has the preview built-in that i didn't know about

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/11302521/70831797-bdfdb280-1df3-11ea-9501-e78f37224ec3.png">

**Comment by jankeromnes** [comment]
Cool that you found the embedded preview! (There is also a preview button on the top right of certain files, like HTML, Markdown, etc.)

Alternatively, for HTML files, you can also navigate to the directory in the Terminal, and run:

```
python3 -m http.server 3000
```

Then simply open port 3000 in a preview.
