### ISSUE TITLE
How many months will there be an Asian node? The only thing less than codespaces is this.

### ISSUE THREAD

**Issue by bbhxwl** [gitpod-io/gitpod#10037]
I use gitpod in Asia, and the Ping delay is 300ms. After waiting for more than half a year, I still haven't realized the Asian node of gitpod. The Asian node of codespaces is Singapore, and the delay is only dozens.

**Comment by atduarte** [comment]
Hi @bbhxwl 👋 We understand that currently the experience is not the best, and want to do better but unfortunately we weren't yet able to prioritise that work. We will share be sharing the updates in #5534.
