### ISSUE TITLE
extract cgroup library from ws-daemon in supervisor

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#10043]
Supervisor and ws-daemon both need information provided by cgroups, but have slightly different implementation. We need to extract a common go library.

See [this discussion](https://github.com/gitpod-io/gitpod/pull/9796#discussion_r872432473) for more context.

**Comment by Furisto** [comment]
@akosyakov I discussed this with @kylos101 and these are the tasks that need to be completed:
- Create the cgroup library
- Switch workspace components to the library
- Extend IWS with an endpoint that provides resource information that is using this library
- Supervisor uses this endpoint to retrieve resource information. That way the IDE team does not need to mess with linux and workspace implementation details.

Do you agree with the direction and is there anything else that you would need?

**Comment by kylos101** [comment]
> It sounds good then the workspace team is going to take care about it?

@akosyakov the first 3 bullets, yes, I think so. For the 4th, for supervisor to use new IWS endpoint, what do you think? I thought IDE team may want to do consumption of the new IWS endpoint from supervisor.

**Comment by akosyakov** [comment]
I think you need to refactor supervisor as well to make sure that library is aligned with our expectations.

**Comment by Furisto** [comment]
Solved by https://github.com/gitpod-io/gitpod/pull/10836
