### ISSUE TITLE
[observability] fire alert when we have an excessive node count 

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#10049]
## Is your feature request related to a problem? Please describe
If many nodes are added, many workspaces start, begin to stop, but one gets stuck in terminating and the finalizer is not removed, the auto scaler can get "stuck" scaling down on that pod's node, and will not scale down till you remove the finalizer on that pod. 

## Describe the behaviour you'd like
Look at grafana to assess what ratio of nodes (regular or headless) make sense for an alert. In general, we should always have less nodes than workspaces or an equal number of both are zero. That should be good enough to catch this condition in the future.

**Comment by utam0k** [comment]
This PR may alleviate this problem.
https://github.com/gitpod-io/gitpod/pull/10085

**Comment by kylos101** [comment]
@sagor999 this happened when the auto scaler misbehaved on a cordoned cluster, we had 10+ nodes, many of which needed to be removed because they were hosting zero workspaces. The problem with the autoscaler was that it would not remove nodes while one of their pods was stuck in Terminating due to a finalizer on a workspace pod.

In other words, many regular nodes had zero workspaces, but weren't being removed by the auto scaler. Perhaps it would make more sense to build an alert for that condition, where 4 or more nodes exist for a workspace type (regular, prebuild), but they've had zero corresponding workspaces for a duration of at least 1h.

**Comment by kylos101** [comment]
> This PR may alleviate this problem. #10085

@utam0k I do not think so, this is more a problem with the autoscaler not scaling down nodes while a single pod is stuck in Terminating status.

**Comment by kylos101** [comment]
@sagor999 I am going to close this for now, it's a fringe scenario that's only happened once.
