### ISSUE TITLE
Create a workspace from subdirectory in monorepo

### ISSUE THREAD

**Issue by EugenWay** [gitpod-io/gitpod#10040]
Is it possible to create an isolated workspace from a subdirectory in a mono repository that contains app examples?

Like https://gitpod.io/#https://github.com/EugenWay/apps/tree/master/[apps-name-1]

Thank you!

**Comment by pawlean** [comment]
Hi @EugenWay! Currently, this is not possible, but I encourage you to raise a feature request. 🙏🏼 I also recommend that you join our Discord server at https://www.gitpod.io/chat where our community hang out with questions like these!

**Comment by axonasif** [comment]
Hey @EugenWay, have you tried doing `code <your-sub-dir-here>` on a Gitpod workspace?
