### ISSUE TITLE
Add information to Replicated support bundle

### ISSUE THREAD

**Issue by julia-leyton** [gitpod-io/gitpod#10059]
In order to support troubleshooting for our Self-Hosted customers it would be great to include the following info in the current support bundle.

- ` network policy`
- `storageclass`
- `volumesnapshotclasses`
- output of `kubectl version`

**Comment by lucasvaltl** [comment]
@MrSimonEmms would you mind checking which one of these we already have, and which ones we should add and potentially create issues for that?

**Comment by MrSimonEmms** [comment]
We don't have any of these in the [support bundle](https://github.com/gitpod-io/gitpod/blob/main/install/kots/manifests/kots-support-bundle.yaml).

Storage class is easy to add ([docs](https://troubleshoot.sh/docs/analyze/storage-class/)) as that's supported out of the box.

The Network Policy, VolumeSnapshotClasses and `kubectl version` aren't supported by default. However, these should be fairly straightforward to get by running a pod and then running the `kubectl` command in that pod, similar to how I've done it with the database/storage/registry checks. As this is in a support bundle and we just want the values, the [run](https://troubleshoot.sh/docs/collect/deprecated/run/) collector saves to a file in the support bundle.

I don't think we need to add separate tickets for each bit as it's all in the same area
