### ISSUE TITLE
GitLab token expires when workspace is reused

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#10065]
### Bug description

I sometimes reuse workspaces when they are in a completely uncommitable state. That means I create them on day 1 and then reopen them on day 2. However after a certain amount of time I am not able anymore to push my changes to the remote git (GitLab in my case). Probably the tokens have expired?

### Steps to reproduce

Create a workspace.
Reopen it a few days later and try to push some changes.
-> error

### Workspace affected

qbilonio-qbilonapplicat-nsptrj38867

### Expected behavior

I can still push changes (Tokens are refreshed on workspace restart?)

**Comment by AlexTugarev** [comment]
It's this issue https://github.com/gitpod-io/gitpod/issues/10932.
I couldn't find the cause on our end, but instead learned about issues with the renewal process on Gitlab side when the refresh token is fairly old. 'Spent too much time on this :-(

**Comment by jldec** [comment]
(removed from Clarification status)
