### ISSUE TITLE
Use a single object storage bucket per Gitpod installation

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#10070]
## Is your feature request related to a problem? Please describe
Currently, full object storage permission is required to install Gitpod as it creates and uses multiple storage buckets. This is a problem for many self-hosted customers. Additionally, AWS account default limit is 100 buckets [[1](https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html)].

## Describe the behaviour you'd like
Self-hosted installations should only use one storage bucket, while SaaS in GCP, for egress optimization regions, should remains as is.

## Describe alternatives you've considered
None that I can think of.

## Additional context
[Internal slack thread 1](https://gitpod.slack.com/archives/C02F19UUW6S/p1652789401018709), and [2](https://gitpod.slack.com/archives/C01LDA28WV6/p1652728380421749)

**Comment by sagor999** [comment]
@aledbf is working on this: https://github.com/gitpod-io/gitpod/pull/10073
Assigning to him, as I was about to start working on this... good that I checked slack threads prior to diving in.
Please update issues when you start working on them.

**Comment by aledbf** [comment]
@sagor999 sorry about that.

**Comment by sagor999** [comment]
@aledbf @kylos101 asked me to help out to take this issue\fix to the finish line, so going to assign it to myself.
