### ISSUE TITLE
[ws-daemon] sporadic crash of ws-daemon

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#10081]
### Bug description

About once a day one of ws-daemons crashes. 
Looking at the state of `ws-daemon` container:
```
Last State:     Terminated                     
  Reason:       Completed                      
  Exit Code:    0                              
  Started:      Wed, 04 May 2022 15:29:50 -0700
  Finished:     Tue, 17 May 2022 06:35:49 -0700
```
Looking at logs, the last entry is:
`Received SIGINT - shutting down`

This would indicate that readiness or liveness prove had failed, and k8s restarted the container.
Cannot confirm 100%, since we do not persist k8s events in log storage right now.

Looking at how health checks are done:
```
	// write out the response code and content type header
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)

	// unless ?full=1, return an empty body. Kubernetes only cares about the
	// HTTP status code, so we won't waste bytes on the full body.
	if r.URL.Query().Get("full") != "1" {
		w.Write([]byte("{}\n"))
		return
	}

	// otherwise, write the JSON body ignoring any encoding errors (which
	// shouldn't really be possible since we're encoding a map[string]string).
	encoder := json.NewEncoder(w)
	encoder.SetIndent("", "    ")
	encoder.Encode(checkResults)
```

This means we only return code, but never any error messages that probe might produce.

Looking at ws-daemon source code:
https://github.com/gitpod-io/gitpod/blob/9e2f4acb688ba774dd1ad73b157eef25d3d97fa7/components/ws-daemon/pkg/daemon/daemon.go#L202-L219

All those error messages would never be reported in our logs with current implementation of the probe.

### Steps to reproduce

No known repro. Happens in SaaS.

**Comment by utam0k** [comment]
I have some infomations: 
- It seems to happen when the ws-daemon's gc happened. [grafana](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&var-cluster=us45&var-node=All&var-pod=All&var-grpc_method=All&var-datasource=VictoriaMetrics&from=1652766900000&to=1652777759000)
- There is a go-routine reak
    - https://github.com/gitpod-io/gitpod/blob/6b11a82af7532f2c04e6f14f18222f06b650eddc/components/ws-daemon/pkg/cgroup/plugin_iolimit_v1.go#L110

**Comment by sagor999** [comment]
@utam0k hm. I can't find a correlation between metrics and actual pod restart.

**Comment by utam0k** [comment]
> @utam0k hm. I can't find a correlation between metrics and actual pod restart.

@sagor999 
Can you see `Go Runtime Metrics` section  on [grafana](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&var-cluster=us45&var-node=All&var-pod=All&var-grpc_method=All&var-datasource=VictoriaMetrics&from=1652766900000&to=1652777759000)?
If you focus on ws-damon-2djrv, you will see that it is restarting during GC.

**Comment by sagor999** [comment]
From recent crash: 
`Readiness probe failed: Get "http://10.20.10.195:8086/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by sagor999** [comment]
[this](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&var-cluster=us45&var-node=All&var-pod=ws-daemon-7f7vn&var-grpc_method=All&var-datasource=VictoriaMetrics&from=1652898710126&to=1652904720561) tells me that it might not be related to number of go routines. 
container restarted 3 times in a row. 

I think it is something with checking containerd status.
But, looking at logs of containerd on the host, I don't really see any signs of a problem with containerd.
Plus it if would be containerd, then other containers would have issues as well. 
:thinking:

**Comment by jldec** [comment]
Similar readiness failure messages again today (and multiple wsdaemon restarts -> critical alerts)  
from describe pod 👇 

> Warning  Unhealthy     12m (x130 over 154m)  kubelet          Readiness probe failed: Get "http://10.20.193.65:8086/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by jldec** [comment]
Looking at the GC times and they appear to correlate with the restarts.
There were several GCs which took more than 4 seconds

![Screenshot 2022-05-23 at 17 14 56](https://user-images.githubusercontent.com/849592/169863413-cc081c64-0920-4666-97ed-c374a00705a0.png)

**Comment by sagor999** [comment]
This seems to be related to ws-daemon doing a lot of backups and getting so busy that it stops responding to readiness probes.
Alejandro adjusted how many backups we do at the same time and I think that might have fixed this particular case.
So I will close this issue as done.
