### ISSUE TITLE
Error: Couldn't parse context 'https://e1826c32-6b03-4b9c-b8ca-e56a6bf8cd6e.ws-eu01.gitpod.io/'.

### ISSUE THREAD

**Issue by garaei** [gitpod-io/gitpod#1008]
**Describe the bug**

FROM ERLY BEGIN IT GIVES ME THIS ERROR;
Error: Couldn't parse context 'https://e1826c32-6b03-4b9c-b8ca-e56a6bf8cd6e.ws-eu01.gitpod.io/'.

**To Reproduce**

JUST OPEN THE PROJECT

**Expected behavior**

iT SHOULD OPEN MY PROJECT WORK SPACE 

**Additional Information**

Error: Couldn't parse context 'https://e1826c32-6b03-4b9c-b8ca-e56a6bf8cd6e.ws-eu01.gitpod.io/'.

**Comment by jankeromnes** [comment]
Hi @garaei! The "context URL" is whatever you put after the `gitpod.io/#` prefix.

Gitpod currently only supports GitHub and GitLab URLs (repositories, issues, pull requests, etc).

From your error message, it looks like your trying to open this URL:

> `https://gitpod.io/#https://e1826c32-6b03-4b9c-b8ca-e56a6bf8cd6e.ws-eu01.gitpod.io/`

This will not work. Where did you find this URL? In other words, just before you saw this error page, did you click on some button or did you type in some URL in your browser's address bar?

**Comment by jankeromnes** [comment]
Follow-up thought: If you're simply trying to resume your Gitpod workspace with the ID `e1826c32-6b03-4b9c-b8ca-e56a6bf8cd6e`, please simply go to:

https://gitpod.io/workspaces/

then find the right workspace in the list (if you don't see it, check "Archived"), and then click on "Start" next to it. That should do it.
