### ISSUE TITLE
Firefox extension request permissions for unrecognized domain

### ISSUE THREAD

**Issue by maphew** [gitpod-io/gitpod#10080]
### Bug description

On relaunching Firefox Gitpod extension asks for permissions to access data for sites in the jihulab.com domain. That domain is not visibly associated with Gitpod and is not listed at https://addons.mozilla.org/en-CA/firefox/addon/gitpod/

![image](https://user-images.githubusercontent.com/486200/168909536-2beef271-d6de-4070-a12c-80d044d0366e.png)

### Steps to reproduce

see previous

### Workspace affected

any

### Anything else?

Firefox 100.0.1 (64-bit) on Windows 10

**Comment by gtsiolis** [comment]
Thanks, @maphew! Cross-posting from https://github.com/gitpod-io/gitpod/issues/10067#issuecomment-1129032821:

> This is expected due to the latest browser extension release[[1](https://github.com/gitpod-io/browser-extension/releases/tag/v1.14)] which includes changes in the manifest to support opening repositories from jihulab.com, formerly known as [gitlab.cn](http://gitlab.cn/)[[2](https://about.gitlab.cn/)][[3](https://about.gitlab.com/blog/2021/03/18/gitlab-licensed-technology-to-new-independent-chinese-company)]. See relevant pull request in https://github.com/gitpod-io/browser-extension/pull/56.

However, we've reverted this change for now as others have asked about this, see https://github.com/gitpod-io/browser-extension/releases/tag/v1.15. Updating the extension should suppress this permission request.

Closing this for now, but feel free to reopen if you have any further questions. 📕
