### ISSUE TITLE
CI/CD on gitpod?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1009]
Is there a way to run CI/CD on gitpod?

Meaning quality assurance tests like https://travis-ci.org/Kreyrock/Kreyrock/builds/625841266?utm_source=github_status&utm_medium=notification (tests after commit outside of gitpod) ?

**Comment by svenefftinge** [comment]
You can include any test runs in your `init` tasks so they would run during prebuild. Is that what you asked for?

**Comment by Kreyren** [comment]
> You can include any test runs in your init tasks
 
Those seems to run on gitpod only I would need some frontend for it to be used in merge requests like provided example

**Comment by Kreyren** [comment]
closing as stale
