### ISSUE TITLE
GitLab connection tokens auto-expire. Repository not found starting GitLab workspace. New Project feature broken.

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#10090]
GitLab appears to have changed the way they do token expiration.
This results in the following errors in Gitpod

- Repository not found Error opening GitLab workspace
  <img width="388" alt="image (2)" src="https://user-images.githubusercontent.com/849592/169303746-fd00dd04-7844-4b2b-9f5d-cf37751ed6e3.png">

- New project feature broken for all users with a GitLab connection - even when creating a GitHub Project.  
  UI shows spinner. 401 error in dev console.  
  
  <img width="1503" alt="Screenshot 2022-05-18 at 10 18 10" src="https://user-images.githubusercontent.com/849592/169304051-2e1acf9a-eb29-41e7-86e3-8743e2a70949.png">

**RECOMMENDED WORKAROUND**
Log out of Gitpod, and then log in with GitLab. This will update the GitLab auth token.

**Comment by AlexTugarev** [comment]
gitlab.com was updated recently and token refresh is now enforced. Unfortunately, there is no way on our end to invalidate  all users' tokens.

> All existing integrations must be updated to support access token refresh.
From: https://docs.gitlab.com/ee/integration/oauth_provider.html#expiring-access-tokens

**Comment by jldec** [comment]
This should be fixed now - thank you @AlexTugarev 🙏 .

**Comment by AlexTugarev** [comment]
I think it's good to close now.
