### ISSUE TITLE
Unable to authorize using Firefox 71.0

### ISSUE THREAD

**Issue by ofury** [gitpod-io/gitpod#1011]
**Describe the bug**
Unable to authorize using Firefox 

**To Reproduce**
1. Open https://gitpod.io/login/ in Firefox 71.0 (64-bit) (Windows 10)
2. The "Log in page" appears without login form

**Expected behavior**
"Log in page" appears with login form

**Additional Information**
Firefox console log:

Firefox can’t establish a connection to the server at wss://gitpod.io/api/gitpod. reconnecting-websocket-mjs.js:483:18
The connection to wss://gitpod.io/api/gitpod was interrupted while the page was loading. reconnecting-websocket-mjs.js:483:18
{…}
​
error: Error: "TIMEOUT"
​
message: "TIMEOUT"
​
target: Object { _retryCount: 25, _shouldReconnect: true, _connectLock: true, … }
​
type: "error"
​
<prototype>: Object { constructor: t() }
logging.js:149:19
    v logging.js:149
    d logging.js:124
    error logging.js:47
    onerror service-factory.ts:20
    listen connection.js:47
    _callEventListener reconnecting-websocket-mjs.js:521
    _handleError reconnecting-websocket-mjs.js:167
    _handleError reconnecting-websocket-mjs.js:167
    _handleTimeout reconnecting-websocket-mjs.js:493
    _connectTimeout reconnecting-websocket-mjs.js:488

**Comment by jankeromnes** [comment]
Hi @ofury, thank you for reporting this and sorry for the bad experience.

This is likely a known issue: do you have another tab open with a stopped Gitpod workspace in it? If so, please close it, and Gitpod will work normally again.

Explanation: when a workspace stops, the tab currently tries to reconnect to the server to see if your workspace is coming back up or not. This is unfortunately a bit aggressive, leading Firefox to temporarily rate-limit all websocket connections to Gitpod.

(Chrome doesn't have this problem, but I think they don't respect the websocket specification, which I believe asks for a top-level domain rate-limit.)

This is something we need to fix in our stopped workspace tabs, but you can easily work around it by closing these tabs.

**Comment by ofury** [comment]
@jankeromnes, 
Unfortunately I can`t authorize at all to use Gitpod in Firefox.
Maybe something changed in last Firefox updates. I used it before without any issues.
Chrome is working ok at the same PC.

**Comment by jankeromnes** [comment]
@ofury That's unfortunate. I use Gitpod daily in Firefox 73.0a1 on Mac OS without any issues.

Please double-check that you don't have any Gitpod tab open somewhere. The WebSocket timeout and retry count look very much like rate-limit problem.

Or, could you possibly use Gitpod from behind a proxy that blocks all WebSocket connections?

**Comment by ofury** [comment]
I guess the problem because of  a proxy. The strange thing is that Chrome works without issues behind same proxy.
