### ISSUE TITLE
Add feedback successful submission step in the feedback modal

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#10124]
### Problem to solve

Following up from the discussion in https://github.com/gitpod-io/gitpod/pull/10061#discussion_r876113464, the feedback modal currently lacks a successful submission step.

> 1. We're missing a confirmation step to provide some feedback to users that we've received their feedback. Currently, when submitting the form, it feels like you are throwing something out of a cliff, no?
> 2. For the same reason, when you are pressing enter on the second step, it's not entirely clear that your feedback has been sent.

Cc @laushinka because https://github.com/gitpod-io/gitpod/pull/10061
Cc @jldec because https://github.com/gitpod-io/gitpod/issues/7925

### Proposal

Add a feedback successful submission step in the feedback modal.

### Designs

| Early design from the linked discussion above |
|-|
| <img width="1440" alt="Modal" src="https://user-images.githubusercontent.com/120486/169098522-7438c54f-fac2-491c-959c-e4392adea6aa.png"> |

> See [design specs](https://www.figma.com/file/HknoZvF952qXt3Sk4wLdrq/Low-friction-dashboard-form-to-collect-feedback-about-Gitpod-features-%237925?node-id=1068%3A1523) for grabbing the emoji SVG.

**Comment by laushinka** [comment]
@gtsiolis Should we close this because implemented in #10071?

**Comment by gtsiolis** [comment]
Thank you for coming back to this, @laushinka! ✨ 

The UX issue described here seems still valid (see screenshot below) but we did add the feedback successful submission step in #10071. ✔️ 

The UX issues are also mentioned in the following two comments which are included in the follow-up issue in https://github.com/gitpod-io/gitpod/issues/10307:
1. https://github.com/gitpod-io/gitpod/pull/10071#discussion_r880611543
2. https://github.com/gitpod-io/gitpod/pull/10071#discussion_r880793513

Closing this, and referencing the proposal from the issue description in the follow up issue in https://github.com/gitpod-io/gitpod/issues/10307, see point [9] in the issue description. 📕 

| PROPOSAL | PRODUCTION |
|-|-|
| <img width="1440" alt="Modal" src="https://user-images.githubusercontent.com/120486/169098522-7438c54f-fac2-491c-959c-e4392adea6aa.png"> | <img width="1440" alt="Screenshot 2022-06-01 at 11 05 55 AM (2)" src="https://user-images.githubusercontent.com/120486/171363125-366c8be5-5fab-4fb6-a336-1cf2c42cc4d6.png"> |
