### ISSUE TITLE
Gitpod - for react native environment

### ISSUE THREAD

**Issue by suprmat95** [gitpod-io/gitpod#10125]
## Is your feature request related to a problem? Please describe
Is it possible to run a react native environment in gitpod?  If yes, how?

## Describe the behaviour you'd like
I'd like to have a common react native environment for my team in gitpod.

## Describe alternatives you've considered
Virtual machine.

**Comment by axonasif** [comment]
Hey 👋 
I think you reached out to us via email. Closing this.

Also, leaving https://github.com/jayfresh/react-native-expo-gitpod here for anyone stumbling upon this issue 😁

**Comment by giantgun** [comment]
How would one be able to use Android emulator on gitpod. Or use the expo go QR code on gitpod. The article on port forwarding and the likes are vague and not detailed enough.
