### ISSUE TITLE
Extending workspace timeout using ide button fails with error

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#10120]
### Bug description

When trying to extent the workspace timeout of a workspace in us45 cluster the extension fails with an error (screenshot)

![image](https://user-images.githubusercontent.com/32481722/169263245-fcf8730b-1fa7-4752-8fc1-f3444d495d91.png)

### Steps to reproduce

Start a workspace in us45 cluster. Click on the workspace timeout extend button

### Workspace affected

https://gitpodio-workspaceprevi-v4jb4i9vtbd.ws-us45.gitpod.io/

**Comment by princerachit** [comment]
Assigning to the webapp team as it looks like the webapp is sending incorrect cluster name to the ws-manager-api.

**Comment by gtsiolis** [comment]
Thanks, @princerachit! See also https://github.com/gitpod-io/gitpod/issues/9173.

**Comment by gtsiolis** [comment]
@princerachit I'll close this as duplicate in favor of #9173 but feel free to reopen if this describes a different issue.
