### ISSUE TITLE
Debugging Java sometimes doesn't work

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#1013]
**Describe the bug**
Sometimes, when I try to debug Java (by going to the Debug left panel and clicking the green button), it doesn't work. It shows error messages like this:

<img width="511" alt="Screenshot 2019-12-17 at 17 18 58" src="https://user-images.githubusercontent.com/599268/71022994-15f12d80-2102-11ea-8172-98bd8a023b6f.png">

But there are no error messages, not in the Terminal; nor in the Debug Console; nor anywhere else.

**To Reproduce**
1. Open https://gitpod.io/#https://github.com/gitpod-io/spring-petclinic
2. Open the left Debug panel
3. Click on the green "Play" button
4. It doesn't work (error notifications + no output anywhere)

**Expected behavior**
Debugging should work, there should be output logged somewhere, and the error notifications shouldn't be there.

**Additional Information**

**Comment by akosyakov** [comment]
It is a dup of https://github.com/gitpod-io/gitpod/issues/886

**Comment by svenefftinge** [comment]
dupliace of #1018
