### ISSUE TITLE
[GitLab] Can't open new (empty) GitLab repository

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#1014]
**Describe the bug**
When I want to open a brand new (empty) GitLab repository, Gitpod fails with:

```
Error: Cannot find tag/branch: jankeromnes/gitpod-test/tree/master.
```

<img width="1218" alt="Screenshot 2019-12-19 at 04 33 43" src="https://user-images.githubusercontent.com/599268/71142803-c6e9ec00-2218-11ea-8cb2-e4aeeafe832e.png">

**To Reproduce**
1. Try to open https://gitpod.io/#https://gitlab.com/jankeromnes/gitpod-test

**Expected behavior**
It should open my repository.

**Comment by jankeromnes** [comment]
Workaround: You can create any new file or commit from GitLab's UI, then Gitpod will start to work on that repo.

**Comment by corneliusludmann** [comment]
Fixed in production.
