### ISSUE TITLE
What the hell just happened

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1015]
I think Gitpod just updated and it looks to have broken a lot of stuff, like for example everything I type in the terminal is being duplicated, so for example pressing `s` results in `ss`.

Not sure what just happened, but its broken everything and I'm certainly not happy about it.

**Comment by jankeromnes** [comment]
Hi @RDIL, we're very sorry about the breakage. We just deployed a new version to production (we do these quite frequently, and usually you shouldn't even notice them, apart from a very brief orange flash), which may have triggered this Terminal duplication bug.

I've seen this problem too on rare occasions. Could you please simply refresh your IDE tab? That usually resolves it for me. (And I agree that we should investigate and fix this -- there are a couple rare input problems like these that mysteriously evade our debugging attempts...)

**Comment by RDIL** [comment]
Hey @jankeromnes,
I understand, and yes, deleting the workspace and recreating it fixed it.  
The only thing remaining broken is RubyGems, [and this will fix it](https://github.com/gitpod-io/workspace-images/pulls).  Other than that, the update doesn't seem to be disturbing anything.

**Comment by jankeromnes** [comment]
> deleting the workspace and recreating it fixed it

Glad that it's fixed! In theory a simple browser refresh should have fixed it, but deleting/recreating a workspace should also work well if you can do that. 🙂

I took at look at the PR -- many thanks for making these! (And sorry for the slow response time on that repository, there are a couple outstanding PRs that I'd love to get merged soon.)
