### ISSUE TITLE
GitpodWorkspacesStuckOnStopping alert is misleading

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#10174]
### Bug description

The [`GitpodWorkspaceStuckOnStopping`](https://github.com/gitpod-io/gitpod/blob/5045e85f2aabcb53bed5c72e5aa10f859073eb2c/operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet#L29-L45) alert is misleading. It's checking if the number of workspaces in "STOPPING" is consistently higher than some (low) threshold. 

It does NOT however check if it's the very same workspaces that have been in stopping for a given time.

### Steps to reproduce

Stop many workspaces at the same time

### Expected behavior

The alert should only fire if the same workspaces are actually stuck in stopping.

### Related

xref: [the runbook to improve](https://github.com/gitpod-io/runbooks/issues/344)

**Comment by jenting** [comment]
> The alert should only fire if the same workspaces are actually stuck in stopping.

We could check the `current time - the time of DeletionTimestamp > the workspace timeout time`.

For example, if the workspace default timeout time is 1 hour, the alert could check whether `the current time - the time of DeletionTimestamp > 1 hour`, then trigger an alert.
