### ISSUE TITLE
Windows 11 Chrome Terminal View

### ISSUE THREAD

**Issue by GamerCoder215** [gitpod-io/gitpod#10178]
### Bug description

On Chrome (Windows 11, 101.0.4951.67 (Official Build) (64-bit) (cohort: Stable)), the GitPod VS Code desktop version has the terminal looking like swiss cheese.

![image](https://user-images.githubusercontent.com/54124162/169712581-9cebe5e3-9dfa-44e4-a5a3-d45b9fdba6e5.png)

### Steps to reproduce

1.) USe that Chrome Build on Windows 11
2.) Use GitPod as normally, see terminal

### Workspace affected

gamercoder215-diamondpin-n3obzwiuei2.ws-us45

### Expected behavior

Terminal should look like normal VS Code Terminal

**Comment by axonasif** [comment]
Hey, please take a look at https://github.com/gitpod-io/gitpod/issues/4130
