### ISSUE TITLE
[jb] mavenprojects are not imported automatically with warm-up in prebuilds

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#10185]
### Bug description

JetBrains IDE Issue: mavenprojects are not imported automatically with warm-up in prebuilds.

See this [internal thread](https://gitpod.slack.com/archives/C02BRJLGPGF/p1652080919910699)

### Steps to reproduce

- Enable IntelliJ in Gitpod preferences
- Start a workspace with prebuilds on https://github.com/gitpod-io/spring-petclinic
- Note the Explorer is empty.
  ![image](https://user-images.githubusercontent.com/418083/169799597-9d5f29c1-2358-4488-be74-5b9697f8d079.png)
- To make the project display correctly on Explorer, one has to click "Load Maven Prject" in the notification area.
  ![image](https://user-images.githubusercontent.com/418083/169799685-a0bd0ac5-aa3b-418f-8211-54702393f5e7.png)
  ![image](https://user-images.githubusercontent.com/418083/169799839-cd6558c9-f8bd-4cb3-81ee-8a97c792d3c0.png)

### Expected behavior

Instead modules should be imported automatically.

### Example repository

https://github.com/gitpod-io/spring-petclinic

**Comment by loujaybee** [comment]
Related JetBrains issue: https://youtrack.jetbrains.com/issue/IDEA-294532

**Comment by fmartins** [comment]
In my case, the maven project was automatically imported after using the directive

```
jetbrains:
  intellij:
    prebuilds:
      version: stable
```

https://www.gitpod.io/docs/ides-and-editors/intellij#indexing-using-prebuilds

---

After this change, my current issue is with the timespent while importing the project.
Does anyone have a great idea about how we can optimize this process? My java project is getting ~10minutes to be ready for use

**Comment by akosyakov** [comment]
> After this change, my current issue is with the timespent while importing the project.

@fmartins Could you elaborate on it please?
