### ISSUE TITLE
Find a way to display workspace ID in GCP Snapshots page

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#10186]
## Is your feature request related to a problem? Please describe
We want the GCP Snapshots page contains the information of workspace ID. So, it's convenient to see the snapshot belongs to which workspace ID. 

Currently, the snapshot contains the PVC name _only_.
![image](https://user-images.githubusercontent.com/49380831/169938989-2cb63171-5f00-406d-8b39-d98eca5ca155.png)

And the PVC contains the information as.
- PV name
- PVC name (same as workspace name)
![image](https://user-images.githubusercontent.com/49380831/169939190-ac72bb01-a21a-42e0-86f6-6b0fcfedccc0.png)

Although we could get the PVC name from snapshot first, and then get the workspace ID from description.
It'd be good if we could found the workspace ID directly from the snapshot.

## Describe the behaviour you'd like
Display the workspace ID in snapshot either by description _or_ label.

## Describe alternatives you've considered
Manually check snapshot to get the PVC name, and then check the disks to find the workspace ID from the description.

## Additional context

#7901

**Comment by jenting** [comment]
Reference PR https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/935

**Comment by jenting** [comment]
We should be able to achieve by adding the flag `--extra-create-metadata` to the csi-snapshotter and updates the gcp-compute-persistent-disk-csi-driver from [v1.4.0](https://github.com/gitpod-io/workspace-preview/blob/dd75d039626645389a7d5056554c9944c2a9cde2/gcp/deploy/kubernetes/images/stable-master/image.yaml#L55) to v1.7.0 that includes the [PR](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/935) and Pavel's [PR](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/release-1.7/CHANGELOG/CHANGELOG-1.7.md). After that, the snapshot contains the VolumeSnapshot name/namespace and VolumeSnapshotContent name in snapshot description field.

However, the [release v1.7.0](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/releases/tag/v1.7.0) doesn't have the corresponding container image be released. We have to wait the upstream to release the v1.7.0 container image.

**Comment by sagor999** [comment]
Keep in mind that PVCs are ephemeral. They exist only as long as workspace is running. When workspace stops, PVC gets deleted and only Volume Snapshot will remain.

**Comment by kylos101** [comment]
@jenting is this still blocked, or did you mean for status to be something else?

**Comment by jenting** [comment]
I'm waiting for the upstream to release the next container image, so I put into blocked status.

**Comment by sagor999** [comment]
@jenting can you also explore if it is possible to add `labels` to snapshots? Not just description. 
Why labels? Labels allow us to filter the cost. 
We might need to introduce upstream PR for this.

**Comment by jenting** [comment]
If I remember correctly, there is no way currently.

But we could improve code to upstream 😄

**Comment by jenting** [comment]
> @jenting can you also explore if it is possible to add `labels` to snapshots? Not just description. Why labels? Labels allow us to filter the cost. We might need to introduce upstream PR for this.

Which label are we preferred to add to filter the cost? I could think is the label to diffentiate the standard/XL cluster.
