### ISSUE TITLE
observability: add metrics so we can measure frequency and duration of PVC snapshot backup and restore

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#10195]
Frequency:
- PVC snapshot backup
  - `workspace_backups_success_total`.
  - `workspace_backups_failure_total`.
- PVC snapshot restore
  - `workspace_restores_success_total`.
  - `workspace_restores_failure_total`.

Duration:
- PVC snapshot backup: `gitpod_ws_manager_volume_snapshot_seconds`.
- PVC snapshot restore: `gitpod_ws_manager_volume_restore_seconds`.

**Comment by sagor999** [comment]
@jenting assigning to you, similar to this: https://github.com/gitpod-io/gitpod/pull/9355

**Comment by jenting** [comment]
For the  PVC snapshot restore time, we could calculate the time of PVC object be initialized to bound.
