### ISSUE TITLE
Gitpod generates bad .gitpod.yml for unsupported projects (content "{}")

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#1020]
**Describe the bug**
When you open a project, Gitpod now offers to take you through the setup (if there is none).

The first step is to generate a `.gitpod.yml`. But if the project isn't supported (e.g. it's not npm/yarn/mvn/etc), the generated file looks like this:

```
{}
```

**To Reproduce**
1. Open a not-yet-supported project in Gitpod, e.g. https://gitpod.io/#https://github.com/llvm/llvm-project (careful, the clone time is a bit long)
2. Accept the setup prompt
3. Accept the `.gitpod.yml` generation

**Expected behavior**
The default `.gitpod.yml` should be syntactically valid, and maybe have some standard boilerplate to help the developer fill in the blanks.

**Additional Information**
<img width="1440" alt="Screenshot 2019-12-20 at 09 55 26" src="https://user-images.githubusercontent.com/599268/71244184-3ee80d00-2312-11ea-813d-d35ab78e94da.png">

**Comment by svenefftinge** [comment]
this was fixed some time ago already
