### ISSUE TITLE
Repo with incremental prebuilds temporarily stopped triggering prebuilds

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#10209]
- created https://github.com/jldec/yarn-prebuild with an init task (`yarn install`)
- created a project -> first prebuild was auto-triggered
- turned on incremental prebuilds
- made several more commits
- after 4 additional commits (i.e. 4 incremental prebuilds) the repo stopped triggering prebuilds
- subsequent commits do not have a prebuild, so the init task is running in each workspace

#### update
- prebuilds were stalled but not entirely stopped
- an hour later they resumed and caught up

**Comment by jldec** [comment]
I thought perhaps this was a rate-limiting issue, but we're nowhere close to 50 commits.
https://github.com/gitpod-io/gitpod/pull/8568

**Comment by jldec** [comment]
After an hour, prebuilds have resumed - so this is not a bug - just a mystery.

![Screenshot 2022-05-24 at 11 54 25](https://user-images.githubusercontent.com/849592/170018942-a5da675c-d36e-47cd-8e6f-050ae137ccc1.png)

**Comment by jankeromnes** [comment]
Wow, many thanks for reproducing this bug!

Unfortunately the `d_b_project_usage.lastWebhookReceived` timestamp doesn't keep history, so we can't use it to know whether you did receive webhook events during the "no prebuild" period.

Are you able to find out anything about the webhooks being sent from GitHub's project settings/admin?

**Comment by geropl** [comment]
This sounds like a temporary issue. With our (preliminary) webhook events table we should be able to pinpoint such issues in the future. 👍 

@jldec I will close this for now as I don't now how to action it; please re-open if this happens again! 🙏
