### ISSUE TITLE
Unable to open workspace on desktop Vs Code

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#10206]
### Bug description

[Error  - 07:14:08.305] failed to access the local app: Error: workspace not found

### Steps to reproduce

1. Attempt to open workspace in VS Code
2. VS Code opens
3. Error in the popup says "Workspace not found"

### Workspace affected

kunxinchor-fatefoundrym-i2rmto3a64w

### Expected behavior

Opens in VS Code

**Comment by akosyakov** [comment]
We developed a new SSH connection mode for VS Code Desktop which brings stability and performance improvements. This mode can be enabled by setting `gitpod.remote.useLocalApp` to `false` in VS Code settings and will be enabled by default in future releases. You can learn more about new the approach in its announcement [blog post](https://www.gitpod.io/blog/vscode-desktop-ssh-updates).
