### ISSUE TITLE
Update GCP PD CSI driver from v1.4.0 to v1.7.1 to include faster PVC mount time fix

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#10210]
## Is your feature request related to a problem? Please describe
Currently, in the workspace-preview, we shipped the GCP PD CSI driver with v1.4.0, we should bump the version v1.7.1 which includes Pavel's work on making the PVC mounting time more faster.
But we have to wait the upstream to release v1.7.0 container image first. https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1000

## Describe the behaviour you'd like

Bump the GCP PD CSI driver to v1.7.0.

## Describe alternatives you've considered

No

## Additional context

https://github.com/gitpod-io/gitpod/issues/7901

**Comment by jenting** [comment]
Waits upstream release new container image.

**Comment by sagor999** [comment]
@jenting as part of this task, can you also make sure we are using this params now as well:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/956
This is to ensure that we poll for gcp attachment event faster then default 5sec, that way we can proceed with workspace container creation faster, instead  of waiting 10+ seconds. More info: https://github.com/gitpod-io/gitpod/issues/9054

**Comment by kylos101** [comment]
@jenting is this still blocked, or did you mean for status to be something else?

**Comment by jenting** [comment]
I'm waiting for the upstream to release the next container image, so I put into blocked status.

**Comment by sagor999** [comment]
@kylos101 before we will start dog fooding PVC work at gitpod, we need to make sure that this issue is closed.
Why? Without it, PVC attach time is considerably longer and first impressions matter. If new PVC approach will be perceived as much slower then old one, we will have unnecessary friction with adopting this feature.

**Comment by kylos101** [comment]
@sagor999 :+1: yes, @jenting indicated that today too, and shared work is in-progress [here](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1000#issuecomment-1150127928). 

One option may be for us to build this image ourselves, if it cannot be available fast enough through [this means](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1000#issuecomment-1150127928). wdyt? :thinking:

**Comment by sagor999** [comment]
Yup, that is a good option (to build image)

**Comment by sagor999** [comment]
Seems like 1.7.1 was just released:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/releases/tag/v1.7.1

**Comment by kylos101** [comment]
Thank you, @aledbf !
