### ISSUE TITLE
Factory URL to create new branches (in an existing repo)

### ISSUE THREAD

**Issue by CarterQC** [gitpod-io/gitpod#10226]
## Is your feature request related to a problem? Please describe
We've started using Asana as a company instead of github issues. 

We previously used the extension that added the Gitpod button, which was very handy for creating a new workspace set to a new branch named after the issue. I'm looking for a way to easily do that with Asana automations.

## Describe the behaviour you'd like
Be able to open a workspace from an existing branch/commit, but set in the anchor URL (somehow) the name of the new branch.

Something like `gitpod.io/#https://github.com/my-project/tree/main?branch=some-new-branch`

This way I could easily have gitpod open a workspace to a brand new (previously non-existent) branch that I've set in the anchor URL, but I wouldn't need to link to a github issue.

## Describe alternatives you've considered
Using Asana automations to sync tasks to create github issues, but those tend to be expensive and not work that well (delays, issues, etc.)

This would be a really simple way to be able to get that issue -> new branch feature anywhere.

**Comment by atduarte** [comment]
@kylos101 I'm unsure of who owns this. Would it be part of the Workspace Start Request and therefore WebApp or us?

**Comment by kylos101** [comment]
@atduarte this feels like context parsing to me, and would start on the webapp side. For example, when we start Gitpod from the context of an issue, that also creates a related branch. @geropl added to webapp inbox for consideration.
