### ISSUE TITLE
[setup] Smarter readme update

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#1022]
Currently, the assistant is just pasting in a markdown version of the readme badge to the top of a readme.
It need to handle other cases:
 - no existing readme. (Ask if one should be created)
 - asciidoc
 - html syntax (many readme's prefer that so they can center layout the badges)

Also the insertion point could, try to find a better place by checking for certain patterns in the readme.

**Comment by jankeromnes** [comment]
Good idea! There is also `README.rst` sometimes.
