### ISSUE TITLE
Building image with custom Dockerfile fails

### ISSUE THREAD

**Issue by lechien73** [gitpod-io/gitpod#10220]
### Bug description

When trying to build a workspace that pulls from `gitpod/workspace-base:latest`, the build fails with `Error: headless task failed: exit status 1`

This is whether you are using a full custom Dockerfile or a minimal one.

<img width="1010" alt="Screenshot 2022-05-24 at 14 29 47" src="https://user-images.githubusercontent.com/21156053/170047022-2bed226e-831a-4504-b143-3bf8242ceeb3.png">

### Steps to reproduce

1. Visit https://github.com/lechien73/workspacetest, which contains a minimal custom Dockerfile pulling from `workspace-base:latest`
2. Click the Gitpod button to open in Gitpod (or visit https://gitpod.io/#https://github.com/lechien73/workspacetest)
3. The Building Image step fails with the error noted above

### Expected behavior

The workspace should build normally without errors.

### Example repository

https://gitpod.io/#https://github.com/lechien73/workspacetest

### Anything else?

This is an issue currently affecting our entire student body.

**Comment by GordonSmith** [comment]
I am seeing the same with:  https://gitpod.io/#https://github.com/GordonSmith/ECL-Playground/tree/hpcc-platform-8.6.28-1 
But the following branch is working:  https://gitpod.io/#https://github.com/GordonSmith/ECL-Playground/tree/hpcc-platform-8.4.12-1

**Comment by kylos101** [comment]
Hi there, this was resolved as part of [this incident](https://www.gitpodstatus.com/incidents/vrgy1bpsq523).
