### ISSUE TITLE
Open gp URL with flag/command (e.g. `gp url port --open`)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10245]
Most often when I type gp URL it's because I also want to open the browser, not print the URL. 

1. Type `gp url 3000`
2. Have to click the command

Would be nice if there was a quick way to just open the browser automatically, e.g. via a flag to gp url (`gp url 3000 --open`)

**Sidenote:** `gp open` feels intuitively like it should do this, not open a file, and we also have `gp preview` for this behaviour inside the IDE/editor.

**Comment by akosyakov** [comment]
Is not it `gp preview $(gp url 3000)`? 

It is documented here: https://www.gitpod.io/docs/command-line-interface#url

**Comment by filiptronicek** [comment]
Here's the piece of code responsible for opening in the browser that @akosyakov mentioned 👀 
https://github.com/gitpod-io/gitpod/blob/0945a996fbc95f2bd074c87cb2f7a29dbdbf158e/components/gitpod-cli/cmd/preview.go#L33-L39

**Comment by alileza** [comment]
I wonder what about something like

```
$ gp url --preview
Previewing on url=http://localhost external=false

$ gp url --preview --external
Previewing on url=http://localhost external=true

$ gp url 8080 --preview --external                   
Previewing on url=http://8080-localhost external=true
```

I think that would be cleaner. But there will be a hard dependency between `url` command and `preview` command. I'm not sure how critical that is for maintenance.

I drafted a PR there for an example, could groom the PR a bit more with test if this looks good

**Comment by loujaybee** [comment]
Closing for now, as we have the workaround composing the two commands as @akosyakov suggested. I still feel that's a clunky API for what feels like a fairly common action, though (that said, it is very "linux" in a composition sense, though).

**Comment by loujaybee** [comment]
@alileza — sorry I did not see your pull request until just now! 

@akosyakov — do you think there's an API in here that could make sense, or you still feel this is unnecessary given the composed example?

**Comment by alileza** [comment]
@loujaybee no problem, so I guess it's safe to close the PR for this?

**Comment by akosyakov** [comment]
> @akosyakov — do you think there's an API in here that could make sense, or you still feel this is unnecessary given the composed example?

I think there are already well known commands how to achieve it.  We should consider what to do with them if we are going to duplicate functionality in another place. `gp url` originally is intended to have only one function.
