### ISSUE TITLE
Can't pull image, can't kill workspace

### ISSUE THREAD

**Issue by marcopeg** [gitpod-io/gitpod#1024]
**Describe the bug**
When I try to open my wkspace "https://e78fe1ad-f7e3-4f6c-9e2e-1fa5c357668c.ws-eu01.gitpod.io/" I get the error "cannot pull image: Back-off pulling image "eu.gcr.io/gitpod-dev/workspace-images:86fa69f0a8476bc83ad0679b1f9d500c24cfc21cce009f8e5e4c042326f917db"
Please file an issue if you think this is a bug." (that suggests me to open this issue)

**To Reproduce**
I just have to try to run my workspace.

**Expected behavior**
The workspace should open as usual

**Additional Information**

**Comment by marcopeg** [comment]
seems to be working fine now

**Comment by jankeromnes** [comment]
Please re-open if it starts happening again.
