### ISSUE TITLE
Nav Items change when navigating to Admin>License

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10246]
### Bug description

Weirdly, if I navigate to the license page in the admin dashboard of a self-hosed installation (Was using latest / main of today) the top nav items change from `Workspaces` to `Branches`. If I then click on anything in the nav bar, I am stuck in this weird nav bar world where there are no workspaces 🤔 You can reset this by going back to home (clicking the Gitpod icon).

See this [loom](https://www.loom.com/share/bf3d570a69694a7c863a76bd778f7572) for a runthrough.

### Steps to reproduce

Set up self hosted instance, or go to a recently completed werft build and log into the instance (this only works if you are the first one to do so and by this get given admin privileges). Navigate to the admin dashboard then to the license page.

**Comment by gtsiolis** [comment]
Thanks @lucasvaltl for noticing this, recording the loom, and opening this issue! 🙏 

Long-term, this will be resolve with https://github.com/gitpod-io/gitpod/issues/8385 which would remove the unnecessary tabs and move the left sidebar menu to tabs, see admin screenshots in the issue description.

> <img width="1440" alt="160603576-b4a152d6-ea70-4f8c-b57f-4c011171cdd0" src="https://user-images.githubusercontent.com/120486/170238917-174699bb-c26d-46b6-aee1-786e7439fde7.png">

However, it could be worth resolving this earlier as a minimum viable change in the scope of this issue, as reusing the tabs on the admin area would require us to also align the content of the pages below.
