### ISSUE TITLE
Kots admin UI bug - in-cluster S3 fields don't go away

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10257]
### Bug description

In the KOTS installation Configuration section, under Container registry, you can get into a state where fields are being shown that should be hidden.

### Steps to reproduce

Check the in-cluster option, then select the S3 alternative. Uncheck the in-cluster option - the S3 specific fields stay there instead of going away.

https://www.loom.com/share/1cbe5fb5122b499797b41aeefbba8290

### Expected behavior
 The S3 specific fields should go away when unselecting In-cluster container registry.

**Comment by Pothulapati** [comment]
Verified that this still happens, and raised https://github.com/gitpod-io/gitpod/pull/12218
