### ISSUE TITLE
Bug Report: Multi-repo workspace "files changed" only factors in the `mainConfiguration` repo's changes

### ISSUE THREAD

**Issue by mickmister** [gitpod-io/gitpod#10253]
### Bug description

If I make changes to one of the `additionalRepositories`, the changes shown in Dashboard do not reflect the number of changes done to these repositories. Only changes to the `mainConfiguration` repo show in the Dashboard.

### Steps to reproduce

- Spin up a multi-repo workspace
- Make changes to one of the `additionalRepositories`
- Go to the Gitpod Dashboard
- Note that these changes are not shown in the count of changes

### Expected behavior

Reported changes should factor in all repositories in the workspace that have changes

### Example repository

https://github.com/mattermost/mattermost-gitpod-config

**Comment by geropl** [comment]
Moved to Team Workspace because of the reading of git status in multiple repositories.
