### ISSUE TITLE
Stop running workspaces on log out

### ISSUE THREAD

**Issue by randomir** [gitpod-io/gitpod#10261]
### Bug description

For security reasons, running workspaces should be stopped on GitPod log out.

### Steps to reproduce

1. Log in to gitpod.io
2. Start a workspace
3. Log out using the avatar dropdown on gitpod.io/workspaces
4. Verify the workspace is still running

### Expected behavior

When user explicitly logs out, they expect all active sessions to their GitPod account are terminated. Otherwise, the next user of the same machine would be able to access first user's private data (like GitHub token, environment variables, etc).

**Comment by pawlean** [comment]
Hey @randomir!

I'm unable to replicate this. When I open a workspace then log out from the dashboard and refresh the page for the workspace, it gives me this:

<img width="1429" alt="2022-05-26 at 11 10 47 - Google Chrome@2x" src="https://user-images.githubusercontent.com/17087373/170446794-62762573-a53a-4314-a78b-75feaee72766.png">

Can you verify that's what you see too?

**Comment by randomir** [comment]
@pawlean, that's correct, but I didn't say anything about refreshing the workspace. If you *don't refresh it*, you can use it until timeout (I suppose).

**Comment by pawlean** [comment]
@randomir I just tried it again without refreshing and see what you mean, thanks for reporting! 🙌 I'll make sure that the relevant team sees this.

**Comment by kylos101** [comment]
@pawlean this seems like it may be a webapp or IDE team concern. For now I am going to share with the webapp team to get their input.

For example, we could have server stop all running workspaces on [log out ](https://github.com/gitpod-io/gitpod/blob/3bec1f8be62122674a73516e6d5ff33313508e5f/components/server/src/user/user-controller.ts#L163-L185)(essentially doing garbage collection on the user's running regular workspaces), or, we could have the IDE check with server for session validity periodically, like as part of the [heartbeat](https://github.com/gitpod-io/gitpod/blob/43a41f2a65203fa2a40ff4648a25cf850e18a254/components/supervisor/frontend/src/index.ts#L234), and to stop the workspace if the session is no longer valid.

@geropl , wdyt?

**Comment by kylos101** [comment]
> @pawlean this seems like it may be a webapp or IDE team concern. For now I am going to share with the webapp team to get their input.
> 
> For example, we could have server stop all running workspaces on [log out ](https://github.com/gitpod-io/gitpod/blob/3bec1f8be62122674a73516e6d5ff33313508e5f/components/server/src/user/user-controller.ts#L163-L185)(essentially doing garbage collection on the user's running regular workspaces), or, we could have the IDE check with server for session validity periodically, like as part of the [heartbeat](https://github.com/gitpod-io/gitpod/blob/43a41f2a65203fa2a40ff4648a25cf850e18a254/components/supervisor/frontend/src/index.ts#L234), and to stop the workspace if the session is no longer valid.
> 
> @geropl , wdyt?

nvm, looks like it already made it to webapp :)

**Comment by charleswhchan** [comment]
Any updates on this issue?
