### ISSUE TITLE
[docs] Create a documentation for management of KOTS app via CLI

### ISSUE THREAD

**Issue by nandajavarma** [gitpod-io/gitpod#10272]
We should document the installation of Gitpod via KOTS CLI along with upgrade, maintenance etc. to ensure options for automation. Alongside, things like pushing images directly via CLI in airgapped seem to be much faster. We should clearly state this benefit.

Internal conversation [here](https://gitpod.slack.com/archives/C01KLC56NP7/p1653495657205969).

**Comment by lucasvaltl** [comment]
Step 1 should be to define what is worth documenting here.
