### ISSUE TITLE
MariaDB docker image fails to start on gitpod

### ISSUE THREAD

**Issue by Tasty213** [gitpod-io/gitpod#10287]
### Bug description

When you try and run the latest version of the MariaDB docker image on gitpod it fails with the error
```
2022-05-26 15:29:44+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.8.3+maria~jammy started.
2022-05-26 15:29:44+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
        command was: mariadbd --verbose --help --log-bin-index=/tmp/tmp.Sxk0V0vFe1
        Can't initialize timers
The terminal process "/usr/bin/bash '-c', 'docker run --rm -it  -p 3306:3306/tcp mariadb:latest'" terminated with exit code: 1.
```
This is my first time using gitpod so I don't know if worked previously or if mariadb has never worked on gitpod.

### Steps to reproduce

Open new gitpod environment and run
```
docker run --rm -it  -p 3306:3306/tcp mariadb:lates
```

### Workspace affected

tasty213-gryphongames-zpvyf2760l3

### Expected behavior

MariaDB container to start normally

**Comment by axonasif** [comment]
This seems to be an issue on the MariaDB side.
You will have to use an old version instead of `latest`.
See https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1135889824

Feel free to close the issue if we're done here.
