### ISSUE TITLE
Error: Request createWorkspace failed with message: 14 UNAVAILABLE: TCP Read failed

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1028]
**Describe the bug**

![image](https://user-images.githubusercontent.com/50386709/71314145-c44de900-2408-11ea-9aa3-b80920ee0836.png)

**To Reproduce**
try opening ws
**Expected behavior**
workspace build
**Additional Information**
OS: ChromeOS

**Comment by geropl** [comment]
Hi @JesterOrNot ,

thanks for reporting. We seems to have sporadic connection issues between internal services. They never last longer then a couple of seconds, but that's enough to break some requests (like yours).

We will follow up after the holidays. Until then, please retry in such cases.

**Comment by geropl** [comment]
Outdated.
