### ISSUE TITLE
Hide Feedback Form for self-hosted

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#10296]
Self-hosted are not sending tracking events, therefore we should hide the feedback form from those users.

**Comment by laushinka** [comment]
@jldec @gtsiolis Do we want the Help link to go back to the top nav for self-hosted? Easiest would be to keep it under the profile 🙏🏽

**Comment by gtsiolis** [comment]
@laushinka I'd keep the structure as is (keep it under the Profile menu) as :a: the other existing links provide the visual balance needed and :b: build a foundation for future changes like https://github.com/gitpod-io/gitpod/issues/8385 which could probably move also the Docs link or introduce a second Help menu next to the User menu.

Thanks for taking action by opening #10297, @laushinka! ✨
