### ISSUE TITLE
Point to Community License in replicated license upload page

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10306]
## Is your feature request related to a problem? Please describe
The page during the Gitpod self-hosted-installation that asks you to upload a license file should mention where to find the free community license. Right now, unless you read out public docs very carefully, you won’t know how to get past the license page.

## Describe the behaviour you'd like
Point to where you can get a community license in the upload license page

## Context
Originally raised [here](https://gitpod.slack.com/archives/C01KLC56NP7/p1653658512162129) (internal)

**Comment by gtsiolis** [comment]
Re-posting from a [relevant discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1651768020798549?thread_ts=1651764252.754309&cid=C01KLC56NP7) (internal) in case it sounds helpful or possible:

> Could we include the community license in the source code so that there’s no need to add any license at all when installing by default? The current links to the community license seem a bit hard to discover, no?

**Comment by corneliusludmann** [comment]
I'll close this issue because this is not possible in KOTS.
