### ISSUE TITLE
Failing to build Image

### ISSUE THREAD

**Issue by AwsSG** [gitpod-io/gitpod#10303]
### Bug description

When I try to create a new workspace for my repository, the page get stuck in "Building Image" and the log does not show anything. It stays like this for about 10 minutes, eventually it will show this message "Error: headless task failed: Exit status 1"

I tried several times, always the same result

### Steps to reproduce

Create new repository by importing an existing one. When finished, click Gitpod button on the page of the repository. Same result if attempt to start new workspace from Gitpod directly and pasting the link to the repo, or adding "gitpod.io/#" in the beginning of the url.

### Workspace affected

https://gitpod.io/#https://github.com/AwsSG/flask-withnosqldb

### Expected behavior

I should see the workspace open and I can write code

### Example repository

https://github.com/AwsSG/flask-withnosqldb

### Anything else?

I tried to create a new workspace by creating a new blank repository, this seem to work fine.

**Comment by kylos101** [comment]
👋 @AwsSG are you still having this trouble? I am unable to reach this repo you shared in this issue (I get a 404 error). 

We fixed an issue recently where image build and prebuilds were not streaming correctly as a heads up.

Also, there is [this issue](https://github.com/gitpod-io/gitpod/issues/7147), but, you don't appear to be hitting it.

I am going to close this issue for now. If it is still an issue, please let us know, and we'll happily reopen.

**Comment by AwsSG** [comment]
Hi kyle,
I tried again but still no luck :(
This is what I'm getting 

Hope that helps.
Thanks,Aws    On Tuesday, June 7, 2022, 04:34:15 AM GMT+1, Kyle Brennan ***@***.***> wrote:  
 
 


 👋 @AwsSG are you still having this trouble? I am unable to reach this repo you shared in this issue (I get a 404 error).

We fixed an issue recently where image build and prebuilds were not streaming correctly as a heads up.

Also, there is this issue, but, you don't appear to be hitting it.

I am going to close this issue for now. If it is still an issue, please let us know, and we'll happily reopen.

**Comment by axonasif** [comment]
@AwsSG can you please reply from Github? I can't see if you posted a screenshot (since you're replying from email I assume)

**Comment by AwsSG** [comment]
Yes I replied in email, I don't actually know how to get back to the issue I created 😕
Sorry

Sent from Yahoo Mail on Android 
 
  On Wed, 8 Jun 2022 at 7:27 PM, ***@***.***> wrote:   


@AwsSG can you please reply from Github? I can't see if you posted a screenshot (since you're replying from email I assume)

**Comment by AwsSG** [comment]
Still having the issue, any updates ?
