### ISSUE TITLE
Add missing margin on the browser extension button when viewing a file in GitHub 

### ISSUE THREAD

**Issue by shashankpatil125** [gitpod-io/gitpod#10301]
### Bug description

when we open any git repository code then the margining of gitpod is changed it is shown in picture 
<img width="204" alt="image" src="https://user-images.githubusercontent.com/67343395/170694809-824b935f-9e1c-4a1a-8954-19567ad22122.png">

### Steps to reproduce

1. open github 
2. open any repository
<img width="685" alt="image" src="https://user-images.githubusercontent.com/67343395/170695382-c75a3e75-fb68-4a49-8fc1-592edfaf5e8c.png">

3. open any typed code
<img width="920" alt="image" src="https://user-images.githubusercontent.com/67343395/170695501-88a200d9-641c-4ead-86ac-70545dc401af.png">

4. see the gitpod button 
<img width="193" alt="image" src="https://user-images.githubusercontent.com/67343395/170695526-3214df8a-28f3-4b14-9c07-3b399ec7b700.png">

### Expected behavior

when we open any repo then any code then the gitpod button's margin need to give margin

**Comment by gtsiolis** [comment]
Thanks for catching and noticing this, @shashankpatil125! I've added some labels to help with the issue visibility and marked this as a **[~good-first-](https://github.com/gitpod-io/gitpod/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue)**issue as this could be relatively simple to fix in **[gitpod-io/browser-extension](https://github.com/gitpod-io/browser-extension)**.

**Comment by kunalchhabra37** [comment]
Hi I want to Contribute to this issue. Can You Please assign it to me

**Comment by jwpjrdev** [comment]
This issue really belongs in https://github.com/gitpod-io/browser-extension

**Comment by kunalchhabra37** [comment]
@gtsiolis I have created PR for this Issue in https://github.com/gitpod-io/browser-extension where the Issue actually belongs to. You can review my PR https://github.com/gitpod-io/browser-extension/pull/63
