### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by ergouliang** [gitpod-io/gitpod#1030]
ERROR: Package 'pyppeteer' requires a different Python: 2.7.16 not in '>=3.5'

**Comment by JesterOrNot** [comment]
can you provide the repository in question?

**Comment by ergouliang** [comment]
acb34708-b3d8-4cd2-be6f-12481fae2a3a
Can you provide this？

**Comment by jankeromnes** [comment]
Hi @ergouliang, Gitpod ships with both Python 2 _and_ Python 3 by default, using `pyenv`.

Python 2 is currently the default, but you can change the default by running this in your Gitpod terminal:

```
pyenv local 3.7.4
```

This will create a `.python-version` file, and switch the default `python` command to Python 3.

To make this change permanent, please add + commit + push the `.python-version` file to your repository.

**Comment by svenefftinge** [comment]
Did you try using the command `python3` (resp. `pip3`) instead?

**Comment by JesterOrNot** [comment]
why not add something to the .gitpod.yml script to do this during a prebuild or on start to avoid this

**Comment by jankeromnes** [comment]
Using `python3` / `pip3`, and/or using `pyenv local 3.7.4`, and or adding a `.python-version` file to your repository should fix this problem.

@ergouliang Please comment here again if your problem wasn't solved.
