### ISSUE TITLE
New workspace based on a Prebuild not recovering enviroment

### ISSUE THREAD

**Issue by WilianZilv** [gitpod-io/gitpod#10310]
### Bug description

Using a new workspace based on a prebuild simply doesnt load the previously built enviroment.

![Captura de tela 2022-05-27 204015](https://user-images.githubusercontent.com/28124804/170800523-b4eeac6b-c6ec-4306-bd83-0ebdea3a11d2.png)

### Steps to reproduce

Fork my sample project https://github.com/WilianZilv/gitpod-test;
Go to https://gitpod.io/projects and create a new project based on the foked repo;
For the first time it will initialize everything and work as expected;
Delete the current workspace;
Create a new workspace based on the prebuild;

### Workspace affected

Every workspace based on a prebuild

### Expected behavior

When creating a new workspace based on a prebuild. I expect to load the previously built enviroment.

### Example repository

https://github.com/WilianZilv/gitpod-test

**Comment by geropl** [comment]
@WilianZilv Gitpod does not store env vars bceause we're proponents of "dev environment as code".
Did you look into move that environment variable into one of these locations:
 - Dockerfile
 - .gitpod.yaml
    ![Image](https://user-images.githubusercontent.com/32448529/180228033-4987121d-8ac8-4e52-8670-0a6edfc1d9d3.png)
 - Project Env var
![Image](https://user-images.githubusercontent.com/32448529/180228255-9ef45c55-752c-4daf-b1d5-1c7ae653391c.png)
