### ISSUE TITLE
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 57302581248, capacity: 57639522304 Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by diegocassandri** [gitpod-io/gitpod#1032]
**Describe the bug**
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 57302581248, capacity: 57639522304
Please file an issue if you think this is a bug.

**To Reproduce**
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 57302581248, capacity: 57639522304
Please file an issue if you think this is a bug.

**Expected behavior**
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 57302581248, capacity: 57639522304
Please file an issue if you think this is a bug.

**Additional Information**

https://e51103e4-0e89-4c03-8580-d260476b553a.ws-us02.gitpod.io/

/start: started workspace instance: 2333f40f-fb2b-4ed0-bb9f-800deaa99c0c

**Comment by JesterOrNot** [comment]
Probably a Kubernetes issue @svenefftinge can you take a look?

**Comment by svenefftinge** [comment]
It is corner case in the scheduler logic, that we believe to have fixed in staging already. Will land in production next week.

**Comment by diegocassandri** [comment]
It's solved. Thanks.

**Comment by Madeline8** [comment]
Oh, no! Something went wrong!
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 3435973837, used: 65865462583, capacity: 66388008960

I am not unable to submit my project, deadline tomorrow :(((

**Comment by axonasif** [comment]
@Madeline8 it should go away by itself on retrying, our workspace team is investigating.

**Comment by MouniR-123** [comment]
Pod Node didn't have enough resource: memory, requested: 8589934592, used: 10903093248, capacity: 13208985600
kubernetes version: 1.22.6 what could be the reason?
