### ISSUE TITLE
Implement usage APIs

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#10325]
Depends on https://github.com/gitpod-io/gitpod/issues/10324.

With the API definition in place, implement the API. Recommended approach:

 - [x] First define a stub API which returns mocked out data
 - [x] Second, implement necessary access controls and restrictions (including feature flag check)
 - [x] Third, implement actual logic for data retrieval.
 - [ ] Add a "time range filter" parameter

**Comment by geropl** [comment]
Dropping work here, as the "wiring" between `dashboard`, `server` and `usage` is done. Leaving for @andrew-farries to pick it up. :muscle:
