### ISSUE TITLE
[content-service] workspace backup cannot be restored because it's larger than the workspace

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#10329]
### Bug description

[A user reported](https://discord.com/channels/816244985187008514/839379835662368768/979364591958110269) being unable to start a workspace that was previously backed up.

The backup tar file was 27GB, the size of the extracted contents was 32GB, which caused content init to fail and the workspace to not start.

![image](https://user-images.githubusercontent.com/1272076/170892548-8da56f29-e934-4273-b480-566f52300220.png)

[Related log entry.](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-05-26T12:50:06Z;query=resource.type%3D%22k8s_container%22%20AND%0Alog_id%2528%22stderr%22%2529%20AND%0Aseverity%3E%3DERROR%0A%22go8zjeyqjgm%22%0Atimestamp%3D%222022-05-26T12:50:06Z%22%0AinsertId%3D%22s5ewckfmr7wytx2d%22%0Atimestamp%3D%222022-05-26T12:50:06Z%22%0AinsertId%3D%22s5ewckfmr7wytx2d%22;timeRange=2022-05-26T09:50:06.001Z%2F2022-05-26T12:50:06.001Z?project=workspace-clusters)

[Related log entry for the last 7 days as of May 31.](https://cloudlogging.app.goo.gl/CWMGdJ7W2KZaczTWA)

### Steps to reproduce

From a `workspace-preview` instance
For the `ws-manager` config map, set the storage limit in the default workspaceClass for container to `1G` like so:

```json
 "workspaceClass": {
      "default": {
        "container": {
          "requests": {
            "cpu": "1m",
            "memory": "3.2Gi",
            "ephemeral-storage": "5Gi"
          },
          "limits": {
            "cpu": "6",
            "memory": "12Gi",
            "ephemeral-storage": "10Gi",
            "storage": "1G"
          }
        },
```
Start a workspace
Add content to its `/workspace` that is greater than the `1G` limit, like `1100MB`
Stop the workspace, it should backup
Try to restart the workspace, it should fail starting during the content init, because the extract contents are larger than the workspace limit

### Workspace affected

mrkldshv-deno-go8zjeyqjgm

### Expected behavior

Content we successfully backup must be able to be successfully restored.

### Example repository

n/a

### Anything else?

There are two things we must do:
1. Assert (and potentially fix) [quota enforcement](https://github.com/gitpod-io/gitpod/issues/10329#issuecomment-1140749433) for `/workspace`.
2. Stop `dockerd` prior to beginning content backup. This is true both for regular workspaces but also prebuild workspaces.

**Comment by aledbf** [comment]
> The backup tar file was 27GB, the size of the extracted contents was 32GB, which caused content init to fail and the workspace to not start.

If the decompressed size is 32GB then it means the `/workspace` quota was not enforced

**Comment by utam0k** [comment]
Why does `dockerd` relate to this issue? The problem could be reproduced without dockerd.

> Stop dockerd prior to beginning content backup. This is true both for regular workspaces but also prebuild workspaces.

**Comment by kylos101** [comment]
> Why does `dockerd` relate to this issue? The problem could be reproduced without dockerd.
> 
> > Stop dockerd prior to beginning content backup. This is true both for regular workspaces but also prebuild workspaces.

The thought was that dockerd (and containers) may still be running, and writing to `/workspace` during the backup, and during that time, perhaps the quota isn't being honored?

**Comment by utam0k** [comment]
it happened again 😭

**Comment by atduarte** [comment]
As a first step, could we improve the error message to be more user-friendly? E.g. "Could not load prebuild as it is larger than the available workspace storage" / "Could not load workspace backup as it is larger than the available workspace storage".

**Comment by utam0k** [comment]
> As a first step, could we improve the error message to be more user-friendly? E.g. "Could not load prebuild as it is larger than the available workspace storage" / "Could not load workspace backup as it is larger than the available workspace storage".

@atduarte Good point. Thank you. But we talked with @kylos101 that the increase in size when content is restored was not reproduced by me. This actually indicates that the user's content does not exceed the limit.
> The backup tar file was 27GB, the size of the extracted contents was 32GB, which caused content init to fail and the workspace to not start.

**Comment by utam0k** [comment]
But I found one cause this issue brings. But maybe there are another reasons. Anyway I'm trying to cope with this case.
https://gist.github.com/utam0k/7d93ebb513801a597c941f05b030a51e
