### ISSUE TITLE
Write usage report into test-mode in Stripe

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#10322]
Depends on https://github.com/gitpod-io/gitpod/issues/10320

We'd like to start writing our usage report into Stripe (in test-mode) to get a good feel for the flow, consistency and any issues arising from this.

For team (gitpod), start updating the invoice line items based on the report produced.

**Comment by andrew-farries** [comment]
Done by https://github.com/gitpod-io/gitpod/pull/10713
