### ISSUE TITLE
Change Linux date in Gitpod

### ISSUE THREAD

**Issue by mouse484** [gitpod-io/gitpod#1033]
I tried to set the Linux date,
Could not be done from command line.

Maybe can do it with Docker file (not tried)

It would be nice to change this dynamically to browser time

**Comment by Kreyren** [comment]
Why do you need to change the time?

> Maybe can do it with Docker file (not tried)
Cannot be changed using docker file (https://gitpod.io/#https://github.com/Kreyren/gitpod-tests1/tree/2)

**Comment by mouse484** [comment]
> Why do you need to change the time?
Because the console log time is different from the local environment

Quite inconvenient

**Comment by svenefftinge** [comment]
In what situations is that inconvenient? After all this is how web applications run everywhere, i.e. it is super normal that the server side time differs from the client side. It includes the timezone so you can translate to UTC or so and should have the same.

**Comment by mouse484** [comment]
That's right,
However, it is a problem if the time to output to the log is different.


![image](https://user-images.githubusercontent.com/38714187/71555001-c7c91c00-2a69-11ea-895c-dca750ad91c9.png)
![image](https://user-images.githubusercontent.com/38714187/71554999-be3fb400-2a69-11ea-8e13-341e8131568b.png)

**Comment by svenefftinge** [comment]
So you are joining frontend and backend logs? As said above, you should use some timezone agnostic format and then pretty print in one place (i.e. backend).

**Comment by RDIL** [comment]
I think you can just do:
```dockerfile
ENV tz Your/Timezone
```
To make it all match up.
