### ISSUE TITLE
[agent-smith] improve performance

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#10331]
## Is your feature request related to a problem? Please describe

The # of cores used is [often high](https://grafana.gitpod.io/d/agent-smith/gitpod-component-agent-smith?orgId=1&from=1653609600000&to=1653695999000&var-cluster=us46&var-node=All&var-pod=All&var-datasource=VictoriaMetrics&viewPanel=2) and we believe this might be one of the contributing causes for disconnects in the XL clusters. Not as high as [ws-daemon](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&from=1653609600000&to=1653695999000&var-cluster=us46&var-node=All&var-pod=All&var-grpc_method=All&var-datasource=VictoriaMetrics&viewPanel=2), but is higher than [registry-facade](https://grafana.gitpod.io/d/registry-facade/gitpod-component-registry-facade?orgId=1&var-cluster=us46&var-node=All&var-pod=All&var-grpc_method=All&var-datasource=VictoriaMetrics&from=1653609600000&to=1653695999000&viewPanel=2). In other words, it is taking CPU that workspaces could be using. Why? Please [profile](https://www.notion.so/gitpod/Profiling-Go-Code-a0de0ddcb34a48ac9ebee7fa4f0faf52) `agent-smith`, and then check to see if there are opportunities to optimize.

## Describe the behaviour you'd like

Max core usage is consistently less. Perhaps less than 2.5?

## Describe alternatives you've considered

Less average and max memory used would be ideal, too.

## Additional context

Tuning done to improve ws-daemon performance. [[1](https://github.com/gitpod-io/gitpod/pull/10274)][[2](https://github.com/gitpod-io/gitpod/pull/9836)]

**Comment by atduarte** [comment]
Updated the description to reflect what triggered us to work on this: "we believe this might be one of the contributing causes for disconnects in the XL clusters".

Agent-smith has a lot more work to do on Standard nodes as this have more workspaces running. When looking at the XL clusters at the times of the issues, I don't see high CPU usage: https://grafana.gitpod.io/d/agent-smith/gitpod-component-agent-smith?orgId=1&from=1653552000000&to=1653573600000&var-cluster=us44xl&var-node=All&var-pod=All&var-datasource=VictoriaMetrics&viewPanel=2

**Comment by kylos101** [comment]
Resolved in #10356
