### ISSUE TITLE
Opening a workspace fails with git: invalid index-pack output

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#10338]
### Bug description

<img width="572" alt="Screenshot 2022-05-30 at 10 11 09" src="https://user-images.githubusercontent.com/1419286/170952063-b1e9bbfa-c64c-45fb-a56b-0f79af427c4a.png">

Running on `ws-eu44xl` clusters.

### Steps to reproduce

Opening a workspace from a branch on gitpod-io/gitpod

### Workspace affected

gitpodio-gitpod-zjf9pfmr85y

**Comment by easyCZ** [comment]
Possibly related to https://github.com/gitpod-io/gitpod/issues/9280

**Comment by kylos101** [comment]
@utam0k may I ask you to search the logs for this issue, to see how often it has happened since we stopped using `gen44`? For now, I am going to remove this from our scheduled work. Based on your findings, and the frequency for this error, we may want to reschedule.

**Comment by utam0k** [comment]
@kylos101 This error still continues to happen.
https://cloudlogging.app.goo.gl/2pCbVrPXNHJgS54i7

It appears that both `fetch` and `clone` can get this failure. It seems that the git command has problems with HTTP/2 when retrieving information from larger repositories.

**Comment by kylos101** [comment]
Good catch, scheduled!

![image](https://user-images.githubusercontent.com/1272076/172847335-990fca9b-c87b-40ba-b3a0-10cff3985466.png)

**Comment by utam0k** [comment]
Fixed by https://github.com/gitpod-io/gitpod/pull/11400
