### ISSUE TITLE
gp cli analytics

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10349]
Understand usage of the `gp` cli, it's commands and flags. 

- [ ] Call Segment directly instead of using Server

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/gitpod/issues/9930

**Comment by akosyakov** [comment]
For the start I would like to have some simple monitoring dashboard which show:
- frequencies of CLI commands
- error rates of CLI commands
- latencies of CLI commands

I don't think we need to collect analytics yet on concrete flags, arguments, errors and so on. Monitoring dashboard should show us some usage patterns for beginning.

**Comment by andreafalzetti** [comment]
I plan to look into this during this week. I will have a chat with @iQQBot tomorrow (14.06) to discuss the approach.

**Comment by andreafalzetti** [comment]
I will be picking up this task now, since I am on-call. I've started a chat with @iQQBot to discuss the approach and technical implementation.

cc @akosyakov
