### ISSUE TITLE
Self-Host http gitpod can't create workspace

### ISSUE THREAD

**Issue by 502647092** [gitpod-io/gitpod#1034]
**Describe the bug**

```
Sorry, something went wrong 😓
Error: Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: Error response from daemon: Get https://reg.gitpod.miaowoo.cc/v2/: dial tcp 52.155.117.207:443: connect: connection refused
```

**To Reproduce**

- install gitpod at k8s
- open http://gitpod.miaowoo.cc/#https://github.com/eclipse-theia/theia
- report error and it get info from https

**Expected behavior**
**Additional Information**

**Comment by meysholdt** [comment]
Hi @502647092 !

can you please check that 
1. you have [https enabled](https://www.gitpod.io/docs/self-hosted/latest/install/34_https_certs/) for your installation
2. you have the [built-in docker-registry](https://www.gitpod.io/docs/self-hosted/latest/install/35_docker_registry/) enabled. you can verify this by running `kubectl get pods`. There should be a pod named "registry".
