### ISSUE TITLE
Configurating NGINX Ingress on Gitpod Self Hosted?

### ISSUE THREAD

**Issue by diessetechnology** [gitpod-io/gitpod#1035]
Hello, I'm trying Gitpod Self Hosted...
I have a single node vanilla k8s cluster and I have deployed Gitpod Self Hosted successfully without errors...
but now I'm confused because no NGINX Ingress has been generated (unlike Eclipse Che, that cloud ide generated automatically an ingress)...
Assuming that the domain is called "mygitpoddomain.com" (naturally not my real domain), and I have correctly assigned a wildcard certificate on *.ws.mygitpoddomain.com and *.mygitpoddomain.com...how can I create the right NGINX Ingress?

I have opened the same issue on gitpod-io/self-hosted repo

**Comment by meysholdt** [comment]
hi @diessetechnology!

Gitpod self-hosted creates a Kubernetes [Service of type LoadBalancer](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#finding-your-ip-address). It's named 'proxy' and you should be able to see it when running `kubectl get services`.

See [here](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#finding-your-ip-address) for how to discover the IP address that got assigned to your LoadBalancer. That's the IP address your DNS should be pointing to. 

It's true that Gitpod self-hosted so far does not create a resource of type `ingress`.

Let me know if this helps to get it running. In case you have more questions or feedback... don't hesitate to ask :)

**Comment by diessetechnology** [comment]
No Load Balancer, I have settled the property gitpod.components.proxy.loadBalancerIP to my ip
(Is a single-node k8s cluster on a dedicated server)...
I need to know the right ingress yaml for a domain....i no have clue on the ingress to create, and the documentation helped very little.

**Comment by meysholdt** [comment]
Can you explain what you mean by "no Load Balancer"? Can your Kubernetes cluster not create services of type LoadBalancer?

What's the output when you run `kubectl get services`? It should look something like this: 
```
NAME                                            TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S) 
dashboard                                       ClusterIP      10.0.1.1     <none>         3001/TCP
db                                              ClusterIP      10.0.1.2     <none>         3306/TCP
image-builder                                   ClusterIP      10.0.1.3      <none>         8080/TCP
proxy                                           LoadBalancer   10.0.10.59    34.83.1.1   80:31080/TCP,443:31443/TCP 
```

The `EXTERNAL-IP` of services with `NAME` `proxy` (here: `34.83.1.1`) should be accessible publicly and without ingress.

Let me know if I'm missing something.

**Comment by diessetechnology** [comment]
No Load Balancer because i have a single node cluster on a dedicated server,so not on GCP,AWS,Azure or similar.
So I can't create a LoadBalancer...I have setted the property gitpod.components.proxy.loadBalancerIP to my IP,but the problem is that.
I have deployed successful many services without problem in this way...either Eclipse Che.
I explicitly need to access via Ingress, so how can I create the right ingress?

**Comment by lucky4ever2** [comment]
I have the same problem. I have a self hosted rancher without a cloud provider. Therefore the proxy cannot create a load balancer service.
I changed the serviceType to "NodePort" and created an ingress behind it at Port 80. But unfortunately I get the default nginx page displayed: "Welcome to nginx!" (https://gitpod.domain.de)

My Helm Chart Config:
hostname=gitpod.domain.de
certificatesSecret.secretName=gitpod-secret-ssl
ingressMode=pathAndHost
components.proxy.serviceType=NodePort
minio.persistence.size=50Gi
components.wsDaemon.containerRuntime.nodeRoots[0]=/var/lib
components.wsDaemon.containerRuntime.nodeRoots[1]=/run/containerd/io.containerd.runtime.v1.linux/moby
defaults.dnsPolicy=ClusterFirstWithHostNet

And I don't know if that is related, but the ws-manager-bridge shows this error: 
`Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778`
