### ISSUE TITLE
KOTS Performing Automatic Updates Even When Not Configured Too

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#10353]
### Bug description

KOTS appears to be performing automatic updates to my Gitpod instance even when it is not configured too. This results in a broken install since I use `ClusterIP` and not `LoadBalancer`. This in turn results in an "infinite loop" of attempted rollbacks.

<img width="518" alt="Screen Shot 2022-05-30 at 08 25 43AM" src="https://user-images.githubusercontent.com/405585/171018176-ce152ac3-7aa3-43a5-be0a-74c733a30d15.png">

```
18      	Fri May 27 12:45:09 2022	deployed        	gitpod-kots-1.0.0	main.3384  	Upgrade complete
19      	Sun May 29 15:10:29 2022	failed          	gitpod-kots-1.0.0	main.3384  	Upgrade "gitpod" failed: timed out waiting for the condition
20      	Sun May 29 15:16:26 2022	failed          	gitpod-kots-1.0.0	main.3384  	Release "gitpod" failed: timed out waiting for the condition
21      	Sun May 29 15:22:12 2022	pending-rollback	gitpod-kots-1.0.0	main.3384  	Rollback to 19
```

Revision 18 was a manual update I performed on Friday, then on Sunday something seems to have happened where it tried updating itself? I ran a manual rollback to 18 myself this morning to resolve the issue.

I faintly remember this happening last Sunday too, is there some sort of automation we have in place to run on Sundays?

### Steps to reproduce

1. Spin up a KOTS instance of Gitpod.
2. You may need to wait until Sunday (afternoon) for you to observe that some sort of automation attempted to take place.
3. You can review the helm history - `helm history gitpod --namespace gitpod`.

**Comment by Seenox** [comment]
@jimmybrancaccio not directly related to your issue. However, since I also use `ClusterIP` and had a similar issue, you might be interested in using https://github.com/gitpod-io/gitpod/pull/10537 to solve (part of) your issue.
