### ISSUE TITLE
Windows and macOS workspaces

### ISSUE THREAD

**Issue by florisvdg** [gitpod-io/gitpod#10363]
What's your vision on Gitpod workspaces in Windows and macOS runners?

Paid plans only of course – but is it even on the roadmap? Especially Windows would be quite the 'shut-up-and-take-my-money' feature.

**Comment by atduarte** [comment]
Hey @florisvdg! Thanks for opening the issue, it's helpful for me to learn that some people are interested on it 🙂 We are only focused on x86 Linux for now and have no plans to change that, for now.

**Comment by brillout** [comment]
> We are only focused on x86 Linux for now

Is that still the case?

**Comment by samuelstroschein** [comment]
@brillout haha do you need to debug on windows machines too and thought gitpod could be an easy windows virtual machine?

**Comment by brillout** [comment]
Yea exactly for OSS devs it would be a boon to be able to spin up a windows env. I (mis-)use GitHub's workflows in the meantime but I should probably setup a windows personal laptop at some point :)
