### ISSUE TITLE
Gitpod button showing inside the dependabot alert

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#10360]
### Bug description

Gitpod button showing on the wrong place.

<img width="1204" alt="Screen Shot 2022-05-30 at 12 44 48 PM" src="https://user-images.githubusercontent.com/426452/171034116-7d5135e8-6659-4c34-8136-88e66685031c.png">

### Steps to reproduce

- Install the gitpod extension
- Go to this link: https://github.com/breatheco-de/app/blob/main/src/pages/thank-you.jsx#L25

### Workspace affected

none

### Expected behavior

The button should show up on button bar right below the alert.
![gitpod](https://user-images.githubusercontent.com/426452/171034388-6e862b7e-2736-42ac-a12e-2d0997543660.png)

### Anything else?

I'm not sure how important this bug is, but I thought it was a good idea to document it.

**Comment by gtsiolis** [comment]
Thanks, @alesanchezr! Closing this in favor of https://github.com/gitpod-io/gitpod/issues/8171.

**Comment by alesanchezr** [comment]
I still see it inside the dependabot alert (even after re-installing the plugin and updating brave browser).

[Version 1.38.119 Chromium: 101.0.4951.67 (Official Build) (x86_64)](https://brave.com/latest/)
