### ISSUE TITLE
[setup] Toggle for config suggestion

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1036]
Please make it so there is a switch in user settings that makes it so you can toggle the this project could use a configuration popup - it’s super annoying

**Comment by Kreyren** [comment]
I also find these suggestions annoying assuming that it outputs the same thing over and over again.

**Comment by svenefftinge** [comment]
Do you suggest to do this on a per project or per user level?
Can you explain in what situations you don't want a .gitpod.yml on a project?

**Comment by RDIL** [comment]
Per user, and I do want the file but I don't need your dialog to create it

**Comment by svenefftinge** [comment]
This has landed in production.
If you dismiss the prompt, another prompt asks if you want to get asked every again.
