### ISSUE TITLE
[previewctl] Configure shell autocompletion in the workspace image

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#10389]
After spending more time than I'm proud to admit, I decided to give up and open an issue for this.

previewctl shell completion can be configured by running `source <(previewctl completion bash)`, however, it only adds to the current terminal. We should update our workspace image to build previewctl and also add the completion command to `~/.bashrc`

**Comment by meysholdt** [comment]
Maybe this helps to find a solution:
We already have some places where we add completion-config to the `~/.bashrc` for exactly the reason you mention:
https://github.com/gitpod-io/gitpod/blob/0f406c4468f475d285a525b978e37d77012fb68f/dev/image/Dockerfile#L140
https://github.com/gitpod-io/gitpod/blob/0f406c4468f475d285a525b978e37d77012fb68f/dev/image/Dockerfile#L22

**Comment by ArthurSens** [comment]
The problem is that before this step we need to build the binary from somewhere, that's where I failed 😕
