### ISSUE TITLE
Add metrics to be able to identify leaking prebuild

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#10383]
Came up in the context of:
 - https://github.com/gitpod-io/gitpod/issues/8195: prebuilds are stuck in running because of an (suspected) supervisor bug (@AlexTugarev please fill in issue id HERE once created :pray: )
 - https://github.com/gitpod-io/gitpod/issues/9395#issuecomment-1142058473: prebuilds are stuck in `queued` for multiple reasons

First idea:
 - have counters on "queued" ([WorkspaceFactory](https://github.com/gitpod-io/gitpod/blob/81a79af4ec3f9a5de53f40370ab455bf8a054c85/components/server/ee/src/workspace/workspace-factory.ts#L168-L178) in `server`), "running" and end states ("available", "failed", in [bridge](https://github.com/gitpod-io/gitpod/blob/bb0a42a48c39ab6c1457d0624518415a2c3be596/components/ws-manager-bridge/ee/src/bridge.ts#L108), while making sure to only capture flanks :+1: )
 - subtracting those should give a fairly good trend

**Comment by geropl** [comment]
metrics:
 - a) prebuild_state_counter { state }
 - b) prebuild_started_counter + prebuild_finished_counter
 - c) ...?

**Comment by laushinka** [comment]
Just noticed that we have [`prebuild_queue_size`](https://github.com/gitpod-io/gitpod/blob/aafb99b6ba90658679ee9c5febe762881cb71c59/components/server/src/workspace/client-data-prometheus-adapter.ts#L31) metric which is not used anywhere it seems.
