### ISSUE TITLE
bug: connection diposed

### ISSUE THREAD

**Issue by vigneshyaadav27** [gitpod-io/gitpod#1038]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by JesterOrNot** [comment]
How stable is your WiFi? This error occurs when the web-socket connections go out?

**Comment by JesterOrNot** [comment]
Closing this as this issue is known however if this issue reoccurs or you have other questions then please feel to either file a separate issue or reopen this issue 👍
