### ISSUE TITLE
allow image-builder-mk3 to have multiple pull secrets

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#10396]
> For a full explanation of the problem, see [this comment in 10298](https://github.com/gitpod-io/gitpod/issues/10298#issuecomment-1141915258)

The image-builder-mk3 requires support for multiple pull secrets to maintain parity with the `imagePullSecrets` in Kubernetes's pod spec.

Suggested approach
 - add in `pullSecrets` as an array of strings (can remove `pullSecret` in a future PR, but out of scope for this ticket)
 - usage of these `pullSecrets` then becomes "loop through the secrets, only failing when all have failed"

**Comment by atduarte** [comment]
@kylos101 how much effort would you say this is?
