### ISSUE TITLE
bug: gitpod needs adaptation for GOPATH

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1039]
### Describe the bug

Using https://github.com/Kreyren/gitpod-tests1/tree/user with `USER gitpod` (https://github.com/Kreyren/gitpod-tests1/blob/06f7f1c7bc002a3a30a092bd8cb26ab2ac2bf443/.gitpod.Dockerfile#L34) does not perform the requested action on the gitpod user (Installing `checkmake` during prebuild)

### To Reproduce

Open https://gitpod.io/#https://github.com/Kreyren/gitpod-tests1/tree/user and check if `checkmake` is executable in the terminal (it shoudn't be even when the install process was performed on gitpod user)

### Expected behavior

Install `checkmake` on the gitpod environment during prebuild without the use of `init:` in the `.gitpod.yml` which unexpectedly runs on runtime and is not cached

### Additional note

Performing the installation of checkmake (https://github.com/Kreyren/gitpod-tests1/blob/user/.gitpod.Dockerfile#L35) once the gitpod is built makes the `checkmake` working as expected assuming dependencies installed

**Comment by 32leaves** [comment]
At workspace startup we mount a volume in `/workspace` which means that anything under `/workspace` in the Docker image will be shadowed. This is most likely the reason that you're not seeing checkmate installed once the workspace is open.

If installed somewhere else, i.e. `GOPATH=/opt/go` then it works.

**Comment by Kreyren** [comment]
@32leaves Exporting GOPATH works, but it has more unexpected issues

<img width="559" alt="image" src="https://user-images.githubusercontent.com/11302521/71589808-7763c400-2b26-11ea-8371-4eec1bff263a.png">

Seems to export wrong permission for the gitpod user
<img width="582" alt="image" src="https://user-images.githubusercontent.com/11302521/71589890-daedf180-2b26-11ea-9e40-5906cf1fc0d3.png">


Or i assume that gitpod already cached this with a root permission?

**Comment by svenefftinge** [comment]
For the initial issue, Chris' answer is the reason. 
The second problem is caused by how you install the npm package.

You need to do that as `USER gitpod` and you should pass the -g option (to make it a global install).
e.g.
```
USER gitpod
# Install Markdownlint (https://github.com/DavidAnson/markdownlint)
RUN npm install markdownlint -g
```

should work.

**Comment by Kreyren** [comment]
Using https://gitpod.io/#https://github.com/Kreyren/gitpod-tests1/tree/32e6c915fbb5b235593470c8ff44aa25cf391406 with Dockerfile set as:
```Dockerfile
# Install Markdownlint (https://github.com/DavidAnson/markdownlint)
RUN npm install markdownlint -g

## Get linting for Makefile
# Get dependencies
RUN apt install -y golang pandoc
RUN mkdir /opt/go
RUN chown gitpod:gitpod /opt/go
RUN chown -R gitpod:gitpod /home/gitpod/.npm/_cacache/index-v5/
# Compile and install
USER gitpod
 ENV GOPATH=/opt/go
 RUN go get github.com/mrtazz/checkmake
 RUN make -C "$GOPATH/src/github.com/mrtazz/checkmake"
 RUN make -C "$GOPATH/src/github.com/mrtazz/checkmake" install
USER root
```

results in same issue:
```console
gitpod /workspace/gitpod-tests1 $ npx markdownlint
npm ERR! path /home/gitpod/.npm/_locks/staging-9b7649cca73bc029.lock
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/home/gitpod/.npm/_locks/staging-9b7649cca73bc029.lock'
npm ERR!  { [Error: EACCES: permission denied, open '/home/gitpod/.npm/_locks/staging-9b7649cca73bc029.lock']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, open \'/home/gitpod/.npm/_locks/staging-9b7649cca73bc029.lock\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/home/gitpod/.npm/_locks/staging-9b7649cca73bc029.lock' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2019-12-30T17_55_27_346Z-debug.log
Install for markdownlint@latest failed with code 243
gitpod /workspace/gitpod-tests1 $ makecheck
bash: makecheck: command not found
```

Note that these are two different packages (checkmake and markdownlint) that are affected by the issue explained

**Comment by Kreyren** [comment]
Proposed works for npm, thanks @svenefftinge, but checkmake is still not working as expected on https://gitpod.io/#https://github.com/Kreyren/gitpod-tests1/tree/5979af21d161f590ec29a4c011bd70a33f51b86c where this line seems to be processed wrong https://github.com/Kreyren/gitpod-tests1/blob/5979af21d161f590ec29a4c011bd70a33f51b86c/.gitpod.Dockerfile#L43 (checkmake not executable)

Note that this was about two packages (markdownlint which is currently solved and checkmake which is still an issue)

**Comment by Kreyren** [comment]
closed as stale
