### ISSUE TITLE
Error when git-adding quickly

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#104]
**Describe the bug**
I get this error message popup:
```
Request add failed with message: SSH connection error when executing the Git command. add, <filename>
```

**To Reproduce**
1. change ~5 files
2. in the git-commit-view, click `+` quickly for all 5 files.
3. observe one or more adds to fail, with the above error message.

**Expected behavior**
no error.

**Comment by AlexTugarev** [comment]
Cannot reproduce this any longer. We deployed an improvement of the ssh connection a while ago, I think this is solved.
