### ISSUE TITLE
"Remaining usage time" counting when no workspaces running

### ISSUE THREAD

**Issue by svdarren** [gitpod-io/gitpod#1040]
**Describe the bug**
On the workspaces page, there is a counter for "Remaining usage time".  This counter is always ticking down, even when no workspaces are actively running.  Reloading the page returns to the original value, but also ticking down.

**To Reproduce**
Load the [workspaces](https://gitpod.io/workspaces/) page.

**Expected behavior**
When no workspaces are running, the counter should stop.

**Additional Information**
I'm not certain this counter is always displayed.  Due to the new free tier, my under is now under 30 minutes remaining, so I'm getting extra reminders.

**Comment by svenefftinge** [comment]
It seems this is caused by prebuilds running in the background.

**Comment by svdarren** [comment]
Do prebuilds count towards the quota?
