### ISSUE TITLE
Download files

### ISSUE THREAD

**Issue by UCYT5040** [gitpod-io/gitpod#10406]
## Is your feature request related to a problem? Please describe

I ran out of hours on Gitpod, and I'd like to download my files. The download option doesn't seem to be a zip file. I want to download my files from the workspace.

## Describe the behaviour you'd like

I'd like there to be a download zip or download files option so I can get my files.

## Describe alternatives you've considered

An alternative would be to warn users before they run out of hours. Then I could commit and work locally.

## Additional context

There is a download option but the file doesn't seem to be openable.

**Comment by gtsiolis** [comment]
@UCYT5040 Have you tried using the download action from the workspace more actions? It's not a .zip file (https://github.com/gitpod-io/gitpod/issues/7955) but you should be able to rename it and extract the files locally.

<img width="421" alt="Screenshot 2022-06-01 at 4 58 54 PM" src="https://user-images.githubusercontent.com/120486/171422890-c78bf9c8-2c11-40a2-b712-7c39b32bb571.png">

**Comment by gtsiolis** [comment]
Great to hear, @UCYT5040!
