### ISSUE TITLE
Lua support for Gitpod

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1041]
I think Lua would be a great language to have in Gitpod
I've started a repo https://github.com/JesterOrNot/Gitpod-Lua

**Comment by JesterOrNot** [comment]
Vscode version Is not up to date
Activating extension Lua failed: The language client requires VS Code version ^1.40.0 but received version 1.38.0.
![image](https://user-images.githubusercontent.com/50386709/71647116-947bcc80-2cb7-11ea-9e4a-1ffb4d257124.png)

**Comment by akosyakov** [comment]
We will bump VS Code version, in the meantime please use a version of VS Code extension compatible with VS Code 1.38.0.

**Comment by JesterOrNot** [comment]
thanks @akosyakov
