### ISSUE TITLE
[installer] remove need for YAML overrides / leverage config surface

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#10418]
## Is your feature request related to a problem? Please describe

Leverage the config surface for:
1. blobserve
2. workspace-templates
3. ws-manager
4. ws-daemon
5. ws-proxy

## Describe the behaviour you'd like

We use [YAML overrides](https://github.com/gitpod-io/ops/tree/main/deploy/workspace/manifests) for deploying the saas.

They are [applied here](https://github.com/gitpod-io/ops/blob/f675f178f36820bc9bca47110aebd02c94f2aff5/deploy/workspace/gitpod-up.sh#L231-L307).

Ideally we'd have the shape (structure) for the configuration that we want in the installer, some of which may be experimental, with logical corresponding defaults.

Consider continuing to use YAML overrides for`agent-smith` too, unless it is very easy to include as part of this effort. **Note**: the config values we use for agent-smith must still be applied "at deploy time" and persisted in the Ops repo.

## Describe alternatives you've considered

n/a

## Additional context

Related issues (close as needed):
https://github.com/gitpod-io/gitpod/issues/7748
https://github.com/gitpod-io/gitpod/issues/7747
https://github.com/gitpod-io/gitpod/issues/7746
https://github.com/gitpod-io/gitpod/issues/7006

**Comment by kylos101** [comment]
This was scheduled so that we 1) treat the installer config surface as the source of truth and 2) stop using override manifests when we deploy. Why? Recently other teams were making changes to workspace components, and they were unaware that we use manifest overrides (like with `ws-proxy`).

**Comment by sagor999** [comment]
all changes are done in PRs referenced above.
Once all of them are merged, this task can be marked as done.

**Comment by sagor999** [comment]
all PRs have been merged.
