### ISSUE TITLE
part of the path is duplicated in the workspace UI

### ISSUE THREAD

**Issue by lpmi-13** [gitpod-io/gitpod#10411]
### Bug description

I was running gitpod from a specific branch of one of my projects

https://github.com/lpmi-13/ucsb-cs-course-repos.github.io/tree/add_gitpod_option

and after I was finished developing, I shut down the workspace. Immediately afterwards, I decided I wanted to navigate to my repo in GitHub, so I clicked the link, but it seemed like the URL had `/tree/add_gitpod_option` twice, so it ended up being:

`https://github.com/lpmi-13/ucsb-cs-course-repos.github.io/tree/add_gitpod_option/tree/add_gitpod_option`.

I haven't noticed this behavior while using workspaces created from the default branch.

### Steps to reproduce

Open a workspace from a non-default branch.

Stop the workspace.

In the UI, click the link to the GitHub repo.

### Workspace affected

https://lpmi13-ucsbcscourserepo-zezumb6syzo.ws-eu46.gitpod.io/

### Expected behavior

I would expect a link directly to the actual branch

`https://github.com/lpmi-13/ucsb-cs-course-repos.github.io/tree/add_gitpod_option/`

### Example repository

https://github.com/lpmi-13/ucsb-cs-course-repos.github.io/tree/add_gitpod_option/

### Anything else?

![URL has a duplicate path](https://user-images.githubusercontent.com/5070516/171511179-fd4071ce-b4d9-4a09-9a36-fa58babca834.png)

**Comment by geropl** [comment]
@lpmi-13 I tried to reproduce, but can't: https://github.com/geropl/domain-like.repo.io/tree/add_option works as expected, as well as the URL you provided 😕 
Please re-open if you have a way to re-produce! 👍
