### ISSUE TITLE
[ws-manager] alert when IDE backend is unhealthy for a workspace

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#10417]
## Is your feature request related to a problem? Please describe

Sometimes the workspace backend becomes unhealthy, and the workspace frontend disconnects, preventing the user from being able to work with the IDE. We do not have a quick way of knowing this is happening, aside from end-users reporting the problem.

## Describe the behaviour you'd like

There are two parts to this idea:
1. a periodic probe that emits a metric when workspaces become unhealthy
2. an alert when triggered to notify on-call staff

Implement health checks in `ws-manager` that fire on an interval. These would inspect workspaces that should be active to assert whether supervisor and IDE backend processes, perhaps using [go-health](https://github.com/InVisionApp/go-health), are still viable. If not, we'd emit a metric. [Related ports for IDE and supervisor.](https://github.com/gitpod-io/gitpod/blob/406da1e9c79780776859dac98634115edbdfdfac/components/ws-manager/pkg/manager/create.go#L922-L923)

We'd compliment the poor health metric with a new alert. For example, if the new IDE metric indicates poor health for 2+ instances on the same node fail over a 5m duration, fire an alert. 

How would we respond to the alert? On-callers would take action, likely cordoning the node because it is suspect(to avoid  scheduling of workspaces onto the node). We lack continuous profiling, so unless the unhealthy workspace pods are (1) still running and (2) unhealthy, we won't necessarily be able to do profiling.

Please profile ws-manager after this change, before going into production using an ephemeral cluster, to gauge the related impact (in comparison to ws-manager resource usage in production). You'll want to use [loadgen](https://github.com/gitpod-io/gitpod/tree/main/dev/loadgen) for this.

To avoid a "thundering herd", we'll want to see if we can stagger (with random jitter?) the health check for workspaces. Otherwise it's possible that `ws-manager` will have regular spikes of undesirable performance.

## Describe alternatives you've considered

We may want to implement `IStatusListener` in `go-health`, and check the workspace is alive, supervisor is running, the IDE is reachable.

Another option is to leverage existing metrics that we have for the workspace pod, and create alerts based on those now. This way we're not adding more code.

## Additional context

n/a

**Comment by sagor999** [comment]
This seems a bit cumbersome to have ws-manager run health check on potentially 500 workspaces.
Why not instead add liveness probe to workspace itself that would test both supervisor and IDE ports, assuming both have some sort of healthz endpoint on them.
Then, if those fail for several minutes, workspace would shutdown on its own, as k8s will issue a kill command for container that fails liveness probe. 

I will assign this issue to myself for now while figuring out details of this task.

**Comment by sagor999** [comment]
I don't think PSI should act as a proxy that could kill a workspace. It would be good to monitor it as a metric, but it is not actionable metric I think.

**Comment by atduarte** [comment]
Created a separate issue: https://github.com/gitpod-io/ops/issues/3070

**Comment by kylos101** [comment]
@atduarte removing from breakdown for now, we'll want to add this (I think) to a success criteria epic (liveness).
