### ISSUE TITLE
[preview-environments] Clean up post-processing when using VMs

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#10434]
## Is your feature request related to a problem? Please describe
Preview environments running on VMs require less post-processing, e.g. don't require a variable registry-facade host. This unnecessary post-processing should be removed to get us closer to the actual installer experience.

**Comment by meysholdt** [comment]
prerequisite: https://github.com/gitpod-io/ops/issues/2529

**Comment by ArthurSens** [comment]
I believe we don't need to discontinue core-dev to implement this. Have a single interface that is implemented in different ways depending on where we're deploying 🙂
