### ISSUE TITLE
Move all ports commands under the gp CLI namespace

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10449]
Following the introduction of `gp ports list`, we now have two patterns for the CLI, top-level commands, and nested commands. Nested commands is the pattern followed for `gp tasks`, for instance, but ports commands are still at the top level. 

I suggest adding an alias from:

`gp forward-port` to `gp ports forward` (this should be renamed)
`gp await-port` to `gp ports await`

And removing references to the original command help text in all docs.

**Comment by akosyakov** [comment]
Do we still need `gp ports forward` at all?
