### ISSUE TITLE
Not able to open my workspace - showing "cannot mount workspace" error message

### ISSUE THREAD

**Issue by vinaydhakre** [gitpod-io/gitpod#1044]
**Describe the bug**
Not able to open my project - showing "cannot mount workspace" error message

**To Reproduce**
1. Go to https://gitpod.io/workspaces/
2. Click on start to start a project.
3. Not able to open the workspace. It is throwing "cannot mount workspace" error message

**Expected behavior**
it should open the workspace.

**Comment by Seniru** [comment]
I also got a similar error. I got this when I tried to run a fresh workspace of a repository as the workspace I was working can't save or commit files. It gave this error: `error: file write error: No space left on device fatal: unable to write sha1 file`

I wrote this thing here as I think that error is related to this one

**Comment by Panchajanya1999** [comment]
![Screenshot from 2020-01-02 12-21-50](https://user-images.githubusercontent.com/26135639/71654989-b67a5b00-2d5a-11ea-9134-63fb5454425d.png)

**Comment by b4s36t4** [comment]
I've been facing same issue, how ever it is a Fresh workspace and its not even creating workspace and saying `No Space` and cannot mount workspace etc..

**Comment by Seniru** [comment]
Seems everybody is getting this error. Is this a downtime or a problem with disc?

**Comment by b4s36t4** [comment]
I have been facing same issue from past 15 minutes.. :(

**Comment by Seniru** [comment]
There were no changes to the codebase for the past 2 weeks according to github. Should be a problem with the drive as I mentioned earlier

**Comment by b4s36t4** [comment]
![image](https://user-images.githubusercontent.com/59088937/71655114-694ab900-2d5b-11ea-8ed0-30d7897f6e79.png)
But the status is fine.. :(

**Comment by JesterOrNot** [comment]
@Seniru this is not where the source code for Gitpod is hosted there is a private repository for Kubernetes stuff and the internals

**Comment by Seniru** [comment]
Oh, thanks for letting me know :)

**Comment by JesterOrNot** [comment]
I am able to start workspaces I am running chrome os and chrome as my browser
![image](https://user-images.githubusercontent.com/50386709/71655258-98c9d900-2cfb-11ea-88cf-54184f8b49d3.png)

**Comment by Panchajanya1999** [comment]
> I am able to start workspaces I am running chrome os and chrome as my browser
> ![image](https://user-images.githubusercontent.com/50386709/71655258-98c9d900-2cfb-11ea-88cf-54184f8b49d3.png)

Lemme try on a smaller project

**Comment by Seniru** [comment]
Yeah! Me too! 
@b4s36t4 @vinaydhakre I think it's fixed now

**Comment by b4s36t4** [comment]
Yeah.!! Just Checked it now... Happy to see gitpod like that again 😍

**Comment by Panchajanya1999** [comment]
Thanks, Fixed
Close this issue?

**Comment by Seniru** [comment]
Somebody close this one and #1042, #1043 (which is also related to this issue)

**Comment by svenefftinge** [comment]
Sorry, there was a bad node in the asia cluster.
