### ISSUE TITLE
Add machine readable formats to gp CLI output

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10448]
Consider adding a more machine-readable format for the `gp` CLI commands, such as `gp ports list`

https://github.com/gitpod-io/gitpod/issues/9286#issuecomment-1144012355

**Comment by andreafalzetti** [comment]
When we implement this, let's keep in mind that multiple commands can benefit from this feature.

If we can find a reusable pattern, it will speed up adding the same to all commands potentially.

Another candidate is `gp tasks list`.
