### ISSUE TITLE
[proposal] improve github PR message

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#1045]
- trim known metadata, like signed-off-by, co-authored-by and so on
- include not only message from the last commit, but a list of all commits
- allow to specify a placeholder in the PR template, where a message should be inserted

**Comment by tmorehouse** [comment]
If a repo has a `/.github/PULL_REQUEST_TEMPLATE.md` I would like to see that as the pre-populated pull request placeholder

**Comment by tmorehouse** [comment]
The PR template is highly important to us to ensure that contributors follow our guidelines for PRs... with our template, if they do not follow our template guidelines, then the PR will most likely be closed automatically.

**Comment by jankeromnes** [comment]
Actually, while looking back into this, I found this older issue: https://github.com/gitpod-io/gitpod/issues/328

It seems that maybe Gitpod actually supports `/.github/PULL_REQUEST_TEMPLATE.md`, or it did in the past? I'll look more into what happened, and what's required to bring this back.
