### ISSUE TITLE
Support providing existing certificate resource in KOTS installer

### ISSUE THREAD

**Issue by mrzarquon** [gitpod-io/gitpod#10451]
## Is your feature request related to a problem? Please describe

There are situations where a user needs certificates generated with specific information in their environment that KOTS can't anticipate, Gitpod should support being passed an existing certificate resource at install time, instead of having to upload the cert/key file themselves.

In repeated deployments this enables being able to backup a certificate (ie, generated via letsencrypt) and restoring it as a result before performing a new install. Because Gitpod requires wildcard certificates, there is limit on how many identical CSRs for the same wildcard domain can be requested in a rolling 5 day period.

## Describe the behaviour you'd like
Under certificates, provide an option called "existing" that allows for the user to provide the certificate name.

## Describe alternatives you've considered
The only alternative is to patch the certificate generated by Gitpod that has failed to be issued due to missing fields and hope that Gitpod installer then picks up and respects the patched certificate object, ie:
```
kubectl patch certificate https-certificates -n gitpod -p \                  
  '{ "spec": { "subject": { "organizations": [ "gitpod" ] } } }'
```

**Comment by adrienthebo** [comment]
This was discussed briefly in Slack; it was proposed that pre-populating the `https-certificates` certificate secret prior to installation via KOTS may circumvent the need for explicit plumbing in KOTS. This approach is not yet verified; if it works then this approach can be added to the documentation and potentially validated via testing. Otherwise we should be able to make the `https-certificates` secret generation optional with the described `existing` certificate config option (with associated testing and documentation).

**Comment by corneliusludmann** [comment]
> In repeated deployments this enables being able to backup a certificate (ie, generated via letsencrypt) and restoring it as a result before performing a new install. Because Gitpod requires wildcard certificates, there is limit on how many identical CSRs for the same wildcard domain can be requested in a rolling 5 day period.

To prevent this, you can indeed create the `https-certificates` secret before you start the installation. cert-manager recognizes that this cert exists already and will not re-issue this as long as it is still valid.

However, I see the point that you cannot add additional fields to this file with KOTS: https://github.com/gitpod-io/gitpod/blob/da68928bb8ad41db7ae36c94bd643ed62b9aa56c/install/kots/manifests/gitpod-certificate.yaml

We could indeed add an option additional to “self-signed”, “cert-manager”, and “upload your own” like “use existing” that just asks for the secret name and set this secret name [in the Gitpod config](https://github.com/gitpod-io/gitpod/blob/476851ba05ff693cabb0d0476097dc670c18ab64/install/installer/example-config.yaml#L8) in the [installer job](https://github.com/gitpod-io/gitpod/blob/2bbacac350821bf5f38534e856fcfdc2ab780474/install/kots/manifests/gitpod-installer-job.yaml). Then, you can manage the cert creation on your own. That would make sense.
