### ISSUE TITLE
Gitpod for hardware design? 

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1046]
Is there some way to get an environment for hardware design in gitpod? 

### Circuit designer
To design a circuit for manufacturer to create

example
![image](https://user-images.githubusercontent.com/11302521/71834600-e786c280-30af-11ea-969f-33154273e36a.png)

### Circuit simulator
To visually see what voltage and wave form is present on the exact part of the circuit 

<img width="469" alt="image" src="https://user-images.githubusercontent.com/11302521/71834688-18ff8e00-30b0-11ea-941b-b91f70c3d855.png">

live preview on: https://makezine.com/2015/07/14/design-circuits-web-based-circuit-simulator/

### Circuit checker
basically linting for circuit design in case unexpected voltage is provided in a component that is not made for the voltage, etc..

Basically linting to prevent common mistakes alike: https://youtu.be/Tq-EpR-8R0w?t=778

### Board design
To adapt the circuit design on the board itself and specify silkscreen and components for manufacturing

![image](https://user-images.githubusercontent.com/11302521/71835183-354ffa80-30b1-11ea-9e1a-f1d21843e632.png)

### Some method to adapt this for contribution
submitting circuit design for a contribution is currently pita if there would be some overlay in gitpod that would allow to blame specific parts of the design then it would speed up the development

### 3D designer
some way to implement blender to design the casing and make a mock-up

![image](https://user-images.githubusercontent.com/11302521/71835278-6c261080-30b1-11ea-8891-bb4133523bcd.png)

source: https://www.youtube.com/watch?v=RcMIcRqMWn8

#### ComponentEditor?
https://github.com/Circuito-io/ComponentEditor

Seems to be oriented on making some kind of component database -> doesn't meet the requiremenys

**Comment by JesterOrNot** [comment]
I'll get a repo setup

**Comment by JesterOrNot** [comment]
@Kreyren Specifically what tools would you want for this experience?

**Comment by jankeromnes** [comment]
Please take a look at https://github.com/Circuito-io/ComponentEditor, which seems related. 🙂

It should already work well with Gitpod.

**Comment by Kreyren** [comment]
Sorry for the delay i was busy

---

@JesterOrNot 

> Specifically what tools would you want for this experience?

Elaborate on tools? Expecting something from distro repositories or?

---

@jankeromnes 

> Please take a look at https://github.com/Circuito-io/ComponentEditor, which seems related. slightly_smiling_face

That repository seems to be oriented on making some kind of database of components?

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/11302521/71834303-33853780-30af-11ea-9d9b-7f21554a250c.png">

Doesn't seem to meet the requirements

**Comment by Kreyren** [comment]
To provide a real-life example currently the best alternative i found for online IDE is fritzing running in rollApp: https://www.rollapp.com/launch/fritzing
