### ISSUE TITLE
Terminal Issue

### ISSUE THREAD

**Issue by hfakouri** [gitpod-io/gitpod#1047]
**Describe the bug**

Backspace key doesn't remove any character in terminal 

**To Reproduce**

Just open Google Chrome, open any github repository, open a new terminal from menu and write something. Then hit backspace key to remove the text. It doesn't remove it!

**Expected behavior**

Backspace key supposed to remove the text

**Comment by JesterOrNot** [comment]
Can you provide a screencast?
This might also be a X-Term issue

**Comment by hfakouri** [comment]
Here's the [screencast](https://drive.google.com/file/d/1Udh1r2wRUpHMAfNL5QsviivMeVYZTSBr/view)

**Comment by hfakouri** [comment]
Alright, I realized if I remove all my Chrome extensions, I don't have this issue. I'm not sure which extension causes the issue, but now it works correctly!
