### ISSUE TITLE
Workspace times out after a couple of minutes of compute

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#10474]
### Bug description

Workspace will time out after several minutes of compute, but well within the 30 minutes allotted since last user input. 

Compute is running a bunch of C++ unit tests.

I've seen this multiple times - maybe once a day, maybe a bit less often than that.

Workspace appears to have been properly saved, so I can restart where I left off.

### Steps to reproduce

This isn't deterministic.  It just happens from time to time.  This time: approximately Sun June 5 02:00 UTC (more or less).

### Workspace affected

bakinsbits-gitpodsetupf-hx081db2esy

### Expected behavior

Should allow unit tests to finish without timing out!  They're launched manually (at the command line) and take <10 minutes.

### Example repository

https://gitlab.com/bakins-bits/gitpod-setup-for-bitcoin-core-dev/-/tree/main - but this is a multirepo

**Comment by axonasif** [comment]
Hey @david-bakin! Could you share a workspace ID in which this happened?
Also please remember to grab some [logs](https://www.gitpod.io/docs/troubleshooting) on your client after it happens again and send us via contact@gitpod.io with a reference to this issue 🙏

**Comment by david-bakin** [comment]
> Hey @david-bakin! Could you share a workspace ID in which this happened? Also please remember to grab some [logs]

I thought `bakinsbits-gitpodsetupf-hx081db2esy` was a workspace id, if it isn't, what is (and where do I find it)?

I didn't know that about how to get logs.  Will do if I see this again.  (Or something else!)

**Comment by david-bakin** [comment]
I haven't seen this for a long time - closing this issue as no longer relevant
