### ISSUE TITLE
blobserve and registry don't run with http_proxy variables 

### ISSUE THREAD

**Issue by gastondecus** [gitpod-io/gitpod#10484]
### Bug description

blobserve is based on alpine linux , alpine does not support http_proxy and https_proxy configurations the same goes for some other pods any idea?

### Steps to reproduce

I create gitpod.yaml with gitpod-installer render and upgrade this with http_proxy and https_proxy enviroments

### Workspace affected

blobserve and others

**Comment by corneliusludmann** [comment]
Hi @gastondecus! Thanks for reporting the issue with http_proxy and https_proxy. We currently don't support this officially. That's why I don't have a good answer to your requests yet. :disappointed: However, we are considering accepting this as a feature request.

**Comment by lucasvaltl** [comment]
Closing this as it is replaced by #10769
