### ISSUE TITLE
Keep admin menu active when opening a user, project, or team

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#10499]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/10309, currently when opening a user, project, or team in the `/admin` area the menu highlight disappears.

| `/admin/teams` | `/admin/teams/c5895528-xyz` |
|-|-|
| <img width="1105" alt="Screenshot 2022-06-07 at 12 18 46 PM (2)" src="https://user-images.githubusercontent.com/120486/172345240-0cdd9d95-a458-47bb-94cc-8565f46a7f8a.png"> | <img width="1105" alt="Screenshot 2022-06-07 at 12 20 14 PM (2)" src="https://user-images.githubusercontent.com/120486/172345246-9916b399-0b87-411e-b1e5-deb49662fb0e.png"> |

Pasting below a relevant line code that could help:

https://github.com/gitpod-io/gitpod/blob/0a6e84e0af629c3066e27726e599d417744d17a4/components/dashboard/src/Menu.tsx#L110

### Proposal

The menu item should remain active also when opening a user, project, or team in the `/admin` area.

**Comment by Devansu-Yadav** [comment]
@gtsiolis Is this issue still prevalent, considering that we addressed this as part of #16307?

**Comment by gtsiolis** [comment]
Thanks, @Devansu-Yadav! It definitely feels less critical and will be irrelevant if we merge the changes in https://github.com/gitpod-io/gitpod/pull/16423. Let's close this! 📕
