### ISSUE TITLE
Consider remembering team selection when visiting pages like workspaces

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#10496]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/10309, currently when visiting pages like workspaces, the team scope selection changes back to the personal account unnecessarily, as users may work inside a team most of the team and never use their personal account for adding projects, etc.

This could require users to perform more click actions to get back to their team or project they were working on before switching to workspaces, etc.

Cc @AlexTugarev because https://github.com/gitpod-io/gitpod/pull/10309#pullrequestreview-997633645.

### Proposal

Consider remembering the team selection when visiting pages like workspaces.

**Comment by aboqasem** [comment]
Hi! Do you mean this issue?

https://user-images.githubusercontent.com/62098043/173049380-9a7a4840-06e1-4671-a010-c11119c2641a.mov

**Comment by gtsiolis** [comment]
> Do you mean this issue?

@aboqasem Yes, exactly.

> And also, is it intended to send users to the Projects (not Workspaces) page when they switch to team from Workspaces page?

@aboqasem Correct, the team menu on the left is intended to be used for switching to projects for your personal account or any other teams you may be part of, concretely separating and providing a single point of access for the (global) workspaces list.

In case it's not clear enough from the issue description, the proposal here is to keep the selected team scope on the left menu intact and not fallback to your personal account when navigating to other pages like `/workspaces` since many users may not be using the product for developing for any personal projects but mostly collaborate with others or shared projects within a team.

[FWIW](https://en.wiktionary.org/wiki/FWIW), we've experimented with separating the workspaces for teams and projects, but we reverted this change as it was more confusing than helpful, see [relevant issue](https://github.com/gitpod-io/gitpod/issues/7604). Instead, we plan to focus on improving the workspaces list by introducing better filters (#8419), and more.

**Comment by aboqasem** [comment]
Thank you for the elaboration, @gtsiolis!

> [FWIW](https://en.wiktionary.org/wiki/FWIW), we've experimented with separating the workspaces for teams and projects, but we reverted this change as it was more confusing than helpful, see https://github.com/gitpod-io/gitpod/issues/7604. Instead, we plan to focus on improving the workspaces list by introducing better filters (https://github.com/gitpod-io/gitpod/issues/8419), and more.

I made sure that determining the team is not just from the URL. So `/workspaces` would also be aware of the current team.
