### ISSUE TITLE
Setup Wizard creates broken gitpod.yml

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#1051]
**Describe the bug**
The Setup Wizard created a broken `.gitpod.yml` for me.

![image](https://user-images.githubusercontent.com/239422/71831308-ebfbad00-30a8-11ea-9eb8-32f0558b27ad.png)

**To Reproduce**

Run the Setup Wizard on this state:
http://gitpod.io/#https://github.com/meysholdt/guide/commit/b69b890f8d004e04fd8923e52f0e984b0ca86b32

**Comment by JesterOrNot** [comment]
duplicate of #1020

**Comment by JesterOrNot** [comment]
Closing due to duplicate
