### ISSUE TITLE
Improve server-side feature flags

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#10524]
### Bug description

Currently, we have the following feature-flag implementation in `dashboard`:

https://github.com/gitpod-io/gitpod/blob/e63d89afca4694f89fcefbeea888b177875900d3/components/dashboard/src/experiments/client.ts#L38-L55

This is great, because it allows us to specify and control feature-flags separately for staging and production, with custom rules as to who should get the feature flag.

We have a similar implementation in the `server`:

https://github.com/gitpod-io/gitpod/blob/e63d89afca4694f89fcefbeea888b177875900d3/components/server/src/experiments.ts#L13-L22

However, this one is problematic, because it only uses the feature-flags configuration from staging (even in production), and the API is somewhat different.

See also https://github.com/gitpod-io/gitpod/pull/10378#discussion_r892030476:

> It also lives under the root of server/src which it should not.

> This will in fact work for server. However, there's a second problem with it as it hard-codes a single Client ID which is for the preview/staging environment, but not production.

> Let's land as is, and fix it up in a follow-up PR. We'll need to move the file, but also inject the Client ID based on environment we're running in. The current version would also break self-hosted environments as it reaches out to an external source.

### Steps to reproduce

1. Try to use feature flags in `dashboard` / in `server`

### Expected behavior

The `dashboard` and `server` APIs should be similar, and use different rule-sets for staging vs production

**Comment by geropl** [comment]
@easyCZ I think you already addressed this right? I cannot find the PR/issues, though. :shrug:

**Comment by easyCZ** [comment]
@geropl Yes, this fully landed this morning. Thanks for closing this one!
