### ISSUE TITLE
Error: Couldn't parse context 'https://ebbb023b-d8a2-4c88-a5d4-9ff6abf0fd62.ws-eu01.gitpod.io/'.

### ISSUE THREAD

**Issue by paveldyrov1488** [gitpod-io/gitpod#1052]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by JesterOrNot** [comment]
@paveldyrov1488 please elaborate what happened?

**Comment by akosyakov** [comment]
@paveldyrov1488 you don't need to prefix workspace URL with `gitpod.io#`, just enter it as is.

`gitpod.io#` works only GitHub and GitLab urls as contexts, not workspace URLs.
