### ISSUE TITLE
[prebuild] state flip-flop on instances if they need an image build

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#10527]
just saw a weird state modification on instances in workspace-starter.ts:

called in `actuallyStartWorkspace`:
  - `buildWorkspaceImage` is setting `WorkspaceInstanceStatus.phase = "building"`
  - `tryStartOnCluster` is setting `WorkspaceInstanceStatus.phase = "pending"`

**Comment by geropl** [comment]
Nice find! In case we're in building, we should never flip back to "pending". So we need to teach `tryStartOnCluster` to distinguish I guess.

**Comment by geropl** [comment]
@AlexTugarev Just took a look at this one: There is nothing wrong with the state transition `preparing` -> `building` -> `pending`.

Did you notice any cycles there (not clear from the OT)?

**Comment by AlexTugarev** [comment]
👍🏻  thanks for verifying!
