### ISSUE TITLE
Extend workspace timeout via gp CLI

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10525]
Extend workspace timeout via the `gp CLI`

![image](https://user-images.githubusercontent.com/5528307/172578892-849ea58b-a503-4842-81a3-ea509aa15876.png)

[Internal link](https://gitpod.slack.com/archives/C02P236JZPC/p1654032016448669)

**Comment by gtsiolis** [comment]
@loujaybee is this describing a different feature request from https://github.com/gitpod-io/gitpod/issues/7096?

**Comment by loujaybee** [comment]
Now possible: https://www.gitpod.io/docs/command-line-interface#timeout 🚀
