### ISSUE TITLE
GitPod can not open GitLab branch name with '#' in it

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#1054]
**Describe the bug**
I tried to open a private GitLab repository within a group named qbilon-io/qbilon-process-agent/tree/1-initial-process-agent-%232wfn13 and got the error message: Error: Cannot find tag/branch: qbilon-io/qbilon-process-agent/tree/1-initial-process-agent-%232wfn13

**To Reproduce**
Create a private repository within a group and a hashtag in its name (gets translated into % in the url) and try to open it in GitPod

**Expected behavior**
Gitpod can open the repository

**Additional Information**

**Comment by JesterOrNot** [comment]
What subscription do you have?

**Comment by Sandared** [comment]
Personal. Also the master branch of the same repo is no problem to open for GitPod. I assume GitPod can not work with the % sign in the address maybe?

**Comment by JesterOrNot** [comment]
Try it with just https://gitpod.io/#gitlab.com/qbilon-io/qbilon-process-agent

**Comment by Sandared** [comment]
That does work, as does the master branch. However the branch with % in its name does not :(

**Comment by jankeromnes** [comment]
Hi @Sandared, thanks for reporting this! It's probably a bug due to urlencoding/urldecoding (e.g. a `%20` in a URL should be converted to a whitespace).

I agree that trying to open a branch name that includes a `#` should work, so Gitpod should probably urldecode the tag or branch name.

**Comment by svenefftinge** [comment]
solved and deployed
