### ISSUE TITLE
Files in menu items (such as explorer) are opened on mouseup, not onclick

### ISSUE THREAD

**Issue by nicofrand** [gitpod-io/gitpod#10559]
### Bug description

Hi!

When I select a line in the editor I often start my selection from the end of the line, pressing the mouse left button and go to the beginning of the line and release the mouse button. However I go further than the beginning of the line to be quick and my cursor is on the left panel (ex: Explorer).

When I release the mouse button this triggers a `mouseup` event in the panel, for example a file name, which causes it to open in the editor (thus switching the active file being edited).

I am a VSCode user on desktop and everything works fine: the files are only opened from the Explorer on `click` (`mousedown` + `mouseup` on the same element).
Gitpod.io does it only on `mouseup`, which is confusing.

![gitpod-bug-mouseup](https://user-images.githubusercontent.com/3419050/172867805-1f4cc7ff-0bfe-47f4-aa2c-88a823ad8584.gif)

### Steps to reproduce

1. Have the Explorer panel (or any other panel with files) open on the left with a bunch of files
2. Open a file for edition
3. Select a line starting at the end in the editor panel, by pressing the left button of the mouse
4. Move the cursor into the Explorer panel 
5. Release the mouse button on a file name

### Expected behavior

This should not open the file (thus switching the file in the editor) on which the `mouseup` event occurs (it should only do so if the previous `mousedown` event was triggered on it).

### Anything else?

Nothing, thanks for the great tool!

**Comment by akosyakov** [comment]
Please report VS Code bugs to upstream: https://github.com/microsoft/vscode
It does not seem to be related to Gitpod, to confirm you can try to reproduce with https://vscode.dev/
Unfortunately I could not reproduce it on my machine, neither on Gitpod or https://vscode.dev/

**Comment by nicofrand** [comment]
OK but this works on a local vscode like I said nor on vscode.dev. 
It only happens on gitpod…
