### ISSUE TITLE
The Docker image for Grain is out of date

### ISSUE THREAD

**Issue by marcusroberts** [gitpod-io/gitpod#10557]
### Bug description

I observed on Twitter (@k33g_org) was using Grain in a gitpod but wasn't getting LSP features like lenses in VSCode.

Spinning up my own Gitpod Grain in the terminal reports as 0.4.6 but I know the VSCode extension is new from the Grain file icons.

The Docker file references ghcr.io/grain-lang/grain:latest-slim which looking here

https://github.com/grain-lang/grain/pkgs/container/grain. 

is up to date with 0.5.1

This is probably less a bug and more a misunderstanding from me on configuring this, but should I expect it to pull a new Docker image when building and any reason it's not?

### Steps to reproduce

Launch a Gitpod from https://github.com/marcusroberts/gitpod-graintemplate

### Expected behavior

The image should have the latest version of Grain to match the VSCode extension

### Example repository

https://github.com/marcusroberts/gitpod-graintemplate

**Comment by marcusroberts** [comment]
I'm just forcing a reference to the 0.5.1 to test further.

**Comment by k33g** [comment]
I added Grain to my Docker image.
It looks like the LSP server cannot find the dependencies. 

<img width="2160" alt="image" src="https://user-images.githubusercontent.com/491848/172873316-9c8784bc-099f-4ba4-8121-0718d04e9d4a.png">
