### ISSUE TITLE
Cannot set PYTHONPATH in configuration

### ISSUE THREAD

**Issue by Auzzy** [gitpod-io/gitpod#1056]
**Describe the bug**
I'd like to set PYTHONPATH in my Gitpod project's configuration, but it is unset before the workspace is created.

One of my initialization scripts relies on the workspace package itself being available to import, which requires PYTHONPATH to be defined. I've confirmed that it is being unset by chatting with @jankeromnes over on the forum (https://community.gitpod.io/t/setting-pythonpath-not-working/282/2). So it's somewhere between a bug and a feature request, since it seems like Jan was uncertain whether this was intentional or required or an inadvertent feature.

**To Reproduce**
1. Set PYTHONPATH via the Dashboard
1. Start the workspace
1. `echo $PYTHONPATH`

**Expected behavior**
I'd expect the echo to show that PYTHONPATH is loaded in the environment with the value that was defined in the dashboard.

**Additional Information**
Running `gp env` in the workspace shows PYTHONPATH was properly picked up, but isn't available in the workspace. Running `eval $(gp env -e)` loads it in, as expected.

**Comment by jankeromnes** [comment]
Thanks for filing this issue!

I'll try not unsetting `PYTHONPATH`. I expect this won't break our Python / pip setup, but I'm not sure, which is why this needs to be well tested.

**Comment by jankeromnes** [comment]
Relevant feedback from @AlexTugarev (thanks Alex!):

> I expect this to break the persistence of python package into `/workspace/.pip-modules` or their availability to be on search path after installation. This is what I recall from following the #460 traces.
> 
> While hard unsetting seems to be a brute solution, it wasn't compatible with `pip install` of package having `PIP_USER` set to `true`. 
> 
> Also, please consider, use of `PYTHONPATH` seems to be the least optimal solution to add a python module anyways. cf. https://www.tutorialspoint.com/What-is-PYTHONPATH-environment-variable-in-Python, and most of the resources can be found on this. In a nutshell: `pip install -e` (`e` for `editable`) and things like that should be used for dev mode; not sure if there are any other valid use cases.

**Comment by AlbertoFabbri93** [comment]
I am having the same issue, any news on this?

**Comment by CarlosDomingues** [comment]
This issue breaks `poetry` as [it also changes PYTHONPATH](https://github.com/python-poetry/poetry/issues/1729)
