### ISSUE TITLE
VNC timeouts with disconnected

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#1057]
In theia repo VNC page goes in disconnected state often and i have to reload the browser page:
<img width="1552" alt="Screen Shot 2020-01-08 at 16 06 45" src="https://user-images.githubusercontent.com/3082655/71973582-1d9f8000-3231-11ea-85a6-e03b6bf7ab69.png">

cc @meysholdt @jankeromnes @32leaves

**Comment by akosyakov** [comment]
@jankeromnes I heard you found a solution could you share it please? It would improve my experience in Theia a lot for electron and puppeteer.

**Comment by jankeromnes** [comment]
@akosyakov indeed, our solution was to use `/vnc.html?autoconnect=true&reconnect=true&resize=scale` instead of `/vnc_lite.html`. Gitpod should now redirect port 6080 preview to that new URL automatically.

See also: https://github.com/gitpod-io/workspace-images/blob/015ce9b3c2dcb847d091dbe153da4252fd836ad9/full-vnc/novnc-index.html#L8

**Comment by jankeromnes** [comment]
Actually this issue should already be resolved since 2020-04-06:

https://www.gitpod.io/docs/changelog/#2020-04-06

I wonder why you're still getting to the old URL.

**Comment by JesterOrNot** [comment]
I've dealt with something similar recently, try adding a new line to the Dockerfile Gitpod must not be rebuilding the image.

**Comment by akosyakov** [comment]
I will retrigger the build for Theia.

**Comment by akosyakov** [comment]
Please try https://github.com/eclipse-theia/theia/pull/7630

**Comment by akosyakov** [comment]
It seems to be fine now: https://github.com/eclipse-theia/theia/pull/7630#issuecomment-617040004

**Comment by JesterOrNot** [comment]
Glad I could help.
