### ISSUE TITLE
Integrate multiple terminals into JetBrains IDE's

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10579]
Currently, JetBrains doesn't read the commands/tasks functionality of Gitpod. 

This can be worked around by using `gp tasks` for now, but ideally this is a first-class feature in JetBrains. 

There is an issue to resolve for JetBrains https://youtrack.jetbrains.com/issue/CWM-6093 but this is reported now as fixed.

**Comment by akosyakov** [comment]
@felladrin @loujaybee Let's create follow up issues for points from https://github.com/gitpod-io/gitpod/issues/10579#issuecomment-1167076927, add them to https://github.com/gitpod-io/gitpod/issues/7956 and close this issue?

**Comment by felladrin** [comment]
I've created https://github.com/gitpod-io/gitpod/issues/12142 and added it to the Epic.
The other (https://github.com/gitpod-io/gitpod/issues/12126) was previously added by @loujaybee  there.
Closing this issue now.
