### ISSUE TITLE
[gp cli] gp command to print/show workspace class

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#10572]
## Is your feature request related to a problem? Please describe
We recently [added an environment variable](https://github.com/gitpod-io/gitpod/pull/10562) which carries the name of the workspace class a workspace is running on.

## Describe the behaviour you'd like
Environment variables are not always stable - and we are trying to educate folks to not rely on them. Instead, we should plug this into the `supervisor` info endpoint, and add a `gp` command to access it.

**Comment by akosyakov** [comment]
I think the logical place will be `gp top`. It should show workspace class, its configuration for CPU and MEMORY, usage, and provide hints to upgrade if necessary.

To consume programatically we can provide an option like `gp top --json`.

**Comment by mustard-mh** [comment]
x-posting suggestions of `gp top` here https://github.com/gitpod-io/gitpod/pull/12338#issuecomment-1227696754 https://github.com/gitpod-io/gitpod/pull/12338#pullrequestreview-1086514903

cc @filiptronicek @andreafalzetti 

Another reason to add `class description` in `gp top` is, sometimes the limit of resources in `gp top` is not align to the workspace's limit but limit in a time window

**Comment by akosyakov** [comment]
I think we maybe will need to have another command to get different info about workspace, that people can rely on it instead of env var as now. But then it should be rather one command like `gp into (workspaceId|instanceId|workspaceClass|...)?` I think there is already an issue to deprecate evn var and we could do it as a part later.
