### ISSUE TITLE
Integrate with JetBrains backend control center

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10580]
JetBrains backend control center shows information about the node, not the container, this is due to the control center not respecting applications using cgroups (see: [CWM-6090](https://youtrack.jetbrains.com/issue/CWM-6090/Respect-cgroups-in-performance-indicator)). There should be API's that we can use to add custom performance information for Gitpod into this control center so that it's more usable for users in a Gitpod context. 

**Note:** It would be best if JetBrains are able to update the integration to respect cgroups, however due to time limitations we might want to implement ourselves (Gitpod) and eventually update if JetBrains do get around to updating the performance center to respect cgroups and container-based implementations. 

See: 
* https://www.jetbrains.com/help/idea/remote-development-a.html#control_center

![image](https://user-images.githubusercontent.com/5528307/173051890-b56d3c27-2153-49f9-b19e-ad728a5383c3.png)

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/11042

**Comment by akosyakov** [comment]
Internal thread about APIs: https://gitpod.slack.com/archives/C02BRJLGPGF/p1649428266870899
