### ISSUE TITLE
Epic: Offline mode for Gitpod

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10588]
### Summary

In order to bridge scenarios where one does not have access to the internet (e.g. on a train, or worst in case of an internet outage) we want to still give developers the ability to develop. 

### Context

Although Gitpod provides a great development experience (We hope ;) ), it still requires access to the internet. However, this is not always the case, e.g. on a train, or worse in case of an internet outage. 

The idea here is to provide a way to run a workspace locally without having to have a constant internet connection, but with the settings and environmental set up that the user is used to from Gitpod.

### Value

- Extend the applicability of Gitpod to situations where you do not have internet
- Can be part of a disaster recovery plan for an enterprise business

### Acceptance Criteria

- I can run a workspace offline locally (obviously this needs to be better refined)

### Measurement

- Feedback received on this feature
- Uptake of feature - number of users who have tried this

### Context & Additional Info
- [Internal discussion ](https://gitpod.slack.com/archives/C01KGM9DVRC/p1654816243559629)thread with potential solutions

**Comment by lucasvaltl** [comment]
Our stale bot has closed this - we unfortunately did not get to this in this quarter because of competing priorities. I'm removing this out of the Q3 roadmap and putting it back into the future backlog until we can prioritise this again.

**Comment by serotonin276** [comment]
For nomads, it is an essential feature

**Comment by Mustafanaji0413** [comment]
This is a must

**Comment by 1muen** [comment]
You could run a Linux VM in Browser 😉 
https://bellard.org/jslinux/vm.html?url=alpine-x86-xwin.cfg&mem=1024&graphic=1
Its not super fast, but maybe if its optimized :D
