### ISSUE TITLE
Epic: JetBrains Ports information shown on terminals

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10581]
JetBrains are integrating a ports view into the terminals view [CWM-4821](https://youtrack.jetbrains.com/issue/CWM-4821/Offer-port-forwarding-for-the-built-in-terminal). 

This issue is to integrate with that view and expose port information. 

Related issues: 
- https://github.com/gitpod-io/website/issues/2958
- https://github.com/gitpod-io/gitpod/issues/14667
- https://github.com/gitpod-io/gitpod/issues/13761

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/10579
- https://youtrack.jetbrains.com/issue/CWM-6196/Port-forwarding-for-Gitpod

**Comment by felladrin** [comment]
[Auto-forward Task Terminals Ports on JetBrains IDEs #10986](https://github.com/gitpod-io/gitpod/pull/10986) got merged, but we need to keep track of this limitation:

- Forwarded ports on Terminals from Gitpod Tasks won't display the message "Your application is listening on ports" that you see when you start a server on a standard IntelliJ Terminal Widget.

| Open port on Gitpod Task Terminal | Open port on standard IntelliJ Terminal |
| ----------------------------------- | ------------------------------------- |
| ![image](https://user-images.githubusercontent.com/418083/176254937-63ca0146-5a83-482a-85e7-bb9c2c90233f.png) | ![image](https://user-images.githubusercontent.com/418083/176254985-c25924e7-1674-4f09-8706-c1fa180f3297.png) |

JetBrains team will continue working on Port Forwarding implementation, and we might have a solution for it soon.

**Comment by loujaybee** [comment]
Waiting on a build from JetBrains for this one.

**Comment by andreafalzetti** [comment]
> [Auto-forward Task Terminals Ports on JetBrains IDEs #10986](https://github.com/gitpod-io/gitpod/pull/10986) got merged, but we need to keep track of this limitation:
on for it soon.

I've captured the work mentioned here in this ticket: https://github.com/gitpod-io/gitpod/issues/14667

**Comment by loujaybee** [comment]
**Current status:** Running processes within the terminal window shows ports information, but we cannot yet automate this process. @andreafalzetti / @felladrin to collate any YouTrack or related issues so that we can share also with JetBrains, and push for some more updates so that we can make progress on this.

**Comment by loujaybee** [comment]
Still waiting to compile links for JetBrains on YouTrack.

**Comment by loujaybee** [comment]
Issues have been progressed as far as we can for now. We're waiting on some further updates from Jetbrains API's, however we'll open smaller issues to address. More information on the change in the changelog: 

https://www.gitpod.io/changelog#manage-workspace-ports-without-needing-to-leave-your-jetbrains-ui
