### ISSUE TITLE
What is the difference between `Open Preview` & `Preview`?

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#106]
<img width="660" alt="screen shot 2018-10-19 at 10 09 24" src="https://user-images.githubusercontent.com/3082655/47205749-19b2e400-d387-11e8-9452-bc414dd92e16.png">

I see both of them for markdowns. `Open Preview` does not seem to do anythign though. It is confusing.

**Comment by svenefftinge** [comment]
Our preview handling needs improvement.
I think we should 
 - refrain from opening the preview for markdown files, but always open with the editor
 - have some sort of tool bar icon in editors supporting previews

**Comment by kittaakos** [comment]
> I see both of them for markdowns. `Open Preview` does not seem to do anythign though. It is confusing.

It is an old issue, the `Open Preview` and the `Preview` as the opener gets registered somehow. I had the same when I was working with the mini-browser. There is an issue with `Code Editor.` @AlexTugarev does it ring the bell?

**Comment by AlexTugarev** [comment]
@kittaakos, yes indeed. `Preview` command is enabled on selection of files in the navigator if the preview contribution can handle them. 

`Open Preview` the command for the context menu in the source editor. I think if we remove the [label of this command](https://github.com/theia-ide/theia/blob/master/packages/preview/src/browser/preview-contribution.ts#L34), we won't see it in the command palette.

**Comment by kittaakos** [comment]
> I think if we remove the [label of this command](https://github.com/theia-ide/theia/blob/master/packages/preview/src/browser/preview-contribution.ts#L34), we won't see it in the command palette.

That's for sure, but I do not think we want to remove `Open Preview` I would rather remove `Preview`. I will check.

**Comment by akosyakov** [comment]
It's a generic issue with open handlers, they contribute commands to the context menu and there labels like `Code Editor`, `Preview` makes sense. But then they also visible in the command palette. I will be fine to move a label from commands contributed by open handlers to menu items.
