### ISSUE TITLE
Hosted vs self-hosted: difference in DNS search domains in Docker containers breaks application

### ISSUE THREAD

**Issue by wilj** [gitpod-io/gitpod#10606]
### Bug description

I set up a single-node k3s cluster per the self-hosted installation instructions, and opened an existing project that I use with the hosted version of Gitpod.  On the self-hosted server the docker containers get a DNS search domain including the Gitpod namespace.

k3s version: v1.23.6+k3s1
OS version: Ubuntu 20.04

resolv.conf from Docker container on self-hosted version (not working):
`
search gitpod.svc.cluster.local svc.cluster.local cluster.local
nameserver 127.0.0.11
options ndots:5
`

resolv.conf from Docker container on hosted version (working):
`
nameserver 127.0.0.11
options ndots:0
`

Sample output from dig and nslookup showing different results based on the search domain:
`
root@87875d698079:/# dig db

; <<>> DiG 9.16.27-Debian <<>> db
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33835
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;db.                            IN      A

;; ANSWER SECTION:
db.                     600     IN      A       172.18.0.2

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Sat Jun 11 22:03:56 UTC 2022
;; MSG SIZE  rcvd: 38

root@87875d698079:/# nslookup db
Server:         127.0.0.11
Address:        127.0.0.11#53

Name:   db.gitpod.svc.cluster.local
Address: 10.43.151.139

root@87875d698079:/# nslookup
> set nosearch
> db
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   db
Address: 172.18.0.2
> set search
> db
Server:         127.0.0.11
Address:        127.0.0.11#53

Name:   db.gitpod.svc.cluster.local
Address: 10.43.151.139
> 
`

### Steps to reproduce

1) Install the self-hosted version on Ubuntu 20.04 and k3s.
2) Open workspace and run docker containers.
3) Exec into containers, inspect resolv.conf, and dig/nslookup results.

### Expected behavior

DNS entries in Docker containers should resolve the same in the host and self-hosted versions.

### Anything else?

I'm able to work around it by specifying an external DNS server for each of my containers:

> services:
>   server:
>     dns:
>       - "1.1.1.1"
 

Overriding the DNS server with an external one seems to force it to look up the correct IP.

[supportbundle-2022-06-11T22_35_26.tar.gz](https://github.com/gitpod-io/gitpod/files/8884842/supportbundle-2022-06-11T22_35_26.tar.gz)

**Comment by aledbf** [comment]
@wilj this works as expected. Without additional configuration, the containers inherit the Kubernetes configuration.
If you don't want that, you can customize the installation using something like
```
workspace:
  templates:
    default:
      spec:
        dnsConfig:
          nameservers:
            - 1.1.1.1
            - 8.8.8.8
        dnsPolicy: None
```

**Comment by aledbf** [comment]
> DNS entries in Docker containers should resolve the same in the host and self-hosted versions.

Enabling customization (if required) provides more flexibility. Also, in some environments is not desirable/possible to use custom values.

**Comment by wilj** [comment]
> @wilj this works as expected. Without additional configuration, the containers inherit the Kubernetes configuration. If you don't want that, you can customize the installation using something like
> 
> ```
> workspace:
>   templates:
>     default:
>       spec:
>         dnsConfig:
>           nameservers:
>             - 1.1.1.1
>             - 8.8.8.8
>         dnsPolicy: None
> ```

Awesome, thank you!  Since that's the "default" template, I'm guessing there can be more than one?  It would be nice to be able to change it per workspace, or per type of workspace.
