### ISSUE TITLE
Default keybindings cannot be overridden

### ISSUE THREAD

**Issue by havogt** [gitpod-io/gitpod#1060]
**Describe the bug**
I would like to set some custom keybindings. The key combination I am currently looking at is already used in a default: `ctrl+d`. I cannot find a way to bind this key to something else (e.g. `Delete Line`).
I am not 100% sure if this is just an issue with `ctrl+d` or an issue with all key combinations which are already used as a default. Probably this is a theia issue, but I don't have a theia setup to try to reproduce their.

**To Reproduce**
In all the following cases the behavior is the same: `ctrl+d` will always do the default command which is `Add Selection To Next Find Match`
- setting the keybinding manually in the `keymaps.json`
```
    {
        "command": "editor.action.deleteLines",
        "keybinding": "ctrl+d",
        "context": "textInputFocus && !editorReadonly"
    },
```
- setting the key via UI -> will just add the above to the `keymaps.json`, and the default `ctrl+shift+k` will still be shown in the UI
- try to change the `Add Selection To Next Find Match` to something else first -> `ctrl+d` will still do the default action (note that it is not possible to unbind a command: the UI says `keybinding value is required`)

**Expected behavior**
The key binding should do the requested custom command.

**Additional Information**
I used Firefox and Chrome on Linux.

**Comment by akosyakov** [comment]
That’s a bug in Theia, we don’t suppress monaco keybinding handler.

**Comment by havogt** [comment]
Thanks for the fix @akosyakov. Now I can really start using gitpod as a desktop replacement! Good work!
