### ISSUE TITLE
[installer-tests] Test K3s with different Ubuntu versions

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#10600]
## Is your feature request related to a problem? Please describe

Test automation uses a specific [Ubuntu image](https://github.com/gitpod-io/gitpod/blob/8dcddf4d9e9e0cc54b0286e7bec43b95cf1c67c4/install/infra/terraform/k3s/main.tf#L76).

## Describe the behaviour you'd like

It would be nice to test many versions of Ubuntu.

Why? [We currently support 18.04, and 20.04](https://www.gitpod.io/docs/self-hosted/latest/cluster-set-up#node-and-container-requirements), and are running 22.04 on the saas. 

What if 18 or 20 break? We won't know (easily) unless a self-hosted customer tells us, because the saas is on 22.

Ideally we'd be able to include other variables too, for more complex permutations, like Kubernetes and containerd versions. But I think we need to be careful in how many permutations we take one...it'll quickly grow out of control.

## Describe alternatives you've considered

Right now the version is stored in a file, and triggered via werft. Perhaps we can provide for the ability to override some values at runtime?

## Additional context

The [product compatibility matrix](https://www.notion.so/gitpod/Product-Compatibility-Matrix-a7f15b2155a545aa8a7b6c27cf7e00ae) [internal] has many combinations. We should pick the highest risk variables and invest in related test automation.

**Comment by MrSimonEmms** [comment]
One thing to note is that it seems that Ubuntu 22.04 has changed their SSH authentication process. It works fine if you're using normal `ssh` in a terminal, but it seems to have broken how applications such as `k3sup` use it - see this [issue](https://github.com/alexellis/k3sup/issues/377) for instance

**Comment by lucasvaltl** [comment]
This is related to #7316 and #10620 and will likely be covered in the latter.

**Comment by lucasvaltl** [comment]
@nandajavarma how does this ticket fit into your next steps for automated testing? Would you mind moving this to the relevant state: backlog if we are not going to work on it soon, and scheduled if we are going to work on it soon.

**Comment by nandajavarma** [comment]
Closing this in favor of #11272
