### ISSUE TITLE
Have labels on GCP Disks and Snapshots

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#10612]
## Is your feature request related to a problem? Please describe
We need to add labels to GCP Disks and Snapshots because we use labels to filter the cost.

## Describe the behaviour you'd like
Make the GCP Disks and Snapshots have labels so we are able to filter the cost.

## Describe alternatives you've considered

N/A

## Additional context

https://github.com/gitpod-io/gitpod/issues/10186#issuecomment-1152422085

#7901

**Comment by sagor999** [comment]
Upstream PR: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1017

**Comment by jenting** [comment]
> Upstream PR: [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1017](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1017)

Code merged, waits for the next release 🚀

**Comment by jenting** [comment]
It's good to add the cluster name to the label, so we can easily file the cluster by the label on the GCP console.

**Comment by sagor999** [comment]
This [PR](https://github.com/gitpod-io/ops/pull/4123) enables labels on disks.
Once upstream will release new gsi driver containing my fix for allowing to add labels to snapshot classes, we will do the same for snapshots. Until then I will add blocked label.

**Comment by kylos101** [comment]
@sagor999 is there an ETA for upstream to release new driver?

**Comment by sagor999** [comment]
Not as far as I know... :( Just have to wait, or we can build it ourselves and use our own version until then.

**Comment by kylos101** [comment]
@sagor999 is there a PR for which we can inquire about the release? I ask because I think @jenting did similar last time...and then the release was cut rather quickly. :pray:

**Comment by jenting** [comment]
> @sagor999 is there a PR for which we can inquire about the release? I ask because I think @jenting did similar last time...and then the release was cut rather quickly. :pray: 

https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1017#issuecomment-1227370762

**Comment by kylos101** [comment]
Hi @jenting what release cycle do they generally follow, can you share a link? If none, can you reach out to Matt again?

**Comment by jenting** [comment]
> Hi @jenting what release cycle do they generally follow, can you share a link? If none, can you reach out to Matt again?

[v1.8.0-rc1 release](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/releases/tag/v1.8.0-rc1)
We could tried it at ephemeral cluster _or_ workspace preview now 🚀

**Comment by jenting** [comment]
@sagor999 I have a question, if we would want to add custom labels to `VolumeSnapshot`, should we use the [v1.8.0 release](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/releases/tag/v1.8.0-rc1) release?
Because I like like to delete the VolumeSnapshot by labeling so we could remove the snapshots generated by the ephemeral cluster.

**Comment by sagor999** [comment]
Yeah, that is the only way or build our own version of it that has that commit. 
It will also require creating separate snapshot classes, similar to how I did with storageClasses (as label is specified there).

**Comment by jenting** [comment]
> It will also require creating separate snapshot classes, similar to how I did with storageClasses (as label is specified there).

If I understand correctly, creating separate volume snapshot classes with different labels.
The volume snapshot and volume snapshot content will inherit the labels from volume snapshot classes, correct?

**Comment by sagor999** [comment]
yup!

**Comment by jenting** [comment]
> Yeah, that is the only way or build our own version of it that has that commit. It will also require creating separate snapshot classes, similar to how I did with storageClasses (as label is specified there).

I built it `jenting/gcp-compute-persistent-disk-csi-driver:v1.8.0-rc1_linux_amd64`, and I will try it tomorrow.

**Comment by sagor999** [comment]
@jenting probably no need to build you own version of it anymore: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/releases/tag/v1.8.0

**Comment by jenting** [comment]
> @jenting probably no need to build you own version of it anymore: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/releases/tag/v1.8.0

The container image does not released 😢 
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/1056

**Comment by jenting** [comment]
I build our own `jenting/gcp-compute-persistent-disk-csi-driver:v1.8.0`
