### ISSUE TITLE
Eagerly display typed input in terminal

### ISSUE THREAD

**Issue by Nick-Mazuk** [gitpod-io/gitpod#10611]
## Is your feature request related to a problem? Please describe

When you type anything in the terminal, there's currently latency between the keypress and when it's displayed on the screen. For me, the latency is quite noticeable (probably ~250ms). This creates a suboptimal user experience.

## Describe the behaviour you'd like

Since all keystrokes will eventually be displayed to the screen, the keystrokes should be eagerly displayed—especially when there aren't any other tasks happening.

That way, we can eliminate all latency and to simulate a local-first development experience with the power of a cloud-based development environment.

## Describe alternatives you've considered

As far as I know, there's nothing a user can do right now to fix this.

**Comment by axonasif** [comment]
Hey 👋 
Where are you based? Asia?
It might be due to the server latency for your location, you can check in: https://gcping.com/

**Comment by akosyakov** [comment]
You can enable local echo in VS Code to see typing immediately: https://code.visualstudio.com/docs/terminal/basics#_local-echo
