### ISSUE TITLE
installer: allow to specify storageClass in gitpod.yaml

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#10613]

**Comment by jenting** [comment]
@sagor999 
Now the installer contains the `storageClass` and `snapshotClass` in [config.yaml](https://github.com/gitpod-io/gitpod/blob/85536681745404ba912c294dabddc5e692d36580/install/installer/example-config.yaml#L33-L34) already.
And the user could change the value before rendering the `gitpod.yaml` manifest.

What else should we implement? If not, I'd like to close this issue.

**Comment by sagor999** [comment]
yup. this task was already done. close it please.
