### ISSUE TITLE
gitpod workspace stuck on "stopping"

### ISSUE THREAD

**Issue by angharadcaswell** [gitpod-io/gitpod#10624]
### Bug description

I was working on gitpod and the workspace stopped working and requested to refresh the page. I did but then it was not loaded properly. I did try to open it again through the dashboard but when clicking on the workspace it got stuck on "stopping". 

### Steps to reproduce

Clicked on the workspace on the Gitpod Dashboard

### Workspace affected

https://angharadcas-surfvolunte-sxsnaalvlqe.ws-eu47.gitpod.io/

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ouve)

**Comment by jenting** [comment]
Related to #11336
