### ISSUE TITLE
Connect via SSH button appears even when SSH not enabled

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#10643]
### Bug description

> There are likely other ways to connect to SSH in addition to the documented one. These should also be disabled appropriately

When starting a workspace, the home screen's "More Actions" button has a "Connect via SSH" option. 
This is always enabled, even when [SSH has not been configured](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/config/v1/config.go#L105) by the Installer.

This screenshot is from my own self-hosted instance where SSH has not been enabled (it's running on a Hetzner instance, which hardcodes port 22 for SSH for accessing the node).

![image](https://user-images.githubusercontent.com/275848/173517986-6f9dde2b-014f-4bc9-99dc-d3291185b48e.png)

### Steps to reproduce

Configure a self-hosted instance, leaving the SSH option (if using KOTS) disabled

![image](https://user-images.githubusercontent.com/275848/173518830-c3c23416-6c26-42e3-881e-7568f407de0b.png)

### Workspace affected

self-hosted

### Expected behavior

"Connect via SSH" only appears if it's configured.

Reasoning being that I can foresee a slew of tickets saying "why can I not connect via SSH" which are due to the option not being configured.

### Anything else?

It's likely that this will require a config change in the Installer in addition to the `SSHGatewayHostKey`. If so, this will also need going into the [KOTS config](https://github.com/gitpod-io/gitpod/blob/main/install/kots/manifests/gitpod-installer-job.yaml#L213).

[Internal discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1655136458216889)

**Comment by loujaybee** [comment]
Adding note that this would also apply to desktop IDE's, including JetBrains and (soon to be) VS Code Desktop, as they all use (or will soon use) the SSH gateway under the hood.
