### ISSUE TITLE
[Usage] workspace.go:68 Error 1390: Prepared statement contains too many placeholders

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#10642]
### Bug description

It looks like our `usage` component is logging an error containing tons of workspace IDs once every minute:

```
github.com/gitpod-io/gitpod/usage/pkg/db/workspace.go:68 Error 1390: Prepared statement contains too many placeholders\n[140.200ms] [rows:0] SELECT * FROM `d_b_workspace` WHERE `d_b_workspace`.`id` IN ('techlabapps-myjourney-mysicp2zuyi','antdesign-antdesign-j3ad1xm6oqt',.........
```

I believe the problem arises here:

https://github.com/gitpod-io/gitpod/blob/39557c349987d26bffc60529a2804197313243e8/components/usage/pkg/controller/reconciler.go#L204

when we try to get all the workspaces corresponding to all the workspace instances which ran some time this month.

Reminder: Gitpod runs _tons_ of workspaces and instances each month. We should be careful when querying them all into memory and/or dumping them all into logs. (And, currently, the usage component does both every minute.)

See also:
- [slack thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1655158943465569) (internal)
- [cloud logging](https://cloudlogging.app.goo.gl/5wwBKCobgoEMqqDp6) (internal)

### Steps to reproduce

1. Check `usage` component logs in production

**Comment by jankeromnes** [comment]
As [suggested on StackOverflow](https://stackoverflow.com/a/57238745/3461173), a small 🛹 fix here could be to split the workspaces query (see quoted line of code ☝️) into chunks of e.g. 1000 IDs max, then run all the chunks one by one.

Also, I'm a bit uneasy about the `usage` loop frequency of once per minute. We could dial that one down to e.g. once every 30min or 1h.

**Comment by jankeromnes** [comment]
FYI, as a better, longer-term fix, we could refactor the current code (which has large queries & several iterations over the same data) to try and:
- Only query the necessary data into memory (not fully-hydrated DB shapes, but just the columns we actually need)
- Try to iterate over all instances as few times as possible, ideally just once

---

We could e.g. do something like this:

1. Query only `id`, `workspaceId`, `creationTime`, `stoppedTime`, `workspaceClass` (and [soon](https://github.com/gitpod-io/gitpod/pull/10574) `attributedTeamId`) from `d_b_workspace_instance` for all instances that ran in the desired month and have a `startedTime` (unused field, but there to eliminate instances that never started):

```sql
SELECT `id`, `workspaceId`, `creationTime`, `stoppedTime`, `workspaceClass`
FROM d_b_workspace_instance
WHERE stoppedTime >= '$BEGINNING_OF_PERIOD' AND creationTime < '$END_OF_PERIOD' AND startedTime != ''
```

(Currently, we query all the fields from all the instances, even the ones that never started: [source](https://github.com/gitpod-io/gitpod/blob/39557c349987d26bffc60529a2804197313243e8/components/usage/pkg/db/workspace_instance.go#L62-L83))

2. Iterate over all the instance, just once, and for each instance, begin "transforming" them into a usage record by:
    - Trimming `creationTime` to no-earlier-than-beginning-of-period (e.g. [like so](https://github.com/gitpod-io/gitpod/blob/39557c349987d26bffc60529a2804197313243e8/components/usage/pkg/controller/reconciler.go#L288-L290))
    - Trimming (or simply setting) `stoppedTime` to no-later-than-end-of-period (e.g. [like so](https://github.com/gitpod-io/gitpod/blob/39557c349987d26bffc60529a2804197313243e8/components/usage/pkg/controller/reconciler.go#L292-L294))
    - Inserting the `workspaceId` into a Set or Map
      - (the current code [inserts into an array with duplicates](https://github.com/gitpod-io/gitpod/blob/39557c349987d26bffc60529a2804197313243e8/components/usage/pkg/controller/reconciler.go#L201) and later [processes the array into a unique set](https://github.com/gitpod-io/gitpod/blob/39557c349987d26bffc60529a2804197313243e8/components/usage/pkg/controller/reconciler.go#L301-L312) -- using a Set immediately sounds more efficient)
      - keeping a reference/pointer to each instance or usage record in each Set or Map item could save a second iteration over all instances 💭

3. Next, iterate over the unique workspace IDs in order to resolve just the `userId` (a.k.a. `ownerId`) and `projectId` for each usage record:

```SQL
SELECT ownerId, projectId
FROM d_b_workspace
WHERE id IN ('$UNIQUE_WS_IDS')
```

and then back-fill this ownership information into every relevant usage record (using `workspaceId`).

4. Also, once we have https://github.com/gitpod-io/gitpod/pull/10574, we'll no longer need to resolve the relevant `teamId` in the `usage` component itself (I believe we currently check the `userId` against `d_b_team_membership` to do that, or we were planning to). We'll already have the attributed `teamId` for the instance's usage, and we can possibly save these `teamId`s into a Set as well, in order to later resolve Stripe Customer IDs for these.

---

An alternative approach could be to do all the joins in SQL directly, but from my understanding, this is typically less efficient, and prevents using caching or sharding on intermediate steps.

**Comment by easyCZ** [comment]
Reopening as https://github.com/gitpod-io/gitpod/pull/10778 still needs to land to close this.
