### ISSUE TITLE
Allow configuration of connect via SSH port (e.g. port 22)

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#10645]
## Is your feature request related to a problem? Please describe

The "connect [to workspace] via SSH" button only connects via port 22.

When using k3s on a plain VM, some vendors (eg, Hetzner/DigitalOcean/Civo) don't provide an option to change the port for SSHing into the VM. This means that they can never enable the "connect via SSH" option on their Gitpod installation.

## Describe the behaviour you'd like

An option in the KOTS dashboard to configure the SSH port to a different port number. This would need changes in the Installer and `server` components to handle this configuration parameter.

![image](https://user-images.githubusercontent.com/275848/173524488-2ad5c678-e24d-46e1-8771-6b1aec42947b.png)

## Describe alternatives you've considered

Without the option to configure the SSH port on the machine, there are limited available options.

## Additional context

In the KOTS dashboard at least, we may wish to offer a select list of available ports to avoid internal port conflicts - suggest `22` (default), `2200`, `2222`, and `2244`. The Installer and `server` should just accept the value that they are given.

[Internal discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1655136458216889)

**Comment by loujaybee** [comment]
Removing WebApp from here, as seems more IDE and Self-Hosted 🙏

**Comment by tyler36** [comment]
Would love to see some progress on this issue. Our IT department blocks access to port 22 unless you submit an application the day before.

**Comment by mrsimonemms** [comment]
Hey @tyler36 - Gitpod self-hosted is [dead](https://www.gitpod.io/blog/introducing-gitpod-dedicated).

That said, I did figure out a way how to [change the server's port 22 to 2244](https://github.com/mrsimonemms/gitpod-self-hosted/blob/main/cloud-init/k3s_manager.yaml#L26,L32) - this doesn't affect Gitpod's SSH server running on port 22 and, as self-hosted is [dead](https://github.com/mrsimonemms/gitpod-self-hosted#gitpod-self-hosted-instructions), I sincerely doubt it will.

**Comment by akosyakov** [comment]
@tyler36 you can switch to Web tunnel via `gitpod.remote.useLocalApp: true` in VS Code user settings. We are also working on new smoother experience which will automatically find the best way to connect, stay tune!

**Comment by tyler36** [comment]
@akosyakov 

if I set `gitpod.remote.useLocalApp: true`, it overrides `remote.SSH.configFile` on my local PC which means I have manually change it back before I can access other SSH remotes.

**Comment by akosyakov** [comment]
yeah, sorry, for now we don't have the better way, we are working on new which should not, but still in prototype state
