### ISSUE TITLE
Epic: Limit TCP connections per workspace

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#10651]
### Summary

Limit number of TCP connects a given workspace can establish, to avoid "conntrack table is full" issues and ensure workspaces don't starve neighbours.

### Context

Currently, we receive a significant number of _GitpodNodeConntrackTableIsFull_ alerts. Whenever this happens, the experience in all workspaces that live in that node are at risk, and the on-callers have to manually identify the abuser and act accordingly. 

Relates to https://github.com/gitpod-io/gitpod/issues/10756 and https://github.com/gitpod-io/gitpod/issues/10760.

### Value

Improve reliability and reduce operational burden.

### Acceptance Criteria

* A given workspace is unable to starve the conntrack table.

### Measurement

* Reduction of _GitpodNodeConntrackTableIsFull_ alert count.

### Tasks

- [x] https://github.com/gitpod-io/gitpod/issues/11632
- [x] #13041

**Comment by atduarte** [comment]
Preliminary work, that relies on augmenting agent-smith with Tetragon capabilities, exists at: https://github.com/gitpod-io/gitpod/tree/fo/agent-smith-mk2 (from @Furisto).
If that works, epic's effort should be small (2 weeks).

**Comment by utam0k** [comment]
@adrienthebo @kylos101 What is the status of this issue? I ask because https://github.com/gitpod-io/gitpod/pull/11255 processed this epic, right?

**Comment by kylos101** [comment]
> @adrienthebo @kylos101 What is the status of this issue? I ask because #11255 processed this epic, right?

I think you meant @atduarte ? 

And no, it does not finish the epic yet. Instead of limiting, it'll record where it would have limited, and we'll be able to use a new graph @Furisto added to the `ws-daemon` dashboard, to determine how often workspaces would have been limited. We can then use that knowledge to determine if we need to tune the configuration, prior to actually limiting.
