### ISSUE TITLE
Re-introduce inactive workspaces collapsible component on the workspaces list

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#10665]
### Problem to solve

The new inactive workspaces grouping introduced in https://github.com/gitpod-io/gitpod/pull/10450 was reverted in https://github.com/gitpod-io/gitpod/pull/10663.

See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1655206478525059) (internal). Cc @AlexTugarev @geropl 

### Proposal

Given, this seems like a trivial fix, like the one back in https://github.com/gitpod-io/gitpod/pull/3945, let's re-introduce back this feature.

For more context, see [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1655202551884529) (internal).

**Comment by svenefftinge** [comment]
Happy to take this, so it doesn't side-track the team too much 😇
