### ISSUE TITLE
The flakiness of workspace integration test when port-forwarding

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#10671]
### Bug description

The flakiness of workspace integration test when port-forwarding.
The error message is
```shell
contexts_test.go:134: timed out attempting to connect agent: dial tcp 127.0.0.1:36405: connect: connection refused
```

Ref to https://github.com/gitpod-io/gitpod/blob/f0daee20478e5b9e928c57ac01dee2a82aaeed86/test/pkg/integration/integration.go#L218-L242

### Steps to reproduce

https://werft.gitpod-dev.com/job/gitpod-custom-main.84

**Comment by kylos101** [comment]
@jenting scheduled, thank you for creating! If you get blocked and have spare time, please investigate?

**Comment by jenting** [comment]
> @jenting scheduled, thank you for creating! If you get blocked and have spare time, please investigate?

Sure thing 😉

**Comment by kylos101** [comment]
@jenting do you think this is related to our tests, or the preview environments? I ask because if preview environments, I am tempted to close this issue (as we plan to run them in self-hosted infra).

**Comment by jenting** [comment]
> @jenting do you think this is related to our tests, or the preview environments? I ask because if preview environments, I am tempted to close this issue (as we plan to run them in self-hosted infra).

I can't 100% sure of the culprit. We could keep this open until we change to using the self-hosted infra. WDYT?

**Comment by kylos101** [comment]
Okay, sounds good, I'll remove you as assignee and bring down in priority for now.

**Comment by kylos101** [comment]
@jenting removing from scheduled work for now, we'll revisit after getting tests running on self-hosted infra and sharing output in a Slack channel

**Comment by utam0k** [comment]
dup: https://github.com/gitpod-io/gitpod/issues/12248
