### ISSUE TITLE
Overriddes VSCode config for SSH Config Location

### ISSUE THREAD

**Issue by Merith-TK** [gitpod-io/gitpod#10692]
### Bug description

this literally changes the vscode global config for this to work, and it is *quite* annoying to have to switch it back every single time as I have workspaces on remote hardware that I need to be able to access quickly

### Steps to reproduce

have `~/.ssh/config` set as your default config *locally*

then click "open in vscode" on gitpod, 

### Anything else?

It is very annoying and I believe there should be an way to not do this, or rather add an *tempory* config into the pre-defined `.ssh/config` that is then deleted after use

**Comment by filiptronicek** [comment]
Hey there @Merith-TK, sorry to hear of your troubles. 

I believe the extension should not alter your SSH config anymore in the latest version. Could you please check what version you are using and try out the pre-release version if you are not currently using it? It should be as simple as clicking the button on the extension's page in VS Code. It should be released in the stable channel soon.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/29888641/174016475-6263913d-e81d-4484-8e1c-19e7fcd53115.png">

**Comment by Merith-TK** [comment]
pre-use of extension
![image](https://user-images.githubusercontent.com/10422110/174191266-72b5a2ef-ee1c-4917-ab46-01b4443dd865.png)

After use settings remained the same (yay!)

however, now 
![image](https://user-images.githubusercontent.com/10422110/174191358-2896d5cd-75b5-4434-b0ce-4f792d45dff8.png)

**Comment by filiptronicek** [comment]
@jeanp413 have we seen this issue yet with SSH Gateway?

**Comment by jeanp413** [comment]
@Merith-TK could you try using an absolute path to your default ssh config file in the `Remote.SSH config file` setting like this `C:\Users\{USERNAME}\.ssh\config`? If that doesn't work maybe try deleting `known_hosts` file. ([from stackoverflow](https://stackoverflow.com/questions/60335069/vscode-remote-connection-error-the-process-tried-to-write-to-a-nonexistent-pipe))

**Comment by MilesCranmer** [comment]
I am also seeing this issue as of today on my machine which is macOS Monterey. Even when I remove the gitpod-provided ssh config manually from settings, it just adds it back the next time I launch gitpod, which prevents me from using my local ssh config in other windows.

**Comment by axonasif** [comment]
I disabled `gitpod.remote.useLocalApp` and that does not seem to overwrite my VSCODE `remote.SSH.configFile`.

**Comment by jeanp413** [comment]
@MilesCranmer you can try ` "gitpod.remote.useLocalApp": false` in your settings.json or install the pre-release version of the gitpod-desktop extension (it's `false` by default in there).

**Comment by akosyakov** [comment]
I'm closing it, please follow https://github.com/gitpod-io/gitpod/issues/10692#issuecomment-1165843068. In the future it is going to become a default.

**Comment by loujaybee** [comment]
Also, please see: https://www.gitpod.io/blog/vscode-desktop-ssh-updates

For more information.
