### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by isontheline** [gitpod-io/gitpod#1069]
**Describe the bug**
Hello Gitpod Team. There is no disk space left for my workspace :
c9dd8ef3-xxxx-xxxx-xxxx-fd4f5e73224d

**To Reproduce**
Just launched workspace on a Gitpod pod.

**Expected behavior**
Some disk space in order to do some work :)

**Additional Information**
```
Filesystem      Size  Used Avail Use% Mounted on
overlay         193G  148G   46G  77% /
tmpfs            64M     0   64M   0% /dev
tmpfs            30G     0   30G   0% /sys/fs/cgroup
/dev/sdb        369G  355G     0 100% /theia
/dev/sda1       193G  148G   46G  77% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs            30G     0   30G   0% /proc/acpi
tmpfs            30G     0   30G   0% /proc/scsi
tmpfs            30G     0   30G   0% /sys/firmware
```

**Comment by thomas-worm-fernuni** [comment]
Seems all workspaces cannot start because of missing space.

**Comment by thomas-worm-fernuni** [comment]
It is now working

**Comment by jankeromnes** [comment]
@isontheline and @thomas-worm-fernuni Many thanks for reporting this issue! We're very sorry for the bad experience.

As indicated in https://github.com/gitpod-io/gitpod/issues/1071#issuecomment-573570039, one of our Europe West 1 cluster servers had a full disk 3 hours ago. We were able to fix it about 2 hours ago.

We're trying to prevent these problem from happening again in the future. Apologies for the disruption this morning!

**Comment by jozefvodicka** [comment]
happened again:
> [1/5] FROM [docker.io/gitpod/workspace-full-vnc@sha256:a2daa43ed4f0f87146f793b0f7e9c8fa197cf450799daa6cc93076f28629cba3](https://www.google.com/url?q=http://docker.io/gitpod/workspace-full-vnc@sha256:a2daa43ed4f0f87146f793b0f7e9c8fa197cf450799daa6cc93076f28629cba3&sa=D&source=calendar&ust=1720815305592312&usg=AOvVaw37FEsfz3C72cVg8vE79ndw):
------
.gitpod.Dockerfile:8
--------------------
   6 |     # GitPod image with support of VNC (GUI access via 6080 port, to access Cypress Browser tests).
   7 |     # ref: [https://www.gitpod.io/guides/gitpodify#getting-a-virtual-desktop](https://www.google.com/url?q=https://www.gitpod.io/guides/gitpodify%23getting-a-virtual-desktop&sa=D&source=calendar&ust=1720815305592312&usg=AOvVaw35Gh0bN9WpwLjYKzP-JXgZ)
   8 | >>> FROM gitpod/workspace-full-vnc 
   9 |     
  10 |     ENV DEBIAN_FRONTEND noninteractive
--------------------
ERROR: failed to solve: failed to register layer: write /home/gitpod/.rvm/gems/ruby-3.2.4/gems/nokogiri-1.16.6-x86_64-linux/lib/nokogiri/3.0/nokogiri.so: **no space left on device**
Image Build Failed
