### ISSUE TITLE
[Go] support projects that use go modules

### ISSUE THREAD

**Issue by kjk** [gitpod-io/gitpod#107]
With release of go 1.11, Go ecosystem is quickly moving to using go modules, which deprecates traditional GOPATH setup.

The changes needed to support Go modules well:

1\) Update go to 1.11 as this is the first version that supports go modules. Currently gitpod uses go 1.9.2.

2\) Auto-detect if project uses go modules by checking if file `go.mod` exists in top-level of the source code directory.

3\) If project uses go modules, don't do the current GOPATH setup. I.e. you can checkout the code directly into `/workspace/src` instead of `/workspace/src/github.com/...` and you don't have to run `go get -v ./...` at startup because when using modules, `go build` takes care of that based on the content of `go.mod`. This would address https://github.com/gitpod-io/gitpod/issues/57

**Comment by 32leaves** [comment]
We're bumping Go to 1.11.2 in `workspace-full`.

Thank you for the ideas - once tooling becomes more mature for go modules (see https://github.com/Microsoft/vscode-go/wiki/Go-modules-support-in-Visual-Studio-Code, resp. https://github.com/golang/go/issues/24661) this makes total sense as default behaviour. 

Until we have better go module support available, it might make sense to keep the current behaviour s.t. one can use the traditional GOPATH support for tooling. This way `go get -v ./...` still works and one can use `GO111MODULES=on go build ./...` to use go modules.
