### ISSUE TITLE
Improve user experience by overcoming the common issues/questions/struggles

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#10701]
## Is your feature request related to a problem? Please describe

From my personal experience, here's what I've seen being asked the most on our Discord server and other communication channels such as github, frontapp regarding the SaaS Gitpod.io. Trying to braindump all the important points I can think of now.

1. How do I configure my project X for lang/tool Y?
   - How do change the version of Y on my workspace?
> Potential solution: Have lots of useful and **upto date** examples on our docs and have some automation for emails, discord and elsewhere where it makes sense for suggesting docs-pages and github-issues.
> <details>
>  <summary>Example</summary>
> <img width="344" alt="Screenshot 2022-06-16 at 8 25 45 PM" src="https://user-images.githubusercontent.com/39482679/174092076-9366e5e0-dc74-4c7a-ba43-af2b950e06b4.png">
> 
> </details>
>
> ### Related issues:
> - https://github.com/gitpod-io/website/issues/2187
> - https://github.com/gitpod-io/gitpod/issues/10683
> - https://github.com/gitpod-io/website/issues/2227
> - https://github.com/gitpod-io/website/issues/2226

2. Why I can't find the tools/things I configured from `.gitpod.yml` `tasks` (assuming `init` task and prebuilds is enabled)
> Potential solution: use custom dockerfile or `before`/`command` task, but it would be nice if we could automatically detect and warn users during prebuild for files being written outside of `/workspace`. Provide this info via comments on `.gitpod.yml` for auto-generated `.gitpod.yml` (related: [slack discussion](https://gitpod.slack.com/archives/C020VCB0U5A/p1642150398086600))
> ### Related issues:
> - https://github.com/gitpod-io/gitpod/issues/12185
3. Why is my webapp-port/service/websocket is unreachable from program X while it works outside of Gitpod? (assuming web version of Gitpod.io VSCODE)
> Potential solution: Open workspace in desktop vscode or run chrome/firefox(Example templates: [flutter](https://github.com/gitpod-io/template-flutter), [keystonejs](https://github.com/gitpod-io/template-keystonejs)) on Gitpod. Can this somehow be detected for automatic suggestion until we improve the situation on the web-version? 
> ### Related issues:
> - https://github.com/gitpod-io/gitpod/issues/459
> - https://github.com/gitpod-io/gitpod/issues/9262
> - https://github.com/gitpod-io/website/issues/2179
4. How do I : 
   - alter some X file under location Y
   - install or configure tool X

for each of my workspaces
> Potential solution: Utilize dotfiles and it's `install.sh` when necessary.
> Related: [Global-workspace-tailoring](https://www.notion.so/gitpod/Global-workspace-tailoring-a6e9200fb6ae4e7aadb1ef721ef1a14e)
5. Why isn't my workspace opening in local VSCODE, why am I getting asked for password, why can't I connect with the ssh command.
> Potential solution: Make users aware of the troubleshooting tips for SSH issues. Put step by step instructions that must be followed for first-time users to better ensure that their system is properly configured before them attempting to copy-paste the `ssh` command.
> ### Related issues:
> - https://github.com/gitpod-io/gitpod/issues/8513
> - https://github.com/gitpod-io/gitpod/issues/9932
6. Questions about teams and plans. (related: https://github.com/gitpod-io/gitpod/issues/7759)
7. Questions about working with configuring gitpod (related: #7671)
8. Also, our `template-*` repos and `workspace-images` needs more maintenance. (Related: [slack thread](https://gitpod.slack.com/archives/C01LDA27WJC/p1655280898636299))
9. How do I continue my work while gitpod is having downtime/incident?
> Potential solution:
Have a good local fallback([slack discussion](https://gitpod.slack.com/archives/C01KGM9DVRC/p1654816243559629)) + let the users know of the incident during a incident when they try to open a workspace or got disconnected and provide docs link for guidance of what to do.
10. Why am I having permission issues with docker-compose on Gitpod but it doesn't happen locally on my PC?
> Related discord threads:
> - https://discord.com/channels/816244985187008514/816246578594840586/985927978947063839
> - https://discord.com/channels/816244985187008514/816246578594840586/982597242055721000
> - And there was more, can't find them by searching now....
10. Friction and confusion for making Private org repos work on Gitpod.
> Users mostly feel lost about this issue, often we have to tell them to follow this [doc](https://www.gitpod.io/docs/github-integration#errors-with-private-repositories-on-github-orgs) page. Could this be somehow improved or automated?
> ### Related issues:
> - https://github.com/gitpod-io/gitpod/issues/8076
11. IDE is sometimes not fully loaded due to either browser config/extension or network/CORS. As a side effect, this causes other non-existent issues.
> Sometimes the workaround is to try a different browser, use a VPN or open in desktop VSCODE. Could this be somehow improved so that the gets informed about how to troubleshoot it?
> ### Related issues:
> (Please add/suggest)

## Describe the behaviour you'd like

We can try to eliminate the causes for most of the questions and also document the missing parts.

## Additional context

cc @akosyakov @loujaybee

**Comment by akosyakov** [comment]
I think one idea here is to think how we can address them in product by using diagnostics/quick fixes/notifications and other IDE means.

**Comment by axonasif** [comment]
> Some related issues, can you link/add to your description, @axonasif ?

Done @loujaybee 👍

**Comment by axonasif** [comment]
#### New entry added:
-----
11. IDE is sometimes not fully loaded due to either browser config/extension or network. As a side effect, this causes other non-existent issues.
> Could this be somehow improved so that the user knows and gets informed about how to troubleshoot it?
> Related issues:
> (Please add/suggest)

cc @loujaybee @akosyakov
