### ISSUE TITLE
Error build failed when opening a repository created from a template

### ISSUE THREAD

**Issue by NielMc** [gitpod-io/gitpod#1072]
**Describe the bug**

Unable to open a github repository if it is created with a template. 
**To Reproduce**

Used this template https://github.com/Code-Institute-Org/gitpod-full-template
**Expected behavior**

This template has worked with no issues since September. No changes made to it in the last month. 
**Additional Information**

Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: Error response from daemon: No such image: gitpod.io/image-builder/selfbuild:0d43ec8ced752a6866ceff4c4e054184be03c58023cd1270bf5af574a0a2d1cf
Please file an issue if you think this is a bug.

**Comment by jankeromnes** [comment]
Hi @NielMc, sorry about this problem and thank you for reporting it.

This error message is new to me, so I'm looking into what could be causing it. (Additionally, a few hours ago, one of our Europe West 1 servers had a full disk. I'm not sure if this is related, but I know that a full disk can potentially disrupt Docker builds.)

If it's indeed a temporary server problem, there is a chance that simply trying again can solve this error. If not, maybe there could be a problem in the Dockerfile / Gitpod's image builder / the templating system (I'm not yet sure where this comes from exactly).

I'll update this issue when we know more.

**Comment by jankeromnes** [comment]
Aha, in order to recover disk space in the full-disk server this morning, we had to delete all Docker images. This may be the root cause of the error you're seeing.

I'll now ask Kubernetes to stop allocating workspaces on this node, and eventually remove it from the cluster. This should fix it.

**Comment by timoch** [comment]
I realize the issue #1074 I just opened in clearly linked to this. Same error message. 
Any updates ?

**Comment by jankeromnes** [comment]
@timoch, thanks for reporting this too, and sorry for the bad experience.

We've just removed the faulty `image-builder` service, which ran on the server with the earlier disk space problem. A new `image-builder` has started up, so this problem should now be fixed.

(But please reply here if it's still happening.)

**Comment by ivgd01** [comment]
this bug appears again

**Comment by mparkcode** [comment]
Hi there, this bug has appeared again:

Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: Error response from daemon: No such image: gitpod.io/image-builder/selfbuild:d206635ad520e60517fa3ca4c42ca6b2966e0bcce32474021253a2753a0f262f
Please file an issue if you think this is a bug.

Using the same template: https://github.com/Code-Institute-Org/gitpod-full-template

**Comment by rholland** [comment]
Hitting the same error.

```
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: %!w(string=)
Please file an issue if you think this is a bug.
```

**Comment by bramrodrigo89** [comment]
I am experiencing the same issues just now

**Comment by rholland** [comment]
It is happening to me now.
