### ISSUE TITLE
Self-Hosted installation: Resource requirement inconsistency

### ISSUE THREAD

**Issue by julia-leyton** [gitpod-io/gitpod#10726]
### Bug description

As per our [doc](https://www.gitpod.io/docs/self-hosted/latest/cluster-set-up) we require at least 8GB RAM, but we are also triggering a warning: `The cluster must have least 16 GB of memory` on install
![image004](https://user-images.githubusercontent.com/32554329/174286963-f68441bf-3ccf-4a32-a4ce-ac469896c7df.png)
![image003](https://user-images.githubusercontent.com/32554329/174286964-9816f3b5-47e1-4256-b121-d58d3d4f4464.png)

### Steps to reproduce

Install on cluster with <16GB RAM

### Workspace affected

no

### Expected behavior

no warning or update doc to raise requirement to 16GB

### Example repository

N/A

**Comment by lucasvaltl** [comment]
Thanks for raising this @julia-leyton - should be fixed now :)
