### ISSUE TITLE
[Usage-based] Implement a "Cost Center" entity

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#10757]
## Is your feature request related to a problem? Please describe

Until now, we attribute workspace usage hours to Users or Teams directly (which themselves might map to a Stripe Customer).

But, as explained in [this comment](https://github.com/gitpod-io/gitpod/issues/10533#issuecomment-1160159281), it would be good to create an "indirection", and attribute workspace usage to a dedicated "Cost Center" entity.

## Describe the behaviour you'd like

- A new "Cost Center" entity should be created (which can potentially map to a Stripe Customer if payments are enabled)
- All workspace usage hours should get pre-attributed to a "Cost Center" instead of a Team

## Describe alternatives you've considered

We currently attribute directly to a Team or a User. However, this makes some of the logic implicit (i.e. "if no attributed Team, default to workspace owner"), and does not allow future evolutions like sharing a Cost Center between multiple Teams, or having "Organization"-level Cost Centers (once "Organizations" exist)

**Comment by geropl** [comment]
Hey @jankeromnes , thank you for creating an issues for this!

I feel we still need a bit of alignment before we dive into the implementation. I'm not sure about the naming, for instance. "Cost center" feels to me like a different meaning, and we came to use it because we put "Kostenstelle" into Google translate. :laughing: 
E.g., I like "billing account", because it's less ambiguous.
But anyway, we should align on this one. :slightly_smiling_face:

**Comment by geropl** [comment]
> What I don't like about "billing account" is that this directly maps to payments -- e.g. I would expect a "billing account" to be something in Stripe. In Self-Hosted, you may want to track costs without any billing (e.g. just for accounting, or setting up per-team/per-project quotas, etc).

:bulb: Ah, that's a new perspective for me! I always thought about the concept to strictly be a "BillingService" (SaaS) concern. Have to think about the idea that it can also host quotas...

**Comment by jankeromnes** [comment]
**Update**: As an initial simplification, we've started by implementing a unique `usageAttributionId` (new column on `d_b_workspace_instance`):

#10822 

This sort of represents a "cost center" for workspace usage (but without an entity), and can either point to a Team or to a User, e.g.:
- A `team:1234` attribution ID identifies the Team with ID `1234`
- A `user:5678` attribution ID identifies the User with ID `5678`

In the future, if we want to implement a "cost center" entity (for example, to persist limits or quota information), I suggest that we create a new table for them, and use the unique attribution ID as the primary key of that table, e.g.:

```ts
export interface CostCenter {
    id: string;
}
```

(Where `id` is of type `varchar(60)` and can either look like `team:...` or `user:...` -- thus there is no need for extra `userId` or `teamId` attributes.)

**Comment by geropl** [comment]
> > All workspace usage hours should get pre-attributed to a "Cost Center" instead of a Team

> @geropl and @easyCZ, please help with clarifying this. What exactly is the expectation for this point? 

That's outdated here, and already happening, so should not be part of this task anymore.
