### ISSUE TITLE
Delete Poolkeper

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#10759]
## Is your feature request related to a problem? Please describe
The component [poolkeeper](https://github.com/gitpod-io/gitpod/tree/main/dev/poolkeeper) is no longer needed. To reduce complexity and prevent future toil, we should delete it. 

1. The functionality from poolkeeper is needed less because we discontinue preview envs in core-dev.
2. The functionality of poolkeeper can be achieved in simpler ways:
  * Ensure there is at least one node in the nodepool? Set min node count.
  * Ensure kube-system pods don't block cluster-scale-down? Define pod disruption budget.

## Describe the behaviour you'd like
Delete [poolkeeper](https://github.com/gitpod-io/gitpod/tree/main/dev/poolkeeper) from this git repo and the `core-dev` cluster.

**Comment by geropl** [comment]
Awesome that we found better solutions for these problems - let's remove that cruft! :muscle:
