### ISSUE TITLE
QueryFailedError: ER_LOCK_WAIT_TIMEOUT

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#10750]
### Bug description

This June 18 several people reported to be having this issue over on Discord and Email.
<img width="596" alt="Screenshot 2022-06-20 at 8 53 28 AM" src="https://user-images.githubusercontent.com/39482679/174516957-c3288601-c46d-4846-81e5-950a100147fe.png">

However the issue might have been automatically resolved after a few hours.
<img width="611" alt="Screenshot 2022-06-20 at 8 54 35 AM" src="https://user-images.githubusercontent.com/39482679/174517071-de6cc723-8674-4f54-b0e3-b7611fbb4c98.png">

### Steps to reproduce

- Open a workspace.

### Workspace affected

- odinetwork-odinetworkdo-i3swoctkt3c - motitechnologies-moti4-gji5o3mt6qb

**Comment by geropl** [comment]
Thank you for reporting! :pray: We had temporary DB issues which have been resolved yesterday morning around 09:00 CEST.
