### ISSUE TITLE
Record a "prebuild trigger" for every webhook event

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#10764]
Currently users cannot distinguish at-all/easily between:
 - no webhook received at all (installation misconfigured)
 - webhook received but not run due to global rate-limiter
 - webhook received but not run because of user config
 - what caused a particular prebuild to be executed

This issue is the first one in a series that seeks to enable the user to understand just that. To that end, we need to keep track of "prebuild triggers".

To illustrate the idea, this could be possible states for such a prebuild trigger:
 - `created`: webhook was received
 - `ignored_user`: user configured rate limit, not run due to user config, ouf of money, ...
 - `ignored_system`: sanity rate limit, ...
 - `enqueued`: prebuild entry was created (in `queued` state)

A schema could/should contain (at least):
 - trigger id (pk)
 - creationTime
 - triggeredBy: `manual` | `webhook` | `app` (?)
 - state: `created` | `dropped_user` | `dropped_system` | `enqueued`
 - message (string, details on the state)
 - context (JSON, whatever we need from the trigger to start the prebuild)
 - prebuildId (if in `enqueued` state)

**Comment by AlexTugarev** [comment]
Before starting with manifesting the schema, let's take a look at the flow to be backed by it. We need to take into account, that there is a status quo and some iterations to reach the wanted state.


1. We have 4 kinds of webhook receivers for different Git services. Each of them are sending (push) events in a specific shape and level of details. (Some of those details can actually replace the following API call, which are currently done afterwards to gather information to be rendered.)
2. From a push event we derive the context details (context URL, project association, prebuild details, etc.); the context URL is fundamental for the subsequent queries. 
3. A prebuild manager takes care of the actual start requests. Ideally, it should not need to differentiate between provider specific details.
4. Currently, a received push event is directly translated to a prebuild manager call – except for basic filter criteria.


5. Goal: we want to be able to tell when a push event was registered (per context/branch/name-it).
6. Goal: we want to be able to tell if a push event caused a prebuild start.
7. (Future) goal: event reception to be decoupled from prebuild triggering. This should allow for more control.

**Comment by svenefftinge** [comment]
Would be indeed great to generalize the event types and properties over the various gitproviders. @AlexTugarev are you making a proposal?
