### ISSUE TITLE
Add notice to Team Plans about new Team Billing

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#10767]
Suggested text:

> Membership in these Team Plans is managed manually. See [Team Billing](https://www.gitpod.io/docs/team-billing) for auto-subscription.

cc: @jankeromnes

**Comment by gtsiolis** [comment]
See also https://github.com/gitpod-io/gitpod/pull/5121 and https://github.com/gitpod-io/gitpod/issues/5118, in case they contain any useful information.
