### ISSUE TITLE
[dashboard] Better display of workspace names

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#10773]
Users are allowed to _name_ their workspaces - but the name appears at the _end_ of the repo name - and there isn't much space for it!  See here where the names are "latest" and "tapscript-&lt;something-too-long-to-show>":

||
| :--: |
|<img src="https://user-images.githubusercontent.com/4162948/174493133-9178e3c7-bfe3-47a1-b76b-8087eacd51a8.png" width="75%" />|

Maybe put the name first - or on a separate line if it gets too long?  

(Also - of the two workspaces shown above one is pinned, the other not.  It would be nice to have a visual indication of that somehow.)

Names are useful - in some use cases (much) more useful than branch names to keep what's in different workspaces clear in your head - it would be nice to have longer ones. In fact, one reason _I_ spend time deleting inactive workspaces is because the names are relatively useless to tell me which one's which, so I delete the known useless ones to remove some confusion.  Simply folding them away doesn't really help this use case ...

(You might wonder why I have long-lived workspaces when much of gitpod.io's own promotions for its service involve a workflow that frequently creates short-lived branches and merges them immediately.  (E.g., most of your introductory videos - which are very good by the way! - on youtube.)  The reason is that I work on fairly large "features" - and keep going and going on a given branch with `git commit --amend`.  I have several branches in progress at a time - but do all the work in one workspace, generally, switching between them with `git branch` rather than via separate workspaces.  Perhaps it could be considered a more "traditional" workflow? "retro" even?  Or possibly just fuddy-duddy.  Or maybe also (as I believe) it reflects the different nature of working on backend server code vs. web development/full stack development. Or maybe its just me ... but, no, I think it possible other people work this way too ...)

**Comment by geropl** [comment]
@gtsiolis Any thoughts on this?

**Comment by wvffle** [comment]
Dear stale bot, please don't close this issue. Thank you in advance.

**Comment by gtsiolis** [comment]
Thanks for opening this, @david-bakin! The core issue starts with the unnecessary or duplicate information of the context URL, repository name, and workspace description which we allow users to change.

Some improvements described in https://github.com/gitpod-io/gitpod/issues/3594 should already cover mot of the issues raised here.

Differentiating pinned workspaces is something we probably need, follow https://github.com/gitpod-io/gitpod/issues/10921 for updates.

Let me close this in favor of https://github.com/gitpod-io/gitpod/issues/12033 where we're tracking improvements to the workspaces page.

Thanks for the ping, @geropl! 🏓
