### ISSUE TITLE
Slow evaluation of feature flags causes UI issues

### ISSUE THREAD

**Issue by andrew-farries** [gitpod-io/gitpod#10786]
Feature flag evaluation is currently very slow (in the order of a few seconds), which causes UI glitches when page components are rendered/activated on already loaded pages in response to feature flags becoming enabled.

Here the delay in evaluating the 'PVC' feature flag causes the corresponding checkbox to render disabled for several seconds before becoming enabled:

https://user-images.githubusercontent.com/8225907/174745252-9bd22413-431f-4967-a291-40221449b468.mov

**Comment by jankeromnes** [comment]
Thanks for opening this issue @andrew-farries!

FYI, this issue also affects the Usage-Based Billing UI in Team Billing (also behind a feature flag).

> Feature flag evaluation is currently very slow (in the order of a few seconds)

Actually, the delay seems to be a bit random -- sometimes, it's consistently super fast (near instantaneous) on every page load, but other times it seems to take several seconds on each page load.

But, it seems indeed to be more often slow than fast.
