### ISSUE TITLE
Epic: Automate off + onboarding via Public API (users, teams & projects)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10799]
This issue is for public APIs that allow the creation of user, team and projects within Gitpod.

The use case for this is for customers to integrate with existing systems: 

- Automated user management, e.g. integration with auth tooling such as Active Directory
- Scripting of Gitpod resources within infra as code tools, e.g. Terraform 
- Team and project-level environment variable support
- Only allow projects to be created in a specific team (e.g. no personal projects)
- Remove users who have low usage (use-case: a challenge for seat-based pricing [internal link](https://gitpod.slack.com/archives/C01KGM9DVRC/p1663693147741289))

**Note:** When it comes to implementation, this issue might be broken down into sub-epics, this is an initial placeholder.

**Relates to:** 
- https://github.com/gitpod-io/gitpod/issues/10798
- https://github.com/gitpod-io/gitpod/issues/15213
- https://github.com/gitpod-io/gitpod/issues/11335
- https://github.com/gitpod-io/gitpod/issues/10799
- https://github.com/gitpod-io/gitpod/issues/14280
- https://github.com/gitpod-io/gitpod/issues/10427
- https://github.com/gitpod-io/gitpod/issues/15419
- https://github.com/gitpod-io/gitpod/issues/15632
- https://github.com/gitpod-io/gitpod/issues/15829

**Callout:** 👋 Are you interested in this feature? We would be interested to [talk to you](https://calendly.com/lou-gitpod/product-feedback). 

**Public API in private beta**:  See [this issue](https://github.com/gitpod-io/gitpod/issues/15453) for more details.

**Comment by ubshreenath** [comment]
Upvoting this.

**Comment by Cvetk0** [comment]
👍 - looking forward to having an API for team and project management.

**Comment by loujaybee** [comment]
@ubshreenath / @Cvetk0 - if you're still interested, please reach out in the Discord community (https://gitpod.io/chat), we have a private beta channel where you can try out some of the APIs in an early state 🙏
