### ISSUE TITLE
Create `gp info` command

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#10797]
Create a `gp info` command that includes:
- Workspace class name
- Resources available (CPU/RAM/Storage)
- URL
- Workspace cluster and region

To replace the use of the respective environment variables.

----

### Original description

Deprecate all "default environment variables" in favour of either `gp` cli wrapper, or namespaced variables. 

We currently have listed "default" environment variables [listed in the documentation](https://www.gitpod.io/docs/environment-variables#default-environment-variables). For a user to understand which environment variables they can rely on, they have to bounce from the docs to the product. It would be good if they can discover these variables more easily using an approach more familiar to "linux", e.g. through `gp`, and/or `man` pages.

Some preferred experience could be: 

1. Move all default environment variables under `gp`
2. Namespace protected environment variabes with a prefix, etc to make it clear which ones can be relied upon. 

Examples: 
- `GITPOD_IDE_ALIAS ` (https://github.com/gitpod-io/website/pull/2562/files)

**Important:** This doesn't mean breaking backwards compatibility, or removing the env variables (yet) but introducing an alias, or a clear API, such as the `gp` wrapper, to open the opportunity for future removal as an integration point within the product. 

Related issues: 
- https://github.com/gitpod-io/gitpod/issues/10572

**Comment by akosyakov** [comment]
To clarify: env vars are internal implementations of supervisor, they are there, but they should not be surfaced to user in docs, rather `gp cli`.

**Comment by atduarte** [comment]
@loujaybee Are there other env vars that you believe should be converted into a `gp` command other than the workspace class / info?

**Comment by loujaybee** [comment]
@atduarte not that i know off the top of my head, would need to audit / look through the current variables.

**Comment by atduarte** [comment]
@loujaybee based on that changed the issue to be more actionable to the workspace team. LMKWYT
