### ISSUE TITLE
Epic: Workspace Classes on Self-Hosted

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#10805]
### Summary

Productise workspace classes for self-hosted.

### Context

After https://github.com/gitpod-io/gitpod/issues/8261.

We are unsure what capabilities that previous epic will bring to self-hosted admins, and what the experience will look like. This epic will be the follow-up to ensure that those concerns are taken care of.

### Value

Self-hosted customer will be able to provide differentiated workspace resources for different people, optimizing the use of their resources.

### Acceptance Criteria

* Self-hosted admins should be able to define multiple workspace classes, at installation time. (Kots, self-hosted team)
* Self-hosted admins should be able to control the type of underlying node, node density and CPU/IO/network/RAM limits of each workspace class. (Docs, Workspace team)
* Provide self-hosted admin guidance on how what limits (Kubernetes and ws-daemon) and nodes to use, and how to optimize resource usage for the customers workload (which ultimately influences the density per node per workspace class). (Docs, Workspace team)

### Measurement

Number of customers using the feature.

**Comment by ynedelec** [comment]
Hi,
This would be very, very valuable to us.

Without diving into too much details, our data scientists would use Gitpod for both software development and exploratory analysis. While the former doesn't require high specs environments, the later could have drastically different needs in term of CPU or RAM.

This is why having the possibility to trigger Gitpod workspaces with different specs is a requirement for us.

**Comment by kylos101** [comment]
@atduarte closing because this was for self-hosted. Feel free to reopen and update if needed for Dedicated.
