### ISSUE TITLE
Workspaces taking way too long to start

### ISSUE THREAD

**Issue by filipedeschamps** [gitpod-io/gitpod#1081]
**Describe the bug**
Workspaces taking way too long to start. It keeps hanging in a "Starting..." screen even if the container is already created.

**To Reproduce**
Just append the `gitpod.io/#` to a repository URL.

**Expected behavior**
Faster first and consecutive boots.

**Additional Information**
Since yesterdays' instability, things feel slower than usual.

**Comment by JesterOrNot** [comment]
Can you send a screencast?

**Comment by filipedeschamps** [comment]
Not a screencast, but a screen shot from the network:

![image](https://user-images.githubusercontent.com/4248081/72362835-b3f7f980-36a8-11ea-9d02-9d18ca6909e9.png)

**Comment by filipedeschamps** [comment]
And if I look and the workspaces list, it's there:

![image](https://user-images.githubusercontent.com/4248081/72362993-e570c500-36a8-11ea-9c0b-4b0ae1f3eec9.png)

But the previous page keeps looping

**Comment by jankeromnes** [comment]
Hi @filipedeschamps! Sorry about this problem.

This looks like a saturated WebSocket. Could you please close any browser tabs that have a "stopped" workspace in them, then see if the problem goes away after a minute or so?

(Stopped workspace tabs are currently very noisy on the WebSocket link, causing the browser to temporarily rate-limit all Gitpod websockets, which we use for status updates everywhere in the app).

**Comment by filipedeschamps** [comment]
Clicked on Open and after a while on "Starting..." state, I got this:

![image](https://user-images.githubusercontent.com/4248081/72363164-37b1e600-36a9-11ea-97df-8ece76f7a531.png)

**Comment by jankeromnes** [comment]
Does your DevTools Console have any warnings or errors explaining why all these requests get cancelled or disposed?

**Comment by filipedeschamps** [comment]
@jankeromnes I didn't have it open in this second screenshot, but maybe it is something related to the `https://gitpod.io/api/refresh-login` url... it's not opening the workspace list anymore.

**Comment by jankeromnes** [comment]
I think the `https://gitpod.io/api/refresh-login` URL was failing yesterday due to very long API response times from GitHub: https://github.com/gitpod-io/gitpod/issues/1075#issuecomment-574216860

Or is it failing again now?

**Comment by filipedeschamps** [comment]
@jankeromnes now, oscillating actually

**Comment by filipedeschamps** [comment]
Trying to open the workspace:

![image](https://user-images.githubusercontent.com/4248081/72363585-f241e880-36a9-11ea-9174-bcc6ae85b4e0.png)

![image](https://user-images.githubusercontent.com/4248081/72363638-01c13180-36aa-11ea-82d0-e13d64b30147.png)

**Comment by filipedeschamps** [comment]
After forcing a refresh on the workspace final URL (with the id) I eventually got in 👍

**Comment by filipedeschamps** [comment]
But something still not right, I can't access the public URL with an HTTP service running on port 3000 using Node.js. It does not reach the server and it's returning an Nginx 500 error

![image](https://user-images.githubusercontent.com/4248081/72366967-2fa97480-36b0-11ea-9eb7-20509335b693.png)

**Comment by filipedeschamps** [comment]
The public URL started to become more stable now 👍

**Comment by filipedeschamps** [comment]
Workspace list also, very fast and stable 👍

**Comment by filipedeschamps** [comment]
Everything looks stable now 👍

**Comment by jankeromnes** [comment]
@filipedeschamps I'm glad that it started working again, many thanks for the update!

The nginx 500 error on the workspace port proxy is new, and seems to only affect the US for now. We're looking into it.

**Comment by filipedeschamps** [comment]
@jankeromnes looks like `https://gitpod.io/api/refresh-login` started to hang again and workspaces aren't being listed anymore.

**Comment by jankeromnes** [comment]
Thanks for reporting! Yesterday was terrible 😞 this problem was likely due to https://github.com/gitpod-io/gitpod/issues/1075

Sorry again, and please let me know if you're still having issues.

**Comment by filipedeschamps** [comment]
Yes, issue resolved 👍
