### ISSUE TITLE
Sorry, something went wrong 😓 Error 504  It will not let me in to my workspaces; can get into github.com just fine

### ISSUE THREAD

**Issue by BobHerold** [gitpod-io/gitpod#1082]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by filipedeschamps** [comment]
I'm not on Gitpod team but looks like it's fixed: https://github.com/gitpod-io/gitpod/issues/1081

**Comment by jankeromnes** [comment]
FYI the `Error 504` problem seems to be happening again: #1151. We're currently investigating it and will try to restore service as fast as possible. Sorry for the disruption.
