### ISSUE TITLE
Dotnet (.Net) with VSCode Locally doesn't work with default `tasks.json`

### ISSUE THREAD

**Issue by joeizy** [gitpod-io/gitpod#10831]
### Bug description

When I use VSCode locally, the auto-generated Run & Debug doesn't work. I get the error: `The terminal process failed to launch: Path to shell executable "dotnet" is not a file or a symlink.`

<img width="533" alt="image" src="https://user-images.githubusercontent.com/11180858/173576694-225d5548-c963-4bee-aedf-3185bd299f70.png">

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/11180858/173559716-447dce01-5a28-452b-a964-362edad8bab0.png">

This happens even when using the https://github.com/gitpod-io/template-dotnet-core-cli-csharp template.

### Steps to reproduce

1. Navigate to template dotnet project https://github.com/gitpod-io/template-dotnet-core-cli-csharp 
2. Open in GitPod
3. Open that workspace VSCode locally
4. Install the C# extension in VSCode
5. Click Yes to add the required assess for build & debug.
![image](https://user-images.githubusercontent.com/11180858/175072129-a517c4a7-d96c-4446-8ae6-8faf8af1311b.png)
6. Click the "Run & Debug" button
<img width="533" alt="image" src="https://user-images.githubusercontent.com/11180858/173576694-225d5548-c963-4bee-aedf-3185bd299f70.png">

Notice that this works fine the browser.

### Expected behavior

The console app should run and debugger should attach in VSCode Local in the same way that it does when running VSCode in Browser.

NOTE: When you click "Run & Debug" button in VSCode (browser or local) it generates two files `.vscode/launch.json` and `.vscode/tasks.json`. The files which are generated by VSCode browser and VSCode local are identical.

### Example repository

The issue is reproducible with the [GitPod Dotnet Sample](https://github.com/gitpod-io/template-dotnet-core-cli-csharp) or any blank dotnet project such as one created with `dotnet new <template_name>` such as `dotnet new console`.

Here are two workarounds I was able to find but neither is ideal because you should be able to run `dotnet new`, open in vscode desktop, and immediately hit debug/run.

1. [change build tasks to 'shell' from 'process'](https://github.com/joeizy/gitpod-template-dotnet-core-cli-csharp/commit/dfa2447669c9aafc0882448cc38b65c36c3101d7) in branch [working-task-as-shell](https://github.com/joeizy/gitpod-template-dotnet-core-cli-csharp/tree/working-tasks-as-shell)
<img width="533" alt="image" src="https://user-images.githubusercontent.com/11180858/173577246-40e254f3-5a89-451a-bffd-2be9deaff9f6.png">

2. [change build task command - full path to dotnet](https://github.com/joeizy/gitpod-template-dotnet-core-cli-csharp/commit/c3a3f55bf6176b618c798d6d4883851641ee1bf8) in branch [working-command-full-path](https://github.com/joeizy/gitpod-template-dotnet-core-cli-csharp/tree/working-command-full-path)
<img width="536" alt="image" src="https://user-images.githubusercontent.com/11180858/173577307-55828de9-72c1-4eeb-b576-15e49eabe032.png">

These workarounds do not break vscode in browser.

**Comment by 0xakihiko** [comment]
I'm also experiencing this

**Comment by akosyakov** [comment]
@kylos101 @aledbf @ghuntley Is it the same like https://github.com/gitpod-io/gitpod/issues/10122

I'm trying to reproduce and getting as well:
"The terminal process failed to launch: Path to shell executable "dotnet" is not a file or a symlink."

I don't think there is something to change in IDE, it is rather template shoudl be changed or something wrong with dotnet setup in workspace images.

**Comment by tobil4sk** [comment]
I just came across this when searching for an issue I was experiencing with an unrelated project. In case this is any help, this is the issue that is causing the error: https://github.com/microsoft/vscode/issues/106661. Unfortunately, it doesn't seem like it'll get fixed.

You probably have a `dotnet` folder in your home directory (which might be the PWD of vscode). When the task is run as a `process`, for some reason this folder gets in the way and this error is shown before it is even able to look for a `dotnet` executable in `PATH`.

**Comment by tobil4sk** [comment]
Just to update, https://github.com/microsoft/vscode/pull/158666 has been merged. With the next vscode release this issue should be resolved.

**Comment by axonasif** [comment]
cc @jeanp413 @akosyakov

**Comment by akosyakov** [comment]
@tobil4sk It should be in VS Code insider on our side already. Select **latest** in https://gitpod.io/preferences and try.

**Comment by jeanp413** [comment]
Closing this as @tobil4sk PR got merged upstream, you can test it by installing vscode-desktop insiders
