### ISSUE TITLE
[preview envirionments] run with cgroup v2

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#10832]
## Is your feature request related to a problem? Please describe

`gen49` is switching to cgroup v2; preview environments should have parity with production.

## Describe the behaviour you'd like

Upgrade preview environments to use cgroup v2.

## Describe alternatives you've considered

n/a

## Additional context

The image has been updated in other issues [like so](https://github.com/gitpod-io/gitpod/issues/9684).

The latest image which supports cgroup v2 [is internal](https://github.com/gitpod-io/gitpod-packer-gcp-image/releases/tag/gitpod-k3s-202206202141). This uses K3s 1.24, and uses systemd as the cgroupDriver.

## How to test
```
gitpod /workspace/template-python-flask (main) $ ls /sys/fs/cgroup/cgroup.controllers
ls: cannot access '/sys/fs/cgroup/cgroup.controllers': No such file or directory
```

The above file should exist (thanks, @Furisto !), but is what we currently get in preview environments.

**Comment by meysholdt** [comment]
reopening, because we needed to revert the PR here: https://github.com/gitpod-io/gitpod/pull/10989

reasons: 
* https://gitpod.slack.com/archives/C032A46PWR0/p1656448245444129
* https://github.com/gitpod-io/gitpod/pull/10987#issuecomment-1169389161

**Comment by ArthurSens** [comment]
Now that we reverted it, how do we proceed here? Could you point us to a new image that you'd like to have in preview environments @kylos101 ?

**Comment by kylos101** [comment]
Hey @ArthurSens , could you try a branch with [this image](https://github.com/gitpod-io/ops/blob/main/deploy/workspace/common.sh#L33), which is what we're using "now"? Also, is it possible to test that we can start workspaces using the image, prior to merging back to main?

cc: @aledbf

**Comment by ArthurSens** [comment]
> Also, is it possible to test that we can start workspaces using the image, prior to merging back to main?

That is an interesting question, I believe I did test it... I tried opening workspaces and they started 🤔 

Not sure how to tell if my tests were correct or not though. I'll try to hold the merge until someone from workspace team made the tests as well, is that ok?

**Comment by kylos101** [comment]
@ArthurSens adding you as an assignee on this because of the open PR. Is this okay? I'm not sure if this fits into your current week plan for Platform.

**Comment by ArthurSens** [comment]
> @ArthurSens adding you as an assignee on this because of the open PR. Is this okay? I'm not sure if this fits into your current week plan for Platform.

Hi Kyle, unfortunately I don't plan to work on this issue this week. I think the way our teams are interacting on this one can definitely improve and the task is taking a lot longer than it should because of it 😬 

I've spoken with @meysholdt in our last team sync, and I believe he'll set up a call so both teams can share knowledge about:
* Different ways to setup cgroupv2
* Different ways we can configure kernel parameters during boot of preview environments

After we're aligned about what needs to be done, I hope we can finally have some progress!

**Comment by kylos101** [comment]
@ArthurSens :+1: thanks for the heads up! 

@meysholdt :wave:,

For this issue, our goalis to have preview environments run with cgroup v2. 

@jenting and @utam0k were asking about having a werft annotation to have the ability to go back and forth from cgroup v2 to v1 (depending on the annotation), but, that is outside the scope of this ask and should be a separate issue. In other words, that is just a nice to have, and is not required for now.

I'm not sure why the image doesn't work "as is". Based on the testing that was done in the related PR, it sounds like cgroup v1 is still being used. I recommend inspecting the the grub boot loader config, to see if what's being used in Harvester is different than what we're using in the Packer image. For example, harvester may be mutating the image we provide, after importing it, such that the grub parameters are being changed, thus avoiding cgroup v2.

Let me know if that helps, and if you need anything else. :pray:
