### ISSUE TITLE
Cannot access any Gitpod sites after logging in...

### ISSUE THREAD

**Issue by cruizfun** [gitpod-io/gitpod#1083]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by filipedeschamps** [comment]
I'm not on Gitpod team but looks like it's fixed: https://github.com/gitpod-io/gitpod/issues/1081

**Comment by jankeromnes** [comment]
Closing this issue for now. Please comment again if this bug happens again.

**Comment by cruizfun** [comment]
It is happening again. I try to access my workspaces dashboard and the page is just blank.

**Comment by cruizfun** [comment]
I am also experiencing server issues. Either the server does not respond or it is painfully slow.
