### ISSUE TITLE
Support deprecated extensions in vscode

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#10847]
VS Code now supports showing deprecated extension in extension view. It's controlled by `extensionsGallery.controlUrl` property in `product.json` providing a url to a json file. This json file contains a list of deprecated extensions.
We need to investigate how we should serve this json file for us to consume in our vscode fork

[Upstream PR ](https://github.com/microsoft/vscode/pull/149697)

RFC done by @filiptronicek 
https://www.notion.so/gitpod/RFC-Add-an-Open-VSX-wide-extensions-json-c3a1a8132bb5495db099a484fcc0ecde

Example: 
![image](https://user-images.githubusercontent.com/25115070/175199940-3913cb98-8e95-49b2-b98e-beea30ea52db.png)

**Comment by akosyakov** [comment]
@filiptronicek maybe you can take it to OpenVSX to consider to expose us such endpoint or for add such on our ide proxy and you will curate it?

**Comment by jeanp413** [comment]
I talked with Filip about this:
- hosted by open-vsx but not sure how good that would be, if we want to update it will take a long time until deployed
- host it ourselves it would be really easy served by ide proxy
- Filip suggested to be in openvsx github repo and just use github url to the json file
