### ISSUE TITLE
Customers should be able to select their preferred workspace class

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#10843]
## Is your feature request related to a problem? Please describe
Support https://github.com/gitpod-io/gitpod/issues/8261

## Describe the behaviour you'd like
As a user of Gitpod, I would like to select the workspace class that is used for regular and prebuild workspaces.

## Describe alternatives you've considered
n.a.

## Additional context
Affected components:
- Dashboard
- gitpod-protocol
- gitpod-db
- ws-manager-api
- server

**Comment by kylos101** [comment]
@Furisto this issue is still open, but the status is awaiting deployment. 🤔 

Is there a PR that can be linked to this issue? 🙏 

I ask because I'm sanitizing our Awaiting Deployment column. 🧹
