### ISSUE TITLE
Bug in GitPod Spring PetClinic sample

### ISSUE THREAD

**Issue by opus111** [gitpod-io/gitpod#1085]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by jankeromnes** [comment]
Thanks @opus111 ! Please describe the bug:

- what did you try?
- what did you expect to happen?
- what happened instead?

Also, often screenshots help a lot. Thanks!

**Comment by jankeromnes** [comment]
Closing due to lack of actionable information.
