### ISSUE TITLE
[billing] Create a dedicated Stripe account for production

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#10856]
We want to create a new Stripe account to use for Production.

* [x] Ensure production environment is updates with API keys for the new account
* [x] Configure products in the production account
* [x] Update Product IDs in production
* [x] Configure branding of the production account
* [x] Configure customer portal in the production account

**Comment by jankeromnes** [comment]
Thanks @easyCZ! Added two items:

> * Configure branding of the production account
> * Configure customer portal in the production account

**Comment by jankeromnes** [comment]
We'll also want to add the credentials to 1Password, and possibly use more restricted API keys (i.e. not just a single private key that can do everything, but maybe one key that can only create customers / subscriptions / payment methods / submit usage)

**Comment by jankeromnes** [comment]
All done and live! ✅
