### ISSUE TITLE
Per node label memory requirements & preflight checks

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10867]
## Is your feature request related to a problem? Please describe
Currently, we have a single memory requirement for every node - 16gb. However, not all of our components are created equal, and some require more memory than others. E.g. the main driver of the 16gb memory need are the workspace nodes (i.e. image-builder). Non-workspace nodes may require less. 

## Describe the behaviour you'd like
A more granular approach to memory requirements that respects the actual components that will be scheduled on a node. 
- get definitive memory/CPU requirements for all [5 of the node labels](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/cluster/affinity.go#L9) from the appropriate teams, mention this in our requirements and we apply the pre-flight checks on a per node label basis
- This should also be reflected in our reference architectures

## Describe alternatives you've considered
- Keep current one-size-fits-all - while it "works", it is not very resource efficient.

## Additional context
- Internal [slack conversation](https://gitpod.slack.com/archives/C01KLC56NP7/p1655987771833879?thread_ts=1655986020.829029&cid=C01KLC56NP7)

## Tasks

- [x] #11344
- [ ] #11347
- [ ] Update the reference architectures/docs

**Comment by Pothulapati** [comment]
Should we close this? 🤔 Wondering if there is anything left here (to take up)!

**Comment by lucasvaltl** [comment]
I believe we can close this yes
