### ISSUE TITLE
My IDE loaded into "unauthenticated" state again

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#10864]
### Bug description

I just now opened https://github.com/gitpod-io/gitpod in Gitpod (production, stable VS Code browser).

Unfortunately, I landed in the same bad state as when https://github.com/gitpod-io/gitpod/issues/8703 was happening, so this might be a regression.

### Symptoms

| Wrong theme (Light instead of Dark) | Cannot Stop Workspace | Cannot push to Git |
| --- | --- | --- |
| <img width="600" alt="Screenshot 2022-06-23 at 14 29 52" src="https://user-images.githubusercontent.com/599268/175299501-ae8fed26-5ac5-471d-beba-7b5570e3c3cc.png"> | <img width="600" alt="Screenshot 2022-06-23 at 14 30 13" src="https://user-images.githubusercontent.com/599268/175299515-0ff0ff4e-adbd-4206-8c04-0538004e17b0.png"> | <img width="600" alt="Screenshot 2022-06-23 at 14 32 36" src="https://user-images.githubusercontent.com/599268/175299516-68613549-b7ba-4849-88ce-c053264fe523.png"> |

### Steps to reproduce

1. Open a new workspace
2. Sometimes, it randomly lands in a bad state where you cannot work

The only workaround is to stop the workspace.

### Workspace affected

https://gitpodio-gitpod-d2329h6tyfd.ws-us49.gitpod.io/

**Comment by akosyakov** [comment]
Could you please check settings sync ouput of your workspace for any errors?

**Comment by akosyakov** [comment]
@jeanp413 @andreafalzetti logs are here: https://gitpod.slack.com/archives/C03L5B9N6BA/p1655990181004239?thread_ts=1655988434.203009&cid=C03L5B9N6BA Could you investigate please? 🙏

**Comment by akosyakov** [comment]
@jankeromnes @AlexTugarev @geropl For some reasons supervisor cannot find a token for Gitpod API agin. I moved to webapp team.

**Comment by akosyakov** [comment]
I think it is the same like: https://github.com/gitpod-io/gitpod/issues/8703

**Comment by geropl** [comment]
The conclusion fro #8703 (and similar issues) has been:
 - we reduced likelihood of [this happening](https://github.com/gitpod-io/gitpod/issues/8703#issuecomment-1104391630)
 - but still might happen until we "get rid of OTS" ([#10134](https://github.com/gitpod-io/gitpod/issues/10134))

**Comment by geropl** [comment]
I'd like to close this as symptom of #10134
