### ISSUE TITLE
Opening workspace fails due to CORS error (ws-us47)

### ISSUE THREAD

**Issue by tnir** [gitpod-io/gitpod#10862]
### Bug description

Visual Studio Code for Web is not opened completely with the following CORS error in browser console:
```
Access to internal resource at 'https://blobserve.ws-us47.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-5cff80fdce975a70553712505e3eebf73bfdf5fa/__files__/manifest.json' (redirected from 'https://[workspace-name].ws-us47.gitpod.io/manifest.json') from origin 'https://[workspace-name].ws-us47.gitpod.io' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

### Steps to reproduce

1. Open a new workspace
2. Stop the worksapce
3. Re-open the workspace

### Workspace affected

gitlaborgcharts-gitlab-pw8jc7j83hx

### Expected behavior

Open the workspace correctly

### Screenshot

![for-a-long-time](https://user-images.githubusercontent.com/10229505/175325560-367a8446-a479-4a83-9cfe-ab4e53025958.png)

**Comment by aledbf** [comment]
Closing. The traffic to `blobserve.xxxxxxx` is now exposed through `ide.gitpod.io`.

We started the traffic shift to eu49 and us49.

**Comment by aledbf** [comment]
Reopening and assigning the issue to the IDE team

**Comment by tnir** [comment]
Thanks @aledbf for reopening.

@jeanp413 I just added the screenshot to the issue description. I cannot get any log since Gitpod does not accept any of my input, which is as same as every time I ran into.

**Comment by akosyakov** [comment]
@tnir You can get logs from browser devtools.

**Comment by tnir** [comment]
After errors for a few hours, my environments are now alive. Let me close this and open a new one with linking here when I run into this again. Thank you.

@akosyakov I will use it to get logs!
