### ISSUE TITLE
Hello, just want to know how could I debug in Golang...

### ISSUE THREAD

**Issue by jackjieYYY** [gitpod-io/gitpod#1087]
I could run the "go run main.go" command to run the go file but while I tiring to debug the code it always said no permission...

could not launch process: fork/exec /workspace/Golearning/HelloWorld/__debug_bin: operation not permitted

![image](https://user-images.githubusercontent.com/53422254/72457407-a6628100-381a-11ea-9cd7-e339d69d49ec.png)

and this is the access control as you can see all the access I have given

![SKV`@{6W92}NJ5)M896 P1U](https://user-images.githubusercontent.com/53422254/72457664-3a344d00-381b-11ea-8b82-eb6b125f52d4.png)

thanks！
Regard!

**Comment by JesterOrNot** [comment]
@jackjieYYY 
Unfortunately ptrace is not enabled within workplaces yet however ptrace will be enabled soon!

**Comment by jackjieYYY** [comment]
> @jackjieYYY
> Unfortunately ptrace is not enabled within workplaces yet however ptrace will be enabled soon!

thanks for your annswer

**Comment by jankeromnes** [comment]
FYI this will be fixed at the same time as #544 in the next few weeks. 🙂

**Comment by svenefftinge** [comment]
deployed
