### ISSUE TITLE
ws-manager: Add volume snapshot related events to workspace pod event log

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#10887]
It would be great if we could add events to workspace pod that show the progress of volume snapshot operations: `kubectl describe pods`
That way it will be easier to debug later on if workspace pod is stuck or misbehaving.

Thanks @aledbf for an idea!

Related to epic: https://github.com/gitpod-io/gitpod/issues/7901

**Comment by sagor999** [comment]
@jenting would like to look into this one? (not a high priority)

**Comment by jenting** [comment]
Sure
