### ISSUE TITLE
Switch gitpod team (eating your own dog food) to using PVC - regular workspaces only

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#10886]

**Comment by sagor999** [comment]
@kylos101 I would like to switch gitpodders to using PVC feature on Monday (June 27th)
That would be only for new workspaces. (will not apply to prebuilds)

**Comment by aledbf** [comment]
> I would like to switch gitpodders to using PVC feature on Monday (June 27th)

Not in SaaS right?

**Comment by sagor999** [comment]
In SaaS indeed. I assume you have objections? @aledbf 
That would enable the part where when you start a new workspace, it will use PVC and load any prior data from GCS.
But not enabled for prebuilds, since that PR is not merged yet.

**Comment by aledbf** [comment]
> In SaaS indeed. I assume you have objections? @aledbf

I think it is too risky to do it that way. I think it would be better to use a workspace class, meaning a separated node pool. Then, in case of any issue, the blast radius is limited to only a few nodes running only PVC workspaces from the team.

The problem with that idea is that we need to wait for Thomas work on workspaces classes :(

**Comment by sagor999** [comment]
Not entirely agree on it being too risky.
If anything, there is much less dependence on ws-daemon with PVC approach. So if anything, it should be more reliable, considering that ws-daemon crashes often. 
Waiting for workspace classes will delay PVC roll out even longer.

**Comment by kylos101** [comment]
Removing from scheduled work for now (as you and JenTing are largely testing in ephemeral clusters, and will test later, probably gen61, with dedicated nodes).

**Comment by kylos101** [comment]
@sagor999 may I ask you to create an issue to track whether `chown` can be removed for PVC, and add it to the epic as a day 2 item?  I say this because I am skeptical we can remove for PVC "now".

For now, it seems like it depends whether the git content init was done from a prebuild versus a regular workspace. [Example](https://github.com/gitpod-io/gitpod/issues/12420#issuecomment-1242624855).

**Comment by sagor999** [comment]
@kylos101 done: https://github.com/gitpod-io/gitpod/issues/12892

**Comment by kylos101** [comment]
@sagor999 gonna close this issue, as there are no PRs linked to it, and we're using the Notion doc to plan release deploys/release.
