### ISSUE TITLE
work spaces not loading

### ISSUE THREAD

**Issue by Badwolf369** [gitpod-io/gitpod#1088]
**Describe the bug**
Errors continually show up saying "Connection got disposed"
work spaces page loading incredibly slowly or not at all

**To Reproduce**
go onto work spaces. that loads very slowly, if at all. if it does load, start any work space. it will either freeze on the loading screen or get an error saying "connection got disposed"

**Expected behavior**
I expected the work space page to load and my work spaces to start

**Additional Information**
line upon line 
of "connection got disposed" and "Invariant Violation: Minified React" from devtool console
![Capture](https://user-images.githubusercontent.com/22065391/72457959-87adad00-377c-11ea-96f8-f63e6dbe7062.PNG)

**Comment by jankeromnes** [comment]
Thanks a lot for filing this issue, and sorry about this problem. I think it was linked to a recent incident in our US region: https://github.com/gitpod-io/gitpod/issues/1075

This incident is now resolved, so I'll close this issue. Please let me know if you're still having issues though.
