### ISSUE TITLE
Cannot clone git repo with ssh submodules

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#109]
Some repositories users have reported that they are no longer able to start workspaces.
They see the message below:

<img width="440" alt="screen shot 2018-10-22 at 08 17 43" src="https://user-images.githubusercontent.com/372735/47279733-3f342d80-d5d3-11e8-8fce-b90bb2dab3cd.png">

**Comment by svenefftinge** [comment]
> This seems to be related to GitHub outage. Now it is working again.

There were lots of issue because of the GitHub outage, but this one is real.
But it only affects github repos with submodules, where the submodule URLs are SSH URLs (or pointing to dead repos, we saw one case).

We need to be more graceful in those cases and refrain from the deep clone and tell the user about it.

**Comment by svenefftinge** [comment]
@32leaves was this solved already?

**Comment by 32leaves** [comment]
This is fixed in master and will be deployed with the next release.
