### ISSUE TITLE
gitpod wont open

### ISSUE THREAD

**Issue by gabsrodriguez** [gitpod-io/gitpod#1090]
Good afternoon! Having trouble accessing my project. Gitpod wont open. Getting a "500 internal server error"

**Comment by jankeromnes** [comment]
Hello! Thank you for filing this issue, and sorry about this problem. I think it was linked to a recent incident in our US region: https://github.com/gitpod-io/gitpod/issues/1075

This incident is now resolved, so I'll close this issue. Please let me know if you're still having issues though.
