### ISSUE TITLE
Requesting Fig integration 

### ISSUE THREAD

**Issue by RostyslavDzhohola** [gitpod-io/gitpod#10917]
## Is your feature request related to a problem? Please describe
 In my Terminals, I use Fig autocompletion feature for commands. It saves time and a great tool to navigate folders through terminal.

## Describe the behaviour you'd like
Autocomplete and suggesting feature provided by Fig.

## Describe alternatives you've considered
 https://fig.io/   This is what I am using right now.

## Additional context

<img width="769" alt="image" src="https://user-images.githubusercontent.com/30268115/175791078-d9f76acb-0e12-4a4f-86f2-38cb332dcb53.png">

**Comment by benvp** [comment]
Are there any plans for integrating fig?

**Comment by axonasif** [comment]
Hey @RostyslavDzhohola, do you need the fig integration for when you ssh into Gitpod from your terminal?

**Comment by benvp** [comment]
That would be my usecase. Tried with installing the ssh integration but this didn't work for me.
