### ISSUE TITLE
Error 504

### ISSUE THREAD

**Issue by sharoon-c** [gitpod-io/gitpod#1091]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by JesterOrNot** [comment]
A little more context, i.e screenshots?

**Comment by ThomasThelen** [comment]
I'm seeing this after trying to login with GitHub.

1. Click `Login`
1. Click `github.com`
1. See GitHub Authorization Page
1. Authorize
1. See a blank page, with `Waiting for gitpod.io`
1. See call to `https://gitpod.io/auth/github/callback?code=MyCoDe` never finishes

<img width="1554" alt="Screen Shot 2020-01-15 at 3 52 23 PM" src="https://user-images.githubusercontent.com/9289652/72481343-120f0480-37af-11ea-9285-496f01a4ff01.png">

**Comment by jankeromnes** [comment]
Thank you for filing this issue, and sorry about this problem. I think it was linked to a recent incident in our US region: https://github.com/gitpod-io/gitpod/issues/1075

This incident is now resolved, so I'll close this issue. Please let me know if you're still having issues though.

**Comment by jelaniwoods** [comment]
This is still happening to me.

**Comment by jankeromnes** [comment]
Thanks @jelaniwoods, and sorry about that. We're aware that this problem is happening again and we're actively investigating it. We'll post any updates in #1151.
