### ISSUE TITLE
Distinguish between pinned workspaces and recent workspaces in dashboard

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#10921]
It would be helpful to show an indicator for pinned workspaces in the workspaces list.
![Screenshot 2022-06-27 at 12-33-40 Workspaces — Gitpod(1)](https://user-images.githubusercontent.com/39482679/175897571-64ac3786-9107-4423-97d5-ff0b4b47480f.png)

**Comment by gtsiolis** [comment]
I just love how this is now hiding 44 workspaces for you, @jldec! ✨

**Comment by gtsiolis** [comment]
Closing this in favor of UX-47.
