### ISSUE TITLE
[jb] add a warning if runtime Xmx is different from configured 

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#10924]
An idea is to detect a user change to the actual max heap size in the backend plugin and suggest a user to put in .gitpod.yml to persist. So the flow would be like:
- a user starts using with default Xmx
- experience perf issues and follow notifications to upgrade Xmx of the running instance
- after JB backend restart there will be a warning on .gitpod.yml that Xmx of the running instance was changed, but it should be applied to .gitpod.yml to be persistent

@yaohui-wyh Maybe you can have a look how we can validate .gitpod.yml? Basically add a warning on .gitpod.yml or on a project if the file is missing if configured Xmx at runtime is different from default one. Later we can add a quick fix to add it into .gitpod.yml

**Comment by yaohui-wyh** [comment]
Hi Anton! Sure, I would look into it.

**Comment by akosyakov** [comment]
I would start with 1 and then we can refactor to 2 if necessary. Do you need pointers about how to get yaml AST, modify and so on?

**Comment by akosyakov** [comment]
there is yaml plugin already, so it should work
