### ISSUE TITLE
Cannot open space

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1093]
**Describe the bug**
Unable to open space, get this:

Sorry, something went wrong 😓
Error: Connection got disposed.
Please file an issue if you think this is a bug.

**To Reproduce**
Url used: https://gitpod.io/#https://github.com/4GeeksAcademy/flask-rest-hello

**Expected behavior**
Space to open

**Additional Information**
Have had a number of issues trying to open over the past few days, though with some successes, first time posting. Students in class have also experienced the same issue.

**Comment by jankeromnes** [comment]
Thank you for filing this issue, and sorry about this problem. I think it was linked to a recent incident in our US region: https://github.com/gitpod-io/gitpod/issues/1075

This incident is now resolved, so I'll close this issue. Please let me know if you're still having issues though.

**Comment by ColbyWTaylor** [comment]
Hi @jankeromnes - At this moment it is working, but I'm still experiencing the same issue throughout the day, along with my students. Would this be related?
