### ISSUE TITLE
Git commit or amend not working

### ISSUE THREAD

**Issue by jayanthantw** [gitpod-io/gitpod#10958]
### Bug description

When trying to commit some changes in git pod workspace the terminal shows a message stating 

`hint: Waiting for your editor to close the file`

<img width="793" alt="Screenshot 2022-06-28 at 12 57 42 PM" src="https://user-images.githubusercontent.com/92082070/176119871-24cdb0ae-cf6a-404a-89ec-5308019bfe78.png">

### Steps to reproduce

- open any git repo in gitpod 
- make some changes 
- add the changes
- Try committing it using `git commit` command

### Expected behavior

The terminal should open a interactive console to type the commit message

### Example repository

https://gitpod.io/#snapshot/91004a45-9c20-4cf1-baf4-c29ad9a1c0e1

**Comment by svenefftinge** [comment]
What editor do you use with Gitpod? We are configuring the `EDITOR` variable so it uses and opens the commit message editor in your IDE.

**Comment by jayanthantw** [comment]
> What editor do you use with Gitpod? We are configuring the `EDITOR` variable so it uses and opens the commit message editor in your IDE.

Vscode Browser

**Comment by axonasif** [comment]
> Vscode Browser <img alt="Screenshot 2022-06-28 at 2 24 47 PM" width="793" src="https://user-images.githubusercontent.com/92082070/176137912-2d99e016-27e2-471a-8ea0-36f6846cc087.png">

Hey @jayanthantw, you will have to modify the `GIT_EDITOR` env variable. This variable takes precedence over `EDITOR` for the `git` CLI as this is also explicitly exported within the workspace environments.
<img width="343" alt="Screenshot 2022-06-29 at 8 38 47 AM" src="https://user-images.githubusercontent.com/39482679/176339299-becb135e-988a-4f25-907c-fee0b497a2af.png">

For a global change, you can:
- Go to https://gitpod.io/variables
- Create a `New Variable` in the following manner:
![Screenshot 2022-06-29 at 08-40-36 Variables — Gitpod](https://user-images.githubusercontent.com/39482679/176339509-627b0ebb-3cc1-4ab2-94e6-2557dbec3b22.png)
Note that you can specify some other editor if you like.


------
@loujaybee do you think this is worth documenting under the IDE section 👀 ?
There has been a few questions regarding this in the past on our discord server.

**Comment by jayanthantw** [comment]
> as this is also explicitly exported within the workspace environments

Is there any way to configure `GIT_EDITOR` variable for via `gitpod.yml `
