### ISSUE TITLE
[ws-daemon] GC time is over 10 mins causes the ws-daemon received signal terminated

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#10954]
### Bug description

When the ws-daemon received the signal terminated, we notice that the GC time would is over 10 minutes.

We could check these dashboards for reference (Pod Name / Node Name)
- ws-daemon-mmgqv / workspace-ws-us47-pool-9465
  - [ws-daemon](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&var-cluster=us47&var-node=All&var-pod=ws-daemon-mmgqv&var-grpc_method=All&var-datasource=VictoriaMetrics&from=1656355800000&to=1656357300000)
  - [workspace node's normalized load average](https://grafana.gitpod.io/?orgId=1&var-datasource=VictoriaMetrics&var-cluster=us47&from=1656355800000&to=1656357300000&viewPanel=3)
- ws-daemon-jqcgx / workspace-ws-us47-pool-44gn
  - [ws-daemon](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&var-cluster=us47&var-node=All&var-pod=ws-daemon-jqcgx&var-grpc_method=All&var-datasource=VictoriaMetrics&from=1656340200000&to=1656343800000)
  - [workspace node's normalized load average](https://grafana.gitpod.io/?orgId=1&var-datasource=VictoriaMetrics&var-cluster=us47&from=1656340200000&to=1656343800000&viewPanel=3)
- ws-daemon-c5srf / workspace-ws-us47-pool-xbl7
  - [ws-daemon](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&var-cluster=us47&var-node=All&var-pod=ws-daemon-c5srf&var-grpc_method=All&var-datasource=VictoriaMetrics&from=1656336600000&to=1656340200000)
  - [workspace node's normalized load average](https://grafana.gitpod.io/?orgId=1&var-datasource=VictoriaMetrics&var-cluster=us47&from=1656336600000&to=1656340200000&viewPanel=3)
- ws-daemon-rzwdx / workspace-ws-us47-pool-2tqj
  - [ws-daemon](https://grafana.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&var-cluster=us47&var-node=All&var-pod=ws-daemon-rzwdx&var-grpc_method=All&var-datasource=VictoriaMetrics&from=1656349200000&to=1656352800000)
  - [workspace node's normalized load average](https://grafana.gitpod.io/?orgId=1&var-datasource=VictoriaMetrics&var-cluster=us47&from=1656349200000&to=1656352800000&viewPanel=3)

### Steps to reproduce

The issue happens in the production cluster randomly.

### Anything else?

Related issues
- #9893
- https://github.com/gitpod-io/gitpod/issues/10081#issuecomment-1129356529

**Comment by utam0k** [comment]
Good point @jenting, Is it confirmed that the long gc time is due to go routine leak? I am wondering if it is one of the suspected areas and maybe not the others. For example, I am wondering what the load is like during backups.

**Comment by jenting** [comment]
> Good point @jenting, Is it confirmed that the long gc time is due to go routine leak? I am wondering if it is one of the suspected areas and maybe not the others. For example, I am wondering what the load is like during backups.

Currently, the dashboard indicates the number of state transitions from `PREBUILD - STOPPING` _or_ `REGULAR - STOPPING` per cluster. If we want to check the per ws-daemon load during backups, we don't have such a dashboard for now.

I'll investigate whether the existing ws-daemon reports metrics are doable or not.

**Comment by andrew-farries** [comment]
> But, if the ws-daemon starts to perform the GC and the GC time is over 10 minutes, the ws-daemon readiness probe failed, therefore, the ws-daemon restart.

Why does the `ws-daemon` restart when it's readiness probe fails? Failing liveness probes should cause pod restarts, not failing readiness probes, right?

**Comment by jenting** [comment]
> > But, if the ws-daemon starts to perform the GC and the GC time is over 10 minutes, the ws-daemon readiness probe failed, therefore, the ws-daemon restart.
> 
> Why does the `ws-daemon` restart when it's readiness probe fails? Failing liveness probes should cause pod restarts, not failing readiness probes, right?

You are right! The readiness probe shouldn't cause the Pod to be restarted.
