### ISSUE TITLE
prebuild initializer failed when `git stash push` -u bacause of of permission denied

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#10953]
### Bug description

the error message is here.
```console
cannot initialize workspace: cannot initialize workspace: prebuild initializer: git stash push -f failed (exit status 1): Save working directory and index state WIP on develop: XXXXXXXX Merged in YYYYY warning: failed to remove AAA/BBB/CCC: Permission denied
```

the error message is made by this code
https://github.com/gitpod-io/gitpod/blob/2823606369b667188187b1e8ee9a75cbe968633b/components/content-service/pkg/initializer/prebuild.go#L117

[Internal link](https://gitpod.slack.com/archives/C03145ZD98D/p1655997194030959)

### Steps to reproduce

I don't know but this error happened on gen49

### Expected behavior

Works fine

**Comment by kylos101** [comment]
We just bumped into this issue on gen53 and gen54, too.

Scheduled the issue to groundwork.
