### ISSUE TITLE
Rustlang: IDE is not sufficient

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1096]
Currently (16012019) gitpod seems to be unable to provide sufficient IDE for rustlang.

For vscode this is integrated in https://marketplace.visualstudio.com/items?itemName=kalitaalexey.vscode-rust

**Comment by JesterOrNot** [comment]
@Kreyren I am making WIP documentation on how to setup a Rust Project
I'm still in the process of writing it but maybe it can help you https://deploy-preview-403--gitpod-website.netlify.com/docs/rust-in-gitpod/
if not maybe you can give some feedback thanks!

**Comment by jankeromnes** [comment]
> Currently (16012019) gitpod seems to be unable to provide sufficient IDE for rustlang.

What seems to be missing? Gitpod should have full IDE language support, and ship with the both latest stable and nightly Rust.

Please try to be specific about exactly what seems to be missing. Thanks!

**Comment by Kreyren** [comment]
>  if not maybe you can give some feedback thanks! @JesterOrNot 

1) The white theme hurts my eyes :disappointed: 
2) Adding `gitpod.yml` file with:
```
vscode:
  extensions:
    - belfz.search-crates-io@1.2.1:kSLnyrOhXtYPjQpKnMr4eQ==
    - serayuzgur.crates@0.4.7:HMkoguLcXp9M3ud7ac3eIw==
    - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==
    - Swellaby.vscode-rust-test-adapter@0.11.0:Xg+YeZZQiVpVUsIkH+uiiw==
```

And then restarting gitpod doesn't load the extensions (https://gitpod.io/#https://github.com/Kreyren/rustlang-fibonnaci/tree/f4800460c74155464ccd354397a9246b22c3ba4c) 

4) Seems to work when loaded manually, but `search crates` extension seems to output annoying emoji in the code that should be disabled

5) Add https://marketplace.visualstudio.com/items?itemName=bungcip.better-toml on the list for better highlighting of .toml files

---

> What seems to be missing? Gitpod should have full IDE language support, and ship with the both latest stable and nightly Rust. @jankeromnes 

On my end GitPod doesn't have the mensioned IDE for rustlang for linting

**Comment by JesterOrNot** [comment]
Thanks @Kreyren! A few things
1. Search crates.io is not the one with emojis `crates` is and I've added a emoji warning above it
2. I added `better TOML` to the extensions

Anything else?

**Comment by JesterOrNot** [comment]
See https://deploy-preview-403--gitpod-website.netlify.com/docs/rust-in-gitpod/

**Comment by Kreyren** [comment]
> Search crates.io is not the one with emojis crates is and I've added a emoji warning above it

You are right, my bad

> I added better TOML to the extensions

Perfect! Thanks <3

> Anything else?

Testing https://gitpod.io/#https://github.com/Kreyren/rustlang-fibonnaci/tree/master doesn't seem to deploy these by default.

Or do you expect end-user to configure those per repository?

**Comment by Kreyren** [comment]
i've been using gitpod for rustlang development and it seems that previous issues are no longer present -> closing as solved will reopen if they appear again
