### ISSUE TITLE
Move tabs for projects and teams down below the heading

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#10976]
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/issues/8385, we're updated the dashboard navigation to provide a better UX, color accessibility, breadcrumb structure, and more,  while surfacing a single one-click-away button to access all your workspaces without having to switch to your personal account every time.

This created a top level menu that filters everything below the top navigation to contain information only relevant to these options like Team, Workspaces, and Admin.

The top navigation could benefit from :a: maintaining a fixed height which could later on use a different background, :b: action buttons to request access to a team (https://github.com/gitpod-io/gitpod/issues/7007), and more. This could become useful if and when we decide to move the sidebar menu in **/admin** to use tabs instead.

| Team | Branches  | Admin |
|-|-|-|
| <img width="1440" alt="160603865-6ae2e842-dd5b-42b1-8944-a64c4a64e144" src="https://user-images.githubusercontent.com/120486/176183938-0f316f26-e4c9-40ba-8f31-dd2831c8029f.png"> | <img width="1440" alt="160603562-cde83773-8ffd-4f10-b7b3-4b694a8dd6bf" src="https://user-images.githubusercontent.com/120486/176183964-5a8edcae-ab73-4625-aa61-317584bf221a.png"> | <img width="1440" alt="160603576-b4a152d6-ea70-4f8c-b57f-4c011171cdd0 (1)" src="https://user-images.githubusercontent.com/120486/176184026-bb7b7f6e-3fd3-44ad-af0a-445a41c0348c.png"> |

### Proposal

Following the initial proposal from https://github.com/gitpod-io/gitpod/issues/8385, we could consider moving all tabs for projects and teams down below the heading.

**Comment by gtsiolis** [comment]
Cc @jldec as we recently discussed this change. 🏓

**Comment by Devansu-Yadav** [comment]
@gtsiolis I'm looking to make my first contribution to Gitpod and this issue seems like a good way to start. Can I take up this issue?

**Comment by gtsiolis** [comment]
Hey @Devansu-Yadav! Yes, any issue without an assignee should be free to pick up.

We're planning some larger updates in the navigation in the scope of https://github.com/gitpod-io/gitpod/issues/15665, but until then moving the tabs below the header should be a good MVC step as this is what we want to do long-term anyway.

I'd focus on moving all tabs below the header, everywhere except the admin dashboard for now. ❗

**Comment by Devansu-Yadav** [comment]
> Hey @Devansu-Yadav! Yes, any issue without an assignee should be free to pick up. Feel free to open a pull request and link back to this issue. 🏓
> 
> We're planning some larger updates in the navigation in the scope of #15665, but until then moving the tabs below the header should be a good MVC step as this is what we want to do long-term anyway.

Got it! 👍

> 
> I'd focus on moving all tabs below the header, everywhere except the admin dashboard for now. ❗

So, does this mean that I should be moving all the tabs for everything under projects and teams, right?

**Comment by gtsiolis** [comment]
@Devansu-Yadav Yes!

**Comment by Devansu-Yadav** [comment]
@gtsiolis Before moving on with the implementation, I wanted some validation on my approach for this issue. After going through the React code for the dashboard, I could identify how the tabs are being rendered on the projects and teams pages within the [`Menu`](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/Menu.tsx#L515) component. I think that we should decouple [this code](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/Menu.tsx#L514-L525) from the `Menu` component into a separate component (something like `secondLevelMenu`) which could then be individually used within each of the components for projects and teams pages. We need to do so because we want to render the tabs below the `Header` component (responsible for displaying the heading and sub-headings for a page), which is being rendered separately for each page.

I'm open to suggestions from your end! 😄

**Comment by gtsiolis** [comment]
Thanks for reaching out, @Devansu-Yadav!

> I think that we should decouple [this code](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/Menu.tsx#L514-L525) from the Menu component into a separate component ...

Haven't gone through the code specifics lately, but I also remember seeing these two elements mixed together. The approach you describe sounds good. Let me loop in @geropl in case someone from the `@gitpod-io/engineering-webapp` could provide a hint for the code changes.

In any case, @Devansu-Yadav, opening a pull request could be the fastest way to get feedback on the implementation you described above.

**Comment by Devansu-Yadav** [comment]
> Haven't gone through the code specifics lately, but I also remember seeing these two elements mixed together. The approach you describe sounds good. 

Thanks for the feedback, @gtsiolis!

> Let me loop in @geropl in case someone from the `@gitpod-io/engineering-webapp` could provide a hint for the code changes.

Sure, that would be quite helpful! 😄
> 
> In any case, @Devansu-Yadav, opening a pull request could be the fastest way to get feedback on the implementation you described above.

Sure, that makes sense. How about I implement this change for one of the pages (either projects or teams page) first and get feedback on whether I'm heading in the right direction?

**Comment by gtsiolis** [comment]
@Devansu-Yadav I'm coming back a bit late to your question, but the team has already started working on moving the tabs below the heading in https://github.com/gitpod-io/gitpod/pull/16164. Still moving the tabs for admins or other settings is something we could tackle later.

**Comment by Devansu-Yadav** [comment]
> @Devansu-Yadav I'm coming back a bit late to your question, but the team has already started working on moving the tabs below the heading in #16164. Cc @svenefftinge

Sure, seems like a lot of changes have been made for this issue 😅. Thanks for informing btw! 🙌

> Still moving the tabs for admins or other settings is something we could tackle later, see #7879.

Is there any way I could contribute to #7879 as of now or any issue related to the dashboard that you could suggest I could work on? 😄
