### ISSUE TITLE
bug: vscode-rust extension outputs errors

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1098]
After exporting https://marketplace.visualstudio.com/items?itemName=kalitaalexey.vscode-rust in gitpod through downloading from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/kalitaalexey/vsextensions/vscode-rust/0.4.2/vspackage and then drag and dropping in gitpod the following message appears:

![image](https://user-images.githubusercontent.com/11302521/72490988-f6d8df00-3818-11ea-9c64-c310348a730b.png)

And extension is not working

**Comment by jankeromnes** [comment]
Hi @Kreyren, thank you for reporting this problem, and sorry for the late response.

Please file any issues relative to VS Code extension support in Gitpod against the Theia repository: https://github.com/eclipse-theia/theia/issues

**Comment by Kreyren** [comment]
> and sorry for the late response.

Feel free to process this issue with low priority in favor of US cluster i can wait

> Please file any issues relative to VS Code extension support in Gitpod against the Theia repository:

will do

**Comment by akosyakov** [comment]
@jankeromnes are you sure that it is Theia bug? Errors are not coming from Theia, but from rust extension. Could be something with missing tools in the workpace image?

**Comment by Kreyren** [comment]
@akosyakov pebcak is a posibility and i am not sure how to diagnose it to determine what the issue is since the message provided doesn't make sence to me.
