### ISSUE TITLE
Differentiate usage of different workspace classes and types (prebuilds)

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#10985]
Users viewing a usage report should recognize where that usage happened. This means differentiating between usage for different [workspace classes](https://github.com/gitpod-io/gitpod/issues/8261) (which are metered at different rates), as well as separating usage of workspaces like prebuilds, from regular workspaces.

**Comment by easyCZ** [comment]
In https://github.com/gitpod-io/gitpod/pull/11043, we've added configuration to price different classes differently. The remaining work is to expose the WorkspaceType in the results. To do this, we'll need to join WorkspaceInstances with Workspaces.

We'll need to something like the following query to get the:
```
SELECT wsi.id, wsi.creationTime, wsi.startedTime, wsi.stoppedTime, wsi.usageAttributionId, ws.projectId, ws.type
    FROM d_b_workspace_instance AS wsi
    LEFT JOIN d_b_workspace AS ws
      ON wsi.workspaceId = ws.id
    LIMIT 100;
```

**Comment by easyCZ** [comment]
This is now complete.
