### ISSUE TITLE
Google-docs style editing on gitpod?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1099]
Proposing a method to add "Google-docs style" editing on GitPod meaning that people invited through generated unique link could gain access to the end-user's IDE (with restrictions on sensitive files with authentification, etc..) and depending on set permission on the mensioned link to make changes or propose changes for approval on said session:

![](https://media.giphy.com/media/cfLpKYLQqkJNK/giphy.gif)

**Comment by JesterOrNot** [comment]
@akosyakov Can you take a look at this?

**Comment by akosyakov** [comment]
Such features have to be discussed and planned first 😃 it is not 2 days of work

**Comment by Kreyren** [comment]
let's discuss and plan then :smiling_imp:

**Comment by JesterOrNot** [comment]
Sounds like fun can I help?

**Comment by JesterOrNot** [comment]
My bad
