### ISSUE TITLE
Show team billing in admin dashboard team view

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#10998]
For teams with billing, the team view should indicate which kind of billing has been configured.

**Billing**
`Usage-based` _or_ `Team Unleashed` _or_ `Team Professional`

**Comment by gtsiolis** [comment]
This seems to be partially implemented as :a: we're hard-coding the billing mode and :b: we only surface two options (chargebee and usage-based). Cc @jldec 

> BIllingMode
> usage-based

> BIllingMode
> chargebee

**Comment by jldec** [comment]
Closing now - covered by #14739
