### ISSUE TITLE
Order Git providers by frequency of usage for login and new project flow

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#10997]
The order of git providers in the Login and new project flows could be improved to make it more likely that users will find the provider which they intend to use at the top of the list.

#### /login
Here is the suggested order to use in the login page, if all 3 cloud providers have been configured on the Gitpod instance (E.g. on gitpod.io)

- GitHub
- GitLab
- Bitbucket

#### /new
When users have connected to multiple Git providers, the new project flow should default to showing repos from one provider in the same order the first time it is used e.g. if you have connected to both GitLab and GitHub, then GitHub repos should be suggested first. 

In line with the goal of showing the most likely intended provider first, once a user has created a project with one provider, subsequent /new projects should default to the same provider.

**Comment by gtsiolis** [comment]
Cross-posting a [relevant discussion](https://gitpod.slack.com/archives/C01KGM9DVRC/p1656495783183179?thread_ts=1656446483.400359&cid=C01KGM9DVRC) (internal) for more context on the current list order. Cc @sagor999 @atduarte @jldec

**Comment by jldec** [comment]
Icebox area = Dashboard
