### ISSUE TITLE
Align the terraform module with the Reference Architecture

### ISSUE THREAD

**Issue by nandajavarma** [gitpod-io/gitpod#11027]
Presently, we have[ terraform modules ](https://github.com/gitpod-io/gitpod/tree/main/install/infra/terraform)that we use for nightly tests. We should align these with the reference architectures to provide an officially supported `IaC` way to setup as per the reference.

Points to ensure:
- [ ] Tag terraform modules with release version to ensure incremental updates
- [ ] Ways to maintain the reference architecture and terraform modules in Sync, and easy way to get to one from the other
- [ ] Cleaner linting and validation for terraform modules tracked in #11029 
- [ ] Make the security groups less permissive https://github.com/gitpod-io/gitpod/issues/11065

**Comment by lucasvaltl** [comment]
Closing this in favour of https://github.com/gitpod-io/gitpod/issues/10620 - will create separate new issues for this.
