### ISSUE TITLE
Validate and lint terraform modules

### ISSUE THREAD

**Issue by nandajavarma** [gitpod-io/gitpod#11029]
Since the terraform modules would end up being used for production purposes, we have to make validate the terraform module and keep it formatted. We can essentially rum `terraform fmt -check -recursive ./.` and `terraform validate` on the modules. This fix will be similar to [what is done in the ops repo](https://github.com/gitpod-io/ops/blob/0cec049b688d1a04cd73f030662f826e8b26d99f/.github/workflows/terraform-on-push.yml).

**Comment by MrSimonEmms** [comment]
It's also worth adding a CI/CD job that fails if there's an invalid format (the `-check` command is your friend here) and if the `terraform validate` fails as well
