### ISSUE TITLE
My workspaces won't open

### ISSUE THREAD

**Issue by Krobert18** [gitpod-io/gitpod#1102]
Whenever I try to open my workspaces (I have two), it doesn't open and it gives me this message "Evicted: Pod The node had condition: [DiskPressure].
Please file an issue if you think this is a bug."

I'm not sure why this is happening. I haven't used either for about 4 days, and the last time I used it, it was working just fine. After I pressed the start button to open up the workspace it prompted me with the [DiskPressure] error.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by jankeromnes** [comment]
Hi @Krobert18, many thanks for your bug report, and sorry that this happened to you.

This is a new bug that recently started affecting user workspaces, and it's currently tracked in #1080 so I'll close this issue for now.

In short, this is an automatic response from Kubernetes when it thinks that a server disk is getting full, so it tries to resolve this by "evicting" (i.e. force-stopping) user workspaces. That's not at all the correct response, so we'll try to reconfigure this behavior.

While we're working on a fix, if this happens to you, please simply wait a few minutes and try again. (Sorry for the silly workaround, we'll try to fix this for good as soon as possible.)
