### ISSUE TITLE
Remove the latest editor release warning alert on workspace time out

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11035]
### Bug description

Back in https://github.com/gitpod-io/gitpod/pull/8783, we introduced a warning alert to notify users when they've opted in for using the latest editor release for workspaces.

This is also shown on the workspace pages like `Timed Out`, `Stopping`, `Stopped`  which can be inaccurate as the user may have changed the setting in the meantime.

Instead, relying on showing this warning during workspace (re)start could be better.

**When the latest warning should be shown**
- It's before or (re)starting the workspace -> ref to phases https://github.com/gitpod-io/gitpod/blob/9d2d729b378acfc895f4700922b553655e206d86/components/dashboard/src/start/StartPage.tsx#L26-L50
- Workspaces start/stopped failed for some unexpected reasons (i.e. with exit code from supervisor) -> when it shows error https://github.com/gitpod-io/gitpod/blob/9d2d729b378acfc895f4700922b553655e206d86/components/dashboard/src/start/StartPage.tsx#L116

### Steps to reproduce

1. Go to **[/preferences](https://gitpod.io/preferences)** and opt in for the _Latest Release (Unstable)_ option.
2. Open a new workspace and let it time out (~30 min)
3. Notice the on the _Timed Out_ page we're still showing the latest editor release warning alert.

<img width="1440" alt="Screenshot 2022-06-30 at 1 34 34 PM" src="https://user-images.githubusercontent.com/120486/176658016-2d0d1e1a-cddd-49f5-ae8c-ec305105b7ea.png">

**Comment by gtsiolis** [comment]
Still relevant, marking as ~never-stale.

**Comment by Devansu-Yadav** [comment]
@gtsiolis As there was no assignee for this issue, I thought of resolving it by raising #16551, as it was a trivial change and is still valid (I was able to reproduce this issue).
