### ISSUE TITLE
Can't access workspaces

### ISSUE THREAD

**Issue by BobHerold** [gitpod-io/gitpod#1104]
**Describe the bug**
I"m unable to open by Gitpod workspaces; it tells me remaining time is 0;0, then says upgrade subscription; when i go to account profile; it shows I have "unlimited team" via Code Institute. whats going on here gitpod?

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by BobHerold** [comment]
The "Start" buttons on the Work-spaces are "grayed out".

**Comment by jankeromnes** [comment]
Hi @BobHerold! Thanks for letting us know, that doesn't sound right. We're looking into it.

**Comment by geropl** [comment]
Hi @BobHerold ,

we recently fixed a bug regarding invitations links for Team Subscriptions. I now spotted and fixed bad data generated by that bug.

Could you please try again and report if it now works for you?

**Comment by BobHerold** [comment]
Hello Gero, 
 it is still giving me the same screen with "grayed out" start buttons, at top left it says "remaining usage time 0:00", etc. However in Account settings under subscription, etc. it shows I have unlimited time due to "team subscription". Account control has all boxes check-marked.




Thank you for any assistance you can give me here.

Bob Herold.




    On Friday, January 17, 2020, 04:57:14 AM EST, Gero Posmyk-Leinemann <notifications@github.com> wrote:  
 
 
Hi @BobHerold ,

we recently fixed a bug regarding invitations links for Team Subscriptions. I now spotted and fixed bad data generated by that bug.

Could you please try again and report if it now works for you?

**Comment by BobHerold** [comment]
Its still not letting me in;     
![screencapture-gitpod-io-workspaces-2020-01-17-09_32_36](https://user-images.githubusercontent.com/54417085/72620290-02a5cd80-390d-11ea-91c3-7f41f712d152.png)

**Comment by BobHerold** [comment]
Have cleared  cache many times in chrome browser, etc.   It gives the same result in an "incognito window".

**Comment by geropl** [comment]
Hi @BobHerold ,
what does `https://gitpod.io/usage/` show you?

**Comment by BobHerold** [comment]
Current Subscription      Remaining hours:  unlimited

**Comment by BobHerold** [comment]
![screencapture-gitpod-io-usage-2020-01-17-10_02_37](https://user-images.githubusercontent.com/54417085/72622292-ec017580-3910-11ea-8da7-9f40775ff495.png)

**Comment by BobHerold** [comment]
On Friday, January 17, 2020, 10:00:21 AM EST, Gero Posmyk-Leinemann <notifications@github.com> wrote:  
 
 
Hi @BobHerold ,
what does https://gitpod.io/usage/ show you?

**Comment by BobHerold** [comment]
see the above screen shot

**Comment by geropl** [comment]
I'm very sorry this takes so long but we still struggle to find an explanation for your case. I tried to replicate your state and run it as test but that behaves exactly as expected..
I tried something else after having noticed that you are using the US cluster. Could you try again?

**Comment by BobHerold** [comment]
At 5:55 PM EST, US,   I was able to get "blue Start" buttons and was able to access my work spaces and they did load up.
I'll try again sometime tomorrow to verify its all  up and working again.
Thank you, 
Bob Herold.  Code Institute student.


    On Saturday, January 18, 2020, 03:05:41 PM EST, Gero Posmyk-Leinemann <notifications@github.com> wrote:  
 
 
I'm very sorry this takes so long but we still struggle to find an explanation for your case. I tried to replicate your state and run it as test but that behaves exactly as expected..
I tried something else after having noticed that you are using the US cluster. Could you try again?

**Comment by geropl** [comment]
Thank you for posting back, that looks good (please re-open if it doesn't). I will further pin this down and deploy a fix for everyone else (who _might_ me affected).
