### ISSUE TITLE
`error reading from server: EOF` on docker compose build

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#11045]
### Bug description

Recently I keep getting problems with Docker system inside Gitpod. For instance, when I need to do docker compose build, from time to time it crashes build mid-way saying:

`failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF`

### Steps to reproduce

`docker compose build`

### Workspace affected

https://appwrite-appwrite-khhi0xp6xdv.ws-eu47.gitpod.io/

### Expected behavior

No error

### Example repository

https://github.com/appwrite/appwrite

### Anything else?

[Discord thread](https://discord.com/channels/816244985187008514/990944600288022558/990944602943000628)

**Comment by atduarte** [comment]
Same behaviour reported in Discord [here](https://discord.com/channels/816244985187008514/990944600288022558/990944602943000628).

**Comment by svenefftinge** [comment]
not sure if related https://github.com/gitpod-io/gitpod/issues/11729#issuecomment-1205187435
