### ISSUE TITLE
In-workspace class upgrade

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#11042]
## Is your feature request related to a problem? Please describe
When my workspace performance is insufficient for my current workloads I would like to be able to upgrade the workspace class easily.

## Describe the behaviour you'd like
From inside the workspace, using `gp` cli or a menu option I would like to upgrade the workspace to a class of my choosing. Behind the scenes, the workspace would stop, and start with the new workspace class.

Furthermore, it would be good to automatically suggest this action to the user when heavy-usage is degrading the experience.

## Describe alternatives you've considered
- User stopping the workspace, changing the settings and starting again.
- User stopping the workspace, and starting again where we always ask what workspace class they want to use.

## Additional context
Depends on #8261

**Comment by perlun** [comment]
@atduarte @sagor999 Was this ever implemented? :thinking: Asking since I created a GitLab GDK instance now with the "small" class but it's perhaps a bit too small for my needs so I want to be able to upscale it, preferably without removing the machine contents... Any way to do it?

**Comment by axonasif** [comment]
Hi @perlun, no updates on this yet.
