### ISSUE TITLE
[installer] fusefs and I/O limits cannot work together

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11057]
### Bug description

`fusefs` does not support I/O limiting. If both attributes are configured, the installer should cancel the process.

### Steps to reproduce

-

**Comment by lucasvaltl** [comment]
Hey @aledbf what is the impact of this bug? Does this impact only SaaS or Self-Hosted as well? Further - is this something you need team self-hosted's help for?

**Comment by aledbf** [comment]
> Does this impact only SaaS or Self-Hosted as well?

Only self-hosted. Anyone using fusefs and the intention to set i/o limits will see no effect.

**Comment by mrsimonemms** [comment]
Is there any work needed on this in view of the planning changes and, ultimately, dropping support for fuse?
