### ISSUE TITLE
pre-existing dotfiles and conflict resolution where Gitpod provides a ~/.gitconfig

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#11062]
# overview

Gitpod by default generates a `~/.gitconfig` file which is in conflict with the Gitpod feature of "bring your own dotfiles"

<img width="1075" alt="Screen Shot 2022-07-01 at 1 34 50 pm" src="https://user-images.githubusercontent.com/127353/176818410-92118a23-3392-4100-a312-779021010bd0.png">

# problem

- file exists during bootstrap so `stow` (https://venthur.de/2021-12-19-managing-dotfiles-with-stow.html) fails by default.

- no documentation for gp credential-helper that explains the why/what/that it is configured.

```
[credential]
        helper = /usr/bin/gp credential-helper
```

- are these defaults needed?

```
[push]
        default = simple
[alias]
        lg = log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
[credential]
        helper = /usr/bin/gp credential-helper
[user]
        name = Geoffrey Huntley
        email = ghuntley@ghuntley.com
```

- can we not run `git config credential.helper = /usr/bin/gp credential-helper` instead of shipping a `.gitconfig` thus removing default failure modes for standard tools like stow?

**Comment by axonasif** [comment]
Related: https://github.com/gitpod-io/gitpod/issues/7603#issuecomment-1014612321

**Comment by gtsiolis** [comment]
Removed the **~feedback-issue** label and the title prefix to avoid any confusion as feedback issues are used to gather feedback, suggestions, and experiences from users while iterating on a specific product feature.

Cross-posting also the recently updated issue template description in https://github.com/gitpod-io/gitpod/pull/11244.
