### ISSUE TITLE
Why didn't dotfiles initiatize? Where can I find these logs.

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#11063]
# problem

Over in the dashboard my dotfiles have been configured

<img width="940" alt="Screen Shot 2022-07-01 at 1 48 21 pm" src="https://user-images.githubusercontent.com/127353/176819686-f5629756-5032-4f00-82ad-9b4f1599468c.png">

My dotfiles can be found at https://github.com/ghuntley/dotfiles

I have started a workspace but the dotfiles were not present when starting a new workspace via https://www.gitpod.new/

# background story

The reason why the dotfiles did not install is

- `stow` has not been published yet ([internal link discussion](https://gitpod.slack.com/archives/C0201TXMV54/p1656644479899229?thread_ts=1655945935.029709&cid=C0201TXMV54))
- `Makefile` support has not shipped (https://github.com/gitpod-io/gitpod/pull/10811)

If I didn't have this knowledge then would have been stumped.

# feature request

As a non-Gitpodder;  I'd like to troubleshoot this but have no idea where to get information?

**Comment by axonasif** [comment]
The user will need to be aware of https://www.gitpod.io/docs/config-dotfiles, otherwise one can feel pretty lost.

**Comment by loujaybee** [comment]
`~/.dotfiles.log` is the file, however with `gp` being the main "API" in a gitpod workspace exposing these logs there would make sense. Will also link/relate to: 

- https://github.com/gitpod-io/gitpod/issues/7671

**Comment by gtsiolis** [comment]
Removed the **~feedback-issue** label and the title prefix to avoid any confusion as feedback issues are used to gather feedback, suggestions, and experiences from users while iterating on a specific product feature.

Cross-posting also the recently updated issue template description in https://github.com/gitpod-io/gitpod/pull/11244.
