### ISSUE TITLE
[code insiders] Extension walkthroughs don't remember state

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#11076]
### Bug description

Whenever I open a new workspace, I am spammed with 7 editor pages in 6 different windows, all contributed by extensions. Most of them are extension walkthroughs from all the various 70+ extensions I have.

On VS Code Browser stable (1.68) this is not happening, I'm using 1.69.0-insider@https://github.com/gitpod-io/openvscode-server/commit/1899e4ae0065bfa7bc004ed6dfd12164f7dfa311.

![image](https://user-images.githubusercontent.com/29888641/176876277-db82232c-adcf-4a17-a332-b052a6777f30.png)

### Steps to reproduce

Open any new workspace and wait for extensions to sync and finish installing.

### Workspace affected

all of 'em

### Expected behavior

These extension walkthroughs to only appear once: when I install the extension and then disappear forever when I hit `Mark Done`. I believe the state here should be synced by Settings Sync, but not sure.

### Example repository

https://gitpod.new

**Comment by filiptronicek** [comment]
Appears as it does not happen for https://insiders.vscode.dev or https://github.dev.

**Comment by jeanp413** [comment]
@andreafalzetti could you take a look at this today and investigate

**Comment by jeanp413** [comment]
Fixed in https://github.com/microsoft/vscode/pull/154313 and cherry picked to 1.69 release branch

**Comment by filiptronicek** [comment]
Thanks a lot, @jeanp413 🙏
