### ISSUE TITLE
Open project in subdirectory and have tasks execute

### ISSUE THREAD

**Issue by titusfortner** [gitpod-io/gitpod#1108]
I'm not sure if this is a bug (related to #255?) or a new feature request. I have a monorepo with a number of different subdirectories. I'd like to be able to open them and have tasks in the `/subdirectory/.gitpod.yml` execute within that directory. Is there a way to do this now?

Thanks!

**Comment by svenefftinge** [comment]
You can only have one `.gitpod.yml` at the root fo the repository. But that can of course start multiple terminals and you can run something like `cd subdirctory && ./mycommand` as a task.
Would that solve your issue?

**Comment by titusfortner** [comment]
Is there a way to automatically set the directory list to open to the subdirectory?

**Comment by RyanQuey** [comment]
@svenefftinge We have a similar use case where we have one repo with multiple microservices, and each microservice would need its own dockerfile. Each microservice lives in its own subdirectory. Is it possible to run different dockerfiles depending on what subdirectory the developer is currently working in?

**Comment by PirateBread** [comment]
It would certainly be a nice feature if GitPod treated the path as the container for the workspace, and did not traverse up the tree but I also quite like the 1 repo 1 workspace convention.

**Comment by jpoehnelt** [comment]
I also have a similar use case with many samples in a repository that I would like to target individually.
