### ISSUE TITLE
upgrade gitpod/workspace-full to Java 17

### ISSUE THREAD

**Issue by rajivraghu** [gitpod-io/gitpod#11088]
### Bug description

Hello,
As of Jun, 8, 2022, Java 17 is now required for running vscode-java.
https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements

Unless this happens, everytime, we will need to make custom build gitpod workspaces which takes a bit of time . 

### Steps to reproduce

Refer above

**Comment by aledbf** [comment]
Closing. Please check https://github.com/gitpod-io/workspace-images/pull/845

**Comment by rajivraghu** [comment]
@aledbf ,
Is it Done? 
I tired opening empty workspace... Default is still JDK 11 

https://gitpod.io/#https://github.com/gitpod-io/empty

Not sure wot i am missing in closing this ??

**Comment by aledbf** [comment]
@rajivraghu I am sorry to not be clear. The default version will not be updated, at least in the near future.
Please check this comment https://github.com/gitpod-io/workspace-images/pull/845#issuecomment-1138212164

If you want to use Java 17, you can use [gitpod/workspace-java-17](https://hub.docker.com/r/gitpod/workspace-java-17)
