### ISSUE TITLE
Workspace stuck in Preparing

### ISSUE THREAD

**Issue by rebeccoder** [gitpod-io/gitpod#11097]
### Bug description

Workspace wont loads but the others will, just gets stuck on the preparing screen

### Steps to reproduce

I'm not sure what to try, its definitely not my internet

### Workspace affected

https://gitpod.io/start/#rebeccoder-milestonepro-89jg61du5se

**Comment by jimmybrancaccio** [comment]
Customer (`cnv_jisdoqy`) experienced this issue today.

**Comment by jimmybrancaccio** [comment]
Customer (`cnv_jiw5gju`) experienced this today.

**Comment by geropl** [comment]
Cannot reproduce as well. 😕
