### ISSUE TITLE
Unable to configure dotfiles

### ISSUE THREAD

**Issue by jkleve** [gitpod-io/gitpod#11090]
### Bug description

I have my dotfiles configured in `/preferences` but they don't get applied to my pods. I have an error in `.dotfiles.log` that no one else on my team gets.

```text
# dotfile init failed: rpc error: code = NotFound desc = no token available
```

### Steps to reproduce

I don't think this will be reproducible but you can try and set my dotfiles repo `https://github.com/jkleve/gitpod-dotfiles.git`.

**Comment by jldec** [comment]
Sorry - can't reproduce this.
I suspect that this is not a dotfiles issue issue at all, but rather a problem with your GitHub integration.
Please check your integrations settings, and make sure that you are able to open workspaces and push to GitHub.
Thanks

**Comment by jkleve** [comment]
I see. It wasn't clear to me from the gitpod documentation that you need to have write permissions on your repo or need to have the integration set up.

My solution was switching to gitlab where I do have the integration defined. Now it works.
