### ISSUE TITLE
Multiple long (~<32K) env vars can prevent workspace start

### ISSUE THREAD

**Issue by eliezedeck** [gitpod-io/gitpod#11105]
### Bug description

When creating a workspace that has some environment variables, sometimes I get the error:

```
QueryFailedError: ER_DATA_TOO_LONG: Data too long for column 'value' at row 1
```

UNLEASHED user here.

### Steps to reproduce

Create an environment with some long ENV variable. If it is more that 32K chars, the `gp env` command will refuse it.

However, reduce the length of the chars something less than 32K, but still long enough, now `gp env ...` will accept the variable because it's lower than 32K. But the next time you create a brand new workspace, it may have the error above.

### Expected behavior

It should not get stuck with that error.

The fact that `gp env` has accepted the env variable should mean that it's good. And it is because it only affects creation of new workspaces. Starting an existing workspace with the same long env variable doesn't have any problem.

### Anything else?

I'd like to suggest a **different method** for data restoration that is not limited to 32K in length. That should very well be possible.

While that can be done by any programmer, having it integrated and **secured by Gitpod** is something better.

**Comment by axonasif** [comment]
Relates to: https://github.com/gitpod-io/gitpod/issues/9284
