### ISSUE TITLE
Telemetry for `local-preview`

### ISSUE THREAD

**Issue by Pothulapati** [gitpod-io/gitpod#11113]
## Is your feature request related to a problem? Please describe

Currently, With #10766 done, We get the platform information in the `gitpod-telemetry` job. But for `local-preview`, This is not
really useful as the job only runs once per day during the midnight, and the fact that `local-preview` installs are short-lived.

## Describe the behaviour you'd like

Run the job right after the Gitpod pods are ready (as the telemetry job works only then), and also
run once more once a exit signal is received by the container. This way we not only have telemetry
that a `local-preview` installation is done, but also some numbers around the activity.

## Additional context

https://gitpod.slack.com/archives/C01KLC56NP7/p1656677767244989

**Comment by Pothulapati** [comment]
Reoping as we also plan to run the telemetry job once again before the exit.

**Comment by lucasvaltl** [comment]
@Pothulapati can this be closed?

**Comment by Pothulapati** [comment]
Yep!
