### ISSUE TITLE
[db-sync] Db-sync should scale up again in case of a failed deployment

### ISSUE THREAD

**Issue by andrew-farries** [gitpod-io/gitpod#11121]
If a deployment fails `db-sync` is left in a scaled down state (0 replicas).

`db-sync` should scale up again if deployment fails.

See this [Incident Retrospective (internal)](https://www.notion.so/gitpod/internal-Webapp-deployment-failed-to-run-database-migration-c02d681f19534a15ae0dcaf0fd8356a2?v=2df2f472ffa44823afc70af13cad26d5).

**Comment by geropl** [comment]
I'm in favor of closing this for now, until we got rid of it entirely.
