### ISSUE TITLE
gp top breaks sometimes with too many requests to workspace info and never recover

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#11139]
### Bug description

`watch gp top` fails at some point and does not rework in the workspace under load. I also had https://github.com/akosyakov/gitpod-monitor installed at the same time which make use of workspace info endpoint as well.

See [internal thread](https://gitpod.slack.com/archives/C01KGM9AW4W/p1657011133538689?thread_ts=1657009367.430579&cid=C01KGM9AW4W).

```
gitpod /workspace/factorial-gitpod (master) $ gp top
2022/07/05 08:47:42 cannot get workspace resources: rpc error: code = Unknown desc = could not retrieve workspace info: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
```

<img width="1237" alt="Screenshot 2022-07-05 at 10 51 41" src="https://user-images.githubusercontent.com/3082655/177290755-997c5944-b590-4644-b2b0-b0a9ce9dc01b.png">

### Expectation

Running something like `watch gp top` should not fail even under load, since it is an only a way for a user to see perf problems. cc @Furisto 

### Steps to reproduce

See above.

**Comment by akosyakov** [comment]
I think it happened because I also have https://github.com/akosyakov/gitpod-monitor which does requests each 2 second from each window. I think we need then caching and debouncing in supervisor, that a result is served from a cache within 1sec for instance.

**Comment by kylos101** [comment]
Scheduled. @Furisto is on-call this week, so the earliest he'd get to peek is next week. @utam0k if you get spare bandwidth this week, perhaps you can look? Probably easiest to recreate if you run `watch -n 1 gp top`.

**Comment by utam0k** [comment]
This problem could not be reproduced. Is it still occurring in production?

**Comment by akosyakov** [comment]
closing as duplicate of https://github.com/gitpod-io/gitpod/issues/12083
