### ISSUE TITLE
Give new workspaces more resources

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#11144]
## Is your feature request related to a problem? Please describe
The experience of opening a new workspaces can be painful because setup tasks are running. Users have to wait until they can start working because not enough resources  are available  to fulfill all requests.

## Describe the behaviour you'd like
Give new workspaces a higher priority (maybe use the already existing Qos attribute) during resource distribution.

**Comment by atduarte** [comment]
What alternatives were considered and discussed? Would ensure that the IDE has enough resources during that time be sufficient?

**Comment by aledbf** [comment]
I think this would be unfair to the other workspaces running in the node. I could even abuse that running tasks knowing that I have more CPU

**Comment by kylos101** [comment]
:wave: @Furisto thank you for creating this issue. @aledbf and I tested this recently with gen47 and gen51, and observed the same trend. It's an existing/old problem, I think, generally encountered when workspaces (usually monorepos) try to run too much.

We should talk more before scheduling this issue, I am going to move back to our inbox for now. 

For example, there may be other ways to solve this problem. Perhaps we could do a combination of things:
* introduce larger workspace classes
* increase the lower limits of the existing XL workspace class
* show users a "gauge" for their various resources and rely on them to tune their respective workloads
* proactively notify users when they're using excessive resources, to either tune their repo or use a larger workspace class (I think @atduarte recently created an issue for this idea)

**Comment by atduarte** [comment]
In an effort to keep the Inbox tidy and with only actionable work, I will close this in favour of #10861 as the desired outcome is similar. Feel free to reopen if you disagree.
