### ISSUE TITLE
Not connected message error

### ISSUE THREAD

**Issue by cruizfun** [gitpod-io/gitpod#1115]
I cannot start my workspace as I get this error: "Request startWorkspace failed with message: Not connected to message bus
Please file an issue if you think this is a bug."

**Comment by RDIL** [comment]
@jankeromnes @JesterOrNot help pleaseeee

**Comment by JesterOrNot** [comment]
@cruizfun can you send a screenshot of the issue and the logs in the dev-tools console?

**Comment by JesterOrNot** [comment]
nvm will work on other copy of issue

**Comment by jankeromnes** [comment]
Thank you for reporting this. Duplicate of #1110 and should work again.
