### ISSUE TITLE
"Error: not connected to message bus"

### ISSUE THREAD

**Issue by GeneralPoxter** [gitpod-io/gitpod#1116]
**Describe the bug**
Gitpod workspace not opening due to titular error.

**To Reproduce**
Attempt to open a workspace.

**Expected behavior**
Workspace should open.

**Additional Information**
I have a lot of unpushed work in the workspace.

**Comment by jankeromnes** [comment]
Thank you for reporting this. Duplicate of #1110 and should work again.
