### ISSUE TITLE
"Continue with default configuration" seems to be broken

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#11179]
![image](https://user-images.githubusercontent.com/32448529/177560940-a4a1e6fd-d3d3-4181-ae24-615a82eed27a.png)

On every click web console prints: "Error: Invalid gitpod.yml: should NOT have additional properties"

**Comment by andreafalzetti** [comment]
Just experienced this. In my case, my `.gitpod.yml` was entirely commented out. The error in this case is: `Invalid gitpod.yml: should be object`

At every click to "Continue with default configuration", the request to `server` seems to include the right props:

```json
{
  "jsonrpc": "2.0",
  "id": 8,
  "method": "createWorkspace",
  "params": {
    "contextUrl": "https://github.com/andreafalzetti/gitpod-experiments-d",
    "mode": "default",
    "forceDefaultConfig": true
  }
}
```

However, `forceDefaultConfig` seems to be ignored by `server` 🤔 

I had a quick look but I couldn't find anything obvious.
