### ISSUE TITLE
Unable to create workspaces for GitLab repos in suborganizations

### ISSUE THREAD

**Issue by techpeace** [gitpod-io/gitpod#1118]
**Describe the bug**

Attempting to create a GitLab repository under a suborganization parses the repo URL incorrectly.

**To Reproduce**

1. Head to https://gitpod.io/#https://gitlab.com/voxable/studio/design/docs

**Expected behavior**

A workspace should be created for https://gitlab.com/voxable/studio/design/docs

Instead, it attempts to create a workspace for https://gitlab.com/voxable/studio

**Additional Information**

**Comment by bazan101** [comment]
Hello is this bug readey to be fixed .
It's definilty keeping me from using GitPod at all as gitlab is my only corporate GIt repository hosting servicE.

**Comment by corneliusludmann** [comment]
Thanks for reporting this issue. It is fixed and will be deployed soon. We will close this issue once it is deployed. Thanks for your patience.

**Comment by svenefftinge** [comment]
deployed
