### ISSUE TITLE
Unable to Start a Workspace Using GitHub or GitLab Wiki Repository

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#11188]
### Bug description

I am unable to open a new workspace using either a wiki from GitHub or GitLab. I tested with:

- https://github.com/jimmybrancaccio/gitpod-test.wiki
- https://gitlab.com/astuffedtiger/gitpod-test.wiki

Both return that 'the repository was not found'.

<img width="650" alt="Screen Shot 2022-07-06 at 20 22 55PM" src="https://user-images.githubusercontent.com/405585/177669999-c8ae1891-b6ee-4c40-9a51-7053f1182891.png">

I am able to run `git clone https://github.com/jimmybrancaccio/gitpod-test.wiki.git` locally though.

```
git clone https://gitlab.com/astuffedtiger/gitpod-test.wiki.git

Cloning into 'gitpod-test.wiki'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.
```

### Steps to reproduce

1. Setup a wiki within a repository in either GitHub or GitLab. I just made a really basic one [page one in GitHub](https://github.com/jimmybrancaccio/gitpod-test/wiki).
2. If you have a look at the sidebar on your wiki page, you should see 'Clone this wiki locally' and a URL is provided.
3. You should be able to take this URL and attempt to start up a workspace with it, for example - `https://gitpod.io/#https://github.com/jimmybrancaccio/gitpod-test.wiki`.
4. Observe the error that the repository cannot be found.

### Expected behavior

Given that this is just a plain ole' Git repository I see no reason why we wouldn't allow a workspace to be created using a wiki repository from GitHub or GitLab. I expect that it should work just like other Git repositories.

### Anything else?

This stemmed from a [question in Discord](https://discord.com/channels/816244985187008514/816246578594840586/993813258832199720).

**Comment by amplifications** [comment]
+1

I am trying a find a solution for this problem too

**Comment by 201flaviosilva** [comment]
Me too, that feature would help a lot :)

**Comment by geropl** [comment]
So far we never supported opening Wikis in the first place so this is a feature request.

And while I understand the motivation and benefit, I don't think it makes sense to keep this issues around, because it's not in our current focus and we have to prioritize what we work on. 🧘
