### ISSUE TITLE
[content-service] cannot restart stopped workspace

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#11183]
### Bug description

The full error on start is:

```
cannot initialize workspace: cannot restore backup: tar /dst: tar /dst: exit status 2;tar: .docker-root/overlay2/dedcf720e850fe485571223ecd9959f159eb8eef5250e7ee42ac96f010a3e369/diff/root/.npm/_cacache/content-v2/sha512/2c/49/1e6cfe1a91b8ccb4030ecac14cfe4d1d4e557aaf369a254fd344a9a7e864c7f4cab9edb19e21e7313357cb8eaacc48e19d7fc2b1d2ed294af55846548846: Cannot open: Permission denied tar: .docker-root/overlay2/dedcf720e850fe485571223ecd9959f159eb8eef5250e7ee42ac96f010a3e369/diff/root/.npm/_cacache/content-v2/sha512/74/de/010104b1dac999964663a5780e77912dd860c4bf1089dabe1f9b8175af2aaed3b5e5cba0f24fe31bfc38f19bcc40ffd609a6d2ab6ea02561055f96ba53a6: Cannot open: Permission denied tar: Exiting with failure status due to previous errors
```
Logs:
https://cloudlogging.app.goo.gl/82CpwrNzW9oJWX1Q8

Log entry for the error:
https://console.cloud.google.com/logs/query;cursorTimestamp=2022-07-06T11:31:39Z;query=resource.labels.cluster_name%20:%20%2528%22eu51%22%2529%0A%22eb595f2b-7de4-4248-800d-7dfe0280f802%22%0Atimestamp%3D%222022-07-06T11:31:39Z%22%0AinsertId%3D%227hkbcwop4k5qd0t4%22;summaryFields=:false:32:beginning:false;timeRange=P1D?project=workspace-clusters

Trend over last 7 days:
https://cloudlogging.app.goo.gl/qdGdJ7CrD1zmLyrQ8

![image](https://user-images.githubusercontent.com/1272076/177650734-a91fd61c-126f-4e85-8beb-e0654599cccc.png)

### Steps to reproduce

1. Open this repository on Gitpod: https://gitlab.com/6uliver/gitpod-workspace-restart-error-repro
2. Wait for the workspace and Supertokens to be started, you should see this message in the console: "Started SuperTokens on 0.0.0.0:3567"
3. Stop the workspace and wait for it to be stopped
4. Open and start workspace

### Expected result

The workspace can be started successfully and Supertokens is running.

### Actual result

You can see a Gitpod error page with the text "Oh, no! Something went wrong!" and the following long error message:
```
initializeWorkspaceContent failed: cannot initialize workspace: cannot restore backup: tar /dst: tar /dst: exit status 2;
tar: .docker-root/overlay2/a061703a1735ce483b1f0d56341fe6943e2adf755b31b20a3f8ed82ee8f38e9e/diff/usr/lib/supertokens/jre/legal/java.base/ADDITIONAL_LICENSE_INFO: Cannot open: Permission denied 
tar: .docker-root/overlay2/a061703a1735ce483b1f0d56341fe6943e2adf755b31b20a3f8ed82ee8f38e9e/diff/usr/lib/supertokens/jre/legal/java.base/ASSEMBLY_EXCEPTION: Cannot open: Permission denied 
...
```

### Workspace affected

https://prlct-shipapp-5830i5ovwcb.ws-eu51.gitpod.io/

### Expected behavior

The ability to restart a stopped workspace

### Anything else?

How to test? [From here](https://github.com/gitpod-io/gitpod/pull/9589/files#diff-3861b50290797e328e85ef20028f0aee5d7d6a39d16eabd1de1e7f11ba0baf45L111).

#### How to test

1. Run these tests :point_down: 
- Open a workspace. In the terminal execute:
```
touch basic
sudo touch root-file
touch executable-file
chmod +x executable-file
touch suid-file
chmod 2555 suid-file
mkdir suid-directory
chmod g+s suid-directory
```
- Check the output of `ls -lat`, should be similar to
```
drwxr-x--- 8 gitpod gitpod 4096 Apr 28 17:31 .
-r-xr-sr-x 1 gitpod gitpod    0 Apr 28 17:31 suid-file
drwxr-sr-x 2 gitpod gitpod    6 Apr 28 17:31 suid-directory
-rwxr-xr-x 1 gitpod gitpod    0 Apr 28 17:30 executable-file
-rw-r--r-- 1 root   root      0 Apr 28 17:30 root-file
-rw-r--r-- 1 gitpod gitpod    0 Apr 28 17:30 basic
```
- Stop and open the workspace
- Open a terminal and run `ls -lat`
- Compare the outputs

2. Assert the [steps to recreate here](https://github.com/gitpod-io/gitpod/issues/3174) do not fail

3. Follow the steps to recreate in this issue, but, before stopping your workspace, stop the `supertokens` container, and then stop your workspace. Restart your workspace, it should avoid this error.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3oi2y)

**Comment by kylos101** [comment]
@utam0k is this something you could look at next, once you are free? :pray: It appears to be impacting many users.

**Comment by utam0k** [comment]
I couldn't reproduce it with `watch -n1 gp top` on gen52 😭 Maybe it is related the load of the node.

**Comment by utam0k** [comment]
There really seem to be a few more users with the same error.
https://cloudlogging.app.goo.gl/owK8qukCGMcpkKQk7
![image](https://user-images.githubusercontent.com/13010913/177942565-9aaf6030-c31a-492d-929f-c4923c4f5799.png)

**Comment by utam0k** [comment]
I removed the assignee by myself because I'll go into the vacation next week.

**Comment by filipjnc** [comment]
I encounter the same issue. I cannot start/restart a workspace, so I need to create a new one everytime. Work not pushed is work lost.

**Comment by filipjnc** [comment]
Decided to try it out again today. Worked fine for an hour until the container stopped while working. Afterwards, cannot start the workspace. All my hour worth of work is gone - so annoying. Come one GitPod, get it together and fix it.

```

cannot initialize workspace: cannot restore backup: tar /dst: tar /dst: exit status 2;tar: .docker-root/overlay2/0ad5fb59a0da61c61bef0492772e450b29c3afb2c36d058fb30501d3fff86ac0/diff/usr/lib/supertokens/jre/legal/java.base/ADDITIONAL_LICENSE_INFO: Cannot open: Permission denied tar: .docker-root/overlay2/0ad5fb59a0da61c61bef0492772e450b29c3afb2c36d058fb30501d3fff86ac0/diff/usr/lib/supertokens/jre/legal/java.base/ASSEMBLY_EXCEPTION: 
…
```

**Comment by utam0k** [comment]
Hi, @filipjnc. Thanks for your report. This issue is already scheduled but has not yet been worked on due to priorities.
Can I ask you to share the repository or how to reproduce it?

**Comment by filipjnc** [comment]
Hi @utam0k,
Workspace ID: filipjnc-dtlearnhunt-l2swncfwtr7
Cluster: ws-eu54.gitpod.io

I can reproduce it as follows:
- Start new workspace from GitHub repo
- Shut down workspace or wait for timeout
- Can't restart it again, the error above keeps coming up. As if the container has been permanently corrupted.

**Comment by utam0k** [comment]
@filipjnc Thanks for your information. It helps us to resolve it. Is the reproduction rate 100%?

**Comment by filipjnc** [comment]
> @filipjnc Thanks for your information. It helps us to resolve it. Is the reproduction rate 100%?

Yes. Can reproduce it every time on my end. All old (damaged) workspaces could never be started again.

**Comment by utam0k** [comment]
Sorry for the trouble. Thanks for your help.

**Comment by semiautomatix** [comment]
![image](https://user-images.githubusercontent.com/20738236/183051818-927bfa49-286c-4003-a66d-75484b9d826e.png)

Unfortunately this is about the fourth workspace I've lost. I'm becoming obsessive about `git commit` before I switch off as trust in Gitpod is minimal at the moment.

**Comment by semiautomatix** [comment]
> Hi, @filipjnc. Thanks for your report. This issue is already scheduled but has not yet been worked on due to priorities. Can I ask you to share the repository or how to reproduce it?

As way of possibly testing, I'm using a skeleton of this project: https://github.com/sprintcube/docker-compose-lamp

**Comment by semiautomatix** [comment]
And again...

![image](https://user-images.githubusercontent.com/20738236/183058543-dff74fe1-22e6-4d63-b421-678488832426.png)

I forgot to push one of my commits, fortunately it's a small change. But annoying as because now I have to recreate the whole damn docker image.

**Comment by semiautomatix** [comment]
Attempted `docker-compose down` to bring everything down and no dice.

![image](https://user-images.githubusercontent.com/20738236/183061687-c257d7db-88aa-4b28-86d7-cac12d29fc8c.png)

**Comment by jenting** [comment]
> > Hi, @filipjnc. Thanks for your report. This issue is already scheduled but has not yet been worked on due to priorities. Can I ask you to share the repository or how to reproduce it?
> 
> As way of possibly testing, I'm using a skeleton of this project: https://github.com/sprintcube/docker-compose-lamp

@semiautomatix Sorry for the late reply 🙏 

I tried to use the repo https://github.com/sprintcube/docker-compose-lamp you provided
- Open workspace
- Run `docker-compose run`
- Write some files under the path `/workspace/docker-compose-lamp`
- Manually stop the workspace

However, I can't reproduce it. Would you please provide more detailed steps? Thank you.

**Comment by jenting** [comment]
> Hi @utam0k, Workspace ID: filipjnc-dtlearnhunt-l2swncfwtr7 Cluster: ws-eu54.gitpod.io
> 
> I can reproduce it as follows:
> 
> * Start new workspace from GitHub repo
> * Shut down workspace or wait for timeout
> * Can't restart it again, the error above keeps coming up. As if the container has been permanently corrupted.

@filipjnc Thanks for providing the information. I tried to access your repo to reproduce it, however since it's private so I can't do any further testing and reproduce it.

**Comment by semiautomatix** [comment]
> > > Hi, @filipjnc. Thanks for your report. This issue is already scheduled but has not yet been worked on due to priorities. Can I ask you to share the repository or how to reproduce it?
> > 
> > 
> > As way of possibly testing, I'm using a skeleton of this project: https://github.com/sprintcube/docker-compose-lamp
> 
> @semiautomatix Sorry for the late reply 🙏
> 
> I tried to use the repo https://github.com/sprintcube/docker-compose-lamp you provided
> 
> * Open workspace
> * Run `docker-compose run`
> * Write some files under the path `/workspace/docker-compose-lamp`
> * Manually stop the workspace
> 
> However, I can't reproduce it. Would you please provide more detailed steps? Thank you.

Thanks for the update. I was hoping a clean pull would recreated the error.

Additionally, I've cloned the project, added code to the www folder, started docker-compose, imported an SQL file into the database.

I'll attempt to recreate the error, and provide access to the repo.

**Comment by axonasif** [comment]
I encountered this issue as well.
<img width="567" alt="Screenshot 2022-09-05 at 12 45 26 PM" src="https://user-images.githubusercontent.com/39482679/188382057-33839e0d-ca0b-479f-b0f3-db9f68305c29.png">
```js
cannot initialize workspace: cannot restore backup: tar /dst: tar /dst: exit status 2;tar: buildkit/runc-overlayfs/snapshots/snapshots/28/fs/etc/sudoers.bkp: Cannot open: Permission denied tar: Exiting with failure status due to previous errors 
```
WS ID: `gitpodio-workspaceimage-5wke6grm46l`

**Comment by nisan1337** [comment]
I encountered this issue twice for today.
<img width="451" alt="image" src="https://user-images.githubusercontent.com/87061773/188457910-f8db2ae5-6cf4-46b3-bd81-019071fd3165.png">
I am suspecting this occurs because I left some docker containers(with compose) running and manually stopped the workspace.

**Comment by Nishchit14** [comment]
facing it too, lost many file changes and .env setup
#12900

**Comment by kylos101** [comment]
@Furisto to follow-up on our conversation from earlier today:
1. PVC may solve this, but self-hosted may not have PVC for a while.
2. We should see if we can do a tactical solution here. For example, gracefully stop containers long before dispose starts, really close to after either (1) a workspace times out or (2) a user stops a workspace.

**Comment by Furisto** [comment]
@kylos101 I am not convinced that 2. will help because containers that do not handle SIGTERM will be killed either way, regardless of the mechanism. I have found a way to reproduce this and it looks like it is related to us restoring the extended attributes of files. I do not get the error message in my workspace if I do not specify --xattrs during untar. Trying to find a way now how I can solve this error without reintroducing what caused us to restore extended attributes in the first place.

**Comment by kylos101** [comment]
> I have found a way to reproduce this and it looks like it is related to us restoring the extended attributes of files. 

Interesting @Furisto ! How come that permission denied message generally pertains to `.docker-root/overlay2`?

> I do not get the error message in my workspace if I do not specify --xattrs during untar. Trying to find a way now how I can solve this error without reintroducing what caused us to restore extended attributes in the first place.

Okay, this further confirms that going to PVC will resolve the issue. Can you share a reference issue or PR Re: `what caused us to restore extended attributes in the first place.`? I recommend setting a timebox for this issue, where you draw a line in the sand, sharing that if we cannot resolve confidently, then, we'll need to wait for PVC.

**Comment by Furisto** [comment]
We have identified a solution for this problem but it will take some time testing this until we can roll it out to all customers. Current estimate is ~1 month.

**Comment by 6uliver** [comment]
> Decided to try it out again today. Worked fine for an hour until the container stopped while working. Afterwards, cannot start the workspace. All my hour worth of work is gone - so annoying. Come one GitPod, get it together and fix it.
> 
> ```
> 
> cannot initialize workspace: cannot restore backup: tar /dst: tar /dst: exit status 2;tar: .docker-root/overlay2/0ad5fb59a0da61c61bef0492772e450b29c3afb2c36d058fb30501d3fff86ac0/diff/usr/lib/supertokens/jre/legal/java.base/ADDITIONAL_LICENSE_INFO: Cannot open: Permission denied tar: .docker-root/overlay2/0ad5fb59a0da61c61bef0492772e450b29c3afb2c36d058fb30501d3fff86ac0/diff/usr/lib/supertokens/jre/legal/java.base/ASSEMBLY_EXCEPTION: 
> …
> ```

We have exactly the same problem and we are also using Supertokens as a Docker container. I think it's related to these files under .docker-root/overlay2/(...)/diff/usr/lib/supertokens/jre/legal, they have 444 permissions which means no one has write access to these files. Maybe this is the root cause of the permission denied error.

**Comment by 6uliver** [comment]
I've created a simple repository where this bug can be reproduced in a stable way, I hope this will help to test the bugfix and resolve the bug.

### Steps to reproduce

1. Open this repository on Gitpod: https://gitlab.com/6uliver/gitpod-workspace-restart-error-repro
2. Wait for the workspace and Supertokens to be started, you should see this message in the console: "Started SuperTokens on 0.0.0.0:3567"
3. Stop the workspace and wait for it to be stopped
4. Open and start workspace

### Expected result

The workspace can be started successfully and Supertokens is running.

### Actual result

You can see a Gitpod error page with the text "Oh, no! Something went wrong!" and the following long error message:
```
initializeWorkspaceContent failed: cannot initialize workspace: cannot restore backup: tar /dst: tar /dst: exit status 2;
tar: .docker-root/overlay2/a061703a1735ce483b1f0d56341fe6943e2adf755b31b20a3f8ed82ee8f38e9e/diff/usr/lib/supertokens/jre/legal/java.base/ADDITIONAL_LICENSE_INFO: Cannot open: Permission denied 
tar: .docker-root/overlay2/a061703a1735ce483b1f0d56341fe6943e2adf755b31b20a3f8ed82ee8f38e9e/diff/usr/lib/supertokens/jre/legal/java.base/ASSEMBLY_EXCEPTION: Cannot open: Permission denied 
...
```

**Comment by utam0k** [comment]
@Furisto 
I noticed that this problem is for all upper-layer files. Perhaps it is a change that occurred within a container. This file is supposed to be deleted when dockerd stops. In other words, I thought I was receiving a SIGKILL, so I made this change. What do you think? I just couldn't figure out how to reproduce it and would love to hear what you know how to do.
https://github.com/gitpod-io/gitpod/pull/14498

**Comment by kylos101** [comment]
> @Furisto I noticed that this problem is for all upper-layer files. Perhaps it is a change that occurred within a container. This file is supposed to be deleted when dockerd stops. In other words, I thought I was receiving a SIGKILL, so I made this change. What do you think? I just couldn't figure out how to reproduce it and would love to hear what you know how to do. #14498

@utam0k are you able to recreate this issue when using PVC (like with Gitpod project and repo)? Or, are you only able to recreate when using backup powered by object storage? If the problem is isolated to object storage, we should wait, PVC may solve. If you can recreate the problem with PVC too, let us know?

**Comment by utam0k** [comment]
> @utam0k are you able to recreate this issue when using PVC (like with Gitpod project and repo)? Or, are you only able to recreate when using backup powered by object storage? If the problem is isolated to object storage, we should wait, PVC may solve. If you can recreate the problem with PVC too, let us know?

@kylos101 That's what I'm wondering too. However, I don't know how to reproduction this issue, I was asking @Furisto 
And if the problem is that processes in the workspace receive SIGKILL, this is a much more abstract problem. In other words, it is likely that there is software other than dockerd that will terminate without being given time to clean up afterwards. e.g. supervisor

**Comment by kylos101** [comment]
@utam0k @Furisto I am going to remove this issue from our project (for now) as we plan to proceed with PVC. Let's plan to reevaluate after PVC is being used.

**Comment by YoungElPaso** [comment]
I'm also having this issue - presumably the same reasons. This makes Gitpod unusable for half of my work... and makes the service generally unreliable.

**Comment by YoungElPaso** [comment]
Workaround for anyone else who has this issue before it's resolved: manually stop and clean up all containers and volumes before stopping your workspace.

Removing all containers and volumes is  PIA but as so far worked for me.

Wish Gitpod had a 'stop' task that we could automate this or any similar task in to fully teardown a workspace if we wanted.

**Comment by utam0k** [comment]
@YoungElPaso Thanks for finding a workaround. We plan to extend the grace period from the time a process in the workspace receives the SIGTERM to the time it exits to 3 minutes on the next deployment. Currently, it is 30 seconds. Perhaps this will affect this issue. Please wait for a little.

**Comment by 6uliver** [comment]
I've just lost a couple of hours of work because of this issue. 😠
My "_best practice_" for these cases was to download the workspace by hand, extract the content on my local machine, commit the changes and push it. It's a very ugly workaround when I would like to use a cloud IDE.

Fortunately there is an epic which goal is to "Better protect user data" so that "they will not lose data.": https://github.com/gitpod-io/gitpod/issues/7901

Part of this epic was to remove the download feature: https://github.com/gitpod-io/gitpod/issues/14364

So now I **really** lost my work, and I can not download the whole workspace anymore. 😢
It's very strange to work in a way that I have constant anxiety about losing my work.

**Comment by axonasif** [comment]
@6uliver sorry for the trouble, could you please email us at support@gitpod.io with your workspace ID? Our support team could try getting a backup for you.

**Comment by 6uliver** [comment]
> @6uliver sorry for the trouble, could you please email us at [support@gitpod.io](mailto:support@gitpod.io) with your workspace ID? Our support team could try getting a backup for you.

Sure, thank you for your help, maybe I will write. But it's a temporary solution to ask support to restore my workspace every time when this problem happens :)

**Comment by atduarte** [comment]
I'm sorry we haven't solved this yet, @6uliver and @YoungElPaso. I just tested the repository linked above (thanks, @6uliver!) and the error continues to happen.

@kylos101 given the huge impact of this error, I will add this to breakdown

**Comment by kylos101** [comment]
> Hoping we can fix the core issue thought pray
:100: :dart: yes, I believe @Furisto may even have a branch that could help with this, but, it's in a draft state. @Furisto is that right?

**Comment by kylos101** [comment]
Added steps to recreate and how to test (by inspecting prior PRs), moving to Scheduled

**Comment by kylos101** [comment]
@utam0k can you move this issue to In Validation? It's PR is deployed.

**Comment by 6uliver** [comment]
> 👋 @6uliver @YoungElPaso @filipjnc @semiautomatix @nisan1337 @Nishchit14 , we wanted to reach out and let you know that this issue is in fact resolved as of gen79 (us79 or eu79). I just double checked logs, and there are no traces of this error as of gen79 (which contains the fix). Let us know if you continue to have any trouble restarting stopped workspaces?

Great news! We tried it out for our project and it's working fine! Thank you very much, it has a great impact for us!

**Comment by filipjnc** [comment]
I'm able to restart the pods without issues now too. Loving gitpod again :)

**Comment by kylos101** [comment]
:wave @srgwsrgwetgethg this was an incident https://www.gitpodstatus.com/incidents/rs838czq8clg, and resolved by https://github.com/gitpod-io/gitpod/pull/18236
