### ISSUE TITLE
Replace 'Company' with 'Company Name' in account profile

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#11182]
Suggestion based on [feedback](https://gitpod.slack.com/archives/C01KPEPNBD0/p1657041828327789) (internal) to #11023
![Screenshot 2022-07-05 at 16 43 40](https://user-images.githubusercontent.com/849592/177643911-14e9d9d0-e047-4ec2-9ca7-a4849b4a65cf.png)

**Comment by gtsiolis** [comment]
Things to consider before updating the text label:
1. The term Company is the most common term for an input like this
2. Using short terms when possible is preferred
3. Name could be a bit ambiguous for a text label

Instead we could add a help text as seen in the initial specs, see https://github.com/gitpod-io/gitpod/issues/10999#issuecomment-1170455932.

| Account |
|-|
|  <img width="1440" alt="Account-3" src="https://user-images.githubusercontent.com/120486/176541476-9e868667-1bb3-4dd7-9a68-1bf989997c16.png"> |

**Comment by phimae** [comment]
had a short chat with @svenefftinge yesterday who gave some context: GitLab will pass the company domain instead of the name which is why he opted for name in the first place. This field is empty for existing users but will be pre-populated for new users that have the company or company domain property in their SCM

**Comment by gtsiolis** [comment]
Thanks, @phimae!

> This field is empty for existing users but will be pre-populated for new users that have the company or company domain property in their SCM

Agree, this makes sense. 💯 

> GitLab will pass the company domain instead of the name which is why he opted for name in the first place. 

Using the domain here could be tricky or confusing to users without using any help text. 💭 

Thinking about this again, maybe it could help to also change the text label from _Company_ to _Organization_ to also support institutes, open source orgs[[1](https://www.gitpod.io/for/opensource)], etc.?
