### ISSUE TITLE
Epic: Browser based terminal

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#11180]
Epic covering the implementation of a terminal in the browser as an explicit IDE preference. 

Related to spike: https://github.com/gitpod-io/gitpod/pull/8464

**Comment by filiptronicek** [comment]
Had the same thought as @felladrin in my head. I think this would make sense and make it clear and expose more users to connecting just to their terminal.

**Comment by filiptronicek** [comment]
oh nonono you won't close on me stalebot

**Comment by filiptronicek** [comment]
hmmm I guess you will though, we have separate issues to handle this. Please use https://github.com/gitpod-io/gitpod/issues/17724 for feedback.
