### ISSUE TITLE
Extension Drag & Drop not working

### ISSUE THREAD

**Issue by CastHash532** [gitpod-io/gitpod#1119]
**Describe the bug**
After i drag & drop the .vsix file , the notification shows uploading  then installation and finally deploying but then nothing happens at all, no extension added.

**Additional Information**
I'm using chrome browser on Windows
downloaded the .vsix files from vsixhub.com

**Comment by JesterOrNot** [comment]
Can you send me a link to the extension?

**Comment by Amine-Sahraoui** [comment]
https://www.vsixhub.com/vsix/10524/

**Comment by JesterOrNot** [comment]
I wasn't able to reproduce your issue
![image](https://user-images.githubusercontent.com/50386709/72682669-301d8300-3a95-11ea-9292-e8aaa3aec635.png)
Can you send a screencast

**Comment by Amine-Sahraoui** [comment]
I think it has something to do with Internet filtering in my school

**Comment by Amine-Sahraoui** [comment]
I think i figured out the problem
It has to do with  custom image configuration
Here's a screencast : http://somup.com/cYVY2tfPAQ

**To Reproduce**
Setup the project with a custom docker image configuration for VNC support (not sure for other images)
Upload extension .vsix file with drag and drop
Open .gitpod.yml file

**Comment by Amine-Sahraoui** [comment]
It worked only after replacing:
```{ image: { file: .gitpod.Dockerfile } }```
With:
```image:  
  file: .gitpod.Dockerfile```

Snapshot:  https://gitpod.io#snapshot/f7e17519-a9bf-457e-b355-7dce4cc74ca9

**Comment by svenefftinge** [comment]
Yes ☝️ is the cause. The setup wizard sometimes generates a yaml syntax that the extension installation doesn't understand when it adds the extension information to `.gitpod.yml`. I have already changed the setup wizard so that it doesn't do that anymore, but it is not yet deployed.

**Comment by svenefftinge** [comment]
deployed
