### ISSUE TITLE
Not sure how to access a private repo?

### ISSUE THREAD

**Issue by daniel-hill** [gitpod-io/gitpod#112]
I used the http://gitpod.io#myprivateurlrepohere

And Gitpod complains that it hasn't got access, which is right, but doesn't give me any means of giving it access.

Upon registration, Gitpod only seeks permissions to access my public repos

Any ideas?

**Comment by svenefftinge** [comment]
Gitpod should show a message that the repository doesn't exist and that it might be private (because we get 404 from GitHub). There is also a link that allows you to grant that access.

Today, however all strange things happen, because of GitHub being down or unreliable.

**Comment by daniel-hill** [comment]
A link to give greater permissions is appearing now. Must be contributed to GitHub's mishaps yesterday!
