### ISSUE TITLE
Custom fontFamily does not work for Safari browser

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#11207]
### Bug description

Related:
- https://github.com/microsoft/vscode/issues/125968
- https://github.com/tuanpham-dev/code-server-font-patch

### Steps to reproduce

- Try to use a system installed custom font on `terminal.integrated.fontFamily` or `editor.fontFamily` on your Gitpod VSCode settings.
- Use your workspace on Safari

### Anything else?

Original question at Discord: https://discord.com/channels/816244985187008514/816246578594840586/994524386864418836

I made a quick experiment by making some changes to https://github.com/tuanpham-dev/code-server-font-patch and killing the IDE process on start from `.gitpod.yml`, not sure if it works 😂 

You can see [here](https://github.com/axonasif/code-server-font-patch/blob/master/.gitpod.yml) (Update: Doesn't work)

cc @schickling

**Comment by schickling** [comment]
Quick update: I've given the `code-server-font-patch` by @axonasif a try but no luck so far:

![image](https://user-images.githubusercontent.com/1567498/177830858-3f791b4a-6549-426b-b80f-f802c58a8d93.png)

**Comment by akosyakov** [comment]
You should try to reproduce on https://vscode.dev/ and report to upstream: https://github.com/microsoft/vscode
