### ISSUE TITLE
Analytics on `vscode.extensions` inside `.gitpod.yml`

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#11200]
## The problem
Many users have trouble getting the extensions they are using to VS Code. Therefore, users may choose to install their extensions via URLs leading to their corresponding `.vsix` packages.

If we can get insights into what extensions they are using, we can talk to extension authors to publish to Open VSX to make a better experience.

## Proposed solution
Using the [gitpod-web](https://github.com/gitpod-io/openvscode-server/tree/gp-code/main/extensions/gitpod-web) extension, we could check the extensions listed and report either all extensions or just the ones that use a URL. We would then do some post-processing on the data to determine what extension IDs the URLs actually represent.

**Comment by filiptronicek** [comment]
Linking [an internal discussion](https://gitpod.slack.com/archives/C01KGM9AW4W/p1657013980441349?thread_ts=1657009367.430579&cid=C01KGM9AW4W).

**Comment by akosyakov** [comment]
To be clear it is important for VS Code Desktop, not VS Code Browser. I think we need to add analytics in our validation logic in shared package in case of ui kind is desktop.

**Comment by akosyakov** [comment]
I'm going to close this issue, since we got data without additional analytics.
