### ISSUE TITLE
Make Terminal- /Ports- /Problems-panel Minimizable

### ISSUE THREAD

**Issue by ccssmnn** [gitpod-io/gitpod#1120]
Currently it seems impossible to minimize the terminal panel without closing the terminal (killing the terminal process).

On desktop its possible to drag it down a little bit to get more vertical space for reading and editing code, but on iPad this is not possible. Either way a button for minimizing these panels would be great. Tabs of open Terminals / Portinformation etc. should still be visible (clickable).

VSCode has a similar button.

**Comment by JesterOrNot** [comment]
https://www.loom.com/share/89affca4ac524d06a369f57f2e3beee9

**Comment by ccssmnn** [comment]
There are toggle view commands for ports and problems but not for terminal. Should I file a new issue for this?

**Comment by JesterOrNot** [comment]
If we are filing a new issue we should do it in eclipse-theia Gitpod's IDE

**Comment by JesterOrNot** [comment]
To track this issue further please see https://github.com/eclipse-theia/theia/issues/6913
