### ISSUE TITLE
Infer name from public key uploaded.

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#11212]
Current `title` field in SSH key upload is mandatory, however we can first try to infer the name from the key to avoid a user being required to explicitly name the key. 

<img width="499" alt="image" src="https://user-images.githubusercontent.com/5528307/177820871-8d7dbece-ea8e-440b-9585-5194f7adfe59.png">

**Comment by abdullahranginwala** [comment]
Hello! This is my first time contributing to GitPod. Could you elaborate a little on this issue? I'm really excited to explore GitPod and your help will be really appreciated.
