### ISSUE TITLE
[JetBrains Gateway Plugin] "TransportException: Timeout expired" on Gateway v2022.1 & "Connect in Browser" button not working Gateway v2022.2

### ISSUE THREAD

**Issue by yangbo19** [gitpod-io/gitpod#11227]
### Objective

![1657266853848](https://user-images.githubusercontent.com/95022180/177944881-fbc518b3-9cf8-4abb-88e6-fc5e84f40665.png)

**Comment by felladrin** [comment]
ℹ️ The fix has just been deployed to Gitpod servers.

**Comment by yangbo19** [comment]
May be that I still don't know how to solve it.

**Comment by felladrin** [comment]
@yangbo19 are you still having this issue? If so, could you provide more details about what's happening?

Also please check this topic:

- [What should I do if JetBrains Gateway and Gitpod aren’t working?](https://www.gitpod.io/docs/troubleshooting#what-should-i-do-if-jetbrains-gateway-and-gitpod-arent-working)

Cause it could be related to your Gateway or Plugin being out of date.

**Comment by yangbo19** [comment]
Thank you for your help.I face another question.
![1657514222197](https://user-images.githubusercontent.com/95022180/178189474-faf862ec-8371-4b78-ada4-31cfb60b97d7.png)
![1657514248366](https://user-images.githubusercontent.com/95022180/178189513-472c20da-57f3-43c8-bca9-52f485db5733.png)
I switched to this version.

**Comment by felladrin** [comment]
That's right! You need to log in to Gitpod from the JetBrains Gateway. So clicking "Connect in Browser" should lead you to the Gitpod page, where you log in and authorize JetBrains Gateway to use your account. It's needed, to have access to your workspace list and start new workspaces.

Let us know if the login works.

**Comment by yangbo19** [comment]
I have clicked, but nothing happens.Do you have any idea?Thank you.

**Comment by felladrin** [comment]
Let me try to reproduce the issue here.

**Comment by yangbo19** [comment]
What can I do for you ? Thank you for your help.

**Comment by felladrin** [comment]
I've cleaned my JetBrains Gateway install and re-installed it from scratch, and it's working. These were the steps from me:

Installed the Gateway.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/418083/178251982-8a5cb249-dbfb-4f92-b5bf-81a6f5d43805.png">

Clicked to install the Gitpod Extension.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/418083/178252120-9300fc00-0d4e-42be-ba6e-c992eede79cd.png">

Clicked Connect to Gitpod and it opened a browser tab:
![image](https://user-images.githubusercontent.com/418083/178252331-827a51e5-161e-42a1-ab7f-9dd174ae3b20.png)

The browser tab closed after it logged me into Gitpod, and brought me back to the JetBrains Gateway:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/418083/178252725-fa221674-8f2b-4a2c-b341-ac280165d458.png">

**Comment by felladrin** [comment]
Could you please confirm also if you're using the latest Gitpod Plugin version?

If not, you'll see it asking for you to update it on JetBrains Gateway _Preferences >> Plugins_, like this:
<img width="978" alt="image" src="https://user-images.githubusercontent.com/418083/178250186-a0bce14a-2496-4840-986a-626ded8a0ccd.png">
If that's the case, update and let us know if it works.

**Comment by yangbo19** [comment]
Thanks for your help again! 
![1657541577743](https://user-images.githubusercontent.com/95022180/178261575-cbc992d2-e0cd-43d6-84af-45510aeab30b.png)
But when I clicked connect to Browser,still nothing happen.
![1657541697720](https://user-images.githubusercontent.com/95022180/178261902-400d5eff-0e8f-4808-946e-9bc9a7e9604b.png)
Do you support its use in China?

**Comment by felladrin** [comment]
Maybe it's some conflict or cache with the account logged in the browser.

Could you try accessing https://gitpod.io/workspaces, logging out, and then clicking the "Connect in Browser" button?

Then, clicking on the button should lead you to this page:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/418083/178263401-60fa9989-0890-41e2-a236-4c022ea070a3.png">

Is this what happens?

If it doesn't work, here's another question: when logging into gitpod, are you using GitHub, GitLab, or BitBucket to connect?

**Comment by yangbo19** [comment]
I am soory that this method didn't work.I use github.
![1657542847077](https://user-images.githubusercontent.com/95022180/178265314-64ca47f2-e6a5-4d04-8289-2063680b5e8a.png)
I used gitpod this way before.

**Comment by felladrin** [comment]
Another thing I've noticed:

If you click the "Connect in Browser" button and it opens the login page, but right after you close the browser page (without logging in), if you click the "Connect in Browser" button again, it will do nothing (because it's still waiting for the response from the page that was closed).

And the only way to make the button work again is to close JetBrains Gateway app, re-open it, and click the "Connect in Browser" button again.

Could you please try force-quitting the app (or restarting your machine) and try again?

**Comment by yangbo19** [comment]
I restarted my machine.It still didn't work.

**Comment by yangbo19** [comment]
But I really appreciate your help.

**Comment by akosyakov** [comment]
@yangbo19 Please make sure to follow https://www.gitpod.io/docs/troubleshooting#gitpod-logs-in-jetbrains-gateway 🙏

**Comment by felladrin** [comment]
We've received the logs @yangbo19, thanks for sending them.
It seems it's being blocked from your network. You mentioned it was working before, right?
Do you remember when the connection through JetBrains Gateway worked last time?
Was there some notable change on your network/firewall meanwhile?

**Comment by yangbo19** [comment]
I used JetBrains Gateway first time.I just downloaded it and installed gitpod.I didn't do other things.

**Comment by felladrin** [comment]
@yangbo19, thanks for confirming. I believe this issue is due to network blocking, so I'd like to ask if you're using a VPN, and if not, would you be able to use one for us to confirm if it would solve the problem?

**Comment by yangbo19** [comment]
![Uploading 1657630765629.png…]()
This is link.
