### ISSUE TITLE
Request: Add Per User Configuration

### ISSUE THREAD

**Issue by CastHash532** [gitpod-io/gitpod#1122]
It would save time if you add a per user configuration feature for environments
Like the one in Visual Studio Online.

**Comment by jankeromnes** [comment]
Hi @Amine-Sahraoui! Thanks for the great suggestion.

I'm not familiar with how VSO does it, but please note that https://gitpod.io/environment-variables/ allows you to set ENV variables across all workspaces (can be specific to repositories, orgs, or for everywhere with the filter "*/*").

Additionally, you can change IDE settings on a user-wise basis.

I believe there will also soon be a way to install some VS Code extensions automatically in all your workspaces.

**Comment by akosyakov** [comment]
@Amine-Sahraoui Do you mean dot env files? https://docs.microsoft.com/en-us/visualstudio/online/reference/personalizing ? If you can share a bit more info it would be helpful.

Regarding of https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring. Gitpod supports much more already via .gitpod.yml file, please see our docs: https://www.gitpod.io/docs/40_configuration/
