### ISSUE TITLE
All requests from Gateway to server is blocked

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#11228]
### Bug description

All request from Gateway to server is missing, `sendHeartbeat` not works so that users will get timed out by their default time out duration if they only open JetBrains IDE.

See also user report in [discord](https://discord.com/channels/816244985187008514/994584933265846322), and [internal Chat](https://gitpod.slack.com/archives/C03LKE6AS93/p1657202967512559)

This bug come up since `2 pm, Thu, Jun 30, 2022`, maybe related to PR https://github.com/gitpod-io/gitpod/pull/10974

### Steps to reproduce

- Open workspaces with any JetBrains IDEs
- Check if heartbeat sent

**Comment by felladrin** [comment]
ℹ️ The fix has just been deployed to Gitpod servers.
