### ISSUE TITLE
AWS Single Cluster Ref Arch: Create a nice transition to gitpod installation

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#11223]
Currently, the [AWS single cluster reference architecture](https://github.com/gitpod-io/website/pull/2324) just ends without giving input into what one needs to fill out in the following Gitpod installation to connect said installation to the resources created in the ref arch. 

We should change this by exposing the values one would use to connect the created resources to the subsequent gitpod installation - see the [GCP version](https://www.gitpod.io/docs/self-hosted/latest/reference-architecture/production-ready-single-cluster#install-gitpod) for inspiration. 

**Acceptance Criteria:**
- Go through current state of the AWS single cluster reference architecture
- Provide a similar table of values that you need to input during the kots installation UI to then connect Gitpod to the created resources

**Comment by adrienthebo** [comment]
Resolved in #2458.
