### ISSUE TITLE
Custom CA Cert isn't placed in Blobserve

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#11233]
### Bug description

When using a custom-generated TLS cert, the CA Cert isn't placed in the blobserve deployment. This results in the workspace not being able to be accessed.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/275848/177979322-7bff9b06-8da5-40ab-a450-a1574f252306.png)

### Anything else?

- Might be related to #11070

**Comment by J-Insel** [comment]
We've circumvented the issue by changing the blobserve image. We patched in our certificates and re-uploaded the image again. But I guess this is only a solution for air gapped environments. 

The openvsx-proxy has the same issue, it does not get the certificates that are provided while installing Gitpod.
