### ISSUE TITLE
Share Running workspace is broken

### ISSUE THREAD

**Issue by yamsergey** [gitpod-io/gitpod#1123]
**Describe the bug**
`Share running workspace` doesn't work. Al the time I share a workspace with a link, another person can't open it. 

**To Reproduce**
Prerequisites:
1. Two accounts on github
2. Public java project (e.g. https://github.com/yamsergey/learn-java)

Steps:
1. Open the project with Gitpod
2. Try to share running workspace 

**Expected behavior**
It works

**Additional Information**
![Unbenannt](https://user-images.githubusercontent.com/666661/72758353-d6bb6e00-3bd2-11ea-9948-4e3810a1eff0.PNG)

**Comment by svenefftinge** [comment]
I think you ran into a UX issue we have there in that you have to explicitly click the 'share' button in the opened dialog once more. We should get rid of that and do this automatically when running the share command.

**Comment by yamsergey** [comment]
🤦‍♂  Sorry, my miss. One small thing. I see how another person typing in n terminal, but I don’t see files opened and changed ( I see changes on lunch when they are saved). Is it how it planned?

**Comment by yamsergey** [comment]
I will close the issue.
