### ISSUE TITLE
Prebuilds show wrong Pending status while pulling & building image(s)

### ISSUE THREAD

**Issue by szab100** [gitpod-io/gitpod#11248]
### Bug description

Prebuilds show "Pending" status while they are already building the workspace's Dockerfile (basically the docker part), and the output is already being streamed to the UI as well. This phase - depending on the complexity of the used dockerfile & structure of base imgs - can last quite long and apart from the wrong UI messaging, the major issue is that due to this time spend in Pending status, Gitpod does not count it towards the time spent (and saved) during the prebuild.

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/10001539/178079269-e8ef5559-a1be-46cd-9861-50a177963bd5.png">

Example:
- image building takes 5 mins
- running before & init commands take 7 mins
- => Gitpod welcomes the user saying he saved only 7 mins, while if starting the same workspace from scratch w/o a prebuild, users wait the full 5 + 7 = 12 mins

### Steps to reproduce

Just use some more complex dockerfile for the workspace, even better if it is using a base that has not been loaded on the node before.

### Expected behavior

See the "Running" status while building the image, or some new differentiated status, like "Initializing" (elapsed time in this status is still counted into prebuild times).

**Comment by geropl** [comment]
@szab100 I agree that the status and message we display is confusing.

> the major issue is that due to this time spend in Pending status, Gitpod does not count it towards the time spent (and saved) during the prebuild.

I think that's fine, because image builds and prebuilds are foundamentally decoupled, and images might be reused my n prebuilds, so not taking that time into account IMO makes sense.

Technically, PENDING also make sense from the perspective of the prebuild, because it's waiting for the image build to finish. But we definitely need to update the misleading text message.

@szab100 Would that help already? 🤔

**Comment by geropl** [comment]
> So IMO, users should be able to clearly see and understand how much (total and in each individual phases) time was spent during prebuilds and workspace starts

Could not agree more. :upside_down_face:  All of this information is valuable to users, and should definitely be displayed. I think it's worth having a [separate feature request](https://github.com/gitpod-io/gitpod/issues/11552) for that. :100:

> BTW, we experienced a seemingly buggy behavior with prebuilds on our self-hosted today: prebuilds stayed in PENDING state (3 out of 3 we triggered sequentially).

Next weeks self-hosted release will come with a bunch of improvements to the prebuilds/image builds process, which I think should fix this behavior. Note that we recently introduced "auto-cancel" of running prebuilds (if they happen to be on the same branch), which might or might not be related to your observation:
![image](https://user-images.githubusercontent.com/32448529/180380093-5695feae-f7a9-4c53-8cc6-f13bdafa9104.png)
