### ISSUE TITLE
`onOpen: open-preview` is not working

### ISSUE THREAD

**Issue by topher200** [gitpod-io/gitpod#11243]
### Bug description

`onOpen: open-preview` in `gitpod.yml` is expected to open a preview of the website served by the port on Workplace startup.

However, no preview is being opened.

### Steps to reproduce

This is broken in Gitpod's example documentation (as well as my own project).

1. Navigate to https://www.gitpod.io/docs/languages/html#try-it
2. Click "Open in Gitpod"

### Expected behavior

Expected behavior: Preview opens a webpage

Actual behavior: no webpage is opened

### Example repository

https://gitpod.io/#https://github.com/gitpod-io/Gitpod-Web-Development-Example

### Anything else?

I tested this in Chrome and Firefox on the Gitpod example repo.

![image](https://user-images.githubusercontent.com/206988/178033050-3c7ae55c-c11a-4c5e-b079-a18e5695118d.png)

![image](https://user-images.githubusercontent.com/206988/178033109-64352fe6-1b06-4250-8b28-40561eddd601.png)

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.10
Release:        21.10
Codename:       impish
```

**Comment by shesek** [comment]
I'm experiencing the same issue.

**Comment by mustard-mh** [comment]
Fixed and deployed to production
