### ISSUE TITLE
500 Internal Server Error nginx/1.14.1 when tried to open workspace

### ISSUE THREAD

**Issue by HSSANT** [gitpod-io/gitpod#1126]
Hello again.
500 Internal Server Error nginx/1.14.1 when tried to open workspace

@jankeromnes could you please check? 

Thanks.

**Comment by geropl** [comment]
@HSSANT Thanks for reporting, we're on it. Any other observation that could help?

**Comment by geropl** [comment]
I'm closing this as the US cluster is working again. Please re-open if that's not the case for you!

**Comment by jankeromnes** [comment]
FYI this specific problem is now tracked in #1128. We're currently able to fix this intermittent problem within 30 minutes whenever it appears, and we're working toward fixing the root cause to prevent it from happening again.
