### ISSUE TITLE
"Connect" button on Gitpod Workspaces list in JetBrains Gateway points to a URL that may be outdated

### ISSUE THREAD

**Issue by felladrin** [gitpod-io/gitpod#11284]
### Bug description

"Connect" button on the side of each workspace name on the list of workspaces leads to outdated workspace URLs (e.g. `https://gitpodio-empty-z3ml0fq4itx.ws-eu51.gitpod.io/`) when it should lead to `https://gitpod.io/start/#gitpodio-empty-z3ml0fq4itx`.

![image](https://user-images.githubusercontent.com/418083/178271687-799a6660-6f33-49c9-a4f1-3c3ab66e3f96.png)

<img width="796" alt="image" src="https://user-images.githubusercontent.com/418083/178272156-d19f0897-94fd-47cf-b5c3-d054aa2b144b.png">

In this case, the error happened because the Cluster `eu51` doesn't exist anymore. Using `https://gitpod.io/start/#` correctly leads the user to an actual cluster (`eu53` at the time of writing).

### Steps to reproduce

- Create a workspace from gitpod.io UI.
- Stop the workspace.
- Open Gitpod Workspaces list in JetBrains Gateway.
- Click the "Connect" button.
- Observe the URL opened in the browser: it's the workspace URL from the last time it was opened.

### Expected behavior

It should lead to an URL with the format `https://gitpod.io/start/#<WORKSPACE_ID>`.

**Comment by akosyakov** [comment]
@felladrin We should align the logic here with dashboard. Just using start page is not enough, since it is another flow. IDE url in most case is the best option. I think it happens only when the cluster is gone. cc @aledbf @kylos101 correct?

**Comment by kylos101** [comment]
@felladrin what is the first picture of? Is it the Gitpod Dashboard page, or some local JetBrains Gateway showing old workspaces?

@akosyakov assuming you can be certain the workspace is not running (or starting or stopping) and is truly off, I agree, you should link to something like `https://gitpod.io/start/#<WORKSPACE_ID>`.
