### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by gabsrodriguez** [gitpod-io/gitpod#1129]
Good afernoon! When i push my work, the rendered page gives a 500 internal server error

**Comment by jankeromnes** [comment]
Hi @gabsrodriguez, thanks for reporting this. It's an intermittent problem which seems to happen randomly in the US region. We're actively investigating it, quickly fixing it every time it pops up, and we believe we're getting closer to understanding the root cause.

Let's track this in #1075.

**Comment by jankeromnes** [comment]
FYI this specific problem is now tracked in #1128. We're currently able to fix this intermittent problem within 30 minutes whenever it appears, and we're working toward fixing the root cause to prevent it from happening again.
