### ISSUE TITLE
add support for asciidoc

### ISSUE THREAD

**Issue by rdmueller** [gitpod-io/gitpod#113]
asciidoc is a powerfull markup language like markdown - but with more features :-) https://asciidoctor.org/

It would be great if gitpod.io would also support asciidoc previews the same way as it supports them for markdown.

Is it correct that theia supports vs-code plugins? Then the solution would be to just add this plugin:
https://marketplace.visualstudio.com/items?itemName=stayfool.vscode-asciidoc

**Comment by svenefftinge** [comment]
> Is it correct that theia supports vs-code plugins? 

Not yet, support is still in development.

**Comment by svenefftinge** [comment]
Also we should check for `README.adoc` files and auto open them in preview mode in the default context.

**Comment by svenefftinge** [comment]
https://github.com/theia-ide/theia-asciidoc-extension

**Comment by rdmueller** [comment]
wow. that was quick!
But I guess it will still take some time for the plugin to find its way to gitpod?
Can I help with beta-testing or something like that?

**Comment by svenefftinge** [comment]
It will go into production early next week.
You can test the extension above within through:
https://gitpod.io/#https://github.com/theia-ide/theia-asciidoc-extension

And running the following in the terminal:
```sh
yarn && cd browser-app/ && yarn start --hostname 0.0.0.0 ..
```
