### ISSUE TITLE
[local-preview] Add Arm (and Mac M1) support

### ISSUE THREAD

**Issue by Pothulapati** [gitpod-io/gitpod#11309]
## Is your feature request related to a problem? Please describe

Currently, `local-preview` does not work on Arm platforms including Mac M1. There seems
to be a couple of reasons why
- Support for `k3s` inside a docker container (Looks like we have to upgrade our `k3s` to latest)
- Get our docker images built for `arm` platform

Doing the above things, Might also add support other devlces like raspberry PI, etc.

## Describe the behaviour you'd like

Work on Mac M1 as it works on an Intel Mac.

## Additional context

- [Last known stance on ARM support
](https://github.com/gitpod-io/gitpod/pull/7937#issuecomment-1042718737)

**Comment by zakariahmusic** [comment]
Duplicate of # #11552

**Comment by charleswhchan** [comment]
Is this still issue still valid given the recent release of the (experimental) Support for running x86-64 binaries with Rosetta 2?
https://github.com/docker/roadmap/issues/384
