### ISSUE TITLE
[chore] Get rid of WorkspaceType "probe"

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#11315]
This includes:
 - shipping a migration to delete it from all installations
 ´´´
SELECT COUNT(1)
FROM d_b_workspace AS ws
WHERE ws.type = 'probe';
´´´
   still reveals a couple of instances
 - find last usages and types in code and remove those as well

**Comment by easyCZ** [comment]
How do we approach nuking the records from the DB? Do we need to make the cleanup work in self-hosted instances also? Or were probes only a cloud concept?

One approach is to write this as a migration which deletes the records, but that in itself may not work too great in terms of the interaction with `db-sync`.
Alternatively, we run this as a scheduled job on `server`.

**Comment by easyCZ** [comment]
Final piece - removal of instances from the DB is here https://github.com/gitpod-io/gitpod/pull/13477

**Comment by easyCZ** [comment]
All probe workspaces have been deleted from SaaS.

I've created a follow-up to remove the garbage collector - https://github.com/gitpod-io/gitpod/issues/13773. Closing as complete.
