### ISSUE TITLE
[Get rid of OTS] Add an integration test for protected_secrets feature flag

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#11318]
## Is your feature request related to a problem? Please describe
Add integration for the protected_secrets feature flag. 

## Describe the behaviour you'd like

Have an integration test for the protect_secrets feature flag, it'd be good to test both public and private repo is able to launch a workspace and stops the workspace where the context is a private Git repo (not a prebuild).

## Additional context

#11198

**Comment by kylos101** [comment]
@jenting I am going to remove you for now. If you decide to do in the future, please assign yourself back.

**Comment by kylos101** [comment]
Consider using the identify related to this [user token](https://github.com/gitpod-io/gitpod/blob/bf59b02156086e9422266d244657f62b5d53e8a2/test/tests/workspace/contexts_test.go#L98)
