### ISSUE TITLE
Suggestion: Set rust.actionOnSave as check by default

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1131]
Rustlang's IDE used from vscode (currently 22012020 unreliable on gitpod https://github.com/gitpod-io/gitpod/issues/1098) is recompiling the whole project by default on each change which seems system resources inefficient -> Proposing parsing

```
  "rust.actionOnSave": "check",
```

In GitPod's configuration by default (allow end-user to overwrite if desired) which afaik is generally prefered and is friendly on system resources

**Comment by ArtemGr** [comment]
Copy-pasting a snippet of mine:
```
    {
      // NB: Eager saving and RLS translates to cursor lag on GitPod.
      //     Have to hark back to manual Ctrl+S saving there.
      //"editor.autoSave": "on"
      // Only do RLS on save
      "rust.build_on_save": true
    }
```
