### ISSUE TITLE
[server] consider avoiding retry of StartWorkspace

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#11327]
### Bug description

[This prebuild instance ID](https://cloudlogging.app.goo.gl/CC24SNiH529cQfAD9) was attempted to be started five times, which appears to be coming from `ws-manager-api`, and may be coming from [here](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/typescript/src/promisified-client.ts#L111).

### Steps to reproduce

Try doing in a preview environment where the node is cordoned, and make a change to a branch or PR that warrants a trigger of a prebuild. That should result in `server` trying to `startWorkspace` five times.

Another option (which may be simpler) is to try starting a Regular workspace, rather than a Prebuild, against a cordoned node.

### Workspace affected

Refer to logs (above)

### Expected behavior

Server would try starting a workspace once, and not retry, if the workspace cluster indicated the workspace start was failed.

### Example repository

n/a

### Anything else?

We introduced exponential backoff within `ws-manager` for `startWorkspace` [here](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/pkg/manager/manager.go#L304), which should cover retries (at least when there is a failure within the workspace cluster). 

Do we want to also retry workspace starts from `server`? :thinking:

**Comment by geropl** [comment]
@kylos101 Retries were introduced to cope with the fact start on a given workspace cluster might fail, but maybe another one is available to serve it.

Would it be ok to ensure not to re-try the same cluster here? 🧘

**Comment by aledbf** [comment]
Closing. Fixed in https://github.com/gitpod-io/gitpod/pull/11547
