### ISSUE TITLE
Add Phone Verification for new Users

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#11339]
In order to reduce the ever increasing amount of abuse on Gitpod, we'd like to make it hard for such people to get onto Gitpod. The hypothesis is that phone number verification would add an extra step that can reduce the amount.

The verification should happen before after signup but before they can start their first workspace. We could further reduce the friction for good users by whitelisting based on certain criteria (e.g. age of GH or GL account). 

The verification should only be active on SaaS and we should make use of an external service such as Twillio's Verify.

See **[design specs](https://github.com/gitpod-io/gitpod/issues/11339#issuecomment-1183387915)** below. 🥯

**Comment by gtsiolis** [comment]
Cross-posting also some [relevant meeting notes](https://www.notion.so/gitpod/Product-Sync-d646bfe174284af98fd4397ad9145f94#47b55951499048179146b0fde48c171e) (internal) and two relevant RFCs[[1](https://www.notion.so/gitpod/02991a4e1d214b2a9325969b1c9acdfe)][[2](https://www.notion.so/gitpod/c472058591af4e57b2497a5b6ebc67cd)] (internal).

**Comment by gtsiolis** [comment]
Moving this to _In Progress_ to catch up with the recently open https://github.com/gitpod-io/gitpod/pull/11346. Cc @svenefftinge

**Comment by gtsiolis** [comment]
Adding below some early designs on how the flow could look like, depending on the third party service API flexibility and if we're going to also block or allow dashboard access when a user has not completed user validation:

| Modal (Empty) | Modal (Input) | Modal (Invalid Input)
|-|-|-|
| <img width="1440" alt="UserValidationModalEmpty" src="https://user-images.githubusercontent.com/120486/178774038-20aea814-e969-42e7-9ede-f0cb70336905.png"> | <img width="1440" alt="UserValidationModalNumber" src="https://user-images.githubusercontent.com/120486/178774129-68c02770-2125-4ed4-97b5-62cc73a53fa1.png"> | <img width="1440" alt="UserValidationModalInvalidNumber" src="https://user-images.githubusercontent.com/120486/178774211-fba221c2-1d05-468f-b52c-7c14509de6ed.png"> |

| Verification (Sent) | Verification (Resent) | Verification (Input) | Verification (Invalid Input) |
|-|-|-|-|
| <img width="1440" alt="UserValidationModalVerificationSent" src="https://user-images.githubusercontent.com/120486/178774337-e2499d3d-9a2b-49ed-b46d-0f4bbeca4a39.png"> | <img width="1440" alt="UserValidationModalVerificationResent" src="https://user-images.githubusercontent.com/120486/178774346-f435d5fd-67cb-48dc-8fb7-4eb3d58a4322.png"> | <img width="1440" alt="UserValidationModalVerificationEnter" src="https://user-images.githubusercontent.com/120486/178774369-305c314a-9572-4a60-bf2c-e47241b9ffc3.png"> | <img width="1440" alt="UserValidationModalVerificationEnter-1" src="https://user-images.githubusercontent.com/120486/178774423-c6100e5a-cb52-40d3-a4bb-02be145a1314.png"> |

| Verification (Progress) |
|-|
| <img width="1440" alt="UserValidationModalVerificationInProgress" src="https://user-images.githubusercontent.com/120486/178774627-8e8b8c07-bcc1-4b87-b461-3a229f1071d3.png"> |

| Validation Required Alert |
|-|
| <img width="1440" alt="UserValidationAlert" src="https://user-images.githubusercontent.com/120486/178774693-77320ba3-9c35-4fb8-ba32-da846f47c293.png"> |

See [design specs](https://www.figma.com/file/jorFpdvydV22oRc0YqKWGo/Add-phone-verification-for-new-users-%2311339?node-id=1142%3A4869).

**Comment by atduarte** [comment]
Phone number verification example from Kaggle: https://www.loom.com/share/0e7d8b3bf7d2422aa6770ca37089d349

**Comment by jldec** [comment]
Reopened - tracking PR #12258

**Comment by tiudvek** [comment]
this is why i left gitpod.

**Comment by crcdng** [comment]
Currently there is a modal pop-pup without data protection note, no explanation how you use the phone number, no opt out, no link to a data protection statement - all of which appears to be in violation of GDPR. In doubt, check with your data protection officer.

<img width="934" alt="Screenshot 2022-09-12 at 10 47 45" src="https://user-images.githubusercontent.com/830492/189612407-69d4214a-8de4-4c20-a478-b3153c7c615b.png">

**Comment by ultracodez** [comment]
> this is why i left gitpod.

And how does this add to the conversation?

**Comment by axonasif** [comment]
Hi @tomlowenthal, thank you for sharing feedback. You can subscribe to https://github.com/gitpod-io/gitpod/issues/17583

**Comment by Semechka-ik** [comment]
It seems like you are experiencing issues with authorization. When you enter the code "6", the "Validate Account" button remains inactive. However, if you enter "66666", the "Validate Account" button becomes active.

**Comment by Favourrufus1** [comment]
Hey I'm trying to create an account on gutpod ,but I was asked to use a phone verification code but it just says a random no )like 1 or 6 and tells me I'm not responding and it offs and I've tried it s veral tes what do I do

**Comment by 1tbfree** [comment]
I do not have a phone number could you please remove that?

**Comment by axonasif** [comment]
@1tbfree sorry, we can't

**Comment by banchester1** [comment]
How to fix following Error: Phone calls not allowed to the given number?

**Comment by shimaarabeen** [comment]
> How to fix following Error: Phone calls not allowed to the given number?

Did you find a solution?
