### ISSUE TITLE
[Java] Rename class copies class and renames the wrong one

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#1133]
**Describe the bug**
When I rename a class A to B, then its file A.java is copied and the class in this file is renamed to B while the original file is renamed to B.java and now contains a class A. 

**To Reproduce**
* Open a Java class file
* select the class name and press F2
* rename the class and press enter

**Expected behavior**
The file containing the class should not be copied, but be renamed according to the class renaming

**Additional Information**
-

**Comment by svenefftinge** [comment]
TODO: Check if this is the same in VS Code. If so move ticket to Java VS Code extension.

**Comment by akosyakov** [comment]
Partial fix will be deployed next week, please see https://github.com/eclipse-theia/theia/issues/7054#issuecomment-587389681 for details.

**Comment by Sandared** [comment]
Awesome :) Thank you!

**Comment by akosyakov** [comment]
@Sandared please try again, how does it work for you now?

**Comment by Sandared** [comment]
Hey @akosyakov it works now! Thank you! 
The only thing that's odd is every time I change it I get such a notification:
`Do you want to overwrite the changes made to 'backend/rest/impl/src/main/java/io/qbilon/backend/rest/impl/ClassABC.java' on the file system?`

Is this intended? If so, can I turn this off?

**Comment by akosyakov** [comment]
> Is this intended? If so, can I turn this off?

Not, that's why I said it fixed partially. Unfortunately i did not have enough time to figure out why java LS ignoring some dirty buffers which we sent after the rename.
