### ISSUE TITLE
Get requirements for meta/IDE nodes

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#11344]
Establish requirements for the meta/IDE nodes from the @gitpod-io/engineering-webapp and @gitpod-io/engineering-ide teams in the same way we have requirements for Workspace nodes (4vCPU/16GB RAM).

In lieu of any firm requirements, suggest 2vCPU and 4GB RAM

/cc @gitpod-io/platform

**Comment by geropl** [comment]
@MrSimonEmms I wonder what kind of installation we're targeting here in terms of reference architecture. If we go for "Single Cluster Production Ready" that says 8vCPU/32GB RAM. I feel this is a tad too high, though, as we scale horizontally anyway. 4vCPUI/16GB looks way more reasonable.

Technically 2vCPU/4G would certainly work for Gitpod, and if we're looking to establish a hard boundary, that could be one. But I'd rather push people to 4vCPU/16GB or higher, and find that limit somewhere within the ref-arch framework. :lotus_position:

**Comment by MrSimonEmms** [comment]
Is that for the `meta` nodes? I know we need that for the `workspace` nodes because of all the stuff they're doing with image building, but I had the feeling that the `meta` nodes didn't need to be as high

**Comment by geropl** [comment]
RAM is plenty, but CPU is weak. 2vCPUs is basically nothing, if you mix kubernetes, network virtualization overhead and not super performant runtime with a reasonable traffic. Even streaming workspace logs, for instance, tends to get CPU bound faster then you think.

As in: might work for singular users, but we should not recommend that for teams that are looking for the Gitpod experience (TM).
So, again? Are these hard boundaries? Or recommendations? And if we pick one: Where do we put them in the ref-arch framework? :shrug:

**Comment by MrSimonEmms** [comment]
This is more a test of "will it work" rather than "will it work well"? It's for the KOTS preflight checks where we can alert if they don't have a power enough node.

I'm perfectly happy to put as 4vCPU/16GB RAM - that's the setting for `workspace` nodes anyway

Also, I like "the Gitpod experience (TM)"

**Comment by geropl** [comment]
> I'm perfectly happy to put as 4vCPU/16GB RAM - that's the setting for workspace nodes anyway

:100: Good, let's do that for now. I will see to update the ref arch to that value as well. I see no point in requiring 8cores as long as we scale. :+1:

**Comment by MrSimonEmms** [comment]
Thanks for your help @geropl 🎉
