### ISSUE TITLE
Website won't let me log in with GitHub at all

### ISSUE THREAD

**Issue by kimya18** [gitpod-io/gitpod#1134]
Keeps saying

 Sorry, something went wrong 😓
Login with GitHub failed. Please try again.

**Comment by jankeromnes** [comment]
Hi @kimya18, sorry about this issue.

Sometimes it can happen that GitHub is too busy and drops our authentication requests, but usually this is pretty rare and also resolves itself quickly.

Could you please try again? I think it should work now. (If it doesn't, we'll take a look at our server logs to see if there is any deeper problem there.)
