### ISSUE TITLE
More selective control of prebuilds by commit or PR

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#11352]
On large projects, prebuild usage can become overwhelming e.g. when there is automation to merge changes into a large number of branches, many of which are unlikely to be opened as workspaces.

Gitpod already supports some configuration to limit prebuilds on GitHub repositories. For more details see https://www.gitpod.io/docs/prebuilds#github-specific-configuration

This issue proposes 2 additional ways to prevent prebuilds using a `[no prebuild]` pattern
When the pattern is detected in either of these places, no prebuild will be triggered.

1. on specific commits with a pattern in the commit message
2. on specific PRs with a pattern in the PR name or description

Subsequent workspaces opened on a context which is missing a prebuild as a result of this pattern will behave just like today, and run the prebuild tasks during workspace startup.

---

Similar examples from CI providers:

- https://docs.semaphoreci.com/essentials/skip-building-some-commits-with-ci-skip/
- https://plavc.github.io/jenkins-scmskip-plugin/
- https://docs.gitlab.com/ee/user/project/push_options.html
- https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

**Comment by ahukkanen** [comment]
Yes please! This would be highly useful to save some resources.

What I was also thinking, maybe there could be a configuration option to define excluded branch patterns, such as `exclude_branches: "backport/**"` which would disable the prebuilds for branches matching that pattern.

Another option I was thinking is that if the PR has a specific label defined for it, such as `backport`, it would be excluded from the backports.
