### ISSUE TITLE
Support pvc workspace classes

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#11357]
## Is your feature request related to a problem? Please describe
We need to test pvc for workspace backups without having impact on workspaces that are still doing backup with gcp object storage.

## Describe the behaviour you'd like
Define an internal workspace classes that are only available to gitpodders, that ensure that workspaces are started with pvc and are scheduled to different nodes.

**Comment by utam0k** [comment]
Who is working on this issue? I think @Furisto?

**Comment by kylos101** [comment]
@Furisto can you link the draft PRs to this issue? 🙏

**Comment by kylos101** [comment]
@Furisto moving to in-progress, as you have two open PRs for this already 🙏

**Comment by kylos101** [comment]
@sagor999 for 👀
