### ISSUE TITLE
Init command for Java/Maven projects could be improved

### ISSUE THREAD

**Issue by mthmulders** [gitpod-io/gitpod#11368]
### Bug description

It seems that for Java projects, the default generated `.gitpod.yml` file has an `init` of `mvn install -DskipTests=false`.

As far as I'm concerned, there are two issues with this:

1. It encourages people to skip running tests.
2. It installs the project artifact(s) in the local repository.

### Steps to reproduce

Generate a `.gitpod.yml` file for any GitHub project that uses Apache Maven.

### Expected behavior

I would propose to change the `init` to `mvn verify`. This will cause less pollution to the storage, as it no longer copies the project artifact(s) in the local repository. In a properly setup project, this should not be necessary. And it verifies that the user is working in a "clean" environment with all tests green.

### Example repository

I ran into this when my colleague @tomcools showed me Gitpod on [one of his repositories](https://github.com/TomCools/rickroll-security-spring-boot-starter). I [suggested to change it](https://github.com/TomCools/rickroll-security-spring-boot-starter/pull/4), and he said it's the default that got generated.

**Comment by mthmulders** [comment]
Rather than ignoring the issue for three months and then announcing to close it, would it be possible to actually give a meaningful reaction to my question/report?

**Comment by TomCools** [comment]
Let's go to the Gitpod booth at Devoxx? :-)

**Comment by Thomas-Gitpod** [comment]
@jacobparis

**Comment by mthmulders** [comment]
@thomas-gitpod @jacobparis Any news on this? This is the second time Stalebot comes by, threatening to close this issue...
