### ISSUE TITLE
react app not working

### ISSUE THREAD

**Issue by xodia117** [gitpod-io/gitpod#11375]
### Bug description

Trying to npm start my react app and it will not load in browser or preview.

### Steps to reproduce

cd my-app
npm start

brower freezes or preview freezes whole gitpod.

**Comment by pawlean** [comment]
Can you share your repo with us @xodia117?

**Comment by xodia117** [comment]
@pawlean Managed to sort the issue, turns out I had a minor syntax error which caused the crash

**Comment by pawlean** [comment]
Good to know! Thanks @xodia117, will close this issue. ✨
