### ISSUE TITLE
Investigate ways to not require adding custom cert to browser

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#11379]

**Comment by MrPeacockNLB** [comment]
Hi,

you can use https://traefik.me/ to get valid LE certs to be used with a reverse proxy in front e.g. NginX or Traefik to terminate wiht TLS. You can download https://traefik.me/cert.pem and https://traefik.me/fullchain.pem from there site.

https://gitpod.treafik.me will resolve to 127.0.0.1

```
nslookup gitpod.traefik.me
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   gitpod.traefik.me
Address: 127.0.0.1
```
