### ISSUE TITLE
rustlang: Support formatting of popups

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1139]
GitPod doesn't seem to process the popups formatting correctly:
![image](https://user-images.githubusercontent.com/11302521/73087489-da047180-3ed2-11ea-996e-416602b54eff.png)

I assume that this should be formatted alike:

expected identifier, found `"fibonnaci-kreyren"`

**Comment by JesterOrNot** [comment]
This is likley an issue with the extension, also, as far as I know that is not how you do things in rust try
```rust
use fibonnaci-kreyren;
```
instead of a string literal

**Comment by JesterOrNot** [comment]
@akosyakov Can you take a look at this?

**Comment by Kreyren** [comment]
> instead of a string literal -- @JesterOrNot 

That is a syntax error made to present this issue i am aware of it breaking the build.

**Comment by Kreyren** [comment]
This seems to be resolved now:
![image](https://user-images.githubusercontent.com/11302521/74466983-8fa25f00-4e98-11ea-8008-4b83a272ca5c.png)
