### ISSUE TITLE
[ws-manager-bridge] the number of workspace instances remaining seems to be wrong

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#11399]
### Bug description

We wanted to delete the us53 cluster, the number of workspace pod is empty, so we triggered the werft job to delete the us53 cluster. But somehow, the ws-manager-bridge reported the number of running instances is 2.

```console
Updated property [core/project].
downloading sha256:c479b2288f1e17ae558d565dcd1d686765cf4b9c310a5c85d2bbcdc644074b91  100% || (21/21 MB, 51.481 MB/s)
Switched to context "us53".
🚀 Retrieving governing meta cluster prod-meta-us02 kubeconfig
Fetching cluster endpoint and auth data.
kubeconfig entry generated for prod-meta-us02.
🚀 Changing kubectx to prod-meta-us02
Switched to context "gke_gitpod-191109_us-west1_prod-meta-us02".
Context "gke_gitpod-191109_us-west1_prod-meta-us02" modified.
Active namespace is "default".
🚀 Deregistering cluster us53
time="2022-07-14T20:35:29Z" level=fatal msg="rpc error: code = Unknown desc = cluster is not empty (2 instances remaining)"
```

After that, we check the DB according to the code logic
- https://github.com/gitpod-io/gitpod/blob/c752a16b46dcccd9446ada11add5cfc3213a30d4/components/ws-manager-bridge/src/cluster-service-server.ts#L263
- https://github.com/gitpod-io/gitpod/blob/c752a16b46dcccd9446ada11add5cfc3213a30d4/components/gitpod-db/src/typeorm/workspace-db-impl.ts#L450-L485

The number of workspace according to the criteria using SQL query is 10, rather than 2.

We are not sure is it the bug of ws-manager-bridge _or_ we input the wrong query parameters.

### Steps to reproduce

[Internal slack thread](https://gitpod.slack.com/archives/C02F19UUW6S/p1657831120699349).

**Comment by geropl** [comment]
@jenting Could you elaborate on what the actual problem is here? The fact that we're querying the DB when deregistering the cluster? Or that you feel the numbers aren't correct? If it's the latter: What was the number you expected to see? E.g. in the cluster/by asking ws-manager?

**Comment by jenting** [comment]
> @jenting Could you elaborate on what the actual problem is here? The fact that we're querying the DB when deregistering the cluster? Or that you feel the numbers aren't correct? If it's the latter: What was the number you expected to see? E.g. in the cluster/by asking ws-manager?

Well, the problem is that we run the werft job `workspace-cluster-delete` to tear down the cluster, and it displays the 2 instances are still running. However, after running the SQL query command to the production DB directly, it displays that 10 workspace works are in a stopping _or_ stopped state.

We are not sure whether the problem is the code bug _or_ we query the wrong SQL command to the production DB. You could check the https://gitpod.slack.com/archives/C02F19UUW6S/p1657831120699349 thread to see the SQL command we queried. Thank you.

**Comment by kylos101** [comment]
@geropl both, it seems wrong to query the database (but I may be missing historical context as to why we do that), and the numbers aren't correct. 

Here is an example for `us58`:

```shell
# see how there are zero workspaces in the cluster?
gitpod /workspace/gitpod (main) $ kubectl get pods
NAME                                 READY   STATUS    RESTARTS       AGE
agent-smith-49rd2                    2/2     Running   0              2d3h
agent-smith-ccplz                    2/2     Running   0              3d14h
agent-smith-gsbpp                    2/2     Running   0              3d18h
agent-smith-n7m9s                    2/2     Running   0              2d3h
agent-smith-nr9zg                    2/2     Running   0              5d21h
image-builder-mk3-65f487c8c5-p6fw8   2/2     Running   0              6d
registry-facade-2nlbt                3/3     Running   0              3d14h
registry-facade-9fqnh                3/3     Running   0              3d18h
registry-facade-f9xct                3/3     Running   0              2d3h
registry-facade-r5578                3/3     Running   1 (5d8h ago)   5d22h
registry-facade-wwg7n                3/3     Running   0              2d3h
ws-daemon-5rcpt                      3/3     Running   0              3d18h
ws-daemon-9gjsx                      3/3     Running   0              2d3h
ws-daemon-g2lsz                      3/3     Running   0              3d14h
ws-daemon-kv22v                      3/3     Running   0              5d22h
ws-daemon-pvrx8                      3/3     Running   0              2d3h
ws-manager-84bb5cffd6-6pq5h          2/2     Running   0              2d7h
ws-proxy-c4cb5d5cf-77m27             2/2     Running   0              6d
ws-proxy-c4cb5d5cf-89lnl             2/2     Running   0              6d
ws-proxy-c4cb5d5cf-rp469             2/2     Running   0              6d
```

In [this job](https://werft.gitpod-io-dev.com/job/ops-workspace-cluster-delete-main.233/raw), we get: `time="2022-08-04T21:21:49Z" level=fatal msg="rpc error: code = Unknown desc = cluster is not empty (14 instances remaining)"`.

It looks like the workspaces that are being counted in this case are the `pending` ones, which I think means they didn't necessarily land on a workspace cluster, such as [this one](https://gitpod.io/admin/workspaces/gitpodio-templatepython-v9snnjcma0x).

The query that would have rendered this I think looks similar to:
```sql
SELECT dbwi.id, dbwi.phasePersisted, dbw.id, dbwi.deleted 
FROM gitpod.d_b_workspace dbw  
inner join gitpod.d_b_workspace_instance dbwi 
on dbw.id = dbwi.workspaceId  
WHERE 
dbwi.phasePersisted not in ('stopped')
and dbwi.deleted = 0
# change to match a region you're interested in
and dbwi.region = 'us58'
ORDER by 2 asc
;```

Which yields 14 pending workspaces plus 39 stopping workspaces = 53 in total.

```bash
05bb0a45-a6ff-46e2-9001-ee6686f00b24	pending
237c28fc-93cf-4040-bd5e-b1474f921bfa	pending
3ba75899-2d09-4bc9-b242-2582e24e5fa3	pending
457957db-01fc-4b3f-b3fb-cb76066b011d	pending
524b3d97-9b1b-4cc0-af80-82a8ef21a13a	pending
5ec47396-e0db-4d6f-8cbb-8d76d80dc634	pending
683ad836-3763-455c-9924-78aa40dfbc73	pending
6f925daf-3234-46b7-bf1c-d73d0b337d42	pending
7ea87b1a-78bf-4972-aa98-7388053dae03	pending
824103f9-2a95-412a-afc0-f755c0eba6f6	pending
c2ea0add-f401-4ceb-813f-45d46887c20c	pending
eb43d308-49cd-4311-ac1a-c3369ba8aca9	pending
ecfe5d14-3ce4-4477-a2a8-2fd09acd23dc	pending
fdec6ee9-73a1-4104-9490-a9de771db03f	pending
00a166eb-4a8f-451e-87ff-8942787d47f7	stopping
00d01460-d6a3-4bfa-9ef3-6a9da965be9a	stopping
0845b9f7-03da-483e-a488-a29533d7e905	stopping
08795675-d1ed-4b37-ad71-18a5711f6820	stopping
088bcfdb-0983-4202-93cf-ad40254a033a	stopping
1415d706-3cb2-4fd2-9865-c52a0c418665	stopping
1673ef52-b6b7-4860-a186-9c4ced43fe30	stopping
1eb9c665-73cf-4c6d-a2aa-d9d5eb2c5755	stopping
21a38c96-682a-40cf-babe-367750ab89fd	stopping
25a1d59e-d065-46f4-af12-a50b9de3a7b0	stopping
3ea722e7-7770-4a60-b890-66f74a0fefef	stopping
40e79c64-2ea1-4d07-be79-e145d5aaf9c7	stopping
468aeb00-85da-463f-b3ed-3a9f92015027	stopping
49a1013a-2c19-426d-a33c-b4fedbcb2c30	stopping
558f816c-80ab-411c-852d-352d2ff55fdb	stopping
5b6c1ffc-7770-44b9-a42a-17c13de67907	stopping
5fe85b12-4002-494d-b1ec-34a9d6595cbd	stopping
69d74cc3-048c-4fe8-87ed-badbc8c9ff5c	stopping
6f88653f-0406-4de9-89e6-7e475de7eb05	stopping
7086ffb8-9e91-4631-8fa3-c6816c337ffa	stopping
786f289b-43e1-4ab8-bead-96a941a346d4	stopping
8b0336bc-f6f0-4e6f-812a-89671cbf754b	stopping
96c156a5-eaa6-4538-b5dd-ed4f33b320f7	stopping
99053f27-9af0-4a85-b135-e0d061d9f67d	stopping
a027754e-9275-49ad-996b-7b53dfe922ed	stopping
a2f7376e-46ea-4262-a3ba-3740cd8ad50b	stopping
a6642e66-b983-4a65-9b31-a0023008da9c	stopping
aaf7b2d2-7f74-4341-9629-8c6f8fc78495	stopping
b28a0c8a-3c4b-472d-80ca-e4129c676b9d	stopping
b618272c-31e6-4fb4-8cef-1d3eaf2f1f11	stopping
b8fd5342-59bf-4d47-a77c-34bef3ec5522	stopping
ba164f69-f532-4fa7-a517-abfe6ba6dcee	stopping
bb0c963f-1337-4646-b328-488b6eaba0d1	stopping
c15c8fc0-1500-42af-857b-274769921f9d	stopping
c63a3e6c-28c4-407b-a370-44171437fd60	stopping
c7cd4cf0-3875-415a-9c36-848f35694b4d	stopping
cac60a06-63a8-4776-8a66-fd8a3eadc52a	stopping
f738649e-b166-4278-adf2-eb4e0bebf7a4	stopping
fca9ab28-00df-4212-b55d-ec89b67388b4	stopping
```

We've been having phase management problems lately, I imagine this is a symptom. I would have expected there to be zero (because of what I saw in the workspace cluster), but would have expected `ws-manager-bridge` to return 53 workspaces, not 14. Ideally `ws-manager-bridge` would have returned zero, matching the workspace cluster...but that is a separate problem.

**Comment by kylos101** [comment]
@geropl I think this may be related https://github.com/gitpod-io/gitpod/issues/11397
