### ISSUE TITLE
Setup and implement API to enforce limits (Paywall backend)

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#11403]
On StartWorkspace, check if a limit has been hit, and notify the client.

**Comment by AlexTugarev** [comment]
This issue reads like a repetition of 1.) from https://github.com/gitpod-io/gitpod/issues/11403 
@geropl, what should be done in here exactly?

**Comment by geropl** [comment]
@AlexTugarev Kind of, but more about the wrapping and communicating the signal to frontend. :+1:
