### ISSUE TITLE
"Spending Limit" UI + storage

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#11401]
Each CostCenter (e.g., an individual user or a team) can configure a spending limit as discussed in the ["Usage Based Pricing" RFC](https://www.notion.so/gitpod/RFC-Usage-Based-Pricing-133f8018a64344bb93dd9a65d82a9c6a#a22576b7b77646fd9ea0a08ac475de8b).
Here's a link to [the user story](https://www.notion.so/gitpod/Usage-Based-Pricing-User-Stories-0fc4ac2f2413449b95d70feb60177aaf#b9f6d7889ec14b3a86671ce123864236) which already include figmas. :sparkles: 

The focus is primarily "Teams", but there should be an opportunity to reuse a big chunk of this for users. :upside_down_face:

**Comment by AlexTugarev** [comment]
Created another issue for UI refinements as a follow-up. 
https://github.com/gitpod-io/gitpod/issues/11575
