### ISSUE TITLE
Paywall + Notification UI

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#11404]
When users hit their configured [Spending Limit](https://github.com/gitpod-io/gitpod/issues/11401) (implemented in #11403) they:
 1. need to be shown on StartWorkspace about their current state and shown options how to unblock them: [user story](https://www.notion.so/gitpod/Usage-Based-Pricing-User-Stories-0fc4ac2f2413449b95d70feb60177aaf#e4ae9ada8d714ee5bc1b3d52d3a5d978).
 2. they should be notified on the dashboard (alert component?): [user story](https://www.notion.so/gitpod/Usage-Based-Pricing-User-Stories-0fc4ac2f2413449b95d70feb60177aaf#bd4ee25f830b478f82fd1faf4dd3ffc7)

**Comment by AlexTugarev** [comment]
Hi @gtsiolis! Could we reuse the toast notifications from https://github.com/gitpod-io/gitpod/issues/3530 for the second part of this? WDYT?

**Comment by gtsiolis** [comment]
Posting for visibility after discussing with @AlexTugarev and @jldec, we're going to:
1. Surface a modal blocking workspace start when spending limit is reached
2. Possibly allow switching back usage attribution to user's personal account credits.
3. Link to billing when usage credits have been used.

Later on, we could ad-hoc allow resolving the issue for individuals users by allowing them to add a credit card on the fly to enable billing and continue with the workspace start. 💡

**Comment by easyCZ** [comment]
I've assigned this to you @AlexTugarev as I believe you've been focusing on this. Please un-assign if this is incorrect.
