### ISSUE TITLE
Show ssh connection command from `gp`

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#11415]
Allow the user to get the SSH string from `gp`

The same as: https://github.com/gitpod-io/gitpod/issues/9230 but for `gp cli`, not VS Code.

**Comment by filiptronicek** [comment]
I'm voting for using `gp ssh` 👀

**Comment by filiptronicek** [comment]
The PR for this is now raised @ #17998. Some ideas for the future of the command:
- easier connections with alternate authentication which is easier than setting up SSH keys
- command to open your local terminal directly without any copy-pasting utilizing [`ssh://`](https://serverfault.com/questions/974307/how-can-i-create-an-ssh-protocol-link-from-my-browser-which-will-use-a-jump-host/974330#974330?newreg=bd24995907544342b2d37b9390b3db0f)
