### ISSUE TITLE
Unknown branch-name prefix

### ISSUE THREAD

**Issue by pyx900** [gitpod-io/gitpod#11422]
### Bug description

Relates
- #5683

Currently, my user-name prefix on the branch names was quite long. So I shortened my name in
   - GitHub user name
   - GitPod user name

Yet, the branch names continues to be my long old user name. So where is the long name coming from ?

How do I reset this to use the newer short name ?

### Steps to reproduce

1. rename your user name
2. observe to see if contextual workspace created carries the new name as prefix
3. It doesn't (for me)

### Expected behavior

The new branch names should use the current shortened user name

**Comment by geropl** [comment]
@pyx900 As a workaround you should be able to log out and login again to update that name. If that does not work, please open a separate bug report.

The parts about branch names I'd like to close in favor of #5683. 👍
