### ISSUE TITLE
"Share workspace snapshot" hangs when limit of 3 snapshots/backups is reached

### ISSUE THREAD

**Issue by nemanjam** [gitpod-io/gitpod#11423]
### Bug description

Last two days I am unable to create workspace snapshot, popup just hangs for ever.

After investigation, @jimmybrancaccio figured out that it's related with the limit of 3 snapshots per workspace (which include workspace backups).

### Steps to reproduce

Open workspace and select `Share workspace snapshot`.

### Workspace affected

https://nemanjam-nextjsprismabo-h4e9fmpo6a5.ws-eu54.gitpod.io/

### Expected behavior

It should generate workspace snapshot successfully after few seconds.

### Example repository

Its workspace made from this repository:

https://github.com/nemanjam/nextjs-prisma-boilerplate

### Anything else?

Two days ago it worked fine, I wanted to make snapshot that includes latest changes but it just hangs for ever.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ovd6)

**Comment by jimmybrancaccio** [comment]
I've gotten at least 2 support tickets about this issue over the last few days. When investigating today I determined there appears to be a limit of 3 snapshots per workspace. I am not sure if this is something new we've implemented but it is causing issues for customers in turn tickets for support.

**Comment by atduarte** [comment]
@jimmybrancaccio I’m not entirely sure both issues (limit of 3 and hanging) are 100% related. Does it hang for you after the 3?

@nemanjam does this happen in all workspaces? Even if you start a new one?

**Comment by jimmybrancaccio** [comment]
@atduarte Yes, I just tested on a test workspace I have on SaaS. I actually thought it was an issue with `strace` but after looking in Google logs I found the error about hitting the maximum snapshots.

I forgot to leave a link to the [Google logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-07-17T12:54:15Z;query=%225f1ec7cb-ad26-4e1e-98f5-55a494c166e9%22%0Atimestamp%3D%222022-07-17T12:54:15Z%22%0AinsertId%3D%22kdle6glgltsoswfa%22;timeRange=2022-07-17T05:00:00.000Z%2F2022-07-18T04:59:59.999Z?project=workspace-clusters) for @nemanjam workspace because I did look it up for his workspace as well and sure enough I saw that workspace hit the snapshot limit too.

**Comment by TakehideSoh** [comment]
I am one also encountering his issue. 

```
I am not sure if this is something new we've implemented but it is causing issues for customers in turn tickets for support.
```
From 2020

**Comment by JohnPirog-Array** [comment]
What does this mean - when a limit of 3 snapshots is reached? I have three separate snapshots submitted to me that hang when I try to open them. I cleared out all my workspaces and deleted all inactive workspaces but still get this error trying to open the three snapshots that were submitted to me.

**Comment by JohnPirog-Array** [comment]
This is the message in the Javascript console when it hangs with the "Initializing content..." message:

Failed to load resource: the server responded with a status of 502 () - https://bronze-partridge-t2fimfvyv5e.ws-us54.gitpod.io/_supervisor/v1/status/supervisor

**Comment by nemanjam** [comment]
Is this fixed? A lot of time passed.

**Comment by aledbf** [comment]
Closing. This was fixed in https://github.com/gitpod-io/gitpod/pull/11807 and was deployed in gen60.
