### ISSUE TITLE
vlang: Gitpod is unable to compile vlang

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1143]
Vlang doesn't seem to be supported on gitpod:
```console
gitpod /workspace/hello-benchmark $ v --help
bash: v: command not found
```

**Comment by Kreyren** [comment]
update: Using following dockerimage

```Dockerimage
FROM gitpod/workspace-full-vnc:latest

## VLANG ##
USER root
ENV VLANG_SOURCE="/opt/vlang"
RUN git clone https://github.com/vlang/v "$VLANG_SOURCE" || exit 1
RUN make -C "$VLANG_SOURCE" || exit 1
RUN "$VLANG_SOURCE/v" symlink || exit 1
RUN unset VLANG_SOURCE
```

Results in

```
gitpod /workspace/gitpod-vlang-init $ v
V panic: V tool "/opt/vlang/tools/vrepl.v" could not be compiled
denied
collect2: error: ld returned 1 exit statusV error: C error. This should never happen. 
Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose
addr2line: 'v': No such file
v(+0x3b67) [0x564a5900eb67]
addr2line: 'v': No such file
v(+0x97d5d) [0x564a590a2d5d]
addr2line: 'v': No such file
v(+0x98380) [0x564a590a3380]
addr2line: 'v': No such file
v(+0x9ad62) [0x564a590a5d62]
                                               | 0x7f3345fc5b6b | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) 
addr2line: 'v': No such file
v(+0x24ba) [0x564a5900d4ba]
```

Apparently `sudo` is required.

Test environment: https://gitpod.io/#https://github.com/Kreyren/gitpod-vlang-init/tree/94bc4091fc7ea5d6c62be8c68a182732bad48dbd

**Comment by JesterOrNot** [comment]
Please see https://github.com/JesterOrNot/Gitpod-V

**Comment by Kreyren** [comment]
@JesterOrNot eh o.o Should i close https://github.com/gitpod-io/workspace-images/pull/153 if you are already working on it?

I guess your way is better for stable release management and using new bin dir in PATH is more robust.

**Comment by JesterOrNot** [comment]
V (as cool as it seems) probably isn't stable enough to add to an official docker image.

**Comment by Kreyren** [comment]
> V (as cool as it seems) probably isn't stable enough 

Referencing https://github.com/vlang/v/issues/3567 -> Until the memory leak is resolved i agree that it is not suitable for version controlled product like gitpod.. I would suggest this for rolling-release though.

**Comment by JesterOrNot** [comment]
See

```Dockerfile
FROM gitpod/workspace-full

USER gitpod

WORKDIR /opt/vlang

RUN sudo wget -c https://github.com/vlang/v/releases/download/0.1.24/v_linux.zip \
    && sudo unzip v_linux.zip \
    && sudo chown -hR gitpod /opt

ENV PATH=/opt/vlang:$PATH
```

Full example repo [here](https://github.com/JesterOrNot/Gitpod-V)

**Comment by Kreyren** [comment]
psa: memory leak is apparently expected to be resolved in the near future see https://github.com/vlang/v/issues/3972#issuecomment-596239985

with proper tracking for critical bugs making is usable for production?

@JesterOrNot Is that sufficient solution for Gitpod ?

**Comment by JesterOrNot** [comment]
Try it out I haven gotten everything worked out yet but it should be ok for compiling

**Comment by Kreyren** [comment]
Mine implementation also seems to work, see https://github.com/gitpod-io/workspace-images/pull/153

> Try it out I haven gotten everything worked out yet but it should be ok for compiling

Can't check atm (i don't have a timeframe for it)
