### ISSUE TITLE
Remove a user extension

### ISSUE THREAD

**Issue by 201flaviosilva** [gitpod-io/gitpod#11442]
### Bug description

I've installed some extensions that I don't want to use any more and I try to remove them, but whenever I open a new workspace, the extensions that I supposedly removed already show up installed again.
Video example:

https://user-images.githubusercontent.com/55815265/179515679-d4044335-88cd-4b17-bb02-56f69f76801d.mov

### Steps to reproduce

I'm not sure how to reproduce this problem, but basically, what I did was:
- Installed some extensions.
- After some time (days/weeks) I opened a project and removed the extensions.
- I close the project.
- I open a new one and the extensions are there again.

(I don't have the extensions in `gitpod.yml`)

### Expected behavior

I hope that when you remove an extension, it doesn't reappear in the new project

### Example repository

nop

### Anything else?

Discord discussion: https://discord.com/channels/816244985187008514/816246578594840586/997843134916599848

(Sorry, my bad English)

**Comment by jeanp413** [comment]
@201flaviosilva from the video you are restarting a workspace so the extensions appear as installed at the beginning as they're already on disk but if you wait a few seconds it until settings sync kicks in it should uninstalled them automatically, let me know if that doesn't work

**Comment by 201flaviosilva** [comment]
Hey, thanks for replying, but that's just a demo video, because I already deleted those extensions a week ago, but they keep reappearing :)

(I recorded the video yesterday +/-)

**Comment by 201flaviosilva** [comment]
OK, I think I finally solved, I need to right-click at the extension and click "do not sync" 😅

**Comment by jeanp413** [comment]
@201flaviosilva indeed all extensions installed manually through the vscode UI will be sync by default, if you want to install some extension that's only scoped to a repository and does not sync you can do so by configuring it in your `.gitpod.yml`, [see docs](https://www.gitpod.io/docs/ides-and-editors/vscode-extensions#installing-an-extension)

**Comment by 201flaviosilva** [comment]
Yap, I already found that. My problem was that I was not able to remove it, but I already solved it, thanks anyway :)
