### ISSUE TITLE
Self-hosted (latest) + VSCode Gitpod 0.0.40+

### ISSUE THREAD

**Issue by scheibling** [gitpod-io/gitpod#11440]
### Bug description

When updating the VSCode-plugin (Release) past 0.0.40, the below error is thrown when trying to sign in to a self-hosted (free tier) Gitpod instance. Gitpod.io still works.

Might be related to 

```json
{
    "status": 400,
    "message": "The requested scope is invalid, unknown, or malformed: Check the `function:getSSHPublicKeys, function:sendHeartBeat` scope(s)"
}
```

### Steps to reproduce

- Upgrade vscode plugin to 0.0.41 or 0.0.42
- Start a workspace from the web interface
- Choose "Open in VSCode" or "Open in VSCode insiders"

### Expected behavior

-

### Example repository

Not repository-specific, same error for any workspace (old or newly created).

### Anything else?

- Tried with the 2022.04.1.2, 2022.06.0.10 and 2022.06.1.7-releases of Gitpod (installed w/ gitpod-installer due to some additional configuration needed for deployment in our cluster). 
- The 0.0.40-plugin works as previously, with either false or true on "gitpod.remote.useLocalApp", 0.0.41+ works with neither. 
- Signing in with Gitpod for the settings sync (while not connected to a workspace) still works with the newer plugin, but can't connect to a workspace due to the authentication error.

**Comment by jeanp413** [comment]
Released version `0.0.43` fixing this so it's backwards compatible
