### ISSUE TITLE
[Self-Hosted] Guidance on workspace resource limits for Reference Architectures.

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#11449]
## Is your feature request related to a problem? Please describe
Currently we do not give guidence on setting limits for workspace sizes - we only set a default request (which is [here](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/config/v1/config.go#L60-L61) afiak).

## Describe the behaviour you'd like
In order to avoid any future complexities around this, we should more clearly set a default limit in the reference architectures, explain the impact of this and how to change it, and also explain what impact it has on the number of workspaces per node (in combination with the request set). This should be implemented for all existing reference architectures.

## Describe alternatives you've considered
- Do nothing - which will likely result in a bad experience over time

## Additional context
- this is a follow up for a [comment](https://github.com/gitpod-io/website/pull/2324#issuecomment-1186624321) raised in this [PR](https://github.com/gitpod-io/website/pull/2324)
- This relates to #10805 , where we are likely to create a better UX for setting workspace sizes. 
-  Internal [discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1658143693570059)

**Comment by aledbf** [comment]
> Currently we do not give guidence on setting limits for workspace sizes

This should be implemented in the current alpha, not even in beta. Delaying this until alpha means customers in production are exposed to node issues (loss of nodes and content), bad performance, and noisy neighbors.

ping @csweichel
