### ISSUE TITLE
vlang: Linting of vlang is not supported on gitpod

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1144]
Gitpod doesn't seem to support Vlang linting

Notice syntax error in `main.v`:
![image](https://user-images.githubusercontent.com/11302521/73137519-4d37f000-4059-11ea-9cf7-a3c43e54c94c.png)

Note that Vlang has to have a vscode extension (made by an upstream) for the linting to work.

**Comment by JesterOrNot** [comment]
please see https://github.com/JesterOrNot/Gitpod-V
its a pet project of mine

**Comment by Kreyren** [comment]
@JesterOrNot Doesn't seem to be relevant to linting of Vlang where official vscode extension is https://marketplace.visualstudio.com/items?itemName=0x9ef.vscode-vlang&ssr=false

**Comment by svenefftinge** [comment]
Did you install that extension and it didn't work?

**Comment by Kreyren** [comment]
@svenefftinge the extension doesn't seem to work, but it may be an upstream issue.

**Comment by sr229** [comment]
Please keep in mind Vlang must have a VS Code extension if you want linting to work: similar to how Go does as well.

**Comment by Kreyren** [comment]
@sr229 updated OP with that ^-^
