### ISSUE TITLE
Calling StopWorkspace on a workspace that is not fully up yet

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#11453]
### Bug description

Currently if calling StopWorkspace on a workspace that has not fully started up yet will cause that workspace state to become failed. 
We need to better handle this case. This is currently used by webapp to stop already running prebuild if newer prebuild has started (commit is obsolete, etc).

It is negatively impacting our workspace success rate (~5-10% depending on prebuild volume).

### Steps to reproduce

https://gitpod.slack.com/archives/C02EN94AEPL/p1657828853695599

### Expected behavior

`conditions` object is a child of `status` column in `d_b_workspace_instance` table. 

On the workspace side, for `ws-manager`:
Add a `wasCancelled` attribute to the `conditions` object, and inspect the field when setting the phase on stop workspace. 

On the webapp side, for `server`:
If the `wasCancelled` is true, set the phase to `stopped` (instead of `failed`). For workspace start, we then have to make sure we do not try and start a new workspace instance from a prior workspace instance where its conditions have `wasCancelled` set to true.

**Comment by kylos101** [comment]
@sagor999 is this issue for prebuilds, or are you considering this to also include regular workspaces and image builds?

I'm going to assume prebuilds (at least for now).

It looks like we'd want the phase to be [stopped](https://github.com/gitpod-io/gitpod/blob/8130107b0fc343b1dbefcb444920406cd6290d7a/components/ws-manager-api/core.proto#L470), and failed to be considered false [[1](https://github.com/gitpod-io/gitpod/blob/8130107b0fc343b1dbefcb444920406cd6290d7a/components/ws-manager-api/core.proto#L419)][[2](https://github.com/gitpod-io/gitpod/blob/8130107b0fc343b1dbefcb444920406cd6290d7a/components/ws-manager-api/core.proto#L391)]. But that might be naive. For example, if we indicate the prebuild stopped and did not fail, that could signal that there is a valid backup to create a new workspace from (given the prebuild indicates it was successful) - and there may not be depending on how far the prebuild got.

We should get together later this week (after the deploy of gen55) to sort out a couple options/ideas.

**Comment by sagor999** [comment]
@kylos101 yes, for prebuilds.

Good point about phase. :thinking: 
@geropl what state should be set on those prebuilds that were aborted? :thinking: I don't think we have "aborted" state and not sure if we want to add another state just for this case (seems like overkill?). 
Want to ensure as Kyle mentioned that we don't attempt to use such prebuild later on.

**Comment by kylos101** [comment]
@geropl Would it make sense to add a Cancelled phase? For example, to handle prebuilds which are interrupted because a newer commit triggered a webhook and subsequent prebuild.

**Comment by geropl** [comment]
@kylos101 I think closet to your current model - where we have `stopped` & `condition.failed` - would be a `aborted`/`cancelled` condition: we would have the same assumptions as for the former, but would clearly signal it did not fail, but got aborted.

About the "has valid backup" signal: Not sure it's out-of-scope here, or irrelevant with the PVC effort, but it would be awesome to have a clear, separate signal for that. A condition `hasBackup`, for instance.

**Comment by kylos101** [comment]
@geropl we've updated the expected behavior and scheduled this, thank you for your input! :+1:

**Comment by sagor999** [comment]
@geropl would like to pick your brain in terms of implementation details of this from webapp perspective.
Currently we have this:
https://github.com/gitpod-io/gitpod/blob/e437e1868072dfad1d195031a4709a254bd60dc8/components/ws-manager-api/core.proto#L112-L119

I would suggest to add additional StopWorkspacePolicy:
`ABORT = 2`

This policy would be similar to `IMMEDIATELY`, plus it would tell ws-manager that we don't want to attempt to run any finalizer steps on workspace, we don't care about backing up any data from that workspace, we just want to shutdown workspace as fast as possible.

You would then need to specify this policy when you are cancelling already running prebuild if there is a newer prebuild running already.

I will also add a condition to the workspace that would show that workspace was aborted\cancelled, so that UI wise we can signal this to the user. So workspace would be marked as failed, and will have wasAborted condition set to true as well. Why failed? To ensure that any existing code will filter that workspace out and will not attempt to use it to restore anything from it.
https://github.com/gitpod-io/gitpod/blob/e437e1868072dfad1d195031a4709a254bd60dc8/components/ws-manager-api/core.proto#L389
Will add this into that struct:
```
    // wasAborted is true if workspace was requested to stop and not save any data from it
    WorkspaceConditionBool wasAborted = 13;
```

WDYT?

**Comment by geropl** [comment]
@sagor999 That sounds perfect, thank you! :100: From that we can derive all states clearly, plus are backwards compatible. :lotus_position: 

:cloud:  One small nit/some :bike: shedding: from the previous values I'd expect the condition to be called `aborted`. If you reference the `StopWorkspacePolicy` in the comment the meaning is crystal-clear I think.

**Comment by sagor999** [comment]
@geropl I did my part in PR https://github.com/gitpod-io/gitpod/pull/12284 
how do you want to proceed with webapp portion? do you want to add as a commit into my PR? so that we can test it as part of one PR? Or do you want to do it as a separate PR?

**Comment by kylos101** [comment]
@sagor999 moving from scheduled to in-progress as this has a draft PR :pray:

**Comment by geropl** [comment]
@sagor999 As far as I understood your PR is independent and backwards compatible. Do you agree?
If yes let's merge that PR, and we can start developing based on the types in the API package. :+1:

**Comment by sagor999** [comment]
@geropl yes, it is. sounds good, I will mark that PR as ready for review then.

**Comment by kylos101** [comment]
@sagor999 what happens if webapp ships their change before https://github.com/gitpod-io/gitpod/pull/12284 lands? I ask because https://github.com/gitpod-io/gitpod/pull/12284 may not make it into `gen63`, as @jenting already started testing. Should we give webapp a heads up, to avoid scheduling and shipping this https://github.com/gitpod-io/gitpod/pull/12284 is live in workspace clusters?

**Comment by sagor999** [comment]
@kylos101 very good point. We do indeed need to wait for #12284 to be deployed first.

**Comment by kylos101** [comment]
> @kylos101 very good point. We do indeed need to wait for #12284 to be deployed first.

@geropl for awareness

**Comment by jenting** [comment]
I'm not sure if this issue is the right place for sharing.
We can see that even running the loadgen on an ephemeral cluster, we saw the backup failures per second.

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/49380831/186326752-3dac7af4-3fe1-41cf-b97b-f2e2e8a8447c.png">

**Comment by kylos101** [comment]
@sagor999 I assume the thought is to leave this in Awaiting Deployment, until the webapp change ships, and then move this to in-validation?

**Comment by sagor999** [comment]
@kylos101 yes.
