### ISSUE TITLE
Prevent the only remaining team owner to change their role to member

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11452]
### Bug description

While we are now preventing the last team owner to leave a team (see https://github.com/gitpod-io/gitpod/issues/4623), we're not preventing the only remaining team owner to change their role to member, leading edge cases like member-less teams after leaving the team (https://github.com/gitpod-io/gitpod/issues/6311) or owner-less teams.

See also [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1658155844284609) (internal). Cc @ jimmybrancaccio @jldec 

Cc @nidhinmanu because https://github.com/gitpod-io/gitpod/issues/6311#issuecomment-1186481212

From another [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1646217102883169?thread_ts=1646207958.538879&cid=C02EN94AEPL):

> The last owner can’t leave a team, but can change to a member and then leave. 

### Steps to reproduce

1. Create a team
2. Change your role to member
3. Leave a team
4. Try creating a new team with the same name ❗ 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3opl6)

**Comment by easyCZ** [comment]
Fix is [here](https://github.com/gitpod-io/gitpod/pull/13744)
