### ISSUE TITLE
Alternative way to access the workspace

### ISSUE THREAD

**Issue by sandorex** [gitpod-io/gitpod#1145]
While i love the idea of gitpod, i would love it if it was possible to use local apps, for example use VSCode and connect to the workspace remotely and/or use ssh to get access to the terminal without having to use the web interface which i personally dont really like and still has scrolling issues with firefox

**Comment by svenefftinge** [comment]
See #1147. Not quite the same but would solve the pain point.

**Comment by sandorex** [comment]
I am interested will ssh be exposed so that i could manually adapt vscode at least

**Comment by svenefftinge** [comment]
It is too early to make a definitive statement about that, but I understand you'd like to see that.

**Comment by svenefftinge** [comment]
closing this as it is tracked in #1781
