### ISSUE TITLE
Update supported SSH locations for VS Code Desktop

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#11467]
Currently [the following file](https://github.com/gitpod-io/gitpod-vscode-desktop/blob/df8736acad2c135eb2c6dc1938ce41605ef763cb/src/ssh/identityFiles.ts#L10-L37) dictates the locations where SSH keys are found for VS Code Desktop connections. 

This issue is to investigate removing this so it's not as brittle or explicit about locations, and will support behaviours such as [modifying the SSH key location](https://stackoverflow.com/questions/84096/setting-the-default-ssh-key-location#answers), and where possible to directly follow the rules of SSH client native to the OS. 

This also means that the detection for SSH connection might suggest the user doesn't have a key when they actually do, so we might also want to support "continue" anyway" in the SSH connection dialog on VS Code Desktop. 

Also, consider the user changing the SSH file location from within VS Code itself. 

![image](https://user-images.githubusercontent.com/5528307/179742136-3744f56b-f6c6-4df9-ad18-d98e026dabd5.png)

**Comment by Pothulapati** [comment]
I'm using the new [1password for SSH](https://developer.1password.com/docs/ssh/) integration, which means theres a new 1password SSH agent installed locally that takes care of Authentication (by retrieving private keys from the account).

But, I still get the prompt to copy password, even though it isn't needed as I authenticate with my MacOS touch ID (for 1password to work). Made a video for the same at https://www.loom.com/share/4817abee8e9f4147949c4636b9d93b2b

Not sure about the specific tech details. My reasoning was, I don’t have a private key file as that’s the whole point of using 1password but the prompt is searching for a file, and showing it as I don’t have it.

**Comment by akosyakov** [comment]
@jeanp413 I'm not sure anymore that trying to parse on our side is great idea. It won't cover @Pothulapati use case.

Could we consider instead asking a user about it? i.e.
- if a user does not have SSH keys in a Gitpod account we show a prompt to use a password and configure SSH keys
- if a user has then ask a user whether he would like to use SSH keys on this machine or password, if he selects a key then remember this choice and consider that machine is configured properly, so we won't ask again. We can make it also explicit, i.e options `Use SSH Key` and `Always use SSH Key`, only seconds will suppress the prompt in the future.

I think it simplifies implementation and let a user to streamline the flow without false positive.

**Comment by Pothulapati** [comment]
Using an SSH-agent for retrevial with no passwords may not be as common (yet?). So, I don't think my case should be the main focus here. But it would be nice to have a way to disable the pop up for users who know what they are doing. 👍🏼

**Comment by akosyakov** [comment]
@jeanp413 please check with @Pothulapati to prove that it covers all cases 🙏

**Comment by jeanp413** [comment]
@Pothulapati I released a new pre-release version of the extension `0.1.2022080404`, now the extension should detect keys from the ssh-agen, could you test it and let me know if it works for you

**Comment by Pothulapati** [comment]
@jeanp413 Yep, I tested this today with `v0.1.2022080517` and it doesn't show me the prompt to copy the password anymore!  Thanks!👍🏼
