### ISSUE TITLE
Cannot preview a HTML file with .xhtml extension

### ISSUE THREAD

**Issue by rschroll** [gitpod-io/gitpod#1146]
**Describe the bug**
HTML files with a `.html` extension show a preview button and expose the "Open Preview" command.  But when the file is renamed to a `.xhtml` extension, both of these features disappear, even though a preview is obviously possible.

**To Reproduce**
Open a file with a `.xhtml` extension.  Note that there is no option to preview the file.

**Expected behavior**
I would have expected the ability to preview a file to depend on the language mode associated with that file.  The IDE correctly identifies a `.xhtml` file to use the HTML mode, so I would expect it to offer preview as well.

If this feature must be hooked to the file name for some reason, I would expect `.xhtml` to be recognized as a common extension for HTML file.

**Additional Information**
You are welcome to try rschroll/se-gitpod for a repo containing `.xhtml` files.

**Comment by jankeromnes** [comment]
Hi @rschroll, thank you for reporting this problem! I agree that `.xhtml` extensions should be supported for live-preview.

If you have time, could you please report this issue upstream in https://github.com/eclipse-theia/theia/issues ? (Theia is Gitpod's IDE, and I believe that's where this should be fixed.)

**Comment by vince-fugnitto** [comment]
I went ahead and opened an issue in Theia, the issue here is closeable :smiley:

**Comment by JesterOrNot** [comment]
OK closing in favor of https://github.com/eclipse-theia/theia/issues/6968

**Comment by rschroll** [comment]
Thanks, all!  I was guessing it was a problem in Theia, but thought y'all would know best.  Thanks for shuttling it to the correct spot.
