### ISSUE TITLE
Faciliate log collection for VS Code Desktop

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#11468]
- Provide a CTA for a user to be able to show output logs when making connections to Gitpod via VS Code Desktop. 

For example...

![image](https://user-images.githubusercontent.com/5528307/179743275-ed1e8958-14b4-417b-b8b5-58b88ea5eb94.png)

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/11467

See [internal link](https://gitpod.slack.com/archives/C01KGM9BH54/p1658231030867079?thread_ts=1658227536.627319&cid=C01KGM9BH54)

**Comment by akosyakov** [comment]
We discussed with @jeanp413 to open the output view automatically. And print where we looked for identity files and whether we found them there. If not something like `prompting a user to use a password`

**Comment by akosyakov** [comment]
It was implemented with `Show Logs` button.
