### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#1147]
We should provide a downloadable application based on electron, that connects to the remote workspaces.

**Comment by Kreyren** [comment]
> based on electron

![](https://media.giphy.com/media/d10dMmzqCYqQ0/giphy.gif)

**Comment by Kreyren** [comment]
@jankeromnes What about something like [servo](https://github.com/servo/servo) instead of literally anything but electron (excluding java that would be even worse)

**Comment by dragonDScript** [comment]
I already made https://gitlab.com/dragonDScript/gitlab-desktop a long time ago.

**Comment by dragonDScript** [comment]
> @jankeromnes What about something like [servo](https://github.com/servo/servo) instead of literally anything but electron (excluding java that would be even worse)

Why is servo different to chromium?

**Comment by mickmister** [comment]
Hi @dragonDScript, I'm wanting to download your application you linked, but I'm getting a 404 from GitLab on both of those links. Do you know why this might be the case?

**Comment by dragonDScript** [comment]
> Hi @dragonDScript, I'm wanting to download your application you linked, but I'm getting a 404 from GitLab on both of those links. Do you know why this might be the case?

Yes, sorry, I archived it and moved yo a different URL. You can use ghr extension 'gitpod window' or open vscode
