### ISSUE TITLE
Migrate workspace class settings components

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11472]
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/pull/11435, we added support for selecting a workspace class for your workspaces. However, this settings area is not using the [`SelectableCardSolid`](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/SelectableCardSolid.tsx) component which could benefit from using the same style, save us time from updating this area manually in the future, and all the things that come with reusing components like this. Cc @Furisto 

See also relevant discussions[[1](https://github.com/gitpod-io/gitpod/pull/11435#discussion_r923569590)][[2](https://gitpod.slack.com/archives/C01KPEPQYE6/p1656595836599059?thread_ts=1656593726.806589&cid=C01KPEPQYE6)].

### Proposal

Migrate workspace class settings components to use [`SelectableCardSolid`](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/SelectableCardSolid.tsx) component.

**Comment by Furisto** [comment]
@gtsiolis After looking at this today, I am not convinced that using `SelectableCardSolid` is worth it in this case. The actual code shared between `WorkspaceClass` and `SelectableCardSolid` is

```
  className={`rounded-xl px-3 py-3 flex flex-col cursor-pointer group transition ease-in-out ${
                props.selected
                    ? "bg-gray-800 dark:bg-gray-100"
                    : "bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700"
            } ${props.additionalStyles || ""}`}
            onClick={props.onClick}
```

**Comment by gtsiolis** [comment]
@Furisto

While this is reusing a small portion of code, it could help minimize UX inconsistencies between similar elements like these on future updates. For example, changing a simple hover state color or padding in the theme selection would require us to update the element in `WorkspaceClass`. 💡 

Also, since the workspace class component was added most recently, it contains improvements that do not exist in the `SelectableCardSolid` component, like better typography and layout. 🛹 

Ideally, we could reuse the same component and fine tune the modularity of the component layout so that it supports all cases with more shared code. ✨ 

However, it's better to not impose any strong dependency here as this workspace class element will most probably evolve to support more workspace classes, moving away from functionality of the `SelectableCardSolid` component. To run a bit ahead, this will most probably look like a dropdown, as seen in this [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1659618385384999) (internal).

Let me close this issue to :a: avoid implying we need this change to happen anytime soon and :b: be respectful of your time spent already shipping this, since there's no need to further improve or optimize this for the time being.
