### ISSUE TITLE
Waiting for Admin Console to be ready ⠦Error: - Self Hosted

### ISSUE THREAD

**Issue by balajib-b** [gitpod-io/gitpod#11478]
### Bug description

root@ai:/home/gitpod# kubectl kots install gitpod
Enter the namespace to deploy to: gitpod
  • Deploying Admin Console
    • Creating namespace ✓  
    • Waiting for datastore to be ready ✓  
Enter a new password to be used for the Admin Console: •••••••••••••
    • Waiting for Admin Console to be ready ⠦Error: Failed to deploy: failed to deploy admin console: failed to wait for web: timeout waiting for deployment to become ready. Use the --wait-duration flag to increase timeout

### Steps to reproduce

Environment:
-Oracle cloud
-K3s
-Ubunru 20.04 
- ARM64 Architecture
- 4 CPU
- 24GB RAM
- K3 installed
- certmanager installed successfully

$ kubectl kots install gitpod

May i know which ports are to be opened to public web access.

### Expected behavior

install and availabled at localhost:8080

### Anything else?
gitpod@ai:~$ sudo kubectl get services -n gitpod
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kotsadm-minio      ClusterIP   10.43.174.41    <none>        9000/TCP   48m
kotsadm-postgres   ClusterIP   10.43.223.253   <none>        5432/TCP   48m
kotsadm            ClusterIP   10.43.71.54     <none>        3000/TCP   47m

![image](https://user-images.githubusercontent.com/64471553/179788025-330172f8-723c-4e47-83c7-3c9abf3e84a6.png)

**Comment by gkramer** [comment]
@balajib-b GitPod explicitly does not support arm64 yet, see:

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
<snip>
          - key: kubernetes.io/arch
            operator: NotIn
            values:
            - arm64

Question to the team: When will this be supported? [Today will be the first time I start looking at your codebase, as I've only just started test-driving the kit now; If its not too big a task, I'm happy to consider adding the support myself - do you guys have access to arm64 github runners?]

**Comment by lucasvaltl** [comment]
Hey @gkramer and @balajib-b , [here](https://github.com/gitpod-io/gitpod/pull/7937#issuecomment-1042718737) is a link to a comment that represents our current stance on ARM support. I'd suggest you follow that ticket  in order to get notified when our stance changes on this. I will close this issue for now.
