### ISSUE TITLE
Stuck in an authentification loop with gitlab 😭

### ISSUE THREAD

**Issue by voncay** [gitpod-io/gitpod#11475]
### Bug description

I'm authenticated on my company's Gitlab.com account with my work email.
I click on the Gitpod button from my gitlab project.
The gitpod.io page invites me to continue with gitlab for the repository of my project, so I click on the invitation.
I'm having the following error:
"Email address already used in another account. Please log in with gitlab.com."

### Steps to reproduce

1. Authenticate on gitlab.com
2. launch gitpod from repository project page.

### Expected behavior

workspace launched flawlessly.

### Anything else?

I did changed the username  assoscieted with my work email a while back, might be related.
If so, how can I reset my "gitpod account" if I can't even login ?

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3p022)

**Comment by jimmybrancaccio** [comment]
This appears to also affect self-hosted Git provider instances as well. See Front conversations (linked in initial message of this issue).

**Comment by mgoedecke** [comment]
This affects us as well, at least I think this is the same issue.

We use gitpod.io but with self-hosted gitlab connected. Everything worked fine when settings things up and couple of days after that. Yesterday got message from gitpod.io that I need to login again.

Then I click Continue with GitLab, authenticate successfull with Gitlab and as I am being redirected I get this error message, that I would need to login with our self-hosted gitlab. However I really don't know how that should be possilbe since there are only the 3 social logins available:

![image](https://user-images.githubusercontent.com/3637347/181272799-d59d5b6b-cb1a-4197-80a6-44086e169e6b.png)

**Comment by amael-heiligtag** [comment]
Hello, 

this looks like the issue I'm also facing. Please find below detailled steps to reproduce.

My steps :
1.	I created a gitpod.io account by connecting with **github** and my professional email address
2.	I opened a workspace from our _self-hosted gitlab_ [following the official procedure](https://www.gitpod.io/docs/gitlab-integration#connecting-your-self-hosted-gitlab-account)
3.	While opening the workspace I got the following warning, which I closed by clicking on “Authorize…”

![image](https://user-images.githubusercontent.com/99711941/182785635-0be60b35-1c58-4909-a9f3-b544cc277956.png)

4.	Now my _self-hosted gitlab OAuth provider_ was showing up in my account’s “integrations” section
 
![image](https://user-images.githubusercontent.com/99711941/182786049-ab60524a-da83-4bba-b65c-90bf3471d651.png)

5.	Then I closed everything, disconnected and tried to reconnect using **Saas gitlab** where I also have an account with the same email adress 
•	[ISSUE 1] This is where I got the error message indicating - wrongly - that I should login with my self-hosted provider  #11475. The correct message would be to tell me to login with my initial OAuth provider **github**.
 
7.	Using this github I just played a little more…. And too much ? I revoked the **github** account integration in my profile, leaving only the _self-hosted gitlab_ and tried to get back in. Impossible as you can’t login with a third party OAuth provider… my email  address seems locked out of gitpod.io… 
•	[ISSUE 2] This should be impossible to do. It should not be possible to revoke the logging-in OAuth provider.
 
8.	My last try was to create a new gitpod account linked to another **SaaS gitlab** account using a different email address, and try to link this one to my _self-hosted OAuth provider_. I get up to the following window #7001
 
 
![image](https://user-images.githubusercontent.com/99711941/182786868-c782c6a5-f984-4a1f-9b4e-7000251059d7.png)

 
9.	But both options fail and I’m back to the original message asking me to login with _my self-hosted identity provider_. My identity in this one is now definitively locked out of gitpod.io.
•	[ISSUE 3] You should not offer a choice that can’t work (login with a 3rd party identity provider)

**Comment by jimmybrancaccio** [comment]
Re-opening this since it's popped up again.
