### ISSUE TITLE
Add pagination or infinite scroll support

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11483]
### Problem to solve

Pagination. 📄 

### Proposal

:a: **Pagination** breaks up content into multiple pages.
:b: **Infinite scroll** helps users parse a large number of items. Infinite scroll is also suitable when the list updates frequently and there are no sorting or filtering options.

Cc @laushinka @jldec because of our recent discussion related to pagination.

### Designs

| Pagination (Simple) | Pagination (Complex) | 
|-|-|
| <img width="1440" alt="Simple" src="https://user-images.githubusercontent.com/120486/179847577-dd0c430b-32d1-4f53-9f05-36ffbe9ce7c8.png"> | <img width="1440" alt="Complex" src="https://user-images.githubusercontent.com/120486/179847152-8e7ed349-7877-46ce-8574-fb6a1bfc8256.png"> |

| Infinite Scroll (Simple) | Infinite Scroll (Loading) | Infinite Scroll (Showing All) |
|-|-|-|
| <img width="1440" alt="InfiniteScrollSimple" src="https://user-images.githubusercontent.com/120486/179844592-59a9c18d-10b8-434d-b866-736637df157a.png"> | <img width="1440" alt="InfiniteScrollPage" src="https://user-images.githubusercontent.com/120486/179844602-a437f648-a84b-4dfe-b815-8f0e30f120e6.png"> | <img width="1440" alt="InfiniteScrollAll" src="https://user-images.githubusercontent.com/120486/179844608-ad14893f-6214-4abd-9324-6d909af66759.png"> |

See [design specs](https://www.figma.com/file/3fdBIQangZxnOPm35uWJZX/Team-usage-view---Iterate-on-UI-based-on-designs%2C-feedback-%2311285?node-id=1326%3A3573).

**Comment by laushinka** [comment]
Thanks for the designs! 
@gtsiolis @jldec If paginated, how many results do we want to show per page?

**Comment by gtsiolis** [comment]
@laushinka, 20 is usually a good starting point for pagination that makes sense, but also depends on the context.

However, I'd say **let's go with 10**, which is also a common approach, for brevity following our approach with other product areas like the workspaces list (see inactive workspaces grouping, etc) and given the upcoming **collapsible component** to be added on each entry and the potential addition of the **usage graph** above this list (see [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1657709070799429) (internal)).

We can always adjust this in future iterations. ➿

Looping in @jldec in case he has any strong preference towards a different solution. 🏀

**Comment by laushinka** [comment]
> 20 is usually a good starting point...
>  **let's go with 10**, ... and given the upcoming **collapsible component** to be added on each entry and the potential addition of the **usage graph** 
> We can always adjust this in future iterations. ➿

Agree! I also thought 10 is a good start. For now we're doing the pagination in the client instead of the server, so once the data is loaded, going through the pages takes no time at all.

**Comment by laushinka** [comment]
> I assume in the long-run we will switch to server-side pagination. 

Exactly.
