### ISSUE TITLE
Workspace shutting down after the inactivity timeout while actively working

### ISSUE THREAD

**Issue by dlabak-bt** [gitpod-io/gitpod#11488]
### Bug description

The workspace has consistently shut down after every 30 minutes (inactive workspace timeout) today even while I've been actively modifying and saving files, and running commands in the terminal.

The workspace should only shut down after 30 minutes of inactivity, not while I'm actively typing in the terminal window.

This occurs both while running the workspace in the web browser and while running in a local vscode instance on desktop.

### Steps to reproduce

Actively work in the gitpod workspace for 30 mintues.

### Expected behavior

Workspace should remain up while actively working.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ot1m)

**Comment by akosyakov** [comment]
@dlabak-bt Could you please send to [support@gitpod.io](mailto:support@gitpod.io) affected workspace ids and when it happened. As well which interfaces did you use? VS Code Browser/Desktop, any JB IDE or direct SSH?

**Comment by akosyakov** [comment]
I removed from scheduled, see the issue does not have any troubleshooting information.

**Comment by akosyakov** [comment]
Just discussed with @iQQBot that in VS Code Desktop there is no heartbeating if a user only works with terminals and does not do any other UI actions, like typing in the editor. In VS Code Browser it is not the case though.

**Comment by dlabak-bt** [comment]
I always go back to the web dashboard and click “open in vscode desktop”.

Today, the new workspace is working normally (not shutting down) and I’m following the same procedure that I followed yesterday.

**Comment by jeanp413** [comment]
@dlabak-bt I've did a few more fixes on the gitpod extension last week, do you still get this error?
