### ISSUE TITLE
Issues with numpy and pandas, even in provided minimal project

### ISSUE THREAD

**Issue by tallgaijin** [gitpod-io/gitpod#11482]
### Bug description

Getting a ModuleNotFoundError on pandas and numpy, even after the packages have been installed.

### Steps to reproduce

1. Open https://www.gitpod.io/docs/languages/python#pandas in Gitpod
2. Run

I get:
gitpod /workspace/Gitpod-Pandas (master) $ /home/gitpod/.pyenv/versions/3.8.13/bin/python /workspace/Gitpod-Pandas/src/app.py
Traceback (most recent call last):
  File "/workspace/Gitpod-Pandas/src/app.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Verified that numpy is installed:
gitpod /workspace/Gitpod-Pandas (master) $ pip show numpy
Name: numpy
Version: 1.23.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /workspace/.pyenv_mirror/user/3.8.13/lib/python3.8/site-packages
Requires: 
Required-by: pandas

Seeing similar behavior on a private repo with pandas.

**Comment by tallgaijin** [comment]
Seems like whether this error happens or not depends on how I run the script.

Using VS code run and debug feature results in this command and triggers the error:

gitpod /workspace/Gitpod-Pandas (master) $  /usr/bin/env /usr/bin/python3 /workspace/.vscode-remote/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 45153 -- /workspace/Gitpod-Pandas/src/app.py

Using a simple command like this results in no error:

gitpod /workspace/Gitpod-Pandas (master) $ python src/app.py

Using this command triggers the error:

gitpod /workspace/Gitpod-Pandas (master) $ /bin/python3 /workspace/Gitpod-Pandas/src/app.py
Traceback (most recent call last):
  File "/workspace/Gitpod-Pandas/src/app.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by svenefftinge** [comment]
The interpreter. path was not set properly. I have added it to the example [[1](https://github.com/gitpod-io/Gitpod-Pandas/commit/57486a59935895027f3745575e4449f4aee27ba7)].

**Comment by tallgaijin** [comment]
> 

OK, thanks. What about other Python repositories? Shouldn't Gitpod be setting that value correctly by default when creating a new Gitpod for a Python repository?

**Comment by axonasif** [comment]
> OK, thanks. What about other Python repositories? Shouldn't Gitpod be setting that value correctly by default when creating a new Gitpod for a Python repository?

It seems like https://github.com/gitpod-io/workspace-images/pull/895 can resolve this issue.
