### ISSUE TITLE
Update EKS terraform module to use s3 access policy in EKS reference architecture

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#11480]
At present our EKS terraform module grants [broad access to s3 buckets](https://github.com/gitpod-io/gitpod/blob/3955503d630aba05bda0352f99782a3ef3a8d16a/install/infra/terraform/eks/storage.tf#L11-L17) within an AWS account. This broad grant prevents access issues with object storage and the registry but diverges from the more strict policy laid out in the EKS reference guide. The EKS terraform module should replicate this tighter access so we're fully validating the reference architecture behavior.

**Comment by lucasvaltl** [comment]
I believe this should be covered via #11280 cc @nandajavarma
