### ISSUE TITLE
[Workspaces] Open Button seems to be enabled but does not work in pending state

### ISSUE THREAD

**Issue by jbicker** [gitpod-io/gitpod#1148]
### Describe the bug
Although the WS is in pending state the Open Button seems to be enabled. Nothing happens on click. It should be greyed out then.
<img width="1150" alt="Bildschirmfoto 2020-01-27 um 14 28 40" src="https://user-images.githubusercontent.com/28291421/73178978-b29be780-4112-11ea-8680-6c88710b7604.png">

### Steps to reproduce
Open Workspaces page. If there is an WS in `Pending` state click the open button and watch what happens...

### Expected behavior
Either the button should be greyed out or otherwise open the WS page showing the respective state.

**Comment by svenefftinge** [comment]
deployed
