### ISSUE TITLE
Issue opening Space

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1149]
### Describe the bug

Went to open a github project and received this error using the chrome extension:
Sorry, something went wrong 😓
Login with GitHub failed. Please try again.

This is the url that appeared:
https://gitpod.io/sorry/#Login%20with%20GitHub%20failed.%20Please%20try%20again.

This is the space I attempted to open:
https://github.com/gabsrodriguez/ReduceReuseRecycle-frontEnd

I then tried the chrome extension again and it looks like it had started, but for some reason was redirected. Opened from here without issue! Wanted you to be aware anyway. The project info, if useful, is here:

fb5712ff-8eaa-4891-9213-1598c494ba56
gabsrodriguez/ReduceReuseRecycle-frontEnd - master
Created 2 minutes ago
gabsrodriguez/ReduceReuseRecycle-frontEnd
master
6000046d
Running - Started 2 minutes ago.

To reiterate, it is opening fine now, but I wanted to let you know. Please let me know if you have any questions!

**Comment by jankeromnes** [comment]
Hi @ColbyWTaylor, many thanks for your detailed error report. 💯 

For this error message specifically:

> Sorry, something went wrong 😓
> Login with GitHub failed. Please try again.

it's usually a temporary bug on GitHub's side (e.g. one of their servers was under heavy load and decided to drop our request). It should be fairly rare, and it should not persist when you retry immediately.

But please report this again if you feel the issue becomes more frequent, or doesn't go away on retry.
