### ISSUE TITLE
Add usage page empty state

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11495]
### Problem to solve

In the upcoming changes for adding usage pages, the default page layout will contain no usage data for new teams.

### Proposal

A boring (simple) solution would be to use a similar empty state as other product areas.

However, this is a good opportunity to:
1. Nudge users about usage-based pricing (UBP) for teams or individuals.
2. Link back to team billing for team owners.
3. In the future, link to invoices.

See also [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1658306701330459?thread_ts=1658306651.019699&cid=C02EN94AEPL) (internal). Cc @easyCZ @laushinka

> @easyCZ: It should instruct the user to check which team/account they have configured to attribute to (or switch teams)

**Comment by laushinka** [comment]
Thanks for creating the issue, @gtsiolis! 
We can also do the nudging [this way](https://gitpod.slack.com/archives/C02EN94AEPL/p1658312100766029?thread_ts=1658306651.019699&cid=C02EN94AEPL). Let me know what you think.
