### ISSUE TITLE
Workspaces Empty, Gitpod not opening

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1150]
### Describe the bug

I tried opening a project, but it would not load. I then went into my gitpod workspaces to see if it was in there but I am just seeing a black screen with nothing in- not even the logos. Any idea what is happening?

**Comment by ColbyWTaylor** [comment]
After refreshing a few times I am seeing the gitpod logo and navbar again, but the projects are nonexistent still. The path is https://gitpod.io/workspaces/ and I am logged in.

**Comment by jankeromnes** [comment]
Thanks for reporting these problems. They seem to be related to #1151, which we are currently investigating, but your report contains different symptoms which could help our investigation.

**Comment by jankeromnes** [comment]
I'll close this issue now, since the #1151 incident has been resolved. But please let me know if you're still seeing issues.
