### ISSUE TITLE
Project Named "billing" Can't Be Managed in Dashboard

### ISSUE THREAD

**Issue by nkeenan38** [gitpod-io/gitpod#11510]
### Bug description

In the dashboard, a team's projects can be managed under `https://gitpod.io/t/<team>/<project>`. Team Billing settings are managed under `https://gitpod.io/t/<team>/billing`. If a project is added named `billing`, then that project's settings cannot be managed due to the conflict with the Team Billing page. 

### Steps to reproduce

1. Create a new team.
2. Create a new project from a GitHub repo named `billing`.

### Expected behavior

Team management settings should not shadow project management settings (and vice-versa).

**Comment by gtsiolis** [comment]
Nice catch, @nkeenan38! I remember running into this a similar issues back in https://github.com/gitpod-io/gitpod/issues/5516.

**Comment by gtsiolis** [comment]
This is no longer reproducible as the billing is no longer nested under the team path. Cc @nkeenan38
