### ISSUE TITLE
Add initContainer to workspace pods to ensure we can reach ws-daemon

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11513]
## Is your feature request related to a problem? Please describe

When the autoscaler adds a node, `ws-daemon` starts and in some edge cases the workspace can start and not be able to reach `ws-daemon` because the socket is not mounted in the pod (timeout of 2m)

## Describe the behaviour you'd like

Wait until the workspace can reach `ws-daemon` port to start the `workspacekit` ring0

**Comment by jenting** [comment]
Related to #9536

**Comment by sagor999** [comment]
Spoke to @aledbf 
His PR #11540 should fix this issue, as adding initContainer that would talk to ws-daemon is not as straight forward as we thought it would be (network policy (can't just curl ready probe from outside), rbac complications(cannot check daemon`s pod ready state from inside init container as that would require giving workspace access to list pods :grimacing: ).
