### ISSUE TITLE
Allow users to switch between months and update usage page sidebar designs

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11526]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/11481, the sidebar in the new usage page does not support switching between other periods (months).

### Proposal

| Sidebar | Sidebar (Dropdown) |
|-|-|
| <img width="500" alt="Sidebar-1" src="https://user-images.githubusercontent.com/120486/180205291-08396083-a9f0-4370-a303-64fbbcd5998a.png"> | <img width="500" alt="Sidebar" src="https://user-images.githubusercontent.com/120486/180205297-e5238e6d-eca5-4c63-81f1-f61807f2893a.png"> |

**Comment by laushinka** [comment]
Hope you don't mind I reordered the wording to show the main task first 🙏🏽

**Comment by gtsiolis** [comment]
Thanks, @laushinka! PERMISSION TO EDIT: ALWAYS ON 🏀

**Comment by gtsiolis** [comment]
For more clarification, the goal of the designs is to provide dropdown options only for the months that the team had active billing months.

This comes with a scalability issue as the list could grow a lot after a year or two, which can be tackled later by either introducing a scrolling area or trimming the list to the last 6 months.

However, in the future, I'd expect this to become clearer by providing a separate invoice view where billed months are listed in a better and more scalable way similar to what has been initially described for the use page (see early designs in https://github.com/gitpod-io/gitpod/issues/10328#issuecomment-1165627563) and instead rely on date range filtering on the usage page for drilling down on usage for a specific invoice (billed month), see screenshot below.

<img width="520" alt="Screenshot 2022-07-26 at 11 22 31 AM" src="https://user-images.githubusercontent.com/120486/180959578-8f8584d9-6f6f-4305-8f5b-4be124303283.png">

**Comment by laushinka** [comment]
Thanks, @gtsiolis! Writing down comments here after a quick brainstorm on the implementation with @easyCZ:

> the goal of the designs is to provide dropdown options only for the months that the team had active billing months.

For simplicity in this skateboard, we will show a list/dropdown/buttons/something of the previous 6 months without knowing beforehand whether the team has billed sessions or not. If there is no data, then that is tackled by the empty data page. 

> trimming the list to the last 6 months.

👍🏼

A summary of the functionality for this skateboard:
- User is shown by default the current month.
- List/dropdown/history shows 6 months prior. This could be a separate section, or a scrolling dropdown as shown in the design above.
- We don't have to know beforehand whether there is data for the previous months. If there is no data, we show the empty usage data page.

Next issues maybe:
- Put month in the URL (shareable)

@gtsiolis Let me know if you'd like to talk further about this or if that changes your designs in any way 🙏🏽

**Comment by gtsiolis** [comment]
Fair enough, @laushinka and @easyCZ! 🤝 

This will also push for improving the empty state and the copy included there, in https://github.com/gitpod-io/gitpod/issues/11587.

> Put month in the URL (shareable)

Rendering a usage view based on a URL parameter sounds great for fixed durations like Last 30 Days, etc. or custom range dates which will be needed for deep-linking from a potential invoice page in the future, but not sure if adding the month in the URL of the usage page is something we won't need to remove later. 💭 

> Let me know if you'd like to talk further about this or if that changes your designs in any way 🙏🏽

Let's go with the fixed 6 dropdown options, but also include a **section header** there to make this clearer for users in case they wonder what happened to the previous billing cycles, etc. I'd love to make this an opt in feature of the existing dropdown component if possible, but let me know if that's introducing too much complexity. Feedback is welcome! 

<img width="500" alt="Sidebar" src="https://user-images.githubusercontent.com/120486/180983560-cdf7fcf7-5352-486f-98dd-66761a736044.png">

See [design specs](https://www.figma.com/file/3fdBIQangZxnOPm35uWJZX/Team-usage-view---Iterate-on-UI-based-on-designs%2C-feedback-%2311285?node-id=1379%3A4710) for detailed padding, colors, font-size, and font-weight in case it helps, @laushinka!

**Comment by laushinka** [comment]
Writing here that the dropdown didn't get implemented [in the PR](https://github.com/gitpod-io/gitpod/pull/11617). [This](https://github.com/gitpod-io/gitpod/issues/11685) is the follow-up ticket to do so.
