### ISSUE TITLE
Site cannot be reached

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#11551]
### Bug description

When attempting to open a workspace in Gitpod, or access a shared workspace, we get the _This site can't be reached_ error
![site-cannot-be-reached](https://user-images.githubusercontent.com/14900791/180353967-40b75b81-f0b1-4645-9964-1a17e3dd8149.PNG)

This seems to be the issue with the internet connection at the site as if we switch to another network Gitpod works with no issues. However, what are the network settings or router settings do we need to tweak to allow connection to Gitpod?

The issue is replicated among different users using different workspaces connected to the same network.

### Steps to reproduce

1. Attempt to create a Gitpod workspace (or access a workspace by its shared link:)

**Comment by svenefftinge** [comment]
Can you share more information around the network where you reliably see that issue? How is it restricted/special?

**Comment by kunxin-chor** [comment]
As the network belongs to the school, I need to write in specially. It seems to be a DNS-related issue as Gitpod works if I switch to Google DNS. Are you aware of any network or router settings that will cause a DNS error when connecting to Gitpod workspaces?
