### ISSUE TITLE
service down PT 9:20am 01/27/2020?

### ISSUE THREAD

**Issue by tianhaoz95** [gitpod-io/gitpod#1155]
### Describe the bug
Login user info empty and workspace is forever loading.

### Steps to reproduce
Login from homepage or open a workspace from a repo.

### Expected behavior
It should show my workspaces.

### Additional Information
n/a

### Example Repository
https://github.com/tianhaoz95/iwfp

**Comment by jankeromnes** [comment]
Hi @tianhaoz95, really sorry about this problem. Likely related to this ongoing incident: #1151. We're currently trying to restore US service as fast as possible, and also make the US region durably more stable.

**Comment by tianhaoz95** [comment]
@jankeromnes now the service is back up, but many workspace freezes after first user interaction. For example, it freezes after I type in a work in terminal. However, the workspace did not die. I can close it and log back in, but after typing another word, it will freeze again.

**Comment by svenefftinge** [comment]
Can you share additional information like what you did on what kind of project?

**Comment by tianhaoz95** [comment]
@svenefftinge now the issue has been gone. It happened on 3 of my projects. 1 python, 1 dart + js and 1 typescript.

**Comment by svenefftinge** [comment]
Probably a noisy-neighbourhood issue. Closing this, as we have other more concrete issues to take actions. Thanks for reporting!
