### ISSUE TITLE
Avoid accumulating large amounts of webhook event data in d_b_webhook_event  

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#11578]
Followup to PR #11356

The JSON for raw events in `d_b_webhook_event` is quite large - and events will accumulate fast. Let's reduce the data which is retained long term, and avoid storing information which is never relevant to prebuilds.

**Comment by AlexTugarev** [comment]
```
(node: 29) UnhandledPromiseRejectionWarning: QueryFailedError: ER_DATA_TOO_LONG: Data too long for column 'rawEvent' at row 1
```

@jldec, can we schedule this?

**Comment by jldec** [comment]
scheduled (no need to ask :))

**Comment by jldec** [comment]
First step here is probably to reduce the size of data stored by removing large unnecessary json like git changes
