### ISSUE TITLE
Refine Spending Limit modal

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#11575]
A followup to https://github.com/gitpod-io/gitpod/issues/11401 as https://github.com/gitpod-io/gitpod/pull/11508 added just a simple version of the Spending Limit modal w/o the unlimited setting.

<img width="622" alt="Screen Shot 2022-07-22 at 15 46 02" src="https://user-images.githubusercontent.com/914497/180452506-e2139072-19d3-40f3-b7fa-1800a0590b58.png">

Here's a link to [the user story](https://www.notion.so/gitpod/Usage-Based-Pricing-User-Stories-0fc4ac2f2413449b95d70feb60177aaf#b9f6d7889ec14b3a86671ce123864236) which already include figmas. :sparkles:

**Comment by jldec** [comment]
Closing - please open new issues for UI polish or new features related to usage limits.
