### ISSUE TITLE
Add Project.prebuildAuthorizedUser

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#11574]
Issues like https://github.com/gitpod-io/gitpod/issues/11566 arise from the fact that the authorized user is not related to a project and when a push event is processes, it's not easy to find the account/credentials to run a prebuild with. 

Since we introduced the Project as an umbrella for repositories and prebuild configuration, we may consider using it to persist a source of credentials (abstract on purpose) which might be a user account to match the current behavior, or a service account in future. 

This would also gives us a greater chance to add management features for credentials on the dashboard. I'm thinking of updating the authorization and fixing the webhook configuration in case of related changes in a team.

**Comment by geropl** [comment]
I think this idea is still relevant, and we continue to discuss it.
