### ISSUE TITLE
Adjust usage attribution to prompt users when attribution is ambiguous

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#11579]
In order to correctly attribute usage to either user or a team, we need to update our Workspace Instance attribution logic.

An `usageAttributionid` should always be set on a `WorkspaceInstance`, irrespective if the installation is SaaS or Self-hosted.

The logic to determine the `usageAttributionId` is as follows (in order of priority):
1. The user has made an explicit choice in their user settings and have configured the `User.usageAttributionId`.
2. The user is a member of exactly one entity from (user, team 1, team 2) which has billing enabled. If there is exactly such choice, then the attribution is not ambiguous and the one entity is used.
3. The choice is ambigous. In this case the user must be prompted to set the entity to which to attribute usage for the WorkspaceInstance currently being started. On the server, this should be reported as a typed error and the user should be prompted to specify the `usageAttributionId` as part of the WorkspaceInstance create request.

**Comment by gtsiolis** [comment]
@easyCZ Is this related to a different problem to solve from https://github.com/gitpod-io/gitpod/issues/11498?

**Comment by easyCZ** [comment]
@gtsiolis You've found this before I finished writing the description :)

It's related to the same problem. This focuses more on the backend logic but I think we can merge, tho the backend is likely needed a lot sooner than we can realistically do the UI changes.

**Comment by geropl** [comment]
Note: Also need to update the WebApp docs!

**Comment by jankeromnes** [comment]
On a side note: https://github.com/gitpod-io/gitpod/pull/11584 started implementing this change (by no longer setting the user attribution override in some cases). https://github.com/gitpod-io/gitpod/pull/11777 will continue and finish this work.
