### ISSUE TITLE
Document load balancer requirements more clearly

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#11581]
Gitpod services (specifically HTTPS and SSH) are exposed to the outside world via load balancers; however we don't document this dependency at a high level on the [Gitpod installation prerequisites](https://www.gitpod.io/docs/self-hosted/latest#prerequisites-to-install-gitpod-self-hosted). In addition our reference architectures give brief setup instructions for load balancers but don't indicate specific requirements, such as EKS clusters requiring the use of either ELBs or a combination of ALB (for HTTPS when using AWS certificates) and NLB (for SSH).

This information should be presented at a high level in the requirements list and more detailed instructions should be presented in the reference architectures.

**Comment by lucasvaltl** [comment]
this is related to https://github.com/gitpod-io/gitpod/issues/10126
