### ISSUE TITLE
Improve usage page design when no data is present (empty state)

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11587]
## Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/11554 (Cc @laushinka @easyCZ @jldec), the usage page empty state could benefit from the following changes:
1. Reused the existing pattern and design of the empty state used elsewhere in the product, see screenshots below.
2. Update the empty state copy for better clarity. What are sessions, how can you check with other teams, etc.

> No sessions found.
> Have you started any[ workspaces](https://gt-test.preview.gitpod-dev.com/workspaces) or checked your other teams?

| Usage |
|-|
| <img width="1440" alt="Screenshot 2022-07-22 at 8 12 58 PM (2)" src="https://user-images.githubusercontent.com/120486/180490831-0ed17c57-e05b-4090-a970-31519b094694.png"> |

| Variables | SSH Keys |
|-|-|
| <img width="1440" alt="Screenshot 2022-07-22 at 8 13 16 PM (2)" src="https://user-images.githubusercontent.com/120486/180490755-99a71fe3-a708-4e90-b138-a053ddf96ced.png"> | <img width="1440" alt="Screenshot 2022-07-22 at 8 13 19 PM (2)" src="https://user-images.githubusercontent.com/120486/180490759-59738436-1332-41d0-b36b-fe4a8021d12a.png"> | 

| Workspaces | Projects |
|-|-|
| <img width="1440" alt="Screenshot 2022-07-22 at 8 13 36 PM (2)" src="https://user-images.githubusercontent.com/120486/180490682-70d1afff-55f4-41e6-b554-7cde39165e97.png"> | <img width="1440" alt="Screenshot 2022-07-22 at 8 13 08 PM (2)" src="https://user-images.githubusercontent.com/120486/180490699-fc3860ae-a5c3-4cfd-9895-29634c5acac8.png"> |

**Comment by svenefftinge** [comment]
I think this has been implemented.

**Comment by gtsiolis** [comment]
@svenefftinge Thanks for noticing! This issue was about improving the design of the empty state layout, not adding the empty state for previous months as described in https://github.com/gitpod-io/gitpod/issues/12803 and https://github.com/gitpod-io/gitpod/pull/12858.

But let's keep this closed until the design of the empty state becomes a real issue.
In the meantime, I may open a PR for updating the design of this page.
