### ISSUE TITLE
User defined bash_aliases

### ISSUE THREAD

**Issue by Phxntxm** [gitpod-io/gitpod#11585]
## Is your feature request related to a problem? Please describe

No, not a problem. This is purely a QOL change, but a very nice one to have IMO

## Describe the behaviour you'd like

I'd like there to be user settings where you can define aliases that will be thrown into any workspace you want (or possibly scoped to specific ones, similar to how environment variables have scope).

## Additional context

Many users have their own workflow, their own aliases, their own functions to simplify their work. It's often that these won't exactly be shared between different developers. Just as a small example, I've often overrode cd to do a cd, then immediately ls... it's just a habit of mine to ls when changing to a new folder, but not everyone is going to want this, so throwing it into the .gitpod.yml file isn't really a good solution. User defined bash aliases seems like a pretty simple and elegant thing to improve QOL

**Comment by svenefftinge** [comment]
This can be done by adding your dotfiles repository to the user settings.
See https://www.gitpod.io/docs/config-dotfiles#title
