### ISSUE TITLE
Websocket Connections Blocked

### ISSUE THREAD

**Issue by CastHash532** [gitpod-io/gitpod#1158]
My school recently added web authentification and i can no longer access to gitpod workspaces:

![image](https://user-images.githubusercontent.com/51857536/73260324-f867b700-41c9-11ea-8a28-b0b276abfec3.png)

Do i have to contact the school administration, Or you guys can fix this problem?

**Comment by svenefftinge** [comment]
You'll need to allow websocket connections to *.gitpod.io. We cannot fix that for you, unfortunately.
