### ISSUE TITLE
GPU support for Data Science / ML work

### ISSUE THREAD

**Issue by singhsidhukuldeep** [gitpod-io/gitpod#11599]
## Is your feature request related to a problem? Please describe
I have to port my code everytime I want to check functionality with GPUs

## Describe the behaviour you'd like
I would like an option to have Nvidia GPU attached gitpods

## Describe alternatives you've considered
I have a gaming laptop 😂

## Additional context
State of the art Data science development is very bound by compute. It would be amazing if gitpod bridges that gap

---

Also, thanks guys for an amazing platform 👌🙌

**Comment by aledbf** [comment]
Closing. Please follow the EPIC https://github.com/gitpod-io/gitpod/issues/10650
