### ISSUE TITLE
Install Gitpod Self-Hosted failed

### ISSUE THREAD

**Issue by luxingxiao** [gitpod-io/gitpod#11594]
### Objective

When I install gitpod in a self-built kubernetes cluster, it fails, and the installation is blocked in the "Waiting for datastore to be ready" stage. Describe pod found the following errors: 1 pod has unbound immediate PersistentVolumeClaims.

**Comment by gtsiolis** [comment]
Removed the **~feedback-issue** label to avoid any confusion as feedback issues are used to gather feedback, suggestions, and experiences from users while iterating on a specific product feature.

Cross-posting also the recently updated issue template description in https://github.com/gitpod-io/gitpod/pull/11244.

**Comment by corneliusludmann** [comment]
Could you please list the persist volumes and persist volume claims?

```
$ kubectl get pv
$ kubectl get pvc
```
