### ISSUE TITLE
"OutOfMemory"

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1159]
### Describe the bug

Hi! Trying to open a workspace but receiving this error:

OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 57302581248, capacity: 57639526400
Please file an issue if you think this is a bug.

**Comment by jankeromnes** [comment]
Hi @ColbyWTaylor, sorry about that, and thank you for reporting. This looks like a Kubernetes scheduling bug that I thought we had already fixed. I'll investigate.

**Comment by jankeromnes** [comment]
Ah, it seems like we've fixed the problem in our staging environment, but haven't deployed the fix to production yet. This should happen tomorrow is all goes well.

**Comment by svenefftinge** [comment]
deployed
