### ISSUE TITLE
Restart the ws-daemon cause the workspace pod sometimes Failed

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#11606]
### Bug description

Manually restart the ws-daemon `kubectl delete pod -l component=ws-daemon`.
Sometimes the workspace pod goes into a _Failed_ state.

![image](https://user-images.githubusercontent.com/49380831/180682213-d797e72c-e0a1-4920-8c34-caa46f15fff6.png)
![image](https://user-images.githubusercontent.com/49380831/180682202-10468863-bf5b-445b-b7bf-36b117b4d820.png)

Note that, it's not always reproducible. However, even if it's not reproducible, the workspace pod's shell is affected as well. For example:
- was 
   ![Screen Shot 2022-07-25 at 11 03 35 AM](https://user-images.githubusercontent.com/49380831/180690128-14140434-1958-4898-bce2-f3fe2c98161a.png)
- is
   ![image](https://user-images.githubusercontent.com/49380831/180690044-b2c0b452-5b52-4968-9dd6-e474d7b9d12b.png)

However, kubectl exec the workspace pod, the shell is able to use.

### Steps to reproduce

1. Create a preview environment with the repo `github.com/gitpod-io/leeway`.
2. Keep the workspace (don't stop the workspace).
3. Delete the ws-daemon to make it restart `kubectl delete pod -l component=ws-daemon`.
4. The user's workspace will be stopped _or_ the user's shell does not work normally (you can run `ls` command, but you can't execute any commands success).

### Expected behavior

The user can keep using the workspace without any impact.

**Comment by utam0k** [comment]
@kylos101 Should we put this into the schedule column? I asked because it's a big problem. As I recall, I think the backup process was only affected before.

**Comment by kylos101** [comment]
@utam0k no, I do not think so, at least not yet. Why? Two reasons:

1. It is unusual for `ws-daemon` to be deleted or restart. When `ws-daemon` is restarted while a backup or content init is happening, then, workspace failure is likely.
2. I'm not sure how we can mitigate this for installations that are using object storage (not PVC), but, I think that would require significant redesign of how we use object storage...and it would be better to remove it (rather than harden it).

**Comment by kylos101** [comment]
Closing as we should not be deleting ws-daemon pod, and, with mk2, it should be possible.

**Comment by jenting** [comment]
> Closing as we should not be deleting ws-daemon pod, and, with mk2, it should be possible.

@kylos101 
When we replace a new ws-daemon container image, how's that possible without restarting the ws-daemon pod?
Also, the problem is still there, and the mk2 hasn't been in production. Closing as not planned rather than Close as completed is more suitable.

**Comment by kylos101** [comment]
@jenting we won't be doing in-place upgrades on gitpod.io until we have mk2. We will be doing in-place upgrades with Gitpod Dedicated using ws-manager's new maintenance mode, but, only after all workspaces reach running (finish starting or stopping).

In other words, the assumption is, restarting ws-daemon won't cause Running workspaces to fail. However, it would definitely cause Starting or Stopping workspaces to fail.

Is there a specific scenario for maintenance mode, where you are worried a restart of ws-daemon could cause a Running workspace to fail?
