### ISSUE TITLE
[GitLab] Docker file is not picked up from branches

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#1161]
Reproduce:
 - create gitlab project
 - create branch
 - commit dockerfile
 - open new workspace and see how it is not used.

**Comment by jankeromnes** [comment]
Thanks a lot @carl-parrish for reporting this bug and @svenefftinge for filing this issue!

**Comment by corneliusludmann** [comment]
Error message is:

![image](https://user-images.githubusercontent.com/24960040/73687938-52d1ad80-46cb-11ea-87d1-672ef9599f2f.png)

**Comment by svenefftinge** [comment]
The fix/change is now deployed in production.
