### ISSUE TITLE
502 error only on self-hosted multi node k3s cluster

### ISSUE THREAD

**Issue by Torsten85** [gitpod-io/gitpod#11615]
### Bug description

Hello,
I've strictly followed the guide on how to setup a self hosted instance on a multi node k3s cluster.

Everything works (dashboard, image build) until the workspace should be opened. All I see is a 502 error.
Investigating a little further, the `ide-proxy` logs 

```
{"level":"error","ts":1658322513.743159,"logger":"http.log.error","msg":"dial tcp 10.43.141.240:4000: i/o timeout","request":{"remote_addr":"23.88.124.221:3976","proto":"HTTP/1.1","method":"HEAD","host":"ide.gitpod.my-domain.dev","uri":"/blobserve/eu.gcr.io/gitpod-core-dev/build/supervisor:commit-2bf93a3f9797e9cc6239cca24e091e392f3071f6/main.js","headers":{"X-Forwarded-Proto":["https"],"User-Agent":["Go-http-client/2.0"],"X-Forwarded-For":["192.168.166.128"],"X-Forwarded-Host":["ide.gitpod.my-domain.dev"]}},"duration":10.512823633,"status":502,"err_id":"q259kc3ur","err_trace":"reverseproxy.statusError (reverseproxy.go:886)"}
```

So it seems like the blobserve service is not responding.

Doing the whole installation process on a single node k3s clusters works as expected.

### Steps to reproduce

Install gitpod on a multi node k3s cluster following the online guide

**Comment by Torsten85** [comment]
Tried the same setup, but without calico and with the default flannel backend... and it works!
Is this a "safe" setup or is calico critically important?

**Comment by aledbf** [comment]
@Torsten85  Flannel has no support for NetworkPolicies

**Comment by corneliusludmann** [comment]
Hi @Torsten85! In the past, I've seen this error very rarely in K3s. There seems to be some kind of race condition with the network policies. When it happens again, could you try to delete the network policy of the `blobserve`? That usually fixed it for me.
