### ISSUE TITLE
slow 'new project' ui widget with large github enterprise instances

### ISSUE THREAD

**Issue by szab100** [gitpod-io/gitpod#11628]
### Bug description

The |Team or persona scope| / Projects / New Project widget has been super slow since the feature's debut when running against large Github Enterprise instances with 10s of thousands of repositories under many-100 git-orgs. Since the current implementation is filtering to show only the repos where the current user has 'admin' permissions only after all pages are fetched and it makes the UI wait for the entire result set to be fetched before returning, the UI is frozen for 5-10+ minutes.

### Steps to reproduce

To successfully reproduce this issue, one would probably need access to a super beefy GH Enterprise instance (1k+ git-orgs with 10k+ git repos).

**Comment by andrew-farries** [comment]
Some good suggestions for performance/usability improvements here: 

https://github.com/gitpod-io/gitpod/pull/11630#issuecomment-1195727935
