### ISSUE TITLE
broken 'new project' widget when octokit/gh-api returns with null item(s)

### ISSUE THREAD

**Issue by szab100** [gitpod-io/gitpod#11629]
### Bug description

GH Enterprise (experienced with v3.3.9) instances (or at least its octokit client library) can contain null elements within the pages returned, therefore this ui widget is broken (basically frozen with no error msg) and preventing self-hosted users from setting up prebuilds for their git repositories.

### Steps to reproduce

This might be related to https://github.com/gitpod-io/gitpod/issues/11628, so reproducing might need a huge gh enterprise server with 10s of thousands of repositories OR this may be related to one or more repositories configured in a certain way on our side when this can occur.

**Comment by geropl** [comment]
Fixed in #11630
