### ISSUE TITLE
Allow more static URLs

### ISSUE THREAD

**Issue by Explosion-Scratch** [gitpod-io/gitpod#11620]
## Is your feature request related to a problem? Please describe
![image](https://user-images.githubusercontent.com/61319150/180776721-c21c4673-02a7-41a4-90d0-6ce1534fde67.png)

## Describe the behaviour you'd like
It would be really nice to have URLs that didn't change for the period that the workspace was open. Maybe multiple workspaces could share a URL when one is dormant as well, for example:
1. When you open a workspace for vuejs/vue it would generate a URL for it, e.g. `vuejs-vue-0f9xzm0f8538.ws-us99.gitpod.io`
2. If you open another workspace on the same repo it would give you a prompt "Change URL to `vuejs-vue-0f9xzm0f8538.ws-us99.gitpod.io`? (with buttons "Stop other workspaces", "Change URL", "Keep URL")

## Describe alternatives you've considered
Typing long gitpod URLs that change randomly into every auth service

**Comment by svenefftinge** [comment]
Thanks for the feedback 🙏 We are tracking this in https://github.com/gitpod-io/gitpod/issues/11620

**Comment by Explosion-Scratch** [comment]
> Thanks for the feedback 🙏 We are tracking this in #11620

?? You just linked this issue

**Comment by gtsiolis** [comment]
@Explosion-Scratch see https://github.com/gitpod-io/gitpod/issues/898. 🏓
