### ISSUE TITLE
[Security] Theia is out of date

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1162]
https://github.com/eclipse-theia/theia/blob/master/CHANGELOG.md#v0150

**Comment by Kreyren** [comment]
afaik gitpod is on stable release with version control so keeping theia on tested version with manual review of new version (which takes time) is sane unless rolling release with more aggressive Quality Assurance (which is more likely to break on production, but also more efficient for maintainance) is used.

**Comment by jankeromnes** [comment]
Thanks for keeping an eye on this @RDIL! FYI we're planning deploying a Theia update tomorrow morning around 06:00 UTC.

**Comment by jankeromnes** [comment]
We've also been testing this release for the past few days. It seems that all features covered in our QA plan are working. Fingers crossed for tomorrow 🤞
