### ISSUE TITLE
minor: Do not promote extension if it's already installed

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1163]
Currently gitpod promotes the gitpod extension even if it's already installed which i find annoying -> Suggesting it to not display if extension is already installed

![image](https://user-images.githubusercontent.com/11302521/73514759-2da31d80-43f3-11ea-8f9b-6cc6560f1965.png)

**Comment by jankeromnes** [comment]
Thanks! I was able to reproduce this.

For some reason in my Firefox Nightly on Mac OS, the Gitpod extension is installed and enabled, but it doesn't seem to do anything (no Gitpod logo in the top right browser bar).

**Comment by gtsiolis** [comment]
This is no longer reproducible. I'm only seeing the prompt when I don't have the browser extension installed. Closing this. /cc @Kreyren @jankeromnes

**Comment by gtsiolis** [comment]
Just run into the prompt a couple of times while having the extension installed. Let's reopen this. @jankeromnes do you know if we no longer check this?

**Comment by LinqLover** [comment]
I don't think this has been resolved?

**Comment by gtsiolis** [comment]
Closing this as it's no longer relevant. :closed_book:
