### ISSUE TITLE
Align in-product changelog version with self-hosted installation.

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#11641]
Self-hosted users should see in-product changelog relevant for their self-hosted installation:
- We should align cadence of changelog with self-hosted releases. 
- In-product changelog should show the latest changelog for the version of self-hosted release.

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/11675

**Comment by loujaybee** [comment]
CC: @lucasvaltl

**Comment by atduarte** [comment]
> In-product changelog should show the latest changelog for the version of self-hosted release.

Now in the Product Sync, we discussed that it should show the changelog related to the version that is installed.

**Comment by lucasvaltl** [comment]
An interesting side-effect of this might also be that users might prompt their admin to update Gitpod - because they see how old the version is that they are on :)

**Comment by akosyakov** [comment]
For now we removed self-hosted changelog from in-product changelog. We will come back on integrating it properly when we have capacity.
