### ISSUE TITLE
Show workspace details in usage list view

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#11640]
_@jldec updated Aug 9_

Workspace details in a dropdown or inline in each row
Let's increase the page size to 50 for now (https://github.com/gitpod-io/gitpod/pull/12122)

**Must haves** 
- usage type: prebuild OR workspace  
- class (large / default)
- workspace ID
- repository context (link)
- started date/time (actual) (https://github.com/gitpod-io/gitpod/pull/12123)
- User ID or name

**Nice to have (ok skip for now) **
- Project (link)
- Stopped date/time (actual)

From [Figma](https://www.figma.com/file/3fdBIQangZxnOPm35uWJZX/Team-usage-view---Iterate-on-UI-based-on-designs%2C-feedback-%2311285?node-id=1347%3A3079)

<img width="811" alt="Screenshot 2022-08-09 at 09 58 08" src="https://user-images.githubusercontent.com/849592/183608690-430b36ff-4cee-4aa4-a383-967869ba7577.png">

NOTE: Other design changes are discussed in separate issue #11953

**Comment by svenefftinge** [comment]
Looks great, some thoughts I had:
 - some of the header titles don't make sense
 - `project` (instead of `'repository`) should be a top-level property
 - `status` doesn't make so much sense here IMHO
 - `session` would probably confuse users more than it helps. Maybe we omit it and work with workspace id plus started time to reference an instance?
 - "Monthly Usage" could be something like "Usage in Period"? Sounds like an average otherwise. Also, I believe we are going to allow more flexibility with the period selection in the future.

**Comment by gtsiolis** [comment]
Some thoughts on the feedback points from bottom to top, while keeping in mind this is still work-in-progress:

> `Last Active` could be just `Date` without using moment but an absolute time stamp. Makes IMHO more sense when looking into things form the past and sort, filtering them.

Good point! 🤝 

> `Monthly Usage` could be something like `Usage in Period`. Sounds like an average otherwise. Also, I believe we are going to allow more flexibility with the period selection in the future.

Agree, we've already changed this to `Total Usage` in https://github.com/gitpod-io/gitpod/issues/11526 which will make more sense once we introduce the option to drill down to usage types like workspaces, prebuilds, etc., see early designs in the [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1657709070799429) (internal). ✔️ 

> `session` would probably confuse users more than it helps. Maybe we omit it and work with workspace id plus started time to reference an instance?

This was inspired from a past discussion in https://github.com/gitpod-io/gitpod/issues/10328#issuecomment-1167113277 with the intent to start exposing users to the concept of session which could be useful also on the workspaces list later. However, I agree we could skip that for now and re-introduce later. 🤝 

> `status` doesn't make so much sense here IMHO

This is related to whether we surface running workspace or prebuilds in this list. So far, the consensus I've seen is to include running workspaces (see. [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1657804885786219?thread_ts=1657803337.186569&cid=C02EN94AEPL) (internal)) but I'm not sure about the current implementation. If we are going to include running workspaces, we'd have to make sure the STOPPED time remains blank or includes an indicator this is still running, etc.

> project (instead of 'repository) should be a top-level property

Good point! This was probably left outside while tackling data structure which is different for workspaces and prebuilds, like the workspace ID v. prebuild ID and workspace owner vs. missing prebuild triggerer (see [relevant note](https://www.notion.so/gitpod/Usage-Based-Pricing-User-Stories-0fc4ac2f2413449b95d70feb60177aaf#28bd55429b9247e8bc23f05c4f41ceed) (internal).

> some of the header titles don't make sense

![homer-simpson](https://user-images.githubusercontent.com/120486/180977282-70a3a740-b163-4523-9341-167b15a3937e.gif)

--- 

Thanks @laushinka for opening this and @svenefftinge for the feedback!

**Comment by gtsiolis** [comment]
Posting a new iteration of the workspaces details, including font color, weight, and alignment on the table in the scope of https://github.com/gitpod-io/gitpod/issues/11527. Changes from the last iteration include the following:

1. Toned down left sidebar elements
2. Surface workspace or prebuild ID on the visible row details
3. Included (optional) project column in the details
4. Experimenting with same color active row and details panel
5. Split user avatar and moved to end of the row just before the toggle icon to provide better visual balance when the avatar is missing for prebuilds.
6. Introduced an icon indicator ⚪ + ⬜ for differentiating workspaces and prebuilds without the need to repeat the type with text while also carrying the icon used in the workspaces list for workspaces' status. 

| Light Theme | Dark Theme |
|-|-|
| <img width="1440" alt="usage-light" src="https://user-images.githubusercontent.com/120486/181765183-809156ac-3e02-4ae8-9324-1ec17e411a92.png"> | <img width="1440" alt="usage-dark" src="https://user-images.githubusercontent.com/120486/181765187-2fe0c34b-c72d-4052-9910-2f74d16c0de7.png"> |

**Comment by gtsiolis** [comment]
Adding below the updated design specs for the usage list after this morning's discussion and pairing session with @laushinka and @jldec. 🍐 

| Usage (List) |
|-|
| <img width="1440" alt="UsageAllInOne" src="https://user-images.githubusercontent.com/120486/183722277-d8eef45e-3b20-47c8-94f0-19c6202277f2.png"> |

See [design specs](https://www.figma.com/file/3fdBIQangZxnOPm35uWJZX/Team-usage-view---Iterate-on-UI-based-on-designs%2C-feedback-%2311285?node-id=1417%3A8970).
