### ISSUE TITLE
[BitBucket] Failed calls to fetch `.gitpod.yml` are silently ignored

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#11649]
### Bug description

https://github.com/gitpod-io/gitpod/blob/main/components/server/src/bitbucket/bitbucket-file-provider.ts#L65

silently ignores (debug) thrown errors and as a result the caller is interpreting it as no config and continues with the project config and eventually inferring one. This results in strange and surprising behavior. We should bail out if this happens.

I found this in the logs:

```
"HTTPError: Too Many Requests
    at /app/node_modules/bitbucket/lib/index.umd.js:15:6585
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
```

### Steps to reproduce

try often enough

**Comment by jmls** [comment]
I would expect that the prebuild process should cancel with a warning message if it cannot access the file

Could we also please 

1) have a way of forcing a prebuild from the UI if one doesn't exist on a branch
2) Be able to invalidate / delete an existing prebuild from the UI - this would then enable us to do #1 ;)

**Comment by svenefftinge** [comment]
> I would expect that the prebuild process should cancel with a warning message if it cannot access the file'

Yes, it should show as errored.
