### ISSUE TITLE
Gitpod won't open any repository

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1164]
Gitpod hangs on `Acquiring Node ... (1/3)` on any repository, reproducable always

timestamp: 3101200955

![image](https://user-images.githubusercontent.com/11302521/73525534-a912c800-440f-11ea-8fac-b660fbdab707.png)

### Steps to reproduce
Open any repository using gitpod

**Comment by meysholdt** [comment]
duplicate of #1165
