### ISSUE TITLE
Gitpod stuck on "Acquiring Node"

### ISSUE THREAD

**Issue by armedcor** [gitpod-io/gitpod#1165]
When opening a Gitpod workspace the loader is getting stuck on the "Acquiring Node..." screen.

Not a network issue as it is affecting a number of students in various locations on different networks.

First instance of the problem reported at 8.14 am GMT.

**Comment by meysholdt** [comment]
Earlier this morning, while working on a fix for the issue, we temporarily paused scheduling for workspaces in the EU cluster. Then, workspaces were automatically schedules in the US.

**Comment by armedcor** [comment]
@meysholdt Lovely, thanks for the quick update.

**Comment by Kreyren** [comment]
works on my end now.
