### ISSUE TITLE
[ws-manager] refactor connectToWorkspaceDaemon to avoid workspaces stuck in Stopping and pod Terminating

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#11664]
### Bug description

We had to rollback and fix `gen56`, due to an issue with connectToWorkspaceDaemon logic in `ws-manager`. It was excessively trying (but unable) to connect to `ws-daemon`.

### Steps to reproduce

@aledbf do you have a reliable way of recreating the behavior we saw? I assume run loadgen with the defaults.

### Expected behavior

Excessive connections should be rate limited or avoided altogether.
Workspaces should reach a stopped phase, and not get stuck in terminating.

### Example repository

n/a

### Anything else?

We should not store the connection in a pool

**Comment by jenting** [comment]
Is it due to #11563?

**Comment by kylos101** [comment]
@jenting no, because of #11517. Refer to #11661 for context.
