### ISSUE TITLE
failed to fetch JetBrains Gateway Join Link.

### ISSUE THREAD

**Issue by mittalyashu** [gitpod-io/gitpod#11671]
### Bug description

Whenever I try to open a workspace using JetBrains Gateway it throws this error

![CleanShot 2022-07-27 at 11 47 29@2x](https://user-images.githubusercontent.com/29014463/181175180-09bddb25-74d1-4f56-9648-125161224f20.png)

### Steps to reproduce

1. Open JetBrains Gateway
2. Connect to Gitpod in browser.

<img width="797" alt="CleanShot 2022-07-27 at 11 49 05@2x" src="https://user-images.githubusercontent.com/29014463/181175411-1b65b632-2ca2-4f60-ae96-d2ddab8d1786.png">

3. Select the workspace and click on "Connect" button
![CleanShot 2022-07-27 at 11 50 15@2x](https://user-images.githubusercontent.com/29014463/181175549-fd2d40e7-1c9a-4a9e-9b0f-0f139e9d4695.png)

**Comment by felladrin** [comment]
Hi @mittalyashu, did it start happening recently? Or has it been like that since the first time you tried using JetBrains Gateway?

Does it happen with any repository? Or only with a specific one?

If you create a new one via [gitpod.new](https://gitpod.new/), does it happen? If so, can you please provide the workspace id (e.g. `gitpodio-empty-van1wjy0byv`) for us to check what could be going wrong?

**Comment by mittalyashu** [comment]
Hi @felladrin,

> Did it start happening recently? Or has it been like that since the first time you tried using JetBrains Gateway?

Yes, it happened from day one I installed JetBrains Gateway.

> Does it happen with any repository? Or only with a specific one?

Nope, it seems to happening for different repositories.

> Do you have dotifles configured on your account? It can happen that they are causing the workspace to fail to start. If so, can you try disabling the dotfiles and check if it solves the problem?

Nope, I haven't used any dotfiles.

> If you create a new one via gitpod.new, does it happen? If so, can you please provide the workspace id (e.g. gitpodio-empty-van1wjy0byv) for us to check what could be going wrong?

Yes, I tried creating an empty workspace and same issue is happening again.
Should I share the workspace ID here or drop an email to support team?

---

A sidenote, I even tried using SSH connection to connect to gitpod workspace even that didn't work for me. I've already drop an email to gitpod support team.

**Comment by felladrin** [comment]
Thanks for providing the details, @mittalyashu.
In the email you sent to support, did you also send the logs from JetBrains Gateway?
If not, could you send them too? Instructions are [here](https://www.gitpod.io/docs/troubleshooting#gitpod-logs-in-jetbrains-gateway).

**Comment by akosyakov** [comment]
Logs or stack trace from logs would be helpful here: https://www.gitpod.io/docs/troubleshooting#gitpod-logs-in-jetbrains-gateway

**Comment by mittalyashu** [comment]
I've reverted back to support team with the logs and stack trace via email.

**Comment by mittalyashu** [comment]
Any update on this issue 🙂

**Comment by mustard-mh** [comment]
This can happen if your default IDE is not `Jetbrains` IDE, which means that if you choose VSCode in your [preference](https://gitpod.io/preferences) when you open the workspace, it's doesn't support to switch to another `desktop IDE` while workspace running, if you want to run the workspace with another IDE, you have to go to your preference and change your IDE before you open the workspace.

**Comment by mittalyashu** [comment]
That's really interesting, it didn't even cross my mind.

Let me give it a try.
