### ISSUE TITLE
Filter the self-hosted changelogs from the in-product changelog

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#11675]
Features such as: https://www.gitpod.io/changelog/june-self-hosted-release should not show in the in-product changelog, we need to find a way to filter out these changelogs so they don't show in VS Code for users (as they're targeted at the installer persona's, not the end user developers). 

CC: @lucasvaltl, @MrSimonEmms 

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/11641

**Comment by lucasvaltl** [comment]
The alternative would be to have a second changelog in the self-hosted docs section that just has notes about every release. I think this is what we had initially, but then moved it to the global changelog to increase visibility.
