### ISSUE TITLE
Implement dropdown for the list of billing months

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#11685]
The dropdown was supposed to have been implemented in [this ticket](https://github.com/gitpod-io/gitpod/issues/11526).

**Comment by gtsiolis** [comment]
We could probably use the link dropdown we currently use in the **[/billing](https://gitpod.io/billing)** section, right?

https://github.com/gitpod-io/gitpod/blob/87321b30053f358dd7ff9953d5c7b7400bfb606b/components/dashboard/src/settings/Billing.tsx#L66-L83

**Comment by gtsiolis** [comment]
Cross-posting a relevant comment from https://github.com/gitpod-io/gitpod/issues/11526#issuecomment-1195297262 containing designs specs for this issue.

> <img width="500" alt="Sidebar" src="https://user-images.githubusercontent.com/120486/180983560-cdf7fcf7-5352-486f-98dd-66761a736044.png">

> See [design specs](https://www.figma.com/file/3fdBIQangZxnOPm35uWJZX/Team-usage-view---Iterate-on-UI-based-on-designs%2C-feedback-%2311285?node-id=1379%3A4710) for detailed padding, colors, font-size, and font-weight in case it helps, @laushinka!
