### ISSUE TITLE
gitpod will open preview but not browser

### ISSUE THREAD

**Issue by robbinsjk** [gitpod-io/gitpod#1168]
I found this [thread](https://github.com/gitpod-io/gitpod/issues/1157) which sounds like the same issue, but I bring it up again because I've seen the "onOpen: open-browser" work in the past, but something has changed because now if I specify "open-preview" that works, but "open-browser" give me the notification "a service is available on port 4200" and the buttons to choose preview or browser.

Has anyone figured out a work-around or a reason for this new behavior? Is it happening to everyone or can some people open the browser successfully?

My repo is [here](https://github.com/robbinsjk/membership-tracking). My .gitpod.yml is:
`github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    addCheck: false
    addComment: false
    addLabel: prebuild-in-gitpod

tasks:
  - before: export NG_CLI_ANALYTICS=ci &&
            npm i -g @angular/cli &&
            ng analytics off
    init: ng analytics off &&
          npm install && npm run build
    command: npm run start

ports:
  - port: 4200
    onOpen: open-browser`

**Comment by JesterOrNot** [comment]
I'll take a look at it

**Comment by svenefftinge** [comment]
Thanks, I have marked #1157 as a bug. As this is a the same I close it as a duplicate.
