### ISSUE TITLE
Improve usage loading spinner style

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11696]
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/pull/11687, a loading indicator (spinner) was added while the data is loading. Thanks, @laushinka and @easyCZ!

Although, there are no concrete guildelines yet on the loading indicators (spinners), we've been using a slightly different pattern for the loading spinner for fetching data-heavy pages.

| Branches | Prebuilds | Usage |
|-|-|-|
| ![gitpod-staging com_t_gitpod_gitpod](https://user-images.githubusercontent.com/120486/181259927-ca99a407-37b3-4b92-b892-5151c8b6b5b3.png) | ![gitpod-staging com_t_gitpod_gitpod_prebuilds (1)](https://user-images.githubusercontent.com/120486/181259943-1bd7f37f-df9d-403b-bd09-2b890dc4fdb0.png) | ![gitpod-staging com_t_gitpod_usage](https://user-images.githubusercontent.com/120486/181259948-e82bd614-4df8-4021-8ca7-d95fa6915f94.png) |

### Proposal

Update the loading indicator (spinner) of the usage page to follow the style of the rest of the instances across the product.

Things to consider:
1. Align horizontally loading spinner with the loading text.
2. Use sentence case instead of uppercase.
3. Use the same top margin from the header.

**Comment by kradchenko** [comment]
Hi @gtsiolis! I would like to work on this issue!

**Comment by gtsiolis** [comment]
You're welcome, @kradchenko! Feel free to mention this issue once you open a pull request to resolve this. 🏓
