### ISSUE TITLE
Gitpod.yml theming section does not support the themes from the extensions and it breaks them.

### ISSUE THREAD

**Issue by studentIvan** [gitpod-io/gitpod#1169]
### Describe the bug
Gitpod.yml theming section does not support the themes from the extensions and it breaks them.

### Steps to reproduce
1. install theme [Dracula official](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula)  `dracula-theme.theme-dracula@2.19.2:YGBEpb4XH7h9BBDzol1CBw==`
2. check the color theme settings - you will see the Dracula theme is available
3. write to the `.gitpod.yml` file:
> ```yaml
> theming:
>     - editor-theme: Dracula 
> ```
4. check color theme settings - you will not see the Dracula theme is available

### Expected behavior
1. vscode color theme sets to Dracula
2. at least Dracula theme still available to use

**Comment by JesterOrNot** [comment]
AFAIK there is no theming property
CC @jankeromnes

**Comment by akosyakov** [comment]
Current theme should be configured in user preferences.

**Comment by svenefftinge** [comment]
Theming is considered a user-specific setting. So you should install the extension in the user's extension space:
<img width="434" alt="Screenshot 2020-02-03 at 08 57 09" src="https://user-images.githubusercontent.com/372735/73635215-4e71aa00-4663-11ea-86c5-25370f60757b.png">

and then you need to activate using the `Preferences: Color Theme` command.
<img width="684" alt="Screenshot 2020-02-03 at 08 57 21" src="https://user-images.githubusercontent.com/372735/73635223-53cef480-4663-11ea-8cc1-35ac7a9a573c.png">

**Comment by svenefftinge** [comment]
We should add that info to the documentation.
