### ISSUE TITLE
Upload of snapshot should check we did not reach the limit

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11709]
### Bug description

![Screenshot from 2022-07-27 20-21-29](https://user-images.githubusercontent.com/161571/181394404-7c38efc7-e612-44b1-9fc7-fdd4cf9a1159.png)
![Screenshot from 2022-07-27 20-22-12](https://user-images.githubusercontent.com/161571/181394408-dcf55351-22cc-43af-9e3c-3402218e164e.png)

### Steps to reproduce

Create multiple workspace snapshots

**Comment by kylos101** [comment]
@aledbf what is the expected behavior here? For example, if we're at the limit, would it remove the oldest one and upload the new one?
