### ISSUE TITLE
[ws-daemon] Unexpected error during workspace dispose 

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11715]
### Bug description

![Jaeger-UI (1)](https://user-images.githubusercontent.com/161571/181407168-9551f5a9-c459-4cf1-be8d-b063c0d1e573.png)

### Steps to reproduce

- n/a

### Expected behavior

Log the error when its encountered and include context (instance ID) so its easier to track down what happened. 

### Anything else?

This is just the first step for now, get some insight to whether this condition is happening, with related context, so we can react later.

**Comment by csweichel** [comment]
This suggests multiple `Dispose` calls. When the `workspace.json` file is gone a second `Dispose` call should be a successful no-op.

**Comment by kylos101** [comment]
@jenting reopened this issue and moved back to in-progress because of https://github.com/gitpod-io/gitpod/pull/12018

**Comment by jenting** [comment]
We need to check the jaeger tracing on the gen63 cluster to see if it still happens or not.
