### ISSUE TITLE
REQUEST: Promote IRC channel

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1172]
As of 03.02.2020 there are 546 issues about which i believe that at least half of them could be solved faster if IRC channel was more maintained.

There is already a `#gitpod` channel on freenode, but only janx is there

Requesting promoting the IRC channel on this repository and assign more gitpod staff there so that those issues can be processed more efficiently while directing the workflow on gitpod documentation for a contribution and community education for self-helping.

**Comment by JesterOrNot** [comment]
See https://community.gitpod.io/

**Comment by Kreyren** [comment]
FWIW there is a spectrum chat, but it sucks

**Comment by Kreyren** [comment]
@JesterOrNot didn't know about that thanks O.o 

Aldo what is it for?

**Comment by JesterOrNot** [comment]
See https://community.gitpod.io/t/welcome-to-the-gitpod-community-forum/7

**Comment by Kreyren** [comment]
Fair enough thanks for info, but IRC is still preferred for something that can be resolved quickly and forum/issues for more complicated issues.

**Comment by Kreyren** [comment]
closing as stale
