### ISSUE TITLE
What is the difference between /ide/bin/remote-cli/gitpod-code and  /ide/bin/helpers/browser.sh

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#11739]
### Objective

Question: 

1. Do we have tech debt here that should be cleaned up?
2. Which one should be documented on https://www.gitpod.io/docs/ides-and-editors/vscode-browser 👍 
3. `export EDITOR` is currently set to `/ide/bin/remote-cli/gitpod-code`

```
gitpod /workspace/website (main) $ cat /ide/bin/remote-cli/gitpod-code
#!/usr/bin/env sh
#
# Copyright (c) Microsoft Corporation. All rights reserved.
#
ROOT="$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"

APP_NAME="gitpod-code"
VERSION="1.69.2"
COMMIT="412debcdce97027594b55f85871951f0aa87c2fc"
EXEC_NAME="gitpod-code"
CLI_SCRIPT="$ROOT/out/server-cli.js"
"$ROOT/node" "$CLI_SCRIPT" "$APP_NAME" "$VERSION" "$COMMIT" "$EXEC_NAME" "$@"
```

```
gitpod /workspace/website (main) $ cat /ide/bin/helpers/browser.sh
#!/usr/bin/env sh
#
# Copyright (c) Microsoft Corporation. All rights reserved.
#
ROOT="$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"

APP_NAME="gitpod-code"
VERSION="1.69.2"
COMMIT="412debcdce97027594b55f85871951f0aa87c2fc"
EXEC_NAME="gitpod-code"
CLI_SCRIPT="$ROOT/out/server-cli.js"
"$ROOT/node" "$CLI_SCRIPT" "$APP_NAME" "$VERSION" "$COMMIT" "$EXEC_NAME" "--openExternal" "$@"
```

**Comment by gtsiolis** [comment]
Removed the **~feedback-issue** label to avoid any confusion as feedback issues are used to gather feedback, suggestions, and experiences from users while iterating on a specific product feature.

Cross-posting also the recently updated issue template description in https://github.com/gitpod-io/gitpod/pull/11244.

**Comment by axonasif** [comment]
Both scripts are calling the same parent script, the only difference is that the `browser.sh` is passing on an additional CLI argument: `"--openExternal"`, which is why I think it's aliased `browser.sh`
