### ISSUE TITLE
Support for MOSH would yield better SSH developer experience

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#11736]
## Is your feature request related to a problem? Please describe

https://mosh.org/ is 🔥 and makes latency disappear. It's a replacement to the SSH command (however it uses SSH as transit) that enables remote terminal applications to roam switching between networks, and supports intermittent connectivity (no more SSH disconnects if working on a eurorail train), provides intelligent local echo and line editing of user keystrokes.

In short _it is amazing_ and rn it's not possible afaik to make it work on Gitpod afaik due to lack of UDP tunneling.

## Describe the behavior you'd like

Improve SSH DX for people who use command line.

Make folks in https://github.com/gitpod-io/gitpod/issues/7489 happy

## Additional context

1. The `mosh` binary needs to be installed into workspace-base.
2. Gitpod would need to add support for forwarding UDP (can we do this yet?)

```
ghuntley@ghuntleys-macbook-pro ~ % mosh 'gitpodio-website-xkazejc68xi@gitpodio-website-xkazejc68xi.ssh.ws-us54.gitpod.io'
client_global_hostkeys_private_confirm: server gave bad signature for ECDSA key 0
Error binding to IP UNKNOWN: Bad IP address (UNKNOWN): Name or service not known: Success



mosh did not make a successful connection to 35.230.81.106:60001.
Please verify that UDP port 60001 is not firewalled and can reach the server.

(By default, mosh uses a UDP port between 60000 and 61000. The -p option
selects a specific UDP port number.)
[mosh is exiting.]
```

**Comment by axonasif** [comment]
Possible duplicate: https://github.com/gitpod-io/gitpod/issues/10440

**Comment by ghuntley** [comment]
Closing as dupe of #10440
