### ISSUE TITLE
Support staging invidual codeblocks with Gitpod's Git UI

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1173]
This is a feature request

As of 030220 it's not possible to stage invidual changes in one file without rewriting the source

For example i have this file and i want to stage either yellow or green (not in the same time), but gitpod only allows merging both of these changes.
![image](https://user-images.githubusercontent.com/11302521/73631354-06e62080-4659-11ea-831a-0f84c9146705.png)

**Comment by jankeromnes** [comment]
Hi @Kreyren, that's a good suggestion, thanks! I also stage individual codeblocks separately quite often.

FYI, the current workaround for this is to use `git` in the terminal, like so:

```
git add -p path/to/file.txt
# stage or ignore each codeblock as desired
```

**Comment by Kreyren** [comment]
workaround noted
