### ISSUE TITLE
Handle context canceled in GCloudBucketRemotegcpStorage.EnsureExists

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11732]
### Bug description

![Screenshot from 2022-07-28 17-11-07](https://user-images.githubusercontent.com/161571/181638273-49a200fc-bba5-46d6-89ae-528bfc7c8c51.png)

### Steps to reproduce

-

**Comment by kylos101** [comment]
Closing in favor of removing historical backups via https://github.com/gitpod-io/gitpod/issues/11709

**Comment by atduarte** [comment]
@
