### ISSUE TITLE
I'm in VSCode how do I switch to SSH from within VSCode?

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#11737]
## Is your feature request related to a problem? Please describe

<img width="1056" alt="2022-07-29_13-24-12" src="https://user-images.githubusercontent.com/127353/181676355-2a071aca-263f-47cc-b60f-f32714485708.png">

## Describe the behaviour you'd like

CTRL+Shift+P -> Connect with SSH -> instructions that I can copy and paste are provided.

ie. the same instructions that are provided on the dashboard.

## Describe alternatives you've considered

Switching development contexts/closing vscode/manually navigating dashboard/clicking on things multiple times...

**Comment by loujaybee** [comment]
Agree this is a pain, especially for users who like to open a terminal or client at the same time as the editor. 

That said, I'll close as duplicate, I think we've got this tracked 

- Issue for native integration in VS Code => https://github.com/gitpod-io/gitpod/issues/9230
- Issue for integration into `gp` CLI => https://github.com/gitpod-io/gitpod/issues/11415
