### ISSUE TITLE
Unable to authenticate GitLab

### ISSUE THREAD

**Issue by SaiLikhith7** [gitpod-io/gitpod#1174]
### Describe the bug

I tried authorizing gitlab to access my repos, but authorization error occured even though credentials are same.

### Steps to reproduce

Step1: In gitpod.io, go to action center, grant read repository permission to gitlab in gitpod.io website and press update. 
Step2: enter your cedentials
You can see that authentication failed

### Expected behavior

Authentication should succeed

**Comment by jankeromnes** [comment]
Hi @SaiLikhith7, sorry about this problem, and thank you reporting it.

Unfortunately, there are many steps in the authentication process, and I'm not able to figure out what exactly went wrong from the information you provided. Also, GitLab authentication works well for me.

Could you please share the exact error message you're seeing? E.g. a screenshot would be perfect.

**Comment by AlexTugarev** [comment]
@SaiLikhith7, I just had a quick look into the server logs. GitLab auth seems to work in general, but not in your case. I see `Failed to fetch user profile` as error, which basically means that the last step of the OAuth flow fails for you. My best guess is that you might have a fresh GitLab account and did non yet accept ToS on their site. Could you please check and try again, please?

**Comment by svenefftinge** [comment]
Would be great if we were able to give users a hint on what went wrong.

**Comment by SaiLikhith7** [comment]
> @SaiLikhith7, I just had a quick look into the server logs. GitLab auth seems to work in general, but not in your case. I see `Failed to fetch user profile` as error, which basically means that the last step of the OAuth flow fails for you. My best guess is that you might have a fresh GitLab account and did non yet accept ToS on their site. Could you please check and try again, please?

Sure, I'll check from my side and revert back. Thanks for the reply.

**Comment by SaiLikhith7** [comment]
This issue is resolved. Thanks for your prompt replies and yes, it's because I haven't setup a GitLab account at time. Now, everything's fine.
