### ISSUE TITLE
Pass extension args in .gitpod.yml

### ISSUE THREAD

**Issue by pyhp2017** [gitpod-io/gitpod#11742]
## Is your feature request related to a problem? Please describe
I'm going to use an extension which needs to pass some settings values to it, it would be perfect we can pass args in the .gitpod.yml in self (it's a vscode extension)

## Describe the behaviour you'd like
Set given values in extension settings automatically

## Describe alternatives you've considered
I used ENV variables for that and changed the extension it self in order to use these env variables (I've set env variables in .dockerfile)

**Comment by axonasif** [comment]
Hi @pyhp2017, do you mean to add configuration to your VSCode `settings.json`?

**Comment by akosyakov** [comment]
Not sure what is request about. It would be better to provide some more concrete example.

**Comment by pyhp2017** [comment]
@axonasif Yes exactly for settings.json
for example some of the extensions use JAVA path for their language server, and I want to pass this value (for extension) which is in settings.json

**Comment by axonasif** [comment]
@pyhp2017 you can do it from your `.gitpod.yml` `init` task, here's an example:

```yaml
tasks:
  - name: Open in chromium
    command: |
      gp await-port 8080 # The websocket port or anything you want to be up
      # Change the parameters here.
      settings_name="python.defaultInterpreterPath" # example param
      settings_value="$HOME/.pyenv/shims/python" # example param
      
      machine_settings_file="/workspace/.vscode-remote/data/Machine/settings.json"
      if ! grep -q "$settings_name" "$machine_settings_file" 2>/dev/null; then {
	      if test ! -e "$machine_settings_file"; then {
		      mkdir -p "${machine_settings_file%/*}"
		      printf '{\n\t"%s": "%s"\n}\n' "$settings_name" "$settings_value" >"$machine_settings_file"
	      } fi
      } else {
           sed -i "1s|^{|{ \"$settings_name\": \"$settings_value\"\n|" "$machine_settings_file"
      } fi
```

**Comment by darthweiter** [comment]
i assume your using vscode for your project.
So you can create a .vscode folder and inside this folder you can create your settings.json file. In this file you can add all your settings specific for your project or your extension. 
push this folder with the file to git and create a new workspace, so you can use your settings
