### ISSUE TITLE
Mixed-up workspace search results

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#1175]
### Describe the bug

I recently typed `cancelDowngrade` into the workspace search input, and got this:

<img width="329" alt="Screenshot 2020-02-04 at 10 56 31" src="https://user-images.githubusercontent.com/599268/73733912-1dfe3e80-473d-11ea-8dae-5a0711293502.png">

As you can see, this is the results from both `cancelDow` and `cancelDowngrade` searches, i.e. the "search results from when I was done typing" got mixed into the "results from when I was still typing", instead of just replacing them.

However, right after taking this screenshot, the results view updated itself and was fixed. So I guess this is a very small & temporary issue.

### Steps to reproduce
1. Search for an existing string in your workspace

### Expected behavior
1. The new results should replace the previous results (i.e. before the full update event that came after my screenshot)

**Comment by jankeromnes** [comment]
@svenefftinge FYI this continues to happen to me occasionally (duplicate search results):

<img width="224" alt="Screenshot 2020-02-14 at 17 28 35" src="https://user-images.githubusercontent.com/599268/74549851-ac9a6900-4f50-11ea-917c-f5f503c3d5b7.png">

**Comment by akosyakov** [comment]
Please use VS Code instead: https://www.gitpod.io/docs/feature-preview/#default-ide It is going to be default rather soon and does not have such bugs in the search view.
