### ISSUE TITLE
A Prebuild Page Shows Nothing Where I Believe Logs Should Show Up

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#11755]
### Bug description

When visiting a prebuilds page there is a large amount of whitespace where I believe logs should show up. This is when you view the prebuild after it has completed.

<img width="1338" alt="Screen Shot 2022-07-29 at 12 43 52" src="https://user-images.githubusercontent.com/405585/181815555-8849ba55-6232-45e9-b6cb-4b55130377ad.png">

When a prebuild is in progress you actually do see logs:

![hnflchahhbaamldp](https://user-images.githubusercontent.com/405585/181815683-74ae9076-b25e-47df-a770-c707846de9a1.png)

### Steps to reproduce

1. Create a project within Gitpod.
2. Perform an action which would trigger a prebuild - usually just making a commit should do the trick.
3. You can check the prebuild while it's going or after. If you check while it's going you should see some logs. If you check after you should see nothing.

Of note I have only replicated this on gitpod.io, I have not tried replicating it on a self-hosted instance but I have a feeling it would surface there as well.

### Expected behavior

I would expect that even after the prebuild has been completed that I see the logs from the prebuild OR that the giant block of whitespace where one would think the logs would show up be hidden if our intention is not to show logs for completed prebuilds.

### Example repository

N/A

### Anything else?

N/A

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3p34a)

**Comment by geropl** [comment]
Hey @jimmybrancaccio , do you have a specific prebuildId / workspaceId to share so we can check the logs?

Or can you invite me to your test project so I can check myself?

**Comment by jimmybrancaccio** [comment]
@geropl Were you able to follow the steps for replication above? Did they not reproduce the issue?
