### ISSUE TITLE
Workspace ends in Completed status

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11759]
### Bug description

In the logs, we can find `workspace in UNKNOWN phase` and then `cannot determine workspace phase` repeats for a long time.

### Steps to reproduce

[example logs in GCP](https://cloudlogging.app.goo.gl/kV6tau6KaVmmBZMZ7)

### Anything else?

![image](https://user-images.githubusercontent.com/1272076/182055345-de0bc160-6fad-46db-9b96-149e790e0f7e.png)

**Comment by kylos101** [comment]
@jenting could you help with this, after testing PVC?
