### ISSUE TITLE
Investigate limit core dump file size dump inside workspace

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#11760]
If a program crashes and generates a core dump file it's possible that if the generated file is too big, it will force the workspace to stop, [see slack thread](https://gitpod.slack.com/archives/C03ND7D4NKX/p1658865272867739?thread_ts=1658584968.171359&cid=C03ND7D4NKX), right now the file size is set to unlimited

Here's a [related thread](https://discord.com/channels/816244985187008514/816246578594840586/1002242027121025034) in discord where a user reported this file being generated when running brew

**Comment by kylos101** [comment]
@jeanp413 we are going to try and resolve this issue via https://github.com/gitpod-io/gitpod/issues/12453. Just wanted to give you a heads up! We'll likely try and do via workspacekit. Internal [link](https://github.com/gitpod-io/gitpod-packer-gcp-image/issues/162#issuecomment-1238744081) for reference.
