### ISSUE TITLE
bug?: Repository not found

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1176]
i'm getting this:

![image](https://user-images.githubusercontent.com/11302521/73759377-2de14700-476c-11ea-8420-ed3d64ac4f13.png)

On instance `bf7f1f18-b6ec-4641-a0af-be70f7b08688`

Affected repo: https://gitpod.io/#https://github.com/Kreyren/icelanders-portage-config/tree/9a9a3fcc9f07dc61826182e64560d1b60e2f3140

**Comment by JesterOrNot** [comment]
It opens for me
![image](https://user-images.githubusercontent.com/50386709/73745911-b682c780-4719-11ea-9b16-e45b3d39c3af.png)

**Comment by Kreyren** [comment]
@JesterOrNot I have a theme so it may not be obvious: 
![image](https://user-images.githubusercontent.com/11302521/73759338-202bc180-476c-11ea-8b1b-0fefb47b86d3.png)

This is happening in the branch tab (op updated)
