### ISSUE TITLE
Custom images without resolv.conf result in broken name resolution

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#11767]
### Bug description

When using a custom image on gitpod, without a resolv.conf precreated, gitpod gives it only root permissions. This therefore prevents the gitpod user to resolve using DNS.
Only with 0644 `/etc/resolv.conf` it works.

(source https://twitter.com/gbraad/status/1550734174906372096?s=12&t=KQ7OxWSNrIfQbfs6P6wvMg)

### Steps to reproduce

Use an image without a `resolv.conf`

**Comment by csweichel** [comment]
@gbraad How would I create such an image? The naive approach fails:

```Dockerfile
FROM fedora:36
RUN rm /etc/resolv.conf
```

<img width="572" alt="image" src="https://user-images.githubusercontent.com/3210701/182136980-d160f47b-5453-4b43-b160-c587c0a96077.png">

**Comment by gbraad** [comment]
The stock Fedora image doesnt have, so using as an image on gitpod would fail.

Docker or podman can do the right thing.

On the repo gbraad/devenv I have an image setup but that does a chmod. Just skip this step to repro.

**Comment by gbraad** [comment]
This issue never got resolved and has been worked around by adding a `chmod 644 /etc/resolv.conf` to a specific Dockerfile for gitpod deployment.

`gitpod/Dockerfile`
```
FROM baseimage
RUN chmod 644 /etc/resolv.conf
```
