### ISSUE TITLE
[PVC] trigger prebuild affected all the users without PVC feature flag enabled

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#11769]
### Bug description

While testing PVC + prebuild, we enable the PVC feature flag internally (without enabling PVC on the project).
![image](https://user-images.githubusercontent.com/49380831/182504198-82a79116-5e1d-4025-a1a3-eaca5ca80ead.png)
![image](https://user-images.githubusercontent.com/49380831/182504210-83168629-3e46-490f-a5a0-0353e638699c.png)

Then force the trigger to prebuild on repos. For example
- gitpod.io/#prebuild/https://gitlab.com/gitpod-io/template-python-flask
- gitpod.io/#prebuild/https://gitlab.com/gitpod-io/template-python-django

After that, all the users open the above repos https://gitlab.com/gitpod-io/template-python-flask, https://gitlab.com/gitpod-io/template-python-django makes the user use the PVC feature as well, which means the PVC and VolumeSnapshot object be created within the cluster. Furthermore, since we internal use the XL pool (PVC size is 50Gi), the normal user can't start the workspace because the user's PVC size is 30Gi which causes the PVC restore failure.

### Steps to reproduce

1. Enable PVC feature flag.
2. Manually retrigger prebuild.

### Anything else?

#7901

**Comment by kylos101** [comment]
@sagor999 I think this was expected, that if a prebuild is done with PVC enabled, workspaces that are created from it will also use PVC? wdyt? In this case, it seems like a manual prebuild was done (as a user), and the feature flag was set at the user level (rather than in config cat or on the project itself in Gitpod).

**Comment by sagor999** [comment]
Yeah. It is kind of working as designed, except that I did not think that manual prebuild (via url link) would be handled by server like normal prebuild, meaning anyone else opening a repo will now use that prebuild.

**Comment by jenting** [comment]
> @sagor999 I think this was expected, that if a prebuild is done with PVC enabled, workspaces that are created from it will also use PVC? wdyt? In this case, it seems like a manual prebuild was done (as a user), and the feature flag was set at the user level (rather than in config cat or on the project itself in Gitpod).

I think it's not expected, but what I did last time was enable PVC on my account, but I did not enable PVC on the project.

**Comment by sagor999** [comment]
@jenting you are right, I think we should not be enabling PVC for prebuild if project does not have PVC enabled. So even though the user has flag enabled, but if prebuild is manually started for the project that doesn't have flag enabled, then it should not use PVC.

**Comment by jenting** [comment]
The PR is deployed by WebApp rather than Workspace, therefore, I changed the it status from Awaiting Deployment to Done.
