### ISSUE TITLE
Firefox: can't scroll in the Terminal

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#1177]
Scroll does not seem to be working.
In fact, there is no scroll bar appearing in the right corner of the screen. 
![image](https://user-images.githubusercontent.com/46004116/73739357-e1940800-4767-11ea-9a9f-2eedbed53bb0.png)

**Comment by jankeromnes** [comment]
Oops, thank you for reporting this very annoying issue @nisarhassan12!

Quick questions:

- If you have other browsers installed (e.g. Chrome), does Terminal scrolling work in them?

- If you visit https://xtermjs.org/ ; then focus on the demo Terminal ; and hit `Enter` many times -- are you able to scroll there?

**Comment by nisarhassan12** [comment]
Thanks! @jankeromnes In Firefox at https://xtermjs.org/ the scrolling in the terminal work fine

https://xtermjs.org/

![image](https://user-images.githubusercontent.com/46004116/73810686-0b493f80-47f9-11ea-9520-804cddb38ec0.png)

Also scrolling on chrome seems to work fine in Gitpod. Scrollbar does appear in Chrome.

**Comment by kevinhq** [comment]
I hope you can make scroll a bit wider on all browsers.

Tried this on Chrome Version 80.0.3987.163 on macos catalina.

![alt text](https://i.ibb.co/PGGt5gX/Screen-Shot-2020-04-11-at-1-33-54-PM.png "Logo Title Text 1")
