### ISSUE TITLE
[ws-manager] finalizeWorkspaceContent takes a very long time sometimes

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#11787]
### Bug description

Example:
![image](https://user-images.githubusercontent.com/18602811/182272561-cfee535e-6e71-4960-896d-3eb0167d2ebd.png)

It is not known why it takes a very long time.
More info in slack thread: 
https://gitpod.slack.com/archives/C03RMAAP7J7/p1659401082578319

I speculate that maybe `m.finalizerMapLock.Lock()` is getting locked by one of the go routines and takes a very long  time to unlock, causing all other threads to get stuck.

### Steps to reproduce

n/a
it just happens all of a sudden.

**Comment by kylos101** [comment]
Potentially resolved in a425468a8baa01154d635a5fb76090b350f558c7 via https://github.com/gitpod-io/gitpod/pull/11784
