### ISSUE TITLE
[ws-daemon] git log --pretty=%H -n 1 failed

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#11789]
### Bug description

<img width="906" alt="image" src="https://user-images.githubusercontent.com/49380831/182316098-741284dd-02fb-4d22-ab60-50c655893c4f.png">

### Steps to reproduce

Probably because the user uses Gitpod to open a repo with an empty commit, and stop the workspace after that.

**Comment by kylos101** [comment]
@jenting how often is this error happening?

**Comment by jenting** [comment]
I queried yesterday Jaeger in us58, about 5 times.

**Comment by atduarte** [comment]
@kylos101 @jenting FYI we have gitpod.new that starts a workspace without any commits. I use it quite frequently actually.

**Comment by jenting** [comment]
> gitpod.new

Cool, thanks for the heads up https://github.com/gitpod-io/empty

**Comment by jenting** [comment]
![image](https://user-images.githubusercontent.com/49380831/182993065-d5af02ca-1515-4e0c-9bc3-f653d0879600.png)

It's a tracing error, and we had a special handle for the `does not have any commits yet` error already https://github.com/gitpod-io/gitpod/blob/ae726f000062f66422a1792fdd69ba6fdaeb58aa/components/content-service/pkg/git/git.go#L304

Therefore, it's fine not to fix it. WDYT? @kylos101

**Comment by kylos101** [comment]
👋 @jenting I am able to recreate this by starting a workspace with gitpod.new, and then stop it.

As a user, I do not get an error on workspace stop, which is good.

As an administrator, however, it is confusing that this trace is seen as an error, which generally means something is wrong. This seems wrong to me, and should be fixed, this way traces that administrators see actually require some sort of action to improve system health. 

I think it should be fixed, to reduce trace errors.

**Comment by jenting** [comment]
Okay, roger that.
