### ISSUE TITLE
Replace column sorting icon in usage page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11783]
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/pull/11774, a new sorting icon was added in the column header.

Cc @laushinka @easyCZ 

The `Arrow` component was used. However:
1. We've been using a different arrow for the sorting icon in columns across the product. For example, see :a: [`/t/gitpod/members`](https://gitpod.io/t/gitpod/members) or :b: [`/admin/teams`](https://gitpod.io/admin/teams).
2. The sorting icon used in the usage based is used for indicating a dropdown button which could be confusing to what to expect when clicking on that area.

| Sorting icon | Dropdown icon |
|-|-|
| <img width="834" alt="Screenshot 2022-08-02 at 9 52 04 AM" src="https://user-images.githubusercontent.com/120486/182311699-3780b36e-80f5-4c20-a1a9-0e62c23de9f0.png"> | <img width="901" alt="Screenshot 2022-08-02 at 9 53 40 AM" src="https://user-images.githubusercontent.com/120486/182311704-5726a918-936e-4e00-86c2-58068f76edce.png"> |

### Proposal

Replace column sorting icon in usage page with the sorting arrow used across the product for indicating column sorting.

**Comment by laushinka** [comment]
@gtsiolis Thank you for the quick response! I had a feeling the icon seemed different but I totally forgot 🤣
