### ISSUE TITLE
[ws-daemon] workspace.Dispose workspace.json: no such file or directory

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#11790]
### Bug description

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/49380831/182317461-2e7e5cc4-c420-44c0-9e80-8d34cc0daec4.png">

### Steps to reproduce

<img width="578" alt="image" src="https://user-images.githubusercontent.com/49380831/182317678-110f7371-5739-451a-b691-998cf7ae2756.png">

**Comment by utam0k** [comment]
@jenting Maybe duplicate https://github.com/gitpod-io/gitpod/issues/11715

**Comment by jenting** [comment]
> @jenting Maybe duplicate #11715

Good catch!
