### ISSUE TITLE
Question: Why can't i build custom dockerfile?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1179]
I'm trying to build following: https://github.com/Kreyren/workspace-images/blob/b965c4dd0e8f680f8e785740f8c9070fd87c54b7/exhered-full/Dockerfile which results in:

![image](https://user-images.githubusercontent.com/11302521/73759171-d9d66280-476b-11ea-8eb6-d776f74bbfc9.png)

Based on gitpod/gitpod-full:latest image i assume that there is some gitpod-specific post-built self-test that fails if apt is not detected? Or do i need to configure dazzle?

**Comment by JesterOrNot** [comment]
The gitpod layer will add the gitpod user for you

**Comment by Kreyren** [comment]
@JesterOrNot 

Keeping only `FROM` flag results in same issue:
![image](https://user-images.githubusercontent.com/11302521/73759914-e9a27680-476c-11ea-936e-d510c19e5248.png)

**Comment by jankeromnes** [comment]
Hm, we seem to be censoring Gitpod layer errors. That's a shame, because it hides explicit error messages and thus prevents users from understanding/fixing the underlying problem.

I'll try to find out more about this.

**Comment by jankeromnes** [comment]
@Kreyren I'm not exactly sure what `exherbo/exherbo-x86_64-pc-linux-gnu-base:latest` is based on, but for Gitpod we currently try to support Debian and Alpine-based images, and Gitpod expects a few things from the image:
- The packages `dpkg-query` and `apt-get` for Debian, or `apk` for Alpine, as well as `bash`
- The commands `addgroup`, `useradd`, `adduser`

Then there are also a lot of language-specific tools in `gitpod/workspace-full`, without which the IDE may not be fully functional, so you may need to debug your image iteratively by trial & error.

Hope this helps!

**Comment by jankeromnes** [comment]
See also https://github.com/gitpod-io/gitpod/issues/318

**Comment by Kreyren** [comment]
> I'm not exactly sure what exherbo/exherbo-x86_64-pc-linux-gnu-base:latest is based on -- @jankeromnes 

it's a docker image provided by exherbo**.org** which is source-based linux distribution with portage-inspired package manager 

> The packages dpkg-query and apt-get for Debian, or apk for Alpine -- @jankeromnes 

Is there a way to disable this check so that it would allow me to build it on a non-apt system? Exherbo is using paludis (https://paludis.exherbo.org/) and different toolchain management.

> Then there are also a lot of language-specific tools in gitpod/workspace-full, without which the IDE may not be fully functional, so you may need to debug your image iteratively by trial & error. -- @jankeromnes 

I am aware of this and i wanted to adapt exherbo image for it, but from what i understand gitpod won't built it for me to make expected development.

> See also #318 and #780 -- @jankeromnes 

Checking

**Comment by JesterOrNot** [comment]
@Kreyren but what *linux* distro is it i.e Alpine, debian, ubuntu, arch linux

**Comment by Kreyren** [comment]
@JesterOrNot Nether of above it's Exherbo Linux using Paludis package manager

Paludis is portage-inspired package manager (gentoo's using portage)

**Comment by JesterOrNot** [comment]
I see, at this time we only support Debian, Ubuntu, and Alpine based images see #813

**Comment by Kreyren** [comment]
@JesterOrNot I would like to self-maintain this in gitpod. Can you add this to "whitelist" or something so that it would allow me to build it?

**Comment by JesterOrNot** [comment]
Sorry, that is not the issue the Gitpod layer needs to be adapted for more information please see https://github.com/gitpod-io/gitpod/issues/813#issuecomment-553424655

**Comment by Kreyren** [comment]
@JesterOrNot I'm reading through, but i don't understand what is the issue is there something on my end that i can do or contribute to or is this something that needs to be done by gitpod on closed-source solution assuming:

> How can the community help bring this support to gitpod? -- https://github.com/gitpod-io/gitpod/issues/813#issuecomment-553426880

**Comment by Kreyren** [comment]
Closed in favor of https://github.com/gitpod-io/gitpod/issues/813
