### ISSUE TITLE
[local preview] Check arch and fail fast on non-supported arch

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#11792]
The local preview image does not work on Macs with Apple Silicon (e.g. M1). We should check the arch at the beginning of the container run and fail fast when the arch is not supported (with a clear error message).

**Comment by lucasvaltl** [comment]
Might be solved by https://github.com/gitpod-io/gitpod/pull/12468 (this is merged but [might actually not work](https://gitpod.slack.com/archives/C01KLC56NP7/p1661776420773429))

**Comment by lucasvaltl** [comment]
Maybe the skateboard here is to always have a warning in the prerequisite check output in the CLI that warns that ARM / M1 macs are not supported. I.e. it is always there, wether you have a ARM based chip or not, those that don't have these chips can ignore this.

**Comment by Pothulapati** [comment]
Merged https://github.com/gitpod-io/gitpod/pull/13123, which adds a confirmation from the user before proceeding but not sure if closing this is the right thing to do. Hence, Reopening it. Feel free to close it if you feel so.

**Comment by lucasvaltl** [comment]
Will close this for now - we have a skateboard fix, let's measure the impact of that and then iterate.
