### ISSUE TITLE
[oauth integration]: support for git repos hosted sourcehut instances

### ISSUE THREAD

**Issue by ajhalili2006** [gitpod-io/gitpod#11796]
## Is your feature request related to a problem? Please describe

Pushing Git objects and Mercurial revisions are currently limited to SSH-only setup and Sourcehut doesn't support
Basic authentication for push (and pull access for private repos), and since `~/.ssh` directory doesn't presist between
restarts, one could write some scripts to presist these keys as base64-encoded tar.gz binary in user-wide variables.

## Describe the behaviour you'd like

Adding OAuth integration support for sourcehut via their OAuth2 and `meta.sr.ht` GraphQL API for adding SSH keys.
The SSH key should be generated during the workspace creation and stored as a persistent SSH key in `/workspace/.gitpod`
directory between restarts and accessible through the plain SSH agent (this can be reused across shell sessions via
[keychain][deb-keychain]).

[deb-keychain]: https://packages.debian.org/bullseye/keychain

### Proposed OAuth2 scopes

```
meta.sr.ht/PROFILE:RO meta.sr.ht/SSH_KEYS:RW git.sr.ht/REPOSITORIES git.sr.ht/OBJECTS todo.sr.ht/TRACKERS todo.sr.ht/TICKETS:RW lists.sr.ht/PATCHES:RW lists.sr.ht/LISTS lists.sr.ht/EMAILS
```

Explaination for each scope:

* `meta.sr.ht/PROFILE:RO` - read-only access to your sourcehut profile
* `meta.sr.ht/SSH_KEYS:RW` - write access to ypur account's SSH keys for adding per-workspace SSH keys
when opening `git.sr.ht` repos through regular `gitpod.io/#` URLs.
* `git.sr.ht/REPOSITORIES git.sr.ht/OBJECTS` - fetch repsotiory data and objects for prebuilds, currently
only lists repositories owned by authenticated user, but in the future this might include repos you can
access through ACLs configured by the repository owner.
* `todo.sr.ht/TRACKERS todo.sr.ht/TICKETS:RW` - managing tickets from sourcehut's ticket tracking service
* `lists.sr.ht/PATCHES lists.sr.ht/LISTS lists.sr.ht/EMAILS` - for reviewing and applying patches from mailing lists

### OAuth2 page preview

[![An screenshot of OAuth2 authorization page from meta.sr.ht, click on image to see it IRL](https://cdn.recaptime.eu.org/ajhalili2006/2022/sr.ht-oauth2-preview-gitpod.png)](https://meta.sr.ht/oauth2/authorize?client_id=17848cd9-a88c-40d7-a4dd-82bf6ae5e3bc&scope=meta.sr.ht/PROFILE:RO%20meta.sr.ht/SSH_KEYS:RW%20git.sr.ht/REPOSITORIES%20git.sr.ht/OBJECTS%20todo.sr.ht/TRACKERS%20todo.sr.ht/TICKETS:RW%20lists.sr.ht/PATCHES:RW%20lists.sr.ht/LISTS%20lists.sr.ht/EMAILS&response_type=code&state=abc123test)

### Documentation

* <https://man.sr.ht/graphql.md> for GraphQL API docs
* <https://man.sr.ht/meta.sr.ht/oauth.md> for implementing OAuth2 for sourcehut instances

## Describe alternatives you've considered

I'm currently working on an DrupalPod-style project (minus the browser extension) for git.sr.ht repos
at <https://git.sr.ht/~ajhalili2006-experiments/hutpod> ([mirror on GitLab for prebuilds][git-mirror])
with the mentioned workarounds for the SSH keys, although it's currently a work in progress right now.

[git-mirror]: https://gitlab.com/ajhalili2006-experiments/hutpod

## Additional context

For context about sourcehut: Sourcehut is an code forge, written in Python with some parts in Golang, licensed under AGPL, and technically each feature is separated into its own repository. While this feature suggestion is for adding OAuth2 support to automate per-workspace SSH key setup, it should be optional since you can send improvements as an email patch to be applied through Git.
(Most of sourcehut features are accessible without an account, usually through email.)

**Comment by ajhalili2006** [comment]
I'll also add an note in this: If the user prefer not to add SSH key for an public or unlisted git.sr.ht repo or not to use SSH to clone a repo, Gitpod should clone the repo via regular HTTPS read-only Git URL.

**Comment by akosyakov** [comment]
@gitpod-io/engineering-webapp i moved to your inbox, since it seems to be about new auth provider.

**Comment by geropl** [comment]
Hey @ajhalili2006 , thx for reporting. However I feel that this is very far from our current trajectory. I will close this to clearly communicate that it's not on our roadmap. Meanwhile the issues stays here for future reference. 🧘
