### ISSUE TITLE
Epic: Improve JetBrains Gateway version updates

### ISSUE THREAD

**Issue by buggtb** [gitpod-io/gitpod#11801]
When updates occur to JetBrains Gateway + related plugins failures can surface in Gitpod in unexpected ways. 

**Solutions worth considering**

1. Support previous versions (e.g. maintain on last stable version)
2. Ensure legible error messages when an upgrade to version related issue emerges 

**Related issues / conversations:** 

1. [Internal conversation](https://gitpod.slack.com/archives/C02CBKZEVS8/p1671106002085899)
2. https://github.com/gitpod-io/gitpod/issues/12089

<details>
  <summary>Original description</summary>
  
### Bug description

Arrived at my desk on Friday morning. Fired up a workspace, saw the intellij loading bar, then it never started. Tried again, nothing, no error or anything just silence.

Transpired I needed a JB Gateway upgrade and then a Gitpod plugin upgrade and the thing came back to life.

### Steps to reproduce

Have an old gateway installed and wait for an update!

### Expected behavior

Somehow users should be notified because it was a pure guess that I needed to upgrade, otherwise it would have failed silently and I wouldn't know what to do.

</details>

**Comment by felladrin** [comment]
Extra info: Screenshot of the error users can face due to the outdated plugin.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/418083/182559237-f7336bb3-eed2-40d3-bc87-e4cf3a677cf6.png">

**Comment by akosyakov** [comment]
@felladrin Is it reported to JB? Could you link a youtrack issue please? 🙏 I don't think we can do anything here on our side.

**Comment by loujaybee** [comment]
Example error message shared by @filiptronicek in [internal thread](https://gitpod.slack.com/archives/C02CBKZEVS8/p1665000894895399)

![image](https://user-images.githubusercontent.com/5528307/194275021-357a5ae0-8157-45cc-8320-01bbf31a1492.png)

**Comment by loujaybee** [comment]
Promoted this issue to an epic + updated the description.
