### ISSUE TITLE
UX issue: option-w can remove important gitpod UI elements

### ISSUE THREAD

**Issue by thefliik** [gitpod-io/gitpod#1180]
### Describe the bug

_This is a UX issue, but it appears to be severe enough that I'm logging it as a bug._

Using Gitpod on a Mac with the Chrome browser, I attempted to close the open VS Code tabs using `option-w`. This appeared to work, as repeatedly pressing the button closed the open tabs. It was only after I was done that I noticed it *also* removed a number of installed extensions, including the file browser and git history.

- On further experimentation, I find that, if an extension is focused (e.g. if you click in the search box of the search extension) and click `option-w`, then the extension is removed. I assume that, as I closed tabs in Gitpod, focus automatically shifted to some of the extensions, at which point I accidently closed them.
- This appears to be intended behavior for VS Code, as right clicking on an extension's icon give you the "close" option with the linked hotkey option-w. The problem here is that A) there doesn't appear to be any way to undo this, and B) because gitpod can't use the VS Code standard `command-w` to close tabs, it seems reasonable that other users may make the same mistake I did 

I can no longer view any files in the workspace, and it's unclear to me how I can recover this workspace (short of creating a new one). The search extension was still present initially, and I could correctly search for files (so I know that the files still exist in the workspace, I just can't view them). However, in diagnosing the issue I also was able to remove the search extension.

Again, I'm basically able to (irreversibly?) remove very key sections of the user interface.

### Steps to reproduce

1. Open a gitpod instance using a Mac and Google Chrome (not actually sure if the OS / Browser matters).
2. Focus an extension
3. Press `option-w` (perhaps `alt-w`)

### Expected behavior

Does not remove focused extension

### Additional Information

n/a

### Example Repository

I think this is reproducible in any repo making use of the default hotkeys

**Comment by thefliik** [comment]
Ah ha! I'm able to re-add the extensions to the view by navigating to `view` > `explorer`.

I still think its a UX error to have both "close explorer window" and "close extension" have the same hotkey, as I think mashing the "close window" command to close open windows is a pretty common occurrence (and removing extensions from the UI will almost never be the intended goal). I'll have to test when I get home, but I don't think the desktop version of VS Code uses the same hotkey for both those commands (otherwise I think I'd have already run into this problem many times).

**Comment by thefliik** [comment]
Part of the problem is also that closing an explorer window in Gitpod returns focus to the explorer extension, when it should shift focus to the next open window (and only when all windows are closed should focus return to the explorer extension).

**Comment by JesterOrNot** [comment]
Gitpod does not use vscode as an editor the open source theia is https://www.gitpod.io/docs/ide/

**Comment by svenefftinge** [comment]
> Gitpod does not use vscode as an editor the open source theia is https://www.gitpod.io/docs/ide/

Yes, and the underyling issue here is that in Theia we have generalized all sorts of widgets. Maybe we should bind the option+w binding to 'close current editor' rather than 'close active widget'.
@akosyakov WDYT?

**Comment by spoenemann** [comment]
A fix is on the way: https://github.com/eclipse-theia/theia/pull/7101

**Comment by akosyakov** [comment]
I believe Theia fix was already deployed to Gitpod for it.
