### ISSUE TITLE
NOT ABLE TO DELETE MY ACCOUNT

### ISSUE THREAD

**Issue by ghost** [gitpod-io/gitpod#11818]
### Bug description

Hi all,

Apologies for posting here, but no other options left for me,

I've been trying to delete my account for gitpod numerous times through all tutorials provided by you online, all without success, and as a result I'm still receiving marketing emails by 'Chad Metcalf ' and others from gitpod.

I would really appreciate it if you could help me deleting my account.

cheers,

### Steps to reproduce

.

**Comment by axonasif** [comment]
Hi @day-by-day22, did you create your Gitpod account from this **GitHub** account?
