### ISSUE TITLE
Some projects have persistent volume claim enabled in settings

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#11822]
### Bug description

Some projects have persistent volume claim enabled in settings, even though that setting is not publicly exposed.
Currently two exist:
https://gitpod.io/admin/projects/5034f903-19f2-44b5-8ed7-d66efc0851fc
https://gitpod.io/admin/projects/e4695d7f-0009-44a6-bd0a-560af9946081

### Steps to reproduce

n\a

### Expected behavior

Need to figure out how they got that flag enabled on them. After investigation, please fix those two projects (by disabling that flag on them).

**Comment by easyCZ** [comment]
Investigated this, details in [(internal) slack thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1659525155271029?thread_ts=1659489106.638469&cid=C02EN94AEPL).

**Comment by sagor999** [comment]
Resolved and affected projects corrected.
