### ISSUE TITLE
Gitpod panics if new commit from a maintainer in contributor's branch is made

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1182]
### Describe the bug

Gitpod gets confused if maintainer is making a change in merge request (or as github calls it pull request) in branch that contributor has granted an access.

![image](https://user-images.githubusercontent.com/11302521/73841050-fe891380-4819-11ea-9398-6563e5f1db8f.png)

### Steps to reproduce

1. Make a new repository
2. Submit a merge request from a different user and allow changes
3. Make a change from the original creator of the repository and notice gitpod having a panic attack

### Expected behavior

Gitpod panicking is not expected

### Example Repository

This is the commit in question: https://github.com/RXT0112/Zernit/pull/37/commits/11c449edd8c3a54b010b9ee5ff011fd0380b0407

But i doubt that being reproducable without having a write access to RXT0112/Zernit thus steps to reproduce provided.

The instance ID is `b00fda77-1999-476f-ae1e-a4879eaaf4fd`

**Comment by nisarhassan12** [comment]
I saw the following in a workspace. I do have push permissions for gitpod-website i.e I just created and pushed to this branch https://github.com/gitpod-io/website/tree/nisarhassan12/link-broken-675 from the same workspace.


![image](https://user-images.githubusercontent.com/46004116/84237488-e2bcb380-ab12-11ea-80c5-c939d1542e29.png)
