### ISSUE TITLE
Forking a repo does not update the remote on the status bar

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#1183]
### Describe the bug

When I fork a repository with my GH account, the status bar still shows the upstream remote, instead of the fork.

### Steps to reproduce

I did the example steps from the Theia workshop repository, more precisely, from here: https://github.com/TypeFox/theia-workshop/tree/exercise-0#create-a-fork

Checking the remotes from a terminal looks good, but the status bar does not get updated unless I open the SCM view.

```
gitpod /workspace/theia-workshop $ git remote -v
origin  https://github.com/kittaakos/theia-workshop.git (fetch)
origin  https://github.com/kittaakos/theia-workshop.git (push)
upstream        https://github.com/TypeFox/theia-workshop.git (fetch)
upstream        https://github.com/TypeFox/theia-workshop.git (push)
gitpod /workspace/theia-workshop $ git branch 
* exercise-0
  master
gitpod /workspace/theia-workshop $ git push -n
To https://github.com/kittaakos/theia-workshop.git
   106d969..d2f786d  exercise-0 -> exercise-0
```

### Expected behavior

The status bar shows my fork and branch instead of the remote after forking.

Expected:
![Screen Shot 2020-02-05 at 13 18 53](https://user-images.githubusercontent.com/1405703/73841308-9c7cde00-481a-11ea-811a-7ba19b308e41.jpg)

**Comment by AlexTugarev** [comment]
I think this is a generic `@theia/git` issue as got the same when fiddling with remotes manually.

**Comment by svenefftinge** [comment]
Isn't it just a missing update on after fork, no?
