### ISSUE TITLE
Do not retry git clone operations when authentication fails

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11845]
### Bug description

```
git clone --depth=1 --no-single-branch https://gitlab.com/XXXXXXX --config http.version=HTTP/1.1 . failed (exit status 128): Cloning into '.'...
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.com/XXXXXXX
```
![Screenshot from 2022-08-03 11-32-30](https://user-images.githubusercontent.com/161571/182648912-bd35d2bd-3e72-4eac-bb1a-c3b8278a955d.png)

### Steps to reproduce

Try browsing to a private repo that you lack access to, such as, https://gitpod.io/#https://github.com/org/some-private-repo

### Expected behavior

If we fail authenticating, do not retry, and share a good message with the user indicating why their workspace did not start.

### Anything else?

[This happened roughly 20 times](https://cloudlogging.app.goo.gl/MvRW8RzCmjVem7xY9) in all clusters over the last week given this period.

Questions:
Why are we retrying on a failed authentication?

**Comment by sagor999** [comment]
@aledbf how do you reproduce this? 
I tried accessing several private repos, on both  github and gitlab, but I am getting an error from server way before it even attempts to create workspace for it. Example:
![image](https://user-images.githubusercontent.com/18602811/182957229-b609b33f-b4b9-4ad6-a33f-6bbb0e60d148.png)
