### ISSUE TITLE
Improve getBlob resilience to remote disconnections

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#11847]
### Bug description

error logs show remote disconnections while pulling from registries `read tcp 10.20.8.196:44218->74.125.199.128:443: read: connection reset by peer ` creating a fatal issue opening workspaces.

### Steps to reproduce

Not sure :smile: 

### Workspace affected

n/a

### Expected behavior

1. No issues. 
2. Have a simple retry mechanism for timeouts and disconnections
3. Have a meaningful metric for timeouts and disconnects

### Anything else?

![image](https://user-images.githubusercontent.com/1272076/182705553-db005314-3553-45e0-ae95-747720442c4e.png)

**Comment by jankeromnes** [comment]
Could this be a regression? (Happened today in production)

```
Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: failed to do request: Head "https://eu.gcr.io/v2/gitpod-dev/workspace-images/manifests/5aca622ec34f841d432659cf2f7b2bd71e25692dc082f29b40af17d6d3740ebc": read tcp 10.100.4.184:51470->66.102.1.82:443: read: connection reset by peer

Unknown Error: { "code": -32603 }
```

<img width="1438" alt="Screenshot 2022-09-15 at 10 36 12" src="https://user-images.githubusercontent.com/599268/190370976-b82c0b04-d619-47d6-867c-baf756aead03.png">
