### ISSUE TITLE
Gitpod proposes to install and use the Chrome extension for better experience, although I have it installed

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#1185]
### Describe the bug

The startup screen suggests installing the Gitpod Chrome extension, although I have it up and running.

### Steps to reproduce

 - Open Theia in Gitpod: gitpod.io/#https://github.com/eclipse-theia/theia using Chrome,
 - See the obsolete suggestion.

![Screen Shot 2020-02-05 at 13 29 57](https://user-images.githubusercontent.com/1405703/73841996-08ac1180-481c-11ea-9d14-beb1c9c2c05e.jpg)
![Screen Shot 2020-02-05 at 13 30 01](https://user-images.githubusercontent.com/1405703/73842000-09dd3e80-481c-11ea-9517-0e87114ae5a6.jpg)
![Screen Shot 2020-02-05 at 13 30 24](https://user-images.githubusercontent.com/1405703/73842001-09dd3e80-481c-11ea-8555-e7efb8663dad.jpg)

### Expected behavior

I do not see the Chrome extension hint, but something else.

**Comment by svenefftinge** [comment]
This has been fixed.
