### ISSUE TITLE
When I try to open a specific workspace, it tells me:Evicted: Pod The node was low on resource: [DiskPressure]. Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by BobHerold** [gitpod-io/gitpod#1186]

**Comment by BobHerold** [comment]
https://b5ba9c52-2ffb-4757-afc2-93ccd69c2f47.ws-us02.gitpod.io/    Will not open;  keeps giving me the same message;     "Evicted: Pod The node was low on resource: [DiskPressure].
Please file an issue if you think this is a bug."        I can open up older workspaces though....

**Comment by BobHerold** [comment]
What is going on here, I'm "dead in the water" for my online course and its milestone project!!

**Comment by BobHerold** [comment]
Its working right now, thank you very much!

**Comment by JesterOrNot** [comment]
Closing then! Please file another issue if this happens again!
