### ISSUE TITLE
TrailBackup sometimes times out

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#11860]
### Bug description

Presumably, the context is canceled here.
https://github.com/gitpod-io/gitpod/blob/ad14c17cbefc48a0acec447bc7c1a2386d23b9e3/components/content-service/pkg/storage/gcloud.go#L499

[Internal Link](https://gitpod.slack.com/archives/C01TNS8EVQT/p1659586154689139?thread_ts=1659585534.075989&cid=C01TNS8EVQT)

### Steps to reproduce

I don't know

### Expected behavior

TrailBackup succeeds successfully.

**Comment by utam0k** [comment]
Maybe we don't need to address this issue because of https://github.com/gitpod-io/gitpod/pull/11807

**Comment by aledbf** [comment]
Closing. #11807 was merged
