### ISSUE TITLE
If we failed within finalizeWorkspaceContent, the pod keeps in Terminating state

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#11861]
### Bug description

If we fail within the function finalizeWorkspaceContent, the pod keeps Terminating because the annotation `gitpod.io/startedDisposal` is there.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/49380831/182775784-a88978b6-c672-4b10-87f2-b7c20aa8ce57.png)
![image](https://user-images.githubusercontent.com/49380831/182775828-e7fe546b-8d8c-4040-8de3-a65d768acdb5.png)
![image](https://user-images.githubusercontent.com/49380831/182808147-bb1b6166-7b02-4b6e-a243-9c9da9d834b7.png)

https://github.com/gitpod-io/gitpod/blob/63f3bb78ae473e34febebcb901094a5026166769/components/ws-manager/pkg/manager/monitor.go#L1275
https://github.com/gitpod-io/gitpod/blob/63f3bb78ae473e34febebcb901094a5026166769/components/ws-manager/pkg/manager/monitor.go#L1413-L1417

### Anything else?

https://github.com/gitpod-io/gitpod/pull/11826#issuecomment-1204655217

**Comment by utam0k** [comment]
I have to use `disposalStatusAnnotation` instead of `gitpod.io/startedDisposal`
