### ISSUE TITLE
Evicted: Pod The node was low on resource: [DiskPressure]

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1187]
### Describe the bug

**Evicted: Pod The node was low on resource: [DiskPressure].
Please file an issue if you think this is a bug.**

### Steps to reproduce

Open gitpod:
https://bcb4047d-a077-43ff-a7e5-66e5cfe5bc9c.ws-us02.gitpod.io/

### Expected behavior

To work :)

**Comment by ColbyWTaylor** [comment]
Hi- I'm experiencing this again:

Evicted: Pod The node was low on resource: [DiskPressure].
Please file an issue if you think this is a bug.

https://f9eeb62a-3c87-4d9e-b284-4cb5d3f34693.ws-us02.gitpod.io/

Upon going to "Workspaces", the project is showing that it is running, however attempting to go back to the project again from that view yields the same result. Any ideas what might be causing this?

**Comment by ColbyWTaylor** [comment]
A quick update- this is still occurring.

**Comment by svenefftinge** [comment]
Thanks for pinging us. We have a fix that we are testing in our staging environment. To be deployed next Wednesday. cc @csweichel

**Comment by svenefftinge** [comment]
We need to do two things here.
1) make sure this doesn't happen in the first place
2) mark errored workspaces as stopped immediately (they currently timeout for an hour and block users)

**Comment by svenefftinge** [comment]
The fix/change is now deployed in production.
