### ISSUE TITLE
Improve Process When User Has Deleted Their Git Provider Account

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#11892]
## Is your feature request related to a problem? Please describe

When a signs up for a Gitpod account but then deletes their account at a Git provider (GitHub, GitLab, BitBucket) and then creates a new account at a the same provider and tries signing up for Gitpod again it fails. This is expected since the account still exists on our end and thus we tell them they already have an account.

I'm somewhat surprised there wasn't an authentication error of sorts when the user tried logging in.

## Describe the behaviour you'd like

I'm not positive because I think there could be some security implications involved here. Giving it a quick thought though perhaps we ask the user to re-authenticate with GitHub? I do think some discussion needs to happen though on the least frictionless but also secure way to present this to users who are in this situation.

## Describe alternatives you've considered

Contact support (a.k.a me) to delete the old account on our end.

## Additional context

N/A

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3pe2y)

**Comment by jldec** [comment]
We don’t have a self-service mechanism to do this atm. Contacting support to delete the old identity is the only way.

It would be nice to have an email-based self-service “account recovery” feature which sends a recovery URL to the existing email address, and deletes the git provider identity in our DB.

That recovery URL would then allow re-authentication, to associate the user with a new OAuth identity.
