### ISSUE TITLE
Trying to add read_repository permission to gitlab integration causes error

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#11894]
### Bug description

Trying to add permission:
![image](https://user-images.githubusercontent.com/18602811/182956394-add46063-2fda-4ae2-99ee-7ce06b8e15f9.png)

Results in:
![image](https://user-images.githubusercontent.com/18602811/182956422-bd106d0b-4cd2-4dd9-b883-e9a197929050.png)

### Steps to reproduce

Go to gitpod settings, select integrations, gitlab and click on edit permissions.

**Comment by gtsiolis** [comment]
@sagor999 I could not reproduce this on `gitpod.io`. 🤷

**Comment by sagor999** [comment]
Hm. That was happening to be on preview environment... odd.

**Comment by sagor999** [comment]
Yup. Works correctly on gitpod.io
Going to close this, maybe it is just a quirk of our preview environments.
