### ISSUE TITLE
A "notes" input when adding a user

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#1189]
Hi! I'm adding users to my Gitpod team manually but after having a lot its hard to know who is who, because I don't remember everyones Github usernames, is it possible to add a "notes" field?

That way I could add their full names, company departments or event the student cohort name. 

![Screen Shot 2020-02-05 at 11 12 32 AM](https://user-images.githubusercontent.com/426452/73859687-6f273480-4808-11ea-9120-bdf4819980f0.png)

**Comment by svenefftinge** [comment]
Would an avatar and a link to the github profile page be sufficient?

**Comment by alesanchezr** [comment]
That is better but not really because they have github default avatars or names, what I really need to know is the class number (cohort number) the user belongs, because some of them already graduated and I need to remove them to open space for more other users instead of adding new team members.

But anyway, I can still do the manual lookup I'm doing, it was just a suggestion because managing lots of users can become cumbersome.

**Comment by JesterOrNot** [comment]
@svenefftinge don't we have an education version of Gitpod

**Comment by svenefftinge** [comment]
Ok, understood. It might be useful for other larger orgs as well.
