### ISSUE TITLE
Build failed: Cannot build base image

### ISSUE THREAD

**Issue by alanassis** [gitpod-io/gitpod#1190]
Error: build failed: cannot build baseimage: Error response from daemon: Error processing tar file(exit status 1: unpigz: skipping: <stdin>: corrupted -- incomplete deflate data

This error occurs when I select the docker image "gitpod/workspace-full-vnc"

### Steps to reproduce

1 - When creating a new workspace, select "Setup Project"

2 - In "Update Docker Configuration" I select "Default + VNC"

3 - In Test Drive, when I click on "Push to Branch & Start Workspace" this error appears

**Comment by JesterOrNot** [comment]
Hello, @alanassis and welcome to the Gitpod community, I was unable to reproduce your issue can you try again?
![image](https://user-images.githubusercontent.com/50386709/73899643-d538a980-4852-11ea-891d-ccc7b7252603.png)

**Comment by alanassis** [comment]
I tried it this morning and it's working, weird ... I don't know what happened before.
