### ISSUE TITLE
Allow dynamic workspace location configuration in .gitpod.yml

### ISSUE THREAD

**Issue by ducphamle2** [gitpod-io/gitpod#11901]
## Is your feature request related to a problem? Please describe

I need a .gitpod.yml file that can dynamically reads the repository name & sets the workspace location to that name. The reason is that I am using a VSCode extension that only shows the UI when there exists a specific file in the repository. However, the default workspace location is `/workspace`, which is not what I want. What I want is: `/workspace/<foobar>`.

At the moment, there is no way we can use any environment variables for the `workspaceLocation`. I can only use hard-coded string, which is frustrating.

## Describe the behaviour you'd like

Users can set their environment variables or use the pre-defined ones like `$GITPOD_REPO_ROOT` to setup the `workspaceLocation`. With this feature, the `.gitpod.yml` file can be reused in different projects without modifying anything.

**Comment by loujaybee** [comment]
Relates to: 

- https://github.com/gitpod-io/website/issues/2368

**Comment by ducphamle2** [comment]
> @ducphamle2 do you have an example repo so I can try to replicate, what extension are you using?

Sure. Here's an example that we use .gitpod.yml: https://github.com/oraichain/oraiwasm

Basically, if we want to jump into the oraiwasm/ dir instead of /workspace/, then we will need to explicitly write the workspace location as /workspace/oraiwasm. As far as I know, there's no other way to set it like: /workspace/$ROOT_DIR, for example.

The extension is built by my team. We have had a workaround for this problem, which is to find the required file from package.json, but hopefully Gitpod can have a variable that can identifies the actual repo name

**Comment by jeanp413** [comment]
@ducphamle2 is there a reason why you have `workspaceLocation: '.'` in your gitpod.yml, if you remove it then vscode will open `/workspace/oraiwasm` by default

**Comment by ducphamle2** [comment]
> @ducphamle2 is there a reason why you have `workspaceLocation: '.'` in your gitpod.yml? if you remove it then vscode will open `/workspace/oraiwasm` by default

I just tested by removing the workspaceLocation, and it worked! Somehow I thought it was mandatory to set a workspaceLocation variable. Thank you!

I think we can close this issue now
