### ISSUE TITLE
Unable to clone repos using ssh

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1191]
Invoking `git clone` on github repository using ssh results in denied publickey

```console
gitpod /workspace $ git clone git@github.com:Kreyrock/Kreyrock.git
Cloning into 'Kreyrock'...
The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,140.82.118.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by svenefftinge** [comment]
What's your suggestion here? I don't think this could work without user's SSH keys.

**Comment by Kreyren** [comment]
> What's your suggestion here? I don't think this could work without user's SSH keys.

I though there is a solution using GitHub API, but that does not seem to be the case.

What about giving end-users few megs of storage assigned as custom homedir that could have these?

**Comment by svenefftinge** [comment]
Yes, that would be possible. The user home however is also configured by the docker build, so we'd need to make sure the suer specific things lie on top. We are close to a solution for that, but it is too early to commit to an actual date.

**Comment by shaal** [comment]
I would like to re-open this issue, and request that the label `meta: never-stale` be added to this issue

**Comment by shaal** [comment]
This solution worked for me:
Clone any additional repositories in a Gitpod workspace via HTTPS in order to push code.

https://community.gitpod.io/t/clone-2nd-repo-and-push-changes-back/3660/2

**Comment by ivansglazunov** [comment]
https://gitpod.io/start/#pink-koi-0vr2oema have same problem, pls help

**Comment by ivansglazunov** [comment]
temporary works solution for me:

```sh
git config --global url."https://".insteadOf git://
git config --global url."https://github.com/".insteadOf ssh://git@github.com/
```

**Comment by Dids** [comment]
> temporary works solution for me:
> 
> ```shell
> git config --global url."https://".insteadOf git://
> git config --global url."https://github.com/".insteadOf ssh://git@github.com/
> ```

In addition to these, I also had to use the following:
```sh
git config --global url."https://github.com/".insteadOf git@github.com:
```

**Comment by putskan** [comment]
@ivansglazunov @Dids  
Is there a way to do it automatically on workspace creation?

**Comment by shaal** [comment]
You can clone repos using https instead of ssh. When using https, Gitpod uses the access you granted it under 'integrations' -> 'git providers'.

Otherwise if you want to use ssh, gitpod needs your private ssh key (which I have as environment variable to my user, and copy it during .gitpod.yml's start task into the correct file location at `~/. ssh/id_rsa`
