### ISSUE TITLE
Human-input Ctrl+C to `read` causes the shell to crash, SIGINT does not

### ISSUE THREAD

**Issue by dangercrow** [gitpod-io/gitpod#11914]
### Bug description

If a human user sends a Ctrl+C to a `read` command awaiting input, the shell crashes.

This appears to be separate to receiving a SIGINT, as indicated by the repro case.

In the repro, I've taken care to provide a machine-driven use case in which a separate shell sends a SIGINT via `kill`, to demonstrate that it appears to be human-driven specifically.

### Steps to reproduce

```
# (See example repo for in-depth repro)
# Open Terminal in browser VSCode (default GitPod setup)
read -p "Please Ctrl+C to crash this shell" # Press Control-C
# Shell has crashed.
```

### Expected behavior

The human-input driven shell should show the same behaviour as the machine-driven shell, which is to not crash.

### Example repository

https://github.com/dangercrow/gitpod/tree/read_ctrlc_repro (or more specifically https://github.com/dangercrow/gitpod/commit/7338c6bd88c534729f48b2a68faa5ada726bd1b0)

**Comment by dangercrow** [comment]
Unstaling.

**Comment by axonasif** [comment]
It might be because of the `direnv` hook shell-modifications (from `nix-env`) on `.bashrc` PROMPT_COMMAND..
