### ISSUE TITLE
Improve spending limit reached modal

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#11927]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/11576, the spending limit reached modal as it comes with some usability issues like multiple primary buttons with the same weight side by side, etc. Cc @AlexTugarev @geropl 

Other things to consider include allowing team owners to ad-hoc increase the spending limit, etc.

Re-posting from a relevant discussion in https://github.com/gitpod-io/gitpod/issues/11404#issuecomment-1190131861:

> 1. Surface a modal blocking workspace start when spending limit is reached
> 2. Possibly allow switching back usage attribution to user's personal account credits.
> 3. Link to billing when usage credits have been used.
> 4. Potentially, show a non-dismissible alert component in the dashboard for team owners when visiting pages in a team that spending limits have been reached and team members are blocked from using the product.

> See also relevant docs[[1](https://www.notion.so/gitpod/Usage-Based-Pricing-User-Stories-0fc4ac2f2413449b95d70feb60177aaf#bd4ee25f830b478f82fd1faf4dd3ffc7)][[2](https://www.notion.so/gitpod/Usage-Based-Pricing-User-Stories-0fc4ac2f2413449b95d70feb60177aaf#e4ae9ada8d714ee5bc1b3d52d3a5d978)] (internal).

> Later on, we could ad-hoc allow resolving the issue for individuals users by allowing them to add a credit card on the fly to enable billing and continue with the workspace start. 💡

### Designs

| Modal for team members | Modal for team owners |
|-|-|
| <img width="1440" alt="Links-1" src="https://user-images.githubusercontent.com/120486/183496371-eb997eea-d61a-419d-94d9-5acc052f6bb9.png"> | <img width="1440" alt="Links" src="https://user-images.githubusercontent.com/120486/183496377-f4aacafe-b63e-4020-8e81-c59807c1ae1e.png"> |

In parallel with the updates in https://github.com/gitpod-io/gitpod/issues/11498 (see https://github.com/gitpod-io/gitpod/issues/11498#issuecomment-1205281686) we could reuse the same elements to provide ad-hoc resolution by changing the billing account within this blocking modal.

| Modal with ad-hoc resolution |
|-|
| <img width="1440" alt="Disabled" src="https://user-images.githubusercontent.com/120486/183496760-bb6397ec-f5e4-45ec-864c-8982b215b5ff.png"> |

See [design specs](https://www.figma.com/file/gbcSeypnvZdBlVHqTFKfkY/Improve-spending-limit-reached-modal-%2311927?node-id=1501%3A793).

**Comment by jldec** [comment]
Some thoughts about this:

Changing the billing account is probably not the most helpful suggestion in this scenario since users are unlikely to be members of multiple billing accounts. 

I recommend simply pointing the user to their own billing settings (at `/billing`) where they can configure their own billing or select a different billing account if that actually exists.

> Configure usage-based billing in your [billing settings](/billing) 

(Additionaly, in the case when the spending limit was hit for a team billing account)

> or contact the team owner of [team x](<link to team>) to increase the spending limit.

**Comment by gtsiolis** [comment]
Posting below the designs following the specs described [above](https://github.com/gitpod-io/gitpod/issues/11927#issuecomment-1210813607).

| Usage Limit Reached |
|-|
| <img width="1440" alt="UsageLimitReached" src="https://user-images.githubusercontent.com/120486/184115039-97782719-ed5e-4a96-9492-a0780798d3e8.png"> |

See [design specs](https://www.figma.com/file/gbcSeypnvZdBlVHqTFKfkY/Improve-spending-limit-reached-modal-%2311927?node-id=1502%3A102).
