### ISSUE TITLE
REQUEST: Allow closing ports on demand

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1192]
Currently it doesn't seem that it is possible to close ports on demand:
![image](https://user-images.githubusercontent.com/11302521/73905735-a8ab7e80-48a0-11ea-9f76-f94e326f2807.png)

**Comment by svenefftinge** [comment]
You mean to not expose or to stop the process?

**Comment by Kreyren** [comment]
> You mean to not expose or to stop the process? -- @svenefftinge 

i'm not sure what you mean so:

If i expose a port i want to have the ability to change it's status on `not exposed` on demand

It would also be a nice feature to expose ports on runtime where gitpod only allows to expose 5900 and 35900 by default where adding additional ports i not possible unless something outputs in them.

**Comment by svenefftinge** [comment]
We are going to change this soon so that the 'unexposed' state means: only accessible to users having access to your workspace. That is only you unless you have shared the running workspace. 
'Exposed' means accessible publicly (without need to login, etc.).

**Comment by svenefftinge** [comment]
And with that it will be possible to change the un-/exposed state in the ports view, of course.

**Comment by Kreyren** [comment]
Assuming `reporter-feedback-needed` i find that as a sufficient solution.

**Comment by akosyakov** [comment]
Ports are always exposed by privately now. You can change the visiblity to public to share them with someone.

**Comment by ysgurjar** [comment]
Hi, I use Ctrl + C to from "port running terminal" to kill it.

**Comment by TulaUnogi** [comment]
> Hi, I use Ctrl + C to from "port running terminal" to kill it.

But sometimes when you get an error in a code the port turns into a "Schroedinger's port"- it is marked as "open" but not really working and you can't kill it with ctrl-c either.
