### ISSUE TITLE
Cannot initialize workspace

### ISSUE THREAD

**Issue by Ananthavijay** [gitpod-io/gitpod#1194]
### Describe the bug
I get an error: "cannot initialize workspace"

````
cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/49b69de4-5514-45cf-bacf-89a183043a2e: no space left on device
Please file an issue if you think this is a bug.
````
Even though I don't have any workspace, this error pops

### To Reproduce
Create a workspace with any repository from GitHub and wait for it to start up

### Expected behaviour
The repository should be cloned and files ready in the workspace.

**Comment by csweichel** [comment]
Hi,

thank you for bringing this to our attention. I have cordoned the faulty node, so things should work again as expected.

Sorry for the inconvenience.
