### ISSUE TITLE
Add copyable SSH password field to SSH "Access token" panel

### ISSUE THREAD

**Issue by WilliamIPark** [gitpod-io/gitpod#11955]
## Is your feature request related to a problem? Please describe

It's awkward to dig about the current input if you're just looking for your SSH password, for entry into VSCode for example.
![Screenshot 2022-08-08 at 10 07 55](https://user-images.githubusercontent.com/445688/183411449-416e6ef4-432f-413f-8e90-029286b31b66.png)

## Describe the behaviour you'd like

An additional copyable input below with just the SSH password. 

## Additional context

I know this a bit of a UX nitpick, but my hope is it wouldn't be too much effort to add in.

**Comment by loujaybee** [comment]
Thanks for raising @WilliamIPark !

**Comment by loujaybee** [comment]
Related feedback from Discord: 

![image](https://user-images.githubusercontent.com/5528307/184834056-c9d5aeb8-9b82-4319-8099-1ef0446dcc71.png)

**Comment by Phxntxm** [comment]
I don't really want to post a whole new issue for it, as I just have a question regarding this specifically so sorry if this isn't the best place but... why is access token even needed? We're using a private and public SSH key now, that typically REPLACES password entry. Why this extra step? It seems superfluous and disruptive to me

**Comment by axonasif** [comment]
@Phxntxm the access token method can be handy for just checking out a workspace for once on something like Android+[Termux](https://github.com/termux/termux-app) for example. And it can have other usecases as well :smile:

**Comment by Phxntxm** [comment]
> @Phxntxm the access token method can be handy for just checking out a workspace for once on something like Android+[Termux](https://github.com/termux/termux-app) for example. And it can have other usecases as well smile

Sure sure, I probably wasn't clear sorry... I'm not asking "why is access token necessary" I am asking "why is access token necessary when using the new Gitpod extension SSH connection, which uses private and public SSH key pairs."

I have reread the original post, and now realize this has nothing to do specifically with that, and now I feel stupid, and this probably should have been a new issue.... oops, my bad. I came to check out these issues with that thought specifically in mind, so I sort of read this interpreting "ssh" as that specifically, sorry for the confusion... I can post this question in a new issue if that's wanted :sweat_smile:

**Comment by loujaybee** [comment]
Will move to backlog for now, still important that we make this change as it improves usability for SSH users and for VS Code Desktop. However, we're still closing off some other work, so we'll come back to this one soon.
