### ISSUE TITLE
Design updates for usage list view

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#11953]
- better separation of user avatar
- distinguish more effectively between prebuilds and workspaces
- refine sidebar elements
- improve dark/light mode
- color improvements

See [design specs](https://www.figma.com/file/3fdBIQangZxnOPm35uWJZX/Team-usage-view---Iterate-on-UI-based-on-designs%2C-feedback-%2311285?node-id=1347%3A3079).

**Comment by gtsiolis** [comment]
Moved this to **[Product Design / Scheduled](https://github.com/orgs/gitpod-io/projects/29/views/4)**. 🥯

**Comment by gtsiolis** [comment]
Closing this as all points mentioned above have been resolved except the one regarding the sidebar elements which is being tracked in https://github.com/gitpod-io/gitpod/issues/11685.

Future improvements on the sidebar elements include https://github.com/gitpod-io/gitpod/issues/13288, https://github.com/gitpod-io/gitpod/issues/13290, etc.
