### ISSUE TITLE
Billing period navigation (by month) appears incorrect in usage list view 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#11959]
Clicking on the previous month (July) shows a list starting "14 days ago" even though it is only Aug 8.

<img width="1419" alt="Screenshot 2022-08-08 at 13 29 02" src="https://user-images.githubusercontent.com/849592/183419289-61ca3e3f-2315-4e2a-a193-bfe99edd2666.png">

**Comment by geropl** [comment]
I think this has been resolved, right? 🤔
