### ISSUE TITLE
Workspace class appears empty for default workspaces in usage list view

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#11956]
From https://gitpod.io/t/gitpod/usage (internal)

<img width="1011" alt="Screenshot 2022-08-08 at 12 30 53" src="https://user-images.githubusercontent.com/849592/183411880-f7aee038-0620-4186-9b49-4df4bfc9e8f3.png">

**Comment by Furisto** [comment]
This is fixed with https://github.com/gitpod-io/gitpod/pull/11957
![usage](https://user-images.githubusercontent.com/24721048/185881629-6de3b534-14e8-47cc-bde6-0e163c1ffbdd.png)
