### ISSUE TITLE
The workspace integration tests failed because of grpc timeout

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#11979]
### Bug description

Below is a snippet of the end of most werft jobs from [#workspace-jobs](https://gitpod.slack.com/archives/C03E52788SU), where if you open the related werft job run for any run that failed with `Failed at preparing the preview environment`, you'll see the following at the end of the log entry for `build preview environment / build failed` step:

```
Ensure VM Readiness        Ensuring VM is ready for deployment
[Waiting for VM readiness] Wait for VM readiness
Error: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR
tip: There seems to be a problem with your werft installation - please get in contact with whoever is operating this installation.

build failed
```
[internal link](https://gitpod.slack.com/archives/C032A46PWR0/p1656483640055099)

### Steps to reproduce

Start [workspace integration tests](https://github.com/gitpod-io/gitpod/blob/main/.werft/workspace-run-integration-tests.yaml) (try trigger nightly as a werft job, but can also be run manually).

### Expected behavior

Pass all workspace integration tests, or at least, stop timing out on the RPC exception, so we can see test failures.

**Comment by kylos101** [comment]
:wave: @mads-hartmann I just ran the job, it failed and I'm unsure why. [Slack convo here](https://gitpod.slack.com/archives/C03E52788SU/p1660250303744999?thread_ts=1660225661.452749&cid=C03E52788SU).
