### ISSUE TITLE
Self Hosted EKS Guide install script fails

### ISSUE THREAD

**Issue by DirkChau** [gitpod-io/gitpod#11970]
### Bug description

Running `make install` gives error `❌  Addons failed: Error: The stack named Addons failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Received response status [FAILED] from custom resource. Message returned: Error: b'Release "metrics-server" does not exist. Installing it now.\nError: chart "metrics-server" version "5.10.10" not found in https://charts.bitnami.com/bitnami repository\n'`

### Steps to reproduce

Run `make install`

### Workspace affected

N/A

### Expected behavior

A successful installation.

**Comment by corneliusludmann** [comment]
Hi @DirkChau! Thanks for reporting your issue. I would like to let you know that we deprecate the EKS guide repo soon in favor of [this guide](https://www.gitpod.io/docs/self-hosted/latest/reference-architecture/single-cluster-ref-arch). Please try it out and let me know if you have any issues with that guide.

Closing this for now. Feel free to create an issue (or even better head over to https://gitpod.io/chat) in case you have any issues with the new guide.
