### ISSUE TITLE
bug: Gitpod editor does not show symlinks

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1197]
![image](https://user-images.githubusercontent.com/11302521/74018386-20a7a080-4996-11ea-9a46-566f75bbab39.png)

**Comment by akosyakov** [comment]
Please switch to VS Code: https://www.gitpod.io/docs/feature-preview/#default-ide

It displays symlinks properly and going to become the default editor rather soon.

<img width="312" alt="Screenshot 2021-03-18 at 11 23 40" src="https://user-images.githubusercontent.com/3082655/111611211-7dea6400-87dc-11eb-80e1-9e5168e4d16c.png">
