### ISSUE TITLE
REQUEST: Gitpod to support modelines?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1198]
[Vim](https://www.vim.org/) allows editor configuration per file by using [modelines magic](https://vim.fandom.com/wiki/Modeline_magic) which allows end-user to add comments alike:
```c
// vim: noai:ts=4:sw=4
   -or-
/* vim: noai:ts=4:sw=4
*/
   -or-
/* vim: set noai ts=4 sw=4: */
   -or-
/* vim: set fdm=expr fde=getline(v\:lnum)=~'{'?'>1'\:'1': */
```

which allows to set indentation and various other options per file

**Comment by JesterOrNot** [comment]
I don't know if this will help but take a look at https://marketplace.visualstudio.com/items?itemName=vscodevim.vim

**Comment by Kreyren** [comment]
@JesterOrNot vim extension has performance issues https://github.com/gitpod-io/website/pull/512/commits/0382ca746baf10823ba2faef71836097c4ce9e8b

I would rather propose custom modelines recognized for gitpod instead of using vim modelines.
