### ISSUE TITLE
Unable to create a workspace from a private image from dockerhub

### ISSUE THREAD

**Issue by Keith-Hon** [gitpod-io/gitpod#11982]
### Bug description

Reference: https://github.com/gitpod-io/gitpod/pull/8550#issuecomment-1208225358

Using a private image from dockerhub will cause the below error

![Capture](https://user-images.githubusercontent.com/23226987/183557728-82d87e22-3a33-433e-a656-6f07e3f0a624.png)

### Steps to reproduce

1. Build a docker image from one of the gitpod workspace images, e.g. gitpod/workspace-full:2022-06-20-19-54-55
2. Publish that image with scope to dockerhub, so that the image is private
3. Create a new git repository and edit .gitpod.yml with reference of the private image
4. Start a new workspace on such repository
5. Error occurs

### Expected behavior

It should successfully start a new workspave with a private docker image from dockerhub

### Anything else?

Related Discord discussion: https://discord.com/channels/816244985187008514/1006133715409313882

**Comment by kapke** [comment]
Hi! I'm playing with gitpod and I have run into exactly the same issue. I have a private repo and a private dockerhub image. Gitpod cannot build/load the image because of exactly the same error as in the original post. 
Sadly, neither the repo or image can be made public.

**Comment by axonasif** [comment]
Is your repo private as well @kapke?
<img width="802" alt="Screenshot 2022-08-25 at 10 07 56 PM" src="https://user-images.githubusercontent.com/39482679/186715993-a47e3fbd-6deb-4841-ae8a-675b63a0fc11.png">

**Comment by kapke** [comment]
@axonasif Yes, it is. Will Dockerfile like 
```
FROM my-private-image
```

work in such case?

**Comment by axonasif** [comment]
No, I mean to put your dockerfile contents into that file, souring it externally with `FROM` would not help for now.

**Comment by kapke** [comment]
I see. Sadly this is way beyond what's easy for the environment I need. 
On the other hand, Nix with flakes does the job just fine in my case, I looked at Docker mostly to have the workspace load instantly instead of having to wait couple of minutes for Nix to fetch everything.

**Comment by kylos101** [comment]
@Keith-Hon @kapke if you'd like to try this again, please try [these docs](https://www.gitpod.io/docs/configure/workspaces/workspace-image#use-a-private-docker-image), and if you continue to have trouble let us know? Happy to reopen the issue.
