### ISSUE TITLE
[bootanimation] Add a fallback in case WebGL is not supported

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#120]
As a user I see a blank screen for while the workspace is started. 

The error `This browser does not support WebGL` is reported on the JS console.

This appears to happen on older machines running latest Chrome and is probably related to the graphics chip. 

**To Reproduce**
Start Chrome like this: `open -a "Google Chrome" --args  -disable-webgl`

**Expected behavior**
Even if WebGL is not supported/enabled, I want to use Gitpod ❤️

**Comment by geropl** [comment]
Today I have the same behavior on each first start of a workspace with Firefox. Needs a `F5` to fix but very annoying.

**Comment by jankeromnes** [comment]
> Today I have the same behavior on each first start of a workspace with Firefox. Needs a F5 to fix but very annoying.

Strange, I didn't see any blank screens on my Firefox (Nightly) today on Mac.

**Comment by geropl** [comment]
@jankeromnes Goneafter reboot. I guess a random graphics deivce/driver thing.
