### ISSUE TITLE
Can Gitpod spawn vms with specified specs CPU / GPU / RAM 

### ISSUE THREAD

**Issue by frosk1** [gitpod-io/gitpod#12013]
### Objective

How can this text written on the homepage of gitpod be true?

"Code anywhere, on any device
You no longer need an over-powered laptop to code, Gitpod works just as smoothly on a Chromebook or iPad. All you need is a browser."

When gitpod does not offer a capability of spawning vms / container with specified CPU /GPU or RAM?

If gitpod only offers hard limit environments, some tasks can not be developed, build, tested etc.

Please elaborate.

**Comment by gtsiolis** [comment]
Hi @frosk1! We're actively working on enabling more workspace classes which is planned for this quarter, see https://github.com/gitpod-io/gitpod/issues/8261.
