### ISSUE TITLE
Python complains about missing dependencies

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1201]
### Describe the bug
I have gitpod install my dependencies, **mypy included**, but every time I open my workspace, I am greeted with the fun 
![Screenshot 2020-02-07 at 8 29 17 AM](https://user-images.githubusercontent.com/34555510/74033407-0bc21180-4984-11ea-80e9-74e1162a839f.png)

this happens with flake8 sometimes aswell but not as often.

### Steps to reproduce

Disable default python linters, enable mypy && flake8
Have it preinstall
open py workspace
open py file

### Expected behavior
shouldn't popup

### Example Repository
git@github.com/cakebotpro/cakebot works

**Comment by svenefftinge** [comment]
Can you share how you have put it on the path? It seems as the python extension doesn't see it.
cc @AlexTugarev

**Comment by RDIL** [comment]
Pip handles that stuff

**Comment by AlexTugarev** [comment]
I just tried with `github.com/cakebotpro/cakebot`, and here is what I saw:
* initially the python extension has no interpreter selected
  * I've selected `3.7.6 pyenv`
* 'opened a python file
* `F1 > select linter` and chose `mypy`
  * though I didn't see any editor decorations, a new folder appeared in the workspaces named `.mypy_cache`

>  It seems as the python extension doesn't see it.
☝️ would not be working, if this would be the case.

@RDIL you write `Disable default python linters, enable mypy && flake8`, is there more to this?

**Comment by AlexTugarev** [comment]
@RDIL the message about missing `mypy` is only shown if you select `python2` as interpreter for the python extension. 
<img width="999" alt="Screen Shot 2020-02-10 at 07 56 50" src="https://user-images.githubusercontent.com/914497/74127496-1d512680-4bdb-11ea-8002-edbf7a38ee70.png">

Is this the case in your setup?

I also double-checked that the `mypy` package is installed via config as wanted:
<img width="1111" alt="Screen Shot 2020-02-10 at 07 59 33" src="https://user-images.githubusercontent.com/914497/74127624-686b3980-4bdb-11ea-8a7e-fc3bd9b38bd3.png">

This looks fine, and works nicely with `python3` as interpreter.

**Comment by RDIL** [comment]
No, I have jedi enabled...

**Comment by RDIL** [comment]
Hey @AlexTugarev,
Terribly sorry for the delay, but now I'm ready to get this fixed.

I have mypy and flake8 enabled on my user-level, but since this is an organization project I'm not sure if it will apply.

I have flake8 and mypy enabled in my repos `.theia/settings.json`, and one of my startup tasks makes sure they are installed, however when I open a Python file for the first time, I am greeted with the error.  

The mypy-cache DOES however show up for me - meaning mypy is running but theia thinks it isn't present.

Clicking on install opens up a python tab in the console, where pip alerts me that each of the requested requirements are installed and up-to-date.  

Since my last message, .theia is now committed but the issue still persists.

Also what is the difference with Jedi?? - everybody keeps saying to turn it off but its on by default so I'm confused!

**Comment by RDIL** [comment]
One more thing - for current linter it says "multiple in use" - flake8 is a linter but mypy is a static analysis engine which I wouldn't technically call a "linter", but it seems theia does.

**Comment by RDIL** [comment]
Hey @AlexTugarev,
I've confirmed that moving off workspace-full and onto better-wsfull has made the popups come up less frequently, but they still happen.  Honestly I am just fed up with theia's python integration

**Comment by jankeromnes** [comment]
Hey, many thanks for the feedback @RDIL, and sorry for the bad experience.

If these issues are caused by Theia's Python integration, would you know a better alternative? E.g. a VS Code extension that's known to work great, in particular with Pyenv?

Otherwise, we should probably move forward with some changes you proposed, e.g. using system Python3 instead of Pyenv if that improves things (unfortunately, I can't make any promises there, as we'd have to extensively test any alternative setup to ensure that it works great/better for most Gitpod Python projects out there -- but I'm happy to try anything).

**Comment by RDIL** [comment]
@jankeromnes I have reconfigured better-wsfull to use python as a base image, which has quite a few upsides.  As for how to fix this, I have never seen a good python extension for vscode. I think this one is alright, but needs a few things tweaked. I’m going to open an issue upstream in vscode-python to complain. 

If they aren’t willing to fix it, maybe we can try to convince Theia to apply .patch files that fix it during the build.
