### ISSUE TITLE
[ws-manager] The container could not be located when the pod was terminated

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#12021]
### Bug description

We have observed in production, in preview-env and integration tests an error that results in the status of the workspace being "The container could not be located when the pod was terminated". We check the related GCP log and there is no data loss happened.

### Questions

- Is "The container could not be located when the pod was deleted.  The container used to be Running" also happening?
  > Yes! Check this [GCP log](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-01-04T05:22:19.977165741Z;query=%22workspace%20failed%22%0Atimestamp%3D%222023-01-04T05:22:19.977165741Z%22%0AinsertId%3D%22domvix05xh6189z6%22;timeRange=PT3H?project=workspace-clusters).
- Is this only happening on stop? Milan's scenario seems to indicate otherwise.

### Plan

1. [x] Verify whether as it is now there is data loss when this error occurs
2. [ ] Check Milan's case to understand if it happened during the running workspace phase.

<details>
  <summary>Old description</summary>

  We try to get the status of the pod, when is not running anymore, at a time we are not sure.  [logs](https://cloudlogging.app.goo.gl/EALr6Wbfh8q4VNBS7)

Impact to the user: 
(1) the workspace is generally left in a failed state. Users can try to restart, as failed is a terminal phase.
(2) user data may be lost.

This error message(`The container could not be located when the pod was terminated`) comes from kubelet.
https://github.com/kubernetes/kubernetes/blob/4aa451e8458a7cbf78ed464e9e47e87d424541ce/pkg/kubelet/kubelet_pods.go#L1810-L1817

Potentially related with this Kubernetes bug: https://github.com/kubernetes/kubernetes/issues/104107

### Steps to reproduce

I don't know

### Expected behavior

There isn't this error message in production.

### Anything else?

This has been happening in `gen59`, `gen60` and `gen61`, too. [Logs.](https://cloudlogging.app.goo.gl/86UASif6LeCtkS8T9)

### Definition of done

Let's spend some time researching if this is a Kubernetes bug, or in fact could be caused by other circumstances too. Please timebox at 2 hours, after which please share results with the team in Slack, so we can socialize next steps. 

Why research? Because the workspaces impacted by this bug end with a Failed status. cc @geropl I'm not sure if a workspace ending in a failed status will negatively impact UBP...assume not, but, wanted to check.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3sf4a)
</details>

**Comment by kylos101** [comment]
@utam0k good find, I [see](https://cloudlogging.app.goo.gl/dKE8L2g1oYNC1Jxu6) with `gen60`, too.

**Comment by kylos101** [comment]
Still seeing in `gen63`, cc: @sagor999 for posterity, I realize you're working other things, but, not sure if this is related. [gen63 Logs.](https://cloudlogging.app.goo.gl/tS3J288vKWVzyZk47)

**Comment by sagor999** [comment]
Hm. I looked at one instance that had this error: `9e368af4-a27a-48d8-9c37-19dffb785c11`
and inspected traces for it (eu63) but it did not show any errors. Furthermore, it showed that workspace stopped correctly (according to traces). :thinking:

**Comment by utam0k** [comment]
I found we can reproduce this issue with our integration test on the preview environment.

**Comment by kylos101** [comment]
> I found we can reproduce this issue with our integration test on the preview environment.

How so @utam0k ?

**Comment by kylos101** [comment]
> I found we can reproduce this issue with our integration test on the preview environment.

@utam0k can you share? 🙏

**Comment by utam0k** [comment]
> > I found we can reproduce this issue with our integration test on the preview environment.
> 
> @utam0k can you share? 🙏

Just run an integration test. However, I will include a fix to ignore this issue in the integration test.

**Comment by kylos101** [comment]
@utam0k do you mean temporary ignore? For example, so we can incrementally have tests passing in main branch, while a fix is done for the failing test?

**Comment by utam0k** [comment]
@kylos101 Sorry for my lack of information. I'm going to put this if statement into the main branch. Please note the link I shared is not in the main branch.
https://github.com/gitpod-io/gitpod/blob/4e824503da137d43ae901f37b972400254ca5b68/test/pkg/integration/workspace.go#L522-L523

**Comment by jldec** [comment]
Got this errer after a workspace timed out running on self-hosted preview env on Azure with a build from today.
![](https://user-images.githubusercontent.com/849592/193279643-acd5461f-b879-48fa-a8f8-13e5f0c6a739.png)

**Comment by lucasvaltl** [comment]
FYI that I tried to reproduce what @jldec experienced above on my (newly created, via terraform) GCP environment. I set the global timeoutDefault  to 5m and had 2 different workspaces time out successfully after the 5 minutes. That of course does not mean that this never happens, but at least that this is flaky 🤔

**Comment by kylos101** [comment]
Another occurrence ([Internal](https://gitpod.slack.com/archives/C02F19UUW6S/p1665000596221749))

**Comment by lucasvaltl** [comment]
Ran into this again. Stopped two workspaces at the same time on an AWS Self-Hosted Environment (2022.09rc6). One was fine, the other showed the `The container could not be located when the pod was terminated` error. @nandajavarma will link asupport bundle with the logs. The workspace in question was: `lucasvaltl-getrobotisla-clmsdohpu5r.ws.release-aws.[...]`

**Comment by nandajavarma** [comment]
[Here is the link](https://vendor.replicated.com/troubleshoot/analyze/2022-10-07@12:15) to the support bundle for the `release-aws` cluster

**Comment by jenting** [comment]
From the above all reported, the issue happened when the workspace was stopping. I'm wondering if it's because of this
- the ws-daemon backing up the content to GCS
- the ws-daemon requests lots of resources from the node because backing up the content
- the kubelet evicts the workspace pod because this node is out of resource
- the workspace pod transited into an [unknown state](https://github.com/kubernetes/kubernetes/blob/9b4b1c0e79aca46965137227e2c9cde0d285cabb/pkg/kubelet/kubelet_pods.go#L1663-L1675), and the error message reported
- the ws-manager catches the workspace pod terminated, and shows the error message to the user

**Comment by kylos101** [comment]
This is still an issue with `gen73`, recent [logs](https://cloudlogging.app.goo.gl/1BoozfhzqhQZXTRY6).

@jenting one way to resolve this, is to ship PVC, and avoid backup with `ws-daemon` altogether, you're right that stopping workspaces incur a heavy resource hit with `ws-daemon`.

I am going to remove this from our project, for now (putting it back to inbox) so that there is less work "in progress" so that we can focus. :wave:

**Comment by svenefftinge** [comment]
I've had the same error just now. When I tried to restart the workspace I got:
```
cannot pull image: rpc error: code = NotFound desc = failed to pull and unpack image "reg.ws-us73.gitpod.io:20000/remote/d584ec9e-7038-401f-b93b-51b164fcdb33:latest": failed to resolve reference "reg.ws-us73.gitpod.io:20000/remote/d584ec9e-7038-401f-b93b-51b164fcdb33:latest": reg.ws-us73.gitpod.io:20000/remote/d584ec9e-7038-401f-b93b-51b164fcdb33:latest: not found
```
Tried multiple times and I'm not able to start my workspace.

**Comment by jenting** [comment]
> 

Thanks for the report. But from the error log, it's another symptom.

**Comment by jenting** [comment]
> I've had the same error just now. When I tried to restart the workspace (gitpodio-gitpod-zjkqtz6c188) I got:
> ```
> cannot pull image: rpc error: code = NotFound desc = failed to pull and unpack image "reg.ws-us73.gitpod.io:20000/remote/d584ec9e-7038-401f-b93b-51b164fcdb33:latest": 
> failed to resolve reference "reg.ws-us73.gitpod.io:20000/remote/d584ec9e-7038-401f-b93b-51b164fcdb33:latest": reg.ws-us73.gitpod.io:20000/remote/d584ec9e-7038-401f-b93b-51b164fcdb33:latest: not found
> ```
> Tried multiple times and I'm not able to start my workspace.
> 

 
Thanks for the report. But from the error log, it's another symptom.

**Comment by kylos101** [comment]
@easyCZ just experienced this after 10 minutes in https://gitpodio-gitpod-cqng3518h09.ws-eu77.gitpod.io/, he was using VS Code Desktop for the IDE via the unstable channel.

**Comment by kylos101** [comment]
@easyCZ it looks like:
1. [the IDE loop ended](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-28T14:33:40Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%22715abcd4-659f-407f-a6f0-fc9f99341ce5%22%0Atimestamp%3D%222022-11-28T14:33:40Z%22%0AinsertId%3D%22cklxwcptexresm3m%22;summaryFields=:false:32:beginning;timeRange=2022-11-28T12:16:29.147Z%2F2022-11-28T15:16:29.147Z?project=workspace-clusters)
2. But I'm unsure why. Perhaps [this](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-28T14:33:40Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%22715abcd4-659f-407f-a6f0-fc9f99341ce5%22%0Atimestamp%3D%222022-11-28T14:33:40Z%22%0AinsertId%3D%22wpy610njgdiipzgn%22;summaryFields=:false:32:beginning;timeRange=2022-11-28T12:16:29.147Z%2F2022-11-28T15:16:29.147Z?project=workspace-clusters) is a start for debugging? @akosyakov @utam0k wdyt?

**Comment by utam0k** [comment]
FYI: This error can also be seen rarely in integration tests. Now we are ignoring this error to pass the integration stably.
https://github.com/gitpod-io/gitpod/blob/116ea559bc0979227467c9e30c717e786c2bee97/test/pkg/integration/workspace.go#L733

My first concern is whether the backup is complete. How about checking that first? I feel that would change the priority of this issue.

**Comment by atduarte** [comment]
@utam0k @kylos101 Hey! Me, @WVerlaek, and @jenting are doing the refinement and have a couple of questions (mentioned in the description). Do you know the answer to any of them?

**Comment by jenting** [comment]
We see the log `The container could not be located when the pod was deleted.  The container used to be Running` within the [GCP log](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-01-04T05:22:19.977165741Z;query=%22workspace%20failed%22%0Atimestamp%3D%222023-01-04T05:22:19.977165741Z%22%0AinsertId%3D%22domvix05xh6189z6%22;timeRange=PT3H?project=workspace-clusters). (Under the _jsonPayload.conditions.failed_ field).

**Comment by jenting** [comment]
This issue increases the metric `workspace_stops_total{reason="failed"}` which affects our [stop workspace SLO](https://pyrra.gitpod.io/objectives?expr={__name__=%22workspace-stop-workspace-success-ratio%22,%20namespace=%22monitoring-central%22,%20team=%22workspace%22}&grouping={}&from=1672811726370&to=1672815326370).

We can find it by comparing the [Grafana](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22C%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,type%3D%5C%22REGULAR%5C%22%7D%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221672811966000%22,%22to%22:%221672815566000%22%7D%7D) and the [GCP log](https://cloudlogging.app.goo.gl/DAE9iVygAmM5TuFQ9).

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/49380831/210501079-e2bbee48-34e8-4f32-aff5-f8989db7215e.png">
<img width="495" alt="image" src="https://user-images.githubusercontent.com/49380831/210501583-46eb89ff-6682-44eb-b585-19d1c517fc39.png">

> **Note**
> We have duplicated log, so we should treat the same time period log (within one second) as a stopping workspace failed. Good news is the backup is complete which means no data loss `jsonPayload.conditions.finalBackupComplete=true`.

**Comment by kylos101** [comment]
@jenting  can you update the description for https://github.com/gitpod-io/gitpod/issues/12021? It seems like you verified there is no data loss? 

Also, regarding Milan's case, that is old, back when there was trouble in the IDE space causing workspaces to start slowly. I am skeptical it will provide value. 

Do you have any traces for recent occurrences of this issue that help "paint a a picture", so we can see more easily how to recreate?

**Comment by jenting** [comment]
I checked over the last seven days [GCP log](https://cloudlogging.app.goo.gl/mXX7XXZ2C6xUcAh2A).

There is only [one instance](https://cloudlogging.app.goo.gl/yN9k7EctPhzW6cEC6) without `jsonPayload.conditions.finalBackupComplete=true`. Checking the detailed GCP log, I am skeptical that it's a data loss case because the start workspace and stop workspace request is within a minute. I think that the workspace never goes into a Running state.

**Comment by jenting** [comment]
> Do you have any traces for recent occurrences of this issue that help "paint a a picture", so we can see more easily how to recreate?

The traces [[1](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/search?end=1673331966672000&limit=20&lookback=1h&maxDuration&minDuration&service=ws-manager&start=1673328366672000&tags=%7B%22instanceId%22%3A%2247ee3566-71d8-4c16-a12d-bba41c6d2468%22%7D)], [[2](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/search?end=1673331827648000&limit=20&lookback=3h&maxDuration&minDuration&service=ws-manager&start=1673321027648000&tags=%7B%22instanceId%22%3A%221695a47b-5637-48d8-abbd-5f0d779fb23e%22%7D)], and [[3](https://jaeger-eu-prod.workspace-preview.gitpod-io-dev.com/search?end=1673332059643000&limit=20&lookback=3h&maxDuration&minDuration&service=ws-manager&start=1673321259643000&tags=%7B%22instanceId%22%3A%22327e9117-2f24-4af1-a99e-dc0d522fa7b3%22%7D)] indicate the workspaces are stopped correctly 🤔

**Comment by jenting** [comment]
There are some [reasons](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#node-conditions) that the kubelet evicts the pods.
We add disk and memory pressure tolerate to indefinitely, and network unavailable tolerate to 30 seconds. Refer to https://github.com/gitpod-io/gitpod/blob/1512a765b1f30c6ba9b1caae8fe5931fcb628145/components/ws-manager/pkg/manager/create.go#L544-L563

For the node not ready and unreachable tolerate to 300 seconds is also applied to the workspace pod.

The possible suspect is the PID pressure.
