### ISSUE TITLE
Docker: COPY doesn't work?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1202]
Using https://github.com/RXT0112/Zernit/tree/9e901d81e015362904f1294f53473d2e6de8ce97

Which has `vlang_init.sh` placed in `gitpod/vlang_init.sh` (same file as `gitpod.Dockerfile`) with configuration:
```docker
COPY vlang_init.sh /usr/bin/vlang_init
```

Results in: 
```
 ---> Running in 4a2b9a20162f
 ---> 804b64b32181
Step 6/10 : COPY vlang_init.sh /usr/bin/vlang_init
Step 6/10 : COPY vlang_init.sh /usr/bin/vlang_init

build failed: cannot build base image: COPY failed: stat /var/lib/docker/165536.165536/tmp/docker-builder524602626/vlang_init.sh: no such file or directoryStep 6/10 : COPY vlang_init.sh /usr/bin/vlang_init

Error: build failed: cannot build base image: COPY failed: stat /var/lib/docker/165536.165536/tmp/docker-builder524602626/vlang_init.sh: no such file or directory
```

Full log: http://dpaste.com/1VAMRV0.txt

---

Why can't i use `COPY` from a repository?

**Comment by Kreyren** [comment]
Solved, it considers root as root of the repository instead roof of the dockerfile -> `COPY gitpod/vlang_init.sh ...` works

**Comment by JesterOrNot** [comment]
@Kreyren should we close this issue then?
