### ISSUE TITLE
Establish an easy way to try IPFS in a preview or workspace-preview environment

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#12023]
## Is your feature request related to a problem? Please describe

We don't have a good way to check the behavior of IPFS, because we don't support for IPFS feature on preview env and workspace-preview.

## Describe the behaviour you'd like

We can check it other than the production

**Comment by aledbf** [comment]
You only need to execute

- `/usr/local/bin/ipfs-bootstrap.sh`
- `kubectl apply -f /var/lib/gitpod/manifests/ipfs.yaml`

both assets are included in the GCP VM image.

**Comment by utam0k** [comment]
@aledbf Thanks!!
