### ISSUE TITLE
Use the observability installer to install monitoring satellite in preview envs

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#12036]
## Is your feature request related to a problem? Please describe
Similar to https://github.com/gitpod-io/ops/pull/3758, run `go run main.go render` to install observability in preview envs rather than running jsonnet. 

For now, hide the functionality behind a feature flag (i.e. werft annotation).

## Describe the behaviour you'd like
RUn go instead of jsonnet here:
https://github.com/gitpod-io/gitpod/blob/5855038f60fc97f7c1e3ecff11b9dc8757137397/.werft/observability/monitoring-satellite.ts#L57

**Comment by mads-hartmann** [comment]
You can now use:

```
werft job run github -a observabilityInstallationMethod=observability-installer -a with-preview=true
```

However the installation isn't successful. Partly due to the installer not being feature complete yet (afaik) and partly because the installer doesn't install CRDs: [see comment](https://github.com/gitpod-io/gitpod/pull/12039#pullrequestreview-1069609574)

**Comment by mads-hartmann** [comment]
@meysholdt Should we close this issue now as the ability to use the installer is in place? Or do you want to keep it open until we have completely switched to using the installer as the default?

**Comment by ArthurSens** [comment]
I'm currently working on this issue, so we can leave it open 😅
