### ISSUE TITLE
GitPod can not find Docker Files when using a branch 

### ISSUE THREAD

**Issue by vikas5914** [gitpod-io/gitpod#1203]
### Describe the bug
According to documentation (https://www.gitpod.io/docs/config-docker/), The easiest way to try out docker setting is to push them into a branch and create a new workspace. But this throw `Dockerfile" does not exist` error.  I have not testing this with github. 

### Steps to reproduce
1. Create a new repo sample project.
2. Create a new branch and add `.gitpod.yml` and `docker file`
3. Create Workspace using the branch.

### Expected behavior
Workspace should build using dockerfile..

### Additional Information
![image](https://user-images.githubusercontent.com/7912297/74053095-24244180-4a01-11ea-816d-b170fce19b56.png)

### Example Repository
Gitlab Repo with branch: https://gitlab.com/vikas5914/gitpod-docker-branch-test/tree/docker

GitPod workspace URL: https://gitpod.io/#https://gitlab.com/vikas5914/gitpod-docker-branch-test/tree/docker

PS: Can we add `php-bcmath` and `php-ctype` to the base `workspace-full` image? Both extension is required for Laravel 6.0. With those we can run laravel project out of the box with sqlite and artisan serve.

**Comment by vikas5914** [comment]
Created PR for the Extensions: https://github.com/gitpod-io/workspace-images/pull/160

**Comment by JesterOrNot** [comment]
See
#1000 #643 and #692

**Comment by vikas5914** [comment]
@JesterOrNot I think this is a different bug. The files exist and there is no spelling/name mismatch here. If I merge the files to master branch, the Gitpod will work on both branches.

**Comment by JesterOrNot** [comment]
I will look more into it

**Comment by svenefftinge** [comment]
Thanks for reporting. It is high on our schedule. Not sure it will make it into Wednesday's release, though. I'm closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/1161
