### ISSUE TITLE
Improve workspaces page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#12033]
### Problem to solve

Following up with all the recent features added to the product like **Teams & Projects** and the upcoming **Usage-Based Pricing (UBP)**, the [**Workspaces**](https://gitpod.io/workspaces) page could benefit from new patterns, components, or layouts.

This could tackle potential improvements like https://github.com/gitpod-io/gitpod/issues/3594, https://github.com/gitpod-io/gitpod/issues/5125, https://github.com/gitpod-io/gitpod/issues/10140, https://github.com/gitpod-io/gitpod/issues/4635, https://github.com/gitpod-io/gitpod/issues/4225 and more.

### Proposal

TBD (To be discussed)

**Comment by gtsiolis** [comment]
Posting an early design from a [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1660129817951259) (internal).

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="workspaces-page-before" src="https://user-images.githubusercontent.com/120486/185452281-7a7c852e-6160-429e-9cb8-0f3719d68031.png"> | <img width="1440" alt="workspaces-page-after" src="https://user-images.githubusercontent.com/120486/185452284-51d88b3b-21b7-4f48-a8a2-5c82e2daeb73.png"> |

**Comment by jldec** [comment]
Thanks @gtsiolis - I copied some feedback below captured during our discussion earlier. I would recommend editing the list below to indicate which item is about which column (or perhaps connect the list to the screenshot)


Some design thinking points:

1. Removes one column, from four to three.
jl - nice - reduces duplication, more responseive. (would like a prototype to test responsivenesss - e.g. when cells are narrower and wrap) 

2. Adds back the table header.
jl - nice - explains the columns more clearly

3. Keeps the workspace ID as the primary table identifier.
jl - agree

4. Introduces workspace class.
jl - agree - should surface this info everywhere we can (ws class-names messy) 

5. Uses label for running status indicator for better accessibility.
jl - agree (states should already be there ?)

6. Combines context URL with branch.
jl - ok - It’s helpful to surface different flavors of context url but not at the expense of seeing the repo info and being able to go to the repo. Based on the header, the column is supposed to be mainly about the repo.

7. Removes the repository URL in favor of the new combined context.
jl - I don’t like losing the repo URL entirely - is it clickable to go to github? I would put this in bold at the top of the cell, _not_ below the team/project.

8. Introduces project association.
jl - nice idea - but what if the project is not visible? not sure if it’s easy to do - 

9. Introduces team association.
jl - nice idea - but how to handle if the team is not visible?  

10. Nudges users to add repository as project when not added.
jl - how would this work with teams? need to clarify the flow before committing to this.

11. Surfaces credits used per workspace.
jl - this differs from the usage per workspace session - i think it will confuse users unless we make it clear that this is an aggregate when there have been multiple sessions/instances for one workspace e.g. by showing the breakdown or session count.

12. Changes orientation of the more actions dropdown button.
jl - fine with this 🙂

**Comment by gtsiolis** [comment]
Closing in favor of UX-26.
