### ISSUE TITLE
[ws-manager] cannot take snapshot, cannot find workspace during TakeSnapshot

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#12049]
### Bug description

The log message is **cannot take snapshot**, the underlying error is `rpc error: code = NotFound desc = cannot find workspace during TakeSnapshot`.

Regular and prebuild workspaces appear to get the [error](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-08-10T16:43:35Z;query=severity%3D%22ERROR%22%0Aresource.labels.container_name%3D%22ws-manager%22%0Aresource.labels.cluster_name%20:%20%2528%22us60%22%2529%0A-%22headless%22%0Atimestamp%3D%222022-08-10T16:43:35Z%22%0AinsertId%3D%229rawym67n24stlhj%22;summaryFields=resource%252Flabels%252Fcluster_name,jsonPayload%252FworkspaceId,jsonPayload%252Fstatus%252Fruntime%252Fnode_name:false:32:beginning;timeRange=PT3H?project=workspace-clusters).

### Steps to reproduce

Not sure, I can create snapshots and start workspaces from the URL provided by Gitpod.

Please look at the workspace [in this log](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-08-23T17:08:12Z;query=%22cannot%20take%20snapshot%22%0Atimestamp%3D%222022-08-23T17:08:12Z%22%0AinsertId%3D%22wrrkgau6hgzpp072%22;summaryFields=resource%252Flabels%252Fcluster_name,jsonPayload%252FworkspaceId,jsonPayload%252Fstatus%252Fruntime%252Fnode_name:false:32:beginning;timeRange=P7D?project=workspace-clusters), the related git context (repo) this this error often for the related organization.

### Workspace affected

gitlaborg-gitlab-nubhzid4agc

### Anything else?

This is still happening with `gen62`, here are related [logs](https://cloudlogging.app.goo.gl/7w1cbLHgdoB5Ha1d6).

**Comment by sagor999** [comment]
I believe (by inspecting [logs](https://cloudlogging.app.goo.gl/eZiuocFrC6uUZKMD8)) this issue is fixed via https://github.com/gitpod-io/gitpod/pull/12360
