### ISSUE TITLE
Possibility to build docker images

### ISSUE THREAD

**Issue by thomas-worm** [gitpod-io/gitpod#1205]
Hello,

I'd like to build docker images in the workspace like

```
docker build -t namespace/appname .
docker image save namespace/appname -o namespace-appname.dockerimage
```

This fails because docker cannot connect to the docker deamon.

Installing docker into the workspace image is not possible because this would be a docker container in a docker container.
Perhaps it is possible to expose the docker socket into the workspace for image creation? This would be great!

Best Regards,
Thomas

**Comment by svenefftinge** [comment]
Hi Thomas, yes this is something we need to make possible. We are on a good path towards allowing root and Docker in Docker, but are not there yet. I think it is a matter of a few months.
Here's the main issue for this https://github.com/gitpod-io/gitpod/issues/52. Feel free to chime in there. Closing this as a duplicate.
