### ISSUE TITLE
[observability] - warn when the # of nodes in a pool exceeds 80% of node pool maximum

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#12051]
## Is your feature request related to a problem? Please describe

Send a warning to workspace team when the # of nodes hits 80% of the maximum.

## Describe the behaviour you'd like

We currently monitor this manually, which is risky as we approach node pool maximums.

## Additional context

1. https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/proposals/metrics.md
2. `cluster_autoscaler_max_nodes_count` currently returns nothing, so, I'm not quite sure how we'll monitor as we get closer to the maximum.

**Comment by jenting** [comment]
> `cluster_autoscaler_max_nodes_count` currently returns nothing
- https://github.com/kubernetes/autoscaler/blob/bb8e41f77ef24ec94762c5ed136f25d8b17707ad/cluster-autoscaler/main.go#L385
- https://github.com/kubernetes/autoscaler/blob/bb8e41f77ef24ec94762c5ed136f25d8b17707ad/cluster-autoscaler/main.go#L129

**Comment by kylos101** [comment]
Ah, I see, `cluster_autoscaler_max_nodes_count` is not ideal for hitting instance group maximums.

**Comment by kylos101** [comment]
👋 @jenting thanks for sharing, I agree, max nodes count won't help us. 👍 

It doesn't look like we have "anything good" to alert us when we're approaching an autoscaler maximum for a node pool.

As a result, I doubt it is valuable to add an alert for `unschedulable_pods_count` because we already have [regular not active](https://github.com/gitpod-io/gitpod/blob/87fbe606ea43278f18100f117a6a2707b8e53045/operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet#L77).

Unless you can think of another way for us to proactively be alerted as we approach a maximum, please close this issue.

**Comment by jenting** [comment]
> As a result, I doubt it is valuable to add an alert for `unschedulable_pods_count` because we already have [regular not active](https://github.com/gitpod-io/gitpod/blob/87fbe606ea43278f18100f117a6a2707b8e53045/operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet#L77).

Agree.
 
> Unless you can think of another way for us to proactively be alerted as we approach a maximum, please close this issue.

Right now I have no idea about this now. I prefer to close this issue now.
Note, Alejandro extends the max node count from 50 to 75.
