### ISSUE TITLE
OAuth error with bitbucket server

### ISSUE THREAD

**Issue by jmls** [gitpod-io/gitpod#12065]
### Bug description

try to add an integration with bitbbucket server. We get all the way through to the Authorise screen, then when we press the button, an error appears
![Screenshot from 2022-08-11 13-15-43](https://user-images.githubusercontent.com/929523/184135985-4325cf67-1887-4f1a-995b-42a435e47d49.png)

### Steps to reproduce

follow the steps here

https://www.gitpod.io/docs/bitbucket-server-integration

### Expected behavior

for integration to work

**Comment by geropl** [comment]
Hey @jmls ,

could you share `server` logs right after this error appeared? Without it's hard to understand what might have happened.

**Comment by AlexTugarev** [comment]
@jmls and @geropl, I believe we've already investigated this issue on internal channels. 

While the underlying issue was resolved, we've scheduled https://github.com/gitpod-io/gitpod/issues/12158 to improve inspection of those kind of issues by forwarding the necessary error states.

**Comment by geropl** [comment]
Ok. I'm going to close this one in favor of https://github.com/gitpod-io/gitpod/issues/12158, then.

D'accord?
