### ISSUE TITLE
[server] Improve maintenance of workspace instance state

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#12067]
When there's an exception happening in `actuallyStartWorkspace` we catch it and treat the start request as failed by updating the workspace_instance in the DB and marking it as stopped. The request to ws-manager might have succeeded, and the error might have been thrown later (the concrete case was a protocol error with billingservice). 

We should try to keep the system consistent and try to cancel the workspace start with ws-manager in `failInstanceStart`.

Because the workspace instance was actually started, the stopped state will eventually be overwritten by `ws-manager-bridge`. It however only sets the status but doesn't reset the `stoppedTime`and `stoppingTime`fields. If they are set, we should log an error but also set those two properties to their default state again.

**Comment by kylos101** [comment]
Thank you @svenefftinge ! As a heads up, there is a [similar state management issue](https://github.com/gitpod-io/gitpod/issues/11397) that can cause workspaces to get stuck in Pending, too. Might be a good use case to test after this change is made.

cc: @laushinka
