### ISSUE TITLE
Offline Status - Server Issues?

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1206]
### Describe the bug

I have been getting the orange "offline" notification every few seconds while trying to edit- my connection is solid from what I've tested without any drops. Is there any issue currently with the servers? In the past it may happen momentarily, but typically is fine within a few seconds and doesn't return.

### Steps to reproduce

I've just tried launching a few different instances with the same issue.

### Expected behavior

To be able to edit as normal.

### Additional Information

NA

### Example Repository

https://github.com/4GeeksAcademy/html-hello

**Comment by alesanchezr** [comment]
I second this with another 2 accounts in the US.
