### ISSUE TITLE
Ensure that not more than one instance of a workspace is created at the same time

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#12072]
### Bug description

During an [incident](https://gitpod.slack.com/archives/C03T68YENAZ), we discovered that a workspace instance had been created, but due to another later call that failed server considered the creation of the workspace instance failed, set the instance to stopped and created another instance. Workspace manager was able to create the workspace pod successfully in the meantime. The second workspace failed because it assumed there must have been a backup due to the stopped (but actually running) workspace.

### Steps to reproduce

- A workspace request is sent successfully to ws-manager by workspace-starter
- A later request in the same try/catch caused an exception
- The workspace was then set to stopped and another workspace could be created

### Expected behavior

Ensure that only one instance of an workspace can exist in a workspace cluster at one time. In other words, there can be only one active instance of a metaID in a single workspace cluster.

Out of scope:
This must work even if there are multiple workspace clusters. Ref: https://github.com/gitpod-io/gitpod/issues/12067

**Comment by sagor999** [comment]
This is already done here:
https://github.com/gitpod-io/gitpod/blob/0699f84aba13019cbdb3c13dce79b2d33541a56f/components/ws-manager/pkg/manager/manager.go#L224

So something else might have caused this.
Unfortunately slack link does not provide instanceId or link to logs to look at it and do a deeper analysis.

I am going to return this task back into Breakdown category.
