### ISSUE TITLE
Dashboard should trim spaces around URL before creating workspace

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#12079]
### Description

If, by mistake, I copy/paste an additional space before the repo url, the dashboard fails where it could auto heal by trimming the space

<img width="928" alt="Screenshot 2022-08-11 at 21 35 28" src="https://user-images.githubusercontent.com/2318450/184224488-ba00022a-1be9-40da-8ad4-0dad750dcea6.png">

### Steps to reproduce

1. Open https://gitpod.io/#%20https://github.com/gitpod-io/spring-petclinic

### Expected behavior

The dashboards trims the space in the input when submitting avoiding me the error

<img width="641" alt="Screenshot 2022-08-11 at 21 36 33" src="https://user-images.githubusercontent.com/2318450/184224671-9a25d40f-58a1-402c-a4f7-7ab80b33593e.png">

**Comment by asemarian** [comment]
Hey @andreafalzetti, I'd love to work on this issue but I have no idea where to start. Where can I find instructions to run the project locally?

**Comment by andreafalzetti** [comment]
Hey @asemarian, the Dashboard component has its own [README.md](https://github.com/gitpod-io/gitpod/tree/main/components/dashboard) where you can find info on how to work on it, using gitpod itself.

Thanks for your interest in collaborating on this task 🙌

**Comment by geropl** [comment]
@asemarian Another approach could be to put this into the `ContextParser` [here](https://github.com/gitpod-io/gitpod/blob/45f13cf8e9214db664adc23a418e53d92364fbb7/components/server/src/workspace/context-parser-service.ts#L31), which is the authorative piece of code for handling "contextURLs".
💡  There should also be tests, and maybe you could extend them with your case.

**Comment by asemarian** [comment]
I'm having trouble running the project locally. So far I'm getting this error when running npm install

**Comment by andreafalzetti** [comment]
> I'm having trouble running the project locally.

@asemarian Did you try opening the gitpod's repo in gitpod?

**Comment by Hardik500** [comment]
I would like to work on this issue, if no one else has taken it

**Comment by andreafalzetti** [comment]
Thanks for the interest, @Hardik500!

I think nobody has worked on this right recently, no PRs were opened so I'd say: feel free to take ownership :)

**Comment by Hardik500** [comment]
Sure @andreafalzetti

**Comment by Hardik500** [comment]
https://github.com/gitpod-io/gitpod/issues/12079#issuecomment-1265726543
@andreafalzetti Any thoughts?

**Comment by andreafalzetti** [comment]
On how to debug `server` better to ask @gitpod-io/engineering-webapp as they own this component

**Comment by axonasif** [comment]
I'll try mentioning @jankeromnes from the webapp team, could you please help @Hardik500 with some clues 😇 ?

**Comment by Hardik500** [comment]
@jankeromnes Would love it if you could point me to some docs or any clues.
