### ISSUE TITLE
Add option to delete workspace to IDE interface

### ISSUE THREAD

**Issue by randomir** [gitpod-io/gitpod#1207]
I often want to delete the workspace I'm done with, and my current workflow is:
- open top-right avatar dropdown:
![image](https://user-images.githubusercontent.com/447371/74107535-00a6e700-4b26-11ea-8d01-43c10502d27b.png)
- click stop
- remember first few letters of workspace uuid
- on the modal that pops (stopping workspace), click "Workspaces"
- on workspaces page, delete the appropriate workspace by clicking the garbage bin icon

Having an option to "Delete Workspace" in the avatar dropdown would speed this up.

A valid concern, I hear you saying, is people inadvertently clicking "Delete" instead of "Stop" -- well, a great feature I would be equally happy with would be to add "Delete Workspace" command in the Command Palette (F1)

**Comment by svenefftinge** [comment]
We are going to activate the automatic garbage collection, that will delete unused workspaces after a certain period of time. So you don't have to manually care about it. Would solve your issue?

**Comment by randomir** [comment]
Maybe I'm just not used yet to the GitPod workflow, but I prefer to keep the list of my workspaces small.

Imagine starting multiple workspaces (possibly for the same repo), and then at some point deciding to keep only some (or just one). Going back to workspace list, it's hard to know which one is which, without actually running it.

At the very least, it would be useful to have "Rename Workspace" in the Command Palette (or the avatar menu).

**Comment by alesanchezr** [comment]
But you can rename a workspace and you can also delete:
![Workspaces - Gitpod](https://user-images.githubusercontent.com/426452/74109555-690bbd80-4b52-11ea-82c7-8d9d80485a66.png)

**Comment by randomir** [comment]
@alesanchezr, I am aware of that. I opened this feature request to speed-up the workflow (and improve UX). Deleting and/or renaming the workspace from the IDE, while you're still running it is faster (more convenient) than going back to the list of workspaces, locating your workspace and then clicking one of those icons.

**Comment by alesanchezr** [comment]
I understand, u r right, some of my students struggle to find the update pencil feature some times.
