### ISSUE TITLE
cpu/memory thresholds should be propagated by supervisor

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#12075]
## Is your feature request related to a problem? Please describe
Currently, to display high usage of CPU/Memory we replicated thresholds in [gitpod-cli](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/cmd/top.go#L48-L57) and `jb backend plugin`. Ideally, supervisor should own the thresholds and propagate them to the clients.

## Describe the behaviour you'd like
- hardcoded cpu/memory thresholds are removed from all components
- thresholds are retrieved from supervisor like we retrieve the resource status

Places in the code to change:
- https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/cmd/top.go#L48-L57
- TODO: add link to JetBrains IDE once https://github.com/gitpod-io/gitpod/pull/12053 gets merged

## Describe alternatives you've considered

N/A

**Comment by andreafalzetti** [comment]
@akosyakov do you think thresholds should be propagated together with [ResourcesStatusResponse](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor-api/status.proto#L234-L239) or shall we have a separate endpoint?

**Comment by akosyakov** [comment]
@andreafalzetti I thought it will be part of https://github.com/gitpod-io/gitpod/blob/698e6bf78f8113ac378b5e88c794eea175781da1/components/supervisor-api/status.proto#L240 something like 
```proto
message ResourceStatus {
    int64 used = 1;
    int64 limit = 2;
    ResourceStatusSeverity severity = 3;
}
enum ResourceStatusSeverity {
    normal = 0;
    warning = 1;
    danger = 2;
}
```

concrete numbers will be implementation details of supervisor
