### ISSUE TITLE
extend supervisor rate-limiting on ResourceStatus

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#12083]
## Is your feature request related to a problem? Please describe
Currently, supervisor endpoints for retrieving [ResourceStatus](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor-api/status.proto#L76-L80) calls directly an [upstream socket](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/pkg/supervisor/top.go#L26) to retrieve the resource status info, when a client requests them. There is requests rate-limiting upstream, so multiple clients request resource status to supervisor, and those requests are directly sent upstream, supervisor might fail to respond.

## Describe the behaviour you'd like
If we extend supervisor by fetching resource status asyncronously from incoming ResourceStatus requests, we can control the frequency of calls to the socket. When a new client requests data, we would just return the latest data received from upsteam.

## Describe alternatives you've considered
Implementing a exponentioanl backoff retry strategy in each client. Currently, [gitpod-monitor](https://github.com/akosyakov/gitpod-monitor/blob/15bc5a39d8ab4f71a18ce7e0a38a70c8e9e0e526/src/extension.ts#L65-L77) already uses this approach but it would mean replicating this logicin in all clients (jetbrains backend-plugin, gitpod-cli, etc..).

**Comment by akosyakov** [comment]
> we could extend the rate-limiting in supervisor to queue requests and try to reply successfully to all reqs.

@andreafalzetti I meant doing supervisor what you did in JB:
- have a go routing which fetch workspace info socket each 1second and use exponential fallback if it fails
- store last successful in a variable
- then a client calls resource endpoint use copy variable in another local variable and use to create the state

**Comment by andreafalzetti** [comment]
I've updated the issue description with much more context and the approach agreed. Thanks for the call, it was helpful 🙏
