### ISSUE TITLE
Implement exponential backoff in JetBrains for retrieving ResourceStatus from supervisor

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#12088]
## Description
While we wait for implementing a [proper fix in supervisor](https://github.com/gitpod-io/gitpod/issues/12083) a quick patch could be implementing backoff functionality in the client, as follow-up PR from: https://github.com/gitpod-io/gitpod/pull/12053#discussion_r944122574

**Comment by akosyakov** [comment]
I think we can close it if we implement https://github.com/gitpod-io/gitpod/issues/12083

**Comment by akosyakov** [comment]
Closing in favor of https://github.com/gitpod-io/gitpod/issues/12083
