### ISSUE TITLE
Cannot build repository that was working before

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#1208]
### Describe the bug
I cannot open in github this repository (it worked without issues for almost a year already):
https://github.com/breatheco-de/assets

### Steps to reproduce
Click here: https://gitpod.io/#https://github.com/breatheco-de/assets

### Expected behavior
To create the workspace, make the build and run the app.

### Additional Information
Its a PHP workspace.

**Comment by svenefftinge** [comment]
I opened the repo and it seem to work nicely. Can you describe what went wrong?

**Comment by alesanchezr** [comment]
yeah its opening fine now.
