### ISSUE TITLE
Insufficient space and Server lssues.

### ISSUE THREAD

**Issue by jelaniwoods** [gitpod-io/gitpod#1209]
### Describe the bug
I'm having difficulty installing dependencies, modifying files, and using git. I'm getting error messages like "There was insufficient space remaining on the device."

### Steps to reproduce
Create this workspace: [https://gitpod.io/#https://github.com/appdev-projects/msm-queries](https://gitpod.io/#https://github.com/appdev-projects/msm-queries)

The `bundle install` command fails.
![image](https://user-images.githubusercontent.com/17581658/74110364-770d0e80-4b51-11ea-9ecb-4de7573385ce.png)

### Expected behavior
To be able to install dependencies normally and use git to version control.

### Additional Information
I'm located in the US and am working in a Ruby on Rails project.
For existing workspaces, files seem to delete their entire content and I can't seem to use git to restore them.
![image](https://user-images.githubusercontent.com/17581658/74110406-edaa0c00-4b51-11ea-9e41-636d69d108a6.png)

This is possibly related to #1206, since I am also experiencing the "offline" notification frequently along with general slowness and lag using the command line.

**Comment by RDIL** [comment]
Yeah, experiencing the same thing in facebook/create-react-app when running `yarn` in a GP workspace.
