### ISSUE TITLE
Enable workspace_classes when Usage-based billing is enabled for a user

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#12098]
## Is your feature request related to a problem? Please describe

Right now, usage based pricing and workspace classes are enabled independently.

## Describe the behaviour you'd like

If Usage-Based Billing is enabled for a user, also enable workspace_classes. 
We should still be able to enable workspace_classes separately, for example, if an installation does not use usage based billing.

**Comment by kylos101** [comment]
@geropl @jldec  :wave: just sharing as a heads up, I figure we'll need this in advance of stage 3 for the UBP/workspace-classes rollout.

**Comment by kylos101** [comment]
@Furisto as a heads up, created this, so that later once we're further along in the timeline, workspace_classes will be enabled if a user has UBP enabled.

**Comment by geropl** [comment]
I will make it so that users see this option if either a) they're allowed to do so based on BillingMode (usage-based pricing logic), OR b), they have that workspace_classes feature flag set.

@Furisto Does this make sense?
