### ISSUE TITLE
[Git] Git operations feel slow

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#121]
Since our last update any git operation seems a lot slower.
Also I get `.gitlock`-notifications quite often.

**Comment by svenefftinge** [comment]
@AlexTugarev Any idea what could cause this?

**Comment by AlexTugarev** [comment]
'Not sure if this are two issues. I do observe the same, though it's not always really bad.

One known issue: git operations might compete now more likely as we've a new indirection now talking to the workspace git. Was there anything considered to have git operations sequenced in Theia?

We should definitely measure this to identify the bottleneck.

**Comment by AlexTugarev** [comment]
This https://github.com/gitpod-io/gitpod/issues/104 might be related.
