### ISSUE TITLE
Can't push to public repository even though GitHub access is granted

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#1210]
### Describe the bug
I have previously granted `write public repos` to Gitpod in https://gitpod.io/access-control/:

<img width="200" alt="Screenshot 2020-02-11 at 18 57 40" src="https://user-images.githubusercontent.com/599268/74264343-cc3b5280-4d00-11ea-8c08-8c4d2878610a.png">

But when I try to push to the public repository https://github.com/gitpod-io/website, I get this error:

```
gitpod /workspace/website $ git push origin jx/ruby-add-rails-sample-app 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/gitpod-io/website.git/'
```

<img width="504" alt="Screenshot 2020-02-11 at 18 52 26" src="https://user-images.githubusercontent.com/599268/74264324-c5acdb00-4d00-11ea-966c-fb4c3aa679e2.png">

When I click the GitHub audit link, Gitpod even seems to have "Full control of private repositories" (!) (I've granted it previously, but then revoked it, so this is surprising to me):

<img width="759" alt="Screenshot 2020-02-11 at 18 58 26" src="https://user-images.githubusercontent.com/599268/74264412-e83ef400-4d00-11ea-90d2-287213ee51d6.png">

Note: Granting `read/write private repos` in Access Control does allow me to push to my public repository.

### Steps to reproduce
0. Revoke `read/write private repos` in Access Control
1. Open a public repo (from an org maybe?)
2. Create a new branch
3. Try to `git push origin new-branch`

### Expected behavior
Push should succeed.

**Comment by artalar** [comment]
Check this out https://github.com/gitpod-io/gitpod/issues/846#issuecomment-541612629

**Comment by jankeromnes** [comment]
@artalar thanks! But my error message says:

```
fatal: Authentication failed for 'https://github.com/gitpod-io/website.git/'
```

I'm not using SSH authentication, so I don't think that's the problem.

**Comment by svenefftinge** [comment]
The fix/change is now deployed in production.

**Comment by Kreyren** [comment]
@svenefftinge Can you reference the relevant code which fixes the issue? It would help us to better understand how gitpod works for contribution

**Comment by JesterOrNot** [comment]
Sorry, @Kreyren AFAIK this is all in a closed sourced repository

**Comment by svenefftinge** [comment]
Yes, sorry, as Sean mentioned. The part that fixed it is closed sourced.
Please open an issue, if you still see this happening.

**Comment by MangelMaxime** [comment]
Before the release of the fix I didn't have the error.

But now, I am seeing this error each time I am pushing to a repo even if the `git push` command is working. I am not sure how I can provide reproduction or more info about this problem.

**Comment by svenefftinge** [comment]
Please ignore the error message, as it is working otherwise. We have a fix that is going into production on Wednesday.
