### ISSUE TITLE
VSCode in browser fails to load sometimes

### ISSUE THREAD

**Issue by mbrevoort** [gitpod-io/gitpod#12107]
### Bug description

When starting a new workspace, VSCode fails to load fully in browser sometimes. A browser refresh usually fixes the problem. I have not been able to reproduce this consistently but it typically happens the first time I load a gitpod on a new device.

See screenshot:
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/30455/184448747-1f4345c1-90f5-4c7d-bcf2-0005e590f502.png">

### Steps to reproduce

Start a workspace in the browser.

### Workspace affected

pbpdnbu5hqm.ws-us60.gitpod.io

### Expected behavior

VSCode should open and be functional

### Example repository

https://github.com/gitpod-io/gitpod

**Comment by foobar421** [comment]
Could this be caused by the recent load-balancer issues? I.e. some of the requests haven't been served properly?

**Comment by metcalfc** [comment]
I hit this as well I believe. I wasn't able to reload to fix it. I had to close the tab completely and reopen the workspace. Happy to get more details the next time I see it if there is something I can grab.

**Comment by loujaybee** [comment]
We've added some analytics and observability for this error, and we can see the error. However, we don't currently have a clear view of how many users this is affecting right now. The next step is to get a clearer picture on the % of users that this is affecting right now. 

@filiptronicek is going to take a closer look.

**Comment by loujaybee** [comment]
We've instrumented this one with data, we'll drop this one from the current iteration and pick up again for investigation in another week or two.
