### ISSUE TITLE
Add (cloud) repo create/push to `gp` command line program

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#12117]
Given the capability to create a new "blank" workspace via https://gitpod.new - have a command line option (i.e., via `gp`) to create a remote repository on the associated github/gitlab/bitbucket account.  So you can start up a playpen but then decide to make it "official" from right within the workspace.  (Instead of going to Github/Gitlab/bitbucket and creating it there and then hooking up your workspace to it via a "git init"/"git add remote" or whatever it would be.)

GitHub has this already in their [command line tool](https://cli.github.com/manual/gh_repo); GitLab doesn't have a command line tool of that sort that I know of; bitbucket I have no idea.

(Alternatively, add this capability to VSCode.  But both the browser and the desktop version.  Maybe it's already there but using the "..." menu on the source control workspace pane I don't see a "create remote repo" option anywhere, and I don't see it via F1 at the command dropdown either.)

Actually, on thinking of it I see that gitpod is so remote-git-repo agnostic it doesn't actually know what your "preferred" remote-git-repo is.  Maybe one of the git providers on the account could be designated for this, or maybe the command would have you specify github/gitlab/bitbucket.

**Comment by akosyakov** [comment]
I would think that each git hosting provider should take care of own tools, provide cli tools and extension for IDEs. So if tooling is missing first place should be to create issues for GitHub/GitLab or BitBucket. I don't think it makes sense layer to build the layer of abstraction over it. We could consider though preinstall vendors tooling by default depending on opened context, as we do it now with installing [GH PR](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) extension for GH contexts.

@gtsiolis maybe you know about GitLab cli

**Comment by david-bakin** [comment]
> We could consider though preinstall vendors tooling by default depending on opened context, as we do it now with installing [GH PR](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) extension for GH contexts.
> 

That would be fine!

**Comment by axonasif** [comment]
I'm installing and logging into `gh` from my dotfiles.
https://github.com/axonasif/dotfiles/blob/main/src/install/gh.sh

**Comment by gtsiolis** [comment]
@akosyakov In case this helps, in GitLab you can create a new project with Git push, see [relevant docs](https://docs.gitlab.com/ee/user/project/working_with_projects.html#create-a-new-project-with-git-push). 💡
