### ISSUE TITLE
Can i test github actions on gitpod?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1211]
I'm slowly loosing my mind over testing Github Actions through spam commiting and silently blaming github for having terrible documentation.. 

Is there a way to test these on gitpod so that i woudn't have to wait 47.742 sec on average for the workflow to trigger ?

**Comment by svenefftinge** [comment]
Unfortunately, the answer appears to be no.

**Comment by Kreyren** [comment]
Relevant https://github.com/nektos/act/issues/74
