### ISSUE TITLE
Log in to Gitpod with a GitLab account started failing at around 2022-08-13 @ 01:45 UTC

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12114]
### Bug description

Error message `the provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client`.

### Steps to reproduce

Log in to Gitpod with GitLab account.

### Anything else?

The current GitLab version is GitLab Enterprise Edition [15.3.0-pre](https://gitlab.com/help) [7a46d227f1e](https://gitlab.com/gitlab-org/gitlab/-/commits/7a46d227f1e).

- [Incident 195](https://app.incident.io/incidents/195)
- [GitLab issue](https://gitlab.com/gitlab-org/gitlab/-/issues/370671)
- #12112

**Comment by jenting** [comment]
Feedback from @gtsiolis 
1. This issue seems to be relevant to the breaking OAuth flow changes ([#10090](https://github.com/gitpod-io/gitpod/issues/10090)) in GitLab 15.0. We bypassed this issue on our side with a workaround in [#10102](https://github.com/gitpod-io/gitpod/pull/10102), cross-posting in case it helps. :eyes:
2. There’s also [#10932](https://github.com/gitpod-io/gitpod/issues/10932) which can be resolved by simply reload the page, see [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1656323882688609). I could be wrong but it sounds also related.

**Comment by geropl** [comment]
We noticed that the login failure ratio dropped to pre-incident values again: 
![image](https://user-images.githubusercontent.com/32448529/184597877-d472b137-d0b0-4285-919b-1fb70ef58db5.png)

It's unclear why, though. We're leaving this open to keep track, and are hoping from [further feedback](https://gitlab.com/gitlab-org/gitlab/-/issues/370671#note_1064573516) from GitLab on this.
