### ISSUE TITLE
Prebuild failed "fatal: 'origin/main' is not a commit and a branch 'main' cannot be created from it

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#12118]
### Bug description

Prebuild failed as follows:
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/4162948/184511607-3d962f0a-bddc-4411-a8f0-c7c07d406bcd.png">

```
SYSTEM ERROR
Prebuild failed for system reasons. Please contact support. cannot initialize workspace: cannot initialize workspace: git initializer clone: git checkout -B main origin/main failed (exit status 128): fatal: 'origin/main` is not a commit and a branch 'main' cannot be created from it
```

Main repo: https://gitlab.com/bakins-bits/gitpod-setup-for-bitcoin-core-dev/ (default branch is `main`, commit `c800c2e3`)

Additional repos: 
- https://github.com/david-bakin/bitcoin (default branch is `master`, commit `695ca641a`)
- https://github.com/david-bakin/btcdeb (default branch is `master`, commit `3ba1ec7f4`)

Prebuild url: https://gitpod.io/projects/gitpod-setup-for-bitcoin-core-dev/7cfe11d0-5d28-47fd-963d-7d47c18859ec

Incremental prebuilds _not_ enabled.

Note that this _used_ to work.  Nothing has changed recently in any of these repos (_especially_ no change of default branch).  Also  only minor (unrelated) changes to `.gitpod.yml` and the custom docker image. (Though you can check that.)

### Steps to reproduce

Just try to open / prebuild this workspace. Same thing also happens when opening new workspace off this repo w/o prebuild.

### Workspace affected

https://bakinsbits-gitpodsetupf-gpparx4s13d.ws-us60.gitpod.io/

### Expected behavior

Prebuild should work!  Main repository and additional repositories should be fetched from their appropriate default branch (`main` for the main repo, `master` for the additional repos.)

### Example repository

https://gitlab.com/bakins-bits/gitpod-setup-for-bitcoin-core-dev/-/tree/main

### Anything else?

Commit hashes given above so I can advance `gitpod.yml` to try to get unwedged.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3pnnu)

**Comment by david-bakin** [comment]
Also the error messages shown are inadequate for a multi-repo workspace: _which_ repository is causing the trouble, eh?

**Comment by david-bakin** [comment]
Related to #11854

**Comment by axonasif** [comment]
Possibly.

**Comment by geropl** [comment]
> Dup of https://github.com/gitpod-io/gitpod/issues/11854 ?

@david-bakin Yes, that seems to be the case. Moving over to workspace, but assume we can close it once rolled out.

**Comment by jenting** [comment]
This is duplicated of #11854, and it's deployed already.
Closing this issue now. Feel free to reopen it once you still encounter it.
Thank you.
