### ISSUE TITLE
Feedback Issue: SSH with Termius

### ISSUE THREAD

**Issue by LucBerge** [gitpod-io/gitpod#12119]
### Objective

I would like to be able to connect to my workspace with Termius on my phone.

What I've done do far:
- Create a RSA key on Termius
- Implrt the RSA public key in Gitpod
- Copy/paste the command diplayed by Gitpod to connect with Termius

But in the last step, Termius asks me for a password. What password ?

Thanks

Edi: I don't want the whole VS code environment, just the terminal.

**Comment by axonasif** [comment]
Hi @LucBerge, I'm assuming that you're on iOS. Because on android I would rather use the flexible [`Termux`](https://github.com/termux/termux-app), which is OSS as well 😄 

To see what's going wrong with `Termius`, I had installed it today morning.
It seems to be a limitation on how `Termius` implemented their SSH client.

## First approach (relatively easy)

|Easy way|Complicated and repetitive way|The Android way|
|--|--|--|
|https://user-images.githubusercontent.com/39482679/184612126-9c40ada8-afee-4756-82f7-cada179e7a2c.mp4|https://user-images.githubusercontent.com/39482679/184612448-a0ad7f9a-1880-4db4-9845-d3bc1fddef5e.mp4|https://user-images.githubusercontent.com/39482679/184612769-fe892a47-76a9-4319-85e7-8ff0968ddd53.mp4|

**Comment by LucBerge** [comment]
I'm on Android but thank you. It helped me a lot !

**Comment by LucBerge** [comment]
The problem with using the access token is that it changes for every session. Using it is not a permanent solution for me. I found out how to connect with a ssh key.

How to connect with a SSH key via termius
---

- Create a RSA key on Termius
- Import the RSA public key in Gitpod
- Copy the command diplayed by Gitpod. The optain command is `ssh username@server`
- In terminus, create a new host
- Use whatever you want for **Alias**
- Use `server` for **Hostname or IP Address**
- Let the **Port** to `22`
- Use `username` for **Username**
- Left the **Password** empty
- For the `Key`, go find the RSA key using the blue button
- Connect

**Comment by axonasif** [comment]
Thanks for writing that up @LucBerge 😄 

But don't you think this will only work for a specific workspace unless you modify the `username` and `host` each time for a new workspace? I think I recorded the same thing on `Complicated and repetitive way`.

If you are able to use termux, you can just copy the ssh command and paste it into the terminal, it'll just work 🚀

**Comment by LucBerge** [comment]
> But don't you think this will only work for a specific workspace unless you modify the `username` and `host` each time for a new workspace?

This not a problem. I'll create one host per workspace.

> I think I recorded the same thing on `Complicated and repetitive way`.

Your video is black half the time (at least for me). I was not able to use it.

> If you are able to use termux, you can just copy the ssh command and paste it into the terminal, it'll just work.

I don't want to have to copy the url each time I connect. I want to be able to open my SSH client and connect.

**Comment by axonasif** [comment]
> This not a problem. I'll create one host per workspace.

Makes sense. But still lots of manual steps.

> > I think I recorded the same thing on `Complicated and repetitive way`.
> 
> Your video is black half the time (at least for me). I was not able to use it. I have updated the intro of my previous comment.

Seems like android built-in recorder blacks out sensitive stuff.

> > If you are able to use termux, you can just copy the ssh command and paste it into the terminal, it'll just work.
> 
> I don't want to have to copy the url each time I connect. I want to be able to open my SSH client and connect.

Understood, usually I dispose a workspace and forget about it, it's what ephemeral means. But yeah, for some quick SSHing from Phone for casual stuff makes sense this way.
