### ISSUE TITLE
The VSCodeVim extension has very bad performance in GitPod

### ISSUE THREAD

**Issue by andypea** [gitpod-io/gitpod#1212]
### Describe the bug
The VSCodeVim extension provides a vim-like interface for Visual Studio Code. 
When this extension is installed on GitPod the editor runs painfully slowly.

### Steps to reproduce
Install the VSCodeVim extension on GitPod and try to edit a file.

### Expected behavior
A usable editor with vim-like interface.

### Additional Information
I'm in New Zealand and I'm using the free plan, so that may be contributing to the problem.

**Comment by JesterOrNot** [comment]
@akosyakov can you look at this?

**Comment by Kreyren** [comment]
Same issue on my end

**Comment by Kreyren** [comment]
FWIW emacs extension seems to have same issue

**Comment by JesterOrNot** [comment]
See https://github.com/eclipse-theia/theia/issues/5125

**Comment by andypea** [comment]
When the VSCodeVim extension is installed the editor still remains painfully slow even if I set the `Vim::disableExtension` option to `true`. Uninstalling the extension immediately returns the editor to full speed.

I've also tried editing files in an actual copy of Vim opened within the terminal. This is still a little slow, but it performs much better than the Theia editor with VSCodeVim enabled, so I think the issue isn't caused by the latency between me and the GitPod container.

**Comment by andypea** [comment]
I just checked and this problem also exists when using Eclipse Che containers hosted on OpenShift. If you have an OpenShift login you can see an example here:

https://github.com/andypea/openshift-test

**Comment by akosyakov** [comment]
It is an issue how Vim extension is designed, it intercepts each editor keystore and process it to decide what to do: https://github.com/VSCodeVim/Vim/issues/2021 So whenever you press something it is delivered to backend, processed and then sent back. The worst about this extension that it affects performance of other extensions: https://github.com/microsoft/vscode/issues/75627

**Comment by jedwards1211** [comment]
@akosyakov it's kind of the reverse, other extensions can severely affect VSCodeVim's responsiveness

**Comment by dclong** [comment]
Keys are constantly ignore. The extension is barely usable.

**Comment by davidar** [comment]
This is still an issue. I wouldn't mind the lag if not for the fact that it even affects insert mode. Some kind of local echo (like the terminal seems to have?) would be an improvement.

**Comment by jedwards1211** [comment]
Navigating around with vi keys is just as painful as insert mode when the extension host is bogged down

**Comment by jedwards1211** [comment]
UI responsiveness is so sacred that...not even keyboard extensions are allowed to interfere with it, apparently 🙄

**Comment by jankeromnes** [comment]
Hi @andypea, @davidar, @jedwards1211 -- sorry for the over-eager stale-bot here. 😬

Does this problem still happen if you switch your Gitpod IDE to Code in https://gitpod.io/settings/ ? (Actual VS Code is available as an IDE option under "Feature Preview", and will soon become the default IDE in Gitpod)

**Comment by jedwards1211** [comment]
@akosyakov re-reading your comment, I do agree that it's bad to pass every single keystroke back and forth to a separate process using IPC.  But this is VSCode's fault, it doesn't allow any extensions to run in the main process.  Isolation is more important to them than keyboard input latency.

**Comment by davidar** [comment]
> Does this problem still happen if you switch your Gitpod IDE to Code in https://gitpod.io/settings/ ?

![image](https://user-images.githubusercontent.com/24291/111711525-aaaf8180-8897-11eb-9b47-80c1564495b2.png)

**Comment by akosyakov** [comment]
In VS Code Vim extension will run in the web worker and it should improve performance a lot. The issue is it right now that Open VSX does not index web extensions properly yet (to be fair it is not even official VS Code feature yet): https://github.com/gitpod-io/gitpod/issues/3259 As soon as it resolved you can switch to VS Code, install Vim extension and enjoy it without performance degradation.

**Comment by jedwards1211** [comment]
Will all extensions be run in the same web worker?  It will certainly perform better than running them in the backend, but if they're sharing the same worker thread other extensions will still be able to hamper Vim performance like they do in desktop VSCode.

**Comment by akosyakov** [comment]
It is up to an extension to decide, they will need to specify that `web` is a supported extension kind in package.json as well as `browser` entry point for code which can be executed in the web worker. As for now I don't expect that many extensions can satisfy second requirement, probably on Vim.

**Comment by jedwards1211** [comment]
But will all `browser` extensions run in the same web worker, or will they all have their own individual web workers?

**Comment by delucca** [comment]
> In VS Code Vim extension will run in the web worker and it should improve performance a lot. The issue is it right now that Open VSX does not index web extensions properly yet (to be fair it is not even official VS Code feature yet): #3259 As soon as it resolved you can switch to VS Code, install Vim extension and enjoy it without performance degradation.

That is strange.

I've enabled the feature preview, switched to Code as my default editor and was able to install the Vim extension.

But, after installing it, there is a HUGE delay between key press and something happening in the editor.

**Comment by akosyakov** [comment]
> But will all browser extensions run in the same web worker, or will they all have their own individual web workers?

I think yes. We will see how it works when there are other web extensions. I don't expect heavy extensions like TypeScriprt or Java smartness to run there they need fast access to underlying runtimes and fs. 

> That is strange.

https://github.com/gitpod-io/gitpod/issues/3259 is not resolve yet. Until then it should not be possible to install this extension at all in VS Code, that you were able is strange. We are talking about this extension right: https://open-vsx.org/extension/vscodevim/vim

**Comment by delucca** [comment]
> > But will all browser extensions run in the same web worker, or will they all have their own individual web workers?
> 
> I think yes. We will see how it works when there are other web extensions. I don't expect heavy extensions like TypeScriprt or Java smartness to run there they need fast access to underlying runtimes and fs.
> 
> > That is strange.
> 
> #3259 is not resolved yet. Until then it should not be possible to install this extension at all in VS Code, that you were able is strange. We are talking about this extension right: https://open-vsx.org/extension/vscodevim/vim ?

My bad.

Actually I've activated the Code feature preview and when I went back to my code editor it was using Theia instead (it took some time for it to update). So, I've installed it in Theia.

Now that I've tried in the Code editor, I was not able to install (as expected according to this issue).

Looking forward for a solution to this :)

**Comment by akosyakov** [comment]
You can install VSCode VIM extension from Open VSX. And it runs alone in browser web worker.
<img width="1904" alt="Screenshot 2021-06-19 at 09 50 07" src="https://user-images.githubusercontent.com/3082655/122631261-fca8b300-d0e3-11eb-9d4a-a00f6871e060.png">
