### ISSUE TITLE
Workspaces keep reloading 

### ISSUE THREAD

**Issue by AAYAN717628** [gitpod-io/gitpod#12129]
### Bug description

I am not able to open my workspace its keep reloading from preparing workspace and the url changed to `not_found=true#` 
kindly fix these issue 

### Steps to reproduce

by workspace

### Workspace affected

aayan717628-aayanhandle-tspxw9fueho

### Expected behavior

its keep restarting the page again n again

**Comment by NguyenCongVN** [comment]
it's just happened to me, too

**Comment by AlexTugarev** [comment]
That might be another case of a failed workspace start caused by the recent incident, see https://github.com/gitpod-io/gitpod/issues/12128

Does it work now for you?

**Comment by axonasif** [comment]
He posted an update on Discord
<img width="436" alt="Screenshot 2022-08-15 at 3 47 40 PM" src="https://user-images.githubusercontent.com/39482679/184614139-27d2597a-e6c3-4e3a-9fcd-b0ae07423848.png">
