### ISSUE TITLE
[JetBrains] Task should be stopped when closing terminal tab

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#12126]
## Is your feature request related to a problem? Please describe
Closing a tab maintains the task alive. It's very confusing when the IDE disconnects temporarly and on-reconnect the tasks which have been closed, are all back.

Related discussions / links
- [Exiting terminal from Supervisor closes the widget on IntelliJ](https://github.com/gitpod-io/gitpod/blob/8f4543d1703ad7f67a977e9ed579f48113ff5154/components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodTerminalService.kt#L241-L244)
- [Closing the widget on IntelliJ exits the terminal on Supervisor](https://github.com/gitpod-io/gitpod/blob/8f4543d1703ad7f67a977e9ed579f48113ff5154/components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodTerminalService.kt#L342-L367) 
- https://gitpod.slack.com/archives/C01KGM9BH54/p1660144865249169?thread_ts=1660140031.099549&cid=C01KGM9BH54

## Describe the behaviour you'd like
When the terminal tab "X" button is clicked, the task is stopped

**Comment by felladrin** [comment]
Currently, there's no way to detect when a terminal is closed from the Thin Client, and there's also no way to programmatically close the terminal widget on the Thin Client. [[Internal Discussion](https://gitpod.slack.com/archives/C02BRJLGPGF/p1661445229422579)]
I'll open an issue for JetBrains to keep track of and link it here later.

**Comment by felladrin** [comment]
It has been fixed on JetBrains IDEs v223 (Current EAP) [[1](https://youtrack.jetbrains.com/issue/CWM-7222/Cant-detect-that-a-terminal-widget-was-closed-on-Thin-Client)].

It worked like a charm, but now, when we close JetBrains EAP Client (by clicking "X" button in the client window), it also considers that the terminals all terminal widgets were closed on purpose (which, in our case, causes all Gitpod Task Terminals to be terminated).

We now need to try to avoid it from happening. Possibly using `AppLifecycleListener.appWillBeClosed` [[1](https://gitpod.slack.com/archives/C02BRJLGPGF/p1668775333968749?thread_ts=1668774814.801159&cid=C02BRJLGPGF)] to remove this subscription from the widget terminals:

https://github.com/gitpod-io/gitpod/blob/fd4386a68d8ace3cca90cce42ddc082f308c527e/components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodTerminalService.kt#L271-L279

**Comment by felladrin** [comment]
ℹ️ Started testing the abovementioned changes in [this branch](https://github.com/gitpod-io/gitpod/tree/felladrin/avoid-closing-task-terminals-when-client-gets-closed), but had to pause it. Will continue looking into it later.

**Comment by felladrin** [comment]
The [issue on YouTrack](https://youtrack.jetbrains.com/issue/CWM-7222/Cant-detect-that-a-terminal-widget-was-closed-on-Thin-Client) has been marked as resolved, and I could notice an improvement:

If we click "X" button in the Connection Window, and then click "Disconnect", it correctly disconnects without closing the terminals.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/418083/209933964-414d72d4-bc04-4497-82cd-c1618ff9eb03.png">

But if we click "X" button in the JetBrains Client, it behaves differently, and the terminals end up closed.
