### ISSUE TITLE
Move .gitpod.yml into .github folder?

### ISSUE THREAD

**Issue by Fenny** [gitpod-io/gitpod#1213]
Is it possible to move the `.gitpod.yml` into the `.github` folder?

**Comment by JesterOrNot** [comment]
As far as I know, right now, you need the .gitpod.yml in the root directory

**Comment by svenefftinge** [comment]
We are thinking about allowing a `.gitpod` folder that can contain the .gitpod.yml as well as Dockerfile etc. Gitpod is not only for GitHub and looking up the config in a lot of alternative places would slow down the startup process.

**Comment by jankeromnes** [comment]
See also https://github.com/gitpod-io/gitpod/issues/729

**Comment by Kreyren** [comment]
+1 for .github folder

**Comment by Kreyren** [comment]
+1 for .github folder

**Comment by JesterOrNot** [comment]
We also support GitLab, I feel it show to much favor toward GitHub to put the config in a GitHub specific directory.

**Comment by ryo33** [comment]
This is the reason I don't use gitpod for my project. I want to make the root directory as clean as possible.
