### ISSUE TITLE
Make deleteWorkspace work always, irrespective of `phase`

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#12137]
Currently, it only works if a workspace is in "stopped" state. All calls to that method fail with `Unknown workspace manager`.

[GCloud logs](https://console.cloud.google.com/logs/query;query=%22Unknown%20workspace%20manager%22;timeRange=PT24H;summaryFields=jsonPayload%252Fmessage,jsonPayload%252Fpayload%252Fargs%252F0:false:32:beginning;cursorTimestamp=2022-08-15T02:48:22.485Z?project=gitpod-191109)

Context: https://github.com/gitpod-io/gitpod/issues/9571#issuecomment-1214656215

/cc @svenefftinge

**Comment by DevertNet** [comment]
I cannot currently delete 4 of my 4 workspaces. That means I can't use gitpod at the moment. Is there any workaround to delete them?

Do you know approximately how long it takes to solve the problem?

IDs of the stuck workspaces:
devertnet-devertpdfexpo-9vtq848xnuq
devertnet-devertpdfexpo-0ywnw2zsl9y
devertnet-devertpdfexpo-gofbrsea0j6
devertnet-devertpdfexpo-6ez9322xb8y

**Comment by geropl** [comment]
Hi @DevertNet, thx for pointing out. I created https://github.com/gitpod-io/gitpod/issues/12138 for the root cause of your issues, and tried to come up with a fix. If everything goes well that should be in tomorrow.

Meanwhile, I'll fix the DB state for the entries that are in the DB currently.
