### ISSUE TITLE
[JetBrains Gateway Plugin] Make the version number meaningful 

### ISSUE THREAD

**Issue by felladrin** [gitpod-io/gitpod#12141]
Currently, we're not adequately versioning our [releases from JetBrains Gateway Plugin](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions).
Since the beginning, we've been using version `0.0.1`.
We should correctly version it and possibly post an update message for each new release.

Here's a suggestion:
Suppose the JetBrains Gateway version is **2022.2** (Build #GW-**222.3345**.108) and that our current plugin is based on Gtipod's build `#4067`.
So instead of the plugin version being **0.0.1-main.4067**, it could be **2022.2**.4067 or **222.3345**.4067.

To change it, we should look into thes lines:
https://github.com/gitpod-io/gitpod/blob/41b6f1546bd659f8bedd83f989031dfe3dbc6d86/components/ide/jetbrains/gateway-plugin/BUILD.yaml#L20
https://github.com/gitpod-io/gitpod/blob/41b6f1546bd659f8bedd83f989031dfe3dbc6d86/components/ide/jetbrains/gateway-plugin/build.gradle.kts#L30-L34

**Comment by akosyakov** [comment]
We need to have branch name in version besides main. In semver there is qualifier for that?

What are recommendations for that from JB? What other plugins do? I’m not sure why we need to align with versioning of JB distributable?

**Comment by felladrin** [comment]
> We need to have branch name in version besides main. In semver there is qualifier for that?

Hmmm, even the builds from PRs have unique build numbers.
But if it's really needed, we can keep the branch name as it is after the dash. That's correct according to semver.
Ok, so I'm changing my suggestion for one of the following:
- 2022.2.4067-main
- 222.3345.108-main.4067

Because all of those numbers (2022.2, 222.3345.108, main.4067) we have already available to use. So we don't need to calculate anything, just concatenate.

> What are recommendations for that from JB?

There's none. On [docs](https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html) they only say:
```xml
  <!--
  Plugin version. Plugins uploaded to the Marketplace must follow
  the semantic versioning: https://plugins.jetbrains.com/docs/marketplace/semver.html.
  It is displayed in the "Plugins" settings dialog and in the Marketplace
  plugin page.
  -->
  <version>1.0.0</version>
```

> What other plugins do?

Bundled plugins:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/418083/185067240-30fe38ca-9f93-44a8-9627-311f98b37467.png">
<img width="205" alt="image" src="https://user-images.githubusercontent.com/418083/185067321-79934e54-9225-4017-99b1-a015f5c293a0.png">

Third-party plugins:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/418083/185067785-2e1fc57f-fba0-4b6b-af34-0ffb2079fd90.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/418083/185068032-76517000-cf2b-4ce4-a3fa-e635c62aed6e.png">
<img width="305" alt="image" src="https://user-images.githubusercontent.com/418083/185068066-43e91401-ddac-434d-860b-43da6511c41a.png">
<img width="500" alt="image" src="https://user-images.githubusercontent.com/418083/185068113-81fedc33-2b33-45d1-92e6-2bc37c61196c.png">

Our plugin:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/418083/185067193-3a30a191-a69d-4653-8572-b13687fbd860.png">

> I’m not sure why we need to align with versioning of JB distributable?

We don't need to, but to avoid keeping track of the semantic version ourselves, we could use the numbers that are already provided by the software we're following, as it's a plugin.
