### ISSUE TITLE
Underscore shows incorrectly in Terminal

### ISSUE THREAD

**Issue by tallgaijin** [gitpod-io/gitpod#12145]
### Bug description

Underscore characters mess up the Terminal display:
![image](https://user-images.githubusercontent.com/8585296/184778560-f062d5cd-c16c-46d9-ab9e-42087647518d.png)

### Steps to reproduce

Anytime terminal output includes an underscore. Have tried several VScode color themes, it happens with all of them.

**Comment by axonasif** [comment]
Hi @tallgaijin, can you try setting `terminal.integrated.gpuAcceleration` to `off` 🤔 ?

**Comment by axonasif** [comment]
And what browser are you using? Is there any adblocker or such other extensions in play?

**Comment by akosyakov** [comment]
Please try to reproduce with https://vscode.dev/ and report in upstream: https://github.com/microsoft/vscode

**Comment by akosyakov** [comment]
cc @jeanp413 if you seen already some bug in upstream like that
