### ISSUE TITLE
UX feedback for Environment Variables page

### ISSUE THREAD

**Issue by spoenemann** [gitpod-io/gitpod#1214]
### Describe the bug
The UI in https://gitpod.io/environment-variables/ has a blue button "Add Variable" in the bottom right. While editing variables, I have sometimes mistaken that button for "Apply" / "Commit" because it's blue and it's in the bottom right.

### Steps to reproduce
Edit environment variables and apply your changes, but don't read the text in the blue button.

### Expected behavior
I'm not sure what could have improved my experience here. Maybe move the button to the top right?

**Comment by gtsiolis** [comment]
Hey @spoenemann! The description here doesn't match the current state of the app in production or staging. The blue buttons seem to be aligned on the left now. Do you think this is still an issue?

**Comment by spoenemann** [comment]
Right, we can close this.

But #1534 remains.
