### ISSUE TITLE
[code-desktop] switch all users to SSH Gateway

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#12155]
Integrate ConfigCat to enable SSH Gateway for all users in VS Code Desktop extension.

**Comment by jeanp413** [comment]
Configcat is disabled for now

**Comment by akosyakov** [comment]
We implemented it and serving 30% of traffic with SSH gateway now.

**Comment by loujaybee** [comment]
Message from the community: 

> I'm wondering what's the target time for Websocket method as an option instead of SSH. For me, this is currently my biggest blocking point as my ISP sometimes will block SSH (port 22) and it appears that they are putting in place a deep packet inspection method and will detect the SSH traffic even if I redirect to different ports.

Related to: 
- https://github.com/gitpod-io/gitpod/issues/10645

**Comment by akosyakov** [comment]
We switched all gitpod.io users to SSH Gateway.

**Comment by loujaybee** [comment]
**Note:** Does not include Self-Hosted users, for Self-Hosted, please see: 

- https://github.com/gitpod-io/gitpod/issues/12475
