### ISSUE TITLE
Support `gp open --wait`

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#1215]
To allow using gitpod a s a GIT_EDITOR we should allow the cli command to wait until the editor is closed again.
We should align the option with vscode, which uses 
```
-w --wait                         Wait for the files to be closed before returning.
```
see https://code.visualstudio.com/docs/editor/command-line#_command-line-help

**Comment by svenefftinge** [comment]
See also https://community.gitpod.io/t/editor-not-set-to-the-theia-editor/102/5

**Comment by felipecassiors** [comment]
The `gp open --wait` would be awesome! Looking forward to it.

**Comment by svenefftinge** [comment]
The fix/change is now deployed in production.
