### ISSUE TITLE
Long variable names overflow Name column in Project Variables settings  

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12172]
<img width="1121" alt="Screenshot 2022-08-17 at 12 29 18" src="https://user-images.githubusercontent.com/849592/185107715-80ec0865-dbd7-4315-95c4-0b437d4b4fa6.png">

Variables in personal setting are truncated nicely. 👇 
<img width="942" alt="Screenshot 2022-08-17 at 12 28 43" src="https://user-images.githubusercontent.com/849592/185107809-b65a74f9-b80b-4d44-93c9-f1e36e9c8dbe.png">

**Comment by gtsiolis** [comment]
Thanks for the ping, @jldec! I've added this in 🥯 [**Product Design / Scheduled**](https://github.com/orgs/gitpod-io/projects/29).

**Comment by gtsiolis** [comment]
Nice catch, @jldec! This seems to be trivial to fix, opened https://github.com/gitpod-io/gitpod/pull/12234.
