### ISSUE TITLE
Add doc page(s) for "hints and tips" for getting stuff to work with gitpod

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#12185]
Add specific easy-to-find pages for _hints_ and _tips_ for getting stuff to work with gitpod.  Specific stuff.

E.g., people frequently discover<sup>†</sup> that things that they do in a start task aren't persisted - why? because only `/workspace` is persisted (specifically `/home/gitpod` is not persisted, nor is anything in `/usr/` and so on).

This _is_ documented but people have trouble with specific tools.  E.g., `npm` which puts stuff by default into `/usr/local` (apparently, or at any rate _not_ in `/workspace`).

All these tools have supported workarounds - environment variables, or command line arguments, or config files, or something - that control where they install stuff, or look for stuff.

So the suggestion is:  Have a page that explains this.  E.g., it would say if you're using `brew` then by default it installs stuff in `/usr/local` which is fine in your custom Dockerfile but _not_ in your `.gitpod.yml` - you've got to actually _install_ `brew` into `/workspace` if you want brew-built packages to persist.  And `pyenv` wants to put stuff - I forget where, I think your home directory - but you can set the env var `PYENV_ROOT` to where you want it to put things.  And so on and so forth.

And then this page can have _other_ hints and tips too about configuring _specific_ stuff to work _specifically_ in gitpod workspaces...

----

<sup>†</sup> - these issues frequently come up on the discord channels

**Comment by axonasif** [comment]
Hey @david-bakin, thanks for writing that up. I'm going to include your issue on https://github.com/gitpod-io/gitpod/issues/10701

**Comment by pawlean** [comment]
Lou is working on this in this draft PR: https://github.com/gitpod-io/website/pull/2950
