### ISSUE TITLE
Support Setting to Disable "Get Started with Gitpod" Page on Startup

### ISSUE THREAD

**Issue by tomwheeler** [gitpod-io/gitpod#12183]
## Is your feature request related to a problem? Please describe
When starting a GitPod workspace, a "Get Started with GitPod" page shows up by default. Although it is possible for an individual user to uncheck the bottom of the page to suppress this page in the future, there appears to currently be no way for the person configuring a workspace to suppress this page for all users. 

This is a problem for those of us who intend to use GitPod for technical training. In case you have never delivered live technical training before, imagine that you have a few dozen people in front of you and you have to give them instructions. You can't see their screens, and as beginners, they don't yet have the knowledge to distinguish what is or is not important. You can describe the steps they need to perform, but if there's an unexpected window/tab, they will be confused and it will derail the class. The absolute worst case is when some of these students have the window and others do not, which will happen if some (e.g., more advanced students) close the tab and/or uncheck the box to suppress this page in the future. This has already happened with me and a co-worker, who had no idea what page I was talking about because it does not come up for him.

## Describe the behaviour you'd like
I am requesting a configuration parameter that, when added to the `.gitpod.yml` file in a repository, will suppress the "Get Started with Gitpod" Page for workspaces created based on that repository. I have no strong opinion about what this parameter is called, what its value might be, or even whether it goes into `.gitpod.yml` file specifically. I really just care about the outcome, which is that I can be sure that in 100% of cases, the only windows that show up in the workspace are the ones that I have specifically configured. In other words, I can be sure that the workspace looks exactly the same for every student in the class.

To be clear, I am not suggesting that you change the _default_ behavior. It's fine that this "Get Started" page shows up by default. I just want a way to explicitly disable it for all workspaces created from a given repository.

## Describe alternatives you've considered
I am not aware of any alternative approach to achieve what I have described. Adapting to the current behavior is not really an acceptable solution, as consistency and predictability are pretty essential to a good training experience.

## Additional context
For context, this was recently [brought up by another user in Discord](https://discord.com/channels/816244985187008514/1003040051002880131/1006172682829692948). I found that thread because I was searching for the same thing (a way to suppress this page). I wasn't able to find an issue filed by OP requesting this capability, so I am filing it.

**Comment by akosyakov** [comment]
Have you tried to configure `workbench.startupEditor`: `none` in VS Code Settings of your project and commit?  [[1](https://stackoverflow.com/questions/43453467/vscode-always-opens-welcome-screen-on-startup-instead-of-last-opened-folder)]

**Comment by tomwheeler** [comment]
Yes, I tried that and found that it did not work and the other user in Discord (mentioned in the "Additional context" section) also reported that they found this setting did not work for them. 

I will be very clear about what I tried, in case I am doing it wrong. In the root of my repository, I created a  `.vscode` directory and created a `settings.json` file in that directory. Here are the contents of that file:

```
{
    "workbench.startupEditor": "none",
    "workbench.editorAssociations": 
        {
            "README.md": "vscode.markdown.preview.editor",
        }
}
```

I am sure this file is getting used because the other change it contains makes VSCode show the `README.md` file in preview mode rather than showing the markdown source. However, After adding the `"workbench.startupEditor": "none",` line, committing and pushing the change to GitHub, and then launching a new workspace, I observed that the unwanted "Get Started with GitPod" page is still being shown. After seeing this, I checked the `.vscode/settings.json` file and observed that the `"workbench.startupEditor": "none",`  line was present, so I conclude that this does not work.

**Comment by jmls** [comment]
did you find a solution ? I also want to prevent this from showiing by default

**Comment by tomwheeler** [comment]
> did you find a solution ? I also want to prevent this from showiing by default

No, unfortunately, I did not find a solution to this.

**Comment by jeanp413** [comment]
@tomwheeler This is fixed in vscode web `1.71.1`, you should see it one more time when opening a new workspace but then it won't show anymore, let me know if that's not the case

**Comment by loujaybee** [comment]
Thanks for raising @tomwheeler - aside from the workshop use case, I wanted to note that this also causes a challenge for Gitpod use cases where users want to use Gitpod as part of some "onboarding" flow, either onboarding into an Open Source project, or just into a project in general. We want to allow users the ability to configure as much of the onboarding as possible to be tailored to their needs, showing the changelog and/or getting started with Gitpod might not make sense, as users might want to be able to override these with their own Gitpod instructions, or project onboarding notes. 

Noting that principally this is the same request as: 

- https://github.com/gitpod-io/gitpod/issues/12704

Any solution that is applied here, should likely also apply to the changelog.

**Comment by loujaybee** [comment]
Assigning to @jeanp413 to close when released / verified as working !

**Comment by jeanp413** [comment]
Closing as already fixed on stable
