### ISSUE TITLE
"No space left on device" despite disk being not full...

### ISSUE THREAD

**Issue by gounthar** [gitpod-io/gitpod#12182]
### Bug description

Hi,

I am experimenting with a Jenkins controller there: https://gitpod.io/#https://github.com/gounthar/MyFirstAndroidAppBuiltByJenkins/tree/damien-cleanup 

The disk is 33.5% full, the `/workspace` is 79% full, but I get `Download failed after 1 attempts: write /var/lib/docker/tmp/GetImageBlob3575330226: no space left on device`

I am using docker in docker, and  `/var/lib/docker` does not exist on the "machine", so I guess it's a limitation in the way docker runs...

```bash
sudo df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/md42        30G   24G  6.5G  79% /workspace
```

### Steps to reproduce

Try https://gitpod.io/#https://github.com/gounthar/MyFirstAndroidAppBuiltByJenkins/tree/damien-cleanup  (admin/butler).

### Workspace affected

https://gounthar-myfirstandroid-yhe5d8e8fit.ws-eu61.gitpod.io/

### Anything else?

Thanks.

**Comment by atduarte** [comment]
For additional context, disk usage in the node during the lifetime of the workspace: 
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/666176/185370898-277a50f7-4346-48f7-a29e-520dfd1f8a57.png">

**Comment by atduarte** [comment]
@gounthar did it happen again?

**Comment by gounthar** [comment]
No, thank you, all sorted out. 🙏
