### ISSUE TITLE
Use Page Title Instead of "Simple Browser"

### ISSUE THREAD

**Issue by tomwheeler** [gitpod-io/gitpod#12184]
## Is your feature request related to a problem? Please describe
In my workspace, I want to open a browser for a web application running on port 8080. I use `gp preview $(gp url 8080)` in my `.gitpod.yml` to do this. Although this opens the browser, the title of the browser tab is "Simple Browser" for some reason, rather than the actual page title provided by the web application. This is very confusing because it doesn't distinguish which (or which of the multiple web applications available in this workspace) is currently being shown.

## Describe the behaviour you'd like
Ideally, the embedded browser would set its tab title based on the title of the current page. If this is not possible, then an acceptable workaround would be to support a `--title <string>` argument for `gp preview` so that we can set at least set a static title and provide some context to the user about what this browser is showing. 

## Describe alternatives you've considered
I attempted to use the `--external` flag for `gp preview`, thinking that this would correctly show the page title. Although this does show the page title, it's a worse user experience because my testing in Safari shows that it displays a scary message "The browser interrupted the opening of a new tab or window. Press 'Open' to open it anyway." and opens in a new window rather than a new browser tab within the current window. Since Chrome, Firefox, and Microsoft Edge might have some different behavior, it makes writing exercise instructions much more complicated.

## Additional context
My use case is using GitPod as an exercise environment for technical training. Thus, I am not the end user in this situation, but rather the person configuring the environment that an end user will use. Their usage will be asynchronous from me in a self-paced training scenario, so having to explain what "Simple Browser" represents or how to interpret scary messages on dialog boxes when opening external windows is a distraction from the actual learning objectives.

**Comment by akosyakov** [comment]
Functionality of Simple Browser is implemented in upstream: https://github.com/microsoft/vscode Could you file an issue whether to display title of the page instead?

**Comment by tomwheeler** [comment]
Done. I have now filed [issue #158505 with VSCode upstream](https://github.com/microsoft/vscode/issues/158505)
