### ISSUE TITLE
Black blocks in terminal at every underscore

### ISSUE THREAD

**Issue by TamaMcGlinn** [gitpod-io/gitpod#12190]
### Bug description

Whenever an underscore _ is encountered in the terminal window, a black box is drawn around that character.

![Screenshot from 2022-08-18 08-27-04](https://user-images.githubusercontent.com/5008897/185309315-328de3f2-ade9-490d-a56a-ed4c660bd1c0.png)

### Steps to reproduce

Type `echo "_hi"` into a terminal window.

### Expected behavior

It should look the same as on a native terminal, just `_hi`

**Comment by axonasif** [comment]
Possible duplicate of https://github.com/gitpod-io/gitpod/issues/12145

**Comment by akosyakov** [comment]
Do you use Firefox?
