### ISSUE TITLE
fetching the GitHub Education API failed with status 401: Unauthorized

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#12203]
### Bug description

In most Gitpod installations (every one except production i.e. https://gitpod.io), we see these errors very frequently in the logs:

```
fetching the GitHub Education API failed with status 401: Unauthorized

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at EligibilityService.<anonymous> (/app/node_modules/@gitpod/server/dist/ee/src/user/eligibility-service.js:88:37)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@gitpod/server/dist/ee/src/user/eligibility-service.js:19:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

We don't think this error is problematic (it's just that checking the GitHub student status fails), however it's very noisy, and often distracts from "real problems" by acting as a "red herring" (i.e. investigate a new bug, check the logs, see this, report it -- but that wasn't the relevant error message).

We should probably fix it in dev to make our lives easier.

### Steps to reproduce

1. Use any Gitpod preview or staging environment
2. Check the server logs

### Expected behavior

When checking the student status on GitHub fails, we shouldn't be as loud about it (either log a clear, minimal warning, or don't log anything at all).

**Comment by geropl** [comment]
@AlexTugarev I believe you had a commit with a fix somewhere...? Cannot find it anymore.

**Comment by AlexTugarev** [comment]
this happens to happen in the `isStudent` check. AFAIR it was a missing `return`. commit is gone, but that's a quick fix.
