### ISSUE TITLE
Support altering project-level environment variables with `gp env`

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#12208]
## Is your feature request related to a problem? Please describe

Right now `gp env` can only alter the [user-level environment variables](https://gitpod.io/variables). That means, if you try to add a var like so: `gp env foo=bar`, it will get registered under your personal account but not project. Similarly, it will only list your user vars when `gp env` is run.

## Describe the behaviour you'd like

Add a CLI flag to specify the target, either user or current project.

## Additional context

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3ptfu)

**Comment by geropl** [comment]
@akosyakov `gp` is owned by Team IDE, right?

**Comment by axonasif** [comment]
not stale 😄

**Comment by akosyakov** [comment]
We are not going to allow altering, but only align `gp env` to show all workspace env vars. In order to change a user should go to the project settings.
