### ISSUE TITLE
Pre install Vscode Extensions in self-hosted

### ISSUE THREAD

**Issue by pyhp2017** [gitpod-io/gitpod#12201]
## Is your feature request related to a problem? Please describe

I want to pre install some extensions in "every" workspaces (without setting it in .gitpod.yml) just when users create a new workspace they already have the extensions 

## Describe the behaviour you'd like

Just by uploading vsix in "Advanced customization" section, we could have our extensions pre installed 

## Describe alternatives you've considered

I used bashscript and I put it into Base Image which be executed after starting in every workspace and it will install the extension using gp-code --install-extension

**Comment by lucasvaltl** [comment]
Moving this to the IDE team, as this is not a self-hosted exclusive issue and rather an an IDE issue:)

**Comment by akosyakov** [comment]
> Moving this to the IDE team, as this is not a self-hosted exclusive issue and rather an an IDE issue:)

@lucasvaltl Are you sure that installation configuraiton is it a right place? Maybe better place would be team configuration? cc @geropl @svenefftinge 

@pyhp2017 Do you have a single team?

We can allow to pass additional list of VS Code extensions to install besides from .gitpod.yml if there is a team which will actually use it.

**Comment by loujaybee** [comment]
Thanks for raising, @pyhp2017

You're not the first person to mention this requirement. I think there are multiple issues and potential solutions: 

1. Customers or users who want default extensions in all workspaces. A dedicated feature for this might make sense, but this also might be better served by improved `.gitpod.yml` defaults that are inherited in a cascade effect by projects. 
2. For self-hosted customers who want much more fine-grained control on security for extensions, I think the epic for self-hosted Open VSX will likely be the best place to implement this governance. 
- #12004

> I used bashscript and I put it into Base Image which be executed after starting in every workspace and it will install the extension using gp-code --install-extension

Glad to know you have a workaround for now, this is what I would have suggested 🙏
