### ISSUE TITLE
[Preferences View] settings description is not readable

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1221]
### Describe the bug

In preferences the extension that has long description are not readable:
![image](https://user-images.githubusercontent.com/11302521/74466036-c5464880-4e96-11ea-8a63-b0d57863c071.png)

Even when i make the screen larger:
![image](https://user-images.githubusercontent.com/11302521/74466091-e018bd00-4e96-11ea-83af-ee34a03cd2ca.png)

### Additional Information

I would assume that allowing multiline for these might make them more readable

**Comment by svenefftinge** [comment]
The settings editor is generally in a bad shape and going to be replaced completely, soon.

**Comment by Kreyren** [comment]
@svenefftinge that would be cool i hate the vscode's preferences and prefer atom-like.
