### ISSUE TITLE
Feature Request: Support a description or notes on a given workspace

### ISSUE THREAD

**Issue by mickmister** [gitpod-io/gitpod#12216]
## Is your feature request related to a problem? Please describe

I want to be able to distinguish different workspaces, more thoroughly than a short title

## Describe the behaviour you'd like

Set a description or add notes/details to describe the workspace. This content should be visible from the workspace dashboard

**Comment by axonasif** [comment]
Possible duplicate: https://github.com/gitpod-io/gitpod/issues/7737

Oh and you can change your workspace name/description from https://gitpod.io/workspaces

**Comment by mickmister** [comment]
@axonasif At the moment you can "name" the workspace, but I'm wanting to provide a description with more text. Like a paragraph explaining why I made the workspace, and possibly the current stage or next steps for my plans with the workspace.

**Comment by geropl** [comment]
> Like a paragraph explaining why I made the workspace, and possibly the current stage or next steps for my plans with the workspace.

Hm, this feels a bit at odds with how we envision workspace: create for a single task, develop, push and "throw it away". What's the reason you watn to re-use your workspace? (or did I get this wrong? 🤔)

**Comment by axonasif** [comment]
_Maybe to have some memories contained within workspaces, just so that you can revisit in future time_ 😆

**Comment by mickmister** [comment]
@geropl Many of my larger tasks/branches/PRs are longstanding. I've been using each workspace to capture ongoing progress on separate tasks. Some tasks have specific setups for the task, so it's beneficial to have it as a saved workspace while I'm still working on them
