### ISSUE TITLE
Better way to see the Workspace Dashboard

### ISSUE THREAD

**Issue by byjg** [gitpod-io/gitpod#12210]
## Is your feature request related to a problem? Please describe
It is not a problem per see; however, it led me to click on the wrong icon several times. The Workspace Dashboard shows the workspace name, GitHub, pull request, branch and additional options. All information in this line is clickable to different links and the design doesn't show that all links are clickable and to different places.
![image](https://user-images.githubusercontent.com/981924/185444129-75f73041-d586-4ff3-b03b-7b4adeaf4eb7.png)

## Describe the behavior you'd like
Since "open" is the most used option, we should move to outside the "hamburger" menu. Go to Github also is an option, but it isn't in the menu. So we could either add it to the menu OR create a highlight for it too. 
![image](https://user-images.githubusercontent.com/981924/185444668-e567e189-5da2-4f45-952d-a419f1a5629d.png)

## Describe alternatives you've considered
Another option I've considered and simpler is to add the external link icon. 
![image](https://user-images.githubusercontent.com/981924/185446373-a963a73e-1bed-48a3-ac4d-03a73652487d.png)

## Additional context
TBH, I am not a designer. That is a suggestion on how it could be easier to access the workspace.

**Comment by gtsiolis** [comment]
Thanks for the feedback, @byjg! You're right. This was part of the first iteration for the workspaces list and we're already working on improving the workspaces page in https://github.com/gitpod-io/gitpod/issues/12033, see also early design in https://github.com/gitpod-io/gitpod/issues/12033#issuecomment-1219722431.

Let me close this issue in favor or https://github.com/gitpod-io/gitpod/issues/12033.
