### ISSUE TITLE
Prebuilds stopped being used when creating new workspaces

### ISSUE THREAD

**Issue by mickmister** [gitpod-io/gitpod#12217]
### Bug description

When I create a new workspace from a branch that has a completed prebuild, that prebuild is not being used. This was working correctly a few hours ago.

### Steps to reproduce

Creating a workspace from https://gitpod.io/#github.com/mickmister/mattermost-gitpod-config should create a workspace using a prebuild, but it instead recreates the workspace from scratch.

I have tried automated and manual prebuilds opened right from Gitpod's UI as well. The prebuilds are still not being used.

### Example repository

https://gitpod.io/#github.com/mickmister/mattermost-gitpod-config

**Comment by mickmister** [comment]
I'm not sure what other information I can provide here. Prebuilds aren't working in my projects and I don't know why. Has anyone else been experiencing this?

**Comment by chuck-confluent** [comment]
I've been experiencing this.

.gitpod.yml file: 
- https://github.com/confluentinc/demo-database-modernization/blob/3d7e9a692ed2197240bd85ed4468687084354c6c/.gitpod.yml

Prebuild logs:
![image](https://user-images.githubusercontent.com/48225759/195198819-f3f87f7e-3ef8-4fbb-91f1-6b7b46ac0447.png)

My python virtual env is being created, packages installed, and the CLI is being installed in prebuild. But when I launch, it doesn't say "loading prebuild" and nothing has been done. The task isn't even named correctly -- it's called "Gitpod Task 1", not "demo".

**Comment by chuck-confluent** [comment]
I just tried with a different github account in an incognito browser and it worked as intended. There's some weird auth issue happening. Try logging out and logging back in or even clearing your browser cache.
