### ISSUE TITLE
Use a different sorting icon color on dark theme

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#12225]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/12135#discussion_r949240961:

> Ideally, we could use a different color for the SVG icon on light and dark theme but it's ok to leave this out of the scope here. [FWIW](https://en.wiktionary.org/wiki/FWIW), `gray-400` for light and `gray-500` for dark theme.

| Icon (Light) | Icon (Dark) (BEFORE) | Icon (Dark) (AFTER) |
|-|-|-|
| <img width="430" alt="header-light" src="https://user-images.githubusercontent.com/120486/185583723-890a4cf7-d39a-46b1-b25c-b787e0e43502.png"> | <img width="430" alt="header-dark-before" src="https://user-images.githubusercontent.com/120486/185583727-2b79f273-c540-4e33-a6c7-e275839b429d.png"> | <img width="430" alt="header-dark-after" src="https://user-images.githubusercontent.com/120486/185583729-f0db42f4-5821-45cd-8896-b78181540712.png"> |

**Comment by priyal32** [comment]
Hi! is this issue still open to work on?

**Comment by gtsiolis** [comment]
@priyal32 Yes! Feel free to open a pull request and reference this issue. 🏓

**Comment by priyal32** [comment]
@gtsiolis I'm new to open source and this community so I'm kinda having trouble locating the file. As I understand it should be in one of the folders in gitpod/components/dashboard/src but I'm not sure where to go from there. Do I go to components and then arrow.tsx? Any help would be appreciated!

**Comment by priyal32** [comment]
@gtsiolis I think I found the file (https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/UsageView.tsx) but the sort arrow is not imported. I see that it was imported in like one of the previous versions?

**Comment by gtsiolis** [comment]
Nice catch, @priyal32! ⚾ 

We've recently removed the sorting functionality but we'll probably come back to this later. Let me close this for now as this is no longer relevant.
