### ISSUE TITLE
UX: Terminal position?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1222]
Currently the terminal gets in the way most of the time.

Is there a way to invoke terminal by a shortcut and then closing it with the same shortcut in such a way that would overlap over the current workspace? i.e like pop-up ?

**Comment by JesterOrNot** [comment]
@Kreyren does this help?
https://www.loom.com/share/3507395e0e8747c398fd25cfd131b7de

**Comment by Kreyren** [comment]
@JesterOrNot It would if it would be possible to set on a key stroke which does not seem to be the case since theia only allows to open a new terminal.

Ideally this should be independant from the windows on the instance so that it wouldn't mess up with overlay and did not take around 2sec for overlay to resize after its been toggled off.

**Comment by JesterOrNot** [comment]
Oh ok @Kreyren CTRL+J

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/74480104-efd3d980-4e75-11ea-8efc-704d3a20e25d.png)

**Comment by Kreyren** [comment]
thanks! but that still solves only part of the issue

**Comment by JesterOrNot** [comment]
What do you mean by a popup?

**Comment by JesterOrNot** [comment]
@Kreyren something like this?
![image](https://user-images.githubusercontent.com/50386709/74490294-b313dc80-4e8d-11ea-9fe5-81bcba3ed666.png)

**Comment by Kreyren** [comment]
@JesterOrNot Not sure i was rather thinking about something like this being used as a terminal

![image](https://user-images.githubusercontent.com/11302521/74558734-1c195400-4f63-11ea-9f41-1c2076642264.png)

So that it would be independent from the windows and could be called on demand while it opening under 1 sec

**Comment by JesterOrNot** [comment]
Thanks for the suggestion :smile:, however, his is more of a theia thing I'll file an issue of there for it to be tracked

**Comment by Kreyren** [comment]
@JesterOrNot thanku

**Comment by JesterOrNot** [comment]
For future tracking please see https://github.com/eclipse-theia/theia/issues/7158
