### ISSUE TITLE
Configure UsageConfig.billInstancesAfter

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#12223]
We already implemented billInstancesAfter but we still need to configure it.

links:
 - [config](https://github.com/gitpod-io/gitpod/blob/e437e1868072dfad1d195031a4709a254bd60dc8/install/installer/pkg/config/v1/experimental/experimental.go#L232)
 - discussion about the value to set there: https://gitpod.slack.com/archives/C027AUU7BC3/p1660832504534679 (note that the installer expects Go `time.Time`!)

**Comment by laushinka** [comment]
GitHub didn't pick up the related issue links. Closing manually.
