### ISSUE TITLE
it saying permissions are suddenly not granted

### ISSUE THREAD

**Issue by edking94** [gitpod-io/gitpod#1223]

**Comment by jankeromnes** [comment]
Hi @edking94, thanks for reporting this problem.

It looks similar to https://github.com/gitpod-io/gitpod/issues/1210, right?

**Comment by AlexTugarev** [comment]
@edking94 this is likely the same as https://github.com/gitpod-io/gitpod/issues/1210 
'Working on a resolution.

**Comment by edking94** [comment]
thank you!

**Comment by jankeromnes** [comment]
Closing this issue as duplicate. Please subscribe to #1210 for updates.
