### ISSUE TITLE
Introduce gp command to add env from .env file

### ISSUE THREAD

**Issue by thisisommore** [gitpod-io/gitpod#12243]
## Is your feature request related to a problem? Please describe
When we have .env file with variables already there and we want to persist that in gitpod way using `gp env` we have to manually run the command `gp env KEY=value` for each variable, which decreases my productivity for setting new repos

## Describe the behaviour you'd like
I would like to run command which reads and specified file like .env and persist that key and values of environment variables for that repo, like what `gp env` does. 
For example
```bash
$ gp env-read .env
> 13 Environments added
```

**Comment by axonasif** [comment]
Hey @thisisommore 👋 

As a workaround for now you can use the following to save your time:

```bash
while read -r line; do {
   [[ ! "$line" =~ ^\# ]] && gp env "$line";
} done < .env
```

**Comment by thisisommore** [comment]
@axonasif can this be never stale?

**Comment by axonasif** [comment]
@thisisommore let's comment each time when stalebot tries to close it for this issue 🙂

**Comment by thisisommore** [comment]
@axonasif can we add `meta: never-stale` instead 😃

**Comment by axonasif** [comment]
I added it to one of your other issue that was also stale.

**Comment by thisisommore** [comment]
@axonasif I don't get it
So this issue will also act as never stale?
Are this two(this and one #12877) issues linked anywhere?
