### ISSUE TITLE
Email already in use

### ISSUE THREAD

**Issue by giseletoledo** [gitpod-io/gitpod#12246]
### Bug description

When I try to enter with gitlab or github, says that my email it's already in use.

### Steps to reproduce

Try to login
Click on the button github or gitlab

Email address already used in another account. Please log in with github.com.

### Expected behavior

Open some workspace

**Comment by svenefftinge** [comment]
Is that not your email? Or do you have a two github accounts using the same email (I believe that is not possible).

**Comment by jldec** [comment]
Hi @giseletoledo, please share the email that you have on your GitHub or GitLab account by contacting support via email contact@gitpod.io or the [support page](https://www.gitpod.io/contact/support). This will enable us to investigate. Please mention this issue. #12246

If you signed up to Gitpod with a previous (now deleted) GitHub or GitLab ID and are using a new ID with the same email, then we will need to remove the old orphaned account to unblock you.

**Comment by giseletoledo** [comment]
Thank you, i send it to support.

Em dom., 2 de out. de 2022 17:05, Jürgen Leschner ***@***.***>
escreveu:

**Comment by EricJones720** [comment]
I'm having the same issue. New user. How do I fix this? Thanks in advance.
