### ISSUE TITLE
[code-desktop] Align on a way to ensure Gitpod API compatibility between IDE clients and SH installations.

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#12254]
- We decided to change how ouath2 endpoint works. It should ignore unknown scopes, verify and return only subset of known scopes. Clients should use returned scopes as source of truth to check whether features are present. It is for instance how GitHub auth works.
- We will still need to adhere to `api/version` for 2 SH releases which has changes to ouath2 endpoint. After this check can be removed.

Internal RFC [[1](https://www.notion.so/gitpod/Gitpod-Server-API-compatibility-check-ee00fcfe60a84c1e8e018ab6c06c1f5d)]

**Comment by loujaybee** [comment]
Current update: PR Is up:

- https://github.com/gitpod-io/gitpod/pull/12446

But we need to resolve some of the outstanding discussions, would be good to get @geropl and WebApp teams help to unblock this one 🙏

**Comment by jeanp413** [comment]
Closing this as it got deployed
