### ISSUE TITLE
arduino

### ISSUE THREAD

**Issue by sofa82** [gitpod-io/gitpod#1225]

**Comment by JesterOrNot** [comment]
Hello @sofa82, and welcome to GitHub and our community! 😄 Can you help explain your issue?

**Comment by sofa82** [comment]
Hellow my frind

**Comment by sofa82** [comment]
I want to make a smart irrigation system using arduino

**Comment by JesterOrNot** [comment]
Cool! What do you need to do that?

**Comment by sofa82** [comment]
I want to bluid this system using real time clock to operate the system according to specific time rang and i want to link the system to the Internet and i do not know how

**Comment by JesterOrNot** [comment]
This is not really my field but you could try https://www.gitpod.io/blog/local-services-in-gitpod/
