### ISSUE TITLE
Cap reported Usage to max(Usage, SpendingLimit) before reporting to Stripe

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#12264]
When creating an invoice, we need to cap the invoice to maximum of the usage limit. This is to ensure we conform to users expectations.

In practice, this means the following:
* When we are updating an invoice with a new value, we need to take into consideration the spending limit set.
* When a spending limit is greater than the current value, do nothing special.
* When the spending limit is lower or equal to current used value, cap the invoice to the spending limit.

Optionally:
* Tag the invoice (in Stripe) with metadata saying what the spending limit is, such that admins are not surprised when it is not increasing and do not need to hunt across multiple systems.

The number of credits used can exceed the spending limit due to eventual consistency in the system between reconciliation of usage starting of new workspaces. As such, this difference is where we are losing money. To monitor how much this diff is, we want to expose a metric which measures the diff between real usage and spending limit for each attribution.

* Add a metric which tracks "billing accuracy" or "credits lost"

Side change:
- Move ownership of the DB Cost Center to the Usage Component

**Comment by geropl** [comment]
@laushinka could you document the outcome of the Slack discussion here? 🙏
