### ISSUE TITLE
[ide] Investigate the impossibility of connecting via SSH to some workspaces using custom Docker images

### ISSUE THREAD

**Issue by felladrin** [gitpod-io/gitpod#12265]
We've found one case where the use of a Custom Docker Image in .gitpod.yml caused the SSH connection to fail (which makes it also impossible to connect using JetBrains IDE): https://github.com/spring-projects/spring-petclinic/

In this specific repository, it seems it started failing after this change: https://github.com/spring-projects/spring-petclinic/commit/5aef5c380c564d9c22afef3e173b1ec6af2c54bd

_Originally discussed in https://github.com/gitpod-io/gitpod/issues/12163#issuecomment-1222253943_

**Comment by jeanp413** [comment]
I was with the impression it is not expected for gitpod to work with MS docker images as they have custom users/changes. I remember trying and sometimes it didn't even build, have that changed?

**Comment by jeanp413** [comment]
This is funny, it doesn't even work when trying to connect from the terminal xD cc @iQQBot

**Comment by loujaybee** [comment]
> I was with the impression it is not expected for gitpod to work with MS docker images - @jeanp413 

This is somewhat related to the ongoing challenge we have with Gitpod about the visibility of the underlying image for a Gitpod workspace. It's possible that we want to mark certain images or images with certain characteristics as incompatible (or at least warn users of unexpected behaviours):

- https://github.com/gitpod-io/gitpod/issues/10683

**Comment by akosyakov** [comment]
It seems to because this image has another user and it somehow breaks installing SSH keys.
