### ISSUE TITLE
[jb] Investigate how to improve the development cycle of JetBrains Backend Plugin

### ISSUE THREAD

**Issue by felladrin** [gitpod-io/gitpod#12268]
Currently, the development of the JetBrains Backend Plugin follows this cycle:
1. Make edits in files from `components/ide/jetbrains/backend-plugin`.
2. Run `components/ide/jetbrains/backend-plugin/launch-dev-server.sh`
3. Check if the changes are working. Then, restart the dev server and check if changes continue running (sometimes the second run reviews some problems).
4. Push the code, and create a Pull Request with Preview Environment. That's where we spend a lot of time: Werft takes around 25 minutes to build [[1](https://werft.gitpod-dev.com/job/gitpod-build-felladrin-12030.26)].
5. Test both Stable and Latest versions of the IDE in the Preview Environment to confirm they're working.
6. If everything is fine, set the Pull Request as Ready for Review. If not, restart from Step 1.

It takes too long to try new changes in Preview Environments since the plugin build triggers the rebuild of 4 images.
We need to find a way to make this process faster, mainly in steps 4 and 5.
Maybe we can optimize image builds or deliver plugins at runtime via IDE proxy.

**Comment by loujaybee** [comment]
Waiting for the deployment of this.
