### ISSUE TITLE
Module not found.

### ISSUE THREAD

**Issue by Yash-Varshney** [gitpod-io/gitpod#1226]
Hey devs,
I was working on golangci-lint. but my code raise an exception that --
Exception: b'/home/gitpod/.pyenv/versions/3.7.6/bin/python3.7: No module named golangci-lint\n'
any idea How to resolve ?
Thanks

**Comment by JesterOrNot** [comment]
Hello @Yash-Varshney and welcome to the Gitpod community 😄! Can you send a link to the repo in question?

**Comment by Yash-Varshney** [comment]
hye. I didnt get you. I was developing shouldi api of dffml.
https://ad5f7ab5-f1cb-4feb-8387-d42bbaa03ed6.ws-ap01.gitpod.io/#/workspace/shouldi
this is link to the repo.
thanks

**Comment by Yash-Varshney** [comment]
sorry for the wrong info.
the golangci_lint module is not a python module. I was looking it in python3.7
Does anyone know the relative path for go modules ?

**Comment by JesterOrNot** [comment]
`/home/gitpod/go` is the goroot

**Comment by svenefftinge** [comment]
`GOPATH` points to `/workspace/go`

**Comment by Yash-Varshney** [comment]
thanks for the help !!
