### ISSUE TITLE
[dashboard] notify users when their preferred workspace class is overidden

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#12279]
## Is your feature request related to a problem? Please describe

When starting a new workspace from the context of a prebuild, the context user's preferred workspace class might be "too small" and be upgraded. For example, from standard to large.  A side effect of using a larger workspace class is a higher burn rate for the user's credits, assuming they are enabled for usage based pricing. 

## Describe the behaviour you'd like

When we do an implicit upgrade of the workspace class (say from Standard to Large) we communicate to the user:
1. That the upgrade happened 
2. Related usage of the upgraded class will result in faster burn of their credits

## Describe alternatives you've considered

Notify them of the upgrade on the Starting page:
![image](https://user-images.githubusercontent.com/1272076/185997363-27eb1407-0273-40d3-b336-4d3320886db1.png)

Some benefits for using the Starting page:
1. We implement once
2. We can show the notification to the user early in the life cycle. For example, it could be visible: when we're adding a node to a cluster (preparing resources), pull the image or loading the prebuild. 

Notify the user within the IDE. Some cons to using the IDE:
1. It may have to be done for many IDEs.
2. It's later in the life cycle. So, you may find, after a couple minutes of waiting for a workspace to start from a prebuild, that the upgrade has happened, and then take corrective action (work with the person who created your project to reset their preference,  rerun the prebuild, and then try starting a workspace again).

## Additional context

[Related epic](https://github.com/gitpod-io/gitpod/issues/8261)

**Comment by kylos101** [comment]
Hi @gtsiolis :wave: , @geropl and @Furisto and I were talking about this today, that we currently upgrade the user's workspace class in some scenarios, but don't do a good job of communicating the upgrade (or its impact) to them.

Could we ask for your help on this one? Where do you think it would make sense to communicate the workspace class upgrade?

@geropl @Furisto can you think of any other ideas for notifying the user of the upgrade that I missed?

**Comment by Furisto** [comment]
> @geropl @Furisto can you think of any other ideas for notifying the user of the upgrade that I missed?

Do we have a common understanding that notifying the user about the upgrade of the workspace class is a good first step, but not the final solution? The desired solution for me would be to inform the user that a prebuild is available, but that their currently selected workspace class is not sufficient. They then can either choose from the workspace classes that are eligible or skip the prebuild and continue with their configured workspace class.

**Comment by geropl** [comment]
I think that's the "automatic upgrade" situation is the most important to notify users about, yes.

> The desired solution for me would be to inform the user that a prebuild is available, but that their currently selected workspace class is not sufficient. 

That is possible as well. But we have to be careful to not introduce too many of those modals to startWorkspace.

Personally, I don't have hard feelings here, and like to rely on @gtsiolis and @jldec to weight in with their better UX overview. I think we still need to learn how to best configure workspace classes. I could imagine that this is one of the properties of the CostCenter paying for the workspace: "Automatic Upgrade of Workspace Class: ask every time / do automatically" or so...
