### ISSUE TITLE
Custom image builds are failing using gitpod/workspace-base

### ISSUE THREAD

**Issue by lechien73** [gitpod-io/gitpod#12310]
### Bug description

When opening a custom image with Gitpod, the build fails with the error:

13 INTERNAL: cannot start build: "rpc error: code = Unknown desc = pods \"imagebuild-421b3860-9c1a-4a2e-a47d-2a9028ebcf8b\" is forbidden: PodSecurityPolicy: unable to admit pod: []"

I created a minimal custom build to check.

### Steps to reproduce

1. Open the https://github.com/lechien73/blankbuild repo
2. Try to open in Gitpod
3. The build fails

### Expected behavior

A new, blank IDE workspace created

### Example repository

https://github.com/lechien73/blankbuild

**Comment by axonasif** [comment]
Hey @lechien73, thanks for reporting. It was solved shortly on that day 😄 
https://www.gitpodstatus.com/incidents/p35ggryhtszy
