### ISSUE TITLE
finalizeWorkspaceContent gets cancelled sometimes erronously

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#12318]
### Bug description

It seems like sometimes (not sure how often) `finalizeWorkspaceContent` may get cancelled, even though everything gets backed up. Example attached of jaeger trace shows that context got cancelled 1min into the process, and caused a restart of `doFinalize` func, which then failed as everything was already backed up.
[3c1d891336190128.txt](https://github.com/gitpod-io/gitpod/files/9410256/3c1d891336190128.txt)

### Steps to reproduce

n\a

**Comment by kylos101** [comment]
@sagor999 here are some [recent traces](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/search?end=1665150517397000&limit=1500&lookback=24h&maxDuration&minDuration&operation=finalizeWorkspaceContent&service=ws-manager&start=1665064117397000&tags=%7B%22error%22%3A%22true%22%7D), which may provide more clues. Could you peek at let me know? I'd like to add to groundwork next week, as it'll, still be a while before we have PVC with self-hosted.
