### ISSUE TITLE
[ws-daemon] during store dispose 'no such file or directory` error is not handled properly

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#12323]
### Bug description

See attached trace.
[0be53e101df66704.txt](https://github.com/gitpod-io/gitpod/files/9411089/0be53e101df66704.txt)

https://github.com/gitpod-io/gitpod/blob/512e26fa5ad674f432226cfcb9e4846b0c19ce3c/components/ws-daemon/pkg/internal/session/workspace.go#L205-L213

Trace logged this error:
`cannot remove workspace persistent state location: remove /mnt/workingarea/5838d713-f2ad-45b1-8c69-9d590ab931d2.workspace.json: no such file or directory`
it appears that `os.IsNotExist` might not be catching this error properly.
Reference: https://github.com/golang/go/issues/41122

### Steps to reproduce

n\a

**Comment by jenting** [comment]
This is awesome 🤩 @sagor999 
We could consider updating the go style guide https://github.com/gitpod-io/go-style-guide/blob/master/style.md

**Comment by kylos101** [comment]
@jenting good point! Please consider starting a conversation in #go-tech to socialize this (to get buy-in), and then raise a PR. :+1:
