### ISSUE TITLE
[garbage collection] have a simple way to cleanup ephemeral cluster generated snapshot by loadgen

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12327]
## Is your feature request related to a problem? Please describe

When we launch an ephemeral cluster for test PVC, a temporary snapshot is created.
Currently, the snapshot is garbage collection by the server component, and we did see the very old snapshot still present within the GCP project.
It'd be good to have a way to clean up the snapshot generated by the ephemeral cluster, just like how we clean up the backups on the GCS bucket created by loadgen. 

## Describe the behaviour you'd like

Have a simple way to clean up the snapshot generated by the ephemeral cluster when we run the loadgen.

## Additional context

#7901

**Comment by kylos101** [comment]
@jenting we moved this a week later too, we can wait to do the related delete for test snapshots, and harden this process once we're dog fooding.

**Comment by jenting** [comment]
This issue is blocked by issue #10612 because we need the snapshots to have the labels.
After that, we could remove the ephemeral cluster generated snapshot by label filter.

**Comment by jenting** [comment]
https://www.notion.so/gitpod/Deploy-checklist-for-workspace-clusters-a8a06edfc1474c7b83377f0a84e67c87#e61efc12dd56478a83397bfd54d6f65b
