### ISSUE TITLE
[ws-daemon] excessive logging for `could not get resource information`

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12330]
### Bug description

From GCP log in us63, we see the `could not get resource information` error.

```console
failed to get cpu usage:
    github.com/gitpod-io/gitpod/ws-daemon/pkg/iws.resolveCPUStatV2
        github.com/gitpod-io/gitpod/ws-daemon/pkg/iws/iws.go:1289
  - open /mnt/node-cgroups/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podad41d5dd_930e_446c_879f_7628dce993b6.slice/cri-containerd-12ada141db6a1d737640badc384fe73254d097910312ee32c400882bee1dd837.scope/cpu.stat: no such file or directory
```

### Steps to reproduce

Dunno

### Definition of done

Log as a warning when its not an error. If its truly an error, log is as an error.

**Comment by utam0k** [comment]
same question
https://github.com/gitpod-io/gitpod/issues/12329#issuecomment-1225270134

**Comment by kylos101** [comment]
Reopening and adding to inbox because the frequency is consistent and rather noisy.

[Logs](https://cloudlogging.app.goo.gl/hX8RWedo9e7gGHmB8)

**Comment by kylos101** [comment]
@Furisto @utam0k could I ask you to reevaluate this issue? [Context](https://github.com/gitpod-io/gitpod/issues/12330#issuecomment-1292628120).
