### ISSUE TITLE
ReconcileUsage does not update stale records

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#12347]
When the reconciler runs, it collects Workspace Instance records in the current month. However, it does not remove old records which were not part of the updated set.

Example:
1. A workspace instance is started on July 15 10:00
2. Due to an incident or an outage, the instance does not have a stop time set. This results in the instance having a huge credits used, but also actually can roll over into August.
3. We notice this is the case and correct the stop time on the Workspace Instance, set it to July 15, 14:00
4. When we run the reconciler on August 1, it's no longer considered in the time range for this month, and therefore it's not retrieved (because it stopped before August 1)
5. The old usage record remains, as the reconciler no longer updates this Workspace Instance ID

Possible fixes:
* Also run the Usage Reconciler for the previous month (it would update the records) - without actually updating the invoice for these
* Take a diff of IDs in the current time period (August 1 -> end of August) and delete any which are not in the current batch of instances - effectively a reconcile

**Comment by svenefftinge** [comment]
If we fail to accurately set a stopped time we should not guess a duration, but set the stoppedTime and stoppingTime to the startedTime. The basic rule is: when in doubt the cost is on us. Not sure if this renders this scenario a non issue, though.

**Comment by svenefftinge** [comment]
As a first step, we need to make sure that we can split usage records for workspace instances that span multiple usage periods (currently month).
I'll look into adding a column `period` to create a composite key with `instanceId`. And change the reconcilation to consider all instances that have either no `stoppingTime` or a `stoppingTime` in the current period. As a result, we can have multiple usage records for the same `instanceid` that can span multiple periods.

In a second step, we could evaluate if we can entirely drop the database table and rely on the usage report instead. The reason we are not getting rid of stale entries is that our strategy for storing is insert or update. We never delete anything that was added previously but is no longer contained in a usage record.

**Comment by svenefftinge** [comment]
This si solved/outdated now.
