### ISSUE TITLE
Failed to build custom docker image,  Debian/Ubuntu or Alpine based images.

### ISSUE THREAD

**Issue by ivgd01** [gitpod-io/gitpod#1234]
### Describe the bug
reference to steps according to gitpod.io/doc

### Steps to reproduce
paste the link ""https://gitpod.io/#https://github.com/ivgd01/testgitpod/tree/dev"" in the chrome browser, then press Enter

### Expected behavior
build the simple custom docker image successfully

### Additional Information
no

### Error Message
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: Error response from daemon: No such image: gitpod.io/image-builder/selfbuild:xxxxxxx

**Comment by svenefftinge** [comment]
Thanks for reporting. It is a duplicate of #1236.

**Comment by svenefftinge** [comment]
works again, sorry for this.
