### ISSUE TITLE
Add a loading spinner when changing sorting order on usage page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#12358]
### Problem to solve

Changing timestamp sorting order on usage page makes the dashboard unresponsive and seem like it's broken.

### Steps to reproduce

1. Go to [`/t/gitpod/usage`](https://gitpod.io/t/gitpod/usage)
2. Click on the Timestamp sorting icon to change the sorting order

While navigating through the 100+ pages using client-side pagination is not an issue, changing sorting order makes the product feel broken or unresponsive.

See [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1661348610400419?thread_ts=1661347575.269799&cid=C027AUU7BC3) (internal). Cc @laushinka @jankeromnes @easyCZ 

### Proposal

Until we have proper **server-side pagination** in place, we could show a loading spinner when changing sorting order, as we do when selecting other monthly periods.

**Comment by jldec** [comment]
This column is not sortable since https://github.com/gitpod-io/gitpod/pull/12501
closing.
