### ISSUE TITLE
Improve wrapping of column text in usage view when content is long or viewport is constrained

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#12359]
### Bug description

The most recent updates in the usage page include design updates to the table, etc.

However, seeing this will real-life data, three (3) of the columns could use more reserved space for longer strings to avoid text wrapping.

| Hidden min suffix, wrapping user names, and wrapping workspace class |
|-|
| <img width="850" alt="Screenshot 2022-08-24 at 11 32 56 PM" src="https://user-images.githubusercontent.com/120486/186517870-76fd494a-561a-400b-b2a8-1ca88e640fb6.png"> |

### Steps to reproduce

Reproducible in https://gitpod.io/t/gitpod/usage (internal).

**Comment by jldec** [comment]
General improvements necessary in the component layout behavior (not just spacing).

**Comment by gtsiolis** [comment]
Closing this as the credits column truncation has been fixed and the type column issue is no longer relevant as all available types fit ok in the existing layout.
