### ISSUE TITLE
Cant create workspace

### ISSUE THREAD

**Issue by mauroindigne** [gitpod-io/gitpod#1235]
### Describe the bug

When opening a new Gitpod of this template, im greeted with and error message and can not open my workspace 
### Steps to reproduce

- Open a template
- click Green "gitpod" button
- message pops up with error 
### Expected behavior

I need my work space to be opened.

**Comment by svenefftinge** [comment]
thanks for reporting, it is a duplicate of #1236

**Comment by svenefftinge** [comment]
works again, sorry for this.
