### ISSUE TITLE
Unable to open gitpod workspace from template

### ISSUE THREAD

**Issue by mparkcode** [gitpod-io/gitpod#1236]
### Describe the bug
Unable to open workspace from template  https://github.com/Code-Institute-Org/gitpod-full-template

### Expected behavior
Expected to be able to open workspace from template

### Additional Information
This bug occured previously on Jan 13 https://github.com/gitpod-io/gitpod/issues/1072

Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: Error response from daemon: No such image: gitpod.io/image-builder/selfbuild:d206635ad520e60517fa3ca4c42ca6b2966e0bcce32474021253a2753a0f262f
Please file an issue if you think this is a bug.

**Comment by svenefftinge** [comment]
It seems to happen in asia cluster, only.

**Comment by svenefftinge** [comment]
It works again. Thank you for reporting it including helpful details and sorry for the interruption.

**Comment by mparkcode** [comment]
Great, thanks for the prompt response and fix.
