### ISSUE TITLE
workspace: compare cluster success rate in new dashbaord, and remove by-cluster grouping in existing dashboard

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12364]
### Bug description

The workspace success rate (by cluster) does not show us63.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/49380831/186565885-22238083-476f-49f4-aa2b-73830da7f9e0.png">

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/49380831/186565961-fe8c53be-5dfe-40b5-a742-2dc095363aee.png">

### Steps to reproduce

Check the team workspace success criteria dashboard

### Anything else?

Definition of done: update the success criteria dashboard & [make a new dashboard to compare two clusters](https://grafana.gitpod.io/explore?left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22expr%22:%22%23%20gen71%20regular%20workspaces%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%22,%22instant%22:false,%22interval%22:%22%22,%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22hide%22:true%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22expr%22:%22%20%23%20gen70%20regular%20workspaces%5Cn%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%22,%22instant%22:false,%22interval%22:%22%22,%22refId%22:%22C%22,%22editorMode%22:%22code%22,%22hide%22:true%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22expr%22:%22%20%20%23%20gen71%20vs%20gen70%20regular%20workspaces%20%28%3E%200%20is%20bad%20gen71,%20%3C%200%20is%20bad%20gen70%29%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%5Cn%5Cn%20-%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%22,%22instant%22:false,%22interval%22:%22%22,%22refId%22:%22B%22,%22editorMode%22:%22code%22,%22hide%22:true%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22expr%22:%22%20%20%23%20gen71%20vs%20gen70%20prebuild%20workspaces%20%28%3E%200%20is%20bad%20gen71,%20%3C%200%20is%20bad%20gen70%29%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%5Cn%5Cn%20-%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%22,%22instant%22:false,%22interval%22:%22%22,%22refId%22:%22D%22,%22editorMode%22:%22code%22,%22hide%22:true%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22expr%22:%22%23%20prebuild%20success%20for%20both%20clusters%5Cn1%20-%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D~%5C%22us70%7Cus71%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D~%5C%22us70%7Cus71%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D~%5C%22us70%7Cus71%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D~%5C%22us70%7Cus71%5C%22,%20type%3D%5C%22PREBUILD%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%22,%22instant%22:false,%22interval%22:%22%22,%22refId%22:%22E%22,%22editorMode%22:%22code%22,%22hide%22:true%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22expr%22:%22%23%20regular%20success%20for%20both%20clusters%5Cn1%20-%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D~%5C%22us70%7Cus71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D~%5C%22us70%7Cus71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D~%5C%22us70%7Cus71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D~%5C%22us70%7Cus71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%22,%22instant%22:false,%22interval%22:%22%22,%22refId%22:%22F%22,%22editorMode%22:%22code%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D&orgId=1) & also in workspace success dashboard, break down top level success rate by type too.

**Comment by kylos101** [comment]
I think this happens because in [this](https://github.com/gitpod-io/gitpod/blob/94a9ee7b07cc0eae176890806bd251f1c5218332/operations/observability/mixins/workspace/dashboards/success-criteria.json#L263):
`
1-    (sum by (cluster)(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted",cluster!~"prod-meta-.*|ephemeral.*"}[1h])) OR on() vector(0))
`

We're excluding by `grpc_code`, where values are `OK` or `ResourceExhausted`.

In other words, workspaces are starting, but, not failing to start. At least, that's the story that the metric wants us to believe.

Could I ask you to do a brief test @jenting , where you try to start a workspace that fails, and then assert whether the failure is visible in Grafana? For example, you could try starting a workspace with a base image that is private, but lacks credentials (or some other way).

That will help us confirm that we can see workspace start failures in our metrics (good), or confirm that the metric is broken in some way (not so good).

**Comment by jenting** [comment]
As you mentioned, the problem is this query
```
(sum by (cluster)(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted",cluster!~"prod-meta-.*|ephemeral.*"}[1d])) OR on() vector(0))
```

There is no StartWorkspace gRPC call in not OK _or_ ResourceExhausted.

The weird thing is we assign default value to zero with `OR on() vector(0)`.
However, it seems not to be working correctly...

**Comment by kylos101** [comment]
It is visible now:
![Image](https://user-images.githubusercontent.com/1272076/186685071-009dffd0-fec9-4827-9ea3-026f1a45b017.png)

So, it must have taken a while to encounter a workspace start failure 💪.

The query I used to check is:
`
1-(
    (sum by (cluster)(rate(grpc_server_handled_total{grpc_method="StartWorkspace",grpc_code!~"OK|ResourceExhausted",cluster!~"prod-meta-.*|ephemeral.*"}[1h])) OR on() vector(0))
    /
    sum by (cluster)(rate(grpc_server_handled_total{grpc_method="StartWorkspace",cluster!~"prod-meta-.*|ephemeral.*"}[1h]))
  )
`

**Comment by kylos101** [comment]
We should be able to move `OR on() vector(0)` such that the numerator for failures doesn't cause the whole expression to remove the new cluster, resulting in the success rate % for the new cluster to be 100, instead of not exist at all in the dashboard.

**Comment by jenting** [comment]
[Internal discussion thread](https://gitpod.slack.com/archives/C020VCB0U5A/p1661406662631689)

**Comment by kylos101** [comment]
[Related grafana that may help us compare cluster generations in the future](https://grafana.gitpod.io/explore?left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22expr%22:%22%23%20gen71%20regular%20workspaces%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%22,%22instant%22:false,%22interval%22:%22%22,%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22hide%22:true%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22expr%22:%22%20%23%20gen70%20regular%20workspaces%5Cn%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%22,%22instant%22:false,%22interval%22:%22%22,%22refId%22:%22C%22,%22editorMode%22:%22code%22,%22hide%22:true%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22expr%22:%22%20%20%23%20gen71%20vs%20gen70%20regular%20workspaces%20%28%3E%200%20is%20bad%20gen71,%20%3C%200%20is%20bad%20gen70%29%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us71%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%5Cn%5Cn%20-%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_stops_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%2B%20%5Cn%5Cn%20%20%28%5Cn%20%20%20%20%28%5Cn%20%20%20%20%20%20%28sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Breason%3D%5C%22failed%5C%22,cluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%29%5Cn%20%20%20%20%20%20%2F%5Cn%20%20%20%20%20%20sum%20by%20%28cluster%29%28rate%28gitpod_ws_manager_workspace_starts_total%7Bcluster%3D%5C%22us70%5C%22,%20type%3D%5C%22REGULAR%5C%22%7D%5B1h%5D%29%29%5Cn%20%20%20%20%29%5Cn%20%20%29%20OR%20on%28%29%20vector%280%29%20%22,%22instant%22:false,%22interval%22:%22%22,%22refId%22:%22B%22,%22editorMode%22:%22code%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D&orgId=1)

**Comment by atduarte** [comment]
@jenting @kylos101 should this be moved to Ops?

**Comment by kylos101** [comment]
@atduarte no, our observability (dashboards and alerts) are here: https://github.com/gitpod-io/gitpod/tree/main/operations/observability/mixins/workspace

I will update the definition of done for this issue, there's a change @jenting and I learned about last week that warrants a new dashboard, to compare two cluster generations during a shift.

**Comment by kylos101** [comment]
Opting to close and not fix this, in favor of focusing on using Pyrra and erosion of error budgets at the 1h level, to gauge how a traffic shift is doing.
