### ISSUE TITLE
share workspaces don't expose env

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#12374]
### Bug description

Currently share env will pose environment variables, this is very dangerous default.

### Steps to reproduce

share worksapce expose sensitive info in https://gitpod.io/variables.

**Comment by axonasif** [comment]
Very related: https://github.com/gitpod-io/gitpod/issues/6782

**Comment by gengjiawen** [comment]
@axonasif can you reopen this?

**Comment by gengjiawen** [comment]
Not stale
