### ISSUE TITLE
`Copy GitHub link` is broken in diff editors.

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#1237]
### Steps to reproduce

`Copy GitHub link` is broken in diff editors.

 - Open Gitpod on this PR: https://github.com/eclipse-theia/theia/pull/7159
 - In the `sidepanel.css (4d4f6c293907893670c7aa7c11b55c4811d004a3) ⟷ sidepanel.css` diff editor right-click in line 85 and select `Copy GitHub link`.
 - I have this URL: https://github.com/Anasshahidd21/theia/tree/dc16e5841d5a34766e19cdba597b7c5252cbb351#L85. It does not seem good, and it does not open the file if I paste it in the browser.

Remarks:
 - It works in code editors.

**Comment by jankeromnes** [comment]
Funny enough, https://github.com/gitpod-io/gitpod/issues/322 was filed exactly 1 year ago, on February 19th! 😂 🎂 

In honor of this, I think we should fix it.

**Comment by LinqLover** [comment]
I think I've traced this issue down to
https://github.com/gitpod-io/gitpod/blob/52660b5ad8a1456d0c28de3833216b8971af0c38/components/theia/packages/gitpod-extension/src/browser/github/github-frontend-contribution.ts#L395
So probably `selectionService`/`UriSelection` does not work as expected in diff editors? Unfortunately, I can't tell more without debugging the issue ...

**Comment by LinqLover** [comment]
a bing for the bot 🙄

**Comment by akosyakov** [comment]
@LinqLover Could you please try switching to VS Code: https://www.gitpod.io/docs/feature-preview/#default-ide It is going to be default since April. You can install GitLens extension there for your user and use open in remote instead. How does it work for you?

**Comment by LinqLover** [comment]
Wow, this is great news! Works like a charm now.

**Comment by akosyakov** [comment]
I'm going to close it. Please start switching to VS Code. Right now it is already on par with VS Code on the desktop. After March release it will have all missing features from Theia. For missing features in GitLens extension please file an issue for this extenison.
