### ISSUE TITLE
Slowness loading usage list view

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12388]
Loading the usage list for the Gitpod team take 10s or longer, even when toggling between current and previous months. 

If this only happened once, we might have a chance to mitigate e.g. by prefetching, but it's not usable if it happens on every click.

NOTES: 
- Preserving the ability to change the sort direction on the timestamp column is not required - feel free to drop.
- Showing the total usage for the period is required. 
- A spinner when changing the period (as per #11960) is helpful, but not unfortunately not sufficient.

**Comment by geropl** [comment]
Two possible avenues to improve here:
 - paginate based on the offset + number into backends service (SQL query ala admin dashboard)
 - UI/UX: introduce Toggle to only show/fetch user/project details on request (?)

**Comment by AlexTugarev** [comment]
Going to implement the offset-based pagination on server side.
