### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by RossComputerGuy** [gitpod-io/gitpod#1240]
### Describe the bug
Trying to open a repo using `http://gitpod.io/#https://github.com/user/repo` does not work and causes an internal server error message to pop up.

### Steps to reproduce
1. Open a repo

### Expected behavior
The repo to start opening

### Example Repository
https://github.com/ExpidusOS/builder/tree/redesign

**Comment by jankeromnes** [comment]
Hi @RossComputerGuy, please try again, this should be resolved.

FYI this was caused by a GitHub incident today: https://www.githubstatus.com/ -- this also affected Gitpod, or at least its components that depend on GitHub, like OAuth sign-in and cloning repositories.

**Comment by jankeromnes** [comment]
Closing as GitHub's incident is marked as resolved. Please do comment here if you're still seeing issues though.
