### ISSUE TITLE
self-hosted/docs: reference architectures don't distinguish between requirements and general setup instructions

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#12400]
## Is your feature request related to a problem? Please describe

Recent feedback from a client following the EKS reference architecture indicates that distinctions aren't always made between what steps must be followed precisely (such as the gitpod database must be named `gitpod`) and which steps are general procedures that can be altered to suit one's needs (such as the name of the EKS cluster). This leads end users into traps where they tweak small configurations and produce slightly misconfigured infrastructure that soaks up effort in troubleshooting before the Gitpod installation can complete.

## Describe the behaviour you'd like

The reference architectures should be reviewed in detail and requirements should be called out where noted. Values that can change should be indicated accordingly that users can adjust to meet their needs.

Areas of note include the following:

- Database instance name (should be variable, need to verify)
- Database name (must be `gitpod`)
- Route53 region must be `us-east-1` (https://github.com/gitpod-io/gitpod/issues/12399)
- `gitpod-issuer` ClusterIssuer is not needed when external certificates are being used (such as when ALBs/NLBs are in use)
- https://github.com/gitpod-io/gitpod/issues/12410 eksctl cluster name and `k8s.io/cluster-autoscaler/<CLUSTER-NAME>` must be [synchronized](https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html)

**Comment by lucasvaltl** [comment]
Fwiw, @adrienthebo  I am not 100% sure that the database name must be `gitpod` this might have been a misunderstanding as well. Just don't want us to write this into the docs without validating it.
