### ISSUE TITLE
Add a loading state for the total credits on the usage left sidebar

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#12415]
### Problem to solve

Currently, when users are visiting the new **usage** page, the **total credits** section on the left sidebar has no loading state and shows `0.00 Credits`. This can be confusing to users.

| Loading | Loaded |
|-|-|
| ![credits-loading](https://user-images.githubusercontent.com/120486/186777463-c498e964-2522-4b71-8704-a051d554c5eb.png) | ![credits-loaded](https://user-images.githubusercontent.com/120486/186777467-4c1244cc-57fe-4ada-b088-a7daaae7a3c0.png) |

### Proposal

A good [MVC](https://www.notion.so/gitpod/f7f54cb1c69643e9ac42c9f2ddd9e46f) could be to reuse a loading spinner. 🛹 

Alternatively, using a new skeleton loader component could help, although the skeleton loading pattern should be used scarcely because of the accessibility issues and more. ❗ 

TBD (To be discussed)

**Comment by svenefftinge** [comment]
Closing this for now as we are loading fast enough atm.
