### ISSUE TITLE
Unable to create workspaces based on repositories

### ISSUE THREAD

**Issue by mparkcode** [gitpod-io/gitpod#1243]
### Describe the bug
Unable to create workspaces based on repositories
### Steps to reproduce
Click on gitpod button on a repository

### Expected behavior
A gitpod workspace to be created

### Additional information
error message:
cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/0a371eb9-1600-4629-bd91-c9f0ec04ba66: no space left on device
Please file an issue if you think this is a bug.

**Comment by JesterOrNot** [comment]
This is a known issue with Kubernetes please try refreshing and see if that helps

**Comment by mparkcode** [comment]
Hmm, the problem seems to be persisting

**Comment by 505799690** [comment]
same problem

**Comment by JesterOrNot** [comment]
I'll let my colleagues know

**Comment by boraoren** [comment]
same problem

**Comment by devlights** [comment]
same problem

**Comment by zhangsean** [comment]
same problem

**Comment by kugared94** [comment]
cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/83966c08-1407-4783-9625-d97e12458627: no space left on device
Please file an issue if you think this is a bug.

**Comment by jankeromnes** [comment]
Thank you for reporting this, and sorry for the disruption. We're investigating.

**Comment by jankeromnes** [comment]
Update: We found the root cause of this problem, and are starting to free up space in all nodes. Service should start recovering from here on out.

**Comment by devlights** [comment]
I have confirmed that the problem has been resolved. Thanks :)

**Comment by mparkcode** [comment]
Yup looks like it's working again, great stuff, thanks.

**Comment by JesterOrNot** [comment]
Closing this as resolved then!

**Comment by xys20071111** [comment]
It works.I can countine my things.

**Comment by jankeromnes** [comment]
I confirm the issue is resolved. Thanks a lot for your patience and help.

As next steps, we will improve our disk usage monitoring; alerting; and disk quota enforcement.

In the future, when reporting operations issues and/or downtime, please try to mention which global geographical region you're seeing this problem in (e.g. Asia, Europe, North America -- or ideally the cluster name if you know it, e.g. `ap01`, `eu01` or `us02`). This can help us resolve it faster.
