### ISSUE TITLE
Clean up recorded webhook events

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#12430]
Followup to PR https://github.com/gitpod-io/gitpod/pull/11356

We should auto-delete recorded webhook events after a configured retain period.

**Comment by gtsiolis** [comment]
@AlexTugarev This is probably why prebuild events take 3 minutes to load for some high-activity projects, right? See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1661463300942529?thread_ts=1661462846.914919&cid=C02EN94AEPL) (internal).

**Comment by AlexTugarev** [comment]
@gtsiolis, I ran the query for the mentioned project and it returned in a ~100ms, but in 1 out of 10 tries it was 3s. 🤷🏻‍♂️

**Comment by gtsiolis** [comment]
Oh, the page for the aforementioned project seems to load in 1-3 seconds. 🤷
