### ISSUE TITLE
[installer] investigate how to improve build in prev envs

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#12437]
Right now it always takes around 100s for each build without any changes to installer itself. See internal [[1](https://gitpod.slack.com/archives/C032A46PWR0/p1661506688834589?thread_ts=1661502110.424609&cid=C032A46PWR0)]

**Comment by mrsimonemms** [comment]
@akosyakov is this still problematic? I know that some work has been done on this (I believe by @mads-hartmann and others).

**Comment by akosyakov** [comment]
I think we can close it for now. I think it was better recently because of different hot deploy scripts.
