### ISSUE TITLE
VS Code: Import Java projects as part of the prebuild

### ISSUE THREAD

**Issue by OLibutzki** [gitpod-io/gitpod#12448]
## Is your feature request related to a problem? Please describe
Currently Java projects are imported whenever I open a Gitpod workspace. That takes some time and leads to a delay until I can start coding. This issue can be reprduced using the spring-petclinic example.

Here is a little video demonstrating the current behaviour:

https://user-images.githubusercontent.com/977893/186992847-f0cfd8b4-16f8-4d02-89e1-08802e45cae2.mp4

After about 30 seconds the IDE is ready including the extensions...
It takes another 14 seconds until the Java project is imported. Please keep in mind that the petclinic is a small project. Bigger projects (like Maven Multi-Module projects) take more time to be imported into VS Code.

## Describe the behaviour you'd like
It would be great if the Java project import could be moved into the prebuild phase.

## Describe alternatives you've considered
Using the JetBrains stack might be an alternative, but I have not tried it yet.

## Additional context
//cc @svenefftinge the result of our conversation today

**Comment by OLibutzki** [comment]
I assume that it's an issue how vscode-java works...

Every _Reload window_ leads to a reimport of the Java projects.

**Comment by axonasif** [comment]
Hey @OLibutzki, thanks for rising this. Does https://github.com/gitpod-io/gitpod/issues/10185 seem related to you?

**Comment by OLibutzki** [comment]
From a user's point of view it seems to be related, but I doubt that it's related from a technical point of view as IntelliJ and the RedHat VS Code implementations are completely different.

**Comment by akosyakov** [comment]
Thank you for the issue. It is an interesting idea. @fbricon I wonder is there some way to prerun java LS on CI that it opens the project quicker on the startup in VS Code?

**Comment by akosyakov** [comment]
I opened the issue in VS Code Java: https://github.com/redhat-developer/vscode-java/issues/2724
