### ISSUE TITLE
Epic: Improve control over shared running workspace URLs

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12444]
Shared running workspace can be accessed by anyone with access to the workspace URL.  There is no indication to the workspace owner when other users open the shared workspace in their own browser.

<img width="1087" alt="Screenshot 2022-08-26 at 16 16 26" src="https://user-images.githubusercontent.com/849592/186938290-6cba5d88-2f1b-4910-bb40-3f9390309cf6.png">

Suggested improvements:

1. Single-use shared workspace URLs 
2. User-scoped shared workspace URLs
3. Indication (to the workspace owner) when others are accessing their shared workspace.
4. Confirmation prompt to allow/deny shared workspace access.
5. Audit trail of shared workspace access.

**Comment by atduarte** [comment]
Related with https://github.com/gitpod-io/gitpod/issues/13188

**Comment by gtsiolis** [comment]
Some thoughts:
1. I don't think investing time for generating single-use or user-scoped shared workspace URLs is worth the effort.
2. The fixed share button that also includes the state sounds perfect for surfacing this kind of information, see [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1658518674537959) (internal).
3. Maybe we could bundle all these Gitpod-specific information in a dedicated Gitpod view in the remote explorer, see [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1658551330343829?thread_ts=1658518674.537959&cid=C01KPEPQYE6) (internal).
4. In the meantime, we could use this fixed space for the share action and state to also surface user avatars that access the shared workspace as described in https://github.com/gitpod-io/gitpod/issues/4112, and we could also use this pattern also in the dashboard, see screenshot below.

| User avatars accessing a shared workspace (Early Design)|
|-|
| ![image](https://user-images.githubusercontent.com/120486/116555597-41467800-a905-11eb-8550-45986fe5347e.png) |
