### ISSUE TITLE
[supervisor] Initialization hangs for 20min

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#12455]
We found workspace starts of gitpod-io/website starting to be super slow when started in US. Here's an [internal thread](https://gitpod.slack.com/archives/C03TW75AN4U/p1661669570521249).
They stay in the loading prebuild phase for 20 min.

**Comment by akosyakov** [comment]
Supervisor will always hangs till content is initialised is expected. IDEs cannot be started without content.
Why content init takes so long? It is part of ws-daemon not supervisor.

**Comment by svenefftinge** [comment]
It resolved itself after 1h.

**Comment by mikenikles** [comment]
This has been an issue for a while: https://github.com/gitpod-io/gitpod/issues/12345
