### ISSUE TITLE
[local-preview] build fail

### ISSUE THREAD

**Issue by tomatebeans** [gitpod-io/gitpod#12451]
### Bug description

Followed instructions https://www.gitpod.io/docs/self-hosted/latest/local-preview

Even when clicking `Use Default Image` button, build still fails.
Happens even when choosing sample/template repo https://github.com/gitpod-io/spring-petclinic.

![image](https://user-images.githubusercontent.com/108106367/187013342-312a835e-0b79-4aa4-9360-5c181f42c182.png)

### Steps to reproduce

1. Install local preview
2. Integrate with github ( integrated my with my https://github.com/tomatebeans )
3. Tried to create workspace any of the following
     https://preview.gitpod-self-hosted.com/start/#gitpodio-springpetclini-c6lwysngjz5
     https://preview.gitpod-self-hosted.com/#https://github.com/tomatebeans/fulls
     https://preview.gitpod-self-hosted.com/#https://github.com/tomatebeans/blank.git
     https://preview.gitpod-self-hosted.com/#https://github.com/gitpod-io/template-sveltejs
4. Click `Continue  with Default Image`

![chrome_q9rTp8tpNO](https://user-images.githubusercontent.com/108106367/187013539-d1da693b-3064-4188-bc49-ebdfd9e62224.gif)

### Expected behavior

clicking `Continue with default Image` should have no error

**Comment by lucasvaltl** [comment]
Hey @tomatebeans thanks for raising this. I'm sorry that this did not work immediately - let's see how we can fix this :) @Pothulapati, would you be so kind at take a look at this? I assume the first step here will be to gather some logs.

**Comment by Pothulapati** [comment]
Hey @tomatebeans, Thanks for the detailed descriptions `dalong with the video).

Because you seem to have went till the Gitpod UI, I don't think looking at the `k3s` logs would be useful. The `image-builder-mk3` are the logs that that I think would be useful. Can you share the logs of the same?

Thanks

**Comment by tomatebeans** [comment]
Hi, tried it again today with the same result.

Sorry I currently know where the `image-builder-mk3` logs are.

Currently the logs I saw are just from one container (viweing at docker desktop and at portainer).

![image](https://user-images.githubusercontent.com/108106367/188249551-f99bbf4c-5328-4aad-9afa-c2a2be4a88f4.png)

[_gitpod_logs.txt](https://github.com/gitpod-io/gitpod/files/9481588/_gitpod_logs.txt)

**Comment by Pothulapati** [comment]
@tomatebeans 

You should be able to get the `image-builder-mk3` logs by running `docker exec gitpod kubectl logs deployment/image-builder-mk3`. Can you please share those logs?

Thanks :)

**Comment by tomatebeans** [comment]
executed:   `docker exec gitpod kubectl logs deployment/image-builder-mk3 image-builder-mk3` 
output logfile: [dockerlogimagebuildermk3.txt](https://github.com/gitpod-io/gitpod/files/9583821/dockerlogimagebuildermk3.txt)

**Comment by tomatebeans** [comment]
updated image: `docker pull eu.gcr.io/gitpod-core-dev/build/local-preview:latest`
message seems different:
![image](https://user-images.githubusercontent.com/108106367/191523295-4899c682-210d-4af7-93c8-c08bb9890cea.png)

then: `docker exec gitpod kubectl logs deployment/image-builder-mk3 image-builder-mk3 > outputlog2.txt`
[outputlog2.txt](https://github.com/gitpod-io/gitpod/files/9617245/outputlog2.txt)

**Comment by Pothulapati** [comment]
Hey @tomatebeans,

Thanks for the reply!

Hmm, Looking at the `image-builder-mk3` logs, I see a bunch of registry not allowed logs on `docker.io`. I just built a local-preview image that includes `docker.io` registry in the allow list. Can you run the the same command but with the following image?
```
eu.gcr.io/gitpod-core-dev/build/local-preview:tar-lp-reg-docker.8
```

Also, If even that does not work. Can you post the `image-build` logs itself by running `docker exec gitpod kubectl logs -f -l workspaceType=regular` when you click the button (as the container could disappear pretty fast)?

Thanks!

**Comment by tomatebeans** [comment]
Thanks, currently in progress:

It seems taking more than the usual 5mins ( though system resources are almost not used ):
![image](https://user-images.githubusercontent.com/108106367/192598291-0ed5d45a-5dec-4f5c-a354-08fb922fe9c9.png)

will try again in another day

**Comment by tomatebeans** [comment]
Seems for me, the new image is not able to start the webserver:

![image](https://user-images.githubusercontent.com/108106367/193465375-3aa62719-2ba7-441f-af8d-bbb6edf0548f.png)

**Comment by Pothulapati** [comment]
👋 

This issue seems to be about k3s itself not starting as we can't seem to connect to the kubernetes cluster. Did something change? i.e Moving to WSL2 or something?

The new image doesn't really change anything except for adding new gitpod configuration 🤔 which should prevent Gitpod from starting if soemthing is wrong but shouldn't effect k3s in any way.

**Comment by tomatebeans** [comment]
I think I don't remember something significant.
I tested using the usual image ( from the local preview instructions ) but I only remember it working despite the new image not working.

Today I pulled the usual image with no changes, ... maybe I have broken something:

![image](https://user-images.githubusercontent.com/108106367/193735495-f1bb7469-94b4-48b9-b36c-916f2bc49aa4.png)

I'll check again.

**Comment by tomatebeans** [comment]
my recent changes is 22h2 windows 11 update, but I'm getting the same behavior, the `:tar-lp-reg-docker.8` is really not working while the default `:latest` is working.


- A
Tried it again, and the default `:latest` image has activity, and finished less than 6mins ( although it leads to the same issue) :
[cpu usage is about 35%, significant disk and wifi activity]
![image](https://user-images.githubusercontent.com/108106367/194362715-6152a3ef-fa12-4bf8-9cda-7210dff8ed14.png)

Result: Accessed https://preview.gitpod-self-hosted.com but same error 1image build did not produce workspace image`

- B
In contrast, the `:tar-lp-reg-docker.8` image does not show any activity at start and is not finished even after 8mins:
[cpu usage is at most 20% and averages 12%,, almost 0 disk and just background wifi activity:]
![image](https://user-images.githubusercontent.com/108106367/194363829-4f48bdd8-8bbb-4e74-b6b7-38cc5179fc06.png)
After 8mins, still not done:
![image](https://user-images.githubusercontent.com/108106367/194365665-b11f0198-99ad-4d65-b0ec-bd1d71b4ebac.png)
After 20mins, still not done either

Result: was not able to access https://preview.gitpod-self-hosted.com at all

---------------------------

> Hmm, Looking at the image-builder-mk3 logs, I see a bunch of registry not allowed logs on docker.io

My internet seems ok but somehow maybe my region ( Philippines ) connection to docker registry is throttled, resulting in pull error.
I had an experience where a Windows2012 VM inside azure outside my region can pull a mssql server docker image very fast, but when I do it on my laptop on my region ( PH )  it was never successful.

Maybe since this issue only happens to me, I can close it?
