### ISSUE TITLE
Workspace Cluttered with core.* files

### ISSUE THREAD

**Issue by a0v0** [gitpod-io/gitpod#12453]
### Bug description

![image](https://user-images.githubusercontent.com/62926341/187032364-cb0cdb83-5308-42e1-853d-0c945b2d06f7.png)

### Steps to reproduce

Install anything and you will see these files

Run:
`brew install go-task/tap/go-task`

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3q51m)

**Comment by pawlean** [comment]
Hey @a0v0! I've just tried to replicate this but was unable to. Are you still seeing it?

**Comment by axonasif** [comment]
Related https://github.com/gitpod-io/gitpod/issues/11760

**Comment by axonasif** [comment]
I am able to reproduce it by running `brew install tmux`, note that my `pwd` was `$GITPOD_REPO_ROOT`.

**Comment by axonasif** [comment]
Rolling back to old brew doesn't seem to help:
```bash
cd $GITPOD_REPO_ROOT

git -C "/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core" checkout 4e1a5bafc78c38ab37fb2a6ef05f3235428f64b3

git -C "/home/linuxbrew/.linuxbrew/Homebrew" checkout 3.4.0

rm -f core.*; brew uninstall tmux; brew install tmux; ls -la
```

**Comment by sharebear** [comment]
I'm experiencing this too... I didn't see the issue when doing `brew install <thing>` interactively in the terminal, but it's definitely when calling `brew install <thing>` during `init` on a task similar to @a0v0's example.

**Comment by kylos101** [comment]
:wave: hi, we might be able to resolve this issue by making a change to our `workspacekit` component, by setting soft limits for the workspace, using the [prlimit syscall](https://linux.die.net/man/2/prlimit). For example, set `RLIMIT_CORE` to 0. [Reference](https://linux.die.net/man/2/prlimit#:~:text=to%20this%20size.-,RLIMIT_CPU,-CPU%20time%20limit). 

I've added this issue to our team's backlog, so we can further discuss later this week. We'll share more updates soon! :pray:

**Comment by Furisto** [comment]
I can disable the core dumps for the workspace with setrlimit, but I think we would want to preserve the option to create core dumps if the user wants it. However once the value is set by workspacekit, I get "Operation not permitted" when using ulimit from within the workspace. Allowing prlimit64 and setlimit in the seccomp profile does not have any effect.

**Comment by kylos101** [comment]
Okay, thanks for the heads up, @Furisto . Perhaps this is something to socialize next week with @utam0k as part of Breakdown. I'll check with @aledbf and @sagor999 today too, to see if they have ideas.

**Comment by aledbf** [comment]
Disabling core files hides the issue, some process is restarting and generating those files. I understand this is an issue with disk space but maybe we need to just disable it (as first step) but we also need to report something to the user. The later can be after removing the noise of the core files.

**Comment by aledbf** [comment]
> Processes that belong to the root user cannot be changed.

I think that's fine for the first step. This issue is mostly related to brew and npm that run as gitpod.

**Comment by kylos101** [comment]
> Changing the limit from within the workspace works as long as the target process belongs to the gitpod user.

@Furisto can you share how the change might be done? I assume in `workspacekit` but am not sure how. For example, would you use another syscall, other than `setrlimit`? I ask so that we can schedule this related work. :bow:

**Comment by kylos101** [comment]
@Furisto a related issue: https://github.com/gitpod-io/gitpod/issues/13102 (not sure if you want to link in your draft PR)

**Comment by jankeromnes** [comment]
FYI, I've just restored a workspace backup for an affected user.

The workspace backup was 168.1 GiB (so unrestartable), and this is what I found inside:

```
core.17646       160GiB
core.33825       1,4GiB
core.13717       1,4GiB
core.19192       1,1GiB
core.29828       975MiB
core.33072       974MiB
core.26923       972MiB
core.31959       951MiB
core.13144       879MiB
```

So, just a heads up that these `core` files can be as large as `160GiB`(!)

**Comment by Furisto** [comment]
@utam0k I will be OOO for the next three days. If you have the bandwidth can you take a look at this? The preferred option would be to not have these dump files created at all (the [rlimit option](https://github.com/gitpod-io/gitpod/pull/12814)). Another option would be to [exclude these files from backup](https://github.com/gitpod-io/gitpod/tree/fo/exclude-core). 

Disabling core dumps currently means that the user is not able to reenable them if required which is obviously not great. See this [comment](https://github.com/gitpod-io/gitpod/pull/12814#issuecomment-1251174355) for details. If we could somehow make this work it would be the preferred solution. 

If we instead exclude core dumps from the backup we should check what the performance impact of running a regular expression on every file in /workspace for a big repository is (e.g. by using https://github.com/torvalds/linux/).

**Comment by aledbf** [comment]
@Furisto I will take this issue, use your draft PR, disable by default core dumps and enable the feature, and set the soft and hard limits using the .gitpod.yml

**Comment by aledbf** [comment]
@a0v0 this issue is fixed but still waiting for deployment (during the next 24hs)
