### ISSUE TITLE
Cannot open an exist workspace.

### ISSUE THREAD

**Issue by xys20071111** [gitpod-io/gitpod#1245]
### Describe the bug

When I tried to open an exist workspace,it falied to start.
### Steps to reproduce

1:Log in
2:Open an exist workspace.
3:It will happen
### Expected behavior

It should work as usual as yesterday.
### Additional information

cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/ef3d52cd-0089-4a6b-a338-4ec4db9945fb: no space left on device
Please file an issue if you think this is a bug.
### Example repository

b5c8d586-08ec-4887-8a80-37dcd47176b8

**Comment by JesterOrNot** [comment]
Hello @xys20071111 and welcome to the Gitpod community :100: 
We are aware of this see #1243

Thanks for contributing 😃
