### ISSUE TITLE
[PVC] Open workspace from prebuild PVC, no message This task ran as a workspace prebuild on CLI

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12464]
### Bug description

[PVC] Open workspace from prebuild PVC, no message `This task ran as a workspace prebuild` on CLI

### Steps to reproduce

- Prebuild + PVC
- The user account with PVC
- The user open the workspace from prebuild

### Expected behavior

We should see the message `This task ran as a workspace prebuild` in workspace CLI when we open from prebuild. After that, we could know whether the workspace open from prebuild or not.

### Anything else?

#7901

**Comment by kylos101** [comment]
@jenting can you share more detail about what the expected result is? I assume you mean to say that the text we normally get from a prebuild is no longer being displayed upon regular workspace start?

cc: @sagor999 this seems like a change in behavior, wdyt?

**Comment by jenting** [comment]
We should be able to see the message `This task ran as a workspace prebuild` on workspace CLI.
Otherwise, the user can't know whether the workspace is start from prebuilds or git clone.

**Comment by sagor999** [comment]
Ah, this is a valid concern. Needs to be looked into.
I will Schedule this then.

**Comment by kylos101** [comment]
@jenting as getting PVC working with regular prebuilds is a higher priority, for now, I will move this back to scheduled. 🙏

**Comment by jenting** [comment]
From my observation, after workspace ready, the content is
- Without PVC: from-prebuild
- With PVC: from-other
