### ISSUE TITLE
git clone issue on on-prem installation with github enterprise SSL certificate 

### ISSUE THREAD

**Issue by roshvin** [gitpod-io/gitpod#12479]
### Bug description

we have installed gitpod on-prem version. and integrating with GHE on-prem version.
our GHE server running with corporates SSL  certificate . during workspace creating we are seeing below error. 

`: git initializer gitClone: git clone --depth=1 --no-single-branch https://hostname.domainname.com/RO-DevSecOps/sample-node-app.git . failed (exit status 128): Cloning into '.'...\nfatal: unable to access 'https://sgscaiu0798.inedc.corpintra.net/RO-DevSecOps/sample-node-app.git/': server certificate verification failed. CAfile: /etc/ssl/certs/custom-ca.crt CRLfile: none\n","volume_snapshot":{}},"runtime":{"node_name":"insta-develop","pod_name":"imagebuild-702432a8-2be9-4559-93e9-dbdc603e7873","node_ip":"53.126.11.11`

could you help on bypassing SSL certificate in imagebuild/workspace .

### Steps to reproduce

we have installed gitpod on-prem version. and integrating with GHE on-prem version.
our GHE server running with corporates SSL  certificate . during workspace creating we are seeing below error. 

`: git initializer gitClone: git clone --depth=1 --no-single-branch https://hostname.domainname.com/RO-DevSecOps/sample-node-app.git . failed (exit status 128): Cloning into '.'...\nfatal: unable to access 'https://sgscaiu0798.inedc.corpintra.net/RO-DevSecOps/sample-node-app.git/': server certificate verification failed. CAfile: /etc/ssl/certs/custom-ca.crt CRLfile: none\n","volume_snapshot":{}},"runtime":{"node_name":"insta-develop","pod_name":"imagebuild-702432a8-2be9-4559-93e9-dbdc603e7873","node_ip":"53.126.11.11`

could you help on bypassing SSL certificate in imagebuild/workspace .

**Comment by corneliusludmann** [comment]
Hi @roshvin! Thanks for reaching out. To help you, I need more information like your actual configuration. Could you write an e-mail to troubleshooting@gitpod.io and append your [support bundle](https://www.gitpod.io/docs/self-hosted/latest/support-bundle)?

I'm closing this here for now. Please let me know when you cannot reach out via e-mail for some reason.
