### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by Tshoes** [gitpod-io/gitpod#1248]
### Describe the bug
 cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/e618eeb6-8d2b-426a-bdeb-bdb5eee2ea1c: no space left on device
Please file an issue if you think this is a bug.

**Comment by boraoren** [comment]
you can follow https://github.com/gitpod-io/gitpod/issues/1243 @JesterOrNot

**Comment by JesterOrNot** [comment]
Thanks, @boraoren
