### ISSUE TITLE
Usage Reconciler fails with "message too large"

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#12487]
Usage Reconciler is failing at the end of the month with 
```
"failed to reconcile usage: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (117180415 vs. 104857600)"
```

To fix this, we need to pass the data another way.

Solution:
* We already return the ReportID in the response, we can use that to download the report in the Billing Controller to avoid this problem.

**Comment by svenefftinge** [comment]
I think this is now fixed but we have [another error](https://github.com/gitpod-io/gitpod/issues/12506) now.

**Comment by easyCZ** [comment]
Resolved.
