### ISSUE TITLE
In-browser terminal as IDE option

### ISSUE THREAD

**Issue by jwpjrdev** [gitpod-io/gitpod#12484]
## Is your feature request related to a problem? Please describe
Lately, I've been enjoying using vim for my projects. However, it's quite a hinderance to open it in the browser VS Code window, maximise the terminal, and then still have wasted space on the screen from VS Code that I won't be using.

## Describe the behaviour you'd like
It would be nice to have an in-browser terminal (likely would be implemented with xterm.js) as an IDE option that opens the terminal rather than VS Code. I've tried out [`ttyd`](https://github.com/tsl0922/ttyd) and have seen [tmate](https://tmate.io). I haven't extensively used either but they seem like a good starting point.

## Describe alternatives you've considered
An option or keybind to hide all of VS Code's content except for the terminal would be nice but likely a pain to use—what if you forget the keybind? What if you reload the window? What if it times out?

## Additional context
I use Gitpod on my iPad and therefore don't have the luxury of unused space on my screen. Everything has to be there for a reason. It's already cluttered as is.

**Comment by mustard-mh** [comment]
Hey @filiptronicek, you must be good to see this issue (PR https://github.com/gitpod-io/gitpod/pull/8464)

**Comment by andreafalzetti** [comment]
@jwpjrdev An approach that you could also consider is using SSH + vim. Once you start your workspace with VS Code Browser, if you at the same time connect using SSH with your local terminal, you can have a quite good experience with vim! :)

**Comment by jwpjrdev** [comment]
@andreafalzetti I saw that—is there any roadblock for releasing it in beta other than the xterm.js icon?

**Comment by jimmybrancaccio** [comment]
@jwpjrdev A few folks including myself have been using Blink on our iPads.

**Comment by loujaybee** [comment]
Today is the day, enjoy @jwpjrdev !

https://www.gitpod.io/changelog/code-in-the-terminal-without-leaving-your-browser!

Drop any feedback here: https://github.com/gitpod-io/gitpod/issues/17724

**Comment by jwpjrdev** [comment]
OH MY WORD YOU GUYS ARE THE BEST
