### ISSUE TITLE
cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/83966c08-1407-4783-9625-d97e12458627: no space left on device Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by kugared94** [gitpod-io/gitpod#1249]

**Comment by JesterOrNot** [comment]
Hello, @kugared94 and welcome to the Gitpod community this! Thank you for contributing! :100:

This issue is currently being tracked in #1243 

Please take any concerns you have there if you would like 😄
