### ISSUE TITLE
[integration tests] add regular workspace PVC integration test from PVC test plans

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12497]
## Is your feature request related to a problem? Please describe

Manually go thru. the PVC test plans take about half a day, and it's too long for each release to manually test against all the PVC test plans.

## Describe the behaviour you'd like

Trying to add more integration tests from the PVC test plans if possible, and make the manual PVC tests as small as possible.
Therefore, we could minimize the deployer only need to test the manually PVC test plans. 

## Describe alternatives you've considered

None

## Definition of Done (DoD)
- Update existing tests with PVC feature flag
  - [x] TestBackup #12620
  - [x] TestRegularWorkspaceTasks #12620
  - [ ] TestGitHubContexts #12650
  - [ ] TestGitActions #12650
  - [ ] TestGitLFSSupport #12650
- Add new tests
  - [x] PVC test plans regular workspace case 2 Existing workspace and enable PVC (Disable PVC ❌ → Enable PVC ✅) #12620
  - [x] PVC test plans regular workspace case 3 Fresh new workspace and enable PVC, then disable PVC (Enable PVC ✅ → Disable PVC ❌ ) #12620

## Additional context

#7901 

@jenting I briefly looked at the below tests, and removed them from scope for now. Can you review, and let me know your thoughts? They seem unnecessary, but, let me know what you think? :pray: 
- Other regular workspace tests, not necessarily needed for PVC
    - [x] TestWorkspaceInstrumentation (creates a user via server API, starts a workspace from gitpod repo, transfers or uses an agent to the workspace pod, sets up a port forward, and asserts it can connect to the agent via RPC...it is unclear how this relates to PVC)?
    - [x] TestLaunchWorkspaceDirectly (this is exercised in most of the tests starting a workspace already)

**Comment by kylos101** [comment]
@jenting I updated Additional Context for this issue to reduce the # of required tests for regular workspaces, please review?

**Comment by kylos101** [comment]
:wave:  @jenting regarding cases 2 and 3 (which warrant new tests), if I were to run those cases, would you expect them to pass? I ask because [this discussion](https://gitpod.slack.com/archives/C02F19UUW6S/p1662133142820379?thread_ts=1661998100.115679&cid=C02F19UUW6S) is unresolved.

**Comment by jenting** [comment]
> 👋 @jenting regarding cases 2 and 3 (which warrant new tests), if I were to run those cases, would you expect them to pass? I ask because [this discussion](https://gitpod.slack.com/archives/C02F19UUW6S/p1662133142820379?thread_ts=1661998100.115679&cid=C02F19UUW6S) is unresolved.

Yes, I expect them to pass

**Comment by jenting** [comment]
> @jenting I updated Additional Context for this issue to reduce the # of required tests for regular workspaces, please review? 🙏

Thanks for the detailed check, I agree those two tests do not require testing against the PVC feature flag.

**Comment by kylos101** [comment]
@jenting could you move the `Prebuild tests for PVC` tasks to a separate issue? That way, this issue doesn't stay "in progress" for "too long" in our groundwork. :bow:
