### ISSUE TITLE
Failed usage reconciliations did not alert

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#12491]
On Monday 29.8, we noticed the Usage Reconciler Failed with `"failed to reconcile usage: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (117180415 vs. 104857600)"`.

This did not produce an Alert, but it should.

Ensure an alert fires in this exact scenario, routed to WebApp.

![Image](https://user-images.githubusercontent.com/1419286/187286601-6d08fe97-886f-492b-947b-23899a36a751.png)

[Logs](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22usage%22%2529;timeRange=PT1H;cursorTimestamp=2022-08-29T19:10:07Z?authuser=0&project=gitpod-191109)

[Metrics](https://grafana.gitpod.io/d/8W7P-jg4z/component-usage?orgId=1&from=now-7d&to=now)

**Comment by easyCZ** [comment]
Related issue for a fix: https://github.com/gitpod-io/gitpod/issues/12487

**Comment by geropl** [comment]
@easyCZ Is this still relevant?

**Comment by easyCZ** [comment]
Resolved as part of https://github.com/gitpod-io/gitpod/issues/13034
