### ISSUE TITLE
[PVC] Can't open from prebuilds if prebuilds with large workspace class but user prefers standard workspace class

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12494]
### Bug description

Prebuilds was built with a large workspace class (50Gi), and the user prefers a standard workspace class (30Gi).
The user cannot open the workspace because the PVC disk size is 30Gi, not 50Gi.

### Steps to reproduce

- Force the prebuilds to build with a large workspace class (50Gi)
- After prebuilds are finished, the VolumeSnapshot size is 50Gi
- Change the user workspace class preference is standard workspace class (30Gi)
- Open the workspace from prebuilds, the workspace can't start because the disk size dos not be increased

### Expected behavior

@atduarte @Furisto @jenting my understanding is, that in this scenario, we want to auto upgrade the workspace class to large, so that the regular workspace being started from a large prebuild is also large. Otherwise, it will not be able to start, because the restore will fail as @jenting described.

### Anything else?

https://github.com/gitpod-io/gitpod/issues/7901

**Comment by jenting** [comment]
Related to #11912

**Comment by jenting** [comment]
> my understanding is, that in this scenario, we want to auto upgrade the workspace class to large, so that the regular workspace being started from a large prebuild is also large.

@kylos101 correct

**Comment by atduarte** [comment]
> my understanding is, that in this scenario, we want to auto upgrade the workspace class to large, so that the regular workspace being started from a large prebuild is also large.

That's correct, given the current technical impossibility of doing it differently.

**Comment by sagor999** [comment]
@jenting would not this be fixed by #11912 ?

**Comment by jenting** [comment]
> @jenting would not this be fixed by #11912 ? 

From my testing, nope.

**Comment by jenting** [comment]
I verified this issue with PR #12734, and it works well.
