### ISSUE TITLE
[cli] Allow run commands in new terminals

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#125]
The cli should allow running commands in new terminals.
E.g.
```
   gp run yarn
```
or just
```
   run yarn
```

Should run yarn in a new terminal.
Additional supported options : 
```
 -cwd <path>
 -open-in <panel> (can be 'main', 'left', 'right', 'bottom' (default))
 -open-mode <mode> (can be 'split-top' | 'split-left' | 'split-right' | 'split-bottom' | 'tab-before' | 'tab-after' (default))
 -title <title> (the title shown in the tab)
```

The cli command can be used in tasks, for instance I could have a task like this
```
command: >
   yarn && \
   gp run -open-mode split-right 'yarn watch'\
```

**Comment by 32leaves** [comment]
That would be a really handy feature. Personally, I'd favour `gp run` as `run` by itself might interfere with pre-existing commands.

Alternatively, this could be `gp start` akin to `start` in the windows command prompt (not something we want to model after too much, but this is a common one).

**Comment by svenefftinge** [comment]
supported already. See https://docs.gitpod.io/44_Config_Start_Tasks.html#configuring-the-terminal
