### ISSUE TITLE
Open url in new browser tab

### ISSUE THREAD

**Issue by karpa** [gitpod-io/gitpod#12504]
## Is your feature request related to a problem? Please describe
If i run "gp preview $(gp url 8080)" it opens inside VS code a browser preview.

## Describe the behaviour you'd like
How can i make it open the URL on a different browser tab (or window)?

## Describe alternatives you've considered
None..

**Comment by axonasif** [comment]
Hi @karpa, you can use `gp preview $(gp url 8080) --external` to open in a separate browser tab.

Tip: You can always try `gp <subcommand> --help` or in this case `gp preview --help` to learn more about the available flags :wink:

**Comment by karpa** [comment]
Thanks for the quick response.

The commnd is working if i run it directly to the command line. But if i add the command inside a bash script (e.g hook_commnd.sh) it does not open the tab. Should i add some extra option?

Thanks

**Comment by axonasif** [comment]
> Thanks for the quick response.
> 
> The commnd is working if i run it directly to the command line. But if i add the command inside a bash script (e.g hook_commnd.sh) it does not open the tab. Should i add some extra option?
> 
> Thanks

In that case you could try `( gp ports await 23000 1>/dev/null && gp preview $(gp url 8080) --external ) &` in your bash script.

**Comment by karpa** [comment]
Now it does work running from script, but i must have the tab in focus to open the new tab.
i.e if i run it and go to another tab (reading email or SO) it does not open the tab. As soon as i go to the gitpod tab, it opens.

**Comment by axonasif** [comment]
Thats a safety feature I think.

**Comment by karpa** [comment]
The safety feature is from browser or VS Code? 

Running the bellow code it does open the new tab/window even if it's not in focus.

`setTimeout(openNewTabWithDelay, 3000);
function openNewTabWithDelay() {
  window.open("https://www.w3schools.com");
}`

**Comment by axonasif** [comment]
Probably VSCode, @jeanp413 might know better.
