### ISSUE TITLE
[Self-hosted installation] unable to see imagebuild logs 

### ISSUE THREAD

**Issue by meenajaeiei** [gitpod-io/gitpod#12513]
### Bug description

Gitpods UI doesn't show image build Logs
![Uploading Screen Shot 2565-08-30 at 19.20.47.png…]()

### Steps to reproduce

I checked every pods during the **imagebuild-** pods was working, I checked inside the imagebuild- pods by `kubectl exec -it <imagebuild-pod-name> && tail -f /workspace/.gitpod/prebuildlog ` and found the Log build was really exist
<img width="828" alt="Screen Shot 2565-08-30 at 19 23 04" src="https://user-images.githubusercontent.com/20944597/187445191-1616435a-8aa8-4783-a1ea-635060c82a74.png">

and log output from **imagebuild-** pod stdout doesn't provide anything that relate to cause of the issue
<img width="1668" alt="Screen Shot 2565-08-30 at 19 29 10" src="https://user-images.githubusercontent.com/20944597/187445838-c4e1b0c3-a0cd-4220-a5eb-fc31a349897a.png">

 I found an abnormal log that came from **server-** pods. it said` Request watchWorkspaceImageBuildLogs unsuccessful: 640/\"cannot watch imagebuild logs for workspaceId\"","payload":{"method":"watchWorkspaceImageBuildLogs"`
![Uploading Screen Shot 2565-08-29 at 22.01.57.png…]()

### Workspace affected

any building workspace

### Expected behavior

the Build Log is supposed to show in Gitpod UI

### Example repository

affect on any repos

### Anything else?

- I installed GItpod by using manifest file that generated from KOTS
- I raised the issue in Discord for more information https://discord.com/channels/816244985187008514/1013826856140689508

**Comment by geropl** [comment]
Hey @meenajaeiei , thank you for reporting.

I think the info about KOTS is the relevant part here.

@MrSimonEmms Could you help us setting up a self-hosted installation to debug this? Or maybe you have one handy? 🤔

**Comment by MrSimonEmms** [comment]
@geropl sure thing. Let me know when you want to schedule this and I'll get one ready for you

**Comment by geropl** [comment]
Just tested with a fresh SH installation running version `2022.10.0-rc1` and it works nicely.
The symptom might actually be caused by broken setups, or failures to start image-builds entirely.
