### ISSUE TITLE
Pagination links not properly themed

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#12537]
The links on the bottom of a paginated table are not properly themed.

<img width="1177" alt="Screenshot 2022-08-31 at 08 57 20" src="https://user-images.githubusercontent.com/372735/187613448-ab5db4fc-f931-4cc9-8e89-65bd8caa903a.png">

**Comment by gtsiolis** [comment]
Besides the styling issues, pagination also comes with some usability issues, see https://github.com/gitpod-io/gitpod/issues/12027.

> 1. Use the while button area as an active hover area instead of just the number
> 2. ...

**Comment by gtsiolis** [comment]
Thanks by the way for noticing, @svenefftinge! 🏀 

For the styling issues, the initial design specs linked in https://github.com/gitpod-io/gitpod/issues/12027, https://github.com/gitpod-io/gitpod/issues/11483, and https://github.com/gitpod-io/gitpod/issues/11285 should already cover what we need to changes here.

Just added also some [detailed designs](https://www.figma.com/file/3fdBIQangZxnOPm35uWJZX/Team-usage-view---Iterate-on-UI-based-on-designs%2C-feedback-%2311285?node-id=1463%3A8838) for the dark theme in case this helps. ✔️ 

Re-posting the designs here for visibility:

| Light Theme | Dark Theme |
|-|-|
| <img width="800" alt="pagination-light-theme" src="https://user-images.githubusercontent.com/120486/187662755-1c16e3ab-80b6-4b33-abf9-fd316dd24efd.png"> | <img width="800" alt="pagination-dark-theme" src="https://user-images.githubusercontent.com/120486/187662765-f760e84d-78f5-408e-a0f6-c853f89aaff0.png"> |

**Comment by Hardik500** [comment]
Hey, @gtsiolis @svenefftinge I would like to work on this issue

**Comment by svenefftinge** [comment]
Awesome! Thank you @Hardik500.

**Comment by gtsiolis** [comment]
@Hardik500 You can find the detailed design specs linked above in https://github.com/gitpod-io/gitpod/issues/12537#issuecomment-1232785471.

Feel free to open a PR and link back to this issue. 🏓

**Comment by Hardik500** [comment]
Thanks for the reference @gtsiolis

**Comment by Hardik500** [comment]
@gtsiolis In terms of adding new styling changes, do I also have to add the styling that is related to mobile and compact displays?
Also, what about infinite displays, cause I am not seeing that being handled right now?

**Comment by Hardik500** [comment]
https://github.com/gitpod-io/gitpod/issues/12537#issuecomment-1265655487
@gtsiolis @svenefftinge thoughts?

**Comment by gtsiolis** [comment]
@Hardik500 Feel free to skip anything related to responsive layout.

In the spirit of our [ship skateboards](https://www.notion.so/Ship-skateboards-f7f54cb1c69643e9ac42c9f2ddd9e46f) value, we can always break down the issue into smaller pieces and open a follow-up issue for the mobile layout. 🛹
