### ISSUE TITLE
is there potential disk space leak in docker/kubernate based system?

### ISSUE THREAD

**Issue by ivgd01** [gitpod-io/gitpod#1253]
### Describe the bug
First, thanks to gitpod for providing us such a great place to work/study/play with codes.
I'm totally new to coding, and docker, as I know gitpod is a cool system, it based on docker/kubernate cluster systems which can manage thounds of sub-nodes. 

But in this week, I encounterred two critical/block issues, like #1234 #1243
which the root cause is the device run out of the diskspace. I searched the `issues`  and found more related bugs, such as #1071 #1069 

This kind of issues may not happend by accident, I thinks there may be some bugs in the way of how to release the user-resources.

For example, 
User1
working in his workspace , generate files , commit to repo, then delete the temporay files in his worksapce.

User2
work the same way in the worksapce. gnerate files, then remove the files, repeate this lots of times.
especially generate large files (logs or something like that) for test. Or use the linux  `dd` command for a disk pressure test.

if you use df -h for monitoring the space
you will get the summary.

```
Filesystem      Size  Used Avail Use% Mounted on
overlay         193G  150G   43G  78% /
tmpfs            64M     0   64M   0% /dev
tmpfs            30G     0   30G   0% /sys/fs/cgroup
/dev/sdb        369G  175G  175G  50% /theia
/dev/sda1       193G  150G   43G  78% /etc/hosts
shm              64M  4.0K   64M   1% /dev/shm
tmpfs            30G     0   30G   0% /proc/acpi
tmpfs            30G     0   30G   0% /proc/scsi
tmpfs            30G     0   30G   0% /sys/firmware`
```

and serveral minutes later:

```
Filesystem      Size  Used Avail Use% Mounted on
overlay         193G  158G   36G  82% /
tmpfs            64M     0   64M   0% /dev
tmpfs            30G     0   30G   0% /sys/fs/cgroup
/dev/sdb        369G  188G  162G  54% /theia
/dev/sda1       193G  158G   36G  82% /etc/hosts
shm              64M  4.0K   64M   1% /dev/shm
tmpfs            30G     0   30G   0% /proc/acpi
tmpfs            30G     0   30G   0% /proc/scsi
tmpfs            30G     0   30G   0% /sys/firmware
```

From above, the disksapce  `/dev/sdb`   is getting smaller and smaller, at last run out of all the space.

What's the root cause of this kind of issue? docker disk leak? gitpod system issue?
It would be great if we can do some work for prevent this issue from happening again and again.

may related issue for referrernce ??
https://github.com/moby/moby/issues/21925

**Comment by ivgd01** [comment]
may related issue for referrernce ??
https://github.com/moby/moby/issues/21925

**Comment by Kreyren** [comment]
From available info i would guess that there is a problem with something relevant to garbage collection or assuming that most of the users affected seems to be located in US (based on the time of filled issues) i guess that hoster in US might have problems with hardware health that may cause a data corruption that then require restoration from backups which based on my experience has similar symptoms?

**Comment by svenefftinge** [comment]
There are different issues regarding disk space and we are shipping fixes on Wednesday.

**Comment by svenefftinge** [comment]
The fix/change is now deployed in production.
