### ISSUE TITLE
In-browser Emacs?

### ISSUE THREAD

**Issue by tiudvek** [gitpod-io/gitpod#12531]
## Is your feature request related to a problem? Please describe
Lately, I have used doom emacs in my projects, and I love it; except for the part where I don't have much space.

## Describe the behavior you'd like
Basically just basic emacs in the start, and then it has support for `.emacs.d` and the other stuff.

## Describe alternatives you've considered
Just normally use emacs on my computer, but mine is underpowered.

## Additional context
Nope, not rly.

**Comment by axonasif** [comment]
Try this:
https://github.com/emacs-lsp/lsp-mode/issues/2845#issuecomment-926154392

**Comment by tiudvek** [comment]
sheesh nice

**Comment by loujaybee** [comment]
Hey, @tiudvek 👋 

Gitpod has early support for a browser based terminal. Some users have explored setting up emacs that way. 

If you're interested, there's some information in how to get into the private beta, if you wanted to test that out. 

https://github.com/gitpod-io/gitpod/issues/17724
