### ISSUE TITLE
[Self-Hosted]Some problems encountered with self-hosting

### ISSUE THREAD

**Issue by Learntotolearn** [gitpod-io/gitpod#12541]
### Objective

1. When uploading a license, you will always be prompted with an error. I have installed the command provided when an error is reported, but it is not useful to me. 
![image](https://user-images.githubusercontent.com/85656971/187654297-90cb8b54-a32e-4103-86ab-86a9f548b7df.png)
![image](https://user-images.githubusercontent.com/85656971/187654439-6ab98332-dff7-47a4-bd23-48f83e6271c1.png)

2. There is an error in uploading the license, but I can modify the URL to install the page. At this time, I will submit an error after filling in the instance domain name and publisher 。
![image](https://user-images.githubusercontent.com/85656971/187654491-2203fe9f-2bb8-46c4-a6f7-c2a714b14576.png)

3. At this time, I can also click "application" on the page to jump to the page where gitpod is installed to check and install the configuration, even though there is an error. After installation, add the workspace. After entering the newly added workspace, the URL will be converted to "*. ws.xx.com". However, its certificate uses the pan domain name certificate of "*. xx.com" instead of the pan domain name certificate of "*. ws. xx.com".
![image](https://user-images.githubusercontent.com/85656971/187654547-bbf090be-2065-4c57-8eac-f55734bdd200.png)

**Comment by lucasvaltl** [comment]
Hey @Learntotolearn - which self-hosted license are you using? I assume you are using the [community license](https://www.gitpod.io/community-license)?

**Comment by Learntotolearn** [comment]
> Hey @Learntotolearn - which self-hosted license are you using? I assume you are using the [community license](https://www.gitpod.io/community-license)?
Hello，
Yes community license, here is part of the information I got in the mail:
You can download your free community license below. You'll have access to the full feature set until you reach 10 users.

**Comment by Learntotolearn** [comment]
> Hey @Learntotolearn - which self-hosted license are you using? I assume you are using the [community license](https://www.gitpod.io/community-license)?

Is there any difference between self-hosted license and community license?

**Comment by lucasvaltl** [comment]
The community license is just one of the two self-hosted licenses we have :) So in theory, you should be all good with the community license. I am not aware of an issue with it. Where are you based (roughly)? I suspect this might be a networking issue.

**Comment by Learntotolearn** [comment]
The deployed gitpod is self-hosted and can't be used which makes me sad.

**Comment by Learntotolearn** [comment]
Workspaces can be added successfully, but cannot be opened.
Web Tips:
HTTP ERROR 401

**Comment by lucasvaltl** [comment]
> The deployed gitpod is self-hosted and can't be used which makes me sad.
This makes me sad as well :) 

If you can, could you please [create a support bundle](https://www.gitpod.io/docs/self-hosted/latest/support-bundle) and send it to troubeshooting@gitpod.io? This includes information and errors from your installation and might help us better understand the issue.

**Comment by Learntotolearn** [comment]
> 1. When uploading a license, you will always be prompted with an error. I have installed the command provided when an error is reported, but it is not useful to me.

I feel very much that I have sent an email to this mailbox.

**Comment by Learntotolearn** [comment]
Happily, the third question is supported by official technicians. The problem has been found and solved.
Solution:
```
kubectl describe NetworkPolicy/blobserve -n gitpod
kubectl delete NetworkPolicy/blobserve -n gitpod
```
The reason is that some network policy blobserves are making mischief.
Thank you very much for Jimmy B's help.

**Comment by lucasvaltl** [comment]
Happy to hear that the problem has been solved. The email did not work because I missed a letter in that email address, it should be troubleshooting@gitpod.io - very sorry about that! Were you able to resolve your 1. and 2nd question as well?

**Comment by lucasvaltl** [comment]
Closing this for now, feel free to re-open if the questions above still stand.
