### ISSUE TITLE
Run Fewer Prebuilds

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#12583]
(Idea from a discussion with @mbrevoort)

We currently run prebuilds on every push. This has two problems:
- highly frequented branches are constantly running prebuilds so they are constantly cancelled and there's rarely a usable prebuild.
- Many other prebuilds are also not used.

### Proposed Solution
Run only the full prebuilds and [allow workspaces to use them to start incremental workspaces](https://github.com/gitpod-io/gitpod/issues/12582). Make it so that incremental workspaces are based on the last successful prebuild, so if there's a running full prebuild on the commit it is not considered, i.e. I don't need to wait for it.

### Benefits
- Fewer prebuilds
- No prebuilds in the hot path

**Comment by josepjaume** [comment]
Great idea! Would be a game changer for us!
