### ISSUE TITLE
Remove the pointer cursor on the timestamp column in team usage page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#12581]
### Problem to solve

While we dropped the timestamp sorting order in usage in https://github.com/gitpod-io/gitpod/pull/12501, we left behind the cursor-pointer class on the column header.

See [relevant diff](https://github.com/gitpod-io/gitpod/pull/12501/files#diff-133f74f34700fb70678ded1312ecb51ced6f277b9fba8ddb4b51fb95a45b202dL236-L246).

Cc @AlexTugarev @easyCZ @svenefftinge @jldec 

### Proposal

Remove the pointer cursor on the timestamp column in team usage page.

Fix should be relatively easy:

```diff
diff --git a/components/dashboard/src/teams/TeamUsage.tsx b/components/dashboard/src/teams/TeamUsage.tsx
index 05429d90c..c86c0ff06 100644
--- a/components/dashboard/src/teams/TeamUsage.tsx
+++ b/components/dashboard/src/teams/TeamUsage.tsx
@@ -232,7 +232,7 @@ function TeamUsage() {
                                             <span>Credits</span>
                                         </ItemField>
                                         <ItemField className="my-auto" />
-                                        <ItemField className="col-span-3 my-auto cursor-pointer">
+                                        <ItemField className="my-auto">
                                             <span
                                                 className="flex my-auto"
                                                 onClick={() => setIsStartedTimeDescending(!isStartedTimeDescending)}
```

**Comment by skrmain** [comment]
Hi @gtsiolis,

Can I work on the Issue...?

**Comment by gtsiolis** [comment]
@skrmain Yes, any open issue is available for picking up. Just make sure there's no one assigned and there's not any work-in-progress PR linking back to an issue. 🏓

**Comment by skrmain** [comment]
Hi @gtsiolis,

I have made the change and raised the PR.
