### ISSUE TITLE
[cli] Get URL of the workspace or a service running on a port

### ISSUE THREAD

**Issue by 32leaves** [gitpod-io/gitpod#126]
It can be handy to get the URL of the workspace, or a service running in the workspace, from a script. E.g. to send out a Slack message, register with some other infrastructure (think some central pubsub service) or when generating code/configuration during the build.

Gitpod could support something like `gp url` which would print the URL of the workspace on stdout and `gp url <port>` which would print the URL of a service listening on `<port>` in the workspace.

**Comment by sherbang** [comment]
Here's a quick and dirty workaround:

gp_url.py:
```
#!/usr/bin/env python

from __future__ import print_function

import os
import sys

if len(sys.argv) <> 2:
    print('USAGE: {} <port_number>'.format(sys.argv[0]))
else:
    print('https://{}-{}'.format(sys.argv[1], os.environ['GITPOD_WORKSPACE_URL'].split('https://')[1]))
```
