### ISSUE TITLE
Asia servers going offline constantly

### ISSUE THREAD

**Issue by TravelTimN** [gitpod-io/gitpod#1260]
### Describe the bug
I offer student support to developers who use Gitpod (specifically our template https://github.com/Code-Institute-Org/gitpod-full-template), and only students on the Asian servers are experiencing this issue. The servers constantly go from online to offline, very regularly. If they share their workspace with me, I can see this as well.

### Steps to reproduce
Use the template listed above.
Start new workspace with said template.
Try to develop on workspace.
Constantly (every 10-15 seconds?) get yellow Offline warning at bottom of window.

### Expected behavior
Expected bahavior - should not continuously go offline.

### Additional information
Sounds quite similar to existing case [#1206](https://github.com/gitpod-io/gitpod/issues/1206) but they're referencing the US Servers there.

### Example repository
https://github.com/kugared94/third-try-first-milestone-project
(although for this student's repo, it doesn't look like they actually used the proper template above, but same result either way, it's a Gitpod project that keeps going offline)

**Comment by svenefftinge** [comment]
Was that happening shortly before you entered the issue? I tried now using a VPN through Sydney. So super long turnaround, but never saw the yellow status bar.

**Comment by svenefftinge** [comment]
We had a couple of users burning a lot of CPU in the asia cluster two hours ago. This could lead to insufficient CPU cycles for other servers. We have a better CPU sharing model implemented in staging, which will be deployed to production on Wednesday. Thanks for reporting this.

**Comment by TravelTimN** [comment]
@svenefftinge thanks Sven. I didn't hear anything back from the students in Asia after this (middle of the night there for them). I'm back on tomorrow and left a message for a colleague based in Asia as FYI in case they see similar issues tomorrow morning. Thanks for the update!

**Comment by svenefftinge** [comment]
The fix/change is now deployed in production.
