### ISSUE TITLE
Improve usability of JetBrains Gateway when experiencing authentication errors

### ISSUE THREAD

**Issue by YoannBuch** [gitpod-io/gitpod#12625]
There are situations where a user might have the wrong logged in user, is not authenticated properly, or some other authentication related error that means they cannot access their workspace. Currently these errors are not obvious, not the resolution path. We should look to provide users in JetBrains Gateway who get authentication errors with:

1. Improved error messaging when they receive the `operation not permitted` errors. 
2. Information about their currently logged in user

<details>
  <summary>Original description</summary>
  
### Bug description

I am trying to open up a workspace using Jetbrains Gateway, but it does not work.

When I click on the "Open in IntelliJ IDEA" button in gitpod.io, I see that my Jetbrains Gateway is being called because of the notification popup I receive on my Ubuntu desktop but it does nothing else.

I expect it to launch a thin IntelliJ client instead.

I am using the following versions:
- Ubuntu 22.04.1 LTS
- Jetbrains Gateway: 2022.2.1
- Gitpod plugin: 0.0.1-main.4067

You will find attached the Jetbrains Gateway logs. Among other things you will find a suspicious `operation not permitted: missing get permission on workspace` error.

Jetbrains Gateway logs:
[gateway-logs-20220902-19042814161197084175745587.zip](https://github.com/gitpod-io/gitpod/files/9479911/gateway-logs-20220902-19042814161197084175745587.zip)

### Steps to reproduce

1. Launch Jetbrains Gateway
2. Navigate to https://gitpod.io/workspaces 
3. Open a workspace 
4. Click on "Open in IntelliJ IDEA"

=> desktop (Ubuntu) notification shows up 
![image](https://user-images.githubusercontent.com/513669/188204032-79ac7a13-1368-4680-a6ff-b6cbee6e0af8.png)

**but Jetbrains Gateway does not open IntelliJ.**

And there is no listed workspace:
![image](https://user-images.githubusercontent.com/513669/188204223-6e517f1b-2bea-4f84-b2fa-d5364c998e1c.png)

### Workspace affected

denisturbiez-apikotlin-vctn84gfozw.ws-eu63

### Expected behavior

- Succesfully launch IntelliJ Idea from gitpod.io using Jetbrains Gateway
- See workspaces in Jetbrains Gateway

</details>

**Comment by akosyakov** [comment]
@YoannBuch Please share logs as explained here: https://www.gitpod.io/docs/troubleshooting#gitpod-logs-in-jetbrains-gateway

**Comment by akosyakov** [comment]
@YoannBuch This workspace does not seem to belong to you. Live sharing of workspaces is not supported by JB products. cc @loujaybee

**Comment by YoannBuch** [comment]
Thanks for the reply @akosyakov.

I do have access to this workspace in gitpod.io, however maybe there's a mismatch between what Jetbrains Gateway thinks I am vs who owns the workspace?

How does Gateway know in the first place who I am? How does it connect to gitpod.io? I don't recall setting up any credentials.

**Comment by akosyakov** [comment]
> I do have access to this workspace in gitpod.io, however maybe there's a mismatch between what Jetbrains Gateway thinks I am vs who owns the workspace?


It is using an account with which you authenticated the plugin. You can click logout and then loging again. If you changed account in your browser.
<img width="1370" alt="Screenshot 2022-09-05 at 09 38 27" src="https://user-images.githubusercontent.com/3082655/188394655-ceb4e245-0ea3-4a85-a95d-51c44f52f2be.png">

**Comment by YoannBuch** [comment]
Ok makes sense... I had totally forgot that step :man_facepalming: 

Thanks a lot!

I guess a nice error message on the UI would be helpful in that case :)

You can close the issue :+1:

**Comment by loujaybee** [comment]
Thanks for raising @YoannBuch! 

Actually, rather than close I'm going to convert this issue from a bug to a feature request. It'd be good if we're able to show user information, or better debug messaging in the Gateway for these types of authentication errors. I've updated the description, but have captured your original context in a toggle so we have it for future reference, thanks!

**Comment by loujaybee** [comment]
Would be good to define this as an application error code, with a description, e.g. applying the following approach: 

- https://github.com/gitpod-io/gitpod/issues/12089
