### ISSUE TITLE
Preview environment fails to start due to cert-manager webhook, preventing workspace integration tests from running

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#12629]
### Bug description

In this case, the preview environment job failed, which prevented the tests from running.

The failure was:
```
STDERR: Error from server (InternalError): error when creating "k8s.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "[https://cert-manager-webhook.cert-manager.svc:443/validate?timeout=10s](https://cert-manager-webhook.cert-manager.svc/validate?timeout=10s)": EOF

    at handleResult (/workspace/.werft/util/shell.ts:42:19)
    at exec (/workspace/.werft/util/shell.ts:60:9)
    at Installer.install (/workspace/.werft/jobs/build/installer/installer.ts:368:13)
    at /workspace/.werft/jobs/build/deploy-to-preview-environment.ts:355:19
    at step (/workspace/.werft/jobs/build/deploy-to-preview-environment.ts:44:23)
    at Object.next (/workspace/.werft/jobs/build/deploy-to-preview-environment.ts:25:53)
    at fulfilled (/workspace/.werft/jobs/build/deploy-to-preview-environment.ts:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Steps to reproduce

Refer to this [internal slack thread](https://gitpod.slack.com/archives/C03E52788SU/p1662143960600599?thread_ts=1662122068.594929&cid=C03E52788SU) for context

### Expected behavior

Ideally the web-hook would not fail, and the preview environment would start.

**Comment by kylos101** [comment]
Another reference: https://werft.gitpod-dev.com/job/gitpod-build-wk-inte-test-20220902190031.0/raw

**Comment by kylos101** [comment]
Another: https://werft.gitpod-dev.com/job/gitpod-build-wk-inte-test-20220907030249.0/raw

**Comment by kylos101** [comment]
Additional manifestations of this related failure:
https://gitpod.slack.com/archives/C03E52788SU/p1662690511179629
https://gitpod.slack.com/archives/C03E52788SU/p1662690520439169

**Comment by meysholdt** [comment]
Seen again here: https://werft.gitpod-dev.com/job/gitpod-build-se-small-usage-ui-impr.9/raw
Context: https://gitpod.slack.com/archives/C032A46PWR0/p1663058556909449?thread_ts=1663056299.288899&cid=C032A46PWR0

**Comment by kylos101** [comment]
See again [here earlier today](https://werft.gitpod-dev.com/job/gitpod-workspace-run-integration-tests-main.123/raw) @meysholdt

**Comment by meysholdt** [comment]
We've refactored cert handling and moved to ZeroSSL. We assume this is fixed unless somebody sees it sagin.
