### ISSUE TITLE
bulk variables or .env file support for workspace

### ISSUE THREAD

**Issue by Nishchit14** [gitpod-io/gitpod#12634]
## Is your feature request related to a problem? Please describe
I have more than 30 variables for my monorepo. It is hard to add one by one at workspace creation, and also difficult to manage/update on the go while developing.

## Describe the behaviour you'd like
It would help if there is a feature available to add/update variables in bulk. It would be even better if we can upload the .env file.

## Additional context
render.com if providing this feature (bulk variables and .env file)

**Comment by axonasif** [comment]
Duplicate of https://github.com/gitpod-io/gitpod/issues/12243
