### ISSUE TITLE
Don't `open-preview` if there is an opend preview tab already.

### ISSUE THREAD

**Issue by Jehong-Ahn** [gitpod-io/gitpod#12633]
## Is your feature request related to a problem? Please describe
When a stopped container restarts, there should be opend preview tab.
In this situation, gitpod.yml `open-preview` setting will create another preview tab with another split window.

## Describe the behaviour you'd like
Before open preview tab, the gitpod should inspect other preview tab already opend.

**Comment by jeanp413** [comment]
Fixed upstream https://github.com/microsoft/vscode/pull/163389, will cherry-pick it, will be in tomorrows insiders and in the next stable release 1.73
