### ISSUE TITLE
[integration tests] add prebuilds workspace PVC integration test from PVC test plans

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#12638]
## Is your feature request related to a problem? Please describe

Manually go thru. the PVC test plans take about half a day, and it's too long for each release to manually test against all the PVC test plans.

## Describe the behaviour you'd like

Trying to add more integration tests from the PVC test plans if possible, and make the manual PVC tests as small as possible.
Therefore, we could minimize the deployer only need to test the manually PVC test plans. 

## Describe alternatives you've considered

None

## Definition of Done (DoD)
- Update existing tests with PVC
  - [x] TestPrebuildWorkspaceTaskSuccess https://github.com/gitpod-io/gitpod/pull/12859
- Create new test with Prebuild + PVC
  - [x] PVC test plan prebuild workspace case 1 https://github.com/gitpod-io/gitpod/pull/13024
  - [x] PVC test plan prebuild workspace case 2 https://github.com/gitpod-io/gitpod/pull/13371
  - [x] PVC test plan prebuild workspace case 3 https://github.com/gitpod-io/gitpod/pull/13371
  - [x] PVC test plan prebuild workspace case 4 https://github.com/gitpod-io/gitpod/pull/13223, https://github.com/gitpod-io/gitpod/pull/13268
  - [x] PVC test plan prebuild workspace case 5 https://github.com/gitpod-io/gitpod/pull/13223, https://github.com/gitpod-io/gitpod/pull/13268

## Additional context

#7901

**Comment by jenting** [comment]
> @jenting could you update the issue description, so we can see which test cases are left? 🙏

We could check the Definition of Done (DoD) to see which test cases are left. If that's not enough, we can link the notion page.

**Comment by kylos101** [comment]
The DoD is perfect, I see 2 tests have PRs, and 2 are left (need PRs). Thank you, @jenting !

**Comment by jenting** [comment]
I have finished all the DoD, closing this issue.
