### ISSUE TITLE
License.txt refers to nonexistent License.GPF.txt

### ISSUE THREAD

**Issue by tv42** [gitpod-io/gitpod#12639]
### Bug description

> 2. enterprise features are licensed under Gitpod Self-Hosted Free Licensing Terms, see License.GPF.txt

Said file does not exist. Did you mean License.enterprise.txt?

### Steps to reproduce

https://github.com/gitpod-io/gitpod/blob/2871bdc1b853dbdef502c54cf950e7319babef61/License.txt#L6

**Comment by corneliusludmann** [comment]
@securitymirco are you that person that can help us with this?

**Comment by securitymirco** [comment]
@corneliusludmann not directly but let me check with @KlasenK

**Comment by lucasvaltl** [comment]
@securitymirco were you able to check with @KlasenK?

**Comment by securitymirco** [comment]
Not yet - sorry , @KlasenK do you know where we've got our license information stored? "License.GPF.txt" does seem to exist - License.enterprise.txt does seem to exit.

**Comment by securitymirco** [comment]
@tv42 Yes that would be `License.enterprise.txt` instead.

**Comment by lucasvaltl** [comment]
@meysholdt can we mark this as complete?
