### ISSUE TITLE
[Local Preview] Show Full Logs

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#12655]
## Is your feature request related to a problem? Please describe
I used the local preview yesterday, and found it difficult to diagnose why it didn’t work. Getting to the logs is difficult

## Describe the behaviour you'd like
Being able to show the full logs (e.g. with a keypress or a flag) would be handy

## Context
- [Internal discussion](https://www.notion.so/Product-Engineering-Sync-2ebc3b84700545c3bd20d1efbc616aa1?d=2b6768f10a4e46a7b0672e7fa75ade1b#56c9ff0e858a4f459e1370479c8b167b) where this came up

**Comment by Pothulapati** [comment]
👋🏼 

 I think the most straightforward way to fix this is to remove the `--rm` flag from the documentation which [just cleans up the container](https://docs.docker.com/engine/reference/run/#clean-up---rm). And when ever the `run` command fails. We could just ask them to copy over the logs by running `docker container cp gitpod:logs.txt ./logs.txt`. WDYT?

**Comment by lucasvaltl** [comment]
Works for me :)
