### ISSUE TITLE
Not able to get OAuth-like flow to callback VS Code in browser

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#12660]
> I'm using vscode.env.asExternalUri() and this works perfecty in GitHub Codespaces. The same flow fails in Gitpod VS Code with a Not Found page. The URL looks correct, the host is the same as the actual workspace. 

More context https://discord.com/channels/816244985187008514/1015881863929274378/1015881867301498880

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3qgwa)

**Comment by ptrthomas** [comment]
@jeanp413 thanks ! when would this fix be available on gitpod.io/workspaces ?

**Comment by jeanp413** [comment]
@ptrthomas it will take some time as deployment of this fix depends on workspace team schedule maybe 1-2 weeks

**Comment by ptrthomas** [comment]
I was just able to confirm that this works in gitpod.io/workspaces
