### ISSUE TITLE
expose workspace and ephemeral disk space usage and limit to supervisor

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#12676]
Right now in JB user see only disk usage of the entire node. We would like to show real disk space. I think it also makes sense to show usage of ephemeral disk space to improve awareness for users about differences between them.

**Comment by felladrin** [comment]
A user on Discord also asked for a way to track the workspace space usage [[1](https://discord.com/channels/816244985187008514/1043068292505546772)].

**Comment by akosyakov** [comment]
It seems we can calculate it in supervisor instead with: `df --output=size,used / /workspace`
Seconds line is the disk space. Ephemeral space is a difference between first and second line.
