### ISSUE TITLE
 No space left on device

### ISSUE THREAD

**Issue by kwokkakit** [gitpod-io/gitpod#1268]
### Describe the bug
 No space left on device

cannot initialize workspace: cannot initialize workspace: cannot restore backup: tar /mnt/workingarea/7edbcdc6-7c96-4266-b4ea-2370d54ccf85: exit status 1;tar: write error: No space left on device
Please file an issue if you think this is a bug.

**Comment by jankeromnes** [comment]
Hi @kwokkakit, sorry about this problem, and thanks a lot for reporting it. We're investigating.

**Comment by jankeromnes** [comment]
This incident should be resolved. Thanks for your patience.

Also, since we've introduced proper disk space quotas this morning, it should not happen again.
