### ISSUE TITLE
[UBP for individuals] Configure a usage limit for usage-based billing in personal settings

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12684]
The design and behavior of this UI should be very similar to the UBP usage limit input for teams.

- The limit value is pre-set to x credits, where x = the free credit allowance for individuals.
- Thie UI should allow the value to be set above (or equal to) the free credit allowance, but not below.

![Image](https://user-images.githubusercontent.com/849592/188622052-89620a39-f285-4b09-b628-c83a851a980b.png)

**Comment by svenefftinge** [comment]
The usage limit is unrelated to the amount of credits we grant on for free. I.e. It should be always 0 when there is no pay-as-you-go plan active. We should think of the usage limit as a debit limit.

**Comment by andrew-farries** [comment]
Removing my assignment from this now that https://github.com/gitpod-io/gitpod/pull/12942 is merged.

Users can now sign up for UBP, so this issue is unblocked.

**Comment by AlexTugarev** [comment]
This needs to be verified. I think it's already solved.

**Comment by AlexTugarev** [comment]
Verified in a test deployment, cf. https://github.com/gitpod-io/gitpod/pull/13076#issuecomment-1250836541
✅
