### ISSUE TITLE
[UBP for individuals] Show personal usage when usage-based billing is configured

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12686]
This view will live at gitpod.io/usage. The UI should show a tab at the same top level as personal settings, similar to the way team usage lives alongside team settings.

Behavior of the personal usage view should mirror the team usage view, with similar selection of time-range for billed and unbilled usage, and the same details in each colum.

In addition to the "total" credits used, the UI should include the number of "free" credits. If users subtract the free amount, from the total amount, this should result in the total invoiced credits.

**Comment by AlexTugarev** [comment]
Also, the PR to re-enable attribution of personal account is merged as well. https://github.com/gitpod-io/gitpod/pull/12839

**Comment by jldec** [comment]
Per discussion ([internal](https://gitpod.slack.com/archives/C02EN94AEPL/p1663755673106779?thread_ts=1663748289.192209&cid=C02EN94AEPL))

> - All usage exploration should happen in the usage view.
> - In the scenario where individuals are wondering about their invoice, the usage view needs to match the period they are exploring (which may be mid-month to mid-month - separate issue incoming)
> - **The usage view does not need to show the amount of free credits or prepaid credits.**
> - Free or prepaid credit amounts should appear with the Usage Limit in the billing page (together with current total usage as reported to Stripe)
