### ISSUE TITLE
Customise onboarding (Customise when: Gitpod release and Gitpod Walkthrough are shown)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#12704]
**Context**
There are some cases where users might not want the changelog (for Open Source, and Self-Hosted, etc). 

**Use Cases**
1. For optimised "onboarding" flows in Open-Source or Self-Hosted
2. When hopping hosts, Self-Hosted installs or onto SaaS (you will see a changelog multiple times)
3. When creating a custom onboarding flow into Gitpod in Self-Hosted - Self-Hosted customers often have a more "high-touch" onboarding into Gitpod than users on SaaS or in Open Source projects. The need for a self-serve onboarding is less relevant as these customers might choose to have literal in-person sessions with their users to onboard them. 

**Potential solutions**
1. Improved heuristic for when release notes are shown, e.g. 
    1. Don't show release notes for a new project the user is opening (to the user) - prioritise the onboarding experience of the project instead of Gitpod onboarding. 
    1. Only to users who are new to Gitpod - prioritise Gitpod onboarding over the project onboarding. 
2. Options for a user to disable entirely Release Notes for themselves
3. Options for disabling the Release Notes + Walkthrough on a per-project basis
4. Disable release notes or walkthrough on an installation level (e.g. a full Self-Hosted installation) where the company will take ownership of onboarding both into the project AND into Gitpod as a product

![image](https://user-images.githubusercontent.com/5528307/188696417-102b86a3-f941-4218-a60e-547b36946a4c.png)

**Comment by Siddhant-K-code** [comment]
Also, worth noting that: Currently it shows release notes for every new workspace (it should be limited to the first workspace only, after every release)

Related [Internal Discussion](https://gitpod.slack.com/archives/C01KPEPNBD0/p1664987281685579)

**Comment by loujaybee** [comment]
> Currently it shows release notes for every new workspace (it should be limited to the first workspace only, after every release)

This is a bug, not expected behaviour let's raise a separate issue 🙏

**Comment by Siddhant-K-code** [comment]
Opened a new issue here: https://github.com/gitpod-io/gitpod/issues/13638

**Comment by filiptronicek** [comment]
The options for disabling release notes altogether are here 🙂: both in VS Code Browser and VS Code Desktop. The configuration is `"gitpod.showReleaseNotes": false`. With Settings Sync, this should sync from VS Code Browser to Desktop and vice-a-versa.

cc @Siddhant-K-code @loujaybee

**Comment by jeanp413** [comment]
Closing this for now, as @filiptronicek mentioned now there's `gitpod.showReleaseNotes` setting

**Comment by loujaybee** [comment]
Thanks @jeanp413 ! I will improve the description of this issue. It's useful to know that release notes can be configured! I don't believe that's covered in our documentation, is it? If not it should be! This issue was more about re-thinking the different user contexts of our onboarding. We are currently assuming that all users want to see the changelog and gitpod onboarding walkthrough, but for our customers, or in an open source context, having customizable onboarding flows makes a lot of sense.

**Comment by filiptronicek** [comment]
With changelogs gone from our VS Code distributions, is it time to close this @loujaybee?
