### ISSUE TITLE
Sandbox error

### ISSUE THREAD

**Issue by jimbobding** [gitpod-io/gitpod#1271]
Hi 

Had an issue today in which my workspace failed to load and was greeted with this error
![Screen Shot 2020-02-26 at 13 50 25](https://user-images.githubusercontent.com/55886146/75351790-9c638180-58a0-11ea-8449-d57cf2dc8245.png).
everything seems to be okay now but I just thought I would flag it with you

**Comment by jankeromnes** [comment]
Hi @jimbobding, many thanks for reporting this, as screenshots and complete error messages are really helpful when troubleshooting an issue.

Also, I believe this is #1270, so I'll close this issue for now. Please let me know if this is still happening, or if you think that it's a different issue.
