### ISSUE TITLE
apt install not working

### ISSUE THREAD

**Issue by johnmckinzie** [gitpod-io/gitpod#1272]
I'm trying add Hugo to the full workspace Docker image. Below are my files:

`.gitpod.yml`
```
image:
  file: .gitpod.Dockerfile
```

`.gitpod.Dockerfile`
```
FROM gitpod/workspace-full

# Install custom tools, runtime, etc.
RUN sudo apt-get update \
    && sudo apt-get install -y \
        hugo \
    && rm -rf /var/lib/apt/lists/*
```

I'm also getting the following error when I try and run `sudo apt` in the shell:

`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

Anything jump out as incorrect? Is there a place to see the logs for the image building?

**Comment by JesterOrNot** [comment]
Can you send the link to the repo that is problematic?

**Comment by JesterOrNot** [comment]
Also, you cannot run things as root in our workspaces for security reasons see #39

**Comment by JesterOrNot** [comment]
And welcome to the Gitpod community by the way :tada:

**Comment by johnmckinzie** [comment]
Haha, thanks! And thank you for the quick response.

https://github.com/johnmckinzie/lcr-hugo/tree/docker-hug

Roger that on running as root. 👍

**Comment by JesterOrNot** [comment]
I found the issue, I will prepare a small PR

**Comment by johnmckinzie** [comment]
Great. Thank you so much for the help. I'm definitely intrigued by Gitpod for several use cases, so I'm excited to start using it.

**Comment by JesterOrNot** [comment]
In your .gitpod.yml file you have this
```yaml
tasks:
  - init: Update GitHub email
    command: git config user.email "johnmckinzie@users.noreply.github.com"
```
This init command will fail because there is no Update command as far as I know did you mean for this to be a label?

**Comment by JesterOrNot** [comment]
See https://github.com/johnmckinzie/lcr-hugo/pull/1

**Comment by JesterOrNot** [comment]
If this is meant to be a label let me know and I can show you how to do that

**Comment by johnmckinzie** [comment]
The git command is just to set the repo email to the github masked one. I probably don't need it after it's run once. Probably need to look at the lifecycle of the container.

I merged PR the and pulled the branch but `hugo` is still not installed/found.

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/75373101-3f130480-588f-11ea-82a3-cbaee7f3123f.png)

Hugo is in $PATH try `hugo new site <SITENAME>` where SITENAME = the name of the site

**Comment by johnmckinzie** [comment]
```bash
gitpod /workspace/lcr-hugo $ hugo new site test
bash: hugo: command not found
```

**Comment by JesterOrNot** [comment]
Which branch are you on? We merged into the docker-hug branch

**Comment by johnmckinzie** [comment]
```bash
gitpod /workspace/lcr-hugo $ git branch
* docker-hugo
  master
gitpod /workspace/lcr-hugo $ git pull
Already up to date.
```

**Comment by JesterOrNot** [comment]
That is odd. Try creating a new workspace

**Comment by johnmckinzie** [comment]
It's working now after creating a new workspace. Weird that it would rebuild by start/stopping workspace. Thank you for all your help!

**Comment by JesterOrNot** [comment]
No problem!

**Comment by JesterOrNot** [comment]
Should we close this issue?

**Comment by johnmckinzie** [comment]
Done.
