### ISSUE TITLE
Change Color of Verify User Button

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#12737]
## Is your feature request related to a problem? Please describe

This isn't necessarily a problem but rather an improvement. I noticed myself glazing over the new Verify User button because of it's current coloring.

## Describe the behaviour you'd like

In order to differentiate the Verify User button from the Block User and Delete User buttons I believe it would be helpful to give it a blue coloring. The red color it currently has is generally used to indicate danger whereas I think a blue color would fit better.

## Describe alternatives you've considered

N/A

## Additional context

https://getbootstrap.com/docs/5.2/components/buttons/

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3qioa)

**Comment by geropl** [comment]
@gtsiolis linking you because of color in the UI 🙃
