### ISSUE TITLE
Notification when workspace has started

### ISSUE THREAD

**Issue by mbrevoort** [gitpod-io/gitpod#12735]
## Is your feature request related to a problem? Please describe
Sometimes workspaces take a little while to start, and it's convenient to go do something else meanwhile rather than staring at the loading screen. But it's easy to get distracted and be burdened to continue to check on the progress.

## Describe the behaviour you'd like
If the browser tab is unfocused when the workspace successfully starts (or tragically fails), send a [browser notification](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API).

## Describe alternatives you've considered
* Melodramatically  roll fingers on the table repeatedly, chin slumped in other hand staring at the screen. 
* Switching to some other task and forgetting the workspace started
* Checking back incessantly like returning to the kitchen to check if the water is boiling yet. 

## Additional context
[internal customer request](https://gitpod.slack.com/archives/C033MA45L5S/p1662501764803569)
[related internal conversation](https://gitpod.slack.com/archives/C01KPEPQYE6/p1653942099830409)

**Comment by rgoldfinger-quizlet** [comment]
Can we keep this open? This feature would be a nice help for us.

**Comment by axonasif** [comment]
It'll stay open now as you commented @rgoldfinger-quizlet!
