### ISSUE TITLE
Gitpod slow?

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1274]
### Describe the bug

Gitpod seems to responding unusually slowly- having issues getting into dashboard as well- other websites not an issues. Is there a server issue? Referencing: e6a33b5e-b87b-4537-ae70-09342337a95a

**Comment by nabildroid** [comment]
me too I experience that

**Comment by RDIL** [comment]
Same

**Comment by svenefftinge** [comment]
Just tried to reproduce in US cluster, but seems fine. I see a node that was high on CPU usage during the time you reported this, though.
Was it the startup of workspaces or the usability of them that was affected?

**Comment by RDIL** [comment]
Both

**Comment by svenefftinge** [comment]
Is it still like that for you right now?

**Comment by RDIL** [comment]
Its being slow running right now for me, but startup isn't a problem anymore.

**Comment by svenefftinge** [comment]
Could you provide more details on what exactly is slow? Is it content assist, typing in terminal or running processes in the terminal?
What languages are you working with?

**Comment by RDIL** [comment]
I'm working with React/JSX, and the websockets and git operations are the slow part

**Comment by ColbyWTaylor** [comment]
Also working with react, the text being entered wouldn't respond for several seconds, trying to open a directory was delayed, but no issues with other websites.

**Comment by ColbyWTaylor** [comment]
worked fine later on, btw

**Comment by svenefftinge** [comment]
We have moved out prebuilds to a dedicated node pool and believe this was causing the slowness. Please keep us posted.

**Comment by baharestani** [comment]
It unusably slow

**Comment by svenefftinge** [comment]
> It unusably slow

Can you share more information? What exactly is slow and where are you located?

**Comment by baharestani** [comment]
Gitpod takes longer than a minute to load a git repository. I didn't wait longer than that so I don't know how much longer it would take but at least 1 minute.
I am located in Sydney, Australia.

**Comment by RDIL** [comment]
Yeah it can take like 3-4 minutes usually
