### ISSUE TITLE
Autentication Gitlab

### ISSUE THREAD

**Issue by diegoernani** [gitpod-io/gitpod#1275]

**Comment by jankeromnes** [comment]
Hi @diegoernani, are you having a problem of some sort? It is hard to tell from your issue title / comment.

**Comment by zhuohoudeputao** [comment]
Sorry, something went wrong 😓
GitLab authentication failed. Please try again in a few minutes.
_________________________________________________________________
When I change access to github, it appears.

**Comment by AlexTugarev** [comment]
@zhuohoudeputao I'm checking this. Thanks for reporting 🙏

**Comment by AlexTugarev** [comment]
@zhuohoudeputao could you try again, please? it seems, that GitLab's API server are busy sometimes.

**Comment by AlexTugarev** [comment]
🎉 the fix was deployed!
