### ISSUE TITLE
[SLO] `createWorkspace` and `startWorkspace` API methods are too slow

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#12768]
### Bug description

We've recently implemented these three SLOs:

- During each month, we'll serve 99% of `createWorkspace` requests successfully within 10 seconds
- During each month, we'll serve 99% of `startWorkspace` requests successfully within 10 seconds
- During each month, we'll serve 99% of `getWorkspaces` requests successfully within 5 seconds

That's because creating workspaces, starting workspaces, and listing workspaces are deemed the three most important actions performed by `server`, and since they are so central to the UX of Gitpod, we want them to be very reliable and fast.

Unfortunately, two of these SLOs are already failing:

<img width="1319" alt="Screenshot 2022-09-08 at 14 08 54" src="https://user-images.githubusercontent.com/599268/189118186-dba2ce00-2ca3-47e6-9b83-a740251398bc.png">

This means we'll need to investigate why `createWorkspace` and `startWorkspace` are not performing the way we want them to, and then fix and/or optimize them.

### Steps to reproduce

1. Use the Gitpod dashboard to create or start a workspace
2. This should work successfully within 10 seconds 99% of the time in a month

### Expected behavior

This actually works within constraints 97% and 98.22% of the time.

**Comment by jankeromnes** [comment]
@gitpod-io/engineering-workspace What is the expected response time (or SLO) of `/ws-manager/startWorkspace`?

See also [this comment](https://gitpod.slack.com/archives/C02EN94AEPL/p1662639651940899?thread_ts=1662637018.194149&cid=C02EN94AEPL) (internal) by @csweichel:

> Gut feeling: it's actually the response times from  ws-manager which cost here, because ws-manager (mkI) waits for the pod (and possibly PVC) to be scheduled before returning.

**Comment by kylos101** [comment]
Hi @jankeromnes , we don't have one currently, but, thanks for the idea. :smile: 

Can you share a link to the Honeycomb trace you mentioned above? I assume you're referring to a trace from production. 214s, is about 3.5 minutes, which would make sense if we were scaling up a node at that time to schedule the related workspace pod. 

To confirm it was node scale-up, with the instanceId, from the `workspace-cluster` project, we should be able to see in the logs that this workspace pod was unschedulable, until we added a new node to the cluster. In other words, I would expect that startWorkspace is intermittently slow, especially when scaling up a new node.

**Comment by geropl** [comment]
I think conceptually, the ideal case would be if ws-manager would handle that call in an async fashion. :sun_with_face: 

@jankeromnes But until we're there, we could try to _exclude_ all a) time and b) error cases that are introduced by `ws-manager` connections. With that we'd still have an imperfect picture (because we'e loose insight there), but we'd put the focus on the WebApp parts for starters.

**Comment by sagor999** [comment]
This is most probably the case when we are waiting for new node to spin up and waiting for Pod to actually become scheduled (as Chris mentioned).
StartWorkspace call has a 10min timeout as well. 
I am not sure what the impact will be if we were not to wait for the Pod to become scheduled before returning from that function.

**Comment by geropl** [comment]
> I am not sure what the impact will be if we were not to wait for the Pod to become scheduled before returning from that function.

I assume we'd need to store state outside of the Pod, which would/could be solved by `ws-manager-mkii` IIRC. But probably not something we want to tackle now, hence the suggestion to exclude it. :+1:
