### ISSUE TITLE
Error: Cannot read property 'sha' of undefined

### ISSUE THREAD

**Issue by davimury** [gitpod-io/gitpod#1276]

**Comment by Kreyren** [comment]
afaik this means that there is a syntax error in your gitpod.yml file

**Comment by svenefftinge** [comment]
Please share more information - ideally a link to a public repository to reproduce the error.

**Comment by davimury** [comment]
I fixed the error, but take me a while to understand the error, you could
show more simplified eros like "  there is a syntax error in your
gitpod.yml file", would easy to fix the error if with was like that

Em sex., 28 de fev. de 2020 às 05:15, Sven Efftinge <
notifications@github.com> escreveu:

**Comment by svenefftinge** [comment]
Thanks, I agree. Closing this as a duplicate of #717.
