### ISSUE TITLE
Collapse empty subfolders

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#1277]
In Gitpod/Theia each subfolder is displayed in the file explorer regardless of it being empty or not. Especially in larger multi module Java projects this leads to very deep nested folder structures like this one:

![image](https://user-images.githubusercontent.com/5059773/75546129-30ac2080-5a28-11ea-895a-c1ead761e596.png)

It would be awesome to have a mechanism like in VSCode that collapses such folder structures so that they do look more like this:

![image](https://user-images.githubusercontent.com/5059773/75546284-7f59ba80-5a28-11ea-856e-72c9ef74a4a6.png)

**Comment by akosyakov** [comment]
It's called compressing, not collapsing, but anyway an issue in the upstream: https://github.com/eclipse-theia/theia/issues/4783

**Comment by Sandared** [comment]
Ah thanks for clarifying. That would be a super handy feature :)

Looking forward to it!

Am So., 1. März 2020 um 11:36 Uhr schrieb Anton Kosyakov <
notifications@github.com>:
