### ISSUE TITLE
[self-hosted/docs] GKE (and potentially EKS) scale to zero with node labels might not scale up

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#12782]
## Is your feature request related to a problem? Please describe

Placeholder issue

## Additional context

- [Cluster autoscaler FAQ: How can I scale a node group to 0?](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-can-i-scale-a-node-group-to-0)
- [Cluster Autoscaler scaling from 0 on AWS EKS stops working after CA pod is restarted](https://github.com/kubernetes/autoscaler/issues/3780)

**Comment by kylos101** [comment]
Hi @lucasvaltl , can you help me? I'm not sure what is needed from Team Workspace for this issue. Is there something specific that is needed?

**Comment by shaoye** [comment]
we can confirm it also doesn't work on EKS
