### ISSUE TITLE
Support `settings` in `.gitpod.yml`

### ISSUE THREAD

**Issue by felipecassiors** [gitpod-io/gitpod#1279]
Support VS Code/Theia `settings` entries in `.gitpod.yml` would help us to ensure an even more concise developer environment. 

Visual Studio Code Remote Containers already supports it: https://code.visualstudio.com/docs/remote/containers#_container-specific-settings

**Comment by svenefftinge** [comment]
Just to ensure we are on the same page, here. You are asking to override workspace level settings through a gitpod-specific settings entry in `.gitpod.yml`?

**Comment by felipecassiors** [comment]
Oh, didn't notice `{{workspaceFolder}}/.theia/settings.json` work for that. Despite it seems obvious since `vscode` supports the same thing, it would be useful at least if the documentation pointed this.

**Comment by Kreyren** [comment]
> it would be useful at least if the documentation pointed this.

Feel free to contrib to docs (https://github.com/gitpod-io/website) then :p 

Or do you want me to process it?

**Comment by felipecassiors** [comment]
I can do, however, most likely I won't have time this week =/. Feel free to do it if you want =).
