### ISSUE TITLE
.gitpod.yml:vscode:extensions are not auto installed on Desktop VSCode

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#12791]
### Bug description

I have added an extension here:
https://github.com/axonasif/test/blob/fed82b192cddb3339dfce36b1d07d53a5580ae22/.gitpod.yml#L6

However it doesn't get installed when I have VSCode Desktop selected as the default IDE on my https://gitpod.io/preferences

### Steps to reproduce

- Follow: https://www.gitpod.io/docs/ides-and-editors/vscode-extensions#installing-an-extension
- Follow: https://www.gitpod.io/docs/ides-and-editors/vscode#on-workspace-start
- Observe that the extension was not installed on VSCode Desktop

### Expected behavior

Should automatically get installed as in VSCode Browser.

### Example repository

https://github.com/axonasif/test/blob/fed82b192cddb3339dfce36b1d07d53a5580ae22/.gitpod.yml#L6

### Anything else?

Originally reported in: https://discord.com/channels/816244985187008514/1009738248110747719

**Comment by akosyakov** [comment]
@axonasif Why would you do it like that? You can list ms-vscode.cpptools. VS Code Desktop is using MS Marketplace and can install from there.

**Comment by axonasif** [comment]
> @axonasif Why would you do it like that? You can list ms-vscode.cpptools. VS Code Desktop is using MS Marketplace and can install from there.

As we discussed internally, it was to see if I can reproduce the bug as one of our community members bought it up on discord 😄

**Comment by purkhusid** [comment]
I raised the issue originally because rust-analyzer is failing to publish to open-vsx(https://github.com/rust-lang/rust-analyzer/issues/11080) and I wanted to work around this by using the release on github.

**Comment by benvp** [comment]
I have the same issue as I need an extension which includes a language server which needs to be compiled with the same version running the project (ElixirLS).

My workaround for now is to build the extension in the Dockerfile and then install it using a `folderOpen` vscode task. This works both in the browser and in VSCode locally.

Would love to see this fixed and also support local paths to extensions in `.gitpod.yml`

**gitpod/install_extensions.sh**:

```bash

#!/bin/bash
#
# Install ElixirLS extension if we run inside gitpod and run desktop vscode.
# This is a workaround until https://github.com/gitpod-io/gitpod/issues/12791
# is fixed.

ELIXIR_LS_VERSION=0.11.0

if test $USER = "gitpod"
then
  code --install-extension $HOME/extensions/elixir-ls-$ELIXIR_LS_VERSION.vsix
else
  echo "Nothing to do"
fi

exit 0
```

**.vscode/tasks.json**:

```jsonc
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Gitpod: Install ElixirLS extension",
      "type": "shell",
      "command": "./gitpod/install_extensions.sh",
      "group": "none",
      "presentation": {
        "reveal": "silent",
        "panel": "new",
        "close": true
      },
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
  ]
}
```
