### ISSUE TITLE
Indicate current usage period in usage view, and show text when empty 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12803]
The screenshot below shows usage after clicking on `August` to show usage for August.

- the currently selected period (August) should have a grey background
- the main list area should say `No billed usage for this period.`

<img width="1103" alt="Screenshot 2022-09-09 at 09 20 16" src="https://user-images.githubusercontent.com/849592/189305920-c2d3f0f1-b0c6-47d9-959b-d844ba07688e.png">

**Comment by svenefftinge** [comment]
I opted for adding information about the displayed range, as we should go away from the fixed calendar month views anyway. FWIW I like the usage view in vercel

<img width="1261" alt="Screenshot 2022-09-12 at 12 43 26" src="https://user-images.githubusercontent.com/372735/189634594-3df85916-2016-4648-ac67-00528c1342a2.png">
