### ISSUE TITLE
[server] Create CostCenters for Individuals

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#12802]
Individuals that have not subscribed to UBP (put in credit card with Stripe) should automatically get a CostCenter with `billingStrategy: 'other'`. and a `spendingLimit` that matches the amount of workspace hours they currently have in their billingMode. That is we crate such a cost center for every individual no matter they are freemium, prof OSS or have a paid plan with chargebee. 
Users should not be able to update their spendingLimit unless they have switched to a `'stripe'` `billingMode`.

**Comment by AlexTugarev** [comment]
Hi @svenefftinge!

> unless they have switched to a 'stripe' billingMode.
You mean the `stripe` billing strategy here, right?

> and a spendingLimit that matches the amount of workspace hours they currently have in their billingMode.

Could you point where to find this? 
https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/src/billing-mode.ts

**Comment by svenefftinge** [comment]
> > unless they have switched to a 'stripe' billingMode.
> 
> You mean the `stripe` billing strategy here, right?

Yes
 
> > and a spendingLimit that matches the amount of workspace hours they currently have in their billingMode.
> 
> Could you point where to find this? https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/src/billing-mode.ts

Sorry, it's not in their billingmode but in their subscriptions.

**Comment by geropl** [comment]
Close like this is not necessary atm.
