### ISSUE TITLE
Stop. Opening. Previews.

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1280]
### Describe the bug
It seems like recently, a Gitpod update came out.
It now opens previews even if set to open the browser in the config.
This may be a bug, or a feature, but either way I am fed up with it.

PLEASE, make it STOP.  THIS is a BIG PAIN.

**Comment by jankeromnes** [comment]
Hi @RDIL, thanks for reporting this annoying-sounding issue.

Could you please provide a repository URL where this error can be reproduced?

Also, please note that `onOpen: open-browser` can lead to some problems, e.g. because many browsers prevent websites from opening "pop-ups" by default (because they're usually unwanted ads). We try to detect such blocks in Gitpod, and open a notification instead, that asks you if you want to open a Preview or a Browser tab (and when you click on Browser tab, it's no longer blocked, because the user-click tells the browser that the user actually wants to open the "pop-up" / new tab).

**Comment by RDIL** [comment]
You can reproduce on https://d179dbc7-889d-44da-914f-c4ba814e77c6.ws-us02.gitpod.io - its a private repo so I'm going to stop sharing in 10 minutes

**Comment by JesterOrNot** [comment]
I was unable to reproduce this :(
![image](https://user-images.githubusercontent.com/50386709/75693523-a56f9c80-5c6c-11ea-8e27-21d3619f020f.png)

**Comment by RDIL** [comment]
It only happens on first start

**Comment by jankeromnes** [comment]
Please provide a repository URL where this issue can be reproduced, or a screencast.

**Comment by RDIL** [comment]
https://github.com/rdil/eduaid - I'll give you collaborator so you can open it since its private

**Comment by Kreyren** [comment]
This may be irelevant, but while i was working on gitpod/website where i've notice it opening a preview on page build which i also find pretty annoying.

confirm relevance and i will provide steps to reproduce

**Comment by jankeromnes** [comment]
> This may be irelevant, but while i was working on gitpod/website where i've notice it opening a preview on page build which i also find pretty annoying.

This is because of this `.gitpod.yml` configuration:

https://github.com/gitpod-io/website/blob/d4369f5db174999d3737a7245417729bb36d6d79/.gitpod.yml#L2-L3

I.e., whenever something becomes active on port 8000, Gitpod automatically opens a preview for that port.

**Comment by svenefftinge** [comment]
Do you use `create react app`? It does open the website in a browser on start and we are now supporting such calls. I.e. it behaves as it would do locally (open a browser tab).
You can disable that with a command line flag.

**Comment by jankeromnes** [comment]
Bug confirmed in Gitpod production in Firefox on Mac OS:

- `.gitpod.yml` says `onOpen: open-browser`:

<img width="273" alt="Screenshot 2020-03-02 at 17 38 13" src="https://user-images.githubusercontent.com/599268/75696949-a9bbaa00-5cac-11ea-8be7-051e943c6b75.png">

- when the port becomes active, port 8000 is opened in both a (blocked) pop-up and a preview panel:

<img width="600" alt="Screenshot 2020-03-02 at 17 37 24" src="https://user-images.githubusercontent.com/599268/75696859-85f86400-5cac-11ea-9a7d-e5d847535c82.png">

**Comment by jankeromnes** [comment]
> Do you use `create react app`? It does open the website in a browser on start and we are now supporting such calls. I.e. it behaves as it would do locally (open a browser tab).
You can disable that with a command line flag.

Ah, that should be it.

@RDIL If you start your server with `BROWSER=none yarn start`, the preview no longer opens.

I think you can also configure `BROWSER` on a project- or user-wide basis in https://gitpod.io/environment-variables/

**Comment by RDIL** [comment]
Ahh okay, thanks @jankeromnes!

p.s. thanks a ton for blurring the content ❤️
