### ISSUE TITLE
CI(featureReg): Trigger only if gitpod relevant pathname has been edited

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1281]
### Description
It seems that it's not possible to get Gitpod bot to trigger a prebuilt depending on files changes

### Expectation
Expecting gitpod to trigger prebuild **only if** commit or merge request changes `.gitpod.yml` file or `gitpod` directory.

### Reasoning
Less noise in the CI

**Comment by svenefftinge** [comment]
Why is that? The prebuild usually builds your project, so most files in a repo are considered input.

**Comment by Kreyren** [comment]
> Why is that?

Optimization so that we woudn't have to wait for gitpod to process the request when it's not needed.

> The prebuild usually builds your project, so most files in a repo are considered input.

I'm triggering the prebuild manually depending on when it is needed since gitpod likes to build even when the end result is the same at previous (uneccesary waste of system resources and delay in deploy)
