### ISSUE TITLE
Workspace team changes to support HTTP_PROXY

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#12825]
This is the known list of issues. This may be added to until the parent ticket is closed.

- [x] #12829
- [x] #12832

Related PR where foundational work was done: https://github.com/gitpod-io/gitpod/pull/12726

**Comment by kylos101** [comment]
Thanks, @MrSimonEmms ! I've added both issues to our inbox, but removed this parent from the inbox (as its more of a tracking issue).

As you add new children to this, please add them to our inbox? 

PS: I like this flow, it will make it easier to chunk out the work, I really appreciate the breakdown.

**Comment by MrSimonEmms** [comment]
Thanks @kylos101. My expectation is that there may be WebApp and IDE team work for this feature in future, so it made sense to separate the tasks into individual teams.

Will add anything new to the inbox as requested
