### ISSUE TITLE
allow for injection of envvars into imagebuild/workspace templates from the Installer

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#12829]
As part of the Installer work to introduce support for HTTP_PROXY, we have created a `ProxyEnv` function that injects the six envvars from a customisable secret - see [code](https://github.com/gitpod-io/gitpod/blob/ef3867df9948b3815b6f3634ddce6cef05d2e056/install/installer/pkg/common/common.go#L71,L89).

Both the imagebuild and workspace templates require these six envvars in the [workspace](https://github.com/gitpod-io/gitpod/blob/05141becb5f677263f8ad4553c88076f19db2a4c/components/ws-manager/pkg/manager/create.go#L771-L787).

It would be a useful feature if we could add envvars into the [workspace template configmap](https://github.com/gitpod-io/gitpod/blob/ef3867df9948b3815b6f3634ddce6cef05d2e056/install/installer/pkg/components/ws-manager/configmap.go#L160,L239). This would allow for the envvars to be injected into the workspace so that the actual configuration can be driven by the Installer without having to repeat the functionality in multiple parts of the codebase.

**Comment by kylos101** [comment]
@MrSimonEmms  it seems like we're much closer than I realized to having a feedback loop that support the proxy use case!

1. :heavy_check_mark:  [a self-hosted environment built with kots](https://github.com/gitpod-io/gitpod/pull/12229), this is :rocket: awesome!
2. :white_check_mark: [kots proxy support](https://github.com/gitpod-io/gitpod/pull/12726) in the Gitpod product. :pray: thank you so much!
3. :question:  the werft job introduced in #12229 be updated to support proxy use cases (where all egress must go through the proxy server)

After which, I think we'd be in a position to iterate quite nicely. @MrSimonEmms and @corneliusludmann , can you share an ETA for when the werft job may support the proxy use case, and an alternative set of instructions we can use for the interim? Having either will make it possible for us to Schedule this work for Team Workspace.

**Comment by mrzarquon** [comment]
We can't assume the proxies used for services are the same proxies users want in their workspaces. Either for security or tracking purposes users may have to configure different proxies for a 'live' workspace vs proxies used for gitpod's purposes.
