### ISSUE TITLE
Receive error code 502 when pushing images to container registry through a proxy

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#12832]
During the investigations of #10769, I made a simple version of #12829 by hardcoding all the envvars into an image. This gave a series of 502 errors when pushing images to my container registry.

Once the work for #12829 has been done, this will be the next thing to do.

**[NB](https://www.britannica.com/dictionary/NB)** this ticket is more an _[aide-mémoire](https://www.merriam-webster.com/dictionary/aide-m%C3%A9moire)_ that a problem potentially exists rather than an expectation of some work to be done

**Comment by kylos101** [comment]
@MrSimonEmms does this issue rename align with the problem you were experiencing?

**Comment by MrSimonEmms** [comment]
Sure. It's perfectly plausible that this issue goes away when #12829 is done, so this issue shouldn't be worked on until that other issue is done
