### ISSUE TITLE
use-case of `ws-manager-client-tls` certificate

### ISSUE THREAD

**Issue by Pothulapati** [gitpod-io/gitpod#12838]
Part of #12836 

While the use-case of other certificates i.e `docker-registry` are clear i.e them being the server side certificates of components, That does not seem to be the case with `ws-manager` as they seem to have two certificates i.e `ws-manager-tls` and `ws-manager-client-tls`.

[`ws-manager-client-tls` namely](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/ws-manager/tlssecret.go#L66) is being loaded into various components that interact with `ws-manager` i.e `ws-proxy`, `registry-facade`, etc but not sure about the exact use-case here. It feels like `mTLS` but without it not being loaded into `ws-manager` itself, I’m not sure how that would be possible.

The history of it’s presence seems to go back all the way to the [Gitpod helm chart cleanup](https://github.com/aledbf/gitpod-chart-cleanup/blob/main/charts/gitpod/templates/ws-manager-tlssecret.yaml)

I've tried a branch where I removed it, and things still seemed to have worked. My plan is that if to remove it if it's not useful anymore, or atleast re-name,add comments if its needed.

So, It would be nice to have the following information:
- Is `ws-manager-client-tls` still in use or is it a left-over?
- If it is still needed, can you provide me with a paragraph explaining its use that I can add to the documentation?

**Comment by kylos101** [comment]
Added to groundwork, thanks for laying out the questions so nicely, @Pothulapati !

**Comment by kylos101** [comment]
@corneliusludmann @Pothulapati I need to create some bandwidth in our groundwork, and am moving this back to our inbox. Please let me know if there is a time constraint or customer who is waiting for this research.
