### ISSUE TITLE
Pull Request CI in Gitpod

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1284]
Add CI checks like this
![image](https://user-images.githubusercontent.com/50386709/75782784-14a8c780-5d25-11ea-9b86-21a23403b3be.png)
Here
![image](https://user-images.githubusercontent.com/50386709/75782807-212d2000-5d25-11ea-940e-ec1db038f1ba.png)

**Comment by jankeromnes** [comment]
I think that's an excellent idea! Many thanks.

I see this being really helpful e.g. for preview URLs in CI checks (that way you can open the PR preview from Gitpod instead of having to jump back to the PR tab first).
