### ISSUE TITLE
Bitbucket pullrequest scopes incorrectly not implying repository scopes

### ISSUE THREAD

**Issue by sbhrule15** [gitpod-io/gitpod#12853]
### Bug description

When providing an OAuth consumer for Bitbucket cloud, and choosing the `pullrequest:write` scope, GitPod does not imply the proper repository scopes in the UI or in the web IDE. Currently the only issue I've noticed is frequent popups in the IDEs saying they do not have the proper scope. Per Bitbucket on the pullrequest:write scope:

> Implies pullrequest but adds the ability to create, merge, and decline pull requests. This scope implies repository:write, giving write access to the pull request's destination repository. This is necessary to facilitate merging.

Here is BitBucket's documentation on this scope inference: https://developer.atlassian.com/cloud/bitbucket/bitbucket-cloud-rest-api-scopes/#pullrequest-write

### Steps to reproduce

Link a Bitbucket provider via Bitbucket cloud, and select the proper permissions required by GitPod (notice how the repository read and write scopes are auto-selected: 
<img width="683" alt="image" src="https://user-images.githubusercontent.com/65102852/189539000-ef78c45d-02c5-40c6-bf80-0f42243bc0ae.png">

Open a GitPod Workspace, or go to the permissions and scopes area, and notice that repository and repository:write are not selected:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/65102852/189539152-38e12485-1842-496b-bd3e-f892528f720f.png">
<img width="656" alt="image" src="https://user-images.githubusercontent.com/65102852/189539373-ebbc3f57-1d13-4cb1-8e57-0501d7a276d5.png">

### Expected behavior

Pull Request Write scope privileges imply repository read and write scopes, and should be reflected as such in the scope checking.

**Comment by jldec** [comment]
@sbhrule15 can you confirm that you are configuring bitbucket.org from a self-hosted instance of Gitpod and let us know the version? 

Users connecting their accounts to bitbucket.org from gitpod.io (using the Gitpod-managed OAuth, not user-managed) see the full-set of OAuth scopes in their integration.

<img width="1111" alt="Screenshot 2022-10-11 at 10 48 24" src="https://user-images.githubusercontent.com/849592/195044656-395993c4-2e08-497b-a015-778ba191d99a.png">

**Comment by sbhrule15** [comment]
@jldec  That is correct - this is connected to Bitbucket Cloud, with a self-hosted of version of GitPod, running version 2022.8.0. 

<img width="252" alt="image" src="https://user-images.githubusercontent.com/65102852/195737177-f804f39e-e474-4a39-adbc-bb7d62f99cfe.png">

**Comment by jldec** [comment]
There appears to be a discrepency between how self-hosted and gitpod.io do BBS registrations.
