### ISSUE TITLE
Error: cannot create build volume

### ISSUE THREAD

**Issue by alanassis** [gitpod-io/gitpod#1288]
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: Error response from daemon: create build-0e2e5dfcf45ef4aec3c4b58b3b7795a43e5ac6f387f725f86d045fca493915de-1583316365: error while creating volume path '/var/lib/docker/165536.165536/volumes/build-0e2e5dfcf45ef4aec3c4b58b3b7795a43e5ac6f387f725f86d045fca493915de-1583316365/_data': mkdir /var/lib/docker/165536.165536/volumes/build-0e2e5dfcf45ef4aec3c4b58b3b7795a43e5ac6f387f725f86d045fca493915de-1583316365: no space left on device
Please file an issue if you think this is a bug.

### Steps to reproduce
Occurs after setting up my repository's gitpod

https://github.com/alanassis/tarefull-tarefas-organizadas/tree/alanassis/gitpod-setup

**Comment by alanassis** [comment]
I got this message too: "cannot initialize workspace: cannot initialize workspace: cannot create workspace: mkdir /mnt/workingarea/a44152f1-261c-4c86-ad04-453724b04ca5: no space left on device
Please file an issue if you think this is a bug."

**Comment by meysholdt** [comment]
> no space left on device

This issue has been resolved few minuted after it happened 9h ago.
