### ISSUE TITLE
Ensure invoice does not go above Usage Limit

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#12881]
We want to ensure that the number of credits on an invoice is at most the value of the spending limit. This is to provide users with a guarantee that they will not be charged for more than their spending limit.

To achieve this, we will need to do the following:
* When updating a spending limit, prevent setting it below any existing accrued usage. The spending limit can be increased, but it cannot be decreased below the current usage.
* When updating invoices, retrieve the spending limit for each Attribution ID and take the `min(usage, spending_limit)

See related (internal) [conversation](https://gitpod.slack.com/archives/C02EN94AEPL/p1662984984475409).

**Comment by laushinka** [comment]
> * When updating a spending limit, prevent setting it below any existing accrued usage. The spending limit can be increased, but it cannot be decreased below the current usage.

Do we need a design for how we show this message to the user? cc @jldec @gtsiolis

**Comment by laushinka** [comment]
Unassigning based on [this](https://gitpod.slack.com/archives/C02EN94AEPL/p1663066260300139?thread_ts=1662984984.475409&cid=C02EN94AEPL) internal discussion.
