### ISSUE TITLE
Docs + Changelog for JetBrains common actions

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#12884]
Documentation + Changelog item for the following PR: 

- https://github.com/gitpod-io/gitpod/issues/8024

**Comment by loujaybee** [comment]
Also assigning @andreafalzetti as he said he might have some time, if not I will pick this up!

**Comment by andreafalzetti** [comment]
Is this issue to update both website docs and changelog? 

Re: website docs, are we blocked by the docs restructure?

cc @loujaybee

**Comment by andreafalzetti** [comment]
Removing myself from assignees due to lack of time

**Comment by andreafalzetti** [comment]
@loujaybee shall we close this? anything missing?

**Comment by loujaybee** [comment]
Thanks @andreafalzetti ! Yep, [documentation in changelog here](https://www.gitpod.io/changelog/september-gitpod-release-2022#jetbrains-backend-control-center---gitpod-workspace-actions).
