### ISSUE TITLE
Workspace not found

### ISSUE THREAD

**Issue by JokerTheBond** [gitpod-io/gitpod#12915]
### Bug description

When I open my usual workspace I get the error:

"Oh, no! Something went wrong!
Workspace not found!"

### Steps to reproduce

/

### Workspace affected

coffee-gorilla-uf186pcy

### Expected behavior

/

### Example repository

/

### Anything else?

I have received no warning that the workspace was going to be deleted. Now it seems disappeared, I can't see it anymore in my dashboard.
I truly hope this is a temporary issue otherwise I would have lost all uncommitted changes in the workspace...

**Comment by axonasif** [comment]
Hey @JokerTheBond, we have an ongoing [incident](https://www.gitpodstatus.com/incidents/v9pdpmcbgz6g), maybe it's an instance of that. I'm adding your issue to our workspace team inbox to take a look. Thanks for your patience 🙏

**Comment by JokerTheBond** [comment]
> Hey @JokerTheBond, we have an ongoing [incident](https://www.gitpodstatus.com/incidents/v9pdpmcbgz6g), maybe it's an instance of that. I'm adding your issue to our workspace team inbox to take a look. Thanks for your patience 🙏

Thanks for the help. https://www.gitpodstatus.com/ is now saying that today's incident was solved however I still get the same error "Workspace not found"

**Comment by axonasif** [comment]
@JokerTheBond in that case I would recommend to raise a ticket via https://www.gitpod.io/contact/support
