### ISSUE TITLE
Syntax highlighting goes "white"

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#1291]
Hi! The past few days we've noticed a lot of the code goes "white" after a few minutes. The only way to bring back the expected syntax highlighting is by restarting the workspace. Any idea why this might be happening? Thank you in advance :)

**Comment by JesterOrNot** [comment]
Hello @ColbyWTaylor can you explain the issue and perhaps send some screenshots or a screencast?

**Comment by ColbyWTaylor** [comment]
![image](https://user-images.githubusercontent.com/16373392/75925906-87a26300-5e37-11ea-9fe5-54acbe0f1719.png)

**Comment by ColbyWTaylor** [comment]
In the past it has occurred when a session closes so I just refresh, might be something to do with dependencies not getting called if there's a break in the connection?

**Comment by JesterOrNot** [comment]
CC @akosyakov

**Comment by jankeromnes** [comment]
Just happened to me as well, after returning to a tab that I had left open:

<img width="587" alt="Screenshot 2020-03-05 at 12 10 41" src="https://user-images.githubusercontent.com/599268/75976261-5d55b180-5eda-11ea-9b83-dfd9f5c099f4.png">

The devtools browser console has this error:

```
Error: no adapter found
    at LanguagesExtImpl.withAdapter (/theia/node_modules/@theia/plugin-ext/lib/plugin/languages.js:146:35)
    at LanguagesExtImpl.$provideCodeActions (/theia/node_modules/@theia/plugin-ext/lib/plugin/languages.js:340:21)
    at RPCProtocolImpl.doInvokeHandler (/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:268:23)
    at RPCProtocolImpl.invokeHandler (/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:253:41)
    at RPCProtocolImpl.receiveRequest (/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:217:31)
    at RPCProtocolImpl.receiveOneMessage (/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:186:22)
    at /theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:78:109
    at /theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:293:17
    at /theia/node_modules/@theia/core/lib/common/event.js:160:33
    at CallbackList.invoke (/theia/node_modules/@theia/core/lib/common/event.js:175:39)
```

**Comment by jankeromnes** [comment]
Oh, and all the language support features are gone. I guess that the TypeScript language server died for some reason?

<img width="250" alt="Screenshot 2020-03-05 at 12 16 17" src="https://user-images.githubusercontent.com/599268/75976679-2fbd3800-5edb-11ea-89af-a6d6f5364e38.png">

**Comment by jankeromnes** [comment]
Note: Simply refreshing the tab works around the problem (it successfully restarts the TS language server after a brief hang).

**Comment by ColbyWTaylor** [comment]
Yes the refresh has been well used with this issue! For diagnosing, I get it while typing sometimes- so maybe related to tabbing or something deeper that tabbing triggers?

**Comment by corneliusludmann** [comment]
Does `F1` → `>TypeScript: Restart TS server` helps as well?

**Comment by svenefftinge** [comment]
> Does F1 → >TypeScript: Restart TS server helps as well?

I've seen that, too, now. For some reason all extensions are unloaded, so that command from TS doesn't exist anymore.

**Comment by svenefftinge** [comment]
should be fixed now.
