### ISSUE TITLE
Refreshing issue

### ISSUE THREAD

**Issue by Naqij** [gitpod-io/gitpod#12927]
### Bug description

Live preview of the website is not working.
when I open repository and type python3 -m http.server it opens like normal but if I make changes to the code and refresh the live preview it just keep loading and doesn't do anything. 
I did "control + shift + r" as well but nothing happens.

### Steps to reproduce

Refresh the live preview and it gets stuck loading.

### Expected behavior

should updated changes when refreshed

### Example repository

https://github.com/Naqij/quiz-game

**Comment by axonasif** [comment]
Hey @Naqij, could you check your console logs?

Which browser are you using?

You can try opening the preview-window in a separate browser tab.
