### ISSUE TITLE
bug: Wrong linting on github actions

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1293]
![image](https://user-images.githubusercontent.com/11302521/75923401-49239d00-5e65-11ea-83ef-c2a36cd19f9a.png)

This syntax is valid, see https://github.com/Kreyren/dockerfreeze/pull/1/checks?check_run_id=486049924

### Expected
Expecting theia to provide correct linting

### Additional info
Snapshot
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/6b5246d9-746f-4ca9-af79-2539443b833f)

**Comment by svenefftinge** [comment]
We are pulling JSON schema from http://schemastore.org/json/.
So it seems like http://json.schemastore.org/github-action is wrong?

**Comment by svenefftinge** [comment]
Seems like it is outdated. There are other issues along this line: https://github.com/SchemaStore/schemastore/issues/928

**Comment by Kreyren** [comment]
@svenefftinge https://github.com/SchemaStore/schemastore/issues/928 seems like different issue
