### ISSUE TITLE
Workspace stuck at "stopping" state

### ISSUE THREAD

**Issue by whenzei** [gitpod-io/gitpod#12939]
### Bug description

Unable to start the workspace as it is stuck at the "stopping" state

### Steps to reproduce

https://gitpodio-templaterustcl-7o718qd8cqo.ws-us64.gitpod.io/

**Comment by geropl** [comment]
Thank you for reporting @whenzei ! :pray:  Your workspace has been stopped by now.

I'm closing this issue because:
 - we're already working on a fix here: #12902 
 - it's a duplicated entry of #12938
