### ISSUE TITLE
Compatibility for luna-lang?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1295]
Referencing https://luna-lang.org/ which is graphical programming language written in haskel with IDE written in rustlang

See demonstration https://youtu.be/RWzsDPZjOoo?t=83

Is there a way to implement this to work in gitpod? I am considering using this for a package manager downstream.

Or is there any alternative that gitpod is able to support that would allow contributors to use GUI to script the package manager downstream?

**Comment by JesterOrNot** [comment]
I'll see if I can get an example repo setup!

**Comment by Kreyren** [comment]
Apparently luna developers are preparing for 2.0 release which should provide web-view editor.. Could we support alternative to theia on gitpod?

**Comment by JesterOrNot** [comment]
Sure!

**Comment by Kreyren** [comment]
Referencing ENSO which is the mensioned editor

https://github.com/luna/enso

**Comment by Kreyren** [comment]
Seems to work using the lasted commit that passed the CI https://github.com/luna/ide/tree/6614e2ab1e9d67b2b56a97d49d4aa30eed4e8122

**Comment by wdanilo** [comment]
@Kreyren thanks for mentioning us! I'm from the Luna team. Just FYI, currently, CI does not pass as a dependency of a binary in Rust was broken this night and a lot of Rust packages/binaries stopped building: https://github.com/rust-lang-nursery/failure/issues/342 . It should be fixed soon. And you are right, our new GUI can be found here https://github.com/luna/ide . However, it is not yet in really working stage – in few months (around end of May) we plan to release it to the public. It will be 100% WebGL based and as always, we'd love to help if you would like to use it! :)

**Comment by Kreyren** [comment]
@wdanilo thanks for info appreciated ^^

>  However, it is not yet in really working stage 

It seems to have the codebase to build in semi-working state, is there any commit that is capable of semi-functional runtime?

> we'd love to help if you would like to use it! :)

Could you provide more info for the functionality?

to provide context i'm working on a package manager on https://github.com/RXT0112/Zernit that is expected to have bunch of functions defined in libraries which are then expected to be scripted alike:

https://github.com/bobwya/bobwya/blob/master/app-emulation/wine-staging/wine-staging-5.3.ebuild

-- OR --

https://gitlab.exherbo.org/kreyren/exheredrey/tree/master/packages/app-compat/wine (.exlib is used as a per-package library to be sourced and .exheres-0 is the file used to provide the downstream)

If Luna/Enso can do this it efficiently then would be awesome ^-^

**Comment by wdanilo** [comment]
> It seems to have the codebase to build in semi-working state, is there any commit that is capable of semi-functional runtime?

Yes, the `master` branch should build fine and work. We keep `master` always in a working stage.

> Could you provide more info for the functionality?
Currently, in the GUI 2.0 you can run a lot of benchmarks of our WebGL renderer + some initial nodes view. During next weeks a full-blown node-editor should appear.

> If Luna/Enso can do this it efficiently then it would be awesome ^-^
What is the exact use case here? Do you want to visually define the pipeline of operations?

**Comment by Kreyren** [comment]
@wdanilo Let's move the Zernit usecase in it's separate issue so that this can be used for tracking of gitpod's compatibility for luna/enso.

See https://github.com/RXT0112/Zernit/issues/61
