### ISSUE TITLE
[terraform/aws] Install Calico after deleting the default CNI

### ISSUE THREAD

**Issue by nandajavarma** [gitpod-io/gitpod#12953]
This is a big step missing towards syncing the terraform module with the reference architecture. Follow the discussion here https://gitpod.slack.com/archives/C01KLC56NP7/p1663153953823739

**Comment by Pothulapati** [comment]
If folks haven't started working on this, I'm happy to take it up!

**Comment by Pothulapati** [comment]
If folks haven't started working on this, I'm happy to take it up!  @nandajavarma @adrienthebo

**Comment by nandajavarma** [comment]
Yup! I was not planning to pick this up before the quarter ends. Please go ahead!

**Comment by Pothulapati** [comment]
This seems to be related https://github.com/gitpod-io/gitpod/issues/12492
