### ISSUE TITLE
Project is considered inactive incorrectly

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#12952]
We found a case in which a project is considered inactive, which means prebuilds are not executed when push events are registered. Unfortunately, there were workspaces started for the very same context URL, which means the activity was not detected as expected. There is nothing in the UI what could help our users to identify the situation. 

Here are the relevant entries from the database:
```
from d_b_prebuilt_workspace

|id   |commit|creationTime                 |branch|error                                                                                     |projectId                           |

|1...d|f...a|2022-09-13 17:18:01.549572000|master|Project is inactive. Please start a new workspace for this project to re-enable prebuilds.|3...4|
|e...4|f...a|2022-09-13 17:18:01.544879000|master|Project is inactive. Please start a new workspace for this project to re-enable prebuilds.|3...4|
|1...8|4...4|2022-09-11 15:47:37.477726000|master|                                                                                          |3...4|
|7...d|4...4|2022-09-11 15:47:37.475648000|master|                                                                                          |3...4|
|6...7|8...7|2022-09-10 19:15:00.512667000|master|                                                                                          |3...4|

```

```
from d_b_project_usage

"projectId","lastWebhookReceived","lastWorkspaceStart","deleted","_lastModified"

"3..4","2022-09-13T23:59:36.148Z","2022-09-13T17:33:26.312Z",0,"2022-09-13 23:59:36.153359000"
```

Records from `d_b_workspace` show that there were workspaces created for that repo in recent days, thus prebuilds should have been started as expected.  

See the correction from [comment](https://github.com/gitpod-io/gitpod/issues/12952#issuecomment-1247608325).

```
from d_b_workspace

"type","creationTime","id","contextURL"

regular,"2022-09-14T08:18:37.589Z",d...m,https://github.com/d...d/d..v
regular,"2022-09-14T06:52:32.427Z",d...g,https://github.com/d...d/d..v
regular,"2022-09-14T06:48:41.790Z",d...5,https://github.com/d...d/d..v
regular,"2022-09-13T17:33:26.294Z",d...i,https://github.com/d...d/d..v
regular,"2022-09-13T12:28:02.516Z",d...0,https://github.com/d...d/d..v
regular,"2022-09-07T02:34:47.617Z",d...2,https://github.com/d...d/d..v
regular,"2022-09-07T02:32:05.963Z",d...v,https://github.com/d...d/d..v
regular,"2022-09-07T02:12:12.526Z",d...l,https://github.com/d...d/d..v
```

This seems to be the underlying issue for https://github.com/gitpod-io/gitpod/issues/9564

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3rsju)

**Comment by AlexTugarev** [comment]
A correction to the data queried initially. I've learned that only team members workspaces do count for the activity of projects. 'Going to follow this separately, but here are the recent workspace starts filtered for team members only.

```
 type   |creationTime            |id           |contextURL    
|regular|2022-09-13T17:33:26.294Z|d...wzajo5czi|https://github.com/d...d/d...v|
|regular|2022-09-06T14:36:23.709Z|d...dmc2kbnbc|https://github.com/d...d/d...v|
|regular|2022-08-19T21:08:48.815Z|d...en0f4b4nu|https://github.com/d...d/d...v|
```

**Comment by jankeromnes** [comment]
> A correction to the data queried initially. I've learned that only team members workspaces do count for the activity of projects. 'Going to follow this separately

@AlexTugarev Do we already have an issue for expanding the scope of "project is considered active" from "project owners have opened a workspace for this project" to "any Gitpod user has opened a workspace for this repository"? (Or, maybe something like "any Gitpod user has benefited from a prebuild for this repository"?)
