### ISSUE TITLE
[server] Add SLO for image-build completed successfully

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#12960]
We are currently lacking insight into how often image-builds are not completed successfully. Especially we suspect, that rollouts of `server` might lead to updates about image-builds are being lost.
To proof that, and to be able to hunt this down, we should introduce a metric + SLO.

- [ ] Create metric
- [ ] Create SLO

**Comment by easyCZ** [comment]
Just to clarify, the focus is on measuring from the perspective of the `server` listening for image build status, not from the perspective of `image-builder` building the image and completing OK?

If that's the case, then the problem we need to solve here can be expressed with the following metrics:
* Counter of image builds completed as observed by Server
* Counter of image build completed as observed by Image manager

The metric we want to measure is the diff between these.

As a bonus, I'd recommend also adding:
* Counter of image builds started as observed by Server
* Counter of image build started as observed by image manager

These allow us further debug if the request didn't actually reach image builder, or if we just lost the update.
