### ISSUE TITLE
I AM UNABLE TO LOG IN TO GITPOD

### ISSUE THREAD

**Issue by parzival0611** [gitpod-io/gitpod#1296]

**Comment by AlexTugarev** [comment]
@parzival0611, sorry to hear about that. I just checked the logs, and it looks like GitHub didn't recognize your token for the "read email" request. It was OK during the OAuth process though. 

Just in case, please try again. It might be a glitch with GitHub servers. In Gitpod we've a retry strategy in place for such cases.

**Comment by AlexTugarev** [comment]
@parzival0611 any news?
