### ISSUE TITLE
Usage-based pricing - validate that self-hosted Gitpod users are not impacted by UBP changes

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#12969]
Feature flags _should_ ensure that there is no impact of UBP on self-hosted Gitpod installations, but this needs to be validated.

- no unexpected UBP-related errors during install or at run-time
- no billing config or usage view for teams or individuals
- no workspace or prebuild errors related to usage limits

#### known issues
- [x] #13390
- [x] #13392
- [x] #13395

**Comment by geropl** [comment]
For ensuring exactly this we introduced the concept of `BillingMode`, with the possible values of `none`, `chargebee` and `usage-based`. And the relevant lines of code are [here](https://github.com/gitpod-io/gitpod/blob/2d2c70f62c4799fe1bf0dca0aa55d4c70bb09386/components/server/ee/src/billing/billing-mode.ts#L78-L82): if `enablePayment` is not set to `true` by the installer, the `BillingMode` for all users (and [teams](https://github.com/gitpod-io/gitpod/blob/2d2c70f62c4799fe1bf0dca0aa55d4c70bb09386/components/server/ee/src/billing/billing-mode.ts#L163-L167)) defaults to `none`.
This `BillingMode` influences three things:
 - it governs what users can see on the dashboard ([an improvement over the prior state](https://github.com/gitpod-io/gitpod/issues/10247#issuecomment-1245072064)!)
 - it governs what API users can use (e.g., being allowed to call `upgradeSubscription` or not)
 - it governs which implementation (strategy) of the [`EnttilementService`](https://github.com/gitpod-io/gitpod/blob/7f537e2537e69a2ff1cf728a2a4dd8cae5b48c94/components/server/src/billing/entitlement-service.ts#L32-L71) is used to figure out what a user is _entitled_ to do. Here's the implementation for `none` (should be named `license`, really. My fault :roll_eyes: ): [EntitlementServiceLicense](https://github.com/gitpod-io/gitpod/blob/7f537e2537e69a2ff1cf728a2a4dd8cae5b48c94/components/server/ee/src/billing/entitlement-service-license.ts#L22-L64)

That being said: we should still test, though. :upside_down_face:

**Comment by AlexTugarev** [comment]
> Request deleteTeam failed with message: Stripe is not properly configured

This error blocks from team deletion, if payment is not configured.

**Comment by lucasvaltl** [comment]
@geropl what is the ask here towards the self-hosted team? If this is about spinning up self-hosted environments to test this, you should be able to use the environments during next week's release week to test this :)

**Comment by geropl** [comment]
Issue: "Usage View" is visible in self-hosted but shows broken content. (context: https://gitpod.slack.com/archives/C01KLC56NP7/p1664288507520209 )

**Comment by jldec** [comment]
FYI - edited issue description to include 2 new issues as sub-tasks (fix usage view and team deletion)

**Comment by adrienthebo** [comment]
This item has been marked as completed in the 2022.09.0 release document ([internal notion](https://www.notion.so/gitpod/Self-Hosted-Release-2022-09-0-0534b6ba181b476cb1826e358a7149f9#2d065ca75cab4e14b61cfa4f7d129c62)), I believe this issue is done.
