### ISSUE TITLE
I am looking to be able to get back to the same state as of before even when a new workspace is opened

### ISSUE THREAD

**Issue by akshatnarayangupta** [gitpod-io/gitpod#12977]
## Is your feature request related to a problem? Please describe
I am looking fo a feature to clone/copy the contents of the snapshot, so that i can enable to users of my application to always be able to restore back to the same point from where they left.

## Describe the behaviour you'd like
I have a github repository, which when opened in gitpod authenticates the users and asks them perform some tasks , I want the users to get back to the same point even when they leave and come back. 
Currently while clicking on the link it creates a new workspace every time. Either snapshots can help, or some feature might help which will prohibit the new workspace creation and redirect them to the already existing workspace

## Describe alternatives you've considered
I tried taking snapshots through the script but i can't use it to restore the workspace last state.

**Comment by axonasif** [comment]
Hey @akshatnarayangupta, which are the things that needs to be persisted between workspaces? The authentication?

**Comment by akshatnarayangupta** [comment]
> Hey @akshatnarayangupta, which are the things that needs to be persisted between workspaces? The authentication?

Actually I we have an application where ask user for authentication, after authentication we allow them to edit few files(its some kind of task), they can complete it within any span of time, we sync their work from time to time and then mark them as passed or failed, but the issue we are facing is, when the user tries to again open the workspace wuing the gitpod.io/#github.repository they end up opening a new workspace and have to start the task from the beginning.

So we need a feature to help the users get back to the same state even after taking breaks(a day, a month or so on). Their workspace files needs to be restored automatically ie not possible using snapshots, we directly want them to be redirected to their previous workspace.

**Comment by axonasif** [comment]
@akshatnarayangupta ok, that helps to better understand!

> we sync their work from time to time and then mark them as passed or failed

Since you already sync things, so you can sync the value of `$GITPOD_INSTANCE_ID` and `$GITPOD_OWNER_ID` as well. These are environment variables.

> an application where ask user for authentication using terminal and scripts

Later in the beginning of your script, you can:
- Check if `$GITPOD_WORKSPACE_ID` is already there on your sync-server based on `$GITPOD_OWNER_ID`.
  - If it is, then compare the value of local env-variable `$GITPOD_WORKSPACE_ID` with your remote sync-server.
  - If they don't match, programmatically start that workspace and close the current one.

Here's some semi-pseudocode:
```bash
# Try to fetch $GITPOD_WORKSPACE_ID from your database which is assigned to $GITPOD_OWNER_ID
if ws_id="$(fetch "$GITPOD_OWNER_ID")"; then {
   # Compare the values to see if they don't match
   if test "$ws_id" != "$GITPOD_WORKSPACE_ID"; then {
      # Launch the old workspace
      gp preview "https://gitpod.io/#start/${ws_id}" --external;
      # Stop the current one
      sleep 20;
      gp stop;
   } fi
} fi
```

If your repo is opensource, I could take a look myself too 😉

**Comment by akshatnarayangupta** [comment]
hey @axonasif ,
Thanks for the help, but i am still facing some issue executing the above pseudocode, can you please help ---
the line  **if gp preview "https://gitpod.io/start/#${ws_id}" --external; then {** 
is giving the following error -

Unable to connect to VS Code server: Error in request.
Error: connect ECONNREFUSED 127.0.0.1:23000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 23000
}

Can you help me with this?

**Comment by axonasif** [comment]
@akshatnarayangupta I updated that line now, check again 👍

**Comment by akshatnarayangupta** [comment]
hey @axonasif 
Now this  gp ports await 23000 1>/dev/null && gp preview "https://gitpod.io/start/#${ws_id}" --external
is not working , it went inside if then but it didn't open a new webpage

**Comment by axonasif** [comment]
Can you share a screen recording of what's happening and how you're executing this script?

**Comment by akshatnarayangupta** [comment]
I just noticed the chrome is blocking the pop-up 👀

**Comment by akshatnarayangupta** [comment]
Hey @axonasif , sorry for disturbing again

THE FLOW STILL SEEMS TO BE A BIT OFF.....explaining

Is there some command to redirect automatically? Or if we are opening in new tab close the previous tab automatically and delete the workspace created and move to the new tab.

ie when the old workspace already exists, close the tab with the new workspace, delete the new workspace and move to the new tab which we opened using gp preview ie the already existing workspace.

I tried the following code, but all it does is delete the workspace files and clear the env, 

```
read -p "Do you wish to open the already existing workspace? Enter your choice y/n: " choice
      if [ "$choice" == "y" ] || [ "$choice" == "Y" ]; then {
         if gp ports await 23000 1>/dev/null && gp preview "https://gitpod.io/start/#${workspace_url}" --external; then {
            sleep 10;
            rm -rf * && rm -rf .* && gp env -u
            #  kill -9 $$ && pkill -f "gitpod" && exit 0   <----this line is commented since it stops the running script, but we want to close and delete the workspace
            gp stop
            } fi
            }fi
```

Do you have any better solution for **deleting the new workspace created->closing the tab->moving to the new tab** all automatically through the script?

**Comment by akshatnarayangupta** [comment]
And one more thing is **customized** pop-ups allowed?

Maybe we can give popup to choose if they want to open a already existing workspace.

**Comment by axonasif** [comment]
@akshatnarayangupta why do you need to confirm since you want to make it mandetory anyway?
And there is no need to delete the files in your workspace since you're stopping it with `gp stop`.

Try doing it this way, it will also block ctrl+c:
```bash
trap 'gp stop' EXIT SIGINT
if gp ports await 23000 1>/dev/null && gp preview "https://gitpod.io/start/#${workspace_url}" --external; then {
   gp stop
} fi
```

**Comment by akshatnarayangupta** [comment]
@axonasif Since we just closed the workspace using gp stop, but later if the user ends up creating many inactive workspaces, it will cause a minor confusion.

**Comment by axonasif** [comment]
If you wish to do so: `sudo rm -rm "$GITPOD_REPO_ROOT";`

**Comment by AkshatNGupta** [comment]
Hey @axonasif , I read somewhere that in active workspaces are deleted after 14 days. If that's so, We are building our application so that the users can come in and attend the program as they wish and resume back as they wish. Like hackerearth/hackerrank. If the inactive workspaces are deleted, our purpose will be defeated for such cases. 

For workspaces to not be deleted we have to pin them manually. Is there some other way through which we can automatically do this through script/prohibit the gitpod to delete this workspace?

**Comment by axonasif** [comment]
Hey @AkshatNGupta 

> Is there some other way through which we can automatically do this through script/prohibit the gitpod to delete this workspace?

As of today, no.

I would encourage you to raise a feature request to add a subcommand on the `gp` CLI for pinning workspaces.

You could also do it via our API but it's not here yet: https://github.com/gitpod-io/gitpod/issues/10798

**Comment by axonasif** [comment]
@AkshatNGupta you might be interested in checking out how 4geeks integrate with gitpod for their educational platform: https://www.gitpod.io/for/education/4geeks
