### ISSUE TITLE
Impossible to add some GitLab repositories as a Project when you're a maintainer of more than 100 repositories

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#12970]
### Bug description

When you want to add a repository as a new Project in Gitpod, Gitpod first gets the list of all the possible repositories you could add (grouped by account), and then lets you find the repository you want to add via scrolling or searching/filtering.

Unfortunately, in the case of GitLab, we only fetch the first 100 repositories that you could add:

https://github.com/gitpod-io/gitpod/blob/1d52870bfe3dbb675ae0028c2e1d7a441d2a1489/components/server/ee/src/gitlab/gitlab-app-support.ts#L54

This is a problem, because if you want to add a specific repository that is not present in the first 100 repositories returned by GitLab, you will never be able to see it or find it in the Gitpod UI -- thus adding it as a project is totally impossible.

### Steps to reproduce

1. Be a maintainer of more than 100 GitLab repositories
2. Try to create a new project for a repository that is not listed in the first 100 results returned by GitLab

### Expected behavior

- You should always be able to create a new project for a GitLab repository that you're a maintainer of (even if it's not in the first 100 results from GitLab)

### Anything else?

Possible solutions:
- Paginate the GitLab API call in order to fetch more than just the first 100 repositories
- Allow creating projects by manually entering a repository URL

**Comment by gtsiolis** [comment]
Cross-posting in case it helps, there’s support for [offset-based pagination](https://docs.gitlab.com/ee/api/index.html#offset-based-pagination) which we could use to increase the page size here. But maybe this is not available through the API? 🤷 

For example:

```
https://gitlab.com/api/v4/projects?min_access_level=40
https://gitlab.com/api/v4/projects?min_access_level=40&per_page=2000
```

See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1663172660241819?thread_ts=1663140993.635109&cid=C02EN94AEPL) (internal).

**Comment by jankeromnes** [comment]
There is actually one workaround: Using the browser console to create a Project manually.

Say I want to add my repository https://gitlab.com/jankeromnes/test-before as a Project to one of my Teams, but for some reason, Gitpod's UI won't show it to me. Then, I can still do this:

1. Run `await window._gp.gitpodService.server.getTeams()` in order to find the team ID under which I want to create the Project
2. Then, run the following (just replace the `name`, `slug`, `cloneUrl` and `teamId` -- `appInstallationId` is useless but the API requires it):

```js
await window._gp.gitpodService.server.createProject({
    name: "test-before",
    slug: "test-before",
    cloneUrl: "https://gitlab.com/jankeromnes/test-before.git",
    teamId: "5db3013f-31d1-4d8e-9445-0a746b43edde",
    appInstallationId: "",
})
```

**Comment by jankeromnes** [comment]
@gtsiolis Good catch!

> ```
> https://gitlab.com/api/v4/projects?min_access_level=40&per_page=2000
> ```

Unfortunately, this isn't quite as simple, because the maximum allowed page length is 100:

<img width="823" alt="Screenshot 2022-09-14 at 18 35 39" src="https://user-images.githubusercontent.com/599268/190212442-bb85d572-f9ed-4448-9ece-6b6825887d49.png">

The proper solution to get all results would be to implement API pagination, i.e.:

1. Query the first 100 results (i.e. page 1)
2. If the response provides a hint that there is a next page (typically via a response header), we do step 1. again but for the next page (e.g. 2, 3, 4... until there is no next page anymore)

**Comment by jankeromnes** [comment]
Apparently, Gitbeaker (the library we use to fetch GitLab data) is already supposed to handle pagination and return all results: https://github.com/jdalrymple/gitbeaker#offset-pagination 🤔

But maybe that feature or the version of Gitbeaker we use has a bug with pagination? Or we're not using it properly? 🤷

**Comment by AlexTugarev** [comment]
@jankeromnes, are you planing to work on this? If not, I'd start working on it.

**Comment by AlexTugarev** [comment]
First step: bumping GL library in https://github.com/gitpod-io/gitpod/pull/13001
