### ISSUE TITLE
not allowing both gitlab and github

### ISSUE THREAD

**Issue by pprasha** [gitpod-io/gitpod#1297]

**Comment by Kreyren** [comment]
@pprasha can you elaborate on the issue?

**Comment by pprasha** [comment]
on Gitpod it doe snot let me connect both accounts

**Comment by svenefftinge** [comment]
If you go to https://gitpod.io/access-control/ you should see your auth status with both GitLab and GitHub. Please tell us what you tried and how your expectations were not fullfilled.

**Comment by AlexTugarev** [comment]
@pprasha we've deployed a fix to allow to connect both account. Though you didn't mention the error message, it's likely it was complaining about an already existing link with a different Gitpod account. This will be resolved now, which means that you will just keep your most recently used Gitpod account.

**Comment by AlexTugarev** [comment]
@pprasha please reopen if something left here 🙏
