### ISSUE TITLE
Workspace failed to start, instance appears to have gone from stopped to running

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#12983]
### Background

I'm debugging data consistency between ws-manager and ws-manager-bridge. There are instances where we receive an update for a workspace instance which moves from "stopped" into "running".

We already make use of the event GenerationID which allows us to skip events which are not the most recent. So from the "messaging" perspective, the reason for this update is not ordering of events.

[Internal Slack thread](https://gitpod.slack.com/archives/C02F19UUW6S/p1663139755463959)

### Bug description

Sometimes workspaces attempt to run, do not start, and never achieve running.

### Steps to reproduce

Identify occurrences with this [logs query](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22ws-manager-bridge%22%2529%0A%22Resetting%20already%20stopped%20workspace%20to%20running.%22;timeRange=2022-08-31T20:38:00.000Z%2F2022-09-13T12:00:00.000Z;summaryFields=jsonPayload%252Fpayload%252FinstanceId:false:32:beginning;cursorTimestamp=2022-09-09T15:43:43.533Z?authuser=0&project=gitpod-191109)

Example Instance ID where this happened: `7e3de43a-f831-4132-9ad1-69ce563ead72`

Run `loadgen` for 100 workspaces a few times

### Expected behavior

Workspaces should start.

### Anything else?

Here is a [related trace](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/trace/793b2cf6fa1173bb) demonstrating the problem in `gen73` which was observed while doing loadgen test as part of deployment. If you expand the logs in the trace with a value of 6, you'll see `failed before stopping and never ready`. Here are the related [logs](https://cloudlogging.app.goo.gl/9RYz3dfeBzBRcGBP9). 

@utam0k had a good observation...that when this happens we never enter CREATING phase.

-------

### Proposed Plan

1. Start by investigating why the CREATING phase is skipped.

**Comment by sagor999** [comment]
I looked on workspace cluster side for instances that have this error, and according to logs it is coming from pods\containers that got into some really weird\odd state.
They all seem to have failed to start(?): `cannot connect to daemon from ring0`
So it is very odd that somehow bridge got an update that container was running after being stopped.

Ideally I would love to investigate traces for this, but most recent instance of this was 3 days ago and those traces seem to be gone already from our cluster. :( 

I will take a look at this again and see if I can get traces to paint a better picture here.

**Comment by kylos101** [comment]
I am seeing this intermittently when load testing. [Logs.](https://cloudlogging.app.goo.gl/YQdqp3Pw3jnZ8N868)

I will update the issue and add to groundwork, because now we have a means for recreating (run loadgen for 100 workspaces a few times).

Also, [the issue exists in production](https://cloudlogging.app.goo.gl/UzgrF4kUeRnZ8t146) in on `us72` and in a new cluster we're prepping `us73`.

**Comment by kylos101** [comment]
Another example from loadgen: [Logs](https://cloudlogging.app.goo.gl/8PH8bV8qAjks4fwa8) for failed instance, and related [traces](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/search?end=1666820878841000&limit=20&lookback=1h&maxDuration&minDuration&service=ws-manager&start=1666817278841000&tags=%7B%22instanceId%22%3A%2259a652fb-cc4d-4d89-84e3-22cd8a6dc4ac%22%7D)

**Comment by kylos101** [comment]
Here another from `gen73` loadgen testing:
```
gitpod /workspace/gitpod (main) $ gpctl workspaces list | grep -v RUNNING
OWNER                                       WORKSPACE                             INSTANCE                                    PHASE               TYPE           POD                                            ACTIVE        NODE
c0f5dbf1-8d50-4d2a-8cd9-fe563fa53c71        black-aphid-sk1nlg59                  2bea46ff-50bb-4663-ad22-7e97295fce21        INITIALIZING        REGULAR        ws-2bea46ff-50bb-4663-ad22-7e97295fce21        false         workspace-ws-us73-pool-q1kw
gitpod /workspace/gitpod (main) $ gpctl workspaces list | grep -v RUNNING
OWNER                                       WORKSPACE                             INSTANCE                                    PHASE          TYPE           POD                                            ACTIVE        NODE
c0f5dbf1-8d50-4d2a-8cd9-fe563fa53c71        black-aphid-sk1nlg59                  2bea46ff-50bb-4663-ad22-7e97295fce21        STOPPED        REGULAR        ws-2bea46ff-50bb-4663-ad22-7e97295fce21        false         workspace-ws-us73-pool-q1kw
```

**Comment by kylos101** [comment]
Moving back to the inbox, to create bandwidth in our groundwork.

cc: @atduarte
