### ISSUE TITLE
How can I copy and paste in Gitpod? I have tried every way that I know but it's not working for me in Gitpod

### ISSUE THREAD

**Issue by oakerele-web** [gitpod-io/gitpod#1298]
How can I copy and paste in Gitpod? I have tried every way that I know but it's not working for me in Gitpod

**Comment by Kreyren** [comment]
CTRL+C and CTRL+V works for me.. You can also select using mouse and right click to open a menu with `Copy` and `Paste`

**Comment by oakerele-web** [comment]
Thanks @Kreyren CTRL+V works but I have tried the mouse right click to copy and paste but did not work. 
My other observation is that I have to type out my closing tags myself i.e. </p>, it does't come automatic. Do you have the idea of what I have done wrong or is it in the setting?

**Comment by oakerele-web** [comment]
Don't worry. I have discovered what to do. Thank you very much.

**Comment by Kreyren** [comment]
> @oakerele-web Don't worry. I have discovered what to do. 

Can you elaborate on the solution?

**Comment by oakerele-web** [comment]
Yeah, I discovered that all I have to do is type the letters without the tags and press tab button e.g. for <div> to come as <div></div>, all I need to do is type div and press the tab button. That is the answer to my second question that I said "I have discovered what to do"

**Comment by JesterOrNot** [comment]
Please See https://www.gitpod.io/docs/html-in-gitpod/ for closing tags in HTML! Let me know what you think of the guide if you get the chance
