### ISSUE TITLE
Diagraming in gitpod?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1299]
Referencing https://github.com/RXT0112/Zernit/issues/59 for requirement tracking

I am a have hard time finding a diagramming tool that plays well with gitpod.

Can you recommend me some so that i wouldn't have to make one from scratch? ^-^

**Comment by jankeromnes** [comment]
@Kreyren I know that several projects are using Sprotty to generate diagrams in Gitpod.

Also, I remember a JS implementation of Dot, and there is also https://github.com/tpatel/OpenSequenceDiagrams.js/ for sequence diagrams. There are probably more diagramming libraries that could work well in Gitpod. :) (Actually even Dot itself now that I think of it.)

**Comment by Kreyren** [comment]
@jankeromnes Sprotty is perfect! Thanks!! ^-^

In theory i can also use it to generate a dependency graph for packages o.o

Is there any configuration for sprotty to run in gitpod? (So that i can develop the diagrams on it)

**Comment by Kreyren** [comment]
solved

**Comment by jankeromnes** [comment]
> Is there any configuration for sprotty to run in gitpod? (So that i can develop the diagrams on it)

@Kreyren It seems that the Sprotty repo is itself configured for Gitpod: https://github.com/eclipse/sprotty

Not sure if that answers your question though. If not, could you please clarify?

Also, happy diagram-making! 📊 🥳

**Comment by Kreyren** [comment]
> @Kreyren It seems that the Sprotty repo is itself configured for Gitpod: https://github.com/eclipse/sprotty

yep i was blind and missed it :smile:

**Comment by Kreyren** [comment]
Reopening, it turned out that i am incompetent https://github.com/eclipse/sprotty/issues/166 or sprotty configuration for theia is outdated and i do not know how to update it >.>
