### ISSUE TITLE
Provide service status feedback

### ISSUE THREAD

**Issue by 32leaves** [gitpod-io/gitpod#130]
At the moment we have no means of telling our users when our service is degraded or broken, what we're doing about it, and when it's going to be back to normal again. We need a status page akin to https://status.github.com or https://status.cloud.google.com. 

Additionally, we should be able to bring this information to our users by showing it to affected users where appropriate (e.g. in the dashboard or during workspace startup).

**Comment by meysholdt** [comment]
potential status values:
* "gitpod works" per region as determined by semantic heartbeat
* "GitHub API works"?

**Comment by 32leaves** [comment]
Amongst others [Statusfy](https://statusfy.co/) seems to be a good candidate.

**Comment by jankeromnes** [comment]
I'm not sure if it's any better than implementing our own, but there are also status page services out there, e.g. I think www.statuspage.io is a popular option.

**Comment by 32leaves** [comment]
I am happy to announce that we now have a status page up and running at https://status.gitpod.io/.
We'll put links in place in appropriate places.
