### ISSUE TITLE
Remove d_b_billed_session and corresponding usage

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#13009]
We've introduced the `d_b_billed_session` to track usage between Stripe and Chargebee, but we're not planning to use it goign forward. We can clean up.

Clean up the following:
- [ ] Calls into `BillingService.SetBilledSessions`
- [ ] Remove API `BillingService.SetBilledSessions`
- [ ] Once we confirm no usage, remove the table

**Comment by laushinka** [comment]
@easyCZ Are you working on this?

**Comment by easyCZ** [comment]
To remove the calls: https://github.com/gitpod-io/gitpod/pull/13011

**Comment by easyCZ** [comment]
Remove RPC implementation: https://github.com/gitpod-io/gitpod/pull/13012
Remove proto definition: https://github.com/gitpod-io/gitpod/pull/13013
Remove Go DB model: https://github.com/gitpod-io/gitpod/pull/13014

Once these land, we can also drop the table.

**Comment by easyCZ** [comment]
Removal of table: https://github.com/gitpod-io/gitpod/issues/13009

**Comment by geropl** [comment]
@easyCZ Is this already "Done", or rather "in progress"?
