### ISSUE TITLE
Show error logs on the loading screen if dotfiles installation script exits with a non-zero code

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#13004]
### Bug description

It can be hard to notice that your dotfiles script is failing suddenly. In order to inspect `$HOME/.dotfiles.log`, it's necessary to at least have the IDE start but if you have a relatively complex dotfiles installation script and it fails, it can sometimes cause the IDE to not start.

### Steps to reproduce

- In your dotfiles script, do something like `sudo rm -rf /ide`

### Expected behavior

The loading splash screen to show an error if the dotfiles installation script fails, the user may acknowledge this by pressing an button to continue loading the workspace. 

It might be also nice to have an extra button on the loading screen to view `dotfiles.log` in case the dotfiles installation script didn't return an error code for users with dotfiles.

### Anything else?

I experienced this myself several times.
Also a report internally on [slack](https://gitpod.slack.com/archives/C02P236JZPC/p1663246828386599?thread_ts=1663245292.247189&cid=C02P236JZPC).

Related: https://github.com/gitpod-io/gitpod/issues/12100

**Comment by fcsonline** [comment]
Our team is really interested on having this feature. If not it is really hard to debug what is going on if something fails.
