### ISSUE TITLE
Automation environments in Werft

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#13026]
As of today, Gitpodders have the ability to create a preview environment in Werft, either through `/werft run preview` or by selecting the checkbox in a PR. This is very helpful from a SaaS point of view, but there are options for self-hosted users that are not captured by this automation.

The intention at this stage is not to capture every single permutation of self-hosted installation type but to capture likely installation types that will be required for cross-team work.

Unless stated otherwise, the installations should be built in GCP. Self-Hosted definitions of terminology can be found [here](https://www.notion.so/gitpod/Self-Hosted-Definitions-76409b905147450ba5307e9dacfc6e67).

- [x] #13027
- [x] #13028
- [x] #13030

## Questions

 - how will Werft/Harvester behave if a user creates multiple preview environments? /cc @gitpod-io/platform 
 - should these instances deploy Gitpod, or is it just the infrastructure that is then installed via KOTS? /cc @gitpod-io/engineering-self-hosted 

---

The expectation is that these new environments will add a new line in the block at the bottom of a PR

![image](https://user-images.githubusercontent.com/275848/190597986-c33f796e-7e3c-4ea4-b61c-41482f78ed62.png)

**Comment by MrSimonEmms** [comment]
See also [RFC](https://www.notion.so/Future-preview-environments-00b475e599344c61b527cedd22364c21) from Aleks
