### ISSUE TITLE
Add python IDE configuration to integrate with pyenv

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#13029]
## Is your feature request related to a problem? Please describe

Right now it's being done externally (from an IDE perspective) at [here](https://github.com/gitpod-io/workspace-images/blob/86212df19c9f06ce263987e6efa23740ef6c5d05/chunks/lang-python/python_hook.bash#L96-L103).

## Describe the behaviour you'd like

Upon the existence of ms-python.python and detection of `pyenv` on the workspace, add the following **Machine** settings from the Gitpod vscode extension:
```json
{
  "python.defaultInterpreterPath": "$HOME/.pyenv/shims/python",
  "python.terminal.activateEnvironment": false
}
```

Jetbrains IDEs are not covered by this but would be nice if someone can do that as well.

## Additional context

https://gitpod.slack.com/archives/C01KGM9BH54/p1663313469673879?thread_ts=1663268941.926259&cid=C01KGM9BH54

https://gitpod.slack.com/archives/C01KGM9BH54/p1663747428135699

**Comment by loujaybee** [comment]
I'll need to do some investigation into this one.
