### ISSUE TITLE
Forking on gitpod takes up to 56 seconds

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1303]
### Describe the bug

Pressing the fork button
![image](https://user-images.githubusercontent.com/11302521/76167869-39a89a80-616a-11ea-917a-0b980253ab30.png)

Takes up to 58 seconds to open the required GUI to finish forking, this takes too much time.

### Steps to reproduce

1. Open any repository on gitpod that you have not forked
2. Try to fork it and expect long delay

### Expected behavior

Should take max 5 sec

### Example repository

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/082c02c0-f530-4b82-94c6-5ce8a6d59352)

**Comment by corneliusludmann** [comment]
Can you reproduce it or does this happen to you often? I used your snapshot and it took less than 3 seconds that the message appears after hitting the `Fork...` button. Recently, GitHub had some API outages. Maybe that was the reason?!

**Comment by Kreyren** [comment]
> Can you reproduce it or does this happen to you often? 

Happens every time

> Recently, GitHub had some API outages. Maybe that was the reason?!

Possible, i will let you know if the issue persist.

**Comment by Kreyren** [comment]
assuming solved, will reopen if this issue persist
