### ISSUE TITLE
Add commit verified signature with pgp

### ISSUE THREAD

**Issue by gerardo-junior** [gitpod-io/gitpod#1304]
Generate a pgp key by account and add on github account and configure git on the gitpod container layer

![](https://i.imgur.com/nlyzJff.png)

https://help.github.com/en/github/authenticating-to-github/about-commit-signature-verification

**Comment by gerardo-junior** [comment]
A key wallet and dotfiles config can improve the possibility to make gitpod a standard workspace for all

**Comment by geropl** [comment]
@gerardo-junior I'm not sure I understand correctly: You're asking for Gitpod automatically importing SSH keys added to your GitHub account? Or a SSH key management within Gitpod?

**Comment by gerardo-junior** [comment]
Originally I was thinking of an option to manage the pgp commit sigin on gitpod.  but now i realized a problem to run manual deploy on gitpod.  it would be nice to have a key wallet and the possibility to load dotfiles.


because in the bank that I work one of the reasons why we didn't adopt gitpod in this moment was lack of possibility to carry out signed commits (only with custom image)

**Comment by geropl** [comment]
> because in the bank that I work one of the reasons why we didn't adopt gitpod in this moment was lack of possibility to carry out signed commits (only with custom image)

Ok, think I got it.

One thing you could do today is to inject your SSH key environment variables `SSH_KEY`: https://gitpod.io/settings/ Those are stored encrypted and allow you to scope them to one single repository. (this has to be done by every user)

Then you have a `.gitpod.yml` with a `command` that runs a script like this on every start (once for a repository, works for all users that have the env var set in their user settings):
```
#!/bin/bash
WRITE_PATH="/home/gitpod/.ssh"

if [ ! -f "$WRITE_PATH" ]; then
    if [ -z "$SSH_KEY" ]; then
        echo "SSH_KEY not set, doing nothing."
        return;
    fi
    echo "$SSH_KEY" > "$WRITE_PATH"
    echo "Set WRITE_PATH value based on contents from SSH_KEY"
fi
```

Still not as nice as custom .dot files but after the setup it comes close to 99% UX-wise.

**Comment by gerardo-junior** [comment]
Load credentials by environment variables, became an option after I opened this issue, but I'm not a big fan of this solution because environment variables can be exposed when opening malicious repositories. it is a feature that depends on different parts of the project, but I will try to develop this feature to make a PR. it would really be very useful for workflows that depend on a high level of security
