### ISSUE TITLE
Gitpod to support rebuild current workspace

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1305]
Having to close the current workspace and having to build a new one can be confusing for new users, we should make a way to trigger the rebuild of the current workspace

**Comment by rholland** [comment]
I agree.

**Comment by Kreyren** [comment]
How thought

**Comment by ceefour** [comment]
This is really needed: https://community.gitpod.io/t/configuration-workflow/1299

**Comment by ldettwy** [comment]
This is a pretty big barrier for me. I think it should stay open.

**Comment by danielbraun89** [comment]
In github codeapaces:  Ctrl+P -> rebuild container.  
Why does it have to be so difficult to implement in gitpod?  Also why is this marked as stale with no option to reopen? Your stale bot is way too aggressive

**Comment by gtsiolis** [comment]
Thanks @danielbraun89! We're currently working on this. You can track all progress in the epic https://github.com/gitpod-io/gitpod/issues/7671 which is currently planned for Q3'2022. Cc @andreafalzetti @loujaybee
