### ISSUE TITLE
Workspaces start even though usage limit exceeded for the team

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13059]
The usage limit is not working for a new team on gitpod.io configured with UBP.
Current total usage is showing 153 credits, but limit is set to 100 credits.

- no notification
- workspaces are starting normally 

This may be related to #13058 

Noticed this on gitpod.io while doing UBP walkthrough ([internal](https://www.notion.so/gitpod/Usage-based-Pricing-for-Teams-end-2-end-Walkthrough-53d41966254245ab8ae77112dc639e54)) with a new team. ([admin](https://gitpod.io/admin/teams/a6308ddb-9e4c-4b06-9beb-caa92dd9808b)). That team has been configured with usage-based billing.

<img width="1100" alt="Screenshot 2022-09-19 at 00 06 06" src="https://user-images.githubusercontent.com/849592/190932024-c4fb97ed-9169-4141-a76d-4c954bb58d24.png">

<img width="1100" alt="Screenshot 2022-09-19 at 01 06 20" src="https://user-images.githubusercontent.com/849592/190932068-69d747fa-4117-4195-9c09-8adb5966ba0d.png">

**Comment by jldec** [comment]
@svenefftinge is this resolved now? I can no long reproduce the issue.

**Comment by svenefftinge** [comment]
Yes, it got resolved with changes from last week.
