### ISSUE TITLE
Off-by-one difference between total usage and usage detail in usage list

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13056]
I noticed this in a personal usage view for a user who only had 1 workspace session (I manually opened gitpod.io/usage).

The total in the left says 11 credits, but the session in the list says 10.0 credits. Perhaps we are rounding incorrectly for the total? 

<img width="1100" alt="Screenshot 2022-09-18 at 12 39 56" src="https://user-images.githubusercontent.com/849592/190898227-5273ee51-86e4-430b-bc71-236bf38bc10d.png">

**Comment by easyCZ** [comment]
@jldec Would it be acceptable to show the total usage to 2 decimal points? We're guaranteed that all the results store at most 2 decimal points, this means that the resulting total usage will also have at most 2 decimal points. This would then remove any rounding all together and ensure the total matches the sum of the entries.

**Comment by jldec** [comment]
> Would it be acceptable to show the total usage to 2 decimal points? 

@easyCZ Yes, that's fine. :)
