### ISSUE TITLE
Improve support for forking to personal repo at gitlab

### ISSUE THREAD

**Issue by hallvard** [gitpod-io/gitpod#1307]
Now that gitpod supports gitlab, it would be nice to have two features now currently available only for GitHub. BTW, my scenario is sharing a repo to a university class with the setup and initial code for an assignment, where the students' submissions are their personal fork (also on gitlab)

- A warning if the user doesn't have write access to the original, and hence cannot push.
- Easy forking to (new) personal repo. The default repo name should be the same as the original and the new remote should be the default for pushing.

**Comment by svenefftinge** [comment]
This has been deployed to gitpod.io now.
