### ISSUE TITLE
Wrong status shown in "create workspace" page when allocating resources

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#13070]
## Is your feature request related to a problem? Please describe

Currently, when you create a new workspace, it can sometimes spend a few minutes in "Pending" state.

This is because `server.createWorkspace()` currently waits for the workspace to be actually started before returning, and during scale-up it can sometimes take several minutes before the workspace is actually started.

This causes users to remain stuck in an empty "create" screen, even though they could already move on to the "start" screen (note: you can simulate that yourself by opening the same workspace from your workspaces list -- this will go directly to the "start" screen)

| New workspace is "Pending" for 4 min | User is stuck in the screen ("create") | User could see this instead ("start") |
| --- | --- | --- |
| <img width="1435" alt="Screenshot 2022-09-19 at 10 32 15" src="https://user-images.githubusercontent.com/599268/190979859-9b1bd9b8-ac97-4238-af71-beedb2927e66.png"> | <img width="1437" alt="Screenshot 2022-09-19 at 10 31 57" src="https://user-images.githubusercontent.com/599268/190980060-40796700-b421-4fb4-8299-f8986f106f99.png"> | <img width="1436" alt="Screenshot 2022-09-19 at 10 32 05" src="https://user-images.githubusercontent.com/599268/190980064-e46bb9e5-9ba4-48fc-94fe-05dc17f2feab.png"> |

## Describe the behaviour you'd like

We could keep having `server.createWorkspace()` call `internalStartWorkspace` to get things started, but no longer `await` on it.

This way, users would graduate much faster out of the empty "create" screen and into the more dynamic "start" screen.

Note: This won't actually make workspaces start faster, but will show a more accurate state to users, instead of leaving them in a stressful empty page where nothing seems to happen for several minutes.

## Describe alternatives you've considered

1. Continue showing a screen where nothing seems to happen for several minutes

**Comment by AlexTugarev** [comment]
@jankeromnes, where would we get events or state update from during `User could see this instead ("start")`?

**Comment by jankeromnes** [comment]
@AlexTugarev The start page can figure this out given an ID, right?

You can try this yourself during scale-up:
1. Create a new workspace -- it gets stuck in "checking..." for several minutes
2. Meanwhile, open the workspaces list in a new tab, and open the same workspace -- there it's already in the "preparing" phase with a dynamic loader

I think the second option is a more accurate (and less stressful) state representation.

**Comment by jankeromnes** [comment]
Here is a screencast demonstrating the problem:

<a href="https://youtu.be/-nMP1zJg0-A"><img width="849" alt="Screenshot 2022-09-27 at 08 56 00" src="https://user-images.githubusercontent.com/599268/192454967-add49394-4756-4a12-a450-ff9b9d744309.png"></a>

**Comment by akosyakov** [comment]
@jankeromnes You did not have a look at browser logs by any chances to exclude that it is some kind of frontend bug?

**Comment by jankeromnes** [comment]
@akosyakov Thanks for looking into this! From what I remember, there was no specific frontend bug in the browser console. But, the next time I see this problem, I'll check again just in case.

**Comment by akosyakov** [comment]
> @akosyakov Thanks for looking into this! From what I remember, there was no specific frontend bug in the browser console. But, the next time I see this problem, I'll check again just in case.

@jankeromnes yes I had yesterday 3 times and there were not any error in logs 👍

**Comment by akosyakov** [comment]
btw @jankeromnes I'm not looking into it, we tried something last week https://github.com/gitpod-io/gitpod/issues/14061#issuecomment-1308635501 but it would be better if webapp team takes over the experiment 🙏

**Comment by svenefftinge** [comment]
this is "fixed" now (at least the UX)
