### ISSUE TITLE
Cannot create workspaces from a template

### ISSUE THREAD

**Issue by lechien73** [gitpod-io/gitpod#1308]
### Describe the bug
When trying to create a new workspace based on a pre-defined template with a `.gitpod.dockerfile` and `.gitpod.yml file`, we get the error in the attached screenshot. Creating a workspace from a blank repository works without issue.

### Steps to reproduce
Visit https://github.com/Code-Institute-Org/gitpod-full-template, click on *Use this template*, create a new repository based on the template and then try open the new repo in Gitpod.

### Expected behavior
A new workspace would be created using the template, as was working up until today. No changes have been made to the template.

### Example repository
https://github.com/lechien73/mattles
![Screenshot 2020-03-12 at 09 53 10](https://user-images.githubusercontent.com/21156053/76509506-086cea80-6448-11ea-8f3d-88e8e70142b6.png)

**Comment by csweichel** [comment]
Hi,

Thank you for reporting this.
The issue has been resolved.
