### ISSUE TITLE
Can't remove synced extensions from settings sync

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#13091]
### Bug description

I have settings sync and `gitpod.remote.syncExtensions` enabled but there is an odd issue. A bunch of unknown extensions (to me) are automatically installed, even if I manually mark Do not sync extension and uninstall, they appear back on my next workspace. These un-synced extensions are also added on `settingsSync.ignoredExtensions[]` (as you can see on the screenshot) but that doesn't help. This is not an issue on VSCode Web.
<img width="1504" alt="Screenshot 2022-09-19 at 7 11 27 PM" src="https://user-images.githubusercontent.com/39482679/191029507-601b6c50-9704-4bfb-a9ac-4b355bc7e3ea.png">

### Steps to reproduce

- Enable [Setting sync](https://www.gitpod.io/docs/ides-and-editors/settings-sync)
- Enable `gitpod.remote.syncExtensions`
- Mark `Do not sync extension` and uninstall a bunch of extensions
- Create a new workspace
- Notice that those extensions are still maked `Do not sync` but somehow they got installed

### Expected behavior

Uninstalled extensions should get removed from settings sync.

**Comment by loujaybee** [comment]
Related to: 

- https://github.com/gitpod-io/gitpod/issues/7906

**Comment by jeanp413** [comment]
@axonasif you need to sync the uninstallation first i.e. remove them from `gitpod.remote.syncExtensions` and then uninstall so they are removed from the sync server, then if you want to only install an extension locally add it to `gitpod.remote.syncExtensions` first or use the `Install (do not sync)` action

**Comment by akosyakov** [comment]
@jeanp413 is there something to document? cc @loujaybee

**Comment by jeanp413** [comment]
Don't think so as that's normal behavior, but we can mention vscode docs if needed

**Comment by axonasif** [comment]
> @axonasif you need to sync the uninstallation first i.e. remove them from `gitpod.remote.syncExtensions` and then uninstall so they are removed from the sync server, then if you want to only install an extension locally add it to `gitpod.remote.syncExtensions` first or use the `Install (do not sync)` action

Hey @jeanp413, where can I find `gitpod.remote.syncExtensions`? Not available on my `settings.json`.

**Comment by jeanp413** [comment]
@axonasif sorry I meant `settingsSync.ignoredExtensions`

**Comment by axonasif** [comment]
@jeanp413 I tried this r8n but it didn't help, maybe I'm doing something wrong 😅 ?
