### ISSUE TITLE
error

### ISSUE THREAD

**Issue by likibikangben** [gitpod-io/gitpod#1310]
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: Error response from daemon: No such image: gitpod.io/image-builder/selfbuild:ba2eeb0d5ce9f211f69b92c42ce48af11b06e74ef72db6a19a4f119ea12d37e3

**Comment by nisarhassan12** [comment]
Hi, Thank you for reporting this.
The issue has been resolved.
