### ISSUE TITLE
code -r . <some-other-files> does not work properly on vscode web

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#13107]
### Bug description

Trying to reopen the VSCode web instance with a different code-workspace root directory and a relative file to it does not work as expected. This is not an issue on VSCode desktop.

See the video below if it's not fully clear what I mean:

https://user-images.githubusercontent.com/39482679/191192199-8b1648c7-cdb0-4fc9-9baa-b0509f774c94.mp4

### Steps to reproduce

- Open a workspace on vscode web.
- Inside your workspace, create a dir, e.g `src`.
- Copy or create a file inside the `src` dir, e.g `README.md`.
- Then on your terminal run `cd src && code -r . README.md`
- Notice that the vscode-instance switched to `src` dir as it's code-workspace root but didn't open `README.md` there, however it got opened on the parent instance.

### Expected behavior

The files relative to the new code-workspace root dir should also get opened as like VSCode-desktop.

### Anything else?

Originally bought up by @TimothyStiles
https://discord.com/channels/816244985187008514/1020773220279922789/1021538242752946196

**Comment by akosyakov** [comment]
@axonasif VS Code Web cli is not the same as for VS Code Desktop cli. I think you need to open an issue in https://github.com/microsoft/vscode to support it.

**Comment by jeanp413** [comment]
Hey @TimothyStiles, actually it probably is a bug in our fork of vscode in the browser and not an upstream bug

**Comment by TimothyStiles** [comment]
@jeanp413 thanks for telling me! I'll close it now.

**Comment by jeanp413** [comment]
Took a deeper look and actually is kinda expected behavior of upstream code as the with the exposed API is only possible to open a folder or a workspace [[1](https://github.com/microsoft/vscode/blob/da506e9b8d86a7265d53255ef8a8603d792d74f5/src/vs/workbench/services/host/browser/browserHostService.ts#L49-L79)]
So it's Ok to reopen the issue upstream, sorry for the confusion.

**Comment by axonasif** [comment]
Upstream issue was closed:
- https://github.com/microsoft/vscode/issues/161330#issuecomment-1303100415
