### ISSUE TITLE
Replace the editor selection cards with the new dropdown component used in the start with options new workspace modal

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#13116]
### Problem to solve

Currently, we're using the [`SelectableCardSolid`](https://github.com/gitpod-io/gitpod/blob/fe26d2613df2f85667829c9de86bbeb187dc81cf/components/dashboard/src/components/SelectableCardSolid.tsx) component in multiple areas in the dashboard like the Editor, Workspaces, etc.

While the options for _Editor_ and _Workspaces_ will grow over time, they will always remain finite. See https://github.com/gitpod-io/gitpod/issues/7751 and https://github.com/gitpod-io/gitpod/issues/12708.

However, this card component can not scale well after adding too many options, especially when the card will have to contain multiple rows of information like the _Workspaces_ (class) selection.

See also [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1663594639896499) (internal). Cc @loujaybee 

### Proposal

~~Introduce a new, more flexible component or pattern like a dropdown that is able to scale better for selecting from a range of options like the _Editor_ and _Workspaces_.`~~

Replace the editor selection cards with the new dropdown component used in the start with options new workspace modal.

See [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1672836161790069) (internal). Cc @akosyakov 

| BEFORE / AFTER |
|-|
| <img width="1464" alt="editor" src="https://user-images.githubusercontent.com/120486/213715850-15060768-7b5a-4c5e-8376-9ac672900c28.png"> |

**Comment by loujaybee** [comment]
**Note:** Also affects the IDE selection during onboarding flow.

**Comment by loujaybee** [comment]
Can we hold off on this for now? @geropl is talking to WebApp team, and @selfcontained might pick this up 🙏

**Comment by laushinka** [comment]
> Can we hold off on this for now? @geropl is talking to WebApp team, and @selfcontained might pick this up 🙏

What's the status of this? In case IDE can pick it up.

**Comment by filiptronicek** [comment]
@gtsiolis after the discussions in https://github.com/gitpod-io/gitpod/issues/16831, should we leave the <kbd>Latest</kbd> button in the preferences and dynamically change the dropdown contents **or** make it static without the button (include everything) as the original design in the PR description suggests?

**Comment by gtsiolis** [comment]
@filiptronicek From what I understand, we can safely keep the _Latest_ checkbox option in settings to catch both VS Code and JetBrains editor cases, regardless if we replace the cards with the dropdown.

What is missing from the designs in the issue description above, is the beta notice for the JetBrains integration. We could either drop it or show a small note below the dropdown, see screenshots below. Cc @loujaybee @akosyakov 

| Editors dropdown | Editors dropdown with beta notice |
|-|-|
| <img width="796" alt="Editors" src="https://user-images.githubusercontent.com/120486/225075418-47fcca35-5c7c-4907-96a7-88ec052a41b9.png"> | <img width="796" alt="Editors-1" src="https://user-images.githubusercontent.com/120486/225075433-0f5038a1-8391-471a-9eca-102bc0bd3858.png"> |

**Comment by gtsiolis** [comment]
@filiptronicek I'm adding below a minor correction in the dropdown to match the expectations from the [relevant discussion](https://gitpod.slack.com/archives/C01KPEPNBD0/p1678730088606169?thread_ts=1678135856.665879&cid=C01KPEPNBD0) (internal) earlier today and the upcoming changes in https://github.com/gitpod-io/gitpod/pull/15252.

| Editor dropdown | Editor dropdown with beta notice |
|-|-|
| <img width="796" alt="Editors" src="https://user-images.githubusercontent.com/120486/225077663-2230f50e-9bb8-4bca-b6d8-62ab0296a704.png"> | <img width="796" alt="Editors-1" src="https://user-images.githubusercontent.com/120486/225077666-f4dfa640-d2f6-4898-85ee-f6ae970139e5.png"> |
