### ISSUE TITLE
Settings Sync restart prompt has no way to dismiss

### ISSUE THREAD

**Issue by jacobparis** [gitpod-io/gitpod#13122]
Currently there is no way to dismiss the VS Code Settings Sync Modal: 

![image](https://user-images.githubusercontent.com/5528307/191258364-85eafa04-3b96-4147-b975-4986260f5a42.png)

**Comment by loujaybee** [comment]
Copying internal response:

> Could you raise it as an issue? The restart UX is indeed a bit rough, because if you forget or don’t know to do the restart, the changes don’t apply and you’re left wondering why settings sync isn’t working. Closing window is also not enough, has to be a full restart.
