### ISSUE TITLE
How to add vscode extension whose `.vsix` is not present

### ISSUE THREAD

**Issue by anikethsaha** [gitpod-io/gitpod#1312]
First of all! Thanks a lot for gitpod and with your `professional open source` program !

I noticed after downloading the released package of `prettier` and noticed it doesnt have `.vsix` file in it. Is there any way to have these extensions running in gitpod ?
After cloning and building prettier for vscode , it just gives `extension.js` file and I think its not compatible with gitpod ! (I tried dragging , didnt work !)
I know I am missing something but not sure what !

Thanks !

**Comment by corneliusludmann** [comment]
The `package.json` of `prettier` has a `vscode:package` script defined:
https://github.com/prettier/prettier-vscode/blob/9476a014323f41da7e89a05f133671a97a53ac07/package.json#L71-L72

Run `yarn && yarn vscode:package` and you get a `prettier-vscode-x.xx.x.vsix` file. Of course, you can build the *.vsix in Gitpod as well: https://gitpod.io/#https://github.com/prettier/prettier-vscode

**Comment by anikethsaha** [comment]
.opps. ! I did build it but only checked the dist. 
thanks
