### ISSUE TITLE
getNotifications is returning 500 code errors

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#13131]
[Dashboard](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28gitpod_server_api_calls_total%7Bmethod%3D%5C%22getNotifications%5C%22%7D%5B7d%5D%29%29%20by%20%28statusCode%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D&query=gr)
<img width="1587" alt="Screenshot 2022-09-20 at 15 44 55" src="https://user-images.githubusercontent.com/1419286/191274338-bb27dee5-5ae6-4e52-b316-28c6a2dd523e.png">

query: `sum(increase(gitpod_server_api_calls_total{method="getNotifications"}[7d])) by (statusCode)`

**Comment by easyCZ** [comment]
@jankeromnes Landing https://github.com/gitpod-io/gitpod/pull/13178 caused this issue to close. But I believe the fix introduced does not actually fix the API returning 500 errors - it handles them on the UI side but does not stop them from happening server side. Are you happy for me to re-open?

**Comment by jankeromnes** [comment]
Hi @easyCZ! 👋

> it handles them on the UI side but does not stop them from happening server side

Actually, https://github.com/gitpod-io/gitpod/pull/13178 handles them server side 😇

<img width="1386" alt="Screenshot 2022-09-22 at 09 46 46" src="https://user-images.githubusercontent.com/599268/191688758-d7dbd96b-3c01-499e-8e92-fd5b8907e816.png">

And looking at the code, I'm pretty sure that this does fix the API returning 500 errors (unless `super` throws, but that [seems unlikely](https://github.com/gitpod-io/gitpod/blob/fff9ce3d5b7a2b69481b1284d0ad5a1f66de8a76/components/server/src/workspace/gitpod-server-impl.ts#L3229-L3232)).

But please do re-open this if you notice more 500 errors from this call post deployment. 👍

**Comment by easyCZ** [comment]
Thanks @jankeromnes, I must have confused the PRs. This does look like it indeed handles them. I'll do some validation on this from the metrics side post rollout and will re-open if we continue to see issues.
