### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by entibo** [gitpod-io/gitpod#1313]
### Describe the bug
Similar to what was reported in other issues (eg. https://github.com/gitpod-io/gitpod/issues/1268)
Cluster is `eu01` and it worked yesterday.

> cannot initialize workspace: cannot initialize workspace: cannot restore backup: tar /mnt/workingarea/4e34a370-2576-4ad8-9cfd-6702f65789c0: exit status 1;tar: write error: No space left on device

**Comment by jankeromnes** [comment]
Hi @entibo, thank you for reporting this problem. We're looking into it.

**Comment by svenefftinge** [comment]
This should be resolved now.

**Comment by jankeromnes** [comment]
@entibo There was a bad node in the Europe cluster. We have removed it, and also removed another one that acted up this morning.

Could you please try again?

**Comment by entibo** [comment]
Working now. Thanks a lot!
