### ISSUE TITLE
registerGithubApp is returning 500 code errors

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#13132]
<img width="1595" alt="Screenshot 2022-09-20 at 15 47 51" src="https://user-images.githubusercontent.com/1419286/191275044-ab224fc7-e06f-47f7-9e35-421d641f1f75.png">

[Grafana](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28gitpod_server_api_calls_total%7Bmethod%3D%5C%22registerGithubApp%5C%22%7D%5B7d%5D%29%29%20by%20%28statusCode%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D&query=gr)

query: `sum(increase(gitpod_server_api_calls_total{method="registerGithubApp"}[7d])) by (statusCode)`

**Comment by axonasif** [comment]
Test comment (please ignore) 🙏
