### ISSUE TITLE
[self-hosted] Consider separating k8s system pods from Gitpod IDE/meta/workspace-service pods

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#13139]
## Description

The AKS documentation is [pretty emphatic](https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli) that production clusters should isolate system workloads (coredns, metrics-server) from user workloads. However, the [microsoft-aks guide](https://github.com/gitpod-io/gitpod-microsoft-aks-guide/blob/main/setup.sh#L90-L107) uses the default nodepool for Gitpod services. At the time this issue was created we do the same thing for the Terraform azure module.

While running more nodes is obviously more costly it's worth considering splitting up our workloads like the AKS documentation recommends. This might be worth considering for the EKS and GKE modules as well.

**Comment by metcalfc** [comment]
@adrienthebo I'm supportive. We've seen several deployments already that would be safer if this was the case.

**Comment by MrSimonEmms** [comment]
Broadly supportive of this change too.

If we're using Terraform, I guess we could have a `independent_control_nodes` boolean (or something similar). That would then enable us to support enterprises who want the safety of separate system pods, or the cheapness of not.
