### ISSUE TITLE
Directly support Azure Blob Storage instead of shimming to it via Minio

### ISSUE THREAD

**Issue by mrzarquon** [gitpod-io/gitpod#13135]
## Is your feature request related to a problem? Please describe
Currently we ship two versions of minio in our image list, because AKS blob storage was [deprecated](https://github.com/bitnami/charts/issues/10258) and we also want a way to support S3 for incluster storage, which pulls in another image.

This makes [mirroring images and tagging them with release](https://github.com/gitpod-io/gitpod/issues/12812) difficult because we can't easily flatten every image into a unique single tag for a release.

## Describe the behaviour you'd like
A customer can use Azure Blob Storage directly.

## Describe alternatives you've considered
Minio gateway was the alternative, but it's since been [deprecated](https://blog.min.io/deprecation-of-the-minio-gateway/).

**Comment by MrSimonEmms** [comment]
AFAIK, this will require a change in the [content-service-api](https://github.com/gitpod-io/gitpod/blob/main/components/content-service-api/go/config/config.go#L14,L28) to add Azure as an option.

This will also require a change in the [Installer's `storage.go`](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/common/storage.go#L95,L34)
