### ISSUE TITLE
Vetur error message concerning VSCode version

### ISSUE THREAD

**Issue by Christoph-Harms** [gitpod-io/gitpod#1314]
### Describe the bug
The following error message appears when opening a workspace and having the vetur extension installed. The extension does not seem to be completely dysfunctional though, at least the syntax highlighting still works.
<img width="506" alt="Bildschirmfoto 2020-03-13 um 09 24 36" src="https://user-images.githubusercontent.com/17005834/76604587-4b45c580-650f-11ea-81e9-a32aced37bc6.png">

### Steps to reproduce
1. Have the vetur extension installed
2. Start and open your workspace

### Expected behavior
No error message should appear

**Comment by zzisu** [comment]
Still the same bug now...

**Comment by jankeromnes** [comment]
Oh, sorry for the over-zealous stale-bot here. 😬

But, please switch your Gitpod IDE to VS Code in https://gitpod.io/settings/ (in Feature Preview now, but will become the default IDE soon) -- the Vetur extension should work in VS Code, since it's more recent.
