### ISSUE TITLE
Unable To Push To GitHub Via GitPod

### ISSUE THREAD

**Issue by JackBen2019** [gitpod-io/gitpod#1315]
I'm currently working on a repository and whenever I add 'git push' into the command line, it says that it was unable to access the repository and that access was denied to the account I'm currently logged into? (see screenshot below)

![image](https://user-images.githubusercontent.com/52998869/76700928-4f5f1800-66b4-11ea-8483-ebbe24f36f0c.png)

### Example repository
https://github.com/JackBen2019/Jack-Bennett-Data-Centric-Development-Milestone-Project

**Comment by JesterOrNot** [comment]
Hello, and welcome to the GitHub and the Gitpod community :tada: Can you show your access control page?

**Comment by JackBen2019** [comment]
Apologies, but I'm not sure what page you're referring to there?

**Comment by JesterOrNot** [comment]
See https://www.loom.com/share/35e0bde4082247a296d05e156fc2f767

**Comment by AlexTugarev** [comment]
@JackBen2019 thanks for reporting! We found a bug in detecting the repo URL for with the built-in permission check should be triggered, thus you didn't see a notification suggesting to open https://gitpod.io/access-control/ and give Gitpod permissions necessary to allow `git push`. 

You can solve it manually by navigating to https://gitpod.io/access-control/ and allowing `write public repos`.

**Comment by JackBen2019** [comment]
Ah brilliant! I've just gone onto the access control page, updated the relevent options and it's now allowing me to push.

Cheers Alex!

**Comment by Kreyren** [comment]
> See https://www.loom.com/share/35e0bde4082247a296d05e156fc2f767

irelevant to do topic

how do you make those videos?

**Comment by JesterOrNot** [comment]
First of all, it was completely relevant, he didn't know how to get to the page for the authentication for push access. Second of all I use [loom](https://chrome.google.com/webstore/detail/loom-for-chrome/liecbddmkiiihnedobmlmillhodjkdmb)

**Comment by rogfrich** [comment]
Hi, I just started using GitPod in the last day or so. I think that I also didn't get a notification to check / change the access control page (or if I did, I missed it, but I don't think so).

Like the OP, I was struggling to understand why I couldn't push to my GitHub account. I found this GitHub issue thread by Googling for the problem. I'm all sorted now, but wanted to add my +1.

**Comment by Exlsunshine** [comment]
> @JackBen2019 thanks for reporting! We found a bug in detecting the repo URL for with the built-in permission check should be triggered, thus you didn't see a notification suggesting to open https://gitpod.io/access-control/ and give Gitpod permissions necessary to allow `git push`.
> 
> You can solve it manually by navigating to https://gitpod.io/access-control/ and allowing `write public repos`.

it works, thanks!

**Comment by sbalasa** [comment]
This helped me:
`git push https://<username>:<password>@<repo_url_link>`

**Comment by esmaeilmirzaee** [comment]
> This helped me: `git push https://<username>:<password>@<repo_url_link>`

It imposes security risks.

**Comment by axonasif** [comment]
Hi @esmaeilmirzaee, I assume you're having a similar issue, hence you're here on this old issue 😄 
If that's the case, I'd suggest to:
- Check if you have the necessary scopes granted here: https://gitpod.io/integrations
- Check if [this](https://www.gitpod.io/docs/github-integration#errors-with-private-repositories-on-github-orgs) is the case.

**Comment by yuwash** [comment]
I created a gitpod workspace from a template and then struggling hard to push it to my own repository. I originally added `git remote add my-origin git@gitlab.com:my/repo.git` (or same with github) and it failed to push whether from terminal inside VS Code or the native push feature of VS Code. Write access was already enabled as suggested above. I then changed the remote url to `https://github.com/my/repo` and that worked! No need for password, either to be included in the URL as suggested above or being typed in.

**Comment by Nolulamo** [comment]
I was facing the same issue, but I removed the origin URL and re-added it with an auth token, and it worked. Gitpod automatically adds remote origins when you open your github repo with it; just remove that origin and add another with an auth token, and it will work.

**Comment by AzerbijanFan** [comment]
Im lost
