### ISSUE TITLE
Credits column in usage detail view is misaligned and truncation is annoying

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13154]
Content in the Credits column should be aligned right, and I think overflow:hidden would work better (instead of ellipses) when the "min" units string does not fit.

<img width="992" alt="Screenshot 2022-09-21 at 10 12 27" src="https://user-images.githubusercontent.com/849592/191452356-209e4a7f-bc26-4e28-bf1a-0d471e0bb2ce.png">
<img width="1161" alt="Screenshot 2022-09-21 at 10 12 05" src="https://user-images.githubusercontent.com/849592/191452366-97f71b41-bf2b-4e0f-a9c3-1eb53def17f5.png">

**Comment by easyCZ** [comment]
Originally, the ellipsis existed because we were storing the credits with high precision. Now, we only store them with a 2 digit precision. To fix the ellipsis, we could simply stop truncating and show the 2 decimal points that we now guarantee to have on the results.

**Comment by svenefftinge** [comment]
I think this is fixed. Please reopen if I'm missing something.
