### ISSUE TITLE
Stripe: Create observability into the type, rate and return code of API calls we issue against Stripe

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#13157]
As it says in the title. An example is the metric `gitpod_server_api_calls_total` ([link](https://grafana.gitpod.io/d/Gj5DE-O7k/meta-overview?orgId=1&editPanel=36)) from which we get insight into error rates, repsonse times and type of method called.

**Comment by easyCZ** [comment]
Implementation-wise, we should use a HTTP Client tripper to compose an HTTP client which also exports metrics. See https://dev.to/stevenacoffman/tripperwares-http-client-middleware-chaining-roundtrippers-3o00 for examples

**Comment by jankeromnes** [comment]
FYI, Stripe Dashboard > Developers already has this:

<table><tr><td>
<img width="755" alt="Screenshot 2022-09-21 at 10 58 00" src="https://user-images.githubusercontent.com/599268/191461942-30a32ea8-187f-4beb-ba81-5f6207ed324a.png">
</td><td>
<img width="750" alt="Screenshot 2022-09-21 at 10 58 11" src="https://user-images.githubusercontent.com/599268/191461949-1976fff1-9ea2-41bc-8a78-fed20242d20c.png">
</td></tr></table>

**Comment by geropl** [comment]
Still seems worth implement the low-hanging parts on our end. a) Grafana is more flexible in displaying data, and b) we can build alerts with our common tools.

**Comment by easyCZ** [comment]
> Still seems worth implement the low-hanging parts on our end. a) Grafana is more flexible in displaying data, and b) we can build alerts with our common tools.

Stripe will only have server metrics - for requests that actually reached it. If we fail to contact Stripe for whichever reason, we'd be blind - we need client side metrics also.

**Comment by easyCZ** [comment]
Client-side metrics from server [PR is here](https://github.com/gitpod-io/gitpod/pull/13645)

**Comment by easyCZ** [comment]
Metrics from server are coming through nicely on staging


![Image](https://user-images.githubusercontent.com/1419286/194399417-34ad7939-ab84-41f7-9bf8-293790119096.png)


However, metrics from `usage` include the full path in their labels which also includes Subscription IDs - this would lead to high cardinality of these metrics and will need to be reworked. We'll need to strip the IDs and sub-resources.
[Metrics reported from usage](https://grafana.gitpod-staging.com/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:false,%22expr%22:%22sum%28increase%28gitpod_stripe_requests_completed_seconds_count%5B1m%5D%29%29%20by%20%28path,%20code%29%22,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)

**Comment by easyCZ** [comment]
Fix for the high cardinality metrics is here - https://github.com/gitpod-io/gitpod/pull/13701

**Comment by easyCZ** [comment]
Metrics are now exposed properly [see dashboard](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22gitpod_stripe_requests_completed_seconds_count%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)
