### ISSUE TITLE
Goland does not set GOPATH to the same value as Workspace environment variables

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#13158]
### Bug description

When I launch gitpod on one of my [personal repositories](https://github.com/easyCZ/seer), Goland automatically detects GOPATH (in IDE config) and sets it to home/gitpod/go.

If I do the exact same thing with our gitpod-io/gitpod repo, it for some reason sets it to home/gitpod/go-packages. This then causes the IDE to not have the dependencies and requires me to manually ask it to fetch and index the dependencies.

### Steps to reproduce

Launch Goland on `gitpod-io/gitpod` repository and observe the GOPATH variable in Goland Settings is set to `home/gitpod/go-packages`

Screenshot of the GoLand Preferences (right after the workspace startup) with "Use GOPATH that is defined in system environment" set:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/418083/191464115-31f122ab-b868-4e8c-aa19-6a909fdfb1ad.png">

And then, here is what it looks like when we uncheck this option:

![image](https://user-images.githubusercontent.com/418083/191464333-5d4a9fef-b550-496a-840a-ac4c6a1a4dda.png)

### Anything else?

As a possible datapoint, if I add GOPATH=/workspace/go into my Gitpod env variables, it then shows up in the IDE configuration.
However, that should not be needed, as the GOPATH in the workspace image is set to /workspace/go already.

See [internal thread](https://gitpod.slack.com/archives/C01KGM9BH54/p1663708785555299)

**Comment by felladrin** [comment]
Extra info: When we uncheck the "Use GOPATH that is defined in system environment" option and ask GoLand to sync the project dependencies, it prints this warning:
```
GOROOT=/home/gitpod/go #gosetup
GOPATH=/home/gitpod/go #gosetup
/home/gitpod/go/bin/go mod tidy #gosetup
warning: GOPATH set to GOROOT (/home/gitpod/go) has no effect
```

**Comment by felladrin** [comment]
On YouTrack, when searching for [Goland sync dependencies](https://youtrack.jetbrains.com/issues?q=Goland%20sync%20dependencies) or [GOPATH](https://youtrack.jetbrains.com/issues?q=GOPATH), I could only find these related issues:

- [Implement ability to automatically run `go mod download`](https://youtrack.jetbrains.com/issue/GO-9454/Implement-ability-to-automatically-run-go-mod-download)
- [Ask users to download missing dependencies when a project is created from existing sources](https://youtrack.jetbrains.com/issue/GO-6697/Ask-users-to-download-missing-dependencies-when-a-project-is-created-from-existing-sources)
- [Go Modules dependencies are not synchronized](https://youtrack.jetbrains.com/issue/GO-6600)

**Comment by akosyakov** [comment]
@felladrin Did you file an issue on youtrack?

**Comment by felladrin** [comment]
We're closing this issue, as the `GOPATH` in GoLand settings is now correctly set with the same value from the workspace's `GOPATH` environment variable.

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/418083/207876033-b8774f33-7a92-4820-b8ee-316d79f31856.png">
