### ISSUE TITLE
Specify branch for dotfiles repository

### ISSUE THREAD

**Issue by francoisdtm** [gitpod-io/gitpod#13156]
## Is your feature request related to a problem? Please describe
My dotfiles are separated into different branches (one per machine). The `gitpod` branch is not the default one, and therefore I cannot use it for GitPod.

## Describe the behaviour you'd like
I would like to be able to choose which branch GitPod will clone and install into my workspaces.

**Comment by axonasif** [comment]
This is a useful thing to have, however you could use a install.sh script to determine which files are symlinked.

**Comment by francoisdtm** [comment]
I changed the default branch for an easy fix, but yes it can be automated
