### ISSUE TITLE
Improve content of notifications when the Usage Limit is reached

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13166]
The current notification text does not provide enough guidance.

To fix:

- Follow the same detailed explanation as the workspace start error message which mentions the team 
- Both should also link to your personal billing settings page where you can change billing accounts.

Existing notifications:
<img width="1034" alt="Screenshot 2022-09-20 at 18 47 33" src="https://user-images.githubusercontent.com/849592/191489633-728c8d94-60a1-43df-b277-eec80728ee4e.png">

<img width="1100" alt="Screenshot 2022-09-19 at 16 22 09" src="https://user-images.githubusercontent.com/849592/191489879-46c029cd-3370-4cf8-8d45-ddbcb91f6e43.png">

**Comment by jldec** [comment]
cc: @gtsiolis for design consideration 🙏 .

**Comment by svenefftinge** [comment]
I think it should mention the billing account and provide a link to switching to a different one (i.e. a link to the user's billing settings).
e.g. "The usage limit for 'team/user name' is almost reached. [Manage billing]."
