### ISSUE TITLE
Flask installed, but unable to access it

### ISSUE THREAD

**Issue by JackBen2019** [gitpod-io/gitpod#1316]
I've installed Flask via the command line and moved all the installed packages into the requirements.txt file so I know that Flask was definitely installed. I've also referenced Flask in my run.py file by adding '**from flask import Flask**'.

Now, when I try to run my 'run.py' file, it tells me that there is no module named 'flask'. I've added some screenshots below so you can see what I'm entering into the command line and also my file structure.

**Command line:**

![image](https://user-images.githubusercontent.com/52998869/76701015-1a9f9080-66b5-11ea-8b85-27765e8b9ae7.png)

**File structure:**

![image](https://user-images.githubusercontent.com/52998869/76701029-3b67e600-66b5-11ea-8d40-fec2b1c7207a.png)

### Example repository
https://github.com/JackBen2019/Jack-Bennett-Data-Centric-Development-Milestone-Project

**Comment by JesterOrNot** [comment]
Try doing `python3 run.py` as you installed it with `pip3` it seems.

**Comment by JackBen2019** [comment]
That's worked, thank you!

**Comment by JesterOrNot** [comment]
Glad to hear it! 🎉
