### ISSUE TITLE
Enable db-sync for d_b_prebuilt_workspace and d_b_prebuilt_workspace_updatable

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#13160]

**Comment by easyCZ** [comment]
https://github.com/gitpod-io/gitpod/pull/13164 and https://github.com/gitpod-io/gitpod/pull/13163 add the necessary migrations.
Next we need to configure these tables in db-sync

**Comment by easyCZ** [comment]
Configuration of db-sync is here https://github.com/gitpod-io/gitpod/pull/13165/files, needs to be merged only after we deploy the migrations tho.

**Comment by geropl** [comment]
"Done", or "In progress" ? 🤔

**Comment by easyCZ** [comment]
Weird, this was dragged into the Done column (this morning) in the Current Sprint but that didn't seem to have updated the status..
