### ISSUE TITLE
Custom popups similar to the one where we ask confirmation for deletion of workspaces. I want to show custom popups similar to that.

### ISSUE THREAD

**Issue by akshatnarayangupta** [gitpod-io/gitpod#13171]
## Is your feature request related to a problem? Please describe
When a user opens a git repo in Gitpod we want to show them some message in Custom pop-ups. Since terminal messages might not be visible/can be missed.

## Describe the behaviour you'd like
I would like the users to select on option With some message. Fo example - Do you want to continue opening this workspace? Agree/Disagree

## Describe alternatives you've considered
We tried asking for their choice using terminal tasks, but Since it is not focused, and can be stopped using Cmd+C commands, we want popups to ask for their choice.

**Comment by axonasif** [comment]
This is out of scope for Gitpod as of now, it's more of a VSCode thing, we do not develop VSCode, Gitpod only implements it. If you wish such functionality, you may consider developing a [custom VSCode extension](https://code.visualstudio.com/api/get-started/your-first-extension) to achieve that.

Closing this to continue on [here](https://github.com/gitpod-io/gitpod/issues/12977#issuecomment-1251538692).
