### ISSUE TITLE
Restrict access to shared running workspaces

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13188]
This issue specifically covers MVC access restriction on shared running workspaces
Any of the following would be a reasonable first step.

- A modification of the default behavior to limit access to users who can access the underlying repo (similar to #8257) 
- A team-level configuration flag turning the feature on/off for all workspaces associated with a team
- A team-level configuration flag limiting shared access to members of a team

**Comment by jldec** [comment]
Note workspace aspect (from [comment](https://github.com/gitpod-io/gitpod/issues/8257#issuecomment-1042723942)) 

> Running workspace access is mediated by ws-proxy, who has no notion of the authentication on server side. We'd need to introduce guest tokens (which we conceived of when we introduced the owner token, hence the name). 

cc: @atduarte , @gtsiolis

**Comment by csweichel** [comment]
> A team-level configuration flag limiting shared access to members of a team

When we originally built the workspace sharing feature we made provisions for this.

To implement team-level sharing (or any other form of "scoped" runtime sharing), we'd extend the current workspace admission spec with a "team" mode. This would cause `ws-manager` to produce a `guest token` (in addition to today's `owner token`) which is valid until the admission is changed to a different mode. The `fetchWorkspaceToken` call would then return this guest token to anyone authorised to access the workspace.

**Comment by csweichel** [comment]
> - A modification of the default behavior to limit access to users who can access the underlying repo (similar to https://github.com/gitpod-io/gitpod/issues/8257)
> - A team-level configuration flag turning the feature on/off for all workspaces associated with a team

Both features, IMHO live well in the scope of a "policy skateboard" we should be thinking about.

**Comment by csweichel** [comment]
A short term fix would be to introduce a query token that needs to be passed in order to access a shared workspace. I.e. knowing the URL is not enough.

**Comment by securitymirco** [comment]
Lets react rather quickly on this one and put a short term fix in place until we've got a full solution.
