### ISSUE TITLE
The usage limit almost reached (80%) notification can be distracting

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13187]
All team members see the notification when usage reaches 80% of the limit.
The only way to make it go away permanently (afaik) is to increase the limit.
Our options to fix this are:

~~1. Make the percentage at which this triggers configurable but leave the behavior unchanged~~
2. Only show the notification to team owners (good enough for now)
~~3. Replace the dashboard notifications with email notifications (sent only to team owners)~~
~~4. Offer a way for users to enable "don't show me this again for this billing period"~~

**Comment by svenefftinge** [comment]
Is distracting (or better alerting) not the original intend of this message?

**Comment by geropl** [comment]
Related: #13166

**Comment by jldec** [comment]
The problem is that everyone on the team is notified, but only team owners can do something to change the limit.

How about proceeding with option #2??

> Only show the notification to team owners (good enough for now)
