### ISSUE TITLE
Improved speed of workspace integration test

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#13197]
## Is your feature request related to a problem? Please describe

The workspace integration tests take about 1.5h on werft now. 2 hours is the limit for the werft job. We know that we will reach 2 hours in the near future.
e.g. https://werft.gitpod-dev.com/job/gitpod-workspace-run-integration-tests-main.122/logs

## Describe the behaviour you'd like

Run up to two workspaces in parallel

## Additional context

My analysis of [one sample job](https://werft.gitpod-dev.com/job/gitpod-workspace-run-integration-tests-main.122/logs)
The following are the main time eaters.
- build and wait for a ready preview environment `810` sec
- ws-manager tests `1191.773` sec
    -  Especially, [TestBackup](https://github.com/gitpod-io/gitpod/blob/6475a7846fac947697ff7038ae1a455a2d0d85b5/test/tests/components/ws-manager/content_test.go#L25) `420` sec
- workspace tests `2562.607` sec
     -  Especially, [TestGitHubContexts](https://github.com/gitpod-io/gitpod/blob/6475a7846fac947697ff7038ae1a455a2d0d85b5/test/tests/workspace/contexts_test.go#L30) `1682` sec

**Comment by utam0k** [comment]
These are my flash ideas:
- Create the multiple preview env for ws-manger tests and workspace tests
    This should at least pull time to the longest workspace test, saving 1191 seconds(part of the ws-manager test).
- Investigation of tests that can be run concurrently
    Currently, all tests are in series. This was to prevent flakey Possibly some tests could be done in parallel and still be fine.
- Reuse a workspace
    In some test cases, it should be possible to reuse the workspace. For example, for the https://github.com/gitpod-io/gitpod/blob/6475a7846fac947697ff7038ae1a455a2d0d85b5/test/tests/workspace/mount_proc_test.go#L47 test, we just want a workspace where we can execute commands. The workspace used in the other test cases will be fine.

**Comment by vulkoingim** [comment]
In general I would suggest to run tests in parallel where possible, as this would be (IMO) the easiest and least invasive change you can make. Moreover, it is a good practice in general. 

If you need more resources for the VM you can run the preview environment with `-a with-large-vm=true`, which would give you a VM with double the resources - `6` -> `12` CPU and `12` -> `24` GB RAM.

Preview-environment per test is also an option, but I'm afraid we'll hit the limits on the VMs that run Harvester very quickly. Currently we're working on improving the way we create preview-environments and we'd (probably) have an option to run on other VMs (GCE/EC2 etc), which could be a viable option for that use case. Until then I would recommend against it.

I would suggest against the 3rd option as it sounds like you could end up with race conditions, for which you'll have to control and your code will become more complicated.

**Comment by kylos101** [comment]
My vote would be to try this:
```
If you need more resources for the VM you can run the preview environment with -a with-large-vm=true, which would give you a VM with double the resources - 6 -> 12 CPU and 12 -> 24 GB RAM.
```

And then try running tests in parallel, to see what the outcome is.

**Comment by kylos101** [comment]
@utam0k will leave in the inbox for now, please focus on existing groundwork (scheduled status). :pray:

**Comment by utam0k** [comment]
@vulkoingim I didn't know `with-large-vm` option. Great! Thanks.

**Comment by kylos101** [comment]
Added to breakdown. @utam0k , could you add a proposed definition of done, and socialize in the next refinement?

**Comment by kylos101** [comment]
@utam0k Iinked the draft PR to this issue 🙏
