### ISSUE TITLE
[preview environments] unstable network led to many workarounds in integration tests

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#13193]
### Bug description

:wave: hey there Platform team, in https://github.com/gitpod-io/gitpod/issues/12248, we found it necessary to make many code changes to make the integration tests and related port-forwarding more fault tolerant of unstable network conditions.

I'm not sure if the problem is exclusive to Harvester, or core-dev in GCP, or both, and wanted to give you a heads up. For example, this might impact @geropl and @akosyakov when they dedicate energy to integration tests for WebApp and IDE.

cc: @corneliusludmann , I'm not sure if you run integration tests in Harvester preview environments.

### Steps to reproduce

Run integration tests for webapp or ide, they may experience disconnects.

### Expected behavior

The network for preview environments should be more stable

### Anything else?

Not sure if this is impacting any other werft jobs

The result of test runs is share [internally here](https://gitpod.slack.com/archives/C03E52788SU)

**Comment by utam0k** [comment]
This often happened during [the context test](https://github.com/gitpod-io/gitpod/blob/main/test/tests/workspace/contexts_test.go).
