### ISSUE TITLE
Epic: schedule outage windows to support in-place upgrades

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#13191]
## Is your feature request related to a problem? Please describe

Outage window user defined messages are not visible in the Gitpod dashboard or from the IDE, and cannot be scheduled via the administration view. Additionally, manual intervention is required to honor an outage window (stop running workspaces & disable start of new workspaces).

## Describe the behaviour you'd like

As an administrator, I'm able to use the administration view to create a window of time where:
1. Running workspaces are stopped
2. Workspace start is disabled
3. A user defined message, defining the outage can be set

As a user:
1. My active workspaces will stop, and I'll see a message why in the IDE.
2. From the dashboard, I can see an outage message indicated why workspaces cannot be started
3. I cannot start new or existing workspaces 

## Describe alternatives you've considered

Instruct administrators to:
1. Message their users sharing the outage window
2. At the start of the outage, stop all workspaces with kubectl, this will force shutdown and graceful backup
3. Once all workspaces are stopped, scale ws-manager to zero
4. Do the upgrade
5. scale ws-manager up from zero
6. Message users that they may start new and existing workspaces again
7. FYI, users will not see any communication in-product for the outage

## Additional context

Not sure how this would be different for handling within the IDE for JetBrains or VS Code.

**Comment by mrzarquon** [comment]
Implementation wise, I'd want to be able to announce a maintenance window ahead of time. So in the current admin view, having a maintenance window section and option to define a time (ie, Tuesday 9am UTC until 11am UTC), would correspond to an end user on the US West Coast seeing "Gitpod will in maintenance from 1am until 3am Tuesday, your workspaces will be halted and you will not be able to launch them until after the maintenance completes". This Could also be injected into the shell message of the day when users launch a new workspace, popup via the gitpod extensions, etc.

**Comment by lucasvaltl** [comment]
This should be an epic that will require the involvement of all other teams. I'll rename this to clarify that this is an epic :)

**Comment by lucasvaltl** [comment]
@kylos101 does it make sense to add the other teams, including workspace, to this already? We will need someone to drive this and break it down.

**Comment by kylos101** [comment]
@lucasvaltl we'd at least want webapp and workspace. Although, it would be nice to have feedback from within your IDE that is related to an outage, too. For example, to see the outage window, or that my workspace is shutting down due to an outage.

**Comment by andreafalzetti** [comment]
If we have good support for this in the dashboard we could consider not updating all IDEs to support this feature, at least for first iterations 🛹

**Comment by mbrevoort** [comment]
Is the intent to put Gitpod into maintenance mode so that Gitpod can be updated or to update the underlying infrastructure? 

If it is to upgrade Gitpod, then we should instead strive to support live upgrades that allow running workspaces to continue to run. We should seek to eliminate the need for a maintenance mode completely. If we absolutely need one we should minimize the impact to developers.

**Comment by lucasvaltl** [comment]
The intent of this was the latter - to put Gitpod into maintenance mode to allow for an update. The underlying assumption is that we won't be able to get to a state of "live upgrades" soon, and hence we need this to ease the pain of maintenance windows. @kylos101 How fair is this underlying assumption?

**Comment by kylos101** [comment]
@lucasvaltl we might want feedback from WebApp and IDE, too, I'm not sure if/how their components can do live update with the single cluster ref arch.

From a workspace perspective, to achieve live upgrades for workspace components "now", we'll need a high availability ref arch which includes governed workspace clusters (like we do with the saas). 

However, once we're on PVC with self-hosted, we should revisit the single cluster ref arch, to see if live upgrade work (because the backup and restore capabilities become fault tolerant - to avoid data loss).

**Comment by vyas-n** [comment]
Even with the live update feature, I'd still like for there to be a maintenance mode feature in Gitpod Self-hosted.

A couple of situations that I don't see live-update resolving are:
- Setting the maintenance mode for a cluster-wide change (for example, changing the default storage class for persistence volume claims)
- Migrating in-cluster gitpod dependencies to external dependencies (such as the MySQL Database or Container Registry)
- Changing the gitpod exposed service type (for example from LoadBalancer to API Gateway).

**Comment by kylos101** [comment]
Closing as this was intended for self-hosted.
