### ISSUE TITLE
[self-hosted][air-gaped] openvsx-proxy doesn't follow http 3xx redirections

### ISSUE THREAD

**Issue by Kevin-mit-C** [gitpod-io/gitpod#13206]
### Bug description

In our air-gaped environment, yust the openvsx-proxy is able to connect to https://open-vsx.org. If VSCode trys to install an extension, it can't download the extension, because of an http 3xx redirections to https://openvsxorg.blob.core.windows.net.

### Steps to reproduce

```
> curl -I https://open-vsx.gitpod.io/api/redhat/vscode-yaml/1.10.1/file/redhat.vscode-yaml-1.10.1.vsix
HTTP/1.1 200 Connection established

HTTP/1.1 302 Found
Access-Control-Allow-Origin: *
Cache-Control: max-age=604800, public
Content-Length: 0
Date: Thu, 22 Sep 2022 11:07:39 GMT
Location: https://openvsxorg.blob.core.windows.net/resources/redhat/vscode-yaml/1.10.1/redhat.vscode-yaml-1.10.1.vsix
Server: nginx
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Via: 1.1 google
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

### Expected behavior

```
> curl -I  https://open-vsx.gitpod.io/api/redhat/vscode-yaml/1.10.1/file/redhat.vscode-yaml-1.10.1.vsix
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Content-Length: 1126026
Content-Type: application/octet-stream
Last-Modified: Mon, 29 Aug 2022 13:36:30 GMT
ETag: 0x8DA89C37AFF4523
Vary: Origin
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: bc771f0a-f01e-0044-2073-cecece000000
x-ms-version: 2009-09-19
x-ms-lease-status: unlocked
x-ms-blob-type: BlockBlob
Date: Thu, 22 Sep 2022 11:10:38 GMT
```

**Comment by Kevin-mit-C** [comment]
Hey @axonasif, unfortunately, the error is not related to the open-vsx.org disorder you mentioned.

It is a malfunction of the pod openvsx-proxy when handeling http 3xx responses (https://github.com/gitpod-io/gitpod/tree/main/components/openvsx-proxy).

**Comment by axonasif** [comment]
Ah, I overlooked then, sorry about that. Reopening the issue and putting it on IDE inbox.

**Comment by jeanp413** [comment]
@Kevin-mit-C you need to configure proxy settings in your workspaces too, openvsx doesn't server actual content only the metadata, vscode will follow the redirections.
