### ISSUE TITLE
Display Timestamp When Hovering Mouse Over Start Time on Workspace Page

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#13217]
## Is your feature request related to a problem? Please describe

When troubleshooting workspace where many instances are involved it would be very helpful to see a timestamp of the start time from the latest instance ID of the workspace. This will help when comparing timestamps while looking at the database where I can see a list of all instances of a workspaces.

## Describe the behaviour you'd like

On a workspaces page within the admin dashboard there is a 'Last Start' which usually provides the 'time ago' when the workspace was last started. When going your mouse over the 'time ago' value it should show a tooltip or alt text that displays a timestamp (as stored in the database - ex. `2022-09-20T04:10:45.345Z`).

## Describe alternatives you've considered

Attempting to correlate what '3 days ago' translates to as a timestamp.

## Additional context

N/A

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3r2mi)

**Comment by geropl** [comment]
@gtsiolis What do you think? Personally I feel this would be helpful as well, but I faintly recall we discusses this at some point already. :thinking:

**Comment by gtsiolis** [comment]
@jimmybrancaccio This seems like a valid feature request. Thanks for the ping, @geropl! 🏓 

**suggestion**: Adding a tooltip on the relative date and time make sense! 

---

Pasting from a follow-up issue in https://github.com/gitpod-io/gitpod/issues/13764 to describe the general problem and how to approach a solution holistically:

> We've been using relative and absolute date and time formats across the product. For example, see [projects](https://gitpod.io/t/gitpod/projects), [members](https://gitpod.io/t/gitpod/members), and [usage](https://gitpod.io/t/gitpod/usage) for the Gitpod team in Gitpod.io.

> Generally, both absolute and relative formats can be useful depending on each use case. 💡

> 🅰️ Relative date and time can be useful when the content is updated frequently and surfacing an absolute date is not critical, etc.
> 🅱️ Absolute date and time makes sense when users would need to convert the date in order to complete a task, etc.

**Comment by jimmybrancaccio** [comment]
I think we could close this one out in favor of #13764?

**Comment by gtsiolis** [comment]
Agree! Although the scope of this issue is smaller, I believe #13764 covers the problem here and describes a more generic solution across the dashboard, which can later be broken down into smaller pieces for implementation if needed. Closing this in favor of #13764. Thanks for coming back to this, @jimmybrancaccio! 🏀
