### ISSUE TITLE
Clean up plans page in dashboard to match website pricing and page 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13229]
See https://gitpod.io/plans and https://www.gitpod.io/pricing

- Rename OPEN SOURCE with FREE
- Remove mention of Teams under the PROFESSIONAL plan (since the Teams feature is available to all users). 

#### existing content (at the time of this issue)
<img width="1232" alt="Screenshot 2022-09-23 at 10 13 23" src="https://user-images.githubusercontent.com/849592/191918805-7a174fbf-1245-44ab-b3ef-a43bb3b7392e.png">

<img width="1336" alt="Screenshot 2022-09-23 at 10 14 19" src="https://user-images.githubusercontent.com/849592/191918872-2abb5cf1-216b-4127-9d09-8a15623a4b35.png">

**Comment by gtsiolis** [comment]
@jldec Just run into this issue.

1. The Open Source plan name can be changed through Chargebee, not sure if any other checks need to take place before making this change.
2. Removing Teams on the Professional plan in the dashboard sounds good! What about the Team Plans in the website side, shall we drop this, too?

**Comment by jldec** [comment]
Thanks @gtsiolis 

1. I don't really understand the [naming logic](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/settings/Plans.tsx#L74-L79) but the dashboard should say "FREE".
2. Yes, I it's incorrect to list "Team Plans" as a feature on the Professional plan tile on the website. 

Free or Personal plan users can use the "team plans" feature to create a team plan, but they can only use that to give their team plan members' a Pro or Unleashed subscription.

**Comment by gtsiolis** [comment]
Thanks for clarifying, @jldec!

Took a stab at this by opening https://github.com/gitpod-io/gitpod/pull/13538 and https://github.com/gitpod-io/website/pull/2840. Feel free to take a look when you're free to pass these to someone on the team. 🏓
