### ISSUE TITLE
Request push failed with message: fatal: could not read Username for 'https://github.com': No such device or address 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#1322]
### Describe the bug

I was previously able to push to my repo but I'm not longer able to.

![image](https://user-images.githubusercontent.com/46004116/76846137-d9001880-6861-11ea-8cf1-977a497c48a5.png)

### Example repository

https://github.com/nisarhassan12/react-use-gesture

**Comment by AlexTugarev** [comment]
Hi @nisarhassan12 👋 
Do you see any errors on JS console?
Also, please check the state of https://gitpod.io/access-control/, have you granted write permissions?

**Comment by nisarhassan12** [comment]
Thanks, @AlexTugarev :slightly_smiling_face:  This is what my access control state looks like:

![image](https://user-images.githubusercontent.com/46004116/76849243-dbb13c80-6866-11ea-9ad5-ff6060a4b394.png)

Also, I have opened a new workspace from the same repo and it seems to work well. I think the problem was unique that workspace. I will let you know If I will see this problem in the future.

**Comment by nisarhassan12** [comment]
@AlexTugarev I'm having the same issue once again.

![image](https://user-images.githubusercontent.com/46004116/77248199-67f1a400-6c59-11ea-9889-68ecc5973b4f.png)

this is what I get in the JS Console:

![image](https://user-images.githubusercontent.com/46004116/77248234-abe4a900-6c59-11ea-98f4-948c50488f95.png)

I have not done anything with the Access Control it is the same as shown in https://github.com/gitpod-io/gitpod/issues/1322#issuecomment-600004900

**Comment by nisarhassan12** [comment]
I'm seeing this issue quite a lot and each time opening a new workspace seems to solve the problem.
![image](https://user-images.githubusercontent.com/46004116/77654994-9e019180-6f93-11ea-9ba3-967371a9f4b1.png)

My access control settings are still the same.

**Comment by nisarhassan12** [comment]
I have encountered this once again.
![image](https://user-images.githubusercontent.com/46004116/82689386-cfd16480-9c73-11ea-9dad-40f5020c476c.png)

**Comment by nisarhassan12** [comment]
It happed again:

![image](https://user-images.githubusercontent.com/46004116/83639421-1c963300-a5c4-11ea-9116-0c2033be33f0.png)

**Comment by jankeromnes** [comment]
That's unfortunate.

However, I think that pushing from the Terminal should work. (Note that in your earlier screenshot, the Terminal version failed because you tried to push to `orgin` instead of `origin`, so Git said "I have no idea what `orgin` is".)

**Comment by nisarhassan12** [comment]
@jankeromnes Many Thanks
