### ISSUE TITLE
Setting 'Usage Limit' is inconsistent

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#13243]
### Bug description

Setting the 'Usage Limit' for a newly subscribed team is inconsistent:

<a href="https://youtu.be/ZCOoxP-eNkg"><img width="600" alt="Screenshot 2022-09-23 at 15 38 42" src="https://user-images.githubusercontent.com/599268/191973041-af5cab4d-5c5d-480c-ae83-470e037fd878.png"></a>

### Steps to reproduce

1. Upgrade a team to Usage-Based
2. Set a custom Usage Limit
3. Reload the page 🎰 Usage Limit now has a different value!

### Expected behavior

The 'Usage Limit' should still have the value that you set, not some other random value.

### Anything else?

- When testing https://github.com/gitpod-io/gitpod/pull/12957, I noticed an unrelated problem: https://github.com/gitpod-io/gitpod/pull/12957#issuecomment-1255867271 -- I subscribed a new team, changed the usage limit from 100 to 200, refreshed... and my limit was suddenly **0** (with a limit reached alert) 🤔
- Then I tested something similar: https://github.com/gitpod-io/gitpod/pull/12957#issuecomment-1255869934 -- I subscribed as an individual, changed the usage limit from 100 to 200, refreshed... and my limit was suddenly **500** 🤪
- Then, I tested again on https://gitpod-staging.com (see above YouTube video) -- subscribe as a new team, change limit from 100 to 200, refresh... and suddenly my limit was **100000** 🤯

Is it somehow getting the limit from a different team? 🤔

**Comment by svenefftinge** [comment]
Looks like a race. The 1,000,000 credits are set as a default when there is no cost center.

**Comment by jankeromnes** [comment]
I can take a look at this issue while implementing https://github.com/gitpod-io/gitpod/issues/13389 👀

**Comment by jankeromnes** [comment]
I can no longer reproduce this issue. Maybe it was fixed meanwhile?

Let's close this for now, and re-open if it comes back.
