### ISSUE TITLE
Investigate including DB tables into support bundles

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#13249]
Motivation: To better be able to support customers facing issues, like it happened recently ([internal link](https://www.notion.so/gitpod/2022-8-0-Upgrade-Failure-for-Quizlet-76f58f61b4434aca87e3a525f9a5b478#86f262a6f4ed44008f4322a3bfa39227)).

Tasks:
 - [ ] Clarify what questions we want to answer (we might not want to include all tables because of size and data confidentiality concerns)
 - [ ] Implement that data capturing [here](https://github.com/gitpod-io/gitpod/blob/main/install/kots/manifests/kots-support-bundle.yaml)  @adrienthebo Might be able to help with that.

More context and material:
 - [Support Bundle HowTo](https://www.notion.so/gitpod/Analyze-a-support-bundle-dc4ca69555914b62b6dfee03a2a0e6ef)
 - [code](https://github.com/gitpod-io/gitpod/blob/main/install/kots/manifests/kots-support-bundle.yaml)

/cc  @julia-leyton

**Comment by julia-leyton** [comment]
adding @hellofromspark to follow up on this

**Comment by easyCZ** [comment]
@hellofromspark Would you be able to help us clarify what questions we want to be able to answer when we include DB tables in the support bundle? A couple of questions on this come to mind:

* Are we looking for raw data, or aggregate data? 
* What are the privacy/security concerns around exporting this data? Do we need to communicate to customers specifically which data would be exported?
