### ISSUE TITLE
Implement an init system by default

### ISSUE THREAD

**Issue by felipecrs** [gitpod-io/gitpod#1324]
How about implementing an init system, such as [s6-overlay](https://github.com/just-containers/s6-overlay)? This would make it easier for people to define background services and would let us start the database instances in the official images without the need for the final user to manually add the command in `.gitpod.yml`.

**Comment by felipecassiors** [comment]
See [this](https://github.com/felipecassiors/spring-crud/pull/1) as an example.

**Comment by svenefftinge** [comment]
Yes, it makes sense. I thin we should just treat `CMD` properly.
One open question however is, what we do about the output. I'd think this should be routed to a terminal. Also the usual contract that the container stops when the command terminates should probably not be implemented.

**Comment by felipecassiors** [comment]
About the output, maybe doesn't worth it to forward to a terminal. Gitpod's `mysql` workspace image already starts the daemon by default, and there is no output about it on the Gitpod. But it would be useful if there is a way to read the logs.
