### ISSUE TITLE
Display available/used disk space in JetBrains backend control center

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#13248]
## Description
Currently, we display workspace class and the allocated disk space, but we don't display the used/available storage. We should extend the [backend control center](https://user-images.githubusercontent.com/2318450/191988988-e800872d-e49a-4fcd-9c87-488a243c66be.png) with an additional progress bar showing the used/available disk space.

**Comment by akosyakov** [comment]
@andreafalzetti it depends on https://github.com/gitpod-io/gitpod/issues/12676

**Comment by andreafalzetti** [comment]
> @andreafalzetti it depends on #12676

thanks, I was trying to understand if there was any limitation, removing `good-first-issue` for now then.
