### ISSUE TITLE
ctrl-z does not work

### ISSUE THREAD

**Issue by timoch** [gitpod-io/gitpod#1325]
### Describe the bug
UI menu for Undo shows ctrl-w. But this will close my tab when I press it.
Changing the keyboad layout preferences does not work (original binding is ctrlcmd+z, switching to ctrl+z does not work)

### Steps to reproduce
I think it is related to my keyboard layout (be-fr). So try opening a session with that layout.

### Expected behavior
I should be able to set ctrl-z as the undo shortcut. I actually expect as a default. 
I also expect ctrl-w to not be mapped to commands as it is pre-empted by the browser and will close the entire editor tab

**Comment by timoch** [comment]
changing my keyboard layout to en-us show the Undo menu item associated with ctrl-z but it does not work either

**Comment by Kreyren** [comment]
Try changing the shortcut for the Undo in keyboard shortcuts:
![image](https://user-images.githubusercontent.com/11302521/76857544-f4fdbd00-6855-11ea-9d7b-45676b98a733.png)

**Comment by timoch** [comment]
I tried this already. using ctrl-z as an undo shortcut does not work. If I use ctrl-d for instance, it does work. 

If my keymaps.json indicates ctrl-z and I press ctrl-z. it doesn't work
If my keymaps.json indicates ctrl-z, and I press ctrl-w. it tries to close the tab
If my keymaps.json indicates ctrl-w and I press ctrl-z, **it works** (and the menu item shows ctrl-z)

This looks related to chrome or the editor handling some shortcuts in a special way and somehow getting confused with keyboard layout. 

For now the following keymaps.json works for me

[
    {
        "command": "core.undo",
        "keybinding": "ctrl+w"
    },
    {
        "command": "-core.undo",
        "keybinding": "ctrlcmd+z"
    }
]

**Comment by Kreyren** [comment]
@timoch Can you try binding it to for example `Alt+z` ? Afaik depending on your window focus management the web browser that you are using might not relay the shortcut to theia (gitpod) but instead to the web browser.

**Comment by timoch** [comment]
alt+z in keymaps.json lets me use alt+w as a shortcut and vice versa
alt+m in keymaps.json lets me use alt+, as a shortcut and vice versa 

looks like I have to convert whatever key I want from my fr-be layout to the corresponding en-us layout key in keymaps.json

**Comment by Kreyren** [comment]
> looks like I have to convert whatever key I want from my fr-be layout to the corresponding en-us layout key in keymaps.json

Seems like a gitpod/theia bug to me then :thinking:

**Comment by akosyakov** [comment]
@timoch Which input did you try undo? Editor? Git input?

**Comment by timoch** [comment]
That would be the editor. I don't remember what was going on for other
parts of the UI.

**Comment by akosyakov** [comment]
It sounds like a bug related to keyboard layout handling. cc @spoenemann

**Comment by spoenemann** [comment]
> changing my keyboard layout to en-us show the Undo menu item associated with ctrl-z but it does not work either

@timoch where have you changed the keyboard layout? In your OS or in Theia (there's a command for that)?

Could you look into your browser log? There should be an info regarding the detected keyboard layout after Theia has loaded.
