### ISSUE TITLE
Add a Hook Task Before Gitpod Workspace Termination

### ISSUE THREAD

**Issue by AymanZahran** [gitpod-io/gitpod#13263]
I am facing additional management overhead for cleanup resources after my workspace stop (Ex: Delete Okteto Cluster [Dev Environment] after deleting Gitpod Workspace)

It would be awesome to add a feature in the gitpod.yml to run tasks just before the termination of the workspace container (Similar to prebuild but before termination)

At the time being since this feature is not exists, I am deleting the resources manually or trigger a script for clean up manually

**Comment by axonasif** [comment]
Similar: https://github.com/gitpod-io/gitpod/issues/3966
