### ISSUE TITLE
Option for init submodules before building docker image

### ISSUE THREAD

**Issue by huweiATgithub** [gitpod-io/gitpod#13279]
## Problem
I have a repository whose Dockerfile lies in a submodule. 
I tried to use this file, but it says the file does not exist.
```
File xxx  does not exist in repository xxx
```
I guess this might be due to the submodule is not initialized. 

## Describe the behavior you'd like
Provide option to control workspace initialization behavior: initialize submodule before building the docker image.

## Describe alternatives you've considered
Multi-repo Workspaces might work? But I guess other repos are cloned at a later stage?

## Additional context
As docker needs context to build, so I guess before building a docker image, a repo was cloned.

**Comment by axonasif** [comment]
Hey @huweiATgithub, could you just clone the repository and initialize the submodules from a dockerfile `RUN` instruction? Here's something below that might give you an idea of how a workspace starts:
![gitpod-diagram](https://user-images.githubusercontent.com/39482679/192230020-82296070-e356-4fbf-9fc4-73efaf90cd0c.png)

**Comment by huweiATgithub** [comment]
Thank you @axonasif, the figure is clear.  
From the figure, it is unclear what is the section "preprocess a few things" before the docker build. In the figure, it seems the repo is cloned after the docker image has been built. But I think a repo needs to clone before an image is ready to be built.

As the repo is private, it is not easy to do the cloning in a safe way in a RUN instruction.

**Comment by axonasif** [comment]
Upon re-reading your issue, I understood what you meant 🙏 
Added it to our webapp team inbox to take a look into implementing it.

> From the figure, it is unclear what is the section "preprocess a few things" before the docker build.
Thanks for the feedback @huweiATgithub, it was changed to `Parse .gitpod.yml` now 👍

**Comment by axonasif** [comment]
Also, as you mentioned about the Gitpod's multi-repo feature, for the meantime [this](https://www.gitpod.io/docs/multi-repo-workspaces#delegating-configuration) might be interesting for you.

**Comment by huweiATgithub** [comment]
Thank you! It could be better if the image-building process can be customized/hooked by providing more options under `image` section.
