### ISSUE TITLE
workspace integration test failed with git ls-remote --exit-code origin main failed (exit status 2)

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#13278]
### Bug description

The workspace integration test failed with an error message 
```console
git ls-remote --exit-code origin main failed (exit status 2)
```

### Steps to reproduce

https://werft.gitpod-dev.com/job/gitpod-build-to-gc-inte-br.15

### Expected behavior

The integration test pass

### Anything else?

Related to https://github.com/gitpod-io/gitpod/pull/13241

**Comment by utam0k** [comment]
I have one question. Should this modify the test, or is this something that contentInitializer should handle (or ignore)?

**Comment by jenting** [comment]
> I have one question. Should this modify the test, or is this something that contentInitializer should handle (or ignore)?

I use Jaeger to catch the initializer sent from the server, and it does not contain the _TargetMode_ and _CloneTarget_ from the start workspace request. That's why we can't reproduce it when we open the workspace from Gitpod GUI.

For the short term, we could fix it with an integration test.

But I am thinking about the long term. We should change the workspace integration test that sends requests from integration test client -> server -> ws-manager, rather than from integration test client-> ws-manager.
After that, we could test against the real code logic, WDYT?
