### ISSUE TITLE
Support bnd

### ISSUE THREAD

**Issue by pkriens** [gitpod-io/gitpod#1327]
Would it be possible to support bnd & OSGi? Currently your Java environment does not have a classpath. I am the owner of the bnd project and am willing to do the work if you can provide guidance. I see you use visual code? Is it sufficient to add bnd to VC?

https://github.com/bndtools

Looking forward to your feedback.

**Comment by corneliusludmann** [comment]
Thanks for your interest and for offering your help.

To be honest, I'm not 100% sure what you mean. But I am sure we can figure that out together.

At first, we do not use VSCode, Gitpod ist based on [Theia](https://theia-ide.org/). However, Theia supports VSCode extensions. Gitpod supports Java as well as Maven / Gradle out of the box. You could find [more information in the docs](https://www.gitpod.io/docs/languages/java/).

I randomly picked an example OSGi / bnd project from GitHub and opened it in Gitpod: https://gitpod.io/#https://github.com/vorburger/osgi-bnd-maven-example

In this project I had to change the Java version like this:
```shell
$ sdk install java 8.0.242-open
```
After this I was able to run the [`test.sh`](https://github.com/vorburger/osgi-bnd-maven-example/blob/master/test.sh) script that runs Gradle as well as Maven. The build finished successfully.

To get language support for bnd and MANIFEST.MF files I installed [a VSCode extension](https://github.com/lgdd/vscode-osgi). I opened [the repository in Gitpod](https://gitpod.io/#https://github.com/lgdd/vscode-osgi), ran `yarn && npx vsce package`, downloaded the *.vsix file and [installed the extension in my Gitpod workspace](https://www.gitpod.io/docs/vscode-extensions/) (drag-and-drop).

> Would it be possible to support bnd & OSGi?

What kind of support are you thinking of? Maybe you has an example that you can share?

> Currently your Java environment does not have a classpath.

What do you mean with this?

Don't hesitate to ask if you have further questions.

**Comment by pkriens** [comment]
Thanks for the extensive answer. I'll take  look at Theia and will come back after I understand what the implications are.

**Comment by corneliusludmann** [comment]
I'll close the issue for now. Feel free to open it again if desired.

**Comment by jankeromnes** [comment]
Cc @vorburger and @sandared who may know better about OSGi and/or bnd in Gitpod 😇 

Also, this tutorial about using Java in Gitpod may be helpful here: https://www.gitpod.io/docs/languages/java/

**Comment by Sandared** [comment]
@pkriens when you say supporting bnd/OSGi then do you mean something like bndTools just for Theia/VSCode (which would be awesome btw!  😁) or do you mean altering the classpath at development time, so that I immediately am warned (compiler error) )when I for example try to access types within a private package?

**Comment by Sandared** [comment]
@pkriens  just out of curiosity: did you progress any further on this topic or was it dismissed?

**Comment by pkriens** [comment]
@Sandared I am afraid other shining topics took over my limited attention span :-(

**Comment by Sandared** [comment]
xD that's a very nice way to say it. If you ever hear of anyone else tackling this topic, let me know it :)
