### ISSUE TITLE
[usage] Allow more flexible time ranges

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#13288]
Currently, we only allow showing usage for the last calendar month. It would be great to default top the current billing cycle, but also allow picking arbitrary ranges. This is especially helpful when looking for patterns and outliers in the data.

Some potential widgets to explore:
- https://coreui.io/react/docs/forms/date-range-picker/#custom-ranges
- https://rsuitejs.com/components/date-range-picker/
- https://reactdatepicker.com/

**Comment by gtsiolis** [comment]
Closing as this as the first iteration for allowing flexible date selection for usage has been added in https://github.com/gitpod-io/gitpod/pull/14515.

Next steps could include:
1. https://github.com/gitpod-io/gitpod/issues/15544
2. Moving away from the fixed month-based filter, see [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1669737909843879) (internal).
