### ISSUE TITLE
High demands

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1328]
Hello Gitpod team,
I get it, with nCOVID-19, it is most likely stressful right now.  I'm opening this issue because Gitpod is being very slow.  Just trying to run a React app development server, looking at htop, all 16 of the CPUs are above 80% usage.  I can understand how it may be because people at home/in quarantine need ready-to-code environments since many can't reach their work machines, but I really need functionality here, so please, if there is anything you can do, like scale up the clusters or something, it would be greatly appreciated.  

Thank you.

**Comment by svenefftinge** [comment]
Hi, thanks for the feedback. We have noticed this situation in US cluster and will apply the required changes ASAP.

**Comment by svenefftinge** [comment]
We have moved prebuilds to its own cluster which has improved the situation significantly according to our data. Can you confirm?

**Comment by RDIL** [comment]
Yup, looking back to normal.
