### ISSUE TITLE
Research and implement versioning for reference architectures

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#13287]
Although likely less frequently over time, our reference architectures are bound to change over time. This means that customers will be on different versions of the reference architectures, and require a good upgrade experience. This means, we need to think carefully about versioning the reference architectures and related topics: 
- How to version reference architectures (this is related to https://github.com/gitpod-io/website/issues/2247 and might be solved via this as a side-effect)
- How to communicate changes from version to version
- How to clarify which version a customer is on - could we add a file to a configmap or something similar to indicate the reference architecture version? At least for the terraform?

**Comment by adrienthebo** [comment]
Adding some notes for how we could attach this (from #13327)

- Per @lucasvaltl's comment, a configmap in a non-gitpod namespace (as this information should be persisted even if the gitpod namespace is wiped
- Attached as an annotation on the nodegroup/nodes, so if an update is partially applied we can identify that a partial update may have been applied
