### ISSUE TITLE
Subcommand on the gp CLI for pinning workspaces.

### ISSUE THREAD

**Issue by akshatnarayangupta** [gitpod-io/gitpod#13297]
## Is your feature request related to a problem? Please describe
Inactive workspaces are deleted by Gitpod after 14 Days. To prevent a workspace from being deleted, you can pin it in your list of workspaces. Pinned workspaces are kept forever.

## Describe the behaviour you'd like
We are looking for ability to keep workspace for more than 14 days, without having to explicitly pin it. Is there a way to do so.  Feature request to add a subcommand on the gp CLI for pinning workspaces will be helpful.

For more context-
https://github.com/gitpod-io/gitpod/issues/12977#issuecomment-1257665937

**Comment by axonasif** [comment]
To team-ide: I assume ide team owns the `gp` CLI component even though `workspace-pinning` might be a bit webapp scoped. Feel free to readjust if needed 👍

**Comment by loujaybee** [comment]
Seems logical, thanks for raising @akshatnarayangupta !
