### ISSUE TITLE
Can not open close nor delete a workspace

### ISSUE THREAD

**Issue by vhemery** [gitpod-io/gitpod#1329]
### Describe the bug
My workspaces are stuck in a mode where I can't take any action on them.
The Open button is available but inactive.
![image](https://user-images.githubusercontent.com/7920847/77041022-6609b580-69b9-11ea-84cc-1c0a54752b08.png)

I can't delete the workspace :
![image](https://user-images.githubusercontent.com/7920847/77040961-483c5080-69b9-11ea-8739-8b51e85a79d8.png)

When I try opening it with the URL, it's stuck at Booting up phase.
![image](https://user-images.githubusercontent.com/7920847/77041095-8a659200-69b9-11ea-906a-6590cd5eb1f8.png)

The workspace is considered active, so as I have 4 workspaces in this state, I can't use my free open source subscription.

### Steps to reproduce
Always reproducible with my account.
Reprocucible with Firefox 74.0 (64 bits) (gitpod plugin installed) and Chrome Version 80.0.3987.132 (official build) (64 bits). Only the color of the disabled open button changes between Chrome and Firefox (grey with Chrome, dark blue with Firefox).
I just opened workspaces with https://gitpod.io/# prefix, then closed the corresponding windows... Then tried the same with an incorrect URL (Git repo not on Github). And finally opened other workspaces with the Gitpod button from the firefox extension.
Not sure everyone with a free open source account can reproduce it with these simple steps... And I don't have other tries left to reproduce.

### Expected behavior
Being able to either close, delete, or open one of my workspaces.

### Additional information
Share and pin functionnalities still work.
So I shared workspaces e01a6692-fcc1-48c4-a3d8-14f562a691d7 and f8196bb5-2e77-45d5-bf7b-232a90df154f in case that could help debugging.

### Example repository
These 4 workspaces bellow : (e.g. workspace e01a6692-fcc1-48c4-a3d8-14f562a691d7 )
![image](https://user-images.githubusercontent.com/7920847/77043467-e3372980-69bd-11ea-9e6d-552a6e302c29.png)

**Comment by jankeromnes** [comment]
Hi @vhemery, many thanks for reporting this issue.

This symptom (workspace status = "Unkown") indicates that our workspace manager lost track of your workspace. So it won't allow you to perform any action on it (start, stop, open, delete) in order not to lose any data (e.g. if it contained unpushed commits, we let it time out and get backed up).

This situation should resolve itself after a maximum of one hour.

Also, we had previously fixed a bug that caused our workspace manager to occasionally lose track of workspaces. I'm not sure why it is happening again, but we'll look into what's causing it and then fix it again.

**Comment by vhemery** [comment]
> This situation should resolve itself after a maximum of one hour.
It's been a day. So I don't think it will resolve itself soon.

Wouldn't it make sense to enable some options with a warning in such case ?
I mean, when I try and delete, I do expect to lose data...

**Comment by jankeromnes** [comment]
Indeed, this time it seems to be different -- we've found several workspaces stuck in "Unknown" state, and it started happening since last week's production deployment, so this is likely a new bug. Also, these workspaces don't even seem to have ever started.

> And I don't have other tries left to reproduce.

Oh, I'm sorry, I didn't notice that you were now totally unable to use Gitpod due to this bug. Many thanks for providing detail reproduction instructions -- we're using them to investigate the bug.

Meanwhile I'll try to intervene and manually get you unblocked as soon as possible.

**Comment by jankeromnes** [comment]
@vhemery FYI I've manually set your 4 "unknown" workspaces to "stopped". This should allow you to continue using Gitpod while we're fixing the underlying bug. Thanks again for your help!

**Comment by vhemery** [comment]
Thanks.
Not sure this is what triggerred the issue, but when I try restarting one of these workspaces, I get 

> Sorry, something went wrong 😓
>Error: Request createWorkspace failed with message: 5 NOT_FOUND: cannot resolve base image: not found
>
>Please file an issue if you think this is a bug. 

I also get this message when starting a new workspace on https://github.com/TypeFox/theia-workshop/tree/exercise-0 and then the workspace is also in Unknown state. So it looks like it is related to me.

On the other hand, I can start a new workspace on https://github.com/vhemery/ecf2018-theia-workshop/tree/exercise-0 without trouble. Even though I also has one of my stuck workspaces on this branch. So I'm not sure what my guess is worth...

**Comment by vhemery** [comment]
It looks to me that the behavior has changed since my last post.
Now, whenever I try again the steps which got me stuck in the first place, either everything works fine, or I get the following error

> Request startWorkspace failed with message: 5 NOT_FOUND: cannot resolve base image: not found
Please file an issue if you think this is a bug.

which occurs way faster than before. And my workspace won't open so it is not considered active.

So as far as I can tell, the bug looks closed to me (or at least it's another bug, but it is no longer blocking).
I'll let you close it in case you still have any on-going work on this issue or need to investigate more if it was fixed by side effect.

Anyway, thank you and stay healthy.
