### ISSUE TITLE
Regular load tests for Single Cluster Reference Architecture

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#13294]
We should have a process & tooling in place to load test the single cluster reference architecture regularly (e.g. at least once a quarter) with ever increasing numbers. This is to build trust and confidence with customers. 
- Way of doing load tests (best to use [loadgen](https://github.com/gitpod-io/gitpod/tree/main/dev/loadgen))
- A way of storing results such that we can compare over time. This needs to be consistent/standardised and persisted for years

**Comment by Pothulapati** [comment]
Related https://github.com/gitpod-io/gitpod/issues/12515

**Comment by Pothulapati** [comment]
👋🏼 

More points from my [experience of load testing the EKS single-cluster guides manually](https://github.com/gitpod-io/gitpod/issues/10869#issuecomment-1235529947):
### Using loadgen
- Feels best to use `loadgen`, as its being improved consistently and something we can rely on.
- The only point of concern is considering this as a complete load/scale testing suite, as it exclusively focuses on workspace lifecycle i.e starting, termination, etc and `ws-manager`(which is an important part of the Gitpod). There would still be missing parts i.e `server`, `dashboard`, etc.
### Storing results
- I think, This is an important requirement. We could use `gcs` to store the output of the runs along with the meta information like time, gitpod version, etc.
### Comparing results
- Currently, `loadgen` emits only the output of existing suite along with the time taken, etc. I'm not sure how we can use that and compare results over time. Especially, As the current loadgen testing is more `red/green` i.e given a specific load parameters, it tries and gives output if it was successful along with the time taken. Feels more like a check? 🤔 

Overall, We should be able to wire up a `loadgen` parameter into the [existing automated testing pipeline](https://www.notion.so/Self-hosted-automated-preview-and-test-pipelines-fdc5a202e67b4197aa00d93b98d57927), which when given a input config yaml, runs the load gen and shows the output in a werft job while also saving it in a file (along with metadata) into gcs for future usage. WDYAT?
