### ISSUE TITLE
Calling `git clone` in a workspace startup task cannot use credentials

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#133]
**Describe the bug**
When using git clone in a startup task (i.e. as configured in the `.gitpod` file), one cannot clone private repositories because the Git credentials are not available. Git will as for a username/password.
This functionality might be needed to e.g. clone a separate tool repository which is not a submodule.

**To Reproduce**
Create a workspace with a `.gitpod` file that tries to clone a private repository as startup task.

**Expected behavior**
The private repository should be cloned as part of the workspace startup.

**Comment by AlexTugarev** [comment]
@svenefftinge would it be an acceptable limitation for startup tasks to wait for an initialized frontend?

**Comment by svenefftinge** [comment]
I think we should consider talking to the server from the backend
