### ISSUE TITLE
502 issue on supervisor

### ISSUE THREAD

**Issue by julienmarie** [gitpod-io/gitpod#13300]
### Bug description

Open Workspace stuck

### Steps to reproduce

Launch workspace.
I get 502 on https://julienmarie-bonoboom-lucynkfxy3g.ws-us67.gitpod.io/_supervisor/v1/status/supervisor and link to open in VSCode never appear.
I can connect throught SSH though

**Comment by pawlean** [comment]
Hey @julienmarie! 👋 I just checked your account and it looks like this workspace is no longer stuck in stopping. Is this still an issue?
