### ISSUE TITLE
Setting Email Address With '+' Under Settings > Account Fails to Update Git Configuration in Workspace

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#13323]
### Bug description

When I go to Settings > Account and set the email field to something like `jimmy+test@mydomain.com`, spin up a new workspace and look at what the value is by running `git config user.email` I see it does not include the `+`. It looks like somewhere along the line of creating the workspace we're failing to handle the `+` symbol properly.

### Steps to reproduce

There's a couple weird things going on here...

1. Go to Settings > Account and change the Email field to something like `yourname+test@test.com`. Observe after hitting the Update button you still see the new email address you just entered (including the `+`) in the Email field.
2. Spin up a new workspace.
3. In a terminal enter in `git config user.email`. Observe that what is displayed is what was in the email field prior to adjusting it.
4. In the follow command use the same email address you put in with the `+` symbol on Settings > Account page, for example - `git config user.email "yourname+test@test.com"`.
5. Now run `git config user.email` and observe that you see the email address you just set which includes the `+` symbol. This means Git can be configured with plus addresses.

--

Another thing I found while testing this (and I create a new issue for this if preferred):

1. Go to Settings > Account and hopefully the Email field is set to an address without plus addressing.
2. Change the email address to one with a `+` - ex. `yourname+test@test.com`. Hit Update and observe the message that it was updated.
3. Change the email to something different without using a `+` - ex. ilovetocode@example.com and hit the Update button again. Observe the message that things were updated.
4. Change the email one more time to something different but use a `+` in the email address this time - ex. `firstname+lastname@gmail.com`. Hit update and observe the message that things were updated.
5. Spin up a new workspace and once it's available type in terminal `git config user.email`.
6. Observe the output is the original email address you saw in step 1.

### Expected behavior

I would expect that since using a `+` in an email address is valid that it would show up in the workspace when I run `git config user.email` in a terminal or make commits.

### Anything else?

N/A

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3r51m)

**Comment by JesseRigon** [comment]
This is especially important in that github creates a public facing email for git commits if you choose to keep your email private. This generated email includes a plus and there is no option on github to modify the generated email that I can see.

My support ticket is actually the reason this issue was posted and its surprising to me that this github private email issue has never previously occured.

**Comment by JesseRigon** [comment]
I've worked around this for now using the dotfiles repo feature. This works, but I use gitpod.yml and this is the only thing in this repo so even though this works I don't think it devalues the bugs importance.

FYI, what doesn't work is using gitpod variables. The special character email bug is present there as well. This is assuming the hierarchy of importance for pulling variables goes Accounts Page -> GitPod Variables -> dotfiles repos -> local .env files. I could be wrong about that order.

**Comment by narumincho** [comment]
This problem still occurs today.

**Comment by axonasif** [comment]
@narumincho try working around with dotfiles https://www.gitpod.io/docs/configure/user-settings/dotfiles
