### ISSUE TITLE
Set gitpod team CostCenter to Stripe

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#13347]
[Context](https://gitpod.slack.com/archives/C02EN94AEPL/p1664186143718479)

**Comment by jankeromnes** [comment]
Thanks for cutting this ticket! I've updated our Usage Limit from 200 000 to 150 000, and this fixed our team's CostCenter billingStrategy:

<img width="1199" alt="Screenshot 2022-09-27 at 10 30 21" src="https://user-images.githubusercontent.com/599268/192475814-125465ef-ced1-469c-8baf-64eeeef38a44.png">

**Comment by jankeromnes** [comment]
Side note: While the CostCenter billingStrategy got fixed, the change caused an invoice finalization that reset the current monthly balance for team Gitpod.

To get accurate numbers sent to Stripe again, we needed to undo the invoice finalization. See also [Slack](https://gitpod.slack.com/archives/C027AUU7BC3/p1664270891147159?thread_ts=1664269991.720149&cid=C027AUU7BC3) (internal).
