### ISSUE TITLE
We are having trouble parsing your context Error: NotFoundError

### ISSUE THREAD

**Issue by Jazzthedog** [gitpod-io/gitpod#1334]
### Describe the bug

We are having trouble parsing your context
Error: NotFoundError

### Steps to reproduce

Just logged in to try this service.

**Comment by svenefftinge** [comment]
Is this reproducible? Can you explain what exactly you are doing?

**Comment by Jazzthedog** [comment]
Hello,

It was just my first attempt to try to log in. Nothing really special.I am
using
chrome latest version. I will use another profile and disable all my
extensions and try again. Thanks.
