### ISSUE TITLE
Imposible to build workspace

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#1335]
This repository has been working since more than a year ago, today its giving me a message:
```bash
Error: build failed: rpc error: code = NotFound desc = base image does not exist: eu.gcr.io/gitpod-dev/workspace-base-images/github.com/breatheco-de/projects:001dac947f73f916c94340944551a4a2b1cc3298@sha256:138d1b78f3f0b67cb083b76b4d1b0eaccf6dc3a5e3a3203c71f37ef201791734
Please file an issue if you think this is a bug.
```
This is the workspace:
https://gitpod.io/start/#d197e52b-7f45-4b3a-a644-f1a46f45ace0

What could this be? 🤔

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/77238506-9494b580-6b9e-11ea-8ca8-a72f2cab40d6.png)
Can you give the link to the repo?

**Comment by alesanchezr** [comment]
Of course: https://github.com/breatheco-de/projects

**Comment by JesterOrNot** [comment]
Can you show a screenshot of the error?

**Comment by alesanchezr** [comment]
![Screen Shot 2020-03-21 at 10 02 08 PM](https://user-images.githubusercontent.com/426452/77241430-50b6a600-6bc8-11ea-8084-6d02d5668d7a.png)

**Comment by JesterOrNot** [comment]
That's odd, it works for me 🤔 

![image](https://user-images.githubusercontent.com/50386709/77242599-249e2380-6bce-11ea-91ac-a65ce612aa46.png)

**Comment by alesanchezr** [comment]
Maybe it's a us problem? 🤔Usually the US servers seem less stable.

**Comment by alesanchezr** [comment]
Ok I tried opening again and it works, its just the old workspace that is broken who knows why. Thank you!!!
