### ISSUE TITLE
Gitpod to support a --minimal option

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1336]
Create a `--minimal` command line flag for `gp init` that would generate the following

`.gitpod.yml`
```YAML
image:
  file: .gitpod.Dockerfile

```

`.gitpod.Dockerfile`
```Dockerfile
FROM gitpod/workspace-full

USER gitpod

```

`-m` could be the shorthand flag.

**Comment by svenefftinge** [comment]
FWIW I wouldn't expect a dockerfile with `--minimal`.

**Comment by JesterOrNot** [comment]
Just added the flag :)
