### ISSUE TITLE
[supervisor] Processes started in terminals do not get a SIGTERM signal on stop

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#13365]
We only SIGTERM the main process of the terminal and rely on propagation which doesn't seem to happen with the interactive bash processes.

We need to make sure we SIGTERM all the processes started within the terminals before SIGTERMING the main process.

**Comment by geropl** [comment]
> the main process

Asking for clarification: You mean the root process of the (user-visible) workspace , right? Is that`supervisor`?
