### ISSUE TITLE
Base usage measurement on `stoppedTime`

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#13369]
We are currently using `stoppingTime` but we should use `stoppedTime` as the time it takes to stop a workspace depends on the size of a workspace. Also, we are introducing `terminationGracePeriodSeconds` property to extend the stopping time [[ref](https://github.com/gitpod-io/gitpod/pull/13352)].

**Comment by geropl** [comment]
> Also, we are introducing terminationGracePeriodSeconds property to extend the stopping time

Jep, I think this in itself is worth the change.

**Comment by jldec** [comment]
**Clarification**

- _StoppingTime_ -> Time at which the user clicked stop and we started the process of stopping a workspace
- _StoppedTime_ -> Time at which the workspace completed stopping, including any shut-down (and possibly stop tasks defined by the user)

How can users minimize the time needed for stopping?

(We should not charge for the stopping process if this time is largely out of control of the user. )

**Comment by easyCZ** [comment]
In the default case, when there is no extra "work" specified by the user to be done they do nothing.

In the case where stopping tasks are introduced (https://github.com/gitpod-io/gitpod/issues/3966, https://github.com/gitpod-io/gitpod/issues/13263), the user controls how much work is done in those tasks and hence how long those tasks take.

**Comment by jldec** [comment]
@geropl, @svenefftinge do you agree with the summary above that this change is primary for "end-tasks" (#3966) which are under user-control, and should not significantly impact other users?

**Comment by svenefftinge** [comment]
It's also a function of how big the backup is (at least currently)

**Comment by svenefftinge** [comment]
It still seems a little unclear of what event is best to use for measuring the session end. I suggest we postpone this change until we are clearer.

**Comment by svenefftinge** [comment]
I'm closing this for now.

**Comment by gtsiolis** [comment]
For more context and future reference, here's a link to the relevant line of code for this:

https://github.com/gitpod-io/gitpod/blob/460ccb0981fcf04363e0d8feb93fa39258e5e03a/components/usage/pkg/apiv1/usage.go#L371-L374

See also [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1676036629139909) (internal).
