### ISSUE TITLE
Workspace timeout with SSH connection

### ISSUE THREAD

**Issue by mittalyashu** [gitpod-io/gitpod#13370]
### Bug description

I've SSHed into Gitpod workspace using Jetbrains Gateway SSH provider.

The Jetbrains Client started indexing in the background, while I was coding.

But the workspace just timeout-ed assuming no one is working on it.

---

Not sure if this part plays any role, but even just by enabling this it should keep the workspace from not stopping.

<img width="536" alt="CleanShot 2022-09-27 at 18 43 35@2x" src="https://user-images.githubusercontent.com/29014463/192536201-4e8dfa8a-0314-4cb9-a29f-a2325dfc6ea1.png">

### Steps to reproduce

1. Create a Gitpod workspace
2. Use Jetbrains Gateway SSH provider _(choose a project which is big)_
3. Continue working on it, until workspace automatically stops

### Expected behavior

Not sure if this issue is workspace specific. 🤷 

### Anything else?

I just have to use VSCode to get the work done.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3r77u)

**Comment by axonasif** [comment]
Hey @mittalyashu, please also follow https://www.gitpod.io/docs/troubleshooting#gitpod-logs-in-jetbrains-client

**Comment by mittalyashu** [comment]
I've sent the logs on support email, but I am generating these logs after 19 hours, I am not sure if this attachment will contain the logs of the current issue. 🤷‍♂️
