### ISSUE TITLE
Adjust cost centers and usage limits depending to spec

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#13389]
For un-upgraded cost centers (i.e. not Stripe customer), the usage limit should be:
- **500 credits** for individiual users (the free tier)
- **0 credits** for teams

These should also not be customizable (hard usage limit).

Then, for upgraded cost centers (i.e. Stripe customers), the usage limits should default to:
- **1000 credits** for individual users (customizable, but you can only set it to >= 1000 credits)
- **1000 credits * team members** for teams (customizable to any value)

**Comment by jankeromnes** [comment]
In addition to the customizable / non-customizable / minimum value specs mentioned above, there is a suggestion by @svenefftinge to always ask new Stripe customers what limit they want when they sign up:

> Would it be better to ask the user what spending limit they want when they create a team? Hardcoding this in the backend doesn't seem to make so much sense, as e.g. the spending limit for teams greatly varies with the team size.
I've put the defaults into the usage component because of the get-or-create semantic of cost centers. But they will always be created as `billingStrategy: other` and Stripe cost centers are always created by users, so we can also pass the spendingLimit. Happy to discuss

I guess this requires further alignment on what we do by default; what we ask for and when; and how we enforce the minimum / non-customizable values.

**Comment by easyCZ** [comment]
While doing this, it would be great to do it in a such a way that it complements the other scheduled issue in the current sprint - https://github.com/gitpod-io/gitpod/issues/13198 - that is move more of the handling logic to usage.

**Comment by jankeromnes** [comment]
Fixed in https://github.com/gitpod-io/gitpod/pull/13746 and https://github.com/gitpod-io/gitpod/pull/13798
