### ISSUE TITLE
Add additional JAEGER_TAGS and JAEGER_SERVICE_NAME env vars

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#13385]
## Is your feature request related to a problem? Please describe

No

## Describe the behaviour you'd like

Add additional labels with information about the component and version of the installer.
An additional dynamic value would be great (like ws-us68)

https://www.jaegertracing.io/docs/1.38/client-features/

## Describe alternatives you've considered

Use kubectl patch to append the variables.

## Additional context

- Related to #13381

**Comment by lucasvaltl** [comment]
@aledbf could you provide a bit more info on this - where do you want this option to live? Is this about the installer?

**Comment by aledbf** [comment]
@lucasvaltl sorry, yes, someplace in the installer where we can set this and propagate it to all the components.
