### ISSUE TITLE
Add additional security to admin panel access

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#13397]
## Is your feature request related to a problem? Please describe
Today the admin panel lives on the same API endpoint as the remainder of functionality. While guarded by resource and function scopes, we would benefit from additional layers of security.

Key concerns with the current state are that spear phishing/social engineering or impersonation (someone stealing the session somehow) attacks.

Note: this is not insecure today, and there is potential for improving it.

## Describe the behaviour you'd like
Many means to mitigate these issues are conceivable:
- add _Multi Factor Authentication_ to admin access, i.e. all admin RPC calls require a second factor,

  > **Note**
  > Today all Gitpod employees are required to use MFA to access any resource. We enforce MFA on all our GitHub and Google accounts.

- add _Multi Person Authorisation_ to modifying operations,
- move the admin RPC calls to a different endpoint, potentially inaccessible from the open internet. Other means of making this accessible include Tailscale or Teleport (both of which would provide MFA). There is opportunity here with the public API effort (cc @geropl, @easyCZ)

**Comment by csweichel** [comment]
A reasonably simple skateboard for implementing MFA and the different endpoint would be to move the admin panel behind [Teleport](https://goteleport.com/docs/architecture/proxy/). We'd disable the /admin route and admin RPC calls on the main interface, and require that to be accessed on a different port which would only be available through teleport.

**Comment by MrSimonEmms** [comment]
@csweichel as is now my catchphrase, "how would that affect self-hosted?"

Teleport is fine for gitpod.io, but all Gitpod instances have an /admin endpoint. I'm not against there being a different solution for non-SaaS, but it is a consideration.
