### ISSUE TITLE
Unable to open current workspace on gitpod

### ISSUE THREAD

**Issue by kescardoso** [gitpod-io/gitpod#1339]
### Describe the bug
Workspace status shows as "Stopping", and "Stop" and "Open" buttons are unclickable.

### Steps to reproduce
I refreshed my workspace after coming from my lunch break and I was then unable to reopen it again from the list of workspaces

### Expected behavior
I should be able to restart it as I normally do and continue to work on my code

### Additional information
e81f0a06-967f-453e-9140-4e6e95fd7fae
kescardoso/mongodb 
2ae920c1

### Example repository
https://github.com/kescardoso/mongodb/commits/2ae920c1

**Comment by kescardoso** [comment]
<img width="1164" alt="Screenshot 2020-03-23 at 16 00 00" src="https://user-images.githubusercontent.com/47559909/77330259-5e327400-6d1f-11ea-8b9b-8bb7591b3a69.png">

**Comment by svenefftinge** [comment]
Thanks for reporting it. We are looking into this.

**Comment by svenefftinge** [comment]
This is now fixed.
