### ISSUE TITLE
Gibberish after builds in gitpod terminal

### ISSUE THREAD

**Issue by mteam88** [gitpod-io/gitpod#13408]
### Bug description

After starting a gitpod workspace (usually not for the first time) I sometimes (usually) see something like the following:
```
jq: error: Could not open file /workspace/.vscode-remote/data/Machine/.tmp: No such file or directory
jq: error (at /workspace/.vscode-remote/data/Machine/.tmp:0): object ({"python.de...) and null (null) cannot be multiplied
rm: cannot remove '/workspace/.vscode-remote/data/Machine/.tmp': No such file or directory
jq: error: Could not open file /home/gitpod/.vscode-server/data/Machine/.tmp: No such file or directory
jq: error (at /home/gitpod/.vscode-server/data/Machine/.tmp:0): object ({"python.de...) and null (null) cannot be multiplied
rm: cannot remove '/home/gitpod/.vscode-server/data/Machine/.tmp': No such file or directory
```
Just above the prompt in the terminal.
![image](https://user-images.githubusercontent.com/84196639/192768795-eae76b2f-91a7-4985-90f9-09b273e299f6.png)

### Steps to reproduce

Not sure if it is happening for other users... I just opened a workspace for the second time.

### Workspace affected

mteam88-keyswarm-rzh921czcr2

### Expected behavior

Just a regular terminal.

**Comment by mteam88** [comment]
Love all the 👍, but anyone have the same issue?

**Comment by chuck-confluent** [comment]
Yes, it's happening to me too. I could assume the thumbs up are folks who, like me, have come to the issues and searched for "jq error"

**Comment by david-bakin** [comment]
I get this for a _new_ workspace on a repo that has no `.gitpod.yml`.  (Just one repetition of `cp:`, `rm:`, `jq:` though.)

There _is_ a dotfile repo though - but it is at a commit that really has nothing in it at all - https://gitlab.com/bakins-bits/dotfiles-gp/-/tree/c54704461cde7e157c81c0d5c2cb466e04ca684b

**Comment by axonasif** [comment]
Sorry for the inconvenenice folks, it should get fixed after https://github.com/gitpod-io/workspace-images/pull/928 is merged.

**Comment by mteam88** [comment]
@axonasif Can you explain what the issue is?

**Comment by axonasif** [comment]
@mteam88 the python chunk in our workspace images tries to add configuration to the Machine settings of VSCode, which fails sometimes to due the missing parent directory and the lack of error handling. The mentioned PR above aims to address that.
