### ISSUE TITLE
Support SSH and agent forwarding in the VS Code extension

### ISSUE THREAD

**Issue by florisvdg** [gitpod-io/gitpod#13418]
## Is your feature request related to a problem? Please describe

SSH agent forwarding [works great now](https://github.com/gitpod-io/gitpod/issues/6993) with Gitpod. This lets me use SSH within my remote Gitpod workspace, including Git commit signing (🎉), without the private key ever leaving my local device (🎉). This works great, but I can only get it to work if I use the `Connect via SSH` option and then add the `-A` flag.

I can't get it work when using the Gitpod VS Code extension in my local VS Code app. If I try that and then open a terminal in VS Code, all my SSH requests fail (and `SSH_AUTH_SOCK` is not set).

## Describe the behaviour you'd like

I'd like for the Gitpod VS Code extension to connect to workspaces over SSH and allow me to enable SSH agent forwarding as well. Either in the `settings.json` and/or by reading my SSH config.

## Describe alternatives you've considered

I stopped using the Gitpod VS Extension now and I'm using the [Visual Studio Code Remote SSH extension](https://code.visualstudio.com/docs/remote/ssh) instead. This actually works pretty well, but takes a few additional steps to set up and to maintain:

First I have to copy the `Connect via SSH` command and add the `-A` flag to it.

Then I have to run `Add New SSH Host…` and then I paste it in, which adds it to my local SSH config.
<img width="601" alt="image" src="https://user-images.githubusercontent.com/7430639/192844580-f7b4fff2-e1a6-4587-974b-7f857314084a.png">

Then I have to run `Connect to Host…` and select my new Gitpod workspace.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/7430639/192844762-fd36b365-f5d6-490a-95dc-4b225893d46e.png">

And then I have to manually navigate to `/workspace/<my workspace name>`.

If I then open a terminal, SSH & commit signing works great, but I do miss the 'magic' of the native Gitpod VS Code extension.

Also, if the workspace closes I can't connect to it anymore and I need to manually start it again.

**Comment by jeanp413** [comment]
@florisvdg Gitpod extension delegates ssh connection to the MS remote - ssh extension so agent forwarding should just work if you configure it in your `~/.ssh/config` file
Try something like this
```
Host *.gitpod.io
    ForwardAgent yes
```

**Comment by florisvdg** [comment]
Ah, now I got it to work! I did have that snippet already in my SSH config, but what the issue was is that when opening a workspace, VS Code tries to recover the previous shell, which had stale environment variables. Exiting it and creating a new one fixed it for me. Could be nice to mention this caveat in the docs as well.
