### ISSUE TITLE
Is it possible to run Docker CLI (for example, 'docker run hello-world') inside Gitpod?

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#1342]
If so, how?

Transferred from https://github.com/eclipse-theia/theia/issues/7427

**Comment by JesterOrNot** [comment]
Sorry no, See #52

**Comment by escalonn** [comment]
Isn't the answer yes, so long as the docker context/host is remote? The Docker CLI is just a CLI.

**Comment by jankeromnes** [comment]
This is currently being implemented in Gitpod, and will become possible soon.

Duplicate of https://github.com/gitpod-io/gitpod/issues/52
