### ISSUE TITLE
Add AWS and Azure CLIs to Gitpod workspace

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#13441]
Now the expectation for testing of Self-Hosted releases has shifted from the sole responsibility of the Self-Hosted test to every team, the AWS and Azure CLIs should be installed to the base Gitpod Docker image.

These are used to get Kubeconfig files for the test clusters

**Comment by adrienthebo** [comment]
Does [this](https://github.com/gitpod-io/gitpod/blob/main/dev/image/Dockerfile#L183-L189) cover the need for AWS?

**Comment by MrSimonEmms** [comment]
Yeah, looks like it. So, just Azure necessary then
