### ISSUE TITLE
[Self-Hosted][KOTS] Registry connection preflight check sending false positive

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#13446]
### Bug description

Registry connection preflight check sending false positive when using Artifactory. Note that in theory, artifactory is [not officially supported](https://www.gitpod.io/docs/references/compatibility?admin). 

This also might be the case when using Gitlab

### Steps to reproduce

Spin up artifactory, use it in the Gitpod installation, run preflight checks. See if test comes back as failed. Install anyways, and see if images can be built and pushed.

**Comment by MrSimonEmms** [comment]
I believe this is also the case when using GitLab
