### ISSUE TITLE
can not install metrics-server

### ISSUE THREAD

**Issue by sinycn** [gitpod-io/gitpod#13453]
### Bug description

10:20:09 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | metricsserverBaseC...erverChart21822EB5
Received response status [FAILED] from custom resource. Message returned: Error: b'Release "metrics-server" does not exist. Installing it now.\nError: chart "metrics-server" version "5.10.10" not found in https://charts.bitnami.com/bitnami repository\n'

### Steps to reproduce

make install 

### Expected behavior

the code in metrics-server.ts 
export class MetricsServer extends cdk.Construct {
    constructor(scope: cdk.Construct, id: string, props: StackProps) {
        super(scope, id);

        const cluster = importCluster(this, process.env.CLUSTER_NAME);

        const helmChart = cluster.addHelmChart('MetricsServerChart', {
            chart: 'metrics-server',
            release: 'metrics-server',
            repository: 'https://charts.bitnami.com/bitnami',
            namespace: 'kube-system',
            version: '5.10.14',
            wait: true,
            values: {
                hostNetwork: true,
                apiService: {
                    create: true
                },
                extraArgs: {
                    'v': '2',
                    'kubelet-preferred-address-types': 'InternalIP, ExternalIP, Hostname'
                }
            },
        });
    }
}

mean that the version is 5.10.14 

### Anything else?

but the cloudformation shows version "5.10.10" is not found , iam confused,why cloudformation get the metrics server version 5.10.10 it is not set in code

**Comment by lucasvaltl** [comment]
Closing issue as the EKS guide is deprecated in favour of the reference architectures. Please see [EKS guide readme ](https://github.com/gitpod-io/gitpod-eks-guide)for more information.
