### ISSUE TITLE
Admin user list page is slow to open on gitpod.io, creating friction for admins 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13458]
Since #13161 the user list page is auto-populated (no search required) but this takes 20 or more seconds on gitpod.io, making it hard to open the admin console without waiting.

cc: @svenefftinge as author of #13161

**Comment by gtsiolis** [comment]
@jldec is this a duplicate of https://github.com/gitpod-io/gitpod/issues/13334?

**Comment by jldec** [comment]
I also noticed that starting a search while the intial open-page query is still in progress will cause the search input to be lost and the search results to be replaced by the default (empty) results of the intial page load.

**Comment by jldec** [comment]
sigh - thought I did a search before creating this one... 
duplicate - closing
