### ISSUE TITLE
Workspace pre-build seems to be taking quite long due to pod is pending

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#1345]
### Describe the bug

Workspace pre-build seems to be taking quite long and this is what is showing up

![image](https://user-images.githubusercontent.com/46004116/77662837-2dac3d80-6f9e-11ea-9828-6e9a6ef7ca91.png)

**Comment by svenefftinge** [comment]
This has been fixed and deployed to production.
