### ISSUE TITLE
.gitpod.yml tasks won't be created for a tag branch context

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#13489]
### Bug description

When you open a repo's tag(branch), the "tasks" in ".gitpod.yml" won't be created/started.
The variable `$GITPOD_TASKS` doesn't exist either.

### Steps to reproduce

- Open https://gitpod.io/#https://github.com/logto-io/logto/tree/v1.0.0-beta.10
- Notice that no task terminals were created.
- Also notice that the env variable `$GITPOD_TASKS` doesn't exist either. (`env | grep GITPOD_TASKS`)

### Expected behavior

- Gitpod should understand the context of a tag branch and parse `.gitpod.yml` accordingly.

### Example repository

https://gitpod.io/#https://github.com/logto-io/logto/tree/v1.0.0-beta.10

### Anything else?

Originally reported via an user at [discord.](https://discord.com/channels/816244985187008514/1025285232020160552)

**Comment by wangsijie** [comment]
Is there any updates?
