### ISSUE TITLE
[BitbucketServer] Prebuilds are broken on branch context

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#13486]
### Bug description

We see a blocker for prebuilds on branches of BBS repositories. 

Given a context URL like `https://bbs.server.com/projects/proj1/repos/repo1/browse?at=refs%2Fheads%2Ffoo`, the context parser computes `refs/heads/foo` as value for `ref`, which is fully qualified and might be necessary for API calls, but it's apparently wrong for git operations. 

Git initializer fails with: 
```
cannot initialize workspace: cannot initialize workspace: git initializer clone: git checkout -B refs/heads/main origin/refs/heads/foo failed (exit status 128): fatal: 'origin/refs/heads/foo' is not a commit and a branch 'refs/heads/foo' cannot be created from it
```

Using the branch name from `refs/heads/<branchName>` should work, though remains to be verified.

Also, for the context, if subsequent API calls would also work with `?at=foo`, it could be simplified in the context parser, otherwise we need to check the params for prebuild manger which is called by the BBS application. 

### Steps to reproduce

1. (BBS) Create a repo and a new branch from default branch.
2. (Gitpod) Create a project for that repo. And make sure the repo is gitpodified, e.g. there is a .gitpod.yml included.
3. Try to run a prebuild from the branch.

**Comment by jmls** [comment]
this is a real problem with us for one of our customers .. please can we have some feedback on this

**Comment by jldec** [comment]
@jmls we're looking at this - can you confirm that this is only an issue with Bitbucker Server (not bitbucket.org cloud).

**Comment by jmls** [comment]
@AlexTugarev awesome ! thanks - any expectation of eta so I can inform the customer ?

**Comment by AlexTugarev** [comment]
@jmls, I'll try to verify that workspaces do start as expected for branch contexts once the running deployment is done, then post an update here.

**Comment by AlexTugarev** [comment]
@jmls, it looks good now. I could start workspaces for branch URLs.

**Comment by jmls** [comment]
thanks, will let the customer know
