### ISSUE TITLE
Update onboarding IDE selector

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#13497]
Nice catch, @andreafalzetti! Agree, let's go with a boring (simple) MVC fix like the two rows of four for now. 🤝 

```diff
diff --git a/components/dashboard/src/settings/SelectIDEModal.tsx b/components/dashboard/src/settings/SelectIDEModal.tsx
index e24318a74..dde3e3504 100644
--- a/components/dashboard/src/settings/SelectIDEModal.tsx
+++ b/components/dashboard/src/settings/SelectIDEModal.tsx
@@ -44,7 +44,7 @@ export default function (props: SelectIDEModalProps) {
             visible={visible}
             onClose={handleContinue}
             closeable={true}
-            className="_max-w-xl"
+            className="max-w-2xl"
             buttons={<button onClick={handleContinue}>Continue</button>}
         >
             <p className="text-gray-500 dark:text-gray-400 text-base pb-3">
```

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="Screenshot 2022-09-30 at 5 05 18 PM (2)" src="https://user-images.githubusercontent.com/120486/193287749-082c6528-7c4a-4028-b5f1-5d30f8a73e70.png"> | <img width="1440" alt="Screenshot 2022-09-30 at 5 05 31 PM (2)" src="https://user-images.githubusercontent.com/120486/193287761-50f68529-6651-4592-98e5-28424fd43c8c.png"> |

_Originally posted by @gtsiolis in https://github.com/gitpod-io/gitpod/issues/13488#issuecomment-1263623639_

**Comment by Siddhant-K-code** [comment]
I can take that up 🙋‍♂️

**Comment by measutosh** [comment]
Hi @andreafalzetti , I have modified the code as suggested above, raised a PR [13557](https://github.com/gitpod-io/gitpod/pull/13557).
Please have a look.

Thanks

**Comment by measutosh** [comment]
> Hi @andreafalzetti , I have modified the code as suggested above, raised a PR [13557](https://github.com/gitpod-io/gitpod/pull/13557). Please have a look.
> 
> Thanks



> I can take that up raising_hand_man



> I can take that up raising_hand_man

hey @Siddhant-K-code ,sorry for the MR , I know it's not good to pickup an issue where someone else is working but I just saw and jumped staright into this

**Comment by gtsiolis** [comment]
It's ok @measutosh! Generally, it's best to avoid working on issues with already an assignee, but since this is a fairly trivial change and there was no open PR[[1](https://github.com/gitpod-io/gitpod/pulls/andreafalzetti)] from @andreafalzetti, let's move forward with the changes in https://github.com/gitpod-io/gitpod/pull/13557.

@andreafalzetti I've re-assigned this to @measutosh. 🍫
