### ISSUE TITLE
Is the workspace directory partition fixed at 15gb?

### ISSUE THREAD

**Issue by Lrvineshaw** [gitpod-io/gitpod#1349]
My current project USES more than 15gb of disk space, and I tried to go to another directory for the project, but any file creation behavior prompted read-only, so does that mean I can't continue using gitpod?
![image](https://user-images.githubusercontent.com/34879145/77840071-9f120900-71b5-11ea-9a0b-fa10dac1e619.png)

**Comment by svenefftinge** [comment]
Yes, we have put in this limit. Could you elaborate what kind of project it is and why it is consuming that much disk space?

**Comment by Lrvineshaw** [comment]
> Yes, we have put in this limit. Could you elaborate what kind of project it is and why it is consuming that much disk space?

An image smart recognition project that I'm currently working on myself does use a lot of libraries, and maybe I could try the paid service to get around that

**Comment by jankeromnes** [comment]
Actually, that's weird, I think this limit should be at 30 GiB currently (and I'm lobbying internally to get it raised to 50 GiB, in order to unlock several ultra cool large open-source projects).

This 15G limit seems like a bug.

**Comment by csweichel** [comment]
Those are two separate limits: one is the space available to a workspace (used to be 15 GiG). The other is the maximum bytes we'll upload during a backup (20 GiG).

**Comment by Kreyren** [comment]
+1 to 50GB! ~~or 500GB because i need around 256GB for minds development~~

**Comment by Lrvineshaw** [comment]
> Actually, that's weird, I think this limit should be at 20 GiB currently (and I'm lobbying internally to get it raised to 50 GiB, in order to unlock some ultra cool large open-source projects).
> 
> This 15G limit seems like a bug.

thanks bro, let me know if you've got it

**Comment by jankeromnes** [comment]
@Lrvineshaw Sure! But I think this bug is already fixed (🎉) https://github.com/gitpod-io/gitpod/issues/1349#issuecomment-624206558:

> one is the space available to a workspace (used to be 15 GiG)

The "used to be 15 GiB" makes me think that this limit is no longer active, and I personally haven't seen a 15 GiB disk limit in my workspaces recently. So I'll close this issue, but please let me know if you're still seeing 15 GiB! (Then we should look again and fix it for good.)
