### ISSUE TITLE
Validate or document breaking changes on Self-Hosted September Release

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#13494]
As part of the September's release, we (workspace team) need to validate that no breaking changes were introduces or document otherwise.

**Comment by utam0k** [comment]
Checking... https://github.com/gitpod-io/gitpod/compare/2022.08.0...2022.09.0-rc4

**Comment by utam0k** [comment]
My note(WIP)
- [Bump runc from 1.3 to 1.4](https://github.com/gitpod-io/gitpod/commit/21b1d3d6741504bde9b633302b7cb0997ce16b81)

**Comment by utam0k** [comment]
@atduarte can we close this issue?
