### ISSUE TITLE
`coreDump` property of `.gitpod.yml` marked deprecated in schema

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#13500]
### Bug description

`coreDump` property of `.gitpod.yml` is marked deprecated in schema because it is "experimental" - but it has shipped and shows up in the release notes and in the docs without "experimental" remark.

(Deprecation in schema means it shows up with red squiggles in VSCode (with YAML (Red Hat) extension, I guess).)

<img width="535" alt="image" src="https://user-images.githubusercontent.com/4162948/193354148-5f217ff5-140f-4244-bdf4-c69b0f4de91d.png">

### Steps to reproduce

Put a `coreDump:` attribute in your `.gitpod.yml` and see what happens?

### Anything else?

<img width="406" alt="image" src="https://user-images.githubusercontent.com/4162948/193354301-e97ab91d-c2e3-41cd-9d66-2ea6c8f3e6d5.png">

**Comment by andreafalzetti** [comment]
@david-bakin unfortunately in the JSON schema there isn't support for experimental or beta properties so we use the deprecation as a way of highlighting experimental features, I and feel the pain of seeing those red lines underling correct syntax 😅 

On another note, although the JSON schema should be the source of truth I agree that the docs and changelog we should also reflect the experimental state.

Let's ask the workspace team their thoughts. cc @atduarte?

**Comment by david-bakin** [comment]
Ah, so it is _still_ considered experimental?  That's ok of course.  But then I agree, it's the docs/changelog that are missing information.  I thought it was released.  (I can ignore the squiggles.)

**Comment by akosyakov** [comment]
Moved to the workspace team, since they are working on this feature.
