### ISSUE TITLE
cannot resolve workspace image: failed to do request: Head "https://registry.gitpod.elunisis.com/v2/workspace-images/manifests/83a9d3182651700079941607ed08dd881ae242394d76ed2221520cbda3b79230": remote error: tls: handshake failure

### ISSUE THREAD

**Issue by stauder** [gitpod-io/gitpod#13506]
### Bug description

With a fresh self-hosted installation based on Ubuntu 20.04.5 LTS (GNU/Linux 5.15.0-48-generic x86_64)
I get this error, whatever repository I open:

![CleanShot 2022-10-01 at 12 09 11@2x](https://user-images.githubusercontent.com/10399966/193404301-c6898d7b-e010-45b6-a183-54225037947f.png)

cannot resolve workspace image: failed to do request: Head "https://registry.gitpod.DOMAIN/v2/workspace-images/manifests/83a9d3182651700079941607ed08dd881ae242394d76ed2221520cbda3b79230": remote error: tls: handshake failure

### Steps to reproduce

1) Fresh installation of the self-hosted installation, started with https://github.com/MrSimonEmms/gitpod-k3s-guide . I have chooses always the default setting, especially for cert-manager and in-cluster registry.

2) Open of e.g. https://github.com/gitpod-io/template-python-django (but I tried also other repos with the same error).

### Workspace affected

every workspace is affected

### Anything else?

I would be happy to provide further information if someone can guide me to the respective logfiles.

**Comment by MrSimonEmms** [comment]
Hi @stauder, are you using a publicly signed cert or a self-signed one?

Can you provide a KOTS support bundle, please (go to the "troubleshoot" section in the KOTS dashboard? Please encrypt it using GPG with my [public key](https://gist.github.com/MrSimonEmms/b742ced9016488e84424e5609bbb0e68).

**Comment by MrSimonEmms** [comment]
Closing as no response

**Comment by stauder** [comment]
Hello @MrSimonEmms 
Thanks for the offer of help! I attach you the GPG encrypted export. This still happens with the October release I just upgraded to. [](url)

**Comment by MrSimonEmms** [comment]
There's nothing in the support bundle that I can see that looks wrong.

This message is not one that I've seen before - could it be that the [system time on the cluster is incorrect](https://www.geeksforgeeks.org/how-to-fix-the-ssl-tls-handshake-failed-error/)?
