### ISSUE TITLE
De-attach/share/transfer database b/w workspaces

### ISSUE THREAD

**Issue by mittalyashu** [gitpod-io/gitpod#13504]
## Is your feature request related to a problem? Please describe

To run a workspace, we do have a database seed script, but sometimes that's is not enough.

After accumulating a bunch of data in a single workspace, it's really difficult to re-generate all that data again (manually).

**NOTE:** The data I am talking about here is not the seed data

In those cases, is there any way to transfer/share or just keep the database independent of the workspace to attach it to multiple workspaces.

**Discord link convo:** https://discord.com/channels/816244985187008514/816246578594840586/1018834460818546768

**Comment by axonasif** [comment]
Hey @mittalyashu, https://github.com/gitpod-io/gitpod/issues/9284 would be helpful for your usecase.

**Comment by akosyakov** [comment]
You could try to generate data in the docker image or use external database.
