### ISSUE TITLE
lldb doesn't work with vscode (desktop) + microsoft c++ extension + clang 15

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#13513]
### Bug description

Apparently you need to be a god to get `lldb` to work in general and with vscode in particular.  It certainly doesn't work out of the box, and there are multiple alternatives, non supported.  You also have to apparently ensure you're in a docker container with sufficient capabilities (apparently systemtap is needed for lldb).

So - since I am _not_ knowledgeable in any way about how vscode or its extensions work, nor do I have any control over the gitpod container that the workspace runs in, I'm really hoping that Gitpod itself - which _is_ expert in vscode and also its workspace environment - can get this figured out!

(Similar bugs filed in the past have been closed due to being stale.  I kind of hope this gets put into some kind of C++ support epic so some day it can be scheduled when c++ support is interesting ...)

### Steps to reproduce

Spend several evenings, not necessarily consecutive, trying and failing to get `lldb` to work in a gitpod workspace.  You'll see.

**Comment by andreafalzetti** [comment]
@david-bakin it's great to see interest for Gitpod from the C++ space. It would help if you could elaborate more on what you attempted so far? For example:
- did you try [customizing](https://www.gitpod.io/docs/configure/workspaces/workspace-image#configure-a-custom-dockerfile) the default workspace image? Could you share a `Dockerfile`?
- did you check out the [C++ section of the docs](https://www.gitpod.io/docs/introduction/languages/cpp#c-in-gitpod)?

Thanks 🙏

**Comment by david-bakin** [comment]
I have tried everything available on the net for this problem.  It isn't gitpod specific (though perhaps part of the fix has to do with the way the workspace's container is configured).

I did get lldb itself to work.  (That happened here: https://gitlab.com/bakins-bits/env-wrappers-cpp/-/commit/aa54f10a1205f41ca9400585b251612f3fc60c3e)

The problem is the integration with VSCode (Desktop) with (obviously) the Microsoft C/C++ extension.

Doesn't work with "type": "lldb" in the launch.json.

I've tried using the extension "LLDB VSCode" which uses llvm's own lldb-vscode code (https://github.com/llvm/llvm-project/tree/main/lldb/tools/lldb-vscode) though I didn't try to build either the extension myself or the underlying lldb-vscode tool myself.  commit here: https://gitlab.com/bakins-bits/env-wrappers-cpp/-/commit/c4a59db94f5147c96643c6f8a3afffda044cdf1f - following instructions here: https://stackoverflow.com/a/72386036/751579 

I tried building the _older_ method lldb-mi myself following instructions here: https://github.com/microsoft/vscode-cpptools/issues/5415#issuecomment-835831548 - starting with commit here: https://gitlab.com/bakins-bits/env-wrappers-cpp/-/commit/b657c6fb3c5517b01145ac038e8001e1c65523e6 with dockerfile

Then added the actual build here https://gitlab.com/bakins-bits/env-wrappers-cpp/-/commit/33cdb385f78f4596edeb69b6036ed10a2e5b6853 but that didn't work due to bug #13512 

And of course the C++ section of the guides - which I did check - doesn't apply because it's all about gcc + gdb, not clang + lldb.  But by the way I _do_ have clang + gdb working, integrated into vscode.

So all that's left is lldb into vscode.  And that's a tough not, not least because apparently the _only_ way that lldb (or maybe it is lldb-mi) reports any error at all is with the following error message:

> 'A' packet returned an error: 8 

There are lots of hits for that on the web and basically it just means something went wrong and we're not going to tell you what.

**Comment by david-bakin** [comment]
Here's another tip on docker container configuration from a guy who wrote yet another lldb-using vscode extension: https://github.com/vadimcn/vscode-lldb/wiki/Debugger-startup-problems#a-packet-returned-an-error

**Comment by jeanp413** [comment]
@david-bakin Seems your repo is private so I couldn't test it myself https://gitlab.com/bakins-bits/env-wrappers-cpp.
But have you tried using https://github.com/vadimcn/vscode-lldb, it work pretty well for me debugging rust

**Comment by david-bakin** [comment]
> @david-bakin Seems your repo is private so I couldn't test it myself [gitlab.com/bakins-bits/env-wrappers-cpp](https://gitlab.com/bakins-bits/env-wrappers-cpp). But have you tried using [vadimcn/vscode-lldb](https://github.com/vadimcn/vscode-lldb), it works pretty well for me debugging rust

Oops, fixed (access issue). Good to know about `vscode-lldb` - I've actually installed it as an extension but haven't tried it.  Will do so now and report back.

**Comment by akosyakov** [comment]
Is there anything yet to work on? @david-bakin have you managed to use another extension?

**Comment by kasperk81** [comment]
> Is there anything yet to work on?

yes, lldb (a 12 yo debugger) does not work from terminal in gitpod like gdb (36 yo): https://github.com/gitpod-io/gitpod/issues/5705#issuecomment-1326800023 (i tried several images from gitpod.io gallery and all of them have same result)

in any ubuntu/debian based pod: execute `sudo apt install lldb` in terminal followed by `lldb <any program>` then type `run` in lldb repl. it will greet with (world's most cryptic) error message `'A' packet returned an error: 8`. in the same terminal `gdb <any program>` has no issue running the program under its debugger.

so on top of insanely cryptic error messages, lldb, by nature, is frustratingly demanding.
