### ISSUE TITLE
Prebuild on a branch failed when fetching additional repository that didn't have that branch

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#13512]
### Bug description

Pushed commits to a new branch `lldb-attempts` in GitLab repo, prebuild was triggered, it seemed to completely build the custom `.gitpod.Dockerfile` but then failed with

```
SYSTEM ERROR
Prebuild failed for system reasons. Please contact support. undefined
```

Log cut/pasted from prebuild window: https://gist.github.com/david-bakin/51c7240de342148f228133e57983c1bd

Oh wait a sec!  When I _reopened_ the prebuild window I see a _different_ SYSTEM ERROR:

```
Prebuild failed for system reasons. Please contact support. cannot initialize workspace: cannot initialize workspace: git initializer clone: Remote branch lldb-attempts does not exist in https://github.com/lldb-tools/lldb-mi.git
```

And this is true!  My main repo is trying to prebuild branch `lldb-attempts` but I expected the _additional repo_ to _pull_ its _default_ branch!  

**Note that the documentation says it will do this!!**

> When the above configuration is defined then the following additional steps happen when Gitpod workspace is started:
>
> 1. If you open a workspace on a branch, Gitpod will clone the same-named branch in all repositories. **If such a branch doesn’t exist Gitpod checks out the default branch.**

And by the way the "undefined" error on the first prebuild window I saw is bad - it is only by sheer chance, wanting to file an issue on the "SYSTEM ERROR", that I opened the window again from the prebuilds dashboard page and saw the _real_ error.

### Steps to reproduce

Set up a repo with an additional repo - any arbitrary one off of the web.  Main repo needs a .gitpod.yml that triggers a prebuild when any new branch is pushed.  Then push a new branch to the main repo _making sure the new branch name is not one that is present in the additional repo_.  See if it fails this way.

### Workspace affected

https://gitpod.io/projects/env-wrappers-cpp/e9acba92-0005-452d-8319-927c48f6db4e

### Expected behavior

I expected either the additional repo to _pull_ its _default branch_, or for there to be a way to _specify_ which branch to pull for the additional repos.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3rbt6)

**Comment by jimmybrancaccio** [comment]
I can confirm this is replicable. I was just working on a support ticket where this was happening. Thanks @david-bakin for getting this issue in! 😁 🎉
