### ISSUE TITLE
Unable to find the installed EditorConfig extension 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#1351]
### Describe the bug

I have the following in `.gitpod.yml`  but I don't see it installed in the extensions tab.

```
- EditorConfig.EditorConfig@0.14.4:EjFaoTaOf8wRmwR0LNY51A==                                              
```

![image](https://user-images.githubusercontent.com/46004116/77881683-eb724d00-7278-11ea-80d5-dcccbdecf941.png)

This is what I get in the console: 
![image](https://user-images.githubusercontent.com/46004116/77881842-3c824100-7279-11ea-82ba-a62defacbb05.png)
![image](https://user-images.githubusercontent.com/46004116/77882008-8c610800-7279-11ea-999f-780040fd5efc.png)

Also, I don't see it in the `BUILT-IN` tab-pane.

### Steps to reproduce

I have tried installing the `EditorConfig` extension via dragging and dropping the `.vsix` file. 

I have tried refreshing + starting a new workspace but It does not help.

### Example repository

https://gitpod.io/#https://github.com/nisarhassan12/mobx

**Comment by Kreyren** [comment]
Same issue here, looks like theia bug to me?

**Comment by Kreyren** [comment]
@nisarhassan12 Seems that this extension is already built-in? So i assume that the failure caused by installing the duplicate in theia?
![image](https://user-images.githubusercontent.com/11302521/78574301-19800000-782a-11ea-9375-f00a87e6feb9.png)

**Comment by akosyakov** [comment]
Yes, it is a bug, if you try install built-in extension as a workspace extension of exactly the same version then it is INSTALLED, but not displayed as a workspace extension.
