### ISSUE TITLE
Jetbrains gateway link doesn't work

### ISSUE THREAD

**Issue by rushiagr** [gitpod-io/gitpod#13528]
### Bug description

Text says `If you don't see an open dialog in your browser, make sure you have the [JetBrains Gateway with Gitpod Plugin](https://www.gitpod.io/docs/ides-and-editors/jetbrains-gateway#getting-started-jetbrains-gateway) installed on your machine, and then click Open in PyCharm below.`, but when I open the link, it says 404, and opens this link: https://www.gitpod.io/docs/ides-and-editors/jetbrains-gateway

### Steps to reproduce

Create a pod out of a github repo (used pycharm / python repo)

### Expected behavior

link should work

**Comment by Siddhant-K-code** [comment]
Hey @rushiagr 👋🏼 

Thanks for raising the issue.
We've missed out on adding a redirect in our new re-structured [docs. website](https://www.gitpod.io/docs)

It is fixed now in https://github.com/gitpod-io/website/pull/2842
