### ISSUE TITLE
Branch names should not be used to checkout additionalRepositories

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#13527]
### Bug description

When a repository contains a .gitpod.yml with `additionalRepositories`, and we open a branch, that branch name does not necessarily exist in the additional repositories.

![Screenshot from 2022-10-03 08-40-21](https://user-images.githubusercontent.com/161571/193568514-1c8505fb-7967-4a2c-8ccd-cfcd7d807683.png)

### Steps to reproduce

Open a workspace using https://github.com/gitpod-io/gitpod-test-repo/tree/aledbf/test-additional-repositories

### Workspace affected

gitpodio-gitpodtestrepo-77i2bt10ohp

### Expected behavior

Use the default branch name

**Comment by kylos101** [comment]
@aledbf I added to the webapp inbox.

cc: @geropl

**Comment by kylos101** [comment]
nvm, I see you linked a PR :smile:

**Comment by david-bakin** [comment]
See also #13512
