### ISSUE TITLE
[PVC] unable to open the workspace with download initializer

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#13531]
### Bug description

function `GetContentLayerPVC` returns `no backup or valid initializer present` when the StartWorkspace request with the download initializer.

https://github.com/gitpod-io/gitpod/blob/14a1ffd65baa3ce8269a7659c1a9de789f4d570e/components/ws-manager/pkg/manager/imagespec.go#L50-L107

### Steps to reproduce
Set the `persistent_volume_claim` feature for your user

Open the workspace from the repo https://github.com/utam0k/utam0k.github.io

https://gitpod.slack.com/archives/C02F19UUW6S/p1664770050148509

### Expected behavior

It should open the workspace.

### Example repository

https://github.com/utam0k/utam0k.github.io

### Anything else?

#7901

**Comment by jenting** [comment]
cc @sagor999

**Comment by jenting** [comment]
Since the code of PVC is similar to FWB.
So I enabled the FWB and opened the https://github.com/utam0k/utam0k.github.io, and it failed with the same error message.
![image](https://user-images.githubusercontent.com/49380831/194058854-1d6f680a-cf21-4e4e-84c6-398bb80f760e.png)

**Comment by sagor999** [comment]
@jenting do not use FWB. that code has not been tested in a very long time.

**Comment by jenting** [comment]
> @jenting do not use FWB. that code has not been tested in a very long time.

I want to ensure the FWB would hit the same error because the code is similar.
