### ISSUE TITLE
Private repo error 502

### ISSUE THREAD

**Issue by KieranHolroyd** [gitpod-io/gitpod#1354]
### Describe the bug
https://gitpod.io/auth/github/callback on private repo not working, location: https://gitpod.io/sorry/#Error%20502 i get this in the response header. i upgraded my account and everything.

### Steps to reproduce
open my private repo? or update my access controls

### Expected behavior
load my repo... or change the controls

### Additional information
WebSocket connection to 'wss://gitpod.io/api/gitpod' failed: Error during WebSocket handshake: Unexpected response code: 302 _in the js console_.

### Example repository
https://github.com/kieranholroyd/medical-frontend

**Comment by KieranHolroyd** [comment]
i just tried to relog to see if that fixes it, i can't login anymore...

**Comment by AlexTugarev** [comment]
Hi @KieranHolroyd! I'll try to help. Let me check the logs.

**Comment by AlexTugarev** [comment]
Could it be, that you've tried to access https://gitpod.io/auth/github/callback for a second time? GitHub responded with an error code 502 at 16:54:25.497 CEST.

**Comment by KieranHolroyd** [comment]
i don't think so, i just clicked the gitpod button, then grant permissions

**Comment by AlexTugarev** [comment]
I think this was just a glitch with accessing GitHub servers. While there is no downtime logged, https://downdetector.com/status/github/ shows at least one report from the same time.

Please, let us know if it happens again!

**Comment by KieranHolroyd** [comment]
Okay, sorry, i was just rather confused by it. but it does seem to be from github.
