### ISSUE TITLE
test: Automatic detection of whether PVC is operational or not

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#13559]
## Is your feature request related to a problem? Please describe

The self-hosted test is not an environment in which PVC can operate. Currently, we have to change the code to make the test work.
We can reduce this friction by detecting if the PVC test can run and skipping the test if necessary.

## Describe the behaviour you'd like

Pass the test on an env without PVC env

**Comment by kylos101** [comment]
@utam0k how would you recommend we do? For example, one option might be to change the configmap which stores the installer settings used to install Gitpod. If PVC is enabled there, then proceed with testing PVC. Can you think of any other ideas?

cc: @sagor999 @jenting

**Comment by jenting** [comment]
Not sure if it's doable or not.

We could check the CSI driver contains the CREATE_DELETE_SNAPSHOT capability to determine we should test PVC feature or not.

**Comment by jenting** [comment]
Or, we could check the ws-manager ConfigMap, `snapshotClass` is empty string to determine we should test PVC or not.

**Comment by utam0k** [comment]
> Or, we could check the ws-manager ConfigMap, `snapshotClass` is empty string to determine whether we should test PVC or not.

@kylos101 @jenting 
I would recommend relying on our product rather than relying on Kubernetes because I think it is easier to control and understand mechanism.

**Comment by kylos101** [comment]
Rely on product how @utam0k ? Do you mean like a Gitpod config map, which contains installer options used to do the last install or upgrade?

**Comment by utam0k** [comment]
> We could check the CSI driver contains the CREATE_DELETE_SNAPSHOT capability to determine whether we should test PVC or not.

Oh no, I was trying to figure out which of the two methods JenTing suggested would be easier for us to do. Presumably, the capability of the above method is a value that is managed by Kubernetes, right? Well, I think both methods are very good.

**Comment by utam0k** [comment]
So, I recommend this one
> Or, we could check the ws-manager ConfigMap, snapshotClass is empty string to determine whether we should test PVC or not.

**Comment by jenting** [comment]
@utam0k 
Could you please help to check the ws-manager ConfigMap snapshotClass is empty in the self-hosted installation?

**Comment by utam0k** [comment]
@jenting It looks like `snapshotClass` is always `""`

**Comment by jenting** [comment]
> @jenting It looks like `snapshotClass` is always `""`

Thank you 🙏

**Comment by jenting** [comment]
The PVC integration test is disabled #14838. This issue is no longer valid.
