### ISSUE TITLE
SSH `exec` output race condition

### ISSUE THREAD

**Issue by spearki** [gitpod-io/gitpod#13562]
### Bug description

Running a non-interactive command over SSH often returns nothing instead of the output I expect.

### Steps to reproduce

Run this a few times against a workspace:

```
ssh $wsid@$wsid.ssh.ws-us67.gitpod.io 'uname -a'
```

In my case, it returns no output at all around 50% of the time.

If I add a short sleep to the shell command, this is more reliable:

```
ssh $wsid@$wsid.ssh.ws-us67.gitpod.io 'uname -m && sleep 0.01'
```

I suspect `sshproxy` is closing the client connection too early?

### Expected behavior

An SSH exec command should reliably return the result of a command.

**Comment by axonasif** [comment]
Similar issue on a discord-question:
- https://discord.com/channels/816244985187008514/1020726397423067306

**Comment by loujaybee** [comment]
@iQQBot investigated - can you provide any information from that investigation, Pudong? We might need some more information before we can resolve.
