### ISSUE TITLE
VSCode R extension fails to open an R terminal

### ISSUE THREAD

**Issue by hriebl** [gitpod-io/gitpod#1357]
### Describe the bug

The VSCode R extension recommended in the docs (https://www.gitpod.io/docs/languages/r/) fails to open an R terminal and falls back to a shell instead.

### Steps to reproduce

Create the workspace https://gitpod.io/#https://github.com/hriebl/asp20model/tree/hriebl/gitpod-setup (the R package installation takes a while, sorry), press F1, and run the "R: Create R terminal" command.

### Expected behavior

A new terminal window with R opens (instead of a shell, which is what currently happens).

### Additional information

Here is how the extension tries to open an R terminal: https://github.com/Ikuyadeu/vscode-R/blob/master/src/rTerminal.ts#L15. I tried to figure out what goes wrong but can't identify the issue...

### Example repository

https://github.com/hriebl/asp20model/tree/hriebl/gitpod-setup

Thumbs up for creating Gitpod and Theia. Both super useful tools!

**Comment by hriebl** [comment]
This is probably related to this bug: https://github.com/eclipse-theia/theia/issues/6574

**Comment by JesterOrNot** [comment]
I'm sorry it does not work, I will look into this.

**Comment by JesterOrNot** [comment]
CC @akosyakov
