### ISSUE TITLE
Start Gitpod in specific subdirectory for explorer sidebar

### ISSUE THREAD

**Issue by chriswyatt1** [gitpod-io/gitpod#13608]
Hi, this is probably trivial. 

I have searched through all the issues and the docs, but how do you start an environment in a specific subdirectory within the explorer side bar in VS code?

In the following repo (https://github.com/seqeralabs/nf-training-public/tree/new_container_nextflow_22.09.7), I want to start in the `/workspace/nf-training-public/nf-training` folder (which I already cd into in the yml), so that I do not see all the build files in the head directory `/workspace`. I tried setting these in the gitpod yml: 

`workspaceLocation: "./nf-training"
workspaceLocation: "/workspace/nf-training"
checkoutLocation: "./nf-training"`

But this just removes the explorer bar completely on the left hand side.

<img width="285" alt="image" src="https://user-images.githubusercontent.com/9978862/194039581-173e8d64-9afc-4276-bcdd-049c798e64af.png">

**Comment by axonasif** [comment]
Hey @ewels, [this here](https://github.com/gitpod-io/gitpod/issues/8623#issuecomment-1232806473) might help.

We should probably get this documented well.

**Comment by ewels** [comment]
Awesome - this looks ideal, we'll give it a try. Thanks @axonasif !

**Comment by chriswyatt1** [comment]
Awesome, worked great, thanks @axonasif
