### ISSUE TITLE
Many shortcuts don't work with the Neo 2 keyboard layout

### ISSUE THREAD

**Issue by kreibaum** [gitpod-io/gitpod#1363]
### Describe the bug
When using gitpod with the Neo 2 layout multiple shortcuts don't work. Most prominently, this includes ctrl+S for saving as well as ctrl+C, ctrl+V for copy and paste.

I am on Ubuntu 19.10 and this is a Problem in both Firefox and in Chromium

The layout Neo 2 is a special German layout included with most Linux distributions. I have included an image of the layout to give an idea of its "alien-ness".

![Screenshot from 2020-04-05 00-39-46](https://user-images.githubusercontent.com/48726499/78462823-1ecc3600-76d6-11ea-9fff-3de64e80e38e.png)

### Steps to reproduce
Use the German Neo 2 layout on Ubuntu and try to save or try to use copy paste in Gitpod.

### Expected behavior
I expect those shortcuts to work, as if I where using a standard QWERTZ/QWERTY layout.

### Additional information
In vscode there is a bug with Neo 2 where parts of layer 4 don't work (arrow keys on the home row). This must be worked around by setting `"keyboard.dispatch": "keyCode"` which is not a setting available in Gitpod/Theia. https://github.com/microsoft/vscode/issues/24043

I did not check this with other niche keyboards like Bépo, but I suspect those will have similar issues.

### Example repository
I am trying out Gitpod in https://github.com/kreibaum/pacosako but I already had that problem with the animal doctor example project.

**Comment by akosyakov** [comment]
cc @spoenemann

**Comment by spoenemann** [comment]
@kreibaum we need your help to solve this issue. Could you do the following:

 * Connect your Neo 2 keyboard to a **Windows** PC
 * Install Node.js 10 and Yarn as described here: https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#building-on-windows
 * Clone https://github.com/eclipse-theia/theia
 * Run `yarn` (it doesn't matter if it fails to build all packages)
 * Run https://github.com/eclipse-theia/theia/blob/master/packages/core/scripts/generate-layout.js with this command
```
yarn --cwd packages/core generate-layout --output src/common/keyboard/layouts/de-Neo_2-pc.json
```
 * Create a pull request here to add the generated file

I know this is quite some work, but there is no way we can fix the issue without a Neo 2 keyboard (I don't have one). Doing these steps on Windows is important so the generated layout data will work on both Linux and Windows. It will not work properly on Windows if you do it on Linux.

**Comment by kreibaum** [comment]
I think there may be a bit of a misunderstanding about the keyboard. It is a normal German QWERTZ keyboard and I am just using a different layout through software (and blind typing).

Do your comments still apply in that case?

(I can also try to debug what exactly happens in theira if you give me some hints where to start)

**Comment by spoenemann** [comment]
There's no need to debug, we just need to generate a layout file using the [generator script](https://github.com/eclipse-theia/theia/blob/master/packages/core/scripts/generate-layout.js).

You're right, I forgot that it's usually sufficient to set the keyboard layout in the operating system (independently of the actual hardware). In this case someone should check whether the layout is available on Windows, and if yes generate it from there as described above. If not, it's ok to generate it on Linux with the same steps.

**Comment by kreibaum** [comment]
Sorry for the delay, I had some problem building it on my machines. I just now got around to setting up a fresh Ubuntu on an older Laptop and here I was able to build theia.

**Comment by jankeromnes** [comment]
Hi @kreibaum, does this issue still reproduce if you switch your IDE to Code in https://gitpod.io/settings/ ? (Under Feature Preview -- but Code will soon become the default IDE in Gitpod)

**Comment by kreibaum** [comment]
This is amazing ❤️

It does not work out of the box but the same fix that works for vscode (https://github.com/microsoft/vscode/issues/24043) works in the browser as well.

Thank you for telling me about this new editor frontend!
