### ISSUE TITLE
Use `gcloud storage` instead of `gsutil`

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#13639]
## Is your feature request related to a problem? Please describe

According to [Google official blog ](https://cloud.google.com/blog/products/storage-data-transfer/new-gcloud-storage-enables-super-fast-data-transfers), gcloud has better performance than `gsutil`. 

https://github.com/gitpod-io/gitpod/blob/27068da167adc9c95026375a0ee9f37cd75c530f/components/content-service/pkg/storage/gcloud.go#L210

There may be room to improve upload and download backups, but I think we have to validate about it

## Describe the behaviour you'd like

Improve the performance of upload and download backup

**Comment by aledbf** [comment]
Two comments, this is still alpha and the speed is similar to gsutil.
Let's wait until this at least beta.

**Comment by utam0k** [comment]
> Two comments, this is still alpha and the speed is similar to gsutil. Let's wait until this at least beta.

:+1:
