### ISSUE TITLE
Release Notes in every workspace

### ISSUE THREAD

**Issue by Siddhant-K-code** [gitpod-io/gitpod#13638]
### Bug description

Currently it shows release notes for every new workspace (it should be limited to the first workspace only, after every release),

### Steps to reproduce

- Open Multiple workspaces (parallel or one after the other) you will see a VS Code tab of release notes in each workspace.

### Expected behavior

It Should show Release Notes for once only

### Example repository

Open a workspace from [**`gitpod.new`**](https://gitpod.new/)

### Anything else?

Currently Tested on VS Code Browser 

Related [Internal Discussion](https://gitpod.slack.com/archives/C01KPEPNBD0/p1664987281685579)

**Comment by mustard-mh** [comment]
Hey @Siddhant-K-code , could you reproduce it again? if yes, you can check if `settings sync` for `Extensions` enabled, it's required to store release note display state.

|F1 quick actions| Settings |
|:-:|:-:|
|![image](https://user-images.githubusercontent.com/20944364/215774594-68c0c453-a3cb-4e98-a664-2ca3698afd4b.png)|<img width="716" alt="image" src="https://user-images.githubusercontent.com/20944364/215774581-1552aa72-9988-4aa7-9e16-f4bcb7c29cd6.png">|

**Comment by Siddhant-K-code** [comment]
We can test this with our new upcoming release 🙏🏽

**Comment by mustard-mh** [comment]
> We can test this with our new upcoming release 🙏🏽

fyi @Siddhant-K-code  for the new releases, if we open multiple workspaces in seconds, it will show multiple times too, because it needs time to sync data. 

VSCode will do it automatically, but if you want to make sure it's synced, you can use quick action (press F1) `Settings Sync: Sync Now`

**Comment by Siddhant-K-code** [comment]
Seems to work fine now. Will re-open this, if anything looks weird.

Thanks @mustard-mh
