### ISSUE TITLE
Remove old OTS code

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#13634]
- [ ] identify components requiring changes
- [ ] Remove the code and related tests
- [ ] Remove the `protected_secrets` feature flag from config cat
- [ ] Update architectural diagrams

**Comment by kylos101** [comment]
@Furisto could you update this issue with a brief timeline? We just spoke, and you indicated there's an order of events that are tied to deploys for you to get unblocked and proceed with this issue.

**Comment by Furisto** [comment]
- Deploy the changes required for workspace clusters with gen73
- Make the changes on web app side after the roll out of gen73 is completed
The web app changes remove the feature flag, so if we would deploy them before the workspace cluster changes protected secrets would be disabled again.

**Comment by kylos101** [comment]
@Furisto are you still blocked on this issue?

**Comment by Furisto** [comment]
@kylos101 No, the changes on web app side are now ready for review.

**Comment by easyCZ** [comment]
There remains server-side implementation of the OTS retrieval on `server`. Is that in scope for removal? @Furisto
