### ISSUE TITLE
Unexpected Dockerfile caching behaviour

### ISSUE THREAD

**Issue by spearki** [gitpod-io/gitpod#13636]
### Bug description

I think this is a known issue (within Gitpod at least), but it was a surprise to me that with a line in a `.gitpod.Dockerfile` like:
```
COPY the_file /here/
```
...changes to `the_file` don't actually trigger a rebuild of the image. We internally came up with the same workaround of using a dummy ENV var to break the cache manually and force a rebuild when any dependent files change.

It would be good to at least document this limitation, so devs don't have to independently discover it, usually following a period of frustration at why changes aren't being reflected in the workspace. 😞 

### Steps to reproduce

`.gitpod.Dockerfile`:
```
FROM gitpod/workspace-full:latest
COPY something /
```

Open a workspace in a repo with the above Dockerfile configured, then make a change to `something`, push and open a new workspace again. If a previously cached image exists, the image won't be rebuilt.

### Expected behavior

In Docker/buildkit normally a change to a `COPY`ied file will trigger a rebuild of that layer and following layers.

**Comment by david-bakin** [comment]
Should _also_ be rebuilt if `FROM` refers to an image which has changed in its repo (this happens when, e.g., the tag is `:latest`) (see [this comment](https://github.com/gitpod-io/gitpod/issues/11455#issuecomment-1188368440)).

**Comment by spearki** [comment]
> Valid point, added to the docs [gitpod-io/website#2866](https://github.com/gitpod-io/website/pull/2866) 🙏

Thank you! Hopefully will help others avoid this pitfall in the future.
