### ISSUE TITLE
role of owner should be prohibited from changing role

### ISSUE THREAD

**Issue by huweiATgithub** [gitpod-io/gitpod#13635]
### Bug description

I created a team with only me.
I can't help myself when I see the drop-down 
![image](https://user-images.githubusercontent.com/37072526/194197888-8d2b4b97-71cb-4c06-b067-69ae7940d145.png)
and click `member`.

Then, I find myself as a member of a team without an owner. 

I can't open `Settings` in the project anymore.  (I don't dare leave it now 😭 )
Once I click `Settings`, it just flashes out (which might be another UI bug, it should not reject users from accessing `Settings` in this way).

### Steps to reproduce

As described.

**Comment by gtsiolis** [comment]
Thanks for noticing, @huweiATgithub! This is already known and tracked in https://github.com/gitpod-io/gitpod/issues/11452. Please, feel free to drop a message in support with your single-member team if you want to restore the permissions. If there's another owner in that team, I'd suggest reaching out to them to restore your permissions.

**Comment by jldec** [comment]
Duplicate of #11452
