### ISSUE TITLE
Cannot open local vscode workspace when ControlPath is specified in ~/.ssh/config

### ISSUE THREAD

**Issue by abeluck** [gitpod-io/gitpod#13641]
### Bug description

When the local ssh client is configured to use a `ControlPath` for all connections, gitpod sometimes cannot be used locally because often the full name of the host and user is over the [108 character limit](https://man7.org/linux/man-pages/man7/unix.7.html) for unix domain socket names.

### Steps to reproduce

1. Add the following to your `~/.ssh/config`

```
Host *
  ControlMaster Auto
  ControlPath ~/.ssh/%h-%r
```

2. Try to open a gitpod locally (it must have a decently long name)

Result:

```
[11:40:20.405] Spawned 1877472
[11:40:20.507] > local-server-5> Spawned ssh, pid=1877480
[11:40:20.509] stderr> OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
[11:40:20.510] stderr> ControlPath too long ('/var/home/abel/.ssh/mylongorgname-myproject-172jhshash.ssh.ws-eu67.gitpod.io-mylongorgname-myproject-172jhshash' >= 108 bytes)
[11:40:20.511] > local-server-5> ssh child died, shutting down
[11:40:20.516] Local server exit: 0
[11:40:20.516] Received install output: local-server-5> Spawned ssh, pid=1877480
OpenSSH_8.8p1, OpenSSL 3.0.5 5 Jul 2022
ControlPath too long ('/var/home/abel/.ssh/mylongorgname-myproject-172jhshash.ssh.ws-eu67.gitpod.io-mylongorgname-myproject-172jhshash' >= 108 bytes)
local-server-5> ssh child died, shutting down
```

### Expected behavior

The local workspace should open

**Comment by axonasif** [comment]
Hi @abeluck, why not use one static control path?
If you wish to it this way, you could wrap the `ssh` command to generate random short filenames under `/tmp/` to use them as the Control socket. Here's a tiny project doing that in case you're interested:
https://github.com/axonasif/gssh

I'll add this to our IDE team inbox to see if there's a fix for this.

**Comment by akosyakov** [comment]
I assume you are using auth token not SSH keys? Have you tried with configured keys?
