### ISSUE TITLE
[JetBrains] Stabilize stable releases and simplify maintenance

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#13654]
## Description

- [x] Refactor JetBrains GHA workflows for IDEs and backend-plugin to be updated in one bigger job, but only when all IDEs have been released to stable (meaning, we wait to create the PR if one IDE has not been updated by upstream yet). Only then we realease new stable IDE images and new backend-plugin as stable in Gitpod
    https://github.com/gitpod-io/gitpod/pull/14013

- [x] Publish `nightly` GW plugin builds only if when there are actual changes related to the GW code 
    https://github.com/gitpod-io/gitpod/pull/13923

- [x] Make sure that the nightly job does not push nightly images if the build of the plugin fails
    https://github.com/gitpod-io/gitpod/pull/14263
    https://github.com/gitpod-io/gitpod/pull/14292

- [x] Automatically publish stable GW plugin (it's important to be able to avoid publishing builds which have no relevant changes in the gw)  (Related issue: https://github.com/gitpod-io/gitpod/issues/9101)
    https://github.com/gitpod-io/gitpod/pull/14262
    
- [x] Automatically update Stable Gateway Plugin, without auto-approving its PR.
    https://github.com/gitpod-io/gitpod/pull/14744

**Comment by akosyakov** [comment]
In which content it is relevant? Compatibility checks can be done with verifyPlugin command locally. We don't want to install from marketplace on backend since SH distribution should be self-contained.

**Comment by felladrin** [comment]
This Epic seems complete. Shall we close it?

**Comment by andreafalzetti** [comment]
Good call, @felladrin :)
