### ISSUE TITLE
Do not use `workspaceLocation` when the path is invalid and show error notication on VSCode

### ISSUE THREAD

**Issue by thisisommore** [gitpod-io/gitpod#13650]
### Bug description

Clicked gitpod button as I usually do and this happened
<img width="670" alt="image" src="https://user-images.githubusercontent.com/51229945/194331778-af3eccce-f863-4510-87ef-cca546a10e13.png">

### Steps to reproduce

Go to https://gitpod.io/#https://github.com/TheLazarusNetwork/go-helpers
See the issue

### Workspace affected

thelazarusnet-gohelpers-wjka5j790e3

### Expected behavior

Should properly show the clone and everything should be there

### Example repository

https://github.com/TheLazarusNetwork/go-helpers

### Anything else?

I have noticed many random bugs happen? Is there any way in future where everything is more stable and random bugs comes less. Currently there new bug each week and it is so random that it blocks by work since I am fully dependent on gitpod. Near zero setup on local machine.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3sabu)

**Comment by thisisommore** [comment]
```bash
ls /workspace
```
<img width="413" alt="image" src="https://user-images.githubusercontent.com/51229945/194332515-022cc82e-937e-4bfb-856f-debd729404b9.png">

**Comment by thisisommore** [comment]
> Hey @thisisommore, there seems to be a typo in your `.gitpod.yml` `workspaceLocation` value. [TheLazarusNetwork/go-helpers#1](https://github.com/TheLazarusNetwork/go-helpers/pull/1) should fix it.

Oh damn typo

**Comment by akosyakov** [comment]
It was the issue with a user configuration, correct? Is there something else to do?

**Comment by axonasif** [comment]
Yes, the path had a typo @akosyakov 

But we could show an warning for that and not use the non-existent path.
