### ISSUE TITLE
Dotfiles break in some proxy environments

### ISSUE THREAD

**Issue by mrzarquon** [gitpod-io/gitpod#13682]
### Bug description

tl,dr; we don't honor no_proxy when cloning dotfiles.

Supervisor copies https_proxy and http_proxy into the git clone subroutine, but ignores the [no_proxy](https://github.com/gitpod-io/gitpod/blob/219b71f89423d90f72da13fd1810d4a04a9ec49d/components/content-service/pkg/git/git.go#L183-L196) value.

For users whose SCM instances that host their dotfiles repo are behind the proxies, this is not a problem. But for users whose scm instances aren't behind the proxy and are on the no_proxy list, the dotfiles clone will fail because we explicitly create an empty environment and only set certain variables for it.

The result is the user can clone the repository once their workspace has launched, but the dotfiles won't clone during workspace launch.

This will cause significant issues unless addressed before self-hosted supports [https_proxy](https://github.com/gitpod-io/gitpod/issues/10769)

### Steps to reproduce

Set a user environment variable setting a proxy, also set the no_proxy escaping your-github.com.

Attempt to launch a workspace with your user settings for dotfiles at your-github.com/me/dotfiles

### Expected behavior

Wherever we apply https_proxy environment variables, we must check and apply no_proxy environment variables.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3rs96)

**Comment by mrzarquon** [comment]
This isn't fixed by #13959, it just prevents that from happening in some cases. The problem still exists.

**Comment by subinamathew** [comment]
Do you have a lead time on this issue?
