### ISSUE TITLE
Weird error message when workspace is stopped

### ISSUE THREAD

**Issue by thisisommore** [gitpod-io/gitpod#13691]
### Bug description

This message comes when workspace is stopped, but it is weird since my workspace starts without any issues, happen to me second time
<img width="454" alt="image" src="https://user-images.githubusercontent.com/51229945/194704018-2d88e4a1-bdce-44a2-8dbc-24246b5d0b6e.png">

### Steps to reproduce

Open any workspace in gitpod
Stop it
And see the error

### Expected behavior

Should not show any error message since that makes user(me) afraid that they are losing data and code

**Comment by axonasif** [comment]
Hey @thisisommore, thank you for reporting. Are you still seeing this? If not we can close the issue, or you could share the workspace URL/ID if it persists.

**Comment by thisisommore** [comment]
> Hey @thisisommore, thank you for reporting. Are you still seeing this? If not we can close the issue, or you could share the workspace URL/ID if it persists.

It did happen to me two times last week, but not this week let's see, not sure if that is solved though, also doesn't happen to any particular workspace, but I will share the ID when it happens again

**Comment by thisisommore** [comment]
Did happen again, workspace url is https://weareflexable-superiad-rx9xtgvcogq.ws-us73.gitpod.io/

**Comment by axonasif** [comment]
@thisisommore please subscribe to https://github.com/gitpod-io/gitpod/issues/12021
