### ISSUE TITLE
Make HTML Preview more visible

### ISSUE THREAD

**Issue by jmewes** [gitpod-io/gitpod#137]
I am searching for a tool which enables teaching HTML / CSS / Bootstrap / Git to pupils.

Gitpod seem like a very good fit, if only it could preview HTML files as it does for Markdown files.

**Comment by svenefftinge** [comment]
You can right click in the file navigator and then choose `Open in Mini Browser`

<img width="550" alt="screenshot 2018-11-12 at 21 18 22" src="https://user-images.githubusercontent.com/372735/48372958-9acc7500-e6c0-11e8-942b-4070ee1a676d.png">


<img width="1042" alt="screenshot 2018-11-12 at 21 18 44" src="https://user-images.githubusercontent.com/372735/48372946-8daf8600-e6c0-11e8-8547-fd574056c06e.png">

**Comment by svenefftinge** [comment]
We should add the new preview toolbar to html files.

**Comment by svenefftinge** [comment]
@akosyakov could you take care of this as part of https://github.com/theia-ide/theia/pull/3451 or separately if you prefer?
