### ISSUE TITLE
Dotfiles task hooks

### ISSUE THREAD

**Issue by spearki** [gitpod-io/gitpod#13700]
## Is your feature request related to a problem? Please describe
Users can currently control their baseline environment configuration via dotfiles, but the `install.sh` script is run before IDE startup, so there's a limit to what a user can customise for a particular repo.

## Describe the behaviour you'd like
Be able to run scripts from the user's dotfiles repo as a separate supervisor task at different stages during workspace startup.

Two possible hook points:

1) IDE ready - for interacting with the IDE (install extensions, etc)
2) All `.gitpod.yml` tasks finished - for interacting with the fully-configured workspace after all `command:`s are finished.

## Describe alternatives you've considered
We can implement this on a per-repo basis by explicitly adding a new task to our `.gitpod.yml`, but this feels like a generally useful feature that could possibly be supported natively?

**Comment by axonasif** [comment]
Hey @spearki, actually there are many ways you can detect things within a Gitpod workspace.

There are certain environment variables, state files. And there's also `gp` CLI for you to query a few things.

> IDE ready - for interacting with the IDE (install extensions, etc)

This might be useful for some usecases but what I've found is, for vscode, it's better to do before vscode server starts.
- If you wish to wait for VSCode-Web to start, [here's an example](https://github.com/axonasif/dotfiles-sh#awaitfor_vscode_ide_start).
- I would recommend using [settings-sync](https://www.gitpod.io/docs/ides-and-editors/settings-sync) for your extensions to be auto installed, this is the most straightforward method.

> All .gitpod.yml tasks finished - for interacting with the fully-configured workspace after all command:s are finished.

You may want to take a look inside the `/workspace/.gitpod` dir, a file called `ready` is placed there after repos are fully cloned AFAIK.

To achieve what you're asking, I can only think of appending an extra command to the task terminals that would increment the value inside a file for you to query.
