### ISSUE TITLE
How to get delete workspace?

### ISSUE THREAD

**Issue by Murtaza-arif** [gitpod-io/gitpod#1370]
How to get delete workspace?
I don't know that I have to pin the workspace now they are gone is there any way to get it back they are very important for me

**Comment by jankeromnes** [comment]
Hi @Murtaza-arif, actually there is no need to email support@, I have just restored all of your old workspaces.

Please double-check https://gitpod.io/workspaces/ and delete those that you no longer need.

**Comment by Murtaza-arif** [comment]
Hi Gitpod-Io/Gitpod,
Can you check this workspace as well
https://a2237ce2-7db6-4884-a99e-c8f757e6de9a.ws-ap01.gitpod.io/#/workspace/PyTLDR
https://f29dac02-e335-45e6-a56a-3c0a2b44eeaf.ws-ap01.gitpod.io/#/workspace/text-summarization

Thanks

**Comment by jankeromnes** [comment]
Hi @Murtaza-arif,

These two workspaces are alive and well, and you should be able to find them in your workspaces list at https://gitpod.io/workspaces/

Worst case, if you don't find them for some reason, please email support@gitpod.io and we will be able to email you a backup archive of these workspaces.
