### ISSUE TITLE
IDE consumes system cache over time, causing long running workspace to get OOMkilled

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#13732]
### A self-hosted customer reported
We’re seeing long-running pods get killed by k8s due to memory usage with our self-hosted installation. 

I had assumed it was a memory leak or something else that we’re doing, but after testing it looks like the kernal cache is growing and eventually causing the pod to get killed. During that time there’s no real increase in memory usage by anything reported by htop.

System cache increases linearly when the workstation is not in use when user processes. I’ve traced that down to the IDE server and similar process writing logs.

[Front message](https://app.frontapp.com/open/cnv_jyvctqi)

### Steps to reproduce

Start a workspace, let it run but remain idle for a while.

Observe the workspace periodically via `watch -n 60 free --mega`, to see whether cache goes up, goes up but plateaus, or stays low.

### Expected behavior

Cache should not continue to climb

### Example repository

n/a

### Anything else?

Related issue: https://github.com/gitpod-io/gitpod/issues/13254

This could be user processes, the IDE server, or VS Code extensions that the user had loaded in the workspace. **The intent of this issue is to focus on the IDE server, to examine consumption of system cache.** If the IDE server is constantly consuming cache, we may want to resolve and release a self-hosted patch, to avoid similar issues for other customers.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3rs22)

**Comment by kylos101** [comment]
@akosyakov @loujaybee for awareness

**Comment by jimmybrancaccio** [comment]
As a side note, I am having users in support tickets whom are reporting this to run the following in a workspace and then to send me over the created log file:

```bash
for i in `seq 1 60` ; do date |tee -a memory.log ; free --mega | tee -a memory.log ; echo '' >> memory.log ; echo '' >> memory.log ; sleep 60 ; done
```

**Comment by jeanp413** [comment]
I took a look yesterday but don't see any increase in cache memory :thinking:
