### ISSUE TITLE
Non-helpful error message when the fork of a PR has been deleted

### ISSUE THREAD

**Issue by spoenemann** [gitpod-io/gitpod#1375]
### Describe the bug
When you open a PR in Gitpod that was created from a fork, and the fork is deleted again, Gitpod displays

> We are having trouble parsing your context
> Error: Cannot read property ‘repository’ of null

### Steps to reproduce
 * Fork a repository
 * Create a PR to the original repository
 * Delete the fork
 * Open the PR in Gitpod

### Expected behavior
The error message should make clear that the repository does not exist.

### Example repository
https://github.com/eclipse/openvsx/pull/61

**Comment by jankeromnes** [comment]
I very much agree that this error message is super unhelpful.

Originally reported as https://github.com/gitpod-io/gitpod/issues/4

**Comment by jankeromnes** [comment]
Now being tracked here: https://github.com/gitpod-io/gitpod/issues/3659
