### ISSUE TITLE
Always display the absolute time in a tooltip when using the relative date and time format

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#13764]
### Problem to solve

We've been using **relative** and **absolute** date and time formats across the product. For example, see [projects](https://gitpod.io/t/gitpod/projects), [members](https://gitpod.io/t/gitpod/members), and [usage](https://gitpod.io/t/gitpod/usage) for the Gitpod team in Gitpod.io.

Generally, both absolute and relative formats can be useful depending on each use case. 💡 

:a: Relative date and time can be useful when the content is updated frequently and surfacing an absolute date is not critical, etc.
:b: Absolute date and time makes sense when users would need to convert the date in order to complete a task, etc.

### Proposal

In any case, I think we can safely use the following guideline across the product:

> When using the relative format, always display the absolute time in a tooltip.

This issue acts as a placeholder for adding a tooltip on all relative date and time formats used across the product. 🛹 

### Next steps

Future next steps include:
1. Documenting this as a guideline.
2. Introducing more sophisticated guidelines on when to use which.
3. Explain in detail date and time format options and how to use them.

**Comment by tanishq-singh-2301** [comment]
_Hey @gtsiolis, I would like to work on this issue._

**Comment by tanishq-singh-2301** [comment]
@gtsiolis This is my first issue in gitpod, I'm not able to find any contribution and installation guide??

**Comment by gtsiolis** [comment]
Hi @tanishq-singh-2301! Re-posting from https://github.com/gitpod-io/gitpod/issues/15669#issuecomment-1381793399:

> 1. Contributing to Gitpod can be more complicated than other projects because of the nature of the project working on top of Kubernetes cluster, etc.
> 1. For the dashboard component, you can find some basic instructions in the [relevant folder](https://github.com/gitpod-io/gitpod/tree/main/components/dashboard), but we have not been actively maintaining that README file.
> 1. We develop Gitpod in Gitpod which means we're not running Gitpod locally to develop it.
> 1. Usually community contributors push a new branch or a new PR and we help by spinning a preview environment for them which deploys a preview installation of Gitpod where you can connect later with telepresence and make changes.

**Comment by tanishq-singh-2301** [comment]
I got it setup, but I'm not able to create or view `teams`.
It's giving me error `HTTP 404` If I try to create a new team.
How do I access that page??

![image](https://user-images.githubusercontent.com/76192403/212926180-a7acba1d-254d-489c-94bb-73c4cec6bfdf.png)

**Comment by tanishq-singh-2301** [comment]
> Hi @gtsiolis I got it setup, but I'm not able to create or view `teams`. It's giving me error `HTTP 404` If I try to create a new team. How do I access that page??
> 
> ![image](https://user-images.githubusercontent.com/76192403/212926180-a7acba1d-254d-489c-94bb-73c4cec6bfdf.png)

here is an update!!
I noticed that api call was responding with 404, So I added this piece of code.
To proxy `/public-api` to `gitpod.io/public-api`

```js
// craco.config.js

"/public-api": {
     target: "https://" + process.env.GP_DEV_HOST,
     ws: true,
     headers: {
         host: process.env.GP_DEV_HOST,
         origin: "https://" + process.env.GP_DEV_HOST,
         cookie: process.env.GP_DEV_COOKIE,
     },
},
```
