### ISSUE TITLE
Sort Ports view

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#13777]
## Is your feature request related to a problem? Please describe
No.

## Describe the behaviour you'd like
I'd like the Ports view sorted by port so I can find the one I'm looking for quickly.

## Describe alternatives you've considered
None.

## Additional context
My project has 14 open ports, having them sorted would make it easier to find the one I'm looking for.

**Comment by loujaybee** [comment]
Hey @mikenikles — just checking, if this is already covered by: 

1. https://github.com/gitpod-io/gitpod/issues/7764

Also, possibly related: 

1. https://github.com/gitpod-io/gitpod/issues/10294
1. https://github.com/gitpod-io/gitpod/issues/10275

If you think it's sufficiently different happy to keep, but wanted to signpost those others as potential duplicates.

**Comment by mikenikles** [comment]
Yes, #7764 covers it.

**Comment by loujaybee** [comment]
For others finding this issue, this is now shipped. 

It will be announced in the October 2022 changelog 🙏
