### ISSUE TITLE
SSH not connectable on macOS

### ISSUE THREAD

**Issue by dalisoft** [gitpod-io/gitpod#13776]
### Bug description

I'm cannot connect to Gitpod via Gitpod Remote. First think it's bug on my side and re-checked my all access, SSH keys and etc, debugged and searched logs and found the reason all is OK but just bug on my macOS

Report bug: `unix_listener: path "/tmp/dalisoft-vscodeworkspac-{RANDOM}@dalisoft-vscodeworkspac-{RANDOM}.ws-eu70.gitpod.io:22.P4x8eOXXXXXTlZ1M" too long for Unix domain socket`

### Steps to reproduce

Desktop on  master [!?] took 9s 
❯ ssh 'dalisoft-vscodeworkspac-{RANDOM_STRING}.ssh.ws-eu70.gitpod.io' -i ~/.ssh/personal/gitpod/oss
unix_listener: path "/tmp/dalisoft-vscodeworkspac-{RANDOM}@dalisoft-vscodeworkspac-{RANDOM_STRING}" too long for Unix domain socket
Desktop on  master [!?] 
❯ ssh 'dalisoft-vscodeworkspac-{RANDOM_STRING}.ssh.ws-eu70.gitpod.io'
The authenticity of host 'dalisoft-vscodeworkspac-{RANDOM}.ssh.ws-eu70.gitpod.io (XX.79.YYY.55)' can't be established.
ECDSA key fingerprint is SHA256:SHA_FINGERPRINT.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'dalisoft-vscodeworkspac-{RANDOM}.ssh.ws-eu70.gitpod.io' (ECDSA) to the list of known hosts.
unix_listener: path "/tmp/dalisoft-vscodeworkspac-{RANDOM_STRING}.ws-eu70.gitpod.io:22.cXBMFuXXXXXtwm" too long for Unix domain socket
Desktop on  master [!?] took 5s 
❯ ssh 'dalisoft-vscodeworkspac-{RANDOM_STRING}.ssh.ws-eu70.gitpod.io' -i ~/.ssh/personal/gitpod/oss
unix_listener: path "/tmp/dalisoft-vscodeworkspac-{RANDOM}@dalisoft-vscodeworkspac-{RANDOM_STRING}" too long for Unix domain socket
Desktop on  master [!?] 
❯ 

### Expected behavior

Just connect to remote Gitpod from my local machine

### Example repository

https://github.com/dalisoft/vscode-workspace-bug

**Comment by axonasif** [comment]
Seems to be related with https://github.com/gitpod-io/gitpod/issues/13641

Could you please setup your ssh-keys on Gitpod so that you do not have to use an access-token like that?
https://www.gitpod.io/docs/configure/user-settings/ssh

**Comment by dalisoft** [comment]
@axonasif I am using SSH keys. Added public keys on Gitpod, locally using private key and SSH key is without password. Is there any step missing?

**Comment by dalisoft** [comment]
```
Host *
     ControlMaster no
     ControlPersist no
     ServerAliveInterval 120
     TCPKeepAlive no
     AddKeysToAgent yes

Host * !*.gitpod.io
     ControlMaster auto
     ControlPath /tmp/%r@%h:%p
     
Host *.gitpod.io
     IdentityFile ~/.ssh/personal/gitpod/oss
     ControlPath /tmp/%r-gitpod
```

I'm found workaround (maybe a solution?) to get it working, separate logic in `ssh config` gives me possibility to get code in VSCode desktop and remote executing to save power and energy.

Thank you for help and right direction for solving this case

**Comment by akosyakov** [comment]
@axonasif Something learn and document here for other users to reference?

**Comment by axonasif** [comment]
Will do, had asked Lou about it 🙏

**Comment by axonasif** [comment]
Another report: https://app.frontapp.com/open/cnv_k9dhi6i

User was trying to open their workspace in VSCode but they hit this issue due to their `user/repo` name being big. Can we reopen this issue?

**Comment by akosyakov** [comment]
sure, do it
