### ISSUE TITLE
Two browser tabs open when I click a port's address

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#13778]
### Bug description

When I click the "Address" of a port in the Ports view, it opens two browser tabs instead of one.

### Steps to reproduce

1. Start a workspace for https://github.com/gitpod-io/website
2. Open the **Ports** view
3. Click on the "Website(3000)" port's **Address** URL

### Workspace affected

All

### Expected behavior

One browser tab opens.

### Example repository

https://github.com/gitpod-io/website

### Anything else?

Hey @JohannesLandgraf, this is yet another case where all you need is a single person who focuses on quality assurance to avoid embarrassing bugs. As a co-CEO, you're in a good position to make a change and improve Gitpod's QA - what do you think?

**Comment by axonasif** [comment]
Hey @mikenikles 👋 
I tried the following on google chrome:
- `python -m http.server 3000`
- And then click the 🌏 button on ports list to open a browser tab

But was unable to reproduce, could you please share us the [logs](https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop) when you notice this again 🙏 ?

**Comment by axonasif** [comment]
Also tried on Firefox with https://github.com/gitpod-io/website r8n.

**Comment by mikenikles** [comment]
I tried again now and it doesn't happen. If only Gitpod publicly shared when releases happen and what exactly was deployed as part of it, the community could actually determine what may have fixed/broken stuff. Not your fault Asif of course, but @JohannesLandgraf could do something about it if he wanted to.

**Comment by mikenikles** [comment]
It's back 🎉. I emailed the logs as requested.

https://user-images.githubusercontent.com/788827/195453904-6f2a0ff4-cb5a-41b3-b6aa-d1771fcc031f.mov

**Comment by mbrevoort** [comment]
Logs attached for that session:
[vscode-web-logs-20221013T015851.zip](https://github.com/gitpod-io/gitpod/files/9769772/vscode-web-logs-20221013T015851.zip)

**Comment by mikenikles** [comment]
It's Firefox in my case.

**Comment by mustard-mh** [comment]
The link is an `<a>` tag, two tabs opened may relate to this (calling `preventDefault()` in codebase). 

Will check it with Firefox and Arc 🙏
