### ISSUE TITLE
Oauth Redirect 

### ISSUE THREAD

**Issue by avoorhees** [gitpod-io/gitpod#1379]
I'm running a django application that uses social auth (google authentication). 

Since django thinks the app is running on `http://127.0.0.1:8000/` the redirect after logging in is going to localhost (which obviously isn't running b/c I'm using gitpod). 

Have other people encountered a similar issue?

**Comment by ajgrayson** [comment]
I'm running dotnet, same issue though - I created a new google credentials using the workspace URL but of course that constantly changes meaning I need to keep creating new credentials each time I start working.... not ideal. Is there any better approaches?

**Comment by tylerstephens814** [comment]
Same issue

**Comment by gpalazuelosg** [comment]
Same issue on my side.

**Comment by pawlean** [comment]
@tylerstephens814 @gpalazuelosg I suggest looking into the Gitpod Local Companion app. Relevant docs [here](https://www.gitpod.io/docs/ides-and-editors/local-companion#gitpod-local-companion). Or adjusting your application to use gp URL. Relevant docs [here](https://www.gitpod.io/docs/command-line-interface#url).

**Comment by tysonrm** [comment]
If you configure your redirect to be localhost and use VSCode on your desktop ports are automatically forwarded. Localhost will route to your workspace. Otherwise, tunnel manually using ssh.
