### ISSUE TITLE
Customizeable favicon for workspaces, different icon for www.gitpod.io

### ISSUE THREAD

**Issue by abitrolly** [gitpod-io/gitpod#13812]
## Is your feature request related to a problem? Please describe

I'm always frustrated when I need to find and switch to Gitpod workspace tab after visiting a dozen of references.

## Describe the behaviour you'd like

1. Different tab icon for the main site at www,gitpod.io and tab with Gitpod workspace
2. Customizable icon for workspace in `.gitpod.yml`
3. Different favicon when workspace is loading

**Comment by gtsiolis** [comment]
Hey @abitrolly! I can totally relate to this.

I'm not sure about changing the website favicon 

1. Customizing the favicon for workspaces has been brought up again, but not sure if this is the best way forward, as this would introduce another point of friction or configuration that could go wrong.
2. Using a different favicon for the website could be interesting, but I'd definitely consider using a different one for the docs section. Cc @chrifro 
3. Opened https://github.com/gitpod-io/gitpod/issues/13837, following from a comment in https://github.com/gitpod-io/gitpod/issues/7477#issuecomment-1141049961 to propose using a different favicon based on workspace status.
