### ISSUE TITLE
[prebuild] cannot initialize workspace

### ISSUE THREAD

**Issue by Lxxyx** [gitpod-io/gitpod#1381]
### Describe the bug

Open the workspace and get error:

cannot initialize workspace: cannot initialize workspace: cannot initialize workspace: prebuild initializer: git checkout -B master origin/master failed (exit status 1): Branch 'master' set up to track remote branch 'master' from 'origin'. Reset branch 'master' Your branch is up to date with 'origin/master'. env: ‘node’: No such file or directory
Please file an issue if you think this is a bug.

### Steps to reproduce

Open https://gitpod.io/#https://github.com/midwayjs/midway

### Expected behavior

Workspace ready

### Additional information

Github Repo: https://github.com/midwayjs/midway

**Comment by Lxxyx** [comment]
Is there any progress on this issue? @JesterOrNot

**Comment by jankeromnes** [comment]
Hi @Lxxyx, no progress sorry, this issue slipped through because other incidents took priority (see https://status.gitpod.io). I'll look into it now.

**Comment by jankeromnes** [comment]
Removing label `critical`, because Gitpod doesn't seem to be down for everyone, cc @JesterOrNot.

**Comment by jankeromnes** [comment]
I was able to reproduce the issue:

<img width="1348" alt="Screenshot 2020-04-11 at 16 11 17" src="https://user-images.githubusercontent.com/599268/79046110-22e4e000-7c0f-11ea-9a59-23054c31e226.png">

**Comment by jankeromnes** [comment]
So, first of all, our system believes that there is a prebuild available for https://github.com/midwayjs/midway's latest commit https://github.com/midwayjs/midway/commit/673f07a947c2d7f13a737ac221d84508364b0553:

```
+----------------------------------------+------------------------------------------+-----------+----------------------------+
| cloneURL                               | commit                                   | state     | creationTime               |
+----------------------------------------+------------------------------------------+-----------+----------------------------+
| https://github.com/midwayjs/midway.git | 673f07a947c2d7f13a737ac221d84508364b0553 | available | 2020-04-09 06:03:36.523609 |
+----------------------------------------+------------------------------------------+-----------+----------------------------+
```

So Gitpod will try to use it. I will take a look at what the actual prebuild contains, to see if that gives any insights into what's going wrong here.

**Comment by jankeromnes** [comment]
Next, it seems that the prebuild is hosted in the `asia-east1` region, while I thought we had migrated this cluster to the `us-west1` region. Maybe that has something to do with the bug.

**Comment by jankeromnes** [comment]
Ah, when I'm inside the prebuild, and I do the command that fails, it gives me `git-hooks` errors. Maybe `git-hooks` are not well supported by Gitpod's prebuild initializer?

```
midway ((v1.18.6)) $ git checkout -B master origin/master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Switched to and reset branch 'master'
Your branch is up to date with 'origin/master'.
[GIT-HOOKS ERROR] Cannot find module '/workspace/midway/node_modules/git-hooks/lib/git-hooks'
[GIT-HOOKS ERROR] Please reinstall git-hooks to fix this error
```

**Comment by jankeromnes** [comment]
I think this is simply our prebuild system not handling git-hooks well.

I believe the error message `env: ‘node’: No such file or directory` is thrown by the `post-checkout` Git hook, probably because the prebuild loader is not an actual development environment (i.e. it's likely missing `node` in the `PATH`).

**Comment by Lxxyx** [comment]
Thanks reply,expect this issue to be fixed in a subsequent update @jankeromnes
