### ISSUE TITLE
VSCode Ports list on Safari broken icons

### ISSUE THREAD

**Issue by mbrevoort** [gitpod-io/gitpod#13819]
### Bug description

The ports list in VSCode on Safari has broken icons. See the comparison between Chrome and Safari (Version 16.0 (17614.1.25.9.10, 17614))
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/30455/195478429-c1fe2135-614a-432e-99a4-4d16db2efe03.png">

### Steps to reproduce

1. Open a workspace with ports like https://gitpod.io/#https://github.com/gitpod-io/website on Safari
2. Navigate to Ports tab

### Workspace affected

gitpodio-website-l56xwp08uod

### Expected behavior

Should appear like Chrome in screenshot

### Example repository

https://gitpod.io/#https://github.com/gitpod-io/website

**Comment by jimmybrancaccio** [comment]
This might be related to #7293.

**Comment by jeanp413** [comment]
cc @mustard-mh we should do the same as in https://github.com/microsoft/vscode/pull/176462
