### ISSUE TITLE
Support Large workspace class in preview environments (has default and small now)

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#13827]
## Is your feature request related to a problem? Please describe
We should support the same workspace classes in preview environments that are available in SaaS.

## Describe the behaviour you'd like
I am able to select different workspace classes in a preview environment.

## Describe alternatives you've considered
Continue using just the default workspace class.

**Comment by jenting** [comment]
Currently, the preview env supports default (30Gi disk) and small (20Gi disk) workspace classes already. @Furisto

**Comment by jenting** [comment]
Related PR and comment https://github.com/gitpod-io/gitpod/pull/13223#pullrequestreview-1121896332
