### ISSUE TITLE
UX: Open Workspace in New Tab

### ISSUE THREAD

**Issue by megafinz** [gitpod-io/gitpod#13826]
## Is your feature request related to a problem? Please describe
Currently if I need to open multiple workspaces I need to:
1. Open https://gitpod.io (assume that I'm logged in to https://gitpod.io already).
2. Left-click on the "Actions" button to open the context menu of Gitpod.
3. Right-click on the "Open" menu item to open the browser context menu.
4. Click "Open Link in New Tab" menu item.
5. Repeat 2–4 for every workspace I'd like to open.

## Describe the behaviour you'd like
Would be nice if:
a. "Open" menu item would open the workspace in new tab by default instead of having to go through "Right-click → Open Link in New Tab" sequence. I use touchpad so I don't have the middle-click-to-open-link-in-new-tab gesture option out of the box. This will reduce number of actions required to open a workspace from 3 to 2.
b. (Ideal) There would be an "Open" button visible for the inactive workspaces (near the current "Actions" button) in the list items in the "Workspaces" list that would do the same.  This will reduce the number of actions required to open a workspace from 3 to 1.

## Additional context
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/1543216/195550146-cb3d6bd9-6ce4-44d9-a420-c55cc8c034cc.png">

**Comment by harshsinghatz** [comment]
What if someone doesn't want their workspace to open on another tab? I guess currently one can you do both if they wish to

**Comment by megafinz** [comment]
> What if someone doesn't want their workspace to open on another tab? I guess currently one can you do both if they wish to

To me this looks like a non-issue. Is there any inconvenience in opening a new tab in this case?

**Comment by axonasif** [comment]
cc @gtsiolis

**Comment by megafinz** [comment]
@axonasif welp, today I learned, thank you for that :)
1. Didn't know you could cmd-click a link to open it in a new tab.
2. Didn't know you could click a workspace name to open it.
