### ISSUE TITLE
Improve default usage limit UX when upgrading to Stripe

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#13835]
## Is your feature request related to a problem? Please describe

**Currently**: When you upgrade to Stripe, the front-end picks a sensible initial value for your new cost center (1000 credits * team members). You can then adjust this limit based on your liking once the upgrade process is complete.

**Possible alternatives**:
- Move the initial value selection logic back to server (see proposal: https://github.com/gitpod-io/gitpod/pull/13746#discussion_r993349823)
- Ask the new customer to confirm or edit this limit while they upgrade (see proposal: https://github.com/gitpod-io/gitpod/pull/13535#issuecomment-1265647634)

**Comment by jldec** [comment]
Thanks @jankeromnes - the current behavior of setting the default based on the member count is already much better that before :)
