### ISSUE TITLE
Workspace files lost after timeout

### ISSUE THREAD

**Issue by ghost** [gitpod-io/gitpod#13862]
### Bug description

Created a workspace and left it idle for sometime all the files i created under /workspace/ directory is lost.

### Steps to reproduce

Create a workspace 
Create a file in /workspace/ directory
Let the workspace timeout  

### Expected behavior

To have the files not getting removed and be persistent.

**Comment by axonasif** [comment]
The issue author's account seems to be deleted here on GitHub. Going to close this.
