### ISSUE TITLE
Unusable workspaces due to high load on the node (WS-EU01)

### ISSUE THREAD

**Issue by isontheline** [gitpod-io/gitpod#1386]
### Describe the bug
I cannot use my workspaces because of the high load on the node :
![Capture d’écran 2020-04-10 à 20 37 03](https://user-images.githubusercontent.com/44212923/79014441-35a5d900-7b6b-11ea-8d2b-4e4c4e12394f.png)

### Steps to reproduce
Just launched my workspaces as usual

### Expected behavior
A load less than 5.0/10.0

### Additional information
Node : WS-EU01

**Comment by jankeromnes** [comment]
Hi @isontheline, thank you for reporting this, and sorry for the disrupted development experience.

Yesterday evening (CEST), a server in the `ws-eu01` cluster started seeing unusually high CPU load. I had marked it for removal from the cluster, but for some reason, it only got removed around 45 minutes ago.

We'll investigate what happened there, and see how we can restore service quality much faster next time something similar happens. I think the load should be back to normal levels, but please do report if you see high loads again.
