### ISSUE TITLE
image-builder: Use `zstd` for a workspace image compression instead of `gzip`

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#13861]
## Is your feature request related to a problem? Please describe

Support for zstd[^1][^2][^3] compression, now we are using `gzip`, which is default for `buildkit`
zstd is said to be much faster than gzip.

[^1]: https://www.infoq.com/news/2022/09/amazon-gzip-zstd/
[^2]: https://aws.amazon.com/blogs/containers/reducing-aws-fargate-startup-times-with-zstd-compressed-container-images/
[^3]: https://www.slideshare.net/KoheiTokunaga/starting-up-containers-super-fast-with-lazy-pulling-of-images

dazzle has already implemented https://github.com/gitpod-io/dazzle/pull/58

AFAI, the implementation is simply to add `compression=zstd` to the following line. So it is worth a try.
 https://github.com/gitpod-io/gitpod/blob/2c451bcf7c642c26701aba4b8a74424d0376a140/components/image-builder-bob/pkg/builder/builder.go#L141

## Describe the behaviour you'd like

Pull and push a workspace image with `zstd`.
You should be able to check the manifest using [oci-tool](https://github.com/csweichel/oci-tool).

## Additional context

docker (or rather moby) has not yet released a version that supports `zstd`. Implementation is complete.

**Comment by kylos101** [comment]
@utam0k can you update the issue description to better describe how this will benefit users? For example, will users see time savings when pulling container images? If yes, what is the expected time savings?

**Comment by kylos101** [comment]
For now I've classified this change as "user quality of life". In other words, it does not seem like it is an essential change that we need "now". Is that right, @aledbf and @utam0k , that it's a nice to have? I'm just trying to make sure I understand the related motivation or "the why" for this issue.

**Comment by utam0k** [comment]
@kylos101 Thanks for your comment.
We could take detailed data, but that would take some time. For example, how small the size of the image will be and the time it will take to affect the startup of the container. We didn't dare to do that this time because I need time. Do you want me to decide on a time box and take data?

**Comment by utam0k** [comment]
> For now I've classified this change as "user quality of life". In other words, it does not seem like it is an essential change that we need "now".

yes, However, I expect implementation to be fairly straightforward.

**Comment by kylos101** [comment]
> Do you want me to decide on a time box and take data?

:wave: @utam0k no, thank you for asking, though. :smile:  Please ignore this issue for now, let's leave in the inbox. That way, you can focus on groundwork that is either in-progress or scheduled.

**Comment by utam0k** [comment]
> > Do you want me to decide on a time box and take data?
> 
> :wave: @utam0k no, thank you for asking, though. :smile:  Please ignore this issue for now, let's leave in the inbox. That way, you can focus on groundwork that is either in-progress or scheduled.

I agree with you👍 I was just going to write the issue as an idea as I don't think we should spend time on it now either.

**Comment by atduarte** [comment]
> For now I've classified this change as "user quality of life".

@kylos101 how does this benefit the end user? Shorter workspace startup times?

**Comment by kylos101** [comment]
> how does this benefit the end user? Shorter workspace startup times?

Yes @atduarte , shorter workspace startup times on image build and pull, specifically.

We'd have to change parts of our stack, though. Dazzle, image-builder-mk3, and registry-facade. I'm not sure about IPFS. There may be others.

Related internal conversations [[1](https://gitpod.slack.com/archives/C02F19UUW6S/p1661162400187349)][[2](https://gitpod.slack.com/archives/C02F19UUW6S/p1665897973035959)]
