### ISSUE TITLE
Prompt users to restart unhealthy workspaces

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#13877]
Unfortunately sometimes workspaces have a bad deploy (it happens). We need some way to push notifications (or highlight) to users to prompt them to restart a workspace if it's unhealthy for some reason. This could surface in the IDE or the dashboard.

**Comment by loujaybee** [comment]
We should consider adding "tainted" or other as an official workspace status. Relates to: 

- https://github.com/gitpod-io/website/pull/2858/files

**Comment by axonasif** [comment]
Test comment (please ignore 🙏 )
