### ISSUE TITLE
Manual functional testing for doing image builds in workspace cluster

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#13881]
1. In addition to all of [these use cases](https://www.gitpod.io/docs/configure/workspaces/workspace-image) working
2. We also need image builds to work from private registries associated with Gitpod Projects, too. [Draft instructions](https://github.com/gitpod-io/website/issues/1704#issuecomment-1275403894) are located here.

**Comment by WVerlaek** [comment]
These tests are done, including the private image registry test (used `ghcr.io`)
