### ISSUE TITLE
Clarify notification to "remove projects under personal accounts in Q1'2023."

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13892]
Users with projects under their personal accounts currently see the following notification. This was introduced in #13414

> We'll remove projects under personal accounts in Q1'2023.`

This should be changed so that users are not left thinking that their project data will be deleted. Suggested wording:

> Projects under personal accounts have been [deprecated](https://www.gitpod.io/docs/configure/projects), please add new projects under a team. Existing personal projects will continue to work for now, but may require migration to a team in future.

The docs page for projects should be also updated to include a deprecation notice. see https://github.com/gitpod-io/website/issues/2934

#### Example of the current notification

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/849592/196034264-fe7d5b87-ea02-46ee-a5f4-03e3917c5206.png">

**Comment by gtsiolis** [comment]
Cross-posting below a relevant comment (https://github.com/gitpod-io/gitpod/pull/13414#discussion_r986977342) from the UX review in the initial PR that added this alert:

> Probably not the best line to comment for this, but here's an alert we could use to inform users about projects deprecation under personal accounts. Things to consider:

> 1. Making the copy focus on the positive aspects of this change.
> 2. Nudge users with the best action forward, that is creating a team.
> 3. Make this closable to avoid getting into the face of users if they decide this is something they want to dismiss.

> | Alert to inform users about projects deprecation under personal accounts |
> |-|
> | <img width="1440" alt="Screenshot 2022-10-04 at 3 57 43 PM (2)" src="https://user-images.githubusercontent.com/120486/193852274-144441c1-100c-494b-9fae-365d092b60e3.png"> |

**Comment by gtsiolis** [comment]
This is no longer relevant as the message has been removed in https://github.com/gitpod-io/gitpod/pull/15784. Cc @svenefftinge @jldec
