### ISSUE TITLE
Support for ion

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1389]
Requesting support for ion https://github.com/redox-os/ion
- vscode extension unknown

**Comment by JesterOrNot** [comment]
I'll give it a shot see https://github.com/JesterOrNot/Gitpod-Ion

**Comment by JesterOrNot** [comment]
Done!

![image](https://user-images.githubusercontent.com/50386709/79055696-a7862d00-7c14-11ea-9fe1-269e77a79484.png)

**Comment by Kreyren** [comment]
That was fast O.o thanks ^-^
