### ISSUE TITLE
Can't scroll in visual studio code while using Safari

### ISSUE THREAD

**Issue by RLungarella13** [gitpod-io/gitpod#13893]
### Bug description

I open my gitpod workspace and everyting works fine, but when i try to scroll nothing happens. I am using a magic keyboard but it doens't work with fingers either. I tried using other browsers, Chrome worked, but I don't like how it is optimized with the magic keyboard. Is there a fix?

### Steps to reproduce

Opening a gitpod workspace

**Comment by axonasif** [comment]
Hi @RLungarella13, can you try in https://vscode.dev as well? Does it work there?

**Comment by RLungarella13** [comment]
@axonasif yeah it works fine in https://vscode.dev

**Comment by axonasif** [comment]
Ok, that's interesting. How about you try the insider version of vscode on Gitpod?
You check select that here: https://gitpod.io/preferences
Then create a new workspace.

**Comment by RLungarella13** [comment]
@axonasif Okay I tried different things. First of all I made a mistake on the previous comment because vscode.dev doens't work when opened with safari, it previously worked beacuse I opened the link in g-mail and it didn't directally redirect me on safari but it was a pop-up page of g-mail (I don't know if i am explaining myself sorry for my bad english :( ). I tried using the insider version of vscode of gitpod but it's the same thing.

**Comment by akosyakov** [comment]
I think it should be reported in upstream: https://github.com/microsoft/vscode

**Comment by akosyakov** [comment]
@jeanp413 @mustard-mh Maybe you are aware about any issues in upstream. I don't think we can do anything on our side, since we simply consume VS Code for that. Closing?

**Comment by jeanp413** [comment]
@RLungarella13 if you can repro in vscode.dev then please create an upstream issue in vscode repo :pray:
