### ISSUE TITLE
Live Sare crash

### ISSUE THREAD

**Issue by blablanumerodeux** [gitpod-io/gitpod#1392]
### Describe the bug

When creating a shared session i get this: 
```
Plugin runtime crashed unexpectedly, all plugins are not working, please reload the page. If it doesn't help, please check Theia server logs.
```

### Additional information

https://db86aebf-1040-47ed-923f-2fc36f438ae9.ws-us02.gitpod.io/

**Comment by svenefftinge** [comment]
Can you provide a pointer to your repository or share a snapshot URL?

**Comment by blablanumerodeux** [comment]
here you go: 

[snapshot](https://gitpod.io#snapshot/c9c670a6-6152-4cbc-9a63-5d1112ab340b)
