### ISSUE TITLE
ws-daemon: could not get handle for network namespace: no such file or directory

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#13931]
### Bug description

We saw the ws-daemon reports `could not get handle for network namespace: no such file or directory` in gen70 and gen71 clusters.

### Steps to reproduce

- gen71 https://cloudlogging.app.goo.gl/RUApqS6RpLJ9jzZH8
- gen70 https://cloudlogging.app.goo.gl/7CZhRLunDooVbQtdA

### Expected behavior

Is it cosmetic? If not, then we should check what's wrong instead of keep logging it.

**Comment by Furisto** [comment]
This is related to network limiting. I guess same issue as we have seen before with workspaces being stopped but dispatch still thinking they exist. Would have to look into it more to be sure though. If this is something more than a delay between workspace stop and us getting notified we would see it as an issue with observability, it would not impact the user experience.
