### ISSUE TITLE
KOTS upgrade function "HTTPSProxy" not defined

### ISSUE THREAD

**Issue by scasei** [gitpod-io/gitpod#13933]
### Bug description

On upgrade to 2022.9.0 or 2022.9.1 I get following error:

> Upstream Update
> failed to pull: failed to render upstream: failed to convert upstream file gitpod-http-proxy-settings.yaml to base: failed to render file template: failed to get template: template: gitpod-http-proxy-settings.yaml:14: function "HTTPSProxy" not defined

### Steps to reproduce

Start kots admin with `kubectl kots admin-console --namespace gitpod`
And go to browser http://localhost:8800

Then hit button `Download` at `New version available` / `2022.9.1`

### Expected behavior

Gitpod will upgrade to upstream version

### Anything else?

Maybe related: https://github.com/gitpod-io/gitpod/issues/10769

**Comment by MrSimonEmms** [comment]
You will need to upgrade your KOTS CLI to the latest version. This [function](https://docs.replicated.com/reference/template-functions-static-context#httpsproxy) was recently added

**Comment by scasei** [comment]
Thank you, works, just for completeness:

```
curl https://kots.io/install | bash
kubectl kots admin-console upgrade --namespace gitpod
```
