### ISSUE TITLE
Backups: allow user to download workspace backup from the volume snapshot

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#13930]
## Is your feature request related to a problem? Please describe

Gitpod supports downloading the workspace content (from GCS). After we switch backup mechanism from GCS to GCP snapshots, we can't let the user download the workspace content anymore. We should consider supporting download workspace content if the user backup mechanism is the GCP snapshot.

## Describe the behaviour you'd like

Support downloading the workspace content from the GCP snapshot.

## Describe alternatives you've considered

Do not implement download workspace backup from existing volume snapshot

## Additional context

#7901

**Comment by jenting** [comment]
I created this issue and assigned it to @sagor999 because the RFC is under review.

**Comment by kylos101** [comment]
@jenting I'm not sure that this should be in-progress, yet. For example, we haven't made a decision yet on the RFC. Can you remove status for now?

**Comment by jenting** [comment]
> @jenting I'm not sure that this should be in-progress, yet. For example, we haven't made a decision yet on the RFC. Can you remove status for now?

Okay, removed. Because I thought RFC is also an in-progress.

**Comment by kylos101** [comment]
RFC is a medium or vehicle we use to make a decision as an async team. Depending on the decision, we'll then know if this issue is needed or if it can be closed. Additionally, if it is needed, we'll better understand the related urgency, which'll help with prioritization/planning.
