### ISSUE TITLE
Show more details about the "Last Successful Prebuild"

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#13944]
## Is your feature request related to a problem? Please describe

This is a follow-up to https://github.com/gitpod-io/gitpod/pull/13801 which introduced a `Use Last Successful Prebuild` button in the "Prebuild in Progress" screen:

<img width="600" alt="Screenshot 2022-10-18 at 12 17 51" src="https://user-images.githubusercontent.com/599268/196403794-d0d84438-c3df-4b23-8cc7-7216b7c79061.png">

It would be nice to show details about this "last successful prebuild" that you can use, e.g.:
- What commit is it based on? How old is that commit? How much has changed since that commit?
- How long did this older prebuild originally take to build?

## Describe the behaviour you'd like

> - would like to see the details of the last prebuild:
>   - what was the commit point of the last prebuild, how many commits since, some sense of the delta
>   - how long did it take? (oh 40 minutes, the current prebuild is at 3 minutes so it’s going to be a long time if I wait)

Source: https://github.com/gitpod-io/gitpod/pull/13801#issuecomment-1281704711

Here is a quick super-ugly attempt to show such information directly inside the `Use Last Successful Prebuild` button:

<img width="200" alt="Screenshot 2022-10-18 at 09 08 31" src="https://user-images.githubusercontent.com/599268/196400996-18e3838f-cf16-4257-a36b-97f281dd8c5c.png">

**Comment by jankeromnes** [comment]
On a side note: This `Use Last Successful Prebuild` button doesn't have to be right next to `Skip Prebuild` -- it could actually also be moved into a dropdown menu, e.g. like so:

```
           [ Skip Prebuild | v ]
 ______________________________
| Use Last Successful Prebuild |
|              ...             |
|______________________________|

**Comment by jankeromnes** [comment]
Good point @laushinka!

Also, if it helps, here is some inspiration taken from GitHub and GitLab on how to give a sense of "How much has changed since commit X?" (but basically, it's a total number of added lines & removed lines):

| GitHub | GitLab |
| --- | --- |
| <img width="499" alt="Screenshot 2022-10-19 at 17 30 44" src="https://user-images.githubusercontent.com/599268/196737019-ba4e23a1-c28a-4b19-b13a-37f0bdc21769.png"> | <img width="449" alt="Screenshot 2022-10-19 at 17 33 23" src="https://user-images.githubusercontent.com/599268/196737694-acc730d5-7e97-43d8-b91a-d985e4dabd11.png"> |
| <img width="324" alt="Screenshot 2022-10-19 at 17 30 57" src="https://user-images.githubusercontent.com/599268/196737025-b1794191-1c9b-4e72-96c7-b1f68cfd3bfd.png"> | <img width="834" alt="Screenshot 2022-10-19 at 17 33 01" src="https://user-images.githubusercontent.com/599268/196737690-67d8f745-6aa2-40b5-a2d9-887b0d2dd07f.png"> |

**Comment by jankeromnes** [comment]
@geropl Good catch! No, I indeed think that our current approach (automatically re-using an older prebuild when possible) is better than offloading choice and complexity onto our users.

Let's close this ticket for now. I believe https://github.com/gitpod-io/gitpod/issues/14479 is now the more relevant issue, if we want to provide more clarity to users when an older prebuild is used, but I'd also consider that one low-priority until we get more user feedback (e.g. if users are never confused about which prebuild is being used, I guess that would mean we did a good job making the prebuild-selection intuitive and unproblematic -- in that case, maybe we wouldn't even need extra clarification).

@gtsiolis apologies for the back-and-forth here! I hope you hadn't started spending time on a design here. 🙈

**Comment by gtsiolis** [comment]
Thanks for the ping, @jankeromnes!

> I hope you hadn't started spending time on a design here.

No, this was still on the **[product design inbox](https://github.com/orgs/gitpod-io/projects/29)**. 😁 

> I believe https://github.com/gitpod-io/gitpod/issues/14479 is now the more relevant issue

Let's keep that open as you mentioned to keep track of this. I think bringing better visibility of which commit you're using in the prebuild could be useful on the workspace start, if not also on the workspaces list. 💭
