### ISSUE TITLE
Epic: Create an X-Large (16 cores, 32GB) workspace class

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#13950]
## Is your feature request related to a problem? Please describe
Users using monorepos or other big projects experience friction in using Gitpod. They either experience poor performance or limit themselves to run less tools and services at a time reducing productivity.

## Describe the behaviour you'd like
Have an option to use a 16 cores, 32GB RAM, 100GB of /workspace disk on gitpod.io

ID: g1-xlarge
Name: X-Large
Description: Up to 16 vCPU, 32GB memory, 70GB disk

## Additional context
Internal feedback [1](https://gitpod.slack.com/archives/C01KPEPNBD0/p1666072709501839), [2](https://gitpod.slack.com/archives/C01KPEPNBD0/p1665054185507829), ...

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3t24q)

**Comment by gtsiolis** [comment]
Re-posting from a relevant discussion (internal):

> ... from UX perspective if want to offer a third option alongside the two other options (Standard, Large) it would be nice if we could not use a break line for the third option as all three break out of the container.

> Unlike the editor options, which scale better and we also need to update soon, for the workspace class selection would be better if users had to choose through a linear list of options so that they feel like they are selecting from a range of increasingly better options, not just alternatives.

Ways forward:
1️⃣  Introduce a third option in a new line and improve the UX in future iterations.
2️⃣  Keep the vertical alignment but use narrower width, see screenshot below.
3️⃣  Introduce a more flexible component or pattern like a dropdown, see [#13116](https://github.com/gitpod-io/gitpod/issues/13116) and [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1663669797298519?thread_ts=1663594639.896499&cid=C01KPEPQYE6) (internal).

| Early design for going with option 2️⃣ |
|-|
| <img width="750" alt="Screenshot 2022-11-28 at 7 15 10 PM" src="https://user-images.githubusercontent.com/120486/204815479-d24465e4-d6e2-4e15-8730-3cfa9de1dc62.png"> |

**Comment by smiley9000** [comment]
what about 8v cpu 16gb memory and 320gb ssd

**Comment by tanmay-veer** [comment]
> what about 8v cpu 16gb memory and 320gb ssd

Hell yeah that will be awesome
We need it for llmops
