### ISSUE TITLE
[UBP] Personal usage is hard to reach or discover, and hard to differentiate from team usage pages

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13968]
The personal usage page can currently only be reached throught the personal usage-based billing settings page.

## suggestions
1. Add "Usage" back into the personal settings menu under Billing (only for feature flagged UBP users) - see image below.
2. Differentiate the usage page main heading to say either "Personal Usage" or "Team Usage" 

<img width="1079" alt="Screenshot 2022-10-18 at 19 20 13" src="https://user-images.githubusercontent.com/849592/196501256-83cad01c-b5c2-48f9-915b-55ca6074a074.png">

**Comment by jldec** [comment]
cc: @gtsiolis

**Comment by jankeromnes** [comment]
FYI, here is an alternative UX proposal from [Slack](https://gitpod.slack.com/archives/C027AUU7BC3/p1666880831028449?thread_ts=1666879099.675049&cid=C027AUU7BC3) (internal):

> For the navigation, I would remove the menu entry for `usage` in the settings, so that we can only navigate there from the button on the billing page. We could add a "<- back to settings" link on top if you think that is necessary. :a: would also mean we need the selector for the individual account again. :b: wastes screen estate, which will be very precious in future versions of the usage view.

> If we really need a top-level menu entry for personal usage it should go under the context menu on the avatar not settings.
