### ISSUE TITLE
Unknown team path renders a page instead of a 404

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#13988]
### Bug description

When we go to `https://gitpod.io/t/[team-name]/[gibberish-project-name]` that doesn't exist, it renders the page instead of a 404.

https://www.loom.com/share/94bf6a95ae394157ab1b2dd49209ae99

### Steps to reproduce

1. Go to `https://gitpod.io/t/gitpod/blablabla`
2. It succeeds and you see the usual tabs for a project.

### Expected behavior

Shows a not found page or redirects.

**Comment by gtsiolis** [comment]
This also affects prebuilds, causing more side effects like #7689. For example:
- https://gitpod.io/t/gitpod/gitpod/593b3957-c384-473c-baf1-non-existing-URL 
- https://gitpod.io/t/gitpod/non-existing-project/593b3957-c384-473c-baf1-non-existing-URL

Other problems with URLs include:
1. #5516
2. #11510
