### ISSUE TITLE
[PVC] the prebuild workspace is unable to be up and running

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#13980]
### Bug description

The prebuild workspace is unable to be up and running.

It's the limitation of the GCP regional disk. We can't create a new zonal persistent disk from the same snapshot in the same zone, more than once in 10 minutes. https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-snapshots#creating_new_zonal_persistent_disks_from_snapshots

### Steps to reproduce

Enable the projects prebuild PVC

https://gitpod.slack.com/archives/C02F19UUW6S/p1666105041014279

### Expected behavior

The prebuild workspace should be up and running.

### Anything else?

#7901

**Comment by kylos101** [comment]
@jenting can you pause on this issue and its PRs? [Let's wait to see if Google can remove the snapshot/volume limit.](https://gitpod.slack.com/archives/C02F19UUW6S/p1666218318835349?thread_ts=1666105041.014279&cid=C02F19UUW6S) I ask because we may proceed and do PVC just for regular workspaces.

**Comment by kylos101** [comment]
@jenting adding blocked label for the meantime, I recommend looking at alternative groundwork for the meantime. @sagor999 if you need any help from @jenting let him know? 🙏

**Comment by jenting** [comment]
Internal discussion https://www.notion.so/gitpod/Next-steps-for-PVC-given-snapshot-volume-limits-593d5d804e734f459a8935208b57903b

**Comment by jenting** [comment]
For prebuild workspaces, we'll use GCP image to backup prebuild workspace PVC.
For regular workspace, we'll use GCP snapshot to backup regular workspace PVC.

**Comment by jenting** [comment]
PR both merged, waiting for the deployment, and closing it.
