### ISSUE TITLE
Webhooks for GitLab projects are disabled on Unauthorized Errors

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#13985]
**Issue**

We've learned now that GitLab webhooks are disabled automatically if the receiver (Gitpod) is responding with status codes other than 2xx. The rules for [failing webhooks](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#failing-webhooks) are basically:
* on 5xx responses -> disable temporarily
* on 4xx responses -> disable permanently, which requires manual re-enabling on GitLab

There seems to be at least two cases where the Unauthorized Error might occur:
* when the Gitpod user who created the project disconnects from the GitLab integration.
* (as we assume after scanning logs) when there are repository forks involved, for which webhook events are registered, but the Gitpod users is not authorized. 

In any case, we should not upset GitLabs when webhooks cannot be triggered. 

**Solution**

On Unauthorized Errors the GitLab webhook handler should respond with a code 2xx. 

Further we should investigate
* the errors on events for repository forks.
* how to make Unauthorized Errors visible to project owners.

**Comment by geropl** [comment]
@AlexTugarev Can we close this one? Looking at the activities it looks this might be a left-over.
