### ISSUE TITLE
bitbucket server does not install webhooks

### ISSUE THREAD

**Issue by jmls** [gitpod-io/gitpod#13998]
### Bug description

When trying to setup a prebuild hook , prefixing the url with gitpod.io/#prebuild/  *does not* create the BB webhook.

it does create the webhook for BB cloud.

### Steps to reproduce

Create a new repo, and gitpod project. prefix the branch url with `gitpod.io/#prebuild/ `

### Expected behavior

webhook to be created on the repo

**Comment by AlexTugarev** [comment]
Hi! The prebuild-context URLs are considered deprecated since the introduction of projects, see https://github.com/gitpod-io/gitpod/issues/4353

cc. @jldec

**Comment by AlexTugarev** [comment]
I see. In this case the mentioning of the `prebuild` prefix-URL was misleading for me. Webhooks are supposed to be created on project creation.

Let me try to find something related in the logs.

**Comment by AlexTugarev** [comment]
@jmls, I couldn't find any errors related to BBS webhooks. 

Could you try to reproduce again, please? Make sure you have proper permissions for the test repository you'd want to add as project – it should be "REPO_ADMIN" or "PROJECT_ADMIN". 

Also, please do not try with the `#prebuild/` prefix-URL.

**Comment by AlexTugarev** [comment]
We've added proper logging to shad some light on the issue with creating webhooks on BBS instances. @jmls, once this is deployed, it would be awesome to repeat the procedure with a second test repository of yours. We need to understand the situation properly, which requires to capture the errors response. 
🙏🏻  I'll ping you.
