### ISSUE TITLE
New user with default OAuth scope cannot see branches for private repos in a project

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#13996]
- Start using Gitpod as a new user
- Create your first project by selecting a private repository
- The project will be created but the branches list fails silently

The console says:
`Getting branches failed Error: Request getProjectOverview failed with message: Not Found`

**Comment by jldec** [comment]
Adjusting your [integration](https://gitpod.io/integrations) permissions (OAuth scopes) to allow access to private repos fixes the sympton.

**Comment by jldec** [comment]
Scheduling this since it adds an easily encountered friction point for new, onboarding users.

**Comment by AlexTugarev** [comment]
Just for completeness: 
* the proposal would work to fix if the repo is accessible to the user.
* if the private repo is in an unauthorized org, the error will still be the same, thus we might need to render a hint explaining the situation.
