### ISSUE TITLE
For users with no teams the "New Team" button hides the Personal Account with projects

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14002]
The issue applies to users who have no team memberships, but who **do** have Gitpod projects under their personal account.

The New Team button hides the Personal Account selector, so projects can no longer be accessed.
Adding a team reveals the Personal Account selector and projects.

<img width="848" alt="Screenshot 2022-10-19 at 15 04 48" src="https://user-images.githubusercontent.com/849592/196699495-0d8e328e-dbd7-4222-83e6-ad1e21694fcd.png">

---

Add a team
<img width="833" alt="Screenshot 2022-10-19 at 15 05 22" src="https://user-images.githubusercontent.com/849592/196699507-963a896c-8d78-473e-8eca-6d6185f35c3e.png">

---

<img width="856" alt="Screenshot 2022-10-19 at 15 05 48" src="https://user-images.githubusercontent.com/849592/196699525-f4003c7d-288d-446f-a4ff-8024860a88c3.png">

cc: @gtsiolis

**Comment by gtsiolis** [comment]
@jldec Nice catch, I can reproduce this! ⚾
