### ISSUE TITLE
Change new project flow to remove the personal account option

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14037]
Leftover from #14036

**Comment by gtsiolis** [comment]
This is still something we'd like to remove, unless we work first on removing all projects form personal account (https://github.com/gitpod-io/gitpod/issues/14035) or migrating all user attribution to teams (https://github.com/gitpod-io/gitpod/issues/15665).

Cc @geropl @svenefftinge @jldec

**Comment by gtsiolis** [comment]
Closing this as it's no longer relevant. Org selection is now no longer needed. Cc @atduarte for visibility.
