### ISSUE TITLE
[PVC] investigate we could avoid the cannot mount workspace error

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#14032]
### Bug description

The user hits the `cannot mount workspace` error. Not sure if it's an intermediate state or not.
If it's an intermediate state, we could ignore it just like we ignore [the error here](https://github.com/gitpod-io/gitpod/blob/537a6801f0967e246776c9fab8b466d5a50371f6/components/ws-manager/pkg/manager/status.go#L618-L621).
If not, see if we could recreate the PVC and remount rather than report the error to the user.

It causes the `cannot mount workspace` error comes first and then makes the [issue](https://github.com/gitpod-io/gitpod/issues/14030) happens.

https://gitpod.slack.com/archives/C0201TXMV54/p1666253166702419

### Steps to reproduce

We don't know.

### Anything else?

#7901

**Comment by kylos101** [comment]
@sagor999 this error happened in `us72` and `eu71`. 

[Logs](https://cloudlogging.app.goo.gl/dQfpuUx7ButLEKs27)

However, what's really weird about this is, one of the instances that landed in `us72` also landed (with the same ID) in `us71`.

[Logs for one instance](https://cloudlogging.app.goo.gl/a9RVAknmayzb2e9U9)

Looping in @geropl , because I believe this is not supposed to happen.

**Comment by sagor999** [comment]
>However, what's really weird about this is, one of the instances that landed in us72 also landed (with the same ID) in us71.

maybe because each StartWorkspace request selects cluster prior to making the call? And due to traffic shift in the process, it landed on a different cluster.

**Comment by kylos101** [comment]
@geropl I'll create a separate issue to socialize the below:

I would have expected **startWorkspace** requests to different clusters to have used different instance IDs. I could also be wrong.

I recall that `ws-manager-api` [retrys](https://github.com/gitpod-io/gitpod/blob/c46250a72e1aa4c5cf24c359a29fe167d9cb2094/components/ws-manager-api/typescript/src/promisified-client.ts#L112), it seems like it is [initialized to zero retry attempts](https://github.com/gitpod-io/gitpod/blob/c46250a72e1aa4c5cf24c359a29fe167d9cb2094/components/ws-manager-api/typescript/src/promisified-client.ts#L53), though in the [logs](https://cloudlogging.app.goo.gl/AXSeLVBTeME4w8gPA) it looks like it is retrying. Perhaps the retries use the same instanceID?

For example, the [first one](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-20T06:28:49Z;query=resource.labels.container_name%20:%20%2528%22ws-manager%22%2529%0Aresource.labels.cluster_name%20:%20%2528%22us71%22%20OR%20%22us72%22%20OR%20%22eu71%22%20OR%20%22eu72%22%2529%0A%22b3e04860-915f-4ba7-b799-963c2961ae21%22%0Atimestamp%3D%222022-10-20T05:51:46Z%22%0AinsertId%3D%22nnj62zuyk5cq6aed%22;summaryFields=resource%252Flabels%252Fcluster_name,jsonPayload%252FinstanceId:false:32:beginning;timeRange=2022-10-19T18:29:03.504Z%2F2022-10-20T18:29:03.504Z?project=workspace-clusters) was to `us71`, and 7 seconds later the [second one](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-20T06:28:49Z;query=resource.labels.container_name%20:%20%2528%22ws-manager%22%2529%0Aresource.labels.cluster_name%20:%20%2528%22us71%22%20OR%20%22us72%22%20OR%20%22eu71%22%20OR%20%22eu72%22%2529%0A%22b3e04860-915f-4ba7-b799-963c2961ae21%22%0Atimestamp%3D%222022-10-20T05:58:46Z%22%0AinsertId%3D%223dblmw3f0yrff6s8%22;summaryFields=resource%252Flabels%252Fcluster_name,jsonPayload%252FinstanceId:false:32:beginning;timeRange=2022-10-19T18:29:03.504Z%2F2022-10-20T18:29:03.504Z?project=workspace-clusters) was to `us72`. :thinking: 

There are some [logged warnings](https://cloudlogging.app.goo.gl/hetPGZ7gBPVc1NxeA) for [server where it cannot connect and retries](https://github.com/gitpod-io/gitpod/blob/c46250a72e1aa4c5cf24c359a29fe167d9cb2094/components/ws-manager-api/typescript/src/promisified-client.ts#L90).

**Comment by svenefftinge** [comment]
FWIW I just had the "cannot mount workspace" error when starting gitpodio-gitpod-zjkqtz6c188. 
Giving it another try worked.

**Comment by jenting** [comment]
Two options:
- We could consider treating the"cannot mount workspace" error as an intermediate state in ws-manager, just like what we did in PR #13760
- We could delete the workspace pod and recreate a new workspace pod once we hit the "cannot mount workspace" error, just like what we did in PR #11690

**Comment by sagor999** [comment]
@jenting lets try with first option first (`We could consider treating the"cannot mount workspace" error as an intermediate state in ws-manager`) and if that not going to fix it, then we can go with option two of recreating the pod.
Since it is hard to repro and verify this issue, we would have to deploy option 1 first and see if that would resolve this problem.
