### ISSUE TITLE
Introduce a progress indicator component for the balance used element in the billing page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#14049]
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/pull/13564, the **billing** page was updated to include a section for the _balance used_ in personal account and teams. The component used the **[progress indicator](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress)** HTML element, however, styling the progress indicator is not fully compatible across all browsers, specifically Firefox[[1](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-progress-value)][[2](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-progress-bar)][[3](https://caniuse.com/?search=progress-bar)].

This is causing the **progress bar** element to render differently on Firefox when compared to other browsers when using the dark theme. 🌔 

| Chrome | Firefox |
|-|-|
| <img width="610" alt="balance-chrome" src="https://user-images.githubusercontent.com/120486/196988492-ccbaebd8-fc64-4f9e-bd84-33c2110c1ab0.png"> | <img width="610" alt="balance-firefox" src="https://user-images.githubusercontent.com/120486/196988496-a75ac017-9b14-4a10-8297-a6b31c46ca9d.png"> |

Plus, the HTML progress indicator comes with some rendering challenges when used with border radius, see screenshot below.

<img width="781" alt="Screenshot 2022-10-20 at 7 13 22 PM" src="https://user-images.githubusercontent.com/120486/197002889-19ad7580-c4f2-467b-86c9-814b35ee328a.png">

See [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1666271013855189) (internal). Cc @jankeromnes 

### Proposal

For more context, using custom colors for an element like the progress indicator can help to render the component with more accessible colors, and provide flexibility in terms of style and structure that can be used on different color themes (light, dark), viewports (desktop, mobile), etc.

<img width="535" alt="Frame 1117" src="https://user-images.githubusercontent.com/120486/196992124-b0368a8f-9913-433c-921e-17ab46d91fbd.png">

### Designs

Going with the suggested colors from https://github.com/gitpod-io/gitpod/pull/13564#discussion_r988978175 would be a good MVC. 🟢 

> @gtsiolis: ... could we easily make this more dark-theme-friendly? Using green-500 for the bar fill and gray-600 for the background fill could suffice, see draft design below.

**Comment by yashikajotwani12** [comment]
Hey @gtsiolis, I would like to work on this issue.

**Comment by gtsiolis** [comment]
@RayAsh37 This is about the progress bar looking like the one in light theme in Firefox. You can see the different between Chrome and Firefox for example using dark theme, see screenshot below.

<img width="328" alt="Screenshot 2023-04-26 at 23 12 54" src="https://user-images.githubusercontent.com/120486/234691747-be15590d-e0d1-4979-b9b7-8d202bba7b2f.png">
