### ISSUE TITLE
Port not being auto forwarded to localhost VSCode Desktop

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#14046]
### Bug description

A user was having trouble to make `bit login` work.[^1]

### Steps to reproduce

- Open https://gitpod.new on VSCode Desktop
- Run:
```bash
npx @teambit/bvm install
bit login
```
- It would open port `8085` on the Gitpod workspace
- But notice that the port `8085` wasn't auto forwarded to your PC via VSCode
- Manually add port `8085` on the bottom-panel PORTS view to make things work.

### Anything else?

[^1]: https://discord.com/channels/816244985187008514/1032373941836197988

**Comment by jeanp413** [comment]
I can repro, seems to be an upstream issue, only happens in the initial connection, if you reload the window and run the command again it will detect it automatically :thinking:
