### ISSUE TITLE
Annoying text at the top of the editor

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1406]
### Describe the bug

![image](https://user-images.githubusercontent.com/11302521/79532326-087a8e80-8075-11ea-9377-ba5ffe6dccfc.png)

### Steps to reproduce

1. Select random thing
2. Press CTRL+D
3. Withness the annoyance

### Expected behavior

Don't output annoying text unless in debug mode?

**Comment by AlexTugarev** [comment]
I've seen this in Theia, too. Unfortunately, I couldn't reproduce. 

The issue, or the thing you see there is a ARIA container added by monaco editor, which isn't supported in Theia, thus styles are missing. 

@Kreyren, `CTRL+D` with FF on Windows, or how do you reproduce it?

**Comment by Kreyren** [comment]
@AlexTugarev for some reason using CTRL+A and CTRL+D on this code causes it, (i was unable to reproduce it selecting specific codeblocks):

https://gist.githubusercontent.com/Kreyren/a56d474db8f5e19e2b93baf50fcb5ca9/raw/b7e5c376ce4c7ab30f030b4a6eff280006ea4831/sdgsdagasd

---

I was unable to make a snapshot (fails to create it).. So i am providing workspace UUID `ebaab2db-ce22-4ae3-a71b-e301ce51736f` at least.

FWIW the file was set to have 'Shell Script' highlighting

**Comment by AlexTugarev** [comment]
💯x thanks!

That's the repro, finally!

`ctrlcmd+a` `–>` `ctrlcmd+d`

@akosyakov, do you know about this "feature"?
