### ISSUE TITLE
[Markdown] properly resolve relative path to images

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#1407]
See https://community.gitpod.io/t/preview-readme-md-error/1223/4

**Comment by corneliusludmann** [comment]
This has been fixed by @AlexTugarev here https://github.com/eclipse-theia/theia/issues/1744 some time ago. It's been a while. But I can confirm that it's not working anymore.

**Comment by AlexTugarev** [comment]
That's not an issue in Theia. 
I can take care of this.

**Comment by svenefftinge** [comment]
This has been fixed and deployed to production.
