### ISSUE TITLE
Investigate continous downwards trend of webapp-login-success-ratio

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#14076]
![Image](https://user-images.githubusercontent.com/32448529/197169536-dd9e4084-8962-4cb8-8aed-a0d2350d96bf.png)

**Comment by gtsiolis** [comment]
[FWIW](https://en.wiktionary.org/wiki/FWIW), I've also noticed an increased flow errors where the auth pop-up does not close. I'd estimate this happened +30% during the last quarter while trying to login.
