### ISSUE TITLE
Gitpod preparement stuck at Building Image screen

### ISSUE THREAD

**Issue by Zeptar1069** [gitpod-io/gitpod#14107]
### Bug description

When I tried to open a workspace, it's now stuck at a "Building Image" screen.

### Steps to reproduce

Open a Gitpod image

### Workspace affected

zeptar1069-zeptar1069-oi5smvnnylg

### Expected behavior

Gitpod preparing correctly

### Example repository

![Screenshot 2022-10-22 3 23 10 PM](https://user-images.githubusercontent.com/99463015/197314945-9c9d846d-e6e1-4c10-a259-97a16522b5a3.png)

**Comment by shyim** [comment]
how does your docker file look like?

**Comment by Zeptar1069** [comment]
What do you mean dockerfile?

**Comment by Zeptar1069** [comment]
I can't open it so I can't see files

**Comment by Zeptar1069** [comment]
There's no code in the box

**Comment by Zeptar1069** [comment]
![image](https://user-images.githubusercontent.com/99463015/197356385-c15a44e6-09c3-453f-989e-a692fea40174.png)

**Comment by shyim** [comment]
Did you tried deleting that workspace and creating a new one?

**Comment by Zeptar1069** [comment]
I can't, because it has so many changes in it that I didn't push to github. It only says "No changes" when it's getting ready.

**Comment by axonasif** [comment]
Hey @Zeptar1069, please use https://www.gitpod.io/contact/support

**Comment by axonasif** [comment]
Oops, mistakenly closed it.

**Comment by will-beta** [comment]
also having this issue. expecting updates.

**Comment by axonasif** [comment]
Hi @will-beta, could you share your workspace ID for investigation?

**Comment by will-beta** [comment]
@axonasif Problem solved when I add a worker node into the pool.
