### ISSUE TITLE
Browser extension button is not rendering after viewing a file in GitHub

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#14117]
### Bug description

Following up from https://github.com/gitpod-io/gitpod/issues/13609 and https://github.com/gitpod-io/browser-extension/pull/68, the button is still not rendering on a) PRs, b) issues, c) folders, or d) files after visiting a file in GitHub.

See [relevant discussion](https://gitpod.slack.com/archives/C020VCB0U5A/p1666591838187069) (internal). Cc @Siddhant-K-code @andreafalzetti 

### Steps to reproduce

1. Install the browser extension
2. Go to a random repository on GitHub. For example, https://github.com/gitpod-io/gitpod
3. Go to a folder, issue, or a PR inside the repository. For example, [[1](https://github.com/gitpod-io/gitpod/tree/main/components)] or [[2](https://github.com/gitpod-io/gitpod/issues/14049)] or [[3](https://github.com/gitpod-io/gitpod/pull/14054)].
4. Go to a file inside the repository. For example, open [`README.md`](https://github.com/gitpod-io/gitpod/blob/main/README.md) in **gitpod-io/gitpod**.
5. Go back to step [3] and noticed the button is missing from everywhere, including [the repository homepage](https://github.com/gitpod-io/gitpod). ❗ 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3u98q)

**Comment by gtsiolis** [comment]
This is now worse as the button is never visible on folders or files after the introduction of the new file browser on GitHub[[1](https://github.blog/2022-11-15-a-better-way-to-search-navigate-and-understand-code-on-github/)].

**Comment by Siddhant-K-code** [comment]
GitHub Search & GitHub File view UIs are currently in Beta, I think, it's worth spending time, if we the new UI is rollout to 100% users. 

<img width="588" alt="image" src="https://user-images.githubusercontent.com/55068936/211353131-bdedd37c-6d37-4b81-bded-8c9fc60921c1.png">

**Comment by gtsiolis** [comment]
Resolved in https://github.com/gitpod-io/browser-extension/pull/80. Thanks, everyone!
