### ISSUE TITLE
Cleanup published Public API JS client

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#14113]
We publish NPM packaged for the public API on every branch: https://www.npmjs.com/package/@gitpod/public-api

We need to clean up that package to do the following:
* Do not publish on every branch, only on main
* Make it possible to publish a branch, but it should be an epxlicit trigger rather then by default
* Ensure published API client has reasonable ergonomics, and allows the following imports:
  * /stable/v1/
  * /stable/v2/
  * /experimental/v1/
  * /experimental/v2/

**Comment by akosyakov** [comment]
> Do not publish on every branch, only on main

It was useful for other packages like supervisor APIs, one could try changes from any branch without merging to main.

**Comment by easyCZ** [comment]
Currently, we publish a version of the client on every commit because we have a default setting in our [WORKSPACE.yaml](https://github.com/gitpod-io/gitpod/blob/main/WORKSPACE.yaml#L7).

The desired state of the publishing is as follows:
* When we do land a change on main, publishing a client is OK
* We shouldn't publish to NPM on every commit on a branch. We should however have the means to do so for a specific commit, such that we can test things out

When do we increment the package version? The versions published to NPM are somewhat independent of the commits to the gitpod repository. They mostly follow the lifecycle of the APIs, rather than of other gitpod components.

Given this, we could go for the following options:

**Release version manually only**
We can add a CI job to publish the client to NPM. This will incur some overhead having to maintain this manually, however, it provides the best UX as we're explicit about publishing a new version.

**Release version on changes to main**
We can push releases only when we land changes on main. This reduces the volume of releases, but we'd still be publishing a super large number of releases.

**Release a new version only when the Public API package changes on main**
This suffers from the package definitions existing not actually indicating they are ready to be used, yet.

@akosyakov @loujaybee Any other ideas on how we could approach this?

**Comment by easyCZ** [comment]
As for how to clean up the released packages:

1. Sign into NPM on the CLI
2. List all the releases of the `public-api` pacakge with `npm view @gitpod/public-api versions --json`
3. Identify the ones we want to keep. Currently, the following seem to fit the bill:
```
"0.1.5-2022.8.0",
"0.1.5-2022.9.1",
"0.1.5-main.5510"
```

Unpublish all the other ones, using `npm unpublish @gitpod/public-api@<version>`

**Comment by akosyakov** [comment]
> Given this, we could go for the following options:

- I think we should keep publishing from main under tag like `next` or something for each commit regardless of how we do publish for `latest` tag.
- For latest I guess we will need to do it manually if we want to be conscious about versions communicating API changes, or with some automation like conventional commits?

Do we plan to follow `semver`? or rather bump minor version each month and major each year instead? Maybe something to discuss on today sync. We don't follow such conventions for other packages as for now.
