### ISSUE TITLE
SLO: Looks like our create-workspace-latency SLO is broken

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#14127]
### Bug description

Looks like our [create-workspace-latency SLO](https://pyrra.gitpod.io/objectives?expr={__name__=%22webapp-create-workspace-latency%22,%20namespace=%22monitoring-central%22,%20team=%22webapp%22}&grouping={}&from=1664181747143&to=1666600947143) might be broken (it's important to keep this accurate in order to be aware of workspace creation speeds).

<img width="1422" alt="Screenshot 2022-10-24 at 10 42 02" src="https://user-images.githubusercontent.com/599268/197534977-12b9c1c4-d658-4671-a55b-6b6c2a75127f.png">

<img width="1382" alt="Screenshot 2022-10-24 at 10 41 53" src="https://user-images.githubusercontent.com/599268/197535025-d5abfdf8-f06d-4deb-9760-d14529b2a62e.png">

### Steps to reproduce

https://pyrra.gitpod.io (internal)

### Expected behavior

Availability and error budget cannot logically be > 100%. Something is wrong with the data.

**Comment by easyCZ** [comment]
https://github.com/gitpod-io/ops/pull/6295 ought to fix this. We measures the total without 4xx errors, but the success with. This made the metric non-semantic which resulted in > 100% availability
