### ISSUE TITLE
Add `gp` command/alias for awaiting until the IDE is reader (whether browser or desktop)

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#14137]
There have been several different people at different times (though recently) asking on the Discord channel for a way to open a file in the IDE when the IDE is ready.†

@axonasif pointed out this could be done by

```yaml
tasks:
  - command: gp ports await 23000 && gp open file.md
```

since `23000` is the port that the IDE is talked to with.‡   And it works - if you _already know_ the magic port number.

Feature suggestion:  Add an alias command to `gp` to wait for the IDE to become available.  Perhaps `gp ports await IDE` or `gp sync-await IDE` or even better something like `gp ide await` (which is nice because the `gp ide` command could later be expanded to do other things for you).

* _second-rate alternative_: Just document `23000` somewhere useful (in the CLI documentation, perhaps).
 
----

† Also other asks, not as easy, e.g.,: opening the VSCode sidebar Explorer filesystem tree to a specific folder.
‡ Yeah, that's not idiomatic English - ending a sentence with not one but _two_ prepositions is probably against the "rules" - but it's too early in the morning to figure out the right way to say it.

**Comment by axonasif** [comment]
Related https://github.com/gitpod-io/gitpod/issues/8826

**Comment by axonasif** [comment]
Actually, I realized that awaiting for port 23000 is not [necessary](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/cmd/open.go#L29) when you use `gp open` subcommand[^1] but is for `code`, I was just trying to reapply it to what we were discussing in that discord thread 😅 

[^1]: https://github.com/gitpod-io/gitpod/issues/8826#issuecomment-1076003406

**Comment by david-bakin** [comment]
Well, in _that_ case the feature ask is to provide a supported way of doing this - possibly via some coordination with the Gitpod extension that all Gitpod users have in their VSCode (desktop or browser).
