### ISSUE TITLE
support getting repo url from referrer

### ISSUE THREAD

**Issue by leighmcculloch** [gitpod-io/gitpod#14135]
## Is your feature request related to a problem? Please describe

Sometimes a developer wants to load up gitpod for the current branch they're viewing on GitHub, or a tag, or a pull request.

## Describe the behaviour you'd like

Add an option to the URLs gitpod supports for loading workspace from a GitHub URL to support a "referrer" mode where it learns of the URL to load from the referrer. This doesn't require a developer to manually insert a gitpod link that refers to the current branch, etc.

## Describe alternatives you've considered

Each branch and PR can link to their gitpod URL manually.

## Additional context
 N/A

**Comment by axonasif** [comment]
BTW, you could also use the [browser extension](https://www.gitpod.io/docs/configure/user-settings/browser-extension) for having a `Gitpod` button on almost any actionable context.

And this too:
- https://www.gitpod.io/docs/references/gitpod-yml#github
