### ISSUE TITLE
Don't add previewctl to our dev image

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/gitpod#14149]
Currently we add `previewctl` to our dev image ([source](https://github.com/gitpod-io/gitpod/blob/main/dev/image/Dockerfile#L257)). 

This means that whenever we update previewctl we'll have to build a new Docker image and update all jobs. This is tedious and slow. See example [PR](https://github.com/gitpod-io/gitpod/pull/14144) here.

We should see if we can remove `previewctl` from the image and instead use the binary built by Leeway in the different environments

1. For Gitpod Workspaces we can build previewctl as part of our prebuild configuration. We have to ensure it's on the PATH. We'd also have to install bash completions there and remove it from the Dockerfile ([source](https://github.com/gitpod-io/gitpod/blob/3393f87cd07b10b13d4298c20d5f8abf894f06be/dev/image/Dockerfile#L261))
2. For the Werft build job we should be able to use the previewctl that we create as part of the build

If we use previewctl in other Werft jobs we'll have to figure out solutions there too.

**Note**: This is also true for `kubecdl` and `gpctl`  - if it makes sense we could do the same for them.

**Comment by meysholdt** [comment]
Proposed solution: Leeway should build this, and all scripts that need it should have it as a dependency.
