### ISSUE TITLE
Slow at Initializing

### ISSUE THREAD

**Issue by thisisommore** [gitpod-io/gitpod#14147]
### Bug description

<img width="510" alt="image" src="https://user-images.githubusercontent.com/51229945/197726409-b821d078-0aa4-4d47-9eb3-4e080c84bfd1.png">

### Steps to reproduce

Press gitpod button on GitHub repo and see the issue

### Expected behavior

Workspace should be launched without any issues

**Comment by axonasif** [comment]
Hi @thisisommore, are you still experiencing this?

**Comment by thisisommore** [comment]
> Hi @thisisommore, are you still experiencing this?

Not now, but happens once in a while
