### ISSUE TITLE
Workspace is stuck

### ISSUE THREAD

**Issue by artalar** [gitpod-io/gitpod#1414]
### Describe the bug

I develop a newspaper application: cms at a server and web-site at a front. When I start only a server and open admin web site, no matter by a preview or a new tab, all is fine. When I start only a dev server of a web site and open it, no matter by a preview or a new tab, all is fine. When I start both: back and front, expose front port to browser (open in new tab) - the gitpod is freeze / stuck / block / don't know how describe it better. The main and strangest problem thats seems like it is not a problem of my application - https://gitpod.io/workspaces/ is not available too(!) until workspace is not go to sleep:

![image](https://user-images.githubusercontent.com/27290320/79720657-a5456200-82e9-11ea-9c80-ee2882dcd7a1.png)

**By the way it is is not a first time. And it give to me awful UX - it just block my work and I can't trust to gitpod anymore...**

### Steps to reproduce

Go to https://github.com/ke-community/platform/commit/199439dbb7eec0571d749fde8ba81ace8bf12fc1 , start a gitpod, install node_modules at server and client, **move files around** by the dir tree in the sidebar (looks like it is the main reason of the problem, but I don't sure), `./server> npm run start`, `./client> npm run dev`, open 3000 port.

![image](https://user-images.githubusercontent.com/27290320/79720292-ed17b980-82e8-11ea-9638-53bef3a61443.png)

### Expected behavior

gitpod is never stuck

### Additional information

My instance https://df85f8ae-18b4-4955-8ec0-ef5d9d91bf9e.ws-eu01.gitpod.io/#/workspace/platform

### Example repository

https://github.com/ke-community/platform

**Comment by svenefftinge** [comment]
Thanks for reporting. I couldn't reproduce it with the description, but we have see issues with one of our microservices for the last days and are working on a solution.

**Comment by artalar** [comment]
Here video with reproduce https://yadi.sk/i/LMzhrB596FPpyQ

**Comment by artalar** [comment]
Just trying it again in private tab - same error

**Comment by artalar** [comment]
@svenefftinge fix reproduce instruction: `./server> npm run start`, `./client> npm run dev`

**Comment by svenefftinge** [comment]
Thank you so much to take time for the recording. I hope it helps to identify the issue.

**Comment by geropl** [comment]
Hi @artalar ,

thank you very much for the detailed info. Your video gave an very interesting hint, especially when the browser would not open https://gitpod.io/workspaces: Could you show the "Console" tab in the devtools for that page? That you help us tremendously to pin down the problem.

**Comment by geropl** [comment]
So, we think we identified the issue: It's related to the you have uncommitted in your workspace (see your video). It somehow blocks the event loop of the Preview and - this is the bug - this affects the _whole_ workspace tab, including Theia. If you try to "Open in Browser Tab" you should be able to use the workspace - but only the new tab blocks.

**Comment by artalar** [comment]
@geropl "Open in Browser Tab" is not helpfull (looks like tabs with the same domain has a common thread). After ~7 attempts in different time I could't start the previous workspace, so I delete it, and create new one...

New question (please tell me if I need to create new issue for that) - when i expose a ports to public and get an link (like `https://${port}-${workSpaceUid}`) - it can't be opened in a private tab (I need to test permissions for my content on a strapi server, share a site preview to my colleagues) - it is a bug or a new future for limit a user?

**Comment by svenefftinge** [comment]
> New question (please tell me if I need to create new issue for that) - when i expose a ports to public and get an link (like https://${port}-${workSpaceUid}) - it can't be opened in a private tab (I need to test permissions for my content on a strapi server, share a site preview to my colleagues) - it is a bug or a new future for limit a user?

You need to make the port public in order to allow others to access it. Ports listed in .gitpod.yml are `public` by default but without that you need to make them public manually (either in the notification or in the ports view).

**Comment by artalar** [comment]
Now I get it! My misunderstood. Thanks a lot.
