### ISSUE TITLE
[UBP] Allow Professional OSS plan users to upgrade to UBP 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14141]
There is currently no straightforward way for users on the Professinoal OSS plan to upgrade to UBP.
Enabling the UBP feature flag for these users does not enable UBP the way it does for regular Free plan users.

**Comment by geropl** [comment]
This should be the case since we filter out the Prof. OSS plan [here](https://github.com/gitpod-io/gitpod/blob/5bef3e336c1fc8a593e2cd7cff0f71630ec474ec/components/server/ee/src/billing/billing-mode.ts#L122).

**Comment by jldec** [comment]
Sorry, you're right @geropl 

I have confirmed that after setting the UBP feature flag, these users see the default UBP free tier in their billing settings.
