### ISSUE TITLE
Can not create a snapshot when using PVC for workspaces

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#14159]
### Bug description

Although PVC rollout is only internal so far, there's an issue that prevents users from creating a snapshot when using PVC for workspaces. When users try to create a snapshot, they get an error notification inside VS Code Browser. ❗ 

Moreover, the PVC feature seems to be enabled regardless if the project setting is enabled. 💭 

See [relevant docs](https://www.gitpod.io/docs/configure/workspaces/collaboration#workspace-snapshots) on workspace snapshots and [relevant discussion](https://gitpod.slack.com/archives/C02F19UUW6S/p1666695767074899) (internal). Cc @jenting @sagor999 @kylos101 

| VS Code notification | Project settings |
|-|-|
| <img width="470" alt="Screenshot 2022-10-25 at 1 28 10 PM" src="https://user-images.githubusercontent.com/120486/197772272-04f33c9f-267f-46d9-a2ea-e27af7a66aa3.png"> | <img width="526" alt="Screenshot 2022-10-25 at 1 42 37 PM" src="https://user-images.githubusercontent.com/120486/197772276-34fee146-b595-4cfb-81dc-4147f85c4d0c.png"> |

### Steps to reproduce

1. Be part of the feature flag that enables PVC for your account.
2. Open a workspace for any repository or project.
3. Try creating a snapshot from the command palette.
4. Notice that snapshot creation fails, and you get an error notification.

**Comment by sagor999** [comment]
@gtsiolis how does this feature work? :) 
When it is done, does it show you a link to download your snapshot tar file? Is it used for anything else?

**Comment by kylos101** [comment]
> When it is done, does it show you a link to download your snapshot tar file? 

:wave: @sagor999 it shows you a link to start a workspace like [this](https://gitpod.io#snapshot/635c2e02-969c-45a7-aeb6-f93e6a57b85e), which can be used to create many regular workspaces. In other words, having the URL to the snapshot means you can start a workspace from the Snapshot's backup context...entirely avoiding the original Git or prebuild or backup context. Some people use this to take 'point in time' backups of their workspaces, so that they have something to fall back to.

**Comment by jenting** [comment]
@sagor999 Do you need help on this issue? If yes, feel free to talk with me.

**Comment by sagor999** [comment]
@jenting no, thank you. I was OOO until now, but I should have workspace part implemented today. :pray:

**Comment by sagor999** [comment]
@geropl adding this to WebApp inbox.
I implemented Workspace related changes to make snapshotting work when workspace is using PVC.
Now I need your help to implement webapp side of changes. 
Two changes are required:
1. Call `TakeSnapshot` for ws-manager client for workspace that needs to be snapshotted (I believe this might not to be changed by reading webapp code, but I could be wrong. wsman TakeSnapshot now checks if workspace is PVC enabled and creates snapshot using PVC if so, and as a result returns volume snapshot name as `Url`. This is similar to how volume snapshots are stored in DB already for PVC enabled workspaces).
2. Change how we check when snapshot is ready. Currently webapp directly checks GCS if the tar file was uploaded. Now instead webapp needs to check if workspace is PVC enabled, then call ws-manager new RPC that I added: `CheckVolumeSnapshotReady` by passing `Url` as snapshotID into it, and it will return true or false if snapshot is ready for use or not).

Please feel free to add your PR on top of this PR: https://github.com/gitpod-io/gitpod/pull/14374

Would be amazing if you can prioritize this, as it blocks PVC rollout currently.

:pray: 

@kylos101 :eyes:

**Comment by geropl** [comment]
@sagor999 Scheduled for next week :+1:

**Comment by geropl** [comment]
@kylos101 My understanding is that we can delay the work here until we are clear on how PVC is moved forward with. Correct? :thinking:

**Comment by kylos101** [comment]
@geropl :100: yes

**Comment by sagor999** [comment]
Removed from workspace project for now as we are rethinking our PVC approach.

**Comment by svenefftinge** [comment]
we've decided to discontinue/roll-back the PVC work as is.
