### ISSUE TITLE
[expander] add component to main

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#14160]
## Is your feature request related to a problem? Please describe

It lives in a branch [here](https://github.com/gitpod-io/gitpod/compare/main...aledbf/expander)

## Describe the behaviour you'd like

It should be part of main branch [here](https://github.com/gitpod-io/gitpod)

## Describe alternatives you've considered

n/a, this will make it easier to support and maintain

## Definition of done
1. Open a PR to have this branch merged to main
2. Update the codeowners file, so that this component requires review from the Workspace Team

**Comment by atduarte** [comment]
@kylos101 @aledbf we are doing refinement right now, and we would like to have a bit more context on this. Why has this branch kept separate? Is there anything that needs to be resolved first?

**Comment by atduarte** [comment]
@kylos101 @aledbf we are doing refinement right now, and we would like to have a bit more context on this. Why has this branch kept separate? Is there anything that needs to be resolved first?

**Comment by kylos101** [comment]
Hi @atduarte , getting this to main is a good start iteration wise, we can resolve other things later if issues arise. This is being used now, by the `cluster-autoscaler`.

**Comment by kylos101** [comment]
Updated the definition of done to include adding this to the codeowners file.

**Comment by kylos101** [comment]
@aledbf should we build images for `autoscaler-expander` and `cloud-controller-manager`, too? I ask because I am scheduling the IPFS work, and this feels related. 

https://github.com/gitpod-io/gitpod-packer-gcp-image/blob/a528173daa30cab91c1cadcd6b5818ec1520738e/rootfs/var/lib/gitpod/manifests/autoscaler-expander.yaml

https://github.com/gitpod-io/gitpod-packer-gcp-image/blob/a528173daa30cab91c1cadcd6b5818ec1520738e/rootfs/var/lib/gitpod/manifests/gcp-ccm.yaml

**Comment by aledbf** [comment]
@kylos101 no
