### ISSUE TITLE
Reset usage for BillingStrategy Other

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#14178]
We need to periodically reset usage for attribution IDs on BillingStrategy.Other so that Free tier users are not blocked.

[Context ](https://gitpod.slack.com/archives/C02EN94AEPL/p1666755684969439)

**Comment by easyCZ** [comment]
The [job](https://github.com/gitpod-io/gitpod/pull/14189) & [RPC](https://github.com/gitpod-io/gitpod/pull/14229) are implemented.

https://github.com/gitpod-io/gitpod/pull/14246 implements the trigger. With these, the job will only list number of cost centers that need to be updated, not actually reset them, yet.

**Comment by easyCZ** [comment]
The resetting of usage is implemented in this PR: https://github.com/gitpod-io/gitpod/pull/14249

We should also add metrics to measure how many usage records have been reset, and the outcome.

**Comment by jldec** [comment]
Closing as this is marked status Done.
