### ISSUE TITLE
"We have trouble parsing your context"

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#142]
**Describe the bug**
I wasn't able to open my repository in Gitpod.

**To Reproduce**

1. Go to https://gitpod.io/#https://github.com/JanitorTechnology/dockerfiles/

**Expected behavior**

Gitpod should open my repository.

**Actual behavior**

Gitpod shows the following error message:

> We have trouble parsing your context
> Error: ER_WRONG_FIELD_WITH_GROUP: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gitpod.credit.date' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
> Please file an issue if you think this is a bug.

**Comment by geropl** [comment]
Hi @jankeromnes! Thanks for your feedback. It worked for me. Looks like it was a temporary issue during a deployment. Could you check again if it works for you?

**Comment by svenefftinge** [comment]
Thank you for reporting it! Closing it as we know what went wrong during the rolling update.

**Comment by jankeromnes** [comment]
I confirm that it works again, thanks! :fireworks:
