### ISSUE TITLE
[loadgen] ability to run many tests concurrently

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#14213]
### Bug description

Running two test instances at once causes conflict on the files used to manage state

### Steps to reproduce

1. Start two tests at the same time, with each test starting 2 workspaces (4 in total).
2. You'll see that `stats.json` contains data for the most recent (2nd) run.
3. Stop the first run, you'll see that `benchmark-result..json` is written with all 4 instances (instead of the 2 you stopped), loadgen says its stopping 2 workspaces in the first run, and it waits
4. Stop the second run, the `benchmark-result.json` file is overwritten to have 2 workspaces, instead of the 4 it previously had

### Expected behavior

Each `loadgen` run has exclusive state, and the `stats.json` and `benchmark-result.json` files are exclusive to their respective runs. Perhaps they should be stored in a generated folder.

### Anything else?

Its nice to run 2 or more waves of loadgen at one time, so we can stop a whole wave (to apply stop pressure to a cluster).

As an alternative, if we don't make this change, we can stop individual workspaces.

**Comment by atduarte** [comment]
From @utam0k: We need to execute two loadgens in parallel for example to test object storage and PVC types at the same type.

From @WVerlaek: Even if they don't run in parallel, it is nice to not have the second run to overwrite the results of the first.
