### ISSUE TITLE
No visible Gitpod button available in My Repositories

### ISSUE THREAD

**Issue by 7-Deuce** [gitpod-io/gitpod#1421]
### Describe the bug
No Gitpod button appearing to launch Gitpod from My Repositories

### Steps to reproduce
Installed Gitpod Extension (Chrome)
Authorized Access
Created new blank repo. 
Click on green button but there is no green GitPod button. 

### Expected behaviour
Expected to see green GitPod button repo page

### Additional information
The issue is identical to this previous issue
https://github.com/gitpod-io/gitpod/issues/453
Also getting same results in Firefox. 

### Example repository
https://github.com/7-Deuce/second-repo
![repo_gitpod-error](https://user-images.githubusercontent.com/59662245/79896453-4de5e580-8400-11ea-94e5-b0e871fef2b4.png)

**Comment by corneliusludmann** [comment]
What you describe is that there is no Gitpod button for an empty repository, right? That's indeed a limitation of the Gitpod browser extensions since the button only appears next to the `Clone or download` button that does not exist on an empty repository.

I would like to close this issue in favor of #453.  Do you agree?

**Comment by 7-Deuce** [comment]
Hi there, thanks for getting back so quickly. I realise this now only occurs where the repository is empty. It was my first time setting it up, and was going off an instructional video and initially couldn't tell why there was a difference. I understand now. 

Yes, I agree. Please close this. 

Thanks.

**Comment by Gaberoids** [comment]
Solution
One the steps to reproduce add "check the box that says to add the readme file to repository". This will add the git button to your new repository.
Steps to reproduce would look like this

Installed Gitpod Extension (Chrome)
Authorized Access
Created new blank repo **### (make sure to check the box that says to add the readme file to repository)**
Click on green button but there is no green GitPod button.

When you open GitPod, you will see the readme.md file in your gitpod workspace. You can remove it if you want. It has not functional effect on your project. readme.md is usually used for documentation purposes. This file is valuable if you will be sharing your repository with someone, like and person on your job interview
