### ISSUE TITLE
Supervisor unit tests are flaky

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#14210]
### Bug description

Supervisor tests for the terminal panic in CI runs:
* https://werft.gitpod-dev.com/job/gitpod-build-mp-protocol-team-apis.2

### Steps to reproduce

https://werft.gitpod-dev.com/job/gitpod-build-mp-protocol-team-apis.2

**Comment by andreafalzetti** [comment]
Thanks for opening the issue, I've noticed we have two similar ones. Can we close this as duplicate of https://github.com/gitpod-io/gitpod/issues/14425? cc @easyCZ

**Comment by jeanp413** [comment]
Closing this as duplicate of https://github.com/gitpod-io/gitpod/issues/14425
