### ISSUE TITLE
Missing sources for Gitpod Web Support extension

### ISSUE THREAD

**Issue by abitrolly** [gitpod-io/gitpod#14222]
### Bug description

Gitpod Web extension comes without links to source code, so unable to report bugs.

![image](https://user-images.githubusercontent.com/8781107/198203335-ed9e2bfa-86ed-423a-9418-a8c434887477.png)

### Steps to reproduce

```
git push https://github.com/lvee/lvee-engine
```
![image](https://user-images.githubusercontent.com/8781107/198204216-efcea8a8-3587-4f45-a96c-98039ab257c5.png)

**Comment by axonasif** [comment]
Hi @abitrolly, is this on Desktop VSCode?

Also, could you please follow [this](https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop)?

**Comment by akosyakov** [comment]
@mustard-mh this one is resolved, right? can be closed?

**Comment by filiptronicek** [comment]
@abitrolly to make sure, is the thing you are looking for a links to report bugs like these? I took a look and we do specify these in the source code [[1](https://github.com/gitpod-io/openvscode-server/blob/gp-code/release/1.73/extensions/gitpod-web/package.json)], but it seems like they are ignored for built-in.


![Image](https://user-images.githubusercontent.com/29888641/200367920-69dee7db-12b7-4995-b74e-83bfe954189c.png)

**Comment by filiptronicek** [comment]
@mustard-mh could you please take a look at https://github.com/gitpod-io/openvscode-server/pull/462? It should be a 🛹 fix for this, as I didn't find an easier solution for forcing the display of the metadata - and I think it's enough.

@abitrolly with the changes done in the above Pull Request, would you be alright for you if the extensions view would look like this (see mainly changes in description)? Would appreciate any feedback.

<img width="916" alt="image" src="https://user-images.githubusercontent.com/29888641/200694673-56167e29-1cdd-4692-9748-7117bd57c8c1.png">

**Comment by abitrolly** [comment]
Can't comment for some reason. Testing.

**Comment by abitrolly** [comment]
Awesome! Thanks. An improvement would be to explain what it really does, because "integration" doesn't make it clear.

I would also leave the naked link..

https://github.com/gitpod-io/openvscode-server/tree/gp-code/main/extensions/gitpod-web

The other thing that is not clear, is iwhyssues are not belong to this repo?
