### ISSUE TITLE
Can't upgrade to 2022.9.2 from 2022.8.0

### ISSUE THREAD

**Issue by jim-huang-nj** [gitpod-io/gitpod#14226]
### Bug description

When I  want to upgrade gitpod from 2022.8.0 to 2022.9.2, I found we can't download it.

error:
failed to pull: failed to render upstream: failed to convert upstream file gitpod-http-proxy-settings.yaml to base: failed to render file template: failed to get template: template: gitpod-http-proxy-settings.yaml:16: function "HTTPSProxy" not defined

### Steps to reproduce

1. run "kubectl kots admin-console --namespace gitpod"
2. Go to http://localhost:8800/ to access the Admin Console
3. click "Download"
4. get error information

**Comment by jbanety** [comment]
Same bug here.
![Capture d’écran 2022-10-28 à 10 27 37](https://user-images.githubusercontent.com/1055330/198541573-b801c37c-7a57-4afb-8b5d-f1685263dcd8.png)

**Comment by jimmybrancaccio** [comment]
Have a look at #13933.

**Comment by jbanety** [comment]
:+1:

**Comment by jim-huang-nj** [comment]
Thanks. It can work.
