### ISSUE TITLE
.gitpod.yml file is ignored in some cases

### ISSUE THREAD

**Issue by tomwheeler** [gitpod-io/gitpod#14239]
### Bug description

About 10 days ago, after successfully using GitPod for a few months, I found that all new workspaces I created from a [particular repository](https://github.com/temporalio/edu-101-go-code) were missing all customization specified in the `.gitpod.yml` file. None of the tasks declared there were run nor any of the VScode extensions installed, yet the `.gitpod.yml` file hadn't been modified for more than two weeks before this problem started. I eventually learned that this problem was specific to me (i.e., my manager created a workspace from this same repository and worked fine for him). I also found that I could create a different repo with the same contents and that worked fine. Thus, the problem appeared to affect only the combination of my account and this repository.

I [posted about this in Discord](https://discord.com/channels/816244985187008514/1031943844981383288) and Pauline from GitPod support had me check several things. Eventually she had me check the permissions associated with GitHub integration. Although I had never changed these, she had me check all of the boxes. To our mutual surprise, it began working. I later reverted to the original permissions, and it continued working for another nine days. The problem happened to me again yesterday for no apparent reason, so I reinstated all of the permissions again, which worked around whatever is causing this. Coincidentally, my manager began to experience the problem yesterday afternoon. He found this morning that clearing the cookies and local storage in Chrome fixed it.

Although we have two workarounds (assigning permissions and clearing cookies/local storage), there's clearly an underlying problem, so I wanted to report it. 

### Steps to reproduce

I cannot reproduce the problem at will. 

When the problem occurs, creating a new workspace from the GitHub repository results in a new workspace without any customization whatsoever in 100% of cases for the affected user. It does not affect other users who create workspaces from the same repository at the same time. The problem will persist for the affected user until they apply one of the two workarounds described (assigning all permissions in the GitHub integration or clearing the cookies/local storage in Chrome). However, this does not appear to be browser-specific problem, as I have experienced it in both Safari and Chrome. 

### Expected behavior

The workspace should be configured according to the configuration specified in the `.gitpod.yml` file. However, it is missing all of the customizations specified there.

### Example repository

https://github.com/temporalio/edu-101-go-code

**Comment by axonasif** [comment]
Hi @tomwheeler, could you also share the specific workspace ID or URL when you notice this again?

**Comment by tomwheeler** [comment]
Absolutely. I have just reverted to the original permissions for GitHub integrations, in the hopes that it makes the bug surface again.

**Comment by tomwheeler** [comment]
I should have also mentioned in this issue (as I did in the Discord thread) that there are no obvious errors when this problem happens, either in the UI or any of the log files available to me.
