### ISSUE TITLE
Opening a Github PR that was already merged to `main` results in an error screen

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#14234]
### Bug description

![image](https://user-images.githubusercontent.com/22901/198282689-e5c34e9e-565d-42dd-87b3-1e43221bd1e4.png)

### Steps to reproduce

1. Open a PR in Github
1. Merge PR
1. Go to the PR page, either use Gitpod extension or add `https://gitpod.io/#` before the URL

**Comment by svenefftinge** [comment]
What would be your expectations in the case that the branch doesn't exist anymore?
