### ISSUE TITLE
[Bug] asExternalUri never returns

### ISSUE THREAD

**Issue by jeromelaban** [gitpod-io/gitpod#14248]
### Bug description

Since what I think is https://github.com/coder/code-server/pull/5624, awaiting `vscode.env.asExternalUri(vscode.Uri.parse("http://localhost:12345");` never returns.

### Steps to reproduce

I don't have a simple repro available, but the promise awaiting `vscode.env.asExternalUri` does not return.

Here's an larger repro:
1. Open: https://gitpod.io/#https://github.com/unoplatform/uno.quickstart
1. Install the suggested [Uno Platform extension](https://marketplace.visualstudio.com/items?itemName=unoplatform.vscode)
1. Once the C# environment is setup, with the commmand palette use the command "Omnisharp: Select project" (or click on the project name in the status bar)
1. Select the `MyApp.Wasm` project
1. If the `vscode.env.asExternalUri` works, the output for `Uno Platform - Hot Reload` will show `Application started. Press Ctrl+C to shut down.`. 

Currently, that message does not appear.

### Expected behavior

A new listening port is opened based on the external uri.

**Comment by jeanp413** [comment]
@jeromelaban seems to be working for me, can you still reproduce?
```
[Info] Launching remote control server (Port:41463, Path:/home/gitpod/.nuget/packages/uno.ui.remotecontrol/4.6.18/buildTransitive/../tools/rc/host/net6.0/Uno.UI.RemoteControl.Host.dll)
[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[3]
      Hosting starting

[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[4]
      Hosting started

[40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly Uno.UI.RemoteControl.Host

Hosting environment: Production
Content root path: /workspace/Uno.QuickStart
Now listening on: http://[::]:41463
Application started. Press Ctrl+C to shut down.
```

**Comment by jeromelaban** [comment]
Hi @jeanp413! We published a workaround for it in our v0.5.1, but if you install the version 0.4.0 of the addin, it should reproduce.

As for the code-server PR, my apologies if it's unrelated. I don't really understand yet the relations between all the pieces of gitpod's ecosystem :)

**Comment by jeanp413** [comment]
Small repro: 
You need to not have anything running in 32456 port
```
const d = vscode.Uri.parse(`http://localhost:32456`);
const h = await vscode.env.asExternalUri(d);
```

@mustard-mh maybe related to some optimizations we did about not firing event for ports, [this logic](https://github.com/gitpod-io/openvscode-server/blob/ce5566276e561303d92bec32a9f58008cddd5270/extensions/gitpod-web/src/extension.ts#L320-L328) is always returning false

**Comment by jeromelaban** [comment]
Thanks!

**Comment by mustard-mh** [comment]
@jeromelaban it's not deployed yet 🙏 , will ping you if we are going to deploy it to SaaS Gitpod

**Comment by mustard-mh** [comment]
Sorry for being late, it's been [deployed](https://github.com/gitpod-io/gitpod/pull/14761#event-7846174827) to production SaaS Gitpod. @jeromelaban
