### ISSUE TITLE
[server] tune GC frequency to support perceived rate

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#14243]
## Is your feature request related to a problem? Please describe

We are changing how we persist regular and workspace backups (from GCS to disk snapshots and images), which are subject to different rate limiting.

Context:
[Internal conversation](https://gitpod.slack.com/archives/C02EN94AEPL/p1666744721189149)
[Related issue for Workspace team](https://github.com/gitpod-io/ops/issues/6270)

## Describe the behaviour you'd like

Smooth GC runs by running more often and doing less on each tick. (thanks @easyCZ for the phrasing!)

## Describe alternatives you've considered

For now, we've reached out to Google, to see if we can increase the related limit impact PVC backup mechanisms. TBD.

For the future (certainly not in scope for this issue), have webapp send GC requests to workspace, workspace would persist these as CRDs, and chew through that GC queue on its own. Not sure how `server` would get confirmation that the GC is `done`, though.

## Additional context

@easyCZ does `server` backoff and try again when GC failures happen? 

@sagor999 my understanding is that `server` leverages `content-service` now to do GC. But, while on PVC they'll leverage `ws-manager` for the workspace's region. Is that correct?

**Comment by kylos101** [comment]
@geropl could we ask that this be considered for upcoming groundwork? It'll help avoid related rate limiting in the GCP space once we start start using PVC at scale.

**Comment by easyCZ** [comment]
@kylos101 
Can you provide the maximum rate of requests you're willing to accept? You'll need to partition the rate limits for Creates and Deletes as I assume there's a single rate limit for both PVC operations (and likely Creates are much more important).

It would be extremely helpful to also set this as an incoming rate limit on your side as there are no guarantees in distributed systems, this then forms a natural layer of load-shedding mechanics between the two systems. Assuming this is in place, the only necessary steps are:
1. Ensure we try again later, and we fail gracefully when you send a Rate Limit Exceeded status code.
2. Fine tune our GC frequency

**Comment by kylos101** [comment]
Hey @easyCZ , we can accept a rate of 1,000 [mutations to a snapshot per minute with GCP](https://cloud.google.com/compute/quotas#api-rate-limits:~:text=Rate%20per%20project%20(GlobalResourceWriteRequestsPerMinutePerProject)%3A%20375%20requests/minute) (which includes create and delete of snapshots) - we bumped the quota up from 375 to 1000. 

As far as a limit for the deletes that `server` sends, it would be ideal to cap that at `100 deletes per minute`, for now. Is that doable?

I don't believe the [delete workspace PVC endpoint](https://github.com/gitpod-io/gitpod/blob/449bcc21b18b755d9b88d8e0662788d3a3c40cdd/components/ws-manager/pkg/manager/manager.go#L516) supports rate limiting, though. However, it seems like it is config driven. [[1](https://github.com/gitpod-io/ops/blob/49c40bea9d2cc6181d56a2ec1b8da97410ee67d7/deploy/workspace/installer-values.yaml#L24-L32)][[2](https://github.com/gitpod-io/gitpod/blob/449bcc21b18b755d9b88d8e0662788d3a3c40cdd/components/ws-manager/cmd/run.go#L126-L140)] So, we should be able to add. @sagor999 wdyt? If yes, could I ask you to do?

**Comment by easyCZ** [comment]
Thanks @kylos101 and @sagor999.

We're struggling with capacity this week, but we'll going to be looking into this as soon as we can.

What's the sharding of the rate limit? Is it per GCP project? If that's the case, then multiple WS clusters (and ws-managers) will consume the rate limit concurrently. This could mean that if you're between 2 generations, and across 2 regions, we'd be able to execute up to 400 requests, based on current rate limit.

**Comment by sagor999** [comment]
Correct. Which is probably ok for now. But we might tune that rate limit in the future.

**Comment by kylos101** [comment]
:wave: @geropl I just added this issue to our [internal milestone plan](https://www.notion.so/PVC-for-Regular-Workspaces-Milestones-8ace913ac67e4b68b6b9758cc7dea551?d=05f080d599b6444cb4668815deb13adf#13c7ba5a26b6491b96c682fe0b487f0c) for PVC and regular workspaces. Let us know if it is okay, or if it needs to be pushed out?

**Comment by easyCZ** [comment]
@kylos101 This was left accidentally in our previous sprint and didn't show up on the new one, so it went "out of sight, out of mind". I'm picking it up now.

**Comment by easyCZ** [comment]
The GC batch size reduction (and frequency increase) landed in production during today's rollout. Closing the issue. If there's anything else we can help with, let us know and reopen the issue.

**Comment by kylos101** [comment]
Thank you, @easyCZ !
