### ISSUE TITLE
Delete projects from project settings

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14251]
Deleting a project should be consistent with deleting a team or a user account.

- Go to project Settings
- Look for the "Delete Project" section at the bottom of the "General" settings page.
- Click on the button, and then do what what the confirmation modal tells you to do.

It's OK to also allow deletions from the Delete action on the context menu of the project card on the Projects page.

**Comment by gtsiolis** [comment]
Closing this in favor of https://github.com/gitpod-io/gitpod/issues/7273 which also includes design specs (https://github.com/gitpod-io/gitpod/issues/7273#issuecomment-1096680115) than can be used for the implementation in https://github.com/gitpod-io/gitpod/pull/15316.
