### ISSUE TITLE
chrome desktop support 

### ISSUE THREAD

**Issue by chiyanglin-AStar** [gitpod-io/gitpod#14255]
### Bug description

I follow this article (the following link)  to try to lauch chrome desktop on Gitpod 
https://ubuntu.com/blog/launch-ubuntu-22-04-desktop-on-google-cloud

![gitpod_chrome_desktop1](https://user-images.githubusercontent.com/28211609/198559937-dd5d818c-7a06-45eb-b3e2-24f958d51831.png)

after ssh launch , chrome host side (my laptop) is to receive the package of gitpod chrome desktop, the show that it can connect !   

press button and pin keyin ,   
 
![gitpod_chrome_desktop2](https://user-images.githubusercontent.com/28211609/198560544-7976c901-0381-434d-a099-d872e56e24f0.png)

press ok , then close !    I am not sure whether  need to open something in Gitpod !  please give some advice !

### Steps to reproduce

I follow this article (the following link)  to try to lauch chrome desktop on Gitpod 
https://ubuntu.com/blog/launch-ubuntu-22-04-desktop-on-google-cloud

![gitpod_chrome_desktop1](https://user-images.githubusercontent.com/28211609/198559937-dd5d818c-7a06-45eb-b3e2-24f958d51831.png)

after ssh launch , chrome host side (my laptop) is to receive the package of gitpod chrome desktop, the show that it can connect !   

press button and pin keyin ,   
 
![gitpod_chrome_desktop2](https://user-images.githubusercontent.com/28211609/198560544-7976c901-0381-434d-a099-d872e56e24f0.png)

press ok , then close !    I am not sure whether  need to open something in Gitpod !  please give some advice !

I also not sure it is belong bug or feature support , please allow me to post on bug !

**Comment by axonasif** [comment]
Hi @chiyanglin-AStar, you can use the [workspace-full-vnc](https://github.com/gitpod-io/workspace-images/blob/axonasif/add_docs/chunks/tool-vnc/README.md#workspace-full-vnc) image instead.

**Comment by chiyanglin-AStar** [comment]
Got it !  tks a lot for remind !   vnc-full version improve a lot !   another simple question :  have build-in browser and vnc-full gitpod template ?

**Comment by chiyanglin-AStar** [comment]
> Hi @chiyanglin-AStar, you can use the [workspace-full-vnc](https://github.com/gitpod-io/workspace-images/blob/axonasif/add_docs/chunks/tool-vnc/README.md#workspace-full-vnc) image instead.

Got it ! tks a lot for remind ! vnc-full version improve a lot ! another simple question : have build-in browser and vnc-full gitpod template ?

**Comment by axonasif** [comment]
> have build-in browser in vnc-full gitpod template

Yes, there is google-chrome installed in it.

**Comment by chiyanglin-AStar** [comment]
@axonasif   have tried it !  working !  very tks!
