### ISSUE TITLE
GitPod not loading sites through local dev server

### ISSUE THREAD

**Issue by ShavingSeagull** [gitpod-io/gitpod#1426]
### Describe the bug
The local server starts fine, but the site won't load in the browser - just leads to a long loading time which results in a 500 error

### Steps to reproduce
Run a local dev server and try to reach the port via a browser

### Expected behavior
The site to load up as normal

### Additional information
It is affecting all of our European students' workspaces (US seems OK for now). Error seems to be internal on your end. No errors in dev tools or logs etc. A workspace affected by this is [here](https://bfcedd03-652e-4d28-9ff5-22ffa61a3d4a.ws-eu01.gitpod.io/#/workspace/datacentric-milestoneproject)

### Example repository
Repo for the above workspace is right [here](https://github.com/Leannald13/datacentric-milestoneproject)

**Comment by isontheline** [comment]
Same here

**Comment by RohrerHope** [comment]
Not loading the projects anymore and before that, the extensions were not loading.

**Comment by jankeromnes** [comment]
Sorry about that. Gitpod is partially down in Europe. We're investigating, and trying to restore service as soon as possible.

Tracking this issue in #1429.

**Comment by Taitdanielle** [comment]
Yea I have been getting this for hours now, Tried another browser, cleared cache, and cookies. Used incognito mode too.

![Screenshot 2020-04-22 at 16 02 33](https://user-images.githubusercontent.com/51921627/79998571-c0af9900-84b2-11ea-8c2b-07763c8b87be.png)

**Comment by jankeromnes** [comment]
Hi @Taitdanielle, really sorry about this. Is Gitpod still unusable for you now?

**Comment by Taitdanielle** [comment]
Hi Jan, Yea it's just showing the G bouncing about again.

Thanks
Danielle

________________________________

**Comment by Taitdanielle** [comment]
It just shows the G then says starting then goes away again.

________________________________

**Comment by jankeromnes** [comment]
Thanks for reporting, will investigate. Cautiously re-opening this issue.

**Comment by Taitdanielle** [comment]
Thank you :)

________________________________

**Comment by mayasaffron** [comment]
still not loading for me
<img width="1440" alt="Screenshot 2020-04-22 at 16 15 49" src="https://user-images.githubusercontent.com/56965613/80000038-8941ec00-84b4-11ea-99ab-9bfa71d928b7.png">

**Comment by jankeromnes** [comment]
@Taitdanielle You're welcome, and sorry again for the disruption.

Your workspace apparently reports being ready since ~20 minutes ago, so in theory it should let you into the IDE.

What happens if you go back to https://gitpod.io/workspaces/ and then open the workspace again?

**Comment by mayasaffron** [comment]
still not loading for me

**Comment by Taitdanielle** [comment]
Yea I noticed that so when I click into it it sits at the G says starting and just sits, when I go back to my work space its says its ran since then. But it hasn't

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mayasaffron** [comment]
exactly the same for me ^

**Comment by jankeromnes** [comment]
@mayasaffron your workspace reports being ready since 7 minutes ago... That's really strange.

I think it's a different problem (i.e. unrelated to today's EU outage). I'll investigate why some workspaces don't get past the loading screen.

**Comment by mayasaffron** [comment]
<img width="1440" alt="Screenshot 2020-04-22 at 16 22 50" src="https://user-images.githubusercontent.com/56965613/80000805-84316c80-84b5-11ea-8f12-c847784750f6.png">
 just clicked on it and still here..

**Comment by jankeromnes** [comment]
I tried to reproduce this problem by opening both your repositories in Gitpod, but my workspaces loaded fine.

Could you please try to create a new workspace for the same project? (I'm trying to figure out if this problem randomly affects any workspace, or if it's project-specific or user-specific.)

**Comment by Taitdanielle** [comment]
So I just opened another workspace I have, It loaded fine.  The workspace I am trying to use my Gaudi in a day is a project :( I'll make another workspace just now.

**Comment by Taitdanielle** [comment]
Ok, the New one opens fine what will I do about the work I have on my other one?

**Comment by jankeromnes** [comment]
@Taitdanielle Many thanks for confirming. 🙏 So this problem seems to be workspace-specific, and not project-specific. We'll continue investigating what's wrong with these workspace that don't want to load, and try to fix it, so that you can open them again.

(But meanwhile, if you need to access files in these workspaces that weren't committed or pushed, please note that you can also download a workspace archive from https://gitpod.io/workspaces/)

**Comment by Taitdanielle** [comment]
You are welcome. Ok, so will I stop working on it just now until it's resolved?

**Comment by jankeromnes** [comment]
@Taitdanielle Please feel free to continue working, e.g. in the new workspace, as I'm not sure how long it will take to understand and fix the bug with the old workspace.

If you need to access some files that are still "stuck" in the old workspace, please download that old workspace from https://gitpod.io/workspaces/ (you'll get an archive with all the files from your workspace), that way you'll be able to upload the files into your new workspace.

I'm very sorry for the inconvenience this causes.

**Comment by mayasaffron** [comment]
![Uploading Screenshot 2020-04-22 at 17.07.46.png…]()
mine is now getting past the loading stage full bar loading at the top. then stopping here

**Comment by ralphilius** [comment]
![https___cfdcd7c0-50be-4371-a8dc-f6c03b0a100b_ws-us02_gitpod_io](https://user-images.githubusercontent.com/4253551/80005789-47359c00-84ee-11ea-9ff3-7406c1e6a6ec.jpg)
Maybe this cause the issue with editor?

**Comment by mayasaffron** [comment]
my issue is that currently, when i try and get a preview of my work, its not showing any of the chnages ive made

**Comment by jankeromnes** [comment]
> Ok, the New one opens fine what will I do about the work I have on my other one?

@Taitdanielle Wait, I just noticed that you had created another repository: https://github.com/Taitdanielle/Gaudi-in-a-day-

Sorry, by "creating a new workspace", I simply meant opening your original project https://github.com/Taitdanielle/Gaudi-In-a-Day in a new Gitpod workspace, for example by visiting:

https://gitpod.io/#https://github.com/Taitdanielle/Gaudi-In-a-Day

I didn't mean to create a brand new repository https://github.com/Taitdanielle/Gaudi-in-a-day- where you'd have to do all the work again 😓 sorry!

**Comment by mayasaffron** [comment]
ive checked, if im deffo saving everything and i am but its not showing any of it on my preview port or even when the preview is in the browser

**Comment by mayasaffron** [comment]
do you think the git pod issue will be solved by tmw?

**Comment by jankeromnes** [comment]
> do you think the git pod issue will be solved by tmw?

@mayasaffron Sorry, which issue do you mean? I think we've discussed a few different issues:
- The Europe partial outage was resolved 2 hours ago
- The workspaces being "stuck" in the loading screen are being investigated (you can workaround it by going back to your repository and opening it in Gitpod again)
- You also mentioned an issue where the preview doesn't update -- I haven't been able to look into it yet, but I'd probably need more information, or ideally a workspace snapshot to reproduce the problem (you can take a workspace snapshot by clicking on the Avatar in the IDE)

**Comment by Taitdanielle** [comment]
Ohhh ok, my bad sorry I'll remove that one.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Dop-dd** [comment]
Bug:
 It doesn't load my images. Forms and maps are ok. But not images. I'm due to present my project to mentor in an hour and then submit it

**Comment by Valencia-08** [comment]
Hi, i am getting error 401 Authorization Required
nginx/1.14.1, whenever i try to preview my sites, when i use python3 -m html.server, it says No module named html.server, help?!

**Comment by jankeromnes** [comment]
Closing because stale + related to past incidents that got resolved. Thanks for the reports!

> Hi, i am getting error 401 Authorization Required
> nginx/1.14.1, whenever i try to preview my sites, when i use python3 -m html.server, it says No module named html.server, help?!

@Valencia-08 I think you want `http.server`, not `html.server`:

```
python3 -m http.server 3000
```

**Comment by objec7** [comment]
This is not stale this is a constant problem. Stop closing without answering the questions or FIXING the issue. Gitpod still has this issue. Just hangs nothing loads. And when it does finally decide to work it's slow and clunky at the best of times. My advice get off of Gitpod and back in your local dev environment. This is not a viable solution for serious developers with production projects.
