### ISSUE TITLE
X11 tunneling for tauri dev

### ISSUE THREAD

**Issue by NoelJacob** [gitpod-io/gitpod#14268]
### Bug description

Tauri is an app framework and so requres a $DISPLAY. I tried few ways to forward x11 but was not successful. How do I go about forwarding display? Anything other than X11 is also okay.

### Steps to reproduce

```
pnpm create tauri-app
cd app
pnpm install
pnpm tauri dev
```

**Comment by axonasif** [comment]
Hi @NoelJacob, see https://github.com/gitpod-io/workspace-images/tree/axonasif/add_docs/chunks/tool-vnc#workspace-full-vnc
