### ISSUE TITLE
gitpod not working

### ISSUE THREAD

**Issue by ashur-k** [gitpod-io/gitpod#1427]

**Comment by Kreyren** [comment]
@ashur-k Can you elaborate on what is not working?

**Comment by isontheline** [comment]
> @ashur-k Can you elaborate on what is not working?

Containers are unreachables :
403 Forbidden
nginx/1.14.1

**Comment by Kreyren** [comment]
@isontheline i can't reproduce on my end, more info?

**Comment by jankeromnes** [comment]
Indeed, sorry about this. We're investigating a current outage in Europe: #1429
