### ISSUE TITLE
Release `1.73`

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#14272]
Endgame: https://github.com/microsoft/vscode/issues/164400
Release: https://github.com/microsoft/vscode/releases/tag/1.73.0

MS release date: 2022/11/02

DRI: @filiptronicek @mustard-mh 
Plan:

- [x]  Create corresponding release branches for `main` and `gp-code/main`
    - [x] Create release branch `release/[1.xx]`
    	- Execute the rebase from upstream: `./scripts/sync-with-upstream.sh upstream/release/[1.xx] release/[1.xx]`
    - [x] Create release branch `gp-code/release/[1.xx]`
     	- Execute the rebase from upstream: `./scripts/sync-with-upstream.sh upstream/release/[1.xx] gp-code/release/[1.xx]`
        - [x] Turn off `experimental` feature flags for PortsView in gitpod-web - review and cherry-pick https://github.com/gitpod-io/openvscode-server/pull/456
- [x]  Switch nightly jobs in https://github.com/gitpod-io/openvscode-releases and Gitpod Code-Nightly GitHub actions to point to the release branches
	- [x] https://github.com/gitpod-io/openvscode-releases/blob/1b60a53a1a34b61dfb41ca13b65bfbad4115bda4/.github/workflows/insiders-gp.yml#L19
    - [x] https://github.com/gitpod-io/openvscode-releases/blob/1b60a53a1a34b61dfb41ca13b65bfbad4115bda4/.github/workflows/insiders.yml#L19
    - [x] https://github.com/gitpod-io/gitpod/blob/6c4c22c9133737d5c85948cbd01ed18144735103/.github/workflows/code-nightly.yml#L34
- [x]  Port fixes from `release/[1.xx]` to `main` if any
- [x]  Switch nightly jobs in https://github.com/gitpod-io/openvscode-releases and Gitpod Code-Nightly GitHub actions to point back to the `main` and `gp-code/main` branches
- [x]  Monitor for recovery releases and provide corresponding release in Gitpod and OpenVSCode if necessary

## For each minor / patch release

Recovery releases:
- 1.73.1 [[milestone](https://github.com/microsoft/vscode/milestone/215)]

- [x]  Create and merge a PR in https://github.com/gitpod-io/gitpod to generate a stable image for VS Code https://github.com/gitpod-io/gitpod/pull/14342
    - Update `codeCommit` inside of https://github.com/gitpod-io/gitpod/blob/main/WORKSPACE.yaml with the SHA of the tip of the `gp-code/release/{VERSION}` branch
    - Use [`insider.md`](insider.md) as a PR template
- [x]  Create and merge PR in https://github.com/gitpod-io/gitpod updating VS Code stable image tags to the image generated in the previous step (the commit can be found in the resulting Werft job) https://github.com/gitpod-io/gitpod/pull/14371
	- Update `CodeIDEImageStableVersion` in https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/workspace/ide/constants.go
	- After updating the file, execute `cd install/installer/; make generateRenderTests`
    - Use [`stable.md`](stable.md) as a PR template
- [x]  Deploy VS Code Insiders as stable ([How to deploy](https://www.notion.so/gitpod/How-to-deploy-IDE-e66a8219add74f2090bfc08104f91445) in Notion)
- [x]  Release [OpenVSCode Server](https://github.com/gitpod-io/openvscode-server)

**Comment by mustard-mh** [comment]
PR https://github.com/gitpod-io/openvscode-server/pull/456 to remove `experimental` flag and RemoteExplorer

**Comment by mustard-mh** [comment]
Added a commit https://github.com/gitpod-io/openvscode-server/commit/b60c26abfc22b0a5cf1c9b2b7ed4bab0530d2b9d to fix error message in issue https://github.com/gitpod-io/gitpod/issues/14222

```
Cannot use 'in' operator to search for 'code' in null
```

cc @jeanp413

**Comment by akosyakov** [comment]
can be closed?

**Comment by filiptronicek** [comment]
@akosyakov I think there may be some recovery releases that would go under this issue.
