### ISSUE TITLE
[sso/oidc] Add OIDC Clients UI

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#14278]
Part of [Epic: SSO/OIDC Setup Flow (for Dedicated)](https://github.com/gitpod-io/gitpod/issues/15649) and #7761

The dashboard UI to configure OIDC connections should be added to Team Settings under a "SSO" sub-menu. This UI can follow similar UI patterns as the existing Git Integrations UI (in personal settings)

Please feature flag to allow preview on gitpod.io

- List OIDC connections - if empty, show box with action button to add new connection. 
- New OIDC connection - opens empty configuration UI
- Edit OIDC connection - opens existing configuration UI
- Delete OIDC connction

**Comment by AlexTugarev** [comment]
@gtsiolis, we would like to sync with you on this issue.

**Comment by jldec** [comment]
@AlexTugarev could you list the configurable properties for an OIDC provider, for which we will provide UI?

**Comment by jldec** [comment]
### Provider config (e.g. for google workspace)

- Minimal OIDC properties

  - 
  - 
  - 

- Basic authorization hints e.g. email domain 

  - 
  -

**Comment by AlexTugarev** [comment]
Initially, it would be sufficient to have a new ~Teams~ Org page to create new OIDC client configurations.

**Comment by AlexTugarev** [comment]
@jldec, I saw your extension of the contents late, and what to clarify that I'm closing this as completed via https://github.com/gitpod-io/gitpod/pull/15903. 
The initial goal for the last iteration was to create initial UI for creation of OIDC clients. This will be extended in https://github.com/gitpod-io/gitpod/issues/15961 as soon as the API is ready to use.

**Comment by AlexTugarev** [comment]
@gtsiolis, we'd still need product design inputs on this topic.

**Comment by gtsiolis** [comment]
Adding, #15961 on the **[product design board](https://github.com/orgs/gitpod-io/projects/29)** to take a look this week. Thanks for the ping, @AlexTugarev! 🏓
