### ISSUE TITLE
Can't create or access Gitpod workspaces in Europe

### ISSUE THREAD

**Issue by circeco** [gitpod-io/gitpod#1429]

**Comment by jankeromnes** [comment]
Thanks for reporting this. We're investigating a current Gitpod outage in Europe.

We're very sorry for the disruption, and are doing our best to restore service ASAP.

**Comment by jankeromnes** [comment]
Updated https://status.gitpod.io/

**Comment by jankeromnes** [comment]
Problem should be solved, and service recovering.

**Comment by jankeromnes** [comment]
Closing this issue, but please add a comment if something still doesn't work for you, and I'll re-open it.
