### ISSUE TITLE
ws-manager: Unknown feature flag PROTECTED_SECRETS

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#14306]
### Bug description

Even though the PROTECTED_SECRETS feature flag is enabled by default.
The ws-manager shouldn't bump out this warning message.

### Steps to reproduce

https://cloudlogging.app.goo.gl/C2XMBHTR4rRFGD5y9

### Expected behavior

There is no warning message when the ws-manager receives the feature flag PROTECTED_SECRETS.

### Anything else?

https://github.com/gitpod-io/gitpod/issues/13634

**Comment by jenting** [comment]
cc @Furisto for awareness.

**Comment by Furisto** [comment]
@jenting Should be gone when https://github.com/gitpod-io/gitpod/pull/14288 is deployed

**Comment by jenting** [comment]
I did not see the warning anymore after 2022-11-03 20:44:45.000 CST
https://cloudlogging.app.goo.gl/2mEctyHBaYq3qV3R7
