### ISSUE TITLE
after npm install -g @angular/cli   , after installed if i am get 1 hr break then open project thin i need again run install cli command 

### ISSUE THREAD

**Issue by pradeepmishrapune** [gitpod-io/gitpod#1430]

**Comment by pradeepmishrapune** [comment]
expected behavior as per any example i install bootstrap it is working fine after 1 hr also

**Comment by JesterOrNot** [comment]
Try using a [custom Dockerfile](https://www.gitpod.io/docs/config-docker/)

In this case

```Dockerfile
FROM gitpod/workspace-full

RUN npm install -g @angular/cli
```

**Comment by svenefftinge** [comment]
You should go with Sean's advice. The reason is that only the state in `/workspace` is persisted between sessions and globally installed npm packages (`-g` option) are not persisted within the project. If you want to store something outside, you need to do that in the Dockerfile.
