### ISSUE TITLE
getting 403 for all gitpod.io endpoints

### ISSUE THREAD

**Issue by squeaky-godzilla** [gitpod-io/gitpod#14322]
### Bug description

I'm getting a 403 for gitpod.io/dashboard and other endpoints

### Steps to reproduce

1. open gitpod.io/dashboard
2. get 403 Forbidden error

### Workspace affected

all

### Expected behavior

see the dashboard

**Comment by axonasif** [comment]
Hi @squeaky-godzilla, are you using a VPN or proxy?

**Comment by squeaky-godzilla** [comment]
👍 thanks, disconnecting from VPN service fixed it.

is there any way I can use VPN with Gitpod?

**Comment by axonasif** [comment]
I use a VPN too, but I noticed that issue when I was connected some specific servers across VPN-countries.
I assume Gitpod blocks shared IPs that are blacklisted for abuse (e.g. https://www.projecthoneypot.org/index.php), I do not exactly know if that's the case but someone from our webapp team may know. (cc @AlexTugarev)
