### ISSUE TITLE
PVC: Deprecate the download feature

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#14364]
Changes made as part of https://github.com/gitpod-io/gitpod/issues/7901 make it difficult to keep the download feature. At the same time, this is a feature that has very low usage.

We are seeking to deprecate it, to accelerate the work on #7901, and later invest in better ways to solve the base problems that this feature was originally designed to mitigate.

As a first step we need to:
- [ ] #14380
- [x] #14381

After, we need to:
- [x] #14520
- [x] #14382
- [x] #14483
- [x] #14378

[Internal RFC](https://www.notion.so/gitpod/Deprecating-support-for-downloading-workspace-when-using-PVC-48e8b4d46176421985c7ec76a97b45f6)

**Comment by easyCZ** [comment]
The removal should also remove the endpoints. Removing anything from the UI is not sufficient. If the endpoint should remain, then changing the required permissions for the download is required.

**Comment by atduarte** [comment]
Thank you for such a fast turn around and great job, @gtsiolis! I really like option A. 🙌 Option B would be best if there were a lot of users using but in this case I don't think is necessary.

**Comment by gtsiolis** [comment]
@kylos101 I've opened https://github.com/gitpod-io/gitpod/pull/14393 to try resolving both https://github.com/gitpod-io/gitpod/issues/14381 and https://github.com/gitpod-io/gitpod/issues/14382. However, I'm no longer actively working on #14381 and have listed how we can move forward with that PR in https://github.com/gitpod-io/gitpod/pull/14393#issuecomment-1302120475.

**Comment by kylos101** [comment]
Thanks @gtsiolis ! I've added #14381 and #14382 to the WebApp board and set the status for both to in-progress. @geropl I'm not sure if there are other attributes on the project that should be set for WebApp team?

**Comment by gtsiolis** [comment]
Thanks, @kylos101! I've removed the ~**needs visual design** label and removed this issue from the **product design board** for now. From what I understand, #14380, listed in the issue description, could benefit from some design input, but let me know if this is the case. Cc @atduarte

**Comment by kylos101** [comment]
:wave: @easyCZ I've created https://github.com/gitpod-io/gitpod/issues/14483 to track your [recommendation](https://github.com/gitpod-io/gitpod/issues/14483), thank you for providing a couple options.

**Comment by gtsiolis** [comment]
@kylos101 #14393 could already cover #14483, but I'll leave this to @easyCZ to decide, see https://github.com/gitpod-io/gitpod/pull/14393/commits/3efa8bc1dc804fef034d9d1fdb841b34bd0e6e88 from #14393.

**Comment by easyCZ** [comment]
I've added a task to this epic - https://github.com/gitpod-io/gitpod/issues/14520 to remove the backend parts. It required more changes than were worth bundling into it.

**Comment by gtsiolis** [comment]
**heads-up**: @kylos101 The download functionality has been removed (merged, not deployed yet) from the workspaces list (https://github.com/gitpod-io/gitpod/issues/14381) and the admin dashboard (https://github.com/gitpod-io/gitpod/issues/14382).

We still need to resolve https://github.com/gitpod-io/gitpod/issues/14483 to completely remove the functionality. Cc @atduarte

**Comment by easyCZ** [comment]
The backend removal PRs are open, referenced in the issue 
* https://github.com/gitpod-io/gitpod/issues/14483

**Comment by atduarte** [comment]
Closed as not planned given implementation of PVC in its existing form was halted.

**Comment by gtsiolis** [comment]
Thanks, @atduarte! heads-up: Although we reverted most of the changes listed in the description issue we haven't reverted the docs changes in https://github.com/gitpod-io/website/pull/3007.

**Comment by atduarte** [comment]
Thanks, @gtsiolis! Reverting that too.

**Comment by gtsiolis** [comment]
Cross-posting relevant issue in case anyone runs into this issue in the future:

- https://github.com/gitpod-io/gitpod/issues/14829
