### ISSUE TITLE
[UBP] Show "Credits used" and "Usage limit" and "Next reset or bill" on admin dashboard pages for users and teams

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14367]
If users or teams have UBP enabled, it will be important for admins to access their usage balance.

- [ ] Credits used since the last invoice or monthly reset
- [ ] Usage limit as configured
- [ ] Next monthly billing or (free tier) reset date

This could mirror the balance used indicators which users see on their personal or team billing settings.

**Comment by jldec** [comment]
Additional suggestions (from discussion with @gtsiolis)

- Can combine credits used / usage limit in one block with 2 actions
- Can show UBP Plan (billing strategy) re-using the existing "Plan" element and combine that with showing next reset date in the same block.

**Comment by gtsiolis** [comment]
Added some relevant design specs that could be overlapping for this issue in https://github.com/gitpod-io/gitpod/issues/14591#issuecomment-1315644715.
