### ISSUE TITLE
Gitpod still uses a very old Docker image for https://github.com/openai/gym

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#1437]
### Describe the bug
When you open https://github.com/openai/gym in Gitpod, you get a Docker image that seems to be from 2019.

### Steps to reproduce
1. Open https://gitpod.io/#https://github.com/openai/gym
2. Run `pyenv versions`
3. Notice that it's still using Python 3.7.4

We've upgraded `gitpod/workspace-full` to Python 3.7.5 on [2020-01-03](https://github.com/gitpod-io/workspace-images/commit/4a098f0ed0863481584eb1e0b5f307d25fe860dc), and then upgraded again a few more times.

### Expected behavior

It should have Python 3.8.2 (i.e. what's [currently in gitpod/workspace-full](https://github.com/gitpod-io/workspace-images/blob/f2fe95173d79cf116411d3df2d52d8a5f2572676/full/Dockerfile#L211)) or more recent.

### Additional information

A workaround seems to be to commit a change to your `.gitpod.Dockerfile`.

Several projects seems to have adopted a trick where you increment an unused `ENV` variable whenever you need a newer base image: https://github.com/eclipse-theia/theia/blob/c5014828501607bc26e57808b8f5594d45973e13/.gitpod.dockerfile#L3-L4

**Comment by Kreyren** [comment]
> It should have Python 3.8.2 (i.e. what's currently in gitpod/workspace-full) or more recent.

What about backports ?
