### ISSUE TITLE
kubecdl does not fall over to other control plane node if the 1st node k3s kubeconfig unavailable

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#14419]
### Bug description

When the incident https://gitpod.slack.com/archives/C049CU0GM8D happened, we couldn't use the kubecdl to download the remote control plan server k3s KUBECONFIG.
It's because the kubecdl list all control plane server nodes but will only ssh into the 1st node to download the k3s KUBECONFIG.

Unfortunately, the incident was the 1st server node without the k3s KUBECONFIG, and the kubecdl does not fall over to other nodes to download the k3s KUBECONFIG locally.

### Steps to reproduce

Make the 1st server nodes without k3s KUBECONFIG. We could change the path of the k3s KUBECONFIG.

### Expected behavior

kubecdl to use a different VM that with the available k3s KUBECONFIG.

**Comment by aledbf** [comment]
@jenting I think this is an exception, not the norm, and treat it like that, meaning, if a VM is replaced and we lose the content, use gcloud ssh. In any case, the node is useless after the replacement. We can delete the "first" VM or change kubecdl to use a different VM. For the first option, we don't need to write code.

**Comment by jenting** [comment]
> change kubecdl to use a different VM

I was considered choose option 2.
I update the description.
