### ISSUE TITLE
Terminal issue

### ISSUE THREAD

**Issue by wesbitty** [gitpod-io/gitpod#14413]
### Bug description

I’m having terminal issue with my workspace

### Steps to reproduce

Don’t know

### Expected behavior

The terminal refuse to show words

### Anything else?

Nothing else

**Comment by Azeezdot123** [comment]
I feel you need to just restart the workspace.

**Comment by wesbitty** [comment]
> I feel you need to just restart the workspace.

I did that already, still it doesn't work

**Comment by Azeezdot123** [comment]
If you can try and reproduce it and then screenshot the problem I think you could get more help with it.
