### ISSUE TITLE
Custom docker image isn't working

### ISSUE THREAD

**Issue by viceice** [gitpod-io/gitpod#14424]
### Bug description

We try to build our own image for gitpod. It builds successfully but then fails to start the workspace

### Steps to reproduce

https://gitpod.io/#https://github.com/renovatebot/renovatebot.github.io/pull/244

### Workspace affected

https://gitpod.io/start/#renovatebot-renovatebot-a87uogj7ht0

### Expected behavior

A custom image should work. Or it should give a error message to solve the cause.

### Example repository

- https://github.com/renovatebot/renovatebot.github.io/pull/244

### Anything else?

https://discord.com/channels/816244985187008514/1035211944107462746

browser logs
![image](https://user-images.githubusercontent.com/1798109/199939537-a0765de1-8415-4c3f-8184-aee74a6c3a0b.png)

**Comment by viceice** [comment]
not stale 😕 still a big issue

**Comment by viceice** [comment]
not stale 😕

**Comment by axonasif** [comment]
Hi @viceice,

It's likely because of missing dependencies on your custom dockerfile (image). You can use this as a reference: https://www.gitpod.io/docs/configure/workspaces/workspace-image#ubuntu

**Comment by axonasif** [comment]
@viceice I proposed a fix 🎉 
https://github.com/renovatebot/renovatebot.github.io/pull/326

**Comment by viceice** [comment]
so the fix is that the primary group needs to be gitpod?
