### ISSUE TITLE
Show Theia's version in Gitpod about

### ISSUE THREAD

**Issue by felipecrs** [gitpod-io/gitpod#1444]
This would make things more transparent, It would be cool to see if the running Gitpod's Theia is based on 1.0 for instance, or not 😊.

Here I mean: 
![image](https://user-images.githubusercontent.com/29582865/80288212-d1f3e200-870c-11ea-9919-0eef627e14ad.png)

**Comment by jankeromnes** [comment]
Agreed that it would be cool! 😁

Also yes, that's Theia 1.1.0, with built-in extensions from Open VSX! 🎉 (I'm late adding it to https://www.gitpod.io/docs/changelogs/ -- sorry about that, will do soon)

**Comment by felipecassiors** [comment]
> Also yes, that's Theia 1.1.0, with built-in extensions from Open VSX! 

That's awesome to know!

**Comment by felipecrs** [comment]
:-(
