### ISSUE TITLE
Gitpod Terminals not displaying text

### ISSUE THREAD

**Issue by PlanexDev** [gitpod-io/gitpod#14459]
### Bug description

Whenever I open a workspace, the terminal only shows the following:
![IMG_0701](https://user-images.githubusercontent.com/104588511/200187669-55133804-9d9c-4e14-9d48-43a821b4d304.jpeg)

Everything works and I can type and run commands like normal. However, no output shows up, and that’s all there is.

### Steps to reproduce

Open any workspace, even an empty one.

### Expected behavior

The terminal should be correctly functioning.

### Example repository

Works for all workspaces I’ve tested so far.

**Comment by PlanexDev** [comment]
Extra information: This only happens in VSCode Browser, not in JetBrains IDEs, haven't tested with VSCode Desktop

**Comment by svenefftinge** [comment]
What browser & version do you use?

**Comment by PlanexDev** [comment]
iOS Safari 15.6. This started happening a few days ago, never happened before

**Comment by PlanexDev** [comment]
Tested this on Chrome 103 on Linux, no bug

**Comment by fawaz-alesayi** [comment]
Can confirm the same issue.
Blink v16.0.1.616

**Comment by axonasif** [comment]
Hi, could you guys please follow this?
- https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop

**Comment by akosyakov** [comment]
It seems to be a regression in the upstream: https://github.com/microsoft/vscode/issues/165416

Try to disable gpu acceleration how suggested here: https://github.com/microsoft/vscode/issues/165416#issuecomment-1302651173
