### ISSUE TITLE
Make Gitpod a Progressive Web App

### ISSUE THREAD

**Issue by felipecrs** [gitpod-io/gitpod#1445]
With this, Gitpod workspaces could be opened in Gitpod PWA instead of as a tab in the browser. It would save a lot of space in the top bar and make Gitpod online IDE feels more like a desktop app.

CodeSandbox supports it: https://codesandbox.io/s/.

Note that users can force the install of Gitpod as a PWA by themselves, however, supporting it by default has some benefits:
- better icons
- better window title
- title bar theming
- a beautiful prompt to install as a app in Google Chrome
- and more, of course.
- ability to open by default new workspaces in Gitpod's previously installed PWA

Look at how different the size could be in the browser:
Before ![image](https://user-images.githubusercontent.com/29582865/80288360-e389b980-870d-11ea-9f27-d335efd89ad2.png)

After
![image](https://user-images.githubusercontent.com/29582865/80288364-ee444e80-870d-11ea-9261-74a41d32bb92.png)

**Comment by svenefftinge** [comment]
Did you see https://itnext.io/i-wrote-a-chrome-extension-gitpod-window-here-is-what-i-learned-8583a3a179dd

**Comment by Kreyren** [comment]
***kreyren** would implement this as a configuration option*

**Comment by felipecassiors** [comment]
@svenefftinge that's cool, pretty much what I was looking for. 

However, with the PWA this extension would not be required. So, I think the PWA is still an improvement, don't you think?

**Comment by jankeromnes** [comment]
I 100% agree that it would be super cool to make Gitpod a Progressive Web App that you can install on any device and use full-screen / with native keybindings. 🚀

For that, we should:
- [x] Add a `manifest.json` file: https://gitpod.io/manifest.json
- [ ] Add a Service Worker with a `fetch` handler, to explicitly implement caching & offline behavior (doesn't have to be full-blown functional offline IDE at first, but can work towards that in small steps)

Learn more: https://web.dev/progressive-web-apps/

**Comment by stoopman** [comment]
are there any concrete plans for this feature?

**Comment by dragonDScript** [comment]
> I 100% agree that it would be super cool to make Gitpod a Progressive Web App that you can install on any device and use full-screen / with native keybindings. rocket
> 
> For that, we should:
> 
>     * [x]  Add a `manifest.json` file: https://gitpod.io/manifest.json
> 
>     * [ ]  Add a Service Worker with a `fetch` handler, to explicitly implement caching & offline behavior (doesn't have to be full-blown functional offline IDE at first, but can work towards that in small steps)
> 
> 
> Learn more: https://web.dev/progressive-web-apps/

A service worker is not required by Chrome Desktop, Firefox and Edge. Only on Chrome Android.

Having said this, the Service Worker has already been implemented. (If you open gitpod and turn off your connection you'll see an 'offline' text and the menu at the bottom will turn yellow)

**Comment by dragonDScript** [comment]
> I 100% agree that it would be super cool to make Gitpod a Progressive Web App that you can install on any device and use full-screen / with native keybindings. 🚀
> 
> For that, we should:
> 
> * [x]  Add a `manifest.json` file: https://gitpod.io/manifest.json
> * [ ]  Add a Service Worker with a `fetch` handler, to explicitly implement caching & offline behavior (doesn't have to be full-blown functional offline IDE at first, but can work towards that in small steps)
> 
> Learn more: https://web.dev/progressive-web-apps/

It is manifest.webmanifest following the web standards.

**Comment by atduarte** [comment]
I certainly empathize with the shortcuts (e.g. cmd/ctrl-w) issue and loss of vertical space. 

Currently, we are investing in improving the local experience by allowing users to seamlessly use their preferred local IDE. In my opinion, such an experience will feel more native and natural than a PWA, while it also solves the issues mentioned here.

We wrote a blog post with some preliminary details ([here](https://www.gitpod.io/blog/local-app)) and will share more soon.

**Comment by stoopman** [comment]
> I certainly empathize with the shortcuts (e.g. cmd/ctrl-w) issue and loss of vertical space.
> 
> Currently, we are investing in improving the local experience by allowing users to seamlessly use their preferred local IDE. In my opinion, such an experience will feel more native and natural than a PWA, while it also solves the issues mentioned here.
> 
> We wrote a blog post with some preliminary details ([here](https://www.gitpod.io/blog/local-app)) and will share more soon.

@atduarte I'll keep an eye on this for sure, it sounds promising!
I love the whole idea of Gitpod, but my main IDE is PHPStorm and I know it's available through projector in the browser, the developer experience just doesn't compare to using the native local app. You mention that you are investigating being able to use your preferred local IDE in combination with a remote workspace. Does that only apply to VS Code editors? I can imagine it would be hard to achieve this with Intellij IDE's. This would be my holy grail though ;)

**Comment by atduarte** [comment]
> Does that only apply to VS Code editors? 

We will start with VS Code, but ultimately the goal is to support others :)

**Comment by dragonDScript** [comment]
> > I certainly empathize with the shortcuts (e.g. cmd/ctrl-w) issue and loss of vertical space.
> > Currently, we are investing in improving the local experience by allowing users to seamlessly use their preferred local IDE. In my opinion, such an experience will feel more native and natural than a PWA, while it also solves the issues mentioned here.
> > We wrote a blog post with some preliminary details ([here](https://www.gitpod.io/blog/local-app)) and will share more soon.
> 
> @atduarte I'll keep an eye on this for sure, it sounds promising!
> I love the whole idea of Gitpod, but my main IDE is PHPStorm and I know it's available through projector in the browser, the developer experience just doesn't compare to using the native local app. You mention that you are investigating being able to use your preferred local IDE in combination with a remote workspace. Does that only apply to VS Code editors? I can imagine it would be hard to achieve this with Intellij IDE's. This would be my holy grail though ;)

Intellij is impossible to support, since it does not use web technologies. It'd be very hard  or impossible to support it.

Gitpod will support web-based IDEs.

**Comment by akosyakov** [comment]
> Intellij is impossible to support, since it does not use web technologies. It'd be very hard or impossible to support it.

It is not about running Intellij in browser, but using local Intellij to connect to remote workspace. Similarly how VS Code Remote works: https://code.visualstudio.com/docs/remote/remote-overview JetBrains actively working on closing this gap for them: https://youtrack.jetbrains.com/issue/IDEA-226455

**Comment by akosyakov** [comment]
> I love the whole idea of Gitpod, but my main IDE is PHPStorm and I know it's available through projector in the browser, the developer experience just doesn't compare to using the native local app. You mention that you are investigating being able to use your preferred local IDE in combination with a remote workspace. Does that only apply to VS Code editors? I can imagine it would be hard to achieve this with Intellij IDE's. This would be my holy grail though ;)

PHPStorm already support remote interpreters, some community members trying to make it work via [the local companion](https://www.gitpod.io/blog/local-app): https://community.gitpod.io/t/lets-talk-gitpod-local-companion-localhost/3998/7

**Comment by stoopman** [comment]
I just had a quick look at coder.com and it looks like they support local Intellij IDE in combination with the Code With Me feature to connect to the remote workspace. I guess this is a good approach as well?
https://coder.com/docs/coder/v1.20/workspaces/editors#code-with-me

**Comment by svenefftinge** [comment]
> Code With Me feature to connect to the remote workspace

I'm currently somewhat holding my breath, since I hope Jetbrains is releasing the proper remote development support [rather soon](https://youtrack.jetbrains.com/issue/IDEA-226455#focus=Comments-27-5125731.0-0).

**Comment by dragonDScript** [comment]
> I certainly empathize with the shortcuts (e.g. cmd/ctrl-w) issue and loss of vertical space.
> 
> Currently, we are investing in improving the local experience by allowing users to seamlessly use their preferred local IDE. In my opinion, such an experience will feel more native and natural than a PWA, while it also solves the issues mentioned here.
> 
> We wrote a blog post with some preliminary details ([here](https://www.gitpod.io/blog/local-app)) and will share more soon.

What about chromebooks?

**Comment by atduarte** [comment]
> What about chromebooks?

Good question. For now, given the low usage by our users, the high cost of developing it, and our engineering capacity constraints we are not prioritizing it.

In the meantime, it may be worth checking the post @svenefftinge mentioned above ([link](https://itnext.io/i-wrote-a-chrome-extension-gitpod-window-here-is-what-i-learned-8583a3a179dd)) and the associated non-official extension [gitpod-window](https://chrome.google.com/webstore/detail/gitpod-window/jhpkbhdoenpnfnnkelgpikndadikogdl?hl=en).

**Comment by felipecrs** [comment]
And Chromebooks runs VS Code, if Linux support is enabled.

**Comment by dragonDScript** [comment]
> And Chromebooks runs VS Code, if Linux support is enabled.

Althought most chromebooks are able to run vscode, including mine, it is slower than gitpod.

**Comment by felipecrs** [comment]
> > And Chromebooks runs VS Code, if Linux support is enabled.
> 
> Althought most chromebooks are able to run vscode, including mine, it is slower than gitpod.

I suppose you mean it's slow when developing locally, right? The goal here was to use VS Code not to develop locally, but remotely connected to the Gitpod environment. Just like Codespaces.

**Comment by dragonDScript** [comment]
> > > And Chromebooks runs VS Code, if Linux support is enabled.
> > 
> > 
> > Althought most chromebooks are able to run vscode, including mine, it is slower than gitpod.
> 
> I suppose you mean it's slow when developing locally, right? The goal here was to use VS Code not to develop locally, but remotely connected to the Gitpod environment. Just like Codespaces.

Both locally and remotely. Using the browser is just better.

**Comment by hrishirc** [comment]
Also, mobile mode with Samsung DeX

**Comment by ljieyao** [comment]
looking forward for this feature, desperately need to install it as PWA, anyone started working on this already?

**Comment by axonasif** [comment]
@hrishirc @ljieyao
## If you're on chrome-desktop:
- You can install gitpod.io as a chromium app from `top right three dotted icon> More Tools> Create Shortcut` while being on the https://gitpod.io page
<img width="1212" alt="Screenshot 2022-02-03 at 1 36 19 PM" src="https://user-images.githubusercontent.com/39482679/152300425-fc73a0ba-4f06-4be4-abf9-72f386ac5223.png">

- Or you can use a [chromium extension](https://chrome.google.com/webstore/detail/gitpod-window/jhpkbhdoenpnfnnkelgpikndadikogdl?hl=en)

## If you are on mobile:
- I recommend using Kiwi browser(android), it features a full-blown Dev-console like desktop, chromium based and OSS.
- Visit https://gitpod.io/ and from your browser menu use `Add to Homescreen` button. (Works for most chromium browsers such as Google-Chrome, Brave, Opera, Kiwi, Vivaldi etc.)
- Your browser will detect it as PWA and install the app.
![Screenshot_20220203-134013](https://user-images.githubusercontent.com/39482679/152304135-fca0e248-ff92-4f89-a5f7-522e20638eb0.png)

**Comment by bachrc** [comment]
Does not work anymore on iPad. Previously there were a fullscreen app, but now doing « Add to homescreen » just opens Safari.

**Comment by loujaybee** [comment]
👋 - Dropping by here to note that we are running some experiments with improvements to our desktop experience, which does include exploring a desktop application / more native experience for desktop. If you'd be interested to join us for some early experimentation in this area, and to give us feedback on what you'd like to see, we've added "Gitpod Desktop App" to [gitpod.io/labs](https://gitpod.io/labs). Feel free to sign up there for early and pre-release updates.
