### ISSUE TITLE
bitbake vscode extension

### ISSUE THREAD

**Issue by chiyanglin-AStar** [gitpod-io/gitpod#14455]
## Is your feature request related to a problem? Please describe

on my laptop , vscode can find bitbake extension 

## Describe the behaviour you'd like

in gitpod vscode , also can find bitbake extension

## Describe alternatives you've considered

let me know how to add extension by manual

**Comment by pawlean** [comment]
Hey @chiyanglin-AStar! 👋🏼 

Our documentation details how to install extensions [here](https://www.gitpod.io/docs/references/ides-and-editors/vscode-extensions#vs-code-extensions). Feel free to also drop by [our community Discord server](https://www.gitpod.io/chat) for help with these types of questions!

Let me know if I can help with anything else.

**Comment by chiyanglin-AStar** [comment]
@pawlean tks a lot for reply !   but I follow instruction , still not work !    and I am not allowed to drop message in Discord !    
                 just provide this extension info. to you for reference : 
                            https://marketplace.visualstudio.com/items?itemName=EugenWiens.bitbake
                            https://github.com/bjorkstromm/vscode-bitbake

**Comment by axonasif** [comment]
Hi @chiyanglin-AStar, not sure why you can't drop message on discord, maybe try again 😅 

You can use that extension by opening your workspace on vscode desktop:
- https://www.gitpod.io/docs/ides-and-editors/vscode

**Comment by chiyanglin-AStar** [comment]
@axonasif  tks a lot !  it could be that I am not familar with discord !   
                      
                   I know that bitbake extension can support vscode desktop ,  my question is how to add this extension in vscode browser !  if it can't support for now , just let me know ! tks  a lot !

**Comment by axonasif** [comment]
> if it can't support for now , just let me know ! tks a lot !

It's possible to use it on the browser(web) version, but I can't show you how. So in other words.. yeah, it's not supported **right now**.

But, you can get it on the browser(web) vscode by asking the extension author to publish on https://open-vsx.org/, resharing a (tag)link  which Pauline had already shared 🙂 :
- https://www.gitpod.io/docs/references/ides-and-editors/vscode-extensions#where-do-i-find-extensions

**Comment by chiyanglin-AStar** [comment]
@axonasif very tks a lot for explanation ! not sure that arthor have interest to follow open-vsx to revise ! 
                  if you have any better tool for yocto or bitbake on vscode , please let me know ! tks again !
