### ISSUE TITLE
Technical breakdown of Gitpod Personal tokens

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#14465]
Break down the work for https://github.com/gitpod-io/gitpod/issues/14280 into individual steps.

Acceptance Criteria:
* Outline of how we will approach the problem
* Outline how we will store the tokens
* Outline of milestones, with rollout plan for each

**Comment by laushinka** [comment]
Outcome of this ticket is included in the [Epic](https://github.com/gitpod-io/gitpod/issues/14280) description.
