### ISSUE TITLE
UBP Free tier usage page should match the Balance Used period in personal billing settings

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14463]
This is a followup to #14363

Both the usage page and the balance used indicator should show the actual period for total credits used since the last reset.

See https://github.com/gitpod-io/gitpod/issues/14363#issuecomment-1301869158 for details.

**Comment by jankeromnes** [comment]
Didn't we decide that the Usage page should be completely unrelated to any billing cycle?

I remember us reaching a conclusion akin to:
- Billing page should reflect your exact current billing cycle usage
- Usage page should show your latest Usage, independently of any cycles, and e.g. allow you to see "last  day", "last 7 days", "last 30 days", etc

Cc @easyCZ as I think you originally advocated for the uncoupled Usage page periods.

**Comment by svenefftinge** [comment]
I think it would be useful to default to the current billing cycle and then allow users to flexibly pick any other range.
