### ISSUE TITLE
[server] Error: Field 'userId' doesn't have a default value 

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#14464]
Just seen repeated occurrences in logs – no further helpful stacktrace attached. 

```
QueryFailedError: ER_NO_DEFAULT_FOR_FIELD: Field 'userId' doesn't have a default value
```

**Comment by easyCZ** [comment]
This started happening on Oct 15

[logs](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22server%22%2529%0A%22QueryFailedError:%20ER_NO_DEFAULT_FOR_FIELD:%20Field%20'userId'%20doesn't%20have%20a%20default%20value%22;timeRange=P60D;cursorTimestamp=2022-11-14T08:18:40.537Z?authuser=0&project=gitpod-191109)

**Comment by easyCZ** [comment]
Started with version `main.5165`

**Comment by easyCZ** [comment]
The issue seems to be somewhere between these commits:
https://github.com/gitpod-io/gitpod/compare/fccdaa3921a58f00caa834b8dcf3a21120478d45...a4870ce5db87d35a4547afee07836e82018e50e3

**Comment by easyCZ** [comment]
While parigin with @AlexTugarev, we've narrowed it down to a hypothesis that this is caused by the OAuthCode table, which stores the `userId` but allows `null` values, whereas the schema requires NOT NULL.

Alex will follow-up with a validation whether this is indeed the cause.

**Comment by easyCZ** [comment]
Validation: https://github.com/gitpod-io/gitpod/pull/14706

**Comment by easyCZ** [comment]
The fix in https://github.com/gitpod-io/gitpod/pull/14706 didn't actually fix the issue, we're still [getting the errors ](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22server%22%2529%0A%22ER_NO_DEFAULT_FOR_FIELD%22;timeRange=PT30M;cursorTimestamp=2022-11-16T08:32:27.360Z?authuser=0&project=gitpod-191109)

**Comment by geropl** [comment]
We identified the root cause to be [this line](https://github.com/gitpod-io/gitpod/blob/0d7f5d66d3d130d640a3b936fc3e1ca994fb0cc7/components/gitpod-db/src/typeorm/auth-code-repository-db.ts#L61). The log PR did not trigger because of the missing `await`.

**Comment by AlexTugarev** [comment]
Unbelievable, this is still not working.
