### ISSUE TITLE
Replace "Usage-based" with "Pay-as-you-go"

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14475]
Pay-as-you-go is friendlier, less-jargony, and somewhat self-explanatory.
This change would impact the folowing dashboard UI elements.
The first page below requires the most re-design thinking.
Separate docs issue to follow UI changes gitpod-io/website#3004
cc: @gtsiolis

## team billing - no billing configured
<img width="1100" alt="Screenshot 2022-11-07 at 12 14 35" src="https://user-images.githubusercontent.com/849592/200309856-9a08e7e5-e05b-4289-aa6d-d936bf0c617c.png">

## team biling - billing configured
<img width="1100" alt="Screenshot 2022-11-07 at 12 17 42" src="https://user-images.githubusercontent.com/849592/200309951-995af807-f607-4242-82f5-19663e8b31ea.png">

## user billing - no billing configured
<img width="1100" alt="Screenshot 2022-11-07 at 12 16 16" src="https://user-images.githubusercontent.com/849592/200310493-a31f0c3a-6b81-43ea-a756-1efb6082ed6e.png">

## user billing - paid plan configured
<img width="1100" alt="Screenshot 2022-11-07 at 12 31 06" src="https://user-images.githubusercontent.com/849592/200311263-7522f814-e8ca-45fe-b1f9-166c692a7cd9.png">

**Comment by gtsiolis** [comment]
Thanks for shipping this, @jldec! 🙌
