### ISSUE TITLE
Alternative .gitpod.yml location

### ISSUE THREAD

**Issue by abitrolly** [gitpod-io/gitpod#14476]
## Is your feature request related to a problem? Please describe

I'm always frustrated when the root of the project is filled up with dozens of .dotfiles.

## Describe the behaviour you'd like

Autodetect location of `.gitpod.yml` in other dot dirs, and show debug message about it on startup.

## Describe alternatives you've considered

* Specify location to `.gitpod.yml` in URL.

## Additional context

https://github.com/teaxyz/cli/pull/127

**Comment by mxcl** [comment]
In fact we'd like to offer some kind of collaboration where tea defines how to build a project in that projects README using executable markdown and gitpod can infer that itself (without tea/cli).

**Comment by abitrolly** [comment]
Oh I like that. Especially if README.md can having a collapsible section with the location of these files. What should be the convention for section name? Or just freestyle text at the beginning of the line?

```
.gitpod.yml: .somerepodir/gitpod.yml
```

Although for human consumption, I would stuff this at the end of file.

<details>
  <summary><h3>Config<h3></summary>

```yaml
.gitpod.yml: .somerepodir/gitpod.yml
```
</details>

---

And the template.

    <details>
      <summary><h3>Config<h3></summary>
    
    ```yaml
    .gitpod.yml: .somerepodir/gitpod.yml
    ```
    </details>

**Comment by axonasif** [comment]
Possible duplicate: https://github.com/gitpod-io/gitpod/issues/729

**Comment by mxcl** [comment]
my request was more for `.github/godpod.yml` (even though `github` is not relevant, it's become a kinda standard place to put meta project config).
