### ISSUE TITLE
Use a friendlier error message in the dashboard when creating a team with an existing name

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#14482]
### Problem to solve

The product no longer surfaces a user friendly error message when a user tries to create a team using an existing team name.

This could be related to the recent switch to consume our API internally for such operations, see possibly relevant pull request in https://github.com/gitpod-io/gitpod/pull/14406. Cc @easyCZ 

See [relevant discussion](https://gitpod.slack.com/archives/C0463A2KQUU/p1667834471387539) (internal).

<img width="369" alt="Screenshot 2022-11-07 at 5 15 51 PM" src="https://user-images.githubusercontent.com/120486/200352621-18f182b9-2eac-4cf8-aacf-98233083a294.png">

**Comment by jankeromnes** [comment]
Thanks @gtsiolis for spotting this issue!

FYI, we were already trimming user-unfriendly parts of error messages in this page:

https://github.com/gitpod-io/gitpod/blob/88fa55e9a240e2b682919a779f47347f4842e6fe/components/dashboard/src/teams/NewTeam.tsx#L65

I guess we'll simply need to adjust this code to remove the new user-unfriendly prefix. 😇

**Comment by easyCZ** [comment]
With the Public API using `connect-web`, we have access to much richer error messages. We can handle the errors as per https://connect.build/docs/web/errors without needing to trim.

The problem here is that the Go API client for the Websocket API bundles the code and the message together. We need to unbundle (or handle explicitly) these in the Public API, it's currently done here 
https://github.com/gitpod-io/gitpod/blob/main/components/public-api-server/pkg/proxy/errors.go#L13-L55

**Comment by easyCZ** [comment]
https://github.com/gitpod-io/gitpod/pull/14490 adds support to better unwrap error responses from `server` -> `public-api`. 

On the client, we still need to handle these as well, we should do the following:
```typescript
try {
  await client.something({});
} catch (err) {
  // We have to verify err is a ConnectError
  // before using it as one.
  if (err instanceof ConnectError) {
    err.code;    // Code.InvalidArgument
    err.message; // "sentence cannot be empty"
  }

  // handle it as before, the above will only trigger for the Public API case (behind a feature flag)
}
```

**Comment by easyCZ** [comment]
Validated this change works in prod.



![Image](https://user-images.githubusercontent.com/1419286/200837915-13c0c992-be66-4fa2-ad24-ccff4e9dcff8.png)

**Comment by gtsiolis** [comment]
Looks great, @easyCZ! Thanks for confirming. 🏓
