### ISSUE TITLE
Gitpod Terminal sometimes forgets its own height (garbled `less` output)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#14484]
### Bug description

If you use `git diff`, `git log`, or any other terminal command that's using `less` to paginate output, you're probably seeing this bug regularly:

<a href="https://youtu.be/ujG9pKhUFE8"><img width="600" alt="Screenshot 2022-11-07 at 16 57 07" src="https://user-images.githubusercontent.com/599268/200355732-dfccfb89-ebd0-47fb-9754-c80e88355369.png"></a>

It seems that the terminal somehow forgets its own height sometimes, leading to any `less`-based output being "garbled" (scrolling down is "janky" and shows random nonsense on some lines).

The workaround is to just slightly change the terminal height. This instantly fixes `less` output (until the next time the terminal forgets its height).

### Steps to reproduce

1. Use an in-browser VS Code workspace
2. ??
3. Quite often, you'll notice that the output of any `less`-based commands (like `git diff`) is janky to scroll and somewhat garbled

### Expected behavior

`git diff` should always scroll smoothly and never be garbled

### Example repository

https://github.com/gitpod-io/gitpod

**Comment by jeanp413** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/166682 but seems it's already fixed in insiders.
@jankeromnes could you try insiders and see if you can repro there
Closing for now
