### ISSUE TITLE
[self-hosted] prebuilds may be scheduled during Gitpod upgrade

### ISSUE THREAD

**Issue by adrienthebo** [gitpod-io/gitpod#14495]
### Bug description

During a debugging session of a gitpod self-hosted upgrade we noticed that prebuilds were being created during the upgrade process. We assume that workspaces will be stopped during the upgrade process; prebuilds break this assumption in a pretty surprising way and may lead to odd workspace behaviors if ws-daemon is restarted on a node containing a running prebuild.

### Steps to reproduce

1. Create a gitpod instance and verify that prebuilds are generated for a given repository
2. Begin the upgrade process and stall it; scaling up the number of workspace nodes is a pretty reliable mechanism of slowing down the upgrade process.
3. While the upgrade is running, push a commit to a repo that will trigger a prebuild.

### Expected behavior

Prebuilds should be disabled while gitpod is upgrading.

**Comment by aledbf** [comment]
@adrienthebo to avoid any new workload in the cluster, you should cordon the cluster or adjust the score to 0 (gpctl)
