### ISSUE TITLE
configurable timeout until server stops

### ISSUE THREAD

**Issue by rdmueller** [gitpod-io/gitpod#145]
The timeout is currently set to 30 minutes.

This is quite long since if I get distracted and leave my machine alone, it will cost me 30 minutes of my valuable 10 hrs time :-)

So it would be great if I could configure this timeout to lets say 10 minutes.

And someone who uses gitpod to give a training might wish for 1hr...

**Comment by adamskrodzki** [comment]
I understand that it is a matter of resources allocation, but would be great if workspaces instead of being shut down go to some hibernation mode, from which they can be awaken ir requested

**Comment by svenefftinge** [comment]
No it hasn't changed, this is how it works. 
You can go to your dashboard (https://gitpod.io/workspaces) to start your stopped workspaces again.

**Comment by codemzy** [comment]
I'd love to be able to set a longer timeout option, maybe an hour. A couple of occasions I've been timed-out when testing out the UI myself or trying to solve a complex problem. It's not a big deal because you can restart, but would be a good enhancement on paid plans :)
