### ISSUE TITLE
Personal usage page does not show settings menu

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#14506]
`https://gitpod.io/usage` should show the settings menu as well.

| ACTUAL | EXPECTED |
| - | - |
| <img width="423" alt="Screenshot 2022-11-08 at 11 30 22" src="https://user-images.githubusercontent.com/8015191/200541617-0712c544-b868-4034-bb9e-5b606ef04bd6.png"> | <img width="323" alt="Screenshot 2022-11-08 at 11 32 12" src="https://user-images.githubusercontent.com/8015191/200541903-c9a0ba44-4e40-464c-af3b-0b6505ce26e8.png"> |

**Comment by gtsiolis** [comment]
Currently, the usage page is designed as a full page layout.

See also [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1666879099675049) (internal) and https://github.com/gitpod-io/gitpod/issues/14240.

**Comment by jldec** [comment]
Let's keep it full page - this navigation weirdness does not justify redesigning the page.

To maintain discoverability, we could remove it from the settings sidebar, and put it in the main user dropdown at the top instead.
