### ISSUE TITLE
Execute specific integration tests instead of all

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#14504]
## Is your feature request related to a problem? Please describe
Executing all integration tests can take a while. It would be great if one could specify which of the integration tests should be executed. This would speed up integration of PRs as one could then do` integration-test=TestCpuBurn,TestPrebuild` to execute only the tests that have been failing.

## Describe the behaviour you'd like
Specifiy the integration tests you would like to run in the PR. Only those tests should be executed.

## Describe alternatives you've considered
Continue executing all integration tests.

**Comment by Furisto** [comment]
@kylos101 This issue is not for running the integration tests locally in your workspace because as you have mentioned running a subset of tests is already possible there. The focus of this issue is on speeding up PRs. Often only a single test is failing and after fixing that test having to run every test with `integration-test=workspace` on the PR takes time (although less now that we have parallelized integration tests). 

The idea here is to allow something like `integration-test=TestCpuBurn,TestPrebuild.`

**Comment by kylos101** [comment]
I see :bulb: , thanks @Furisto ! As this is related to devX, I will add to their related project for consideration. They're considering https://github.com/gitpod-io/gitpod/issues/13598.  cc: @meysholdt

**Comment by kylos101** [comment]
@Furisto also, I removed Team Workspace from this, as it's more of a cross cutting concern that should be handled by DevX.
