### ISSUE TITLE
stopped responding to css

### ISSUE THREAD

**Issue by Kittencode91** [gitpod-io/gitpod#1451]
### Describe the bug
The workspace has stopped responding to my css code. 

### Steps to reproduce
started new workspace

### Expected behavior
to respond again

### Additional information
It worked fine in Repl.it

### Example repository
kittencode91/template

**Comment by svenefftinge** [comment]
Can you elaborate what you mean by 'stopped responding'?

**Comment by Kittencode91** [comment]
Yeah, sorry. So when I saved it and then "ran" it again to see the updated version in the webpage window it stopped updating to the most current version of my CSS3 file.

I retested both my HTML and CSS3 in repl.it and it was fine. Gave me the correct result.

So I concluded it was Gitpod that was having issues.

Thanks.

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by svenefftinge** [comment]
Ok, I assume you are using `python3 -m http.server` to run the webserver?
I think that webserver does some sort of caching.

I'd recommend using
```
npx browser-sync start -s -w --ui-port 40001
```
because that will also auto-update on save, which is were convenient.
