### ISSUE TITLE
Forking forked GitHub Repo fails

### ISSUE THREAD

**Issue by froboy** [gitpod-io/gitpod#14531]
### Bug description

Trying to publish a branch to a public GitHub repo you do not have privileges to correctly triggers the "Create Fork" flow, but then forking fails with `Git: remote upstream already exists.` 

Logs report:

```
[info] > git remote rename origin upstream [2ms]
[info] error: remote upstream already exists.
```

I also tried to manually remove the upstream before the process with `git remote remove upstream` but `git remote -v` reports the upstream remains no matter how I try to remove it.

### Steps to reproduce

- Spin up a GitPod instance on a forked repo (such as https://github.com/YCloudYUSA/yusaopeny_docs)
- Create a new branch
- Click "Publish Branch" in the Source Control panel
- Click "Create Fork" when prompted
- Observe the error.

### Expected behavior

If an upstream exists, either the new one should have a new name or the existing upstream should be removed.

### Example repository

https://github.com/YCloudYUSA/yusaopeny_docs

**Comment by froboy** [comment]
Workaround for this is manually creating the fork and adding it via `git remote add...` but that requires extra steps which might be challenging for a novice contributor.

**Comment by axonasif** [comment]
Hi @froboy, can you reproduce this on [VSCode Desktop](https://www.gitpod.io/docs/ides-and-editors/vscode)? (assuming that you're using Gitpod on VSCode Web)

**Comment by froboy** [comment]
@axonasif yes, it looks like the same behavior in VSCode Desktop:
<img width="647" alt="zzztest_—_yusaopeny_docs__SSH__ycloudyusa-yusaopenydoc-zczgvwqn68i_ssh_ws-us75_gitpod_io_" src="https://user-images.githubusercontent.com/238201/200900688-fbcdf71f-2614-46cf-974f-6e28c862492c.png">

Also just for kicks I cloned [the repo](https://github.com/YCloudYUSA/yusaopeny_docs) locally and the upstream isn't there automatically, so it does seem related to something going on in GitPod.

**Comment by axonasif** [comment]
Thank you for sharing your findings 🙏 

Since it's on the IDE team inbox, @andreafalzetti, can you please help to move this issue forward? (maybe escalating it to some other team if IDE doesn't own this)

**Comment by jeanp413** [comment]
@aledbf  is not possible to remove upstream remote `git remote remove upstream`  it gets added automatically again, is this related to `GitInitializer` in content-service?

**Comment by aledbf** [comment]
@jeanp413 that [is done here](https://github.com/gitpod-io/gitpod/blob/aba04a0e803e0aa6468449becef734f058c036d4/components/content-service/pkg/git/git.go#L359-L378) and is really old. I don't have enough context of the reason for that.
ping @csweichel

**Comment by jeanp413** [comment]
ah sorry, it's the GitHub PR extension who's doing it :facepalm:

**Comment by mustard-mh** [comment]
Hi @froboy 👋 

Close as it's a known [issue upstream](https://github.com/microsoft/vscode/blob/1ac5ea41e191611f130e0ae216e4a5dd1966f1f5/extensions/github/src/pushErrorHandler.ts#L70). But once you try to rename or remove remote `upstream`, it will be added again by `Github PullRequest` extension (issue https://github.com/microsoft/vscode-pull-request-github/issues/4209)

cc @akosyakov @jeanp413

**Comment by froboy** [comment]
@mustard-mh thanks for the research! I'm totally ok with "we wont fix it... (but someone else might)". 😄
