### ISSUE TITLE
Don't open a new tab on update

### ISSUE THREAD

**Issue by NatoBoram** [gitpod-io/gitpod#14533]
## Is your feature request related to a problem? Please describe

It is rude to interrupt my workflow by opening a new tab while I'm working...

## Describe the behaviour you'd like

Can you, like, not do that? Please?

## Describe alternatives you've considered

At least have a setting to disable this behaviour...

## Additional context

![Screenshot](https://user-images.githubusercontent.com/10495562/200646788-70058078-4c9c-4883-9d51-6c8a7d5bdd9d.png)

Your issue template doesn't ask which repo this issue applies to, but it's this one: https://github.com/gitpod-io/gitpod-vscode-desktop

**Comment by axonasif** [comment]
Hi @NatoBoram, you will have an option soon.
https://github.com/gitpod-io/gitpod/issues/12704

**Comment by mustard-mh** [comment]
@loujaybee  Another issue for Epic: VSCode flow improvement

**Comment by NatoBoram** [comment]
Bruh, I'm a bit busy right now, I can't read the patch notes at the moment.

![image](https://user-images.githubusercontent.com/10495562/205147409-0be14569-6653-43a8-9d22-bab65a1edff5.png)

**Comment by akosyakov** [comment]
@NatoBoram it should happen only on a new workspace start? Did it just pop up?

**Comment by filiptronicek** [comment]
Hey there @NatoBoram 👋! Is this issue still present in your workflow? If so, we've recently introduced the ability to disable the release notes showing altogether, which may help and make everything less distracting before we get to the ground reason the changelog is showing at inconvenient times. 

You should be able to turn off the behavior if you open your VS Code user settings and search for `Gitpod`. There should be a checkbox for disabling, and if not, please check that you are running the latest version of our VS Code extension. 

![image](https://user-images.githubusercontent.com/29888641/208887587-b3be1ca8-1291-464a-825c-ccd5df156a71.png)

**Comment by NatoBoram** [comment]
Thanks! The setting seem to be `"gitpod.showReleaseNotes": false`

**Comment by akosyakov** [comment]
It still would be good to figure out what is a reason for the original issue. We don't want users using this settings generally, but rather should have less annoying default behaviour.

**Comment by NatoBoram** [comment]
When I'm working, I want to work; not read GitPod's (or anyone else's) release notes.
