### ISSUE TITLE
Gitpod to support a no-cache option

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1453]
Option to rebuild docker images everytime, this can be useful when debugging Gitpod configs, or maybe just a Gitpodify mode that allows one to have docker builds the image and possibly other stuff.

**Comment by Kreyren** [comment]
YES PLEASE! i have to put:

```dockerfile
RUN true "replace" \
  && ...
```

With makefile step : `@ cat build/some.Dockerfile | sed -E "s#(RUN\s{1}true\s{1}\")(replace)(\"\s{1})#\1$$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)\3#gm" > build/some.Dockerfile` to workaround the caching X.X
