### ISSUE TITLE
`gp ports await` subcommand errors with: cannot read /proc/net/tcp6

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#14556]
### Bug description

Noticed this after I opened `workspace-images` repo on Gitpod, a task was using `gp ports await` subcommand.
<img width="1437" alt="Screenshot 2022-11-09 at 6 51 55 PM" src="https://user-images.githubusercontent.com/39482679/200836110-26044e7a-8b88-494b-bd46-45883c637835.png">

```bash
Awaiting port 5000... 2022/11/09 12:50:37 cannot read /proc/net/tcp6: open /proc/net/tcp6: no such file or directory
```

### Steps to reproduce

- Open https://gitpod.new or https://github.com/gitpod-io/workspace-images on Gitpod
- Run `gp ports await 1111`
- See error.

**Comment by kylos101** [comment]
Thank you @aledbf for picking this up!

**Comment by j0nes2k** [comment]
Is a fix for this already deployed? Running into the same issue at the moment...

**Comment by akosyakov** [comment]
It should be deployed today at 12 CET.
