### ISSUE TITLE
Epic: Allow annual credit pre-commitments for usage-based

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#14561]
### Summary

In the context of usage-based, we would like to allow customers to pre-commit to a certain number of usage credits over (e.g.) the next 12 months.

### Context

- [RFC](https://www.notion.so/gitpod/RFC-enable-selling-Public-SaaS-UBP-annual-commits-multi-tenant-a735e7a6fb5a4f32a7296ae545874398) (internal)
- [Slack thread](https://gitpod.slack.com/archives/C027AUU7BC3/p1667993271227099) (internal)

### Acceptance Criteria

This likely implies creating a new BillingStrategy (e.g. "stripe-prepaid") for our CostCenters, which should:
- Grant an arbitrary number of prepaid credits that can be used over the next 12 months (after which they expire)
- Be linked to a unique OrderID that represents the unique pre-commitment
- Each month, create an invoice that:
  - Shows the CostCenter's actually-consumed credits during the month
  - Includes the unique OrderID of the pre-commitment
  - Does not require any payment or credit card (the actual payment happens outside of Stripe)
- Each month, the UsageLimit should be set to the total remaining prepaid credits (such that a customer is allowed to consume their entire yearly pre-commitment if they wish to, but not more)
  - _Optionally, we can make this UsageLimit customizable by the customer (but it shall always remain between 0 and the total remaining prepaid credits)_
  - _Optionally, we may allow the customer to set a higher limit, by providing a credit card, such that any over-consumption gets paid at the regular pay-as-you-go rate_
- Once all the prepaid credits are consumed, or at the end of the pre-commitment period:
  - Any remaining credits expire and are voided
  - A final invoice is created, which must also include the unique OrderID + recap all the previous invoice IDs

**Comment by jldec** [comment]
We can handle annual commits manually for now. Closing this issue.

- Invoicing done manually
- Apply credit grant in the admin dashboard
- Balance shown = grant + usage limit - actual usage (usage limit defaults to zero)
- No monthly invoicing required
- Teams should not receive free credits every month (@svenefftinge can you confirm that this is true)
- Credit expiration can be applied in the admin dashboard at the end if necessary, with a negative grant
