### ISSUE TITLE
Gitpod is stuck on "Pulling docker images"

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1456]
### Describe the bug

![image](https://user-images.githubusercontent.com/11302521/80459484-b9651100-8932-11ea-9829-95b9c704843a.png)

### Steps to reproduce

1. Open gitpod on any repository
2. Notice it being stuck on "Pulling docker images"

**Comment by Kreyren** [comment]
Issue resolved itself while i was making this issue

**Comment by Abearsis** [comment]
Good

**Comment by vfarcic** [comment]
I'm experiencing it right now.

**Comment by jankeromnes** [comment]
Hi @vfarcic, how long has it been like that? (Hint: You can see how long ago your workspace was created by opening a second tab on https://gitpod.io/workspaces/ )

Gitpod should normally be really fast to start up workspaces, except on rare occasions where the cluster needs to scale up and a new node is being added. In that case, the node needs to pull all the Docker images first, and there can be many at the same time, which can explain why occasionally you'll see "Pulling Docker Images" for 2 minutes or so.

Anything longer than that is be considered a cluster incident.

**Comment by vfarcic** [comment]
It deleted the workspace after waiting for 10 minutes and created a new one. It worked the second time.

**Comment by jankeromnes** [comment]
@vfarcic Hmm, 10 minutes is much too long, that would be a cluster incident, except everything appears to be operating normally in our monitoring. Are you based closer to Europe or to North America?

In any case, good that it worked the second time!

**Comment by Kronifer** [comment]
can confirm its stuck, in north america latest chrome version

**Comment by Kronifer** [comment]
This is happening again

**Comment by arusa** [comment]
I'm currently waiting since 10min on "Pulling container image …"
