### ISSUE TITLE
Move gitpod related files to `.gitpod` directory

### ISSUE THREAD

**Issue by mittalyashu** [gitpod-io/gitpod#14585]
To have a clean project tree and have consistency just like other providers, it would be nice to have all Gitpod related configuration files to `.gitpod` directory.

As far I know there are currently these files Gitpod uses:
* `.gitpod.yml`
* `.gitpod.Dockerfile`

**Comment by mittalyashu** [comment]
_I don't see any label added_ 👀

This is a feature request 🙂

**Comment by gtsiolis** [comment]
Hey @mittalyashu! Thanks for opening this, closing it as a duplicate of https://github.com/gitpod-io/gitpod/issues/729.

**Comment by mittalyashu** [comment]
and here I spent 10 minutes searching for an existing issue 🤦‍♂️😂

Thanks George
