### ISSUE TITLE
Error: Couldn't parse context 'https://e5b69df9-4114-4126-9bc5-c3ddfa05c3bd.ws-us02.gitpod.io/'.

### ISSUE THREAD

**Issue by Vadiraj-Kulkarni-14** [gitpod-io/gitpod#1459]

**Comment by jankeromnes** [comment]
Hey @Vadiraj-Kulkarni-14, thanks for reaching out!

Maybe you've found this out already, but:

- `https://e5b69df9-4114-4126-9bc5-c3ddfa05c3bd.ws-us02.gitpod.io/` is a Gitpod workspace URL. There is no need to prefix it with `gitpod.io/#`.

- The `gitpod.io/#` prefix is meant to be used with GitHub URL, e.g. a repository URL, or Pull Request URL, or branch URL, etc. Using it will create a fresh workspace for the context URL you provided.

- To restart old workspaces (it's recommended to always create new fresh workspaces, but if you've left some unsaved work in one of your workspaces, you can restart it at any time), simply go to https://gitpod.io/workspaces/, find the old workspace you want to restart, and click on `Start` next to it.

Hope this helps!
