### ISSUE TITLE
Implement scopes update UI

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#14617]

**Comment by jeanp413** [comment]
@gtsiolis is there a mockup for this?

**Comment by gtsiolis** [comment]
@jeanp413 Is this about editing a token? If yes, scopes are already included there for change, but for now we have permissions that's always enabled. Cc @laushinka @easyCZ

**Comment by easyCZ** [comment]
Indeed, by default, there should be no Permissions selected (checkbox empty). The user should explicitly choose check that box to include all permissions. Similarly,
* If a user selected no perms, they should be able to edit the token and add all scopes
* If they selected all scopes, they should be able to unselect and update the token to have no scopes

**Comment by easyCZ** [comment]
A user can also update the name of the token (which I believe is already implemented)

**Comment by gtsiolis** [comment]
Thanks for clarifying, @easyCZ! Unless I'm missing something, this means that reusing the existing patterns and simply enabling the permissions checkbox could suffice here. Cc @jeanp413
