### ISSUE TITLE
Implement empty PersonalAccessToken page in the dashboard

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#14614]
Behind the feature flag `personalAccessTokensEnabled`

**Comment by gtsiolis** [comment]
The **empty state** contains more than the side menu, right? Shall we reopen this? Cc @laushinka @MichaelAring 

See relevant comment in https://github.com/gitpod-io/gitpod/issues/14280#issuecomment-1323809687

> | 1️⃣ No tokens |
> |-|
> | <img width="1440" alt="Empty" src="https://user-images.githubusercontent.com/120486/203340048-e7d33a49-48b8-4f59-b073-5dd772ae5bfa.png"> |

**Comment by laushinka** [comment]
> The **empty state** contains more than the side menu, right? Shall we reopen this? Cc @laushinka @MichaelAring
> 
Thanks for the designs, George.
This ticket aimed to have an empty page behind a feature toggle, so that anyone who picks up the UI work can just start.
I don't think this is the same as what you show in the design, since it involves showing the list of personal access tokens and a modal to create new ones.

**Comment by gtsiolis** [comment]
Thanks for clarifying, @laushinka!

I brought this up because this issue was listed in the tasks list in https://github.com/gitpod-io/gitpod/issues/14280. 💡 

Let's leave this as is, hopefully the empty state can be tackled along with one of the tasks related to the UI like https://github.com/gitpod-io/gitpod/issues/14615. 🤝

**Comment by laushinka** [comment]
Yess, now that we have designs we can polish the UI tickets. I think the listing and the creation can be worked on separate tickets, so I'll create the UI to only do the listing, as that is the one that's missing. Thanks for the nudge!

**Comment by laushinka** [comment]
[List tokens ticket](https://github.com/gitpod-io/gitpod/issues/14860)
