### ISSUE TITLE
Shellcheck

### ISSUE THREAD

**Issue by vivek-verma202** [gitpod-io/gitpod#1461]
### Describe the bug
This should be a quick one, please pardon me for asking basic questions.
I am not able use shellcheck on Gitpod

![Screenshot (1)](https://user-images.githubusercontent.com/33168572/80602414-15946780-89fd-11ea-9504-6dddb4e608f6.png)

Tried installing shellcheck locally, tried brewing it on the Gitpod but no luck..
Considering that I plan to access Gitpod from multiple machines, I would prefer to have it centrally "installed" instead of pointing executablePath to a local directory.
My .gitpod.yml looks like:
> tasks:
     - init: echo "Replace me with a build script for the project."
    command: echo "Replace me with something that should run on every start, or just
      remove me entirely."
     - init: brew install shellcheck
image: gitpod/workspace-full
> vscode:
>  extensions:
    - timonwong.shellcheck@0.9.0:hsU/Rd39aqPYowTqL+DbXg==
    - medo64.render-crlf@1.5.3:HLx6qIeeDMkxZSYLpmfjnw==
    - Ikuyadeu.r@1.2.8:CY7MPewM7+8dqLNwOs4z+Q==

The workspace I am referring to is:
### vivek-verma202/GWAS_FM - master

Thank-you for your help!

**Comment by Kreyren** [comment]
Seems that shellcheck from homebrew has different path from the one that is hard-codded in shellcheck extension:

![image](https://user-images.githubusercontent.com/11302521/80604915-a2a5e380-8a32-11ea-967a-f4127caf96a1.png)

**Comment by Kreyren** [comment]
Might be worth it to report this to extension developer so that if the path is not set it would use PATH by default.

**Comment by Kreyren** [comment]
Btw.

> The workspace I am referring to is:
> vivek-verma202/GWAS_FM - master

Also next time link alike https://github.com/vivek-verma202/GWAS_FM would be faster and preferable :p

**Comment by Kreyren** [comment]
@vivek-verma202 Also i see that you are trying to improve your shell/bash in which case i can recommend you https://webchat.freenode.net/#bash which is an [IRC](https://en.wikipedia.org/wiki/Internet_Relay_Chat) channel on [freenode network](https://freenode.net/) with professionals/experienced scripters happy to help and educate you about best practices. ^-^

... ~~and greycat~~
