### ISSUE TITLE
I BEING FIRED BECAUSE OF GITPOD

### ISSUE THREAD

**Issue by DhanielB** [gitpod-io/gitpod#14622]
i'm having a lot of problems with gitpod, my time limit is over and i hadn't saved my files, now i'm about to be **fired**, if i don't submit the project by monday **my boss fires me**, **_HOPE SOME SOLUTION AND FAST_**

**Comment by axonasif** [comment]
Hi @DhanielB, could you contact support?
https://www.gitpod.io/contact/support
