### ISSUE TITLE
VSCode desktop stuck on "Installing local extensions on remote" progress bar

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#14626]
### Bug description

Yesterday I updated to latest vscode and also updated my Gitpod extension, since then I saw this happening.

### Steps to reproduce

- Update to latest vscode desktop client and gitpod extension.
- See this being stuck:
<img width="575" alt="Screenshot 2022-11-11 at 9 52 02 PM" src="https://user-images.githubusercontent.com/39482679/201377221-93fdc7a8-b2fc-47a4-9f78-6c3dca6c4801.png">

### Anything else?

VSCode log dump posted on slack.

Earlier report on discord:
- https://discord.com/channels/816244985187008514/1039768668248215634

**Comment by jacobparis** [comment]
I can confirm I have also been facing this for at least a week

**Comment by mrzarquon** [comment]
I just checked and saw that `use local app` somehow got enabled again in my case, disabling it and this behavior stopped.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/57210/203528298-20dff2e8-2285-4eb8-a8b9-a835ec89fa2e.png">

**Comment by jeanp413** [comment]
@mrzarquon `use local app` is deprecated as you can see in the description

BTW this is an upstream bug https://github.com/microsoft/vscode/issues/166196

**Comment by jeanp413** [comment]
Fixes in https://github.com/microsoft/vscode/pull/167723, will be available in next vscode desktop stable release next week or you can try it in vscode desktop insiders
