### ISSUE TITLE
Move "Usage" out of the Settings sidebar and into the user dropdown  

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14636]
The previous solution to #13968 added a link to the sidebar, but this is awkward since other settings pages preserve the sidebar, but the usage page takes up the full width.

This issue proposes moving the `Usage` link into the main user dropdown menu, under `Settings`, making the usage page reachable from all dashboard pages. 

<img width="1100" alt="Screenshot 2022-11-12 at 20 51 48" src="https://user-images.githubusercontent.com/849592/201494776-b08d807e-7411-4b6a-8534-c23944dd1814.png">

The `View Usage` button on the billing page is too obscure, especially when users have not configured any billing.

<img width="1067" alt="Screenshot 2022-11-12 at 21 09 46" src="https://user-images.githubusercontent.com/849592/201494777-0be43596-cdb8-472a-9d84-f6e04223b2cd.png">

#### Usage page

<img width="1101" alt="Screenshot 2022-11-12 at 21 09 23" src="https://user-images.githubusercontent.com/849592/201494864-03cf2f97-ed27-44c4-9875-3bb81826d3e6.png">

Related to #14240, #14506 cc: @gtsiolis, @laushinka

**Comment by gtsiolis** [comment]
YAS! Thanks everyone for making this change! 💯
