### ISSUE TITLE
add code linting based on `pyproject.toml`

### ISSUE THREAD

**Issue by AngryMaciek** [gitpod-io/gitpod#14640]
### Objective

Would be cool to include parsing of `pyproject.toml` in the linting section here:
https://www.gitpod.io/docs/introduction/languages/python#linting

**Comment by axonasif** [comment]
Hi @AngryMaciek, thank you for raising this issue!

Do you have any suggestions or pointers? I am personally not very familiar with Python.

And BTW, that page source code lives [here](https://github.com/gitpod-io/gitpod/issues/9376#issuecomment-1159149038), feel free to contribute if you want!
