### ISSUE TITLE
[git/gitlab] Write permission check fails for private repos

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#1464]
The notification ...

```
The remote repository "${repoFullName}" is not accessible with the current token.
                    Please make sure Gitpod is authorized for the organization this repository belongs to.
```

is always shown when I try to push a private GitLab repo. It doesn't affect the actual git operation.

**Comment by alexandercmonnet** [comment]
I also experience this issue with private gitlab repos hosted on gitlab.com.

**Comment by jankeromnes** [comment]
Thanks for reporting. We're aiming to deploy a fix for this early tomorrow morning.

**Comment by AlexTugarev** [comment]
@alexcmonnet please try again. This should be fixed now

**Comment by kaushikikrityy** [comment]
I am facing the same  issue .
