### ISSUE TITLE
[UBP] handle UBP rollback scenario for paid UBP subscribers

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14652]
Once we start rolling out UBP to all users, if we need to rollback (reverse free users back to non-UBP), teams and users on paid UBP (Stripe) subscriptions should be able to continue working with those plans. We should not cancel their subscriptions.

**Comment by svenefftinge** [comment]
Disabling the feature flag would do this, no?

**Comment by geropl** [comment]
> Disabling the feature flag would do this, no?

Basically yes. We just need to make sure that we gracefully handle the case where people already|upgraded to a Stripe subscription. and not block them from interacting with those.
