### ISSUE TITLE
Investigate downwards trend in webapp-create-workspace-latency

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#14654]
https://pyrra.gitpod.io/objectives?expr={__name__=%22webapp-create-workspace-latency%22}&grouping={}&from=1665998389662&to=1668417589662

![Image](https://user-images.githubusercontent.com/32448529/201622723-e613ef8a-b5a1-47f4-855a-68c7fdfd9c22.png)

**Comment by svenefftinge** [comment]
This seems to correlate with how long `ws-manager/startWorkspace` takes. See also #14061
