### ISSUE TITLE
Gitpod extension not working after download on Macbook Pro

### ISSUE THREAD

**Issue by Archierowe** [gitpod-io/gitpod#1465]

**Comment by Archierowe** [comment]
When I start a new repo in github there is no gitpod button - unsure why - help would be appreciated

**Comment by Kreyren** [comment]
@Archierowe Provide user-agent i.e using http://whatsmyuseragent.org/

**Comment by Kreyren** [comment]
Also check console for anything relevant:
![image](https://user-images.githubusercontent.com/11302521/80764142-93f12680-8b2f-11ea-8015-d084c999af0f.png)

**Comment by Kreyren** [comment]
Also check the code for `gitpod-btn-container` maybe it's in the physical HTML, but not rendered correctly? (you can use Ctrl+F for search within the developer tools inspector)
![image](https://user-images.githubusercontent.com/11302521/80764378-1b3e9a00-8b30-11ea-8e5a-63be36823f55.png)

**Comment by Archierowe** [comment]
Thanks - I'm new to this so I'll have a good look into what you have said.

Really appreciate your message

**Comment by Kreyren** [comment]
@Archierowe any new info?

**Comment by Archierowe** [comment]
Hey there - sorted it - thanks so much for checking in and bothering! Really appreciate your time.

**Comment by Kreyren** [comment]
@Archierowe Care to share the solution?
