### ISSUE TITLE
[JetBrains] Fix SDK updater script to always use newer versions

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#14676]
We have a bug in the script that updates the SDK for JetBrains plugins, see: https://github.com/gitpod-io/gitpod/pull/14658/files

**Comment by felladrin** [comment]
Listing here the two solutions we have for it (in order of preference):
1. Continue using https://www.jetbrains.com/intellij-repository/snapshots/index.json, but sort (descending) by `lastModifiedUnixTimeMs` before picking the first one (considering the filters we already have).
2. Use https://www.jetbrains.com/intellij-repository/snapshots/index.html as it comes already sorted. In this case we use xpath to find the value.

**Comment by andreafalzetti** [comment]
@felladrin I would try first to sort the array, as parsing the HTML is not very friendly 😄

**Comment by felladrin** [comment]
Just found the issue! Will create a PR in a moment.
