### ISSUE TITLE
More transparency on gitpod prebuilds

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#14695]
### Objective

we are using it https://github.com/nodejs/node, But prebuilds seems never work.

Is it because code submmited to frequently or the project is too big?

**Comment by gengjiawen** [comment]
not stable

**Comment by gengjiawen** [comment]
@akosyakov

**Comment by akosyakov** [comment]
@gengjiawen sorry I cannot help here

**Comment by loujaybee** [comment]
@gengjiawen can you provide some more details here? 

1. What is the repo? Can you share a reproduction? 
2. What makes you think the project is "too big"?
3. How long are prebuilds taking for you? 
4. What do you see in the prebuilds log in your projects in Gitpod?

**Comment by gengjiawen** [comment]
> What is the repo? Can you share a reproduction?

Open https://github.com/nodejs/node in gitpod

> What makes you think the project is "too big"?

take really long to build

> How long are prebuilds taking for you?

It seems it never works, I start a new gitpod workspace, it start to build from the scratch.

> What do you see in the prebuilds log in your projects in Gitpod?

It's a org repo. not sure what's the url

**Comment by svenefftinge** [comment]
In the prebuild settings you ca reduce the amount of prebuilds, so that prebuilds are only created every nth commit on the main branch. Workspace pick the last successful prebuild and run an incremental build on top.

Did you try that? does it help?
