### ISSUE TITLE
[JetBrains] Evaluate if we can remove custom logic to detect JDK

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#14697]
As a follow-up of this ticket being deployed: https://youtrack.jetbrains.com/issue/IDEA-296866/Automatically-pick-the-Java-on-PATH-if-module-SDK-isnt-explicitly-set

We need to check if the new logic works in EAP and decide if we can remove the custom logic to detect the JDK

**Comment by felladrin** [comment]
I've checked it today, and unfortunately, we'll need to keep our service that auto-sets the JDK.

On EAP (223.x) IDEs, without our service, when opening a repository that has the `.idea` folder with `misc.xml` defining which JDK to use, it works great: (In this example, the [misc.xml defines it to use JDK 17](https://github.com/Gitpod-Samples/spring-petclinic/blob/e2abf7109a5a828b614717d634243454281ace8d/.idea/misc.xml#L10))
| |
| --- |
| <img width="1320" alt="image" src="https://user-images.githubusercontent.com/418083/202415318-3f71ab60-6724-47a7-89e0-63b454d4195d.png"> |

But the problem appears when there's no `.idea/misc.xml`. In this case, it does detect the JDK, but it doesn't set it automatically:
| | |
| --- | --- |
| <img width="1094" alt="image" src="https://user-images.githubusercontent.com/418083/202415471-f65d361f-ea45-42dd-9306-5ba33ad7475e.png"> |  <img width="1094" alt="image" src="https://user-images.githubusercontent.com/418083/202415502-b2e95eda-ac7a-44cb-8d15-489084735491.png"> |
| <img width="982" alt="image" src="https://user-images.githubusercontent.com/418083/202415521-84990c76-0e5d-43d0-a89f-1fb52cc24653.png"> | <img width="949" alt="image" src="https://user-images.githubusercontent.com/418083/202415884-69a4c1f6-37b6-49c4-9338-8b4e520f55f9.png"> |

With our service, when there's no `.idea/misc.xml`, it automatically sets the JDK to the default one:
| | |
| --- | --- |
| <img width="1118" alt="image" src="https://user-images.githubusercontent.com/418083/202415906-c49830c6-3c30-451c-87f6-4e38008df1b9.png"> | <img width="1118" alt="image" src="https://user-images.githubusercontent.com/418083/202415544-35968db6-b9d9-4646-b4cc-2d2be8b0a4ba.png"> |

For this reason, I vote for keeping the codebase as it is and closing this issue.

**Comment by felladrin** [comment]
I've informed JetBrains about it. [[Internal Discussion](https://gitpod.slack.com/archives/C02BRJLGPGF/p1669023495085699)]
