### ISSUE TITLE
[dev:preview] run deploys (terraform, k8s) in parallel

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#14707]
## Is your feature request related to a problem? Please describe
`leeway run dev:preview` currently runs `terraform applyy` to create/update the preview-VM before it runs `leeway build`.

## Describe the behaviour you'd like
* `terraform apply` should run in parallel to `leeway build`
* installing monitoring-satellite should run in parallel to installing Gitpod.

**Comment by meysholdt** [comment]
Idea: 
* Describe infra, monitoring-satellite, and gitpod-install as leeway-packages, so Leeway will run them in parallel.
* Ensure Leeway will always rebuild the package, so that package can make the decision internally. To always rebuild: e.g. add `version` to `argDeps` or mark package as ephemeral (not sure if this works).
* The package impl decides if a re-deploy needs to happen: It stores a leeway-content-hash in a GCP-bucket or a k8s config map: If the new leeway-content-hash differs from the persisted hash, a redeploy is necessary.

**Comment by mads-hartmann** [comment]
We're going to implement this https://github.com/gitpod-io/leeway/issues/136 in Leeway as the easiest 🛹 to add parallelism to dev:preview.
