### ISSUE TITLE
Error start workspace - user unauthorized

### ISSUE THREAD

**Issue by davidacmoreira** [gitpod-io/gitpod#1472]
### Describe the bug
When I'm starting a workspace, I get this message:
> We are having trouble parsing your context
> Error: Unauthorized

### Steps to reproduce
Start workspace by adding `gitpop.io/#` before repository url.
Example: *gitpod.io/#https://github.com/my_user/my_repository*

### Additional information
In the past, I used gitpod, with a github account that was using the same email that I'm currently using in my new github account. Can this be the problem?

**gitpod settings**

![gitpod_access_control](https://user-images.githubusercontent.com/64630240/80947826-dee99300-8de8-11ea-827c-4f6d95ecbe9a.PNG)

**github settings**

![github_authorized_oauth_apps](https://user-images.githubusercontent.com/64630240/80947831-e0b35680-8de8-11ea-9767-80998290070b.PNG)

**Comment by AlexTugarev** [comment]
Hi @davidacmoreira! I'm sorry to hear about these issues.

> In the past, I used gitpod, with a github account that was using the same email that I'm currently using in my new github account. Can this be the problem?

I'm checking your account links with GitHub identities. Could you please confirm, that you've created a new GitHub account and now using the same email address in there? What did you do with the old account?

**Comment by davidacmoreira** [comment]
Hi.
Yes, I create a new account, and I'm using the same email address.
The old account, I deleted before create the new one.

**Comment by AlexTugarev** [comment]
@davidacmoreira please try again, also maybe you'd need to update permissions on https://gitpod.io/access-control/ one more time. I manually unlinked with your old account for now, but we're going to fix this bug in next release.

**Comment by davidacmoreira** [comment]
It's working. Thank you.

**Comment by AlexTugarev** [comment]
We've deployed a fix for this issue. With the next login to Gitpod (or with any update of granted permissions) the issue should disappear.
