### ISSUE TITLE
[prebuilds] workspace starts with derived config, wrong image, and no prebuild

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#14726]
Happened once for me yesterday, I started a workspace on g/g but ended up with a derived config, wrong workspace image and no prebuild. 

When digging through the [logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-15T14:15:19.341Z;pinnedLogId=2022-11-15T14:15:19.341Z%2Fizentz4oyrqh937p;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22gitpod-191109%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22prod-meta-eu02%22%0Aresource.labels.namespace_name%3D%22default%22%0Alabels.k8s-pod%2Fapp%3D%22gitpod%22%0Alabels.k8s-pod%2Fcomponent%3D%22server%22%0Aresource.labels.pod_name%3D%22server-775cb4684f-5hlp7%22%0Atimestamp%3D%222022-11-15T14:15:19.341Z%22%0AinsertId%3D%22izentz4oyrqh937p%22;timeRange=P2D?project=gitpod-191109), I've seen the following error message, which is related to a recent change in https://github.com/gitpod-io/gitpod/pull/14461

> did not find a finished prebuild in the database despite waiting long enough after msgbus confirmed that the prebuild had finished

There are ~200 entries found in EU server logs. Unsure if this is a cause for the issue, nor is this directly translates to the number of affected workspaces. 

<img width="1188" alt="Screen Shot 2022-11-15 at 15 22 45" src="https://user-images.githubusercontent.com/914497/202121885-cc7c0b48-71d6-4ae0-9e05-8618706781d0.png">

**Comment by geropl** [comment]
We should definitely investigate how this can happen. @AlexTugarev Do you have any IDs, so we can investigate on a specific data set? Or at least a link to the logs?

**Comment by AlexTugarev** [comment]
I've added the [link](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-15T14:15:19.341Z;pinnedLogId=2022-11-15T14:15:19.341Z%2Fizentz4oyrqh937p;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22gitpod-191109%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22prod-meta-eu02%22%0Aresource.labels.namespace_name%3D%22default%22%0Alabels.k8s-pod%2Fapp%3D%22gitpod%22%0Alabels.k8s-pod%2Fcomponent%3D%22server%22%0Aresource.labels.pod_name%3D%22server-775cb4684f-5hlp7%22%0Atimestamp%3D%222022-11-15T14:15:19.341Z%22%0AinsertId%3D%22izentz4oyrqh937p%22;timeRange=P2D?project=gitpod-191109) to the error logged for my workspace where I started the investigation for.

**Comment by nhorton** [comment]
I am getting an error which might be related. When users kick off workspaces with just the gitpod.io prefix to the github.com url, it does not use the prebuilds, and in fact does not run the init before letting the user in, so everything breaks badly.

**Comment by svenefftinge** [comment]
@nhorton How do users start workspaces when the prebuilds do work? Asking because workspaces are always started with the prefix URL, no matter you start them from Gitpod dashboard or GitHub. Are the users members of the team that owns the project?

**Comment by svenefftinge** [comment]
That path for the mentioned warning message is only reached if waiting for finishing prebuild is enabled. I had previously proposed to remove all this logic and never wait for prebuilds that are in progress. WDYT @geropl?

**Comment by nhorton** [comment]
When users start from the prebuild badge or action on GitHub, it often does
not use the prebuild.

That link is always there, it is just reachable from prebuild status page
under the status, including when Ready.

I know at least some of the affected users are team members as this affects
me myself.
