### ISSUE TITLE
[Admin dashboard] Show billing detail for teams  

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14739]
Teams with billing enabled need a "Billing" indicator in the team detail page, similar to the "Plan" indicator for Users.

The values for this should be one of the following:

- `Professional` or `Unleashed` (if team is on a Chargebee team-billing plan)
- `Usage-based` (if team is on a Stripe UBP subscription)

Related to #14367

**Comment by gtsiolis** [comment]
@jldec Shall we also drop the `BillingMode` column?

| User with `chargebee` | User with `usage-based` | 
|-|-|
| <img width="755" alt="Frame 11392" src="https://user-images.githubusercontent.com/120486/202181916-2179e631-2eb9-4cab-8e07-5aa017e04359.png"> | <img width="755" alt="Frame 1139" src="https://user-images.githubusercontent.com/120486/202181983-c981e4d0-1616-4b3d-a6eb-58363c49958d.png"> |

**Comment by jldec** [comment]
> Shall we also drop the BillingMode column?

@gtsiolis - no - the BillingMode is true for UBP-enabled teams (feature flagged), even if they have not yet configured any team-level billing.
