### ISSUE TITLE
Fix broken links in emails we send to users

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#14754]
### Bug description

Links included in emails we're sending to users link to broken pages.

For example, in the email titled _Personalize your workspace – Add your favourite VS Code extension_, we're linking to https://www.gitpod.io/docs/vscode-extensions which no longer exists. 

This could affect more emails we send out.

Cc @Siddhant-K-code @loujaybee because https://github.com/gitpod-io/website/pull/2587
Cc @chrifro @MichaelAring @phimae because of a [relevant task](https://www.notion.so/gitpod/7431896ad7c04b7a8ad45af2632d41c6) (internal)

| Email | Website |
|-|-|
| <img width="594" alt="Screenshot 2022-11-16 at 7 03 04 PM" src="https://user-images.githubusercontent.com/120486/202246006-d0b923b1-5928-4936-b9df-55ccceb87967.png"> | <img width="1440" alt="Screenshot 2022-11-16 at 7 16 36 PM (2)" src="https://user-images.githubusercontent.com/120486/202248728-dfc38e95-0e72-4052-8c29-a201702d65c5.png"> |

### Steps to reproduce

1. Search for an email titled "Personalize your workspace – Add your favourite VS Code extension 🎨"
2. Click on the primary click-to-action (CTA) in that email titled "_Personalize your workspace_".

**Comment by Siddhant-K-code** [comment]
I think we need to redirect the provided^ URL to [`vscode-extensions`](https://www.gitpod.io/docs/references/ides-and-editors/vscode-extensions)? It would be a quick fix, will send out the PR.
