### ISSUE TITLE
[browser extension] Add Gitpod button for new empty repositories

### ISSUE THREAD

**Issue by SalvoBevi** [gitpod-io/gitpod#1476]
I would like to:

Create a new GitHub repository
Click on Gitpod button to start coding
But there is no Gitpod button when my repository is still empty:

![Screen](https://user-images.githubusercontent.com/59666557/81048083-8cc17400-8eb3-11ea-8892-09f6c2a484d1.png)

Goodmorning everyone. I'm having the same problem too.
How can I solve it?

I have already read the mice of #453 but I haven't found the solution.

**Comment by Kreyren** [comment]
See https://github.com/gitpod-io/gitpod/issues/453#issuecomment-623925382

**Comment by jankeromnes** [comment]
Seems like this is broken again for empty repositories:

<img width="1440" alt="Screenshot 2020-05-05 at 18 37 06" src="https://user-images.githubusercontent.com/599268/81091408-7d681800-8eff-11ea-85d7-ae55800fb189.png">

Thanks for reporting! 👍

**Comment by Kreyren** [comment]
Broken on my end too, but i remember having the button there -> Maybe regression?

**Comment by jankeromnes** [comment]
Definitely a regression. 👍

**Comment by Kreyren** [comment]
@Salvo3 Why closed?

**Comment by jankeromnes** [comment]
Re-opening: The button is still missing. Cc @jbicker

**Comment by jankeromnes** [comment]
@Salvo3 Also, as a workaround, you can use the `gitpod.io/#` URL prefix to open the empty repository in Gitpod, like so:

```
gitpod.io/#https://github.com/<username>/<repo>
```

When you visit that with your browser, it will be just as if you've clicked on a Gitpod button.

**Comment by gtsiolis** [comment]
This is no longer reproducible. The button is visible now on empty repositories. Let's close this! /cc @SalvoBevi
