### ISSUE TITLE
Cannot initialize workspace: cannot restore backup: ... Permission denied tar

### ISSUE THREAD

**Issue by kineticsquid** [gitpod-io/gitpod#14774]
### Bug description

I'm attempting to set up a Gitpod workspace for https://github.com/kineticsquid/pass-docker. When the workspace goes idle and I attempt to restart it, I get the following error. I'm able to consistently reproduce this. I don't see this with other workspaces.

<img width="906" alt="Screen Shot 2022-11-17 at 3 04 48 PM" src="https://user-images.githubusercontent.com/681707/202556178-c96baeba-fd21-43b2-b1cc-a1f67eaeedf0.png">

### Steps to reproduce

Use the link in the repo above to create a workspace, let it go idle, then attempt to restart.

### Workspace affected

kineticsquid-passdocker-95fffuzpiz7

### Anything else?

This is my first attempt at setting this up, so I may be missing something obvious.

**Comment by navicstein** [comment]
Having this issue too

**Comment by utam0k** [comment]
@kineticsquid @navicstein Thanks for your report. This issue is duplicated https://github.com/gitpod-io/gitpod/issues/11183. Please keep watching this one :pray:
