### ISSUE TITLE
Cannot start a workspace because no workspace clusters are available

### ISSUE THREAD

**Issue by WesleyMConner** [gitpod-io/gitpod#14788]
### Bug description

No luck starting https://gitpod.io/start/#opigencetech-flexsearch-atsly76gvmu this morning. Additionally, the workspaces page suggests 'no changes', but this doesn't seem correct.

### Steps to reproduce

Attempt to launch workspace from workspaces page.

### Workspace affected

https://gitpod.io/start/#opigencetech-flexsearch-atsly76gvmu

### Expected behavior

Normally starts without issue.

### Example repository

n/a

**Comment by WesleyMConner** [comment]
Same issue for https://gitpod.io/start/#opigencetech-utils-yzkn1f590hh

**Comment by axonasif** [comment]
Hi all, please subscribe to https://www.gitpodstatus.com/incidents/9q9yk3wjj5rb
