### ISSUE TITLE
Request ideReady and contentReady twice in supervisor-frontend

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#14782]
### Bug description

Request ideReady and contentReady twice in supervisor-frontend

![image (10)](https://user-images.githubusercontent.com/20944364/202674689-53fc5c75-397f-4fdc-9bbd-b302a25ead39.png)

### Steps to reproduce

- Start a workspace in Gitpod
- Open DevTool / Network tab
- Check request number

**Comment by akosyakov** [comment]
It can happen because of timeout for instance: https://github.com/gitpod-io/gitpod/blob/63245668cf70f1122f8405735d0eb7f9da039d74/components/supervisor/frontend/src/ide/supervisor-service-client.ts#LL62C20-L62C20 and would be the right thing to do

**Comment by akosyakov** [comment]
Did you check debug log for this line: https://github.com/gitpod-io/gitpod/blob/63245668cf70f1122f8405735d0eb7f9da039d74/components/supervisor/frontend/src/ide/supervisor-service-client.ts#L60?

**Comment by mustard-mh** [comment]
They are two succeed requests (same kind) with both `ok=true`
