### ISSUE TITLE
extension: spmeesseman.vscode-taskexplorer unable to start tasks

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#1478]
### Describe the bug

Reported in https://github.com/swapagarwal/swag-for-dev/pull/573#issuecomment-623658218

[spmeesseman.vscode-taskexplorer](https://marketplace.visualstudio.com/items?itemName=spmeesseman.vscode-taskexplorer#internally-provided-tasks-vs-vscode-provided-tasks) unable to start tasks i.e pressing `F1` and then toggling task view explorer makes the task view appear on the left but there are no  npm tasks showing up.

![image](https://user-images.githubusercontent.com/46004116/81061901-987e5c00-8eee-11ea-8f7b-8e611136c650.png)

### Steps to reproduce

Try opening a workspace via the following link

https://gitpod.io/#https://github.com/nisarhassan12/swag-for-dev/tree/ts-lint

and try starting some task.

**Comment by akosyakov** [comment]
You can switch to VS Code now: https://www.gitpod.io/docs/feature-preview/#default-ide It is going to become default rather soon.
