### ISSUE TITLE
Using JetBrains Gateway 2022.3 RC and Rider doesn't load project files

### ISSUE THREAD

**Issue by laurentkempe** [gitpod-io/gitpod#14799]
### Bug description

Starting a new Gitpod workspace from JetBrains Gateway with Rider, starts the workspace on Gitpod, then JetBrains Client is started with my .NET Solution loaded but I cannot see something else than the solution file (.sln) and the project file (.csproj) in Solution view which displays 1 project, 1 unloaded

![image](https://user-images.githubusercontent.com/272612/202841476-c1a9e904-8ef4-4868-8f2b-e3bf9200e8cb.png)

Turining to File System view I see my files

![image](https://user-images.githubusercontent.com/272612/202841861-77cc12d6-29d9-4f91-8f6b-5c1750ebca35.png)

Something to note is that dotnet is not installed

![image](https://user-images.githubusercontent.com/272612/202841904-644a40ea-3127-4393-a0c1-eea04eeb848e.png)

# Versions

JetBrains Gateway 2022.3 RC
Build #GW-223.7571.70, built on November 17, 2022
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 24
Non-Bundled Plugins:
    com.github.codespaces.jetbrains.gateway (0.3.0.921)
    io.gitpod.jetbrains.gateway (0.0.1-main.5684-latest)

JetBrains Client 2022.3 Beta
Build #JBC-223.7571.24, built on November 12, 2022
Licensed to JetBrains Rider EAP user: Laurent Kempe
Expiration date: December 12, 2022
Runtime version: 17.0.5+1-b653.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
Controller in Remote Development (RD)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 24
Registry:
    rdclient.backend.actionHandlers=false

Non-Bundled Plugins:
    com.intellij.plugins.resharperkeymap (223.7571.10)
    com.intellij.plugins.visualstudiokeymap (223.7571.73)

### Steps to reproduce

1. Start JetBrains Gateway 2022.3 RC with Gitpod Gateway 0.0.1-main.5684-latest installed
2. Select Rider in the dropdown
3. Use https://github.com/laurentkempe/ChiseledDocker or https://github.com/laurentkempe/AsyncVoidCommandTesting repository
4. Click New Workspace
5. Browser opens creating Gitpod image "This workspace is configured with the latest release (unstable) for the editor. [Change Preferences](https://gitpod.io/preferences)"
6.  When workspace is ready JetBrains Client 2022.3 Beta opens with solution file and project file

### Workspace affected

laurentkemp-chiseleddoc-md8zzd3f44e

### Expected behavior

I can work on my .NET solution

### Example repository

https://gitpod.io#snapshot/a747d5f7-5699-4eed-b2e3-95e1a9e95f27

**Comment by andreafalzetti** [comment]
Thanks for trying our and reporting the issue 🙌 

I suspect that you are using the default Gitpod workspace image which doesn't come with `dotnet` installed. The easiest way to install dotnet in Gitpod is to use the dedicated workspace image: `workspace-dotnet`. This can be configured in `.gitpod.yml` and `.gitpod.Dockerfile`, example:


In `.gitpod.yml`:
```
image:
  file: .gitpod.Dockerfile
```

In `.gitpod.Dockerfile`:
```
FROM gitpod/workspace-dotnet:latest
```

Full example: https://github.com/Gitpod-Samples/template-dotnet-core-cli-csharp

@laurentkempe we look forward to hear if this helped 🙏

**Comment by laurentkempe** [comment]
In the meantime, I installed the .NET SDK 7.0 by hand and can compile and run the project from the CLI. But I still cannot load the project from JetBrains Client. 

I will try your proposal @andreafalzetti and let you asap

**Comment by laurentkempe** [comment]
> Disclaimer: Due to a current limitation in Rider, the dialog to choose the project does not show in remote dev environments, so to launch Rider we need to find the first `.sls` or `.csproj` in the repository. Opening a repo with multiple `.sls` file is currently not fully supported.

I guess you mean `.sln`, my repos as only one [ChiseledDocker.sln](https://github.com/laurentkempe/ChiseledDocker/blob/master/ChiseledDocker.sln)

**Comment by laurentkempe** [comment]
Thanks a lot @andreafalzetti it works now 🎉🎉🎉🎉

Having `.gitpod.yml` and `.gitpod.Dockerfile` fixed the problem at the end.
https://github.com/laurentkempe/ChiseledDocker/blob/master/.gitpod.yml
https://github.com/laurentkempe/ChiseledDocker/blob/master/.gitpod.Dockerfile

![AwesomeGrandmaGIF](https://user-images.githubusercontent.com/272612/202843390-aa85a021-c6aa-4cf7-acb9-499efdc662a9.gif)
