### ISSUE TITLE
[terminal] Duplicated terminals inside one widget

### ISSUE THREAD

**Issue by marechal-p** [gitpod-io/gitpod#148]
**Describe the bug**
More often than not, two terminals are opened inside one terminal widget...

![gitpod-double-terminal](https://user-images.githubusercontent.com/14182238/48720268-5c1d4a00-ebed-11e8-87e3-fa62e58de3cc.gif)

**To Reproduce**
Open terminal widget with `ctrl+backtick` (just once).

**Expected behavior**
Only one terminal per widget.

**Comment by svenefftinge** [comment]
Hey Paul, thanks for reporting it.
I cannot reproduce it on mac as the shortcut doesn't seam to work on OS X.
