### ISSUE TITLE
SelectWorkspaceClass in ProjectSettings should not depend on PVC feature flag 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14800]
The new workspace class selector is not visible in any project settings on gitpod.io  
It appears that the selector depends on the PVC feature flag.

https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/projects/ProjectSettings.tsx#L162-L164

This feature has been requested in connection with this [customer support issue](https://gitpod.slack.com/archives/C03372UP877/p1668878163941979) (internal)

cc: @svenefftinge @atduarte

**Comment by jldec** [comment]
Related to #14535

**Comment by kylos101** [comment]
@jldec I removed from the Team Workspace inbox. Let us know if anything is needed in a new issue?
