### ISSUE TITLE
Gitpod terminal becomes unresponsive 

### ISSUE THREAD

**Issue by Garvit-k** [gitpod-io/gitpod#14807]
### Bug description

The terminal and vs code features becomes unresponsive and only way to solve it is to refresh the whole page.
The internet connection is stable and at 100 Mb/s throughout.
Using: Firefox Developer Edition 108.0b3 (64-bit)

### Steps to reproduce

After running 1 command in terminal it becomes unresponsive.

### Workspace affected

stellar-sorobanexamples-gb8hrfm5pa5

### Expected behavior

Terminal should be responsive.

### Example repository

https://gitpod.io/#snapshot/f20af6dc-8270-4ff4-a121-0c2625755b28

**Comment by axonasif** [comment]
Hi @Garvit-k, can you reproduce this on a different browser?

Moreover, could you try in [Firefox troubleshoot mode?](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode#w_troubleshoot-mode-window)?

And if could could provide your vscode logs:
- https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop

**Comment by RCheesley** [comment]
I am experiencing the same issue with Chrome repeatedly - commands are not being typed, and it becomes completely unresponsive.

**Comment by andreafalzetti** [comment]
@RCheesley any public repo or steps for us to try reproduce?

**Comment by RCheesley** [comment]
I emailed logs to the troubleshooting address as requested. Several PRs on mautic/mautic I have been testing today and yesterday are having this issue.
