### ISSUE TITLE
www.nekisltd.net

### ISSUE THREAD

**Issue by jgbokoua** [gitpod-io/gitpod#1480]
<!DOCTYPE html>
<html>
<head>
<style>
div {
background-color: lightblue;
 padding: 70px;
 border: 2px solid lightblue;
}
</style>
</head>
<body>
<h1><img src="file:///C:/Users/HP/Desktop/NEKISLTD/logo.png"></h1>
<div> <h1> NEKIS LIMITED </h1>
<ul>
<li><a href="">Home</a></li>
<li><a href="">About us</a></li>
<li><a href="">Services</a></li>
<li><a href="">Produit</a></li>
<li><a href="">Contact</a></li>
<li><a href="">Location</a></li>
</ul>
</div>
</body>
</html>
</style>

<!DOCTYPE html>
<html>
<head>;
</head>
<body>
</style>
</head>
<body>
<div id="header">
<div id="nav">
<img src="https://brain-images-ssl.cdn.dixons.com/3/5/10196053/u_10196053.jpg"> 
<p>Product features Social: Basic computing on the go</p>
<p>Windows 10 AMD A6-9225 Processor</p>
<p>RAM: 4 GB / Storage: 1 TB HDD Full HD screen</p>
<p>Similar models in this range</p>
</div>
</diV>;
</div>
<div id="content">
<div id="feature">
<p>FEATURE</p>
<p>Just browsing? Laptops in our Social range are perfect for getting online, streaming and checking </p>
<p>in on social media. All the essentials. Responsive and reliable.Great for updating Facebook, managing emails,</p> 
<p>and doing coursework, the HP 15-db0500sa 15.6"AMD A6 Laptop gets you online with ease. Designed for</p> 
<p>streaming, surfing, and playing,the AMD A6 processor powers through everyday tasks. Sleek and portable</p>
<p>The HP 15 Laptop is slim enough to fit neatly in a bag, and looks great whether it's on a work desk</p> 
<p>or balanced on your knees. It's also got ample storage for all of your music and movies, and the HD camera</p> 
<p>lets you make video calls wherever you are. Stay connected and entertained The battery lasts for a whopping 
<p>10 hours, so you can take the HP  Notebook 15 with you all day and not worry about finding a plug socket.</p> 
<p>And when you do need to recharge - you'll go from 0-50% battery in just 45 minutes. Microsoft </p>
<p>Office & internet security If you use Word or PowerPoint all the time at work or school, you'll probably</p> 
<p>want it on your laptop at home. Click on the Bundles tab above for a great deal on Microsoft Office. Want to</p>
<p>protect yourself against viruses? We've got you covered with deals on internet security too.</p>
<div class="article column1">
</div>;
</div>
</div>

<p> <!DOCTYPE html>
<html>
<head>
<title>Image and text</title>
<style>    
</style>
</head>
<body>
<div class="wrapper">
<th><img src=" http://cdn.ttgtmedia.com/digitalguide/images/Misc/pms_dlc.gif"></th>	
</div>
</body>
</html>
</p>
</div>;

<div class="article column2">
<p><!DOCTYPE html>
<html>
<head>
<title>GALLERY</title>
</head>
<body>
<table border="1"cellpadding="25"
cellspacing="25">
</div>
</div>
<tr>
<th colspan=1><h3>THE NEKIS LIMITED GALLERY</h3> </th>
</tr>
<th>LAPTOPS HP </th>
<th><img src="https://www.bing.com/th?id=OPE.epnKcTcRFmT0tA300C300&pid=21.1&w=120&h=120&qlt=100"></th>
<th><img src="https://www.bing.com/th?id=OPE.epnKcTcRFmT0tA300C300&pid=21.1&w=120&h=120&qlt=100"></th>
<th><img src="https://www.bing.com/th?id=OPE.epnKcTcRFmT0tA300C300&pid=21.1&w=120&h=120&qlt=100"></th>
<th><img src="https://www.bing.com/th?id=OPE.epnKcTcRFmT0tA300C300&pid=21.1&w=120&h=120&qlt=100"></th>
</tr>
<tr>
<td>LAPTOPS DELL </td>
<td><img src="https://www.bing.com/th?id=OPE.lpQtOOHnBJuq7g300C300&pid=21.1&w=120&h=120&qlt=100"></td>
<td><img src="https://www.bing.com/th?id=OPE.lpQtOOHnBJuq7g300C300&pid=21.1&w=120&h=120&qlt=100"></td>
<td><img src="https://www.bing.com/th?id=OPE.lpQtOOHnBJuq7g300C300&pid=21.1&w=120&h=120&qlt=100"></td>
<td><img src="https://www.bing.com/th?id=OPE.lpQtOOHnBJuq7g300C300&pid=21.1&w=120&h=120&qlt=100"></td>
</tr>
<th>LAPTOPS ACER </th>
<th><img src="https://www.bing.com/th?id=OPE.epnKcTcRFmT0tA300C300&pid=21.1&w=120&h=120&qlt=100"></th>
<th><img src="https://www.bing.com/th?id=OPE.epnKcTcRFmT0tA300C300&pid=21.1&w=120&h=120&qlt=100"></th>
<th><img src="https://www.bing.com/th?id=OPE.epnKcTcRFmT0tA300C300&pid=21.1&w=120&h=120&qlt=100"></th>
<th><img src="https://www.bing.com/th?id=OPE.epnKcTcRFmT0tA300C300&pid=21.1&w=120&h=120&qlt=100"></th>
</tr>
<tr>
<td>LAPTOPS COMPAQ</td>
<td><img src="https://www.bing.com/th?id=OPE.lpQtOOHnBJuq7g300C300&pid=21.1&w=120&h=120&qlt=100"></td>
<td><img src="https://www.bing.com/th?id=OPE.lpQtOOHnBJuq7g300C300&pid=21.1&w=120&h=120&qlt=100"></td>
<td><img src="https://www.bing.com/th?id=OPE.lpQtOOHnBJuq7g300C300&pid=21.1&w=120&h=120&qlt=100"></td>
<td><img src="https://www.bing.com/th?id=OPE.lpQtOOHnBJuq7g300C300&pid=21.1&w=120&h=120&qlt=100"></td>
</tr>
</table>
</body>
</html></p>
</div>;

<div class=">
<!DOCTYPE html>
<html>
<head>
<title>Form semantic elements</title>
</head>
<body>    
<form action="https://formdump.nekisltd.net/" method="post">
<fieldset>
<legend>Personal details</legend>
<label for="name">Your name:</label>
<input type="text" name="name" id="name">
<label for="age">Your age:</label>
<input type="number" name="age" id="age">
</fieldset>
<fieldset>
<legend>Education</legend>
<label for="institution">Institution:</label> 
<input type="text" name="institution" id="institution">
<label for="degree">Degree:</label> 
<input type="text"  name="degree" id="degree">
<label for="class">Class:</label>
<input type="text" name="class" id="class">
</fieldset>
<input type="submit">
</form>
</body>
</html>
<p>column trhree </p>
</div>
</div>;

<div id="footer">
<h3> NEKISLTD 2020  </h3>
<p>Operating system The first decision you need to make when choosing a desktop is which operating system to choose and at present you have two main choices an Apple device running the Macintosh operating system or a</p>
<p>device that runs Microsoft Windows. Which you choose really depends on your own personal preferences, if you’re used to Apple devices or Windows devices then you will need to go through a learning curve to switch, however</p>
<p>the time taken to get up and running in either is negligible. Most desktops on the market run the Windows operating system and give you access to millions of applications written for the platform. There are fewer</p>
<p>applications written for Apple devices, however that doesn’t mean you can’t run your favourite Windows software</p>
<p> www.nekisltd.net  </p>
</footer>
</div>
</body>
</html>

**Comment by Kreyren** [comment]
@jgbokoua What the hug!
