### ISSUE TITLE
[UBP] Configure higher usage limit on "Gitpod for Open Source" plan users

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14819]
[Gitpod for Open Source](https://www.gitpod.io/for/opensource) plan users will receive a higher credit allowance under UBP. This higher usage limit setting should persist indefinitely (not expire at the end of the month)

The Current plan should be labeled “Open Source”. 

Besides the difference in plan name and higher credit limit, the Billing page should behave just like other Free-tier users.

See [RFC](https://www.notion.so/gitpod/RFC-Professional-OSS-Plan-for-UBP-d7af057f0b6042b3af92c12e7cb00179) (internal)

**nice to have**  

Showing a one time notification in the dashboard, announcing the switch, and the higher limit would help to improve awareness of the changes.

**Comment by jldec** [comment]
@geropl, @svenefftinge could you confirm that this approach makes sense.

**Comment by svenefftinge** [comment]
The SQL query is in #14950 and should be manually applied.

**Comment by jldec** [comment]
If we're going to it manually, I think it would be nice to do it 2 steps

1. identify cost centers to be adjusted (or not) to filter out users who already have a higher usage limit
2. apply the insert, respecting the output of step 1

This makes the 2nd part a little bit safer, using step 1 as a sanity check, and allows the process to be run multiple times without creating duplicates. It also avoids overwriting manually-updated higher usage limits.

**Comment by svenefftinge** [comment]
You could verify the select part once more (I did that already). And when it is good, we can apply it.

**Comment by jldec** [comment]
This was done using a manual migration today.
See followup issue #15095
