### ISSUE TITLE
Opening port does not work

### ISSUE THREAD

**Issue by MichaelVoelkel** [gitpod-io/gitpod#14818]
### Objective

Hi,

I want to use VNC, however, I cannot use the container that Gitpod provides because I have my own custom image.

Now, that works in essence fine. I have VNC running on 5900 and my local netcat also tells me that this is working fine.

However, the exposed port seems to be seen ONLY as https... this makes no sense, I want to have the port open but not via https clearly, the protocol IS VNC.

How can I accomplish this? It seems, it's not possible. But then again, you have some guides that tell that VNC works (I don't see how because they would need to tunnel via https?!)

**Comment by axonasif** [comment]
Hi @MichaelVoelkel, you can find some info here:
- https://github.com/gitpod-io/workspace-images/tree/axonasif/add_docs/chunks/tool-vnc#workspace-full-vnc

**Comment by axonasif** [comment]
And about http ports on the web version, https://github.com/gitpod-io/gitpod/issues/459 is relevant.

**Comment by MichaelVoelkel** [comment]
Ok, thanks, got it!
So I will have locally something that tunnels VNC via https and expose that. Not perfect, but ok

**Comment by braughtg** [comment]
> Ok, thanks, got it! So I will have locally something that tunnels VNC via https and expose that. Not perfect, but ok

Were you able to get this to work? If so, any tips or pointers?  I'm struggling with the same issue now.  Thanks!

**Comment by axonasif** [comment]
Hi @braughtg, a very simple way is to just open your workspace in VSCode Desktop and then connect to `localhost:5900` using a VNC client.

Relevant links:
- https://www.gitpod.io/docs/configure/workspaces/ports#port-forwarding
- https://github.com/gitpod-io/workspace-images/tree/axonasif/add_docs/chunks/tool-vnc#workspace-full-vnc

Although, may I ask, why not just use the noVNC web client?

**Comment by braughtg** [comment]
> Although, may I ask, why not just use the noVNC web client?

We are connecting to an full GUI desktop environment and the copy/paste between the host machine and the noVNC client in the browser requires the use of the "clipboard" tool in the noVNC client, which is inconvenient.  Using a full VNC client makes the copy/paste behavior between the host and the remote machines seamless.

I have seen that there are issues and a PR open in noVNC to address this issue, but they have been open and unresolved for quite some time:
- https://github.com/novnc/noVNC/pull/1347

I have developed a spike for another project that shows how this can work.  In case it is helpful to anyone else, it is here:
-  https://github.com/braughtg/gitpodVNC
