### ISSUE TITLE
[project settings] Allow setting workspace class for prebuilds independently

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#14811]
## Is your feature request related to a problem? Please describe
For prebuilds some teams might want to use a different workspace class than for the actual workspaces.

## Describe the behaviour you'd like
We should allow settings the workspace class for prebuilds. Workspaces started from prebuilds unfortunately can only use larger classes. So a setting where prebuilds run in a larger workspace class than the actual workspaces would be invalid.

**Comment by gtsiolis** [comment]
Adding below the design specs for adding this feature in project settings, following a recent discussion with @svenefftinge.

Changes include:
1. Adding the workspace class selector under the prebuilds section.
2. Adding a section subtitle for the prebuilds section.
3. Rephrasing the subtitle in workspaces section to match the new subtitle of the prebuilds section.

| BEFORE | AFTER |
|-|-|
| ![project-settings-before](https://user-images.githubusercontent.com/120486/203779952-47b41021-eea8-489d-a9cb-5f354277ce69.png) | ![project-settings-after](https://user-images.githubusercontent.com/120486/203779979-c9cccbcc-87c1-4e68-8fd0-c6287987fda8.png) |
