### ISSUE TITLE
The port range suppression doesn't work

### ISSUE THREAD

**Issue by trinhpham** [gitpod-io/gitpod#1484]
### Describe the bug
I followed the guide of @jankeromnes at [issue #245](https://github.com/gitpod-io/gitpod/issues/245#issuecomment-490120252) to suppress some unnecessary ports be annoyed since the app open & close ports at runtime.
But it seems not work

### Steps to reproduce
Start gitpod with my repo at https://github.com/trinhpham/test-with-gitpod
There're notifications that ask me for the ports in suppression range
![image](https://user-images.githubusercontent.com/9128061/81253026-aa2c4480-9051-11ea-8a72-565fc8ab6757.png)

### Expected behavior
Only notification to ask for port 6080

### Example repository
https://github.com/trinhpham/test-with-gitpod

**Comment by gtsiolis** [comment]
Hey @chuck-confluent! Since a lot has changed since last year (May 2020) could you open a new bug report issue about this?
> https://github.com/gitpod-io/gitpod/issues/new?assignees=&labels=bug&template=bug_report.yml
