### ISSUE TITLE
Nothing showing in terminal in Safari

### ISSUE THREAD

**Issue by vasucp1207** [gitpod-io/gitpod#14859]
### Bug description

I open a workspace in Safari and notice that gitpod terminal not showing anything.

### Steps to reproduce

I check whether the terminal is working or not by typing **git checkout main**, and surprisingly the command works in the terminal but the terminal is totally empty.

<img width="1414" alt="Screenshot 2022-11-22 at 8 43 48 PM" src="https://user-images.githubusercontent.com/85363195/203351659-4fef090a-964e-468c-9d48-80192beac6d5.png">

<img width="1418" alt="Screenshot 2022-11-22 at 8 43 35 PM" src="https://user-images.githubusercontent.com/85363195/203351692-6fb79085-f1e4-4161-8661-6fc3016f6b3d.png">

**Comment by axonasif** [comment]
Hi @vasucp1207, does this help?
- https://github.com/gitpod-io/gitpod/issues/14459#issuecomment-1308640577

**Comment by felladrin** [comment]
Possibly related:
- https://github.com/gitpod-io/gitpod/issues/14833

**Comment by mustard-mh** [comment]
Hey @vasucp1207  Could you try with this setting in VSCode `"terminal.integrated.gpuAcceleration": "off"` ? 🙏

**Comment by jeanp413** [comment]
Closing this for now, feel free to reopen if `"terminal.integrated.gpuAcceleration": "off"` doesn't work
