### ISSUE TITLE
Can't grant GitPod any rights to access GitHub

### ISSUE THREAD

**Issue by pranaya2005** [gitpod-io/gitpod#1486]
### Describe the bug

I recently signed up for GitPod using the GitHub's Student Developer Pack, in which I got a free plan worth $9 for 6 months. I connected both my GitHub and GitLab accounts to the same GitPod account. But when I wanted to start work on one of my GitHub projects on GitPod, I saw that GitPod couldn't access the repository saying "Unauthorised", I went to Access Control section and tried to check all the boxes for GitHub and clicking on Update but everytime it was reset to only the first checkbox enabled. I tried the same with GitLab and it worked, but still I can't grant full access to GitPod in GitHub.

### Steps to reproduce

Go to Access control, check all boxes for GitHub, click on "Update"

### Expected behavior

All the boxes should have been checked after clicking "Update" and GitPod should have been granted access to my GitHub.

### Additional information

N/A

### Example repository

N/A

**Comment by AlexTugarev** [comment]
@pranaya2005 thanks for reporting! I'm looking into your account.

**Comment by AlexTugarev** [comment]
@pranaya2005 please try again.

This is the same issue as https://github.com/gitpod-io/gitpod/issues/1472 and will be fixed in the next deployment.

**Comment by pranaya2005** [comment]
> @pranaya2005 please try again.
> 
> This is the same issue as #1472 and will be fixed in the next deployment.

Thank you so much sir, I appreciate your help 😄
