### ISSUE TITLE
Continuation of #10108

### ISSUE THREAD

**Issue by michielbdejong** [gitpod-io/gitpod#14878]
### Bug description

Continuation of https://github.com/gitpod-io/gitpod/issues/10108#issuecomment-1321863968
It seems that it was fixed in May but it seems to be happening again.

### Steps to reproduce

See https://github.com/gitpod-io/gitpod/issues/10108#issuecomment-1321863968

### Workspace affected

michielbdej-federatedti-uagmoe54t0u

**Comment by michielbdejong** [comment]
<img width="1215" alt="Screenshot 2022-11-23 at 09 36 56" src="https://user-images.githubusercontent.com/408412/203502425-45e7c7ef-96bd-4f44-ab87-c716bfb286c5.png">

**Comment by axonasif** [comment]
Duplicate of https://github.com/gitpod-io/gitpod/issues/11183
