### ISSUE TITLE
Is it possible to preconfigure theia settings

### ISSUE THREAD

**Issue by yiendos** [gitpod-io/gitpod#1487]
Hi there, 

You docs make mention of pre-configuring your editor workspace: 
https://www.gitpod.io/docs/config-editor/

And a github issue refers to it being possible to supply these configurations via the .gitpod.yml file: 
https://github.com/gitpod-io/gitpod/issues/1279

But I'm not having much luck with this. I've attempted to copy my local `settings.json` file to `/home/gitpod/.theia/settings.json` 

* via the Dockerfile  
* a`build` command in my gitpod.yml. 

Copying from the build command, enables the file to be correctly located, but the workspace doesn't pick up these configuration automatically. 

```
{
   "folders": [
      {
         "path": "file:///workspace/joomlatools-pages"
      },
      {
         "path": "file:///var/www/preview/joomlatools-pages"
      }
   ],
   "settings": {
          "explorer.autoReveal": true
      }
}
```

Any help or suggestions would be gratefully received.

**Comment by akosyakov** [comment]
User settings are not stored under `/home/gitpod/.theia/settings.json`, but in the Gitpod database, so they can be shared between workspaces. Please use preferences UI to edit User settings.

**Comment by trinhpham** [comment]
Why's not store the settings at project level (file `.vscode/settings.json`), @yiendos?
It seems ok in my [test repo](https://github.com/trinhpham/test-with-gitpod).

**Comment by Kreyren** [comment]
> Why's not store the settings at project level (file .vscode/settings.json), @yiendos? @trinhpham 

Because theia is not vscode :p So if there is a property that is not supported or handled differently by theia it will cause conflicts.

**Comment by trinhpham** [comment]
Therefore, why's not a file at project level, such as `.theia/settings.json`?

**Comment by Kreyren** [comment]
@trinhpham Reading through theia's code i don't see it having a definition for project level file, but to me that seems irelevant to this issue.

**Comment by jankeromnes** [comment]
@Kreyren Theia supports both `.theia/` and `.vscode/` settings. Committing such a directory in one of your repositories allows pre-configuring Theia settings for all Gitpod workspaces created for that repository.

The other option that @akosyakov mentioned is to pre-configure Theia for _all_ your personal Gitpod workspaces, regardless of the repository (i.e. user-level settings). These cannot be configured via `.theia/` or `.vscode/` directory, but can be edited in the IDE > File > Settings > Open Preferences > "User" tab (and are then saved in Gitpod's database).

**Comment by Kreyren** [comment]
> @Kreyren Theia supports both .theia/ and .vscode/ settings. Committing such a directory in one of your repositories allows pre-configuring Theia settings for all Gitpod workspaces created for that repository. @jankeromnes

My bad then!

**Comment by diegoulloao** [comment]
> @Kreyren Theia supports both `.theia/` and `.vscode/` settings. Committing such a directory in one of your repositories allows pre-configuring Theia settings for all Gitpod workspaces created for that repository.
> 
> The other option that @akosyakov mentioned is to pre-configure Theia for _all_ your personal Gitpod workspaces, regardless of the repository (i.e. user-level settings). These cannot be configured via `.theia/` or `.vscode/` directory, but can be edited in the IDE > File > Settings > Open Preferences > "User" tab (and are then saved in Gitpod's database).

This doesn't work

**Comment by akosyakov** [comment]
@diegoulloao Could you elaborate what did you try to configure, what was expectation and what did not work? thank you

**Comment by diegoulloao** [comment]
I have this in my `.gitmod.yml`:

```
image: gitpod/workspace-mysql

vscode:
  extensions:
    - dracula-theme.theme-dracula@2.22.3:c2qxutk2xT/UW8L9+9bW2g==
    - PKief.material-icon-theme@4.4.0:rUeW9VprKCFBXYTvg+AimA==
```

And this in my `.theia/settings.json`:
```
{
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "Dracula"
}
```

*Expected:* load the editor with Dracula theme and Material Icons.
*What's happening:* editor loads with default settings.

I already tried to rename .vscode instead of .theia

**Comment by akosyakov** [comment]
I cannot reproduce. Could you share the repo please?

Also usually you will need to install such extensions as user extensions and add settings to User settings (File > Settings > Open Preferences > "User" tab) to preserve them across different workspaces.

**Comment by diegoulloao** [comment]
@akosyakov thanks for your time.

I'm working in this: https://github.com/bananasplit-js/bananasplit-js/tree/main/gitpod/template
Branch `main/gitpod/template`

I expect the editor automatically load the color and icon themes.

Files in my repo:
- `.gitpod.yml`
- `.theia/settings.json`

**Comment by akosyakov** [comment]
@diegoulloao I was able to reproduce this issue for icon themes, but not for colors. Anyway I wanted to point you that we support VS Code now: https://www.gitpod.io/docs/feature-preview/#default-ide And there it should work with project settings, given that you rename `.theia` to `.vscode`. It is still in preview mode and there are some missing features, in particularly preserving user settings between workspaces and restarts. It would be resolved in Jan.

**Comment by diegoulloao** [comment]
Thanks for your answer.  Color theme should be work fine? Only for this particular workspace?
