### ISSUE TITLE
Source control: No repository found

### ISSUE THREAD

**Issue by artalar** [gitpod-io/gitpod#1488]
### Describe the bug

`Source control: No repository found` in fresh workspace

### Steps to reproduce

Open https://github.com/artalar/reatom in gitpod (I do it by button from chrome extension)

### Expected behavior

Source control works fine

### Additional information

https://d8d33be4-2af9-4b09-8673-60112c23984d.ws-eu01.gitpod.io/#/workspace/reatom

![image](https://user-images.githubusercontent.com/27290320/81290164-3f3e3600-9070-11ea-82eb-83108901205f.png)

**Comment by artalar** [comment]
By the way, I has a previosly created workspace with the same repo and there source control works fine https://c15aff00-5db5-4013-9158-fce71d8ec2f2.ws-eu01.gitpod.io/#/workspace/reatom

**Comment by Michaelhobo** [comment]
I'm having the same problem. After I use the workspace for a bit, the source control panel starts working again.

**Comment by Michaelhobo** [comment]
This seems related to https://github.com/eclipse-theia/theia/issues/7860

**Comment by gtsiolis** [comment]
Thanks @artalar @Michaelhobo! I can reproduce this but haven't seen the behavior you mention in https://github.com/gitpod-io/gitpod/issues/1488#issuecomment-724805739 yet.

@akosyakov do you think this is issue with `eclipse-theia/theia`?

**Comment by Michaelhobo** [comment]
@gtsiolis I also have trouble reproducing the behavior in that comment. I've tried making it work again in a few different workspaces, but no luck so far.
