### ISSUE TITLE
Have prebuild settings from dashboard in `.gitpod.yml`

### ISSUE THREAD

**Issue by mittalyashu** [gitpod-io/gitpod#14887]
## Is your feature request related to a problem? Please describe

![IMG_3728](https://user-images.githubusercontent.com/29014463/203530396-f6623fd7-2a28-427c-9191-09d6dc7665a8.jpeg)

Have a single place to allow configure project prebuild settings from `.gitpod.yml` file.

## Describe the behaviour you'd like

Or even better to have two-way settings from UI (dashboard) to `.gitpod.yml` and vise-versa.

**Comment by gtsiolis** [comment]
Thanks @mittalyashu! Do you think https://github.com/gitpod-io/gitpod/issues/7426 covers the feature request here?
