### ISSUE TITLE
Setup Project/Pull request for GitLab repositories doesn't work

### ISSUE THREAD

**Issue by alblue** [gitpod-io/gitpod#1489]
### Describe the bug

When running a project for the first time, GitPod offers setting up a .gitpod.Dockerfile and a .gitpod.yml files, and then offering to create a pull request. When the repository comes from GitLab in the first place, it doesn't work well.

### Steps to reproduce

1. Set up a repository on GitLab.com
2. Clone with a GitPod workspace
3. Follow the 'set up a .gitpod' file
4. When it offers you to create a pull request, do so

### Expected behavior

A pull request on GitLab should be opened; however, it is blank

**Comment by gtsiolis** [comment]
Just run into this which is probably because the setup process defaults to using GH. Here's the console error:

```
Uncaught (in promise) Error: Not a GitHub repository!
...
```
