### ISSUE TITLE
Add native support for AWS S3

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#14892]
## Is your feature request related to a problem? Please describe

Provide native support to use S3 as object storage and also allows the use of IAM Roles for Service Accounts (in pods)

## Additional context

https://aws.amazon.com/es/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

**Comment by kylos101** [comment]
:wave: @gitpod-io/engineering-workspace , @csweichel is going to start breaking this down, no need to cover as part of refinement. Unless of course you're in refinement "now" with Chris, and want to socialize. :smiley:

**Comment by kylos101** [comment]
👋 @csweichel I changed the status for this issue to`in-progress`, as there's a linked draft PR, thank you 🙏

**Comment by kylos101** [comment]
👋 @csweichel, @Furisto 💪 is going to reach out to you to assume ownership of this issue.
