### ISSUE TITLE
gitpod/workspace-full image fails with "headless task failed: exit status 1"

### ISSUE THREAD

**Issue by dword-design** [gitpod-io/gitpod#14919]
### Bug description

`gitpod/workspace-full` fails with `headless task failed: exit status 1`. No other error message.

### Steps to reproduce

Add docker image with `FROM gitpod/workspace-full:latest`

### Expected behavior

The workspace is opening

**Comment by axonasif** [comment]
Hi @dword-design, I just tried reproducing your issue at https://github.com/axonasif/test/tree/workspace-full but was unable to, could you please share the contents of your custom dockerfile?

**Comment by dword-design** [comment]
@axonasif jup there you go:

https://github.com/dword-design/try-gitpod-error/tree/master

https://gitpod.io/#https://github.com/dword-design/try-gitpod-error/tree/master

**Comment by dword-design** [comment]
That's weird sometimes it's working and sometimes not

**Comment by adampapl** [comment]
I can confirm I'm getting "headless task failed: exit status 1" screen since few days when starting any of my projects.
You need to retry starting env few times before it works.
Happens both for new environments as for previously created (when I try to reopen them).
Very annoying.

**Comment by RCheesley** [comment]
Same problem on mautic/mautic with this PR: https://github.com/mautic/mautic/pull/11761 amongst others.

**Comment by kylos101** [comment]
:wave: @RCheesley @dword-design hi there, we created [this incident](https://www.gitpodstatus.com/incidents/b5b2p2fhwv0j) for the EU region, image builds appears to be stable again (we're seeing their success rate climb). Let us know if your experience improves, or, if you're still having trouble? I was able to recreate the problem, and after mitigating, am no longer able to recreate the problem.

**Comment by kylos101** [comment]
:wave: @adampapl , I see that you're in the US region and are also having trouble. Let me look into this further and report back to you, more updates to follow.

**Comment by adampapl** [comment]
@kylos101 Im located in NL so i should be running in EU region.

**Comment by kylos101** [comment]
@adampapl ah, I see now, I was looking at a prebuild workspace, which generally run in the US region. You are correct, I see you running in the EU region for regular workspaces. I assume your image build experience is better today? Let us know if not. :wave:

**Comment by adampapl** [comment]
@kylos101 Yesterday I could quickly start existing workspaces, but I could not create any new workspaces whole day (using 'new workspace' button). It was stuck at "building image" forever.
I checked now and creating new workspace works faster than ever. I hope it will stay like this because starting existing/creating new workspaces is unreliable a bit too often.

**Comment by kylos101** [comment]
> but I could not create any new workspaces whole day (using 'new workspace' button). It was stuck at "building image" forever.

Hey @adampapl , [was it stuck forever during this time](https://www.gitpodstatus.com/incidents/b5b2p2fhwv0j)? 

If yes, that would explain it. We've setup corresponding alerts, so we can react sooner if a similar issue in the future causes image builds to fail at a high rate. My apologies for the inconvenience.

If no, can you share the contents of your dockerfile? I'd be happy to test, but, assume it was the degraded perf mentioned above.

**Comment by adampapl** [comment]
@kylos101 yes it wa stuck like this for hours. Restarting did not help.

**Comment by kylos101** [comment]
Aye, @adampapl, that makes sense, the EU region's image build cluster was having trouble during that time. Thank you for confirming!
