### ISSUE TITLE
[JetBrains] Using new UI triggers UI Mismatch error dialog

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#14913]
In latest JetBrains IDE, opting in for the new UI causes an error dialog and asks for restart. When restarting, the IDE does not automatically reconnect.

![7C90EB91-3392-4B6E-B5AB-2B7683FDB919](https://user-images.githubusercontent.com/2318450/203790732-88e3d891-8ac2-4805-a096-55275f4f4eba.jpeg)

**Comment by dahaupt** [comment]
I am also experiencing this behavior. Would be great to be able to opt in for the new UI by default.
