### ISSUE TITLE
Detecting which URL was used to spin-up the Gitpod Environment

### ISSUE THREAD

**Issue by Kwok-he-Chu** [gitpod-io/gitpod#14923]
## Is your feature request related to a problem? Please describe
I have multiple applications that can be spun up within the same repository.

## Describe the behaviour you'd like
I would like gitpod to run a specific application on-startup. If there are multiple applications, it should be based off where the user came from (see example below). Ideally: Gitpod is aware from which subfolder it spun-up its environment (through URL parameters perhaps?).

## Describe alternatives you've considered
- Having multiple gitpod files support that can be placed within subfolders _(gitpod only looks at the /root for the .gitpod.yml file)_
Tried placing the .gitpod.yml file in multiple subfolders.

- Detecting which URL was used to spin-up the environment _(I couldn't find anything about this in the documentation)_
For example: `gitpod.io#https://github.com/gitpod-io/gitpod/tree/main/dev` would know it came from the subfolder: `/main/dev/`.
I can then write a gitpod script/command that checks the origin url and run the application automatically.

- Current solution:
Foreach application within the subfolder, I tell the user to execute a specific command in the Terminal

**Comment by Kwok-he-Chu** [comment]
Thanks for the swift response @axonasif, I'll take a look!

**Comment by axonasif** [comment]
Not sure if this falls under IDE team, but put it to your inbox (IDE team). Possibly related issue:
- https://github.com/gitpod-io/gitpod/issues/8252

**Comment by Kwok-he-Chu** [comment]
The solution above worked flawlessly, thank you for providing a clear example @axonasif Are there any future plans of including this information in (for example) an Gitpod environmental variable?

**Comment by axonasif** [comment]
Great to hear! That's something @loujaybee could help with I think 🙏

**Comment by akosyakov** [comment]
Env vars are subject to change. There are 2 primary means of getting info supervisor API and gp cli.

It is already possible to fetch via supervisor API: `curl -s $SUPERVISOR_ADDR/_supervisor/v1/info/workspace | jq .workspaceContextUrl`

Adding it to `gp info --json | jq .workspaceContextUrl` would make sense as well.

**Comment by axonasif** [comment]
Nice! Thanks for sharing, something new I learned 😁

**Comment by Kwok-he-Chu** [comment]
@axonasif I've made a [PR](https://github.com/gitpod-io/gitpod/pull/16096) to add this specific property. Would you mind to take look? :) A nice-to-have would be to include the (most) relevant properties of the supervisor api in `gp info`.

**Comment by axonasif** [comment]
Thank you for the efforts on this @Kwok-he-Chu! I see that the the IDE team was requested a review, so I'll leave it to them 🙏
