### ISSUE TITLE
[UBP] Dashboard notification of pay-as-you-go on first use of Gitpod after switch

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14939]
Users would benefit from a notification in Gitpod when they have been switched to pay-as-you-go billing.

### suggested design
- shown once after usage-based feature has been enabled 
- modal or banner (tbd)
- dismissable
- not alarming (not an error)
- ideally visible on first login or in dashboard (if already logged in) or in new workspace 
- only shown to existing users, not new signups
- content should include link to docs

> Your account has been enabled for pay-as-you-go. [Learn-more](https://www.gitpod.io/docs/configure/billing/usage-based-billing)

cc: @gtsiolis for visual design

**Comment by jankeromnes** [comment]
> - modal or banner (tbd)

Hi @gtsiolis! 👋

Would you have any sense of whether a "What's New" / "Choose IDE" type modal, or a more discreet "Info / Alert" type top banner would make more sense here?

Also, do you have a rough sense of what it should say? Maybe something along these lines?:

> Congratulations, you're now using Gitpod pay-as-you-go! (free tier) Upgrade your team, discover faster workspace classes, and only pay for the resources that you actually use. [Learn more]

**Comment by jankeromnes** [comment]
Ah, I just found another, possibly relevant suggestion [here](https://github.com/gitpod-io/gitpod/issues/14940#issue-1463777819):

> It would be helpful to show a notification on these pages
> 
> > Your account has been enabled for pay-as-you-go. [Learn-more](https://www.gitpod.io/docs/configure/billing/usage-based-billing)  
> > New payment options are available under [Billing](https://gitpod.io/billing).

**Comment by jldec** [comment]
Closing - no longer required.
