### ISSUE TITLE
Deprecate and remove "Cancel Prebuilds on Outdated Commits" feature

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#14949]
## Is your feature request related to a problem? Please describe

In an effort to optimize Prebuilds, we've previously introduced a Project Settings feature called "Cancel Prebuilds on Outdated Commits":

<img width="691" alt="Screenshot 2022-11-25 at 09 38 54" src="https://user-images.githubusercontent.com/599268/203937577-9b9fc98f-ec27-4572-ac58-db417ac8777a.png">

What this feature does is: When new commits are pushed to a given branch, automatically cancel any prebuilds that are currently still running for this branch.

Unfortunately, this feature **doesn't quite work as we intended**, and it has a number of **unfortunate side effects**:

- For projects with a low commit frequency, this feature does nothing (i.e. prebuilds are always finished before the next push, so this feature brings zero value)

- For projects with a high commit frequency, this feature:
  - Wastes a lot of compute time (i.e. many prebuilds are triggered, then they run for a while, then they are often discarded when the next push arrives)
  - Rarely produces any actually-usable prebuild (in a busy day, many prebuilds are run and discarded, but the very first prebuild that manages to run until completion happens only when the commit frequency goes down again, e.g. during a lunch break or at the end of a work day when most committers are co-located)
  - Does not actually "cancel" prebuilds semantically, but produces many "System Errors" instead: https://github.com/gitpod-io/gitpod/issues/13874

## Describe the behaviour you'd like

We should **deprecate and remove** the "Cancel Prebuilds on Outdated Commits" feature, because it doesn't work well.

## Describe alternatives you've considered

We already have better alternatives to optimize prebuilds:

https://github.com/gitpod-io/gitpod/blob/08be4195d40cbea9248847547a8fc25fe44f3cba/components/server/ee/src/prebuilds/prebuild-manager.ts#L243-L258

<img width="684" alt="Screenshot 2022-11-25 at 09 48 39" src="https://user-images.githubusercontent.com/599268/203939276-538a0c91-4654-4657-92eb-6683abe466dc.png">

**Comment by easyCZ** [comment]
Should also deprecate (not remove) it from https://github.com/gitpod-io/gitpod/blob/main/components/public-api/gitpod/experimental/v1/projects.proto#L51 used by the public api

**Comment by svenefftinge** [comment]
> For projects with a low commit frequency, this feature does nothing (i.e. prebuilds are always finished before the next push, so this feature brings zero value)

A very common working mode is to force push on a branch. In those case any running prebuilds should always be immediately cancelled (no opt-out), because they are no longer reachable (the commit doesn't exist).
