### ISSUE TITLE
[UBP] Disable subscriptions to old plans after UBP has been enabled

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14940]
After switching to UBP, `Plans` and `Team Plans` are no longer linked from the Settings menu if users are not on any plans, but those pages are still reachable at gitpod.io/plans and gitpod.io/teams.

Users should only be able to use those pages to Cancel existing paid plans or Downgrade to Free.

Upgrades, or buttons to create other Chargebee subscriptions (E.g. Create Team Plan) should be disabled.

It would be helpful to show a notification on these pages

> Your account has been enabled for pay-as-you-go. [Learn-more](https://www.gitpod.io/docs/configure/billing/usage-based-billing)  
> New payment options are available under [Billing](https://gitpod.io/billing).

**Comment by svenefftinge** [comment]
> It would be helpful to show a notification on these pages

This needs to be more specific @jldec
