### ISSUE TITLE
Handle PATs UI loading states

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#14944]
When we're loading PATs (either List, Get, Create etc), add a loading screen transition.

**Comment by jeanp413** [comment]
@gtsiolis is there a mockup for this?

**Comment by easyCZ** [comment]
@gtsiolis Yes, indeed. It's scheduled in the current iteration.

And exactly as @gtsiolis suggested, nothing new or special is needed here, just showing something while the requests are pending. That goes for all the actions - loading the list, creating a token, etc..

**Comment by mustard-mh** [comment]
[Added](https://github.com/gitpod-io/gitpod/pull/15015/commits/e2e1bf88baf4c97b0d717f70b7db060a4b39218d) component `Loader.tsx` with `SpinnerLoader` and `SpinnerOverlayLoader`

|SpinnerLoader | SpinnerOverlayLoader |
|-|-|
|![image](https://user-images.githubusercontent.com/20944364/204800041-c54256fd-2dea-4386-a09f-6fce3129340b.png)|<img width="1514" alt="image" src="https://user-images.githubusercontent.com/20944364/204801228-2ce727da-47f7-4b13-8600-a15d53d2cfc1.png">|
