### ISSUE TITLE
Allow end-users to specify region of cluster

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1496]
Allow end-user to specify the region of a cluster in case they are using proxy/VPN/tor that might confuse gitpod to provide a cluster that has an unacceptable delay.

Ideally this should be allowed per repository with wildcards.

### References
Original issue: https://github.com/gitpod-io/gitpod/issues/1495
 - Created to track this issue since https://github.com/gitpod-io/gitpod/issues/1495 is composed of two issues.

**Comment by ceefour** [comment]
I am hit by this too, according to https://www.gitpod.io/docs/ I am in Indonesia should get the Tokyo region or even Singapore (?). However I'm getting `ws-us02.gitpod.io` workspaces.

Manually changing it to `ws-ap.gitpod.io` as suggested by @Kreyren doesn't work...

![image](https://user-images.githubusercontent.com/24123/92301631-67429500-ef8f-11ea-9fbb-8ba38dc4e2c0.png)

**Comment by ceefour** [comment]
Keep alive

**Comment by axonasif** [comment]
Sure @wilmarques!

**Comment by vanarok** [comment]
I am in Asia but my api which is issued by the provider is designated in the Netherlands.  I'm getting a workspace in the US.
