### ISSUE TITLE
[UBP] Non-zero balances found for non-paying teams

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#14976]
Teams with billing strategy "other" should have a zero credit balance.
This is not the case for a number of teams in the usage ledger.
In most cases they have a small negative balance (all < 30 credits) 

For more details see [discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1669305060587619) or [query](https://console.cloud.google.com/bigquery?sq=441577903635:bf5a5a234b6744459c5a30e8e6cffbc4) (internal)

**Comment by svenefftinge** [comment]
I'll add a control loop that checks for canceled Chargebee subscriptions and runs reset usage.

**Comment by svenefftinge** [comment]
For teams, I think this happened because of some configuration issues in past deploys. You can manually fix them using the admin dashboard. I have [created another issue](https://github.com/gitpod-io/gitpod/issues/15055) to take care of individual usage of chargebee.

**Comment by jldec** [comment]
Manually adjusted all teams to within +1 credit
