### ISSUE TITLE
Pull Requests of large repositories open slow

### ISSUE THREAD

**Issue by shyim** [gitpod-io/gitpod#14982]
### Bug description

When you example open https://github.com/NixOS/nixpkgs/pull/203007 in Gitpod it takes like several minutes to open the Editor.

Opening outside the PR View is fast. I guess updating remote to add a second one is fetching the entire repository. When you open a branch it is fast

### Steps to reproduce

Open this PR in Gitpod https://github.com/NixOS/nixpkgs/pull/203007

**Comment by axonasif** [comment]
Related: https://github.com/gitpod-io/gitpod/issues/14980
