### ISSUE TITLE
Dotfiles installation (symlinking) should not overwrite crutial host files (e.g. bashrc, gitconfig)

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#14986]
## [No overwrite files](https://github.com/axonasif/dotfiles#no-overwrite-files)

The following files from user dotfiles repo should not overwrite the existing host files but instead virtually load after the existing ones to preserve integrity of the host system:

- .bashrc
- .bash_profile
- .zshrc
- .zprofile
- .kshrc
- .profile
- config.fish

These files can contain some crucial functions that may be lost if we do overwrite them.

Use native methods to load the user-file where possible, otherwise append[^1].

## Additional context

Note: not sure if dotfiles falls under ide-team, please forward to the appropriate team if needed 🙏 

[^1]: https://github.com/axonasif/dotsh/blob/157878f8680344d21b11443b00d3044ddefee6d5/src/utils/dotfiles.sh#L115

**Comment by akosyakov** [comment]
How other solutions like Codespaces deal with it? I wonder whether it is a bug or expected? Is there some standard which we should adhere here?

**Comment by axonasif** [comment]
I'm not sure, but I guess they don't handle this special case.

If someone is using a custom dotfiles manager (e.g. [chezmoi](https://gitpod.slack.com/archives/C01KGM9BH54/p1664244289273019)), they'd need to handle it themselves.

https://dotfiles.github.io/ has some useful info I think.

Related internal feedback from Chad: [here](https://gitpod.slack.com/archives/C01KGM9BH54/p1664244289273019)
