### ISSUE TITLE
[supervisor] Support spawning Gitpod tasks as tmux windows

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#14988]
## Is your feature request related to a problem? Please describe

Tmux integration would allow for easy interactivity with Gitpod tasks on SSH and give a more 'first-class' feel to neo(vim)/emacs/ssh users in general.

## Describe the behaviour you'd like

- A option in preferences for enabling tmux integration.
- `supervisor` then opens all Gitpod tasks inside a tmux session as windows.
- (proposal): Auto-install [gitpod.tmux](https://github.com/axonasif/gitpod.tmux) plugin when the integration is enabled by executing the plugin from `/etc/tmux.conf`. (to provide a similar experience as the Gitpod VSCode theme/integrations)
- Since all tasks would be opened in tmux, set `tmux` as the default shell in `Machine` settings.json of vscode with the following: [here](https://github.com/axonasif/dotsh/blob/8364d2c6ef806f11bf4d4a350440bc1d2e6f7470/src/config/shell/mod.sh#L146)

## Describe alternatives you've considered

- https://github.com/axonasif/dotsh#tmux-integration

## Additional context

[Internal slack thread.](https://gitpod.slack.com/archives/C01KGM9AW4W/p1669571310117799)

**Comment by akosyakov** [comment]
I think we should think how we make IDEs pluggable integrations not built in in supervisor as a general solution.

**Comment by axonasif** [comment]
That would be great as well.

**Comment by axonasif** [comment]
BTW, one of the other reasons for suggesting to implement this to supervisor was to also use it for https://github.com/gitpod-io/gitpod/issues/7671 implementation where you'd pass on `/.supervisor` into the testing container and launch the Gitpod tasks in tmux for easy debugging. [But it's just a proposal](https://gitpod.slack.com/archives/C01KGM9AW4W/p1669571426423519?thread_ts=1669571310.117799&cid=C01KGM9AW4W) 🙂

**Comment by gitpod-community** [comment]
Test 2

**Comment by gitpod-community** [comment]
Test 3
