### ISSUE TITLE
Support git "sparse checkout" (via `.gitpod.yml`) to improve experience with very very large repos

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#14980]
Sometimes repos are very (very very) large and you only need to work with some well-defined subset.  

Examples are:
- Working inside a monorepo,
- Working in a repo with an extremely large number of integration/acceptance/regression tests - frequently with many many data files! - that you would not use locally but only remotely via GitHub/GitLab/CircleCI/other CI runners in the cloud,
- Working in a repo where you want to expose (directly, easily) only a subset to many of your users
  - Frequently for pedagogic purposes.

For this it would be great to be able to configure a sparse checkout (as well as another feature for reducing checkout time/bandwidth/space used: partial clone) right in the `.gitpod.yml`, to be respected by gitpod when spinning up a workspace.

See this blog post ["Delivering software faster: How to coax Git into working great with a monorepo"](https://www.sabre.com/locations/apac/delivering-software-faster%E2%80%AFhow-to-coax-git-into-working-great-with-a-monorepo/) for more information (if you need it) on the benefits of sparse checkout.

(Partial clone is [supported by GitLab](https://about.gitlab.com/blog/2020/03/13/partial-clone-for-massive-repositories/) ([docs](https://docs.gitlab.com/ee/topics/git/partial_clone.html), Bitbucket Cloud does [_not_ support it](https://jira.atlassian.com/browse/BCLOUD-19847) but private Bitbuckets [do](https://jira.atlassian.com/browse/BSERV-11639), don't know its status on GitHub but lack of information implies it is not supported there.)

**Comment by david-bakin-sl** [comment]
Also ["sparse index"](https://github.blog/2021-11-10-make-your-monorepo-feel-small-with-gits-sparse-index/) might be useful.

**Comment by axonasif** [comment]
Discord thread:
- https://discord.com/channels/816244985187008514/902832281369075722/1045808089804312647
