### ISSUE TITLE
[SSH] Launch ssh:// custom scheme to open a local terminal-emulator

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#14991]
## Is your feature request related to a problem? Please describe

Having this would allow users to skip the manual copy pasting step of `ssh ''` command!

## Describe the behaviour you'd like

To be like this when enabled:
- https://github.com/axonasif/dotsh#easy-shhing-through-local-terminal

## Additional context

After implemented, we'd need to document how to configure local terminals to recognize `ssh://` URLs.
- https://github.com/axonasif/dotsh/blob/main/docs/REFERENCE.md#open-ssh-protocol-urls-in-local-terminal-emulator

**Comment by akosyakov** [comment]
Is it something standard? If not we are going to have a custom system sceme for local cli and launch it.

I would prefer that feature requests are from user perspective not define implementation details.

**Comment by axonasif** [comment]
I'm not sure if this is a standard but iterm2 and kitty supports this by default.
Also, one of our users had suggested this:
- https://github.com/gitpod-io/gitpod/issues/9323#issuecomment-1149882172
