### ISSUE TITLE
[db-sync] Install Redis into application cluster (or use GCP managed Redis)

### ISSUE THREAD

**Issue by andrew-farries** [gitpod-io/gitpod#14996]
Talk with the workspace team regarding their experience of in-cluster Redis vs GCP MemoryStore.

**Comment by geropl** [comment]
Got feedback from them [here](https://gitpod.slack.com/archives/C02F19UUW6S/p1669646113517129). They had issues with node restarts and k3s not being able to re-join the cluster. But that's something we don't have to bother with. :+1: 

We should decide based on what's quicker, as we just want to invalidate some assumptions (in the context of db-sync removal, at least). A switch later on should always be doable.
