### ISSUE TITLE
Consent Flow interrutps opening the GitPod Workspace

### ISSUE THREAD

**Issue by colemickens** [gitpod-io/gitpod#15]
The first time I used GitPod, it has to go to GitHub to prompt for consent. When I'm redirected back, GitPod isn't stashing/unstashing state, and so I end up on my list of workspaces (empty).

Re-clicking GitPod does the correct thing, of course.

Just a small UX issue.

**Comment by colemickens** [comment]
Sorry, this is a dupe of #8.

**Comment by svenefftinge** [comment]
Thanks for the feedback!
