### ISSUE TITLE
Popups for loading previous old workspace blocked by chrome

### ISSUE THREAD

**Issue by akshatnarayangupta** [gitpod-io/gitpod#15011]
## Open the previous workspace without user intervention in the same tab, also delete this workspace since i want automatic redirects

##Tried gp export --external, but it requires a user event to redirect, automatic redirects are blocked by chrome

**Comment by axonasif** [comment]
Hi @akshatnarayangupta, you can keep an eye on our changelog to know when the public api will be out, that's likely going to help with what you're trying to build:
- https://www.gitpod.io/changelog/
