### ISSUE TITLE
[ws-daemon] workspaces sometimes do not gracefully stop and cannot be restarted

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#15049]
### Bug description

Workspaces sometimes do not gracefully stop, when this happens the workspace cannot restart, preventing the user from accessing files which may have not bee pushed to VCS. This is a poor user experience. As an administrator, we can see this happening when the # of workspace stuck in STOPPED gradually rises.

Observations:
1. STOPPED workspaces are increasing, which is unusual (generally this number fluctuates, instead of steadily increasing):
![image](https://user-images.githubusercontent.com/1272076/204654647-feb598cf-f4db-4ead-bfc3-44b3df41e85f.png)
   * This problem is new for `gen77`, as of Nov 28, which was deployed on Nov 18. It may be related to a recent webapp or ide deployment. :thinking: 
   * The problem started in `eu77` with regular workspaces on Nov 28, and manifested with prebuilds in `us77` on Nov 29.
2. lingering workspaces are in a STOPPED phase, and have `gitpod/never-ready` annotation, which means they never successfully started.
3. upon examination of the original workspace instance ID for workspace ID where the latest instance is stuck in STOPPED, we see [this error](https://jaeger-eu-prod.workspace-preview.gitpod-io-dev.com/trace/224cbfda169ef9b3) in traces `workspace does not exist`. This suggests something prevented the workspace backup from starting or finishing. Here are [all traces with errors for the related workspace ID](https://jaeger-eu-prod.workspace-preview.gitpod-io-dev.com/search?end=1669756920000000&limit=200&lookback=custom&maxDuration=&minDuration=&service=ws-manager&start=1669266000000000&tags=%7B%22workspaceId%22%3A%22andrebraga7-postgresql1-89t68vo8qxj%22%2C%22error%22%3A%22true%22%7D).
4. [Here are the logs](https://cloudlogging.app.goo.gl/JdyGKk9baciGS8XF7) for the original workspace instance which failed backup. We [waited for 10 minutes](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-29T18:23:10Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%2226572ece-d131-437f-983d-f51ceb852e96%22%0Atimestamp%3D%222022-11-29T18:23:10Z%22%0AinsertId%3D%22bxbsm02486e4r0kw%22;summaryFields=:false:32:beginning;timeRange=P1D?project=workspace-clusters) [[1](https://github.com/gitpod-io/gitpod/blob/f89093da40d4a604e2ec64ae8f158d419a86f755/components/ws-daemon/pkg/dispatch/dispatch.go#L209)], and then gave up.

### Steps to reproduce

Not sure, yet

### Workspace affected

andrebraga7-postgresql1-89t68vo8qxj (just one example), the graph (:point_up:) indicates there are more

### Expected behavior

When a workspace stops, it backs up w/o error, so that it can be restarted at a later time.

### Example repository

https://github.com/andrebraga7/postgreSQL101 (just one example, no common pattern I can find yet)

### Anything else?

To find never-ready regular workspaces: `  kubectl get pod -o json -l component=workspace -l headless=false | jq -r '.items[] | select(.metadata.deletionTimestamp != null and .metadata.annotations["gitpod/never-ready"] != null ) | .metadata.name' | column | xargs kubectl get pods -o wide`

**Comment by kylos101** [comment]
Given the example :point_up: , [the related node was created on Nov 28 at 9:00 GMT.](https://cloudlogging.app.goo.gl/FGcVD4ZKtLUF5Qiv5)

The [warning on stop](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-29T18:25:03Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%2226572ece-d131-437f-983d-f51ceb852e96%22%0A-resource.labels.container_name%3D%22calico-node%22%0Atimestamp%3D%222022-11-29T18:23:10Z%22%0AinsertId%3D%22bxbsm02486e4r0kw%22;summaryFields=:false:32:beginning;timeRange=P1D?project=workspace-clusters) (impacting backup) occurred well after the node was created, around Nov 28 18:23 GMT.

So the problem isn't necessarily related to workspaces starting on fresh nodes.

**Comment by kylos101** [comment]
Log observations:
- [The 10 minute context is exceeded to handle a pod update](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-29T18:25:03Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%2226572ece-d131-437f-983d-f51ceb852e96%22%0A-resource.labels.container_name%3D%22calico-node%22%0Atimestamp%3D%222022-11-29T18:23:10Z%22%0AinsertId%3D%22bxbsm02486e4r0kw%22;summaryFields=:false:32:beginning;timeRange=P1D?project=workspace-clusters)
- [Initially we cannot add the workspace given the cgroup path](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-29T18:23:10Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%2226572ece-d131-437f-983d-f51ceb852e96%22%0A-resource.labels.container_name%3D%22calico-node%22%0Atimestamp%3D%222022-11-29T18:23:10Z%22%0AinsertId%3D%22f9jwmlwlekiid1wm%22;summaryFields=:false:32:beginning;timeRange=P1D?project=workspace-clusters)
- [We cannot start the govenor for cpu limiting](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-29T18:23:10Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%2226572ece-d131-437f-983d-f51ceb852e96%22%0A-resource.labels.container_name%3D%22calico-node%22%0Atimestamp%3D%222022-11-29T18:23:10Z%22%0AinsertId%3D%22zfczb9z1wglzy4fp%22;summaryFields=:false:32:beginning;timeRange=P1D?project=workspace-clusters)
- [And then many instances of "workspace we have not seen before" for the cpuLimiter](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-29T18:27:33Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%2226572ece-d131-437f-983d-f51ceb852e96%22%0A-resource.labels.container_name%3D%22calico-node%22%0Atimestamp%3D%222022-11-29T18:23:33Z%22%0AinsertId%3D%2267d00kxmv8tczn0j%22;summaryFields=:false:32:beginning;timeRange=P1D?project=workspace-clusters)
- [Finally workspace backup fails, perhaps because we never added the workspace](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-29T19:13:24Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%2226572ece-d131-437f-983d-f51ceb852e96%22%0A-resource.labels.container_name%3D%22calico-node%22%0Atimestamp%3D%222022-11-29T19:13:24Z%22%0AinsertId%3D%22kn92qmelf7k6h84y%22;summaryFields=:false:32:beginning;timeRange=P1D?project=workspace-clusters)
- [The cpu limiter keeps logging an error, that it found a workspace it hasn't seen before](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-11-29T19:23:33Z;query=resource.labels.cluster_name%20:%20%2528%22eu77%22%2529%0A%2226572ece-d131-437f-983d-f51ceb852e96%22%0A-resource.labels.container_name%3D%22calico-node%22%0Atimestamp%3D%222022-11-29T19:18:33Z%22%0AinsertId%3D%22uktj0l2j7cf43hkl%22;summaryFields=:false:32:beginning;timeRange=P1D?project=workspace-clusters)

Neither `ws-manager` or `ws-daemon` have been restarted:
```
gitpod /workspace/gitpod (kylos101/workspace-not-found) $ kubectl get pods -l component=ws-manager
NAME                          READY   STATUS    RESTARTS   AGE
ws-manager-85b74f9bf7-r2xhg   2/2     Running   0          10d
gitpod /workspace/gitpod (kylos101/workspace-not-found) $ kubectl get pods -l component=ws-daemon
NAME              READY   STATUS    RESTARTS   AGE
ws-daemon-2sdzv   3/3     Running   0          37h
ws-daemon-6slhc   3/3     Running   0          37h
ws-daemon-76fxw   3/3     Running   0          2d8h
ws-daemon-76j7s   3/3     Running   0          13h
ws-daemon-8c5bc   3/3     Running   0          14h
ws-daemon-8j8lz   3/3     Running   0          14h
ws-daemon-8jntl   3/3     Running   0          36h
ws-daemon-8xgqt   3/3     Running   0          14h
ws-daemon-bc75v   3/3     Running   0          14h
ws-daemon-bdsvc   3/3     Running   0          15h
ws-daemon-cjt9n   3/3     Running   0          9h
ws-daemon-cq8gq   3/3     Running   0          14h
ws-daemon-cqk56   3/3     Running   0          13h
ws-daemon-cqqkf   3/3     Running   0          13h
ws-daemon-cvttq   3/3     Running   0          14h
ws-daemon-dvpzl   3/3     Running   0          14h
ws-daemon-f6hcl   3/3     Running   0          4d13h
ws-daemon-fsmpb   3/3     Running   0          12h
ws-daemon-g4pmb   3/3     Running   0          13h
ws-daemon-g4qdt   3/3     Running   0          12h
ws-daemon-g6z9h   3/3     Running   0          38h
ws-daemon-gbzzr   3/3     Running   0          13h
ws-daemon-glpsl   3/3     Running   0          12h
ws-daemon-hfggf   3/3     Running   0          36h
ws-daemon-hn8mj   3/3     Running   0          21m
ws-daemon-hwm99   3/3     Running   0          13h
ws-daemon-hxmc6   3/3     Running   0          13h
ws-daemon-j2lpf   3/3     Running   0          15h
ws-daemon-jcjcc   3/3     Running   0          23m
ws-daemon-jklnw   3/3     Running   0          13h
ws-daemon-ksksk   3/3     Running   0          9h
ws-daemon-l4q6b   3/3     Running   0          37h
ws-daemon-l59mg   3/3     Running   0          14h
ws-daemon-lsbkf   3/3     Running   0          14h
ws-daemon-mthz7   3/3     Running   0          14h
ws-daemon-mvkdv   3/3     Running   0          9h
ws-daemon-nc692   3/3     Running   0          4d13h
ws-daemon-pbtdr   3/3     Running   0          14h
ws-daemon-plm2g   3/3     Running   0          15h
ws-daemon-pmz47   3/3     Running   0          2d11h
ws-daemon-ppwb5   3/3     Running   0          37h
ws-daemon-schnc   3/3     Running   0          13h
ws-daemon-tnkb4   3/3     Running   0          2d14h
ws-daemon-v5zvf   3/3     Running   0          38h
ws-daemon-vk99d   3/3     Running   0          13h
ws-daemon-vxjgl   3/3     Running   0          2d14h
ws-daemon-w9msl   3/3     Running   0          13h
ws-daemon-wmplr   3/3     Running   0          13h
ws-daemon-xhnnx   3/3     Running   0          12h
ws-daemon-xknkd   3/3     Running   0          12h
ws-daemon-xp7dx   3/3     Running   0          14h
```

**Comment by kylos101** [comment]
:bulb: run a test, where we sleep on stop in a preview environment for 11m. What happens? I assume because it takes longer than 10m, that the backup will fail.

**Comment by kylos101** [comment]
@utam0k could I ask you to 👀 at this and share your thoughts? It's becoming a problem in `gen77`.

**Comment by kylos101** [comment]
[Runbook for related mitigation](https://github.com/gitpod-io/runbooks/pull/408/commits/cfb55e4f3bec68e26fee9b3bfe6456a347b81b02)

[Alert for related condition warranting mitigation](https://github.com/gitpod-io/gitpod/pull/15086/commits/8a40e5a05c74754b287059f5b1e010ce1cdf3fc4)

**Comment by utam0k** [comment]
I send out a PR https://github.com/gitpod-io/gitpod/pull/15087 to confirm that

**Comment by kylos101** [comment]
Thanks @utam0k ! How will having that additional trace help?

**Comment by utam0k** [comment]
@kylos101 We can confirm that the request included the backup flag. If there is no backup flag, then ws-daemon is successfully handling the non-backup.

**Comment by kylos101** [comment]
Thanks @utam0k ! How will :point_up:  help us avoid collecting workspaces stuck in STOPPED?

**Comment by atduarte** [comment]
Waiting for PR https://github.com/gitpod-io/gitpod/pull/15087 to be deployed to assert if it's a case where there is no backup flag set, and if yes understand why.

**Comment by kylos101** [comment]
This issue no longer seems relevant. For example, the issue we saw where we were accumulating workspaces in a STOPPED state no longer manifests itself. Therefore, I am going to remove from our groundwork for now. For posterity, [here](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/trace/336e6108af9272bb?uiFind=45a1c2caa9dc62a0) is a span where you can see the new backupLogs tag @utam0k added.

cc: @atduarte
