### ISSUE TITLE
Triggering manual integration test werft job no longer works

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#15048]
### Bug description

```
werft run github -j ./.werft/workspace-run-integration-tests.yaml \
-a with-integration-tests=workspace \
-a with-large-vm=true
```
Does not work anymore. It kicks off a job but fails with 
```
Error: context "dev" does not exist
[Tue 29 Nov 2022 04:48:37 PM UTC] The workspace isn't configured to have core-dev access. Exiting.
```
Werft job: https://werft.gitpod-dev.com/job/gitpod-custom-head.4281

### Steps to reproduce

n\a

**Comment by kylos101** [comment]
@meysholdt @mads-hartmann may we ask for your help in debugging this failure? It seems like our integration test job no longer has access to `core-dev`. Perhaps the [service account](https://github.com/gitpod-io/gitpod/blob/fbd0fe5037e8ed6e2634cf58631a38edc02e4db2/.werft/workspace-run-integration-tests.sh#L91) permissions changed?

**Comment by kylos101** [comment]
Nevermind. We can run [like so](https://werft.gitpod-dev.com/job/gitpod-build-pavel-test123.5/raw).
