### ISSUE TITLE
[UBP] Handle Chargebee cancellations

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#15055]
When a user cancels their chargebee plan, they should transition into a fresh "free" ubp plan, so all previous usage needs to be reset.

**Comment by svenefftinge** [comment]
After reconsideration, we decided to not do anything about this but manually handle the few cases that will happen.

**Comment by jldec** [comment]
Re-opening
see members of [teams mentioned in discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1670609008476229) (internal)
