### ISSUE TITLE
Don't store leeway cache in /tmp

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#15060]
## Is your feature request related to a problem? Please describe
`/tmp` is an in-memory file system (`tmpfs`) and a workspaces memory is too precious to hold tens of gigabytes of leeway cache. 
Also, the IDE components build fails in `leeay run dev:preview` due to memory issues.

Steps to reproduce: 
* install `gitpod-monitor` VS Code extension to see CPU/Memory usage in the status bar.
* run `fallocate -l 10000000000 /tmp/tmp.dat` to create a 9.6GB file.
* see the memory usage go up from 25% to > 70%: 
<img width="151" alt="image" src="https://user-images.githubusercontent.com/239422/204771619-b4cccdf2-f72c-4278-af94-32c7671b949f.png">

## Describe the behaviour you'd like
The leeway cache should be stored in `/var/tmp` as this is part of the root file system. 

## Describe alternatives you've considered
We discussed storing the cache in `/home/gitpod` but dismissed this option because if there were a full-workspace backup one day, we would not want the leeway cache to be part of the backup. We assume Leeway re-downloading the cache is a more pleasant developer experience than a slow workspace startup. 

## Additional context
Thank you, @akosyakov and @iQQBot, for the pointer!

**Comment by mads-hartmann** [comment]
This should be doable by setting `LEEWAY_CACHE_DIR` and `LEEWAY_BUILD_DIR` - asked JenTing to try it [here](https://gitpod.slack.com/archives/C032A46PWR0/p1670500174403189?thread_ts=1670476276.640779&cid=C032A46PWR0)
