### ISSUE TITLE
Improve the error message for `Error: GitHub API Error. Status: 500`

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1507]
Based on https://github.com/gitpod-io/gitpod/issues/1505 the current error message for github's shortage is:

```
We are having trouble parsing your context

Error: GitHub API Error. Status: 500

Please file an issue if you think this is a bug.
```

I believe this being a confusing to some users so i am proposing:

---
## We are having trouble parsing your context

We are unable to contact GitHub API which is required for gitpod authentification.

**FATAL:** GitHub API Error. Status: 500

This may be caused by:
1) Temporary/Full GitHub shortage

Please verify that GitHub has a shortage on https://www.githubstatus.com/ and if so try again later. Alternatively file a new issue to gitpod's tracker

---

**Comment by markfirmware** [comment]
There is no parsing trouble. Remove “parsing” from the message.

**Comment by Kreyren** [comment]
> There is no parsing trouble. Remove “parsing” from the message. @markfirmware 

Agree, but the `We are having trouble parsing your context` seems hardcodded for general error so i didn't propose it's change since it may require additional logic.

**Comment by markfirmware** [comment]
Ok, an improvement is an improvement. Is the api called by the browser or a gitpod server? This ought to be logged and visible to devops for further improvement.

**Comment by Kreyren** [comment]
@markfirmware I may be wrong, but i think that this part of gitpod is kept proprietary (probably for security reasons), but i would also want to have it open-source ^-^
