### ISSUE TITLE
[server] handle rate limiting for startWorkspace

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#15083]
## Is your feature request related to a problem? Please describe

Workspace Team would like to enable startWorkspace rate limiting in https://github.com/gitpod-io/ops/issues/6831 to protect `workspace-clusters`.

## Describe the behaviour you'd like

`server` should gracefully handle a resource exhausted response, retrying for a period of time, and then give up if unsuccessful. 

If `server` gives up, the user should see a related error on the `dashboard` that their workspace could not start. 

What should public API consumers see if their workspace cannot start? @geropl @easyCZ (@kylos101 just added this question)

## Unknowns

How should`server` behave if restarted while backing off? Do we need to persist attempts remaining in the DB, so that when it comes online again, it continues trying?

From @easyCZ :
1. Given there's currently a distinction between createWorkspace and startWorkspace from the WebApp side, what will happen when startWorkspace is rate limited but the createWorkspace succeeded?
2. What is the expected behaviour? I'd expect that when the rate-limit kicks in, we'd retry exponentially up to N times and then give up. Is the expectation that we should eventually try again?
3. Will the rate limit specify try again in X seconds?

## Additional context

Related [internal Slack thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1669836729385499)

**Comment by kylos101** [comment]
@geropl @easyCZ is this something that y'all might be able to consider for an upcoming iteration? :pray: We'll wait to do https://github.com/gitpod-io/ops/issues/6831 until getting confirmation that `server` is "ready".

**Comment by geropl** [comment]
Scheduled it for next week. :+1:

**Comment by kylos101** [comment]
Thank you!

**Comment by kylos101** [comment]
@geropl hey there, can you help set expectations for when this can be picked up? :pray: :pleading_face:

**Comment by andrew-farries** [comment]
Hi @kylos101 and @Furisto. We've just picked this issue up. A few points:

* To check my understanding, it looks like the `ws-manager` `StartWorkspace` rate limit is global to all users across `gitpod.io`? ie, it's not per-user.
* Currently in `eu82` the rate limit for the `StartWorkspace` RPC is set to:

  ```json
      "/wsman.WorkspaceManager/StartWorkspace": {
        "block": true,
        "bucketSize": 3,
        "refillInterval": "500ms"
      }
  ```
  The bucket size seems quite high. Looking at Grafana it looks like we don't get anywhere close to this limit.
  <img width="2473" alt="image" src="https://user-images.githubusercontent.com/8225907/212945681-8db1c8e6-975f-467b-8690-20622cb9b779.png">
  Also in the linked [issue](https://github.com/gitpod-io/ops/issues/6831)  the spike that caused the problems won't trigger the current rate limit either:
  ![image](https://user-images.githubusercontent.com/1272076/202826543-178f554a-dbf5-450c-9a57-e86f87ad4e92.png)
  Do you have values in mind for the `bucketSize` and `refillInterval`?

* `server`'s current behaviour seems adequate if the rate limit is expected to be hit only infrequently. There are UX improvements we could make here such as a specific error message and automatic retries but we'd need to see how often the limit is hit before judging whether that's worth doing.

I'm going to set up `ws-manager` in a preview environment with a low rate limit to verify exactly how `server` behaves when  the `ws-manager` rate limit is hit.

**Comment by andrew-farries** [comment]
Closing this as complete from the webapp team side now. To summarise, we have:

* Exposed rate limiter metrics from the workspace clusters [[PR](https://github.com/gitpod-io/ops/pull/7849)] so that it's possible to see how often the ws-manager rate limit gets hit.
* Improved metrics on the server side [[PR](https://github.com/gitpod-io/gitpod/pull/15904)] so that we can see any StartWorkspace requests that fail due to gRPC ResourceExhausted errors.
* Checked that the dashboard UX is acceptable when workspace starts get blocked by a rate limit (assuming rate limits are hit only infrequently). [[Slack](https://gitpod.slack.com/archives/C02EN94AEPL/p1674044419465289?thread_ts=1674044171.054609&cid=C02EN94AEPL)]
