### ISSUE TITLE
Allow multiple previews

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1509]
Currently gitpod/theia only allows one preview

![image](https://user-images.githubusercontent.com/11302521/81925417-cba4a780-95e0-11ea-9787-dfaa6eb5c8c5.png)

where multiple previews are expected (i.e to manage music and/or watch something while the code is building, various development, etc..)

**Comment by Kreyren** [comment]
Tabs in the preview would be also nice btw ^-^

**Comment by akosyakov** [comment]
Have you tried `F1` -> `Preview: Open URL`?

**Comment by ewels** [comment]
Late to the party, but I'd love this as well 👍🏻
