### ISSUE TITLE
List all (or paginate) access tokens view

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#15098]
Currently we're only fetching the first page of 100 records to show for the tokens. Either we should paginate the view, or we should for now fetch all of them when loading the data.

CC @gtsiolis if you have ideas on this

**Comment by gtsiolis** [comment]
@easyCZ Some thoughts below:
1. Paginating sounds like the best way forward.
2. I'd avoid loading them all at once.
3. I'd also hide the pagination element altogether if the records are less than the page size (100).
4. Maybe also consider paginating at 50, 25, or even 10 entries if it makes sense.

**Comment by easyCZ** [comment]
The API supports any page size between 1 and 100.

**Comment by gtsiolis** [comment]
@easyCZ Let's go with a page size of 50 as we do with the usage page and adjust if needed.

💡 **tip**: There's already a pagination component ready to use, see [`components/src/Pagination`](https://github.com/gitpod-io/gitpod/tree/main/components/dashboard/src/Pagination) folder.

https://github.com/gitpod-io/gitpod/blob/77c68c720993e23df67a9abdaee3f5594b378e07/components/dashboard/src/Pagination/Pagination.tsx#L16
