### ISSUE TITLE
Reduce Regenerate Token UI density

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#15104]
<img width="483" alt="Screenshot 2022-12-01 at 14 13 00" src="https://user-images.githubusercontent.com/1419286/205062036-483a1723-1e4f-4f8d-a6bc-00ab73f40414.png">

The Rengerate Token UI looks a bit dense, especially around the volume of dates being shown. Cleaning up and breaking it up a bit could make it easier to visually grep.

CC @gtsiolis if you've got ideas what we could improve here. Also feel free to close if this is the intended UX

**Comment by gtsiolis** [comment]
That's the most UX nerdy issue title I've read in a while. Thanks for opening this, @easyCZ!

Yeah, simply using our spacing guidelines for separating form groups using `mt-4` could help.

For future reference, our spacing guidelines follow Tailwind's spacing scale. I'm posting below a screenshot from **Foundations / Spacing** in the component library in our Figma team.

| Spacing Guidelines |
|-|
| ![Spacing](https://user-images.githubusercontent.com/120486/205070541-e116ccfe-83d5-41c2-bbbf-f91726934e31.png) |

Posting a diff below, although I'm not sure if the code is correct:

```diff
diff --git a/components/dashboard/src/settings/PersonalAccessTokens.tsx b/components/dashboard/src/settings/PersonalAccessTokens.tsx
index ea391388d..97243dcb9 100644
--- a/components/dashboard/src/settings/PersonalAccessTokens.tsx
+++ b/components/dashboard/src/settings/PersonalAccessTokens.tsx
@@ -148,7 +148,7 @@ function ShowTokenModal(props: TokenModalProps) {
                     Expires on {dayjs(props.token.expirationTime!.toDate()).format("MMM D, YYYY")}
                 </div>
             </div>
-            <>
+            <div className="mt-4">
                 {props.showDateSelector && (
                     <DateSelector
                         title="Expiration Date"
@@ -165,7 +165,7 @@ function ShowTokenModal(props: TokenModalProps) {
                         }
                     />
                 )}
-            </>
+            </div>
         </Modal>
     );
 }
```

Here's how the design should be after this change:

| BEFORE | AFTER |
|-|-|
| <img width="536" alt="modal-before" src="https://user-images.githubusercontent.com/120486/205071027-2aca7750-c54e-44c1-840e-85925521b9ea.png"> | <img width="536" alt="modal-after" src="https://user-images.githubusercontent.com/120486/205071034-2c70d4d0-20b3-499b-814f-9e05c67eb7a6.png"> |

**Comment by gtsiolis** [comment]
Opened #15107 to resolve this.
