### ISSUE TITLE
[JetBrains] Avoid displaying "Connection Closed by Gateway" dialog if user clicks "Disconnect" button

### ISSUE THREAD

**Issue by felladrin** [gitpod-io/gitpod#15113]
## Description

Sometimes when clicking the "Disconnect" button in the Gateway connection dialog, we receive a "Connection Closed by Gateway" dialog. But this dialog should only be shown if the workspace abruptly loses connection, not when a user disconnects on purpose.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/418083/205092984-4e5f47bb-aaf1-4a8a-879d-4b9a897a639d.png">

<img width="416" alt="image" src="https://user-images.githubusercontent.com/418083/205057052-d20e68e3-cf15-412f-b7c4-cef3e2609764.png">

## How to reproduce

1. On a JetBrains IDE, click File >> Invalidate Caches... >> Just Restart
2. Gateway will try to reconnect but will fail because the access token has changed.
3. The connection dialog will remains there, so you click the "X" window-button.
4. The dialog asking if you want to hide the window or disconnect will show up.
5. Click "Disconnect" and notice the "Connection Closed by Gateway" dialog.

**Comment by loujaybee** [comment]
* **Question:** Does the current behaviour bring JetBrains Gateway back to the foreground (I think not currently)? 
* **Thought:** We should think about what is the most useful action that users want to take following closing / stopping workspaces - e.g. do they want to restart the workspace? See or starting new workspaces? Or do nothing (e.g. completely close session / stop working)?
