### ISSUE TITLE
OCI runtime create failed

### ISSUE THREAD

**Issue by domesticmouse** [gitpod-io/gitpod#1511]
Attempting to start https://gitpod.io/#https://github.com/domesticmouse/dart-services/tree/dart-29 results in the following error:

failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/theia/supervisor\": stat /theia/supervisor: no such file or directory": unknown

**Comment by Kreyren** [comment]
@domesticmouse The branch `dart-29` does not exists which results in this on my end:

![image](https://user-images.githubusercontent.com/11302521/82011629-d9583c80-9675-11ea-83bc-7b82746f2720.png)

**Comment by Kreyren** [comment]
> failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: "/theia/supervisor": stat /theia/supervisor: no such file or directory": unknown

This error is interesting though afaik it seems to state that gitpod was unable to deploy the supervisor which may be something related to deployment, but assuming that you are currently the only one who has this issue (and i can't reproduce it) then i assume that it's related to your configuration?

**Comment by Kreyren** [comment]
Relevant: https://github.com/gitpod-io/gitpod/issues/1513

**Comment by Kreyren** [comment]
CC @geropl @csweichel

**Comment by Kreyren** [comment]
Seems that this affects US cluster assuming that none seems to reported this happening outside of US and that i can't reproduce it in EU.

**Comment by Kreyren** [comment]
Relevant: https://github.com/gitpod-io/workspace-images/pull/180

**Comment by jankeromnes** [comment]
Hey everyone, sorry that this bug happened precisely as you're approaching deadlines! 😞

Should be resolved now: https://community.gitpod.io/t/i-cannot-start-my-workspace-again/1356/5

> The issue was that one of our servers in the US cluster started acting up, which seemed to be caused by a rare Google Cloud Kubernetes Engine bug that we’ve already reported with them earlier. For now, we’ve simply removed this server from our cluster, so you should no longer see this problem (i.e. you should be able to start your workspaces again just fine). Please let us know if that’s not the case.
> 
> We’ll ping Google Cloud support about this issue again, as it would be good to resolve this for good.

**Comment by Kreyren** [comment]
@jankeromnes Recommends processing https://github.com/gitpod-io/gitpod/issues/1496 assuming that US cluster seems to be too unstable for gitpod (Multiple shortages in a short period of time) to avoid fatal failures.

**Comment by RDIL** [comment]
Or maybe consider a different platform like Azure?

**Comment by Kreyren** [comment]
> Or maybe consider a different platform like Azure?

Because what could possibly go wrong on something maintained by Microsoft! :p

GKE is in my option the most efficient solution atm, but i would like to see a blockchain implementation.

**Comment by RDIL** [comment]
Because what could possibly go wrong on something maintained by Google! :p

**Comment by Kreyren** [comment]
@RDIL Way less assuming google being a (minor) contributor to linux, using custom sheduler designed for GKE that scales much better compared to M$ solutions, having a higher code quality standard and some of them helping to maintain Gentoo Linux.

**Comment by Kreyren** [comment]
@RDIL If you want to see code quality of microsoft in action :p

https://www.youtube.com/watch?v=5zMbfvEHlTU

**Comment by RDIL** [comment]
AWS then???

**Comment by Kreyren** [comment]
> AWS then??? @RDIL

I woudn't rely on it, but i consider it being somewhat usable.. If i would be the one making the decision where blockchain and other (possibly better alternatives) are not an option, then i would use 85% GKE and 10% AWS (with option to be available to up to 100% on demand) and adjusted them based on runtime with sanity checks multiple times a day.
