### ISSUE TITLE
JDK 8 not being auto-selected as Project-Level SDK on Jetbrains IDE

### ISSUE THREAD

**Issue by fcamblor** [gitpod-io/gitpod#15114]
### Bug description

[As discussed on Discord](https://discord.com/channels/816244985187008514/1047519405451530272/1047519408010039347) I'm encountering problem while trying to pre-select something different than te default Project-Level SDK (`JDK 11` on Intellij 2022.2.4)

Got help from @felladrin who suggested to create this issue, telling that the problem may be located [around here](https://github.com/gitpod-io/gitpod/blob/83740996d0c376cea6f530d1703fbab0de4de36d/components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodProjectManager.kt#L47-L63)

### Steps to reproduce

You can start a gitpod instance with JDK pre-installed : 
```
FROM gitpod/workspace-full

USER gitpod

RUN bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh && \
    sdk install java 8.0.352-zulu && \
    sdk default java 8.0.352-zulu"

ENV IDEA_JDK /home/gitpod/.sdkman/candidates/java/current
ENV JAVA_HOME /home/gitpod/.sdkman/candidates/java/current
```

But Project-level JDK remains with pre-bundled JDK 11 : 
![image](https://user-images.githubusercontent.com/603815/205145260-ae785ed3-70a4-40c9-91c2-82747381a873.png)
![image](https://user-images.githubusercontent.com/603815/205145279-1f4dc6c6-4755-479c-942b-a713589fc850.png)

### Expected behavior

I would expect that Project-Level JDK should be set to globally-configured JDK (in case above, JDK 8)

### Example repository

```
FROM gitpod/workspace-full

USER gitpod

RUN bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh && \
    sdk install java 8.0.352-zulu && \
    sdk default java 8.0.352-zulu"

ENV IDEA_JDK /home/gitpod/.sdkman/candidates/java/current
ENV JAVA_HOME /home/gitpod/.sdkman/candidates/java/current
```

### Anything else?

It could be related to a Jetbrains issue [here](https://youtrack.jetbrains.com/issue/IDEA-227935/JDK-Detector-improvements) regarding JDK Detector.

**Comment by loujaybee** [comment]
When we resolve the issue, we should also update docs on how to override / set the default version for a project. 

https://www.gitpod.io/docs/introduction/languages/java#updating-java-maven--gradle
https://www.gitpod.io/docs/references/ides-and-editors/intellij

**Comment by akosyakov** [comment]
@fcamblor IntelliJ detects JDK version form maven or gradle configuration and try to find the compatible one, i.e. if pom.xml has java 11 set then even if default JDK is 8, IntelliJ will pick the highest closest (i.e. compatible). 

Could you check what your project has specified in source/target level in pom.xml or gradle.build?

**Comment by fcamblor** [comment]
Hello @akosyakov,

I'm not using maven nor gradle in my case, this is a Scala project which relies on sbt.
I'm not an expert on this field, but I don't see where the Java version is specified [in the sbt build file](https://github.com/fcamblor/cfp-devoxx/blob/gitpod-support/build.sbt) (I can only see that a Scala version is enforced, nothing more)

**Comment by akosyakov** [comment]
We reverted the custom JDK detection logic to use one from IntelliJ itself, but it behaves the same way. Here is an issue in the upstream: https://youtrack.jetbrains.com/issue/GTW-2758/IntelliJ-selects-Java-17-when-pom.xml-targets-Java-11-without-.idea-folder

**Comment by andreafalzetti** [comment]
@fcamblor our `workspace-full` image comes with both Java 11 and Java 17. We also have [dedicated](https://github.com/gitpod-io/workspace-images/#-specific-images) Java images for 11 and 17, but not one for 8.

I would recommend removing the versions you don't need and by doing that, IntelliJ will pick up the right JDK.

```
FROM gitpod/workspace-full:2022-12-15-12-38-23

USER gitpod

RUN bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh && \
    sdk uninstall java 17.0.5.fx-zulu && \
    sdk uninstall java 11.0.17.fx-zulu && \
    sdk install java 8.0.352-zulu && \
    sdk default java 8.0.352-zulu"
```

Note: I've pinned the image to the most recent tag `2022-12-15-12-38-23` this will prevent your image to change in case we update and in the future install additional versions of Java

![Screenshot 2022-12-20 at 11 21 25](https://user-images.githubusercontent.com/2318450/208655273-ba01f0c4-66aa-4d99-bd18-9951bb872367.png)

**Comment by felladrin** [comment]
@fcamblor, did you have a chance to try the solution mentioned above by Andrea?

**Comment by fcamblor** [comment]
Sorry, it got out of my radar.

I've just launched a re-build of my particular Scala workspace to check it.
I will keep you posted (it can take a few dozen of minutes to complete, as it seems my docker build cache as disappeared and I'm going to need to download the whole internet again to build my SBT dependencies cache :-))

**Comment by fcamblor** [comment]
It took some time, but it doesn't look like uninstalling sdkman's jdk 11 & 17 changed anything for my setup, except that the default project SDK is not found at project startup : 
<img width="1025" alt="Cursor_and_Project_Structure_and_cfp-devoxx" src="https://user-images.githubusercontent.com/603815/212389972-da5eb47b-1b9f-4e6e-850c-c612f03eab7f.png">

<img width="1019" alt="Cursor_and_Project_Structure" src="https://user-images.githubusercontent.com/603815/212390086-5a0deb1e-4f3b-46e8-83a0-ce56efe0b1e7.png">

I used latest workspace-full image available (`gitpod/workspace-full:2023-01-10-16-35-53`)

**Comment by fcamblor** [comment]
Forget, this is my bad, I just discovered that during my test above, I had a `.gitpod/jetbrains/options/jdk.table.xml` which was targetting old JDK 11/17

I updated the file and this time, it worked fine ! :-)
<img width="1020" alt="Cursor_and_Project_Structure" src="https://user-images.githubusercontent.com/603815/212394642-a8b3c935-825a-4863-9dcd-22edb9beb85e.png">
