### ISSUE TITLE
Ensure node labels for shared components are used in meta and workspace clusters

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#15131]
### Bug description

`gitpod.io/workload_services`  and `gitpod.io/workload_workspace_services` are used in the codebase and also cluster add-ons manifest.

We should unify that and use only one form, `gitpod.io/workload_services`; that way, we can reuse k8s manifests and simplify the maintenance.

**Comment by corneliusludmann** [comment]
Pull request #15132 has a fix. However, before we can merge this, we need to make sure that we do not break gitpod.io prod (we need to adjust the workspace labels in the ops repo).

See also: https://github.com/gitpod-io/gitpod/pull/15132#issuecomment-1335840075
