### ISSUE TITLE
Reliable certs for preview envs via certbot

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#15146]
## Is your feature request related to a problem? Please describe
We currently use Certmanager to obtain certificates from ZeroSSL and Letzencrypt for preview environments. Unfortunately, obtaining certs still fails too often.

It seems that Certmanager is not the best tool for our use cases because:
* The retry logic of Certmanager "If an issuance fails because of a temporary error, it will be retried again with a short exponential backoff (currently 5 seconds to 5 minutes). A temporary error does not result in a failed CertificateRequest." ([src](https://cert-manager.io/docs/faq/#what-happens-if-issuance-fails-will-it-be-retried)) is not what we want. We want an immediate retry.
* Certmanager seems to support only one ClusterIssuer per Certificate. For us, however, it would be super helpful if we could have automated failover: If obtaining the cert with ZeroSSL does not work, automatically retry with LetsEncrypt. 
* The killer feature of cert-manager (automated certificate renewal) is something we don't need because preview envs don't live that long.
* Certificate issues are rather hard to debug because Certmanager runs as k8s controller. 

## Describe the behaviour you'd like

Use `certbot` instead of Certmanager to obtain certs. 
* [Here are docs for how to use it for Gitpod self-hosted](https://github.com/gitpod-io/retired-gatsby-website/blob/4a9d59572cfdaf2eb24aea308751dcffc5772094/src/docs/self-hosted/0.3.0/install/https-certs.md#using-lets-encrypt).
* [It's officially supported by ZeroSSL, too.](https://github.com/zerossl/zerossl-bot)

instead of creating a Certificate-CR for cert-manager, we could run a script that looks something like this:
```
for (i=0;i<50; i++) {
    certbot zerossl;
    if(has_cert) return;
    certbot letsecnrypt;
    if(has_cert) return;  
}
```

A nice side-effect of this change is reducing the dependencies on the "dev" cluster. 

Open questions:
* when/how to run this script? As part of Terraform? As part of Gitpod-Install? A year back, we aimed to run this in parallel to Terraform, not to have the few minutes it takes to get certs added to the critical path. 
* How to cache certs? Will it be enough to not re-request the cert if it is available in the VM? Do we want to cache outside the VM? In the past, we did this to avoid running into the LetsEncrypt rate limit.

**Comment by kylos101** [comment]
:wave: hi Mads, can you help update the [debugging cert issues](https://www.notion.so/Debugging-certificate-issues-9453d1c8ac914ce7962557b67f7b49b3?d=6d6a71c665664f56bf8bcc1888bcf28d) page? I bumped into some issues today, which is blocking our testing for this week's deployment (a small, low risk changeset which I'd prefer to ship, so January's aren't this much larger).

**Comment by mads-hartmann** [comment]
@kylos101 I updated it to specify the correct kubectx to use, but nothing about this has changed, so the docs were just a bit unclear ☺️  once this PR lands it will have to be rewrite that doc completely as we'll not be using CertManger anymore ☺️

**Comment by mads-hartmann** [comment]
I'm keeping this open as there's still clean up to do:

- Delete the cluster issuers from core-dev
- Delete cert manager in core-dev
- Update [Debugging certificate issues](https://www.notion.so/gitpod/Debugging-certificate-issues-9453d1c8ac914ce7962557b67f7b49b3) as the existing instructions are for CertManager

👆 We can't delete CertManager in core-dev until everyone is rebased on main etc. so I think it makes sense to wait a week or so before doing the cleanup - that also means we have to ability to revert if I broke anything ☺️

**Comment by mads-hartmann** [comment]
Updated the [debugging docs](https://www.notion.so/gitpod/Debugging-certificate-issues-9453d1c8ac914ce7962557b67f7b49b3) so I'm closing this.
