### ISSUE TITLE
[public-api] implement CreateOIDCProviderConfig

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#15150]
Part of Epic: Single sign-on (SSO) #7761
Depending on https://github.com/gitpod-io/gitpod/pull/15149

* add a new DB table to store OIDC provider configs ✔️ 
* add a DB model in ~`public-api-server/pkg/db`~ ✔️ 
* add an implementation for `CreateOIDCProviderConfig` ✔️ 
* ~guard this service by checking for admin role (TBD)~ that's obsolete by the decision to associate with org/team, thus check could be part of https://github.com/gitpod-io/gitpod/issues/15708

**Comment by AlexTugarev** [comment]
@easyCZ, can we close this as done, no?

**Comment by easyCZ** [comment]
It's implemented on IAM, not on public api
