### ISSUE TITLE
[GitLab] Docker file is not picked up from subfolder

### ISSUE THREAD

**Issue by peet86** [gitpod-io/gitpod#1516]
### Describe the bug
Docker file is not picked up from subfolder. 
Error message: "Dockerfile 'subfolder/.gitpod.dockerfile' does not exist"
Only Gitlab repos are affected, works with Github. 

### Steps to reproduce
Create .gitpod.yml with 
```
image:
  file: subfolder/.gitpod.dockerfile
```

### Expected behavior
Works just like with Github.

### Additional information
I've double checked the Gitlab permissions, tried to rename / move around the dockerfile. 
Only works if it's in the repo's root dir.

Maybe related to #1161

**Comment by Kreyren** [comment]
cc @jankeromnes
