### ISSUE TITLE
Gitpod loading screen causes 100% GPU load in chrome

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#15169]
### Bug description

Whenever I am on gitpod screen that has an animated gitpod icon moving up and down, my GPU process in chrome goes to 100% cpu use and my laptops fan goes into overdrive mode.
It only happens on screen where we have gitpod icon moving up and down, example:
![image](https://user-images.githubusercontent.com/18602811/205750363-af010225-be19-4f59-b271-183c2955430b.png)

### Steps to reproduce

open new workspace in chrome and open task manager in chrome, observe gpu process using 100% cpu.

### Anything else?

Chrome version: Version 108.0.5359.71 (Official Build) (64-bit)
Linux: 6.0.6-76060006-generic

**Comment by AlexTugarev** [comment]
@sagor999, please retest for workspace start not including an image build. I suspect the terminal rendering being responsible for high GPU load. 

The logo is a SVG and uses CSS animation. It'd be worth checking with the example page as well https://tailwindcss.com/docs/animation.

**Comment by AlexTugarev** [comment]
@geropl is a Linux user well, right? Maybe that's a known issue 🤷🏻‍♂️

**Comment by sagor999** [comment]
Closing as it actually stopped happening for me (after chrome update). :shrug:
