### ISSUE TITLE
[UBP] Replace "pay-as-you-go billing" with "billing" in personal and team billing settings

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15160]
The extra qualification of "pay-as-you-go billing" for billing pages in the dashboard is unnecessary, since this is the only type of billing available.

Suggest: "Manage billing for your Gitpod user account."

<img width="1099" alt="Screenshot 2022-12-05 at 12 56 09" src="https://user-images.githubusercontent.com/849592/205649723-f7d07d44-5056-40ce-b93e-eb12fa474a23.png">

---
Suggest: "Manage billing for your Gitpod team."

![Screenshot 2022-12-05 at 13 24 30](https://user-images.githubusercontent.com/849592/205649830-9c34fd68-45a8-4052-a76e-0a9b3ff2050b.png)

cc: @gtsiolis

**Comment by gtsiolis** [comment]
@jldec Would it make sense to go with something like the following to differentiate the team billing from the personal billing?

> Manage billing and usage limit for your team billing.

> Manage billing and usage limit for your personal billing.

This could provide a subtle hint to help users associate this page better with their personal account sometimes (see https://github.com/gitpod-io/gitpod/issues/15012), etc. and help us avoid having specific page titles like we do with the usage page.
