### ISSUE TITLE
python version change 

### ISSUE THREAD

**Issue by geet2019** [gitpod-io/gitpod#1518]
case 1 :
Unknown option: --
usage: /home/gitpod/.pyenv/versions/2.7.17/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information. 
Need: python3 
I am trying to execute deepmind_research/alphafold_casp13 in gitpod .  I need to execute it in python 3.6+ .Is it possible?. how ?

case 2 : recurrent geometric network 

I need python 2.7.17 but executing in 3.8.2 
how can I change it and

**Comment by jankeromnes** [comment]
Hi @geet2019,

Gitpod workspaces come with both Python 2 and Python 3 installed via [Pyenv](https://github.com/pyenv/pyenv).

You can specify which version of Python you want to be default via the `pyenv` CLI tool, e.g. by doing:

```
pyenv local 3.8.2
```

This will create a `.python-version` file which controls what is the default Python version in the current directory (so you can have different Python versions in different directories).

You can then commit the `.python-version` file to your repository.

Also, you can see exactly which Python versions are available by running:

```
pyenv versions
```

**Comment by jankeromnes** [comment]
Alternatively, you can also use the explicit aliases `python3` and `python2` in your Terminal without having to configure anything.

**Comment by geet2019** [comment]
thank you

**Comment by geet2019** [comment]
gitpod /workspace/rgn $ pyenv local 2.7.17
gitpod /workspace/rgn $ python --version
Python 3.8.2

**Comment by geet2019** [comment]
gitpod /workspace/rgn $ pyenv local 2.7.17
gitpod /workspace/rgn $ python --version
Python 3.8.2


Regards
Geethu S

**Comment by jankeromnes** [comment]
@geet2019 Oops, sorry about that.

What does `pyenv versions` give you?
