### ISSUE TITLE
[UBP] Improve "pay-wall"

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#15188]
When I run out of credits and want to start a workspace I currently see, the error below. This is not helpful as it doesn't tell me how I can get more credits.
<img width="402" alt="Screenshot 2022-12-06 at 14 47 36" src="https://user-images.githubusercontent.com/372735/205929561-77d535bf-223b-4549-a824-87eac1a31fee.png">

**Comment by svenefftinge** [comment]
Maybe at least be consistent and show the same message with the same link we do here:

<img width="1335" alt="Screenshot 2022-12-06 at 14 51 35" src="https://user-images.githubusercontent.com/372735/205930279-fdd66ecc-6519-4c22-ad59-dc6a66164d9e.png">

**Comment by gtsiolis** [comment]
Currently the blocking step (paywall) when trying to open a new workspace is using a design added in https://github.com/gitpod-io/gitpod/pull/11576 and updated in https://github.com/gitpod-io/gitpod/pull/12096, see https://github.com/gitpod-io/gitpod/pull/12096#issuecomment-1220832316. Ideally, these two cases would share the same UX.

| Paywall when opening a new workspace | Paywall when opening an existing (stopped) workspace |
|-|-|
| <img width="1440" alt="Screenshot 2022-12-06 at 6 15 08 PM (2)" src="https://user-images.githubusercontent.com/120486/205965223-2b9c1b98-755b-4c23-96e3-4188f3f6b369.png"> | <img width="1440" alt="Screenshot 2022-12-06 at 6 16 00 PM (2)" src="https://user-images.githubusercontent.com/120486/205965243-2ac80ca8-72cd-40c6-aa7b-2b0310968445.png"> |

**Comment by svenefftinge** [comment]
Also the "Go to Dashboard" should be "Go to Billing"
