### ISSUE TITLE
Connecting to GitLab.com with OAuth for the GitLab Workflow extension from VS Code (Browser) does not work

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15186]
### Bug description

Can not connect with GitLab.com for the GitLab Workflow extension from VS Code (Browser) in Gitpod.

Manually adding an account using a personal access token (PAT) still works ok.

### Steps to reproduce

1. Open a new workspace.
2. Install the **[GitLab Workflow](https://open-vsx.org/extension/GitLab/gitlab-workflow)** extension.
3. Click on the GitLab Workflow extension icon in the activity bar.
4. Click on the Connect to GitLab.com with OAuth button in the activity bar, see screenshot below.
5. Notice how GitLab.com returns an error, see screenshot below.

| Extension in VS Code (Browser) | Error on GitLab.com |
|-|-|
| <img width="1440" alt="Screenshot 2022-12-06 at 3 08 56 PM (2)" src="https://user-images.githubusercontent.com/120486/205921252-15baf032-540a-4e13-9f09-c76f69de1917.png"> | <img width="1440" alt="Screenshot 2022-12-06 at 3 09 06 PM (2)" src="https://user-images.githubusercontent.com/120486/205921262-93a404c4-01af-4eff-9885-92c2f239e4ec.png"> |

**Comment by filiptronicek** [comment]
The problem boils down to the fact that the extension expects you to do this process on the desktop, where the `redirect_uri` is of protocol `vscode://`, `vscode-insiders://`, `vscodium://` or similar. The redirect URI `gitpod-code://gitlab.gitlab-workflow/authentication` will therefore not work.

Some code pointers:
- https://github.com/microsoft/vscode/blob/416349361135f390bc49dee70916bcbe277beb5c/extensions/github-authentication/src/githubServer.ts#L93-L98 -- how GitHub Auth is done
- https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/blob/main/src/accounts/oauth/gitlab_authentication_provider.ts#L52-66 -- how the GitLab extension does it

**Comment by jeanp413** [comment]
I see, but it's not about the extension is about their server, they have some filtering same as we have an only allow vscode stable/insiders and vscodium

**Comment by filiptronicek** [comment]
> @jeanp413 is about their server

Yes, but even if they added it to the protocols, it wouldn't help it to work, so it's not necessary

**Comment by jeanp413** [comment]
> Yes, but even if they added it to the protocols, it wouldn't help it to work, so it's not necessary

why it wouldn't work? gitpod code supports callback uris

**Comment by jeanp413** [comment]
I think we can close this @gtsiolis, we can report this two issues to gitlab
- whitelist url callbacks so it works on web
- use `vscode.env.asExternalUri` api in their extension

**Comment by gtsiolis** [comment]
Thanks for investigating, @filiptronicek and @jeanp413! 🏀 

Let's close this—I've opened https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/issues/700 to keep track of this and looped in a few people to help bring this to GitLab's radar.
