### ISSUE TITLE
cannot initialize workspace

### ISSUE THREAD

**Issue by Adonisbruno** [gitpod-io/gitpod#1519]

**Comment by Kreyren** [comment]
Is this still an issue? If so elaborate on the error message (if any) or provide more informations

**Comment by aticodein** [comment]
Hi, can not load gitpd workspace!

![image](https://user-images.githubusercontent.com/45002010/82126095-4b2da480-97a2-11ea-9a8c-f7a7e4bd2697.png)

**Comment by Kreyren** [comment]
@aticodein Stopped seems to indicate the workspace being stopped from `gitpod.io/workspaces` or you caught it while it was terminating after a timeout (Workspace stay opened for up to 4 hours).

Were you able to reproduce the issue?

**Comment by Kreyren** [comment]
@Adonisbruno 

Feel free to use your native language. If you have problems with english.

Sinta-se livre para usar seu idioma nativo. Se você tiver problemas com o inglês

Siéntase libre de usar su idioma nativo. Si tienes problemas con el inglés.

**Comment by Adonisbruno** [comment]
@Kreyren 
He opened this topic without me seeing it.
I gave up using the tool, it doesn't open.
I'm using offline compilers/interpreters myself.

I'm closing this.

**Comment by Kreyren** [comment]
@Adonisbruno Sorry to hear that, but fwiw it seems like a pebcak using malformed context url.
