### ISSUE TITLE
Activity Timeout metrics

### ISSUE THREAD

**Issue by CTParkinson** [gitpod-io/gitpod#15217]
## Is your feature request related to a problem? Please describe
I am currently working on a companion app for a project developed via use of gitpod.

I'm running into an issue where when working in the app I hit the 30 minute activity timeout and my app loses contact with the backend hosted in the gitpod workspace.

## Describe the behaviour you'd like
It would be nice to have some other things trigger the activity so that I can stop having to restart the workspace each time it stops as I'm active in another part of this project, but not directly in the IDE for the workspace.

## Additional context
After a brief discussion on discord, and as I assumed, network activity is not ideal for the timeout deference admit can be easily abused, but the exposed ports are the only thing in use as I'm working in the companion app.

It's getting increasingly frustrating to see the app stop responding, due to no response from the workspace as it has timed out.
Switch to the workspace and wait for it to stop, then restart it and continue in the app once the workspace has been set up again...

**Comment by axonasif** [comment]
Duplicate of a duplicate 😜 
- https://github.com/gitpod-io/gitpod/issues/13498
