### ISSUE TITLE
[ubp] cannot see "Plan" although a plan is active

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#15219]
If i have subscribed to a paid plan on chargebee but am eligible for UBP, I can no longer see the "/plan"  in the settings (to cancel)

**Comment by geropl** [comment]
@svenefftinge Sounds like it could be a simple dashboard check gone missing. If not, happy to help out. :100:

**Comment by svenefftinge** [comment]
Strange, maybe that was a race or so. I cannot reproduce anymore.
