### ISSUE TITLE
[UBP] Cannot signup with stripe

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#15211]
I get the following error message when entering credit card details:
<img width="530" alt="Screenshot 2022-12-07 at 14 03 52" src="https://user-images.githubusercontent.com/372735/206187003-a4a90a08-dbef-425c-92ad-eae65e50f77e.png">

**Comment by jldec** [comment]
I believe this may be because we did not migrate existing cost centers after #14041

**Comment by AlexTugarev** [comment]
@jldec, that correct.
