### ISSUE TITLE
[Pay-as-you-go] Enable access to Stripe portal after paid users cancel 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15236]
After pay-as-you-go customers cancel, they should be able to go back to their Stripe portal to access earlier invoices.

**Comment by svenefftinge** [comment]
I think it makes sense to keep the Stripe portal link on the /billing page independent of the subscription status.

**Comment by gtsiolis** [comment]
> I think it makes sense to keep the Stripe portal link on the /billing page independent of the subscription status.

Sounds like a good [skateboard](https://www.notion.so/gitpod/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e#0c2e0d6c8a99404b97ccdc206b573d72) before surfacing invoices on our dashboard if this is something we'd like to do in the future.

A good MVC for this could be to :a: keep the link to Stripe as a secondary button to _View Invoices_ and :b: rename the _Upgrade Plan_ button to _Resume Plan_ when a teams cancels their plan. This would also avoid asking again for a credit card (payment method) when and if a teams wants to resume their plan and avoid storing duplicate entries of credit cards when doing so.

| Resume Plan & View Invoices | Duplicated Payment Methods |
|-|-|
| <img width="321" alt="Screenshot 2022-12-08 at 1 16 01 PM (2)" src="https://user-images.githubusercontent.com/120486/206433456-ac9598b7-d35c-426a-a17a-5f3e174e4e6e.png">|  <img width="587" alt="Screenshot 2022-12-08 at 1 13 10 PM (2)" src="https://user-images.githubusercontent.com/120486/206433467-718b60c5-31c2-42fc-9cb8-26005a1bb2a8.png"> |

**Comment by jankeromnes** [comment]
Thanks @svenefftinge for opening https://github.com/gitpod-io/gitpod/pull/15375!

I'll assign you to this issue, but please feel free to change this if you're no longer working on this. 😁
