### ISSUE TITLE
run deepmind/alphafold_casp13 - work to predict 3 d protein structure in gitpod 

### ISSUE THREAD

**Issue by geet2019** [gitpod-io/gitpod#1523]
this is the link to the file:  https://github.com/geet2019/deepmind-research/tree/master/alphafold_casp13 how can I download the dataset and where I can save it.

https://github.com/geet2019/deepmind-research/blob/master/alphafold_casp13/run_eval.sh

# Run contact prediction over 4 replicas.
for replica in 0 1 2 3; do
  echo "Launching all models for replica ${replica}"
I tried to run these commands from the shell is it possible to do so.

 # Run the distogram model.
  python3 -m alphafold_casp13.contacts \
    --logtostderr \
    --cpu=true \
    --config_path="${DISTOGRAM_MODEL}/${replica}/config.json" \
    --checkpoint_path="${DISTOGRAM_MODEL}/${replica}/tf_graph_data/tf_graph_data.ckpt" \
    --output_path="${OUTPUT_DIR}/distogram/${replica}" \
    --eval_sstable="${TARGET_PATH}/${TARGET}.tfrec" \
    --stats_file="${DISTOGRAM_MODEL}/stats_train_s35.json" &

WHERE I CAN SEE THE OUTPUT:- 
WHERE  I NEED TO EXECUTE IT:- 
WHEN I AM TRYING TO EXECUTE EACH.PY EXTENSION SEPARATELY. IT IS ASKING FOR SEPARATE INSTALLATION FOR PACKAGES EVEN THOUGH IT INSTALL THOSE PACKAGES IT IS NOT WORKING WHY? HOW CAN I RESOLVE IT

**Comment by Kreyren** [comment]
From a quick look i would start by opening https://gitpod.io/#https://github.com/geet2019/deepmind-research/tree/master/alphafold_casp13 and then executing your expected payload there?

also FWIW this https://github.com/geet2019/deepmind-research/blob/master/alphafold_casp13/run_eval.sh seems as shell malware assuming lack of quality assurance as shown on https://shellcheck.net/?id=cb87671 and manipulation with `eval`, see https://mywiki.wooledge.org/BashFAQ/048
