### ISSUE TITLE
Please support granting additional credits to Open Source teams

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#15238]
## Is your feature request related to a problem? Please describe

- Gitpod currently sponsors professional Open Source developers with additional resources

- Our new pricing allows granting individuals 2500 credits / month instead of the usual 500 credits / month

- Another option could be to grant a Team a higher credits / month limit (instead of manually granting them for every single member separately)

## Describe the behaviour you'd like

1. In Admin, select an open source Team to sponsor, and set a custom usage limit (e.g. to 2500 credits * number of members)

## Additional context

Note: This is already implemented and almost works -- however, it seems that Gitpod refuses to set the custom limit, because it still expects a paid Stripe subscription to exist:

<img width="1438" alt="Screenshot 2022-12-08 at 11 04 37" src="https://user-images.githubusercontent.com/599268/206420863-01e84063-daed-4668-bcc8-f57e93c812f2.png">

**Comment by jankeromnes** [comment]
Side note: A temporary workaround is to grant a Team a one-time bonus of credits, instead of raising the monthly limit.

**Comment by ghuntley** [comment]
> granting additional credits to Open Source teams
👆 🆙🆙🆙

**Comment by svenefftinge** [comment]
I cannot reproduce the issue. It is probably solved with https://github.com/gitpod-io/gitpod/pull/15159
