### ISSUE TITLE
how to handle gitpod?

### ISSUE THREAD

**Issue by geet2019** [gitpod-io/gitpod#1524]
Run: https://c61e69b7-f35b-4d89-840e-bea4011b35ad.ws-us02.gitpod.io/#/workspace/rgn in gitpod 
 Installation and requirements
Extract all files in the [model](https://github.com/aqlaboratory/rgn/tree/master/model) directory in a single location and use `protling.py`, described further below, to train new models and predict structures. Below are the language requirements and package dependencies:

* Python 2.7
* TensorFlow >= 1.4 (tested up to 1.12)
* setproctitle   [DONE]

gitpod /workspace/rgn/model $ python protling.py
usage: protling.py [-h] [-d BASE_DIRECTORY] [-p] [-e EVALUATION_MODEL]
                   [-m MILESTONE] [-r] [-R] [-c] [-s SEED_INCREMENT] [-g GPU]
                   [-a | -f GPU_FRACTION]
                   config_file
protling.py: error: too few arguments
how can I resolve this ?

what about the dataset ? where to download ? from where I can see the output ? do I need to run each file separtely using greeen colour arrow key right top corner of .py files . 

this is a work done by someone else .I just wanted to run it and check how it work . start by work too

**Comment by jankeromnes** [comment]
Hey @geet2019, thanks for this question. Note that this issue should probably be opened in https://github.com/aqlaboratory/rgn/issues instead.

https://github.com/aqlaboratory/rgn#train-a-new-model-or-continue-training-an-existing-model says to run:

```
python protling.py <configurationFilePath> -d <baseDirectory>
```

So you actually need to provide a configuration file path, and a base directory. Just running `python protling.py` is not enough.

For further questions, please ask in https://github.com/aqlaboratory/rgn/issues 🙂

**Comment by geet2019** [comment]
ok thank you so much
