### ISSUE TITLE
Can not pull my github repository

### ISSUE THREAD

**Issue by Anson-Zhao** [gitpod-io/gitpod#1526]

**Comment by Anson-Zhao** [comment]
login to my github, by "https://gitpod.io/#https://github.com/Anson-Zhao". And then I got a button to let me login with github. I clicked, and then I got the error message like attachment.
![screenshot-gitpod io-2020 05 17-21_26_51](https://user-images.githubusercontent.com/22801720/82166049-3e35b180-9885-11ea-877d-29489378fdf1.png)

**Comment by Kreyren** [comment]
> y "gitpod.io/#https://github.com/Anson-Zhao". 

This is miss-used since you are pointing context url to your github profile :p -> You need to point to the repository for gitpod to open i.e https://gitpod.io/#https://github.com/Anson-Zhao/WebWorldWind
