### ISSUE TITLE
Show enable prebuilds checkbox on new project creation

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15281]
Many projects do not need a prebuild, so running one when a new project is created, is confusing / surprising for users.

Also, the usage-collection for this prebuild is not working.

**Comment by jankeromnes** [comment]
> Many projects do not need a prebuild, so running one when a new project is created, is confusing / surprising for users.

Note: Running a first prebuild is currently the "trick" we use to "enable" prebuilds (i.e. a manually triggered prebuild will also install a webhook for future prebuilds to be run).

If we don't trigger a first prebuild, we will no longer enable prebuilds by default for each project (potentially surprising too? E.g. create a project, commit a .gitpod.yml with an init task... then still no prebuilds? 😳) -- the only way to "enable" prebuilds will then be for the user to click on a "Run Prebuild" button manually.

Also, do we want a way to "disable prebuilds" if you no longer need them?

> Also, the usage-collection for this prebuild is not working.

This sounds like a separate bug that should also be fixed.

**Comment by svenefftinge** [comment]
I think it would be good to ask the user to enable prebuilds (checkbox?) while creating the project. Also in the settings it would be great to be able to disable prebuilds which turns the entire prebuilds section disabled or folded. We could use this for the automatic disabling as well, so that users can enable manually again.

**Comment by geropl** [comment]
Dropped @jankeromnes as he's off, so we need to find some else to progress it.
