### ISSUE TITLE
Estimate team usage based on members' recent usage

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15283]
Team owners need help to estimate team usage when they consider upgrading their teams to pay-as-you-go pricing.

#### 🛹 proposal
For teams without billing, add a section to team billing settings to show a summary of current team members' actual usage. The summary could be generated on demand by clicking a link instead of showing automatically for all teams, which might be slow or expensive.

![Screenshot 2022-12-10 at 14 13 17](https://user-images.githubusercontent.com/849592/206859702-c53971b8-e2fe-4ac9-8687-482408680e37.png)

**Comment by svenefftinge** [comment]
I'd prefer to show general data, where we simply multiply number of users with average usage of an active user. This would work for teams without previous usage and also not use data that doesn't belong to the team (who knows if a user is running an open-source project with heavy prebuilds).
