### ISSUE TITLE
Start workspace with workspace class override

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15287]
This is a followup to #15080

Gitpod users should be able to override the workspace class (determined globally or in project settings.) E.g. when opening a workspace on a repo which does not have a Gitpod project.

####  🛹 ideas
 
1. URL parameter for prefixed URLs E.g. `gitpod.io/#<<<REPO-URL>>>&gitpod-workspace-class=large`
2. Detect key to Interrupt workspace start page, then offer UI with choice of workspace classes
3. Extend the UI for Cmd-O in dashboard to offer choice of workspace classes

cc: @gtsiolis @atduarte

**Comment by svenefftinge** [comment]
@gtsiolis we would need to work on a design for the "Start with options" screen. It should be extendable to optionally also allow other choices in the future (IDE, ENV VARS, etc.)

**Comment by atduarte** [comment]
FYI there's already a URL kind-of-parameter implementation to select JetBrains IDEs https://github.com/gitpod-io/gitpod/blob/96a78364622d5dbb75801df40620046e03aeeebf/components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodStartWorkspaceView.kt#L79

**Comment by svenefftinge** [comment]
@gtsiolis and me worked on this and would like to approach it as follows:

We replace/extend the current open workspace modal to allow selecting:
- context URL
- the IDE
- workspace class

(we can later add additional things, such as e.g. environment variables)

The modal is triggerable and pre-fillable using a query param. If no arguments are provided the context URL must be chosen (using the search we have now). The other two args will be set to what the defaults are for the given context URL (i.e. if I pick a context URL on a project that is set to use large workspaces, large workspace class is pre-selected, if I have IntelliJ as my default IDE, it is preselected as well).

The model will be embedded in `https://gitpod.io/new` (new project should be moved to `gitpod.io/projects/new`).

We should allow using these options on restarts of workspaces as well, where the properties are preselected from the last workspace instance.

George is going to provide some UI designs.

**Comment by gtsiolis** [comment]
Posting below some designs after discussing with @svenefftinge:

| Open in Gitpod |
|-|
| <img width="3636" alt="Open" src="https://user-images.githubusercontent.com/120486/208436294-1ceb8a2c-d177-4260-a883-2082f6457a4e.png"> |
