### ISSUE TITLE
Publish kots: Field 'Config.ObjectStorage.S3.BucketName' is required

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/gitpod#15294]
Something seems to be off with the "publish kots" part of our build on main which means we're posting a lot of error messages to #product-engineering ([example](https://gitpod.slack.com/archives/C01KGM9AW4W/p1670831438183049)).  

```
STDERR: {
  "valid": false,
  "fatal": [
    "Field 'Config.ObjectStorage.S3.BucketName' is required"
  ]
}
configuration is invalid
```

Example [job](https://werft.gitpod-dev.com/job/gitpod-build-main.5956)

**Comment by mrsimonemms** [comment]
Looks like this was introduced by #14970
