### ISSUE TITLE
Make packages available on public repositories 

### ISSUE THREAD

**Issue by kushal-ti** [gitpod-io/gitpod#15293]
## Is your feature request related to a problem? Please describe
Currently, certain packages of the gitpod code base are published on private npm repositories (such as @gitpod/gitpod-payment-endpoint). These libraries were previously licensed as enterprise code, but with the recent move [away from self hosted](https://www.gitpod.io/blog/introducing-gitpod-dedicated), all of the code has been licensed as AGPL in the latest versions
 
## Describe the behaviour you'd like
Ideally, the packages/components that were previously enterprise license, such as [gitpod-payment-endpoint](https://github.com/gitpod-io/gitpod/tree/main/components/ee/payment-endpoint) should be published to public repositories (npm in this case)

## Describe alternatives you've considered
A possible alternative that was considered was that we would use the existing source code, build it ourselves and publish the package in a different name, however, it would be better for the community at large to simple publish these packages from the gitpod source code itself, which would allow the packages to be updated and in sync with the gitpod codebase.

## Additional context
Ideally, just removing the 
```json
{"private": true}
```
from the package.json should be enough to allow publishing the package to the public npm/yarn registries
As far as i'm aware, currently the following components are packaged as private 
[content-service-api](https://github.com/gitpod-io/gitpod/tree/main/components/content-service-api/typescript)
[dashboard](https://github.com/gitpod-io/gitpod/tree/main/components/dashboard)
[db-sync](https://github.com/gitpod-io/gitpod/tree/main/components/ee/db-sync)
[payment-endpoint](https://github.com/gitpod-io/gitpod/tree/main/components/ee/payment-endpoint)
[ide-service-api](https://github.com/gitpod-io/gitpod/tree/main/components/ide-service-api/typescript)
[image-builder-api](https://github.com/gitpod-io/gitpod/tree/main/components/image-builder-api/typescript)
[licensor](https://github.com/gitpod-io/gitpod/tree/main/components/licensor/typescript)
[server](https://github.com/gitpod-io/gitpod/tree/main/components/server)
[supervisor frontend](https://github.com/gitpod-io/gitpod/tree/main/components/supervisor/frontend)
[ws-daemon-api](https://github.com/gitpod-io/gitpod/tree/main/components/ws-daemon-api)
[ws-manager-api](https://github.com/gitpod-io/gitpod/tree/main/components/ws-manager-api)
[ws-manager-bridge](https://github.com/gitpod-io/gitpod/tree/main/components/ws-manager-bridge)
[ws-manager-bridge-api](https://github.com/gitpod-io/gitpod/tree/main/components/ws-manager-bridge-api)
[ws-proxy](https://github.com/gitpod-io/gitpod/tree/main/components/ws-proxy)

**Comment by kushal-ti** [comment]
Would the gitpod team be open to accepting a PR which makes all of these packages public ?

**Comment by svenefftinge** [comment]
Most of those packages are not libraries but apps initself. How would people consume them from nom?
