### ISSUE TITLE
Minor spacing issue when using emojies in output window

### ISSUE THREAD

**Issue by sirspot** [gitpod-io/gitpod#1530]
### Describe the bug
The output window shows no space between the emoji and the next character but the editor window with the output file shows it properly.

### Steps to reproduce
Use printf("😀 Smile"); to output an emoji with the word "Smile" next to it in the output window

### Expected behavior
There should be a space between the emoji and the text just as it is in the editor window

### Additional information
See attached image for example output

### Example repository
https://github.com/sirspot/ACR

![Gitpod Terminal Emoji Spacing](https://user-images.githubusercontent.com/32547616/82338580-147ea680-99bb-11ea-9f81-0ed5a9501da2.png)

**Comment by RDIL** [comment]
@akosyakov this is a `@theia/terminal` issue.

**Comment by akosyakov** [comment]
That's probably underlying shell issue.
