### ISSUE TITLE
Prebuild does not validate gitpod.yml

### ISSUE THREAD

**Issue by nhorton** [gitpod-io/gitpod#15314]
### Bug description

The Github Actions check for the prebuild does not validate the gitpod.yml file. This means that you can't use it as a gate to make sure that you have a good dev environment after a PR's changes.

### Steps to reproduce

Add the following type to gitpod.yml in the ports section. Note the typo at the end.

  - name: blah
    port: 8080
    opOpen: ignore

### Expected behavior

Prebuild should fail

**Comment by svenefftinge** [comment]
Did you set [`prevent-merge-on-error`](https://www.gitpod.io/docs/references/gitpod-yml#prebuildsaddcheck) to `true`?

**Comment by nhorton** [comment]
Yes.
`github:
  prebuilds:
    master: true
    pullRequests: true
    addCheck: prevent-merge-on-error
    addBadge: true`

But the bigger telling thing is you can go to the prebuild, it says it was successful, click the green button to start a workspace from it, and then get the "bad gitpod.yml" error when the workspace tries to start.

**Comment by nhorton** [comment]
Hey @svenefftinge. This behavior has always persisted. We also get an issue where often Gitpod prebuilds don't trigger. 

If really feels like it would be easier to just have a normal Github Action that we could add.
