### ISSUE TITLE
Find whole word option fails to find whole word in Microsoft Edge

### ISSUE THREAD

**Issue by sirspot** [gitpod-io/gitpod#1532]
### Describe the bug
When the find whole word option is selected no matches are found even though they exist within the document.

### Steps to reproduce
Open a document and search for a word. Select the whole word option.

### Example repository
Search for the word memset in
https://github.com/sirspot/ACR/blob/master/include/ACR/public.h
fails as shown in the picture below
![Whole Word Match Fails](https://user-images.githubusercontent.com/32547616/82396262-72db7180-9a1b-11ea-9aa4-629694fc0267.png)

**Comment by Kreyren** [comment]
@sirspot 
![image](https://user-images.githubusercontent.com/11302521/82413984-9f70a700-9a76-11ea-8d95-514ab6ca91e8.png)

Works for me -> My best guess would be that this is caused by some vscode extension?

**Comment by sirspot** [comment]
Good point! I have the C++ intellisense ext in the gitpod config but have the language server turned off so that it works properly. It wouldn’t be surprising if that had an unintended side effect.

**Comment by Kreyren** [comment]
@sirspot Could you verify if this behavior is really caused by the extension so that we could make tracking for it if needed?
Would be faster for you assuming that you have the affected environment compared to me trying to replicate it based on your input :p

**Comment by sirspot** [comment]
I can confirm this is not related to the extension. I tried it with and without and it still did not work. While testing I found that the problem only occurs in Microsoft Edge. I switched to Chrome and the problem is gone. I'll just use Chrome with Gitpod from now on.

**Comment by Kreyren** [comment]
cc @akosyakov seems that there is a problem with theia on Microsoft Edge

@sirspot can you provide a useragent for example from http://whatsmyuseragent.org/

**Comment by Kreyren** [comment]
@sirspot Also relevant logs from a browser console would be appreciated ^-^ (make sure to censor confidential info if any)

I am not familiar with Microsoft Edge so referencing https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console to how to get the console output.

**Comment by sirspot** [comment]
User Agent Info:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363

Console log attached. I'm not a web developer so I just replaced everything that looked like unique ids or keys with "...". Hopefully I didn't remove anything useful

[consolelog.txt](https://github.com/gitpod-io/gitpod/files/4658472/consolelog.txt)

**Comment by Kreyren** [comment]
fwiw issue not relevant to the user-agent (tested on custom firefox-based browser)

![image](https://user-images.githubusercontent.com/11302521/82480281-d75a0780-9ad3-11ea-99f1-36127a4cc15c.png)
