### ISSUE TITLE
Blockers preventing a peaceful end-of-the-year WebApp on-call

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#15329]
### Bug description

Since I'm on-call for team WebApp this week, I'll collect all the problems that could prevent a peaceful end-of-the-year holiday season for WebApp on-call.

Relevant problems are, for example: noisy or high-frequency alerts, unclear alerts, alerts without a runbook, etc.

- [ ] [High server load in US, triggering a tsunami of Slack alerts](https://github.com/gitpod-io/ops/issues/7436)

### Steps to reproduce

1.

**Comment by jldec** [comment]
Closing this for now - thanks @jankeromnes
