### ISSUE TITLE
Please support mobile phone numbers that start with 07 instead of 06 (Morocco, France)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#15331]
### Bug description

In both [Morocco](https://en.wikipedia.org/wiki/Telephone_numbers_in_Morocco) and [France](https://en.wikipedia.org/wiki/Telephone_numbers_in_France), mobile phone numbers can start with either **06** or **07**.

However, Gitpod's phone number validation UI currently only supports numbers start with **06** (in both countries)

| Prefix | Morocco | France |
| --- | --- | --- |
| **06** | <img width="533" alt="Screenshot 2022-12-13 at 17 57 50" src="https://user-images.githubusercontent.com/599268/207396232-1cabe1ce-82e2-4ff8-a32b-c0372ee5ae23.png"> ✅ button is enabled | <img width="538" alt="Screenshot 2022-12-13 at 17 58 16" src="https://user-images.githubusercontent.com/599268/207396250-e26ddf6c-274d-4997-8fbc-8b36261db1e4.png"> ✅ button is enabled |
| **07** | <img width="532" alt="Screenshot 2022-12-13 at 17 58 02" src="https://user-images.githubusercontent.com/599268/207396244-4fd3d54e-aea0-4b21-a7ab-68e44fbb35b0.png"> ❌ button is disabled | <img width="534" alt="Screenshot 2022-12-13 at 17 58 26" src="https://user-images.githubusercontent.com/599268/207397046-c0a2bbb2-cca7-4443-a1ea-abd64119aa9d.png"> ❌ button is disabled |

### Steps to reproduce

1. Create a new GitHub account
2. Log in to Gitpod with it and try to start a workspace
3. In the phone number verification screen, try to send a SMS code to a valid mobile phone number starting with 07, e.g.:
    - +212712345678
    - +33712345678

### Expected behavior

The validation button should be enabled, and Gitpod should send a validation code to the number.

Instead, the validation button remains disabled. (It does get enabled if you replace the first "7" with a "6", but that's no longer your own number.)

**Comment by svenefftinge** [comment]
The library we are using under the hood is google's [libphonenumber](https://github.com/google/libphonenumber/)
You can try the validation [here](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)

**Comment by jankeromnes** [comment]
> The library we are using under the hood is google's [libphonenumber](https://github.com/google/libphonenumber/)
> Could you try the actually reported phone numbers [here](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html)

I can confirm that French 07 mobile numbers are not supported by this library:

| 06 | 07 |
| --- | --- |
| <img width="664" alt="Screenshot 2022-12-13 at 19 29 35" src="https://user-images.githubusercontent.com/599268/207415956-71263f81-47ce-4d9a-b20c-86a75eda1771.png"> | <img width="662" alt="Screenshot 2022-12-13 at 19 29 47" src="https://user-images.githubusercontent.com/599268/207415963-1a7ef07c-ffc6-4c18-a2ea-fcef83e26e8e.png"> |

**Comment by svenefftinge** [comment]
Yes, maybe we can check with a real number that was not accepted?

**Comment by jankeromnes** [comment]
I've reached out again to the user whose number Gitpod didn't recognize. Maybe there is a small bug in Google's phone number parser.
