### ISSUE TITLE
Initially hide environment variable values in Settings page

### ISSUE THREAD

**Issue by spoenemann** [gitpod-io/gitpod#1534]
Gitpod environment variables are often used to store secrets such as access tokens for npm etc. I think the Settings page should hide the variable values initially and offer buttons (:eye:) to show individual values.

Example situation where this is relevant: During a video call with screen sharing the presenter wants to add / change an env variable. Other participants of that call would see the whole mapping of env variables, which could be problematic in some circumstances.

**Comment by Kreyren** [comment]
Agree, i had to change the tokens twice by now, because it got leaked through similar scenario.
