### ISSUE TITLE
Command 'Add to .gitpod.yml' resulted in an error (Cannot read properties of undefined (reading 'trim'))

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#15353]
### Bug description

Can't add `.gitpod.yml` from menu.

### Steps to reproduce

https://github.com/yue/yue

**Comment by filiptronicek** [comment]
Hi there @gengjiawen 👋! Could you please add more info about the extensions you're trying to add (along with the output of `gp info`)? I just tried opening a workspace with your mentioned repo and it seems I can add extensions from the context menu without a problem.

**Comment by filiptronicek** [comment]
The code issue is most likely originating in the [add command](https://github.com/gitpod-io/openvscode-server/blob/31811cad14dbfde0176a11ff7b6412a7f309518d/extensions/gitpod-web/src/extensionManagment.ts#L167) itself [here](https://github.com/gitpod-io/openvscode-server/blob/31811cad14dbfde0176a11ff7b6412a7f309518d/extensions/gitpod-shared/src/gitpod-plugin-model.ts#L58).

**Comment by jeanp413** [comment]
@gengjiawen can you still repro this?

**Comment by gengjiawen** [comment]
> @gengjiawen can you still repro this?

Yeap. Basically every repo. eg: https://gitpod.io/#https://github.com/hugozanini/yolov7-tfjs

It's really disappointing it's still not fixed after so long.

**Comment by jeanp413** [comment]
Thanks, I can repro.

The `Add to .gitpod.yml` is not meant to be run from the command pallete, instead it's used from the context menu when right clicking over an extension entry (it receives the extension id as argument) so I will remove it from the command pallete.

Is you intention of invoking that command from the command pallete to just open the `.gitpod.yml` file? In that case I will add a new command `Open .gitpod.yml`.


![image](https://user-images.githubusercontent.com/25115070/216778055-080d322f-d0d4-4cf8-bc6d-c02776fce7af.png)

**Comment by jeanp413** [comment]
Note to myself: verify if it does work in problem panel

**Comment by filiptronicek** [comment]
@jeanp413 do you mean an `Add to .gitpod.yml` command in the problems panel? I could not find it, but got another warning. That quickfix seems to be doing interesting stuff:
https://www.loom.com/share/d5804fea82fc4109b607c30b543d69e0

**Comment by jeanp413** [comment]
> do you mean an Add to .gitpod.yml command in the problems panel? I could not find it,

Looks it's fine then, problems panel and quick fix uses different command

> That quickfix seems to be doing interesting stuff:

yeah I saw that too =S

**Comment by jeanp413** [comment]
Closing this, `Add to .gitpod.yml` is no longer in the command pallete, for the cases when it breaks gitpod.yml I created another issue https://github.com/gitpod-io/gitpod/issues/16352
