### ISSUE TITLE
Phone verification country dropdown is hidden

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#15370]
### Bug description

Phone verification country dropdown is hidden:

<img width="518" alt="image001" src="https://user-images.githubusercontent.com/599268/207883679-39397e00-e06d-498c-b6cc-b6962a57305f.png">

### Steps to reproduce

1. Create a new GitHub account
2. Log in to Gitpod
3. Try to start a workspace -- this shows the phone verification prompt
4. Try to select a country using the drop down

### Expected behavior

The country selector dropdown should not be hidden

**Comment by svenefftinge** [comment]
cc @selfcontained  is it a side-effect of the recent change you made?

**Comment by andrew-farries** [comment]
Closing this as not reproducible (see [internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1673519562554169)).
