### ISSUE TITLE
EoL of Python2 | Update Python3 pip by default.

### ISSUE THREAD

**Issue by ucalyptus** [gitpod-io/gitpod#1540]

**Comment by jankeromnes** [comment]
Thanks for the suggestion! I agree, let's make Python 3 be the default version in Gitpod. (You can always change it back with `pyenv` if needed.)

**Comment by Kreyren** [comment]
Can't we automate this though? So that gitpod would automatically updated python on newest version?

**Comment by jankeromnes** [comment]
Already automated: https://github.com/autofix-dev/autofix/blob/master/fixers/upgrade-pyenv-tools.js

This script runs every night:

https://github.com/autofix-dev/cronjobs/blob/6779e46be34f7e4185678bd440ad56b32a60fe84/.circleci/config.yml#L35

And opens PRs like this one when needed: https://github.com/gitpod-io/workspace-images/pull/220

**Comment by Kreyren** [comment]
Fair enough O.o

***kreyren**would automate it as a part of gitpod layers that runs depending on ENV specified to make it easier to specify the default version~*

```Dockerfile
ENV PYTHON_VERSION="3.8.2"

RUN | 
	if python --version != 3.8.2; then
		get python version 3.8.2
	elif PYTHON_VERSION="latest"; then
		fetch the latest version from upstream && get that python version
	fi
```

**Comment by Kreyren** [comment]
yay, death to python 2!
