### ISSUE TITLE
[Usage/ Payment] Confusing UX

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#15411]
On the billing page we show available credits which is basically the sum of all entries in the d_b_usage ledger table + the spending limit. For instance, if someone has a spending limit of 10,000 credits and has used 2,340 credits. The Balance would show what is left, i.e. 10,000 - 2,340 = 7660 Credits.

The usage view however shows usage data over a certain period and shows the sum of all usage in that period (ignoring any spending limits or what the balance of the account was before the start of the period). So it would show 2,340 Credits in above's example only if it is set to how the same period and the balance of the account was 0 before the start of the period.

While all this is correct, it certainly is complicated and confusing for users. Let's make this simpler and more intuitive.

**Comment by jldec** [comment]
Assigned to product design - While there is room for improvement, the balance on the billing page is much clearer now than in earlier iterations. Possible improvements:

In the Balance (Billing page) view
> **Balance** = Usage limit + Credits granted or purchased - actual usage

In the Usage page view
> **Total Usage** = Sum of actual usage over the selected period

**Comment by gtsiolis** [comment]
@svenefftinge The usage limit stops usage from going beyond that regardless if there are credits in the balance outside the monthly cycle, right? If this is the case, what do you think of surfacing the used near the usage limit?

This way the used credits in the usage page will include the same number, see https://github.com/gitpod-io/gitpod/pull/16111.

| BEFORE | AFTER |
|-|-|
| <img width="608" alt="billing-before" src="https://user-images.githubusercontent.com/120486/215616680-caa078e5-0724-4705-8c70-1b0ea19971f2.png"> | <img width="608" alt="billing-after" src="https://user-images.githubusercontent.com/120486/215616684-0defcc10-2353-45f9-9893-e329f44037fa.png"> |

**Comment by gtsiolis** [comment]
Closing this, opened UX-19 to keep track of any efforts around this. Removing this also from the product design board.
