### ISSUE TITLE
Deletion of a user, deletes all S3 workspace backups

### ISSUE THREAD

**Issue by scasei** [gitpod-io/gitpod#15425]
### Bug description

When I delete a single user in admin panel, then every backup of workspace for all user and their settings will be deleted.

### Steps to reproduce

Cluster with self hosted minio
Have workspace backups and user with settings
Delete one user 
Load a stopped workspace, now there is error message about backup not found

### Expected behavior

Deletes single user and backups of other are not lost

**Comment by svenefftinge** [comment]
This is because currently workspaces are owned by users. We are going to change that so they are owned by teams. Then they get deleted when the team gets deleted.

**Comment by scasei** [comment]
Thank you for answering. 
Maybe to be more clear: If I delete ONE user, the workspace and seetings of EVERY other user currently have an account on the installation are deleted in S3 minio.
Indeed the complete S3 bucket is wiped out.
