### ISSUE TITLE
Can't open my workspace because I didn't push commits before stopping

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [gitpod-io/gitpod#1542]
### Describe the bug
I opened a blank repository from GitLab to Gitpod and do some commits that's I forget to push. When I am back, I am catching this error.

### Steps to reproduce
1. Open a newly-created/empty repo in Gitpod, [like this one](https://gitlab.com/ThePinsTeam-CommunityHubNetwork/OSS-Squad/telegram-fedbans-exports).
2. Do some stuff, but don't push.
3. Stop the workspace because I need to eat dinner.
4. Restart and the error were triggered.

### Expected behavior
I can continue working my business and push some commits to GitLab.

### Additional information
**Screenshot from DevTools console**:
![image](https://user-images.githubusercontent.com/34998342/82754206-06d38180-9dfe-11ea-9da2-d3c2b79a76ab.png)
**Workspace ID**: `ec72f610-3380-4b71-81b8-3f4e948da8bd`

### Example repository
<https://gitlab.com/ThePinsTeam-CommunityHubNetwork/oss-squad/telegram-fedbans-exports>

**Comment by Kreyren** [comment]
Unable to reproduce on GitHub assuming Gitlab issue.

cc @jankeromnes

**Comment by AndreiJirohHaliliDev2006** [comment]
@Kreyren I tried to export the workspace files to do the `git push` locally and it works. I reattempted the startup process and still catching these errors.

**Comment by AndreiJirohHaliliDev2006** [comment]
**UPD**: I pushed some commits locally to GitLab, but I need to create a new Gitpod workspace to update them.

**Comment by svenefftinge** [comment]
I tried to reproduce what you described with no success. Here's what I tried:

1) start a workspace (https://gitpod.io/#https://gitlab.com/ThePinsTeam-CommunityHubNetwork/oss-squad/telegram-fedbans-exports)
2) make changes, create a commit
3) stop workspace (avatar menu->stop workspace)
4) when stopped, click 'start workspace' in the dialog

The workspace started fine including the unpushed commit.

How did you try to start the stopped workspace again? Through https://gitpod.io/workspaces?

**Comment by AndreiJirohHaliliDev2006** [comment]
@svenefftinge I repeated the process on a new blank GitLab repo on my personal account, and while init process took long before I can use the web editor.

## What I Observed
- Ordinary repositories usually have a link to the source repo, its branch, and the commit ID.

![image](https://user-images.githubusercontent.com/34998342/82992035-269ebb80-a031-11ea-9565-46e17e0b370b.png)

- While blank repositories used in Gitpod doesn't have these.
![image](https://user-images.githubusercontent.com/34998342/82992215-69609380-a031-11ea-9257-b12f5dec00e1.png)
