### ISSUE TITLE
[blobserve] watch and reload dockerAuth config when using ECR

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#15426]
## Is your feature request related to a problem? Please describe

When running in AWS using ECR, the cluster's image pull secret will be updated periodically by the `refresh-credential` component. Eventually, this means the [dockerAuth config](https://github.com/gitpod-io/gitpod/blob/4aacec9e264892232d76aba227f02e6f33da13f5/components/blobserve/pkg/config/config.go#L17) for blobserve will grow stale.

## Describe the behaviour you'd like

blobserve should watch the pull secret for changes and update its configmap, similar to registry-facade and image-builder-mk3.

additionally, the new `refresh-credential` component should be deployed in application clusters as part of [IDE installation types](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/components-ide/components.go), not just [workspace types](https://github.com/gitpod-io/gitpod/blob/4aacec9e264892232d76aba227f02e6f33da13f5/install/installer/pkg/components/components-workspace/components.go#L27).

## Additional context

Here is an example for workspace, and image builder. 

We depend on an image pull secret being defined at install time
https://github.com/gitpod-io/gitpod/blob/0b4662b20e0ba46561221d6125d558ed01f65e09/install/installer/pkg/components/image-builder-mk3/deployment.go#L30

Rotated on a schedule at runtime
https://github.com/gitpod-io/gitpod/blob/0b4662b20e0ba46561221d6125d558ed01f65e09/install/installer/pkg/components/refresh-credential/constants.go#L10

And then components which need a working dockerAuth value update their config  at runtime:
https://github.com/gitpod-io/gitpod/blob/0b4662b20e0ba46561221d6125d558ed01f65e09/components/image-builder-mk3/pkg/auth/auth.go#L42

**Comment by kylos101** [comment]
@laushinka @akosyakov @loujaybee for :eyes: and @jenting because IDE team may questions.

**Comment by kylos101** [comment]
We discussed today that the Scout Team will take of supporting external services, removing from IDE team inbox @akosyakov @laushinka @loujaybee .

**Comment by Daibao9999** [comment]
(.)

**Comment by jenting** [comment]
> additionally, the new refresh-credential component should be deployed in application clusters as part of [IDE installation types](https://github.com/gitpod-io/gitpod/blob/main/install/installer/pkg/components/components-ide/components.go), not just [workspace types](https://github.com/gitpod-io/gitpod/blob/4aacec9e264892232d76aba227f02e6f33da13f5/install/installer/pkg/components/components-workspace/components.go#L27).

If the image builder moved to the workspace cluster, should the refresh-credential still need to be deployed into the application cluster?
