### ISSUE TITLE
Can't sign builds

### ISSUE THREAD

**Issue by ghost** [gitpod-io/gitpod#1543]
Whenever I am trying to sign a build I am getting the following error:
error: gpg failed to sign the data
fatal: failed to write commit object

Locally:
I always get this error locally on VSCode as well.
But in the terminal app itself it just works.

I followed this guide: https://help.github.com/en/github/authenticating-to-github/managing-commit-signature-verification

**Comment by Kreyren** [comment]
relevant: https://github.com/gitpod-io/gitpod/issues/666#issuecomment-534124994

relevant: https://github.com/gitpod-io/gitpod/issues/467

afaik gitpod currently doesn't know how to sign the commits
