### ISSUE TITLE
Prepare Public API for private beta

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#15453]
- [x] https://github.com/gitpod-io/website/pull/3189
- [x] Remove access tokens from navigation in settings page (https://gitpod.io/account)
- [ ] Implement an email opt-in mechanism for the private beta
- [x] Add feature flag to config cat, and only show access token page to user ID's + Gitpodders in feature flag

**Comment by Siddhant-K-code** [comment]
> Implement an email opt-in mechanism for the private beta

@loujaybee we could implement similar mechanism what we've used for workspace classes/ Usage-based Pricing. Adding a new section for `Public API` in [`/support`](https://www.gitpod.io/contact/support) form


[_Internal conversation_](https://gitpod.slack.com/archives/C01LDA28WV6/p1666684526453099?thread_ts=1666644501.776739&cid=C01LDA28WV6)

**Comment by loujaybee** [comment]
Going to close this now, we have what we need for the private beta.

**Comment by loujaybee** [comment]
For those looking to access the private beta for the Public API, please complete this form: 

https://forms.gle/AWJY4dcV859Nis5k9
