### ISSUE TITLE
gmright2

### ISSUE THREAD

**Issue by gmright2** [gitpod-io/gitpod#1547]

**Comment by Kreyren** [comment]
![](https://media.giphy.com/media/iSuffsM2olusE/giphy.gif)

**Comment by gmright2** [comment]
Th

**Comment by Kreyren** [comment]
if i understand correctly you seem to have issues with permission? If so you might be able to fix that on https://gitpod.io/access-control/

Please elaborate further if i am missunderstanding this ^-^

Btw. If you have problems with english then you can use your native language.

**Comment by gmright2** [comment]
https://8080-ebf8e475-b279-469c-8c47-f385b7f161e5.ws-eu01.gitpod.io/oups

Now I want to understand how is this source of application will be able to affect my repository in pod data 


And else how did will be able to affect back the repostory https://3000-ac6befa7-483f-4233-aab0-7110eb5c66db.ws-eu01.gitpod.io

**Comment by Kreyren** [comment]
Sorry

i do not understand >.>

Can you elaborate?

Alternatively ... Can you write in your native language?

**Comment by gmright2** [comment]
Yes gmright2 is helping on   Jekyll to support dependencies   https://github.com/gmright-service-gmright/gmright2.github.io-

**Comment by Kreyren** [comment]
***kreyren** is even more confused*

**Comment by Kreyren** [comment]
So you are using jekyll on gitpod? If so what is the issue?

**Comment by gmright2** [comment]
The codes lines it keep broken when the affection start on this source of application 

https://3000-ac6befa7-483f-4233-aab0-7110eb5c66db.ws-us02.gitpod.io/

**Comment by Kreyren** [comment]
@gmright2 works for me

![image](https://user-images.githubusercontent.com/11302521/84041854-9ce1dd00-a9a4-11ea-85d9-176739970002.png)

**Comment by gmright2** [comment]
Still that is the same https://github.com/gitpod-io/gitpod/issues/1547#issuecomment-638777617 but sometimes it keeps failing 
![098D8B8A-6A0C-486D-B62B-1C833D97CF2A](https://user-images.githubusercontent.com/59498844/84042380-9afb2800-a96a-11ea-9f20-6aadaf1543a1.jpeg)

**Comment by Kreyren** [comment]
afaik port 8080 is for noVNC that you are seemingly not using?

i still don't understand what the issue is for this to be actionable

**Comment by gmright2** [comment]
The issues is to connecting this repostory https://github.com/gmright-service-gmright/gmright2.github.io- and test it in the gitpod but the repostory from GitHub is not showing in gitpod still it keep giving me different repostory 
![ACA2DE00-1EE2-4009-BB5D-CD4B42F2D981](https://user-images.githubusercontent.com/59498844/84043015-68056400-a96b-11ea-9f2e-e6a293c07f92.jpeg)

**Comment by Kreyren** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/11302521/84043278-5ee5b880-a9a6-11ea-8e3b-78b9dc006b87.png)


![image](https://user-images.githubusercontent.com/11302521/84043311-686f2080-a9a6-11ea-82cc-8919410d52a7.png)

**Comment by Kreyren** [comment]
@gmright2 eh? O.o
