### ISSUE TITLE
Won't pass my repository 

### ISSUE THREAD

**Issue by JustinLorenzo03** [gitpod-io/gitpod#1550]

**Comment by JustinLorenzo03** [comment]
Won't allow me to input my repository in gitpod

**Comment by Kreyren** [comment]
@JustinLorenzo03 I need more info to provide the required support

So far it looks to me as pebcak where end-users usually mis-use the context url so please verify that you are trying to open the workspace using:

```
https://gitpod.io/#<URL-TO-YOUR-REPOSITORY>
```

Note that currently gitpod supports GitHub and Gitlab.

For example https://gitpod.io/#https://github.com/gitpod-io/gitpod/issues/1550

**Comment by JustinLorenzo03** [comment]
Yes, I have the correct url for my repository and using gitpod to get it from github, but every time I try to pass it keeps saying "We are having trouble parsing your content, Error: Unauthorized"

**Comment by Kreyren** [comment]
@JustinLorenzo03 Seems that you didn't grant gitpod the required permission.

Try doing so in https://gitpod.io/access-control or installing the gitpod application in https://github.com/marketplace/gitpod-io

**Comment by ret394** [comment]
last I checked Gitpod was missing the appropriate code for auth. simple enough to implement for all-or-nothing access.

thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394)

**Comment by Kreyren** [comment]
@ret394 afaik gitpod has all the required implementations for github authentification atm :thinking:

**Comment by ret394** [comment]
> 
> 
> @ret394 afaik gitpod has all the required implementations for github authentification atm 🤔


If the OSS code has the corresponding commit, you can try to reproduce it.

I'll take a look at it definitely, once someone from Gitpod extends the time limit for my account, 50 hours is a pretty tight leash. 🔍

---

thanks
