### ISSUE TITLE
Inconsistent spacing in prebuild terminal message

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#15508]
### Bug description

<img width="306" alt="Screenshot 2022-12-27 at 10 35 45" src="https://user-images.githubusercontent.com/599268/209646533-2ac079e5-23cf-4687-96e0-b2d696a2cd22.png">

### Steps to reproduce

1. Run a prebuild
2. Observe the final prebuild log line (either by viewing the prebuild logs, or by opening it in a workspace)

### Expected behavior

The spacing between the emoji and the text should look identical in both lines.

**Comment by gtsiolis** [comment]
Thanks for the feedback and noticing[[1](https://github.com/gitpod-io/gitpod/pull/15364#issuecomment-1365761102)], @jankeromnes!

I tried fixing this a couple of weeks ago in https://github.com/gitpod-io/gitpod/commit/474b7c432c58b21519747205f95b0786877bf7d3 but haven't checked this in a preview environment yet.

**Comment by gtsiolis** [comment]
Unassigning for now, this is still relevant, see previous attempt to resolve this in https://github.com/gitpod-io/gitpod/pull/16110.
