### ISSUE TITLE
Default Python configuration indentation inconsistencies

### ISSUE THREAD

**Issue by petehunt** [gitpod-io/gitpod#15514]
### Bug description

When opening Python files using the default configuration, the autoformatter is set to 4 space indentation, but VSCode is set to 2 space.

### Steps to reproduce

* gitpod.new
* create a new python file
* write a function or some other code that has indentation
* save

### Expected behavior

expected: no change to code on save (i.e. stays 2-space indented)
actual: code gets re-indented to 4 space indents, and vscode shows the code as double-indented

**Comment by axonasif** [comment]
Hi @petehunt, can you reproduce it outside of Gitpod on you local machine?
