### ISSUE TITLE
[Code] Ignore `NODE_OPTIONS` env var when starting IDE

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#15519]
# Description
Setting `NODE_OPTIONS` to `--experiemental-vm-modules` will fail the IDE launch. We should ignore user defined `NODE_OPTIONS` when launching the IDE to ensure the IDE always starts.

- [Community discussion](https://discord.com/channels/816244985187008514/1057463418791145492/1057753636819718236)
- [Internal discussion](https://gitpod.slack.com/archives/C0201TXMV54/p1672241938333729)

**Comment by akosyakov** [comment]
I think it is a specific example of https://github.com/gitpod-io/gitpod/issues/14293

**Comment by akosyakov** [comment]
We discussed that error reporting should be improved instead: https://github.com/gitpod-io/gitpod/pull/15526#issuecomment-1372023226
