### ISSUE TITLE
Is there anyway to turn off PIP_USER completely?

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#1552]
I understand that I can use `export PIP_USER=no` but it is temporarily. Is there any permanent way to turn off PIP_USER?

**Comment by Kreyren** [comment]
@dclong What kind of permanent solution do you expect?

Alike you can set the variable on https://gitpod.io/settings/

Alternatively can you elaborate on why do you want to disable it in case there is a better way that you might not be aware of?

**Comment by Kreyren** [comment]
@dclong Also apparently `PIP_REQUIRE_VIRTUALENV=true` is a thing which quoting "it accomplishes the same thing but more generally"

(info from freenode.net/#python)

**Comment by dclong** [comment]
@Kreyren By "permanent" I mean that the environment variable "PIP_USER" defaults to "no" when I open a new terminal in a workspace. I assume the settings in the following screenshot set `PIP_USER` to `no` for all workspaces?

![image](https://user-images.githubusercontent.com/824507/82985558-15aa6780-9fa9-11ea-9fa9-1e5c10c93922.png)

**Comment by AlexTugarev** [comment]
Hi! The reason to set PIP_USER is a pragmatic one: this allows to back up the installed modules and preserve them between workspace runs. We hope to overcome the limitation of backing up only the `/workspace` directory soon, which will make the PIP_USER setting obsolete.

A workaround per repository would be to add a task to a `.gitpod.yml` which would append `export PIP_USER=no` to `~/.bashrc`. Would that work for you?

**Comment by dclong** [comment]
@AlexTugarev I've tried exporting `PIP_USER` to `no` in `.gitpod.yml`. However, it only works in that specific shell, which is inconvenient. And that's why I'm asking for a "permanent" way to turn off PIP_USER.

**Comment by Kreyren** [comment]
***kreyren** would do this*

```Dockerfile
USER gitpod
RUN if ! grep -q "export PIP_USER=no" "$HOME/.bashrc"; then printf '%s\n' "export PIP_USER=no" >> "$HOME/.bashrc"; fi
```

**Comment by dclong** [comment]
@Kreyren,

Will this change get overwritten by gitpod Dockerfile layers (which come after user's customized Docker image)? 

Currently, I have a shell script https://github.com/dclong/docker-gitpod/blob/master/scripts/gitpod.sh built into my customized Docker image and then source in this script in `.gitpod.yml` to reslove the issue.

**Comment by Kreyren** [comment]
> Will this change get overwritten by gitpod Dockerfile layers (which come after user's customized Docker image)?

I am not aware of gitpod layer that would do such a thing.

**Comment by Kreyren** [comment]
> Currently, I have a shell script https://github.com/dclong/docker-gitpod/blob/master/scripts/gitpod.sh built into my customized Docker image and then source in this script in .gitpod.yml to reslove the issue. @dclong 

I would sanitize it, but looks good to me. O.o

**Comment by Kreyren** [comment]
Alternatively do you expect any action from us? I.e making changes to how gitpod handles this variable?

**Comment by AlexTugarev** [comment]
@dclong, you're right, this happens in the Gitpod layer unfortunately.

The workaround I mentioned above looks like this:
```
tasks:
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
```

**Comment by dclong** [comment]
@AlexTugarev Thank you very much! My workaround is inspired by yours.

**Comment by dclong** [comment]
@Kreyren I don't expect any action from GitPod at this time.

Just curious, what are environment variables at https://gitpod.io/settings/ used for?

**Comment by Kreyren** [comment]
> Just curious, what are environment variables at gitpod.io/settings used for?

For a situation where you need a specific variable available on your workspace without exporting it publicly, mostly used for secrets and other things you don't want people to see or has a specific use-case per user alike

![image](https://user-images.githubusercontent.com/11302521/83113856-7da39f80-a0c8-11ea-9495-e7222ef9f9d4.png)

**Comment by Kreyren** [comment]
Closing as solved since reporter doesn't expect any action from gitpod and the issue has been solved
