### ISSUE TITLE
Gitpod doesn't work well with jekyll

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1553]
### Describe the bug

Using `JEKYLL_ENV=development bundle exec jekyll serve` to provide a theia preview of the website causes 404, because gitpod is using `localhost:4000` that is not accesible to gitpod user.

This can either be workedaround using:
- Firefox in noVNC
- Rewriting the whole repository to accept special gitpod environment
- Weird hack alike `cat _config.yml | sed -E "s#^(url:\s{1})(\").*(\").*#\1\2$(gp url)\3#gm" > _config_gitpod.yml && JEKYLL_ENV=production bundle exec jekyll serve --config _config_gitpod.yml` which is not acceptable for gitpod users.

### Expected behavior

We need some way to display `localhost:4000` in theia's preview, maybe some wrapper for theia's preview that points to `$(gp url)` everytime `localhost` is called on it?

### Additional information

Blocks gidpodifying of https://github.com/CircuitVerse/Interactive-Book/pull/374

### Example repository

https://gitpod.io#snapshot/d3a9516c-4be3-47b2-81dc-df4020ff4f57

**Comment by RDIL** [comment]
This is a problem on Jekyll's end for forcibly using localhost instead of the dynamic public address

**Comment by Kreyren** [comment]
@RDIL Possible i guess, what do you propose then?

**Comment by Kreyren** [comment]
cc @ChristinFrohne @uniminin @htes9

**Comment by qnm** [comment]
Maybe you’ve already tried this, but Jekyll accepts a bind param eg

`jekyll serve —host=0.0.0.0`

That should listen on all interfaces.

**Comment by Kreyren** [comment]
@qnm Already tried.. The host can only point to localhost it seems even when i parsed an IPv4 of the workspace to it.

**Comment by svenefftinge** [comment]
I don't see how this could be solved in the frontend. As long as the preview is running as an iframe (webview), we would need to intercept the requests to localhost which is not possible. 
Therefore running a browser in the remote container and somehow showing the rendered ui in the browser seems to be the only generic solution. There is https://github.com/auchenberg/vscode-browser-preview based on chrome headless but also your VNC proposal seems similar.

FWIW I think patching the config in a gitpod config is not too bad either, but for instance the livereload would not work that way.

**Comment by Kreyren** [comment]
Trying the extension which on gitpod results in 
![image](https://user-images.githubusercontent.com/11302521/83967541-cb878700-a8c2-11ea-899f-6d3572bcdde7.png)

trying to install chrome..

**Comment by Kreyren** [comment]
heads-up: activity in https://github.com/jekyll/jekyll/issues/8229
