### ISSUE TITLE
Use the actual current period when visiting the usage page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15544]
### Problem to solve

Usage periods now start and finish on the actual billing cycle date, see #14363, #14485, and [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1669737909843879) (internal).

However, :a: the usage page is using by default the beginning of the month and the current date as a start date and the end date accordingly and :b: visiting the usage page from the billing settings links to a different view.

Cc @svenefftinge because https://github.com/gitpod-io/gitpod/pull/14515

### Proposal

Use the actual current period when visiting the usage page.

| Example period | BEFORE | AFTER |
|-|-|-|
| <img width="613" alt="billing" src="https://user-images.githubusercontent.com/120486/210262181-5823bc7e-5d24-496b-900a-c2d8b6678c0c.png"> | <img width="659" alt="usage-before" src="https://user-images.githubusercontent.com/120486/210261925-8bbe84ec-21d5-40ef-ba2d-19049313bc6c.png"> | <img width="659" alt="usage-after" src="https://user-images.githubusercontent.com/120486/210261927-e8a92157-2e83-45c1-8494-2efd488dc96b.png"> |

**Comment by bonysureliya** [comment]
I am interested to work on this issue can you please explain the issue more precisely .

**Comment by gtsiolis** [comment]
Hi @bonysureliya! When you go to personal usage (`/usage`) or your team usage (`/t/:team/usage`), the selected period (from, to) in the page header and of course the data below should match the **current period** found in the corresponding **billing page**.

For example if you see `Jan 1, 2023 – Feb 1, 2023` as the current period on the billing page, going to usage should filter the default view with these dates. Currently, usage default to the first of month (from) and today's date (to).

Feel free to open a PR and link back to this issue. 🏓

**Comment by bonysureliya** [comment]
Ok i am working on this issue and i will let you know if i need help

**Comment by bonysureliya** [comment]
What we can do is gather the current date as end date (To date) and start date as the today's date of previous month (From date)

**Comment by mittallakshayy** [comment]
I someone currently working on this ?

**Comment by gtsiolis** [comment]
@mittallakshayy I think it's safe to assume that no one is actively working on this as there's no assignee from the team and the last comment from @bonysureliya was 3+ weeks ago. Feel free to open a PR and link back to this issue. 🏓

**Comment by bonysureliya** [comment]
I am currently working on this waiting for the issue to get assigned

**Comment by gtsiolis** [comment]
@bonysureliya I generally avoid assigning anyone outside the team to avoid blocking community contributions to stale issues that never get a PR which is very common across open source projects. However, I like challenging this approach—assigned!
