### ISSUE TITLE
[JetBrains] Consider reducing the Gateway integration tests to a single IDE

### ISSUE THREAD

**Issue by felladrin** [gitpod-io/gitpod#15563]
## Description

JetBrains Integration Tests usually fail as they take more than 1h to complete ([here](https://werft.gitpod-dev.com/job/gitpod-build-jetbrains-update-stable-ides.42/raw), for example, search for "test timed out after 1h0m0s"). When it happens, we're required to run the tests manually [[1](https://github.com/gitpod-io/gitpod/pull/15520#issuecomment-1367930323)].

As we're testing only the Gateway connection with the backend IDE at this moment, we could reduce it to 1 backend IDE (IDEA or Rider), as their codebase (IntelliJ) works the same for all. This would reduce in 87% the time to run Werft Build during PRs.

## Related Issues

- https://github.com/gitpod-io/gitpod/issues/15427

**Comment by andreafalzetti** [comment]
I have been investigating how to improve integration tests for JetBrains in the past days, and one thing I've noticed is that we wait 3 minutes at least, just for the workspace to start, which means 8 IDEs * 3 min = 24 minutes of wait, plus build time etc.. it quickly reaches 1h. 

It would be interesting if we could parallelise the tests, however 1 prev env won't be enough (unless we create a bigger VM).

Alternatively, we could test random IDEs each day, e.g. (2 out of 8)

**Comment by felladrin** [comment]
Agreed.
I like this idea of rotating the IDEs for tests!
