### ISSUE TITLE
Replace rotating magnifier icon with the spinner component

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15616]
### Problem to solve

When redesigning the dashboard, we added for fun a rotating magnifier icon as a search loading indicator. This issue is a placeholder for improving the search UX.

https://user-images.githubusercontent.com/120486/211091661-d50687ff-fea0-4332-a5be-c57a4dcad797.mov

### Proposal

A good MVC could be to replace the magnifier icon with the spinner component while performing the search.

**Comment by Ciggzy1312** [comment]
Seems like a good starting point for me to contribute to this project
Can I give this a try?

**Comment by gtsiolis** [comment]
Absolutely, @Ciggzy1312! Feel free to open a PR and link back to this issue. 🏓

**Comment by Ciggzy1312** [comment]
Hey @gtsiolis I finally managed to setup the project after a lot of struggle
Can you somehow guide me on recreating the issue as I don't see it as of now, or probably am doing something wrong

[Screencast from 15-01-23 07:53:57 PM IST.webm](https://user-images.githubusercontent.com/65884232/212546804-32c009f7-903c-4631-9fba-92a27f268a2b.webm)

**Comment by gtsiolis** [comment]
@Ciggzy1312 The rotating magnifier icon is visible in the admin dashboard search inputs where searching takes longer than a few milliseconds.

If you open a pull request, I can help spinning up a preview environment for you and making your user admin so that you can see this in action.

The areas that need change are the following:

https://github.com/gitpod-io/gitpod/blob/f125f5a5cd0c8635855ad8bbf33abcb6a642656d/components/dashboard/src/admin/TeamsSearch.tsx#L80

https://github.com/gitpod-io/gitpod/blob/f125f5a5cd0c8635855ad8bbf33abcb6a642656d/components/dashboard/src/admin/ProjectsSearch.tsx#L100

https://github.com/gitpod-io/gitpod/blob/f125f5a5cd0c8635855ad8bbf33abcb6a642656d/components/dashboard/src/admin/WorkspacesSearch.tsx#L118

https://github.com/gitpod-io/gitpod/blob/f125f5a5cd0c8635855ad8bbf33abcb6a642656d/components/dashboard/src/admin/BlockedRepositories.tsx#L122

https://github.com/gitpod-io/gitpod/blob/f125f5a5cd0c8635855ad8bbf33abcb6a642656d/components/dashboard/src/admin/UserSearch.tsx#L70
