### ISSUE TITLE
Error: build failed: rpc error: code = Internal desc = cannot create build volume: 

### ISSUE THREAD

**Issue by rholland** [gitpod-io/gitpod#1562]
A simple latex template from your docs is failing to build with the immediate error:

```
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: %!w(string=)
Please file an issue if you think this is a bug. 
```

Is a server down or a disk full as was reported in previous similar incidents?

**Comment by rholland** [comment]
now it has started building.

**Comment by Kreyren** [comment]
Concluded this being a duplicate of https://github.com/gitpod-io/gitpod/issues/1559

**Comment by rholland** [comment]
everything works now

**Comment by Kreyren** [comment]
@rholland let me know if it breaks again, currently being tracked in #1559 ^-^
