### ISSUE TITLE
what screen recording extension is built in?

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#1563]

**Comment by Kreyren** [comment]
I am not aware of any built-in screen recording extension, why are you asking?

**Comment by markfirmware** [comment]
I want to be able to record a running demo and include it in the readme file. I have seen other repositories with this kind of recording and was under the impression that they were produced using a vs ode extension.

**Comment by Kreyren** [comment]
As far as I know this is done by a third party software like:
- https://itsfoss.com/best-linux-screen-recorders/
- https://github.com/linuxdeepin/deepin-screen-recorder

Edit: there seems to be such extensions, but I did not test them

https://github.com/arciisine/vscode-chronicler
https://marketplace.visualstudio.com/items?itemName=wk-j.screen-recorder
https://github.com/wk-j/vscode-screen-recorder


Honorable mensions
- https://marketplace.visualstudio.com/items?itemName=pnp.polacode
- https://stackoverflow.com/questions/1636011/how-to-record-screen-and-save-as-gif-animation

**Comment by JesterOrNot** [comment]
Wait I think I know what you mean, are you talking about something like https://github.com/JesterOrNot/Gitpod-VSCode-Extension-Dev#workflow

**Comment by Kreyren** [comment]
@JesterOrNot I don't see how is provided link relevant

**Comment by markfirmware** [comment]
The question is how was the screen recording in that link produced? Is it done by a a vscode extension that could be built in to gitpod?

**Comment by JesterOrNot** [comment]
OK, I recorded the video using [loom](https://chrome.google.com/webstore/detail/loom-for-chrome/liecbddmkiiihnedobmlmillhodjkdmb?hl=en-US) to record that video. After you record, loom gives you a link to the video. Simply add the link to the README file and GitHub should display the video. Hope this helps :smiley:
