### ISSUE TITLE
Deprecate and remove the licensor

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#15639]
Now that we have ended support for self-hosted, the licensor is now an additional complexity to support. This should be removed.

When self-hosted was officially supported, it made sense to have a licensor. This ensured that no installation exceeded the supported number of users without purchasing a licence, or it limited the feature set available to the installation. Now we no longer officially support self-hosted or sell licences for it, having a licensor is just adding complexity that we have to support and is adding friction into the (unsupported) self-hosted installations out there in the wild.

Of course, as our source code is open source, it wasn't too difficult to bypass these protections.

## Tasks

- [x] #15640
- [ ] Remove the licensor component from `main`

## Linked issues

 - #15457

**Comment by gtsiolis** [comment]
Closing as the `licensor` component has been removed in https://github.com/gitpod-io/gitpod/pull/16983. Cc @aledbf @AlexTugarev @geropl
