### ISSUE TITLE
Resolve the TypeORM readiness check race condition when using `slow-server`

### ISSUE THREAD

**Issue by andrew-farries** [gitpod-io/gitpod#15655]
There is a race condition when `slow-server` starts where the database is considered ready by the waiter init container, but TypeORM has not yet finished initalization. This makes `slow-server` unusable and the only solution is to restart the `slow-server` pods.

See internal discussion [here](https://gitpod.slack.com/archives/C02EN94AEPL/p1670922098012619) and [here](https://gitpod.slack.com/archives/C02EN94AEPL/p1673341030791129).

**Comment by geropl** [comment]
For validation: one symptom were [regular error messages on every rollout.](https://cloudlogging.app.goo.gl/6M4rKKfjewm4jABS6) Those should be gone with the PR. 👆

**Comment by geropl** [comment]
Validated that the new rollout did not trigger any errors: https://cloudlogging.app.goo.gl/RoFYTQoU6bSg1WfC7
