### ISSUE TITLE
Workspace creation fails - sudo: setrlimit(RLIMIT_CORE): Operation not permitted

### ISSUE THREAD

**Issue by ronys** [gitpod-io/gitpod#1565]
### Describe the bug
Can't create workspace: fails trying to run a local script

### Steps to reproduce
https://gitpod.io/#https://github.com/pwsafe/pwsafe/tree/gitpod3

### Expected behavior
Workspace should be created successfully.

### Additional information
Trying to eliminate some duplicates: Both the gitpod Dockerfile and an existing utility script run apt-get install for the project's dependencies. However, replacing 'sudo apt-get install ..." with an invocation of the script 'sudo sh ./Misc/setup-deb-dev-env.sh" causes the workspace build to fail with:
![image](https://user-images.githubusercontent.com/781072/83235808-23274380-a19b-11ea-8184-6037e58cffa7.png)

### Example repository
https://github.com/pwsafe/pwsafe/tree/gitpod3

**Comment by Kreyren** [comment]
Assigned @jankeromnes for reasons in https://github.com/gitpod-io/website/pull/668#issuecomment-635886244

**Comment by jankeromnes** [comment]
Hi @ronys,

At the time you're running:

```Dockerfil
RUN sudo apt-get -q update && sudo sh ./Misc/setup-deb-dev-env.sh && #...
```

there is no such thing as a `./Misc/setup-deb-dev-env.sh` in your Docker image.

Here is a Dockerfile that I think should work better:

```Dockerfile
FROM gitpod/workspace-full-vnc
                    
# Set debconf to noninteractive mode.
RUN echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections

# Install dependencies.
COPY ./Misc/setup-deb-dev-env.sh /tmp/setup-deb-dev-env.sh
RUN sudo apt-get -q update && \
    sudo sh /tmp/setup-deb-dev-env.sh && \
    sudo apt install -yq cmake-gui && \
    sudo rm -rf /var/lib/apt/lists/* /tmp/setup-deb-dev-env.sh

# Set debconf back to normal.
RUN echo 'debconf debconf/frontend select Dialog' | sudo debconf-set-selections
```

**Comment by ronys** [comment]
@jankeromnes - the COPY command you suggest makes sense, but it doesn't work:
![image](https://user-images.githubusercontent.com/781072/83286916-6f00d980-a1e9-11ea-9efb-1d63ef89cd1d.png)

.gitpod.Dockerfile is in https://github.com/pwsafe/pwsafe/blob/gitpod3/.gitpod.Dockerfile

Suggestions?

**Comment by Kreyren** [comment]
```diff
--- COPY ./Misc/setup-deb-dev-env.sh /tmp/setup-deb-dev-env.sh
+++ COPY /Misc/setup-deb-dev-env.sh /tmp/setup-deb-dev-env.sh
```

**Comment by ronys** [comment]
Thanks @Kreyren - that was the missing part!

Where can I see the workspace creation log? I still see some red text, but it's scrolling by way too fast for me to investigate while the workspace is being built.

**Comment by Kreyren** [comment]
> Where can I see the workspace creation log? I still see some red text, but it's scrolling by way too fast for me to investigate while the workspace is being built.

afaik it's only in the provided window and in browser's console

@jankeromnes may clarify

**Comment by jankeromnes** [comment]
> Where can I see the workspace creation log? I still see some red text, but it's scrolling by way too fast for me to investigate while the workspace is being built.

You can scroll up in the build output view, or Select All + Copy + Paste somewhere else if you prefer that.

**Comment by Kreyren** [comment]
FWIW i usually do this or something alike to get logs https://github.com/Kreyren/forkless-pwsafe/blob/01237b1154e3af37e77c9d3a91ed5dd34254c2a9/Makefile#L7

Which provides the required logs on paste service for me to view easily~

**Comment by corneliusludmann** [comment]
Just for the record: The warning
```
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
```
has nothing to do with the failure of the workspace creation. This warning is from `sudo` and can be safely ignored (see https://github.com/sudo-project/sudo/issues/42).

@ronys: Fell free to close this issue when it is solved for you.

**Comment by Kreyren** [comment]
My fault then! >.<
