### ISSUE TITLE
gitpod.io should not be listed on search engines

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/gitpod#15667]
### Bug description

when searching for "gitpod.io" on Google, I noticed that we still index gitpod.io. In #9622 we already intended to remove it but apparently, it's not working. Additionally, Gitpod is also misspelled

<img width="360" alt="Bildschirm­foto 2023-01-10 um 15 59 19" src="https://user-images.githubusercontent.com/46345125/211590484-bd3c7ef1-5094-44c9-910f-6f41f2f497f2.png">

cc @jankeromnes because you worked on #9622

### Steps to reproduce

Search for "gitpod.io" on Google

**Comment by Siddhant-K-code** [comment]
[Internal Discussion](https://gitpod.slack.com/archives/C01KGM9ETU6/p1673365240735409) :thread:

**Comment by Siddhant-K-code** [comment]
It is now removed from search engines ✅ 

![image](https://user-images.githubusercontent.com/55068936/212729751-563dcf19-932f-477d-af24-bdc777ea8fd3.png)
