### ISSUE TITLE
Include a warning alert in the confirmation modal when deleting a workspace with pending changes

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15669]
### Problem to solve

When a workspace contains (pending) changes (uncommitted files or unpushed commits) there's a indication on the workspaces list there are changes.

When a user tries to delete a workspace from the dashboard, they get a confirmation modal. However, there's no clear indication whether the associated workspace contains pending changes (uncommitted files or unpushed commits).

A https://github.com/gitpod-io/gitpod/labels/customer is interested in this feature request, see [relevant discussion](https://gitpod.slack.com/archives/C01KGM9DVRC/p1673365559849689) (internal).

### Proposal

A good [MVC](https://www.notion.so/gitpod/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e#0c2e0d6c8a99404b97ccdc206b573d72) could be to include a warning alert in the confirmation modal when deleting a workspace with pending changes.

| Workspace with changes | BEFORE | AFTER |
|-|-|-|
| <img width="1440" alt="Screenshot 2023-01-10 at 5 51 03 PM (2)" src="https://user-images.githubusercontent.com/120486/211629026-ee91ce4b-8ae3-4d31-ac88-d54188f225be.png"> | <img width="1440" alt="Screenshot 2023-01-10 at 5 51 08 PM (2)" src="https://user-images.githubusercontent.com/120486/211628806-764f0603-50ef-4cb1-9619-a3cc49b7803b.png"> | <img width="1440" alt="Screenshot 2023-01-10 at 8 04 12 PM (2)" src="https://user-images.githubusercontent.com/120486/211628808-94e6fa45-eb84-4b60-a850-ebde29f3cf6a.png"> |

### Risks

However, when reopening a stopped workspace with changes there's no clear indication that there are pending changes and users can still delete the workspace from the more actions menu. ❗ 

| Stopped workspace with changes | Reopened workspace with changes |
|-|-|
| <img width="1440" alt="Screenshot 2023-01-10 at 8 04 21 PM (2)" src="https://user-images.githubusercontent.com/120486/211628637-c41402bf-5628-44c0-9407-c169e949e210.png"> | <img width="1440" alt="Screenshot 2023-01-10 at 8 07 00 PM (2)" src="https://user-images.githubusercontent.com/120486/211628718-578f3852-1d73-4f20-83df-a20f52975172.png"> |

**Comment by vedant-jain03** [comment]
Sure, thanks!

**Comment by vedant-jain03** [comment]
@gtsiolis thanks, it will be great if you could share the `setup` guideline link if there is any!

**Comment by gtsiolis** [comment]
@vedant-jain03:
1. Contributing to Gitpod can be more complicated than other projects because of the nature of the project working on top of Kubernetes cluster, etc.
2. For the dashboard component, you can find some basic instructions in the [relevant folder](https://github.com/gitpod-io/gitpod/tree/main/components/dashboard), but we have not been actively maintaining that `README` file.
3. We develop Gitpod in Gitpod which means we're not running Gitpod locally to develop it.
4. Usually community contributors push a new branch or a new PR and we help by spinning a preview environment for them which deploys a preview installation of Gitpod where you can connect later with `telepresence` and make changes.

**Comment by vedant-jain03** [comment]
Sure, thanks for brief reference. 

I referred the instruction and finds out that [this](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/how-to-get-cookie.png) file is corrupted. Any alternate ref(if any) to setup cookie variable?

**Comment by gtsiolis** [comment]
@vedant-jain03 You mean the `_gitpod_io_` cookie?  You should be able to access it from the developer console in your browser. If you can't figure this out just fork the repository and open a new PR with a new branch—I can spin up a preview environment once the PR is up.

**Comment by vedant-jain03** [comment]
@gtsiolis Sure thanks, you mean empty PR?

**Comment by gtsiolis** [comment]
@vedant-jain03 I have never used the instructions for developing the dashboard component like this. Please, push a new branch with some changes or not and open a PR, and we can go from there. 🙏

**Comment by vedant-jain03** [comment]
sure, thanks!

**Comment by RayAsh37** [comment]
> * Contributing to Gitpod can be more complicated than other projects because of the nature of the project working on top of Kubernetes cluster, etc.
> * For the dashboard component, you can find some basic instructions in the [relevant folder](https://github.com/gitpod-io/gitpod/tree/main/components/dashboard), but we have not been actively maintaining that `README` file.
> * We develop Gitpod in Gitpod which means we're not running Gitpod locally to develop it.
> * Usually community contributors push a new branch or a new PR and we help by spinning a preview environment for them which deploys a preview installation of Gitpod where you can connect later with `telepresence` and make changes.

Hey @gtsiolis , Sorry to trouble you. I was able to spin up an instance of Gitpod dashboard through workspaces. I have the entire thing setup. But after the login page(The login page opens up on localhost:3000 as expected), it opens in a new browser tab and it connects to gitpod.io as a result I am unable to test my changes.

Are you aware of any solution or could you point me toward someone who could help me with this

**Comment by gtsiolis** [comment]
@RayAsh37 Spinning up preview environments for community contributions got a bit more challenging after we've switched to GH Actions. We're now merging community PRs to a branch and open a separate PR to spin up a preview environment. 😭
