### ISSUE TITLE
Allow users to close or dismiss the new workspace with options modal when opening the modal from the projects page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15696]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/15668 and the feedback in https://github.com/gitpod-io/gitpod/pull/15668#issuecomment-1379023843, :a: the current UX when a user is clicking on the `New Workspace ...` menu option from the project card is redirecting the user to the workspace start page to show the start with options modal.

In contrast, :b: when clicking `CMD+O` on the projects list the new workspace with options modal is overlapping the content and you can dismiss or close the modal by clicking the `X` button on the modal or pressing `ESC`.

Usually, for a **modal component**, there should always be multiple ways to close or dismiss this type of modal.

Although :b: does not carry any context (repository) information, which could be considered later, it can be dismissed.

Cc @svenefftinge @jldec @geropl 

| Modal with options from the project more actions menu | Modal with options from the `CMD+O` shortcut |
|-|-|
| <img width="1440" alt="Screenshot 2023-01-11 at 6 21 38 PM (2)" src="https://user-images.githubusercontent.com/120486/211860028-04c140f4-6d2a-4bfe-9362-4fc7f4b7a7df.png"> | <img width="1440" alt="Screenshot 2023-01-11 at 6 21 46 PM (2)" src="https://user-images.githubusercontent.com/120486/211860041-0687cb91-ad51-44f4-a489-13116dea22ac.png"> |

### Proposal

Following the suggestion from https://github.com/gitpod-io/gitpod/pull/15668#issuecomment-1379023843:

> The options modal should go away and return you to the dashboard when you hit escape. It should also have a close button.

**Comment by jldec** [comment]
Being unable to dismiss the modal is a bug in the implementation and unfortunately, quite jarring / surprising.

Scheduling and hoping for a quick followup fix please. 🙏 
cc: @svenefftinge @selfcontained
