### ISSUE TITLE
Ability to create new workspace from tarball

### ISSUE THREAD

**Issue by tdensmore** [gitpod-io/gitpod#15698]
## Problem
As a user, when my workspace does not start I can download a tarball to save my work. However there is no way to create a new workspace from that tarball. As a user, I would have to manually determine what changes are contained in the tarball and copy and paste them into a new workspace.

## Request
Ideally I would like Gitpod to automatically create a new workspace clone from any workspace that cannot be opened.

If that cannot be done, I would like a way to create a new workspace from a tarball in the UI.
Additionally I would like the `download` button to only be visible on workspaces that are not running / be hidden on workspaces that are running.

**Comment by kylos101** [comment]
@atduarte @tdensmore are there any customers asking for this feature? If yes, could you link in https://github.com/gitpod-io/customers?

**Comment by tdensmore** [comment]
No, but I came across this during research for the tangentially related ability to disable the ability to download a tarball for security reasons.
