### ISSUE TITLE
Missing (latest) desktop editor options in the new workspace start with options modal

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15693]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/15567, the _Latest_ editor versions for the desktop IDEs (VS Code, JetBrains) are not present or selectable in the new workspace start with options modal.

Also, the _Ultimate_ and _Professional_ labels are not shown for the _IntelliJ IDEA_ and _PyCharm_ correspondingly.

See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1673438199214579) (internal). Cc @akosyakov  @easyCZ @svenefftinge

| Searching for VS Code Desktop (Latest - Insiders) | Searching for IntelliJ IDEA (Latest - EAP) |
|-|-|
| <img width="552" alt="search-code" src="https://user-images.githubusercontent.com/120486/211834174-7eae4088-905a-456d-b579-916667e5971b.png"> | <img width="552" alt="search-idea" src="https://user-images.githubusercontent.com/120486/211834186-1084e671-5adf-4ea6-9421-4e1cd3a4328a.png"> |

**Comment by svenefftinge** [comment]
I was assuming that the version between stable and latest would differ, but that doesn't seem to be the case. So instead I'll compare the image and if that is the same not show a latest version.
