### ISSUE TITLE
Do not close the editor or repository selection menu in the new start with options modal when typing a whitespace character (space)

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15690]
### Bug description

Following up from https://github.com/gitpod-io/gitpod/pull/15567 (Cc @svenefftinge @easyCZ), searching for editor name with a whitespace character in the name, like "VS Code" or "IntelliJ IDEA", does not work and closes the selection menu without selecting any option.

### Steps to reproduce

1. Open the new workspace modal with options.
2. Try typing "VS Code"

☝️ The same issue affects selecting a repository.

https://user-images.githubusercontent.com/120486/211798924-d3859b2f-9f65-4d5f-bf92-d551b41ee085.mov

**Comment by vedant-jain03** [comment]
@gtsiolis I would like to work on this issue!

**Comment by svenefftinge** [comment]
Tricky. Being able to open and close a dropdown using space is a convenient and common interaction I think. Maybe we can detect somehow that it doesn't do this when the focus is in a textinput?

**Comment by vedant-jain03** [comment]
> Tricky. Being able to open and close a dropdown using space is a convenient and common interaction I think. Maybe we can detect somehow that it doesn't do this when the focus is in a textinput?

Right, can we something like:
- When the input is empty we can use space to dropdown the dropdown.
- When the input is not empty we can use the space for concatenation to the input.

@svenefftinge WDYT?

**Comment by svenefftinge** [comment]
Yes, that sounds good to me. @gtsiolis wdyt?

**Comment by gtsiolis** [comment]
@svenefftinge This sounds like a good next iteration.

---

Some more thoughts on the topic. Cc @vedant-jain03 

>  Being able to open and close a dropdown using space is a convenient and common interaction I think.

True but only when the component is behaving like a regular [`select`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) element with a fixed range of options where a user user can select one or none, but without any search options or additional actions, etc.

☝️ In the case of a regular `select`, pressing space should :a: select the hovered option and close the dropdown or :b: just close the dropdown without any options to the selected item.

> [Pressing `Space` to select/deselect "focused" select options.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#:~:text=Pressing%20Space%20to%20select/deselect%20%22focused%22%20select%20options.)

In the workspace **class selection** closing the dropdown would make more sense when pressing space, just like when pressing escape. ✔️ 

☝️ However, that's only if by default there was a pre-selected option as seen in the closed dropdown. This should change regardless of the interaction. Opened https://github.com/gitpod-io/gitpod/issues/15912 to keep track of this.

**Comment by vedant-jain03** [comment]
> @svenefftinge This sounds like a good next iteration.
> 
> Some more thoughts on the topic. Cc @vedant-jain03
> 
> > Being able to open and close a dropdown using space is a convenient and common interaction I think.
> 
> True but only when the component is behaving like a regular [`select`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) element with a fixed range of options where a user user can select one or none, but without any search options or additional actions, etc.
> 
> point_up In the case of a regular `select`, pressing space should a select the hovered option and close the dropdown or b just close the dropdown without any options to the selected item.
> 
> > [Pressing `Space` to select/deselect "focused" select options.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#:~:text=Pressing%20Space%20to%20select/deselect%20%22focused%22%20select%20options.)
> 
> In the workspace **class selection** closing the dropdown would make more sense when pressing space, just like when pressing escape. heavy_check_mark
> 
> point_up However, that's only if by default there was a pre-selected option as seen in the closed dropdown. This could probably this change regardless of the interaction. Opened #15912 to keep track of this.

Agreed with your point @gtsiolis, I have open a PR for this iteration https://github.com/gitpod-io/gitpod/pull/15889.
