### ISSUE TITLE
Rewrite Host Headers

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#157]
Many dev servers check the host header and will deny anything that is not local by default.
We could rewrite the host header to make those dev servers work without reconfiguring.

**Comment by meysholdt** [comment]
For https://github.com/gothinkster/angular-realworld-example-app, I could work around the issue by using command `yarn ng serve --host 0.0.0.0 --disable-host-check`.

However, then `ng` discourages me with this warning:
> WARNING: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.

**Comment by jankeromnes** [comment]
FYI, we do that for Janitor, and it works relatively well:

https://github.com/JanitorTechnology/janitor/blob/45691d7c15e873ff6f5d60224b63ab2ede008faa/lib/routes.js#L553-L600

I thought about this again today, after getting another `Invalid Host Header` error while trying to gitpodify https://github.com/tyroprogrammer/learn-react-app, and this project even seems to delegate all `webpack-dev-server` stuff to its dependencies, so I didn't find a way to work around it.

Re-writing the `Host` header might help with such host-checks, but it won't rewrite URLs that are served by the web app (fortunately most web apps don't hard-code the domain in their URLs).

Also, it won't help with strict Content Security Policy rules: `webpack-dev-server` also has the great idea to enforce strict `Access-Control-Allow-Origin` or `frame-ancestor` policies, thus preventing web apps to be embedded in iframes (e.g. the Preview pane, so only Browser preview works) or from communicating across ports (e.g. API servers, but maybe this can be solved with a WebPack `proxyConfig`).

**Comment by 32leaves** [comment]
There's a `Host` header rewriting HTTP proxy written in Go here: https://gitpod.io/#snapshot/74d7f990-081d-46bf-84fa-f5b1ddf147c4

We could integrate something like that in `gp` akin to `gp forward-port`.

**Comment by svenefftinge** [comment]
What bas side effects could be caused by always rewriting the header, or at least allow a configuration on the `port` using the `.gitpod.yml´?

**Comment by jankeromnes** [comment]
If we're willing to go down a very ugly road, I think we could try something like:

1. Make the preview accept URLs like `localhost:8080/*` or `http://localhost:8080/*`, but re-write them behind the scenes to `https://8080-XXX.ws-eu0.gitpod.io/*` (user types `localhost`, sees `localhost` in Preview URL bar, and sees their app in the preview = all is good)
2. While serving such a web app, modify it on-the-fly, rewriting any `localhost:*` URL in the HTML or JS to `https://*-XXX.ws-eu0.gitpod.io`
3. In requests that go back to the dev server, rewrite any `https://*.ws-eu0.gitpod.io` HTTP headers back to `http://localhost:*`, so that the dev server is happy

This is very hacky, but I believe it could fool both the developer and the web server into making things work. One scenario where it would not work is if the web app dynamically generates or otherwise obfuscates `localhost` links before making requests, or if it does some sort of integrity checking.

**Comment by svenefftinge** [comment]
As a developer 

1) would be very confusing and way too much magic for me. Also it is leaky because the actual requests would go to a different domain (shown in dev tools) than what it shown in the URL bar. 

2) as well would be surprising and magical to me, when I see in dev tools that URLs in the code are different to how I wrote them. In many cases having a URL pointing to localhost is actually problem that I'd be happy to get pointed to.

3) seem ok to me, especially if I can explicitly enable that in the ports configuration, as the only situation you'd see this is when explicitly looking at the request headers on the server-side. But again, I wonder if that could cause any other bad side-effects we are not aware of.

**Comment by svenefftinge** [comment]
Was implemented in the meantime

**Comment by vijaykanwar** [comment]
Hi @svenefftinge 

I am facing that issue. We are using connect-modrewrite npm package to create the proxy. But it's not working for gitpod vs code. i am able to run that local host but proxy of url not working. Below code. we are using gulp. here we are running the main solution on 8282 port and when in the url contains "/vijaykanwar/" , it's call other solution which is running on 8181. port both solution run on two vs code or two gitpod work space.
  $.connect.server({
        root: ENV.dev.folder,
        port: 8282,
        livereload: true,
        middleware: function (connect, opt) {
            var modRewrite = require('connect-modrewrite');
            return [
                modRewrite([
                    `^/appsapp/(.*)$ http://${devhost}:8080/apps/$1 [P]`,
                    `^/vijaykanwar/(.*)$ http://${devhost1}:8181/$1 [P]`
                ])
            ];
        }
    });

Thanks
Vijay kanwar
