### ISSUE TITLE
Yaml file 'dockerfile.yml' are assigned with a wrong file icon

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1570]
![image](https://user-images.githubusercontent.com/11302521/83371254-408a2680-a3c2-11ea-8756-666b3e43ff19.png)

**Comment by Kreyren** [comment]
cc @akosyakov

**Comment by akosyakov** [comment]
Please move to theia repo, someone can have a look at it there. Theia relies on 3rd party library to detect an icon for the file path. It probably does name matching.

**Comment by Kreyren** [comment]
Transferred to https://github.com/gitpod-io/gitpod/issues/1570
