### ISSUE TITLE
connect to browser service from vscode extension - problems

### ISSUE THREAD

**Issue by rholland** [gitpod-io/gitpod#1571]
The VSCode extension below simplifies github searches.  It opens a github search in a browser.

https://marketplace.visualstudio.com/items?itemName=ettoreciprian.vscode-websearch

Its behavior in gp is to open the preview window, never prompt for a port, provide the correct search url and report that the github.com connection is refused.  I can click on the correctly formed url which then opens a search window correctly in the browser. Is there a way to pass through the search url directly to my local browser as it does in the desktop version of VSCode?

Thanks.  Love gp.

**Comment by Kreyren** [comment]
I am also unable to open to open GitHub in theia, seems to me as duplicate of https://github.com/gitpod-io/gitpod/issues/1528

CC @jankeromnes for confirmation for the root of the issue
