### ISSUE TITLE
[slo] start prebuild error budget is burning

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#15721]
### Bug description

[We're recently burning through our start prebuild error budget too quickly.](https://pyrra.gitpod.io/objectives?expr={__name__=%22workspace-start-prebuild-success-ratio%22,%20namespace=%22monitoring-central%22,%20team=%22workspace%22}&grouping={}&from=1673474480411&to=1673560880411)

![image](https://user-images.githubusercontent.com/1272076/212190770-707411c1-dbac-43cd-96ae-f4be477f910d.png)

![image](https://user-images.githubusercontent.com/1272076/212190821-63abe43a-c57d-4bdf-b211-c8f2645c3cd4.png)

### Steps to reproduce

n/a

### Expected behavior

The error budget should not be going down, unless we expect it to.

### Anything else?

Reassign the issue to @Furisto (on-call now) during his normal working hours on Friday, but, while he sleeps, please research why it is burning, reach out to the on-call team as needed.

I assume our metric is flawed in gen82, or, there was a change (IDE or webapp) that is causing an unusually high # of prebuilds to fail starting.

**Comment by jenting** [comment]
[Start workspace success ratio is dropping](https://pyrra.gitpod.io/objectives?expr={__name__=%22workspace-start-workspace-success-ratio%22,%20namespace=%22monitoring-central%22,%20team=%22workspace%22}&grouping={}&from=1672965970289&to=1673570770289) as well.

**Comment by jenting** [comment]
The [GCP log](https://console.cloud.google.com/logs/query;query=-resource.labels.container_name%3D%22calico-node%22%0A-resource.labels.container_name%3D%22ws-proxy%22%0A-resource.labels.container_name%3D%22workspace%22%0A-resource.labels.container_name%3D%22fluentbit-exporter%22%0A-resource.labels.container_name%3D%22kubelet-stats-exporter%22%0Aresource.labels.container_name%3D%22ws-manager%22%0Aresource.labels.cluster_name%3D%22ws-us82%22%0Aseverity%3DERROR%0AjsonPayload.metadata.annotations.%22gitpod%2Fnever-ready%22%3D%22true%22;timeRange=P2D;summaryFields=jsonPayload%252Fconditions%252Ffailed:false:32:beginning;lfeCustomFields=jsonPayload%252Fconditions%252Ffailed;cursorTimestamp=2023-01-12T18:48:20.200352363Z?_ga=2.76063126.2081798697.1673524797-362368038.1651710660&project=workspace-clusters) for workspace failed and workspace pod never ready.

**Comment by jenting** [comment]
> cannot initialize workspace: cannot find snapshot.

The problem started on Jan 8, 6 PM. 

I did an investigation, according to the Jaeger tracing [[1](https://jaeger-eu-prod.workspace-preview.gitpod-io-dev.com/trace/2217900db2deb0ed)], [[2](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/trace/7545e51f06337c0d)], and [[3](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/trace/1ba5fa384be949ef)]. I can't find the related snapshot on the object storage.

**Comment by kylos101** [comment]
> [Start workspace success ratio is dropping](https://pyrra.gitpod.io/objectives?expr=%7B__name__=%22workspace-start-workspace-success-ratio%22,%20namespace=%22monitoring-central%22,%20team=%22workspace%22%7D&grouping=%7B%7D&from=1672965970289&to=1673570770289) as well.

Yes @jenting , however, burn rate is so low that I think it is okay? At least given it's current "burn".

**Comment by kylos101** [comment]
@jenting given the traces that you shared (thank you), I suspect what is happening, is that the URL to a [snapshot](https://www.gitpod.io/docs/configure/workspaces/collaboration#workspace-snapshots) was being used to start a new workspace, however the underlying snapshot is no longer valid (was probably [deleted](https://www.gitpod.io/docs/configure/workspaces/collaboration#sharing-running-workspaces:~:text=Deleting%20and%20managing%20snapshots%20%2D%20If%20you%20want%20to%20remove%20any%20created%20snapshot%20URLs%2C%20deleting%20the%20workspace%20directly%20removes%20any%20created%20snapshot%20URLs%20associated%20with%20that%20workspace.)).

Why do I suspect a snapshot that has had its source worksapce deleted? The workspace ID (like `fuchsia-fly-xkuqh3dh5fh`) in all three cases was random, instead of `org-repo-random`.

When I check [this trace](https://jaeger-eu-prod.workspace-preview.gitpod-io-dev.com/trace/2217900db2deb0ed), the initializer looks like this:

```
"initializer": {
        "snapshot": {
            "snapshot": "workspaces/<redacted>/snapshot-1670002948719429142.tar@gitpod-prod-user-<redacted>"
        }
    },
```

I created [this snapshot](https://gitpod.io/#snapshot/9d711766-14d1-4e8c-a9aa-3624fe7fb0e1) from an empty workspace, which can be used to start a workspace. In my case, I just created `harlequin-cat-uifimy1moab`, which you can see a trace for [here](https://jaeger-us-prod.workspace-preview.gitpod-io-dev.com/trace/104bf1b318ae7a8a). The initializer is structured similarly as above:

```
  "initializer": {
        "snapshot": {
            "snapshot": "workspaces/<redacted>/snapshot-1673630874408709453.tar@gitpod-prod-user-<redacted>"
        }
    },
```
I just deleted the source workspace, but, I suspect `server` hasn't done the actual garbage collection (because I can still create new workspaces from the snapshot URL). So, that GC will likely take two weeks from now.

May I ask you to inbox an issue to webapp team? Ideally `server` would check a snapshot is valid, prior to trying to start a workspace. It might delegate that decision to `content-service`, but, should check before asking `ws-manager` to start a workspace.

cc: @geropl @svenefftinge

**Comment by kylos101** [comment]
@jenting please close this issue, after inboxing an issue to the webapp team? :pray:

**Comment by jenting** [comment]
> @jenting please close this issue, after inboxing an issue to the webapp team? 🙏

Create two issues as follow up:
- #15732 for injecting the git binary if not present in the base image
- #15746 for checking the prebuild snapshot is valid before sending request to the ws-manager

closing this issue.
