### ISSUE TITLE
Put CORS as a warning around ports visibility

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#15731]
## Is your feature request related to a problem? Please describe

Context [here](https://gitpod.slack.com/archives/C01KPEPNBD0/p1673622109707029)

Maybe we could show an warning or tooltip for the `ports` fields on `.gitpod.yml`? And also for the vscode/jetbrains prompt when a port is detected to be open.

**Comment by akosyakov** [comment]
I think maybe adding something `Learn More` on ports view will make it easier to discover docs.

I'm not sure about tooltip/notifications/warnings. Private is default, and these things can be quite noisy, besides how can you detect whether it is an issue? If we could answer this question the warning diagnostic could make more sense.

**Comment by axonasif** [comment]
> besides how can you detect whether it is an issue

To be honest, I don't know.

> I think maybe adding something Learn More on ports view will make it easier to discover docs.

👍 

> I'm not sure about tooltip/notifications/warnings.

Maybe we add a note about it the description of `ports` or `visibility` property?
- https://github.com/gitpod-io/gitpod/blob/b1c79598993585ea445c14f42e2db5a2b0fa359e/components/gitpod-protocol/data/gitpod-schema.json#L9
- https://github.com/gitpod-io/gitpod/blob/b1c79598993585ea445c14f42e2db5a2b0fa359e/components/gitpod-protocol/data/gitpod-schema.json#L38
