### ISSUE TITLE
Workspace list page does not display all available workspaces

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#15743]
### Bug description

In https://gitpod.io/workspaces, under "inactive workspaces" only 20 workspaces are displayed.
Important workspaces that were not pinned (and not older than 14 days) cannot be found.

### Steps to reproduce

1. Create (and stop) more than 20 workspaces.
2. Go to https://gitpod.io/workspaces
3. Click on "Inactive Workspaces"
4. You will see only the last 20 workspaces

### Expected behavior

All workspaces that are not deleted should be available, either by displaying the full list, adding a pager, or make it into "infirinte scroll".

### Anything else?

I was able to find my missing workspace by using "search" at the top of workspaces page.

**Comment by axonasif** [comment]
👋 @shaal
I checked my workspaces list but I seem to have 25, I counted them as well.
<img width="1133" alt="Screenshot 2023-01-17 at 5 35 09 PM" src="https://user-images.githubusercontent.com/39482679/212888943-6ed4af3b-d381-4cea-92d3-d06777949a86.png">

**Comment by axonasif** [comment]
if you can still reproduce the issue, could you please paste the console logs here?

**Comment by YoungElPaso** [comment]
I cannot see any workspace that's older than 6 months...and all of them were pinned.

**Comment by axonasif** [comment]
Hi @YoungElPaso, I think you need to change the org namespace from the top-right drop-down menu.
Does that help? Please let me know.
