### ISSUE TITLE
Search: showing duplicate results for the same query

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#1575]
### Describe the bug

Search view is showing duplicate results for the same quey view the below screenshot.

![image](https://user-images.githubusercontent.com/46004116/83721637-ebb20e80-a654-11ea-9245-2ce2dfbd6295.png)

I'm expecting it to show and highlight what matches the current query value, not the previous states query value.

### Steps to reproduce

Open up a new workspace for https://gitpod.io/#https://github.com/gitpod-io/website/ and try searching for something i.e "console.log"

**Comment by jankeromnes** [comment]
Many thanks for reporting this @nisarhassan12! I see this all the time, and it's quite annoying (I've now trained myself to wait for duplicate results, then remove + re-add the last letter to remove the old results)

**Comment by corneliusludmann** [comment]
https://github.com/eclipse-theia/theia/issues/7282
