### ISSUE TITLE
docker buildx build never stops

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#15766]
### Bug description

`docker buildx build` hangs forever, also could be reproduced with `docker export` if an image is built with `--squash`.

Not sure whether it is a bug with docker itself, or some IO limiting, or how we run docker in workspaces?

<img width="853" alt="Screenshot 2023-01-16 at 13 59 05" src="https://user-images.githubusercontent.com/3082655/212719189-cfd008c0-0636-4c51-af03-30d681688398.png">

### Steps to reproduce

- Create a Dockerfile with `FROM gitpod/workspace-full:latest`
- Run `docker buildx build -o outdir .`
- You maybe need to try several times, but eventually it will stuck and never finish.

### Expected behavior

does not hang

**Comment by jeanp413** [comment]
Looks like a buildx bug indeed, I let it run for half an hour and it didn't finish  :laughing:

![image](https://user-images.githubusercontent.com/25115070/212941837-85bacd4c-e407-4953-b90b-2b1641b8a5db.png)

**Comment by kylos101** [comment]
:wave: hey there, @akosyakov @jeanp413 ,

I ran a test with buildctl and buildkitd (below), did not have any issues, but, do observe "it takes a while" and "uses a lot of free space".

[From a gitpod workspace for buildkit](https://gitpod.io/#https://github.com/moby/buildkit):
```
pushd /workspace/buildkit/cmd/buildctl
go build .
popd

pushd /workspace/buildkit/cmd/buildkitd
go build .
popd

sudo /workspace/buildkit/cmd/buildkitd/buildkitd --debug --group gitpod --root=/workspace/buildkit &

mkdir ./test-me
echo "FROM gitpod/workspace-full:latest" > ./test-me/Dockerfile

pushd ./test-me
buildctl build  --frontend=dockerfile.v0  --local context=. --local dockerfile=.
popd

```

I am going to close this issue for now. Let us know if anything else is needed?

cc: @utam0k
