### ISSUE TITLE
Improve feedback widget UX

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15760]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/issues/10307, which contains a list of minor improvements for the feedback widget, there's also some text overlapping happening when a user is submitting feedback with long text where the feedback emojis are hiding parts of the text.

See also relevant discussions[[1](https://gitpod.slack.com/archives/C01KPEPQYE6/p1673735310904849)][[2](https://gitpod.slack.com/archives/C01KPEPNBD0/p1673877377941769)][[3](https://gitpod.slack.com/archives/C0420AN379Q/p1673725464390859)] (internal) Cc @loujaybee @mbrevoort 

Cc @jldec as we've briefly discussed this in a past sync.

| Feedback widget with long text |
|-|
| <img width="1440" alt="Screenshot 2023-01-16 at 4 30 28 PM (2)" src="https://user-images.githubusercontent.com/120486/212702539-ffe57e22-811b-46f4-88b0-33ecdb5bf692.png"> |

### Proposal

:a: A boring (simple) solution could be to limit the scrolling area above the feedback emojis.

:b: Alternatively, moving the feedback emojis in the bottom left corner inside the modal could also work.

Long term, we could probably spent some more time exploring a different design for the feedback widget.

| :a: | :b: |
|-|-|
| <img width="1440" alt="Screenshot 2023-01-16 at 4 40 39 PM (2)" src="https://user-images.githubusercontent.com/120486/212704228-457b5a8c-2321-4b03-bd42-b3563a4ab86e.png"> | <img width="1440" alt="Screenshot 2023-01-16 at 4 40 31 PM (2)" src="https://user-images.githubusercontent.com/120486/212704259-78e8091b-8c04-4d09-8c26-94fa57507fcd.png"> |

**Comment by vedant-jain03** [comment]
@gtsiolis I would love to work on this issue if this is open for `community contribution`!

**Comment by gtsiolis** [comment]
Thanks @vedant-jain03! Every open issue without an assignee is probably available to pick up. 🍒

**Comment by vedant-jain03** [comment]
> Thanks @vedant-jain03! Every open issue without an assignee is probably available to pick up. cherries

Sure, thanks!
I will work on it!
