### ISSUE TITLE
Code has suddenly turned white

### ISSUE THREAD

**Issue by leeton1412** [gitpod-io/gitpod#1577]
### Describe the bug
All code has suddenly started to appear in white. This includes all pages and css

### Expected behavior
Code would normally be multi-coloured in order to help see the different elements.

### Additional information
This is occuring on all web browsers not just chrome. Have tried restarting but to no result

### Example repository
the repository it happened on is Cosmic-Rodney

**Comment by jankeromnes** [comment]
@leeton1412 Sorry about this. Does it also happen when you create a new Gitpod workspace for that same repository? (You can simply add `gitpod.io/#` in front of the GitHub repository URL.)

**Comment by jankeromnes** [comment]
Sounds like a re-occurrence of https://github.com/gitpod-io/gitpod/issues/1291

**Comment by leeton1412** [comment]
Sorry I'm pretty new to all this. I'm not sure what you mean with a new
repository. I have read that topic you mentioned but the refresh doesnt
work for me and f1 will not bring up typescript in the search box. I've
tried creating new files in gitpod in the same repository and it doesnt
work either

**Comment by jankeromnes** [comment]
Thank you for checking out these things.

I meant a new Gitpod workspace, not a new GitHub repository.

Concretely, please click on: https://gitpod.io/#https://github.com/leeton1412/cosmic-rodney

This will create a new Gitpod workspace based on your same GitHub repository. (Also, please don't worry, all your previous Gitpod workspaces can be found at https://gitpod.io/workspaces/ )

I expect that in the new workspace, the code will not be white.

**Comment by leeton1412** [comment]
No problem,

I tried to create a new workspace following the link you provided but
unfortunately its still all in white.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
