### ISSUE TITLE
PowerShell in gitpod/workspace-full

### ISSUE THREAD

**Issue by peterbb148** [gitpod-io/gitpod#158]
As PowerShell seems to be the more and more the defacto scripting platform for managing cloud resources with wide support in both AWS, GCP and Azure I think adding PowerShell to the gitpod/workspace-full would make Gitpod the best development environment for PowerShell scripting.

**Comment by svenefftinge** [comment]
We should check having proper PowerShell language support, too.

**Comment by dfinke** [comment]
I see syntax highlighting is there, the PS vsc ext is coming?

**Comment by svenefftinge** [comment]
We'd like to reduce the size of workspace-full. But you can install powershell for your workspace, of course.
Here's an example https://github.com/svenefftinge/gcp-snapshots
