### ISSUE TITLE
Explorer is empty even when files exist in workspace

### ISSUE THREAD

**Issue by jagtesh** [gitpod-io/gitpod#1583]
### Describe the bug
Explorer view is empty, instead of showing the files in the current folder in a tree structure.

### Steps to reproduce
1. Open the workspace
2. Explorer is empty

### Expected behavior
Explorer shows all files and folders not in .gitignore file.

### Additional information
![image](https://user-images.githubusercontent.com/27375/83978429-638e6c00-a8d5-11ea-8da0-73b40eae8349.png)
[workspace link](https://e3a3078f-6710-420f-bf6a-8d07bf995383.ws-us02.gitpod.io/#/workspace/libdeleg8)

**Comment by Kreyren** [comment]
CC @jankeromnes

**Comment by jagtesh** [comment]
If it helps, I was able to get it to work by using Cmd-P to open a file that exists in the project. Then everything started showing up in explorer once again.

**Comment by sr229** [comment]
Might be a bug in the file watcher where it doesn't listen to any file changes that aren't created through the IDE.

**Comment by sr229** [comment]
No longer seeing this bug so I think we can close this. @svenefftinge, can you confirm?
