### ISSUE TITLE
Slowness or unavailability of the Projects view after data-layer change

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15845]
The projects list feels more sluggish now, and some users have [reported (_internal_)](https://app.frontapp.com/open/cnv_km7deyy?key=9pYCg2So8Hk9DdsqWgJFf7-EXGFVVje5) failure to load their projects - seeing just a spinner in some cases. 

Others have noticed that what used to load quickly and then re-paint with a new ordering after some time, now shows a spinner for some time, and then the sorted list with no re-paint.

This started after #15676 - Add react-query to Projects page in Dashboard

**Comment by gtsiolis** [comment]
Cross-posting from the [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1674061370212589?thread_ts=1674061075.038479&cid=C02EN94AEPL) (internal) for visibility:

> @gtsiolis:  This happens when loading the projects for the first time.
> @gtsiolis:  Switching to other teams as well as the personal account loads the projects ok.
> @gtsiolis: Also, force reloading the initial selected teams loads the project successfuly.
