### ISSUE TITLE
Epic: Collect information from users during onboarding

### ISSUE THREAD

**Issue by phimae** [gitpod-io/gitpod#15857]
**Context** The current form fields that we have do not give us sufficient information about our users who sign up. This issue is to improve the success and completeness of initial information gathered during onboarding. 

**Value:** We would like to capture more information about our users during the first time product onboarding. By doing so we can offer better support for our users. 

**Measurement**
- Increase in % of successful company website form submissions
- Increase in % of valid first + last name 
- No significant degradation in onboarding conversion

|Update Profile Information|IDE selection modal|Start new workspace|Phone number verification|
|-|-|-|-|
|if (user has not already provided info **AND** is 24 hours after user sign up) **OR** the last update was 1 year ago |If user has no IDE preference, shown after login (typically first)|Open workspace modal, this information is asked for when clicking "_new workspace_"|If user .... AND on workspace start|
|![image](https://user-images.githubusercontent.com/5528307/219387702-2d7147bf-3c12-411b-b921-6006a6b3e00c.png)|<img width="875" alt="image" src="https://user-images.githubusercontent.com/5528307/219388048-f538dab8-96a0-4292-b0ce-3fb27a30320f.png">|<img width="550" alt="image" src="https://user-images.githubusercontent.com/5528307/219388395-70171bc4-1af8-4b17-975e-f1d97093296a.png">|-|

---

## Design Decisions

* ☑️ First name + Last name presented to user as separate
* ☑️ Ask for company email, not company
* ☑️ Ask for IDE preference during onboarding flow
* ☑️ Consolidate both IDE selection and profile information modals
* ☑️ Implement as either a modal, or a full page 
* ☑️ Implement the onboard as a three step, not a one step flow
* ☑️ Steps will not be dismissible, but some fields will be optional / skippable. 
* ☑️ We won't show a step indicator for now
* ⁉️ Validate fields on each step (if possible), submit at end (if possible)
* ⁉️ Ordering of the three step flow (personalisation first?)

### Work

- https://github.com/gitpod-io/gitpod/pull/16568
- https://github.com/gitpod-io/gitpod/pull/16569
- https://github.com/gitpod-io/gitpod/pull/16545
- https://github.com/gitpod-io/gitpod/pull/16570
- https://github.com/gitpod-io/gitpod/pull/16543
- https://github.com/gitpod-io/gitpod/pull/16501
- https://github.com/gitpod-io/gitpod/pull/16469
- https://github.com/gitpod-io/gitpod/pull/16467

### Future Iterations

1. Bump the existing user base for information (mark tainted data for some users)
1. Request additional qualification information (company size)
1. Request additional disqualification information (students)
1. Re-prompt on subsequent logins if not entered information
1. Move information gathering async (notifications center)
1. Request for information in other parts of the product experience
1. Introduce monetary incentive to submit information (e.g. credits)

<details>
    <summary>Previous issue contents</summary>
See internal [RFC](https://www.notion.so/gitpod/Bring-light-into-the-user-black-box-Ask-for-more-information-d239d92f611641778a251952cb011a70) for more context.

**Current Behavior** 
The current update profile information modal is shown on second login but the larger part of users don't log in again but still could be an interesting persona from a target company. 
<img width="487" alt="Untitled (5)" src="https://user-images.githubusercontent.com/83109781/213244291-502b77c2-0521-4305-83a5-eddb1b58ecdd.png">

**Intended Changes**

- Maintain existing modal
- Change it to show on sign-up, and not on following sign-in
- Remove "Dismiss" button. The close button is already there.
- Remove avatar
- Split the "Name" to "First Name" and "Last Name". _I understand that "Full Name" would be better, but I'm afraid most won't bother_
- Email remains
- Replace Company with Company Website. _We should maximize the chances that it is correctly formatted, without increasing friction. Maybe adding a placeholder example or starting already with "www."?_
- Remove Git related text from description.

This modal does not need to show in Gitpod Dedicated

_Potential Future Iterations_

- Greet the user with their first name in the dashboard (e.g. Hi Bob, start your first workspace with cmd + O)
- If no company website is given but a team is created, prompt to ask for company domain
- Include this modal with the IDE selector / the cmd+ O quickstart modal as a "get started" flow (Step 1, 2 ..)
- Match domain with others -> no others --> invite colleagues. If >2 others --> Get in touch with your colleagues and create a team
- After creating a team --> there are xx other users from xyz.com, invite them to your team (from projects screen)
- Matching users with the same domain name

Related issues: 
- https://github.com/gitpod-io/gitpod/issues/13116
</details>

**Comment by jldec** [comment]
Scheduled for next iteration.

See original design in https://github.com/gitpod-io/gitpod/pull/11023

Note that the prompt happens on the 2nd day after signup (I believe it's independent of whether the user logs in or not).

**Suggestions**
- The change for the prompted fields should be applied to both the modal and the user settings.
- The modal does not require the blurb at the top about git env-variables.

**Comment by phimae** [comment]
Thanks @jldec!

> Note that the prompt happens on the 2nd day after signup (I believe it's independent of whether the user logs in or not).

Correct, with this issue I am proposing to show it right after signup so that we may get information from the 77% of users who never log in a second time (but with information we can still reach out to them)

> The change for the prompted fields should be applied to both the modal and the user settings.

100% - thanks for the catch

> The modal does not require the blurb at the top about git env-variables.


Agree, that's what I meant with "Remove the description text about the Git configuration if possible"

**Comment by svenefftinge** [comment]
We might want to have an explicit "Welcome to Gitpod" experience, that includes initial setup steps and information, such as editing profile information, but also things like picking preferred IDE, etc. It seems like bolting on modal after modal isn't an ideal experience for new users :seedling:

@gtsiolis Do you have the capacity to design a welcome page that includes the information this ticket asks for and the initial IDE setting, as well?

**Comment by gtsiolis** [comment]
Thanks for hanging here, everyone! Took a closer look at the linked RFC and the problem statement above. 👀 

Listing some thoughts below:

1. It's worth noting that the editor selection is a mandatory step for every new user signing up, even if they won't go through the dashboard.
2. The problem of users not coming back is probably not related to the editor selection or profile update step but that's a different discussion.
3. The idea @svenefftinge describes above in https://github.com/gitpod-io/gitpod/issues/15857#issuecomment-1396920120 to combine the editor selection and the profile update sounds good.
    - Could be worth ordering the editor selection first so that users actually can get some value out of this action.
    - We could minimize the profile information layout by shrinking the avatar, skipping (or removing completely the company field, and removing the variables related information at the top.
5. The proposal above[[1](https://github.com/gitpod-io/gitpod/issues/15857#issuecomment-1396633818)][[2](https://github.com/gitpod-io/gitpod/issues/15857#issuecomment-1396641476)] to remove the Git and variables related information on the profile update step sounds absolutely logical. This was probably left there as a first iteration (skateboard) to get this in the sooner, see relevant comment in https://github.com/gitpod-io/gitpod/pull/11023#discussion_r911136492.
6. Renaming _Email_ to _Work Email_ sounds good.
7. Using a field for the _Company_ name was being tracked in https://github.com/gitpod-io/gitpod/issues/11182 but we never got around it. Maybe it does not help much or create a good incentive for the user to bother updating this, see also relevant comment in https://github.com/gitpod-io/gitpod/issues/11182#issuecomment-1177305755.
    - Does it make sense to measure how many users have actually set this field?
    - Isn't the work email sufficient for what's needed here?
8. I'd highly recommend avoiding splitting the name into two fields for first name and last name. Instead, we could rename _Name_ to _Full Name_.
9. To create some basic incentive for users to bother updating their full name or work email, we could use the section subheading.
    - Currently, this information is only used for authoring commits.
    - Later on, we could use this to suggest teams to join, etc, see screenshots below.

Taking into the above, I made some quick drafts on how this could looks like as a modal or a full page.

| Welcome (Modal) | Welcome (Full page) |
|-|-|
| <img width="1440" alt="Welcome-Modal" src="https://user-images.githubusercontent.com/120486/213733319-ee9e68f5-2ece-48aa-9699-1ae82c6b5aa8.png"> | <img width="1440" alt="Welcome-Full" src="https://user-images.githubusercontent.com/120486/213733333-f8fa99d7-d40a-47be-86fc-d17673c5f8b2.png"> |

**Comment by svenefftinge** [comment]
I think we could use multiple pages so they are less crowded. Also the "you are logged in as foo from GitLab" doesn't seem helpful. Can we do without?

**Comment by gtsiolis** [comment]
> Can we do without?

We can start without it, although it does provide a hint that an account has been created or associated with the form below.

> We could use multiple pages so they are less crowded.

Something like a two-step flow?

| Step 1 | Step 2 |
|-|-|
| <img width="1440" alt="Welcome" src="https://user-images.githubusercontent.com/120486/213744102-403db6d5-905c-47c4-818a-74ba91ade0b7.png"> | <img width="1440" alt="Welcome-1" src="https://user-images.githubusercontent.com/120486/213744115-d40eba82-f2b7-4594-9ef7-2c670327017b.png"> |

**Comment by phimae** [comment]
Hi @gtsiolis! Thanks for your reply and the nice looking drafts. Really like the two bars that indicate what's coming. I also thought about having a third step that just says "start workspace" but I think @svenefftinge wasn't a big fan when we discussed. 

> The problem of users not coming back is probably not related to the editor selection or profile update step but that's a different discussion.

I agree - my point was more about missing out on a substantial share of users whose information we would never get if we kept it on 2nd day (as they don't come back for a 2nd session)

> skipping (or removing completely the company field

We would like to name it company website and keep it please

> Does it make sense to measure how many users have actually set this field?

We do that already through the `profile_changed` track call - 3% currently change the company name

> I'd highly recommend avoiding splitting the name into two fields for first name and last name. Instead, we could rename Name to Full Name.

Understand how that feels unnecessary, but there are two reasons why this is important: 1. We can personalise comms for the user better (so far we can only say "Hey there" or "Hey gtsiolis") and 2. we need a proper name split into first and last for enrichment


> To create some basic incentive for users to bother updating their full name or work email, we could use the section subheading.
Currently, this information is only used for authoring commits.
Later on, we could use this to suggest teams to join, etc, see screenshots below.

Love that, would be great if we could demonstrate value for the user with this! Had some similar thoughts in the Future Iterations paragraph in the issue description

**Comment by phimae** [comment]
Hi @svenefftinge and @gtsiolis - just came back from PTO and wanted to check in to see if there have been any discussions around this while I was out?

**Comment by atduarte** [comment]
Given the constrained capacity, I would suggest we go with something very small for now.

To get to a decision faster I will suggest a set of changes, but if you feel strongly about any feel free to change:
- Maintain existing modal
- Remove "Dismiss" button. The close button is already there.
- Remove avatar
- Split the "Name" to "First Name" and "Last Name". _I understand that "Full Name" would be better, but I'm afraid most won't bother_
- Email remains
- Replace Company with Company Website

👍 ?

**Comment by loujaybee** [comment]
Hey folks, going to close this, we're currently looking into future iterations, but the first iteration is now out. 

|-|-|-|

<img width="650" alt="image" src="https://user-images.githubusercontent.com/5528307/221841847-4cb3a115-cded-41ea-9e03-2c1e9c799933.png">
<img width="683" alt="image" src="https://user-images.githubusercontent.com/5528307/221841886-65568325-f7b0-4615-9a0b-dc38aa5edcae.png">
<img width="716" alt="image" src="https://user-images.githubusercontent.com/5528307/221841916-251f30b6-d2b0-4e82-9553-bdfa2380a9c2.png">

**Comment by loujaybee** [comment]
Hey folks, going to close this, we're currently looking into future iterations, but the first iteration is now out. Will attach some screenshots of the final design for future reference, and close out this issue, thanks all ! 🙏 

|Step 1|Step 2|Step 3|
|-|-|-|
|<img width="650" alt="image" src="https://user-images.githubusercontent.com/5528307/221841847-4cb3a115-cded-41ea-9e03-2c1e9c799933.png">|<img width="683" alt="image" src="https://user-images.githubusercontent.com/5528307/221841886-65568325-f7b0-4615-9a0b-dc38aa5edcae.png">|<img width="716" alt="image" src="https://user-images.githubusercontent.com/5528307/221841916-251f30b6-d2b0-4e82-9553-bdfa2380a9c2.png">|
