### ISSUE TITLE
Updated `AutoscaleFailure` alert to consider impact on users

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#15863]
## Is your feature request related to a problem? Please describe

Current AutoscaleFailure fires without user impact. What is essential in an alert is whether or not the user is affected. Update to take this into account. 
https://github.com/gitpod-io/gitpod/blob/478a75e744a642d9b764de37cfae655bc8b29dd5/operations/observability/mixins/workspace/rules/central/nodes.yaml#L48-L56

ws-manager retried creating a workspace pod for 10min in order to address waiting for auto-scaling.  Hence there is no user impact unless autoscaling fails for an extended period in a row. 

## Describe the behaviour you'd like

Fire this alert when it actually the users are affected by failing autoscaling

For example, this query could be used to determine whether or not the actual failure.
```
sum(gitpod_server_instance_starts_failed_total{reason="clusterSelectionFailed"})
```

**Comment by kylos101** [comment]
@utam0k may I ask, as on-caller, how come you did not add this to our board (it looks like you added to our inbox only)? I ask because this would be good to do this week, to help avoid unnecessary alerts this week and in the future.

**Comment by utam0k** [comment]
> @utam0k may I ask, as on-caller, how come you did not add this to our board (it looks like you added to our inbox)? I ask because this would be good to do this week, to help avoid unnecessary alerts this week and in the future.

Does `our board` means our ground work?

**Comment by utam0k** [comment]
> @utam0k may I ask, as on-caller, how come you did not add this to our board (it looks like you added to our inbox)? I ask because this would be good to do this week, to help avoid unnecessary alerts this week and in the future.

I created PR https://github.com/gitpod-io/gitpod/pull/15916
But sorry, I'm not sure what should have done.
