### ISSUE TITLE
Replace the custom SVG icon used for the search loading state with the Loader component

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15896]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/15804, the spinner element used to replace the rotating magnifier icon is a custom SVG. However, we do have a [`Loader`](https://github.com/gitpod-io/gitpod/blob/e940a97c0fe5ab3709a37918a71d07b26a8917a9/components/dashboard/src/components/Loader.tsx) component using an SVG under the hood, which we could replace to use and maintain a consistent icon across the product, see relevant comment in https://github.com/gitpod-io/gitpod/pull/15804#pullrequestreview-1261792254. Cc @andrew-farries @Ciggzy1312 

### Proposal

Replace the custom SVG icon used for the search loading state with the [`Loader`](https://github.com/gitpod-io/gitpod/blob/e940a97c0fe5ab3709a37918a71d07b26a8917a9/components/dashboard/src/components/Loader.tsx) component.

### Risks

Could be worth exploring whether the [`Loader`](https://github.com/gitpod-io/gitpod/blob/e940a97c0fe5ab3709a37918a71d07b26a8917a9/components/dashboard/src/components/Loader.tsx) component is too large to fit into the search input. If that's the case, aligning the size to fit alla cases or introducing two component sizes (small, large) could be the besrt way forward.

**Comment by Ciggzy1312** [comment]
On it, will link a PR once done

**Comment by gtsiolis** [comment]
@Ciggzy1312 This looks like a good MVC. We can slightly reduce the spinner thickness to make it also look better in the search input.

**Comment by Ciggzy1312** [comment]
@gtsiolis looks like the thickness of the Spinner SVG cannot be reduced. So I have added the new SVG to the Loader component and rendered it based on the optional prop I am passing to fit the Spinner in the search bar

Sounds right or am doing something wrong?

**Comment by gtsiolis** [comment]
@Ciggzy1312 The Loader component is build with the [spinner SVG](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/icons/Spinner.svg) icon. I was thinking of replacing the SVG for all spinner instances with a new slightly thinner version, like the following:

![spinner](https://user-images.githubusercontent.com/120486/214096423-f2bed5a1-ec09-434e-ab48-dd4e874c80ac.png)


Let me know what you think—I'm also attaching below an optimized SVG version:

```svg
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 16">
  <path fill="#A8A29E" fill-rule="evenodd" d="M9.42871.944336C8.26855.324219 6.97266 0 5.65723 0v3c2.76172 0 4.99997 2.23828 4.99997 5 0 2.7617-2.23825 5-4.99997 5-1.38086 0-2.63086-.5605-3.53516-1.4648L0 13.6572c.494141.4932 1.04883.918 1.64844 1.2657.53027.3076 1.0957.5537 1.68652.7324 1.25879.3818 2.59277.4472 3.88281.1914 1.29004-.2569 2.49805-.8281 3.51463-1.6621.4697-.3858.8916-.8213 1.2598-1.2989.4297-.5566.7851-1.1699 1.0557-1.8242.5039-1.2158.7001-2.53611.5712-3.84568-.0732-.74414-.25-1.4707-.5224-2.16016-.208-.52441-.4717-1.02734-.7881-1.5-.7305-1.09375-1.7197-1.99121-2.87989-2.611324Z" clip-rule="evenodd"/>
</svg>
```

**Comment by Ciggzy1312** [comment]
@gtsiolis looks great, more compatible with the UI
Should I replace the current spinner with this new one in this PR itself?

**Comment by gtsiolis** [comment]
Seems like a trivial change which can be included in the same PR, but feel free to open a separate PR if you run into any issues or large code changes so that we can review and merge faster as a smaller [MVC](https://www.notion.so/gitpod/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e#0c2e0d6c8a99404b97ccdc206b573d72).
