### ISSUE TITLE
Error: "Failed to connect to X gitpod workspace" when setting up SSH keys for VS Code Desktop

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#15919]
"Failed to connect to X gitpod workspace"

**Steps to replicate:** 
* Open VS Code Desktop without SSH setup
* Follow prompt to SSH page
* Return to VS Code Desktop after browser redirect

<img width="404" alt="image" src="https://user-images.githubusercontent.com/5528307/213651262-33680e19-1483-4ce1-97e2-2c1aad5322b5.png">

**Note:** Please excuse the image resolution, it is taken from a screen recording, will try to get another higher resolution! 

**Expected result:** 
* No error message, instead a prompt such as: restart workspace "I have enabled my SSH keys" 

**Actual result:** 
* When returning to VS Code Desktop you are presented with a connection error

**Comment by jeanp413** [comment]
@loujaybee what redirect are you referring to?  

> instead a prompt such as: restart workspace "I have enabled my SSH keys"

you don't need to restart, your new added key is valid in all currently running workspaces
