### ISSUE TITLE
Preselect editor and class on the new workspace modal on first load

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#15912]
### Problem to solve

Currently, when opening the new open-in-gitpod modal in the dashboard, there's a preselected **editor** and **class**. However, if you open (toggle) the dropdown, there's no preselected option.

### Proposal

Preselect editor and class on the new workspace modal on first load.

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="Screenshot 2023-01-20 at 12 39 48 AM (2)" src="https://user-images.githubusercontent.com/120486/213578675-df3ffdc4-f286-4b5a-874d-aab80c0d82a5.png"> | <img width="1440" alt="Screenshot 2023-01-20 at 12 39 51 AM (2)" src="https://user-images.githubusercontent.com/120486/213578687-b8965bc8-3921-4b5e-8781-d4995aeb96df.png"> |
| <img width="1440" alt="Screenshot 2023-01-20 at 12 40 00 AM (2)" src="https://user-images.githubusercontent.com/120486/213578695-2ab3d9ac-1759-4026-a6bd-0b1c7ebdbc4d.png"> | <img width="1440" alt="Screenshot 2023-01-20 at 12 40 01 AM (2)" src="https://user-images.githubusercontent.com/120486/213578698-cb2cb37a-0d1e-4858-8550-42d2eeadf313.png"> |

**Comment by yashikajotwani12** [comment]
I would like to work on this issue.

**Comment by Siddhant-K-code** [comment]
You're welcome, @yashikajotwani12! Feel free to mention this issue once you open a pull request to resolve this. 🏓

**Comment by yashikajotwani12** [comment]
> You're right @yashikajotwani12! The idea is to highlight the preselected editor.

Okay! Thanks for clarifying.
