### ISSUE TITLE
docker-up does not work in rootless image

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#15917]
### Bug description

Try to use `docker build` in https://github.com/gitpod-samples/template-elixir It is also not visible to us from GCP logs.

[Internal discussion](https://gitpod.slack.com/archives/C03NWNHJ163/p1674201430253809?thread_ts=1674146960.028529&cid=C03NWNHJ163)

### Steps to reproduce

See above.

**Comment by utam0k** [comment]
@akosyakov 
There are two conditions, right?
- a workspace comes from a rootless image
- this image doesn't have docker, docker-compose, etc...

**Comment by kylos101** [comment]
/werft run with-integration-tests=workspace with-large-vm=true

**Comment by kylos101** [comment]
Routing to IDE inbox, as @akosyakov is working the issue already in https://github.com/gitpod-io/gitpod/pull/15924

cc: @laushinka

**Comment by akosyakov** [comment]
I removed it from IDE. We are going to bundle docker cli for gitpod cli instead.

**Comment by kylos101** [comment]
@akosyakov okay, I'll close as not planned for now, and remove from Workspace project, too.
