### ISSUE TITLE
Allow .devcontainer/Dockerfile to be used as base image

### ISSUE THREAD

**Issue by alblue** [gitpod-io/gitpod#1592]
The current GitHub codespaces beta uses .devcontainer/Dockerfile for its use. You can enable both GitPod and GitHub codespaces by adding a .gitpod.yml file as follows:

```
image:
  file: .devcontainer/Dockerfile
```

The GitPod workspace picks up the other settings from the .vscode folder in both places, so the link between the image and the dockerfile is now the only thing that's needed to get started in both. If you could automatically infer this file, if:

1. The GitPod.yml file doesn't exist and/or doesn't have an image: block
2. The .devcontainer/Dockerfile exists

then it would be great :)

**Comment by alblue** [comment]
Hmm. Sadly it’s not quite as easy as I thought. The Docker build runs from the root of the workspace, whereas the .devcontainer runs from the .devcontainer folder, so (e.g.) the maven-settings.xml file isn’t pulled from the right place.

http://github.com/alblue/jvmulator Is a project that works in GitHub codepsaces, and I want to enable it to run in GitPod at the moment. The docker build file fails because the maven-settings.xml file can’t be found.

```
e82f1330-1946-413e-a9c4-67cb0ff1df18
alblue/jvmulator - master
Created 5 minutes ago
alblue/jvmulator
master
35af7281
Last run 4 minutes ago: Error: build failed: cannot build base image: COPY failed: stat /var/lib/docker/165536.165536/tmp/docker-builder989594123/maven-settings.xml: no such file or directory
Download
Start
```

**Comment by alblue** [comment]
The docker content in #62 allows the docker container to be located anywhere, but the context that the docker file runs in is still assumed to be the root of the repository. It would be good if you could specify that the docker content came from somewhere else.

**Comment by Kreyren** [comment]
Checking..

Btw. Who have you murdered to get the access to githubpod

**Comment by Kreyren** [comment]
@alblue What kind of action do you expect here?

I would think that you could replace the paths with some variable and then define it in gitpod.io/settings and it's equivalent on githubpod O.o

i.e
```Dockerfile
COPY $myRoot//maven-settings.xml /usr/share/maven/ref/
```

but without the access to githubpod i don't think this should be actionable for gitpod especially during githubpod's development that may change this.

also `WORKDIR` not an option?

**Comment by alblue** [comment]
The issue isn’t the work dir is wrong ... it’s that docker is being run from a different location on GitHub pod and so it fails at the COPY step.

If you go to https://github.com/alblue/jvmulator and click on the ‘open in gitpod’ you’ll see it doesn’t work. That’s because what’s happening when it builds the container is:

$ cd /workspaceroot; docker build . -file .devcontainers/Dockerfile

What appears to be happening on GitHub pod is:

$ cd /workspaceroot/.devcontainers; docker build .

As a result the `COPY` doesn’t pick up the maven-settings.xml file in gitpod, but it works in githubpod.

It would be great if you could just open a githubpod project in gitpod without needing to add extra content. So something like:

```
If [ ! -f .gitpod.yml -a -f .devcontainers/Dockerfile ] {
  cd /workspacerot/.devcontainers
  Docker build . -f Dockerfile
}
```

The alternative would be to require having a .githpod.yml file similar to:

```
Image:
  File: Dockerfile
  Dir: .devcontainers
```

Which would then do the same thing.

Happy to test out any proposed fixes, or you can use the alblue/jvmulator as a reference for something that’s known to work on githubpod.

**Comment by alblue** [comment]
https://github.com/alblue/jvmulator/commit/e497e6fe6457bb2048ec3df5eb4e31157af6871d Is the commit which just has the githubpod files; if you can make that work in gitpod without needing any extra files, that would be great.

**Comment by Kreyren** [comment]
@alblue I don't know how i feel about this in the long term assuming that it may be possible for github to change the workdir during the development making the effort worthless. O.o

***kreyren** is going to check if he can make a quick implementation in gitpod-layers*

**Comment by Kreyren** [comment]
@alblue Can you provide an output from `pwd` on githubpod in case it's saving the files in a directory that is not `/workspace/project` ?

**Comment by alblue** [comment]
I used that as an example - I don’t know what the directory is, and it probably doesn’t matter. The issue is that it’s running the docker build from the .devcontainers directory, wherever it’s checked out.

You can reproduce this on the command line outside of GitHub/GitPod:

```
$ git clone https://github.com/alblue/jvmulator
$ cd jvmulator
$ docker build . -file .devcontainers/Dockerfile # fails
$ cd .devcontainers
$ docker build . -file Dockerfile # works
```

**Comment by alblue** [comment]
By the way, here are the projects for the .devcontainers that are used by Codespaces:

https://github.com/microsoft/vscode-dev-containers

Their instructions are ‘drop a .devcontainers’ repo into the root of your repository

You’ll probably find that the majority of containers work because they’re not copying resources. However, the Java one (which I based my project on) has maven-settings.xml in the .devcontainers directory.

If GItHub avoids using this folder in future, you could just failsafe - if .devcontainser/Dockerfile isn’t present, don’t use it.

**Comment by alblue** [comment]
https://github.com/microsoft/vscode-dev-containers/tree/master/containers/java-11 Is the one I used as my template

**Comment by Kreyren** [comment]
> Their instructions are ‘drop a .devcontainers’ repo into the root of your repository

I see so that should make it less likely to change in the future :thinking: 

but i don't have an access to relevant codeblock so dropping from assignment atm unless @jankeromnes provides it ^-^

**Comment by jankeromnes** [comment]
Hey @alblue, I'm late to the party, but would a `.gitpod.yml` like this work?

```yml
image:
  file: .devcontainer/Dockerfile
  context: .devcontainer
```

**Comment by Kreyren** [comment]
@jankeromnes As far as i understood this expects gitpod to work without changes on githubpod repository :thinking:

**Comment by alblue** [comment]
Thanks @jankeromnes that’s exactly the undocumented behaviour I’m looking for :)

So I can confirm that having made that change I’m able to have a GitPod and GitHub Codespaces project in the same place, by using the .devcontainer/Dockerfile to boot the same image.

While it’s not necessarily needed, it would be useful for GitPod to be able to synthesise that file as in the above-but-one comment if the .devcontainer/Dockerfile exists. That way, people who have set up a project for GitHub codespaces will automatically be able to use GitPod.

That said, the workspace I opened from it is still stuck in the ‘pulling docker images’ step, so maybe there’s still an issue? Can you open my jvmulator project in gitpod now I’ve made the change?

**Comment by alblue** [comment]
Given that GitPod is now open-source, do you have any pointers about how I could create a PR for this feature?

**Comment by JesterOrNot** [comment]
@alblue So you're proposing Gitpod looks for the .devcontainer/Dockerfile if no image / Dockerfile is provided?

**Comment by alblue** [comment]
Yes, along with the `context: .devcontainer` as well.
