### ISSUE TITLE
Unable to start my workspace

### ISSUE THREAD

**Issue by isontheline** [gitpod-io/gitpod#1593]
### Describe the bug
Hello Gitpod Team ;)

I have been fired from my workspace while working. Then when I launch it again I have this error :
> Error: 2 UNKNOWN: cannot start workspace: workspaceExists: the server has received too many requests and has asked us to try again later (get pods)
> Please file an issue if you think this is a bug.

Could you check my trouble ?

Have a nice day !

### Steps to reproduce
Just launching my workspace

### Expected behavior
A working workspace of course :)

### Additional information
ID : d3a780e5-####-####-####-8d8a240dd271

**Comment by aineon** [comment]
I'm having the same problem!

**Comment by stefdworschak** [comment]
Same problem here.

**Comment by lechien73** [comment]
Same issue here

**Comment by Archierowe** [comment]
Same issue here

**Comment by isontheline** [comment]
Oups :(
> Stopping - Started 39 minutes ago: last backup failed: workspace does not exist. Please contact support if you need the workspace data.

**Comment by Kreyren** [comment]
Same issue on my end
![image](https://user-images.githubusercontent.com/11302521/84405334-47a60580-ac08-11ea-80a1-7c8bf7065466.png)

**Comment by alesanchezr** [comment]
Seems to be in europe, USA is working fine.

**Comment by jankeromnes** [comment]
Many thanks for the reports. We're currently investigating this problem.

**Comment by jankeromnes** [comment]
It seems that Gitpod had a partial outage in EU between 14:20 UTC and 16:00 UTC, likely triggered by high load, but EU service seems to be recovering now.

We're still investigating what caused this incident.

**Comment by jankeromnes** [comment]
EU service seems fully restored now. Please let us know if you're still seeing issues (e.g. with starting/stopping workspaces, or restoring work-in-progress).

**Comment by jankeromnes** [comment]
@isontheline Your last workspace session (started `2020-06-11T14:27:04.516Z`) is still on the server. Please let me know if it contains some data that you'd like to get back.

**Comment by Kreyren** [comment]
Works for me now

**Comment by isontheline** [comment]
> @isontheline Your last workspace session (started `2020-06-11T14:27:04.516Z`) is still on the server. Please let me know if it contains some data that you'd like to get back.

@jankeromnes Thank you but it seems that data in the pod container is older than the GIT repository, so I don't need the data. Thank you for your help anyway !

**Comment by Kreyren** [comment]
***kreyren** also wanted to complain about proper management for the host system to avoid halting on 100% of utilization of any system resource, but he realized that it would require too much explaining and so he's rather silent~*
