### ISSUE TITLE
Remove Usage-Based Billing feature flag

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#15949]
Remove `isUsageBasedBillingEnabled` feature flag 

https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-652c-4bae-88be-17963da63a1c

**Comment by geropl** [comment]
1. remove all code referencing it: https://github.com/gitpod-io/gitpod/pull/16015
2. Remove the flag itself

**Comment by geropl** [comment]
Put on hold on request from Sven: https://github.com/gitpod-io/gitpod/pull/16015#issuecomment-1402268229
