### ISSUE TITLE
Unable to open workspace - I tried multiple times and I appear to have broken it!

### ISSUE THREAD

**Issue by Archierowe** [gitpod-io/gitpod#1595]
### Describe the bug

OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 55585013760, capacity: 57639526400
Please file an issue if you think this is a bug.

**Comment by Archierowe** [comment]
I thought the workspace was being slow - clicked several times to open the workspace and I appear to have broken it! Argh - please help!

**Comment by alesanchezr** [comment]
the same, this is only in europe.

**Comment by Kreyren** [comment]
Assuming duplicate of https://github.com/gitpod-io/gitpod/issues/1593

Ping me if it's unrelated
