### ISSUE TITLE
Mark user-level Git Auth as Deprecated

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#15963]
Let's deprecate them in UI and docs for now.

Removal is out of scope here.

**Comment by AlexTugarev** [comment]
@geropl, after thinking once more about this, it only make sense to deprecate this once the organizational Git Auth is GA. 

But we can already add this to the UI behind the same feature flag. 

cc. @selfcontained

**Comment by geropl** [comment]
@AlexTugarev Fine with that.

Also, happy to descope it/mark as optional in the context of #15955. I just hoped this is relatively easy if we piggy-back the organization-migration. Your call! :+1:
