### ISSUE TITLE
[JetBrains] Investigate why Ruby on Rails template is not working with RubyMine

### ISSUE THREAD

**Issue by felladrin** [gitpod-io/gitpod#15969]
# Description

When opening https://github.com/gitpod-samples/template-ruby-on-rails-postgres, RubyMine fails to connect to it.

It was confirmed [here](https://github.com/gitpod-io/gitpod/pull/15513#issuecomment-1399779349). We need to investigate what's causing this failure.

Other ruby repositories are working fine on RubyMine [[1](https://github.com/gitpod-io/gitpod/pull/15513#issuecomment-1398719552)].

<img width="477" alt="image" src="https://user-images.githubusercontent.com/55068936/213964604-d9807ce3-2d42-4f9f-911a-6b4e7dfcdddf.png">

We suspect the RubyMine Prebuild might be causing it in this repo.

**Comment by felladrin** [comment]
ℹ️ I've tried forking https://github.com/gitpod-samples/template-ruby-on-rails-postgres and opening on RubyMine, but it resulted in the same: got stuck in "Connecting".

**Comment by Siddhant-K-code** [comment]
It seems to be working now :)

![image](https://github.com/gitpod-io/gitpod/assets/55068936/ab606693-71b5-40ba-a712-9df8d750e91b)
