### ISSUE TITLE
[PROPOSAL]: Consider VS Code

### ISSUE THREAD

**Issue by maximousblk** [gitpod-io/gitpod#1596]
The UI and and features are due an upgrade. Gitpod lacks many of the latest VS Code features.

Why is it so?

[skip to main](#issuecomment-643373370)

**Comment by Kreyren** [comment]
@maximousblk Because gitpod is **NOT** Visual Studio Code.

TypeFox (The maintainer of gitpod and co-creator of Theia) is using Theia (https://github.com/eclipse-theia/theia) as the frontend which is a standalone project that is just taking inspiration from the vscode UI and supports the vscode extensions. ^-^

What kind of features would you like on gitpod?

**Comment by maximousblk** [comment]
@Kreyren I'm really sorry. I did not know that. Gitpod just looks very similar to older versions of VS Code.

P.S. Would using VS code for Gitpod be considered at any point? projects like [cdr/code-server](https://github.com/cdr/code-server) would make it possible to do so.

**Comment by Kreyren** [comment]
@maximousblk I see vscode being inferior to theia so i personally don't see any reason to provide vscode other then GNU ethics to support everything atm O.o

Is there any specific reason to why you want to use vscode that cannot be done on theia? There is a strong possibility that theia already has that function and you might not aware of it :p

**Comment by maximousblk** [comment]
> I see vscode being inferior to theia

How so?

**Comment by Kreyren** [comment]
> How so? @maximousblk 

From the major differences
- Respects four freedoms
- Actively supports Free and Open-Source movement
- Not made by Microsoft or other company that does it's best to ruin FOSS.

The rest:
- Has most of the functionality of vscode implemented excluding things that are legally blocked like omnisharp that has license permitting it to run only on vscode.
- Works on anything that has a web browser with javascript
- Has linux terminal with 16 threads available for compilation and stuff

**Comment by maximousblk** [comment]
[cdr/code-server FAQ](https://github.com/cdr/code-server):
> code-server takes the open source core of VS Code and allows you to run it in the browser.

The rest:

 - [x] Has most of the functionality of vscode implemented excluding things that are legally blocked like omnisharp that has license permitting it to run only on vscode.
- [x] Works on anything that has a web browser with javascript
- [x] Has linux terminal with 16 threads available for compilation and stuff (depends on the container)

---

I GitPod used VScode, it could be a competitor to [Github Codespaces](https://github.com/features/codespaces/)

I'm reopening this issue and changing the title.

**Comment by Kreyren** [comment]
> If GitPod used VScode, it could be a competitor to Github Codespaces

How is gitpod not a competitor to GitHub Codespaces? Gitpod implemented the same idea sooner and the implementation seems to be so far better based on information that is available O.o

Quick examples:
- Github Codespaces doesn't support sharing snapshots of the code or sharing the workspace by itself.
- Doesn't seem to support caching

**Comment by maximousblk** [comment]
> How is gitpod not a competitor to GitHub Codespaces? [...] Is not even production ready

Yes that is why they're not yet comparable.

Pricing will be the biggest factor. Github is Planing for a pay-per-use model contrary to Gitpod which has premium tiers for those who need more features.

How will CodeSpaces be a competition?

- Native extension marketplace ([not possible in gitpod](https://github.com/cdr/code-server/blob/master/doc/FAQ.md#differences-compared-to-vs-code))
- Native to GitHub (gitpod is not)
- You can also personalize your codespace by pulling in dotfiles. (maybe?)
- You can use it from within VS code (probably not possible for gitpod)

---

But now that I think about it, The biggest problem is the major infrastructural change that is required for this to happen, which is not worth the discussed features.

closing

**Comment by Kreyren** [comment]
> Native extension marketplace (not possible in gitpod)

Theia support vscode extensions though O.o

> Native to GitHub (gitpod is not)

Hmm True O.o

> You can also personalize your codespace by pulling in dotfiles. (maybe?)

You can do this on gitpod already afaik

> You can use it from within VS code (probably not possible for gitpod)

How would that even work?

> But now that I think about it, The biggest problem is the major infrastructural change that is required for this to happen, which is not worth the discussed features.

Disagree assuming info provided above -> Reopening

**Comment by jankeromnes** [comment]
Hi @maximousblk!

> The UI and and features are due an upgrade. Gitpod lacks many of the latest VS Code features.

We are constantly upgrading the UI and features of Gitpod.

Please list specifically which "latest VS Code features" seem to be missing in Gitpod -- that way we'll be able to work on them.

> code-server takes the open source core of VS Code and allows you to run it in the browser.

See also https://theia-ide.org/

Gitpod uses Theia as its IDE, and Theia also uses open-source components of VSCode, but was re-architected to be more flexible & extensible (e.g. to build custom IDEs) and to work better in a cloud context (e.g. to make better hosted development services).

On a side note, Theia is fully open-source, vendor-neutral, and it's used as a base for many tools/services like:
- Gitpod
- Google Cloud Shell (IDE)
- Arduino Pro IDE
- Arm mbed studio

... and many others.

> - Native extension marketplace (not possible in gitpod)

See also https://open-vsx.org which is an open-source vendor-neutral VSCode extension marketplace that can be self-hosted and/or integrated natively into any product or service like Gitpod, Theia, VSCodium, Coder, and even VSCode.

OpenVSX is already the default extension marketplace for Theia, and native integrations are coming soon to Gitpod and to other aforementioned tools.

**Comment by Kreijstal** [comment]
ok so you listened to this guy, but uh, I hope you don't stop supporting theia :/

**Comment by akosyakov** [comment]
@Kreijstal please see https://github.com/gitpod-io/gitpod/issues/3475#issuecomment-801020229 We will support it for sometime, but in long term it does not make sense for us anymore. Please though if you have any issues with VS Code we should resolve them, so file new issues to provide feedback.

**Comment by gbraad** [comment]
I am glad this happened. Is there an issue to check what is configured and enabled? As so far I do not see it is possible to enable extensions ... right?

**Comment by akosyakov** [comment]
Everything should work similarly to your desktop experience already. If not please file an issue and elaborate how it breaks.
