### ISSUE TITLE
Cleanup old Feature Flags (Team Workspace)

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#15978]
Internal link to [zombie report](https://gitpod.slack.com/archives/C03NTLVU134/p1674459916442329)

workspace_classes
workspace_classes_backend
protected_secrets
movedImagedBuilder

The assumption is that they've already unused on the webapp side, and need to be removed from ConfigCat.

**Comment by kylos101** [comment]
Related to WKS-90
