### ISSUE TITLE
Can't load anymore https://github.com/EOSIO/eosio-web-ide

### ISSUE THREAD

**Issue by iamveritas** [gitpod-io/gitpod#1597]
### Describe the bug
this link used to work
https://gitpod.io/#https://github.com/EOSIO/eosio-web-ide
now it yields below result:

```
We are having trouble parsing your context
Error: GitHub API Error. Status: 403
Please file an issue if you think this is a bug.
```

### Steps to reproduce
try to open https://gitpod.io/#https://github.com/EOSIO/eosio-web-ide

### Expected behavior
it should load gitpod wiht generic eosio-web-ide

**Comment by jankeromnes** [comment]
Hi @iamveritas,

> Error: GitHub API Error. Status: 403

This sounds like a connection issue with GitHub, which would probably be unrelated to the https://github.com/EOSIO/eosio-web-ide project.

Also, I am able to open that project without issues. Please double-check GitHub permissions in https://gitpod.io/access-control/ and maybe try again a bit later (sometimes GitHub randomly rejects some requests but then it works again later).

**Comment by iamveritas** [comment]
now it works. I've tried several times before I files this issue. I don't know what caused this.
