### ISSUE TITLE
Teams without credits can be selected as the default billing account

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15982]
_NOTE: this issue may be moot given #15665 however the current behavior has caused some confusion, hence recording here for awareness._

Users are able to select any team in which they are a member for their [default billing account](https://www.gitpod.io/docs/configure/billing#configure-personal-billing). This does not make sense for teams which have no credits, in which case the selection of that team will trigger an immediate out-of-credits warning.

![Screenshot 2023-01-23 at 14 40 20](https://user-images.githubusercontent.com/849592/214067335-50bd7bcf-40c2-4aca-8416-2c22214af3ed.png)

- create a new team
- go to your personal billing settings
- select the new team as you default billing account

**Comment by svenefftinge** [comment]
I think that's fine as is, also we are going to remove this switch pretty soon
