### ISSUE TITLE
Constant GitHub shortages

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1598]
Issues alike https://github.com/gitpod-io/gitpod/issues/1597 seems to be very common on gitpod -> Implement gitpod retrying connection to GitHub API as an attempt to avoid fatal?

**Comment by jankeromnes** [comment]
True, having a retry mechanism for GitHub API calls sounds like a good idea.

What may be tricky is to properly differentiate between actual errors (e.g. the repository URL you're trying to open actually doesn't exist) vs GitHub errors (for some reason, GitHub is just saying "not now", but you can try again in 2 minutes and it will work).

**Comment by Kreyren** [comment]
> GitHub is just saying "not now", but you can try again in 2 minutes and it will work).

In which case i would implement an error screen with a 'retry' button for this GitHub API fatal.
