### ISSUE TITLE
Unlimited access

### ISSUE THREAD

**Issue by Birch1993** [gitpod-io/gitpod#1599]
I'm not able to access unlimited gitpod from Code Institute, there was an error accessing my username. I deleted an account and created a new one with the same email and they cannot find the account but can access the old account

**Comment by jankeromnes** [comment]
Hi @Birch1993, please contact @lechien73 about this, or email support@gitpod.io if this seems like a bug in Gitpod.

FYI, I can confirm that you have two Gitpod accounts (same email, same name), both created on `2020-04-13`.

To make sure that the account you're currently using is properly set up, please head to https://gitpod.io/access-control/ and make sure that your GitHub and/or GitLab accounts are properly associated (at least one checkbox should be checked -- if not, please check a box, and update). This may resolve the problem. (If not, please use the support email above.)
