### ISSUE TITLE
SSO configuration UI enhancements

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15995]
This is a followup to #15903.

#### enhancements 
- "Name" input, becomes the name shown in the list of providers, and later in the Login UI.

#### wording changes:

> ## SSO
> Configure OpenID Connect single sign-on providers.
> ### OpenID Connect providers
> Configure single sign-on for your organization.
> #### No OIDC providers
> Enter the client ID, client secret, and other information issued by your identity provider, to enable single sign-on for your organization. 
> [New OIDC Provider]

![Screenshot 2023-01-23 at 20 27 04](https://user-images.githubusercontent.com/849592/214147147-8a33f6be-addc-4095-b950-aff8d1674b31.png)

---

![Screenshot 2023-01-23 at 20 53 51](https://user-images.githubusercontent.com/849592/214147822-407ce12e-fc1c-4580-a2e9-b0e3eb503c79.png)

---

![Screenshot 2023-01-23 at 20 49 57](https://user-images.githubusercontent.com/849592/214147223-3b9a5ba1-2290-4e23-9a5e-fcea5c21872b.png)

**Comment by vedant-jain03** [comment]
@jldec I would love to contribute, can I work on this issue?
