### ISSUE TITLE
UX Enhancements and Questions

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#160]
Hi,

I wasn't sure whether to open an issue for each of my bugs/suggestions/questions or not. If I should, then just tell me and I will split the following into several issues, but I thought it a bit off, as I have quite a few issues/questions ;)

Questions:
1) Can I change syntax highlighting anywhere? Would like to have the same as in Eclipse.
1) Are there keyboard shortcuts to switch focus between editor/terminal/etc?
1) Can I add snippets as in Eclipse, e.g. I type "fore" and autocomplete proposes a foreach loop template?
1) Is it possible to change the auto formatting somehow?
1) Is there a status indicator for the project build having finished/ is running? Did not see one.

Bugs?:
1) Ctrl+C/Ctrl+V does not work in terminal. Right-Click and then selecting copy/paste works
1) Shift+left/right/pos1/end does not work in terminal when I try to select text.
1) Several keyboard shortcuts (e.g. Shift+Alt+O for organize imports) are not working. Ctrl+Shift+P is a workaround for all of them and works
1) Format Document/Selection does not work for XML? (a pom.xml in my case)
1) Changing the pom.xml of a project results in a popup asking me if I want to  synchronize the Java classpath/configuration. Although I chose "Always" as option, Gitpod keeps asking me the same question each time I change the pom.xml
1) Share running workspace seems to have some flaws or I'm using it wrong:
   1) When I share a running workspace with a colleague and then stop the sharing he still is able to write to my workspace until he refreshes the window. He is not actively kicked from my workspace as I would have expected
   2) When sharing a running workspace and a colleague joins this workspace his avatar is not shown in the upper right corner or anywhere else.
1) When I have two monitors and remove the tab with Gitpod from chrome on the first one and then move this tab to the second one then the terminal stops working and is blank.

UX Enhancements (Bugs?)
1) Git:
   1) Commit and Push could be in one view instead of two. I always have to switch between both
   1) Right now I have to add each file to the staging area individually by clicking the + sign. It wuold be nic to select all files I want to add and then DnD them to the staging area.
1) Alt+Up/Down moves code lines up and down but the indentation is broken afterwards. So if I move a line of code into a method then it is indented the same amount as the method signature. I would have expected it to be indented more than the method signature.
1) JavaDoc is not shown in autocompletion. I would like something like in Eclipse where the JavaDoc is shown for each method that I preselect in autocompletion.
1) Quickfixes with Ctrl+. have to be invoked directly on the word that is underlined in red. It would be nice to be able to invoke this on the line the error is in, as in Eclipse. For several errors then there could be several quickfixes being proposed.

Despite all these (minor) issues and being a Eclipse fan for many years I have to say that Gitpod/Theia is awesome and could easily become my favorite IDE! I currently would love to use it for just **everything** I'm doing at work! Thanks a thousand times for such a great piece of software ;)

**Comment by svenefftinge** [comment]
Hey Sandared,

thank you for all the feedback. It would indeed be nice to have individual tickets, so they can be discussed individually. We haven't really focussed on the Java experience specifically and are aware of many of the issues you raised. So far it was JavaScript/TypeScript that had our focus. Java and Go are next.
Here's some short feedback on some of the items. The rest are pretty valid enhancement requests (including the unanswered questions) and should really go into their own item.


> Questions:
> 
> Can I change syntax highlighting anywhere? Would like to have the same as in Eclipse.

No. Ticket (in https://github.com/theia-ide/theia) would be great

> Are there keyboard shortcuts to switch focus between editor/terminal/etc?

No. Ticket (in https://github.com/theia-ide/theia) would be great

> Can I add snippets as in Eclipse, e.g. I type "fore" and autocomplete proposes a foreach loop template?

No. Ticket (in https://github.com/theia-ide/theia) would be great.

> Is it possible to change the auto formatting somehow?

It depends on the formatter (language server). 
A ticket specifically for the languages you care (in https://github.com/theia-ide/theia) would be great.

> Is there a status indicator for the project build having finished/ is running? Did not see one.

Yes, in the status bar. But you are not the first who didn't see it. We should improve that.

> Ctrl+C/Ctrl+V does not work in terminal. Right-Click and then selecting copy/paste works

It works for me (Chrome and OSX). Could you file a ticket (in theia) and share your system info?

> Shift+left/right/pos1/end does not work in terminal when I try to select text.

It is a terminal so the typical navigation doesn't work.

> Several keyboard shortcuts (e.g. Shift+Alt+O for organize imports) are not working. 

Ticket (in https://github.com/theia-ide/theia) would be great.

> Format Document/Selection does not work for XML? (a pom.xml in my case)

We don't have real support for XML. But that is definitely on the list.
https://github.com/gitpod-io/gitpod/issues/163

> Changing the pom.xml of a project results in a popup asking me if I want to synchronize the Java classpath/configuration. Although I chose "Always" as option, Gitpod keeps asking me the same question each time I change the pom.xml

Yes, that is very annoying. Ticket (in https://github.com/theia-ide/theia) would be great.

> Share running workspace seems to have some flaws or I'm using it wrong:
> When I share a running workspace with a colleague and then stop the sharing he still is able to write to my workspace until he refreshes the window. He is not actively kicked from my workspace as I would have expected

Please file a ticket here.

> When sharing a running workspace and a colleague joins this workspace his avatar is not shown in the upper right corner or anywhere else.

It works for me (just tested). If you can reproduce it, please file a ticket with your systems information.

> When I have two monitors and remove the tab with Gitpod from chrome on the first one and then move this tab to the second one then the terminal stops working and is blank.

That, too, works here. We all work with two screens. Please share the details about your setup.

> Git:
> Commit and Push could be in one view instead of two. I always have to switch between both
> Right now I have to add each file to the staging area individually by clicking the + sign. It wuold be nic to select all files I want to add and then DnD them to the staging area.

+1 We discussed that last week, already.

> Alt+Up/Down moves code lines up and down but the indentation is broken afterwards. So if I move a line of code into a method then it is indented the same amount as the method signature. I would have expected it to be indented more than the method signature.

It should work like that, once we enable auto format.

> JavaDoc is not shown in autocompletion. I would like something like in Eclipse where the JavaDoc is shown for each method that I preselect in autocompletion.

If you see the (i) icon you have to press CTRL+Space a second time.
<img width="479" alt="screenshot 2018-11-30 at 09 07 55" src="https://user-images.githubusercontent.com/372735/49276714-8c7fa680-f47f-11e8-9d42-ba2d60dcb371.png">
<img width="691" alt="screenshot 2018-11-30 at 09 08 00" src="https://user-images.githubusercontent.com/372735/49276719-8f7a9700-f47f-11e8-846e-f93db3834f72.png">

> Quickfixes with Ctrl+. have to be invoked directly on the word that is underlined in red. It would be nice to be able to invoke this on the line the error is in, as in Eclipse. For several errors then there could be several quickfixes being proposed.

Please file a ticket.

Again, thank you so much for the feedback. Would be really great if you could file the tickets. :heart:

**Comment by Sandared** [comment]
Thanks for this detailed answer :) I will file the tickets you mentioned.
