### ISSUE TITLE
Is there a way to delete a prebuilt workspace?

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#1600]
I want to delete the prebuilt workspace so that I can test changes to my init tasks.

**Comment by jankeromnes** [comment]
@markfirmware Unfortunately, there isn't yet a way to see prebuilds & delete them, however:

- Pushing any change to your branch will trigger a new prebuild
- When you try to open a workspace while the prebuild is still running, you can spy on the prebuild logs, or choose to "skip prebuild" (which means "leave the prebuild running but start a non-prebuilt workspace now")
- You can also manually force a prebuild, by using the URL prefix `https://gitpod.io/#prebuild/https://github.com/<user>/<repo>`

**Comment by Kreyren** [comment]
Seems as duplicate of https://github.com/gitpod-io/gitpod/issues/1453 to me
