### ISSUE TITLE
[Extension View] Add Upload action in toolbar menu

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1602]
There used to be a drag and drop dialog:
![image](https://user-images.githubusercontent.com/11302521/84569349-194e3480-ad86-11ea-922e-27f86f5d9517.png)

Which is no longer present -> Add it back since it makes the UI to seem like it doesn't support drag-and-drop of extensions

**Comment by svenefftinge** [comment]
I don't think we should add it again, because we have a search feature now. The D'n'D tiles are large and noisy, and we've had a lot of feedback about people being confused where to get extensions from. I'm concerned they would distract from the new search field and still leave the user confused.

**Comment by svenefftinge** [comment]
@akosyakov and @jankeromnes propose to add an upload command to the toolbar menu (`...`) instead
