### ISSUE TITLE
Open PR "Review in Gitpod" badges in a new tab

### ISSUE THREAD

**Issue by nicolo-ribaudo** [gitpod-io/gitpod#1603]
I'm setting up Gitpod in the [`babel/babel`](https://github.com/babel/babel) repository.

I have enabled the `addBadge` option, but it has a minor annoyance: if I open a workspace, test the new code, and then want to go back to the PR on GitHub, I either have to use the "back" browser button and close Gitpod or open a new tab and manually navigate to the PR.

The "Gitpod" button injected by the Chrome extension in repositories and PRs opens Gitpod in a new tab: would it be possible to do the same thing with the badge?

**Comment by svenefftinge** [comment]
I agree that should be symmetrical
