### ISSUE TITLE
[dashboard] Relayout navigation in dashboard

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#16046]
To simplify the UX and clarify what team context I'm acting as a user, we decided to move the org selector left and go back to a workspaces list per organization.

The current state of the design:

![image](https://user-images.githubusercontent.com/372735/216337282-769d5671-5a6c-49c3-823b-c25f99cc3ca0.png)

> This change also requires moving from a global workspaces list to one per team. It would be confusing to do that change separately.

**Comment by atduarte** [comment]
@svenefftinge will the "Feedback" button be removed?

**Comment by gtsiolis** [comment]
@atduarte It's still there—sorry, the draft design skipped that. 😇

<img width="1104" alt="Screenshot 2023-02-02 at 3 55 1" src="https://user-images.githubusercontent.com/120486/216343829-79d55c5c-70e9-41b3-8eea-2f3a00963f23.png">

Also, _Members_, _Usage_, and _Settings_ may move under the org selector in future iterations.

**Comment by atduarte** [comment]
Thank you! Love it 🧡

**Comment by mbrevoort** [comment]
That's a lot of options along the top, how should the design respond to narrower screens? Ideally, the gitpod dashboard shoul be "usable" all the way down to the size of a mobile device sized screen.

Here's a snapshot of the current state:
![image](https://user-images.githubusercontent.com/30455/216390172-fca327be-2105-497d-bda2-3b130f83fada.png)
