### ISSUE TITLE
Suppress remote OS selector from SSH extension when connecting to workspace

### ISSUE THREAD

**Issue by Omcsesz** [gitpod-io/gitpod#16058]
### Bug description

Hello, Team!

I wanted to open 
https://liuxingbaoyu-babel-fokhojkfw0k.ws-eu84.gitpod.io/ on my local VSCode installation (I have Gitpod extension, and Remote SSH extension installed), but I received no information on what goes wrong, and why I don't see the files in VSCode (see attachment). 
[RemoteDesktopDoesNotGiveInfo](https://user-images.githubusercontent.com/1839739/214947042-4dff8faf-3949-449c-8289-5ec6db58447c.gif)

Can you please fix this?

### Steps to reproduce

1. Open https://liuxingbaoyu-babel-fokhojkfw0k.ws-eu84.gitpod.io/ in a browser.
2. After opening, choose OK in "Do you want to open this workspace in VS Code Desktop?" in the right bottom corner.
3. Follow the gif attached in the Bug Description section

### Workspace affected

liuxingbaoyu-babel-fokhojkfw0k.ws-eu84

### Expected behavior

I want to receive a popup saying what went wrong instead of "Got bad result from install script".

**Comment by akosyakov** [comment]
@Omcsesz not sure whether it is related to Gitpod or Remote SSH. We will logs from your VS Code **Desktop** (not browser). Could you provide them following https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop

**Comment by Omcsesz** [comment]
@akosyakov Here they are:
[vscode-desktop-logs-20230127T124417.zip](https://github.com/gitpod-io/gitpod/files/10518967/vscode-desktop-logs-20230127T124417.zip)

**Comment by akosyakov** [comment]
@jeanp413 Could you have a look please? 🙏 

in Gitpod logs looks weird
```
[Error  - 12:16:57.635] Couldn't get identities from OpenSSH agent
Error: Failed to connect to agent
	at Socket.r (c:\Users\developer\.vscode\extensions\gitpod.gitpod-desktop-0.0.71\out\extension.js:2:690427)
	at Socket.emit (node:events:526:28)
	at Socket.emit (node:domain:475:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
[Trace  - 12:16:57.635] Identity keys:
None
[Trace  - 12:16:57.635] Registered public keys in Gitpod account:
None
```

@Omcsesz I don't see remote-ssh logs at all. Could you check that you have https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh extension installed? Do you see its logs in the output?

**Comment by Omcsesz** [comment]
@akosyakov I checked, and Remote-SSH is installed.

**Comment by akosyakov** [comment]
@Omcsesz Could you collect its logs manually please from failed window? 🙏

**Comment by jeanp413** [comment]
> in Gitpod logs looks weird

That's expected, probably doesn't have the ssh agent enabled in his machine

**Comment by Omcsesz** [comment]
@akosyakov Here it is:
[vscode-desktop-logs-20230127T155849.zip](https://github.com/gitpod-io/gitpod/files/10520691/vscode-desktop-logs-20230127T155849.zip)

**Comment by jeanp413** [comment]
@Omcsesz when you get prompted select the OS, which one are you choosing? you need to select  the remote OS so in  this case `linux`

**Comment by Omcsesz** [comment]
@jeanp413 I choose Windows. If I choose Linux, it works.

**Comment by akosyakov** [comment]
ok, we should document it. It is not client machine, but os of remote machine.

**Comment by filiptronicek** [comment]
@jeanp413 I added the troubleshooting docs in the linked PR, but as the issue title suggests, is there a way to suppress this altogether? 

From my testing, on macOS, I never get this prompt. I always get this prompt on Windows, though. We could theoretically add the SSH host to the config@`remote.SSH.remotePlatform` before connecting. I'll try that.

**Comment by jeanp413** [comment]
> We could theoretically add the SSH host to the config@remote.SSH.remotePlatform before connecting. I'll try that.

yes, If I'm not mistaken that's what happens in the end if you select the OS when prompted

**Comment by filiptronicek** [comment]
exactly

**Comment by filiptronicek** [comment]
So, this is indeed possible it seems. PR raised at https://github.com/gitpod-io/gitpod-vscode-desktop/pull/31.

cc @jeanp413
