### ISSUE TITLE
gitpod.io renders a blank white screen

### ISSUE THREAD

**Issue by jonlambert** [gitpod-io/gitpod#16068]
### Bug description

When visiting https://gitpod.io, I receive a blank white screen with some errors logged to the console. 

I have attempted to clear the application storage / cookies in the browser but it doesn't seem to fix the issue.

<img width="679" alt="Screenshot 2023-01-27 at 12 08 34" src="https://user-images.githubusercontent.com/856225/215084575-5b79a771-5f3f-4065-8490-86159966554e.png">

### Steps to reproduce

This is my first time trying out GitPod as part of an exercise evaluating different hosted cloud editor solutions. Unfortunately I'm not really in a position to attempt to put together accurate reproduction steps for this issue... but a rough estimation of what I did:

1. Visited gitpod.io
2. Created an account linked with GitHub
3. Selected a random public repo in my account
4. Loaded the environment, was prompted to add more permissions to the GitHub connection
5. Followed the alert link, added more permissions within the GitHub OAuth flow
6. Returned to the GitPod editor and refreshed the page
7. Now unable to load any pages on gitpod.io

**Comment by svenefftinge** [comment]
Sorry, @jonlambert we attempted to deploy a change that unfortunately broke the connections for a few minutes around that time.
