### ISSUE TITLE
surface image build prefix in the product

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#16064]
## Is your feature request related to a problem? Please describe

Sometimes it is useful to bust image caches, i.e. if a base image is changed or some installed tool is not pinned. A user can use imagebuild prefix to retrigger the clean build.

## Describe the behaviour you'd like

It would be good to surface this action on UI somewhere. It was suggested to add in IDE but it is not related to the current workspace, alternative could be to add it on the branch in dashboard. And surface `Open Project` in IDE which reveals the relevant branch in the dashboard.

## Describe alternatives you've considered

Docker recommends to use versioning pinning as cache busting technique in such cases that Dockerfile is changed explicitly. This approach is cleaner since it ensures that all caches are cleaned up everywhere, and everybody get the same runtime. See `cache busting` in https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
Devs often use especial ARG or ENV at the top of the file to clean caches as well. See https://www.freecodecamp.org/news/docker-cache-tutorial/

As an alternative we can remove imagebuild prefix and document to use this practice.

**Comment by gtsiolis** [comment]
Ah, cross-linking possibly related if not duplicate issues: https://github.com/gitpod-io/gitpod/issues/15400, https://github.com/gitpod-io/gitpod/issues/13636, and https://github.com/gitpod-io/gitpod/issues/7149.

Possibly [related discussion](https://gitpod.slack.com/archives/C03NWNHJ163/p1673952863990479) (internal) to support a full rebuild command that clears your cache and rebuilds the container with fresh images. Cc @loujaybee @akosyakov 

Alternatively, it could be interesting to explore a project setting which provides a manual action to `Clear Image Cache`.
