### ISSUE TITLE
Feedback Issue: Can't access Gitpod Archetecture

### ISSUE THREAD

**Issue by GLYASAI** [gitpod-io/gitpod#16075]
### Objective

<img width="528" alt="image" src="https://user-images.githubusercontent.com/21967570/215316028-7a1e8e44-d33e-4867-b813-83ce6505b6e5.png">
Can't access Gitpod Archetecture(https://www.notion.so/gitpod/Architecture-0e39e570b10f4e8ba7b259629ee3cb74)
<img width="453" alt="image" src="https://user-images.githubusercontent.com/21967570/215316095-91eb0cac-7a56-462b-8edd-d3efa2082ace.png">

**Comment by axonasif** [comment]
Hi @GLYASAI, please see https://www.youtube.com/watch?v=svV-uE0Cdjk instead.
