### ISSUE TITLE
Allow using public repositories for dotfiles

### ISSUE THREAD

**Issue by niduy** [gitpod-io/gitpod#16077]
## Is your feature request related to a problem? Please describe
If you put a public Github repo for your dotfiles without having an integration, the dotfiles won't install and you will get the following error in `~/.dotfiles.log`:
```sh
# dotfile init failed: rpc error: code = NotFound desc = no token available
```

## Describe the behaviour you'd like
Getting dotfiles shouldn't require an integration to clone the repo from anywhere

## Describe alternatives you've considered
Linking my personal Github account and work's Bitbucket account. I would imagine many would want to avoid mixing personal and professional accounts, especially if they have different tier levels

## Additional context
If this is done purely for security reasons, it should be an opt-in feature

**Comment by axonasif** [comment]
Hi @niduy, it seems to be related with:
- https://github.com/gitpod-io/gitpod/issues/14984

**Comment by axonasif** [comment]
It not essentially be a duplicate.
https://github.com/gitpod-io/gitpod/pull/16133 might fix the issue.
