### ISSUE TITLE
Upgrade to NPM 9.4

### ISSUE THREAD

**Issue by mmailaender** [gitpod-io/gitpod#16072]
## Describe the behaviour you'd like
Current NPM Version is 8.19.3 Upgrade Docker container to the latest major version 9.4.0

**Comment by Siddhant-K-code** [comment]
👋🏽 @mmailaender. We are in the process of publishing a new workspace image (https://github.com/gitpod-io/workspace-images/pull/966), very soon.

Till then you can follow [our docs to use specific node/nvm versions](https://www.gitpod.io/docs/introduction/languages/javascript#updating-node-versions).
