### ISSUE TITLE
gp timeout set allows >24 hour timeout (and < 1s)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16085]
The docs for `gp timeout set` [[1](https://www.gitpod.io/docs/references/gitpod-cli#set)] states that the workspace timeout cannot be set to exceed 24 hours "**maximum workspace timeout is 24 hours**", however current `gp timeout set` allows for higher values than 24 hours to be entered. 

* **Expected result:** `gp timeout set` returns an error message if value is set higher than 24hours
* **Actual result:** `gp timeout set` allows to set an above 24 hours value without error. 

We should also set a sane upper and lower default: e.g. somewhere between 3 days to 1 week (requires discussion) which could potentially be overridden by contacting Gitpod directly, or in certain circumstances, however the current command allows you to set values into the 100's of years + (e.g. `gp timeout set 2000000h` => success, which is 228 years). Also the current command allows you to set very low timeouts, e.g. < 1 minute, which can be done in error. 

|Setting timeout to 25 hours|The current documentation|
|-|-|
|<img width="507" alt="image" src="https://user-images.githubusercontent.com/5528307/215404867-12b1c824-d132-4862-ba09-ea689f68a246.png">|<img width="886" alt="image" src="https://user-images.githubusercontent.com/5528307/215404794-568decdb-0bf9-4d54-860d-c14d42ba5f02.png">|

**Comment by atduarte** [comment]
Just want to add that the total time of a workspace session (i.e. instance) currently is defined at 24 hours. Meaning that if the workspace ran for 2 hours, a 24h timeout should not be possible.

**Comment by Siddhant-K-code** [comment]
quick-go: We could add the limit b/w 5m _(current: 1m)_ & 1440m (24 hours). Else, it would return an error. 

Future: We could decouple the server limit & adding support to this (https://github.com/gitpod-io/gitpod/issues/9038#issuecomment-1399320435) & allow users to set to >1440m

**Comment by loujaybee** [comment]
@atduarte is there anyway for a user to know how long is remaining? Or, when the workspace was created to get an understanding for how long is remaining on the timeout? I would like to update [this documentation PR](https://github.com/gitpod-io/website/pull/3326/files).

**Comment by Siddhant-K-code** [comment]
> quick-go (before this month's changelog release): We could add the limit b/w 5m (current: 1m) & 1440m (24 hours). Else, it would return an error.

@loujaybee @atduarte Should I send out a small PR to limit this from Gitpod CLI side? to avoid misuse _(before changelog release)_

**Comment by loujaybee** [comment]
> Should I send out a small PR to limit this from Gitpod CLI side? 

Yes, please. We are adding this constraint to the other clients, also: 

- VS Code: https://github.com/gitpod-io/gitpod/pull/16220
- JetBrains: https://github.com/gitpod-io/gitpod/pull/16267

**Comment by filiptronicek** [comment]
@loujaybee cc @Siddhant-K-code the JetBrains PR, https://github.com/gitpod-io/gitpod/pull/16267, should fix these issues and add the 24 hour hard limit:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/29888641/217803143-27796472-ab51-431c-9f25-5cc003d7882b.png">

**Comment by Siddhant-K-code** [comment]
**Suggestion** With an Invalid message, can we specify the next action item to the user? 

```sh
Invalid timeout value: 0m. Timeout limit should be between 5m to 24h
```

**Comment by filiptronicek** [comment]
> Invalid timeout value: 0m. Timeout limit should be between 5m to 24h

Looks good, I think that can be helpful.

Do we have ideas for a sensible minimum workspace timeout? Currently, it's 1 minute. Maybe no need to change that, although extremely low.

**Comment by Siddhant-K-code** [comment]
> Do we have ideas for a sensible minimum workspace timeout

@loujaybee or @atduarte might have some thoughts as they are also involved with this similar PR for docs (https://github.com/gitpod-io/website/pull/3341#discussion_r1101312402) 

<img width="888" alt="image" src="https://user-images.githubusercontent.com/55068936/217813890-9764a5b4-d3bc-4d23-9be3-fed39a131397.png">

**Comment by loujaybee** [comment]
Will close this issue as it's now partially completed. The command no longer allows more than 24hour timeouts, however the error output exposes unneeded implementation details around grpc: 

```
gitpod /workspace/empty (main) $ gp timeout set 25h
jsonrpc2: code 650 message: Invalid duration : Workspace inactivity timeout cannot exceed 24h
```
