### ISSUE TITLE
Move the "close timeout" (IDE + editor timeout) to a user preference.

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16089]
Currently, when an editor disconnects from Gitpod, the workspace timeout is then "reset" to 5 minutes. This means that when a user uses the newly implemented `gp timeout set` command that closing the editor will still close the workspace after 5 minutes. The user should be able to control this editor timeout value, and when extending the workspace timeout should be able to ensure that the workspace will not close, despite the editor closing. 

See [related comment](https://github.com/gitpod-io/gitpod/issues/9038)

> Hello and thank you for releasing the timeout extension command and for allowing us to have timeouts of up to 1-2 days (possibly more). However, it looks like the <5 minute timeout when closing the browser window still applies, so the utility of timeout extensions is pretty limited at the moment (at least in our case). Is there a way for us to have the timeout honored even when all browser tabs are closed?

See [internal conversation](https://gitpod.slack.com/archives/C01KGM9DVRC/p1675274111048109?thread_ts=1675165857.524489&cid=C01KGM9DVRC). 

**Related to:** 
- https://github.com/gitpod-io/gitpod/issues/10373
- https://github.com/gitpod-io/gitpod/issues/9038

**Comment by henit-chobisa** [comment]
Hey, @loujaybee I am interested to work on this issue. 🐳

**Comment by laushinka** [comment]
We will revisit on 20 Feb 2023.

**Comment by loujaybee** [comment]
This is marked complete, but the UI is not yet implemented, re-opening.

**Comment by loujaybee** [comment]
@gtsiolis ah, there might be some confusion. 

This issue is related to the [editor timeout](https://www.gitpod.io/docs/configure/workspaces/workspace-lifecycle#editor-disconnect), not the inactivity timeout (https://github.com/gitpod-io/gitpod/issues/9038). Updates to editor timeouts were descoped from the other PR to get the change merged, and follow up with additional changes for the editor timeout.
