### ISSUE TITLE
Remove workspace components from application cluster

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#16095]
Context:
 - Epic: https://github.com/gitpod-io/gitpod/issues/7845
 - Concrete issue: https://github.com/gitpod-io/ops/issues/6700

Team Workspace is running image-builder in workspace clusters now, so we (WebApp) can remove all workspace artifacts from application clusters for now.

### Steps
- [x] Check potential dependencies
   - [x] image-builder: no longer referenced
   - [x] ws-proxy:
     - [x] https://github.com/gitpod-io/gitpod/pull/16104 still referenced by proxy, required for single-cluster deployment :warning: 
     - [x] https://github.com/gitpod-io/gitpod/pull/16147
- [x] Validate the diff of objects between a `Full` and `Meta`
   - render both, and check the diff: make sure we don't delete sth we still require to be running in app clusters
   - ~store that list for later for deletion of those objects :point_down:~
- [x] Do a temporary scale-down
- [x] Rollout `Meta` only
  - [x] https://github.com/gitpod-io/ops/pull/8118
  - [x] https://github.com/gitpod-io/ops/pull/8120
~- [ ] Remove all workspace k8s objects~ Not necessary, as we use argo-cd with `--prune` :heavy_check_mark: 
- [x] Remove the node-pool: https://github.com/gitpod-io/ops/pull/8123

**Comment by geropl** [comment]
Regarding `ws-proxy`:
 - we only hit this in external-workspace scenarios, when:
   -  a former workspace cluster got shut down, and thus it's DNS entry, e.g. `ws-eu02.gitpod.io`
   - all old browser tabs then send their traffic to the base domain, e.g. `gitpod.io`, where it gets handled by the app cluster
 - currently, we respond in two ways:
   - [workspace route](https://github.com/gitpod-io/gitpod/blob/959e584b55a836e3e5a4dcc387dc82d40b4e40d2/components/ws-proxy/pkg/proxy/routes.go#L640): redirect to `htts://gitpod.io/start/?not_found=true#workspaceID`
   - [port route](https://github.com/gitpod-io/gitpod/blob/478a75e744a642d9b764de37cfae655bc8b29dd5/components/ws-proxy/pkg/proxy/auth.go#L44): respond with 404

We could easily mirror that behavior. :+1:

**Comment by geropl** [comment]
Done :heavy_check_mark:

**Comment by kylos101** [comment]
@geropl :clinking_glasses:
