### ISSUE TITLE
Epic: Admin control over workspace timeouts

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16090]
With the introduction of UBP, and the ability for users themselves to update the timeouts of workspaces, this feature request would then allow an admin to control the timeout policies for users within a Gitpod organisation, mainly for cost management purposes: https://github.com/gitpod-io/gitpod/issues/9038

**Comment by davidwindell** [comment]
A vote for this from a long-term paid organisation. Our users are already starting to set higher timeouts and increasing our costs on the new plan without us having any control over this. Please implement ASAP!

**Comment by lalitindoria** [comment]
Very much needed to control the cost.

**Comment by davidwindell** [comment]
Also the ability to restrict the workspace type at the same time. We only want our users to use the standard class to avoid racking up unnecessary costs.

**Comment by davidwindell** [comment]
@loujaybee I don't have time for a chat, but what I have outlined above is super critical for cost control. We need to be able to limit the class of machine and timeout duration for our users. Those two things are all we need.

**Comment by davidwindell** [comment]
This needs to stay open.
