### ISSUE TITLE
Python debugger

### ISSUE THREAD

**Issue by yozlet** [gitpod-io/gitpod#161]
Given that you have a Django app as one of the demos, it'd be amazing to be able to debug it.

Some extra info, in case this is useful for thinking ahead:

I tried adding the standard launch config from `vscode-python` to `launch.json`, and (correctly) got a warning that `python` isn't a supported `type` because there's no debugger extension for it, but it also complained about `console: none` and, obviously, the `django` key:
```json
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/manage.py",
            "console": "none",
            "args": [
                "runserver",
                "--noreload",
                "--nothreading"
            ],
            "django": true
        }
```

**Comment by svenefftinge** [comment]
Yes, the available properties are provided by the debug adapter. So once we hook up the python debug adapter the other warnings will go away, as well.

**Comment by AlexTugarev** [comment]
Debugging python code will work with `"console": "internalConsole"`

**Comment by JesterOrNot** [comment]
Please see https://www.gitpod.io/docs/python-in-gitpod/

**Comment by jankeromnes** [comment]
See also https://community.gitpod.io/t/django-debugging/381/6

**Comment by yozlet** [comment]
Works great, thanks @jankeromnes & @JesterOrNot!
