### ISSUE TITLE
Reimplement gitpod-desktop ssh connection to use the native ssh client

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#16108]
# Description

Right now we use a node ssh library to test the ssh connection but this only support basic features and we need to implement them manually again.

# Solution

Reimplement gitpod-desktop ssh connection to use the native ssh client, this is the same approach MS remote ssh extension does

**Comment by loujaybee** [comment]
> we use a node ssh library to test the ssh connectio

This issue only concerns the testing of the SSH connection, not the SSH connection itself, correct @jeanp413 ? 

Trying to figure out if this issue is related to: 

- https://github.com/gitpod-io/gitpod/issues/16440

**Comment by jeanp413** [comment]
> Is this issue only concerning the testing of the connection? Not the actual SSH connection itself @jeanp413 ?

yes, remote-ssh extention already uses native ssh client
