### ISSUE TITLE
My-first-repo

### ISSUE THREAD

**Issue by cynthiapinedoh79** [gitpod-io/gitpod#1611]

**Comment by Kreyren** [comment]
@cynthiapinedoh79 i assume that @jankeromnes is assuming this being invalid.

Since this is your first repo? let us know if you need help with something ^-^ New users and developers are among the most important people in Free and Open-Source world :p

**Comment by Kreyren** [comment]
Also note that this https://github.com/gitpod-io/gitpod/issues/1611 is not a repository, these are used as issues used to track various bugs and problems in the source code.

For new repository you may want to use https://github.com/new ^-^
