### ISSUE TITLE
Typing expeirence wrong on 16:10 screens

### ISSUE THREAD

**Issue by Mintactus** [gitpod-io/gitpod#16116]
### Bug description

I
I have a chromebook acer CP714-1WN-560E
I'm using chrome 107.0.5304.110 (Official Build) (64-bit)

On this chromebook, the screen is ratio is 16:10.

The cursor is simply not at the right place at all when I'm writing.

### Steps to reproduce

Try typing with a 16:10 maybe

**Comment by axonasif** [comment]
Hi @Mintactus, https://github.com/microsoft/vscode/issues/160702 might be related and [this workaround](https://github.com/microsoft/vscode/issues/160702#issuecomment-1262870646).
