### ISSUE TITLE
[GCP] Configure caching for static assets of the app (gitpod.io) 

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#16125]
So far we only target local browser caches by setting [proper cache headers](https://github.com/gitpod-io/gitpod/blob/975e54d0b60b63a9ff69ae452b60de5e355505de/components/dashboard/conf/Caddyfile#L53-L59) and [generating content-dependent asset names](https://github.com/gitpod-io/gitpod/blob/478a75e744a642d9b764de37cfae655bc8b29dd5/components/dashboard/leeway.Dockerfile#L13-L17).

We should add simple CDN caching for static assets in GCP based on the generated headers/names.

**Comment by csweichel** [comment]
Using a CDN makes a lot of sense.

We must retain the quality of Gitpod being a contained deployment. I.e. it's containers that get run somewhere, and don't have an infrastructure dependency at build time.

Especially when thinking about Dedicated this really matters.
