### ISSUE TITLE
Add workspace session time to `gp info`

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16146]
Currently a workspace cannot run for more than 36 hours continuously. However, there is no way for a user to know officially how long the workspace has been running, and to gauge how much uptime they have left on the running workspace. You can use the `uptime` command to show the session time, however I'm not sure how accurate this is. It would be good to add both: 

- Current uptime
- Remaining uptime (36 hours - current uptime)

Into the `gp info` command, so that users are at least aware of, and can track this limitation. 

See related documentation: 
- https://github.com/gitpod-io/website/pull/3341/files

And issue: 
- https://github.com/gitpod-io/gitpod/issues/16085

**Comment by akosyakov** [comment]
I'm not sure `info` is a good place. It is rather static info. Maybe `top` is better? It reflects dynamic characteristics.
