### ISSUE TITLE
[content-service] backup upload sometimes fails causing data loss

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#16165]
### Bug description

Sometimes gsutil can fail to upload a backup. [Logs](https://cloudlogging.app.goo.gl/Rj999ju6tkPTcSpD8), the actual [error](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-01-31T21:48:18.495648206Z;query=jsonPayload.serviceContext.service%3D%2528%22ws-daemon%22%2529%0Aresource.labels.cluster_name%20:%20%2528%22eu84%22%2529%0Alabels.%22compute.googleapis.com%2Fresource_name%22%3D%22workspace-ws-eu84-internal-xl-pool-95sd%22%0Atimestamp%3D%222023-01-31T12:38:45.181850777Z%22%0AinsertId%3D%2211od0xfc3h1r3b3b%22;summaryFields=:false:32:beginning;timeRange=2023-01-30T21:31:47.051Z%2F2023-02-01T21:31:47.051Z?project=workspace-clusters) on upload.

For example, we recently found a failure mode where an upload failure:
1. doesn't result in a retry
2. doesn't show a trace with an error

The error is:
```
ResumableUploadException: 503 Server Error
CommandException: Some temporary components were not uploaded successfully. Please retry this upload.
CommandException: 2 files/objects could not be transferred.
```

And was captured with [this log statement](https://github.com/gitpod-io/gitpod/blob/3e23290d6d8fb7be182c05c2f41b272b4b5897a8/components/content-service/pkg/storage/gcloud.go#L418).

Here is the trace for the original backup and [STOPPING](https://jaeger-eu-prod.workspace-preview.gitpod-io-dev.com/trace/7da93954c1f0ca90). Here is the [trace](https://jaeger-eu-prod.workspace-preview.gitpod-io-dev.com/trace/13b19deac7a9b5a6) for the follow-on workspace start (as you can see, no backup was found, so start failed).

Hints:
[Retry logic](https://github.com/gitpod-io/gitpod/blob/3e23290d6d8fb7be182c05c2f41b272b4b5897a8/components/ws-daemon/pkg/content/service.go#L730)
The [interface containing upload](https://github.com/gitpod-io/gitpod/blob/3e23290d6d8fb7be182c05c2f41b272b4b5897a8/components/content-service/pkg/storage/storage.go#L163)
Upload calls [[1](https://github.com/gitpod-io/gitpod/blob/3e23290d6d8fb7be182c05c2f41b272b4b5897a8/components/ws-daemon/pkg/content/service.go#L627)][[2](https://github.com/gitpod-io/gitpod/blob/3e23290d6d8fb7be182c05c2f41b272b4b5897a8/components/ws-daemon/pkg/content/service.go#L680)]

### Steps to reproduce

Not sure.

Potentially related to https://github.com/gitpod-io/gitpod/issues/13496

### Workspace affected

Refer to logs

### Expected behavior

Upload failures retry & if there is an upload failure, the trace includes an error & the upload failure is propagated and not eaten

### Anything else?

Related internal conversations in chronological order:
customer: https://gitpod.slack.com/archives/C02SF4A050W/p1675177840083469
on-call: https://gitpod.slack.com/archives/C0201TXMV54/p1675236509082179
ide team: https://gitpod.slack.com/archives/C01KGM9BH54/p1675153158288099
workspace team: https://gitpod.slack.com/archives/C02F19UUW6S/p1675247778299819

**Comment by kylos101** [comment]
What did the node resources look like at the time of this issue? Pretty much what you'd expect (high CPU and disk I/O).

![image](https://user-images.githubusercontent.com/1272076/216170111-4ddf0393-854b-481f-b2fe-208b7f49d6c7.png)

![image](https://user-images.githubusercontent.com/1272076/216170273-d2b0acd3-9abb-4f96-9bba-bf8f934f8a9b.png)

**Comment by Furisto** [comment]
We checked the logs for errors regarding the retry of the backup and found 2 instances where this problem happened over the last 30 days. Each time it was a different cause. Once was a timeout fetching the token and another one the auth credentials were not accepted. @kylos101 How would you rank the priority of this issue based on this information?
