### ISSUE TITLE
Faster way to run CMD+C and `gp rebuild` again. 

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16178]
When running `gp rebuild` I'm often doing iterations on my configuration. Having to CMD + C to close the terminal, then press up on my terminal, then having to run `gp rebuild` feels like friction that could be avoided by having the terminal output pause waiting for input, e.g. if the user hits "enter" the `gp rebuild` command will automatically stop and start. Alternatively, this could be a "y/n" type of input, where the question is "did your configuration complete successfully? y - exit, n - restart". This would be similar ergonomics to the jest testing library, e.g.

``` › Press Enter to trigger a test run.```

<img width="457" alt="image" src="https://user-images.githubusercontent.com/5528307/216338619-0379d39f-0de3-4ea5-8d7d-9be5da4514cc.png">

**Comment by akosyakov** [comment]
Interesting idea!

We had bad experience while trying `run gp` that creates an overlay effect but then it makes links unclickable in VS Code. But maybe it is just an implementation issue.
