### ISSUE TITLE
[dashboard] cannot add new project to organizations

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#16189]
### Bug description

I cannot add new projects to any organizations, I get a spinner like so when trying to fetch repositories (attached below). Also, in the dev tools, I have this error, but no signal in the UI that the API call failed.

```
Error: Request getProviderRepositoriesForUser failed unexpectedly without providing any details.
    at main.js:449:48
    at main.js:276:17
    at main.js:260:13
    at setImmediate.js:40:13
    at l (setImmediate.js:69:21)
    at n (setImmediate.js:109:17)
```

![image](https://user-images.githubusercontent.com/1272076/216465950-421aab83-3c40-4cf2-b6eb-44d1a71bab44.png)

### Steps to reproduce

From any organization, click New Project

### Workspace affected

n/a

### Expected behavior

I should see a list of repositories

**Comment by Siddhant-K-code** [comment]
This looks ok now (still slow as it was previously). Are you still facing the same issue?


https://user-images.githubusercontent.com/55068936/216507387-83fe950e-508b-4cbc-9f1f-f2a8bdf0286a.mov
