### ISSUE TITLE
Stream log output of terminals to `gp rebuild`

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16180]
When running `gp rebuild` I found myself not wanting to have to open up the debug workspace every time to see the log output. I found myself wanting to see the logs inline with the main `gp rebuild` logs, e.g. with some command like: `gp rebuild --logs` that would stream them to the main workspace rather than having to open the debug workspace each time.

**Comment by akosyakov** [comment]
It maybe good to do it by default. My only worry will be that prompt with how to open in another window would be logs.
About `--logs` not sure, since we have `--log=info` already. Wonder what could be an alternative option name that it is more specific about tasks?
