### ISSUE TITLE
Can't push to branch

### ISSUE THREAD

**Issue by itsmekaren** [gitpod-io/gitpod#1618]
I can pull from a branch but I can't push

ERROR: Permission to itsmekaren/demo.git denied to kcardoz19.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Kreyren** [comment]
@itsmekaren Seems that gitod doesn't have the required permission, check https://gitpod.io/access-control

Also gitpod should output a helpful message with prompt to the mensioned url, let me know if it did that if not it's bug and steps to reproduce would make it actionable ^-^
