### ISSUE TITLE
run a single happy path workspace start smoke test on each main build

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#16196]
## Is your feature request related to a problem? Please describe

This test should be lightweight and headless, but test a workspace start which as close as possible how user will start it. It should cover:
- image build
- prebuild
- supervisor and IDE startup (regular workspace start does not fail)
- regular workspace stop

**Comment by akosyakov** [comment]
@iQQBot @laushinka should we move it to done?

For me the acceptance criteria will be:
- running as a part of a usual build always, not a separate job - but as I understand it is not reachable right now, because preview envs are not stable enough? cc @mads-hartmann 
- run prebuild test as well, since last incident was about them

**Comment by mads-hartmann** [comment]
> but as I understand it is not reachable right now, because preview envs are not stable enough?

Let's get some experience running it after each merge on main as it is implemented now. Then we can start a conversation later about running it on every PR prior to merge at a later point ☺️ It would indeed require a bit of changes/capacity planning for preview envs if we wanted to run it on every PR.

**Comment by akosyakov** [comment]
@mads-hartmann just to be the on the same page I think it should be run on main to guarantee that this version of main is good, running on PR does not ensure it

@geropl We are wondering how we can test prebuilds, since it was triggered by last incident breaking prebuidls exactly. @iQQBot says it is very complicated now because project is needed

**Comment by laushinka** [comment]
@iQQBot @mads-hartmann Do we have an update on this issue? 🙏🏽
