### ISSUE TITLE
What to do with `core.gitpod-node` file, added to new Bitbucket workspace?

### ISSUE THREAD

**Issue by AniX** [gitpod-io/gitpod#1620]
A few days ago I've created a new workspace to test this awesome new feature https://github.com/gitpod-io/gitpod/issues/626

Today I've noticed that a file has been added without my doing: `core.gitpod-node.7580.1592696891`

I haven't noticed this behavior with the gitlab based workspaces before. I wonder if I'm supposed to do something with this file, or if I can safely remove it, or if it is a bug that you may want to address.

Workspace ID: `cb9800e5-****-****-****-4037395151c6`

```
gitpod /workspace/val-srv $ git status
On branch issue/MG2-58
Your branch is up to date with 'origin/issue/MG2-58'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        core.gitpod-node.7580.1592696891

nothing added to commit but untracked files present (use "git add" to track)
gitpod /workspace/val-srv $ ls -la core.gitpod-node.7580.1592696891
-rw------- 1 gitpod gitpod 113197056 Jun 20 23:48 core.gitpod-node.7580.1592696891
```

**Comment by Kreyren** [comment]
> Workspace ID: cb9800e5-****-****-****-4037395151c6

Afaik and FWIW the workspace ID can't be abused by anyone, but it can be used by GitPod Staff to identify the workspace :p 

What's inside that `core.gitpod-node.7580.1592696891` (assuming that it's not something confidential) ?

**Comment by svenefftinge** [comment]
This seems to be a core dump of the IDE process that has died. You can safely remove it, but please let us know if you see it regularly.
