### ISSUE TITLE
How to pass an array as an argument?

### ISSUE THREAD

**Issue by DaniilNapuda** [gitpod-io/gitpod#1621]
I need to pass a two-dimensional array of objects to a method.
How to fix this?

**Code(Example):**
```
using System;

class Program
{
	static void Main()
	{
		Obj [,] Arr = new Obj[5, 5];
		Input(Arr);
	}

	static void Input(Obj [,] Arr)
	{
		// Iterating over and outputting an array
	}
}
class Obj{}
```
**Bug(Part of the error removed):**
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object

**Comment by corneliusludmann** [comment]
Hello and welcome to Gitpod!

It seems that your issue is not Gitpod related at all. I don't even know in which language you are programming. Probably you should ask your question at [StackOverflow](https://stackoverflow.com/) or similar.
