### ISSUE TITLE
Glitched Terminal Text (Tor Browser)

### ISSUE THREAD

**Issue by intfract** [gitpod-io/gitpod#16215]
### Bug description

Everything inside the terminal has glitched text. None of the characters are readable. Everything is a blur of colours. The problem persists despite reloading many times. 

### Steps to reproduce

1. Download [Tor](https://torproject.org/)
2. Open a Gitpod workspace
3. Open a new terminal

### Expected behavior

I should see normal text instead of random colours. 

### Anything else?

![image](https://user-images.githubusercontent.com/110207136/216813620-d3e5dbef-a37f-4099-b241-41b35f6ebbd3.png)

**Comment by axonasif** [comment]
Hi @intfract, thank you for rising this.
May I ask, why would you need to access Gitpod through tor?

It is pretty uncommon and I probably don't see this getting prioritized anytime soon, so I'll close this if that's OK. If you mind, feel free to reopen 👋

**Comment by intfract** [comment]
Well, I use tor for privacy reasons. I don't want people on my network to know that I'm coding or using Gitpod. 

I found something unusual in the error logs. Looks like Gitpod uses WebGL. `ERR this._glyphRenderer is undefined:`

**Comment by axonasif** [comment]
Since you're using VSCode (browser/web version) through Gitpod. I could suggest to raise this issue on:
- https://github.com/microsoft/vscode/issues/
