### ISSUE TITLE
bitbucket: Gitpod asks for too much permission

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1623]
![image](https://user-images.githubusercontent.com/11302521/85454465-42986d00-b59d-11ea-9952-b690e8a028e2.png)

I don't see a reason for gitpod to have access to issues and webhooks?

Also the account informations that it's requesting should be cherrypicked, i.e it should only need name and email in my opinion :thinking:

**Comment by svenefftinge** [comment]
Webhooks are need to install prebuilds and we are asking everything upfront because Bitbucket doesn't allow to gradually add scopes.

**Comment by sr229** [comment]
We do need issues access IIRC so Gitpod may have some sort of context-based changes based on one issue (which we had in place for GitHub).

**Comment by corneliusludmann** [comment]
Unfortunately, the `issue` scope comes with the `repository` scope. There is nothing we can do to prevent it. If you request the `repository` scope you get:

> - the ability to view and use the issue tracker on any repository (created issues, comment, vote, etc)

See: https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/
