### ISSUE TITLE
Please support private Docker registries with a non-default port

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#16237]
### Bug description

Today in Gitpod, you can use private Docker images by specifying a `GITPOD_IMAGE_AUTH` Project-level variable as described in:

https://www.gitpod.io/docs/configure/workspaces/workspace-image#use-a-private-docker-image

Unfortunately, since `:` was used as a separator, you cannot specify Docker registries with non-default ports, i.e.:

- Specifying `registry.example.com` works ✅
  - (`GITPOD_IMAGE_AUTH="registry.example.com:Zm9vOmJhcg=="` is properly recognized 👍)

- Specifying `registry.example.com:1337` doesn't work ❌
  - (`GITPOD_IMAGE_AUTH="registry.example.com:1337:Zm9vOmJhcg=="` is ignored due to the double `:` 😖)

### Steps to reproduce

1. Try to specify a private Docker registry using a non-default port (like `registry.example.com:1337`)

### Anything else?

The following code ignores any value of `GITPOD_IMAGE_AUTH` that doesn't have exactly one `:` character:

https://github.com/gitpod-io/gitpod/blob/508148b8366804d0bb0a43316b44df7b83abc72a/components/server/src/workspace/workspace-starter.ts#L695-L699

**Suggestion**: Maybe, it could instead split on the _last_ occurrence of a `:`, and allow 0 or 1 `:` to be present in the Docker registry hostname ? (Or, maybe it could allow a base64-encoded Docker registry hostname?)

**Comment by kylos101** [comment]
Hi @jankeromnes , this is all set - better late than never! ❤

**Comment by jankeromnes** [comment]
Nice, thank you Gitpod team! 🎉 I forgot which customers needed this, but I assume you're able to figure this out internally to let them know the good news. 😁

Also I hope everyone is well! Please share that I said hi 🙏
