### ISSUE TITLE
Port not found - @web/dev-server

### ISSUE THREAD

**Issue by bangank36** [gitpod-io/gitpod#16246]
### Bug description

I created new workspace with Adobe Spectrum Web Component repo https://github.com/adobe/spectrum-web-components.
When run the project using `yarn start`, it produced a `Port not found` error on Preview ( not matter the port )
Attached is the gitpod URL in case it helps
https://gitpod.io/start/#adobe-spectrumwebcompo-iqm3f1c3uc6

I think it has something relate to this file [dev-server-config](https://github.com/adobe/spectrum-web-components/blob/main/wds-storybook.config.js), I tried to update the port prop to other value, but it still shouted the same issue 

### Steps to reproduce

- Create gitpod instance on https://github.com/adobe/spectrum-web-components
- Install depencies and start the demo by `yarn & yarn start` ( this is running automatically when gitpod starts )
- Open the preview and see the Port not found issue

**Comment by axonasif** [comment]
Hi @bangank36, could you please try to open the workspace in [desktop vscode client](https://www.gitpod.io/docs/references/ides-and-editors/vscode) for [localhost port forwarding](https://www.gitpod.io/docs/configure/workspaces/ports#port-forwarding)?
