### ISSUE TITLE
notifications page infinite loop

### ISSUE THREAD

**Issue by dengBox** [gitpod-io/gitpod#16257]
### Bug description

When I enter the `notifications` page in an email, the page keeps refreshing and never stops

### Steps to reproduce

1.  I subscribed to your mailbox before
2. I enter[ this page](https://www.gitpod.io/unsubscribe) to unsubscribe 
3.  Jump to this page on this page.

![WX20230207-101711@2x](https://user-images.githubusercontent.com/29906246/217130927-3fabc08a-57c2-4030-806f-3942edc79a42.png)

### Workspace affected

n

**Comment by axonasif** [comment]
Hi @dengBox, thanks for reporting!
We'll probably need to have some redirects setup for the old paths and update the links in source code.

**Comment by geropl** [comment]
Thanks for reporting! This got fixed with https://github.com/gitpod-io/gitpod/pull/16259, but we had to wait for https://github.com/gitpod-io/gitpod/pull/16275 to be able to roll it out. Thansk @svenefftinge ! :pray:
