### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by ayotundeakinsola** [gitpod-io/gitpod#1626]
![error](https://user-images.githubusercontent.com/49040268/85724017-17746180-b6f4-11ea-8675-778e67299178.png)

Hi, I keep getting this error when I try to run my python script: "OSError: [Errno 101] Network is unreachable"

Please can you help out?

**Comment by svenefftinge** [comment]
Can you provide a reproducible (repo or snapshot)?

**Comment by ayotundeakinsola** [comment]
> Can you provide a reproducible (repo or snapshot)?

do you mean I should post my code?

**Comment by corneliusludmann** [comment]
If your GitHub repository is publicly available, please post the link to the repo. Otherwise, you could create a snapshot of your workspace in the menu `Workspace` → `Share Workspace Snapshot`.
