### ISSUE TITLE
Use location header from load balancer to select region

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#16271]

**Comment by aledbf** [comment]
@easyCZ is this feature optional? do we need to support this feature in dedicated?
(we use NLBs, where is not possible to add headers)

**Comment by easyCZ** [comment]
So the header would only be used initially to specify a default, if nothing is set. We do want to provide the ability to ping WS clusters and be able to choose the appropriate one, or for the user to be able to explicitly set a preference.

In the case of Dedicated, I expect that there would only be a WS cluster(s) in the same region initially, and as such the lack of a region preference from the user wouldn't actually result in scheduling in the wrong region.

But I do share your concerns. The header usage is stop-gap to allow SaaS to remove the second application cluster, but we'll need to generalize that immediately after.
