### ISSUE TITLE
"No such image" error when trying to build from Github repo

### ISSUE THREAD

**Issue by rokopt** [gitpod-io/gitpod#1627]
### Describe the bug
When trying to build a new Gitpod image from [one of my repos](https://github.com/rokopt/geb-lang) by clicking the "Gitpod" button provided by the app, I have today started consistently receiving the following error:

```
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: Error response from daemon: No such image: gitpod.io/image-builder/selfbuild:be4a5a83176295d4d4ab67e8772a73c3f5db59fcaea403390ac2e3fef9a80120
Please file an issue if you think this is a bug.
```
### Steps to reproduce
Navigate to [this Gitpod link](https://gitpod.io/#https://github.com/rokopt/geb-lang)

### Expected behavior
A new build should occur and I should eventually end up in a workspace built from that repo.  It has been working for several days now, and the other repo that I've been working on ([this one](https://gitpod.io/#https://github.com/rokopt/stellar-core/tree/stellar-core-gitpod)) still works.

I have done quite a bit of creating and deleting of workspaces from both of those repos over the past week.

### Additional information
I'm guessing that that ```be4a5a83176295d4d4ab67e8772a73c3f5db59fcaea403390ac2e3fef9a80120``` from the error log is a workspace ID?

### Example repository
https://github.com/rokopt/geb-lang

**Comment by rokopt** [comment]
Update:  I was wrong that the other repo that I've been working on still works; I'm now getting the same error from, for example, here:

https://gitpod.io/#https://github.com/rokopt/stellar-core/tree/stellar-core-gitpod-pr-1

So it's something common to my account, seemingly, not to any one particular repo or workspace.  It looks like the ```be4a5a83176295d4d4ab67e8772a73c3f5db59fcaea403390ac2e3fef9a80120 ``` hash (?) is the same regardless of which repo/branch I try to build a workspace from.

**Comment by rokopt** [comment]
Another update:  a colleague did me a favor and tried the https://gitpod.io/#https://github.com/rokopt/stellar-core/tree/stellar-core-gitpod-pr-1 link, and got the same error that I'm getting (including the same hash).  So it's _not_ just my account.  I'm not sure what the common factor is now.

**Comment by rholland** [comment]
same problem

**Comment by rholland** [comment]
Problem still there. Any updates on when it will be resolved?
Thanks.

**Comment by svenefftinge** [comment]
Sorry for the delay, we are looking into it now.

**Comment by svenefftinge** [comment]
It is fixed now.

**Comment by rokopt** [comment]
Confirmed -- fix works for me too.  Thanks!
