### ISSUE TITLE
Unable to Signup or Login to gitpod.io via github account

### ISSUE THREAD

**Issue by evilantnie** [gitpod-io/gitpod#1628]
### Describe the bug
I'm receiving an error when I attempt to authenticate via github, I am successfully logged into github, but gitpod gives me an error page. In the dev console I see a login error saying i'm not logged in.

### Steps to reproduce
Clicked the "Let's Try It!" button on the homepage, authenticated with github when prompted, and then after a 4-5s wait (maybe a timeout?) I get the "Sorry, something went wrong 😓 Authorization failed. Please try again." error.

If I try again by going to the login->github.com option, it fails in the same way.

### Expected behavior
I should not get an error page when attempting to login to gitpod.io via github OAuth.

### Additional information
`Error: User is not authenticated. Please login.
    at main.js:449
    at main.js:276
    at main.js:260
    at setImmediate.js:40
    at h (setImmediate.js:69)
    at s (setImmediate.js:109)`

### Example repository
No repository, I was just clicking the "Let's Try It!" button on the homepage, authenticated with github when prompted, and then got the error page.

**Comment by Kreyren** [comment]
What's gitprime and how is it relevant to gitpod? :thinking:

**Comment by evilantnie** [comment]
That is a typo, I meant gitpod

**Comment by Kreyren** [comment]
@evilantnie In which case please verify that you are not blocking cookies from `https://gitpod.io` and that you have granted gitpod permission in https://gitpod.io/access-panel

**Comment by evilantnie** [comment]
Odd, when I visited the access-panel url above just now, I was successfully redirected to an account creation page and am now able to get in.
