### ISSUE TITLE
service reliability question

### ISSUE THREAD

**Issue by rholland** [gitpod-io/gitpod#1629]
Hi,

I really like gp and want to use it as a primary part of my and other's workflow. You guys have done a great job and are responsive.  But I am now trying to understand the reliability of the service.  

I first tried gp over the course of a day a few weeks ago. Today I came back to the project.  Both times there were server problems with loading workspaces from github.

Are there tables or web pages that give uptime or reliability data for your service?  Is it something you can comment on qualitatively at this point and what your expectations are?   Are some paid plans more reliable than others?

I am in San Francisco.

Thanks,
Rod Holland

**Comment by svenefftinge** [comment]
Hi Rod,

Thanks for the kind words. We maintain https://status.gitpod.io/.  I don't know what went wrong the first time you experienced issues. 
Generally we are fully committed to be responsive and keep everything operational 24/7. That said, our team is still relatively small and entirely based in Europe. Also we run multiple clusters, not only to make sure your workspace is close, but also to quickly move all traffic to working clusters in case we have incidents. Furthermore we have many automated monitoring triggers and keep adding new ones that notify us immediately about certain issues. We don't yet have one for yesterday's problem, though.

hth,
Sven
