### ISSUE TITLE
Language Support for XML

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#163]
So far we only have syntax coloring.
We should look into using https://github.com/angelozerr/lsp4xml.

**Comment by dhuebner** [comment]
See https://github.com/theia-ide/theia-xml-extension

**Comment by dhuebner** [comment]
@svenefftinge Published the extension https://www.npmjs.com/package/@theia/xml 

Could someone add it to gitpod?
... and close the issue
