### ISSUE TITLE
Gitpod button is too small compared to new GitHub UI

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1630]
![image](https://user-images.githubusercontent.com/11302521/85797193-714c4a00-b73b-11ea-97f6-65fc7785dd90.png)

**Comment by svenefftinge** [comment]
Fixed and published for Firefox but the chrome extension is pending in review for two days now.

**Comment by corneliusludmann** [comment]
Is fixed with browser extension version >= 1.5 (currently in Chrome store).
