### ISSUE TITLE
Cannot run jetbrains IDE on `gitpod/workspace-postgres` base image

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#16302]
### Bug description

It happen in integration test, and production, every repo if using `gitpod/workspace-postgres` as base image and using any Jetbrains IDE it will stuck in connecting

The process tree shows `/bin/bash -ilc /ide-desktop/jb-launcher env 3c82672c-77a8-4796-9be7-16b17443bfa9` hang on

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/20944364/217559463-d4716780-5f42-4a27-b7ac-09362bd5d6f7.png">

try kill and it will work.

### Steps to reproduce

Start a workspace with `gitpod/workspace-postgres` base image

### Workspace affected

mustardmh-test-rpnlit9quax

### Expected behavior

Can connect with Jetbrains gateway

### Example repository

https://github.com/mustard-mh/test/tree/mh/pg

**Comment by mustard-mh** [comment]
This's because [postgres workspace image](https://github.com/gitpod-io/workspace-images/blob/5d1e7aa2d8b77048f5ee3f2d4128ec23fa93512c/chunks/tool-postgresql/postgresql-hook.bash#L26) will start pg with this `&` . It's NOT EXIT when [we exec with `bash -ilc`](https://github.com/gitpod-io/gitpod/blob/223640862fa72ee5f203468c4be5b03c073a7b95/components/ide/jetbrains/launcher/main.go#LL484-L497C3). `-l` will load all profiles like the link above and `&` make it never return.

**Comment by mustard-mh** [comment]
To resolve this problem, we can introduce process managers like `pm2`, `systemd` ... https://github.com/gitpod-io/gitpod/issues/16092 . But it requires bunch of changes.

cc @akosyakov since you mentioned `dev container` [internal chat](https://gitpod.slack.com/archives/C01KGM9AW4W/p1676285903351409) can be a solution too.

**Comment by akosyakov** [comment]
@mustard-mh I agree we should address https://github.com/gitpod-io/gitpod/issues/16092 this issue just a follow up

**Comment by mustard-mh** [comment]
Now should we change JetBrains integration test [repo refer](https://github.com/gitpod-io/gitpod/blob/0e792b9963723b77e35feeae96f3960d73ed48ec/test/tests/ide/jetbrains/gateway_test.go#L275) to make it work? @akosyakov

**Comment by akosyakov** [comment]
@mustard-mh sounds good

**Comment by akosyakov** [comment]
@mustard-mh btw VS Code does the same trick, why does it work for VS Code terminals?
