### ISSUE TITLE
Gitpod refuses to build images `FROM: scratch`

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1631]
### Describe the bug

I've made from scratch docker environment for my repository that on gitpod just get replaced with default dockerfile

### Steps to reproduce

1. Open https://gitpod.io/#https://github.com/Kreyren/Zernit/tree/rework

**Comment by sr229** [comment]
What does it look like when built in the console, I'd like to have a reference before I can reproduce.

**Comment by JesterOrNot** [comment]
Hmmm, according to your logs your YAML syntax is wrong. It could be that Gitpod is ignoring your configuration because your syntax is broken.

**Comment by Kreyren** [comment]
> What does it look like when built in the console, I'd like to have a reference before I can reproduce. @sr229

Sorry didn't get a notification about your reply. I currently don't have an environment to test this, but i will test it asap.

> Hmmm, according to your logs your YAML syntax is wrong. It could be that Gitpod is ignoring your configuration because your syntax is broken. @JesterOrNot 

Elaborate on the syntax err? Looks good to me and i ain't getting any logs O.o

**Comment by Kreyren** [comment]
@sr229 Results in:

```console
kreyren@leonid:~/Repositories/gitpod-test-zernit-scratch-devuan$ sudo docker build --file gitpod/dockerimages/devuan/devuan.Dockerfile .
Sending build context to Docker daemon  167.5MB
Step 1/14 : FROM scratch
 ---> 
Step 2/14 : LABEL MAINTAINER="RXT0112 (Zernit)"
 ---> Running in 4cad596fd9ed
Removing intermediate container 4cad596fd9ed
 ---> d6ead92b834e
Step 3/14 : LABEL DESCRIPTION="Designed for zernit development to be used in theia frontend"
 ---> Running in 8da01740cf3b
Removing intermediate container 8da01740cf3b
 ---> e1f53de837cb
Step 4/14 : ADD gitpod/dockerimages/devuan/fsh /
ADD failed: stat /var/lib/docker/tmp/docker-builder625737653/gitpod/dockerimages/devuan/fsh: no such file or directory
```

investigating..

**Comment by sr229** [comment]
Looks like it's trying to call a command as root so it fails but I don't think in any circumstances it should fail like that. Might be  a Kube-specific issue.
