### ISSUE TITLE
I am having issues trying to open a repository from Github. Below is the error message I get. 

### ISSUE THREAD

**Issue by Isaac3060** [gitpod-io/gitpod#1632]
Error: 13 INTERNAL: cannot create build volume: cannot create build volume: Error response from daemon: No such image: gitpod.io/image-builder/selfbuild:be4a5a83176295d4d4ab67e8772a73c3f5db59fcaea403390ac2e3fef9a80120
Please file an issue if you think this is a bug.

**Comment by svenefftinge** [comment]
This is dupe of https://github.com/gitpod-io/gitpod/issues/1627 and has been fixed.
