### ISSUE TITLE
Add VS Code integration for `gp rebuild`

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16326]
When running `gp rebuild` it's easy to lose the debug workspace URL in the log output, or from the single popup from VS Code. This issue is the proposal to add VS Code native actions like command palette to interact with the debug workspace in the case that the user cannot find the URL. We should do this after re-considering the `gp rebuild` naming.

**Comment by akosyakov** [comment]
We open automatically the window now always, still an issue?
