### ISSUE TITLE
`gp init -i` is returning `{}`

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16335]
Currently `gp init -i` commands are outputting empty JSON objects for some reason. 

**Steps to replicate:** 
* Use `gp init -i`

**Expected result**
* A valid `.gitpod.yml` or `Dockerfile` is created.

**Actual result**
* A `.gitpod.yml` is created with `{}` as the response

Relates to `gp rebuild` as `gp init -i` is referenced in the output. 

<img width="358" alt="image" src="https://user-images.githubusercontent.com/5528307/218048779-05ea9e04-fa5c-4de9-99e8-49c70de2cfdc.png">

**Comment by mustard-mh** [comment]
@loujaybee do you remember the detail selected options? 

I tried with `gp init -i` and it paniced. So maybe not the same problem (want to ship/fix it before our DEMO time)

**Comment by akosyakov** [comment]
@mustard-mh is it resolved?

**Comment by mustard-mh** [comment]
> @mustard-mh is it resolved?

We [fixed](https://github.com/gitpod-io/gitpod/pull/16550) `gp init` panic problem, but it seems not the same with this issue

**Comment by Siddhant-K-code** [comment]
It seems to work fine now. We can close this issue, @loujaybee?

https://github.com/gitpod-io/gitpod/assets/55068936/7f937f89-3556-4e3e-be8d-ca0a5ac91bd2

**Comment by mustard-mh** [comment]
Let's close and see if we have further report about it
