### ISSUE TITLE
Dotfiles debugging support for inner loop (`gp rebuild`)

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#16349]
## Is your feature request related to a problem? Please describe

Iterating and debugging dotfiles for Gitpod would be equally useful as with `.gitpod.yml`.

## Describe the behaviour you'd like

:thought_balloon: As an user I imagine it to be:
- If `~/.dotfiles` dir exists on the parent workspace, share a clone of it in the debug workspace.
- If the user opens their dotfiles repo as a workspace, share that as `~/.dotfiles` in the debug workspace instead of sharing from the parent workspace `$HOME/.dotfiles`.
- Have a --dotfiles-dir flag to specify a custom dir of dotfiles. (nice to have)
- From where dotfiles dir is being shared could be informed to the user through terminal logs.
- If the user updates the dotfiles link on https://gitpod.io/preferences, inform and maybe switch to it?

## Additional context

Some more context here 🙏 
- https://gitpod.slack.com/archives/C03NWNHJ163/p1676048235177169?thread_ts=1675954838.949759&cid=C03NWNHJ163

**Comment by axonasif** [comment]
Some recent feedback:
- https://github.com/gitpod-io/gitpod/issues/13004#issuecomment-1354530182

**Comment by akosyakov** [comment]
Debug workspace should share what is actually shared between workplace restarts, ie /workspace. Nothing else should be by design. Instead as any other workpace it should go via initialization of dotifles on start. If it does not happen then it is a bug. Adding —dotfiles option makes check to point to iterate on dotfiles repo itself.

**Comment by axonasif** [comment]
> Debug workspace should share what is actually shared between workplace restarts, ie /workspace.

dotfiles may not be directly saved between restarts but it's applied/installed between restarts and can influence the startup of a workspace. Having the capability to only test dotfiles would be useful too as you mentioned. However, sometimes the `/workspace` repo context is needed for some debugging some specific automation.

**Comment by akosyakov** [comment]
It is the point. It should work as for normal workpace, ie applied/installed each time exactly the same way. Not in any new way.
