### ISSUE TITLE
Support Visual Studio Code Remote - SSH

### ISSUE THREAD

**Issue by samuelcaldas** [gitpod-io/gitpod#1635]
[Visual Studio Code Remote - SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)

**Comment by corneliusludmann** [comment]
Have you tried to install this extension? If yes, what works, what not? Please provide more information on this issue.

**Comment by bobfang1992** [comment]
I dont think this is possible as that extension is close sourced. It is only available on VS code's marketplace but not the Open VSX market place. I know gitpod is not using code-server but code-server does a better job explaining the whole thing here:

https://github.com/cdr/code-server/blob/master/doc/FAQ.md#differences-compared-to-vs-code

**Comment by svenefftinge** [comment]
We can not offer installing the extension into gitpod, but you can install it into your VS Code and then connect to Gitpod.
To make this work, you'll need to tunnel the process through something like Chisel.
@corneliusludmann built an example https://github.com/corneliusludmann/gitpod-playground/tree/sshd-over-chisel

That said we are going to provide SSH access pretty soon, as it is useful in different situations.

**Comment by svenefftinge** [comment]
see https://github.com/gitpod-io/gitpod/issues/1781
