### ISSUE TITLE
gp timeout set now showing timeout value

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16366]
**Steps to replicate:** 
- Run `gp timeout set` with any value, e.g. `gp timeout set 180m`

**Expected result:**
- Response: `Workspace timeout is set to 180 minutes`

**Actual result:** 
- Response is blank for value `Workspace timeout is set to .`

**Comment by mustard-mh** [comment]
Close as it's completed in https://github.com/gitpod-io/gitpod/pull/16367
