### ISSUE TITLE
Typo in entitlement service

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16371]
Minor typo in entitlement service.

https://github.com/gitpod-io/gitpod/blob/be8f9e30c5d8de8922330cbe79ebe5c188e0fb8c/components/server/ee/src/prebuilds/prebuild-manager.ts#L309

_Originally posted by @svenefftinge in https://github.com/gitpod-io/gitpod/pull/16347#discussion_r1104058020_.

**Comment by 2002Bishwajeet** [comment]
Hey, Can I work on this?

**Comment by gtsiolis** [comment]
Absolutely, @2002Bishwajeet! Feel free to open a pull request and link back to this issue. 🏓

**Comment by 2002Bishwajeet** [comment]
Hmm, Looks like this is already fixed in `main` branch

https://github.com/gitpod-io/gitpod/blob/main/components/server/ee/src/prebuilds/prebuild-manager.ts#L309

**Comment by gtsiolis** [comment]
Oh, thanks for taking a closer look and spotting this, @2002Bishwajeet! Let's close this one. Cc @svenefftinge
