### ISSUE TITLE
Tip on Ports panel of statusbar disagrees with State column of Ports view about public vs private

### ISSUE THREAD

**Issue by gjsjohnmurray** [gitpod-io/gitpod#16376]
### Bug description

In the screenshot below the Ports view correctly reports three private ports, but the hover tip on the status bar panel reports them as Public.

![Screenshot](https://user-images.githubusercontent.com/6726799/218497258-3f0f75aa-599d-48c4-925b-66d09e0e24f7.jpg)

### Steps to reproduce

Go to https://gitpod.io/#github.com/gjsjohnmurray/dx-jetpack-demo/pull/1

### Expected behavior

I would expect the hover tip to show the ports as Private.

### Example repository

https://gitpod.io#snapshot/07cfe23d-c8bb-4f87-84fc-cf4a4f7681dc

**Comment by akosyakov** [comment]
I could reproduce it. cc @jeanp413 @mustard-mh

**Comment by filiptronicek** [comment]
It looks like this is happening because we just don't check for the visibility 😄 https://github.com/gitpod-io/gitpod-code/blob/8612f777fb5c44227ca6f2b91f40fa0929637e22/gitpod-web/src/extension.ts#L326-L333
