### ISSUE TITLE
Allow changing languages using a language pack for visual studio code extension

### ISSUE THREAD

**Issue by samuelcaldas** [gitpod-io/gitpod#1637]
The extensions are already there and work well with Theia. we just want to be able to use them

**Comment by corneliusludmann** [comment]
Which extensions do you have in mint? You can install VSCode extensions via the Extensions view (via OpenVSX if available or via drap-and-drop of *.vsix files). See https://www.gitpod.io/docs/vscode-extensions/

Are there any issues?

**Comment by samuelcaldas** [comment]
the problem is not the extension support. I can install the extension. I just can't change the language. even with the Portuguese language extension installed.

**Comment by jankeromnes** [comment]
Hi @samuelcaldas! Please switch your Gitpod IDE to Code in https://gitpod.io/settings/ (under Feature Preview, but will become the default IDE soon). I think the Portuguese language extension should work well there.
