### ISSUE TITLE
[prebuilds] Disable prebuilds from bots by default

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#16386]
Considering push events caused by bots on GitHub for prebuild triggers doesn't seem to be a good idea:
 * We register waves of push events potentially generating exceptional load. 
 * It's questionable that those prebuilds would be used a lot to start workspaces from.

The suggestion here is to flip the default and disable the prebuilds for such events. We can improve as a follow-up to introduce an option for projects to let them run on demand. 

From the payload of a push event, we can easily detect if the change was caused by a bot:
```json
    "sender": {
        "login": "dependabot[bot]",
        "id": 49699333,
        "avatar_url": "https://avatars.githubusercontent.com/in/29110?v=4",
        "url": "https://api.github.com/users/dependabot%5Bbot%5D",
        "html_url": "https://github.com/apps/dependabot",
        "type": "Bot",
        // ...
    },
```

**Comment by geropl** [comment]
Looking at this a bit more holistically:
 - long term I'm sure we want a generic filter (regex?) for branches
 - I could also imagine a generic filter (regex?) for logins (`dependabot[bot]`)

So while I think a option on "type: Bot" (default: false) make sense on it's own, we might want to look beyond that to find sth that is stable long-term.
