### ISSUE TITLE
Review naming + use-cases provided by `gp rebuild`

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16389]
This issue is to discuss two topics: 

1. Naming for the `gp rebuild` command.
2. The exact behaviours exposed. 

**Naming options**

1. `gp rebuild`
1. `gp build`
1. `gp validate`

**Current naming:**

|command|Description|
|-|-|
|`gp rebuild`|Runs: `before` + `init` + `command`.|
|`gp rebuild --from="prebuild"`|Runs: `before` + `command`|
|`gp rebuild --prebuild`|Runs: `before` + `init`|

**Option 1: As / from semantics**

|command|Description|
|-|-|
|`gp rebuild`|Runs: `before` + `init` + `command`.|
|`gp rebuild --from="prebuild"` / `gp rebuild --from-prebuild`|Runs: `before` + `command`|
|`gp rebuild --as="prebuild"`/ `gp rebuild --as-prebuild`|Runs: `before` + `init`|

**Option 2: Explicit task naming**

|command|Description|
|-|-|
|`gp rebuild` (implicit `gp rebuild -bic`)|Runs: `before` + `init` + `command`.|
|`gp rebuild --before -command` / `gp rebuild -bc` |Runs: `before` + `command`|
|`gp rebuild --before -init`/ `gp rebuild -bi`|Runs: `before` + `init`|

**Option 3: Giving the task grouping phase names**

|command|Description|
|-|-|
|`gp rebuild` (implicit: `--phase="full"`) |Runs: `before` + `init` + `command` - Full (not prebuilt) start|
|`gp rebuild --phase="reboot"` |Runs: `before` + `command` - Snapshot, restarts, from prebuild start|
|`gp rebuild --phase="preparation"`|Runs: `before` + `init` - Emulates a prebuild |

**Option 4: Nest under validate namespace**

* `gp configure init` => Alias + move `gp init`
* `gp configure validate` => Alias + move `gp rebuild`

Or, as this applies to workspace configuration...

* `gp workspace init` => Move `gp init`
* `gp workspace validate` => The current `gp rebuild`
* `gp workspace lint`=> The lint aspect of `gp rebuild`

**Comment by akosyakov** [comment]
There are 2 more cases which are start from restart and snapshot, they also do `before` + `command`, but they disregard terminal history from prebuilds.

**Comment by loujaybee** [comment]
Thanks, @akosyakov ! — I added a third option just now, to group the phases, and potentially name them. 

> I'm not sure about Option 2 since it is not clear from flags names that is related to tasks commands.
* Indeed, I was pondering the most explicit way to name the command flags. I'm also not in in love with the idea. 

> But they disregard terminal history from prebuilds.

* Is that a sufficient enough distinction that we should specify a naming? 
* Or, we could just reference in docs to test those two scenarios you could use X command (and it's close enough)?

**Comment by akosyakov** [comment]
Maybe we could use tasks option instead of phase, ie to stay close to current concepts, something like `—tasks=all|prebuild|restart`?

> Is that a sufficient enough distinction that we should specify a naming?

I think we can leave it out and wait for someone to ask.
