### ISSUE TITLE
Update settings layout for the admin dashboard

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16399]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/16307#pullrequestreview-1297969338:

> ❗ issue: One UX change I find a bit jarring is the License and Settings layout, as expected since they were designs with a different layout.

Cc @Devansu-Yadav

### Proposal

> ...
> Reuse the left sidebar which is commonly used for project or org settings, to host two admin settings: General (Usage Statistics and Telemetry settings) and License, so that these pages can continue to use the previous layout.

**Comment by Devansu-Yadav** [comment]
> ### Problem to solve
> Following up from [#16307 (review)](https://github.com/gitpod-io/gitpod/pull/16307#pullrequestreview-1297969338):
> 
> > ❗ issue: One UX change I find a bit jarring is the License and Settings layout, as expected since they were designs with a different layout.

> ### Proposal
> > Two approaches we can take here:
> 
> > 1. **Reuse the left sidebar** which is commonly used for project or org settings, to host two admin settings: _General_ (Usage Statistics and Telemetry settings) and _License_, so that these pages can continue to use the previous layout.
> > 2. **Leave this as is** and open a follow-up issue or PR to tackle the layout reordering for _License_ and _Settings_.

@gtsiolis If we talk about the first approach i.e **Reusing the left sidebar**, are you suggesting having **License** and **Settings** under a single tab(called "Settings" or something appropriate) on the admin dashboard with a sub-menu that contains these two settings (General and License)?

**Comment by gtsiolis** [comment]
> ... are you suggesting having ...

@Devansu-Yadav Exactly! Do you see any drawbacks or blind spots for this change?

**Comment by Devansu-Yadav** [comment]
> > ... are you suggesting having ...
> 
> @Devansu-Yadav Exactly! Do you see any drawbacks or blind spots for this change?

@gtsiolis For now, I can't see any drawbacks as such, as I probably read that only the free community license for Gitpod is now being supported after the Nov 2022 release (please correct me if I'm wrong 😅). I think this change would probably help make the UX of the admin dashboard more consistent with the org dashboard.

**Comment by gtsiolis** [comment]
@Devansu-Yadav Yes:
1. Truth is we're deprecating support for self-hosted and focusing on [Dedicated](https://www.gitpod.io/dedicated), our new offering, see [relevant blog post](https://www.gitpod.io/blog/introducing-gitpod-dedicated).
2. The license page will most probably be dropped all together in the near future.
3. Also, generally the admin dashboard is still useful internally, and I would estimate that parts of it will continue to live through the new Organizations, previously known as teams (see https://github.com/gitpod-io/gitpod/issues/15980), for both Dedicated instances and Gitpod.io. 💭

**Comment by Devansu-Yadav** [comment]
> 2. The license page will most probably be dropped all together in the near future.

@gtsiolis If the License page is most likely going to be dropped, then would it be feasible to combine "Settings" and "License" under a single tab and have a sub-menu? 🤔

I'm thinking from the perspective of duplication of efforts here, since once we go ahead with a sub-menu with "General" and "License" options, we might have to go back to without the sub-menu (as the sub-menu would then only have one option i.e "General") 😅

**Comment by gtsiolis** [comment]
@Devansu-Yadav:
1. Dropping the license page has not been discussed internally with the team. 
2. I'd go for duplication as a boring (simple) solution.
3. Going with the two tabs will also help with the visual balance or the [raison d'être](https://en.wikipedia.org/wiki/Raison_d%27%C3%AAtre#:~:text=Raison%20d'%C3%AAtre%20%2F%CB%8Cr,or%20%22reason%20to%20be%22.) of the sidebar in settings.
4. By the time we decide to drop the license tab, there could be a need for more settings that can be nested in this tab.
