### ISSUE TITLE
vaadin

### ISSUE THREAD

**Issue by fmeirlyn** [gitpod-io/gitpod#1640]

**Comment by svenefftinge** [comment]
Please provide more information.

**Comment by jankeromnes** [comment]
@fmeirlyn FYI, Vaadin is supported in Gitpod:

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/vaadin/skeleton-starter-flow-spring/tree/v14)

See also:
- https://www.gitpod.io/docs/languages/java/#vaadin-in-gitpod
- https://vaadin.com/start (click on the "Online Workspace" tab)
