### ISSUE TITLE
Update spacing layout for user, workspace, project, and organization in the admin dashboard

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16408]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/16307, there are a few nitpicks that fell between the cracks., besides the issue described in https://github.com/gitpod-io/gitpod/issues/16399.

1. The page layout when visiting a workspace or a project lacks a proper width limit.
2. The user, workspace, project, and organization could benefit from some top margin.
3. From a discussion in the initial PR in https://github.com/gitpod-io/gitpod/pull/16307#pullrequestreview-1297969338:  _There are a few minor issues like column header alignment and missing sorting icons ..._

Cc @Devansu-Yadav

| Project | Workspace | User | Org |
|-|-|-|-|
| <img width="1512" alt="admin-project" src="https://user-images.githubusercontent.com/120486/218979744-fcdd73f0-4162-4e76-9025-c3260ccd6056.png"> | <img width="1512" alt="admin-workspace" src="https://user-images.githubusercontent.com/120486/218979755-fe83f380-e3f7-401c-b8e5-00f97a0dce77.png"> | <img width="1512" alt="admin-user" src="https://user-images.githubusercontent.com/120486/218979767-ee8ce7f6-2a16-4d3c-98ad-c8b6cda4184b.png"> | <img width="1512" alt="admin-org" src="https://user-images.githubusercontent.com/120486/218979775-18bed502-77e5-466c-9224-1b45d60fdbb6.png"> |

**Comment by Devansu-Yadav** [comment]
> ### Problem to solve
> Following up from #16307, there are a few nitpicks that fell between the cracks., besides the issue described in #16399.
> 
> 1. The page layout when visiting a workspace or a project lacks a proper width limit.
> 2. The user, workspace, project, and organization could benefit from some top margin.
> 3. From a discussion in the initial PR in [UI updates to admin dashboard #16307 (review)](https://github.com/gitpod-io/gitpod/pull/16307#pullrequestreview-1297969338):  _There are a few minor issues like column header alignment and missing sorting icons ..._

@gtsiolis I have a clear idea of how to proceed with **[1]** and **[2]**. For **[3]**, I'm aware of the column header alignment and missing sorting icons issue for the **Users** page. Any other pages that you could notice that have the same issue on the admin dashboard?

**Comment by gtsiolis** [comment]
@Devansu-Yadav For [3]:
1. Besides the _Users_ page, the _Workspaces_ page has an extra empty cell in front of the name.
2. The sorting icon seems more useful only to the _Users_ page as you mentioned above.

There are more improvements I can jot down if we go down this route, but I'd like to limit the amount of focus or energy we put in this until we can be sure the admin dashboard or its component will still be useful in the product direction. Listing of  them in case any of these are trivial to fix:
- https://github.com/gitpod-io/gitpod/issues/10499
- https://github.com/gitpod-io/gitpod/issues/8983
- https://github.com/gitpod-io/gitpod/issues/3836
- https://github.com/gitpod-io/gitpod/issues/3930
- https://github.com/gitpod-io/gitpod/issues/14760
- https://github.com/gitpod-io/gitpod/issues/14762
- https://github.com/gitpod-io/gitpod/issues/6372
- ...

**Comment by Devansu-Yadav** [comment]
> @Devansu-Yadav For [3]:
> 
> 1. Besides the _Users_ page, the _Workspaces_ page has an extra empty cell in front of the name.
> 2. The sorting icon seems more useful only to the _Users_ page as you mentioned above.

Sure, I'll make the appropriate changes.

> There are more improvements I can jot down if we go down this route, but I'd like to limit the amount of focus or energy we put in this until we can be sure the admin dashboard or its component will still be useful in the product direction. Listing of them in case any of these are trivial to fix:
> 
> * [Keep admin menu active when opening a user, project, or team #10499](https://github.com/gitpod-io/gitpod/issues/10499)
> * ...

This makes sense. Maybe once we tackle this issue as well as #16399, I can probably have a look into these.

**Comment by gtsiolis** [comment]
Thanks, @Devansu-Yadav! I appreciate the effort and energy you put in this. 🍊
