### ISSUE TITLE
Java/Maven build fails when browser tab is not focused on Gitpod page

### ISSUE THREAD

**Issue by Hakky54** [gitpod-io/gitpod#1641]
### Describe the bug

I have a Java/Maven project [Mutual-tls-ssl](https://github.com/Hakky54/mutual-tls-ssl) which I am using within Gitpod workspaces. When I open this project within gitpod it starts building because of the init script. If my browser is not focused on the gitpod tab during the initial build, the build will fail.

### Steps to reproduce

Open the github project in gitpod and switch to another tab. The build takes around 3 to 4 minutes. When you switch back after that amount of time you will see that the build will fail.

### Expected behavior

The build should be successful 

### Additional information

See here for the video where I demonstrate the bug: https://youtu.be/i1ilR6RMUGc

1. Initial build with focus -> build passes
2. another build without focus -> build passes
3. Initial build without focus -> [build fails](https://youtu.be/i1ilR6RMUGc?t=439)
4. rebuild with focus -> build passes

### Example repository

https://github.com/Hakky54/mutual-tls-ssl

**Comment by corneliusludmann** [comment]
Hello and thanks for reaching out. Unfortunately, I'm not able to reproduce this. I opened https://gitpod.io#https://github.com/Hakky54/mutual-tls-ssl and changed the tab focus. After some time I returned to the tab and the build has been successfully finished.

Actually, I don't believe that this has something to do with the focus. Could it be that it was an unfortunate coincidence that leads to the build failure (e.g. network issues etc.)?

Please let me know if this problem still exists and if you are able to reproduce this.

**Comment by Hakky54** [comment]
Thank you for having a look at it @corneliusludmann It is strangly not occuring anymore after retrying 20+ times today. I had seen it multiple times happening over the last couple of months and thought it had to do something with not focusing on the tab during the initial build. Well that was the only thing which I could relate to... But maybe it was duo some network issues, I am not quite sure. I thought it would be handy to share it here, but we can close this ticket. If I discover a way to reproduce it with specific steps than I will share it here

**Comment by corneliusludmann** [comment]
OK, thanks. That's sounds good for now.
