### ISSUE TITLE
Copy from workspace to other workspace is not working

### ISSUE THREAD

**Issue by skflowne** [gitpod-io/gitpod#1642]
### Describe the bug

I have 2 workspaces (source and destination)
If I right-click "Copy" in source and then right-click "Paste" in the destination it says "Please use browser command or shortcut"
If I use CTRL+C/CTRL-V, nothing happens
If I drag from source and drop in destination nothing happens
If I right-click "Download" from source and then use drag and drop to destination then it works

### Steps to reproduce
The file I was trying to copy was generated with code in the source workspace and is not tracked with Git, maybe that's why ?

### Expected behavior
All methods should copy files into destination workspace

**Comment by corneliusludmann** [comment]
Unfortunately, copying files between workspaces via the clipboard is not possible and probably won't be due to technical limitations. You need to download the files to your local computer and upload them in the other workspace.
