### ISSUE TITLE
Authorization failure: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#16431]
https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22server%22%2529%0A%22Error%20%5BERR_HTTP_HEADERS_SENT%5D:%20Cannot%20set%20headers%20after%20they%20are%20sent%20to%20the%20client%22;timeRange=P7D;cursorTimestamp=2023-02-16T08:16:01.937Z?authuser=0&project=gitpod-191109

**Comment by AlexTugarev** [comment]
Some context: this comes from the OAuth Server part which is used to authorize local apps.

cc. @gitpod-io/engineering-ide
