### ISSUE TITLE
Improve the checkmark icon for the selected organization in the org selector

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16434]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/16422, this is a placeholder issue to improve the **checkmark icon** for the selected organization in the org selector. Ignoring the small design details here's the checkmark for light and dark themes we need to replace. Cc @selfcontained 

```svg
// LIGHT THEME
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none">
  <path fill="#78716C" fill-rule="evenodd" d="M18.2348 5.8867 7.88699 16.2345l-2.12132-2.1213L16.1135 3.76538l2.1213 2.12132Z" clip-rule="evenodd"/>
  <path fill="#78716C" fill-rule="evenodd" d="m3.88695 8.06069 5.00004 5.00001-2.12132 2.1214-5.00005-5.0001 2.12133-2.12131Z" clip-rule="evenodd"/>
</svg>

// DARK THEME
<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none">
  <path fill="#E7E5E4" fill-rule="evenodd" d="M18.2348 5.8867 7.88699 16.2345l-2.12132-2.1213L16.1135 3.76538l2.1213 2.12132Z" clip-rule="evenodd"/>
  <path fill="#E7E5E4" fill-rule="evenodd" d="m3.88695 8.06069 5.00004 5.00001-2.12132 2.1214-5.00005-5.0001 2.12133-2.12131Z" clip-rule="evenodd"/>
</svg>
```

| BEFORE | AFTER |
|-|-|
| ![org-a1](https://user-images.githubusercontent.com/120486/219357281-3efb2545-d9d3-4357-b625-b48c5370a77e.png) | ![Navigation](https://user-images.githubusercontent.com/120486/219357295-72276447-83d1-4451-937a-770b082e70f2.png) |
| ![org-a2](https://user-images.githubusercontent.com/120486/219357392-c0dd27eb-ba9e-4723-9420-4bbe02349f8a.png) | ![Navigation-1](https://user-images.githubusercontent.com/120486/219357397-90218b05-1c5c-4348-9fb8-38d2076d5d23.png) |

**Comment by Devansu-Yadav** [comment]
@gtsiolis I'd like to pick up this issue 😄

**Comment by gtsiolis** [comment]
@Devansu-Yadav Since there's no assignee or anyone else who mentioned they're working on this, feel free to open a pull request and link back to this issue. 🏓
