### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_socket')

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#16444]
Errors from websocket connection

[logs](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22server%22%2529%0A--%20%2263908d4d-f301-4863-99fd-5ee714628ba8%22%0A%22TypeError:%20Cannot%20read%20properties%20of%20undefined%20%2528reading%20'_socket'%2529%22;timeRange=P7D;cursorTimestamp=2023-02-17T07:21:51.282Z?authuser=0&project=gitpod-191109)

**Comment by AlexTugarev** [comment]
That's a low priority, I think. We can also consider reverting the PR which introduced this error. Don't have it handy, but we've tried to clean up failed websockets, which were in a weird state, but that didn't work.
