### ISSUE TITLE
Usage pagination is broken

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16453]
### Bug description

Paginating through usage entries is not working—it's redirecting back to the first page.

### Steps to reproduce

1. Go to [`/usage`](https://gitpod.io/usage) for an org that has more than 1 page of usage entries.
2. Try navigating to a different page (2, 3, Next, etc.)
3. Notice the flaky reload of the page and redirect back to page 1.

**Comment by Dhruv-Gajjar** [comment]
Hey @gtsiolis I would like to work on this issue.

**Comment by gtsiolis** [comment]
Hey @Dhruv-Gajjar! Since there's no assignee or anyone else who mentioned they're working on this, feel free to open a pull request and link back to this issue. 🏓

**Comment by gtsiolis** [comment]
Closing this as the issue has been resolved. 📕 

Cc @Dhruv-Gajjar because https://github.com/gitpod-io/gitpod/issues/16453#issuecomment-1437946695.

Cross-posting [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1678103312085009) (internal). Cc @svenefftinge
