### ISSUE TITLE
Gitpod doesn't highlight vim files

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1648]
gitpod compared to vim:
![image](https://user-images.githubusercontent.com/11302521/86648270-032c4080-bfe1-11ea-8c32-7b6aa878eee9.png)

Expecting it to highlight vim files

https://gitpod.io/#snapshot/ba7a7aa4-dc51-4f15-85e3-087105d88035

**Comment by corneliusludmann** [comment]
There is no built-in language support for vim files. However, you could a VSCode extension for this. I tried `vscode-viml-syntax` from `dunstontc` and it works pretty well:
- https://github.com/dunstontc/viml
- https://marketplace.visualstudio.com/items?itemName=dunstontc.viml

![image](https://user-images.githubusercontent.com/24960040/87534357-33857600-c696-11ea-9bb7-7c94a88fe535.png)

Currently, it's not in OpenVSX (I'll try to add it soon) but you can drag-and-drop this extension into the Gitpod extensions panel.

Don't hesitate to re-open this issue if needed.

**Comment by corneliusludmann** [comment]
The extension is now on OpenVSX and can be installed out of the extensions view in Gitpod easily: https://open-vsx.org/extension/dunstontc/viml
