### ISSUE TITLE
Review perf impact of `gp rebuild` on workspace caching, backup performance, etc. 

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16480]
Currently `gp rebuild` encourages users to update their images. However, we need to review the potential impact this has on workspace image caching, particularly as the images users use become more unique, the cache hits should decrease. We need to understand the impact this has on workspace performance. This issue is to gather data on the impact, so that we can make any decisions (or not) on how to modify, or improve either workspace caching, or the `gp rebuild` feature.

**Comment by loujaybee** [comment]
@gitpod-io/engineering-workspace -> Any tips and pointers to this data, or support in gathering and analysing the data would be useful.

**Comment by loujaybee** [comment]
Adding to @gitpod-io/engineering-workspace inbox for visibility, but IDE team will continue to own and drive the work.

**Comment by kylos101** [comment]
> encourages users to update their images

How is `gp rebuild` doing? Can you share an example?

> However, we need to review the potential impact this has on workspace image caching, particularly as the images users use become more unique, the cache hits should decrease. 

I assume you are referring to workspace node and IPFS cache misses, and not a cache miss in-workspace using Docker in Workspace?

> We need to understand the impact this has on workspace performance.

Less cache hits will increase start times. We have [several SLOs here](https://pyrra.gitpod.io/?filter=%7Bteam=%22workspace%22%7D), for example.

>  the IDE team will continue to own and drive the investigation and data analysis work for now.

Given :point_up: adding to IDE team inbox.

**Comment by loujaybee** [comment]
> How is gp rebuild doing? Can you share an example?

We're are not doing this (nudging users to update workspace images) yet. However, a natural consequence of the feature might be more custom images, as it makes the configuration loop simpler. In future we (after a clean up of workspace images) we might get more pushy nudging users to different workspace images. 

> I assume you are referring to workspace node and IPFS cache misses, and not a cache miss in-workspace using Docker in Workspace?

Yep, general workspace cache is the question, not in workspace cache. However in workspace cache I presume will affect backup sizes, which is another dimension/topic of the issue 🙏

**Comment by loujaybee** [comment]
Dropping, will pick up in future.
