### ISSUE TITLE
# Commands to start on workspace startup tasks:   - name: Setup & Build     before: yarn global add express     init: yarn install     command: yarn build  # Ports to expose on workspace startup ports:   - port: 3000     onOpen: open-preview     name: Website     description: Website Preview

### ISSUE THREAD

**Issue by valash85** [gitpod-io/gitpod#16484]

**Comment by valash85** [comment]
# Commands to start on workspace startup
tasks:
  - name: Setup & Build
    before: yarn global add express
    init: yarn install
    command: yarn build

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-preview
    name: Website
    description: Website Preview

**Comment by loujaybee** [comment]
Hey @valash85 can you reformat the title of this issue, and update the description with the issue you're facing? 

I'm going to close for now, but feel free to re-open when you've updated the description, etc 🙏

**Comment by valash85** [comment]
> ## Is your feature request related to a problem? Please describe
> 
> 
> ## Describe the behaviour you'd like
> 
> 
> ## Describe alternatives you've considered
> 
> 
> ## Additional information from our community on how to get a good job here **[![image](https://user-images.githubusercontent.com/121147518/227375918-35f27325-e015-417e-af67-232eae1d5893.jpeg)]()**context
>  ![image](https://user-images.githubusercontent.com/121147518/227376101-f051d27d-a41e-460b-a93b-ad9a15ba16b1.jpeg)
