### ISSUE TITLE
copy and paste \r\n

### ISSUE THREAD

**Issue by rdmueller** [gitpod-io/gitpod#165]
**Describe the bug**
When on a windows machine, I often copy & paste the shebang of a file like

    #!/usr/bin/env groovy

but when I try to run the file, I get the following error:

    /usr/bin/env: ‘groovy\r’: No such file or directory

**To Reproduce**
Copy & paste between files

**Expected behavior**
It seems that on windows, a \n gets replaced with \r\n
Expected is that this does not happen.

**Comment by XinYaanZyoy** [comment]
@rdmueller change .editorconfig to end_of_line = lf or if you don't have that file try to change it manually!
i guess that's the causer!
