### ISSUE TITLE
Extract text and search input from forms as component

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16511]
### Problem to solve

There are around more than **100 instances** of text inputs or search inputs elements across the product, see `<input>` instances[[1](https://github.com/search?q=repo%3Agitpod-io%2Fgitpod+%3Cinput&type=code)].

Currently, most input elements rely on the main button styles in [`index.css`](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/index.css).

https://github.com/gitpod-io/gitpod/blob/77b4d0672387e4f319ad5efd0d325df041020a55/components/dashboard/src/index.css#L83-L91

It would be great to have some form elements as components to cover some of the different elements, states, variants, etc. of each element once across the product.

**Elements**: Checkbox, Date Picker, Filter, Search, Textarea, Text Input, etc.

Some basic designs already exist for the **input** and the **checkbox** elements.

| Input | Checkbox |
|-|-|
| <img width="556" alt="Input" src="https://user-images.githubusercontent.com/120486/220614314-c0a3bee4-13eb-43fe-a39c-c867ad807e6c.png"> | <img width="672" alt="Checkbox" src="https://user-images.githubusercontent.com/120486/220614293-b3a78546-84f7-4b90-bd95-4a7c03754a28.png"> |

See also [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1676644116946799?thread_ts=1676409669.544409&cid=C01KPEPQYE6) (internal). Cc @selfcontained

**Comment by Devansu-Yadav** [comment]
@gtsiolis Can I continue on @selfcontained's work in #16545 by helping to replace the use of the `<CheckBox/>` component with the newly created `<CheckboxInput>` component across the dashboard code?

**Comment by gtsiolis** [comment]
Cross-posting from relevant comment in https://github.com/gitpod-io/gitpod/pull/16636#issuecomment-1463806787 for visibility and more context:

> There are a few minor spacing differences with the search input in dashboard vs. admin dashboard, but should be fine to merge this as is and tackle this separately with https://github.com/gitpod-io/gitpod/issues/16511. Cc @selfcontained

> | Admin (Users) | Project (Branches) | Admin (org) |
> |-|-|-|
> | <img width="352" alt="admin-users" src="https://user-images.githubusercontent.com/120486/224329441-3ebf2415-45fa-4ba0-abee-f169e5773132.png"> | <img width="352" alt="project-branches" src="https://user-images.githubusercontent.com/120486/224329444-f6013e7c-c38a-425e-8db8-d157665f6be0.png"> | <img width="352" alt="admin-org" src="https://user-images.githubusercontent.com/120486/224329452-cf25b4fa-eaad-4564-b21e-576f8b314000.png"> |

**Comment by Devansu-Yadav** [comment]
@gtsiolis I'd like to work on extracting the search input as a separate component that could be used across both the dashboards 😄

Currently, I see a couple of places where `<input type="search" ... />` element is being used within the dashboard code.
