### ISSUE TITLE
New Gitpod workspaces keep installing a certain VS Code extension

### ISSUE THREAD

**Issue by AniX** [gitpod-io/gitpod#16526]
### Bug description

This started as question on Discord: https://discord.com/channels/816244985187008514/1074434872355078316

We are using gitpod.io cloud with an org and many different repositories. All VS Code (browser).

The `.gitpod.yml` files define a list of extensions. Because Jupyter extension for some reason interferes with the code collapse/expand feature in Python files, I wanted to remove again the Jupyter extension and a bunch of related extensions that depend on it.

I removed these related Jupyter extensions from all `.gitpod.yml` files, yet when I start a new workspace the extensions will be installed again. Our dotfiles repo doesn't include these extensions either.

I have the suspicion I have enabled them with my user profile as well and now they are installed with every new workspace because of some user setting that I can't see.

In multiple workspaces from different projects I selected *Disable* all the related Jupyter extensions - the first option, not the *Disable (Workspace)* and also uninstalled. It works in the current workspace. But with any new workspace these extensions will be installed and enabled again. I also tried syncing each extension, with no avail.

I was asked to launch an empty workspace with `gitpod.new`: This workspace didn't include these extensions.

Then I created again a new workspace from one of the projects and the extensions are showing up. I did run a prebuild on the branch and tried in another new workspace, still with the offending extensions installed.  I can't enable the sync. I can disable them and also uninstall them, but still not persistently for new workspaces.

Another team member reported back. When he launches via `gitpod.new` he gets the Jupyter extensions (different from me). He is certain he never manually/explicitly installed them (while I'm not certain in my case).

How do I permanently remove them from all my new workspaces? Or at least how can I figure out why they are still installed/enabled?

![_gitpod_yml](https://user-images.githubusercontent.com/1204628/220886618-b8de8150-0108-4104-94a9-0527425c68f1.png)
![_vscode_settings_json](https://user-images.githubusercontent.com/1204628/220886622-329ed5c2-435d-4ae0-81f8-870da52f872d.png)

### Steps to reproduce

1. In any Bitbucket repo, e.g. `main` branch, click on *Gitpod* button
2. Wait until the new workspace is initialized
3. In the side navigation, click on Extensions.
4. For all five extension the UI shows *This extension is enabled globally* and *This extension is ignored during sync*.
![extensions](https://user-images.githubusercontent.com/1204628/220887427-c06985da-8262-4a7f-bd99-6af3b23ae5ed.png)

### Expected behavior

These five Jupyter-related extensions should not be installed and enabled in any of the new workspaces.

### Example repository

https://bitbucket.org/modigiev2/insfdc-srv

### Anything else?

I'll email the vscode logs.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4qkp6)

**Comment by axonasif** [comment]
Attached the link to the email on the main issue `Anything else` 👆

**Comment by jeanp413** [comment]
@AniX they are installed automatically when you install the python extension because they are specified in its package.json as an extension pack.

Possible workaround:
- you can try open an empty workspace with gitpod.new and then install the python extension manually from the extensions view, this will install the jupyter extension too and then disable it, this way the extensions will be synced in your profile and disable state for the jupyter extension too. The downside of this is python extension will be installed in all repos you open.

> Because Jupyter extension for some reason interferes with the code collapse/expand feature in Python files,

Maybe there's a setting from the extension that you can disable so it doesn't break collapse/expand, you could ask/report that in the jupyter extension repo

![image](https://user-images.githubusercontent.com/25115070/221080470-dd3535b5-5e47-4bbf-acc4-e7ab110a82e5.png)
![image](https://user-images.githubusercontent.com/25115070/221082009-27ba7987-af6d-41f4-8795-ad9a1cdbd7d2.png)

**Comment by AniX** [comment]
@jeanp413  Many thanks for your help.  I thought I'd give your alternative suggestion another shot and finally found a workaround [here](https://github.com/microsoft/vscode-jupyter/issues/12520#issuecomment-1377539302).

This works for us even better because we don't have to disable/enable the extension and code folding works. In our case, I have added `"editor.foldingStrategy": "indentation"`.

Again many thanks to the gitpod team!
