### ISSUE TITLE
"HelloWorld.java" is a non-project file -- But why?

### ISSUE THREAD

**Issue by mkarg** [gitpod-io/gitpod#1654]
Gitpod tells me that "HelloWorld.java" is a non-project file. In fact I wonder why! Here is what I did:
* In folder "I" I create a small java project, and it works fine in Gitpod.
* I copied folder "I" to folder "II", and that project also works fine in Gitpod.
* I did that another time -- and THIS ONE is reported as not being a project file!

This looks weird to me. Any ideas what my fault is?

**Comment by geropl** [comment]
Hi @mkarg ,

this sounds like maybe the Java Language Server does not recognize your folder structure properly. Could you share a concrete example, maybe as Gitpod Snapshot?

**Comment by mkarg** [comment]
Dumb Question: How to provide a Gitpud Snapshot...?

**Comment by corneliusludmann** [comment]
In your Gitpod IDE open the `Workspace` menu and select `Share Workspace Snapshot`.
