### ISSUE TITLE
Remove the company name field in the user profile

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16560]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/16501, the new **Company Website** field a user optionally fills in during the onboarding can never be seen from the user again.

Currently, in the user profile a previous **Company** fields is present, which was initially added for similar reasons in https://github.com/gitpod-io/gitpod/pull/11023, see also https://github.com/gitpod-io/gitpod/issues/10999.

Now the company field seems duplicate if not redundant.

### Proposal 

We could probably :a: remove the _Company_ field in the user profile or also :b: replace it with the _Company Website (optional)_ so that users can edit this after the onboarding and not end up with an empty field they thought they've already filled in or have to fill in again.

**Comment by selfcontained** [comment]
I was thinking about this too, and think perhaps we could just drop Company, and not add Company Website either. There's not a great reason I can think of that a user would want to update this after onboarding, and we don't have it surface anywhere in the product. We could always surface it later if we find a reason to surface it in Product somewhere, but atm it's only used as part of the information collected during onboarding to help us understand users better, like their reasons for signing up and what they hope to get out of Gitpod. Thoughts?
