### ISSUE TITLE
Timeout - decrease timeout to less than 30 min.

### ISSUE THREAD

**Issue by AharaleBatonia** [gitpod-io/gitpod#16565]
## Is your feature request related to a problem? Please describe

For now, the timeout is set for 30m and the paid version can extend the value up. i think it makes sense to add the option to decrease the time to a few minutes [eg. 5m] so that students like me that are using your generous free tier offer can better use this time frame instead of wasting time.

## Many Thanks :)
Aharale

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4qv0q)

**Comment by axonasif** [comment]
Not sure if this goes to WebApp or IDE team, added to both (GitHub) **Projects**, please feel free to remove if needed.

**Comment by loujaybee** [comment]
Thanks, @AharaleBatonia ! This is currently being discussed here: 

- https://github.com/gitpod-io/gitpod/pull/16503

Relates to: 

- https://github.com/gitpod-io/gitpod/issues/16089
- https://github.com/gitpod-io/gitpod/issues/16200
- https://github.com/gitpod-io/gitpod/issues/9038

**Comment by filiptronicek** [comment]
Also, before the discussions come to any conclusions, @AharaleBatonia, I recommend manually executing `gp stop` or stopping the workspace from the UI when you're finished with it --> by that you can eliminate wasting your unused resources 🙂

**Comment by axonasif** [comment]
That's a great suggestion @filiptronicek! 🎯 

I personally have a keybinding on VSCode just for that. It's ⌘ + Shift + 0. And it has turned into a habit to press that before closing any workspace tab 😆 

Also got a shortcut through tmux on the terminal, that fires `gp stop` command when pressed.
