### ISSUE TITLE
Workspace build fails: 'file integrity checksum failed for "usr/share/emacs/26.3/lisp/leim/quail/ipa-praat.elc"'

### ISSUE THREAD

**Issue by rokopt** [gitpod-io/gitpod#1656]
### Describe the bug
When trying to build a new Gitpod image from [one of my repos](https://github.com/rokopt/geb-lang/tree/containers-dev) by clicking the "Gitpod" button provided by the app, I have today started consistently receiving the following error:

```
Error: build failed: cannot push base image: file integrity checksum failed for "usr/share/emacs/26.3/lisp/leim/quail/ipa-praat.elc"
```

### Steps to reproduce
Navigate to [this Gitpod link](https://gitpod.io/#https://github.com/rokopt/geb-lang/tree/containers-dev)

### Expected behavior
A new build should occur and I should eventually end up in a workspace built from that repo.  It worked about one week ago, I believe.  The build today was after a new checkin, but emacs should already have been being installed in last week's build.

### Example repository
https://github.com/rokopt/geb-lang/tree/containers-dev

**Comment by geropl** [comment]
Hi @rokopt ,


The issue you describe normally happens under one of the following circumstances:
 - disk full (was not)
 - one of the layers got corrupted

I cleared all old layers from the cache, could you try to rebuild again? The link you provided seems to point to a private repository I have no access to and cannot reproduce/retry.

**Comment by rokopt** [comment]
> Hi @rokopt ,
> 
> The issue you describe normally happens under one of the following circumstances:
> 
> * disk full (was not)
> * one of the layers got corrupted
> 
> I cleared all old layers from the cache, could you try to rebuild again?

Yes -- it works now.  Thank you very much!

> The link you provided seems to point to a private repository I have no access to and cannot reproduce/retry.

Oops -- sorry about that; I'll open it up if and when it exhibits another bug before I open it up for good (once it's no longer embarrassingly skeletal!).

**Comment by corneliusludmann** [comment]
@rokopt: Can this issue be closed? Or is it still an issue for you?

**Comment by rokopt** [comment]
> @rokopt: Can this issue be closed? Or is it still an issue for you?

It can be closed.  Should I do so myself when one of my issues is resolved, or should I leave that to maintainers?

Thanks again!

**Comment by corneliusludmann** [comment]
Great! :-) You can do it yourself when it's solved.
