### ISSUE TITLE
i can´t run potigol

### ISSUE THREAD

**Issue by mobr132** [gitpod-io/gitpod#1658]

**Comment by geropl** [comment]
Oh, I may have been a bit too quick here, just learned that Potigol is a language: http://potigol.github.io/
Could you elaborate what you did, what you expected to happen and what did nor work?

**Comment by JesterOrNot** [comment]
The snapshot does not work. They provide one on the site.

**Comment by JesterOrNot** [comment]
Nevermind might have been a bug

**Comment by JesterOrNot** [comment]
works on refresh

**Comment by JesterOrNot** [comment]
Nevermind not working 🤔

**Comment by lrlucena** [comment]
Hi @JesterOrNot, are you still having problem with Potigol?
