### ISSUE TITLE
Wrong highlighting of 'false' in shell/bash files

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1659]
It is unwanted from theia to highlight argument 'false' as function/command:

![image](https://user-images.githubusercontent.com/11302521/87297735-33a43b00-c509-11ea-88fc-153cdca26f79.png)

**Comment by corneliusludmann** [comment]
Same as #1660 → https://github.com/microsoft/vscode/tree/master/extensions/shellscript
