### ISSUE TITLE
[ssh] debug logs are too noisy

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#16607]
### Bug description

In [this](https://cloudlogging.app.goo.gl/cMbTk3nmqPczq2aE8) 3 hour period, ~627,000 entries were created by one workspace.

![image](https://user-images.githubusercontent.com/1272076/221882187-47211216-b7b6-42ff-b035-63d54c1a90b2.png)

This must inflate GCP logging costs.

### Steps to reproduce

Not sure

### Expected behavior

Some form of exponential backoff for related logs? The assumption is these logs are specific to SSH, and perhaps can be better tuned.

**Comment by kylos101** [comment]
@laushinka may we ask for your help with prioritizing this issue? :pray:

**Comment by kylos101** [comment]
Updated the issue description to clarify that these logs were generated by a single workspace

**Comment by akosyakov** [comment]
We tried other levels and they don't give us insights in actual ssh channels. We used to understand what is going with VS Code Desktop and JB integrations on customer requests. Not sure what would be an alternative right now.

> This must inflate GCP logging costs.

How much?

**Comment by kylos101** [comment]
> How much?

@akosyakov @laushinka added cost info in https://gitpod.slack.com/archives/C01KGM9BH54/p1678207748706589?thread_ts=1678207199.872739&cid=C01KGM9BH54

> We tried other levels and they don't give us insights in actual ssh channels. We used to understand what is going with VS Code Desktop and JB integrations on customer requests. Not sure what would be an alternative right now.

Perhaps you could change the logging, such that it only gets enabled conditionally? This way, you'd opt it into higher levels, instead of always capturing so many logs?
