### ISSUE TITLE
docker-compose is partially not working (panic) when used in a .gitpod.yml task

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#16614]
### Bug description

`docker compose` panics when called through [a .gitpod.yml task](https://github.com/Derroylo/sulu-workspace-sample/blob/e024720c9d6859b511ab3ab2fb73e51d64a2f006/.gitpod.yml#L68).

<img width="1034" alt="Screenshot 2023-03-01 at 12 48 43 AM" src="https://user-images.githubusercontent.com/39482679/221950086-a0f2c418-40ef-4664-b057-3114e2ad86a5.png">

However, if you manually run the command again from the same Gitpod created task terminal, it will work without any panicking. Which is very weird.

It seems to be because of a custom `docker-compose`[^1] binary that we're installing[^2]. It also overwrites the `docker-compose` installation from our [tool-docker](https://github.com/gitpod-io/workspace-images/blob/a389f4d49ada020c169121735df1eb1cac283687/chunks/tool-docker/Dockerfile#LL19C5-L19C140) workspace-image.

Re-installing the vanilla docker-compose before the execution of it inside a task group works-around[^3] the issue:
```yaml
before: sudo curl -o /usr/local/bin/docker-compose -fsSL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-$(uname -m)
```
with a potential caveat of breaking the intended behavior implemented through https://github.com/gitpod-io/gitpod/pull/16363

[^1]: https://github.com/gitpod-io/compose
[^2]: https://github.com/gitpod-io/gitpod/blob/504d1a0a0151804be8ba25b099d21d05cf861bfd/components/docker-up/docker-up/main.go#L297
[^3]: https://github.com/axonasif/sulu-workspace-sample/commit/babe22f85a339bcc1bef7a7f39a2fa7dc095252d

### Steps to reproduce

- Open https://github.com/Derroylo/sulu-workspace-sample/ on Gitpod
- See if the first task named `Docker` panicked
- Now manually run either `docker compose pull` or `docker compose up` and see it work.

### Expected behavior

`docker-compose` command should continue to work without panicking as before when run from `.gitpod.yml`.

### Example repository

- https://github.com/Derroylo/sulu-workspace-sample

Also, if you don't run `docker-compose` through `.gitpod.yml` tasks and then manually run it from a terminal, it also works. Which means, a halfway failed previous cache of a `docker-compose` run from `.gitpod.yml` is not effecting the consequent manual execution of `docker-compose`.

See:
- https://github.com/axonasif/sulu-workspace-sample

### Anything else?

Noticed three community members to bring up this issue:
- https://discord.com/channels/816244985187008514/1079483006756073602
- https://discord.com/channels/816244985187008514/1079753969703866419
- https://discord.com/channels/816244985187008514/1079483006756073602/1080140009547501599

**Comment by MahdiBaghbani** [comment]
same here, with a small difference that is some of my co-workers cannot manually run the command again from the same Gitpod created task terminal, the docker compose gives the same panic message again and again.

**Comment by yasharpm** [comment]
@MahdiBaghbani 's colleague here. The "before" command provided in the issue made me able to get it working. I have a theory as to why it is different for me. It might have to do something with me having 2 gitpod instances running on 2 different projects in the same time.

**Comment by Phxntxm** [comment]
To give maybe a bit more information as well, this is a docker compose bug specifically... there's a bug report for it here:

https://github.com/docker/compose/issues/10322

**Comment by akosyakov** [comment]
I'm moving it to the workspace team inbox, since it seems to be related to generic docker-compose integration. (if at all to Gitpod in particularly)

**Comment by kylos101** [comment]
@Phxntxm this looks like it may have been fixed in https://github.com/docker/compose/pull/10336, once Docker releases an official version, we'll plan to update our fork and ship an update to Gitpod. :pray:

**Comment by sonali-rajput** [comment]
This is so confusing omg I can't figure it out my brain is hurting now.

**Comment by pservit** [comment]
docker-compose [fixed](https://github.com/docker/compose/pull/10336/files) this bug in [v2.17.0](https://github.com/docker/compose/releases/tag/v2.17.0) release

please update gitpod fork, we have all our prebuilds broken :(

**Comment by kylos101** [comment]
@pservit :wave: , we'll be including the fix, https://github.com/gitpod-io/gitpod/pull/17049 in tomorrows deploy. Thanks, @aledbf !
