### ISSUE TITLE
ESP webtool integration 

### ISSUE THREAD

**Issue by norbert-walter** [gitpod-io/gitpod#16625]
I run a [website](https://open-boat-projects.org/en/diy-ultraschall-fuellstandsmessung/) with open source code for ESP32 microcontrollers programmed in C. With Gitpod it is possible to compile the code as if you were doing it with PlatformIO. I would think it would be really cool if you could integrate the ESP webtools into Gitpod.

[https://esphome.github.io/esp-web-tools/](https://esphome.github.io/esp-web-tools/)

With ESP webtools, the binary code could be flashed onto the microcontroller directly from the browser via the UBS interface on the PC or laptop. A Flash tool would be integrated into Gitpod with ESP webtool. You could add a flashing icon to the bottom of the footer like it's done in PlatformIO. Flash functionality could add depending on the gitpod.yml when PlatformIO is loaded as environment.

This would provide a completely uncomplicated online development environment for ESP32 microcontrollers, which are often used in the DIY sector. This greatly reduces the barriers to entry for beginners.

Or to put it another way: Is there a way to automatically pass the binary code to another web application?

**Comment by axonasif** [comment]
I'm not familiar with this topic. But I'm wondering if the below issue is related?
- https://github.com/gitpod-io/gitpod/issues/5814

**Comment by norbert-walter** [comment]
Yes, the issue is similar. Thanks

**Comment by axonasif** [comment]
Thanks for confirming! @norbert-walter would it work if you comment on that issue with the contents of this one? I can re-open the original one then.
