### ISSUE TITLE
Error in loading in firfox

### ISSUE THREAD

**Issue by theja0473** [gitpod-io/gitpod#1665]
### Describe the bug
We are having trouble parsing your context
Error: Couldn't parse context 'https://a7e43659-c174-4acd-9e47-08c39b94b459.ws-us02.gitpod.io/'.

**Comment by corneliusludmann** [comment]
How did you try to open a workspace? The URL `https://a7e43659-c174-4acd-9e47-08c39b94b459.ws-us02.gitpod.io/` is indeed not a valid context.
