### ISSUE TITLE
Please show a User's Organizations in the Admin panel

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#16664]
## Is your feature request related to a problem? Please describe

One customer support use case that comes back frequently is: Which Organizations is this User a Member/Owner of?

## Describe the behaviour you'd like

It would be nice if the Admin panel showed, for any given User, which Organizations they are part of.

## Describe alternatives you've considered

Right now, this information is not visible on User profiles in the Admin panel, and the only way to find out is to go do over-complicated DB spelunking in BigQuery, which is very time consuming.

Or, we need to ask the user, which adds unnecessary back-and-forth (and is also time consuming).

**Comment by gtsiolis** [comment]
From UX perspective this could be another block element and organizations could be listed serially via comma (Org1, Org2, Org3) or with a collapsible dropdown as proposed in https://github.com/gitpod-io/gitpod/pull/8645#discussion_r823098406.


| Collapsed | Expanded |
|-|-|
| <img width="695" alt="providers-collapsed" src="https://user-images.githubusercontent.com/120486/157537513-1c167f21-a3a6-4303-99e0-36aae038d561.png"> | <img width="695" alt="providers-expadned" src="https://user-images.githubusercontent.com/120486/157537397-eae55ff7-bd77-4486-916e-6eb5474bb3ec.png"> |
