### ISSUE TITLE
Gitpod very unresponsive

### ISSUE THREAD

**Issue by snowch** [gitpod-io/gitpod#1668]
### Describe the bug
Very slow to perform any operation.

### Steps to reproduce
Close all workspaces and open my project

### Additional information
workspace id: a78da000-a0e3-4604-a4ab-54824a7b420a

### Example repository
https://github.com/hpe-container-platform-community/hpecp-python-library

**Comment by corneliusludmann** [comment]
Thanks for reporting. I'll have a look.

**Comment by corneliusludmann** [comment]
We had a node pool in EU where a workspace causes a lot of CPU and memory consumption. It should be fixed since around 2 pm CEST.

Please let me know if this issue still exists.
