### ISSUE TITLE
Metrics for aws/aws-cdk Gitpod usage (including forks)

### ISSUE THREAD

**Issue by skinny85** [gitpod-io/gitpod#1669]
Hey all,

similar to #1579, could we get the current numbers for: the amount of users, number of workspaces and total hours spent for Gitpod instances created from [aws/aws-cdk](https://github.com/aws/aws-cdk), including forks?

Thanks in advance for your help!

PS. If it's possible to put some mechanism in place that doesn't force me to bug you guys every moth for these numbers, that would be awesome as well 🙂.

**Comment by skinny85** [comment]
Pinging @jankeromnes , who helped the last time 🙂.

**Comment by corneliusludmann** [comment]
Hi @skinny85,

Since Jan is offline this week I'm happy to help. These are the total numbers (as of 2020-07-29 09:50 CEST):

```
+-------+------------+-------+
| users | workspaces | hours |
+-------+------------+-------+
|   128 |        263 |   346 |
+-------+------------+-------+
```

**Comment by corneliusludmann** [comment]
PS: I'll discuss an automatism with the team. But it will probably not be implemented too soon. Feel free to open an issue next month and ping Jan in this issue.

**Comment by skinny85** [comment]
Thanks @corneliusludmann !
