### ISSUE TITLE
Can a vscode extension test for the theia environment?

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#1673]
https://github.com/eclipse-theia/theia/issues/7608#issuecomment-660053756

I would like to use zigtools/zls-vscode but it uses semantic tokens which are not yet supported in theia. I would like to update the extension so that it does not use this feature when it is installed in theia. Is there a way for the extension to test for theia?

**Comment by akosyakov** [comment]
There are 2 ways:
- you can test against Gitpod, create a vsix of your extension and upload in `Extension` view
- you can test again Theia from sources: https://github.com/eclipse-theia/theia/wiki/Testing-VS-Code-Extensions

For second, you can also open Theia in Gitpod: gitpod.io#https://github.com/eclipse-theia/theia and check out your extension in `plugins` folder and build it there.

**Comment by svenefftinge** [comment]
Closing this because it is answered.
