### ISSUE TITLE
Breach of privacy is taken authorization ,Unauthorizedly,attempted to encroach upon in an computing environment.

### ISSUE THREAD

**Issue by Kkpanda170** [gitpod-io/gitpod#1674]
What they ask you to grant permission which Violet's
Your consent to grant authority like ,read write or look in to it in you absence or presence.
 Let each of them handle their pages on their own.
Taking over authority issues by asking digital authorisation is subject to a forcible persuasion of facts &figure to the user who hardly knows the pros & Con's of assigning  this vital access regulatory consent.
Thanks.

**Comment by svenefftinge** [comment]
Sorry, I'm not sure what you are talking about or whether this comes from an actual person?
Please elaborate.
