### ISSUE TITLE
[ipfs] Investigate duplicate content storage

### ISSUE THREAD

**Issue by WVerlaek** [gitpod-io/gitpod#16740]
Investigate whether we're storing duplicate content in ipfs, and if so, how to prevent it.

## Testing

* Create image build
  * Check content gets pushed to ipfs
* Start workspace from image build
  * Check it uses the content in ipfs
* Retrigger same image build
  * Check for content duplication

**Comment by WVerlaek** [comment]
Observed no duplication of image layers in IPFS, consecutive image builds don't push new content to IPFS.

I did observe that every workspace (even without an image build), produces a small unique image digest (produced here: https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-bob/pkg/builder/builder.go#L94, essentially an empty Dockerfile referencing the base image). This digest gets stored in IPFS, but is only 30-60kB in size. Multiplying this by the total number of workspace starts per week this wouldn't fill up IPFS (couple of GB at most).

My guess is that we're just growing in the number of unique images used across all workspaces. On each new generation, these images will get stored in IPFS as soon as a workspace is started for them. The number of unique images is likely to increase, but I'll try to confirm this.

Discussed an alternative yesterday with @aledbf, and that is to increase the disk size for IPFS (smallest increase is doubling, as you can only add SSDs in pairs of 4, and IPFS currently has 4). This might be a quick win, as I don't see evidence for duplicated data that could help us reduce disk usage. cc @kylos101

**Comment by kylos101** [comment]
@WVerlaek what led to yesterday's failure, was it related to disk space?

**Comment by kylos101** [comment]
@WVerlaek the updated storage does not appear to be usable yet by IPFS with us90 (luckily it will be short lived):
```
k exec -n storage -c ipfs ipfs-78fdm -- ipfs diag sys
{"diskinfo":{"free_space":1485998989312,"fstype":"1481003842","total_space":1485998989312},"
...
```

**Comment by WVerlaek** [comment]
@kylos101 thanks for testing, is the packer image based on this branch https://github.com/gitpod-io/gitpod-packer-gcp-image/tree/kylos101/gen-90? If so it would need a rebase from master to include the IPFS storage change
