### ISSUE TITLE
New team members not showing up

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#16743]
### Bug description

I recently added a new user called "Dylan" into my team. I know that Dylan accepted the invite but its not showing on my list of members. You can [open this image for more details](https://tinyurl.com/2lgnomea).

### Steps to reproduce

1. Login to to gitpod and navigate to https://gitpod.io/members
2. Copy invite link.
3. Share invite link to someone new (His name is Dylan).
4. Dylan paste's the link on his browser and accepts the invite.
5. Dylan can now see the all the team members but I only see myself, I don't see Dylan.

### Expected behavior

Both should see the same list.

**Comment by svenefftinge** [comment]
Thanks for the feedback. We started to cache the team information for one hour, which is probably a little long. 
Did you see Dylan in the list eventually?

**Comment by alesanchezr** [comment]
Hello @svenefftinge its been a long time!
Yes I saw it eventually, will this be taking this much time always? 
We are about to migrate hundreds of members to the new teams and we would need real time info to make sure everyone has access correctly.

**Comment by svenefftinge** [comment]
Hi Alejandro 👋 I believe we can invalidate the cache on reload, which would recreate the previous experience. Does that work for you?
