### ISSUE TITLE
[new workspace page] allow continue with enter

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#16754]
If on the new workspace page, all required information is provided hitting enter should allow proceeding

**Comment by filiptronicek** [comment]
q: Would it be enough to put [`autoFocus`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) on the <kbd>New Workspace</kbd> button or do we want to make the <kbd>Enter</kbd> behavior possible across the whole page?
