### ISSUE TITLE
Usage metrics for personal use

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#1676]
Hi,

it would be great if there were some sort of usage history for each gitpod workspaces, e.g., 
* Workspace 1
   * 01.01.2020 09:00 - 12:00
   * 02.01.2020 09:00 - 17:00
   * ...
* Workspace 2
* ...

This would be great for timetracking, especailly when u open a workspace per issue/merge request as we do.

WDYT?

Kind regards,
Thomas

**Comment by svenefftinge** [comment]
Yes, makes absolute sense.
