### ISSUE TITLE
Migrate Checkbox components to the new CheckboxInputField component

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16768]
### Problem to solve

In https://github.com/gitpod-io/gitpod/pull/16545, a new `CheckboxInputField` component was introduced.

Before that, we had a basic `CheckBox` component that can now be replaced.

### Proposal

To help avoid technical debt or inconsistent usage, we could migrate all checkbox input to the new component and delete the previous iteration.

See also https://github.com/gitpod-io/gitpod/issues/16511#issuecomment-1461835209. Cc @Devansu-Yadav

**Comment by PatriciaHeimfarth** [comment]
Can I work on that issue?

**Comment by gtsiolis** [comment]
Thanks, everyone! @PatriciaHeimfarth the link that @Devansu-Yadav [shared above](https://github.com/gitpod-io/gitpod/issues/16768#issuecomment-1463425147) is correct!

You can still contribute to any open issue that has no assignee or a linked PR in the issue. I generally avoid assigning anyone outside the team to avoid blocking community contributions to stale issues that never get a PR which is very common across open source projects. I'll opportunistically assign this to @Devansu-Yadav because of the previous work mentioned in the issue description. 🏓

**Comment by gtsiolis** [comment]
Closing this as it has been resolved in https://github.com/gitpod-io/gitpod/pull/17171.
