### ISSUE TITLE
Replace the workspace class cards with the new dropdown component used in the start with options new workspace modal

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16775]
### Problem to solve

Following the proposal in https://github.com/gitpod-io/gitpod/issues/13116, the workspace classes list under project settings is getting longer in _Dedicated_ instances and are breaking the container limits.

See [relevant ](https://gitpod.slack.com/archives/C04Q88AHKQQ/p1677615322051089)discussion (internal).

| Breaking container width |
|-|
| <img width="1440" alt="container" src="https://user-images.githubusercontent.com/120486/224068667-b8a40ea8-1e02-4b97-a531-e8093d11cb5c.png"> |

### Proposal

| BEFORE | AFTER |
|-|-|
| <img width="1076" alt="class-before" src="https://user-images.githubusercontent.com/120486/224068392-ff733661-232b-4e8b-bc5c-205794f5b338.png"> | <img width="1076" alt="class-after" src="https://user-images.githubusercontent.com/120486/224068401-202b3d30-0eea-470c-a762-2af857e4741e.png"> |

**Comment by PatriciaHeimfarth** [comment]
Can I work on that? :)

**Comment by gtsiolis** [comment]
Closing this in favor of the new internal issue in WEB-126. Cc @svenefftinge 

@PatriciaHeimfarth Let us know if you are actively working on this.
