### ISSUE TITLE
Billing cycle renewals are intermittently failing

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#16782]
We have observed in the Gitpod org, and then found out in other orgs too, that the billing period shown in the Billing page still references Feb 1 to March 1 even though today is March 9. 

Did the Billing cycle never renew at all? There's an invoice for March 1st ([here](https://dashboard.stripe.com/invoices/in_1MgdNbAyBDPbWrha5VpcNTcz)).

See https://gitpod.slack.com/archives/D0261QXM4JD/p1678381419714239

**Comment by codemzy** [comment]
I've got the same issue and the billing cycle credits and period haven't renewed (credits are still depleting from previous period April 10 - May 10)

**Comment by codemzy** [comment]
This has been fixed 🤩

**Comment by gtsiolis** [comment]
Thanks for confirming, @codemzy! 🍊
