### ISSUE TITLE
[new workspace page] allow switching orgs

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#16781]
- [x] When switching orgs the details of the form are lost. 
 - [x] Additionally, when the org selected doesn't have sufficient funds, it's not possible to dismiss the warning and switch the org.

**Comment by svenefftinge** [comment]
Switching orgs is actually not so straight-forward, as we would need to keep the state from the create workspace page (context URL, etc.) but state is now kept per org, so switching it moves you into a different state scope.
It bit about
> when the org selected doesn't have sufficient funds, it's not possible to dismiss the warning and switch the org.

Was fixed in https://github.com/gitpod-io/gitpod/pull/16789
