### ISSUE TITLE
Add a full-page loading indicator for the dashboard

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16803]
### Problem to solve

Loading the dashboard sometimes can take longer than usual.

This also affect staging.

See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1678446520801539?thread_ts=1678442513.181549&cid=C02EN94AEPL) (internal). Cc @AlexTugarev @svenefftinge 

### Proposal

Some thoughts on loading:
- Loading strategies
  - Skeleton loaders
  - Loading indicators
    - Full-page loading (**This issue!**)
    - Inline loading
  - Progressive loading
  - Load more options

For the scope of this issue, we can re-use the [`Loader`](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/Loader.tsx) component for adding a **full-page loading** when the entire page is processing, see designs below.

| Full-page loading |
|-|
| <img width="1440" alt="Frame 1290" src="https://user-images.githubusercontent.com/120486/224318369-368eaa86-4bc1-4bfa-a18b-5cab5f3f775d.png"> |

**Comment by himanshu1221** [comment]
can I give it a try?

**Comment by gtsiolis** [comment]
Cross-posting from a [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1679424647343079?thread_ts=1679421570.839489&cid=C02EN94AEPL) (internal) and https://github.com/gitpod-io/gitpod/pull/16941 which we may need to revert once we have the full-page loading indicator in place.

> @gtsiolis: 
> ❓ For the next iteration, shall we investigate a full-page loading indicator? See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1678452543551539?thread_ts=1678442513.181549&cid=C02EN94AEPL) and [#16803](https://github.com/gitpod-io/gitpod/issues/16803).
> ❗ The interaction seems a bit jarring as the switch of the org happens after ~3-5 seconds.
> ❗  This also breaks permalinks for projects. For example, you can no longer link directly to **[the gitpod project](https://gitpod.io/projects/gitpod)**.
> ❗  The interaction UX will become more jarring when we split the workspace attribution per org and the workspaces list re-renders, see [#15980](https://github.com/gitpod-io/gitpod/issues/15980).

**Comment by gtsiolis** [comment]
@himanshu1221 Heads-up that @selfcontained started working on this as this became a priority issue. 🏓

**Comment by himanshu1221** [comment]
> @himanshu1221 Heads-up that @selfcontained started working on this as this became a priority issue. 🏓 

No worries
