### ISSUE TITLE
Feedback Issue: Can't switch to new PAYG pricing

### ISSUE THREAD

**Issue by codemzy** [gitpod-io/gitpod#16808]
### Told to switch to the new pricing plans - but can't

I emailed support to ask how to switch to the new PAYG pricing without any downtime. They advised that I cancel my current plan manually. So far it hasn't gone well 😢 

There was no way to cancel my current plan in account settings (nothing even telling me what plan I am on or how to cancel). I guessed the url was `https://gitpod.io/user/plans` and typed that in and finally could see my plan. So I cancelled it - as advised by support.

Now I've cancelled, I still can't see any billing page or info in the account, so no way of upgrading to the new PAYG pricing. 

Can someone please help me?

**Comment by codemzy** [comment]
I managed to upgrade by guessing the URL (again 😆 ) `https://gitpod.io/user/billing` and typing it in the browser. There's no billing menu item in my account so I think this might be a bug. Leaving this issue open so you can look into it and hopefully resolve so that I can navigate to the billing area from my account in future.

**Comment by codemzy** [comment]
The billing tab is showing now, maybe it was a delay! I'll leave this issue open just so you know about the problem in the UI with not being able to cancel the old plan without typing in the URL. But just wanted to let you know that everything is looking good in my account now 👍

**Comment by svenefftinge** [comment]
> The billing tab is showing now, maybe it was a delay!

It was a regression that we introduced and fixed last week. Sorry for the trouble.
