### ISSUE TITLE
Epic: Improve Desktop IDE onboarding flow

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#16838]
Description TBD. 

**Related:** 
- https://github.com/gitpod-io/gitpod/issues/11370
- https://github.com/gitpod-io/gitpod/issues/9975
- https://github.com/gitpod-io/gitpod/issues/15920

**Comment by loujaybee** [comment]
@loujaybee to add more description updates and speak to @gtsiolis about designs.

**Comment by akosyakov** [comment]
https://github.com/gitpod-io/gitpod/issues/11370 is not relevant for VS Code Desktop if https://github.com/gitpod-io/gitpod/issues/16836 successful, only for general SSH
