### ISSUE TITLE
Show only stable or latest editor options from the new workspace modal

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16831]
### Problem to solve

The recently updated new workspace modal includes a list of all available editor options, including the latest versions—that is Insiders for VS Code and EAP for JetBrains.

However, this modal is not necessarily targeting power users who would need the option to use the latest editor in this modal. This leads to a more confusing and verbose UI/UX.

The option still remains available at reach inside user settings for any power user who wants to get the latest updates for the editor options.

See [relevant discussion](https://gitpod.slack.com/archives/C01KPEPNBD0/p1678135856665879) (internal). Cc @loujaybee @filiptronicek @akosyakov @mbrevoort

See [relevant discussion point](https://www.notion.so/gitpod/IDE-Design-Check-in-5d79b220d8a348fb9ed19cbae7c23afe?pvs=4#24e8fbb54ffd4662b58a3ca67038a79c) (internal) from a recent design check-in. 🍳 

### Proposal

Remove the latest editor options from the **new workspace** modal.

**Comment by gtsiolis** [comment]
@akosyakov I'll make an (expensive) assumption here that users overriding the editor don't necessarily need to switch between the latest or not.

☝️ Collecting some metrics around this could shed some light on this. Re-posting [relevant discussion point](https://www.notion.so/gitpod/IDE-Design-Check-in-5d79b220d8a348fb9ed19cbae7c23afe?pvs=4#24e8fbb54ffd4662b58a3ca67038a79c) (internal) from a recent design check-in. 🍳

---

If this sound acceptable, I'd keep the latest checkbox as opt-in only in user settings and only allow control from there. 

This way, changing the editor on the new workspace modal will respect the option of the latest or not, but :a: not list explicitly all options in the new workspace modal and :b: defaulting and surfacing to stable or latest based on the user setting. Does this sound ok?

**Comment by akosyakov** [comment]
Yes, I agree to list only one option based on user setting. The question was about naming. We could keep showing latest label indeed. I still think that using proper product names is better. I don’t think someone knows what is VS Code desktop latest.

**Comment by gtsiolis** [comment]
> Yes, I agree to list only one option based on user setting.

DEAL—🤝 

> The question was about naming. We could keep showing latest label indeed.

DEAL—🤝 

> I still think that using proper product names is better. I don’t think someone knows what is VS Code desktop latest.

DEAL—Once the user opt-in to using the latest using the checkbox input in user settings, we can then show _Insiders_ or _EAP_ as the label next to the editor in the new workspace modal, see designs below how we could also surface this on the current editor selection cards. 🃏 

Then, once https://github.com/gitpod-io/gitpod/issues/13116 lands, we can simply replace the editor cards with the same exact compact dropdown.

| BEFORE | AFTER |
|-|-|
| <img width="630" alt="editos-before" src="https://user-images.githubusercontent.com/120486/224805263-f999472d-9a17-4803-be95-4e3b198cb658.png"> | <img width="630" alt="editos-after" src="https://user-images.githubusercontent.com/120486/224805236-f1992915-51c4-4318-9f41-4042b3e07b22.png"> |

**Comment by filiptronicek** [comment]
> we can then show Insiders or EAP 

I like this, because around release dates, it does happen that VS Code Browser Stable ==  VS Code Browser Insiders - see [internal thread](https://gitpod.slack.com/archives/C01KPEPNBD0/p1678137248913499?thread_ts=1678135856.665879&cid=C01KPEPNBD0) for an example (I believe the same can happen for JB). With this we can show the version as non-insiders even if `Insiders` is chosen in the user prefs. Related: https://github.com/gitpod-io/gitpod/pull/15251

**Comment by filiptronicek** [comment]
Actually already fixed by https://github.com/gitpod-io/gitpod/pull/16847.
