### ISSUE TITLE
Chromium 32bits issue

### ISSUE THREAD

**Issue by mcartagena** [gitpod-io/gitpod#1685]
### Describe the bug
When I tried to get context there is a error.

### Steps to reproduce

1.- Install the gitpod extension for chrome, I'm using Chromium for i86 (ubuntu 14.04 32bits architecture).
2.- Click on the extension, you get the issue

### Expected behavior
Get the context to start coding (React and javascript)

### Additional information
N/A

### Example repository
N/A

**Comment by AlexTugarev** [comment]
Hi @mcartagena! What's the version of Chromium you are using? Just asking, as `14.04` is pretty old, and there might be some general issues with loading extensions from marketplace, if the stock browser is used.

**Comment by mcartagena** [comment]
Hi Alex, I have decided to move on to xubuntu 18.04 and I will try with Firefox, I'll let you know the result... I have an old machine for now x86 32 bits.

**Comment by mcartagena** [comment]
Hi @AlexTugarev , it works perfectly in firefox 72.0.2 (32-bit) for xubuntu 18.04.1.

Regards.
