### ISSUE TITLE
[ws-manager] inspect observability for startWorkspace when image pull fails

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#16869]
### Bug description

There are [reports](https://gitpod.slack.com/archives/C047WL9JBLG/p1678778928866779) from Gitpodders that the dev-09 cell has had some image pull failures on workspace start.

### Steps to reproduce

Unsure

### Workspace affected

Refer to report above

### Expected behavior

When `ws-manager` cannot start a workspace due to a failed image pull:
1. it must log the error (we see this working in gitpod.io for some scenarios, [example](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-03-15T17:17:19.569255034Z;query=severity%3DERROR%0AjsonPayload.serviceContext.service%3D%2528%22ws-manager%22%2529%0Aresource.labels.cluster_name%20:%20%2528%22us90%22%2529%0A-%22headless%22%0Atimestamp%3D%222023-03-15T14:55:18.040221784Z%22%0AinsertId%3D%228xzuv2d2nbba3e0b%22;summaryFields=:false:32:beginning;timeRange=P7D?project=workspace-clusters)), but does it work for all scenarios? Some :bulb: scenarios are below.
2. the `gitpod_ws_manager_workspace_starts_failure_total` and `gitpod_ws_manager_workspace_starts_total` metrics must increment
3. the related trace for failed `startWorkspace` must contain an `error=true` tag, as well as the reason why startWorkspace failed.

### Anything else?

To start, run a few tests in a preview environment (harvester or workspace-preview) to assert the behavior for logs, metrics, and errors when startWorkspace fails during image pull.

Scenario 1: due to restarting `registry-facade` during workspace start, as image pull is happening.
Scenario 2: due to shutting the containerd service off, as image pull is happening
Scenario 3: due to restarting the containerd service, as image pull is happening

What other scenarios make sense to explore related image pull failure modes? Can we recreate the issue with loadgen?

[This](https://gitpod.slack.com/archives/C047WL9JBLG/p1678886632024339) details how to get a kubecontext for a cell.

**Comment by kylos101** [comment]
@nandajavarma can you share a link to a loadgen config that you use for load testing in Gitpod Dedicated cells? :pray:

**Comment by nandajavarma** [comment]
@kylos101 Here is a gist of the one I used to test dedicated https://gist.github.com/nandajavarma/732c4103babd51885863fbdd65faeba3

**Comment by kylos101** [comment]
> The recent PR by @Furisto should fix this: https://github.com/gitpod-io/gitpod/pull/16738 by gracefully falling back to another blob source. @nandajavarma do you know if that PR has already been deployed to dedicated?

@WVerlaek Dedicated does not use IPFS. Which failure mode were you thinking this could help with in Dedicated?

> I wasn't able to reproduce this exact error in the three scenarios

@WVerlaek Perhaps you could try to reproduce the problem by running loadgen against `dev-09`? I ask because I suppose it is possible when `connection refused` happens, perhaps our metric for ms-manager start failures doesn't increment, but does for other scenarios?

cc: @aledbf is there anything else that you might recommend for @WVerlaek to peek at when trying to recreate `connection refused`?

**Comment by kylos101** [comment]
👋  @WVerlaek closing this issue, as I think @geropl cracked the code on metric behavior in this thread: https://gitpod.slack.com/archives/C047WL9JBLG/p1679043443185369?thread_ts=1679043320.020209&cid=C047WL9JBLG
