### ISSUE TITLE
Captcha oops

### ISSUE THREAD

**Issue by sguyrep** [gitpod-io/gitpod#1686]
### Describe the bug
<!-Captcha was not displayed after a wait of several minutes I simply left it with my initial response of having checked I am not a robot while the timeout indicator continued to spin ->

### Steps to reproduce
complete the signup ignoring the never ending wait for the unresponsive captcha

### Expected behavior
Either the captcha interaction should have accepted my representation that I am not a robot, or it should have presented a test and accepted my very human response.

**Comment by svenefftinge** [comment]
Where exactly did you see that captcha? We don't use captchas in our registration process.
