### ISSUE TITLE
Error loading webview: Error: Could not register service workers: TypeError: Failed to register a ServiceWorker for scope

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#16885]
### Bug description

Preview not working

### Steps to reproduce

https://gitpod.io/#https://github.com/cpojer/vite-ts-react-tailwind-template

```
Error loading webview: Error: Could not register service workers: TypeError: Failed to register a ServiceWorker for scope ('https://063331ropgks4dojiro00c9212urfm6p56dhc7csiuob3mu66ucv.ws-us90.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-37273e54bbbaa4e83882b56a355706b7b903fec9/__files__/out/vs/workbench/contrib/webview/browser/pre/') with script ('https://063331ropgks4dojiro00c9212urfm6p56dhc7csiuob3mu66ucv.ws-us90.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-37273e54bbbaa4e83882b56a355706b7b903fec9/__files__/out/vs/workbench/contrib/webview/browser/pre/service-worker.js?v=4&vscode-resource-base-authority=vscode-resource.gitpod.io&remoteAuthority=cpojer-vitetsreacttailw-3bumg9vzdge.ws-us90.gitpod.io'): An unknown error occurred when fetching the script..
```

**Comment by gengjiawen** [comment]
@jankeromnes Can you help on this one, this impact fe devs productivity deeply.

**Comment by gengjiawen** [comment]
@akosyakov

**Comment by akosyakov** [comment]
@gengjiawen Which browser? FireFox? Could you try to upgrade to latest? Try Chrome?

**Comment by gengjiawen** [comment]
> @gengjiawen Which browser? FireFox? Could you try to upgrade to latest? Try Chrome?

Chrome: 112.0.5615.137

**Comment by akosyakov** [comment]
It is weird. I have the same version of Chrome and tried with both latest and stable VS Code Browser, but cannot reproduce.

**Comment by akosyakov** [comment]
@gengjiawen Did you try to disable caches in network tab and start a new workspace?

**Comment by gengjiawen** [comment]
> @gengjiawen Did you try to disable caches in network tab and start a new workspace?

disable cache not helps (two macs, same behavior). I tried safari, it works.

**Comment by akosyakov** [comment]
@gengjiawen Could you share latest errors from chrome please?

**Comment by filiptronicek** [comment]
@gengjiawen maybe it could be browser extension-related? Could you try running Chrome with `--disable-extensions`? 🙏

**Comment by gengjiawen** [comment]
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-extensions
```
not working on macOS, but I installed a canary version without extensions. It works.

It's truly caused by extensions.

**Comment by gengjiawen** [comment]
But I have not find the extensions. I reset my chrome cache. It works now. Thx for all.

**Comment by filiptronicek** [comment]
if you find out what extension might have caused this, please let us know, I'd love to add it to our [Troubleshooting docs](https://www.gitpod.io/docs/help/troubleshooting).

**Comment by gengjiawen** [comment]
The most suspicious is https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
but it doesn't block any element on gitpod.io. Can you try repro on your side.

**Comment by gengjiawen** [comment]
The root cause is this external rules.

<img width="639" alt="CleanShot 2023-04-26 at 15 45 53@2x" src="https://user-images.githubusercontent.com/3759816/234506029-fbdf2e82-dfb7-4364-a110-2ef2b9b77d69.png">

**Comment by filiptronicek** [comment]
With the ad list I can reproduce
