### ISSUE TITLE
Technical investigation for feature flags

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#16906]
Time-boxed to the end of week 32.

[[Internal doc](https://www.notion.so/gitpod/Feature-flags-for-Dedicated-04fd55def7be498c9f808a2271475ed2)]
[[Internal Substrate talk](https://drive.google.com/file/d/17sPgA-ESgtoJx4N7f-Ba_KLfDoxrFBfA/view)]

**Comment by laushinka** [comment]
@filiptronicek @iQQBot Since this investigation was timeboxed for one week, please write your findings and next steps in this issue or [the epic](https://github.com/gitpod-io/gitpod/issues/16903). Once done, you can close this issue.

**Comment by filiptronicek** [comment]
Our findings and plans are all available [on Notion](https://www.notion.so/gitpod/The-Plan-80495d20247544d5876602aaf999dd97?pvs=4).
