### ISSUE TITLE
Gitpod workspace would not open.

### ISSUE THREAD

**Issue by RhysPollardDevelopment** [gitpod-io/gitpod#1691]
cannot initialize workspace: cannot initialize workspace: cannot initialize workspace: git initializer: git clone https://github.com/RhysPollardDevelopment/UserCentricMilestoneProject.git . failed (exit status 128): Cloning into '.'... fatal: unable to access 'https://github.com/RhysPollardDevelopment/UserCentricMilestoneProject.git/': transfer closed with outstanding read data remaining
Please file an issue if you think this is a bug.

### Steps to reproduce
Just pushed gitpod button on RhysPollardDevelopment/UserCentricMilestoneProject.git repository.

### Expected behavior
Should open the workspace for this repository.

### Example repository
UserCentricMilestoneProject

**Comment by AlexTugarev** [comment]
I'm afraid it fails due to an incident with GitHub services. See https://www.githubstatus.com/

Please try again shortly.

**Comment by AlexTugarev** [comment]
@RhysPollardDevelopment, FYI the status on GitHub is back to green.
