### ISSUE TITLE
[docker] support all workspace classes in Dedicated

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#16914]
### Bug description

It does not work reliably with extra large workspace classes in Dedicated. A workaround is to restart the XLarge workspace, or use Large or Standard workspaces.

https://gitpod.slack.com/archives/C047WL9JBLG/p1678876460037889

### Steps to reproduce

* Start a large workspace in dev-09
* Try `docker run hello-world` many times, or run a leeway build in your workspace

### Expected behavior

Can start workspaces, and avoid this error:
```
runc create failed: unable to start container process: unable to apply cgroup configuration: mkdir /sys/fs/cgroup/docker: permission denied: unknown
```

**Comment by Furisto** [comment]
@kylos101 Tried this with 25 XLarge and XXLarge workspaces and was not able to reproduce it. When I observed it before there was a ~ 50% chance that it would happen. I suggest to close the issue. We can reopen should this happen again.

**Comment by kylos101** [comment]
Closing for now, we can reopen if it continues to be an issue.
