### ISSUE TITLE
Can't open a renamed GitLab project using the old URL

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#1695]
### Describe the bug

Can't open a renamed GitLab project using the old URL. 📦 

### Steps to reproduce

1. Create a GitLab project
1. Change project's path or transfer the project via project settings (`/:namespace/:project/edit`)
    - For example, from `project1` to `project2`
1. Open a Gitpod workspace using the old URL
    - For example, go to `http://gitpod.io/#https://gitlab.com/namespace/project1`

You're then prompted to grant access to the repository which is not accurate since clicking on the CTA button (Grant Access) redirects you to the same page.

### Expected behavior

Open a Gitpod workspace using the new project URL.

### Additional information

This works fine for renamed repositories at GitHub.

This could be due to the `302` redirect used by GitLab in contrast with the `301` redirect used by GitHub for renamed repositories.

**Comment by AlexTugarev** [comment]
@gtsiolis, wow! Thanks a lot the details. I'm looking into it.

**Comment by AlexTugarev** [comment]
@gtsiolis, I can confirm the issue. Unfortunately, in contrast to the web app, where you see the `302` redirect, the API endpoint returns a `404`. 

It looks like a known limitation, cf. https://gitlab.com/gitlab-org/gitlab/-/issues/30013. 

'Not giving up though, maybe there's a way.

**Comment by gtsiolis** [comment]
Thanks for taking a look @AlexTugarev!

I've [pinged](https://gitlab.com/gitlab-org/gitlab/-/issues/30013#note_393867719) the relevant PM and EM in that issue in case this could be prioritized.

I'd say this could be a low priority issue since a) you can always open the renamed project using the new URL and b) it would be best to fix the API endpoint in GitLab instead, unless more users run into this issue.
