### ISSUE TITLE
Branch context using the commit-related URLs is not working

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#1696]
### Describe the bug

The [branch context](https://www.gitpod.io/docs/context-urls/#branch-context) using the commit-related URL is not working for GitLab projects.

### Steps to reproduce

1. Create a branch and push a commit in a GitLab project.
1. Opening a Gitpod workspace with the branch using the `commits/` URL is not working for GitLab projects.
   - For example, go to `/:namespace/:project/-/commit/:commit_sha` or `/:namespace/:project/-/commits/:branch_name` although the second URL could be expected not to work.

### Expected behavior

This should open a Gitpod workspace using the branch context as expected.

### Example repository

1. https://gitpod.io/#https://gitlab.com/gtsiolis/now-vue-example/-/commit/284c14c4ed6ff418a1573aaf718232436ceef6ec
1. https://gitpod.io/#https://gitlab.com/gtsiolis/now-vue-example/-/commits/change-header-text

**Comment by svenefftinge** [comment]
Thanks! Does that mean that 
  https://gitlab.com/gtsiolis/now-vue-example/-/tree/change-header-text
and 
  https://gitlab.com/gtsiolis/now-vue-example/-/commits/change-header-text
can be treated equally?

**Comment by gtsiolis** [comment]
@svenefftinge yes, this is correct. This is also the case for GH URLs. For example: 
1. https://github.com/gitpod-io/spring-petclinic/tree/GH-1
2. https://github.com/gitpod-io/spring-petclinic/commits/GH-1

Also, it seems that the commit-related URLs are not working both for GL and GH as they both default to using the latest commit from the main branch. I've updated the issue title to reflect this. ✍️

**Comment by svenefftinge** [comment]
both work now
