### ISSUE TITLE
Surface missing git integration on the new new workspace flow

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#16977]
### Bug description

Previously, when users tried opening a workspace for a repository from a provider with a missing integration the dashboard showed an error-like page with a single click-to-action (CTA) to authenticate with the missing provider integration, see https://github.com/gitpod-io/gitpod/issues/4696.

Following up the new new workspace flow, which is currently available only the Gitpod team members, users are not able to authenticate for the missing provider integration, see screenshot below.

| BEFORE | CURRENT |
|-|-|
| <img width="1512" alt="Screenshot 2023-03-22 at 19 12 22" src="https://user-images.githubusercontent.com/120486/226984484-c6d9b9d0-83d6-4a60-af14-4f3dbf9265f5.png"> | <img width="1512" alt="Screenshot 2023-03-22 at 19 12 02" src="https://user-images.githubusercontent.com/120486/226984405-ac2821bc-f539-4191-814a-37bfacba4d1d.png"> |

### Steps to reproduce

1. Be part of the feature flag, affects only Gitpod team members.
2. Try opening a workspace for a repository from an unauthorized git provider.

**Comment by svenefftinge** [comment]
@gtsiolis Can you provide UI for how this should be presented to the user in the create workspace flow?

**Comment by gtsiolis** [comment]
@svenefftinge I'm adding below an approach to resolve this with a UX that resembles form inline validation, see [design specs](https://www.figma.com/file/MLJUI2WQ3ZSZvd1dGhrfbu/Start-workspace-with-workspace-class-override-%2315287?node-id=2020%3A3969&t=HxjTkn0sGXlKcsF3-1) (internal). Thoughts?

| Inline validation for missing Git authorization |
|-|
| <img width="1440" alt="missing-auth" src="https://user-images.githubusercontent.com/120486/230880848-4af8b7af-22d0-43f3-9b6d-cb1a8688453d.png"> |
