### ISSUE TITLE
[chrome] "Use Chrome" recommendations appears since updating Chrome

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#170]
I think the browser detection is confused by the latest Chrome.

<img width="1176" alt="screen shot 2018-12-06 at 09 43 18" src="https://user-images.githubusercontent.com/914497/49573477-59855900-f93e-11e8-8166-75725cea2780.png">

**Comment by jbicker** [comment]
Since Version 71... . It used to work in Version 70...

**Comment by AlexTugarev** [comment]
related to https://blog.chromium.org/2018/06/improving-extension-transparency-for.html

**Comment by AlexTugarev** [comment]
resolved.
