### ISSUE TITLE
We are having trouble parsing your context Error: Cannot read property 'sha' of undefined

### ISSUE THREAD

**Issue by Davewalsh3** [gitpod-io/gitpod#1700]
### Describe the bug

Created new workspace from template , launching gitpod from github casued the error On the following loading page
### Expected behavior

gitpod loads up
### Example repository

personal profile page

**Comment by AlexTugarev** [comment]
Hi @Davewalsh3! We've recently discovered an issue which might be causing this. 

Please, can you share more information on your project setup. Especially the `image` property of the `.gitpod.yml` would be of interest to me, as well as if a referenced file really exists.

**Comment by Davewalsh3** [comment]
sorry I have deleted the file
