### ISSUE TITLE
Disable Git Auth on user-level for Dedicated

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#17018]
We should feature-flag "user-level Git auth" (default: false, gitpod.io: true)

**Comment by AlexTugarev** [comment]
It would be nice to ensure we have this feature in place from day one.

**Comment by geropl** [comment]
I think it's handled in this PR already (did not verify/review yet): https://github.com/gitpod-io/gitpod/pull/17007

**Comment by geropl** [comment]
Closed with https://github.com/gitpod-io/gitpod/pull/17007 :heavy_check_mark:
