### ISSUE TITLE
Improve the full-page loading indicator

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#17044]
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/issues/16803 and https://github.com/gitpod-io/gitpod/pull/16984, a full-page loading indicator was added while loading the dashboard.

Although, this significantly improves the dashboard by not showing a blank white page on load, there's room to improve this page and also avoid confusing users. From https://github.com/gitpod-io/gitpod/pull/16984#discussion_r1145890305:

> @gtsiolis: Re-using the bouncing logo could frustrate or confuse users as they usually to see that loading state (bouncing logo) a lot while opening workspaces.

The current state also lacks a loading indication, as the logo remains still, which could confuse users even more as the layout resembles the error page, besides the workspace start page.

| Full-page loading | Error | Start |
|-|-|-|
| <img width="1512" alt="Screenshot 2023-03-27 at 12 55 08" src="https://user-images.githubusercontent.com/120486/227923270-667a5aa0-3036-40a1-b60a-6793d243bd7f.png"> | <img width="1512" alt="Screenshot 2023-03-27 at 12 55 15" src="https://user-images.githubusercontent.com/120486/227923277-dd5155e6-feeb-45c3-ad8b-c61a577e7baa.png"> | <img width="1512" alt="Screenshot 2023-03-27 at 13 01 52" src="https://user-images.githubusercontent.com/120486/227923738-8732b6f2-2144-4f4c-a877-c309efc38fbe.png"> |

### Proposal

Replace the current full-page loading in indicator with the (animated) spinner animation.

| BEFORE | AFTER |
|-|-|
| <img width="1512" alt="Screenshot 2023-03-23 at 11 20 36" src="https://user-images.githubusercontent.com/120486/227158477-9a5388e5-c116-4d03-8310-e0fc6a316caf.png"> | <img width="1440" alt="224318369-368eaa86-4bc1-4bfa-a18b-5cab5f3f775d" src="https://user-images.githubusercontent.com/120486/227158622-b52303fe-3edb-4305-bdb1-400520326c05.png"> |

**Comment by himanshu1221** [comment]
Can I give it a try @gtsiolis?

**Comment by vedant-jain03** [comment]
@himanshu1221 In case you are not working on this issue, please let me know, I would love to work on this!

**Comment by himanshu1221** [comment]
> @himanshu1221 In case you are not working on this issue, please let me know, I would love to work on this!

Yes @vedant-jain03 i am still trying

**Comment by gtsiolis** [comment]
Hey @RayAsh37! Chatted with the team about this internally and decided we're going to keep the current version for now. Thanks for hanging here, let me close this for now. 📕
