### ISSUE TITLE
Unable to Start MYSQL

### ISSUE THREAD

**Issue by flamecopper** [gitpod-io/gitpod#1705]
image: gitpod/workspace-full:latest

tasks:
  - init: npm install
    command: npm run dev

I have include the following to the yml file.
However when I restarted, it still show mysql: command not found,
Please advise.

**Comment by jankeromnes** [comment]
Hi @flamecopper,

As shown in https://www.gitpod.io/blog/gitpodify/#mysql you want to use `gitpod/workspace-mysql`, Gitpod's official MySQL image, instead of simply `gitpod/workspace-full` (note: `-mysql` will give you `-full` with an additional MySQL setup that works in Gitpod).

**Comment by flamecopper** [comment]
Hi Jan,

I have already spawned a new project and create from scratch:

image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

The dockerfile being:
FROM gitpod/workspace-mysql

# Install custom tools, runtimes, etc.
# For example "bastet", a command-line tetris clone:
# RUN brew install bastet
#
# More information: https://www.gitpod.io/docs/config-docker/
 $ mysql -e "show databases;"
bash: mysql: command not found

Have restarted the workspace severaltimes ,still not working

**Comment by flamecopper** [comment]
Nevermind, it is working right now.
After I switch another workspace.
But why.
Btw, why do I have so many workspace spawned after I closed workspace and start them again

**Comment by flamecopper** [comment]
I am trying to run the following command:
mysql> CREATE USER 'xxxx'@'localhost' IDENTIFIED BY 'info_g_lab1';
ERROR 1726 (HY000): Storage engine 'MyISAM' does not support system tables. [mysql.db]
why is that so?

**Comment by corneliusludmann** [comment]
Does this information help? https://stackoverflow.com/questions/54292491/how-to-fix-error-1726-hy000-storage-engine-myisam-does-not-support-system-t

**Comment by flamecopper** [comment]
No the above command not working, abit troublesome. So I created mysql instance from another host.

**Comment by Mosaab-Emam** [comment]
For anyone still facing this problem, restarting the workspace will not work. You will have to delete from workspaces and create it again, then gitpod will build the docker image.
