### ISSUE TITLE
Make Neovim available

### ISSUE THREAD

**Issue by havogt** [gitpod-io/gitpod#1707]
I started using the neovim vscode plugin, however it requires the neovim executable to be installed.

Currently I just install it after launching a workspace, but it's obviously a bit annoying (copy the file, reload the browser).

A pragmatic solution could be to add it to the default gitpod docker images. Other solutions could be to allow user specific commands on init (I think it's currently not possible?). Or adding your own layer on top of the docker image as suggested in #214.

Maybe you see another solution that's already possible? Thanks for your help!

**Comment by corneliusludmann** [comment]
Hi @havogt and thanks for reaching out.

Currently, there is no other way than adding the dependencies to a repo with a `.gitpod.yml` resp. `.gitpod.Dockerfile`. There is no way to run commands on a user level for each of your workspaces. That would be quite helpful, though.

Sorry, that I don't have better news there ...

**Comment by havogt** [comment]
Thanks for your feedback.

**Comment by havogt** [comment]
I'll close, but the comment by @corneliusludmann, sounds still like a useful feature

>There is no way to run commands on a user level for each of your workspaces. That would be quite helpful, though.

**Comment by integrate-your-mind** [comment]
Can we please still get this feature? This is cruelty to NeoVim users and should be a human right that we are allowed to use NeoVim, especially on GitPod.

**Comment by axonasif** [comment]
Hey @havogt @integrate-your-mind @samuelj123 @siawkz @nkoporec @lagoQ, this has been possible for the last few months, check this out to quickly get started with Neovim et' all: https://github.com/axonasif/dotfiles-sh

**Comment by Zebreus** [comment]
If you only need neovim and not all the other stuff provided by `dotfiles-sh` you can also set `https://github.com/Zebreus/install-neovim` as the Dotfiles repo in your [gitpod.io/preferences](https://gitpod.io/preferences).
That repo contains a short script that will fetch and install the latest neovim in the fastest way.
