### ISSUE TITLE
Remove the obsolete checkbox component

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#17103]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/16813 which replaced all the checkbox components with the new form components, a good next step would be to completely remove the obsolete checkbox component.

Obsolete component: [CheckBox](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/CheckBox.tsx) ❌
New component: [CheckboxInputField](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/forms/CheckboxInputField.tsx) ✔️

Cc @Devansu-Yadav because https://github.com/gitpod-io/gitpod/pull/16813#issuecomment-1491444399

**Comment by gtsiolis** [comment]
Note that this is currently blocked until https://github.com/gitpod-io/gitpod/pull/16813 has been merged. ⚠️

**Comment by vedant-jain03** [comment]
@gtsiolis I would like to work on this!

**Comment by Devansu-Yadav** [comment]
> @gtsiolis I would like to work on this!

@vedant-jain03 Thanks for showcasing your interest in working on this issue! 😄 
As this is a follow-up issue for my PR #16813 which I'm already working on, I would suggest you to check out some other good first issues.

**Comment by Devansu-Yadav** [comment]
> Obsolete component: [`CheckboxInputField`](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/forms/CheckboxInputField.tsx) ❌ 
> New component: [`CheckBox`]() ✔️

@gtsiolis Just a small update to the issue description based on the recent changes made in #17171:

> Obsolete component: [`CheckBox`](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/CheckBox.tsx) ❌
> New component: [`CheckboxInputField`](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/forms/CheckboxInputField.tsx) ✔️

**Comment by gtsiolis** [comment]
Oh, nice catch @Devansu-Yadav! Updated the issue description. ⚾
