### ISSUE TITLE
All of sudden I don't have access to any of my workspaces

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#1712]
### Describe the bug

In the morning. On the Dashboard, I saw my recent workspaces as usual but now when I visited `https://gitpod.io` I was automatically logged out and upon login, I'm seeing no workspaces at all.

![image](https://user-images.githubusercontent.com/46004116/90491467-67523080-e159-11ea-9a06-8efeae374440.png)

**Comment by corneliusludmann** [comment]
That looks odd. Sorry for the inconvenience. In the database, I can still see your workspaces. Does the problem still persist, even if you log in and out again?

**Comment by nisarhassan12** [comment]
Sorry. My bad I was accidentally visiting Gitpod Staging and was expecting my production workspaces to be there.
