### ISSUE TITLE
Java input redirection from file not working

### ISSUE THREAD

**Issue by tu5h4r** [gitpod-io/gitpod#1713]
### Describe the bug
Java debugger is not taking _args_ parameter for redirecting input correctly
### Steps to reproduce

Add `"args": ["<","Input.txt"] ` to launch.json configurations. 
In the code add something like `Scanner scan = new Scanner(System.in)`  that should consume data from Input.txt and print the data
### Expected behavior
Data gets printed

### Observed behavior
Control is paused for user input as the redirection operator doesn’t work properly

### Additional information
The _Run_ command adds single quotes to _<_ operator that stops it being treated as the redirect operator. As soon as this is manually removed from terminal, the redirection works

**Comment by AlexTugarev** [comment]
Hi @tu5h4r!

`args` in launch configurations only specify command line arguments to the application, thus any escaping is expected. 

If your (CLI) app needs input from a terminal, try switching to `"console": "integratedTerminal"`, cf. https://code.visualstudio.com/docs/java/java-debugging#_debug-session-inputs.

**Comment by geropl** [comment]
Hm that really looks like a bug. I think it's worth to create a ticket in Theia with the details you provided above: https://github.com/eclipse-theia/theia

**Comment by akosyakov** [comment]
You can switch to VS Code now: https://www.gitpod.io/docs/feature-preview/#default-ide It is going to become default rather soon.
