### ISSUE TITLE
Restarting an old workspace can attribute usage to an org that you've already left

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#17144]
### Bug description

Restarting an old workspace can attribute usage to an org that you've already left.

- [Screencast](https://www.loom.com/share/862025d9ec7d47f48c217043b42e62c3) (internal)
- [Linear issue](https://linear.app/gitpod/issue/WEB-84/leaving-a-team-and-restarting-a-workspace-attributes-to-team-you-just) (internal)

### Steps to reproduce

1. Be part of an Org
2. Start a Workspace that's attributed to that Org
3. Leave the Org
4. Restart the previously-attributed Workspace -- the newer instances still get attributed to the Org that you're no longer a member of :warning: :bug:

**Comment by svenefftinge** [comment]
The solution to this will be a workspaces list that is filtered by org. So when you left an org you have no longer access to the workspaces you created within that org.

**Comment by ubshreenath** [comment]
@svenefftinge If I may suggest, the ideal expectation would be to attribute the workspace usage to the individual's personal billing account for any usage session that starts after they have been removed from the org. This allows them to continue to use the workspaces if they were intending to work on it.

**Comment by svenefftinge** [comment]
@ubshreenath workspaces are going to belong to the org they have been created in. So when you leave an org, you'll have no access to the workspaces anymore.
