### ISSUE TITLE
Error: Parsing 'Getting-Started'

### ISSUE THREAD

**Issue by J-Vin** [gitpod-io/gitpod#1714]
### Describe the bug
 Error: Couldn't parse context 'get-started'.

### Steps to reproduce
 Possibly different for me as it usually is, but I simply attempted to access https://gitpod.io/#get-started

### Expected behavior
 I *expected* to #get-started.

**Comment by J-Vin** [comment]
"We are having trouble parsing your context
Error: Couldn't parse context 'get-started'."
"Please file an issue if you think this is a bug."

**Comment by AlexTugarev** [comment]
Hi @J-Vin! 

How did you end up at https://gitpod.io/#get-started ? 

For the website you simply need to navigate here: https://www.gitpod.io
To start a workspace for a repository, [just prefix the repo url](https://www.gitpod.io/docs/getting-started/) with `gitpod.io/#`

**Comment by JesterOrNot** [comment]
I think they are trying to reference the `Getting started` header on the `www.gitpod.io` site

**Comment by J-Vin** [comment]
Well, I got past #getstarted. Now I receive error and a request for code
https://a839778b-7775-4d1b-8d0a-9df429b9ed03.ws-us02.gitpod.io/#/workspace/self-hosted
