### ISSUE TITLE
gitpod.io/user/variables : add a filter on the variable name or the repository

### ISSUE THREAD

**Issue by jeanphi-baconnais** [gitpod-io/gitpod#17158]
## Add a filter on gitpod.io/variables
On my variables pages, I have a lot of variables and I asked me if this could be great to have the possibility to filter on the variable name or the git repository.

**Comment by jeanphibaconnais** [comment]
Hello @RayAsh37 , yes it's a search bar, the same as the workspaces spaces (I think because I have not actives workspaces)

**Comment by RayAsh37** [comment]
Great! Thanks for the confirmation. I am already on it.

**Comment by jeanphibaconnais** [comment]
Great, thank you ! 
Don't hesitate to ping me if I can help you

**Comment by RayAsh37** [comment]
hey, @jeanphibaconnais I have opened a PR. I have tried to adhere to the coding standards but this is my first time with this significant contribution so go easy on me 😅

Also, can I test my branch locally or any other way? just asking as it will be a bit easier for me to debug, it will help for future contributions too.

any feedback is welcome 😄

**Comment by jeanphibaconnais** [comment]
Hello @RayAsh37 , nice ! Thanks for this PR and your speed ! 
I didn't contribute to the Gitpod website, I don't know how test your branch I'm sorry. Are you on the discord server ? You can find some help 😁
