### ISSUE TITLE
Each time GitPod loads the logo is red and the message states that work space is not found.

### ISSUE THREAD

**Issue by kseniyakaz** [gitpod-io/gitpod#1715]

**Comment by geropl** [comment]
Hi  @kseniyakaz ,

please provide more information:
 - Which URL are you trying to open?
 - You can review the list of your workspace on https://gitpod.io/workspaces
 - You can always create a new, fresh workspace with opening https://gitpod.io/#https://github.com/kseniyakaz/my-first-repo for example
