### ISSUE TITLE
Project URL conflict when two projects are called exactly the same inside an org

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#17179]
### Bug description

When you have two projects called exactly the same inside an organization, their Project URLs end up being identical, preventing you from managing one of the two projects. 🐛 

### Steps to reproduce

1. Have an Org
2. Add two repositories with the same name but different clone URLs (e.g. `my-org/dotfiles` and `user/dotfiles`) as Projects in the same Org
3. Verify that the two Project URLs are different

### Expected behavior

The second Project should have a different URL than the first Project.

The second Project's URL could e.g. contain an org-unique slug (e.g. `dotfiles-2`) or Project URLs could contain the unique Project ID instead of a slug.

**Comment by vedant-jain03** [comment]
@jankeromnes I would like to work on this issue!

**Comment by jankeromnes** [comment]
@vedant-jain03 hey, that's awesome! Many thanks for offering.

Please create a pull request, and ping me in it so that I can help you test it.

Also, please let me know if you'd like any pointers into the code.

**Comment by vedant-jain03** [comment]
> @vedant-jain03 hey, that's awesome! Many thanks for offering.
> 
> Please create a pull request, and ping me in it so that I can help you test it.
> 
> Also, please let me know if you'd like any pointers into the code.

Sure @jankeromnes!

**Comment by vedant-jain03** [comment]
@jankeromnes can we do the slug something like this: `/dotfile-${uuid()}`, WDYT?

**Comment by jankeromnes** [comment]
@vedant-jain03 That would work! But, don't you think that Project URLs would become very long? 👀

**Comment by vedant-jain03** [comment]
> @vedant-jain03 That would work! But, don't you think that Project URLs would become very long? 👀

Yes, agree on that!
So then going with using project id as url would be good, WDYT @jankeromnes ?

**Comment by jankeromnes** [comment]
@vedant-jain03 As you prefer 😁 although personally, I'd go with the project name as before, except in the cases where there are collisions -- then I'd increment a suffix until I find a unique slug for this org.

E.g.:
- Adding project `my-org/dotfiles` uses slug `/dotfiles`
- Then, adding project `user/dotfiles` would cause a collision, so it would use slug `/dotfiles-2` instead
- If we add another project called `dotfiles` in the same org, it would get the slug `/dotfiles-3`, etc

But this is really a matter of personal taste. If you're the one implementing a fix, I think you get to choose which solution you prefer. 👍

**Comment by vedant-jain03** [comment]
> @vedant-jain03 As you prefer 😁 although personally, I'd go with the project name as before, except in the cases where there are collisions -- then I'd increment a suffix until I find a unique slug for this org.
> 
> E.g.:
> 
> * Adding project `my-org/dotfiles` uses slug `/dotfiles`
> * Then, adding project `user/dotfiles` would cause a collision, so it would use slug `/dotfiles-2` instead
> * If we add another project called `dotfiles` in the same org, it would get the slug `/dotfiles-3`, etc
> 
> But this is really a matter of personal taste. If you're the one implementing a fix, I think you get to choose which solution you prefer. 👍

Sure, thanks for the references!

**Comment by vedant-jain03** [comment]
> @vedant-jain03 As you prefer 😁 although personally, I'd go with the project name as before, except in the cases where there are collisions -- then I'd increment a suffix until I find a unique slug for this org.
> 
> E.g.:
> 
> * Adding project `my-org/dotfiles` uses slug `/dotfiles`
> * Then, adding project `user/dotfiles` would cause a collision, so it would use slug `/dotfiles-2` instead
> * If we add another project called `dotfiles` in the same org, it would get the slug `/dotfiles-3`, etc
> 
> But this is really a matter of personal taste. If you're the one implementing a fix, I think you get to choose which solution you prefer. 👍

Hey @jankeromnes , I am having some issues while starting the dashboard in gitpod. I have added the ENV variables:

```
GP_DEV_HOST=gitpod.io
GP_DEV_COOKIE=_gitpod_io_v2_=<-token->
```

But when I try to sign-in, it redirect to `gitpod.io` not in my instance of gitpod?

**Comment by svenefftinge** [comment]
@atduarte WDYT how the slugs should be made unique?

**Comment by atduarte** [comment]
@svenefftinge Thanks for the ping! Would also like to hear your thoughts too

**Ideal world**

I bias towards identifying repositories by their fully qualified name (e.g. `gitpod-io/ops` instead of `ops`). For two main reasons: it's common to have multiple repositories with the same name (e.g. `config`), and it's the identifier used by GitHub/GitLab. Given that, I think project names and slugs should include the org/group. _cc @gtsiolis as we have recently talked about this_

That doesn't prevent the existence of collisions, but significantly reduces their probability. In the rare chance that still happens, I would say adding a counter to the end as suggested by @jankeromnes sounds good.

**Pragmatic version**

I understand that now changing the project names to include the github/gitlab org/group would considerably increase the work needed, and even require some design work. So I would argue we can start with the simpler solution to mitigate slug collision as Jan proposed.

**Comment by svenefftinge** [comment]
I think we should generally allow using the project ID instead of the project name as a slug and fall back to using the ID whenever there is ambiguity. To make the URL more readable we could append the projectname similar to how notion does.

**Comment by gtsiolis** [comment]
Cross-posting from a [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1625064176314500?thread_ts=1625063886.313200&cid=C021Q4BL8E8) (internal) which I still think could be relevant:

> Would it be worth it to reconsider generating team and project URLs with a random hash suffix or prefix attached?
> Like:
> [gitpod.io/team-o9yti4go/project-1bik3oxv/](http://gitpod.io/team-o9yti4go/project-1bik3oxv/)
> or
> [gitpod.io/team/o9yti4go/team/](http://gitpod.io/team/o9yti4go/team/) +
> [gitpod.io/project/1bik3oxv/project/](http://gitpod.io/project/1bik3oxv/project/)

In the current case, adding a suffix to the project URL with parts of the project ID as @svenefftinge mentioned above sounds great from UX perspective.

For example, the `gitpod` project could have a URL like `https://gitpod.io/projects/gitpod-ef9d3f23`

**Comment by gtsiolis** [comment]
Resolved in https://github.com/gitpod-io/gitpod/pull/18618. Thanks, @svenefftinge. 🌮
