### ISSUE TITLE
Partially missing icons in gitpod workspace

### ISSUE THREAD

**Issue by ellen008** [gitpod-io/gitpod#17173]
### Bug description

upon launching workspace from branch most icons in left-side menu are missing. 
![image](https://user-images.githubusercontent.com/44596756/231346484-eed15172-55de-4841-a696-8b7b0acab905.png)

![image](https://user-images.githubusercontent.com/44596756/231346936-597cce76-9fb4-4aee-853f-3b22efc55265.png)
![image](https://user-images.githubusercontent.com/44596756/231347212-8f0c49ee-76fd-4893-965e-902d346b6dde.png)
![image](https://user-images.githubusercontent.com/44596756/231347359-96bee192-280c-4f61-9b15-9a7541cc2ddb.png)
![image](https://user-images.githubusercontent.com/44596756/231347417-1ed90540-2cb6-4d54-a43b-439e5e67df77.png)

### Steps to reproduce

hit gitpod button in Github repo

### Workspace affected

all workspaces are affected

### Expected behavior

I'd expect to see icons and other graphic command elements instead of empty boxes

### Example repository

https://gitpod.io/#snapshot/c656ac70-112f-4c41-9f9c-4751e3a4c16a

**Comment by axonasif** [comment]
Hi @ellen008, which browser are you using? It could be a _network issue_ or some browser settings/extension is causing this. Additionally, you could take a look into your console logs and share with us.

You could also use vscode desktop instead of the browser version:
- https://www.gitpod.io/docs/references/ides-and-editors/vscode

**Comment by ellen008** [comment]
Hi @axonasif 
I'm using 2 browsers: M Edge and Chrome.
I'm not sure what browser setting/extension could cause this behavior. I have a history of using Gitpod smoothly.
I didn't change the .gitpod.yml settings, I'm building on a branch that had no issues before, however the issue persists.

I'm not sure about which console logs you're talking about. The icons are rendered at gitpod container build before my app launches, thus no logs in terminal.

I'm working on Windows machine, so what exactly does the option "open in VS" do? 
Am I still developing inside UNIX container ?

Thank you.

**Comment by axonasif** [comment]
What happens if you reload the page and wait for a few seconds?
