### ISSUE TITLE
Gitpod server CORS issues

### ISSUE THREAD

**Issue by 201flaviosilva** [gitpod-io/gitpod#17191]
### Bug description

I'm developing this application in react: https://bitbucket.org/flavio-silva-mindera/gitpod-cors-errors/
I'm using a mock server ([json-server](https://www.npmjs.com/package/json-server)) for the BE, but the problem is that whenever I make a request I get CORS errors:

```
acess to fetch at 'https://3001-201flaviosi-reactjsonse-kio59mbtdvc.ws-eu93.gitpod.io/products' from origin 'https://3000-201flaviosi-reactjsonse-kio59mbtdvc.ws-eu93.gitpod.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### Steps to reproduce

- Open the repository in a Gitpod environment;
- Open the console and the error will appear;

### Workspace affected

flaviosilva-gitpodcorse-omdmooo0hg8

### Expected behavior

Being able to make requests to a server running in a Gitpod environment

### Example repository

https://bitbucket.org/flavio-silva-mindera/gitpod-cors-errors/

### Anything else?

Sorry if this is a really stupid mistake, and I'm doing something wrong 😅

**Comment by Manthan1313Github** [comment]
Hi @201flaviosilva,
![image](https://user-images.githubusercontent.com/20395595/232468195-32205992-d4cf-44ab-b518-c90fa1c59902.png)
 try with noCors property to true. If this doesn't work, try installing CORS package.

**Comment by 201flaviosilva** [comment]
Hey, @Manthan1313Github, I tried with these two options, but it still didn't work 😅

**Comment by Manthan1313Github** [comment]
@201flaviosilva,

https://3001-flaviosilva-gitpodcorse-neel7hm3hvs.ws-us94.gitpod.io/products This URL works when we log in to the Gitpod. You can check opening this URL in incognito mode, it will give you the 401 response. I cloned your project and tried to run it, gave the same 401 response. I tried URL in postman, it was also giving 401, but after I tried cookie value from browser with signed-in, it gave 200 response. I think you need will need to add cred with fetch request. Let me know if it works.

![image](https://user-images.githubusercontent.com/20395595/232771542-5243f14a-33c9-4dc3-afcc-c111adc19879.png)

**Comment by 201flaviosilva** [comment]
Ye, the project works in my local machine, but in the gitpod machine no :)

**Comment by axonasif** [comment]
You can try to make the port public:
- https://www.gitpod.io/docs/configure/workspaces/ports#configure-port-visibility

We have some info about CORS on our docs:
- https://www.gitpod.io/docs/configure/workspaces/ports#cross-origin-resource-sharing-cors

You might be also interested in port-forwarding:
- https://www.gitpod.io/docs/configure/workspaces/ports#port-forwarding

**Comment by 201flaviosilva** [comment]
Nice, that fixed the problem, thanks 😁

**Comment by fynnfluegge** [comment]
Hey @201flaviosilva how did you fix this? I have a similar issues with Angular and lambda functions started with `sam local`. On my device everything's running fine, but in my gitpod workspace I get 
```
CORS Error: Redirect is not allowed for a preflight request.
```
I already enabled `Access-Control-Allow-Credentials` in request and response, but it has no effect, seems like I am missing something 🤔
