### ISSUE TITLE
Tests either unavailable OR available and not running

### ISSUE THREAD

**Issue by sameergarach** [gitpod-io/gitpod#17190]
### Bug description

As a trainee at Revature, we are required to use Gitpod for coding labs and challenges to test our knowledge of the material and practice coding. However, the tests are either unavailable OR available and not running. Therefore, the tests don't run and I can't commit my code to github and mark my work as complete. I am not sure what the issue what gitpod is because previously I could run tests and commit my code. Now I cannot. This is affecting several workspaces.

### Steps to reproduce

Simply attempt to run tests created by Revature.

### Workspace affected

sameergarach-OtherStringMethods

### Expected behavior

I should be able see the tests, run them, and commit my code.

### Anything else?

![Capture](https://user-images.githubusercontent.com/103470536/231537252-c5d3a238-af61-48f8-a00b-7b6a9e4b3cd1.PNG)

**Comment by axonasif** [comment]
Hi @sameergarach, can you also try in vscode desktop?
- https://www.gitpod.io/docs/references/ides-and-editors/vscode

It would be great if you could share a public Git repository, that would allow us to reliably reproduce your issue.

**Comment by sameergarach** [comment]
The issue is resolved. I had many unnecessary extensions installed. Once I
removed or disabled them, things worked fine.

Best,
