### ISSUE TITLE
Copy & Paste Doesn’t work when running from Chrome on iPadOS

### ISSUE THREAD

**Issue by jessenich** [gitpod-io/gitpod#1719]
### Describe the bug
Copy seems to work. As in I can copy from GitPod, and paste to another app. However, if I try to paste into a new code file it freezes up, alongside the iOS “paste” button appearing an random, odd places. Once the iPadOS paste button is tapped, GitPod unfreezes, however no copied text makes it to the destination file. Have tried with files as well. Will text on Firefox for iPadOS and MacOS next and update soon.

### Steps to reproduce
Using the latest Chrome version for iPadOS, copy text from one source file and paste to another. It will freeze until you tap the bubble with no paste results.

### Expected behavior
To be able to copy and paste text between files, and even copying files from one directory to another would be nice.

### Additional information
Unfortunately no logs are output on failure, that I can find at least.

### Example repository
It’s a private repo under contract and NDA, I can’t share the exact repo, but I would assume this is reproducible in any project utilizing GitPod on Chrome for iPadOS.

**Comment by jessenich** [comment]
Any updates or feedback on this from the developers? Would be extremely convenient to develop on an iOS tablet, especially for freelance devs like myself who travel a lot and/or appreciate switching up their workspace location on occasion. Even support for just the new iPad Pro + iPad Magic Keyboard attachment would be wonderful.

**Comment by twalkera16** [comment]
I've also been having these issues!

**Comment by twalkera16** [comment]
> However, if I try to paste into a new code file it freezes up, alongside the iOS “paste” button appearing an random.
I have also been experiencing this same issue has there been any updates to this issue?

**Comment by twalkera16** [comment]
> However, if I try to paste into a new code file it freezes up, alongside the iOS “paste” button appearing an random

I have also been experiencing this same issue has there been any updates to this issue?
