### ISSUE TITLE
Add property to `.gitpod.yml` to close the terminal following command completion

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#17199]
It's quite common for users to write .gitpod.yml scripts that terminate + close, not creating a literal terminal in the IDE. In some cases users have echo'ed messages to their users asking them to manually close terminals, which is added manual labour when opening a terminal that could be avoided. We should consider adding a first class property to the YAML, such as `closeOnFinish` (naming tbd) so that the terminal exits and closes when the script is complete. 

Example from https://github.com/AzBuilder/terrakube/blob/main/.gitpod.yml

```
  - name: Dependencies Backend
    init: |
      chmod +x scripts/dependencies/loadDependencies.sh &&
      scripts/dependencies/loadDependencies.sh &&
      gp sync-done dependencies-backend
    command: echo "Backend Dependencies installed, you can close this terminal"
```

**Comment by svenefftinge** [comment]
I think you can call `exit` to stop the bash process which then closes the terminal.
