### ISSUE TITLE
"We have trouble parsing your context" (network timeout)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#172]
**Describe the bug**

![trouble-parsing-context](https://user-images.githubusercontent.com/599268/49655076-dba67800-fa39-11e8-88ca-f2d66eb06f4b.png)

**To Reproduce**

1. Try to open https://gitpod.io#https://github.com/jankeromnes/gecko-dev
2. See the network timeout error page (after a brief moment)
3. Refresh (second attempt works fine)

**Expected behavior**

The timeout threshold should probably be increased a little, in order not to show a near-instant error page on first try (I suppose this issue only affects very large repositories, but might still be worth fixing).

**Comment by kambleaa007** [comment]
i donno im gettin same
