### ISSUE TITLE
Constantly getting "settings sync is disabled" reminder

### ISSUE THREAD

**Issue by benediktwerner** [gitpod-io/gitpod#17224]
Since a while ago, I'm constantly getting this reminder from the Gitpod extension:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/19309705/232220951-752b13b1-aa9c-40ce-8c28-13594c21e453.png">

It shows up every time I connect to a remote and also in some other cases (I think when editing settings for example).

I use settings sync via GitHub, so I'm not interested in enabling it for Gitpod, so this reminder is rather useless and annoying.

It would be nice to have an option to disable it. Many similar notifications in VSCode have a "don't remind me again" button (not sure about the exact text, but you get the idea). Or maybe it would even just make sense to only show this notification once. If the user doesn't interact with it the first time, they probably won't be interested in it the next hundred times they open a workspace.

**Comment by axonasif** [comment]
Hi @benediktwerner, could you follow the instructions from below link?
- https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop

**Comment by jeanp413** [comment]
@benediktwerner released a new version `0.0.104`, it shouldn't show when you connect to a remote now, only when you update the related gitpod settings
