### ISSUE TITLE
Issue when loging in

### ISSUE THREAD

**Issue by Cois0** [gitpod-io/gitpod#1723]

**Comment by AlexTugarev** [comment]
Hi @Cois0! Welcome to Gitpod!

I've quickly checked the logs and see, that you've logged in successfully. Great!

To start a workspace you need to prefix a repository URL with `gitpod.io/#`. Find more on this on https://www.gitpod.io/docs/getting-started/#getting-started

The message you've seen by the way was a "not found" as you likely prefixed you GitHub account URL. Go to https://github.com/new to create a new repository in your account.
