### ISSUE TITLE
Prebuilt stuck at pending

### ISSUE THREAD

**Issue by palmmymumu** [gitpod-io/gitpod#17267]
### Bug description

I just created a test project (fork from gitpod-samples) and I've found that prebuilt isn't working

![image](https://user-images.githubusercontent.com/8638498/232758686-1fb538e5-5d1c-4c73-81af-a2541ce9b88a.png)

It still stuck at PENDING status without any logs and nothing happen after trying to Cancel Rebuilt

![image](https://user-images.githubusercontent.com/8638498/232759015-a34a364f-40ca-4dc0-8b13-76a5398568a6.png)

### Steps to reproduce

I tried to remove all project, add a new project, created workspace

The issues still happened!

### Workspace affected

palmmymumu-templatenest-f2arnj6w6nm

### Anything else?

Does GitPod have configuration for global .gitpod.yml file for all project?
_No response_

**Comment by axonasif** [comment]
Hi @palmmymumu, did the prebuild eventually run? If so, please feel free to close the issue.
