### ISSUE TITLE
Delete inacitve workspace does not update the page

### ISSUE THREAD

**Issue by RayAsh37** [gitpod-io/gitpod#17386]
### Bug description

I had 2 workspaces which I had not used for 2 days. Today when I logged in, they were marked as inactive and there was a section that offered me to delete the inactive workspaces. I click on "delete inactive workspaces" and then I do the same on the delete confirmation modal but the inactive workspaces are still visible along with the same section that offers to delete the inactive workspaces.

I try again with the same steps, and confirm in the modal too. But nope, it was as if nothing had happened. The two inactive workspaces were staring at me, making me feel bad about my decisions.

But then I  manually refreshed the page and voila, they were no more.

I believe the workspace list is not updating upon deletion.

### Steps to reproduce

1. Create 1 or 2 workspaces.
2. stop them all.
3. let them sit until they are tagged as inactive by gitpod
4. now you must be able to see a new section that offers to delete all the workspaces tagged as inactive.
5. hit that and confirm on the modal too.
6. see that nothing has changed
7. be surprised once you manually refresh the page

### Workspace affected

nope

### Expected behavior

after the deletion, the workspace list should update and not show the previously deletes inactive workspaces or the section with the message to delete the inactive workspaces

**Comment by svenefftinge** [comment]
This has been fixed in the meantime
