### ISSUE TITLE
Support mygitpod.com for helm chart

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#1738]
Would be nice if this would work:

1. `helm install gp gitpod`
2. run `kubectl get services` to look up external IP.
3. open http://192-168-1-10.ip.mygitpod.com/ in my webbrowser.

For Gitpod 0.5.0, the dashboard remains black and I get this error in the JS terminal:
```
WebSocket connection to 'ws://192-168-1-10.ip.mygitpod.com/api/gitpod' failed: Error during WebSocket handshake: Unexpected response code: 302
```

**Comment by corneliusludmann** [comment]
It should work already if you set `hostname` in your `values.yaml` to `192-168-1-10.ip.mygitpod.com` and `forceHTTPS: true`. Setting
```
ingressMode: pathAndHost
components:
  wsProxy:
    disabled: false
```
would make sense for this setting as well.
