### ISSUE TITLE
Active workspace doesn't deactivate causing to have multiple active workspace

### ISSUE THREAD

**Issue by RayAsh37** [gitpod-io/gitpod#17392]
### Bug description

This is a follow-up for the #4635 

Selecting more actions for a workspace and then exiting the overflow menu does not deactivate the workspace. When the process is repeated for multiple workspaces, it leaves multiple active workspaces.

https://user-images.githubusercontent.com/70441807/234560827-405bd261-58be-4bc3-b63f-a8bf4c39d0e1.mp4

### Steps to reproduce

1. open more actions for one workspace and then exit the overflow menu by clicking on some blank space.
2. Repeat the above for another workspace
3. observe multiple active workspaces workspaces

### Workspace affected

no

### Expected behavior

should deactivate the previous active workspace as soon as the user exits the overflow menu and when the user focuses on another workspace. Refer to #4635 for the design details. Maybe @gtsiolis can clarify too.

**Comment by gtsiolis** [comment]
Looping in @henit-chobisa because https://github.com/gitpod-io/gitpod/pull/16657, https://github.com/gitpod-io/gitpod/pull/16258, and https://github.com/gitpod-io/gitpod/pull/16151.
