### ISSUE TITLE
easier ways of making a workspace

### ISSUE THREAD

**Issue by Rexogamer** [gitpod-io/gitpod#1739]
Hey! Gitpod has been very useful for me, and I think the current system for creating workspaces works fine enough (on desktop at least). However, I have two suggestions for making it quicker and easier (especially on mobile):
- maybe some sort of github/gitlab search on the workspaces list?
- for commonly used services, a shorthand could be `gitpod.io/service/org/repo` (so for example, this repo would be `gitpod.io/github/gitpod-io/gitpod`)

Again, thanks for making this! Especially for those without reliable computer access, this is a very useful app.

**Comment by Rexogamer** [comment]
I'm thinking about working on this one - where exactly would I get started?

**Comment by geropl** [comment]
Hi @Rexogamer ,

there currently is a wider effort on re-vamping the complete dashboard (see PR https://github.com/gitpod-io/gitpod/pull/3295). The first step will not include a lot of new features, though. I will forward your issue to the team working on that.

**Comment by svenefftinge** [comment]
Hey @Rexogamer, could you outline the two ideas in more detail? I don't think I understand them.

**Comment by Rexogamer** [comment]
Sure Sven! So my first idea was a search function on the site, so I could
type in a repo name and get a list of results (eg I could search for
"gitpod" and find all repo results); alternatively, maybe the ability to
sort through my personal repositories as a list? The second was basically
the ability to shorten the links a bit (instead of typing out `
gitpod.io/#https://github.com/gitpod-io/gitpod`, I could just type `
gitpod.io/github/gitpod-io/gitpod` or something similar). Hope this helps!

Rexo

**Comment by csweichel** [comment]
side note: [gitpod.io/#github.com/gitpod-io/gitpod](https://gitpod.io/#github.com/gitpod-io/gitpod) works today already
