### ISSUE TITLE
Stuck at "Just getting a few more things ready"

### ISSUE THREAD

**Issue by thisisommore** [gitpod-io/gitpod#17408]
### Bug description

Randomly when I start workspace this view appears 
<img width="988" alt="image" src="https://user-images.githubusercontent.com/51229945/234759332-ee44d0b1-500f-4fdf-9a5d-0edd6b020834.png">

When I login in private window it works without any issue

### Steps to reproduce

1. Start any workspace
2. See the bug
Note - This is very random for me but happened to me 4-5 times till now

### Expected behavior

It should start gitpod workspace normally

**Comment by axonasif** [comment]
Hi @thisisommore, could you copy the console logs when you notice this again? You may share them here afterwards
