### ISSUE TITLE
Upgrade MinIO

### ISSUE THREAD

**Issue by dtwilliams10** [gitpod-io/gitpod#1740]
I'm trying to stand up a self-hosted instance on my own hardware using minikube to start the cluster. I have filled in the values.yaml file but when I try to start the cluster it consistently fails with:
Error: template: gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml:192:20: executing "gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled

Any thoughts or suggestions? I'm trying to run it on an up to date CentOS 7 box with the latest release of Kubernetes.

**Comment by corneliusludmann** [comment]
This is an issue with the helm templates when using newer helm resp. golang (Go >= 1.14.0). See:

- https://community.gitpod.io/t/issues-installing-on-own-k8/1531/5?u=corneliusludmann
- https://github.com/helm/helm/issues/7711#issuecomment-593113347

I quick fix would downgrade your Go or patch the helm charts as described in the link above.

**Comment by corneliusludmann** [comment]
See also https://github.com/minio/minio/issues/9868

**Comment by bacongobbler** [comment]
FYI, this was fixed with https://github.com/helm/charts/commit/89a712556d2e3bb8c18acc350dca0bc9a5baba8d. Bump to a newer version of minio to receive the fix.

https://github.com/gitpod-io/gitpod/blob/0b05b751d0cd4d78e279cf99dfce8f384188190b/chart/requirements.yaml#L11

**Comment by dan-kez** [comment]
@corneliusludmann Just curious if you have any plans to merge the commit associated here

**Comment by timiil** [comment]
hi, me too, i am in WSL2 --> ubuntu 16.04, docker-ce 19.03, (kubectl 1.19.4,GoVersion:"go1.15.2"), (helm 3.4.1, go1.14.11),
when i do 
```
helm repo add charts.gitpod.io https://charts.gitpod.io
helm dep update
helm upgrade --install $(for i in $(cat configuration.txt); do echo -e "-f $i"; done) gitpod .

```
hit the fault:

```
Release "gitpod" does not exist. Installing it now.
Error: template: gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml:192:20: executing "gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled

```

**Comment by yyexplore** [comment]
I also met the same problem with the latest gitpod, gitpod uses low version of minio

I did a quick check, @corneliusludmann 's change is working ,  https://github.com/gitpod-io/gitpod/blob/9c068480a4cbfb8dd5fa5493f0da45b9658c3749/chart/requirements.yaml   ,  but seems it's not merged into master branch so far

**Comment by meysholdt** [comment]
We should upgrade MinIO.

**Comment by meysholdt** [comment]
We've upgraded MinIO:
https://github.com/gitpod-io/gitpod/commit/9b68621d8bcfb98bc5af6feb681f4f72db87aa7c#diff-6f441456bcd7d8cd1a04ca3d3264a683c8d89e22fa600c6058ee0ac8c3c1ef80
