### ISSUE TITLE
Can't reach PyPi from inside a container

### ISSUE THREAD

**Issue by h4ck3rk3y** [gitpod-io/gitpod#17421]
### Bug description

We're maintaining https://github.com/kurtosis-tech/autogpt-package which allows you to spin up AutoGPT with Redis, Weaviate, any other backend of choice

When we spin up Weaviate we also try installing weaviate-client via pip inside the container but for some reason Pip ins't reachable

Doing wget google.com results immediately while pip remains stuck

This breaks weaviate for us

### Steps to reproduce

1. Visit https://gitpod.io/?editor=code#https://github.com/kurtosis-tech/autogpt-package
2. Run kurtosis run github.com/kurtosis-tech/autogpt-package --enclave autogpt '{"OPENAI_API_KEY": "YOUR_API_KEY_HERE"}'

You will see a failure for weaviate not being installed. Kurtosis essentially setup a container for the autogpt image

You can ssh into it using kurtosis service shell autogpt autogpt 

Or use docker

If you then try running `pip install weaviate-client` that would fail as well

### Expected behavior

Pypi should be reachable from inside the container

**Comment by adschwartz** [comment]
@h4ck3rk3y I wonder if this is due to a connection issue based on this error:

```
ReadTimeoutError(\"HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)\")': /simple/weaviate-client/
```

**Comment by axonasif** [comment]
Hi @h4ck3rk3y, does the below link help?
- https://www.gitpod.io/docs/configure#no-internet-access-over-https-port-443-on-docker-containers-with-custom-network

**Comment by h4ck3rk3y** [comment]
This is close to the problem we're having. I'll try this out tomorrow @axonasif

**Comment by h4ck3rk3y** [comment]
@axonasif that seems to do it. Thank you! I am closing this issue.
