### ISSUE TITLE
Provide CSV export for Gitpod usage

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#17455]
## Is your feature request related to a problem? Please describe

https://gitpod.io/usage does not provide a way to export usage data.

## Describe the behaviour you'd like

An export button on the https://gitpod.io/usage page to download usage in CSV ([comma-separated values](https://en.wikipedia.org/wiki/Comma-separated_values)) format.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by alesanchezr** [comment]
Yeah this would be great, we need it to keep track of usage.

**Comment by alesanchezr** [comment]
Yeah, this would be great. We need it to keep track of usage internally and within our several sub-organizations.

**Comment by mbrevoort** [comment]
Hello! Yes, I agree. If think in terms of questions you want to answer about usage, what questions would you ask?

**Comment by gtsiolis** [comment]
Closing this as the feature has been added in #17791. Cc @alesanchezr @mikenikles
