### ISSUE TITLE
Port 8000 locked open

### ISSUE THREAD

**Issue by Robertpokane** [gitpod-io/gitpod#1748]
### Describe the bug

django 

Using 'pyhton3 manage.py runserver'

Port got stuck open even after terminal window got closed. would not run again

**Comment by svenefftinge** [comment]
Sounds like the process didn't die. Did you check using e.g. `ps`?
IF you can reproduce it, please share a [snapshot link](https://www.gitpod.io/docs/sharing-and-collaboration/#sharing-snapshots).
