### ISSUE TITLE
Private ports are accessible publicly

### ISSUE THREAD

**Issue by tekumara** [gitpod-io/gitpod#1751]
### Describe the bug

Private ports are accessible publicly

### Steps to reproduce

In a gitlab workspace, start a server on port 10000:
```
python -m http.server 10000
```

The port is detected, and shows in the footer as private 
<img width="503" alt="Screen Shot 2020-08-27 at 9 30 52 pm" src="https://user-images.githubusercontent.com/125105/91437053-97fa3e80-e8ac-11ea-89b5-0be8cf7470a6.png">

Click open Browser
Copy the URL and open it from another browser or machine

### Expected behavior

It shouldn't be possible to access private ports from anywhere other than the current browser

### Additional information

https://10000-a9875149-cc19-459c-bbd4-d2f03c66bec1.ws-us02.gitpod.io/

### Example repository

https://github.com/tekumara/gitpod-goes-local

**Comment by geropl** [comment]
Hi @tekumara ,

I cannot reproduce the issue on gitpod.io. Are you using a self-hosted installation of Gitpod?

**Comment by tekumara** [comment]
This is happening for me on gitpod.io, eg: https://www.gitpod.io/#https://github.com/tekumara/gitpod-goes-local

eg: https://10000-df011677-b07c-4c4a-9570-2c6f5413b0eb.ws-us02.gitpod.io/

**Comment by geropl** [comment]
Still cannot reproduce. Could it be that you:
 - opened the URL on one of your other machines
 - the browser on that machine is synced with your current machine (and also syncs cookies)?

I tested by opening a private tab, pasted the port url - and got a 403 as expected.

**Comment by tekumara** [comment]
It was someone else's computer, so no cookies could have been synced.

Did you try with the same repo as I?
