### ISSUE TITLE
An individual cannot open workspaces from another org's Private Repository

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#17519]
### Bug description

Ever since my individual account was turned into an organization, I cannot open private repositories from the organization I work for. Instead, it requests that the org installs the Gitpod app.

![image](https://user-images.githubusercontent.com/24193764/236493914-98f0fe84-6e14-48a7-8a74-ee037e27b125.png)

### Steps to reproduce

* Create a private repository in an org that doesn't have the Gitpod app installed.
* Open a repository from an account that has the Gitpod app installed and access to the other org's private repo.

### Expected behavior

I'd expect that the gitpod app installed in my personall account would be enough to open workspaces from any organization that I havea access to.

### Anything else?

I'm a huge fan of CDEs and I have a hard time switching back to local to be honest 😛, but I wasn't able to convince the company to switch just yet. 

Installing the Gitpod app in the whole org might take some time, so it would be nice if the old behavior comes back :)

**Comment by axonasif** [comment]
Hi @ArthurSens 👋 
I've posted this internally.

I'm not sure but it could be that https://gitpod.io/user/integrations got reset, can you check the permissions there?

**Comment by AlexTugarev** [comment]
Hi @ArthurSens! Hope you are doing well!

Please check settings under https://github.com/organizations/coralogix/settings/oauth_application_policy and make sure to approve Gitpod for your Org account. 

<img width="972" alt="Screenshot 2023-05-11 at 08 43 12" src="https://github.com/gitpod-io/gitpod/assets/914497/1f70ebc8-fad9-468a-94a6-4c4475638419">

On GitHub it's a different security model for Orgs, and admins need to approve use of OAuth2 Apps (like Gitpod) so that members may work with repositories under the Org.

**Comment by ArthurSens** [comment]
Unfortunately I don't have access to the org account :(, I need approval from other teams to install gitpod in the org level and I don't know how long that will take

That wasn't a problem before my account turned into an organization in Gitpod though, so I'm wondering if reverting this change isn't a possibility 😅

**Comment by AlexTugarev** [comment]
> Ever since my individual account was turned into an organization

Ah! I got it wrong in the beginning. I thought, it's you GH account that was turned into an organization. 

The change on Gitpod's account model is completely unrelated to the OAuth2 permissions on GitHub. Also, I just learned about an incident with GitHub API. 🤞🏻 that this will be resolved soon, see https://www.githubstatus.com/

**Comment by ArthurSens** [comment]
> Could it be that the GH Org admin cleaned up permissions?

No, it never had permission, to begin with 🤔. My account could open any repository I could access before it became a "Gitpod organization".

After that, it started asking Github organizations to authorize Gitpod so I can open private repositories. Public repositories still work the same way
