### ISSUE TITLE
Ironic website spelling error

### ISSUE THREAD

**Issue by ChillyBots** [gitpod-io/gitpod#17526]
### Bug description

![image](https://user-images.githubusercontent.com/80390882/236672425-0863750f-940f-4f7b-9842-78b823f2b0a6.png)

### Steps to reproduce

Got o https://www.gitpod.io/

**Comment by AFZL210** [comment]
If no one is working on this, I would love to create a patch for it.

**Comment by axonasif** [comment]
Hi @ChillyBots, thanks for reporting and nice catch!

**Comment by axonasif** [comment]
Resolved in https://github.com/gitpod-io/website/pull/3624
