### ISSUE TITLE
Feature request : Deploy On Heroku

### ISSUE THREAD

**Issue by raghavkhanna30** [gitpod-io/gitpod#1753]
### Feature Requested

**About Heroku**

Heroku is a cloud platform as a service supporting several programming languages. One of the first cloud platforms, Heroku has been in development since June 2007, when it supported only the Ruby programming language, but now supports Java, Node.js, Scala, Clojure, Python, PHP, and Go.

**Feature request**

This is to bring attention that as GitPod has become Open Source and is capable to run easily on cloud platform like Google Cloud , AWS , Custom Kubernetes. 
I was looking for a way to deploy this on [Heroku](https://www.heroku.com/) .
If this is possible it can become easier and also it will expand the reach of GitPod . also directly or indirectly it maybe beneficial to someone.
Kind Regards,
Raghav Khanna

(Founder of [Developer Community of INDIA](https://devcommunity.in))

**Comment by geropl** [comment]
Hi @raghavkhanna30 ,

If I understood you correctly you want Gitpod to provide "deploy-to-Heroku" integration out of the box.

Our strategy is more to integrate with existing solutions. For instance there is an [Heroku VS code extension](https://marketplace.visualstudio.com/items?itemName=ivangabriele.vscode-heroku) that seems to be able to deploy apps from within VS code.

Did you [try to install](https://www.gitpod.io/docs/vscode-extensions/) and use that to achieve your goal?

**Comment by raghavkhanna30** [comment]
Hey! 
Thanks for the reply. 
Give me some time I'll check and get back here on the same thread. 

Regards

Raghav khanna

**Comment by svenefftinge** [comment]
Sounds like this is about running Gitpod Self-Hosted on Heroku. AFAIU Heroku doesn't support Kubernetes as the runtime platform. This would be a requirement.

**Comment by raghavkhanna30** [comment]
Okay, @svenefftinge thanks for the information.
