### ISSUE TITLE
can this window be hide？

### ISSUE THREAD

**Issue by zhipengzuo** [gitpod-io/gitpod#17545]
it may be confuse many workspace because there are two windows for each workspace (this window and one ThinClient)
![image](https://user-images.githubusercontent.com/54702578/236989331-73f74b02-a237-4cd1-b6e9-12b693d3734a.png)

**Comment by zhipengzuo** [comment]
seems can set hideToTrayOnStart to true

**Comment by Siddhant-K-code** [comment]
But, this Window tray seems useful when we are in the "Connecting" state to specify the user about the current state of the process:

<img width="362" alt="image" src="https://github.com/gitpod-io/gitpod/assets/55068936/94e68fea-0840-463a-a933-85a41c565c35">
