### ISSUE TITLE
aarch64 support (and system requirements?)

### ISSUE THREAD

**Issue by kisik21** [gitpod-io/gitpod#1756]
Hi! I'm interested in self-hosting Gitpod for myself on a cluster of new shiny Raspberry Pi 4s. Does Gitpod run out-of-the-box on aarch64 and how many Raspberry Pi 4 units you recommend for an optimal configuration?

Let's assume that I configured k3s, the Raspberry Pi 4 units have 4 to 8 GB of RAM each, minimum amount of RAM is preferred. Also assume one user with around 4 workspaces running in parallel as a worst-case scenario.

Generally I would assume that Gitpod scales fairly well horizontally, so in case every workspace has a dedicated machine, they'll run at max speed, but considering I might not need absolute best performance, could I cram all four and the Gitpod infrastructure on a single Raspberry Pi 4 with 8GB of RAM?

For simplification, let's also assume the memory use of non-Gitpod stuff in workspaces is negligible, since my development toolchain and the apps I code are very lightweight.

**Comment by geropl** [comment]
Hi @kisik21 ,

while Gitpod runs on `k3s` works I think the experience would be sub-par: if you had one Pi reserved for `k3s` + Gitpod static services and make run 1 workspace per PI doing dev work would feel very limited.

But the the core problem is that there are no arm Docker images of the Gitpod core services.

**Comment by kisik21** [comment]
It may be beneficial for the project to provide ARM-based Gitpod images in the future - renting an ARM server is dirt-cheap (Amazon offers some) and a fleet of Raspberry Pi units could be built for a price of a single x86_64 server.

**Comment by geropl** [comment]
Do you have a for link the cost-per-performance advantage you're referring too?

**Comment by jasonrandrews** [comment]
I would love to self-host on AWS Graviton. Would it be possible for me to build Arm container images?

**Comment by schabert** [comment]
The cost / performance advantages can be view at e.g. AWS Graviton

> 40% better price performance
https://aws.amazon.com/ec2/graviton/?nc1=h_ls

**Comment by crsct** [comment]
Has there been any development on this front?

I am running a mixed cluster, my controlplane running on ARM while I plan on deploying the workspaces on an x86 server, any idea how I can stop important pods to spawn on the ARM one, except manually setting nodeselector?
