### ISSUE TITLE
Ability to specificy Environment Variables in a .gitpod.yml

### ISSUE THREAD

**Issue by ChevronTango** [gitpod-io/gitpod#17580]
## Is your feature request related to a problem? Please describe

There is currently no easy way to specify additional environment variables to apply to the whole workspace. You might for example want to set it up so that the workspace is always run with `LOG_LEVEL=debug` or `PRODUCTION=false` but presently you'd have to write a task to add those values to the bashrc file. It would be much nicer if Gitpod provided a way to add those variables to the pod directly so that it was globally true and consistent across workspaces, without needing to write any scripts or tasks.

## Describe the behaviour you'd like

An extra parameter in the `.gitpod.yml` file for specifying workspace environment variables. Currently you can only specify variables for individual tasks, not the whole workspace.

```yml
image: registry.gitlab.com/gitlab-org/gitlab-development-kit/gitpod-workspace:stable
env:
  LOG_LEVEL: debug

tasks:
  - name: GDK
```

## Describe alternatives you've considered

writing a task to add the environment variables to the bashrc file manually, but this is cumbersome and ugly.

## Additional context

Gitpod runs its workspaces in the cluster as pods with pre-determined system environment variables so it would make sense if these additional environment variables were simply added to the workspace there rather than doing anything clever inside the workspace itself.

**Comment by svenefftinge** [comment]
You can set environment variables in docker and in your [project configuration](https://www.gitpod.io/docs/configure/projects/environment-variables).

**Comment by ChevronTango** [comment]
> You can set environment variables in docker and in your [project configuration](https://www.gitpod.io/docs/configure/projects/environment-variables).

That assumes you are not reusing the same image in multiple workspaces, or that you are using the project function. If you are creating a community project that many users are expected to fork, and you want to reference a common image, you have no options. The `.gitpod.yml` is supposed to contain everything a workspace needs to function correctly so it's odd that this ask is absent.

**Comment by mustard-mh** [comment]
Hey @ChevronTango , If you want a env

**Repo level**, that could be visible for all users that open your repo with Gitpod, you could try with [`.envrc`](https://direnv.net/) which is default installed in Gitpod workspace-image-full (default image)

If it's **Personal or Team level** then try with `gp env` [[doc](https://www.gitpod.io/docs/configure/projects/environment-variables#using-the-account-settings)]

**Comment by loujaybee** [comment]
A couple additional thoughts...

* My knee-jerk response was this might be best achieved with org-wide env variables, however the request seems to be  for community or open-source projects, so that likely doesn't make sense, the context is different. 
* Ideally, the `.gitpod.yml` is the declarative reference of all the required configuration for a project to run. Having implicit variables for configuration stored in the project in Gitpod is not entirely optimal, it would be nice to define those environment variable names in the `.gitpod.yml`, even if they are sourced from other locations.
