### ISSUE TITLE
[BUG] While Creating a New Workspace, Context URL isn't changing when changing the URL 

### ISSUE THREAD

**Issue by Nabhag8848** [gitpod-io/gitpod#17598]
### Bug description

- When creating an new workspace from a github repository by appending `https://gitpod.io#` Context URL dropdown isn't changing as per the changes in the github repository URL.

### Steps to reproduce

1) open any repository by appending  `https://gitpod.io#` for creation of new workspace.
2) change the github repository url. for eg:
before (open with): https://gitpod.io#https://github.com/<username>/<repo-name>
after: https://gitpod.io#https://github.com/<username>/<new-repo-name>
3) Observer the Context URL dropdown isn't changing.

### Workspace affected

No

### Expected behavior

- Context URL Dropdown should change as the github repository URL in the browser changes.

## Attachment Showing Bug:
- changing to `Nabhag8848/Nabhag8848` didn't change Context URL dropdown
![Gitpod](https://github.com/gitpod-io/gitpod/assets/65061890/cb8e8010-4ffa-4904-963d-544912a029e8)

**Comment by DarshanDixit05** [comment]
Hi 👋 , 
I want to work on this issue , can you please assign it to me ?

**Comment by gtsiolis** [comment]
@DarshanDixit05 Feel free to open a pull request and link back to this issue. 🏓 

Thanks for reporting, @Nabhag8848. 👋
