### ISSUE TITLE
[snapshot] init task is run on snapshots with .gitpod file

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#176]
**Describe the bug**
If the repo contains a `.gitpod` file instaed of the new `.gitpod.yml` file, the `init` task is also run when the workspace is opened as a snapshots. This doesn't make sense as snapshots are about reproducing a very specific state.

**To Reproduce**
Open https://gitpod.io#snapshot/52205fab-aa8c-46a1-b4eb-d9b764b389fd

**Expected behavior**
The `init` task should not run on snapshots.

**Comment by svenefftinge** [comment]
The most important bit is that we want to get rid of `.gitpod` files. So we should update everything.
