### ISSUE TITLE
when a new organization is just created, it starts with no free credits

### ISSUE THREAD

**Issue by seyoon20087** [gitpod-io/gitpod#17604]
### Bug description

Hi folks

When I created a new organization on Gitpod, 
it starts with NO free credits.

I'm not sure if this is intentional.

### Steps to reproduce

1. Create a new organization.
2. Go to `https://gitpod.io/billing` and see the available credits

Here's a sample screenshot:
![image](https://github.com/gitpod-io/gitpod/assets/24852454/2c0454a2-607d-4938-99f0-d4f32e9b4cb0)

### Expected behavior

In the [pricing page](https://www.gitpod.io/pricing), I saw that free credits are 500 by default.

But the credits when I just created are absolutely zero.

I thought that when a new Gitpod organization was just created, it would receive 500 credits.

### Anything else?

Maybe this is a bug on Gitpod.io, or it's intentional?

Note: this is not a question -- I'm writing this just to make sure this is a bug

**Comment by axonasif** [comment]
Hi, this is intentional.
