### ISSUE TITLE
[Bitbucket] Branch context URL with branch with '/' does not work

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#1761]
A Bitbucket branch that has a `/` cannot be opened with Gitpod.

The relevant part in the context parser is here: https://github.com/gitpod-io/gitpod/blob/52660b5ad8a1456d0c28de3833216b8971af0c38/components/server/src/bitbucket/bitbucket-context-parser.ts#L60

`moreSegments[1]` uses the first part of the branch (up to the first `/`) as branch name only.

See also:
- https://community.gitpod.io/t/we-are-having-trouble-parsing-your-context/1732/3

**Comment by geropl** [comment]
I bet you are aware, but just in case: GitHub has the same issue with URLs being non-unique, so we have to [try and see what matches](https://github.com/gitpod-io/gitpod/blob/master/components/server/src/github/github-context-parser.ts#L120).

**Comment by corneliusludmann** [comment]
> I bet you are aware, but just in case: GitHub has the same issue with URLs being non-unique, so we have to [try and see what matches](https://github.com/gitpod-io/gitpod/blob/master/components/server/src/github/github-context-parser.ts#L120).

Yes, that's definitely true for the `…/src/…` context. However, for the `…/branch/…` we could just consider the rest of the URL as branch name, I guess.
