### ISSUE TITLE
Can we pass tokens using gitpod cli, to the port for react frontend and set it to its cookie?

### ISSUE THREAD

**Issue by AkshatNGupta** [gitpod-io/gitpod#17618]
## Is your feature request related to a problem? Please describe
The current login flow in my application is as follows. Users reset their password using aws cognito self hosted page. Users are redirected to github where they again need to log themselves in. After which Users are redirected to gitpod which again asks the users to sign up using the Gitpod CLI, after successful authentication we download artifacts from S3, run the backend JAR and Docker into Gitpod, after which the user opens a frontend port running on 3000, and then finally log in again in the React frontend. This flow includes multiple logins. It leads to a poor user experience and I want to reduce the number of logins required.

## Describe the behaviour you'd like
I would like to improve the user experience by reducing the number of logins in the application flow. Ideally, I want to integrate the existing flow, and reduce the number of login with the authentication process and thereby eliminate the need for separate logins. Users should be able to log in once, or twice at most and seamlessly access the application without repeated authentication steps.

## Additional context
Currently, the login flow involves multiple steps and logins, leading to a cumbersome user experience. By reducing the number of logins, we can enhance usability and make it more convenient for users to access the application. Any improvements to the authentication process would greatly benefit the overall user experience.

Please help.

**Comment by loujaybee** [comment]
Hey @AkshatNGupta 👋 

We are investigating OIDC support that would allow you to connect a workspace to a 3rd party like AWS. 

We'll be talking about this today: https://www.youtube.com/watch?v=iHtAd2Vfz-Q
Also see related issue: https://github.com/gitpod-io/gitpod/issues/9412

However, I get the feeling that you're trying to build sort of a whitelabel experience on top of Gitpod? Is it just authentication into an 3rd party that you need? Or are you looking at something more comprehensive to seamlessly integrate Gitpod into another product flow?

**Comment by AkshatNGupta** [comment]
Hey @loujaybee,

Thank you for looking into OIDC support. It sounds promising for connecting workspaces to third-party services like AWS.

Regarding my use case, while authentication into a third-party service is a part of it, I'm actually looking for a more comprehensive solution to seamlessly integrate Gitpod into another product flow. The current flow involves multiple logins and steps, which can be quite cumbersome for users. I'm aiming to reduce the number of logins and provide a smoother experience.

Ideally, I would like to leverage Gitpod as a white-label experience, where users can seamlessly access the application without the need for repeated logins. This means integrating Gitpod with the existing authentication mechanisms, such as the GitHub login, and potentially exploring options like single sign-on (SSO) or OAuth to streamline the authentication process.

If there are any ongoing discussions or plans to address this type of use case, I would greatly appreciate any information or updates. Improving the integration of Gitpod into product flows would greatly enhance the user experience.

Please let me know if you need any further clarification or if there's any additional information I can provide.
