### ISSUE TITLE
Implement OpenShift installer

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1764]
Should be probably placed in: https://github.com/gitpod-io/gitpod/tree/master/install

OpenShift has a management for VM-based containers which allows for a sane root to resolve https://github.com/gitpod-io/gitpod/issues/39

**Comment by JesterOrNot** [comment]
@Kreyren this mostly is blocked by not having a module to describe an openshift cluster.

**Comment by Kreyren** [comment]
@JesterOrNot Be more specific because i don't understand 17% of what you are saying~

**Comment by JesterOrNot** [comment]
Right now I'm trying to use https://github.com/ibm-cloud-architecture/terraform-openshift4-gcp however it is out of date with the latest terraform version so I have made a fork here https://github.com/JesterOrNot/terraform-openshift4-gcp which will be fixed. Right now we have created a standard way of creating the Gitpod installation. However, with openshift there are no good ways to create the cluster using Terraform. So I'm trying to adapt an already existing one.

**Comment by JesterOrNot** [comment]
Will likley move it directly to the script to make it easier to edit.

**Comment by Kreyren** [comment]
@JesterOrNot Noted, anything else i should know about if i consider contribution? I.e special deployment procedure etc..

**Comment by JesterOrNot** [comment]
Not really, just fill out the variables and do Terraform apply, right now we need to get the OpenShift module working there are quite a few bugs in the script but it seems like a good starting point.

**Comment by JesterOrNot** [comment]
It's very likely I will replace this with my own module

**Comment by JesterOrNot** [comment]
Yea, the module is definitely not made for public use, however, I have asked them what we should do. In the meantime, we might be able to make a hack by templating an `install-config.yaml` file I'm currently writing up a prototype

**Comment by JesterOrNot** [comment]
Or more likely we will create resources from scratch

**Comment by svenefftinge** [comment]
AFAIK openshift doesn't satisfy Gitpod's dependency to containerd.
