### ISSUE TITLE
Implement a whitepaper

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1765]
Whitepapers are a great way to provide information about how the software works which allows for a more efficient implementation and reimplementation that can be peer-reviewed to achieve the expected runtime.

Requesting it to be added.

**Comment by Kreyren** [comment]
ping @geropl @jankeromnes @JesterOrNot I am considering contributions(s) do you might providing info for this so that i don't have to reverse-engineer the whole thing to know how it works? :p

**Comment by ret394** [comment]
you don't need to reverse-engineer the whole thing. That route is plain stupidity, trust your intuition and do it the right way.

thanks for that. and the info. I wouldn't use terraform, but that explains it.

**Comment by Kreyren** [comment]
> you don't need to reverse-engineer the whole thing. That route is plain stupidity

It's not a plain stupidity assuming that it seems like gitpod skipped on the abstracting and research part (the most important once!) prior to writing the code so brainstorming this is expected to allow for a refactor with most likely more efficient and reliable implementation.

Reverse-engineering the code is an option, but a painful one and without a code management the development is likely to divert from that part due to the previous developer-errors so that would be reimplementing the previous mistakes instead of finding a permanent solution.

Which seems to be the case here assuming the lack of documentation, peer-reviews, Insufficient CI and current implementations and decision making alike using GKE that doesn't support VM containers so that end-user doesn't have access to the root during the runtime.

**Comment by ret394** [comment]
>  access to the root during the runtime.

If you're talking about dev work, that isn't required since at least 2008, padding with +2 years.

Once you finish brainstorming and implement the solution. Drop me a link. I'll find the junk and compare my version and see what you guys missed the 2nd time.


> plain stupidity

I wasn't wasting words there.

you're welcome, as always. all the best. 👍
don't say '... passim' to folks on Github or other sites.

[ret394](https://github.com/ret394)

**Comment by Kreyren** [comment]
> If you're talking about dev work, that isn't required since at least 2008, padding with +2 years. @ret394 

Disagree for example cross-platform development is impossible as it requries /dev/kvm (https://github.com/gitpod-io/gitpod/issues/1265) to test the changes or using a docker to test the uselands without messing up the host system (https://github.com/gitpod-io/gitpod/issues/52) to name a few.

Agree that for front-end this might be acceptable enough.

**Comment by svenefftinge** [comment]
We don't have any plans on spending our time on whitepapers atm. If you have specific questions regarding the architecture, please ask.
