### ISSUE TITLE
Strapi Content Security Policy Error

### ISSUE THREAD

**Issue by 201flaviosilva** [gitpod-io/gitpod#17674]
### Bug description

When I run the `npm run develop` command I am getting Content Security Policy Error on the port: http://localhost/:1337/admin

What's weird is that I'm only getting this error in the gitpod environment and not locally.
If I clone this local repository and run `npm run develop` local it will work normally.

### Steps to reproduce

- Open the repo in the gitpod: https://gitpod.io/#https://bitbucket.org/201flaviosilva-labs/q-gitpod-strapi-content-security-policy-error/;
- Run: `npm run develop`;
- Open `http://localhost/:1337/admin` in the browser;

### Example repository

https://bitbucket.org/201flaviosilva-labs/q-gitpod-strapi-content-security-policy-error/

### Anything else?

Sorry if I opened the issue in the wrong place. And thanks in advance. 😅

#### Preview Image

![Preview Image](https://bitbucket.org/201flaviosilva-labs/q-gitpod-strapi-content-security-policy-error/raw/1c619e06ef81307af1303f301a7d96285dd32fa4/Preview.png)

**Comment by axonasif** [comment]
Hi @201flaviosilva,

Can you try it on vscode desktop?
- https://www.gitpod.io/docs/references/ides-and-editors/vscode

It will allow you to port forward.

**Comment by 201flaviosilva** [comment]
@axonasif :)

Thanks a lot for the answer 😁 

But that doesn't solve my problem 😅, I want to use Gitpod in the browser, because if I want to use the project locally, I would clone it instead

**Comment by axonasif** [comment]
How about local-companion app?
- https://www.gitpod.io/blog/local-app

You can continue working from the browser but access your web services through `http://localhost` instead of the gitpod generated subdomain for your port.

**Comment by 201flaviosilva** [comment]
Humm, no, I want to work everything in the browser, it’s easier 😅

And I feel that it's just a workaround, not a real solution 😅

**Comment by axonasif** [comment]
In that case you would need to adjust some of the server internals in your code. I'm not familiar with it this tech stack, so I'll need some time to check. For example, in our own website we manually specify the gitpod generated port address:
- https://github.com/gitpod-io/website/blob/56f69187323b7f02fb5a9f00b49d11c1bf440284/vite.config.js#LL11C9-L11C22
