### ISSUE TITLE
Port is served, but can't be accessed

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#17687]
### Bug description

Ports are listed as ready, but accessing the specific URL shows a "Port 1234 Not Found" error page.

Reported by three people [in Discord](https://discord.com/channels/816244985187008514/1109097680791154819).

### Steps to reproduce

It varies, but from the people who reported the bug, it appears to happen for different web frameworks.

### Workspace affected

t9f7k1bkl0n.ws-us97.gitpod.io, derroylo-derroylogithub-hcv2d1yelx9

### Expected behavior

When a port is listed with a 🟢 icon, it can be accessed at its URL.

### Example repository

No public repository reported

**Comment by ghostdevv** [comment]
This should be [fixed now](https://www.gitpodstatus.com/incidents/2bx7r2fl10gm) so I'll close this, feel free to reopen/comment if there are still problems :pray:
