### ISSUE TITLE
Implement compatibility for Emacs

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1769]
Allow gitpod to deploy a remote terminal in a browser to use emacs on demand or per user configuration on repository.

**Comment by loujaybee** [comment]
Hey, @Kreyren 👋 

Gitpod has early support for a browser based terminal. Some users have explored setting up emacs that way. 

If you're interested, there's some information in how to get into the private beta, if you wanted to test that out. 

See description in: https://github.com/gitpod-io/gitpod/issues/17724
