### ISSUE TITLE
minor grammar error for Theia whitelisted workspace option

### ISSUE THREAD

**Issue by Rexogamer** [gitpod-io/gitpod#1773]
This should read "Deep dive into Gitpod's open-source IDE (written in TypeScript)." I'd fix this but I'm not sure where to look as taking a search the only results were migration files and I suspect that's not the correct place (is it server-side or something?)
![F6BF8FF0-DC40-4D0C-941B-CEDAD7067C00](https://user-images.githubusercontent.com/42586271/91638200-78c2f480-ea05-11ea-836a-28d78b5ae536.jpeg)

**Comment by svenefftinge** [comment]
You can fix it in the migration file, which will be executed on fresh installs. For existing installations this would need to be updated in the DB.

**Comment by Rexogamer** [comment]
fixed in #2145
