### ISSUE TITLE
eu.gcr.io/gitpod-core-dev/build/gitpod-k3s:latest not found

### ISSUE THREAD

**Issue by tekumara** [gitpod-io/gitpod#1775]
```
$ git clone git@github.com:gitpod-io/gitpod.git
$ cd gitpod/install/docker/examples/gitpod
$ docker-compose up
WARNING: The DOMAIN variable is not set. Defaulting to a blank string.
Creating network "gitpod_default" with the default driver
Pulling gitpod (eu.gcr.io/gitpod-core-dev/build/gitpod-k3s:latest)...
ERROR: manifest for eu.gcr.io/gitpod-core-dev/build/gitpod-k3s:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/gitpod-core-dev/build/gitpod-k3s/manifests/latest"
```

**Comment by corneliusludmann** [comment]
We haven't published a `latest` version for these Docker images yet. You could create a `.env` file next to the `docker-compose.yaml` file with a proper version e.g. like this:
```
VERSION=gitpod-build-clu-fix-gitpod-k3s.7
DOMAIN=10-0-0-5.ip.mygitpod.com
```

You also need to configure your domain. The easiest way is to use a domain like `10-0-0-5.ip.mygitpod.com`. Replace `10-0-0-5` with your local IP (does not need to be publicly available, replace `.` with `-`) and you can access Gitpod by opening https://10-0-0-5.ip.mygitpod.com.

Documentation for these Docker images and a `latest` version is coming coon.

**Comment by tekumara** [comment]
Awesome thanks @corneliusludmann! Thanks for the `*.ip.mygitpod.com` tip as well, that very handy 😎 

With the above (using `DOMAIN=127-0-01.ip.mygitpod.com`) I can start the container, but when I browser to https://localhost I get:
```
We are having trouble connecting to the server.
Either you are offline or websocket connections are blocked.
```

In Dev Tools I see:
```
Error during WebSocket handshake: Unexpected response code: 302
```

**Comment by tekumara** [comment]
Using websocat:
```
$ websocat wss://localhost/api/gitpod
websocat: WebSocket SSL error: The certificate was not trusted.
websocat: error running
```

**Comment by corneliusludmann** [comment]
You need to open https://127-0-0-1.ip.mygitpod.com in your browser, not https://localhost. The DNS server of `*.ip.mygitpod.com` resolves to the IP `127.0.0.1`, thus the web traffic does not route from your browser to the server that hosts `*.ip.mygitpod.com`. The traffic goes directly to your local Gitpod instance after DNS resolution. The NGINX reverse proxy needs the host `127-0-0-1.ip.mygitpod.com` to route the traffic and does not work if you use `localhost`.

_By the way: there is a `-` missing in `DOMAIN=127-0-01.ip.mygitpod.com`._

Also: You could now use `latest` as well. I tagged the latest Docker image with `latest` today.

**Comment by corneliusludmann** [comment]
And something else: I guess that `127-0-0-1.ip.mygitpod.com` does not work since resolving as `localhost` could break the communication between the Gitpod components. You can try it but I would recommend to use your local IP that is assigned to your network device like `192.168.1.xx` or `10.0.0.xx` or whatever your local network looks like.

**Comment by tekumara** [comment]
Doh! Taking your helpful suggestions, I've tried the following with `latest`:

`DOMAIN=127-0-0-1.ip.mygitpod.com` with https://127-0-0-1.ip.mygitpod.com/ is the same as above.

`DOMAIN=192-168-1-2.ip.mygitpod.com` with https://192-168-1-2.ip.mygitpod.com/ doesn't even get to the blank gitpod HTML page.
 
I must be doing something else wrong... This is on macOS where the [Docker networking](https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds) is different from Linux.
