### ISSUE TITLE
User-configurable workspace sizes

### ISSUE THREAD

**Issue by tekumara** [gitpod-io/gitpod#1777]
It would be fantastic to have the ability for the end-user to configure:

* CPU
* Memory
* Disk
* Taints (eg: schedule on a GPU)

For their workspaces.

**Comment by pattacini** [comment]
Hi,

I've seen that most of the requests made through this issue are somehow already addressed in the [roadmap](https://github.com/gitpod-io/roadmap/issues/15).

Any plan for supporting GPU as well?
