### ISSUE TITLE
Build finished before we established a listener

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#178]
**Describe the bug**
![listener](https://user-images.githubusercontent.com/599268/49924397-7f6aaa80-feb6-11e8-944e-15f580443439.png)

**To Reproduce**

1. Try to open https://gitpod.io/#https://github.com/jankeromnes/mozjs

**Expected behavior**

The IDE should load successfully even if the build is very fast.

**Comment by 32leaves** [comment]
The build this error message refers to here is not the build tasks that get started when the IDE opens, but the `Dockerfile` build. We've recently changed how we build Dockerfiles and this is a bug that was introduced in the process.

**Comment by 32leaves** [comment]
We haven't seen this issue since the fix ... closing for now.

**Comment by alesanchezr** [comment]
Hey @jankeromnes , I'm having this issue now with this repository:
https://gitpod.io/#https://github.com/breatheco-de/api

Is something wrong on the repository configuration?

**Comment by svenefftinge** [comment]
I couldn't reproduce. The docker build went through nicely.

**Comment by alesanchezr** [comment]
Yep, seems to be working perfect now. Thanks!
