### ISSUE TITLE
can not be reactived in the local VS code window

### ISSUE THREAD

**Issue by randychen2046** [gitpod-io/gitpod#17810]
## Is your feature request related to a problem? Please describe

when opened in local VS code,then it is stopped, can not  be reactived in the VS code window

**Comment by axonasif** [comment]
Hi @randychen2046, can you please provide more info?

**Comment by akosyakov** [comment]
I think it is about a user coming back to VS Code where the last window was remote and then there are many dialogs which are not helpful. @randychen2046 correct?
