### ISSUE TITLE
SSH connection timing out when using the node package node-ssh

### ISSUE THREAD

**Issue by k2helix** [gitpod-io/gitpod#17817]
### Bug description

I'm making a Node.js program which asks the user (which will be a friend) for their Gitpod's ssh access token connection uri so that when they insert it, the program automatically connects to the workspace so that the user does not have to run any commands to run and/or install dependencies and just has to click a .bat or .sh file on their computer.  

I wanted to use the Gitpod workspace as a temporary HTTP server so that the user does not need any kind of port forwarding and to avoid CORS problems, and also because this way the user can edit the program to their needs in Gitpod. However, when connecting via ssh like this, the workspace is stopped some time after the browser window is closed, so the server stops running.

Here is an example of the code I'm using:
```js
const { NodeSSH } = require('node-ssh');
const conn = new NodeSSH();

const config = {
  host: host,
  username: user
};
// config from the access token uri, both host and user are asked in an input before this

conn.connect(config).then(() => {
    conn.execCommand("test");
    // do things
}).catch((error) => {
    console.error('Error connecting to the server:', error);
});
```

### Steps to reproduce

1. Open any workspace.
2. Go back and connect via ssh.
3. Copy the access token uri
4. Connect via node-ssh
5. Wait some minutes to be disconnected.

### Expected behavior

The ssh connection should stay alive until the user closes the node program.

**Comment by akosyakov** [comment]
For ssh connection there is only heartbeating for pty sessions. I'm not sure you have such session if not you can try to increase timeout `gp timeout set` instead.

**Comment by k2helix** [comment]
A bit late but I ended up using ssh from the shell instead. Thank you and sorry for taking so long to answer!
