### ISSUE TITLE
Optional port path customization

### ISSUE THREAD

**Issue by ChevronTango** [gitpod-io/gitpod#17825]
## Is your feature request related to a problem? Please describe

Often when exposing ports using gitpod and having services and UIs working in tandem we see CORS issues cropping up. In production these aren't an issue as the API and UI are hosted on the same domain with nginx doing the routing based on path, eg /api/ is routed to a particular api server. In gitpod we can only expose unique domains. This causes CORS issues that the user then has to debug and resolve when the UI domain does not match the API domain.

## Describe the behaviour you'd like

A way to optionally customize certain ports to instead be exposed at `ports-my-gitpod-workspace.gitpod.io/some-custom-path/` to allow more representative testing.

I can see some users wanting to host a ui at `/` and an API at `/api/` as the most common example setup.

## Describe alternatives you've considered

Many users take to standing up an nginx server locally, but this can be cumbersome and difficult to manage or keep up to date. It would be much nicer if gitpod was able to do at least the simple path routing on the users behalf.

## Additional context

This is mostly to make dev of complex multi component applications easier and more representative of the production environment they will eventually move into. CORS is very annoying and is frequently the stumbling block our users encounter the most when developing there apps using gitpod.

**Comment by axonasif** [comment]
Could https://github.com/gitpod-io/gitpod/issues/10405 be related?

**Comment by ChevronTango** [comment]
I'll add my comments to the other ticket and close this as a duplicate
