### ISSUE TITLE
Handle the error when VS Code Desktop URL doesn't open

### ISSUE THREAD

**Issue by abitrolly** [gitpod-io/gitpod#17836]
### Bug description

If VS Code Desktop doesn't have registered handler, Gitpod silently fails to [open it](https://www.gitpod.io/docs/references/ides-and-editors/vscode?uYLn#connecting-to-vs-code-desktop-ssh).

![image](https://github.com/gitpod-io/gitpod/assets/8781107/4751de17-e42a-42fb-8054-2a35a5c7b646)

The only trace of the error is in JavaScript console.

> Prevented navigation to “vscode://gitpod.gitpod-desktop/workspace/gitlab?%7B%22instanceId%22%3A%223f32cd-b3d1-4443-b2c1-a95a951cfc50%22%2C%22workspaceId%22%3A%22abitrolly-gitlab-8yniopse6uh%22%2C%22gitpodHost%22%3A%22https%3A%2F%2Fgitpod.io%22%2C%22debugWorkspace%22%3Afalse%7D” due to an unknown protocol.

Need to propose alternative way of connecting to workspace from VS Code Desktop if custom handler failed.

### Steps to reproduce

"Open" workspace in VS Code Desktop without registered handler.

**Comment by akosyakov** [comment]
> Need to propose alternative way of connecting to workspace from VS Code Desktop if custom handler failed.

Unfortunately browser does not allow to detect it. @jeanp413 @mustard-mh I'm not sure we can detect it somehow?

Right now we show a message on the loading screen how to proceed. @abitrolly Have you seen it? It has links explaining how to install VS Code. Although it does not explain how to troubleshoot missing OS handler for `vscode` scheme.
<img width="384" alt="Screenshot 2023-06-06 at 10 00 07" src="https://github.com/gitpod-io/gitpod/assets/3082655/ff9d5db9-8c02-41b2-8ec0-ee01a8000c91">

As an alternative we are working right now on a way to manage workspaces from VS Code Desktop. Would it help?

**Comment by loujaybee** [comment]
Thanks for raising @abitrolly 🙏 ... also looks like a duplicate of: 

- https://github.com/gitpod-io/gitpod/issues/9975

**Comment by akosyakov** [comment]
@abitrolly Does it help if you follow [[1](https://code.visualstudio.com/docs/editor/command-line#_code-is-not-recognized-as-an-internal-or-external-command)] and run `Shell Command: Install 'code' command in PATH` from VS Code? Could you open from the browser afterwards?

**Comment by abitrolly** [comment]
> Unfortunately browser does not allow to detect it. @jeanp413 @mustard-mh I'm not sure we can detect it somehow?

Was there a discussion on what-wg working group or something? I am not a web person, so I don't participate in such groups. I've seen people discussing hacks, such as checking that window lost focus, which should happen if the handler is registered and browser shows confirmation window.

I believe Zoom proposes to open web version if desktop didn't start after a few seconds, maybe they don't even check and just show the message for user to decide.

> It has links explaining how to install VS Code.

@akosyakov no, that doesn't help. My VS Code is installed as a `snap` and I don't see another way. I am pretty sure it doesn't have access to system installed browser to mess with it, and I prefer it to be this way. So it is better to describe in detail which mechanism is being used - is it https://code.visualstudio.com/docs/remote/ssh ? If yes, then which URL to feed to it, and how to do it.

> As an alternative we are working right now on a way to manage workspaces from VS Code Desktop. Would it help?

Do you mean installing another extension and stuff? I prefer [boring solution](https://handbook.gitlab.com/teamops/decision-velocity/#boring-solutions) with no extra fancy extensions and buttons.

**Comment by akosyakov** [comment]
@abitrolly thank you for taking time to explain, it is very helpful. Yes, we rely on Remote SSH, but it is not enough, since you need integration with Gitpod services to keep workspace alive while your are using it, integrations with Gitpod tasks, ports and so on. The system handler will automatically install https://marketplace.visualstudio.com/items?itemName=gitpod.gitpod-desktop which does it. We are working on adding workspace management functionality to it, so you will be to use a command palette like `Gitpod: Start Workspace`, plug context URL and the extension will do the rest.

**Comment by abitrolly** [comment]
> you need integration with Gitpod services to keep workspace alive while your are using it

SSH server can automatically terminate idle session https://unix.stackexchange.com/questions/150402/what-is-the-default-idle-timeout-for-openssh so why Gitpod doesn't use that?

**Comment by abitrolly** [comment]
I am not sure it is resolved.
