### ISSUE TITLE
Include Visual Studio Code Insiders

### ISSUE THREAD

**Issue by codingbutstillalive** [gitpod-io/gitpod#17835]
Github Copilot currently only works under Visual Studio Code Insiders. Would be nice to see this an an IDE option.

**Comment by axonasif** [comment]
Hi, you need to toggle on `Latest Release (Unstable)` in https://gitpod.io/user/preferences
<img width="627" alt="Screenshot 2023-06-06 at 1 11 18 AM" src="https://github.com/gitpod-io/gitpod/assets/39482679/51d3819a-2380-4f0d-9955-0e4c4391bb94">
