### ISSUE TITLE
Add cross-through tagging support for AWS self-hosted installation

### ISSUE THREAD

**Issue by lunaticare** [gitpod-io/gitpod#1783]
It would be awesome to be able specify the set of tags to be put on every AWS resource created by self-hoster.

It would let users:
* specify cost allocation tags used in the organization
* create tag-based IAM policies which are consistent with the organization's rules

**Comment by JesterOrNot** [comment]
@lunaticare Are you talking about an `extra_tags` variable where one could specify tags to be placed on resources in a module?

**Comment by lunaticare** [comment]
@JesterOrNot Yes, a simple version would just allow to set tags which are not used Gitpod installation itself.
A more sophisticated approach might include consistent naming scheme like https://github.com/cloudposse/terraform-null-label
However an `extra_tags` variable should be enough for described usage cases.

**Comment by JesterOrNot** [comment]
OK.

**Comment by sheldonhull** [comment]
Great minds think alike :-) i actually did this in my own branch on one, adding in the exact same cloudposse module. I think the overall design would ideally need a few tweaks with "auto" vars to be driving all those names when possible, so if there is interest in this I could throw together a modified plan for this using cloudposses label module and submit a PR for review. Interested?
