### ISSUE TITLE
Git lost my identity configuration

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#179]
**Describe the bug**
I was working in Gitpod trying to commit a bunch of files when Git started to complain that
```
gitpod /workspace/gitpod $ git commit

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <(null)>) not allowed
```

When looking at the `~/.gitconfig` file, I the name is indeed not configured:
```
gitpod /workspace/gitpod $ cat ~/.gitconfig
[push]
        default = simple
[alias]
        lg = log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
[credential]
        helper = /usr/bin/gp credential-helper
[user]
        email = myemailaddress@typefox.io
```

**To Reproduce**
I am not sure what happened or how to reproduce this. The workspace I was working in was a restarted one where I had previously committed files from without issues (even after prior restarts).

**Expected behavior**
The commit should have gone through without a complaint. The config should have my name set so that Git knows who I am.

**Comment by benbogart** [comment]
This just happened to e as well.  I also do now know what caused the configuration to be rest.  My last commit had no problems and and now my config file has been replaced with:
`[user]
	name = 
	email = `

**Comment by jankeromnes** [comment]
Not technically stale, since it reproduced last month. 😬

Please re-open or comment here if this error reproduces again (or please open a new issue, linking to this one).
