### ISSUE TITLE
Multiple 'Are you ready-to-code?' emails on sign-up

### ISSUE THREAD

**Issue by vitalEol** [gitpod-io/gitpod#1791]
### Describe the bug
Receiving multiple emails (73 & counting in first 30 mins)

### Steps to reproduce
Sign-up/Log-in with GitHub

### Expected behavior
Email received once

### Additional information
N/A

### Example repository
N/A

**Comment by jankeromnes** [comment]
Wow, so sorry about that, I was able to confirm that our mailing system is going crazy.

I've escalated this issue with the team and we'll try to stop & fix this problem. (I don't know yet if it's just you or other users as well -- many thanks for reporting this so fast!)

**Comment by jankeromnes** [comment]
Update: We've found the problem to be a bug in our batch-email-retry mechanism, triggered by a badly-formated email address provided by a user. (The faulty email caused the entire batch to be retried multiple times, even though the other addresses in the batch were valid.)

We're mitigated the situation for now, and are now working on a permanent fix for this bug. Sorry about the email flood and thanks again for reporting this so quickly. 👍

**Comment by jankeromnes** [comment]
(Maybe let's keep this issue open until it's permanently fixed in production.)
