### ISSUE TITLE
SSH as the default editor

### ISSUE THREAD

**Issue by daniloraisi** [gitpod-io/gitpod#17928]
## Is your feature request related to a problem? Please describe

This is a feature request.

## Describe the behaviour you'd like

Allow the user to select SSH as the default editor when creating a new Workspace

![image](https://github.com/gitpod-io/gitpod/assets/38328735/92df7f8d-7809-4d91-a1ef-31adb49fed5c)

**Comment by loujaybee** [comment]
Thanks @daniloraisi ! Can I ask a couple questions on your context....

1. What is the experience you're expecting when you set SSH as the default editor? An easier way to copy paste the SSH connection string for your local machine? Or something else? 
2. What do you then do with the copied SSH string? Are you pasting that into another application to connect, or using it for direct editing? How many connections do you typical open, and for what? 
3. Do you currently have a public key uploaded to gitpod? or are you using the access token SSH connection string? 
4. We have early support for a browser based terminal (https://github.com/gitpod-io/website/pull/3684) would that be something you'd be interested to try out? (it's currently in private beta)

**Comment by loujaybee** [comment]
I think this also could be a duplicate of this issue: 

* https://github.com/gitpod-io/gitpod/issues/9323#issuecomment-1141472973

**Comment by daniloraisi** [comment]
Thanks for the quick replay @loujaybee 

> 1. What is the experience you're expecting when you set SSH as the default editor? An easier way to copy paste the SSH connection string for your local machine? Or something else?

My original thought was the ability to copy the SSH connection string without clicking the button `More Actions...` and then `Connect via SSH`.

> 2. What do you then do with the copied SSH string? Are you pasting that into another application to connect, or using it for direct editing? How many connections do you typical open, and for what?

I use my local terminal to connect—usually, only one connection. I have dotfiles configuring my GitPod to have TMUX and all the tools I need from a single SSH connection.

> 3. Do you currently have a public key uploaded to gitpod? or are you using the access token SSH connection string?

Yes, I connect with a public/private key instead of an Access token.

> 4. We have early support for a browser based terminal ([Document the Browser Terminal website#3684](https://github.com/gitpod-io/website/pull/3684)) would that be something you'd be interested to try out? (it's currently in private beta)

I'm interested in testing if possible.

**Comment by daniloraisi** [comment]
> I think this also could be a duplicate of this issue:
> 
> * [Epic: Vim as an explicit IDE preference #9323 (comment)](https://github.com/gitpod-io/gitpod/issues/9323#issuecomment-1141472973)

I see this as a possibility, but not related to my request. I use Neovim when connected to GitPot through SSH, but I have dotfiles to configure it.

My idea was to provide a simple way to copy the SSH connection string or, in a different approach, as you presented in https://github.com/gitpod-io/website/pull/3684.

**Comment by daniloraisi** [comment]
@akosyakov @loujaybee, any chance to get early access to the In-Browser SSH to help testing?

**Comment by akosyakov** [comment]
@filiptronicek you can whitelist by user id?

**Comment by loujaybee** [comment]
Hey @daniloraisi we are adding you now, can you check if you see it in the dropdown of editors? 🙏 

If you have any feedback, we'd love to hear it.

**Comment by daniloraisi** [comment]
Hello @loujaybee, I saw the option and started using it.
I'm using TMUX with some specific configurations. I faced a strange situation. Where can I send all the info regarding this?

**Comment by loujaybee** [comment]
Here is good, but any option in: https://gitpod.io/support also works. 

Feel free to tag me on Discord, also! https://gitpod.io/chat too 🙏
