### ISSUE TITLE
CLI: gp sync-await does not exit with expected exit code on Ctrl-C

### ISSUE THREAD

**Issue by mk-mxp** [gitpod-io/gitpod#17962]
### Bug description

It is impossible to distinguish, if `gp sync-await` has recieved the expected signal or was aborted by the user using `Ctrl-C`, because the exit code is always `0` (success). Following my shell coding experience, an exit code of `130` (caught SIGINT) is expected.

### Steps to reproduce

In any workspace, open a terminal. Run:

```shell
gp sync-await does-not-matter; echo "$?"
```

and press Ctrl-C to abort the waiting. The result is 0.

### Expected behavior

The exit code is 130.

**Comment by akosyakov** [comment]
@iQQBot What do you think should we generally respect it, I think the convention is 128 + interruption code,

**Comment by mk-mxp** [comment]
Wow! Thanks a lot. Very quick...
