### ISSUE TITLE
Authentication or Authorization issue between Gitpod and LinkedIn.

### ISSUE THREAD

**Issue by Neon-20** [gitpod-io/gitpod#17960]
### Bug description

**It's possible that the authentication process is not successfully retrieving the necessary access tokens or permissions to interact with LinkedIn account.**
Update: I am also not able to access my dashboard in gitpod when I try to connect with linkedin.

### Steps to reproduce

Maybe reconfigure the auth pipeline between linkedin and gitpod.

### Expected behavior

It should enable me to get the credits with my Linkedin account when I do connect with Linkedin on gitpod.

### Example repository

https://github.com/gitpod-io/gitpod/assets/55043383/8ead8e70-126b-4214-832a-6209b34d3b0c

**Comment by akash19coder** [comment]
I wanna work on this issue can please get assigned
