### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#1799]
We want to go away from the `gitpod-protocol` and JSON RPC in favor of GraphQL.
To that end we should enhance the existing admin API.

**Comment by svenefftinge** [comment]
We will see

**Comment by tekumara** [comment]
Sounds very cool. A genuine curious question, what advantages will GraphQL provide over JSON RPC?

**Comment by svenefftinge** [comment]
> Sounds very cool. A genuine curious question, what advantages will GraphQL provide over JSON RPC?

Good question. So far it seems mostly its popularity. Having spent a couple of hours on researching this further, I'm more and more sceptical this is a good use of our time TBH.
