### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#18]
Create Swift extension and make it available in Gitpod.

**Comment by svenefftinge** [comment]
LS needs Linux support : https://github.com/RLovelett/langserver-swift/issues/18

**Comment by funcsatish** [comment]
You can use [SourceKit-LSP](https://github.com/apple/sourcekit-lsp)

**Comment by meysholdt** [comment]
closing in favor of https://github.com/gitpod-io/gitpod/issues/805.
