### ISSUE TITLE
POST requests in aspnet core apps result in Bad Requests

### ISSUE THREAD

**Issue by rinormaloku** [gitpod-io/gitpod#180]
**Describe the bug**
ASP.NET Core applications result in Bad Requests when making POST requests (work fine with GET requests). 
The aspnet app produces the following error:

```
info: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HLIT29JMM76O" bad request data: "Requests with 'Connection: Upgrade' cannot have content in the request body."
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Requests with 'Connection: Upgrade' cannot have content in the request body.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.For(HttpVersion httpVersion, HttpRequestHeaders headers, Http1Connection context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

This issue is caused by KestrelHttpServer that doesn't support Upgrade Requests [Kestrel issue link](https://github.com/aspnet/KestrelHttpServer/issues/2372).

**To Reproduce**
1. Checkout the repo for the code and starting the instance directly in gitpod: https://github.com/rinormaloku/sa-feedback
2. Execute the command:

```
$ dotnet run
```

3. When you run the above command you get a URL in which you can reach the started application.
4. Execute the command below the URL:

```
$ curl -i -H "Accept: application/json" -H "Content-type: application/json" -X POST https://{WEBAPP_URL}/feedback -d "{'sentence': 'i like', 'polarity': 0, 'correct': false }"
```

Response: Bad request **BAD**

```
HTTP/1.1 400 Bad Request
Server: nginx/1.14.1
Date: Thu, 13 Dec 2018 12:11:46 GMT
Content-Length: 0
Connection: keep-alive
X-Gitpod-Region: europe-west1
X-Gitpod-WorkspaceId: f9ff821f-ee78-4c39-b5a1-d4f8cfa9f4a6
X-Gitpod-Port: 8080
```

**Expected behavior**
POST executed successfully.

** Additional info **
I have an important use case where I demo Bot framework v4 to workshop participants using gitpod, and am interested to help to get this one fixed (if it is in our control), give me couple of hints where I should start looking into, and I will get started ;) .

**Comment by svenefftinge** [comment]
Looking into it right now.

**Comment by svenefftinge** [comment]
If I use 
```sh
curl -i -H "Accept: application/json" -H "Content-type: application/json" -X POST http://0.0.0.0:8080/feedback -d "{'sentence': 'i like', 'polarity': 0, 'correct': false }"
```
then it works. 
Is it necessary to use the external URL from within the workspace?

**Comment by geropl** [comment]
We might be a bit to eager with sending `Connection: upgrade` here. @svenefftinge, I sent you a PR.

**Comment by rinormaloku** [comment]
@svenefftinge yes, sorry for being unclear, we need to use the external url generated by gitpod.

**Comment by svenefftinge** [comment]
@geropl Thanks, with your change I get:

```
HTTP/1.1 201 Created
Server: nginx/1.13.3
Date: Thu, 13 Dec 2018 14:47:34 GMT
Content-Length: 0
Connection: keep-alive
X-Gitpod-Region: europe-west1
X-Gitpod-WorkspaceId: a400470c-a223-47d5-9e6b-6bd353ed2a78
X-Gitpod-Port: 8080
```

**Comment by geropl** [comment]
@rinormaloku I just re-tested, it should work now.

**Comment by rinormaloku** [comment]
Such responsiveness is rare!  
Thanks a ton guys! <3
