### ISSUE TITLE
setting git user.email via user ENV dont work.

### ISSUE THREAD

**Issue by MaxPeal** [gitpod-io/gitpod#1800]
### Describe the bug
setting git user.email via user ENV dont work.

### Steps to reproduce
enable Keep my email addresses private in github,
after this its not possibly to make a git push form gitpod,
as gitpod override it with
https://github.com/gitpod-io/gitpod/blob/master/components/ws-manager/pkg/manager/create.go#L527-L543
and:
in the bashrc:
```
    && git config --global credential.helper "/usr/bin/gp credential-helper" \
    && git config --global user.name "${GITPOD_GIT_USER_NAME}" \
    && git config --global user.email "${GITPOD_GIT_USER_EMAIL}" \ 
```

see also 
https://github.com/gitpod-io/gitpod/issues/1555
https://github.com/gitpod-io/gitpod/issues/387
https://github.com/gitpod-io/dockerfreeze/pull/51
https://github.com/gitpod-io/gitpod/issues/1263
https://github.com/gitpod-io/gitpod/blob/master/components/theia/supervisor/pkg/supervisor/supervisor.go#L148

**Comment by corneliusludmann** [comment]
I have set the following environment variables in https://gitpod.io/settings/ with Organization/Repository filter `*/*` to my e-mail address I want to have in the Git history:
```
GIT_AUTHOR_EMAIL
GIT_COMMITER_EMAIL
```

When I start a workspace, Git uses these e-mail addresses. Does this work for you?

**Comment by MaxPeal** [comment]
i have try and set the following environment variables:

Name | Value | Organization/Repository
------------ | ------------- | -------------
EMAIL | idNummber+GithubUser@users.noreply.github.com | \*/\* | 
GIT_AUTHOR_EMAIL | idNummber+GithubUser@users.noreply.github.com | \*/\* |  
GIT_COMMITTER_EMAIL | idNummber+GithubUser@users.noreply.github.com | \*/\* |  
GIT_CONFIG_NOSYSTEM | 1 | \*/\* |  
GIT_USER_EMAIL | idNummber+GithubUser@users.noreply.github.com | \*/\* |  
GIT_USER_NAME | GithubUser | \*/\* |  
GITPOD_GIT_USER_EMAIL | idNummber+GithubUser@users.noreply.github.com | \*/\* |  
GITPOD_GIT_USER_NAME | GithubUser | \*/\* | 

but i will try it again with a new user and only 
Name | Value | Organization/Repository
------------ | ------------- | -------------
GIT_AUTHOR_EMAIL | idNummber+GithubUser@users.noreply.github.com | \*/\* |  
GIT_COMMITER_EMAIL | idNummber+GithubUser@users.noreply.github.com | \*/\* |

**Comment by MaxPeal** [comment]
with 

Name | Value | Organization/Repository
------------ | ------------- | -------------
GIT_AUTHOR_EMAIL | idNummber+GithubUser@users.noreply.github.com | \*/\* |  
GIT_COMMITER_EMAIL | idNummber+GithubUser@users.noreply.github.com | \*/\* |  

the push via the gui just failed without error message.
with a git push i get:
gitpod /workspace/foo $ git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 16 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 317 bytes | 317.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH007: Your push would publish a private email address.
remote: You can make your email public or disable this protection by visiting:
remote: http://github.com/settings/emails
To https://github.com/bla/foo.git
 ! [remote rejected] master -> master (push declined due to email privacy restrictions)
error: failed to push some refs to 'https://github.com/bla/foo.git'
gitpod /workspace/foo $

**Comment by corneliusludmann** [comment]
How does 
```
$ git log --pretty=fuller
```
look like? Is the author and committer e-mail of your newly added commits correct?

By the way: It needs to be `GIT_COMMITTER_EMAIL` (with 2 `T`, sorry for my typo above).

**Comment by MaxPeal** [comment]
yes the the output of:
git log --pretty=fuller
looks corect.

**Comment by corneliusludmann** [comment]
Unfortunately, I'm not able to reproduce your issue.

1. With the environment variables `GIT_AUTHOR_EMAIL` and `GIT_COMMITTER_EMAIL` you can control which e-mail addresses should be used by Git. This seems to work for you as well since `git log --pretty=fuller` looks correct.
2. When I check `Keep my email addresses private` and `Block command line pushes that expose my email` in GitHub I'm not able to push commits with another e-mail address than `24960040+corneliusludmann@users.noreply.github.com` but I am able to push commits with that e-mail (as expected).

There is no magic in Gitpod when you push commits. Therefore this seems not a Gitpod issue. Please double-check that you try to push commits with the correct e-mail only. Have you tried the same steps locally (without Gitpod involved)?

**Comment by jankeromnes** [comment]
Seems like a duplicate of https://github.com/gitpod-io/gitpod/issues/387
