### ISSUE TITLE
Project-specific environment variables are no longer available in workspaces

### ISSUE THREAD

**Issue by najens** [gitpod-io/gitpod#18043]
### Bug description

When you setup a new project-specific environment variable and uncheck the "Hide Variable in Workspaces" checkbox to make it available to workspaces, the environment variable is only accessible in prebuild and not accessible in the workspace. This was working a few weeks ago and appears to have stopped working without any changes made on our end. I also tried recreating the environment variable and making visible to workspaces again and that didn't work. There appears to be a regression on the Gitpod side, unless this is deprecated feature.

### Steps to reproduce

1. Create a new project-specific environment variable and uncheck "Hide Variable in Workspaces"
2. Run a prebuild of the project and echo the environment variable in a "before"  start task. You will see the environment variable during the prebuild.
3. Start a new workspace off of the prebuild. When the "before" start tasks runs again, the environment variable will now have an empty value.

This bug was repeatable across multiple projects, on new projects, and with new environment variables being set using new prebuilds and new workspaces.
<img width="1381" alt="Screenshot 2023-06-23 at 1 08 20 PM" src="https://github.com/gitpod-io/gitpod/assets/28149914/3458871d-183b-4aed-b986-31e246e1b85b">

### Workspace affected

salesrabbit-localfpcomm-8dmliwvatmm

### Expected behavior

I would expect the environment variable to be available in the workspace with the value that was set in the Gitpod project settings for environment variables.

### Example repository

[salesrabbit-localfpcomm-8dmliwvatmm](https://gitpod.io/start/#salesrabbit-localfpcomm-8dmliwvatmm)

**Comment by geropl** [comment]
Hey @najens ,

thanks for reporting.

> Start a new workspace off of the prebuild. When the "before" start tasks runs again, the environment variable will now have an empty value.

Just to verify: How exactly are you starting that new workspace off a prebuild? Asking because it might lead to different behavior.

**Comment by geropl** [comment]
Also, when starting a regular workspace from a repository, I see all my environment variables are present as expected. But will re-test with prebuilds now. :+1:

**Comment by najens** [comment]
@geropl We are using Gitlab and `mainConfiguration` in the `.gitpod.yml` file to store the steps for setting up the local environment in a separate repository from where all of our code lives.  I have triggered new workspaces from within Gitlab as well as from Gitpod UI. In the instances where I have triggered a new workspace from a  prebuild, I've been clicking the green `New Workspace (with this prebuild)` button after the prebuild has completed.
<img width="1345" alt="Screenshot 2023-06-29 at 2 47 21 PM" src="https://github.com/gitpod-io/gitpod/assets/28149914/ba672d0e-d29c-4a0c-8a90-4dd8bdc3ddbb">
<img width="560" alt="Screenshot 2023-06-29 at 2 47 35 PM" src="https://github.com/gitpod-io/gitpod/assets/28149914/c5a88d0e-02f2-4439-8b6a-6a2eda794bb2">

**Comment by PatrickRice-KSC** [comment]
@geropl  - We're also experiencing this issue. We spin up GitPod instances using the built-in integration with GitLab, and starting something this week variables configured at either the project or the user level no longer inject properly into GitPod. Multiple internal projects at my org have reported the same issue.

**Comment by geropl** [comment]
@PatrickRice-KSC Are you using the `mainConfiguration` feature as well?

**Comment by PatrickRice-KSC** [comment]
@geropl  - We are not, no 😕

**Comment by PatrickRice-KSC** [comment]
My issue seems to be resolved for _project_ variables now (not sure what would have resolved it, but figured I'd update the issue). For _user_ variables, the documentation for GitLab has been updated to state that scoping requires "*/**" instead of "*/*", which resolved the user variable issue for everyone.

Just wanted to chime in for anyone else who may find this issue.

**Comment by shaal** [comment]
I have a project in Github, and I see the same things. Setting up project variables ('visible') in Gitpod, but the workspace doesn't receive these variables. A few days (weeks?) ago it still worked. I am not sure what changed?
