### ISSUE TITLE
Nodejs: Ubuntu Focal Fossa (development branch) is not supported

### ISSUE THREAD

**Issue by ceefour** [gitpod-io/gitpod#1806]
### Describe the bug
Ubuntu Focal Fossa (development branch) is not supported

### Steps to reproduce
Install nodejs within Dockerfile based on workspace-mysql

```
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists...

## Your distribution, identified as "Ubuntu Focal Fossa (development branch)", is a pre-release version of Ubuntu. NodeSource does not maintain official support for Ubuntu versions until they are formally released. You can try using the manual installation instructions available at https://github.com/nodesource/distributions and use the latest supported Ubuntu version name as the distribution identifier, although this is not guaranteed to work.



build failed: cannot build base image: The command '/bin/sh -c sudo apt-get update     && sudo apt-get install -y curl     && (curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -)     && sudo apt-get install -y curl nano python3 python3-pip build-essential python3-setuptools mariadb-client mariadb-client-10.3 nodejs redis-server cron     && sudo rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

Error: build failed: cannot build base image: The command '/bin/sh -c sudo apt-get update     && sudo apt-get install -y curl     && (curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -)     && sudo apt-get install -y curl nano python3 python3-pip build-essential python3-setuptools mariadb-client mariadb-client-10.3 nodejs redis-server cron     && sudo rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```

### Expected behavior
Using Ubuntu Focal official release (latest is 20.04.1) to ensure good software support.

### Additional information
https://gitpod.io/#https://gitlab.com/lovia/lovia-erpnext-bench

### Example repository
https://gitpod.io/#https://gitlab.com/lovia/lovia-erpnext-bench

**Comment by corneliusludmann** [comment]
I cannot access your example repository. I get a 404. Is it a private repo?

Could you please provide at least your Dockerfile?

**Comment by ceefour** [comment]
@corneliusludmann Dockerfile below:

```docker
FROM gitpod/workspace-mysql

RUN sudo apt-get update \
    && sudo apt-get install -y curl \
    && (curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -) \
    && sudo apt-get install -y curl nano python3 python3-pip build-essential python3-setuptools mariadb-client mariadb-client-10.3 nodejs redis-server cron \
    && sudo rm -rf /var/lib/apt/lists/*

RUN sudo -E npm install -g yarn
```

**Comment by corneliusludmann** [comment]
What I can see is that you try to install a lot of tools that are already installed in the `gitpod/workspace-mysql` image. I don't know your requirement but the only thing that really makes sense is to install `redis` like this:

```Dockerfile
FROM gitpod/workspace-mysql

RUN sudo apt-get update \
    && sudo apt-get install -y redis-server \
    && sudo rm -rf /var/lib/apt/lists/*
```

- `mariadb-client` is not part of the MySQL image but the MySQL client. If you want to use `mariadb` you probably don't want to use the MySQL base image.
- Don't know how good `cron` works in Gitpod. You could try it out but probably you don't need it.
- Other tools like python, node, yarn etc. are installed. You could also have a look here: https://www.gitpod.io/docs/languages-and-frameworks/

**Comment by ceefour** [comment]
Alright, but ... is Gitpod base image indeed using a focal development image instead of a released one ? If so, I wonder why...
And whether Gitpod base image can run normally with using a released focal image .

**Comment by sr229** [comment]
> Alright, but ... is Gitpod base image indeed using a focal development image instead of a released one ? If so, I wonder why...
> And whether Gitpod base image can run normally with using a released focal image .
> 
> Note that I tried to install Node 12 as for some reason, previously I wasn't able to run yarn (?) using the gitpod workspace image. But I lost the exact Dockerfile that had that issue.

I doubt they're using dev branches of Ubuntu in production, since that's a rather large moving target. If we're going to use development versions we might as well target Debian Sid.

**Comment by corneliusludmann** [comment]
You'll find the Docker file of the Gitpod base image here: https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile

**Comment by ceefour** [comment]
Thanks @corneliusludmann, I will close this issue as it is specific to Nodejs installer script.
