### ISSUE TITLE
Make workspace URL expose ports using the same hostname

### ISSUE THREAD

**Issue by ceefour** [gitpod-io/gitpod#1808]
My use case is: https://discuss.erpnext.com/t/how-to-set-frappe-socketio-url-in-development-mode/65550

By default, Frappe/ERPNext requires web server (on port 8000) and socketio (on port 9000) using the same hostname (e.g. `http://localhost/` or `https://*.ws-us02.gitpod.io/`)

However, gitpod will allocate different hostnames for each port.

Please provide a way (i.e. `gitpod.yml` setting) so we can have the same exposed URL for one workspace for all ports, and access ports normally.

Related to, but different than #898.

**Comment by erasmuswill** [comment]
#736 could also be solved by this

**Comment by akosyakov** [comment]
We just announced preview version of Gitpod local companion which allows to tunnel any tcp port: https://www.gitpod.io/blog/local-app particularly it allows you access everything on localhost on proper port, similarly how you will do it in the local env, please try and give us feedback 🙏🏻
