### ISSUE TITLE
Only half of requests getting through

### ISSUE THREAD

**Issue by nhorton** [gitpod-io/gitpod#18097]
### Bug description

When running a docker-ized application inside Gitpod and accessing it via VSCode desktop with the local proxying, only half of the requests seem to ever get to my server. The same code run locally works fine. The behavior is basically that one can sit there watching the incoming logs and hit reload on a web page over and over, and only 1 in 2 or 3 requests will actually show in the log.

Are you aware of any set of issues / settings / gremlins that can result in not all requests getting to the gitpod instance?

### Steps to reproduce

I don't really have a repro - I am hoping to isolate what might be the cause

### Workspace affected

unsupervise-unsupervise-7ufc4k7iho5

**Comment by akosyakov** [comment]
@nhorton Do you have a reproducible repo? It would make it easier to troubleshoot. 🙏

**Comment by akosyakov** [comment]
@nhorton, there is a known issue with Docker in Gitpod. Consequently, we distribute our own version of the docker daemon/docker-compose that includes necessary fixes. You may have installed a different version that does not include these adjustments.

To remedy this situation, please consider the following:

- Refrain from using your own Docker distribution, if that's the case.
- Refer to the following guide to help resolve network issues: https://www.gitpod.io/docs/configure#no-internet-access-over-https-port-443-on-docker-containers-with-custom-network.

Please let us know if this helps address your problem. We value your feedback.

**Comment by nhorton** [comment]
That is helpful info. Is there an easy way to tell if the version of docker running is your patched version? We have scripts that update dev environments across gitpod and physical machines, and it is not immediately obvious if that update causes the gitpod version to be replaced.

**Comment by aledbf** [comment]
@nhorton if you use docker compose you can check using `docker compose version` returns
`Docker Compose version v2.1X.X-gitpod.0`

**Comment by nhorton** [comment]
I just ran this in our repo and did not see that, but I also just ran it in a virgin repo with no .gitpod.yml or anything that overrides anything, and I get:
`Docker Compose version dde0213`
Are you sure that you are bundling that in still? I don't have a way of getting the docker image version for the workspace, but here is the `gp version` info if it helps. `commit-de62cdc802aae120d90d9855238267250b08b65a`

**Comment by aledbf** [comment]
@nhorton are you using a custom docker image?

Also, please run `which docker compose` (to see if you are installing it in a different path) and also check if the directory is defined before `/usr/local/bin` when you check the output of `echo $PATH`

**Comment by nhorton** [comment]
`which docker` => `/usr/bin/docker`
`docker compose version` => `Docker Compose version dde0213`
`which docker-compose` => `/usr/local/bin/docker-compose`
`docker-compose version` => `Docker Compose version dde0213` (yes, the same version, not copy-paste error)

I am using a custom docker image but it starts from yours and just adds a couple things.. the install-gitpod script is just adding stuff like the gcp client.

dockerfile follows:
```
FROM gitpod/workspace-full
USER gitpod
# Set our current ruby
ENV RUBY_VERSION=3.1.3
ENV BUNDLER_VERSION=2.3.22
# Install system dependancies
COPY /bin/build/install-gitpod.sh ./
RUN sudo ./install-gitpod.sh
# Install arrow
COPY /bin/build/install-arrow.sh ./
RUN sudo ./install-arrow.sh
# Update ruby
RUN _ruby_version=ruby-${RUBY_VERSION} \
  && bash -lc "rvm install ${_ruby_version} && \
  rvm use ${_ruby_version} --default && \
  rvm uninstall 3.1.2"
RUN bash -lc "gem install overcommit"
RUN bash -lc "gem install bundler -v '${BUNDLER_VERSION}'"
```

Note again though that I also ran the version check in a different gitpod that was just opening a default Gitpod workspace, and I got the same version. That one was just opening my personal dotfiles repo, with zero customization to gitpod itself.

**Comment by nhorton** [comment]
@aledbf - any thoughts here?

**Comment by nhorton** [comment]
Hello?

**Comment by akosyakov** [comment]
I'm trying to reproduce but cannot:
- gitpod.io#https://github.com/akosyakov/compose-http-error-rep to create a gitpod workspace and start nginx proxy in docker-compose
- open it in VS Code Desktop, and make sure that port 8080 is local forwarded
- whenever I do `curl localhost:8080` on my local machine, i see a log record in the workspace

Does it work for you?

**Comment by akosyakov** [comment]
I also wonder whether you can observe only via local forwarding? What happens when you use exposed URL from VS Code Browser or curl on localhost inside the workspace. Could it be related to SSH setup on your machine not a docker at all?

**Comment by sansari** [comment]
@akosyakov This issue is affecting our entire team, and suddenly started a few days ago. As such, it's unlikely to be related to any SSH setup on our machines. I'm wondering if y'all have made any changes in the past 2 weeks that might cause requests to be forwarded differently?

**Comment by akosyakov** [comment]
@sansari Does it mean you can confirm that it only happens while going via local forwarding in VS Code Desktop? And does not happen otherwise, i.e. via exposed URL or localhost inside the workspace? Could you confirm please?

**Comment by akosyakov** [comment]
Hi @nhorton and @sansari,

We need some logs to help resolve your issue. Here's what you can do:

- Firstly, set "remote.SSH.logLevel" to "trace" in your VS Code Desktop settings.
- Then, pull the logs from the VS Code windows where you're having trouble. This guide shows you how: https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop
- Please also run the command ssh -G test.vss.gitpod.io and share its output.
- Finally, forward all this info through our support email. Don't forget to mention that it's for the IDE team.

Your help's appreciated. Thanks!

**Comment by ciaarraa** [comment]
Hi @akosyakov, I am also experiencing this issue. The app works as expected when I use VS Code in the browser but does not work when I use VS Code Desktop.

My `.gitpod.Dockerfile` is as follows 
```
FROM gitpod/workspace-mongodb:2023-05-08-21-16-55
USER gitpod

ENV RUBY_VERSION=3.2.1
ENV BUNDLER_VERSION=2.3.22

#use ruby install
RUN wget https://github.com/postmodern/ruby-install/releases/download/v0.9.1/ruby-install-0.9.1.tar.gz \
&& tar -xzvf ruby-install-0.9.1.tar.gz \ 
&& cd ruby-install-0.9.1/ \ 
&& sudo make install

# install ruby 
RUN ruby-install ruby $RUBY_VERSION

#install bundler
RUN bash -lc "gem install bundler -v '${BUNDLER_VERSION}'"
```

I'll forward my VSCode Desktop logs to your support team as described above.

**Comment by akosyakov** [comment]
We released a new version of VS Code Desktop (0.0.144) extension which collect better SSH tracing and try to improve detection of stale connections. Could you upgrade and try please? 🙏 if the situation still happens please follow https://github.com/gitpod-io/gitpod/issues/18097#issuecomment-1645387589

**Comment by nhorton** [comment]
Updated!

**Comment by akosyakov** [comment]
@nhorton How was your experience?

**Comment by mustard-mh** [comment]
Hey @nhorton @sansari @ciaarraa thank you for your reports and supporting 🙏 ! We released a fixing on VSCode Gitpod Extension version `0.0.150`, could you upgrade and try it out?

I'm going to close this issue, feel free to open again if you still have problem

**Comment by nhorton** [comment]
Apologies - I was on vacation. I think this is indeed fixed! I will report if I see it again, but seems good!

**Comment by Gautam-04** [comment]
I am having the same issues in running the gatsby site . The setup is complete but browser is just loading and neither stopping nor giving any input

**Comment by akosyakov** [comment]
> I am having the same issues in running the gatsby site . The setup is complete but browser is just loading and neither stopping nor giving any input

Did you upgrade to latest Gitpod extension on VS Code Desktop? If you are on latest and don't help so please share more logs of affected window following https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop
