### ISSUE TITLE
Add an alias for `hostname`

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#181]
I propose adding `host` (maybe `h`) as an alias for the `hostname`. 

So lazy developers can do:
```
yarn --cwd ./examples/browser start --host 0.0.0.0 --port 3000
```
Instead of:
```
yarn --cwd ./examples/browser start --hostname 0.0.0.0 --port 3000
````

**Comment by svenefftinge** [comment]
Yes, we should do that in theia.
For Gitpod we were thinking about rewriting the header even, that all externally incoming calls look like they were coming from localhost. We have this kind of inconvenience for other projects/dev servers too.

**Comment by meysholdt** [comment]
see #157 for host-header rewrite.
