### ISSUE TITLE
Ctrl + ` doesn't toggle the terminal window

### ISSUE THREAD

**Issue by j-james** [gitpod-io/gitpod#1810]
### Describe the bug
When the terminal is focused, pressing ctrl + \` makes a new terminal instance rather than minimizing the existing one. When the terminal is not focused, pressing ctrl + \` also makes a new terminal instance rather than focusing the existing one.

### Steps to reproduce
Open up a project in Gitpod, and press ctrl + \` twice.

### Expected behavior
The expected behavior would be:
- If the terminal is not focused, focus it
- If the terminal is focused, collapse it down

### Additional information
N/A

### Example repository
https://github.com/j-james/2020-InfiniteRecharge

**Comment by corneliusludmann** [comment]
Why do you expect that `` Ctrl + ` `` focuses an existing terminal? In the `Terminal` menu, the entry `New Terminal` is bound to the shortcut `` Ctrl + ` ``. Thus, it works as I would expect it.

**Comment by j-james** [comment]
Perhaps it's just because I'm coming from VS Code proper, but I'd expect there to be a default shortcut to raise / lower the terminal window. Particularly when working in a browser window with limited space, I find myself switching between running tests in the terminal and writing / reading full screens of code far more often than needing to open a new terminal because the current one is busy with a job.

(although I filled it out as a bug at first, I suppose this is more of a feature request.)

**Comment by corneliusludmann** [comment]
There is `Ctrl + J` that toggles the bottom panel (hit `F1` and search `Toggle Bottom Panel`).
