### ISSUE TITLE
Unable to load workspace

### ISSUE THREAD

**Issue by abhikulshrestha22** [gitpod-io/gitpod#1812]
### Describe the bug
Many times a day the workspace will not start. it shows error connecting to the server

### Steps to reproduce
Keep working for some time on gitpod. and after sometime, it gives alert on workspace page about "error connecting to the server" and also shows offline on the workspace.

### Expected behavior
It should not get timed out so frequently.

### Additional information
Error shown is something like this . Please check attached image for more info.
"Error: TIMEOUT
    at e._handleTimeout (https://gitpod.io/list-workspaces.js:78:7581)
    at https://gitpod.io/list-workspaces.js:78:7461"
<img width="1528" alt="Screenshot 2020-09-06 at 7 33 27 PM" src="https://user-images.githubusercontent.com/9465229/92327610-75b8ab80-f078-11ea-863b-cc0240b47c23.png">

**Comment by svenefftinge** [comment]
Can you share where you are in the world and whether you are using any proxies?

**Comment by abhikulshrestha22** [comment]
@svenefftinge  I am in India. And no I am not using any proxies.

**Comment by sr229** [comment]
Unfortunately I think this is a ISP issue rather than Gitpod's issue, contact your ISP since they may be dropping long lived sockets @abhikulshrestha22

**Comment by abhikulshrestha22** [comment]
@sr229 I changed the network and still faced the issue. It happens mostly after keeping the tab open for hours.

**Comment by akosyakov** [comment]
Did you find a workaround? Does restarting the browser helps or cleaning cookies?
