### ISSUE TITLE
Allow custom named ssh keys instead of specifically defined ones

### ISSUE THREAD

**Issue by Natetronn** [gitpod-io/gitpod#18129]
## Is your feature request related to a problem? Please describe

I spent a lot of time debugging ssh to finally find a note in a blog post about using only specifically named ssh keys. Based on said blog post, I realize this may be a limitation of VS Code, but I'm hoping there is a work around.

## Describe the behaviour you'd like

I'd like to create ssh keys where I can use a custom name, this to help distinguish one key from another.

## Describe alternatives you've considered

Please add a note to the [main ssh docs](https://www.gitpod.io/docs/configure/user-settings/ssh) that custom named ssh keys don't work and link to or list names which do work, as described in [this blog post](https://www.gitpod.io/blog/vscode-desktop-ssh-updates#ssh-gateway-access-using-an-uploaded-public-key-recommended).

Or if there is a way to add a custom named ssh key using config file (?) please offer that as an alternative.

## Additional context

![ssh-keys](https://github.com/gitpod-io/gitpod/assets/582149/35a348c0-d77d-4876-bdb8-3d60510a6fd3)

**Comment by akosyakov** [comment]
We are going to introduce a new connectivity mode which does not require SSH keys for VS Code Desktop. @Natetronn I can enable an experiment for you, is it alright? This mode works in any network and use one time generated secret for each workspace start instead of keys without requiring any configuration from a user side.

**Comment by Natetronn** [comment]
@akosyakov thanks for the reply, Anton! That sounds interesting. Sure, happy to be a part of any experiments :-D
