### ISSUE TITLE
/etc/php/7.4/cli/php.ini:

### ISSUE THREAD

**Issue by flamecopper** [gitpod-io/gitpod#1813]
How can I edit this file?

I want to set the expose_php = off

But it says permission denied.

**Comment by svenefftinge** [comment]
You need root privileges which you only have during docker build.
So you'd need to [add a `.gitpod.Dockerfile`](https://www.gitpod.io/docs/config-docker/#configure-a-custom-docker-image) and either du chmod on that file or change the file during the build.

**Comment by flamecopper** [comment]
Hi there,

Can I confirm the following steps are correct:

`image:
  file: .gitpod.Dockerfile`

`FROM gitpod/workspace-mysql

USER root

# Install required dependencies
RUN true \
	&& apt-get update \
	&& apt-get -y install \
		apache2 \
		php \
		libapache2-mod-php \
		php-mysql \
		php-curl \
		php-gd \
		php-mbstring \
		php-xml \
		php-xmlrpc

# Do something
RUN printf '%s\n' "include /workspace/apache/apache.conf" > /etc/apache2/apache2.conf
RUN printf '%s\n' ". /workspace/apache/envvars" > /etc/apache2/envvars

# Do something
RUN addgroup gitpod www-data

# Allow gitpod group to edit php backend
RUN true \
	&& chown -R root:gitpod /etc/php \
	&& chmod -R g+rw /etc/php`

Stop and Start the workspace again.

**Comment by flamecopper** [comment]
I was reading some where it says:

You need to open a new gitpod instance so that it rebuilds the environment.

**Comment by flamecopper** [comment]
Hi there,

I have a seperate question.
Is there a way to rebuild the entire workspace without having to clone a workspace?
I already edited the .gitpod.Dockerfile

**Comment by svenefftinge** [comment]
You need to push the change to your `.gitpod.yml` and `.gitpod.Dockerfile` to a branch. And then start a fresh workspace using that branch as a context URL. I.e. go to the branch on GitHub and prefix the URL with `gitpod.io#`.
