### ISSUE TITLE
Gitpod is saving changes to my code but not displaying them in teh preview

### ISSUE THREAD

**Issue by jimbobding** [gitpod-io/gitpod#1815]
### Describe the bug
When I save my changes in gitpd and then refresh my preview page the changes re not dispayed
### Example repository
This is occurring throughout the workspace

**Comment by svenefftinge** [comment]
Gitpod is just showing what the webserver you started in your workspace serves. If you can share your project we wight be more helpful, you probably forgot to build something or so?
