### ISSUE TITLE
preview - support 302 redirects

### ISSUE THREAD

**Issue by tekumara** [gitpod-io/gitpod#1816]
When I preview an https URL that responds with a 302 redirect, the redirect isn't followed and instead I see:

```
8888-c6ebb9be-ff6d-4fab-9b5f-804ec730f29e.ws-us02.gitpod.io refused to connect.
```

If I open the https URL in the browser, the browser correctly redirects me.

Example repo:

https://github.com/tekumara/gitpod-jupyter

**Comment by corneliusludmann** [comment]
Thanks for reporting.

@akosyakov: Could you have a look?
