### ISSUE TITLE
Determine "Total Cost of Ownership" (TCO) for Gitpod Self-hosted on GCP and AWS

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#1818]
Currently we offer an easy way to install Gitpod Self-Hosted on [GCP](https://www.gitpod.io/docs/self-hosted/latest/install/install-on-gcp-script/) and [AWS](https://www.gitpod.io/docs/self-hosted/latest/install/install-on-aws-script/) but make no statement about the TCO - mainly because in the past that greatly varied with your config choices. It's also interesting for users how that relates to the number of active users of that installation.
Since the last release changed quite some things there might be some low-hanging fruits to reduce those numbers without too much effort.

### TODO:
 - verify the TCO for GCP/AWS in test installations
 - try to reduce it
 - update docs, including explanation how the numbers related to additional users (maybe break down into base cost + GPh)

Related community questions:
 - https://community.gitpod.io/t/pricing-of-gitpod-in-aws/1795
 - https://community.gitpod.io/t/estimate-self-hosting-costs-on-google-cloud/1769/3

**Comment by csweichel** [comment]
Instead we should document the currently high cost of GPSH clearly
