### ISSUE TITLE
[Docs] Make clear that you need to create a new workspace (instead of restart the workspace) after adding a .gitpod.Dockerfile

### ISSUE THREAD

**Issue by henno** [gitpod-io/gitpod#1821]
### Describe the bug
According to documentation it should be possible to install tools via dockerfile. For example MongoDB.

### Steps to reproduce
1. Create a gitpod workspace with Github
2. Add the following to .gitpod.yml
```
image:
  file: .gitpod.dockerfile
```
3. Add the following to .gitpod.dockerfile to install Mongo
```
FROM gitpod/workspace-full

# Install mongodb
RUN sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
RUN echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
RUN sudo apt-get update \
 && sudo apt-get install -y mongodb-org \
 && sudo apt-get clean \
 && sudo rm -rf /var/lib/apt/lists/*
RUN sudo mkdir -p /data/db \
 && sudo chown gitpod:gitpod -R /data/db

```
4. Commit and push the changes
```
git add .
git commit -m "test"
git push origin master
```
5. Stop and start the workspace
`Workspace > Stop workpsace`

### Expected behavior
Typing mongod on command line finds launches mongo.

## Actual behaviour
Typing mongod on command line says
`bash: mongod: command not found`

**Comment by corneliusludmann** [comment]
It's important that you don't just stop and start your workspace but create a new workspace from this repo.

When you click on the `Start` button (on gitpod.io/workspaces or on the modal that appears after the workspace has stopped) it just starts the same workspace container again. You can resume your work exactly where you stopped the workspace.

However, when you open gitpod.io#https://github.com/your/repo in your browser, a fresh workspace will be created with your custom Dockerfile.

Please let me know if this helps.

**Comment by henno** [comment]
Thanks! After many days of trial and error by me and then also countless trys by other persons that I delegated this task, we now managed to get it working.

"It's important that you don't just stop and start your workspace but create a new workspace from this repo."

This sentence is critical. This information is not explicitly given anywhere. Most importantly it's missing from https://www.gitpod.io/docs/config-docker/. Had it been there, it would have saved hours of frustrations from multiple persons from our team.

**Comment by PirateBread** [comment]
My understanding is that GitPod workspaces are tied to a git commit ID. If you understand that it makes sense that you need to create a new workspace if you want to reference another commit ID.

**Comment by flamecopper** [comment]
Had it been there, it would have saved hours of frustrations from multiple persons from our team. >> same here for me, I supported adding it in.

**Comment by akosyakov** [comment]
Docs are open-sourced: https://github.com/gitpod-io/website/tree/master/src/docs PRs are welcomed!
