### ISSUE TITLE
Frontend projects not loading on gitpod setup.

### ISSUE THREAD

**Issue by surajthapliyal** [gitpod-io/gitpod#18282]
### Bug description

I have a frontend project setup using gitpod. 
When I try to open localhost:3000 or any of my project's links, the page stays loading all the time, as the api requests are not going from the frontend.

### Steps to reproduce

Just open the frontend project.

**Comment by filiptronicek** [comment]
Hi there @surajthapliyal, 
could you please share an example repository for which this happens? Sharing any screenshots would also be super helpful 🙏

**Comment by surajthapliyal** [comment]
@filiptronicek 

<img width="783" alt="image" src="https://github.com/gitpod-io/gitpod/assets/72781278/04a8c8ff-1121-4e02-a4b5-62e8696253d8">

remains loading all the time, and no other requests proceeds after this.

<img width="488" alt="image" src="https://github.com/gitpod-io/gitpod/assets/72781278/2de15cd4-444d-4c57-831c-1b8e1055f950">

**Comment by akosyakov** [comment]
It requires a reproducible repo to continue. Unfortunately it is not reproducible just on any frontend project.

**Comment by radixs** [comment]
I am having a similar issue, sorry cannot give the private repo I am working on, just some hints: For me, just when I open up my pod it all works fine. I go do some thing in another pod and then when I go back to the frontend pod it is either VERY slow or is unresponsive at all. The pod in workspace page shows up and green but it feels like it is going into a sleep mode after a while and fails to get up when the user starts again interacting with it. Powering the pod down and back again makes it work fine for a while again. Me and my workmate experienced this and it started like last week. We tried starting another workspace but it did not help.
The slowness can be experienced both in VScode terminal and on the browser when opening any page.
Another weird thing is that when I go into network tab in dev tools then it seems the initial request that fetches up the page works fine but when it wants to load app.js file then it fails - not always though, sometimes it does not load anything.

**Comment by akosyakov** [comment]
@radixs Could you clarify you are using Docker? Or you are running K8S inside a Gitpod workspace? Is it something like https://github.com/gitpod-io/gitpod/issues/18097?
