### ISSUE TITLE
Python 3.8.4 Update!

### ISSUE THREAD

**Issue by Deep-py** [gitpod-io/gitpod#1828]
**Python 3.8.4** is here why the ide is still **3.8.3**??

**Comment by jankeromnes** [comment]
Hi @Deep-py! Hmm, good question. Normally we should receive an automated Pull Request like [this one](https://github.com/gitpod-io/workspace-images/pull/246/files) to auto-update the Python version.

I would say either Pyenv doesn't know about `3.8.4` yet, or there is a bug in our auto-update system (autofix.dev). I can investigate more tomorrow.
