### ISSUE TITLE
HTTP 403 "You've been blocked." during register/first login

### ISSUE THREAD

**Issue by gnfalex** [gitpod-io/gitpod#18305]
### Bug description

Greetings.
I'd try to register on Gitpod. 
After I fill form and click the "Continue" button on the "Tell us more about you" page, nothing happens. 
Through the browser "Developer Tools", i can see that a POST request has been sent - which has received an HTTP 403 response with the JSON '{"code":"permission_denied","message":"You've been blocked."}'. 
And now i'd stuck on page "Welcome to Gitpod. You are one step away from shipping software faster.". I even can't return to main page.
After deleting all cookies, i was able to sign up via BitBucket - but I can't attach my GitHub account because I'm stuck in that loop again...
Can You explain the reason for blocking this account?
Is there anything you can do to prevent silently getting stuck in the loop in case of such blocking?
Best regards

### Steps to reproduce

It's a account specific problem?
1. Open https://gitpod.io/
2. Fill all data 
3. After last "Continue" button nothing happens.

**Comment by axonasif** [comment]
Hi, you can send us a message through https://www.gitpod.io/contact/support
