### ISSUE TITLE
InviteId empty in email

### ISSUE THREAD

**Issue by mattinannt** [gitpod-io/gitpod#18311]
### Bug description

I just created a team on gitpod.io and received this email `Invite your team mates to team 'Formbricks' on Gitpod` with an `inviteId=undefined`:
<img width="685" alt="Screenshot 2023-07-19 at 17 48 05" src="https://github.com/gitpod-io/gitpod/assets/675065/17e74c27-15fd-4038-be3e-d8c0ccfda4b2">

### Steps to reproduce

- Add a new team on gitpod.io
- Wait for the email asking you to invite your team mates 😎

### Expected behavior

the actual inviteId filled out

**Comment by svenefftinge** [comment]
Thanks for the report. This is fixed with https://github.com/gitpod-io/gitpod/pull/18317.
