### ISSUE TITLE
PHP Server

### ISSUE THREAD

**Issue by flamecopper** [gitpod-io/gitpod#1835]
Hi there,

Is there a in built php server on the gitpod.
When I browser the .php extension file it will launch an preview on the browser?

**Comment by AlexTugarev** [comment]
Hi @flamecopper! 

You'll find an example for a symfony application here: `https://github.com/gitpod-io/symfony-demo`. It's based on the [workspace-full image](https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile) which pre-installs php.

Just open `https://gitpod.io/#https://github.com/gitpod-io/symfony-demo` in a new tab to try it out. 

If you need to run apache as well, you might want to have a look at `https://github.com/gitpod-io/apache-example`
