### ISSUE TITLE
Extensions unable to retrieve secrets through the Secret Storage API in VS Code v1.80.1

### ISSUE THREAD

**Issue by abeatrix** [gitpod-io/gitpod#18364]
### Bug description

Hey team 👋 

Users of [our VS Code extensions](https://marketplace.visualstudio.com/items?itemName=sourcegraph.cody-ai) on the self-hosted version of GitPod are reporting issues where extensions in their GitPod instance cannot retrieve or store tokens through the VS Code API after upgrading to VS Code version 1.80.1.
These issues occur for all the users on the affected GitPod instance, but there are no related logs in the console, server, or output channel. 
Users on non-GitPod instances do not see the same issue, so we suspect this issue was caused by GitPod.
I have also filed an issue with the VS Code team, but I wanted to check if your team has any advice for the GitPod users on the next steps to unblock them. 

Please let us know if you need any other details on the behavior or affected user base.

### Steps to reproduce

- Sign into any extensions that store access tokens to secret storage via the Secret Storage API
- Reload VS Code
- You will now be signed off and require signing in again because the extension unable to retrieve the token through the Secret Storage API

### Expected behavior

Users will be kept signed in when workspace / editor is reloaded

### Anything else?

VS Code Version: 1.80.1
OS Version: Linux Rocky

**Comment by jeanp413** [comment]
@abeatrix This is using vscode desktop correct? then if I'm not mistaken credentials are always stored on user machine so it should be a vscode bug, they've been doing some refactor removing the usage of keytar internally 🤔

**Comment by abeatrix** [comment]
@jeanp413 Hello! They have `vscode-server` set up and the issue can be reproduced on both vs code desktop and vs code web. 
I noticed linux users are reporting a similar bug in the VS Code repo but the[ suggested workaround ](https://github.com/microsoft/vscode/issues/187338#issuecomment-1640112938)isn't working for them, any advice for us 👀 ?

**Comment by akosyakov** [comment]
>the self-hosted version of GitPod

@jeanp413 maybe something with tokens verification in last changes? Did we test new workspace management UI on self-hosted?

@abeatrix ask them try to downgrade Gitpod extension in VS Code Desktop and see which version works. There were introduced new UI which require new APIs. Self-hosted in the maintenance mode and probably don't have them. We do usually try to ensure backward compatibility, but maybe overlooked this time.

**Comment by jeanp413** [comment]
@akosyakov it's not related to our extension, it's about cody-ai extension

@abeatrix in vscode browser is a known limitation to have to login on a new workspace as it stores credentials per origin, for vscode desktop I don't have a linux machine currently to try to reproduce, you can ask to try vscode-insiders or downgrade to vscode 1.79 for a quick workaround

**Comment by abeatrix** [comment]
@jeanp413 @akosyakov thank you so much! I'll pass on the info to them.

If downgrading fixes the issue for them, I assume that confirms it's a vs code issue and I can close this one?

**Comment by jeanp413** [comment]
> If downgrading fixes the issue for them, I assume that confirms it's a vs code issue and I can close this one?

yes 👍
