### ISSUE TITLE
Does GitPod Self-Hosted support GitLab community edition?

### ISSUE THREAD

**Issue by PirateBread** [gitpod-io/gitpod#1836]
I have a very tightly controlled network where we run our own instance of GitLab community edition.

Does GitPod either free or paid, support accessing a GitLab community edition instance?

Thanks

**Comment by sr229** [comment]
IIRC the self-hosted offering allows such since your use case is a air-gapped network.

**Comment by corneliusludmann** [comment]
Sure, you could add your local GitLab instance as auth provider. See https://www.gitpod.io/docs/self-hosted/latest/install/oauth/
