### ISSUE TITLE
Gitpod Button missing

### ISSUE THREAD

**Issue by gustavomm19** [gitpod-io/gitpod#18375]
### Bug description

The github layout was updated and now there is not gitpod button 
![image](https://github.com/gitpod-io/gitpod/assets/47191295/1565b0dc-dc8d-4aa1-8bbd-37b2866e36cc)

### Steps to reproduce

Enter to any repository, and you will notice the new design. The buttons where move and now there is no gitpod button

**Comment by pattacini** [comment]
>The github layout was updated and now there is not gitpod button

More specifically, the <kbd>New Repository Overview</kbd> is a feature preview users may opt-in, which is not the standard layout yet.

That said, I can confirm that the Gitpod green button doesn't get displayed in the new repo overview and it'd be great if you could fix this up.

**Comment by gtsiolis** [comment]
Resolved in https://github.com/gitpod-io/browser-extension/pull/80. Thanks for reporting, @gustavomm19! 🍊

**Comment by pattacini** [comment]
Thanks heaps for being so fast!
