### ISSUE TITLE
Random refresh and lost icons

### ISSUE THREAD

**Issue by kellySmi** [gitpod-io/gitpod#18374]
### Bug description

The UI will refresh at random times during development and after the refresh the icons on the left side of the page are missing.

### Steps to reproduce

None, there is no noticeable action that indicates the page is about to refresh. Once the icons disappear refreshing the page does nothing to restore them.

### Expected behavior

I would expect the icons on the left to always be there.

**Comment by loujaybee** [comment]
Thanks for raising @kellySmi , where in the product do you see this? In one of the IDE or terminal integrations? Or in the browser web application? Do you have a screenshot or more details?

**Comment by akosyakov** [comment]
Please check out devtools for broken requests in the network tab and reasons 🙏

**Comment by kellySmi** [comment]
<img width="183" alt="Screenshot 2023-07-27 at 12 56 19 PM" src="https://github.com/gitpod-io/gitpod/assets/38441299/2a5d517e-b373-4c53-a81b-983e82bfa7fa"> Here is a screenshot of the side panel when this occurred.
