### ISSUE TITLE
504 Error From Gitpod loading project

### ISSUE THREAD

**Issue by gomyar** [gitpod-io/gitpod#1839]
### Describe the bug
Attempted to start a project from github.

Sorry, something went wrong 😓
Error 504

### Steps to reproduce
Login with Github and start a project

### Expected behavior
The project should load

### Additional information
Chrome Version 85.0.4183.83 (Official Build) (64-bit)

### Example repository
https://github.com/gomyar/metaphor

**Comment by corneliusludmann** [comment]
Thanks for reporting. Is this reproducible or has it occurred once?

**Comment by gomyar** [comment]
Seems pretty reproducible - that or the service loads very slowly.

**Comment by corneliusludmann** [comment]
Could you please check if it still occurs, @gomyar? We fixed a slow server instance ...

**Comment by gomyar** [comment]
This appears to be working normally again. Thanks guys.
