### ISSUE TITLE
Please add some onbeforeunload handler in the workspace view to avoid unexpected tab exit

### ISSUE THREAD

**Issue by erikmd** [gitpod-io/gitpod#18416]
## Is your feature request related to a problem? Please describe

Currently using Gitpod in the browser is annoying when (like me) the `Ctrl+w` shortcut is wired in my hands, both in emacs and shell context…

Indeed, this closes the window.

Beyond my particular case, I believe many users also get annoyed when they mistype `Ctrl+w` and close their workspace tab.

## Describe the behaviour you'd like

As suggested in https://github.com/gitpod-io/gitpod/issues/17724#issuecomment-1633234723

I would like to request some closing confirmation *in all Gitpod browser editors*,
→ with some JS code such as `window.onbeforeunload = function(e) {e.preventDefault(); return false;}`

and just undo this setting at workspace stop (e.g. `gp stop`, leading to page Stopped / Go-to-Dashboard)
→ with some JS code such as `window.onbeforeunload = null;`

## Describe alternatives you've considered

One might otherwise try to disable the `Ctrl+w` shorcut in the browser, however as noted in
https://github.com/gitpod-io/gitpod/issues/17724#issuecomment-1633223284
this is neither browser-cross-compatible nor builtin in general, one needs to install 3rd-party extensions to do this.

So, adding an onbeforeunload handler looks way simpler, and fully works.

## Additional context
N/A

**Comment by akosyakov** [comment]
VS Code already does it by default. If you want to have it always please change your settings "application.confirmExit": "always" otherwise it happens only or dirty changes.

**Comment by erikmd** [comment]
So I believe you could reopen this issue :)

**Comment by akosyakov** [comment]
Sorry, yes makes sense, we should support something like that there.

**Comment by erikmd** [comment]
Thanks @loujaybee for adding this label :)

— Actually I noticed the issue with emacs, so maybe it could be tagged `editor: emacs`  as well?

Thanks for your time!

**Comment by erikmd** [comment]
Dear @loujaybee,

Do you think this would help if I'd try to open a PR to implement this small (but very useful IMHO) enhancement?

Of course, I might need a bit of guidance at first, to spot the main components to change…

**Comment by erikmd** [comment]
Hi! Please do not close, I do think this feature request is worth it to be implemented.

**Comment by erikmd** [comment]
Please do not close, this feature request should definitely be addressed! Feel free to start implementing it, otherwise I may try to open a PR in a couple of weeks.
