### ISSUE TITLE
Touch scrolling also for Explorer and Markdown Preview on ChromeOS

### ISSUE THREAD

**Issue by koppor** [gitpod-io/gitpod#1842]
### Describe the bug

I'm trying to integrate GitPod in a Java project (https://github.com/koppor/jabref/pull/446).

I am on the following environment:

```yaml
Chrome OS Version: 85.0.4183.84 (Offizieller Build) (64-Bit)
Chrome: Version 85.0.4183.84 (Offizieller Build) (64-Bit)
```

I have opened gitpod.io in a tab.

I put the finger down in the Java editor and move the finger down. The text scrolls up. When doing the same gesture in the following "viewers", nothing happens

- "EXPLORER"
- Markdown preview
- Output, e.g., EditorConfig, Language Support for Java

### Steps to reproduce

1. Start your Chromebook (or Chromium OS in an emulator - not tested)
2. Open arbitrary GitPod.io project with many files (so that a scrollbar appears)
3. Try to scroll in the "EXPLORER"

### Expected behavior

Scrolling works

### Additional information

--

### Example repository

https://github.com/koppor/jabref/tree/gitpod-setup

**Comment by sr229** [comment]
Can confirm the issue in Chromium OS 87.

**Comment by koppor** [comment]
Note that this was one reason that I moved away from Chrome OS. I am back on Windows 10 again. Thus, I cannot (properly) test.
