### ISSUE TITLE
Git LFS still not working

### ISSUE THREAD

**Issue by cfoust** [gitpod-io/gitpod#18458]
### Bug description

I would expect that a repository that uses Git LFS would "just work". It seems that this was working at some point, but my repository broke at some unknown time in the recent past without any action on my part. In addition, adding a `git lfs pull` to my `.gitpod.yml` [didn't work either](https://github.com/cfoust/sour/blob/main/.gitpod.yml#L11).

### Steps to reproduce

Step 1. Have a repo with assets in Git LFS.
Step 2. Open it in Gitpod.
Step 3. You will still have to `git lfs pull`.

### Workspace affected

 cfoust-sour-dl0jucoi0h1,  cfoust-sour-eqll45kibty

### Expected behavior

Git LFS objects should be pulled automatically at clone time.

### Example repository

https://github.com/cfoust/sour

**Comment by axonasif** [comment]
Hi @cfoust,

I just tried myself and I didn't need to manually rerun the `git lfs` command, can you please check again?

<img width="577" alt="Screenshot 2023-08-18 at 7 16 45 AM" src="https://github.com/gitpod-io/gitpod/assets/39482679/26185489-b713-471a-b20c-a2e39e6c9708">

**Comment by cfoust** [comment]
Appears to be working now, strange 🤔 That may be because I added it to my `.gitpod.yml`. Anyway, thank you!
