### ISSUE TITLE
Consider applying for GitHub Discussions Beta

### ISSUE THREAD

**Issue by sr229** [gitpod-io/gitpod#1847]
Currently some of the issues here are better off in the Discussions feature which is curretly in Beta. Since we're quite a large project I think GitHub would approve it considering the scale of the project merits such feature to be enabled here.

**Comment by wulfthimm** [comment]
We have a community site for discussions https://community.gitpod.io/.

**Comment by sr229** [comment]
Honestly I think people would like to use GitHub itself for this kinds of community discussions since no one would like to make a seperate account just to engage with community if it's in GitHub at the moment - since GitHub has been opening up Discussions in limited beta.

**Comment by akosyakov** [comment]
https://community.gitpod.io/ is using GItHub OAuth. As for now GitHub discussions have very limited features, like missing private communications and so on.
