### ISSUE TITLE
Cannot start workspace

### ISSUE THREAD

**Issue by dclements** [gitpod-io/gitpod#18476]
### Bug description

When  connecting via VS Code in the browser the workspace gets stuck in "starting."  It will not move on past that point.   It will stay open for  up to about 30 minutes if I don't do anything else. 

I can log into the system via ssh but all of the `code` commands (except `--help`) block indefinitely. I can reproduce it on versions 1.81 and 1.82 (unstable). 

I attempted to remove `/workspace/.vscode-remote/extensions` and reboot, they returned on the next load but otherwise it didn't do anything else. 

Follow on to support request id cnv_ljpq5l6

### Steps to reproduce

1. Open any workspace in my system in the browser (or in UCoW) using VS Code 1.81 or 1.82 (unstable)

This is reproducible on all workspaces on my account, including new ones that I have never opened before, regardless of if there is a prebuild, or a project, or a gitpod configuration.  I can reliably reproduce this in Safari, Chrome, and UCoW on an iPad running 16.3.1. 

### Workspace affected

larpconnect-njal-ljp0lc2v5s5

### Expected behavior

It opens the workspace.

### Example repository

I can reliably reproduce it with any repository. https://github.com/w3c/json-ld-api  for example.

**Comment by dclements** [comment]
Additional information/data:

This is the `ps afx`  result:

```shell
    PID TTY      STAT   TIME COMMAND
      1 ?        S<l    0:00 supervisor init
     34 ?        S<l    0:05 supervisor run
     83 pts/0    Ss+    0:00  \_ /bin/bash
    574 ?        S      0:00  \_ sshd: gitpod [priv]
    576 ?        S      0:00  |   \_ sshd: gitpod@pts/1
    577 pts/1    Ss     0:00  |       \_ -bash
   2795 pts/1    R+     0:00  |           \_ ps axf
   2796 pts/1    S+     0:00  |           \_ less
   2512 ?        S<     0:00  \_ sh /ide/bin/gitpod-code --log=info --install-builtin-extension gitpod.gitpod-theme --install-builtin-extension github.vscode-pull-request-github --port 23000 --host 0.0.0.0 --without-connection-token --server-data-dir /workspace/.vscode-remote --do-not-sync --start-server
   2521 ?        S<l    0:01      \_ /ide/node /ide/out/server-main.js --log=info --install-builtin-extension gitpod.gitpod-theme --install-builtin-extension github.vscode-pull-request-github --port 23000 --host 0.0.0.0 --without-connection-token --server-data-dir /workspace/.vscode-remote --do-not-sync --start-server
```

(removing the installed extensions from the output since they don't seem to matter)

Executing `kill`on the `gitpod-code` leads to it being spun up again. 

The following output shows up on a recurring basis in `/var/log/gitpod/supervisor.log`:

```
time="2023-08-10T17:24:38.17123336Z" level=info msg="IDE is ready" ide=web serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:24:39.353862143Z" level=info msg="fetching from https://gitpod.io/configcat" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:24:39.359540182Z" level=info msg="config fetched but refusing to redirect from custom URL without forced redirection" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:25:39.35395966Z" level=info msg="fetching from https://gitpod.io/configcat" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:25:39.35884064Z" level=info msg="config fetched but refusing to redirect from custom URL without forced redirection" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:26:39.353948628Z" level=info msg="fetching from https://gitpod.io/configcat" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:26:39.358642688Z" level=info msg="config fetched but refusing to redirect from custom URL without forced redirection" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:27:39.354113776Z" level=info msg="fetching from https://gitpod.io/configcat" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:27:39.361680976Z" level=info msg="config fetched but refusing to redirect from custom URL without forced redirection" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:28:39.354100234Z" level=info msg="fetching from https://gitpod.io/configcat" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
time="2023-08-10T17:28:39.358605723Z" level=info msg="config fetched but refusing to redirect from custom URL without forced redirection" serviceContext={supervisor commit-57b237a656fd28f13469e4d0cac5a2c756175460}
```

**Comment by axonasif** [comment]
Hi @dclements, do you use dotfiles?

**Comment by jyr** [comment]
Hi!

I have same problem and minutes are billing (spending)

**Steps to reproduce**

1. Open any workspace in my system in the browser  using VS Code web 1.84.2 

**Workspace affected**

jyr-learnelixir-b97u4btrma2

**Expected behavior**

It opens the workspace.

**Example repository**

I can reliably reproduce it with any repository, too. https://github.com/jyr/learn-elixir

**Anything else?**

No response

**Comment by axonasif** [comment]
Hi @jyr. Could you attempt to create a workspace using a different browser? It's possible that the issue is related to your current browser settings or browser-extensions or even something like VPN/proxy.
