### ISSUE TITLE
Update media image

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#1849]
The current media image is outdated

<img width="600" alt="Bildschirmfoto 2020-09-14 um 08 26 39" src="https://user-images.githubusercontent.com/46345125/93051909-81523680-f665-11ea-85ba-8482b5089adc.png">

New media image:
![Media-image-structure](https://user-images.githubusercontent.com/46345125/93052003-ab0b5d80-f665-11ea-8a21-70f3ec3c264d.jpg)

**Comment by jankeromnes** [comment]
@nisarhassan12 Could you please also look into fixing this?

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/website/pull/755
