### ISSUE TITLE
We are having trouble parsing your context

### ISSUE THREAD

**Issue by flamecopper** [gitpod-io/gitpod#1850]
We are having trouble parsing your context
Error: Cannot read property 'sha' of undefined
Please file an issue if you think this is a bug.

**Comment by JesterOrNot** [comment]
I thought this was fixed. @flamecopper Could you provide the repo?

**Comment by corneliusludmann** [comment]
Without more context information / a repo link it's hard to say what the reason is. It could be that the `.gitpod.Dockerfile` that is referenced in your `.gitpod.yml` file not exist.

**Comment by JesterOrNot** [comment]
@corneliusludmann but wasn't the issue fixed? i.e. there should be a helpful error message now.

**Comment by corneliusludmann** [comment]
Don't think that this is already deployed.

**Comment by sr229** [comment]
I couldn't reproduce the issue. @flamecopper please provide more information and a repo so we can reproduce, this is one of your issues that has vague info that we can't work out the issue out of. Avoid **making** issues without giving substantial evidence that the issue exists. You're not giving us even a screenshot or an error stack.

**Comment by flamecopper** [comment]
Hi Gitpod-Io

this issues are quite common
I thought you should have know
by the time I try to troubleshoot the other issues and find workaround,
hands are already full..

**Comment by akosyakov** [comment]
@JesterOrNot @corneliusludmann Which fix do you mean?

@flamecopper a context is URL like: `gitpod.io#https://github.com/gitpod-io/gitpod/issues/1850`. Could you share it please?
