### ISSUE TITLE
Update meta description for gitpod.io

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#1851]
### Describe the bug

meta subscription is outdated
<img width="307" alt="Bildschirmfoto 2020-09-14 um 15 42 31" src="https://user-images.githubusercontent.com/46345125/93093435-f98a1d80-f6a0-11ea-9d0c-c342694f305f.png">

### Solution
meta title: `Gitpod - Dev environments built for the cloud `
meta description: `Gitpod streamlines developer workflows by providing prebuilt, collaborative development environments in your browser - powered by VS Code. `

**Comment by jankeromnes** [comment]
> `Gitpod - Dev environments build for the cloud `

I think you meant `Gitpod - Dev environments built for the cloud` (past tense)

Also, maybe we could even change that line to `Gitpod - Dev environments in the cloud` (makes it even easier to understand that the dev environment is in the cloud, and not some product that we've built for some purpose but it's not clear how to get the product).

**Comment by ChristinFrohne** [comment]
>I think you meant Gitpod - Dev environments built for the cloud (past tense)
of course thanks!

I'd stick with the sentence as we already have it, by that the messaging stays consistent. Also I like having "built" in it. That shows that Gitpod was always meant for the cloud and just pushed to it afterwards.

**Comment by jankeromnes** [comment]
@nisarhassan12 would you be interested in fixing this? 🙏
