### ISSUE TITLE
Connection refused when opening files from terminal

### ISSUE THREAD

**Issue by ajhalili2006** [gitpod-io/gitpod#18557]
### Bug description

I'm attempting to create GPG-signed commit from terminal since my GPG key are stored separately from the default `GNUPGHOME` for persistence between workspace restarts, but when I ran `git commit --signoff`, this happens:

```shell
gitpod /workspace/digital-garden (main) $ git commit --signoff
hint: Waiting for your editor to close the file... Unable to connect to VS Code server: Error in request.
Error: connect ECONNREFUSED ::1:23000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 23000
}
error: There was a problem with the editor '/ide/bin/remote-cli/gitpod-code --wait'.
Please supply the message using either -m or -F option.
```

### Steps to reproduce

1. Attempt to use either `code` or `gp open` in terminal to open a file.

### Workspace affected

andreijiroh-digitalgard-dcj0l1n4u00

### Expected behavior

Should opens `.git/COMMIT_EDITMSG` in the web editor to easily write the commit message

### Example repository

**Snapshot**: <https://gitpod.io#snapshot/a549e6b8-d71d-4f32-99ab-83b3eacb1954> (includes my GPG key at `/workspace/.gnupg` for setting `GNUPGHOME` and commit signing, although they do have passphrase for safety reasons)

### Anything else?

May or may not related to <https://www.gitpodstatus.com/incidents/d56gc7l95dh8>

**Comment by ajhalili2006** [comment]
Tried restarting the workspace, but issue persists.

**Comment by jeanp413** [comment]
@ajhalili2006 I can repro but only in vscode insiders, insiders can always have new bugs introduced as it updates daily from the changes done in the upstream vscode repo, could you try using vscode stable `1.81.1` in your preferences
![image](https://github.com/gitpod-io/gitpod/assets/25115070/17ae5a65-261e-4762-a9b8-d663ff7fcf16)

**Comment by ajhalili2006** [comment]
@jeanp413 Thanks for the note. I might update the issue description to reflect these findings.

**Comment by jeanp413** [comment]
Closing this for now, please comment if you see it in vscode stable
