### ISSUE TITLE
Running GitPod without an internet connection

### ISSUE THREAD

**Issue by ibilalkayy** [gitpod-io/gitpod#18556]
## Is your feature request related to a problem? Please describe
I started using GitPod and it's an amazing software in which I can work on my browser but one problem that I am facing is the internet. There are times when I don't have a strong internet connection then I get this message:

![Screenshot from 2023-08-19 13-33-57](https://github.com/gitpod-io/gitpod/assets/64713734/ce360ba0-be59-4635-bbfd-9d9e53778dc9)

## Describe the behaviour you'd like
GitPod should allow me to code normally even if I don't have an internet connection and the internet should only be required when I am pushing the code.

In this case, I won't have to worry about the Internet.

## Additional context
If this feature is not present then I would love to work on it. Please let me know.

**Comment by ajhalili2006** [comment]
I might also suggest using [`devbox`](https://jetpack.io/devbox) too if you also need hybrid dev env setups.

**Comment by ibilalkayy** [comment]
@axonasif @ajhalili2006 Isn't there any kind of solution in GitPod that will allow me to write code even if the internet is not working but if the internet is recovered, the remote server will be synced and we won't notice that weather we're working on the remote server or offline with this syncing process.

**Comment by axonasif** [comment]
@ibilalkayy not currently in the way you might want.
