### ISSUE TITLE
the workspace keeps running even if i delete it 

### ISSUE THREAD

**Issue by Noothan-am** [gitpod-io/gitpod#18580]
### Bug description

 workspace keeps running even after it is deleted before stopping it. due to which the credits get wasted.

### Steps to reproduce

run any project in gitpod and without stopping it just delete it. and check in billing section you will get the bug.

### Expected behavior

workspace should stop as soon as the app is deleted. even if it is not stopped by the user manually.

### Example repository

here the workspace not showing up as I deleted it already.
👇👇
![image](https://github.com/gitpod-io/gitpod/assets/100135382/cf8cfc7c-296b-4ec2-a103-3d3bee6ffa22)

but still it is shows the workspace is still running.
👇👇
![image](https://github.com/gitpod-io/gitpod/assets/100135382/089e9558-1ba0-45c9-b2f4-0197745e72bf)

**Comment by gtsiolis** [comment]
Hey @Noothan-am, the usage page is updated every 15 minutes, see notice on the header. Do you still see the workspace running?

**Comment by Noothan-am** [comment]
> Hey @Noothan-am, the usage page is updated every 15 minutes, see notice on the header.
> 
> Do you still see the workspace running?

yes it stops after 15 mins but till then credits are get wasted

**Comment by gtsiolis** [comment]
@Noothan-am The workspace should stop consuming credits when it stops. If you manually stop the workspace it should stop consuming credits and show up as stopped in the usage page consuming only credits for the minutes the workspace was up and running. If that's not the case this is a bug, could you provide steps to reproduce this?

Keep in min that workspaces will also stop when you don't have an open editor, see [relevant docs](https://www.gitpod.io/docs/configure/workspaces/workspace-lifecycle#:~:text=a%20paid%20plan.-,Editor%20or%20IDE%20Disconnect,-All%20inactivity%20timeouts):
> All inactivity timeouts are dependent on an active editor or IDE connection. Closing your Gitpod connected editor or IDE will reduce the workspace timeout to 5 minutes unless an explicit workspace inactivity timeout is set via user preference, or via the Gitpod CLI.
