### ISSUE TITLE
Send Pull request: Failed to submit - without explanation

### ISSUE THREAD

**Issue by ceefour** [gitpod-io/gitpod#1859]
### Describe the bug

Send Pull request: Failed to submit - without explanation

### Steps to reproduce

1. Open https://www.gitpod.io/docs/config-docker/
2. Click pencil icon, which will open https://gitpod.io/#https://github.com/gitpod-io/website/blob/master/src/docs/config-docker.md
3. Fork to own repository
4. Edit file, then commit
5. Push to own repository
6. Make pull request to gitpod-io/website
7. Failed to submit - see screenshot below

### Expected behavior

Sends pull request.

### Additional information

![image](https://user-images.githubusercontent.com/24123/93289617-0164d180-f809-11ea-9929-c58787f921df.png)

### Example repository

https://github.com/gitpod-io/website/blob/master/src/docs/config-docker.md

Forked to https://github.com/ceefour/website-1

**Comment by akosyakov** [comment]
@ceefour Could you check devtools next time whether there is any additional errors? We are displaying errors from GitHub but maybe something slipped away.
