### ISSUE TITLE
add `cursor.sh` IDE support to Gitpod

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#18619]
## Is your feature request related to a problem? Please describe

`cursor.sh` (https://www.cursor.sh) provides a full IDE experience in the browser, with support for extensions and theming. It would be great to have this as an option when connecting to a Gitpod workspace. 

## Describe the behavior you'd like

I would like the option to open a Gitpod workspace using `cursor.so` as the IDE, similarly to how local IDEs such as VSCode and JetBrains are supported now.

## Describe alternatives you've considered

The only alternative is using VSCode, but `cursor.so` has significant advantages with built-in GPT4 AI support for the whole project's codebase.

## Additional context

`cursor.so` is based on VSCodium so it should be straightforward to integrate it as a connection option. Please consider adding support for this great IDE alternative!

**Comment by shaal** [comment]
While this issue is not resolved, here's my manual process to connect Gitpod workspace to Cursor IDE -

- Open Gitpod workspace
- Open that workspace in your local VSCode
- In local VSCode - Install Live Share extension
- In Local VSCode - Start a new Live Share session (copy link)
- In Cursor.so - Install Live Share VSCode extension
- In Cursor.so - Join the session (paste link)

**Comment by worldofgeese** [comment]
I also use Cursor and assumed, since it's built on OSS VS Code, Gitpod integration would just work. Cursor is a game-changer for AI-assisted development. Big ➕ for this feature!

**Comment by mbrevoort** [comment]
@shaal wow, that workaround is involved but clever! 

We'll reach out to the folks at Cursor and see if they are interested in making this happen. I would love to see Gitpod expand our IDE support.

**Comment by mbrevoort** [comment]
Hi @shaal, this still includes some friction but I was able to manually connect over SSH link this:
https://www.loom.com/share/c029b3a942ba4d8f8a1b5707f83b1dcc

We'll see if we can streamline this. :)

**Comment by shaal** [comment]
@mbrevoort thank you! It does work.

To clarify, for whoever trying to follow the steps of connecting Gitpod workspace in Cursor through SSH:
(Open a repo in Gitpod)
* Go to https://gitpod.io/workspaces
* On right side of the environment that you enabled - click on the 3 vertical dots
* Click on "Connect via SSH"
* Next to string that begin with `ssh '...` - click on the copy icon 
* Open Cursor (or choose File -> New Window, if you have another project already open)
* Click on `Open with SSH`
* Paste the text you copied earlier, but make sure to remove the word `ssh` from the beginning of the string, and the quotes that wrap the actual SSH address
* Press Enter
* In explorer sidebar you won't see any files, click on "Open Folder"
* Delete `/home/gitpod/`
* Type `/workspace/` and you'll get a dropdown of various files and directories, choose the directory with the name of your repo
* Press "OK"
* 🎉

Using the "Live Share" extension was less involved.
I hope there's a way to streamline the SSH method into 1 click.
Thank you!

**Comment by shaal** [comment]
... update from today: the SSH connection between Gitpod workspace and Cursor no longer works for me.

I am back to using Live Share as an alternative. I don't know what changed, I tried starting a new workspace but still no success with SSH.

<img width="254" alt="image" src="https://github.com/gitpod-io/gitpod/assets/22901/9c6b1d5c-5218-4e1f-8ac4-7727640e0ff4">

**Comment by shaal** [comment]
To allow Cursor to connect through SSH with Gitpod, it is important to NOT have the `Remote - SSH` extension from Microsoft installed. 

As seen in the screenshot below, Cursor has built-in support for SSH, so this Microsoft extension conflicts and cannot be installed alongside Cursor's SSH functionality.

I had originally imported all my VSCode extensions to Cursor, including the `devbox by jetpack.io` [extension](https://marketplace.visualstudio.com/items?itemName=jetpack-io.devbox). By uninstalling this jetpack extension and reloading Cursor, the conflicting `Remote - SSH` extension from Microsoft is no longer installed, and the expected Cursor SSH message appears as in the screenshot.

The key points are:

- Cursor has native SSH support, so the Microsoft Remote - SSH extension conflicts
- Uninstalling the jetpack devbox extension removed the Microsoft SSH extension on reload
- The screenshot shows the expected Cursor SSH message after this change

<img width="1048" alt="image" src="https://github.com/gitpod-io/gitpod/assets/22901/88154874-b6d0-4dd8-8de8-40b21325d6ba">

**Comment by mbrevoort** [comment]
Thanks for the additional details. At the end of the week we were trying to get our extension to work with the open-remote-ssh fork used by cursor. I think we are pretty close to resolving the issues. I agree, it would be great to have cursor just work as a supporter ide.

**Comment by shaal** [comment]
Thank you!

One additional issue I noticed when connecting to Cursor via SSH is that it does not keep the Gitpod workspace awake.

Typically, Gitpod workspaces will automatically sleep after a period of inactivity. However, I would expect that connecting and interacting with the workspace through SSH and Cursor would reset the sleep timer and keep the workspace active.

This does not appear to be happening at the moment. The workspace still goes to sleep even when connected through SSH, which interrupts ongoing work.

**Comment by nhorton** [comment]
Related thing to the sleep issue; every few months, it seems like there is a bug that makes that sleep-while-in-use thing happen in Gitpod, including with VSCode. If you would put in something like a timeout countdown in the web page and a button to extend, it would give at least some way to workaround it when it happens.

**Comment by shaal** [comment]
Is there any update on this feature?

**Comment by rosendanew** [comment]
Any updates on the issue and it's priority within the gitpod team?

**Comment by jeanp413** [comment]
We did the required changes on our side, the problem now is that cursor is using an old version of the open-remote-ssh extension, they need to update it, we already send them a message.

**Comment by shaal** [comment]
@jeanp413 did you hear back from Cursor?
