### ISSUE TITLE
Last backup failed

### ISSUE THREAD

**Issue by bytefong** [gitpod-io/gitpod#1862]
### Describe the bug

I was working on a workspace then it suddenly unresponsive. When I refreshed the page it said the instance is stopping. A few minutes later I got below message.

`last backup failed: backup timed out. Please contact support if you need the workspace data.`

I tried to open the workspace again and it's succeeded without my previous local commits.

My Workspace ID: b7155a40-f209-4a8d-a148-437db26adae2

**Comment by wulfthimm** [comment]
Reply was send via Email.
