### ISSUE TITLE
Create A Terraform Script to install self-hosted on Digital Ocean

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#1863]
We should create a Terraform script to run Gitpod on Digital Ocean

**Comment by wolfymaster** [comment]
I'm running my self-hosted on DO - it has had some quirks, especiallty related to using their managed MySQL. If there is any help needed in building out DO support or scripts, I'm happy to lend a hand.

**Comment by JesterOrNot** [comment]
I do have one question did you zet up external storage w/ minio and if so what values did you use?

**Comment by wolfymaster** [comment]
This is coming up on my todo. I can follow up when I have storage solidified.
