### ISSUE TITLE
Wrong arrow direction on icon with non-default sidebar location

### ISSUE THREAD

**Issue by bsharrow** [gitpod-io/gitpod#18646]
### Bug description

When the VSCode sidebar is on the right, the arrow direction of the Connect icon is pointing away from the editor area.

<img width="517" alt="image" src="https://github.com/gitpod-io/gitpod/assets/2466523/b4f37473-3715-4bf2-9d59-b43792473956">

### Steps to reproduce

1. Update VSCode Desktop's sidebar location to the right: `"workbench.sideBar.location": "right"`
2. Open the Gitpod extension without a workspace open
3. Hover over the Connect icon of workspace, note the arrow points away from the editor area

### Expected behavior

Arrow points toward the editor area

**Comment by axonasif** [comment]
Hi @bsharrow, are you able to reproduce this behavior on VSCode Desktop?

**Comment by bsharrow** [comment]
> Hi @bsharrow, are you able to reproduce this behavior on VSCode Desktop?

Yes, should have clarified I'm not using the Web version.

**Comment by mustard-mh** [comment]
I thought the original idea is to make it align with `Remote Explorer`

<img width="331" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/7dd9ce1e-2408-4db8-bdaa-5e8fea97ece1">
