### ISSUE TITLE
Preview not working

### ISSUE THREAD

**Issue by Yael95** [gitpod-io/gitpod#1869]
Preview does not show my html. Is there a problem with my configuration?

```html
<body>
    <h1>Hello World</h1>
</body> 
```

this simple html does not show on my preview

**Comment by corneliusludmann** [comment]
Could you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) or at least your configuration?

**Comment by jankeromnes** [comment]
Hi @Yael95!

I see in your screenshot that the `index.html` file changes were not saved (see the full white disk in the editor tab handle).

If you press <kbd>Cmd</kbd> + <kbd>S</kbd>, this should save the file, and also update the HTML live preview.

**Comment by Yael95** [comment]
Thank you , and sorry for the bother.

**Comment by jankeromnes** [comment]
No worries! Glad I could help 😊
