### ISSUE TITLE
The "Dashboard" page is opened in the same tab. 

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#187]
**Description**

The "Dashboard" page is opened in the same tab.

**Steps To Reproduce:**

1. Login
2. Start some workspaces.
3. Click the "Dashboard" button
4. Pay attention to the "Dashboard" page. 

**Actual result:**
The "Dashboard" page is opened in the same tab.
Image: https://www.dropbox.com/s/ec45vhcn273q5nn/SameTab.png?dl=0

**Expected result:** 
The "Dashboard" page is opened in a new tab.

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98

**Comment by 32leaves** [comment]
fixed and deployed
