### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by flamecopper** [gitpod-io/gitpod#1870]
Hi there,

1. I am using apachectl , I can start with a configuration file but cannot stop
2. Using apachectl server, I can edit the php.ini after I grant permission from the Dockerfile, but when I restart the workspace it goes back to the original
3. Is there an inbuilt diff tools in the gitpod?
4. I am importing a database of type MyISAM, when I try to convert to InnoDB table, the table become corrupted.
5. At times I notices things are hanging or running very slowly when typing, how can I speed things up

Do let me know if you require more details of each of the issues,

**Comment by corneliusludmann** [comment]
Hi @flamecopper,

It would be great if you could create a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

Here is what I can answer based on your description:
- Currently, everything that is not in the folder `/workspace` will not survive a workspace restart. That's probably why the changes in `php.ini` are not persistent.
- You can compare files in your workspace by selecting both files in the file tree and select the entry from the context menu.
