### ISSUE TITLE
Add option to drop some Gitpod layer metadata

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1871]
When building workspace images, Gitpod does this dumb process of modifying the bashrc file to add some configuration which doesn't need to exist assuming the image already does it.

If you want a more comprehensive idea on why this is extremely flawed, please see https://github.com/gitpod-io/gitpod/issues/1555.

## My proposed solution

Add an empty file to all images that are meant explicitly for gitpod, like `/bin/.is-gp-image.metadata`, and if this file *exists*, then **only** add the declaration of user-set environment variable in Gitpod settings, and nothing else, assuming the image has the rest pre-configured, but if the file *does not* exist, add all the existing bashrc changes.
If a file doesn't work, maybe then just a list of image names that exclusively want to opt-out of this metadata addition.

Any thoughts @jankeromnes ?

I feel like this should be simple enough to implement.

**Comment by sr229** [comment]
We could use `LABEL`s and parse them to automatically configure the container post-pull since this would allow us to use standard container features that are already builtin.

**Comment by RDIL** [comment]
Any updates on this? Its still super annoying.

**Comment by RDIL** [comment]
Still really want this.

**Comment by jankeromnes** [comment]
FYI, the problematic Gitpod layer has been entirely removed in https://github.com/gitpod-io/gitpod/pull/4923
