### ISSUE TITLE
VS code desktop version reconnect issues

### ISSUE THREAD

**Issue by utkarsh914** [gitpod-io/gitpod#18710]
### Bug description

Whenever I open VS code desktop from gitpod, I get reconnection multiple times every once in a while. It looks like some sort of bug, as it doesn't happen if I use the web version of VS code.

Some details -
OS - MacOs Ventura 13.2 (22D49)
VS code desktop info - 
```
Version: 1.82.0
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:08:29.670Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.3.0
```
VS code gitpod extension version - v0.0.157

Note - the network connect on my end is stable, as the web version doesn't cause issues

### Steps to reproduce

Configure default editor as VS code desktop.
Open a workspace. It reconnects every once in a while. 
Gives a popup to reconnect, or reload the workspace.

### Workspace affected

https://clearfeed-appserver-m3wpexnb7au.ws-us104.gitpod.io/

### Expected behavior

Should not reconnect every now and then, without any reason.

**Comment by jeanp413** [comment]
Hi @utkarsh914, do you have telemetry disabled in vscode desktop? If so could you then collect logs once you are connected to remote workspace https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop
