### ISSUE TITLE
Deploying from gitpod

### ISSUE THREAD

**Issue by Yael95** [gitpod-io/gitpod#1873]
I was wondering if it is possible to deploy my web app as I am adopting gitpod as my work environment due to my machine's limitations. Can I deploy my web app to ( for instance Google cloud or app engine)? if so what is the procedure to follow as I feel more comfortable working on my projects on gitpod rather than setting up my environment in my local machine.

**Comment by sr229** [comment]
If you're aiming to deploy to Google Cloud Engine, you will need the Google Cloud CLI installed first, then set your token in your environment variables, you can find it on your account settings.

The Cloud CLI installation can be done in your workspace's Dockerfile and have your `.gitpod.yml` use that `Dockerfile.

**Comment by Yael95** [comment]
Thank you for your information. Do I need to install gitpod on my own cloud environment or I can do the deployment from gitpod?

**Comment by sr229** [comment]
You can do it both on the public offering and your self-hosted solution! It's documented in the docs on how to do your custom Docker environment @Yael95.

**Comment by Yael95** [comment]
Thank you guys for your info, have a bright weekend!
