### ISSUE TITLE
Allow using custom docker image without creating Dockerfile 

### ISSUE THREAD

**Issue by shyim** [gitpod-io/gitpod#18731]
## Is your feature request related to a problem? Please describe
Make it simpler to use external docker images

## Describe the behaviour you'd like
I want to uses my custom docker image without a Dockerfile.

## Additional context
I built my Gitpod Image in GitHub Actions and push it so it's faster startup across multiple projects

**Comment by akosyakov** [comment]
You can create .gitpod.yml and point image attribute to it?

**Comment by shyim** [comment]
It tries to look up for a file then. `.gitpod.yml` supports right now only file paths, not just the image name like
```
# .gitpod.yml
image:
  file: friendsofshopware/gitpod-shopware-workspace:latest
```

**Comment by akosyakov** [comment]
Please see my comment above. I've update it with a link to docs and example .gitpod.yml

**Comment by shyim** [comment]
Ahh nice. Are Alphas enabled for all users?

**Comment by shyim** [comment]
nvm it worked. no alpha access required
