### ISSUE TITLE
Can't use SDL even when using the VNC version

### ISSUE THREAD

**Issue by ProtoByter** [gitpod-io/gitpod#1876]
### Describe the bug
You can't use SDL2 on gitpod as it doesn't have any render backends (OpenGL, Vulkan, etc.) (Based on info from SDL_GetError())

### Steps to reproduce
Try and create an sdl renderer in gitpod

### Expected behavior
The renderer to be made without being nullptr

### Additional information
For reference this is what SDL_GetError() returns:
`Couldn't find matching render driver`

### Example repository
https://github.com/protobyter/VSmileTileEdit

**Comment by wulfthimm** [comment]
Gitpod is currently not supporting GPU rendering.

**Comment by ProtoByter** [comment]
oh ok, is it planned?

**Comment by jankeromnes** [comment]
On a side-note, I believe that you could enable software-rendering without having a physical GPU on the machine.

I've successfully used that in the past to allow Mozilla's experimental Rust browser engine Servo to run in Gitpod, specifically by tweaking noVNC's start-up flags in my Dockerfile:

https://github.com/gitpod-io/definitely-gp/blob/30f6a09fa5f0a7eaaa9cd0b7174b534a738bf21b/servo/.gitpod.dockerfile#L53-L56
