### ISSUE TITLE
Git editor is always set to pycharm, even when running through vscode

### ISSUE THREAD

**Issue by HughMacdonald** [gitpod-io/gitpod#18792]
### Bug description

In trying to do a "git rebase -i", it said that it was waiting for the editor to close, but never gave me an editor.

### Steps to reproduce

While using VSCode in GitPod, run any git command that requires an editor (`git rebase -i main`), and it will not show anything

### Expected behavior

It should open some kind of editor (vim, nano, in VSCode) to allow you to edit the commit message/rebase/etc

### Anything else?

I tried setting core.editor to a few different things (nano, "code --wait"), and nothing worked. I did figure out that the VSCode executable was called "gitpod-code", so set it to "gitpod-code --wait", but still no luck.

I eventually realised that $GIT_EDITOR was set to `/ide-desktop/pycharm/bin/idea-cli open --wait`
Running `unset GIT_EDITOR` meant that it use the config value properly.

I would suggest, as a fix, ensuring that $GIT_EDITOR is properly set to use the same IDE that the user is using

**Comment by mustard-mh** [comment]
Hey @HughMacdonald 👋 , did you start your workspace with PyCharm?

**Comment by HughMacdonald** [comment]
I was actually helping out @mkmacd with his workspace, so he'd be better able to answer that question

**Comment by mkmacd** [comment]
I think I might have done originally but never used pycharm with it and have since changed my preference to use VS Code (which for some reason it still tries to default opening with pycharm. 
Not sure if there's a preference somewhere withing GitPod because the dashboard doesn't fix it.

![image](https://github.com/gitpod-io/gitpod/assets/134923802/023880ae-8b0b-465c-a6b6-baa3514c3e8d)

**Comment by mustard-mh** [comment]
@mkmacd  I see, you could be affected by `Autostart` option, you can try to reset it on [your preferences](https://gitpod.io/user/preferences)
|Autostart|Reset|
|:-:|:-:|
|<img width="724" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/90f013b4-17aa-4aa8-92c1-a0f515df22eb">|<img width="936" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/3cfae4b3-3004-47fa-bcba-384449c503ae">|
