### ISSUE TITLE
Uploading Folders from Chromebook broken

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#188]
**To Reproduce**
1. On the ChromeBook, create a folder "foo" in the "Files" app with two jpeg images inside
2. start a Gitpod workspace
3. Drag-n-Drop the folder "foo" from the Files app into a folder inside the Gitpod "File" View. 

Observe nothing to happen. No files arrive in the Gitpod workspace and there are no errors in the JS console.

I've tried it on ChromeOS version 70.0.3538.110 (64-bit) here

**Expected behavior**
The folder should be uploaded.

**Comment by HPestock** [comment]
I have the same problem, I usually just send the files to another device, say a phone for instance, and I upload it from there.

**Comment by svenefftinge** [comment]
@HPestock are you on a chromebook, too?

**Comment by HPestock** [comment]
Yes, I hate the thing.

**Comment by minecraft-spec-sys** [comment]
lo

**Comment by ritikareddy29** [comment]
I also use a chromebook and I can only upload files, not folders

**Comment by axonasif** [comment]
Hi @ritikareddy29, you could create an archive of the files you want to upload (e.g. `zip`, `tar` and etc.)
