### ISSUE TITLE
docker run emits no output without the `--tty` flag

### ISSUE THREAD

**Issue by jgraettinger** [gitpod-io/gitpod#18814]
### Bug description

Stdout and stderr from docker containers isn't collected until you pass the `--tty` flag, which is not expected.

A `docker run` without a `--tty` should still emit the stdout and stderr of its container.

`docker logs` of a container should also show combined stdout/stderr of its container regardless of `--tty`, but does not on Gitpod.

Thanks!

### Steps to reproduce

Easily reproduced. Here's an example session starting from the "template-golang-cli" sample. I've observed it in every other workspace I've tried:

```
gitpod /workspace/template-golang-cli (main) $ docker run alpine echo hello
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
7264a8db6415: Pull complete 
Digest: sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
Status: Downloaded newer image for alpine:latest
```
Note that "hello" is not output.

```
gitpod /workspace/template-golang-cli (main) $ docker run --tty alpine echo hello
hello
```

With `--tty` it is.

```
gitpod /workspace/template-golang-cli (main) $ docker run alpine echo hello
```
Again, no output.

```
gitpod /workspace/template-golang-cli (main) $ docker ps -a
CONTAINER ID   IMAGE     COMMAND        CREATED          STATUS                      PORTS     NAMES
00621fad300f   alpine    "echo hello"   6 seconds ago    Exited (0) 4 seconds ago              busy_darwin
dd23d32c3d5a   alpine    "echo hello"   9 seconds ago    Exited (0) 8 seconds ago              beautiful_ishizaka
01c1620ab513   alpine    "echo hello"   16 seconds ago   Exited (0) 15 seconds ago             elastic_vaughan
gitpod /workspace/template-golang-cli (main) $ docker logs busy_darwin
gitpod /workspace/template-golang-cli (main) $ docker logs beautiful_ishizaka
hello
gitpod /workspace/template-golang-cli (main) $ docker logs elastic_vaughan
```

`docker logs` shows output only for the container started with `--tty`.

```
gitpod /workspace/template-golang-cli (main) $ docker inspect busy_darwin | grep -A 3 LogConfig
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
```

Containers were run with the expected `json-file` docker log driver, which should be collecting output.

### Expected behavior

`docker run` and `docker logs` should show the expected "hello" output regardless of whether `--tty` is passed.

**Comment by medihack** [comment]
To make sure everyone finds this issue. This also affects `docker compose logs`. No outputs are visible anymore (especially when opening them with the VS Code Docker extensions from the left menu. I hope this gets fixed soon.

**Comment by joe-dakota** [comment]
I also experienced this and added `tty: true` to all of our service in our docker-compose.yml to workaround

**Comment by axonasif** [comment]
Hi! It appears that there may have been a regression in the latest upgrade of [docker-compose version](https://github.com/gitpod-io/compose/releases). Our team is currently investigating the issue and we may need to revert back to the previous version as a temporary fix.
