### ISSUE TITLE
Live reload does not work for parcel/webpack

### ISSUE THREAD

**Issue by maksimr** [gitpod-io/gitpod#1881]
Example project:

https://github.com/maksimr/playground

STR:

- Open `gitpod.io/#https://github.com/maksimr/playground`
- Open terminal `npm ci`
- Run task `npm start`
- In popup select `Make port public` and `Open preview`
- Change `index.js`

AR: Preview show old result
ER: Preview refreshed/reloaded and show new result

If manually press “Refresh” it would show new result

The same problem with webpack configuration
https://github.com/maksimr/y

OS: iPadOS 14

**Comment by akosyakov** [comment]
I'm not sure whether it is gitpod issue or misconfiguration of parcel. The preview listens to file changes when an opened URL is pointing to a file. In this case though the content is fetch from a server started by parcel. I would expect that parcel or webpack devserver is responsible to trigger hot reload, and it should work in the preview and in a new browser window.

Could you point to docs about how to configure live reload for parcel?

**Comment by maksimr** [comment]
@akosyakov parcel already has preconfigured server with live reload. There are not so much room to configure it manually :( 

> Parcel has a development server built in, which will automatically rebuild your app as you change files and supports hot module replacement for fast development. Point it at your entry file:
https://parceljs.org/getting_started.html

But live reload works locally and in codesandbox (which use parcel by default)

I could create minimal example with webpack if it would help. Because webpack also doesn’t work for me

**Comment by maksimr** [comment]
@akosyakov I believe that I have not configured something properly on gitpod because for example
https://github.com/4GeeksAcademy/react-hello-webapp works for me but only for port **3000** if I change port on **8080** for example it would not reload the page so I believe there are some configuration for gitpod

**Comment by maksimr** [comment]
Playground with webpack - https://github.com/maksimr/playground/tree/webpack

**Comment by akosyakov** [comment]
Parcel tries to establish a web socket to hot reload server but fails:
<img width="1674" alt="Screenshot 2020-09-22 at 10 27 31" src="https://user-images.githubusercontent.com/3082655/93859764-56e42700-fcbe-11ea-91b7-0a50b2b90a54.png">

We expect that external URLs shoudl be consrcuted like `${port}-${windowl.location.href}` and all on the same port. Parcel though does `${windowl.location.href}:${port)`.

@svenefftinge Maybe you have an idea how to deal with? 

Not sure about webpack yet. https://github.com/4GeeksAcademy/react-hello-webapp works for me on both ports 3000 and 8080.

**Comment by akosyakov** [comment]
Something like https://github.com/parcel-bundler/parcel/issues/2275 could help.

**Comment by maksimr** [comment]
@akosyakov thanks a lot! I have created an example with webpack.

I have tried to run in on PC to debug and see that requests to fetch changes failed
![image](https://user-images.githubusercontent.com/616193/93860568-f659e780-fcc7-11ea-9cfd-72a0b819ecf6.png)
![image](https://user-images.githubusercontent.com/616193/93860619-096cb780-fcc8-11ea-825c-70dfc1a3e52e.png)

**Comment by maksimr** [comment]
Hm... in webpack examples it tries to go on port 3000

**Comment by akosyakov** [comment]
@alesanchezr Hi, sorry to bother. Maybe you can shed some light how you managed to enable hot reload for https://github.com/4GeeksAcademy/react-hello-webapp and what is missing in https://github.com/maksimr/playground/tree/webpack?

**Comment by akosyakov** [comment]
It works with webpack-dev-server@3.3.1, but now with latest :(

**Comment by maksimr** [comment]
@akosyakov I was able to run live reload in latest webpack by passing `--sockPort=443`. Otherwise, webpack try to poll `<host>:<serverPort>` but gitpod.io proxy only `443` port

**Comment by maksimr** [comment]
Another solution use `--public` and `gp url`

 `webpack-dev-server -d --disable-host-check --host 0.0.0.0 --port 3000 --public $(gp url 3000)`

**Comment by akosyakov** [comment]
Maybe something worthwhile to document here: https://www.gitpod.io/docs/languages-and-frameworks/

**Comment by nisarhassan12** [comment]
I have opened an issue for it on the documentation website repo https://github.com/gitpod-io/website/issues/771. Will make a Pr soon.

**Comment by maksimr** [comment]
@nisarhassan12 but currently parcel doesn't have proper solution due their implementation, only webpack

**Comment by nisarhassan12** [comment]
@maksimr Thanks. You're right. https://github.com/parcel-bundler/parcel/pull/3324 

We will hopefully try to make a PR and have a proper solution in Parcel soon in the future.

For now We are planning to document something like [this](https://github.com/nisarhassan12/svelte/blob/7145c752efe1531d9523ff48bfad21e373d418aa/.gitpod.yml#L7) which is a hack we used to make Live reload work for [Svelte](https://github.com/sveltejs/svelte) which uses Rollup as a module bundler.

**Comment by fabrizim** [comment]
I got this working using a similar approach as the svelte patch, adding the following to the `init` task in the .gitpod.yml file:

    sed -ri "s/hostname\s+\s':'\s+\sprocess\.env\.HMR_PORT/hostname.replace(\/^(\\d+)\/, process.env.HMR_PORT) + ':443'/" ./node_modules/parcel-bundler/src/builtins/hmr-runtime.js

Hope that helps someone else. FYI - this is only for parcel v1.

**Comment by nisarhassan12** [comment]
Thanks, @fabrizim for sharing this.

@jankeromnes is probably working on a Pr for parcel v2 once that is merged we will no longer have to hack our way around this and we will be able to do it like it's done here https://github.com/gitpod-io/sveltejs-template. 

The time this https://github.com/nisarhassan12/svelte/blob/7145c752efe1531d9523ff48bfad21e373d418aa/.gitpod.yml#L7 was wriiten I think there were no `clientUrl` option available to help.

**Comment by alesanchezr** [comment]
I don't know if I'm too late @jankeromnes @maksimr but here is how @unocongafas was able to fix this issue within our boilerplates: Add this into your webpack.config:

```js
const [schema, host] = process.env.GITPOD_WORKSPACE_URL.split('://')
const publicUrl = `3000-${host}`

module.exports = {
    ...
    devServer: {
        ...
        public: publicUrl
    },
}
```

**Comment by Lninn** [comment]
> I don't know if I'm too late @jankeromnes @maksimr but here is how @unocongafas was able to fix this issue within our boilerplates: Add this into your webpack.config:
> 
> ```js
> const [schema, host] = process.env.GITPOD_WORKSPACE_URL.split('://')
> const publicUrl = `3000-${host}`
> 
> module.exports = {
>     ...
>     devServer: {
>         ...
>         public: publicUrl
>     },
> }
> ```

Thanks, work for me

**Comment by akosyakov** [comment]
We just announced preview version of Gitpod local companion which allows to tunnel any tcp port: https://www.gitpod.io/blog/local-app in particular you can do http on localhost the same way as in local env, please try and give us feedback 🙏🏻
