### ISSUE TITLE
VS Code Browser Release `1.83`

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#18869]
This issue exists for tracking the release process of the latest release of our VS Code distribution for the web, Gitpod VS Code Browser.

Upstream planned release date: `3rd of August` (actual also)

## `1.83.0`

Upstream endgame: https://github.com/microsoft/vscode/issues/193938
Upstream release: https://github.com/microsoft/vscode/releases/tag/1.83.0
Release PR: https://github.com/gitpod-io/gitpod/pull/18868
OpenVSCode Server Release: https://github.com/gitpod-io/openvscode-server/releases/tag/openvscode-server-v1.83.0

## Resources

- Checklist for releasing new VS Code minor versions: [`minor.md`](https://github.com/gitpod-io/openvscode-releases/blob/main/resources/checklists/minor.md)
- Checklist for releasing new VS Code patch versions: [`patch.md`](https://github.com/gitpod-io/openvscode-releases/blob/main/resources/checklists/patch.md)

**Comment by GitMensch** [comment]
Current version output:

```
Version: 1.83.1
Commit: 9ab5dfec5c88efc77a902df0a0c26733ab0c4a51
Date: 2023-10-12T12:45:25.391Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0
```

--> seems to be done, next would be #18969, which seems to be in progress, too (but strangely misses the applicable label)
