### ISSUE TITLE
clang++ compiler options (include libraries)

### ISSUE THREAD

**Issue by mfouesneau** [gitpod-io/gitpod#1888]
I have a very minimal example and I cannot make it work properly.

The example is very minimal but includes a second header provided within the repository. However the editor does not find where this piece is and I cannot find where to put something similar to "--include-directory ${workspaceRoot}/include"

Could you help?

example here:
https://github.com/mfouesneau/gitpod_cpp_template

**Comment by jankeromnes** [comment]
Hi @mfouesneau, sure! I'll see if I can get this to work properly.

My first guess would be to configure `clangd`, the Language Server behind editor's C/C++ support, like so: https://github.com/Shadouw/HelloGitPod/blob/master/.theia/settings.json

However, we might have changed the C/C++ VSCode extension in Gitpod, so maybe that's no longer the correct way to configure this. I'll take a look.

**Comment by mfouesneau** [comment]
I did try that. Have a look at my configuration. The includes are not used there.

**Comment by jankeromnes** [comment]
I see in your [.theia/settings.json](https://github.com/mfouesneau/gitpod_cpp_template/blob/9100a8bc714939076749817bf6b7273b9f4b11ca/.theia/settings.json#L10-L12) that you've tried to configure something called `clangd.arguments`, but that doesn't seem to exist:

<img width="498" alt="Screenshot 2020-09-23 at 17 01 07" src="https://user-images.githubusercontent.com/599268/94030831-8bd7a300-fdbe-11ea-81b7-d996464b7fad.png">

Maybe you could simply add the `--include-directory ${workspaceRoot}/include` argument into the above `cpp.clangdArgs`? E.g. like so:

```js
    "cpp.clangdArgs": "--background-index --include-directory ${workspaceRoot}/include"
}
```

**Comment by mfouesneau** [comment]
When I do so I get a series of error notifications on clangd server that cannot start.

yes clangd.arguments does not work here.
