### ISSUE TITLE
Is it possible to know when a Pull Request is opened from a Gitpod workspace (for metrics tracking)?

### ISSUE THREAD

**Issue by skinny85** [gitpod-io/gitpod#1889]
Hey all,

in an effort to track how impactful adding Gitpod support is to our project's contribution experience, I was wondering: is there any way to know (and count) whether a given Pull Request was opened from a Gitpod workspace?

Thanks,
Adam

**Comment by akosyakov** [comment]
@jankeromnes Could you answer please?

**Comment by jankeromnes** [comment]
Hey @skinny85,

For sure! Gitpod always remembers for which context URL (e.g. specific Pull Request URL) and commit SHA a workspace was created, so it's possible to get stats on that. (Note: Deleted workspaces will not show up in this data though.)

Long-term we'll likely want to expose this data (e.g. anonymized per repo / per PR usage stats) in some sort of dashboard, but for now I'm happy to answer specific data requests here.

Which Pull Request did you have in mind?

**Comment by aslafy-z** [comment]
It could eventually be done by tagging these pull request with something like `opened-by: gitpod`, either manually as part of your contribution process or automatically added by gitpod (default labels in .gitpod.yml) to your PRs?

**Comment by skinny85** [comment]
Thanks for the answer @jankeromnes . I was actually curious about the number of Pull Request that were opened to the [aws/aws-cdk](https://github.com/aws/aws-cdk) project from Gitpod workspaces, to maybe see how effective it is for enabling contributions to the project.

I would love to see that number, but since you mentioned it doesn't include deleted workspaces, I assume it's going to be much lower than the real number...?
