### ISSUE TITLE
Select all - Ctrl+a doesn't work in the New File and New Folder name box

### ISSUE THREAD

**Issue by alexcmonnet** [gitpod-io/gitpod#1890]
### Describe the bug
When prompted to name a new file or new folder, I'm unable to use the ctrl+a select all shortcut to select then delete the prepopulated 'Untitled.txt' in the input field. 

### Steps to reproduce
1. Open a project in the Gitpod workspace.
2. Create a new file in the IDE
3. Select/focus on the input field in the pop-up titled 'New File'
4. Use the select all keyboard shortcut 'ctrl + a'
5. Note that the text in the input field is not selected.

### Expected behavior
When the 'ctrl+a' shortcut is executed, the entire input of the field should be selected and highlighted.

### Additional information
Browser is Firefox 80.0.1 (64-bit)
Host OS is Windows 10 Home version 1909

### Example repository
https://gitlab.com/alexmonnet/rust-helloworld

**Comment by akosyakov** [comment]
It sounds like FF issue. It works in other browsers. Could you report a bug for them please: https://bugzilla.mozilla.org/home?

**Comment by alexcmonnet** [comment]
Opened a bug report with Mozilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1667140
