### ISSUE TITLE
Manually approve Shared Workspace users

### ISSUE THREAD

**Issue by ChevronTango** [gitpod-io/gitpod#18946]
## Is your feature request related to a problem? Please describe

Currently when sharing a workspace it is open to any user with the link. This is not secure and it means anyone can get in and start making changes with no limits or controls beyond keeping your workspace URL secret.

## Describe the behaviour you'd like

A panel in the UI, similar to the ports window, showing which users have access to the workspace, and who is still pending. When a user attempts to connect, they move into a pending state until the host allows them in. The host receives pop up windows whenever a new user attempts to join a session.

## Additional context

LiveShare does a similar thing for controlling permissions and use of workspaces

**Comment by loujaybee** [comment]
x-posting related comment: 

> Thanks for the feedback, @ChevronTango - more granular control on workspace sharing would be great.
It's worth noting that workspace sharing (if required) can be disabled at the organization level:
https://www.gitpod.io/changelog/organizational-policy-workspace-sharing
And many 3rd party sharing plugins also work (if that's use to anyone looking for more feature-rich solutions):
https://www.gitpod.io/docs/configure/workspaces/collaboration#external-collaboration-plugins

https://github.com/gitpod-io/gitpod/issues/18945#issuecomment-1769043176
