### ISSUE TITLE
Add Stop Workspace Button

### ISSUE THREAD

**Issue by VarunSharma3520** [gitpod-io/gitpod#18940]
## Is your feature requested wanted a stop workspace button?
I have been using Gitpod a long ago. I have felt have been switching off workspace from 3 dot button menu, I think it will be difficult for new user to find stop button. So. I think it should be placed out side the 3 dot button

It should Be easy enough to stop workspace.

click the link to redirect: https://gitpod.io/workspaces

## Have a look
![Screenshot 2023-10-17 221226](https://github.com/gitpod-io/gitpod/assets/110775856/e4d180ee-3cb8-4e51-9c2a-4f58029be2d4)

**Comment by Siddhant-K-code** [comment]
There is an option to `Stop` which comes to "running" workspaces

<img width="1125" alt="Screenshot 2024-02-12 at 11 25 28 AM" src="https://github.com/gitpod-io/gitpod/assets/55068936/ef4f9100-b02b-4c9a-8f90-fd27bdd3566e">
