### ISSUE TITLE
Private key exposed in gitpod repo.

### ISSUE THREAD

**Issue by Aju100** [gitpod-io/gitpod#1896]
The private key and other credentials have been exposed to your repo. here is the link to where it's located.
https://github.com/gitpod-io/gitpod/blob/master/chart/secrets/messagebus/msgbus-client.pem

**Comment by AlexTugarev** [comment]
@Aju100 thanks for reaching out! 

This isn't a critical thing, as it's just used to secure the internal message bus which is not exposed otherwise.

We definitely should add means of generating that key in helm and maintain on updates.

**Comment by Aju100** [comment]
@AlexTugarev  thank u for ur response
