### ISSUE TITLE
I received a spam email from contact@gitpod.io but I never used gitpod

### ISSUE THREAD

**Issue by NinoDLC** [gitpod-io/gitpod#18980]
### Bug description

I received a spam email from contact@gitpod.io about privacy changes but I never used this service. Is this a scam ? How did you get my email adress ? I use this email only for Github btw... are you scrapping GitHub ?

OAuth connection with my GitHub account isn't even done so that's even more sketchy (since the email address is only used with GitHub). 

### Steps to reproduce

Never use this product.
You get an email anyway.

**Comment by securitymirco** [comment]
Hi @NinoDLC,

thanks for reaching out! Our records indicate you signed up around 5 years ago on April 10th, 2019.

If you like I can just delete all data associated with you, which should prevent future emails - just let me know.

Happy to help if you have any other questions.

Best regards,

Mirco

**Comment by Adele583** [comment]
hallo
