### ISSUE TITLE
Extension requires a license key every time when I open gitpod

### ISSUE THREAD

**Issue by maksimr** [gitpod-io/gitpod#1899]
STR:

- Install an extension which requires a license
- Add license
- Reload page

AR: Extension requires to type license again

**Comment by AlexTugarev** [comment]
Hi @maksimr!

Which extension is it?

**Comment by maksimr** [comment]
@AlexTugarev similar to [quokkajs](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)

**Comment by AlexTugarev** [comment]
"similar to" but not exactly that one? it's hard do diagnose if it's not that one. 

it would be great to see if there are any issues logged. if you don't mind to assist on that, please retry and have a look at the JS console in the dev tools of your browser. is there anything related logged?

**Comment by maksimr** [comment]
@AlexTugarev you can use Quokka

>  if you don't mind to assist on that, please retry and have a look at the JS console in the dev tools of your browser. is there anything related logged?

After set license key no any message in console

**Comment by AlexTugarev** [comment]
Just tried with the trial license. It seems to work 🤷‍♂️

**Comment by maksimr** [comment]
@AlexTugarev it doesn't show license dialog again after page reload?

**Comment by AlexTugarev** [comment]
No it doesn't. 
I installed the extension and then requested/applied the trial license.

**Comment by maksimr** [comment]
@AlexTugarev hm... have tried with trial license and all works fine.

**Comment by maksimr** [comment]
Close issue because now my own license also works fine after replace trial
