### ISSUE TITLE
Default Editor is Ignored

### ISSUE THREAD

**Issue by cawoodm** [gitpod-io/gitpod#18996]
### Bug description

Each time I open a workspace it tries to open VS Code Desktop edition instead of my preference VS Code Browser edition.

### Steps to reproduce

Create a workspace and choose VS Code Desktop edition as the default editor. Later change your mind.

### Workspace affected

cawoodm-pyreact-oft7hvkp559.ws-eu105

### Expected behavior

The UI says:
> You can change the default editor for opening workspaces in [user preferences](https://gitpod.io/user/preferences).
Well you can, but it makes no difference.

![image](https://github.com/gitpod-io/gitpod/assets/498834/30b444b4-e099-409b-bbb9-11aede2c3389)

### Example repository

https://cawoodm-pyreact-oft7hvkp559.ws-eu105.gitpod.io/

**Comment by svenefftinge** [comment]
The editor preference only affects newly created workspaces. Youz cannot change the editor for an existing workspace that you restart.
