### ISSUE TITLE
Workspace not reacheable

### ISSUE THREAD

**Issue by marcdumais-work** [gitpod-io/gitpod#19]
When attempting to open this PR: https://github.com/theia-ide/theia/pull/1983 . I tried again, chose to have GitPod create a new workspace, and the same problem happened again.

Not sure if it's something with that specific PR or general. 

![image](https://user-images.githubusercontent.com/25749063/43321852-1d9bc85a-917b-11e8-96b3-c80c2a2d01fb.png)

![image](https://user-images.githubusercontent.com/25749063/43322041-9167c784-917b-11e8-8b7f-1a98b0ab09f1.png)

**Comment by geropl** [comment]
Hi @marcdumais-work, thank you for your feedback! We're truly sorry for your inconvenience. We just did a massive rebuild of our underlying infrastructure. By now it should work fine, though!

**Comment by marcdumais-work** [comment]
Thanks @geropl - I just re-tried and it worked.
