### ISSUE TITLE
Inconsistent tab title behavior

### ISSUE THREAD

**Issue by sherbang** [gitpod-io/gitpod#190]
If a new tab is created after the workspace is loaded, then xterm-style escape sequences can set the tab title.  However, this doesn't work when the tab is created by a -command: line in .gitpod.yml.

    - command: echo -ne "\033]0;TAB TITLE\007" && <long-running-process>
should set the title of the tab to "TAB TITLE".

Using ctrl-` to create a new tab, and then run ```echo -ne "\033]0;TAB TITLE\007" && sleep 5``` _does_ set the title of the tab to "TAB TITLE"

**Comment by sherbang** [comment]
This isn't an issue with the echo command running before the tab is fully loaded.  If the tab was launched at startup, then the title can never be set in that tab.

ctrl-c to kill the running process in the tab, and try to use echo to set the title. Doesn't change.

**Comment by svenefftinge** [comment]
Thank you, we will look into it. 
In the meantime, if you want to set the tab title initially you can use the property `name`. E.g.
```
tasks:
- name: My title
  command: echo hello
```

try it in action: 
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/0b1cf955-dbe8-49d7-8f57-087d9c5b5d52)
