### ISSUE TITLE
missing option to globally set environment variables (docker context?)

### ISSUE THREAD

**Issue by GitMensch** [gitpod-io/gitpod#19007]
## Is your feature request related to a problem? Please describe
Some projects need environment variables to be setup; while this is possible to be done in gitpod tasks, those don't trigger for the integrated IDE or terminals created apart from the initial tasks.

## Describe the behaviour you'd like
Provide a way to setup environment variables in gitpod.yml that are set for the whole enviroment.

## Describe alternatives you've considered
Setting these in the workspace config -> not shared between users, so: bad.
Setting these in each of the client configuration files (tasks.json, launch.json, ...) -> triggers also outside of gitpod, so: bad.
Setting these in manually in all terminals and config files on each workspace start: bad.

**Comment by akosyakov** [comment]
@GitMensch you should be able to set up env var in the docker image as well as on [user](https://www.gitpod.io/docs/configure/projects/environment-variables#user-specific-environment-variables) or [repo configuration](https://www.gitpod.io/docs/configure/projects/environment-variables#project-specific-environment-variables) level.

**Comment by GitMensch** [comment]
Docker image only works when using an own docker image, per user setting via account setting or DOCKERD_ARGS doesn't work for shared projects, project specific won't work for new people not part of the project (and only if it actually is integrated)... using `gp env` in gitpod.yml directly _should_ work- but only with project specific prefixes (for example I wanted to extend the `PATH`, that doesn't sound likely something to be done for the user in every gitpod instance).

I suggest adding something like the following to gitpod.yml:
[`image.env`](https://www.gitpod.io/docs/references/gitpod-yml#imageenv): list of values that are set directly after the container started, may include environment variables itself.

**Comment by akosyakov** [comment]
Understand the proposal.

>Docker image only works when using an own docker image

I'm not sure what is wrong with adding a tiny layer on top of the default image to add couple env vars?

**Comment by GitMensch** [comment]
I'm not a docker person (yet), so I have no clue how to add a tiny layer...

Can you help me to find out how to extend the full-vnc image to do the installation of the necessary tools and set the PERF related environment vars [for this example](https://github.com/KDAB/hotspot/blob/404792d7f8767bcfc3b216fcf12f99683f74433c/.gitpod.yml)?

**Comment by GitMensch** [comment]
Friendly ping @akosyakov about the help with "add a tiny layer" to add env vars (and ideally also updating the image with a bunch of tools to remove the need for extensive `apt` and "static" make commands).

**Comment by mustard-mh** [comment]
> Friendly ping @akosyakov about the help with "add a tiny layer" to add env vars (and ideally also updating the image with a bunch of tools to remove the need for extensive apt and "static" make commands).

Hey @GitMensch , you could check our [Document](https://www.gitpod.io/docs/configure/workspaces/workspace-image#using-a-custom-dockerfile) about how to customize your Dockerfile. `gp validate` [[doc](https://www.gitpod.io/docs/configure/workspaces#validate-your-gitpod-configuration)] command is very useful if you want to verify your gitpod configuration.

Example for a tiny layer

```
FROM gitpod/workspace-base:latest

ENV FOO=A BOO=B
```

**Comment by GitMensch** [comment]
Works fine, thank you! Should we close that FR or do we want to keep it?

`image.env` has the benefit of not needing another file (which in my case is definitely the way to go in any case), so will be quite useful; also it can be directly passed to docker using `-e "[varname]=[value]"`.

**Comment by axonasif** [comment]
@GitMensch I'll close this one, feel free to create a new issue if needed.

**Comment by GitMensch** [comment]
Not **needed**, there's only the _idea_ of a useful feature that _seems_ to be easy to be implemented left.
