### ISSUE TITLE
Error running command gitpod.workspaces.connectInCurrentWindow_inline@1: Invalid URL

### ISSUE THREAD

**Issue by elee02** [gitpod-io/gitpod#19037]
### Bug description

I am encountering an issue when trying to connect to a workspace in Gitpod through Visual Studio Code. The error message I receive is:

```
Error running command gitpod.workspaces.connectInCurrentWindow_inline@1: Invalid URL: https:/<REDACTED: user-file-path>. This is likely caused by the extension that contributes gitpod.workspaces.connectInCurrentWindow_inline@1.
```

### Steps to reproduce

1. Open Visual Studio Code.
2. Attempt to connect to a Gitpod workspace.

### Expected behavior

I expect to be able to connect to the Gitpod workspace without any issues.

**Actual behavior:**

I receive the aforementioned error message.

### Anything else?

- Visual Studio Code version: 

Version: 1.84.1 (Universal)
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:37:18.666Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 20.6.0

- Gitpod extension version: v0.0.163

- Operating System: 
MacOS Big Sur
Version: 11.7.10 (20G1427)

![Screen Shot 2023-11-08 at 20 34 51](https://github.com/gitpod-io/gitpod/assets/112889202/b1659422-b1af-422e-8e0f-639ca5aa528a)

Any help resolving this issue would be greatly appreciated.

**Comment by axonasif** [comment]
Hi @elee02, can you make sure both vscode and gitpod vscode extension is up to date? If it is, can you try again and let us know if the issue still persists?

**Comment by error9098x** [comment]
@axonasif hi, I have the same problem with vs code insider , both things are up to date

**Comment by saravmajestic** [comment]
i have the same issue with windows 10 vscode v 1.86.1 and gitpod extn v0.0.164. When I try to open with vscode desktop from within a workspace, it works.

**Comment by dipeshsingh253** [comment]
Hi, I am facing the same issue. Did we find any solution for this?

**Comment by elee02** [comment]
Good day! Unfortunately, no, I went back to use github copilot

**Comment by dipeshsingh253** [comment]
I found out that the issue is only when you try to open it from github extension in vscode you face this issue. If you connect it from browser instance it works fine. Have a good day too !!!
![image](https://github.com/gitpod-io/gitpod/assets/84814627/28323f11-04b5-478f-8ecc-2dcf50e5ac5e)

**Comment by elee02** [comment]
Wow, the observation is much appreciated!

**Comment by NathanAP** [comment]
This issue should not be closed because the error still exists and some of the pointed workaround won't always work. Right now I just cannot connect to any of my workspaces.

**Comment by axonasif** [comment]
Hi @NathanAP, could you collect logs and reach out at https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop ?

**Comment by axonasif** [comment]
Awesome, thanks for sharing @NathanAP !
