### ISSUE TITLE
xdg-open command is not working

### ISSUE THREAD

**Issue by mmailaender** [gitpod-io/gitpod#19065]
### Bug description

xdg-open command is not workinging)

### Steps to reproduce

run `xdg-open` in Gitpod

### Expected behavior

xdg-open should work

### Anything else?

As a workaround, I reinstalled the xdg-utils `sudo apt-get install --reinstall xdg-utils`

**Comment by axonasif** [comment]
Hi @mmailaender, see https://www.gitpod.io/docs/configure/workspaces/workspace-image#how-to-run-a-desktop-app-for-gui-development-inside-a-gitpod-workspace
