### ISSUE TITLE
Extension: No GitPod link available on GitLab repositories

### ISSUE THREAD

**Issue by StoneyJackson** [gitpod-io/gitpod#19071]
### Bug description

The "clone" pill no longer replaced with the "GitPod" pill on a GitLab repository. Still works on GitHub.

### Steps to reproduce

Install extension. Enable it for the gitlab.com domain. Navigate to a repository on GitLab (e.g., https://gitlab.com/StoneyJackson/test-gitpod-extension). Observe the absence of a GitPod link/button/pill.

### Expected behavior

A GitPod button/link should appear that I can click to start a workspace.

### Example repository

https://gitlab.com/StoneyJackson/test-gitpod-extension

### Anything else?

My context:
* MacOS 14.0 (23A344)
* Chrome Version 119.0.6045.123 (Official Build) (x86_64)
* GitPod extension 2.1.1

I've tried:
* Uninstalling and reinstalling the extension.
* Installing and using the extension in FireFox. Same behavior: works on GitHub but not on GitLab.
* Opening a GitLab repository by pasting its URL into GitPod's "New Workspace" dialog works.

**Comment by filiptronicek** [comment]
@StoneyJackson thanks for the report! I can reproduce the issue on GitLab repos, and will get back with a fix. Stay tuned

**Comment by StoneyJackson** [comment]
Another workaround: Select "Edit" -> "Gitpod".

**Comment by StoneyJackson** [comment]
The button is back, and it works!

<img width="489" alt="Screenshot 2023-12-05 at 9 32 31 AM" src="https://github.com/gitpod-io/gitpod/assets/1394670/5d9a3f60-e8fd-4d6a-8f38-2c93b4600bbb">

So, I'm closing. Feel free to reopen if that's the wrong move.

**Comment by filiptronicek** [comment]
Thank you for closing. This was addressed with yesterday's release for Chrome and today's for Firefox 🎉
