### ISSUE TITLE
A way to share files between workspaces

### ISSUE THREAD

**Issue by k4ml** [gitpod-io/gitpod#19113]
## Is your feature request related to a problem? Please describe
We need to share data such as database dump, logs, csv files between developers.

## Describe the behaviour you'd like
Click on Project ==> Settings, under General and Variables, there's another link called Files. Click that and we have form that allow us to upload files. The files then will be available to all workspaces in the project, similar to how Variables works.

## Describe alternatives you've considered
Right now we have to use separate git repo to share that data files.

**Comment by Derroylo** [comment]
@k4ml Take a look at this post from axon: https://github.com/gitpod-io/gitpod/issues/9284#issuecomment-1402313601 He suggested a tool called rclone to share files between workspaces. Maybe that is something worth taking a look at.
