### ISSUE TITLE
Cannot open a GitHub repository with React Native - no error message

### ISSUE THREAD

**Issue by ceefour** [gitpod-io/gitpod#1913]
### Describe the bug

Cannot open a GitHub repository with React Native - no error message

### Steps to reproduce

Open this repository: https://github.com/soluvas/Rocket.Chat.ReactNative/commit/c418e66fe4242c8d022eeff93c9bae960117ae3f

Gitpod is stuck:

![image](https://user-images.githubusercontent.com/24123/94360841-8f2e9f80-00da-11eb-8ba8-371354ea770e.png)

### Expected behavior

Opens the IDE.

### Additional information

https://f472ddfb-c0eb-424c-a19a-06360fb537e6.ws-us02.gitpod.io/#/workspace/Rocket.Chat.ReactNative
(note: this workspace will probably be already deleted)

### Example repository

https://github.com/soluvas/Rocket.Chat.ReactNative/commit/c418e66fe4242c8d022eeff93c9bae960117ae3f

**Comment by svenefftinge** [comment]
I cannot reproduce any issues. The workspace loads fine. Looks like connection issues, but I couldn't find anything specific in our system.

**Comment by ceefour** [comment]
May I suggest gitpod to show *much* more detailed messages when opening a workspace?

When it works, it works.

But problem is when it doesn't, we aren't able to give any useful info anyway then when "the issue resolves itself" it will be closed because cannot reproduce.

In my time of using gitpod, there have been intermittent issues but I can never submit a proper bug report due to lack of debug info or similar.

The general theme seems to be "delete the workspace and recreate it"..
