### ISSUE TITLE
Allow user-triggered workspace prebuilds

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#19175]
## Is your feature request related to a problem? Please describe

Currently, users are limited to predefined prebuilds, which are built automatically in a separate process. This restricts users' ability to reuse workspaces opened by other users on the same commit. Users have to rebuild things from scratch even if another user has already built that commit in their workspace.

## Describe the behaviour you'd like  

It would be helpful if any workspace loaded by a user could automatically trigger the creation of a prebuild for that commit. This would allow any other user opening the same commit to reuse the built workspace rather than rebuilding from scratch. 

Essentially, it would behave like the existing prebuilds but be triggered by a user workspace rather than an automatic separate process. This would improve efficiency and sharing of workspaces across users.

## Describe alternatives you've considered

An alternative would be to implement a manual trigger for users to request a prebuild from a workspace, rather than it being automated. However, this would place extra burden on users to remember to do this.

## Additional context

This feature would significantly improve efficiency when multiple users are collaborating on the same repositories within Gitpod. Being able to automatically reuse existing workspaces without rebuilding for every user would save time and resources.
```[tasklist]
### Tasks
```

**Comment by AlexTugarev** [comment]
> An alternative would be to implement a manual trigger for users to request a prebuild from a workspace, rather than it being automated.

@shaal, how would that be different from creating [workspace snapshots](https://www.gitpod.io/docs/configure/workspaces/collaboration#workspace-snapshots)?
