### ISSUE TITLE
unable to open git lab

### ISSUE THREAD

**Issue by shalinshah54-lab** [gitpod-io/gitpod#1919]

**Comment by shalinshah54-lab** [comment]
Every time I open access control and allow repository access under GitLab and try to connect the error message of "Sorry something went wrong" Authorization failed Please try again.

I have been trying this same thing from last few days but getting the same message

**Comment by AlexTugarev** [comment]
@shalinshah54-lab, thanks for reporting! I'll have a look...

**Comment by AlexTugarev** [comment]
@shalinshah54-lab what's your account name on GitLab.com?

**Comment by shalinshah54-lab** [comment]
shalinshah54-lab

**Comment by AlexTugarev** [comment]
@shalinshah54-lab I think I've found the issue. 

`Please confirm your GitLab account and try again.` is reported by GitLab.com. So, please go into your settings on GitLab.com and verify in order to do any OAuth based logins with GitLab. 

Actually, we should have a message to display in such cases. I'll check if that is still the case. Not sure if that may went broken due to API changes 🤷‍♂️

**Comment by shalinshah54-lab** [comment]
And also i am unable to access repository when i enter the command git push. It says manage access, and it directs me to gitLab and when connect by giving access it says to update and then i cant update. Its just a normal button nothing is happpening if i click on it.

**Comment by AlexTugarev** [comment]
@shalinshah54-lab, so you've connected with gitlab.com by now?

What's checked for GitLab on  https://gitpod.io/access-control/ for you? `respository_access` is checked. 

Is it one of your repositories? Is it public?

**Comment by shalinshah54-lab** [comment]
I have asigned it to public. I can see everything is connected here.  But when i push my file after commit command. It says manage your git access.

**Comment by AlexTugarev** [comment]
> shalinshah54-lab

I still cannot find you :-(
gitlab.com/shalinshah54-lab is a 404
