### ISSUE TITLE
The "Login" button is not displayed on the "Business" page.

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#192]
**Description**

The "Login" button is not displayed on the "Business" page.

**Steps To Reproduce:**

1. Open the site.
2. Click the "Business" button.
3. Pay attention to the header of web page. 

**Actual result:**
The "Login" button is not displayed on the "Business" page.
![loginbutton](https://user-images.githubusercontent.com/41964662/50079321-fd4def00-01f1-11e9-95b6-a0aca4316b2e.png)

**Expected result:** 
The "Login" button is displayed on the "Business" page.

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98

**Comment by AlexTugarev** [comment]
`Go to app` on www.gitpod.io ✔️
