### ISSUE TITLE
Autogenerated project name exists - s3 bucket error. Results in needing to rebuild all assets

### ISSUE THREAD

**Issue by dan-kez** [gitpod-io/gitpod#1923]
### Describe the bug

On attempt to stand up self hosted git pod in aws the following error occurs during the terraform apply.

```
Error: Error creating S3 bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
	status code: 400, request id: 39111D7BEDA61FB5, host id:XXXXXXX

  on modules/storage/main.tf line 10, in resource "aws_s3_bucket" "gitpod_storage":
  10: resource "aws_s3_bucket" "gitpod_storage" {
```

I've confirmed that `gp5577006791-storage` already exists

### Steps to reproduce
We run in `us-east-1`. I have also run without passing through `AWS_REGION_DEFAULT` and `AWS_REGION`.

The additional environment variables are due to MFA
```
docker run --rm -it \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY \
    -e AWS_SESSION_TOKEN \
    -e AWS_REGION \
    -e AWS_REGION_DEFAULT \
    -e AWS_SECURITY_TOKEN \
    -v "$PWD/awsinstall":"/workspace" \
    eu.gcr.io/gitpod-io/self-hosted/installer:latest aws
```

### Expected behavior

* A more unique project name to be used
* An ability to add a hash or other key to the s3 bucket name so all resources do not need to be recreated.

**Comment by corneliusludmann** [comment]
Thanks for reporting this issue.

@wulfthimm Is this something for you?

**Comment by arleif-dfactory** [comment]
I hit the same problem, reproduced it multiple times, and worked around it. The code appears to have some timestamp logic to generate the project name, but that doesn't kick in. All of us get the exact same project name every time we run that command. The project name is used for the bucket name, and obviously s3 doesn't like that.
To work around this:
1) Use `terraform destroy` to clean up if you have already provisioned all resources
2) Edit the main.auto.tfvars file and change the project name (make sure it is something unique)
3) Run that `docker run` command again. It will use the new project name for the bucket and that will work.

**Comment by all-the-hackz** [comment]
This is due to not initialising the default source - see https://golang.org/pkg/math/rand/#Seed

> If Seed is not called, the generator behaves as if seeded by Seed(1). Seed values that have the same remainder when divided by 2³¹-1 generate the same pseudo-random sequence.

PR https://github.com/gitpod-io/gitpod/pull/3435/
