### ISSUE TITLE
There is two same shell in the browser vscode.

### ISSUE THREAD

**Issue by hourloop-jeffcai** [gitpod-io/gitpod#19236]
### Bug description

<img width="230" alt="Screenshot 2023-12-11 at 7 07 41 PM" src="https://github.com/gitpod-io/gitpod/assets/113324408/29bdad5a-52e5-497f-80f4-eba495175b28">

### Steps to reproduce

It happens everytime I open a workspace.

### Workspace affected

https://hourloop-hourloop-f6rlouk5y2t.ws-us106.gitpod.io/

**Comment by axonasif** [comment]
Can you share your .gitpod.yml ?

**Comment by hourloop-jeffcai** [comment]
> Can you share your .gitpod.yml ?

[my_file.txt](https://github.com/gitpod-io/gitpod/files/13691604/my_file.txt)

**Comment by axonasif** [comment]
Hmm, can't spot anything obvious from it. Do you have a public repo that I can take a look at?

**Comment by hourloop-jeffcai** [comment]
https://github.com/gitpod-io/gitpod/assets/113324408/07ae6ec1-bd2a-4c1e-ba41-8c9d0353d267

Looks like it is a frontend problem.
Seems they are the same shell.

**Comment by axonasif** [comment]
@hourloop-jeffcai if it's still happening, how about you try in a different browser?
