### ISSUE TITLE
gitpoid.io websites have a memory leak

### ISSUE THREAD

**Issue by Juesto** [gitpod-io/gitpod#19249]
### Bug description

whenever i visit any gitpod.io websites other than the code web workspace pages, the tab memory is constantly increasing

### Steps to reproduce

visit gitpod.io with a logged user or gitpod.io/billing or any other dashboard related page that is not a workspace in chrome 109 under windows 7

### Anything else?

Using Gitpod Free

**Comment by axonasif** [comment]
@Juesto can you still reproduce this?

**Comment by Juesto** [comment]
@axonasif was something updated? it seems that tab memory consumption is fine now

**Comment by axonasif** [comment]
I don't know, I noticed it on Firefox as well, although it was hogging my CPU but not RAM. I suspect it's something went wrong on the frontend framework side.

**Comment by Juesto** [comment]
thanks for the response!
