### ISSUE TITLE
Support a dotfiles install script that *isn't* generic-sounding / that mentions `gitpod`

### ISSUE THREAD

**Issue by Julian** [gitpod-io/gitpod#19255]
## Is your feature request related to a problem? Please describe
I have a dotfiles install script for my dotfiles, which I essentially use everywhere, including many environments that aren't Gitpod (a new laptop, a new host in cloud infrastructure, etc.).

Whenever some Gitpod-specific logic is needed (e.g. to workaround #19254 or #19202) I would love to put that logic somewhere *not* my usual script, as it's unneeded on any other system. But right now the list of filenames gitpod will automatically run is very "Generic" sounding. Specifically, [from the docs](https://www.gitpod.io/docs/configure/user-settings/dotfiles):

> Gitpod will recognize and run one of the following install scripts from your dotfiles repository.
>     install.sh
>     install
>     bootstrap.sh
>     bootstrap
>     script/bootstrap
>     setup.sh
>     setup
>     script/setup

## Describe the behaviour you'd like
It would be nice to have at least one option there that was specifically `gitpod`-specific, rather than generic sounding. Concretely, `.gitpod-setup.sh` or `gitpod-install` or something of the sort, where I could put gitpod-specific logic if needed, and then call my "normal" installation before or after, without cluttering files that someone who has no idea what Gitpod is may encounter / be looking through.

## Describe alternatives you've considered
Even better would be adding a UI option where I could configure what the filename to run is, but I assume that's more work to touch the frontend.

**Comment by axonasif** [comment]
From your main installation script you can use some logic to check if the environment is Gitpod. We could probably add an example about this to our docs.

See https://stackoverflow.com/questions/72561982/how-to-detect-gitpod-workspace-in-bash-script
