### ISSUE TITLE
S3 policy permissions need to be set by hand for AWS installations

### ISSUE THREAD

**Issue by limuzili** [gitpod-io/gitpod#1925]
cannot initialize workspace: cannot use configured storage: cannot create bucket: The specified bucket does not exist; last backup failed: workspace does not exist. Please contact support if you need the workspace data.
Please file an issue if you think this is a bug.

### Additional information
Error: Error creating S3 bucket: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
	status code: 409, request id: B6B8929C712012CE, host id: eHoyNLm4tDRTUmgq2xQeiwqZyT2Tp9QVzP6/gUGOYV2PBc3GnJX7wX2iwrsA7ui6lYSrejIn0Ug=

  on modules/storage/main.tf line 10, in resource "aws_s3_bucket" "gitpod_storage":
  10: resource "aws_s3_bucket" "gitpod_storage” {

**Comment by corneliusludmann** [comment]
Is it a duplicate of #1923?

**Comment by limuzili** [comment]
duplicate?

No, they are two different problems, both on AWS's ec2 instance.

Details:

I authorized all the S3 policy permissions to the user automatically created by gitpod, and then the gitpod bucket was created, the instance can run normally, and the problem is solved.

**Comment by corneliusludmann** [comment]
So, if I understand this correctly, you tried to install Gitpod to AWS and it needs an additional, undocumented step (“authorized all the S3 policy permissions to the user automatically created by Gitpod”) to make it running, right? Thanks a lot for reporting this!

**Comment by corneliusludmann** [comment]
@wulfthimm Could you have a look at this issue?
