### ISSUE TITLE
Error: found in Chart.yaml, but missing in charts/ directory: docker-registry, minio, mysql

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#1926]
I get error 

> Error: found in Chart.yaml, but missing in charts/ directory: docker-registry, minio, mysql

when I run `terraform apply` on the gcp-terraform scripts directly from this repo.

Expectation: There should be no error and Terraform should run `helm dep update` as needed.

**Comment by supra08** [comment]
@meysholdt this one is related to a recent bug that was found. I would like to fix this.

**Comment by supra08** [comment]
@meysholdt it seems to have fixed, can you try it out once.

**Comment by dlbock** [comment]
Anyone else still having this issue? I'm on terraform `1.0.4` and still seeing this happen.

I'm installing the [SonarQube helm chart](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube) and getting the following error:

```
Error: found in Chart.yaml, but missing in charts/ directory: postgresql, ingress-nginx
```

`postgresql` and `ingress-nginx` are listed as dependencies in [requirements.yaml](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/requirements.yaml)
