### ISSUE TITLE
install should fail when db-migration fails

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#1928]
When `db-migration` fails, `helm install` will not terminate or (if invoked by Terraform) timeout after 5min.

It would be awesome, if
* the user could see the stdout of the `db-migrations` during install
* install would fail immediately if `db-migrations` fail.

The challenge here is that currently `db-migrations` run as a Kubernetes Job that's triggered via Helm hook and helm has (AFAIK) no way to forward the logging-output of the job to the stdout of the `helm`-process that invoked it.

**Comment by supra08** [comment]
@meysholdt I would like to investigate this and try fixing ^
