### ISSUE TITLE
Add deep integration support for Codeberg

### ISSUE THREAD

**Issue by arghyadeep-k** [gitpod-io/gitpod#1929]
Deep Integration works great with Github, Gitlab & Butbucket but isn't supported on Codeberg yet.

Requesting to implement it for Codeberg as well so that users can create a workspace by appending https://gitpod.io/# to their Codeberg URL.

**Comment by arghyadeep-k** [comment]
I'm willing to help on this but not sure where to start.

**Comment by CutestNekoAqua** [comment]
this is still relevant and needed
