### ISSUE TITLE
why IDEA Remote Development don't have gitpod plugin 

### ISSUE THREAD

**Issue by zhipengzuo** [gitpod-io/gitpod#19296]
![image](https://github.com/gitpod-io/gitpod/assets/54702578/5096968c-2cf8-4208-9794-4aa708bf5fe0)
hello, it seems Coder plugin can shows there ,can't find gitpod plugin 

in Gateway it's ok 
![image](https://github.com/gitpod-io/gitpod/assets/54702578/b0a42727-f182-4a7a-aaea-63543b97ba41)

**Comment by Derroylo** [comment]
@zhipengzuo i am not sure what you mean. You only need the gitpod plugin within the jetbrains gateway and nowhere else. So why would you expect the gitpod plugin been shown in the IDE itself?

**Comment by zhipengzuo** [comment]
@Derroylo 
1.the 2023.3.2version change the client log to IDEA log ,if we can start client from IDEA, it will more smoothly.
![image](https://github.com/gitpod-io/gitpod/assets/54702578/152a4ac3-0062-4dc5-bde8-e04fb1f4f963)

2. some change will be happen in gateway(manage app) ,we can't tell you detail there . you can write email to ask Gateway team to suit gitpod plugin

**Comment by zhipengzuo** [comment]
add <depends optional="true">com.jetbrains.gateway</depends> in plugin.xml can solve this .if gitpod want show in IDEA ,you can try this.

**Comment by zhipengzuo** [comment]
![image](https://github.com/gitpod-io/gitpod/assets/54702578/e2adb365-a622-45d8-b453-6b066d6ad746)

as I mentioned, the Remote development in IDEA is released ,but the Gateway is still beta . the the Remote development in IDEA will be more important

**Comment by akosyakov** [comment]
> add <depends optional="true">com.jetbrains.gateway</depends> in plugin.xml can solve this .if gitpod want show in IDEA ,you can try this.

@zhipengzuo sorry we have other focus right now. If you would like to you can check out this repo locally, try to change plugin.xml, build and see whether it helps 🙏 Feel free to send a PR if it does.
