### ISSUE TITLE
The "Open-Source" card size differs from other cards size in the "Pricing" block.

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#193]
**Description**

The "Open-Source" card size differs from other cards size in the "Pricing" block.

**Steps To Reproduce:**

1. Open the site.
2. Scroll to the "Pricing" block
3. Pay attention to the "Open-Source" card. 

**Actual result:**
The "Open-Source" card size differs from other cards size in the "Pricing" block.
![opensource](https://user-images.githubusercontent.com/41964662/50080569-173d0100-01f5-11e9-9b6a-4e412e69293d.png)

**Expected result:** 
The size of the "Open Source" card is the same as other card sizes in the "Prices" block.

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98

**Comment by svenefftinge** [comment]
It is intentionally so to highlight the default choice.
