### ISSUE TITLE
Phone Verification

### ISSUE THREAD

**Issue by hourloop-allentsai** [gitpod-io/gitpod#19302]
### Bug description

When I attempted to start a workspace for a project within the organization, I was prompted to verify my phone number after clicking to initiate the workspace.

<img width="587" alt="Screenshot 2024-01-04 at 9 00 16 AM" src="https://github.com/gitpod-io/gitpod/assets/155427951/d23813bf-56c1-4297-a2e1-4b90ac7ab1a3">

### Steps to reproduce

when I want to new a workspace.

**Comment by AmirAkmed** [comment]
I have had similar problem. Where I receive no pin code on my phone.

**Comment by hourloop-allentsai** [comment]
Just report this issue to them, they will verify it manually for you.

**Comment by chichi725** [comment]
I do received a call but not in a language that I could understand!
