### ISSUE TITLE
Gitpod CLI : add a find | search command

### ISSUE THREAD

**Issue by jeanphi-baconnais** [gitpod-io/gitpod#19312]
## Is your feature request related to a problem? Please describe

I use the Gitpod CLI in CICD and I would like to search in my workspaces if I have already one. 

## Describe the behaviour you'd like
A command like this could be great : `gitpod workspace search -r <my-repo> -b <branch-to-search>` with -R for repository and -b for branch 😅

**Comment by filiptronicek** [comment]
Hi @jeanphibaconnais 👋, although searching is not possible now, and I think that we will go with a route of filter flags for `workspace list` instead, there is a way to filter workspaces with grep. Filtering via all the different columns' values sounds like a good feature for the future, though.

```bash
gitpod workspace ls | grep 'gitpod-io/gitpod.*main' | awk '{print $1}'
```

**Comment by loujaybee** [comment]
Thanks for the feature request, @jeanphibaconnais ! ❤️ Out of curiosity what is the flow you're using from CI? What workspaces do you create? When and why do you create them? Trying to contextualise your request! 🙏

**Comment by jeanphibaconnais** [comment]
Thanks @filiptronicek for your response. Yes of course we can add grep instruction but if this is pertinent, getting this command in the CLI could be great 😅

@loujaybee , I am playing with the Gitpod CLI (I hope I can write a blog post to explain this in January). I prepare this project  : https://gitlab.com/jeanphi-baconnais-experiments/playing-with-gitpod-cli 
The aim is to create a Gitpod workspace when people create one issue in a project. When dev or changes are done, team member can remove the gitpod workspace.

But the last thing I have to do is to block the duplication of Gitpod workspaces. At each commit a new pipeline is running and a new Gitpod workspace is created. A search in the existing workspaces can allow me to avoid this behavior 😄  

I am asking on another point of view : as a administrator of an organization, search a workspace could be useful no?
