### ISSUE TITLE
[ide] Check location usage in Theia gitpod extension

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#1931]
In several cases we rely on current location in the frontend of the gitpod extension: 

<img width="947" alt="Screen Shot 2020-10-01 at 14 44 12" src="https://user-images.githubusercontent.com/914497/94811359-8c42f000-03f5-11eb-8d08-ca673dc0f430.png">

Current master received just recently a change to the supervisor host frontend, which changes the location url like this:

```
const ideURL = new URL(window.location.href);
ideURL.searchParams.append('gitpod-ide-index', 'true');
```

We should make sure, that this doesn't break anything. Sven pointed out that the workspace url in the "Share Running Workspace" dialog contains that suffix ☝️

**Comment by svenefftinge** [comment]
start a workspace on staging and try to share it
<img width="677" alt="Screenshot 2020-10-04 at 08 58 49" src="https://user-images.githubusercontent.com/372735/95009132-df988680-061f-11eb-8b7d-00d1410bc31a.png">
