### ISSUE TITLE
Can't download workspace on self hosted gitpod with custom minio server

### ISSUE THREAD

**Issue by pleclech** [gitpod-io/gitpod#1936]
### Describe the bug
When trying to download a workspace from a self hosted gitpod installation with a custom minio server, we got an error : 
Sorry, something went wrong...

### Steps to reproduce
- install a self hosted gitpod
- configure a minio server which is not builtin
- create a workspace
- stop the workspace
- try to download the workspace 

### Expected behavior
- we should be able to doanload the workspace without error

### Additional information
- After looking at the log i see that

> [MINIO_END_POINT](https://github.com/gitpod-io/gitpod/blob/b71f68fc1aaefbe12b62a4c6ab5137e9a3df29a7/chart/templates/server-deployment.yaml#L152) 

 and 

> [MINIO_PORT](https://github.com/gitpod-io/gitpod/blob/b71f68fc1aaefbe12b62a4c6ab5137e9a3df29a7/chart/templates/server-deployment.yaml#L154)

 are hard coded and are not taking into account what we put into **components.wsSync.remoteStorage.***

**Comment by supra08** [comment]
I would like to work on it, can you assign me @svenefftinge @corneliusludmann.
