### ISSUE TITLE
IMPORTANT ! ACCESED all of your Dev Files 

### ISSUE THREAD

**Issue by I-Cat** [gitpod-io/gitpod#1937]
### Example repository

hello im not too sure but I think I can access all of gitpod files by doing an cd  command
it puts me to the root of git pot could be bad? If the Wong person pushes code? I Hope I Helped thanks.

**Comment by I-Cat** [comment]
![Gitpod](https://user-images.githubusercontent.com/68921721/95003953-0a002a80-05b3-11eb-87ed-dc209948b254.PNG)

**Comment by svenefftinge** [comment]
I'm pretty sure that is not a problem. It is intended that you can `cd` around. It is your container and unless you invite someone no one else can access it.
