### ISSUE TITLE
The "Beta" text is not displayed on the logo of the web site. 

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#194]
**Description**

The "Beta" text is not displayed on the logo of the web site. The issue is reproduce:  Business, Imprint, Privacy Policy, Terms of Service pages.

**Steps To Reproduce:**

1. Open the site.
2. Click the "Business" button.
3. Pay attention to the logo of the web site. 

**Actual result:**
The "Beta" text is not displayed on the logo of the web site.
![logo](https://user-images.githubusercontent.com/41964662/50081411-14431000-01f7-11e9-88ae-80b594eac233.png)

**Expected result:** 
The "Beta" text is  displayed on the logo of the web site.

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98

**Comment by svenefftinge** [comment]
That's fine we will remove the 'beta' tag all together soon. :)
