### ISSUE TITLE
Github Copilot Extension Support (manual install)

### ISSUE THREAD

**Issue by bd82** [gitpod-io/gitpod#19467]
I understand it is not possible to automatically install Github Copilot in Gitpod
due to licensing issues (not published on open vsx registry).

## Problem:
What I don't understand is why an end user cannot **manually** install it  from the *.vsix file directly.
When I do so I get an error:

![image](https://github.com/gitpod-io/gitpod/assets/4233843/fcc0220f-4a47-4b43-8ee5-450bf15498f1)

## Possible Cause:
My understanding is that Copilot Ext uses `Github Auth Provider` in VScode and that Gitpod replaced the
implementation of the `Github Authentication` Extension which supplies this auth provider.

## So the question is:
Does manually installing Copilot extension not work because:
  1. A problem in gitpod's replaced `Github Auth` extension implementation?
  2. Microsoft "locking down" usage of Copilot in None pure VSCode IDE context?

## Related Issues:
- https://github.com/gitpod-io/gitpod/issues/10242
- https://github.com/gitpod-io/gitpod/issues/10032
- https://github.com/gitpod-io/gitpod/issues/5060

**Comment by akosyakov** [comment]
cc @jeanp413 could you answer?

**Comment by bd82** [comment]
I looked at this farther and I suspect that it is not related to scopes.

copilot extension seem to request only `[user:email]`
But it would still work properly if I modify it's bundled code to request something else (e.g `[workflow]`).

I suspect there is something special with the `client_id` which allows copilot to work.
Perhaps this is also why Personal Access Tokens are not supported in the copilot CLI.
- https://github.com/github/gh-copilot/issues/1
