### ISSUE TITLE
I can't get into the Gitpod workspaces

### ISSUE THREAD

**Issue by thaiminhnguyen1999** [gitpod-io/gitpod#19475]
### Bug description

I tried everything but still can't get into the Gitpod workspace
![image](https://github.com/gitpod-io/gitpod/assets/109969513/c9e96b8d-4563-4d98-b188-a32b8eba8116)
And when I open the site's Console, a lot of error messages are displayed
![image](https://github.com/gitpod-io/gitpod/assets/109969513/4605e1cf-d142-4382-9968-e493233461b2)
How to fix it?

### Steps to reproduce

When I create a new workspace on Gtpod it does the same thing

### Workspace affected

gitpodio-gitpod-064pjauehp2

**Comment by Exorcism0666** [comment]
Same issue here.

![image](https://github.com/gitpod-io/gitpod/assets/46537034/515d1091-3611-4f8d-98ab-1fad63ccede5)
