### ISSUE TITLE
Can't start workspace from a BitBucket branch `HTTPError: Not Found`

### ISSUE THREAD

**Issue by srgwsrgwetgethg** [gitpod-io/gitpod#19485]
### Bug description

Since renaming the Projects page, it seems to be impossible to create a new workspace from a prebuild. There is nowhere a button to be found to do this. Using the 'New Workspace' on the Workspaces page and the url of a (bitbucket branch) results in "We're sorry, there seems to have been an error.
HTTPError: Not Found"

gitpod has become unusable for us. We are a paying customer

### Steps to reproduce

- Create a prebuild for any branch
- Try to make a new workspace for it

### Expected behavior

Being able to create a new workspace for a prebuild.

**Comment by mustard-mh** [comment]
Hey @srgwsrgwetgethg, thank you for your feedback. Regarding your issue with creating a new workspace from a prebuild, we have removed this functionality. New workspaces should automatically use theirs prebuilds without manual intervention. 

> Using the 'New Workspace' on the Workspaces page and the url of a (bitbucket branch) results in "We're sorry, there seems to have been an error. HTTPError: Not Found"

This one seems to be a bug, would be good if you could share more information to help us debug with:
- The bitbucket branch url (hide the host if sensitive) that can't start a workspace
- A screenshot for this failed new workspace view

I'll update this issue's title, feel free to update again if it's not align to the real issue

**Comment by srgwsrgwetgethg** [comment]
After some more testing I discovered the following:
It seems that the branch url now is case sensitive, if the branch-name contains an uppercase letter, the 'new workspace' dialog suggests the same name in all lowercase, however, the when selecting the suggested name, the dialog reports 'url not found'. Creating a branch with all lowercase does work. This is a bug, url's and especially branch names should be case sensitive or at least when using the url with an uppercase letter it should be found.

However! This was a prebuild we created before the update of the projects-page. I created a new branch, all lowercase, and it seems the be impossible to create a prebuild of it.

Apart from that, we have a complex setup in which many external resources are downloaded during the prebuild. The automatically triggered prebuild with 5 necessary check ins without the option of manually triggering the prebuild is no option for us. Also we have seen that prebuilds stopped working after a while probably due to updates of gitpod. It was enough to manually start the prebuild to get it working again, now we are forced to do unnecesary commits.

This update is really, really, really very annoying.

**Comment by mustard-mh** [comment]
@srgwsrgwetgethg  I'm sorry for bring you bad experience 🙏 

> It seems that the branch url now is case sensitive, if the branch-name contains an uppercase letter, the 'new workspace' dialog suggests the same name in all lowercase, however, the when selecting the suggested name, the dialog reports 'url not found'. Creating a branch with all lowercase does work. This is a bug, url's and especially branch names should be case sensitive or at least when using the url with an uppercase letter it should be found.

Yes, I could reproduce this, I'll create an issue for it. 

As a workaround, you could try with our [Browser Extension](https://www.gitpod.io/docs/configure/user-settings/browser-extension) or use `gitpod.io/#<your_scm_url>` to create a workspace.

> However! This was a prebuild we created before the update of the projects-page. I created a new branch, all lowercase, and it seems the be impossible to create a prebuild of it.

Do you mean the new Prebuilds View can't create prebuild manually for a specified branch? yes, indeed. It's in our plan, we will add it back. We recommend users to manage their prebuild settings to trigger them automatically, may I ask you to have a try? (see screenshot below)🙏 

workaround: you could still access https://gitpod.io/projects to use old project view, it's not removed yet.

> Also we have seen that prebuilds stopped working after a while probably due to updates of gitpod.

I'm not sure how this is going to happen, prebuild is suppose to have 1 hour to run. Would you mind share more context? Like your unexpected stopped prebuilds id or url

|Prebuild Settings|
|:-:|
|<img width="1114" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/ab979b77-8fa6-4bfa-97e4-ff978a1eda19">|

**Comment by srgwsrgwetgethg** [comment]
The prebuild not starting was probably caused by a syntax error in the .gitpod.yml file. That was my mistake. The prebuild is now running. It would be nice to have some kind of feedback when a prebuild can't start because of such an error.

And a clarification of the last point: `Also we have seen that prebuilds stopped working after a while probably due to updates of gitpod.` With that I meant:
It's not that prebuilds are not running or unexpectedly stopping, it is that a new workspace based upon an existing  prebuild does not work properly anymore. The behaviour of new Workspaces based upon the same prebuild changes.

**Comment by mustard-mh** [comment]
> The prebuild not starting was probably caused by a syntax error in the .gitpod.yml file. That was my mistake. The prebuild is now running. It would be nice to have some kind of feedback when a prebuild can't start because of such an error.

@srgwsrgwetgethg  Thanks for troubleshooting and clarification!🧡  I will share this feedback to our team

> it is that a new workspace based upon an existing prebuild does not work properly anymore. The behaviour of new Workspaces based upon the same prebuild changes.

Could you share a workspace ID / url that you expect it to run base on a prebuild to us to debug?
