### ISSUE TITLE
The "Sign up" button doesn't worked on the "Imprint" page. 

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#195]
The "Sign up" button doesn't work on the "Imprint" page. The issue is reproduced: Imprint, Privacy Policy, Terms of Service pages.

**Steps To Reproduce:**

1. Open the site.
3. Scroll to the footer of the web site
2. Click the "Imprint" link.
3. Pay attention to the "Sign Up" button. 

**Actual result:**
The "Sign up" button doesn't work on the "Imprint" page.
![sign up button](https://user-images.githubusercontent.com/41964662/50083498-b0234a80-01fc-11e9-9306-dabfdcf3511d.png)

**Expected result:** 
The "Sign up" button does work on the "Imprint" page.

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98
Should the "Sign Up" button be displayed as user has to login via github?

**Comment by AlexTugarev** [comment]
this was fixed a while ago.
