### ISSUE TITLE
Gitpod variables : unable to get the value of my variable

### ISSUE THREAD

**Issue by jeanphibaconnais** [gitpod-io/gitpod#19505]
### Bug description

I don't know why, but I can't access to the value of my Gitpod variable.

### Steps to reproduce

In this project : https://gitlab.com/jeanphi-baconnais-experiments/gitpod-terminal 
I just want to use a secret stored in my Gitpod variable and a simple echo $My_var don't work.
So I used gp env to help me (cf https://gitlab.com/jeanphi-baconnais-experiments/gitpod-terminal/-/blob/main/.gitpod.yml?ref_type=heads#L12).
it's very strange, I already use variables without get this problem. Maybe a very big mistake for my part but I didn't understand.

And today, I see another error using the `gitpod login`command : 
```
Mar  5 12:25:39.595 [DEBUG] could not write token to keyring, storing in config file instead err="exec: "dbus-launch": executable file not found in $PATH"
Mar  5 12:25:39.595 [DEBUG] establishing connection to Gitpod host=https://api.gitpod.io/
loading your organizations...
Error: internal: jsonrpc2: connection is closed 

```
My token is a new token 🤷

**Comment by mustard-mh** [comment]
Hey @jeanphibaconnais , environment variables with prefix `GITPOD_` will not be attached to your workspace [[document](https://www.gitpod.io/docs/configure/repositories/environment-variables#reserved-prefix)], would you mind to change the name of your env var?

**Comment by jeanphibaconnais** [comment]
Oh ! I didn't see that. I am sure that is not a Gitpod problem but one of my eyes 😅 thanks for your response.

And do you have any ideas about the second problem with gitpod login ?

**Comment by mustard-mh** [comment]
This is Gitpod's problem that should have more graceful information provide when it's going to setup an env var with `GITPOD_` prefix. Thank you for raising this issue 🙏 

> And do you have any ideas about the second problem with gitpod login ?

@jeanphibaconnais  According to the `help` info from `gitpod login`. I thought the correct env name is `GITPOD_TOKEN`. Since we can't set such an env var (prefix with `GITPOD_`) in Gitpod, we could pass it like `gitpod login --token $MY_GITPOD_TOKEN`

```
$ gitpod login --help
Logs the user in and stores the token in the system keychain.

Usage:
  gitpod login [flags]

Flags:
  -n, --context-name string   The name of the context to create (default "default")
  -h, --help                  help for login
      --host string           The Gitpod instance to log in to (defaults to $GITPOD_HOST) (default "https://gitpod.io")
      --non-interactive       Disable opening the browser and prompt to select an organization
      --org string            The organization ID to use for the context
      --token string          The token to use for authentication (defaults to $GITPOD_TOKEN)

Global Flags:
      --config string   Location of the configuration file (default "~/.gitpod/config.yaml")
  -v, --verbose         Display verbose output for more detailed logging
```

**Comment by jeanphibaconnais** [comment]
Yes it's ok ! thanks for your help. I can close this issue.
