### ISSUE TITLE
websocket service down lead to unable to use gitpod

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#19500]
### Bug description

![CleanShot 2024-03-04 at 17 39 55@2x](https://github.com/gitpod-io/gitpod/assets/3759816/0bae59ce-8d7f-403e-aa8d-4a21d8ec3903)

```
```

### Steps to reproduce

just open repo like https://github.com/t6adev/waku-simple-todo

### Workspace affected

t6adev-wakusimpletodo-fqkbritqct9

**Comment by gengjiawen** [comment]
@akosyakov Can you take a look, this is unusable for me now.

**Comment by akosyakov** [comment]
@gengjiawen Could you check in your browser devtools do you use http2 for requests?

**Comment by gengjiawen** [comment]
@akosyakov turns out macOS doesn't support websocket proxy. thx for the debug.
