### ISSUE TITLE
my repository is public by it is not loading up on workspace  from bitbucket 

### ISSUE THREAD

**Issue by shehrozasmat** [gitpod-io/gitpod#1951]
i made my repo public on bitbucket i tried creating workspace but it didnt work as shown in the attached image
![image](https://user-images.githubusercontent.com/5235000/95105834-276afb00-0751-11eb-8018-9fea1e57b731.png)

**Comment by corneliusludmann** [comment]
The context URL that you try to use does not work. Just open your repo in your browser (https://bitbucket.org/shehrozasmat/signer/src/master/) and add the prefix `https://gitpod.io/#` in front of your URL like this:

https://gitpod.io/#https://bitbucket.org/shehrozasmat/signer/src/master/

I am curious: How did you get the URL you tried to use? By hand or is there a malicious path to it somewhere?
