### ISSUE TITLE
Need to type CTRL + key instead of CMD + key on VNC on macOS

### ISSUE THREAD

**Issue by dword-design** [gitpod-io/gitpod#19511]
### Bug description

On macOS I need to type CTRL instead of CMD key to trigger hotkeys. So e.g. I normally use CMD + R to reload a tab, in VNC I need to type CTRL + R.

I know that it's supposed to be CTRL since it's a Linux system and it's noted in the menu entries, but would be much more usable for mac users to be able to use CMD instead.

### Steps to reproduce

Open file browser, hit CMD + T to open a new tab. Nothing happens, instead CTRL + T opens a new tab.

**Comment by axonasif** [comment]
Hi @dword-design , this is related with novnc that we use. There isnt much we can do about it.

https://github.com/novnc/noVNC/issues/594

**Comment by axonasif** [comment]
You could use a desktop vnc client. See https://github.com/gitpod-io/workspace-images/tree/axonasif/add_docs/chunks/tool-vnc#details
