### ISSUE TITLE
[supervisor-frontend] annoying message box on workspace restart

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#1954]
given a timed out workspace.
when selecting "restart workspace",
you will be asked multiple times whether you really want to leave the page. after 3rd click you'd assume this is broken.

/cc. @akosyakov

**Comment by akosyakov** [comment]
I wonder is not it the same in production? If you have the workspace timeout overlay and you forgot some changes then on page closing you will have such notifications from Theia?

Or you can reproduce it always even without dirty changes?

**Comment by AlexTugarev** [comment]
> I wonder is not it the same in production? 

never seen it's popping up more than one time.

and yes, there were few unsaved changed.

**Comment by akosyakov** [comment]
yes, it is exactly the same:
<img width="800" alt="Screenshot 2020-10-06 at 14 05 11" src="https://user-images.githubusercontent.com/3082655/95199393-0c45cd00-07dd-11eb-8fb0-d232213bc6a4.png">

I will try to see whether it is possible to emulate onbefore unload event to persist local data and remove ide frame before the page reload. If not we can try to catch onbefore unload event in stop its propagation then local data will be lost, but it is the same in the production..

**Comment by AlexTugarev** [comment]
> yes, it is exactly the same:

no it's not the same.

with the supervisor changes in place you'll see the dashboard pages `stopping...` > `stopped.` on timeout. and on `restart workspace` you'll see the `reload site?` box, which reappears several times if you accept.

**Comment by akosyakov** [comment]
Eventually figure it out. That's the start workspace page is spamming with redirect events.
