### ISSUE TITLE
There is no cancel button on the new prebuild screen

### ISSUE THREAD

**Issue by srgwsrgwetgethg** [gitpod-io/gitpod#19556]
### Bug description

When testing a prebuild that contained checking a condition to stop (the output of a program) I suddenly realized that that output state will never be reached. But there is no cancel button on the new screen. Luckily the old screen is still available. It would be very nice to have a cancel button on the new prebuild screen.

### Steps to reproduce

Create workspace with a prebuild.
Start the prebuild via the new screen
No way of stopping it.

### Expected behavior

A cancel button in the prebuild screen of a specific prebuild.

**Comment by filiptronicek** [comment]
Hey @srgwsrgwetgethg 👋, I brought this issue up internally. I would like to see it back too, so let's see what we decide on, and I'll get back to you here.

**Comment by filiptronicek** [comment]
We have picked this up and implemented the ability for users to cancel running prebuilds. Hope you find it useful :)

it should be available tomorrow from about 2PM CET on gitpod.io
