### ISSUE TITLE
Unable to set GITPOD_IMAGE_AUTH environment variable

### ISSUE THREAD

**Issue by webkp** [gitpod-io/gitpod#19574]
### Bug description

When attempting to configure private Docker images in Gitpod following the documented instructions at https://www.gitpod.io/docs/configure/workspaces/workspace-image#use-a-private-docker-image, I encounter an error message.
 
Despite the documentation stating that credentials can be provided by setting `GITPOD_IMAGE_AUTH` as a repository-level environment variable, I receive a __"Repository: Error: Variable name with prefix 'GITPOD_' is reserved"_ error when attempting to do so. Additionally, trying to set this variable at the user level results in a __"User: Name with prefix 'GITPOD_' is reserved"_ error.

### Steps to reproduce

Go to Gitpod's Dashboard and try to set `GITPOD_IMAGE_AUTH` as a repository-level environment variable.

### Expected behavior

Be able to set `GITPOD_IMAGE_AUTH` as a repository-level environment variable.

### Anything else?

Not sure but maybe was introduced by https://github.com/gitpod-io/gitpod/pull/19547 ?

**Comment by mustard-mh** [comment]
> Not sure but maybe was introduced by https://github.com/gitpod-io/gitpod/pull/19547 ?

Yes, sorry about regression  🙏 . That PR is about to avoid reserved env var name prefix `GITPOD_` [[doc](https://www.gitpod.io/docs/configure/repositories/environment-variables#reserved-prefix)]

I'll create a PR to whitelist `GITPOD_IMAGE_AUTH `

**Comment by webkp** [comment]
> I'll create a PR to whitelist GITPOD_IMAGE_AUTH 

Sounds great, thank you very much @mustard-mh 👍

**Comment by mustard-mh** [comment]
@webkp Thank you so much for reporting 🙏 fixing should be landed on gitpod.io at tomorrow UTC 8:00 AM

**Comment by webkp** [comment]
> fixing should be landed on gitpod.io around UTC 8:00 AM tomorrow

awesome, thank very much @mustard-mh for the very quick fix! 👍😊
