### ISSUE TITLE
Selectable permissions for new members

### ISSUE THREAD

**Issue by DLBPointon** [gitpod-io/gitpod#19599]
## Is your feature request related to a problem? Please describe

I am running GitPod as an educational tool, and requesting new members join means they join the organisation as a Member which is undesirable as it means they can see a lot more than I want them to. This should be a drop-down so I can default this behaviour to Collaborator or perhaps a set of custom permissions (although that doesn't matter right now).

## Describe the behaviour you'd like
A selectable drop-down in the organisation's settings page to select the default permissions given to someone using the invite link.

## Describe alternatives you've considered
The alternative is going through one-by-one and setting the permissions manually which isn't helpful when I'll be setting this up for >1000 people.
This would be useful even if it was part of the paid tier.

## Additional context
This is so these members can join my organisation and make use of the Prebuilds without access to anything else.

**Comment by svenefftinge** [comment]
This is now available. Please check organisation settings.
