### ISSUE TITLE
Commands following `gp ports await` or `gp open` do not run 

### ISSUE THREAD

**Issue by tomwheeler** [gitpod-io/gitpod#19591]
### Bug description

As described more thoroughly in [this Discord thread](https://discord.com/channels/816244985187008514/1223357578029961398), I observe that the command following `gp ports await` or `gp open` in a task does not run. In the case of `gp ports await`, the port is bound and the `gp ports await` seems to acknowledge this with an "OK" message, as per [this screenshot](https://media.discordapp.net/attachments/1223357578029961398/1223381682451779707/image.png?ex=6619a5fa&is=660730fa&hm=470af5d4a6e53bce51e425e781c0b935920025c62b917bd697886e1fb55ab3a7&=&format=webp&quality=lossless&width=1842&height=1256), but the `gp preview command` that follows it does not seem to get executed because the page that it should display is not visible in the workspace even several minutes later.

This is not limited to `gp ports await` because I observe similar behavior with `gp open`, specifically in [this task of my .gitpod.yml file](https://github.com/temporalio/edu-102-go-code/blob/t102-go-maintenance-202403/.gitpod.yml#L33-L36). The `README.md` file does not open and the terminal does not exit.

In both cases, though, the commands will eventually behave as expected if the user clicks to set focus within the browser's viewport. That's not an obvious workaround though, and most users would likely conclude that the workspace didn't initialize properly and just give up.

### Steps to reproduce

In Safari or Google Chrome (I've reproduced this in both, but have not tested other browsers):

1. Click [this link](https://gitpod.io/#https://github.com/temporalio/edu-102-go-code/tree/t102-go-maintenance-202403) to launch the workspace
2. Wait for several minutes and observe that neither the Web app on port 80 nor the `README.md` file was displayed as it should have been
3. Click around within the browser window's viewport and there's a good chance that doing so will cause both the Web app on port 80 and the `README.md` file to finally be shown 

This seems to be an intermittent problem, but it happens almost all of the time.

### Expected behavior

Should display a preview of the README file on the left of the main workspace area and the embedded browser to its right

### Example repository

Click [this link](https://gitpod.io/#https://github.com/temporalio/edu-102-go-code/tree/t102-go-maintenance-202403) to launch the workspace.

The `.gitpod.yml` file [https://github.com/temporalio/edu-102-go-code/blob/t102-go-maintenance-202403/.gitpod.yml](is here).

**Comment by svenefftinge** [comment]
Sorry, for the late follow up. I'm not sure I can reproduce or undrstand the problem.
When clicking on the link to launch the workspace my workspace opens with a browser to 8080.
<img width="1782" alt="Screenshot 2024-05-21 at 13 27 47" src="https://github.com/gitpod-io/gitpod/assets/372735/98a91efd-247c-419d-88bf-f48d8870517e">

**Comment by tomwheeler** [comment]
We eventually figured it out. Adding another `openMode: split-right` to our GitPod config file fixed the problem. I'll close the issue.
