### ISSUE TITLE
[design doc] Workspace teardown script/command

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#1961]
Moved to [Notion](https://www.notion.so/gitpod/Teardown-Command-0b1cdd2675994c4ca5e2baf416f92e8c)

**Comment by svenefftinge** [comment]
> the workspace's supervisor to execute the teardown command and then delete the container. This would 

what about?

**Comment by svenefftinge** [comment]
> for now we do not provide access to any log output produced by the teardown command

I think we should at least write the logs into a file next to where we have the logs for prebuilds.

**Comment by csweichel** [comment]
> > We would remove the BackupService and add a function to supervisor's ControlService
> 
> Instead of naming the API after what the task lifecycle (`teardown`), I'd like to name the API after the lifecycle event `onPreStop`. It is the business of supervisor to do the right thing within. I.e. it not only calls the `teardown` tasks but other things as well (e.g. FWB)

So far supervisor's API always describes operations, not events or hooks. The thing that we're asking supervisor to do is to teardown the workspace. To avoid confusion we could call it `PrepareForStop` instead of `TeardownWorkspace` though. WDYT?

**Comment by corneliusludmann** [comment]
Thanks for writing this down, @csweichel! :+1: 

I only have a few questions of understanding:

> Note: this CLI must not return before the teardown command has finished executing. If it did the timing guarantees/mechanism described above would break.

Is this also the case for the currently implemented FWB CLI call? If not, why do the requirements differ here?


> In the FWB case, we use the ws-sync InWorkspaceHelper to pause the IDE process group before performing the backup.

The “pause IDE” call is not implemented yet, right?
https://github.com/gitpod-io/gitpod/blob/758ccbe50dd9286c351573cbb41e6d9f2781a6a8/components/ws-sync/pkg/syncd/service.go#L669-L675

The actual pause action seems to be implemented.
https://github.com/gitpod-io/gitpod/blob/758ccbe50dd9286c351573cbb41e6d9f2781a6a8/components/supervisor/pkg/supervisor/supervisor.go#L255-L265

Is it just the call of [`PauseTheia`](https://github.com/gitpod-io/gitpod/blob/758ccbe50dd9286c351573cbb41e6d9f2781a6a8/components/ws-sync-api/workspace.proto#L20) that is missing? Or is it more work to do?

>  After 15 seconds we'd kill the teardown if its still running, and trigger the FWB.

I wonder if 15 seconds isn't a bit short for some applications!? Just to get a better understanding: What do we lose if we set the `terminationGracePeriod` to e.g. 60 seconds and allow 45 seconds for `teardown`?

**Comment by csweichel** [comment]
> Thanks for writing this down, @csweichel! 👍
> 
> I only have a few questions of understanding:
> 
> > Note: this CLI must not return before the teardown command has finished executing. If it did the timing guarantees/mechanism described above would break.
> 
> Is this also the case for the currently implemented FWB CLI call? If not, why do the requirements differ here?
> 

Indeed it is. I thought it important to mention it here because unlike for FWB, the timing is important for the teardown. If the FWB call doesn't delay the container removal, that might result in some data loss worst case. If the teardown call doesn't delay the container removal, the teardown command might not even be executed. But you're right, the timing matters for both cases.

> > In the FWB case, we use the ws-sync InWorkspaceHelper to pause the IDE process group before performing the backup.
> 
> The “pause IDE” call is not implemented yet, right?
> https://github.com/gitpod-io/gitpod/blob/758ccbe50dd9286c351573cbb41e6d9f2781a6a8/components/ws-sync/pkg/syncd/service.go#L669-L675
> 
> The actual pause action seems to be implemented.
> https://github.com/gitpod-io/gitpod/blob/758ccbe50dd9286c351573cbb41e6d9f2781a6a8/components/supervisor/pkg/supervisor/supervisor.go#L255-L265
> 
> Is it just the call of [`PauseTheia`](https://github.com/gitpod-io/gitpod/blob/758ccbe50dd9286c351573cbb41e6d9f2781a6a8/components/ws-sync-api/workspace.proto#L20) that is missing? Or is it more work to do?

That's correct. The Theia pause isn't used yet, which in hindsight looks more like an oversight than intentional :/

> 
> > After 15 seconds we'd kill the teardown if its still running, and trigger the FWB.
> 
> I wonder if 15 seconds isn't a bit short for some applications!? Just to get a better understanding: What do we lose if we set the `terminationGracePeriod` to e.g. 60 seconds and allow 45 seconds for `teardown`?

In the past we've struggled with workspaces taking "forever" to stop (several minutes). To curtail this behaviour and provide sensible stopping times we've settled on the default grace period of 30 sec (which also is the Kubernetes default). We could experiment with increasing this period and giving the teardown command more time. We could even use different grace periods, depending on if there's a teardown command or not (what happens if you just added one in this current workspace instance?).

I'd propose we start with 15 seconds, because increasing this time guarantee is easier than reducing it.
