### ISSUE TITLE
Not anymore persisting the /workspace content populated by custom .Dockerfile

### ISSUE THREAD

**Issue by complyue** [gitpod-io/gitpod#19615]
### Bug description

Content populated under /workspace/ during custom .dockerfile building, ultimately get lost when the workspace is started.

### Steps to reproduce

https://gitpod.io/#https://github.com/complyue/tour/blob/master/welcome.edh

### Expected behavior

Haskell toolchain (GHCup and pieces it installs) installed during custom .Dockerfile building should persist as before.

### Example repository

https://github.com/complyue/tour

### Anything else?

It works before, not been touching the env until recently. /workspace should persist, right?

**Comment by complyue** [comment]
I configured prebuilds, and it's still not persisted on ws open. What can go wrong?

**Comment by axonasif** [comment]
Hi @complyue, I see that you're writing files to `/workspace` from your dockerfile. Please use a different location (or leave the default location value) such as `$HOME`.

**Comment by complyue** [comment]
Hi @axonasif , but per the doc, only `/workspace` will persist, `$HOME` will get reset every time the ws is restarted, that situation has changed? Haskell GHC toolchain is rather heavy (10 GB at least) not feasible to setup every time the ws is started.

**Comment by axonasif** [comment]
@complyue that is true but not when you do it from a dockerfile, since that will bake you changes into the image/container itself in a static way.

**Comment by axonasif** [comment]
BTW, I was referring to this part of your dockerfile code, my suggestion was to change the paths to somewhere else other than `/workspace` (e.g. `$HOME`)

https://github.com/complyue/tour/blob/master/.gitpod.Dockerfile#L10-L17

**Comment by complyue** [comment]
> that will bake your changes into the image/container itself in a static way

> my suggestion was to change the paths to somewhere else other than `/workspace` (e.g. `$HOME`)

@axonasif , persisted over ws restart is a requirement, can `$HOME` or some other dir you'd suggest warrant that nowadays? They used to be reset every time ws restarts.

**Comment by axonasif** [comment]
> They used to be reset every time ws restarts.

Yes, they still do. But your workspace docker image is static once it's built, so whatever you put in those dirs from your **dockerfile** will be there between restarts

**Comment by axonasif** [comment]
@complyue prebuilds work differently now. Only members [added](https://www.gitpod.io/docs/configure/orgs/members#add-users-to-an-organization) to your Gitpod organization can access the prebuild: https://www.gitpod.io/docs/configure/repositories/prebuilds#prebuilds-are-only-available-to-organization-members

I took a look at your .gitpod.yml and .gitpod.Dockerfile, I think we can approach this problem in a different way. Can you raise a support ticket from [here](https://www.gitpod.io/contact/support)?

**Comment by complyue** [comment]
@axonasif thanks for your kind advice! submitted.

![image](https://github.com/gitpod-io/gitpod/assets/15646573/f5d740e3-aeac-490e-9a32-ebb77fe29b4d)
