### ISSUE TITLE
git does not detect file being closed by editor

### ISSUE THREAD

**Issue by LinqLover** [gitpod-io/gitpod#1967]
### Describe the bug
If I type `git commit` into a console and close the commit message tab, git does not detect this.

### Steps to reproduce
1. Open a repository in gitpod
2. Type into the console:
   ```terminal
   $ git commit --allow-empty
   ```
3. A tab for the commit messages opens, close it [optionally: edit it before and save the changes]

### Expected behavior
The commit is completed and git terminates.

### Actual behavior
The git command is still running and saying:
```terminal
$ git commit --allow-empty
hint: Waiting for your editor to close the file...
```

**Comment by akosyakov** [comment]
Are you sure that you don't have the same workspace opened in another window somewhere? It is known bug unfortunately that we wait for all windows.

**Comment by LinqLover** [comment]
Hm, I cannot reproduce the issue right now, maybe I had opened it twice ... If there is already a known bug, this issue is probably redundant. Thanks for the reply!
