### ISSUE TITLE
Example devcontainer for docker in docker

### ISSUE THREAD

**Issue by nhorton** [gitpod-io/gitpod#19689]
We use Gitpod largely because it supports Docker-compose inside the main docker image. We now want to use devcontainer files for having VSCode properly run some of the functionality inside an inner docker container, but normal guides on how to do that end up with something that conflicts with the remote docker container of Gitpod itself.

Can you help with an example of a docker-in-docker devcontainer file for Gitpod?

**Comment by svenefftinge** [comment]
You can run devcontainers in Gitpod, but I'm not sure devcontainer with docker in docker can work in gitpod, as gitpod workspaces are themselves run in docker. So this would be two docker in dockers. 
Can you provide an example repository that allows us to reproduce this?
