### ISSUE TITLE
Gitpod stuck in "Allocating Resources"

### ISSUE THREAD

**Issue by jrdzha** [gitpod-io/gitpod#19694]
### Bug description

Gitpod is stuck in allocating resources.

![Screenshot 2024-05-01 at 11 38 39 AM](https://github.com/gitpod-io/gitpod/assets/12738689/48215fc0-bca7-4b31-9fbd-c9268ab8f383)

### Steps to reproduce

Open a gitpod.

### Workspace affected

polyture-askedith-wc3d1xscw0j

### Expected behavior

Opening a gitpod should work.

**Comment by zacanger** [comment]
Same. Also prevented me from stopping a workspace, I ended up just deleting it.

**Comment by TulaUnogi** [comment]
Same for myself and others I know about. It also doesn't allow creating new workspaces.
