### ISSUE TITLE
 It is possible to create a new file without extension specified.

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#197]
It is possible to create a new file without extension specified.

**Steps To Reproduce:**

1. Login to the site 
2. Start some workspaces.
3. Create a new file without extension specified (e.g. "newfile").
4. Pay attention to the created file

**Actual result:**
It is possible to create a new file without extension specified.
![newfile](https://user-images.githubusercontent.com/41964662/50091353-d3a5bf80-0213-11e9-9d18-68e048e9f302.png)

**Expected result:** 

It is not possible to create a new file without extension specified.

**Additional Information:**
May,  show a message if the file was created without the specified extension.
Win 10 Google Chrome 71.0.3578.98

**Comment by svenefftinge** [comment]
Creating files without extension should be supported. Works as expected.
