### ISSUE TITLE
Pre-builds don't work for PRs

### ISSUE THREAD

**Issue by skinny85** [gitpod-io/gitpod#1971]
### Describe the bug

In our [aws/aws-cdk project](https://github.com/aws/aws-cdk), we have pre-builds enabled. However, for some reason, they don't for PRs, even though created from the same repository (example: https://github.com/aws/aws-cdk/pull/10730 ).

The [documentation](https://www.gitpod.io/docs/prebuilds) states that these should be enabled by defaults.

The prebuilds still work fine for the default branch (`master`).

### Steps to reproduce

1. Go to https://github.com/aws/aws-cdk/pull/10730
2. Click "Gitpod" in the "Show all checks" box on the bottom.
3. See that a build is triggered in the workspace.

### Expected behavior

The workspace should be pre-built.

### Example repository

https://github.com/aws/aws-cdk/pull/10730

--------------------------------

Thanks,
Adam

**Comment by jankeromnes** [comment]
Hi @skinny85!

By default, prebuilds are disabled for Pull Requests from forks:

https://github.com/gitpod-io/gitpod/blob/1548367b5cc61c8e7baf4c6e1508972afe349038/components/server/ee/src/prebuilds/github-app-rules.ts#L21

https://www.gitpod.io/docs/prebuilds/#configure-the-github-app

You can enable them by adding this to your `.gitpod.yml`:

```yml
github:
  prebuilds:
    pullRequestsFromForks: true
```

**Comment by skinny85** [comment]
Hi @jankeromnes ,

the PR I gave as an example (https://github.com/aws/aws-cdk/pull/10730) does not come from a fork - it was created from a branch of the repository itself.

Thanks,
Adam

**Comment by svenefftinge** [comment]
Thank you for bearing with us on this and providing all this feedback. I looked into the system and found that a lot of the prebuilds from your repo timeout after 1h. Do you see any possibilities to make prebuilds run in less than 1h even on very packed nodes?
FYI: Revising the prebuild feature in order to bring more visibility to these kind of issues is top on our list and will be tackled next month.

**Comment by skinny85** [comment]
Thanks @svenefftinge . Unfortunately, the pre-build already does the minimum amount of work (no unit tests, no compatibility check, etc.), and I can't come up with a way to make it shorter.

It's true that our build times have increased lately, and so that might be the reason for the recent timeouts.

I'm looking forward to seeing what you come up with for visualizing these!

Thanks,
Adam
