### ISSUE TITLE
Unable to uninstall this extension for SSH remote

### ISSUE THREAD

**Issue by jimbozhang** [gitpod-io/gitpod#19740]
Does this issue occur when all extensions are disabled? Yes

- VS Code Version: 1.78.1
- OS Version: Any

I am unable to uninstall the [Gitpod Remote](https://marketplace.visualstudio.com/items?itemName=gitpod.gitpod-remote-ssh) extension for SSH remote hosts. Once I uninstall it and reload VSCode, the extension always reinstalls itself automatically, regardless of whether the sync was enabled or disabled. This issue does not occur with other extensions.

**Comment by Vaviloff** [comment]
Thanks, Anton, indeed that was the reason why the extension would come back to haunt me 😅
