### ISSUE TITLE
How can we save our work in our repository in GitHub ?

### ISSUE THREAD

**Issue by Bapt5** [gitpod-io/gitpod#1976]
Hello 
I haven't how can we save our work in our repository in GitHub ? Can someone help me ?

**Comment by wulfthimm** [comment]
Hi,
if you want to contribute, you can fork this repository, commit your changes to your fork and make a pull-request.
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by Bapt5** [comment]
@wulfthimm I don't want to contribute I just want to save MY work on MY account.

**Comment by svenefftinge** [comment]
You need to push your changes back using `git`. This can be done either via command line or by using the Git UI in the Gitpod IDE. See https://www.gitpod.io/docs/git/
