### ISSUE TITLE
It is not possible to delete a new folder if its name contains non-latin symbols

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#198]
**Description**

It is not possible to delete a new folder if its name contains non-latin symbols

**Steps To Reproduce:**

1. Login to the site 
2. Start some workspaces
3. The created folder (name contains non-latin symbols)
4. Delete a new folder 
5. Pay attention to the file tree

**Actual result:**
It is not possible to delete a new folder if its name contains non-latin symbols
Video: https://www.dropbox.com/s/uzaanr7e5584nlt/DeleteFolder.mp4?dl=0

**Expected result:** 

It is  possible to delete a new folder if its name contains non-latin symbols

**Additional Information:**
If you close / open the tree, the new folder will be deleted
Win 10 Google Chrome 71.0.3578.98

**Comment by svenefftinge** [comment]
Are you sure this has todo with the non-latin characters?
I.e. does it work with ascii only?

**Comment by tarasdidyk** [comment]
Yes, I am sure. This only works with ASCII.
