### ISSUE TITLE
Add an option to disable automatic generation of `gitpod.yml`

### ISSUE THREAD

**Issue by catfoolyou** [gitpod-io/gitpod#19804]
## Is your feature request related to a problem? Please describe
For some reason Gitpod tends to automatically create a `gitpod.yml` file when I create a new workspace, meaning that when it loads up it's already doing something, most of the time something that gets in the way.

## Describe the behaviour you'd like
There should be some sort of checkbox or option to generate a `gitpod.yml` when creating a new workspace.

**Comment by axonasif** [comment]
Hi @catfoolyou 👋 

Please see https://github.com/gitpod-io/gitpod/issues/7516

**Comment by catfoolyou** [comment]
Alright, thanks.
