### ISSUE TITLE
Unable to run workspaces

### ISSUE THREAD

**Issue by chris3522** [gitpod-io/gitpod#1981]
### Describe the bug

All my workspaces are not launched or are suddenly stopped : here two errors with two workspaces

`Last run 5 minutes ago: last backup failed: cannot delete workspace from store. Please contact support if you need the workspace data.`

And,

`Last run 4 minutes ago: cannot pull image: Back-off pulling image "reg.gitpod.io:8081/remote/3af22935-a5bf-4b9f-8795-c918769f44f6"`

### Additional information
id: f3471083-9686-4c81-a0c7-6dbff0b983bf
id: e33b5473-26f3-4084-8c96-d57990ea4541

**Comment by corneliusludmann** [comment]
Thanks for reporting. Duplicate of #1979? Should be fixed now.

**Comment by chris3522** [comment]
Yes i's fixed, many thanks.
