### ISSUE TITLE
After cancelling a pers. subscription users should access remaining credits before subscription end date 

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/gitpod#1989]
**Based on user feedback** 

After consolidating accounts and moving a user with a Personal Account to another account held by the same company, Gitpod told the user he will able to use his remaining credits and then he'll be moved to an open source account.

After logging in a day later, he was told: 

> This repository is private
> Gitpod is free for public repositories. To work with private repositories, please select a subscription.

Next to the UI bug in the dark mode of the dashboard (see below), it still shows he has almost 100h left in the valid subscription. Which he should be able to use w/o restrictions for both private and public repos.  

![image](https://user-images.githubusercontent.com/22498066/95872417-10d72c00-0d6f-11eb-826c-59f32d0daeb3.png)

**Comment by svenefftinge** [comment]
The dark mode bit is `fixed-not-deployed` 🏷️
