### ISSUE TITLE
Can I deploy it locally?

### ISSUE THREAD

**Issue by zhiyue** [gitpod-io/gitpod#199]

**Comment by svenefftinge** [comment]
We will have a self-hosted version ready around February.

**Comment by sandeepone** [comment]
Any update?

**Comment by jankeromnes** [comment]
Gitpod's self-hosted version is almost ready, and should be ready to try (in Beta) in a few weeks.

Once all the rough edges have been ironed out, we'd like to release a public Helm chart, so that anyone can easily install Gitpod in their own Kubernetes cluster.

**Comment by huseyin** [comment]
thanks for your good news @jankeromnes i'm looking forward the Gitpod's next releases.
