### ISSUE TITLE
Drupal 11 support

### ISSUE THREAD

**Issue by Adrianm6254** [gitpod-io/gitpod#19950]
### Bug description

I wish to start developing using Drupal 11 but the ddev build fails.  I get an error:

`Failed to start project(s): the n2c-base11-d project has an invalid app type: drupal 
the n2c-base11-d project has an invalid app type: drupal`

When I do a ddev version on the gitpod is v1.22.6                                 

There is a ddev update that needs to be applied   DDEV version     v1.23.1  

### Steps to reproduce

Install the site

### Example repository

![Screenshot_20240620_135603](https://github.com/gitpod-io/gitpod/assets/13153806/753c2b74-0576-46e5-b841-83185941346c)

**Comment by axonasif** [comment]
Hi @Adrianm6254, I believe something is wrong with your code/setup. Can you refer to the ddev docs? I might be able to provide you a solution or hints if your repo is public.

**Comment by webkp** [comment]
@Adrianm6254 the ddev version installed comes from the image you are using (defined in `.gitpod.yml`). That's not something Gitpod is in charge of. 

To use ddev `1.23.2` you may use this image from ddev in your `.gitpod.yml`:
`image: ddev/ddev-gitpod-base:20240614`
(Source/Example: https://github.com/ddev/ddev-gitpod-launcher/blob/main/.gitpod.yml)

For a more drupal specific image you may check out this one: 
https://github.com/shaal/ddev-gitpod

**Comment by katannshaw** [comment]
@Adrianm6254 I'm not sure if it's exactly the same issue, but I was getting the exact same error `project has an invalid app type: drupal`

The issue for me was that I had multiple versions of ddev installed through homebrew manual installs. I followed the steps from the [DDEV docs: Why do I have an old DDEV? FAQ](https://ddev.readthedocs.io/en/stable/users/usage/faq/#why-do-i-have-an-old-ddev) and it and it solved the issue for me.

Hope it helps.

Kat Shaw
