### ISSUE TITLE
[GitLab] Gitpod cannot find Dockerfiles in sub-directories

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#1995]
### Describe the bug

When specifying a Dockerfile in your `.gitpod.yml` on GitLab, but the Dockerfile is located in a sub-directory (i.e. not in repo root), then Gitpod fails with:

<img width="600" alt="Screenshot 2020-10-14 at 11 47 56" src="https://user-images.githubusercontent.com/599268/95972770-23a33c80-0e13-11eb-9328-84b12e97511d.png">

### Steps to reproduce

1. Create private repo in GitLab
2. Create `.gitpod.yml` with:

```yml
image:
  file: test/Dockerfile
```

3. Create `test/Dockerfile` with:

```Dockerfile
FROM gitpod/workspace-full
```

### Expected behavior

Opening the private GitLab repo in Gitpod should work.

**Comment by svenefftinge** [comment]
deployed now
