### ISSUE TITLE
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

### ISSUE THREAD

**Issue by tekumara** [gitpod-io/gitpod#1997]
### Describe the bug
Not able to install python packages inside a virtualenv.

### Steps to reproduce

1. Open https://gitpod.io/#https://github.com/tekumara/typed-cookie
2. Source the venv: `. venv/bin/activate`
3. `pip install pytest`

### Expected behavior
The python package is installed into the virtualenv

### Additional information
```
(venv) gitpod /workspace/typed-cookie $ pip install pytest
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
WARNING: You are using pip version 20.2.1; however, version 20.2.3 is available.
You should consider upgrading via the '/workspace/typed-cookie/venv/bin/python3 -m pip install --upgrade pip' command.
```
### Example repository

https://github.com/tekumara/typed-cookie

**Comment by AlexTugarev** [comment]
@tekumara please make sure to store the packages of your virtual envs under `/workspace`, in order to preserve them at workspace restart, or for prebuilds. 

currently, only the `/workspace` location is backed up. this limitation will be removed in a future release.

**Comment by svenefftinge** [comment]
Has this issue been resolved and can be closed?
