### ISSUE TITLE
Changelog website link broken

### ISSUE THREAD

**Issue by dannaf** [gitpod-io/gitpod#19972]
### Bug description

The bottom of the Gitpod.io website links to a changelog at https://www.gitpod.io/changelog, but this website returns a 500 error page instead of displaying the changelog.

### Steps to reproduce

1. Go to https://www.gitpod.io/changelog and observe a 500 error page.

or

1. Go to gitpod.io and scroll to the bottom and click on changelog; observe 500 error page.

### Expected behavior

Should see the changelog; should not see a 500 error page.

### Anything else?

I guess the changelog should then be updated to reflect that the changelog link has been repaired -:) just kidding, this is a very minor change/bugfix. (How strictly does Gitpod follow [semantic versioning](https://semver.org/)?&mdash;I don't know, I haven't seen the changelog... ^_^)

**Comment by Siddhant-K-code** [comment]
https://www.gitpod.io/changelog is working fine 🤔

<img width="1511" alt="image" src="https://github.com/gitpod-io/gitpod/assets/55068936/0c7feeb0-4bb6-49e3-b698-d1abe6fcd969">
