### ISSUE TITLE
2024-06-30T16:57:58Z ERR node does not have enough balance to register, skipping. addr=allo1rzmu63kvkqfrs0j35x02v2jdhjvp035j4dsa7p topic=1

### ISSUE THREAD

**Issue by ksunil2** [gitpod-io/gitpod#19983]
### Bug description

i have fees but showing i dont i have fees

### Steps to reproduce

nothing

### Workspace affected

allora networks and

**Comment by axonasif** [comment]
Can you elaborate?

**Comment by blockchainguy1** [comment]
I think there needs to be a minimum balance to register a node. I tried with two days of faucet claim it isn't enough. Will update once I know exactly required ALO balance value.

**Comment by blockchainguy1** [comment]
After you restart your PC or docker use following command

Open docker 1st
#1 cd allora-chain
#2 cd basic-coin-prediction-node
#3 sudo docker compose up -d
#4 docker ps

**Comment by fessnecro** [comment]
same problem

**Comment by Sarafaniuk** [comment]
same problem, how to fix it, any solution ?
