### ISSUE TITLE
Gitpod k3 builds

### ISSUE THREAD

**Issue by markcalloway** [gitpod-io/gitpod#1998]
Hi

looking at the various builds

https://console.cloud.google.com/gcr/images/gitpod-core-dev/EU/build/gitlab-k3s?gcrImageListsize=30

anything upto  master.90 or so would work fine with docker-compose or docker run using something like

docker run --privileged=true -ti  -e DOMAIN='xxx' -e  DNSSERVER='xx' -p 80:80  -v $(pwd)/values.yaml:/values/values.yaml  
	-v $(pwd)gitpod-docker:/var/gitpod/docker  eu.gcr.io/gitpod-core-dev/build/gitpod-k3s:master.90

however all the versions after that just exit out of docker when running

could we have detailed instructions on how to run the later builds in docker?

**Comment by corneliusludmann** [comment]
The current master has a bug in the `entryscript.sh`. It should work in docker-compose but not with docker run. I'm currently working on a fix and let you know when it's done.

I'm also working on documentation. However, the docker containers with k3s are still experimental.

**Comment by markcalloway** [comment]
apart from docker are there any recommendation/tips on how to get this running on an on premises server.     

could install kubernetes but how would you go from a git clone of https://github.com/gitpod-io/gitpod   to  setting it up on kube?

could do helm charts but latest version seems to be a month or two behind

**Comment by corneliusludmann** [comment]
Our latest official release is 0.5.0 from 2020-08-25T13:04:24.130Z (see https://charts.gitpod.io/). We are working currently on a new release but have to fix some bugs first.

You'll find the latest helm charts here: https://github.com/gitpod-io/gitpod/tree/master/chart
