### ISSUE TITLE
Sometimes Snapshots don't start directly after creation

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#200]
**Describe the bug**
I created a snapshot of a workspace, but the link only yields

>Sorry, that should not have happened!
>snapshot/028b64cf-669d-4680-9e94-741129ab8945
>Please file an issue if you think this is a bug.

It seems that it starts working when the workspace is properly stopped.

**To Reproduce**
Create a snapshot and open it in the same browser -> error
Close the original workspace and try the same link again -> error
Wait until a while and try the link again -> workspace opens

**Expected behavior**
The snapshot should be available immediately, or at least there should be a message that it can take a while until you can use it or what you have to do (stop original ws?) to make it work.

**Comment by svenefftinge** [comment]
I cannot reproduce it has definitely nothing to do with running workspaces. It could be a timing issue, i.e. the data hasn't made it to the database. But this should only be possible across regions. I guess you didn't change the region when you tried, or did you send the snapshot to someone else?

**Comment by svenefftinge** [comment]
I still cannot reproduce it. The snapshot above works now.
Seems like there is a latency.

**Comment by svenefftinge** [comment]
@32leaves Any idea what could cause it?

**Comment by JanKoehnlein** [comment]
Yes, after some time, the snapshots work and they seem to stay stable. It's just right after creation that this bug appears.
