### ISSUE TITLE
SSL error on the workspace.

### ISSUE THREAD

**Issue by sysop-88** [gitpod-io/gitpod#20003]
### Bug description

I have an error for the workspace with the **SSL** for **Gitpod**. The **SSL** cert is not for the workspace sub-domains, so it gives a **SSL common name error** . The browser tells you it is not trusted because the cert is not for workspace sub-domains.

### Steps to reproduce

Go to **Gitpod** a workspace with a **(chrome) browser**.
Then, it tells you the cert is not trusted. 

### Workspace affected

sysop88-test2-z2a06p83bmu

### Expected behavior

Regular workspace

### Anything else?

no

**Comment by axonasif** [comment]
Does it happen on every workspace? And have you tried in a different browser?

**Comment by axonasif** [comment]
Closing it here since you've also raised a support ticket.
