### ISSUE TITLE
dotfiles bootstrapping failed

### ISSUE THREAD

**Issue by dalisoft** [gitpod-io/gitpod#20005]
### Bug description

I'm getting 
```
Unable to open universal variable file '/': Permission denied
```

or `ls not found` when using Terminal on VSCode. 

<img width="1274" alt="Screenshot 2024-07-06 at 06 43 45" src="https://github.com/gitpod-io/gitpod/assets/3511344/b953872c-6b74-4819-ba0b-0681289e8b0d">
<img width="1274" alt="Screenshot 2024-07-06 at 06 44 30" src="https://github.com/gitpod-io/gitpod/assets/3511344/274b1322-5c42-41f5-9ecc-583b450566eb">

### Steps to reproduce

1. Use https://github.com/dalisoft/dotfiles as dotfiles (used scripts from gitpod dotfiles template)
2. See error

### Workspace affected

dalisoft-commitlintrs-hn9vwietu8j

### Expected behavior

Dotfiles loading (my configs)

### Example repository

https://github.com/nanoexpress/ultimate-oss

### Anything else?

Maybe it's related to `fish` shell?

**Comment by axonasif** [comment]
It's probably happening because you change the default shell with `chsh` to fish.

**Comment by dalisoft** [comment]
@axonasif Yeah, maybe as it's mentioned in `Anything else` but it should work, isn't it?

**Comment by axonasif** [comment]
fish isn't a posix compliant shell, so this is expected. Do you need fish shell for every new terminal you create on Gitpod VSCode Web? In that case you may set it as the default shell profile on vscode, see https://code.visualstudio.com/docs/terminal/profiles


I have a personal project that also attempts to solve this, you might find it interesting: https://github.com/axonasif/dotsh#optimized-for-custom-shells

I'm marking this issue as "closed"
