### ISSUE TITLE
Implement Content Store

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2001]
Design Docs are something we're just getting started with.
Discussing them in the linear fashion afforded by GitHub is cumbersome.
To try something else, I've moved this design doc to Notion.

Everyone can read and comment.

[The document is here](https://www.notion.so/gitpod/Content-Store-87971bede96b4ac2bcd7279e1e2458c3).

**Comment by akosyakov** [comment]
We should avoid storing the complete user home. It can have configurations only relevant for the current workspace instance, for instance, Code will store workspace extensions and layouts next to sharable user data. It reminds me that each operating system has conventions about where to store portable data and caches (and it is not user home), something similar was discussed in Theia and Code: https://github.com/eclipse-theia/theia/issues/7218.

**Comment by csweichel** [comment]
We could make it so that the `home` blob always includes `$HOME/.config` and `$XDG_CONFIG_HOME`. If they're the same path, all the better.

**Comment by akosyakov** [comment]
I think I can force Gitpod Code server particularly respect `XDG_CONFIG_HOME`, so your proposal just to use `XDG_CONFIG_HOME` sounds good. 👍

**Comment by svenefftinge** [comment]
> 1. first call Delete on the content service,
> 2. then delete the entry in the database.

Should be the otherway around so we don't serve no existing entries during deletion?

**Comment by svenefftinge** [comment]
> LastAccess: time the blob was last read/accessed

Would be good to keep track of lastRead and lastWrite separately.

**Comment by csweichel** [comment]
> > 1. first call Delete on the content service,
> > 2. then delete the entry in the database.
> 
> Should be the otherway around so we don't serve no existing entries during deletion?

If we did it the other way 'round we'd run the risk of "forgetting" about content blobs (deleting them from the database) while their actual content is still around.
This way, if we're serve a "deleted" content blob, i.e. one that still exists in the database but whose content is gone, server can still answer correctly if it gets a `NOT_FOUND` from content service.

**Comment by csweichel** [comment]
> > LastAccess: time the blob was last read/accessed
> 
> Would be good to keep track of lastRead and lastWrite separately.

`LastAccess` very much has a `LastRead` semantic, except that it's initialised with the time that the blob was created (a detail missing in the doc above).

Would we also record `lastWrite` for statistics sake?

**Comment by svenefftinge** [comment]
> Would we also record lastWrite for statistics sake?

Yes, but (see my edited comment above) the content blobs should be immutable so only the DB entry needs to have update information.

**Comment by svenefftinge** [comment]
> If we did it the other way 'round we'd run the risk of "forgetting" about content blobs (deleting them from the database) while their actual content is still around.
> This way, if we're asked to serve a "deleted" content blob, i.e. one that still exists in the database but whose content is gone, server can still answer correctly because the gets a NOT_FOUND from content service.

We could have a two phase deletion, where we mark the entry deleted and then only after a successful deletion really wipe the entry. We do it like that for other data that is GCed.
