### ISSUE TITLE
phone verification problem without contact support

### ISSUE THREAD

**Issue by miamii11036** [gitpod-io/gitpod#20013]
### Bug description

When I attempted to create a own workspace to complete freecodecamp project and verified my phone number, I got the trouble like this image.
![螢幕擷取畫面 2024-07-09 204150](https://github.com/gitpod-io/gitpod/assets/175118438/cfd15695-da8c-4bef-a800-2d9432a37119)

I searched existing issues like this situation.    https://github.com/gitpod-io/gitpod/issues/19302
I saw there was a【contact support】 button, but I didn't have that

### Steps to reproduce

When i want to start own workspace

**Comment by axonasif** [comment]
Send a message at https://www.gitpod.io/contact/support
