### ISSUE TITLE
Gitpod OAuth errors

### ISSUE THREAD

**Issue by hm2075** [gitpod-io/gitpod#2002]
Hi

following on from this fix  
https://github.com/gitpod-io/gitpod/pull/1903

I managed to get this session fix.7  version running on kubernetes

on the plus side I can now authenticate with gitlab.com which wasnt working prior to the fix

unfortunately for the self hosted version of gitlab I have I am seeing

OAuth Error. Please try again.

I took some logs for the server and can see

for gitlab.com

gitpod reports 

"authProviderId":"GitLab","authUser":{"authId":"7179644","authName":"xxxx","avatarUrl":"xx","name":"xxx xxx","primaryEmail":"xxxx@live.co.uk"}}}

but for my self hosted version of gitlab I see

"authProviderId":"GitLabSelfHosted"}}

{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"server","version":"at-session-fix.7"},"stack_trace":"InternalOAuthError: Failed to obtain access token\n    at GenericOAuth2Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:379:17)\n  

any pointers?

**Comment by hm2075** [comment]
I have strong feeling this may be because  my self-hosted version of gitlab is using certificates that are generated in house,   

can't test non-ssl as there is no option to switch to http  in values.yaml auth provider in this version

**Comment by AlexTugarev** [comment]
Hi @hm2075!

The error you've pasted indicates, this is an issue in the OAuth2 Ping Pong

> InternalOAuthError: Failed to obtain access token\n at GenericOAuth2Strategy.OAuth2Strategy._createOAuthError 

Searching for that error message shows various possible reasons, e.g. proxy firewalls which restricts the communication between the Gitpod server pod and the GitLabSelfHosted. 

Can you please describe your infrastructure?

**Comment by hm2075** [comment]
Thanks @AlexTugarev 

Starting again

version : master.109
imagePrefix: eu.gcr.io/gitpod-core-dev/build/

On centos8,     installed kubernetes and got master 109 working,     local minio and mysql installation
all pods come up fine
gitpod is installed on premise behind corporate firewall
due to issues with split parts in domain name i registered  a seperate domain  xxxx.com  and pointed it to our IP address

then I configured both gitlab.com and our selfhosted gitlab      ,   self hosted gitlab is on premise as well behind corporate firewall


when logging on to gitlab.com through gitpod  I get

![image](https://user-images.githubusercontent.com/53794682/96281112-c6ed8080-0fd0-11eb-966e-ddfcbff08a48.png)


when logging on to our selfhosted gitlab I get

![image](https://user-images.githubusercontent.com/53794682/96281144-d7056000-0fd0-11eb-878d-ee0d147994b3.png)

**Comment by hm2075** [comment]
I wonder if its something to do with this

https://github.com/binario200/passport-social-auth


"The thing is that oauth2.js does not take in consideration the proxy environment variables when it performed the requests. Blocking the web app to get authenticated (receive the access token and the github user info)"

**Comment by hm2075** [comment]
@AlexTugarev 

it wasnt proxy,     i had suspected corporate signed certificates so applied  digicert ssl certificates to both gitpod and gitlab and it worked straight away

you can close this issue after you have reviewed

**Comment by AlexTugarev** [comment]
@hm2075 thanks for the notice about your solution 🙏 

Indeed the session-based mechanics during the login may break when the browser agent won't accept/send cookies on redirects due to issues with the HTTPS  connection.
