### ISSUE TITLE
Bug While Editing A File

### ISSUE THREAD

**Issue by ItzNesbroDev** [gitpod-io/gitpod#20036]
### Bug description

So whenever i click on a variable or any text and click elsewhere the first clicked text popup there and whenever i try to type anything it goes like `aaeasease` like random letters

### Steps to reproduce

I don't know

**Comment by ItzNesbroDev** [comment]
![Uploading Screenshot_2024-07-13-19-57-29-587_com.brave.browser.jpg…]()
example

**Comment by axonasif** [comment]
I suggest using Kiwi Browser.

**Comment by ItzNesbroDev** [comment]
> I suggest using Kiwi Browser. And this is specific to https://github.com/microsoft/vscode, Gitpod only uses a fork.

I got this issue first on kiwi so I tried on brave

**Comment by ItzNesbroDev** [comment]
@axonasif help bro

**Comment by axonasif** [comment]
Sorry, this is related with vscode itself. Please report on https://github.com/microsoft/vscode

Some workarounds for this could be this:
- Use a chrooted/prooted Linux Distro on your Android device and run a VNC Desktop server, in it you can run chrome or any other desktop browser, which will not have the same problem.
- Use [Gitpod SSH](https://www.gitpod.io/docs/references/ides-and-editors/command-line) + Termux app and edit code with a CLI editor such as neovim or Emacs.
- Use https://www.gitpod.io/docs/references/ides-and-editors/browser-terminal with CLI editor.
