### ISSUE TITLE
opening the devcontainer takes for ever

### ISSUE THREAD

**Issue by bitflame** [gitpod-io/gitpod#20079]
### Bug description

I am using Fedora and Chrome and I am able to open vscode but when I say yes to the question "do you want to open the devcontainer" it just hangs for ever

### Steps to reproduce

Use Fedora 40 to open a GitHub project with vscode via GitPot

### Expected behavior

It should run faster

### Example repository

https://github.com/bitflame/AWS-Examples

### Anything else?

Do I have to open the dev container? I do not know!

**Comment by axonasif** [comment]
Hi, I think the devcontainers vscode extension is not supported on Gitpod workspaces at the moment.

**Comment by bitflame** [comment]
I thought I need it in order to proceed with the project. Could you maybe tell me what it is or send some links my way that explain what it is I am trying to download?

**Comment by axonasif** [comment]
Can you elaborate on what you're trying to do?

**Comment by bitflame** [comment]
Sure. I use gitpod as development environment for AWS projects.

Regards-
Shahin Ansari
tel. 703-389-5679

Ask me about the benefits of Proton mail email account. I love it!
CONFIDENTIALITY NOTICE:
The contents of this email message and any attachments are intended solely for the addressee(s)
and may contain confidential and/or privileged information and may be legally protected from
disclosure. If you are not the intended recipient of this message or their agent, or if this message
has been addressed to you in error, please immediately alert the sender by reply email and then
delete this message and any attachments. If you are not the intended recipient, you are hereby
notified that any use, dissemination, copying, or storage of this message or its attachments is
strictly prohibited.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by axonasif** [comment]
@bitflame you will need to replicate what the decontainer.json is installing/configuring through `.gitpod.yml`, it's pretty easy. We might have devcontainer support in the future but for now this is the only way.

See https://www.gitpod.io/docs/introduction/gitpod-tutorial/2-configure-your-gitpod-yml#step-2-configure-the-gitpodyml

**Comment by bitflame** [comment]
Thanks.

Regards-
Shahin Ansari
tel. 703-389-5679

Ask me about the benefits of Proton mail email account. I love it!
CONFIDENTIALITY NOTICE:
The contents of this email message and any attachments are intended solely for the addressee(s)
and may contain confidential and/or privileged information and may be legally protected from
disclosure. If you are not the intended recipient of this message or their agent, or if this message
has been addressed to you in error, please immediately alert the sender by reply email and then
delete this message and any attachments. If you are not the intended recipient, you are hereby
notified that any use, dissemination, copying, or storage of this message or its attachments is
strictly prohibited.

Sent with [Proton Mail](https://proton.me/) secure email.
