### ISSUE TITLE
Extensions do not install to workspaces when using VS Code Desktop 1.92

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#20096]
### Bug description

Remote extensions do not install, I only see the Gitpod Remote extension

Related upstream issue: https://github.com/microsoft/vscode/issues/225139

### Steps to reproduce

Start a workspace

### Expected behavior

My extensions should load

### Example repository

Any

### Anything else?

There are a couple workarounds.

You can continue using VS Code Desktop 1.92 and install extensions manually.

or

You can downgrade VS Code Desktop on your local machine to 1.91 and disable the auto upgrade feature.

**Comment by oconnorjoseph** [comment]
Encountering the same issue

**Comment by shaffy9633** [comment]
i thought i was the only one :(

**Comment by builtbyjavi** [comment]
+1

**Comment by kylos101** [comment]
Hi @oconnorjoseph , @shaffy9633 , and @builtbyjavi , we shipped a new version of the Gitpod Remote extension, v0.0.52. Please upgrade to it if you haven't already, it contains a workaround (so we are not dependent on an upstream fix).

Ref:
```
Name: Gitpod Remote
Id: gitpod.gitpod-remote-ssh
Description: Gitpod Remote Support
Version: 0.0.52
Publisher: Gitpod
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=gitpod.gitpod-remote-ssh
```

I am going to close this issue. If you continue to have trouble, let us know? And, have a nice weekend!
