### ISSUE TITLE
Fast updates of shell content cause heavy load on client

### ISSUE THREAD

**Issue by sailingKieler** [gitpod-io/gitpod#201]
When opening https://github.com/ScheidtBachmann/statemachine/ and running `mvn package`, I noticed loads of up to 400% cpu core usage on my macbook, see

<img width="733" alt="gitpodbrowserload" src="https://user-images.githubusercontent.com/8513883/50166374-3b790a80-02e7-11e9-94f4-89cc6f289e39.png">

**Comment by svenefftinge** [comment]
Would be interesting to see if that is better with the latest version of xtermjs. @AlexTugarev WDYT?

**Comment by AlexTugarev** [comment]
I don't see great improvements on my machine.

I did a quick test with Theia in a workspace to test the effect on the cpu. The newer version of xterm feels much smoother, but the cpu usage is not reflecting that in any way. Also, it might depend on the update frequency of those `Progress ...` lines, which again depends on the network conditions for the downloads in that case. We might need a proper measurement with a synthetic test in form of a script which updates lines quite fast.

In general, I think this impacts the whole FE, as it adds a lot of pressure on the web socket connection. Ideally, we could detect the terminal sequences meant to update the last line, and reduce the frequency. 

# xtermjs@3.9.1
![2018-12-19 08 53 22](https://user-images.githubusercontent.com/914497/50206723-97d23d80-036c-11e9-90b4-51c61cac46f6.gif)

# previous version of xtermjs
![2018-12-19 08 57 45](https://user-images.githubusercontent.com/914497/50206730-9d2f8800-036c-11e9-8f0b-94b33a29549f.gif)
