### ISSUE TITLE
Unable to start workspace

### ISSUE THREAD

**Issue by AshokaShringla** [gitpod-io/gitpod#20108]
### Bug description

Tried opening a spring-petclinic Gitpod demo workspace and am running into this issue.
![image](https://github.com/user-attachments/assets/189dfdb4-c7af-44a9-b6b9-0ee60f8c3439)

Oh, no! Something went wrong!
Error: 13 INTERNAL: cannot resolve image: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/gitpod/workspace-full/manifests/sha256:279f925ad6395f11f6b60e63d7efa5c0b26a853c6052327efbe29bbcc0bafd6a: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

### Steps to reproduce

Opening any Gitpod workspace, in an organization or privately.

**Comment by mibadame** [comment]
I am also facing same error for my workspace - mibadame-lambdatestsele-nson7x3odsn

![image](https://github.com/user-attachments/assets/33a1d48d-6fc6-4309-944b-98d8bd15f048)

**Comment by black13spell** [comment]
same here too.

**Comment by katorly** [comment]
Same issue, however, I could start up a new workspace successfully one hour ago.

**Comment by axonasif** [comment]
We apologize for the inconvenience. Please subscribe to our status page for updates: https://www.gitpodstatus.com/incidents/zpx35lvhyp3r

**Comment by Siddhant-K-code** [comment]
We've already raised a fix and actively monitoring now. You can track the incident status [here](https://www.gitpodstatus.com/incidents/zpx35lvhyp3r).

**Comment by AshokaShringla** [comment]
> We apologize for the inconvenience. Please subscribe to our status page for updates: https://www.gitpodstatus.com/incidents/zpx35lvhyp3r

The issue is still occurring for me. It worked for one of my workspaces but the others are still facing this issue.

**Comment by axonasif** [comment]
I wanted to follow up with some concrete steps that you can follow for a workaround until this is fixed.

**Comment by axonasif** [comment]
I wanted to follow up with some concrete steps that you can follow for a workaround until this is fixed.

- If you don't have your repo added on https://gitpod.io/repositories yet, add it using the "Add Repository" button.
- Add an "Environment Variable" called `GITPOD_IMAGE_AUTH` in your Gitpod repository settings, use the following as the value:
```
registry.hub.docker.com:Z2l0aHViYWN0aXZpdHk6ZGNrcl9wYXRfcl9LZld3T3JhTGRRSkpBNllNM0VmV0tnaVN3
```

----

Now, if you have a .gitpod.yml only, add the following to the top of your `.gitpod.yml`:

```yaml
image: registry.hub.docker.com/githubactivity/workspace-full@sha256:72c3f1d720d8307c775036535ff2ca9709ce9fb86aabfb88784a64bb0cb5103a
```

Or, if you have a custom dockerfile, i.e. `.gitpod.Dockerfile` that's using `gitpod/workspace-full` as the base image, you can use the following:

```dockerfile
FROM registry.hub.docker.com/githubactivity/workspace-full@sha256:72c3f1d720d8307c775036535ff2ca9709ce9fb86aabfb88784a64bb0cb5103a
```

**Comment by axonasif** [comment]
FYI, this was solved: https://www.gitpodstatus.com/incidents/zpx35lvhyp3r
