### ISSUE TITLE
VS Code Pull Requests extension failed on gitpod when I tried to create a pull request from the source control Tab on VS code

### ISSUE THREAD

**Issue by sirine707** [gitpod-io/gitpod#20102]
### Bug description

When I click on creating pull request from 
I have "The extension 'GitHub Pull Requests' wants to sign in using GitHub" I click Allow 
Then This appear " An operation requires additional permissions: read:user. Please grant permissions and try again." I click on Open Access Control  
and eventually  the lower right tab appear saying " Error signing in to GitHub"  

### Steps to reproduce

- use gitpod extension on Gtihub to clone my fork and open VS code on browser
- create a new branch
- push to update the fork
- create pull request from VS code source control Tab  

### Anything else?

![image](https://github.com/user-attachments/assets/0cf91eb6-64d2-422b-944a-99ccfcc31ffe)
![image](https://github.com/user-attachments/assets/054c1210-2199-41d2-aa74-7b89ea5d2b55)

**Comment by sirine707** [comment]
I appreciate your guidance

**Comment by axonasif** [comment]
Hi @sirine707, do you have all the permissions checked at for `GitHub` at https://gitpod.io/user/integrations ? You'll need to use the "Edit permissions" menu option.

**Comment by sirine707** [comment]
Hi @axonasif , I went to my target repo-> settings  ; as shown its authorized , is this what you are pointing to?


![image](https://github.com/user-attachments/assets/5d8b4673-205e-413b-9dc4-45fe36688dac)

**Comment by axonasif** [comment]
@sirine707 Please follow the steps below:
- Go to https://gitpod.io/user/integrations
- Click on the hamburger menu icon next to `GitHub` and select "Edit Permissions" option
![2024-08-12 at 17 48 54@2x](https://github.com/user-attachments/assets/458615bc-aaf3-4885-b7bd-225780bcc021)
- Ensure it looks like this, with "read:user" 
![2024-08-12 at 17 56 57@2x](https://github.com/user-attachments/assets/770b044f-81ce-43ce-8f3b-0b3f2164519b)



---

After you've followed the steps above, please **create a new workspace** and try again.
