### ISSUE TITLE
Issues with the Build a Mario Database

### ISSUE THREAD

**Issue by Mookiematic** [gitpod-io/gitpod#20118]
### Bug description

<img width="753" alt="Screenshot 2024-08-14 at 9 01 46 PM" src="https://github.com/user-attachments/assets/77e0779b-cfaa-4db4-be2b-a699e508863c">

I keep getting these popups all the time and halfway through whatever I am doing it just freezes and I have to restart the task. I am working on the Build a Mario Database from freeCodeCamp

### Steps to reproduce

Nothing really it just stops working randomly. It won't time out or kick me out but no matter what I type it will not react to anything.

### Workspace affected

https://freecodecam-learnrelati-gz6ek3qdij2.ws-us115.gitpod.io/

### Expected behavior

I should see a result even if it is to tell me what I typed was wrong

**Comment by axonasif** [comment]
Can you please elaborate? If you could record a video walking through the issue, that would be helpful
