### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Kick933** [gitpod-io/gitpod#20148]
### Bug description

When i create or start any previous gitpod, it get stuck in infiniter loop of starting and reloading the page. I assume it happened due to a deployment. I am able to recreate it every time. It gives a network error message in red, and console shows unhandled promise error.

### Steps to reproduce

Create a gitpod and start it.

### Expected behavior

The gitpod should start and vscode should appear on the screen

**Comment by axonasif** [comment]
Can you try this again and copy paste your console logs here?
