### ISSUE TITLE
[Feature] UserDirs

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2016]
## Context
With gitpod users use fresh containers all the time. In order to leverage caches and user specific configuration used by many tools, we need a way to retain user-specific state between multiple workspace sessions.

One obvious use case is keeping user settings from vscode across sessions. While we could build a special solution as we did with our Theia IDE, that would make sure the tool is not writing this state to disk but to another file system, we would like to build a more generic solution so other similar problems can be solved.

##Goals and non goals

We want to allow a simple but flexible enough way to keep user-specific file contents between sessions.

## Design

Allow users to configure "user dirs" as part of their settings. On workspace start the data should be read from the content store (if existing) and on workspace stop the data shall be stored again (last write wins).

### On Start
Supervisor shall process the user's UserDirs after `init` and before any tasks are executed. For each dir it checks if an associated blob exists and if so restores it. It shall not create an empty dir if or do any other sideffects otherwise.

### On Stop
Before the contents is backed-up the userDirs shall be stored using the content store. If there is no file for a certain userDir, nothing is done. Otherwise the data is stored and the files are deleted, so they don't end up in workspace contents.

### On Snapshot
We don't want to share UserDir contents with others. So a snapshot needs to be freed from the userDir contents.

### User Settings
Users can configure any number of userdirs in the settings. They are processed in the order they are listed on start and in reverse order on stop.

**Comment by Michaelhobo** [comment]
What about mounting a shared volume into the workspace? I think having a live-updated homedir would be better than copy/restore of a directory, for a few reasons:

- some things like caches can be shared across workspaces, live
- Changes propagate across all your running workspaces, like a regular user's homedir would
- You don't need to handle file conflicts between workspaces. The responsibility is pushed to the volume's filesystem, and most standard tools already handle this - e.g. many tools use lock files to fix contention issues.

e.g. a quick search makes it sound like netapp could work:
https://docs.netapp.com/us-en/cloud_volumes/aws/task_mounting_cloud_volumes_for_aws.html

The big tradeoff is you need to deal with network performance issues, but if you use some volume that's in-network to your cloud provider, this might be OK.

**Comment by jgao1025** [comment]
I am also searching for the solution. So far from what I found, using `Environment Variables ` is the workaround. It says it can store sensitive data. I think it could be better to use seperate key for it and also use base64 encrypt the key before using.
