### ISSUE TITLE
Unable to push repo to github

### ISSUE THREAD

**Issue by its7rishi** [gitpod-io/gitpod#20174]
### Bug description

When I try to push a repo into GitHub, I get an error saying "<repoisitory_name> is  not acessible with this token. Set access permissions". I checked the access permission and all the permissions have been given.

### Steps to reproduce

1. Commit changes
2.  Sync Changes

### Workspace affected

https://freecodecam-learnworldc-6nm2drdtr5r.ws-us116.gitpod.io/

### Expected behavior

The repo should sync with github and all the files should appear in the GitHub repo

### Example repository

https://gitpod.io#snapshot/179e53a3-b6ab-4ce3-9fda-59aa953441fe

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by axonasif** [comment]
It could be that you're trying to push to the original repo here: https://github.com/freeCodeCamp/learn-world-cup-database

What do you see when you run `git remote -v` on your workspace terminal?

**Comment by axonasif** [comment]
Marking this issue as 'closed', as this is more like a support request than a bug.
Please use https://www.gitpod.io/contact/support in the future.
