### ISSUE TITLE
Jupyter Notebooks stopped working

### ISSUE THREAD

**Issue by rdmueller** [gitpod-io/gitpod#20185]
### Bug description

https://github.com/gitpod-samples/template-jupyter-notebook/issues/2

### Steps to reproduce

https://gitpod.io#https://github.com/gitpod-samples/template-jupyter-notebook/issues/2

ctrl+shift+p

"select kernel"

python environments

now, all known python interpreter should be listed, but the list is empty. Try to execute python in the terminal - it works

### Expected behavior

python environment should be detectable by VS Code in order to start jupyter notebooks

### Example repository

see above

### Anything else?

thanx for your great work!

**Comment by rdmueller** [comment]
Don't know what has been changed, but it works again.

**Comment by axonasif** [comment]
Cool
