### ISSUE TITLE
Extension option to color VSCode windows different colors

### ISSUE THREAD

**Issue by nhorton** [gitpod-io/gitpod#20184]
## Is your feature request related to a problem? Please describe
I sometimes want to work on multiple branches at once, and have tried doing it with Gitpod. Unfortunately, I often get confused regarding which window is which branch. 

I know I would use multiple workspaces simultaneously (and therefore you would make 2x as much) if I could more easily tell them apart.

Adding an option in your VScode extension to set some of the window colors using something like a hash of the branch name would make this easy.

**Comment by axonasif** [comment]
Thanks for the feedback.
