### ISSUE TITLE
iframe to localhost in gitpod

### ISSUE THREAD

**Issue by escapeoneone** [gitpod-io/gitpod#2018]
### Describe the bug
If the extension opens the server then when you open it in the Gitpod tab it will be Iframe on localhost:_{port}_
Using TabNine as an example
### Steps to reproduce
> Install TabNine
1. Open TabNine settings
![Screenshot from 2020-10-18 17-55-55](https://user-images.githubusercontent.com/54133395/96371626-339c8280-116b-11eb-9a08-19c59f008bf1.png)

2. Opened Iframe to localhost with error and opened port to 5555
![Screenshot from 2020-10-18 17-54-32](https://user-images.githubusercontent.com/54133395/96371605-1798e100-116b-11eb-856a-4a5f8dc5524a.png)
![Screenshot from 2020-10-18 17-55-00](https://user-images.githubusercontent.com/54133395/96371645-4dd66080-116b-11eb-880d-d4bd0e212ee9.png)

### Expected behavior
1. Open TabNine settings
![Screenshot from 2020-10-18 17-55-55](https://user-images.githubusercontent.com/54133395/96371626-339c8280-116b-11eb-9a08-19c59f008bf1.png)

2. Opened Iframe to https://5555-{workspace-id}.gitpod.io and opened port to 5555

### Additional information
The same error exists in PlatformIO

**Comment by akosyakov** [comment]
Hello! Could you clarify which extensions? Extensions should use `vscode.webview.asWebviewUri` to create proper external URIs instead of hardcoding localhost: https://code.visualstudio.com/api/advanced-topics/remote-extensions#always-use-aswebviewuri

**Comment by boomik305** [comment]
> Hello! Could you clarify which extensions? Extensions should use `vscode.webview.asWebviewUri` to create proper external URIs instead of hardcoding localhost: https://code.visualstudio.com/api/advanced-topics/remote-extensions#always-use-aswebviewuri

- PlatformIO 

- TabNine

**Comment by akosyakov** [comment]
I could not find a usage of this API in source code of `TabNine` extensions. Please open a feature request for them to support running in the remote context according to this docs: https://code.visualstudio.com/api/advanced-topics/remote-extensions
