### ISSUE TITLE
The "More Information" notification is not displayed in the Theia after clicking  the "More Information" button

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#202]
**Description:**

The "More Information" notification is not displayed in the Theia after clicking  the "More Information" button

**Steps To Reproduce:**

1. Login to the site
2. Start the workspace (classpath is incomplete)
3. Click the "More Information" button
4. Pay attention to the workspace

**Actual result:**

The "More Information" notification is not displayed in the Theia after clicking the "More Information" button
![mswindow](https://user-images.githubusercontent.com/41964662/50218072-5bfe9e80-0393-11e9-9be9-34c3d75bccea.png)

**Expected result:**

The "More Information" notification is displayed in the Theia after clicking the "More Information" button

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98

**Comment by AlexTugarev** [comment]
This was an issue with the Java extension; fixed there and about to get obsolete with the switch to the vscode extension.
