### ISSUE TITLE
Cannot clone VLC repository

### ISSUE THREAD

**Issue by TheChatty** [gitpod-io/gitpod#20249]
### Bug description

https://gitpod.io/new/#https://code.videolan.org/videolan/vlc.git results in
`Error: Couldn't parse context 'https://code.videolan.org/videolan/vlc.git'`
whereas issueing
`git clone https://code.videolan.org/videolan/vlc.git`
works.

### Steps to reproduce

Follow the above URL.

### Expected behavior

Same behavior as when working with git locally.

**Comment by axonasif** [comment]
This is expected. We do not support SCMs other than GitHub/GitLab/Bitbucket for workspace creation.

You can read more on this here: https://www.gitpod.io/docs/configure/authentication

**Comment by JensKoehlerMW** [comment]
Thanks for the clarification. I was under the impression that any git source would work. So it's necessary to create a (supported SCM) repo clone first.

**Comment by axonasif** [comment]
You might be able to create a mirror on GitHub and such.

**Comment by TheChatty** [comment]
Thanks for the clarification. The workaround is of course possible. Would I be able to start an empty workspace so I can issue the `git clone` command myself?
