### ISSUE TITLE
Github Auth for the new github flex fails on sign-in.

### ISSUE THREAD

**Issue by FunnyCorgi** [gitpod-io/gitpod#20258]
### Bug description

Whenever signing into the new gitpod flex, it fails with "failed to sign in" and on reloads fails with "failed to exchange OAuth2 token"

### Steps to reproduce

Attempt signing in with github to app.gitpod.io

### Workspace affected

none

**Comment by axonasif** [comment]
Hi @FunnyCorgi, we've deployed a fix. Can you please try again?

**Comment by FunnyCorgi** [comment]
Ok sorry, haven't been checking, will do

**Comment by FunnyCorgi** [comment]
@axonasif This fix has solved the issue, and I was able to sign in.
