### ISSUE TITLE
feature request: base image with KasmVNC rather than NoVNC

### ISSUE THREAD

**Issue by christopher-aldred** [gitpod-io/gitpod#20250]
## Describe the behaviour you'd like

The NoVNC experience when using the VNC Gitpod image is not great, can an image be created which harnesses KasmVNC?
The experience compared to NoVNC is much better. It supports better image quality, better screen scaling, audio and copy/paste.

[gitpod/workspace-full-vnc](https://hub.docker.com/r/gitpod/workspace-full-vnc)

[KasmVNC](https://kasmweb.com/kasmvnc/docs/master/index.html)
[Linux Webtop](https://docs.linuxserver.io/images/docker-webtop/)

## Describe alternatives you've considered

Using a bespoke Dockerfile.

**Comment by axonasif** [comment]
We have no plans at the moment and we may deprecate the workspace images in the near future, feel free to create and use it yourself:
https://www.gitpod.io/docs/configure/workspaces/workspace-image#using-a-custom-dockerfile
