### ISSUE TITLE
Invalid URL when the user is logged out without option to log in

### ISSUE THREAD

**Issue by fjgarlin** [gitpod-io/gitpod#20263]
### Bug description

When visiting certain URLs, like this one https://gitpod.io/#VARIABLE=value/https://git.drupalcode.org/project/drupalpod
* If you happen to be logged in, everything works as expected
* But if you are not logged in, you receive `Failed to construct 'URL': Invalid URL` and have no option to log in
![Screenshot 2024-10-02 at 16 33 19](https://github.com/user-attachments/assets/3291e024-dbdb-4c7d-a8a4-e5e89bd1b40b)

It should be an option to log in and not just the `Reload` button, as the URL seems to be valid.

Before, there was a prompt to log in, this only started happening a few days ago.

### Steps to reproduce

1. Log out of gitpod.io
2. Visit https://gitpod.io/#VARIABLE=value/https://git.drupalcode.org/project/drupalpod
3. See the error

1. Log in to gitpod.io
2. Visit https://gitpod.io/#VARIABLE=value/https://git.drupalcode.org/project/drupalpod
3. See that it works

### Expected behavior

If the URL is valid, then an option to log in should be presented.

**Comment by axonasif** [comment]
Hi @shaal 

I'm posting this internally to get the attention of our engineering.

**Comment by filiptronicek** [comment]
Sorry for the troubles folks, I'm currently looking into this!

**Comment by filiptronicek** [comment]
@fjgarlin thanks a bunch for the very nice report! The bug is now fixed and awaiting deployment tomorrow European morning.

**Comment by filiptronicek** [comment]
If this continues being a problem before tomorrow morning, please try either:
- stripping the `VARIABLE=value/` prefix from the URL you're opening
- or, logging in before opening the context

**Comment by fjgarlin** [comment]
Thanks for fixing up so quickly 🙂

**Comment by shaal** [comment]
@axonasif ++ @filiptronicek ++
Thank you for fixing this so fast!
