### ISSUE TITLE
Local Dev over Skaffold

### ISSUE THREAD

**Issue by sr229** [gitpod-io/gitpod#2032]
I believe it would be nice if we can get this working with local dev over with Skaffold to promote a easier development pipeline for those who want to help with development and want to test the changes in their development Kubernetes cluster.

**Comment by wulfthimm** [comment]
https://skaffold.dev/

**Comment by sr229** [comment]
Yep! Skaffold is a good tool for testing a Kubernetes app locally like for example a Docker Desktop Kube cluster.
