### ISSUE TITLE
Self hosted can'd be install via docker 

### ISSUE THREAD

**Issue by ranglang** [gitpod-io/gitpod#2034]
### Describe the bug

If you don't have your own (sub-)domain available, leave this field blank and we'll get a temporary one for you.
That domain will work for at least 30 days, but is not meant for productive installations.
You can, at any time move to your own domain by editing aws/main.auto.tfvars and re-running this installer.
domain ? gitpost.wintercoming.xyz
   running command: terraform [init]
Initializing modules...
- gitpod in modules/gitpod
Downloading terraform-aws-modules/eks/aws 13.0.0 for kubernetes...
- kubernetes in .terraform/modules/kubernetes
- kubernetes.node_groups in .terraform/modules/kubernetes/modules/node_groups
- registry in modules/registry
- storage in modules/storage
Downloading terraform-aws-modules/vpc/aws 2.44.0 for vpc...
- vpc in .terraform/modules/vpc

Error: Unsupported Terraform Core version

  on .terraform/modules/kubernetes/versions.tf line 2, in terraform:
   2:   required_version = ">= 0.12.9, != 0.13.0"

Module module.kubernetes (from terraform-aws-modules/eks/aws) does not support
Terraform version 0.13.0. To proceed, either choose another supported
Terraform version or update this version constraint. Version constraints are
normally set for good reason, so updating the constraint may lead to other
errors or unexpected behavior.

!! 

### Steps to reproduce

```
docker run --rm -it \
    -e AWS_ACCESS_KEY_ID \
    -e AWS_SECRET_ACCESS_KEY \
    -v "$PWD/awsinstall":"/workspace" \
    eu.gcr.io/gitpod-io/self-hosted/installer:latest aws
```

**Comment by corneliusludmann** [comment]
See
- https://community.gitpod.io/t/error-unsupported-terraform-core-version-when-using-the-aws-installer-image/2018/2?u=corneliusludmann
- https://community.gitpod.io/t/error-for-one-liner-installs-on-gcp-and-aws/1992?u=corneliusludmann

Does this solve the problem?

**Comment by ranglang** [comment]
fixed.

PWD/awsinstall , find .terraform dir and then remove it, change version in main.tf
