### ISSUE TITLE
Lying about the free tier

### ISSUE THREAD

**Issue by RayS-GIT** [gitpod-io/gitpod#20366]
### Bug description

Pretty self explanatory. I have never had any free access since i registered on your site so this statement cant be true..
"Tiers
Free Tier
All users receive a free usage allowance of up to 500 credits per month to try Gitpod in their first created organization."

### Steps to reproduce

Open a new account,
new organization,
try acces a space,
see the error that you have reached your limit (which is very easy to reach at 0 minutes)

### Example repository

https://gitpod.io/?autostart=true#https://github.com/freeCodeCamp/boilerplate-mean-variance-standard-deviation-calculator/

**Comment by loujaybee** [comment]
Hey @RayS-GIT there definitely should be free credits applied to new accounts, if that is not happening there is likely some cause that we should look into. Can you please submit a support ticket so we can help you out. 

https://www.gitpod.io/contact/support

I will close the issue as it shouldn't require other community input or feedback.
