### ISSUE TITLE
When integrated with GitLab, many places still say 'GitHub'

### ISSUE THREAD

**Issue by olearycrew** [gitpod-io/gitpod#2037]
### Describe the bug
There are a number of places that say "GitHub" (assumably hardcoded) even when integrated with a different SCM (e.g. GitLab).  For example:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/6044920/96746013-c1a78180-1394-11eb-8945-681bce5e24f7.png">

### Example repository
https://gitlab.com/brendan-demo/waypoint

**Comment by jgallucci32** [comment]
Please provide more details. I am currently seeing the custom FQDN of our on-prem Gitlab server with a v0.5.0 deployment on vanilla Kubernetes.
![image](https://user-images.githubusercontent.com/9018897/96753364-a0d73000-1384-11eb-8f1e-1eb1f31ba31b.png)

**Comment by corneliusludmann** [comment]
On gitpod.io it is still as @olearycrew said. It's already fixed for self-hosted and in this repo but not deployed to prod yet.

**Comment by jankeromnes** [comment]
The fix is now live in prod.

**Comment by gtsiolis** [comment]
This has been deployed to production, let's close this. 📕 

Thanks @jankeromnes @corneliusludmann @olearycrew!
