### ISSUE TITLE
[supervisor] I see the 'this task ran as part of a prebuild" message in prebuilds

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2039]
https://gitpod-staging.com/#prebuild/https://github.com/nisarhassan12/svgr

<img width="801" alt="Screenshot 2020-10-22 at 06 24 05" src="https://user-images.githubusercontent.com/372735/96824545-58288100-142f-11eb-82b5-2a0b1bcc9932.png">

**Comment by svenefftinge** [comment]
Not sure if this is new, though. Just didn't see it before but could be because it is the last thing before a redirect so maybe I never noticed.

**Comment by akosyakov** [comment]
It is new, my bad, will do a PR promptly. Good catch!
