### ISSUE TITLE
The “Sorry, this should not have happened!” page is displayed after clicking the "Share Running Workspace" link by a non-logged in

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#204]
**Description:**

The “Sorry, this should not have happened!” page is displayed after clicking the "Share Running Workspace" link by a non-logged in

**Preconditions:**  

Any workspace was shared previoulsy, a link was provided (e.g. https://f65e20c4-e381-4be8-87f0-b0b31e285bcb.ws-eu.gitpod.io/#/workspace/GeometricShapes)
The user by a non-logged in

**Steps To Reproduce:**

1. Follow this "Share Running Workspace" link
2. Pay attention to the "Sorry, this should not have happened!” page

**Actual result:**

The “Sorry, this should not have happened!” page is displayed after clicking the "Share Running Workspace" link by a non-logged in
Video: https://www.dropbox.com/s/083953zlanutvb4/Share.mp4?dl=0
![workspace](https://user-images.githubusercontent.com/41964662/50229499-1fdb3600-03b3-11e9-9ccb-79a9c0423261.png)

**Expected result:**

The "Login" page opened after clicking  the "Share Running Workspace" link by a non-logged in

Additional Information:
Win 10 Google Chrome 71.0.3578.98

**Comment by sr229** [comment]
Duplicate of #95

**Comment by krainboltgreene** [comment]
Seems to still happen and even if I'm logged in
