### ISSUE TITLE
[staging]: activating 'Material Theme' extension fails

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2040]
### Describe the bug

On Gitpod staging saw this prompt on the workspace startup

![image](https://user-images.githubusercontent.com/46004116/96826532-fa0a9680-144c-11eb-8a97-7219c1fc4567.png)

### Steps to reproduce

Open a new workspace on `gitpod-staging`. I have opened 2 workspaces so far both of them showed the above prompt.

**Comment by akosyakov** [comment]
Which repo did you open?

**Comment by akosyakov** [comment]
Moved to open vsx repo: https://github.com/open-vsx/publish-extensions/issues/196 not gitpod or theia issue

**Comment by nisarhassan12** [comment]
Sorry for the late reply. I think all the repositories which I open via staging. I'm not sure How the extension was installed but it is installed under the user tab in the extensions pane.
![image](https://user-images.githubusercontent.com/46004116/96863036-b5e4b980-147f-11eb-8b40-73b5bb1c0a22.png)

**Comment by akosyakov** [comment]
@nisarhassan12 ah, it is installed for your user
