### ISSUE TITLE
[staging]: open preview / open in browser does not seem to work i.e you can't view what's being served on port 8000

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2045]
### Describe the bug

Open Preview / Open in Browser does not seem to work i.e you can't view what's being served on port 8000 staging also trying the following command:

```
gp preview $(gp url 8000)
```

Does not seem to work as expected either.

### Steps to reproduce

Open any workspace on staging ie. maybe try https://gitpod-staging.com#https://github.com/gitpod-io/contribute.dev and you won't be able to open the preview or open the browser for what is being served by port 8000.

**Comment by nisarhassan12** [comment]
Tested another project and tried port 8080 which seem to work.

**Comment by akosyakov** [comment]
@csweichel it would be better if you have a look, somehow ws-proxy does not know about internal port.

**Comment by akosyakov** [comment]
I will tackle it in https://github.com/gitpod-io/gitpod/pull/1909

**Comment by akosyakov** [comment]
@nisarhassan12 Could you try to reproduce it in #1909?

**Comment by nisarhassan12** [comment]
@akosyakov Thanks. I have tried it against #1909 and it seems to work i.e I'm able to preview what is on port 8000 but live-reload/HMR does not seem to be working.

**Comment by akosyakov** [comment]
@nisarhassan12 I am not sure that HMR related to ports handling or it is ws proxy issue. Could you file a separate issue please and mark it with staging label?

**Comment by akosyakov** [comment]
nvm, HMR was addressed in #1909 as well, see https://github.com/gitpod-io/gitpod/pull/1909/commits/bad296b6585507907964d693ae5220baa99b13d6

**Comment by akosyakov** [comment]
Everything was resolved in https://github.com/gitpod-io/gitpod/pull/1909
