### ISSUE TITLE
[staging]: diff view does not work properly 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2061]
### Describe the bug

On staging the diff view does not work properly i.e there is no colour highlighting for the additions and the subtractions:

![image](https://user-images.githubusercontent.com/46004116/97145693-71f7fa00-1788-11eb-9797-93e01208dedd.png)

![image](https://user-images.githubusercontent.com/46004116/97145703-76bcae00-1788-11eb-80bc-8b22ec544062.png)

### Steps to reproduce

- Open a workspace on gitpod staging i.e https://gitpod-staging.com/#https://github.com/vuejs/vuex.
- Try changing some files.
- Open the Diff View from Source control for any chnaged file.

**Comment by akosyakov** [comment]
```
Unsafe attempt to load URL http://blobserve.ws-dev.cw-supervisor-ports.staging.gitpod-dev.com/eu.gcr.io/gitpod-core-dev/build/theia-ide:cw-supervisor-ports.138/__files__/vs/base/worker/workerMain.js#editorWorkerService from frame with URL http://dded06c6-00e8-45ab-be74-7633cb7f7c98.ws-dev.cw-supervisor-ports.staging.gitpod-dev.com/#/workspace/vscode. Domains, protocols and ports must match.
```

The editor web worker cannot be launched.

**Comment by akosyakov** [comment]
There is no reliable way in the proxy to tell what is a request mode. There is `sec-fetct-mode` but it seems to work only in secure context and is not well supported by all browsers yet. The only way to fix is to exclude static files which should be served from exactly same origin (like workers) from blobserver layer of Theia.
