### ISSUE TITLE
[staging]: Open Ports tab does not renders what ports are running.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2062]
### Describe the bug

[staging]: Open Ports tab does not renders what ports are running.

![image](https://user-images.githubusercontent.com/46004116/97149167-29433f80-178e-11eb-9be9-005ede5bcecf.png)

### Steps to reproduce

I think I only saw this in one workspace and I'm not able to re-produce this in any other workspace so far.

**Comment by corneliusludmann** [comment]
Do you have a workspace ID of the workspace?

**Comment by nisarhassan12** [comment]
Sorry. I don't have the ID.

**Comment by akosyakov** [comment]
@nisarhassan12 Could you try against https://github.com/gitpod-io/gitpod/pull/1909?

**Comment by nisarhassan12** [comment]
@akosyakov I tried against https://github.com/gitpod-io/gitpod/pull/1909 and this is the terminal output:

![image](https://user-images.githubusercontent.com/46004116/97184483-c8812a80-17c0-11eb-90d3-ddab3077aba4.png)

No logs regarding the tasks which were supposed to run on this terminal although the ports view is rendered as expected looks like the task `yarn dev` ran but there were no logs and the preview for port 8000 does not seem to work.

![image](https://user-images.githubusercontent.com/46004116/97184722-0bdb9900-17c1-11eb-9646-88b40c21d2ec.png)

**Comment by nisarhassan12** [comment]
I tried another workspace againist #1909 http://cw-supervisor-ports.staging.gitpod-dev.com/#https://github.com/gitpod-io/website where it seems to work fine:

![image](https://user-images.githubusercontent.com/46004116/97185357-c370ab00-17c1-11eb-9acd-fac0fe9ec830.png)

**Comment by akosyakov** [comment]
let's track terminal issues separately, in regard to ports I think it is addressed in https://github.com/gitpod-io/gitpod/pull/1909

**Comment by akosyakov** [comment]
ports issue was resolved in https://github.com/gitpod-io/gitpod/pull/1909, terminal issue is tracked in https://github.com/gitpod-io/gitpod/issues/2116
