### ISSUE TITLE
[staging]: No logs regarding the tasks in `.gitpod.yml` 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2063]
### Describe the bug

A few days back I opened a workspace for https://github.com/nisarhassan12/blueprint and there were No logs regarding the tasks in `.gitpod.yml` 

![image](https://user-images.githubusercontent.com/46004116/97150911-a374c380-1790-11eb-8f95-9fd0021a731e.png)

I tried a new workspace and I'm unable to re-produce the above.

**Comment by nisarhassan12** [comment]
I'm able to reproduce this randomly, this time around the log is a bit different though:

![image](https://user-images.githubusercontent.com/46004116/97152423-aec8ee80-1792-11eb-9904-0d3d03f8afb5.png)

**Comment by csweichel** [comment]
This is a distinct IO issue. I've filed the issue there.
