### ISSUE TITLE
Cannot Resolve Workspace Image in docker-compose based self hosted instance

### ISSUE THREAD

**Issue by BenjaminBeichler** [gitpod-io/gitpod#2068]
### Describe the bug
When creating a new workspace the following error is created:

```
Request startWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: Error response from daemon: Get https://registry.gitpod.beichler.info/v2/: dial tcp: lookup registry.gitpod.beichler.info on 10.43.0.10:53: no such host
Please file an issue if you think this is a bug.

```
### Steps to reproduce
install gitpod via docker-compose.yaml with lets-encrypt https-certificates supplied

### Expected behavior
workspace should be created

### Additional information
the registry pod is running 
this is created with docker-compose exec
```
kubectl get pods
NAME                               READY   STATUS      RESTARTS   AGE
registry-facade-6b9844459f-k6kn9   1/1     Running     0          38m
ws-scheduler-8b5785dbd-kkwjf       1/1     Running     0          38m
svclb-proxy-k5hb5                  2/2     Running     0          38m
dashboard-5774db8bb9-6dpw4         1/1     Running     0          38m
ws-sync-5l5zt                      1/1     Running     0          38m
ws-manager-ff87f767b-mqk6s         1/1     Running     0          38m
ws-manager-node-ds7qm              1/1     Running     0          38m
image-builder-66f6b975f6-r9lfh     2/2     Running     0          38m
registry-5b68d4db9c-hn26w          1/1     Running     0          38m
proxy-6696d745bd-w7scn             1/1     Running     0          38m
minio-6845c586dc-9c48z             1/1     Running     0          38m
theia-server-7b4fbd946f-tl2bd      1/1     Running     0          38m
messagebus-659bb5d458-qvzc2        1/1     Running     0          38m
node-daemon-56pv7                  1/1     Running     0          38m
mysql-65c5b9f8f9-dmtzj             1/1     Running     0          38m
ws-manager-bridge-65d7cc4f-s425x   1/1     Running     0          38m
gitpod-helm-installer              0/1     Completed   0          38m
server-b74cbbfc8-4rkpj             1/1     Running     0          38m
```

**Comment by corneliusludmann** [comment]
Just to make sure: Do you use the latest docker image?
```
docker pull eu.gcr.io/gitpod-core-dev/build/gitpod-k3:latest
```

**Comment by BenjaminBeichler** [comment]
yes, actually I use this docker-compose file https://github.com/gitpod-io/gitpod/blob/master/install/docker/examples/gitpod/docker-compose.yaml

**Comment by corneliusludmann** [comment]
A few more questions:
- Do you have a custom `values.yaml` file?
- Is `registry.gitpod.beichler.info` configured in your DNS correctly? Could you ping it from your node?
- What does `docker-compose exec gitpod cat /etc/resolv.conf` say?

**Comment by BenjaminBeichler** [comment]
> A few more questions:
> 
> * Do you have a custom `values.yaml` file?
no
> * Is `registry.gitpod.beichler.info` configured in your DNS correctly? Could you ping it from your node?
I set a wildcard cname in my DNS-Config to the host which runs the docker-daemon. If I ping, this ist the output:
```
ping registry.gitpod.beichler.info
PING gitpod.beichler.info (139.30.202.38) 56(84) bytes of data.
64 bytes from fud738-374.amd.e-technik.uni-rostock.de (139.30.202.38): icmp_seq=1 ttl=64 time=0.096 ms
```
Hopefully the reverse-name resolution is not problematic.

> * What does `docker-compose exec gitpod cat /etc/resolv.conf` say?
```
search amd.e-technik.uni-rostock.de
nameserver 127.0.0.11
options ndots:0
nameserver 127.0.0.11
nameserver 172.21.0.2
```
I hope the search domain is not critical, but I could change it.

**Comment by BenjaminBeichler** [comment]
Within the container the ping is also successfull:

```
docker-compose exec gitpod ping registry.gitpod.beichler.info
PING registry.gitpod.beichler.info (139.30.202.38): 56 data bytes
64 bytes from 139.30.202.38: seq=0 ttl=64 time=0.121 ms
64 bytes from 139.30.202.38: seq=1 ttl=64 time=0.117 ms
```

**Comment by BenjaminBeichler** [comment]
@corneliusludmann is any information missing ?

**Comment by BenjaminBeichler** [comment]
Mhh actually, this machine is a Proxmox VM (not LXC Container) with an Ethernet-Interface getting one public accessible ip address, without any firewall restrictions. I'm using an Ubuntu 20.04 Cloud Image and installed upstream docker.

Currently, I'm trying to get it running in a rancher kubernetes docker container, but since I'm totally unexperienced with kubernetes, it is quite hard to get into this whole stuff.

Another problem raised, when I tried to use not the latest tag, but the newest master tag (master.133), and it fails to install the helm chart.

**Comment by corneliusludmann** [comment]
The newest master tags are some kind of nightly builds and not supported. They probably don't work at all. Usually, the GCP installation works best since we use GCP for production. Good Kubernetes skills are recommendable to get Gitpod self-hosted running.

**Comment by BenjaminBeichler** [comment]
yeah, I was expecting, that not all nightly build work, but I want to give it a try.

I understand, that GCP is recommended, but I think I won't get the financial resources to host an adequate GCP instance. I want to do a student class and it is even not feasible to require a gitlab/github account from all students.
