### ISSUE TITLE
K8S deployment doc: Too less information to finish helm value setting

### ISSUE THREAD

**Issue by iWangJiaxiang** [gitpod-io/gitpod#2069]
For example, this doc [Docker Registry Docs - Gitpod](https://www.gitpod.io/docs/self-hosted/latest/install/docker-registry/) tells admin how to setup private docker registry and the steps are as followed:

![image](https://user-images.githubusercontent.com/19409802/97260513-e8aff880-1857-11eb-9e92-6f30dddaf206.png)

But there is nowhere I could find detailed info about `values/registry.yaml` file. How could I do it if I know nothing about the content.

And other docs have the same issue, too.

Could you please update the doc?

Thank you!

**Comment by wulfthimm** [comment]
The content of the `registry.yaml` is by default:
```gitpod:
  components:
    imageBuilder:
      registryCerts: []
      registry:
        # name must not end with a "/"
        name: your.registry.com/gitpod
        secretName: image-builder-registry-secret
        path: secrets/registry-auth.json

    # server:
    #   defaultBaseImageRegistryWhitelist:
    #   - some.registry.domain.com

    workspace:
      pullSecret:
        secretName: image-builder-registry-secret

  docker-registry:
    enabled: false

gitpod_selfhosted:
  variants:
    customRegistry: true
```

You can find the old one [here](https://github.com/gitpod-io/self-hosted/tree/master/values) or look for the values to configure the registry in [this file](https://github.com/gitpod-io/gitpod/blob/3e5b45b8c411405003f556e56ebb397b1d0d64f1/chart/values.yaml#L160).
