### ISSUE TITLE
Connect gitpod.io account with self-hosted GitLab instance

### ISSUE THREAD

**Issue by LinqLover** [gitpod-io/gitpod#2073]
I seem to miss any proper documentation. I have a self-hosted GitLab instance and followed [these steps](https://docs.gitlab.com/ee/integration/gitpod.html) to enable the Gitpod integration.
Unfortunately, when I open <https://gitpod.io/login/>, I only see three buttons for logging in with GitHub, GitLab.com, and BitBucket, but there is no button for connection my self-hosted GitLab instance. Also in the [Access Control settings](https://gitpod.io/access-control/), there is no button for self-hosted GitLab.

How can I open a repository from my self-hosted GitLab instance in Gitpod? Thanks in advance.

**Comment by corneliusludmann** [comment]
Unfortunately, that's not possible yet. It's a feature that is coming soon but currently, you have to host your own Gitpod instance for that.

**Comment by LinqLover** [comment]
Where is the feature coming soon being traced?

**Comment by wulfthimm** [comment]
We have put the information into our list and will discuss the release of this feature.

**Comment by svenefftinge** [comment]
This is now available, from settings https://gitpod.io/settings

**Comment by TeNNoX** [comment]
Thanks a lot for adding this feature!


I added our self-hosted gitlab as provider in gitpod.io settings.
Sadly, I cannot get it to work:
![IMG_20201208_144154_416](https://user-images.githubusercontent.com/2084639/101498163-ae13a280-3963-11eb-8d68-fbdfe547062e.jpg)

![IMG_20201208_144156_549](https://user-images.githubusercontent.com/2084639/101498135-a81dc180-3963-11eb-8526-5cbe04fb00fe.jpg)

Url: `https://gitpod.io/#https://gitlab.ourdomain.org/cybernetics/our-board/-/tree/master/`

**Comment by akosyakov** [comment]
@TeNNoX please file a new issue for better visibility

**Comment by TeNNoX** [comment]
Alright ;}
  #2606
