### ISSUE TITLE
Gitpod install on cloud server

### ISSUE THREAD

**Issue by rajanagori-hl60** [gitpod-io/gitpod#2074]
I just wanted to ask about the gitpod installation on my cloud server. I'm trying to install the gitpod instance with creating the docker-compose file with all the images from gitpod/workspace-full repo and up the instance. docker-compose file runs the instances but exited same time. I check the docker container logs but can't find any appropriate information regarding.

**Comment by corneliusludmann** [comment]
Do I understand it correctly that `docker-compose up` fails? Could you please post at least the last lines from `docker-compose logs`?

**Comment by rajanagori-hl60** [comment]
It is only showing "No logs available".

**Comment by corneliusludmann** [comment]
That's odd. Could you please describe your steps in more detail?

**Comment by rajanagori-hl60** [comment]
Yes, First I take the pull of the latest Image then make file.yml file in which I have mention the gitpod image with ports and finally docker-compose -f file.yml up -d

**Comment by corneliusludmann** [comment]
Unfortunately, that's still not enough information to reproduce your setting. E.g.:
- How does your `file.yml` look like?
