### ISSUE TITLE
The “Download Chrome extension” block is displayed although the extension is installed.

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#208]
**Description:**

The “Download Chrome extension” block is displayed although the extension is installed.

**Preconditions:**
 
Install the browser extension

**Steps To Reproduce:**

1. Login to the site
2. Start the workspace
3. Pay attention to the "Download chrome extension" block

**Actual result:**

The “Download Chrome extension” block is displayed although the extension is installed.
![experience](https://user-images.githubusercontent.com/41964662/50285863-2d9dc380-0466-11e9-9798-1f39459f6b58.png)

**Expected result:**
The “Download Chrome extension” block is not displayed although the extension is installed.

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98

**Comment by svenefftinge** [comment]
This is only happing for staging and is expected
