### ISSUE TITLE
Vetur Installation on project

### ISSUE THREAD

**Issue by Yael95** [gitpod-io/gitpod#2082]
I just tried to install Vetur which is an extension for syntax highlighting for the vuejs framework and a bunch of other useful things, but when I install it i guet this issue popping out after the installation : **_Activating extension Vetur failed: Cannot read property 'includes' of undefined._** 
Do you know how can I solve it as do not get all the capacities of the extension and the necessary syntax highlighting.

**Comment by wulfthimm** [comment]
Have you checked that it is not related to the extension itself? Could you give us more information about the version of the extension? Have you installed Gitpod yourself or are you using Gitpod.io?

**Comment by Yael95** [comment]
I tried to install it directly from the store on gitpod.io, just type very and try to install it it throws an error.

**Comment by gtsiolis** [comment]
Hi @Yael95! FYI This should be resolved within the next days, see [relevant discussion](https://community.gitpod.io/t/vetur-extension-not-working/1960/6):

> ... this has been already fixed in our staging environment and will be soon deployed in production at gitpod.io. This is planned to happen within the next days, stay tuned!

**Comment by Yael95** [comment]
Great, thank you for working on gitpod it is an amazing workspace.
