### ISSUE TITLE
why my workspace has ben bloked?

### ISSUE THREAD

**Issue by fbigun** [gitpod-io/gitpod#2083]
I am prompted after logging in to gitpod

---------
```
Your account has been blocked.
If you have questions please contact us.
```

I don't know where the problem is, can I continue to use it.

**Comment by wulfthimm** [comment]
You get blocked if you have acted against the terms of services that are described [here](https://www.gitpod.io/terms/). If you think that there is a failure, please reach out to contact@gitpod.io  and file a complaint.
