### ISSUE TITLE
reloading the stopped loading screen does not restart the workspace

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#2085]

**Comment by akosyakov** [comment]
Resolved by https://github.com/gitpod-io/gitpod/pull/2113

**Comment by gtsiolis** [comment]
I run into this a few times while trying to review https://github.com/gitpod-io/gitpod/pull/2192, opened https://github.com/gitpod-io/gitpod/issues/2257 to continue discussion. 🏀
