### ISSUE TITLE
The "Version control is not available at this time" message is displayed in the "Left" panel.

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#209]
**Description:**

The "Version control is not available at this time" message is displayed in the "Left" panel.

**Steps To Reproduce:**

1. Login to the site
2. Start the workspace
3. Open the Git in the "Left" panel
4. Pay attention to the "Left" panel

**Actual result:**

The "Version control is not available at this time" message is displayed in the "Left" panel.
![git](https://user-images.githubusercontent.com/41964662/50287358-2b8a3380-046b-11e9-8d59-2a545c717336.png)

**Expected result:**
The “Git" panel is displayed 

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98

**Comment by svenefftinge** [comment]
We are working on a fix.

**Comment by AlexTugarev** [comment]
fixed.
