### ISSUE TITLE
Cannot push to public repo with gitpod

### ISSUE THREAD

**Issue by Yael95** [gitpod-io/gitpod#2099]
I have been working on an app in NuxtJS and I just started out writing basic functionality when I wanted to push (knowing that I granted Gitpod all the access rights even the read organizations one hoping it would be some network issue), I still get the following error and I do not seem to get why because It was working just two weeks ago.

Here is what I get in my terminal:
![problemgitpod](https://user-images.githubusercontent.com/13720660/97815159-7b9fc700-1c8c-11eb-886e-c3e4bdbc43f4.JPG)

**Comment by JanKoehnlein** [comment]
Sorry for the late reply. It looks like the remote for your git repository has been deleted. 
Did you try to reconnect it using `git remote add <name> <url>` as prompted?
