### ISSUE TITLE
[review] cannot open review conversations view anymore

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#2104]
### Describe the bug
Review conversations view doesn't open anymore.

### Steps to reproduce
- Open a PR with comments in Gitpod.
-> The comments view doesn't open. It won't open by using the menu or the link the PR view either.

### Expected behavior
The comments view should open

### Additional information
Log shows an DI error on constructor injection. @akosyakov already tracked it down to a bogus object in our compare routine. Could be GitHub APIs have changed slightly.

<img width="346" alt="Screenshot 2020-11-03 at 09 00 37" src="https://user-images.githubusercontent.com/377752/97966335-fd424280-1dbb-11eb-9ebe-f691110a10e6.png">

### Example repository
Doesn't happen with all repos. It's reproducible with PR 82 in the TypeFox Website repo. Maybe because it's private, maybe because some of the comments trigger the bug.

**Comment by akosyakov** [comment]
It also breaks commenting.
