### ISSUE TITLE
Opening workspaces on git-tags is broken

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#211]
**Describe the bug**
I can't open a workspace on a git-tag. 

**To Reproduce**
Open https://gitpod.io#https://github.com/32leaves/ruruku/tree/v0.3.1

**Expected behavior**
A workspace with the git-tag checked-out.

**Comment by meysholdt** [comment]
duplicate of #385

**Comment by jankeromnes** [comment]
Oh, sorry for re-filing an issue you had already filed. I did try search, but maybe not hard enough.
