### ISSUE TITLE
Cannot change the keyboard shortcut for View:Find Command

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#2112]
### Describe the bug
Cannot change the keyboard shortcut for View:Find Command. By default it's set to Shift-CMD-P; this conflicts with opening a private window in Firefox on macOS. 

#### Can't remap the View:Find Command shortcut
- On macOS
- Using Firefox
- Open File: Settings: Keyboard Shortcuts
- Search for either "Command", "View", "shift", "cmd etc

**Result**: Nothing related to the menu View:Find Command is available

**Expected** : An item for changing the View:Find Command keybinding should be available 

#### Can't use  default shortcut
- On macOS
- Using Firefox
- Open any repo
- Hit "Shift-CMD-P"

**Result**: Private window opens

**Expected**: Command Pallet opens

### Additional information
- macOS, any version
- FireFox, any version

### Example repository
Any repository

**Comment by JanKoehnlein** [comment]
What you're looking for seems to be `workbench.action.showCommands`. I can change the key binding for this locally in Firfox on Mac without problems. Into the bargain, it is always bound to `F1` which doesn't have a conflict and works in FF as well.

**Comment by smacintyre** [comment]
@JanKoehnlein Thank you! I searched high and low for that.
