### ISSUE TITLE
https://developers.eos.io/welcome/latest/getting-started/try-eosio

### ISSUE THREAD

**Issue by rusty-block-one** [gitpod-io/gitpod#2114]
### Describe the bug
Displays error message
We are having trouble parsing your context
Error: GitHub API Error. Status: 403

### Steps to reproduce
Selected "right now" link to try eosio-web-ide

### Example repository
unknown

**Comment by ponsel55** [comment]
RETETS

**Comment by JanKoehnlein** [comment]
Can you give a bit more information on what context you're trying? What is the link? Where can I find the button "right now"?

**Comment by AlexTugarev** [comment]
@rusty-block-one just tried with `https://gitpod.io/#https://github.com/EOSIO/eosio-web-ide` (URL from ☝️ link) and it works fine.

```
We are having trouble parsing your context
Error: GitHub API Error. Status: 403
```
'Don't see a simple reason why GitHub is responding with `Forbidden`, it's a public repo after all. Do you still can reproduce.
