### ISSUE TITLE
Error starting workspace on staging

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2118]
```
cannot initialize workspace: cannot find workspace upperdir: mount entry has no appropriate mapping; last backup failed: workspace does not exist. Please contact support if you need the workspace data.
Please file an issue if you think this is a bug.
```

<img width="1280" alt="Screenshot 2020-11-04 at 07 06 14" src="https://user-images.githubusercontent.com/372735/98075235-49e55680-1e6c-11eb-8a23-5fbaa48ab2ac.png">

**Comment by AlexTugarev** [comment]
This happens to be the case if the full workspace backup feature is enabled.

**Comment by akosyakov** [comment]
@csweichel is it still valid?

**Comment by csweichel** [comment]
I don't know
