### ISSUE TITLE
Self-hosted ws-proxy passes multiple Cookie headers

### ISSUE THREAD

**Issue by tomusher** [gitpod-io/gitpod#2121]
### Describe the bug
After having set up Gitpod self-hosted on GCP using the documented installation tool, we noticed issues with our Python application parsing cookies when running inside a Gitpod workspace.

It looks like when `ws-proxy` forwards the cookies to the application in the workspace, it splits them in to separate Cookie headers which prevents the application from parsing them correctly (as it's expecting a single header separated by semi-colons).

### Steps to reproduce
1. Install Gitpod on GCP using the installer container.
2. Start a workspace from this demo repo https://github.com/tomusher/gitpod-test
3. Access the generated service URL, note the output in the logs indicates that there are multiple Cookie headers (one for `theme` and one for `gitpod-user`) and that Python has only parsed one header.
4. Try the same repo on Gitpod.io and note that the Cookies are all available in a single header and Python parses them correctly.
5. Disable ws-proxy by setting `components.wsProxy.disabled` to true in `values.yaml` and reapply the changes through helm.
6. Note now that ws-proxy is no longer being used, cookies are served correctly.

### Expected behavior
Cookies passed by ws-proxy should be served in a single `Cookie` header.

### Example repository
https://github.com/tomusher/gitpod-test

**Comment by csweichel** [comment]
@tomusher thank you for providing the handy test server. That made replicating the issue a breeze 💯
