### ISSUE TITLE
enable long term caching for dashboard

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#2127]
Clients should fetch only once static resources of the dashboard and don't ask server anymore till the next deployment. Currently clients are doing multiple requests which all end up with 304 which unnecessary increase the initial loading time.

It is particularly important for the loading screen since it is used on the workspace location.

See for how to enable it with webpack: https://developers.google.com/web/fundamentals/performance/webpack/use-long-term-caching

**Comment by akosyakov** [comment]
It also would be good to bundle as much as possible, right now there are myriad small requests to pull the loading screen which is harming a lot with high latency.

**Comment by akosyakov** [comment]
It is hard with the current dashboard setup. It would be good to simplify, streamline and speed it up via bundling everything properly via wepback and getting rid of ts-loader.

**Comment by geropl** [comment]
Unassigned because I did https://github.com/gitpod-io/gitpod/pull/3552 but that does not fix the issue for images, yet. More webpack magic needed for that.

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/3552 and https://github.com/gitpod-io/gitpod/pull/3556
