### ISSUE TITLE
You've been Blocked

### ISSUE THREAD

**Issue by HackrTP** [gitpod-io/gitpod#2137]
I was making my github repository because I am trying to figure out why any changes I make on gitpod.io, doesn't show on my github repository. But, when I was in the middle of adding a readme it said disconnected, so I reconnected but it says I have been blocked. Is there anything that I did wrong or bad? All I was doing was trying to figure out why nothing on my github repository was changing when I made edits on the gitpod.io website.

**Comment by wulfthimm** [comment]
Being blocked means that there has been a violation with the [TOS](https://www.gitpod.io/terms/). Please reach out to contact@gitpod.io to get your account unlocked.

**Comment by aidarsgames** [comment]
Hey, I've been waiting for 2 days for an answer from contact gitpod how long will it take?

**Comment by dey7322** [comment]
make a new gitpod account ez
