### ISSUE TITLE
Configurable default Dockerfile

### ISSUE THREAD

**Issue by sherbang** [gitpod-io/gitpod#214]
I'd like to configure a default Dockerfile or Docker Image in my account that is used, instead of gitpod/workspace-full, when a git repo doesn't have it's own default defined.

My default Dockerfile will be pre-configured with the development tools/shortcuts that I prefer to use.

**Comment by svenefftinge** [comment]
We could add that as a last resort before using the default workspace-full. I.e. with less priority than project-specific docker information. Is that what you are asking for?

**Comment by sherbang** [comment]
Yes @svenefftinge, that was exactly what I was was thinking.

There's definitely some added benefits to @meysholdt 's solution.

Ideally, I'd like both.  If no image is defined for a repo, then use my default image instead of workspace-full, but if an image is defined, then run my additional commands on top of it to set up git aliases and such.

For mine, I built a base image that sets up my /home/gitpod directory.  In my images I'm using:
```
RUN apt-get install -y <tools I always want>
COPY --from=<base image> --chown gitpod:gitpod /home/gitpod /home/gitpod
```

If I'm dealing with images for different OSes regularly then I'll modify my additional commands to take that into account:
```
RUN if [ -d /etc/apt ] ;then apt-get install htop; elif [ -d /etc/apk ] then apk add htop; fi 
```
If that gets out of control, then it's time to start using something like Ansible inside your overlay.
