### ISSUE TITLE
Can't connect to my account

### ISSUE THREAD

**Issue by CubasticBanjo** [gitpod-io/gitpod#2140]

**Comment by CubasticBanjo** [comment]
![Uploading inkwell-pen-and-paper-old-symbol-for-line-vector-29687520 (1).jpg…]()

**Comment by AlexTugarev** [comment]
@CubasticBanjo could you provide more details on the issue?

**Comment by AlexTugarev** [comment]
@CubasticBanjo, I've searched the logs, but couldn't find your GitHub user name at all. Please reopen and provide some more details in order to help you to get started 🙏
