### ISSUE TITLE
It would be more user friendly if you add the "progress" bar in the "Bottom Status" bar, when user is using some functions ( run, debug, commit ..) 

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#215]
It would be more user friendly if you add the "progress" bar in the "Bottom Status" bar, when user is using some functions ( run, debug, commit ..) 
For example:
![progress](https://user-images.githubusercontent.com/41964662/50351302-6b741800-054a-11e9-8249-44125ac66371.png)

**Comment by AlexTugarev** [comment]
this depends on a particular task. progress indicators are about to be introduced. in general the plan is to align with vscode as far as possible.
