### ISSUE TITLE
Cannot install VSCode extension that has keytar dependency

### ISSUE THREAD

**Issue by mixellent** [gitpod-io/gitpod#2169]
### Describe the bug
When installing the [WhiteSource Advise extension](https://marketplace.visualstudio.com/items?itemName=whitesource.whitesource-advise) VSIX from the VS marketplace, running any of the extension commands does not do anything (no logs/error displayed in view. This seems to be related to lack of support for VS Code extensions relying on keytar.

### Steps to reproduce

1. Drag WhiteSource Advise VSIX extension to Extensions section in GitPod IDE
2. Extension successfully installed
3. Run command "WhiteSource: Activate WhiteSource Advise"
4. Nothing happens

### Expected behavior
A popup is displayed asking the user to enter their email address and WhiteSource license key.

**Comment by akosyakov** [comment]
Unfortunately `keytar` is not supported yet by Theia: https://github.com/eclipse-theia/theia/issues/4935 FYI we are working on brining alternative IDEs including Gitpod version of Code: https://github.com/gitpod-io/gitpod/issues/1780

**Comment by jankeromnes** [comment]
FYI, I previously attempted to solve this by installing `keytar` into Gitpod's Theia IDE image: https://github.com/gitpod-io/gitpod/pull/2562

Unfortunately, it didn't work as expected (not sure why). It's good to have VS Code as an alternative IDE to Theia (see Settings), but if possible I'd still like to somehow install `keytar` in the Theia image to solve this everywhere.

**Comment by akosyakov** [comment]
@jankeromnes We are going to remote Theia in Q2. It is better to start recommending switching to VS Code to everybody.

**Comment by akosyakov** [comment]
Please switch to VS Code in settings instead.
