### ISSUE TITLE
Chrome always asks for permission to use the clipboard for new workspaces

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#2177]
### Describe the bug
When I create a new workspace (and I do this for every change), I need to re-allow clipboard access

### Steps to reproduce
Create new workspace. Try to paste something or copy something.

### Expected behavior
Just do it once! Is there a way to make this experience better? This is a pretty annoying problem.

**Comment by akosyakov** [comment]
I've marked it as Theia, but it would be an issue for any IDE. We need to investigate whether we can ask for such permissions for all subdomains of gitpod.io

**Comment by akosyakov** [comment]
Could you try to add something like `https://[*.]gitpod.io` into clipboard permissions settings of your Chrome? Does it help?

**Comment by Michaelhobo** [comment]
Yup, that works.
Another option: would it be better to move the unique ID out of the subdomain? gitpod.io/workspace/abcdefg could make this work out of the box. I'm also worried that you'll run into the same problem for all chrome permissions settings.

**Comment by PatMyron** [comment]
@akosyakov is it possible to only prompt for permission when programmatically accessing the clipboard? Gitpod is the only site I've encountered that prompts when manually pasting

**Comment by gtsiolis** [comment]
@PatMyron see [relevant docs](https://www.gitpod.io/docs/configure/browser-settings#browser-settings):

> For the best experience when working with Gitpod, we recommend you whitelist the `.gitpod.io` domain in your browser for the following permissions:

> - Paste content from your clipboard to a Gitpod workspace
> - Pop-ups, to preview your dev server in a new tab

**Comment by axonasif** [comment]
@gtsiolis I think @akosyakov above told a similar thing too (which is documented now 🙂) but I wonder if that's what he want, I'm kind of confused 😅

**Comment by gtsiolis** [comment]
Thanks for chiming in, @axonasif!

@PatMyron if the browser workaround described in https://github.com/gitpod-io/gitpod/issues/2177#issuecomment-1008080273 does not help, please open a new issue describing the feature request or bug report. This can help avoid re-opening a closed issue or continuing the discussion in a stale thread. 🏓

**Comment by PatMyron** [comment]
@gtsiolis understand the workaround, but I'm specifically asking why Gitpod is the only site I've encountered that prompts for extra permissions to be able to paste text? Is there some functionality where Gitpod is reading the clipboard at other times? Why can I paste text on other sites without this extra permission but not Gitpod?

**Comment by axonasif** [comment]
> understand the workaround, but I'm specifically asking why Gitpod is the only site I've encountered that prompts for extra permissions to be able to paste text? Is there some functionality where Gitpod is reading the clipboard at other times? Why can I paste text on other sites without this extra permission but not Gitpod?

I guess this is specific to [VSCODE-WEB](https://github.com/gitpod-io/openvscode-server/tree/gp-code/main). I would encourage to create a new issue if there is some important matter you want to discuss about as @gtsiolis suggested!

**Comment by gtsiolis** [comment]
@PatMyron you would experience the same browser behavior for example also when trying to paste something in the terminal in [OpenVSCode Server](https://github.com/gitpod-io/openvscode-server/), [GitHub Codespaces](https://github.com/codespaces), etc. See also [relevant docs](https://code.visualstudio.com/docs/remote/codespaces#_how-do-i-allow-vs-code-to-access-my-clipboard-for-reading) from `code.microsoft.com`. 📚

**Comment by akosyakov** [comment]
Please file an issue in https://github.com/microsoft/vscode
