### ISSUE TITLE
Block on account

### ISSUE THREAD

**Issue by xQuicklyy** [gitpod-io/gitpod#2178]
Hello,
Strongest apologies that I didn't know that Denial of Service attacks were against the TOS. I tested my own network(can be proven via logs) to see how strong it can stand against a denial of service attack. Could I please be given a second chance?

**Comment by ret394** [comment]
I'm not on Gitpod team. But I have to say - Just ask first newbie, it is a open source project with a helpful attitude.

By the way, you probably should create a private issue for this if you are interested in helping them improve system resilience.

And were you performing a DoS attack again in the last 24 hours? I am having a weird issue at a bad time, and need all targets.

thanks ret394

**Comment by ret394** [comment]
Can someone add the stupid label to this issue? ;-)

**Comment by corneliusludmann** [comment]
I unblocked you, @xQuicklyy. Note that Gitpod's main purpose is to develop software. Also, please get familiar with our [TOS](https://www.gitpod.io/terms/).
