### ISSUE TITLE
IDE configuration ignored

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2179]
In staging I have changed my IDE settings to `Code`. I started workspace on this repo and got the Code IDE as expected.
When starting a workspace on https://github.com/opentracing/opentracing-javascript I get Theia (tried twice).

**Comment by akosyakov** [comment]
Are you sure that you enabled registry facade for your user? It should be addressed by https://github.com/gitpod-io/gitpod/pull/2171

**Comment by svenefftinge** [comment]
Yes, I'm sure, because I was able to start Code with this repo. Did you try to reproduce?

**Comment by akosyakov** [comment]
I started 5 workspaces on different repos and could not reproduce 😬

**Comment by svenefftinge** [comment]
Same here, no longer reproducible.
