### ISSUE TITLE
Hot reloading not working Gatsby

### ISSUE THREAD

**Issue by marcoSven** [gitpod-io/gitpod#2181]
Is there a quick fix? 

Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

https://gitpod.io/#snapshot/5949ff0d-369b-48f6-8b2c-0fcc57092062

**Comment by svenefftinge** [comment]
Yes, you need to pass `--host 0.0.0.0`
i.e. `yarn dev --host 0.0.0.0`

**Comment by marcoSven** [comment]
Thank you!
