### ISSUE TITLE
Allow deleting workspace after merge request

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#2182]
This is an idea for a future integration with gitlab/github/bitbucket/etc. When a PR has been merged, have a button that lets you delete the associated gitpod workspace.

I want this for a few main reasons:
- Some people like to have a clean workspace dashboard, to keep track of tasks
- I usually have ~10 "active" workspaces, but a few contain low priority work or experiments. After a few weeks, they get buried in lots of newer but finished workspaces. 
- I often reuse branch names, and I get mixed up when there are multiple workspaces with the same name. Pruning finished ones would keep that number manageable.

**Comment by ret394** [comment]
>     * Pruning finished ones would keep that number manageable.

Quite plainly it is a banal request. 

- I want to prune all the ones that ended up to be duds despite the hype. Not one by one, oh dear god!

thanks
you're welcome, as always. all the best. 👍
don't say nasty stuff or do rude stuff to folks on Github or other sites.

[ret394](https://github.com/ret394)

**Comment by Michaelhobo** [comment]
Lol

**Comment by gtsiolis** [comment]
Thanks for bring this up @Michaelhobo! 💯 

Sounds like a logical request as it's a similar pattern GitLab and GitHub already provide for branches after merging a Merge Request or a Pull Request.

Offering more efficient ways to clean up stopped workspaces is definitely something we could improve.

**Comment by akosyakov** [comment]
It is good practice to always push your work and create a new workspace again later. Workspaces dashboard is more like a history. All unused workspaces are already get deleted in 14 days if they are not pinned. If you don't want to push your changes then pin a workspace and select `show pinned workspaces only` on the dashboard.

**Comment by Michaelhobo** [comment]
I see, pinning and switching to a push-and-recreate-workspace workflow are decent alternatives for many of my use cases.
I still think keeping longer-running workspaces has its uses:
* There are many uses for a workspace that don't result in push-able work. e.g. experimenting with infrastructure, setting up a test for debugging flakes, etc
* New workspaces come with a rebuilding cost for some uses, e.g. Bazel dependency caches, which take upward of 5min to rebuild the cache. The same goes for downloading large datasets, pulling down and building some toolchains, and a bunch of other use cases. The /workspace/* cache saves a lot of time for these.

Pinning is definitely useful, but it requires a user to pin it after creation, and then later unpin it when they're done with it - maybe we can work on improving the ergonomics of pinning? e.g. if I could pin from the workspace (not the dashboard), and unpin after the merge request, that could work.
