### ISSUE TITLE
"last backup failed: cannot delete workspace from store."

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2188]
Started a manual prebuild on this repo's main branch using staging.
Result was:
<img width="831" alt="Screenshot 2020-11-17 at 07 20 45" src="https://user-images.githubusercontent.com/372735/99353830-989be300-28a5-11eb-9650-4adb582b299c.png">

wsID: b7a74fd3-5b4f-43e4-9c3b-c789fb5a7008

**Comment by csweichel** [comment]
This issue masks the underlying problem: user namespaced workspaces don't start in staging.
Because the supervisor crashes so quickly, ws-daemon removes the workspace content while the initialisation is still happening, hence the error message.
