### ISSUE TITLE
[prebuild] Cannot retrigger prebuilds

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2189]
Starting a prebuild on a branch where someone else has already created a prebuild results in

<img width="972" alt="Screenshot 2020-11-17 at 06 41 28" src="https://user-images.githubusercontent.com/372735/99355785-347b1e00-28a9-11eb-9ab6-a448f61eddfe.png">

https://gitpod-staging.com/#prebuild/https://github.com/gitpod-io/spring-petclinic

**Comment by akosyakov** [comment]
Maybe related: https://github.com/gitpod-io/gitpod/issues/2046
