### ISSUE TITLE
The "Refactor / Rename Symbol" functions don't work

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#219]
**Description:**

The "Refactor / Rename Symbol" functions don't work

**Steps To Reproduce:**

1. Login to the site
2. Start the workspace 
3. Use the "Refactor / Rename Symbol" functions (context menu)
4. Pay attention to the workspace

**Actual result:**

The "Refactor / Rename Symbol" functions are not worked 
![rename](https://user-images.githubusercontent.com/41964662/50355114-4e454680-0556-11e9-8a86-effc1b9f3314.gif)

**Expected result:**

The "Refactor / Rename Symbol" functions is works

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98

**Comment by 32leaves** [comment]
This is somewhat expected behaviour - a string is not a symbol that can be renamed. We could not have the menu item visible/enabled on strings, or change the string after all.
