### ISSUE TITLE
Fail to start JSON language server: connection got disposed

### ISSUE THREAD

**Issue by ElviraQDP** [gitpod-io/gitpod#2193]

**Comment by AlexTugarev** [comment]
Hi @ElviraQDP,
can you provide an example how reproduce the issue, please?
I just tried with a simple test, but couldn't find any issue
<img width="675" alt="Screen Shot 2020-11-18 at 09 06 49" src="https://user-images.githubusercontent.com/914497/99502517-77a6c100-297d-11eb-9ced-7abdce7dcb2e.png">

**Comment by ElviraQDP** [comment]
it happened when I open a repo on gitpod, I couldn't see any file do to that error
![image](https://user-images.githubusercontent.com/63673743/99549804-d0378780-2998-11eb-8fc9-5c1173eed451.png)

**Comment by akosyakov** [comment]
Could you share your workspace id please? Do you see the yellow status bar from time to time? It looks like you are having connection issues.

**Comment by ElviraQDP** [comment]
Where can I get my worksapce id?

**Comment by ElviraQDP** [comment]
https://ce0090ea-adec-472f-a2cd-317bc38c1434.ws-us02.gitpod.io/#/workspace/bootstrap-exercises-tutorial

**Comment by akosyakov** [comment]
Yes, from logs I see that on 2020-11-17 you experienced many disconnections between 18 and 21 CET time, but since when it seems to be operating well? Are you sure that you did not have bad internet connection that evening?
