### ISSUE TITLE
We are having trouble parsing your context Error: NotFoundError

### ISSUE THREAD

**Issue by JustinHaase** [gitpod-io/gitpod#2194]

**Comment by JustinHaase** [comment]
Just trying to open Gitpod for the first time. receiving the following message: 
"
![Screenshot 2020-11-17 201515](https://user-images.githubusercontent.com/74632537/99471001-bc960d80-2913-11eb-899e-70252f3b89f6.jpg)
We are having trouble parsing your context
Error: NotFoundError"

**Comment by AlexTugarev** [comment]
Hi @JustinHaase,
Welcome to Gitpod!

You might want to prefix URLs of repositories with `gitpod.io#` which will start a dev environment in that context.

Read more on context URLs: https://www.gitpod.io/docs/context-urls/

**Comment by akosyakov** [comment]
As Alex said, you should prefix the repository URL like gitpod.io/#https://github.com/theia-ide/theia not github.com
