### ISSUE TITLE
Is it possible to run minikube on Gitpod?

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#220]
Hi,

I just tried to start minikube  within Gitpod. I used a custom docker image with minikube installed.
When I tried to start minikube it failed to start and complained about not having the right permissions.
Is it currently possible to run minikube within Gitpod without having root access?

Kind regards,
Thomas

**Comment by meysholdt** [comment]
For Minikube I believe root access (https://github.com/gitpod-io/gitpod/issues/39) is needed. 

But there is [Usernetes](https://github.com/rootless-containers/usernetes) which promises to not need root access. I haven't found the time yet to try it.

**Comment by Sandared** [comment]
Thanks :) will have a look at it

**Comment by esigo** [comment]
Hi, I was wondering if there is any update on this.
Thanks

**Comment by utam0k** [comment]
@esigo cc @axonasif  I think this issue relates https://github.com/gitpod-io/gitpod/issues/4889. Please keep watching it.  Please let us know if this issue is resolved and still does not work. As far as I know, at least qemu can work around it, but it doesn't perform very well.
