### ISSUE TITLE
[theia] Extension Packs aren't installed properly

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#2202]
cf. https://community.gitpod.io/t/are-extension-packs-supported/2144/3

After the (rather quick) installation, there are not errors to see, but also no new features are contributed.

**Comment by jankeromnes** [comment]
I can confirm: Installing https://open-vsx.org/extension/donjayamanne/git-extension-pack in Gitpod seems to work successfully, but none of the pack's extensions actually seem installed.

**Comment by kuniss** [comment]
Could someone please reopen this issue? I guess, it would be an important issue to be solved for Gitpod and Theia, isn't it?
