### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by hansputera** [gitpod-io/gitpod#2204]
### Describe the bug
You've been blocked

### Steps to reproduce
Go to https://gitpod.io/workspaces/
Click delete workspace.

### Expected behavior
Workspace deleted

**Comment by AlexTugarev** [comment]
We are blocking users that don't apply to our [terms](https://www.gitpod.io/terms/). Usually this means you were running a miner, tried doing a DoS attack from a workspace or something similar. If you feel the blocking is not justified, please reach out to info@gitpod.io.
