### ISSUE TITLE
[theia] Browser Widget isn't loading examples 

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#2206]
for instance, the django example is failing to be shown in the preview browser to the side:

<img width="2032" alt="Screen Shot 2020-11-18 at 16 20 19" src="https://user-images.githubusercontent.com/914497/99551712-7779e600-29bc-11eb-988a-22b85e36b895.png">

and in the `referer-policy` for the relevant resources seems to be different in comparison to PROD.

<img width="1741" alt="Screen Shot 2020-11-18 at 16 23 54" src="https://user-images.githubusercontent.com/914497/99551700-747ef580-29bc-11eb-951e-926f769a97f5.png">

**Comment by geropl** [comment]
> The X-Frame-Options is sent to sameorigin. That header should be filtered by the proxy but is not.

1. We deploy `staging` - and in the near future `prod` - with `ws-proxy`. In this case `nginx` forwards workspace-specific traffic via [these lines](https://github.com/gitpod-io/gitpod/blob/master/chart/config/proxy/lib.workspace-port-locations.conf#L9-L22) (not the ones linked above). If we wanted to (re-)add the filter it's worth thinking about whether w want to add it to `ws-proxy` instead. If that's helpful we have to think through all deployment scenarios.

2. I don't recall atm, but there were multiple factors that would allow/deny access `iframe`s. I'm not 100% sure that `X-Frame-Options` is the reason in this case: @AlexTugarev can you check whether the header is actually sent (scrolling down in the first screenshot?)

**Comment by svenefftinge** [comment]
Yes, the `X-Frame-Options` header is the reason. And since we filtered it out in the past (in prod) we will break some use cases. Some dev servers send this header by default because they want to be "secure by default". I think we should keep filtering that.
