### ISSUE TITLE
"You've been blocked. Please file an issue if you think this is a bug."

### ISSUE THREAD

**Issue by Knucklehead-McSpazatron** [gitpod-io/gitpod#2209]
I don't know what this is about, can you please fix it?

**Comment by AlexTugarev** [comment]
We are blocking users that don't apply to our [terms](https://www.gitpod.io/terms/). Usually this means you were running a miner, tried doing a DoS attack from a workspace or something similar. If you feel the blocking is not justified, please reach out to info@gitpod.io.

**Comment by Knucklehead-McSpazatron** [comment]
> We are blocking users that don't apply to our [terms](https://www.gitpod.io/terms/). Usually this means you were running a miner, tried doing a DoS attack from a workspace or something similar. If you feel the blocking is not justified, please reach out to [info@gitpod.io](mailto:info@gitpod.io).

I did none of those things.
