### ISSUE TITLE
Signing in errors

### ISSUE THREAD

**Issue by joshma** [gitpod-io/gitpod#2213]
### Describe the bug
I can't sign in

### Steps to reproduce
1. Visit https://gitpod.io/#https://github.com/gitpod-io/spring-petclinic
2. Click "Login with GitHub & Launch Workspace"
3. I see "Starting..." followed by a redirect to https://gitpod.io/sorry/#Authorization%20failed.%20Please%20try%20again.

![image](https://user-images.githubusercontent.com/64739/99603616-865e9980-29b8-11eb-9476-4245b0966656.png)

### Expected behavior
Expected: can sign in and use the product

### Additional information
I don't know if it's something specific to my GitHub account, but maybe there's some permission I accidentally rejected? I don't know of anything strange about my account, though.

### Example repository
https://github.com/gitpod-io/spring-petclinic

**Comment by gtsiolis** [comment]
Hi @joshma! I cannot reproduce this. If you've already signed up you probably authorized Gitpod as an OAuth app. You could try removing this app from [GitHub > Settings > Applications > Authorized OAuth Apps ](https://github.com/settings/applications) and try again.

Let me know if you are still running into this issue afterwards. 🏀

**Comment by joshma** [comment]
That fixed it! Thanks. :)
