### ISSUE TITLE
GitPods for Workshops (time limiting or invites)

### ISSUE THREAD

**Issue by jaxxstorm** [gitpod-io/gitpod#2214]
This may already be a feature, but checking in just in case it's not.

I want to run GitPod in an AWS account and allow users to sign up via a URL for a time-limited workshop. They'll have access to create workspaces for ~3 hours, and then after that, registration is closed.

I considered trying to do this via oauth and invite codes, but I don't think that's possible.

Are there features available like this?

**Comment by wulfthimm** [comment]
Gitpod is using basic oauth to allow access. Restrictions have to be made by the oauth provider.

**Comment by jankeromnes** [comment]
Hi @jaxxstorm!

Limiting user access to 3 hours isn't currently a feature in Gitpod. I think you could manually block users from the admin dashboard when they no longer should have access to your service, or automate this process somehow in your installation.

Another option could be sending an email to contact@gitpod.io to ask about a support contract.

**Comment by meysholdt** [comment]
hi @jaxxstorm! Closing this because your question has been answered. Feel free to open if I'm missing someting.
