### ISSUE TITLE
F5 reloads website and not starts debugging

### ISSUE THREAD

**Issue by pinguin999** [gitpod-io/gitpod#2216]
### Describe the bug
F5 is the hotkey for start debugging in VS IDEs and it's reload in browsers.
It would be nice to overwirte the F5 browser hotkey with start debugging.

### Steps to reproduce
Open any gitpod project and press F5 to start debugging and the page reloads and kicks you out of your workflow.

### Expected behavior
After pressing F5 the debugger shoud start.

**Comment by gtsiolis** [comment]
Thanks for bringing this up @pinguin999! This is something to consider for sure.

Refreshing (CMD+R) or closing (CMD+W) the tab could probably let users confirm this action when using the IDE.

**Comment by akosyakov** [comment]
I cannot reproduce it in latest Chrome. Which browser did you use?

You can change keybindings in the meantime:
<img width="667" alt="Screenshot 2020-11-20 at 09 39 10" src="https://user-images.githubusercontent.com/3082655/99778824-7f4c9e00-2b14-11eb-961f-da99b72d34d6.png">
<img width="683" alt="Screenshot 2020-11-20 at 09 39 35" src="https://user-images.githubusercontent.com/3082655/99778828-81aef800-2b14-11eb-8383-497932c2da78.png">

**Comment by pinguin999** [comment]
OK it's works for me now too. 
No Idea what's was the problem the first time.
