### ISSUE TITLE
Code does not use the gp credential-helper

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2218]
![image](https://user-images.githubusercontent.com/3210701/99647890-ab9fe600-2a52-11eb-80bf-0b2330e398b5.png)

which is why one has to login manually

**Comment by akosyakov** [comment]
The simple pass was merged here: https://github.com/gitpod-io/gitpod/pull/2320

The next step will be to generalize token validation.

**Comment by akosyakov** [comment]
I will close this one and open a specific issues for token validations.
