### ISSUE TITLE
Blocked

### ISSUE THREAD

**Issue by Knucklehead-McSpazatron** [gitpod-io/gitpod#2220]
I have been blocked, I have not broken any of the terms, and I have emailed info@gitpod.io and nobody responds.

**Comment by gtsiolis** [comment]
Hey there! I've just unblocked your account.

Please keep in mind that the terms also include excessive network use (e.g. scraping, batch-downloading, etc).

See **I. Fair and Acceptable Use; Indemnification** in the [Terms](https://www.gitpod.io/terms/) page.

Thanks for reaching out!

**Comment by Knucklehead-McSpazatron** [comment]
> Hey there! I've just unblocked your account.
> 
> Please keep in mind that the terms also include excessive network use (e.g. scraping, batch-downloading, etc).
> 
> See **I. Fair and Acceptable Use; Indemnification** in the [Terms](https://www.gitpod.io/terms/) page.
> 
> Thanks for reaching out!

Thank you!
