### ISSUE TITLE
[prebuilds] Logs are empty

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2223]
Starting a workspace on the current master will result in a workspace without the logs (left terminal).
I checked the files under /workspace/.gitpod/ and they are empty (besides the banana)

**Comment by akosyakov** [comment]
Could you check against this PR please: https://github.com/gitpod-io/gitpod/pull/2205?

**Comment by csweichel** [comment]
Also maybe related: https://github.com/gitpod-io/gitpod/issues/2253

**Comment by akosyakov** [comment]
resolved in https://github.com/gitpod-io/gitpod/pull/2205
