### ISSUE TITLE
Offline or Websockets are blocked

### ISSUE THREAD

**Issue by dslovin** [gitpod-io/gitpod#2239]
I tried the self hosted installer script for GCP, and recieve the following error.

![Screenshot 2020-04-08 at 1 16 18 PM](https://user-images.githubusercontent.com/2700620/78813869-b01ffe80-799b-11ea-92c1-ea9b0b536964.png)

Everything looks right otherwise, thoughts? Not sure which logs to look at. There is no firewall between us. I have tried on firefox and chrome on multiple OS's. Have tried by going to hostname and IP (hostname is an A record pointing to the IP).

gitpod.io seems to work fine.

**Comment by edson-sooraj** [comment]
Can somebody explain in detail how to solve this error?

**Comment by axonasif** [comment]
Hi @edson-sooraj, which browser are you using?
