### ISSUE TITLE
Editor defaults to dos (\r\n) line endings for new files

### ISSUE THREAD

**Issue by sherbang** [gitpod-io/gitpod#224]
New files are created with `<CR><LF>` dos-style line endings, and there's no obvious way to change them.

**To Reproduce**

* Right-click on a folder, click "new file".
* Name the file test.sh.
* File contents:
```
#!/bin/bash

echo hi
```
* `chmod +x test.sh`
* `./test.sh`
Result: `bash: ./test.sh: /bin/bash^M: bad interpreter: No such file or directory`

**Comment by lvnp** [comment]
Can confirm
- Create new file that contains >1 lines
- `file newfile.txt`
Result: `newfile.txt: ASCII text, with CRLF line terminators`
