### ISSUE TITLE
minio fails to template on go 1.14+

### ISSUE THREAD

**Issue by MGlolenstine** [gitpod-io/gitpod#2246]
There is a problem where the gitpod uses minio package, which has redundant parentheses which cause the template to fail upon trying to install.

<details>
<summary>`helm upgrade --install ...` command output</summary>

```
# helm upgrade --install $(for i in $(cat configuration.txt); do echo -e "-f $i"; done) gitpod .
Release "gitpod" does not exist. Installing it now.
Error: template: gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml:192:20: executing "gitpod-selfhosted/charts/gitpod/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
```
</details>

<details>
<summary>`helm version` output with the go version</summary>

```
# helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.14.4"}
```
</details>

It might be worth noting, that I'm running everything on AARCH64 architecture on a Raspberry Pi 3B+, even though the architecture shouldn't be the cause.

### EDIT:
The problem is with the minio, as the problem has been [reported](https://github.com/helm/charts/issues/21446) with `Helm` as well.

**Comment by corneliusludmann** [comment]
Duplicate: #1740
