### ISSUE TITLE
[ws-manager] logs fatal "cannot start workspace monitor"

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2249]
In staging ws-manager logs "cannot start workspace monitor" on start.

**Comment by csweichel** [comment]
I cannot find the occasion where that happened [in the logs](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22gitpod-staging%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22staging--gitpod-io--eu-west1--02%22%0Aresource.labels.namespace_name%3D%22default%22%0Alabels.k8s-pod%2Fapp%3D%22gitpod%22%0Alabels.k8s-pod%2Fcomponent%3D%22ws-manager%22%0Alabels.k8s-pod%2Fkind%3D%22pod%22%0Alabels.k8s-pod%2Fstage%3D%22staging%22%0A%22cannot%20start%20workspace%20monitor%22;timeRange=P7D;summaryFields=:true:32:beginning?authuser=1&project=gitpod-staging).
Do you have a link?

**Comment by svenefftinge** [comment]
I cannot find it myself anymore. I must have been looking into another gcp project.
