### ISSUE TITLE
It would be more user friendly if add  the "Search" button in the Theia

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#225]
It would be more user friendly if add  the "Search" button in the Theia
For instance (in this place): 

![searchbutton](https://user-images.githubusercontent.com/41964662/50401821-1fb7ad80-079a-11e9-8015-a00b46a69b23.png)

**Comment by svenefftinge** [comment]
We want to align the UI with VS Code because it will help reusing all the existing familiarity. So we are having a search icon on the left panel soon.
