### ISSUE TITLE
User is not authenticated. Please login. Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by Blackniku** [gitpod-io/gitpod#2250]
### Example repository

User is not authenticated. Please login.
Please file an issue if you think this is a bug.

**Comment by svenefftinge** [comment]
Please share more information about what you did and what you expected.

**Comment by jankeromnes** [comment]
Hi @Blackniku! I guess you were trying to access a Gitpod workspace URL directly when you saw this error.

Gitpod will automatically log you out if you don't visit a page like https://gitpod.io/workspaces/, https://gitpod.io/settings/, https://gitpod.io/subscription/, https://gitpod.io/access-control/, etc within 3 days.

However, visiting any of these pages regularly will automatically refresh your authentication cookie (feel free to do that now, this will fix your problem).

Note that visiting bookmarked workspace URLs directly will _not_ refresh your authentication cookie, which may lead to the error above.

Please let us know if the problem persists.
