### ISSUE TITLE
An empty option is listed in the accounts dropdown options

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2255]
### Describe the bug

A empty (_Loading..._) option is listed in the accounts dropdown options.

### Steps to reproduce

1. Enable _Feature Preview_ in _Settings_ and then select _Code_ editor.
1. Open a new workspace.
1. Click the accounts icon on the bottom left corner.

<img width="348" alt="Screenshot 2020-11-23 at 10 10 29 AM" src="https://user-images.githubusercontent.com/120486/99940477-e2d50680-2d74-11eb-9d32-ae3dcf30942a.png">

**Comment by akosyakov** [comment]
It will be fixed in the scope of https://github.com/gitpod-io/gitpod/issues/2340
