### ISSUE TITLE
[prebuild] Running prebuild on repo without task makes it hang

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2265]
Try: https://gitpod-staging.com/#prebuild/https://github.com/jankeromnes/hugo-gitpod and see how the process hangs.

The `.gitpod.yml` doesn't have an init so prebuild should be a no-op.

**Comment by csweichel** [comment]
@akosyakov just discussed this bit for #2205 :D 

will be fixed in that PR
