### ISSUE TITLE
It would be more user friendly if the "Stop"  button  becomes unavailable after clicking  it

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#227]
It would be more user friendly if the "Stop"  button  becomes unavailable after clicking  it. 

![stopbutton](https://user-images.githubusercontent.com/41964662/50440009-dd5ab180-08fc-11e9-9156-fcad979e1657.png)

**Comment by AlexTugarev** [comment]
resolved ✔️
