### ISSUE TITLE
Make Gitpod button in Gitlab open in new tab

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#2272]
When I open Gitpod to do some work, I usually want to go back to Gitlab when I'm done, to manage PR's, watch pipeline output, etc. But, Gitpod opens in the current tab. Can we make the Gitpod button in GItlab open in a new tab?

Another alternative would be to have a "go back to gitlab" button in the Gitpod UI, but that seems clunkier...

**Comment by jgallucci32** [comment]
+1 for this. The Chrome extension for GitHub does this so it would be good for the GitLab extension to have the same behavior.

**Comment by gtsiolis** [comment]
Hey @Michaelhobo! You are probably referring to the native Gitpod button found in the GitLab interface, right? If yes, there's an open issue to track this in https://gitlab.com/gitlab-org/gitlab/-/issues/247946 as this is currently a limitation of the component used for the dropdown button in GitLab.

> The multi-action button component currently doesn't support target="blank".

For more context, see comment in https://gitlab.com/gitlab-org/gitlab/-/merge_requests/37985#note_398380858. /cc @souldzin @corneliusludmann 

> Another alternative would be ...

It's not quite visible but the status bar on the editor already includes a link to the repository on the bottom left corner. 👀 

| Status bar (example) |
|-|
| ![status-bar](https://user-images.githubusercontent.com/120486/100201696-04ff8d80-2f09-11eb-80ac-d9abfb11b425.png) |

FWIW, the browser extension already opens Gitpod in a new tab for both GitHub and GitLab if you _don't_ have the [Gitpod integration](https://docs.gitlab.com/ee/integration/gitpod.html) enabled in your GitLab [profile preferences](https://gitlab.com/-/profile/preferences). /cc @jgallucci32 🙌 

Closing this but feel free to reopen if this describes a different issue! 🏀

**Comment by Michaelhobo** [comment]
Ah, you're right. I guess I can disable the gitlab-gitpod integration for now. Thanks!

**Comment by gtsiolis** [comment]
Anytime @Michaelhobo! Alternatively, you can leave the integration _enabled_ and remember to hold CMD or Control key before clicking the dropdown option, just like you would do to open _any_ link in a new tab which is a common browser shortcut.

**Comment by jgallucci32** [comment]
...or middle-click :)
