### ISSUE TITLE
Eager caching of custom docker images

### ISSUE THREAD

**Issue by randomir** [gitpod-io/gitpod#2273]
### Describe the bug
When using an in-repo Dockerfile, the image is rebuilt (on workspace start) _only when Dockerfile itself has changed_, but not if some of the data files copied (with `ADD`/`COPY`) changed.

### Steps to reproduce
1. In your repo, create a Dockerfile that uses `COPY` to include a file `x` in the image.
2. Create a workspace, see how the image is built.
3. Modify the file `x`.
4. Create a workspace, see how the image is **not built**.
5. Check the contents of file `x` and see how the new version is not included.

### Expected behavior
A behavior consistent with [Docker caching](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache), see points about `ADD` and `COPY` commands. Also, in [`COPY` docs](https://docs.docker.com/engine/reference/builder/#copy) see a note at the end.

**Comment by AlexTugarev** [comment]
Hi @randomir,

as a pragmatic workaround, we got used to tamper the Dockerfile by increasing a version number like this...
```
ENV TRIGGER_REBUILD 2
```

**Comment by randomir** [comment]
@AlexTugarev, thanks, I've been using a similar "cache buster":
```
LABEL version=2
```
