### ISSUE TITLE
[dashboard] invalid URI in start page

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#2274]
There is a new error happening in the start page sometimes:
<img width="1904" alt="Screenshot 2020-11-24 at 14 27 36" src="https://user-images.githubusercontent.com/3082655/100188253-2309c580-2eea-11eb-840b-859c9832f966.png">

This component now also has a reference to `Workspace` twice which are not updated in sync:
- https://github.com/gitpod-io/gitpod/blob/master/components/dashboard/src/components/start-workspace.tsx#L57
- https://github.com/gitpod-io/gitpod/blob/master/components/dashboard/src/components/start-workspace.tsx#L27

**Comment by svenefftinge** [comment]
This would solve it https://github.com/gitpod-io/gitpod/pull/2282
