### ISSUE TITLE
[dashboard] Stopped workspace page shows scrollbars when workspace as dirty

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2278]
### Describe the bug
![image](https://user-images.githubusercontent.com/3210701/100217405-b4416200-2f13-11eb-9849-b23f40a1f5a5.png)

When a workspace is stopped with uncommited changes we now show the list of those changes on the stopped page.
The list of changes we show always has a scrollbar, which looks unfinished.

### Steps to reproduce
1. Start a workspace
2. run `touch xx`
3. stop the workspace

**Comment by svenefftinge** [comment]
That is intentional. We want to provide the context information, but since it can be large I opted for a scrollable div.
Any alternative design ideas? (cc @gtsiolis )

**Comment by csweichel** [comment]
scrollable makes total sense to me. I'm not sure the scrollbars have to be visible all the time though (`auto` instead of `on).

**Comment by gtsiolis** [comment]
This has been resolved in the new dashboard and will be available in this release.
