### ISSUE TITLE
tasks/ports updates should not be dropped

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#2290]
Right now some updates can be dropped while the client is subscribing. It is not very problematic for ports, but for tasks it can lead to a situation when a user never see a running terminal.

**Comment by svenefftinge** [comment]
I just restarted a previously stopped workspace (this repo) and the terminal on the right didn't initialize. There was not even a label in the tab of the view. Is it related, or a different issue?

<img width="591" alt="Screenshot 2020-11-26 at 11 53 18" src="https://user-images.githubusercontent.com/372735/100342333-21b9c500-2fde-11eb-85ec-07744645bd0b.png">
