### ISSUE TITLE
Workspace removed after 14 days. Can I recover the code from it?

### ISSUE THREAD

**Issue by KCarlton96** [gitpod-io/gitpod#2294]
I used a workspace for an assignment but did not know/realize that none of the changes were pushed to the main repo and now need to recover the code. Is this possible? 

The workspace was also part of the free trial for private github repos.

**Comment by jankeromnes** [comment]
Hi @KCarlton96, yes, there is a grace period where we can still restore a garbage-collected workspace for you.

Please email support@gitpod.io with the workspace ID if you have it, or repository & approximate time when you created or worked on it.

**Comment by KCarlton96** [comment]
Thank you, will do!
