### ISSUE TITLE
[staging]: preview does not work and shows 504 Gateway Timeout

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2297]
### Describe the bug

Yesterday(~~Tomorrow~~) while working on the gitpod-website repo I encountered this twice that the preview results in the following:

![image](https://user-images.githubusercontent.com/46004116/100353243-0cf62500-3010-11eb-9c73-b50212cafae3.png)

When the first time it happend reloading the preview worked as expected but when the seconed time it happend I didn't work at all even after reloading for several times. 

### Steps to reproduce

It happend randomly on reloading the preview when the change was not automatically reflected.

The workspace ID is: `f596cf3d-6905-4fb3-8d71-64f1326e099a`

**Comment by akosyakov** [comment]
> Tomorrow...

😄

**Comment by nisarhassan12** [comment]
Whoops my bad I meant Yesterday from Tomorrow :smile:

**Comment by nisarhassan12** [comment]
Just saw it again today reloading for the first time made it work.

**Comment by geropl** [comment]
Maybe that's gone with the new deployment including https://github.com/gitpod-io/gitpod/pull/2305

Worth a re-test once we have staging updated! :+1:

**Comment by svenefftinge** [comment]
The PR is in staging now. Please re-test.

**Comment by nisarhassan12** [comment]
I will post here If a saw this issue again.

**Comment by nisarhassan12** [comment]
Just saw it for a workspace on staging the workspace ID is `ef39b2a1-4e58-45ad-8b46-21b920382344` also reloading does not makes it work: 
![image](https://user-images.githubusercontent.com/46004116/100598272-52706600-3320-11eb-89f2-95d62f36f3e8.png)

**Comment by svenefftinge** [comment]
Yes, I can also reproduce it. Thanks.

**Comment by nisarhassan12** [comment]
Encountered this just now on production.

![image](https://user-images.githubusercontent.com/46004116/102690583-3e859900-4228-11eb-95b2-7e867ab87eac.png)
