### ISSUE TITLE
error while create new user account

### ISSUE THREAD

**Issue by braghome** [gitpod-io/gitpod#230]
**Description**
I am getting an error when creating a new user account 

**To Reproduce**
1. click login and allow authorize from github.com
2. create a new account
3. see the error message

**Expected behaviour**
I should be able to create a new user account without error

**Comment by 32leaves** [comment]
Hi @braghome, it looks like your account was created after all - when you are on https://gitpod.io/workspaces, are you able to login and use the system?

**Comment by braghome** [comment]
yes I see the account was created after all despite the error
