### ISSUE TITLE
Remove theme inheritance from the editor

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2303]
### Problem

The dashboard theme is currently inherited from the most recently selected theme in Theia editor. 🤯 
1. This makes it quite _undiscoverable_ and _surprizing_ to the user as they _always_ start with a dark theme when they sign up and they suddenly see another theme when they get back to the dashboard if they've changed the theme in Theia editor.
1. However, this is not the case when using Code editor, as the dashboard theme doesn't take into account the selected theme in Code editor, which can create more confusion. 😵 
1. Also, it can lead to significant accessibility issues for anyone trying to use a light theme in Theia editor as they eventually run into inaccessible pages like the following where navigation or other page elements are almost hidden, affecting product usability:

| Loading Workspace |
|-|
| ![image](https://user-images.githubusercontent.com/120486/100360783-14163680-3002-11eb-820e-6d93bd53f9ec.png) |

| Dashboard |
|-|
| ![image](https://user-images.githubusercontent.com/120486/100360789-15dffa00-3002-11eb-971b-7bd77b9d7392.png) |

### Proposal

1. Remove any theme inheritance from the Theia editor.
2. Use the color palette from the default light theme in Theia editor for the dashboard.

### Benefits

This can improve the overall user experience of the product by having a cohesive, consistent, and recognizable product experience.

### Out of scope

The editors (Theia, Code) can continue allowing color theme selection as well as persist the most recently selected option for each user.

### Future steps

In the future we can consider introducing a dark theme and a user preference to switch between light and dark theme or even follow the system default which is a common practice. 🔮

**Comment by akosyakov** [comment]
I like this proposal from implementation perspective. It is generally will be hard to align theme when we support different IDEs and we use hacky approach to share a theme like reusing cookie between origins which then unnecessary sent to the server.

**Comment by svenefftinge** [comment]
I think we should just have light and dark theme in the dashboard and for the IDE we could use the editor's default dark and light theme depending on what the user runs as long they haven't changed to a custom theme.

**Comment by gtsiolis** [comment]
This has been resolved in the new dashboard and will be available in this release.
