### ISSUE TITLE
Replace RLS with Rust analyzer as default extension

### ISSUE THREAD

**Issue by Maan2003** [gitpod-io/gitpod#2308]
Even though RLS is the official extension, Rust analyzer provides a way better experience. It will be better to make it default. Also, looks like there is no way to disable built-in extensions

**Comment by geropl** [comment]
We tried that ~6 months ago, there it was blocked by https://github.com/eclipse-theia/theia/issues/7608. 
I'm unsure if we have the appropriate Theia version in Gitpod that includes the fix...

But we also plan to role out VS Code in Gitpod during the next weeks, where `rust-analyzer` should "just work" (TM) - stay tuned!

**Comment by Maan2003** [comment]
I got rust analyzer working by using an older version of extension, but newer version of rust analyzer server

**Comment by Maan2003** [comment]
but RLS is also running, so double completions are annoying

**Comment by statictype** [comment]
Just curious what is the status of this. I've tried Gitpod last week and enabling the Rust Analyzer extension crashes the language server. Older versions of the extension crash as well. The oldest RA extension i found supports VSCode 1.44.1, but Gitpod uses 1.44.0 as far as this error message tells me:

`Activating extension 'rust-analyzer' failed: The language client requires VS Code version ^1.53.0 but received version 1.44.0`

Is there a chance you will update VSCode any time soon?
