### ISSUE TITLE
[messagebus] Configuration races with startup, leading to missing exchanges and thus broken deployments

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#2309]
### Describe the bug
During deployment `messagebus` is started, and we try to setup exchanges automatically via script. Every now and then this script succeeds but somehow silently fails to setup the expected exchanges. There are some components relying on those being present which fail then, rendering the Gitpod installation completely broken.

### Steps to reproduce
Try to install Gitpod via helm a few times.
When `ws-manager-bridge` crashloops, look into it's logs and find it mention a missing exchange.

### Expected behavior
See all components up and running 

### Additional information
-

### Example repository
-

**Comment by ArthurSens** [comment]
Not sure if possible, but logging if we can somehow identify this race failure would be nice as well :slightly_smiling_face:

**Comment by ArthurSens** [comment]
I mean, logging while we don't have a fix for the race failure

**Comment by csweichel** [comment]
This is an issue indeed, and a rather annoying one when it happens. From my experience (without having any data to prove it) it doesn't happen all that often.

**Comment by meysholdt** [comment]
we just saw that in prod and fixed it by restating message bus. Can we increase the prio of resolving this?

**Comment by MrPeacockGmail** [comment]
hi,

i'm getting this error too. I can confirm restarting messagebus fixes ws-manager-brigde to come up and running.

As i'm getting this error everytime i restart my litte K3D cluster. Is there anything i can do to help in fixing this issue?

**Comment by geropl** [comment]
> Is there anything i can do to help in fixing this issue?

Thx for offering your help! Actually it's all about the script you discovered: `/usr/local/bin/configure.sh`, specifically [these lines](https://github.com/gitpod-io/gitpod/blob/b7dda84ad0c0dd195b829b7f4160f9f7acfa355c/components/gitpod-messagebus/configure.sh#L7-L9). We need to find anything in rabbitmq that let us wait until it's up and ready to receive api requests.

Ideally, there would be a way in rabbitmq to ship it with configuration that replace the API calls, but I think that's not supported.

**Comment by aledbf** [comment]
@geropl can we close this issue?

**Comment by geropl** [comment]
@aledbf Definitely. Thank you very much for fixing this! :pray:
