### ISSUE TITLE
Show the accumulated hours in the current subscription even for Professional Open Source plan

### ISSUE THREAD

**Issue by tnir** [gitpod-io/gitpod#2329]
Currently [/usage](https://gitpod.io/usage/) does not show the accumulated hours in the current subscription for Professional Open Source plan users. Can you show the accumulated hours to those who are in POS plan just for reference?

To workaround this, I had to have a tiny snippet as follow:

- https://www.youtube.com/watch?v=j8WHfkSDq8s&t=7
- https://gitlab.com/-/snippets/2044478

**Comment by svenefftinge** [comment]
Sure we can. Out of curiosity: why are you interested in that number?

**Comment by tnir** [comment]
Because

1. I want to opt-out [Professional Open Source plan](https://www.gitpod.io/docs/professional-open-source/) if I use only 50 hours or less a month.
1. it would be helpful (on transition from open source use to company use) to inspect how many hours I will use for private or team project if I used to use.

**Comment by tnir** [comment]
https://gitpod.io/usage was completely deprecated/removed from the dashboard with the rise of #3727.

**Comment by gtsiolis** [comment]
Thanks for closing this @tnir! We'll get the _Usage_ page back with more improvements in the upcoming milestones, see https://github.com/gitpod-io/gitpod/issues/3360.
