### ISSUE TITLE
Issue with JS prompt, confirm, and alert in Terminal

### ISSUE THREAD

**Issue by chrisYoder** [gitpod-io/gitpod#233]
Description:

When trying to use prompt, confirm, or alert and running the Javascript file in the terminal I am getting a ReferenceError. In essence, somehow the Window methods mentioned above are treated as variables that haven't been declared. However, when I execute index.html through the preview window that is feature in GitPod it works.

**To Reproduce**
Write a Javascript that includes any or all of the methods and execute it via the terminal command "node filename.js"

**Expected behavior**
Expected either a popup window or terminal equivalent.

**Comment by svenefftinge** [comment]
We figured out on freshchat that the javascript code was executed using node.js, which doesn't support dialogs as it is UI less
