### ISSUE TITLE
support git hosting providers auth with Code editor

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2340]
### Problem to solve 

The Code editor has not been integrated with GitHub yet.

Although IDE selection can only be enabled via the Feature Preview, this can also lead to confusion as the Code editor prompts for authorization when trying to push a branch to a GitHub repository but always fails.

See also [relevant discussion](https://typefox.slack.com/archives/CGVQAPNPL/p1606738143294300) (internal).

| Step 1 | Step 2 | Step 3 | Step 4 |
|-|-|-|-|
| ![image](https://user-images.githubusercontent.com/120486/100609618-f8b76e00-3316-11eb-86b8-b6e3a849323c.png) | ![image](https://user-images.githubusercontent.com/120486/100609624-fb19c800-3316-11eb-9185-705813c1cfde.png) | ![image](https://user-images.githubusercontent.com/120486/100609627-fc4af500-3316-11eb-8b91-dfef055ab50d.png) | ![image](https://user-images.githubusercontent.com/120486/100609633-fce38b80-3316-11eb-89a2-4e88bb7acbff.png) |

**Comment by akosyakov** [comment]
We should remove github authentication extension from MS and provide our implementation of authentication provider instead which uses  `GitpodServer.getToken` API for different kind of providers, i.e. github, gitlab, bitbucket.
