### ISSUE TITLE
emmet lags behind and works slow

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2353]
Oftentimes in Gitpod, I find emmet to work slow or sort of lag behind as compared to that of VS Code locally i.e see both of the below gifs .I have encountered this many times while working with Gitpod that I type a dot and then some class name then hit tab I lose the class name and it doesn't get added between the quotes whereas on VSCode I never saw this happening.

sometimes what happens is that Let say I create a section with a class named features to do that I type `section.fea` slowly and then fastly `tures`  It creates a section with class `fea` and not the whole word.

### Emmet in Gitpod

![image](https://user-images.githubusercontent.com/46004116/100725187-8cf00680-33e5-11eb-87b6-20c66b64970c.png)

### Emmet in Local VS Code

![image](https://user-images.githubusercontent.com/46004116/100725209-937e7e00-33e5-11eb-97cb-3fbba28bb383.png)

**Comment by akosyakov** [comment]
I would like to investigate whether we can run the emmet extension in a web worker instead for Gitpod Code.
