### ISSUE TITLE
Cannot access my workspace

### ISSUE THREAD

**Issue by Mr-Smyth** [gitpod-io/gitpod#2355]
### Describe the bug
My Project will not open up - even after 10 mins of loading page

### Steps to reproduce
I have repeated this three times - without success

**Comment by jankeromnes** [comment]
Hi @Mr-Smyth,

Sorry about this issue. Could you please provide a screenshot of what your workspace is doing? (I.e. to see which loading phase it gets stuck in.) This would help investigate potential problems.
