### ISSUE TITLE
[staging] workspace content was never ready

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2359]
Starting a workspace failed with 
```
last backup failed: workspace content was never ready. Please contact support if you need the workspace data.
Please file an issue if you think this is a bug.
```

the [logs](https://cloudlogging.app.goo.gl/PPxRPiQFBdw2iq267) say :

"failed to create containerd task: failed to mount rootfs component &{overlay overlay [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1390/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1390/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1003/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1002/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1001/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1000/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/999/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/998/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/997/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/996/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/995/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/994/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/993/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/992/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/991/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/809/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/808/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/807/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/806/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/805/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/804/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/803/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/802/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/801/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/800/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/799/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/798/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/797/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/796/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/795/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/794/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/793/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/792/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/791/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/790/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/789/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/788/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/787/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/786/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/785/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/784/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/783/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/782/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/781/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/780/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/779/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/778/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/777/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/776/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/775/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/774/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/773/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/772/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/771/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/770/fs]}: failed to mountat: failed to find pid=2396775 process: no child processes: unknown"

**Comment by svenefftinge** [comment]
the trace: https://eu.jaeger.gitpod-staging.com/trace/f7d1ede89b298470

**Comment by csweichel** [comment]
This looks to be an instance of https://github.com/containerd/containerd/issues/4009
