### ISSUE TITLE
Can't open Gitpod on my repo: Error: network timeout at: https://api.github.com/repos/.../commits?sha=...&path=...

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#237]
**Describe the bug**

> Error: network timeout at: https://api.github.com/repos/jankeromnes/chromium/commits?sha=a27729cdf1291e13edce220c3dcc3d4594c404d1&path=Dockerfile

**To Reproduce**

Try to open https://gitpod.io/#https://github.com/jankeromnes/chromium

**Expected behavior**

The GitHub API should not time out and Gitpod should start building the Dockerfile.

Potentially interesting details:
- The repository is quite large (~16GB checkout)
- It is forked from an official GitHub mirror. Using Gitpod with an earlier commit worked, but it doesn't seem to work on my new commit (that tries to configure Gitpod)

**Comment by AlexTugarev** [comment]
For some reasons the GH API server cannot handle this commit. It’s responding with code 500. Increasing http timeout has no effect.

Not sure how to handle it, but it looks like a bug we want to report to GH. I tried with a smaller repo, and similar requests use to work.

Also, we can improve the error message here.

**Comment by jankeromnes** [comment]
I investigated this, and it seems that Gitpod requests the list of commits for a given path in order to remember the last commit SHA that changed the file, for caching reasons. (So omitting the path parameter wouldn't help here.)

However, for that particular API call, GitHub is pending for a while, and then throws an Error 500 (I suspect because it gave up after an internal timeout, because it's a very large repository). In order to work around that, we could host the Dockerfile (and .gitpod.yml file) in an external repository that isn't so large, e.g. https://github.com/gitpod-io/definitely-gp/.
