### ISSUE TITLE
Logs are no longer GCP compliant

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2370]
The format that our Go components log in no longer matches the format GCP/StackDriver expects.
We should re-align them, especially summary and severity.

**Comment by ArthurSens** [comment]
Just for the record, severity was addressed by #2396. I'm taking a look at the rest now

**Comment by ArthurSens** [comment]
Hi @csweichel :wave:

I can't find anything about "subject" on [GCP LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) docs, nor at `components/common-go/log/log.go`. Am I looking at the wrong places :thinking:? Could you provide some extra details about what exactly does "subject" refer to :slightly_smiling_face:?

**Comment by csweichel** [comment]
> Hi @csweichel 👋
> 
> I can't find anything about "subject" on [GCP LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) docs, nor at `components/common-go/log/log.go`. Am I looking at the wrong places 🤔? Could you provide some extra details about what exactly does "subject" refer to 🙂?

That was my bad. I meant `summary`, rather than `subject`. I.e. the actual log message. That was addressed by #2396 as well.
