### ISSUE TITLE
Cannot open new workspaces for GitLab repositories

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2371]
### Describe the bug

We're currently using a [deprecated dependency](https://www.npmjs.com/package/gitlab) for interacting with GitLab.

https://github.com/gitpod-io/gitpod/blob/ace0b59bb472c22bbcc1135267bdb882e78d6153/components/server/package.json#L52

<img width="1192" alt="Screenshot 2020-12-02 at 1 20 17 PM" src="https://user-images.githubusercontent.com/120486/100866335-2fb98b00-34a1-11eb-86bb-61645ca15ca0.png">

This is causing an error when opening a new workspace for a GitLab repository:

```
We are having trouble parsing your context
Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

This seems to affect also self-hosted instances, see https://community.gitpod.io/t/cannot-create-workspace-anymore/2224.

### Steps to reproduce

Try opening a new workspace for a GitLab repository.

For example, try opening https://gitpod.io/#https://gitlab.com/gitlab-org/gitlab.

**Comment by yababer** [comment]
We are having the same issue.  Do we have an ETA on when a fix will be ready?

**Comment by m-malz** [comment]
We also have the same issuse. Gitpod as Service

**Comment by yababer** [comment]
We found a workaround.  If you use the Chrome extension and pull a merge request (not a branch) from gitlab, it seems to work.  

For example:  https://gitlab.com/{repo}/-/merge_requests/8

We are not sure if this works for github or other use cases.

**Comment by gtsiolis** [comment]
**UPDATE**: The fix has been deployed on staging and the plan is to deploy this on production (`gitpod.io`) within the next 12 hours. 🔥

**Comment by svenefftinge** [comment]
For the time being there is a workaround https://github.com/gitpod-io/gitpod/issues/2382#issuecomment-738082051

**Comment by svenefftinge** [comment]
The fix has been deployed.

**Comment by jgallucci32** [comment]
Is there a PR which links to this issue in the master branch for the self-hosted code?

**Comment by corneliusludmann** [comment]
@jgallucci32: It's this PR that fixes this issue: https://github.com/gitpod-io/gitpod/pull/2375
