### ISSUE TITLE
support for x86/x64 assembly

### ISSUE THREAD

**Issue by uber6** [gitpod-io/gitpod#238]
Please add support for x86/x64 assembly language

**Comment by JesterOrNot** [comment]
So to be clear this would entail creating a docker image based on gitpod/workspace-full right?

**Comment by jankeromnes** [comment]
@uber6 would you know which CLI tools or dependencies should be installed to work on x86/x64 assembly language?

Also, there even seems to exist a VS Code extension that could work to support this language: https://github.com/13xforever/x86_64-assembly-vscode

**Comment by JesterOrNot** [comment]
here is a repo https://github.com/JesterOrNot/Gitpod-Assembly
