### ISSUE TITLE
Gitlab import repo does not work

### ISSUE THREAD

**Issue by ajm339** [gitpod-io/gitpod#2382]
### Describe the bug

I simply followed the directions found here: https://www.gitpod.io/docs/getting-started/

The code is hosted on a group but I am the owner of the group. I tried with a repo that is not in a Group and it also broke.
### Steps to reproduce

Use Chrome Extension or URL prepend to import Gitlab repo.

### Expected behavior

Your app importing the repo

### Additional information

![image](https://user-images.githubusercontent.com/4138881/100943262-eed66c00-34ca-11eb-8eba-41992589ebf4.png)

I am authenticated with Gitlab so not sure why this isn't working.

### Example repository

https://gitlab.com/mywrkouts/youtube-dl and https://gitlab.com/mywrkouts-code/myworkouts.io

**Comment by Zhomart** [comment]
We are having trouble parsing your context
Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined

*for SEO*

**Comment by yababer** [comment]
We found a workaround.  If you use the Chrome extension and pull a merge request (not a branch) from gitlab, it seems to work.  

For example:  https://gitlab.com/{repo}/-/merge_requests/8

We are not sure if this works for github or other use cases.

**Comment by svenefftinge** [comment]
closing this as it is tracked here: https://github.com/gitpod-io/gitpod/issues/2371
