### ISSUE TITLE
[code] cannot install extensions

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2386]
I can no longer install extensions.
```
Unable to open 'Extension: Go': Channel name 'request' timed out after 1000ms.
```

**Comment by svenefftinge** [comment]
> (index):1 Access to XMLHttpRequest at 'https://storage.googleapis.com/open-vsx-resources/golang/Go/0.19.0/package.json' (redirected from 'https://open-vsx.org/vscode/asset/golang/Go/0.19.0/Microsoft.VisualStudio.Code.Manifest') from origin 'https://ebe20f95-d2f1-4037-ae60-b8b922ee3e47.ws-eu02.gitpod-staging.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/2389

**Comment by spoenemann** [comment]
The problem seems to be that Code is using XMLHttpRequest:
https://github.com/microsoft/vscode/blob/175730751395dbb5526c89413ea7d29df74cdf3e/src/vs/base/parts/request/browser/request.ts

It would work if they'd use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) instead.
