### ISSUE TITLE
Theia don't start, upon start crashes with: We are having trouble parsing your context Error: Cannot read property 'Symbol(Symbol.iterator)' of undefined Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by mjobuda** [gitpod-io/gitpod#2392]
### Describe the bug
eclipse theia don't start

### Steps to reproduce
fork https://gitlab.com/owsikowski/gdates
start gitpod

### Expected behavior
eclipse theia should appear

**Comment by mjobuda** [comment]
seems that for some reason this happens with all my projects!!

**Comment by svenefftinge** [comment]
Hey @mjobuda,
we have fixed it already and can hopefully deploy in a few hours.

duplicate of https://github.com/gitpod-io/gitpod/issues/2382

**Comment by svenefftinge** [comment]
For the time being there is a workaround https://github.com/gitpod-io/gitpod/issues/2382#issuecomment-738082051
