### ISSUE TITLE
terminals getting closed by code for some repos

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#2394]
I can reproduce it by opening io repo. Sven was able to reproduce it for freecodecamp repo.

**Comment by svenefftinge** [comment]
Another thing that seems slightly related is that after reloading the browser on an opened gitpod-io/gitpod ws, the terminals are empty.

**Comment by svenefftinge** [comment]
Reloading helped. So it seems some sort of timing issue. can no longer reproduce with additional reloads.
