### ISSUE TITLE
[code] Show credit alerts in IDE

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2397]
When I run low on hours I should get notified.
```
root ERROR Notification handler 'onCreditAlert' failed with message: this.target[e] is undefined logger-protocol.ts:112:15
    log logger-protocol.ts:112
    get progress-bar.ts:23
    getLog logger.ts:312
    log logger.ts:304
```

**Comment by akosyakov** [comment]
It does not work in Code either. We were discussing to expose notification from an IDE to the supervisor for such notifications.

**Comment by svenefftinge** [comment]
Let's concentrate on showing this through the dashboard.
