### ISSUE TITLE
[admin] Users are falsely shown to have unlimited plan

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2398]
When I opened a user it shows `unlimited`.
Only after I click "account statement" it gets correctly updated.

**Comment by svenefftinge** [comment]
seen in staging

**Comment by ChristinFrohne** [comment]
I've just seen this issue in production. 
Before opening the "account statement" the user profile said `unlimited open-source`.
After opening and closing the "account statement" it says `100 Hours remaining` (note: shouldn't it be 50h?)
