### ISSUE TITLE
[review] Edit pending comment: latest version should be opened

### ISSUE THREAD

**Issue by marcdumais-work** [gitpod-io/gitpod#24]
**Describe the bug**
When editing a pending review comment, the original version of the comment is opened for edition, instead of the latest version.

**To Reproduce**
Add a pending review comment, click on "Update comment"
Edit comment, click on "Update comment"
 -> new version of comment displayed
Edit comment again
 -> original, not latest version of comment, is opened for edition

**Expected behavior**
When editing a pending comment, the latest version should be opened for edition

![peek 2018-08-28 08-09](https://user-images.githubusercontent.com/25749063/44722216-63bfcd80-aa9a-11e8-855c-4f8df57a9921.gif)

**Comment by akosyakov** [comment]
We are switching to VS Code and https://www.gitpod.io/docs/feature-preview/#default-ide for PR reviews on gitpod.io In order to enable VS Code follow https://github.com/microsoft/vscode-pull-request-github
