### ISSUE TITLE
Haskell Support

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#240]
We should add a Haskell extension until native support for VS Code extensions is ready.

Haskell vscode extension: https://github.com/alanz/vscode-hie-server 
Haskell language server: https://github.com/alanz/haskell-lsp

**Comment by JesterOrNot** [comment]
I can start looking into a dockerfile if this is something you are still interested in.

**Comment by JesterOrNot** [comment]
here is the link https://github.com/JesterOrNot/Gitpod-Haskell

**Comment by JesterOrNot** [comment]
Any feedback on my repo?

**Comment by GarnicaJR** [comment]
Thanks JesterOrNot, i will test your repo and will share my feedback once my test is done :)

**Comment by GarnicaJR** [comment]
Hey JesterOrNot, I were testing your repo and it looks good but the only problem i found is ghci terminal sometimes is a bit slow, i dont know if it is a  gitpod issue :/.

BTW thanks Sir.

**Comment by JesterOrNot** [comment]
I'll look into it
