### ISSUE TITLE
Not able to install AWS Toolkit extension

### ISSUE THREAD

**Issue by nickbonic** [gitpod-io/gitpod#2400]
I'm not not able to install AWS Toolkit extension.
I Click the "install" button but it doesn't work.

Thanks in advance

**Comment by gtsiolis** [comment]
Hi @nickbonic! Just added https://github.com/gitpod-io/gitpod/issues/2402, closing this one. 📘 

This will be fixed after the deployment which will take place within the next 12 hours.
