### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2402]
### Describe the bug

Currently, installing extensions is not possible, returning the following error on the console:

```js
root ERROR Request downloadExtension failed with message: The server responded with status 302.
```

This will probably be fixed after the redeployment on production, see https://github.com/gitpod-io/gitpod/issues/2371#issuecomment-738101870. 🚨 

See also [relevant discussion](https://typefox.slack.com/archives/CQJLAF3SR/p1606928415036700) (internal). /cc @jankeromnes @spoenemann

**Comment by svenefftinge** [comment]
this is fixed now.
