### ISSUE TITLE
Project templates are not visible for users not authorized with GitHub

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2409]
### Problem

For example, if you create a user and authorize _only_ with GitLab and create one or more workspaces based on GitLab repositories, the search input becomes visible. However, when you search there and there's no workspace match, a GitHub authorized user would see all the project templates available to start a workspace from. This is not the case for GitLab-only authorized accounts.

**Comment by svenefftinge** [comment]
This is on purpose, because the templates are pointing to GitHub projects.

**Comment by gtsiolis** [comment]
Re-opening this for the following use case affecting user onboarding:

Also, when signing up through GitLab (for example), this issue a) leads users to an empty dashboard page and b) provides no action for the user other than a link to the docs.

**question**: Although, this part of the dashboard will probably become better in the near future, could we simply mirror or manually push all project templates to all git providers to resolve this? Does this sound like a good idea? /cc @csweichel @svenefftinge 

FWIW:
1. We do have a profile on all git providers[[1](https://github.com/gitpod-io/)][[2](https://gitlab.com/gitpod/)][[3](https://bitbucket.org/gitpod/)] but could use a new one to host project templates if needed. /cc @jankeromnes because of the [relevant discussion](https://typefox.slack.com/archives/CHJGR9CJK/p1607436074133900) (internal)
1. GitLab already supports [repository mirroring](https://cloud.google.com/source-repositories/docs/mirroring-repositories). Alternatively we could use [Cloud Source Repositories](https://cloud.google.com/source-repositories/docs/mirroring-repositories) or a GitHub action (like [this](https://github.com/marketplace/actions/mirroring-repository)).

Being able to access project templates, regardless the git provider you've used during signup, will probably be relevant in the long run and affects both product and marketing (see https://github.com/gitpod-io/website/issues/913). What do you think?

**Comment by gtsiolis** [comment]
This is still an issue, reopening.

**Comment by gtsiolis** [comment]
Closing in favor of https://github.com/gitpod-io/gitpod/issues/3531.
