### ISSUE TITLE
[diff view] not present for a specific PR

### ISSUE THREAD

**Issue by marcdumais-work** [gitpod-io/gitpod#241]
**Describe the bug**
I opened this [PR](https://github.com/theia-ide/theia/pull/3980) in Gitpod and the workspace open did not have the PR "diff" view on the left panel, as I expected. Everything else looked good:
![image](https://user-images.githubusercontent.com/25749063/51182334-d1c72e80-189b-11e9-808a-7109b25d26d2.png)

The PR has mostly new files, but with a few modified ones. I opened another random PR in Gitpod and the diff view was present.

**Comment by akosyakov** [comment]
fyi: You can click on `1 commit` in the PR view to reveal the PR "diff" view.

**Comment by svenefftinge** [comment]
I see this more often, there are unfortunately no related errors in the debug console nor can I reproduce it reliably.

**Comment by akosyakov** [comment]
@marcdumais-work Did you open this PR for first time or you open it before and closed the diff view?
