### ISSUE TITLE
GitLab clone failure (timeout?) prevents workspace start without meaningful error message

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2412]
Sometimes (it seems under pressure) some workspaces don't start.
Error message in the initializer is 

<img width="1113" alt="Screenshot 2020-12-04 at 07 50 58" src="https://user-images.githubusercontent.com/372735/101131380-788a5480-3605-11eb-8e20-ac1487da4400.png">

The [logs for this](https://cloudlogging.app.goo.gl/NHDu54dSR5vQ1CUK9)

**Comment by svenefftinge** [comment]
I've found the corresponding error in the initializer.
```
"cannot initialize workspace:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.InitializeWorkspace
        /tmp/build/gitpod-core-components-ws-daemon--content-initializer.ff140c1bfd746b854a1dfedbb6e9929478c337be/_deps/components-content-service--lib/pkg/initializer/initializer.go:345
  - git initializer:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.(*GitInitializer).Run
        /tmp/build/gitpod-core-components-ws-daemon--content-initializer.ff140c1bfd746b854a1dfedbb6e9929478c337be/_deps/components-content-service--lib/pkg/initializer/git.go:68
  - git clone https://gitlab.com/gitlab-org/gitlab.git . failed (exit status 128): Cloning into '.'...
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
fatal: the remote end hung up unexpectedly
```

**Comment by svenefftinge** [comment]
Seems like GitLab didn't like multiple clones from the same URL? 
Would be great to have a more meaningful error message for the user, but let's see if this is actually a thing that happens in reality.

**Comment by gtsiolis** [comment]
This is a quite common issue with cloning from GitLab. [[1](https://gitlab.com/gitlab-org/gitlab/-/issues/3779)] [[2](https://gitlab.com/gitlab-org/gitlab/-/issues/282409)] [[3](https://gitlab.com/gitlab-org/gitlab/-/issues/24243)] [[4](https://gitlab.com/gitlab-org/gitlab/-/issues/29432)] [...]

I don't think this is a bug on our side but we could gracefully handle this on the backend, surface a more accurate error message, or even allow the user to retry starting a workspace.

**Comment by whitetigle** [comment]
I can't start my gitlab pods. So I guess this is related? 

![image](https://user-images.githubusercontent.com/883207/101153191-6370ee00-3624-11eb-8527-8195c1ada1d2.png)
![image](https://user-images.githubusercontent.com/883207/101153218-6c61bf80-3624-11eb-9f27-55300df98acd.png)

**Comment by svenefftinge** [comment]
@whitetigle it seems to be a different error. Does it happen regularly? If yes can you share more info, such as a repo link or something?

**Comment by whitetigle** [comment]
Hi! The problem disappeared. But last week it occured a few times. I will try to give more details it it happens again.
