### ISSUE TITLE
Trying out the service and it failed

### ISSUE THREAD

**Issue by leeroya** [gitpod-io/gitpod#2415]
### Describe the bug
opened: https://gitpod.io/#https://github.com/leeroya/skippy and it failed

### Steps to reproduce
MS Edge (Chrome) opened: https://gitpod.io/#https://github.com/leeroya/skippy

### Expected behavior
Suppose the app starts, I am new

**Comment by leeroya** [comment]
refreshed and it worked

**Comment by jankeromnes** [comment]
Probably related to an EU cluster incident currently being worked: https://status.gitpod.io/incidents/bc0e40be
