### ISSUE TITLE
Bitbucket integration is broken

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2420]
> The BitBucket integration suddenly stopped working. I can't do any pull or push requests, and I can't create new instances from my repositories either (Gitpod says that it's unauthorized or similar). I tried to revoke the connection in Bitbucket, and now there's no access from Gitpod whatsoever, and it doesn't suggest to re-authorize BitBucket.

**Comment by AlexTugarev** [comment]
I’ll look into this.

**Comment by corneliusludmann** [comment]
- I'm able to create a workspace for a Bitbucket repo
- I'm NOT able to push to the repo:
Via GUI:
![image](https://user-images.githubusercontent.com/24960040/101203136-87efb900-366a-11eb-85cc-2d04ce4e8046.png)
```
Via console:
$ git push --set-upstream origin test-branch
remote: Invalid username or password
fatal: Authentication failed for 'https://bitbucket.org/corneliusludmann/my-sample-repo.git/'
```

**Comment by AlexTugarev** [comment]
> I'm able to create a workspace for a Bitbucket repo

Doesn't work for me. I just connected to `Bitbucket.org` from /access-control and copied the OAuth2 token, which works fine with context parser tests, but doesn't work for context parser.

```
We are having trouble parsing your context
Error: Unauthorized
```

**Comment by AlexTugarev** [comment]
reopening, as it's not yet deployed.

**Comment by AlexTugarev** [comment]
<img width="608" alt="Screen Shot 2020-12-07 at 10 17 23" src="https://user-images.githubusercontent.com/914497/101332336-70d0e700-3875-11eb-8f5c-fa4c184d6e98.png">

just verified, the deployed update works 🎉 

thanks @geropl!
