### ISSUE TITLE
code-server command not found in the Code IDE

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#2421]
### Describe the bug

I assume the Code IDE is using `code-server`. However, the `code-server` command is not found on `$PATH`.

### Steps to reproduce

1. Set gitpod to use Code as the IDE.
2. Start a new workspace.
3. Run `which code-server`

### Expected behavior

The code-server command should be on the PATH so that uses can use it for various purposes (e.g., opening file from command-line).

**Comment by svenefftinge** [comment]
FWIW we are not using code-server but vscode. We haven't enabled the code cli yet, but of course that's planned.

**Comment by svenefftinge** [comment]
tracked here https://github.com/gitpod-io/gitpod/issues/2422
