### ISSUE TITLE
supervisor is polluting server with `openPort` requests

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2423]
When the server errors `openPort` supervisor gets a little annoying.
<img width="651" alt="Screenshot 2020-12-04 at 22 16 13" src="https://user-images.githubusercontent.com/372735/101215558-58e34280-367e-11eb-8194-56959abb54e1.png">

one of them: https://console.cloud.google.com/logs/query;pinnedLogId=2020-12-04T11:10:19.556Z%2Ffjogjmg7wc5x72;query=e4dfc8ba-80ce-48a9-a3b4-367a36788628%0Aresource.type%3D%22k8s_container%22%0A-jsonPayload.component%3D%22workspace%22;timeRange=PT10H?project=gitpod-191109

**Comment by akosyakov** [comment]
I think it is the same across all our components, if a method fails we don't swallow an error but log it. When we deployed the load balancer was misconfigured with disconnecting from the server each 30 seconds creating a lot of error logs generally. I am not sure that disabling error logging is a good idea.

**Comment by svenefftinge** [comment]
All those log are from the same workspace and in the same second. It is a call from supervisor to server which responds with an error and supervisor seems to be calling again and again.

**Comment by akosyakov** [comment]
> All those log are from the same workspace and in the same second. It is a call from supervisor to server which responds with an error and supervisor seems to be calling again and again.

Ok, then it is indeed either related to https://github.com/gitpod-io/gitpod/pull/2401 or workspace had many configured or served ports and supervisor will try to auto reveal them one after another

**Comment by akosyakov** [comment]
This workspace tried to expose a lot of different ports. It seems to be each reconnect (each 30s) from the supervisor to server was triggering new ports to be served inside the workspace.

One thing which we should is not try to send request again on disconnect but propagate to the client and let it to decide. Otherwise reconnect and client can trigger double expose of the same port which will explain why so many attempts for the same port. It still does not explain what is triggering new ports to be served.

**Comment by akosyakov** [comment]
Discussed with @csweichel:
- The cluster was too small for our needs on Friday and could not deal with control port requests, so supervisors were trying over and over to expose same ports.
- Chris is going to add prometheus metrics for ws manager API to implement configurable rate limiting later based on measurements.
- https://github.com/gitpod-io/gitpod/pull/2401 can only prevent excessive control ports requests by avoiding calling it for already auto exposed ports. I would also add a commit to this PR to process only latest ports' events.
