### ISSUE TITLE
Curious double startup message appears in the shell log on container startup, with rust and cargo errors

### ISSUE THREAD

**Issue by johndunderhill** [gitpod-io/gitpod#2424]
After the most recent update to Gitpod (thanks, @jankeromnes), I'm seeing a curious double startup message in the shell log on container startup.  There's a couple of errors after the first instance (not mine--I don't use rust in this container):

```
 HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
cat ./fixpath.sh >>/home/gitpod/.bashrc
} && {
yarn install
} && {
source ./fixpath.sh && yarn run dev
}
bash: rustc: command not found
bash: /etc/bash_completion.d/cargo: No such file or directory
gitpod /workspace/costvine-client-svelte $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> cat ./fixpath.sh >>/home/gitpod/.bashrc
> } && {
> yarn install
> } && {
> source ./fixpath.sh && yarn run dev
> }
```

After this startup continues normally.  My `.gitpod.yml` looks like this:

```
image:
  file: .gitpod.Dockerfile
tasks:
  - before: cat ./fixpath.sh >>/home/gitpod/.bashrc
    init: yarn install
    command: source ./fixpath.sh && yarn run dev
ports:
  - port: 5000
    onOpen: ignore
```

Anyone know what's causing this?

John

**Comment by akosyakov** [comment]
> bash: rustc: command not found
> bash: /etc/bash_completion.d/cargo: No such file or directory

It is from the workspace full image. But it was fixed there already: https://github.com/gitpod-io/workspace-images/pull/306
Most likely you need to trigger the image rebuild for your branch. You can do it by adding a new ENV variable to the image like:
```dockerfile
# Docker build does not rebuild an image when a base image is changed, increase this counter to trigger it.
ENV TRIGGER_REBUILD 3
```

**Comment by johndunderhill** [comment]
@svenefftinge Where?  In the Dockerfile?

**Comment by akosyakov** [comment]
@johndunderhill yes in the docker file, like here: https://github.com/eclipse-theia/theia/blob/2d422afdc74ec151b837fd42f00ffef10cf82c63/.gitpod.dockerfile#L3-L4

**Comment by johndunderhill** [comment]
@akosyakov Yes, that did it, although I'm still unclear about the number in that ENV statement (just a counter--start at 1 and increment to force a rebuild?)

**Comment by akosyakov** [comment]
@johndunderhill anything which is different from previous value

**Comment by ceefour** [comment]
Still happens in Jan 30, 2021 and I'm not using any custom image:

```
bash: rustc: command not found
bash: /etc/bash_completion.d/cargo: No such file or directory
```
