### ISSUE TITLE
[Prebuilds] Allow use of docker during prebuilds

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2428]
In order to use docker during a prebuild, we need to run `docker-up` which is a non terminating process. 
Would be good to come up with a simple solution instead of having everyone hacking this by manually stopping the docker service when done.

**Comment by svenefftinge** [comment]
We can generalize this to adding some sort of explicit shutdown hook, that tells gitpod the prebuild is finished.

**Comment by csweichel** [comment]
Alternatively, we could provide a "background" task type that gets run before everything else, and gets stopped just before the workspace shuts down (after a potential future teardown hook).

**Comment by weitzman** [comment]
Looks like #2654 may have made progress here but status is not clear to me.
