### ISSUE TITLE
Activating extension failed: Must use import to load ES Module

### ISSUE THREAD

**Issue by laike9m** [gitpod-io/gitpod#2435]
### Describe the bug
When my [extension](https://open-vsx.org/extension/laike9m/cyberbrain) is being activated, it reports the following error
```
Activating extension 'Cyberbrain' failed: Must use import to load ES Module:
 /tmp/vscode-extensions/laike9m.cyberbrain@0.1.0/extension/out/extension.js require()
 of ES modules is not supported. require()
 of /tmp/vscode-extensions/laike9m.cyberbrain@0.1.0/extension/out/extension.js from
 /theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js is an ES module
 file as it is a .js file whose nearest parent package.json contains
 "type": "module" which defines all .js files in that package scope as ES modules.

 Instead rename extension.js to end in .cjs, change the requiring code to use import(),
 or remove "type": "module" from /tmp/vscode-extensions/laike9m.cyberbrain@0.1.0/extension/package.json.
```
The same extension can work in VS Code without any problem, and it used to (around two weeks ago) work in Gitpod as well.

### Steps to reproduce
Visit
https://gitpod.io/#snapshot/91475a9d-4ccf-420a-b0ee-11db084ce689
and you'll see the error popup.

### Expected behavior
The extension can be activated successfully with no error.

### Example repository
Repository of my extension:
https://github.com/laike9m/Cyberbrain/tree/master/cyberbrain-vsc

**Comment by akosyakov** [comment]
It could be related to Node.js version which we are using to deploy Theia: https://github.com/manuelbieh/geolib/issues/208

**Comment by laike9m** [comment]
This looks like my issue, but I do need the `"type": "module"`. Any ideas?

**Comment by akosyakov** [comment]
Yes removing it will fix the issue. I think the following is happening:
- in 12.14.1 ES modules are experimental and not enabled by deafult, it is why it works in VS Code
- in 12.18.3 is already LTS and ES modules are not experimental anymore, so Node will try to respect `"type": "module"`. It is why it does not work for you in Gitpod, as soon as VS Code moves to newer Node.js your extension will have such problem there as well.

**Comment by akosyakov** [comment]
but it could be a good idea for us to downgrade Node.js to avoid such issues for extensions

**Comment by laike9m** [comment]
By downgrade you mean? My understanding is that the Node.js version is controlled by VS Code, so once it decide to upgrade my extension will break. Or is it?

**Comment by akosyakov** [comment]
> By downgrade you mean? My understanding is that the Node.js version is controlled by VS Code, so once it decide to upgrade my extension will break. Or is it?

Sorry for the confusion. I meant downgrading Node.js version in Gitpod that all VS Code extensions which working in VS Code now also work in Gitpod.

I think you just should remove `"type": "module"` now from package.json and deploy a new version.

**Comment by laike9m** [comment]
Got it. To me it seems to makes more sense to keep the Node version the same with VS Code to avoid such issue from happening. And when VS Code upgrades the Node version, I shall fix it, otherwise it's hard to fix it locally.

**Comment by laike9m** [comment]
Any thoughts?

**Comment by akosyakov** [comment]
PR is there: https://github.com/gitpod-io/gitpod/pull/2508 but I doubt we will deploy it this year, likely beginning next year.

**Comment by laike9m** [comment]
thanks

**Comment by akosyakov** [comment]
The fix was deployed.

**Comment by laike9m** [comment]
VS Code has changed the node version to 12.18.3

**Comment by akosyakov** [comment]
@laike9m thank you for a ping, I will bump i up this month: https://github.com/gitpod-io/gitpod/issues/3069#issuecomment-776556933
