### ISSUE TITLE
Cant see files in workspace

### ISSUE THREAD

**Issue by jimbobding** [gitpod-io/gitpod#2436]
Hi.
Not sure if this is a bug or something that I have pressed accidentally, but my gitpod workspace timed out and when I logged back in I can not see any of my files or code it just all blank. I can still run a port 800 and see the physical site that I have been working on. 
Has anybody else had this issue or anybody know of a fix for this?

**Comment by svenefftinge** [comment]
Maybe a bug. could you try pressing F1 and choose "Reset Workspace Layout"? I hope that fixes it.

**Comment by svenefftinge** [comment]
I think this is due to some layout restoring issues.

**Comment by svenefftinge** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/2193

**Comment by jimbobding** [comment]
It was a display issue I worked out by playing around with the display
settings

**Comment by huy-lv** [comment]
there is no option: Reset workspace layout

**Comment by axonasif** [comment]
cc @jeanp413

**Comment by jeanp413** [comment]
There's `View: Reset View Locations` command
