### ISSUE TITLE
rust-analyzer compatibility issue

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#2438]
### Describe the bug
Activating extension 'rust-analyzer' failed: The language client requires VS Code version ^1.51.0 but received version 1.44.0

### Steps to reproduce
Install latest https://github.com/rust-analyzer/rust-analyzer/releases

### Expected behavior
Works as expected

**Comment by akosyakov** [comment]
Please file in an upstream: https://github.com/theia-ide/theia

You could try to set `VSCODE_API_VERSION=1.51.0` in your docker image, but it is only a temporary hack if it works at all.

**Comment by gengjiawen** [comment]
Thanks, reported in https://github.com/eclipse-theia/theia/issues/8828.
