### ISSUE TITLE
Confirm telemetry setting reflects the setting state and disable by default

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2440]
### Problem

Currently, the telemetry setting seems to be enabled by default for the Code editor.

<img width="480" alt="23NqfR4D2p" src="https://user-images.githubusercontent.com/120486/101327333-37997680-3877-11eb-9668-b8ac399b5531.png">

This is probably not implemented on the backend, see [relevant discussion](https://typefox.slack.com/archives/CGVQAPNPL/p1607329595126200) (internal). /cc @akosyakov 

### Proposal

Make sure the setting reflects the setting state.

Maybe, also disable this by default.

**Comment by akosyakov** [comment]
We don't have any telemetry. This setting is just registered globally and leaking in our product. Should we remove it all together?
