### ISSUE TITLE
[ws-manager] heavily logs "unknown headless log type"

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2441]
https://cloudlogging.app.goo.gl/JYSKSAs58bN8ymADA

**Comment by akosyakov** [comment]
Relevant code: https://github.com/gitpod-io/gitpod/blob/b354264a0feb33283e29413b93931869f233d763/components/ws-manager/pkg/manager/headless.go#L91-L121

**Comment by svenefftinge** [comment]
Yes, and the Type is "".

**Comment by akosyakov** [comment]
Maybe `json.Unmarshal` allows empty `msgTaskLog` 🤷‍♂️ cc @csweichel

**Comment by csweichel** [comment]
`json.Unmarshal(msgTaskLog{})` is most certainly valid.
