### ISSUE TITLE
Workspace failed to Open

### ISSUE THREAD

**Issue by RogueAngelfire** [gitpod-io/gitpod#2443]
### Describe the bug

I have no Idea was working perfectly on Saturday

### Steps to reproduce

Cannot login to it to find out

### Expected behavior

I have been having commit issues but thought they are resolved
### Additional information

Cannot get into the terminal but did notice colors missing from css # areas
### Example repository

RogueAngelfire/the_horseshoue_inn_v1

**Comment by jankeromnes** [comment]
Hi @RogueAngelfire,

Please share a screenshot of the error you see when you are unable to open your workspace. That will help us identify what's wrong and help you regain access.

**Comment by svenefftinge** [comment]
please open a new issue with additional/more information if there is something we should do about this.
