### ISSUE TITLE
Help !!!! Problem to gitpod.io

### ISSUE THREAD

**Issue by andrey199222** [gitpod-io/gitpod#2445]
When trying to log on gitpod.io  it gives an error "failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/theia/supervisor\": stat /theia/supervisor: no such file or directory": unknown; last backup failed: workspace content was never ready. Please contact support if you need the workspace data.
Please file an issue if you think this is a bug.
### Steps to reproduce

I went to the site github.com,  opened my project and added it to the address bar https://githud.io/github.com/andrey199222/my_sites
![image](https://user-images.githubusercontent.com/34586158/101348766-e0a29a00-3894-11eb-9fb9-982815bf5987.png)

**Comment by svenefftinge** [comment]
Sorry, this was an issue with a redeployment we did this morning and has been fixed now.

**Comment by andrey199222** [comment]
thanks for you
