### ISSUE TITLE
High CPU Utilization of DB

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2452]
We recently see more spikes with CPU utilization. We should look at where those come from and take action.

**Comment by geropl** [comment]
There are two parts there:
 - SQL CPU has slowly but constantly risen over the last month; feels like we are missing a index or two on a growing table
 - The DB logs show that we see a lot of `UPDATE d_b_user_storage_resource SET userId='xyz', uri=` in [the logs](https://console.cloud.google.com/logs/viewer?project=gitpod-191109&minLogLevel=0&expandAll=false&customFacets&limitCustomFacetWidth=true&dateRangeStart=2020-12-08T09%3A16%3A20.965Z&dateRangeEnd=2020-12-08T10%3A16%3A20.965Z&interval=PT1H&resource=cloudsql_database&scrollTimestamp=2020-12-08T10%3A15%3A37.354954000Z&advancedFilter=resource.type%3D%22cloudsql_database%22%0A)

**Comment by akosyakov** [comment]
fixed by https://github.com/gitpod-io/gitpod/pull/2476?

**Comment by geropl** [comment]
Related: https://github.com/gitpod-io/gitpod/pull/2511
