### ISSUE TITLE
Uninstall Gitpod help

### ISSUE THREAD

**Issue by niteraven7** [gitpod-io/gitpod#2465]
Hi all, I installed Gitpod via this process:

https://github.com/gitpod-io/self-hosted

To an existing google cloud project (maybe a big mistake) that I was using for another purpose. I cannot afford the price of Gitpod and all the services and additional resources it uses. I cannot simply disable this project since I'm using it.

What all resources would I need to remove to decouple this from my project? I'll start the list...

- Kubernetes
- VM
- MySQL
- Static IPs?
- Private network?
- Load balancer?

Anything else that cost money?

Thanks for your help.

**Comment by niteraven7** [comment]
Also- is there any easy way to remove these? Guess it'll be manual unlike installing an App :-/

**Comment by csweichel** [comment]
The installer use terraform to create the infrastructure. You could use that to [destroy](https://www.terraform.io/docs/commands/destroy.html) what the installer set up.

**Comment by niteraven7** [comment]
Hi @csweichel, thanks for the response. I installed version 0.4 I believe. Looks like docker container is for 0.5?

Will that work?

**Comment by niteraven7** [comment]
Installer uses helm and a script called create-gcp-resources.go

**Comment by niteraven7** [comment]
I did this manually in order, Uninstalled:

x Kube cluster
  x vm
  x load balancing
  x disks
x ips
x vpc network
x bucket storage
x mysql database

Deleting the cluster first took care of most of it.
