### ISSUE TITLE
How can I get the Gitpod public URL programmatically

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#2466]
If I am running two different servers on my workspace, one on port 3000 (front-end) and the other on port 3001 (backend) how can I get the public URL of the backend programmatically?

I know that I can concatenate like this: `echo https://3001-${GITPOD_WORKSPACE_URL:8}`

That will work like 50% of the time because sometimes the public_url of the servers does not match the workspace URL.

**Comment by beyerph** [comment]
Simply use `gp url 3000` and `gp url 3001` in the Terminal

**Comment by gtsiolis** [comment]
Thanks @beyerph for jumping in here! 🙏 

Closing this, @alesanchezr feel free to reopen if needed or add any further questions in the in the [community forum](https://community.gitpod.io/). 💬
