### ISSUE TITLE
[image-builder] Support http(s) proxy during self-build and for the Gitpod layer

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2467]
When Gitpod is deployed behind a proxy, image-builder needs to make use of that proxy during its builds. This particularly affects the Gitpod layer and the self-build.

image-builder should provide settings that inject `http_proxy` and `https_proxy` in the gitpod layer build/self-build.
Specifically, we'd add a section to the image builder config that's similar to the dockerd config:
```
"proxies": {
    "httpProxy": "http://internal-proxy-XXXXX:80",
    "httpsProxy": "http://internal-proxy-XXXXX:80"
}
```

For more details and motivation see: https://community.gitpod.io/t/service-pod-fails-behind-proxy-apk-cant-add-files-off-image-builder/2263/8

**Comment by IantheFlyingHawaiian** [comment]
Could no_proxy be added too?
