### ISSUE TITLE
Trying to connect to self hosted gitlab, get Bad Request

### ISSUE THREAD

**Issue by lawrencetaur** [gitpod-io/gitpod#2468]
### Describe the bug
I'm trying to connect gitpod with a self hosted gitlab instance. 

### Steps to reproduce
I followed the steps as described here https://www.gitpod.io/docs/gitlab-integration/#oauth-application

### Expected behaviour
It should connect to my self-hosted gitlab, but when I click Connect it redirects to https://gitpod.io/sorry/#Bad%20request:%20missing%20parameters.

When I click connect, it briefly has the params in the url but quickly redirects to https://gitpod.io/sorry/#Bad%20request:%20missing%20parameters.

**Comment by AlexTugarev** [comment]
Hi @lawrencetaur! 

I'd love to help you with that. 'Just tried with our test installation of GitLab, so it should work in general.

We just found a bug in our cross-cluster configuration related to the Git Providers. This will be resolved with the upcoming deployment this week.

At the moment this works only if you try to connect from the same cluster as the Git Provider registration was made. If the load balancer is redirecting to another one, it will fail unfortunately. As impractical this is, I barely can call it a workaround 🤷🏻‍♂️

**Comment by AlexTugarev** [comment]
@lawrencetaur due to a race condition, there is a chance of having 2 Git Providers with the same host name, though not verified by connecting with neither of them. Could you please check if that's the case for you, and if so, try to remove both and create a single one, please.

**Comment by lawrencetaur** [comment]
Hi @AlexTugarev 

I deleted the existing provider which failed earlier, I noticed the secret wasn't saved, not sure if that is intentional. 

When I add a new provider with my gitlab domain just like earlier, it does gives the same error as mentioned above.

**Comment by AlexTugarev** [comment]
> ... the secret wasn't saved, not sure if that is intentional.

it's just not shown once it's saved on purpose. given that misunderstanding, we should improve the rendering to indicate that.

> it does gives the same error as mentioned above.

that's not good. thanks for the feedback, I'm on it.

**Comment by lawrencetaur** [comment]
Hi @AlexTugarev 

I tried one more time today and it worked. Thank you for the help. You can close this issue now.

**Comment by AlexTugarev** [comment]
@lawrencetaur that's great news!

> I tried one more time today and it worked.

can you tell me when you did re-try that exactly, please? the reason I'm asking is that we just recently deployed an update to production containing related bugfixes and improvements.

**Comment by lawrencetaur** [comment]
I tried it 5 minutes before I told you.
