### ISSUE TITLE
[tasks] Support VS Code task definitions

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#247]
Gitpod is amazing for discovering new projects, and also for reviewing/amending pull requests.

But in both situations, it may happen that you don't know the project's most useful workflows like running tests, linting the code, profiling the app... and you lose a lot of time sifting through various docs (especially if you're new to that project, but also if you haven't worked on it for a while).

Having a few useful project-specific scripts to run directly from the IDE or from the `gp` command-line would be amazing.

Project maintainers could configure them in their `.gitpod.yml`, for example:

```yaml
workflows:
  - command: make build
  - command: make test
```

(This could also be useful for projects that have non-standard ways of sending patches, e.g. Firefox with `arc patch` and `hg phabsend`; Chromium with `git cl upload`; Linux with sending patches by email...)

- Then these commands could then be exposed in the IDE, either in the `Terminal` top-menu under `Run Task...` (not very discoverable); or directly in a new top-menu just for that project (e.g. `Chromium` > `git cl upload`).
- They could also be exposed via the `gp` CLI in the terminal.

You can find [examples](https://github.com/JanitorTechnology/dockerfiles/search?utf8=%E2%9C%93&q=scripts&type=) of such useful project-specific scripts in Janitor's Dockerfiles repository.

**Comment by svenefftinge** [comment]
I think vs code tasks should be used for that.

**Comment by jankeromnes** [comment]
Good idea, VSCode Tasks seem to be already [well specified](https://code.visualstudio.com/docs/editor/tasks). It looks a bit more complicated to support, but hopefully it will also give us pre-configured Tasks for many existing projects.

Do VSCode's and Theia's "Tasks" concept match 100%?

**Comment by svenefftinge** [comment]
> Do VSCode's and Theia's "Tasks" concepts match 100%?

Not yet, but they have to eventually (i.e. soon).
