### ISSUE TITLE
Gitpod worskpace extensions search yields no results

### ISSUE THREAD

**Issue by bravoalpha79** [gitpod-io/gitpod#2471]
### Describe the bug
When I try to search for "CSS Language Features" (or anything else) in the Extensions tab, the search yields no results whatsoever.
![image (3)](https://user-images.githubusercontent.com/45522344/101622942-fdb3a600-3a17-11eb-90e7-a2a58f7f69c9.png)

As a result, I am unable to install any extensions into the workspace.

Oddly enough, when the same workspace is shared and viewed on another computer, the search results display normally:

![image (2)](https://user-images.githubusercontent.com/45522344/101623003-1754ed80-3a18-11eb-8aae-5a6daa6886f8.png)

Workspace:  https://f1abf907-ec9c-42a9-aee4-c500348cbc4a.ws-eu03.gitpod.io/#/workspace/newgitpod

Note: at least one other student has reported the same - unable to search for extensions (i.e. no results found) from his workspace

### Expected behavior
Search for extension displays results.

### Additional information
There are 150+ errors in the console, namely
![image](https://user-images.githubusercontent.com/45522344/101623299-8894a080-3a18-11eb-9c97-96f81101b358.png)

**Comment by csweichel** [comment]
[open-vsx.org moved to the Eclipse Foundation](https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management) this morning which broke the search for running workspaces.
Please stop and start your workspace - things should be normal afterwards.
