### ISSUE TITLE
Better surface which ports are currently active

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#248]
When you start a web server on a given port, you'll see a notification appear that either offers to Expose the port, or to open it in a Preview pane or Browser tab.

However, sometimes the notification gets dismissed too early (for example, if you reload the page, or sometimes when another port is also opened around the same time). And if you "lose" such a notification, it's not obvious how to find your running apps again.

Here are a few ideas (most of them are from @paulmelnikow -- many thanks!):

- [ ] We could re-surface the open port notifications when the window is reopened (except when the Preview is already open)
- [ ] Also, we probably shouldn't dismiss a port notification just because another port was opened (I think that's a bug)
- [x] We could show which ports are active somewhere in the menus, providing another way to open previews (EDIT: it's in the bottom status bar, although not very obvious)
- [ ] We could implement a `--all` option for `gp url` (see https://github.com/gitpod-io/gitpod/issues/246#issuecomment-455126524)

**Comment by svenefftinge** [comment]
> We could show which ports are active somewhere in the menus, providing another way to open previews

We show that in the status bar. clicking on the item will open the ports view with more information and commands. Doesn't seem to be obvious though if you have missed that.

**Comment by paulmelnikow** [comment]
> We show that in the status bar. clicking on the item will open the ports view with more information and commands. Doesn't seem to be obvious though if you have missed that.

Oh nice! I see that now, and I think even saw it before but did not realize it was clickable. Maybe the dot on the status bar could be rendered in green instead of white; that would make it seem more clickable. Also I'd suggest changing the label, both in the status bar and the View menu, from **Ports** to **Open Ports**.

A small thing, though if I missed it surely others will too!

**Comment by svenefftinge** [comment]
Just got that question again. I think it would be good to have the ports view added to the left panel.
Now, that we use VS Code like icons, people are very likely to check what the view does.

**Comment by AlexTugarev** [comment]
> I think it would be good to have the ports view added to the bottom panel.

That's already the case.

**Comment by AlexTugarev** [comment]
>  Also I'd suggest changing the label, both in the status bar and the View menu, from Ports to Open Ports.

✔️

**Comment by AlexTugarev** [comment]
This issue looks outdated.
