### ISSUE TITLE
[self-hosted] Terraform using unsupported GKE version as min_master_version

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#2481]
### Describe the bug

Following Gitpod Self-hosted "install on GCP script" guide, an error occurred when running the installer image. After confirming the `terraform apply`, it fails with the message:
```
Error: googleapi: Error 400: Master version "1.15.12-gke.9" is unsupported., badRequest
```

After changing the version to a supported one, e.g. `1.16.15-gke.4300` and running the installer again, it works as expected.

### Steps to reproduce

Follow https://www.gitpod.io/docs/self-hosted/latest/install/install-on-gcp-script/

### Expected behavior

The installer runs without errors and I have a GKE cluster with gitpod installed at my google project.

**Comment by ArthurSens** [comment]
@csweichel how do you folks choose gke versions in the past? Should we just pick the default one?

**Comment by meysholdt** [comment]
please just pick the default one

**Comment by ArthurSens** [comment]
Already fixed in master:

https://github.com/gitpod-io/gitpod/blob/db795cc509dc57b05dd9832c378dca1bee3e8069/install/gcp-full-terraform/modules/kubernetes/main.tf#L84

The container in [our guide](https://www.gitpod.io/docs/self-hosted/latest/install/install-on-gcp-script/) is somehow outdated:
```
docker run --rm -it \
    -v $PWD/gcloud:/root/.config/gcloud \
    -v $PWD/gpinstall:/workspace \
    eu.gcr.io/gitpod-io/self-hosted/installer:latest \
    gcp
```
