### ISSUE TITLE
[VS Code] VS Code always defaults to Light theme

### ISSUE THREAD

**Issue by sr229** [gitpod-io/gitpod#2497]
### Describe the bug
Theia by default in Gitpod's configuration is defaulted in dark mode. Visual Studio Code however in my instance does not, as it defaults to light theme almost immediately.

### Steps to reproduce
Reproducible by just creating any workspace in GitHub by selecting VS Code as your default editor.

Video Evidence provided [here](https://twitter.com/satominyaaa/status/1337070518587932672).

**Comment by akosyakov** [comment]
probably will be resolved by https://github.com/gitpod-io/gitpod/issues/2707

**Comment by sr229** [comment]
> probably will be resolved by #2707

is there a working staging build of this, would be neat to try it out before it goes live.

**Comment by akosyakov** [comment]
It happens only once for a user for very first workspace with #2707.
