### ISSUE TITLE
Constantly being thrown out workspace 

### ISSUE THREAD

**Issue by KrisK1978** [gitpod-io/gitpod#2498]
I have been constantly being thrown out from my workspace. It happens when I add new piece of code to my workspace and push them to GitHub. I often get this message. Please see below.

![Screen Shot 2020-12-10 at 16 59 44](https://user-images.githubusercontent.com/46022746/101804745-d6d59c80-3b09-11eb-96fb-fff50b5df0f9.png)

Also, when refreshing the website in browser after clearing cookies I get the following error 

![Screen Shot 2020-12-10 at 17 06 00](https://user-images.githubusercontent.com/46022746/101804942-113f3980-3b0a-11eb-91bf-e16b3d618b26.png)

I cannot complete my project as I am constantly asked to login and open my workspace again and again. Can this be investigated please? Thanks.

**Comment by sr229** [comment]
401 means Unauthorized. Looks like your OAuth tokens expired too early.

**Comment by AlexTugarev** [comment]
@KrisK1978 let me check if I can find any issue in the logs. 

Please, could you post some details on your browser and settings? Check if you have any restrictions in privacy settings, especially w.r.t. to cookies.

Also, it's very unlikely to be an issue with git tokens, but rather with the HTTP session.

**Comment by KrisK1978** [comment]
Hi Alex
Please see some screenshots. Thanks.
![Screen Shot 2020-12-11 at 11 08 25](https://user-images.githubusercontent.com/46022746/101896845-81e56500-3ba1-11eb-87e1-39a1d492bc78.png)
![Screen Shot 2020-12-11 at 11 09 24](https://user-images.githubusercontent.com/46022746/101896851-8447bf00-3ba1-11eb-9204-f86c67baa7ef.png)

**Comment by AlexTugarev** [comment]
@KrisK1978 I see that you get to repeat login quite frequently. That's not intentional for sure. 

> Also, when refreshing the website in browser after clearing cookies I get the following error

Clearing cookies means that you will logout effectively. Gitpod stores a cookie containing a session ID, which the browser will send on each request to the Gitpod server. Once cookies are cleared, you need to login again.

Can you please describe what exactly happens before you get to the point of clearing cookies and reloading the tab, etc.? 

> I have been constantly being thrown out from my workspace. It happens when I add new piece of code to my workspace and push them to GitHub. 

So you have the IDE opened and from there, you get redirected to the /sorry page, is that correct?

**Comment by KrisK1978** [comment]
Well when refreshing the page using cmd+4  after applying some changes in IDE, no changes are visible, so I used to clear cookies not being aware that it would log me out. Now it's more clear for me. Thanks.

**Comment by AlexTugarev** [comment]
Alright, I see. That explains, why there weren't any errors to find 🙏🏻 

But then, please tell me more about ...

> Well when refreshing the page using cmd+4 after applying some changes in IDE

**Comment by KrisK1978** [comment]
Thanks for your assistance in this matter.
