### ISSUE TITLE
[Firefox Extension] Move Button

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#25]
In the gitpod firefox extension, I would suggest putting the gitpod button on the left of the "Clone or download"
The reason being that the gitpod button appears a little bit after the page has started rendering

So it's likely that I'll want to click on "Clone or download" and accidentally click on "Gitpod" because it appeared a millisecond before I clicked

cc/ @simark

**Comment by gtsiolis** [comment]
Closing this, as it is no longer an issue. You can find further improvements related to the button in https://github.com/gitpod-io/gitpod/issues/2110.
