### ISSUE TITLE
Allow to create a new repository on GitHub

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#250]
In addition to the `Fork Repository`-command we should have one that creates a `New Repository`.

The command should ask for the org and then the name. 
It should create the new repository and reconfigure just like it does for the fork command.
The difference is the new repo is not a fork.

*Use Case*
One of the use cases I'd like to cover is to support creating new projects based on template repos.
We could create an almost empty starter-project, that already has the right docker image and .gitpod file as well as good Readme to start with. Such a project could either contain everything needed, or preinstall generators (e.g. yeoman).

When I create a workspace for such a project, I can use the 'new repo'-command to create a new repo and push my changes there.

When running the command on an existing .git project, we should ask the user whether previous git history should be kept.

**Comment by geropl** [comment]
With this it finally makes sense to gitpodify example repos! Until now one has to update remotes etc. by hand: far too tedious.
