### ISSUE TITLE
Unable to create new OAuth Connection to my Github account

### ISSUE THREAD

**Issue by yeongsheng-tan** [gitpod-io/gitpod#2502]
### Describe the bug

Tried to add Github Git provider from https://gitpod.io/settings/
### Steps to reproduce

Entered my Github created OAuth Client ID and Secret generated in Github and when submit on prompt to "Connect", I get error "Sorry, something went wrong 😓
Bad request: missing parameters."
### Expected behavior

Connection should succeed.

**Comment by svenefftinge** [comment]
Hey Tan, thanks for reporting. There was an issue that has been resolved now. Could you try again?

**Comment by svenefftinge** [comment]
duplicate #2468
