### ISSUE TITLE
Gitpod Parse error 

### ISSUE THREAD

**Issue by Valencia-08** [gitpod-io/gitpod#2517]
### Describe the bug
I am trying to open a repository in gitpod and the same error keeps coming up no matter which repository I use. 

### Steps to reproduce
I create a repository on GitHub and then paste it in the URL of gitpod and the same error comes up; We are having trouble parsing your context
Error: Couldn't parse context 'the URL of the repository is inputted here'

### Expected behaviour
I expected a workspace to be opened like usual 

### Additional information
E.g https://gitpod.io/#https://valencia-08.github.io/Bootstrap/

### Example repository
all of the ones in my account

**Comment by akosyakov** [comment]
> https://gitpod.io/#https://valencia-08.github.io/Bootstrap/

https://valencia-08.github.io/Bootstrap/ does not point to GIthHub repo.
