### ISSUE TITLE
[self-hosted] git config - missing user name

### ISSUE THREAD

**Issue by doschkinow** [gitpod-io/gitpod#2519]
### Describe the bug
Opening a github project in a workspace built from https://github.com/gitpod-io/workspace-images/tree/master/full shows insufficient git config (missing git user name) on a self-hosted gitpod deployment. 

### Expected behavior
This is the correct behaviour on gitpod.io (execution in a terminal)

$ git config --list
push.default=simple
alias.lg=log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
credential.helper=/usr/bin/gp credential-helper
user.name=doschkinow
user.email=peter.doschkinow@oracle.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/doschkinow/drawingboard-light.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
![correct-on-gitpod-io](https://user-images.githubusercontent.com/4286764/101939856-e0cccd80-3be5-11eb-834e-7be128171d7d.PNG)

This is the  output on self-hosted gitpod (Oracle OCI kubernetes engine) - *user.name and user.email are missing*:
$ git config --list
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/doschkinow/drawingboard-light.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
![bug-on-gitpod-self-hosted](https://user-images.githubusercontent.com/4286764/101939881-eb876280-3be5-11eb-8141-24361936043d.PNG)

**Comment by philjak** [comment]
``git config  credential.helper "/usr/bin/gp credential-helper"`` seems to help.

```
tasks:
  - before: git config credential.helper "/usr/bin/gp credential-helper"
    init: ...
```

**Comment by doschkinow** [comment]
this suggestion worked for me too, thanks! The question now is how to cover it in the official docs..
