### ISSUE TITLE
XDebug support in VSCode?

### ISSUE THREAD

**Issue by cjensenius** [gitpod-io/gitpod#2520]
I have been able to use xdebug with PHP7.2 without an issue and recently ran into some trouble launching xdebug. I wanted to rule out issues in my configuration so I've disabled VSCode and launched https://github.com/JesterOrNot/Gitpod-PHP-Debug in Theia and have been unable to launch xdebug in the default PHP7.4 configuration. Am I approaching this incorrectly?

**Comment by csweichel** [comment]
@JesterOrNot can you say something about this?

**Comment by cjensenius** [comment]
@csweichel I wanted to update that as of this morning XDebug is working properly in VSCode build:
`
Version: 1.49.0
Commit: 20ded0d97c41cb686098d14b9e1f0533177300d1
Date: 2020-12-17T09:27:27.064Z
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
`

**Comment by akosyakov** [comment]
@cjensenius Could you elaborate please what you are doing, what do you expect and what goes wrong?

Also we support VS Code now as a feature preview: https://www.gitpod.io/docs/feature-preview/#default-ide You may want to give it a go instead.

**Comment by cjensenius** [comment]
Certainly, as noted in the initial issue description, I had been using XDebug for some months without issue until the excellent experimental features change. At that time XDebug was no longer working in Theia or VSCode, and to rule out local configuration issues I used the boilerplate from https://github.com/JesterOrNot/Gitpod-PHP-Debug which was also broken. 
As of this morning when I retested (I have not tested for several days) XDebug appeared to be working properly.

**Comment by cjensenius** [comment]
@akosyakov Thanks for the tip about VSCode! I've been using it since the release on 12/7 and had some rocky initial impressions mostly due to extensions requiring reinstallation between sessions and extensions not persisting between multiple browsers, but overall I'm very happy with it especially with the fixes released yesterday! Theia was great too, so it's nice to have options!

**Comment by cjensenius** [comment]
This can more than likely be marked resolved now, as the original report is no longer valid?

**Comment by akosyakov** [comment]
@cjensenius yeah, it is still in the preview and there are some missing features yet, like user settings are not persisted across workspaces and restarts, but we are close to sort it all out in beginning next year.

**Comment by cjensenius** [comment]
You guys are doing great, keep it up!
