### ISSUE TITLE
Ability to register as a Codespaces Provider

### ISSUE THREAD

**Issue by sr229** [gitpod-io/gitpod#2524]
I think it would be pretty nice if we can register ourselves in the VS Code Codespaces provider as a custom provider since we support VS Code now. The main idea here is this would allow developers to be more flexible now that they have another provider to use other than GitHub.

**Comment by akosyakov** [comment]
Do you mean starting Gitpod workspace from Codespaces?

**Comment by jankeromnes** [comment]
Ah, or maybe you mean that the Gitpod GitHub App could register itself as another option under the repository's `Open ...` dropdown?

I seem to remember that GitHub wanted to make the API for that dropdown available for third-party apps. In that case, I totally agree that the Gitpod app should use that API & add itself to that dropdown menu. 💯

**Comment by sr229** [comment]
> Ah, or maybe you mean that the Gitpod GitHub App could register itself as another option under the repository's `Open ...` dropdown?
> 
> I seem to remember that GitHub wanted to make the API for that dropdown available for third-party apps. In that case, I totally agree that the Gitpod GitHub App should use that API & add itself to that dropdown menu. 💯

Yep! This was I was going for, though an optional route to additionally cover is talking with Microsoft on allowing Gitpod to be provider apart from GitHub Codespaces to allow locally installed VS Code to interact with Gitpod workspaces (if they're using VS Code as their default IDE).

**Comment by jankeromnes** [comment]
> Yep! This was I was going for

🙌

> to allow locally installed VS Code to interact with Gitpod workspaces (if they're using VS Code as their default IDE) in their extension.

Note that this is already in the pipes, and even already works today with a few workarounds:
- VS Code Remote allows programming remotely via an SSH connection
- You can start an SSH server inside a Gitpod workspace and expose it via Chisel ([see how](https://community.gitpod.io/t/how-to-ssh-into-gitpod-workspace/341))
- Connecting the two allows you to develop on Gitpod via your local VS Code 🎉

But we'll make this even more convenient soon as part of our "bring your own IDE to Gitpod" campaign (which already started by allowing you to switch between Theia and web-VSCode in Gitpod's settings, [see how](https://www.gitpod.io/docs/feature-preview/#default-ide), and will soon move on to first-class SSH access to workspaces, JetBrains support, etc).

**Comment by svenefftinge** [comment]
Closing this as there doesn't seem to be a possibility to integrate with GitHub like that.
