### ISSUE TITLE
Support storing secrets for 3rd party services

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#253]
A common use case with Gitpod is to connect to 3rd party services, such as Cloud Providers, Databases, Registries and Hosting Providers. This requires me (as a Gitpod user) to log into the 3rd party service. 

Currently, I need to login again vor every new launched workspace. This tedious and contra the spirit of creating a new workspace for each new task. 

It would be better to store the authentication secrets in my Gitpod profile and have it available in every (or selected) workspaces. 

Interesting tools that require authentication
* `kubectl`: k8s clusters and kubectl-context
* `now`: hosting by zeit.co
* `docker`: private docker registries
* netlify?
* `npm`, `yarn`: publish npm packages, access private registries
* `mvn`: publish artefacts, access private registries
* `gradle`: publish artefacts, access private registries

There is a variety of technical ways to pass login-info to cmd-applications. Most support some, but not all of the following:
* via config-files inside the user-home-directory
* via environment variable
* via cmd-argument
* via auth-helper, e.g. the (git credentials helper)[https://git-scm.com/docs/gitcredentials]

Most apps can do the initial authentication by themselves:
* `gcloud auth login`
* `now`

Security considerations:
* Workspace Snapshots: Currently, snapshots only capture the state of the `/workspace` directory. If, in the future, snapshots would also capture the state of the home directory, storing authentications files in the home directory creates the risk of exposing them.
* Workspace Sharing: In shared workspaces the files system and environment variables of running `bash` terminals are also shared. 
* A user may have secrets in his/her Gitpod account that should *not* be accessible from all workspaces the user accesses, as some workspaces may not be trustworthy.

**Comment by dalemccrory** [comment]
There is a new docker feature that may be helpful here. If this could be integrated into the launch process, it may be a good solution to passing secrets without storing them.

Details here:
http://blog.oddbit.com/2019/02/24/docker-build-learns-about-secr/

I am looking to pass AWS CLI secrets.

**Comment by svenefftinge** [comment]
Supported now. See https://www.gitpod.io/docs/47_Environment_Variables/
