### ISSUE TITLE
Now I see not my workspace in the list of workspaces

### ISSUE THREAD

**Issue by arswarog** [gitpod-io/gitpod#2539]
Now I see not my workspace in the list of workspaces

![Bug](https://i.ibb.co/GdMg4kK/2020-12-15-14-58.png)

In better quality https://ibb.co/tH2yTc7

 I've never run any java projects. I'm coding on TypeScript

**Comment by arswarog** [comment]
Thanks for quick answer and help with this problem! 

You are doing great service!

**Comment by jankeromnes** [comment]
Hey @arswarog! Many thanks for reporting this problem, and for helping us investigate this in our email conversation. 👍

We're still investigating this and looking for similar events that may have happened to other users.

**Comment by svenefftinge** [comment]
We've fixed the underlying issue.
