### ISSUE TITLE
Lombok breaks Java VS Code extension

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#2542]
### Describe the bug
The Lombock VS Code extension adds something to the User's Theia settings that will sends the VS Code Java extension into a crash-restart-loop on all repos that don't have the VS Code Lombock extension installed.

### Steps to reproduce
1. Open a Java Repo that has the Lombock Extension installed
2. Open a Java Repo that does not have the Lombock Extension installed.

### Expected behavior
no crashes. 

### Additional information
Except form broken user settings:
```
{
  ...
  "java.jdt.ls.vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -javaagent:\"/tmp/vscode-extensions/GabrielBB.vscode-lombok@0.9.9/extension//server/lombok.jar\"",
  ...
}
```

While it's possible to argue that this is a bug in Lombock, I'd prefer to have this issue open here in the Gitpod repo because people keep running into this and are kinda lost. 

### Possible Fix
Maybe the Lombock config should go to the workspace settings, not to the user's profile.

**Comment by svenefftinge** [comment]
Should definitely be fixed in Lombok https://github.com/GabrielBB/vscode-lombok/issues/49
