### ISSUE TITLE
Gitpod extremely slow to open workspaces ~10 minutes

### ISSUE THREAD

**Issue by lechien73** [gitpod-io/gitpod#2543]
### Describe the bug
When opening a workspace, Gitpod hangs on the "Acquiring Node...(1/3)" screen after the progress bar has gone all the way to the right.

It may also crash after approximately 10 minutes of waiting with the error:
```
cannot prepare for user namespaces: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /.workspace/daemon.sock: connect: connection refused"
```
### Steps to reproduce
Open an existing workspace. My area is Western Europe.

### Expected behavior
For the workspace to open!

### Additional information
Tested with workspace aa2c1450-bb18-471f-b37e-03151124b625. Multiple students are reporting the same issue.

**Comment by corneliusludmann** [comment]
Thank you very much for reporting this. We have some bad nodes in our cluster. We are currently investigating.

**Comment by corneliusludmann** [comment]
Should be fixed. Please let me know if you still have problems starting a workspace.
