### ISSUE TITLE
Cursor running behind while typing

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [gitpod-io/gitpod#2550]
### Describe the bug
Whenever I am typing, the cursor gets shifted to left on its own. 

### Steps to reproduce
Open any GitHub repo in Gitpod and start writing code. 

### Expected behavior
The cursor should not run left or right but keep in alignment with the latest typed character.

### Additional information
I am using Gitpod on Edge

### Example repository
I opened https://github.com/CircuitVerse/CircuitVerse on Gitpod

**Comment by corneliusludmann** [comment]
I don't know if I understand your issue correctly. Could you probably provide a short video/gif that demonstrates the behavior?

Is the cursor simply delayed? Then a slow internet connection to our servers could be the problem!?

**Comment by ShreyaPrasad1209** [comment]
[2020-12-16 17-29-26.zip](https://github.com/gitpod-io/gitpod/files/5702543/2020-12-16.17-29-26.zip)
Here's a screencast of the issue, it's zipped so you'll have to extract it. 
I'm sure Internet's not the reason because mine is 100 mbps.

**Comment by geropl** [comment]
> I am using Gitpod on Edge
Though latest Edge is based on Chromium we never tested that. Could you try Chrome(/-ium) or Firefox instead?

**Comment by ShreyaPrasad1209** [comment]
I treid on Chrome and it's happening there too

**Comment by akosyakov** [comment]
Which repo do you use? Do you have any special extensions or settings in it?

It would be interesting whether you can reproduce it with the vanilla Theia: https://github.com/eclipse-theia/theia/blob/master/doc/Developing.md#run-the-browser-example-with-gitpod If so then the issue should be filed there. 

btw you can also use VS Code now: https://www.gitpod.io/docs/feature-preview/#default-ide

**Comment by ShreyaPrasad1209** [comment]
@akosyakov I have mentioned the repository link above. No this repo does not require any special extensions. You can have a look at dependencies [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/SETUP.md).
I will have a look at vanilla Theia and let you know

**Comment by akosyakov** [comment]
Unfortunately I was not able to reproduce it. What browser, os? Did you try to use VS Code instead as described here: https://www.gitpod.io/docs/feature-preview/#default-ide ?

**Comment by ShreyaPrasad1209** [comment]
I tried reproducing with vanilla Theia and I'm stuck here for hours. I used VS code yet the issue persisted.

![image](https://user-images.githubusercontent.com/43600306/102686430-bb574980-420d-11eb-937f-b7e5c4649285.png)

On opening Theia in Gitpod it prompted me to open port 3000 and on doing that I got this

![image](https://user-images.githubusercontent.com/43600306/102686462-f8234080-420d-11eb-9d84-a6741e4b280a.png)

**Comment by sr229** [comment]
I am using Windows 10 Insider Pro on the Dev Branch using Stable Edge and can't replicate the issue. I also tried Dev and Canary to no avail. 

I'm not so sure if this is a Edge bug or our fault, but from what I can tell this could be in the system instead of us because I doubt the editor lagging behind input is our fault.

**Comment by ShreyaPrasad1209** [comment]
@sr229 what do you think can go wrong if the error is in the system? Maybe I could look into it? In the meanwhile, I will try running CircuitVerse repository on another device to confirm the source.

**Comment by ShreyaPrasad1209** [comment]
I am no longer facing this problem. Thank you everyone for helping with debugging this out. I am going to close this issue now.
