### ISSUE TITLE
can not login to gitpod?

### ISSUE THREAD

**Issue by davepeyton** [gitpod-io/gitpod#2560]

**Comment by corneliusludmann** [comment]
Could you tell us more about it? What happens when you try to login?

**Comment by AlexTugarev** [comment]
I'll try to find something in the logs...

**Comment by AlexTugarev** [comment]
@davepeyton, please share some details on what you've seen. 🙏🏻 

I could find a successful login in the logs, but nothing else which indicates issues on the backend.
