### ISSUE TITLE
Add installation troubleshooting section in the docs

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2563]
### Problem to solve

@corneliusludmann brought up the need to have a installation troubleshooting section in the docs so that we can reference and link to from the [community forum](http://community.gitpod.io/) or [issues](https://github.com/gitpod-io/gitpod/issues).

**What?** Having a single source of truth (SSOT) for **common installation problems** and steps to resolve the problem sounds really helpful. @corneliusludmann also brought up the idea of linking to the community forum for questions and the issue tracker for bugs. A similar approach is already in the works in https://github.com/gitpod-io/gitpod/pull/2549.

**Where?** Maybe we'll have to create separate troubleshooting pages for each one of the installation methods or aggregate all common problems in a single page.

See also [relevant discussion](https://typefox.slack.com/archives/C010DUELP4Y/p1608117468068600) (internal). /cc @corneliusludmann @jankeromnes @ArthurSens

**Comment by meysholdt** [comment]
A "Troubleshooting" subsections under https://www.gitpod.io/docs/self-hosted/latest/self-hosted/ sounds great to me. 
Let's start with a single page, we can aways split it up later in case we need that.

How other people do this:
https://docs.docker.com/docker-for-windows/troubleshoot/
https://docs.mattermost.com/developer/dev-setup-troubleshooting.html (for dev setup, not for installation, but I like to format)

**Comment by gtsiolis** [comment]
Still an issue.
