### ISSUE TITLE
NPM autocompletion is missing

### ISSUE THREAD

**Issue by titivermeesch** [gitpod-io/gitpod#2564]
### Describe the bug
When in a folder that includes a **package.json** file, autocompleting a script does not work. (npm run + pressing tab).

### Steps to reproduce
1. Setup a basic node project
2. Setup a script called myscript
3. Go into the folder where your package file is
4. Write `npm run m` and press tab

### Expected behavior
When pressing tab, commands like this should autocomplete but they don't

**Comment by csweichel** [comment]
Thanks for reporting this issue. This looks like something in [workspace-full](https://github.com/gitpod-io/workspace-images/issues).

You can also add npm autocomplete support to your workspace/project using your own [Dockerfile](https://www.gitpod.io/docs/config-docker/). If you feel that this should be included by default, please file an issue [here](https://github.com/gitpod-io/workspace-images/issues).
