### ISSUE TITLE
Searchbar has different behaviour

### ISSUE THREAD

**Issue by titivermeesch** [gitpod-io/gitpod#2565]
So I noticed that the searchbar has a different behaviour than what I'm used to, is this because VS Code has some differences, or is this an issue in the code editor or gitpot itself, I don't know.

These are the points that are different:
- I can't seem to search for files that start with . (so searching .git does not return .gitignore or .gitpod.yml)
- Entering line number in the file opener does not work, writing index.js:42 should open `index.js` on line 42
- Writing :10 should go to line 10 in current file when writing in the file opener
- Spaces in file search are handled weird

This picture shows how I get results
<img width="704" alt="Screenshot 2020-12-16 at 15 50 31" src="https://user-images.githubusercontent.com/12189066/102364140-6f5e9780-3fb6-11eb-9e91-272a25bc27bb.png">

This one shows the behaviour in Gitpod
<img width="845" alt="Screenshot 2020-12-16 at 15 51 08" src="https://user-images.githubusercontent.com/12189066/102364242-8604ee80-3fb6-11eb-8f8e-c24394e8e2b8.png">

**Comment by csweichel** [comment]
This looks like a discrepancy in UX between code and Theia. @akosyakov WDYT?

**Comment by corneliusludmann** [comment]
Hi @titivermeesch! 

Thanks for reaching out. At first, the default editor in Gitpod is [Theia](https://github.com/eclipse-theia/theia). I guess you're talking about this one and not the VSCode editor that you can try with [feature preview](https://www.gitpod.io/docs/feature-preview/) enabled, right?

That said, Theia is a bit different from VSCode. For some of you overservations are already issues in the Theia repo, eg:
- Whitespace: https://github.com/eclipse-theia/theia/issues/8747

**Comment by titivermeesch** [comment]
@corneliusludmann I was talking about Theia sorry, I did not know we could change editors. So one of these behaviours may be something specific for Code and not necessarily an issue with Gitpod itself I guess

**Comment by corneliusludmann** [comment]
OK, I would like to close this issue for now. Feel free to open issues in Theia for your feature requests. Once they are landed in Theia they will eventually land in Gitpod as well.
