### ISSUE TITLE
Add linting checks to Gitpod build

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#2566]
With the goal of improving our trust that new PRs won't break Gitpod's functionalities, we want to add a linting check to our CI.

To-do list:
- [ ] Add golangci-lint to default workspace image
- [x] Extend Leeway to run linter when Go code changes
- [x] Fix or mark to ignore(if appropriate) linting problems
- [x] Change workspace IDE settings to use golangci-lint

**Comment by csweichel** [comment]
Leeway has linting support: https://github.com/gitpod-io/leeway/pull/44
