### ISSUE TITLE
The "Code Completion" function does not work  when using the "PHP" repositories

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#257]
**Description:**

The "Code Completion" function does not work  when using the "PHP" repositories

**Steps To Reproduce:**

1. Login to the site
2. Start the workspace (PHP, e.g. https://b5751cb1-3694-41d3-89d6-6e170a13d834.ws-eu./#/workspace/django-beginners-guide)
3. Use the "Code Completion" function
4. Pay attention to the workspace

**Actual result:**

The "Code Completion" function does not work  when using the "PHP" repositories

![2019-01-23_10-12-41](https://user-images.githubusercontent.com/41964662/51592392-2e5bc680-1ef8-11e9-9dcf-278d213548ad.gif)

**Expected result:**

The "Code Completion" function works when using the "PHP" repositories

**Additional Information**:
Reproducibility: 2/5
Win 10 Google Chrome 71.0.3578.98

**Comment by svenefftinge** [comment]
I tried to reproduce but couldn't. The video is too blurry to tell what exactly you tried to do. Please reopen if I missed something.

<img width="816" alt="screenshot 2019-01-23 at 16 59 27" src="https://user-images.githubusercontent.com/372735/51673159-992b0180-1fcd-11e9-858f-9d2de4044691.png">
