### ISSUE TITLE
[Self-Hosted] cannot start workspace: got 404 (GCP, nodomain)

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#2570]
### Describe the bug
When starting a workspace, got stuck at a blank page. Error when inspecting elements in Chrome: https://user-images.githubusercontent.com/24193764/102390481-38d34d80-3fb3-11eb-8839-04df40279ba8.png

Logs from the Dashboard component: 2020/12/16 18:29:08 [error] 19#19: *1152 open() "/www/data/dashboard/supervisor/frontend/main.js" failed (2: No such file or directory), client: 10.0.5.15, server: , request: "GET /supervisor/frontend/main.js HTTP/1.1", host: "35-233-172-32.ip.mygitpod.com", referrer: "https://35-233-172-32.ip.mygitpod.com/workspace/f08cc436-4ccc-47ea-a831-789ef862ae9c/" 10.0.5.15 - - [16/Dec/2020:18:29:08 +0000] "GET /supervisor/frontend/main.js HTTP/1.1" 404 555 "https://35-233-172-32.ip.mygitpod.com/workspace/f08cc436-4ccc-47ea-a831-789ef862ae9c/" "Mozilla/5.0 (X11; Linux x8664) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" "10.138.0.5" 10.0.5.15 - - [16/Dec/2020:18:29:08 +0000] "GET /404/ HTTP/1.1" 200 667 "https://35-233-172-32.ip.mygitpod.com/workspace/f08cc436-4ccc-47ea-a831-789ef862ae9c/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" "10.138.0.5"

### Steps to reproduce
Install following https://www.gitpod.io/docs/self-hosted/latest/install/install-on-gcp-script/, choosing `nodomain`

**Comment by corneliusludmann** [comment]
Does `wsProxy` come up at all? I'm asking due to this bug: https://github.com/gitpod-io/gitpod/pull/2578

**Comment by geropl** [comment]
Yes, after fixing it on my branch :wink:. Approved your PR.

**Comment by corneliusludmann** [comment]
OK, now I have the same issue with the `gitpod-k3s` Docker container. Please let me know if I can do something to help with fixing this.
