### ISSUE TITLE
The "Failed to start RUBY language server" error message is displayed in the "Theia" application after starting the "RUBY" repository

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#258]
**Description:**

The "Failed to start RUBY language server" error  is displayed in the "Theia" application after starting the "RUBY" repository

**Steps To Reproduce:**

1. Login to the site
2. Start the workspace (Language: RUBY, e.g. https://c4821bab-082c-4cea-9e32-7127c1bc4b95.ws-eu./#/workspace/ruby)
3. Pay attention to the "Failed to start RUBY language server" error

**Actual result:**

The "Failed to start RUBY language server" error  is displayed in the "Theia" application after starting the "RUBY" repository

![image](https://user-images.githubusercontent.com/41964662/51594090-551bfc00-1efc-11e9-851b-efb5b18cd909.png)

**Expected result:** 

The "RUBY" language server is  started
 
Additional Information:
Win 10 Google Chrome 71.0.3578.98 // FF 64.0.2

**Comment by svenefftinge** [comment]
related https://github.com/castwide/solargraph/issues/145

**Comment by jankeromnes** [comment]
@tarasdidyk many thanks for reporting this issue. We were able to work around the issue mentioned by Sven. Could you please try again, to see if we've also fixed the bug you're seeing?

**Comment by tarasdidyk** [comment]
It works now

**Comment by jankeromnes** [comment]
Awesome, thanks for confirming! Let's close this issue for now, but please re-open it if the bug comes back.
