### ISSUE TITLE
Distinguish in logging between user-errors and systems-errors

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#2581]
User-errors occur because users did something that's not intended.

System-errors mean something is broken and it's relevant for our SLOs.

Todo:
* decide on severity names
* make our code use them

**Comment by meysholdt** [comment]
And have a third category for 3rd party errors: Errors that we get from requests to GitHub, Gitlab, Bitbucket, Kubernetes Master, etc.

**Comment by csweichel** [comment]
This is not an actionable issue. We'll integrate this concept in our next iteration of the observability API.
