### ISSUE TITLE
Can't parse gitpod/templates/db-migrations-job.yam (gitpod 0.5.0 and 0.6.0beta)

### ISSUE THREAD

**Issue by supersebe** [gitpod-io/gitpod#2586]
When i try to install GitPod, i got this error.

`Error: YAML parse error on gitpod/templates/db-migrations-job.yaml: error converting YAML to JSON: yaml: line 40: found unknown escape character`

**Comment by csweichel** [comment]
How do you try to install Gitpod? I.e. could you post the command/steps you are running?

**Comment by supersebe** [comment]
I followed some of these steps: https://jimmyb.ninja/post/1607033505

**Comment by supersebe** [comment]
Found the problem. The db-password had bad characters.
