### ISSUE TITLE
Python extension completely broken

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#2587]
### Describe the bug
Python in multiple projects is completely unable to find installed modules for syntax highlighting and other related features.

I'll send a screenshot in a minute.  

### Steps to reproduce
Open a python workspace using the `rdilpickle/better-wsfull:latest` image.

### Expected behavior

Imports resolve.

### Additional information

Using new language server, also I have the correct interpreter selected.

### Example repository

github: cakebotpro/cakebot

**Comment by RDIL** [comment]
As you can see here, all external modules are unresolved:
![Capture](https://user-images.githubusercontent.com/34555510/102535681-8d8bcc80-4076-11eb-960f-55546900f66a.PNG)

**Comment by AlexTugarev** [comment]
Indeed, the Python LS ignores packages from `PYTHONUSERBASE=/workspace/.pip-modules` entirely 😞 

@jankeromnes, do you how to fix this?

**Comment by jankeromnes** [comment]
Hi @RDIL! 👋

@AlexTugarev Oops. What image does the Python LS run in? Could it be that we need to (re-)add the `PYTHONUSERBASE` variable to the Theia image?

https://github.com/gitpod-io/gitpod/blob/master/components/theia/app/leeway.Dockerfile

**Comment by AlexTugarev** [comment]
@jankeromnes the IDEs running in the workspace container and `PYTHONUSERBASE` is set. 

actually, let's check the env var is making it into the LS process.

**Comment by RDIL** [comment]
I know it is Christmas eve, but any updates on this?  It would really help to get this working again.  

I know that Python is notorious for these kinds of problems in VSCode.

**Comment by svenefftinge** [comment]
Hey @RDIL, could you share a repo with which the issue is easily reproducible?
Just tried https://github.com/greyli/flask-examples which seemed to work fine (I don't know python well, though)

**Comment by RDIL** [comment]
> Hey @RDIL, could you share a repo with which the issue is easily reproducible?
> Just tried https://github.com/greyli/flask-examples which seemed to work fine (I don't know python well, though)

Try cakebotpro/cakebot

**Comment by svenefftinge** [comment]
Because the processes for the extension host are not login-in shells, the `.bashrc` file doesn't get sourced automatically. 
And because your custom image's `.profile` doesn't source them like the `workspace-full` version the environments don't get initialized properly on non log-in shells.
Not sure if we should generally move those variables to a different initialization file?

**Comment by svenefftinge** [comment]
I believe the underlying issue is, that we do not run the IDE process as a proper login shell. We should mimic the behavior of a locally IDE started by a user. I.e. source `.bashrc` as well, since that seems to be the expectations. cc @akosyakov

**Comment by svenefftinge** [comment]
I've made a PR to your dockerfile https://github.com/RDIL/better-wsfull/pull/8
