### ISSUE TITLE
The "White" line displayed on the "Loading" screen after scrolling down

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#259]
**Description:**

The "White" line is displayed on the "Loading" screen after scrolling down

**Steps To Reproduce:**

1. Login to the site
2. Start any workspace
3. Scroll down
4. Pay attention to the "White" line

**Actual result:**

The "White" line  is  displayed on the "Loading" screen after scrolling down

![image](https://user-images.githubusercontent.com/41964662/51599153-a1b90480-1f07-11e9-9999-5da355103d57.png)

**Expected result:** 
The "White" line is not displayed on the "Loading" screen after scrolling down
 
Additional Information:
Win 10 Google Chrome 71.0.3578.98 // FF 64.0.2

**Comment by svenefftinge** [comment]
There is no scrolling available for me. I can force-scroll a bit and than see some white background on top and bottom. But no scrollbars. @tarasdidyk I consider this unimportant. 
Please, tell me if I missed something.
