### ISSUE TITLE
Getting error in accessing gitpod

### ISSUE THREAD

**Issue by ShikhaMishra9** [gitpod-io/gitpod#2594]
Getting this error

We are having trouble parsing your context
Error: Couldn't parse context 'https://ccf63e42-c7cb-4211-84fd-055a9beb8b38.ws-eu03.gitpod.io/'.

**Comment by akosyakov** [comment]
Did you run `gitpod.io#https://ccf63e42-c7cb-4211-84fd-055a9beb8b38.ws-eu03.gitpod.io/`? Jus try `https://ccf63e42-c7cb-4211-84fd-055a9beb8b38.ws-eu03.gitpod.io/` instead. The part after `#` should point to the valid git repo, nothign else.
