### ISSUE TITLE
[deployment] Suddenly disconnected from my workspace

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#2596]
### Describe the bug

This morning, we've deployed a new version of [gitpod.io](https://gitpod.io) to production. We expect these updates to be invisible or barely noticeable for users.

However, a user reported [on Twitter](https://twitter.com/_Akanoa_/status/1339809055494320128) that:

> Hey @gitpod are you down ? I have been suddenly disconnected from my workspace 😥

> ![Epf1occXUAAGB9A](https://user-images.githubusercontent.com/599268/102590190-7a2d3f80-4110-11eb-9845-94df457d2ef1.png)

### Steps to reproduce

0. Someone is using a gitpod.io workspace
1. Deploy gitpod.io to production

### Expected behavior

- The update should be totally invisible or barely noticeable

**Comment by csweichel** [comment]
This is most likely caused by the proxy cycling through during deployment. Sorry the inconvenience :/

**Comment by geropl** [comment]
> proxy cycling through during deployment

True, but worked as expected: https://github.com/gitpod-com/gitpod/issues/5013#issuecomment-765225729
