### ISSUE TITLE
Have "Back to Workspace List" button

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#2599]
Here, I would love to have a "back to workspace list" button or any other way to get back to Gitpod's dashboard.

![image](https://user-images.githubusercontent.com/239422/102605780-1877d000-4126-11eb-8494-998643467fe0.png)

**Comment by gtsiolis** [comment]
Thanks for opening this @meysholdt! 💯 

This was also brought up in https://github.com/gitpod-io/gitpod/issues/2084 by @akosyakov.

The initial proposal included a button for going back to dashboard (see https://github.com/gitpod-io/gitpod/issues/2084#issuecomment-729234116) and this will probably make more sense once we have a dashboard that's more useful or practical to visit after stopping a workspace.

See also [relevant discussion](https://typefox.slack.com/archives/CGVQAPNPL/p1606820679324700) (internal). /cc @geropl @svenefftinge

**Comment by akosyakov** [comment]
I only need it during testing, since i have to go back to start example workspaces. In production I did not really have a need to go back to workspaces.

**Comment by corneliusludmann** [comment]
Since I also voted for the “Back to Workspace List” and Sven asked for the reasons why we would like to get back to the workspaces list: I can live with not having such a button but then I would like to have all the functions I have in the workspaces list like staring this workspace, downloading the content, go to the user settings etc. on the stopped workspace page.

**Comment by svenefftinge** [comment]
As @gtsiolis already mentioned, we are designing and implementing a proper dashboard landing page to which we can happily forward our users. The issue I have with pointing users to the "workspaces list" is that it currently feels like a dead end and encourages users to restart past workspaces when we really want everyone to start fresh ones based on their Git context.

**Comment by jgallucci32** [comment]
In version 0.5.0 of self-hosted the link took you to the workspace. In 0.6.0 the code was changed to go back to the source code repo (GitLab/Github). I prefer going back to the workspace as well. Is this something which is configurable in the Helm Chart?

**Comment by gtsiolis** [comment]
Hey @jgallucci32! You should be able to see two links, one for the repository and one to reopen the workspace. We plan to redesign this page over the next couple of months and this will most probably include a link to the workspaces list, too. See https://github.com/gitpod-io/gitpod/issues/2599#issuecomment-748043963:

> The initial proposal included a button for going back to dashboard (see https://github.com/gitpod-io/gitpod/issues/2084#issuecomment-729234116) and this will probably make more sense once we have a dashboard that's more useful or practical to visit after stopping a workspace.

**Comment by svenefftinge** [comment]
fixed for the new dashboard
