### ISSUE TITLE
new vue.js project preview yields "Invalid Host header"

### ISSUE THREAD

**Issue by csells** [gitpod-io/gitpod#26]
Installing the vue cli via "npm i -g @vue/cli" and running "vue create hello-world" worked great. However, running it with "yarn serve" and previewing the output on port 8080 yielded a page that said only "Invalid Host header".

**Comment by svenefftinge** [comment]
The dev server isn't accepting external requests. You need to put below's config 
```js
// vue.config.js
module.exports = {
    // options...
    devServer: {
        disableHostCheck: true
    }
}
```

**Comment by csells** [comment]
Yep. That did the trick.

**Comment by svenefftinge** [comment]
Also the host needs to be passed and set to 0.0.0.0 as it defaults to only accepting `localhost`.
```
webpack-dev-server --host 0.0.0.0
```

**Comment by BoboWY** [comment]
Thanks!your answer.my name is bobo.

**Comment by tribals** [comment]
Closed, but it is better to use `devServer.allowedHosts`: https://webpack.js.org/configuration/dev-server/#devserver-allowedhosts

**Comment by sobiero** [comment]
> 
> 
> The dev server isn't accepting external requests. You need to put below's config
> 
> ```js
> // vue.config.js
> module.exports = {
>     // options...
>     devServer: {
>         disableHostCheck: true
>     }
> }
> ```

Where is the file vue.config.js located or do I need to create it? I'm using vue/cli 3.9

**Comment by scozma** [comment]
> 
> 
> > The dev server isn't accepting external requests. You need to put below's config
> > ```js
> > // vue.config.js
> > module.exports = {
> >     // options...
> >     devServer: {
> >         disableHostCheck: true
> >     }
> > }
> > ```
> 
> Where is the file vue.config.js located or do I need to create it? I'm using vue/cli 3.9

You can create a file with that name if you don't have it and add it on the root of your project (same level as package.json for example)

**Comment by qkmc-rk** [comment]
The dev server isn't accepting external requests. You need to put below's config

// vue.config.js
module.exports = {
    // options...
    devServer: {
        disableHostCheck: true
    }
}
Where is the file vue.config.js located or do I need to create it? I'm using vue/cli 3.9
You can create a file with that name if you don't have it and add it on the root of your project (same level as package.json for example)

**Comment by jp96201** [comment]
ssfa

**Comment by mittalyashu** [comment]
I tried passing the url with `--public` flag but it didn't work either

```bash
yarn run dev --public $GITPOD_WORKSPACE_URL
```

Even tried passing the port

```bash
--public $GITPOD_WORKSPACE_URL:443
```

That didn't work either.

**Comment by HalftimeHarry** [comment]
This fixed it https://stackoverflow.com/questions/52959601/using-vue-cli-in-cloud9-ide-container-invalid-host-header

**Comment by Teeratach-Thawilwang** [comment]
> this fixed the error for me: `devServer: { allowedHosts: 'all', },`

This answer helps me a lot. Thank!
for vue-cli-service version ~5.0.0 and my vue.config.js

`
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,
  devServer: { allowedHosts: 'all', },
  pluginOptions: {
    moment: {
      locales: [
        ''
      ]
    }
  }
})`

**Comment by zhangshoucheng1** [comment]
> 开发服务器不接受外部请求。您需要在下面放置配置
> 
> ```js
> // vue.config.js
> module.exports = {
>     // options...
>     devServer: {
>         disableHostCheck: true
>     }
> }
> ```

great

**Comment by ranji31** [comment]
is same as for ionic angular? I'm include above the module file but is still showing "Invalid Host Header"

**Comment by SheikhElMoctarG** [comment]
> is same as for ionic angular? I'm include above the module file but is still showing "Invalid Host Header"

I'm too

**Comment by SheikhElMoctarG** [comment]
I fixed it, only change your `vue.config.js`:
`module.exports = defineConfig({
  transpileDependencies: true,
  devServer: { allowedHosts: 'all', client: {webSocketURL: 'auto://0.0.0.0:0/ws'}},
})`

**Comment by rjj1013404970** [comment]
> I fixed it, only change your `vue.config.js`: `module.exports = defineConfig({ transpileDependencies: true, devServer: { allowedHosts: 'all', client: {webSocketURL: 'auto://0.0.0.0:0/ws'}}, })`

right,if you use vue-cli greater than version 5 ,please change `vue.config.js` to `devServer:{allowedHosts:'all'}` ,
otherwise use less than vue-cli less than version 5, change `vue.config.js` to `devServer:{disableHostCheck: true}`
