### ISSUE TITLE
Web preview overlay hides iframe errors

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#260]
**Describe the bug**

When a web preview fails because of some error, an overlay remains visible in the Preview pane, hiding the actual error.

**To Reproduce**

1. Open this snapshot in Gitpod:

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/1e68fe95-baa8-44d2-ad3e-90538a6111be)

2. A server will start on port 4242, and open a Preview pane, but unfortunately it stays grey

**Expected behavior**

The Preview should show the iframe error, instead of the unhelpful grey overlay.

**Work around**

You can work around this bug by manually deleting the overlay using the browser devtools:

<img width="1552" alt="screenshot 2019-01-23 at 17 59 42" src="https://user-images.githubusercontent.com/599268/51624039-566c1980-1f3a-11e9-9660-f5695c516dfd.png">

<img width="1552" alt="screenshot 2019-01-23 at 18 00 17" src="https://user-images.githubusercontent.com/599268/51624100-713e8e00-1f3a-11e9-8cef-b881b0db3b48.png">

<img width="1552" alt="screenshot 2019-01-23 at 18 00 33" src="https://user-images.githubusercontent.com/599268/51624214-a5b24a00-1f3a-11e9-8870-85e2be81535e.png">

Now you can see the actual error that the iframe encountered, and try to address it.

**Comment by svenefftinge** [comment]
cc @kittaakos

**Comment by kittaakos** [comment]
Related? https://github.com/theia-ide/theia/issues/3589#issuecomment-441247748

**Comment by jankeromnes** [comment]
Well, the CSP error is common, but this bug is about Gitpod hiding any iframe error behind an overlay, while that doesn't seem to happen in Theia itself.

**Comment by jankeromnes** [comment]
The overlay that remains visible (hiding iframe errors), only in Gitpod but not in stock Theia, is:

```html
<div class="theia-mini-browser-load-indicator" style="display: block;"></div>
```

I'll tentatively look into fixing this, but I don't yet know Theia or its Gitpod Extension very well, so I might end up deferring to you @kittaakos or @AlexTugarev.

**Comment by jankeromnes** [comment]
Reading the code, it looks like neither [onFrameLoad()](https://github.com/theia-ide/theia/blob/234b88961be3b335dc6e567cef057f89a55aecb2/packages/mini-browser/src/browser/mini-browser-content.ts#L416) nor [catch (e)](https://github.com/theia-ide/theia/blob/234b88961be3b335dc6e567cef057f89a55aecb2/packages/mini-browser/src/browser/mini-browser-content.ts#L638) are being called in the case of iframe errors. Maybe things like CSP errors get caught somewhere else and not forwarded?

**Comment by jankeromnes** [comment]
Here are the various iframe error behaviors in my two browsers:

## In Firefox (Nightly)

- `gp preview https://www.google.com`
  - Console error: ✅ `Load denied by X-Frame-Options: https://www.google.com/ does not permit cross-origin framing.`
  - 'Load' event: ✅ (loading indicator disappears)
  - Iframe content: ❌ (blank)
- `gp preview http://perdu.com`
  - Console error: ✅ `Blocked loading mixed active content “http://perdu.com/”`
  - 'Load' event: ❌ (loading indicator hides iframe)
  - Iframe content: ❌ (blank)
- `gp preview https://github.com`
  - Console error: ❌ (none)
  - 'Load' event: ❌ (loading indicator hides iframe)
  - Iframe content: ✅ `Blocked by Content Security Policy. An error occurred during a connection to github.com.`
- `gp preview https://www.asdfasdf.asdf`
  - Console error: ❌ (none)
  - 'Load' event: ❌ (loading indicator hides iframe)
  - Iframe content: ✅ `We can’t connect to the server at www.asdfasdf.asdf.`

## In Chrome

- `gp preview https://www.google.com`
  - Console error: ✅ `Refused to display 'https://www.google.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`
  - 'Load'` event: ✅ (loading indicator disappears)
  - Iframe content: ✅ Sad file icon + `www.google.com refused to connect.` on hover
- `gp preview http://perdu.com`
  - Console error: ✅ `Mixed Content: The page at 'https://d42381f3-70bb-4bf0-8099-9b05c27c3d25.ws-eu0.gitpod.io/#/workspace/theia' was loaded over HTTPS, but requested an insecure resource 'http://perdu.com/'. This request has been blocked; the content must be served over HTTPS.`
  - 'Load' event: ❌ (loading indicator hides iframe)
  - Iframe content: ❌ (blank)
- `gp preview https://github.com`
  - Console error: ✅ `Refused to display 'https://github.com/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`
  - 'Load'` event: ✅ (loading indicator disappears)
  - Iframe content: ❌ (blank)
- `gp preview https://www.asdfasdf.asdf`
  - Console error: ❌ (none)
  - 'Load'` event: ✅ (loading indicator disappears)
  - Iframe content: ✅ Sad file icon + `www.asdfasdf.asdf’s server IP address could not be found.` on hover

**Comment by jankeromnes** [comment]
In summary, the loading indicator overlay currently hides these iframe errors:

- In Firefox:
  - `Mixed Content` (but iframe is blank)
  - `CSP error`
  - `Can't connect`
- In Chrome:
  - `Mixed Content` (but iframe is blank)

If we remove the loading indicator overlay (either completely, or hide it after a timeout) we'll reveal the above iframe error (except `Mixed Content`, where the iframe remains blank).

**Comment by jankeromnes** [comment]
Aha, it seems that, in the case of a `Mixed Content` error, `iframe.addEventListener('error', event=>{ })` *does* yield something. Maybe we can subscribe to error events, and display something useful when they happen.

**Comment by jankeromnes** [comment]
Fixed in https://github.com/theia-ide/theia/pull/4399 and deployed. 🎉
