### ISSUE TITLE
When not specifying a domain, GP-SH should use mygitpod.com automatically

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#2603]
@ArthurSens wrote:

 it looks like we have another problem when not setting a domain as well :grimacing:
After installing, I can create a workspace but the Theia IDE never opens, I'm stuck at a black page. Here are the steps I've done:
* Installed gpsh with the installer container and did not set a specific domain for it.
* Opened gpsh with the address provided by the installer.
* Configured git provider with my github account.
* Started a workspace and got stuck in a blackpage.
* Connected to my new k8s cluster, checked if my wokspace was running with kubectl get pods, and it was
* Looked for logs of ws-manager and ws-daemon and they suggested that there were no problems with my workspace
* Looked for logs of dashboard  and noticed this error:

> 2020-12-11T17:22:27.750407256Z stderr F 2020/12/11 17:22:27 [error] 19#19: *1145 open() "/www/data/dashboard/_supervisor/frontend/main.js" failed (2: No such file or directory), client: 10.116.x.xx, server: , request: "GET /_supervisor/frontend/main.js HTTP/1.1", host: "35-233-219-118.ip.mygitpod.com", referrer: "https://35-233-xx-xx.ip.mygitpod.com/workspace/d7f2fc2f-979b-4d56-99ca-53f37415540b/"

**Comment by corneliusludmann** [comment]
Don't understand how the title and the description of this issue fits together. However, the problem described in the issue is a duplicate of this one: #2570. Isn't it?
