### ISSUE TITLE
Kubernetes support with new Docker Preview?

### ISSUE THREAD

**Issue by rsliotta** [gitpod-io/gitpod#2605]
Hello...  I got docker working.  Fantastic!

My next question is should any of the kubernetes work?  k3s, kind, minikube?

**Comment by sr229** [comment]
Gitpod Self hosted supports most Kubernetes distributions so yes, Gitpod should support local Kubernetes, however I haven't tested if it works on K3s, as K3s has a different feature set.

**Comment by akosyakov** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/1337?

**Comment by sr229** [comment]
Reviewing the case it seems to be.

**Comment by aledbf** [comment]
Closing. Duplicate #1337

**Comment by loujaybee** [comment]
Hey folks, just coming back to this for others who are googling, we recently published a new docs page: 

https://www.gitpod.io/docs/integrations/kubernetes

This page covers common use cases and ways to develop Kubernetes applications in Gitpod: 

* [Using Docker in Gitpod](https://www.gitpod.io/docs/integrations/kubernetes#1-using-docker-in-gitpod)
* [Using Docker Compose in Gitpod](https://www.gitpod.io/docs/integrations/kubernetes#2-using-docker-compose-in-gitpod)
* [Using a Kubernetes Network Proxy in Gitpod (e.g. Telepresence)](https://www.gitpod.io/docs/integrations/kubernetes#3-using-a-kubernetes-network-proxy-in-gitpod-eg-telepresence)
* [Running Kubernetes clusters in Gitpod (e.g. MiniKube)](https://www.gitpod.io/docs/integrations/kubernetes#4-running-kubernetes-clusters-in-gitpodeg-minikube)
* [Connecting to a remote Kubernetes cluster inside Gitpod](https://www.gitpod.io/docs/integrations/kubernetes#5-connecting-to-a-remote-kubernetes-cluster-inside-gitpod)

Please do check it out, and let us know if you have any questions 🙏
