### ISSUE TITLE
Authorization with "gitlab." is not permitted. (self-hosted)

### ISSUE THREAD

**Issue by TeNNoX** [gitpod-io/gitpod#2606]
### Describe the bug
When I try to open a repo from my self-hosted GitLab instance, The authorization attempt fails with the error message:
> Sorry, something went wrong 😓
> Authorization with "gitlab." is not permitted.

### Steps to reproduce
1. Open URL for self-hosted instance:  
  `https://gitpod.io/#https://gitlab.mydomain.org/project/our-app/-/tree/master/`
2. See request to authorize:
  > Unauthorized
  > This action requires more permissions. Please authorize with gitlab. to continue.
3. Click "authorize with gitlab." link: `https://gitpod.io/api/authorize?returnTo=https%3A%2F%2Fgitpod.io%2F%23https%3A%2F%2Fgitlab.tamera.org%2Fcybernetics%2Four-board%2F-%2Ftree%2Fmaster%2F&host=gitlab.&scopes=read_user,api`
4. See error page

### Expected behavior
Authorization request to self-hosted instance and successful loading of the repo.

### Additional information
HTTP Request:
`GET https://gitpod.io/api/authorize?returnTo=https://gitpod.io/#https://gitlab.tamera.org/cybernetics/our-board/-/tree/master/&host=gitlab.&scopes=read_user,api`
  => HTTP 302 Found (Location: `https://gitpod.io/sorry#Authorization%20with%20%22gitlab.%22%20is%20not%20permitted.`)
No redirect to our gitlab instance inbetween.

I have also tried setting up a git provider in the settings.

**Comment by svenefftinge** [comment]
I assume you went through the setup of a git provider for your self-managed GitLab instance, as described here?

https://www.gitpod.io/docs/gitlab-integration/#oauth-application

**Comment by JamesCullum** [comment]
As reported in the other ticket, you can use the test url here: https://gitlab.test1.test2.eu/group/folder/repo-name/-/tree/master/

And yes, setting up works fine, just the import fails.

**Comment by AlexTugarev** [comment]
👋🏻  'looking in to this now.

a. `gitlab.mydomain.org` from ☝🏻 has to be verified by the owner of this Git Provider integration in their gitpod.io/settings.
b. `host=gitlab.` param from authorize URL in ☝🏻 looks bogus; it should be a proper hostname

**Comment by AlexTugarev** [comment]
@JamesCullum, and @TeNNoX, please try again 🙏🏻

**Comment by JamesCullum** [comment]
@AlexTugarev The bug has been fixed, but a different one occurs now - it can't find the repository:
`<repo-name> may be private

The repository <repo-name> could not be accessed though you allowed to access private repositories.

You can try this ...
    Make sure the repository <repo-name> exists.
    If <repo-name> belongs to an organization, check if Gitpod was approved.
`

It exists (used the Gitlab integrated gitpod button). The token is for a user with admin access and is part of the group. I'm not aware of any setting where I could approve it for an organization. In the org settings there is no reference to such a permission. The link leads to the user settings which does not contain any reference to an organization.

**Comment by AlexTugarev** [comment]
Please create a new issue, @JamesCullum. And be as specific as possible, as I see you don't want to disclose the project you are working on. The version of your Gitlab installation would be of interest.

**Comment by TeNNoX** [comment]
> @JamesCullum, and @TeNNoX, please try again 🙏🏻

Works! Thanks a lot!! Now I can start coding the sh*t out of my projects from anywhere :sunglasses:
