### ISSUE TITLE
Support Electron apps

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#261]
It would be cool to support electron desktop apps in Gitpod, like for example:

- https://github.com/fabiospampinato/notable
- https://github.com/nukeop/nuclear

**Comment by jankeromnes** [comment]
So I tried running the `nuclear` web app in Gitpod's web preview (i.e. outside of electron), using these `webpack-dev-server` parameters:

```
--host=0.0.0.0 --allowed-hosts=.gitpod.io --target=web
```

The app loading screen does show up, but the app is mostly broken, likely because it's missing some electron features:

```
TypeError: fs.existsSync is not a function
```

Another option to support electron apps could be to run electron via noVNC.

**Comment by 32leaves** [comment]
We do have VNC support in Gitpod that could be handy here (basically noVNC): https://medium.com/gitpod/developing-native-ui-applications-in-gitpod-15af2967c24e

**Comment by jankeromnes** [comment]
@svenefftinge I agree about VNC, but haven't tested it yet. It's the next thing I was planning to do when I cycle back to this issue.

**Comment by svenefftinge** [comment]
I think we should close this ticket, as Gitpod already supports Electron apps. 
Chris' post (referenced above) shows how to run Vs Code which is an electron app.

**Comment by jankeromnes** [comment]
So, I've now got https://github.com/nukeop/nuclear running in Gitpod:

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#https://github.com/jankeromnes/nuclear)
<img width="1552" alt="screenshot 2019-01-25 at 15 40 15" src="https://user-images.githubusercontent.com/599268/51752427-c7850b80-20b7-11e9-83a9-59a16b6cf643.png">

Here is what the config looks like:

https://github.com/jankeromnes/nuclear/commit/c52e4ae40ada932e4ef473ff856ba36fa6d4a1d0

A few obvious UX problems:

- [ ] The VNC tab doesn't auto-reconnect, so if the websocket flakes out, the Preview pane shows "Disconnected" and needs to be manually refreshed
- [ ] The Preview pane size is not great, as you don't see the entire app, and you have to weirdly scroll around to use the desktop app (maybe defaulting to a Browser preview might help)

**Comment by svenefftinge** [comment]
Nice! Do you have suggestions how that could be improved?

**Comment by jankeromnes** [comment]
We don't have that problem on Janitor, and I see a few differences in the x11vnc/Xvfb/noVNC options we use:

https://github.com/JanitorTechnology/dockerfiles/blob/58e2300fd137a157b6c429a9190ea77ddd8ebfda/ubuntu-dev/supervisord.conf#L16-L31

https://github.com/gitpod-io/workspace-images/blob/master/full-vnc/start-vnc-session.sh#L10-L16
