### ISSUE TITLE
Add ability to use a custom IDE Docker image for Gitpod

### ISSUE THREAD

**Issue by mehulagg** [gitpod-io/gitpod#2613]

**Comment by meysholdt** [comment]
Please note that it's already possible to bring custom workspace Docker images and Dockerfiles (which Gitpod builds on-demand) to Gitpod: https://www.gitpod.io/docs/config-docker/

Bringing custom IDEs to Gitpod is work-in-progress, please see https://github.com/gitpod-io/gitpod/issues/2419. 
Closing this issue as a duplicate.
