### ISSUE TITLE
wasm-pack build failed with Error: Permission denied (os error 13)

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#2614]
### Describe the bug
wasm-pack build failed with Error: Permission denied (os error 13)。

wasm-pack --help works.

### Steps to reproduce

open this PR https://github.com/gengjiawen/monkey-rust/pull/14 in gitpods. You may need to install this extension first
https://chrome.google.com/webstore/detail/gitpod-dev-environments-i/dodmmooeoklaejobgleioelladacbeki

when opened

```bash
cd wasm/
wasm-pack build
```
Not sure this related to permission issue or something. But it doesn't show stacktrace.
### Expected behavior

build passed.

### Additional information

I first use my custom image. then I switched to `gitpod/workspace-wasm`, both with the same issue.

Related issue: https://github.com/rustwasm/wasm-pack/issues/945

cc @JesterOrNot

**Comment by svenefftinge** [comment]
The PR was merged and the branch no longer exists, so I cannot try on the referenced PR.
I tried with the main branch on https://github.com/gengjiawen/monkey-rust but couldn't reproduce the issue.

It sounds like some permissions are wrong in the user dir. Maybe there was something installed as root during the docker build. Please note, that you can enable "Feature Preview" in your gitpod settings (https://gitpod.io/settings/) to get `sudo` privileges in case you want to fix those file permissions.

Closing this now, as I don't know how to reproduce and it looks like some issue with your image. Please open a new ticket if you think there is something we need to fix in Gitpod.

**Comment by gengjiawen** [comment]
> it looks like some issue with your image

I am using `gitpod/workspace-wasm`

The master branch issue still exist, using sudo results in other issue.

![image](https://user-images.githubusercontent.com/3759816/103144746-944acb80-4769-11eb-9907-9742aded4825.png)

**Comment by gengjiawen** [comment]
Since official `gitpod/workspace-wasm` not work. I give user image a try. But sudo requires password.

![image](https://user-images.githubusercontent.com/3759816/103219721-7b087180-4959-11eb-96fa-c2bbc659c968.png)

**Comment by svenefftinge** [comment]
> Since official `gitpod/workspace-wasm` not work (Currently in master). I give user image a try. But sudo requires password.
> 
> ![image](https://user-images.githubusercontent.com/3759816/103219721-7b087180-4959-11eb-96fa-c2bbc659c968.png)
> 
> PR: [gengjiawen/monkey-rust#17](https://github.com/gengjiawen/monkey-rust/pull/17)

In a custom image we only add the gitpod user later but we don’t add it to sudoers. We would have to check if sudo is installed at all.

As a workaround you can add the following to your docker file:

### Gitpod user ###
# '-l': see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
RUN useradd -l -u 33333 -G sudo -md /home/gitpod -s /bin/bash -p gitpod gitpod \
    # passwordless sudo for users in the 'sudo' group
    && sed -i.bkp -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers
(taken from https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile#L34)

**Comment by svenefftinge** [comment]
I'm reopening this. We should fix the workspace-wasm image.

**Comment by gengjiawen** [comment]
> > Since official `gitpod/workspace-wasm` not work (Currently in master). I give user image a try. But sudo requires password.
> > ![image](https://user-images.githubusercontent.com/3759816/103219721-7b087180-4959-11eb-96fa-c2bbc659c968.png)
> > PR: [gengjiawen/monkey-rust#17](https://github.com/gengjiawen/monkey-rust/pull/17)
> 
> In a custom image we only add the `gitpod` user later but we don't add it to sudoers. We would have to check if sudo is installed at all.
> 
> As a workaround you can add the following to your docker file:
> 
> ```
> ### Gitpod user ###
> # '-l': see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
> RUN useradd -l -u 33333 -G sudo -md /home/gitpod -s /bin/bash -p gitpod gitpod \
>     # passwordless sudo for users in the 'sudo' group
>     && sed -i.bkp -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers
> ```
> 
> (taken from [https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile#L34](https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile?rgh-link-date=2020-12-30T07%3A42%3A34Z#L34))

Workaround works， thanks.

**Comment by gengjiawen** [comment]
Not sure what changed, this issue is gone. closed.
