### ISSUE TITLE
ServerPod: Error in fetching sampling strategy

### ISSUE THREAD

**Issue by bergerem** [gitpod-io/gitpod#2620]
Im trying to install gitpod and now all pods are on running state, but i can't reach gitpod over the internet.

All I got are these logs from the server-<...> node:

`{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"server","version":"0.5.0"},"component":"server","severity":"ERROR","time":"2020-12-23T14:36:52.386Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"server","version":"0.5.0"},"component":"server","severity":"ERROR","time":"2020-12-23T14:36:55.573Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"server","version":"0.5.0"},"component":"server","severity":"ERROR","time":"2020-12-23T14:37:05.960Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"server","version":"0.5.0"},"component":"server","severity":"ERROR","time":"2020-12-23T14:37:31.036Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}` 

this from the ws-manager-brigde node:

`{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"ws-manager-bridge","version":"0.5.0"},"component":"ws-manager-bridge","severity":"ERROR","time":"2020-12-23T14:36:50.280Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"ws-manager-bridge","version":"0.5.0"},"component":"ws-manager-bridge","severity":"ERROR","time":"2020-12-23T14:37:13.928Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"component":"ws-manager-bridge","severity":"DEBUG","time":"2020-12-23T14:37:40.347Z","environment":"production","region":"local","message":"controlling instances","payload":{"installation":"local-00"}}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"ws-manager-bridge","version":"0.5.0"},"component":"ws-manager-bridge","severity":"ERROR","time":"2020-12-23T14:37:50.279Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"ws-manager-bridge","version":"0.5.0"},"component":"ws-manager-bridge","severity":"ERROR","time":"2020-12-23T14:38:13.928Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"component":"ws-manager-bridge","severity":"DEBUG","time":"2020-12-23T14:38:40.347Z","environment":"production","region":"local","message":"controlling instances","payload":{"installation":"local-00"}}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"ws-manager-bridge","version":"0.5.0"},"component":"ws-manager-bridge","severity":"ERROR","time":"2020-12-23T14:38:50.280Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"ws-manager-bridge","version":"0.5.0"},"component":"ws-manager-bridge","severity":"ERROR","time":"2020-12-23T14:39:13.929Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"component":"ws-manager-bridge","severity":"DEBUG","time":"2020-12-23T14:39:40.347Z","environment":"production","region":"local","message":"controlling instances","payload":{"installation":"local-00"}}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"ws-manager-bridge","version":"0.5.0"},"component":"ws-manager-bridge","severity":"ERROR","time":"2020-12-23T14:39:50.280Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"ws-manager-bridge","version":"0.5.0"},"component":"ws-manager-bridge","severity":"ERROR","time":"2020-12-23T14:40:13.930Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}
{"component":"ws-manager-bridge","severity":"DEBUG","time":"2020-12-23T14:40:40.348Z","environment":"production","region":"local","message":"controlling instances","payload":{"installation":"local-00"}}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"ws-manager-bridge","version":"0.5.0"},"component":"ws-manager-bridge","severity":"ERROR","time":"2020-12-23T14:40:50.281Z","environment":"production","region":"local","message":"Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.","loggedViaConsole":true}`

this multiple times from the ws-manager:

`{"bvail":63955791872,"message":"checked for available disk space","minBytesAvail":21474836480,"serviceContext":{"service":"ws-manager-node","version":""},"severity":"debug","time":"2020-12-23T14:36:17Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","containerID":"15880989be254354b227058520add25ed42e4580539502e086dd4965adb71838","containerImage":"","error":"not found\ngithub.com/containerd/containerd/errdefs.init\n\t/workspace/go/pkg/mod/github.com/containerd/containerd@v1.3.2/errdefs/errors.go:45\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5625\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.main\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:191\nruntime.goexit\n\t/home/gitpod/sdk/go1.15/src/runtime/asm_amd64.s:1374\ncontainer \"15880989be254354b227058520add25ed42e4580539502e086dd4965adb71838\" in namespace \"k8s.io\"\ngithub.com/containerd/containerd/errdefs.FromGRPC\n\t/workspace/go/pkg/mod/github.com/containerd/containerd@v1.3.2/errdefs/grpc.go:107\ngithub.com/containerd/containerd.(*remoteContainers).Get\n\t/workspace/go/pkg/mod/github.com/containerd/containerd@v1.3.2/containerstore.go:50\ngithub.com/gitpod-io/gitpod/ws-manager-node/pkg/resourcegov.(*WorkspaceDispatch).handleContainerdEvent\n\t/tmp/build/components-ws-manager-node--app.3d794f0228d862e5d84e30d75b432214ca40e938/pkg/resourcegov/dispatch.go:192\ngithub.com/gitpod-io/gitpod/ws-manager-node/pkg/resourcegov.(*WorkspaceDispatch).Start\n\t/tmp/build/components-ws-manager-node--app.3d794f0228d862e5d84e30d75b432214ca40e938/pkg/resourcegov/dispatch.go:176\nruntime.goexit\n\t/home/gitpod/sdk/go1.15/src/runtime/asm_amd64.s:1374","message":"cannot find container we just received a create event for","serviceContext":{"service":"ws-manager-node","version":""},"severity":"warning","time":"2020-12-23T14:36:42Z"}`

`{"bvail":63955771392,"message":"checked for available disk space","minBytesAvail":21474836480,"serviceContext":{"service":"ws-manager-node","version":""},"severity":"debug","time":"2020-12-23T14:36:47Z"}`

and this 2 times from ws-sync:

`{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","containerID":"15880989be254354b227058520add25ed42e4580539502e086dd4965adb71838","containerImage":"","error":"not found\ngithub.com/containerd/containerd/errdefs.init\n\t/workspace/go/pkg/mod/github.com/containerd/containerd@v1.3.3/errdefs/errors.go:45\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5625\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.doInit\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:5620\nruntime.main\n\t/home/gitpod/sdk/go1.15/src/runtime/proc.go:191\nruntime.goexit\n\t/home/gitpod/sdk/go1.15/src/runtime/asm_amd64.s:1374\ncontainer \"15880989be254354b227058520add25ed42e4580539502e086dd4965adb71838\" in namespace \"k8s.io\"\ngithub.com/containerd/containerd/errdefs.FromGRPC\n\t/workspace/go/pkg/mod/github.com/containerd/containerd@v1.3.3/errdefs/grpc.go:107\ngithub.com/containerd/containerd.(*remoteContainers).Get\n\t/workspace/go/pkg/mod/github.com/containerd/containerd@v1.3.3/containerstore.go:50\ngithub.com/gitpod-io/gitpod/ws-sync/pkg/cri.(*ContainerdCRI).handleContainerdEvent\n\t/tmp/build/components-ws-sync--app.be17edd28fbd915db71942934270b8b2baedc190/pkg/cri/containerd.go:133\ngithub.com/gitpod-io/gitpod/ws-sync/pkg/cri.(*ContainerdCRI).start.func1\n\t/tmp/build/components-ws-sync--app.be17edd28fbd915db71942934270b8b2baedc190/pkg/cri/containerd.go:117\nruntime.goexit\n\t/home/gitpod/sdk/go1.15/src/runtime/asm_amd64.s:1374","message":"cannot find container we just received a create event for","serviceContext":{"service":"ws-sync","version":""},"severity":"warning","time":"2020-12-23T14:36:42Z"}`

**Comment by supersebe** [comment]
Ok this seems to happen, when im NOT using:

```
dnsPolicy: ClusterFirstWithHostNet
hostNetwork: true
```

**Comment by supersebe** [comment]
Nvm. After distributing ports I got the same issue.

`Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778`
