### ISSUE TITLE
Not exposing ports

### ISSUE THREAD

**Issue by stefdworschak** [gitpod-io/gitpod#2621]
### Describe the bug
When running a web server from the command line (e.g. `python3 -m http.server`) the server runs, but on the Ports tab the specified port gets stuck in status `detecting` and not actually exposing/listening on the port which means you cannot open the webpage.

### Additional behaviour
Starting the workspace did take longer than usual, but did not fail.

### Steps to reproduce
1) Open workspace
2) Run `python3 -m http.sever` 
3) Check "Ports" tab.

### Screenshots
![image](https://user-images.githubusercontent.com/31205982/103008428-05ea0600-452d-11eb-8ae3-55ee7a07556e.png)

![image](https://user-images.githubusercontent.com/31205982/103008415-008cbb80-452d-11eb-928f-496e3525c356.png)

**Comment by armedcor** [comment]
Currently have a number students effected by this issue, one who's workspace temporally hung while trying to stop it.

**Comment by Sraleik** [comment]
I have the exact same problem on a simple vuejs application (which work fine half an hour ago)

**Comment by sergioadll** [comment]
I'm having the same problem also!

**Comment by Vlad-404** [comment]
I'm the student in question xD 

I started working on my project and after I encountered the bug described above, I tried restarting the workspace. It didn't work. After I tried stopping the workspace, I went back to the workspaces list. It took around 10 minutes to stop the workspace and after re-entering workspace in question, problem still persists. I tried Google Chrome and Opera - no difference.

**Comment by TanYa-Go** [comment]
I have the same issue, no open ports, just says detecting ports....

**Comment by byIlsa** [comment]
Same here, loading workspace takes long as well, stuck on "Pulling Docker Images"

**Comment by VMBlakelock** [comment]
Here to UK. Stuck at pulling docker images.
Then when workspace opens shows ports detecting

**Comment by svenefftinge** [comment]
Thanks for reporting. We are looking into it.

**Comment by DaithiShan** [comment]
Hi all, just to flag that I'm experiencing the same issues in Wexford, Ireland. Can't open ports and workspaces.

**Comment by raphaelmar** [comment]
Same here in Danemark, ports not being exposed....Frustrating!

**Comment by svenefftinge** [comment]
It is fixed now.

**Comment by Vlad-404** [comment]
It happened again @svenefftinge 
Workspace id and name: d85e03bd-8ba0-49cf-8e60-e9b6d1bbdb62 Vlad-404/photo-portfolio - master
Location Vienna, Austria.

**Comment by Leefarmer83** [comment]
Having issues as above. detecting ports, trying to get my project done....frustrating.
