### ISSUE TITLE
When using hostNetwork: true results in not enough ports.

### ISSUE THREAD

**Issue by bergerem** [gitpod-io/gitpod#2622]
### Describe the bug
When im trying to use  hostNetwork: true, the Pods are in Pending Status and the logs saying that:

`1 node(s) didn't have free ports for the requested pod ports, 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.`

If i dont use hostNetwork: true, i cant even open the website.

### Steps to reproduce
Adding `hostNetwork: true` under defaults.dnsPolicy in values.yaml.

### Expected behavior
Starting the Pods and see the website.

**Comment by supersebe** [comment]
Problem solved with `kubectl taint nodes --all node-role.kubernetes.io/master-`

BUT now i dont have free Ports on these Pods:
![Unbenannt](https://user-images.githubusercontent.com/60353449/103230096-de33dd00-4934-11eb-99f5-947bf7825757.PNG)
