### ISSUE TITLE
Store and restore dirty editor contents

### ISSUE THREAD

**Issue by artalar** [gitpod-io/gitpod#2623]
### Describe the bug
It is very annoying! If I change some files, but don't save them (it main flow for web development to don't force HMR reloading for the draft code) and went from the browser tab and a pod goes to inactive after page reloading all my changes is disappear.

### Steps to reproduce
Start an pod, make changes in some file, wait some time, after pod goes to inactivity reload it.

### Expected behavior
Changes in file saving in browser storage

**Comment by sanvit** [comment]
Until they fix this, you might want to enable auto save.

**Comment by akosyakov** [comment]
It works nicely in Code already.
