### ISSUE TITLE
[VS Code] code command on terminal opens vim

### ISSUE THREAD

**Issue by sanvit** [gitpod-io/gitpod#2625]
### Describe the bug

using the 'code' command on  terminal opens up vim inside the terminal

### Steps to reproduce

run `code filename`

### Expected behavior

Opens up a new VS Code editor screen

### Video Screenshot

https://user-images.githubusercontent.com/4323051/103166912-128e9700-486a-11eb-914d-063c2468f0d5.mp4

https://user-images.githubusercontent.com/4323051/103166911-0f93a680-486a-11eb-914e-00cd4e790d23.mp4

**Comment by svenefftinge** [comment]
This will be solved with https://github.com/gitpod-io/gitpod/pull/2577

**Comment by akosyakov** [comment]
fixed in https://github.com/gitpod-io/gitpod/pull/2577, will be deployed as a part of Jan release
