### ISSUE TITLE
[Theia] PHP Debug extension doesn't work

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2626]
Only in Theia (VS Code works fine) the debugging with "PHP Debug" doesn't work.
See [community thread](https://community.gitpod.io/t/jesterornot-gitpod-php-debug-breakpoints-ignored/2354).
The browser console says
```
{
command: "initialize"
message: "debug session is closed"
request_seq: 1
seq: 0
success: false
type: "response"
}
```

```

  | Promise.then (async) |   |  
-- | -- | -- | --
  | (anonymous) | @ | debug-session-manager.ts:268
  | (anonymous) | @ | index.ts:17
  | (anonymous) | @ | index.ts:17
  | (anonymous) | @ | index.ts:17
  | o | @ | index.ts:17
  | e.doStart | @ | debug-session-manager.ts:237
  | (anonymous) | @ | debug-session-manager.ts:185
  | (anonymous) | @ | index.ts:17
  | (anonymous) | @ | index.ts:17
  | a | @ | index.ts:17

```

**Comment by davidwindell** [comment]
@svenefftinge I think I'm seeing this too, although I get:

`The debug session type "php7" is not supported.`

**Comment by akosyakov** [comment]
@davidwindell Have you tried to use Code instead? see https://www.gitpod.io/docs/feature-preview/#default-ide

**Comment by davidwindell** [comment]
I find code won't start for me, it sits around for ages pulling container 2/3. 

I used to have PHP debugging working just fine on Eclipse Che Theia.

**Comment by davidwindell** [comment]
In another workspace, I get a different error (this time in the browser console):

```
Uncaught (in promise) {type: "response", request_seq: 1, command: "initialize", seq: 0, success: false, …}
Promise.then (async)
(anonymous) @ debug-session-manager.ts:268
```

**Comment by akosyakov** [comment]
> I find code won't start for me, it sits around for ages pulling container 2/3.

That's probably unrelated to Code, but just to check: could you please share which repo you are trying to start?

**Comment by davidwindell** [comment]
It only happens when I switch to Code (I always run in Feature Preview, for sudo, on Theia without a problem) I'm not particularly interested in pursuing Code tbh b ecause Theia works well for our needs.

That being said, as we're a paying team I'd prefer not to share our private repo links on here but I've been able to find two public repos, one that works and one that demonstrates the problem I'm having with the debugger not even starting (and throwing that Uncaught error):

BROKEN: https://github.com/tetsuroba/Gitpod-PHP-Debug/commit/89ecd57729f81d0671aab85c41f7510bd3169d46
WORKS: https://github.com/apolopena/gitpod-php-debug-boilerplate/commit/ac00238fc20c1fc1e930f691255ee474ea1606cd

Hope that helps?

**Comment by akosyakov** [comment]
I could not reproduce with https://github.com/tetsuroba/Gitpod-PHP-Debug/commit/89ecd57729f81d0671aab85c41f7510bd3169d46
![php-debug](https://user-images.githubusercontent.com/3082655/110083420-f558d600-7d8e-11eb-8a14-2e24cf267edd.gif)

**Comment by akosyakov** [comment]
> I'm not particularly interested in pursuing Code tbh b ecause Theia works well for our needs.

We are going to deprecate Theia rather soon, since Code remote support got quite robust. I would recommend you to try it out and file issues if you miss something.

**Comment by davidwindell** [comment]
Ok, thanks - if that's the intention then we will abandon Theia! I'm about to onboard five of our team on a paid plan next week so don't want to make them change after. Is there some gotcha I should be aware of as it only doesn't work with our custom image. Here's a quick reproduction of the problem:

https://github.com/davidwindell/gitpod-test/tree/main

And a workspace that won't start:

https://emerald-rabbit-exsqmka6.ws-eu03.gitpod.io/

Would you be able to kindly take a quick look before I raise an issue?

**Comment by davidwindell** [comment]
@akosyakov I've created a seperate issue for this https://github.com/gitpod-io/gitpod/issues/3355

**Comment by davidwindell** [comment]
Just to say, xdebug worked perfectly once we moved to Ubuntu on both Code and Theia.
