### ISSUE TITLE
The "Search" result аre switched after clicking the "Refresh"  button 

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#263]
**Description:**

The "Search" result аre switched after clicking the "Refresh"  button 

**Steps To Reproduce:**

1. Login to the site
2. Start any workspace
3. Open the "Search" panel
4. Search for any files / words / letters (for example, "a").
5. Click the "Refresh" button
6. Pay attention to the "Search" result

**Actual result:**

The "Search" result аre switched after clicking the "Refresh"  button 

![2019-01-24_10-38-06](https://user-images.githubusercontent.com/41964662/51666015-c1166700-1fc5-11e9-9dd3-7047e5b54875.gif)

**Expected result:** 

The "Search" result аre not switched after clicking the "Refresh"  button 
 
Additional Information:
Win 10 Google Chrome 71.0.3578.98 // FF 64.0.2

**Comment by svenefftinge** [comment]
See https://github.com/theia-ide/theia/issues/4113
