### ISSUE TITLE
File Context is not working when using the Code editor

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2632]
### Describe the bug

[File Context](https://www.gitpod.io/docs/context-urls/#file-context) is not working when using the Code editor.

> The file context is an extension to the repository context, in that Gitpod will check out the corresponding branch and open the respective file in an editor.

### Steps to reproduce

1. Enable [Feature Preview](https://www.gitpod.io/docs/feature-preview/).
1. Select Code as the [Default IDE](https://www.gitpod.io/docs/feature-preview/#default-ide).
1. For example, open https://gitpod.io/#https://github.com/gitpod-io/NextSimpleStarter/tree/master/pages.

### Expected behavior

This should expand the corresponding folder or open the selected file in the editor, as seen in Theia editor.

**Comment by svenefftinge** [comment]
We are also not opening the project's readme when starting from a default context, nor opening the diff when starting from a MR/PR.

**Comment by akosyakov** [comment]
I guess we will look into GitHub/GItLab/BitBucket authentication while working on this issue, i.e. opening the diff view is not possible without it. Or we should break it down?

**Comment by csweichel** [comment]
@akosyakov I think we should break this down into smaller, more actionable pieces.

**Comment by akosyakov** [comment]
@csweichel Created https://github.com/gitpod-io/gitpod/issues/3305 and https://github.com/gitpod-io/gitpod/issues/3306 based on what we discussed last Friday for Theia -> Code migration.
