### ISSUE TITLE
Explorer doesn't make enough room to expand

### ISSUE THREAD

**Issue by mkarg** [gitpod-io/gitpod#2633]
### Describe the bug
Explorer expands, but subsequent panels do not move downwards.

### Steps to reproduce
Click on + to expand tree in explorer.

### Expected behavior
Explorer expands, and subsequent panel moves downwards.

### Additional information
Explorer expands, but subsequent panel stays at its current location.

### Example repository
https://a4953bd2-e582-4ba9-a9e8-18d7062d9247.ws-eu03.gitpod.io/#/workspace/jaxrs-done-right

**Comment by svenefftinge** [comment]
Not sure I understand what you mean. Can you share more info?
Is anything in this screen recording not meeting your expectations?

https://user-images.githubusercontent.com/372735/103370353-e1fa6780-4acc-11eb-8db5-4539eb74ab06.mov

**Comment by mkarg** [comment]
In your recording, the "Java Dependencies" panel moves to the bottom to make space for the expanding explorer. But in my workspace on Gitpod, the "Java Dependencies" panel does NOT move to the bottom but simply stays in place, hence only few lines of the expanding explorer is seen and I must scroll a lot...! If you like, I can invite you to the workspace or we do screen sharing.

**Comment by svenefftinge** [comment]
Ok, thanks. What browser are you on?

**Comment by mkarg** [comment]
Chrome
