### ISSUE TITLE
Does gitpod provide API to fetch environment variables? 

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#2641]
I wanna add to my extension feature that allow to me fetch env variable that could be used to log in against Gitlab NPM Registry / Docker Registry, etc without need to do it manually.

Use Case.
1. I create a personal access token with needed scopes with access to needed API.
2. Add api call to GitPod API to fetch needed environment and use later for extension needs.

AFIAK gp cli do something familiar.

**Comment by csweichel** [comment]
You could add the token as [environment variable](https://www.gitpod.io/docs/environment-variables/) and have your extension rely on that variable.
At the moment we don't have a generalised token management (yet).

**Comment by svenefftinge** [comment]
closing as answered
