### ISSUE TITLE
Git push

### ISSUE THREAD

**Issue by azimny86** [gitpod-io/gitpod#2643]
Hi, I have a problem with 'git push ' that it's full error what I have on consol :
To https://github.com/azimny86/Milestone-Project.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/azimny86/Milestone-Project.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by csweichel** [comment]
Hi,

this is more of a regular GIt usage thing rather than a Gitpod issue.
What happened is that the main branch of your remote advanced, preventing the push from succeeding.
You could try `git pull --rebase` prior to `git push`.
