### ISSUE TITLE
Gitpod recognizes Java 15 as Java 14

### ISSUE THREAD

**Issue by mkarg** [gitpod-io/gitpod#2644]
### Describe the bug
Gitpod reports "Java 14" in the status line for a project using Java 15.

### Steps to reproduce
In a new Maven project with default JDK 11, install `sdk install java 15.0.1-zulu` and set `maven.compiler.release` to `15`.

### Expected behavior
Gitpod's status line shows 15 instead of 14.

### Example repository
https://d0cfae18-86ee-4e75-bd24-49703a4a78a9.ws-eu03.gitpod.io/#/workspace/jaxrs-done-right

**Comment by corneliusludmann** [comment]
I'm able to reproduce this with the following steps:

1. Open an (empty) repo in Gitpod
2. Run `mvn -B archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4`
3. `File → Open Workspace...`, choose `/home/workspace/.../my-app`
4. Run `sdk install java 15.0.1-zulu`
5. Change properties in `pom.xml`: set `maven.compiler.source`, `maven.compiler.target`, and `maven.compiler.release` to `15`.
6. `F1` → `Java: Clean the language server workspace`
7. Open the `App.java` file, the status bar says `JavaSE-14` but `java -version` says `15.0.1`. 

_Note: Probably some of these steps are actually not necessary to reproduce._

I guess it's an issue with the java plugin: https://github.com/redhat-developer/vscode-java. However, this needs more investigation.

**Comment by svenefftinge** [comment]
I guess it is because the changed environment (PATH) is not available in the extension host process. cc @akosyakov

**Comment by akosyakov** [comment]
I think Sven is right, you can give configure `java.home` in your workspace settings or better modify the docker image, commit and start a new workspace.

**Comment by mkarg** [comment]
Okay, and what does a solution look like that works out of the box, i. e. without me becoming an administrator?

**Comment by corneliusludmann** [comment]
@akosyakov When I hover over `JavaSE-14` in the status bar, the tooltip points to the correct java executable (version 15). That's why I don't believe in @svenefftinge's guess. Maybe the Java plugin just displays the wrong version but uses the correct one?

**Comment by mkarg** [comment]
> @akosyakov When I hover over `JavaSE-14` in the status bar, the tooltip points to the correct java executable (version 15). That's why I don't believe in @svenefftinge's guess. Maybe the Java plugin just displays the wrong version but uses the correct one?

Not for me. It says "Configure Java Runtime" in the tool tip.

**Comment by mkarg** [comment]
> I think Sven is right, you can give a try to configure [java.home](https://open-vsx.org/extension/redhat/java#java-tooling-jdk) and [java.configuration.runtimes](https://open-vsx.org/extension/redhat/java#project-jdks) in your workspace settings or better modify the docker image, commit and start a new workspace.

Unfortunately that does **not** fix the problem. SDK man installed JDK 16-ea into `/home/gitpod/.sdkman/candidates/java/current` and correctly changed `JAVA_HOME` to exactly that path. Then I modified `setting.json` like this...
```json
...
"java.home": "/home/gitpod/.sdkman/candidates/java/current",
"java.configuration.runtimes": [
    {
        "name": "JavaSE-16",
        "path": "/home/gitpod/.sdkman/candidates/java/current",
        "default": true
    }
],
...
```
...and gave Theia a restart (as it requests it), which changes the tooltip text when hovering over `JavaSE-14` in the status bar, but the Status bar *still* says `JavaSE-14` and the language server still is unable to process the `record` keyword, so I assume it really thinks this *is* Java 14 only.
![image](https://user-images.githubusercontent.com/1701815/105573702-aff0c400-5d5f-11eb-8d74-dd96a60492ee.png)
![image](https://user-images.githubusercontent.com/1701815/105573711-bed77680-5d5f-11eb-94f5-a0a99b61fa24.png)
In fact, after the restart, `java.home` is even **gone** form `settings.json` -- seems something removes it (possibly because it is already the same value as `JAVA_HOME`)!

The language server says this in the log:
```log
!ENTRY org.eclipse.jdt.ls.core 4 0 2021-01-23 08:51:14.471
!MESSAGE Runtime at '/home/gitpod/.sdkman/candidates/java/current' is not compatible with the 'JavaSE-16' environment
```
