### ISSUE TITLE
Cant sign up after account deletion

### ISSUE THREAD

**Issue by Sylack-lab** [gitpod-io/gitpod#2645]
### Describe the bug

I deleted my gitpod account because it was the wrong user, and when i tried logging back it would just refresh the page. 
(At first, before deleting, it would log me back into the main acc rather than giving me an oauth window.)

### Steps to reproduce

1. Log in with a github account to gitpod
2. Delete the account
3. Log in again with another github account
### Expected behavior

To log me in with the proper account

### Additional information

![image](https://user-images.githubusercontent.com/48862659/103482389-ed0d0a80-4de0-11eb-88b5-43dbe6fb8e84.png)

### Example repository

https://github.com/Sylack-lab/OSSU

**Comment by Sylack-lab** [comment]
I fixed this issue by making an account in incognito mode, and injecting the cookie values into the main window

**Comment by sr229** [comment]
You need to clear your cookies. See if that helps.

**Comment by csweichel** [comment]
This looks like we're missing some proper handling of the deletion case. Instead of throwing the error/logging the issue, we should try and log out.

**Comment by Sylack-lab** [comment]
> You need to clear your cookies. See if that helps.

I had already tried that before, I took all cookies and retried but still gave me an error.

**Comment by Sylack-lab** [comment]
> This looks like we're missing some proper handling of the deletion case. Instead of throwing the error/logging the issue, we should try and log out.

I was thinking of that, Logging out shouldnt be an error, hope this gets fixed soon!

Closing issue.

**Comment by AlexTugarev** [comment]
I start investigating this. 
Just checked, it works in a preview environment. 
Maybe the logs will show what went south during deletion of account.
The `User is deleted` error is not expected, as after (a successful) deletion it should also clear the session cookie. Only if the session cookie isn't deleted, this might occur.

**Comment by AlexTugarev** [comment]
@Sylack-lab, deleting cookies should log you out from gitpod.io very effectively. Afterwards you should be able to log in (sign up) with (another) Github (account).

> I had already tried that before, I took all cookies and retried but still gave me an error.

**Comment by AlexTugarev** [comment]
@Sylack-lab, please visit https://gitpod.io/api/logout in order to resolve the situation manually.

I just went through the process of account deletion on gitpod.io/settings and realized, that it's quite easy to end up in this situation. After deletion of the account it's required to select the `Finish`  button in order to log out, otherwise the session cookie will remain. This isn't ideal, as you can just close the tab, or navigate to any other location.

We need to have a proper handling for deleted accounts.

**Comment by Sylack-lab** [comment]
> @Sylack-lab, please visit https://gitpod.io/api/logout in order to resolve the situation manually.
> 
> I just went through the process of account deletion on gitpod.io/settings and realized, that it's quite easy to end up in this situation. After deletion of the account it's required to select the `Finish` button in order to log out, otherwise the session cookie will remain. This isn't ideal, as you can just close the tab, or navigate to any other location.
> 
> We need to have a proper handling for deleted accounts.

Thank you!

**Comment by AlexTugarev** [comment]
'reopening as it's not yet deployed on gitpod.io.

**Comment by gtsiolis** [comment]
Let's close this! This will be part of the upcoming [January 2021](https://github.com/gitpod-io/gitpod/milestone/8) release. 🚢 

Thank you @AlexTugarev for working on this! 🙏 

See also [relevant discussion](https://typefox.slack.com/archives/CGVQAPNPL/p1610528818389500) (internal).

/cc @akosyakov @JanKoehnlein @svenefftinge @csweichel
