### ISSUE TITLE
[VS Code] Extensions market place not working

### ISSUE THREAD

**Issue by MeStrak** [gitpod-io/gitpod#2646]
### Describe the bug
I can't access the VS Code extensions marketplace - I get the error:
` We cannot connect to the Extensions Marketplace at this time, please try again later.`

![image](https://user-images.githubusercontent.com/31989238/103484782-49742800-4de9-11eb-8266-8d1f6116e426.png)

### Steps to reproduce
Open GitPod VS Code, navigate to the Extensions tab - error message is displayed.

### Expected behavior
List of extensions should be visible.

### Additional information
It was working earlier today , but I haven't been able to use it for the last few hours.

### Example repository
https://github.com/MeStrak/catkin

I have the issue on any workspace I open. For example: a84ba327-2928-4ca7-8575-a33b5d60dfcd

**Comment by sr229** [comment]
Gitpod uses OpenVSX IIRC so try to see if you can connect right now. If it still doesn't work then infra would have to check it out.

**Comment by csweichel** [comment]
Thank you for reporting this.
Indeed this seems to have been an issue with open-vsx.org. It's working again though, hence closing for now.

**Comment by MeStrak** [comment]
Thanks, I can now install them but still have some unexpected behaviour. I'm not sure if it's a bug or an issue with my config, so I created #2650.

**Comment by tjmonsi** [comment]
I think it is down again @csweichel :(

**Comment by csweichel** [comment]
I am afraid so. There is an on-going incident that's currently being resolved (https://www.eclipsestatus.io/incidents/1hs2z6hznqhl)
