### ISSUE TITLE
Confirm before closing the IDE

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2648]
### Problem to solve

Users accidentally close the browser tab (workspace) when trying to close an editor file using a common keyboard shortcut (`CMD+W`/`CTRL+W`).

See also relevant issue (https://github.com/gitpod-io/gitpod/issues/411) and discussions[[1](https://typefox.slack.com/archives/CGVQAPNPL/p1604305141180400)][[2](https://typefox.slack.com/archives/C01BT930RV1/p1609300808000100)] (internal). /cc @akosyakov 

### Proposal

**Option A**: Use a [simple dialog](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#simple-dialogs) to confirm closing the tab.
**Option B**: Use the [`beforeunload`](https://html.spec.whatwg.org/multipage/indices.html#event-beforeunload) event to show a warning prompt. See also [_Unloading documents_](https://www.w3.org/TR/html52/browsers.html#unloading-documents) in HTML spec.

| A | B |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/103518620-c56b8000-4e7c-11eb-99ca-967733d48d61.png) | ![image](https://user-images.githubusercontent.com/120486/103518627-c7354380-4e7c-11eb-94e7-2491fffdf423.png) | 

In both cases, this could be triggered only when the user has made any changes to any files. FWIW, this is also a common approach with online IDEs like [GitLab's Web IDE](https://docs.gitlab.com/ee/user/project/web_ide/), [Google's Cloud Shell](https://cloud.google.com/code/docs/shell/quickstart), and more.

**Comment by svenefftinge** [comment]
I have seen and heard about this so often, it should be adressed ASAP.
Technically I don't think we can to "Option A" because AFAIK we cannot block the `unload` programmatically.

> In both cases, this could be triggered only when the user has made any changes to any files. 

I think we should trigger it always, because even if you don't loose state it is annoying having to going back. 
Maybe we can detect if the unload happend because of the keyboard shortcut and only ask in such cases?

**Comment by svenefftinge** [comment]
related https://github.com/gitpod-io/gitpod/issues/2623

**Comment by akosyakov** [comment]
You can enable it in Theia by adding `"application.confirmExit": "always"` in your user settings. For Code it is not implemented yet in upstream: https://github.com/microsoft/vscode/issues/14710#issuecomment-723549399

**Comment by akosyakov** [comment]
Also ctlr+w used to be handled in Theia but seems to be broken by latest versions of Chrome or something, namely this code: https://github.com/eclipse-theia/theia/blob/39887bf9d05c29fedc9466db76ca0a58706a1a2a/packages/core/src/browser/common-frontend-contribution.ts#L959-L978

**Comment by gtsiolis** [comment]
Thanks for all the references @akosyakov! 🏀 

**thought**: This works as expected according to _Option B_ described above and looks good. 

**question:** If this (_setting default preferences_) is possible or a common approach for both Code and Theia, what do you think of setting this preference option to default to `always` for Gitpod, as this could make more sense for a web based version nested within browser tabs where closing tabs with a keyboard shortcut (`CMD+W`/`CTRL+W`) is a common pattern?

**Comment by akosyakov** [comment]
I don’t think we should change defaults. There would be other negative effects like a user won’t be able to close the window with a mouse without any actual dirty changes. In addition we don’t want to deviate from Code default settings for web target.

I think we should fix a bug in Theia and upgrade Code.

**Comment by svenefftinge** [comment]
I do believe we should change the default to ask, because the behavior in the web version is different.

**Comment by svenefftinge** [comment]
closed in favor of #2674
