### ISSUE TITLE
rpc error: code = InvalidArgument desc = cannot pull base image: failed to register layer: Error processing tar file(exit status 1): Container ID 243184 cannot be mapped to a host ID51a055555f2c

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#2649]
### Describe the bug

Originally reported here: https://community.gitpod.io/t/cannot-pull-base-image/2412

### Steps to reproduce

1. https://gitpod.io/#https://github.com/trustwallet/wallet-core/pull/1227
2. Image appears to start pulling successfully
3. But then it fails with:

<img width="1552" alt="Screenshot 2021-01-04 at 10 11 18" src="https://user-images.githubusercontent.com/599268/103519334-a61d2480-4e75-11eb-9195-68f9d0068eac.png">

### Expected behavior

Pulling should work, or Gitpod should clearly indicate when the image type is unsupported (and also explicitly show which image types are supported, i.e. Ubuntu, Debian, Alpine, AmazonLinux)

### Additional information

Test with & without "Registry Facade" -- same problem.

### Example repository

https://github.com/trustwallet/wallet-core/pull/1227

**Comment by csweichel** [comment]
We can only build images that use UIDs < 65534 due to user namespaces.

**Comment by hewigovens** [comment]
how to solve this then?

**Comment by csweichel** [comment]
I'm afraid at the moment the only way is  to use an image wit UIDs below 65534

**Comment by svenefftinge** [comment]
See also https://circleci.com/docs/2.0/high-uid-error/

**Comment by jankeromnes** [comment]
Aha, great, the CircleCI docs propose a solution similar to what I was about to suggest.
