### ISSUE TITLE
[VS Code] Help with extensions - config issue or bug?

### ISSUE THREAD

**Issue by MeStrak** [gitpod-io/gitpod#2650]
Hello there,

I previously reported #2646 as I couldn't install extensions, and that is now working.

However, when I install an extension  the `.gitpod.yml` file isn't updated with the name of the installed extension, and I don't think the extensions are being installed from the right registry. I'm not sure if I have a basic configuration setting wrong, or if this is a bug. Would you be able to take a look?

# Expected
From your screencast (https://www.gitpod.io/docs/vscode-extensions/#vs-code-extensions) I can see that extensions are being installed from OPEN VSX REGISTRY:
![image](https://user-images.githubusercontent.com/31989238/103531987-54c76200-4e82-11eb-9aa5-484fced09d72.png)

# Actual
However when I run GitPod with VS Code I think that extensions are installed from the MARKETPLACE instead of the registry:
![image](https://user-images.githubusercontent.com/31989238/103532170-ad96fa80-4e82-11eb-9769-1bbb95729628.png)

I am also not prompted to install for project or user as shown in the user guide:
![image](https://user-images.githubusercontent.com/31989238/103532280-d919e500-4e82-11eb-9789-0f51c0e563b8.png)

Thanks!

**Comment by svenefftinge** [comment]
The extensions are pulled from Open VSX in both IDEs. But for vscode we currently don't automatically update the `.gitpod.yml`. You'll have to do that manually for now.  The syntax is
```
vscode:
  extensions:
    - <publisher-id>.<extension-id>@<version>
```

The version is optional. If you leave it out you get the latest version.

The functionality to install extensions per user vs. per workspace is also not yet implemented for vscode.

**Comment by MeStrak** [comment]
Thanks @svenefftinge, I didn't realise that it's not yet implemented for VS Code. I've switched back to Theia for now.

**Comment by akosyakov** [comment]
Installing from gitpod yml should work already in Code. The rest is coming this month.
