### ISSUE TITLE
[integration tests] Automate low-effort tests from the manual test plan

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2658]
At the moment we do a lot of manual testing based on [our test plan](https://github.com/gitpod-io/gitpod/blob/master/dev/manual-tests/testsuite.yaml). With the advent of [Gitpod's integration tests](https://github.com/gitpod-io/gitpod/pull/2617), we should strive to automate a good part of that test plan.

Part of this task is to decide which tests to automate. Criteria to consider are:
- _implementation effort vs manual test effort_: if it's easy to test manually, but hard to put into code (e.g. an end-to-end test using playwright), we're probably better of testing manually
- _expected brittleness_: if a test would depend on many external "fixtures" it might not be a good candidate
- _common case_: if the test tests a popular use-case, we should consider automating it to make us find out quicker if it breaks

Prerequisite: #2617 is merged

**Comment by geropl** [comment]
There is some progress made on:
 - https://github.com/gitpod-io/gitpod/pull/3260
 - https://github.com/gitpod-com/gitpod/pull/5177

Which stabilizes the tests and added some workspace tests, but also showed the current limits:
 - gp is not usable atm: https://github.com/gitpod-io/gitpod/issues/3162
 - user namespaces in workspace container: https://github.com/gitpod-io/gitpod/issues/3380
 
 As both issues are scheduled for this cycle we're going to pause efforts here until those are resolved.
