### ISSUE TITLE
Add redirect if `www` is missing

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#2659]
### Describe the bug
- If I'm using a URL without "www", I should be redirected to the correct page. Otherwise, this causes error messages and frustrated users. 

- Twitter always shortens a link, thereby linking to a page causes an error message (https://twitter.com/tommyhpratama/status/1346112148703834113)

according to @nisarhassan12 this is probably something that has to be implemented on the server side (https://github.com/gitpod-io/website/issues/842#issuecomment-739048822)

**Comment by geropl** [comment]
Yes, adding a error handler for 404 here should do the trick: https://github.com/gitpod-io/gitpod/blob/master/chart/config/proxy/lib.locations.conf#L45

**Comment by AlexTugarev** [comment]
@geropl, 'you mean an `error_page` inside of the `location /`, right?
I'm wondering how to verify 🤔
