### ISSUE TITLE
[GCP installer] PROJECT_ID is none even if set it

### ISSUE THREAD

**Issue by ryo-egch** [gitpod-io/gitpod#2661]
I tried to install gitpod using gcp installer, https://github.com/gitpod-io/gitpod/tree/master/install/installer
```
docker run --rm -it \
    -v $HOME/gitpod-gcp-installation:/workspace \
    -e PROJECT_ID=MY_PROJECT_ID \
    -e REGION=asia-northeast1 \
    eu.gcr.io/gitpod-core-dev/install/installer:dev scripts/gcp.
```

after entering verification code which is given after GCP login, it said  * current project is [None]* and script finished without setting anything.

```
    You are now logged in as [EXAMPLE@MY_DOMAIN].
Your current project is [None].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID


Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components update



To take a quick anonymous survey, run:
  $ gcloud survey

Updated property [core/project].
```

In command I already set MY_PROJECT_ID, and also execute command as is said on console 
> $ gcloud config set project MY_PROJECT_ID 
  
but nothing changed.

I don't know what is problem

**Comment by corneliusludmann** [comment]
I guess you used the instructions of this readme file, right? https://github.com/gitpod-io/gitpod/blob/master/install/installer/README.md

It seems that this readme file is outdated. I'll gonna remove this file. Please follow the instructions you'll find in our docs: https://www.gitpod.io/docs/self-hosted/latest/install/install-on-gcp-script/

Please re-open and ping me if this issue still happens with the instructions in the docs.
