### ISSUE TITLE
Localstorage Quota for Gitpod appears to be exceeded

### ISSUE THREAD

**Issue by CyberiumShadow** [gitpod-io/gitpod#2662]
### Describe the bug
Upon attempting to launch a Gitpod workspace, the workspace instead appears to stall at the Gitpod loading screen.
Checking the developer console via F12 shows the following errors

```
Failed to start the frontend application. [index.js:87](webpack:///src-gen/frontend/index.js)

DOMException: The quota has been exceeded. [index.js:89](webpack:///src-gen/frontend/index.js)
```

### Steps to reproduce
Not sure as to steps to reproduce, but it appears to involve launching numerous new workspaces over an extended period of time

### Expected behavior
Expected behavior is that the workspace successfully launches without stalling

### Additional information
```
Failed to start the frontend application. [index.js:87](webpack:///src-gen/frontend/index.js)

DOMException: The quota has been exceeded. [index.js:89](webpack:///src-gen/frontend/index.js)
```

**Comment by corneliusludmann** [comment]
Thanks for reporting.

Link to community discussion: https://community.gitpod.io/t/unable-to-load-gitpod-anymore/2404?u=corneliusludmann

**Comment by CyberiumShadow** [comment]
#2712 supersedes this issue :)
