### ISSUE TITLE
latest version for self install

### ISSUE THREAD

**Issue by yyexplore** [gitpod-io/gitpod#2665]
Hello

I'm so confused that what's the  latest version for self installation, there's even no any tags  in this project !

and how to install with helm ?   no document either !

**Comment by corneliusludmann** [comment]
Hi @yyexplore!

Sorry, for the confusion. the latest official self-hosted release is `0.5.0`. However, this version is pretty old and has some known bugs. We're working currently on the `0.6.0` release that will be published in a few days. I would suggest to wait for this release.

**Comment by yyexplore** [comment]
Thanks!  

Looking forward to the version `0.6.0`
