### ISSUE TITLE
Not loading repositories

### ISSUE THREAD

**Issue by lzcristian** [gitpod-io/gitpod#2668]
### Describe the bug
Every time I press the Gitpod button from the Github repository, it sends me to a login page. After I put my username and password it gives me these messages and doesn't continue. Even from Gitpod when I try to push the code, it asks for permission, so it sends me to the Gitpod login page and it happens the same thing when I try to login. I have to do a lot tries and going through Gitpod directly to access other saved repositories and then go back to GitHub and access the one I want, but still doesn't wants to push the code.

**"We are having trouble parsing your context"

"What‽
Your browser did something unexpected. Please contact us if the problem persists."**

### Example repository
https://github.com/lzcristian/jasmine_boilerplate.git

**Comment by AlexTugarev** [comment]
> We are having trouble parsing your context

That sounds like, the context URL isn't supported. Read more on this: https://www.gitpod.io/docs/context-urls/

In your example, this should work fine: gitpod.io/#https://github.com/lzcristian/jasmine_boilerplate

**Comment by AlexTugarev** [comment]
> Every time I press the Gitpod button from the Github repository, it sends me to a login page.

It does so every time?

Have you checked the browser settings? That would mean, your browsing session isn't persisting cookies, or is a temporary session in general?

**Comment by AlexTugarev** [comment]
> but still doesn't wants to push the code.

Please check the granted permissions on https://gitpod.io/access-control/
Do you have `write` permissions granted for GitHub?
