### ISSUE TITLE
SSL Cert expired

### ISSUE THREAD

**Issue by erasmuswill** [gitpod-io/gitpod#2671]
### Describe the bug
The SSL cert for gitpod.io has expired

### Steps to reproduce
Try sign in at https://gitpod.io/login/

### Expected behavior
Able to sign in and start a pod (was getting exit 42 on repos a few minutes ago)

### Additional information
https://gitpod.io/login/ has an expired cert
https://www.gitpod.io/ seems fine

**Comment by Michaelhobo** [comment]
+1

**Comment by svenefftinge** [comment]
Thanks for the outreach. Issue has been solved.
