### ISSUE TITLE
Exit status 42

### ISSUE THREAD

**Issue by erasmuswill** [gitpod-io/gitpod#2672]
### Describe the bug
When trying to start a pod for a new repo, I get the following:
<div> cannot initialize workspace: cannot initialize workspace: exit status 42</div>
I have bypassed HSTS to work around the expired SSL certificate.

### Steps to reproduce
Try to launch a repo you have not launched before.
It hangs on Pulling docker images and then shows the error as above

### Expected behavior
The repo should launch a pod

### Additional information
I am still able to launch existing pods, I just can't create new ones.

### Example repository
https://github.com/gitpod-io/gitpod
Any repo that you do not have a pod for.

**Comment by notbotman** [comment]
Yes facing the same

![image](https://user-images.githubusercontent.com/74244707/103741631-6db94a00-501f-11eb-9755-6977f93fadbf.png)

**Comment by svenefftinge** [comment]
Hey, thanks for reporting this. The issue has been resolved now.
