### ISSUE TITLE
Unable to access Gitpod Dashboard - connection is not secure

### ISSUE THREAD

**Issue by bravoalpha79** [gitpod-io/gitpod#2673]
### Describe the bug
When trying to visit https://gitpod.io, Chrome raises this warning:

![image](https://user-images.githubusercontent.com/45522344/103740915-6d598880-4ff8-11eb-838a-5bd852eaefd4.png)

Chrome is up to date, Gitpod extension is installed.

At least three more people confirmed the exact same issue.

### Steps to reproduce
1. Go to https://gitpod.io
2. Try to log in to your account using GitHub.

### Expected behavior
Gitpod Dashboard provides a secure connection and no error is raised.

### Additional info
One student tried Safari and Firefox and is getting a similar result.

**Comment by svenefftinge** [comment]
Thanks for reporting. We have fixed the issue.

**Comment by bravoalpha79** [comment]
Thank you!! 🙂
