### ISSUE TITLE
[Code] Support user-level extensions 

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#2688]
Gitpod with enabled  default **Theia** editor allows to install some extension or extension pack globally for account.

![image](https://user-images.githubusercontent.com/1110697/103873037-e24fbf80-50d7-11eb-87e9-bae33ee01a85.png)

I'd like to see the same ability for Code editor.

I've found a workaround how install an extension globally but it requires to switch Theia editor each time when I want to install it globally for Code editor.

**Comment by svenefftinge** [comment]
Should "Just Work" with https://github.com/gitpod-io/gitpod/issues/3070

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/3110
