### ISSUE TITLE
Chart docker-registry not found n https://kubernetes-charts.storage.googleapis.com/  when try to deploy gitpod 0.5.0 with docker-compose 

### ISSUE THREAD

**Issue by suunavier** [gitpod-io/gitpod#2690]
Save error occurred:  could not find : chart docker-registry not found in https://kubernetes-charts.storage.googleapis.com/
Deleting newly downloaded charts, restoring pre-update state
Error: could not find : chart docker-registry not found in https://kubernetes-charts.storage.googleapis.com/

**Comment by Tiller431** [comment]
This doesn't seem to be fixed in the docker image for gitpod yet. (eu.gcr.io/gitpod-core-dev/build/gitpod-k3s)
