### ISSUE TITLE
Code/syntax highlighting doesn't work

### ISSUE THREAD

**Issue by bravoalpha79** [gitpod-io/gitpod#2695]
### Describe the bug
Similar to closed issue #2444: 
When the workspace is loaded, the code is displayed as plain white text, with no syntax highlights.

![image](https://user-images.githubusercontent.com/45522344/103897288-96127880-50f3-11eb-8bbc-d7647bb97d4d.png)

Restarting the workspace and logging out/in of Gitpod didn't help.

### Steps to reproduce
Affected workspace: https://e2eb8b73-0e99-4f1b-9108-81386ff2ae9a.ws-eu03.gitpod.io/#/workspace/curl-command-line

### Expected behavior
Code highlight works.

**Comment by bazmac81** [comment]
Please see URL of affected workspace. Code not recognised and ports not being detected.

https://ebcb2d05-9fde-43d7-9b60-bbd0bafc39fc.ws-eu03.gitpod.io/#/workspace/placro

**Comment by PaoloAlbanese** [comment]
This workspace is also affected
also reported in #2713 
workspace:
bd9c91cd-2953-41f2-b11f-247eba7186df
PaoloAlbanese/cocktails - master

all the code is just black and white
shortcuts like ctrl+/ don't comment outs selection
the ports are not available, they just read:
8080– detecting...
3306– detecting...
33060– detecting...

**Comment by PaoloAlbanese** [comment]
Mine on #2713 works now

**Comment by mateuszniechwiej** [comment]
I have a similar issue.No syntax highlights on the code.

https://dff35c61-31c4-42af-b5e6-f09cd884a8c0.ws-eu03.gitpod.io/#/workspace/table

![image](https://user-images.githubusercontent.com/72758272/105646038-7621d980-5e95-11eb-9c5f-8ff7f7f9fe6d.png)

**Comment by inglisj** [comment]
My workspace too is affected with this. 
https://a006f1fe-a38b-4538-b86b-c9636c2c2dba.ws-eu03.gitpod.io/

**Comment by guiMendel** [comment]
same here 
https://cbbf34c9-6fb9-4f64-a392-77bb9428a9b5.ws-eu03.gitpod.io

**Comment by mateuszniechwiej** [comment]
Hi ! I've managed to fix this problem by turning off Kaspersky Security Cloud.

**Comment by nisarhassan12** [comment]
I have encountered the same issue: https://c3bb1940-aa22-4467-b066-32c73fcccbf7.ws-eu03.gitpod.io/#/workspace/devxconf.org

**Comment by nisarhassan12** [comment]
I just tried stopping and restarting the workspace and it fixed the problem for me.

**Comment by HMTRIVEDI** [comment]
I have same problem :https://a37fd37e-2860-454b-8621-2b4eb591d8c8.ws-eu03.gitpod.io/#/workspace/TASKERS
auto closing tags not working

**Comment by dpolivaev** [comment]
same here, see screen shot including errors on the console
![msedge_2021-02-06_19-27-35](https://user-images.githubusercontent.com/1558052/107126698-939d6d00-68b1-11eb-8f64-5074a72e610e.png)

https://gitpod.io/#snapshot/d7417464-cf18-4aba-84fe-543715cc98e1

**Comment by Ri-Dearg** [comment]
I often have this issue with pretty much any workspace. Sometimes it works, sometimes it does not. There's no consistency as to why. Often, all gitpod them icons do not load either.

- I have removed extensions
- I minimised my dockerfile commands
- I changed all settings to default.

Still the issue persisted.

However, I turned off Adblock Plus and Ghostery on Chrome, extensions for blocking ads and trackers, and the rate of the issue occurring has gone down quite a lot.
I don't know why they seem to have an impact but they do. Previously I culd only load up a workspace successfully 1/5 attempts, now its the opposite. I fail 1/5 attempts. I recommend people disable their blockers to see if there's any impact.

**Comment by akosyakov** [comment]
There are timeouts on downloading extensions (quite high though like 5s per an extension). Maybe blockers lead to hitting such timeouts.

**Comment by dpolivaev** [comment]
I have one computer running windows and one computer running linux sharing the same internet connection.
On my linux machine syntax highlighting works fine in all browsers.
On my windows machine syntax highlighting does not work at all.

**Comment by Yannl** [comment]
Hi, I have the same problem here on all workspaces that I launched for the last 5 days. 
Example workspace: https://olive-cattle-s3uc7gc3.ws-eu03.gitpod.io/

Screenshot:
![image](https://user-images.githubusercontent.com/6842725/115088711-14f82800-9f11-11eb-8c19-428fd3d38f79.png)

**Comment by Yannl** [comment]
In addition to above.

It does work on Android smartphone with Chrome for Android.

It didn't work on windows 10 computer with Firefow or Chrome or Edge. Same 
First I disabled all browser extension and updated browsers to latest version. > No change
Then I disabled Kasperky Antivirus > it worked. 

Lastly when it it works I still get the above error message: "Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'https://olive-cattle-s3uc7gc3.ws-eu03.gitpod.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by akosyakov** [comment]
> Then I disabled Kasperky Antivirus > it worked.

Could it prohibit some network traffic like wasm files?

```
Lastly when it it works I still get the above error message: "Access to XMLHttpRequest at 'https://open-vsx.org/vscode/gallery/extensionquery' from origin 'https://olive-cattle-s3uc7gc3.ws-eu03.gitpod.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."
```

It is unrelated. It is misconfigured Open VSX registry, but we work it around but doing the request on the backend.

**Comment by Yannl** [comment]
@akosyakov  Sorry if my previous message was not clear. Yes the CORS error message is not related. It was just to report it as well.

If anyone want to keep using Kaspersky with Gitpod, the relevant message turned out to be :

`Refused to connect to 'wss://gc.kis.v2.scr.kaspersky-labs.com/[...]%2Fwebview-black-firefly-i66xqqyn.ws-eu03.gitpod.io%2Fout%2Fvs%2Fworkbench%2Fcontrib%2Fwebview%2Fbrowser%2Fpre%2Ffake.html%3Fid%3D7467c924-0f71-4e53-9567-d71b2928ef03&nocache=1618858835990' because it violates the following Content Security Policy directive: "default-src 'unsafe-inline' 'unsafe-eval' data: https: http: blob: https://webview-black-firefly-i66xqqyn.ws-eu03.gitpod.io". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.`

My current workaround in Kaspersky 2020 : 
1. Go to : Settings > Networks settings > Traffic processing 
2. Disable  : Inject script into web traffic to interact with web pages.

(source = https://community.kaspersky.com/kaspersky-total-security-14/error-in-local-page-in-firefox-can-t-connect-with-the-server-at-ws-ff-kis-v2-scr-kaspersky-labs-com-etc-2829)

**Comment by code2k13** [comment]
I was able to reproduce this issue today with Edge running on Windows 11. Chrome works fine.

**Comment by axonasif** [comment]
> I was able to reproduce this issue today with Edge running on Windows 11. Chrome works fine.

Hey @code2k13, it's probably due to some extension or browser config of yours on Edge. You might find something interesting on your `console logs`.

**Comment by Harinathlee** [comment]
Disable or uninstall the "Color Identifiers" extension and reload the workspace. It worked for me.
