### ISSUE TITLE
ErrImagePull when i try to install Gitpod 0.6.0beta1 or newer

### ISSUE THREAD

**Issue by bergerem** [gitpod-io/gitpod#2697]
### Describe the bug
When i install gitpod with version 0.6.0beta1 or newer, i can't get the images. It says ImagePullBackOff and ErrImagePull.

### Steps to reproduce
Install gitpod 0.6.0beta1 or newer.

### Expected behavior
Helm installs the gitpod version without any errors.

**Comment by yyexplore** [comment]
please try   eu.gcr.io/gitpod-io/self-hosted

**Comment by geropl** [comment]
Thx @bergerem for reporting, should be fixed with https://github.com/gitpod-io/gitpod/commit/9667dcafb7ba1caff5f4304aa3e5ee56fe4b5c70 / `0.6.0-beta5`.

**Comment by bergerem** [comment]
Nah still doesn't work.
