### ISSUE TITLE
build failed: cannot push workspace image: dial tcp_ lookup *.mysubdomain.mydomain.com: no such host

### ISSUE THREAD

**Issue by bergerem** [gitpod-io/gitpod#2698]
Hi, in the meantime I get Gitpod to display the page. But now I get an error message when I try to create a workspace:

`Error: build failed: cannot push workspace image: dial tcp_ lookup *.mysubdomain.mydomain.com: no such host`
(url is different)

Also, I keep getting the error with the server and ws-manager-bridge:
`Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778`

**Comment by csweichel** [comment]
The `Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778` issues are non-consequential. They indicate the failure of the distributed tracing library, a diagnostics feature that looks like it's too loud when it doesn't work.

From afar it looks like the image-builder cannot reach the configured image registry. Are you using the built-in registry? If not, is the configured registry reachable from the image-builder?

**Comment by bergerem** [comment]
I tried the build-in and my own registry. Do i need SSL Certs for both?

**Comment by csweichel** [comment]
In self-hosted v0.6.0 you'd need SSL certs in both cases. For v0.5.0 not necessarily.
The lookup issue is independent of certs though.

Are you sure your cluster can reach that domain, e.g. the nameservers are setup properly?

**Comment by bergerem** [comment]
I think so. It can reach the docker registry and create an Image and a workspace pod can be created, but it seems, that it cant connect to the new workspace-pod, when i try to use the workspace.

For example: I create a new workspace. It will be created and a ws-pod starts, but when i try to open the workspace, i got this error.

**Comment by jgallucci32** [comment]
@bergerem Which gitpod service (i.e ws-daemon, ws-manager, etc.) gives the connection refused error?

**Comment by bergerem** [comment]
ws-manager-bridge and ws-sync
