### ISSUE TITLE
Github PR merge error not handled

### ISSUE THREAD

**Issue by simark** [gitpod-io/gitpod#27]
**Describe the bug**
When merging is not possible, because a review is necessary, for example, the Merge button is green but clicking on it does nothing.  In the Javascript console, an error is printed:

    Error: {"message":"At least 1 approving review is required by reviewers with write access.","documentation_url":"https://help.github.com/articles/about-protected-branches"}

**To Reproduce**
- Open a PR on the Theia repo, make sure nobody approves it so the merge button on Github is disabled
- Try to merge this PR from gitpod

**Expected behavior**
I see two possible behaviors:
1. Grey-out the button, in some hover text explain why the button is greyed out.
2. When clicking the Merge button, if there is an error, show it the standard way errors are shown in Theia.

**Comment by akosyakov** [comment]
We are switching to VS Code and https://www.gitpod.io/docs/feature-preview/#default-ide for PR reviews on gitpod.io In order to enable VS Code follow https://github.com/microsoft/vscode-pull-request-github
