### ISSUE TITLE
`Open Browser` blocks Gitpod

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#270]
Gitpod is blocked when starting Theia with `Open Browser`.

Steps to reproduce:
 - Open Theia `master` in Gitpod:  [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/theia-ide/theia)
 - Wait for the build.
 - Start Theia with `yarn --cwd ./examples/browser start --hostname 0.0.0.0 --port 3000`
 - Click on `Open Browser`.
 - My Gitpod client is frozen.

**Comment by kittaakos** [comment]
The same issue when I'm opening a workspace, or switching to another workspace in Theia. The Gitpod client is blocked.

**Comment by kittaakos** [comment]
I have figured it out, and it was a problem on my side.

Workaround: I had to disable the Grammarly extension for Chrome.

**Comment by hakeem1106** [comment]
Thank you. This helped me alot.
