### ISSUE TITLE
Allow users to assign static IPs to dev environments

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#2700]
### Problem to solve

In some use cases, it could be useful to allows users to assign static IPs to dev environments.

This could be a feature in one of the paid tiers.

See also [relevant topic](https://community.gitpod.io/t/recommended-way-to-connect-to-cloud-hosted-database/2445) in `community.gitpod.io`. /cc @nicksilver

**Comment by csweichel** [comment]
How would this work from a UX perspective?
- Is this a manual step that you'd repeat for each workspace?
- Is there a set of IP addresses and when you start a workspace we'd choose one of "your IP's" at random, thereby limiting the number of concurrently running workspaces to the number of available IP addresses?

It's also worth noting that IP addresses are a rare resource. It's unlikely that we can reserve one/some per user.

**Comment by gtsiolis** [comment]
> How would this work from a UX perspective?

I'd think as something similar to the flow used in allocating a floating IP address to an instance within OpenStack, see [relevant docs in OpenStack](https://docs.openstack.org/horizon/victoria/user/configure-access-and-security-for-instances.html#allocate-a-floating-ip-address-to-an-instance). I can add some mockups if needed to visualize this as long as this is technically possible or something we would aim for adding.

> Is this a manual step that you'd repeat for each workspace?

I'd say yes. This could make sense for pinned or favorite workspaces that don't get deleted according to the [garbage collection](https://www.gitpod.io/docs/life-of-workspace/#garbage-collection).

> Is there a set of IP addresses and when you start a workspace ... 

I'd say assigning a specific static IP address from a limited pool (3-5) per user, project, or team (in the future) to a workspace or a project. I was thinking of something like using an external load balancer for a specific project, user, or team (in the future) that would be able to use static IP allocation networking feature, see [relevant docs in Kubernetes](https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/). However, this strongly depends on the current architecture and could be impossible to support.

> It's also worth noting that IP addresses are a rare resource

Understood. That's one of the reasons I think this could make it only as a paid feature.

---

**question**: Do you think it could be possible, efficient, or something we would want in the future to assign specific static IPs a) to workspaces (dev environments) or b) a project and consequently to all workspaces opened for a project?  If not, feel free to close this @csweichel and take a look at the [original request](https://community.gitpod.io/t/recommended-way-to-connect-to-cloud-hosted-database/2445/7?u=gtsiolis) from the community in case you can provide any help. 🏀

**Comment by nicksilver** [comment]
I'll add a quick comment to this thread since I was the one who originally brought it up. In my case, even having a known range of IP addresses that I could whitelist would be really helpful. And, personally, I would be happy to pay for this feature.

**Comment by davidwindell** [comment]
@gtsiolis As a soon to be paying customer, we would really like to just have a list of IP addresses to whitelist as a start.

Is Gitpod.io run on GCP? If so, you could easily achieve this with a Cloud NAT gateway with static IP.

**Comment by RdeWilde** [comment]
Please provide a list of IP's or IP ranges to whitelist. Github provides it too, although the most actual list is available via their API.

The lack of whitelisting makes the cloud hosted option unavailable for companies using a firewall

**Comment by jmarbutt** [comment]
I would like this also, I just signed up but can't connect to my database

**Comment by akosyakov** [comment]
> I would like this also, I just signed up but can't connect to my database

Please try Gitpod Local Companion, it exposes services from Gitpod workspace on your localhost automatically: https://www.gitpod.io/blog/local-app We will be interested in the feedback.

**Comment by orellabac** [comment]
@akosyakov 
Gitpod Companion is great, but in my case I need static IPs to allow using gitpod from restricted environments

**Comment by orellabac** [comment]
In my case, I am working on from a Citrix VM. Access to other sites can be enabled but a fixed IP is needed as well as ports.

**Comment by svenefftinge** [comment]
Let's continue the discussion in [this ticket](https://github.com/gitpod-io/gitpod/issues/898), which is similar enough.

**Comment by atduarte** [comment]
We discussed this internally and realized the effort would be quite significant. It is indeed something we want to address, but unfortunately at this time, we don't have the capacity to execute.
