### ISSUE TITLE
Unable to set user environment variables for GitLab repos with nested groups

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#2702]
### Describe the bug

I can't set environment variable for nested groups, for instance, `nifty-panini/backend/gitpod-example`.
Gitlab allows to create nested groups and place repo at under needed group, it's very often use case.

So I wanna have ability set variables like `NPM_TOKEN` under root group to use this variable on all repos under group without need to set variable to each repo.

Currently I can't set variable due to some bug or it's not implemented. 

### Steps to reproduce

1. Go to Settings UI and set environment variable `BARFOO` with value `foobat` and `Organization/Repository` with value `nifty-panini/*` 
2. Open with GitPod with enabled Code editor by default by using link:
https://gitpod.io/#/https://gitlab.com/nifty-panini/backend/gitpod-example/-/tree/master/
3. echo `$BARFOO` to verify that environment variable is present.
4. BARFOO is not set

I've tested it on **Code / Theia** editor, **it doesn't work on both**.

### Expected behavior

I wanna set env variable for nested group on Gitlab and use this variable on each repo that belongs to the group.

### Additional information

![image](https://user-images.githubusercontent.com/1110697/103990355-bc8aef00-5199-11eb-9e93-daecfd8dc1c8.png)

Workspace about info: 
```bash
Version: 1.49.0
Commit: 20ded0d97c41cb686098d14b9e1f0533177300d1
Date: 2020-12-17T09:27:27.064Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284
Workspace ID: c81ce827-d4bb-4c8f-b989-6fb869640014
```

### Example repository

https://gitlab.com/nifty-panini/backend/gitpod-example/-/tree/master/

**Comment by vymarkov** [comment]
according to docs it should work without issues, but may be implementation should be adjusted to Gitlab use case

**Comment by corneliusludmann** [comment]
Related: #1358

**Comment by vymarkov** [comment]
it's still relevant

**Comment by clayton-bridge** [comment]
Any update on this? I'm having this same problem.
