### ISSUE TITLE
Add the ability to add an extension from extension view page to gitpod config

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#2703]
VS Code has the nice feature that allows to add extension to `devcontainer.json` or workspace recommendations.

I'd like to see the feature that allow to add extension to gitpod config by using GitPod.

It has a few benefits: 
- it very easy to do and doesn't require knowledge how to do it
- it encourages developers to add extensions if developers even don't know that they can add some extension to gitpod config (_it happened to me, I didn't know  long time that i can do it_)

![image](https://user-images.githubusercontent.com/1110697/103995122-adf40600-51a0-11eb-9253-6f2b43984d17.png)

I would like to hear your thoughts :)

**Comment by akosyakov** [comment]
Thank you for the issue, it is certainly on our list to add.
