### ISSUE TITLE
Support content store backed user storage in Code

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#2707]
In Code extensions can write files which are expected live beyond a single workspace (e.g. settings or caches). With the advent of the content store (#2001), we should make use of the content store for storing this data.

**Comment by svenefftinge** [comment]
It seems like this would be superseded by https://github.com/gitpod-io/gitpod/issues/3070.
Or are there any other aspects that this solution would help with that a sync service doesn't do?

**Comment by csweichel** [comment]
Removing from milestone due to #3070

**Comment by svenefftinge** [comment]
Closing this as superseded by #3070
