### ISSUE TITLE
CNAME is deleted when pulling a branch with a `docs` folder

### ISSUE THREAD

**Issue by RailRunner166** [gitpod-io/gitpod#271]
Gitpod deletes my CNAME (in my docs directory) when i pull, is there any way to disable this, or would this classify as a bug? I need to keep my cname, and it is really frustrating reverting those changes every time i pull from github

**Comment by svenefftinge** [comment]
Do you mean a file called `CNAME` gets deleted when you call `git pull`?
Is the repo public and how could I reproduce it?

**Comment by RailRunner166** [comment]
the repo is public, and yes that is what i mean, if you want to try it out, fork my repo at https://github.com/railrunner166/canvo, pull and make a change to the contents of the docs folder, then commit, the `CNAME` will be gone, i avoided it the second time when i noticed that it was deleted in the git staging area and discarded the deletion

**Comment by RailRunner166** [comment]
![image](https://user-images.githubusercontent.com/45880278/51772067-ab31a080-20b0-11e9-85c0-0a4f05433ce5.png)
is where i see it every time i pull, and i don't run `yarn docs` only once, either, i run it multiple times, so i would notice it if it was typedoc doing it

**Comment by RailRunner166** [comment]
nevermind, it is typedoc, sorry to waste your time friend :)

**Comment by svenefftinge** [comment]
no problem, you are welcome!
