### ISSUE TITLE
editor functionalities lost - ports not available

### ISSUE THREAD

**Issue by PaoloAlbanese** [gitpod-io/gitpod#2713]
hi
the colors and shortcuts in the text editor are not working anymore,

workspace:
bd9c91cd-2953-41f2-b11f-247eba7186df
PaoloAlbanese/cocktails - master

all the code is just black and white
shortcuts like ctrl+/ don't comment outs selection
the ports are not available, they just read:
8080– detecting...
3306– detecting...
33060– detecting...

is there a problem with the system?
![CaptureWS](https://user-images.githubusercontent.com/55405144/104022865-c53eed80-51b8-11eb-91fc-23c9231325c5.PNG)

**Comment by PaoloAlbanese** [comment]
works for me now

**Comment by mateuszniechwiej** [comment]
I have a similar issue.No syntax highlights on the code.
Also reported on #2695
https://dff35c61-31c4-42af-b5e6-f09cd884a8c0.ws-eu03.gitpod.io/#/workspace/table

![image](https://user-images.githubusercontent.com/72758272/105712010-300a5b80-5f11-11eb-87be-611c8c89497e.png)

**Comment by akosyakov** [comment]
closing as a duplicate
