### ISSUE TITLE
Vue.js Chrome Extension support

### ISSUE THREAD

**Issue by ivelin** [gitpod-io/gitpod#2715]
Currently the [Vue Chrome extension](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en) for developers cannot be used to debug vue apps running in a gitpod web app preview tab. The plugin is unable to detect that there is a vue app running in the browser tab. See screenshots.

![Screen Shot 2021-01-08 at 3 24 02 PM](https://user-images.githubusercontent.com/2234901/104065563-924f2680-51c5-11eb-886d-e61a0b6f89ac.png)
![Screen Shot 2021-01-08 at 3 24 08 PM](https://user-images.githubusercontent.com/2234901/104065593-9f6c1580-51c5-11eb-81b6-bfac567c7875.png)

**Comment by gtsiolis** [comment]
Hey @ivelin! Thanks for bringing this up! ✌️ 

This is a broader issue with [Vue DevTools](https://github.com/vuejs/vue-devtools/) which currently does not support iframes, see relevant issue in https://github.com/vuejs/vue-devtools/issues/353 (cc @Akryum) currently in RFC.

This issue also affects other platforms like Storybook (https://github.com/storybookjs/storybook/issues/1708) and more.

There are some workarounds for this at the moment, see a) https://github.com/vuejs/vue-devtools/issues/353#issuecomment-393555401, b) https://github.com/vuejs/vue-devtools/issues/353#issuecomment-727292083 (cc @JessicaSachs), and c) https://github.com/vuejs/vue-devtools/pull/361.

**In the meantime, Vue DevTools will work as expected when you open the live preview in a new tab or window.** FWIW, embedded live preview is not available yet for the Code editor (currently in [Feature Preview](https://www.gitpod.io/docs/feature-preview/#default-ide)) in case you tried that, see https://github.com/gitpod-io/gitpod/issues/2806 (cc @akosyakov).

Let's keep this open for further discussion and tracking any progress. 💬

**Comment by ivelin** [comment]
Thank you for the thorough response @gtsiolis .
