### ISSUE TITLE
Rename manifest.json to manifest.webmanifest

### ISSUE THREAD

**Issue by dragonDScript** [gitpod-io/gitpod#2717]
From MDN:
> The .webmanifest extension is specified in the Media type registration section of the specification (the response of the manifest file should return Content-Type: application/manifest+json). 

More docs on this: [MDN](https://developer.mozilla.org/en-US/docs/Web/Manifest),

Fixes #1445

**Comment by csweichel** [comment]
That would make us more standard compliant indeed. I reckon it's not an urgent change though, because:
> Browsers generally support manifests with other appropriate extensions like .json (Content-Type: application/json).

**Comment by dragonDScript** [comment]
> That would make us more standard compliant indeed. I reckon it's not an urgent change though, because:
> 
> > Browsers generally support manifests with other appropriate extensions like .json (Content-Type: application/json).

In my case, my browser doesn't detect Gitpod as a PWA. Not sure if it is for this reason tho. It'd be great if it worked.

**Comment by jankeromnes** [comment]
> In my case, my browser doesn't detect Gitpod as a PWA. Not sure if it is for this reason tho. It'd be great if it worked.

@dragonDScript When checking https://gitpod.io/workspaces/ in both Firefox & Chrome DevTools' `Application` tool, it seems that the manifest is well recognized, but both tools complain about a missing Service Worker.

It is my understanding that to be a fully-compliant (i.e. "installable") Progressive Web App, you should implement an offline-capable Service Worker.

Maybe the fact that https://gitpod.io/workspaces/ (i.e. the "dashboard") _doesn't_ have a Service Worker is the reason why you can't install it?

See also https://github.com/gitpod-io/gitpod/issues/1445 and https://github.com/gitpod-io/gitpod/issues/1982
