### ISSUE TITLE
Breakpoints not working when set in referenced class file

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#273]
**Describe the bug**
I tried to run and debug a Vaadin starter app in Gitpod, but were not able to set breakpoints in classes of referenced libraries.
I started the app in debug mode and attached a debugger to it. Breakpoints within my own code, i.e., code within my project, are working as expected, but breakpoints that I set within a referenced class file, e.g., `VaadinServlet` are marked as "Unverified Breakpoint" and are not triggered during debugging.

**To Reproduce**
* Go to https://github.com/Sandared/de.mocaan.vaadin.test 
* Start Gitpod
* Set a breakpoint in `VaadinServlet` init method
* Breakpoint is shown as empty circle instead of a red dot and hovering indicates an "Unverified Breakpoint"
* After Maven has finished type `mvn jetty:run`
* Attach debugger
* Open browser and navigate to 8080-yourpod
* Breakpoint in `VaadinServlet` is not hit, although it should, as it is always called when site is first opened.

**Expected behavior**
Setting of breakpoint in `VaadinServlet` should result in a normal breakpoint that is hit during debugging, instead of being ignored.

**Comment by Sandared** [comment]
I have to elaborate on the observed behavior. In the above mentioned project:
*  When I didn't start the application via `mvn jetty:run`, then I **can** set the breakpoint in `VaadinServlet` as in every other file and it appears as a red dot. However, it is not hit when I start the application, attach a debugger and then open a browser window for 8080-yourpod
* When I started the application and **then** try to add a breakpoint, then I get the above mentioned behavior. The breakpoint is also not hit despite the debugger being attached to the application.

**Comment by akosyakov** [comment]
@Sandared Can you share your debug configuration? How do you attach Theia debugger? I don't see any in the repo.

**Comment by Sandared** [comment]
Hi @akosyakov ,
Debugging configuration is the same as you have:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  "version": "0.2.0",
  "configurations": [
      {
          "type": "java",
          "name": "Debug (Attach)",
          "request": "attach",
          "hostName": "localhost",
          "port": 8000
      }
  ]
}
```
I start the application via mvn jetty:run, then go to the debug view in Gitpod, then click on the green play button. The debugger seems to attach correctly, but the breakpoint I set in VaadinServlet before the start of the application is not hit when I open the app in the browser. In a local Eclipse setup this breakpoint gets hit the first time I open the web app in the browser.

**Comment by akosyakov** [comment]
in Theia: https://github.com/theia-ide/theia/issues/4197

**Comment by akosyakov** [comment]
@Sandared a PR in Theia: https://github.com/theia-ide/theia/pull/4198 :)

**Comment by Sandared** [comment]
Fastest fix ever! Thanks a thousand times 👍
