### ISSUE TITLE
I cant autorize the gitpod with gitlab

### ISSUE THREAD

**Issue by joydebcu** [gitpod-io/gitpod#2731]
### Describe the bug
I cant autorize the gitpod with gitlab

### Steps to reproduce
I cant autorize the gitpod with gitlab

### Expected behavior
I cant autorize the gitpod with gitlab

### Additional information
I cant autorize the gitpod with gitlab

### Example repository
I cant autorize the gitpod with gitlab

**Comment by akosyakov** [comment]
Please go to gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.
