### ISSUE TITLE
Authorization failed issue

### ISSUE THREAD

**Issue by gursimarh** [gitpod-io/gitpod#2738]
I tried logging in multiple times even through multiple devices and still I'm getting the authorization failed please try again message.  Please look into the matter ASAP

**Comment by akosyakov** [comment]
Please go to gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of https://github.com/gitpod-io/gitpod/issues/2746 Please reopen if you did not try to login with GitLab account.
