### ISSUE TITLE
Container does not take over my /etc/hosts

### ISSUE THREAD

**Issue by bergerem** [gitpod-io/gitpod#2739]
### Describe the bug
I changed my /etc/hosts for gitpod, that it can use the internal docker registry, but it doesn't copy it in the container.
I need to manually go into the container and change the hosts-file.

### Steps to reproduce
Just start the helm-installer.

### Expected behavior
Container uses my /etc/hosts -file

**Comment by csweichel** [comment]
Kubernetes does not automatically use the node's `/etc/hosts` file in containers. You can add hosts entries using [host aliases](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) on the pod. To add those to the workspace pod, you modify the workspace pod template in the `values.yaml` (`components.workspace.templates.default.spec.hostAliases`).

Assuming you're using feature preview, i.e. have "root access" available in your workspace, you might be better of adding something to the tune of
```
tasks:
  - init: sudo sh -c "echo 1.2.3.4 myhost.com >> /etc/hosts"
```
to your `.gitpod.yaml`.

**Comment by PlentyCodeDev** [comment]
this didn't work for me, I'm getting `sh: 1: cannot create /etc/hosts: Permission denied` did  it work for you?

**Comment by danielmhair** [comment]
Hey guys, to add a host to `/etc/hosts`. Try using:
```
echo 127.0.0.1 <your-url> | sudo tee -a /etc/hosts
```

Using `sudo tee -a` did the trick with permissions.
