### ISSUE TITLE
Authorization getting failed when trying to login via Github

### ISSUE THREAD

**Issue by heyyitsmanan** [gitpod-io/gitpod#2745]
### Describe the bug
Authorization getting failed when trying to login via Github

### Steps to reproduce
Whenever I am trying to login to Gitpod via my Github account, Authorization is getting failed.

**Comment by akosyakov** [comment]
Could you confirm please that you did not try to login with GitLab account using GitHub credentials? thank you

**Comment by 18JE0618** [comment]
> Could you confirm please that you did not try to login with GitLab account using GitHub credentials? thank you
> 
> If it is the case then please go to gitlab.com and accept Terms of Service then try to login with Gitpod again.
**where i will find terms of services in gitlab**

**Comment by akosyakov** [comment]
@18JE0618 just go to gitlab.com again they should prompt you if not then you are facing another issue

**Comment by AlexTugarev** [comment]
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.
