### ISSUE TITLE
authorization with gitlab.com failed because a user did not accept gitlab TOS

### ISSUE THREAD

**Issue by Komal-Y** [gitpod-io/gitpod#2746]
### Describe the bug
Whenever I am trying to login to GitPod using Gitlab/ Github credentials it redirects me to a page saying "Sorry, something went wrong 😓
Authorization failed. Please try again"

### Steps to reproduce
Try creating a new github account and logging it to GitPod for the very first time using GitLab. Reason was I had not signed in to Gitlab seperately, however the browser showed me that Gitlab is being automatically setup

### Expected behavior
It must login 

### Additional information
![image](https://user-images.githubusercontent.com/77202010/104115296-db24ed80-5333-11eb-871a-b9ef40bc30e5.png)
![image](https://user-images.githubusercontent.com/77202010/104115310-f98ae900-5333-11eb-87c2-ce7716407554.png)

**Comment by akosyakov** [comment]
Could you check please that you accepted GitLab TOS and then try again to auth with Gitpod?
