### ISSUE TITLE
Crashed workspaces are considered running

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#275]
I was trying to create a working Dockerfile and di so by changing stuff and starting workspaces again.
Until Gitpod told me that I have too many running workspaces.
Now, I cannot use Gitpod anymore since those workspaces seem to stop never.

**Comment by Voileexperiments** [comment]
This is still happening. Docker images that failed to be built can't be stopped and they occupy the 8 running workspaces slots.

**Comment by geropl** [comment]
@Voileexperiments Thanks for bringing this up! Will look into it right now.

**Comment by Voileexperiments** [comment]
It seems that it takes up to 30 minutes for the crashed workspaces to be updated as stopped.

**Comment by geropl** [comment]
A quick update: There is a PR to fix this. We plan to deploy it around next Tuesday.
