### ISSUE TITLE
Autocompletion not working as expected for annotations

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#276]
**Describe the bug**
When I tried to add an annotation to one of my methods it is not shown in autocomplete when I hit Ctrl + Space, but after writing it by hand it can be imported by a quickfix

**To Reproduce**
* Go to [this repo](https://github.com/Sandared/io.jatoms.flow.osgi.integration)
* Open class `RouteTrackerInitializer`
* (Maybe delete the annotations first if they are already there)
* Start typing `@Activate` or `@Deactivate` and press ctrl + space (now there should be no suggestion)
* After finishing typing try to import the annotation via quickfix. (If not already imported)

**Expected behavior**
Ctrl + Space should show the annotation as it is obviously on the classpath

**Comment by svenefftinge** [comment]
A quick check revealed that monaco seem to filter out the proposals (as they are returned from the LS). 
Probably because they don't match the prefix (i.e. the filter includes the leading `@`).

**Comment by Sandared** [comment]
Any news on this issue?

**Comment by svenefftinge** [comment]
See also https://github.com/theia-ide/theia/issues/5233

**Comment by Sandared** [comment]
Has there been any insight in/update on this issue? I assume the vscode extension for java are in use by now, but this issue unfortunately still remains :(

**Comment by Sahil624** [comment]
Happening same for my Angular and Ionic project. Earlier It was working (Last time used on gitpod was like 2 weeks ago).
