### ISSUE TITLE
I am constantly getting the message sorry something went wrong when I am trying to login with gitlab since 12 hours.

### ISSUE THREAD

**Issue by Abhiraj3112000** [gitpod-io/gitpod#2778]

**Comment by csweichel** [comment]
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.

**Comment by Abhiraj3112000** [comment]
Thank u very much.
