### ISSUE TITLE
Quickfix for missing explicit constructor

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#278]
Hi,

In [this repo](https://github.com/Sandared/io.jatoms.flow.osgi.integration) when initially writing the class `RouteTracker` which extends `BundleTracker`, then `RouteTracker` is marked as incorrect with the following error message: *Implicit super constructor BundleTracker() is undefined for default constructor. Must define an explicit constructor.*

There is no quickfix for this. Not sure if this is a bug or a missing feature ;)

**Comment by svenefftinge** [comment]
> There is no quickfix for this. Not sure if this is a bug or a missing feature ;)

Not sure either. You could generally compare with the vscode java plug-in. If it does something than we can probably enable it easily, too.
