### ISSUE TITLE
Can't open Workspace: https://<myurl>/sorry/#Error%20

### ISSUE THREAD

**Issue by bergerem** [gitpod-io/gitpod#2788]
I have the following problem:

When i try to open my workspace, it seems to start and the workspaces-section shows this workspace as running, but i can't open the workspace.

It says: 
```
Sorry, something went wrong 😓
Error
```
 
and the url is `https://<myurl>/sorry/#Error%20`

My imagebuilder-service logs says: 

```
{"a":{"All":false,"Explicit":["<registryurl>"]},"message":"registry not allowed","ref":{},"reg":"docker.io","serviceContext":{"service":"image-builder","version":""},"severity":"debug","time":"2021-01-10T18:34:46Z"}
```

(The <...> are replacements from me)

**Comment by csweichel** [comment]
This is happening in your own Gitpod installation I assume, i.e. not gitpod.io?

**Comment by bergerem** [comment]
my own installation and my own docker registry. The registry has ca certs made with certbot.

**Comment by jgallucci32** [comment]
I also see the same error message when using Harbor Registry deployed using Gitpod 0.6.0-beta5. What is strange is I did not have any issues with our Docker Trusted Registry deployment. Both use the same wildcard SSL certificate (different DNS name) so i'm drawing straws here as to what could be the difference.

I've tried multiple combinations of registry auths (robot accounts, personal tokens) as well as redeploying image-builder. In any scenario it just doesn't seem to want to create the layered images and give this error instead.

**Comment by jankeromnes** [comment]
Not sure if this helps, but the error message `"registry not allowed"` seems to originate from this part of Gitpod's code:

https://github.com/gitpod-io/gitpod/blob/9ad74422c168d1e17da756efdc23aa010f96d0f1/components/image-builder/pkg/builder/auth.go#L139-L155

I guess it means that your Gitpod installation does not "allow all registries" (whatever causes `a.IsAllowAll()` to be true), and it does not explicitly allow your particular registry.

However, I'm not sure how to make your Gitpod installation allow all registries or your particular registry, and I didn't find this info in the official documentation:

https://www.gitpod.io/docs/self-hosted/latest/install/docker-registry/#docker-registry

@wulfthimm @csweichel would you know how to fix this `"registry not allowed"` error?

**Comment by jankeromnes** [comment]
Aha, @geropl tells me that private Docker registries using a self-signed CA is not officially supported currently. Maybe that's the reason?

However, it seems that one user recently got it to work: https://github.com/gitpod-io/gitpod/issues/2615#issuecomment-761034087

**Comment by bergerem** [comment]
I got the registry running, and it creates a new Pod but i can't reach it:

`transport: Error while dialing dial tcp 10.97.85.88:22999:connect: connection refused`

**Comment by jgallucci32** [comment]
@bergerem Can you provide your full `answers.yaml` file used for the deployment (sensitive info removed of course)? Also details around which OS version, Docker version, and Kubernetes distro used would be helpful as well.

**Comment by robinWongM** [comment]
Same error here with harbor registry. Maybe it's a compatibility issue?
Also I figured that image-builder was complaining about `unauthorized` at startup:
```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"Error response from daemon: unauthorized: unauthorized to access repository: gitpod/workspace-full, action: pull: unauthorized to access repository: gitpod/workspace-full, action: pull","message":"unable to precache reference","ref":"<private harbor registry>/gitpod/workspace-full:latest","serviceContext":{"service":"image-builder","version":""},"severity":"warning","time":"2021-01-29T15:01:32Z"}
```
But when I start a workspace, it DID authorized the registry and found `workspace-images` missing.
```
Error: Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: Error response from daemon: unknown: repository gitpod/workspace-images not found
```
```
time="2021-01-29T15:03:46.458073428Z" level=error msg="Handler for GET /v1.40/distribution/<private harbor registry>/gitpod/workspace-images:10907463f5139a7ccc4ac847f11b7771449ce1a907599711f6dd948a2721eb2d/json returned error: unknown: repository gitpod/workspace-images not found
```

**Comment by jgallucci32** [comment]
@robinWongM Thanks for confirming, those are the same errors I see as well when using Harbor. Our setup uses LDAP for authentication and I tried with both an LDAP user and robot account. Which auth setup is your Harbor using?

If it helps, we currently have Gitpod working with GitLab Container Registry so there is now another data point for what works or doesn't work. It would be good to know the fundamental difference between DTR/GitLab registries and Harbor to understand compatability. All 3 "should" be using the v2 API the same. So far we've had no other issues with Harbor, Gitpod is the sole issue at the time of this writing.

**Comment by robinWongM** [comment]
@jgallucci32 our Harbor uses its internal basic authentication. I've tried robot account and normal user on gitpod but neither worked. I guess that Gitpod is able to authenticate with Harbor since it knows the repository isn't exists rather than unauthorized when creating a workspace.
