### ISSUE TITLE
VSCode: Can not install local extensions

### ISSUE THREAD

**Issue by tonka3000** [gitpod-io/gitpod#2791]
Hey,

I'm not able to install local extension (vsix). I tried drag n drop like in Theia, but I could not get it to work. I develop VSCode extension and I would like to test them without pushing them to openvx before.

Version: 1.49.0
Commit: 20ded0d97c41cb686098d14b9e1f0533177300d1
Date: 2020-12-17T09:27:27.064Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

Greetings

Michael

**Comment by akosyakov** [comment]
You can start a workspace with your extension repo and use the debug launch configuration to run it.

**Comment by tonka3000** [comment]
https://gitlab.com/tonka3000/simple-cpp-abi-project

Often I have only my exension artifact (.vsix) from my CI pipeline. It work super nice in theia.

**Comment by akosyakov** [comment]
Did you try already upload the vsix file via the explorer and then in the extension view use `Install from VSIX...`:
<img width="713" alt="Screenshot 2021-01-12 at 08 52 14" src="https://user-images.githubusercontent.com/3082655/104285165-7c867d80-54b3-11eb-8940-bd6a85127b88.png">

**Comment by akosyakov** [comment]
> https://gitlab.com/tonka3000/simple-cpp-abi-project

sorry for the confusion, i meant a repo for your extension

> Often I have only my exension artifact (.vsix) from my CI pipeline. It work super nice in theia.

You could push it automatically to open VSX and install from there?

**Comment by tonka3000** [comment]
https://github.com/tonka3000/vscode-qt-tools

**Comment by akosyakov** [comment]
It should be implemented in VS Code in Jan milestone. After we will only need to upgrade.

**Comment by svenefftinge** [comment]
In addition with the next release we will allow URLs in the `.gitpod.yml` as well. So you can upload the vsix file e.g. to github releases and then make gitpod fetch it from there.
