### ISSUE TITLE
VSCode: Git Graph extension does not work

### ISSUE THREAD

**Issue by tonka3000** [gitpod-io/gitpod#2792]
Hey,

I'm not sure why but Git Graph extension does not work in VSCode, but it works in Theia. Regardless what I do, not a single command work.

I already disabled/enabled the extension and reload the workspace.

![image](https://user-images.githubusercontent.com/3163807/104133233-8bb9de00-5382-11eb-98d2-5a46ee54c175.png)

![image](https://user-images.githubusercontent.com/3163807/104133250-a8561600-5382-11eb-8d6b-9b1a279dc1a1.png)

Version: 1.49.0
Commit: 20ded0d97c41cb686098d14b9e1f0533177300d1
Date: 2020-12-17T09:27:27.064Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

Greetings

Michael

**Comment by svenefftinge** [comment]
It works now in staging.
