### ISSUE TITLE
VSCode: Integrated terminal never starts

### ISSUE THREAD

**Issue by tonka3000** [gitpod-io/gitpod#2793]
### Describe the bug
I could not start a Integrated terminal.

### Steps to reproduce
Open the following command
![image](https://user-images.githubusercontent.com/3163807/104133427-cd975400-5383-11eb-87ce-6b2dbe2df647.png)

The terminal is always in `Starting` state and never get responsive for input
![image](https://user-images.githubusercontent.com/3163807/104133441-e43dab00-5383-11eb-83d2-5679d8d2643d.png)

### Expected behavior
Terminal get responsive after some time.

### Additional information
workspace id: c3d05c66-f70a-49bc-9a0a-4c53b48a2d6c

Version: 1.49.0
Commit: 20ded0d97c41cb686098d14b9e1f0533177300d1
Date: 2020-12-17T09:27:27.064Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

### Example repository
I tried it with my gitlab repo https://gitlab.com/tonka3000/simple-cpp-abi-project

**Comment by csweichel** [comment]
I've seen this, too. It strikes me as a race in/around supervisor's terminals. Sometimes the terminals come up, sometimes they don't.
