### ISSUE TITLE
Error: undefined is not iterable error when redirecting from gitlab

### ISSUE THREAD

**Issue by ryo-egch** [gitpod-io/gitpod#2799]
gitlab (self-hosted on GKE) 13.7.1 : using https://www.gitpod.io/docs/self-hosted/latest/install/install-on-gcp-script/
gitpod (self-hosted on GKE) v0.5.0

I set up self-hosted gitlab & gitpod, and tried to integrate them, following docs https://www.gitpod.io/docs/gitlab-integration/#oauth-application 

After setting both gitlab and gitpod, I opened gitpod via gitlab, but I got a error as below.

```
We are having trouble parsing your context
Error: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

gitpod url is 
> https://35-238-45-250.ip.mygitpod.com/#https://gitlab.[MY_GITPLAB_IP].xip.io/root/test-project/-/tree/master/

which looks correct.

No idea what cause this error.

GCP log shows this error
```
stack_trace: "TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at __read (/app/node_modules/gitlab/dist/index.js:1:2673)
    at __spread (/app/node_modules/gitlab/dist/index.js:1:2975)
    at Object.<anonymous> (/app/node_modules/gitlab/dist/index.js:1:6753)
    at /app/node_modules/gitlab/dist/index.js:1:2503
    at Object.next (/app/node_modules/gitlab/dist/index.js:1:2608)
    at p (/app/node_modules/gitlab/dist/index.js:1:1366)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)" 
```

**Comment by ryo-egch** [comment]
Note

I tried to integrate with *managed gitlab (gitlab.com)*
> https://35-238-45-250.ip.mygitpod.com/#https://gitlab.com/myaccountname/sample-project/-/tree/master/

but it also got same error. So this error might be something in self-hosted gitpod

**Comment by csweichel** [comment]
Hi, this issue is fixed on master already. A 0.6.0 release of self-hosted is in the works which will include this fix. I'd expect it to be available within this week.
