### ISSUE TITLE
Invalid certificates served

### ISSUE THREAD

**Issue by birjolaxew** [gitpod-io/gitpod#280]
**Describe the bug**
When attempting to start a new project on GitPod, I get the following security error:

> 8a063b3-f3b7-4a3d-b992-dc181dad24ca.ws-eu0.gitpod.io uses an invalid security certificate.
>
> The certificate is not trusted because the issuer certificate is unknown.  
> The server might not be sending the appropriate intermediate certificates.  
> An additional root certificate may need to be imported.
>
> Error code: SEC_ERROR_UNKNOWN_ISSUER

The relevant parts of the certificate consists of (as reported by Chromium):

<pre>Issued To
  Common Name (CN)	de58f9b2-37aa-49c9-98b0-d7e168207553.ws-eu0.gitpod.io
  Organization (O)	OpenDNS, Inc.
  Organizational Unit (OU)	<Not Part Of Certificate>
Issued By
  Common Name (CN)	Cisco Umbrella Secondary SubCA lon-SG
  Organization (O)	Cisco
  Organizational Unit (OU)	<Not Part Of Certificate>
Validity Period
  Issued On	Saturday, February 2, 2019 at 3:18:46 PM
  Expires On	Thursday, February 7, 2019 at 3:18:46 PM</pre>

**To Reproduce**
Open any GitPod workspace.

**Expected behavior**
The server should serve a valid certificate.

**Comment by svenefftinge** [comment]
@32leaves is this a hickup due to the recent update?

**Comment by 32leaves** [comment]
This is odd - our certificates are issued by Let's Encrypt not Cisco. I just double-checked, on my end a workspace in the EU (i.e. URL ends with `*.ws-eu0.gitpod.io`) uses the correct certificates.

@birjolaxew is is possible that you are trying to access Gitpod from inside a corporate network? It would seem that [OpenDNS](https://www.opendns.com/) is interfering with the certificates.

**Comment by birjolaxew** [comment]
@32leaves I didn't consider that; I was accessing it through my univeristy network, which presumably does not nasty MitM. Good catch!
