### ISSUE TITLE
Update IDE switch in Settings

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2801]
The settings currently sports a switch where users can choose between Theia and VS Code. We also allow users to specify a docker image, to provide your own IDE. Going forward we want to concentrate on the VS Code integration and to that end we should remove the toggle and only allow the docker image alternative. I.e. users who enable 'Feature Preview' will automatically get the vscode based IDE.

**Comment by csweichel** [comment]
Alternatively, we could keep the toggle and default to _Code_ instead of _Theia_.

This way users don't have to opt out of feature preview if they don't want to use Code.
