### ISSUE TITLE
Integrate and Complete Commands in vscode IDE

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#2802]
The code IDE should integrate the Gitpod related commands as menu items. Also, some commands we have in the Theia IDE should be added. We should list them and decide on which we deem important and worthy to add.

**Comment by gtsiolis** [comment]
Tried to jot down below all the commands related to Gitpod available from within the Command Palette.

| Command | Theia | Code |
|-|-|-|
| Account | :heavy_check_mark: | :x: |
| Add Ready-To-Code Badge to README | :heavy_check_mark: | :x: |
| Change Image Configuration in .gitpod.yml | :heavy_check_mark: | :x: |
| Documentation | :heavy_check_mark: | :x: |
| Extend Workspace Timeout | :heavy_check_mark: | :x: |
| Follow us on Twitter | :heavy_check_mark: | :x: |
| Open Access Control | :heavy_check_mark: | :heavy_check_mark: |
| Open Discourse Community (Discuss and get support) | :heavy_check_mark: | :x: |
| Open Workspaces List | :heavy_check_mark: | :heavy_check_mark: |
| Report Issue | :heavy_check_mark: | :x: |
| Setup Project | :heavy_check_mark: | :x: |
| Share Running Workspace | :heavy_check_mark: | :x: |
| Share Workspace Snapshot | :heavy_check_mark: | :x: |
| Stop Workspace | :heavy_check_mark: | :heavy_check_mark: |
| Test the Setup | :heavy_check_mark: | :x: |
| Upgrade Subscription | :heavy_check_mark: | :x: |

Also found the following related commands that do not use the same notation using the Gitpod prefix.

| Command | Theia | Code |
|-|-|-|
| Gitpod Code: Show Release Notes | :x: | :heavy_check_mark: |
| Remote Explorer: Focus on Gitpod Workspace View | :x: | :heavy_check_mark: |
| Preferences: Open Remote Settings | :x: | :heavy_check_mark: |

@akosyakov are there any other commands that are not visible in the Command Palette or listed above?

**Comment by akosyakov** [comment]
It should be only about commands which belong to `Gitpod` category, i.e. started with `Gitpod: `. Commands for terminals, python, workspaces are provided by Code, just have different names.

> thought: Once we have all these in place we could consider a) using the same notation for commands like Open Workspaces v. Open Workspaces List as well as b) consolidate different commands like Gitpod: Stop Workspace and Workspace: Close Workspace unless this is a common pattern for the Code editor.

We don't have influence over commands under `Workspace`. It is about managing Code workspace files, not Gitpod workspaces.

**Comment by akosyakov** [comment]
@gtsiolis @svenefftinge Should we just reimplement all commands from `Gitpod` category or you see some as not important?

**Comment by svenefftinge** [comment]
Sorry, for the confusion I meant as @akosyakov also said in his comment talking about any Gitpod specific commands.
So from the top of my head important ones we should have are:

 - Gitpod: Stop Workspace
 - Gitpod: Open Settings
 - Gitpod: Open Dashboard
 - Gitpod: Open Context
 - Gitpod: Create Snapshot
 - Gitpod: Enable/Disable Sharing
 
What am I missing?

**Comment by svenefftinge** [comment]
Also, should we add a menu group (gitpod)?

**Comment by akosyakov** [comment]
> Also, should we add a menu group (gitpod)?

makes sense, if it is possible from VS Code extension

> Also, should we add a menu group (gitpod)?

What about social like twitter, community and so on? I also would like to have `Gitpod: Open Usage` instead of `Gitpod: Acoount`. It will navigiate to https://gitpod.io/usage/ instead of showing the dialog. WDYT?

**Comment by svenefftinge** [comment]
+1 for 

 - Gitpod: Follow on Twitter
 - Gitpod: Open Community
 - Gitpod: File Issue

Let's not add Open Usage for now.

**Comment by akosyakov** [comment]
| Command | Menu |
| ---------- | ---- |
| Open Dashboard | it is `Go Home` in Home (later in the main menu) |
| Open Context | Home (later in the main menu) |
| Documentation | Help |
| Create Snapshot | Home (later in the main menu) |
| Enable/Disable Sharing | Home (later in the main menu) |
| Stop Workspace | Home (later in the main menu) |
| Gitpod Access Control | Accounts (see at the bottom in the activity bar) |
| Gitpod Settings | Preferences (see at the bottom in the activity bar) |
| Follow Gitpod on Twitter | Help |
| Open Gitpod Community | Help |
| Report Problem | Help |

**Comment by akosyakov** [comment]
What about `Extend Workspace Timeout` and `Upgrade Subscription`. Do we need them? Should we add them to Accounts menu?

**Comment by svenefftinge** [comment]
> What about `Extend Workspace Timeout` and `Upgrade Subscription`. Do we need them? Should we add them to Accounts menu?

Yes, we need both. Extend Workspace Timeout depends on the subscription. I.e. server reports an error if you are not in the right plan. So we'd need to catch that and show a dialog allowing users to upgrade.

**Comment by akosyakov** [comment]
I just noticed that Codespaces also have `remote.help` panel in the remote view container:
<img width="550" alt="Screenshot 2021-01-28 at 11 12 39" src="https://user-images.githubusercontent.com/3082655/106123095-c7fa8600-6159-11eb-8d22-4259fa710fc8.png">

It is hardcoded in VS Code codebase itself. I am not sure whether we need to provide it and how it is going to work if a user install vscode-remote for VS Code desktop. I assume that it is provided by this extension or Codespaces extension then.

**Comment by svenefftinge** [comment]
This would be reasonable for an extension, but for Gitpod Code we should include the help and such more top level.

**Comment by akosyakov** [comment]
Adding sharing commands is involving and will be done separately, see https://github.com/gitpod-io/gitpod/issues/2811 and https://github.com/gitpod-io/gitpod/issues/2812
