### ISSUE TITLE
[code] support "Share Running Workspace"

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#2812]
It should be possible to share running workspaces from Code.

**Comment by akosyakov** [comment]
I moved it to March. We should first sort out Gitpod API access tokens otherwise we can leak user data of owner to invited users.

**Comment by csweichel** [comment]
I don't think we can do this in March. From a product perspective we first have to think through how we want this feature to behave. From a technical perspective, we need to figure out how we want to handle tokens/access in a shared workspace.

**Comment by svenefftinge** [comment]
I think we should add the action to share/unshare to e.g. to the toolbar. You can share workspaces from the dashboard already anyhow. That said we should redesign and rethink the whole sharing mechanic, but I think in the meantime we can just add that command.
