### ISSUE TITLE
Free Pascal support

### ISSUE THREAD

**Issue by pakLebah** [gitpod-io/gitpod#283]
Please, add support for [Free Pascal](http://freepascal.org).

Thank you.

**Comment by meysholdt** [comment]
I see you left more context [here](https://bit.ly/2DcAX6n): 

> Please add support for Pascal programming using [Free Pascal](http://freepascal.org). I manage a local Pascal community with thousand of members, including students, which desperately need a free app hosting like codenvy.io that supports Pascal programming language.

Since you seem to have experience with pascal, can you recommend a good language server or a VS Code plugin for free pascal? Those would be helpful to create support for free pascal.

**Comment by pakLebah** [comment]
Yes, I'm a long time Pascal programmer. I've been using Pascal language since Turbo Pascal 3.3 to the latest [Free Pascal](http://freepascal.org) (with [Lazarus IDE](http://lazarus.freepascal.org)) and [Delphi](http://embarcadero.com/products/delphi). And I'm also using VS Code to write Pascal program for non-GUI applications such as web service or web API.

There are 2 popular Pascal extensions for VS Code, [Pascal language](https://marketplace.visualstudio.com/items?itemName=alefragnani.pascal) and [OmniPascal](https://marketplace.visualstudio.com/items?itemName=Wosi.omnipascal). I prefer [OmniPascal](https://marketplace.visualstudio.com/items?itemName=Wosi.omnipascal) because it's easier to install. Pascal language extension requires some external tools that you have to install manually.

**Comment by sr229** [comment]
I believe Gitpod Twitter confirmed Plugin support coming soon so I could do initial support in a stack.
