### ISSUE TITLE
Customizable list of featured workspaces on the dashboard

### ISSUE THREAD

**Issue by z3ky** [gitpod-io/gitpod#2847]
Would be great, if not already possible, to change the list of featured example workspaces on the dashboard. With this function, I could use the board in classroom to provide the students basic workspaces.

**Comment by csweichel** [comment]
Would you need this on gitpod.io or in a self-hosted installation?

**Comment by z3ky** [comment]
For self-hosted installation. Maybe separate lists for Github and Gitlab users.
