### ISSUE TITLE
Remaining usage time is blank

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [gitpod-io/gitpod#2859]
### Steps to reproduce
1. Fire up an existing workspace or create a new workspace.
2. Click your profile picture in the right top corner.
3. Click **Account**.
4. You'll see what's your remaining usage time.

### Expected behavior
![image](https://user-images.githubusercontent.com/34998342/104307152-d74ac400-5509-11eb-9fd6-636df38e4778.png)

### Additional information
**From the Gitpod Community**: https://community.gitpod.io/t/looks-like-i-dont-see-my-remaining-usage-time-in-workspace/2481

**Comment by csweichel** [comment]
Considering the move towards code, we won't fix this one on the way out.
