### ISSUE TITLE
gitpod.io/#/rcclaro23/4mat2020-3

### ISSUE THREAD

**Issue by rcclaro23** [gitpod-io/gitpod#2863]

**Comment by rcclaro23** [comment]
Please, my gitpod.io/rcclaro23/4mat2020-3 is gone and no longer appears. How can i recover?

**Comment by rcclaro23** [comment]
Please, my gitpod.io/rcclaro23/4mat2020-3 is gone and no longer appears. How can i recover?

**Comment by AlexTugarev** [comment]
@rcclaro23 you might want to prefix the entire repo URL with `gitpod.io/#`, like
```
https://gitpod.io/#https://github.com/rcclaro23/4mat2020-3
```
Read more on this in the docs: https://www.gitpod.io/docs/context-urls/

And you can find your previously created workspaces on https://gitpod.io/workspaces
