### ISSUE TITLE
Gitpod fails to load any workspaces related to my repository

### ISSUE THREAD

**Issue by Terra316** [gitpod-io/gitpod#2868]
Gitpod is stuck on loading, I think.

First off, I started one workspace. this is the only one that is actually able to get past the "Starting..." screen. It got all the way to      "(3/3) Initializing Workspace," and then the tab starts to continuously reload. Any attempt to create another workspace fails to get past the "Starting..." part of the loading process, and any attempt to delete either the created workspaces or the infinitely reloading workspace results in a message that tells me to try again or contact support.
EDIT: The dashboard now allows me to delete any of the created workspaces. However, I believe that the reloading workspace is the reason why I can't create any other ones. Is it possible that I can get the Gitpod team to delete that for me?

**Comment by Terra316** [comment]
Maybe I should make another repository with all of my stuff in it. I bet that would work.

**Comment by gtsiolis** [comment]
Hey @Terra316! See https://github.com/gitpod-io/gitpod/issues/2870#issuecomment-758760944. 🔴 

> We are currently investigating an issue that prevents workspaces from starting in the US cluster.
