### ISSUE TITLE
Cannot open workspaces or launch new ones - Error: 2 UNKNOWN: cannot start workspace: workspaceExists

### ISSUE THREAD

**Issue by cjensenius** [gitpod-io/gitpod#2870]
### Describe the bug

If I attempt to open or create any workspaces I encounter an error:

`Last run 3 minutes ago: Error: 2 UNKNOWN: cannot start workspace: workspaceExists: Get "https://10.0.16.1:443/api/v1/namespaces/default/pods?labelSelector=workspaceID%3De1606bb3-701e-4282-86bb-5f990ccf6b10": dial tcp 10.0.16.1:443: connect: connection refused`

`Last run 6 minutes ago: Error: 2 UNKNOWN: cannot start workspace: workspaceExists: Get "https://10.0.16.1:443/api/v1/namespaces/default/pods?labelSelector=workspaceID%3D0e037951-1552-4d05-8c8a-aebd2deb6e4e": dial tcp 10.0.16.1:443: connect: connection refused`

`Last run 4 minutes ago: Error: 2 UNKNOWN: cannot start workspace: workspaceExists: Get "https://10.0.16.1:443/api/v1/namespaces/default/pods?labelSelector=workspaceID%3D72650fad-1ece-4a2d-b0a6-2d4eff07f91b": http2: server sent GOAWAY and closed the connection; LastStreamID=12481, ErrCode=NO_ERROR, debug=""`

Another error that was encountered was:
`Last run a few seconds ago: Error: 2 UNKNOWN: pods "ws-b71c7ce1-17f1-4e5f-9baf-965225774013" already exists`

### Steps to reproduce

This happens when clicking "Start" on a workspace, or by creating a new one via the "Gitpod" button in my gitlab repo

### Expected behavior

Normally the workspace would launch and present VSCode

### Additional information

This happens with any workspace I've tried, here are the IDs:
b1678e8b-1b2d-4bb5-a007-a33fbd729521
c983a785-81e1-412e-a0e0-14eee225f98d
df724209-92c7-4904-981d-67d66e40bff9

### Example repository

This is for a private repository but I tested by launching edf012c2-8b96-4cb3-b9f5-2ddb0120f013 from
https://gitpod.io/#https://github.com/neverendingqs/serverless-websocket-example and am stuck on "Acquiring Node ... (1/3)"

**Comment by cjensenius** [comment]
I was just able to successfully launch a new workspace from my repo - fe019dce-fdc2-4d32-b608-a337e3169887, I will test the existing workspaces now for completeness

**Comment by Terra316** [comment]
How large is the private repository?

**Comment by cjensenius** [comment]
The existing workspace c983a785-81e1-412e-a0e0-14eee225f98d launched successfully, this was a workspace that was previously unsuccessful.

**Comment by cjensenius** [comment]
I have two workspaces edf012c2-8b96-4cb3-b9f5-2ddb0120f013 and f0fa9bb4-e670-463e-96a7-35d6ea3f8a76 who have a failure mode similar to https://github.com/gitpod-io/gitpod/issues/2868 - they never launch and show a "Acquiring Node ... (1/3)" message and they never fail to allow a relaunch. They remain stuck in the yellow loading state. I understand this appears to be a distinct bug vs the description, please let me know if I should document this in a different ticket.

**Comment by cjensenius** [comment]
Now workspace c983a785-81e1-412e-a0e0-14eee225f98d loads the IDE, I can see the workspace and terminal properly, then it loads the gitpod loading image and I can no longer access the IDE. If I reload the same thing happens. fe019dce-fdc2-4d32-b608-a337e3169887 is still operating normally.

**Comment by cjensenius** [comment]
c983a785-81e1-412e-a0e0-14eee225f98d has stabilized and the IDE is displaying normally now

**Comment by gtsiolis** [comment]
Hey @cjensenius! We are currently investigating an issue that prevents workspaces from starting in the US cluster. See also relevant incident status in [`status.gitpod.io`](http://status.gitpod.io/). In the meantime, you should be able to start workspaces now. We’ve temporarily bypassed the US cluster. 🔴

**Comment by cjensenius** [comment]
Thanks for the update! If I can provide anything helpful please let me know, otherwise I will leave it to you. FWIW, I can confirm that my cluster prefix had changed to ws-eu03.gitpod.io for the successful launches.

**Comment by ArthurSens** [comment]
Hi, sorry for the inconvenience again :disappointed:. We did experience the same issues as yesterday once more. See: https://status.gitpod.io/

It should be fine by now, we are redirecting all traffic to the functional cluster. Could you try again?

**Comment by akosyakov** [comment]
An incident was resolved, please file a new issue if you still experience any problem.
