### ISSUE TITLE
ws-daemon fails to start due to hostPath type check failed

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#2876]
### Describe the bug

Self-hosted ws-daemon cannot initialize due to hostPath type check failed with the following error from the K8s cluster
```
MountVolume.SetUp failed for volume "node-fs1" : hostPath type check failed: /run/containerd/io.containerd.runtime.v1.linux/k8s.io is not a directory
```

### Steps to reproduce

Deploy latest Gitpod self-hosted 0.6.0-beta5

### Expected behavior

ws-daemon deploys and is active

### Additional information

Rancher Kubernetes Engine 17.5.1
Docker 19.03.13
Red Hat Enterprise Linux 7.8

### Example repository

n/a

**Comment by jgallucci32** [comment]
There was a similar issue to this reported in the community forums during v0.4.0 [here](https://community.gitpod.io/t/clean-install-fails-to-start-workspace/1590/5)

I attempted to fix it in a similar manner by adding this to `cluster.yml` in the K8s manifest
```
      extra_binds:
        - '/run/containerd:/run/containerd'
```
But this did not fix the problem (BEWARE: this has broken my K8s cluster)

**Comment by csweichel** [comment]
Also please beware that Gitpod requires `containerd` and will not work with docker-shim or CRI-O.

**Comment by jgallucci32** [comment]
The version of containderd installed is `containerd.io-1.3.7-3.1.el7.x86_64` which is a dependency of Docker CE 19.03.13

**Comment by jgallucci32** [comment]
Ok so the offending configuration is in `ws-daemon.yml` manifest here
```
      - hostPath:
          path: /run/containerd/io.containerd.runtime.v1.linux/k8s.io
          type: Directory
```
When I go do the directory on the K8s node all I see is this
```
# ls -l /run/containerd/io.containerd.runtime.v1.linux
total 0
drwx--x--x. 34 root root 680 Jan 13 13:56 moby
```
What this tells me is that hostPath might be hardcoded for a containerd configuration specific only to GKE which is not good. Will continue to dig into this further.

**Comment by jgallucci32** [comment]
Ok great news, this is not hard-coded, it's a new variable for `ws-daemon`. I added the following to my `answers.yaml` and it made the service active
```yaml
components:
    wsDaemon:
      containerRuntime:
        nodeRoots:
        - /var/lib
        - /run/containerd/io.containerd.runtime.v1.linux/moby
```
This issue can be closed.
