### ISSUE TITLE
cannot access the page on expose port first time

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#288]
**Describe the bug**
I cannot access the page on expose port first time

**To Reproduce**
- expose the port
- open a page in the browser

**Expected behavior**
Expected that a page is always opened, but sometimes it shows an error `port is not exposed`.

**Workaround**
Close a page and open again.

**Comment by ivanraybuglosa** [comment]
How does another user expose your port? I'm sharing my workspace with another person and it seems that he cant expose the port.

**Comment by svenefftinge** [comment]
@ivanraybuglosa thanks for reporting. I have filed a ticket https://github.com/gitpod-io/gitpod/issues/1241
