### ISSUE TITLE
IDE failed to start: fork/exec /theia/node_modules/@gitpod/gitpod-ide/startup.sh: permission denied

### ISSUE THREAD

**Issue by bilalshahzad139** [gitpod-io/gitpod#2880]
### Describe the bug
I setup gitpod on AWS using gcr.io/gitpod-io/self-hosted/installer:0.6.0-beta5. Once it is installed, oAuth is setup and when I open a new workspace (mygitpodurl/#somegithubrepo), it creates workspace but it keeps opening & starting. eventually, it throws the following error on the front end (and logs of ws-manager also shows this error)

 **IDE failed to start: fork/exec /theia/node_modules/@gitpod/gitpod-ide/startup.sh: permission denied**

### Steps to reproduce
1- Install gitpod self-hosted version 0.6.0-beta5 in AWS
2- Setup oAuth
3- Run any github repository (mygitpodurl/#somegithubrepo)

### Expected behavior
- It should open theia IDE without any error

**Comment by csweichel** [comment]
Looks like you got over the image build issue (#2852). Would you mind updating that one about what changed/made it work?

I reckon this issue is closely related, considering it's also an "exec permission on scripts" kind of thing. I double checked the images in question and there the permissions look good. Might be something AWS specific.

**Comment by bilalshahzad139** [comment]
Hi @csweichel I fixed #2852 by adding RUN ["chmod", "+x", "/gitpod-layer/scripts/generate-dockerfile.sh"] in components\image-builder\pkg\builder\selfbuild.go and rebuilt the image. 

After above fix, I faced another issue Permission denied error on /var/gitpod/layer.sh . I fixed this by adding RUN ["chmod", "+x", "/var/gitpod/layer.sh in components\image-builder\workspace-image-layer\gitpod-layer\alpine\Dockerfile and then rebuilt the image.

After the above fixes, the workspace was created but started facing this startup.sh issue. I think this is a similar issue but unable to find when/where this startup.sh file is being added in docker image. I think it is part of theia-app installer but when I try to add chmod in theia app leeway.dockerfile, it is unable to find this startup.sh file. I've tried different combinations. I am still playing with this.

**Comment by csweichel** [comment]
It's odd that those files would have to be chmod'ed explicitly, especially as they have the correct permissions in the Docker images :-/ Is there anything in your cluster (e.g. some noexec flag) that might interfere here?

Regarding the `startup.sh`, for Theia it's copied to the Docker image here:
https://github.com/gitpod-io/gitpod/blob/193eb9b2ec0df9abb7c725aa9905771a12c704e2/components/theia/app/leeway.Dockerfile#L66

I'm not sure if the Theia will just build with `docker build`. We use [leeway](https://github.com/gitpod-io/leeway) to build those images. You can try that by opening the gitpod repo in gitpod and running:
```
leeway build -Dversion=<NameYourOwnVersion> -DimageRepoBase=<YourDockerRepo> components/theia/app:docker
```

This will build the Theia IDE image and push it to `YourDockerRepo/theia:NameYourOwnVersion`.

**Comment by bilalshahzad139** [comment]
Hi @csweichel thanks for sharing this. I thought /theia/node_modules/@gitpod/gitpod-ide/startup.sh is coming from 
`COPY components-theia-app--installer /theia-installer. `
I am also using your leeway tool to build the code & to generate images. It is very good. Let me try these two things and get back to you.

**Comment by bilalshahzad139** [comment]
It seems the following change has fixed this issue.
![image](https://user-images.githubusercontent.com/2134984/104754989-b093c400-577b-11eb-8f01-85a4e62fb93a.png)
