### ISSUE TITLE
Not able to access gitlab

### ISSUE THREAD

**Issue by Dravidgupta09** [gitpod-io/gitpod#2881]

**Comment by notbotman** [comment]
Same I'm getting this often on both theia and cdr @svenefftinge 

![image](https://user-images.githubusercontent.com/74244707/104439246-eb003400-55b6-11eb-8096-c5e7fbb373c5.png)

**Comment by csweichel** [comment]
Please go to www.gitlab.com and accept Terms of Service then try to login with Gitpod again.

closing as duplicate of #2746 Please reopen if you did not try to login with GitLab account.
