### ISSUE TITLE
Unable to login to gitlab

### ISSUE THREAD

**Issue by ckvignesh** [gitpod-io/gitpod#2888]
### Describe the bug

When I open https://gitpod.io/#https://gitlab.com/crio-bytes/me_http I am asked to login to my gitlab account. I did it. But I see a screen which says  ""Sorry, something went wrong 😓
Authorization failed. Please try again.
Please file an issue if you think this is a bug. ""

Therefore I am filing this.

**Comment by svenefftinge** [comment]
This is a duplicate of #2746
