### ISSUE TITLE
Cannot start any workspaces: Error 2 UNKNOWN: Channel Destroyed

### ISSUE THREAD

**Issue by dianaabishop** [gitpod-io/gitpod#2889]
### Describe the bug

When anyone that has access to our repo attempts to start a channel up, we get an error stating "ERROR2 UNKNOWN: Channel Destroyed" 

![image](https://user-images.githubusercontent.com/9054541/104474835-6a2c4280-558c-11eb-9770-8379f9742b82.png)
If we try to create a new workspace using the gitpod extension, we get the same error and/or:
![image](https://user-images.githubusercontent.com/9054541/104474922-7f08d600-558c-11eb-97c3-443066644bb7.png)

### Steps to reproduce

Try to open/start workspace in gitpod, see error. (this is on this public repo: https://github.com/bitly/winterns2021)
FWIW I also noticed this same error happens when I try to open any other repo in gitpod

### Expected behavior

We expect the workspace to open and to be able to use it

### Additional information

https://gitpod.io/#https://github.com/bitly/winterns2021 is the specific gitpod link that we're working off of

### Example repository

https://github.com/bitly/winterns2021

Any assistance would be appreciated!!!

**Comment by abdullah20401** [comment]
I am having the same issue right now.

**Comment by abdullah20401** [comment]
I am having the same issue right now it gives me an error saying: 
`Error: 2 UNKNOWN: workspace *workspace id* exists already
Please file an issue if you think this is a bug.`

**Comment by dianaabishop** [comment]
Update - this seems to have resolved, at least for now! 🎉

**Comment by ArthurSens** [comment]
Hey, sorry for the inconvenience! We did experience an outage on one of our clusters recently. See: https://status.gitpod.io/

I'll be closing this issue but feel free to reopen it if it happens again.

**Comment by dianaabishop** [comment]
> Hey, sorry for the inconvenience! We did experience an outage on one of our clusters recently. See: https://status.gitpod.io/
> 
> I'll be closing this issue but feel free to reopen it if it happens again.

No problem - thank you @ArthurSens !
