### ISSUE TITLE
Metrics for aws/aws-cdk Gitpod usage (including forks)

### ISSUE THREAD

**Issue by skinny85** [gitpod-io/gitpod#2897]
This is a similar request to https://github.com/gitpod-io/gitpod/issues/1579 and https://github.com/gitpod-io/gitpod/issues/1669 .

Could we get the current numbers for: the amount of users, number of workspaces and total hours spent for Gitpod instances created from [aws/aws-cdk](https://github.com/aws/aws-cdk), including forks?

Thanks a lot!
Adam

**Comment by jankeromnes** [comment]
Hi @skinny85!

Sure, since there is still no dashboard for this, I'm happy to provide the data for https://github.com/aws/aws-cdk & forks:

```
+-------+------------+-------+
| users | workspaces | hours |
+-------+------------+-------+
|   380 |        910 |  1275 |
+-------+------------+-------+
```

**Comment by skinny85** [comment]
Thanks @jankeromnes! 😊
