### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#29]
Support launching Gitpod workspaces from git repositories hosted in Gitlab. 

Requested [here](
https://www.reddit.com/r/programming/comments/9b0xdh/gitpod_online_ide_for_github/e50y0gm/).

**Comment by xlnd47** [comment]
@ShalokShalom this only says its working for GitHub, not GitLab

**Comment by DouweM** [comment]
@xlnd47 The description at the top states "Gitpod - One-Click Online IDE for GitHub, GitLab and Bitbucket", but I don't actually see anything show up when I visit a project on GitLab.com.

**Comment by xlnd47** [comment]
Yes me neither

**Comment by svenefftinge** [comment]
We still haven't released the GitLab support, yet. 
What description do you refer to? We should update it for the time being.

**Comment by svenefftinge** [comment]
Ah, got it, the browser extension page.

**Comment by svenefftinge** [comment]
Updated the page.

**Comment by YassinHajaj** [comment]
@svenefftinge Hi, the information is not yet updated on the Google store page

**Comment by aggsol** [comment]
is this feature still in the pipeline or on hold?

**Comment by meysholdt** [comment]
This feature is still in the pipeline! :)

**Comment by denizozsen** [comment]
I'll add my +1 for gitlab support 👍 

Only just started looking at gitpod.io. It's an awesome project, keep up the good work, guys!

**Comment by beevelop** [comment]
I can definitely agree that Gitpod support for GitLab would be awesome. As of right now, setting up something like Eclipse Che, Koding or customizing Theia to get a similar experience is quite painful. 👍

**Comment by kylekatarnls** [comment]
Hi @meysholdt, could we hope having any GitLab app compatible with GitPod, or will it be only the domain gitlab.com?

**Comment by svenefftinge** [comment]
We will release a version for self-hosting that you can integrate with any Gitlab installation.

**Comment by steckdev** [comment]
We are launch a new project here at work and would love to be able to use this functionality. Grateful for the update. I will be crossing my fingers that it will be completed soon.

**Comment by svenefftinge** [comment]
@steckdev would you want to connect with gitlab.com or with your own installation of it?

**Comment by aggsol** [comment]
> @steckdev would you want to connect with gitlab.com or with your own installation of it?

you are not asking me... but... I have customers using their own installation of GitLab, I also need to connect to gitlab.com. So, just a 👍 for me on EVERYTHING!

**Comment by Puddinglord** [comment]
Is there any news on this? I would love to be able to have pre-built environments in GitLab and make sure the team is all on the same page environment wise. Also, working from a Chromebook/iPad is a dream of mine.

**Comment by whitetigle** [comment]
+1

**Comment by meysholdt** [comment]
Gitlab Support is officially here :-D 
Lots of kudos to @AlexTugarev and @svenefftinge for making this happen.

Please RT: https://twitter.com/gitpod/status/1202532815058944000
See this blog post for details: https://www.gitpod.io/blog/gitlab-support/
