### ISSUE TITLE
Control workspace dockerfile CMD

### ISSUE THREAD

**Issue by sabrehagen** [gitpod-io/gitpod#290]
When using a custom docker image, there is no ability to control the `CMD` for the container. For example, when opening the terminal in the editor `bash` is started, but my container's `CMD` is `zsh`. Is this invocation of `bash` controlled by theia or gitpod? If it is gitpod, could an option be added to the `.gitpod.yml` to set the `CMD` for the workspace dockerfile?

**Comment by meysholdt** [comment]
> Is this invocation of `bash` controlled by theia or gitpod?

It's actually controlled by an `sshd` through which Gitpod establishes the terminal-connection into the workspace-container. I haven't tried, but I assume `sshd` has configuration to change a user's terminal CMD.
