### ISSUE TITLE
Always showing reconnecting modal and it is too slow @ first boot

### ISSUE THREAD

**Issue by notbotman** [gitpod-io/gitpod#2901]
### Describe the bug

Always showing reconnecting modal and it is too slow @ first boot

### Steps to reproduce

![image](https://user-images.githubusercontent.com/74244707/104557867-f495a480-5667-11eb-8b1c-1ff562d3ea8d.png)

**Comment by notbotman** [comment]
And the instance is booting more than 20 mins 

![image](https://user-images.githubusercontent.com/74244707/104557937-0b3bfb80-5668-11eb-975b-4cf6441587a2.png)

**Comment by notbotman** [comment]
@svenefftinge can you help me fixing this?

**Comment by gtsiolis** [comment]
Hey @notbotman! FYI, there was a service outage on Jan 13 which could be related. Are you still seeing this?

**Comment by notbotman** [comment]
It's fixed now @gtsiolis
