### ISSUE TITLE
When passing in multiple env variables via the URL, only some variables are being set (just first and last?)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#2902]
Originally reported here: https://community.gitpod.io/t/env-variables-in-url/2505

### Describe the bug
> I’m attempting to set env variables in the URL for my Gitpod workspace, not all env variables are being set when my workspace is loaded. What am I doing wrong?

### Steps to reproduce
> `https://gitpod.io/#ASTRA_DB_USERNAME=tet,ASTRA_DB_KEYSPACE=tst,ASTRA_DB_ID=54bc3e1a-73d1-255a-9dd5-f45c64b7dfad,ASTRA_DB_REGION=us-east1/https://github.com/alexleventer/astra-gatsbyjs-starter/`

### Expected behavior
All variables should be set.

### Additional information
It seems that only the first (`ASTRA_DB_USERNAME`) and the last (`ASTRA_DB_REGION`) are being set, but not the ones in the middle (`ASTRA_DB_KEYSPACE` and `ASTRA_DB_ID`).

**Comment by AlexTugarev** [comment]
Confirming, first and last one are injected into environ, only.
