### ISSUE TITLE
Where Gitpod extension source code is located ? 

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#2903]
I've noticed there is huge difference between **Theia** and **Code** extensions, as I see **Theia** extension  gives to us more features. 

Code: 

![image](https://user-images.githubusercontent.com/1110697/104582467-961cf600-5668-11eb-9b00-651863f1afcc.png)

Theia:
![image](https://user-images.githubusercontent.com/1110697/104584021-93bb9b80-566a-11eb-8bf1-15eefd2dad3f.png)

Where can I find Gitpod extension source code for code / theia editor?

**Comment by akosyakov** [comment]
It is not implemented yet for code, issue to follow: https://github.com/gitpod-io/gitpod/issues/2802 There are more fine grained issues as well if you look for `editor: code`. Please comment on which particularly you miss.

Source code of Gitpod Theia: https://github.com/gitpod-io/gitpod/tree/master/components/theia
Source code of Gitpod Code: https://github.com/gitpod-io/vscode/tree/gp-code
