### ISSUE TITLE
Exposing URLs on a shorter domain

### ISSUE THREAD

**Issue by erasmuswill** [gitpod-io/gitpod#2905]
Hi guys,

I'm using a Pixelbook as my main development machine and Gitpod is a huge help for that. However, there is one huge shortcoming as compared to a local environment; the URLs are extremely long for exposed ports (not to mention non-http services, see #736). In the past week I've had two issues caused by the insanely long URL, which is causing me to revert to running ngrok permanently. Ngrok's URLs are however not stable (port number and/or URL change on each run) and this is especially frustrating when trying to test integration with software that needs to be reconfigured each time the URL changes. Would it be possible to have something like <username>.gitpod.io:<user-selected port number> mapped to a workspace port?

**Comment by csweichel** [comment]
Could you elaborate a bit on how the long URLs are a problem? Are there limitations by other systems that we should consider?

**Comment by erasmuswill** [comment]
The other issues I have had is with db field length for server name used in Hangfire. I think the ideal solution would be to have a client-server solution which exposes those ports on localhost so it's actual local dev but running on the cloud. This would introduce a lot of complexity though, so to counteract this, what if you could add an option for automated SSH setup? That way, one could forward ports easily, and the groundwork for this could potentially be applied to allowing TCP connections into the container (such as MySQL)

**Comment by svenefftinge** [comment]
@erasmuswill adding an SSH mode, that proxies all ports to local is on our roadmap for Q2 2021.

**Comment by erasmuswill** [comment]
Looking forward! Really enjoying Gitpod

**Comment by csweichel** [comment]
Will close this issue for now - SSH mode should fix the issue for this use-case.

**Comment by akosyakov** [comment]
We just announced preview version of Gitpod local companion which allows to tunnel any tcp port: https://www.gitpod.io/blog/local-app particularly it allows you access everything on localhost on proper port, similarly how you will do it in the local env, please try and give us feedback 🙏🏻
