### ISSUE TITLE
no such file or directoryStep 4/10 : COPY client.cnf /etc/mysql/mysql.conf.d/client.cnf

### ISSUE THREAD

**Issue by raphaelbarauna** [gitpod-io/gitpod#2907]
Hello , i'm trying to use gitpod using apache + mysql, but this error is happening, how can i fix this error?

what am I doing wrong? Thank you for your help!

![image](https://user-images.githubusercontent.com/12300929/104595126-e7b98680-5650-11eb-8ae9-b5cedf52afe8.png)

my .gitpod.dockerfile :

![image](https://user-images.githubusercontent.com/12300929/104595136-ed16d100-5650-11eb-8073-5394e04f30a7.png)

my gitpod.yml :

image
![image](https://user-images.githubusercontent.com/12300929/104595149-f142ee80-5650-11eb-8b71-172aeaf763a3.png)

**Comment by csweichel** [comment]
I assume there's a file named `apache/client.cnf` in your repo?

Note that there also is a mysql version of workspace-full already: https://hub.docker.com/r/gitpod/workspace-mysql

**Comment by csweichel** [comment]
No reporter feedback. Closing this
