### ISSUE TITLE
Workspace Dockerfile hangs on Step 9/14

### ISSUE THREAD

**Issue by sabrehagen** [gitpod-io/gitpod#291]
Using the following Dockerfile the workspace build hangs at step 9/14:

```Dockerfile
FROM stemn/development-environment:latest

# Give control to gitpod
USER root

# Gitpod configuration
ENV GITPOD_HOME /home/gitpod
ENV GITPOD_UID_GID 33333

# Keep the stemn user configuration
RUN mv $STEMN_HOME $GITPOD_HOME && \
  chown -R $GITPOD_UID_GID:$GITPOD_UID_GID $GITPOD_HOME

# Remove root user config that gitpod copies over
RUN rm -rf /root
```

![screenshot 2019-02-07 at 10 58 28 pm](https://user-images.githubusercontent.com/1094600/52410301-07260b80-2b2c-11e9-829f-82c053b01ce2.png)

**Comment by 32leaves** [comment]
Hi,

the issue here is similar to the one in #286: the copying over of `/root`. Now that `/root` is empty it's that copy process that fails. I will open an issue. 

As a workaround, you could have a single empty file in `/root` (e.g. `RUN touch /root/dontBreakMyBuild`).
