### ISSUE TITLE
The "Your workspace is currently not shared. Only you can access it." text is not changed in the "Share Workspace" window after start sharing from the Dashboard

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#293]
**Description:**

The "Your workspace is currently not shared. Only you can access it." text is not changed in the "Share Workspace" window after start sharing from the Dashboard

**Steps To Reproduce:**

1. Login to the site
2. Start the workspace
3. Open the "Share Workspace" window
4. Open the "Dashboard" and click "Start sharing" button 
6. Open the "Share Workspace" window in the Theia 
5. Pay attention to the "Your workspace is currently not shared. Only you can access it." text

**Actual result:**

The "Your workspace is currently not shared. Only you can access it." text is not changed in the "Share Workspace" window after start sharing from the Dashboard
![2019-02-07_16-04-45](https://user-images.githubusercontent.com/41964662/52416752-002ed700-2af3-11e9-9642-f459cf94a40a.gif)

**Expected result:**

The "Your workspace is currently shared. Anyone with the link can access this workspace." text is displayed  in the "Share Workspace" window after start sharing from the Dashboard

**Additional Information:**
Win 10 Google Chrome 71.0.3578.98 // FF 64.0.2

**Comment by svenefftinge** [comment]
That's fine. I don't think this needs to be addressed.
