### ISSUE TITLE
self-hosted: getting error on running simple 'sudo' => sudo: effective uid is not 0

### ISSUE THREAD

**Issue by bilalshahzad139** [gitpod-io/gitpod#2932]
- Self Hosted Version using 0.6.0 installer
- deployed in AWS EKS

- Using **FROM gitpod/workspace-full** in .gitpod.Dockerfile 

I am getting the following message when I run sudo (or sudo docker-up after enabling in Preview Features)

sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

Do I need to do change anything in my installation or anything in workspace?

**Comment by csweichel** [comment]
You need to enable "feature preview" for your user in your account's settings.
Note however that the "root access" feature at the moment has pretty strict requirements, first and foremost: it only works on Ubuntu. We are looking to change that.

**Comment by ranzbak** [comment]
I'm trying to get sudo running on a RKE cluster, running on Ubuntu 20.04, but without success.
Googling for the strict requirements, didn't get me usable results, so I'm asking here.
Do you have a link to these strict requirements for self-hosted??
