### ISSUE TITLE
Don't expect /root to exist in Dockerfile build

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#294]
**Describe the bug**
The Gitpod layer expects `/root` to exist and to have a file in it. This breaks Docker images that do not fulfil this condition.

**To Reproduce**
Build a workspace with the following Dockerfile:
```
FROM gitpod/workspace-full

USER root
RUN rm -rf /root
```

**Expected behavior**
The Dockerfile should build and we should not require `/root` to exist.

**Comment by 32leaves** [comment]
This is closely related to #289
