### ISSUE TITLE
Allow to configure "workbench.editor.enablePreview" and "workbench.editor.enablePreviewFromQuickOpen"

### ISSUE THREAD

**Issue by josemontesp** [gitpod-io/gitpod#2951]
As the title says, I'd like to configure these VS Code preferences. By default these settings are disabled, and IMO it's critical to have them enabled to prevent 100s of tabs to end up open after a coding session.

**Comment by svenefftinge** [comment]
You can switch to it by enabling "Feature Preview" in your https://gitpod.io/settings/

**Comment by akosyakov** [comment]
https://www.gitpod.io/docs/feature-preview/#default-ide
