### ISSUE TITLE
Allow to set "files.autoSave": "onFocusChange",

### ISSUE THREAD

**Issue by josemontesp** [gitpod-io/gitpod#2952]
As the title says, I'd like to be able to autosave the files on focus change. Currently it only supports saving after a fixed timeout

**Comment by svenefftinge** [comment]
This is already supported by VS Code. You can switch to it by enabling "Feature Preview" in your https://gitpod.io/settings/
<img width="459" alt="Screenshot 2021-01-19 at 10 19 03" src="https://user-images.githubusercontent.com/372735/105013757-df41c100-5a3f-11eb-8a2d-4a5eb3cbb573.png">

**Comment by akosyakov** [comment]
Pleas use VS Code instead, how to switch: https://www.gitpod.io/docs/feature-preview/#default-ide
