### ISSUE TITLE
issue updating

### ISSUE THREAD

**Issue by mattgreen91** [gitpod-io/gitpod#2954]
Im trying to update my file, but i get the error

gitpod /workspace/CV $ git add index.html

error: unable to create temporary file: No space left on device
error: index.html: failed to insert into database
error: unable to index file 'index.html'
fatal: updating files failed

**Comment by mattgreen91** [comment]
i tried using another browser and same issue.

i saved and uploaded directly to github and had no issues.  the issue is coming from gitpod but i dont know why?

i cant do any git add, git commit and git push..

**Comment by svenefftinge** [comment]
Sorry, for that. One of the nodes ran out of disk space. Resolved now.
