### ISSUE TITLE
[self-host][v0.6.0] ContainerCreating error happens on some deployments

### ISSUE THREAD

**Issue by ryo-egch** [gitpod-io/gitpod#2955]
I tried to install gitpod on GCP (now, latest is already v0.6.0 ) and running command which is written in https://www.gitpod.io/docs/self-hosted/latest/install/install-on-gcp-script/

> mkdir -p $PWD/gpinstall
docker run --rm -it \
    -v $PWD/gcloud:/root/.config/gcloud \
    -v $PWD/gpinstall:/workspace \
    gcr.io/gitpod-io/self-hosted/installer:latest \
    gcp
  
params  are
 - region : asia-northeast1
 - domain: (default)

Then, some pods are not working 
 - proxy
 - registry-facade
 - ws-proxy

and when showing pod log, it showed up

```
  Warning  FailedMount  38s (x11 over 6m50s)   kubelet            MountVolume.SetUp failed for volume "https-certificates" : secret "https-certificates" not found
  Warning  FailedMount  17s                    kubelet            Unable to attach or mount volumes: unmounted volumes=[https-certificates], unattached volumes=[config pull-secret https-certificates cache]: timed out waiting for the condition
```

I wonder if there are some changes from v0.5.0 to v0.6.0 cause it.

**Comment by csweichel** [comment]
Unfortunately, v0.6.0 requires custom HTTPS certificates and won't work the same way that v0.5.0 did.
We're aiming to restore that functionality in a future release (hopefully v0.8.0).

**Comment by exolab** [comment]
Our install of the most recent version is failing the same way. How was this fixed?

**Comment by MrSimonEmms** [comment]
@exolab if you're seeing errors due to `https-certficates` not being present, it's likely that this is due to there being no TLS certificate configured correctly.

The `0.6.0` shares very little with `2022.7.2` release (see this [blog post](https://www.gitpod.io/blog/gitpod-installer)) so it's almost certainly due to configuration. If the TLS certs aren't the problem, please provide some more context

**Comment by exolab** [comment]
You were right, of course. Sorry for the hassle and thank you for your support.
