### ISSUE TITLE
Authorization failed. Please try again. This is what displayed when i tried to open the workspace and logged in with gitlab

### ISSUE THREAD

**Issue by Varunkalra18** [gitpod-io/gitpod#2959]

**Comment by geropl** [comment]
Hi @Varunkalra18 ,

that sounds bad. Could you elaborate on how you got there?

 - Are you a long time user/fresh user?
 - Are you using Gitpod the first time within days/weeks, or is it just another workspace?
 - Did it happen on other workspaces, too?
 - What happened when you tried to open it again?

**Comment by csweichel** [comment]
sounds like a duplicate of #2818
