### ISSUE TITLE
The “Git History” panel  does not close

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#296]
**Description:**

The “Git History” panel  does not close

**Steps To Reproduce:**

1. Login to the site
2. Start the workspace
3. Open  the "Git history" panel in the Top Tool Bar - > View (Alt + H)
4. Clohe the "Git" history" panel  in the Top Tool Bar - > View (Alt + H)
5. Pay attention to the "Git History" panel 

**Actual result:**

The “Git History” panel  does not close
![2019-02-08_10-12-07](https://user-images.githubusercontent.com/41964662/52466649-acbc9780-2b8b-11e9-8825-70ad592f874c.gif)

**Expected result:** 

The “Git History” panel closes

Additional Information:
Bug is reproduced in the Chat With Us window 
Win 10 Google Chrome 71.0.3578.98 // FF 64.0.2

**Comment by kittaakos** [comment]
Possible related: https://github.com/theia-ide/theia/issues/1727

**Comment by jbicker** [comment]
Solved in https://github.com/theia-ide/theia/pull/4997
