### ISSUE TITLE
Get environment variable

### ISSUE THREAD

**Issue by spadletskysdev** [gitpod-io/gitpod#2969]
Hello. I'm quite new to this and I am wondering how can I get the Environment variables i set in the account settings via Javascript or any process. thanks in Advanced!

**Comment by alesanchezr** [comment]
Every language has a different way to retrieve ENV variables, node JS has a global `process` object that yu can use like this:

If you have a ENV variable called `API_URL` anywhere on your code you can type:

```js
console.log(process.env.API_URL);
```

This willpring on the console the content of the `API_URL` variable.

**Comment by csweichel** [comment]
Thank you @alesanchezr for that perfect answer :)
