### ISSUE TITLE
gitpod.yml vs docker-compose.yml

### ISSUE THREAD

**Issue by JamesGreenaway** [gitpod-io/gitpod#297]
is it possible to add the same commands to a gipod.yml file that I would to my docker-compose file?

**Comment by svenefftinge** [comment]
No, they are two different formats. 
Atm we allow only one container for which you can specify either a docker image or file. You can specify multiple start commands. Each will open its own terminal on start. Please also check the [documentation](https://docs.gitpod.io).

Could you outline what you try to achieve? I'd be happy to help if I can.

**Comment by JamesGreenaway** [comment]
I have a custom docker image that i have on docker hub.  I would usually run it via docker-compose as it has a lot of options to fill in and environment variables etc... How would I replicate this with gitpod?

**Comment by svenefftinge** [comment]
You could write a Dockerfile that extends from your image and adds those environment variables.
But I see that you would prefer not to duplicate them. Would extracting them to an env file work for you?

See https://docs.gitpod.io/42_Config_Docker.html

**Comment by JamesGreenaway** [comment]
Yeah I guess i could just extent my dockerfile, thats not really a problem. [My image](https://hub.docker.com/r/jamesgreenaway/craftcms) mounts a host volume and uses a named volume for a persistent mysql database.  Other than that it has a few environment variables mainly for setting up a database.  Do you think I would be able to re-create this? Would you recommend using the official  Gitpod docker image, instead of using my own from scratch?

**Comment by svenefftinge** [comment]
We don't have many requirements on the docker image, as we add what we need in additional layers on top when it is first used. So you should be fine using your own. 
But we disallow root or sudo for security reasons and you will be logged in as the user `gitpod` which we add in case it is not present. So you should make sure that you can start any services (mysqld) as that user. We are looking into specifying multiple sidecar containers in addition to the main workspace image as well as allowing root and sudo. But especially the latter will take a bit, as we are relying on developments in upstream projects (Kubernetes, etc.)

**Comment by JamesGreenaway** [comment]
ok thanks, il give it a go. what do you mean by side car containers, what would be their purpose?

**Comment by svenefftinge** [comment]
Great, please keep us posted about your progress and experience.

**Comment by meysholdt** [comment]
I just came across [changeweb/Unifiedtransform/docker-compose.yml](https://github.com/changeweb/Unifiedtransform/blob/master/docker-compose.yml)
and it looks like nice real-world example for dev-environment via docker-compose.

**Comment by volthier** [comment]
How use same Docker-compose stack like App, Db, Ldap on gitpod.io ate same time?

App its une server
DB another,
LDAP another.
