### ISSUE TITLE
Add ?initial_gitpod_yml url argument

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#2971]
I would like the gitpod button links [on this page](https://markfirmware.github.io/alpinejs-three) to include a ?initial_gitpod_yml argument that supplies the initial .gitpod.yml file (if not already in the repository.) [The gitood link is produced here.](https://github.com/markfirmware/alpinejs-three/blob/4df269ee4ed26e65bb804bf78e5488432af0fa98/docs/index.html#L14-L16)

For this particular page, the initial .gitpod.yml would for instance open a site preview.

I can open a draft pr for this, for further discussion and clarification, if it cannot be readily implemented.

Thanks, Mark

**Comment by csweichel** [comment]
Could you elaborate a bit on the use-case? Why does the .gitpod.yml in the repository now suffice?

**Comment by markfirmware** [comment]
The short answer is that each repo listed does not yet have its own .gitpod.yml. The repos listed on that page are all related in that each repo is designed to be an alpinejs web site. Therefore I, the designer of the listing, have a good idea of what a good .gitpod.yml (at least to start) would be for such a repo (that is, an alpinejs web site.)

So a person browsing the listing would only need to push the gitpod button next to the repo in the listing and the workspace would start ready-to-use without having to guide the user into adding .gitpod.yml and restarting the workspace to have the .gitpod.yml take effect.

I have some updates to make to my demo that I expect will add a lot of clarity to the use case. I will post when they are ready (later today.)

**Comment by markfirmware** [comment]
I am closing this until I get my next demo working.
