### ISSUE TITLE
I can't list my workspaces using Brave Browser

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#2973]
### Describe the bug
I can't see my list of workspaces while using the Brave Browser: https://gitpod.io/workspaces/
![Screen Shot 2021-01-19 at 10 37 19 AM](https://user-images.githubusercontent.com/426452/105056835-a2c39480-5a42-11eb-9273-ebeb3af8f7a4.png)

### Steps to reproduce
Using the Brave browser, log into my account and go to my workspaces.

### Expected behavior

See the entire list of my workspaces.

### Additional information

I'm using the brave browser, it works fine in chrome.
I'm connecting from the USA.

**Comment by alesanchezr** [comment]
Ok so it's fixed now, but it has been inconsistent in the past few days 🤔

**Comment by csweichel** [comment]
We've seen some stability issues with one of our backend services lately. We should be out of the woods though. Closing for now, please re-open if the problem persists.

**Comment by mikenikles** [comment]
I worked on a project yesterday without any issues until some time in the evening UTC. At that time, I got the same popup as above, but also couldn't start workspaces anymore. This is still the case now.

The screenshots below are from a workspace I try to open (https://moccasin-monkey-w9g6fome.ws-us03.gitpod.io/)

Browser console:
![image](https://user-images.githubusercontent.com/788827/111143774-98160f00-855c-11eb-9415-1a326732bce1.png)

And the devtools network tab:
![image](https://user-images.githubusercontent.com/788827/111143849-ad8b3900-855c-11eb-8b5f-6a53870ba912.png)

**Comment by akosyakov** [comment]
Reconnections to gitpod.io each 10mins are expected because of how GCP load balancer works. How often did it happen for you? Also please check with Brave maybe they are leaking ws connections.

**Comment by Bulletninja** [comment]
For me it seems it broke permanently for Brave. Have to use Safari now...

**Comment by gtsiolis** [comment]
Hey @Bulletninja! I could open the _Workspaces_ list successfully with Brave. Could you open a new issue with more details if you are still experiencing this issue? Is this on Gitpod.io or a self hosted instance, etc.
