### ISSUE TITLE
Gitpod browser extension should direct users to the extension activation/uninstall pages on the site

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#2974]
The Gitpod browser extensions should direct the users to `www.gitpod.io/extension-activation` once they install the browser extension and it should direct them to `www.gitpod.io/extension-uninstall` once they uninstall the browser extension.

Popular extensions like Grammarly do something very similar. 

The pages on the site are implemented in https://github.com/gitpod-io/website/pull/835/ which should be merged alongside the implementation of this issue.

**Comment by corneliusludmann** [comment]
@ChristinFrohne @nisarhassan12 How is the priority on this issue? Do we need to squeeze that into the [January milestone](https://github.com/gitpod-io/gitpod/milestone/8) or is it fine to schedule it for the [February milestone](https://github.com/gitpod-io/gitpod/milestone/9)?

/cc @csweichel

**Comment by csweichel** [comment]
Does not strike me as particularly urgent. I'd think February.
