### ISSUE TITLE
image-builder CrashBackoffLoop - Operation Not Permitted

### ISSUE THREAD

**Issue by rsliotta** [gitpod-io/gitpod#2976]
Guys,

I am testing with v0.6.0 and I cannot get image-builder to stay running.  I am using k3s.  I will say up front this could be something in my environment.  Here is the log:

[:] (lucifer) liottar:/home/liottar$ kl image-builder-7b687fd75f-6czpw -c service
{"interval":"6h0m0s","level":"info","message":"starting Docker ref pre-cache","refs":["gitpod/workspace-full:latest"],"serviceContext":{"service":"image-builder","version":""},"severity":"INFO","time":"2021-01-19T21:15:19Z"}
{"gitpodLayer":"/app/workspace-image-layer.tar.gz","hash":"ff3702e73ade2dfeb84d235f727e885b86bd1a9a40202e91e928dd65e77c7de3","level":"info","message":"computed Gitpod layer hash","serviceContext":{"service":"image-builder","version":""},"severity":"INFO","time":"2021-01-19T21:15:19Z"}
{"gitpodLayer":"/app/workspace-image-layer.tar.gz","level":"info","message":"running self-build","serviceContext":{"service":"image-builder","version":""},"severity":"INFO","time":"2021-01-19T21:15:19Z"}
{"level":"debug","message":"self-build context sent","serviceContext":{"service":"image-builder","version":""},"severity":"DEBUG","time":"2021-01-19T21:15:19Z"}
{"level":"debug","message":"Step 1/7 : FROM alpine:3.9","severity":"DEBUG","time":"2021-01-19T21:15:19Z"}
{"level":"debug","message":"pre-cached Docker ref","ref":"gitpod/workspace-full:latest","resolved-to":"docker.io/gitpod/workspace-full:latest@sha256:9bb9abd378dc80ad26a3605ba584efa4de30f621fb24ee70b0b34b5852c7b938","serviceContext":{"service":"image-builder","version":""},"severity":"DEBUG","time":"2021-01-19T21:15:20Z"}
{"level":"debug","message":"3.9: Pulling from library/alpine","severity":"DEBUG","time":"2021-01-19T21:15:20Z"}
{"level":"debug","message":"Digest: sha256:414e0518bb9228d35e4cd5165567fb91d26c6a214e9c95899e1e056fcd349011","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":"Status: Image is up to date for alpine:3.9","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e 78a2ce922f86","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":"Step 2/7 : RUN addgroup -g 33333 gitpod     \u0026\u0026 adduser -D -h /home/gitpod -s /bin/sh -u 33333 -G gitpod gitpod     \u0026\u0026 echo \"gitpod:gitpod\" | chpasswd","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e Using cache","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e a96d793a1edc","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":"Step 3/7 : RUN apk add --no-cache git bash openssh-client lz4 coreutils","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e Using cache","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e 361bcfc603a9","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":"Step 4/7 : COPY bob /bob","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e Using cache","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e ff5eceeb7fad","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":"Step 5/7 : COPY gitpodLayer.tar.gz /gitpodLayer.tar.gz","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e Using cache","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e f69458110446","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":"Step 6/7 : RUN mkdir /gitpod-layer \u0026\u0026 cd /gitpod-layer \u0026\u0026 tar xzfv /gitpodLayer.tar.gz","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"level":"debug","message":" ---\u003e Running in 4583f3db8cf6","severity":"DEBUG","time":"2021-01-19T21:15:21Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"sysfs\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/165536.165536/overlay2/041ba5bb28941330a052f1ee68d21625d78d41f94f696b69250bd2defa24dd9a/merged\\\\\\\" at \\\\\\\"/sys\\\\\\\" caused \\\\\\\"operation not permitted\\\\\\\"\\\"\": unknown","level":"error","message":"self-build failed","serviceContext":{"service":"image-builder","version":""},"severity":"ERROR","time":"2021-01-19T21:15:21Z"}
{"level":"fatal","message":"OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"sysfs\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/165536.165536/overlay2/041ba5bb28941330a052f1ee68d21625d78d41f94f696b69250bd2defa24dd9a/merged\\\\\\\" at \\\\\\\"/sys\\\\\\\" caused \\\\\\\"operation not permitted\\\\\\\"\\\"\": unknown","serviceContext":{"service":"image-builder","version":""},"severity":"CRITICAL","time":"2021-01-19T21:15:21Z"}
[:] (lucifer) liottar:/home/liottar$

**Comment by csweichel** [comment]
This does look like an environment issue. image-builder deploys a Docker-in-Docker (DinD) container which it uses to build images. During startup it "self-builds" an image it needs while building the workspace images. It looks like this self-build is failing because the DinD is unable to mount `/sys`. The odd thing is that other steps in the self-build did work, which begs the question "why fail now".

There are many possible reasons why the `/sys` mount is failing here. Maybe some system details could help, e.g.
- your kernel version (`uname -a`)?
- which version of k3s are you running?

**Comment by rsliotta** [comment]
Hello...  Thanks for the help.

In answer to your question, i WAS on a 4.8 kernel, but with your hint I updated to 5.10 on Centos 8 and the latest k3s.
I am now past the DIND issue I believe but have a new one.  Here is the latest output:

```
[K8s: :] liottar:/Users/liottar$ kl image-builder-5866486bc4-6g4xp -c service
{"interval":"6h0m0s","level":"info","message":"starting Docker ref pre-cache","refs":["gitpod/workspace-full:latest"],"serviceContext":{"service":"image-builder","version":""},"severity":"INFO","time":"2021-01-20T13:11:29Z"}
{"gitpodLayer":"/app/workspace-image-layer.tar.gz","hash":"ff3702e73ade2dfeb84d235f727e885b86bd1a9a40202e91e928dd65e77c7de3","level":"info","message":"computed Gitpod layer hash","serviceContext":{"service":"image-builder","version":""},"severity":"INFO","time":"2021-01-20T13:11:29Z"}
{"gitpodLayer":"/app/workspace-image-layer.tar.gz","level":"info","message":"running self-build","serviceContext":{"service":"image-builder","version":""},"severity":"INFO","time":"2021-01-20T13:11:29Z"}
{"level":"debug","message":"self-build context sent","serviceContext":{"service":"image-builder","version":""},"severity":"DEBUG","time":"2021-01-20T13:11:30Z"}
{"level":"debug","message":"Step 1/7 : FROM alpine:3.9","severity":"DEBUG","time":"2021-01-20T13:11:30Z"}
{"level":"debug","message":"3.9: Pulling from library/alpine","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":"pre-cached Docker ref","ref":"gitpod/workspace-full:latest","resolved-to":"docker.io/gitpod/workspace-full:latest@sha256:9bb9abd378dc80ad26a3605ba584efa4de30f621fb24ee70b0b34b5852c7b938","serviceContext":{"service":"image-builder","version":""},"severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":"Digest: sha256:414e0518bb9228d35e4cd5165567fb91d26c6a214e9c95899e1e056fcd349011","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":"Status: Image is up to date for alpine:3.9","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":" ---\u003e 78a2ce922f86","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":"Step 2/7 : RUN addgroup -g 33333 gitpod     \u0026\u0026 adduser -D -h /home/gitpod -s /bin/sh -u 33333 -G gitpod gitpod     \u0026\u0026 echo \"gitpod:gitpod\" | chpasswd","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":" ---\u003e Using cache","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":" ---\u003e 3aee6b8d8ec2","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":"Step 3/7 : RUN apk add --no-cache git bash openssh-client lz4 coreutils","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":" ---\u003e Running in 4188ee3c51a6","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":"fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz","severity":"DEBUG","time":"2021-01-20T13:11:31Z"}
{"level":"debug","message":"\u001b[91mWARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)","severity":"DEBUG","time":"2021-01-20T13:11:36Z"}
{"level":"debug","message":"\u001b[0mfetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz","severity":"DEBUG","time":"2021-01-20T13:11:36Z"}
{"level":"debug","message":"\u001b[91mWARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"\u001b[0m\u001b[91mERROR: unsatisfiable constraints:","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"\u001b[0m  bash (missing):","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"    required by: world[bash]","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"  coreutils (missing):","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"    required by: world[coreutils]","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"  git (missing):","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"    required by: world[git]","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"  lz4 (missing):","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"    required by: world[lz4]","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"  openssh-client (missing):","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"level":"debug","message":"    required by: world[openssh-client]","severity":"DEBUG","time":"2021-01-20T13:11:41Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"The command '/bin/sh -c apk add --no-cache git bash openssh-client lz4 coreutils' returned a non-zero code: 5","level":"error","message":"self-build failed","serviceContext":{"service":"image-builder","version":""},"severity":"ERROR","time":"2021-01-20T13:11:41Z"}
{"level":"fatal","message":"The command '/bin/sh -c apk add --no-cache git bash openssh-client lz4 coreutils' returned a non-zero code: 5","serviceContext":{"service":"image-builder","version":""},"severity":"CRITICAL","time":"2021-01-20T13:11:41Z"}
```

**Comment by rsliotta** [comment]
This may have been related to the server search path on DNS.  Testing now...

**Comment by rsliotta** [comment]
Confirmed it was a DNS issue.  Imagebuilder is fine

**Comment by rsliotta** [comment]
Some workspaces are working now but it seems nothing from github.  I can checkout the projects, access is set, and I get reach github with wget from the imagebuilder container...  I get the following in the logs now:

```
{"level":"info","logs":"building base image\n\ninitializing base image context\n\u0002\u0000\u0000\u0000\u0000\u0000\u0001j\u001b[31minit failed                                   \u001b[31merror\u001b[0m=cannot initialize workspace: git initializer: git clone https://github.com/eclipse-theia/theia.git . failed (exit status 128): Cloning into '.'...\nfatal: unable to access 'https://github.com/eclipse-theia/theia.git/': Operation timed out after 300025 milliseconds with 0 out of 0 bytes received\n\n","message":"build was closed but not successful","serviceContext":{"service":"image-builder","version":""},"severity":"INFO","status":3,"time":"2021-01-21T22:08:17Z"}
{"level":"debug","message":"closing build listener","serviceContext":{"service":"image-builder","version":""},"severity":"DEBUG","time":"2021-01-21T22:08:17Z"}
{"level":"debug","message":"closing build listener","serviceContext":{"service":"image-builder","version":""},"severity":"DEBUG","time":"2021-01-21T22:08:17Z"}
```

**Comment by rsliotta** [comment]
Some additional information.  I CAN use projects from github and it seems to be related to the custom gitpod setups.  I am currently using the commerical version.  Are custom gitpod images support on the self-hosted?

**Comment by rsliotta** [comment]
Closing in favor of a more specific log
