### ISSUE TITLE
I am not able to authorize my account

### ISSUE THREAD

**Issue by sujalkokane** [gitpod-io/gitpod#2981]

**Comment by sujalkokane** [comment]
I tried to authorize and i did it successfully but i think it is not able to fetch my data from the api

**Comment by AlexTugarev** [comment]
> I tried to authorize and i did it successfully but i think it is not able to fetch my data from the api

@sujalkokane, 🤔  could you be more specific, please? A screenshot, a detailed description, or an error message would help.
