### ISSUE TITLE
Run `Save All` on `Start Debugging` automatically

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#299]
**Description:**

It is not possible to run a new code without save

**Steps To Reproduce:**

1. Login to the site
2. Start the workspace
3. Disable "Auto Save" function
4. Open the "Debug" console 
5. Edit the code and run
6. Pay attention to the "Debug" console 

**Actual result:**

It is not possible to run a new code without save
![2019-02-08_15-18-17](https://user-images.githubusercontent.com/41964662/52480622-e3f36e80-2bb4-11e9-8647-259d8f6c4bb7.gif)

**Expected result:** 

It is possible to run a new code without save

Additional Information:
Win 10 Google Chrome 71.0.3578.98 // FF 64.0.2

**Comment by svenefftinge** [comment]
Do you mean you expect to autosave when launching a debug session?

**Comment by tarasdidyk** [comment]
Yes, or maybe the notification “You have not saved data”

**Comment by jankeromnes** [comment]
Interesting idea, thanks. Note that the `x` icon to close an Editor tab becomes a full disk when the file contains unsaved changes. But maybe this UX can somehow be improved / made more obvious?

**Comment by AlexTugarev** [comment]
I compared with vscode: on start of debugging they just trigger `save all` regardless of `Auto Save`
