### ISSUE TITLE
vim extension breaks editor navigation within 1 hour

### ISSUE THREAD

**Issue by Michaelhobo** [gitpod-io/gitpod#2998]
### Describe the bug

After using a new workspace for a bit, mouse navigation in the browser breaks. This has made using gitpod a terrible experience. When I move somewhere else in my current file, the next action will get applied to the previous location. The same problem applies to using page-up/page-down.

example 0: while in vim insert mode, I'm currently on line 30. I click to line 40, and type "hello". The "h" gets written to line 30, and "ello" gets written to line 40.

example 1: I press page-up, and the cursor jumps up 1 page. Then, I press the up arrow, and the cursor moves 1 page back down, and 1 line up.

The same problem applies in vim's command mode.

Other observations:

- This doesn't happen with a new workspace - it takes a while for it to kick in.
- Once it starts happening, it doesn't fix itself. I don't know if restarting the workspace solves it, but I usually create a new one.
- It happens pretty often (most of my workspaces run into this within an hour)
- vim-only navigation (arrow keys, gg, G, b/w etc) works as expected. Pg-up/Pg-dn, and mouse navigation don't work well.

I also filed this under https://github.com/eclipse-theia/theia/issues/8858. I couldn't reproduce this issue with theia sources, after a reasonable amount of time.

**Comment by svenefftinge** [comment]
Could you try run the command "Restore workspace layout" (Press F1 for the command palette)?
Also alternatively you could switch to VS Code by goint to https://gitpod.io/settings, enable "Feature  Preview" and therein choose "Code".

**Comment by Michaelhobo** [comment]
I didn't find "Restore workspace layout", but I found "View: Reset Workbench Layout", which makes the problem go away for that workspace, but all the context of my open files disappears.

Last time I tried VSCode in Gitpod (sometime last month), user settings didn't persist, gitpod.yml settings didn't apply, and it generally wasn't ergonomic between workspace restarts. The vim emulation there felt a lot more solid though - but not a great solution (yet)

**Comment by akosyakov** [comment]
You can install VSCode VIM extension from Open VSX. And it runs alone in browser web worker.
<img width="1904" alt="Screenshot 2021-06-19 at 09 50 07" src="https://user-images.githubusercontent.com/3082655/122631261-fca8b300-d0e3-11eb-9d4a-a00f6871e060.png">
