### ISSUE TITLE
Can't start test instance: port 3000 not exposed

### ISSUE THREAD

**Issue by marcdumais-work** [gitpod-io/gitpod#3]
When starting a test instance, from the review/dev instance (opened on PR 1775), I got the following error: 

```
Sorry, that should not have happened!
Port '3000' of workspace is not exposed. Please, update your '.gitpod' config file.
```
Here is how I tried to start the test instance: 
```
root /workspace/theia/examples/browser # yarn run start hostname=0.0.0.0 ../../
```

**Comment by marcdumais-work** [comment]
I have confirmed that this issue is not specific to the PR above.

**Comment by svenefftinge** [comment]
It should be `yarn run start --hostname=0.0.0.0 ../../`
Probably, Theia CLI should warn about it.
