### ISSUE TITLE
I'm having a problem with my account. When I tried to start gitpod this line shows up "We are having trouble parsing your context Error: Couldn't parse context '.'." and I am unable to write anything to gitpod cli.

### ISSUE THREAD

**Issue by sut0xar** [gitpod-io/gitpod#3005]

**Comment by gtsiolis** [comment]
Hi @sut0xar! Could you share a context URL (Repository, Pull Request, etc) to reproduce this or add more information on how are you trying to start Gitpod? See [relevant docs](https://www.gitpod.io/docs/context-urls/).

**Comment by AlexTugarev** [comment]
This results from a URL like `gitpod.io/#.` (see the trailing dot)

As suggested by @gtsiolis, please prefix the whole URL of a repository with `gitpod.io/#`, as described in the [docs](https://www.gitpod.io/docs/context-urls/).
