### ISSUE TITLE
workspace-full-vnc opens port 5900 - why?

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#3006]
I understand that 6080 is a vnc to the virtual desktop. For what purpose is 5900? If I open it in a browser, it always appears blank.

https://github.com/markfirmware/gitpod-port-5900

Thanks, Mark

**Comment by gtsiolis** [comment]
Hi @markfirmware! Port 5900 is also used for the VNC service, see [`L11`](https://github.com/gitpod-io/workspace-images/blob/b4b8a2b796ce570efa3aef2fc9d12d5c9803d0d2/full-vnc/start-vnc-session.sh#L11) in the `workspace-full-vnc` image.

You can also find some useful [topics related to VNC](https://community.gitpod.io/search?q=vnc) from the community in [community.gitpod.io](https://community.gitpod.io/). 💬

**Comment by markfirmware** [comment]
I see a topic there on screen resolution - that was my next question so I will study that and discuss it there if needed.

Ok, so 5900 is also the desktop and can be used by a regular vnc viewer  (whereas 6080 is used by the novnc web browser viewer.)

There is no guidance in the configuration instructions for port 5900. It likely should be ignored in the common use case. There should be at least one sentence explaining it. It makes no sense to open it in a browser or in a preview yet there is a notification providing those options.

I will let you keep this issue open for tracking, or to close it as you see fit. Regards, Mark.

**Comment by akosyakov** [comment]
Gitpod automatically expose all ports which are available on localhost that a user could access from outside. By default though everything is exposed only for this user, but visibility of a port can be changed in the ports view.

You can add `onOpen: ignore` in your gitpod yml to avoid notifications about some ports.

**Comment by markfirmware** [comment]
Right, that is the technical design. The point here is that I was directed to use workspace-full-vnc and to use 6080, but there was no explanation or guidance for 5900. I had to figure out on my own that 5900 would be used for a standard vnc viewer (which one would rarely use since 6080 just works in the browser with novnc.)

So
  1. guidance improvement - explain 5900 in the next sentence after explaining 6080
  2. implement #3059 and use it in a few repos and examples and it will become viral guidance. Some users will just copy the ports section of a descriptive .gitpod.yml and many others will then just know the purpose of 5900.
  3. provide links in the ports tab to get to tools and internet text databases that provide descriptions of ports - what if you are gitpodding a new os kernel that opens a zillion ports?

**Comment by markfirmware** [comment]
I meant to say thank you for your attention and responses. It is very much appreciated and you have a great product.
