### ISSUE TITLE
OutOfMemory: Pod Node didn't have enough resources

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3008]
It happens in the preview environment:
<img width="1904" alt="Screenshot 2021-01-25 at 07 48 50" src="https://user-images.githubusercontent.com/3082655/105680130-9d0cf980-5eef-11eb-8c2d-0a5157930b6c.png">

@csweichel mentioned that it should never happen and looks like ws-scheduler bug.

**Comment by geropl** [comment]
Nope, this might happen in `gitpod-dev`/`gitpod-io-dev` as we have multiple `ws-scheduler` instances operating on the same NodePool. Albeit not nice, there is no easy way to avoid this.
