### ISSUE TITLE
workspace can't be restored after stop

### ISSUE THREAD

**Issue by yyexplore** [gitpod-io/gitpod#3020]
### Describe the bug

- self hosting
- Version :  `0.6.0`

Sometimes the stopped workspace can't be resumed 
Starting of workspace is hung
The log of workspace stops here
```
orconfig@0.15.1/extension/out/editorConfigMain.js\"","payload":{"name":"root","params":[]}}
{"component":"workspace","severity":"info","time":"2021-01-26T11:06:02.495Z","message":"Deploying VS Code extension \"ms-vscode.references-view@0.0.47\" from \"/tmp/vscode-extensions/ms-vscode.references-view@0.0.47/extension/dist/extension\"","payload":{"name":"root","params":[]}}
{"component":"workspace","severity":"info","time":"2021-01-26T11:06:02.497Z","message":"Deploying VS Code extension \"vscode.docker@1.47.3\" from \"/tmp/vscode-extensions/vscode.docker@1.47.3/extension\"","payload":{"name":"root","params":[]}}
```
### Steps to reproduce
1. start a new workspace
2. stop workspace
3. restart the workspace

### Expected behavior
The stopped workspace could be restored 

### Additional information

paused here

![截屏2021-01-26 下午7 16 55](https://user-images.githubusercontent.com/3124074/105838480-177e6c00-600b-11eb-916a-5957fea00525.png)

**Comment by corneliusludmann** [comment]
Could you please have a look at the logs of `server`, `ws-manager`, and `ws-daemon`? Is there anything noticeable?

**Comment by yyexplore** [comment]
I have checked the log, only  ws-manager  show an error 

```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"object is being deleted: services \"ws-b4694de3-0d0a-4520-8850-bb932a1bf12b-theia\" already exists","instanceId":"e4b9bf1c-c6b8-4b47-a112-f74f8a616940","level":"error","message":"was unable to start workspace","req":{"id":"e4b9bf1c-c6b8-4b47-a112-f74f8a616940","service_prefix":"b4694de3-0d0a-4520-8850-bb932a1bf12b","metadata":{"owner":"dd71b505-31a6-49c3-b7ab-bc04b947dafa","meta_id":"b4694de3-0d0a-4520-8850-bb932a1bf12b"},
```

I  recreated  server, ws-daemon,  node-daemon and ws-manager,  somehow the problem disappeared !

**Comment by yyexplore** [comment]
I also found that services of workspace `ws-<id>-ports` and `ws-<id>-thiea` were not removed  after the workspace stoped,  the workspace pod was removed correctly.

The problem was solved after I re-created  node-daemon.   I'm wondering  why the node-daemon  affect the workspace
