### ISSUE TITLE
bad code in .bashrc prevents workspace from coming up

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#3029]
### Describe the bug
IDE wont open and ...
Multiple issues with workspaces built from this repo or any branch from this repo:
https://github.com/apolopena/gitpod-laravel8-starter

Many different internal gitpod errors. See [here](https://community.gitpod.io/t/repo-builds-and-starts-but-hangs-when-opening-the-ide/2618/3) for more info.

### Steps to reproduce
Build a new workspace with the repo(s) listed in the example repository section, ensure the workspace image is not cached, force build a new workspace image.
Also Try different things. Stop the workspace, start it again. build a workspace from a cached workspace image, etc...

Some problematic workspace IDs in my account:
```
a08e22c0-91eb-4ccb-b6ea-3c19cb007748
f72bc371-e168-4e21-9fc1-ea33ce7f4df5
c24e4e86-f2e7-4a9f-9d69-1e6bf4e456b0
```

Also this issue has been raised in the community forums [here](https://community.gitpod.io/t/repo-builds-and-starts-but-hangs-when-opening-the-ide/2618/3)

### Expected behavior
No internal errors or browser hangs regardless of if the workspace image is built or cached, stoped or started.

### Example repository
https://github.com/apolopena/gitpod-laravel8-starter
branches of this repo also fail in different ways:
https://github.com/apolopena/gitpod-laravel8-starter/tree/tinkering

### Additional information
This issue may be linked to my gitpod user but I do not know for sure. I have had various error messages and made many tests.  The error messages range from "no websocket or offline (when I am online for sure)" to "Sorry this should not have happened, file a bug" to error logs like this one:
```
Last run an hour ago: failed to create containerd task: failed to mount rootfs component &{overlay overlay [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6159/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6159/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6158/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6157/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6156/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6155/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6154/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6153/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6152/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6151/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6150/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6149/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6148/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6147/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6146/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6145/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6144/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/6143/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1690/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1689/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1688/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1687/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1686/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/144/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/143/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/142/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/141/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/140/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/139/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/138/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/137/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/136/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/135/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/134/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/133/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/132/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/131/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/130/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/129/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/128/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/127/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/126/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/125/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/124/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/123/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/122/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/121/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/120/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/119/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/118/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/117/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/116/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/115/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/114/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/113/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/112/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/111/fs]}: failed to mountat: failed to find pid=1335003 process: no child processes: unknown
```

**Comment by apolopena** [comment]
In the chome dev tool network panel I get a bunch of these often:
```
reconnecting-websocket-mjs.js:483 WebSocket connection to 'wss://gitpod.io/api/gitpod' failed: Error during WebSocket handshake: Unexpected response code: 302
(anonymous) @ reconnecting-websocket-mjs.js:483
logging.ts:165 
```

**Comment by apolopena** [comment]
also I get these 302 errors intermittently when I try to access the gitpod workspace dashboard.

**Comment by apolopena** [comment]
I finally fixed the issue by clearing my "Cookies and other site data" and "Cached images and files" for the last 4 weeks. I suspect I had corrupted cookie data somehow. I could not pinpoint the root cause.

**Comment by apolopena** [comment]
I have identified the issue as bad code I copied into the.bashrc. I can replicate the issue every time now.

**Comment by corneliusludmann** [comment]
Hi @apolopena! Thanks for reporting this! Do I understand it right that a repo with failing code in a `.bashrc` prevents the workspace from coming up? Would you mind providing a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) repo with just the needed code to reproduce this? That would be great!

**Comment by csweichel** [comment]
This is an issue indeed. As part of the IDE startup we usually start a bash. If `.bashrc` is broken, that startup will fail.

**Comment by apolopena** [comment]
Hi @corneliusludmann and @apolopena 
This issue can also can affect websocket connections to the dashboard in subsequent sessions. I am pretty sure the culprit was an `exit 1` command that was 'breaking' `.bashrc`.
Since this is labeled as a bug now, would a minimum reproducable example still be helpful?

**Comment by csweichel** [comment]
@apolopena After some internal discussion we were able to reproduce this ourselves. Thank you for filing this issue :) 

The failure mode isn't great either. Not only does the workspace fail to function, but it breaks incomprehensibly.
We should either:
- make the IDE startup independent of the `~/.bashrc` (preferred)
- or, if that would break things too badly, fail the workspace properly in this case.

**Comment by apolopena** [comment]
Nice.
A graceful fail in the interim before taking `~./.bashrc` out of the IDE startup might be a good approach ;)

**Comment by csweichel** [comment]
Can reproduce with  https://github.com/csweichel/test-repo/tree/broken-bashrc
