### ISSUE TITLE
[VNC] improve screen resolution for X-Server

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#303]
when I open

https://github.com/ssloy/tinyraycaster

and the application launches via VNC in the Preview View, the application window is barely visible because it's too large and too far on the right-hand-side. 

It seems like the X-server is not aware of the Preview-Areas resolution. Maybe it's possible to adjust the X-server's resolution dynamically when the Preview is resized. Or allow zoom in the preview. Or have a resolution-picker (a drop-down-box). 

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/239422/52626793-3fbf3f80-2eb4-11e9-9f17-23f1f0f552de.png">

**Comment by jankeromnes** [comment]
There is a potentially interesting noVNC option called [resize](https://github.com/novnc/noVNC/blob/master/docs/EMBEDDING.md#parameters):

> `resize` - How to resize the remote session if it is not the same size as the browser window. Can be one of `off`, `scale` and `remote`.

**Comment by meysholdt** [comment]
How to experiment with this:

1. run `docker run -u gitpod -p 6080:6080 -it gitpod/workspace-full-vnc bash`
2. open browser on `http://localhost:6080/vnc.html` Attention! `/` will forward you to `vnc_lite.html`, but that's not what we want right now.
3. run `xterm` in the bash from (1).

you get 
![image](https://user-images.githubusercontent.com/239422/55885645-9bebca80-5baa-11e9-9be7-f9249922dcd2.png)

The "remote resizing" option sounds like what we want but has no effect. In `/tmp/display-\:0.log` and `/tmp/x11vnc-0.log` I see nothing suspicious.
