### ISSUE TITLE
[supervisor] Support user notifications

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3038]
Gitpod as a system has to notify users of certain situations while they're in their workspace. To this end, supervisor should sport a "notification" API. Supervisor and other Gitpod components would supply that API with notifications, and the IDE/integration/supervisor frontend would show those notifications to the user.

Example use-cases:
- https://github.com/gitpod-io/gitpod/issues/2810
- https://github.com/gitpod-io/gitpod/issues/2397
- https://github.com/gitpod-io/gitpod/issues/3009

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/3267
