### ISSUE TITLE
Gitpod button is different in GitLab

### ISSUE THREAD

**Issue by notbotman** [gitpod-io/gitpod#3048]
![image](https://user-images.githubusercontent.com/74244707/106230719-25eca380-6216-11eb-9235-1bbdbc9824bd.png)

This is from Gitpod Chrome Extension

**Comment by akosyakov** [comment]
cc @corneliusludmann @gtsiolis Is it expected?

**Comment by gtsiolis** [comment]
Hey @notbotman! This is already fixed in https://github.com/gitpod-io/browser-extension/pull/31 and will go into the next release of the browser extension. Thanks for noticing! ❤️ 

/cc @akosyakov @corneliusludmann
