### ISSUE TITLE
Docker with Bison but no Flex

### ISSUE THREAD

**Issue by polluks** [gitpod-io/gitpod#305]
**Describe the bug**
I have a scanner which requieres flex.

**To Reproduce**
Type `which flex`.

**Expected behavior**
`/usr/bin/flex`

**Comment by 32leaves** [comment]
You can install flex using a custom `Dockerfile` (use `gp init` to set up the Gitpod config):
```
FROM gitpod/workspace-full

RUN apt-get update \
    && apt-get install -y flex \
    && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/* 
```
