### ISSUE TITLE
Ports need descriptions

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#3059]
Quoted from a discussion at https://community.gitpod.io/t/ports-need-a-description/2622

.gitpod.yml

ports:

    port: 5080
    description: ultibo http server in qemu
    onOpen: open-browser
    port: 5900
    description: normal vnc service to desktop - not used
    onOpen: ignore
    port: 6080
    description: browser novnc service to desktop
    onOpen: open-browser

The description should then appear next to the port number (or be in a hover tip or something) anywhere a port number is displayed.

There might be a cli tool or text database on the internet to help with names of well-known or commonly used port numbers.

Yes, this is a request not for a feature but for an improvement of the Open Ports tab (and anywhere else ports are listed. )

That tab lists each port number and preview/browser/private options. Without a description for the port, one can only guess as to its purpose.

Regards,
Mark

**Comment by csweichel** [comment]
@svenefftinge It'd be great to have your input here how/when this fits on the product roadmap.

**Comment by akosyakov** [comment]
btw we could which command is running behind the port?

**Comment by davidwindell** [comment]
We'd really like this feature too, when you have ~5+ running services, spotting port "8080" or whichever is exposed gets quite cumbersome in the list.

Looking at the gitpod.yml spec you marked the "name" property as deprecated, I couldn't see any reason why though?

**Comment by sgurlt** [comment]
+1 that would be great to have :-)

**Comment by markfirmware** [comment]
.

**Comment by svenefftinge** [comment]
Having an explicit description that is shown in the view in VS Code would be great. Ideally, we also show the program that is serving the port. @csweichel I kind of remember you mentioned this was relatively easy.
I think we should allow for a description in the configuration and if that is not set we show the program name.

**Comment by akosyakov** [comment]
I think we could look at cmd of the pid behind the port, similarly how VS Code does it. If we cannot use eBPF.

**Comment by csweichel** [comment]
We have some provisioning for using seccomp-notify for extracting the command that opened the port. It's predominantly a supervisor and workspacekit change.

**Comment by csweichel** [comment]
This would be a great feature to have. However, considering the current workload I don't see how we can fit this in. Please re-add at a later time.

**Comment by roboquat** [comment]
@akosyakov: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/3059#issuecomment-924689910):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
Unfortunately after team discussions we realised that we don't have capacity for upstream issues and have to focus more on bug fixes and robust deployments. I removed it from the scheduled for now.

**Comment by akosyakov** [comment]
Descriptions can be super long how we would display them in the remote explorer? It is already quite crowded there. Would be tooltip enough? 

cc @davemecha since you had some ideas.

**Comment by davidwindell** [comment]
As an end-user, the biggest advantage by far of this would be to make it easy for newcomers to our projects to know exactly which of the ports they should use to view the primary application/web server.

In most of ours, we have ~6 ports shown but only one of them (8080) is actually used by developers working on the project.

Either the ability to highlight a port (i.e. "Launch Application") or to label with short names such as "HTTP" would be ideal.

**Comment by davemecha** [comment]
> Descriptions can be super long how we would display them in the remote explorer? It is already quite crowded there. Would be tooltip enough?
> 
> cc @davemecha since you had some ideas.

I would prefer a name over a description. The use case is similar to the terminals and the visualization could be as well:

![image](https://user-images.githubusercontent.com/137976/144426195-0a136d88-1dc9-4266-9ef6-033d63b09a31.png)

A tooltip would be better than nothing, but I don't think it's that helpful. I work often with multiple ports in projects. If one doesn't want to use the port names, he just can omit the field in the `.gitpod.yml`. So no visual overhead for those users.
Also a tooltip might conflict with the actions on hover.

**Comment by akosyakov** [comment]
We could have both, short name as a prefix and description as a tooltip?

**Comment by davemecha** [comment]
> We could have both, short name as a prefix and description as a tooltip?

Sure, as far as the tooltip is only displayed when a description field is provided in `gitpod.yml` this might be an option. 

Gitpod could track the usage of those features when parsing the yml files and maybe improve further depending on usage data. :)

**Comment by Foxhoundn** [comment]
Please, this would have been great + let me copy the whole URL from the ports view! :)

Also if there could be some indication of why / what opened other ports, that would be useful -

![CleanShot 2021-12-16 at 13 24 01](https://user-images.githubusercontent.com/8861481/146371521-8b58acb6-cd16-4a80-9b42-c761d646deb8.png)

**Comment by akosyakov** [comment]
As first step we will allow to specify name prefix and tooltip description in .gitpod.yml

We could also auto derive prefix as application protocol by probing ports, and detect cmd which exposed the port as a description. But I think we need 2 new issues for that. cc @loujaybee

**Comment by akosyakov** [comment]
> Please, this would have been great + let me copy the whole URL from the ports view! :)

Do you know about `gp url`? Please file a new issue to add copy port URL command to VS Code.

**Comment by Foxhoundn** [comment]
> > Please, this would have been great + let me copy the whole URL from the ports view! :)
> 
> Do you know about `gp url`? Please file a new issue to add copy port URL command to VS Code.

If I wanted to contribute myself, can I? Where is the repo that handles that?

**Comment by akosyakov** [comment]
> If I wanted to contribute myself, can I? Where is the repo that handles that?

It is here: https://github.com/gitpod-io/openvscode-server/tree/gp-code/main

**Comment by davidwindell** [comment]
Did anyone every get this to work? We've had descriptions in our yml's since this was merged but dont' see anything in the IDE

**Comment by davidwindell** [comment]
Ah, I've just found https://github.com/gitpod-io/gitpod/pull/9797 which explains it

**Comment by davemecha** [comment]
@davidwindell yeah, I also can't wait for this feature to finally work- That would be so helpful...
