### ISSUE TITLE
How to replace requirements.txt dynamically in .gitgod.yml?

### ISSUE THREAD

**Issue by yuzhujiutian** [gitpod-io/gitpod#3062]
### Steps to reproduce

i have three projects in one root project direction.
the requirements_xxx.txt is stored in different directions.

i want to replace requirements.txt via requirements_xxx.txt before executing the init command of tasks in .gitgod.yml.

but the requirements.txt is still empty. so pandas cannot be installed.

![image](https://user-images.githubusercontent.com/386347/106384068-395d6180-6404-11eb-8a59-0ddcab73fdc7.png)

the content of requirements_pyarrow_test.txt:
pandas
numpy
pyarrow

**Comment by csweichel** [comment]
The reason for that is that the `before` step runs in a separate task (notice the `- before`). This way it's not synchronised with the `init` command and likely to run "at the same time". 

That said, here are some other points that might help improve the setup 😄 :
- why push back to the repo in the before step? For one, this would not work in a prebuild (no access to the Git token), but also it seems odd that a workspace would do this every time.
- You could use the requirements file directly and run `pip3 install -r pyarrow_test/requirements_pyarrow_test.txt`

**Comment by yuzhujiutian** [comment]
thank you very much. 

it works ok via 'pip3 install -r pyarrow_test/requirements_pyarrow_test.txt' in .gitpod.yml


yesterday, I used the 'pip3 install -r subproject_dir/requirements_subproject.txt' method, 
which may have failed to install the package due to other reasons (such as a file name error), 
so I tried to use the 'before step' method in a detour.

![image](https://user-images.githubusercontent.com/386347/106443661-b4cc1b00-64b7-11eb-8782-0851a60395b9.png)
