### ISSUE TITLE
The prefix "gitpod.io#" doesn't work in Firefox 

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#307]
So far we are advertising the message "prefix any GitHub URL with gitpod.io#" But this prefix only works in Chrome and not in Firefox. If you use this prefix in Firefox, you get redirected to Google. 
"gitpod.io/#" or "https://gitpod.io#" works for both browser but it might be more difficult to remember and even harder to pronounce.

**Comment by JanKoehnlein** [comment]
Same with Safari.

**Comment by geropl** [comment]
That seems to depend on leading protocol, too, extending the table to:
 - https://gitpod.io#https://github.com/TypeFox/gitpod: :heavy_check_mark: 
 - https://gitpod.io/#https://github.com/TypeFox/gitpod: :heavy_check_mark: 
 - gitpod.io/#https://github.com/TypeFox/gitpod: :heavy_check_mark: 
 - gitpod.io#https://github.com/TypeFox/gitpod: `Invalid URL`

**Comment by 32leaves** [comment]
Personally I'd vote for `gitpod.io/#` as prefix. It is slightly more complicated that `gitpod.io#`, but as a developer this feels "closer to home", mainly because it is a valid URL, whereas `gitpod.io#` is not (see https://tools.ietf.org/html/rfc3986#section-3)

**Comment by geropl** [comment]
That seems to depend on leading protocol, too, extending the table to:
 - https://gitpod.io#https://github.com/theia-ide/theia: :heavy_check_mark: 
 - https://gitpod.io/#https://github.com/theia-ide/theia: :heavy_check_mark: 
 - gitpod.io/#https://github.com/theia-ide/theia: :heavy_check_mark: 
 - gitpod.io#https://github.com/theia-ide/theia: `Invalid URL`

**Comment by jankeromnes** [comment]
Same as Chris, at first I was surprised by the `gitpod.io#` trick. It felt a little strange (just like writing only `<!doctype html>` in a web page, or omitting `/` in a void element like `<br>`), and I often added `https://` or `/#` to it out of conscientiousness, but I was slowly getting used to the shorter version.

But then I also got bitten by the sudden Google search when really using just `gitpod.io#`. Maybe let's not rely on Chrome-only behavior.

I'd also vote for `gitpod.io/#`, as it's just one more character (so still as readable and memorable), and it also feels cleaner. HTTPS should be implicit by now (HTTP requests should get redirected by either HSTS policy or permanent redirection without the user having to suffer the cognitive overhead of verifying protocols).

**Comment by kittaakos** [comment]
> `gitpod.io#` I had not even thought of it

I was not aware of this either. `gitpod.io/#` seems reasonable to me.

**Comment by kittaakos** [comment]
> Same with Safari.

For the record, `gitpod.io#https://github.com/TypeFox/gitpod` works from Edge.

**Comment by svenefftinge** [comment]
Ok, let's go with 'gitpod.io/#'. 
I wanted to have something that I can tell friends and they would remember it. So'd continue to say 'gitpod io hash' which translates in written `gitpod.io/#` or even `https://gitpod.io/#`.

**Comment by jankeromnes** [comment]
I think this is addressed now. 😄
