### ISSUE TITLE
Code: Implement UserDataSync protocol

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3070]
VS Code sports a user data syncing feature, which allows to sync user data (settings, keyboard shortcuts, user snippets, extensions, ui state) across machines. 
Currently, we don't provide configuration so it is always disabled. Stock "Visual Studio Code" comes with a configuration that forwards to a load balancer that then redirects based on the auth provider you use (MS or GitHub).

We should configure it to use Gitpod as auth provider and then talk to a service that runs as part of the Gitpod installation. 
The protocol is a [basic REST](https://github.com/microsoft/vscode/blob/master/src/vs/platform/userDataSync/common/userDataSyncStoreService.ts) one with [different resource kinds](https://github.com/microsoft/vscode/blob/master/src/vs/platform/userDataSync/common/userDataSync.ts#L125) and the typical CRUD operations. Also, there is the concept of versions ([refs](https://github.com/microsoft/vscode/blob/master/src/vs/platform/userDataSync/common/userDataSync.ts#L139)) and a couple of [error kinds](https://github.com/microsoft/vscode/blob/master/src/vs/platform/userDataSync/common/userDataSync.ts#L199) that we need to support and are used e.g. for conflict resolution.

I believe supporting this in order to share user-level extensions might align us better with design decisions and UX of VS Code. It might also help integrating Gitpod from local VS Code (we'd need to update the product config, but might be able to support the rest through extensions).

**Comment by svenefftinge** [comment]
cc @akosyakov

**Comment by svenefftinge** [comment]
After some more code reading it seems to be a generic restful CRUD endpoint making use of etags. I wonder if it's generic enough so that we can reuse an existing implementation.

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/3110
