### ISSUE TITLE
Improve "Create Account" and "Select Account" pages

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#3072]
@gtsiolis provided great feedback and suggested more improvements on https://github.com/gitpod-io/gitpod/pull/3032, which seem to be feasible in the following iteration.

### Create Account ([link to origin](https://github.com/gitpod-io/gitpod/pull/3032#discussion_r566800389))

Make it obvious, that a user is creating a new account and mention the provider.

| BEFORE | AFTER | ALTERNATIVE |
|-|-|-|
| ![image](https://user-images.githubusercontent.com/120486/106276785-bdff8280-6240-11eb-85ff-a199f73397bd.png) | ![image](https://user-images.githubusercontent.com/120486/106276796-c22ba000-6240-11eb-87a8-4c462a303067.png) | ![image](https://user-images.githubusercontent.com/120486/106277267-77f6ee80-6241-11eb-96a6-5fb7d47e5a6a.png) |

### Select Account ([link to origin](https://github.com/gitpod-io/gitpod/pull/3032#discussion_r566872780))

`Created ${n} days ago` might be helpful for users to identify their primary account. Count of workspace or other meaningful information might to be included as well, let's discuss.

![image](https://user-images.githubusercontent.com/120486/106290103-bea11480-6252-11eb-8914-2bf929eb94c8.png)

**Comment by svenefftinge** [comment]
We should redesigned this as part of the new dashboard.

**Comment by gtsiolis** [comment]
Closing this in favor of https://github.com/gitpod-io/gitpod/issues/3754 as a) it contains more recent desiggn specs and ​b) we've removed the click-wrap during account creation. Thanks @AlexTugarev! 🏓
