### ISSUE TITLE
Cannot Start Workspace [staging]

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3073]
### Describe the bug
Trying to restart an older workspace (from last week) fails with

<img width="1664" alt="Screenshot 2021-02-02 at 08 21 56" src="https://user-images.githubusercontent.com/372735/106566004-fa2c2f00-652f-11eb-865f-4128d0c00c4a.png">

> failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/.supervisor/workspacekit\": stat /.supervisor/workspacekit: no such file or directory": unknown; last backup failed: cannot delete workspace from store. Please contact support if you need the workspace data.

I have these flags enabled on my user:

<img width="1178" alt="Screenshot 2021-02-02 at 08 22 54" src="https://user-images.githubusercontent.com/372735/106565991-f7313e80-652f-11eb-80f1-4abb52ed67d7.png">

**Comment by csweichel** [comment]
fixed already
