### ISSUE TITLE
dialog rendering is sometimes broken in VNC

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3079]
See https://community.gitpod.io/t/vnc-virtual-desktop-but-easier/669/8?u=akosyakov.

You can also reproduce it by:
- gitpod.io#https://github.com/microsoft/vscode
- nvm install 12 && nvm use 12 && npm install -g yarn && yarn && ./scripts/code.sh
- then open VNC on port 6080 and try to navigate through different (context) menus in VS Code
- some are rendered properly, but some:
<img width="1161" alt="Screenshot 2021-02-02 at 09 24 57" src="https://user-images.githubusercontent.com/3082655/106602365-2e6a1480-655d-11eb-97dc-084d83974e95.png">

**Comment by jankeromnes** [comment]
This problem also affects Brave and Chromium in Gitpod's virtual desktop:

- https://community.gitpod.io/t/vnc-virtual-desktop-but-easier/669/8
- https://github.com/gitpod-io/workspace-images/issues/332
