### ISSUE TITLE
[config] allow to specify 'automatically sign-off commits'

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#308]
Some open-source repositories, e.g. those on Eclipse, require their commits to be signed-off, in particular if they come from non-committers. It would be cool if I could set that to automatic in the `.gitpod.yml` file.

**Comment by svenefftinge** [comment]
I would see this more in the realm of the workspace config.

**Comment by JanKoehnlein** [comment]
I don't mind where.
