### ISSUE TITLE
Stuck on blank, black page after stopping a workspace from within using the dropdown menu

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3082]
### Describe the bug
After stopping a workspace from within that workspace I'm left on a blank, black screen (Firefox). The web console says:
![image](https://user-images.githubusercontent.com/32448529/106629057-bad70000-657a-11eb-8fba-1081686e4494.png)
Dashboard says the workspace is stopped as expected.

Config:
 - feature preview: true
 - IDE: Theia
 - Firefox: 85.0 (64-bit)

### Steps to reproduce

 - use Firefox
 - ~Open a workspace on gitpod-staging.com~ Does not work for any. But I have at least one (copper-planarian-6ytcnjwy) that I can reproduce it with. It's created on 
 - click the top-right menu -> Stop workspace
 - observe the blank page, open devtools for console output

### Expected behavior

Gitpod should show me the "Workspace is stopping" screen include Gitpod cube.

### Example repository

/cc @akosyakov

**Comment by geropl** [comment]
`TypeError: URL constructor: passedin=test%20value/https://github.com/gitpod-io/gitpod-test-repo is not a valid URL.`

**Comment by geropl** [comment]
@AlexTugarev pointed out that this is a bug in prod and that there's already an issue for it: https://github.com/gitpod-io/gitpod/issues/2902

Closing as duplicate.

**Comment by csweichel** [comment]
Considering the pending redesign of the dashboard, I'd close this for now and see if the issue persists with the rebuild.

**Comment by geropl** [comment]
Reopening because already implemented and tested: https://github.com/gitpod-io/gitpod/pull/3191
