### ISSUE TITLE
[tos] When declining updated ToS, we land on /sorry [STAGING]

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3084]
### Describe the bug
When I decline updated ToS I end up on /sorry:
![image](https://user-images.githubusercontent.com/3210701/106709262-86a02580-65f4-11eb-84ec-3d608fef9add.png)

### Steps to reproduce
1. Log in and make sure ToS are accepted
2. Clear `d_b_terms_acceptance_entry` for your user
3. Log out
4. Log in and decline updated terms

### Expected behavior
I should not see an error page but end up on `/login`

**Comment by AlexTugarev** [comment]
Closing, as this was an issue on staging, only.
