### ISSUE TITLE
[browser-extension] Gitpod button missplaced on GitHub File context

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3085]
The extension currently puts the button below the file.

<img width="223" alt="Screenshot 2021-02-03 at 09 05 12" src="https://user-images.githubusercontent.com/372735/106716868-3da19e80-65ff-11eb-8189-245962d41cc0.png">

**Comment by gtsiolis** [comment]
Fixed in https://github.com/gitpod-io/browser-extension/pull/36. 📕
