### ISSUE TITLE
remove 'theia-server' component

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3089]
The `theia-server` will not be needed anymore once `blobserve` will be used all-the-time.

see 
[chart/templates/theia-server-deployment.yaml](https://github.com/gitpod-io/gitpod/blob/master/chart/templates/theia-server-deployment.yaml)
[components/theia/static-server](https://github.com/gitpod-io/gitpod/tree/master/components/theia/static-server)

**Comment by csweichel** [comment]
@AlexTugarev solved this issue when moving Theia out of the repo.
