### ISSUE TITLE
New maven projects are not recognized

### ISSUE THREAD

**Issue by Sandared** [gitpod-io/gitpod#309]
**Describe the bug**
When I create a maven project in an empty workspace then the Java Language Server is started and the maven project is imported. When I then create a new submodule within this maven project it is not recognized and I have to restart the workspace

**To Reproduce**
Create a simple Multi-Module maven project. Add an additional module afterwards.

**Expected behavior**
The added module shall be recognized as a maven project

**Comment by svenefftinge** [comment]
Workaround: You can restart the language server using the corresponding command (F1 > "Restart Java LS")

**Comment by Sandared** [comment]
Hi Sven, 
I tried this but it didn't work. The additional module is not recognized.

Steps to reporoduce:
* go to https://github.com/Sandared/io.jatoms.osgi.base and start gitpod
* type project in commandline and fill out groupId and artifactId
* open the ComponentImpl file in the impl project (Language server is started and Maven projects are imported)
* When language server has started cd into your new project, type ds and fill out groupId and artifactId for your new submodule

This new module is not recognized until I restart the whole workspace. 
Am I doing something wrong?

Kind regards,
Thomas

**Comment by svenefftinge** [comment]
Thanks, I can reproduce it. Seems like we need to explicitly invoke some sort of synchronization.

**Comment by belaso** [comment]
Have the same problem ...
