### ISSUE TITLE
Have metric endpoints for to RED monitoring

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3090]
We'd like to have monitoring (and potentially alerts) based on the [RED method](https://grafana.com/blog/2018/08/02/the-red-method-how-to-instrument-your-services/), because we hope to get metrics/alerts that are very aligned with the user experience.

For this, each gitpod component should expose metrics regarding inbound requests:
* quantity
* error rate of responses
* latency

@csweichel mentioned that
* `ws-manager` already has some of those metrics.
* it's rather easy to monitor these requests for unary GRPC calls and that there are already utils for it.

Open questions:
* metrics for GRPC streaming calls?
* metrics for `servers` RESTful inbound requests
* metrics for `servers` websocket inbound requests
* more?

**Comment by ArthurSens** [comment]
For gRPC calls I often see this repo being used: https://github.com/grpc-ecosystem/go-grpc-prometheus
I certainly lack knowledge when gRPC is the subject, so I'm not sure how well it can be used by us.

This topic was also discussed at [CNCF's SIG-Observability meeting on 2020-12-22](https://docs.google.com/document/d/1_QoF-njScSuGFI3Ge5zu-G8SbL6scQ8AzT1hq57bRoQ/edit#heading=h.ecqcmtg20fry) (Unfortunately no recording for this one :slightly_frowning_face: ). If I remember correctly, the overall idea is that we lack proper tooling for it, but definitely, there is a lot of people out there that depend on Streaming APIs and are doing what is possible to monitor them.

I tried to bring the subject to yesterday's SIG meeting, but the whole agenda was filled with Due Diligence to move OpenTelemetry from Sandbox to Incubating maturity status. 

@csweichel would you be willing to participate in the next SIG's meeting with me? I'd like to discuss with everyone there about methodologies and strategies for monitoring streaming APIs, but my lack of knowledge with gRPC could be a blocker :sweat:

**Comment by meysholdt** [comment]
Testing the prebuilds this morning and us asking the question "do the event arrive" made it seem useful to have dedicated RED metrics for requests coming from GitHub/GitLab/Bitbucket. This would help to understand if and in which cluster they arrive.

**Comment by meysholdt** [comment]
> metrics for gRPC streaming calls?

From the perspective of an observer, this is what would interest me about streams. Not sure how easy it is to get these numbers from gRPC.
* number of initiated streams (Rate)
* number of active streams (Rate)
* number of dropped streams (Error): Rejected requests for streams and streams that did not finish successfully.
* histogram on stream throughput (like "Duration", this can give a sense for the services performance). This would answer questions such as: Are the streams idle? Are there some streams that carry crazy traffic? Do the streams fully utilise the capacity of the network? Did throughput drop and we should be worried the service has a problem? Unless "Duration" I think this metric is not suitable for alerting.

**Comment by csweichel** [comment]
> For gRPC calls I often see this repo being used: https://github.com/grpc-ecosystem/go-grpc-prometheus
> I certainly lack knowledge when gRPC is the subject, so I'm not sure how well it can be used by us.

It would - and it sure beats our own implementation :) 
Makes me wonder why the make-or-buy decision went "make" last time.

> 
> This topic was also discussed at [CNCF's SIG-Observability meeting on 2020-12-22](https://docs.google.com/document/d/1_QoF-njScSuGFI3Ge5zu-G8SbL6scQ8AzT1hq57bRoQ/edit#heading=h.ecqcmtg20fry) (Unfortunately no recording for this one 🙁 ). If I remember correctly, the overall idea is that we lack proper tooling for it, but definitely, there is a lot of people out there that depend on Streaming APIs and are doing what is possible to monitor them.
> 
> I tried to bring the subject to yesterday's SIG meeting, but the whole agenda was filled with Due Diligence to move OpenTelemetry from Sandbox to Incubating maturity status.
> 
> @csweichel would you be willing to participate in the next SIG's meeting with me? I'd like to discuss with everyone there about methodologies and strategies for monitoring streaming APIs, but my lack of knowledge with gRPC could be a blocker 😓

Sounds great - looking forward to that.
