### ISSUE TITLE
Can't add some members to a team

### ISSUE THREAD

**Issue by staxly** [gitpod-io/gitpod#3093]
### Describe the bug

I'm able to add some github users to our team, but for others I get "Gitpod user not found". I haven't been able to determine what might be different about the accounts that work and those that don't. 

### Steps to reproduce

Enter a user's github name at https://gitpod.io/teams/ using the form `github.com/USERNAME`

### Expected behavior

Successful addition of user

**Comment by gtsiolis** [comment]
Hey @staxly! Do you know if the GitHub users you are trying to add have already authorized with GitHub? They should be able to see the GitHub provider in their dashboard in [`/acces-control`](https://gitpod.io/access-control/). If not, they need to first authorize GitHub. Let me know if this helps. ❓

**Comment by staxly** [comment]
Thanks! That resolved it.

**Comment by gtsiolis** [comment]
Thanks for verifying @staxly! Let's close this.
