### ISSUE TITLE
Showing unauthorized despite of me logged in 

### ISSUE THREAD

**Issue by manishdasa100** [gitpod-io/gitpod#3095]
### Describe the bug

I logged in with my github account and the login was successful but it was requesting for further authorization from Gitlab.com. I did that and after I logged in with my Gitlab account it was showing me "Authorization failed. Please try again". I don't know what's happening may be it's a bug.

**Comment by csweichel** [comment]
Probably a duplicate of #2746.
Please reopen if that's not the case.
