### ISSUE TITLE
OAuth account creation config

### ISSUE THREAD

**Issue by krejcar25** [gitpod-io/gitpod#3097]
Hello, I have recently installed Gitpod selfhosted and I have configured OAuth via our selfhosted GitLab instance and later via GitHub too. Everything works smooth, být I see a potential security issue. Now any user from GitHub can create an account on our private Gitpod instance.

The goal with this setup was to allow our GitLab users (managed access) to connect to GitHub and use the Gitpod for GitHub repos too.

The feature request would thus be as follows:
Add a config option to OAuth providers, which states whether said provider can be used to create accounts or just connect existing ones.

This way I could have the GitLab provider be user-creating while only allowing existing users to connect to the GitHub provider.

I would have to believe I am not the only one who could use this.

Thank you for any feedback!

**Comment by AlexTugarev** [comment]
That sounds very reasonable.

**Comment by krejcar25** [comment]
Any news about this suggestion?
