### ISSUE TITLE
Support Go packages with sub-packages

### ISSUE THREAD

**Issue by kjk** [gitpod-io/gitpod#31]
When I try to work on my project https://github.com/gomarkdown/markdown I get:
```
gitpod /workspace/markdown $ go build
markdown.go:7:2: cannot find package "github.com/gomarkdown/markdown/ast" in any of:
        /usr/local/go/src/github.com/gomarkdown/markdown/ast (from $GOROOT)
        /workspace/src/github.com/gomarkdown/markdown/ast (from $GOPATH)
        /usr/local/go-packages/src/github.com/gomarkdown/markdown/ast
markdown.go:8:2: cannot find package "github.com/gomarkdown/markdown/html" in any of:
        /usr/local/go/src/github.com/gomarkdown/markdown/html (from $GOROOT)
        /workspace/src/github.com/gomarkdown/markdown/html (from $GOPATH)
        /usr/local/go-packages/src/github.com/gomarkdown/markdown/html
markdown.go:9:2: cannot find package "github.com/gomarkdown/markdown/parser" in any of:
        /usr/local/go/src/github.com/gomarkdown/markdown/parser (from $GOROOT)
        /workspace/src/github.com/gomarkdown/markdown/parser (from $GOPATH)
        /usr/local/go-packages/src/github.com/gomarkdown/markdown/parser
```

The problem is that `GOPATH` is set to `/workspace;/usr/local/go-packages/src` but the package is checked out to `/workspace/markdown`.

In order for sub-package `github.com/gomarkdown/markdown/ast` to be visible, the code would have to be checked out as `/workspace/src/github.com/gomarkdown/markdown`.

Which might be tricky since it requires auto-detecting that this is Go codebase.

If you upgrade go from `1.9.5` to latest `1.11` then at least packages that have `go.mod` will work properly.

**Comment by 32leaves** [comment]
At the moment Go projects require a [`.gitpod` file to work properly](https://docs.gitpod.io/40_Configuration.html#working-with-go). Using the `.gitpod` file one can create a workspace layout that allows sub-packages. We are working on a way to [detect Go projects automatically](https://github.com/gitpod-io/gitpod/issues/42) and set the workspace up correctly.

**Comment by svenefftinge** [comment]
@32leaves added auto detection for go projects, which solves this.
