### ISSUE TITLE
Workspaces not loading - EU

### ISSUE THREAD

**Issue by armedcor** [gitpod-io/gitpod#3106]
### Describe the bug
On the EU server, the workspace is constantly refreshing on the "starting..." screen. On a workspace that is open, running a terminal preview server sticks on "Detecting" port.
Both personal and shared workspaces stuck on the starting screen.
### Steps to reproduce
Attempt to open a new or previously open workspace.

**Comment by CosmicAsad** [comment]
Closing a workspace also takes longer, and restarting the workspace sticks on "Pending" status before stopping itself after a few minutes with an Error. On active workspaces, sharing snapshots and running workspaces does not work.

**Comment by katiedoherty** [comment]
I am having the same issue. It has been loading for a half an hour now, it won’t let me onto my workspace.

**Comment by Henriqueperoni** [comment]
Same here. 30 minutes waiting and nothing

**Comment by corneliusludmann** [comment]
Thanks for reporting and sorry for the inconvenience. I can't detect anything unusual at the moment and workspaces start without problems for me (EU). Does the problem still exist?

**Comment by armedcor** [comment]
> Thanks for reporting and sorry for the inconvenience. I can't detect anything unusual at the moment and workspaces start without problems for me (EU). Does the problem still exist?

Seems to be working again on my end. Was just able to create a new workspace that opened almost instantly along with the preview server.

**Comment by katiedoherty** [comment]
Ya it’s now working on my end too

**Comment by gtsiolis** [comment]
Thanks @armedcor and @katiedoherty for verifying!

Let's close this as everything seems to be back to normal. /cc @CosmicAsad @Henriqueperoni
