### ISSUE TITLE
ws-daemon go routine leak

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#3108]
### Describe the bug

`ws-daemon` has go routine leaks, as shown by our monitoring data.

Go Routines:
![image](https://user-images.githubusercontent.com/24193764/106947684-729a1800-6709-11eb-88f7-0e94e9ac3e19.png)

Even though it looks strange that one pod is increasing a lot faster than the others, all pods are slowly (but steadily) increasing the number of go routines.

**Comment by aledbf** [comment]
@ArthurSens do you know how to trigger the leak?

**Comment by ArthurSens** [comment]
Sorry @aledbf, I don't have that information. We still need to investigate 🙁

**Comment by aledbf** [comment]
@ArthurSens I profiled the `ws-daemon` component in production and find out this is not a leak. Each workspace creates a goroutine for the `daemon.sock` socket file.

**Comment by ArthurSens** [comment]
I'm not sure I understand how it explains it isn't a leak 🤔. The amount of goroutines is clearly increasing over time and will only go down after a restart. As you can see on the issue description, goroutines start at about a hundred and are only increasing as time passes. Reaching almost 500 avg in a week.


I just took another look at this same dashboard, and things are looking more troublesome after today's deployment! 

A restart happened, so all leaked go routines dropped, but the increase rate is a lot higher now:
![image](https://user-images.githubusercontent.com/24193764/113907538-df826a80-97ab-11eb-87c1-7abff84f9728.png)

**Comment by ArthurSens** [comment]
Maybe this [graph from the EU cluster](https://monitoring-new.gitpod.io/d/ws-daemon/gitpod-component-ws-daemon?orgId=1&from=now-7d&to=now&var-cluster=production.gitpod-io.europe-west1.03&var-node=All&var-pod=All&var-grpc_method=All&var-datasource=Metrics%20Long%20Term%20Storage) shows the difference better:

![image](https://user-images.githubusercontent.com/24193764/113907901-4bfd6980-97ac-11eb-9f83-3395b26374f7.png)

Amount of go routines are going to the roof after today's deployment
