### ISSUE TITLE
Server memory and "CPU leak"

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#3109]
### Describe the bug

`server` has memory and CPU leaks, as shown by our monitoring data. This leak, as time passes, can trigger OOM kills and high CPU saturation of meta nodes.

Memory:
![image](https://user-images.githubusercontent.com/24193764/106948327-53e85100-670a-11eb-8d24-34230d521288.png)

CPU:
![image](https://user-images.githubusercontent.com/24193764/106948349-5c408c00-670a-11eb-90db-27b7e3f0f638.png)

**Comment by AlexTugarev** [comment]
@ArthurSens could double-check this, please? I looked at the `Gitpod / Component / server` dashboard, it seems to be much better now.

**Comment by ArthurSens** [comment]
yep! Looks a lot nicer :)

I'll close this issue then

**Comment by princerachit** [comment]
I am reopening this issue as I can see that the issue still exists.
Currently deployed version [commit](eu.gcr.io/gitpod-core-dev/build/server:commit-b235c42cb698da0b5f8d7707e903d877fc4fb989) i.e. [main.1495](https://github.com/gitpod-io/ops/commit/88c19b313c9063101eb9bdefb05627e0e72c25f3)

![image](https://user-images.githubusercontent.com/32481722/135231517-e9957038-3fc9-417b-a192-90aa5744b828.png)

**Comment by JanKoehnlein** [comment]
Thanks for your thorough analysis. Unfortunately, we're currently swamped. Would you mind bringing it up again at a later stage?

**Comment by JanKoehnlein** [comment]
Memory and CPU consumptiob now seem pretty constant. It's a bit harder to see as we deploy more often now. 
We still have to investigate the server event loop lag  #7082

**Comment by ArthurSens** [comment]
> Memory and CPU consumptiob now seem pretty constant. It's a bit harder to see as we deploy more often now. We still have to investigate the server event loop lag #7082

Could continuous profiling help you folks? I tried to introduce it to monitoring-satellite some months ago but got some [pushback](https://github.com/gitpod-io/gitpod/pull/6131) back then. I'd be happy to continue the work with it can help the meta team
