### ISSUE TITLE
Arrow keys do not work on iPad slim folio case in editor

### ISSUE THREAD

**Issue by geraldthedev** [gitpod-io/gitpod#311]
**Describe the bug**
The normal function of using arrow keys to navigate the text in the editor does not work. The cursor does not move at all. Normal functions as tabbing works. 

**To Reproduce**
Connect to iPad to Slim folio case and attempt to use cursor in the editor. No other steps needed.

**Expected behavior**
The arrow keys should navigate through the editor the same as it would a normal text editor.

**Comment by hakeem1106** [comment]
Edit: the folio that I am directly working with is Logitech - Slim Folio Keyboard Folio Case for Apple® iPad

**Comment by hakeem1106** [comment]
Edit: Also, When attempting to use ctrl+c to stop a script from running in the terminal, it does not pickup the keystrokes, causing the user to have to close the page to stop the script from running.

**Comment by svenefftinge** [comment]
somewhat related: https://github.com/theia-ide/theia/issues/3557

**Comment by hakeem1106** [comment]
Thank you for the link to the similar case. Good to know it has come up before. I hope that this is something that can be pushed soon. Awesome way to use github without leaving github.

**Comment by nmccready** [comment]
YAAASS this fix would be amazing. Gitpod is amazing and making it close to a reality of leaving my laptop upstairs for code! Thanks for everyone’s hard work.

**Comment by jankeromnes** [comment]
Thank you @hakeem1106 for reporting this issue! I also own an iPad and slim folio keyboard case, and I was able to reproduce this issue.

I agree with you and @nmccready that the experience on iPad can be much improved, and I'd like to look into it, because this would be super helpful for me too.

**Comment by jankeromnes** [comment]
Update: I think that a good place to fix this would be in the Monaco editor itself (which lives inside the [vscode](https://github.com/Microsoft/vscode) repository), for example in [src/vs/base/browser/keyboardEvent.ts](https://github.com/Microsoft/vscode/blob/9ef682db65812bfbd5c45cc4472db73eb1855ba0/src/vs/base/browser/keyboardEvent.ts#L13-L166).

However, iPad bluetooth keyboard arrow keys are really weird to detect with JavaScript:
- When they're detected at all, they always seem to have `keyCode: 0`
- Using https://keycode.info/, I sometimes get events with `event.key` being something like `UIKeyInputUpArrow`, `UIKeyInputLeftArrow`, `UIKeyInputRightArrow` or `UIKeyInputDownArrow`, but if I focus on the text input, arrow key presses are no longer detected at all (as if the arrow keys just stop working)
- This [StackOverflow reply](https://stackoverflow.com/a/37403629) looks particularly grim, saying that it's impossible to reliably detect iPad arrow keys, and that we should use other keys like `WASD`
- However, this [other StackOverflow reply](https://stackoverflow.com/a/47719831) says it's detecting arrow keys on `keyup`/`keydown`

I'll see if I can somehow detect these from inside the Monaco editor.

**Comment by nmccready** [comment]
Also are any option to map keys anywhere? Example, Brydge Keyboard decided it would be lovely to not include the escape key.

**Comment by hakeem1106** [comment]
This looks like a step in the right direction. Full disclosure, I am still relatively new to some programming concepts which is a professional statement meaning, "I don't want to break anything" , but @jankeromnes seems to make a lot of sense. It would be nice to see if any other keyboards out there experience the same issue.

**Comment by jankeromnes** [comment]
Sadly, I can confirm that neither [onKeyUp nor onKeyDown](https://github.com/Microsoft/vscode/blob/ba304fe32c4ab647c92bb7063c638617a82321a6/src/vs/editor/browser/controller/textAreaHandler.ts#L241-L247) seem to get triggered by the bluetooth keyboard arrow keys. Every other key triggers `onKeyDown` just fine, e.g. any letters, numbers, `Backspace`, and even `Escape` which I trigger with `Fn`+(whatever that top left key is) because my French slim folio doesn't have a `[` key.

**Comment by jankeromnes** [comment]
Horrible idea: Maybe we could watch the cursor position in Monaco's `textarea` with something like this:

```js
document.querySelector('.inputarea').selectionStart
```

At least on desktop, the cursor position seems to change upon arrow key presses.

**Comment by jankeromnes** [comment]
See also https://github.com/xtermjs/xterm.js/issues/1101.

**Comment by meysholdt** [comment]
There is a bugreport (just fixed!) in Webkit for this issue:
https://bugs.webkit.org/show_bug.cgi?id=149054

**Comment by jankeromnes** [comment]
Hooray! I honestly didn't expect this UIKit bug to be fixed before the web-editors community completely switched to a workaround like CodeMirror's cursor-position-polling.

Now let's hope that the fix makes it to iOS updates pretty soon. 🤞

**Comment by hakeem1106** [comment]
Can confirm, arrow keys now work with Logitech iPad folio keyboard case. 👌🏾

**Comment by meysholdt** [comment]
yehaaa! :-D 

@hakeem1106, which version of iOS are you using?

**Comment by jankeromnes** [comment]
Wow, so soon? That's incredible 😛 I'm updating my iPad to see if I also get this fix.

**Comment by hakeem1106** [comment]
I updated to 12.2 and it worked. I believe that I pressed the keyboard icon in the editor first. There is a slight lag but it is not that bad.

**Comment by jankeromnes** [comment]
> I believe that I pressed the keyboard icon in the editor first. There is a slight lag but it is not that bad.

Wow, interesting, I hadn't noticed that icon before. When I tap it, it briefly flashes, but my arrow keys still won't work. Am I doing something wrong?

**Comment by hakeem1106** [comment]
It was working fine at one point. Now I cannot recreate it. I am not sure what is happening but I will keep testing.
