### ISSUE TITLE
Code does not open on windows machine

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3114]
See https://community.gitpod.io/t/workspace-wont-load-anymore/2684 for details.

**Comment by akosyakov** [comment]
@nojaf Could you check please whether it works for you in https://akosyakov-code-does-not-open-on-3114.staging.gitpod-dev.com/workspaces/? Don't forget to enable feature preview and select Code first.

**Comment by nojaf** [comment]
@akosyakov yes that worked for me!

**Comment by akosyakov** [comment]
We hope to release it by end of next week. For now you can use Theia, sorry for the inconvenience.

**Comment by nojaf** [comment]
It did see one error in the console of the browser but this might be unrelated.
`  ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/gitpod/.gitpod-code/User/snippets'`

**Comment by nojaf** [comment]
Many thanks for the quick response!

**Comment by akosyakov** [comment]
> It did see one error in the console of the browser but this might be unrelated.
ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/gitpod/.gitpod-code/User/snippets'

Yes, it is known. Thanks for noticing.

**Comment by akosyakov** [comment]
The fix should have been released today.

**Comment by geropl** [comment]
Just verified: It works on Windows 10 in Firefox and Edge.

**Comment by nojaf** [comment]
Worked for me as well. Many thanks!
