### ISSUE TITLE
[ws-scheduler] Schedules to nodes with not enough resources

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3116]
### Describe the bug
ws-scheduler schedules pods to nodes that don't have enough resources available to accommodate those pods. This leads to workspace failure because the kubelet rejects the pods.

![image](https://user-images.githubusercontent.com/3210701/107019368-dc660080-67a1-11eb-9a55-09666355c07b.png)

![image](https://user-images.githubusercontent.com/3210701/107020691-767a7880-67a3-11eb-8d83-20836e091099.png)
(note: the same workspace can count multiple times into the failure metric)

### Steps to reproduce
Produce a lot of load.

### Expected behavior
No workspace should fail.

**Comment by geropl** [comment]
Looks like `ws-scheduler` and `kubelet` do not agree on available resources. They differ for one of the nodes by a few MBs, generating the ongoing workspace start failures:
 1. [6247da5c-9d83-4715-b63a-f8b16498173a](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.container_name%3D%22ws-manager%22%0Aseverity%3DERROR%0AjsonPayload.status.conditions.failed%3D%22OutOfmemory:%20Pod%20Node%20didn't%20have%20enough%20resource:%20memory,%20requested:%201879048192,%20used:%2059638808576,%20capacity:%2061499482112%22%0Atimestamp%3D%222021-02-05T08:17:02Z%22%0AinsertId%3D%22rqz3yjfk5h7ms%22;summaryFields=jsonPayload%252Fstatus%252Fconditions%252Ffailed:false:32:beginning;timeRange=2021-02-05T08:17:00.000Z%2F2021-02-05T08:19:00.000Z?project=gitpod-191109): `requested: 1879048192, used: 59638808576, capacity: 61499482112`: 18MB
 2. [977952dc-7292-45a0-8d4d-2018341f5e39](https://console.cloud.google.com/logs/query;pinnedLogId=2021-02-05T08:17:02Z%2Frqz3yjfk5h7ms;query=resource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.container_name%3D%22ws-manager%22%0Aseverity%3DERROR%0AjsonPayload.status.conditions.failed:%22OutOfmemory%22%0Atimestamp%3D%222021-02-05T08:16:34Z%22%0AinsertId%3D%22yynkoxfj97zrl%22;summaryFields=jsonPayload%252FinstanceId:false:32:beginning;timeRange=2021-02-05T08:16:00Z%2F2021-02-05T08:19:00Z?project=gitpod-191109): `requested: 1879048192, used: 59638808576, capacity: 61499482112`: 18MB
