### ISSUE TITLE
EU - Ports stuck on detecting when trying to run preview server

### ISSUE THREAD

**Issue by armedcor** [gitpod-io/gitpod#3118]
### Describe the bug
An issue affecting a number of our students, when trying commands to run a preview server ports are stuck on detecting and not opening a port. The issue seems intermittent and isn't affecting every student. All from the EU region so far.

python3 -m http.server
running a flask file
running Django runserver

All affected by the issue.

**Comment by J-O-B** [comment]
Same issues experienced on my side. Trying to run a Python file, tried other filetypes too to no avail.

**Comment by madatoo** [comment]
I cant open 8000 port at all. When I run command python3 -m http.server I get info about that the 33060 – detecting...
3306 – detecting...
8000 – open (private)  even if I close a workspace and run them from begining than everything looks the same as prevoiusly

**Comment by AlexTugarev** [comment]
@armedcor it appears to be a high load on `Open Port` requests. We're monitoring this. 

Unfortunately, there is no instant workaround for this, but pause retrying for a short while.

**Comment by shiva123-coder** [comment]
Same issue - trying to open the page using python3 -m http server command , its not responding at all

**Comment by jankeromnes** [comment]
Added incident to status page: http://status.gitpod.io/incidents/00105e14

**Comment by aineon** [comment]
having the same issue here

**Comment by byIlsa** [comment]
Same issue, with Python (python3 -filename-) Port not being detected

**Comment by devtoguk** [comment]
Same here:  python3 manage.py runserver    No ports being detected

**Comment by thirdelement** [comment]
Same - no ports opening

**Comment by HMTRIVEDI** [comment]
Same - issue 

No port

**Comment by Gwen-of-lynn** [comment]
I'm affected too, the pop up to open the port isn't opening, if that helps.

**Comment by thebiondGithub** [comment]
Same Issue - Detecting Port running

**Comment by gretaegan** [comment]
Same issue here, detecting for about an hour now.

**Comment by IvanTepes** [comment]
Same Issue - Detecting Ports

**Comment by HollyC7** [comment]
Same issue also

**Comment by akosyakov** [comment]
We are still investigating the issue. Please for time being list important ports in the gitpod config, push changes and restart the workspace: https://www.gitpod.io/docs/config-ports/#exposing-ports It will auto expose configured ports on the startup.

**Comment by Sxpherr** [comment]
I can’t open workspaces...

**Comment by mahmoudajawad** [comment]
Observation: although this issue is flagged with `EU` it seems more like affecting me in the evenings only when `US` timezone hits the working hours, as I'm in the Arab Region, I didn't know of this issue until yesterday evening when I worked in the evening, but it worked for me in the mornings of Saturday and Sunday.

It is clear the issue explains the issue being related to number of available ports,but I wanted to share my observation. Also, the proposed fix here didn't work for me yesterday when I faced the issue.

**Comment by Wings30306** [comment]
Reported issues running Django projects (see first comment in thread) still ongoing.

**Comment by akosyakov** [comment]
The incident was resolved by today deployment. Please open a new issue if you still observe issues with ports.

**Comment by mqsaud** [comment]
I have issue port 8000 stuck on detecting

**Comment by akosyakov** [comment]
@mqsaud sounds like https://github.com/gitpod-io/gitpod/issues/6778 ?
