### ISSUE TITLE
[code] terminals stop working

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3127]
I was coding along in a workspace with vscode, when out of the sudden the terminals didn't work anymore. I tried starting new ones, which hung. After reload no terminal could be initialized anymore. WS ID: cyan-halibut-1rlncq8l

**Comment by svenefftinge** [comment]
I haven't seen this recently in staging.

**Comment by akosyakov** [comment]
I moved it to March, since I need to rewrite terminals again.

**Comment by akosyakov** [comment]
I was able to debug server and it is indeed hangs on list terminals request to the supervisor.

**Comment by akosyakov** [comment]
I had it again on staging, [see workspace logs](https://github.com/gitpod-io/gitpod/files/6207473/ws.log)

New unexpected errors:
```
2021/03/25 19:48:50 WARNING: proto: file "workspace.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

```
[91m[main 2021-03-25T19:49:04.787Z][0m code server: 1:a0892a22-e4c0-4e33-a64c-5d71ff3d3334 terminal: resize failed: Error: 14 UNAVAILABLE: Stream refused by server
    at Object.callErrorFromStatus (/ide/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/ide/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/ide/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/ide/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /ide/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 14,
  details: 'Stream refused by server',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}
```

**Comment by csweichel** [comment]
That's really rather odd. The only two components that sport a `workspace.proto` are ws-daemon and content-service. I'm somewhat doubtful that the double registration message you're seeing is related to this issue.

**Comment by Baneeishaque** [comment]
Issue is still there.

**Comment by jyotsnaSharma10** [comment]
I am still facing this issue but for my colleague its working fine
<img width="628" alt="Screenshot 2021-07-16 at 5 59 24 PM" src="https://user-images.githubusercontent.com/87467825/125947779-a452c587-7ed6-4a70-8677-1838ad1ae363.png">

**Comment by akosyakov** [comment]
@jyotsnaSharma10 Could you create a new issue please? Could you share workspace id, thanks.
