### ISSUE TITLE
Error 504 when trying to access my work space in Gitpod. 

### ISSUE THREAD

**Issue by Gwen-of-lynn** [gitpod-io/gitpod#3130]
Please search existing issues to avoid creating duplicates. 

### Describe the bug
 Currently it's appearing as Error 504 for me. Gitpod stopped allowing me to push, then when I tried stopping and restarting the workspace it said my workspace was not accessible(paraphasing) at this time. I cleared cache and cookies. Again it did not allow access. Reset the computer and tried again. Now I am getting error 504 after logging in.

### Expected behavior
I expect to be able to push code from gitpod to github. And to be able to access my workspace to complete my projects.

### Example repository
 Cannot access any of my repos atm

**Comment by JonathanTreffler** [comment]
I think i am affected by the same issue.
I cannot push to github, the gitpod.io just shows the background color with no content.

**Comment by cfconor** [comment]
Having the same issue! Error 504 after sometime. Accessing from EU if that helps bugfixing. 

I have deleted all cookies and cached items, signed out of Gitpod and Github, and tried signing back in but the error is consistent. 

Hopefully its an easy fix as I have a college project due in 48 hours!

**Comment by gtsiolis** [comment]
Closing, see https://github.com/gitpod-io/gitpod/issues/3128#issuecomment-774673730.
