### ISSUE TITLE
Workspaces not opening

### ISSUE THREAD

**Issue by MihaelaVacarus** [gitpod-io/gitpod#3133]

**Comment by Pipicallu** [comment]
My workspace went offline, when I tried rebooting it, it would not work. I have tried clearing my browser cache and history and its still not  loading. gitpod.io returns a blank page

**Comment by gtsiolis** [comment]
Closing, see https://github.com/gitpod-io/gitpod/issues/3128#issuecomment-774673730.

**Comment by MihaelaVacarus** [comment]
Hi George,

I am still experiencing issues, my workspace is not opening at all.

![image](https://user-images.githubusercontent.com/71561380/107345044-147b8500-6abb-11eb-963a-174f5feff403.png)

Could you please give me an update of the status?

Thanks

**Comment by gtsiolis** [comment]
Hi @MihaelaVacarus! This seems to be unlrelated with the service incident that happened the other day.[[1](https://status.gitpod.io/incidents/758dc907)][[2](https://status.gitpod.io/incidents/d7c4f798)]

Have you tried logging inusing an icognito browser window? if the problem persists, please open a new issue about this and add as much details as possible following the steps in the issue description.

**Comment by MihaelaVacarus** [comment]
Thanks, that's really weird, it opens from an incognito window now.

**Comment by MihaelaVacarus** [comment]
Hi George, 

Apologies for the multiple messages, but I can't seem to be able to push my commits:

![image](https://user-images.githubusercontent.com/71561380/107401930-4c0a2180-6afb-11eb-8ef4-ddd0b7e604ab.png)

Could you please advise?

Thanks

**Comment by akosyakov** [comment]
@MihaelaVacarus Have you tried to press `Grant Permissions` in the notification?
