### ISSUE TITLE
JSX Syntax not working

### ISSUE THREAD

**Issue by juliolugo96** [gitpod-io/gitpod#314]
**Describe the bug**

JSX syntax not working when I create a file with this extension.

**To Reproduce**

Open a file with .jsx extension

**Expected behavior**

Highlight code with specified syntax.

**Comment by sr229** [comment]
JavaScript supersets are not exactly supported yet in Theia.

**Comment by sr229** [comment]
AFAIK JSX is not yet supported but can be in a future plugin support via VS Code extensions. The only JS superset with integration to Theia, which is native to Monaco, is TypeScript

**Comment by svenefftinge** [comment]
That is not true. JSX as well as TSX is support. I'll look into it, thanks for creating the issue.

**Comment by svenefftinge** [comment]
I tried to reproduce but couldn't.
For instance the snapshot below contains js files with JSX components in it.
Works for me. Could you clarify what is not working and maybe share a repository to reproduce?

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/f7398860-f524-4dc9-9a07-886b503237cb)

**Comment by juliolugo96** [comment]
Hello. Thank you for replying.

Yeah, I actually did exactly what you do there: I used 'JavaScript' Language Mode, and it solved the JSX issue.

However, there's a problem that occurs when I select 'JavaScript React' in the Language Mode: syntax doesn't highlight. By default, when I create a file with .jsx extension (MyComponent.jsx, for example), 'JavaScript React' is established as Language by the editor, and JSX syntax is not highlighted in this new file. Take a look:

![screenshot from 2019-02-18 19-45-50](https://user-images.githubusercontent.com/35197161/52981402-f2f8ce80-33b5-11e9-8350-db56f809b27a.png)

**Comment by svenefftinge** [comment]
Ok, thank you, so it is broken with *.jsx files. We'll look into it.

**Comment by burmester** [comment]
Upvote on this!

**Comment by svenefftinge** [comment]
This works now.
