### ISSUE TITLE
First Week: February 2021

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3145]
As part of our development process we run a special "first week" at the beginning of every iteration. In this week we'll tend to pressing issues that arouse during the last iterations endgame and post-deployment.

### First Week Changes (deployed already)
- https://github.com/gitpod-io/gitpod/pull/3081/commits/4c0386120791e0502d1b1a93fad0db74a6696a5a Provide subscription queue metric
- https://github.com/gitpod-io/gitpod/pull/3096/commits/e4f611df36027710ecd58b2cdeb0f9a330f9943d [ws-manager] Replace our own gRPC prom metrics with grpc_ecosystem
- https://github.com/gitpod-io/gitpod/pull/3096/commits/1af286261c9f6c7ff450922f4889452f86d418ef [metrics] Add call metrics to all gRPC services
- https://github.com/gitpod-io/gitpod/commit/8da435d6dca84ec44072618c1d5e649c3802b074 [code] fix user data URI on windows machine
- https://github.com/gitpod-io/gitpod/commit/2cab99e5e740fdc7c05470da7e0f8d8e3efa9d62 handle expose port rate limiting in the supervisor

### Things to test

- Test that Code starts on Windows
- Smoke tests ports

**Comment by geropl** [comment]
- https://github.com/gitpod-io/gitpod/pull/3151: Improve update DBUserStorageResource

**Comment by AlexTugarev** [comment]
This is done, right?

**Comment by csweichel** [comment]
> This is done, right?

Yes :)
