### ISSUE TITLE
Gitpod is not reachable in EU

### ISSUE THREAD

**Issue by megmog88** [gitpod-io/gitpod#3146]

**Comment by jasonford** [comment]
+1. On EU cluster like yesterday in case that's useful

**Comment by corneliusludmann** [comment]
Thanks for reporting. We are currently investigating an incident in EU.

**Comment by corneliusludmann** [comment]
Here is a short update on this incident:

We are still investigating an unusually high load on our servers and database in the EU. We decided to switch our load balancer to the US cluster. However, this leads to petty low performance for EU customers. You could give it a try and report your experiences here.

Sorry again for the inconvenience and thanks for your patience. I'll keep you updated.

**Comment by byIlsa** [comment]
Workspace start looks to be hanging in some 'loop' on starting. 
![Screenshot from 2021-02-08 11-56-06](https://user-images.githubusercontent.com/63145628/107210651-ba1fed00-6a04-11eb-9935-773f38ba90ce.png)

**Comment by MarvinJWendt** [comment]
I currently have the problem, that I cannot upgrade my subscription to Pro (via GitHub Education). I would guess it has something to do with the current issue. Just letting you guys now :)

**Comment by byIlsa** [comment]
I have a workspace now yay! Seems that now the port issue arises in my case :) Thanks for the hard work. This must be a big pain in the behind for you guys...

**Comment by megmog88** [comment]
The workspaces seem to be working now its just I don't want to do all my work and not be able to save it!

________________________________

**Comment by corneliusludmann** [comment]
> I currently have the problem, that I cannot upgrade my subscription to Pro (via GitHub Education). I would guess it has something to do with the current issue. Just letting you guys now :)

Yes, that's related. Subscriptions do not work at the moment. Thanks for letting us know! :+1: 



> I have a workspace now yay! Seems that now the port issue arises in my case :) Thanks for the hard work. This must be a big pain in the behind for you guys...

That's great! Sorry for the port issue. We are still working on this. Thanks for the warm words! :heart:

**Comment by corneliusludmann** [comment]
> The workspaces seem to be working now its just I don't want to do all my work and not be able to save it!

@megmog88: Do you have the workspace with the unsaved work still open? Do you have a blue status bar. What happens when you try to save your work? Could you give me your workspace ID?

**Comment by KelvinHere** [comment]
Europe here, my workspaces are opening now but all my ports are stuck on "Detecting"
![detecting](https://user-images.githubusercontent.com/55555369/107223821-906bc380-6a0e-11eb-80fb-24d18c198b6f.JPG)

**Comment by corneliusludmann** [comment]
@KelvinHere: Thanks for reaching out. It's this issue: https://github.com/gitpod-io/gitpod/issues/3118#issuecomment-774058247

**Comment by Keep-Going-HyeonSoo** [comment]
> Europe here, my workspaces are opening now but all my ports are stuck on "Detecting"
> ![detecting](https://user-images.githubusercontent.com/55555369/107223821-906bc380-6a0e-11eb-80fb-24d18c198b6f.JPG)
> 
> Describe the bug - Open any workspace and ports stick on detecting
> Steps to reproduce - Open any workspace
> Expected behavior - Ports stick on detecting
> Additional information - Tried usual, clearing cache, waiting an hour

Same here 😭

**Comment by ArthurSens** [comment]
A quick update, EU cluster is back up like some of you have already noticed :) 

The issue with ports are still being investigated.

**Comment by j0nes2k** [comment]
Possibly related: I cannot start my old workspaces, I get the error "Error: User is unauthorized"

**Comment by corneliusludmann** [comment]
@j0nes2k That sounds unrelated to this issue. Do you see your workspaces in the dashboard https://gitpod.io/workspaces/?

**Comment by j0nes2k** [comment]
@corneliusludmann  Yes - I see all of them and could also reload this page. I tried several workspaces, all of them had the same error. 
Only after trying to launch a fresh workspace directly from Gitlab solved the issue - I had to reauthenticate, and then everything went wine.

**Comment by jankeromnes** [comment]
@j0nes2k Glad you were able to regain access to your workspaces! This sounds like the Gitpod-to-GitLab authentication needed to be refreshed. If this re-occurs in the future, could please open a dedicated issue for it? Also, https://gitpod.io/access-control/ can always help you audit & manage which permissions are granted for which Git host.

Closing this issue since the incident has been resolved. Many thanks everyone for your help & understanding! ❤️

**Comment by Anthony-Gomez** [comment]
If this issue is resolve and that there is no more degraded Performance for workspaces,
update your status page (https://status.gitpod.io) please :)
