### ISSUE TITLE
remote: Invalid username or password. fatal: Authentication failed for (repo)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3148]
### Describe the bug

Occasionally, when I try to push to one of my repositories from GitHub, it takes a while then fails with something like:

```
$ git push origin jx/updates 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/open-vsx/publish-extensions.git/'
```

Stopping and restarting the workspace seems to fix it.

**Comment by jankeromnes** [comment]
More context from internal chat:

> Once git fails to authorize, I’ve seen it doesn’t recover. Instead it starts asking for password. Though it should after a while.
I’ve seen that when GitHub wasn’t alright.

> hm, GitHub seems to be alright

> `Request getWorkspace unsuccessful: 403/"operation not permitted: missing get permission on workspace"` in the logs

**Comment by AlexTugarev** [comment]
> missing get permission on workspace

@csweichel, this seems to be an issue with workspace token, no?
