### ISSUE TITLE
Unable to Signup or Login to gitpod.io via github account

### ISSUE THREAD

**Issue by tshcherban** [gitpod-io/gitpod#3149]
### Describe the bug
I'm unable to login to gitpod neither via github nor bitbucket/gitlab. 

### Steps to reproduce
1. go to https://www.gitpod.io/
2. press 'login' and select any of three options
3. login with your credentials

### Expected behavior
gitpod is loaded

### Additional information
Im observing error 504

### Example repository
Firstly i was trying this repo:
https://gitpod.io/#https://github.com/arendst/Tasmota/tree/development

**Comment by MarvinJWendt** [comment]
Hi, GitPod is currently some problems. They are on it :)
https://status.gitpod.io/

**Comment by corneliusludmann** [comment]
Thanks for reporting. Please follow this issue: https://github.com/gitpod-io/gitpod/issues/3146

I'll close this as a duplicate. Sorry for the inconvinence.
