### ISSUE TITLE
Agreeing to Terms of Service after viewing them

### ISSUE THREAD

**Issue by mikehcox** [gitpod-io/gitpod#315]
**Describe the bug**
Clicked on link to Terms of Service and read them.
Checked box agreeing to Terms of Service.
Clicked on submission.
Said something bad happened

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Comment by mikehcox** [comment]
?

**Comment by meysholdt** [comment]
Hi Michael! 

thank you for reporting this. The expected behaviour is that nothing bad happens and you can use Gitpod. 
Is this happening repeatedly and is it preventing you from opening a Gitpod workspace?

**Comment by geropl** [comment]
Hello @mikehcox, I just tried to reproduce the issue with a fresh GitHub account but could not reproduce it. Does it happen repeatedly?

**Comment by mikehcox** [comment]
No, it's not happening repeatedly.

**Comment by AlexTugarev** [comment]
@meysholdt, @geropl, I think we can avoid similar issues by displaying ToS without redirecting.

**Comment by AlexTugarev** [comment]
@mikehcox, we might identified the cause. To confirm this, please share some details on your browser. It would be very helpful to know the vendor, version, and especially the privacy settings for cookies etc.. Thanks!

**Comment by mikehcox** [comment]
This will probably make your lives difficult...

On Linux, I mostly use Chrome (Version 72.0.3626.119 (Official Build) (64-bit) currently under Fedora 29), and less often, I use Firefox Quantum (65.0.1 (64-bit) Mozilla Firefox for Fedora - fedora 1.0).  On Windows 10, I mostly use Chrome (Version 72.0.3626.121 (Official Build) (64-bit)), sometimes Chrome Canary, although I'm moving away from that.  Rarely do I use Firefox Quantum on Windows, but I have it installed.  Was there any info transmitted to you all about my environment when it failed?

Privacy settings on Chrome, Fedora are:

Google Chrome may use web services to improve your browsing experience. You may optionally disable these services. Learn more

Allow Chrome sign-in
By turning this off, you can sign in to Google sites like Gmail without signing in to Chrome

Use a prediction service to help complete searches and URLs typed in the address bar

Use a prediction service to load pages more quickly

Use a web service to help resolve navigation errors

Safe Browsing
Protects you and your device from dangerous sites

Help improve Safe Browsing
Sends some system information and page content to Google

Automatically send usage statistics and crash reports to Google

Use a web service to help resolve spelling errors
Smarter spell-checking by sending what you type in the browser to Google

Send a "Do Not Track" request with your browsing traffic

Allow sites to check if you have payment methods saved

Manage certificates
Manage HTTPS/SSL certificates and settings

Content settings
Control what information websites can use and what content they can show you

Clear browsing data
Clear history, cookies, cache, and more

**Comment by AlexTugarev** [comment]
The fix is deployed.
