### ISSUE TITLE
Gitpod not working

### ISSUE THREAD

**Issue by emiberndt** [gitpod-io/gitpod#3150]
Hi.

I currently can neither create new workspaces nor access the workspaces site from Gitpod.
When I try to open the workspaces site I see a blank page, but no errors in the dev console or on the network.

When I try to open a new workspace by prefixing my repo with gitpod.io 1 It says “Sorry, something went wrong. Error: Connection got disposed”

Kind regards,
Em

**Comment by corneliusludmann** [comment]
Thanks for reporting. We are currently investigating an issue in EU.

See also:
- Duplicate of: https://github.com/gitpod-io/gitpod/issues/3146
- http://status.gitpod.io/incidents/d7c4f798

**Comment by emiberndt** [comment]
Ok! Thank you for the info! :)
