### ISSUE TITLE
Downloading workspaces no longer works (404 page)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3152]
### Steps to reproduce

1. Click to Download a workspace (from dashboard or admin panel)

### Expected

Download button downloads the latest workspace backup.

### Actual behavior

Download button opens https://gitpod.io/workspace-download/get/a53fb195-176b-4e30-93a0-9229f2d2ed75 which is a 404 page:

<img width="1440" alt="Screenshot 2021-02-06 at 20 38 45" src="https://user-images.githubusercontent.com/599268/107128148-98671e80-68bb-11eb-8908-5aae29369f99.png">

**Comment by csweichel** [comment]
will be fixed in #3288

**Comment by ArthurSens** [comment]
Shouldn't we close the issue only when the fix is merged? Since the bug is still present, I was looking for an open issue to see the discussion 😬

**Comment by gtsiolis** [comment]
Reopening this for visibility as there have been a few reports about this issue.

1. https://community.gitpod.io/t/why-i-cant-download-my-repository-from-gitpod/2805
2. https://community.gitpod.io/t/attempting-to-download-an-workspace-archive-gave-me-404-errors/2831
3. https://community.gitpod.io/t/page-not-found-when-clicking-on-download/2902
