### ISSUE TITLE
Request openPort is not allowed -> detecting port error

### ISSUE THREAD

**Issue by bilalshahzad139** [gitpod-io/gitpod#3154]
### Describe the bug
We've upgraded our self-hosted env from 0.5.0 to 0.6.0. We faced different issues but eventually, workspaces are opening and running. But we see error "5000 - detecting" in "Open Ports" section. I've checked the logs of the server and see the following error

Request openPort is not allowed

### Expected behavior
openPorts should show Ports in open mode with the relevant setting (e.g. Open Preview, Open Browser)

**Comment by Hentra** [comment]
We are experiencing the same behaviour. You mentioned in #3118 that this is fixed in the EU instances of gitpod.io. Will there be a hotfix for self-hosted?

**Comment by geropl** [comment]
@bilalshahzad139 @Hentra  Thx for reporting!

This should be fixed with the [current 0.8.0 release](https://github.com/gitpod-io/gitpod/releases/tag/v0.8.0).

Please re-open if that's not the case! :pray:
