### ISSUE TITLE
Websocket Connection Error

### ISSUE THREAD

**Issue by elielam** [gitpod-io/gitpod#3157]
### Describe the bug

I followed the tutorial on gitpod.io/docs and my self hosted gitpod don't load.
It seem to be a problem with websockets.
I don't understand how ws-proxy handle connection from ws.gitpod.domain.tld.

![image](https://user-images.githubusercontent.com/34446626/107372005-3c7fde00-6ae5-11eb-8ac0-10b861ffef22.png)

gitpod.domain.tld don't load like gitpod.domain.tld/login and gitpod.domain.tld/workspaces

### Steps to reproduce

Install Gitpod on vanilla Kubernetes following the procedure describe in docs.

### Expected behavior

Working gitpod instance.

### Additional information

Ubuntu 20.04
Microk8s
Helm 3
MetalLB

DNS Setup : 
gitpod.domain.tld
*.gitpod.domain.tld
*.ws.gitpod.domain.tld

Console error : 
WebSocket connection to 'wss://gitpod.domain.tld/api/gitpod' failed: Error during WebSocket handshake: Unexpected response code: 302

I don't find answers in already opened issues.
Sorry if I duplicate and for my poor english.

Additionals :

_values.yml_

    gitpod:
      # This field must be set to your domain name. Leaving it set to its default value will result in
      # a non-functional installation.
      hostname: gitpod.domain.tld
    
      # If you have a static IP that your domain resolves to, set it here.
      # Leaving this field set to its default value is fine. Kubernetes will assign you an IP address
      # during deployment.
      components:
        proxy:
          loadBalancerIP: public_ip
          serviceType: LoadBalancer
    
      # Gitpod needs at least one auth provider to allow users to log in.
      # The auth providers below are examples only. Please change/remove them to fit your installation.
      authProviders:
      - id: "Example Github"
        host: "github.com"
        protocol: "https"
        type: "GitHub"
        oauth:
          clientId: "your-client-ID-here"
          clientSecret: "your-client-secret-here"
          callBackUrl: "https://your-domain.com/auth/github/callback"
          settingsUrl: "https://github.com/settings/connections/applications/your-client-ID-here"
      - id: "Gitlab"
        host: "gitlab.domain.tld"
        protocol: "https"
        type: "GitLab"
        oauth:
          clientId: "xxxx"
          clientSecret: "yyyy"
          callBackUrl: "https://gitlab.domain.tld/auth/gitlab/callback"
          settingsUrl: "gitlab.domain.tld/profile/applications"
    
      # RBAC is enabled by default. If your cluster does not use RBAC, set this flag to false so that
      # we do not attempt to install PodSecurityPolicies and the likes.
      installPodSecurityPolicies: true

_kubectl get pods,svc_

![pods](https://user-images.githubusercontent.com/34446626/107277086-3db4fa80-6a54-11eb-9457-12ee1210110a.PNG)

_loadbalancer_

![loadbalancer](https://user-images.githubusercontent.com/34446626/107276568-80c29e00-6a53-11eb-9448-cab1c81d22a8.png)

_ws-daemon_

![ws-daemon-logs](https://user-images.githubusercontent.com/34446626/107276592-8d46f680-6a53-11eb-87ad-ea567850b687.PNG)

_ws-manager-bridge_

![ws-manager-bridge-logs](https://user-images.githubusercontent.com/34446626/107276617-98018b80-6a53-11eb-880d-8bfd2130c028.PNG)

_ws-manager_

![ws-manager-logs](https://user-images.githubusercontent.com/34446626/107276635-9e900300-6a53-11eb-89a1-fe1edc94085a.PNG)

_ws-proxy_

![ws-proxy-logs](https://user-images.githubusercontent.com/34446626/107276673-aa7bc500-6a53-11eb-8e97-ef5bd23e28d2.PNG)

_ws-scheduler_

![ws-scheduler-logs](https://user-images.githubusercontent.com/34446626/107276688-afd90f80-6a53-11eb-86e5-7ca9acbeb79c.PNG)

**Comment by elielam** [comment]
Can someone can help me ?

**Comment by elielam** [comment]
UP please, I'm still stuck !

I tried a lot of things but it's still not working.

https://community.gitpod.io/t/self-hosted-k8s-error-during-websocket-handshake-302/1627
https://github.com/gitpod-io/gitpod/issues/2239
https://github.com/gitpod-io/gitpod/issues/470
https://community.gitpod.io/t/cant-get-websocket-connection-up/1007

**Comment by elielam** [comment]
resolved

**Comment by orellabac** [comment]
@elielam How did you solved this in the end ?

**Comment by batleforc** [comment]
For the one like me who is still searching for an answer, we are in the first case of this link : https://www.gitpod.io/docs/self-hosted/latest/troubleshooting
We need in this case to add two folders (well, i had to) .
So to make it short, your likely to add:
```yaml
components:
  wsDaemon:
    containerRuntime:
      nodeRoots:
        - /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v2.task/k8s.io
        - /var/snap/microk8s/common/var/lib/containerd/io.containerd.runtime.v2.task/k8s.io
 ```

In your values.custom.yaml
