### ISSUE TITLE
[ws-scheduler] Replace ws-scheduler with a scheduler plugin

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3159]
We originally introduced ws-scheduler to improve cloud density and hence operating cost. Since, ws-scheduler has taken on other responsibilities, namely:
- required services which ensures that e.g. ws-daemon and registry-facade are running on a node before scheduling a workspace pod there. We introduced this because ws-scheduler does not support affinity.
- scaling and ghosts which we aim to use for improving workspace startup time/scale ahead. They are our own attempt at preemtive scheduling, something that [Kubernetes supports OOTB](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/). 

The custom scheduling strategy is something we could also implement using the [scheduling framework](https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/) were introduced. They allow out-of-tree scheduling decisions to be made. This would free us from having to maintain our own scheduler and bring is back in line with regular Kubernetes.

On managed Kubernetes, we might still have to deploy our own scheduler, but could be using the Kubernetes scheduler + our own plugin.

**Comment by geropl** [comment]
Albeit this sounds promising let's have a look at the details together if this is viable. Before one of the first attempts with `ws-scheduler` tried to re-use the scheduling framework from kubernetes, but back then (and with our knowledge from that time) the framework was too unwieldy to use.

> They allow out-of-tree scheduling decisions to be made

This is not new, but AFAIU this only works if you have control over the master. But I might be wrong/outdated here.

FWIW: Today I read through the preemption code of Kubernetes and applied their approach to ghosts. It lead to complete removal of the async binding (less and easier code) and adds priorities.

**Comment by geropl** [comment]
Fixed with: https://github.com/gitpod-io/gitpod/pull/3168
