### ISSUE TITLE
[gp] Support `gp env` by talking to server directly

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#3162]
I've faced with the issue that doesn't allow to read or write any env variable by using gp cli

1. Set Code as a default editor 
2. Open repo https://github.com/stripe-samples/firebase-subscription-payments
3. `gp env` it will produce the error `cannot get environment variables: not found`
4. `gp env foo=bar` it will produce the error `cannot get environment variables: not found`

![image](https://user-images.githubusercontent.com/1110697/107477735-f5dfc180-6b80-11eb-9fb8-353c5755d4d9.png)

```bash
Version: 1.52.1
Commit: 791d97eab4a4d591cc12a4784bf263088968c6d3
Date: 2021-02-05T11:45:08.161Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 OPR/74.0.3911.75
```

**Comment by corneliusludmann** [comment]
Thanks for reporting!

/cc @akosyakov

**Comment by akosyakov** [comment]
We should generally refactor GP to decouple it from Theia as much as possible, i.e. everything besides open and preview.

**Comment by csweichel** [comment]
Indeed, gp should talk to server directly. We need to take great care to not simply give the workspace token power access to all the user's environment variables.

**Comment by csweichel** [comment]
> We should generally refactor GP to decouple it from Theia as much as possible, i.e. everything besides open and preview.

Very much agree. We should also file issues for those individual work items :)

**Comment by csweichel** [comment]
We should to this in two PRs:
- make env var API on server resource scope aware (introduce repository pattern based resource scopes for env vars)
- make `gitpod-cli` talk to server directly using the workspace token from supervisor

**Comment by geropl** [comment]
(BTW: This is an enabler for frontend-less integration tests that check nontrivial stuff inside your workspaces (e.g., are access right configured correctly).
