### ISSUE TITLE
Cannot install chromium-browser with sudo

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#3167]
$ sudo apt-get update
    $ sudo apt-get install chromium-browser
    $ chromium-browser
        Command '/usr/bin/chromium-browser' requires the chromium snap to be installed.
        Please install it with:
        snap install chromium
    $ sudo snap install chromium
        error: cannot communicate with server: Post http://localhost/v2/snaps/chromium: dial unix /run/snapd.socket: connect: no such file or directory

**Comment by corneliusludmann** [comment]
Related: https://github.com/gitpod-io/gitpod/issues/1413, https://github.com/gitpod-io/gitpod/issues/2078

**Comment by ArthurSens** [comment]
Hi @markfirmware, thanks for the report!

As @corneliusludmann mentioned, it looks like this issue is a duplicate. I'm closing this one just so we can centralize the discussion on a single place :slightly_smiling_face:
