### ISSUE TITLE
My 'F1 > Fork' option is wrongly set to another fork

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#317]
**Describe the bug**
My 'F1 > Fork' option is wrongly set to another fork:
<img width="602" alt="screenshot 2019-02-18 at 18 31 48" src="https://user-images.githubusercontent.com/599268/52967817-8a0c5900-33ab-11e9-9660-8e646cb30b61.png">

**To Reproduce**
1. Pre-fork https://github.com/JanitorTechnology/janitor
2. Open upstream in Gitpod: https://gitpod.io/#https://github.com/JanitorTechnology/janitor
3. Press `F1`, type "fork"
4. The "Switch to my fork" option is set to https://github.com/arshdkhn1/janitor, which is not my fork

**Expected behavior**
The "Switch to my fork" option should be correct, it should be set to https://github.com/jankeromnes/janitor.

I suspect this is because `arshdkhn1/janitor` is a [sub-fork](https://github.com/JanitorTechnology/janitor/network/members)? Maybe we don't handle those properly.

**Comment by AlexTugarev** [comment]
@jankeromnes, I cannot reproduce it.

done 1.-3., now at 4. 

![screen shot 2019-02-18 at 17 18 02](https://user-images.githubusercontent.com/914497/52963885-46145680-33a1-11e9-881b-c4c2ba330080.png)

even for `gitpod.io/#https://github.com/arshdkhn1/janitor` I get a proper list:

![screen shot 2019-02-18 at 17 17 29](https://user-images.githubusercontent.com/914497/52963923-5f1d0780-33a1-11e9-81f9-37836b6b776b.png)

please, help me to reproduce this ;-)

**Comment by AlexTugarev** [comment]
@jankeromnes, was it maybe a shared workspace?

**Comment by jankeromnes** [comment]
@AlexTugarev Thanks for looking into it! Strange that you can't reproduce it.

It was not a shared workspace. Running steps 2 and 3 still give me:
<img width="602" alt="screenshot 2019-02-18 at 18 31 48" src="https://user-images.githubusercontent.com/599268/52967817-8a0c5900-33ab-11e9-9660-8e646cb30b61.png">

Also, my earlier screenshot is misleading, because I took it *after* doing `Switch to my fork of janitor -- arshdkhn1/janitor`. As you can see in the more recent screenshot above, only the entry for "my fork" is wrong.

**Comment by jankeromnes** [comment]
Maybe it helps if I share a snapshot of the problematic workspace:

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/d938528a-17fb-4448-a205-6e8531f4e90d)

**Comment by jankeromnes** [comment]
Current theory, after chatting with @AlexTugarev: This bug is probably related to the fact that I have write access to `arshdkhn1/janitor` (Gitpod seems to think that that's "my fork", because GitHub includes it in the list of "repositories owned by my account").
