### ISSUE TITLE
no DOCKER_HOST environment variable

### ISSUE THREAD

**Issue by rumeshmadhusanka** [gitpod-io/gitpod#3172]
### Describe the bug

My project uses fabric docker plugin
It doesn't work on GitPod

### Steps to reproduce

1. Open https://github.com/wso2/product-microgateway/tree/envoy-gw on GitPod
2. Run mvn clean install
![Screenshot from 2021-02-11 16-02-07](https://user-images.githubusercontent.com/32504465/107625586-894ceb80-6c82-11eb-9e76-f0c3a4d3d213.png)

`ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.34.1:build (docker-build) on project adapter: Execution docker-build of goal io.fabric8:docker-maven-plugin:0.34.1:build failed: No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured -> [Help 1]`

### Expected behavior

mvn to build properly
### Example repository

 https://github.com/wso2/product-microgateway/tree/envoy-gw

**Comment by ArthurSens** [comment]
Hi @rumeshmadhusanka :wave:

I think that you just forgot to run `sudo docker-up` before running your build process :)

I've recorded a quick video just to show you how to do it:
https://www.loom.com/share/b286d423b6d8445d98647889ef2893ef

Please let me know if it doesn't work for you
