### ISSUE TITLE
Trial messages still appear on the dashboard, even after signing up to a paid subscription

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#3173]
### Describe the bug

If the trial period hasn't ended, trial messages are still shown to users of paid subscription

### Steps to reproduce

Create a new gitpod account and sign up for a paid subscription before the trial period ends.

### Expected behavior

After signing up for a paid subscription, trial messages should disappear.

[Bug reported by our community](https://community.gitpod.io/t/paid-team-subscription-shows-as-trial/2728) :)

**Comment by staxly** [comment]
Just to verify, is it necessary that the team "owner" occupy a "slot" in the team?

**Comment by staxly** [comment]
Bump
