### ISSUE TITLE
Theia lags and or becomes unresponsive.

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#3178]
### Describe the bug
Every attempt to load my project with the Theia editor results in a either a hung page or a 5 minute wait. The vscode editor does not do this.

### Steps to reproduce
Start a project with the theia editor, notice spinners in the file tree where folders are open and the extra long wait time.

### Expected behavior
Thiea should not hang or take 5 minutes to load when vscode works as expected,

### Additional information

- If you the Beta feature: vscode as the editor, then there is no lag or hung page.

- See the spinners in the file tree in the image below. They spin for up to 5 minutes before I can interact with the page. 

![image](https://user-images.githubusercontent.com/3060702/107671021-36564280-6c48-11eb-8389-c5585078b801.png)

### Example repository
https://github.com/apolopena/q-and-a-challenge/tree/development

**Comment by ArthurSens** [comment]
I've tried to reproduce this behavior with your repository, but was able to open the project in a Theia workspace almost instantly :thinking: 

Looking at our monitoring, it doesn't look like we had degraded performance today, but maybe you had the bad luck to open during some random spikes? 

Is this behavior still happening?

**Comment by apolopena** [comment]
It is still happening. Maybe it has to do with my specific workspace? `emerald-herring-uyhdsamt.ws-us03.gitpod.io`
![image](https://user-images.githubusercontent.com/3060702/107691765-b8526580-6c60-11eb-8ab2-49f7ee2d3d9a.png)

**Comment by akosyakov** [comment]
@apolopena Does it happen if you don't use browser preview but open a new window for preview? Could you share your project?

**Comment by apolopena** [comment]
@akosyakov Yes indeed the project is being served. I can access it from an external browser window while Theia is frozen. I always had a [bug](https://github.com/apolopena/gitpod-laravel8-starter/issues/19) in the [starter project](https://github.com/apolopena/gitpod-laravel8-starter/)  my [project](https://github.com/apolopena/q-and-a-challenge) is built from where restarting the workspace would give me this error:
```
2021/02/03 16:16:18 error while issuing request: Post "http://localhost:23000/gitpod/cli": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/02/03 16:16:53 error while issuing request: Post "http://localhost:23000/gitpod/cli": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
I am pretty sure the cause of the bug is from trying to start the preview browser when it is already running. I had the preview browser running from a `command` task just in case an unsavvy user closed the preview browser, stoped the workspace and then wondered why the preview was gone when they started the workspace back up.
The bug was pretty benign so I left it alone. However perhaps something internally changed because now it appears that this [bug](https://github.com/apolopena/gitpod-laravel8-starter/issues/19) is a blocker. Although if you wait long enough the IDE unfreezes and this familiar message appears in the terminal for the `command` task.
```
2021/02/12 16:39:29 error while issuing request: Post "http://localhost:23000/gitpod/cli": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/02/12 16:40:04 error while issuing request: Post "http://localhost:23000/gitpod/cli": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
I guess I need to sniff for the preview browser process running and then conditionally run the preview/refresh routine. I can look into it more later but right now I just swapped over to VSCode IDE in the beta preview so I can continue to work.

Pretty much all of these issues stem from me trying to circumvent the issue where quite often when the preview browser opens naturally via `onOpen: open-preview`, it is a 404 page with a try again button, after a few attempts the page would display, somtimes the page would display right away but it was inconsistent. This was not a good user experience so I work in this preview/refresh routine which I admit is a kludge.

**Comment by apolopena** [comment]
UPDATE:
The page just froze again in the middle of pushing to the repo. It didnt seem to have anything to do with the preview window.

**Comment by apolopena** [comment]
It stopped happening however there is still seems to be wierdness around calling `gp` in a `command` task. See [here](https://github.com/gitpod-io/gitpod/issues/3195).

**Comment by ccssmnn** [comment]
I am also experiencing this a lot:

![image](https://user-images.githubusercontent.com/29344072/111477122-14604c00-872f-11eb-8e8b-4e65db2aabbc.png)

First only on PRs with lots of changes but now also when launching a workspace with no changes at all.
