### ISSUE TITLE
Disable workspace sharing from config

### ISSUE THREAD

**Issue by Snickdx** [gitpod-io/gitpod#3179]
Greetings,

I teach University courses in Web Programming and I must say gitpod is truly a blessing in these virtual times. For my assessments, I provide a workspace for students to run and test their code. I would like to request the ability to disable workspace sharing from the gitpod.yml file but perhaps this use-case too fringe to be considered?

I know they may be able to get around it by forking the repo and changing the config but the majority of students are very new to git.

Thanks

**Comment by ArthurSens** [comment]
Hello @Snickdx!

Thanks for the idea! Personally, I think that pretty reasonable. Educational purposes are one of the best use-cases for Gitpod, I bet other professors might want this feature as well :slightly_smiling_face:

**Comment by gtsiolis** [comment]
See also https://github.com/gitpod-io/gitpod/issues/1978.
