### ISSUE TITLE
Alpine docker image

### ISSUE THREAD

**Issue by yijunyu** [gitpod-io/gitpod#318]
**Describe the bug**
Receiving the following error while gitpod stops at Step 9/14:
```
Error while adding Gitpod layer.
Please file an issue if you think this is a bug.
```
**To Reproduce**
Prepare Dockerfile based `gp init` as such:
```
FROM alpine:3.8
ENV HOME=/home/gitpod
WORKDIR $HOME
RUN { echo && echo "PS1='\[\e]0;\u \w\a\]\[\033[01;32m\]\u\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\] \\\$ '" ; } >> .bashrc
RUN addgroup gitpod && \
    adduser -G gitpod -s /bin/bash -D gitpod
RUN chmod g+rw /home && \
    mkdir -p /workspace && \
    chown -R gitpod:gitpod /home/gitpod && \
    chown -R gitpod:gitpod /workspace;
ENV SHELL /bin/bash
ENV USE_LOCAL_GIT true

# Give control to gitpod
USER root

# Gitpod configuration
ENV GITPOD_HOME /home/gitpod
ENV GITPOD_UID_GID 33333

# Keep the stemn user configuration
RUN chown -R $GITPOD_UID_GID:$GITPOD_UID_GID $GITPOD_HOME

# Remove root user config that gitpod copies over
RUN rm -rf /root
RUN mkdir -p /root
RUN touch /root/dontremove
```
**Expected behavior**
Since the /root folder has been restored, I was hoping that it won't hang at Step 9/14, as suggested by solution in #291. BTW, `FROM stemn/development` image was working, so I suspect this has to do with the fact of using alpine-based docker image.

**Comment by meysholdt** [comment]
I'll have a look - generally Gitpod does support Alpine based images.

**Comment by meysholdt** [comment]
Your `Dockerfile` works for me when I ensure user and group have UID/GID 33333:

```
RUN addgroup -g 33333 gitpod && \
    adduser -G gitpod -u 33333 -s /bin/bash -D gitpod
```

**Comment by yijunyu** [comment]
Yes, it works for me. I can get through the 14 steps and the workspace is displayed properly. The Terminal doesn't work, but that's because I was using alpine:3.8 basic docker image. I will try to add "bash" to see if works fully.
