### ISSUE TITLE
everytime I try to access Gitpod the workspace just hangs in the starting screen tried everything from reinstalling browser to hard restarts. the only thing I have not done is delete my gitpod account and start again obviously I do not want to do that please help!!

### ISSUE THREAD

**Issue by LeeWebb360** [gitpod-io/gitpod#3180]

**Comment by shaal** [comment]
Can you add some more information?
Screenshots of what you are seing?

What URL did you try accessing? is it https://www.gitpod.io/workspaces?

Here's a working gitpod project I'm working on, can click on the link and check if it works for you?
https://gitpod.io/#https://github.com/shaal/ddevenv

**Comment by akosyakov** [comment]
Could you open devtools next time and collect error logs from there as well as check the network tab for failed requests?
