### ISSUE TITLE
Please allow exposing TCP ports

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#3184]
### Describe the bug

Per https://www.gitpod.io/docs/config-ports/

> At the moment you can only expose HTTP servers

But so very many applications require us to expose plain non-http TCP ports. 

All real computers allow exposing a TCP port. gitpod is awfully close to becoming a real computer! (congrats!)

**Comment by gerardo-junior** [comment]
I can do this with https://github.com/jpillora/chisel doing it by encapsulating the traffic in http packets.

**Comment by akosyakov** [comment]
We just announced preview version of Gitpod local companion which allows to tunnel any tcp port: https://www.gitpod.io/blog/local-app please try and give us feedback 🙏🏻

**Comment by rfay** [comment]
This is an outstanding and exciting feature.  Where would you like feedback? (I'm able to get simple ports to work, but ssh access doesn't seem to work; 

```bash
$ ssh -F /tmp/gitpod_ssh_config amaranth-caterpillar-0wh52qdr
kex_exchange_identification: read: Connection reset by peer
```

Please note that this excellent new feature doesn't address the request in this issue. The idea here would be to actually allow exposing ports on the hostname (or perhaps on a special hostname).

**Comment by rfay** [comment]
Please note that this excellent new feature doesn't address the request in this issue. The idea here would be to actually allow exposing ports on the hostname (or perhaps on a special hostname).

**Comment by rl-gitpod** [comment]
> (Edit: This works on a newly created instance, just doesn't work on an existing one. Here's on a new one:

This is likely due to the existing instance running on an older version of the code that doesn't specify the correct port for the SSH server. It used 0 i.e. next available, which the local companion app cannot use.
If you run something like this in the workspace:
```shell
ps aux | grep drop
```
and see '-p :0' not '-p :23001' then that is the reason.

**Comment by akosyakov** [comment]
> Please note that this excellent new feature doesn't address the request in this issue. The idea here would be to actually allow exposing ports on the hostname (or perhaps on a special hostname).

If you elaborate on your use case it would help. I see localhost as a special stable hostname on each you can access any tcp port.
