### ISSUE TITLE
I added Gitpod extension to my chrome , when I open it I get the error Couldn't parse error

### ISSUE THREAD

**Issue by Tamilsevan** [gitpod-io/gitpod#3190]

**Comment by jankeromnes** [comment]
Hi @Tamilsevan, thanks for trying out the Gitpod extension!

Its main purpose is to automatially add the `gitpod.io/#` URL prefix in front of any GitHub/GitLab/Bitbucket pages.

If you're seeing the error "Couldn't parse your context", this means that the URL you tried to open is not compatible.

- Could you please share the full URL of the page showing this error?

- In general, sharing screenshots of such bugs is extremely helpful

**Comment by csweichel** [comment]
Closing due to lack of response. If this is still an issue, please re-open.
