### ISSUE TITLE
Misleading error when using gp: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#3195]
### Describe the bug
When using the `gp` command sometimes it prints this error message:

> error while issuing request: Post "http://localhost:23000/gitpod/cli": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

The command usually executes as expected despite this message.

However, this error output confuses users, see e.g.: https://github.com/gitpod-io/gitpod/issues/2041#issuecomment-779661350 We should fix this misleading error message.

### Steps to reproduce
See e.g. https://github.com/gitpod-io/gitpod/issues/2041

### Expected behavior
This error message should not occur when the command has been successfully executed.

**Comment by apolopena** [comment]
What does this meesage actually mean? I notice bugs (a synchronous block) in my project when this comes up. I suspect it comes from calling gp preview when a preview window is already up with the same url but I it is hard to prove and test.

**Comment by csweichel** [comment]
Will be fixed in #3309

**Comment by apolopena** [comment]
Hello,
I followed the trail of fixes related to this bug and I am still seeng this issue. Can we reopen this issue or should I file a new issue for it?
The cryptic error message seems to happen whenever `gp preview` is called in a command task in `gitpod.yml` upon a restart of the workspace that already had a terminal open that had previously opened the preview browser.

I can provide a simple repository that illustrates the problem if needed.

**Comment by akosyakov** [comment]
March milestone is not deployed yet. You can see the release date here: https://github.com/gitpod-io/gitpod/milestone/12
