### ISSUE TITLE
Improve workflow for starting a new workspace from an example project

### ISSUE THREAD

**Issue by davidshq** [gitpod-io/gitpod#3206]
### Problem to Solve

In the current state, example projects are hidden once you start a single workspace and requires you to search for those to show up. In fact, these example projects show up only when your search query does not match any description for the existing workspaces. **This interaction is certainly not intuituive or discoverable.** :x:

### Background

We plan to revamp the whole dashboard design over the next couple of months and one of the secondary features we are considering is introducing a better and more useful way to start a workspace from within the dashboard. 🗺️ 

This could be a) either importing an existing project or b) starting from an example project. Let's keep this issue open to track progress for this feature.

### Proposal

See https://github.com/gitpod-io/gitpod/issues/3206#issuecomment-804123107.

---

<details>
<summary>Original description</summary>

> When I first signed up for gitpod I saw all the sample projects available in my account and could easily choose to spin up any of them.

> Once I added a workspace to my account these sample projects disappeared. I can search for them and they still show up, but I have to remember what they are called or what they are about in order to do so. It would be nice if there was a toggle that allowed one to turn on/off sample projects so that individuals who are actively using workspaces can still easily see these projects.
</details>

**Comment by gtsiolis** [comment]
Hey @davidshq! Thanks for bringing this up! I've updated the description in this issue and kept the original description inline, to keep it as a single source of truth (SSOT) for tracking this feature. 🏀

**Comment by gtsiolis** [comment]
FYI, we've already merged a new modal that you can trigger on the  empty state of the workspaces list (see https://github.com/gitpod-io/gitpod/issues/3426) and we're planning to make it also accessible when the workspaces list in not empty (see https://github.com/gitpod-io/gitpod/issues/3534). /cc @davidshq

**Comment by gtsiolis** [comment]
Hey @davidshq! The new dashboard should cover this functionality at large. Closing this for now but feel free to send any remaining feedback to https://github.com/gitpod-io/gitpod/issues/3727 or create a new issue for improving this new functionality. 🏓
