### ISSUE TITLE
Can't open closed pull requests in Gitpod

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#321]
**Describe the bug**
Trying to open a closed pull request in Gitpod gives:

> We have trouble parsing your context
> Error: Cannot read property 'repository' of null

**To Reproduce**
1. Try to open a closed pull request in Gitpod, e.g. https://gitpod.io/#https://github.com/gitpod-io/gitpod-docs/pull/80

**Expected behavior**
It would be nice if we could open closed pull requests in Gitpod. Or, if that's not supported, maybe we should say that in a more explicit error message?

**Comment by AlexTugarev** [comment]
Same as #4?
