### ISSUE TITLE
Kill docker image builds

### ISSUE THREAD

**Issue by Terra316** [gitpod-io/gitpod#3210]
So, basically, I run a command in my docker image to `apt-get install` something, and Gitpod won't stop it because the command is asking for input. So now I have four running workspaces at the same time, each of which I don't need. Can you delete these for me, and can you change the image builds to pass input?

**Comment by shaal** [comment]
@Terra316 you can try going to https://gitpod.io/workspaces
You'll see a list of all your workspaces, and you can click on `Stop` button to stop a running workspace.

**Comment by Terra316** [comment]
The workspaces are still building the docker image, so they can't stop.

**Comment by csweichel** [comment]
At the moment there's no means to stop an ongoing image build I'm afraid. Image builds will time out eventually though.
When we revisit the image builder, we'll consider this a feature.
