### ISSUE TITLE
Can't open workspace

### ISSUE THREAD

**Issue by Wegner** [gitpod-io/gitpod#3213]
### Describe the bug

Upon opening workspace via chrome extension, keep getting wierd screen instead

### Steps to reproduce

1. Authorize on linked gitlab account
2. Click chrome extension browser action button
### Expected behavior

Workspaces page opens
### Additional information

On a screen the is the following text:
We are having trouble parsing your context
Error: {"request":{"query":"query {\n repository(name: \"gitpod\", owner: \"gitpod-io\") {\n issue(number: NaN) {\n title\n }\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n parent {\n \n name,\n owner {\n login\n }\n url,\n isPrivate,\n \n \n }\n \n }\n \n }\n \n }\n \n }\n \n }\n \n }\n \n }\n \n }\n \n }\n \n defaultBranchRef {\n name,\n target {\n oid\n }\n },\n }\n }"},"result":{"errors":[{"path":["query","repository","issue","number"],"extensions":{"code":"argumentLiteralsIncompatible","typeName":"Field","argumentName":"number"},"locations":[{"line":3,"column":29}],"message":"Argument 'number' on Field 'issue' has an invalid value (NaN). Expected type 'Int!'."}]}}
Please file an issue if you think this is a bug.
### Example repository

rusticana.armoracia/jira-tools - master

**Comment by svenefftinge** [comment]
Sorry to let you down. We are having an incident and are fixing it right now. We deployed a new component which should prescale and warm up clusters. Turns out it warms up a bit too much.
We will keep you posted.

**Comment by Wegner** [comment]
@svenefftinge, it got back to normal!

Thanks a lot. If there is an accident already, gonna close the issue.

**Comment by jankeromnes** [comment]
See also https://github.com/gitpod-io/gitpod/issues/3215
