### ISSUE TITLE
Cannot create or open workspaces due channel errors.

### ISSUE THREAD

**Issue by jlaasonen** [gitpod-io/gitpod#3215]
### Describe the bug

Creating or opening a workspace fails with the error message `Error: 2 UNKNOWN: Channel Destroyed` or `Error: Cannot createCall with a closed Channel`. At least GitHub and Bitbucket repositories are affected.

### Steps to reproduce

Create a new workspace or open an existing one.

### Expected behavior

The workspace is created or opened normally.

### Additional information

Workspace IDs:

jade-pelican-3446ykqx
d0481a6c-3412-4dc5-8c55-47719e30cf22
white-guineafowl-a2vvi27p
ivory-fox-g8qipz1g
f3d6fc69-572e-4c0f-afcc-4a397d69473e

### Example repository

https://bitbucket.org/jlaasonen/gp-test/src/master/
https://github.com/ElectronicBabylonianLiterature/ebl-api
https://github.com/ElectronicBabylonianLiterature/ebl-frontend

**Comment by jankeromnes** [comment]
Hi @jlaasonen! Thanks for reporting this problem.

This is related to an ongoing Gitpod incident currently being worked on: http://status.gitpod.io/incidents/90f9d190

We've put mitigations in place, so the service should be recovering / back to normal now.

**Comment by jlaasonen** [comment]
The workspaces are working now.

**Comment by jankeromnes** [comment]
Thanks! We can confirm the service is fully operational again, and we'll keep a close watch on monitoring for the next hour.

We've also identified & fixed the problem ("ghost" workspaces ramped up too hard) and will move on to root cause analysis.
