### ISSUE TITLE
Can't open https://github.com/nodejs/node-addon-examples

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#3216]
### Describe the bug
Open failed https://github.com/nodejs/node-addon-examples

### Expected behavior
Open successfully.

### Additional information

I did multi times, always fail.

![image](https://user-images.githubusercontent.com/3759816/108323814-12739d80-7202-11eb-9d21-4acc44360e34.png)

**Comment by csweichel** [comment]
I'm afraid we had an incident about an hour ago: http://status.gitpod.io/incidents/90f9d190

This should be resolved now. If the problem persists, please re-open this issue.

**Comment by gengjiawen** [comment]
> I'm afraid we had an incident about an hour ago: http://status.gitpod.io/incidents/90f9d190
> 
> This should be resolved now. If the problem persists, please re-open this issue.

The problem persists. (I don't have permission to reopen)

![image](https://user-images.githubusercontent.com/3759816/108329178-16a2b980-7208-11eb-955f-ac6dd630a58b.png)
