### ISSUE TITLE
Ports stuck at detecting

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#3218]
### Describe the bug
Ports are stuck at detecting

### Steps to reproduce
1. Create a empty github and use an image that includes python
2. At terminal run `python3 -m http.server`
3. Ports are stuck at detecting

### Expected behavior
1. Port 8080 is available 

### Example repository

![detecting](https://user-images.githubusercontent.com/14900791/108339439-65555100-7212-11eb-83fc-dce2fc4f1406.PNG)

**Comment by corneliusludmann** [comment]
Thanks for reporting. We're investigating this issue.

- Where are you located (EU, US, Asia, ...?)
- This could help as a workaround: https://github.com/gitpod-io/gitpod/issues/3118#issuecomment-774058247

**Comment by kunxin-chor** [comment]
Location: Asia (Singapore)

**Comment by vncoelho** [comment]
This is still happening some time.
`gitpood.yml` is ignored and the port is not detected.
