### ISSUE TITLE
not serving Port

### ISSUE THREAD

**Issue by Riyasyacub** [gitpod-io/gitpod#3221]
### Describe the bug

Am using Ruby on Rails . I have been using gitpod for more than 3 months. But now I can't open any port (eg: localhost:3000) through your IDE while typing "rails s" in terminal. am facing this problem for more than 4 hours.

**Comment by corneliusludmann** [comment]
Thanks for reporting. We're investigating this issue.

- Where are you located (EU, US, Asia, ...?)
- This could help as a workaround: https://github.com/gitpod-io/gitpod/issues/3118#issuecomment-774058247

**Comment by Riyasyacub** [comment]
Am from Asia
