### ISSUE TITLE
Cannot open workspace. Gitpod current status shows resolved a few hours ago, but still does not load.

### ISSUE THREAD

**Issue by Gregory4321** [gitpod-io/gitpod#3223]
### Describe the bug

Cannot open workspace at all. Just sits on the screen with the blue gitpod logo and nothing happens.

### Steps to reproduce

Restarted workspace a few times, turned off computer and waited then turned on and tried again.

### Expected behavior

The workspace to open.

### Example repository

<img width="1436" alt="Screenshot 2021-02-18 at 12 06 23" src="https://user-images.githubusercontent.com/64581897/108355320-9322a180-71e2-11eb-9a30-6f97bc8fdcd8.png">

**Comment by corneliusludmann** [comment]
Hi @Gregory4321,

According to our database, you have 1 workspace running. The ID of this workspace starts with `red-rattlesnake`. Is this workspace still not accessible for you?

**Comment by Gregory4321** [comment]
Hi @corneliusludmann yes this is the workspace. Tbh I don't know where the red-rattlesnake came from, hope that snot an bug 🤪

**Comment by corneliusludmann** [comment]
It's not a bug. It's part of the new workplace ID schema.

Are you able to access your workspace again?

**Comment by Gregory4321** [comment]
O ok. Still not loading, not even showing (1/3..2/3..3/3) just the blue floating icon

**Comment by corneliusludmann** [comment]
Could you try to stop that workspace and open a new one? I can't see anything suspicious about your workspace.

**Comment by Gregory4321** [comment]
Ok so it opened another workspace, just took a while to load. Can you see it ? called flask-task-manager-project I will stop it and try and open the original one i was trying to open again.

**Comment by Gregory4321** [comment]
It looked promising as i saw (1/3), but now thats gone and its just showing the blue icon again

**Comment by Gregory4321** [comment]
I just stopped the workspace, and then started it again, and it went 1 2 3/3, then that disappeared and stopped loading. Very strange
