### ISSUE TITLE
Alpine docker image miss something to call /usr/bin/gp

### ISSUE THREAD

**Issue by yijunyu** [gitpod-io/gitpod#323]
**Describe the bug**
When a custom docker image is used, there is an error to get /usr/bin/gp run.
The error message is
```
bash: /usr/bin/gp: No such file or directory
```
This issue of /usr/bin/gp makes it unable to use the GUI to commit code changes. 
It is still possible to use the Terminal to commit using the git command on the CLI.

**To Reproduce**
See the #318 issue, the docker image can run when "git and bash" packages are added, however,
even though `/usr/bin/gp` exists:
```
gitpod $ ls -l /usr/bin/gp
-rwxr-xr-x 1 root root 11092836 Feb 19 20:50 /usr/bin/gp
```
**Expected behavior**
gp shall be able to run.

**Comment by 32leaves** [comment]
Thanks for reporting this issue.

`gp` is written in Go and until now we've built it with cgo enabled. We have removed the cgo dependency.

Once this fix is deployed, things should work as expected.

**Comment by 32leaves** [comment]
We have deployed the fix. `gp` works now with Alpine based images.

**Comment by yijunyu** [comment]
Yes, it works for me.
