### ISSUE TITLE
Settings/preferences for Code IDE does not save

### ISSUE THREAD

**Issue by maksimr** [gitpod-io/gitpod#3230]
I have enabled "Feature preview" and selected "Code" as default IDE
![image](https://user-images.githubusercontent.com/616193/108432175-01a04780-7255-11eb-9c02-d59edaf3a6fc.png)

Open a workspace and setup default settings but after stop and rerun workspace (or open new) settings just has reset on default. For the "Theia" IDE all works fine

https://user-images.githubusercontent.com/616193/108432737-ec77e880-7255-11eb-8353-4b3f78426f82.mov

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/3110 in Feb milestone
