### ISSUE TITLE
Document CLI commands

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3239]
### Problem

We're currently missing some documentation for the CLI tool.

CLI commands and and reference documentation can be found scattered across a) release notes[[1](https://www.gitpod.io/docs/release-notes/2019-02-15/february-2019/#gitpod-cli)][[2](https://www.gitpod.io/docs/release-notes/2019-06-17/june-2019/#cli-gp-await-port)][...], community forum posts[[3](https://community.gitpod.io/t/gitpod-yml-and-making-sure-init-completes-before-command/2818/2)][[4](https://community.gitpod.io/t/runing-tasks-after-composer-install/130/3)][...], comments in the [issue tracker](https://github.com/gitpod-io/gitpod/issues/), etc.

### Proposal

Given there are plans for improving[[5](https://github.com/gitpod-io/gitpod/issues/598)] commands and adding[[6](https://github.com/gitpod-io/gitpod/issues/3166)] new ones, let's create a dedicated section in the documentation (`docs.gitpod.io`) that includes a command reference with usage guidelines and examples when possible so that we can have a single source of truth (SSOT) we can reference and point to when needed.

See also other examples[[7](https://docs.gitlab.com/ee/ci/yaml/README.html)][[8](https://vercel.com/docs/cli)][[9](https://cli.netlify.com/)].

**Comment by jankeromnes** [comment]
Here are all the `gp` commands, as per `gp help`:

```
Command line interface for Gitpod

Usage:
  gp [command]

Available Commands:
  await-port        Waits for a process to listen on a port
  env               Controls user-defined, persistent environment variables.
  forward-port      Makes a port available on 0.0.0.0 so that it can be exposed to the internet
  help              Help about any command
  init              Create a Gitpod configuration for this project.
  open              Opens a file in Gitpod
  preview           Opens a URL in Theia's preview view
  sync-await        Awaits an event triggered using gp sync-done
  sync-done         Notifies the corresponding gp sync-await calls that this event has happened
  url               Prints the URL of this workspace

Flags:
  -h, --help   help for gp

Use "gp [command] --help" for more information about a command.
```
