### ISSUE TITLE
Add the ability to configure the favicon in the gitpod.yml

### ISSUE THREAD

**Issue by orellabac** [gitpod-io/gitpod#3246]
When you have several workspaces sometimes you can easily loose track of where you are.

For example on the desktop I use something like the Peacock extension that changes the workspace color per project.

I was thinking that allowing to configure the favicon will provide that functionality, so even if have a lot of tabs open I can easily identify the one for my project.

Thanks!!

**Comment by TheBeeBoi** [comment]
lol
