### ISSUE TITLE
Update Go to 1.16

### ISSUE THREAD

**Issue by superloach** [gitpod-io/gitpod#3247]
I'm not sure what base image is being used for Go, but 1.16 came out recently, and I'd like to use it in Gitpod.
With Python, there's a way of switching versions - perhaps you could do the same with Go using the `golang.org/dl` packages?

**Comment by csweichel** [comment]
You could do the same today in a Gitpod workspace by:
- updating Go 1.16 in a custom Docker image
- or installing it in your workspace using `golang.org/dl`.

We've also just updated the `workspace-full` image (https://github.com/gitpod-io/workspace-images/pull/350).
