### ISSUE TITLE
Tabnine extension is not working (due to outdated Theia version)

### ISSUE THREAD

**Issue by bilucodota** [gitpod-io/gitpod#3249]
### Describe the bug
- Tabnine extension crashes immediately 

### Steps to reproduce
- Install Tabnine from marketplace
![image](https://user-images.githubusercontent.com/70566578/108637851-297dee00-7495-11eb-9264-937f081e8bd2.png)

### Expected behavior
- Tabnine should work 

### Additional information
I'm a software engineer at Tabnine. An [issue](https://github.com/codota/tabnine-vscode/issues/337) was opened at our vscode repository which describes this bug.

As far as I've tested, it seems like Tabnine is using vscode `ColorThemeKind` property which was [introduced](https://github.com/eclipse-theia/theia/commit/4314838089c8ea3cd0f615dafde6f6166d0a0e38) in `theia 1.8`. 

As Gitpod uses `theia 1.5`. It misses this property.
I've tested Tabnine on the the latest `theia` version locally and it works. So a simple upgrade should fix it.

**Comment by JonatasAmaral** [comment]
Upvoting the update here. From out here, it sounds like a good thing, independent of the particular case of the extension even.

**Comment by akosyakov** [comment]
Please try VS Code instead: https://www.gitpod.io/docs/feature-preview/#default-ide

**Comment by JonatasAmaral** [comment]
Tested it out.
The tabnine extention does work, but a feel like i prefer some Theia editor features 🤷‍♂️
So hope it gets updated soon.

Also, can't do ssh connections on GITPOD when using VSCode. apparently, it's because it is in an older chisel version [1.6.0]
It's not dowloading the newer version from script.
Workspace made by cloning [this same repo](https://github.com/corneliusludmann/gitpod-playground/tree/sshd-over-chisel) as did in Theia.

**Comment by akosyakov** [comment]
> but a feel like i prefer some Theia editor features 🤷‍♂️

Could you elaborate which features? In long term Code is going to become default.

**Comment by akosyakov** [comment]
> Also, can't do ssh connections on GITPOD when using VSCode. apparently, it's because it is in an older chisel version [1.6.0]
It's not dowloading the newer version from script.
Workspace made by cloning this same repo as did in Theia.

@csweichel Could it be related to root support? I could not find anything Code specific in scripts.

**Comment by csweichel** [comment]
That's possible. Irregardless I reckon we won't invest in Theia at this point anymore.

For the SSH issue, please open a separate issue.
Will close this one for now. Please reopen if you think we should handle this differently.
