### ISSUE TITLE
Personalized settings make code-based IDE fail to start

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#3250]
### Describe the bug

I tried to set a Dark theme for the code-based IDE using the following settings. 
![image](https://user-images.githubusercontent.com/824507/108644918-c7f25b00-7465-11eb-8242-ae8ae32826de.png)
The corresponding command in the Dockerfile is as below. 
```
COPY settings/settings.json .gitpod-code/User/settings.json
```
However, containers of the built Docker image always fails to start. 
Removing the COPY command makes the Docker image valid to start. 

### Steps to reproduce

1. The Docker image [dclong/gitpod](https://github.com/dclong/docker-gitpod) (dev branch is such as example). The corresponding built Docker image is dclong/gitpod:next.
2. Configure one of your GitHub repo to use dclong/gitpod:next. 
3. Start a new workspace and you shall see that it fails to start. 
4. However, if you configure your GitHub to use dclong/gitpod (the only difference is the dark theme configuration), it works. 

### Expected behavior

There should be a way to configure theme for the code-based IDE.

**Comment by akosyakov** [comment]
> There should be a way to configure theme for the code-based IDE.

It's resolved by https://github.com/gitpod-io/gitpod/pull/3110 and will be deployed as a part of Feb milestone.

> However, containers of the built Docker image always fails to start. Removing the COPY command makes the Docker image valid to star

That sounds like a bug although unrelated to the request. cc @csweichel does it?
