### ISSUE TITLE
Cannot launch workspaces

### ISSUE THREAD

**Issue by kk86bioinfo** [gitpod-io/gitpod#3251]
### Describe the bug

While launching workspace, below error message is displayed:
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: %!w(string=)

### Steps to reproduce

Launch a new workspace.

### Expected behavior

Workspace should have launched accordingly.

**Comment by csweichel** [comment]
Which repository did you start the workspace on?

**Comment by alexmt** [comment]
Got the same error today. Here is gitpod URL that might reproduce the error: https://gitpod.io/#https://github.com/alexmt/argo-cd/tree/gitpod
