### ISSUE TITLE
Opening gitpod

### ISSUE THREAD

**Issue by Edmond-ZAMBA** [gitpod-io/gitpod#3252]
Hello
No workspace found

**Comment by jankeromnes** [comment]
Hi @Edmond-ZAMBA!

Could you please provide more details on the problem you are experiencing?

For example, if you were expecting some workspaces to be listed in https://gitpod.io/workspaces/ but they're not there, please:
- Specify what workspaces you were looking for (i.e. for which repository? when were they created?)
- Provide a screenshot of https://gitpod.io/workspaces/
- Provide a screenshot of https://gitpod.io/access-control/

Thanks!
