### ISSUE TITLE
code: installing web extensions does not work

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3259]
For instance it is not possible to install VIM extension at all. It is a bug in Open VSX: https://github.com/eclipse/openvsx/issues/249

**Comment by akosyakov** [comment]
You can install VSCode VIM extension from Open VSX. And it runs alone in browser web worker.
<img width="1904" alt="Screenshot 2021-06-19 at 09 50 07" src="https://user-images.githubusercontent.com/3082655/122631261-fca8b300-d0e3-11eb-9d4a-a00f6871e060.png">

**Comment by maksimr** [comment]
Could not install the latest version of Vim extension on gitpod.io. Download locally and drop to extensions panel also doesn't work

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/616193/132404177-9d3c9919-2ad4-4cbe-a6a1-f920be2af607.png">

**Comment by akosyakov** [comment]
@maksimr We are looking into it. It seems to be some issue with Open VSX.
