### ISSUE TITLE
[endgame] February 2021

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3262]
As part of our development cycle we run an "endgame week" for every iteration.
This issue collects all feedback/ToDo's for the [February cycle's](https://github.com/gitpod-io/gitpod/milestone/9) endgame.

## Things to test / watch out for

- [x] Load test `ws-scheduler` on staging (once again)

## First Week Tasks

- [ ] Deploy Gitpod Self-Hosted 0.8.0

**Comment by AlexTugarev** [comment]
Closing as done.
