### ISSUE TITLE
5fed447868fa1e145d0b20f110fd482170a8c217

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#3266]
Last run 20 minutes ago: sleeping five minutes to allow debugging

**Comment by jankeromnes** [comment]
Hi @markfirmware!

Please share more information on the problem you are observing (e.g. screenshots), and any relevant repository URLs / workspace IDs (unfortunately, "5fed447868fa1e145d0b20f110fd482170a8c217" is not a valid workspace ID).

**Comment by markfirmware** [comment]
![abc](https://user-images.githubusercontent.com/22677068/109047188-97980000-76a3-11eb-9a75-862885cb6c73.png)

I do not need any response, just reporting.

**Comment by jankeromnes** [comment]
Many thanks! 👍

For what it's worth, the long string is the Git commit SHA of your project on which this workspace was based.

The actual workspace ID is on top: `tomato-kangaroo-mezyfoe7`.

I can't investigate this now, but please ping again if we don't respond / if the problem remains.

**Comment by markfirmware** [comment]
The workspace is now starting. Feel free to close or keep for tracking.
