### ISSUE TITLE
Passing variables from special url to env

### ISSUE THREAD

**Issue by eyak** [gitpod-io/gitpod#327]
It would be great to pass custom variables to the special 'open repo' url;
For example;
https://gitpod.io/#https://github.com/<repo-name>?myvar1=hello&myvar2=world
would clone the repo and set env varbiles MYVAR1=hello, MYVAR2=world

this would allow us to direct users to a custom clone with preset settings, like supplying a userid or triggering internal actions, in the ad-hoc setup.

**Comment by svenefftinge** [comment]
This is now supported. The syntax is
`https://gitpod.io/#VAR1=FOO,VAR2=BAR/https://github.com/org/repo`

See https://www.gitpod.io/docs/47_Environment_Variables/#passing-environment-variables
