### ISSUE TITLE
Allow to set a default custom IDE for other people

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3274]
We support custom IDEs (https://github.com/gitpod-io/gitpod/issues/2419). However, a custom IDE can currently only be activated in a users profile (if the user got invited to the closed beta).

If would be great if the person responsible for a group of users (maintainer, employer, teacher, etc.) could make the IDE available for said users.

Options: 
a) allow to specify a default IDE on team level.
b) allow to specify a default IDE for an OAuth provider, e.g. a self-hosted GitLab.
c) allow to specify a default IDE per repository, for example via `.gitpod.yaml`

My favourite is (c) because I assume the "responsible person" has access to the git repos and this options offers the most flexibility.

**Comment by csweichel** [comment]
@svenefftinge how does this fit in with the product road map? Should we keep this issue around or close it until we're at that point and have figured out how this feature should work exactly?
