### ISSUE TITLE
Clicking download on project produces 404

### ISSUE THREAD

**Issue by tech0tron** [gitpod-io/gitpod#3275]
### Describe the bug

Trying to download a workspace, when I click the button it shows a 404 page and doesn't download anything.

### Steps to reproduce

Click the download button on a project.

### Expected behavior

I wanted to download a project.

**Comment by corneliusludmann** [comment]
Thanks for reporting this bug. There is already an open issue for this: https://github.com/gitpod-io/gitpod/issues/3152
I'll close this issue as a duplicate.
