### ISSUE TITLE
Getting login interruption

### ISSUE THREAD

**Issue by vavadiyasanket** [gitpod-io/gitpod#3276]
### Example repository

Getting message:
You (@xxuseridxx) must accept the Terms of Service in order to perform this action. Please access GitLab from a web browser to accept these terms.

**Comment by geropl** [comment]
Hi @vavadiyasanket ,

honestly I don't get what's the problem here (every Gitpod user needs to accept it's TOS), and will close for now.

Please re-open with for information (e.g., a screenshot) and what you expect to see instead.
