### ISSUE TITLE
Respect github pull-request templates

### ISSUE THREAD

**Issue by eyak** [gitpod-io/gitpod#328]
Gitpod should check if a pull-request template was created in the cloned repo, and if so use it when creating a pull request through gitpod. Currently gitpod pull requests break our pull request style because they ignore the template.

Read more about github pull-request templates here: https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository

**Comment by AlexTugarev** [comment]
Just renamed it to generalize. In Theia the https://github.com/theia-ide/theia/blob/master/.github/PULL_REQUEST_TEMPLATE.md is encouraged, but when creating a PR from Gitpod I've to manually edit it afterwards.

**Comment by akosyakov** [comment]
I'm going to implement it with the following assumptions:
- Multi PR templates are not supported, just the first is picked. It is the same in GitHub, multi PR templates can be used only for automation: https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters.
- PR templates will be looked up in the current branch. Technically it is incorrect, according to docs the PR template can be looked up only from the default branch, i.e. master. But in practice it probably should be a rare case what it is different from branch to branch?
- The body of commit message is prepended to the top of the template.
