### ISSUE TITLE
Display the current Git branch in the Terminal prompt (PS1)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3284]
Today, the Git branch/context is not shown in Gitpod's Terminal prompt.

But maybe it could be nice to have it included (this seems to be a common pattern, and Git even comes standard with the dedicated helper `__git_ps1`).

## Current prompt

<img width="495" alt="Screenshot 2021-02-26 at 14 33 39" src="https://user-images.githubusercontent.com/599268/109306881-1aee5880-7840-11eb-9f54-4bfc50d28a2d.png">

## Proposed new prompt

<img width="565" alt="Screenshot 2021-02-26 at 14 36 05" src="https://user-images.githubusercontent.com/599268/109306895-204ba300-7840-11eb-8feb-5bfbbf39f63d.png">

This can be achieved like so:

```bash
PS1='\[\033[01;32m\]\u\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)") $ '
```

## Criticism

I believe we've previously decided against having this, because the current branch name is already displayed in the bottom left of the IDE:

<img width="467" alt="Screenshot 2021-02-26 at 14 36 20" src="https://user-images.githubusercontent.com/599268/109307397-df07c300-7840-11eb-8aea-8cbbc67ab19c.png">

However, I personally find it hard to spot, and sometimes still accidentally push to the wrong place because I don't know I'm on the wrong branch.

**Comment by jankeromnes** [comment]
Not stale! Still extremely relevant, _especially_ when working with submodules(!)

**Comment by Shulammite-Aso** [comment]
@jankeromnes can I take this up?  I searched for good-first-issues and saw a few, but this one has stayed the longest, hence I'd like to start from it.

**Comment by jankeromnes** [comment]
Hi @Shulammite-Aso! Sure, many thanks for offering! I'll assign this issue to you for now (to let others know that you're intending to work on this).

Please let me know if you have any questions. 😊 FYI, you'll probably want to implement the fix in this file: https://github.com/gitpod-io/workspace-images/blob/master/base/Dockerfile
