### ISSUE TITLE
Build errors with custom apache2/php8 setup

### ISSUE THREAD

**Issue by stefen** [gitpod-io/gitpod#3287]
### Describe the bug
Changes in behaviour from the previous workspace-mysql, which previously built without incident:

- apache2 install now stalls with complaint about pre-existing apache2.conf. I modified the Dockerfile as in the attached screenshot to silence this step. Attempted build with both old/new, same results.
- Install inevitably fails with complaints around mpm_prefork.

<img width="1242" alt="Screen Shot 2021-02-26 at 11 37 35 AM" src="https://user-images.githubusercontent.com/505675/109341788-20d83f80-7828-11eb-92ee-478b4a32436f.png">
<img width="938" alt="Screen Shot 2021-02-26 at 11 38 19 AM" src="https://user-images.githubusercontent.com/505675/109341790-2170d600-7828-11eb-97ae-d76165dad6fd.png">
<img width="1451" alt="Screen Shot 2021-02-26 at 11 30 16 AM" src="https://user-images.githubusercontent.com/505675/109341782-1e75e580-7828-11eb-9ec4-b3d06778c10f.png">

**Comment by aledbf** [comment]
@stefen can you share the repository?
