### ISSUE TITLE
MIgrate to Go 1.16

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3290]
Update the Go version in the dev image, and
- move away from the now deprecated `io/ioutil`
- replace afero with `io/fs`

**Comment by jankeromnes** [comment]
FYI, workspace-full already has Go 1.16 (https://github.com/gitpod-io/workspace-images/commit/217772f7183e4a3af05d1fb1161844f55a80ae07), so I think the dev image can just be bumped/rebuilt.
