### ISSUE TITLE
I'm trouble shooting, trying to find an issue with my django, but in the terminal its coming up blue

### ISSUE THREAD

**Issue by Blakeman260** [gitpod-io/gitpod#3293]
![2021-02-28](https://user-images.githubusercontent.com/59576069/109406933-d6b0a480-7974-11eb-9fab-5db4a4879cc5.png)

as you can see in the picture, this is the issue I'm having in the terminal view. I can adjust the terminal up and down, but it moves with it.

**Comment by svenefftinge** [comment]
No idea. I have never seen that. Can you share a workspace snapshot or the repo?

**Comment by akosyakov** [comment]
Could you try to disable or enable hardware acceleration in Chrome settings? Does it help?
