### ISSUE TITLE
clean up the yarn setup

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3298]
Right now dev dependencies are scattered across all components making upgrade troublesome. Instead we should introduce a new package which list all dev dependencies and reexport binaries, other components should depend only on this package for dev dependencies. After that we can bump to latest typescript to get all nice features.

**Comment by svenefftinge** [comment]
related https://github.com/gitpod-io/gitpod/issues/3296

**Comment by akosyakov** [comment]
It makes sense to do #3296 first.

**Comment by csweichel** [comment]
Please make sure this kind of setup works in conjunction with leeway, e.g. dependencies are correct
