### ISSUE TITLE
[Dashboard] Workspace Start Page

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3301]
As part of the dashboard redesign we are reimplmenting the workspace start screen.

The screen shall communicate the current state of a workspace to users. 
As a first step we need to list all possible states and create designs for them.

This is part of https://github.com/gitpod-io/gitpod/issues/3300. 🍕 

### Designs

| Step 1 | Step 2 | Step 3 |
|-|-|-|
| ![image](https://user-images.githubusercontent.com/120486/110942166-19458a00-8342-11eb-8285-559b807b098f.png) | ![image](https://user-images.githubusercontent.com/120486/110942170-19de2080-8342-11eb-8144-5601e131df7c.png) | ![image](https://user-images.githubusercontent.com/120486/110942174-1b0f4d80-8342-11eb-9ca8-e09da9b455cb.png) |

| System Error |  System Error (Spacing)
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/110942203-28c4d300-8342-11eb-837e-df88d251108f.png) | ![image](https://user-images.githubusercontent.com/120486/110942216-2cf0f080-8342-11eb-9bd0-dc057704256d.png) |

| Existing Workspaces | Existing Workspaces (Spacing) |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/110942381-6c1f4180-8342-11eb-9c15-12436fbe2f35.png) | ![image](https://user-images.githubusercontent.com/120486/110942331-56aa1780-8342-11eb-97f1-e2c57041a2ac.png) |

| Parallel Workspaces | Page Not Found |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/110942435-7c372100-8342-11eb-8477-2ee2242d6901.png) | ![image](https://user-images.githubusercontent.com/120486/110942458-80633e80-8342-11eb-9f76-3ed31b83444e.png) |

See also [design specs](https://www.figma.com/file/FZVZIKi4oAOvYf9NVZnHWB/Workspace-Start-Page-3301).

**Comment by svenefftinge** [comment]
states and information to surface:
https://www.notion.so/gitpod/Redesign-Loading-Screen-5e2f3a45cb5446088566af1b30cde55f

**Comment by gtsiolis** [comment]
I've added a first draft of the design specs in the issue description. /cc @jankeromnes @csweichel @svenefftinge

**Comment by svenefftinge** [comment]
I'll close this as I think most of it is implemented and we should rather work with more concrete new issues.
