### ISSUE TITLE
[Dashboard] Welcome Page

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3302]
New users not coming from the website but from some Gitpod button on the internet, need to have some initial context about what Gitpod is. Imagine you are on some Open-Source project and they claim, start coding now with a button, you click it but have never heard of Gitpod.

### Designs

| Welcome | Welcome (Spacing) |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/112848364-ae6db000-90b0-11eb-8605-be9d5ee2e26d.png) | ![image](https://user-images.githubusercontent.com/120486/112844900-e83cb780-90ac-11eb-86ce-602f3f4d2e06.png) |

See also [design specs](https://www.figma.com/file/nVU4VuaAz8t5YBM3xGhCLS/Welcome-Page-3304?node-id=1%3A2).

**Comment by geropl** [comment]
My first question after I tried the new VS Code and it did not work for me for whatever reason: How do I switch back?

IMO we need a _minimal_ switch in the Settings that allow switching the default IDE.

@gtsiolis Ping: This came up during the Engineering Sync Meeting.

**Comment by gtsiolis** [comment]
Hey @geropl! In the new dashboard, there's already an option in _Preferences_ (`/preferences`) to switch the Default IDE. Does this look sufficient?

![image](https://user-images.githubusercontent.com/120486/111993453-528ab080-8b1f-11eb-8f54-4cca3819d19d.png)

**Comment by geropl** [comment]
@gtsiolis Absolutely, thx! :pray:  Was not aware.

**Comment by svenefftinge** [comment]
FWIW I understood your comment during the meeting more like, that we should make sure people who opt-in on the welcome screen to go with VS Code should get a hint, that they can always go back using the preferences. So people don't feel stressed because this might be a non reversable decision.

**Comment by geropl** [comment]
@svenefftinge It was more about the ability to switch at all. But the aspect you mention is equally important, true.

@gtsiolis Maybe this is already planned/solved as well? I imagine a (small) sentence below the opt-in: `You always can switch your default IDE in your [settings]()`.
