### ISSUE TITLE
[prebuilds] Remove prebuild labels

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3303]
When we first introduced prebuilds we added functionality so that the bot could add comments instead of setting the commit status. This feature doesn't make much sense and is broken (see https://github.com/gitpod-io/gitpod/issues/3235). We should remove it.

**Comment by jankeromnes** [comment]
The `addComment` feature is now fixed, and several users have expressed interest in continuing to use it.

Also, a PR comment is a nice, obvious way to encourage contributors and reviewers to use Gitpod, while a PR "Check" is very discreet and much easier to ignore or overlook (especially when all "Checks" are green and thus collapsed / hidden from view). Additionally, other popular tools/services also have a comment feature available (e.g. Netlify, Vercel, etc).

I would vote for:
- `addCheck`: keep ✅ 
- `addComment`: keep ✅ 
- `addBadge`: keep ✅ 
- `addLabel`: deprecate and remove ❌ (it's still broken and nobody has complained about it, as opposed to comments, so `addLabel` is probably the least useful feature here)
