### ISSUE TITLE
code: github/gitlab integration

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3306]
Specifically viewing PR change sets. See how we can use/integrate GitLens and GitHub PR VS Code extensions.

**Comment by svenefftinge** [comment]
depends on https://github.com/gitpod-io/gitpod/issues/3305

**Comment by akosyakov** [comment]
GitHub support landed: https://github.com/gitpod-io/gitpod/pull/3349

GitLab extension does not provide an easy way to hook up our generic auth provider, so we decided to leave it out for now. When this extension supports the auth vscode extension API we can reconsider. The issue in the upstream: https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/issues/337
