### ISSUE TITLE
code: deprecate user uploaded extensions

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3308]
1. Add linting to `.gitpod.yml` 
    1. that informs users that this feature is going away
    2. marks extensions which are not resolveable against OpenVSX
2. Ignore hashes and try to resolve the ID against OpenVSX
3. Prevent the upload of new plugins

**Comment by AlexTugarev** [comment]
So, there won't be any way to load extensions from within a workspace either? What about the use case of extension development? Would it be possible to load extension from a local path maybe?

**Comment by akosyakov** [comment]
You can always upload vsix files in your running workspace and deploy from the local path. It is only about prohibiting uploading user extensions to GCP storage.

**Comment by gengjiawen** [comment]
Can use still have `user-level` extension ? like vim, I don't want install it on every project.

**Comment by akosyakov** [comment]
Sure, if you install them from Open VSX.

**Comment by gengjiawen** [comment]
Is something move forward, I lost all my extension today (I still use theia-based since vim not ready in code).

![image](https://user-images.githubusercontent.com/3759816/120063489-efc31180-c099-11eb-9134-3b30960f416a.png)

**Comment by gengjiawen** [comment]
> Is something move forward, I lost all my extension today (I still use theia-based since vim not ready in code).
> 

@akosyakov Is this intentional ?

**Comment by akosyakov** [comment]
@gengjiawen no, we have not changed anything, at least what I'm aware

**Comment by gengjiawen** [comment]
I have not switch to code because of vim not usable on it yet. But I lost my theia extensions and I can't upload or install extension now. Can you take a look my issue ? it has been stuck me for a while. 

![image](https://user-images.githubusercontent.com/3759816/121281611-c1033180-c90a-11eb-9788-c478a913d603.png)

**Comment by akosyakov** [comment]
We discussed it and decided that we are not going to put effort into fixing Theia, sorry. It is going to be deprecated this month: Please try VS Code instead. #4459 Open VSX team is looking into fix for vim extension that it can be loaded in VS Code.

**Comment by akosyakov** [comment]
@gengjiawen You can install VSCode VIM extension from Open VSX. And it runs alone in browser web worker.
<img width="1904" alt="Screenshot 2021-06-19 at 09 50 07" src="https://user-images.githubusercontent.com/3082655/122631261-fca8b300-d0e3-11eb-9d4a-a00f6871e060.png">

**Comment by gengjiawen** [comment]
@akosyakov Thanks. It works like a charm. Anyway we can use user uploaded extension in code IDE ?

**Comment by akosyakov** [comment]
@gengjiawen Currently it is not planned. Which extension you don't want to publish to Open VSX?

**Comment by gengjiawen** [comment]
> @gengjiawen Currently it is not planned. Which extension you don't want to publish to Open VSX?

* https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-npm-dependency#review-details
* https://marketplace.visualstudio.com/items?itemName=herrmannplatz.npm-dependency-links

And a fork of wakatime not uploaded in Open Vsx.

**Comment by akosyakov** [comment]
Please reach out to author and for time being you can also create a PR here: https://github.com/open-vsx/publish-extensions#when-to-add-an-extension

We are not going to maintain user extensions for extensions which can be published from MS Marketplace to Open VSX.

**Comment by akosyakov** [comment]
The last step will be https://github.com/gitpod-io/gitpod/issues/4630
