### ISSUE TITLE
gp cli: open and preview support for other IDEs

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3309]
- keep `EDITOR='gp open'`, `BROWSER='gp preview'`
- make `gp open` try
    1. theia
    2. `GP_OPEN_EDITOR` env var
    3. vi
    4. *fail*

**Comment by akosyakov** [comment]
It is better to do after https://github.com/gitpod-io/gitpod/issues/2806

**Comment by meysholdt** [comment]
I just ran `gp open <file>` in VS-C and ended up in `vi`. 
Would have hoped for the VS-C editor, just as `code <file>` opens it.

**Comment by jankeromnes** [comment]
(Note for clarity: `gp open <file>` was fixed for other IDEs, but `gp preview <url>` still isn't -- that part was broken off into a dedicated issue https://github.com/gitpod-io/gitpod/issues/3382).
