### ISSUE TITLE
Community live chat (Discord/Slack?)

### ISSUE THREAD

**Issue by JeremyJaydan** [gitpod-io/gitpod#332]
It'd be awesome to join a community live chat either on Discord (my favourite), Slack, or another live chat platform. I feel the live chat aspect of the platforms encourage the communities to reach out and ask questions and help each other.

**Comment by svenefftinge** [comment]
Have you noticed https://spectrum.chat/gitpod ?

**Comment by JeremyJaydan** [comment]
Yeah I'm a little active on spectrum, I feel that it's more of a forum rather than live chat though.

**Comment by svenefftinge** [comment]
It is indeed. And also we are not very happy with its performance and UX.

**Comment by JeremyJaydan** [comment]
In my opinion, Discord is the best platform for communities to connect. Discord's target audience is gamers, however it is still very popular amongst the creative industry.

**Comment by JeremyJaydan** [comment]
I have come across a few other platforms in the last year, I'll see if I can dig them up.

**Comment by JeremyJaydan** [comment]
https://hey.space was another one I was thinking of but it's more of a team live chat platform (pay per user). I did come across Gitter on my search, https://gitter.im/ may make the most sense.

**Comment by svenefftinge** [comment]
We went away from gitter, because it doesn't have threads. So as soon as there are two topics being discussed at the same time it is super confusing. Maybe we should consider Discord.

**Comment by JeremyJaydan** [comment]
Ah fair enough. I think Discord would be the best choice. It's proven useful for a many communities one of which is the coder ide.

**Comment by Nerd0000** [comment]
and when discord gitpod will come out?

**Comment by dragonDScript** [comment]
I am creating an unofficial Gitpod discord server. If any mantainer thinks that this server can be the official server, I'll give him the ownership (under some terms).
When it's ready I'll share it!

**Comment by Merith-TK** [comment]
> I made an unofficial Gitpod discord server. If any mantainer thinks that this server can be the official server, I'll give him the ownership (under some terms).
> Invite link: https://disboard.org/server/797160046986395658

HEY need a new invite link

**Comment by pawlean** [comment]
Hey @Merith-TK! We have an official Discord server now: https://gitpod.io/chat Come and join us!

**Comment by dragonDScript** [comment]
> > I made an unofficial Gitpod discord server. If any mantainer thinks that this server can be the official server, I'll give him the ownership (under some terms).
> > Invite link: https://disboard.org/server/797160046986395658
> 
> HEY need a new invite link

Deleted since the new server is more active
