### ISSUE TITLE
[code] On connection loss the screen is blocked by a big modal

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3327]
### Describe the bug
Whenever the Code frontend looses connection to the backend it displayes a big, blocking modal which requires user interaction instead of reconnecting direcly (in the background).

This happens on slow internet connections as well as whenever Gitpod is redeployed.

### Steps to reproduce
 - Redeploy Gitpod

### Expected behavior
Ideally, copy the behavior of Theia:
 - status bar changed color (noticeable but does not pull intention immediately)
 - dont block the screen
 - reconnect immediately and don't wait for user interaction

**Comment by JanKoehnlein** [comment]
I have serious network outages here and no modal popping up. Just did things in the UI that were ignored.

**Comment by akosyakov** [comment]
It occurred to me that our backend ws never responds to pings from browser, so maybe browser just shutdowns the connection periodically then it is silent on web socket. I will look into it next month.

**Comment by geropl** [comment]
IMO this has been solved now, thx @akosyakov ! If not please re-open.
