### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#3328]
A changelog helps showcase new features, announce bug fixes and provide additional details on what is happening with Gitpod to anyone who is interested.

Each release update may potentially be quite extensive (i.e. feature announcements, animated gifs, bug fixes, contributors, etc.) Rather than a single `CHANGELOG.md` in the root, I suggest we create individual changelog files in `docs/changelog/<year>-<month>/README.md` to match the current monthly release cycle.

Note: `README.md` becuase GitHub renders a preview automatically when browsing the code. The use of a separate directory per release is to keep changelog assets in their own directory.

The following Markdown template can be used for individual changelog files:

```md
# [yyyy-mm-dd]
_[Summarize the highlights of this release]_

## [Update #n title]
_[Upload a gif of the update (animated if it makes sense)]_

_[Describe the update. Provide links to docs if possible]_

**Contributors**
* _[@-mention each contributor in a comma-separated list. Example below.]_
* [@user1](https://github.com/user1), [@user2](https://github.com/user2)


## [Update #n+1 title]
_[See template above]_


## [Update #n+2 title]
_[See template above]_


## Miscellaneous
* [#xyz](https://github.com/gitpod-com/gitpod/pull/xyz) - _[PR title]_. Thanks to [@username](https://github.com/username)
```

**Comment by gtsiolis** [comment]
Regarding the animated gif, a static close up screenshot of the feature could suffice most of the times, right? 💭

**Comment by mikenikles** [comment]
1. I agree, it doesn't have to be animated
2. Initially I thought about a structured approach, but noticed the docs and blog posts already use Markdown which gives us the flexibility to be more creative if we decide to change the structure of how we document a new release. The goal is to reuse that template for GitHub releases, release blog posts and at some point I imagine to also provide the changelog in the product itself to let people know what's new.

It's worth noting with Markdown we could use frontmatter to add structured data at the top of the changelog:

```md
---
released-at: 2020-02
contributors: @user1, @user2
---

<the rest of the template>
```
