### ISSUE TITLE
[ws-manager] Failed-to-delete pods don't time out

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3330]
### Describe the bug
If during ws-manager's `stopWorkspace` the pod deletion doesn't work for some reason, we'll still have modified the state such that it breaks the timeout mechanism. This can legitimately happen as those state modifications and pod deletions are not atomic/within a transaction.

### Steps to reproduce
1. Modify `stopWorkspace` so that the pod doesn't actually get deleted (e.g. comment out [this bit](https://github.com/gitpod-io/gitpod/blob/e159c8035a9d6b4bb993e11c8b1673d1ec7f3e0c/components/ws-manager/pkg/manager/manager.go#L467-L478) and log something instead)
2. Start a workspace with this modified ws-manager
3. Modify it's custom timeout annotation to something like `30s` so you don't have to wait that long
4. Stop that workspace - the workspace will not stop/go into stopping because the pod is not deleted.
5. After 30 seconds the pod should receive a `gitpod/timedout` annotation but likely won't

Note: when we've tried to stop a workspace that was in this state with a ws-manager whose `stopWorkspace` function worked well, that workspace stopped just fine.

### Expected behavior
We should never enter this limbo state where workspaces no longer time out.

### Additional information
first observed on staging

**Comment by aledbf** [comment]
@csweichel is this valid after the refactor of PLIS?
