### ISSUE TITLE
[dashboard] strange UX when trying to delete last auth provider

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#3333]
### Describe the bug

On the access control page, every user action is handled in popups. 
But when I try to delete the last auth provider, I am forwarded to a new error page. This feels wrong.

### Steps to reproduce

Delete the last auth provider on the access control page 
-> you are transfered to a new page

### Expected behavior

A popup with an error message

### Example repository

any

**Comment by AlexTugarev** [comment]
<img width="1038" alt="Screen Shot 2021-03-03 at 14 39 54" src="https://user-images.githubusercontent.com/914497/109814099-5e750800-7c2e-11eb-89c0-a970dd5978f8.png">


> (...) I am forwarded to a new error page. This feels wrong.

@JanKoehnlein, do you mean the link to the settings page here? Or do you really see an error page?

There is a reason, why it's not possible to just disconnect the last provider: your account would become unreachable. While this is a technical issue, it would be great to have a more consistent way how to deal with this situation.

/cc. @gtsiolis

**Comment by JanKoehnlein** [comment]
That was on staging.

**Comment by AlexTugarev** [comment]
@JanKoehnlein, I don't see any difference between staging and production. Can you reproduce the error page?

**Comment by AlexTugarev** [comment]
Thanks fo @JanKoehnlein! We found an issue. The expected message from ☝🏻  isn't rendered if there is an internal `Gitpod` identity attached to the user's profile. This is a definitely a bug in the frontend bits. Funny though, I couldn't reproduce it, i.e. I couldn't create such an internal identity for my account on staging.
