### ISSUE TITLE
code: uninstalling extensions does not work always

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3342]
Steps to reproduce:
- uninstall GitLens
- click reload the page on an extension to apply changes

If you do it fast extension is installed again on the reload. The issue is that we do the initial sync on each page reload, since on workspace restart user extensions are not persisted and will be completely uninstalled otherwise. In this case though if you do reload fast the sync does not happen and the initials sync on a reload installs the extension again.

**Comment by akosyakov** [comment]
@jeanp413 Please check with workspace team whether all workspace already have this change in. If so then we can deploy the fix to VS Code Insiders.

**Comment by akosyakov** [comment]
@jeanp413 should we close it?

**Comment by jeanp413** [comment]
yes, fixed in https://github.com/gitpod-io/openvscode-server/pull/272
