### ISSUE TITLE
Status sometimes reverts to "BuildingWorkspaceImage"

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#335]
**Describe the bug**
<img width="1552" alt="screenshot 2019-02-25 at 08 14 26" src="https://user-images.githubusercontent.com/599268/53320439-f6b8b380-38d5-11e9-9c50-dbebf0f88f80.png">

**To Reproduce**
1. Start a Gitpod workspace, e.g. https://gitpod.io/#https://github.com/jankeromnes/servo
2. Wait for it to build an image, perform a clone, start the IDE, etc.
3. Start using your workspace

Sometimes, the status suddenly reverts to "BuildingWorkspaceImage", showing you a huge overlay that prevents you from using the IDE.

Deleting the overlay from the Inspector allows continued usage of the IDE.

I think this only happens when you have a long-running `init` step in your `.gitpod.yml` (e.g. a long build).

**Expected behavior**
- The status should not randomly revert back to "BuildingWorkspaceImage"
- There should be a way to dismiss overlays that prevent you from using the IDE (e.g. with this, or "IDE offline", I'd like to say "ok but I know what I'm doing, please let me do work that I know won't be saved")

**Comment by geropl** [comment]
This has been fixed and deployed.

**Comment by techwithtim** [comment]
GitPod worksapces that have build errors in the inital stages cannot be deleted or stopped from running @jankeromnes @geropl
