### ISSUE TITLE
Docker in Ubuntu is outdated and not working with modern docker-compose.yml

### ISSUE THREAD

**Issue by alanwilter** [gitpod-io/gitpod#3352]
### Describe the bug

`docker-compose up` fails with ERROR, because it's outdated.

### Steps to reproduce

Tested with any `docker-compose.yml` file whose header reads: `version: '3.8'` and it will fail with:

``` BASH
$ docker-compose up db
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

### Solution

``` BASH
sudo curl -L "https://github.com/docker/compose/releases/download/1.28.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

or

``` bash
pip install -U docker-compose
```

I've done this on my local Ubuntu and now I can run `docker-composer` without problems.

**Comment by aledbf** [comment]
@alanwilter do you have a public repository to reproduce the issue?

**Comment by alanwilter** [comment]
Please, try https://github.com/alanwilter/flask-pytest-example

Open a terminal and start `sudo docker-up`, in another terminal (or split), just `docker-compose up`.

BTW, `cmd+shift+P` -> "Docker: Compose UP" does not do anything for me in GitPod.
