### ISSUE TITLE
Unable to start workspaces in Code (no errors shown)

### ISSUE THREAD

**Issue by davidwindell** [gitpod-io/gitpod#3355]
### Describe the bug
When I try and start our custom image in Code (feature preview), it gets stuck on Pulling Docker Images ... (2/3).

### Steps to reproduce
 * Enable Feature Preview
 * Set default editor to Code
 * Visit https://gitpod.io/#https://github.com/davidwindell/gitpod-test/tree/main

### Expected behavior
Workspace should start correctly and if not should at least show the reason why there was a failure.

### Additional information
Console shows 502 error for `/_supervisor/v1/status/supervisor`

### Example repository
https://github.com/davidwindell/gitpod-test/tree/main

**Comment by davidwindell** [comment]
Interestingly it's not just our custom image, I'm seeing exactly the same on a random public image that was working fine in Theia https://github.com/tetsuroba/Gitpod-PHP-Debug/commit/89ecd57729f81d0671aab85c41f7510bd3169d46

**Comment by csweichel** [comment]
The IDE doesn't start properly. This is most certainly due to both workspace images being based on `alpine`.

```
{"args":["/workspace/gitpod-test","--port","23000","--hostname","0.0.0.0"],"entrypoint":"/ide/startup.sh","level":"info","message":"launching IDE","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","time":"2021-03-05T09:31:19Z"}
{"envvar":"SUPERVISOR_ADDR","level":"debug","message":"passing environment variable to IDE","serviceContext":{"service":"supervisor","version":""},"severity":"DEBUG","time":"2021-03-05T09:31:19Z"}
{"envvar":["PATH","HOSTNAME","PHP_VERSION","ENABLE_REDIS","ENABLE_CRON","ENABLE_SSH","ENABLE_DEV","NGINX_CONF","NGINX_PORT","PHP_DISPLAY_ERRORS","PHP_OPCACHE_VALIDATE","PHP_MAX_CHILDREN","PHP_TIMEZONE","PUPPETEER_SKIP_CHROMIUM_DOWNLOAD","WEB_ROOT","COMPOSER_MEMORY_LIMIT","COMPOSER_PROCESS_TIMEOUT","XDEBUG_ENABLE","XDEBUG_HOST","SMTP_HOST","SMTP_PORT","SMTP_USER","SMTP_PASS","SMTP_FROM","EDITOR","VISUAL","GIT_EDITOR","GITPOD_INSTANCE_ID","GITPOD_WORKSPACE_ID","GITPOD_WORKSPACE_URL","THEIA_MINI_BROWSER_HOST_PATTERN","GITPOD_GIT_USER_EMAIL","GITPOD_REPO_ROOT","GITPOD_CLI_APITOKEN","GITPOD_THEIA_PORT","GITPOD_GIT_USER_NAME","GITPOD_RESOLVED_EXTENSIONS","GITPOD_MEMORY","THEIA_RATELIMIT_LOG","THEIA_WORKSPACE_ROOT","GITPOD_HOST","THEIA_WEBVIEW_EXTERNAL_ENDPOINT","GITPOD_EXTERNAL_EXTENSIONS","GITPOD_INTERVAL","HOME","SUPERVISOR_ADDR"],"level":"debug","message":"passing environment variables to IDE","serviceContext":{"service":"supervisor","version":""},"severity":"DEBUG","time":"2021-03-05T09:31:19Z"}
{"error":"Get \"http://localhost:23000/static/manifest.json\": dial tcp [::1]:23000: connect: connection refused","level":"info","message":"IDE is not ready yet","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","time":"2021-03-05T09:31:19Z"}
bash: cannot set terminal process group (-1): Not a tty
bash: no job control in this shell
{"level":"info","message":"connection was successfully established","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","time":"2021-03-05T09:31:19Z","url":"wss://gitpod.io/api/v1"}
bash: /ide/node/bin/gitpod-node: No such file or directory
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"exit status 127","level":"warning","message":"IDE was stopped","serviceContext":{"service":"supervisor","version":""},"severity":"WARNING","time":"2021-03-05T09:31:19Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"exit status 127","level":"fatal","message":"IDE failed to start","serviceContext":{"service":"supervisor","version":""},"severity":"CRITICAL","time":"2021-03-05T09:31:19Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"exit status 1","level":"error","message":"unexpected exit","ring":1,"serviceContext":{"service":"workspacekit","version":""},"severity":"ERROR","time":"2021-03-05T09:31:19Z"}
{"level":"info","message":"sleeping five minutes to allow debugging","serviceContext":{"service":"workspacekit","version":""},"severity":"INFO","time":"2021-03-05T09:31:19Z"}
```

**Comment by davidwindell** [comment]
Ouch, does Code not support Alpine (btw does Code = [code-server](https://github.com/cdr/code-server)?).

**Comment by akosyakov** [comment]
> Ouch, does Code not support Alpine (btw does Code = code-server?).

No, we don't use code-server, but vanilla Web Code with custom Gitpod Code Server (i.e. vscode-remote): https://github.com/gitpod-io/vscode

It seems there is limited support of Code on alpine, but you should make sure that required deps are installed: https://code.visualstudio.com/docs/remote/linux#_tips-by-linux-distribution

**Comment by davidwindell** [comment]
That's really helpful info thanks, I guess I'll have to rebuild our dev image in glibc!

**Comment by davidwindell** [comment]
So I rebuilt out development image in Ubuntu (took the whole day!) but it was worth it, first run and we have Code working. Thanks all for the quick support, you'll have paying customers out of us for the long term I'm sure.

**Comment by svenefftinge** [comment]
Reopening this, becaue it is still a problem.

**Comment by svenefftinge** [comment]
We should at least show the error status on the loading screen/dashboard, telling users that `alpine` is not supported.

**Comment by svenefftinge** [comment]
I overlooked there is https://github.com/gitpod-io/gitpod/issues/3356
