### ISSUE TITLE
[Dashboard] Usage Page

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3360]
Because we have hour-based subscriptions we need to be transparent about the accounting. 
We used to show this in the usage view. 
@gtsiolis proposal (which I like) is to make it a page that can be reached from within the subscription page.
See screenshot and top right link in #3358.

The data is there, so we'd need to present it (@gtsiolis 👋 ). 
But I consider this low-prio for the redesign, so mark it as a stretch goal.

---

This issue is a placeholder for the secondary page described in https://github.com/gitpod-io/gitpod/issues/3358.

**Comment by tnir** [comment]
ETA?

Where is the data (which I expect it in JSON format, for example) to render as HTML?

**Comment by gtsiolis** [comment]
Reopening this as it's still relevant.

**Comment by svenefftinge** [comment]
I think it would make sense to tackle this in the context of the new pricing.

**Comment by gtsiolis** [comment]
> I think it would make sense to tackle this in the context of the new pricing.

Agree, removing from Product Groundwork / Inbox for now.

FYI, Reopened this after seeing a [relevant discussion](https://twitter.com/yogicodes/status/1428010443491069957) from the community. Cc @bigint @filiptronicek

**Comment by gtsiolis** [comment]
Closing this as we've started rolling a new usage page based on the new usage-based pricing. 

For more context, see :a: **[relevant section](https://www.gitpod.io/changelog/october-gitpod-release-2022#even-more-power--try-large-workspaces-with-usage-based-billing)** in October's changelog and :b: **[relevant docs](https://www.gitpod.io/docs/configure/billing/usage-based-billing)** on usage-based pricing.
