### ISSUE TITLE
Python debugging seems to have broken with 'The debug session type "python" is not supported'

### ISSUE THREAD

**Issue by yeungalan0** [gitpod-io/gitpod#3365]
### Describe the bug
Not sure if this is specifically a Theia or Gitpod issue, but Python debugging seems to no longer work in a Gitpod container with the message 'The debug session type "python" is not supported' when a debug session is attempted.

### Steps to reproduce

1. Start a Gitpod workspace with the example project [here](https://github.com/gitpod-io/Gitpod-Python-Debug).
2. Set a debug breakpoint
3. Try to run the debugger on the current file

### Expected behavior

Debugger works and a "not supported" message is not shown.

### Additional information

![Screenshot from 2021-03-05 07-58-57](https://user-images.githubusercontent.com/3821187/110133635-c429d700-7d89-11eb-98b8-015a46ce7f35.png)
![Screenshot from 2021-03-05 08-04-03](https://user-images.githubusercontent.com/3821187/110133646-c68c3100-7d89-11eb-85ba-c5c7bff3df83.png)

### Example repository
https://github.com/gitpod-io/Gitpod-Python-Debug

**Comment by yeungalan0** [comment]
Installing the "Python" (ms-python.python) extension seems to have fixed this issue. If this was just me then maybe this extension somehow was uninstalled from all my work spaces?

**Comment by akosyakov** [comment]
It sounds strange, we have not changed built-in extensions in Theia. 

Generally though please start switching to Code: https://www.gitpod.io/docs/feature-preview/#default-ide It is going to become a new default rather soon and Theia deprecated.

For Code one we are not going to add additional built-in extension compare to Theia. And users have to add them to .gitpod.yml in repos. We are going to update our examples accordingly: https://github.com/gitpod-io/gitpod/issues/3341
