### ISSUE TITLE
Workspace "Crashed"

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3370]
I was coding along (using Vs Code) when I got alerts stating that websocket connections don't work.
I kept clicking through a couple of times and continued coding. Eventually I decided to try reloading the page in order to get rid of it, which broke my workspace completely.
I now see an "empty" VS Code (i.e. no workspace folder, no terminals).
The workspace is still reported to be running.

https://magenta-chameleon-rc5izdpb.ws-eu03.gitpod.io/

After I filed the information here, the workspace reloaded and worked again.

**Comment by apolopena** [comment]
I experienced the exact same issue yesterday three times during the day, PST timezone.

**Comment by akosyakov** [comment]
From logs it looks like a frontend reconnected, there was not server side crash of something like that. Maybe related to https://github.com/gitpod-io/gitpod/issues/3327, i.e. Code frontend cannot always nicely recover on reconnection.

Do you have any frontend side logs? Code Frontend does not log anything to backend.

**Comment by svenefftinge** [comment]
I think there were issues with connecting gitpod.io.

**Comment by akosyakov** [comment]
I had several similar reports today from different people. The issue always bad connection to gitpod.io but Code behaves very bad. It does not even show any dialog, just some function stop working. It is easily fixed by the page reload, but annoying. Should we look into after next Code upgrade?

**Comment by apolopena** [comment]
> I had several similar reports today from different people. The issue always bad connection to gitpod.io but Code behaves very bad. It does not even show any dialog, just some function stop working. It is easily fixed by the page reload, but annoying. Should we look into after next Code upgrade?

Yeah I am still getting this issue daily.

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/111553225-e591b680-87be-11eb-9c56-43ef2413179b.png)

**Comment by akosyakov** [comment]
@JounQin Can you share a workspace or underlying git repo with which it happened? I am not sure it is related.

**Comment by JounQin** [comment]
@akosyakov This issue is gone to me...

**Comment by akosyakov** [comment]
Please next time when it happens collect data from browser devtools and share them here.
