### ISSUE TITLE
Initializer Failed

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#3371]
### Describe the bug
Workspace creation fails with the error:
```
cannot initialize workspace: cannot initialize workspace: content initializer failed
```

This seems to be an intermittant issue.

### Steps to reproduce
Have not been able to find any yet.

### Expected behavior
Workspace creation should not fail.

### Additional information
Here is the ID of a workspace that failed this way:
`orange-termite-a7vlylvr`

### Example repository
[`gitpod-laravel8-starter`](https://github.com/apolopena/gitpod-laravel8-starter)

**Comment by jankeromnes** [comment]
Thanks for reporting this issue! I believe this is another occurrence of the same (full disk) incident from https://github.com/gitpod-io/gitpod/issues/3372.

The incident has been resolved now, so I'll close this issue, but please report back if you see this problem again.
