### ISSUE TITLE
Fatal: no space left on device

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#3372]
### Describe the bug
Any repo launched gives the error: `no space left on device`

The workspace is not created.

### Steps to reproduce
Create a new workspace from any repo

### Expected behavior
workspace should be created.

### Additional information

![image](https://user-images.githubusercontent.com/3060702/110233815-77561580-7edb-11eb-8ae6-2434ef8751ca.png)
![image](https://user-images.githubusercontent.com/3060702/110233840-9e144c00-7edb-11eb-9996-a180ef65708b.png)

### Example repository
Repos:
[`gitpod-io/sveltejs-template - master`](https://github.com/gitpod-io/sveltejs-template)
[`apolopena/gitpod-laravel8-starter - main`](https://github.com/apolopena/gitpod-laravel8-starter)

**Comment by apolopena** [comment]
I deleted a bunch of my workspaces and the issue went away.

**Comment by jankeromnes** [comment]
Hi @apolopena! Sorry about this problem. What you've observed correlates with a cluster incident we've had over the weekend, where a server disk went full and triggered alerts (now resolved).
