### ISSUE TITLE
[diff view] allow to filter/arrange files in big changes

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#338]
I am reviewing a PR in generated yet checked-in code (Xtext). The manual changes are very hard to find in between the generated ones, as the diff view presents them as a plain list. 

It would be very helpful if 
* I could either filter the list 
* or If I could arrange the changes in a tree based on their directories (there are separated folders for generated code)
* or if the sorting would take directories into account properly (`.../testlang-src/...` comes after `.../testlang-src-gen/...` as `/` comes after `-` in ASCII)

**Comment by svenefftinge** [comment]
See also https://github.com/gitpod-io/gitpod/issues/11
