### ISSUE TITLE
[Dashboard] Account Page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3395]
### Problem to solve

Currently, the there's a) no dedicated account page for the user, b) no way to change their name, email or avatar, and c) no clear way of deleting their account.

This is part of https://github.com/gitpod-io/gitpod/issues/3300. 🍕 

### User Experience goal

The user should be able to a) see their associated name, email, and avatar on a dedicated account page as well as b) be able to easily delete their account if needed.

### Proposal

In this first MVC (minimum viable change), we can do the following:

1. Introduce a dedicated account page.
2. Surface their name, email, and avatar associated with their account.
3. Introduce a clear way to delete their account.

Components involved:
1. Button
2. Text Field (Disabled)

### Future steps
1. In the future, we could allow users to change their name, email, and avatar associated with their account.

### Designs

| Account | Account (Modal) |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/110629461-da320000-81ac-11eb-937f-46dd1d7fea51.png) | ![image](https://user-images.githubusercontent.com/120486/110629475-dd2cf080-81ac-11eb-8b3e-ca5c188ec112.png) |
| ![image](https://user-images.githubusercontent.com/120486/110630082-9a1f4d00-81ad-11eb-9eb7-6d937aab10a3.png) | ![image](https://user-images.githubusercontent.com/120486/110629505-e4ec9500-81ac-11eb-8fbd-d2583b99fb77.png) |

See also [design specs](https://www.figma.com/file/xd47PEurok4COEWSUFn7gW/Account-3395).

### Documentation

No documentation changes are needed for this first iteration.

**Comment by gtsiolis** [comment]
This is almost done but missing some information we had in the old dashboard. 

| Specs | Live |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/112034063-c3918e80-8b46-11eb-99bf-3cbc32b9b8e0.png) | ![image](https://user-images.githubusercontent.com/120486/112034073-c5f3e880-8b46-11eb-9f6f-bf49260e5a24.png) |

We can 🅰️  ship it as is and create a follow up issue to discuss this dfurther or :b: update this within this milesone. /cc @svenefftinge

**Comment by svenefftinge** [comment]
🅰️ ! let's complete the dialog and deletion.
