### ISSUE TITLE
Syntax highlighting not working specifically for .md files

### ISSUE THREAD

**Issue by kairosity** [gitpod-io/gitpod#3396]
### Describe the bug

There is no syntax highlighting on either of my .md files.
### Steps to reproduce

As above. 
### Expected behavior

I would like the highlighting back on markdown files.

**Comment by akosyakov** [comment]
Which editor do you use Theia or VS Code? Please try VS Code: https://www.gitpod.io/docs/feature-preview/#default-ide It is going to be default and Theia will be deprecated.

Also could you share an example repository?

**Comment by kairosity** [comment]
Thanks, that fixed the issue for me.
