### ISSUE TITLE
I got logged out somehow after using for a while

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#34]
To workaround go gitpod.io and log in again

**Comment by akosyakov** [comment]
It happened to me today again, maybe somehow related to prod deployment?

// cc @32leaves @geropl

**Comment by geropl** [comment]
Yes, me too. Seems to be caused by the deployment. Somehow the sessions get invalidated.

Has anyone already investigated? If not I can have a look in the afternoon.
