### ISSUE TITLE
allow to replace supervisor without redeploy

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3408]
Right now the development cycle of IDE facing supervisor APIs is very slow: changing supervisor, waiting for werft, starting vscode WS in dev-staging, waiting for build, ...

It would be good if one can telepresence in running supervisor in prev env, fix the implementation, without going through the entire loop again.

cc @csweichel @JanKoehnlein

**Comment by csweichel** [comment]
I'm afraid that is not possible. Telepresence can only replace an entire pod, which would wreak havoc with ws-manager's assumptions.

We could attempt to (re-)introduce a "supervisor restart mode" where supervisor can restart itself. This way we could basically replace `supervisor` in a running workspace. We've attempted something like this in the past with little avail, but now that we're having `workspacekit` in front, things should be easier.
