### ISSUE TITLE
Missing update on file deletion

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#341]
**Describe the bug**
The newly created file isn't removed if open the Preferences tab

**To Reproduce**

1. Login to the site
2. Open any workspace
3. Click File -> Settings -> Open Preferences
4. Click File -> New File and save it
5. Click the Preferences tab
6. Right-click the newly added file on the left-side panel
7. Select the Delete option from context menu
8. Observe the result

**Actual result**
The newly created file isn't removed if Preferences tab is opened

![01](https://user-images.githubusercontent.com/41964662/53500634-6c2dab00-3ab3-11e9-91be-ac6946f681b4.gif)

**Expected result**
The newly created file should be removed successfully on clicking the Delete option

**Comment by svenefftinge** [comment]
I've noticed issues with file watching sometimes, too. I doubt this has to do with the preferences.
