### ISSUE TITLE
[code] Sometimes the Git view in the bottom bar is outdated (after force-push, for example)

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3420]
### Bug description

Sometimes after (force?) pushing changes to a remote, the SCM view in the bottom bar is outdated. It still shows 1 remote / 1 local, but should be even after the last force-push (cmp. screenshot).

### Steps to reproduce

Does not seem to be reliable, but this triggers it from time to time:
 - have a diff between remote and local branch
 - `git push --force`

### Expected behavior

It should update to "even" shortly after the push succeeded.

![image](https://user-images.githubusercontent.com/32448529/110755863-bb357b80-8249-11eb-861a-7c4937914c49.png)

**Comment by AlexTugarev** [comment]
Could it be, that you did not accept to periodically call `git fetch`? It usually asks on each workspace start, so it's likely a setting (somehow) scoped per workspace URL.
