### ISSUE TITLE
Gitpod keeps working after hours are up

### ISSUE THREAD

**Issue by FeixuRuins** [gitpod-io/gitpod#3422]
### Bug description

I started my workspace with about 30 mins left of usage time. My usage time is now up and I can still keep using it. I assume that if I restart the workspace I won't be able to keep using it, but it still should kick you off when your time ends.

### Steps to reproduce

Start a workspace when you have little time left. Wait for your time to hit 0. Nothing happens.

### Expected behavior

It should kick you off.

**Comment by JanKoehnlein** [comment]
Thanks for reporting this and thanks for your honesty. We're looking into this issue. 
In the meantime, enjoy coding at our cost!
