### ISSUE TITLE
cant find my documments in gitpod 

### ISSUE THREAD

**Issue by arielstark1** [gitpod-io/gitpod#3425]
### Bug description

i use my gitpod create a new folder and save all yesterday works but today is not working

### Steps to reproduce

save all , close and my documents is missing

### Expected behavior

i cant see my file index.html
or 
style.css

### Example repository

my file is https://apricot-emu-b1t034le.ws-us03.gitpod.io/#/workspace/html-hello
https://olive-parrotfish-8r4vb67q.ws-us03.gitpod.io/#/workspace/instagram
https://gitpod.io/start/#lavender-giraffe-4buk0s7m

**Comment by FeixuRuins** [comment]
Happened to me too. Hit `View` and then `Explorer`.
![image](https://user-images.githubusercontent.com/66232834/110855690-b2ae6680-8284-11eb-905a-09f581f5fa07.png)

**Comment by akosyakov** [comment]
https://apricot-emu-b1t034le.ws-us03.gitpod.io/#/workspace/html-hello is created for https://github.com/4GeeksAcademy/html-hello repo which does not have such files. Did you create a fresh new workspace or restarted old one?

Please check https://gitpod.io/workspaces/ to find your old workspaces. Ideally you should fork your own repo and push changes to GitHub.
