### ISSUE TITLE
`open in github` does not work for issue context

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#343]
It would be nice if it opens:
- a corresponding issue if nothing is selected
- master branch for the selection

**Comment by svenefftinge** [comment]
So it means it doesn't respect the 'origin' branch, but uses the local one?

**Comment by akosyakov** [comment]
It works only if an upstream branch is set.

**Comment by svenefftinge** [comment]
But there is a origin/branch pointing to the same commit. Shouldn't we use that in such cases?
