### ISSUE TITLE
Merge the left and right sidebars on the iPad

### ISSUE THREAD

**Issue by akaFTS** [gitpod-io/gitpod#3436]
When coding on a smaller screen like iPad, every inch of screen real estate matters. This way, it would be really useful if the two menus on the right could be added into the left sidebar, freeing up some space:

![Imgur](https://i.imgur.com/U0ZIXXl.jpg)

**Comment by svenefftinge** [comment]
You can go to gitpod.io/settings and enable feature preview. This will switch your account to use vscode as the IDE which is more optimized for ipad and already does what you are asking for.
