### ISSUE TITLE
[content-service] Refactor components/content-service/pkg/storage/storage.go

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#3437]
The file [storage.go](https://github.com/gitpod-io/gitpod/blob/b5129229861fcbd3c2f9fe233aa9a611945bf1a0/components/content-service/pkg/storage/storage.go) has 2 primary interfaces: `DirectAccess` and `PresignedAccess`

https://github.com/gitpod-io/gitpod/blob/b5129229861fcbd3c2f9fe233aa9a611945bf1a0/components/content-service/pkg/storage/storage.go#L117-L134

https://github.com/gitpod-io/gitpod/blob/b5129229861fcbd3c2f9fe233aa9a611945bf1a0/components/content-service/pkg/storage/storage.go#L53-L72

As the range of features of the content service has increased, the responsibilities of the two interfaces have become increasingly intermingled. While `DirectAccess` gets a state with the Init function (owner and workspace) and provides direct access to workspace-related objects, `PresignedAccess` provides are more stateless access to presigned URLs and gets the object name etc. for each call. The latter allows also to access objects other than workspace backups.

Since we now use `PresignedAccess` to get presigned URLs for workspace backups as well, the calculation of workspace backup object names etc. is needed in both interface implementations. The distinction between the two interfaces makes less and less sense in my opinion.

In my opinion, it makes sense to refactor `storage.go` and merge the two interfaces into one that provides abstract access to the storage objects. Whether we need direct access or access via a presigend URL should be distinguished by choosing the proper function and not the proper interface. This would simplify the interface and avoid duplications.

**Comment by csweichel** [comment]
The statefulness of `DirectAccess` is a direct remnant of the days of `ws-sync`. I'd be rather happy to see this go away and instead have
- proper abstraction over object/bucket stores (`CreateBucket`, `Upload`, `DeleteObject`, `SignUpload` ...) rather than semi-Gitpod semantics
- separation of storage access and naming things. If we had something like `StorageObjectNamer` that would maintain the state currently held in `DirectAccess`

**Comment by geropl** [comment]
@corneliusludmann Are you planning to tackle this issue in the April cycle? If yes: could you assign yourself; if not, move to May? Thx! :pray:

**Comment by csweichel** [comment]
This issue still matters indeed, but considering the current load we have I don't see how we can fit this in right now. I'll remove from groundwork for now. Please re-add at a later time.
