### ISSUE TITLE
"Go" diagnostics not shown outside editor

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#344]
**Description:**
The "No problems have been detected in the workplace so far" message is displayed in the "Problems" console when having some mistakes in the "Go" file

**Steps To Reproduce:**
1. Login to the site
2. Start the workspace (Go)
3. Open the "Go" file and make a mistake(s)
4. Pay attention to the "Problems" console

**Actual result:**
The "No problems have been detected in the workplace so far" message is displayed in the "Problems" console when having some mistakes in the "Go" file.

![diagnostics](https://user-images.githubusercontent.com/41964662/53563692-7e642380-3b5d-11e9-8b21-07cf8c8d6ca4.gif)

**Expected result:**
A description of the problem(s) is/are displayed in the "Problems" console when having some mistakes in the "Go" file

**Additional Information:**
Win 10 Google Chrome 72.0.3626.119
Win 10 Firefox 65.0.1

**Note**
The same issue is reproduced for "Ruby", "CSS" and "Rust" files

**Comment by rishabh96b** [comment]
@tarasdidyk are you saving the changes? Linter should be picking those up when you have saved your changes.
