### ISSUE TITLE
[supervisor] Provide IDE logs as terminal

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3442]
When supervisor starts tasks, it runs them in a terminal that can be accessed using supervisor's API.
Supervisor should do the same with the IDE process, i.e. run it in a terminal to make it accessible through is API.
The `status/ide` service would return the name of the IDE terminal.

**Comment by akosyakov** [comment]
We will need to filter out such processes from IDE.

**Comment by akosyakov** [comment]
fyi in new VS Code you can see IDE backend logs in Output -> Remote Server channel, so you don't need to create a new terminal and attach to it.

**Comment by akosyakov** [comment]
It could be useful to track down issues when VS Code does not work nicely because of missing or incompatible decencies, like here: https://github.com/gitpod-io/gitpod/issues/3832#issuecomment-819259865
