### ISSUE TITLE
User extensions not getting installed on new workspaces (Code)

### ISSUE THREAD

**Issue by j-erasmus** [gitpod-io/gitpod#3466]
### Bug description

I have a few user extensions that I'd like to shared between workspaces, but none of my extensions are automatically installed on new workspaces when using "Code" as my editor.

### Steps to reproduce

1. Open a workspace (using Theia)
1. Install an extension for (user)
1. Change editor to "Code"
1. Create a new workspace
1. Notice that the extension installed in step 1 is not automatically installed

### Expected behavior

User extensions should be automatically installed.

### Example repository

Any repository

**Comment by akosyakov** [comment]
Are you sure that you installed them as sync? Please check that settings sync is on and inspected synched data: https://code.visualstudio.com/docs/editor/settings-sync

**Comment by j-erasmus** [comment]
> Are you sure that you installed them as sync? Please check that settings sync is on and inspected synched data: https://code.visualstudio.com/docs/editor/settings-sync

@akosyakov yes, setting sync is turned on. I tried to replicate it now but couldn't, so I guess it's resolved by itself, or maybe I was being impatient 😄 🤷‍♂️ 

Thank you for the quick reply! Closing.
