### ISSUE TITLE
Pop out preview pane

### ISSUE THREAD

**Issue by pwjablonski** [gitpod-io/gitpod#347]
Hey! Loving using gitpod. I am wondering if there is any way to pop out the preview of an HTML file into a new browser tab. 

Thanks

Peter

**Comment by svenefftinge** [comment]
Hi Peter, great to hear you are happy with it so far.
In the preview there is an icon on the top right, that will open the URL in an external browser window.
Is that what you were looking for? 
If so, any idea how we could have made this more accessible/discoverable to you?

**Comment by pwjablonski** [comment]
Yes that is what I am looking for but I still can't seem to find it. Would it be possible for you to send a screenshot. This is what I see.
![screen shot 2019-03-01 at 5 05 21 pm](https://user-images.githubusercontent.com/9774128/53743577-23864100-3e69-11e9-8786-b74d60e0501c.png)
?

**Comment by svenefftinge** [comment]
Ah, I see now you are using the static preview. For that there is no such option.
A very easy way to view your files in a separate browser is to start a web browser.
E.g. run the following command in the terminal:
```sh
python -m http.server 3000
```

**Comment by pwjablonski** [comment]
Okay thank you @svenefftinge !

**Comment by svenefftinge** [comment]
you are welcome!

**Comment by FlukerBr** [comment]
> Ah, I see now you are using the static preview. For that there is no such option.
> A very easy way to view your files in a separate browser is to start a web browser.
> E.g. run the following command in the terminal:
> 
> ```shell
> python3 -m http.server 3000
> ```



> Ah, I see now you are using the static preview. For that there is no such option.
> A very easy way to view your files in a separate browser is to start a web browser.
> E.g. run the following command in the terminal:
> 
> ```shell
> python3 -m http.server 3000
> ```

i love you
