### ISSUE TITLE
[Code][Staging] Preview has broken icons in Firefox Nightly on Mac OS

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3474]
### Bug description

New Code Preview pane controls have broken icons in my Firefox Nightly on Mac OS.

<img width="400" alt="Screenshot 2021-03-17 at 09 40 00" src="https://user-images.githubusercontent.com/599268/111442987-38a93200-8709-11eb-99ad-c8806d800c92.png">

### Steps to reproduce

1. Open a Preview

### Expected behavior

Control icons should work

**Comment by akosyakov** [comment]
It should be resolved in the upstream, see https://github.com/microsoft/vscode/issues/120036
