### ISSUE TITLE
[Code][Staging] .gitpod.yml extension from the Svelte example repo is not getting installed

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3476]
### Bug description

When opening the Svelte example repository in Gitpod Code (Staging), the Svelte extension listed [in the `.gitpod.yml`](https://github.com/gitpod-io/sveltejs-template/blob/2f01570c4ed7c56423ac00a3bfab36209f82052e/.gitpod.yml#L13-L15) is not getting installed by Gitpod.

The consequence is that `*.svelte` files are not getting syntax-highlighted:

<img width="600" alt="Screenshot 2021-03-17 at 09 43 37" src="https://user-images.githubusercontent.com/599268/111449702-ecadbb80-870f-11eb-9110-45356330d170.png">

<img width="600" alt="Screenshot 2021-03-17 at 09 41 24" src="https://user-images.githubusercontent.com/599268/111449723-f33c3300-870f-11eb-8f8d-892c08c5f0bf.png">

### Steps to reproduce

1. Open https://github.com/gitpod-io/sveltejs-template in Gitpod Code (Staging)
2. Notice that `svelte.svelte-vscode` is not getting installed
3. Open `App.svelte` -- notice that there is no syntax highlighting

### Expected behavior

- `svelte.svelte-vscode` (and any other `.gitpod.yml` extension) should get auto-installed
- `*.svelte` files should get syntax highlighted

### Example repository

https://github.com/gitpod-io/sveltejs-template

**Comment by jankeromnes** [comment]
Working theory:

> could it be because we use different buckets on staging to store extensions?

**Comment by jankeromnes** [comment]
Potential workaround: Remove the extension version / hash:

> Important! We should not use hash based identifiers in .gitpod.yml anymore we are going drop it in future, but proper syntax is `${publisher}.${name}`, i.e. `redhat.vscode-java`, the latest extension will be installed from Open VSX on the workspace startup.

**Comment by akosyakov** [comment]
fixed by https://github.com/gitpod-io/sveltejs-template/commit/ca5b93a31425f6f26a4916b498fe6d084af1ba17
