### ISSUE TITLE
Workspaces broken when running Ubuntu 18.04

### ISSUE THREAD

**Issue by davidwindell** [gitpod-io/gitpod#3477]
### Bug description

We have a workspace base image that works fine with Ubuntu 20.04 but not with Ubuntu 18.04. There are a number of console errors such as:

```
  ERR Error: No authentication provider 'gitpod' is currently registered.
    at AuthenticationService.getSessions (workbench.web.api.js:218394)
    at async UserDataSyncWorkbenchService.getAccounts (workbench.web.api.js:297489)
    at async UserDataSyncWorkbenchService.update (workbench.web.api.js:297477)
    at async UserDataSyncWorkbenchService.initialize (workbench.web.api.js:297465)
    at async UserDataSyncWorkbenchService.waitAndInitialize (workbench.web.api.js:297446)
```

### Steps to reproduce

1. Launch a workspace with the Dockerfile:
```
FROM ubuntu:18.04
```
2. Port browser doesn't work and console errors:

### Expected behavior

Should operate correctly as `FROM ubuntu:20.04` does

**Comment by akosyakov** [comment]
Do you have workspace id to share? It would be helpful to investigate what went wrong. It sounds like the gitpod vscode extension failed to activate.

**Comment by davidwindell** [comment]
@akosyakov hey, thanks - https://plum-planarian-360n26z1.ws-eu03.gitpod.io/

I've tested in Theia and it seems to have the same problems there.

**Comment by davidwindell** [comment]
@akosyakov I can reproduce this with a simple Dockerfile:

https://github.com/davidwindell/gitpod-test/blob/test/Dockerfile

```
FROM ubuntu:18.04
```

**Comment by aledbf** [comment]
@akosyakov I can't reproduce this issue with the current main branch
I created https://github.com/aledbf/gitpod-ubuntu-18 to reproduce the issue.

**Comment by davidwindell** [comment]
Just to say that I can reproduce the issue with your example repo (but on Gitpod.io not main)

**Comment by aledbf** [comment]
@davidwindell after yesterday's release, I can't reproduce the issue. 
Please confirm that using https://gitpod.io/#https://github.com/aledbf/gitpod-ubuntu-18 works as expected.

**Comment by davidwindell** [comment]
We've moved on from Ubuntu 18.04 so no longer have a base image to test against so I will close this now.
