### ISSUE TITLE
[feature] Soft-Deleted users to make abuse harder

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3485]
Currently we often see the pattern that abusers (crypto miners, spammers, etc.), after they have been blocked by us, delete their account and immediately re-create it with the same GitHub account and E-Mail. This is bad because:
 - abusers are not really "blocked"
 - it destroys evidence

This would be solved by a "delayed delete" like we have it for workspaces:
 - soft-delete when the user hits "delete"
 - keep in the DB for some time:
   - long enough that it actually blocks spammers
   - short enough to be GDPR compliant: we have a "justified interest" to investigate and block abuse
 - hard-delete all soft-deleted users after this time
 
 In addition, this would give us the chance to un-delete users account whenever a user requests that.
 
 References:
  - https://github.com/gitpod-com/gitpod/issues/4331

**Comment by wulfthimm** [comment]
Hashing user information like username and email-addresses for good and checking them when a new user logs in would be possibility to stay GDPR compliant.
