### ISSUE TITLE
[Staging] When starting a workspace, it shouldn't take 35 seconds for the workspace URL to respond

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3489]
### Bug description

When starting a workspace on the latest https://main.staging.gitpod-dev.com/workspaces/

- It takes about 10 seconds before you get a workspace URL (~expected)

- Then, when you redirect to the workspace URL, it now takes **about 35 seconds** before that URL starts loading (that's the bug)

Screencast: https://youtu.be/ZJdQYBb3yQ8

### Steps to reproduce

1. Open Gitpod in Gitpod(staging): https://main.staging.gitpod-dev.com/#https://github.com/gitpod-io/gitpod

2. When the create page redirects, observe the 35 seconds of "nothing" before the workspace page loads (and shows other things like "Pulling Docker Images" etc. -- these are out of scope here)

### Expected behavior

The workspace URL should load much faster.

### Example repository

https://github.com/gitpod-io/gitpod

**Comment by jankeromnes** [comment]
Here's the Jaeger trace for the 35 seconds (unfortunately, they happen in code we don't trace yet):

<img width="1440" alt="Screenshot 2021-03-18 at 15 41 30" src="https://user-images.githubusercontent.com/599268/111648234-7094a000-8803-11eb-84fb-28793fb3ecd3.png">

**Comment by csweichel** [comment]
I'm not entirely certain that's the same 35 seconds we're talking about. What you're seeing in the trace is the image pull for the workspace container (hence the "gap" in the trace). That process is independent of the 35 sec start screen loading. 

If after that time the container had been running that would be indicative of a blobserve routing issue.

**Comment by csweichel** [comment]
I'll add metrics to blobserve and a response header that shows who actually answered the request.

**Comment by jankeromnes** [comment]
I've never seen this again since switching from Theia to Code (around the kumquat release).
