### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by mwz** [gitpod-io/gitpod#35]
Support for [Scala](https://www.scala-lang.org) would be really nice.

**Comment by svenefftinge** [comment]
Not sure which LS is better. For Metals they have a big warning for not using it
 - https://github.com/dragos/dragos-vscode-scala
 - https://github.com/scalameta/metals

**Comment by mwz** [comment]
I'd give metals a go even though it's in an alpha stage - I think that you should still be able to get something decent with it.

**Comment by kamilkloch** [comment]
Any news with regard to support for Scala? Metals plugin for VS code is already gorgeous: https://marketplace.visualstudio.com/items?itemName=scalameta.metals. Monaco language client is here: https://github.com/TypeFox/monaco-languageclient

**Comment by svenefftinge** [comment]
You can subscribe to this https://github.com/gitpod-io/gitpod/issues/433
It will allow to install the extension.

**Comment by danbim** [comment]
@tgodzik has successfully integrated Metals with gitpod 🎉 ! See https://twitter.com/olafurpg/status/1186978651025399808?s=20

**Comment by svenefftinge** [comment]
Thanks. I'm closing this ticket.
