### ISSUE TITLE
TestExtractTarbal simple test fails 

### ISSUE THREAD

**Issue by sri-vathsa** [gitpod-io/gitpod#3500]
### Bug description

I am trying to build the image-builder component using the command `leeway build .:docker -c none` command and the build is failing as this `TestExtractTarbal/simple-test` test failed with the following error
```
[components/content-service:lib] === RUN   TestExtractTarbal/simple-test
[components/content-service:lib] time="2021-03-19T07:36:15Z" level=warning msg="cannot chown" error="lchown /tmp/3142113074/target/file2.txt: operation not permitted" gid=33333 path=file2.txt uid=33333
[components/content-service:lib] time="2021-03-19T07:36:15Z" level=warning msg="cannot chown" error="lchown /tmp/3142113074/target/file.txt: operation not permitted" gid=33333 path=file.txt uid=33333
[components/content-service:lib]     tar_test.go:93: expected uid 33333
[components/content-service:lib]     tar_test.go:93: expected uid 33333
[components/content-service:lib] === RUN   TestExtractTarbal/empty-tar
[components/content-service:lib] --- FAIL: TestExtractTarbal (0.00s)
[components/content-service:lib]     --- FAIL: TestExtractTarbal/simple-test (0.00s)
[components/content-service:lib]     --- PASS: TestExtractTarbal/empty-tar (0.00s)
```

### Steps to reproduce

I am using go lang version 1.16 and using ubuntu 20 on ec2. Set LEEWAY_WORKSPACE_ROOT environment variable to the repo root and 
`cd components/image-builder` and when you try to build the component using `leeway build .:docker -c none` you'll see the following error.

### Expected behavior

The test case should pass

**Comment by geropl** [comment]
Hi @sri-vathsa ,

this sounds like a permission problem with EC2 instances.

With Gitpod Self-Hosted currently we aim at a very narrow set of target architectures, and the same goes for our build process: It's not guanrateed nor expected to work outside our build env.

I'm going to close this because we do not plan to act on this. If you plan to dig into it and try to fix please re-open.
