### ISSUE TITLE
no longer able to initialize the workspace. 

### ISSUE THREAD

**Issue by vonstark** [gitpod-io/gitpod#3506]
### Bug description

no longer able to initialize the workspace. 
I don't know why, suddently all my 4 workspaces couldn't start.

The response is "User is unauthorizted"

Yet I check the usage is still enough, and github has gitpod authorized in oauth apps.

### Steps to reproduce

just go my workspace list and click.

**Comment by geropl** [comment]
Sorry @vonstark , we had an outage in the US cluster today: https://github.com/gitpod-io/gitpod/issues/3499 This is resolved now.
