### ISSUE TITLE
"Start Workspace" ignores time limit

### ISSUE THREAD

**Issue by FeixuRuins** [gitpod-io/gitpod#3509]
### Bug description

Even if your time is up, you're able to go to [https://www.gitpod.io/#get-started](https://www.gitpod.io/#get-started) and hit one of the `Start Workspace` buttons and create a workspace without any error. You can only use it once, however. You can't start it again after stopping it.

### Steps to reproduce

Go to [https://www.gitpod.io/#get-started](https://www.gitpod.io/#get-started) and create a workspace.

### Expected behavior

It shouldn't let you make one if your time is up.

**Comment by geropl** [comment]
Thx for the report @FeixuRuins !

Currently we're re-implementing the whole frontend, so I will expect this bug to be "fixed" as side-effect soon.
