### ISSUE TITLE
Blink

### ISSUE THREAD

**Issue by AceKnight97** [gitpod-io/gitpod#351]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
void setup(){
        pinMode(13,OUTPUT);
}
void loop(){
        digitalwrite(13, HIGH);
        delay(500);
        digitalwrite(13, LOW);
        delay(500);
}

**Comment by jankeromnes** [comment]
Hi @AceKnight97!

Thank you for opening this issue. I believe it is not a valid Gitpod bug, as there is no description or steps to reproduce a problem, so I will mark it as closed. But feel free to re-open it with more details.

Here is what you code looks like in Gitpod by the way:

<img width="1552" alt="screenshot 2019-03-04 at 09 54 06" src="https://user-images.githubusercontent.com/599268/53721489-a6a49880-3e63-11e9-8bfe-e61c31a58abb.png">

**Comment by AceKnight97** [comment]
It's very kind of you and your website, thank you very much!
