### ISSUE TITLE
Error: Can't connect using SSH with Chisel

### ISSUE THREAD

**Issue by delucca** [gitpod-io/gitpod#3520]
### Bug description

I've followed the suggestion on [this repo](https://github.com/corneliusludmann/gitpod-playground/tree/sshd-over-chisel) regarding how to connect with Gitpod using SSH. 

I was able to authenticate my local terminal, but, for some reason, I can't connect. Here is the output:
```
[1375] Mar 20 21:44:09 Child connection from ::1:56940
[1375] Mar 20 21:44:09 Pubkey auth succeeded for 'gitpod' with key sha1!! 66:1d:07:4b:8a:cc:a3:bd:4a:ea:d5:b0:6d:99:17:19:ed:6d:b9:44 from ::1:56940
[1375] Mar 20 21:44:10 Exit (gitpod): chown(/dev/pts/3, 33333, 5) failed: Operation not permitted
[1375] Mar 20 21:44:10 chown /dev/pts/3 0 0 failed: Operation not permitted
```

### Steps to reproduce

You can create a new workspace with [this repo](https://github.com/corneliusludmann/gitpod-playground/tree/sshd-over-chisel) and try to connect following the instructions

### Expected behavior

I would like to be able to connect with my workspace using SSH.

### Example repository

https://github.com/corneliusludmann/gitpod-playground/tree/sshd-over-chisel

**Comment by davidwindell** [comment]
@delucca this is a duplicate of my issue #3424

**Comment by akosyakov** [comment]
We announced Gitpod Local Companion last week which allows to SSH into Gitpod workspace: https://www.gitpod.io/blog/local-app Please open new issues if it does not work for you for some reasons or any other feedback around using it.
