### ISSUE TITLE
Gitpod Bug

### ISSUE THREAD

**Issue by JavonMagee** [gitpod-io/gitpod#3522]
### Bug description

I am unable to log in and start workspaces

### Steps to reproduce

Try to login through Github account

### Expected behavior

Copied and pasted result you should expect here:

Sorry, something went wrong 😓
Error 504
Please file an issue if you think this is a bug.

**Comment by jankeromnes** [comment]
Thanks for reporting this incident! Duplicate of https://github.com/gitpod-io/gitpod/issues/3515
