### ISSUE TITLE
Inability to Start Workspace

### ISSUE THREAD

**Issue by xtc-dev** [gitpod-io/gitpod#3524]
### Bug description

Whenever I attempted to start my workspace earlier, it didn't load, I returned to the dashboard and the workspace was at a "Unknown" state . 

### Steps to reproduce

* Start an existing workspace

* Go back to the dashboard

### Expected behavior

Start a workspace as normal

![image](https://user-images.githubusercontent.com/69604405/111911874-9f965600-8a3d-11eb-8d53-5555e6f06a56.png)

**Comment by jankeromnes** [comment]
Hi @xtc-dev, thanks for reporting this! Likely the same problem as this weekend's general instability, see https://github.com/gitpod-io/gitpod/issues/3515
