### ISSUE TITLE
Not connected to message bus

### ISSUE THREAD

**Issue by amafjarkasi** [gitpod-io/gitpod#3527]
### Bug description

When opening workspaces I'm getting error not connected to message bus

### Steps to reproduce

Open workspaces

![image](https://user-images.githubusercontent.com/65797881/111934627-2b3cd080-8a98-11eb-84f9-fe3df8bf5aa6.png)

**Comment by jankeromnes** [comment]
Thank you for reporting this incident. Also closing this as a duplicate of this weekend's US cluster instability: https://github.com/gitpod-io/gitpod/issues/3515
