### ISSUE TITLE
User's name is not picked up when signing up with GitLab

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3532]
### Bug description

User's name is not picked up when signing up with GitLab.

### Steps to reproduce

1. Sign up for a new account using GitLab
2. Go to `/account` and see the Name field.

_Originally posted by @gtsiolis in https://github.com/gitpod-io/gitpod/pull/3521#discussion_r598167924_

**Comment by AlexTugarev** [comment]
@gtsiolis, I cannot reproduce this. Just created a fresh environment and signed up with GL, which reminds me to change email BTW ;-)

<img width="1279" alt="Screen Shot 2021-03-25 at 14 05 41" src="https://user-images.githubusercontent.com/914497/112477360-354e2000-8d73-11eb-8bf5-5f1e65f6edc7.png">

**Comment by gtsiolis** [comment]
@AlexTugarev in the screenshot you posted you should be seeing the name, not the username, right? 💡
