### ISSUE TITLE
[Dashboard] Start Project

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3534]
On an empty active workspaces list we currently propose to start an example (btw. they are not templates, we should change that). We ideally should allow users to start something closer to home. 
A relatively easy and useful thing would be to list the most recently used projects (weighting recent and number of uses).
The examples could be in a second tab, and the component could have a search.

### Proposal

Adding a few additional points to consider:

1. Change the copy and rename the primary action button on the empty state for the workspaces list from _Select Template_ to _New Workspace_.
2. Add a primary action button on the filters area when there are active workspaces. Remember to hide the primary action button from the filters list when the workspaces list is empty.
3. Introduce tabs within the modal and list _Recent_ first, _Examples_ second.
4. Include an empty state for the Recent tab for new users with a primary action button to switch to _Examples_.

### Designs

| List | Empty |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/112007179-1f4f1e00-8b2d-11eb-9a35-5e7b01593368.png) | ![image](https://user-images.githubusercontent.com/120486/112007175-1e1df100-8b2d-11eb-98b8-0c25e8aaf133.png) |

| Recent | Recent (Spacing) |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/112007313-3beb5600-8b2d-11eb-96fa-ea2b0b373257.png) | ![image](https://user-images.githubusercontent.com/120486/112007335-3f7edd00-8b2d-11eb-9cdf-6b4d4b488a3f.png) |

| Examples | Examples (Spacing) |
|-|-|
|  ![image](https://user-images.githubusercontent.com/120486/112007525-64735000-8b2d-11eb-8a3d-6b5d9246f9b2.png) | ![image](https://user-images.githubusercontent.com/120486/112007531-663d1380-8b2d-11eb-9b2f-b1fe91674e61.png) |

| Recent (Empty) | Recent (Empty) (Spacing) |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/112007659-840a7880-8b2d-11eb-9fe1-7c69456ff382.png) | ![image](https://user-images.githubusercontent.com/120486/112007692-8b318680-8b2d-11eb-8e81-2b47763ba1af.png) |

For the case in https://github.com/gitpod-io/gitpod/issues/3531, we could introduce an empty state with the following message and link to the new _Integrations_ (`/integrations`) page:

> ### No Example Projects
> We could not find any example projects for this provider. Authorize with more providers to access more examples projects. 

See also [design specs](https://www.figma.com/file/112TQeB2XhNBc73tIl4ss5/Workspaces-Modal-3534?node-id=0%3A1).

**Comment by gtsiolis** [comment]
Love the idea and this could make it easier to introduce a _Recent_ filter on the workspaces list if needed. Not sure about making it the first tab as this would be empty for new users, however, this could be ok if we could link directly to the second tab, when the recent list is empty, using an empty state like the following:

> ### No Recent Projects
> Start Using an [Example Project](#).

I assume this would use the [Repository Context](https://www.gitpod.io/docs/context-urls/#repository-context) using the default branch, right?

Also, ok for renaming _Templates_ to _Examples_. Templates is something we could consider in the future as skeleton workspaces to build upon. Additionally, we could allow users to select an existing project from their authorized provider making it a third tab here.

**Comment by lukechu10** [comment]
I think in the workspace list under the `Name` column, the repository URL should be shown in bold instead of the workspace id. Most of the times, people will be interested in the project name rather than the id of the workspace (which would only be useful for diagnosing problems remotely). Just my two cents.

**Comment by svenefftinge** [comment]
Hey @lukechu10! Thanks for the feedback. We are trying to educate people to not restart old workspaces, but rather start fresh ones all the time. To that end, we are highlighting the project names in the dialog to start a new workspace and move non-running workspaces out of the way by having a filter that defaults to only showing active workspaces (running or pinned).
Does that make sense?
