### ISSUE TITLE
Text alligment is broken in Terminal after resizing

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#354]
Steps:
1. Login to the site
2. Start the workspace
3. Split several new Terminals 
4. Resize any Terminal
5. Pay attention to the text alligment in resized Terminal

Actual result: Text alligment is broken in Termian after resizing 
![2019-03-04_12-40-13](https://user-images.githubusercontent.com/41964662/53742109-8ba44980-3ea0-11e9-8428-7e892c6f02b4.jpg)

Expected result: Text alligment is NOT broken in Termian after resizing

Additional Information: 
Windows 10  Google Chrome 72.0.3626.119 // Firefox  65.0.2

**Comment by AlexTugarev** [comment]
In vscode the updates are throttled on resize, maybe we should do the same in Theia to mitigate this issue. I mean, it's already much better since the recent releases of Xterm.js, but I still see it when trying to resize fast enough.
