### ISSUE TITLE
Graduate `sudo docker-up` functionality out of Feature Preview

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#3540]
Using root and docker-compose within Gitpod bring simplification for otherwise complex docker setup.
For an example using `ddev` in gotpod to setup PHP projects with ease, https://github.com/shaal/ddev-gitpod

For projects that require such functionality, like `sudo docker-up`, it is not possible to launch them correctly, unless users enable that feature preview in their user settings before launching a project.

Graduate this functionality out of Feature Preview, would allow everyone to enjoy these benefits.

**Comment by aledbf** [comment]
@shaal the required changes for this was merged today https://github.com/gitpod-io/gitpod/pull/3413
