### ISSUE TITLE
Unable to see workspaces 

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#3547]
### Bug description

Going to the Workspaces page results in no workspaces shown, when logged in via Github

### Steps to reproduce

Click on the workspaces page

### Expected behavior

Able to see workspaces

**Comment by mai1015** [comment]
same here, cannot even login

**Comment by suipingooi** [comment]
same. again!

**Comment by meysholdt** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/3548. Apologies for the trouble.
