### ISSUE TITLE
Workspaces in the US cluster not starting again

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#3548]
### Bug description

A repeat of the symptoms of Friday and Monday. Running in `ws-us003`.
- Cannot consistently log in with github
- If able to login, cannot consistently view the Workspaces page
- If able to login, get stuck on on the "Starting Page" starting a new workspace on then goes to Red screen of death

### Steps to reproduce

Start any workspace

**Comment by meysholdt** [comment]
Thank you for your report. There was indeed an issue related to an overloaded Database and Messagebus. We've mitigated the issue by routing all traffic into the EU where those problems don't occur.

**Comment by meysholdt** [comment]
Since workspaces are starting again, I am closing this issue.
