### ISSUE TITLE
"Don't show again" is not applied for the  warning message

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#355]
Steps:
1. Login to the site
2. Start the workspace
3. Click the ""Don't Show Again"" button in warning pop-up 
4. Reload the web-page
5. Pay attention to the displayed warning

Actual result:  ""Don't show again"" is not applied for the  warning message
![2019-03-04_17-16-22](https://user-images.githubusercontent.com/41964662/53742443-49c7d300-3ea1-11e9-83e2-4361837c6058.jpg)

Expected result: ""Don't show again"" is applied for the  warning message

Windows 10 Google Chrome 72.0.3626.119 // Firefox 65.0.2

**Comment by AlexTugarev** [comment]
depends on https://github.com/theia-ide/theia/issues/1078

**Comment by AlexTugarev** [comment]
resolved ✔️
