### ISSUE TITLE
[vscode] terminals resizing issues on reload

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3553]
### Bug description

On page reload the content is not nicely resized.

### Steps to reproduce

- Start a workspace with VS Code
- Reload the page and output should be nicely formatted.
- But it is rendered narrowly instead.

There are also strange messages in terminals on start sometimes:
```
your 131072x1 screen size is bogus. expect trouble
```

**Comment by akosyakov** [comment]
I was able to reproduce by removing focus from the window, i.e. opening another tab while reloading. The theory is that we push data while terminal did not compute proper sizes yet, so it is rendering everything with default, i.e. 1 cols, 1 rows.

**Comment by akosyakov** [comment]
I used bogus initial resize sizes, i.e. (1, 1). It should be (0, 0) then they are overidden by initial resize. I will fix in the context of https://github.com/gitpod-io/gitpod/issues/3694

**Comment by jankeromnes** [comment]
I was just able to reproduce this issue, twice in a row, by opening:

https://akosyakov-unable-to-open-files-3874.staging.gitpod-dev.com/#https://github.com/whatwg/html

<img width="1092" alt="Screenshot 2021-04-22 at 17 14 56" src="https://user-images.githubusercontent.com/599268/115739812-865f2d00-a38e-11eb-88b6-5435ed30f500.png">

in Firefox Nightly (88) on Mac OS.

This is the preview environment of https://github.com/gitpod-io/gitpod/pull/4040 that was just merged into Gitpod Core.
