### ISSUE TITLE
Error: Not connected to message bus (can't launch new or connect to old worspaces)

### ISSUE THREAD

**Issue by delucca** [gitpod-io/gitpod#3557]
### Bug description

As soon as I try to launch any workspace, I see the following error:

```
Error: Not connected to message bus
```

EDIT: I've just tested and I cannot connect to existing workspaces too.

### Steps to reproduce

Create a new workspace, or try to connect with an existing workspace.

### Expected behavior

I would like to be able to connect to my workspaces.

### Example repository

Any

**Comment by corneliusludmann** [comment]
Thanks for reporting. We're investigating.

**Comment by delucca** [comment]
> It seems to be a local problem (maybe only US). It works from Europe (tested Cyprus and Austria).

Just for the record, I'm on Brazil right now. But probably Brazil uses the same server as the US

**Comment by corneliusludmann** [comment]
Yes, it's US only.

**Comment by corneliusludmann** [comment]
Sorry for the inconvenience, again. We're back on track. US is operational again. Workspace start could take some time currently. Please let me know if you still have any trouble.

**Comment by delucca** [comment]
Thanks @corneliusludmann 

Closing this issue now.
