### ISSUE TITLE
[dashboard] login no TOS

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3562]
On first login, there's still a page that looks like this:

<img width="418" alt="Screenshot 2021-03-23 at 20 42 58" src="https://user-images.githubusercontent.com/372735/112208353-8eee0780-8c18-11eb-94fd-9c3e52201be1.png">

**Comment by svenefftinge** [comment]
Another login related small thing is that there is no bitbucket logo. (seen in staging)

**Comment by AlexTugarev** [comment]
Indeed,
1️⃣ I could reproduce with updated ToS and logging in
2️⃣ logo is off, and the list of scopes doesn't fit

**Comment by AlexTugarev** [comment]
1️⃣  https://github.com/gitpod-com/gitpod/pull/5218 
2️⃣  checked in https://github.com/gitpod-io/gitpod/pull/3582

**Comment by gtsiolis** [comment]
This has been resolved! Thanks @AlexTugarev! 🏀 

Thanks @jankeromnes for also bringing back ther Bitbucket logo in https://github.com/gitpod-io/gitpod/pull/3602! 🏀
