### ISSUE TITLE
[feedback] report a problem

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#3564]
# overview

Whilst Gitpod has monitoring fine-grain monitoring and logging we do not yet have an in-product way to capture feedback from customers and overlay these insights onto our monitoring.

# feature request

Provide a way for customers to report problems related to a workspace.

# implementation ideas

- Add report a problem functionality as a button/menu item in the workspace IDE interface that can be used during usage of a workspace.
- Add report a problem functionality in the dashboard that can be used if a workspace does not initialise.

# see also
- https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

**Comment by ghuntley** [comment]
Placing this into the product inbox after [this incident](https://www.gitpodstatus.com/incidents/mpkdzm5rpbc5). Members of the community shared that they were having issues inside an existing GitHub issue that was already open thus visibility was limited. Gitpod needs a way to report faults within the product.

**Comment by atduarte** [comment]
I agree it would be helpful surfacing the "Report a problem" in the application, particularly as many users may not be aware they can do so here. Although I'm not sure how it would help to have an additional channel, in which we would probably receive the same type of questions, requests, bugs, and false positives we already receive here. Would a link to [New issue](https://github.com/gitpod-io/gitpod/issues/new/choose) work?

**Comment by atduarte** [comment]
Duplicate of #4196.
