### ISSUE TITLE
user input ingnored with getchar() at least

### ISSUE THREAD

**Issue by jgueytat** [gitpod-io/gitpod#3566]
### Bug description

The IDE does not wait for the user input.

The terminal does print "Press enter to continue..." and wait.
The IDE does not.

### Steps to reproduce

- open the repository https://github.com/jgueytat/HelloWorld-in-C with GitPod
- select gcc kit for CMake, configure and build all
- run the program through the IDE

### Expected behavior

Getting the prompt

### Example repository

https://github.com/jgueytat/HelloWorld-in-C

**Comment by jgueytat** [comment]
Both extensions **webfreak.debug** and **eclipse-cdt.cdt-gdb-vscode** can not get the input properly.

**Comment by jgueytat** [comment]
I am able to reproduce the bug locally with VSCode.

**Comment by akosyakov** [comment]
You are using VS Code correctly, not Theia?

**Comment by akosyakov** [comment]
> I am able to reproduce the bug locally with VSCode. In case I need to open a bug somewhere else where should it be?
Thanks in advance !

I will start with extensions and maybe with VS Code too: https://github.com/microsoft/vscode

**Comment by jgueytat** [comment]
I was able to get the user input with the Microsoft extension on VSCode. So it has to be a trouble with the extensions themself.
May be we can close this one, or wait for the C/C++ extensions to handle it.

**Comment by akosyakov** [comment]
If there is nothing to do on Gitpod side I would prefer to close.
