### ISSUE TITLE
[dashboard] it is not possible to select and copy text in the workspace list

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3567]
### Bug description

Please make everything selectable and copyable, that's just annoying (not accessible) UX then it is not possible.

### Steps to reproduce

Open workspaces list, try to select a URL of a workspace.

**Comment by jankeromnes** [comment]
It seems that one cannot select/copy text in `<a/>` links in the dashboard.

Given that an entire workspace widget is a `<a/>` link, selecting text in it is impossible. (Changing it into a `<div/>` allows selecting some text, but not where there are other `<a/>` links.)

I'm not sure if this is a Tailwind thing or not.

**Comment by gtsiolis** [comment]
We moved with making the whole row an active link to a) make it easier to open a workspace, b) improve the information hierarchy besides structure in the workspace entry layout, as well as c) reuse the same interaction across the product (see [examples modal](https://github.com/gitpod-io/gitpod/issues/3534), [running workspaces modal](https://github.com/gitpod-io/gitpod/issues/3301), etc).

Eventually we will turn more text elements (repository, context, etc) into active links like the _Pending Changes_ element. In the meantime, as a workaround you can drag and select from outside the workspace entry to select any text in there. /cc @akosyakov @jankeromnes 

<img width="1133" alt="Screenshot 2021-03-24 at 1 21 05 PM" src="https://user-images.githubusercontent.com/120486/112304334-0ae26100-8ca6-11eb-868a-ef91cc3bd7ea.png">

**Comment by svenefftinge** [comment]
solved

**Comment by akosyakov** [comment]
I still cannot select, instead it drags the whole entry.

**Comment by akosyakov** [comment]
It also happens here, I cannot select any part of text or use double click to do it:
<img width="633" alt="Screenshot 2021-04-01 at 15 12 59" src="https://user-images.githubusercontent.com/3082655/113299299-04369800-92fd-11eb-8abb-94abf990dea8.png">

**Comment by gtsiolis** [comment]
Thanks, @akosyakov! I've added a follow up issue (see https://github.com/gitpod-io/gitpod/issues/3711) for improving this list.

**Comment by gtsiolis** [comment]
Closing this, added follow up in https://github.com/gitpod-io/gitpod/issues/3712 for improving the workspaces list. /cc @akosyakov
