### ISSUE TITLE
Terminal do not print all characters

### ISSUE THREAD

**Issue by Oaks** [gitpod-io/gitpod#357]
**Describe the bug**
In terminal I can't type characters      /_*")+>@^

**Comment by AlexTugarev** [comment]
Hi @Oaks, please provide some info about your browser and maybe language or keyboard settings. 

This should work on current Chrome/Firefox/Safari:
<img width="85" alt="screen shot 2019-03-05 at 08 29 07" src="https://user-images.githubusercontent.com/914497/53788140-2e041180-3f21-11e9-9ddd-35cc81a4c058.png">

**Comment by Oaks** [comment]
Hi @AlexTugarev .
It is not work in browser Slimjet 20.0.4.0 (based on Chrome) 32bit.
But is work ,as you say , in Chrome.
Thanks for your fast answer and sorry for my slow answer.

**Comment by pickfire** [comment]
It doesn't seem to print any characters at all in firefox.

**Comment by AlexTugarev** [comment]
> It doesn't seem to print any characters at all in firefox.

@pickfire, which version of Firefox are you using?

/cc. @jankeromnes

**Comment by pickfire** [comment]
@AlexTugarev Firefox 66.0.2 (64-bit) - Arch Linux

**Comment by jankeromnes** [comment]
> In terminal I can't type characters /_*")+>@^

Wow, pretty strange issue 😐 (looks almost like an iPad bluetooth keyboard problem, but on Arch Linux / Firefox that wouldn't make any sense).

In any case, this is likely a bug with [xtermjs](https://github.com/xtermjs/xterm.js), or maybe [theia](https://github.com/theia-ide/theia).

@spoenemann are you aware of any keymapping issues in Theia or Xtermjs that could cause this?

**Comment by geropl** [comment]
I'm on Firefox 64.0 (64-bit), Linux Mint (based on Ubuntu 16.04). I use the terminal without problems.

@pickfire What kind of keyboard/keyboard layout do you use?

**Comment by pickfire** [comment]
@geropl I use uk keyword, dvorak us layout with fcitx ime. But the issue is not about typing, I can type but I cannot see the words, only the cursor.

**Comment by spoenemann** [comment]
> are you aware of any keymapping issues in Theia or Xtermjs that could cause this?

No idea. The problem seems not to be on the keybindings, but on a different level.

**Comment by geropl** [comment]
> fcitx ime

I never used it, but would assume that this somehow causes the behavior. Do you know which encoding it outputs?
Also, to clarify: The cursor moves to the right, but you cannot see the characters? Or is this a coloring issue with your webbrowser? Some default css?

**Comment by pickfire** [comment]
IME probably does not affect that, I only use it to input chinese and japanese characters. It uses utf8.

Other pages displays but just gitpod does not display any characters on the terminal (except the cursor).
Nope, I didn't modify the css, I did check ad-block but there are no issues.
