### ISSUE TITLE
Blank Terminal. Can't Type

### ISSUE THREAD

**Issue by SantiagoYanezFerreiro** [gitpod-io/gitpod#3570]
### Bug description

Hi, my Terminals are blank, and can't type on them. It's very awkward, I never had this problem before.

### Steps to reproduce

Enter GitPod Repository, try to type on terminal

### Expected behavior

Terminal should work

### Example repository

https://teal-squirrel-n76jrpgz.ws-eu03.gitpod.io/

![image](https://user-images.githubusercontent.com/38229837/112298457-f34bae00-8c8e-11eb-94f6-f0c3e6365c92.png)
[](url)

**Comment by akosyakov** [comment]
Please restart the workspace. It is known bug and should be addressed in the March milestone: https://github.com/gitpod-io/gitpod/issues/3127
