### ISSUE TITLE
Align integrations page with the design specs

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3574]
### Problem

The new _Integrations_ page does not follow the design specs close enough. Both the providers list and the modal for editing permissions lack proper alignment and spacing. See https://github.com/gitpod-io/gitpod/issues/3401.

**Comment by svenefftinge** [comment]
I think @AlexTugarev is already working on this.

**Comment by AlexTugarev** [comment]
Let's check with https://github.com/gitpod-io/gitpod/pull/3582
