### ISSUE TITLE
Feature Preview is enabled and still getting error when trying to run sudo apt-get install ---

### ISSUE THREAD

**Issue by ericsupreme** [gitpod-io/gitpod#3576]
### Bug description

Feature Preview is enabled and still getting error when trying to run sudo apt-get install

### Steps to reproduce

Feature Preview is enabled and still getting error when trying to run sudo apt-get install

**Comment by svenefftinge** [comment]
What kind of error do you get? And did you start a new workspace after you enabled feature preview?

**Comment by ericsupreme** [comment]
i get bash: sudo: command not found. when i checked to see if feat preview was enabled , it was already.

**Comment by aledbf** [comment]
> i get bash: sudo: command not found

@ericsupreme that means `sudo` is not installed in the docker image you are using.
The next screenshot was taken using the [svelte template example](https://github.com/gitpod-io/sveltejs-template)

![Screenshot from 2021-03-24 17-40-01](https://user-images.githubusercontent.com/161571/112380415-20688280-8cc8-11eb-9984-30c46ca29804.png)

**Comment by ericsupreme** [comment]
hmmm i actually came across this when googling but i guess i didn't understand. so what can i do now? it is a pre-built image...

**Comment by aledbf** [comment]
> most solution to the sudo issue says "just create a docker image" but the image is already created is there a way i can add commands to it? or it must be rebuilt..

You can "extend" the docker image you already have. Please check this example https://github.com/aledbf/gitpod-postgis

- Uses a custom .gitpod.Dockerfile to use gitpod/workspace-postgres as base image.
- Install the PostGIS extension.

In your case, maybe the `.gitpod.Dockerfile` could be like
```dockerfile
USER root
RUN apt update && apt install -y sudo
```

**Comment by JanKoehnlein** [comment]
I assume this is fixed by above description. Please reopen if the problem persists
