### ISSUE TITLE
Cannot set environment variable

### ISSUE THREAD

**Issue by acgetchell** [gitpod-io/gitpod#3580]
### Bug description

cannot set environment variables: error while issuing request: Post "http://localhost:23000/gitpod/cli": dial tcp [::1]:23000: connect: connection refused

### Steps to reproduce

https://gitpod.io/#https://github.com/acgetchell/CDT-plusplus

### Expected behavior

The environment variable should be set per: https://www.gitpod.io/docs/environment-variables/

### Example repository

https://github.com/acgetchell/CDT-plusplus

**Comment by akosyakov** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/3162
