### ISSUE TITLE
Image embedded in the Gitpod GitHub application is 502

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#3583]
### Bug description

![image](https://user-images.githubusercontent.com/127353/112427329-89fe9480-8d8d-11eb-9e1c-818b8a3257fa.png)
![image](https://user-images.githubusercontent.com/127353/112427355-9256cf80-8d8d-11eb-8732-f0c3c44c26ad.png)

![image](https://user-images.githubusercontent.com/127353/112427385-9be03780-8d8d-11eb-97e2-fc71e55f9082.png)

See https://github.com/unoplatform/uno/pull/5550?fbclid=IwAR2gRDo5UXserLfgFl_q0txb9EIsQEp3wnzBpDt-m1fA0xw_1o6UVtmMKDQ#issuecomment-805415378

### Steps to reproduce

See https://github.com/unoplatform/uno/pull/5550?fbclid=IwAR2gRDo5UXserLfgFl_q0txb9EIsQEp3wnzBpDt-m1fA0xw_1o6UVtmMKDQ#issuecomment-805415378

### Expected behavior

Image displays

### Example repository

```
<a href="https://gitpod.io/#https://github.com/unoplatform/uno/pull/5550"><img src="https://gitpod.io/api/apps/github/pbs/github.com/unoplatform/uno.git/1dc0e3b315f999d48d31dfbf3bd72e081cda339f.svg" /></a>

```

**Comment by JanKoehnlein** [comment]
Is this still an issue?

**Comment by carldebilly** [comment]
It's workign again.  You can close the issue.
