### ISSUE TITLE
Need capture ctrl + w which could close tab

### ISSUE THREAD

**Issue by moonrailgun** [gitpod-io/gitpod#3586]
I am in the habit of use `ctrl + w` to close file.

And its easily close whole tab in gitpod, and i have to reopen it with a looooong time to load assets.

Its frustrating...

Even a alert before close tab will be fine

**Comment by davidwindell** [comment]
An alert is easy to acheive, just add `"application.confirmExit": "always"` to your settings.json.

**Comment by JanKoehnlein** [comment]
Exactly. F1 > Settings: Open Preferences > "application.confirmExit": "always" does the job in Thea, in VS Code it's already enabled by default.

We're evaluating [Gitpod as a PWA](https://github.com/gitpod-io/gitpod/issues/1445) which could also mitigate this.
