### ISSUE TITLE
[dashboard] Blocked user page is using obsolete design specs

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3588]
### Problem to solve

The blocked user page (`/blocked`) still lacks design specs following the dashboard redesign. This page is served to the user when the user has been blocked.

| Blocked User |
|-|
| <img width="618" alt="Screenshot 2021-03-25 at 1 13 13 PM" src="https://user-images.githubusercontent.com/120486/112464208-df29ae80-8d6b-11eb-953b-470fdb1f3e83.png"> |

### Proposal

Redesign the blocked user page following the design language of the new dashboard design.

Things to consider before making any changes:

1. Linking to the terms of service in case of abuse.
2. Remove this page altogether and introduce an error alert in the login page.

### Designs

| Blocked | Blocked (Spacing) |
|-|-|
| <img width="1440" alt="Blocked" src="https://user-images.githubusercontent.com/120486/112874007-09140580-90cb-11eb-80d1-edf4481b7421.png"> | <img width="1440" alt="Blocked (Spacing)" src="https://user-images.githubusercontent.com/120486/112873996-05807e80-90cb-11eb-8bef-34a4493f3c80.png"> |

See also [design specs](https://www.figma.com/file/5yAST3ny38gA58YG4Y1z2A/Blocked-user-3588?node-id=0%3A1).

Thanks for catching this @jankeromnes and @AlexTugarev! 🏀

**Comment by jankeromnes** [comment]
Fixed in https://github.com/gitpod-io/gitpod/pull/3760
