### ISSUE TITLE
[dashboard] Add design specs for the login redirection page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3589]
### Problem to solve

The login redirection page (`/login-success`) is designed to automatically close but in some rare cases the user can end up with a redirection page that did not close automatically. See also [relevant discussion](https://gitpod.slack.com/archives/C01KGM9BUNS/p1616663892154300) (internal).

This page contains only the following text information:

>  This browser tab is supposed to close automatically.

| Redirection Page |
|-|
| <img width="401" alt="Screenshot 2021-03-25 at 1 44 09 PM" src="https://user-images.githubusercontent.com/120486/112467826-30d43800-8d70-11eb-93b7-ed12ccd539b1.png"> |

### Proposal

We could consider providing some minimal design specs that also provide some action links like a button to manually close thew tab or window.

### Designs

TBD (To be discussed)

Thanks for catching this @akosyakov! 🏀

**Comment by svenefftinge** [comment]
> some rare cases

any idea what those cases are?

**Comment by akosyakov** [comment]
> any idea what those cases are?

Muscle memory of closing a page if a button opens another page. I'm actually not sure that it would be rate. We don't hit it because we already have expectations from the button.

**Comment by gtsiolis** [comment]
FYI, this has been updated in https://github.com/gitpod-io/gitpod/pull/3950 (Thanks @AlexTugarev!) to include a close button which could help if not suffice for now. /cc @akosyakov @svenefftinge 

| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/115219672-6ae6ee80-a110-11eb-844b-555fccdbd2df.png) | ![image](https://user-images.githubusercontent.com/120486/115220027-c1ecc380-a110-11eb-80ce-12124d752f1f.png) |

**Comment by akosyakov** [comment]
Maybe a button to go to back to original URL if it does not close automatically? Otherwise you close and you have nothing.

**Comment by AlexTugarev** [comment]
> Maybe a button to go to back to original URL if it does not close automatically? Otherwise you close and you have nothing.

Nope. It's hard to reproduce the situation in the first place, i.e. you'd need to close the dashboard which remains in background. How would you expect to open the URL of origin from there?

If you close the dashboard (aka main window,) I'd rather expect the satellites to be closed automatically. 🤔 this might be even easily to implement.
