### ISSUE TITLE
Cannot view file bar

### ISSUE THREAD

**Issue by hackermondev** [gitpod-io/gitpod#3590]
### Bug description

On the gitpod workspace, i cannot see the files and the only way to get them Is using CTRL + P to search for a file

### Steps to reproduce

I just went into the workspace and it happened. 

![image](https://user-images.githubusercontent.com/60828015/112468459-a7f0d880-8d3e-11eb-80f6-8df158a0bb9c.png)

**Comment by akosyakov** [comment]
Most likely the layout failed to restore. Could you try f1 -> reset layout? Also please start switching to VS Code: https://www.gitpod.io/docs/feature-preview/#default-ide It is going to become default soon.

**Comment by hackermondev** [comment]
@akosyakov the article doesn't really say how to switch to vscode

**Comment by hackermondev** [comment]
nevermind i found it lol

**Comment by gtsiolis** [comment]
Thanks @hackermondev @akosyakov @JanKoehnlein! Closing this.
