### ISSUE TITLE
AWS self hosted - error during installation process

### ISSUE THREAD

**Issue by statictype** [gitpod-io/gitpod#3591]
### Bug description

unable to finish installation on aws

### Steps to reproduce

I followed the intructions from here https://www.gitpod.io/docs/self-hosted/latest/install/install-on-aws-script/
Installation went well for aprox 10-15 min and then i got this error

Error: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden

### Expected behavior

installation works

![Screenshot 2021-03-25 at 14 17 10](https://user-images.githubusercontent.com/42985153/112480172-09806980-8d76-11eb-9c05-47574c11cb22.png)

**Comment by lovetodream** [comment]
Same issue with aws
