### ISSUE TITLE
[dashboard] Add missing tooltips from the workspaces list

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3592]
### Problem to solve

The design specs in https://github.com/gitpod-io/gitpod/issues/3426 for the new Workspaces list contained some tooltips that surface hidden information like workspace creation timestamp and lifecyle state of the workspace (Starting, Stopping).

### Proposal

Add these two tooltips on hover.

**Comment by apolopena** [comment]
I have a couple of possible helpful proposals:

**Show the tooltip for the workspace state on the colored dot**:
![image](https://user-images.githubusercontent.com/3060702/112664915-bbbc3d80-8e17-11eb-904f-c557c44d04ab.png)

**Regarding the Last Active column**:
How would the 'Last Active' column work for workspaces that are active? It seems like a bit of contradiction to have a 'Last Active' status of 'Running' or to have anything in the that row for a workspace that is not stopped. The wording 'Last Active' may infer to some users that the workspace is no longer active.

Would the 'Last Active' state be better named 'Status'? That way workspace state (lifecycle) information could stay on the top level. For example a workspace that was stopped could have a 'Status' of 'Last active 10 minutes ago' or a running workspace could have a 'Status' of 'Running - Started 2 mins ago'.

**Comment by svenefftinge** [comment]
We have changed the column name to `Last Started`.

**Comment by svenefftinge** [comment]
fixed
