### ISSUE TITLE
[dashboard] Update layout and colors for the prebuild output in the loading page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3595]
### Problem to solve

We're going to add a terminal output in the Loading page when a Prebuild is running. The default terminal theme is not using colors used in the rest of the product.

### Proposal

Consider updating the terminal output so that colors are using the color palette from the new dashboard.

**Comment by S3vinit** [comment]
which engine you are using?

**Comment by gtsiolis** [comment]
Hey @S3vinit! We're using `xterm`, see [relevant pull request](https://github.com/gitpod-io/gitpod/pull/3560). 📺
