### ISSUE TITLE
Netlify not able to launch with webpack-dev-server error Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by oyes704** [gitpod-io/gitpod#3597]
### Bug description

Trying to initialize brand new "JAMStack + Netlify + Astra + Cassandra" with a new DSE.

$ netlify dev
◈ Netlify Dev ◈
◈ Overriding command with setting derived from netlify.toml [dev] block: yarn webpack-dev-server
◈ Functions server is listening on 42051
◈ Starting Netlify Dev with #custom
$ /workspace/todo-astra-jamstack-netlify/node_modules/.bin/webpack-dev-server
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /workspace/todo-astra-jamstack-netlify/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/workspace/todo-astra-jamstack-netlify/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspace/todo-astra-jamstack-netlify/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
◈ "yarn webpack-dev-server" exited with code 1. Shutting down Netlify Dev server
error Command failed with exit code 1.

2. I tried the same locally npm -v 7.6.3 throws same error.

3. Changing package.json to 
"webpack": "^5.0.0-rc.3",
"webpack-cli": "^3.3.12",
"webpack-dev-server": "^3.11.0"

Importing with Legacy parameteres doesn't throw errors:
npm install --legacy-peer-deps

But has warning:
WARNING in ./node_modules/node-uuid/uuid.js 59:18-47
Module not found: Error: Can't resolve 'crypto' in 'D:\Projects\DSE\todo-astra-jamstack-netlify\node_modules\node-uuid'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
        - install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "crypto": false }

And not able to save any data to the Astra table.

### Steps to reproduce

1. Create new Astra db/keyspace
2. Launch Netlify as described here: https://github.com/DataStax-Examples/todo-astra-jamstack-netlify#readme
3. See the error

### Expected behavior

Application React To-Do saves data and ToDo list.

**Comment by oyes704** [comment]
It works for data write but not read with the following combinations locally but not from Open Workspace on GitPod:

["webpack": "^5.4.0",
"webpack-cli": "^3.3.12",
"webpack-dev-server": "^3.7.1"](url)


["webpack": "^4.16.3",
"webpack-cli": "3.3.9",
"webpack-dev-server": "3.7.1" ](url)

[npm install --legacy-peer-deps](url)

**Comment by corneliusludmann** [comment]
Hi @oyes704,

Thanks for your interest in Gitpod. Based on your description, it seems that the repo that you try to use has some configuration issues. You should probably ask the repo owner to fix this.

Please let me know if you have a specific issue with Gitpod that I can help you with. To ask for help with the Gitpod setup, you can also use our community forum. https://community.gitpod.io/
