### ISSUE TITLE
Cant launch a workspace

### ISSUE THREAD

**Issue by Sylack-lab** [gitpod-io/gitpod#3599]
### Bug description

Whenever i try to open my Workspace named "Charlotte" it stays loading for hours, but nothing changes.

It shows some errors on the console as well as warnings (Check comment with img)

### Steps to reproduce

1. Open an existing gitpod workspace.
2. Time out from the workspace
3. Try relaunching

Error should happen.

Note: Apparently you're forced to shut down and restart the workspace in order to get it working, i dont know why would you need to do that when re-laucnhing from the timed out interface should work fine.

I also have linked console output images after i got the repository working (Image 2)

### Expected behavior

To load the space and be able of interacting with it.

![image](https://user-images.githubusercontent.com/48862659/112522893-70b21400-8d9e-11eb-8660-6f04b7249ac7.png)
![image](https://user-images.githubusercontent.com/48862659/112523435-0c438480-8d9f-11eb-9677-15513bee35e6.png)

**Comment by akosyakov** [comment]
@Sylack-lab Could you share your full workspace id please?

**Comment by Sylack-lab** [comment]
This?
magenta-dove-1xk20sts

**Comment by Sylack-lab** [comment]
(Closed by accident)
