### ISSUE TITLE
Please add a link to the Browser Extensions on signed-in gitpod.io

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#36]
Thanks for an amazing service! (We're actually building something similar over at https://jntr.io -- truly love your expose-ports-on-the-fly feature!)

Just a quick suggestion: I was searching for your Browser Extensions after trying out the service, but once signed in to https://gitpod.io, the website loses a lot of content (and there is no link to the Browser Extensions).

I had to type "docs.gitpod.io" into my search bar because I remembered the URL to find the Browser Extension link, but other users might not know / remember that URL.

**Comment by svenefftinge** [comment]
Good point. We wanted to get the marketing stuff out of your way as soon as you are a user. But it is probably a bit too much.

**Comment by svenefftinge** [comment]
We have browser extensions for chrome and firefox. And a link to those is displayed in the loading screen when the extension is not installed.
