### ISSUE TITLE
Support creating draft PRs

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#360]
See https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by jankeromnes** [comment]
This seems to work already, I was able to open https://github.com/theia-ide/theia/pull/4533 in Gitpod, which is a draft pull request.

**Comment by svenefftinge** [comment]
I also want to create a draft pull request from within Gitpod. I don't think that's possible.

**Comment by akosyakov** [comment]
I meant from Gitpod.

**Comment by AlexTugarev** [comment]
@jankeromnes, I think we cannot mark them as `Ready for review` yet.
