### ISSUE TITLE
Add support for JetBrains IDEs with Projector

### ISSUE THREAD

**Issue by mvitaly** [gitpod-io/gitpod#3601]
Now that JetBrains IDEs can somewhat officially be accessed remotely, it would be nice to have that as an option with gitpod:
https://jetbrains.github.io/projector-client/mkdocs/latest/

**Comment by aledbf** [comment]
@mvitaly please check https://github.com/gitpod-io/gitpod/issues/3434

**Comment by rmchale** [comment]
I think this would be very useful for iPad development

**Comment by akosyakov** [comment]
@rmchale Have you tried https://github.com/svenefftinge/try-jetbrains-projektor?
