### ISSUE TITLE
Remove the markdown syntax from the new workspace modal

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3603]
### Problem to solve

The example projects in the _New Workspace_ modal in the new dashboard contain some markdown syntax that is not rendering as markdown output.

### Proposal

TBD (To be discussed)

Alternatively, we could safely remove the mardown syntax altogether.

**Comment by svenefftinge** [comment]
Let's remove the markdown syntax and write a migration that updates the examples list.
Also, I'd like to only include real examples, not real-world open-source projects.
