### ISSUE TITLE
Self-hosted GCP install is not reachable

### ISSUE THREAD

**Issue by hephaestus9** [gitpod-io/gitpod#3605]
### Bug description

Documentation seems to be missing a step.

### Steps to reproduce

https://www.gitpod.io/docs/self-hosted/latest/install/install-on-gcp-script/

After following the self-hosted GCP install instructions, using my own subdomain I am unable to reach the URL for the load balancer.  

![gitpod-dashboard1](https://user-images.githubusercontent.com/7241310/112624901-34150580-8dfc-11eb-84c0-7fe312ca3874.png)
![gitpod-dashboard2](https://user-images.githubusercontent.com/7241310/112624919-3aa37d00-8dfc-11eb-8df7-fd953677e591.png)
![gitpod-dashboard3](https://user-images.githubusercontent.com/7241310/112624930-3ecf9a80-8dfc-11eb-85b2-a601d47b37a6.png)

From what I can tell this is not a new issue, but the links I have found in previous issue resolutions all return the 404 page in gitpods documentation, or are for much older versions.  This is my first time installing a kubernetes cluster, and I am not sure how to ssh into the computers as the cloud console gives an error due to the SSD's being used, and unable to find log info from the cluster to find out exactly what the issue is.

**Comment by geropl** [comment]
@hephaestus9 

> After following the self-hosted GCP install instructions

By any chance do you mean these? https://www.gitpod.io/docs/self-hosted/latest/install/install-on-gcp-script
If that's the case: We're planning to deprecated those as we're currently trimming our docs to focus our efforts on more simpler setups with the upcoming 0.9.0 release: https://github.com/gitpod-io/gitpod/issues/3893

I'm closing this. If it's still relevant, or the answer not clear/does not applay, please re-open.
