### ISSUE TITLE
[git] Wrong error message "could not find git on the path"

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#361]
I see this error message for the second time, but git works fine in Theia and in terminals.

![screen shot 2019-03-06 at 10 28 29](https://user-images.githubusercontent.com/914497/53870570-cae6ad80-3ffa-11e9-8e2b-63a88dd97577.png)

/cc. @kittaakos any idea?

**Comment by jankeromnes** [comment]
This also happened to me 8 days ago on staging: https://github.com/TypeFox/gitpod/issues/1938#issuecomment-467455912
