### ISSUE TITLE
Proxy seem to drop some requests

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3611]
### Bug description

Working on https://github.com/gitpod-io/vscode is currently pretty unreliable, as the started webserver serves a huge amount of files and our proxy regularly seems to swallow some of the requests (no responses).
We have to try reloading multiple times until it works.

### Steps to reproduce

1) open gitpod.io/#https://github.com/gitpod-io/vscode
2) wait for the additional window to load (if it stays white you might have seen such a loading issues
3) open dev tools and see network tab.

**Comment by akosyakov** [comment]
I notice the same issues with pprof when I run very long profiling sessions. It seems that there is a timeout for requests. Maybe we should at least set them high enough for port location, not sure about workspace location (although it breaks pprof there and preview too).

**Comment by geropl** [comment]
>  It seems that there is a timeout for requests

This could indeed be the case. There are two ways where this could fail (in the gitpod.io setup):
 - connection proxy -> ws-proxy
 - ws-proxy -> actual service
