### ISSUE TITLE
Gitpod: No space left on device

### ISSUE THREAD

**Issue by codecakes** [gitpod-io/gitpod#3614]
### Bug description

When attempting to run the [develop](https://github.com/Xcov19/covidX) branch on Gitpod, the following error occurs:
dpkg: dependency problems prevent configuration of postgresql-12:
 postgresql-12 depends on postgresql-client-12; however:
  Package postgresql-client-12 is not configured yet.
dpkg: error processing package postgresql-12 (--configure):
 dependency problems - leaving unconfigured
Setting up gnupg2 (2.2.19-3ubuntu2.1) ...
dpkg: dependency problems prevent configuration of postgresql-client:
 postgresql-client depends on postgresql-client-12; however:
  Package postgresql-client-12 is not configured yet.

dpkg: error processing package postgresql-client (--configure):
 dependency problems - leaving unconfigured
Setting up software-properties-common (0.98.9.4) ...
E: py3compile:183: cannot create directory /usr/lib/python3/dist-packages/softwareproperties/dbus/__pycache__: OSError(28, 'No space left on device')
Traceback (most recent call last):
  File "/usr/lib/python3.8/py_compile.py", line 197, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.8/py_compile.py", line 157, in compile
    os.makedirs(dirname)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: '/usr/lib/python3/dist-packages/softwareproperties/dbus/__pycache__'

### Steps to reproduce

1. Go to the develop branch.
2. Open the branch in Gitpod.
3. Wait for Gitpod to build

### Expected behavior

The build should succeed. Gitpod builds images successfully without running out of space.

### Example repository

https://github.com/Xcov19/covidX/
See: https://github.com/Xcov19/covidX/issues/111

**Comment by svenefftinge** [comment]
Sorry, it should be fixed now.
