### ISSUE TITLE
File move events are missing (D'n'D)

### ISSUE THREAD

**Issue by tarasi444** [gitpod-io/gitpod#362]
Description:

Drag&Drop works as Copy/Past (file is copied, not moved)

Steps To Reproduce:

1. Login to the site
2. Start the workspace (classpath is incomplete)
3. Click any file  
4. Move file to another subfolder via Drag & Drop
5. Pay attention to the displayed list of items

Actual result: Drag&Drop works as Copy & Past (file is copied, not moved)
![2019-03-06_16-13-09](https://user-images.githubusercontent.com/29434594/53887802-b66ed900-402b-11e9-8615-dd486b35648d.gif)

Expected result: Drag&Drop works as Cut & Past
Win 10 Google Chrome Version 72.0.3626.119
Win 10 Firefox  65.0.2

**Comment by svenefftinge** [comment]
@akosyakov @AlexTugarev I think the file watching is sometimes broken. Could you check it please?
