### ISSUE TITLE
Error when using Gitpo

### ISSUE THREAD

**Issue by Bradders81** [gitpod-io/gitpod#3628]
### Bug description

Error when l log into Gitpod I get an error that states 'We are having trouble parsing your context Error:NotfoundError.  Screen shot below

This does not stop me accessing my workspace however

### Steps to reproduce

Cleared cookies and checked settings 

### Expected behavior

Not sure.

![image](https://user-images.githubusercontent.com/70446279/112747318-8b59d800-8fac-11eb-8398-d09bc34bfbf8.png)

**Comment by Bradders81** [comment]
Thank you for looking into this.

**Comment by svenefftinge** [comment]
What is the URL (or link) you are using?

**Comment by Bradders81** [comment]
Chrome Gitpod extension

**Comment by svenefftinge** [comment]
And where do you click? We need more information in order to help.
