### ISSUE TITLE
"The debug session type "java" is not supported." error is displayed for incompleted "Start Debugging" action

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#363]
Description:

"The debug session type "java" is not supported." error is displayed for incompleted running debug action

Steps To Reproduce:

1. Login to the site
2. Start the workspace
3. Click the "Debug" -> "Start debugging" 
4. Click anywhere in the workspace 
5. Pay attention to the displayed error

Actual result: "The debug session type "java" is not supported." error is displayed for incompleted "Start Debugging" action
![2019-03-07_11-11-29](https://user-images.githubusercontent.com/41964662/53945217-cf2dcc00-40c9-11e9-95ac-9e8e4f394983.gif)

Expected result:  "The debug session type "java" is not supported." error is NOT displayed for incompleted "Start Debugging" action

Additional Information:
Win 10 Google Chrome Version 72.0.3626.119
Win 10 Firefox  65.0.2

**Comment by svenefftinge** [comment]
This has been fixed and deployed to production.
