### ISSUE TITLE
Errored workspaces don't use the correct status indicator

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3635]
### Problem to solve

The new dasboard surfaces errored workspaces without the correct status indicator.

### Proposal

Use `red-600` for the error status indicator.

| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/112766109-fe009d00-9018-11eb-9fd6-88aa02099ff4.png) |  ![image](https://user-images.githubusercontent.com/120486/112766116-01942400-9019-11eb-81ca-f9c0d48cc779.png) |

**Comment by corneliusludmann** [comment]
@gtsiolis Is it intended, that the interrupted state has color `red-400` and the errored workspace you addressed in this issue should get the color `red-600` as status indicator?

https://github.com/gitpod-io/gitpod/blob/7cc28f0acbe283ce7e6715fb3d2fc7753220f2dc/components/dashboard/src/workspaces/WorkspaceEntry.tsx#L156-L159

**Comment by corneliusludmann** [comment]
What is with the `unknown` state? Currently, the status indicator is rendered with `bg-gitpod-kumquat animate-pulse` (the default, intended for workspaces that are in a transition phase). Should this state get a red indicator as well? The state description does not sound like a transition state but more like a final error state.

https://github.com/gitpod-io/gitpod/blob/9be229e4a2530e333d2cefac1754919ba539119b/components/gitpod-protocol/src/workspace-instance.ts#L85-L87

**Comment by gtsiolis** [comment]
>  Is it intended, that the interrupted state has color ...

Hey @corneliusludmann! I think they can use the same red. I was going to suggest to move forward with the `red-600` but let's go with `red-500` and improve accessibility with color and shape in a later iteration in https://github.com/gitpod-io/gitpod/issues/4225. 🍊 

| `red-400` | `red-500` | `red-600` |
|-|-|-|
| <img width="330" alt="indicator-1" src="https://user-images.githubusercontent.com/120486/120542993-735f6400-c3f4-11eb-95e3-1bb69383d04f.png"> | <img width="330" alt="indicator-2" src="https://user-images.githubusercontent.com/120486/120543001-75292780-c3f4-11eb-80c0-d216bf1a673a.png"> | <img width="330" alt="indicator-3" src="https://user-images.githubusercontent.com/120486/120543003-75c1be00-c3f4-11eb-9307-3facfbf6e3c7.png"> | 

> What is with the unknown state?

Not sure about this one but sounds safe to go with the same red, right? Looping in @jankeromnes @svenefftinge in case they can add any thoughts on this. 💬 

> ... is rendered with `bg-gitpod-kumquat`

Starting and stopping phases can continue to use a yellow-ish color. I think we can safely phase out custom colors like `bg-gitpod-kumquat` and replace it `#FBBF24` from the `colors.amber` palette, see [relevant docs](https://tailwindcss.com/docs/customizing-colors#color-palette-reference). We did import `colors.amber` for the orange palette, however, feel free to leave this out of the scope of these changes.

https://github.com/gitpod-io/gitpod/blob/3d9b16c9978fef250f7f02d8c34eaa17a0654fc3/components/dashboard/tailwind.config.js#L22
