### ISSUE TITLE
Activate workspaces menu on workspaces list

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3641]
### Problem to solve

In the new dashboard, after login you get redirected to the workspaces list but the settings menu is activated.

### Proposal

Activate workspaces menu on workspaces list.

![image](https://user-images.githubusercontent.com/120486/112842508-4a47ed80-90aa-11eb-826c-b60feb10d219.png)

**Comment by svenefftinge** [comment]
fixed
