### ISSUE TITLE
Site is not loaded. "We have trouble connecting to the server..." error is displayed

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#365]
Description: 
Site is not loaded. "We have trouble connecting to the server. Either you are offline or websocket connection are blocked" error is displayed

Steps:
1. Go to the site
2. Pay attention to the error message

Actual result: "We have trouble connecting to the server. Either you are offline or websocket connection are blocked" error is displayed
![2019-03-07_14-58-08](https://user-images.githubusercontent.com/41964662/53959482-6e63bb00-40ec-11e9-98da-e9b21ef33bad.png)

Expected result: No error is displayed at the  attempt to load the site

Additional information
Win 10 Google Chrome Version 72.0.3626.119
Win 10 Firefox  65.0.2

**Comment by svenefftinge** [comment]
An intermediate state on staging
