### ISSUE TITLE
About stale-bot closing issues here

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3657]
## Summary

We're sorry if `stale-bot` closed an issue that is still meaningful to you. This was unintended. If that's the case, please re-open it, or file a new identical issue, and request that the label `meta: never-stale` be added to your issue.

## Full Explanation

We didn't properly triage issues for a long time, and thus left too many issues accumulate that are either not fully qualified, not reproducible, not actionable, or otherwise not useful or meaningful. This causes the few actually-meaningful issues to become lost in the noise, until eventually someone re-files it or fixes it (without closing the original issue) or the component it was filed about gets completely rewritten (like for example VS Code becoming the default IDE, or the dashboard being reimplemented with Tailwind CSS).

## The Solution

That's why we've enlisted the help of stale-bot. It's quite effective (if not ruthless) and it can definitely be over-zealous at times by closing issues that are still relevant.

That's where we need your help. If you see stale-bot closing an issue that is still relevant for you (i.e. it's a well-described bug that is still happening today, or it's a feature request that's still blocking your workflow today) please re-open or re-file it. 🙏

Thank you for being the best developer community we could wish for. Please don't take stale-bot like a sign that we don't care. We honestly do. ❤️

**Comment by gtsiolis** [comment]
Closing this as it's no longer pinned. Thanks @jankeromnes for initialy opening this. 🏀
