### ISSUE TITLE
Improve error message when someone tries to open a merged PR with deleted branch

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#3659]
### Bug description

When I tried opening a pull request which had its branch already merged and deleted, I got an error that really left me wondering what really happened.

### Steps to reproduce

1. Go to a merged PR with a deleted branch
2. Open the URL with GitPod
3. See the error (attached in my comment)
`Error: Cannot read property 'repository' of null`

### Expected behavior

Perhaps something like "couldn't find that branch in this repo, it's been probably deleted!

### Example repository

More of an example Pull Request, here is one: https://github.com/gitpod-io/gitpod/pull/3431

![image](https://user-images.githubusercontent.com/29888641/112963606-d5c38c00-9147-11eb-967a-6b2c37645f71.png)

**Comment by jankeromnes** [comment]
I agree that Gitpod should show a better error message here, so I'll try to fix it.

Also, fun fact, this bug was originally reported as https://github.com/gitpod-io/gitpod/issues/4

**Comment by jankeromnes** [comment]
Fixed in https://github.com/gitpod-io/gitpod/pull/3869, will go live with the next deployment.
