### ISSUE TITLE
Authorize Permission bug

### ISSUE THREAD

**Issue by MaxBrooks114** [gitpod-io/gitpod#366]
When I try to open up one of my github repositories using the gitpod button I get "Unauthorized
This action requires more permissions. Please authorize with github.com to continue." When I try to open the provided link I get: "Sorry, that should not have happened!
Bad request: missing parameters." 

It was working yesterday, without issue.

**Comment by AlexTugarev** [comment]
Thanks for reporting this @MaxBrooks114! Do you have this issue with a private repo?

**Comment by MaxBrooks114** [comment]
I did not have any private repos so I created one, and yes same issue.

**Comment by AlexTugarev** [comment]
@MaxBrooks114, I think we found the issue and will address it shortly. 

As a workaround please log out and log in again.

**Comment by MaxBrooks114** [comment]
Will do. Thanks so much!

**Comment by AlexTugarev** [comment]
@MaxBrooks114 the fix was deployed to production 🎉
