### ISSUE TITLE
Context Menu (of Three Dot menus) is flickering/instable

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#3662]
### Bug description

when moving the mouse pointer outside of the context menu, it's flickering/disappearing and reappearing on hover again.

### Steps to reproduce

switch to `main` branch and try to work with the context menu of tree dot buttons on the dashboard.

![2021-03-30 12 49 47](https://user-images.githubusercontent.com/914497/112977584-85075f80-9156-11eb-8531-29557a680b77.gif)

**Comment by gtsiolis** [comment]
The more actions button (three dots) appearing only when hovering over an row item is by design! The same applies to the workspaces list. Do you think this is confusing?

**Comment by AlexTugarev** [comment]
@gtsiolis it's an issue with the Context Menu ☝🏻 
No issue with the three dots button.

**Comment by AlexTugarev** [comment]
<img width="500" alt="Screen Shot 2021-03-30 at 14 41 06" src="https://user-images.githubusercontent.com/914497/112990159-074b5000-9166-11eb-927d-d5089b76c483.png">

When used in modals, the issue is quite the opposite, i.e. clicking outside of the context menu doesn't dismiss it.

**Comment by gtsiolis** [comment]
Thanks @AlexTugarev! Closing this in favor of https://github.com/gitpod-io/gitpod/issues/3731 which also contains hover state issue and affected pages across the product. 🏓
