### ISSUE TITLE
Restore product reference on the login page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3664]
### Problem

Back in https://github.com/gitpod-io/gitpod/pull/3642#discussion_r603429859, we've made the title of the login page conditional but it's not surfacing the product anymore. /cc @svenefftinge 

### Proposal

Restore product reference on the login page.

| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/112997566-e854ba00-9175-11eb-8716-282fb1d10972.png) | ![image](https://user-images.githubusercontent.com/120486/112997571-e985e700-9175-11eb-9100-d1063a39b143.png) |

**Comment by JanKoehnlein** [comment]
Not sure: Do you expect a discussion whether we want to revert this or is it already decided?

**Comment by corneliusludmann** [comment]
@gtsiolis: Looking at the code, it seems that the “to Gitpod” prefix is rendered only when the welcome panel on the right is there. It's not rendered, when the welcome panel is absent. Do I understand this issue right that it should be the other way around?

https://github.com/gitpod-io/gitpod/blob/f96392a1e429c6bb02fca26c422812d3a3114652/components/dashboard/src/Login.tsx#L131-L131

**Comment by gtsiolis** [comment]
> Do I understand this issue right that it should be the other way around?

Ja! Thanks for taking a look at this @corneliusludmann! 💯

**Comment by gtsiolis** [comment]
> Do you expect a discussion whether we want to revert this or is it already decided?

@JanKoehnlein I think qualifies as **two-way door decision** which we can easily revert if needed. 🚪🚪
