### ISSUE TITLE
Configured debug type 'java' is not supported.

### ISSUE THREAD

**Issue by joelz-jobs** [gitpod-io/gitpod#3668]
### Bug description

Added the below code as 

vscode:
  extensions:
    - vscjava.vscode-java-debug

But still showing below error and notification while I start my workstation 

Error: "Configured debug type 'java' is not supported."
Notification: "Prompt for Install Java"

Each and every time I want to install java and one debugger extension. It taking lot of time.

### Steps to reproduce

open link in gitpod.io 

Link : https://github.com/gitpod-io/spring-petclinic 

### Example repository

 https://github.com/gitpod-io/spring-petclinic

**Comment by joelz-jobs** [comment]
First time raising bug on the public platform, So please ignore if had any mistake

**Comment by akosyakov** [comment]
Please make sure to use VS Code. You can enable it here: https://www.gitpod.io/docs/feature-preview/#default-ide

**Comment by joelz-jobs** [comment]
@akosyakov  Thanks for the helping me. I am using VS Code only, I can fix by using install below extension.

### second-thought:
 Always asking me to install below extension to run java on each time opening container. **Is there any way we can install automatically** ( it may preloaded without any prompt)

1. https://open-vsx.org/vscode/item?itemName=vscjava.vscode-java-debug
2. https://open-vsx.org/vscode/item?itemName=redhat.java

**Comment by akosyakov** [comment]
@joelz-jobs correct, we decided against bloating VS Code with many extensions by default, but keep it as close as possible to the desktop experience. You either should install these extensions for your user or add to .gitpod.yml (see context menu on the extension) to specify for the repo. WIth the latter you should commit changes and restart the workspace to apply them, alternatively you can install them as not sync.
