### ISSUE TITLE
Error when trying to install an extension using VSCode's Semantic Tokens API

### ISSUE THREAD

**Issue by pgfearo** [gitpod-io/gitpod#3673]
### Bug description

It appears that Theia in GitPod does not support VSCode's Semantic Tokens API for extensions that was first published in VSCode stable in May/June 2020.

### Steps to reproduce

Install such an extension that uses the Semantic Tokens API. I used V0.2.6 of the XSLT/XPath extension: https://github.com/DeltaXML/vscode-xslt-tokenizer/releases.

An Error Message shows in the bottom-left corner of the window: 'Activating Extension 'XSLT/XPath for Visual Studio Code' failed: vscode.SemanticTokensLegend is not a constructor.

### Expected behavior

I expected the extension to install without error as it does on VS Code.

### Example repository

https://github.com/DeltaXML/vscode-xslt-tokenizer

Screenshot of error in GitPod: 
![Screenshot 2021-03-31 at 07 26 14](https://user-images.githubusercontent.com/2734234/113100437-5390a180-91f3-11eb-97f7-3fc367048868.png)

**Comment by svenefftinge** [comment]
You can switch to VS Code in the [settings](https://gitpod.io/settings) by enabling "feature preview" on the bottom of the page. It is active when starting new workspaces.
