### ISSUE TITLE
Wrong error message being displayed when running prebuild twice on same commit

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#3687]
### Bug description

In upcoming version of Gitpod - 
Running manual prebuild, when a prebuild is already running on the same commit, results in an error page with the wrong information of what's happening.
```
Unrecognized context: 'prebuild/https://github.com/shaal/gitpod-bug-repro'
```

In the current version of Gitpod, it works as expected, 
```
We are having trouble parsing your context
Error: A prebuild is already running for this commit.
```

### Steps to reproduce

Open a GitHub repo link, with the manual Gitpod prefix command `/#prebuild/`.
https://main.staging.gitpod-dev.com/#prebuild/https://github.com/shaal/gitpod-bug-repro
While this is running - open the same link, in another tab.

You will see that in the 2nd tab the error is: `Unrecognized context: 'prebuild/https://github.com/shaal/gitpod-bug-repro'`

Run the same process above, but in current version of Gitpod, and you'll see the correct error being displayed:
https://gitpod.io/#prebuild/https://github.com/shaal/gitpod-bug-repro

### Expected behavior

Display the correct error message - that another prebuild for that commit is already running.

### Example repository

Any repo would work, I used https://github.com/shaal/gitpod-bug-repro

[Upcoming Gitpod] Screenshot:
![image](https://user-images.githubusercontent.com/22901/113212202-75664480-9244-11eb-90ed-030495b0502c.png)

[Existing Gitpod] Screenshot:
![image](https://user-images.githubusercontent.com/22901/113212287-8d3dc880-9244-11eb-9ca4-7d0f9b67527b.png)

**Comment by jankeromnes** [comment]
Hi @shaal! Many thanks for reporting this issue.

Unfortunately, "Unrecognized context" is kind of a "catch all" for multiple possible problems. The full error is currently logged in the browser console, but I totally agree that the correct error message should be visible on the page.

**Comment by gtsiolis** [comment]
This has been resolved in https://github.com/gitpod-io/gitpod/pull/3693. Thanks for reporting this @shaal!
