### ISSUE TITLE
Update external buttons

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3700]
We need to update the buttons to match the new logo / branding

1) gitpod.io/button/open-in-gitpod.svg (there are other rarely used variants)
2) https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod (it has blue in its name 🙄 )

**Comment by gtsiolis** [comment]
For the first one, we could use the ones we have in [these specs](https://www.figma.com/file/q976RVySxCZbSaFJ9t5QiB/Shared?node-id=534%3A1460). For the shield button we could go with the common shield button style and use our logo there or maybe better the monochromatic version.

**Comment by svenefftinge** [comment]
For shield, we'd need to create a PR on their repo. cc @jankeromnes

**Comment by gtsiolis** [comment]
Added https://github.com/gitpod-io/gitpod/pull/3732 but I could be missing something. /cc @jankeromnes @svenefftinge

**Comment by jankeromnes** [comment]
> For shield, we'd need to create a PR on their repo. cc @jankeromnes

Actually, to https://github.com/simple-icons/simple-icons (the icons library used by shields, where the current logo is). I can make a PR today, but they have very strict rules around SVG formatting so I may need some help.

**Comment by gtsiolis** [comment]
I can help with the SVG icon but what about the shield badge colors:
1. Can we change them?
2. Do we want to change them?
3. Where can we change them?

**Comment by jankeromnes** [comment]
> I can help with the SVG icon

Cool, thanks! 🙌 I've opened a Draft PR here: https://github.com/simple-icons/simple-icons/pull/5425

Here are the guidelines on extracting a minimal icon: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#2-extract-the-icon-from-the-logo

I believe I've already addressed 1. 2. 3. 7. 8., but the `path` still corresponds to the old viewbox (`0 0 36 40`, while `0 0 24 24` is expected) and the icon would also need to be centered.

> but what about the shield badge colors:
>
> 1. Can we change them?

I believe simple-icons controls the logo & color on the left of [Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod), however the blue background on the right is controlled by the word `blue` in the badge URL.

So, we can change the logo & color on the left by sending a PR to simple-icons, but to fix the background color on the right we would need to update the shields badge URL everywhere it's used.

> 2. Do we want to change them?
> 3. Where can we change them?

Left: Yes. Right: Probably as many as we can (e.g. at least everywhere we suggest using a shields badge, like community and Setup Assistant).

**Comment by jankeromnes** [comment]
Er, actually, after trying this:

![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-FFB45B?logo=gitpod)

```
![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-FFB45B?logo=gitpod)
```

I now believe it could be okay to leave the right part blue and just update the simple-icons logo on the left.

**Comment by gtsiolis** [comment]
@jankeromnes yes, let's refrain from using orange on the right. Blue color on the other hand has now little to do with our new brand so maybe we could switch to `lightgray` for the right part. For the left part, we could use a flat white version of the logo as we do in the VS Code status bar. Thoughts? 🏓

**Comment by jankeromnes** [comment]
Okay, now that the new logo has made it through the simpleicons/shields/github cache layers, let's pick a new color for the right part of the badge, then use it everywhere:

- `lightgrey`

![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-lightgrey?logo=gitpod)

```
![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-lightgrey?logo=gitpod)
```

- `A8A29E` (Tailwind warmGray 400)

![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-A8A29E?logo=gitpod)

```
![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-A8A29E?logo=gitpod)
```

- other?

**Comment by gtsiolis** [comment]
Hey @jankeromnes! It seems that this (https://github.com/gitpod-io/gitpod/issues/3771#issuecomment-821068864) slipped between the cracks and the badge colors have been updated again in https://github.com/simple-icons/simple-icons/pull/5464.

I think we're better with this more neautral gray than using the orange background, as seen in https://github.com/gitpod-io/gitpod/issues/3700#issuecomment-827485757. To make this more accessible we could use `gray-500` (`#78716C`).

![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-78716C?logo=gitpod)

WDYT?

**Comment by jankeromnes** [comment]
Aha, good call, thanks!

The only thing that worries me about Gray 500 is that now there is little contrast between the left and right parts of the badge. I wonder if a "Gray 450" would work too. 🤔

**Comment by jankeromnes** [comment]
Splitting hairs even further, we could even imagine a "Gray 475" 😅 (`#847E79`):

![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-847E79?logo=gitpod)

```
![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-847E79?logo=gitpod)
```

**Comment by gtsiolis** [comment]
Haha, you know this is getting really close to `gray-500`, right? 😇 

All `gray-450`, `gray-475`, and `gray-500` should be fine and acccessible. We can also stay with `lightgrey` which is one of the default colors for the badge and users can reuse without fear of what color `908A85` is. WDYT?

**Comment by jankeromnes** [comment]
Haha, true 😅 agonizing over it just a little bit more, I really think the `lightgrey` doesn't look good:

![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-lightgrey?logo=gitpod)

And in the custom colors, I like `gray-475` the most:

![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-847e79?logo=gitpod)

```
![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-847e79?logo=gitpod)
```

Let's go for `gray-475` a.k.a. `#847e79`? 😇🚀

**Comment by gtsiolis** [comment]
LET'S DO THIS. Like in https://github.com/gitpod-io/gitpod/pull/4078#issuecomment-828567105, this is another **two-way door decision** and we'll probably laugh about this discussion when we get back here after sometime. 💯

**Comment by jankeromnes** [comment]
Okay, final change (these badges really want a lot of contrast when all next to each other 🙄) let's go with `gray-450` a.k.a. `#908a85` everywhere! (🙈)

![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-908a85?logo=gitpod)

```
![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-908a85?logo=gitpod)
```

✅
