### ISSUE TITLE
[dashboard] opening a context from the stopping/stopped screen does not work

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3707]
### Bug description

See below.

### Steps to reproduce

See below.

<img width="1904" alt="Screenshot 2021-04-01 at 13 44 10" src="https://user-images.githubusercontent.com/3082655/113289873-18749800-92f1-11eb-8faf-229813027f7e.png">
<img width="1904" alt="Screenshot 2021-04-01 at 13 44 13" src="https://user-images.githubusercontent.com/3082655/113289861-14487a80-92f1-11eb-8b77-e33d9174162d.png">

**Comment by jankeromnes** [comment]
Oh, is that because the link is inside the iframe? 👀

In that case, a potential fix could be to handle the link click with a `onClick` `postMessage` based redirect.

**Comment by akosyakov** [comment]
We used to have code which will send a message to the top window here: https://github.com/gitpod-io/gitpod/blob/58a1436bb607bbcc5d6b3b1263f85fc6d97b2efc/components/supervisor/frontend/src/shared/loading-frame.ts#L14-L21

i.e. any link from iframe should post a message to the top window instead of directly changing window location

**Comment by jankeromnes** [comment]
Indeed, the code is still there:

https://github.com/gitpod-io/gitpod/blob/aaf5f339a9aa39b396eed1da01b92f78c40b7f3b/components/dashboard/src/start/StartWorkspace.tsx#L156-L162

I'm hesitating between a "sophisticated" fix (`<a href="javascript:void(0)" onClick={()=>this.redirectTo('...') />`, doesn't support Cmd+Click) and a "cheap" fix (`<a href="..." target="_blank" />`, doesn't support Click). Any preference?

**Comment by jankeromnes** [comment]
Oh, `target="_parent"` looks promising: https://stackoverflow.com/a/19325592/3461173
