### ISSUE TITLE
[dashboard] prebuilds don't log anything

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#3708]
### Bug description

When I manually create a prebuild using `<gitpodhost>/#prebuild/<repoURL>` I don't see any logs in the big black bogs anymore.

### Steps to reproduce

Trigger a manual prebuild using the prebuild URL
-> log window stays empty

### Expected behavior

The log window should show the output of the prebuild

### Example repository

Any with a longer prebuild build triggered by a `gitpod.yml`

**Comment by csweichel** [comment]
Can't reproduce - if the problem persists, please re-open the issue.
