### ISSUE TITLE
IDE does not open

### ISSUE THREAD

**Issue by DiegoGca** [gitpod-io/gitpod#371]
**Describe the bug**
IDE does not appear, after 'Pulling Docker Images ... (2/3)' it is stuck showing Gitpod logo, but IDE is never launched, even after several minutes.

**To Reproduce**
Using Debian 7.11, Firefox ESR 45.9.0, private browsing.
Either starting Gitpod workspace or creating a new one (via url prefix).

**Expected behavior**
Starting workspace and run IDE as always :)
Create new workspace from url prefix and run IDE

I also captured some logs from Firefox console:
[Pulling Docker Images ... (2/3)]
The resource at "https://www.googletagmanager.com/gtag/js?id=UA-71727855-2" was blocked because tracking protection is enabled.
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create start-workspace.js:57496:9
RWS: init start-workspace.js:51969:16
RWS: connect start-workspace.js:51969:16managed
RWS: bypass properties start-workspace.js:51969:16
Error: WebGL: Disallowing antialiased backbuffers due to blacklisting. start-workspace.js:69933:19
RWS: open start-workspace.js:51969:16
RWS: reconnectDelay: 1571.6004648051073 start-workspace.js:51969:16
Error: WebGL: drawElements: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)

[only Gitpod logo]
La conexión a wss://gitpod.io/api/gitpod fue interrumpida mientras la página se cargaba. start-workspace.js:52014:13
RWS: handleClose Object { shouldRetry: true } start-workspace.js:51969:16
RWS: retries count: 1 start-workspace.js:51969:16
RWS: handleClose - reconnectDelay: 1332.9733973912694 start-workspace.js:51969:16
SyntaxError: missing ; before statement bundle-45f931bac5fe117a0202614d75565918.js:68:517231
Error: WebGL: Disallowing antialiased backbuffers due to blacklisting.

I think this is not the first time I face this issue (or at least related): at February 12, using above PC config described same behavior. BUT using other PC and a recent Firefox version "Channel closed" error appeared as described in #306. I contacted support chat and they provided me my workspace files, so I forgot this issue. That time I could create new worskpaces (and use them flawless).

Will update after using other PC config.

**Comment by DiegoGca** [comment]
Using Linux Mint 19.1 and Firefox 65.0.1 it works (new and old workspaces).
I suggest it's a browser error, since it's and old version (however in current support) rather than OS.

**Comment by svenefftinge** [comment]
Thank you we are looking into it.

**Comment by svenefftinge** [comment]
We should give users a clearer message about what versions of FireFox and Chrome are supported.

**Comment by artalar** [comment]
In my behavior, this bug is reproduced when I open workspace and immediately  **unfocus** browser window.
It is really uncomfortable...

**Comment by svenefftinge** [comment]
@artalar can you describe what you experience in more detail?

**Comment by artalar** [comment]
Hmmm, I can't reproduce it now((
So I don't know (now) why it happens, but it happening often.
Currently I can't run https://e14e3192-7f66-4dc4-8a25-745fa06ba61b.ws-eu01.gitpod.io/
(firefox developer edition 72.0b4 (64))

**Comment by Kronifer** [comment]
can confirm isnt working, using latest chrome os and google chrome, never had problem before
