### ISSUE TITLE
Does Gitpod work for enterprise github?

### ISSUE THREAD

**Issue by jyothsnalekkala** [gitpod-io/gitpod#372]
**Describe the bug**
We have trouble parsing your context
Error: Couldn't parse context 'https://github.build.<company>.com/project/tree/develop/service'.
Please file an issue if you think this is a bug.
**To Reproduce**
Open gitpod with a enterprise github and notice the error
**Expected behavior**
When gitpod is used to open the enterprise version of github repository, it should spin up the gitpod IDE container.

**Comment by svenefftinge** [comment]
To work with your GitHub Enterprise installation, you need to have your own Gitpod installation.
Let us know if you are interested in having such an installation: info@gitpod.io
