### ISSUE TITLE
April upcoming gitpod:  cap_net_bind_service lost from docker image on restore

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#3721]
### Bug description

When an image is pulled that has `setcap cap_net_bind_service`, it works correctly on first use. Unfortunately, if the instance is stopped and then restarted, the `cap_net_bind_service` is lost. The same thing would result from a prebuild followed by launching an instance.

### Steps to reproduce

I prepared a repo to demonstrate this, https://github.com/rfay/cap-add-demo - it has a README with full instructions.

Basically:
1. In a gitpod workspace,  `docker-up` and pull a docker image that has cap_net_bind_service set (I'm sure this is any setcap)
2. Verify that the setcap is functional using getcap
3. Stop the gitpod workspace
4. Start the gitpod workspace. You'll find that the cap_net_bind_service is lost

### Expected behavior

An image should behave the same after restore or after prebuild as they do originally. Capabilities should not be lost.

### Example repository

https://github.com/rfay/cap-add-demo

**Comment by aledbf** [comment]
@rfay thank you for the report

**Comment by aledbf** [comment]
@csweichel the capabilities are not present in the generated tar file
