### ISSUE TITLE
ws manager bridge build fails with error

### ISSUE THREAD

**Issue by sri-vathsa** [gitpod-io/gitpod#3742]
### Bug description

I am trying to build the ws-manager-bridge component on the workspace created by gitpod and I am getting the error
```
mysql: [Warning] Using a password on the command line interface can be insecure.
[components/gitpod-db:dbtest-init] ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
```

### Steps to reproduce

Launch a new workspace on the gitpod repo. Cd to components/ws-manager-bridge. Run the command `leeway build .:docker` 

### Expected behavior

The build should be successful

**Comment by aledbf** [comment]
@sri-vathsa you need to start a MySQL container to build `ws-manager-bridge` (and other components).
This is not done in leeway. The build assumes a MySQL service is available on port 23306.

To start such a container, you can run:

`docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=test -e MYSQL_TCP_PORT=23306 -p 23306:23306 mysql:5.7`

with this, you will pass the tests, and the image will be ready to be uploaded to your docker account.

![build](https://user-images.githubusercontent.com/161571/120242758-aeff0000-c233-11eb-8b3a-7870d59ff44e.png)
