### ISSUE TITLE
Load Gitpod setup through URL params 

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#3746]
## Is your proposal related to a problem?

A PHP project that wants to use Gitpod, needs to create that setup, and then reload the workspace, which takes a long time.

<br>

## Describe the solution you'd like

Load the required Gitpod setup through URL params, adding `gp=<repo_url>`, for example:
`https://gitpod.io/#https://github.com/drupal/drupal&gp=https://github.com/shaal/ddev-gitpod-setup`

Gitpod will -
1. Bring all the files from https://github.com/shaal/ddev-gitpod-setup into the project,
1. Prebuild image
1. Open the project in Gitpod

<br>

## Describe alternatives you've considered

https://github.com/gitpod-io/definitely-gp seems to try solving a similar problem.
* `definitely-gp` is a more limited solution because it only includes `gitpod.yml` and `gitpod.Dockerfile`
* It allows only 1 level namespacing
* It requires submitting PR and waiting for it to be added to `definitely-gp` official repo.

<br>

## Additional context

* This feature will allow projects with complex setups like Drupal, to get contributions started with 1 click.

* This feature can be added to the other feature request, using the UI to manage these complex URLs - https://github.com/gitpod-io/gitpod/issues/3715

**Comment by rfay** [comment]
Important idea.

**Comment by geropl** [comment]
AFAIU you described a mechanism that would allow to use "template repos" with Gitpod.

We've just started working on a similar idea which would require the same "primitive": Gitpod config injection.( cmp. [design doc](https://www.notion.so/gitpod/Onboarding-Flow-bc21ce30f91c42b88bbce42ab58d17c2#32973982dca24b58b17dba5213c0828c))

The idea is to basically have a wizard to streamline the initial repository configuration, without the need to re-start. This can be easily extended to tempalte-repositories as well.

I will close this for now as we seem to have this on our roadmap already. Please re-open if you think it's not the case.

**Comment by geropl** [comment]
Ah, just found the PR: https://github.com/gitpod-io/gitpod/pull/4428

**Comment by shaal** [comment]
@geropl did you mean gitpod.io/projects 

This issue is about allowing repos use external `.gitpod.yml` + `.gitpod.Dockerfile` setup.

**Comment by endocrimes** [comment]
A way to provide external gitpod configuration and dockerfiles would be great - especially when working on larger projects where it isn't always appropriate to commit external tool configuration into the repository.

An example there would be for working on Kubernetes - I have a fork that I work in (and just set up a GitPod workspace for), and can't commit the configuration to (if I want to maintain local master == upstream master).

Currently I can provide an external gitpod.yml via settings, but can't provide a dockerfile through that interface.

Expanding support to an external gitpod config repo would be great for managing and lifecycling that configuration - Plus give me a very convenient way to share the setup with other contributors when helping folks with their first contributions upstream.

**Comment by svenefftinge** [comment]
> A PHP project that wants to use Gitpod, needs to create that setup, and then reload the workspace, which takes a long time.

I don't quite understand why the configuration needs to sit in another git repository. Can you explain a bit more?

> Currently I can provide an external gitpod.yml via settings, but can't provide a dockerfile through that interface.

Yes, Gitpod does allow to setup a project that holds a configuration (currently only the `.gitpod.yml`). We for sure should allow to author a `.gitpod.Dockerfile` there as well. Also, a current limitation might be that we require to also install the GitHub App as part of creating a project. I guess this would be a stopper for configuring larger projects like this.

**Comment by rfay** [comment]
> I don't quite understand why the configuration needs to sit in another git repository. Can you explain a bit more?

The idea is to have a launcher that has gitpod configuration, rather than being intrusive on every single project. A random project (like a web project or something) doesn't need to have gitpod config itself (which also would need to be maintained). Instead, a launcher can launch it with config specified another way. Examples are https://github.com/drud/ddev-gitpod-launcher and https://github.com/shaal/DrupalPod. As you'll note in DrupalPod, the repositories being launched in gitpod are actually temporary forks of random Drupal.org issue repos, and while those could conceivably have gitpod config forced into them, it would just make a mess.

**Comment by jcornaz** [comment]
> I don't quite understand why the configuration needs to sit in another git repository. Can you explain a bit more?

Because it cannot always be in the project repository. For example, as an open-source contributor, I may want to use gitpod, but the project I am contributing to may not want to maintain a gitpod config in their sources.

**Comment by loujaybee** [comment]
Also relates to: https://github.com/gitpod-io/gitpod/issues/8252

**Comment by ibrah3m** [comment]
it will be a better solution if we figure out some way to fork the settings(just like environment  ) from some repo made specifically for PHP that contains everything does LARAVEL projects need to get started just like the same way mentioned above.

**Comment by cart** [comment]
Sadly it looks like #4428 isn't available on the prod instance (I couldn't get it to work and looking at the code, it looks like it is explicitly disabled for `gitpod.io` urls, which is very disappointing).

`additionalcontent` would allow Bevy developers to define their own gitpod config without us needing to check it in directly to our repo, which is a concern we have over at [Bevy Engine](https://github.com/bevyengine/bevy/pull/4700). With `additionalconent` we could still provide a default config, while also letting users define their own settings.
