### ISSUE TITLE
Set timeout on Preview/Web browser

### ISSUE THREAD

**Issue by jaxxstorm** [gitpod-io/gitpod#3749]
I have a web request that can take a few minutes running inside GitPod. Unfortunately, due to the proxy timeout, I gate a gateway error.

Is there any way we can increase this value?

**Comment by akosyakov** [comment]
It looks like a duplicate of https://github.com/gitpod-io/gitpod/issues/3611

**Comment by JanKoehnlein** [comment]
#3611 is closed. Please reopen if this error persists
