### ISSUE TITLE
[Dashboard] Implement /select-account

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3754]
1. First of, ensure you have two accounts with distinct provider connections, e.g. one with GitHub and one with GitLab.
2. Log in with user A.
3. Go to Integerations, try to connect with second provider (which is connected to user B)

You end up on an empty `/select-account` page.

### Designs

| Modal | Modal (Spacing) |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/113697765-52241500-96dc-11eb-9de7-6ead8f16feb6.png)| ![image](https://user-images.githubusercontent.com/120486/113697666-2f91fc00-96dc-11eb-9535-ffe8e0bf663c.png) |

See also [design specs](https://www.figma.com/file/2VSh4dCfVPTc0YEv1Kngw9/Account-Select-3754?node-id=0%3A1).

**Comment by AlexTugarev** [comment]
@gtsiolis is this design spec still valid? https://github.com/gitpod-io/gitpod/issues/3072

**Comment by gtsiolis** [comment]
@AlexTugarev Oh, specs in #3072 are obsolete but I can add them within the next hour if needed.

To allow some head start, this page could use the following patterns:

1. A modal.
2. Two list entries, as seen in _Existing Workspaces_ specs in https://github.com/gitpod-io/gitpod/issues/3301, with all the needed accout information on each entry. 
3. Two action buttons as seen in the existing page.

**Comment by AlexTugarev** [comment]
>  I can add them within the next hour if needed.

I think this would be very helpful.

**Comment by gtsiolis** [comment]
@AlexTugarev I've added the design specs for this in the description above but wanted to provide also an alterative design that would reuse existing patterns in case this could make us implement this faster.

| Proposal A | Proposal B |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/113699537-5f420380-96de-11eb-8a24-61850ca5ade9.png) | ![image](https://user-images.githubusercontent.com/120486/113699540-60733080-96de-11eb-935d-15174ca9098c.png) |
