### ISSUE TITLE
[Dashboard] implement /sorry

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3757]
There are few redirects from server to /sorry.
E.b. https://gitpod-staging.com/sorry/#Error%20

**Comment by gtsiolis** [comment]
@jankeromnes this one can use a similar layout as the _Install_ page in https://github.com/gitpod-io/gitpod/issues/3702. 💡

**Comment by jankeromnes** [comment]
Ah, saw this too late. 😞

**Comment by jankeromnes** [comment]
Fixed by https://github.com/gitpod-io/gitpod/pull/3760
