### ISSUE TITLE
Workspace timeouts don't work

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3763]
Start a workspace and wait > 30min without touching the tab (you can also just close it after start).

Expected: Workspace stop

They don't.

**Comment by csweichel** [comment]
I cannot reproduce this on core-dev and gitpod-staging when closing the tab.
Sven, if you have an unlimited account on gitpod-staging, that would bump the default timeout to 60m.

Closing for now. Please re-open if the issue persists.
