### ISSUE TITLE
Wrong value of DB_ENCRYPTION_KEYS

### ISSUE THREAD

**Issue by dimazaur** [gitpod-io/gitpod#3766]
### Bug description

After installing self-hosted 0.8.0 from gpl/release-0.8.0
Server pod didn’t work properly and I’ve found one issue with DB_ENCRYPTION_KEYS
$ echo $DB_ENCRYPTION_KEYS
]material": “4uGh1q8y2DYryJwrVMHs0kWXJlqvHWWt/KJuNi04edI=”

Which is cutted in the wrong format from the \secrets\encryption-key.json file

### Steps to reproduce

terraform apply

**Comment by geropl** [comment]
Will have a look at this tomorrow.

**Comment by geropl** [comment]
@dimazaur Ah, this is an issue in the terraform scripts. Sadly they are known to be broken atm. :cry: 
They will get however adjusted and fixed with the next release https://github.com/gitpod-io/gitpod/issues/3893.

**Comment by geropl** [comment]
@dimazaur Ah, this is an issue in the terraform scripts. Sadly they are known to be broken atm. :cry: 
They will get however adjusted and fixed with the next release https://github.com/gitpod-io/gitpod/issues/3893.
