### ISSUE TITLE
Error: cannot find volume "vol-this-workspace" to mount into container "workspace"

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3770]
From [the logs](https://cloudlogging.app.goo.gl/JWrsXRcgUKh1G5GF7):

![image](https://user-images.githubusercontent.com/239422/113715770-2c9e0800-96ea-11eb-93e4-3f8202221b4f.png)

The workspace never launched (the error log entry is the last log entry of the pod).

Todo: find out what caused this.

**Comment by meysholdt** [comment]
We see this error since Friday on staging. [Error Report](https://console.cloud.google.com/errors/CJPtvvzG4ObBVQ?time=P30D&refresh=auto&project=gitpod-staging)

**Comment by meysholdt** [comment]
[this seems to be the cause](https://console.cloud.google.com/logs/query;query=%220bffb1d2-0a19-4cab-9edf-46740e8bc69f%22%0Atimestamp%3D%222021-04-06T11:25:05Z%22%0AinsertId%3D%221jsar4vg3zjq7vm%22;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning;timeRange=PT24H?project=gitpod-staging)

![image](https://user-images.githubusercontent.com/239422/113717651-1e50eb80-96ec-11eb-8b77-d23ca3405a4b.png)

**Comment by meysholdt** [comment]
While "cannot initialise workspace" is not a new thing, it's need that the pod now fails with the "cannot find volume" error.

**Comment by svenefftinge** [comment]
I always seems to be the probe user
