### ISSUE TITLE
Update Logo / brand

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3771]
We need to update the logo on the following places:

 - [x] 1. GitHub Org (https://github.com/gitpod-io)
 - [x] 2. Community Forum (https://community.gitpod.io/)
 - [x] 3. Twitter (https://twitter.com/gitpod)
 - [x] 4. YouTube (https://www.youtube.com/channel/UCK9Zf-orAitifVR6-e6lNSg)
 - [x] 5. GitHub App (https://github.com/apps/gitpod-io)
 - [x] 6. GitHub OAuth App (https://github.com/marketplace/gitpod-oauth/)
 - [x] 7. Chargebee
 - [x] 8. shields.io / simpleicons.org (https://github.com/simple-icons/simple-icons/pull/5425)
 - [x] 9. Welcome email after first-time OAuth signup
 - [x] 10. LinkedIn company profile
 - [x] 11. Chrome Marketplace (https://chrome.google.com/webstore/detail/gitpod-dev-environments-i/dodmmooeoklaejobgleioelladacbeki?hl=en)
 - [x] 12. Firefox Marketplace (https://addons.mozilla.org/en-US/firefox/addon/gitpod/)
 - [x] 13. KubeCon Sponsorship (WIP: they have been contacted)
 - [x] 14. CNCF Membership (https://www.cncf.io/about/members/) (WIP: they have been contacted)
 - [x] 15. Crunchbase (https://www.crunchbase.com/organization/gitpod)
 - [x] 16. all Sendgrid emails e.g. private trial, including #9 welcome email
 - [x] 17. Angellist (https://angel.co/company/gitpod)
 - [x] 18. professional open-source (https://github.com/orgs/gitpod-io/teams/professional-open-source/edit)
 - [x] 19. Product Hunt (https://www.producthunt.com/posts/gitpod)
 - [x] 20. Eclipse CloudDEvTools Adopters (https://ecdtools.eclipse.org/adopters/)

(please add)

see also https://www.notion.so/gitpod/8ad7efdacbe341ac968c6b7959bc4230?v=11a0e56a71944230b46448be7eb6fb35

**Comment by gtsiolis** [comment]
Picking up 2. Community Forum.

**Comment by tnir** [comment]
Per `2`, it still looks an older icon to me...
```html
<link rel="icon" type="image/png" href="https://community.gitpod.io/uploads/default/optimized/1X/d204b03ffa1b54c6fef01fdb9dc99021f82cc4bf_2_32x32.png">
```
(while `apple-touch-icon` is updated as follows!)
```html
<link rel="apple-touch-icon" type="image/png" href="https://community.gitpod.io/uploads/default/optimized/2X/4/4cfe88cf2b5a748b624fca9f50b781c5cc018d29_2_180x180.png">
```
Weird...

**Comment by gtsiolis** [comment]
Hey @tnir, it should look ok now, right? Thanks! 🧡

**Comment by filiptronicek** [comment]
@svenefftinge does any of these include the dashboard? 

As per my note on the new design (https://github.com/gitpod-io/gitpod/issues/3727#issuecomment-814790669), there are some places that still have the old design, like the billing modal.

**Comment by gtsiolis** [comment]
@filiptronicek yes, see https://github.com/gitpod-io/gitpod/issues/3727#issuecomment-814797733. 🏓

**Comment by filiptronicek** [comment]
@svenefftinge https://www.producthunt.com/posts/gitpod 👀

**Comment by gtsiolis** [comment]
Reminder to use images double in size when possible to avoid blurry images on high density displays (see [example](https://addons.mozilla.org/en-US/firefox/addon/gitpod/)). /cc @ChristinFrohne

**Comment by ChristinFrohne** [comment]
True, but unfortunately Firefox scales down all images automatically. When you search for other extensions, you can see that all images a bit blurry

**Comment by jankeromnes** [comment]
Nit: The new Firefox extension icon is super blurry:

<img width="855" alt="Screenshot 2021-04-09 at 13 32 10" src="https://user-images.githubusercontent.com/599268/114173835-11283c80-9938-11eb-979b-d7e6cd71013e.png">

https://addons.mozilla.org/firefox/addon/gitpod/

Reminder: Please use SVGs everywhere, or at least very high-definition PNGs 🙏

**Comment by ChristinFrohne** [comment]
@jankeromnes see my comment above
>unfortunately Firefox scales down all images automatically. When you search for other extensions, you can see that all images are a bit blurry

**Comment by tnir** [comment]
https://github.com/gitpod-io/gitpod/issues/3771#issuecomment-814677090

@gtsiolis After hours, it worked! Thanks.

**Comment by gtsiolis** [comment]
Crossed of _Shields.io_. Thanks @jankeromnes for taking care of this in https://github.com/simple-icons/simple-icons/pull/5425! 🛡️

**Comment by adamrusted** [comment]
Hey gang - one of the maintainers of https://github.com/simple-icons/simple-icons here!
We've had another request come in for an update, saying that the hex code provided by @jankeromnes was incorrect, and we should instead use the darker orange. See https://github.com/simple-icons/simple-icons/pull/5464 for my response, suggesting we use the calculated midpoint of the two hex codes as our colour for simple-icons. Would that be okay with you all?

**Comment by filiptronicek** [comment]
Can we please add Docker to the list?
![image](https://user-images.githubusercontent.com/29888641/131379049-46a0f416-61a6-4756-838b-18a270322a93.png)

/cc @gtsiolis

**Comment by gtsiolis** [comment]
Thanks for noticing @filiptronicek! 🐳 

Cross-checked [13], see https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/.

Cross-checked [14].

Cc @jankeromnes because of a [relevant discussion](https://gitpod.slack.com/archives/C01LDA27WJC/p1626765401029000) (internal).

Once [20] is resolved we can close this issue. Cc @ChristinFrohne @JohannesLandgraf

**Comment by gtsiolis** [comment]
Anything we could do to resolve the last outstanding task here and close this issue?

>  20. Eclipse CloudDEvTools Adopters (https://ecdtools.eclipse.org/adopters/)

Cc @ChristinFrohne @JanKoehnlein

Cc @JanKoehnlein as your are assigned here. 🏓

**Comment by ghuntley** [comment]
See also [DCS > Brand Registry](https://www.notion.so/gitpod/8ad7efdacbe341ac968c6b7959bc4230?v=11a0e56a71944230b46448be7eb6fb35) (Internal Link) which is the source of truth.

**Comment by JanKoehnlein** [comment]
I created a [PR](https://github.com/EclipseFdn/eclipsefdn-project-adopters/pull/153) agains the ecdtools repo, but it's currently blocked by the CLA process (my GitHub account is still tied to my Eclipse account with the TypeFox email address, and I cannot just edit that). I contacted Eclipse for steps to go ahead.

**Comment by gtsiolis** [comment]
Thanks @JanKoehnlein @ghuntley!
