### ISSUE TITLE
[Admin] Searching for workspaces doesn't work

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3778]
### Bug description

When searching for a workspace in the admin panel, it doesn't work.

<img width="1440" alt="Screenshot 2021-04-06 at 17 24 09" src="https://user-images.githubusercontent.com/599268/113735892-f1f19b00-96fc-11eb-863b-b408545b19ed.png">

### Steps to reproduce

- Try to search for a workspace by contextURL (e.g. search for "svelte")
- Or, try to search for a workspace by ID (e.g. "plum")

Console says:

```
Uncaught (in promise) Error: TypeError: Cannot read property 'id' of undefined
```

### Expected behavior

It should work

**Comment by JanKoehnlein** [comment]
Cannot reproduce. Other issue with workspace search persists #3992
