### ISSUE TITLE
Failing to build android source code 

### ISSUE THREAD

**Issue by dongfangxunlei** [gitpod-io/gitpod#378]
**Describe the bug**
```
gitpod@ws-e709fdf0-8a02-41ec-bffb-fe7126a76129:/workspace/aosp$ make aapt
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=mini_emulator_x86_64
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=x86_64
TARGET_ARCH_VARIANT=x86_64
TARGET_2ND_ARCH=x86
TARGET_2ND_ARCH_VARIANT=x86_64
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-1026-gcp-x86_64-Ubuntu-18.04.2-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ1A.190105.004
OUT_DIR=out
============================================
[1/1] out/soong/.minibootstrap/minibp out/soong/.bootstrap/build.ninja
[55/56] glob prebuilts/ndk/cpufeatures.bp
[77/77] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -o out/soong/build.ninja Android.bp
Killed
ninja: build stopped: subcommand failed.
09:26:24 soong bootstrap failed with: exit status 1

#### failed to build some targets (44 seconds) ####
```

**Comment by jankeromnes** [comment]
Hi @dongfangxunlei! Thank you for reporting this problem.

It seems that your `ninja` process is getting killed. That's probably because it tries to use too much RAM: we currently allow ~3.5GB RAM per workspace, so the Linux OOM-killer will kill any process that makes your workspace use more than that.

In order to user less RAM, could you please try building with fewer processes? E.g. with:

```
$ make -j2 aapt
```

**Comment by dongfangxunlei** [comment]
@jankeromnes 
I try also -j1 and the same result. I just see  the total memory is 57G and not aware of the 3.5G limitation. 
I also notice the total disk size is above 300G, does this have extra limitation also?

**Comment by jankeromnes** [comment]
@dongfangxunlei Thank you for also trying with `-j1`, and I'm very sorry that it still didn't work.

The 57GB you see is all the RAM on the server (same for the ~300GB disk size), but Gitpod uses Kubernetes and Docker to run multiple workspaces per server.

However, having a 3.5GB RAM hard limit per workspace doesn't make sense, and currently prevents several projects from building on Gitpod, e.g. Chromium, Firefox, Servo, Rust, and now AOSP (thank you for telling us!) There is no such hard limit on disk space.

I believe I've found a way to increase the RAM usable by each workspace, and I'd like to fix this problem soon, but it could take one or two months before the solution is deployed.

**Comment by dongfangxunlei** [comment]
Fixed.

**Comment by android-yanwen** [comment]
@dongfangxunlei hi, I have the same problem, how can you solve it?

**Comment by jankeromnes** [comment]
@android-yanwen are you unable to build something due to an Out Of Memory? (OOM-kill) Have you tried `-j1` as suggested above?

FYI Gitpod's workspace RAM hard limit was since increased to over 8GB, which should be enough for most builds. However, we can probably raise it further if needed.

**Comment by android-yanwen** [comment]
[  0% 0/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
    3:34 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
    7:52 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
    9:53 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
   11:54 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
   13:55 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
   15:56 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
   17:57 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
   18:23 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
   32:14 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
   91:15 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
   106:58 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
   108:59 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
[100% 1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
Killed
15:56:01 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.

#### failed to build some targets (02:13:59 (hh:mm:ss)) ####

hi, this my get wrong, I try -j2 and the same result, total disk size is 150G, 4GB RAM. Do I need to expand RAM to 8GB?

**Comment by michele13** [comment]
> [ 0% 0/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 3:34 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 7:52 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 9:53 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 11:54 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 13:55 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 15:56 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 17:57 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 18:23 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 32:14 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 91:15 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 106:58 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> 108:59 out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> [100% 1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
> FAILED: out/soong/build.ninja
> out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
> Killed
> 15:56:01 soong bootstrap failed with: exit status 1
> ninja: build stopped: subcommand failed.
> #### failed to build some targets (02:13:59 (hh:mm:ss))
> 
> hi, this my get wrong, I try -j2 and the same result, total disk size is 150G, 4GB RAM. Do I need to expand RAM to 8GB?

I also have the same problem. How can we solve it?

**Comment by jankeromnes** [comment]
Hi @android-yanwen and @michele13, when you see `Killed` in the build log, most of the time it does mean that you've been using too much RAM, and thus the Linux OOM-killer wakes up and kills your process that's using the most RAM (i.e. the compiler or linker).

You can try a combination of these options to work around this problem:
- Try to build with fewer processes (e.g.  with`-j1`). This will take longer, but will use less RAM.
- Try a build that uses less RAM, e.g. by disabling debug symbols.
- Increase the available RAM. On Gitpod, you're currently allowed to use up to 8.9 GB before the OOM-killer comes online (we could raise this limit again, but we believe that 8.9 GB RAM is sufficient for most builds already).
- If a build gets killed, you can simply retry it several times. With a little luck, already-compiled objects will be kept, and only new objects will be compiled.

For example, with the current 8.9 GB RAM limit on Gitpod, I'm able to compile Servo in `debug` mode, but it usually gets killed once, and when I retry it once it then finishes successfully. I'm also able to compile Servo in `release` mode, without any OOM-kills (it's also faster and uses less disk space).

Hope this helps! Please let me know if you're still stuck after trying these things.

**Comment by fartsren123** [comment]
Hello , 
      I encountered the same issue today , but can this be solved using SWAP?
