### ISSUE TITLE
[Code] The workbench failed to connect to the server (Error: TIMEOUT)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3782]
### Bug description

I was running some CPU-intensive workload in gitpod-staging, using:
- Repository: https://gitlab.com/gitpod/spring-petclinic
- IDE: VS Code
- Layout: two split Terminals

when suddenly my browser said VS Code was no longer able to connect and that I needed to reload.

<img width="1440" alt="Screenshot 2021-04-06 at 18 18 22" src="https://user-images.githubusercontent.com/599268/113744661-31bc8080-9705-11eb-90c7-9c92cdf6683e.png">

I first clicked "Cancel", then when nothing worked, I refreshed my browser.

Then this error showed up:

> An unexpected error occurred that requires a reload of this page.
> The workbench failed to connect to the server (Error: TIMEOUT)
> [Reload]

<img width="1440" alt="Screenshot 2021-04-06 at 18 18 44" src="https://user-images.githubusercontent.com/599268/113744714-3e40d900-9705-11eb-825e-156a5e202b9f.png">

It now shows up every time, no matter how many times I reload.

### Steps to reproduce

- Try to run [this manual test](https://github.com/gitpod-com/gitpod/blob/614f7b9dfe6eac45a8ee9f2c18e8a10432b57351/devops/manual-tests/testsuite.yaml#L44-L54)
- Have the `cpuburn` and the `watch` in side-by-side split terminals
- After a minute or so, the first error shows up
- Every time you reload, you see the second error

**Comment by jankeromnes** [comment]
Workspace ID, FYI: `indigo-parrot-roq6u35m`

**Comment by akosyakov** [comment]
maybe related to https://github.com/gitpod-io/gitpod/issues/3797

**Comment by akosyakov** [comment]
Please next time when it happens collect data from browser devtools and share them here.

**Comment by akosyakov** [comment]
I was able to reproduce it by switching to 3G network profile on system level.

**Comment by akosyakov** [comment]
fixed by https://github.com/gitpod-io/gitpod/pull/4404
