### ISSUE TITLE
[terminal] Sometimes on workspace restarts all terminals are gone

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#379]
**Describe the bug**
Sometimes after workspace restart all terminals are gone.

**To Reproduce**
 1. start workspace
 2. stop from workspace, but leave workspace tab open
 3. in the still-open tab, click "Restart"

**Expected behavior**
The workspace should re-open all terminals in the same window location as before.

**Comment by akosyakov** [comment]
Root cause: https://github.com/theia-ide/theia/issues/2480#issuecomment-414111855?

**Comment by geropl** [comment]
Outdated
