### ISSUE TITLE
Error: Not connected to message bus

### ISSUE THREAD

**Issue by tars003** [gitpod-io/gitpod#3790]
### Bug description

Every workspace I click on gives me this error 
Oh, no! Something went wrong!
Error: Not connected to message bus

### Steps to reproduce

It was all working before but now I am not able to enter any of my workspace so I don't exactly know how to reproduce this error for any other account than mine.

### Expected behavior

I should be able to login to my workspace

#1110
![image](https://user-images.githubusercontent.com/48816808/113811705-5444ad00-978a-11eb-9a9d-fabbef7acb07.png)

**Comment by mukeshgurpude** [comment]
> ### Steps to reproduce
> It was all working before but now I am not able to enter any of my workspace so I don't exactly know how to reproduce this error for any other account than mine.

Navigate to [gitpod workspace](https://gitpod.io/workspaces/) and start a new workspace using `new workspace` button.

For each and every new workspace it's showing the error.

> Previously created workspaces are opening normally, issue is only with the new workspaces.

**Comment by gtsiolis** [comment]
Hey @tars003! This should be resolved by now. Thanks for reporting! 💯
