### ISSUE TITLE
cannot change permissions for read:user

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#3796]
### Bug description

It breaks `GitHub Pull Requests and Issues` extension.

### Steps to reproduce

See below.

<img width="622" alt="Screenshot 2021-04-07 at 09 17 14" src="https://user-images.githubusercontent.com/3082655/113826632-b00b3800-9782-11eb-9c9b-49a10c236744.png">

**Comment by AlexTugarev** [comment]
This [change](https://github.com/gitpod-io/gitpod/pull/3349/files#diff-592960f05595536410ca31510d5f9732cf2c643173957760643873ea766736deR22) basically breaks the GitHub PR extension for Gitpod sessions being active during the deployment. The meaning of `DEFAULT` scope requirements in this context is that a user need those to sign in, thus cannot change afterwards.

There is no issues for new sessions, i.e. a re-login would be a workaround to allow this.

**Comment by akosyakov** [comment]
fixed by https://github.com/gitpod-io/gitpod/pull/3798
