### ISSUE TITLE
[supervisor/cli] git scope elevation dialog opens wrong link

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#3799]
### Bug description

When performing a git operation with insufficient token scope the dialog says to "Open Access Control" and opens `gp_host/access-control` which redirects to integrations. 

### Steps to reproduce

Perform a git operation with insufficient privileges.

### Expected behavior

We should rather open `gp_host/integrations` with a parameter opening the correct provider config modal.

### Example repository

any

**Comment by AlexTugarev** [comment]
The endpoint should be `api/authorize`. Additional params are needed.
* `host`
* `scopes` to be added
* `returnTo` ideally a success page for the user to communicate, that the operation was successful

> ... opening the correct provider config modal.

I'm not sure if we want to reimplement the buggy form automation for that single use case.

**Comment by JanKoehnlein** [comment]
OK, so my initial assumption was wrong. But we should spec that out:
- I like the indirection to the the access control page because it makes it explicit that the user gives permissions to Gitpod, and makes it clear where they can revoke it later. For sure it should redirect to something more specific, i.e. the modal, or give instructions how to proceed.
- If we follow @AlexTugarev's approach, what page do we redirect to after authentication?
- Do we really want to extend the open external protocol of VS Code?

**Comment by AlexTugarev** [comment]
On the first point: it makes sense to use a pattern in similar cases. Consider the creation of new workspace, where you might be logged in with one provider, but now trying to start a workspace for a second provider. There you get asked to authorize for the second provider. After completion of the authorization you may proceed, or work yourself through the error modes. 

Now if you are within the code editor, and you see the (already existing) permission dialog, which asks you to authorize for more permissions (or additional providers,) why would you need to add more traffic signs? The goal is clear. 

> what page do we redirect to after authentication?

Very good question! In the dashboard space we're able to interact with this landing page, i.e. we can close it, but also read the success/error result. I was hoping, we'd be able to do similar for the code editor 😞
