### ISSUE TITLE
Gitpod works really well in Firefox; please remove the "runs best on Chrome" message

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#38]
Hello,

I'm really impressed with Gitpod, and it works extremely well in Firefox. :smile: :+1:

So please remove the "Gitpod runs best on Chrome" message and the "DOWNLOAD CHROME" button.

![runs-best-in-chrome](https://user-images.githubusercontent.com/599268/44874234-c97aa800-ac9a-11e8-883e-3038824e8aff.png)

Thanks! :heart:

**Comment by jankeromnes** [comment]
Thanks a lot! :+1:

I'd be curious to know what these minor issues with Firefox were? (Maybe we can file bugs and get them fixed.)

Also, maybe users should report browser issues regardless if they use Chrome/Firefox or another one? What about something more generic like: `Please report any browser issues [here](link).`? (Drawback: it doesn't encourage users to try a different browser.)

**Comment by svenefftinge** [comment]
We leave the second message out as we have the pointer to reporting issues in the help menu.

**Comment by svenefftinge** [comment]
> I'd be curious to know what these minor issues with Firefox were? (Maybe we can file bugs and get them fixed.)

We are working on a compatibility page for the docs, listing any known short-comings.
