### ISSUE TITLE
Git hub not clone with gitpod

### ISSUE THREAD

**Issue by Ranjith2503** [gitpod-io/gitpod#380]
**Describe the bug**
I login GitHub to register in Gitpod but it shows like a bug it cannot able to open

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Comment by geropl** [comment]
Hi @Ranjith2503, thanks for reporting your issue.

I tried to reproduce with a fresh GitHub user and it worked for me. Could explain in what step exactly it fails? Maybe also you browser (+ version)?

**Comment by svenefftinge** [comment]
please reopen or comment.
