### ISSUE TITLE
Self-Hosted Update Frequency

### ISSUE THREAD

**Issue by jrdzha** [gitpod-io/gitpod#3804]
The self-hosted version of gitpod doesn't seem to get very much attention. When can we expect the release of 0.8.0? Is there any way the self-hosted can also use the same rolling deployment as gitpod.io?

**Comment by geropl** [comment]
Hi @jrdzha ,

> The self-hosted version of gitpod doesn't seem to get very much attention

sadly this is true. We're currently focusing on gitpod.io as we're still growing and not enough people (yet) to support self-hosted to that extend that we'd love to.

> When can we expect the release of 0.8.0?

Just wanted to answer "it's already released", but it is not, actually. :confused: There is, however:
 - a GitHub release of the RC2: this was meant to be released: https://github.com/gitpod-io/gitpod/releases/tag/v0.8.0-rc2
 - [a branch](https://github.com/gitpod-io/gitpod/tree/gpl/release-0.8.0) that contains the doc changes (just version bumps and deprecation of installer images)
 
 I will review and release the images tomorrow (effectively relabeling them from `0.8.0-rc2` to `0.8.0`, so you can start playing around right away).

**Comment by jrdzha** [comment]
@geropl Thanks for the update, glad to hear that the self-hosted should be 1-1.5 weeks behind SaaS.

For us, we need to self host because our setup requires large volumes of data moving between pods in a Kubernetes cluster, so the hosted gitpod.io doesn't work very well for us, with data going across WAN.

The intermittent release cycle of the self-hosted (and some other minor self-hosted kinks like Ubuntu dependency for preview experimental features, etc) is the only thing giving me pause when choosing gitpod over eclipse che, so if this is resolved, I'm a happy camper.

**Comment by jrdzha** [comment]
Don't mean to be pushy, but any updates here? Thanks!

**Comment by geropl** [comment]
@jrdzha Here's the release: https://github.com/gitpod-io/gitpod/releases/tag/v0.8.0

Issue regarding 0.9.0: https://github.com/gitpod-io/gitpod/issues/3893
 
Closing this for now; please re-open if more questions arise.

**Comment by jrdzha** [comment]
Thanks for this release. I am trying this out now, but ran into a couple issues:

1. Unable to pull "theia-server" image `Failed to pull image "gcr.io/gitpod-io/self-hosted/theia-server:0.8.0"`
2. Proxy and Blobserve successfully pull, but fail to start

I'm having the same issues with 0.9.0-alpha1.

**Comment by geropl** [comment]
> Unable to pull "theia-server"

That component has been removed in the meantime. This almost certainly happens when you use an older version of the chart with a new "version" string. Could that be the case?

**Comment by jrdzha** [comment]
I see, yes I was updating from an existing install of self-hosted 0.6.0. I will try this from scratch now.

As an aside, doesn't having to reinstall from scratch for updates force us to re-setup our github / gitlab credentials each time?

**Comment by jrdzha** [comment]
I can confirm that 0.8.0 is working for me with a clean install, however 0.9.0-alpha1 is not.

Here are my issues with 0.9.0-alpha1:

- messagebus error: `Failed to pull image "gcr.io/gitpod-io/self-hosted/messagebus:0.9.0-alpha1"`
- mysql error: `Failed to apply default image tag "map[tag:5.7]:5.7.30": couldn't parse image reference "map[tag:5.7]:5.7.30": invalid reference format`
- serve pod doesn't start successfully, but there are no kubernetes logs as to why this is.

**Comment by jrdzha** [comment]
@enriquecaballero I am using RHEL in an AWS kubernetes cluster. I haven't tried gitpod in K3OS.

**Comment by geropl** [comment]
0.10.0 should finally get us back to speed/in-line with the gitpod.io deployment: https://github.com/gitpod-io/gitpod/issues/4710
