### ISSUE TITLE
New Release: VSCode can't auth Github and Theia's Typescript support seems broken

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#3805]
### Bug description

Was a bit of a shock today that in the middle of the business day (around 12 noon in the Asia/Bangkok time) Gitpod released a major breaking change with no notification. :(

Trying out VSCode, most of the team couldn't authenticate against Github because we couldn't grant the "user:read" permission which is disabled in the dashboard.

So we tried switching back to Theia, but Typescript support (auto completion, etc) are broken now. A few of us have been able to keep old pre-new-release workspaces open -- everything still works in them with Theia.

This feels like a very rushed release without enough testing. 

### Steps to reproduce

Open any repo

**Comment by akosyakov** [comment]
> Trying out VSCode, most of the team couldn't authenticate against Github because we couldn't grant the "user:read" permission which is disabled in the dashboard.

We fixed it and will deploy within the week I believe. For now re-login and you will be able to grant missing permission.

> So we tried switching back to Theia, but Typescript support (auto completion, etc) are broken now.

Nothing was changed for Theia. It sounds strange. Could you share the repo to reproduce? By switching I assume you toggle IDE in settings? It should be available for some time before we completely switch to VS Code.

**Comment by akosyakov** [comment]
I was able to reproduce typescript smartness issues: https://github.com/gitpod-io/gitpod/issues/3808

**Comment by akosyakov** [comment]
an issue for disabled permission: https://github.com/gitpod-io/gitpod/issues/3796

**Comment by smacintyre** [comment]
@akosyakov Cool. Thank you for your response!

**Comment by akosyakov** [comment]
Everything was fixed, we are planning to deploy fixes tomorrow morning.
