### ISSUE TITLE
[dashboard] Dark theme

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3806]
### Problem to solve

We've implemented the first iteration of the new dashboard design but shipped only with a light theme as an MVC (Minimum Viable Change) in the previous milestone.

### Proposal

> Dark Theme for Dashboard

See [relevant roadmap item](https://www.notion.so/gitpod/Product-Roadmap-b9b5eac0a15147ac8d2dd25cf0519203#4c5bd5c57957477590e840e00c976f5b).

~~Note that we've already shipped a Light and Dark theme for the VS Code editor.~~ The scope of this issue is limited to a) adding the dark theme to the dashboard and b) including a user preference switch to toggle between themes.

**Comment by filiptronicek** [comment]
Is there a dark color palette for the new branding or is there none yet? Some really nice colors can be paired with the new orange.

I made a quick preview with a color that doesn't look that bad, but I didn't take my time with the colors much (like the input fields, etc.)
![image](https://user-images.githubusercontent.com/29888641/113854546-43526680-979f-11eb-97a0-a7744edb16ee.png)

/cc @gtsiolis

**Comment by gtsiolis** [comment]
Thanks @filiptronicek! Yes, a first draft is already in place but we won't get started with this before the week or so. Here's an early draft design for this. 🙈 

<img width="1440" alt="Workspaces (Dark)" src="https://user-images.githubusercontent.com/120486/113855369-9d0b5e80-97a8-11eb-860b-ccec56137eb8.png">

**Comment by filiptronicek** [comment]
A comment on the preference toggle, I really love the Vercel one, it could be a nice inspiration 👀 

It has very cool icons and instantly changes the theme for the user, which I really like. 
![image](https://user-images.githubusercontent.com/29888641/113855773-b4dee480-97a0-11eb-8512-3252d1f83ade.png)
![image](https://user-images.githubusercontent.com/29888641/113855902-db9d1b00-97a0-11eb-8adc-4af710de63f4.png)

**Comment by filiptronicek** [comment]
@gtsiolis wow, cool! Very excited about this!
