### ISSUE TITLE
https://shounanssasaki.github.io/shounamssasaki/

### ISSUE THREAD

**Issue by shounanssasaki** [gitpod-io/gitpod#381]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Comment by jankeromnes** [comment]
Thanks for opening this issue! This doesn't look like a bug report or feature request, so I'll close it.

FYI opening your repository in Gitpod seems to work great:

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/shounanssasaki/shounamssasaki/)
