### ISSUE TITLE
[dashboard] Sometimes, the "Stopped / Timed Out" screen shows "Starting / Opening IDE ..." instead

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3811]
### Bug description

Sometimes, the "Stopped / Timed Out" screen shows "Starting / Opening IDE ..." instead.

<table><tr><td>
<img width="1440" alt="Screenshot 2021-04-07 at 14 23 21" src="https://user-images.githubusercontent.com/599268/113866173-494f4400-97ad-11eb-8e5c-a8f0d90cfbc3.png">
</td><td>
<img width="1440" alt="Screenshot 2021-04-07 at 14 26 32" src="https://user-images.githubusercontent.com/599268/113866179-4b190780-97ad-11eb-8b4f-2ceb4808c340.png">
</td></tr></table>

### Steps to reproduce

- Open a workspace to do some work in it
- Close laptop & go for lunch
- Come back to the timed out workspace -- it says "Starting" and "Opening IDE ..."

### Expected behavior

It should show "Stopped" or "Timed Out"

**Comment by jankeromnes** [comment]
Sometimes it works as expected, e.g. if my browser & laptop remain open while it times out:

<img width="1439" alt="Screenshot 2021-04-08 at 09 55 49" src="https://user-images.githubusercontent.com/599268/113989399-b23bc800-9850-11eb-947e-175d3ab19610.png">

Maybe it's a matter of the Start page not receiving updates while the browser/laptop is asleep, and then not updating itself properly when woken up after the workspace timed out.

**Comment by AlexTugarev** [comment]
> Maybe it's a matter of the Start page not receiving updates while the browser/laptop is asleep, and then not updating itself properly when woken up after the workspace timed out.

That's a known behavior, @jankeromnes. That also may happen on connection loss. That's where we used to add the `notifyDidOpenConnection` listener to fetch latest details on the instance. I think that's missing. In old code we used to have a `ensureWorkspaceInfo`.

BTW, that would also explain why I don't see the "workspace stopped" but the "workspace stopping" from time to time.

**Comment by jankeromnes** [comment]
Will add back the missing listener for that case.

> BTW, that would also explain why I don't see the "workspace stopped" but the "workspace stopping" from time to time.

What do you mean? I do see "Stopped" when I:
- Start a workspace
- Open https://gitpod.io/workspaces in new tab, and click on "Stop" next to the workspace
- Head back to original workspace tab

There I see "Stopping" (as expected) and after a while "Stopped" (as expected).

**Comment by AlexTugarev** [comment]
@jankeromnes, on https://github.com/gitpod-io/gitpod/issues/3811#issuecomment-815604228

Try this
* hit "Stop" and immediately disable network connection on your notebook
* reconnect the network after a while and check the state
