### ISSUE TITLE
Vim Extension no longer working in Theia

### ISSUE THREAD

**Issue by jabuwu** [gitpod-io/gitpod#3815]
### Bug description

With the most recent Gitpod rollout, the vscodevim.vim extension no longer works. Certain Vim command palette options are still working, but none of the editing features work anymore.

### Steps to reproduce

Install the Vim extension from the extensions panel. Vim mode should be enabled by default but it can also be toggled in the command palette ("Vim: Toggle Vim Mode").

### Example repository

I've tried several repos, old and new, and the problem persists.

Theia is to be deprecated (#3475), but with #3259 open, there is no way to use Vim.

I have tried reinstalling the extension, deleting .vimrc, clearing settings.json, and running "Toggle Vim Mode" in the command palette, but no luck.

Perhaps its related to https://github.com/gitpod-io/gitpod/issues/3775#issuecomment-814824907 ?

**Comment by akosyakov** [comment]
fixed by https://github.com/gitpod-io/gitpod/pull/3810 shoudl be released tomorrow morning
