### ISSUE TITLE
[proxy] Make sure we do not (long-term) cache error responses

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3818]
We recently introduced long-term caching for [static assets](https://github.com/gitpod-io/gitpod/blob/e56ed09ccb99dccd27507c3559ca64a49e857786/chart/config/proxy/lib.locations.conf#L25-L32).

While atm we have only a handful of resources under `/static` we should make sure that we do not accidently cache errors like 404s in the future, for instance by using a pattern like this: https://serverfault.com/a/690258

**Comment by geropl** [comment]
@aledbf  I'm not 100% sure it's fixed by #3922. What's the default behavior for caddy on error cases?

**Comment by akosyakov** [comment]
It is still valid, we should apply https://caddy.community/t/correct-way-to-set-expires-on-caddy-2/7914/13?
