### ISSUE TITLE
With VScode enabled: `exec: "code": executable file not found in $PATH` when trying to open files

### ISSUE THREAD

**Issue by NealKaviratna** [gitpod-io/gitpod#3821]
### Bug description

unable to use `gp open` to open files, fails with

```
exec: "code": executable file not found in $PATH
```

### Steps to reproduce

# Open gitpod environment
# Attempt to open file with `gp open`
# Observe

### Expected behavior

file open in code editor successfully

**Comment by akosyakov** [comment]
Could you clarify please do you use VS Code and for which repo?

**Comment by akosyakov** [comment]
Probably the same as https://community.gitpod.io/t/gp-open-does-not-work-in-vs-code-ui/3172/2

**Comment by NealKaviratna** [comment]
Yeah, switched to VS code with the recent update. Unfortunately this was with a private repo that I can't share.

**Comment by NealKaviratna** [comment]
closing as dupe / fixed by #3846
