### ISSUE TITLE
Autocompletion is not working in workspace

### ISSUE THREAD

**Issue by marcogonzalo** [gitpod-io/gitpod#3826]
### Bug description

Before changes when you write, for example, a HTML Tag, Gitpod used to suggest different options to complete it. After new UI change, it is apparently missing.

### Steps to reproduce

Create a new HTML document and try to write <html> or <document> tag.

### Expected behavior

Gitpod should show a list with options to complete what you are writing.

**Comment by jankeromnes** [comment]
Hi @marcogonzalo, thanks for this report!

This is likely due to VS Code having fewer pre-installed extensions than Theia.

To get autocompletion to work again,

**Comment by alesanchezr** [comment]
Wow this seems like a big change, a lot of hard work, hugh? Congratulations!

I guess at 4Geeks we would want to have pre-installed components now for the entire organization to avoid this.

Most of our users are learning to code so we need some of those plugins already on.

**Comment by akosyakov** [comment]
> Most of our users are learning to code so we need some of those plugins already on.

Such extensions should be specified then in .gitpod.yml. Having all extensions turned out to have bad side effects in Theia, like you want to program in go, but getting python notifications for some reason. In VS Code we decided against bloating the IDE but align with the desktop experience. Users need to explicitly extensions which they want to have for the project instead of relying on the magic.

In which language you are interested? I can help you with compiling initial set of extensions.

**Comment by alesanchezr** [comment]
Ok I understand, we are working with python and javascript/html/css/react I will research on what are the best extensions for autocompletion

**Comment by akosyakov** [comment]
For `javascript/html/css/react` VS Code actually has good built-in extensions, for python: https://github.com/gitpod-io/python-flask-example/blob/215eb6a3855bb2deaad0b12c93a107dcb1d0c9e8/.gitpod.yml#L15-L17

**Comment by akosyakov** [comment]
@marcogonzalo How can I reproduce missing HTML tags? Could you try again? We realized several critical fixes to VS Code end of last week. Most likely everything is fine already.

**Comment by akosyakov** [comment]
I cannot reproduce, please reopen if it still happens:
<img width="708" alt="Screenshot 2021-04-13 at 09 54 35" src="https://user-images.githubusercontent.com/3082655/114517081-45547380-9c3e-11eb-8bed-f439808940ef.png">
