### ISSUE TITLE
StandardJS plugin doesnt work (In theia)

### ISSUE THREAD

**Issue by u9g** [gitpod-io/gitpod#3828]
### Bug description

When installing StandardJS, it doesn't lint and the fix on save option does nothing.

### Steps to reproduce

1. install StandardJS plugin
2. watch as the js code isnt linted

### Expected behavior

It should lint code and fix on save (if the option is enabled in settings)

### Example repository

```js
function orange () {
  apple()
  
}
```
should be linted to:
```js
function orange () {
  apple()
}
```
due to the rule: `Block must not be padded by blank lines. (padded-blocks)standard(padded-blocks)`

**Comment by akosyakov** [comment]
The fix was deployed in the morning, please try again.
