### ISSUE TITLE
[Responsiveness] What's New popup is not responsive

### ISSUE THREAD

**Issue by kevinadhiguna** [gitpod-io/gitpod#3829]
### Bug description

I saw a `What's new` popup but was not able to scroll it to click the `Continue` button. As a result, I resized the browser to 90% then clicked the `Continue` button. At the time the browser size was 90%, the height was 100vh I guess, so I was not required to scroll down.

![bug-gitpod_1](https://user-images.githubusercontent.com/43397636/113957662-d942cb80-9849-11eb-9637-eb964af5a269.png)

### Steps to reproduce

1. Open https://gitpod.io
2. Login with Github (Connect to Github)
3. Authorize gitpod
4. See a `What's new` popup
5. Unable to click the `Continue` button unless I resize the browser to at least 90%.

![bug-gitpod_2](https://user-images.githubusercontent.com/43397636/113957649-d1832700-9849-11eb-96f1-40efca2d8267.png)

### Expected behavior

It would be nice if I do not need to resize browser to be able click the `Continue` button. Thank you.

### Environment

Browser : Mozilla Firefox Standard Release
Platform : Desktop
Version : 87.0

**Comment by gtsiolis** [comment]
Thanks for catching this @kevinadhiguna! We'll improve this modal in the next iteration and more specifically in https://github.com/gitpod-io/gitpod/issues/3956 where we'll update the modal content and potentially structure. Let's keep this open for now. 🏓

**Comment by gtsiolis** [comment]
Reopening as this is still relevant.

**Comment by gtsiolis** [comment]
Closing this in favor of https://github.com/gitpod-io/gitpod/issues/10747 which contains more relevant information and two potential proposals for resolving this issue, see https://github.com/gitpod-io/gitpod/issues/10747#issuecomment-1191506907. Cc @kevinadhiguna
