### ISSUE TITLE
Keyboard input on terminal chatters with Firefox and fails on Chromium on Antergos or Manjaro linux.

### ISSUE THREAD

**Issue by atusy** [gitpod-io/gitpod#383]
**Describe the bug**
On terminal pane, "abc" becomes "aabbcc" on Firefox and no input on Chromium.

**To Reproduce**
OS: Antergos or Manjaro linux
Firefox: 65.0.2-1
Chromium: 73.0.3683.75-2

**Expected behavior**
Keyboard input on terminals should result asis (i.e. "abc" becomes "abc")

**Notes**

- Terminal pane on chromium recognizes "Ctrl-V" and "Enter"
- Firefox on windows has no problem.

**Comment by jankeromnes** [comment]
Thanks a lot for reporting this issue!

I've also noticed the terminal input doing weird things sometimes. It's probably not the same bug, but on Android the keyboard auto-correct will also interfere with typing in the terminal (typing into temp buffers, replacing the output, mixing up buffers, duplicating letters and words, etc.) Also on iPad I think some letters or keystrokes just don't work (I forgot which, and can't try currently).

I wonder if there is a way to set the terminal into a "raw input" mode with no autocorrect / auto-capitalizing / fancy input-assist behavior, just entering the keys that you press. For example on twitter you mentioned the SKK Japanese input method, maybe there is some way to indicate that it should not try to be "smart" here.

Also, this is probably not just a bug in Gitpod, but in https://github.com/theia-ide/theia and more specifically in https://github.com/xtermjs/xterm.js/

**Comment by atusy** [comment]
Thanks for reporting situations in other plat forms.
I agree that this bug is related to xterm.js, though I didn't know about xterm.js.
I experienced similar bugs in RStudio Server and https://rstudio.cloud which also use xterm.js as well.
I found an issue which might be related to ours https://github.com/xtermjs/xterm.js/issues/1527 .
