### ISSUE TITLE
Files created with init not visible in file browser

### ISSUE THREAD

**Issue by parsley42** [gitpod-io/gitpod#384]
**Describe the bug**
When creating a new workspace, I clone another repository with related files in an init task. The directory, but none of the file contents, is visible, and I'm unable to open those files for editing.

**To Reproduce**
Simple:
- Go to https://gitpod.io#https://github.com/lnxjedi/gopherbot
- Try to view/open/edit files in robot.skel/

**Expected behavior**
Files appear in files browser, can be opened and edited.

**Comment by AlexTugarev** [comment]
@parsley42, thanks for reporting!

**Comment by AlexTugarev** [comment]
for some reasons directory contents cannot be fetched for `robot.skel`. there is an error logged: `Error: Request 'getFileStat' failed`

**Comment by parsley42** [comment]
FYI, if I manually clone the repo in the terminal, everything is fine; I added this to init because I was needing to do this every time

**Comment by AlexTugarev** [comment]
on the theia backend I see: `ELOOP: too many symbolic links encountered, stat '/workspace/robot.skel/gopherbot'`

**Comment by parsley42** [comment]
argh, yes - looks like this is just an issue with the symlink; when I fixed the link the files all appeared. I'll fix my .gitpod.yml, thanks.

Nothing shows up in the "Problems" tab - I can see where this kind of user error could cause headaches; any way for that "ELOOP" error to find it's way to the user?

**Comment by AlexTugarev** [comment]
Good point. Ideally, problems with file operations might be reported in the Output view. Currently, you only see errors related to `getFileStat` in the JS console of your browser.

**Comment by AlexTugarev** [comment]
@parsley42, let us now if it works for you after fixing the symlink.

**Comment by parsley42** [comment]
Yes, this works after fixing the symlink in my .gitpod.yml, thanks. Feel free to close.
