### ISSUE TITLE
Registry Facade: Error "cannot get spec"

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3842]
The Recistry Facade sometimes logs the error 
```
invalid ref: rpc error: code = NotFound desc = not found:
    github.com/gitpod-io/gitpod/registry-facade/pkg/registry.(*RemoteSpecProvider).GetSpec
        /tmp/build/gitpod-core-components-registry-facade--app.843ddf66799a01837f3c42462a3ed17f6e10e794/pkg/registry/imagecfg.go:55
  - invalid ref
```

Occurance [of this error in the last 12h](https://cloudlogging.app.goo.gl/qpmfsM4CYcb62Ybr5):
![image](https://user-images.githubusercontent.com/239422/114010478-6c88fa80-9864-11eb-89ad-fad231051ed1.png)

A follow-up error of this is a [ghost failing to pull its image](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-04-08T09:31:46Z;pinnedLogId=2021-04-08T09:31:46Z%2F6nso15g5eq4bz4;query=%22registry%22%0Atimestamp%3D%222021-04-08T09:31:46Z%22%0AinsertId%3D%226nso15g5eq4bz4%22;summaryFields=jsonPayload%252Fmetadata%252Fname:false:32:beginning;timeRange=PT3H?project=gitpod-191109):

> Failed to pull image "reg.gitpod.io:31000/remote/28f260b2-9cc0-4706-8820-0f6eb6f43f6f": rpc error: code = Unknown desc = failed to resolve image "reg.gitpod.io:31000/remote/28f260b2-9cc0-4706-8820-0f6eb6f43f6f:latest": no available registry endpoint: reg.gitpod.io:31000/remote/28f260b2-9cc0-4706-8820-0f6eb6f43f6f:latest not found

Not sure yet what causes this, but it seems relevant, because it prevents pods from starting becaue their containers can't be pulled.

**Comment by meysholdt** [comment]
[Image-Pull-Failures started on March 31st](https://console.cloud.google.com/errors/CMz4koK0keWi8wE?time=P30D&project=gitpod-191109&organizationId=327752801919) and are up to 205 per day: 
![image](https://user-images.githubusercontent.com/239422/114016711-69ddd380-986b-11eb-8ea5-3beff94bdb46.png)

**Comment by csweichel** [comment]
Looks like some requirement towards image refs tightened which invalidates the image refs we're trying to pull from registry-facade. Maybe this came in with recent dependency updates.
