### ISSUE TITLE
Ports not opening

### ISSUE THREAD

**Issue by AndrewH1188** [gitpod-io/gitpod#3843]
### Bug description

Good Morning 

I hope you are well?

I having an issue where the ports wont open and was wondering if you would be able to help me please to solve this?

Many thanks for your help in advance.

All the best.

Andrew

### Steps to reproduce

33060 – detecting...
3306 – detecting...
8000 – detecting...

tried python3 -m http.server to open port 8000 but it wont open and sits as detecting as shown from the copied and pasted text above

### Expected behavior

should see: 
make public       open port     open browser

![Screenshot 2021-04-08 at 10 44 40 am](https://user-images.githubusercontent.com/79570978/114012521-55dfa500-985e-11eb-8126-33fb9f6d4a1d.png)

**Comment by akosyakov** [comment]
Hello, could you share a workspace id, repo and when did it happen please? Is it resolved now? Did you try to restart the workspace? Unfortunately it is only workaround for now. We are going to improve handling later, you can track: https://github.com/gitpod-io/gitpod/issues/3160

**Comment by AndrewH1188** [comment]
Hello, 

Thank you for your reply.

I have just been on lunch, come back and the workspace had stopped. I restarted this and it is working again : )

I am happy that this is working again and Thank you again for your help : )

All the best

Andrew
