### ISSUE TITLE
git checkout breaks workspace

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3848]
### Bug description

`git checkout \<any-branch\>` triggers the workspace to go into an error state and terminate:

### Steps to reproduce

1. Open https://gitpod.io/#https://github.com/gitpod-io/gitpod
2. `git checkout` any other branch, for instance `git checkout gpl/fix-delete-workspaces`

### Expected behavior

Workspace should stay alive.

![image](https://user-images.githubusercontent.com/32448529/114032200-61da5f80-987c-11eb-92f7-225aeb281ac6.png)

**Comment by jankeromnes** [comment]
I could reproduce, but only with https://github.com/gitpod-io/gitpod, not with a different repository.

**Comment by akosyakov** [comment]
A duplicate of https://github.com/gitpod-io/gitpod/issues/3752?

**Comment by geropl** [comment]
Closing ad dup of #3752
