### ISSUE TITLE
Support opening git tags in Gitpod

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#385]
STR:
1. Go to repository that has git tags, e.g. https://github.com/emmawedekind/web-development-for-beginners
2. Click on Branch > Tags > (tag name) to switch to a given git tag
3. Try to open in Gitpod, e.g. https://gitpod.io/#https://github.com/emmawedekind/web-development-for-beginners/tree/html

Expected result: Gitpod checks out the requested git tag

Actual result:

> An error occurred during `git clone`, the repository or branch could not be accessed

<img width="320" alt="Screenshot_20190316-151411" src="https://user-images.githubusercontent.com/599268/54476528-bf676380-47fe-11e9-8d9e-145e39939fa2.png">

**Comment by geropl** [comment]
Merged but not deployed yet.
