### ISSUE TITLE
User/snippets location in gitpod workspace

### ISSUE THREAD

**Issue by RandomFractals** [gitpod-io/gitpod#3852]
### Bug description

I am looking to enable User/snippets display in [Snippets Viewer](https://github.com/RandomFractals/vscode-snippets-viewer) for devs using gitpod workspaces.

Since your in-browser experience uses different files and settings storage scheme for saving and retrieving user snippets, I would like to know a good way to get to them via `workspace.fs` with custom `user-data` file sheme or other ways you might have documented for your environment and vscode containers.

See details in https://github.com/RandomFractals/vscode-snippets-viewer/issues/58 
and https://github.com/RandomFractals/vscode-snippets-viewer/issues/59

### Steps to reproduce

1. Install [Snippets Viewer](https://open-vsx.org/extension/RandomFractalsInc/snippets-viewer)
2. Create User Snippet via File -> Preferences -> User snippets menu. Pick a language, like `javascript` in the user snippets language list to create new custom user snippets.
3. Note the location of user snippet file created is `vscode-userdata:/User/snippets/javascript.json`

![image](https://user-images.githubusercontent.com/656833/114049379-047ce900-9851-11eb-9787-50b0fd548e6c.png)

### Expected behavior

Expected to see user snippets retrieved from Settings for your in-browser workspace, as other user data and settings are retrieved, not via custom `vscode-userdata:/` file scheme, which doesn't even match `user-data` structure I've seen in other vscode docs, like the one for portable mode.

This is what it looks like in CodeSpaces:

![remote-workspace-user-snippets-error](https://user-images.githubusercontent.com/656833/114049841-66d5e980-9851-11eb-8fef-6f04dbb60819.png)

I am trying to figure out how to access them in both deployments.

Thanks!

### Example repository

https://github.com/RandomFractals/vscode-snippets-viewer

**Comment by akosyakov** [comment]
Following works for me:
```ts
vscode.commands.registerCommand('gitpod.readSnippets', async () => {
		const buffer = await vscode.workspace.fs.readFile(vscode.Uri.parse('vscode-userdata:/User/snippets/test.code-snippets'));
		const content = new util.TextDecoder().decode(buffer);
		const testChannel = vscode.window.createOutputChannel('test');
		testChannel.appendLine(content);
	});
```

<img width="1444" alt="Screenshot 2021-04-09 at 09 32 19" src="https://user-images.githubusercontent.com/3082655/114145236-7ff49e00-9916-11eb-9448-f40a73338c7b.png">

I think the difference between Gitpod and Codespaces is only in how title is rendered, they both use the same scheme to access user data under the hood.

**Comment by RandomFractals** [comment]
great! I figured that file scheme and using `wrokspace.fs` to read it would work for your workspaces based on a test file path tooltip. I am still not sure that's the case for CodeSpaces, but I'll make that change on my end and take it from there.

Thanks @akosyakov!
