### ISSUE TITLE
Files being opened in the wrong tab when using "gp open" with vs_code

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#3853]
### Bug description

The "gp open" command is inconsistent between Theia and VSCode.

When using the "gp open" command in Theia the new files always opened on the left side on the screen (without blocking the preview window).

Now VS_Code is default IDE and the "gp open" blocks the preview when new files are opened.

Note: We have created [hundreds of exercises and interactive tutorials](https://github.com/4GeeksAcademy/Interactive-Tutorials) that are being used in Gitpod by hundreds of students every month (and growing), for us the "Preview" feature and `gp open` command has become very sensitive.

### Steps to reproduce

Open this repository with gitpod and the VS Code: https://github.com/4GeeksAcademy/html-tutorial-exercises-course

A preview window will show with video and tutorials.

Then run the command "gp open README.md" (or any other file)

You will see how it blocks the preview window.

### Expected behavior

The files should open on the left side of the screen.

![Simple-Browser-—-html-tutorial-exercises-course-—-Gitpod-Code](https://user-images.githubusercontent.com/426452/114050459-49594d80-985a-11eb-901f-62d401f35fef.png)

**Comment by akosyakov** [comment]
I will see what I can do, but VS Code UX is different from Theia. In Theia there used to be the left side bar where we opened the preview. In VS Code preview itself it just another editor which is opened in the editor area. `gp open` delegates to code cli  which opens a new editor in the last focused editor group. I could try to change semantic of `gp open` to always open in the first editor group but it probably won't be satisfactory in other cases.

**Comment by akosyakov** [comment]
One option is to create a VS Code extension exposing a command which opens a new editor in the correct position and call it using code cli, i.e. `code --command myextenison.openToRight relativeFilePath`. You will need to add such extension to .gitpod.yml of all projects.

There is also a built-in command `_workbench.open` for such usages: https://github.com/gitpod-io/vscode/blob/3a6b7f7cbdc969dcba3d4efb9142c91c15b5aff9/src/vs/workbench/browser/parts/editor/editorCommands.ts#L440-L464 But it can allow to open in specific editor group, say in first, and I could not figure it out how to call it properly yet. If we can reuse it then you don't need to add a new extension, but it is less flexible.

**Comment by akosyakov** [comment]
Actually you can do following:
`gp open package.json && code --command workbench.action.moveEditorToPreviousGroup`

**Comment by alesanchezr** [comment]
> Actually you can do following:
> `gp open package.json && code --command workbench.action.moveEditorToPreviousGroup`

I was testing this option but it is a bit inconsistent, sometimes it also sends the preview to the left side.

I think our only option is to ask everyone to go back to Theia until we finish developing a VSCode plugin that does not use the "preview" option but instead uses a Webview.

**Comment by alesanchezr** [comment]
Hey @akosyakov do you think it will be possible to specify the default editor on the gitpod.yml?

The priority will be like this:
- Has the user specified a favorite editor?
- If not... does the gitpod.yml has a default editor?
- if not... vscode.

We are already developing the vscode plugin to fix this bugs that we are having but it may take some time 😢

**Comment by akosyakov** [comment]
> Hey @akosyakov do you think it will be possible to specify the default editor on the gitpod.yml?

I don't think it is an option for us, since it makes the switch from Theia to VS Code even more harder if we allow it. We should rather help you to build the plugin.

> I think our only option is to ask everyone to go back to Theia until we finish developing a VSCode plugin that does not use the "preview" option but instead uses a Webview.

I don't think you need to switch to webview just to open an editor in another position. It can be an extension with one command which you call from `code --command mycommand` instead of `gp open` and which works more consistence than `gp open package.json && code --command workbench.action.moveEditorToPreviousGroup`.

**Comment by akosyakov** [comment]
Unfortunately, I think the only way is to use custom webview. `code --command` is probably will be removed in upstream.

**Comment by alesanchezr** [comment]
Oh no! I was almost ready with this. This is horrible.

**Comment by alesanchezr** [comment]
The webview is a terrible tool for what we need:

1. It creates an iframe with a specific origin called `vscode-webview://` making impossible to communicate with the outside world: We can no longer run youtube videos for the exercise solutions.
2. I can neither use a websocket to communicate between the extension and the UI.
3. I don't event even have access to http://localhost:3000 where the exercise engine is running. 

I only have hacky ideas on how to work around this limitations:

- **Access to localhost:** My webview will have an iframe inside (nested iframes I guess), that way I can all access to localhost on by child iframe.
- **Opening Files without overlapping the instructions:** The only idea that I have is to subscribe to a local file in the workspace that contains the current context of the exercise engine: The currently opened exercise, the current settings, etc. Everytime that file changes I reload the extension and compare changes, if the "opened exercise" changed, then I close the previous files and open the new one.

**Comment by akosyakov** [comment]
@alesanchezr Do you have a sample vscode extension which demonstrates these issues? I can have a look how to resolve them.

**Comment by akosyakov** [comment]
> Oh no! I was almost ready with this. This is horrible.

@alesanchezr Also to clarify: [executeCommand](https://code.visualstudio.com/api/references/vscode-api#commands.executeCommand) is much more powerful than `code --command`. So removing it from CLI should not be a showstopper, you still can call any command from a VS Code extension. Is it enough for you to unblock?

**Comment by alesanchezr** [comment]
No executeCommand function is not a solution because that function must be called inside of the vs code extension, but the previous cli `--command` option I was able to run vs commands from anywhere inside the gitpod container without extra logic. 

But I'm testing a solution that seems to be working fine so far, I subscribed to a `queue.json` file that implements a task queue, when the text file updates the extension retrieves the updates, a similar concept to the classic MessageBrokers but in a very small and text-file-based way.

The other issues I have hope I can get done (the most important ones). But all hope is lost hope for the following ones:

- Playing youtube videos: I will just open them on a new browser window using `vscode.env.openExternal`.
- Always visible instructions: I manage to keep it always visible if the user does not manually drag it to any other column, but if the user drags it to any other column is impossible to send it back to `vscode.ViewColumn.Two`.

But these two features are not really mandatory for MVP, I'm working hard on finishing the rest of the integration by next week and start testing in all the current exercises we already have.

Thanks for caring and your willingness to help!

**Comment by alesanchezr** [comment]
Ok @akosyakov I think you can close this issue, I've managed to solve most of the issues I had. 

1. Youtube videos work perfectly on Gitpod from within the webview/iframe (Kudos to you guys for that!).
2. I was able to make the instructions a lot harder to hide or move from the `vscode.ViewColumn.Two`, I think is stable enough to become "beginners-proof".
3. I'm 90% with everything else, just having to replace the window.confirm and window.prompt with our own implementation in JS/HTML/CSS (because the vscode webview blocks them).

I will send you a link once I have something production-ready so you can take a look.
