### ISSUE TITLE
Can't change the workspace name

### ISSUE THREAD

**Issue by jatv93** [gitpod-io/gitpod#3854]
### Bug description

It's not available the option to change the workspace name

### Steps to reproduce

Click on the name or the menu in the workspace, there is no option to change it

**Comment by akosyakov** [comment]
Do you mean from the dashboard?

**Comment by akosyakov** [comment]
cc @gtsiolis

**Comment by jatv93** [comment]
Yes! From the dashboard

**Comment by gtsiolis** [comment]
Closing this in favor of https://github.com/gitpod-io/gitpod/issues/3946. /cc @jatv93
