### ISSUE TITLE
Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: %!w(string=)

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#3856]
### Bug description

Workspace won't open in Gitpod.

This is an old workspace that we always use with Gitpod, I did a small change removing a `migrations` folder and now it won't open in Gitpod.

### Steps to reproduce

Just open this: https://gitpod.io/#https://github.com/4GeeksAcademy/react-flask-hello

### Expected behavior

Open the workspace and follow dockerfile and gitpod.yml

**Comment by alesanchezr** [comment]
Ok now it gives a different error:   
```
Error: build failed: cannot build workspace image: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"mkdir /workspace/wsctx: no space left on device\"": unknown
```

**Comment by aledbf** [comment]
@alesanchezr apologies. Please try again.
