### ISSUE TITLE
[code] problem keyboard keys in tablet

### ISSUE THREAD

**Issue by SheikhElMoctarG** [gitpod-io/gitpod#3858]
### Bug description

video
https://h.top4top.io/m_192489c8e1.mp4

### Steps to reproduce

in VScode, keyshorts

**Comment by akosyakov** [comment]
Could you share which device do you use please?

**Comment by SheikhElMoctarG** [comment]
> Could you share which device do you use please?

Samsung galaxy tab A(2016)
