### ISSUE TITLE
Horizontal scrollbar on pages that shouldn't have one

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#3859]
### Bug description

When you go to https://gitpod.io/plans or https://gitpod.io/integrations you can see a horizontal scrollbar that probably is there by mistake.

![image](https://user-images.githubusercontent.com/29888641/114099584-53fbfd00-98c3-11eb-96bf-1e5d82ae929b.png)
![image](https://user-images.githubusercontent.com/29888641/114100262-51e66e00-98c4-11eb-9ace-5bc6a285b80e.png)

### Steps to reproduce

1. Sign in to your GitPod account
2. Go either https://gitpod.io/plans or https://gitpod.io/integrations
3. See the scrollbar

### Expected behavior

There shouldn't be a horizontal scrollbar in these places.

### Example repository

_Not applicable_

**Comment by filiptronicek** [comment]
Recently, I've noticed this is also present on the workspaces views under `/workspaces`

![image-redacted_dot_app(25)](https://user-images.githubusercontent.com/29888641/114312115-ceaa5f80-9af1-11eb-979e-e2b874df8e2f.png)

**Comment by jankeromnes** [comment]
Aha, thanks @filiptronicek! I suspect this is because of `width: 100%` combined with `margin` or `padding` on some elements, but I haven’t been able to reproduce it, nor to fix it yet.

Also, maybe this will resolve itself when we make the dashboard responsive for mobile. Will try to fix this soon.

**Comment by JanKoehnlein** [comment]
@jankeromnes Are you still on it?
