### ISSUE TITLE
Don't suggest the web extensions on mobile

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#386]
**Describe the bug**
When using Gitpod on mobile, I'm always asked to install the Gitpod web extension, but it doesn't work on mobile.

**To Reproduce**
1. Open a Gitpod workspace on mobile (e.g. Firefox or Chrome on Android)
2. See the web extension message in the loading screen

**Expected behavior**
The web extension message should not appear.

![Screenshot_20190316-152142](https://user-images.githubusercontent.com/599268/54476628-d5c1ef00-47ff-11e9-9122-c705f18e54ff.png)

![Screenshot_20190316-151048](https://user-images.githubusercontent.com/599268/54476632-dc506680-47ff-11e9-9434-2fb337239250.png)

![Screenshot_20190316-152341](https://user-images.githubusercontent.com/599268/54476637-e83c2880-47ff-11e9-8f80-901cf766366a.png)

**Comment by rugk** [comment]
…actually, on Firefox for Android you could make it compatible and thus allow it to be used there. (after all, AFAIK it just adds one button to GitHub)
