### ISSUE TITLE
All active workspaces are deleted all at once when using the keyboard.

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#3876]
### Bug description

If I acknowledge the deletion of a workspace using the keyboard, every single active workspace I have is deleted simultaneously.

### Steps to reproduce

**In the workspace dashboard**:
- Have any number of workspaces in any state
- Have the filter dropdown set to either Active or All

1. Click the hambuger for a workspace and choose delete
2. Acknowledge the deletion using the keyboard

All workspaces are deleted.

### Expected behavior

Only the workspace the user chooses should be deleted.

### Example repository

Gitpod username: apolopena

**[Example 1 Video](https://youtu.be/R3cg6B70h8k)**

**[Example 2 Video](https://www.youtube.com/watch?v=R3cg6B70h8k)**

**Comment by gtsiolis** [comment]
Great catch @apolopena! I can reproduce this. Will push for a fix within the current milestone. 🥇

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/3945

**Comment by apolopena** [comment]
The way this bug was fixed introduces a new bug.
Please let me know if you want me to file it or if we can address it here.

Hitting the enter key when there is a choice to make, especially in a modal means the the user is saying "Yes" to that choice/prompt. In this case, with this fix, hitting enter closes the modal without taking action. This is indeed a bug as the expected action is to delete the workspace since the user just said "Yes" by hitting enter.

**Comment by gtsiolis** [comment]
Thanks for noticing @apolopena! Yes, feel free to open a new issue if you can concretly describe this as a bug. The plan it to tackle more accessibility and interaction issues including this one in the upcoming iterations. 🏓 

**Footnote**: It's prefereable to avoid reopening closed issues and instead consider opening new ones for future improvements. This can be beneficial in many ways like making us move faster and better. 💡
