### ISSUE TITLE
Consider making pending changes column more accurate for running workspaces

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#3877]
### Problem to solve

Currently, when a workspace is running a) we do not surface any information related to pending changes and b) we're reusing the same state of no changes using the _No Changes_ label which could be confusing to the user.

### Proposal

Tracking live changes when a workspace is running is technically challening if not also inneficient (cc @csweichel). However, we could change the _Pending Changes_ column to be more accurate by a) removing the _No Changes_ label or b) introducing an affordance to indicate the possibility of pending changes.

TBD (To be discussed)

---

<details>
<summary>Original description</summary>

### Bug description

**In the Workspaces Dashboard**:
Any _new_  (unstaged) files generated when a workspace is created do not show up in the Pending Changes column. These new files will show up in the Pending Changes column if you stop the workspace but that status will revert back to No Changes if you restart the workspace and it becomes active again.

### Steps to reproduce

1.  [![Try it out on on Gitpod.io](https://gitpod.io/button/open-in-gitpod.svg)](https://github.com/apolopena/gitpod-test68)
2. 15 text files will be created
3. Go to the workspace dashboard, Pending Changes column for that workspace will have a staus of No Changes
4. Stop the workspace
5. In the workspace dashboard change the filter dropdown to All
6. Once the workspace is stopped, the Pending Changes column for that workspace will have a status of 15 Changes
7. Start the workspace again
8. Once the workspace is started again, the Pending Changes column for that workspace will have a status of No Changes

### Expected behavior

In the workspaces dashboard any unstaged changes should show up in the Pending Changes column for a workspace regardless of the state of that workspace.

### Example repository

 [![Try it out on on Gitpod.io](https://gitpod.io/button/open-in-gitpod.svg)](https://github.com/apolopena/gitpod-test68)

</details>

**Comment by akosyakov** [comment]
@gtsiolis a bug?

**Comment by gtsiolis** [comment]
Hey @apolopena! This is expected due to the fact that is technically challenging to track changes when the workspace is running. /cc @csweichel 

In the meantime, a small UX improvement could be to replace the _No Changes_ label, when the workspace is running, with something more descriptive to that users can be educated about this state.

Thanks for the ping @akosyakov! 🏓

**Comment by apolopena** [comment]
That makes sense.

**Comment by gtsiolis** [comment]
FYI I've updated the description in this issue and kept the original description inline, to keep it as a single source of truth (SSOT) for tracking this feature. 🏀

**Comment by apolopena** [comment]
Is this really stale?
