### ISSUE TITLE
Support delete workspace

### ISSUE THREAD

**Issue by LezaiNiubi** [gitpod-io/gitpod#388]
![img](https://user-images.githubusercontent.com/17443917/54494968-c08db300-491a-11e9-9bd5-6ecd60c8ce69.png)

**Comment by dclong** [comment]
This is a must-have feature.

**Comment by jankeromnes** [comment]
Agreed! Part of the back-end is already in place, so @geropl and I are trying to make it happen.

**Comment by 32leaves** [comment]
We have implemented this feature - it will be deployed with the next release :)
