### ISSUE TITLE
Unable to install GitPod instructions are wrong. Version 0.7.0 does not exist

### ISSUE THREAD

**Issue by simonjcarr** [gitpod-io/gitpod#3880]
### Bug description

I have tried to install a self-hosted version of GitPod but failed miserably.

The first issue I get is that the instructions seem to be wrong from the start. They state I should run the following command

```
helm install -f values.custom.yaml gitpod gitpod.io/gitpod --version=0.7.0
```

There is no version 0.7.0 of GitPod. There is however a version 0.6.0

### Steps to reproduce

Follow the install instructions here https://www.gitpod.io/docs/self-hosted/latest/install/install-on-kubernetes

### Expected behavior

Version 0.7.0 of the software should exist

### Example repository

N/A

**Comment by geropl** [comment]
Thx for reporting @simonjcarr ! This is a clear case of outdated documentation. Fixed with: https://github.com/gitpod-io/gitpod/pull/3900

**Comment by geropl** [comment]
re-opening as it's not deployed yet

**Comment by geropl** [comment]
Closing because outdated.
