### ISSUE TITLE
iPad: can't open workspace URLs from UI

### ISSUE THREAD

**Issue by ccssmnn** [gitpod-io/gitpod#3881]
### Bug description

On the iPad Gitpods new editor doesn't open ports in the browser in none of the provided ways. The Theia-based IDE worked.

I'm not sure if the notification interactions are working at all on the iPad. It looks like they are only dismissed when being touched, even when the cursor highlights a button.

### Steps to reproduce

1. "A service is available on port XXXX" dialog offers an "Open Browser" option which doesn't work
2. CMD + Click on the URL in the terminal doesn't work
3. "Remote Explorer" has a list of ports. Tapping/clicking the "Open Browser" button (globus icon) doesn't work.

### Expected behavior

Well, it should work. But there is a workaround:

1. Run `gp url PORT_NUMBER > file.txt` to print the URL into a file
2. open `file.txt` in editor and copy the url with CMD+C
3. paste it wherever you want

**Comment by akosyakov** [comment]
Which browser? Could it be blocking new windows?

**Comment by ccssmnn** [comment]
I've only tried Safari on iPadOS 14.4.2 with no other active windows (neither split screen nor sidebar).

**Comment by AlexTugarev** [comment]
Hi @ccssmnn! I just tried and could reproduce the silent behavior with popup blocker turned on in `Settings > Safari`. Please check if that's enabled for you. When the popup blocker is disabled, Safari is asking if it's Ok to open the workspace port URL.

**Comment by ccssmnn** [comment]
Thank you @AlexTugarev! Disabling the popup blocker worked for all 3 ways to open a link.
