### ISSUE TITLE
Avatar is broken if switched to Gravatar in GitLab

### ISSUE THREAD

**Issue by bigint** [gitpod-io/gitpod#3882]
### Bug description

Avatar is broken if I switch the avatar provider to Gravatar in GitLab

### Steps to reproduce

- Open GitLab Profile settings
- Remove avatar from GitLab
![image](https://user-images.githubusercontent.com/69431456/114269977-73139f80-9a27-11eb-9525-504ce8a8ed79.png)
- Check the avatar in Gitpod

### Expected behavior

Avatar in Gitpod should be changed to Gravatar

**Comment by gtsiolis** [comment]
Hey @bigint, I cannot reproduce this. Avatar falls back to gravatar when removing the custom profile image from GitLab.com. Have you tried logging out and logging in again? ❓

**Comment by bigint** [comment]
Yes @gtsiolis It's not working still!
