### ISSUE TITLE
How do I set PATH before vscode starts?

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#3883]
I set the path here, in .gitpod.yml/before:
https://github.com/markfirmware/zig-vector-table/blob/6e6a957d041ef37c90778ea3484f5220ce55b6e8/.gitpod.yml#L9

This extension:
https://github.com/markfirmware/zig-vector-table/blob/6e6a957d041ef37c90778ea3484f5220ce55b6e8/.gitpod.yml#L20

starts an lsp server and that server needs the PATH that I set (it would be inherited from the vscode process.) It does not seem to get the PATH that I set in .gitpod.yml/before and I think that that is because vscode is started before the .gitpod.yml/before executes.

Thanks,
Mark

**Comment by akosyakov** [comment]
You will need to configure it in your docker image: https://www.gitpod.io/docs/config-docker

**Comment by markfirmware** [comment]
The problem is that a custom docker image takes a long time to load. May I propose a pre-vscode phase in the .gitpod.yml?

Thanks, Mark

**Comment by akosyakov** [comment]
> The problem is that a custom docker image takes a long time to load.

Should not it be just one layer on the top of workspace full image which is already loaded anyway?

> May I propose a pre-vscode phase in the .gitpod.yml?

@csweichel @svenefftinge We allow to configure env variables for task terminals, maybe we can section for vscode env variables? , i.e. `vscode.env` ? or generally for IDE?

**Comment by akosyakov** [comment]
Thinking about it adding to .gitpod.yml won't help because you don't want to override env variable but most likely prepend or append. Providing a custom image should be way to go. It would be good if someone could have a look why loading your custom image takes so long? Do you have a branch with it already?

**Comment by markfirmware** [comment]
I do agree that custom images are the general solution for things like this. I will prepare a simple case where I think loading a custom image is slow. I will respond with it tomorrow. Thanks!

**Comment by markfirmware** [comment]
1. I started a simple repo with a custom image at https://github.com/markfirmware/gitpod-custom-image. I am not sure anymore whether custom images are loaded at speeds that are too slow. Is there a log file left in the workspace that records events, with timestamps, of the workspace activation?

2. The custom PATH is $GITPOD_REPO_ROOT/tools:$PATH but I do not think that that will work since GITPOD_REPO_ROOT will not be available when the image is built.

**Comment by akosyakov** [comment]
@markfirmware chatted with @csweichel @svenefftinge internally. We are looking into improving perf in Q2 generally and in particularly for use case.

**Comment by markfirmware** [comment]
Thank you. I can get by with things as they are. You can keep this issue open for tracking or close it as you see fit.
