### ISSUE TITLE
Terminal is losing output bytes

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#3884]
### Bug description

Some escape codes are lost causing this output:

testing 9999: info: info: 
info: info: 
info: 

### Steps to reproduce

Start the repo, the program will be compiled and it will run.

### Expected behavior

testing 9999

### Example repository

https://github.com/markfirmware/zig-test-terminal

**Comment by akosyakov** [comment]
fixed by https://github.com/gitpod-io/gitpod/pull/3870

**Comment by markfirmware** [comment]
When will this be deployed? I have an important use case - embedded development using qemu - that produces a 20 byte once a second and it is disrupted within a few seconds.

**Comment by akosyakov** [comment]
deployed, there are still some minor issues with resize on reload, but they will be fixed with May release
