### ISSUE TITLE
Fix image builder garbage collection mechanism

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3887]
the image builder keeps accumulating several hundreds of gigabytes of disk space until we run out of disk space.

~Running `docker system prune` does the trick. This should happen automatically. Maybe every hour or when 100GB disk usage is reached.~

The image builder already has a mechanism to garbage-collect old images. We should fix it.

**Comment by meysholdt** [comment]
This causes image builder outages: https://community.gitpod.io/t/error-build-failed-rpc-error-code-internal-desc-cannot-create-build-volume/3190

**Comment by jankeromnes** [comment]
We've briefly discussed this issue with @aledbf and @geropl. Two thoughts:

- Garbage-collecting based on level (e.g. > 90% full) makes more sense than based on time (e.g. every hour) because it more accurately addresses the problem (disks getting full) while not deleting useful cache when that isn't needed

- Every production workspace node (N2 type) has **two** 350GB SSDs. Currently, we only use the first one, and leave the second one sitting empty. Maybe we could simply make image-builder use the second SSD?

**Comment by aledbf** [comment]
> Currently, we only use the first one, and leave the second one sitting empty. Maybe we could simply make image-builder use the second SSD?

The size of the disk for the builder is already using 350GB. I think this should be increased.

**Comment by meysholdt** [comment]
> Maybe we could simply make image-builder use the second SSD?

I'd love to remove the second localSSD for cost reasons, but GCP [says that N2 nodes with 12 or more cores can only be configured with at least two localSSDs](https://cloud.google.com/compute/docs/disks#local_ssd_machine_type_restrictions). 

> Garbage-collecting based on level (e.g. > 90% full) makes more sense

If image-builder uses the second ssd, I agree.

If image-builder uses the first ssd, I'd be worried starting workspaces may not have enough disk space, because they may need the disk space faster than imageb-builder-gc would make it available. 

> The size of the disk for the builder is already using 350GB. I think this should be increased.

[localSSDs come on one size only](https://cloud.google.com/compute/docs/disks#localssds). To get more storage, google recommends to combine multiple of them - which is exactly what we're discussing here.

**Comment by meysholdt** [comment]
When looking at the disk consumption of an image builder, I'm starting to think that 
* GC works in general, BUT
* re-deploys trigger an increased need for image-rebuilds, so that GC is no longer sufficiently aggressive.

In the picture at a few min before 8 your can see the redeploy:
![image](https://user-images.githubusercontent.com/239422/114840745-656b6a80-9dd7-11eb-9c0f-2906913b3dca.png)
