### ISSUE TITLE
Close vnc viewer tab (6080) when workspace-full-vnc stops

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#3888]

**Comment by akosyakov** [comment]
Could you elaborate please?

**Comment by markfirmware** [comment]
My port 6080 (openvnc desktop) is marked as openBrowser, so I have not only the gitpod vscode browser window open, but I also have an openvnc desktop browser window (actually a tab) open.

When I stop the gitpod workspace, the openvnc can no longer connect. It would be an improvement if that openvnc window could close automatically since there is no longer an active workspace serving it.

Thanks,
Mark

**Comment by akosyakov** [comment]
I am not sure that we can do anything about it. Whatever is served from some port is in control by workspace and user, not Gitpod. It should be resolved by the application serving from this port. Gitpod only serves it without any intervention.

**Comment by markfirmware** [comment]
I was thinking that the novnc window was opened as a consequence of openBrowser in .gitpod.yml. I am guessing that js in the main gitpod browser window called window.open(). This page https://developer.mozilla.org/en-US/docs/Web/API/Window/close says that if a script opens a window, it can close it.

As you said, a general solution would require much more thought. However, 6080 is used explicitly for the novnc desktop, so I think it could be closed when the the user selects stop workspace.

I think this might be able to be done.

**Comment by akosyakov** [comment]
> I was thinking that the novnc window was opened as a consequence of openBrowser in .gitpod.yml. I am guessing that js in the main gitpod browser window called window.open(). This page https://developer.mozilla.org/en-US/docs/Web/API/Window/close says that if a script opens a window, it can close it.

We open new windows with `noopener` flag, otherwise windows will share the same event loop, e.g. debugging one window will stop the main window. With that flag the main window does not control the opened window and cannot close it.

**Comment by markfirmware** [comment]
Thanks.
