### ISSUE TITLE
tap/tun interface support

### ISSUE THREAD

**Issue by pangqingyuan1991** [gitpod-io/gitpod#389]
Is it possible to support tap/tun interface in container? I want to develop a VPN-like program, and this needs adding tap/tun interface and setting route table.

**Comment by meysholdt** [comment]
I haven't worked with TUN/TAP before and I took a brief look at [the documentation](https://www.kernel.org/doc/Documentation/networking/tuntap.txt). But it's not quite clear to me... do you need root privileges or privileges to install something into the linux-kernel to use TUN/TAP devices?

**Comment by pangqingyuan1991** [comment]
OK. Ignore my unreasonable request

**Comment by meysholdt** [comment]
your request wasn't unreasonable. thank you for asking!
