### ISSUE TITLE
[self-hosted] Release Gitpod Self-Hosted 0.9.0

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3893]
ToDo:
  - [x] update to latest Gitpod as from gitpod.io (as usual)
  - [x] docs:
    - [x] reflect our [matrix of supported platforms](https://www.notion.so/gitpod/1b9eac5cb33d42e391f86a87f0e37836?v=4f2ec7c943514ee19203b9d4fe096094) more prominently
    - [x] ~update~ remove OAuth config ~to focus on dynamic setup~: the dynamic part is already documented as part of the "regular" docs
  - [x] build missing UI:
    - [x] reinstate terms page: #3920
    - [x] handle SETUP_REQUIRED: #3920
      - [x] initial Git Provider (on demand)
      - [x] first user to be admin
    ~- [ ] handle EE_LICENSE_REQUIRED https://github.com/gitpod-io/gitpod/issues/3918~
      ~- [ ] Upload License page with a website link to buy the license from~
  - [x] remove deprecated installer images
  ~- [ ] #3912: adjust (and fix) terraform scripts so they are not geared towards installers anymore (and fix #3766 along the way)~

**Comment by dimazaur** [comment]
Hello @geropl 

Could you share your roadmap?
Are you going to fix Self-Hosted in 0.8.0 or in 0.9.0 version?
And what is the schedule?

Thank you.

**Comment by geropl** [comment]
@dimazaur 

> Could you share your roadmap?

You mean our general, Gitpod roadmap? [here it is](https://www.notion.so/gitpod/Gitpod-s-Direction-be35d064c0704fbda61c542b84e07ef6)

> Are you going to fix Self-Hosted in 0.8.0 or in 0.9.0 version?

The 0.9.0 version.

> And what is the schedule?

We originally planned end of this week, but looking through the ToDos (cmp. above) I guess it might as well become next week. Upper bound is end of [April's cycle](https://github.com/gitpod-io/gitpod/milestone/11), though. :upside_down_face:

**Comment by geropl** [comment]
Excluded #3912 and marked as stretch goal for this release due to time constraints :cry:

**Comment by geropl** [comment]
Move `EE_LICENSE_REQUIRED` related work to May due to time constraints.

**Comment by cyrilcros** [comment]
May I point out my pull request #3494 and ask for a merge, since you are updating the self-hosted chart? I can also submit a pull request for #3094.

**Comment by jrdzha** [comment]
Curious if there are any updates here?

Also, I just saw this self-hosted compatibility matrix -- we are running EKS with RHEL, so I'd be happy to testing, if that would be of any help.

**Comment by jrdzha** [comment]
@geropl  Awesome! Very excited for 0.9.0.

**Comment by asthomasdk** [comment]
Looking forward to having 0.9.0 available in a working version for self-hosted...

**Comment by geropl** [comment]
Sorry for the silence here. Was offline due to personal reasons, will continue over the next days.

Also, we're just onboarding someone taking over Self-Hosted more holistically rather than just one engineer one the side, so: stay tuned! :upside_down_face:

**Comment by asthomasdk** [comment]
Sounds good! 
It would be really good to get the self-hosted setup working (and documented) properly.

**Comment by geropl** [comment]
The release: https://github.com/gitpod-io/gitpod/releases/tag/v0.9.0
Issue for the next one: https://github.com/gitpod-io/gitpod/issues/4710
