### ISSUE TITLE
Can't open old workspace

### ISSUE THREAD

**Issue by FeixuRuins** [gitpod-io/gitpod#3894]
### Bug description

I have a workspace that was create around 2 months ago and now whenever I try to open it, it says `Getting workspace info failed`.
![image](https://user-images.githubusercontent.com/66232834/114403764-12917900-9b73-11eb-8399-1c5ca030e009.png)
I believe the workspace was Theia if that helps.

### Steps to reproduce

Open a workspace that was created a while ago.

### Expected behavior

It should launch like any other workspace.

**Comment by akosyakov** [comment]
Could you share workspace id?

**Comment by FeixuRuins** [comment]
`blush-roadrunner-fis7a0je`

**Comment by akosyakov** [comment]
cc @csweichel from backend logs I see that task terminals are failing with:
`rpc error: code = Internal desc = cannot start PTY: fork/exec /bin/bash: no such file or directory`

@FeixuRuins Could you copy errors from devtools?
