### ISSUE TITLE
What happened

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#3896]
I was gone for a weekend and the product looks entirely different.

Somebody please tell me what happened and what has changed.

Thanks,
The extremely confused Reece

**Comment by svenefftinge** [comment]
Hey Reece, sorry for the confusion. We deployed a new version that included a rebranding.
You should have seen a modal when you first logged-in.
some more background here: 
https://www.gitpod.io/blog/next-chapter-for-gitpod

**Comment by RDIL** [comment]
Oh thank god, I can switch back to Theia.

All is well now, thanks.
