### ISSUE TITLE
[self-hosted] Empty login options

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#3904]
### Bug description

If there are no `authProviders` configured, the login doesn't show any action

![Screenshot from 2021-04-12 17-13-12](https://user-images.githubusercontent.com/161571/114463631-ac2c4b00-9bb2-11eb-9f47-97768d80047a.png)

### Steps to reproduce

-

### Expected behavior

A message indicating that there is no configured authentication provider?

### Example repository

-

**Comment by AlexTugarev** [comment]
We need to reinstate a setup page for this case. It used to render the Git Provider component to allow you to setup and connect with a IdP. This is also the way the first user is created. 

cf. #3893
