### ISSUE TITLE
When will this be deployed? I have an important use case - embedded development using qemu - that produces a 20 byte once a second and it is disrupted within a few seconds.

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#3907]
When will this be deployed? I have an important use case - embedded development using qemu - that produces a 20 byte once a second and it is disrupted within a few seconds.

_Originally posted by @markfirmware in https://github.com/gitpod-io/gitpod/issues/3884#issuecomment-818294416_

**Comment by markfirmware** [comment]
I am guessing that deployment is scheduled for the end of April. This is a critical defect for those using the terminal for textual control panel and status programs.

**Comment by akosyakov** [comment]
We are going to deploy a fix for it this week.

**Comment by markfirmware** [comment]
Thank you!

**Comment by akosyakov** [comment]
Scheduled for tomorrow morning.
