### ISSUE TITLE
The GitHub media image is outdated

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#3910]
### Bug description

See
<img width="602" alt="Bildschirmfoto 2021-04-13 um 08 43 43" src="https://user-images.githubusercontent.com/46345125/114508317-7fb91300-9c34-11eb-928f-2dd143cd0f28.png">

### Steps to reproduce

x

### Expected behavior

New one:
![media image](https://user-images.githubusercontent.com/46345125/114508769-0968e080-9c35-11eb-9088-11ca89ea0430.jpg)

**Comment by gtsiolis** [comment]
Updated image in [settings](https://github.com/gitpod-io/gitpod/settings). Thanks @ChristinFrohne! 👩‍🎨 

Image seems to be updated for links to issues, etc. but not when linking to the repository itself probably to some caching on CDNs.
