### ISSUE TITLE
[self-hosted] Make our Self-Hosted terraform scripts infrastructure only

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3912]
Currently our terraform scripts are geared towards a "one-step" install experience as they were meant to be included in the installer images. After we remove those images, we should try to make them work again by:
 - make the terraform scripts _infrastructure only_, without the actual Gitpod installation
 - thus make them work again (fix #3766 along the way)
 - update the docs to reflect the two-step nature:
    1. run provider-specific terraform script (output: `values.terraform.yaml`)
    2. run (generic) helm install

/cc @wulfthimm

**Comment by wulfthimm** [comment]
That would be no problem.

**Comment by asthomasdk** [comment]
Would be nice to see this in action ;-) 

I've been trying for most of a week now to get a working setup with my own terraform for a Hetzner K3s cluster, managed by Rancher 2.5 - and many iterations of trying to get gitpod to work on top of that. A clear set of (working) steps on how to go from zero to Gitpod hero on a simple infrastructure would be great to have.

**Comment by geropl** [comment]
This is issue is superseded by now.
