### ISSUE TITLE
Property editor.defaultFormatter is not allowed

### ISSUE THREAD

**Issue by Eliav2** [gitpod-io/gitpod#3917]
### Bug description

Property `editor.defaultFormatter` is not allowed property in `.vscode/settings.json` file in theia editor on gitpod.\
theia supports editor.defaultFormatter. [see](https://eclipse-theia.github.io/theia/docs/next/modules/editor.html#codeeditorpreferenceproperties-1)
![image](https://user-images.githubusercontent.com/47307889/114533955-257d7980-9c57-11eb-95bd-0e1cf771643c.png)

I'm trying to configure prettier in a gitpod with no success.(formatting keeps using the default formater)

### Steps to reproduce

this branch will recreate the issue:
http://gitpod.io/#https://github.com/Eliav2/react-xarrows/blob/gitpod-prettier-issue/.vscode/settings.json

- go to src folder and open one of the files in the editor.
- select format document
![image](https://user-images.githubusercontent.com/47307889/114533190-501b0280-9c56-11eb-91be-c5085fa74702.png)

seems that the normal formater is used and not prettier

### Expected behavior

editor.defaultFormatter is allowed and prettier is used on formating

### Example repository

https://github.com/Eliav2/react-xarrows/blob/gitpod-prettier-issue/.vscode/settings.json

**Comment by akosyakov** [comment]
We are not going to fix/upgrade Theia anymore. Please switch to VS Code instead: https://gitpod.io/preferences If something is different or does not work in VS Code don't hesitate to open new issues.
