### ISSUE TITLE
"settings.json" file is closed after opening the "Preferences" tab

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#393]
Description:

"settings.json" file is closed after opening the "Preferences" tab

Steps To Reproduce:

1. Login to the site
2. Open the "settings.json" file
3. Click File -> Settings -> Open Preferences 
4. Pay attention to the opened files 
5. Try to open "settings.json" file while "Preferences" tab is opened

Actual result: "settings.json" file is closed after opening the "Preferences" tab. This file also can not be opened while "Preferences" tab is opened
![2019-03-18_17-00-32](https://user-images.githubusercontent.com/41964662/54539997-dd1ffe80-499f-11e9-84c8-81c5dff21e91.gif)

Expected result: "settings.json" file is NOT closed (and can be opened) after opening the "Preferences" tab

Win 10 Google Chrome Version 72.0.3626.121
Win 10 Firefox  65.0.2

**Comment by AlexTugarev** [comment]
We can open the same file only once in an editor. This is a "limitation" in Theia and there is an [issue](https://github.com/theia-ide/theia/issues/3857) to align with vscode eventually. 

/cc. @svenefftinge

**Comment by svenefftinge** [comment]
ok, let's close it here then.
