### ISSUE TITLE
Move gitpod-com compile time variance into this repo

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#3933]
We still have some components left behind in the gitpod-com repo that didn't make the cut when we went open source.
This issue's goal is to move that stuff into the public repository.

**Comment by AlexTugarev** [comment]
probably related https://github.com/gitpod-io/gitpod/issues/4013

**Comment by AlexTugarev** [comment]
Closing this as the rest of the components in the gitpod-com repo will be replaces and not just moved.
