### ISSUE TITLE
It would be more user-friendly if it was possible to return All Collapsed Side Panels

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#394]
It would be more user-friendly if it was possible to return All Collapsed Side Panels
Ctrl+Z doesn't work
And clicking View -> Collapse All Side Panels again also soen't return all closed panels
![2019-03-19_12-02-11](https://user-images.githubusercontent.com/41964662/54597309-093e8c80-4a3f-11e9-9f11-74dd7a7e77be.gif)

**Comment by svenefftinge** [comment]
Changing view layout should not contribute to the undo stack.
I am skeptical there is a real use-case situation where users would want to do that. Usually you want to see something specific. Close all is another way of saying I'll see the editors.
