### ISSUE TITLE
Automatically cancel individual paid plan when accepting a team plan?

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#3948]
**Situation**: A user has an individual paid plan (e.g. Professional), and accepts a team plan invitation, or gets assigned to a team plan seat (e.g. Team Unlimited).

- **Currently**: The user keeps both paid plans. This is unfortunate, because two entities (individual user + team plan manager) are now paying twice for the same result (user can use unlimited hours on Gitpod). The workaround is for the user to cancel their individual plan manually (either by clicking on "Billing" in https://gitpod.io/plans or by downgrading to the Free plan)

- **Ideally**: The newly activated team plan seat should automatically cancel the pre-existing individual plan. Or, at least, the user should get a helpful prompt like:

```
     Welcome into your new team plan! (Team Unlimited)

Would you like to cancel your previous paid plan? (Professional)

    [ Yes, cancel Professional ]        [ No, keep both ]
```

**Comment by AlexTugarev** [comment]
The helpful prompt sounds like a nice idea!

Proactively cancelling the individual plan on assignment of a team seat might be problematic for some users. At least if deltas of the plans are not considered, i.e. cancelling an Unleashed plan in exchange for a Professional Team seat. We also cannot make any assumptions about the duration of the assignment, right?

**Comment by JanKoehnlein** [comment]
This prompt just gives a single opportunity to cancel the existing plan. The user may miss it or not be able to decide that very moment. From that on, the only hint they have that there are two subscriptions is an invoice mail every month.

If we really think that having a team and an individual subscriptions at once is a valid scenario, the UI should reflect that and make it possible to cancel each of these individually. If not, we should automatically cancel any individual subscription when adding users to teams.

**Comment by JanKoehnlein** [comment]
I think, the easiest would be to add a _Cancel Subscription_ button to our _Plans_ page that cancels any individual paid subscription. @gtsiolis and hints on UX are welcome

**Comment by gtsiolis** [comment]
Hey everyone, here're some designs on how we could help resolve this issue. Let me know what you think. 💭 

| Plans without a team subscirption | Plans with a team subscirption |
|-|-|
| <img width="1440" alt="Plans" src="https://user-images.githubusercontent.com/120486/123598995-c236c880-d7fd-11eb-987e-7eeb63be614f.png"> | <img width="1440" alt="Plans-1" src="https://user-images.githubusercontent.com/120486/123598998-c367f580-d7fd-11eb-8b40-46dfe1abac61.png"> |

See [design specs](https://www.figma.com/file/1sviSVuORjErWfUEOBH2cr/Improve-Plans-Individual-v.-Team-3948?node-id=0%3A1 ). 🎨
