### ISSUE TITLE
"Build finished before we established a listener." error after opening some workspaces

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#395]
Description: "Build finished before we established a listener." error after opening some workspaces

Steps To Reproduce:

1. Login to the site
2. Start the workspace 
3. Pay attention to the error 
4. Back to the  Dashboard
5. Pay attention to the Status of previously opened workspace

Actual result: "Build finished before we established a listener." error after opening some workspaces
The status of opened workspace is started ("Stop" and "Open" buttons are active for current workspace) but the workspace can not be opened
![2019-03-19_12-18-12](https://user-images.githubusercontent.com/41964662/54598400-1b212f00-4a41-11e9-8583-037f7bc8af43.png)
![2019-03-19_10-45-34](https://user-images.githubusercontent.com/41964662/54598401-1b212f00-4a41-11e9-8f55-54c5c1e4cc9d.png)

Expected result: No errors are shown after opening any workspace

Win 10 Google Chrome Version  72.0.3626.121
Win 10 Firefox  65.0.2

**Comment by 32leaves** [comment]
@tarasdidyk on which repo did you try to start your workspace?

**Comment by tarasdidyk** [comment]
Bug is reproduced for this workspace -  /start/#e965f888-8796-45ba-9054-0aee42a2f5ee

**Comment by dclong** [comment]
I'm experiencing the same issue recently

**Comment by geropl** [comment]
@dclong Could it be that you ran into an instance of #890 ?

**Comment by svenefftinge** [comment]
I also got a report for restarting an existing workspace. So no docker build involved.
