### ISSUE TITLE
Email address is not automatically updated when changed in GitHub

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/gitpod#3957]
### Bug description

I changed my email address in GitHub a while ago. But in the Gitpod dashboard, it still shows the old address. The newsletter was sent to the old address as well. 

### Steps to reproduce

Change Email in GitHub, see if it's updated in https://gitpod.io/account

**Comment by AlexTugarev** [comment]
There are two things we need to consider for this issue. Currently we still cannot tell which email address to show if you have connected with two providers. And the other limitation is, that updates are only done on login. 

@ChristinFrohne try to log out and log in again, please. Though there is a chance, that on Account page you see the email address from your other provider connection, if exists.

**Comment by ChristinFrohne** [comment]
@AlexTugarev not sure if you meant logging in and out for Gitpod or GitHub. I tried both, didn't work. It still shows the old address 

>Currently we still cannot tell which email address to show if you have connected with two providers
I'm using the same email address for GitLab and GitHub

**Comment by ChristinFrohne** [comment]
oh, you're right. I didn't remember I used bitbucket before. I disconnected Bitbucket and now the correct email is displayed. 

Thanks! So I guess this issue is solved then. Are you planning to improve the UI so the user can change the email address manually at some point?

**Comment by AlexTugarev** [comment]
> Are you planning to improve the UI so the user can change the email address manually at some point?

Managing email addresses is still missing and crucial for the comms with users. 

@gtsiolis, I cannot find GitHub issues related to our discussion on the https://gitpod.io/account page. Is it still true, that the email address should be made editable at some point?
