### ISSUE TITLE
Unable to install GitPod

### ISSUE THREAD

**Issue by simonjcarr** [gitpod-io/gitpod#3960]
### Bug description

Install instructions do not work.

I have followed the instructions here https://www.gitpod.io/docs/self-hosted/latest/install/install-on-kubernete
There is no context to the instructions

* Do I have to clone the repo first. There is no mention of this
* The command `helm install -f values.custom.yaml gitpod gitpod.io/gitpod --version=0.7.0` 
  * Version 7 does not exist (I have already submitted an issue for this and it has been accepted, but docs still say 0.7.0)
  * `values.custom.yaml` what goes in it? Some areas of the docs say everything has to go in a `values` folder

I have spent about 12 hours now trying to install and all I get are failed containers saying that secrets don't exist, mounts don't exist, although the documentation says `By default, the Helm chart installs a working Gitpod installation in a lot of scenarios`. Obviously not mine. 

I have tried the docker installer as well. That also does not work, similar issues, too many to list.

 Instructions on different pages contradict themselves and many pages in the repo that link to further instructions no longer exist.

I think the docs are so out of date, it requires someone to record an install from start to finish for YouTube to provide some confidence that they are still relevant.

### Steps to reproduce

Ask someone who has never installed GitPod before to follow the install instructions

### Expected behavior

GitPod install Instructions provide clear guidance on how to install GitPod

**Comment by aledbf** [comment]
@simonjcarr apologies for the experience installing gitpod.io self-hosted.
The instructions are being updated in this pull request https://github.com/gitpod-io/gitpod/pull/3925
