### ISSUE TITLE
Segfault in content service

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3962]
> panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xba6730] goroutine 233398 [running]: github.com/gitpod-io/gitpod/content-service/pkg/storage.(*PresignedGCPStorage).DeleteObject(0xc000859900, 0xf0c258, 0xc000a6fa10, 0xc00199a580, 0x35, 0xc001564f98, 0x0, 0x0) github.com/gitpod-io/gitpod/content-service/pkg/storage/gcloud.go:926 +0x8d0 github.com/gitpod-io/gitpod/content-service/pkg/storage.(*PresignedGCPStorage).DeleteBucket(0xc000859900, 0xf0c258, 0xc000a6fa10, 0xc00199a580, 0x35, 0x0, 0x0) github.com/gitpod-io/gitpod/content-service/pkg/storage/gcloud.go:943 +0x1c6 github.com/gitpod-io/gitpod/content-service/pkg/service.(*ContentService).DeleteUserContent(0xc0009d0000, 0xf0c258, 0xc000a6f9e0, 0xc000ad4900, 0x0, 0x0, 0x0) github.com/gitpod-io/gitpod/content-service/pkg/service/content-service.go:44 +0x211 github.com/gitpod-io/gitpod/content-service/api._ContentService_DeleteUserContent_Handler.func1(0xf0c258, 0xc000a6f9e0, 0xd30840, 0xc000ad4900, 0xdf4a67, 0xd, 0xe12707, 0x30) github.com/gitpod-io/gitpod/content-service/api@v0.0.0-00010101000000-000000000000/content_grpc.pb.go:88 +0x89 github.com/grpc-ecosystem/go-grpc-middleware/tracing/opentracing.UnaryServerInterceptor.func1(0xf0c258, 0xc000a6f4a0, 0xd30840, 0xc000ad4900, 0xc000c163e0, 0xc000cf2330, 0x3, 0x3, 0x7f20d00743f0, 0xc000c81320) github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/tracing/opentracing/server_interceptors.go:34 +0x108 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xf0c258, 0xc000a6f4a0, 0xd30840, 0xc000ad4900, 0x30, 0xc000031130, 0x7f20cfeeea38, 0x20) github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63 github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0xf0c258, 0xc000a6f4a0, 0xd30840, 0xc000ad4900, 0xc000c163e0, 0xc000c16400, 0xbad3ba, 0xd4faa0, 0xc000c16420, 0xc000c163e0) github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xb0 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0xf0c258, 0xc000a6f4a0, 0xd30840, 0xc000ad4900, 0xc0007c8400, 0x0, 0xc00046cb30, 0x40e278) github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0xf0c258, 0xc000a6f4a0, 0xd30840, 0xc000ad4900, 0xc000c163e0, 0xc000cf2330, 0xc00046cba0, 0x59dea6, 0xd6e380, 0xc000a6f4a0) github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:34 +0xd7 github.com/gitpod-io/gitpod/content-service/api._ContentService_DeleteUserContent_Handler(0xcd98e0, 0xc0009d0000, 0xf0c258, 0xc000a6f4a0, 0xc000993800, 0xc0009c2810, 0xf0c258, 0xc000a6f4a0, 0xc0015ce510, 0x26) github.com/gitpod-io/gitpod/content-service/api@v0.0.0-00010101000000-000000000000/content_grpc.pb.go:90 +0x150 google.golang.org/grpc.(*Server).processUnaryRPC(0xc000817a40, 0xf146d8, 0xc0002ec480, 0xc0011a6900, 0xc0009c2ea0, 0x13e7980, 0x0, 0x0, 0x0) google.golang.org/grpc@v1.36.0/server.go:1217 +0x52b google.golang.org/grpc.(*Server).handleStream(0xc000817a40, 0xf146d8, 0xc0002ec480, 0xc0011a6900, 0x0) google.golang.org/grpc@v1.36.0/server.go:1540 +0xd0c google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002f8044, 0xc000817a40, 0xf146d8, 0xc0002ec480, 0xc0011a6900) google.golang.org/grpc@v1.36.0/server.go:878 +0xab created by google.golang.org/grpc.(*Server).serveStreams.func1 google.golang.org/grpc@v1.36.0/server.go:876 +0x1fd

https://console.cloud.google.com/logs/query;cursorTimestamp=2021-04-15T20:20:18.148817056Z;query=%22invalid%20memory%20address%20or%20nil%20pointer%20dereference%22%0Atimestamp%3D%222021-04-15T20:20:18.148817056Z%22%0AinsertId%3D%221d41kafff9pv4l%22;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning?project=gitpod-191109

https://console.cloud.google.com/logs/query;cursorTimestamp=2021-04-15T20:02:55.845180954Z;query=%22invalid%20memory%20address%20or%20nil%20pointer%20dereference%22%0Atimestamp%3D%222021-04-15T20:02:55.845180954Z%22%0AinsertId%3D%22w7760hfgm3cdj%22;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning?project=gitpod-191109

https://console.cloud.google.com/logs/query;cursorTimestamp=2021-04-15T19:50:20.386770253Z;query=%22invalid%20memory%20address%20or%20nil%20pointer%20dereference%22%0Atimestamp%3D%222021-04-15T19:50:20.386770253Z%22%0AinsertId%3D%22uj334mfe3m3oz%22;summaryFields=resource%252Flabels%252Fpod_name:false:32:beginning?project=gitpod-191109

**Comment by geropl** [comment]
Closing as dup of https://github.com/gitpod-io/gitpod/issues/4077
