### ISSUE TITLE
It would be good if "Paste" works as expected

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#397]
"Please use the browser's paste command or shortcut." warning error error is displayed after clicking Edit->Paste  or clicking Paste in "Right Click" contex menu

![2019-03-19_13-20-56](https://user-images.githubusercontent.com/41964662/54602274-e4034b80-4a49-11e9-9331-70c9d1830d51.png)

**Comment by svenefftinge** [comment]
Yes, but it is a technical limitation of browsers.

**Comment by flamecopper** [comment]
Ctrl+C and CTRL-V will do the trick
