### ISSUE TITLE
ws-proxy: crash due to "concurrent map iteration and map write"

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3974]
`ws-proxy` crashed in prod with message "concurrent map iteration and map write" and 1k follow-up-logmessages filled with  stacktraces. 

* [Error](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-04-16T10:05:15.924808421Z;query=%2277f4c5758d-c85cb%22%0Aseverity%3DERROR%0Aresource.labels.pod_name%3D%22ws-proxy-77f4c5758d-c85cb%22%0Atimestamp%3D%222021-04-16T10:05:15.921408773Z%22%0AinsertId%3D%221sxugqvfzwgk0k%22;timeRange=2021-04-16T10:05:14Z%2F2021-04-16T10:05:15.930Z?project=gitpod-191109)
* [stacktraces](https://console.cloud.google.com/logs/query;query=%2277f4c5758d-c85cb%22%0Aseverity%3DERROR%0Aresource.labels.pod_name%3D%22ws-proxy-77f4c5758d-c85cb%22;timeRange=2021-04-16T10:05:14Z%2F2021-04-16T10:05:15.930Z;cursorTimestamp=2021-04-16T10:05:15.924808421Z?project=gitpod-191109)

**Comment by meysholdt** [comment]
[happened again](https://console.cloud.google.com/logs/query;query=%0Aresource.labels.pod_name%3D%22ws-proxy-77f4c5758d-c85cb%22%0Aseverity%3E%3DERROR;timeRange=2021-04-16T13:51:31.000Z%2F2021-04-16T13:51:31.500Z;pinnedLogId=2021-04-16T16:57:28Z%2Frqyby1g13fuc3v;cursorTimestamp=2021-04-16T13:51:31.078815467Z?project=gitpod-191109)

**Comment by meysholdt** [comment]
[another one](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-04-16T16:57:27.948117120Z;query=%2277f4c5758d-c85cb%22%0Aseverity%3DERROR%0Aresource.labels.pod_name%3D%22ws-proxy-77f4c5758d-c85cb%22%0Atimestamp%3D%222021-04-16T16:57:27.948038883Z%22%0AinsertId%3D%22tysoukg1d3j7q6%22;timeRange=2021-04-16T16:57:24Z%2F2021-04-16T16:57:27.950000001Z?project=gitpod-191109)

**Comment by csweichel** [comment]
root cause: ![image](https://user-images.githubusercontent.com/3210701/115198356-3e23de80-a0f2-11eb-8a1a-6cbf8840d6ed.png)
