### ISSUE TITLE
"gp init" prints "not found" instead of opening .gitpod.yml

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#3975]
### Bug description

cf. https://community.gitpod.io/t/executing-gp-init-results-in-not-found-message/3303/2

`gp init` might have an issue when `code` is used as IDE.

### Steps to reproduce

run `gp init` without any flags. 
1. it creates the default `.gitpod.yml` file
2. it prints `not found`
3. nothing else happens

### Expected behavior

maybe open the created `.gitpod.yml` file?

### Example repository

any

**Comment by ghuntley** [comment]
Confirming this is currently reproducible
```
gitpod /workspace/repo $ gp init
2021/05/03 02:48:55 not found
gitpod /workspace/repo $ 
```

**Comment by svenefftinge** [comment]
gp init should also not auto create a .gitpod.Dockerfile resp. reference one.

**Comment by ghuntley** [comment]
Thx
