### ISSUE TITLE
[server/metrics] Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#3976]
### Bug description

see https://github.com/gitpod-io/gitpod/pull/3110#discussion_r614814967 for context.

there appears to be an unexpected request made. 

### Steps to reproduce

---

### Expected behavior

---

**Comment by corneliusludmann** [comment]
With #4518 this message should not occur once deployed to production. However, the actual problem could not be solved yet. We should watch for `route is undefined` messages after the deployment of #4518.

**Comment by corneliusludmann** [comment]
In staging, we see the following:

![image](https://user-images.githubusercontent.com/24960040/123601661-3a9a8b00-d7f8-11eb-9f1d-9a4874a5a521.png)

https://cloudlogging.app.goo.gl/iWdXJTKftX9sLvS28 (internal)

**Comment by AlexTugarev** [comment]
I commended here: https://github.com/gitpod-io/gitpod/pull/4518/files#r659578823
