### ISSUE TITLE
[github/prebuild] Error: Repository was archived so is read-only.

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#3978]
### Bug description

There was a cluster of such errors logged in prod.

Maybe the case of archived repositories isn't handled in prebuilds? 🤷🏻‍♂️ 

### Steps to reproduce

---

**Comment by aledbf** [comment]
Still an issue https://cloudlogging.app.goo.gl/R2qpZfNZJLGp8TmK7
