### ISSUE TITLE
[dashboard] Sync theme preference between dashboard and editor

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3982]
### Problem to solve

We recently merged the first iteration of the dark theme for the dashboard in https://github.com/gitpod-io/gitpod/pull/3901. Users can now switch between a dark and light theme for both dashboard and editor.

Currently, the dashboard theme defaults to system default while the editor defaults to a light theme. We could try to sync the theme preference between dashboard and editor as long as the user has never changed the editor theme.

See [relevant discussion](https://gitpod.slack.com/archives/C01KGM9AW4W/p1618590899201400) (internal).

### Proposal

TBD (To be discussed)

**Comment by svenefftinge** [comment]
We could also have a preference in the dashboard that says align with VS Code Theme. I.e. if the user switches to any dark theme in Code it will switch to dark theme in dashboard as well and switching to any light theme in code will switch to light theme in dashboard. 

I don't mean applying the color scheme to the dashboard (as we used to do) but just whether it is dark or light.

**Comment by akosyakov** [comment]
Just fyi we cannot do much in VS Code, only decide which theme should be used by default if a user never touched settings.

**Comment by jankeromnes** [comment]
I agree that the default theme of the dashboard and the default theme of VS Code should probably be the same. (And maybe we don't need to sync changes back-and-forth?)

> Just fyi we cannot do much in VS Code, only decide which theme should be used by default if a user never touched settings.

Ah, then we could also make VS Code use the "System" theme by default, right? (When user never touched the settings.)

You can get it like so:

```js
// Get the value once
const isDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

// Listen to changes
window.matchMedia("(prefers-color-scheme: dark)").addEventListener('change', event => {
    const isDark = event.matches;
});
```

I'd vote for either:
1. "System" default in both dashboard and IDE
2. "Light" default in both dashboard and IDE

**Comment by shaal** [comment]
++ for this feature!

I see it in the dashboard, but I don't think it works affects the theme for a new user that see VSCode interface for the first time.
(I changed my VSCode theme to dark theme, and it remembers that option for me across workspaces).

**Comment by shaal** [comment]
I don't think this is completed yet. Perhaps add `meta: never-stale` ?
