### ISSUE TITLE
[dashboard] Update theme preference selector

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#3984]
### Problem to solve

The first part of the dark theme has been added in https://github.com/gitpod-io/gitpod/pull/3901. However, we are still missing a better styled theme selector.

| Theme Selector |
|-|
| <img width="394" alt="Screenshot 2021-04-16 at 10 51 06 PM" src="https://user-images.githubusercontent.com/120486/115077151-3ef81d00-9f06-11eb-8a90-db2d7a466a4f.png"> |

### Proposal

We could:
1. Update the theme selector style to follow the design language of the rest of the product and make the option more appealing to the user. This could use something like the card component used above in the editor preference.
2. Default to light theme to be less surprising to the user. Preference order could be _Light_, _Dark_, _System_.
3. Update the section design description to something more descriptive or maybe playful like _Early bird or night owl? Choose your side._
4. Consider introducing a secondary option to sync theme between dashboard and editor, see https://github.com/gitpod-io/gitpod/issues/3982#issuecomment-821373982.

### Designs

| Light | Dark |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/115416125-289cda80-a200-11eb-9094-aaa8f85d4d24.png) | ![image](https://user-images.githubusercontent.com/120486/115416136-2aff3480-a200-11eb-9bc0-a76add1ec183.png) |

See also [design specs](https://www.figma.com/file/8zu50RSZudHG3rtV9tzRJI/Theme-Selector-3984?node-id=0%3A1).

**Comment by jankeromnes** [comment]
Looks awesome! ✨ Many thanks @gtsiolis 🙏

Additional thought: Once implemented, it could be nice to just copy/paste this Theme switcher into the "What's New" modal (thus allowing users to switch the Theme directly from What's New). Thoughts? 😇

**Comment by gtsiolis** [comment]
Absolutely @jankeromnes! That was the plan, similarly to what @AlexTugarev did with the account select process in https://github.com/gitpod-io/gitpod/pull/3897. But haven't thought this through yet in terms of how this will scale, and more but it should be fine. 🤷
