### ISSUE TITLE
Could project clone have option for depth/shallow?

### ISSUE THREAD

**Issue by arafalov** [gitpod-io/gitpod#3985]
I assume that when the project is cloned, the full git history is kept. Sometimes, for long-running project, this may be a little overwhelming and not-necessary.

For example, I did a URL start for https://github.com/apache/lucene-solr/tree/branch_8x and the interface timed out several times before I got it to run, install ant, and compile and run Solr server (amazing!).

I wish there was a way to say "#....?shallow=true" or "?depth=10" or even a global setting. I do that for my own local copy, so why not for cloud one too. And it is been quite a while since Git was able to commit back to the branches even if not full history was cloned.

**Comment by gtsiolis** [comment]
Thanks for bringing this up @arafalov! In the past this didn't make any difference (see https://github.com/gitpod-io/gitpod/issues/56) but a lot have chnaged since then. Looping in @csweichel and @svenefftinge in case this is something worth taking another look.

 FWIW, another example project I've seen where shallow cloning helps is [GitLab](https://gitlab.com/gitlab-org/gitlab), see [relevant installation instructions](https://gitlab.com/gitlab-org/gitlab-development-kit/-/blob/main/doc/index.md#install-gdk).

> Use `gdk install shallow_clone=true` for a faster clone that consumes less disk-space. The clone
process uses `git clone --depth=1`.

**Comment by aledbf** [comment]
Closing. After https://github.com/gitpod-io/gitpod/pull/4847 this should not be an issue. This will be available in the next release.
As example
```shell
❯ time git clone https://github.com/kubernetes/kubernetes
Cloning into 'kubernetes'...
remote: Enumerating objects: 1252949, done.
remote: Counting objects: 100% (176/176), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 1252949 (delta 80), reused 61 (delta 61), pack-reused 1252773
Receiving objects: 100% (1252949/1252949), 765.54 MiB | 12.58 MiB/s, done.
Resolving deltas: 100% (902464/902464), done.
real	1m12,387s
user	1m3,651s
sys	0m6,077s
```

```shell
❯ du -sm kubernetes
1101	kubernetes
```

```shell
❯ time git clone --filter=blob:none https://github.com/kubernetes/kubernetes
Cloning into 'kubernetes'...
remote: Enumerating objects: 844143, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 844143 (delta 5), reused 5 (delta 5), pack-reused 844118
Receiving objects: 100% (844143/844143), 146.35 MiB | 13.24 MiB/s, done.
Resolving deltas: 100% (542319/542319), done.
remote: Enumerating objects: 19520, done.
remote: Counting objects: 100% (14373/14373), done.
remote: Compressing objects: 100% (11302/11302), done.
remote: Total 19520 (delta 5976), reused 3071 (delta 3071), pack-reused 5147
Receiving objects: 100% (19520/19520), 34.89 MiB | 7.05 MiB/s, done.
Resolving deltas: 100% (7288/7288), done.
Updating files: 100% (23197/23197), done.
real	0m34,297s
user	0m9,171s
sys	0m5,286s
```

```shell
❯ du -sm kubernetes
508	kubernetes
```

**Comment by gtsiolis** [comment]
Thanks @aledbf for closing this and adding https://github.com/gitpod-io/gitpod/pull/4847! 🚀
