### ISSUE TITLE
Admin->Workspace Search should be able to search based on workspace names/IDs

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3992]
Today we can search based on context URL.

However, in support requests and log messages we often don't get that information. 

It would be awesome if the search could find the workspaces based on basically any unique identifier:
* workspaces name (e.g "pink-teddybear-1245") aka workspace-ID
* instance-UUID

**Comment by mads-hartmann** [comment]
I'll be looking into this as an onboarding ticket over the next couple of days :)

**Comment by mads-hartmann** [comment]
When this is done we should also update the NodeFilesystemAlmostOutOfSpace runbook

**Comment by JanKoehnlein** [comment]
Is that ready for a PR?

**Comment by mads-hartmann** [comment]
@JanKoehnlein I have an open PR here https://github.com/gitpod-io/gitpod/pull/4111 but it's missing a review ☺️
