### ISSUE TITLE
Npm packages globally installed deleted on new container

### ISSUE THREAD

**Issue by u9g** [gitpod-io/gitpod#3999]
### Bug description

The vsc plugin standard requires standard to be installed with npm, so I install it globally, but it doesnt persist through reboots so i have to reinstall every time I make a container.

### Steps to reproduce

1. `npm i -g standard`
2. make a new container

### Expected behavior

globally packages persisted?

### Example repository

there's no need

**Comment by smacintyre** [comment]
This is actually a feature :) 

Each workspace is a clean space so you can experiment to your heart's content and not worry about messing up other environments.

If you want to persist changes you just need to specify a Dockerfile or docker image in your `gitpod.yml`. That is how you can configure the "starting point" if a repo's workspaces. See: https://www.gitpod.io/docs/config-docker
