### ISSUE TITLE
Search does not show any results if search words match the file name

### ISSUE THREAD

**Issue by tarasdidyk** [gitpod-io/gitpod#400]
Description:
Search does not show any results if search words matche the file name

Steps:

1. Login to the site
2. Start some workspace
3. Click View->Search
4. Submit the name of any existing file to the search field 
5. Pay attention to the search results

Actual result:  Search does not show any results if search words match the file name
![2019-03-19_16-56-43](https://user-images.githubusercontent.com/41964662/54617134-6ea77300-4a69-11e9-8447-f20d9595c1f2.png)

Expected result: Files can be found in search if search words match the file name

Win 10 Google Chrome 72.0.3626.121
Win 10 Firefox 65.0.2

**Comment by svenefftinge** [comment]
That's expected. Press CTRL+P to search file by name.
