### ISSUE TITLE
[self-hosted][feature-request] Allow setting the affinity of components

### ISSUE THREAD

**Issue by cyrilcros** [gitpod-io/gitpod#4003]
Currently, Gitpod doesn't directly allow to set on which nodes he various components run. It has:
 - a `sessionAffinity`  parameter in the helm `values.yaml` that's undocumented and more relevant to routing/tracing issues
 -  labels like `gitpod.io/workload_workspace` that are in the documentation but have no effects on the chart. They don't show up in the templates

Ideally, users should be able to control which nodes are running the various components of gitpod, and restrict the daemonsets like  `registry-facade` or `ws-daemon` to a few nodes only.

Suggestions:
- make the label system actually work. 
- **better:** add an `affinity` entry to each component.

PS: that used to be a thing in older versions? See https://github.com/gitpod-io/self-hosted/blob/master/values/node-affinity.yaml

**Comment by corneliusludmann** [comment]
You can use something like in this [[1]](https://github.com/gitpod-io/gitpod/blob/5431d5735c32ab7d5d840a4d1a7d7c688d1f0ce9/install/docker/examples/gitpod-3-nodes/values/node-affinities.yaml) file to schedule every meta pod to `gitpod.io/main-node` nodes and every workspace to `gitpod.io/workload_workspace` nodes. Is that what you're asking for?

[1] https://github.com/gitpod-io/gitpod/blob/5431d5735c32ab7d5d840a4d1a7d7c688d1f0ce9/install/docker/examples/gitpod-3-nodes/values/node-affinities.yaml

**Comment by cyrilcros** [comment]
@corneliusludmann That would definitely work, but it isn't documented in the docs: https://www.gitpod.io/docs/self-hosted/latest/install/nodes
