### ISSUE TITLE
Gitpod launching keep at "Allocating resources..."

### ISSUE THREAD

**Issue by kk86bioinfo** [gitpod-io/gitpod#4005]
### Bug description

Gitpod IDE not able to run and keep at "Allocating resources...".

### Steps to reproduce

Launch a gitpod runtime, it is stucked at "Allocating resources...".

### Expected behavior

Gitpod instance should run into IDE.

**Comment by smacintyre** [comment]
See the same thing here. It seems all of Gitpod is down again.

**Comment by Thunderducky** [comment]
Same

**Comment by svenefftinge** [comment]
Sorry, to let you down once more. We have resolved the issue and are now investigating the cause.
