### ISSUE TITLE
Cant Open my gitpod

### ISSUE THREAD

**Issue by fullmoon-sg** [gitpod-io/gitpod#4006]
### Bug description

This error message after I tried to open my gitpod 

"Oh, no! Something went wrong!
container workspace completed; containers of a workspace pod are not supposed to do that"

My gitpod name is "beige-orca-orq15k9f". 

### Steps to reproduce

Login in to Gitpod. 

Click the my project name

### Expected behavior

My Reactjs coding

**Comment by smacintyre** [comment]
Yup, all gitpod seems to be down again. I can't open open anything either this morning.

**Comment by svenefftinge** [comment]
Sorry, to let you down once more. We have resolved the issue and are now investigating the cause.

**Comment by djsnipa1** [comment]
I’m having this exact same issue with all my workspaces. Anyone know why?

**Comment by zhaogeyinzuo** [comment]
me too

**Comment by axonasif** [comment]
Hey @Karreg, alpine based images are not supported at the moment.
Ubuntu and/or debian should do fine.

Please see https://github.com/gitpod-io/gitpod/issues/3356, feel free to share your thoughts on it.

**Comment by Karreg** [comment]
Hello @axonasif 
I managed to fix it indeed by having multiple looks at the documentation and switching to a gitpod image as base image. It's now working fine.
That's just too bad the error message is not helping understand the issue.
It's still possible to install the dependencies in alpine images though. I will try this someday, in an endeavor to use the same code base for gitpod and devcontainer... Until gitpod manages devcontainer ;)
Thanks.

**Comment by axonasif** [comment]
> Hello @axonasif I managed to fix it indeed by having multiple looks at the documentation and switching to a gitpod image as base image. It's now working fine. That's just too bad the error message is not helping understand the issue. It's still possible to install the dependencies in alpine images though. I will try this someday, in an endeavor to use the same code base for gitpod and devcontainer... Until gitpod manages devcontainer ;) Thanks.

Glad you figured it out already, and yeah, it would be nice to have a better error message there. I just shared that on the linked issue above :)
