### ISSUE TITLE
All workspaces are being deleted 

### ISSUE THREAD

**Issue by victormgomezp** [gitpod-io/gitpod#4009]
### Bug description

Workspaces are being deleted same day, my students had oppended a worskpace on friday and today is not on the list of workspaces, before updating this was different

### Steps to reproduce

open a worksapce in gitpod

**Comment by jankeromnes** [comment]
Hi @victormgomezp! Sorry for the confusion here.

Are the workspaces visible when you change `Filter` to `All` in https://gitpod.io/workspaces ?

**Comment by victormgomezp** [comment]
Yes they told me that they have applied this filter, but nothing.

I am not sure if this is important but before updating they had their workspaces pinned.

**Comment by JanKoehnlein** [comment]
I am not sure this issue persists?

**Comment by victormgomezp** [comment]
Let me check with students but i think is ok now.
