### ISSUE TITLE
clone of repository failes

### ISSUE THREAD

**Issue by mitra** [gitpod-io/gitpod#401]
**Describe the bug**
Tried to open a private repository part of an organization in gitpod it failed with "failed to clone"

https://gitpod.io/#https://github.com/CacheboxInc/hyc-storage-layer

A video of what is going wrong is here.
https://drive.google.com/open?id=1TxZXipqRABVgvgMeKe_kYMxxTYaosgTf

**To Reproduce**
Steps to reproduce the behavior.

https://gitpod.io/#https://github.com/CacheboxInc/hyc-storage-layer

**Expected behavior**

should have open like the other repositories see video below.

https://drive.google.com/open?id=1s9ek6R7NS2aV3TNZp7FwP-_ken54p-hk

**Comment by AlexTugarev** [comment]
@mitra, thanks for reporting! As this repo is private, please check if it has submodules with ssh-git urls. Currently Gitpod supports only authentication with https for git.

**Comment by 32leaves** [comment]
Thank you for reporting this ... workspaces should be resilient against failing submodule inits. We're working on a fix.

**Comment by mitra** [comment]
yes it does have ssh-git urls.  Is there are workaround I could use ??

**Comment by mitra** [comment]
It is fine if the workspace is presented to me minus the git submodules. Is it possible to configure this behaviour?

**Comment by 32leaves** [comment]
We have just deployed a fix that should still open a workspace in this case, albeit without submodules.
@mitra could you give it another try and see if things work for you now?

**Comment by svenefftinge** [comment]
@mitra please reopen the issue (or comment) if you still see this not working.
