### ISSUE TITLE
[ws-scheduler] - Ensure it respects cordoned nodes.

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#4016]
While solving today's incident, we noticed that pods were still being scheduled to cordoned nodes. It may not be a bug on ws-scheduler since we couldn't identify the reason for that, but we'd like to investigate a little bit further and make sure there is no bug  on this logic.

---
[Post-mortem action item](https://www.notion.so/gitpod/Workspaces-cannot-be-started-in-US-22aeabec4bb94ea381cb68536eb49801)

**Comment by geropl** [comment]
This has been verified and works as expected: no workspaces are scheduled onto cordoned nodes.
