### ISSUE TITLE
Download option for folder

### ISSUE THREAD

**Issue by drago008** [gitpod-io/gitpod#4019]
i want to revive the download option for folders/directories in gitpod, it was there but after sometime removed .. kindly help.

**Comment by corneliusludmann** [comment]
Do you use VSCode or Theia? (see https://gitpod.io/preferences)

In VSCode, I'm able to download a folder by right click and choose `Download ...`. It asks for a local folder to save the files to.

**Comment by drago008** [comment]
i use VSCode in gitpod .. but option to download folder/directory not showing .. i have to select individual files to download them ..

**Comment by akosyakov** [comment]
Which operating system and browser? it would be good to know exact versions. You can get in VS Code: File -> About and then copy content.

**Comment by drago008** [comment]
Version: 1.48.0 (user setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:06.060Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT ia32 6.1.7601

**Comment by drago008** [comment]
[
![Capture](https://user-images.githubusercontent.com/50899240/115904117-0adea800-a482-11eb-8214-803f405fc63c.PNG)
](url)

**Comment by drago008** [comment]
![Capture](https://user-images.githubusercontent.com/50899240/115904155-15993d00-a482-11eb-827b-f2be93e703eb.PNG)

**Comment by drago008** [comment]
[https://ibb.co/Syk0wtP](url) screenshot of gitpod where download option was available but not now.
