### ISSUE TITLE
Ports detecting

### ISSUE THREAD

**Issue by farrelleoin93** [gitpod-io/gitpod#4022]
### Bug description

Hey, 
I am having an issue where the ports are just detecting. 
![ports](https://user-images.githubusercontent.com/70948100/115437244-dbbb0300-a203-11eb-82d7-a872e8cfb9d2.JPG)

### Steps to reproduce

I have tried reloading the browser but it hasn't helped. Any advice would be appreciated

**Comment by corneliusludmann** [comment]
Thanks for the report. Does it still happen?

For investigating this case we need your workspace ID (part of the URL).

**Comment by akosyakov** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/3160
