### ISSUE TITLE
[self-hosted] Release docs not found

### ISSUE THREAD

**Issue by soniasingla** [gitpod-io/gitpod#4023]
### Bug description

While going through release docs of [v0.80](https://github.com/gitpod-io/gitpod/releases/tag/v0.8.0) & also for the other releases, it's linking to `500` error! 

Link to Self Hosted Docs - https://www.gitpod.io/docs/self-hosted/latest/self-hosted

### Steps to reproduce

https://github.com/gitpod-io/gitpod/releases

**Comment by mikenikles** [comment]
Hi, the following versions are currently deployed:
* latest
* 0.5.0
* 0.4.0
* 0.3.0

Could you let me know what OS and browser you use 🙏? I'm curious to figure out what causes the 500 error in your case.

**Comment by soniasingla** [comment]
I am using Firefox browser and m1 Macbook pro machine! 

Let me know if you need any more details :)

**Comment by mikenikles** [comment]
Quick update on that, it is an intermittent issue that affects the docs. I'm working on a fix in the `gitpod-io/website` repo, but need a bit more time to get to the bottom of it.
