### ISSUE TITLE
[theia] installing big extensions is broken

### ISSUE THREAD

**Issue by avidcoder123** [gitpod-io/gitpod#4025]
### Bug description

Whenever I try to install the Svelte extension, I get the error
`Failed to share svelte.svelte-vscode@104.9.1 extension from svelte.svelte-vscode34A05RZoSB4drB.vsix. Try to upload again.`.
This does not happen with any other extention.extension

### Steps to reproduce

Install the official Svelte extention.

### Expected behavior

The extension should download normally.

**Comment by axonasif** [comment]
Are you using `Theia` IDE?
I had no issues with installing `Svelte` over VSCODE.
![image](https://user-images.githubusercontent.com/39482679/115488113-cc779c00-a27b-11eb-9bbe-4ff8db02f565.png)

FYI, `VSCODE` would be adapted as the default IDE on gitpod in the future and probably `Theia` would be dropped --- from what I see here: https://github.com/gitpod-io/gitpod/issues/3989#issuecomment-822246441

**Comment by akosyakov** [comment]
The same was reported for Java extension: https://community.gitpod.io/t/java-language-support-can-not-be-installed/3229

**Comment by akosyakov** [comment]
We are going to fix in April milestone, but pleas start switching to VS Code. In the long run Theia will go away, see: https://github.com/gitpod-io/gitpod/issues/3475#issuecomment-801020229
