### ISSUE TITLE
Sluggish performance and high load averages

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#4032]
### Bug description

Right now Gitpod is performing extremely sluggishly, almost to the point of not being usable. Commands that normally take seconds are taking minutes. The UI can't keep up with changes of make suggestions. This has been ongoing for a couple hours now.

Load averages are usually 50+ for new workspaces and they quickly go 100+:
`22:23:23 up  2:22,  0 users,  load average: 106.93, 112.06, 118.72`

### Steps to reproduce

Open any new workspace

### Expected behavior

Not be so slow.

**Comment by corneliusludmann** [comment]
Thanks for reporting. I'll have a look.

**Comment by corneliusludmann** [comment]
It seems that there are some users that abuse Gitpod. We are working on it. Thanks for your patience.

**Comment by corneliusludmann** [comment]
@smacintyre Thanks again for reporting. We blocked a user that abuses Gitpod and produces high CPU loads. According to our monitoring, the situation should be resolved. However, we still have an eye on it.

I'll close this issue for now. Please let me know if it happens again.

**Comment by smacintyre** [comment]
@corneliusludmann Thank you! Much better now

New load averages: `23:03:10 up  3:02,  0 users,  load average: 0.66, 10.40, 45.71`

Coming down quick! 👍🏼
