### ISSUE TITLE
Unsubscribing to the newsletter without logging in is not possible

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#4035]
### Bug description

>When trying to unsubscribe, I'm forced to login, that's unacceptable -
I didn't ask to be on this list, and I don't wish to create an account.

### Steps to reproduce

unsubscribe for the last newsletter

**Comment by gtsiolis** [comment]
Sounds legit. Thanks for opening this @ChristinFrohne!

**Comment by gtsiolis** [comment]
Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/4761 which contains more information. Cc @ChristinFrohne
