### ISSUE TITLE
Search Workspaces Filter and Limit always default to "Active" and "50" respectively

### ISSUE THREAD

**Issue by HobDev** [gitpod-io/gitpod#4039]
The web service should remember the user choice. But it does not do so with Workspace search functionality. I want to keep the Filter to "All". But it revert to "Active" after each refresh.

**Comment by gtsiolis** [comment]
Hey @HobDev! I've moved this to the relevant project issue tracker. Thanks for bringing this up! Will take this into account while improving other aspects of the filters and search like https://github.com/gitpod-io/gitpod/issues/3823 and https://github.com/gitpod-io/gitpod/issues/3638.
