### ISSUE TITLE
gitpod/workspace-base starts with error in terminal

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#4044]
### Bug description

initial terminal output:

    ls: cannot access '/home/gitpod/.bashrc.d/*': No such file or directory
    gitpod /workspace/test46 $ 

### Steps to reproduce

https://github.com/markfirmware/test46

### Expected behavior

No errors in terminal

### Example repository

https://github.com/markfirmware/test46

### Anything else?

FYI I intend to build base-vnc instead of full-vnc, then repeat this using bionic instrad of focal.

**Comment by markfirmware** [comment]
Any progress? It would help me to know whether this is an abstract image, intended to be used only in a docker file and not intended to be used in .gitpod.yml.

**Comment by corneliusludmann** [comment]
It's this line:

https://github.com/gitpod-io/workspace-images/blob/409e1707b3cbe6752a894893cd6354fc13d7b8f5/base/Dockerfile#L54

There should be a check if there is at least one file in `/home/gitpod/.bashrc.d` before the loop.

_Note: This error can usually be safely ignored._

**Comment by jordanhailey** [comment]
Hey, @corneliusludmann, Would you like me to add the following `if` block to the Dockerfile? I can open an issue in that repo and submit the PR if so.

Changes proposed:
- From what I understand, I believe the default behavior of `mkdir` is to throw an error similar to what is noted in this issue if any intermediate directories are missing in the path. So I would add the `-p` (`--parent`) flag to the `mkdir` command to create the directory path `/home/gitpod/` if it is not already existing. 
  > **NOTE**: The [man pages for mkdir](https://man7.org/linux/man-pages/man1/mkdir.1.html) note that the `-p` flag will raise no error if the path exists, so if you would rather it did encounter an error I will take that out and also wrap the entire command in another `if` block.
- Wrap the `for` loop with a conditional to ensure there are files present in `$HOME/.bashrc.d`

e.g.
```diff
# use sudo so that user does not get sudo usage info on (the first) login
RUN sudo echo "Running 'sudo' for Gitpod: success" && \
    # create .bashrc.d folder and source it in the bashrc
-    mkdir /home/gitpod/.bashrc.d && \
+    mkdir -p /home/gitpod/.bashrc.d && \
+    if [ "$(ls -A $HOME/.bashrc.d)" ]; then
      (echo; echo "for i in \$(ls \$HOME/.bashrc.d/*); do source \$i; done"; echo) >> /home/gitpod/.bashrc
+    fi
```

**Comment by markfirmware** [comment]
.

**Comment by progmatic-99** [comment]
Created a [PR](https://github.com/gitpod-io/workspace-images/pull/483)
