### ISSUE TITLE
Websocket connections no longer work

### ISSUE THREAD

**Issue by Artur-** [gitpod-io/gitpod#4047]
### Bug description

A Vaadin application in development uses a websocket connection to provide live reload capabilities. The live reload server listens to port 35729, which is indicated in the lower right corner in the Gitpod UI: `Ports: 33411, 35729, 3799, 8080, 45049`.

Port 35729 should be mapped to e.g.
```
$ gp url 35729
https://35729-jade-turkey-nd11myav.ws-eu03.gitpod.io
```

However, establishing a connection to `wss://35729-jade-turkey-nd11myav.ws-eu03.gitpod.io/` fails without any other information in the browser console than `WebSocket connection to 'wss://35729-jade-turkey-nd11myav.ws-eu03.gitpod.io/' failed`.

An additional note is that a websocket connection is also established to `wss://8080-jade-turkey-nd11myav.ws-eu03.gitpod.io/vaadinServlet/?v-r=push&refresh_connection` and this one works properly

### Steps to reproduce

1. Open http://gitpod.io/#https://github.com/vaadin/skeleton-starter-flow-spring
2. Wait for the app to be shown (a text field and a button) 

### Expected behavior

The dev mode indicator in the lower right corner has a full green circle, not a half red half green.

The browser console has no errors

### Example repository

https://github.com/vaadin/skeleton-starter-flow-spring

### Anything else?
This has worked before

**Comment by akosyakov** [comment]
It is reproducible only in VS Code right? not in Theia?

**Comment by Artur-** [comment]
Same problem with Theia

**Comment by yyoncho** [comment]
I am having the same issue when trying to display gtk apps via [Broadway](https://developer.gnome.org/gtk3/stable/gtk-broadway.html)

**Comment by yyoncho** [comment]
Just want to mention that in some cases websockets work fine. I have a demo using https://github.com/xtermjs/xterm.js/ with powered by websocket connection and it works fine. On the other side, gdk broadway does not work. You could reproduce it  sing gitpod/workspace-full - type `broadwayd :5` which will open port 8085 then in the browser console you will see an error for unable to connect.

**Comment by svenefftinge** [comment]
Can you share an example repo with gdk/broadway?

**Comment by svenefftinge** [comment]
Although I was able to reproduce both cases I couldn't figure out what causes the issue. Seems like ws-proxy has issues with the websocket server's response as it logs.
```
"could not connect to backend /: EOF"
```
And the returns 404.

**Comment by akosyakov** [comment]
@Artur- Could you file an issue for spring-boot to treat http headers case-insensitive?
@yyoncho there is already a merge request for broadwayd: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/2894

**Comment by Artur-** [comment]
Sorry, but that makes little sense to me. It would be in the form of "That guy over there said that headers are treated incorrectly in some case in Spring Boot. If you want more info, ask that guy over there. I am just trying to use their IDE". Of course I can do it but filing an issue with relevant details sounds like it has much higher odds of getting fixed.

**Comment by akosyakov** [comment]
ok, filed an issue: https://github.com/spring-projects/spring-boot/issues/26811

**Comment by yyoncho** [comment]
@akosyakov thank you, I will test with a version having that fix and I will let you know.

**Comment by yyoncho** [comment]
@akosyakov  will  #4419 be sufficient to avoid the issue? It seems like that gitpod does not support ubuntu:21.04 which contains the broadway fix, thus I was unable to test.

**Comment by akosyakov** [comment]
@yyoncho yes

**Comment by yyoncho** [comment]
> @akosyakov thank you, I will test with a version having that fix and I will let you know.

Broadway works fine using the latest gitpod deployment. Thank you!

**Comment by francislavoie** [comment]
https://github.com/spring-projects/spring-boot/pull/26813 is now merged, so the issue with spring-boot should be resolved.
