### ISSUE TITLE
Shutdown/teardwon tasks analogue to start tasks?

### ISSUE THREAD

**Issue by timonbimon** [gitpod-io/gitpod#4055]
Hi there :) 

Is there a way to execute a command when a workspace gets shut down now?

Two use case where it would come in very handy for me:
- I am spinning up the app I'm developing on a separate Kubernetes namespace on an Azure cluster with a start task. I'd like to delete all of that again when the workspace gets shut down.
- I'd like to sync my command history on shutdown, so that I can download it again if another workspace gets started somewhere (to jumpstart the history that a reverse search like fzf has access to and make Gitpod even more like my local dev environment)

There is this [design doc](https://github.com/gitpod-io/gitpod/issues/1961) that seems related but has been closed.
Or if it's not a shutdown/teardown task... do you have other ideas for how to implement those two use-cases above?

Thanks in advance!

**Comment by svenefftinge** [comment]
It is still planned but without a concrete ETA. 
The design doc for it is [here](https://www.notion.so/gitpod/Teardown-Command-0b1cdd2675994c4ca5e2baf416f92e8c)

**Comment by svenefftinge** [comment]
duplicate of #3966
