### ISSUE TITLE
Multiple gitlab (or github) accounts

### ISSUE THREAD

**Issue by rmchale** [gitpod-io/gitpod#4058]
I have multiple private gitlab accounts that I use.  Would it be possible to work with multiple gitlab accounts?

**Comment by akosyakov** [comment]
I think it is supported, you should be able to configure additional gitlab accounts for your Gitpod account here: https://gitpod.io/integrations

cc @AlexTugarev

**Comment by rmchale** [comment]
From what I see if you have hosted gitlab there's only 1 integration per provider.

**Comment by gtsiolis** [comment]
Hey @rmchale! Yes, you're right! We currently support only one connection per git provider. Currently, there's no plan to support more account per each provider.

**Tip**: You could use environment variables for setting git author name and email for specific projects using scopes, which could help in your case. 💡

**Comment by AlexTugarev** [comment]
I was quite undecided about this feature request for a while now. I just tried to think it though, and see how far this goes. 

For some parts of the dashboard and the IDE (supervisor-ui?) it's possible to introduce the "current profile" flag. Given that Gitpod is authorizing with OAuth2, the external service would be a potential selector for the state. Connecting to an additional profile of the same kind, would mean that the user is responsible to log in into a different (e.g. GitLab) account. 

There are also caveats to that story:
1. (UX) Selecting token and identity for git operations isn't possible. Some background: git asks for username+password for a hostname in a synchronous way. Intercepting with any UI is problematic (and only reasonable for letting the user allow to return at all.)
2. (prebuilds) 🤷🏻‍♂️ unclear how to select the "current profile" for prebuilds. 
3. (UX) If there will be a manual switch for the "current profile", it might lead to situations where the login state on e.g. gitlab.com is different to the "current profile". Following links from PR/MR extensions in the IDE to the e.g. gitlab.com would be weird.

If the demand is little, it might be just the best option to have two distinct Gitpod accounts.
