### ISSUE TITLE
The video in the browser extension store uses the old Gitpod branding

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#4061]
### Bug description

<img width="1223" alt="2021-04-26_12-17-01" src="https://user-images.githubusercontent.com/127353/116020461-a726cb80-a689-11eb-80da-a8094d1a4e0d.png">

### Steps to reproduce

https://chrome.google.com/webstore/detail/gitpod-dev-environments-i/dodmmooeoklaejobgleioelladacbeki?hl=en

### Expected behavior

.

### Example repository

.

### Anything else?

.

**Comment by pawlean** [comment]
I'll add this to my list of videos to re-create. 👍🏼

**Comment by pawlean** [comment]
I can't close this issue, but it's done. @ghuntley can you close it for me?
