### ISSUE TITLE
Gitpod Extension warning that I have to grant necessary permissions

### ISSUE THREAD

**Issue by pattacini** [gitpod-io/gitpod#4062]
### Bug description

When I git-push to a GitHub repository from a Gitpod workspace I get the following warning popping up in the bottom right corner, although the push operation completes successfully.

![image](https://user-images.githubusercontent.com/3738070/116051179-991c7f00-a678-11eb-8fd1-e8d87a56dd81.png)

In fact, my Gitpod settings are already all set properly.

![image](https://user-images.githubusercontent.com/3738070/116051375-d1bc5880-a678-11eb-983b-da513d54f752.png)

The weird thing is that this happens only for certain repositories.

### Steps to reproduce

Fork https://github.com/icub-tech-iit/documentation and proceed with a push from the workspace.

See for example the video below:

https://user-images.githubusercontent.com/3738070/116051872-5d35e980-a679-11eb-8587-6e7037b16533.mp4

### Expected behavior

The pop-up message should not appear.

### Example repository

The repository where the pop-up message appears:
- https://github.com/icub-tech-iit/documentation.

A repository where everything runs smoothly:
- https://github.com/vvv-school/tutorial_cartesian-interface.

**Comment by asthomasdk** [comment]
I get the same issue using Gitlab.

**Comment by JanKoehnlein** [comment]
We are using `pstree` in our git credential helper which is not installed in @pattacini's repo. So it fails to extract the repository's URL.

**Comment by pattacini** [comment]
Great! Thanks for the fix!
Looking forward to seeing it deployed.
