### ISSUE TITLE
`gp open <filename>` has problems with tab completion

### ISSUE THREAD

**Issue by pattacini** [gitpod-io/gitpod#4064]
### Bug description

In some repositories, I have been experiencing problems while using tab completion alongside the command `gp open <filename>`.

The weird thing is that tab completion works as expected in some repositories and in some others not.

### Steps to reproduce

Fork https://github.com/icub-tech-iit/documentation and proceed with a push from the workspace.

A video of the problem below.

https://user-images.githubusercontent.com/3738070/116054068-9b340d00-a67b-11eb-842d-eecceebe2f53.mp4

### Expected behavior

Tab completion should work correctly.

### Example repository

The repository where I'm getting the problem:
- https://github.com/icub-tech-iit/documentation.

A repository where everything runs smoothly:
- https://github.com/vvv-school/tutorial_cartesian-interface.

### Anything else?

Somehow related to #4062.

**Comment by akosyakov** [comment]
It seems to be the issue with the image which you use. Please try https://computingforgeeks.com/how-to-fix-get-comp-words-by-ref-command-not-found/

**Comment by pattacini** [comment]
Thanks a lot @akosyakov.
Fixed via https://github.com/icub-tech-iit/documentation/commit/adf5e583eebe02362e19cbe50d9e36ea3c096a95.

I didn't think about that in the first place as I had the impression that in the past it wasn't even necessary to explicitly install `bash-completion`.
