### ISSUE TITLE
Error when running prebuild

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#4067]
### Bug description

I tried adding an initial Gitpod setup to the Blender project.
When trying to run a prebuild using contextual URL it fails with error message.

### Steps to reproduce

Open this link in a browser:
https://gitpod.io/#prebuild/https://github.com/blender/blender/pull/25

### Expected behavior

Opening that link should run prebuild that would compile files.

### Example repository

(I don't know what is the cause of this error, so I couldn't create a minimal, reproducible example)

### Anything else?

Screenshot + console errors:
![image](https://user-images.githubusercontent.com/22901/116076033-b72ab500-a661-11eb-95b1-9536f15d5572.png)

**Comment by jankeromnes** [comment]
Hi @shaal!

> I tried adding an initial Gitpod setup to the Blender project.

Wow, that's awesome! 💯 I'm totally on board for helping you make this work. 🚀

> Open this link in a browser:
> https://gitpod.io/#prebuild/https://github.com/blender/blender/pull/25

I'm not sure yet what that error message is about, but I notice in your Pull Request that there is no `.gitpod.yml`. I would assume one is needed (at least to point to the custom Dockerfile, as Gitpod won't automatically detect it).

At first glance I think you want a setup like this:

- `.gitpod.yml`:

```yml
image:
  file: .gitpod/Dockerfile
```

- `.gitpod/Dockerfile`

```Dockerfile
FROM gitpod/workspace-full

# etc.
```

> cannot take snapshot: rpc error: code = FailedPrecondition desc = workspace is not ready

> Error: Workspace blue-unicorn-30ho1y2y has no running instance

Hmm. I'm not yet sure what these errors mean exactly. Also, I couldn't reproduce them: Opening your PR in Gitpod gives me a working but unconfigured environment (i.e. the Dockerfile wasn't built):

<img width="1440" alt="Screenshot 2021-04-26 at 14 43 58" src="https://user-images.githubusercontent.com/599268/116084593-405fdd00-a69e-11eb-9fb9-411716c97744.png">

Maybe your PR has changed in the meantime?

**Comment by jankeromnes** [comment]
Ah, heads up, your latest commit deletes `.gitpod.yml`. That looks unintended:

<img width="1247" alt="Screenshot 2021-04-26 at 14 48 14" src="https://user-images.githubusercontent.com/599268/116084876-84eb7880-a69e-11eb-8522-8c528982f3da.png">

**Comment by shaal** [comment]
Yes, thank you for that. When I renamed it to the correct filename `.gitpod.yml`, the gitignore setting ignored it, so I updated it in the latest commit. 

Now I see "prebuild in progress"
![image](https://user-images.githubusercontent.com/22901/116089037-71c1b400-a670-11eb-9b3b-f714571d9688.png)

**Comment by JanKoehnlein** [comment]
Does it terminate? Can we close this issue?

**Comment by shaal** [comment]
Sorry, yes, thank you @JanKoehnlein ! 
Closing the issue now.
