### ISSUE TITLE
Contact form is not working

### ISSUE THREAD

**Issue by legezam** [gitpod-io/gitpod#4075]
### Bug description

I was trying to enroll the private beta in the contact form here and i was unable to do so: https://www.gitpod.io/contact
Upon hitting the submit button, nothing happens.
Tried in Firefox and Chrome.

### Steps to reproduce

Just visit the contact form, select the enrollment to private beta, give your details, hit submit.

### Expected behavior

Some kind of acknowledgement that tells the submission was either successful or not.

**Comment by JanKoehnlein** [comment]
This seems to be fixed in them meantime. Please reopen if the bug persists.
