### ISSUE TITLE
Add Prettier support

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#408]
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by Eliav2** [comment]
it seems that the formatting is not done with prettier no matter what you configure, Someone succeeded in configure and using prettier on a gitpod?

**Comment by akosyakov** [comment]
@Eliav2 Could you share your project? Also make sure that you are using VS Code now not Theia: https://gitpod.io/preferences

**Comment by Eliav2** [comment]
This was exactly the problem! Thank friend
(for anyone else go to preferences in gitpod and change defult ide)
