### ISSUE TITLE
[Gitpod Code] Add a notification on Pull Requests that asks for opening the PR-Overview

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#4081]
Currently, the button to open the "PR Review View" is hidden:
 - in the "PR View"
 - under an icon (top row) that is not very descriptive
 - invisible by default, until you hover above it

Without the "PR- Review View" you cannot "Submit review".

It would be nice if it'd be easier to find that view, be it with an button on the bottom bar or a notification.

**Comment by akosyakov** [comment]
I think it affects first time users a lot, since they don't know that they have to grant access to GHPR extension.

**Comment by csweichel** [comment]
![image](https://user-images.githubusercontent.com/3210701/127148058-b21037e0-c294-446f-b2ce-24f1e333b20f.png)

I cannot reproduce the issue, but may have given the correct scopes already.
We're also rather full on the scheduled work. I'll remove this from groundwork right now. Please re-add when there's a bit more space.

**Comment by JanKoehnlein** [comment]
After trying a lot of things without success, @akosyakov and me decided to leave it for now.

The main use-case is that a newcomer coming from a GitHub PR who hasn't granted the necessary scopes to GitHub for the GH PR extension yet ('read:user', 'user:email', 'repo') will have no hint where to start. The best way would be to make them sign up and then open the GH PR view (the detail view with the single PR not the master showing all PRs). Here's why that's so complicated

- The GH PR extension seems to assume you start from the master view (showing all PRs) while Gitpod's context is a single PR.
- When programmatically opening the detail view (e.g. by adding a `true` arg to the `github.api.preloadPullRequest` command, or by via the `workbench.view.extension.github-pull-request` command) you have to make sure some other background jobs, like UI state sync, don't override the view selection. That also holds if you are tying that to a button, e.g. in a notification.
- The `pr.signin` command, that's used in the views and the popup messages of the GH PR extension, doesn't properly initialize the views when called from our extension. Views get stuck in "loading". `pr.signinAndRefreshList` doesn't work either.
- We can detect whether we are signed up to GitHub with the correct privileges (using `!!vscode.authentication.getSession('github', [scopes])`) but when we add the `{ createIfNone: true }` argument, the call never returns even if the user has correctly masters the signup flow.
- Testing is extremely tedious. Everything behaves differently when started from a `gitpod-io/vscode` workspace or in a preview environment. Also there is lot of state (UI state, extension authentication, etc.) that is kept in various locations (server, browser, etc) which is reloaded under certain conditions. 

So it seems the GH PR extension just doesn't provide the API to do that.
