### ISSUE TITLE
VS CODE synced settings get reset when accessing a workspace through a VPN

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#4086]
### Bug description

I noticed that my VS CODE(sync enabled) settings get reset if I open a workspace from a different location through a VPN client.

To reduce ping during nighttime at my place, I use a VPN connected to Germany as I saw @jankeromnes to be suggesting so in one of the community.gitpod.io threads. That's when I face this issue mainly. I tried a bunch of other VPN locations too, same happened.

### Steps to reproduce

Connect to a VPN and reload/open a workspace.

### Expected behavior

VS CODE synced settings to be intact.

**Comment by Sylack-lab** [comment]
VSCODE Extensions get reset anytime i open the workspace, synced or not synced...

It's not nice to be installing the same extensions over and over everytime i open my workspace!

**Comment by akosyakov** [comment]
@Sylack-lab It should not happen! Could you check please whether user data sync is actually running for you and what is synched? Open the command palette and type `Settings Sync`, you should see different commands like enabled/disable sync, inspect synced data and logs. Could you check it please?

**Comment by Sylack-lab** [comment]
Apparently it only works on theia, I'm going to check that but it's a weird behaviour.

Also where's file uploading for VS Code?

**Comment by akosyakov** [comment]
> Also where's file uploading for VS Code?

Not sure what you mean? You can drag and drop file in the explorer to upload.

**Comment by Sylack-lab** [comment]
Did not work either

**Comment by Sylack-lab** [comment]
Most of the times i have to upload files to a cloud and download it using wget

**Comment by Sylack-lab** [comment]
I think it's because of my chrome version being dev but im not sure now.
