### ISSUE TITLE
Branch and File Context URLs Not Working

### ISSUE THREAD

**Issue by JakeGWater** [gitpod-io/gitpod#4087]
### Bug description

Neither branch context or file context URLs seem to work for me.

- https://www.gitpod.io/docs/context-urls#branch-context
- https://www.gitpod.io/docs/context-urls#file-context

### Steps to reproduce

File URLs
* https://gitpod.io/#https://github.com/JakeGWater/test/-/blob/test/README.md
* The git branch is wrong.
* The file is not automatically shown in the editor.

Branch URLS
* https://gitpod.io/#https://github.com/JakeGWater/test/-/tree/test
* The git branch is wrong.

### Expected behavior

It should work as documented:

* https://www.gitpod.io/docs/context-urls#repository-context

> Gitpod will automatically check out the requested branch

* https://www.gitpod.io/docs/context-urls#file-context

> Gitpod will check out the corresponding branch and open the respective file in an editor

### Example repository

https://github.com/JakeGWater/test

### Anything else?

Otherwise Gitpod is great!

**Comment by AlexTugarev** [comment]
Hi @JakeGWater!

This is the second time we see that this bit of docs is misleading, unfortunately. The URLs containing `-/tree` are meant for GitLab.

For GitHub this should be 
* https://github.com/JakeGWater/test/blob/main/README.md
* https://github.com/JakeGWater/test/blob/test/README.md

**Comment by JakeGWater** [comment]
Ahh, my bad. Thank you!

**Comment by jpoehnelt** [comment]
Just ran into this, I suggest reopening until the documentation is fixed.
