### ISSUE TITLE
[dashboard] Dashboard dropdown remains active blocking access to other workspace dropdowns

### ISSUE THREAD

**Issue by rl-gitpod** [gitpod-io/gitpod#4090]
### Bug description

If the dropdown is opened on a workspace it is hidden on mouseout of that item in the list, but will always become visible when mousing over any other workspaces within the overlapping region below it, rendering their dropdown inaccessible until the first is toggled closed.

### Steps to reproduce

See https://www.loom.com/share/c6e592828e314987a50741c1c1c354e5

This occurs on gitpod.io and gitpod-staging.io with Chrome - Version 90.0.4430.93 (Official Build) (x86_64) and Brave - V1.23.73 (Apr 22, 2021) on OSX - 11.3 (20E232)

### Expected behavior

As it is a toggling dropdown it should keep the dropdown open when mousing out of the item or alternatively it could auto-close the first dropdown when mousing out and let the dropdown on any workspace be toggles open.

**Comment by gtsiolis** [comment]
Thanks for noticing @rl-gitpod! 🦅 👀 

Closing this in favor of https://github.com/gitpod-io/gitpod/issues/3731.
