### ISSUE TITLE
GitHub App install confirmation flow is broken

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4092]
### Bug description

When I install the [Gitpod Staging](https://github.com/apps/gitpod-staging) for one of my repositories, the installation confirmation flow is broken.

Still, the app successfully installs and then works, so it's just the confirmation that is broken.

### Steps to reproduce

(Note: Problems in **bold**)

- Start here: https://github.com/apps/gitpod-staging

<img width="600" alt="Screenshot 2021-04-28 at 15 34 15" src="https://user-images.githubusercontent.com/599268/116413250-bb103000-a837-11eb-80f8-c843d223f14f.png">

- Install it for your user, for some specific repository:

<img width="600" alt="Screenshot 2021-04-28 at 15 34 34" src="https://user-images.githubusercontent.com/599268/116413262-bd728a00-a837-11eb-9e31-0076a5590585.png">

- In the installation screen, click on "Install App":

<img width="600" alt="Screenshot 2021-04-28 at 15 34 49" src="https://user-images.githubusercontent.com/599268/116413266-be0b2080-a837-11eb-8ce1-ff62786eaf76.png">

- This opens a new tab, that says it should close itself, **but it doesn't**. Close it manually:

<img width="600" alt="Screenshot 2021-04-28 at 15 34 59" src="https://user-images.githubusercontent.com/599268/116413273-bea3b700-a837-11eb-91af-f00d20e7c71d.png">

- The confirmation screen says that **the installation has failed**. Oh no! Click "Try again":

<img width="600" alt="Screenshot 2021-04-28 at 15 35 10" src="https://user-images.githubusercontent.com/599268/116413274-bea3b700-a837-11eb-9137-ec40d2b68f1a.png">

- Clicking "Try Again" gives **a strange error message**:

<img width="600" alt="Screenshot 2021-04-28 at 15 35 18" src="https://user-images.githubusercontent.com/599268/116413276-bf3c4d80-a837-11eb-96c3-63a38ed56a76.png">

However, the app seems to work. Maybe the installation did actually work?

### Expected behavior

- The auto-closing pop-up should auto-close
- Gitpod shouldn't say "installation failed"
- "Try Again" shouldn't give a strange cryptic error

**Comment by AlexTugarev** [comment]
> This opens a new tab, that says it should close itself, but it doesn't. Close it manually:

@jankeromnes did you pay attention to the JS console?

**Comment by jankeromnes** [comment]
> @jankeromnes did you pay attention to the JS console?

Retrying, the self-closing tab doesn't have anything, but the original tab has this:

```
Failed to open the authorize window for github.com                      provider-utils.tsx:61
```

Maybe it tries to open the authorize window twice? 🤔

**Comment by AlexTugarev** [comment]
<img width="1146" alt="Screen Shot 2021-04-28 at 18 13 47" src="https://user-images.githubusercontent.com/914497/116437245-8ad38c00-a84d-11eb-83fa-1adf1b9c1aa3.png">

Thanks for helping with that, @jankeromnes!
