### ISSUE TITLE
[helm] Include containerd-metrics to the deployment

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#4094]
As an effort to improve observability around workspace startup times, the `containerd-metrics` component was refactored to measure the time length of the "Bermuda Gap".

So far we have only included it in the European cluster, but it will be useful to get it deployed into all clusters. Adding it to our Helm chart will help us achieve that.

**Comment by JanKoehnlein** [comment]
Is that still planned?

**Comment by ArthurSens** [comment]
I'm not sure, do we still want to measure bermuda-gaps? If yes, then we should 🤔 

cc @corneliusludmann
