### ISSUE TITLE
Let users confirm closing the IDE

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#411]
We should let confirm users closing the IDE. As many seem to be used to closing editor tabs with ctrl+w (see e.g. https://lacourt.dev/2019/03/07/#closing-files).
Maybe we get the key event before the beforeClose and can base the decision on that.

**Comment by meysholdt** [comment]
👍 took me more than a month to unlearn the CTRL-W reflex.

**Comment by jankeromnes** [comment]
👍 I know many people who can't use cloud IDEs because they compulsively use Ctrl+W all the time.

**Comment by svenefftinge** [comment]
fixed in theia

**Comment by MangelMaxime** [comment]
Hello,

for me if I press `Ctrl+W`, the browser tab is closed directly without any prompt. 

I am using Chrome Version 80.0.3987.87 (64 bits) under Windows 10.

**Comment by hoegertn** [comment]
Same here on Chrome and macOS
