### ISSUE TITLE
registry-facade should use `reg.<prefix>.<domain>`, not `reg.<domain>`

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#4114]
registry-facade should use `reg.<prefix>.<domain>`, not `reg.<domain>`, because registry-facade runs inside a pluggable workspaces cluster which lives under `<prefix>.<domain>`. Making use of `reg.<domain>` interferes with the domain if the meta clusters.

**Comment by meysholdt** [comment]
this just caused certificate renewal to fail once in the US clusters. 
Commenting to bring this back up.

**Comment by meysholdt** [comment]
got bitten by this again.

**Comment by csweichel** [comment]
I reckon the actual issue that we're relying on the public HTTPS certificates for registry-facade.
We've recently started to move to self-signed certs in this case.

@aledbf how much trouble would it be to port your changes over to main?

(removing from groundwork until this becomes actionable)

**Comment by aledbf** [comment]
@csweichel I need to sync in https://github.com/gitpod-io/gitpod/pull/4592 the latest changes from https://github.com/aledbf/gitpod-chart-cleanup
