### ISSUE TITLE
[Loading screen] button styling not nice

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#412]
<img width="491" alt="Screenshot 2019-03-25 at 13 39 58" src="https://user-images.githubusercontent.com/372735/54920467-96805600-4f03-11e9-88a0-b6131ef594ea.png">

**Comment by jankeromnes** [comment]
Oops, that's my fault, I told @32leaves to use:

```html
<Button variant='outlined' color='primary'>
```

but actually I meant:

```html
<Button variant='outlined' color='secondary'>
```

See: https://material-ui.com/demos/buttons/#outlined-buttons

**Comment by jankeromnes** [comment]
Fixed and deployed! 🎉
