### ISSUE TITLE
Cannot initialize workspace when "Full Workspace Backup" flag is enabled

### ISSUE THREAD

**Issue by vinaypuppal** [gitpod-io/gitpod#4121]
### Bug description

@jankeromnes enabled the "Full Workspace Backup" flag today on my account and after that, I started noticing the below error when I am creating new workspaces or restarting my existing workspaces

![Screenshot 2021-04-30 at 5 05 10 PM](https://user-images.githubusercontent.com/8843216/116696332-63142d80-a9df-11eb-9e04-57cbccb8e252.png)

### Steps to reproduce

1. Enable "Full Workspace Backup" flag
2. Try to open any repo in gitpod

### Expected behavior

Should start workspaces 

### Example repository

I was able to reproduce this with any public repo from github

**Comment by vinaypuppal** [comment]
Disabling the flag fixed the issue

**Comment by csweichel** [comment]
We're not currently working on full workspace backup. We'll pick this issue back up when we continue work on that feature.
