### ISSUE TITLE
Add command or URL that rebuilds Gitpod's image

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#4126]
## Is your proposal related to a problem?

Gitpod images might install packages that from time to time get security releases.
The only way to update these packages is manually make a change in `gitpod.Dockerfile`, which will initiate a rebuild to the image (and get the latest security updates)
<br>

## Describe the solution you'd like

Similar to the existing `gitpod.io/#prebuild`, we should add `gitpod.io/#image-prebuild`, that will rebuild the image, without committing anything new to the `gitpod.Dockerfile`.
<br>

**Comment by jankeromnes** [comment]
Thank you for this feature request @shaal!

This is indeed a problem. A popular workaround for this is to increment an (otherwise unused) `ENV` variable in your Dockerfile whenever you wish to force a rebuild, e.g. like so:

https://github.com/gitpod-io/gitpod/blob/474887e6bbf931f142259382713633747e29ae08/dev/image/Dockerfile#L7

**Comment by shaal** [comment]
@jankeromnes I was able to add a comment to `.gitpod.Dockerfile`, to initiate Gitpod image rebuild.
https://github.com/shaal/ddev-gitpod/pull/35/files#diff-454eff0561fdbb1cdf08bef7a76ddf0f82c65fca08a150c43650f5098ecf7118R16-R18

**Comment by apolopena** [comment]
It would be really nice to be able to force a rebuild of the workspace image using a directive in the url.

**Comment by shaal** [comment]
Requesting to add `meta: never-stale` label to this issue

**Comment by corneliusludmann** [comment]
There is `gitpod.io/#imagebuild/` already. (see [may changelog](https://github.com/gitpod-io/gitpod/blob/main/CHANGELOG.md#may-2021)) That triggers a rebuild of the workspace image. Is it what you are looking for?

**Comment by corneliusludmann** [comment]
@mikenikles We don't have this feature in our docs. Do you have some time to find a spot where we could add this?

**Comment by atduarte** [comment]
Thank you, @corneliusludmann. 

@shaal will close the issue as it seems the functionality already exists. If you have further concerns feel free to reopen. :)

**Comment by gtsiolis** [comment]
@atduarte could you open a follow up issue for potentially adding some documentation about this as @corneliusludmann mentioned in https://github.com/gitpod-io/gitpod/issues/4126#issuecomment-901917815?

**Comment by shaal** [comment]
@corneliusludmann Thank you so much, I did not notice that feature before...
💪
