### ISSUE TITLE
Workspace image not rebuilt when there are changes to files used by .gitpod.Dockerfile

### ISSUE THREAD

**Issue by vindvaki** [gitpod-io/gitpod#4127]
### Bug description

Many projects use dotfiles, such as `.ruby-version` ([rvm](https://rvm.io/), [rbenv](https://github.com/rbenv/rbenv)) and `.tool-versions` ([asdf](https://asdf-vm.com/)), as the source-of-truth for runtime dependencies. 

When `.gitpod.Dockerfile` depends on a local repository file, and this file is changed, gitpod does not rebuild the image.

### Steps to reproduce

1. Fork https://github.com/gitpod-io/ruby-on-rails/
2. Start a gitpod (so the workspace is cached)
3. On a branch, change `.ruby-version` to anything different, e.g. `2.7.0`
3. Start a gitpod from your branch

### Expected behavior

The started workspace should have the new ruby version

### Example repository

We ran into this when [updating GitLab's rails project template](https://gitlab.com/gitlab-org/project-templates/rails/-/merge_requests/21#note_564901011).

**Comment by jankeromnes** [comment]
Thank you for the feedback and improvement suggestion @vindvaki!

In Gitpod, custom workspace images are cached based on a hash of the Dockerfile content (this doesn't recursively check included files, or `FROM` image changes, or other upstream dependency upgrades).

However, there are a few workarounds available. For example, you can force a rebuild by incrementing an `ENV` var in your custom Dockerfile: https://github.com/gitpod-io/gitpod/issues/4126#issuecomment-830593427

**Comment by vindvaki** [comment]
@jankeromnes It's an understandable limitation and a reasonable workaround. What do you think about adding  a note in [the docs](https://www.gitpod.io/docs/config-docker)?

**Comment by jankeromnes** [comment]
Not stale + agree this should definitely be mentioned in the docs! 😊🙏
