### ISSUE TITLE
Gitpod cannot connect to websockets

### ISSUE THREAD

**Issue by Sylack-lab** [gitpod-io/gitpod#4128]
### Bug description

Whenever i try to open gitpod dashboard or a project it always says that there was an error connecting to the server and that i am either offline or with websockets blocked.

After 5 or 7 refreshes it finally works but it's a bit time-consuming and not good for user experience

### Steps to reproduce

Open gitpod dashboard or project

### Expected behavior

To run flawlessly the frontend and get my data ready

### Example repository

Happens on any repository i have. (Tested with sylack-lab/Watson and sylack-lab/webmania)

### Anything else?

![image](https://user-images.githubusercontent.com/48862659/116786397-a8e3fb00-aa9e-11eb-8c53-c23c2eccb848.png)

**Comment by akosyakov** [comment]
Which browser version do you use? There were reports that Chrome Canari is unstable. Please use the stable Chrome version if it is so.

**Comment by Sylack-lab** [comment]
> Which browser version do you use? There were reports that Chrome Canari is unstable. Please use the stable Chrome version if it is so.

Running **Chrome Version 92.0.4489.0 (Official Build) dev (64-bit)**

I guess dev version of Chrome causes these errors.

**Comment by akosyakov** [comment]
Yes, please use the stable now. But don't forget to report issues to Chrome devs. It is a point of using beta 😄

**Comment by Sylack-lab** [comment]
> Yes, please use the stable now. But don't forget to report issues to Chrome devs. It is a point of using beta 😄

Will do!
