### ISSUE TITLE
respect maintainer_can_modify settings on PRs

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#413]
I can push as a collaborator to PR:
<img width="225" alt="Screenshot 2019-03-25 at 16 11 14" src="https://user-images.githubusercontent.com/3082655/54931378-2b417e80-4f19-11e9-9f2b-07b089407075.png">

Gitpod does not acknowledge it:
<img width="1472" alt="Screen Shot 2019-03-25 at 16 12 42" src="https://user-images.githubusercontent.com/3082655/54931478-5deb7700-4f19-11e9-993d-6e4784ad6589.png">

I still can push from a terminal though and via Git UI.

**Comment by AlexTugarev** [comment]
I ran some tests on the GH API, and the only hint to determine this is checking the result of `GET /repos/:owner/:repo/pulls/:number` for `maintainer_can_modify: boolean`.

We need to improve the validation of permissions in case of a PR context (origin != upstream):
 * accept if `maintainer_can_modify` is `true`
 * notify otherwise

**Comment by akosyakov** [comment]
I again stumbled over it in https://github.com/eclipse-theia/theia/pull/7610

`git push -f` is good:
<img width="743" alt="Screenshot 2020-04-20 at 09 05 18" src="https://user-images.githubusercontent.com/3082655/79723457-16831600-82e6-11ea-970d-16b71146158f.png">

But UI tells me oppositive:
<img width="540" alt="Screenshot 2020-04-20 at 09 03 59" src="https://user-images.githubusercontent.com/3082655/79723424-05d2a000-82e6-11ea-803f-67a5b3ebcd68.png">
<img width="366" alt="Screenshot 2020-04-20 at 09 04 01" src="https://user-images.githubusercontent.com/3082655/79723419-04a17300-82e6-11ea-93da-2d3e8dc736a5.png">

**Comment by AlexTugarev** [comment]
Revision of the git credential helper to support this is in progress. The happy path was working, but it needs to be tested and fine tuned. One unknown thing remaining ist, that git tends to cache results, which shouldn't be as it would lead to false results whenever you adjust and retry.
