### ISSUE TITLE
Weird font in terminal

### ISSUE THREAD

**Issue by nitish771** [gitpod-io/gitpod#4130]
### Bug description

terminal shows weird font. It is showing vertically half chars.

![Screenshot at 2021-05-02 12-02-11](https://user-images.githubusercontent.com/50190868/116804702-86092380-ab3e-11eb-98f5-14f167f62b73.png)

### Steps to reproduce

When i launched gitpod.io it was there.

**Comment by akosyakov** [comment]
Could you go here and scroll down to the demo: https://xtermjs.org/? Do you get the same effect there? If so it is an issue with font on your operating system.

**Comment by nitish770** [comment]
the font of [xtermjs](https://xtermjs.org/)  works absolutely fine.
The problem is only in gitpod.io terminal. Font in editor and sidebar is good.

**Comment by filiptronicek** [comment]
This is happening to me lately, too. I tried on both Brave and Firefox, and it seems they are both affected.
![image](https://user-images.githubusercontent.com/29888641/117062990-7814f780-ad24-11eb-8c3e-cc43ca7656b6.png)

**Comment by akosyakov** [comment]
You can investigate values of `terminal.integrated.fontFamily` and `editor.fontFamily`. VS Code relies on underlying browser/operating system fonts to render based on these values. Maybe you can check what happens if you use the same fonts in other websites (i guess the same) or try to change the value to find better values.

**Comment by filiptronicek** [comment]
I tried changing `terminal.integrated.fontFamily` to Helvetica, this solved the problem, the font was looking good, even when I then proceeded to delete the setting, it displayed the default font without any issues.

**Comment by nitish770** [comment]
> I tried changing `terminal.integrated.fontFamily` to Helvetica, this solved the problem, the font was looking good, even when I then proceeded to delete the setting, it displayed the default font without any issues.

changing font to Helvetica didn't help but *monospace* did the work.

**Comment by filiptronicek** [comment]
@akosyakov could you please reopen this?

**Comment by lechien73** [comment]
I'm having the same issues. Changing the font family in Settings does fix it temporarily, but if you open a new terminal or restart the workspace then the issue recurs.

![Screenshot 2021-05-14 at 08 46 20](https://user-images.githubusercontent.com/21156053/118238755-dfebe080-b490-11eb-94d5-f9163641b5a2.png)

**Comment by lechien73** [comment]
Any thoughts on this? It's getting quite frustrating to have to reset the terminal font every time I create a new terminal or restart the workspace.

**Comment by nitish771** [comment]
> Any thoughts on this? It's getting quite frustrating to have to reset the terminal font every time I create a new terminal or restart the workspace.

Yeah It is annoying.
This solution is temporary. Even i say just for a few minutes.After you change font after 5 minutes it starts showing that same (weird) font again. I'm not even sure that is a kind of font. 
So I have to come to settings every 5-6 minutes to change fonts to anything (even wrong or empty works) then once time limit is reached same process.

**Comment by lechien73** [comment]
> So I have to come to settings every 5-6 minutes to change fonts to anything (even wrong or empty works) then once time limit is reached same process.

Yes, exactly the same here. I had read about issues with VS Code and the terminal, so I'm hoping when (if) the changes made [in this PR](https://github.com/microsoft/vscode/issues/120004) go live in Gitpod that the problem will be solved. Until then, I need to keep settings.py open and continually reset the font in the terminal which, when you're making tutorial videos based on Gitpod, is extremely frustrating.

**Comment by akosyakov** [comment]
@lechien73 thanks for linking upstream issue, I hope too that it is gone with next VS Code upgrade

**Comment by akosyakov** [comment]
@filiptronicek Could you try whether you can reproduce against https://ak-vscode-update.staging.gitpod-dev.com/workspaces/

**Comment by lechien73** [comment]
In the meantime, we've added a Python file to our template that runs on startup and toggles the font, thereby fixing the issue. Here's the code:

```
# Fixes the font issue on Brave browser
# Matt Rudge
# June 2021

import json
import os

BASE_PATH = os.environ.get("GITPOD_REPO_ROOT")

with open(f"{BASE_PATH}/.vscode/settings.json", "r+") as f:
    content = json.loads(f.read())

    if "terminal.integrated.fontFamily" not in content:
        print("Terminal Font Fix: adding Menlo font")
        content["terminal.integrated.fontFamily"] = "Menlo"
    else:
        print("Terminal Font Fix: removing Menlo font")
        content.pop("terminal.integrated.fontFamily")

    f.seek(0, os.SEEK_SET)
    f.write(json.dumps(content))
    f.truncate()
```

**Comment by filiptronicek** [comment]
> 
> 
> @filiptronicek Could you try whether you can reproduce against [ak-vscode-update.staging.gitpod-dev.com/workspaces](https://ak-vscode-update.staging.gitpod-dev.com/workspaces/)

Looks like I can't access this environment, @akosyakov!
![image](https://user-images.githubusercontent.com/29888641/122055327-ccfa6200-cde8-11eb-856d-9a8799900617.png)

**Comment by akosyakov** [comment]
Let's hope it is gone after June release.

**Comment by sauravhiremath** [comment]
Still an issue

![image](https://user-images.githubusercontent.com/28642011/124001458-48b3fb80-d9f2-11eb-9b50-d4668a878a31.png)

**Comment by akosyakov** [comment]
June release it not yet out.

**Comment by akosyakov** [comment]
Could you verify now?

**Comment by lechien73** [comment]
I opened a workspace that I'd created last week and the issue was still there, but when I opened a few new workspaces it seemed to be fixed. @akosyakov

**Comment by akosyakov** [comment]
@lechien73 Maybe it is related that something about your old workspaces where cached in browser. If you restart new workspaces it is not reproducible?

Also if you look at VS Code about dialog it is 1.57.1 in both cases, right?

**Comment by lechien73** [comment]
Yeah, maybe it was a caching issue - I restarted it again and a few other old workspaces, and the font seems fine now. Thanks @akosyakov

**Comment by Shuhari-Zap** [comment]
I can confirm. Just joined Gitpod on v1.58.2 and it's back for me as well.

**Comment by rotho98** [comment]
I have the same issue, half chars on all the terminal text

**Comment by ayoubelmhamdi** [comment]
https://github.com/gitpod-io/gitpod/issues/5014#issuecomment-891781810

**Comment by shpetimselaci** [comment]
Seems that this still an issue for the Brave, but only if you have the "Shields Up".

Here's the shields up example:
![image](https://user-images.githubusercontent.com/23242179/152604000-5bc1a18f-a212-4598-aa5d-aaa9a6dbe088.png)

Here's the shields down example:
![image](https://user-images.githubusercontent.com/23242179/152604088-204c7196-d9b4-4972-93da-d5a058aeb001.png)


I am using this Brave:
[Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)](https://brave.com/latest/)

My machine is a MacBook Air (13-inch, Mid 2012), running macOS Sierra 10.12.6.

Let me know if you need further info!

**Comment by shpetimselaci** [comment]
It is a bit annoying when the workspace url changes all the time and I have to turn the shields down every time.
Let me know whether I can contribute with a PR or something similar.

**Comment by ludex** [comment]
Same problem encountered. 

My fix was increasing the Letter Spacing value. Not certain if this is correct.

**Comment by kethavathsivanaik** [comment]
This fixed for me
`{
"terminal.integrated.letterSpacing": 2
}`

**Comment by ismail709** [comment]
> This fixed for me
> 
> ```
> {
>     "terminal.integrated.letterSpacing": 2
> }
> ```

Thanks it fixed the issue for me

**Comment by tidley** [comment]
> > This fixed for me
> > ```
> > {
> >     "terminal.integrated.letterSpacing": 2
> > }
> > ```
> 
> Thanks it fixed the issue for me

Setting to 1 works better for me. Thanks

**Comment by kethavathsivanaik** [comment]
It's because of Brave Ad Defender, It worked normal if we disable the Ad Defender

**Comment by mandrasch** [comment]
> It's because of Brave Ad Defender, It worked normal if we disable the Ad Defender

Oh wow, true that!

Could be maybe detected by Gitpod via checking if CSS loading is blocked: 

![Bildschirmfoto 2022-07-30 um 11 37 23](https://user-images.githubusercontent.com/777278/181904660-4521c2ef-ee78-4386-8977-f7e35b5dbd35.png)
