### ISSUE TITLE
Gitpod button shows next to the issue management buttons

### ISSUE THREAD

**Issue by mrexodia** [gitpod-io/gitpod#4133]
### Bug description

![image](https://user-images.githubusercontent.com/2458265/116863300-63dad880-ac06-11eb-9d92-b89a5a128477.png)

### Steps to reproduce

Open any GitHub issue

### Expected behavior

No Gitpod button

### Example repository

https://github.com/MoAlyousef/cmkr/issues/8

**Comment by svenefftinge** [comment]
It is on purpose. It will create a fresh dev environment with a local branch named after the issue which is branched off the default branch. So everything you need in order to fix the issue.
