### ISSUE TITLE
Download trouble

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#414]
**Describe the bug**
Can't download a file with is 2.8GB and not checked into git

**To Reproduce**
1. create a 2.8GB file and 
2. in the File View, open the context menu on the file and select "download".

**Expected behavior**
The file should be downloaded.

Download did work for a small (1k) file.

**Comment by jankeromnes** [comment]
See also: https://github.com/theia-ide/theia/issues/4248

Downloading files seems a bit unreliable, and only works in Chrome, sadly.

**Comment by akosyakov** [comment]
Could you post http code and body of a response?

**Comment by sr229** [comment]
If I remember Cloud9 was able to properly find a workaround this by using a vfs plugin in-tree, and have it as a XHR download.

**Comment by svenefftinge** [comment]
depends on https://github.com/theia-ide/theia/pull/5466
