### ISSUE TITLE
Access denied for cloning internal gitlab repo with gitlab init task

### ISSUE THREAD

**Issue by z3ky** [gitpod-io/gitpod#4140]
### Bug description

Try to clone a repository from self hosted gitlab server using gitpod.yml init/command task. The repo access permission is internal. The user logged in into Gitpod owns this repo.

gitpod.yml

```
image: myImage

tasks:
  - init: git clone https://xxx.git
    name: Clone Repo
```

Workspace log

```
HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> git clone https://xxx.git
> }
Cloning into 'test_repo'...
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://xxx.git/'
```

After the init steps, I can clone the repository using the workspace terminal, with the same command as in gitpod.yml.

### Steps to reproduce

Create a Gitlab repo with access rights: internal
Set up gitpod.yml init task to clone the repo.

### Expected behavior

Repo should be cloned into workspace

### Anything else?

Gitpod 0.8.0 on self hosted k3s

**Comment by AlexTugarev** [comment]
@csweichel do you know if the Gitpod API is already authorized by the time the init tasks are executed? It sounds like a race.

**Comment by JanKoehnlein** [comment]
This currently won't work as the Gitpod API is not yet authorized when running the init task
As a possible workaround, consider linking your Git repositories as submodules.
