### ISSUE TITLE
Does anyone use a window manager? How do I restore minimized windows?

### ISSUE THREAD

**Issue by markfirmware** [gitpod-io/gitpod#4161]

**Comment by thecoder876** [comment]
@markfirmware I'm not a Gitpod dev or anything, but this doesn't seem like it's related to Gitpod; more like your browser. You should probably post this on your browser's community forums (if it has them).

**Comment by markfirmware** [comment]
I still do not know how to restore a minimized window in the novnc view.

**Comment by pawlean** [comment]
> I still do not know how to restore a minimized window in the novnc view.

Hey Mark, have you tried what @thecrewmate876 suggested above?

**Comment by markfirmware** [comment]
No, the problem is in the window manager in the novnc viewer. See #4132
