### ISSUE TITLE
problema en el Build

### ISSUE THREAD

**Issue by GabrielValdiviaGaboloso** [gitpod-io/gitpod#4163]
### Bug description

cuando ocupo el build para probar el trabajo me sale en la terminal el error Error: EAGAIN: resource temporarily unavailable, read desabilitando el build ...

se adjunta pantallazo del problema 
[https://user-images.githubusercontent.com/55467608/117361424-01910a80-ae88-11eb-8748-593cf996bd7f.png](url)

### Steps to reproduce

pruebo el ejercicio con el build

**Comment by aledbf** [comment]
Hola Gabriel,

En el screenshot no se ve exactamente que estas ejecutando. Podrias expandir la consola para entender el contexto?

**Comment by GabrielValdiviaGaboloso** [comment]
![image](https://user-images.githubusercontent.com/55467608/117483493-c9df9c80-af33-11eb-8237-642605a30656.png)

Este es el error que deja deshabilitada el build

**Comment by aledbf** [comment]
> Este es el error que deja deshabilitada el build

Por favor selecciona todo el texto y pegalo como comentario (solo estas mostrando la parte final)

Como estas ejecutando el código?
