### ISSUE TITLE
Make GKE/Grafana links on admin panel work for pluggable workspaces clusters.

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#4166]
For "new" pluggable workspace clusters, the admin panel does not yet show the links "GKE Node" etc
Example: https://gitpod.io/admin/workspaces/fuchsia-squid-nht0rfp9

![image](https://user-images.githubusercontent.com/239422/117405174-76f1ef00-af0b-11eb-8e3b-743426749cf6.png)

Expectation: Have the bottom row of links as shown in the following screenshot:
Example: https://gitpod.io/admin/workspaces/brown-owl-ydndi0ds

![image](https://user-images.githubusercontent.com/239422/117405237-9426bd80-af0b-11eb-9255-b391b4dda3cd.png)

Part of the cause is that here the mapping from cluster to hyperlinks is hardcoded:
https://github.com/gitpod-io/gitpod/blob/af51739d341bb2245598e275336ae9f730e3b41a/components/dashboard/src/admin/gcp-info.ts#L81-L91

A solution would be to make the `GcpInfo` automatically available for new pluggable workspace clusters:
https://github.com/gitpod-io/gitpod/blob/af51739d341bb2245598e275336ae9f730e3b41a/components/dashboard/src/admin/gcp-info.ts#L129-L134

A solution would involve involve surfacing this information from the the pluggable workspace cluster.
TBD: 
1. should the values come from the cluster itself or be stored as metadata in the "clusters" table in the DB?
2. should all values be surfaces from the backed on can we derive some, e.g. via a naming pattern. For example, there is a lot to derive from the name of a cluster: `gp-prod-ws-eu05-eu-west1`.

**Comment by princerachit** [comment]
Mo and I discussed this and we decided that we will be using the below approach:
1. using server to expose the information from the cluster
2. the cluster name would be injected to ws-manager using helm chart
3. To decide if we need to persist the cluster name in the DB


I will update the approach if it is not feasible/violates the current design.

**Comment by AlexTugarev** [comment]
Hi @princerachit!

As the `WorkspaceInstanceStatus`, which is populated in `ws-manager`, already knows the `node`, would it make sense to provide with the cluster info as well? Deriving `GcpInfo` from that would be feasible.

**Comment by princerachit** [comment]
Thanks for the suggestion @AlexTugarev .  I am planning on adding to `project,cluster,` to `WorkspaceInstance` and `namespaceName` to `WorkspaceInstanceStatus` (which is a field in WSI struct).

The primary reason is that I want to keep Kubernetes specific details in one place i.e. WIS, given that we already keep the podName, nodeName in WIS. Does that make sense?

**Comment by princerachit** [comment]
I met with @meysholdt to discuss how and where we should be adding the links to the admin panel.
We identified the following sub tasks/issues:
### Right table to have the links
There are broadly two tables where we can have this information `d_b_workspace_cluster` or `d_b_workspace_instance`. We want to go ahead with `d_b_workspace_cluster` based on [this comment on the PR](https://github.com/gitpod-io/gitpod/pull/4186#issuecomment-843165592) by @csweichel .

### How to fill the information in the DB
There are two options:
1. Use `gcpctl` tool to provide cluster details when we register a new cluster
2. Use ws-manager to store the details in the DB

We decided to go with __2__ as we don't want to add manual effort of adding more information while registering a cluster. It is error prone.

### What are we going to save?
We will have an annotations column in the `d_b_workspace_cluster`. We will store at least these information:
1. Link to the pod
2. Link to the node
3. Link to the logs
4. Link to Grafana ws and Node

Any of the above links which require either the (1) Pod name,  (2) the node name or (3) namespace would have a placeholder for these fields which should be filled during runtime.


As we want to make things generic here is how we will be saving links in the annotations json column, values are mock:

```json
{
  "podURL" : "http://${podName}.myclustername.myprojectname.platform.com/${namespaceName},
  ..
  ..
}
```

This gives us flexibility that we don't end up maintaining separate keys based on the provider. i.e. `gcpPodURL`, `awsProdURL` etc


### How does ws-manager get the information?
We will modify the helm chart for ws-manager config to include url/urlTemplates. This will be parsed and used by ws-manager.

### When does ws-manager populates the DB
The ws-manager will populate the DB when it tries to come up i.e. during initialization.

### What would happen if the pod restarts?
Nothing. It will try to update the database entry with existing information which is ok.
