### ISSUE TITLE
Use previous prebuild

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#417]
If there's a prebuild running one can only wait or choose to work on a non-prebuilt workspace. Sometimes falling back to the previous prebuild is enough. There should be an option next to `Skip Prebuild` where I can choose something like `Use previous prebuild`.

**Comment by svenefftinge** [comment]
In that case at least the repo should be fetched and reset, no?

**Comment by jankeromnes** [comment]
Related, I sometimes would like to purposefully use an older prebuild.

For example:

1. Push "fix typo" commit to repo or PR that takes 2 hours to build
2. Realize I need a prebuilt workspace _now_ to do something else

Thankfully, builds for previous commits can still be accessed via the green ✔️ icons in commit lists (on repo or PR), e.g.:

<img width="812" alt="Screenshot 2019-03-27 at 14 59 16" src="https://user-images.githubusercontent.com/599268/55153401-a5a91300-5152-11e9-8198-b9835e984a46.png">

This means that in theory I could open a finished prebuild of a previous commit, without having to wait.

Unfortunately, all these links have the same URL (i.e. pointing to the repo or PR). A per-commit prebuild URL would be nice. (Or maybe just use `gitpod.io/#https://github.com/NAME/REPO/commit/abcdef01234...`?)

**Comment by jmls** [comment]
if you want to "skip" the prebuild, gitpod could also tag the commit witr the name of the previous prebuild (if there is one) so that the workspace could start quickly.
