### ISSUE TITLE
Ports stay detecting?

### ISSUE THREAD

**Issue by Sylack-lab** [gitpod-io/gitpod#4172]
### Bug description

The ports of my project will never open, they stay "detecting"

### Steps to reproduce

1. Create a PHP File on a existing or new repository
2. Run `php -S localhost:3000`
3. Encounter bug

### Expected behavior

Ports open and i can view my PHP Application

### Example repository

sylack-lab/Watson

(Add a subfolder with 2 php files)

### Anything else?

I use chrome-dev branch, I don't want to downgrade due it resetting my chromebook if i do so.

Region EU (03), Spain.
Editor: Theia
Extensions: none that interfer with the ports
Other code: none only the php files attempting to run
Name of workspace:
moccasin-scorpion-6o6sbf6z

**Comment by Sylack-lab** [comment]
![image](https://user-images.githubusercontent.com/48862659/117455117-27311900-af47-11eb-9c6f-079d9de04bab.png)

**Comment by akosyakov** [comment]
It happens from time to time when k8s master becomes super busy. But should resolve automatically on workspace restart. But we should do https://github.com/gitpod-io/gitpod/issues/3160 to provide better feedback and allow users to retry without the workspace restart.

@Sylack-lab Do you still exp it?

**Comment by Sylack-lab** [comment]
No I don't, but it took a bit to fix, I had to stop and make a new workspace, did not bother much making a new one, but sure it drove me crazy for 10 minutes.

I had been reading on the forums that sometimes servers have to expose too many ports from different servers or something like that.

Anyways I'll close this issue as it is known.
