### ISSUE TITLE
Cannot delete a workspace in PREPARING phase 

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4173]
### Bug description

Users cannot delete workspaces in `PREPARING` phase.

### Steps to reproduce

1. Go to workspaces list (`/workspaces`)
2. Create one or two workspaces. Using the example projects also works.
3. Go back to the dashboard while workspaces are being created.
4. Try to click more actions (···) and then _Delete_ while a workspace is still in `PREPARING` phase.
5. Confirm deletion in the confirmation modal.

### Expected behavior

Workspace should be deleted.

According a reference to the comment in https://github.com/gitpod-io/gitpod/issues/4173#issuecomment-874248212.

> We could either a) disable the workspace delete dropdown option or b) remove the entry from the user interface and handle all the background tasks needed to gracefully delete a workspace.

**Comment by apolopena** [comment]
I have observed this issue as well.

**Comment by csweichel** [comment]
Deleting workspaces in any phase but RUNNING or STOPPED is very difficult. I reckon we should rather disable the "Delete" item in the menu if the workspace is neither running nor stopped.

**Comment by gtsiolis** [comment]
>  I reckon we should rather disable the "Delete" item in the menu if the workspace is neither running nor stopped.

Thanks @csweichel for the insight! Agree, adding the following to the issue description. Let me know if the second option below sounds inefficient. 🏓 

We could either a) disable the workspace delete dropdown option or b) remove the entry from the user interface and handle all the background tasks needed to gracefully delete a workspace.

**Comment by apolopena** [comment]
Previously a workspace could be deleted in any state, what changed? I assumed that (previously) the workspace was removed from the list until all the background tasks for deleting the workspace had been completed.  I use to rely on this functionality, it was useful.

**Comment by csweichel** [comment]
> Previously a workspace could be deleted in any state, what changed? I assumed that (previously) the workspace was removed from the list until all the background tasks for deleting the workspace had been completed. I use to rely on this functionality, it was useful.

Thank you for pointing this out. Except for "in preparation" workspaces in other phases can be stopped (which is what we're doing, actually). It would seem that the deletion doesn't happen reliably afterwards though, i.e. the workspace is stopped but not necessarily deleted).

**Comment by corneliusludmann** [comment]
This seems to be related: https://community.gitpod.io/t/unable-to-delete-workspace/4956
