### ISSUE TITLE
Workspace not stopping or opening.

### ISSUE THREAD

**Issue by nualagr** [gitpod-io/gitpod#4175]
### Bug description

Workspace not opening or stopping.
At 3:45pm the workspace that I had been working on all day stopped responding.

### Steps to reproduce

No attempts in the past half an hour have succeeded in opening or stopping the workspace.

### Expected behavior

Open the workspace.
Stop the workspace.

**Comment by elomasney** [comment]
Experiencing the same issue for the past hour, my workspace won't open and has stopped responding.

**Comment by gabrielzukaa** [comment]
Same problem for me workspace not allowing me to stop or open.

**Comment by MelWatts** [comment]
Same here, I'm shut out now, can't access my workspace.

**Comment by meysholdt** [comment]
hello! 

apologies for the trouble. We lost one Kubernetes cluster with less than 20 workspaces running on it today at around 14:10 UTC today. Since then the status of the workspaces is stuck. Let me update this manually. 

regards,
  Moritz

**Comment by Tmuat** [comment]
Thanks Moritz, do you know how long it will take before I can start using my workspace again?

**Comment by wulfthimm** [comment]
Workspaces can be started again. We have multiple clusters to provide resources for workspaces. We are sorry about that incident.

**Comment by Tmuat** [comment]
My workspace (https://violet-marmot-jstwc05k.ws-eu05.gitpod.io/) is still stuck in a place where I can't stop it and it says is is running but I can't connect to it. The connection times out.

**Comment by elomasney** [comment]
My workspace is still stuck and will not open. The connection still times out

**Comment by elomasney** [comment]
My workspace will open but it doesn't included any of the changes I had made today

**Comment by elomasney** [comment]
No problem, thank you for fixing the issue at least I can get into the workspace now
