### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by GazzaJ** [gitpod-io/gitpod#4177]
### Bug description

After logging into gitpod, I am able to select my workspace(https://ivory-piranha-x28qf5ep.ws-eu05.gitpod.io/). gitpod only gets as far as preparing the workspace before it hangs up and fails to load the workspace when I receive a "This site can't be reached" alert.
I am also unable to stop my workspace from the workspaces dashboard.
I have logged out and logged back in, but get the same result.

### Steps to reproduce

Select workspace to open it.

### Expected behavior

Workspace opens displaying editor windows and terminals.

**Comment by gabrielzukaa** [comment]
Same problem for me workspace not allowing me to stop or open.

**Comment by meysholdt** [comment]
Apologies for the trouble. See https://github.com/gitpod-io/gitpod/issues/4175#issuecomment-834634682 for details.

regards,
  Moritz
