### ISSUE TITLE
Error Connection

### ISSUE THREAD

**Issue by MelWatts** [gitpod-io/gitpod#4180]
### Bug description

I have been working in gitpod all day, last save, it said cannot save error connecting, and now I cannot open my workspace at all. This site cannot be reached is what I get, I have logged out, shut my computer down, restarted everything but same issue. I cannot continue working.

### Steps to reproduce

Restarted my computer, and logged back into Gitpod, Error connecting

### Expected behavior

Open my workspace so I can continue my work

### Example repository

https://amaranth-snipe-60chlmjg.ws-eu05.gitpod.io/

**Comment by Tmuat** [comment]
Same problem! Annoying because the gitpod status says its operational
