### ISSUE TITLE
New prometheus info metric that tells the current score of a cluster.

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#4182]
After the introduction of pluggable workspace clusters, we noticed that our dashboard `Gitpod / Overview` doesn't scale as well as Gitpod 😛. See https://github.com/gitpod-com/observability/issues/100 for details.

We want to do a revamp of that dashboard and one of the things we would like to have there is the current score of each cluster.

@csweichel @geropl do you know which component would be the one that holds such information?

**Comment by meysholdt** [comment]
The score is persisted in the MySQL db and 'server' and 'ws-manager-bridge have' have access to it.

**Comment by ArthurSens** [comment]
Reopening because it is still valid

**Comment by ArthurSens** [comment]
Fixed by #5726
