### ISSUE TITLE
Gitlab got native integration for Gitpod quick-launch

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#4185]
### Bug description

As the title says, it appears that Gitlab now has a button for Gitpod.

An example for it in action:
![image](https://user-images.githubusercontent.com/39482679/117617715-7734f900-b15c-11eb-8cb7-5336ce3bf2f4.png)

It can be enabled under preferences of Gitlab:
![image](https://user-images.githubusercontent.com/39482679/117617926-c418cf80-b15c-11eb-8949-40d142f26fe5.png)

So, I was wondering, would it be still worth to [inject](https://github.com/gitpod-io/browser-extension) the `quick-launch` button for Gitlab repos?

Thanks.

### Steps to reproduce

Go to `Gitlab> User Settings> Preferences> Integrations> Enable Gitpod integration`

See a Gitlab repo page.

**Comment by gtsiolis** [comment]
Hey @axonasif, the extension button should disappear when you enable Gitpod integration and set it as the default action in the IDE dropdown, right? Is the extension button still there after reloading the page?

**Comment by axonasif** [comment]
> Hey @axonasif, the extension button should disappear when you enable Gitpod integration and set it as the default action in the IDE dropdown, right? Is the extension button still there after reloading the page?

Umm yes, guess I should've reloaded :sweat_smile:
