### ISSUE TITLE
Seed Changelog v2 with exciting / user-visible changes from the April / May cycles

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4187]
## Context

We'd like to resume publishing regular changelogs for Gitpod:
- Previous Changelogs (no update since 2020-06-03): https://www.gitpod.io/docs/changelog/
- New Changelogs page (website PR): https://github.com/gitpod-io/website/pull/395

## Process

We want to keep track of exciting / user-visible changes in Gitpod, by either:
- Maintaining a `CHANGELOG.md` file (or multiple files)
- Adding a `changelog` label to relevant Pull Requests

(Currently being decided.)

Roles / responsibilities:
- Author of Pull Request: Should add a one-line changelog entry if their change is user-visible or otherwise exciting/interesting for users (e.g. performance/stability improvements)
- Reviewer of Pull Request: Should remind the author about adding a changelog entry
- Developer Success team: Should communicate Gitpod releases by picking out a few highlights from the changelog, and adding more context & visuals

## Seeding / back-filling the new changelogs

To help kickstart the new changelogs, I'm:
- going through Gitpod's [commit history](https://github.com/gitpod-io/gitpod/commits/main) page by page
- opening relevant commits, then their linked Pull Request, and optionally their linked issue
- writing a short one-line summary of relevant PRs from a user's perspective

Here goes (WIP, newest first):

[May (unreleased)](https://github.com/gitpod-io/gitpod/compare/4ac8ec46e58b85d53fdb253b36625ad2f2d2f538...main):

- Implement admission constraints for Pluggable Workspace Clusters: https://github.com/gitpod-io/gitpod/pull/4158
- Implement new self-hosted setup flow: https://github.com/gitpod-io/gitpod/pull/3995
- Fix Cross Origin Websocket Access (credit: Joern Schneeweisz from the GitLab Security Research Team): https://github.com/gitpod-io/gitpod/pull/4118

[April](https://github.com/gitpod-io/gitpod/compare/745dfbc5bb9b18fb39c29986f612e03b85af5cf2...4ac8ec46e58b85d53fdb253b36625ad2f2d2f538):

- Hide 'Continue with Default Image' button when Docker build is still running (button did nothing): https://github.com/gitpod-io/gitpod/pull/4104
- Standardize 'Pending Changes' component in Workspaces List and fix for dark theme: https://github.com/gitpod-io/gitpod/pull/4078
- VS Code: Fix forking certain repositories: https://github.com/gitpod-io/gitpod/pull/4098
- Fix GitHub App installation confirmation flow: https://github.com/gitpod-io/gitpod/pull/4093
- Theia: Fix installing big extensions (e.g. Java, Svelte): https://github.com/gitpod-io/gitpod/pull/4030
- Ask user for confirmation before deleting an environment variable: https://github.com/gitpod-io/gitpod/pull/4051
- UX: Redirect new/not-signed-in users from gitpod.io to www.gitpod.io: https://github.com/gitpod-io/gitpod/pull/4070
- Fix loading Gitpod's dashboard in Safari < 14: https://github.com/gitpod-io/gitpod/pull/4069
- Fix the GitHub App's 'addComment' and 'addBadge' features: https://github.com/gitpod-io/gitpod/pull/4043
- Fix VS Code IDE opt-in in "What's New" modal: https://github.com/gitpod-io/gitpod/pull/3914
- Optimize Gitpod's dashboard to make it lighter and load faster: https://github.com/gitpod-io/gitpod/pull/3830
- Implement an alpha version of Gitpod's Local Companion app: https://github.com/gitpod-io/gitpod/pull/3958
- Community contribution: [docs][scripts] fix broken README.md weblinks and refactor protoc-generator.sh https://github.com/gitpod-io/gitpod/pull/4027
- Fix VS Code for workspace images based on Ubuntu 18.04: https://github.com/gitpod-io/gitpod/pull/3969
- Make the Docker daemon in workspaces auto-start when needed by introducing a socket activated 'sudo docker-up': https://github.com/gitpod-io/gitpod/pull/4018
- Improve the bug report template: https://github.com/gitpod-io/gitpod/pull/4017
- Implement a 'Cancel Downgrade' flow for paid plans: https://github.com/gitpod-io/gitpod/pull/3873
- Fix Git Integrations 'more actions' button placement https://github.com/gitpod-io/gitpod/pull/4007
- Upgrade to VS Code 1.55.x: https://github.com/gitpod-io/gitpod/pull/3937
- Admin/Self-Hosted: Allow restoring a soft-deleted workspace in one click when still within the grace period: https://github.com/gitpod-io/gitpod/pull/3955
- Implement a Dark Theme: https://github.com/gitpod-io/gitpod/pull/3901
- Don't cache error responses in the dashboard: https://github.com/gitpod-io/gitpod/pull/3935
- Handle 'Email is taken' error case in Login page: https://github.com/gitpod-io/gitpod/pull/3950
- Add OAuth2 host check (credit: Joern Schneeweisz from the GitLab Security Research Team) https://github.com/gitpod-io/gitpod/pull/3940
- Improve Team plans page layout on smaller screens: https://github.com/gitpod-io/gitpod/pull/3845
- UX: Fix accidental workspace deletion when using the 'Enter' key: https://github.com/gitpod-io/gitpod/pull/3945
- Also show environment variables with identical names but different scopes in the dashboard: https://github.com/gitpod-io/gitpod/pull/3938
- Improve error message when trying to open a Pull Request with deleted branch/fork: https://github.com/gitpod-io/gitpod/pull/3869
- Self-Hosted: Release v0.8.0: https://github.com/gitpod-io/gitpod/pull/3900
- Self-Hosted: Require Kubernetes 1.17+: https://github.com/gitpod-io/gitpod/pull/3889
- Redirect to /blocked when trying to create or start a workspace while blocked https://github.com/gitpod-io/gitpod/pull/3785
- Supervisor: Thread-safe listening to terminals: https://github.com/gitpod-io/gitpod/pull/3870
- Dashboard: Replace nginx with caddy: https://github.com/gitpod-io/gitpod/pull/3851
- Make workspace 'start' / 'stopped' screen resilient to network interruptions: https://github.com/gitpod-io/gitpod/pull/3862
- Fix quantity type conversion in Team plans: https://github.com/gitpod-io/gitpod/pull/3866
- Refresh Gitpod's prebuild welcome message (🍌 → 🤙): https://github.com/gitpod-io/gitpod/pull/3863
- Community contribution: Don't make `gp` CLI rely on `PATH` to look up `code`: https://github.com/gitpod-io/gitpod/pull/3846
- VS Code: Make extensions host resilient to network interruptions: https://github.com/gitpod-io/gitpod/pull/3840
- Developing Gitpod-in-Gitpod: Upgrade to Go 1.16.3: https://github.com/gitpod-io/gitpod/pull/3820

[March](https://github.com/gitpod-io/gitpod/compare/44c42cbeaeea139e1c2507256cb2d2974286f1b8...745dfbc5bb9b18fb39c29986f612e03b85af5cf2):

- Revamped Gitpod dashboard: https://github.com/gitpod-io/gitpod/pull/3295
- ... TODO?

**Comment by gtsiolis** [comment]
Closing this, feel free to reopen if this is still relevant. Cc  @jankeromnes @mikenikles
