### ISSUE TITLE
Add menu entry to open dashboard from the VS Code application menu

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4195]
### Problem to solve

Currently, you can only go back to the dashboard from a running workspace through the command palette using a) the [command palette shortcut](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and the [remote host button](https://code.visualstudio.com/docs/remote/ssh#_connect-to-a-remote-host) in the status bar.

See also [relevant discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1620645699054300) (internal).

| Application Menu | Command Palette |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/117702283-f95f0500-b1d0-11eb-9047-2001cd027043.png) | ![image](https://user-images.githubusercontent.com/120486/117702385-198ec400-b1d1-11eb-9d8d-6e82abe6e34d.png) |

### Proposal

Now that new dashboard is more useful to go back from a workspace, let's add a new item in the application menu in VS Code to open the dashboard. 🙂

**Comment by gtsiolis** [comment]
Bumping this up in Engineering Groundwork but feel free to remove from the board if needed. 🌬️

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4195#issuecomment-911353841):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
