### ISSUE TITLE
Change git provider authorization button variant 

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4197]
### Problem to solve

When opening a repository from a git provider you haven't authorized, you are prompted to authorize with that git provider. The primary button to authorize with that provider is currently not using proper weight.

### Proposal

Let's change the button to authorize with a git provider from secondary to primary.

| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/117707181-e818f700-b1d6-11eb-99e0-17f2f7e3a1d4.png) | ![image](https://user-images.githubusercontent.com/120486/117707187-e94a2400-b1d6-11eb-9b8e-5d4508894e31.png) |

**Comment by corneliusludmann** [comment]
Fixed by #4288. Thanks, @jordanhailey!
