### ISSUE TITLE
Change providers order on the login page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4198]
### Problem to solve

We recently updated `www.gitpod.io` and changed the order of the providers to GitLab, GitHub, Bitbucket. However, the product still uses the following order: GitHub, GitLab, Bitbucket.

Besides this:
1. In terms of UX, it would be optimal to use the same ordering across product and marketing to avoid confusion and affecting muscle memory.
1. In general, an equal and neutral treatment for all git providers is ideal, especially given our [neutrality differentiator](https://www.notion.so/gitpod/Brand-Values-2ed4c2f93c84499b98e3b5389980992e#be648015b10342c6a18379a947d80fca).
1. This is one of the reason all three look like carrying the same weight within the product by using dimmed grayscale versions.
1. However, sorting them vertically or horizontally can already imply a preference order. It's worth taking into account a) our [partnership strategy](https://www.notion.so/gitpod/Gitpod-s-Direction-be35d064c0704fbda61c542b84e07ef6#3a6cf93e1cf34829bbe4d19f36619d90) (see Gitpod' Direction), b) existing [go-to-market partnerships](https://www.notion.so/gitpod/Developer-Community-Success-Roadmap-0050d146d48144748b9dace026e58655#b7eb54bd8c2d41a89863ea273dbe6e95) (see DCS Roadmap) as well as our alignment in values, open source, and more with GitLab.

See also [relevant discussion](https://gitpod.slack.com/archives/C01KGM9BUNS/p1617823131059700?thread_ts=1617811745.037100&cid=C01KGM9BUNS) (internal). /cc @AlexTugarev @jankeromnes @svenefftinge 

### Proposal

Let's change the order of the git porviders to match the order used in `www.gitpod.io` and place our friends at GitLab on the top of that list. 🦊 

| BEFORE | AFTER |
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/117708010-f582b100-b1d7-11eb-80d3-cddd53acc45b.png) | ![image](https://user-images.githubusercontent.com/120486/117708014-f6b3de00-b1d7-11eb-805b-2be95a708afd.png) |

**Comment by JanKoehnlein** [comment]
Fixed by https://github.com/gitpod-com/gitpod/pull/5442
