### ISSUE TITLE
Gitpod stuck on loading screen

### ISSUE THREAD

**Issue by ItzSkitz** [gitpod-io/gitpod#4199]
### Bug description

I tried to open a workspace on gitpod for the first time, but it keeps loading. The screen just says "Opening IDE" while the logo animation plays on loop. The first time I tried to get it to load, I left it running for 10-20 minutes with no luck. All my other attempts have lasted 3-7 minutes, and I'm still stuck on the loading screen...

### Steps to reproduce

Opening a new workspace on gitpod.io from Chrome OS

### Expected behavior

For the IDE to open

**Comment by AlexTugarev** [comment]
Hi @ItzSkitz! Can you please comment on the version of Chrome OS? Is it a beta release?

**Comment by AlexTugarev** [comment]
Might be related https://community.gitpod.io/t/websocket-issues-on-chrome-os/3458

**Comment by akosyakov** [comment]
@ItzSkitz Could you please open devtools and copy any errors which you have there.

**Comment by svenefftinge** [comment]
Scheduling for groundwork, because we have seen this issue twice last week, so potentially happens regularly.

**Comment by geropl** [comment]
@svenefftinge The issue is rather old, and I personally never experienced it. Do you have any workspace ids/more context one could start investigating on?

**Comment by csweichel** [comment]
Considering this is hard to reproduce, we might want to collect some more data on this issue first (https://github.com/gitpod-io/gitpod/issues/4863). I'll remove this from groundwork for now and give #4863 higher priority.

**Comment by akosyakov** [comment]
Ideally we need error logs from devtools. We used to collect frontend logs, maybe we can reintroduce it at least for error logs or using https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

**Comment by akosyakov** [comment]
Another alternative is to persist supervisor window logs in indexed db similar how VS Code persist and ask user to provide them later for failed worspace.

**Comment by akosyakov** [comment]
I just had a workspace stopped and then stuck in openning screen. Logs: https://console.cloud.google.com/logs/query;cursorTimestamp=2021-08-06T09:37:33.103647Z;query=%22lavender-fowl-d3u2v4se%22%0A-resource.labels.container_name%3D%22ws-proxy%22%0Atimestamp%3D%222021-08-06T09:37:31Z%22%0AinsertId%3D%22mco1lqloe1xabtgg%22?project=gitpod-191109 Basically IDE process was stopped and then could not start because of `signal: Killed`. It seems that node was low on memory.

**Comment by akosyakov** [comment]
I think there is also a bug in the supervisor frontend, it should detect that the workspace failed and switch from `Opening IDE` screen to failed/stopped screen.

**Comment by akosyakov** [comment]
I add more tracing info https://github.com/gitpod-io/gitpod/pull/5220 to estimate impact and track down the cause.

**Comment by akosyakov** [comment]
According to data 2.5% of window sessions never see running state or take more than 1 mins for regular workspaces. After looking at the code I think there is a race in the supervisor frontend and cause missing ready event sometimes.

**Comment by akosyakov** [comment]
> According to data 2.5%...

Looking closer at data, it does not seem that our events are complete, i.e. we are missing initial ready signal and there are different issues with status_rendered and vscode_session events. Going to fix them in: https://github.com/gitpod-io/gitpod/pull/5710 After that we will need to wait for new meta deployment and some time to collect new data. So I'm putting this issue unhold.

**Comment by akosyakov** [comment]
It happened to me on reconnection during opening then ide is never get started.

**Comment by akosyakov** [comment]
I looked at fresh data since last deployment 7 days, still 1.8% of user sessions seem to be stuck even with fixed events.

**Comment by akosyakov** [comment]
Hm, i think date are still not very clean. We are losing now unload event. If I filter out events which never even see ide-init and unload then we get: 0.8% I will move unload event to more reliable place and for now assume that no unload and ide-init means the page was closed very fast, but we need to verify it later.

**Comment by akosyakov** [comment]
Around 0.1% is actually failure to fetch supervisor info endpoint or load some html resources. I don't think we can do something about them. In such case a user should see the error page and reload.
