### ISSUE TITLE
Gitpod is frozen after initialization

### ISSUE THREAD

**Issue by aloule** [gitpod-io/gitpod#420]
**Describe the bug**
Gitpod is frozen after initialization. When I click on a Workspace in the dashboard, the screen displays 'Starting (x/y)' until 'Running' is displayed. After everything in the gitpod tab  (Chrome) is frozen.

Google Chrome: 73.0.3683.86 (Build officiel) (64 bits)
MacOS: 10.13.6

I think it is related to something I made on my 'user' config file, because each workspace I open ends frozen. But, I found no way to log to see what I have done wrong.

**To Reproduce**
Open dc65ce20-c62a-49e8-9acf-8506ccdc2b2e, or any workspace like https://gitpod.io/#https://github.com/now-examples/nextgram

**Expected behavior**
The editor comes live.

**Comment by svenefftinge** [comment]
Thanks for reporting it. We are looking into it.

**Comment by svenefftinge** [comment]
It was indeed your user settings. I can reproduce it and will fix it.

```
{
   "editor.tabSize": 2,
   "terminal.integrated.lineHeight": 0,
   "terminal.integrated.letterSpacing": 0,
   "terminal.integrated.fontSize": 13,
   "terminal.integrated.fontFamily": "Source Code Pro for Powerline, Menlo, Monaco, 'Courier New', monospace"
}
```

probably the fontFamily.

I have reset your user settings for now.

**Comment by svenefftinge** [comment]
It's
> "terminal.integrated.lineHeight": 0,

**Comment by svenefftinge** [comment]
https://github.com/theia-ide/theia/issues/4767

**Comment by aloule** [comment]
Thanks for the support. I think, beside the issue for this specific setting, the issue is that it is impossible to log into an instance in a kind of 'rescue' mode, and try to correct the issue by myself. Or may be there is a way to do that?

Anyway, thanks for the quick support.
