### ISSUE TITLE
Deprecate `prebuild` task

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#4205]
We should deprecate the `prebuild` lifecycle for tasks as it complicates tasks without adding enough value.
I often see users missusing it. E.g. https://github.com/ray-project/ray/blob/56c309416e04a70d874709b9a612ffb482f3f80a/.gitpod.yml

Adding a deprecation warning to the gitpod yml schema as well as removing the documentation would do as a first step.

**Comment by svenefftinge** [comment]
You would use `init` which is the task that is executed on prebuilds and not again when starting a prebuilt workspace.

**Comment by shaal** [comment]
According to the Gitpod documentation, `init` runs during prebuild, and then run again every time a new workspace is started.

So when we have a command that compiles everything and take a few minutes, the advantage of `prebuild` is that it runs before the user opens a new workspace, but with `init`, it will run during prebuild but then users will have to wait for the compile again, once they open a new workspace.

**Comment by corneliusludmann** [comment]
The `init` command is executed once only. When you start a workspace that does not have a prebuild, it's executed at workspace start. When you start a workspace that has a prebuild, it does NOT executes `init` but `before` and `command`.

The `prebuild` command runs during prebuilds only and never when a workspace without prebuild is started. The application is pretty limited.

I hope I have been able to shed some light on this.

**Comment by shaal** [comment]
Thank you @corneliusludmann for clarifying.
It sounds like `init` IS the way to go, anywhere I used `prebuild` before.

Do you know when will this change take effect? and what will happen to workspaces that would still use `prebuild`?

**Comment by corneliusludmann** [comment]
For now, we will make the `prebuild` task deprecated soon and remove it from the docs but still fully support it. However, using `init` instead of `prebuild` now in your projects would be a good idea.

**Comment by shaal** [comment]
👍 Thank you

**Comment by svenefftinge** [comment]
@shaal since the semantics of `init` didn't seem to come across in the docs, you may have a good suggestion on how to better explain it?

**Comment by mikenikles** [comment]
Reminders:
- [ ] Update the new references/gitpod-yml docs to mark this task as deprecated.
- [ ] Update the Start Tasks docs. A rewrite of the entire page as per above comment will be a separate task.
