### ISSUE TITLE
dashboard/settings/variables: ending drag selection outside of modal dialog dismisses dialog

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#4221]
### Bug description

1. Dashboard > Settings > Variables
2. Input long text (say authentication token)
3. (mouse button down) Try selecting subsection of this text with the mouse
4. (mouse button up) end selection outside of the modal

### Steps to reproduce

![2021-05-17_12-45-51 (1)](https://user-images.githubusercontent.com/127353/118426479-a0322c80-b70e-11eb-9ba7-93f9b1100150.gif)

### Expected behavior

Text entry and manipulation operations do not dismiss the dialog.

**Comment by gtsiolis** [comment]
Thanks, @ghuntley! Agree, we should probably disable closing the modal when clicking outside the modal, especially when editting existing entries.

**Comment by corneliusludmann** [comment]
I am in favor of NOT closing the modal when clicking outside. The legal use case is quite limited and the risk of closing the modal unintentionally is too high, IMO.
