### ISSUE TITLE
Make it easier to delete multiple or all workspaces

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4233]
### Problem to solve

Although workspaces eventually time out and stopped workspaces are getting deleted according to the [garbage collection](https://www.gitpod.io/docs/life-of-workspace#garbage-collection), sometimes a user would like to manually delete multiple or all workspaces regarding running status.

See also [relevant discussion](https://gitpod.slack.com/archives/C01KGM9AW4W/p1621335034023700) (internal). /cc @princerachit @corneliusludmann 

### Proposal

TBD (To be discussed)

First MVC (Minimum Viable Change) could be to add replace the status indicator with a checkbox on hover so that users can select multiple workspaces and then click on the _Delete_ button. Additionally, a checkbox at the top of the list to select all and delete all could be also helpful.

An early design spec could be the following:

| Possible solution for multiple workspace deletion |
|-|
| ![image](https://user-images.githubusercontent.com/120486/118643378-28830100-b7e5-11eb-83a5-fe9a0bf8aefa.png) |

**Comment by princerachit** [comment]
Thanks for creating the issue @gtsiolis . I think` adding a checkbox` is better than `replacing the status indicator with checkbox`.
If we replace the status indicator, we are losing information from the dashboard that we initially used to qualify for action. If I accidentally click on an active ws, I have no way of verifying an active ws.

**Comment by apolopena** [comment]
Someone please mark this the with never-stale label

**Comment by gtsiolis** [comment]
DONE, phew! Thanks, @apolopena! 🙂
