### ISSUE TITLE
 gitpod-io[bot] Sends incomplete notification email

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#424]
**Describe the bug**

I get this each time I create a PR in a repository that is configured with Gitpod.
![Screen Shot 2019-04-02 at 10 07 14](https://user-images.githubusercontent.com/1405703/55386406-b204e580-552f-11e9-975c-6303b5ff5460.jpg)

On GH, it looks as expected:
![Screen Shot 2019-04-02 at 10 11 47](https://user-images.githubusercontent.com/1405703/55386437-c21cc500-552f-11e9-85d8-96109e599466.jpg)

I would like to see a message or the proper icon in my mail. Otherwise, it looks like spam.

**Comment by kittaakos** [comment]
Would this work if we get the SVG from the GH domain instead of `gitpod.io/`?

Instead of:
https://gitpod.io/api/apps/github/pbs/github.com/UsernameOrOrganization/RepositoryName.git/3412165a622496609015a963ed214f3c4869decc.svg

Can we do something like? `https://github.com/UsernameOrOrganization/RepositoryName/raw/branchOrTag/path/to/svg`

**Comment by svenefftinge** [comment]
Is CORRS the reason the mail is incomplete?
The SVG is server-side generated, to reflect the status (color).

**Comment by kittaakos** [comment]
> Is CORRS the reason the mail is incomplete?

It is just my guess, but I think so. Any images, gifs that I upload to GH are visible in the mails; it must be related to the domain. This issue is not a top priority; I was just wondering what could cause it.
