### ISSUE TITLE
admin: change plan of user without subscription

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#4245]
# scenario

1. Gitpod employee needs higher workspace concurrency or workspace timeouts
 
<img width="1437" alt="2021-05-19_16-04-39" src="https://user-images.githubusercontent.com/127353/118763874-ef699000-b8bb-11eb-992b-3d1c95ea7a26.png">

# ask

1. Way to switch plans of a co-worker that doesn't involve doing using SQL.

**Comment by corneliusludmann** [comment]
Couldn't we just give all admin users the unleashed plan automatically?

**Comment by ghuntley** [comment]
Testing scenarios tho?

**Comment by csweichel** [comment]
Considering the upcoming changes on this end, and the "professional open source" workaround, I'd argue for not making this change at this point.
