### ISSUE TITLE
Private fork: "repository is not found in your account"

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#425]
**Describe the bug**

A friend of mine is trying to open a private repository in Gitpod, which should be supported.

(Note: It's a personal fork of an upstream private repo living under a GitHub organization, FYI.)

Both GitHub and Access Control say that "private repo" permission is granted. However, when trying to open the repository, this error is shown:

```
username/privatefork could not be found!
The repository is not found in your account.
```

**To Reproduce**

1. Belong to a GitHub organization with private repos*
2. Fork a private repo to your account
3. Try to open it in Gitpod

*That step alone is not enough to reproduce. Maybe there is some particular org setting that prevents even personal forks from being used with third-party apps?

**Expected behavior**

After access is granted, the private repository should open in Gitpod. Instead, the above error keeps showing up.

**Comment by havogt** [comment]
Any news on this? I run into this issue today.

**Comment by liorsbg** [comment]
Just had this issue as well

**Comment by sean-mcclure** [comment]
Also having this issue. I added a private repo via:

    `git remote add github git@github.com:my_name/my_project.git`

...so that I could push to both the original repo and this private one. Now I cannot open GitPod at all. 

My guess is the newly added remote-url cannot be found. If I can't open GitPod I cannot correct any configuration without opening a local IDE and trying to connect that way.

**Comment by JanKoehnlein** [comment]
The `git` protocol for remotes is not supported. Please use `https` instead.

**Comment by Jehong-Ahn** [comment]
Probably, the gitpod need an access for original repo as well as for forked repo.

**Comment by xihajun** [comment]
> The `git` protocol for remotes is not supported. Please use `https` instead.

Can you explain it what does this mean?

**Comment by axonasif** [comment]
> > The `git` protocol for remotes is not supported. Please use `https` instead.
> 
> Can you explain it what does this mean?

Hi @xihajun, what problem are you facing? Are you using git submodules?

**Comment by xihajun** [comment]
Hi @axonasif, so the issue might be I forked a private repo, and tried to use gitpod to edit it. However, I don't have the permission somehow. Not sure how can we grant the permission
