### ISSUE TITLE
 Preview browser becomes unusable if chrome dev tools is open

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#4254]
### Bug description

This bug will affect anyone whos workflow relies on changing the location of the page in the preview browser while using Chrome Dev Tools. Currently there is no way to debug client side javascript so I would expect this to be a common workflow for many people.

When using `gp preview` in conjunction with Chrome Dev Tools, the Simple Browser is rendered into an unusable state. 

Note: I can also get this bug to happen without using `gp` (using the Command Palette)  but only when the VS Code IDE is running in a browser, and not on my local machine. On my local machine I can't even open Chrome Dev Tools for the SImple Browser.
 
![image](https://user-images.githubusercontent.com/3060702/118906830-58103700-b8d3-11eb-90b3-5c9ad0fa3d8f.png)

### Steps to reproduce

1. Open your project in a Simple Browser tab in the VS Code IDE using `gp preview`. 
    - For example: `gp preview $(gp url 8000)`
2. Open Chrome Dev Tools by right clicking in the Simple Browser and choose 'Inspect'
3. Change the path or port to something else valid using `gp preview`.
    - For Example: `gp preview $(gp url 8000)/another-valid-page`

### Expected behavior

The page loaded in the Simple Browser should never be rendered into an unusable state.

### Example repository

Any repository project that serves at least two different web pages.

### Anything else?

Here is a Screenshot of the end result of reproducing the bug. The errors in the Chrome Dev Tools console came from calling `gp preview` the second time after Dev Chrome Tools was open.
![image](https://user-images.githubusercontent.com/3060702/118906790-49298480-b8d3-11eb-9bb1-0b55da4def30.png)

**Comment by corneliusludmann** [comment]
Hi @apolopena!

Thanks for reporting. Unfortunately, I'm not able to reproduce this. What I did:

1. Open a Gitpod workspace, e.g.: https://gitpod.io/#https://github.com/corneliusludmann/gitpod-playground
2. Create a folder/file, e.g.: `mkdir test && touch test/hello.txt`
3. Serve the directory listing as webpage, e.g.: `curl lama.sh | sh`
4. Open preview on port 8080: `gp preview $(gp url 8080)`
5. Right-click on an element in the preview and choose `Inspect`.
6. Run `gp preview $(gp url 8080)/test/`

Result: Preview still looks fine. There seems to be something special in your case. Have you tried to open the preview in a new browser tab instead?

Here is the recording of my experiment:

https://user-images.githubusercontent.com/24960040/119105571-bcd7a880-ba1d-11eb-9a08-44b6b1fc11b7.mp4

**Comment by apolopena** [comment]
Hi @corneliusludmann,
Thank you for looking into this.
I have been able to reproduce this issue using these steps:

1. Open a Gitpod workspace, e.g.: https://gitpod.io/#https://github.com/corneliusludmann/gitpod-playground
2. Serve the directory listing as a webpage using `curl lama.sh | sh`
3. Open preview on port 8080: `gp preview $(gp url 8080)`
4. Right-click on an element in the preview and choose `Inspect`
5. Run `gp preview $(gp url 8080)/README.md`

Here is a recording:

https://user-images.githubusercontent.com/3060702/119173114-a597bb80-ba1b-11eb-8344-bd7bb90b8607.mp4

**Local Machine Specs**:
Windows 10 Pro: build 10.0.19041.906
Chrome: Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by corneliusludmann** [comment]
Thanks for the update! I tried your steps but unfortunately without getting the same result. I'll ask the team if someone could reproduce this.

For the records: I'm on Arch Linux with Chrome Version 90.0.4430.212 (Official Build) (64-bit)

**Comment by apolopena** [comment]
Not stale

**Comment by apolopena** [comment]
I am sorry wrong bug, this can stay closed. I do see this issue but hardly ever anymore
