### ISSUE TITLE
 Option to switch IDE in the configuration file 

### ISSUE THREAD

**Issue by tani** [gitpod-io/gitpod#4258]
Hi, there! I request adding a configuration-option/URL-queries to switch IDE for each project. Currently, we have an option to set default IDE in the dashboard. So we can only one specific IDE at once. But some of the extensions are incompatible with one of the twos. I want to write something as follows in .gitpod.yml for each project.

```yml
ide: vscode
```

This request is previously discussed at
https://community.gitpod.io/t/option-to-switch-ide-in-the-configuration-file/3667

> tani 
> Is there any option to specify which IDE should use, VSCode or Theia, in gitpod.yml?
I want to use Theia IDE basically, but some of the plugins are incompatible with Theia. Thus, I want to switch IDE for a few project. Currently, I know only option switching IDE globally.
If no, I request to add such an option. Thanks.

> jan
> Hi @tani!
>
>>    Is there any option to specify which IDE should use, VSCode or Theia, in gitpod.yml?
>
> Unfortunately, this isn’t possible yet. The only way to switch between IDEs is:
>
> 1. switch “Default IDE” in https://gitpod.io/preferences
>
> 2. (re)start a workspace to get the newly selected IDE (currently-running workspaces will not hot-swap IDE, but restarting an old workspace will pick up the new IDE)
>
> Regarding an option to set this in your .gitpod.yml, could you please open a Feature Request here? https://github.com/gitpod-io/gitpod/issues/new/choose
> 
> Also, an alternative idea could be to allow overriding the Default IDE via the context URL, e.g. via something like https://gitpod.io/?ide=theia#https://github.com/org/repo (thinking out loud here)

**Comment by akosyakov** [comment]
We are going to deprecate Theia rather soon. Could elaborate  why VS Code does not work for you in some repos?

**Comment by tnir** [comment]
@akosyakov How rather soon?

**Comment by akosyakov** [comment]
@tnir plan was by now already :D but we have other pressing matters

**Comment by tani** [comment]
@akosyakov We are going to deprecate Theia rather soon. Could elaborate why VS Code does not work for you in some repos?

Some browser extensions break VSCode. For example, I faced such a problem with Firefox and ClearURLs, which extension removes tracking code in URLs on webpages. Of course, Theia works well for me.

ref: https://community.gitpod.io/t/incompatible-browser-extensions-for-gitpod/3888

**Comment by akosyakov** [comment]
Please file a new issue for browser extensions which break VS Code. It also would be good to report in upstream: https://github.com/microsoft/vscode

Theia is going away in August: https://github.com/gitpod-io/gitpod/issues/4459 I close this issue since ti does not make sense to add a switch.

**Comment by tani** [comment]
@akosyakov I see. Thank you.
