### ISSUE TITLE
Gitpod v0.9.0-alpha3

### ISSUE THREAD

**Issue by stefanstoeckigt** [gitpod-io/gitpod#4260]
### Bug description

ws-proxy pod fails to deploy. 

The ws-proxy show the following error:

```json
{
    "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
    "error": "tls: private key does not match public key",
    "level": "fatal",
    "message": "cannot start proxy",
    "serviceContext": {
        "service": "ws-proxy",
        "version": ""
    },
    "severity": "CRITICAL",
    "time": "2021-05-20T10:50:06Z"
}
```

The certificated have not changed between updates, and this issue didn't occur in  v0.8.0. https works on the main page. 

### Steps to reproduce

Update to v0.9.0-alpha3.

**Comment by asthomasdk** [comment]
Any possible work-arounds to this one?

**Comment by stefanstoeckigt** [comment]
@asthomasdk, @corneliusludmann 

I managed to get the ws-proxy running. The issue seemed to be in the ws-proxy-config. 

```
 "proxy": {
        "https": {
            "crt": "/mnt/certificates/chain.pem",
            "key": "/mnt/certificates/privkey.pem"
        },
```

changed to: 

```
 "proxy": {
        "https": {
            "crt": "/mnt/certificates/cert.pem",
            "key": "/mnt/certificates/privkey.pem"
        },
```

It looks like the chain is getting used instead of the cert in the proxy config. 
You can also just add the following to the chart values file and it seems to fix the issue also. 

```
certificatesSecret:
  secretName: https-certificates
  keyName: privkey.pem
  chainName: cert.pem
  fullChainName: fullchain.pem
```

**Comment by asthomasdk** [comment]
@stefanstoeckigt cool!
I will give this a try and see if I can get alpha3 up and running - and working.

**Comment by asthomasdk** [comment]
Seems to do the trick. Thanks!

Now to test if I can use this release ;-)

**Comment by corneliusludmann** [comment]
@solomonope FYI

**Comment by asthomasdk** [comment]
FYI - I have managed to get a working environment (almost) using : 

- ubuntu 20.04 (making sure `open-iscsi` is installed) 
- latest k3s (1.20) (without callico, started with : 
 `--disable=traefik --disable-network-policy --kubelet-arg=cloud-provider=external --node-label gitpod.io/main-node=true --node-label gitpod.io/workload_meta=true`
- with a few tweaks in a `values.custom.yaml` file

I am however, having some issues with DNS, as I cannot log into external docker registries from a terminal in the workspace. 

Overall a huge step forward from the last month of trying to get something up an running!

**Comment by ghuntley** [comment]
👋 Howdy folks; v0.10.0 has been released and we recommend upgrading. Closing out this issue please open a new one related to v0.10.0 if required.
