### ISSUE TITLE
Dashboard - Dark mode - Confirm delete modal: cannot read context ID

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#4264]
### Bug description

![image](https://user-images.githubusercontent.com/3060702/119019081-a6fcb180-b951-11eb-9ad9-d7d76810716a.png)

### Steps to reproduce

Delete an inactive workspace whilst in Dark Mode.

The top line of text in the field is white on white.

### Expected behavior

All text should be readable. 

### Example repository

Any

**Comment by corneliusludmann** [comment]
Thanks for reporting.

@gtsiolis: Is this known/fixed in main already?

**Comment by gtsiolis** [comment]
Thanks for noticing @apolopena and for the ping @corneliusludmann! Yes, this is known (see https://github.com/gitpod-io/gitpod/issues/4100#issuecomment-839596793) but let's keep this issue open to tackle separately as an minimum viable change if possible. 🚲

**Comment by gtsiolis** [comment]
This has been resolved in https://github.com/gitpod-io/gitpod/pull/4408.
