### ISSUE TITLE
[code] new VS Code API for window.open doesn't work

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#4266]
### Bug description

VS Code introduced a new API in `dom.ts` to open a new browser tab and return true on success. That way thex can show a dialog when popups are disabled. 
https://github.com/microsoft/vscode/blob/4b5db9098c251f0582dc60d478f80f228020559d/src/vs/base/browser/dom.ts#L1212

Their impl doesn't work as expected, and brings back the problem that when the app in the new tab is stopping on a breakpoint it stalls the original tab with the IDE. To avoid that you must use the `noopener` option when opening the window, causing the new tab to run in a separate event loop. The workaround in VS Code, setting the `opener` to `undefined` after `window.open()` doesn't work.

Furthermore, Chrome seems to have a bug in its popup blocking. We tried using a plain `window.open()` first to detect whether popups are blocked, then closed the resulting window on success and opened it a new wit `noopener`. For some reason the first `open` succeeds the first time even though popups are disabled, and the second one is always blocked regardless of `noopener` or popup blocking settings. 

As a result, we currently cannot detect whether a `window.open()` was successful so we won't see this dialog.

### Steps to reproduce

Missing dialog:
- Start Gitpod on the [Svelte example](https://github.com/gitpod-io/sveltejs-template)
- make sure popups are disabled
- try to open the app in a new tab
- > it doesn't open and there is no feedback other than the "popup blocked" marker in Chorme's URL bar

`noopener` issue:
- Restore VS Code's default behavior
- Start Gitpod on the [Svelte example](https://github.com/gitpod-io/sveltejs-template), open the served page in a new window, set a breakpoint in `bundle.js` and reload the tab.
- > the app halts at the breakpoint and the IDE in the original tab is stalled as well.

### Expected behavior

The original tab with the IDE should keep running.

**Comment by akosyakov** [comment]
It turned out that VS Code added the dialog for Safari, since it does not have a pop-up. I changed it during last Upgrade to use the dialog only for Safair, and for other browsers rely on browser pop-up.
