### ISSUE TITLE
fix content assist in .gitpod.yml

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#427]
I don't see content assist in .gitpod.yml always. Sometimes is there, sometimes no. Very typical case that `onOpen` for ports is not provided.

**Comment by geropl** [comment]
In my experience it's super picky when to provide assist and when not, too. Have not detected any pattern yet.

**Comment by svenefftinge** [comment]
seems like it has to be valid yaml syntactically.
