### ISSUE TITLE
"New Git Integration" dialog - Match field labels with the provider's naming

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#4275]
When creating an OAuth app, GitLab and GitHub provide slightly different names for what we refer to as "Client ID" and "Client Secret" in the UI.

I suggest we display field labels depending on which provider is selected based on the following matrix:

|               | GitLab         | GitHub        |
|---------------|----------------|---------------|
| Client ID     | Application ID | Client ID     |
| Client Secret | Secret         | Client secret |

This change will make it easier to follow the instructions in the documentation as there is no need to explain the above mapping to readers.

**Comment by jordanhailey** [comment]
Hey @mikenikles, following up from our chat in the Svelte Discord, hopefully this first contribution is helpful!

I couldn't figure out how to run an instance of Gitpod on my own Gitpod account. From looking over the forum I [found a relevant post](https://community.gitpod.io/t/i-would-want-bring-contribution-into-building-the-new-dashboard-but-cant-access-to-designs/2969) that seems to indicate that the team needs to initiate a build, after which in which I can get temporary access to run the application and see my changes? Let me know if that will be required for this change. 

My solution was fairly straightforward, but there is one `useEffect` function I've added that should either be pulled out or ran through a QA review.

**Comment by gtsiolis** [comment]
Resolved in https://github.com/gitpod-io/gitpod/pull/4287. Thanks @jordanhailey for contributing! 🌟
