### ISSUE TITLE
Command 'Add to .gitpod.yml' resulted in an error 

### ISSUE THREAD

**Issue by yogeek** [gitpod-io/gitpod#4277]
### Bug description

First time testing gitpod and it did not go as well as expected : after having installed the gitpod chrome extension, and opened gitpod by clicking the `Gitpod` green button in my github repo, I wanted to configure my gitpod project as dicumented in [Configure Your Project](https://www.gitpod.io/docs/configuration) but :

-  no VSCode notification proposed me to configure a project
- no "Toggle Project Setup View" option is available in VSCode wizard (F1)
- the only option I find is "Add to .gitpod.yml" but leads to the error below :

```
Command 'Add to .gitpod.yml' resulted in an error (Running the contributed command: 'gitpod.extensions.addToConfig' failed.)
```

How can I configure a gitpod project then...?

### Steps to reproduce

cf. Bug description

### Expected behavior

I expected to see the VSCode notification the first time I opened a project to configure it within gitpod as stated in https://www.gitpod.io/docs/configuration

### Example repository

https://github.com/yogeek/podinfo

**Comment by JanKoehnlein** [comment]
The docs refer to Theia. We haven't ported this to the VS Code extension yet. The docs are being re-done ATM.
We're also currently redesigning the entire onboarding flow which will cover this usecase.
In the meantime, you can run `gp init -i` form the terminal in your workspace to got through the initialization steps.

**Comment by svenefftinge** [comment]
We have updated the docs accordingly, now. Sorry for the confusion
