### ISSUE TITLE
Publish Gitpod Light and Dark themes on Visual Studio Marketplace and Open VSX 🍊

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4281]
### Problem to solve

The Gitpod Light and Dark themes are currently bundled in the VS Code editor, see [`theme-defaults`](https://github.com/gitpod-io/vscode/tree/gp-code/extensions/theme-defaults/themes).

This makes both themes _not_ available to install on VS Code locally.

See also [relevant discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1618832330030500) (internal).

### Proposal

Given there's also a product roadmap item for a [Local Companion App](https://www.notion.so/Product-Roadmap-b9b5eac0a15147ac8d2dd25cf0519203#136fd9303a6e4105a9bb8bbe32e0a307) it could be useful to publish both themes on [Visual Studio Marketplace](https://marketplace.visualstudio.com/) and [Open VSX](https://open-vsx.org/). 🍊

**Comment by gtsiolis** [comment]
Re-opening as this is still relevant.

**Comment by jeanp413** [comment]
I created the repo https://github.com/gitpod-io/gitpod-vscode-theme
Need to setup the secrets so I can publish to the MS marketplace and open vsx
@gtsiolis maybe you want to create a new icon for the extension to differentiate it from gitpod-desktop and gitpod-remote extensions

**Comment by gtsiolis** [comment]
@jeanp413 Good point! I think we can be playful and use something like the following. What do you think?

| Image | Image in context | 
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/167497548-4593f2eb-6607-47d9-9c18-c834d31b08b3.png) | <img width="602" alt="Screenshot 2022-05-09 at 11 53 41 PM" src="https://user-images.githubusercontent.com/120486/167497562-89c58b5d-22d5-464e-b91b-8667d5b11e81.png"> |

**Comment by jeanp413** [comment]
Still needs publishing to MS marketplace, need new key to publish

**Comment by jeanp413** [comment]
Extension is published in both open-vsx and MS marketplace, closing this

**Comment by gtsiolis** [comment]
Thank you, @jeanp413! 🎉
