### ISSUE TITLE
Browser shortcuts interfere with VSCODE keybindings

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#4289]
### Bug description

Hi,
This is a really annoying issue I face very often.
There are some certain browser shortcuts which are likely not possible for javascript to take over I assume.
I use firefox-87 on linux, I experienced the same sort of issue in chrome as well IIRC.

### Steps to reproduce

Try using on of the following shortcuts in gitpod-vscode:
* Ctrl + W
* Ctrl + T
* Ctrl + Shift + P
* And a few others which I can not remember right now.

Maybe I could just rebind these keys to something else but I'm just already used to them, so...

### Expected behavior

VSCODE being able to overriding some of the strict browser shortcuts if possible.

**Comment by axonasif** [comment]
I found a viable solution to this issue, that is to save gitpod as an app shortcut from chromium based browsers. I also found that a chromium extension called [Gitpod Window](https://chrome.google.com/webstore/detail/gitpod-window/jhpkbhdoenpnfnnkelgpikndadikogdl?hl=en-US) does pretty much the same thing but even better!

**Comment by jimmybrancaccio** [comment]
@axonasif Yeah, I think I started to realized that after I started investigating it after my previous comment. I believe there's a way to unbind them from the web browser, but I am not 100%. That said, the UI is misleading (as seen in my screenshot).

**Comment by koppor** [comment]
Note that Gitpod offers <kbd>F1</kbd> as alternative to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> ("Command Palette...")
