### ISSUE TITLE
Can't find `pip install`ed package in `$PATH`

### ISSUE THREAD

**Issue by janomkernes** [gitpod-io/gitpod#429]
**Describe the bug**
I've installed a package with `pip install`, but I can't run it.

**To Reproduce**
1. New Gitpod workspace
2. Run `pip install codespell`
3. Run `codespell -w` (to fix spelling mistakes in a project dir)

Shows this error:

```
gitpod /workspace/hello-world $ codespell -w
bash: codespell: command not found
```

**Expected behavior**
I should be able to run `codespell` after installing it.

FYI, this is my `$PATH`:

> /home/gitpod/.cargo/bin:/workspace/.rvm/bin:/home/gitpod/.cargo/bin:/home/gitpod/.rvm/gems/ruby-2.6.0/bin:/home/gitpod/.rvm/gems/ruby-2.6.0@global/bin:/home/gitpod/.rvm/rubies/ruby-2.6.0/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/home/gitpod/.pyenv/shims:/home/gitpod/.sdkman/candidates/maven/current/bin:/home/gitpod/.sdkman/candidates/java/current/bin:/home/gitpod/.sdkman/candidates/gradle/current/bin:/home/gitpod/.pyenv/bin:/home/gitpod/.pyenv/shims:/home/gitpod/.nvm/versions/node/v10.15.3/bin:/workspace/go/bin:/home/gitpod/go/bin:/home/gitpod/go-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/gitpod/.rvm/bin:/home/gitpod/.rvm/bin

**Comment by AlexTugarev** [comment]
I think this should do the trick: 
```
export PATH=/workspace/.pip-global/bin:$PATH
export PIP_INSTALL_OPTION="--install-scripts=/workspace/.pip-global/bin"
```

Looking at the code of pip, I think it's a bug. They are reusing a function to "prepare" the target dir for scripts which raises. This is fine for the package directory, as you don't want to override. But it's not ok for the script dir. Also, it's different in case this is installed to the default site location.
