### ISSUE TITLE
Unable to delete workspace when building image is stuck

### ISSUE THREAD

**Issue by yyoncho** [gitpod-io/gitpod#4294]
### Bug description

When debconf kicks in during apt-get when building an image - all is stuck and deleting that workspace is not possible. 

Here it is the error from chrome console:

```
Uncaught (in promise) Error: Request deleteWorkspace failed with message: Unknown workspace manager ""
    at main.js:449
    at main.js:276
    at main.js:260
    at setImmediate.js:40
    at f (setImmediate.js:69)
    at n (setImmediate.js:109)
```

### Steps to reproduce

use this repo https://github.com/yyoncho/lsp-gitpod3

### Expected behavior

being able to delete the workspace

### Example repository

https://github.com/yyoncho/lsp-gitpod3

**Comment by AlexTugarev** [comment]
Might be related https://github.com/gitpod-io/gitpod/issues/4173

**Comment by yyoncho** [comment]
Yes, it is - closing as duplicate.
