### ISSUE TITLE
Missing terms of service approval on Gitlab causes login error and related SLO impact

### ISSUE THREAD

**Issue by rl-gitpod** [gitpod-io/gitpod#4296]
New GitLab users who did not accept ToS on gitlab.com, but trying to sign up with Gitpod will be logged as a login failure:

> Error: 403 Forbidden - You (foo) must accept the Terms of Service in order to perform this action. Please access GitLab from a web browser to accept these terms

This impacts the SLO and can result in GitpodLoginErrorBudgetBurn alerts.

Suggestion from @AlexTugarev is "Maybe we need to reduce the log level for this error case."

**Comment by AlexTugarev** [comment]
Sidebar on how to reproduce this:
0. be logged out of Gitpod and GitLab
1. try to sign up a Gitpod account and select GitLab to continue with
2. on GitLab pages select to create a new account using Google OAuth (for instance)
3. after finishing the GitLab account creation you will be redirected to Gitpod
4. see the GitLab OAuth rejected

If you would create a new GitLab account in step 3. using the regular sign-up form and email address, it would actually result in a confirmed GitLab account and no OAuth error in Gitpod.

**Comment by ArthurSens** [comment]
Just a heads up, reducing log level for this error won't make any difference on the alert. 

It's the login metric that can't be increased for this particular error 😬

**Comment by ArthurSens** [comment]
This change was deployed yesterday and, unfortunately, [the burn rate for Gitlab logins](https://grafana.gitpod.io/d/login-slo/gitpod-slos-login?orgId=1&refresh=1m&from=now-24h&to=now) is still very high.

![image](https://user-images.githubusercontent.com/24193764/126783562-3c312d16-76b8-403d-89bb-2ef2055ae3ae.png)

Should this Issue be reopened and re-added to Groundwork?

**Comment by AlexTugarev** [comment]
@ArthurSens and @csweichel, it's a one-line fix: https://github.com/gitpod-io/gitpod/pull/4944
