### ISSUE TITLE
Pull GitPod configs from user's repositories

### ISSUE THREAD

**Issue by nugend** [gitpod-io/gitpod#43]
The https://github.com/gitpod-io/definitely-gp repo is a great idea for getting public projects to work smoothly with GitPod. However for several reasons, there's a need to allow users to specify customized GitPod configurations that aren't global and aren't in the loaded projects' repository.

As an alternative, it would be very nice to check a user's repo list and detect if they have a "definitely-gp" repository and *always* prefer the config found there over the other public sources (the preference order would be: user/definitely-gp > project's .gitpod file >  gitpod/definitely-gp).

This would allow the user ultimate control over the .gitpod configuration.

**Comment by AlexTugarev** [comment]
Hi @nugend! You are absolutely right, that is necessary, and we already support `.gitpod` files in user's repositories. 👍
You can read more on this in the [docs](https://docs.gitpod.io/40_Configuration.html#gitpod-file).

**Comment by AlexTugarev** [comment]
Oh, sorry! You'd like to have your `user/definitely-gp` scanned for `.gitpod` files.

**Comment by meysholdt** [comment]
I like the idea of `user/definitely-gp`. Additionally to what @nugend mentioned I like that it enables the following process:
1. fork `gitpod/definitely-gp`
2. add/modify and test `.gitpod` files in `user/definitely-gp` (which is the fork)
3. submit a PR to `gitpod/definitely-gp` :)

**Comment by nugend** [comment]
I still think this is a nice idea
