### ISSUE TITLE
Can't delete workspace in "Unknown" state

### ISSUE THREAD

**Issue by fntlnz** [gitpod-io/gitpod#4329]
### Bug description

In my workspaces dashboard I have a workspace in state "Unknown", I cannot delete or open it in any way

This is the javascript console log.
<img width="815" alt="image" src="https://user-images.githubusercontent.com/3083633/119952663-8cec5000-bf9d-11eb-9da8-30b4ac9093c5.png">

Workspace row in my dashboard
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/3083633/119952734-9c6b9900-bf9d-11eb-9e3a-5cd6ee3b4159.png">

### Steps to reproduce

I don't know how to reproduce this. I just opened the leeway workspace via `https://gitpod.io/#https://github.com/gitpod-io/leeway` and after working on it for a little bit I stopped using it.

### Expected behavior

The workspace is in a known state and can be deleted or opened

**Comment by gtsiolis** [comment]
Hey @fntlnz, are you still seeing this? Cc @corneliusludmann because https://github.com/gitpod-io/gitpod/issues/3635#issuecomment-853072205.

**Comment by fntlnz** [comment]
No, this is gone. We can close
