### ISSUE TITLE
vscode extensions

### ISSUE THREAD

**Issue by artalar** [gitpod-io/gitpod#433]
Hi, thx for awesome Gitpod, it very helps me! But my preferred type system for JS is Flow and currently is not friendly for Gitpod because have not integrations.
In [this](https://youtu.be/HbTKDlOL1eo) video Thiea already have vscode extensions (which have flow integration too), when it may come to Gitpod?

**Comment by svenefftinge** [comment]
Adding the Flow extension is high on the list.

**Comment by sr229** [comment]
We already have VSCode extensions support in the upstream project, but AFAIK Gitpod people are working hard to bring these extensions to the IDE.

**Comment by akosyakov** [comment]
We are going to allow installing them per a workspace at first.

**Comment by justinmoon** [comment]
It would be nice if one could "pre-install" extensions `gitpod.yml`

**Comment by svenefftinge** [comment]
> It would be nice if one could "pre-install" extensions .gitpod.yml

Indeed. That's the plan. :)

**Comment by Vlaaaaaaad** [comment]
Is there an ETA for this or PRs/ issues we can track?

**Comment by svenefftinge** [comment]
This is the issue to track. Since we can't really test all 10k extensions and we know there are some parts not fully implemented we plan to release a beta version of this feature mid July.
It will allow to install VS Code extensions and declare them as part of the `.gitpod.yml`.

**Comment by svenefftinge** [comment]
We have released an initial beta version.
See https://www.gitpod.io/docs/vscode-extensions/
