### ISSUE TITLE
Issue when opening my workspace - failed to create containerd task

### ISSUE THREAD

**Issue by Tmuat** [gitpod-io/gitpod#4330]
### Bug description

`failed to create containerd task: failed to mount rootfs component &{overlay overlay [workdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19557/work upperdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19557/fs lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19556/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19555/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19554/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19553/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19552/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19551/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19550/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19549/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19548/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19547/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19546/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19545/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19544/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19543/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19542/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19541/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19540/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19539/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19538/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/19537/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/197/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/196/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/195/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/194/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/193/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/192/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/191/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/190/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/189/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/188/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/187/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/186/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/185/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/184/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/183/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/182/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/181/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/180/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/179/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/178/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/177/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/176/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/175/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/174/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/173/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/172/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/171/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/170/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/169/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/168/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/166/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/165/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/164/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/163/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/162/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/161/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/159/fs]}: failed to mountat: failed to find pid=1840864 process: no child processes: unknown`

### Steps to reproduce

When opening workspace

**Comment by corneliusludmann** [comment]
Hi @Tmuat,

Could you please share some additional information:
- Does it still happen?
- Could you share a workspace ID (first part of the URL, something like `lavender-unicorn-ezokqazf`) of one of your workspaces that are affected?
- On which cluster does your workspace land (second part of the URL, something like `ws-eu08`)?
- Is it a public repo? If yes, could you please share the repo URL?
- Is it an existing workspace that you try to re-open/re-start or a new/fresh workspace?
- Do you have feature preview enabled in your settings?

**Comment by jankeromnes** [comment]
Likely related to https://github.com/gitpod-io/gitpod/issues/3986

**Comment by svenefftinge** [comment]
This happens quite regularly (~ every 20 minutes) we are working on moving to self-managed kubernetes clusters that would sport a recent version of containerd, which than hopefully fixes this.

**Comment by danisafta** [comment]
> Many thanks for the report!
> 
> This issue is likely related to #3986 -- from what I understand, this is a known, rare bug in the `containerd` version we use in Gitpod.
> 
> Simply trying to open the same workspace again should successfully work around the problem.
> 
> We'd like to upgrade our `containerd` version soon to fix this for good, but I think this will take some time.

what version of containerd are you using and what version fixes this? I have encountered the same problem on v1.4.6. Is there any specific commit that fixes this?
