### ISSUE TITLE
Errors on some workspaces

### ISSUE THREAD

**Issue by davidwindell** [gitpod-io/gitpod#4331]
### Bug description

As per the below, **since yesterday** some workspaces are failing to load properly. For example, VS code default settings not applying (i.e. theme in screenshot should be dark) and all ports are showing as pending. Eventually, it seems to resolve itself after a few hours and starting more workspaces. 

![screenshot-nimbus-capture-2021 05 28-09_20_31](https://user-images.githubusercontent.com/1720090/119953914-60810580-bf96-11eb-98d4-d17228e093c7.png)

### Steps to reproduce

TBC

### Anything else?

An example workspace with this error is `violet-crab-b0j4h3ki.ws-eu07.gitpod.io`

**Comment by svenefftinge** [comment]
I'm seeing the same just now.
Relevant [logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-05-28T10:27:31Z;query=resource.labels.pod_name%3D%22ws-5a34ec99-1a01-4eec-bc7e-0e709ec90704%22%0Atimestamp%3D%222021-05-28T10:27:31Z%22%0AinsertId%3D%22w75p63fruhd2j%22?project=gitpod-191109) are:

<img width="708" alt="Screenshot 2021-05-28 at 12 43 40" src="https://user-images.githubusercontent.com/372735/119972317-5a008700-bfb2-11eb-88a8-f896946b97df.png">

**Comment by svenefftinge** [comment]
this has been resolved now
