### ISSUE TITLE
Workspace fails initializing

### ISSUE THREAD

**Issue by Carlos-Schrodinger** [gitpod-io/gitpod#4335]
### Bug description

Whenever i try to start a workspace i just get this message:
![image](https://user-images.githubusercontent.com/48862659/119990292-71e30580-bfc8-11eb-9eae-b6d51992b6aa.png)

### Steps to reproduce

1. Open a empty github repo
2. Open on gitpod
3. Bug

### Expected behavior

To open a new workspace and the IDE.

### Example repository

any

### Anything else?

Running chrome dev branch

**Comment by Carlos-Schrodinger** [comment]
![image](https://user-images.githubusercontent.com/48862659/119990481-aa82df00-bfc8-11eb-9cc0-71d27faa919a.png)
![image](https://user-images.githubusercontent.com/48862659/119990511-b4a4dd80-bfc8-11eb-80c3-c7c26da907c2.png)

**Comment by Carlos-Schrodinger** [comment]
https://share.wildbook.me/Fv0UojxLqV2Xgull.webm

A small video of what happens whenever i try running a workspace.

**Comment by jankeromnes** [comment]
Many thanks for reporting this @Carlos-Schrodinger! It's due to a recent change to the workspace initializer, and only affects opening empty repositories.

We'll try to deploy a fix as soon as possible.

**Comment by Carlos-Schrodinger** [comment]
> Many thanks for reporting this @Carlos-Schrodinger! It's due to a recent change to the workspace initializer, and only affects opening empty repositories.
> 
> We'll try to deploy a fix as soon as possible.

Alright, for now i'll add a README to the repo.

**Comment by asthomasdk** [comment]
I am seeing the same issue on 0.9.0-alpha3 self-hosted.


Regards

Thomas Hansen
Director
____________________________
appSolutions a|s

________________________________

**Comment by Carlos-Schrodinger** [comment]
Made the readme, seems to be working! Thanks ;-)
![image](https://user-images.githubusercontent.com/48862659/119994204-a953b100-bfcc-11eb-9890-4222776fee4a.png)

**Comment by jankeromnes** [comment]
(We've implemented a fix, but still need to deploy it to production.)

**Comment by jankeromnes** [comment]
Fix deployed and gitpod.io can open empty repositories again. 🎉
