### ISSUE TITLE
Support for R

### ISSUE THREAD

**Issue by dolichoderus** [gitpod-io/gitpod#434]
Many biologists and data scientists use R but neglect versioning or struggle with setting up a reproducibil R environment. Having a R-ready gitpod would be great to accelerate research while ensuring reproducibility.

**Comment by jankeromnes** [comment]
Hi @dolichoderus, thanks for the helpful suggestion! Please have a look at [this R-ready one-click example](https://twitter.com/gitpod/status/1106532059223347200?s=19). Is this similar to what you had in mind?

**Comment by JesterOrNot** [comment]
Any updates per the status of this issue?

**Comment by JesterOrNot** [comment]
Then should we close this issue?

**Comment by jankeromnes** [comment]
Indeed, because R is supported. 🎉

We should also add a quick `r_in_gitpod.md` language guide to https://github.com/gitpod-io/website/tree/master/src/docs with a good R example setup.
