### ISSUE TITLE
Lost all work from yesterday?

### ISSUE THREAD

**Issue by Winnypohh** [gitpod-io/gitpod#4341]
I lost all my add . commit work yesterday twice and can't see my work I have early commit but that is 16 days ago? Got working I made mistake forgot to push!

**Comment by svenefftinge** [comment]
You can start your old workspaces again and push the pending changes.
Go to https://gitpod.io/workspaces and change the filter to show all workspaces as shown in the screenshot below:

<img width="1415" alt="Screenshot 2021-05-31 at 08 40 42" src="https://user-images.githubusercontent.com/372735/120150987-08434100-c1ec-11eb-8e8c-945d8ac2faac.png">

**Comment by JanKoehnlein** [comment]
Please re-open when the problem persists.
