### ISSUE TITLE
RegistryFacade should shut down gracefully to support k8s RollingUpdates

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#4343]
Currently, we avoid re-deploying registry-facade because this terminates all TCP connections and apparently (I did not verify) containerd (the only client of registry-facade) does not resume image pulls if a connection dies. This leads to failed workspaces startups. 

Proposed solution: A registry-facade pod should keep running until all its connections have closed naturally (because all layer-downloads have finished). This would allow us to update registry-facade via k8s rolling update like every other k8s workload. This would reduce the number of cases for which we need to create fresh workspace clusters. Also, this would benefit (self-hosted) users that operate Gitpod in fat clusters. 

The process would go as follows
1. The k8s RollingUpdate would start "terminating" pods, which means
2. The pod stops receiving new connections (good!)
3. The pod receives the `SIGTERM` signal. Here, RegistryFacade should *not* stop immediately stop but wait until the last connections has disconnected and then stop.
4. K8s will wait until the `terminationGracePeriodSeconds` has passed before sending the `KILL` signal. We should set this value to a number greater than 99% of all image-pull-durations. Maybe 20 minutes. 

In practice, I would expect registry facade to only take a few seconds to a minute to stop, because most layer pulls only take seconds. Keep in mind that even our 6GB+ workspce-full image is comprised of 30+ layers.

Todo: 
* implement that on `SIGTERM`, registry facade does not stop until all connections drained. 
* set `terminationGracePeriodSeconds` in [registry-facade-daemonset.yaml](https://github.com/gitpod-io/gitpod/blob/main/chart/templates/registry-facade-daemonset.yaml)
* Bonus: a metric that exposes the number of currently open connections. 

Further Reading:
* [Kubernetes best practices: terminating with grace](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace)
* [Termination of Pods](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace)

**Comment by csweichel** [comment]
Prior to Kubernetes 1.21 daemonSets don't support rollouts (see https://github.com/kubernetes/kubernetes/issues/48841) which - if we implemented the process above - would leave us in a situation where the old registry-facade doesn't accept new connections i.e. image pulls until all on-going pulls are completed. This would result in an essentially broken cluster.

We should revisit once daemonSet rollouts are available.

**Comment by csweichel** [comment]
I'd propose we close this issue until k8s supports rolling updates for daemonSets.
