### ISSUE TITLE
HTML file inside Tasmota

### ISSUE THREAD

**Issue by storchalberto** [gitpod-io/gitpod#4348]
It is possible to upload a file on the device and retreive it from a browser using the ip of the device and a path?
I have uploaded a file (SetColors.txt) on my device, but if i try to access it (http://x.x.x.x/SetColors.txt x.x.x.x=device ip address) i receive the message:

File Not Found

URI: /SetColors.txt
Method: GET
Arguments: 0

**Comment by corneliusludmann** [comment]
Hi @storchalberto,

I wonder if you landed in the right place. This is the issue tracker of [Gitpod](https://gitpod.io/). If I understood you correctly, you have a question about Tasmota, the open source firmware for ESP8266 devices, right? Maybe you'd better ask there?

**Comment by storchalberto** [comment]
Thanks, I am using a ESP32 module. I need to upload an html page inside the device and retreive it from my browser (using the ip address of the device). I have downloaded in the Tasmota the file Prova.html and i see that it is possible to edit the page uploaded using the command http://x.x.x.x/ufse?file=/Prova.html, but I need an url on the tasmota that allow the file to be received as a standard html page. Pratically i need that the Tasmota operate as a reduced WEB server.
