### ISSUE TITLE
[browser-ext] change email address for feedback

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#4356]
Currently, feedback on uninstall goes to contact@. We should rather use a distinct address.

**Comment by corneliusludmann** [comment]
@JanKoehnlein Do we have already an address that we can use for this?

**Comment by JanKoehnlein** [comment]
Ask Kai

**Comment by corneliusludmann** [comment]
Actually, the [feedback page is part of the website](https://github.com/gitpod-io/website/blob/f4f639123a5789e0f814ea9e1fce4e7d2df93be2/src/routes/extension-uninstall.svelte), not the browser extension. I'm not sure where the `to` address is configured.

@mikenikles Do you know how to change the address?

**Comment by JanKoehnlein** [comment]
@mikenikles could you also check whether this is page in sync with the usual contact form? We seem to get the same message multiple times and I remember this as a bug we fixed a few weeks ago. 

Addressing it to some address like service+gp-extension-uninstall@gitpod.io should do

**Comment by mikenikles** [comment]
Christin is miles ahead of us :). Closing this issue in favour of https://github.com/gitpod-io/website/issues/454 to collect this feedback in a spreadsheet rather than via email.
