### ISSUE TITLE
Bug: is possible to utilize plan student unlimited for one month free forever

### ISSUE THREAD

**Issue by JohnAnon9771** [gitpod-io/gitpod#4357]
### Bug description

This bug allows users to use the student unlimited plan for one month forever. Each student using the Github student package has a coupon to use on the personal plan, but when the user switches to the unlimited student plan, gitpod did not ask for any further payment information, perhaps due to the coupon being used now on that new plan... I don't know. With this, the user can use the student unlimited plan forever.

### Steps to reproduce

Just follow the video step by step below:

https://user-images.githubusercontent.com/42195321/120265505-99f79080-c276-11eb-84b4-77bc7fb9d9d4.mp4

### Anything else?

Then I discovered this bug a month ago. Sorry for not telling you soon, as I wanted to test to verify that it wasn't just a visual bug but that it was actually possible to use all the benefits of the student unlimited plan.

I hope you don't withdraw the promotion for students, this is helping me a lot, thanks for the affection with the students.

I love gitpod, thank you so much for the work you guys have been doing. ❤️

**Comment by AlexTugarev** [comment]
Thanks for reporting @JohnAnon9771! 🙏🏻 

This is a known limitation of our payment system, and this Student Pack coupon trick is applicable just one time.
