### ISSUE TITLE
[subscription] investigate user cancellation

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#4359]
### Bug description

Some users report they cancelled but are still charged. Investigate whether that's possible.

### Steps to reproduce

See above

**Comment by gtsiolis** [comment]
Cross-posting [relevant discussion](https://gitpod.slack.com/archives/C01KGM9C9BQ/p1620895738190700) (internal) (cc @jankeromnes) and a [recent report](https://gitpod.slack.com/archives/C01KGM9C9BQ/p1621947625037800?thread_ts=1620895738.190700&cid=C01KGM9C9BQ) (internal) (cc @geropl).
Thanks for opening this, @JanKoehnlein! 🏀
