### ISSUE TITLE
When opening an issue in Gitpod, the IDE now wants to push to the wrong upstream branch

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4366]
### Bug description

![gitpod-push-to-wrong-branch](https://user-images.githubusercontent.com/599268/120327323-ecbe6000-c2e9-11eb-9f5c-530c011c7bb3.gif)

_Credit: @jbicker_

### Steps to reproduce

1. Open an issue in Gitpod
2. Make a commit
3. Click on "Push/Pull" in the status bar

⚠️ By default, the commit gets pushed to `origin`'s default branch.

### Expected behavior

Instead, the commit should be pushed to a new `origin` branch, with the same name as the local "issue" branch.

### Anything else?

Likely a regression from https://github.com/gitpod-io/gitpod/pull/4167 which added a remote tracking branch to local issue-context branches:

https://github.com/gitpod-io/gitpod/blob/52a79bc36e2deda3e9242344ae04a91f5b0b7514/components/content-service/pkg/initializer/git.go#L121-L125

Judging from the [git-checkout docs](https://git-scm.com/docs/git-checkout#Documentation/git-checkout.txt-emgitcheckoutem-b-Bltnewbranchgtltstartpointgt), it seems we could simply add `--no-track` to preserve the old semantics (i.e. no remote tracking branch for local issue-context branch).

**Comment by JanKoehnlein** [comment]
@jankeromnes can you fix that? This should likely be hotfix deployed. CC @csweichel
