### ISSUE TITLE
[Theia] Extensions error during installation.

### ISSUE THREAD

**Issue by AkemiShimizu** [gitpod-io/gitpod#4377]
### Bug description

Whenever i try to install any kind of extension from the sidebar, it does not work.

![image](https://user-images.githubusercontent.com/48862659/120490509-bdc2ef80-c3b8-11eb-84be-e8e190e424c9.png)

I've tried reopening the workspace, various times.

### Steps to reproduce

1. Open a workspace
2. Try to install material design icons (Example) or any other.
3. Error 

### Expected behavior

VSIX gets installed and I get the extension goodies.

### Example repository

Any repository

### Anything else?

Workspace ID: apricot-heron-gojdurpm

OS: ChromeOS
Chrome: Dev Branch
Adblock: Installed

**Comment by Carlos-Schrodinger** [comment]
Any backup here?

**Comment by akosyakov** [comment]
Please try VS Code instead. We are looking into issues with VS Code now and deprecating Theia this month: https://github.com/gitpod-io/gitpod/issues/4459

**Comment by Carlos-Schrodinger** [comment]
> Please try VS Code instead. We are looking into issues with VS Code now and deprecating Theia this month: #4459

Well that is funny because: #4391

No idea how this is happening, but im super bugged on gitpod, so none of the editors really work haha!

Personally will stop using gitpod at this rate and just get a workstation. 

No idea how many bugs are happening to me :/

**Comment by akosyakov** [comment]
@AkemiShimizu added your issue to look into this month.

**Comment by AkemiShimizu** [comment]
> @AkemiShimizu added your issue to look into this month.

Thanks a lot!

**Comment by akosyakov** [comment]
We are going to work on Theia fix. Please try VS Code and report if something does not work.
