### ISSUE TITLE
[dev] Go version mismatch with

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#4379]
### Bug description

Opening Gitpod in Gitpod leads to this go error:
```
compile: version "go1.16.2" does not match go tool version "go1.16.3"
```

(internal discussion: https://gitpod.slack.com/archives/C01KGM9AW4W/p1621325460010800 https://gitpod.slack.com/archives/C01KGM9AW4W/p1620645685047900?thread_ts=1620645366.046900&cid=C01KGM9AW4W)

### Steps to reproduce

Open Gitpod in Gitpod. In a new terminal run `leeway build component/gitpod-cli:app`

**Comment by JanKoehnlein** [comment]
Results of offline discussion with Chris: 
- Path settings are different in task terminals than in newly spawned ones. In task terminals this still works.
- We should not redefine / overwrite the Go installation we inherit from `gitpod/workspace-full` in our dev image

I am going to fix the latter.
