### ISSUE TITLE
[VSCode] IDE Languages disappeared.

### ISSUE THREAD

**Issue by Shigetorum635** [gitpod-io/gitpod#4391]
### Bug description

Whenever I set VSCode as my preferred IDE, the languages disappear and thus syntax highlighting etc...

- Languages support disappear and can't be fixed.

This bug causes the IDE to actually not detect any language, I tried checking the VSCode extensions, and it shows that all built-in extensions **are installed and running**, but when it comes to actual use it does not work.

Since language support is non-existent, the syntax highlighting is also none. As well as autocompletion or code usability.

It all shows as gray text (or default text). And when I try to manually change languages it only shows "Text, Bash" and other two, but not any language I actually need like **PHP** or **JavaScript**.

This is a big bug on my side, but I have not seen any complaints anywhere else. So it might be **my problem** rather than gitpod side.

Video
https://share.wildbook.me/ux2BMJlDSROnb94X.webm

PS: I have tried logging out and logging in, as well as clearing cache, and trying out other workspaces. Same issue.

### Steps to reproduce

1.Set IDE to VSCode
2.Open a workspace like Sakusen on gitpod.
2. Experience the lack of any kind of language

### Expected behavior

To add syntax highlighting and work as it is intended to.

### Example repository

Carlos-Schrodinger/Sakusen

(Current and the one empty within the video)

### Anything else?

VSCode worked correctly in the past, even though I had a few issues with autocompletion specially with JavaScript.

I hope this gets fixed soon as I have other issues open with Theia where the extensions dont get installed

Ext: #4377 

Check also my other issue regarding usernames:
Username: #4390 

Workspace ID: rose-python-lafo455y

**Comment by Carlos-Schrodinger** [comment]
![image](https://user-images.githubusercontent.com/48862659/120690475-8d0cb400-c4a5-11eb-9d1a-6cca5f5b1ffb.png)
![image](https://user-images.githubusercontent.com/48862659/120690530-9eee5700-c4a5-11eb-94f9-17a86e190358.png)

Also git control died on VSCode too.

**Comment by akosyakov** [comment]
Which browser do you use?

**Comment by Carlos-Schrodinger** [comment]
> Which browser do you use? Do you still experience it?

Hello, im using chrome stable release, and yes i do still experience this.

**Comment by Carlos-Schrodinger** [comment]
hello @akosyakov any news?

**Comment by Carlos-Schrodinger** [comment]
Some errors
![image](https://user-images.githubusercontent.com/48862659/121521623-95f50c80-c9f4-11eb-83c2-35cc144927c4.png)
![image](https://user-images.githubusercontent.com/48862659/121521657-9e4d4780-c9f4-11eb-9cc5-2581d0c06407.png)
Cors acting up?

**Comment by Carlos-Schrodinger** [comment]
[log.log](https://github.com/gitpod-io/gitpod/files/6631209/log.log)
HEre's the full log of my workspace

**Comment by akosyakov** [comment]
I think it is most likely caused by:
```
log.ts:284  INFO Error while initializing UI State
log.ts:296   ERR NoRef (UserDataSyncError) syncResource:unknown operationId:78037a21-4032-4de2-864c-a5d7673a4156: Server did not return the ref
    at UserDataSyncStoreClient.read (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:160886:23)
    at async https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:314165:38
    at async Promise.all (index 1)
    at async Object.settled (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:23133:28)
    at async UserDataInitializationService.initialize (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:314156:13)
    at async BrowserMain.initServices (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:399675:17)
    at async Promise.all (index 0)
    at async BrowserMain.open (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:399568:32)
log.ts:284  INFO Error while initializing Settings
log.ts:296   ERR NoRef (UserDataSyncError) syncResource:unknown operationId:a7998ed2-4e5e-4dbd-b5b1-e4f75bed8b23: Server did not return the ref
    at UserDataSyncStoreClient.read (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:160886:23)
    at async https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:314165:38
    at async Promise.all (index 0)
    at async Object.settled (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:23133:28)
    at async UserDataInitializationService.initialize (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:314156:13)
    at async BrowserMain.initServices (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:399675:17)
    at async Promise.all (index 0)
    at async BrowserMain.open (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:399568:32)
userDataSyncStoreService.ts:294 Uncaught (in promise) NoRef (UserDataSyncError) syncResource:unknown operationId:18c2c84c-3968-4d31-af43-5e895e115567: Server did not return the ref
    at UserDataSyncStoreClient.read (https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:160886:23)
    at async https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:314145:38
    at async https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:314118:58
    at async https://amethyst-woodpecker-lsv47oef.ws-eu09.gitpod.io/out/vs/workbench/workbench.web.api.js:417622:17
```

**Comment by Carlos-Schrodinger** [comment]
> Something wrond with user data sync for your user. You could try to check sync user data view and maybe reset them. Although it could be a follow up too, hm.

How do i check this? I'd like to get this as fixed as soon as possible.

**Comment by Carlos-Schrodinger** [comment]
@akosyakov I did some research and found out gitpod is not getting my token correctly!
![image](https://user-images.githubusercontent.com/48862659/121732627-c327e480-caf2-11eb-9940-7e00ab2934bc.png)

**Comment by Carlos-Schrodinger** [comment]
Alsot his when i try to force enable sync
![image](https://user-images.githubusercontent.com/48862659/121732832-fcf8eb00-caf2-11eb-98b4-ed31fbb4f2dc.png)

**Comment by akosyakov** [comment]
Maybe is it related to https://community.gitpod.io/t/incompatible-browser-extensions-for-gitpod/3888? Do you use any browser extensions?

**Comment by AkemiShimizu** [comment]
> Maybe is it related to https://community.gitpod.io/t/incompatible-browser-extensions-for-gitpod/3888? Do you use any browser extensions?
I do share adblock and some extensions, let me disable them and try.

**Comment by AkemiShimizu** [comment]
I have disabled adblocker, and some other extensions i dont use as well as the wappalyzer (technology viewer) to see what happens.

**Comment by AkemiShimizu** [comment]
WOAH it sure worked!
![image](https://user-images.githubusercontent.com/48862659/121869078-f55b6100-cd01-11eb-9b0f-70e2c0a185a9.png)

**Comment by AkemiShimizu** [comment]
You should add some kind of warning that extensions might break gitpod.

**Comment by AkemiShimizu** [comment]
thnaks for the advice @akosyakov

**Comment by akosyakov** [comment]
@AkemiShimizu Could you share the name of browser extension? I need to understand it is VS Code issue or in our integration.

**Comment by AkemiShimizu** [comment]
> @AkemiShimizu Could you share the name of browser extension? I need to understand it is VS Code issue or in our integration.

AdblockPlus and Dejavue are the main ones i disabled, but there may be more.

```
· Wappalyzer
· Nshell
· Tampermonkey
· UrCleaner
```

**Comment by wyndon** [comment]
Since @akosyakov asked about extensions :
> @AkemiShimizu Could you share the name of browser extension? I need to understand it is VS Code issue or in our integration.

I'll share my experience.

From my tests, the [`ClearURLS`](https://addons.mozilla.org/en-US/firefox/addon/clearurls/) addon seems to mess up pretty much everything :
- Plugins (syntax highlighting, Live Share, etc.)
- Icons (they just aren't there)
- Preview window (it just does nothing)

I guess the only *real* issue is **plugins**, since Live Share, icons, the preview window, etc. are all plugins in some way.

Here's a screenshot after loading the page, with the addon enabled, and the issues aforementioned.

![2021-07-30 02_15_55-](https://user-images.githubusercontent.com/72203260/127581231-20ae2137-b656-4488-8ad6-08c1a6202f42.png)

And here are the stats of the addon, note that these are **only** the stats from Gitpod, since I had reset the stats before.

![2021-07-30 02_16_29-](https://user-images.githubusercontent.com/72203260/127581394-2614352b-d5d2-42af-81c1-948914605bab.png)

Now if I enable the logs on the extension, I can see this (there are more, but the "Rule" part is the same for all) :

![2021-07-30 02_30_11-Log from ClearURLs — Mozilla Firefox](https://user-images.githubusercontent.com/72203260/127582095-4c03c7f8-b254-4f8f-bdaf-2a7a56818ee5.png)

I'm not sure if the "Rule" part is relevant, I get it on pretty much every request. That's the only logs I have.

**Comment by akosyakov** [comment]
Removing etag will affect your experience a lot, you will loose settings and IDE won't be cached.

**Comment by izzqz** [comment]
Now, the only way to fix this, is disabling ETag filtering completely In ClearURLs settings.

This issue is also described in the extension repo https://gitlab.com/KevinRoebert/ClearUrls/-/issues/977

**Comment by ghuntley** [comment]
Raised https://github.com/gitpod-io/website/pull/874/files to document ClearURLs breaks Gitpod at the moment. If there are additional browser extensions identified please raise a new issue for each one. 🧡
