### ISSUE TITLE
Unable to build the component typescript-grpc.

### ISSUE THREAD

**Issue by tedyage** [gitpod-io/gitpod#4393]
### Bug description

When using leeway build command to build the lib typescript-grpc, an error always occurs and block the build procedure.
The log of leeway build is below:
`
DEBU[0082] running                                       command="cp --parents package.json build.sh /home/tedyage/tenxcloud/projects/gitpod/yarn.lock tsconfig.json /tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c"
DEBU[0082] LEEWAY_YARN_MUTEX is not set, defaulting to "network" 
DEBU[0082] running                                       command="cp /home/tedyage/tenxcloud/projects/gitpod/yarn.lock ."
DEBU[0082] running                                       command="cp /home/tedyage/tenxcloud/projects/gitpod/components/supervisor-api/typescript-grpc/tsconfig.json ."
DEBU[0082] running                                       command="mkdir components-supervisor-api--proto"
DEBU[0082] running                                       command="tar xfz /tmp/cache/6ae8c168e8c4be3ac920bd6152835ecd31e0dc07.tar.gz -C components-supervisor-api--proto"
DEBU[0083] running                                       command="yarn install --mutex network --cache-folder /tmp/build/yarn-cache"
[components/supervisor-api/typescript-grpc:lib] yarn install v1.22.10
[components/supervisor-api/typescript-grpc:lib] [1/4] Resolving packages...
[components/supervisor-api/typescript-grpc:lib] [2/4] Fetching packages...
[components/supervisor-api/typescript-grpc:lib] [3/4] Linking dependencies...
[components/supervisor-api/typescript-grpc:lib] warning " > typescript-formatter@7.2.2" has unmet peer dependency "typescript@^2.1.6 || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >=3.0.0-dev".
[components/supervisor-api/typescript-grpc:lib] [4/4] Building fresh packages...
[components/supervisor-api/typescript-grpc:lib] error /tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/grpc-tools: Command failed.
[components/supervisor-api/typescript-grpc:lib] Exit code: 1
[components/supervisor-api/typescript-grpc:lib] Command: node-pre-gyp install
[components/supervisor-api/typescript-grpc:lib] Arguments: 
[components/supervisor-api/typescript-grpc:lib] Directory: /tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/grpc-tools
[components/supervisor-api/typescript-grpc:lib] Output:
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp info it worked if it ends with ok
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp info using node-pre-gyp@0.15.0
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp info using node@12.16.2 | linux | x64
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp WARN Using needle for node-pre-gyp https download 
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp info check checked for "/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/grpc-tools/bin/grpc_tools.node" (not found)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.9.1/linux-x64.tar.gz
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp http 200 https://node-precompiled-binaries.grpc.io/grpc-tools/v1.9.1/linux-x64.tar.gz
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! install error 
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack Error: There was a fatal problem while downloading/extracting the tarball
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at afterExtract (/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/node-pre-gyp/lib/install.js:100:33)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at Unpack.afterTarball (/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/node-pre-gyp/lib/install.js:176:9)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at Unpack.emit (events.js:310:20)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at Unpack.[maybeClose] (/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/tar/lib/unpack.js:171:12)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at Unpack.opt.ondone (/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/tar/lib/unpack.js:89:23)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at Unpack.emit (events.js:310:20)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at Unpack.[emit] (/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/tar/lib/parse.js:235:12)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at Unpack.[maybeEnd] (/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/tar/lib/parse.js:351:17)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at Unpack.[consumeChunk] (/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/tar/lib/parse.js:359:21)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! stack     at Unpack.write (/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/tar/lib/parse.js:315:25)
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! command "/usr/local/bin/node" "/tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! cwd /tmp/build/components-supervisor-api-typescript-grpc--lib.7d464a8081d27f349c10d918ccb3b9844ea4ce5c/node_modules/grpc-tools
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! node -v v12.16.2
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! node-pre-gyp -v v0.15.0
[components/supervisor-api/typescript-grpc:lib] node-pre-gyp ERR! not ok 
[components/supervisor-api/typescript-grpc:lib] There was a fatal problem while downloading/extracting the tarball
[components/supervisor-api/typescript-grpc:lib] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[components/supervisor-api/typescript-grpc:lib] Process stalled
[components/supervisor-api/typescript-grpc:lib] Active handles:
[components/supervisor-api/typescript-grpc:lib]   - Socket
[components/supervisor-api/typescript-grpc:lib]   - Socket
[components/supervisor-api/typescript-grpc:lib]   - Socket
[components/supervisor-api/typescript-grpc:lib]   - Socket
[components/supervisor-api/typescript-grpc:lib]   - ChildProcess
[components/supervisor-api/typescript-grpc:lib] package build failed
[components/supervisor-api/typescript-grpc:lib] Reason: exit status 1
build failed
Reason: build failed
FATA[0159] build failed
` 

### Steps to reproduce

1. Open this project.
2. Run this command on the project root directory. `export LEEWAY_WORKSPACE_ROOT=$PWD`.
3. Run the build command,  `leeway build components/supervisor-api/typescript-grpc:lib -v`.
4. Wait for the components/supervisor-api:proto building complete and building this component, and then the problem shows up.

### Expected behavior

Successfully build the lib components/supervisor-api/typescript-grpc

### Anything else?

os version: ubuntu 18.04.2 LTS (Bionic Beaver)
node version: v12.16.2
gitpod version: self-hosted 0.6.0
yarn version: 1.22.10

**Comment by JanKoehnlein** [comment]
What is the `leeway version` in your workspace image?

**Comment by tedyage** [comment]
@JanKoehnlein , the leeway version is 0.2.0-fe5c3b2

**Comment by tedyage** [comment]
Hi, @JanKoehnlein , I found out something different that blocks the building from succeeding.
If I set the environment variables "http_proxy" and "https_proxy" before executing the building command, then the building will fail, but if I unset those variables, the building will be successful.

**Comment by JanKoehnlein** [comment]
No idea. Why have you set these env vars in the first place?

**Comment by ghuntley** [comment]
Howdy @tedyage can you please try v0.10.0 and open a new issue if required. See https://www.gitpod.io/docs/self-hosted/latest/installation for instructions.
