### ISSUE TITLE
improve message "Port 'xxxx' of workspace is not exposed"

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#44]
Currently, the message is:

> Sorry, that should not have happened!
> Port '34449' of workspace is not exposed. Please, update your '.gitpod' config file.

For authenticated users, we could have a button here to expose the port.
A pointer to the "Ports" View and the documentation would be helpful, too.

**Comment by AlexTugarev** [comment]
Just asking, how do you get there? ;-)

**Comment by 32leaves** [comment]
He probably exposed the port, but the service listening on it does not serve HTTP. The proxy then redirects to the sorry page.

**Comment by AlexTugarev** [comment]
Ah! Thanks @32leaves.

**Comment by meysholdt** [comment]
reproducible with https://gitpod.io/#https://github.com/apgsga-it/piper

For that project I get the "expose port" message. No init scripts were executed and I didn't launch any servers. 

After exposing the port and opening it externally, I get the "port not exposed" error message.

I suspect: 
- a language server opened a port
- as @32leaves suggested, it doesn't serve HTTP
