### ISSUE TITLE
Align the "New Workspace" examples with the Quickstarts

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#4413]
The list of available Quickstart guides is available at: https://www.gitpod.io/docs/quickstart

**Comment by JohannesLandgraf** [comment]
Should we rename examples to templates? The repositories @svenefftinge built are more templates less examples

**Comment by gtsiolis** [comment]
In case we're still interested in this, adding search could be also helpful given the list of the examples. See https://github.com/gitpod-io/gitpod/issues/5309 and https://github.com/gitpod-io/gitpod/issues/5309#issuecomment-908272776.

**Comment by svenefftinge** [comment]
I think this was done already
