### ISSUE TITLE
“GitHub Actions” extension can not authenticate

### ISSUE THREAD

**Issue by janpio** [gitpod-io/gitpod#4418]
### Bug description

Trying to use the Github Actions extension in Gitpod: Open VSX Registry

After installation, a new authentication thing is added:
![image](https://user-images.githubusercontent.com/183673/121088569-3aedca80-c7e6-11eb-9e12-baddfda2c037.png)

On clicking that I unfortunately get an error message:
![image](https://user-images.githubusercontent.com/183673/121088577-3f19e800-c7e6-11eb-848a-6c458e32fec2.png)

But access control at https://gitpod.io/integrations shows that I already have that:
![image](https://user-images.githubusercontent.com/183673/121088619-4e993100-c7e6-11eb-868e-64f9c2ffda1e.png)
![image](https://user-images.githubusercontent.com/183673/121088629-51942180-c7e6-11eb-9eac-2b3d403775a9.png)

What am I missing here?

### Steps to reproduce

Install extension, observe failure.

### Anything else?

Previously reported at https://community.gitpod.io/t/github-actions-extension-can-not-authenticate/3828

**Comment by akosyakov** [comment]
@janpio It looks like a bug in the extenison, there is no scope `workflow**s**`, but only `workflow`: https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes

**Comment by akosyakov** [comment]
opened a PR in the upstream: https://github.com/cschleiden/vscode-github-actions/pull/98

**Comment by janpio** [comment]
Oh, good catch! I thought that was just an error message thing.

**Comment by akosyakov** [comment]
A new version of the extension was published to Open VSX. Please try again and reopen if it did not help.

**Comment by janpio** [comment]
Yep, seems to be working now 👍
