### ISSUE TITLE
"Workspace prebuild is starting..." but nothing happens

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#442]
**Describe the bug**

When trying to open my repository in Gitpod, I see this "Workspace prebuild is starting ..." screen, but nothing seems to be happening even if I wait a long time:

<img width="680" alt="Screenshot 2019-04-06 at 17 08 03" src="https://user-images.githubusercontent.com/599268/55671467-9469b000-5890-11e9-905b-d61af36b31e5.png">

**To Reproduce**

1. Try to open https://gitpod.io/#https://github.com/jankeromnes/dev.to
2. See above pictured screen
3. Nothing happens (until you click on `Skip prebuild`)

**Expected behavior**

The prebuild should start and do things (or at least it shouldn't block me).

**Comment by nico-abram** [comment]
I am also experiencing this on https://gitpod.io/#github.com/nico-abram/rusty-boy-advance

**Comment by jankeromnes** [comment]
So, the bad news is that this is still happening sometimes (more frequently for some repositories than others).

The good news is that we believe we've found the root cause, and the fix will be deployed soon. 🎉

**Comment by geropl** [comment]
Deployed a few days ago.

**Comment by joshleblanc** [comment]
I'm still running into this. https://gitpod.io/#https://github.com/joshleblanc/secret-santa/tree/master
