### ISSUE TITLE
Is it possible to run QEMU on GitPod for some tests?

### ISSUE THREAD

**Issue by AyaanZaveri** [gitpod-io/gitpod#4431]
### Bug description

Everytime I've tried to run QEMU it always said: 
`qemu-system-x86_64: command not found`

### Steps to reproduce

I've tried `sudo apt-get install qemu-system qemu-utils python3 python3-pip` but it didn't work!
Is it possible?

**Comment by geropl** [comment]
Yes! @fntlnz recently showed an awesome demo! (ping :wink: )

**Comment by corneliusludmann** [comment]
You could have a look here: https://github.com/fntlnz/gitpod-k3s

**Comment by corneliusludmann** [comment]
I don't have an exhaustive answer for you, but maybe this will help you:

https://github.com/gitpod-io/workspace-images/tree/master/full-vnc

This is our workspace image that has VNC configured. There you can open VNC in your browser tab. What you need now is the connection to qemu somehow.
