### ISSUE TITLE
gitpod.yml command not running

### ISSUE THREAD

**Issue by FeixuRuins** [gitpod-io/gitpod#4435]
### Bug description

I'm trying to make Gitpod install Elixir when my workspace starts, like so:
```yml
tasks:
  - command: chmod +x gitpod-init.sh; ./gitpod-init.sh
```
gitpod-init.sh:
```sh
wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb
sudo dpkg -i erlang-solutions_2.0_all.deb
rm erlang-solutions_2.0_all.deb
sudo apt update
DEBIAN_FRONTEND=noninteractive sudo apt install -y esl-erlang
sudo apt install -y elixir
```
However, Elixir is not being installed.

### Steps to reproduce

^^ above

### Expected behavior

It should install Elixir and its counterparts.

### Example repository

https://github.com/FeixuRuins/websocket-test/

**Comment by corneliusludmann** [comment]
Hi @FeixuRuins,

When I open your repo in Gitpod, your script executes and waits for user input (choose keyboard layout). You can prevent this by setting the environment variable `DEBIAN_FRONTEND=noninteractive`.

Does this help?

_By the way: You probably ask these kinds of questions in our community forum: https://community.gitpod.io/_

**Comment by FeixuRuins** [comment]
> Hi @FeixuRuins,
> 
> When I open your repo in Gitpod, your script executes and waits for user input (choose keyboard layout). You can prevent this by setting the environment variable `DEBIAN_FRONTEND=noninteractive`.
> 
> Does this help?
> 
> _By the way: You probably ask these kinds of questions in our community forum: https://community.gitpod.io/_

Thank you! Unfortunately, that does not work either. Even something simple like `sudo apt install -y elixir` does nothing.

**Comment by corneliusludmann** [comment]
Hm … When I open https://gitpod.io/#https://github.com/FeixuRuins/websocket-test/ I get the following:

https://user-images.githubusercontent.com/24960040/121371645-fd03ba00-c93d-11eb-9ee9-9e90af82342c.mp4

Do you get something different? Do you expect something else?

Do you use VSCode or Theia? → See https://gitpod.io/preferences

**Comment by FeixuRuins** [comment]
Odd... Nothing happens when I open my workspace. I have to run the script manually (and it doesn't ask for keyboard configuration.)
I'm using VSCode.

**Comment by FeixuRuins** [comment]
@corneliusludmann Actually, could the keyboard thing be Gitpod's fault? I don't see why else it doesn't ask when it's run manually but it asks when Gitpod runs it

**Comment by FeixuRuins** [comment]
https://github.com/gitpod-io/gitpod/issues/4472
