### ISSUE TITLE
Java LS Hangs

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#444]
The java LS seem to get stuck from time to time.
When that happens content assist hangs in 'Loading...' state.

Reloading the browser helps.

Experienced for instance with https://github.com/apache/maven-shade-plugin

**Comment by mkarg** [comment]
@svenefftinge Thanks for your kind help. Your service is awesome! :+1:

**Comment by clicman** [comment]
Thanks for an attention. I’m an original reporter from Twitter:)

**Comment by AlexTugarev** [comment]
Thanks @clicman and @mkarg! The fix will be deployed with the next release.
