### ISSUE TITLE
noise in workspace full terminals

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4445]
### Bug description

<img width="1475" alt="Screenshot 2021-06-09 at 10 35 31" src="https://user-images.githubusercontent.com/3082655/121299192-784d7780-c90e-11eb-966e-796ed498eed4.png">

### Steps to reproduce

see above

**Comment by jankeromnes** [comment]
Looks like this was a Dazzle cache problem. A fix was merged and is currently being deployed to Docker Hub:
- E.T.A ~30min for a fixed `gitpod/workspace-full`
- ... a bit later for other downstream images
