### ISSUE TITLE
[Ruby] rails binary doesn't survive workspace restarts

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#445]
When I stop and restart a workspace for the rails app (https://gitpod.io/#https://github.com/gitpod-io/rails_sample_app)
The `rails` executable is not found. Seems to be an issue with the PATH variable.

**Comment by svenefftinge** [comment]
I have disabled prebuilds on the repo for now.

**Comment by AlexTugarev** [comment]
Hm. I cannot reproduce the issue.

```sh
gitpod /workspace/rails_sample_app $ which rails
/workspace/.rvm/bin/rails
```
and `rails server` is up and running after restarting the workspace.

**Comment by AlexTugarev** [comment]
given this config
```
tasks:
  - init: >
      bundle install --without production &&
      rails db:migrate
    command: >
      rails server
```

a restarted workspace is quickly up and running rails as expected.
