### ISSUE TITLE
[theia] Add a deprecation warning

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4459]
We are deprecating the use of Theia and plan to remove support for it in August. Users need to get notified about this change so they are not surprised and have a chance to react/adopt.

We should add a deprecation message in the settings and inform users when they start a workspace with the Theia setting.
I think we should use the loading screen for that, so if a user has Theia setting enabled, show below a deprecation message with the info that Theia support is discontinued in August 2021, as well as a link to the settings.

### Proposal

Some points for clarification:
1. We can reuse the same _What's new_ modal we added a couple of months ago, see https://github.com/gitpod-io/gitpod/issues/3297 and https://github.com/gitpod-io/gitpod/pull/3618.
2. The modal would hold back workspace start until the user selects an action, so that we know if we need Theia or VS Code for the workspace.
3. Add a new label component to highlight this is a deprecation warning.
4. The primary action here can be to switch the IDE and continue openning the workspace with VS Code.
5. Secondary action can be to dismiss this mesage continue with the old editor (Theia).
6. Provider a help link to contact us in case somone has any questions that links to https://www.gitpod.io/contact/.
7. Before merging make sure if the deprecation will happen in the next monthly milestone as described in the message. Otherwise, updating the message should suffice.

### Next steps

The next step after removing the old editor is to also remove the preference settings in [`/preferences`](https://gitpod.io/preferences). See https://github.com/gitpod-io/gitpod/issues/4486.

### Designs

| Warning Modal |
|-|
| <img width="1440" alt="Warning" src="https://user-images.githubusercontent.com/120486/121681591-b0e28200-cac3-11eb-9b50-56ec953d7f9b.png"> |

See also [design specs](https://www.figma.com/file/vCcSUpofQRdO3Puq4IYDpb/Add-a-deprecation-warning-4459?node-id=1005%3A121).

**Comment by ghuntley** [comment]
🎗 don't forget about https://gitpod.io/schemas/gitpod-schema.json 🥰

<img width="1124" alt="2021-06-18_13-47-04" src="https://user-images.githubusercontent.com/127353/122503378-abdd7f80-d03b-11eb-8272-dfc3d8267743.png">

**Comment by akosyakov** [comment]
> 🎗 don't forget about https://gitpod.io/schemas/gitpod-schema.json 🥰

that's actually not used and can be removed right now

**Comment by corneliusludmann** [comment]
@gtsiolis: I would also like to see a hint in the “What's new” dialog that ports are private by default and need to be set public explicitly (see #4159). How would that fit into the dialog?

**Comment by gtsiolis** [comment]
Hey @corneliusludmann! Adding below some specs for including the change about port exposure.

Things to consider:
1. We need to conditionally show the New Editor entry for users who are still using Theia.
2. Exposing Ports entry should probably be shown tro all users.

You can find more detailed specs in the same Figma file linked from the issue description. Feedback is always welcome!

| New Editor | Exposing Ports | Exposing Ports + New Editor |
|-|-|-|
| <img width="1440" alt="New Editor" src="https://user-images.githubusercontent.com/120486/122897626-d76dac00-d352-11eb-98b7-fd2a272c62bc.png"> | <img width="1440" alt="Exposing Ports" src="https://user-images.githubusercontent.com/120486/122897630-d8064280-d352-11eb-8602-eabc8b31e0d4.png"> | <img width="1440" alt="Exposing Ports + New Editor" src="https://user-images.githubusercontent.com/120486/122897637-d9376f80-d352-11eb-8719-e3136a589e0b.png"> |
