### ISSUE TITLE
[code] .gitpod.yml extensions not being installed in VS Code

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4460]
### Bug description

Originally reported [here](https://community.gitpod.io/t/extensions-not-being-activated/3783) last week:

> I am using [this](https://github.com/KushagraSinha2002/Resourceium/) repository in Gitpod but for some reason, the extensions are not activated at all. Neither are some of the left sidebar features (like the port explorer)
> 
> The extensions tab is completely empty too:
> 
> ![b830a5d573ca912fc2bbcb33bb9d001aff4ae15e](https://user-images.githubusercontent.com/599268/121493049-b8c4f800-c9d7-11eb-8710-06ca9f849b90.png)
> 
> This worked fine until a couple of weeks ago, but then I put the project on hold and when I came back, I started encountering this problem. I don’t am not really sure what has actually caused this issue.

### Steps to reproduce

1. Set VS Code as default IDE in https://gitpod.io/preferences
2. Open https://gitpod.io/#https://github.com/KushagraSinha2002/Resourceium/
3. Check Extensions panel

### Expected behavior

Extensions should be installed.

### Example repository

https://github.com/KushagraSinha2002/Resourceium/

### Anything else?

While investigating, we noticed a bunch of errors in the browser console, but they're likely unrelated (some known OpenVSX CORS errors, and some local app connection errors).

However, suspecting something might be wrong with the config, I tried to fork the repository. When I opened my **identical** fork in Gitpod, I suddenly had all extensions installed, but none of the tasks ran, which was super confusing.

**Comment by lechien73** [comment]
Further to this, I've noticed that startup commands in .gitpod.yml are no longer being run after the switch to VS Code.

Because the user directory isn't saved between workspace restarts, we run a command on startup to add run aliases to ~/.bashrc

This startup command is no longer being run.

Extract from .gitpod.yml:

```
tasks:
  - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: . ${GITPOD_REPO_ROOT}/.vscode/update_bashrc.sh
```

**Comment by Carlos-Schrodinger** [comment]
Maybe related to #4391

**Comment by akosyakov** [comment]
It is somehow related to Node.js. I was able to create a minimal script which produces it: https://github.com/nodejs/node/issues/39072

I don't know how to properly fix it, but we can try to ignore stderr particuarly for this case, since we collect it only for tracing.
