### ISSUE TITLE
[Teams] Disallow team names that are also user names or that conflict with dashboard URLs

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4469]
When creating a new Team, one should **not** be able to give it a name such that:

- [ ] It's called the same as / looks like a user
- [ ] Its `gitpod.io/:slug` URL conflicts with an existing dashboard URL (e.g. "Workspaces" should be forbidden)

As specified in https://github.com/gitpod-io/gitpod/issues/4355

Follow-up to https://github.com/gitpod-io/gitpod/pull/4401

**Comment by corneliusludmann** [comment]
Is it planned to use a blocklist as well to prevent team names like `admin`, `support` etc? There are a lot of lists out there, e.g. https://github.com/marteinn/The-Big-Username-Blocklist.

**Comment by gtsiolis** [comment]
Cross-posting a comment from a [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1625064176314500?thread_ts=1625063886.313200&cid=C021Q4BL8E8) (internal):

> **question**: Would it be worth it to reconsider generating team and project URLs with a random hash suffix or prefix attached?
> Like:
> > gitpod.io/team-o9yti4go/project-1bik3oxv/

> or

> > gitpod.io/team/o9yti4go/team-name/ +
> > gitpod.io/project/1bik3oxv/project-name/

**Comment by jankeromnes** [comment]
I personally think this looks much less nice. I'm quite happy to have https://github.com/jankeromnes, and would find GitHub much less nice if I had to use https://github.com/jankeromnes-o9yti4go instead

**Comment by gtsiolis** [comment]
@jankeromnes your call! Posted the comment in https://github.com/gitpod-io/gitpod/issues/4469#issuecomment-893859148 in case it could make this issue obsolete or redundant. In terms of UX or Product both options could suffice. Looking forward to see how this implementation will work in action. 👀
