### ISSUE TITLE
[server] Optimize query behind `getTeamMembers`

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4470]
`getTeamMembers(teamId)` should not get all Users one by one when building the `TeamMemberInfo[]` array. Instead, it should get them all in a single query.

As requested in https://github.com/gitpod-io/gitpod/pull/4401/files#r648201200

Follow-up to https://github.com/gitpod-io/gitpod/pull/4401

**Comment by svenefftinge** [comment]
fixed as part of https://github.com/gitpod-io/gitpod/pull/4490
