### ISSUE TITLE
terminal fonts appear blurry in firefox

### ISSUE THREAD

**Issue by opensas** [gitpod-io/gitpod#4475]
### Bug description

terminal fonts appears blurry in firefox

See screenshot attached:

![image](https://user-images.githubusercontent.com/481687/121558074-b53b6c00-c9eb-11eb-99f2-c35ec93147a3.png)

In chromium in displays ok:

![image](https://user-images.githubusercontent.com/481687/121558145-c5ebe200-c9eb-11eb-9639-0b7cb5c142e3.png)

## context info:

$ uname -a
Linux xps 5.4.0-75-generic #84~18.04.1-Ubuntu SMP Fri Jun 4 01:43:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
OS: Ubuntu 18.04.5 LTS x86_64 
Kernel: 5.4.0-75-generic 

### Steps to reproduce

Open any github repo with gidpod.io/#/<github repo> using a firefox explorer

### Expected behavior

The terminal fonts should display ok

### Anything else?

Not sure if this is the place to submit these kind of issues

**Comment by aledbf** [comment]
Closing. Duplicate https://github.com/gitpod-io/gitpod/issues/4130

@opensas please check the linked issue.
