### ISSUE TITLE
[ui] eBPF terminal should not show up in Gitpod IDE

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#4477]
### Bug description

When I open a Gitpod workspace, I get another terminal `Prepare Agent Smith BPF dev environment: leeway`
This appears useless to common users and should not show up. 

### Steps to reproduce

Open a new Gitpod workspace

**Comment by jankeromnes** [comment]
Side note: A minimal "fix" could also be to just place the eBPF Terminal as the very first task in `.gitpod.yml` (that way it'll be "hidden" behind the two other Terminals that most users want to see).

**Comment by akosyakov** [comment]
> Side note: A minimal "fix" could also be to just place the eBPF Terminal as the very first task in .gitpod.yml (that way it'll be "hidden" behind the two other Terminals that most users want to see).

I want to change it while upgrading VS Code and focus first terminal by default.
