### ISSUE TITLE
[git] false negatives when validating token scopes

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#4478]
### Bug description

Sometimes on git operations a dialog pops up claiming 
> The remote repository “…” is not accessible with the current token. Please grant the necessary permissions 
even though the user is correctly authenticated and the operation succeeds.

See https://community.gitpod.io/t/the-remote-repository-is-not-accessible-with-the-current-token-please-grant-the-necessary-permissions/3829

### Steps to reproduce

Happens sporadically

**Comment by JanKoehnlein** [comment]
We should improve logging around this topic

**Comment by janpio** [comment]
When trying to push to a origin that I added to get around that (perceived) problem, I also sometimes get this error message without actually naming the repository in the error message.

**Comment by JanKoehnlein** [comment]
See also https://github.com/gitpod-io/gitpod/pull/4503
