### ISSUE TITLE
[github] Gitpod hits rate limit

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#4480]
### Bug description

I've experienced that myself about a month ago, but now users are reporting this too. Gitpod seems to hit rate limits calling GitHub APIs. See https://community.gitpod.io/t/github-api-error-status-403/3866

We should find out why and take countermeasures

### Steps to reproduce

Happens sporadically, no reliable reproduction

**Comment by akosyakov** [comment]
It is caused by https://github.com/microsoft/vscode-pull-request-github/issues/2741#issuecomment-848546250

**Comment by JanKoehnlein** [comment]
Downgrading to 0.25.1 does the job: 
1) Wait until you can connect again (took a few minutes for me)
2) In Gitpod, got to extensions, locate the GitHub Pull Requests Extension and click on the gear icon. 
3) Select _Install Another Version_, chose _0.25.1_ and then click on _Reload Required_
