### ISSUE TITLE
[code] terminal resize errors are back

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#4483]
### Bug description

On production, I get this again

<img width="711" alt="Screen Shot 2021-06-11 at 08 56 21" src="https://user-images.githubusercontent.com/377752/121678608-a9b57700-cab7-11eb-9bc4-923a67bd4369.png">

### Steps to reproduce

E.g. open gitpod-io/gitpod in Gitpod

**Comment by akosyakov** [comment]
Unfortunately I cannot reproduce it on staging. If someone knows how please share.

**Comment by akosyakov** [comment]
I cannot reproduce it wth new VS Code, please reopen if you can.
