### ISSUE TITLE
Remove theia option in settings

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4486]
### Problem to solve

Now that we're deprecating the old editor (Theia) (see https://github.com/gitpod-io/gitpod/issues/4459), we can safely remove the editor (Default IDE) preference in settings once the deprecation has been made.

⚠️ **Warning**: This is currently blocked until the deprecation is complete and will most probably be ready-for-development in the next milestone. /cc @akosyakov

**Comment by gtsiolis** [comment]
Since today (Sep 1), the message we have in _Preferences_ (`/preferences`) for deprecating Theia is running a bit late. 😅 

<img width="584" alt="Screenshot 2021-09-01 at 3 16 30 PM" src="https://user-images.githubusercontent.com/120486/131669676-969e3d11-af4a-449a-9158-014a19dbd144.png">

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4486#issuecomment-911354700):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
To clarify, this ticket only comprises removing the option in the Dashboard settings? Removing references and functionality in the codebase is not part of the scope?

**Comment by akosyakov** [comment]
Correct, we will fist remove UI and wait some time to see that everybody completely switched to VS Code, after that we will remove underlying functionality.

**Comment by akosyakov** [comment]
Of course, users with Theia selected now should also get Code, i.e. theia alias should point to the same image as code alias.

**Comment by JanKoehnlein** [comment]
@akosyakov to clarify: Users with Theia will still get Theia, there just shouldn't be an option to switch to Theia anymore, right?

**Comment by akosyakov** [comment]
> Users with Theia will still get Theia

I think they should get stable VS Code, we don't have Theia anymore.

**Comment by gtsiolis** [comment]
> I think they should get stable VS Code, we don't have Theia anymore.

Agree. 💯
