### ISSUE TITLE
Error: Couldn't parse context '%E2%80%9D'.

### ISSUE THREAD

**Issue by jayeshd7** [gitpod-io/gitpod#449]
**Describe the bug**
When i create a free account on gitpod via github .

**To Reproduce**
Take any Github account and try to create account on gitpod.

**Expected behavior**

**Comment by Armankhan4499** [comment]
Take any Github account and try to create account on gitpod.

**Comment by jankeromnes** [comment]
Oh, did you by any chance click on a link from our [launch blog post](https://www.gitpod.io/blog/gitpod-launch/)? These characters translate to an oblique quote `”`:

```js
decodeURIComponent('%E2%80%9D')
```

Just like if you clicked on a link like https://gitpod.io/#” -- I think there is a markdown error in our parser that causes links to include such quotes. I'll take a look.

**Comment by jankeromnes** [comment]
Here is probably the faulty link:

<img width="749" alt="Screenshot 2019-04-08 at 08 21 52" src="https://user-images.githubusercontent.com/599268/55702605-66db4e80-59d7-11e9-92d4-77d6bf2cc570.png">

**Comment by jankeromnes** [comment]
The link is also broken in GitHub's markdown viewer:

<img width="680" alt="Screenshot 2019-04-08 at 08 23 39" src="https://user-images.githubusercontent.com/599268/55702715-b588e880-59d7-11e9-81d5-f893d69f1256.png">


See https://github.com/gitpod-io/website/blob/master/src/blog/gitpod-launch.md#one-click-dev-environments-for-github

**Comment by jankeromnes** [comment]
Fixed the broken link like so:

```diff
- “https://gitpod.io/#”
+ “[gitpod.io/#](https://gitpod.io/#)”
```

And the fix is now [live](https://www.gitpod.io/blog/gitpod-launch/). Thanks again!

**Comment by jayeshd7** [comment]
Fixed and Working now.
Thanks.
