### ISSUE TITLE
gp env - failed to fetch env vars from server

### ISSUE THREAD

**Issue by liorsbg** [gitpod-io/gitpod#4495]
### Bug description

On any workspace in my account, running `gp env -e` will fail with the following message:

`failed to fetch env vars from server: json: cannot unmarshal array into Go struct field UserEnvVarValue.value of type string`

### Steps to reproduce

`gp env -e`

### Expected behavior

ENV_VAR_1=value1
ENV_VAR_2=value2

**Comment by JanKoehnlein** [comment]
Do your ENV vars have special characters (quotes or =) in their values? 
https://github.com/gitpod-io/gitpod/pull/4494 might fix it.

**Comment by corneliusludmann** [comment]
Hi @liorsbg!

Thanks for reporting. I'm not able to reproduce this bug. Is it reproducible for you? Could you share more information, e.g. the workspace ID of the workspace where this happens? Steps to reproduce?
