### ISSUE TITLE
[Java] No content assist in vavr

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#45]
Just tried:

https://gitpod.io#https://github.com/vavr-io/vavr

The Java LS seems to have trouble with it.

**Comment by svenefftinge** [comment]
They need an older maven version. So the build is failing.

**Comment by AlexTugarev** [comment]
> [WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
> Maven 2.1.0 and 2.2.0 produce incorrect GPG signatures and checksums respectively.

**Comment by AlexTugarev** [comment]
no, wait:

```
                                <requireMavenVersion>
                                    <version>3.5.3</version>
                                </requireMavenVersion>
```

**Comment by AlexTugarev** [comment]
and we have:

```
gitpod /workspace/vavr $ mvn --version
Picked up JAVA_TOOL_OPTIONS: -Xmx3189m
Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-1015-gcp", arch: "amd64", family: "unix"
```

**Comment by svenefftinge** [comment]
Let's update in workspace-full.

**Comment by svenefftinge** [comment]
With the updated maven, the build runs a bit longer and the LS initializes.
But the workspace has 5000+ errors and the LS gets very slow. So not really much better for now.

**Comment by meysholdt** [comment]
If we really need to be that bleeding-edge, we can consider go upgrade from ubuntu-bionic to ubuntu-cosmic. There we have maven in version 3.5.3-1: https://packages.ubuntu.com/cosmic/maven

**Comment by AlexTugarev** [comment]
![Screen Shot 2019-09-09 at 16 23 20](https://user-images.githubusercontent.com/914497/64539125-30a35180-d31e-11e9-9a1d-0e928b40d457.png)

works fine now!
