### ISSUE TITLE
Show logs for docker container creation

### ISSUE THREAD

**Issue by madoar** [gitpod-io/gitpod#450]
During the docker container creation some errors occurred when I wanted to install Chrome inside my `Dockerfile`. After the build phase finished and the container started it seems to be impossible to view the logs for the docker container creation. It would be useful to view them again at a later time, especially when errors occur.

**Comment by Armankhan4499** [comment]
Thanks

**Comment by jankeromnes** [comment]
Thanks for reporting this annoying problem! I think the bug you're seeing is https://github.com/gitpod-io/gitpod/issues/423.

We should fix that.

**Comment by madoar** [comment]
I'm not sure whether I'm having the same issue as described in #423. In my case the docker container/image was "successfully" built, just without Chrome, because of missing dependencies.

If I remember correctly the issue occurred to me with https://github.com/madoar/angular-archwizard/pull/204/commits/08977a039af88c736f774c977336020053902f6f

**Comment by meysholdt** [comment]
I'd like the idea if we could store the log in an additional file in the container, e.g. under `/.gitpod.docker-build.log`. This would allow any workspace user to look at it at any time and we don't need to build additional UI for it. I remember talking about this with @32leaves.

**Comment by madoar** [comment]
I also like the idea to store the build log of the docker image inside the container, but I'm not sure if this is enough. The issue with storing the log **only** inside the container is that the users:
- need to start the container to access it
- need to have knowledge about the specific location of the file.

I think it is better to additionally provide an UI on the dashboard to access the log file(s)

**Comment by svenefftinge** [comment]
The initial request to keep the erroneous logs is now deployed.
