### ISSUE TITLE
Terminal Window Typing Out of Order

### ISSUE THREAD

**Issue by sterno** [gitpod-io/gitpod#4504]
### Bug description

This occurred when I was on a cell network.  The network appeared to have a reasonable amount of bandwidth and ping time (>10MBps and ping of around 50).  

When I would use the terminal window, my typing was lagging, but worse, it was picking up the keys in the wrong order.  So if I typed "bundle install" what I would get is something more like "bnudel intsall".  Like if it was just laggy and slow that wouldn't be so bad, but it's totally unsuable if it's corrupting the order.

This was on an ipad pro running Safari.  

### Steps to reproduce

See above.

**Comment by csweichel** [comment]
I believe I've seen this too but so far have attributed this to my bad typing.

**Comment by akosyakov** [comment]
Does anyone know how to reliable to reproduce it? I tried on emulated slow connection with trying 1234567890 multiple times and it never give me wrong order.

**Comment by akosyakov** [comment]
Although from code it probably can happen in supervisor: https://github.com/gitpod-io/gitpod/blob/fc8edff8aaefdf9f6be8ecf3dfcd1a9261994d2a/components/supervisor/pkg/terminal/service.go#L291-L305

@csweichel Writing to PTY is not in the critical section and 2 writes can race correct?

**Comment by csweichel** [comment]
> Writing to PTY is not in the critical section and 2 writes can race correct?

Indeed they can. We'd need to ensure that the `Write` calls are processed in order.

**Comment by akosyakov** [comment]
> Indeed they can. We'd need to ensure that the Write calls are processed in order.

There is no way actually. There is no guarantee that RPC calls are processed in order, each executed in own go routine: https://github.com/grpc/grpc-go/blob/master/Documentation/concurrency.md#servers Only a client (Gitpod Code Server) can ensure the order.

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/4560#issuecomment-866466906
