### ISSUE TITLE
New here how to use this app

### ISSUE THREAD

**Issue by Armankhan4499** [gitpod-io/gitpod#451]
Tell me

**Comment by jankeromnes** [comment]
Hi @Armankhan4499, welcome to Gitpod!

Here is how you can use the app:

1. Go to any project on GitHub, for example https://github.com/gitpod-io/website/
2. To open the project in Gitpod's online IDE, just add `https://gitpod.io/#` in front of the GitHub URL, for example https://gitpod.io/#https://github.com/gitpod-io/website/
3. This will open the project in an online IDE, where you can edit the code, run the app to test it, send pull requests, etc.

Hope this helps! 👍
