### ISSUE TITLE
"This content is blocked" in LaTeX workshop pdf viewer

### ISSUE THREAD

**Issue by jemand771** [gitpod-io/gitpod#4513]
### Bug description

When trying to preview a PDF file inside of a vscode tab using the [LaTeX workshop](https://open-vsx.org/extension/James-Yu/latex-workshop) extension, an error message appears in place of the pdf contents:
![image](https://user-images.githubusercontent.com/19669567/122052158-ac7cd880-cde5-11eb-9e28-db5fe1ea59e4.png)
The browser's console is also full of messages like
```
no handler for  MessageEvent
```
with lots of info about the `MessageEvent` - I can post that in a comment if you need it.

What i think might be related to the issue is the following message (again, in the browser's js console):
```
Refused to frame 'https://45369-beige-mongoose-s08nrrsf.ws-eu09.gitpod.io/' because it violates the following Content Security Policy directive: "default-src http://localhost:* http://127.0.0.1:*". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

### Steps to reproduce

Either:
* install [LaTeX workshop](https://open-vsx.org/extension/James-Yu/latex-workshop) extension (`James-Yu.latex-workshop
`)
* setup a LaTeX project and compile in gitpod
* view using LaTeX workshop

Or: (not-so-minimal, but easier to set up)
* open a [commit](http://gitpod.io/#https://github.com/jemand771/Vorlage-Latex/commit/62f11a70ac709171f7087c820712fb861d855163) in an affected repo ([launch gitpod](http://gitpod.io/#https://github.com/jemand771/Vorlage-Latex/commit/62f11a70ac709171f7087c820712fb861d855163))
* wait until setup tasks are done
* 1: Click build and wait for it to complete (5-10 seconds)
* 2: open the Latex/main.tex file (or any other .tex file, if you want)
* 3: Click view (the pdf icon, not the reload one). A splitscreen-like tab should open, displaying the error message from above.

Reference: Biuld and View buttons in the status bar:
![image](https://user-images.githubusercontent.com/19669567/122053321-ef8b7b80-cde6-11eb-9650-e7b83c71484d.png)

### Expected behavior

Similar to using a local vscode installation, gitpod should display the pdf in a vscode tab.
Screenshot from my local instance:
![image](https://user-images.githubusercontent.com/19669567/122053694-43966000-cde7-11eb-91bc-a2ee35620613.png)

### Example repository

As mentioned above, my repo https://github.com/jemand771/Vorlage-Latex (fork of https://github.com/DSczyrba/Vorlage-Latex) contains an example to reproduce the issue. It's not exactly minimal, but easy to set up.
Specifically, the gitpod branch: https://github.com/jemand771/Vorlage-Latex/tree/gitpod
Even more specifically, commit https://github.com/jemand771/Vorlage-Latex/commit/62f11a70ac709171f7087c820712fb861d855163 (i'm probably gonna do some thinkering around after that)

### Anything else?

I'm not 100% sure if this is an issue on gitpod's side or maybe due to the way LaTeX workshop handles its PDF viewer. I did check to see if the same error occurs on a different machine/network, which it does. Let me know if there's anything else I can do to help you investigate.

**Comment by TheColin21** [comment]
👍🏻

**Comment by AlexTugarev** [comment]
This might be related: https://github.com/gitpod-io/gitpod/issues/3831#issuecomment-843268778

**Comment by akosyakov** [comment]
It is an issue with an extension. They should use webview csp not localhost.

**Comment by akosyakov** [comment]
moved to upstream: https://github.com/James-Yu/LaTeX-Workshop/issues/2772

**Comment by akosyakov** [comment]
Unfortunately https://github.com/James-Yu/LaTeX-Workshop/issues/2772 was closed without ability for conversations. I will have a look what we can do later, but usually if an extension is not tailored to remote settings there is no much what can help.

**Comment by akosyakov** [comment]
There is multiple issues:
- in Extension: it assumes localhost. It should be rewritten according to https://code.visualstudio.com/api/advanced-topics/remote-extensions#using-the-webview-api cc https://github.com/tamuratak Gitpod or GitHub Codespaces will automatically expose local server running in remote workspace on external URLs, like localhost:5000 translates to some URL accessible on Internet. VS Code exposes a special APIs like asWebviewURI or webview.csp which depending on env will produce proper values, like localhost as you want to have it on localhost or CSP more suitable for internet. Many extensions were already adjusted in such way to support local and remote context.
- in Gitpod: our function to externalise URI drops important bits from URI. It is really a bug and I would fix it in June release

**Comment by akosyakov** [comment]
So the second point will be addressed in https://github.com/gitpod-io/gitpod/pull/4557 We are going to release it hopefully next week.
In regards to first point: Last week we announced the Gipod Local Companion (https://www.gitpod.io/blog/local-app). It is an app which allows to access services from Gitpod workspace on localhost. And it's turned out that It also fixes VS Code extensions which are not yet adopted to run in remote context. Please look at blogpost and aforementioned PR description how to use it.
