### ISSUE TITLE
Run default commands on startup

### ISSUE THREAD

**Issue by Milo123459** [gitpod-io/gitpod#4516]
Hey! Love GitPod, so convenient!

1 thing would make it better, if we could run startup commands on creation of a workspace. For example, running the install script for starship, or custom tools. It'd have to be 1 config and persist across all workspaces

**Comment by ghuntley** [comment]
👋 Welcome, @Milo123459. Glad to hear you are finding Gitpod useful. There are a few things in that message so let's unpack them.

1. If you are asking if it is possible to run commands when a workspace is created then the answer is [yes it is possible](https://www.gitpod.io/docs/references/gitpod-yml).
2. You would like to request the following feature:

> feature: share a gitpod.yml configuration across all workspaces

**Comment by Milo123459** [comment]
I'm thinking more of a share a `.bashrc` across all workspaces. Either works tho

**Comment by ghuntley** [comment]
> I'm thinking more of a share a `.bashrc` across all workspaces. Either works tho

A `bashrc` can currently be shared by creating your own Dockerfile which contains the configuration required. 

https://github.com/gitpod-io/workspace-images/blob/master/base/Dockerfile#L46
