### ISSUE TITLE
add credentials to gitpod extension

### ISSUE THREAD

**Issue by serapath** [gitpod-io/gitpod#452]
`details:` https://mobile.twitter.com/serapath/status/1114585342215168000

users should be able to deploy git repos to servers on demand and interact by sending commands.

anyone could integrate that seevice into their website by prompting users to install your extension

**Comment by meysholdt** [comment]
Thank you for your message. I'm summarizing your request in my own words to see if I understood correctly.

Currenlty we have the "Open in Gitpod" button, which is provided by the Gitpod browser extension.
You propose we should have a "Deploy to Server" that will check out, build and deploy the git repo?

**Comment by serapath** [comment]
Yes, that would be sweet, but it would be nice to expose an API and document it, so that people could make their own browser extensions too :-)
