### ISSUE TITLE
[code] not all extensions are sync

### ISSUE THREAD

**Issue by Milo123459** [gitpod-io/gitpod#4520]
### Bug description

When you install Fluent Icons as your product icon theme, it won't set it as the product icon theme whenever you open a new VSCode workspace, and won't install the extension.

### Steps to reproduce

Install Fluent Icons, set as product icon theme. Create a new workspace, it won't be fuent icons for the product icon theme.

### Expected behavior

It should sync the fact that I am using fluent icons theme.

**Comment by AlexTugarev** [comment]
<img width="735" alt="Untitled-123" src="https://user-images.githubusercontent.com/914497/122198731-b3fdb980-ce99-11eb-955c-c99b9e26bb28.png">

Just verified. This extension is not synced into workspaces opened after installation. 

Seems to be a bug. 

cc. @akosyakov

**Comment by akosyakov** [comment]
Interesting it also does not work for my extension: https://open-vsx.org/extension/akosyakov/gitpod-monitor

**Comment by Milo123459** [comment]
Also bit of an offtopic question, can I connect to my git pod from my desktop vscode and not the in browser one?

**Comment by akosyakov** [comment]
@Milo123459 please track https://github.com/gitpod-io/gitpod/issues/4780 Preview is going to be released later this month.

**Comment by Milo123459** [comment]
> @Milo123459 please track https://github.com/gitpod-io/gitpod/issues/4780 Preview is going to be released later this month.

Thanks! Saw your extension and was curious

**Comment by gengjiawen** [comment]
> Interesting it also does not work for my extension: [open-vsx.org/extension/akosyakov/gitpod-monitor](https://open-vsx.org/extension/akosyakov/gitpod-monitor)

@akosyakov Also my https://open-vsx.org/extension/gengjiawen/vscode-wakatime-gitpods. Any progress on this ? I have to install this for every repo.

**Comment by akosyakov** [comment]
Thanks to Open VSX issue. The following request returns nothing and because of it VS Code does not treat extensions as compatible:
```
Request URL: https://open-vsx.org/vscode/gallery/extensionquery
Request payload: {"filters":[{"criteria":[{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":4,"value":"41aac8eb-b4f4-408d-9708-320d033a17f8"},{"filterType":12,"value":"4096"}],"pageNumber":1,"pageSize":1,"sortBy":0,"sortOrder":0}],"assetTypes":[],"flags":438}
```

**Comment by akosyakov** [comment]
An issue in the upstream: https://github.com/eclipse/openvsx/issues/317

**Comment by gengjiawen** [comment]
> An issue in the upstream: [eclipse/openvsx#317](https://github.com/eclipse/openvsx/issues/317)

@akosyakov I see you fixed upstream bug. Is there any timeline this deployed to gitpod.

**Comment by akosyakov** [comment]
> @akosyakov I see you fixed upstream bug. Is there any timeline this deployed to gitpod.

We are still investigating. The issue was not closed yet. Unfortunately I don't think we have capacity this week.

**Comment by gengjiawen** [comment]
> > @akosyakov I see you fixed upstream bug. Is there any timeline this deployed to gitpod.
> 
> We are still investigating. The issue was not closed yet. Unfortunately I don't think we have capacity this week.

Any progress on this ? I have been installed my extension all the way recently, feeling bit of tired.

**Comment by akosyakov** [comment]
@gengjiawen Could you try now?

**Comment by gengjiawen** [comment]
> @gengjiawen Could you try now?

works like a charm. Thx for the hard work 👍

**Comment by akosyakov** [comment]
ok, closing, please reopen if there are still issues
