### ISSUE TITLE
[ws-manager] evicted workspaces are not backed up

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#4525]
### Bug description

When a workspace pod is evicted (e.g. for hitting RAM limits) we seem not to be able to perform backups.
See https://community.gitpod.io/t/cannot-initialize-workspace-cannot-initialize-workspace-content-initializer-failed/2925/5

We expected this to be fixed but this happened well after [the fix](https://github.com/gitpod-io/gitpod/commit/779d18f450bf47ae1a41acddfbd90912aba610d9) had been deployed.

### Steps to reproduce

Will have to investigate

**Comment by csweichel** [comment]
How can I find the evicted-but-not-backed-up cases you refer to?

**Comment by JanKoehnlein** [comment]
Look for the first incarnation of the mentioned blue-chicken WS:

> {"phase": "stopped", ... "conditions": {"failed": "Evicted: The node was low on resource: memory. Container workspace was using 11135364Ki, which exceeds its request of 1792Mi. ; last backup failed: cannot connect to ws-daemon: pod has no hostIP. Please contact support if you need the workspace data.", ...

**Comment by JanKoehnlein** [comment]
Turns out we didn't deploy it
