### ISSUE TITLE
Asia-Pacific Datacenter.

### ISSUE THREAD

**Issue by vbuterin2** [gitpod-io/gitpod#4526]
Please plan for a datacenter in asia pacific as applications like vnc requires low latency, please consider singapore / japan / sydney

**Comment by ghuntley** [comment]
Howdy @vbuterin2. Could you please share a screenshot from https://gcping.com/ 🚀

nb. I'm based in Sydney, Australia.

**Comment by jankeromnes** [comment]
Very much agree! Thank you for suggesting this @vbuterin2. 🙏

We're currently considering adding a new Gitpod workspace cluster in Singapore. Please follow the progress by subscribing to this issue: https://github.com/gitpod-io/gitpod/issues/5534

**Comment by tnir** [comment]
#5534 has discussed only Singapore region though... 😭
