### ISSUE TITLE
[browser extension] Add Gitpod button for new empty repositories

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#453]
I would like to:

1. Create a new GitHub repository
2. Click on `Gitpod` button to start coding

But there is no `Gitpod` button when my repository is still empty:

![Screenshot_2019-04-08 gitpod-io gitpod-yml-schema](https://user-images.githubusercontent.com/599268/55722592-03691500-5a07-11e9-8cef-45e780e269d4.png)

I can manually prefix the URL with `gitpod.io/#`, but a button somewhere on this page would be much more convenient. 🙂

**Comment by jankeromnes** [comment]
Cc @jbicker

**Comment by jbicker** [comment]
Thanks for the hint! I will have a look at it.

**Comment by jbicker** [comment]
Update is available with this fix.

**Comment by Salvo3** [comment]
Goodmorning everyone. I'm having the same problem too. 
How can I solve it?
thanks a million in adavance

**Comment by Kreyren** [comment]
@Salvo3 Afaik this is fixed already, check the installed version in relation to the release version.
