### ISSUE TITLE
No open ports

### ISSUE THREAD

**Issue by jessezauka** [gitpod-io/gitpod#4531]
### Bug description

I am trying to open 3000 port. 

### Steps to reproduce

Tried everything. 
Added line:

ports:
- port: 3000

Not working

### Expected behavior

Open port

### Example repository

https://github.com/jessezauka/CenitCollegeProject

**Comment by svenefftinge** [comment]
Hey Jesse, that repo seems to be private. Can you share something that helps to reproduce what you are experiencing?
