### ISSUE TITLE
Missing a warning message when opening more than 1 workspace with Gitpod Local Companion

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#4534]
### Bug description

When opening a second workspace, there's no warning message that the second Gitpod workspace is not connected to your local-app.

### Steps to reproduce

1. Run Gitpod Local Companion on your local machine
1. Open https://gitpod.io/#https://github.com/sveltejs/template
1. Run `npm i && npm run dev`
1. Open local browser with localhost:5000
1. (_everything works well_)
1. Open a second workspace - https://gitpod.io/#https://github.com/sveltejs/template
1. Run `npm i && npm run dev`

No warning message that the second Gitpod workspace is not connected to your local-app.

**Comment by akosyakov** [comment]
All workspaces are connected to the local app. There is not primary or secondary. If a port is occupied then random is used.

We probably should have although a status bar indicator whether the local app is connected or not. cc @svenefftinge

**Comment by shaal** [comment]
When I opened the 2 Svelte workspaces, it seems that both of them were running on port 5000.

**Comment by akosyakov** [comment]
You can check in the ports view. First workspace is directly mapped to 5000, but second maps to 62883. It is important that you see `open on localhost` or `open on all interfaces`. If don't have it then your windows failed to connect to the local app, reloading the page should fix it. I meant that we should have a status indicator and allow to reconnect on click without the page reload.
<img width="1904" alt="Screenshot 2021-06-18 at 07 44 45" src="https://user-images.githubusercontent.com/3082655/122498798-2d67ea00-d009-11eb-8a5c-6351bff2b493.png">
<img width="1904" alt="Screenshot 2021-06-18 at 07 44 48" src="https://user-images.githubusercontent.com/3082655/122498788-28a33600-d009-11eb-8515-83fb1d1bf0d5.png">

You can also look at logs of the local app, whether a tunnel was generally established. Later we are going to provide CLI tool which can display such info:
<img width="1509" alt="Screenshot 2021-06-18 at 07 45 10" src="https://user-images.githubusercontent.com/3082655/122498945-715aef00-d009-11eb-9e2e-02e5ac47e985.png">
<img width="1509" alt="Screenshot 2021-06-18 at 07 45 15" src="https://user-images.githubusercontent.com/3082655/122498935-6b650e00-d009-11eb-8612-514e108762ef.png">

**Comment by shaal** [comment]
Requesting adding a label `meta: never-stale`

**Comment by akosyakov** [comment]
Not sure what should be done here. Added to the product groundwork to figure it out.
