### ISSUE TITLE
Button for preview in VScode is not opening correctly while Gitpod Local Companion is running

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#4535]
### Bug description

![image](https://user-images.githubusercontent.com/22901/122414534-37c8ac00-cf55-11eb-853d-edf39b38e95e.png)

It opens a preview in VScode of -
http://localhost:8080

Instead of opening the preview with -
https://8080-maroon-bonobo-56n86lfg.ws-us08.gitpod.io/

### Steps to reproduce

1. Run Gitpod Local Companion on a local machine
1. Run https://gitpod.io/#https://github.com/shaal/ddev-gitpod
1. When it finishes loading, open the ports sidebar
1. Click on "preview" next to port 8080.

### Expected behavior

When running Gitpod Local Companion, VScode preview should open the same URL as when Gitpod Local Companion is not running.

Ie:
Open https://8080-maroon-bonobo-56n86lfg.ws-us08.gitpod.io/
Instead of http://localhost:8080

**Comment by akosyakov** [comment]
> When running Gitpod Local Companion, VScode preview should open the same URL as when Gitpod Local Companion is not running.

It is actually not expected. As we designed it for now tunnels to localhost takes priority of exposure to Internet. What is not expected that the preview is broken for localhost.


For a priority between tunnels over exposure. Maybe we need a preference that a user can configure.
If you do localhost tunnelling but still need exposed URL please use `gp url`.

**Comment by shaal** [comment]
Requesting adding a label `meta: never-stale`

@akosyakov What I suggest, is that when running Gitpod Local Companion app, the preview button in Ports Panel should either:
* Not appear at all, because previewing localhost:8080 in vscode cannot be opened
or
* Because it's preview inside VSCode, open the port like `gp url 8080` instead of localhost:8080.

**Comment by akosyakov** [comment]
> Not appear at all, because previewing localhost:8080 in vscode cannot be opened

It is a bug which should be fixed.

**Comment by roboquat** [comment]
@akosyakov: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4535#issuecomment-920699302):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jeanp413** [comment]
@shaal sorry for the late reply,
Regarding you issue opening `http://localhost:port` in the simple browser works fine, the issue in your case is that drupal is serving your page with `X-Frame-Options: SAMEORIGIN` header in the response, maybe you could configure it so it doesn't send that header during development.

I'll close the issue for now, thanks.
