### ISSUE TITLE
[code] does not open on Android with Edge Chromium

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#4537]
### Bug description

When a workspace starts, the screen is stuck with "Starting - Opening IDE":

<details>
<summary>Click to see screenshot</summary>

![Screenshot_20210617-151618](https://user-images.githubusercontent.com/788827/122464665-17184a80-cf85-11eb-94b9-757a6056efe6.jpg)

</details>

### Steps to reproduce

I haven't found a reliable way, but have seen it on both Brave & Edge browsers on desktop & mobile. Three other people have reported the same behaviour to me via Discord.

### Expected behavior

The workspace starts.

### Example repository

I've seen it on various repos.

### Anything else?

A few more screenshots provided by @shaal 🙏:

![unknown](https://user-images.githubusercontent.com/788827/122465048-93ab2900-cf85-11eb-847f-3b48c5d28fa9.png)

![unknown-1](https://user-images.githubusercontent.com/788827/122465081-a02f8180-cf85-11eb-8428-a74730a0a037.png)

**Comment by shaal** [comment]
I am having this issue ^^ with Edge browser on Android.
It never passes that screen (as oppose to Chrome on Android that always work as expected).
Please let me know if I can provide any additional details.

**Comment by akosyakov** [comment]
a duplicate of https://github.com/gitpod-io/gitpod/issues/4448

**Comment by akosyakov** [comment]
As a workaround till release reload the page. It was a race of loading grpc-web and local app.

**Comment by shaal** [comment]
@akosyakov reloading the page does not solve the problem.

**Comment by akosyakov** [comment]
@shaal Could you share the devtools log? And also

**Comment by akosyakov** [comment]
I just tried on both Brave and Edge on Mac and could not reproduce unfortunately. I will need some proper devtools logs as an input to start investigation.

**Comment by shaal** [comment]
The screenshots I took, were taken by connecting my Android phone to the desktop computer and debugging it.
 
As I wrote in https://github.com/gitpod-io/gitpod/issues/4537#issuecomment-863529451, the issue ONLY happens on **Edge** that is running on **Android** phone.

Any other browser is working as expected. It is working on Chrome and Edge on desktop. It is working on Chrome on Android.

The only thing that doesn't work - is Edge browser on Android.

**Comment by shaal** [comment]
This problem also happens on android tablet, running Edge Chromium

**Comment by shaal** [comment]
I tested Github.dev, and github1s.com
They all seem to have the same problem, VScode doesn't open on Android with Edge Chromium browser.

**Comment by akosyakov** [comment]
Could it be that you don't use latest version? From your logs it seems that optional chaining is not supported. Could you share versions of OS and browsers?

**Comment by shaal** [comment]
@akosyakov I added devtools inspect details here -
https://github.com/microsoft/vscode/issues/131382

Also, the issue is specifically with Edge Chromium browser on mobile device (and not with Chrome browser).
