### ISSUE TITLE
Allow installing Gitpod-App on Orgs via Marketplace, not only via App listing

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#454]
In the Github Marketplace, the Gitpod App (https://github.com/marketplace/gitpod-io) can only be installed for personal GitHub accounts, but not for organizations. 

However, when you access the app via the app listing (https://github.com/apps/gitpod-io), it can be configured for organizations. 

This is confusing because people who find the app via marketplace and fail to install it on their org don't realize that there is another way. 

There should be an intuitive way for visitors of the marketplace to enable prebuilds for their org-repos.

**Comment by svenefftinge** [comment]
Changed that settings.
