### ISSUE TITLE
[dashboard] text wrapping on "workspace is already running" dialog

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#4556]
### Bug description

<img width="987" alt="2021-06-21_11-58-56" src="https://user-images.githubusercontent.com/127353/122697309-6792ef00-d288-11eb-844e-c9dc14a1dd4a.png">

### Steps to reproduce

1. Start workspace via https://gitpod.io/#EXAMPLE_DIR=typescript%2Fgraphql/https://github.com/ghuntley/prisma-examples/tree/gh/gitpodify
2. Start another workspace via https://gitpod.io/#EXAMPLE_DIR=typescript%2Fgraphql/https://github.com/ghuntley/prisma-examples/tree/gh/gitpodify

### Expected behavior

Design implementation accommodates long URLs

<img width="987" alt="2021-06-21_11-58-56" src="https://user-images.githubusercontent.com/127353/122697343-7bd6ec00-d288-11eb-9fd3-037f09d7503b.png">

**Comment by jankeromnes** [comment]
Good catch! This qualifies as a good-first-issue that anyone can pick up (please add a comment below if you'd like to try fixing this).

The corresponding React element needs:
- A `truncate` CSS classname (see corresponding [Tailwind docs](https://tailwindcss.com/docs/text-overflow))
- A `title` attribute (so that you can still see the full text when hovering over the truncated text)

Code location:

https://github.com/gitpod-io/gitpod/blob/2f7cc1579eff6b1f0390bc2841dfa85680d9a15c/components/dashboard/src/start/CreateWorkspace.tsx#L168

**Comment by sandyabhi** [comment]
Hey, I would like to work on this.

**Comment by gtsiolis** [comment]
Hi @sandyabhi! Sounds great, feel free to open PR with a fix and and link back to this issue. 🏓

**Comment by ghuntley** [comment]
Awesome. Make it so @sandyabhi

**Comment by sandyabhi** [comment]
Hi, @ghuntley is there any gitpod IRC channel? I have been stuck after the "serve -s build"  localhost 5000 showing error.

**Comment by ghuntley** [comment]
Yes, www.gitpod.io/chat

**Comment by sandyabhi** [comment]
hi, @ghuntley , 
I just open forked gitpod repo
after all the installation gitpod do
I type the command "npm serve build "
then " serve -s build"
localhost: 5000 shows
![Screenshot (14)](https://user-images.githubusercontent.com/75850277/123379901-61fd1800-d5ac-11eb-880c-af800b1c2a7b.png)

**Comment by roboquat** [comment]
@gtsiolis: GitHub didn't allow me to assign the following users: Cahllagerfeld.

Note that only [gitpod-io members](https://github.com/orgs/gitpod-io/people), repo collaborators and people who have commented on this issue/PR can be assigned. Additionally, issues/PRs can only have 10 assignees at the same time.
For more information please see [the contributor guide](https://git.k8s.io/community/contributors/guide/first-contribution.md#issue-assignment-in-github)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4556#issuecomment-900883342):

>/assign @Cahllagerfeld


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
