### ISSUE TITLE
[diff] The Diff view is empty for the PR

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#457]
**Describe the bug**

The Diff view is empty for a PR: https://github.com/theia-ide/theia/pull/4762

**To Reproduce**

Open the PR.

**Expected behavior**
I can see the changes in the Diff view.

![Screen Shot 2019-04-09 at 11 46 48](https://user-images.githubusercontent.com/1405703/55791171-37ebd800-5abe-11e9-8a9c-2f3d27d22f5b.jpg)

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/6dd1731d-2d40-47c1-8488-ad127c58383d)

**Comment by AlexTugarev** [comment]
It looks like it's broken for prebuilt workspaces. For example, it works fine for https://gitpod.io/#https://github.com/qmk/qmk_firmware/pull/5593.

**Comment by akosyakov** [comment]
It's reproducible for any prebuilt workspace from a fork. An underlying issue is that upstream branch is not set for them.
