### ISSUE TITLE
[Self-hosted] installNetworkPolicies is not respected 

### ISSUE THREAD

**Issue by cyrilcros** [gitpod-io/gitpod#4574]
### Bug description

Hi, I am trying the new v9 Chart version. Things are going fine, and then I hit the bug reported here: https://community.gitpod.io/t/gitpod-0-9-0-chart-self-hosting-anyone-succeeded/3789/11?u=cyrilcros

That could point to a networkPolicy blocking access to the cluster DNS, but I set ` installNetworkPolicies: false` in the chart. I still see a messageBus `NetworkPolicy` is generated from the the chart, and the templates of some components do not check if `installNetworkPolicies`.

### Steps to reproduce

- Install self hosted v9 with ` installNetworkPolicies: false`
- Look for NetworkPolicy objects being created

### Expected behavior

No network policy should be created with  `installNetworkPolicies: false`. This matters, because they work on a whitelist basis: if you use even one, then all communications that are not explicitly whitelisted are blocked.

### Anything else?

If possible, just add access to cluster DNS where required as there: https://github.com/gitpod-io/gitpod/issues/1942#issuecomment-703455017

### Finally
I guess also in this case I am hitting a dumb DNS issue because the registry DNS name is not created in my own server...

**Comment by cyrilcros** [comment]
I want to add a big thank you to the devs, self-hosted now works for me! https://community.gitpod.io/t/gitpod-0-9-0-chart-self-hosting-anyone-succeeded/3789/22?u=cyrilcros

**Comment by corneliusludmann** [comment]
Indeed, the messagebus networks policy is created independently from the value of `installNetworkPolicies`. The reason is that the messagebus rabbitmq is installed as a dependency, not by our templates. You need to disable the network policies  here:

https://github.com/gitpod-io/gitpod/blob/25ece59c495d525614f28971d41d5708a31bf1e3/chart/values.yaml#L533-L535
