### ISSUE TITLE
Stuck at Allocating Resources

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#4576]
### Bug description

Workspace is stuck at allocating resources for minutes. This applies to both old and existing workspaces.

### Steps to reproduce

1. Open existing workspace
2. Stuck at allocating resources message

### Expected behavior

The workspace should open

### Example repository

https://github.com/kunxin-chor/tgc12-mysql-chinook
https://github.com/kunxin-chor/tgc12-mysql

**Comment by corneliusludmann** [comment]
Hey @kunxin-chor! Sorry for the bad experience. Does it still happen to you?

**Comment by kunxin-chor** [comment]
Hi it has has been resolved automatically.
