### ISSUE TITLE
yaml comments should NOT be part of executed command

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#458]
```yaml
command: >
    # start window manager
    jwm & &&
    # start browser example
    yarn --cwd examples/browser start ../..
```

translates to:
`# start window manager jwm & && # start browser example yarn --cwd examples/bowser start ../..`

**Comment by meysholdt** [comment]
maybe the fix is to properly pass the linebreaks to `bash` so that `bash` can properly filter out the comments. This would also make it unnecessary to finish the lines with `;` or `&&`.

**Comment by svenefftinge** [comment]
Maybe you should use `|` instead then? I don't think we should do anything about it as it is yaml semantics. https://yaml-multiline.info/
