### ISSUE TITLE
Make browser extension options (settings) more discoverable

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4591]
### Problem to solve

Currently, browser extension options (settings), like setting the Gitpod installation URL (see [relevant docs](https://www.gitpod.io/docs/browser-extension#use-with-gitpod-self-hosted)), are not quite discoverable.

### Proposal

There are two improvements that could make browser extension options (settings) more discoverable:
1. Improve the visual and user experience design of the settings panel, by introduing a standalone settings page.
2. Allow changing the configuration without visiting a different page from within a dropdown with one left click.

For example, see extension settings for the sourcegraph extension.

| Sourcegraph Dropdown | Gitpod Dropdown | Sourcegraph Settings | Gitpod Settings |
|-|-|-|-|
| <img width="459" alt="Screenshot 2021-06-23 at 7 01 23 PM" src="https://user-images.githubusercontent.com/120486/123131647-8e9f1b80-d456-11eb-90f3-5965639ee8d6.png"> | <img width="303" alt="Screenshot 2021-06-23 at 7 02 58 PM" src="https://user-images.githubusercontent.com/120486/123131461-62839a80-d456-11eb-9df7-a026894e89d1.png"> | <img width="1440" alt="Screenshot 2021-06-23 at 7 00 31 PM" src="https://user-images.githubusercontent.com/120486/123131601-82b35980-d456-11eb-86d4-2625a483865e.png"> | <img width="1440" alt="Screenshot 2021-06-23 at 7 03 55 PM" src="https://user-images.githubusercontent.com/120486/123131472-64e5f480-d456-11eb-9817-bdd7ed40df5f.png"> |

**Comment by corneliusludmann** [comment]
> 2\. Allow changing the configuration without visiting a different page from within a dropdown with one left click.

The reason, that a left click opens the current page as context URL is to support self-hosted GitLab installations. With this feature. you can click on the extension icon to open a repo in your self-hosted GitLab installation with the Gitpod installation configured in the settings dialog.

We can move this action to the context menu. However, this would need 2 clicks to open the repo in Gitpod for users of self-hosted GitLab installations. We could also introduce a configuration flag for this behavior.

**Comment by gtsiolis** [comment]
Closing this as extension settings got more visible with the latest release.

<img width="408" alt="Screenshot 2023-09-27 at 18 00 40" src="https://github.com/gitpod-io/gitpod/assets/120486/4ac8ca54-06b3-4d4b-b211-55a6547ffcb0">

Cc @filiptronicek @svenefftinge @laushinka @loujaybee
