### ISSUE TITLE
Webpack hot reloader gets ERR_CONNECTION_REFUSED over websocket.

### ISSUE THREAD

**Issue by mikesol** [gitpod-io/gitpod#4599]
### Bug description

When updating a file in my project that is supposed to trigger a webpack hot reload, I see in the command line that it picks up on the file:

```bash
./output/Gopher/index.js 10.5 KiB [built] [code generated]
```

![Screenshot from 2021-06-24 08-58-27](https://user-images.githubusercontent.com/525350/123210510-c2b42400-d4ca-11eb-8835-33d05929bbda.png)

But when visiting the browser, I see several error messages saying a connection with the websocket cannot be established:

![Screenshot from 2021-06-24 08-58-48](https://user-images.githubusercontent.com/525350/123210562-d95a7b00-d4ca-11eb-8a13-9ef2fb1be97e.png)

I'm wondering if there is a special setting that needs to be enabled to get this to work? It works fine locally.

### Steps to reproduce

1. Navigate to https://www.gitpod.io/#https://github.com/mikesol/wagsi.
1. From the terminal on the bottom of the screen, run `npm install`.
1. Run `npm run gitpod` to install PureScript IDE.
1. Press `Ctrl+Shift+P` and look for the command **PureScript: Restart/Reconnect purs IDE server**. Select this. You can monitor the output of the purescript ide server by clicking on the output tab. Eventually, yellow (or red) squigglies should show up in your source files.
1. Run `npm start` to start the webpage.
1. You'll see a pop-up asking to open a port and to open the page in your browser. Click on both. This will open a new page for your audio session.
1. On the new page, click **Start audio**.
1. Back in the online editor, open up Wagged and start changing stuff. For inspiration, you can use this `graph`:

```purescript
graph e (a :: Unit) = a /-\ speaker { unit0: gain (cos (pi * e.time) * -0.02 + 0.02) { osc0: sinOsc 440.0 } }
```

Already by this point, you should see the error message in the console of the browser saying that the websocket connection cannot be established.

### Expected behavior

The websocket connection should be established or there should be documentation on settings needed to allow webpack to hot reload. If this feature isn't supported at the moment, that would be helpful to know as well.

### Example repository

https://github.com/mikesol/wagsi (pretty minimal, only a few files and one hot reload - the only issue is it takes a while to compile, but it gets the job done). Thanks!

**Comment by mikesol** [comment]
Closing issue as I found the solution here: https://community.gitpod.io/t/setting-up-webpack-dev-server-on-gitpod/1648.

**Comment by akosyakov** [comment]
We released the preview of Gitpod Local Companion which allows to access services from Gitpod workspace on localhost: https://www.gitpod.io/blog/local-app

It is easier to get started than changing configuration to `gp url`, but they are not replacement: `gp url` allows to expose the port to Internet while the local app to tunnel the port to the user local network.
