### ISSUE TITLE
We Cannot connect to the Extensions Marketplace at this time, please try again later.

### ISSUE THREAD

**Issue by tahlilma** [gitpod-io/gitpod#4600]
### Bug description

I opened up one of my workspaces today and saw that none of my extensions were activation. I waited for 5 mins thinking that it would work but it did not. When I went to the 'Extensions' tab there was no extensions present there and the only thing it showed was this. 

![image](https://user-images.githubusercontent.com/67750110/123211371-3531fd80-d4e5-11eb-8243-ebff369c4bfe.png)

Without searching it looks like 
![image](https://user-images.githubusercontent.com/67750110/123211422-4418b000-d4e5-11eb-8166-8ef768a1212b.png)
It  loops infinitely.

(This is my first ever issue so please forgive me for anything wrong)

### Steps to reproduce

It happened to me at random

### Expected behavior
The extensions should automatically be installed and they should be visible in the extensions tab.

**Comment by corneliusludmann** [comment]
OpenVSX seems to be down. See https://github.com/EclipseFdn/open-vsx.org/issues/555 and https://www.eclipsestatus.io/incidents/1hs2z6hznqhl.

**Comment by jankeromnes** [comment]
The incident was resolved and https://open-vsx.org is back online.

See also https://www.gitpodstatus.com/incidents/84ktht09s7rx

**Comment by shaal** [comment]
Extension Marketplace is not accessible in Gitpod again.

https://www.open-vsx.org screenshot:
![image](https://user-images.githubusercontent.com/22901/126591748-299db26c-3ef7-429b-82d0-786ef6bd64ae.png)

**Comment by meysholdt** [comment]
This issue was resolved back in June. It looks like we forgot to close it back then. Doing that now.
