### ISSUE TITLE
Figure out Teams & Projects top menu navigation

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4622]
From https://github.com/gitpod-io/gitpod/pull/4571#pullrequestreview-692696153:

> One last question: Somewhere we split the team dropdown into two distinct elements. Could we restore this as one component? See [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1624363839230600) (internal). ❓ 

We've recently split the Team selector dropdown into two parts:
1. Clicking on the team name goes to the default team page (i.e. "Projects", or "Workspaces" if your personal account is selected)
2. Clicking on the arrow allows switching to a different team

<img width="520" alt="Screenshot 2021-06-25 at 18 12 56" src="https://user-images.githubusercontent.com/599268/123454702-2761a280-d5e1-11eb-8524-7ecebd4b8dec.png">

The thought was to allow a sort of "breadcrumb navigation", allowing to:
1. Dive into Teams > Projects > (a project) > (a prebuild)
2. Go back (e.g. to the Team, or switch to another team)

similar to how Vercel does it:

<img width="576" alt="Screen Shot 2021-06-25 at 14 42 01" src="https://user-images.githubusercontent.com/599268/123454491-ea95ab80-d5e0-11eb-9159-8b841a13c73e.png">

However, the current implementation feels awkward:
1. Clicking on my name (biggest clickable surface) does the same thing as clicking on the Gitpod logo (i.e. go to "Workspaces") -- it feels awkward that these two "primary" items go to the same place (i.e. broken link?)
2. Switching teams can only be done by clicking on the super small down-arrow (requires more precision & effort and might get overlooked)

It would be cool to improve this.

### Proposal

In this iteration we can:

1. Introduce a new team selector (dropdown) component
2. Use a similar icon for showing the second-level page like prebuilds
3. (Optional) Add a hypelink on the project breadcrumb item to link back to project overview page.

### Designs

| Default | Hover | Active |
|-|-|-|
| <img width="1000" alt="Default" src="https://user-images.githubusercontent.com/120486/123949583-67db6a80-d9ab-11eb-84a6-ee091e80ce42.png"> | <img width="1000" alt="Hover" src="https://user-images.githubusercontent.com/120486/123949587-68740100-d9ab-11eb-9fac-68fa1b4575d2.png"> | <img width="1000" alt="Active" src="https://user-images.githubusercontent.com/120486/123949594-6a3dc480-d9ab-11eb-81e5-d40a682e6125.png"> |

| Project | Prebuild |
|-|-|
|  <img width="1000" alt="Project" src="https://user-images.githubusercontent.com/120486/123949764-9c4f2680-d9ab-11eb-82c4-5aff25e95289.png"> | <img width="1000" alt="Prebuild" src="https://user-images.githubusercontent.com/120486/123949767-9d805380-d9ab-11eb-990d-735e5bccb190.png"> |

See [design specs](https://www.figma.com/file/vvrocXdwNaKEjHaMvMcoRZ/Teams-and-Projects-top-menu-navigation-4622?node-id=0%3A1).

**Comment by jankeromnes** [comment]
Giving this a go 🖌️

**Comment by AlexTugarev** [comment]
@jankeromnes please base on https://github.com/gitpod-io/gitpod/pull/4876 🙏🏻  as I already added some changes to the menu structure.

**Comment by jankeromnes** [comment]
@AlexTugarev makes sense, thanks! I [agree](https://github.com/gitpod-io/gitpod/pull/4917#issue-695758804) 😁

> - [ ] Fix top menu UX: https://github.com/gitpod-io/gitpod/issues/4622 (looks like part of that is already being implemented in https://github.com/gitpod-io/gitpod/pull/4876)
