### ISSUE TITLE
When starting a new workspace, I want to choose the docker image in Docker Hub

### ISSUE THREAD

**Issue by twtwtw-gj** [gitpod-io/gitpod#4625]
[Ideal]

- access https://gitpod.io/workspaces
- push the button "new workspace"
- There is a tub "choose docker image in Docker Hub", and an input which I set docker image, new workspace will start in this image.

**Comment by atduarte** [comment]
@twtwtw-gj could you please help me understand what problem you are trying to solve.

Currently, the docker image used is already configurable by changing the .gitpod.yml/.gitpod.Dockerfile.  https://www.gitpod.io/docs/config-docker#custom-docker-image

**Comment by twtwtw-gj** [comment]
I think that if there is a new button "set up a new workspace", after changing .gitpod.yml, we can reset my workspace more convenient than now.

**Comment by ghuntley** [comment]
So if I understand correctly @twtwtw-gj the dashboard would expose a way to search images on dockerhub (nb: only ubuntu images are compatible with vscode) then launch that image on Gitpod without establishing a git repository first?

<img width="603" alt="2021-08-28_15-38-37" src="https://user-images.githubusercontent.com/127353/131207604-73189d52-89ac-4511-8db8-d23901d3a7c4.png">

<img width="954" alt="2021-08-28_15-39-13" src="https://user-images.githubusercontent.com/127353/131207614-7cfba673-1e74-45b2-8c02-d3baee5a0cee.png">

**Comment by twtwtw-gj** [comment]
Yes, thank you for understanding what I said.

**Comment by atduarte** [comment]
If I understood correctly there are two requests:
1. To open an arbitrary Docker image from the dashboard, selecting it from the Docker Hub
2. To have a way to rebuild the workspace (or create a new one) using the edited .gitpod.yml/.gitpod.Dockerfile

Is that correct? 

Could you please describe the use case or general problem you are trying to solve with the first one?

**Comment by twtwtw-gj** [comment]
> Is that correct?

Yes.

I usually edit .gitpod.Dockerfile in the gitpod dev environment. I often think , the procedure which includes git-committing, pushing and restarting my workspace is complicated.
