### ISSUE TITLE
Make account information editable

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4629]
### Problem to solve

We've received a couple of reports that username or email changes are not reflected in Gitpod, see https://github.com/gitpod-io/gitpod/issues/4390, https://github.com/gitpod-io/gitpod/issues/3957, etc.

### Proposal

Since it could be optimal to avoid syncing this information from the provider (see https://github.com/gitpod-io/gitpod/issues/4390#issuecomment-854805362 cc @AlexTugarev) we could allow users to edit this data within Gitpod from `/account`.

**Comment by geropl** [comment]
Workaround:
 - logout of Gitpod
 - login again

**Comment by corneliusludmann** [comment]
Random thought: With https://github.com/gitpod-io/gitpod/pull/4115 merged, we could give users the freedom to choose which of the verified email address from GitLab/GitHub should be used for communication via a drop-down menu.

**Comment by jldec** [comment]
The account name in the Gitpod account settings (and also in the account dropdown at the top of the dashboard) does not change when the GitHub account id is renamed on GitHub, or when the integration is removed and then reconnected (assuming another integration exists).

The user id on the integration is correctly updated.

# GitHub

![Screenshot 2021-12-23 at 15 52 12](https://user-images.githubusercontent.com/849592/147263772-d2c93701-dbb6-4386-bc9a-3c20ba8a9735.png)

---

# Gitpod

![Screenshot 2021-12-23 at 15 48 38](https://user-images.githubusercontent.com/849592/147263475-73f11307-0af5-4b28-8955-d95d561fe767.png)

![Screenshot 2021-12-23 at 15 48 59](https://user-images.githubusercontent.com/849592/147263396-e8d6c01f-d985-4b11-845a-fbb68827124a.png)

**Comment by filiptronicek** [comment]
> Random thought: With #4115 merged, we could give users the freedom to choose which of the verified email address from GitLab/GitHub should be used for communication via a drop-down menu.

This would be great; I think my account is still using my secondary email address while my primary one (filip@gitpod.io) is not used.

**Comment by jadeastar** [comment]
Is this issue still active?

**Comment by gtsiolis** [comment]
It's alive, @jadeastar! We probably going to work on this in the near future if there's more demand. FYI, there're a few work arounds if you run into this issue, like re-creating the account, re-connecting a provider or using environment variables to set a different author name and email. 💡

**Comment by jadeastar** [comment]
> It's alive, @jadeastar! We probably going to work on this in the near future if there's more demand. FYI, there're a few work arounds if you run into this issue, like re-creating the account, re-connecting a provider or using environment variables to set a different author name and email. 💡 

I appreciate the fast response! Thank you for all your work :)

**Comment by gtsiolis** [comment]
Closing this in favor of https://github.com/gitpod-io/gitpod/issues/10999 which contains more information around the problem solution. Cc @svenefftinge
