### ISSUE TITLE
Scrolling position lost sometimes after expanding explorer branch

### ISSUE THREAD

**Issue by mkarg** [gitpod-io/gitpod#463]
**Describe the bug**
Sometimes it happens that the explorer scrolls down (so loses its scroll position) when expaning a branch. This is very annoying as you visually lose track where that branch actually is, particularly if then tree is very long and very deep.

**To Reproduce**
In a project with a long and deep branch, expand some branches. Sometimes it will happen, sometimes not.

**Expected behavior**
The scroll position stays the same, i. e. the Y-coordinate of the expanded branch does not change.

**Comment by alesanchezr** [comment]
I'm having this same problem, it's really annoying, here is an animated gif to explain it better:

![2019-04-25 16 23 23](https://user-images.githubusercontent.com/426452/56766135-bdd27900-6776-11e9-9041-353d2f31aa99.gif)
