### ISSUE TITLE
remove Theia and move extension resolution to Code

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4630]
We don't support user uploaded extensions anymore and going to remove Theia. After that we can remove extension resolution logic from server and resolve extensions directly from .gitpod.yml on Gitpod Code Server startup.

**Comment by AlexTugarev** [comment]
is there an ETA for the departure of Theia? would be good to link here.

**Comment by akosyakov** [comment]
Theia is deprecated in June release and should be removed in July release.

**Comment by gtsiolis** [comment]
Cross-posting the relevant issue for removing the corresponding dashboard section, see https://github.com/gitpod-io/gitpod/issues/4486.

**Comment by JanKoehnlein** [comment]
On the settings page, we state

> We're deprecating the Theia editor. You can still switch back to Theia for the next few weeks but the preference will be removed by the end of August 2021.

Maybe we should wait until end of August?

**Comment by akosyakov** [comment]
But we should start working on it.

**Comment by csweichel** [comment]
I'm afraid we're a bit stuffed on groundwork right now. Please add back in a week's time. 

Also there are plenty of other code issues scheduled :)

**Comment by bd82** [comment]
I'm just wondering.

The fact this issue is still open means gitpod is stlil using Theia under the hood?

**Comment by JanKoehnlein** [comment]
>The fact this issue is still open means gitpod is stlil using Theia under the hood?

No, it doesn't. There is just some dead code and config to be cleaned up

**Comment by bd82** [comment]
> No, it doesn't. There is just some dead code and config to be cleaned up

Thanks for clearing this up.

**Comment by akosyakov** [comment]
@mustard-mh @jeanp413 I think now it can be done, since we don't consume env vars computed by Gitpod Server anymore. It will remove a dependency from Server to OpenVSX and should improve workspace startup time a bit if it has .gitpod.yml.
