### ISSUE TITLE
Improve controls on tablets and mobile devices

### ISSUE THREAD

**Issue by jwpjrdev** [gitpod-io/gitpod#4639]
I am currently working on an iPad. From a few 
hours of messing around, I've found a few issues. 

For example, terminals are hard to resize because it requires a lot of precision.

Another issue I've found is the lack of an easy way to close files/tabs. Hotkeys such as command+W simply close the tab (in the browser) on most browsers. This is extremely annoying coming from a PC where it's my most prevalent method of closing files. A few other hotkeys don't work very well (or at all) either.

Errors are also extremely hard to deal with. iPads have no version of hovering so you can't just hover over text to see the error. Instead, you have to compile and try it out. In languages like Rust this is super straightforward because it tells you everything but I'd imagine in C++ or any other language with a less informative compiler it would be a pain.

It'd be really nice to see improvement on these weak spots.

**Comment by heldr** [comment]
A simple way to overcome the `cmd + w` issue is adding workspace to home screen, that will turn it into a PWA(Progressive Web App).

**Comment by akosyakov** [comment]
> A simple way to overcome the cmd + w issue is adding workspace to home screen, that will turn it into a PWA(Progressive Web App).

You have to do it for each workspace, i.e. an app per a workspace, correct?

**Comment by jwpjrdev** [comment]
Yes, that works, but it’s quite clunky. If you simply save gitpod.io or anything but the workspace itself it doesn’t work.

Another random thing that I should probably open in another issue is that when testing extensions, it opens a new “tab” of VS Code. However, it simply replaces the window. It’d be nice if the dev workspace and testing environment opened in separate browser tabs so I don’t have to reopen it every time I want to mess with the extension’s code.

> On Jul 11, 2021, at 11:09 PM, Anton Kosyakov ***@***.***> wrote:
> 
> ﻿
> A simple way to overcome the cmd + w issue is adding workspace to home screen, that will turn it into a PWA(Progressive Web App).
> 
> You have to do it for each workspace, i.e. an app per a workspace, correct?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
________________________________________________


*CONFIDENTIALITY 
NOTICE:*

*The information transmitted in this electronic message may be 
legally privileged and confidential under applicable law, including the 
Family Educational Rights and Privacy Act (FERPA) and the Health Insurance 
Portability and Accountability Act (HIPAA), and is intended only for the 
person or entity to which it is addressed. If the recipient of this message 
is not the above named intended recipient, you are hereby notified that any 
review, retransmission, dissemination, copy, disclosure or other use of, or 
taking any action in reliance upon, this information by persons or entities 
other than the intended recipient is prohibited. If you received this 
electronic transmission in error, please notify Mississinewa Community 
School Corporation at (765) 674-8528, and purge the communication 
immediately from any computers, storage devices, paper or other media 
without making any copy or distribution thereof. Thank you for your 
cooperation.*

**Comment by heldr** [comment]
> > A simple way to overcome the cmd + w issue is adding workspace to home screen, that will turn it into a PWA(Progressive Web App).
> 
> 
> 
> You have to do it for each workspace, i.e. an app per a workspace, correct?

correct! 1 app per workspace.

**Comment by akosyakov** [comment]
I had the same experience with PWA, as for now they don't scale well for apps requiring multiple origins. There seem to be some proposed solutions: https://web.dev/pwa-url-handler/ Maybe we can find time to make a prototype.
