### ISSUE TITLE
IDE temporarily prevents cleanup of maven target folder

### ISSUE THREAD

**Issue by mkarg** [gitpod-io/gitpod#464]
**Describe the bug**
Sometimes the IDE temporarily prevents cleanup of maven target folder, resulting in messages like this:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:3.1.0:clean (default-clean) on project maven-shade-plugin: Failed to clean project: Failed to delete /workspace/maven-shade-plugin/target -> [Help 1]`

**To Reproduce**
Unfortunately the problem only happens *sporadically*.
* Open maven project in IDE
* `mvn clean package` - runs well
*  Expand explorer branches of `target` folder
* `mvn clean package` - sometimes fails with above message
* `mvn clean package` - runs well even when executed directly after it failed

**Expected behavior**
* Never fails to clean `target`

**Comment by akosyakov** [comment]
Do you mean that Explorer is not refreshed? Could you toggle expansion of `target` folder? There is a known issue that fs events for symlinked folders are not reported properly, maybe you are hitting it.

**Comment by akosyakov** [comment]
Ah I see you are getting an error on the terminal, so fs watching is not related.

**Comment by mkarg** [comment]
@akosyakov No I don't mean that explorer is not refreshed, I mean that `mvn clean` says:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:3.1.0:clean (default-clean) on project maven-shade-plugin: Failed to clean project: Failed to delete /workspace/maven-shade-plugin/target -> [Help 1]`

**Comment by svenefftinge** [comment]
Could it be that the LS and maven are operating on the same files and run into locks/conflicts?
