### ISSUE TITLE
files not showing 

### ISSUE THREAD

**Issue by marc1210** [gitpod-io/gitpod#4640]
### Bug description

when starting the code and when it loads the files don't show to the left.  How can see the files 

### Steps to reproduce

i have no idea why its happening

**Comment by akosyakov** [comment]
@marc1210 Could you share your workspace ID or repo with whit that happens, thank you?

**Comment by akosyakov** [comment]
From backend logs, it looks like you are using Theia, please make sure switch to Code and try again: https://gitpod.io/preferences Theia is going to be deprecated this week and removed in one month. We don't maintain it anymore.

**Comment by marc1210** [comment]
![image](https://user-images.githubusercontent.com/47263287/123999858-f5658d00-d9a0-11eb-92cf-194819cc9024.png)

**Comment by marc1210** [comment]
![image](https://user-images.githubusercontent.com/47263287/124000042-2c3ba300-d9a1-11eb-9e49-192d334ac486.png)

**Comment by gtsiolis** [comment]
Closing this as we've deprecated Theia in favor of VS Code editor, see https://github.com/gitpod-io/gitpod/issues/4459 and https://github.com/gitpod-io/gitpod/issues/4486.
