### ISSUE TITLE
Handle deletions and re-creation of GitHub accounts

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#4656]
Since https://github.com/gitpod-io/gitpod/pull/3950 Gitpod won't let you create a new account using a taken email address with a different GitHub account. This might be a valid case though, when the first GH account was deleted.

A solution might be to query the GH API for the other user's GH profile. If the profile is 404:
 1. disconnect other user's GH identity (to be discussed)
 2. allow creating a new account

**Comment by aggmoulik** [comment]
@AlexTugarev is anyone working on the issue?

**Comment by gtsiolis** [comment]
@aggmoulik no one is working on this at the moment. Is this a blocking issue for you?

**Comment by aggmoulik** [comment]
No, I was wondering whether I can work on this issue.

**Comment by gtsiolis** [comment]
Hey @aggmoulik! Feel free to open a PR to resolve this. 🏓

**Comment by MODmasterBlock** [comment]
I have this issue
