### ISSUE TITLE
Unreadable text in the terminal

### ISSUE THREAD

**Issue by boris-remo** [gitpod-io/gitpod#4665]
### Bug description
![image](https://user-images.githubusercontent.com/81965134/123973480-771ae200-d9c4-11eb-8946-d3e4ff399d3a.png)

### Steps to reproduce

I opened one of my repos in gitpod and the terminal text was illegible. The rest of VSCode looks good

### Expected behavior

The text in the terminal is as readable as the rest of the app

### Example repository

https://jade-goat-iq1s10uh.ws-eu08.gitpod.io/

**Comment by akosyakov** [comment]
It should be fixed in next release: https://github.com/gitpod-io/gitpod/issues/4130
