### ISSUE TITLE
Gitpod tries to pull Theia image with a tag that does not exist

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#4679]
- See #4672
- I tagged `eu.gcr.io/gitpod-core-dev/build/ide/theia@sha256:537433f51fc21561d117c65746601eed95a8f9e08d8d31e81b03defdea65e238` by hand with tag `commit-f8da2b7b725c2a0949f904ead725763923b653ea`, now it works
- We need to investigate why this missing tag happened in the first place

**Comment by meysholdt** [comment]
Probably not the cause, but it makes finding stuff a bit harder: 
Commit [f8da2b7b725c2a0949f904ead725763923b653ea](https://github.com/gitpod-io/gitpod/commit/f8da2b7b725c2a0949f904ead725763923b653ea) is [not on master](https://github.com/gitpod-io/gitpod/issues/4667)

The build for commit ...53ea is [gitpod-build-jh-track-user-deletion.0](https://werft.gitpod-dev.com/job/gitpod-build-jh-track-user-deletion.0) and the [Theia image](https://github.com/gitpod-io/gitpod/tree/main/components/ide/theia) is not part of the build results:

![image](https://user-images.githubusercontent.com/239422/124188206-3a7fe100-dabf-11eb-8ba3-9a702ab4e016.png)

**Comment by meysholdt** [comment]
`docker run eu.gcr.io/gitpod-core-dev/build/versions:jh-track-user-deletion.0 cat /versions.yaml` returns
```
theiaImage:
      version: commit-195a305c297b4989e26d075f65f036f3bbfe34c6
```

Since that version is different from the one Cornelius posted, I suspect the cause is a config error: The Theia image is being pulled using a tag that was designated for a another image.

**Comment by meysholdt** [comment]
From the prod `server` k8s deployment:
```
        - name: SERVER_VERSION
          value: commit-f8da2b7b725c2a0949f904ead725763923b653ea
(...)
        - name: THEIA_IMAGE_REPO
          value: eu.gcr.io/gitpod-core-dev/build/ide/theia
```

It looks like the Theia image is using the server-version.

https://github.com/gitpod-io/gitpod/blob/ce50d2a812a791bc331467ac756b16ac3821f6e9/chart/templates/server-deployment.yaml#L142-L149

The server should obtain+use the Theia-version.

**Comment by corneliusludmann** [comment]
Indeed, it takes the server version as fallback whenthe Theia version is not set:

https://github.com/gitpod-io/gitpod/blob/0bf71f1ed37b7b0a1702ba34908b43e2c2fbe15e/components/server/src/env.ts#L35-L38
