### ISSUE TITLE
Add projects empty state illustration for dark theme

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4680]
### Problem to solve

We're on the way on adding Teams & Projects in this release and while we've already added an empty state for the Projects list, we are not using an illustration optimized for the dark theme. 😇 

| Emtpy State Illustration (Light) | Emtpy State Illustration (Dark) |
|-|-|
| <img width="1440" alt="Screenshot 2021-07-01 at 8 06 29 PM" src="https://user-images.githubusercontent.com/120486/124163066-e0bfec80-daa7-11eb-9b69-a031e73c5fae.png"> | <img width="1440" alt="Screenshot 2021-07-01 at 8 06 19 PM" src="https://user-images.githubusercontent.com/120486/124163068-e289b000-daa7-11eb-9afd-17d9d052fabb.png"> |

### Designs

| Projects Empty State |
|-|
| <img width="1440" alt="AFTER" src="https://user-images.githubusercontent.com/120486/127133935-0510ec86-a59e-4e21-ad38-b0204060d136.png"> |

See [design specs](https://www.figma.com/file/qUoiEmhah5FSKym1yAHmar/Add-projects-empty-state-illustration-for-dark-theme-4680?node-id=1%3A22).

**Comment by gtsiolis** [comment]
Added the design specs for the illustration in the issue description. 🏓

**Comment by jankeromnes** [comment]
Taking this on as a drive-by fix 😁 🚀
