### ISSUE TITLE
not able to view my code in a window

### ISSUE THREAD

**Issue by tomfinnegan** [gitpod-io/gitpod#4681]
### Bug description

when working in Gitpod I cant run my code in the preview window to see what it looks like 

### Steps to reproduce

no

### Expected behavior

no

### Example repository

no

### Anything else?

no

**Comment by JanKoehnlein** [comment]
Can you elaborate on what kind of application you develop, which languages and frameworks, and if it is a web app, why `gp open $(gp url <port>)` doesn't work for you?

**Comment by tomfinnegan** [comment]
html CSS JavaScript the window to preview the web page only shows code no images

**Comment by akosyakov** [comment]
please see discussions here: https://github.com/gitpod-io/gitpod/issues/3831

VS Code does not support live preview of files by default, but you can use additional extension like Five Server to fix it.
