### ISSUE TITLE
Option to allow custom titles on browser tab

### ISSUE THREAD

**Issue by eric-naguras** [gitpod-io/gitpod#4684]
Hey Gitpod,
Great project, really love it.

I always have multiple repositories open, like a backend and one or more front ends.
On average I work at 4 (sub) projects at the same time.

Currently, Gitpod shows the opened file name in the tab title of the browser.
That does not work for me.
I would like to be able to set my own tab title in the .gitpod.yml file.
This would save me a lot of time by not having to constantly switch between tabs to find the correct project.

Below are some examples for different projects/repositories

browser:
 - tab-title: API

or 

browser:
 - tab-title: ADMIN

or

browser:
 - tab-title: Web

**Comment by akosyakov** [comment]
Have you tried to use browser extensions like https://chrome.google.com/webstore/detail/tab-modifier/hcbgadmbdkiilgpifjgcakjehmafcjai?hl=en#:~:text=Quick%20rename%20can%20be%20done,click%20on%20%22Rename%20Tab%22. ?

**Comment by eric-naguras** [comment]
> Have you tried to use browser extensions like https://chrome.google.com/webstore/detail/tab-modifier/hcbgadmbdkiilgpifjgcakjehmafcjai?hl=en#:~:text=Quick%20rename%20can%20be%20done,click%20on%20%22Rename%20Tab%22. ?

Hmmm, a bit complicated.
It would be so easy to add this (as a choice) to gitpod.
