### ISSUE TITLE
Disable GitHub Student Pack expiration emails in Sendgrid

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#4689]
**Context:** 
We want to move all emails from Sendgrid to Chargebee or customer.io to keep a better overview of the emails we're sending, to have a consistent layout/theme, and to avoid unnecessary service costs. 

All account-related emails should be sent by Chargebee. 

I drafted two emails that will be sent 5 and 1 day before the free trial of the GitHub Student Pack expires. The emails will only be sent to users who applied a GitHub coupon code and they won't affect anyone else. See settings [here](https://gitpod.chargebee.com/notifications/subscription_expiry_and_cancellations/view)

In order to activate these emails, we need to disable the current Sendgrid emails first. 
Affected template IDs: `d-8ab33d6d323e4bc18fc7d4f698fe732a`  `d-b86511ef38234ed4a1f6b7f197821bdf`

**Comment by ChristinFrohne** [comment]
@jankeromnes maybe you could help as you also disabled the welcome emails in Sendgrid?

[Here](https://gitpod.slack.com/archives/C01LDA27WJC/p1625132038212700) is some more context

**Comment by ChristinFrohne** [comment]
Please ping me once this is live so I can enable the email in Chargebee. Thanks!

**Comment by csweichel** [comment]
Are we still using sendgrid? I reckon we're still deploying `postman`, but do not support making changes here anymore. We should move all of this stuff to `customer.io` and disable sendgrid entirely.

@geropl please correct me if I misunderstood something here.

**Comment by csweichel** [comment]
I'll remove it from the inbox for now, because it's not clear how to act on this.

@jankeromnes once you're back online, please have a look at this issue and decide how to continue. Possible ways forward:
1. there are actions we need to take. If so, please re-add to the inbox.
2. it's a matter of disabling postman altogether, then we should do that in prod.

**Comment by ChristinFrohne** [comment]
Right now we are still sending the GitHub Student Pack emails and emails related to the private trial from Sendgrid. 

Once the future of trials is decided, we can update and move these emails as well.

**Comment by jankeromnes** [comment]
Aha, it seems that all remaining postman campaigns have been moved here: https://github.com/gitpod-com/postman/tree/main/src/notifications/campaigns

**Comment by jankeromnes** [comment]
Given that Postman has been totally inactive since July 1st (as per our SendGrid data), we would like to sunset & remove https://github.com/gitpod-com/postman from any deployment.

@meysholdt / @wulfthimm what is the process for doing this?

**Comment by JanKoehnlein** [comment]
I moved this to platform as it seems the action is on them

**Comment by meysholdt** [comment]
We removed postman from all deployments in this commit. https://github.com/gitpod-io/ops/commit/efc03e0c62e580ebd078892ce5bd111cbd61278f. 

Removing from Platform inbox and assigning back to @ChristinFrohne to see if there is more to do here.

**Comment by ChristinFrohne** [comment]
Thanks! The emails are already in Chargebee. But there is a sending issue due to our subscription limitations, but that's another issue. So I would close this one.
