### ISSUE TITLE
Fix learn more link style on projects empty state page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4690]
### Problem to solve

The projects empty state page contains a Learn more link that does not use the style for _default_ and _hover_ state accordign to to the intial specs.

| Workspaces | Projects |
|-|-|
| <img width="1440" alt="Screenshot 2021-07-02 at 11 32 17 AM" src="https://user-images.githubusercontent.com/120486/124246290-764f9080-db29-11eb-9a9e-6ee2f36167fc.png"> | <img width="1440" alt="Screenshot 2021-07-02 at 11 32 23 AM" src="https://user-images.githubusercontent.com/120486/124246297-78195400-db29-11eb-934c-1023f1053058.png"> |

### Proposal

This can use the same style attributes as the _Learn more_ link in the workspaces empty state page.

https://github.com/gitpod-io/gitpod/blob/99ec2a5c5733c7ddd04b7854896d6c6be05b3399/components/dashboard/src/workspaces/Workspaces.tsx#L138

**Comment by Cahllagerfeld** [comment]
I'd try to do this, if its not done yet (:

**Comment by Cahllagerfeld** [comment]
I think thats already done
```css
/*index.css*/
 a.gp-link {
        @apply underline underline-thickness-thin underline-offset-small text-gray-400 dark:text-gray-600 hover:text-gray-500 dark:hover:text-gray-500;
    }
```
```tsx
{/*Projects.tsx*/}
<a className="gp-link" href="https://www.gitpod.io/docs/prebuilds/">Learn more about Prebuilds</a>
```
```tsx
{/*Workspaces.tsx*/}
<a className="gp-link" href="https://www.gitpod.io/docs/getting-started/">Learn more</a>
```

**Comment by gtsiolis** [comment]
You're right @Cahllagerfeld! This was updated in the scope of https://github.com/gitpod-io/gitpod/pull/5112. Thanks for noticing. Let's close this. 📕
