### ISSUE TITLE
Something goes wrong when clicking on the Gitpod button from Safari

### ISSUE THREAD

**Issue by leodido** [gitpod-io/gitpod#4701]
### Bug description

When clicking on the ready-to-code button
<img width="169" alt="image" src="https://user-images.githubusercontent.com/120051/124454986-5d451a80-dd89-11eb-85e4-06e313bc60ca.png">
from the [Gitpod's README](https://github.com/gitpod-io/gitpod#readme), the user is getting redirected to the usual flow.

But soon afterward, Gitpod notifies that something went wrong with the following error page:
![image](https://user-images.githubusercontent.com/120051/124455123-7ea60680-dd89-11eb-8ff9-a198eb7b02db.png)

### Steps to reproduce

1. Use Safari (tested on version 14.1.1)
2. Go to the repo's README
3. Click on the ready-to-code button
4. Follow the experience
5. Notice the error page

### Expected behavior

It should just work.

Or, in case Safari isn't supported, users should be made clearly aware of it.

## Proposed solutions

1. Document that Safari is not supported
2. Detect Safari and stop the flow alerting the user to switch browser

I propose to implement 1 or 2. Both would be probably better, IMHO.

I'm not proposing "3. Support Safari" because @geropl told me it does NOT properly support Web Standards on which Gitpod builds a few of its features upon.

### Example repository

https://github.com/gitpod-io/gitpod

**Comment by gtsiolis** [comment]
See also https://github.com/gitpod-io/gitpod/issues/688.

**Comment by svenefftinge** [comment]
We definitely want to support safari as it is the standard browser on ipads.
What "Web Standards" are you referring to @geropl ?

**Comment by geropl** [comment]
I don't recall clearly, but we struggled with:
 - websocket connections (IMO some connection limit per host)
 - CORS handling differed from Chrome/Firefox
 - very early one we had trouble with cookie handling. E.g. dashboard cookies would not be sent with workspace requests.
 - more edge cases like:
   - handling of redirects on non-200 responses
   - referrer headers not sent at all (?)
Of course this might be outdated by now. A general sentiment of the experience is that often Safari would interpret standards differently/only implemented a subset of Chrome/Firefox. If that still holds for our case would be indeed interesting.

**Comment by csweichel** [comment]
This particular case is probably caused by the missing referrer headers (the button in the Gitpod readme uses `from-referrer`).

**Comment by AlexTugarev** [comment]
To be more precise, Safari removes the path from the URI if "do not track me" is enabled. The is sent, this is why we get to the starting frame.
Suggestion on the solution would be to extend the check for header: if no path included, treat it as if the header is not present.
