### ISSUE TITLE
ws-us10 high load averages and network timeouts

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#4709]
### Bug description

Looks like the issues around high load averages and network timeouts have returned to at least ws-us10. Seeing load averages of >30, all CPUs at 100%, and when doing `yarn install` or `yarn upgrade`, getting a lot of network timeouts.

### Steps to reproduce

Open a workspace

**Comment by ghuntley** [comment]
👋 @smacintyre, thanks for your report.  We are investigating and https://www.gitpodstatus.com/ has been updated.

**Comment by ghuntley** [comment]
We have identified terms of service violations and have suspended the users who were abusing Gitpod. See https://www.gitpodstatus.com/incidents/t4vf6ljrcly9

**Comment by smacintyre** [comment]
@ghuntley Thank you! ❤️
