### ISSUE TITLE
Would you add  libGL.so.1 to the container?

### ISSUE THREAD

**Issue by hidehiro98** [gitpod-io/gitpod#471]
https://github.com/alifelab/alife_book_src/blob/master/chap02/gray_scott.py

When I run this code, I cannot use this because I cannot install `libGL.so.1`.
If possible, would you add this library?

**Comment by hidehiro98** [comment]
FYI
https://packages.ubuntu.com/search?suite=xenial&arch=any&mode=filename&searchon=contents&keywords=libGL.so.1

**Comment by jankeromnes** [comment]
Hi @hidehiro98, thank you for reaching out!

You can easily install new dependencies by adding configuration files like these to your repository:

`.gitpod.yml`:

```yaml
image:
  file: .gitpod.dockerfile
```

`.gitpod.dockerfile`:

```Dockerfile
FROM gitpod/workspace-full-vnc

RUN sudo apt-get update \
 && sudo apt-get install -y libgl1 \
 && rm -rf /var/lib/apt/lists/*
```

(Note: I assume that you'll need a graphical environment, so I picked the base image `gitpod/workspace-full-vnc`, which includes a X11 server and a web-based VNC client that allows you to view and interact with graphical applications).

See also:
- This (more complicated) [dockerfile example](https://github.com/jankeromnes/servo/blob/master/Dockerfile), which allows building and running the Servo web browser in Gitpod
- Gitpod's [Docker image docs](https://www.gitpod.io/docs/42_Config_Docker/)
- This [blog post](https://www.gitpod.io/blog/docker-in-gitpod/) which goes through adding a dockerfile to your project

**Comment by geropl** [comment]
Hi @hidehiro98 ,

you can add it to the [.gitpod.yml](https://www.gitpod.io/docs/41_Config_Gitpod_File/) for your project yourself: Just add a `.gitpod.yml` with these contents:
```
image:
  file: .gitpod.dockerfile
```
and a `.gitpod.dockerfile` like so:
```
FROM gitpod/workspace-full-vnc

RUN apt-get update && apt-get install -yq \
        libgl1-mesa-glx \
&& apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/*
```
After you pushed the change, just re-open your project in a Gitpod and it should be there!

**Comment by hidehiro98** [comment]
Wow, thank you very much both @jankeromnes @geropl, I'll try this later!

**Comment by hidehiro98** [comment]
@jankeromnes @geropl, it worked! Thank you so much.
