### ISSUE TITLE
Problems accessing gitpod website/workspaces. "Websocket connections are blocked"

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#4714]
### Bug description

Having issues accessing Gitpod using Chrome.
Earlier today, I demoed Gitpod to someone in Europe, he had issues opening workspaces and opening Gitpod website (not the www). A couple of hours later, I see a similar issue (I am in USA).

Trying to open a workspace in Gitpod -
![image](https://user-images.githubusercontent.com/22901/124625743-110ede80-de4c-11eb-95ba-25d53e2ff14d.png)

Gitpod Dashboard -
![image](https://user-images.githubusercontent.com/22901/124626276-85498200-de4c-11eb-8627-c64ab5017a24.png)

### Steps to reproduce

I am not sure how to reproduce. I never saw this issue until today.

**Comment by meysholdt** [comment]
Hi!

thx for bringing this up. We're debugging this atm. What Chrome version are using?

**Comment by corneliusludmann** [comment]
Sorry for the inconvenience. What we know so far that usually restarting the browser mitigates the problem. Often it also works again by itself a short time later.

**Comment by corneliusludmann** [comment]
We added this to our status page: https://www.gitpodstatus.com/incidents/shqmz0dl01mr

**Comment by shaal** [comment]
I am using Edge Chromium Version 91.0.864.53, on macOS Big Sur (11.4)

The person from Europe is using Chrome Version 91.0.4472.114, on macOS Big Sur (11.4)

**Comment by akosyakov** [comment]
It seems to a regression in stable Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1226856&q=Sec-WebSocket-Key&can=2

**Comment by JohannesVlr** [comment]
@akosyakov We're also seeing this issue. Have you identified any workarounds yet? At the moment it seems that Firefox is a temporary workaround.

**Comment by ArthurSens** [comment]
> @akosyakov We're also seeing this issue. Have you identified any workarounds yet? At the moment it seems that Firefox is a temporary workaround.

Hi @JohannesVlr, 
So far we've been able to workaround by using firefox or by restarting chrome completely. Firefox is more reliable though

**Comment by ArthurSens** [comment]
After hours of sweat 😅 , we've identified a regression on chromium that is causing this issue. We're implementing and deploying a workaround for the bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1226856#c12

**Comment by ArthurSens** [comment]
The fix is on production! 

Please let us know if you still have problems

**Comment by shaal** [comment]
Thank you, now it works for me :)
