### ISSUE TITLE
[server] Add analytics API 

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#4728]
In order to send events from the dashboard and other places (vs code, local companion app, etc.) to our analytics end-point, the server should expose an API. I think it would be easiest to add a `trackEvent` method to the websocket protocol.

**Comment by csweichel** [comment]
We already have the [AnalyticsWriter API](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/src/util/analytics.ts) in gitpod-protocol. We could implement the AnalyticsWriter interface on the gitpod-server API. Downside is that we ~bloat~ extend that API further. Upside: we get authentication along for the ride and don't have to expose the segment write key/config.

**Comment by svenefftinge** [comment]
> we get authentication along for the ride and don't have to expose the segment write key/config.

Yes, I think adding it as a message to gitpod-service is easy and preferable also because it centralizes the analytics strategy (and its config).
