### ISSUE TITLE
Can't edit new build configuration in Preferences view

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#473]
**Describe the bug**

I can't edit a new build configuration I just created in the Preferences view.

<img width="1552" alt="Screenshot 2019-04-11 at 11 59 07" src="https://user-images.githubusercontent.com/599268/55948647-461e2d80-5c51-11e9-92dd-c6512dc01040.png">

**To Reproduce**

1. Open a C++ project in Gitpod, e.g. https://gitpod.io/#https://github.com/Shadouw/CPPToyProblems
2. `F1` > `Change Build Configuration` > `Create` "Build"
3. Try to edit the `Workspace` config in the `Preferences` editor
4. Keypresses don't seem to modify the file, but the `Preferences` tab gets into an "unsaved" state

**Expected behavior**

The new configuration file should be editable.

Closing the `Preferences` editor, and doing `gp open .theia/settings.json` opens a normal editor where the file can be edited.

Then, returning to `Preferences` also allows editing the Build config. Not sure what went wrong the first time.

**Comment by AlexTugarev** [comment]
> Keypresses don't seem to modify the file, but the Preferences tab gets into an "unsaved" state

Ouch! it's even worse, `User` settings are modified instead.
