### ISSUE TITLE
[server] Misleading log in `additional-content-prefix-parser.ts`

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#4733]
This error log is misleading. It is logged when the prefix is **NOT** found in the context URL:

https://github.com/gitpod-io/gitpod/blob/66539b0f4b1cc0be717d7bb10f18da225b844e90/components/server/src/workspace/additional-content-prefix-context-parser.ts#L30-L30

**Comment by corneliusludmann** [comment]
@svenefftinge Is there a reason you added the log message? Thinking about removing this. If you would like to have it for some reason I would move it as debug log to the right place instead.

**Comment by svenefftinge** [comment]
It is wrong. I wanted to get a log, if the context is an additional content context. But it's not really important so can also just be removed
