### ISSUE TITLE
Elm support

### ISSUE THREAD

**Issue by baalhiverne** [gitpod-io/gitpod#474]
Would be nice to have Elm support too😃 
VS code extension [here](https://github.com/Krzysztof-Cieslak/vscode-elm)

**Comment by svenefftinge** [comment]
You can follow progress in https://github.com/gitpod-io/gitpod/issues/433

**Comment by JesterOrNot** [comment]
I can get started on a dockerfile here is the repo
https://github.com/JesterOrNot/Gitpod-Elm

**Comment by svenefftinge** [comment]
I don't think a ready to use dockerfile is needed. I'd rather see a Julia section in [the docs](https://www.gitpod.io/docs/languages_and_frameworks/) that explains how to set up a dev environment for Julia and use it.

**Comment by JesterOrNot** [comment]
Alright

**Comment by JesterOrNot** [comment]
So should we get a spot in the docs ready?

**Comment by svenefftinge** [comment]
Yes, feel kick this off with a PR. I'm sthinking about something similar and on the same level as the Java guide: https://www.gitpod.io/docs/java_in_gitpod/
I.e. 
 - describe how to setup a dev environment for elm
 - describe how to use the IDE with the ELM extension
 - provide a slick example
