### ISSUE TITLE
[proxy] Produce access logs only for non-200 requests

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#4740]
Thereby cleaning up the proxy logs and making them more useful.

**Comment by csweichel** [comment]
I'm not convinced that Caddy can do this out of the box. I found nothing in the docs our sources that would indicate conditional logging.

**Comment by leodido** [comment]
Probably there's a tricky way to do it with Caddy (need to double-check on its version, tho).

Setting the `level` version of the `log` config to `warn` would avoid `200`s being logged.

https://caddyserver.com/docs/caddyfile/directives/log

**Comment by aledbf** [comment]
I think we should not use the default logger and instead write a small plugin [like this one](https://github.com/harshavardhana/caddylogger/blob/master/caddylogger.go) and just set the fields we need.
Basically, trim [this file](https://github.com/caddyserver/caddy/blob/master/logging.go#L589) and define a new directive, like `gitpod.log`

**Comment by leodido** [comment]
> this file

This ^^^ would be the correct **way to go**. I agree.

Just to clarify: I defined my attempt as a trick for this exact reason :)
