### ISSUE TITLE
[server] Fix subscription-based default timeouts

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#4760]
Just surprisingly stumbled over the parallel workspace limit to learn that there were a couple of workspaces running for more than 45 minutes. I'm pretty sure I haven't accessed at least one of them.

Can someone please verify that started workspace where the browser tab idles in the background, actually to time out?

**Comment by svenefftinge** [comment]
Update: after an hour (I'm on the professional open-source plan) one of the workspaces timed out.
So maybe it is just that the prof open-source account has 1h timeouts (unlike shown in the UI)?

**Comment by csweichel** [comment]
Turns out the default timeouts broke during the migration away from gitpod-com: https://github.com/gitpod-io/gitpod/blob/e8762f258e8b81d0a8da0b8062e7352722948e6c/components/server/ee/src/user/user-service.ts#L28-L28

right now, every user gets a default timeout of 1h.

**Comment by csweichel** [comment]
When fixing this, we must do this in a way that doesn't break self-hosted
