### ISSUE TITLE
[devx] Decrease size of workspace on gitpod-io/gitpod

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#4763]
Original Slack thread: https://gitpod.slack.com/archives/C01KGM9AW4W/p1625820943461200

Problem: Currently workspaces are around 25GB of size, from originally 2-3GB. This slows down "stop" and "restart" of a workspace.

This seems to be cause by the QEMU image that every workspaces contains ([link](https://github.com/gitpod-io/gitpod/blob/ccb09c9c4d1366763de364e80668d92e3d62ad2b/components/ee/agent-smith/scripts/prepare-bpf-dev-environment.sh)).
We should try to use a image of dynamic size as described in [this thread](https://askubuntu.com/questions/1298291/how-to-create-dynamic-disks-qcow2-as-it-happens-with-vdi).

**Comment by AlexTugarev** [comment]
This is the case, unfortunately.

**Comment by geropl** [comment]
@AlexTugarev Are you sure you did not hit a an old prebuild? Especially since we use incremental prebuilds this could easily be the case.

**Comment by geropl** [comment]
Let's close for now and re-try in a couple of days/Monday.
