### ISSUE TITLE
Gitpod Local Companion doesn't write SSH config file on Windows

### ISSUE THREAD

**Issue by jmcelreavey** [gitpod-io/gitpod#4768]
### Bug description

Attempting to run with windows executable for Gitpod Local Companion results in an error message:

time="2021-07-10T20:23:05+01:00" level=error msg="cannot write ssh config file" error="open /tmp/gitpod_ssh_config: The system cannot find the path specified." path=/tmp/gitpod_ssh_config

### Steps to reproduce

run `gitpod-local-companion-windows.exe` and see the above mentioned error message

### Expected behavior

Should successfully create the SSH Config so I can SSH into the workspaces :) 

### Anything else?

Keep up the good work!

**Comment by akosyakov** [comment]
It is hardcoded here: https://github.com/gitpod-io/gitpod/blob/bc1e14d34d9589be7d6641738ca6488242af1b35/components/local-app/main.go#L82

Golang has an utility function [ioutil.TempFile](https://golang.org/pkg/io/ioutil/#TempFile). Someone can try to use it on windows platform to create a file. It would be good to print the path on startup then.
