### ISSUE TITLE
have 'gp domain' command

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#477]
it should work just like the `gp url` command, but the result should not include the `https://` and trailing `/`.

This is often needed to configure a server for the domain it's running on.

Example [workaround1](https://github.com/jankeromnes/PeerTube/blob/b43637f22c2510eaa7ab2d2f709f8b1872d1b0d9/.gitpod.yml): 
`$(gp url 3000 | cut -d/ -f3)` (CC @jankeromnes ).

Example [workaround2](https://github.com/gitpod-io/apache-example/blob/master/apache.env.sh):
`$(gp url 8080 | sed -e s/https:\\/\\/// | sed -e s/\\///)`

**Comment by svenefftinge** [comment]
We should deprecate the `gp url` command in favor of this.
