### ISSUE TITLE
[server] `testEmptyProject` of the GitLab context parser fails

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#4773]
The `testEmptyProject` of the GitLab context parser fails:

https://github.com/gitpod-io/gitpod/blob/bc6c9f72c0d0a5a1085e5d37d67c01f1a5af4c31/components/server/src/gitlab/gitlab-context-parser.spec.ts#L531-L548

```
1) TestGitlabContextParser
       testEmptyProject:
     AssertionError: expected { Object (isFile, path, ...) } to have deep property 'ref'
      at TestGitlabContextParser.<anonymous> (src/gitlab/gitlab-context-parser.spec.ts:549:36)
      at Generator.next (<anonymous>)
      at fulfilled (src/gitlab/gitlab-context-parser.spec.ts:19:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The actual result is:
```json
{
  "isFile": false,
  "path": "",
  "title": "gp-test-group/gp-test-empty-project - main",
  "revision": "",
  "repository": {
    "host": "gitlab.com",
    "name": "gp-test-empty-project",
    "owner": "gp-test-group",
    "cloneUrl": "https://gitlab.com/gp-test-group/gp-test-empty-project.git",
    "defaultBranch": "main",
    "private": false
  }
}
```

Opening the empty workspace actually works, though. It's just the test that fails and needs to be fixed.

**Comment by AlexTugarev** [comment]
@corneliusludmann, from reading the expectation and the error message, to me it seems like the test could be adjusted. with no bike-shedding in mind, `{ ref: undefined, [more] }` is not a typical response, but `{ [more] }`. 

perhaps there was a change in the GitLab library we use and this response is fixed now. 

> Opening the empty workspace actually works, though. It's just the test that fails and needs to be fixed.

👍🏻

**Comment by roboquat** [comment]
@corneliusludmann: GitHub didn't allow me to assign the following users: me.

Note that only [gitpod-io members](https://github.com/orgs/gitpod-io/people), repo collaborators and people who have commented on this issue/PR can be assigned. Additionally, issues/PRs can only have 10 assignees at the same time.
For more information please see [the contributor guide](https://git.k8s.io/community/contributors/guide/first-contribution.md#issue-assignment-in-github)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4773#issuecomment-882464521):

>/assign me


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
