### ISSUE TITLE
Community Templates Integration?

### ISSUE THREAD

**Issue by mitchazj** [gitpod-io/gitpod#4776]
Heyo! I'm looking for ways to contribute code back to open-source and was wondering - would you guys be interested if I started work towards & implemented community templates for Gitpod?

Eg, something like this in the workspaces UI:
![image](https://user-images.githubusercontent.com/15032956/125381719-be976a00-e3d7-11eb-837e-b7bef3cdc1c9.png)

## Reasoning:
1. Allows for a beautiful combination of community contribution, showcasing, and discoverability for new users.
2. Empowers people with strong domain knowledge to write and share templates specific to their domain knowledge, raising value for everyone involved.

## Some initial thoughts (very formative, none of this strictly held):
- Would allow people to place a tag on their public repo, and then apply to have it listed as a template (should be automatic in most cases)
- Some kind of community reporting feature and block for repeat bad actors (eg, submitting malicious code templates) would be needed
- Some use cases: course authors sharing template code from parts of their stack, hobbyist devs automating their workflow

## Stack
- Not completely familiar with your stack but I could maybe use a supabase DB to build this? Keeps it super simple, but I'm also 90% sure you'd recommend a different approach.
- Very open to suggestions (and really just floating the idea atm). It's a big project but I'd love to start a repo + pull request and contribute towards building it if you're keen.

## Misc
A possible MVP (and likely simpler to implement first) would be:
- a tab called "Your Templates" allowing you to pin strictly your own repos as templates for your own usage

This would solve 80% of my UX issue at the moment, but would be a selfish solution and wouldn't multiply.

Also, not sure if this aligns with your mission / direction, but allowing people to sell premium templates through a marketplace could become an avenue to encourage high-quality usage and also support indie developers (but this is 10 steps ahead of this initial idea)

**Comment by svenefftinge** [comment]
That's an excellent idea! We could maybe just use a public query on GitHub, where we are searching for certain tags and then weight them by stars or so. Also suggesting users to star the repo if they liked the template.

**Comment by mitchazj** [comment]
Sounds good! I'll give it a try when I get a spare moment
