### ISSUE TITLE
make context URLs work for www.gitpod.io (note the `www`)

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#478]
see https://news.ycombinator.com/item?id=19589743

**Comment by cokron** [comment]
hey guys, the same happened to me. I came googled gitpod.io and came to www.gitpod.io. I saw the instruction to  replace the part after the domain name with "/#" followed by my github URL.
This does not work and there is no error message displayed. 
While we worked this out eventually, we all agreed that this is a bug that you should catch to help new users who are not aware of the difference between www.gitpod.io and gitpod.io.
So I suggest reopening this issue and fixing what to us appears to be a UI bug.
Thank you guys and gals.

**Comment by jankeromnes** [comment]
See also https://github.com/gitpod-io/website/issues/43

**Comment by svenefftinge** [comment]
fixed it.
