### ISSUE TITLE
Local VS Code support

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4780]
We are going to make use of VS Code Remote SSH extension which provision VS Code Server in Gitpod workspaces. Additional we will provide local Gitpod extension which enables port tunneling via the local app and integrates other Gitpod services like tasks, notifications and so on.

**Comment by akosyakov** [comment]
Not yet, we are working on good startup flow for it.

**Comment by purkhusid** [comment]
When can we expect this to be deployed?

**Comment by axonasif** [comment]
> When can we expect this to be deployed?

I'm with you too 😝, but eh, we just need to be patient.

**Comment by akosyakov** [comment]
> When can we expect this to be deployed?

Deployed soon, but we won't make it available to everybody immediately. If all go well in 1-2 week for everybody.

> I'm with you too 😝, but eh, we just need to be patient.

🙏

**Comment by tnir** [comment]
3 weeks passed, any updates? @akosyakov

**Comment by akosyakov** [comment]
> 3 weeks passed, any updates? @akosyakov

We think that major issues were addressed and targeting to release preview version on Tuesday.

**Comment by axonasif** [comment]
> > 3 weeks passed, any updates? @akosyakov
> 
> We think that major issues were addressed and targeting to release preview version on Tuesday.

I'm excited to test it out!

**Comment by tnir** [comment]
Great!
