### ISSUE TITLE
Basic cli support for the local companion

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4781]
Right now the user has to start a new terminal and the app just auto tunnel everything. We want to run a single daemon in background and allow CLI communicate with it via grpcweb.

See https://www.notion.so/gitpod/Local-Companion-App-599983916fa24443b956f925128870ce#ef754cfc1c3940c890f16ac006cbea60 for initial commands.

**Comment by roboquat** [comment]
@akosyakov: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4781#issuecomment-919805986):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
Unfortunately after team discussions we realised that we don't have capacity for upstream issues and have to focus more on bug fixes and robust deployments. I removed it from the scheduled for now.

**Comment by loujaybee** [comment]
> Is there a way to always open in my local vs code? Currently I either go to GitHub and open Gitpod using the browser extension or I open it directly from Gitpod. But both those options opens in the browser first and then I have click open in VS Code. Is there a setting or a work flow that let's me open directly in vs code?

Noting an additional comment/feedback from the community [[1](https://discord.com/channels/816244985187008514/839379835662368768/907931354472251403)] about enabling a better flow for opening VSCode desktop.

**Comment by loujaybee** [comment]
This issue is also related to: https://github.com/gitpod-io/gitpod/issues/6602

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/gitpod/issues/7185
