### ISSUE TITLE
Cannot install packages in virtualenv

### ISSUE THREAD

**Issue by iksaif** [gitpod-io/gitpod#479]
```
$ virtualenv -p python3 venv
Running virtualenv with interpreter /home/gitpod/.pyenv/shims/python3
Using base prefix '/home/gitpod/.pyenv/versions/3.7.2'
New python executable in /workspace/flacon/venv/bin/python3
Also creating executable in /workspace/flacon/venv/bin/python
Installing setuptools, pip, wheel...
done.
$ source venv/bin/activate
$ pip install black
Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

**Comment by AlexTugarev** [comment]
@iksaif, please use `export PIP_USER=no` together with `venv`.

It's enabled by default in order to install everything below `/workspace` directory which is persisted, cf. `PYTHONUSERBASE=/workspace/.pip-modules`

Persistence is not a problem for local `venv`s.

**Comment by iksaif** [comment]
Ok thanks, will try that :)

**Comment by alesanchezr** [comment]
Why not using pipenv? working good for me.

**Comment by AlexTugarev** [comment]
@iksaif did it work for you eventually?

@alesanchezr that's an option as well (cf. https://github.com/gitpod-io/gitpod/issues/525)

**Comment by iksaif** [comment]
Yes it worked in the end for me,thanks !

**Comment by marcospsviana** [comment]
easy_install working for me
