### ISSUE TITLE
Update notification preferences in dashboard

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#4793]
### Scope

- [x] Account notifications should be mandatory (see below for wording). It’d only lead to confusion if a user disables it. Other services don’t even list that option in their notification settings
- [x] Add another checkbox (see below for wording)
- [x] Set all notification preferences to active by default for new users
- [x] Reflect the Changelog and Product tips notifications in our data bank
- [x] Make sure the unsubscribe logic forwarding the user preferences to customer.io is aligned

 
### **Context regarding active emails by default:**
First I wanted to set only account notifications and Changelog to active by default, as according to the GDPR "Requests for consent must be **clearly distinguishable from the other matters** and presented in **clear and plain language**. [[1](https://gdpr.eu/email-encryption/)]. Still, Johannes was voting of setting all emails to active by default, so I did some more research. 

**Orbit:** doesn't ask for permission. It sets a weekly summary email to active by default although their [privacy policy](https://orbit.love/privacy-policy) says "We will only provide you with marketing-related information after you have, where legally required to do so, opted in to receive those communications."
**GitLab** is asking for permission in the onboarding flow
**Zapier** is not asking for permission and sets most emails 6/7 to active by default

Conclusion: let's set all emails to active by default for new users until we get complaints or an email spam rate >0,1% (currently 0,01%)

 

### **Wording:**
Account Notifications [required] (Receive essential emails about changes to your account)
Changelog (Be the first to learn about new features and overall product improvements)
Product tips & inspiration (receive emails on how to supercharge your Developer Experience)

 @pawlean If you have another suggestion for the wording of your emails, let me know

[Internal discussion](https://gitpod.slack.com/archives/C01KGM9BUNS/p1625815432140700)

**Comment by ChristinFrohne** [comment]
Note: Onboarding emails will be treated separately and don’t belong to a checkbox.  Users can unsubscribe directly from the mail for that specific campaign. Unsubscribing from the onboarding campaign, won't influence the email settings

**Comment by ChristinFrohne** [comment]
relating issue #4761

**Comment by csweichel** [comment]
I'm afraid the issue as it stands right now is not actionable - or at least I don't understand it :) 

Are the things listed in _Scope_ basically the ToDo items to complete this issue?

**Comment by ChristinFrohne** [comment]
>Are the things listed in Scope basically the ToDo items to complete this issue?

Yes, it's mainly about adding a third option for the emails settings. But when doing so we should make sure that 
1) this option is set to active by default as well 
2) the messaging in the code aligns with one in the dashboard (no more marketing emails) 
3) the unsubscribe logic is aligned, so that the new information is forwarded to customer.io as well

Regarding  "Account notifications should be mandatory", it could also be its own issue, but I thought it could be address with this together

**Comment by laushinka** [comment]
This is the mockup that @ChristinFrohne provided:
<img width="721" alt="Bildschirmfoto 2021-08-05 um 15 10 23" src="https://user-images.githubusercontent.com/8015191/128361513-9b538195-823e-42a9-a164-b00c27ea9b53.png">

**Comment by laushinka** [comment]
@ChristinFrohne A couple of things: 
1. I have updated the Scope above. Please take a look and confirm that they are as you expect.
2. Now that we have a "Save preferences" button, what behavior do you expect once the button is clicked?

**Comment by ChristinFrohne** [comment]
@laushinka I feel that there has been a misunderstanding between #4761 and this issue. 
The mockup above is meant to be shown when someone uses the unsubscribe link in emails and it refers to #4761 

The screen for the dashboard notification preferences already exists, see [https://gitpod.io/notifications](https://gitpod.io/notifications). 
The scope for this issue would be

- [ ] make account notification mandatory in /notifications

- [ ] add a third checkbox to /notifications

- [ ] adjust the wording for all checkboxes (changelog & product tips)

- [ ]  Set all notification preferences to active by default for new users

- [ ] Reflect the Changelog and Product tips notifications in our data bank

- [ ] make sure changes in /notification are picked up by Segment and forwarded to customer.io



For #4761, I was thinking to create a new screen (e.g. /unsubscribe), that can be accessed without logging in and which is automatically synchronized with /notification. [Here](https://gitpod.slack.com/archives/C01KGM9ETU6/p1628235932015300?thread_ts=1628169492.011100&cid=C01KGM9ETU6) are examples of how other services deal with the unsubscribe logic. Please let me know if the current approach (#3) is technically too difficult to implement. 

Does that make sense now? :)

**Comment by laushinka** [comment]
@ChristinFrohne Ah you're right I got them mixed together! Sorry about that, I'll fix the Scope.

**Comment by ChristinFrohne** [comment]
Johannes suggested another wording for the third checkbox
>Developer Experience & Product Tips
Bring back joy and speed to your workflows

**Comment by ChristinFrohne** [comment]
Jakob suggested adding another checkbox for the onboarding flow emails to the notification preferences. Previously we thought to keep the unsubscribe logic of the onboarding emails at customer.io to keep the effort of the new changes as low as possible. We now reconsidered that and decided to implement another checkbox, as the implementation isn't that complex and because there are several benefits coming with it:
- it can be confusing if a user unsubscribes to all emails in the dashboard but still receives onboarding emails 
- the behavior of the unsubscribe link in emails isn't consistent (sometimes it refers to customer.io and other times to the dashboard)
- it's a nicer way of handling data, all information would be stored in the same place


Could you add another option as suggested in the mock below @laushinka ? :) 
The checkbox should be enabled for all users. Enabling this checkbox should not have any consequences for the user. They will only receive the onboarding emails right after user creation. 
<img width="725" alt="Bildschirmfoto 2021-08-23 um 15 27 40" src="https://user-images.githubusercontent.com/46345125/130455956-03b99af8-0f0f-4d50-8151-a005954efe51.png">


cc @jakobhero

**Comment by ChristinFrohne** [comment]
The last comment will be addressed in issue #5327
