### ISSUE TITLE
Workspaces based on a snapshot executes "init" steps

### ISSUE THREAD

**Issue by sgurlt** [gitpod-io/gitpod#4794]
### Bug description

I am currently facing the issue that a new workspace that is based on a shared snapshot is executing "init" steps. Based on the documentation this should not happen:

https://www.gitpod.io/docs/config-start-tasks#start-a-snapshot

### Steps to reproduce

Here is my example `.gitpod.yml` file which i causing the issue.

```
---
tasks:
  - before: >
      echo "before"
    init: >
      echo "init"
    command: >
      echo "command"
    name: Gitpod - Snapshot bug
```

### Expected behavior

The steps within init should not be executed when a workspace is based on an snapshot.

### Example repository

Repo: https://github.com/sgurlt/gitpod-snapshot-bug

Example Snaphot: https://gitpod.io#snapshot/0137ff6a-b55a-4cef-85cb-e4a03afcad36

**Comment by sgurlt** [comment]
Is the bug reproducible on your end?

**Comment by pawlean** [comment]
> Is the bug reproducible on your end?

Hey @sgurlt! It is a known issue and we're looking to get a fix in soon! Thank you for raising this issue. Hang tight :)

**Comment by sgurlt** [comment]
> > Is the bug reproducible on your end?
> 
> Hey @sgurlt! It is a known issue and we're looking to get a fix in soon! Thank you for raising this issue. Hang tight :)

Got it, thank you very much :)

**Comment by sgurlt** [comment]
@pawlean Could you frame me a timeline when this is going to be fixed?
