### ISSUE TITLE
Show complete logs when displaying a running prebuild

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#4799]
When I start a workspace for which a prebuild is currently running, I'd want to see the full logs in order to see how progressed it is and generally get a sense of progress.

**Comment by svenefftinge** [comment]
Would this be solved with https://github.com/gitpod-io/gitpod/pull/4439 ?

**Comment by geropl** [comment]
#4439 includes a couple of fixes, yes, but the general re-connect case should be fixed with `main.1100` already. Do you have a workspaceId so I can dig up and see what's wrong?

**Comment by svenefftinge** [comment]
I created a workspace on a freshly pushed branch and ended up with no output. Eventually there was some. Then I reloaded the page and again had a black/blank log widget. I'd have expected to see the pas logs. You should be able to reproduce it by starting a workspace on a freshly pushed branch on this repo and then reload sometimes.

**Comment by svenefftinge** [comment]
It works now. I guess I was just impatient.
