### ISSUE TITLE
Please include current Git branch in the Terminal prompt

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#48]
Current prompt:

    gitpod /workspace/definitely-gp $

Expected prompt:

    gitpod /workspace/definitely-gp (master) $

Since `__git_ps1` seems to be installed (by default alongside `git`), this could be achieved like so:

    PS1='\[\033[01;32m\]\u\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)") $ '

([source](https://github.com/JanitorTechnology/dockerfiles/blob/9ee71d49efce9f5a7d875c9a82d9f7e9e54d9c19/ubuntu-dev/ubuntu-dev.dockerfile#L125) but with `\u \w` instead of `\u@\h:\w` to imitate the current gitpod prompt)

**Comment by svenefftinge** [comment]
We don't do that on purpose, because it does not update, if I change the branch outside the terminal.
The branch information is shown in the status bar on the bottom left.
