### ISSUE TITLE
c/c++ debugging is broken

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4805]
### Bug description

reported https://community.gitpod.io/t/c-c-debug-configuration/4148 It is a regression.

@geropl Reported that Rust debugging is affected as well.

### Steps to reproduce

See above.

**Comment by csweichel** [comment]
@akosyakov how would one go about looking into this? And who could do this?

**Comment by akosyakov** [comment]
@csweichel It seems to be related to some container security, an error is:
```
No symbol table is loaded. Use the "file" command.
Running executable
warning: Error disabling address space randomization: Operation not permitted
Hello world!
[Inferior 1 (process 1725) exited normally]
```

Maybe @fntlnz or @leodido can look into it?

**Comment by fntlnz** [comment]
C/C++ debugging is working as intended. Let's analyze the gdb output we have line by line.

```
No symbol table is loaded. Use the "file" command.
```

User did not compile the program with debugging symbols (this is why it **seems** that debugging is not working)


```
Running executable
```
It is indeed working!


```
warning: Error disabling address space randomization: Operation not permitted
```

This is normal and debugging can still work despite this, we don't allow disabling ASLR in Gitpod as it will be dangerous.
 

```
Hello world!
```
This is the proof that gdb worked


```
[Inferior 1 (process 1725) exited normally]
```
Same as above.



Let's now see what the user should do to actually debug that program.

In `CMakeLists.txt` add a `-g` flag to the `CMAKE_CXX_FLAGS`. This can also be done optionally with a cmake option on wether this is release or debug software but this will work.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0a83c4c..54ce044 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -15,7 +15,7 @@ file(GLOB SRC_FILES
 
 # Enable C++11 features on gcc/clang
 if("${CMAKE_CXX_COMPILER_ID}" MATCHES "(GNU|Clang)")
-    set(CMAKE_CXX_FLAGS "-std=c++11")
+    set(CMAKE_CXX_FLAGS "-std=c++11 -g")
 endif()
 
 add_executable(${problem} ${SRC_FILES})
```

Now

```
cd build
cmake ..
make
```


After that, just use gdb.

From the command line:


```
gitpod /workspace/HelloGitPod/build $ gdb ./HelloGitPod 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./HelloGitPod...
(gdb) 
```


Now to show the symbols.


```
(gdb) l
1       #include <iostream>
2
3       using namespace std;
4
5       int main()
6       {
7           cout << "Hello world!" << endl;
8           char *pC = 0;
9           return 0;
10      }
```


Breakpoint on line 7

```
(gdb) b 7
Breakpoint 1 at 0x11b5: file /workspace/HelloGitPod/main.cpp, line 7.
```


Run (it will break on line 7)

```
(gdb) r
Starting program: /workspace/HelloGitPod/build/HelloGitPod 
warning: Error disabling address space randomization: Operation not permitted

Breakpoint 1, main () at /workspace/HelloGitPod/main.cpp:7
7           cout << "Hello world!" << endl;
```


Continue, it will finish and exit

```
(gdb) c
Continuing.
Hello world!
[Inferior 1 (process 2540) exited normally]
```

**Comment by fntlnz** [comment]
To disable the warning write this line in `~/.gdbinit`

```
set disable-randomization off
```

**Comment by davegi** [comment]
Thanks. This all works great and is a good overview of how gdb/compiler interact WRT symbols, but given that this is _your_ sample, shouldn't this be explained in or near the **Debugging** section on this ([C++ in Gitpod](https://www.gitpod.io/docs/languages/cpp)) page?
Also, this doesn't help at all at getting the IDE Debugger working in Chrome.

**Comment by akosyakov** [comment]
> Also, this doesn't help at all at getting the IDE Debugger working in Chrome (on Windows).

Do you mean that it does not work from launch configuration created from VS Code? Which extension do you use? @fntlnz did you try to debug using VS Code debug view somehow or only from terminal?

**Comment by fntlnz** [comment]
@akosyakov  I didn't try any extension, I just made sure that gdb worked from the command line. Since extensions use gdbserver I thought this was enough.

Looks like [Native Debug](https://open-vsx.org/extension/webfreak/debug) is the only extension in open-vsx that can do that.

**Comment by fntlnz** [comment]
How to use it is described in the gitpod docs https://www.gitpod.io/docs/languages/cpp#debugging - so, compiling with `-g` and using that extension should work for you. Can you confirm @davegi ?

**Comment by davegi** [comment]
I'm sorry, I can't confirm. I've been playing w/this for a couple of hours, but I am not well-versed in the Linux toolchain, nor in how to get it to interact w/VS Code. What I am after is the ability to use your IDE to build and debug a multi-file (.c/.h) _hello world_ application. It shouldn't be this hard😎.
Starting w/your HelloGitPod sample:
- I can build w/cmake/make but how is this done w/the IDE? Are CMakeLists.txt changes (like adding `-g` which I did) integrated into the build or do they have to be run from the command line w/cmake? Etc., Etc.
- I can debug w/gdb from the terminal and can get the IDE debugger to launch w/the configuration below but can't set BPs.
``` xml
    "configurations": [
        {
            "name": "Debug",
            "type": "gdb",
            "request": "launch",
            "target": "build/HelloGitPod",
            "cwd": "${workspaceRoot}",
            "valuesFormatting": "parseText"
        }
    ]

```
Given that one of GitPod's great attractions is that it supports a fairly robust VS Code based dev. env., a step-by-step guide on how to build/debug _hello world_ in C would be really helpful. Thanks.

**Comment by leodido** [comment]
Hello @davegi,

regarding you not being able to set breakpoints, could you please double-check whether you have this setting on or not?

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/120051/126978580-66a5cbf3-1089-4bc8-bc4a-b62dc279cdb8.png">

**Comment by akosyakov** [comment]
Should we reopen till clarified?

**Comment by mfouesneau** [comment]
yes please

**Comment by akosyakov** [comment]
@mfouesneau I think it is better if you open a new issue by now and explain what you are trying to achieve in which project and what does not work. This issue is quite old.
