### ISSUE TITLE
A user (with privileges) should be able to chose a workspace cluster explicitly

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#4809]
Use cases: If there are multiple pluggable workspace clusters...
* with admission constraints and you want to choose one
* or the cluster you want to start a workspace in has a low "score" and you don't want to start 10 workspace to have at least on end up on the right clusters. In fact, some colleagues could not use this strategy in the past because they did not have an "unleashed" plan and ran into the workspace limit too early.

Proposal:
* support an `&cluster=eu12` argument in the context urls, similar to how we do it to trigger prebuilds manually and pass ENV vars.
* since we only use this for testing this argument should only be usable by people who have the permission to do so, e.g. the `new-workspace-cluster` permission. We don't want to give users the ability to override our loadbalancing/failover/cluster-cycling strategies.

Context: @geropl brought this up in today's all-hands.

**Comment by csweichel** [comment]
Other simple solution: extend the admission constraints to explicitly name users, i.e. introduce a `user=` admission constraint.

Pro: does not require plumbing cluster choice to workspace context/config.
Downside: still not as flexible as passing it in as env var.

> or the cluster you want to start a workspace in has a low "score"

This case I don't understand yet. Why can't we just raise the score while testing the cluster?

**Comment by meysholdt** [comment]
> Why can't we just raise the score while testing the cluster?

it pins you to single cluster :( Sometimes it's nice to work with multiple ones: First start your "dev" workspace on a "stable" cluster and then start a test workspace on the k3s-cluster, another one on EKS, and another one on GKE just to make the comparison.

With that being said, it feels like even with a ration of 10000:50 I still end up on the "50" cluster 1/4 of the time, so I ended up starting multiple workspace in the past.

Another nice use-case for having the cluster-name in the URL: We can share such URLs in Slack "here, try this cluster".

**Comment by csweichel** [comment]
> With that being said, it feels like even with a ration of 10000:50 I still end up on the "50" cluster 1/4 of the time, so I ended up starting multiple workspace in the past.

That sounds like a separate bug we should look into

> Another nice use-case for having the cluster-name in the URL: We can share such URLs in Slack "here, try this cluster".

That's a great use-case indeed

**Comment by csweichel** [comment]
In conversation with @meysholdt we've decided to skip this feature for now. Removing from groundwork.
