### ISSUE TITLE
Revise setting workspace stop time: Don't let workspace stopping time eat up users' hours

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#4818]
Currently, the time during the workspace stopping phase decreases the users' hours. When the workspace is stuck in stopping, that could eat up users' hours completely. Reconsider setting the stopping time that calculates the hours as soon as the stopping phase begins.

/cc @svenefftinge @csweichel

**Comment by geropl** [comment]
Currently we're account for the time between ["startedTime" and "stoppedTime"](https://github.com/gitpod-io/gitpod/blob/e8762f258e8b81d0a8da0b8062e7352722948e6c/components/ee/payment-endpoint/src/accounting/account-service-impl.ts#L264-L264). We could think about adding a column "stoppingTime" and use that instead.

**Comment by csweichel** [comment]
Why not set the `stoppedTime` the first the workspace enters `stopping`?
