### ISSUE TITLE
Caret Placement

### ISSUE THREAD

**Issue by GDJason12** [gitpod-io/gitpod#482]
**Describe the bug**

When I delete a mistake from the text, the caret misplaces and it bugs the entire IDE.
**To Reproduce**

1. Place the caret in the correct pos.
**Expected behavior**

Caret is placed in the correct order, doesn't make bugs, and the caret is after the letter.

**Comment by akosyakov** [comment]
@GDJason12 hi, thank you for the issue

Do you mean something like that https://github.com/theia-ide/theia/issues/3796?

**Comment by svenefftinge** [comment]
I think it is a duplicate of #339 
(Are you on a Chromebook)
