### ISSUE TITLE
Workspace don't stop

### ISSUE THREAD

**Issue by CarlosAraki** [gitpod-io/gitpod#4824]
### Bug description

I try to stop the https://fuchsia-raven-dsgspfgf.ws-us10.gitpod.io/ but nothing happens

### Steps to reproduce

go to git pod workspace and try to make workspace stop

**Comment by CarlosAraki** [comment]
I'm dump LOL

**Comment by mikenikles** [comment]
Haha that was funny :). I was looking into it and saw that the workspace was stopped. When I came back here to report, I saw your latest comment.

Glad that's resolved 👍
