### ISSUE TITLE
Cannot open new workspaces from Github: Connection got disposed.

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#4826]
### Bug description

Trying to open a new workspace on a Github repo:

The tab stays at "Preparing workspace" for about 10 minutes:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/361689/125703597-76666091-2bb5-4146-9b63-9a747d900b03.png">

Then displays: Connection got disposed.
<img width="353" alt="image" src="https://user-images.githubusercontent.com/361689/125703640-a5f849fe-b208-4d37-bf15-a4d82ae7829a.png">

It's my start of day. This is happening on every repo I try.

### Steps to reproduce

Try to open a new workspace from any Github repo

**Comment by smacintyre** [comment]
Interestingly, I tried hitting refresh on one of my "Connection got disposed" tabs, and it brought up a workspace. But no prebuilds had executed. Still having the issues with opening a new workspace from github.

**Comment by jelaniwoods** [comment]
I'm also still seeing this. Refreshing doesn't seem to help and I get the message

> Error: 4 DEADLINE_EXCEEDED: Deadline exceeded

**Comment by smacintyre** [comment]
@jelaniwoods Yeah, refreshing isn't at all useful. The resulting workspace can't open ports and is using the wrong image with no prebuilds. It's completely busted.

**Comment by mikenikles** [comment]
Hey 👋, I'm closing this in favour of #4825 to streamline communication.
