### ISSUE TITLE
Ports stuck on detecting when trying to run preview server

### ISSUE THREAD

**Issue by geeklady2** [gitpod-io/gitpod#4827]
### Bug description

Rails/Sinatra app used for educational course is experiencing issues for all of our students.
A version of the code can be found here

Shotgun is used to start the server but the port gets stuck on detecting.

![GitPodHung](https://user-images.githubusercontent.com/2140309/125706619-86b5e87e-e6fe-4756-befc-9f5c661cc727.png)

### Steps to reproduce

Use this version of the code
https://github.com/geeklady2/LHLCompleteFinstagram

type  bin/serve
in the terminal and wait

### Expected behavior

For the port to be opened and the ability to preview or open the web app

**Comment by mikenikles** [comment]
Hi, thanks for letting us know. It is likely related to #4825. I will close this issue so I can streamline communication over in #4825 and keep everyone updated.
