### ISSUE TITLE
provide better feedback if .gitpod.yml cannot be parsed

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4828]
Right now we ignore it completely and does not tell the user the reason.

See https://github.com/gitpod-io/gitpod/issues/4825#issuecomment-880332288 and https://community.gitpod.io/t/gitpod-yml-not-running-init-command-tasks-and-new-images-also-not-building/4098

**Comment by svenefftinge** [comment]
I think we should stop the workspace creation with an error message, showing the problem instead of ignoring it. And then have an action that allows users to start a workspace ignoring the gitpod.yml.
