### ISSUE TITLE
[theia] command to create a gitpod link for the current context

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#483]
As a user I want to add nice links and badges to README file for example. Right now i had to copy it from other repos, it would be nice to have a command to generate them.

**Comment by jankeromnes** [comment]
Agreed! My current (completely broken) workflow is:

1. Click top-right avatar
2. "Share Workspace Snapshot"
3. Copy the Markdown code, but replace snapshot URL with what you want

(I'm aware that this creates a snapshot that's never used, but... it's convenient 😅)

**Comment by svenefftinge** [comment]
https://github.com/gitpod-io/gitpod/issues/1023
