### ISSUE TITLE
Testing our automation

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#4835]
This tests roboquat

**Comment by roboquat** [comment]
@csweichel: Only scheduler can add this label. Those are:


<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4835#issuecomment-880687889):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
