### ISSUE TITLE
Stopped workspace 'ivory-meerkat-jtlqx106' not showing unsaved changes

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4839]
### Bug description

Today in Gitpod (in production) I had some unsaved work-in-progress in a workspace (ID `ivory-meerkat-jtlqx106`), then I had a few meetings, and when I returned to my workspace, it had (predictably) timed out.

However, it told me that there were no unsaved changes:

<img width="1440" alt="Screenshot 2021-07-15 at 17 04 24" src="https://user-images.githubusercontent.com/599268/125811579-70184acb-343a-4a23-8079-0d4e934f0b81.png">

Now, I knew this couldn't be true, and indeed when I restarted my workspace, it showed my unsaved changes again:

<img width="1440" alt="Screenshot 2021-07-15 at 17 06 56" src="https://user-images.githubusercontent.com/599268/125811674-29760732-2783-4b0e-bd14-23fc600c424a.png">

### Steps to reproduce

1. Make some unsaved changes in a workspace
2. Wait for the workspace tab to time out (e.g. by doing something else for 30+ minutes)

### Expected behavior

The "stopped workspace" tab should show that there are some unsaved changes in your workspace.

**Comment by gtsiolis** [comment]
@jankeromnes do you remember if you checked out a new branch and made the changes there? Noticed this recently but I could be wrong.

**Comment by nisarhassan12** [comment]
I had this issue on my workspace where I didn't check out a new branch.
