### ISSUE TITLE
Workspace is suddenly completely empty when opening

### ISSUE THREAD

**Issue by annakovesdi** [gitpod-io/gitpod#4845]
### Bug description

My workspace that was working normally yesterday, is suddenly completely empty. The files (that are usually on the left) are not visible (the whole section is gone) and I cannot continue to work. 
When trying to view the built work in the browser it works and is there - but I can not continue to work on it. Also if I create a new file with the terminal I cannot see it or work on it (normally it would open the new file up and you could work on it without having to click it in the filetree)

<img width="1654" alt="Screenshot 2021-07-16 at 09 48 33" src="https://user-images.githubusercontent.com/67696002/125912325-85c4ce6e-ec0e-4e5e-a749-08af1790b3d2.png">

Here a screenshot for what I am seeing. I am working with a hard deadline and really should continue... I really hope I don't have to start a new workspace and install and configure everything again.

This did happen more often but I just started a new workspace from github every time, but now because of the limited time that I have I really hope this can be solved faster on your side?

### Steps to reproduce

If i close the workspace and stop it, and open it again it is the same. 

### Expected behavior

The filetree should be visible and i should be able to open files to work on them

**Comment by annakovesdi** [comment]
I started a new workspace. However, If there is a better solution for the next time it happens I would be glad to know it!

**Comment by akosyakov** [comment]
@annakovesdi Do you still use Theia? Please switch to VS Code: https://gitpod.io/preferences Theia is going to be removed next month.

**Comment by annakovesdi** [comment]
Yes, because I am so new at coding and this project is my graduation that needs to be finished way too soon: I wanted to switch after I finished so no time would be wasted figuring out how it is different from Theia (that I am used to). But if I understand correctly you are suggesting to switch so it won't happen again :) thanks, I really did not think about this, stupidly! I am sure this issue is not relevant.
