### ISSUE TITLE
Gitpod should checkout Git LFS files in workspace

### ISSUE THREAD

**Issue by sgarner** [gitpod-io/gitpod#4852]
Gitpod does not natively support repositories using Git LFS (Large File Support). It would be great if this could be addressed.

It is possible to work around this in some situations by manually installing git-lfs into the container and running `git lfs pull` in the workspace as an `init` task (in `.gitpod.yml`).

However that has limitations. In particular, LFS files are not available during the Docker image build, so if you need to `COPY` a large file into the image from your Dockerfile, it won't work.

I haven't looked yet at how this works in Gitpod, but I would imagine that enabling LFS during the git checkout phase would be a relatively simple enhancement. Can this be considered?

**Comment by ghuntley** [comment]
> Gitpod does not natively support repositories using Git LFS (Large File Support). It would be great if this could be addressed.

👍 

> It is possible to work around this in some situations by manually installing git-lfs into the container and running git lfs pull in the workspace as an init task (in .gitpod.yml).

👋 I use git-lfs over at https://github.com/ghuntley/ghuntley with Gitpod and this is what I do.

> enabling LFS during the git checkout phase would be a relatively simple enhancement

Breaking down this to the best of my knowledge.

1. installation of the git-lfs binaries into the base image https://github.com/gitpod-io/workspace-images/blob/d57c5f4b47a2df0bad344ff6c6a0209bd862a352/base/Dockerfile#L36
2. configuration of appropriate bash hooks (example: https://github.com/ghuntley/ghuntley/tree/trunk/git-hooks)
3. Appropriate changes that add `git lfs pull` to https://github.com/gitpod-io/gitpod/blob/035fa4e1f107d2d73e250e8a853e1923aa9b313b/components/content-service/pkg/git/git.go#L262
4. ... other changes ...

> LFS files are not available during the Docker image build

It would be good to understand the use cases where large files need to be pulled into the docker image, as the smaller the docker image the faster workspace starts are :)

**Comment by ghuntley** [comment]
> * installation of the git-lfs binaries into the base image https://github.com/gitpod-io/workspace-images/blob/d57c5f4b47a2df0bad344ff6c6a0209bd862a352/base/Dockerfile#L36

Opened pull-request over at https://github.com/gitpod-io/gitpod/issues/4852 to add this in.

**Comment by sgarner** [comment]
Thanks for looking at this @ghuntley ❤️ 

> It would be good to understand the use cases where large files need to be pulled into the docker image, as the smaller the docker image the faster workspace starts are :)

My use case is to preload the mysql database in gitpod workspaces with data from an SQL file. I have a 100MB gzipped dump committed to the repository using LFS.

I wanted to `COPY` the dump in my Dockerfile and then `RUN` a mysql command to restore it inside the container during the image build. But this was not possible because at the time of the image build the dump file is only a pointer due to lack of LFS support.

I also tried restoring the data from a Gitpod `init` task. This works, but the downside is workspace prebuild/startup becomes very slow because restoring the database takes 5-10 minutes each time. The benefit of doing this inside the Docker image build is it would be cached and not need to be re-done on every commit.

For now my workaround has been to create a separate Docker image from `mysql/mysql-server` where I preload the data and which I build outside of Gitpod. Then in Gitpod workspaces I pull that image and run it as a separate (Docker in Docker) container. This achieves good performance - the downsides of this approach are added complexity to build the second image, and the need for all teammates to configure a token in their Gitpod environment to be able to pull the image from a private repository.

**Comment by sagor999** [comment]
This should be fixed now via: https://github.com/gitpod-io/gitpod/pull/8119
I am closing this issue now, but if git-lfs still not working, please comment\re-open.
