### ISSUE TITLE
Workspace Timed out while Active

### ISSUE THREAD

**Issue by Kaushik-Kalesh** [gitpod-io/gitpod#4853]
### Bug description

While I was working on a workspace, a message popped out on the screen saying "Timed out" or something, and that the workspace was to be stopped. Now, when I tried to re-open the workspace, it loaded forever saying "Allocating resources...", and after a while this error message popped up "Error: 4 DEADLINE_EXCEEDED: Deadline exceeded". I don't know what happened, it couldn't have close due to inactivity (because it wasn't).

P.S - I am not a paid/premium user (I have 38 hours left this month)

### Steps to reproduce

Use a workspace for more than 2 hours (but keep the workspace active, i.e, do stuff)

**Comment by pawlean** [comment]
Hey there @Kaushik-Kalesh! I've not been able to replicate this issue on my end, and I followed your steps to reproduce with no luck. I was wondering if it's a one-off. Are you still getting this issue?
