### ISSUE TITLE
Gitpod not starting on Firefox latest version.

### ISSUE THREAD

**Issue by AstroOrbis** [gitpod-io/gitpod#4854]
### Bug description

When I try opening any repo/workspace on Gitpod, it gets stuck on this message:
```
Checking

Preparing workspace...
```

and 

```
Preparing

Allocating resources...
```

### Steps to reproduce

1. Use latest version of FireFox with no extensions installed.
2. Try starting any repo or workspace using Gitpod

### Expected behavior

The workspace should open.

**Comment by shaal** [comment]
@AstroOrbis unfortunately, I couldn't replicate the issues you had reported.
I tested it with Firefox 91.0b3 developer edition, no extensions installed.
I was able to open these repos with no errors - 
https://gitpod.io/#https://github.com/shaal/DrupalPod (custom docker image)
and
https://gitpod.io/#https://github.com/shaal/fast (default docker image)

Can you please add more details, of specific Firefox version, specific repos you tried, and perhaps any messages that might be displayed in Console of the browser's devtools?

**Comment by AstroOrbis** [comment]
After a little bit of reinstalliing and fixing MacOS settings, it works again! Thanks for trying though!
