### ISSUE TITLE
Applying SSL Certificates

### ISSUE THREAD

**Issue by daronhudson** [gitpod-io/gitpod#4859]
### Bug description

After generating let's encrypt certificates for the self-hosted version of gitpod and applying them to the necessary secret and upgrading the installation, the web portion still shows as using the traefik default certificate.

I'm not sure if it's something I did wrong or if it's just not applying them, but the secret contains my certificates.

I'm getting this error from my ws-proxy pod:

`{"ca":"/ws-manager-client-tls-certs/ca.crt","cert":"/ws-manager-client-tls-certs/tls.crt","key":"/ws-manager-client-tls-certs/tls.key","level":"debug","message":"using TLS config to connect ws-manager","serviceContext":{"service":"ws-proxy","version":""},"severity":"DEBUG","time":"2021-07-19T01:24:59Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"error while connecting to ws-manager:\n    github.com/gitpod-io/gitpod/ws-proxy/pkg/proxy.(*RemoteWorkspaceInfoProvider).Run\n        github.com/gitpod-io/gitpod/ws-proxy/pkg/proxy/infoprovider.go:167\n  - context deadline exceeded","level":"error","message":"cannot start workspace info provider - will retry in 10 seconds","serviceContext":{"service":"ws-proxy","version":""},"severity":"ERROR","time":"2021-07-19T01:25:09Z"}
{"ca":"/ws-manager-client-tls-certs/ca.crt","cert":"/ws-manager-client-tls-certs/tls.crt","key":"/ws-manager-client-tls-certs/tls.key","level":"debug","message":"using TLS config to connect ws-manager","serviceContext":{"service":"ws-proxy","version":""},"severity":"DEBUG","time":"2021-07-19T01:25:19Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"error while connecting to ws-manager:\n    github.com/gitpod-io/gitpod/ws-proxy/pkg/proxy.(*RemoteWorkspaceInfoProvider).Run\n        github.com/gitpod-io/gitpod/ws-proxy/pkg/proxy/infoprovider.go:167\n  - context deadline exceeded","level":"error","message":"cannot start workspace info provider - will retry in 10 seconds","serviceContext":{"service":"ws-proxy","version":""},"severity":"ERROR","time":"2021-07-19T01:25:29Z"}
{"ca":"/ws-manager-client-tls-certs/ca.crt","cert":"/ws-manager-client-tls-certs/tls.crt","key":"/ws-manager-client-tls-certs/tls.key","level":"debug","message":"using TLS config to connect ws-manager","serviceContext":{"service":"ws-proxy","version":""},"severity":"DEBUG","time":"2021-07-19T01:25:39Z"}
{"level":"info","message":"workspace info provider started","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-07-19T01:25:39Z"}
{"level":"info","message":"started proxying on :8080","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-07-19T01:25:39Z"}
{"addr":":60095","level":"info","message":"started Prometheus metrics server","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-07-19T01:25:39Z"}
{"level":"info","message":"🚪 ws-proxy is up and running","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-07-19T01:25:39Z"}
{"addr":":60060","level":"info","message":"serving pprof service","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-07-19T01:25:39Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"error while starting streaming status updates from ws-manager:\n    github.com/gitpod-io/gitpod/ws-proxy/pkg/proxy.(*RemoteWorkspaceInfoProvider).listen.func1\n        github.com/gitpod-io/gitpod/ws-proxy/pkg/proxy/infoprovider.go:236\n  - rpc error: code = Unavailable desc = transport is closing","level":"warning","message":"error while listening for workspace status updates, reconnecting after timeout","serviceContext":{"service":"ws-proxy","version":""},"severity":"WARNING","time":"2021-07-19T01:28:17Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"context deadline exceeded","level":"warning","message":"error while connecting to ws-manager, reconnecting after timeout...","serviceContext":{"service":"ws-proxy","version":""},"severity":"WARNING","time":"2021-07-19T01:28:30Z"}`

### Steps to reproduce

- Install gitpod
- configure DNS settings for it
- generate certificates and move them to the necessary location
- create the gitpod https secret
- upgrade installation
- open website url

### Expected behavior

The gitpod installation should now be using the generated let's encrypt certificates.

**Comment by daronhudson** [comment]
So after some tinkering I managed to fix the proxy. 

It still uses the traefik default cert though.

Now when I try to connect to the url all I get is connection refused

**Comment by daronhudson** [comment]
Seems that port 443 is no longer opening.

**Comment by ghuntley** [comment]
> generate certificates and move them to the necessary location

How were the certificates generated (ie provide CLI commands used if available)?

The error `cert_authority_invalid` typically is as a result of using self-signed certificates (not supported atm), expired certificates (unlikely but check!) or with trust roots (using your own CA is not supported atm)

**Comment by daronhudson** [comment]
I generated the certificates using letsencrypt through certbot exactly as the documentation was showing.
Upon inspecting the certificate that certbot provides, I noticed that it only covers *.ws.domain.com and not the additional 2 domains that certbot verifies.

**Comment by daronhudson** [comment]
Hello? Is there anyone that can help with this? I've been dealing with this for over a week now and I've gone through multiple installations with no success so far. This is getting very frustrating.

**Comment by ghuntley** [comment]
Can you please generate a [support bundle](https://github.com/gitpod-io/support-bundle) and then send it over to the address listed in the README?

Specific things to check:

- contents of `secrets/https-certificates` contains your letsencrypt certificates and that they are valid certificates.

From https://www.gitpod.io/docs/self-hosted/latest/configuration/ingress

- the k8 secret has been generated: `kubectl create secret generic https-certificates --from-file=secrets/https-certificates`
- the k8 secret has been applied: `helm upgrade --install -f values.custom.yaml gitpod gitpod.io/gitpod --version=0.10.0`

**Comment by yusufali94** [comment]
however it does not work unless you explicitly have a "tls.crt" file, see here https://github.com/gitpod-io/gitpod/issues/5378
