### ISSUE TITLE
gp-cli: gp rebuild

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#4861]
An idea for useful helper for the GP cli application.

```
Command line interface for Gitpod

Usage:
  gp [command]

Available Commands:
  rebuild         Restarts the current workspace and rebuilds it (ie inner loop for debugging prebuilds and gitpod.yml)
```

**Comment by akosyakov** [comment]
@loujaybee is it a dup of https://github.com/gitpod-io/gitpod/issues/6818#issuecomment-975633422?

**Comment by svenefftinge** [comment]
tracked in https://github.com/gitpod-io/gitpod/issues/7671
