### ISSUE TITLE
[priority] Browser window and port serving not working

### ISSUE THREAD

**Issue by pranavr2003** [gitpod-io/gitpod#4869]
### Bug description

I've created a simple HTML file to test, and tried to run it using `webbrowser.open()` to open it on a browser. It opens on the side, but says `Not found`, for some reason. Clicking on the 'Open in browser' at the top right corner does nothing at all too.

Then I tried to open it on a port using Flask (which worked about 3 days ago) with a simple route and tried to render the template. The side browser didn't work (it didn't about 3 days too), so I did this:
![image](https://user-images.githubusercontent.com/56883253/126173373-8d0e16dd-3ded-4f05-8f8e-cc327aa98282.png)

and instead of displaying the content (which worked 3 days ago), it says this:
![image](https://user-images.githubusercontent.com/56883253/126173509-877f2812-5617-4f42-b1c1-9575f31a43ac.png)

The side browser window has never worked before (which is quite crucial for my work), and now port serving doesn't seem to do too.

### Steps to reproduce

All this was done on a newly created public repo with no files existing

Pretty self-explanatory

![image](https://user-images.githubusercontent.com/56883253/126172657-ec787c17-df5e-4ab3-9a0e-5e2c30b1fdd1.png)

Trying with Flask:
![image](https://user-images.githubusercontent.com/56883253/126176763-5a5376fe-86f6-41bb-bde6-7790efb4658f.png)

For the Flask test, create a `templates/` directory and put `test.html` into it.

### Expected behavior

The content displays.

### Anything else?

While the experience with Python has been great, GitPod lacks a lot when it comes to web dev. I'm not a web dev, but I regularly work with those tools along with Python, and it hasn't been smooth when it comes to that. It works just fine when I'm using just Python, without anything else (the backend-only experience has been great).

It would be great if these specific issues were rectified as a priority, since frontend devs need a smooth experience, which is really lagging right now. As a user, I would love to run my HTML file with CSS and/or JS linked with a click of a button, but I'm having to go to Python and use `webbrowser` everytime I need to do it, which still doesn't work. The bigger hassle is to create a Python file, install Flask, and serve it on a port just to run a simple application, which is too much to do just to run a simple file with just 6 lines of code. That too isn't working now.

I feel like GitPod is not very warming to frontend dev (which must obviously not be out of intention), since there's no direct way to run the file independent of another file created just for it. Personally, I've completely shifted my workbase to GitPod with a time unlimited plan, but this is not a good experience when it comes to working on the frotnend.

One thing I would suggest to make it a tad smoother is to add an 'Open with Browser' option on right-clicking HTML/JS files to directly open it on a browser. The Side Browser needs to work too, so does the top right corner 'Open in browser' button.

**Comment by pranavr2003** [comment]
Port serving works now, but the Side browser and the open in browser button at the top right still doesn't.

**Comment by csweichel** [comment]
Thank you for your feedback, especially regarding frontend-development. The port access takes a short while to become available at time times. We are looking into steps of making that quicker and more reliable, but don't have an ETA for those improvements yet.

Regarding the side browser: AFAIK it behaves like a browser running on your machine, hence I wouldn't expect `test.html` to just work. Your approach of serving that file from a web server is a good one. While we don't have explicit support for doing so, there are a number of means available already that make this easier than rolling a flask app, e.g.
```bash
# using Python 3
python -m http.server 8000

# independent of any language
curl lama.sh | sh
```

Indeed, Gitpod is not intentionally unwarming to frontend devs, thus thank you again for your feedback :)

**Comment by pranavr2003** [comment]
@csweichel Thanks for the clarification. But can you explain 'behaves like a browser running on your machine'? From what I understand it doesn't run on any ports and if it doesn't, why would `test.html` not work? Which kind of stuff would then run on the Side Browser?

**Comment by akosyakov** [comment]
Please for 3rd party extensions like five server to preview local files, see discussions here also https://github.com/gitpod-io/gitpod/issues/3831

**Comment by pranavr2003** [comment]
JS isn't working on Five Server, for some reason.
However 
```
# using Python 3
python -m http.server 8000

# independent of any language
curl lama.sh | sh
```
is working, as expected. However can you please clarify how Side Browser works/what it works on, if not for opening regular HTML files? 

Thanks.

**Comment by akosyakov** [comment]
@pranavr2003 The preview is an iframe which loads something from given source. Since your file belong to remote workspace in Gitpod, they are not accessible via localhost and you have to expose them. Five Server should do it for you by starting a file server, lama does the same.

> JS isn't serving on Five Server (and Live Server too), for some reason.

Could you comment on #3831 and ping the author with steps to reproduce?
