### ISSUE TITLE
I sometimes get stuck forever in the 'Starting...' screen

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#487]
**Describe the bug**
Sometimes, in Firefox Nightly on Mac, I get stuck forever in the `Starting...` screen.

Even when my workspace has successfully started:

<img width="1552" alt="Screenshot 2019-04-15 at 12 49 37" src="https://user-images.githubusercontent.com/599268/56127408-6285d700-5f7d-11e9-94ac-ca68ab484ee0.png">

... I don't get forwarded (although the page seems to have gotten the message):

<img width="1552" alt="Screenshot 2019-04-15 at 12 49 27" src="https://user-images.githubusercontent.com/599268/56127363-46823580-5f7d-11e9-8016-30c10a94fe3b.png">

**To Reproduce**
1. Start a workspace
2. ... sometimes don't get forwarded? 😕 

**Expected behavior**
I should always get forwarded once the workspace has started.

**Comment by svenefftinge** [comment]
I have seen that, too.

**Comment by alesanchezr** [comment]
It happened to me yesterday with this repo: https://github.com/4GeeksAcademy/django-rest-hello

Using Chrome.

After a few attempts now it's loading fast as usual.

**Comment by geropl** [comment]
Thanks @alesanchezr for reporting. We have a PR which fixes this, will be deployed soon.

**Comment by jianboy** [comment]
me too.

![image](https://user-images.githubusercontent.com/11532015/141431071-e42317c1-f42b-4910-b89d-b03477f9e0d2.png)
