### ISSUE TITLE
Error: 4 DEADLINE_EXCEEDED Error launching existing workspace

### ISSUE THREAD

**Issue by cjensenius** [gitpod-io/gitpod#4872]
### Bug description

I am attempting to launch https://gitpod.io/start/#indigo-chickadee-cben01ge and am receiving the following error message:

Oh, no! Something went wrong!
Error: 4 DEADLINE_EXCEEDED: Deadline exceeded

### Steps to reproduce

Launch https://gitpod.io/start/#indigo-chickadee-cben01ge and wait

### Expected behavior

Normal launch of existing workspace

**Comment by cjensenius** [comment]
I received the same behavior from https://gitpod.io/start/#coral-mandrill-fbuviks4

**Comment by cjensenius** [comment]
Earlier I had been working in the https://gitpod.io/start/#indigo-chickadee-cben01ge workspace when it was forced into the shutting down state, I did not see an error message during that process. The DEADLINE_EXCEEDED message arrived after that event for any workspace

**Comment by cjensenius** [comment]
Attempting to launch a new workspace from the same private repo yields a different error:

Oh, no! Something went wrong!

Connection got disposed.

**Comment by cjensenius** [comment]
The issue has resolved for indigo-chickadee-cben01ge, checking new workspace launches

**Comment by cjensenius** [comment]
New workspace failed with same Connection got disposed. error. I've reported what seemed like the relevant information, please let me know if you need anything else.

**Comment by csweichel** [comment]
Thank you @cjensenius for the detailed report. We had a minor service outage yesterday (a system-critical service was evicted). We're looking into this.
