### ISSUE TITLE
[ws-manager] Leaks memory

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#4877]
### Bug description

ws-manager leaks memory in some circumstances (e.g. in `us11`).

![image](https://user-images.githubusercontent.com/3210701/126286806-a5db912a-8b3b-46e1-b3b8-50968126fe58.png)

We must find out what causes this leak and fix it.

This has adversely affected users: https://github.com/gitpod-io/gitpod/issues/4872

### Steps to reproduce

wait long enough

### Expected behavior

should not leak memory

**Comment by aledbf** [comment]
@csweichel this seems related to Jaeger (again)

![Screenshot from 2021-07-20 07-40-24](https://user-images.githubusercontent.com/161571/126317989-0ff01214-59c0-46c0-a9f4-24c4116bd68d.png)

**Comment by ghuntley** [comment]
See also https://community.gitpod.io/t/is-gitpod-down/4210/3 for affected users.

**Comment by csweichel** [comment]
hopefully fixed in https://github.com/gitpod-io/gitpod/pull/4883
