### ISSUE TITLE
accessing shared workspaces fails with startWorkspace failed

### ISSUE THREAD

**Issue by pretentious7** [gitpod-io/gitpod#4881]
### Bug description
Error applying to gitpod.io hosted service.

Attempting to access shared workspace from another user in team gives this error:

`Request startWorkspace failed with message: No workspace with id '<redacted>' found.`

### Steps to reproduce

- Start a new workspace with some github repo
- share workspace using gitpod overall menu or vscode plugin
- error appears on click for other user.

### Expected behavior

- Start a new workspace with some github repo
- share workspace using gitpod overall menu or vscode plugin
- Other user is able to access workspace

### Anything else?

First noticed 930AM EDT July 20, 2021

**Comment by corneliusludmann** [comment]
Hi @pretentious7,

Sorry for the inconvenience. Could you do me the favor and check if this still happens?

**Comment by corneliusludmann** [comment]
Also: In which region do you use Gitpod (rather EU cluster or US cluster)? In which region has the workspace been shared?

**Comment by pretentious7** [comment]
Seems to work now! was in the EU cluster.
