### ISSUE TITLE
Gitpod Self-Hosted shipped with agent-smith enabled

### ISSUE THREAD

**Issue by bmnave** [gitpod-io/gitpod#4885]
### Bug description

The agent-smith daemonset fails in deployment of Gitpod 0.10.0-alpha1 on a Self Hosted K8S install.  The log contains the following error:

`{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"program bpf_sys_getrlimit_setrlrimit_x: load program: invalid argument","level":"fatal","message":"error while loading and attaching bpf program","serviceContext":{"service":"agent-smith","version":""},"severity":"CRITICAL","time":"2021-07-20T19:28:01Z"}`

### Steps to reproduce

Deploy Self Hosted Gitpod 0.10.0-alpha1 via helm

### Expected behavior

Pods should start up normally

### Example repository

n/a

### Anything else?

I'm not sure if the error during workspace creation:

`Oh, no! Something went wrong!
cannot initialize workspace: cannot initialize workspace: content initializer failed`

is related to the agent-smith pods failing to spin up?

**Comment by IdealAppsCloud** [comment]
The v0.10.0 deployment also fails because there is no agent-smith 0.10.0 tag in the registry. What else? Haven't checked yet.
![Zrzut ekranu 2021-07-21 o 00 55 20](https://user-images.githubusercontent.com/56419191/126405806-07ee0477-b8e6-4ac7-90d4-8cb0cb67a5e6.png)

**Comment by bmnave** [comment]
> The v0.10.0 deployment also fails because there is no agent-smith 0.10.0 tag in the registry. What else? Haven't checked yet.
> ![Zrzut ekranu 2021-07-21 o 00 55 20](https://user-images.githubusercontent.com/56419191/126405806-07ee0477-b8e6-4ac7-90d4-8cb0cb67a5e6.png)

Yup. I noticed this as well which is why I’m still playing with the alpha1 release yesterday. 0.10.0 was only tagged today so I figured all of the release artifacts haven’t been pushed out yet. Comparing the alpha1 release against the final shows no changes. So they should be effectively the same once those images are pushed.

**Comment by corneliusludmann** [comment]
Thanks for reporting.

1. The tagging of the `0.10.0` images went wrong for some reason. I'm investigating this currently. However, nothing has changed between `0.10.0-alpha1` and `0.10.0`. Therefore, you can safely use these images.
2. @fntlnz: Could you have a look regarding the agent-smith problem? I'm not able to reproduce this in my k3s cluster.

**Comment by fntlnz** [comment]
Thanks for bringing this to my attention @corneliusludmann - IIRC Agent smith should not be deployed by default or even required in self hosted clusters -  @csweichel do I remember correctly?

**Comment by corneliusludmann** [comment]
Currently, it will be deployed for self-hosted as well.

https://github.com/gitpod-io/gitpod/blob/035fa4e1f107d2d73e250e8a853e1923aa9b313b/chart/values.yaml#L139-L144

One can set `disabled: true` here to disable agent-smith. Gitpod should work without as well. Probably this should the default for self-hosted?

**Comment by bmnave** [comment]
@corneliusludmann 

Confirmed that adding the following to my values.yaml file disables `agent-smith`:

```
components:
  agentSmith:
 disabled: true
```

Thanks!
