### ISSUE TITLE
Dart, Fluutter

### ISSUE THREAD

**Issue by otokomnet** [gitpod-io/gitpod#489]

**Comment by jankeromnes** [comment]
Hi @otokomnet, thank you for this feature request!

Please note, @sr229 already wrote Dockerfiles [for Dart](https://github.com/gitpod-io/workspace-images/blob/master/dart/Dockerfile) and [for Flutter](https://github.com/gitpod-io/workspace-images/blob/master/flutter/Dockerfile).

Feel free to copy these Dockerfiles into your project. You can use them like so:

`.gitpod.yml`:

```yaml
image:
  file: .gitpod.yml
```

`.gitpod.dockerfile`:

```dockerfile
FROM gitpod/workspace-full

# Install Dart, Flutter, etc.
```

(Once these files are committed into your project, and pushed to GitHub, you can simply create a new Gitpod workspace on your repository to get the new image.)

**Comment by svenefftinge** [comment]
Let's track this in #114

**Comment by fpisidoro** [comment]
Thanks for posting the Flutter Dockerfile. I got a Gitpod subscription just to try it out. But during the Workspace build, it stops with a "returned a non-zero code: 8" error.

This is the last part of the log: 

```
extracting: android-studio/build.txt

The command '/bin/sh -c cd /home/gitpod && 
wget -qO flutter_sdk.tar.xz 
https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.0.0-stable.tar.xz     && 
tar -xvf flutter_sdk.tar.xz && rm flutter_sdk.tar.xz &&     
wget -qO android_studio.zip 
https://dl.google.com/dl/android/studio/ide-zips/3.3.0.20/android-studio-ide-182.5199772-linux.zip &&     unzip android_studio.zip && rm -f android_studio.zip &&
wget --output-document=android-sdk.tgz --quiet http://dl.google.com/android/android-sdk_r26.1.1-linux.tgz && 
tar -xvf android-sdk.tgz && rm android-sdk.tgz;' returned a non-zero code: 8
```

Any idea what that means?

I also tried the Flutter Dockerfile of definitely-go, which does complete the workspace build. But the result just gives the IDE without syntax coloring and no functioning testing/debugging/building. Am I missing something here or is it too early to try flutter/dart with GItpod?
Thanks.

**Comment by svenefftinge** [comment]
Yes, it is a bit early for flutter as we don't have Dart language support included. We will soon allow VS Code extensions and with that I'll have another look at Flutter support. The docker would work in principle but without a mobile emulator (see #523). So I'll focus on Hummingbird: https://medium.com/flutter-io/hummingbird-building-flutter-for-the-web-e687c2a023a8

**Comment by VinayBaviri** [comment]
Any suggestion on #5047 !!
