### ISSUE TITLE
Update MySQL to 8.0

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#4890]
We're still running on MySQL 5.7 which is rather slow on some schema modifications - something [that MySQL 8 does much better](https://mysqlserverteam.com/mysql-8-0-innodb-now-supports-instant-add-column/).

## Steps forward
1. Analyse [the upgrade guide](https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html) to make sure we're not relying on defaults that have changed
2. update chart dependency to pull in 8.0
3. if need be, bump the TypeORM mysql dependency
3. run db-tests
4. observe server and ws-manager bridge for any DB-related errors

**Comment by MrSimonEmms** [comment]
> This is details in this [SO Post](https://stackoverflow.com/questions/50373427/node-js-cant-authenticate-to-mysql-8-0). I'll give a brief overview

MySQL 8 authentication has changed which causes a few issues with NodeJS as they've changed the plugin from `mysql_native_password` to `caching_sha2_password`. None of the MySQL plugins for NodeJS support this new authentication mechanism.

There's a couple of workarounds:
- if you have access to the run command (eg, if it's in a Docker container), append the command with `--default-authentication-plugin=mysql_native_password`
- if it's a cloud instance, run `ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'MyNewPass';`

Although I've never investigated it, these shouldn't affect the speed of the schema modifications.

**Comment by JanKoehnlein** [comment]
This issue has been set to scheduled by our automation because the label "meta:stale" was added. Unscheduling
