### ISSUE TITLE
[leeway] `with-retag` does not re-tag a package if nothing changed (e.g., not even `version`)

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#4892]
### Bug description

`leeway` does not re-tag docker images if:
 - the package is already cached
 - the `version` does not change

This makes it hard to publish Gitpod releases because one has to artificially invalidate the cache (by using `no-cache`, for instance).

### Steps to reproduce

 1. run a full build on a commit
 1. run the build again on the same commit and with the same version and `with-retag`
 2. note how no docker images are listed in the werft results

### Expected behavior

`leeway` should push all docker images (again).

**Comment by csweichel** [comment]
I'd argue that we get rid of "with-retag" altogether. It potentially breaks future deployments and really feels like a remanent from the past. It would strike me though that I'm missing a use-case where it's still needed.

What are you using with-retag for?

**Comment by csweichel** [comment]
Removing from groundwork right now - we'll re-add once it's clear what we need to do here.
