### ISSUE TITLE
Init command beeing run when opening snapshot

### ISSUE THREAD

**Issue by Pawluq** [gitpod-io/gitpod#4894]
### Bug description

When sharing a snapshot the init command in the start task “prepare webserver” is beeing run when opening it. According to the doc I think this shouldn’t be? The init command in the start task “setup” isn’t run as expected.

.gitpod.yml:
```
image:
  file: .gitpod.Dockerfile

tasks:
  - name: setup
    init: bash ./gitpod/init.sh 
    command: cd ./environment/ && docker-compose up

    # to have its own terminal, npm is run from here, to guarantee its depencies are installed up to this moment, they're also installed from here
  - name: npm install/run
    openMode: split-right
    command: echo 'Waiting for webserver container to start...' &&
     until docker ps | grep -q "webserver"; do sleep 1; done &&
     docker exec -it $(docker ps | grep "webserver" | awk '{ print $1 }') 
     bash -c "cd /var/www/laravel && npm install && npm run watch"

  - name: prepare webserver
    openMode: split-right  
    init: echo 'Waiting for webserver container to start...' &&
     until docker ps | grep -q "webserver"; do sleep 1; done &&
     docker exec -it $(docker ps | grep "webserver" | awk '{ print $1 }') 
     bash -c "/var/www/laravel/scripts/init_gitpod.sh"
```

init_gitpod.sh
```

#!/bin/bash

cd /var/www/
rm -R html
ln -s /var/www/laravel/public /var/www/html

# beautyful chat
cd /var/www/laravel
composer install
git submodule sync --recursive
git submodule update --init --recursive

cd ./resources/vue-beautiful-chat
#cd /var/www/laravel/resources/vue-beautiful-chat
npm install

cd /var/www/laravel/
composer install

# give file access
chmod 777 -R storage/


php artisan migrate
php artisan cache:clear
php artisan queue:restart
php artisan db:seed

#copy gitpod debugger config
cp -a ./gitpod/docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/

exit
```

### Steps to reproduce

-

### Expected behavior

The init command is only run when creating the workspace as described in the doc.

**Comment by csweichel** [comment]
Thank you for the detailed description.
I reckon this is a duplicate of https://github.com/gitpod-io/gitpod/issues/4838 though.

We'll raise the priority of #4838 accordinly

**Comment by csweichel** [comment]
I'm afraid that's an error in the documentation. At the moment when starting a workspace from a snapshot, the `init` tasks are executed. It's odd that the `init` command _setup_ isn't.

We now have two ways forward:
1. update the documentation to reflect current behaviour
2. make workspaces started from snapshot behave like they're re-started workspaces (breaking change)

@svenefftinge wdyt?

**Comment by svenefftinge** [comment]
I consider the current state a bug, so I'm all for

> 2. make workspaces started from snapshot behave like they're re-started workspaces (breaking change)
