### ISSUE TITLE
Current Gitpod workspace not loading fully

### ISSUE THREAD

**Issue by liammcluckie** [gitpod-io/gitpod#4896]
### Bug description

If I try to open a recent gitpod workspace specifically my cook-house one it doesn't fully load. By this I mean it doesn't display any of the usual items on the bottom bar including branches, push, pull etc. If I try to run my local server this also doesn't work correctly, everything in my terminal displays as it should but the Gitpod pop up with the server link never displays. If I try to access the server through the url from when this did work it also doesn't work. The way I got around this once was by starting a new workspace (using the gitpod button in the repo) but this means I need to re-upload my .env file and update my requirements.txt which is rather frustrating.

### Steps to reproduce

Open workspace (cook-house) you will see the bottom bar items not loading correctly. Try to run the server using python3 app.py.

### Expected behavior

Usually, I can see the branches etc in the bottom bar and I can run my server with no issues.

### Anything else?

Screenshots can be provided

**Comment by corneliusludmann** [comment]
I think it's due to the outage of open-vsx.org. See:

- https://www.gitpodstatus.com/incidents/4lm081417v7h
- https://www.eclipsestatus.io/incidents/yd3qyk7g0xj3

Since it's solved, could you please check if it works again, @liammcluckie?

**Comment by liammcluckie** [comment]
Hi, everything seems to be working fine now. Thanks for getting back to me!
