### ISSUE TITLE
Responsive preview 

### ISSUE THREAD

**Issue by AmalDjibo** [gitpod-io/gitpod#4898]
I thnk GItpod would be 100x better if it had a responsive preview feature where you could pick whether the preview window match the pixel width/height of a phone, iPad, or desktop screen.

**Comment by alesanchezr** [comment]
All major browsers do that pretty well, here is the documentation for chrome:
https://developer.chrome.com/docs/devtools/device-mode/

**Comment by ghuntley** [comment]
🎯 exact @alesanchezr. In your `.gitpod.yml` configure your webserver to `open-browser` (https://www.gitpod.io/docs/references/gitpod-yml/#portsnonopen) then use https://developer.chrome.com/docs/devtools/device-mode/
