### ISSUE TITLE
"no space left on device" (docker-root) during gitpod initialization

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#4902]
### Bug description

Running https://gitpod.io/#https://github.com/drud/ddev/pull/3103

During initialization I got:

> 7d93a5b42215: Download complete 
b7750a8a910a: Download complete 
write /workspace/.docker-root/tmp/GetImageBlob039063700: no space left on device
Failed to start simpleproj: exit status 1 

while it was downloading images. 

### Steps to reproduce

I expect you'll see this on https://gitpod.io/#https://github.com/drud/ddev/pull/3103 unless it has to do with overall system resources. 

### Expected behavior

I don't want to be crashing due to unknown system disk allocation limits (docker)

**Comment by rfay** [comment]
```bash
gitpod /workspace $ sudo du -sh .
51M     .
gitpod /workspace $ sudo df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb        369G  350G     0 100% /workspace
gitpod /workspace $ 
```

**Comment by rfay** [comment]
I guess this is a system allocation problem, because creating a new workspace from scratch everything worked fine, and

```bash
gitpod /workspace $ sudo du -sh .
7.2G    .
gitpod /workspace $ sudo df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb        369G  166G  184G  48% /workspace
```

**Comment by princerachit** [comment]
Hi,
We found that one of the nodes (where your ws was scheduled) had very high disk usage which caused this error. We have fixed the issue.
