### ISSUE TITLE
Bridge open-vsx outages

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#4904]
Open-vsx.org has had too many outages in the past and it breaks all users when it's down.
In order to minimize the impact, we should add some sort of cache which we can use when open-vsx is not responsive.

I think https://github.com/gitpod-io/gitpod/pull/3677#issuecomment-884702943 could be revived.

**Comment by akosyakov** [comment]
I wonder how we test it, the issue was that VS Code is calling query endpoint to resolve extensions' URLs. Is this endpoint changeable at all? If not caching artifacts does not help.

**Comment by corneliusludmann** [comment]
Don't know if I understand you right, @akosyakov. Actually, we don't want to cache artifacts (the actual extensions) at all but the queries to the registry. I implemented a caching for the query [here](https://github.com/gitpod-io/gitpod/pull/3677) already (for nginx, need to port this to Caddy). That worked pretty well.

**Comment by akosyakov** [comment]
That sounds good

**Comment by philschatz** [comment]
Hello :wave: ! It seems this proxy has a problem. https://open-vsx.gitpod.io/vscode/gallery/extensionquery seems to have the wrong certificate so installing extensions no longer works (see screenshot).

![image](https://user-images.githubusercontent.com/253202/134404049-192533bd-99f4-4a84-a4db-ff99e53c9751.png)
