### ISSUE TITLE
Prebuild logs are no longer being shown

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#4908]
### Bug description

When starting a manual prebuild, we used to get headless logs displayed.

However, since recently this is no longer the case.

### Steps to reproduce

1. Start a manual prebuild for some repository, using the URL prefix `gitpod.io/#prebuild/`
2. No logs are displayed

Instead, the browser console shows errors like these in a loop:

```
/start: started workspace instance: da5c76e1-105d-4f0f-9efa-5731bb536500
Request getHeadlessLog unsuccessful: 404/"Headless logs for da5c76e1-105d-4f0f-9efa-5731bb536500 not found" 
Object { method: "getHeadlessLog", args: (2) […] }
re-trying headless-logs because: error while listening to stream Error: Headless logs for da5c76e1-105d-4f0f-9efa-5731bb536500 not found
fetching from streamUrl: https://storage.googleapis.com/gitpod-prod-user-643ac637-74a…hUTRdshxeIxbsKsuwEJGgY3f197CBOFP0nj6rjijJIzmH818iYgsWw%3D%3D
re-trying headless-logs because: error while listening to stream TypeError: NetworkError when attempting to fetch resource.
fetching from streamUrl: https://storage.googleapis.com/gitpod-prod-user-643ac637-74a…fLTLo31ktPP1JGSQ80STS6xwNskP%2FQ7O5fKzxCSiEE83Tgza1J7A%3D%3D
re-trying headless-logs because: error while listening to stream TypeError: NetworkError when attempting to fetch resource.
...
```

<img width="1440" alt="Screenshot 2021-07-22 at 11 43 55" src="https://user-images.githubusercontent.com/599268/126620035-d99a584a-65a2-4237-8cd7-1103ed8e3d03.png">

### Expected behavior

- The headless logs should get displayed
- No errors should be logged in the console

### Anything else?

I suspect (without proof) that this might be a recent regression caused by the deployment of this related PR: https://github.com/gitpod-io/gitpod/pull/4875

**Comment by roboquat** [comment]
@svenefftinge: We have more than 19 cards scheduled. Above 15 only scheduler can perform this action. Those are:
  - csweichel
  - JanKoehnlein


<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4908#issuecomment-884787892):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jankeromnes** [comment]
Interestingly, https://gitpod.io/#prebuild/https://gitlab.com/gitpod/spring-petclinic **does** show prebuild logs in prod:

```
/start: started workspace instance: e343d567-be7b-46ac-ac14-9498d4ca46e5
fetching from streamUrl: https://gitpod.io/headless-logs/e343d567-be7b-46ac-ac14-9498d4ca46e5/edb375c6-ae32-4fa3-96f0-2115bc19f07b
```

**Comment by ghuntley** [comment]
Dupe of https://github.com/gitpod-io/gitpod/issues/4856#issuecomment-882209321

**Comment by csweichel** [comment]
Closing this issue for now. Let's revisit when it re-occurs. Also, we're looking at prebuilds and their logs in #4856
