### ISSUE TITLE
Proposal: Automating the generation of the engineering changelog

### ISSUE THREAD

**Issue by leodido** [gitpod-io/gitpod#4919]
As we plan to deploy more frequently, I think that automating the generation of the engineering changelog is a way to reduce the burden of the collateral details the development process has.

## Goal

Automate the generation of the engineering [CHANGELOG](https://github.com/gitpod-io/gitpod/blob/main/CHANGELOG.md) such that:

- Every PR gets associated with a set of **user-facing** changes
- Every set of changes gets associated with the authors and the reviewers
  - Ensuring credits and accountability
- Every change is categorized - ie., fix, breaking change, new feature, non-user-facing, etc.
- Every PR gets associated with a **release**
- No human edits the [CHANGELOG](https://github.com/gitpod-io/gitpod/blob/main/CHANGELOG.md) file
  - It becomes one of the tasks of our friend 🤗 [roboquat](https://github.com/roboquat)

## Implementation

Thus, as per internal discussions, I describe what we need to implement it.

- Install PR templates in this repository
  - The PR template markdown will contain a `release-note` block ([example](https://raw.githubusercontent.com/falcosecurity/falco/master/.github/PULL_REQUEST_TEMPLATE.md))
  - The content of such a block will associate a set of changes to the PR, to its author, and its reviewers
- Install the [`release-note`](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/releasenote) Prow plugin in the [gitbot](https://github.com/gitpod-io/gitbot) repo for the **gitpod** repo (this one)
  - Every PR without a valid description of the changes in the `release-note` block will be automatically blocked by being merged in through the GitHub label `do-not-merge/release-note-label-needed` (Tide responsibility)
  - PRs not implementing **user-changes** will use the passthrough string - ie., `NONE`
  - Changes MUST follow the [Commits Conventional Spec v1](https://www.conventionalcommits.org/en/v1.0.0/#examples) so that they can be categorized by using parsers like [go-conventionalcommits](https://github.com/leodido/go-conventionalcommits)
- Merged in PRs gets assigned to a **release** (see open points below)
   - Depending on what a **release** is the automation for this step will require different Prow plugins
- CHANGELOG gets generated by [rn2md](https://github.com/leodido/rn2md) (see open points below)
   - Every time (automatically) a GitHub milestone gets closed
   - Every time (automatically) a PRs gets merged in and moved to a specific GitHub project card
   - [roboquat](https://github.com/roboquat) will push the changes to the CHANGELOG file
     - Either directly on the `main` branch of the repo or via a PR

## Examples

Here some examples of `release-note` blocks.

Communicate no **user-changes**.

```release-note
NONE
```

Communicate a new feature:

```release-note
new(components/gitpod-cli): introducing the `magic` command
```

Communicate a fix:

```release-note
fix(components/server): ensure a sane redirect/returnTo query param
```

Notice this DOES NOT impose any convention on commits. Only on the content of the `release-note` block in the PRs.

Here's an example of a CHANGELOG created with a very similar process to the one proposed here: [example](https://github.com/falcosecurity/falco/blob/master/CHANGELOG.md#v0281).

## Open points

To define what's a **release**.

I see two possibilities.

1. Given a release cadence (eg., monthly) we create a GitHub milestone and tag all the PRs in the defined time range as belonging to the milestone. Then, such a milestone is used to filter the PRs at the end of the time range to automatically generate the engineering CHANGELOG.

2. We tie the concept of **release** to the existing GitHub projects cards. Automation grabs the release notes from the merged-in PRs in a given Github projects card (eg., "Done"). Assuming the PRs in this status are deployed this could play nicely.

Whether we chose to define a **release** as (1) or (2) does not matter in terms of automation.
Meaning, both choices can be automated with Prow plugins (and GitHub APIs).

**Comment by JohannesLandgraf** [comment]
Nice 👍 Given that we deploy 2 times a week. In line with https://link.medium.com/qPXV6cqK7hb I think we should have at least a bi-weekly, potentially even weekly Changelog cadence.

**Comment by csweichel** [comment]
I love the gratuitous use of automation in this proposal, especially when it comes to enforcing convention. A few comments:
- Do I understand this correctly that we would not be imposing a convention on the commit messages themselves, but would rather follow the "conventional commit message" format for describing the changes in the changelog?
- Regarding cadence: to me it would make most sense to synchronise this with the deployment itself. Whenever we deploy, we update the changelog. This way the changelog would always reflect what's currently available to the users.

**Comment by leodido** [comment]
>     * Do I understand this correctly that we would not be imposing a convention on the commit messages themselves, but would rather follow the "conventional commit message" format for describing the changes in the changelog?

Correct.
This proposes to enforce the Conventional Commits format only for describing the changes.
This translates to enforcing it only in the `release-note` block of the pull requests.

**Comment by mikenikles** [comment]
Thanks Leo, this is great!

The engineering changelog is the first step of a larger process to release www.gitpod.io/changelog, send a tweet, etc. Once this issue here is resolved, I'll work on automation for the other steps of the release process. Looking forward to automating as much of this as possible.

**Comment by JohannesLandgraf** [comment]
What is the next step here? Schedule to Groundwork?

**Comment by MrSimonEmms** [comment]
I've done this sort of thing a few times. [CommitLint](https://github.com/conventional-changelog/commitlint) is very useful for enforcing the standards and then can use [Semantic Release](https://semantic-release.gitbook.io/semantic-release/) to generate a changelog as well as generating a new version number.

One thing to note - Semantic Release either sets versions to v1.0.0 or above, or an RC version number (eg, v1.0.0-rc1). I've not found a way of getting it to stay within the 0.x.x range

**Comment by JanKoehnlein** [comment]
First shot can be tested on https://github.com/gitpod-io/gitpod-test-repo

I am not sure whether the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) syntax buys us something here:
1) CC is meant for complete commit messages. In our case we extract the note exclusively form a block.
2) Body and footer don't make much sense here for the same reason.
3) In a continuous changelog, sorting by _type_ or _scope_ doesn't make much sense either, so why parse it in the first place?
4) We should validate the note syntax before adding the tag. Currently, we only validate whether the block is there and contains at least the word `NONE`. 
5) We should create and curate a list of types and scopes for uniformity. That's extra effort.
6) The new autogenerated notes will look different from the old manually written ones.

OTOH, CC is somehow a standard (what k8s does) and we can uniformly mark breaking changes.

I'd rather go for a simpler format:
- `!` für breaking followed by the prose description until the end of line
- alternatively `NONE`

WDYT?

**Comment by mikenikles** [comment]
From a www.gitpod.io/changelog perspective, I'm :+1: for the simpler format as all we need there is a way to highlight breaking changes.

I use CC in personal projects at the commit level where it makes sense to be granular with types & scopes. We apply it at a PR level and a PR can easily span multiple types or scopes.

**Comment by mikenikles** [comment]
Thanks Jan for helping me test https://github.com/gitpod-io/gitpod-test-repo/pull/142. This PR has two contributors, but the changelog only lists me - I opened the PR.

To make sure we mention all contributors, we should find a way to comma-separate all PR contributors in `CHANGELOG.md`

**Comment by JanKoehnlein** [comment]
Done.
