### ISSUE TITLE
[Dashboard] Allow Projects for Individuals

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#4920]
We should allow projects below individual accounts as well.
 - Individuals might feel squeezed into the concept of a team
 - will make teams and individuals more alike and therefore easier to grasp

### Designs
| BEFORE | AFTER |
|-|-|
| <img width="1000" alt="Personal Account - BEFORE" src="https://user-images.githubusercontent.com/120486/126787803-a400bd71-31f2-4699-afb3-b59bb2c7b29b.png"> | <img width="1000" alt="Personal Account - AFTER" src="https://user-images.githubusercontent.com/120486/126973631-e716b000-7386-4259-9b2b-56d89572e088.png"> |

**Comment by jankeromnes** [comment]
I'll give this a try! 🔧

**Comment by svenefftinge** [comment]
@gtsiolis WDYT about reversing the tabs, I.e. make project the first one?

**Comment by gtsiolis** [comment]
Makes sense! Updated the screenshots in the issue description.

🍊 🍊 🍊 🍊 

Cross-posting some notes from the [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1627291113017800) (internal) regarding URLs.

> **George**: Could be minor but going with a) Projects as the first tab here and b) the redirect to /username/workspaces, would lead users the second tab when loading the dashboard using /workspaces their browser history until their browser history is updated based on usage.

> **George**: Thinking about this again, a boring (simple) solution could be to just keep the same URL (/workspaces) for workspaces associated with the personal account and only nest team workspaces within a /team-name/workspaces URL.

**Comment by svenefftinge** [comment]
> Thinking about this again, a boring (simple) solution could be to just keep the same URL (/workspaces) for workspaces associated with the personal account and only nest team workspaces within a /team-name/workspaces URL.

And same for projects.
