### ISSUE TITLE
Can't connect to public port from inside workspace when cluster is using cilium networking

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#4922]
### Bug description

From inside a workspace, one can usually `curl` the URL of a publicly exposed port. This does not work when the cluster is using cilium networking.

Connecting to the exposed port from the outside (e.g. the browser) works just fine. 

### Steps to reproduce

hi Sebastian,

I can reproduce the problem. 
1. open https://gitpod.io/#https://github.com/gitpod-io/spring-petclinic
2. ensure you are on staging or cluster `eu12` or `us12`. (that's where cilium networking is enabled).
3. expose port 8080 as "public"
4. run `curl --fail -sS $(gp url 8080)`
5. see the `curl` command time out.

### Expected behavior

`curl` should have returned the HTML content, as it does on clusters `eu11` and `us11`.

### Anything else?

Workaround: Restart workspace until you end up on `us11` or `eu11` cluster.

Reported [here](https://community.gitpod.io/t/cli-cant-connect-to-ports/4243).

**Comment by meysholdt** [comment]
I've cordoned the clusters eu12 and us12, so as a user you should no longer run into the bug. If your workspace is still running on an affected cluster, restarting it will move it back to non-affected clusters.

**Comment by csweichel** [comment]
Cilium would be awesome to have, and we've been talking about this for a while. Considering the current workload however, we don't have an urgent need for the upgrade. 

I'll unschedule this issue for now - please re-add in a week or two.
