### ISSUE TITLE
[ws-daemon] Ensure we're respecting the `gcloud.tmpdir` when creating backups

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#4928]
### Bug description

We seem to be creating the backup tars on the container `tmp` directory:
![image](https://user-images.githubusercontent.com/3210701/126867641-f74cd1dd-4588-4c68-a9ae-3bc790ccb717.png)

Also, we're not configuring the `sync-tmp` volume to use `ssd1` (@meysholdt)

### Steps to reproduce

Run in prod

### Expected behavior

We should respect the configured tmpdir

**Comment by meysholdt** [comment]
That is both fixed by https://github.com/gitpod-com/gitpod/pull/5691, isn't it?

**Comment by csweichel** [comment]
It is indeed. We should as a follow up ensure we always have valid configuration, ie make extra fields an error. 

I'll modify this issue to reflect that.

**Comment by csweichel** [comment]
fixed in #4942
