### ISSUE TITLE
[image-builder] (mk3) - the name of the bucket cannot be repeated (S3)

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#4929]
### Bug description

The name of the bucket is `gitpod-user-image-builder`. 

### Steps to reproduce

Build an image and check the name of the bucket

**Comment by csweichel** [comment]
We should not create a bucket in the first place. We'll never create a backup or snapshot for an image build workspace.

**Comment by ArthurSens** [comment]
@csweichel what do we do about mk3 issues? Should we move them to "Done" in the groundwork? Or do you want to rework something?

**Comment by csweichel** [comment]
Nope, done is the right place.

It's just we have new issues also
