### ISSUE TITLE
Consider auto-exposing active ports

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#493]
Today, when I run a server in Gitpod, I need to do several things before I can see my app:

<img width="864" alt="Screenshot 2019-04-17 at 12 44 00" src="https://user-images.githubusercontent.com/599268/56282086-8e849200-610e-11e9-9bfc-b414ae85b6db.png">

→ Click `Expose`

<img width="864" alt="Screenshot 2019-04-17 at 12 44 14" src="https://user-images.githubusercontent.com/599268/56282121-9fcd9e80-610e-11e9-8da1-6077ea479de0.png">

→ Click `Open Preview` or `Open Browser`

What's the point of "Expose"? Why don't we just automatically expose all active ports?

As a user, I don't care about "Expose" or what it means, I just want to see my app, and today I need to either dismiss an extra pop-up or manually list my ports in a `.gitpod.yml`. This seems like unnecessary friction.

**Comment by AlexTugarev** [comment]
I got your point, @jankeromnes, but not every service has a UI. Would a merger of these actions reduce the friction as well? 

`A service is available on port ... [Open Preview] [Open Browser] [Just Expose]`, WDYT?

**Comment by jankeromnes** [comment]
It's not just the number of actions required. Confronting our users with the concept of "Expose" raises many questions, and increases Gitpod's perceived complexity + our users' mental overhead while using Gitpod: Not only do users have to know what services are running on what ports, but we also introduce an additional state of "exposed" / "not exposed" for ports, that we implicitly demand our users understand (or guess at), keep in mind, and manage.

And I feel like it's not sufficiently useful, i.e. Gitpod users won't massively benefit of being able to expose / unexpose ports. That's why I'm suggesting to auto-expose active ports, and just remove the internal concept of "Expose" from our product.

When we decide to show the `[...] but is not exposed [Expose]1 pop-up, can't we just do whatever "Expose" does, and not bother the user with it? 🙂

**Comment by akosyakov** [comment]
For local debugging auto-exposing won't make sense, they just should be ignored.

**Comment by jankeromnes** [comment]
I guess the main question here is:

> Is it useful to **not** expose a port where some server is running?

If that's not an extremely useful thing, we can auto-expose all active ports and be done here. 😄

**Comment by svenefftinge** [comment]
We should not expose by default because these ports are exposed to the internet so at least people should be aware of it. But we can skip the first notification and imply exposing when a user clicks 'open preview' or 'open port'.
