### ISSUE TITLE
Terminal does not open in the correct `workspaceLocation `

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#4935]
### Bug description

When I set a `workspaceLocation` in my `.gitpod.yml` file, I expect the terminal to open in that directory. Currently, it opens in the `checkoutLocation` I specified.

### Steps to reproduce

1. Create the following `.gitpod.yml` file:
    ```yaml
    checkoutLocation: here-is-my-source-code
    workspaceLocation: .
    ```
2. Open a new workspace based on that configuration

### Expected behavior

The terminal opens in the default `/workspace` directory since I set this as the `workspaceLocation`.

### Example repository

The `configure-cloud-based-development` branch in https://github.com/mikenikles/redwood ([direct link](https://github.com/mikenikles/redwood/tree/configure-cloud-based-development))

**Comment by akosyakov** [comment]
Is it expected? Is it regression? cc @svenefftinge

**Comment by csweichel** [comment]
The user impact is not clear. Just because something affects a user-facing feature doesn't mean it has actual user impact.

**Comment by csweichel** [comment]
will remove from groundwork until it's clear if this is a regression or expected behaviour. Please re-add once this has become actionable.

**Comment by svenefftinge** [comment]
It makes total sense and worked like that in Theia. So I'm all for changing/fixing this.

**Comment by akosyakov** [comment]
What do we do when workspaceLocation is workpace file? Do we fall back to checkout location? @svenefftinge ?

**Comment by akosyakov** [comment]
And just to clarify it's only going to work for task terminals, regular VS Code terminals are controlled by VS Code frontend and we cannot change there.
