### ISSUE TITLE
Prebuild got stuck, now workspace doesn't open

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#4936]
### Bug description

I updated `.gitpod.yml`, which triggered a prebuild.
All the `init` tasks ran successfully, but this screen kept showing this for hours.
![image](https://user-images.githubusercontent.com/22901/126910678-ac1b2431-9422-466d-8a63-6457ab6edf15.png)

Trying to open the workspace (https://github.com/shaal/druxt.js/tree/gitpod), displays this error -
![image](https://user-images.githubusercontent.com/22901/126910696-24600049-670d-496b-8cab-0a924b6f7b8e.png)

### Steps to reproduce

Not sure if this will happen again - the steps are 
1. Update `.gitpod.yml`, that include init tasks.
1. Watch the prebuild and confirm all init tasks run successfully.
1. (If prebuild screen is stuck with exiting, try open the workspace without prebuild)

### Expected behavior

When all `init tasks` run successfully, I expect the workspace to open with no errors.

### Example repository

https://github.com/shaal/druxt.js/tree/gitpod

**Comment by shaal** [comment]
Running on another repo.
When I make changes in https://github.com/shaal/DrupalPod/pull/25, a prebuild runs automatically.

After running everything successfully, it stays like that forever -
![image](https://user-images.githubusercontent.com/22901/127082506-ebf9c8f9-5df0-4a97-9602-4e5d1db04c14.png)

But now,  I can open new Gitpod workspaces from that PR, even that the prebuild screen seems stuck.

**Comment by geropl** [comment]
Possibly related/dupe: https://github.com/gitpod-io/gitpod/issues/4879

**Comment by shaal** [comment]
Help please.
I noticed that after making changes in `.gitpod.Dockerfile`, even that the image-build process is running, and a prebuild seems to be running afterwards, the workspace itself is running all the `init` tasks, instead of receiving it from prebuild.

The solution I found, was initiating a manual prebuild (through `#prebuild` in the URL). It worked well whilw it was in a PR.
Now that I merged that PR into `main`, the prebuild seems to be stuck
I believe this is the URL of the prebuild - https://amaranth-cephalopod-su26hid8.ws-eu13.gitpod.io/
I can open new workspaces of DrupalPod project, but they will all run `init` commands in the workspace.
I cannot initiate a manual `prebuild` through URL, because I am getting an error message, that workpsace already running prebuild.

Is there a way to release a stuck prebuild? is it by submitting a bug report? does it fix itself after a few hours?
Thank you!

**Comment by shaal** [comment]
I think I "solved" it, by making a change in `.gitpod.Dockerfile` file.

**Comment by pawlean** [comment]
I'm curious - what did you change?

**Comment by shaal** [comment]
Hi @pawlean I have a special comment in `.gitpod.Dockerfile`, exactly for these scenarios. I updated that comment to initiate an image rebuild.
https://github.com/shaal/DrupalPod/commit/9aedd250acfdb21dcd91aa38f89e034d5f808ca0#diff-880b52e6ca2bb12254505114898f0c6ba79405449754dfd236a7bee4fb871918R29

**Comment by JanKoehnlein** [comment]
The original issue has been worked around, and there are lots of changes since then in the handling of pre-builds. Feel free to  add new issues if the problem persists in a similar way.
