### ISSUE TITLE
Fix workspace sorting order in dashboard

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#494]
**Describe the bug**
This workspace sorting order doesn't make any sense to me:

<img width="1552" alt="Screenshot 2019-04-17 at 13 34 04" src="https://user-images.githubusercontent.com/599268/56284705-9562d300-6115-11e9-9d91-55edc47e24f0.png">

**To Reproduce**
1. Start a few workspaces
2. Be confused by their (strange and unstable) order in Dashboard

**Expected behavior**
They should probably be ordered by creation time.

**Comment by ekene90** [comment]
Good

**Comment by jankeromnes** [comment]
We have recently deployed a change to the workspace sorting.

The change was to always display currently running workspaces at the top. Otherwise, I believe running workspaces and stopped workspaces will all be sorted by `creationDate`, but I'm not sure.
