### ISSUE TITLE
[ws-daemon] Don't accept configuration with unknown fields

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#4940]
As such configuration is most likely erroneous and will lead to system failure down the road. E.g. this was the root cause of the latest incident whereby ws-daemon was misconfigured which eventually lead to its eviction.

**Comment by ArthurSens** [comment]
Regarding misconfigured files. I highly recommend the use of CUE, where you can define a schema to your config and easily test it via CI with a single command `cue vet file.config schema.cue`


See also: 
*  https://cuelang.org/docs/usecases/datadef/
* https://cuelang.org/docs/usecases/validation/

**Comment by csweichel** [comment]
Cue does sound rather interesting, but also dauntingly complex. Most of our configuration is generated using helm with a staggering number of degrees of freedom (another problem we must tackle). We'll always need runtime config validation.
