### ISSUE TITLE
Move qemu image build to Docker image rather than the init tasks

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#4945]
Right now we're building the agent-smith qemu image for every prebuild. Instead we should be building it once during the image build. This way, prebuilds will be considerably quicker.

**Comment by svenefftinge** [comment]
Would the 22GB move into the image then as well?

**Comment by ghuntley** [comment]
It's circa 2GB these days after https://github.com/gitpod-io/gitpod/blob/f654391fcb4e160ed933f6f8724d7d90e138bf4d/components/ee/agent-smith/scripts/prepare-bpf-dev-environment.sh#L26. Specific change: `--preallocation=off`
