### ISSUE TITLE
Watching ports and opening browser results in many windows

### ISSUE THREAD

**Issue by ttauchen** [gitpod-io/gitpod#4946]
### Bug description

Dear devs,

```
ports:
  - port: 4004
    onOpen: open-browser
```

Works nice initially, but we are using a server which recompiles once we edit a file and reservers via port 4004 (i assume the process fully restarts). This results in gitpod opening window after window after window. Any way i can prevent this? Could gitpod remember that a window is already open for 4004 and not open another one?

### Steps to reproduce

```
ports:
  - port: 4004
    onOpen: open-browser
```

**Comment by svenefftinge** [comment]
We use a constant [window name](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) per port and workspace.

**Comment by ttauchen** [comment]
> We use a constant [window name](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) per port and workspace.

We are unable to pin the window name as it is set by the server and later altered by the static apps displayed inside (dependent on the location you navigaate to)

**Comment by svenefftinge** [comment]
Sorry, I meant to say "we *should* use a constant window name ...". I.e. how to we could fix your issue in the product.

**Comment by akosyakov** [comment]
It is actually internals of VS Code, not "we", and there is not API to pass it from the extension host to the main window.
