### ISSUE TITLE
Update project configurator designs

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4948]
Following the updates in project https://github.com/gitpod-io/gitpod/pull/4631 which added a cut through of the project configurator, the project configurator designs need to be updated.

### Designs

Adding below the first step of the project configurator.

| Authorize Provider |
|-|
| <img width="1440" alt="Pending" src="https://user-images.githubusercontent.com/120486/126963409-a8b862c3-cee3-4ebb-99b3-2e8e5738341a.png"> | 

| Repository List | Repository Hover | Repository Taken |
|-|-|-|
| <img width="1440" alt="Default" src="https://user-images.githubusercontent.com/120486/127672398-8f3407b9-bccb-4b0a-8744-4686caab845c.png"> | <img width="1440" alt="Hover" src="https://user-images.githubusercontent.com/120486/127672482-b536e3e2-cf82-4128-acf9-12bd9f7f8064.png"> | <img width="1440" alt="Taken" src="https://user-images.githubusercontent.com/120486/127672486-fae3178f-e301-433d-9275-0e198e2a35ff.png"> |

| Select Team | Create Team |
|-|-|
| <img width="1440" alt="Default" src="https://user-images.githubusercontent.com/120486/127672643-cfc64766-0208-427a-8a9d-6c05b400dc74.png"> | <img width="1440" alt="Create" src="https://user-images.githubusercontent.com/120486/127672656-bb0e4036-7ae5-44c9-93af-18492715bb6e.png"> |

| Configuration Existing in Git |
|-|
| <img width="1440" alt="Configure" src="https://user-images.githubusercontent.com/120486/127672818-c2776e7e-70b4-4702-8773-b034bb442ec6.png"> |

| Add Configuration | Pending Prebuild | Failed Prebuild | Running Prebuild | Ready prebuild |
|-|-|-|-|-|
| <img width="1440" alt="Configure-4" src="https://user-images.githubusercontent.com/120486/127673110-44e8d28b-ab6a-436c-82c3-757e69b02ba2.png"> | <img width="1440" alt="Configure" src="https://user-images.githubusercontent.com/120486/127673133-687201d5-7faf-4c41-96ef-9600e44a825d.png"> | <img width="1440" alt="Configure-1" src="https://user-images.githubusercontent.com/120486/127673146-80400711-2baf-47f3-a485-7fada0e27719.png"> | <img width="1440" alt="Configure-2" src="https://user-images.githubusercontent.com/120486/127673158-f45d16c7-7f5d-4963-9c9f-d352e3e63cfa.png"> | <img width="1440" alt="Configure-3" src="https://user-images.githubusercontent.com/120486/127673166-d10d580f-a112-40f9-86eb-a0518418999e.png"> |

| Project Configuration |
|-|
| <img width="1440" alt="Prebuilds" src="https://user-images.githubusercontent.com/120486/127674475-9d20c0fd-7ae8-4485-895e-5db033829605.png"> |

See [design specs](https://www.figma.com/file/iYeLdIMjMdSpTgFGEAicmk/Project-Configuration-4648?node-id=0%3A1).

**Comment by jankeromnes** [comment]
Happy to take this on next week! Also, happy to collaborate on this (e.g. by reviewing small PRs in case you want to fix small parts of this 🏓)

**Comment by gtsiolis** [comment]
LET'S DO THIS ! 🏀

**Comment by gtsiolis** [comment]
Pasting below the new specs for the project configuration page. Cc @jankeromnes @AlexTugarev @svenefftinge 

| Detecting | Detected |
|-|-|
| <img width="1440" alt="Detecting" src="https://user-images.githubusercontent.com/120486/128853803-2321a240-d208-46b6-9211-52336ee683a3.png"> | <img width="1440" alt="Detected" src="https://user-images.githubusercontent.com/120486/128853780-365452e4-de25-4517-9010-05cc0017d274.png"> |

| Existing |  Failed | Pending | Success |
|-|-|-|-|
| <img width="1440" alt="Existing" src="https://user-images.githubusercontent.com/120486/128853823-89aa2461-4fb5-4f7a-acd4-b575aafcd902.png"> | <img width="1440" alt="Failed" src="https://user-images.githubusercontent.com/120486/128853937-39dd041a-c56c-44b5-ab8b-3cf3a030f67b.png"> | <img width="1440" alt="Pending" src="https://user-images.githubusercontent.com/120486/128853942-398e2820-d3ca-4711-84e7-c120a63c985e.png"> | <img width="1440" alt="Success" src="https://user-images.githubusercontent.com/120486/128854197-3555469a-5bfb-4afa-aed2-4bedc2c22963.png"> |

**Comment by jankeromnes** [comment]
Wow! These specs are extremely good ✨😍🎯

Many thanks! 🙏 Will start implementing them in my next PR 🚀

**Comment by gtsiolis** [comment]
Thanks, @jankeromnes! Let me know if anything looks unclear. 🤓
