### ISSUE TITLE
Gitpod Self-Hosted v0.10.0 is limited to only 50 hours

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#4950]
### Bug description

https://community.gitpod.io/t/gitpod-self-hosted-pricing-clarification-limited-to-only-50-hours/3747

### Steps to reproduce

https://community.gitpod.io/t/gitpod-self-hosted-pricing-clarification-limited-to-only-50-hours/3747

### Expected behavior

Gitpod Self-Hosted should not be limited to 50 hours. It seems like the payment wall for SaaS is now active in the self-hosted edition.

**Comment by geropl** [comment]
Seems like we've switched the default build output from OSS to EE, but haven't adjusted the Self-Hosted release process/code.

**Comment by geropl** [comment]
Looking at the code there's nothing obvious. And re-reading the community issue closely I don't see proof that this is an code error. Will try verify.

**Comment by geropl** [comment]
This seems indeed not be the case: https://community.gitpod.io/t/gitpod-self-hosted-pricing-clarification-limited-to-only-50-hours/3747/9?u=geropl

I will keep this open until this is verified, and we can discuss whether we want to change the UI, but will remove the prio label for now.

**Comment by ArthurSens** [comment]
I saw this issue on the "Awaiting Deployment" column but doesn't really make sense to me since it is not related to our SaaS offering, is it? (It's not waiting for deployment because we don't deploy this anywhere).

Should I just move it to "Done"?
