### ISSUE TITLE
Update team creation designs

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#4951]
### Problem to solve

Following the upcoming design changes for the project configurator (see https://github.com/gitpod-io/gitpod/issues/4948), the project team creation page would be better to use the same elements and style as the project configurator step for team creation.

Also, since the upcoming and new pricing changes will land later on, this is a good place to also inform users about pricing of the Teams & Projects fearture.

### Proposal

Let's a) update the team creation page using the updated elements from the project configurator and b) add a footnote about upcoming pricing changes of this feature or even link to a more detailed pricing page.

### Designs

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="NewTeam - BEFORE" src="https://user-images.githubusercontent.com/120486/126983232-c8999438-f44c-4f10-a62b-24def62d455c.png"> | <img width="1440" alt="NewTeam - AFTER" src="https://user-images.githubusercontent.com/120486/126983972-3ab89b54-d62d-4428-ba75-888806ee0948.png"> |
| <img width="1440" alt="NewTeamError - BEFORE" src="https://user-images.githubusercontent.com/120486/126983253-7d7cf00a-45c2-434d-ad8b-8a478252cfab.png"> | <img width="1440" alt="NewTeamError - AFTER" src="https://user-images.githubusercontent.com/120486/126983987-2f0a14f7-098a-44de-b704-2967893f62ac.png"> |

See [design specs](https://www.figma.com/file/hRVJP4UEM0b6DnTpiWsZL8/Update-team-creation-designs-XXXX?node-id=0%3A1).

**Comment by gtsiolis** [comment]
Still relevant and something to potentially keep in sync with the new team selection designs updated in https://github.com/gitpod-io/gitpod/pull/7030. Cc @jldec

**Comment by jldec** [comment]
FYI - current wording below

@gtsiolis I don't find the design jarring or problematic. Would suggest closing this issue.
---

![Screenshot 2022-01-01 at 21 10 34](https://user-images.githubusercontent.com/849592/147860259-e85ff6d0-0c1e-4015-98a8-30f5d53f7b07.png)
