### ISSUE TITLE
[supervisor] title does not get updated anymore

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#4968]
### Bug description

The task terminal title should update to reflect currently running process, but it shows only first now. It is a regression in the supervisor.

### Steps to reproduce

Open a task terminal, and execute some long running command like `watch ls -l`, you should see that task terminal displays `watch`, but it does not.

**Comment by csweichel** [comment]
We have directly user-impacting issues incoming that need more attention.
It's unusual that we de-schedule an issue once it's been scheduled, but have no other choice on the matter.

**Comment by roboquat** [comment]
@csweichel: dont-schedule is not yet supported

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/4968#issuecomment-896627803):

>/dont-schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
Code pointers:
- grpc interface: https://github.com/gitpod-io/gitpod/blob/2c70b97ac1ed5b5ec8856e49f5c0551637a37092/components/supervisor/pkg/terminal/service.go#L257-L277
- test: https://github.com/gitpod-io/gitpod/blob/2c70b97ac1ed5b5ec8856e49f5c0551637a37092/components/supervisor/pkg/terminal/terminal_test.go#L24

We should reactivate tests, fix them and make stable.

**Comment by akosyakov** [comment]
It works with latest VS Code 1.60.0 again
