### ISSUE TITLE
Printing Unicode to the Gitpod terminal

### ISSUE THREAD

**Issue by danwallach** [gitpod-io/gitpod#497]
**Describe the bug**
If Unicode characters are too tall, they get chopped off to fit the font height.

**To Reproduce**
I've got a Java autograder I'm working on. You can play with it here:
https://gitpod.io/github.com/RiceComp215-Staff/RiceChecks-RpnExample

If you run `./gradlew autograder`, you'll see the chopped text. I'm attaching a screenshot from my Mac, running the Chrome browser.

**Expected behavior**
I'm not entirely clear what's the best way to handle Unicode glyphs, but other terminals seem to render this better.

![Screen Shot 2019-04-20 at 5 53 37 PM](https://user-images.githubusercontent.com/743029/56463228-796d6480-6395-11e9-9880-67f4d423e3da.png)

**Comment by svenefftinge** [comment]
Thanks! We should check and compare with the bare xterm.js example.
