### ISSUE TITLE
Stage selected lines

### ISSUE THREAD

**Issue by ad-si** [gitpod-io/gitpod#4971]
I'm looking for a way to stage selected lines. Apparently that's possible with the desktop VS Code: https://stackoverflow.com/questions/34730585/how-can-i-commit-some-changes-to-a-file-but-not-others-in-vscode. How can I do it in Gitpod?

**Comment by ad-si** [comment]
Ah just a few lines down is a working solution: https://stackoverflow.com/a/47331858
But I'd prefer to be able to do it in the source control view…

**Comment by akosyakov** [comment]
It shoudl work exactly the same way in VS Code web version. Are you sure that you are switched to VS Code from Theia: https://gitpod.io/preferences

**Comment by ad-si** [comment]
> Are you sure that you are switched to VS Code from Theia

![image](https://user-images.githubusercontent.com/36796532/127823080-4a1ed86c-5daf-4f50-a127-5846c12ec3b0.png)

> It should work exactly the same way in VS Code web version

This are the options I have when I'm in the source control tab:

![Screen Shot 2021-08-02 at 07 43 08Z](https://user-images.githubusercontent.com/36796532/127823235-aaf4fab7-1351-4980-a9bb-37415639dd66.png)

**Comment by akosyakov** [comment]
Hm, strange indeed, it appears there only if file is already staged. It seems to be some VS Code regression. Hope it gets resolved next versions.

You can try to select the change indicator in the editor ruler and use actions there:
<img width="1494" alt="Screenshot 2021-08-02 at 10 26 55" src="https://user-images.githubusercontent.com/3082655/127829074-139bb9ee-8b38-4559-b926-ec4c76f633d8.png">

**Comment by ad-si** [comment]
Has this been fixed?

**Comment by akosyakov** [comment]
@ad-si Could you try? If not please open the issue int the upstream: https://github.com/microsoft/vscode
