### ISSUE TITLE
Sync Issue with Self-Hosted Gitlab Private Repo Sync

### ISSUE THREAD

**Issue by orellabac** [gitpod-io/gitpod#4973]
### Bug description

If you are using a self-hosted gitlab instance with gitpod and you have a private repository you will find some annoying sync issues with the message:

An operation requires additional permissions: read_repository. Please grant permissions and try again.
However if you go the gitpod.io/integrations and try to add the read_repository permission:

### Steps to reproduce

Use a selfhosted gitlab with gitpod ( for this situation I use gitlab as my repo server but I use github for authentication with gitpod)

- Create a private repository
- open that repository in gitpod
- press the git sync icon from the status bar

You will get an alert that says:

An operation requires additional permissions: read_repository. Please grant permissions and try again.
However if you go the gitpod.io/integrations and try to add the read_repository permission:

If you navigate to gitpod.io/integrations and on your gitlab integration select Edit Permission and mark the read_repository check and press update_permissions

The browser navigates to:

https://selfhostedgitlab.net/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fgitpod.io%2Fauth%2Fsnowconvertstudio.net%2Fcallback&scope=api%20read_user%20read_repository&client_id=cdd2a441ee52b8c19c7bf7c6dfb0ce3e641ae5edd436dba2809b2222aadb169f

And the page displays:

An error has occurred
The requested scope is invalid, unknown, or malformed.

### Expected behavior

You can update the read_repository permission to have the alert go away.

**Comment by drumm** [comment]
I worked around this by going back to the initial user account used to set up Gitpod in our GitLab instance, and adding the read_repository scope to that account's application.

**Comment by orellabac** [comment]
Thanks I will try that out
