### ISSUE TITLE
Download workspace shows error while any workpace is running for the first time

### ISSUE THREAD

**Issue by tyler36** [gitpod-io/gitpod#4977]
### Bug description

When I clicked the `download` link on the dashboard, the page reloaded with an error
```
Oh, no! Something went wrong!
Error
```

I tried 3 times but with same results. Unfortunately, the error is generic and therefore I am unsure what the problem might be.

My first attempts was with a gitpod session spawned by DrupalPod on [this issues](https://www.drupal.org/project/avif/issues/3188912)
I also attempted a gitpod session spawened by DrupalPod on [this issue](https://www.drupal.org/project/cypress/issues/3179307)

Finally, in order to have "steps to repoduce" I attempted it with a default template, see below.

### Steps to reproduce

1. Visit [https://gitpod.io/workspaces/](https://gitpod.io/workspaces/)
2. Click `New workspace`
3. Click `Examples` tab
4. Click `template-php-drupal-ddev`
5. Click `Gitpod` button in bottom left, and select `Gitpod: open dashboard`
6. Click virtual dots (have we decided on a name for these yet?) for the workspace and select `download`
7. New page loads, with generic error (see screenshot)
![gitpod-download-error](https://user-images.githubusercontent.com/7234392/127244797-93f7584d-f970-4ec7-983b-80a1f611c355.jpg)

### Expected behavior

Obviously a download would be preferable.

### Anything else?

Besides the `download` feature not working, perhaps the error message could be improved. Eg.
- "Your account does not have permsission"
- "We seem to be having a network issue"
- "This workspace is currently locked"
- "The download feature is unavailable at this time"

It's hard to know if it's a gitpod issues, template issue, feature issues, temporary glitch in the matrix issue, permissions issue ... etc.

Since I'm on the "basic" account with limited hours, I'm hesitant to randomly spin up different workspaces and try downloading them.  There really isn't any information to begin debugging though.

**Comment by gtsiolis** [comment]
Thanks for opening this issue @tyler36! FYI, downloading is currently not possible while the workspace is running. Providing a better error message could help here.

**Comment by tyler36** [comment]
@shaal , disabling the download link makes sense. Adding a tooltip / popup explaining would improve the user experience. 

At the moment it feels "broken".

**Comment by gtsiolis** [comment]
Re-opening as this is still relevant.

**Comment by jldec** [comment]
This feels broken.

I believe this only applies during the very first workspace start. If you stop and then restart a workspace, the download will return the last saved state even while the workspace is running.

**Comment by JanKoehnlein** [comment]
I am inclined to always disable the download button if the workspace is running, as the user might expect the current state not the last backup. Unfortunately, this is often the last resort  to get at least some data when workspaces are not stopping for whatever reason. Maybe labeling it "Download (latest) backup" would be better and disabling if there is no backup?

**Comment by gtsiolis** [comment]
> I am inclined to always disable the download button if the workspace is running

Agree. We could disable and provide some context on why the button is disabled through a tooltip or a label inline.

Alternatively, we coud remove the download button when downloading is not possible.

FWIW, we have a similar but lower-impact situation when deleting workspaces in `PREPARING` phase, see https://github.com/gitpod-io/gitpod/issues/4173 and https://github.com/gitpod-io/gitpod/pull/5186. Cc @MrSimonEmms

**Comment by tyler36** [comment]
I prefer the option of a disabled button with text explaining why. This shows that the feature is usually available but currently is not because <insert reason here>.

Removing buttons could be seen as removing features.

**Comment by jldec** [comment]
Let's fix the error with minimal additional complexity for now.
- Change Action to "Download Backup"
- Don't change behavior except if there is no backup - ok to omit - better to disable and show tooltip with "no backups".

**Comment by gtsiolis** [comment]
Closing this as we're removing the **workspace download** functionality in the scope of workspace file durability (https://github.com/gitpod-io/gitpod/issues/7901).

See also https://github.com/gitpod-io/gitpod/issues/14364#issuecomment-1301901454:
> Besides ensuring workspace files reliability, this could push us towards figuring out new ways to allow users to export or back up workspace files and more importantly file changes, like exporting in branch, downloading a patch, and more.

Cc @kylos101 @atduarte
