### ISSUE TITLE
Gradle integration features

### ISSUE THREAD

**Issue by danwallach** [gitpod-io/gitpod#498]
Let's say you're pulling in a Java project that has a `build.gradle` file. Today, the only way to interact with Gradle is from the terminal. This certainly works, but it would be nice if:

- Gitpod could extract a list of all the tasks and provide them somewhere on the right column.
- Gitpod could grok the Gradle file layout (e.g., separate directories `src/main` vs. `src/test`) and offer some sort of button to run the unit tests all together or right-click on an individual unit test and run just that.

These are all things that IntelliJ automagically supports as part of its Gradle import process.

**Comment by melaasar** [comment]
It looks like I can find and install the Gradle (VSCode) extension in Gitpod. However, unlike in VSCode, doing this does not show the Gradle side bar. Bug?

**Comment by akosyakov** [comment]
@melaasar It sounds like Theia bug, could you open an issue here: https://github.com/theia-ide/theia

In the meantime we also working on support of alternative IDEs: https://github.com/gitpod-io/gitpod/issues/1780 Including Gitpod version of VS Code. It would allow even better support of VS Code extensions in the future.
