### ISSUE TITLE
[blobserve] String substitution is flakey

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#4992]
### Bug description

Sometimes don't replace the `webview-foreign` string in content served by blobserve.

This is most likely because the string replacement does not happen as part of the synchronised blobspace prep.

### Steps to reproduce

Open enough workspaces

**Comment by akosyakov** [comment]
Im not sure i understood the issue webview-foreign should be replaced by VS Code frontend code, it should not do anything with blobserve.

**Comment by csweichel** [comment]
Excellent point - I just jumped to the conclusion that it's blobserve.

The effect we're seeing is that some things try to make requests to `*.webview-foreign.` i.e. not a proper domain. There's some parts missing that would make this domain resolvable.

**Comment by csweichel** [comment]
Will close for now - let's re-file/re-open this once we have more details on the failure mode.
