### ISSUE TITLE
Include for .gitpod.yml

### ISSUE THREAD

**Issue by ttauchen** [gitpod-io/gitpod#4999]
Dear all,

i love the idea of as you advertise "development environment as a code". Surely at the moment .gitpod.yml already fullfills this promise but lacks the feature of referencing, requiering or including an additional config from other files and more important other repositories.

In our company we will most likely have a lot of rotating projects, restaffed quite often. The type of project and the environment setup can differ trasticly. Never the less we identify some core types of development and would need a base set of 5 environment which we extend if needed.

To make a simple example:
1 environment with extensions for frontend (.frontend.yml)
1 environment with extensions for backend (.backend.yml)
1 environment with extensions for database (.database.yml)

I know that i am able to install tooling with docker. This is about extensions.

Based on my example the per project .gitpod.yml could look like the following:

referencing a file or url
```
include: './paht/to/.frontned.yml'

[...]

```

referencing via GitLab project (most important for us)

```
include:
- project: 'my-group/my-project'
  ref: main
  file: 'path/to/backend.yml'

```

This is inspired by the .gitlab-ci.yml which has even more options to include: https://docs.gitlab.com/ee/ci/yaml/includes.html

For including from antoher repository the user or gitpod obviously would need access rights.

If these are not given gitpod could warn like it does for invalid dockerfiles or configs.

Cheers

**Comment by gtsiolis** [comment]
Thanks @ttauchen for opening and writing this! Let's mark this as a feature request.

Also, cross-linking [a recent relevant discussion](https://community.gitpod.io/t/installing-extensions-in-docker/4337/4) from the community forum. 💬
