### ISSUE TITLE
How to use on a standard laravel project?

### ISSUE THREAD

**Issue by philippejadin** [gitpod-io/gitpod#500]
Hello, really nice tool already! I'd need guidance on how to use it for a laravel project :

- how to have access to a mysql db (is it provided in the default docker image "full"? What are the credentials?)
- I need two additional php extensions, mcrypt and mbstring, how to add them ?

...then I hope to be able to composer install, php artisan stuff

I'm almost there, but having no previous docker experience, it's the latest 1% that's hard and might be useful to add to the docs. How to use gitpod from a to z on a laravel project :-)

The laravel project I'm attempting to gitpodize is here : https://github.com/philippejadin/agorakit

I'd LOVE to make the life of fuure Agorakit developers easier using Gitpod so I commit to document the process as soon as it will work.

**Comment by svenefftinge** [comment]
There is a demo project: https://github.com/meysholdt/laravel-apache-mysql-php-in-gitpod-example

@meysholdt is it functional / can you help here?

**Comment by philippejadin** [comment]
I already tried it, but it doesn't adress several things : 
- install missing php extensions
- allow to use in an existing laravel project, where root is the project.
- how to deal with mysql user credentials

Basically, we need to create a correct gitpod file that one can simply drop into an existing laravel project.

In the future, you might detect automagically from composer.json that the project is a laravel one, and provide sane defaults. That would be a killer option.

**Comment by meysholdt** [comment]
hi @philippejadin, I'm happy to help. 

There is actually a lot of interesting work out there:
* [Homestead](https://github.com/laravel/homestead): the official dev environment based on vagrant. There seems to be nothing official based on docker, however :(
* [Laradock](https://github.com/laradock/laradock): community-provided docker images for laravel-dev-environments. Unfortunately, this seems to be one docker-file per dependency. They are intended to be combined using docker-compose. 
* projects like [shincoder/homestead-docker](https://github.com/shincoder/homestead-docker), which aim to re-build homestead in docker. They seem to cover only a tiny subset of the original.

**Comment by philippejadin** [comment]
Thanks for the links. Then my question is : is it possible to use something like docker-compose on gitpod? Because else I don't see how to add mysql cleanly?

**Comment by meysholdt** [comment]
That would mean to launch multiple containers when starting your workspace... that's on the roadmap ("sidecar containers") but not yet here. See also for discussion: https://github.com/gitpod-io/gitpod/issues/297.

Today I think the best solution is to improve my example (or a base image) based on [your suggestions](https://github.com/gitpod-io/gitpod/issues/500#issuecomment-485441146).

I was just curious about how other people develop for Laravel and if something could be reused.

**Comment by philippejadin** [comment]
About the laravel way, it's usually not with docker as far as I can tell, and the laradock system seems bloated unfortunately.

On your example can you tell me a little bit how the mysql part works? I'd like to avoid having a separate mysql config file. Can this be done? Also how to define root access and password?

I think I'll find a way for the other stuff  :-)

**Comment by meysholdt** [comment]
I didn't do much for Mysql yet. [This line](https://github.com/meysholdt/laravel-apache-mysql-php-in-gitpod-example/blob/b3182fa2aa46eec3cc20dfc24ce3a23828f592de/Dockerfile#L10) overwrites the default-config with a new file that includes the mysql-config from the git-workspace. If you remove this line the default-config will be taken. 

You may need some `RUN chown -R gitpod:gitpod foobar` in your Dockerfile to set the permissions so that mysql can work even though it runs as `gitpod` users. That's necessary because that's the user you have in the Terminal and it can't be changed yet.

To start the mysql server I think you need to run `mysqld` in the Terminal and you can pass arguments that set the inital password.

**Comment by teirureddo** [comment]
You can try this:
https://github.com/teirureddo/envinits-gitpod-php

**Comment by meysholdt** [comment]
I'm working on
- adding Apache and Nginx to the `workspace-full` image: https://github.com/gitpod-io/workspace-images/pull/85
- creating a new image that includes MySQL: https://github.com/gitpod-io/workspace-images/pull/88

Hopefully, with those changes in place, Laravel project will run out-of-the-box.

**Comment by philippejadin** [comment]
This is great! Instead of reinventing the whell, I'll wait for your contributions and report back on how it works from a laravel dev wannabe point of view :-)

**Comment by chapagaiashim** [comment]
Laravel Blade Language support is not available in gitpod. What to do to use blade related extensions?

**Comment by svenefftinge** [comment]
Did you try installing one of these extensions?
https://marketplace.visualstudio.com/search?term=blade&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by obasekietinosa** [comment]
I wrote a guide to how I got Gitpod working with my Laravel project here: https://notes.etin.space/posts/gitpodifying-a-new-laravel-application

**Comment by philippejadin** [comment]
Great step by step guide. Gitpod should have done this months ago. At least
you got it working. Thanks!


--
Philippe Jadin
https://123piano.com
https://fablabke.be
https://agorakit.org

**Comment by obasekietinosa** [comment]
Thank you!
