### ISSUE TITLE
Only prebuilds for the default branch are surfaced on the projects list

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5002]
### Problem to solve

Currently, only prebuilds for the default branch are saurfaced on the projects list (cards).

Screenshots below contain early designs. 🙈 

| Prebuilds | Projects |
|-|-|
| <img width="1380" alt="Screenshot 2021-07-29 at 2 58 54 PM" src="https://user-images.githubusercontent.com/120486/127488386-758cd7a0-e7ba-429c-ba19-a334d0344f87.png"> | <img width="382" alt="Screenshot 2021-07-29 at 2 59 05 PM" src="https://user-images.githubusercontent.com/120486/127488390-d2daee3c-b724-471b-b2f2-019017d1fd33.png"> |

**Comment by AlexTugarev** [comment]
@gtsiolis can you describe what should be rendered instead, please?

**Comment by gtsiolis** [comment]
@AlexTugarev the initial idea was to always surface the latest prebuild on the project card as described in the specs in https://github.com/gitpod-io/gitpod/issues/4420. Does this make more sense to you?

Cross-posting below the relevant specs for visibility.

| Projects |
|-|
| <img width="1440" alt="121364262-4c4aea00-c940-11eb-8f84-135402d14066" src="https://user-images.githubusercontent.com/120486/127490537-8530aaa8-d501-4970-92d9-cdff3166e0b1.png"> |
