### ISSUE TITLE
GKE cluster-scheduler decides too late to scale up

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5006]
We just had a case where image-builds did not run because not enough resources (aka nodes) were available. 

When [looking at the logs](https://console.cloud.google.com/logs/query;query=%2528resource.labels.cluster_name%3D%22prod-meta-eu01%22%0AjsonPayload.message%3D%22scheduling%20a%20pod%20failed:%20Unschedulable%22%2529%0AOR%0A%2528resource.labels.project_id%3D%22gitpod-191109%22%0Aresource.labels.cluster_name%3D%22prod-meta-eu01%22%0AlogName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcontainer.googleapis.com%252Fcluster-autoscaler-visibility%22%20severity%3E%3DDEFAULT%0AjsonPayload.decision.decideTime!%3Dnull%0A%2529;timeRange=2021-07-29T13:40:00.000Z%2F2021-07-29T14:26:00.000Z;cursorTimestamp=2021-07-29T14:25:06Z?project=gitpod-191109) we can see this timeline
* 15:43:07: first "[Unschedulable](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-07-29T13:43:56Z;query=%2528resource.labels.cluster_name%3D%22prod-meta-eu01%22%0AjsonPayload.message%3D%22scheduling%20a%20pod%20failed:%20Unschedulable%22%2529%0AOR%0A%2528resource.labels.project_id%3D%22gitpod-191109%22%0Aresource.labels.cluster_name%3D%22prod-meta-eu01%22%0AlogName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcontainer.googleapis.com%252Fcluster-autoscaler-visibility%22%20severity%3E%3DDEFAULT%0AjsonPayload.decision.decideTime!%3Dnull%0A%2529%0Atimestamp%3D%222021-07-29T13:43:07Z%22%0AinsertId%3D%2222sup09n8qqx2mu1%22;timeRange=2021-07-29T13:40:00.000Z%2F2021-07-29T14:26:00.000Z?project=gitpod-191109)" error from ws-scheduler.
* 16:07:52: the [cluster-autoscaler decides to scale up](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-07-29T14:07:55Z;query=%2528resource.labels.cluster_name%3D%22prod-meta-eu01%22%0AjsonPayload.message%3D%22scheduling%20a%20pod%20failed:%20Unschedulable%22%2529%0AOR%0A%2528resource.labels.project_id%3D%22gitpod-191109%22%0Aresource.labels.cluster_name%3D%22prod-meta-eu01%22%0AlogName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcontainer.googleapis.com%252Fcluster-autoscaler-visibility%22%20severity%3E%3DDEFAULT%0AjsonPayload.decision.decideTime!%3Dnull%0A%2529%0Atimestamp%3D%222021-07-29T14:07:52.801110153Z%22%0AinsertId%3D%22c63d16df-4a3d-419e-8fcb-2036971ef716@a1%22;timeRange=2021-07-29T13:40:00.000Z%2F2021-07-29T14:26:00.000Z?project=gitpod-191109). This is just decision point, the new node becomes available later after it has started.

in a picture: The tiny blue dot is the decision. The yellow bars are "Unschedulable" warnings.
![image](https://user-images.githubusercontent.com/239422/127510609-3048d0c0-d778-4059-a8ee-b004284b9dfb.png)

<details>
(resource.labels.cluster_name="prod-meta-eu01"
jsonPayload.message="scheduling a pod failed: Unschedulable")
OR
(resource.labels.project_id="gitpod-191109"
resource.labels.cluster_name="prod-meta-eu01"
logName="projects/gitpod-191109/logs/container.googleapis.com%2Fcluster-autoscaler-visibility" severity>=DEFAULT
jsonPayload.decision.decideTime!=null
)
</details>

Actual: The cluster-autoscaler took around 25min to notice that new nodes are needed. 
Expectation: The cluster-autoscaler should have noticed instantly. 

We noticed that when deploying image-builder-mk3 to prod, but I don't think this issue is specific to image-builder. Much rather, I assume this is about the interplay of ws-scheduler and the k8s-cluster-autoscaler.

**Comment by meysholdt** [comment]
I assume the cluster-autoscaler does indeed see the "Unschedulable" pods without delay, because the following curves overlay nicely. If there would be a delay one curve would have been shifted. 

![image](https://user-images.githubusercontent.com/239422/127523813-ef2d27e7-f58f-4c18-9aee-90ed615d4f2e.png)

<details>
sum(kube_pod_status_unschedulable{cluster="prod-meta-eu01"})
sum(gitpod_ws_scheduler_pending_pods{cluster="prod-meta-eu01"})
</details>

**Comment by meysholdt** [comment]
Same graph, but with the scale-up as blue line. I've scaled the line by factor 10 to make the effect more visible.

![image](https://user-images.githubusercontent.com/239422/127528433-de8d4853-4470-4500-9030-6084ba19e5d9.png)

**Comment by csweichel** [comment]
This is not an application problem, but rather an infrastructure one. The scheduler produces the regular Kubernetes signals. 

If we want to improve this situation, we need to schedule more ghosts, tune the scalar or use a different one.
