### ISSUE TITLE
Is it possible to use Powershell terminal in Gitpod?

### ISSUE THREAD

**Issue by danBamikiya** [gitpod-io/gitpod#5018]
I'll like to be able to run my Powershell scripts in Gitpod. Is that possible? If it is not when will it be possible?

**Comment by ghuntley** [comment]
> I'll like to be able to run my Powershell scripts in Gitpod. Is that possible? If it is not when will it be possible?

Yes, it is possible.

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7.1

**Comment by danBamikiya** [comment]
@ghuntley Thanks!
