### ISSUE TITLE
Add empty state for project prebuilds

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5022]
### Problem to solve

Currently, when adding a project in a team a) the product does not surface previous prebuilds and b) the project may not have any previous prebuilds.

### Proposal

To avoid having empty pages where it's not clear if the data does not exist or an error occurred while fetching the data we could add an empty state for the prebuilds page when adding a project.

A good first MVC (Minimum Viable Change) could be to reuse the same logic we've used in https://github.com/gitpod-io/gitpod/pull/4571 when searching members returns no members.

https://github.com/gitpod-io/gitpod/blob/76617033726ccc8983f438a333aed00cc0694d7a/components/dashboard/src/teams/Members.tsx#L151

Two more things to consider in this scope:
1. The same could apply when a project is an empty repository and does not contain any active braches. 💡 
2. The same component could be used when searching for branches or prebuilds returns no results. 💡 

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="Prebuilds BEFORE" src="https://user-images.githubusercontent.com/120486/127655820-1437c8c3-7d49-4e8a-aa9e-e35562f8680f.png"> | <img width="1440" alt="Prebuilds AFTER" src="https://user-images.githubusercontent.com/120486/127655821-5a9a214d-b96d-4489-8005-bb31145fdfda.png"> |

**Comment by gtsiolis** [comment]
Marking this as never stale.

**Comment by laushinka** [comment]
Also tackled in https://github.com/gitpod-io/gitpod/pull/7882

**Comment by gtsiolis** [comment]
Closing this as it was resolved in #7882. Thanks @laushinka! 🏀
