### ISSUE TITLE
`Docker-compose pause` not working

### ISSUE THREAD

**Issue by danBamikiya** [gitpod-io/gitpod#5027]
### Bug description

I tried to pause my docker containers using `docker-compose pause` but it didn't pause. The errors it showed were:

`ERROR: for cuttlink_server  Cannot pause container 0de80443d2007f1c0accd5c04a84d087320a0bcb596961dbe16f793da615e2b3: OCI runtime pause failed: cannot toggle freezer: cgroups not configured for container: unknown`

### Steps to reproduce

Run a container using docker-compose then try to pause it using `docker-compose pause`

### Expected behavior

It should pause my container

### Example repository

It's a private repo.

**Comment by pawlean** [comment]
I've been able to replicate this issue myself @danBamikiya - thanks for raising it. I've marked it as a bug for Engineering to have a closer look at :)

**Comment by danBamikiya** [comment]
@pawlean Thanks!

**Comment by semiautomatix** [comment]
Was there ever a solution for docker-compose? I'm getting a similar issue:

```
API error (500): Cannot pause container 9dc5f1e36d172f9c72a5fd839abc859da2ee9a747b8ffaf9bb4380825e6a0fed: OCI runtime pause failed: cannot toggle freezer: cgroups not configured for container: unknown
```

**Comment by atduarte** [comment]
I was able to reproduce by trying to run `docker-compose pause` on https://github.com/gitpod-io/template-docker-compose

**Comment by semiautomatix** [comment]
Thanks for getting this back in play, it took me some time to discover my code was not to blame :-)

**Comment by utam0k** [comment]
> Do we have an approximate timeline on the switch to cgroup v2? I'm presently sticking with Gitpod, but will have to, at the very least, switch to local development until this happens.

We are currently moving to cgroup v2. And pause/unpause worked properly in the new environment of cgroup v2. Please wait for a while.

**Comment by utam0k** [comment]
Now, we are working with cgroup v2 on SaaS, and the pause/unpause command looks fine.
