### ISSUE TITLE
Make registry-facade and image-builder provide the new base image annotation

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5028]
This would greatly help debug the base image chain of images running in a gitpod installation: https://github.com/ImJasonH/ImJasonH/tree/main/articles/oci-base-image-annotations

**Comment by aledbf** [comment]
[Link to pre-defined annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) (already contains the mentioned annotation in the previous link)
