### ISSUE TITLE
Allow usage of private osix registry via the extension ui + gitpod file

### ISSUE THREAD

**Issue by ntziolis** [gitpod-io/gitpod#5031]
As of now the extension plugin seems hardwired to use the public open vsix registry. It would be greatly beneficial to also allow leveraging a private feed as well.

For starters it would be sufficient if it would be possible to override registry url via environment variables `GITPOD_VSIX_REGISTRY_URL` or similar, while defaulting to open vsix when not set.

This would allow users to host their own [openvsix instance ](https://github.com/eclipse/openvsx) while leveraging the public open vsix registry as upstream source.

**Comment by akosyakov** [comment]
I don't think it is fixed. We have a proxy right now but it always works against open-vsx.org

**Comment by corneliusludmann** [comment]
You can set the host of the OpenVSX instance in the `values.yaml` file:

https://github.com/gitpod-io/gitpod/blob/cfb528c5daf5115b666ec7404bfe25d9fc9598d6/chart/values.yaml#L137

Please give it a try!

**Comment by akosyakov** [comment]
@corneliusludmann Do you mean in self hosted? I am not sure whether this issue about self hosting or allow on gitpod.io for some repos. @ntziolis could you clarify?

**Comment by ntziolis** [comment]
We have enterprise customers that have a policy that only allows them to deploy extensions from sources they fully control. Meaning they will be running their own ovsx instance that largely just uses the public open vsx as upstream source but with an approval process attached.

This is not a requirement we can control and that we have seen in lots of enterprise customers in Germany.

**Comment by jgallucci32** [comment]
This is a great request and there is tremendous value for self-hosted installed behind slow company firewalls. One advantage here is you can use something like Artifactory or Nexus to act as a remote repository for open-vsx.org to be able to cache on-demand at scale. I'm going to see if I can manually test this on 0.10.0 since the IDE replacement commands seem simple enough to put in manually. Can't wait to test this in the next release of self-hosted.

**Comment by corneliusludmann** [comment]
Indeed, we needed to change the config. The new config looks like this:

https://github.com/gitpod-io/gitpod/blob/37435335ae86eef44eb9fee7f53f62b7e156c8e1/chart/values.yaml#L437-L462

I'll suggest a change at https://github.com/gitpod-io/website/pull/1058.

**Comment by ntziolis** [comment]
@ghuntley First of let me say this requirement is born out of enterprise process and regulation stupidity.

Lets forget gitpod for a second and think node packages:
- a lot of enterprises we work with do not allow installing directly from the public npm registry
- their corporate IT demands that a private npm registry is used
- that said the npm feed uses the public npm feed as upstream source
- this allows corporate IT to control the packages and versions that developers within the enterprise can use
- and also insure business continuity should the public npm registry be not available anymore at some point in the future

The exact same reasoning applies to ANY third party library/component feed developers are using. Hence the request to set a custom vsix registry.

Why not use the hosted version with a custom vsix:
- before enterprises do not understand the benefit they are not going to make the jump to a hosted version
  - it might suprise that they would let their code move outside controlled IT environment (public gitpod)
  - but by now they are already used to having their code reside on shared infrastructure 
- so the goal would be to lower the barrier of entry
- that said at some point the enterprises we work with would very likely migrate to a hosted version to gain more control

**Comment by ntziolis** [comment]
@jgallucci32 Sry for skipping over your comment earlier. If I understood correctly you plan to support private repositories / feds via the third party artifactory service? If I misunderstood that point most of what I have written below is mood.

I think providing any path is already a huge step forward. That said I do foresee considerable push back from enterprise clients if they are not already using artifactory. They usually already have package / container registry services in place with respective approval processes build on top.

Question:
- Could artifactory be configured to use their existing private registries as upstream source? While not optimal this might provide a path for some customers.

That said, the best solution would be for them to be able to connect to their existing registries infrastructure directly (authenticated).

Note:
- I fully understand that leveraging artifactory as single point of integration would reduce the implementation overhead on your end significantly and I think it would remove the blocker for us. 
- Thinking about it there might be an opportunity to bundle (transparently) artifactory with gitpod
   - provide a simple UI that lets customers provide the details for their upstream registries 
   - you pass through the fee for using private repositories 
   - customers dont have to deal with another third party (enterprises hate adding third parties to their suppliers)
   - and for customers that already have artifactory they can just 'connect' their account

**Comment by jgallucci32** [comment]
@ntziolis Yes you understood that correctly, you can support private repositories using Artifactory as a third party service using the workaround I posted earlier. The configuration is not limited to Artifactory, and should be able to support other common enterprise repositories tools such as Sonatype Nexus. If authentication is required, the api keys could be added to the nginx.conf to support that requirement. We have been using this setup in product for over 3 weeks with Gitpod v0.10.0 and so far have not had any issues with the nginx reverse proxy setup to Artifactory.

I'm not sure I would want to bundle Artifactory with Gitpod as that would limit support to a single tool, rather I think it would be better to have the nginx.conf reverse proxy I created added as an endpoint within the gitpod deployment which would then point to an existing enterprise repository already running within the enterprise. (Of course Caddy could probably be used in place of Nginx, I just have never used Caddy before)

Hit us up on Discord in the self-hosted channels if you want to discuss this further.
