### ISSUE TITLE
[dashboard] Gracefully handle connection disposal

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#5042]
### Bug description

Loading a workspace took very long time, at the end I got this:
![image](https://user-images.githubusercontent.com/22901/127903490-1a1f5c68-2a40-484d-9eb5-ad56c7279343.png)

### Steps to reproduce

It happened only once; But I've never seen it before.
I was able to open the URL in a new tab and it worked as expected.

This is the URL:
https://gitpod.io/#DP_PROJECT_NAME=feeds_ex,DP_ISSUE_FORK=feeds_ex-3025848,DP_ISSUE_BRANCH=3025848-context-examples-with-code,DP_PROJECT_TYPE=project_module,DP_MODULE_VERSION=8.x-1.x,DP_CORE_VERSION=9.2.0,DP_PATCH_FILE=,DP_INSTALL_PROFILE=standard/https://github.com/shaal/drupalpod

### Expected behavior

It would be awesome to know what is going on while it's happening, why a workspace takes long, what part of it got stuck, is it something I did wrong, or a glitch in the system. I'm just happy it only happened once :)

### Example repository

https://gitpod.io/#DP_PROJECT_NAME=feeds_ex,DP_ISSUE_FORK=feeds_ex-3025848,DP_ISSUE_BRANCH=3025848-context-examples-with-code,DP_PROJECT_TYPE=project_module,DP_MODULE_VERSION=8.x-1.x,DP_CORE_VERSION=9.2.0,DP_PATCH_FILE=,DP_INSTALL_PROFILE=standard/https://github.com/shaal/drupalpod

**Comment by jankeromnes** [comment]
Hi @shaal! Thanks for raising this issue. 😁

I believe that "Connection got disposed" is an error that typically gets logged by the front-end when it cannot reach the back-end at all (e.g. when there is an Internet outage, or even a brief network flake out).

I was able to reproduce it by loading the dashboard, then turning off my laptop wifi, and then trying to navigate to a different page & back.

**Comment by akosyakov** [comment]
Probably dashboard should handle reconnections more gracefully.

**Comment by akosyakov** [comment]
I got the same today as well.

**Comment by AlexTugarev** [comment]
Looking at the [code](https://github.com/gitpod-io/gitpod/blob/08361795be7298d06caf306840b8ae5b4bc605fb/components/dashboard/src/start/StartPage.tsx#L99) this is not a websocket connection issue at all. 

 That error is propagated from server to the frontend.
