### ISSUE TITLE
help with gitpod self-hosted on k3s

### ISSUE THREAD

**Issue by jasonrandrews** [gitpod-io/gitpod#5046]
### Bug description

I'm trying to follow the [example for self-hosted on k3s](https://github.com/gitpod-io/gitpod/tree/main/install/docker/examples/gitpod). 

I have generated the random keys and put them in values/minio-secrets.yaml and generated the certificates for my custom domain and put them in the certs/ directory. 

After running docker-compose up I can connect to the domain with my browser and see gitpod is running as expected. I'm able setup the git integration with GitHub using oauth but can’t start any workspaces.

When trying to start a workspace the error is:

Request createWorkspace failed with message: 14 UNAVAILABLE: No connection established
Unknown Error: { "code": -32603 }

Looking at the logs I see this error which may be related. 
secret.go:195] Couldn't get secret default/image-builder-registry-secret: secret "image-builder-registry-secret" not found

Any tips, additional documentation, or blogs to get this running on version 0.10.0 would be appreciated. 

### Steps to reproduce

Run 

$ docker-compose up 

in the gitpod/install/docker/examples/gitpod directory.

**Comment by ghuntley** [comment]
Howdy Jason!

The `gitpod/install/*` folder is in a state of flux at the moment and I would recommend avoiding it - apologies for the time wasted will keep this issue open to track the need for improvements. Here are three solid resources for Gitpod Self-Hosted v0.10.0 with k3s:

- https://github.com/corneliusludmann/gitpod-k3s-droplet (what I use personally!)
- https://www.gitpod.io/docs/self-hosted/latest/installation/on-kubernetes
- https://www.gitpod.io/docs/self-hosted/latest/installation/on-amazon-eks

**Comment by ghuntley** [comment]
👋 @jasonrandrews. I'm closing out this issue but would love to see you over in the #gitpod-self-hosted room at https://www.gitpod.io/chat

Have opened the following housekeeping PR's so others don't experience the problems you did:
- https://github.com/gitpod-io/gitpod/pull/5144
- https://github.com/gitpod-io/gitpod/pull/5145
