### ISSUE TITLE
Gitpod + Flutter support

### ISSUE THREAD

**Issue by VinayBaviri** [gitpod-io/gitpod#5047]
Hii guys,

I recently started flutter and moved it to gitpod. Firstly i faced issue with syntax highlighting. By seeing the previous posts, added extensions and its works fine. But now, i can't able to navigate in the code base. Ex: If i use className.methodName() in one file and if i try to goto method definition by ctrl+click on that method name. Its not working. Also, flutter auto suggestions also not coming while coding. Can anyone help me to get out of it !!!

Thanks in advance.

**Comment by akosyakov** [comment]
@VinayBaviri Can you share your repo?

**Comment by VinayBaviri** [comment]
Hii @akosyakov , 

created one sample repo. U can find here
https://github.com/VinayBaviri/flutter-app/blob/master/FLUTTER/lib/main.dart.
 
Briefly,  
created one sample widget and using inside of main.dart file. Now i want to navigate to sample widget definition from main.dart file it self.

**Comment by sr229** [comment]
@VinayBaviri can you also provide your reproduction steps and the addons you have used? It seems to be an issue regarding not having the appropriate VSIX extensions rather than Gitpod itself.
