### ISSUE TITLE
gitpod.yml command: `npm install` its running to early

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#505]
**Describe the bug**
When a new fresh clone starts I get the error `webpack-dev-server: not found` but if I try doing webpack-dev-server manually it does work.

My guess is that the `command` are running before the `init` finishes.

This is the repo: https://github.com/alesanchezr/vanillajs-hello

**To Reproduce**
Open this repo in github: https://github.com/alesanchezr/vanillajs-hello

**Expected behavior**
Having webpack dev-server to start and first build.

**Comment by AlexTugarev** [comment]
Hey @alesanchezr! Please have a look at https://github.com/alesanchezr/vanillajs-hello/pull/1 :-) Enjoy Gitpod!

**Comment by alesanchezr** [comment]
Oh, thanks @AlexTugarev! It works 👏

I'm enjoying a lot, this webpack+vanillajs boilerplate is ready and will always be maintained. Here is the link:
https://github.com/4GeeksAcademy/vanillajs-hello

If anyone wants to use it, it comes with the following features:
- Gitpod ready.
- Run `npm run deploy` to deploy to github pages.
- Prettier.
- Latest version of standard ES6.

**Comment by AlexTugarev** [comment]
That's look awesome!  ⭐️
