### ISSUE TITLE
Unable to delete workspace olive-eel-5r07flcd after 6 days (and counting)

### ISSUE THREAD

**Issue by etmmafl** [gitpod-io/gitpod#5053]
### Bug description

The DELETE button doesn't work on this workspace

![image](https://user-images.githubusercontent.com/19225255/128174020-55343d35-14b3-48cb-94a3-967163cd2614.png)
![image](https://user-images.githubusercontent.com/19225255/128173975-d93cf7dd-e578-4faa-b41a-ce4a9f460f51.png)

### Steps to reproduce

not sure

### Expected behavior

just delete the workspace

**Comment by pawlean** [comment]
I was unable to replicate this issue but I've seen that another user has +1 your issue so I've added a bug label. Engineering should be able to investigate further, thanks!
