### ISSUE TITLE
No syntax highlighting with broken extensions

### ISSUE THREAD

**Issue by izzqz** [gitpod-io/gitpod#5057]
### Bug description

When I open example pod, https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node. Syntax highlighting broken. And extensions page has infinity loading.

![image](https://user-images.githubusercontent.com/35831725/128219045-8fc0eb55-15d5-41e5-914e-31aadf2be523.png)

Looks the same as closed https://github.com/gitpod-io/gitpod/issues/2695, https://github.com/gitpod-io/gitpod/issues/2444, https://github.com/gitpod-io/gitpod/issues/1291

### Steps to reproduce

Open example pod: 
https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node
*also has shared snapshot* 
https://turquoise-puma-18p8zl0r.ws-eu14.gitpod.io/

Maybe only on Pixelbook Go

### Expected behavior

Working syntax highlighting and extensions

### Anything else?

Running on Google Pixelbook Go with `Intel(R) Core(TM) i5-8200Y CPU @ 1.30GHz`
OS Version: 91.13904.0

---

Browser console export: [**console.log**](https://github.com/gitpod-io/gitpod/files/6932941/console.log)

**Comment by akosyakov** [comment]
Please check that you don't use any add blocking extensions, firewalls or antivirus software which can intervene with traffic.

**Comment by akosyakov** [comment]
I think it is a dup of https://github.com/gitpod-io/gitpod/issues/4391 Please reopen if not

**Comment by izzqz** [comment]
> Please check that you don't use any add blocking extensions, firewalls or antivirus software which can intervene with traffic.

Yeah, it's a dub. Removing ETag filtering in ClearURLs works well.
