### ISSUE TITLE
Error when using helm install

### ISSUE THREAD

**Issue by ryo-egch** [gitpod-io/gitpod#5059]
### Bug description

following document, https://www.gitpod.io/docs/self-hosted/latest/installation/on-kubernetes  running
> $ helm install -f values.custom.yaml gitpod gitpod.io/gitpod --version=0.10.0

showed error
```Error: parse error at (gitpod/templates/proxy-configmap.yaml:43): function "bcrypt" not defined```

### Steps to reproduce

> $ helm install -f values.custom.yaml gitpod gitpod.io/gitpod --version=0.10.0

### Anything else?
GKE cluster
 - currentMasterVersion: 1.20.8-gke.900
 - node
     -  imageType: UBUNTU
     - machineType: e2-standard-2

**Comment by ghuntley** [comment]
👋 @ryo-egch can you please share your `values.custom.yaml` via https://gitpod.sendsafely.com/dropzone/support? Then let me know the file upload identifier!

**Comment by ryo-egch** [comment]
I upload values.custom.yaml I made;  # 4ZK6-DB41

**Comment by MrSimonEmms** [comment]
I'm finding this when running v0.10.0 in K3S. In the meantime, v0.9.0 works on K3S as the change was introduced the day after v0.9.0 was published.

Also, https://community.gitpod.io/t/self-hosted-helm-bcrypt-error/4534
