### ISSUE TITLE
remove deleted users from customer.io

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#5061]
**Problem**
Currently, we just mark deleted users with "deleted at" in customer.io. By that, we keep their "dead" profiles and also continue paying for them. But more importantly, according to GDPR, we are obliged to delete all user data after their deletion "Under GDPR, data controllers and processors are obliged to return or delete all personal data after the end of services, or on expiry of a contract or agreement, unless it's necessary to retain the data by law." 

**Possible solution**
Use API endpoints instead of the `deleted at` attribute
See [docs](https://customer.io/docs/deleting-users/)

**Remaining questions**
- What happens to the historic user data? Is it deleted when the profile is deleted or can it persist anonymously? 

cc @atduarte

**Comment by jakobhero** [comment]
I have chatted with the customer support of customer.io to address this issue. The takeaways are:

1. Metrics will maintain the activities of deleted users
2. The deletion of users in customer.io cannot be done with workflow actions, but the API call to delete the user can be made from a [webhook action](https://customer.io/docs/webhooks-action/#creating-a-webhook-action) inside of customer.io. I will have a look at implementing this today or tomorrow.

**Comment by jakobhero** [comment]
**UPDATE**
Users are automatically deleted through a [campaign](https://fly.customer.io/env/106338/campaigns/9/overview?channels=email_webhook) in customer.io that is triggered everytime a deletion event comes in and then calls the deletion endpoint of customer.io.
What still remains is to clean up the users that are marked as deleted (`deleted_at` attribute is set). I will tackle this in the afternoon or tomorrow.

**Comment by jakobhero** [comment]
**UPDATE #2**
Cleaned up all 461 users marked as deleted from customer.io. Closing this issue.
