### ISSUE TITLE
Prebuilds are not always associated with the correct project

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5065]
### Problem to solve

@AlexTugarev mentioned that prebuilds are not always associated with the correct project. This is visible only with multiple projects (usually more than two). Cc @jankeromnes

**Comment by gtsiolis** [comment]
@AlexTugarev I could not reproduce this but let's keep this open to track the issue and keep an eye in case this happens again. 👀

**Comment by AlexTugarev** [comment]
@gtsiolis, the effect of this bug is that you won't see prebuilds on https://gitpod-staging.com/gitpod-io/gitpod/prebuilds

**Comment by gtsiolis** [comment]
Ah, ok! Thanks for clarifying @AlexTugarev! I can confirm this! ✔️
