### ISSUE TITLE
Allow users to rename teams

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5067]
### Problem to solve

The upcoming changes for Teams & Projects do not include a way to rename a team.

### Proposal

In the long run, having team settings could be interesting and also a good place to surface a team rename action. However, a minimum viable change (MVC) for this could be to a) add a more actions button next to the primary action button on the team page (projects list) and b) trigger a confirmation modal to rename a team. See also closely related issue about deleting teams in https://github.com/gitpod-io/gitpod/issues/5066 for specs.

**Comment by svenefftinge** [comment]
I think introducing a settings page isn't big effort and would make the UX symmetrical. See also https://github.com/gitpod-io/gitpod/issues/5066

**Comment by gtsiolis** [comment]
Cc @jldec for visibility.
