### ISSUE TITLE
Allow instance admins to manage teams and projects

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5069]
### Problem to solve

For instance admins, it could help to surface all instance teams and projects in the _Admin_ pages as this could be helpful for debugging issues or helping out users.

**Comment by gtsiolis** [comment]
Definitely still relevant.

**Comment by jldec** [comment]
Closing in favor of epic #7597 and issue #7636

**Comment by gtsiolis** [comment]
@jldec Maybe it's worth considering repurposing this issue by limiting the scope to searching teams, since we're probably going to need a separate issue about searching teams, right? 🏓
