### ISSUE TITLE
Suspicion: broken IWS after ws-daemon restart

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5079]
### Bug description

It seems that when ws-daemon restarts it either doesn't serve IWS of existing workspaces, or workspacekit does not reconnect to the new IWS.

This results in non-functional Docker daemon and failing workspace teardown. Probably the cause of #4955 

### Steps to reproduce

1. Start a workspace
2. Restart ws-daemon
3. Try `docker run ...`

**Comment by csweichel** [comment]
The assumption was that this rarely to never happens in prod. We've recently seen ws-daemon failures though due to containerd failures.

Hence this issue is likely to impact users directly.

**Comment by jankeromnes** [comment]
> broken IWS

> doesn't serve IWS of existing workspaces

> reconnect to the new IWS

For transparency, what does "IWS" mean here?

_(Also, please [always avoid acronyms](https://gist.github.com/anonymous/ca9721fbf27e77667abb) 😇🙏)_
