### ISSUE TITLE
"Just prefix" to start does not work

### ISSUE THREAD

**Issue by rugk** [gitpod-io/gitpod#508]
**Describe the bug**

Your video explains, at the end, that you can just prefix a GitHub URL with the domain + hash and it is supposed to work.

Instead, it just shows me the home page… https://www.gitpod.io/

**To Reproduce**

Access this URL:
https://www.gitpod.io/#https://github.com/rugk/offline-qr-code/

Firefox 68

**Expected behavior**

Note: I did actually open the URL in a new tab, but it did not do anything. (I would have understood the issue if I just change the current URL, as that does not reload the site. But, anyway, you may need to check for that, too.)

---

no console errors visible:
![image](https://user-images.githubusercontent.com/11966684/56607617-47643880-6609-11e9-8aca-c0ef02884002.png)

**Comment by AlexTugarev** [comment]
Hi @rugk!

Please use just `gitpod.io/#` (without the `www`) as prefix.

We're are aware that this could be improved, see https://github.com/gitpod-io/gitpod/issues/478.

**Comment by rugk** [comment]
ugh, yeah, this is not a great UX :laughing:

**Comment by jankeromnes** [comment]
Hi @rugk! Sorry about the confusing experience, and thanks for reporting the bug!

FYI we'd like to also make the `www.gitpod.io` website properly handle repository prefixes, see https://github.com/gitpod-io/website/issues/43. I haven't had time to get to it yet.
