### ISSUE TITLE
Start recovery environment if `image:` in .gitpod.yml is incorrect

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5088]
Hey folks,

Currently, if something is wrong with the .gitpod.yml the user experience is this.

<img width="1004" alt="2021-08-06_19-55-50" src="https://user-images.githubusercontent.com/127353/128493268-051e5671-2c6e-4a4f-9ba3-c7f2c064d980.png">

It would be rad if there was a button that said "start recovery environment" (ie. workspace-full) so that the problem could be fixed in Gitpod instead of having to use "edit file in GitHub"

**Comment by csweichel** [comment]
we have this kind of "recovery environment" in other situations already, namely when the image build fails or the gitpod.yml is invalid. We could re-use the same wording and behaviour.

**Comment by ghuntley** [comment]
Agreed
