### ISSUE TITLE
Terminal sometimes has duplicate keypresses

### ISSUE THREAD

**Issue by lutzky** [gitpod-io/gitpod#5099]
### Bug description

The terminal sometimes repeats keystrokes. This doesn't always happen, but it's common enough to get me typing things like `git puush` or `export WRONG_ENV_VAARRIABLE`. This only occurs in the terminal - the text editor doesn't exhibit this bug.

### Steps to reproduce

In the terminal, type "ababab..." repeated. This yields:

    ababababababababababbabbabbababbababbabbabbabaabbababbababbabbaabbaabbaabbaab

So, not entirely consistent, but consistent enough to be annoying.

### Expected behavior

Expecting to see:

    abababababababababababababababababababababababababababababababababababab

### Anything else?

Interestingly, this reproduces on Chrome 92.0.4515.107 on Ubuntu 21.04, but not on my Chromebox nor Chromebook.

**Comment by bstachmann** [comment]
Same for me: `git staattus git staatuus git status`. Only happens when typing fast. Only happens in the terminal. Editor is fine.

Ubuntu 20.10, Chrome is also Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by bstachmann** [comment]
Workaround: Use Firefox

**Comment by lutzky** [comment]
Confirmed, I cannot (with reasonable effort) reproduce this in Firefox.

**Comment by MrSimonEmms** [comment]
I'm using Ubuntu 21.04 with Chrome 92.0.4515.131 (latest as of 11/08/21) and I can't recreate this issue - is it possible that this has been fixed in a later version of Ubuntu/Chrome? I've tried this in fresh workspace created in Chrome, and an existing workspace created in FF and both the same.

**Comment by lutzky** [comment]
Confirmed, this no longer reproduces for me. In the [chromium changelog](https://chromium.googlesource.com/chromium/src/+log/92.0.4515.107..92.0.4515.131?pretty=fuller&n=10000), the following change stands out as potentially having fixed this, even though the description mentions backspaces specifically, and stuff about IME so I'm not 100% sure this is the thing that fixed it:

https://chromium.googlesource.com/chromium/src/+/7b7932975668e4d97ad6a3666a8fe9e9bca6e958

**Comment by csweichel** [comment]
Thank you @lutzky for the hint 🚀
