### ISSUE TITLE
[server] GITPOD_RESOLVED_EXTENSIONS is not valid json

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5104]
### Bug description

Actually it seems to be another bug, for some reasons GITPOD_RESOLVED_EXTENSIONS is not complete in my repo, so Code Server cannot install extensions:
<img width="1693" alt="Screenshot 2021-08-07 at 12 00 06" src="https://user-images.githubusercontent.com/3082655/128596528-1c1f5643-7848-419a-a3cc-28e030b465e4.png">

@csweichel Could it be that there is some length constraint on value of set env variable?

### Steps to reproduce

Not sure, maybe installing https://open-vsx.org/extension/akosyakov/gitpod-monitor

**Comment by akosyakov** [comment]
Jaeger tracing shows that the server sends a valid JSON to ws-manager.

**Comment by akosyakov** [comment]
I think many users are affected, for some reasons everything after last `=` is stripped. I see the same in GOFLAGS in this repo: https://github.com/gitpod-io/gitpod/blob/ebc8fde83c5c3509bc85a20f4dbf330f06d57a5c/dev/image/Dockerfile#L127

**Comment by akosyakov** [comment]
I see that environ of supervisor is good, but child processes are not.

**Comment by akosyakov** [comment]
It's a regression since https://github.com/gitpod-io/gitpod/pull/4923 We use `stings.Split` unconstrained.

/schedule

**Comment by roboquat** [comment]
@akosyakov: We have more than 21 cards scheduled. Above 15 only scheduler can perform this action. Those are:
  - csweichel
  - JanKoehnlein


<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5104#issuecomment-894748610):

>It's a regression since https://github.com/gitpod-io/gitpod/pull/4923 We use `stings.Split` unconstrained.
>
>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
