### ISSUE TITLE
slow git blame on files with large history leading to OOM kills

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5110]
### Bug description

Since last 2 weeks I start getting OOM kills while working on https://github.com/gitpod-io/vscode repo. After investigation it turned out that doing some git operations causes git gc/repack which runs for long sometimes and consumes memory. So newly started processes cannot get more memory and gets killed, eventually leading to the workspace eviction. I found several triggers in my settings: (1) i had auto enabled gti fetch, (2) git blame via gitlens, as wells as (3) git push causes git gc from time to time. In particular blaming via GitLens can get unresponsive for minutes. You can see it on the screenshot below:
<img width="1904" alt="Screenshot 2021-08-09 at 07 51 46" src="https://user-images.githubusercontent.com/3082655/128669290-6272b7f1-ba28-4b0c-acb8-1269c0d7bd78.png">

Don't pay attention to htop saying 33.G/62.8G. It does not know about gcroups. Instead have a look at the status bar, it shows almost 100% utilisation of memory limited by cgroups, which is used to trigger OOM kills. It is computed here: https://github.com/akosyakov/gitpod-monitor/blob/96d342a3abb13e6608dbd48fdf9efbc4c0700b55/src/extension.ts#L37-L39

I suspect a cause for it is the partial cloning.

### Steps to reproduce

Install GitLens and use blame on different files in https://github.com/gitpod-io/vscode while running some task terminals. My particular trigger was doing `yarn gitpod-min`.

**Comment by csweichel** [comment]
What happens if you do the same thing on a repo cloned without `--filter`?

**Comment by svenefftinge** [comment]
I can reproduce a super slow `git blame`.
E.g.
```
git blame src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts
```
Takes minutes. I wonder if git has some sort of inflate operation, that would allow us to fetch the blobs async after the content initialization.

**Comment by csweichel** [comment]
> I wonder if git has some sort of inflate operation, that would allow us to fetch the blobs async after the content initialization.

been thinking the same thing - had a look a few days ago while looking into the `origin` issue, but found nothing. That's not to say such an operation doesn't exist, but it doesn't seem to be obvious. If we had such a thing though, we could heuristically inflate things.

Also, we should double check the Git issues. Is this resource demand/bad performance a known issue?

**Comment by svenefftinge** [comment]
Just stumbled over
```
git -c "remote.origin.partialclonefilter=blob:none" fetch --deepen=999999 origin
```
which seems to do the trick. [Source](https://www.spinics.net/lists/git/msg390700.html)

**Comment by csweichel** [comment]
![image](https://user-images.githubusercontent.com/3210701/128673379-f9e1bb11-42cb-4117-8acb-8adc98046933.png)

it does not help when calling `git blame` unfortunately. To my understanding the command above helps when cloning the repo with a tree filter, rather than a blob filter.
Removing the blob filter altogether doesn't help either: `git -c "remote.origin.partialclonefilter=" fetch --deepen=999999 origin`

**Comment by svenefftinge** [comment]
True, I ran it on a repo that was already inflated by running `git blame` on a large file, so  blame on other files were instant afterward. Generally, the inflation wouldn't help us much if we were running it eagerly, because many users would not wait for git clone but for content init from a prebuild. So if we always inflate it we are back to the same size on disk.

**Comment by akosyakov** [comment]
Discussed on the engineering call that to add it to the groundwork inbox to research on the solution which can preserve partial cloning and inflate the workspace afterwards when it is needed. Maybe add a flag in .gipod.yml to enable such inflation for special cases, like this one and https://github.com/gitpod-io/gitpod/issues/4914

**Comment by aledbf** [comment]
Maybe we can make this git feature optional using a setting to the `gitpod.yml` file?

**Comment by JanKoehnlein** [comment]
Let's investigate this with a timebox of one day.

/schedule

**Comment by svenefftinge** [comment]
Agreed, that we should make the partial clone an **opt-in** feature that one can enable through `.gitpod.yml`.

It's too bad this improvement is not transparent enough to make it opt-out, but the impact of not being able to fork (#4914) and sometimes experiencing oom kills and/or long waiting times on git blame is surprising and will leave users with a bad experience. I'd rather compromise on the loading speed than the functional experience.

**Comment by akosyakov** [comment]
VS Code (git) does not allow to commit sometimes because of it:
<img width="1904" alt="Screenshot 2021-08-11 at 10 32 17" src="https://user-images.githubusercontent.com/3082655/128996878-879124fc-9ef0-4836-96f6-890f8620d0d8.png">

**Comment by akosyakov** [comment]
Discussed with @svenefftinge We are reverting it till there is no better solution which does not break blame but most importantly fork.

**Comment by akosyakov** [comment]
partial clone was revered in https://github.com/gitpod-io/gitpod/pull/5152
