### ISSUE TITLE
Add what's new modal entry for teams and projects

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5114]
### Problem to solve

Given the upcoming release of the Teams & Projects feature in the next weeks, it'd be great to use the What's New modal to inform the users about this feature.

### Proposal

Let's add a what's new modal entry for teams and projects.

**Title**: Teams & Projects
**Label**: New Feature
**Paragraph**: TBD (To be discussed)

Additionally, if we could also link to relevant documentation changes[[1](https://www.gitpod.io/docs/teams)] or blog posts[[2](https://www.notion.so/gitpod/Teams-and-Projects-v0-2-30f5705202ac40cb884f7b428e08e381#d980ad0e00b74494a8795044faad25e3)]. 💡

**Comment by gtsiolis** [comment]
Removing assignee until we pick this up again. See also closed PR in https://github.com/gitpod-io/gitpod/pull/5126. Cc @jldec

**Comment by jldec** [comment]
No longer needed - thanks for tracking and for the PR @gtsiolis
