### ISSUE TITLE
Allow users to add projects in teams from self hosted GitLab providers

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5115]
### Problem to solve

The upcoming **Teams & Projects** feature supports adding repositories from GL (`gitlab.com`) and GH (`github.com`) but does not support projects from self hosted GitLab instances.

See also relevant discussion in https://github.com/gitpod-io/gitpod/pull/5113#discussion_r685091660. Cc @AlexTugarev 

### Risks

This would require first to introduce any safety mechanisms that make the dashboard usable even if the self hosted instances go offline. Such mechanisms could include caching information (see https://github.com/gitpod-io/gitpod/issues/5038) or using skeleton loaders to handle any slow connection issues (see https://github.com/gitpod-io/gitpod/issues/5075).

**Comment by AlexTugarev** [comment]
@gtsiolis, I suggest to limit the scope of this issue to self-managed GitLabs. We assume that it will work with little changes, just by relaxing the blocker. 

With GHE things look much different. The configuration part of GItHub Prebuilds requires to generate a key and import it into Gitpod, which is currently supported at deploy-time only.

**Comment by gtsiolis** [comment]
Sounds absolutely reasonable, @AlexTugarev! I've only added this to avoid missing both points. Renamed this issue for GitLab self hosted and opened https://github.com/gitpod-io/gitpod/issues/5297 for supporting GitHub self hosted which I'd think also has a lower priority than this one. 🔅

**Comment by gtsiolis** [comment]
This was recently brought up in our discord server, see [relevant discussion](https://discord.com/channels/816244985187008514/816246578594840586/907316018790166638). Cc @jldec

**Comment by jldec** [comment]
https://github.com/gitpod-io/gitpod/issues/5095#issuecomment-966046337

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5115#issuecomment-982599715):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by AlexTugarev** [comment]
> This would require first to introduce any safety mechanisms that make the dashboard usable even if the self hosted instances go offline.

@gtsiolis, just from re-reading the issue, I don't think tackling these risks is in scope of the [PR](https://github.com/gitpod-io/gitpod/pull/7125) to initially support self-managed GitLab instances. preserving details from remote services is a general improvement not directly depending on the provider.
