### ISSUE TITLE
Mention the user who already imported the repository as a project

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5119]
### Problem to solve

In the upcoming **Teams & Projects** feature, a user can try importing a repository as a project. However, there will be cases where someone on your team, with proper permissions to install the app for GitHub[[1](https://www.gitpod.io/docs/github-integration#enable-prebuilds)] or the hook for GitLab[[2](https://www.gitpod.io/docs/gitlab-integration#enabling-prebuilds)], has already imported a repository as a project.

Curently, there's a text label next to each each project with the label _already taken_. However, there's no indication for who added the project so that you can reach out or make any action.

### Proposal

A good first MVC (minimum viable change) could be to surface the user who already added the repository as a project.

### Designs

| Tooltip on already added projects |
|-|
| <img width="1440" alt="Taken" src="https://user-images.githubusercontent.com/120486/128721110-921467d4-f756-42b6-871b-711ba0d3c889.png"> |

**Comment by jldec** [comment]
Let's do this ™️ 

**1 caveat:** we have to be careful not to expose user information which the user is not already exposing e.g. if say the user's github id is visible, but their email is not visible, it would be better to expose their github id only. 

**nit:** for usability, tooltips that require hovering are not the easiest (esp on touch devices), so making something visibile or clickable is preferable.

**Comment by laushinka** [comment]
I have a stupid question - is it possible to allow anyone with proper permissions to create projects out of the same repos?  Or is this something that the git providers don't let us?

**Comment by jldec** [comment]
We know from user support questions that this is causing problems.
Let's implement the minimal solution to show a team owner name - a tooltip as proposed by @gtsiolis is fine.
