### ISSUE TITLE
Worskpace fails to open with "cannot pull image"

### ISSUE THREAD

**Issue by bravoalpha79** [gitpod-io/gitpod#5132]
### Bug description

Upon student trying to open an existing workspace, the following error is received:

![image](https://user-images.githubusercontent.com/45522344/128842476-634cb4fa-d1de-4158-9fa2-ab1cb50ddeb1.png)

This has been going on since yesterday and this morning again - the workspace was opening normally before that.

### Steps to reproduce

Affected workspace:

https://teal-limpet-fz3ezfxe.ws-us13.gitpod.io/

Note: Gitpod Status logs no outages/incidents in the past 24hrs, so I assume this is workspace-specific.

### Expected behavior

Workspace opens without error.

### Example repository

https://teal-limpet-fz3ezfxe.ws-us13.gitpod.io/
https://github.com/NgiapPuoyKoh/django-blogchat-tech

### Anything else?

This is a student's final project workspace which contains their local DB (gitignored), so creating a duplicate workspace is the last option as it would require rebuilding the DB and the data in it. 
Please try to restore the original workspace.

**Comment by svenefftinge** [comment]
I restored the workspace.

**Comment by bravoalpha79** [comment]
Thank you so much!!

**Comment by NgiapPuoyKoh** [comment]
Reopening this issue
Tried several times to day to start workspace that was restored it is stuck in image build
https://gitpod.io/start/#teal-limpet-fz3ezfxe

**Comment by pawlean** [comment]
> Reopening this issue
> Tried several times to day to start workspace that was restored it is stuck in image build
> https://gitpod.io/start/#teal-limpet-fz3ezfxe

I've just seen your other issue #5188 - we're looking into it!
