### ISSUE TITLE
Workspace sync is breaking the VSCode UI

### ISSUE THREAD

**Issue by suneetk92** [gitpod-io/gitpod#5133]
### Bug description

VSCode UI is not initializing the properly because of setting sync when launching an existing workspace.

![image](https://user-images.githubusercontent.com/12783242/128846207-01b67c31-1dfc-4344-98a2-cae0a0eca90d.png)

### Steps to reproduce

1. Enable VSCode
2. Launch a new workspace. -> First time everything works as expected.
3. Refresh / Relaunch the workspace. -> In the console you will see the error in the console and UI is not loaded properly. 
No ports, no plugins, no user setting.
![image](https://user-images.githubusercontent.com/12783242/128846861-000adab8-a6c1-4b8f-897b-0f461f9f3f04.png)

### Expected behavior

Re launching the workspace should work without any issue. All settings, plugins should be enabled.

### Anything else?

I'm encountering this in a v0.10.0 of self-hosted.

**Comment by suneetk92** [comment]
When I delete all the entries from `d_b_code_sync_resource` table, then on next refresh everything works as expected.

**Comment by suneetk92** [comment]
Also, disabling the "Setting sync" on first time helps.

**Comment by akosyakov** [comment]
Which base image do you use? VS Code does not support alpine.

**Comment by suneetk92** [comment]
> 
> 
> Which base image do you use? VS Code does not support alpine: #3356

image - workspace-full
template - https://github.com/gitpod-io/template-haskell

> 
> Also is it self-hosted or on Gitpod.io?

self-hosted

**Comment by akosyakov** [comment]
You should check Gitpod server logs as well as the output channel for sync can give some clues.

**Comment by suneetk92** [comment]
Looks clean to me.

`/ # kubectl logs -f --tail 0 server-56cdbc46ff-kmqmt server
{"component":"server","severity":"DEBUG","time":"2021-08-10T10:20:22.572Z","environment":"production","region":"local","context":{"userId":"ba325ea3-c768-48cc-917b-7b91053cdb7d"},"message":"clientRegion: undefined"}
{"component":"server","severity":"INFO","time":"2021-08-10T10:20:22.572Z","environment":"production","region":"local","context":{"userId":"ba325ea3-c768-48cc-917b-7b91053cdb7d"},"message":"initializeClient"}
{"component":"server","severity":"DEBUG","time":"2021-08-10T10:20:22.704Z","environment":"production","region":"local","message":"Established listener on ba325ea3-c768-48cc-917b-7b91053cdb7d.*.updates"}
{"component":"server","severity":"DEBUG","time":"2021-08-10T10:20:22.705Z","environment":"production","region":"local","message":"Established listener on ba325ea3-c768-48cc-917b-7b91053cdb7d.*.credit"}
{"component":"server","severity":"INFO","time":"2021-08-10T10:20:22.788Z","environment":"production","region":"local","context":{"userId":"ba325ea3-c768-48cc-917b-7b91053cdb7d"},"message":"getWorkspace"}
{"component":"server","severity":"INFO","time":"2021-08-10T10:20:22.799Z","environment":"production","region":"local","context":{"userId":"ba325ea3-c768-48cc-917b-7b91053cdb7d"},"message":"getTeams"}
{"component":"server","severity":"INFO","time":"2021-08-10T10:20:22.835Z","environment":"production","region":"local","context":{"userId":"ba325ea3-c768-48cc-917b-7b91053cdb7d"},"message":"getLoggedInUser"}
{"component":"server","severity":"INFO","time":"2021-08-10T10:20:23.123Z","environment":"production","region":"local","context":{"userId":"ba325ea3-c768-48cc-917b-7b91053cdb7d"},"message":"sendHeartBeat"}
{"component":"server","severity":"INFO","time":"2021-08-10T10:20:23.123Z","environment":"production","region":"local","context":{"userId":"ba325ea3-c768-48cc-917b-7b91053cdb7d","instanceId":"c792ab60-51c9-47ad-87c1-da18c2670751"},"message":"sendHeartBeat"}
{"component":"server","severity":"INFO","time":"2021-08-10T10:20:23.153Z","environment":"production","region":"local","context":{"userId":"ba325ea3-c768-48cc-917b-7b91053cdb7d","workspaceId":"lime-peacock-oj87i9qs"},"message":"startWorkspace"}
{"component":"server","severity":"INFO","time":"2021-08-10T10:20:23.513Z","environment":"production","region":"local","context":{"userId":"ba325ea3-c768-48cc-917b-7b91053cdb7d"},"message":"getWorkspace"}`

**Comment by suneetk92** [comment]
It's more of a frontend issue. 

In network tab, everything looks fine. all requests has a proper response.

**Comment by akosyakov** [comment]
Your frontend logs says that code-sync server endpoint failed to respond properly. Maybe DB corrupted for some reasons

**Comment by suneetk92** [comment]
I clean wipe everything and setup the gitpod again with buildin mysql, but the results were same. 

First time everything works, in the database I can see all the code-sync reference, all files are available in minio. 

![image](https://user-images.githubusercontent.com/12783242/128858230-6cc0626a-c6d1-4700-9877-e1854de0a470.png)

![image](https://user-images.githubusercontent.com/12783242/128858288-354b4760-5c5d-4fa7-9a75-cd65fb8a1a87.png)


2nd time onwards, the network tab shows the response are proper, but it UI fails to load it properly.

![image](https://user-images.githubusercontent.com/12783242/128858571-a66ae7fd-2e94-491f-812e-55edb06f6ce5.png)

![image](https://user-images.githubusercontent.com/12783242/128858661-f66099ec-00ea-48f7-8d18-e6f0136ba273.png)


My speculation is, first time code had to initialize everything and then push the data to mysql and minio -> it is not reading the data from anywhere. Next time onward, it has to read the data and somehow it is unable to parse the data properly. Maybe the JSON data is not properly stored.

**Comment by akosyakov** [comment]
How response look like in devtools for GET requests?

**Comment by suneetk92** [comment]
2nd times, only extension api is called and then code breaks:
![image](https://user-images.githubusercontent.com/12783242/128866174-11579521-541d-4208-9d49-e179d0dc8cf4.png)


I just tried to remove the `extension` entry from the `d_b_code_sync_resource` and then it is able to load the UI properly.

**Comment by suneetk92** [comment]
https://github.com/gitpod-io/vscode/blob/126b2f5128b5281e5357fcb71728f4f77e9f2bfc/src/vs/platform/userDataSync/common/userDataSyncStoreService.ts#L294

Code is expecting a ETag, which is not available in Minio?

**Comment by suneetk92** [comment]
Settings contain the etag:
![image](https://user-images.githubusercontent.com/12783242/128924500-a1e847be-7e7d-4ea0-bc7f-b84b51912580.png)

globalSettings do not contain etag:
![image](https://user-images.githubusercontent.com/12783242/128924731-d149212f-d965-45be-b5b9-83ca65c55798.png)

**Comment by suneetk92** [comment]
While writing the data, minio is returning the etag
![image](https://user-images.githubusercontent.com/12783242/128926146-87ab27fe-23a7-4cd0-b7a2-729a87f674b0.png)

But it is lost somewhere :(

**Comment by akosyakov** [comment]
Do you use any adblocking software or firewalls which removes etags? See for the context: https://github.com/gitpod-io/gitpod/issues/4391#issuecomment-889545562

**Comment by suneetk92** [comment]
> 
> 
> Do you use any adblocking software or firewalls which removes etags? See for the context: [#4391 (comment)](https://github.com/gitpod-io/gitpod/issues/4391#issuecomment-889545562)

I don't believe so, because `etag` is available for `settings`.

**Comment by suneetk92** [comment]
@akosyakov Thanks for pointing me in right direction. I am able to resolve the issue now.

Issue was because my website is behind cloudflare and certain features in cloudflare remove the ETag - https://support.cloudflare.com/hc/en-us/articles/218505467-Does-CloudFlare-support-ETag-headers-

For me just disabling the Brotli optimization helped.

**Comment by suneetk92** [comment]
We can close this issue now. Thanks again for the reference.
