### ISSUE TITLE
user insight into workspace health

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5134]
Recently I had issues with OOM kills and wrote https://github.com/akosyakov/gitpod-monitor to get overview of memory usage in the workspace. It spawned some discussions to built it in the product to provide better user insights and allow preemptive measurements.

From @csweichel:
> It’s also a good starting point for giving users more insight into their workspace health in general. While this should not be necessary, it unfortunately is. Rather than silently failing, we should provide predictive indicators that can warn users when their workspace is about to fail (OOM killed, won’t get a backup because ws-daemon isn’t present, is being CPU limited, heartbeating failed and workspace might time out).

Aslo form @jankeromnes:
> Cloud9 had 3 minimal "progress bar" indicators for these quota, and an upgrade notification (I've found it helpful, especially when I accidentally filled up my allowed disk space a few times)

We could think of some cli tool which gives user k8s metrics around CPU, memory and disk usages in workspace container. Such tool can be used by IDE as well to provide UI.

**Comment by svenefftinge** [comment]
What is the use case for this? I mean as a user I don't want to be concerned that I run out of resources.

**Comment by akosyakov** [comment]
> What is the use case for this? I mean as a user I don't want to be concerned that I run out of resources.

As a user one wants to know if something eats a lot and be able to optimize. Right now users are blind.
