### ISSUE TITLE
Worskpace fails to open with "cannot pull image"

### ISSUE THREAD

**Issue by stephenavocado** [gitpod-io/gitpod#5138]
### Bug description

Upon trying to open an existing workspace, the following error is received:

Oh, no! Something went wrong!
cannot pull image: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory"

This has been going on since yesterday and this morning again - the workspace was opening normally before that.

### Steps to reproduce

Affected workspace:

https://crimson-hyena-hmalhtbx.ws-us13.gitpod.io/

Note: Gitpod Status logs no outages/incidents in the past 24hrs, so I assume this is workspace-specific.

### Expected behavior

Workspace opens without error.

### Example repository

https://crimson-hyena-hmalhtbx.ws-us13.gitpod.io/

### Anything else?

This workspace is really important and I needed to access it for a deadline coming up this sunday - is there anything that can be done to restore it?

**Comment by stephenavocado** [comment]
Hi, @svenefftinge - sorry to bother you. I saw you help with a similar issue earlier today and wondering if it might be an easy fix for my issue.

**Comment by svenefftinge** [comment]
This has [happened a lot](https://cloudlogging.app.goo.gl/qrzAUUmcwb6GF4KZ6) yesterday.

**Comment by svenefftinge** [comment]
@stephenavocado I have reset your workspace so you can start it again. Sorry for the inconvenience.
Leaving this open, to fix the root cause.

**Comment by csweichel** [comment]
> This has [happened a lot](https://cloudlogging.app.goo.gl/qrzAUUmcwb6GF4KZ6) yesterday.

Note, that all workspaces belonging to `00000000-0000-0000-0000-000000000000` are ghosts. That's not to say we don't have an issue here, but to help judge the impact.

**Comment by svenefftinge** [comment]
> Note, that all workspaces belonging to 00000000-0000-0000-0000-000000000000 are ghosts. That's not to say we don't have an issue here, but to help judge the impact.

I already had filtered them out in that query (`-jsonPayload.userId="00000000-0000-0000-0000-000000000000"`)

**Comment by svenefftinge** [comment]
There are also many other [workspaces that fail](https://cloudlogging.app.goo.gl/q7oo9KWq98cAUox57) for other reasons.

**Comment by stephenavocado** [comment]
Thank you so much!

**Comment by csweichel** [comment]
The root cause was most likely the recent containerd instability issues. I'll close this for now and will re-open if the issue re-appears.
