### ISSUE TITLE
[cloudcosts] automatically scale down ghosts on empty clusters

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5141]
Today, ghosts "appear" and "disappear" based on the fixed schedule ws-scheduler's config-map. 

Due to our deployment strategy, we often have empty k8s clusters on stand-by.
Our staging clusters are also empty most of the time.

The past has shown that it is not practical to manually scale up/down the node count when clusters go on (or return from) stand-by. On staging the desirability of nodes may be limited to the time when staging is in use.

Thus I propose that ws-scheduler should have an additional strategy to scale down ghosts if the cluster is empty. 

Possible strategies:
a) If there are no regular workspaces on the clusters, dynamically reduce max ghosts to zero.
b) define max ghost count to be `min(count(regular_workspaces), max_ghost_count_from_configmap).

**Comment by csweichel** [comment]
We should rather automate this as part of the deployment process where we update the config accordingly.
Also, if we had control over the scheduler (move out of GKE) we could do away with ghosts almost entirely.

I don't see that we'll need to/or make a change here at this point. Hence removing from groundwork.
