### ISSUE TITLE
Emmet not working in GitPod

### ISSUE THREAD

**Issue by AndyMc3000** [gitpod-io/gitpod#5148]
### Bug description

I can't get the Emmet extension to work in my workspaces. This happened after the migration to VS code. I have tried working with the settings.json etc but can't get it to work. It seems this is an known issues for some users. Can you suggest a fix or an alternative extension I can use for auto tagging?

### Steps to reproduce

Whe I start typing an html tag, I don't get tag suggestions...see screenshot.
<img width="505" alt="Screen Shot 2021-08-11 at 10 37 06" src="https://user-images.githubusercontent.com/72210068/129016713-a9a19e28-bf3d-4fef-8c88-1761b3f184e7.png">

### Expected behavior

HTML tag suggestions

**Comment by akosyakov** [comment]
@AndyMc3000 Could you share your repo please? And confirm that you have VS Code selected here: https://gitpod.io/preferences

Emmet extension is built-in and should work out of the box.

**Comment by akosyakov** [comment]
I just verified that emmet extension is installed and works:
<img width="1904" alt="Screenshot 2021-08-11 at 13 51 47" src="https://user-images.githubusercontent.com/3082655/129024056-b3923c98-3c74-40fd-89f5-b774f32b204c.png">

Which language does your file have? Maybe it is not supported by emmet. Docs says that following is supported from https://code.visualstudio.com/docs/editor/emmet#_how-to-expand-emmet-abbreviations-and-snippets:
> Emmet abbreviation and snippet expansions are enabled by default in html, haml, pug, slim, jsx, xml, xsl, css, scss, sass, less and stylus files, as well as any language that inherits from any of the above like handlebars and php.

**Comment by AndyMc3000** [comment]
Hi Akosyakov,

I can confirm that VS code is my default IDE.

My shared workspace link is; https://orange-rabbit-fj9oof28.ws-eu14.gitpod.io/

I'm just using HTML and CSS right now. My project is a Django/Python app.

Thanks,
Andy

**Comment by akosyakov** [comment]
@AndyMc3000 You should not share workspace on internet like that! It is enough for me to know workspace id.

**Comment by AndyMc3000** [comment]
Oh, ok. Thanks for the tip!

**Comment by akosyakov** [comment]
It seems that `hookyqr.beautify` breaks it, if you disable it then emmet works again.

**Comment by akosyakov** [comment]
I noticed weird thing. If I just type ctrl space then it does not give me any emmet proposals, if i type `ul` for example then I see them. I verified though that it is the same way on desktop.

**Comment by AndyMc3000** [comment]
Brilliant. I disabled all my extensions and closed and opened my workspace. Emmet is now working (I just need to know figure which of the extensions broke Emmet).

Thanks for your help Akosyakov!

**Comment by akosyakov** [comment]
ok, keep us posted, if you figure out which combination is it, we can have a look then
also try to reproduce then with dekstop VS Code, if it is reproducible we need to repo it upstream on extensions or vscode repo
