### ISSUE TITLE
Add documentation for teams and projects

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5150]
### Problem to solve

The upcoming Teams & Projects feature does not have any documentation at the moment. In addition, there's also some existing documentation about the current Teams feature, see [`/docs/teams`](https://www.gitpod.io/docs/teams) which could cause some confusion to the users.

### Proposal

Let's add some documentation around teams and projects as well as add a deprecation notice for the current Teams feature, following the changes in https://github.com/gitpod-io/gitpod/pull/5121.

**Comment by jldec** [comment]
Closing this - since we have docs now and even a Beta notice :)

**Comment by gtsiolis** [comment]
Thanks for coming back to this, @jldec! Missed closing this the initial PR in #842 was replaced in https://github.com/gitpod-io/website/pull/842#issuecomment-944415830.
