### ISSUE TITLE
Can not start our pods

### ISSUE THREAD

**Issue by yababer** [gitpod-io/gitpod#5158]
### Bug description

We are seeing this issue when spawning a new pod:

Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume: 

### Steps to reproduce

Spawn a new pod from gitlab

### Expected behavior

the pod starts up

**Comment by taylorcoffelt** [comment]
Looks like they ran out of space in the US Cluster:
https://www.gitpodstatus.com/
![image](https://user-images.githubusercontent.com/690213/129082731-70b46077-8452-446b-9c97-c2b843a7b1fe.png)

**Comment by svenefftinge** [comment]
It is resolved now.
