### ISSUE TITLE
Package (ipython3) installed not show up

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#517]
**Describe the bug**
I have a customized Docker image dclong/gitpod-py3 (on DockerHub) which installs both `pelican` and `ipython` for Python3. However, when I use it `pelican` is available but `ipython` is not. 

**To Reproduce**
1. Specify dclong/gitpod-py3 as a customized Docker image for a GitHub repository.
2. Open the GitHub repository in GitPod. 
3. Run `which ipython3` and `which ipython`.

**Expected behavior**
The installed package ipython should be available. 

**Dockerfiles**

https://github.com/dclong/docker-gitpod-py3/blob/master/Dockerfile

https://github.com/dclong/docker-gitpod-svim/blob/master/Dockerfile

**Comment by AlexTugarev** [comment]
@dclong, thanks for reporting!

there is an issue with the workspace-full which prevents you from installing additional python modules in a custom image derived from the former, cf. https://github.com/gitpod-io/workspace-images/pull/87. 

I've tested a workaround with your setup here: https://github.com/AlexTugarev/test.repo/blob/testing-python/.gitpod.dockerfile

`RUN unset PYTHONUSERBASE PIP_USER && pip3 install ...` should to the trick temporarily. this will be added back again in the Gitpod image layer.

also, please do `USER gitpod` before installing python packages, see. https://github.com/dclong/docker-gitpod-py3/blob/master/Dockerfile#L3
