### ISSUE TITLE
Starting docker containers failing with "mount through procfd: operation not permitted"

### ISSUE THREAD

**Issue by adi-g15** [gitpod-io/gitpod#5171]
### Bug description

When starting a container through the terminal, it fails with: 

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted: unknown.

![image](https://user-images.githubusercontent.com/37269665/129189586-1f2d4902-b111-4cfe-8239-826eb930bb54.png)

### Steps to reproduce

1. Open gitpod with any repo, eg. https://gitpod.io/#https://github.com/adi-g15/zeeve-learnings
2. docker run -it ubuntu

> I tried with multiple images, all failed with same error, including archlinux, custom images, hyperledger sawtooth

### Anything else?
Didn't find a duplicate, maybe related to #5090 

This wasn't a problem few days ago. Also, another friend had this same error, maybe more people may face this.

**Comment by pawlean** [comment]
I also see this issue, and someone else pointed it out [on our community page.](https://community.gitpod.io/t/custom-docker-image/4537)

**Comment by csweichel** [comment]
The workspace contains `runc` in version 1.0.1 which breaks right now. We have a fix on main (https://github.com/gitpod-io/gitpod/pull/5139) but it's not deployed yet. This should happen by the end of today (CEST timezone).

**Comment by ghuntley** [comment]
Resolved and in production.
