### ISSUE TITLE
Rate limit prebuilds

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#5176]
### Bug description

Today at around 13:24 UTC, there was a sudden jump in the number of prebuilds: Over about a minute, the repository https://gitlab.com/yo/gitlab triggered nearly 100 new prebuilds.

Unfortunately, this put excessive pressure on the US cluster, and in particular on the database, which lead to several workspaces not being able to start (for example: https://community.gitpod.io/t/django-pod-is-down/4541).

This incident lasted about 20 minutes and was logged here: https://www.gitpodstatus.com/incidents/ddyzghh3mfbm

### Steps to reproduce

Instantly trigger 100 prebuilds

### Expected behavior

There should be no outage, especially in the database

### Anything else?

Maybe it would make sense to introduce a reasonable rate limit on prebuilds, for example per repository.

**Comment by AlexTugarev** [comment]
Looking into the old solution for now: https://github.com/gitpod-io/gitpod/blob/main/components/server/ee/src/prebuilds/prebuild-queue-maintainer.ts

I hope, @csweichel or @geropl find time to provide more details on this, please 🙏🏻

**Comment by geropl** [comment]
This just lead to an incident: https://app.incident.io/incidents/101
Thus added it to #7812

/cc @jldec

**Comment by jldec** [comment]
Scheduled this issue.
Similar to https://github.com/gitpod-io/gitpod/issues/7400

**Comment by jldec** [comment]
Remove highest priority label - not 🔥.

**Comment by jldec** [comment]
Back on the urgent list after another close call ([internal](https://gitpod.slack.com/archives/C01KGM9DVRC/p1645984314944559))
cc: @kylos101

**Comment by jankeromnes** [comment]
Happy to look into implementing a reasonable rate limit that doesn't break normal usage but prevents incidents.

**Comment by jankeromnes** [comment]
I did some [research](https://github.com/gitpod-io/ops/issues/1373#issuecomment-1055338729) (internal) on our top prebuild rates for February 2022:

> Research reveals three top rate classes:
> - "Abuse-like" (50-85+ / min)
> - "Dependabot" (25-50 / min)
> - "Popular & mirrors" (up to 25 / min)
> 
> I think we'll want to stop the "Abuse-like", but continue supporting the "Popular & mirrors".

Also, the "Dependabot" case is interesting:
- Developers probably don't need all Dependabot pushes to be prebuilt all the time. Maybe it's okay to fail some prebuilds in case of high-frequency push bursts?
- Also, auto-enabling Incremental Prebuilds for top 10 "Dependabot" repositories would likely help us significantly

**Comment by kylos101** [comment]
Hi @jankeromnes , would it be prohibitive to also include a check to see how many total prebuilds this user is running now, and not allow them to do more than 50?

**Comment by kylos101** [comment]
Hey @jankeromnes :wave: ,

> I think this is an interesting, but somewhat more complicated proposal

I thought that might be, but wanted to ask for the sake of posterity (my lens was the one user, two repos, and ~100 PRs). Thank you very much for your thoughtful response!

> Short term, the proposed rate-limit on the prebuild trigger is already a very simple, low-risk fix that can prevent outages like we've seen in the past without disrupting normal UX

Totally agreed, this will :100: help! :pray: :star2: 

> Longer term

Those are excellent points! :1st_place_medal: I appreciate you sharing the related use cases / different ways to control the throttle. 

@jldec is there a related epic for `get better at being a CI`? I ask because @jankeromnes made some great points (above), and I'm not sure if they exist elsewhere in a related epic. Also, it might make sense to cancel prebuilds if a PR is merged or closed w/o merge.
