### ISSUE TITLE
The Python package pelican does not work well

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#518]
**Describe the bug**
I installed the pelican package (for building static web sites) in my customized Docker image for Gitpod but it's working as expected. The same code works well in Ubuntu, Mac and Ubuntu in Docker. 
```
gitpod /workspace/blog $ ./blog.py p -ecm
Done: Processed 0 articles, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 0.32 seconds.
Traceback (most recent call last):
  File "./blog.py", line 1288, in <module>
    args.func(blogger, args)
  File "./blog.py", line 154, in publish
    _push_github(dir_, args.https)
  File "./blog.py", line 122, in _push_github
    shutil.copy('pages/index.html', 'index.html')
  File "/home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'pages/index.html'
```

**To Reproduce**
1. For the GitHub repository [dclong/blog](https://github.com/dclong/blog)
2. Open it for editing in Gitpod
3. Run `./blog.py p -ecm` in terminal. `blog.py` is Python script that I developed to help generating my personal blog.

**Expected behavior**
The Python package pelican should work well as in other environments (Linux/Mac/other Docker images).

**Comment by AlexTugarev** [comment]
@dclong thanks for reporting! I'm closing this because it's the same issue as https://github.com/gitpod-io/gitpod/issues/517#issuecomment-486634030

Please try with the temporary workaround `RUN unset PYTHONUSERBASE PIP_USER && pip3 install ...`, also do not forget to switch user. If that doesn't work for you, feel free to comment!

**Comment by dclong** [comment]
@AlexTugarev Can we reopen this issue and further investigate it? I follow your suggestions and have rebuilt my Docker images based on the latest Docker image `gitpod/workspace-full`. The issue https://github.com/gitpod-io/gitpod/issues/517 is resolved now, however, this issue in thread still exists.

**Comment by AlexTugarev** [comment]
@dclong, yes let's have a closer look. how can I reproduce it?

**Comment by AlexTugarev** [comment]
@dclong, I'm not familiar with `pelican` at all, but from your `blog.py` script I can tell that it's creating output just fine:

![Screen Shot 2019-04-26 at 09 37 31](https://user-images.githubusercontent.com/914497/56791314-10f40c80-6807-11e9-8d50-128bbde8b49a.png)

I think it's the `_push_github` function that might make wrong assumptions about paths. please have a look.

**Comment by dclong** [comment]
@AlexTugarev I do think it's an issue of `pelican` in the Gitpod Docker image. It's expected to generated a subdirectory named `pages` which contains `index.html` under the directory `home/output`. As I've mentioned that the exact same thing (code, blog content, etc.) works well in other environment. For example, it works well in the Docker image `dclong/jupyterhub-ds` (need to install pelican manually) which is also base on Ubuntu 18.10.

**Comment by AlexTugarev** [comment]
@dclong, that still might be a different version of the package. I'm going to test it, to understand the different behavior. Thanks for the hint with the other image.

One question: why do you prefer to install packages in the image over freezing a set of requirements? You could run `pip install -r requirements.txt` in the `init` task.

**Comment by dclong** [comment]
@AlexTugarev It's a good suggestion to use `init`. Are both `ini`t and `command` run using the user gitpod?

**Comment by AlexTugarev** [comment]
@dclong, yes they are. Have a look at [docs](https://www.gitpod.io/docs/44_Config_Start_Tasks/#code-classlanguage-textinitcode-command), the `init` command is a perfect fit for one-time tasks like `pip install ...`.

**Comment by dclong** [comment]
I found that this issue happens in another environment (not gitpod Docker container), so it sounds like that it might be an issue of Pelican itself. I will close the issue at this time.
