### ISSUE TITLE
Users not accepting GitLab ToS should not look like application error in Gitpod

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5183]
@ghuntley noticed that we've got many requests on gitpod.io/sorry which he (validly) thought may be an indicator to a larger problem. 

On the LoadBalancer, I can see that [many of these requests have gitlab.com as referrer](https://console.cloud.google.com/logs/query;query=resource.type%3D%22http_load_balancer%22%0AhttpRequest.requestUrl:%22sorry%22;timeRange=PT12H;summaryFields=httpRequest%252Freferer:false:32:beginning;cursorTimestamp=2021-08-13T07:12:34.237979Z?project=gitpod-191109).
![image](https://user-images.githubusercontent.com/239422/129322527-56b6d46d-2663-4229-b728-f8f87fdab8e8.png)

In the [server logs I see entries such as](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-08-13T00:41:05.229Z;query=%22server%22%20%22sorry%22%0Atimestamp%3D%222021-08-13T00:07:37.246Z%22%0AinsertId%3D%22uj5g4ylto7z8qp1u%22;timeRange=PT12H?project=gitpod-191109)
```
Error: 403 Forbidden - You (<username>) must accept the Terms of Service in order to perform this action. Please access GitLab from a web browser to accept these terms.
    at Object.create (/app/node_modules/@gitpod/server/dist/src/auth/errors.js:23:30)
    at Object.create (/app/node_modules/@gitpod/server/dist/src/auth/errors.js:48:30)
    at GitLabAuthProvider.<anonymous> (/app/node_modules/@gitpod/server/dist/src/gitlab/gitlab-auth-provider.js:67:61)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/@gitpod/server/dist/src/gitlab/gitlab-auth-provider.js:17:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

To avoid future confusion of people who do operations, this error should not do a redirect to "/sorry" but only send a HTTP 403 with the error page and that's it.

**Comment by laushinka** [comment]
I'm not sure how to reproduce this or how to work on this, so based on [this Slack thread](https://gitpod.slack.com/archives/C01KGM9AW4W/p1630318615053600) and discussion with @JanKoehnlein I will assign this issue to Product.

**Comment by AlexTugarev** [comment]
Some additional hints on where to start:
 * the [redirect](https://github.com/gitpod-io/gitpod/blob/main/components/server/src/auth/generic-auth-provider.ts#L366) to the sorry page to be replaced (it's the `UnconfirmedUserException` case we're handling)
 * [example](https://github.com/gitpod-io/gitpod/blob/main/components/server/src/auth/generic-auth-provider.ts#L349) for error propagation back to the frontend

**Comment by laushinka** [comment]
> Here is the procedure which I hope still works:

@AlexTugarev Thank you for the very helpful steps! I was able to reproduce it 🙌🏽 Will attempt to work on this then. If I have more questions I will let you know :)
