### ISSUE TITLE
Trim the amount of prebuilds surfacing the dashboard

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5185]
### Problem 

The upcoming **Teams & Projects** feature will surface prebuilds in the dashboard. However, this is still not optimized to fetch all prebuilds, see https://github.com/gitpod-io/gitpod/issues/5038

For example, see https://gitpod-staging.com/gitpod-io/gitpod/prebuilds (internal).

### Proposal

Before improving the performance for fetching prebuilds or adding any kind of pagination, we could just trim the amount of prebuilds surfacing the dashboard to 10 or 20 items similar to the branches list.

**Comment by AlexTugarev** [comment]
<img width="496" alt="Screen Shot 2021-08-23 at 14 25 22" src="https://user-images.githubusercontent.com/914497/130446813-d2690744-4829-419b-bc5c-8be67df2fde9.png">

this is quite bad and results in an empty rendering.
