### ISSUE TITLE
Issue with restored Worskpace for closed issue #5132

### ISSUE THREAD

**Issue by NgiapPuoyKoh** [gitpod-io/gitpod#5188]
### Bug description

Attempted to open workspace with several tries

This workspace opened normally yesterday afternoon and evening US EST

### Steps to reproduce

Affected workspace:

https://teal-limpet-fz3ezfxe.ws-us13.gitpod.io/

![BuildingImage](https://user-images.githubusercontent.com/61414348/129351093-e4114824-a7a9-4df0-8312-d5ff05edbd62.png)

### Expected behavior

Workspace opens without error.

### Example repository

https://teal-limpet-fz3ezfxe.ws-us13.gitpod.io/
https://github.com/NgiapPuoyKoh/django-blogchat-tech

### Anything else?

This is a student's final project workspace which contains their local DB (gitignored), so creating a duplicate workspace is the last option as it would require rebuilding the DB and the data in it.

Note: Gitpod reported issues yesterday 
Aug 12, 2021
Some workspaces won't start in the US
Resolved - New workspaces can be started again (since 45min ago), and workspaces that are currently stuck in "Creating" should automatically time out after some time, after which they can be restarted normally.

**Comment by jankeromnes** [comment]
Hi @NgiapPuoyKoh!

From our side, this workspace appears to be running currently. Is it possible that this situation is resolved now?

FYI, sometimes it can happen that the "Building Image" screen doesn't show any logs, even when there is a build in progress. In that case, it should still automatically open the workspace when the image rebuild is done.

Please let us know if it still doesn't work, or if you have any questions.

**Comment by NgiapPuoyKoh** [comment]
Thank you Pawlean and Jan
I am able to start the gitpod workspace and run my app

Any idea that happened and is there anything I can do to avoid this
I have had 3-4 incidence of issues with the workspace during the past 6 days

Please advise

**Comment by NgiapPuoyKoh** [comment]
FYI I tries to restart the workspace several times between 6am until I submitted this ticket
I tried using incognito window, close and reopen every few minutes etc...

In future are there specific steps I should take to get the gitpod workspace started?

**Comment by jankeromnes** [comment]
> Thank you Pawlean and Jan

You're quite welcome! 😊 

> I am able to start the gitpod workspace and run my app

Ah, that's great -- thanks for confirming! I'll close this issue then.

> Any idea that happened and is there anything I can do to avoid this
> I have had 3-4 incidence of issues with the workspace during the past 6 days

Sorry about that 🙈 Normally, your workspace should almost never need to rebuild its image once it has been created.

However, in the past week or so, there have been two things that may have caused the more frequent rebuilds:

- We have deployed new changes to Gitpod's image-builder. When this happens, most workspaces typically need to rebuild their image once (even older workspaces)

- There have also been recent incidents related to image builds, which may have impacted your workspace. See all recent incidents here: https://www.gitpodstatus.com/

> FYI I tried to restart the workspace several times between 6am until I submitted this ticket
> I tried using incognito window, close and reopen every few minutes etc...

That's probably related to a recent Gitpod incident then. I'm sorry for the disruption. Normally this should never happen, but when there is an incident, there isn't much you can do on your side (e.g. trying incognito & other browsers typically won't help).

> In future are there specific steps I should take to get the gitpod workspace started?

Normally, no, just starting your workspace from https://gitpod.io/workspaces or (even better) creating brand new workspaces is the best you can do.

But if something like this ever happens again, please do check https://www.gitpodstatus.com/ -- it may contain more information on what exactly is happening and when it will be resolved.
