### ISSUE TITLE
Text invisible in the terminal (Safari 15.0)

### ISSUE THREAD

**Issue by maksimr** [gitpod-io/gitpod#5194]
### Bug description

No font in the terminal Safari **Version 15.0** (16612.1.26.1.4, 16612)

### Steps to reproduce

STR:

- Open https://gitpod.io/#https://github.com/maksimr/playground in **Safari 15**
- Open Terminal
- Type `ls`

### Expected behavior

Should show text in the terminal

### Example repository

https://gitpod.io/#https://github.com/maksimr/playground

### Anything else?

https://user-images.githubusercontent.com/616193/129384098-6652a209-9dc6-4148-8164-a8d54811c554.mov

**Comment by vultuk** [comment]
Your terminal will be visible if you go into settings and search for the following setting.

`terminal.integrated.gpuAcceleration`

Then change the setting to...

`off` or `canvas`

**Comment by akosyakov** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/5040
