### ISSUE TITLE
Expo start show black screen

### ISSUE THREAD

**Issue by chlbri** [gitpod-io/gitpod#5196]
### Bug description

I run an react native app, but when I run yarn start (expo start), I got az black screen in the browser for developper tools.

### Steps to reproduce

Create a react native app and after all steps, tun expo start.

### Expected behavior

It has to show the developper tools

**Comment by filiptronicek** [comment]
I have been having issues with Expo and GitPod, too, but if you just want things to work, try [GitPod's local companion](https://www.gitpod.io/blog/local-app), it helped me a lot and I was able to run my expo app just fine.

**Comment by chlbri** [comment]
I will try it. Thanks you.

Envoyé à partir de Courrier pour Windows

De : Filip Troníček
Envoyé le :vendredi 13 août 2021 22:30
À : gitpod-io/gitpod
Cc : chlbri; Author
Objet :Re: [gitpod-io/gitpod] Expo start show black screen (#5196)

I have been having issues with Expo and GitPod, too, but if you just want things to work, try GitPod's local companion, it helped me a lot and I was able to run my expo app just fine.
