### ISSUE TITLE
Docker Build doesn't show log on `start`URL

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#520]
When opening a starting workspace that is currently in docker build phase, we do not show that status nor the logs.

<img width="756" alt="Screenshot 2019-04-25 at 16 43 03" src="https://user-images.githubusercontent.com/372735/56745313-68986680-677a-11e9-8587-73e82c116730.png">

**Comment by AlexTugarev** [comment]
Looks like https://github.com/gitpod-io/gitpod/issues/487 to me. @geropl, am I right? Your latest PR addresses this.

**Comment by jankeromnes** [comment]
I think this was fixed. Please re-open if not.
