### ISSUE TITLE
Workspace not working

### ISSUE THREAD

**Issue by Iacopo454** [gitpod-io/gitpod#5203]
### Bug description

I have created yesterday a new workspace but after a few hours I can not anymore open this workspace. 
After launching the project, the window states stopping. 
Please see attached the workspace:  https://green-hoverfly-vgcjlwus.ws-eu14.gitpod.io/

### Steps to reproduce

Just click on the link workspace:  https://green-hoverfly-vgcjlwus.ws-eu14.gitpod.io/

**Comment by pawlean** [comment]
Hey @Iacopo454! I can see that your workspace is running now :) Apologises for this! We will be shipping a fix for these stopping workspaces soon. Please reach out if you have any more questions!
