### ISSUE TITLE
Workspace that was restored (Issue#5132) and (Issue#5188) stuck on Stopping Mode

### ISSUE THREAD

**Issue by NgiapPuoyKoh** [gitpod-io/gitpod#5205]
### Bug description

This workspace opened normally earlier today
Now it is stuck in Stopping Mode

Note: This workspace was restored  4 days (Issue#5132) and was stuck on Thursday (Issue#5188)

### Steps to reproduce

Affected workspace:
https://teal-limpet-fz3ezfxe.ws-us13.gitpod.io/

![workspaceStopping](https://user-images.githubusercontent.com/61414348/129461950-086f1ea8-42b3-4cb1-8f63-1c2b03241ff1.png)

### Expected behavior

Workspace opens without error.

### Example repository

https://teal-limpet-fz3ezfxe.ws-us13.gitpod.io/
https://github.com/NgiapPuoyKoh/django-blogchat-tech

### Anything else?

This is a student's final project workspace which contains their local DB (gitignored), so creating a duplicate workspace is the last option as it would require rebuilding the DB and the data in it.

This workspace had issues this past week  (Issue#5132) and (Issue#5188) which were restored

**Comment by NgiapPuoyKoh** [comment]
Similar issues have been reported in the gitpod community channel. 
I a going to check in tomorrow first thing in the morning US EST 4am
This disruption all week is impacting my progress on my project and had impacted my ability to meet the submission deadline

**Comment by pawlean** [comment]
Apologises @NgiapPuoyKoh! I've responded to your Twitter DM and community posts. Let us know if you have any more issues!

**Comment by NgiapPuoyKoh** [comment]
Thank you Pauline, I was able to start the workspace
Any updates on the root cause and resolution to the issue to prevent recurrences?

**Comment by tommygonzaleza** [comment]
Hello, other teammates and I are facing the same issue! Please let us know how to prevent it or when the issue is solved

**Comment by yababer** [comment]
Agreed, we are having the same issue as well.

**Comment by pawlean** [comment]
Hi @tommygonzaleza @yababer - we're currently looking for a fix here. Please see: https://www.gitpodstatus.com/ for details and updates!
