### ISSUE TITLE
https cert issue?

### ISSUE THREAD

**Issue by jean** [gitpod-io/gitpod#5206]
### Bug description

When opening up an existing workspace using Chrome on Android, I got this warning: 
![Screenshot_20210815-142752_Chrome](https://user-images.githubusercontent.com/84800/129471552-db4a03af-4b10-4601-ab08-c49dae019ca2.jpg)

### Steps to reproduce

Open an existing workspace.

**Comment by akosyakov** [comment]
I seen the same for pinned workspaces for old clusters. cc @meysholdt

**Comment by jean** [comment]
Ugh stale bot

**Comment by jean** [comment]
Ugh, this again

**Comment by axonasif** [comment]
Hey @jean, do you still experience this?
