### ISSUE TITLE
Jekyll Web Server Following Links Yield to Localhost in URL

### ISSUE THREAD

**Issue by Coder206** [gitpod-io/gitpod#521]
**Describe the bug**

Potential issue with auto-forwarding and host rewriting clauses. 

**To Reproduce**

I am working on a Jekyll-based website in Gitpod (https://github.com/LU-MCSC/lu-mcsc.github.io), after setting up the dependencies, I navigated successfully to [this page](https://github.com/LU-MCSC/lu-mcsc.github.io/blob/master/index.html) when I click a link it navigates to the localhost address (e.g.: Going to Archives, yields https://localhost/archives/ in the URL bar (and a browser page not found))

**Expected behavior**

Navigate to {Gitpod-URL}/archives and show the content of the page

cc @svenefftinge

**Comment by svenefftinge** [comment]
Turns out `jekyll serve --host=0.0.0.0` works fine, once you've cleared the browser cache (or use a fresh workspace)

**Comment by distinctperspective** [comment]
this doesnt not work for me.   I have files called "/Tour" (<-- directory)  and  "/Tour.html"

**Comment by svenefftinge** [comment]
@distinctperspective Can you provide an example repository?

**Comment by distinctperspective** [comment]
git@github.com:clockshark/dev-clockshark.git
