### ISSUE TITLE
[analytics] enable geographical segmentation of users

### ISSUE THREAD

**Issue by jakobhero** [gitpod-io/gitpod#5211]
Some analytics providers (e.g. Mixpanel) segment users through client IP addresses (or ranges). Ususally the cleint IP should be automatically collected and forwarded for every tracking call done from the client side, but this is currently not the case. Associating our users with a geographical regions would greatly enhance our user understanding.

**Comment by jakobhero** [comment]
After digging deeper, the IP addresses are already collected and the problem is caused when the events are forwarded to mixpanel. i am going to take on this now as it's no longer an engineering problem

**Comment by JanKoehnlein** [comment]
Thanks for the heads up. Unscheduling from engineering groundwork
