### ISSUE TITLE
Firebase keeps getting mysteriously uninstalled in my projects

### ISSUE THREAD

**Issue by UnrealApex** [gitpod-io/gitpod#5212]
### Bug description

I've noticed that after installing Firebase in a Gitpod workspace and returning to it after a few days, firebase is gone as if it was never installed, but files like the `.firebaserc` and `serviceAccountKey.json` are still there unmodified.

### Steps to reproduce

1. Create a new Gitpod workspace
1. Install Firebase  with `npm install -g firebase-tools`
1. Wait 3 days
1. Open the same Gitpod workspace and try typing `firebase`
1. See in terminal  <samp>bash: firebase: command not found</samp>

### Expected behavior

Upon opening the workspace and trying to run firebase, firebase would be installed.

### Anything else?

I use Gitpod on a school administered machine so it could be possible that my school IT admins have been remotely accessing my chromebook and uninstalling it for security reasons or maybe my chromebook has a virus 👀 .

**Comment by akosyakov** [comment]
Where is it installed? Only content of `/workspace` folder is preserved for now. Please see https://github.com/gitpod-io/gitpod/issues/340

**Comment by UnrealApex** [comment]
Good question, not exactly sure. I would assume the install location is the "default" for `npm`. How would I be able to find the install location?

**Comment by JanKoehnlein** [comment]
> How would I be able to find the install location?

After installing, try `which firebase` in the terminal

**Comment by UnrealApex** [comment]
Thanks, here it is:
 <samp>/home/gitpod/.nvm/versions/node/v14.17.3/bin/firebase</samp>

**Comment by akosyakov** [comment]
@UnrealApex You should have a custom Dockerimage and instal firebase there: https://www.gitpod.io/docs/config-docker
It is not recommended to rely on the same workspace, but start a new workspace each time which is created from Dockerfile and your github repo: https://www.gitpod.io/docs/workspaces

**Comment by UnrealApex** [comment]
While that will keep Firebase installed, won't I need to login everytime?
