### ISSUE TITLE
Allow mounting ISO, squashfs and ext* filesystem images

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#5226]
Hi,
I found that we can't mount `.iso`(9660), `.sfs`(squashfs) or `.img`(ext4, ext2, ext3) images via the `mount` command.
Although it appears some of the filesystem types are allowed to be mounted, such as `tmpfs`.
Would it be possible to allow the mounting of such filesystem types within Gitpod in the future?
This could make operating system development easier though.
Thanks.

**Comment by axonasif** [comment]
Reopening for an user query at [Discord](https://canary.discord.com/channels/816244985187008514/947882257534832661/947883467268579368)

**Comment by wimax-grapl** [comment]
(I'd also really love this. My use case is [building a rootfs](https://github.com/firecracker-microvm/firecracker/blob/main/docs/rootfs-and-kernel-setup.md#creating-a-rootfs-image) for a KVM. There are pretty few ways to do this without a mount! 

Yes, one of the options is `qemu` but, like, I'd rather not :)

**Comment by axonasif** [comment]
@wimax-grapl for ISO images, you can use `archivemount` which uses the fuse driver.
Maybe you could find some fuse implementations for other filesystem needs until this is natively supported on Gitpod. There are a few ext* FUSE drivers which I didn't try yet but curious to know :)
https://github.com/gerard/ext4fuse
https://libguestfs.org/guestmount.1.html
