### ISSUE TITLE
Workspace is stucked on stopping mode.

### ISSUE THREAD

**Issue by tommygonzaleza** [gitpod-io/gitpod#5227]
### Bug description

I'm having the same problem that the one explained in this issue: https://github.com/gitpod-io/gitpod/issues/5205

### Steps to reproduce

I just tried to open a workspace and it didn't let me, it got stuck on stopping mode before opening it.

**Comment by tommygonzaleza** [comment]
It is telling me this:
![image](https://user-images.githubusercontent.com/56565994/129617661-87739747-a924-430d-a1a7-61ea1b2f0de2.png)

**Comment by yababer** [comment]
I just had a similar issue, I was working in a pod and it suddenly stopped.  That pod is stuck in stopping mode.

The new pod is stuck in allocating resources mode.

**Comment by pawlean** [comment]
Hi both - I believe I responded to you on another issue and on Discourse. But right now, we're looking into this issue. https://www.gitpodstatus.com/ Please bare with us and keep an eye out for this!
