### ISSUE TITLE
Support Android Development

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#523]
I was trying to get an Android emulator running through VNC but got stuck.

Here's what I have so far:
 - repo : https://github.com/svenefftinge/samples

```
gitpod /workspace/samples $ ~/android-sdk/emulator/emulator -avd avd-25
Couldn't statvfs() path: No such file or directory
emulator: ERROR: x86_64 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
```

**Comment by svenefftinge** [comment]
According to https://github.com/ksoichiro/dockerfiles/issues/3 docker privileged mode could help, but I guess the real issue is that our nodes don't have GPUs?

**Comment by geropl** [comment]
Those are virtualization capabilities of the CPU necessary for VMs/virtualization technology (vmx is Intel, svm AMD). We would need to enable nested virtualization to pass these capabilities from the physical machine -> Google VM -> Docker container.

**Comment by geropl** [comment]
GCloud VMs generally support it (with a few restrictions): https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances

It is not possible to enable that for GKE yet: https://issuetracker.google.com/issues/110507927

**Comment by JesterOrNot** [comment]
look at #723

**Comment by jankeromnes** [comment]
You're right, let's close this issue in favor of #723, which has picked up this work.

**Comment by ceefour** [comment]
Where is #723 ?

**Comment by nisarhassan12** [comment]
@ceefour Looks like #723 got deleted here is the recovery of that https://github.com/gitpod-io/gitpod/issues/1273
