### ISSUE TITLE
reintroduce partial clone

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5231]
See https://github.com/gitpod-io/gitpod/pull/5152

We should reintroduce it in such way that it does not break [forking](https://github.com/gitpod-io/gitpod/issues/4914) and [blaming](https://github.com/gitpod-io/gitpod/issues/5110).

**Comment by JanKoehnlein** [comment]
Though I am convinced improving performance is important, I think we should ATM focus on issues that increase stability instead. Feel free to bring this up at a later point in time. 

If you have any particular idea how to avoid the prior pitfalls, don't hesitate to add them to this issue. The clearer the path to a solution the more likely it will be scheduled.

**Comment by akosyakov** [comment]
It seems the load timing is significantly high now. If it is the reason I think we should assign someone to investigate. I don't think the solution will appear othewise.

**Comment by svenefftinge** [comment]
We should allow people to opt-in through the repository configuration on how a clone should happen.
I think it makes sense to allow general clone arguments. So people can use different kinds of clones. Also we might want to investigate if a shallow clone followed by an async inflation that happens when users are already on the workspace couel make sense. this could drastically reduce the size on the file system for prebuild snapshots as well.

**Comment by gtsiolis** [comment]
An option to select partial clone, full clone, or clone using arguments could be something to consider adding in a projects settings area, next to features like project-level environment variables https://github.com/gitpod-io/gitpod/issues/4456. 💭

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5231#issuecomment-955704259):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
