### ISSUE TITLE
initContainer of ws-daemon logs infos as errors

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5249]
In the bash script that creates the raid0, the `set -x` causes all statements to be printed to stderr when executed, which then get severity "error" in our log system. 

Expectation: info-messages should not be errors. Maybe `-v` instead of `-x` does the trick. Or something with `BASH_XTRACEFD`. 

see also https://serverfault.com/questions/296991/send-bash-x-output-to-logfile-without-interupting-standard-output/579078#579078

**Comment by meysholdt** [comment]
I'm filing this issue because the errors led to confusion [here](https://gitpod.slack.com/archives/C01KGM9AW4W/p1629199911275400?thread_ts=1629194188.271200&cid=C01KGM9AW4W)

**Comment by JanKoehnlein** [comment]
We're currently swamped. Pleas bring this up again later
