### ISSUE TITLE
Gitpod.yml: All commands don't execute if the first one is `pipenv shell`

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#525]
**Describe the bug**
I'm not sure if I am doing something wrong, this is my gitpod.yml
```yml
ports:
    - port: 3000
tasks:
    - init: >
        pipenv shell &&
        pipenv install &&
        export FLASK_APP=src/main.py &&
        export FLASK_ENV=development

      command: >
        pipenv shell &&
        flask run -p 3000
```

When the workspace is created this is what I see on the console:
![Screen Shot 2019-04-26 at 10 50 03 AM](https://user-images.githubusercontent.com/426452/56816218-148c9100-6811-11e9-9fc2-479330416dea.png)

It seems that the other commands `pipenv install`, etc. were never executed, if I try to running flask it says `flask: command not found`.

My guess is that only the `pipenv shell` was executed and now I have to run the other ones manually.

**To Reproduce**
Type in your browser url: [gitpod.io#https://github.com/4GeeksAcademy/flask-rest-hello.git](gitpod.io#https://github.com/4GeeksAcademy/flask-rest-hello.git)

**Expected behavior**
I would expect all commands to run and flash server already running when I start coding.

**Comment by AlexTugarev** [comment]
@alesanchezr thanks so much for reporting this!

Instead of `pip`ing into `~/.local` it should use a `.venv` directory in your project. That's done by setting `PIPENV_VENV_IN_PROJECT` like in the following example. Please try it! 

```
ports:
    - port: 3000
tasks:
    - init: >
        export PIPENV_VENV_IN_PROJECT=true;
        pipenv shell;
        pipenv install;
        export FLASK_APP=src/main.py;
        export FLASK_ENV=development
      command: >
        pipenv shell;
        flask run -p 3000
```

Also, I'm going to make `PIPENV_VENV_IN_PROJECT` be set by default.
