### ISSUE TITLE
liveness probe causes ws-daemon to be restartet

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5250]
[seen on staging](https://console.cloud.google.com/logs/query;query=%2528%22ws-daemon-phfmr%22%0AjsonPayload.source.component%3D%22kubelet%22%2529%20OR%0A%2528%2528logName%3D%22projects%2Fgitpod-staging%2Flogs%2Fkube-container-runtime-monitor%22%2529%20%0A-jsonPayload.MESSAGE%3D%22Start%20kubernetes%20health%20monitoring%20for%20container-runtime%22%2529;timeRange=2021-08-17T16:27:30.000Z%2F2021-08-17T17:03:30.000Z;summaryFields=labels%252F%2522compute.googleapis.com%252Fresource_name%2522:false:32:beginning;cursorTimestamp=2021-08-17T16:29:27Z?project=gitpod-staging):

![image](https://user-images.githubusercontent.com/239422/129808568-a969ff10-fd00-4f67-ad54-49b7c900cbf4.png)

The livenessprobe was introduced here: https://github.com/gitpod-io/gitpod/pull/5221

Maybe the timeout on the liveness probe is too aggressive: It times out before contianerd is back.

**Comment by aledbf** [comment]
@meysholdt that's expected. The failure is related to contained not being available. We need to choose to kill ws-daemon or delegate the check to the probes. (workspaces keep doing things that could require interaction with containerd)

**Comment by JanKoehnlein** [comment]
We already relaxed the liveliness probe in https://github.com/gitpod-io/gitpod/pull/5255. Closing this
