### ISSUE TITLE
Make homebrew install recent things

### ISSUE THREAD

**Issue by PEZ** [gitpod-io/gitpod#5251]
When I install `clojure` using homebrew like so:

```sh
brew install clojure/tools/clojure
```

It installs an ancient version, `1.10.1.536`. If I do it on my own machine I get version `1.10.3.943`.

Even if I (in my workspace) try to upgrade, I get this:

```sh
gitpod /workspace/pirate-lang $ brew upgrade clojure/tools/clojure
Warning: clojure/tools/clojure 1.10.1.536 already installed
```

I don't know the reasons Gitpod uses old packages, but I really would like to have an option to use the latest stuff.

**Comment by PEZ** [comment]
OK. So it seems to depend on which repository I try with.

* https://github.com/PEZ/pirate-lang -> ancient `clojure`
* https://github.com/PEZ/rich4clojure -> latest `clojure`

What gives?

**Comment by shaal** [comment]
@PEZ Here is one way to resolve this issue (by adding a comment to `.gitpod.dockerfile` and get it to rebuild the docker image.
https://github.com/PEZ/pirate-lang/pull/1
