### ISSUE TITLE
Workspace Pods hang in Terminating

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5253]
This issue is about workspace pods that stay in terminating. 
We had many of them last week, but there still seem to be a few cases. 
I think we should do two things here:

1) Identify and fix the cause.
2) Create an alert for workspaces that hang in terminating for more than one hour.

Related but different: #5275, #5274, #5273

**Comment by aledbf** [comment]
Can we close this issue? The fixes were deployed and the `Terminating` behavior is not there anymore.
