### ISSUE TITLE
Add a Contributing Guidelines file to the Repo

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [gitpod-io/gitpod#5258]
Adding a Contributing.MD file will make the repo conform to community standards making it better.

- To make your contributing guidelines visible in the repository's docs directory, type docs/ to create the new directory, then CONTRIBUTING.
- If a repository contains more than one CONTRIBUTING file, then the file shown in links is chosen from locations in the following order: the .github directory, then the repository's root directory, and finally the docs directory.
![image](https://user-images.githubusercontent.com/70568620/129888134-8af55966-7f1b-4167-8999-d704855312c3.png)

For reference: https://github.com/atom/atom/blob/master/CONTRIBUTING.md

**Comment by pawlean** [comment]
I totally agree that this would be a great way for our community to contribute with this :) Thanks @Prathamesh-Shanbhag!

**Comment by Prathamesh-Shanbhag** [comment]
I actually requested this because I'm trying to solve an issue on the dashboard Component of Gitpod but I'm unable to reproduce the error, so if there were proper steps as to how we can make the contributions that would be great! The issue was #5086

**Comment by gtsiolis** [comment]
Cross-posting from https://github.com/gitpod-io/roadmap/issues/27#issuecomment-947010907:
> Making it easier for everyone to contribute is certainly on our radar and we'll do our best to prioritize this given a) the complexity of the project, b) the current limitations of preview environments for forks, and c) our current focus on adding core features as well as making the product reliable. 🗺️

💭 **thought**: I've tried to outline some distinct next steps we'd like to work on as part of making it easier for everyone to contribute to Gitpod in https://github.com/gitpod-io/gitpod/issues/6466 and this includes also what we think is a good first MVC (minimum viable change) which is to document how to contribute using [`minikube`](https://minikube.sigs.k8s.io/), a tool that lets you run Kubernetes locally. ➿  

❓ **question**: @iQQBot having seen the guidelines you added in https://github.com/gitpod-io/gitpod/pull/6036, I've also noticed you've set up minikube to make it easier to contribute to Gitpod. Would you be up for having a sync chat about the minikube setup? That would be really helpful as we're interested in improving the community contributor experience. @ghuntley could probably join us. 🍵 🍵 🍵 

I'll forward a link to this comment to you also via email for visibility but feel free to also reach out in our discord server[[1](https://www.gitpod.io/chat)] publicly in `#contributing` or via DM (Direct Message). 🤖

**Comment by ghuntley** [comment]
Some additional thoughts:

📝 The destination for a `CONTRIBUTING.md` should be `gitpod-io/.github/CONTRIBUTING.md`
📝 `CONTRIBUTING.md` purpose is to direct people to `https://www.gitpod.io/docs/contributing`
📝 Content existing at `https://www.gitpod.io/docs/contributing` enables capture of feedback (via widgets) and that drives continual improvements.

**Comment by ghuntley** [comment]
Have started scaffolding towards above via:
- https://github.com/gitpod-io/.github/blob/main/CONTRIBUTING.md
- https://github.com/gitpod-io/website/pull/1187
