### ISSUE TITLE
Pylint E0401: Unable to import 'flask'

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#526]
I'm new to pylint and so far I have not been able to remove the E0401: Unable to import error. 
I know it happens because I'm using pyenv and I have installed everything on a virtualenv, so pylint its not able to recognize my installed packages.

I tried using the init-hook on the .pylintrc but nothing: 
```
init-hook='import sys; sys.path.append("/workspace/flask-rest-hello")'
```

What else can I do?

**Comment by AlexTugarev** [comment]
There should be a way to configure the Python language server (we're talking about pylint in editor, right?) Let me check which options do we have there. We might need to add some preference entries for that, then you would be able to customize this per project. This is at least, what I see in vscode.

**Comment by alesanchezr** [comment]
Yes we are talking inside the editor, it marks the lines as with errors:

<img width="589" alt="Screen Shot 2019-04-28 at 6 58 58 PM" src="https://user-images.githubusercontent.com/426452/56871159-c5e51f80-69e7-11e9-907c-12447c381058.png">

Also on the "problems" tab:

<img width="541" alt="Screen Shot 2019-04-28 at 6 59 05 PM" src="https://user-images.githubusercontent.com/426452/56871163-ce3d5a80-69e7-11e9-8093-7fcf5c22ed8b.png">

**Comment by alesanchezr** [comment]
What about something like this on the settings.json?
```json
{
   "python.pythonPath":"venv/bin/python",
   "python.linting.pylintPath": "venv/bin/pylint"
}
```

**Comment by svenefftinge** [comment]
See also https://github.com/Microsoft/vscode-python/issues/865

And https://github.com/Microsoft/vscode-docs/blob/master/docs/python/linting.md#default-pylint-rules :

> These arguments are passed whenever the python.linting.pylintUseMinimalCheckers is set to true (the default). If you specify a value in pylintArgs or use a Pylint configuration file (see the next section), then pylintUseMinimalCheckers is implicitly set to false.

We should do the same or simply switch to the VS Code extension entirely.

**Comment by Esaie88** [comment]
Si vous utilisez le terminal et que vous avez code dans votre chemin, lancez le code VS à partir de votre espace de travail et virtualenv sera chargé automatiquement:

cd python-workspace
code -n python-workspace
(note: le -n est pour nouvelle fenêtre)

Si cela ne fonctionne pas, assurez-vous que pylint est installé dans votre virtualenv (c'est-à-dire que vous n'utilisez pas la variable globale pylint).

**Comment by Esaie88** [comment]
De plus, vous devez ajouter l'entrée suivante dans votre workspace settings sur Visual Studio Code pour éviter l'erreur [pylint] E0401:

"python.linting.pylintPath": "/path/to/your/virtualenv/bin/pylint"
Ceci remplace la variable d'environnement et indique à VSCode d'utiliser la pylint version dans votre env virtuel (au lieu du global one). C'était probablement le point qui vous manquait
