### ISSUE TITLE
Deleting account returns an error and does not log out the user properly

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5262]
### Bug description

When a user tried to delete their account from the Account section in Settings the product returns an error in console and does not log out the user properly.

```js
Uncaught (in promise) Error: Request deleteAccount failed with message:
```

### Steps to reproduce

1. Go to [`/account`](https://gitpod.io/account)
2. Click _Delete Account_ button.
3. Type your email to confirm.
4. Click _Delete Account_.

### Expected behavior

The user should not see any error in the console and they should be properly logged out.

**Comment by JanKoehnlein** [comment]
@gtsiolis could you reproduce this?

**Comment by gtsiolis** [comment]
@JanKoehnlein yes! User deletion seems to happen in the background but a) some errors pop up in the console, b) user is stuck in the deletion modal, and c) reloading the page will not let you login back in the same browser session. Maybe something is not set up properly with cookies or local storage?

| Delete | Login |
|-|-|
| <img width="1440" alt="Screenshot 2021-08-19 at 10 08 57 AM" src="https://user-images.githubusercontent.com/120486/130026184-50ed788a-f284-423a-9fd3-fead1c409b35.png"> | <img width="1440" alt="Screenshot 2021-08-19 at 10 09 18 AM" src="https://user-images.githubusercontent.com/120486/130026308-eb7f91fc-792a-414c-819e-890732ab6b97.png"> |
