### ISSUE TITLE
Update the order of the prebuilds

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5268]
### Problem to solve

Currently, prebuilds order is chronological order, however, ideally the most recent prebuilds need to be at the top of the list.

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="Screenshot 2021-08-19 at 1 58 11 PM" src="https://user-images.githubusercontent.com/120486/130057490-7c736d8a-4c2c-410d-ab5d-24facb0016c1.png"> | <img width="1440" alt="Screenshot 2021-08-19 at 1 58 30 PM" src="https://user-images.githubusercontent.com/120486/130057494-68b29f3c-ec19-486e-bcba-a3c3611ff03d.png"> |

**Comment by AlexTugarev** [comment]
@gtsiolis did you see this in a preview environment, on staging, or on prod ?

**Comment by gtsiolis** [comment]
@AlexTugarev this is reproducible on a) [this preview environment](https://werft.gitpod-dev.com/job/gitpod-build-at-gitlab-projects.26) from https://github.com/gitpod-io/gitpod/pull/5120#issuecomment-901976859, b) staging, and c) production but only when triggering a prebuild manually from the _Branches_ page.
