### ISSUE TITLE
Highlight the default branch for GitLab projects in branches

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5278]
### Problem to solve

GitLab projects do not a) list the default branch on top of all other branches or b) use a label to indicate the default branch.

| Branches for a GitHub project | Branches for a GitLab project |
|-|-|
| <img width="1440" alt="Screenshot 2021-08-19 at 5 40 17 PM" src="https://user-images.githubusercontent.com/120486/130088721-c4530a87-9ffe-4c9f-b421-bb51c412df56.png"> | <img width="1440" alt="Screenshot 2021-08-19 at 5 39 49 PM" src="https://user-images.githubusercontent.com/120486/130088727-062c557a-d2f8-46a9-8a44-ce99039ffcfc.png"> |

**Comment by AlexTugarev** [comment]
This is already resolved in #5120

**Comment by gtsiolis** [comment]
Woohoo! Thanks, @AlexTugarev! 🏀
