### ISSUE TITLE
Change workspaces list filter, garbage collection, and pinning

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5279]
### Problem to solve

**Filters:** The dashboard redesign back in https://github.com/gitpod-io/gitpod/issues/3426 split the workspaces list into _Active_ & _All_. The split was introduced to help educate users about the ephemeral nature of workspaces as users kept coming back to restart stopped workspaces that contained obsolete code. See also [Gitpod's Product Vision](https://www.notion.so/Gitpod-s-Direction-be35d064c0704fbda61c542b84e07ef6) and [relevant blog post](https://www.gitpod.io/blog/cloud-based-development-for-everyone). 🌀 

**Garbage Collection**: Regardless this split, users still find it difficult to keep in mind the active [garbage collection](https://www.gitpod.io/docs/life-of-workspace#garbage-collection) that automatically deletes unpinned workspaces that have been stopped for more than 14 days, even if with the [new non-dismissible alert](https://user-images.githubusercontent.com/120486/111039005-7d487b00-8434-11eb-8d5f-4ff81b83e11f.png) on the top of the stopped workspaces list. ♻️ 

**Pinning**: Thus, pinning workspaces became more like a habit users fallback to maintain a peace of mind. ✌️ 

Besides all the above, we're still receiving a lot of requests from users to restore auto-deleted workspaces, and more.

### Proposal

Things we could try in smaller iterations as MVC (minimum viable changes) or altogether in one step: 
1. Keep all workspaces with pending changes in the _Active_ workspaces list. Potentially auto-pin to avoid confusion.
2. Never garbage collect any workspace with pending changes.
3. Remove the pinning functionality altogether.

**Comment by svenefftinge** [comment]
We cannot never garbage collect, because that would blow up our storage usage. We've been there.

How about moving both active and inactive to one page, where we have a thin separator that starts with the garbage collection warning?

Something like this:

<img width="1170" alt="Screenshot 2021-08-23 at 07 19 58" src="https://user-images.githubusercontent.com/372735/130394459-867ecff5-363e-4526-b160-a72c3d9c0cc7.png">

**Comment by gtsiolis** [comment]
Closing as this has been resolved in #5555. Future improvements could include merging the unified workspaces list (see https://github.com/gitpod-io/gitpod/issues/5861), removing the pinning functionality, re-introducing the global workspaces list, and more.
