### ISSUE TITLE
Autocompletion on java language

### ISSUE THREAD

**Issue by isontheline** [gitpod-io/gitpod#528]
Hello Gitpod Team !

1) Your product is awesome

2) I think I don't use it rightly

When I clone your workspace template "java spring boot", java code autocompletion is working.
But when I clone my own repositories like it :
https://github.com/isontheline/smdr-parser

Autocompletion didn't work :(

Does something need to be added to the config file for Gitpod ?

Have a nice day anyway :)

**Comment by vorburger** [comment]
FYI #529 is a another Java project "nature" (?) related issue

**Comment by meysholdt** [comment]
Hi @isontheline, hi @vorburger, yes, there seems to be a compatibility issue between the Java Language Server and the JDK. This is.... not good. I'm optimistic we can resolve this tomorrow.

**Comment by isontheline** [comment]
Hi @meysholdt,

If you need some tests (or changes in code) on my side : don't hesitate to ask me 🤠

Nice night 😴

**Comment by AlexTugarev** [comment]
Hey @isontheline, hi @vorburger! Thanks for reporting this!
We're testing a fix the issue and going to deploy asap.

**Comment by AlexTugarev** [comment]
http://at-java-version.staging.gitpod.io/#https://github.com/isontheline/smdr-parser should have java support in the editor

**Comment by AlexTugarev** [comment]
<img width="1525" alt="Screen Shot 2019-04-29 at 11 17 18" src="https://user-images.githubusercontent.com/914497/56886901-5ff0aa80-6a70-11e9-8c6a-a2f357e1e856.png">

seems to work with the `smdr-parser` example

**Comment by AlexTugarev** [comment]
'Going to close this once the fixed version is really deployed.

**Comment by AlexTugarev** [comment]
Hey @isontheline, hi @vorburger, the fix is now deployed! 🎉

**Comment by isontheline** [comment]
> Hey @isontheline, hi @vorburger, the fix is now deployed! 🎉

You rock !
Everything is working right now 🤠
Thank you !

**Comment by isontheline** [comment]
Hello,

Since 3 days java autocompletion and live code checking doesn't work anymore :(
