### ISSUE TITLE
Running brew update causes environment to stop

### ISSUE THREAD

**Issue by shafy** [gitpod-io/gitpod#5280]
### Bug description

If I try to run `brew update` in an environment, it first runs for a while and then the environment stops.

### Steps to reproduce

1. Start a default Rails environment from the Gitpod examples
2. Run `brew update`

### Example repository

https://github.com/gitpod-io/template-ruby-on-rails-postgres

### Anything else?

I wanted to update Homebrew because when I was trying to install the Stripe CLI with brew (`brew install stripe/stripe-cli/stripe`) it always returned that there's invalid syntax in the tap. Might this be related?

**Comment by pawlean** [comment]
Hey @shafy! I confirm that my environment also crashes when I try and run a `brew update` in that repo. Thank you for flagging this 🙏🏼

**Comment by shafy** [comment]
Thanks @pawlean ! Do you also have problems installing taps (e.g. `brew install stripe/stripe-cli/stripe`) with that repo or is that unrelated?

**Comment by pawlean** [comment]
I also had the same issue when trying to install stripe. But I'm not 100% sure if it's related to this as I was looking on Stripe's repo and saw others complain about the same issue...🤔 This would definitely need further investigation! Thanks for highlighting.

**Comment by shafy** [comment]
Ok, good to know. Thanks!

**Comment by shaal** [comment]
Is there any update on this issue?
By the way, when running `brew update` during image prebuild, there's no error.

**Comment by JanKoehnlein** [comment]
There used to be a problem with agent smith killing the workspace as `brew update` produced a log line for `xmrig` independent of the actual usage of `xmrig`. Anything in the logs?

**Comment by rl-gitpod** [comment]
> There used to be a problem with agent smith killing the workspace as `brew update` produced a log line for `xmrig` independent of the actual usage of `xmrig`. Anything in the logs?

Confirming that this is still the case when running 'brew update':

`"user ran  blacklisted command: /bin/bash [/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/scm/gitcat-fileblobe811be8b63d911c2e1f479 9e46ec6ee4 e849f :Formula/xmrig.rb
`

**Comment by jankeromnes** [comment]
A potential workaround could be to update `brew` in `gitpod/workspace-full`. That way, there is no need to run `brew update` for a while, and installing the Stripe CLI might work again.

To do this, we can commit one change to the [HomeBrew image layer](https://github.com/gitpod-io/workspace-images/blob/02b4999b13e24032f86bec67aaf0133718e63b7f/full/Dockerfile#L61-L74) in order to invalidate the Dazzle cache and force a rebuild of the HomeBrew layer (looking at the "Blame", it seems that our current `brew` installation is at least 23 days old).

I'll make a PR.

**Comment by jankeromnes** [comment]
> Do you also have problems installing taps (e.g. `brew install stripe/stripe-cli/stripe`) with that repo or is that unrelated?Do you also have problems installing taps (e.g. `brew install stripe/stripe-cli/stripe`) with that repo or is that unrelated?

Hi @shafy! I've fixed the `brew update` problem in https://github.com/gitpod-io/workspace-images/pull/502, but `brew install stripe/stripe-cli/stripe` is still broken for me:

```
$ brew install stripe/stripe-cli/stripe
==> Tapping stripe/stripe-cli
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/stripe/homebrew-stripe-cli'...
remote: Enumerating objects: 315, done.
remote: Counting objects: 100% (147/147), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 315 (delta 48), reused 0 (delta 0), pack-reused 168
Receiving objects: 100% (315/315), 40.29 KiB | 4.48 MiB/s, done.
Resolving deltas: 100% (103/103), done.
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/stripe/homebrew-stripe-cli/stripe.rb
formulae require at least a URL
Error: Cannot tap stripe/stripe-cli: invalid syntax in tap!
```

I think that's due to this bug in Stripe CLI's Homebrew formula: https://github.com/stripe/stripe-cli/issues/645

Alternatively (see last comment in that issue) it seems that you could potentially get a working Stripe CLI via `brew install bfontaine/utils/stripe`.

**Comment by shaal** [comment]
👋 
This issue is back...

To replicate:
* Open any workspace (ie. https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node)
* Run in terminal - `brew update`

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5280#issuecomment-932045958):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by princerachit** [comment]
I could reproduce the error and can see that Agent Smith is penalizes the ws as it is running a blacklisted:
```
user ran  blacklisted command: /bin/bash [/hom /linuxbr w/.linuxbr w/Hom br w/Library/Hom br w/shims/scm/gitcat-fil blob32c831b13f94bd3f378afbb9a8909f18c323b4ca:Formula/xmrig.rbG�G�^pTgitcpus t=/kub pods/burstabl /pod07992a6f-dcd6-4a72-b2aa-ccfb 1cd53b4/2f8658579006bc7c2 6ab0 78 b14903053722 5abf0f1684d0fb71d4af5a2f8cpu=/kub pods/burstabl /pod07992a6f-dcd6-4a72-b2aa-ccfb 1cd53b4/2f8658579006bc7c2 6ab0 78 b14903053722 5abf0f1684d0fb71d4af5a2f8cpuacct=/kub pods/burstabl /pod07992a6f-dcd6-4a72-b2aa-ccfb 1cd53b4/2f8658579006bc7c2 6ab0 78 b14903053722 5abf0f1684d0fb71d4af5a2f8io=/kub pods/burstabl /pod07992a6f-dcd6-4a72-b2aa-ccfb 1cd53b4/2f8658579006bc7c2 6ab0 78 b14903053722 5abf0f1684d0fb71d4af5a2f8m mory=/kub pods/burstabl /pod07992a6f-dcd6-4a72-b2aa-ccfb 1cd53b4/2f8658579006bc7c2 6ab0 78 b14903053722 5abf0f1684d0fb71d4af5a2f8SHELL=/bin/bashHOMEBREW_COMMAND_DEPTH=2HOMEBREW_PROCESSOR=x86_64HOMEBREW_ANALYTICS_ID=UA-76492262-1HOMEBREW_RUBY_WARNINGS=-W1HOMEBREW_REQUIRED_RUBY_VERSION=2.6.3HOMEBREW_BOTTLE_DEFAULT_DOMAIN=https://ghcr.io/v2/linuxbr w/cor HOMEBREW_DEFAULT_LOGS=/hom /gitpod/.cach /Hom br w/LogsHOMEBREW_PREFIX=/hom /linuxbr w/.linuxbr wHOMEBREW_DEFAULT_CACHE=/hom /gitpod/.cach /Hom br wHOMEBREW_SYSTEM=LinuxHOMEBREW_BREW_DEFAULT_GIT_REMOTE=https://github.com/Hom br w/br wPWD=/hom /linuxbr w/.linuxbr w/Hom br wHOMEBREW_VERSION=3.2.14HOMEBREW_BROWSER=gp-pr vi wHOMEBREW_DEFAULT_TEMP=/tmpHOMEBREW_LOGS=/hom /gitpod/.cach /Hom br w/LogsHOME=/hom /gitpodHOMEBREW_CURL=curlHOMEBREW_LINUX_MINIMUM_GLIBC_VERSION=2.13HOMEBREW_EDITOR=/id /bin/cod HOMEBREW_NO_AUTO_UPDATE=1TERM=xt rm-colorHOMEBREW_UPDATE_BEFORE=4 6919b73444 9f9 02ad81d8afc4bbd97533567HOMEBREW_UPDATE_AFTER_HOMEBREW_HOMEBREW_CORE=7f9d28a9c 0d7274 81a94a550cafdbbc33006b8HOMEBREW_RUBY_PATH=/hom /linuxbr w/.linuxbr w/Hom br w/Library/Hom br w/v ndor/portabl -ruby/curr nt/bin/rubyUSER=gitpodHOMEBREW_USER_AGENT_CURL=Linuxbr w/3.2.14 (Linux; x86_64 Ubuntu 20.04.2 LTS) curl/7.68.0HOMEBREW_CELLAR=/hom /linuxbr w/.linuxbr w/C llarHOMEBREW_PATH=/hom /gitpod/.sdkman/candidat s/mav n/curr nt/bin:/hom /gitpod/.sdkman/candidat s/java/curr nt/bin:/hom /gitpod/.sdkman/candidat s/gradl /curr nt/bin:/hom /gitpod/.rvm/g ms/ruby-2.7.3/bin:/hom /gitpod/.rvm/g ms/ruby-2.7.3@global/bin:/hom /gitpod/.rvm/rubi s/ruby-2.7.3/bin:/hom /gitpod/.py nv/plugins/py nv-virtual nv/shims:/workspac /.cargo/bin:/workspac /.pip-modul s/bin:/workspac /.rvm/bin:/id /bin:/workspac /.cargo/bin:/workspac /.rvm/bin:/workspac /.pip-modul s/bin:/hom /gitpod/.py nv/bin:/hom /gitpod/.py nv/shims:/workspac /go/bin:/hom /gitpod/go/bin:/hom /gitpod/go-packag s/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/hom /linuxbr w/.linuxbr w/bin:/hom /linuxbr w/.linuxbr w/sbin/:/hom /gitpod/.nvm/v rsions/nod /v14.17.6/bin:/hom /gitpod/.cargo/bin:/usr/gam s:/usr/gam s:/hom /gitpod/.nvm/v rsions/nod /v14.17.6/bin:/hom /gitpod/.rvm/binHOMEBREW_BREW_FILE=/hom /linuxbr w/.linuxbr w/bin/br wSHLVL=0HOMEBREW_UPDATE_AFTER=4 6919b73444 9f9 02ad81d8afc4bbd97533567HOMEBREW_CORE_GIT_REMOTE=https://github.com/Hom br w/linuxbr w-cor HOMEBREW_REPOSITORY=/hom /linuxbr w/.linuxbr w/Hom br wHOMEBREW_ANALYTICS_USER_UUID=4DBB71AA-26A4-4C2F-8A4A-3E38A8F8EC9ATERMINFO_DIRS=/hom /linuxbr w/.linuxbr w/Hom br w/Library/Hom br w/v ndor/portabl -ruby/curr nt/shar /t rminfoHOMEBREW_UPDATE_BEFORE_HOMEBREW_HOMEBREW_CORE=32c831b13f94bd3f378afbb9a8909f18c323b4caHOMEBREW_USER_AGENT=Linuxbr w/3.2.14 (Linux; x86_64 Ubuntu 20.04.2 LTS)HOMEBREW_BREW_GIT_REMOTE=https://github.com/Hom br w/br wHOMEBREW_PRODUCT=Linuxbr wHOMEBREW_GIT=gitLC_ALL=C.UTF-8HOMEBREW_GIT_CONFIG_FILE=/hom /linuxbr w/.linuxbr w/Hom br w/.git/configPATH=/hom /linuxbr w/.linuxbr w/Hom br w/Library/Hom br w/shims/scm:/usr/bin:/bin:/usr/sbin:/sbinHOMEBREW_UPDATE_TO_TAG=1HOMEBREW_OS_VERSION=Ubuntu 20.04.2 LTSHOMEBREW_LIBRARY=/hom /linuxbr w/.linuxbr w/Hom br w/LibraryHOMEBREW_MINIMUM_GIT_VERSION=2.7.0HOMEBREW_CACHE=/hom /gitpod/.cach /Hom br wHOMEBREW_TEMP=/tmpHOMEBREW_CORE_DEFAULT_GIT_REMOTE=https://github.com/Hom br w/linuxbr w-cor TMPDIR=/tmp�^����ad7040]
```

**Comment by princerachit** [comment]
I have raised a similar workaround PR https://github.com/gitpod-io/workspace-images/pull/517 again but we need to find a better way to deal with this issue.
