### ISSUE TITLE
Add better Projector Support

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/gitpod#5282]
We list Jetbrains as an integration in our docs https://www.gitpod.io/docs/integrations/jetbrains while the developer experience includes lot of friction. 

According to a recent post people seem to be satisfied with Projector https://youtrack.jetbrains.com/issue/IDEA-226455#focus=Comments-27-5088721.0-0

Adding the Jetbrains Fleet as an option to Gitpod is also #1 requested feature from one of our largest customers

**Comment by svenefftinge** [comment]
I agree, it would be great. We have too many other things and loose ends in the pipeline atm. Given that people [can use Projector already](https://www.gitpod.io/docs/integrations/jetbrains) and that the [Jetbrains' remote development seems around the corner](https://youtrack.jetbrains.com/issue/IDEA-226455#focus=Comments-27-5125731.0-0). Suggest we unschedule this for now. Please put it back in one or two months.
