### ISSUE TITLE
browser extension: This item is age restricted. To view it, sign in to your account.

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5284]
### Bug description

<img width="823" alt="2021-08-20_11-47-22" src="https://user-images.githubusercontent.com/127353/130166165-e165eceb-2786-431d-a17d-3ad73229c93a.png">

### Steps to reproduce

https://chrome.google.com/webstore/detail/gitpod-dev-environments-i/dodmmooeoklaejobgleioelladacbeki?hl=en

### Expected behavior

Should be able to view or install the Gitpod browser extension if under 18 but above 13.

### Anything else?

After signing in with 18+ account the store listing is displayable

<img width="1280" alt="2021-08-20_11-50-47" src="https://user-images.githubusercontent.com/127353/130166432-7717a68c-bbc4-427b-b6a5-a03a6912a9db.png">

**Comment by JanKoehnlein** [comment]
While this may look strange, this is according to our ToS

> By the time of sign-up the Customer must be at least 18 years old and fully contractually capable. In case of doubt Gitpod is entitled to ask the individual Customer to submit a documentary evidence of age or contractual capability.

I know that GitHub allows minors as well, but European/German law forbids entering any contract with minors.
