### ISSUE TITLE
If a person belongs to the GitHub organisation @maintainers then automatically upgrade their account

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5285]
If a person belongs to the GitHub organisation https://github.com/maintainers (circa 2400 people) then automatically upgrade their account to the [Gitpod is free for open-source maintainers plan](https://www.gitpod.io/docs/professional-open-source) when they access Gitpod. Thus removing the need for people to do applications to Gitpod by hand and reducing our customer support burden. This would not replace the manual application process because not everyone belongs to `@maintainers` and our 🧡 campaign for people who make open-source possible should not be gated by whom GitHub accepts into their closed community.

**Comment by svenefftinge** [comment]
If it's only 2400 people I wonder if it's really worth the extra engineering effort and having special code in our system for such a small special case.

**Comment by gtsiolis** [comment]
Also, this seems to be an inactive community group since 2019, right? See also [README](https://github.com/maintainers/public-resources#readme).

> We are not currently accepting applications, but we may do so in the future.

Removing from Product Groundwork / Inbox for now.
