### ISSUE TITLE
Java support not working if the POM & code is in a sub-directory

### ISSUE THREAD

**Issue by vorburger** [gitpod-io/gitpod#529]
**Describe the bug**
https://spectrum.chat/gitpod/general/how-do-you-get-java-support-working-if-the-pom-code-is-in-a-sub-directory~4a13cbc1-ac11-4b39-97a7-c888faf7f1a9

**To Reproduce**
https://github.com/vorburger/apps.learn.study (as of rev. ee4a8e34f535dfc8f0cfec276d57f9df879143a9)

**Expected behavior**
https://gitpod.io/#github.com/vorburger/apps.learn.study should have Java support.

**Comment by vorburger** [comment]
FYI #528 seems to report that Java support is NOK even for a simpler project with simple POM at root?

**Comment by AlexTugarev** [comment]
@vorburger, you're right, this is the same as #528.
