### ISSUE TITLE
[Feature request]add ready-to-code pull request to welcome screen.

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#5290]
I find it `Fully automate dev setup with Gitpod` feature is missing after switch to vscode.
Maybe we can add it back like in welcome screen.

Old PR generated by this: https://github.com/gengjiawen/monkey-rust/pull/1.

**Comment by svenefftinge** [comment]
We should add a comment through the app to PRs that lists two links
 - to the prebuild page
 - start a dev environment

**Comment by gengjiawen** [comment]
Any update on this ? I have been add gitpod to more repos. but this get need lots of work compared to old days.

**Comment by gengjiawen** [comment]
@stale not stale

**Comment by gengjiawen** [comment]
not stale

**Comment by geropl** [comment]
@gengjiawen Do I understand correctly that you basically want the old "Gitpodify my project wizard" back? :thinking: IMO there was a bit of confusion before :point_up:

**Comment by gengjiawen** [comment]
> @gengjiawen Do I understand correctly that you basically want the old "Gitpodify my project wizard" back? 🤔 IMO there was a bit of confusion before ☝️

yeap. that's a fastest way I can add badge to `README.md`
