### ISSUE TITLE
Allow users to add projects in teams from self hosted GitHub providers

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5297]
### Problem to solve

Following https://github.com/gitpod-io/gitpod/issues/5115, the upcoming **Teams & Projects** feature supports adding repositories from GL (gitlab.com) and GH (github.com) but does not support projects from self hosted GitHub instances.

**Comment by AlexTugarev** [comment]
This is solved in https://github.com/gitpod-io/gitpod/issues/8501
