### ISSUE TITLE
[Java] Add support for Lombok

### ISSUE THREAD

**Issue by php-coder** [gitpod-io/gitpod#53]
In my project I'm using Lombok (https://projectlombok.org/) to reduce boilerplate code. Gitpod doesn't know about it and it shows a lot of errors because I doesn't see generated getters/setters and constructors.

It would be great to have a support for Lombok. Thanks!

**Comment by svenefftinge** [comment]
This ticket https://github.com/redhat-developer/vscode-java/issues/458 sounds like it works if one specifies the lombok agent as a command line arg.

**Comment by daredkar** [comment]
Even I'm looking for Lombok support in gitpod.
Do we have any workaround for the same ?

**Comment by stackedone** [comment]
> This ticket [redhat-developer/vscode-java#458](https://github.com/redhat-developer/vscode-java/issues/458) sounds like it works if one specifies the lombok agent as a command line arg.

Doesn't work with 
`"java.jdt.ls.vmargs": "-javaagent:/workspace/m2-repository/org/projectlombok/lombok/1.18.8/lombok-1.18.8.jar -Xbootclasspath/a:/workspace/m2-repository/org/projectlombok/lombok/1.18.8/lombok-1.18.8.jar -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication"`

**Comment by OLibutzki** [comment]
Any progress regarding this one? There a a lot of Java projects using Lombok and I didn't manage to get them working in Gitpod so far.

**Comment by akosyakov** [comment]
@OLibutzki coudl you give me an example project? I may try to gitpodify it properly

**Comment by php-coder** [comment]
@akosyakov I can share my pet project: https://github.com/php-coder/mystamps For example, [`CountryServiceImpl`](https://github.com/php-coder/mystamps/blob/master/src/main/java/ru/mystamps/web/feature/country/CountryServiceImpl.java) or [`LinkEntityDto`](https://github.com/php-coder/mystamps/blob/master/src/main/java/ru/mystamps/web/common/LinkEntityDto.java)

**Comment by meysholdt** [comment]
Does installing https://open-vsx.org/extension/cool2k/vscode-lombok not resolve the issue?

**Comment by akosyakov** [comment]
@meysholdt I will assume so 👍 I am not sure what was wrong, but I am not getting any errors after installing it:
<img width="1904" alt="Screenshot 2020-12-11 at 10 58 13" src="https://user-images.githubusercontent.com/3082655/101889547-cec83c00-3b9f-11eb-8b56-5b80e53ed8e5.png">

**Comment by OLibutzki** [comment]
Sorry for replying that late. Yes, installing the extension resolves the issue.

Issue can be closed.
