### ISSUE TITLE
Development environment with multiple hostnames

### ISSUE THREAD

**Issue by Ro-phon** [gitpod-io/gitpod#5306]
Hi,

I couldn't figure out how to configure multiple hostnames.

We have a PHP project that consists of different services.

- api.myproject.com
- www.myproject.com
- admin.myproject.com
- clientA.myproject.com
- admin-clientA.myproject.com
- ...

Routing is done at application level.

While Googling this I saw a (very) similar question but unfortunately it got closed https://github.com/gitpod-io/gitpod/issues/1962

**Comment by akosyakov** [comment]
Have you tried to use subdomains of localhost, i.e. api.localhost.com, www.localhost.com, admin.locahost.com and so on. In this case you can make use of [the local companion](https://www.gitpod.io/blog/local-app). It auto tunnels services from a Gitpod workspace to provide them on localhost similarly how you will do in usual local setup.

An alternative but trickier, is to use your own DNS server which resolves against the Gitpod workspace. Something like that was done here: https://github.com/gitpod-io/gitpod/issues/898#issuecomment-899938625
