### ISSUE TITLE
Support custom images with labels, like toolbox?

### ISSUE THREAD

**Issue by carrete** [gitpod-io/gitpod#5307]
I understand some distros can't be supported because of libc issues, as in https://github.com/gitpod-io/gitpod/issues/3356, but what other issues would prevent supporting distros like Fedora which does use the correct libc? (Fedora 34 didn't work for me. The gitpod layer couldn't be applied.) I wonder if there's another way to address this issue. Toolbox supports custom images which must also meet certain requirements, https://github.com/containers/toolbox#image-requirements. Toolbox assumes these requirements have been met if a particular label exists. I wonder if a similar approach (instead of applying the gitpod layer) would be better?

**Comment by akosyakov** [comment]
I think we discussed couple times to build for different archs, but it will add overhead on our side to build them and can somehow affect startup performance, maybe because of low image reuse not sure. cc @csweichel

**Comment by svenefftinge** [comment]
Can you share some reasons why supporting many different distros would be important? Just to get a bit more info to balance on the effort vs. value side.

**Comment by carrete** [comment]
> but it will add overhead on our side to build them

@akosyakov, The idea is to not build the gitpod layer, but instead use the existence of labels to check that the image has been built to the proper specs. Or instead of labels, a script that can be run as a command which outputs details about the image.

**Comment by carrete** [comment]
@svenefftinge, Ubuntu has made many packages snap only which cannot be run in containers, such as chromium,  is one such reason.
