### ISSUE TITLE
Allow users to search recent and examples in the new workspace modal

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/gitpod#5309]
When creating a new workspace from a template-repo, a search-function might be added to seach the existing templates.
![grafik](https://user-images.githubusercontent.com/43843195/130364570-e771fd43-d87b-4242-b6c2-004d61370785.png)

**Comment by gtsiolis** [comment]
Thanks @Cahllagerfeld! Using a search input could suffice here although skipping search could be also ok given this list will most probably remain finite. I've spent some time on how this could look like, see [design specs](https://www.figma.com/file/oBYyoZsASNu1jHLXQUHNfc/New-Workspace-Modal-Search-3534?node-id=0%3A1). Posting below some screenshots:

| Modal with search input | Modal with no results |
|-|-|
| <img width="1440" alt="New Workspace Modal Search" src="https://user-images.githubusercontent.com/120486/131333772-d518903d-63ed-45e7-b78b-addaee2bac42.png"> | <img width="1440" alt="New Workspace Modal Search - Empty" src="https://user-images.githubusercontent.com/120486/131333777-fa969bab-95c5-493c-9f38-9e17cc824d55.png"> |

**Comment by Cahllagerfeld** [comment]
They look amazing!

**Comment by gtsiolis** [comment]
Removing this from **Product Groundwork** as design specs are already in place in https://github.com/gitpod-io/gitpod/issues/5309#issuecomment-908272776 but engineering bandwidth is limited for the next couple of weeks. Added help wanted label in case any community member would like to contribute with this change. 🌳

**Comment by gtsiolis** [comment]
Still relevant. Cc @jldec

**Comment by jldec** [comment]
Closing in favor of #7564 which provides a similar search-like UX using a text input with auto-suggest.
