### ISSUE TITLE
Add Suport for gitlab.cn

### ISSUE THREAD

**Issue by sunny0826** [gitpod-io/gitpod#5311]
Hi, I'm a [gitlab.cn](https://about.gitlab.cn/) team member and a loyal user of gitpod. Currently gitpod integrates well with `gitlab.com`, and I would like to integrate with `gitlab.cn`, both in the gitlab platform and in browser extensions, and I will help in any way I can. This will also bring more users from China to gitpod.

/label `git provider: gitlab` `component: browser-extension`

**Comment by svenefftinge** [comment]
Did you try to add gitlab.cn as a self-hosted GitLab as described [here](https://www.gitpod.io/docs/gitlab-integration#connecting-your-self-hosted-gitlab-account)?

**Comment by sunny0826** [comment]
> Did you try to add gitlab.cn as a self-hosted GitLab as described [here](https://www.gitpod.io/docs/gitlab-integration#connecting-your-self-hosted-gitlab-account)?

Sure, that's what I'm currently doing. I imported my project by prefixing the url with `gitpod.io/#` and had a great experience. But I would like `gitlab.cn` to automate the configuration like `gitlab.com` does.

**Comment by sunny0826** [comment]
@svenefftinge Bad news, currently only my account on gitlab.cn integrates with gitpod, other colleagues show `Provider for this host already exists.` when integrating, so it is not available to our SaaS users.

**Comment by svenefftinge** [comment]
You need to install the integration once. The other users should be able to authorize by just opening a gitlab.cn repo with gitpod. I.e. `https://gitpod.io/#https://gitlab.cn/group/repo`

**Comment by sunny0826** [comment]
@svenefftinge  thx, I'm now looking for more team member to try gitpod, and we'll be integrating gitpod more deeply in [GitLab 14.2](https://about.gitlab.com/releases/2021/08/22/gitlab-14-2-released/#launch-a-preconfigured-gitpod-workspace-from-a-merge-request).
