### ISSUE TITLE
automatically enable "product tips" notifications for existing users

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#5315]
**Context:**
we just introduced a third notification option ("Developer Experience & Product Tips") to the notification preferences. This preference is automatically enabled for all new users but disabled for existing ones. 

**Proposed solution:**
enable the checkbox for "Developer Experience & Product Tips" for all users that formerly allowed marketing emails. 
Note: We set the "changelog" checkbox to active for all users that formerly allowed product emails and deleted the product email information in the DB. So we can't access that information anymore. But we could set "Developer Experience & Product Tips" emails to active for everyone that has "Changelog" enabled as well. 

It's quite unlikely that someone already unsubscribed from the "Developer Experience & Product Tips" emails, as the change went live at the end of last week and the last DevX email has been sent on August 4th. 

To avoid manual extra work for users that unsubscribed to "Developer Experience & Product Tips" emails, it would make sense to implement this change as soon as possible.
<img width="1083" alt="Bildschirmfoto 2021-08-23 um 10 02 28" src="https://user-images.githubusercontent.com/46345125/130419973-a4d69a06-3ff8-4f08-8b8e-db8b58c57679.png">

cc @laushinka

**Comment by roboquat** [comment]
@csweichel: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5315#issuecomment-905476275):

>/team meta
>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5315#issuecomment-905476381):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
@atduarte Could we find out how many users unsubscribed from the DevX mail in these two weeks?

**Comment by atduarte** [comment]
The users that changed the `unsubscribe_devx` attribute are listed [here](https://fly.customer.io/env/106338/activity_logs/identified?name=unsubscribed_devx&type=attribute_change). There are only two of them as of now, and one of them is invalid (not sure how it appeared in customer.io).

**Comment by laushinka** [comment]
> The users that changed the `unsubscribe_devx` attribute are listed [here](https://fly.customer.io/env/106338/activity_logs/identified?name=unsubscribed_devx&type=attribute_change). There are only two of them as of now, and one of them is invalid (not sure how it appeared in customer.io).

@atduarte Hmm. I wonder why `unsubscribed_changelog` (previously `unsubscribed`) isn't there, while `unsubscribed` is still generating events even today. I'm only cc-ing @jakobhero because he's on vacation, but maybe this is something that needs to be looked into.

**Comment by laushinka** [comment]
@ChristinFrohne From the link that @atduarte sent, it looks like hundreds of unsubscriptions are happening, and it could be the ones for Changelog. We don't know because `unsubscribed_changelog` isn't part of the dropdown, so we have to investigate whether something went wrong.

There are two things that I propose should happen:
1. Figure out whether something went wrong downstream. @jakobhero or @atduarte can investigate or point me to where I can figure this out.
2. Rethink the importance of this ticket, considering the time that will continue to pass. @ChristinFrohne

**Comment by atduarte** [comment]
@laushinka `unsubscribed_changelog` does not show up because there was no "Attribute Change" event that affected it

**Comment by laushinka** [comment]
> @laushinka `unsubscribed_changelog` does not show up because there was no "Attribute Change" event that affected it

@atduarte I thought that too, but then I triggered it using my account (laurie@gitpod.io), and it still doesn't show up in the logs..

**Comment by ChristinFrohne** [comment]
>Rethink the importance of this ticket, considering the time that will continue to pass. @ChristinFrohne

It's quite important as without that change we would miss out to send DevX Emails to +110k existing users that formerly allowed these emails. 

Can we not activate the devX checkbox for everyone that allows "changelog" emails minus the two users that recently unsubscribed from DevX?

**Comment by laushinka** [comment]
> Can we not activate the devX checkbox for everyone that allows "changelog" emails minus the two users that recently unsubscribed from DevX?

@ChristinFrohne I will do this. For the two that recently unsubscribed I will ask @atduarte to do this manually, since it will be easier than a DB migration script.

**Comment by atduarte** [comment]
@laushinka we can activate for everyone and use the new /unsubscribe URL to manually unsubscribe the required users. Although, I should warn that at the moment given #5440 we are unable to determine whether we had more users unsubscribing.
