### ISSUE TITLE
Error while adding Gitpod layer.

### ISSUE THREAD

**Issue by Alaboudi1** [gitpod-io/gitpod#532]
**Describe the bug**
I have been trying to use Gitpod for projects that I have on my dashboards but got this error message no matter what the project is. I really like Gitpod and would like to see it works very reliably.
![2019-04-29_10-52-51](https://user-images.githubusercontent.com/16814184/56905086-97aa2300-6a6d-11e9-919e-52f5bc8e800e.jpg)

**Comment by AlexTugarev** [comment]
Hi @Alaboudi1, thanks for reporting! Could you please share your docker file with us? I'd like to understand what the actual error is.

**Comment by Alaboudi1** [comment]
I am not sure what you mean by sharing my docker file. I am not very familiar with Gitpod, so I may just misuse it :). Here is my use case: I heard about Gitpod 3 months ago. So I went and cloned random GitHub repositories just to try it. It worked great at that time. Fast forward today, I went back to my dashboard and decided to start one of these projects that I cloned months ago, and I got this error. 
![2019-04-29_12-14-10](https://user-images.githubusercontent.com/16814184/56910651-15276080-6a79-11e9-88a0-4696ac0bdcc6.jpg)

Is there something wrong with the way I used Gitpod? If so, what is the typical workflow for it?

**Comment by AlexTugarev** [comment]
@Alaboudi1, I assumed you'd had a custom docker image for your workspace. But in your case it might be a braking change with the Gitpod Layer introduced a while ago. We'll try to investigate this.

Please feel free to start over and create a new workspace for [`rust-lang/rust-by-example`](http://gitpod.io/#https://github.com/rust-lang/rust-by-example)

**Comment by Alaboudi1** [comment]
Cool, thanks for replying. It would be nice to have Gitpod recovering from this error by offering an option to construct a new workspace for me. But for now, I am happy to do it manually :).

**Comment by geropl** [comment]
@Alaboudi1 Just to let you know, we're working on two things here:
 1. Resolve the root cause (a stupid `apt-get` thing)
 1. improve the UX to allow to recover from a failed build

**Comment by Sashenka** [comment]
I still have the Gitpod Layer problem, failing on step 5/14. I had it last week, it was resolved friday, I had a new loading 'experience' with a more verbose log. Now I'm back to have it fail again like last week. I'm in no hurry, just saying it still happens to me :)

**Comment by svenefftinge** [comment]
@Sashenka can you share your repo or a equivalent for reproduction?

**Comment by Sashenka** [comment]
@svenefftinge Sure thing!
My workspace ID is d81306eb-db25-4031-8041-fc35dc4e3dc2, repo https://github.com/Sashenka/node-steamapi-es2017. Creating a new Workspace from the repo works but I had uncommited changes left when I left in a hurry Friday and forgot to commit. It's nothing vital, just something I use to learn and mess around but if it is recoverable it would be nice. Thanks.
![Annotation 2019-05-07 214723](https://user-images.githubusercontent.com/729223/57343551-c8dfbe80-7111-11e9-9350-f0307012fda1.png)

**Comment by geropl** [comment]
@Sashenka We are working on a fix. Sorry for the inconvenience.

**Comment by meysholdt** [comment]
hey @Sashenka! thank you for the details and I'm sorry for the trouble. I'll contact you via email to help recover your workspace.

**Comment by RobertWalter83** [comment]
Hi all, the same error happens for me when I try to do the Xtext/Theia/Sprotty tutorial, using the "open in Gitpod" buttons provided in the Readme file, maybe it's a useful additional piece of information: https://github.com/TypeFox/theia-xtext-sprotty-example

**Comment by svenefftinge** [comment]
Hey Robert, I couldn't reproduce any issues. I tried:
https://gitpod.io/#https://github.com/TypeFox/theia-xtext-sprotty-example

Could you elaborate on what you see?

**Comment by RobertWalter83** [comment]
Hi Sven,
you are right, adding the prefix to the github repository address works for me as well. 
My issue, however, is with opening the tutorial's snapshots provided as "open in github"-buttons within the README:
![gitpod_issue](https://user-images.githubusercontent.com/5462981/57427896-3977ff80-7226-11e9-806d-3f5d5de18a10.gif)

**Comment by geropl** [comment]
Will close when deployed.

**Comment by geropl** [comment]
Just deployed the fix that tamed `apt-get`.
