### ISSUE TITLE
[ws-daemon] "cannot set new CPU limit"

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5326]
We see [many logs](https://cloudlogging.app.goo.gl/LoZdKzdCA4za84zt9) with this error:
```
cannot set CFS quota:
    github.com/gitpod-io/gitpod/ws-daemon/pkg/resources.cgroupCFSController.SetQuota
        github.com/gitpod-io/gitpod/ws-daemon/pkg/resources/controller.go:443
  - write /mnt/node-cgroups/cpu/kubepods/burstable/pod5d57bb02-8a7e-47db-a25b-8edd352b6e6d/c53ad2cbf8675ea43a40ca5e3549b991b9bba45197370d75d8ef2b616f949422/cpu.cfs_quota_us: invalid argument"
 ```

**Comment by aledbf** [comment]
@svenefftinge this is the reason why I added addition context in ws-daemon to understand the reason https://github.com/gitpod-io/gitpod/pull/5082

**Comment by csweichel** [comment]
I have only ever seen this issue when ws-daemon tried to set the value that was already set. E.g. the quota is set to `6000` and we try to set it to `6000` again.
