### ISSUE TITLE
Change existing string values in DB to booleans

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#5328]
### Bug description

![Screenshot 2021-08-23 at 09 15 25](https://user-images.githubusercontent.com/8015191/130458252-7f6cf7ca-32f0-4186-9ac6-079a5b668d1d.png)

Some values of allowsChangelogMail are strings when they should be booleans. This was caused by a migration on 20.08.2021 where the query incorrectly populated the field as strings, therefore it only affected data up to that date.

### Steps to reproduce

1. Connect to the Gitpod DB in production.
2. Run `select name, additionalData from from d_b_user`.

### Expected behavior

"allowsChangelogMail" should be either `true` or `false`.

**Comment by svenefftinge** [comment]
Maybe tackle this together with https://github.com/gitpod-io/gitpod/issues/5315
