### ISSUE TITLE
Colors highlighting changes in the middle of the code

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#533]
**Describe the bug**
Sometimes the colors get weird, look at this screenshot:

![Screen Shot 2019-04-29 at 1 22 44 PM](https://user-images.githubusercontent.com/426452/56914511-49534f00-6a82-11e9-9b6d-38dd50bb5093.png)

Note: The JSON has no syntax problem.

**To Reproduce**
Create a huge JSON file and eventually, parts of the file will be in different colors all the sudden.

**Expected behavior**
Colors highlighted to be consistent.

**Comment by svenefftinge** [comment]
We have a threshold for the coloring for how long lines can be. We simply stop tokenizing after that, which leaves the coloring in a bad state afterwards.

**Comment by alesanchezr** [comment]
Ok, I can use a linter/prettier to fix lines. Thanks for the response!
