### ISSUE TITLE
Default to personal account when importing a project from GitLab

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5331]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/5120#discussion_r690469441, when trying to import a project from GitLab,  the pre-selected account is a specific but maybe random group.

### Proposal

Default to personal account when importing a project from GitLab. 🦊

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5331#issuecomment-924744946):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by gtsiolis** [comment]
Friendly reminder, this is only needed when Teams & Projects is enabled for a user. 🎗️
