### ISSUE TITLE
Add a hyperlink to the provider when importing a project

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5333]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/5120#discussion_r690460216, when importing a project, a text version of the provider domain is shown. We could provide a quick link back to that provider so that users could inspect project membership, create new projects, etc. that they can import in Gitpod.

Similar to the project header for Branches that links to the project itself, simply adding a hyperlink to the provider when importing a project could suffice.

| Project | Branches New Project |
|-|-|
| <img width="397" alt="Screenshot 2021-08-23 at 8 51 30 PM (2)" src="https://user-images.githubusercontent.com/120486/130493775-fefc8e3a-4bb9-4d22-b834-0e89f88fa324.png"> | <img width="460" alt="Screenshot 2021-08-23 at 8 47 54 PM (2)" src="https://user-images.githubusercontent.com/120486/130493658-d374aea2-a4c5-43d6-ae74-dcc45a70bde6.png"> |

**Comment by trumbitta** [comment]
> Looping in @jldec in case this could seem useful to keep around. Ideally, we could get rid of the change link next to the provider here. 💡

I find the *change* link pretty useful here! I have repos both on GitLab and on GitHub and that little link helps keeping me sane 😄 

I'm all for adding the new proposed link 👍

**Comment by jldec** [comment]
Thanks @gtsiolis and @trumbitta - I think what we have now works reasonably well (I like the change link too).
closing

---

![Screenshot 2022-01-01 at 20 46 34](https://user-images.githubusercontent.com/849592/147860126-190c2cdc-7f86-4f74-a1f3-7ed8a33ebce6.png)
