### ISSUE TITLE
[Projects] Cannot access prebuild logs if not project owner

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#5344]
### Bug description

When trying to access prebuild logs of a project where I'm not the installation owner, I see the following error `missing get permissions on workspace`.  The error does not appear on projects which I installed.

<img width="931" alt="Screen Shot 2021-08-24 at 10 24 21" src="https://user-images.githubusercontent.com/914497/130589582-270d38d6-1a3c-47d2-bf23-8defec141ffd.png">

The API operations we are using in `PrebuildLog.tsx` are `getWorkspace`, `watchWorkspaceImageBuildLogs`, and `getHeadlessLog(instanceId)`, all of which compare the workspace owner with the current user and block on mismatch. 

### Proposed solution

`PrebuildLog.tsx` would call a dedicated `getPrebuildLog(prebuildId)` which would map from `prebuildId` to the underlying instance and also check for team permissions. This way, we would only relax the access guard within a team, and only for the necessary operation.

**Comment by gtsiolis** [comment]
Could not easily reproduce but sounds something we need to fix before shipping **Teams & Projects**. Adding this to the crew proejct board for now. Thanks @AlexTugarev!

**Comment by geropl** [comment]
@AlexTugarev FYI: WorkspaceLogs already has a [`RessourceAccessGuard`](https://github.com/gitpod-io/gitpod/blob/main/components/server/src/auth/resource-access.ts#L440) which allows everyone with "read" permission to repo to access the logs. Maybe we can re-use that for other stuff as well.

But I wonder if we should lift the permissions for `getWorkspace` in general. Maybe it'd be better to ask why we need it on the `PrebuildLogs.tsx` and replace it with (guarded) substitutes.
