### ISSUE TITLE
Two same class in different java file which they are both public

### ISSUE THREAD

**Issue by ForresterLu** [gitpod-io/gitpod#535]
**Describe the bug**

Two same class in different java file which they are both public,I thought an error should be throwed out.
**To Reproduce**

![image](https://user-images.githubusercontent.com/26716009/57002405-a9b4ce80-6bf1-11e9-8415-16be2be47114.png)

**Expected behavior**

Show an error to warn me.

**Comment by svenefftinge** [comment]
You should see something like this:
<img width="592" alt="Screenshot 2019-05-01 at 08 27 50" src="https://user-images.githubusercontent.com/372735/57007711-0c569c00-6beb-11e9-996c-d90e32c56cad.png">

But you some basic Java project configuration like a `maven`, `gradle`  or `eclipse` config.
