### ISSUE TITLE
Can't log in using GitHub account

### ISSUE THREAD

**Issue by robertlyson** [gitpod-io/gitpod#5361]
### Bug description

Hi,

I'm trying to log in using my GitHub account but after providing my credentials I'm receiving "Your browser did something unexpected" message.

![gif (22)](https://user-images.githubusercontent.com/2392583/130639341-1200061e-d980-41c8-8371-0084717f2386.gif)

Looks like the call `POST https://github.com/session` end up in status 422.

![image](https://user-images.githubusercontent.com/2392583/130639528-7b05c4c4-6115-4021-83f1-079b88fdaaae.png)

My GitHub account has 2FA enabled.

Seems to be working fine when I log in via private mode / window so tried to clean cookies for https://gitpod.io but that didn't help.

![gif (24)](https://user-images.githubusercontent.com/2392583/130640726-3d88bd0a-24e4-4ca3-a508-5862a4770c43.gif)

### Steps to reproduce

- go to https://gitpod.io/login/
- click on "Continue with GitHub
- provide GitHub credentials

**Comment by AlexTugarev** [comment]
Hi @robertlyson! It looks like you cannot login into github.com actually. Please try to login on github.com first.

**Comment by robertlyson** [comment]
Hi @AlexTugarev, thanks for the response! Actually, I'm already signed in to github.com otherwise I wouldn't be able to post comments here, but when I open a new tab and I go to gitpod.com and click `Continue with GitHub` I'm experiencing an error from the gif above.

**Comment by robertlyson** [comment]
Maybe this one will show better what I'm experiencing

![gif (25)](https://user-images.githubusercontent.com/2392583/130749408-5f27685d-940a-41f9-a865-69cbd99d9bfd.gif)

The funny thing is, it's all works fine when I try to log in into gitpod with GitHub in the browser's private session.

**Comment by AlexTugarev** [comment]
@robertlyson you are right about that. Still, github.com asks you to sign in. Which fails in turn, see the relevant part of your recording:

<img width="852" alt="Screen Shot 2021-08-25 at 09 47 28" src="https://user-images.githubusercontent.com/914497/130749119-e6833249-0ce1-4347-9544-73b083b54677.png">

Could it be some browser extension that limits access to github.com or any redirects back to gitpod.io?
Can you share some more details on the browser you are using?

**Comment by robertlyson** [comment]
@AlexTugarev also GitHub doesn't ask me about 2FA code from auth app when redirecting from gitpod.io.
I'm using the latest version of https://brave.com browser. 

>Could it be some browser extension that limits access to github.com or any redirects back to gitpod.io?

Will try to disable all extensions and see how that does.

**Comment by robertlyson** [comment]
Just noticed, that when my sign-in to GitHub from gitpod fails, my original GitHub sessions die.

**Comment by robertlyson** [comment]
Disabled all extensions in Brave and now works like a charm, let me just find which one was causing pain and will let you know ;)

**Comment by robertlyson** [comment]
@AlexTugarev it was Bitdefender Anti-tracker extension, thanks for your help and thanks for gitpod.io, great tool <3

**Comment by AlexTugarev** [comment]
That's good news, @robertlyson! Happy coding!
