### ISSUE TITLE
Unable to create Gitpod workspace from Bitbucket private branch with format "feature/JIRA-123-summary"

### ISSUE THREAD

**Issue by ryanolsonx** [gitpod-io/gitpod#5364]
### Bug description

I've been trying to start using Gitpod at work. While attempting to open a Bitbucket branch in the format "feature/JIRA-123-summary", I encounter an error "Oh, no! Something went wrong!" message with "Not found." When looking at your code, I'm not sure that the bitbucket-context-parser accounts for this scenario.

### Steps to reproduce

1. Create a private repository with branch "feature/JIRA-123-summary"
2. Open https://gitpod.io/#https://bitbucket.org/owner/repository/branch/feature/JIRA-123-summary
3. Notice "Oh, no! Something went wrong!" message with "Not found"

### Expected behavior

I expect to be able to open up a Gitpod workspace from a branch in Bitbucket.

**Comment by ghuntley** [comment]
Observations are as follows:

1. Created https://bitbucket.org/ghuntley/gitpod-issue-5364 (as a public repository)
2. Pushed `feature/JIRA-123-summary` branch
3. Navigated to the branch in the Bitbucket UI which yields https://bitbucket.org/ghuntley/gitpod-issue-5364/src/9534e0b7e346f5908168cb13ea788d7ad2f8e2fa/?at=feature%2FJIRA-123-summary
4. Open with Gitpod button launches repository
5. Source code is cloned at `9534e0b` with _detached head_ and not `feature/JIRA-123-summary`

<img width="345" alt="2021-08-25_15-26-05" src="https://user-images.githubusercontent.com/127353/130731473-141083ae-fd0a-4713-b896-3557dab444d7.png">

6. Change privacy of https://bitbucket.org/ghuntley/gitpod-issue-5364 to private
7. Navigated to the branch in the Bitbucket UI which yields https://bitbucket.org/ghuntley/gitpod-issue-5364/src/9534e0b7e346f5908168cb13ea788d7ad2f8e2fa/?at=feature%2FJIRA-123-summary
8. Used open with Gitpod button to create a new workspace.
9. Source code is cloned at `9534e0b` with _detached head_ and not `feature/JIRA-123-summary`

So I've been unable to replicate the problem of creating the workspace @ryanolsonx however checking out as a detached head isn't the behaviour that I would expect as GitHub/BitBucket clone using the exact branch name.

**Comment by ghuntley** [comment]
Pushed https://bitbucket.org/gitpod/sample-repository/branch/feature/JIRA-123-summary as a test case.

**Comment by gtsiolis** [comment]
Adding this in groundwork in case the WIP in https://github.com/gitpod-io/gitpod/pull/5367 is 90% DONE and anyone from meta team could pick it up and push it through the finish line. 🏁

Cc @jldec @JanKoehnlein   

/schedule
