### ISSUE TITLE
Gitpod incorrectly reports `offline` when opening a huge file in the editor

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#537]
**Describe the bug**

Gitpod reports `offline` on the status bar when opening a fairly big file in the editor.

**To Reproduce**
 - Open your WS.
 - Click on a huge file in the navigator.
 - The `offline` status is reported, you have to wait.
 - You get back the `online` status once the editor has opened.

**Expected behavior**
 - Do not report offline, or
 - [Do **not** open that huge file](https://github.com/theia-ide/theia/issues/4731).

**Comment by alesanchezr** [comment]
This issue is the sames as #545

**Comment by kittaakos** [comment]
> This issue is the same as #545

Why? #545 reports offline when downloading a file. I had the issue when I clicked on the file to open it.

**Comment by alesanchezr** [comment]
u r right, I connected both bugs thinking that they are triggered by the same reason: When the IDE has to do a heavy task.

But that is probably a big assumption.

**Comment by svenefftinge** [comment]
I think they are caused by the same thing: long running process in the main renderer loop.
