### ISSUE TITLE
No feedback when triggering prebuilds

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#5374]
**Problem**

After creating a project (gitpod-staging.com/new), since the prebuild didn't automatically run (at least, apparently) and I couldn't trigger it on the configuration page, I went to the prebuilds tab and triggered a prebuild. 

That action resulted in no feedback. Refreshed but there was no entry in the list, so I tried again (multiple times?). 5 minutes later when I came back there were three prebuilds running.

**Suggested solution**

As an improvement, we should provide the user with immediate feedback (whether it started, or failed to start), if possible, by representing it in the list below.

**Comment by AlexTugarev** [comment]
PR https://github.com/gitpod-io/gitpod/pull/5116 will improve the situation by updating the Prebuilds page once a prebuild was enqueued.

There is still a gap to bridge between the action of a user and the backend events being propagated back to the frontend. It would make sense to add some intermediate state on the frontend to signal the start of an action. Once we receive the first event on a prebuild, it should be resolved accordingly.

**Comment by gtsiolis** [comment]
Thanks for noticing @atduarte!

From a [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1625736950377200?thread_ts=1625736640.376900&cid=C021Q4BL8E8) (internal) (Cc @AlexTugarev):

> Ideally, this button would trigger a modal for confirming triggering a new prebuild for the default branch.

From a [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1627030246476800?thread_ts=1627026808.472200&cid=C021Q4BL8E8) (internal) (Cc @jankeromnes @svenefftinge @AlexTugarev):

> In terms of UX, this button could trigger a modal to confirm prebuild on the default branch. Possible improvements could include selecting a different branch, passing an env var for a prebuild, etc.

**Comment by jankeromnes** [comment]
Thanks for this idea @gtsiolis!

I agree that a modal could be a good idea (separately), but it doesn't answer the question: What should the UI show between the moment the user clicked on `Trigger Prebuild` (or accepted the modal), and the moment we hear back from the server that a prebuild was started? This can take a few seconds, which as @atduarte described can be stressful / confusing for users if the UI shows nothing.

In the Project Configurator, when you click on `Run Prebuild`, the front-end _immediately_ shows an "artificial" Pending state (which, after a few seconds, gets replaced with a "real" Pending status from the started prebuild -- but showing an immediate visual response to a user action is A+ UX 😁)

**Comment by jankeromnes** [comment]
Maybe a minimal viable change could be disabling the `Trigger Prebuild` button and adding [a spinner](https://tailwindcss.com/docs/animation#spin) to it while we wait for the server to call back?

**Comment by gtsiolis** [comment]
Adding this to the [**Teams & Projects** crew board](https://github.com/gitpod-io/gitpod/projects/4). Cc @jankeromnes @AlexTugarev @svenefftinge

**Comment by gtsiolis** [comment]
> Could you please provide a spinner SVG with transparent background?

On it. Will post here the SVG tomorrow. Thanks for noticing! 👀

**Comment by gtsiolis** [comment]
Incoming SVG for the spinner (loading icon)! 🍕 

```svg
<svg width="16" height="14" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.055 9.771A8 8 0 0016 6h-4a4 4 0 11-6.828-2.828L2.343.343a8 8 0 1012.712 9.428z" fill="#A8A29E"/></svg>
```

Cc @jankeromnes

**Comment by jankeromnes** [comment]
Many thanks @gtsiolis!

However, the SVG is not square, so adding a spin animation to it makes it look like a misaligned wheel 😅 I've tried fixing the SVG coordinates manually, but didn't succeed.

Could you please provide another spinner SVG with transparent background and the same height & width? (So that rotating it around its center creates a perfect circle)

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5374#issuecomment-921658973):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by gtsiolis** [comment]
Oh, no! You're right @jankeromnes! Here's one with correct dimensions. 🙈 

```
<svg width="16" height="16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#clip0)"><path fill-rule="evenodd" clip-rule="evenodd" d="M15.055 10.77A8 8 0 0016 7h-4a4 4 0 11-6.828-2.828l-2.83-2.83a8 8 0 1012.713 9.429z" fill="#A8A29E"/></g><defs><clipPath id="clip0"><path fill="#fff" d="M0 0h16v16H0z"/></clipPath></defs></svg>
```

**Comment by gtsiolis** [comment]
Small update to the SVG. Cc @jankeromnes 

```
<svg width="16" height="16" fill="none" xmlns="http://www.w3.org/2000/svg"><g clip-path="url(#a)"><path fill-rule="evenodd" clip-rule="evenodd" d="M11.77.945A8 8 0 0 0 8 0v4a4 4 0 1 1-2.828 6.828l-2.83 2.83A8 8 0 1 0 11.77.945h-.001Z" fill="#A8A29E"/></g><defs><clipPath id="a"><path fill="#fff" transform="rotate(-90 8 8)" d="M0 0h16v16H0z"/></clipPath></defs></svg>
```

**Comment by jankeromnes** [comment]
The new spinner is now merged, but the initial attempt to add visual feedback to the `Trigger Prebuild` button failed and we decided to close the PR. One step back, two steps forward. 🔜
