### ISSUE TITLE
Integration Test: Workspace Backup should succceed

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5379]
Yesterday, we needed to roll back deployment because workspace backup was broken. 

We should have an integration test that ensures this never happens again. 

Cause: https://github.com/gitpod-io/gitpod/pull/5325
Fix: https://github.com/gitpod-io/gitpod/commit/c31135bb66b625c1758d6657d1361f1e4d8f0992
Conversation: https://gitpod.slack.com/archives/C021LT6GUJG/p1629793948204700
Incident: https://gitpod.slack.com/archives/C02C4S04PA6

**Comment by csweichel** [comment]
This [test already exists](https://github.com/gitpod-io/gitpod/blob/main/test/tests/workspace/content_test.go#L20).
