### ISSUE TITLE
Allow to choose/change language mode manually

### ISSUE THREAD

**Issue by php-coder** [gitpod-io/gitpod#54]
Hello,

I have `Dangerfile` (http://danger.systems/ruby/) in my project that is a Ruby script by the fact. When I open it, there is no syntax highlighting. How I can enable and specify it manually?

**Comment by svenefftinge** [comment]
It is currently not possible. See also https://github.com/theia-ide/theia/issues/2064

**Comment by svenefftinge** [comment]
This has been solved.
