### ISSUE TITLE
Gitpod stuck in starting a workspace screen infinitely

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#5401]
### Bug description

While trying to open/create a workspace the screen went into infinite loop of redirects. The page refreshed automatically and showed the same page everytime.

On inspecting the logs of ws-proxy it was clear that the response from ws-proxy was to redirect. However, the ws pod was already created and running.

ws-proxy logs:
```json
{"instanceId":"","level":"info","message":"no workspace info found - redirecting to start","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-08-26T12:13:12Z","userId":"","workspaceId":"coffee-lynx-kx97h0kz"}
{"level":"info","message":"hit route handler","portID":"","routeHandler":"HandleDirectSupervisorRoute (authenticated: false)","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-08-26T12:13:12Z","url":"/_supervisor/v1/status/ide","workspaceId":"coffee-lynx-kx97h0kz"}
{"instanceId":"","level":"info","message":"no workspace info found - redirecting to start","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-08-26T12:13:12Z","userId":"","workspaceId":"coffee-lynx-kx97h0kz"}
{"instanceId":"","level":"info","message":"no workspace info found - redirecting to start","serviceContext":{"service":"ws-proxy","version":""},"severity":"INFO","time":"2021-08-26T12:13:13Z","userId":"","workspaceId":"coffee-lynx-kx97h0kz"}
```

### Steps to reproduce

Not reproduceable. Occurs sporadically.

### Expected behavior

Gitpod creates a workspace and opens IDE in the browser.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5401#issuecomment-911352854):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by csweichel** [comment]
should be fixed by #5449

**Comment by zhouzilong2020** [comment]
> should be fixed by #5449

Sorry to bother, I met the same problem even after #5499. The page just keep refreshing all the time.
Is the online version has not incorporated #5499 yet?

**Comment by NguyenCongVN** [comment]
This issue seems to happen in my workspace today. It keeps redirecting with a URL starting with "https://gitpod.io/start/?not_found=true#". But in the dashboard, it's still in a running state.

**Comment by axonasif** [comment]
Hey @NguyenCongVN, please check https://www.gitpodstatus.com/

**Comment by jwjsystem** [comment]
Hello! I noticed this reproduces on our setup as well, do you guys have any troubleshooting articles or tips on how to avoid this?

Basically, it happens every time I try to activate back an environment which has been IDLE for inactivity.  It's not happening each and every time, and I am not sure what could be the cause.

**Comment by svenefftinge** [comment]
thanks @jwjsystem for the report. We are looking into it.

**Comment by KC-7** [comment]
> Hello! @axonasif @meysholdt @roboquat I noticed this reproduces on our setup as well, do you guys have any troubleshooting articles or tips on how to avoid this?
> 
> Basically, it happens every time I try to activate back an environment which has been IDLE for inactivity. It's not happening each and every time, and I am not sure what could be the cause.

I'm also having this issue, it has happen a few times in recent weeks.

**Comment by sjoshid** [comment]
Im still facing this issue. I just signed up $9/mo. WTF.

**Comment by sjoshid** [comment]
Asked for a refund. What trash are you people running??

**Comment by Akxai** [comment]
![Screenshot 2024-05-08 111442](https://github.com/gitpod-io/gitpod/assets/85357123/df8f7638-8b86-4f33-a8b5-d8cf6adff1ae)

It's refusing to start.

**Comment by Akxai** [comment]
It's not even deleting my account. Don't know what's happening with gitpod!
