### ISSUE TITLE
Gitpod Self-Hosted on Red Hat® OpenShift®

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5409]
Red Hat® OpenShift® does not currently work with Gitpod Self-Hosted but we would like to support the platform in the future. In this GitHub issue members of the community can organise and potentially work together to implement the necessary changes.

**Comment by jgallucci32** [comment]
Given the current requirement for Gitpod is Linux Kernel >= 5.4 it will likely mean OpenShift will not work until RHEL9 is released.

**Comment by gsharma-jiggzy** [comment]
Any way we can help out? I saw the RHEL9 beta is out and lots of gov work is RHEL and Openshift based.

**Comment by jgallucci32** [comment]
@gsharma-jiggzy I recommend you ask @pawlean to create a the channel `#self-hosted-ocp` in Discord to begin the process of deploying/testing Gitpod on OpenShift Container Platform (OCP).

**Comment by gsharma-jiggzy** [comment]
@pawlean can you make a channel in discord?

**Comment by pawlean** [comment]
Hey folks! Let's [get this started](https://discord.com/channels/816244985187008514/911280850132410418) 🚀

**Comment by cnukwas** [comment]
We're using OpenShift and interested in self-hosted Gitpods, is there any progress towards that?

**Comment by gsharma-jiggzy** [comment]
@pawlean @cnukwas sorry had to drop openshift due to a shift in work.

**Comment by srudolph-credera** [comment]
Looks like RHEL 9 is out with Kernel 5.14 - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/9.0_release_notes/architectures. That should open the door to Gitpod, right?

**Comment by jgallucci32** [comment]
@srudolph-credera That is very unfortunate to hear. The minimum requirement is Kernel 5.2 as it includes a SYSCALL which was only made available in that version of the kernel. I'll dig through my notes to see which exact SYSCALL is being used to see if perhaps it will be backported to RHEL9.

**Comment by srudolph-credera** [comment]
@jgallucci32 - you've got me questioning my understanding of the Linux kernel versioning scheme, but it *looks* like 5.14 would be newer than 5.2: https://www.kernel.org/category/releases.html. Apologies if I confused things by leaving out the patch version: 5.14.0.

**Comment by jgallucci32** [comment]
@srudolph-credera Yeah that's my mistake, I need more sleep lol.

You are correct that is a newer version and technically should support the needed system call.

**Comment by jgallucci32** [comment]
Looks like there is an additional dependency from `agent-smith` referenced in https://github.com/gitpod-io/gitpod/issues/5647#issuecomment-917115363

Once I determined `open_tree` was needed I stopped my work on RHEL8 + Gitpod and switched to Ubuntu 20.04

**Comment by krauthosting** [comment]
FYI it's not best-practice anymore to use RHEL hosts with OpenShift 4.  
For nodes RHCOS or FCOS for OKD is the preferred operating system:
https://docs.okd.io/latest/architecture/architecture-rhcos.html
It's CoreOS rebuilt on RHEL/Fedora instead Gentoo (BTW forked as FlatCar).
In OpenShift 4.10 the RHCOS image is built on top RHEL8.4 packages:
https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html
With heavy kernel back-porting better look at version but kernel capabilities.

**Comment by jgcrunden** [comment]
From the little I've used Gitpod, I'm loving it!
I'm interested in it being able to run on Openshift. Just looking through the comments above to understand what's blocking it.
It seems for the two identified:
1. open_tree - @patrickeasters has found it was backported to RHEL 8.4
2. agent-smith using eBPF - I've found the following, suggesting it was [introduced in RHEL 7.6](https://www.redhat.com/en/blog/introduction-ebpf-red-hat-enterprise-linux-7) and [in RHEL 8](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/considerations_in_adopting_rhel_8/kernel_considerations-in-adopting-rhel-8#ebpf_available_as_a_technology_preview) as a [Technology Preview](https://access.redhat.com/support/offerings/techpreview)

Are there any other things blocking Gitpod running on Openshift?
I'd like contribute if possible. How can I help?

**Comment by frank-hollmann** [comment]
open_tree syscall and ebpf are necessary for gitpod in ocp 4.x.  open_tree is in rhel 8.4 and ebpf is supported since rhel 8.1.  the corresponding rhcos releases are supporting the requested functionality as well. 

So gitpod should be usable unter OCP 4.7 and later.
