### ISSUE TITLE
Support "Bring Your Own VM"

### ISSUE THREAD

**Issue by bytekast** [gitpod-io/gitpod#541]
The current RAM restriction prevents building large projects. It would be nice to be able to bring your own pre-configured VM.

**Comment by jankeromnes** [comment]
Sorry about the current RAM restriction -- I agree that the allowance is much too low.

For what it's worth, we've experimented with higher RAM limits, and it seems pretty easy and safe to significantly increase it. I've been pushing on that for a while, and it could happen pretty soon (ping @geropl @32leaves :P).

And if you need more RAM, note that [Gitpod Enterprise](https://www.gitpod.io/pricing#enterprise) can provide up to 360GB RAM per workspace, or allow you to bring your own VM.

**Comment by bytekast** [comment]
Adding the ability to increase RAM even for non-enterprise customers would be nice. I'd be willing to pay additional for such service.

Another reason for my "Bring Your Own" VM request is the ability to use docker inside the workspace. When working with languages such as Rust/Go, we often have to build binaries for specific distributions. 
A common workflow is to build such binaries in a docker container. 

Also, for machine learning tasks, It would really be nice to be able to bring my own GPU optimized VM.
