### ISSUE TITLE
[analytics] track usage of collaboration live sharing

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5412]
In order to estimate impact of https://github.com/gitpod-io/gitpod/issues/5151

**Comment by akosyakov** [comment]
I think it was done partially. We can have an event now when someone shares the workspace. It would be good also to have an event when someone joins the shared workspace, i.e. owner is not a user in VS Code extension.

**Comment by akosyakov** [comment]
I removed it from the groundwork for now. We prioritize collecting analytics for initial onboarding.

**Comment by loujaybee** [comment]
Removing from current inbox for now.

**Comment by akosyakov** [comment]
we know it already from commands usage.
