### ISSUE TITLE
DEADLINE_EXCEEDED: gRPC communication trouble

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5414]
the query 
```sql
SELECT * from `d_b_workspace_instance` as i 
    WHERE i.creationTime >= "2021-08-27" and status LIKE "%DEADLINE_EXCEEDED%";
```

returns 74 matches, all on cluster eu15 and all with status

```json
{
    "phase": "stopped",
    "message": "Workspace cannot be started: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded",
    "conditions": {
        "failed": "Error: 4 DEADLINE_EXCEEDED: Deadline exceeded"
    }
}
```

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5414#issuecomment-908119099):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
How is this related to this PR we recently deployed? https://github.com/gitpod-io/gitpod/pull/5322

**Comment by csweichel** [comment]
> How is this related to this PR we recently deployed? Did it mainly occur after deploying it?
> 
> #5322

I reckon this mostly relates to server as the workspaces fail to start in the first place. I.e. their `StartWorkspace` request never makes it to ws-manager.

**Comment by meysholdt** [comment]
re-opening, [because in the logs I see this happened again on eu15 this morning](https://console.cloud.google.com/logs/query;query=logName%3D%22projects%2Fgitpod-191109%2Flogs%2Fcloudsql.googleapis.com%252Fmysql-general.log%22%0AtextPayload:%22DEADLINE_EXCEEDED:%20Deadline%20exceeded%22%0AtextPayload:%22UPDATE%22;timeRange=2021-08-31T20:48:00.000Z%2F2021-09-01T02:16:00.000Z;summaryFields=jsonPayload%252Fpayload%252Fargs%252F0%252FinstanceId:false:32:beginning;cursorTimestamp=2021-09-01T01:09:08.396970Z?project=gitpod-191109).
