### ISSUE TITLE
Evicted From Workspace - Ephemeral-Storage

### ISSUE THREAD

**Issue by stephenavocado** [gitpod-io/gitpod#5429]
### Bug description

Was working on my project and all of a sudden got this error: 

Evicted: The node was low on resource: ephemeral-storage. Container workspace was using 82083771, which exceeds its request of 0.

Not sure what to do 

### Steps to reproduce

Was working in workspace:

https://amethyst-shrew-7l5syx6h.ws-us16.gitpod.io/

### Expected behavior

Workspace opens 

### Example repository

https://amethyst-shrew-7l5syx6h.ws-us16.gitpod.io/

**Comment by ghuntley** [comment]
👋 @stephenavocado we have retired the server which was running low on disk-space and are investigating why this happened to you. Can you please try restarting your workspace and report back.

**Comment by stephenavocado** [comment]
Thank you @ghuntley! I am able to access the workspace again.

**Comment by ghuntley** [comment]
Good to hear. We have 🆙 the size of disks in each node in the cluster to 600GB and will be monitoring the situation.
