### ISSUE TITLE
Support buildkit 

### ISSUE THREAD

**Issue by shism2** [gitpod-io/gitpod#5430]
Anyone? Is buildkit supported? I haven't been able to get it to work things like below to work: # syntax=docker/dockerfile:1.2

```
FROM alpine

# shows secret from default secret location:
RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret

# shows secret from custom secret location:
RUN --mount=type=secret,id=mysecret,dst=/foobar cat /foobar
```

**Comment by akosyakov** [comment]
Alpine is not supported: https://github.com/gitpod-io/gitpod/issues/3356

**Comment by shism2** [comment]
The lines I pasted are from the docker documentation as an example. It happens to me with ubuntu as well for example.

**Comment by csweichel** [comment]
With the new image-builder we'll also support buildkit during workspace image builds. Expect this to be available within the next two weeks.

**Comment by shism2** [comment]
Just checking to see if this is still to be released soon?

**Comment by shism2** [comment]
@csweichel

**Comment by loujaybee** [comment]
@csweichel / @gitpod-io/engineering-workspace is there are any status you can share on this issue / when it might be available? I'm asking on behalf of a client 🙏

**Comment by csweichel** [comment]
Unfortunately the rollout of this feature has proven rather difficult. While we're still expecting to roll out this feature at some point, I'll refrain from communicating timelines in this regard.

That said, we're still actively working on this.

**Comment by aledbf** [comment]
Closing. The new image-builder is available in production.

@shism2 please try again and let us know if there are still issues. Thanks!
