### ISSUE TITLE
SSL Cert for gitpod.io is expired.

### ISSUE THREAD

**Issue by dgigantino** [gitpod-io/gitpod#5435]
### Bug description

The SSL cert for gitpod.io has expired

### Steps to reproduce

Try sign in at https://gitpod.io/login/

### Anything else?

https://gitpod.io/login/ has an expired certificate
https://www.gitpod.io/ is fine

**Comment by gengjiawen** [comment]
I thought gitpod use caddy to auto-renew ssl certificate. Guess I am wrong :(

**Comment by ghuntley** [comment]
Confirmed. We are investigating.

**Comment by gengjiawen** [comment]
Also https://www.gitpodstatus.com/ failed to detect this.

**Comment by meysholdt** [comment]
We have resolved this. Please try again.
