### ISSUE TITLE
Remove gitpod_ws_daemon_workspace_cpu_limit_sec metric

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#5443]
### Bug description

**Reasons:**

- Scalability is an issue due to the number of workspaces
- The metric is not being used
- We also log when a change in the CPU limit is configured. In this case, a log makes sense because of the additional context
- The metric is not removed after a workspace is disposed
- Reduce cost of self-hosted instances

### Steps to reproduce

-

**Comment by roboquat** [comment]
@aledbf: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5443#issuecomment-908527476):

>/schedule
>/assign


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
