### ISSUE TITLE
Workspace goes offline when try gin to download 700MB-file

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#545]
1. create 700MB file
2. in File View, open context menu on the file, click download. 
3. observe status bar go yellow (offline).

**Comment by geropl** [comment]
I think there already is a Theia issue for that but I cannot find it. @akosyakov Do you know the title from the top of your head?

**Comment by alesanchezr** [comment]
It happens with heavy tasks like: 
- Searching for a string inside a huge folder.
- Downloading big files.

**Comment by akosyakov** [comment]
cc @kittaakos should https://github.com/theia-ide/theia/pull/4890 help?

**Comment by akosyakov** [comment]
@alesanchezr for search an issue in Theia: https://github.com/theia-ide/theia/issues/5092

**Comment by kittaakos** [comment]
> cc @kittaakos should [theia-ide/theia#4890](https://github.com/theia-ide/theia/pull/4890) help?

If you are referring #537, then no. I wanted to **open** a file and not **download**.

**Comment by akosyakov** [comment]
@kittaakos i was referring to improving download of big files that it does not block UI

**Comment by alesanchezr** [comment]
If you ask me, I no longer have this issue. 😄
