### ISSUE TITLE
Support for AWS CodeCommit

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5450]
Often AWS Customers are left with Cloud9 as their only choice because other products do not support AWS CodeCommit. Adding support for AWS CodeCommit into Gitpod would solve this pain point.

> AWS CodeCommit is a secure, highly scalable, managed source control service that hosts private Git repositories. It makes it easy for teams to securely collaborate on code with contributions encrypted in transit and at rest. CodeCommit eliminates the need for you to manage your own source control system or worry about scaling its infrastructure. You can use CodeCommit to store anything from code to binaries. It supports the standard functionality of Git, so it works seamlessly with your existing Git-based tools.

https://aws.amazon.com/codecommit/

## SDK

NPM can be found at https://www.npmjs.com/package/@aws-sdk/client-codecommit

## Authentication

https://docs.aws.amazon.com/codecommit/latest/userguide/auth-and-access-control.html

### Clone URL

I created a brand new AWS trial account and a repository called “integration testing”

```
https://git-codecommit.us-east-2.amazonaws.com/v1/repos/Integration-testing
ssh://git-codecommit.us-east-2.amazonaws.com/v1/repos/Integration-testing
codecommit::us-east-2://Integration-testing
```

### Commits

URL when navigating to a singular commit

```
https://us-east-2.console.aws.amazon.com/codesuite/codecommit/repositories/Integration-testing/commit/681046371ce9f8253bd6dc3e3f21d149ec1198d2?region=us-east-2
```

### Branches

Created `main` and `My-cool-branch`

```
https://us-east-2.console.aws.amazon.com/codesuite/codecommit/repositories/Integration-testing/browse/refs/heads/main?region=us-east-2
https://us-east-2.console.aws.amazon.com/codesuite/codecommit/repositories/Integration-testing/browse/refs/heads/My-cool-branch?region=us-east-2
```

### Pull-requests

I did a commit into `My-cool-branch` then raised pull-request into `main` which ended up being pull-request number `1` 
```
https://us-east-2.console.aws.amazon.com/codesuite/codecommit/repositories/Integration-testing/pull-requests/1/details?region=us-east-2
```

## AWS Resources

Repository ID:
```
c27cf684-2085-4064-8393-365d4e8b357d
```

Repository ARN:
```
arn:aws:codecommit:us-east-2:877558633215:Integration-testing
```

**Comment by andymac4182** [comment]
Is there a breakdown of the minimum implementation for a new git provider?
