### ISSUE TITLE
Support for env vars at Git host level

### ISSUE THREAD

**Issue by ajhalili2006** [gitpod-io/gitpod#5451]
## About this Issue

In the current state, the user-specific secrets/variables are only scoped at the namespace/organization and repository level. One can do `*/*` to include at the global level within their account but the problem is some repos can have the same namespace-repository path if mirrored to other Git hosts (e.g. `RecapTime/verify` in GitHub also exists in GitLab SaaS as the same namespace-repository path because I mirror it, but this can be possibly configured at project's `.gitpod.yml`, which I'll discuss in the future GitHub issue).

## What I Propose?

**In the Variables setting page**: Add a dropbox menu for selecting which GIt host should variable be scoped. The dropbox menu should support multiple options, similar to this one:

```
* By host type
  * GitHub # When selected, this includes GitHub.com + GHES instances
  * GitLab # When selected, this includes GitLab SaaS + self-hosted instances
  * Bitbucket # IDK about Bitbucket Server
* By hostname
  # List the instance-wide Git host domains first
  * github.com
  * gitlab.com
  * bitbucket.org
  # Then list the user and team level host domains below
  * ghe-example.net
  * gitlab.example.com 
```

**In the `gp` CLI inside the workspace**: Add support for the `--host` flag, which if set, new variables will be scoped to specific Git host of an project ONLY if the path is same or configured at `.gitpod.yml`.

## Use Case

Suppose your automated MR review (we assume your project is using Danger [Ruby](https://danger.systems/ruby)/[JS](https://danger.systems/js)/[Swift](https://danger.systems/swift)) failed because your PAT is expired at the time the MR is triggered that workflow/pipeline or something is broken between the cloning and dependency installation process (we assume your Dangerfiles are working as usual) and you decided to open the affected MR in Gitpod.

If you're in GitHub, you can simply make Danger think its a CI by setting some variables and then running `danger ci` on the terminal:

```sh
# vars are based on https://github.com/danger/danger-js/blob/main/source/ci_source/providers/Fake.ts
eval $(gp env --host github.com -e DANGER_GITHUB_API_TOKEN=ghp_yourPATherePlzReplaceMe DANGER_MANUAL_GH_REPO=octocat/dangerfile-testbed)

# then run Danger in CI mode
DANGER_MANUAL_CI=true DANGER_MANUAL_PR_NUM=1234yarn danger ci [--your-other-flags=here]
```

For GitLab users, the internal ID, as per the GitLab Docs, is the issue/merge request number.

```sh
# TODO: Replace example.gitlab.com with the host of your GitLab instance, minus the protocol for the host flag.
# If you're using GitLab SaaS, use gitlab.com for the host flag and remove DANGER_GITLAB_HOST stuff.
eval $(gp env --host example.gitlab.com DANGER_GITLAB_API_TOKEN=yourPAToverHerePlzReplace DANGER_GITLAB_HOST=https://example.gitlab.com CI_PROJECT_PATH=mirrors/gitlab-sass/gitlab-org/gitlab)

# since https://example.gitlab.com/mirrors/gitlab-sass/gitlab-org/gitlab in this example is an mirror of GitLab source code
# from GItLab SaaS, you probably need to check their Dangerfiles and stuff to mock on an dummy MR on your instance
# Ref: https://gitlab.com/gitlab-org/gitlab/-/blob/master/.gitlab/ci/review.gitlab-ci.yml#L239-263
source scripts/utils.sh
bundle_install_script "--with danger"
run_timed_command "retry yarn install --frozen-lockfile"

# since we're running Danger locally, setting GITLAB_CI upfront isn't needed
# Ref: https://gitlab.com/gitlab-org/gitlab/-/blob/master/scripts/utils.sh#L139-140
CI_MERGE_REQUEST_IID=1234 run_timed_command danger_as_local

# if you prefer to run the Dangerfiles and you know what you're doing, don't use the above command and instead use this:
CI_MERGE_REQUEST_IID=1234 GITLAB_CI=true run_timed_command "bundle exec danger --fail-on-errors=true --verbose"
```

## Glossary

* namespace - In GitHub and Bitbucket, this is referred to the organization's username. In the case of GitLab, the namespace can have subgroups up to 27 levels (main group + any subgroups).
* project - In GitHub, Git support + PRs is enabled in every single repository and there's no way to disable it if you want only issues. In GitLab, you can also adjust access to only users with access to specific features. IDK about Bitbucket if it's like GitHub in this case.
* MR/merge requests - GitLab wording for PR/pull requests here in GitHub

**Comment by svenefftinge** [comment]
Thanks for the very detailed feature description. We have lots of things scheduled at the moment, so I'm unscheduling this until we see more demand for supporting this.
@anyone : if you think this is important, please add a comment outlining your use case.

**Comment by ajhalili2006** [comment]
Keeping this issue open for a couple of days, possible added to the backlog in the future.
