### ISSUE TITLE
join discord server button on https://gitpod.io/login/

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5453]
Opening for discussion. Not sure how to integrate it (visually) but if we can integrate some sort of secondary flow where people either a) signup/signin for gitpod b) join community to learn more about gitpod if they are hesitant about scenario a). 

Maybe completely not worth doing... 

<img width="717" alt="2021-08-31_18-13-00" src="https://user-images.githubusercontent.com/127353/131467257-be6d53fc-f072-4f25-b990-5be9a0c442d2.png">

or maybe: 

> Spin up fresh, automated dev environments for each task in the cloud, in seconds.

becomes

> Spin up fresh, automated dev environments for each task in the cloud, in seconds. Join the community

<img width="880" alt="2021-08-31_18-11-54" src="https://user-images.githubusercontent.com/127353/131467262-88e9510a-735a-4303-b47c-e7ef6226c0ce.png">

**Comment by svenefftinge** [comment]
Adding more options/choice is potentially compromising conversion. 
I'd think we should add a nudge to join the community to our loading screen again. 
But isn't community => https://community.gitpod.io?

**Comment by ghuntley** [comment]
> But isn't community => community.gitpod.io?

www.gitpod.io/chat is seeing more growth than the forums and _feels_ like a community whereas `community.gitpod.io` due to the real-time interactions that people prefer. I kinda want to see us renaming `community.gitpod.io` to `discuss.gitpod.io`

**Comment by svenefftinge** [comment]
I don't think it makes sense to lift up the joining community into our primary conversion channel. As I said, there might be other places where we can highlight/suggest joining it, though.
