### ISSUE TITLE
[configurator] Endless spinning when user has no access

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5461]
I created two users User A with GitLab token and User B with GitHub token.
User A created a team & project (connected to a gitlab repo) and invites user B.
User B  goes to the configuration page and sees:

<img width="678" alt="Screenshot 2021-08-31 at 14 39 16" src="https://user-images.githubusercontent.com/372735/131504288-73003eff-406f-4b34-969f-4c7fee2e7102.png">

**Comment by svenefftinge** [comment]
cc @jankeromnes

**Comment by jankeromnes** [comment]
I guess this is the same bug as described in https://github.com/gitpod-io/gitpod/pull/5433#issuecomment-909319798:

> However, I also uncovered two bugs, but they're likely unrelated to this PR:
> 
> 1. When you don't authorize GitLab (just GitHub), most Team Project pages just fail to load anything if it's a GitLab project:
> 
> <table><tr><td>
> <img width="1440" alt="Screenshot 2021-08-31 at 16 50 28" src="https://user-images.githubusercontent.com/599268/131526144-c9da7cb1-9efa-48e5-abd4-7c30f5d316a3.png">
> </td><td>
> <img width="1440" alt="Screenshot 2021-08-31 at 16 50 45" src="https://user-images.githubusercontent.com/599268/131526160-e2d14874-429e-48b8-99ce-735bc974f66e.png">
> </td><td>
> <img width="1440" alt="Screenshot 2021-08-31 at 16 51 22" src="https://user-images.githubusercontent.com/599268/131526165-ce51538a-f0f3-4065-9b6f-7623734b22eb.png">
> </td></tr></table>
> 
> However, authorizing with GitLab resolves this. We should probably handle these errors better (and show a "Authorize GitLab" button)However, I also uncovered two bugs, but they're likely unrelated to this PR:
