### ISSUE TITLE
[teams] move team URLs in its own slug (namespace)

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5465]
To avoid name clashes we should introduce a `/team/` segment to the team URLs.
E.g. `gitpod.io/team/<team-name>`

**Comment by gtsiolis** [comment]
Cross-posting from the [relevant and recent product sync meeting](https://www.notion.so/gitpod/Product-Sync-b0369cb3611e4920a5a64e92157d569e#5e39c885fee74f499848217edd3c7a5a) (internal).

> Alternatively, we could use `/t/` for short instead of `/team/`.
