### ISSUE TITLE
gitpod.yml warning with (marketplace) extensions installed as .vsix

### ISSUE THREAD

**Issue by NormalGaussian** [gitpod-io/gitpod#5466]
### Bug description

I am using a custom build of a VSCode extension and adding it as a vsix file (to get the nightly version whilst waiting for an upstream release with the fix I need). gitpod.yml lets me install this via HTTP but does not recognise that the installed extension is specified in the list.

I get this warning: `asvetliakov.vscode-neovim extension is not synced, but not added in .gitpod.yml`

I have not confirmed as to whether this warning is or is not present when the extension is not in the marketplace.

### Steps to reproduce

With this `gitpod.yml`:

```
# image includes neovim runtime, unlikely


vscode:
  extensions:
    - https://gitlab.com/Normal_Gaussian/gitpod-workspace-full-with-neovim/-/raw/main/vscode-neovim.vsix
```

### Expected behavior

No warnings in gitpod.yml file, gitpod to realise the extension is in the .gitpod.yml

(you can ignore the "MainController" errors, these are due to the baseimage not having a package the extension requires, to fix and see the warning without the error add `image: normalgaussianfeb2020/gitpod-workspace-full-with-neovim:latest` to `.gitpod.yml`)

### Example repository

https://github.com/NormalGaussian/issue-repro_gitpod_1

**Comment by akosyakov** [comment]
That's indeed a bug, but we don't have capacity to tackle it right now.

**Comment by akosyakov** [comment]
It is still the issue.

**Comment by akosyakov** [comment]
We don't seem to filter extensions resolved from vsix files.

**Comment by akosyakov** [comment]
There is also not install extension when it is not installed, but present in .gitpod.yml.

**Comment by jeanp413** [comment]
Fixed in https://github.com/gitpod-io/openvscode-server/pull/468
