### ISSUE TITLE
No longer able to select kernel for Jupyter notebook

### ISSUE THREAD

**Issue by Mjboothaus** [gitpod-io/gitpod#5467]
### Bug description

I have a environment defined in .gitpod.yml file that creates a conda Python environment (including Jupyter notebooks). It has been working fine for a while now.

### Steps to reproduce

When I fired up Gitpod today (from https://github.com/DataBooth/db-hello-gitpod) I can no longer select a Jupyter kernel. 

This is the workspace instance - https://green-bass-o31gml56.ws-us15.gitpod.io

I tried stopping and starting the workspace and the behaviour is reproducible.

### Expected behavior

When you click Select Kernel within the notebook interface within VS Code you normally can choose from a list of (Python) environments -- but there are now no choices.

### Example repository

https://github.com/DataBooth/db-hello-gitpod

### Anything else?

Really loving Gitpod.

**Comment by Mjboothaus** [comment]
So trying to work out what has changed and broken this (as there were no changes in the .gitpod.yml file).

Here are the Editor: Help -> About details:

```
Version: 1.59.0
Commit: 330c9b35c2f3d95af9192bc1ce23eccc5fcbe808
Date: 2021-08-30T07:53:57.621Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
```

**Comment by Mjboothaus** [comment]
So I assume it is something in the Gitpod (custom) VS Code editor build that has broken this functionality. I will try opening the notebooks via `jupyter notebook` in the command line as a work-a-round.

**Comment by Mjboothaus** [comment]
So work-a-round not working at least initially as the notebook via browser is not able to find the kernel.

This might be a Jupyter config issue in this setup - although it is puzzling.

**Comment by Mjboothaus** [comment]
So this is certainly a blocker -- I'm wondering where I can see release details for Gitpod releases, VS Code releases etc. in a centralised way so that it is easier to pinpoint what part of the chain has been broken.

**Comment by Mjboothaus** [comment]
Hmmm...

Select Interpreter to Start Jupyter server

`Installed kernelspec ENV_NAME in /home/gitpod/.local/share/jupyter/kernels/ENV_NAME` where ENV_NAME is the label I use for my conda env

`@id:ms-toolsai.jupyter`

**Comment by Mjboothaus** [comment]
Maybe this is related to these types of issues:

https://github.com/microsoft/vscode-jupyter/issues/513

https://github.com/microsoft/vscode-jupyter/issues/2282

**Comment by roboquat** [comment]
@csweichel: We have more than 16 cards scheduled. Above 0 only scheduler can perform this action. Those are:


<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5467#issuecomment-910053141):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@csweichel: We have more than 16 cards scheduled. Above 0 only scheduler can perform this action. Those are:


<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5467#issuecomment-910054143):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
Maybe related to these changes: https://github.com/gitpod-io/workspace-images/pull/461 cc @aledbf @AlexTugarev could it be related?

**Comment by jeanp413** [comment]
@Mjboothaus do you have a public repo that I can try to reproduce? I can't access https://github.com/DataBooth/db-hello-gitpod

**Comment by Mjboothaus** [comment]
Hello Jean Pierre

Yes - I meant to publish it as a public repo. Will try to do that shortly.

Cheers,
Michael

**Comment by Mjboothaus** [comment]
https://github.com/DataBooth/public-hello-gitpod

Is a public version of the repo

I have just tested it in Gitpod i.e. opened the notebook in the notebook directory and I still can’t Select Kernel.

Cheers :)

**Comment by akosyakov** [comment]
@Mjboothaus which version of python extension do you run? Latest from Open VSX?

**Comment by Mjboothaus** [comment]
Hi Anton — thanks for your question.

As per the conda environment.yml file in the repo:


dependencies:
  - python >=3.8,<3.9


Currently conda is installing:

conda 4.10.3
Python 3.8.10

in the (conda) environment.

Cheers,
Michael

**Comment by akosyakov** [comment]
Python extension in Open VSX is old and not compatible with VS Code 1.59 anymore. I can upgrade it but it does not seem to fix the problem. I'm looking into whether `Select Kernel` requires another extension right now or it is misconfiguration in our workspace image.

**Comment by Mjboothaus** [comment]
![image](https://user-images.githubusercontent.com/956433/131802215-75d2f23d-b2de-4c3e-8b31-09c0d998b508.png)

**Comment by Mjboothaus** [comment]
Thanks @akosyakov -- just looked up the MS Jupyter extension history and it seems some work is happening there currently.

**Comment by Mjboothaus** [comment]
I feel the 2.5 star rating for the extension is a little harsh :)

**Comment by akosyakov** [comment]
> Oh - so Open VSX is an alternate market place for VS Code extensions...

Yes, I mean there it is out-dated

> All I can say is my .gitpod.yml setup was working perfectly for the past month or so and then stopped abruptly on Wed AM Sydney (AEST GMT+10).

VS Code 1.59 was released, but we don't have smoke tests for notebooks yet 🙈

**Comment by Mjboothaus** [comment]
Seems I'm smoking... (whether I like it or not) 🚬

**Comment by akosyakov** [comment]
Yes, it helps in testing environments:
<img width="1904" alt="Screenshot 2021-09-02 at 11 23 15" src="https://user-images.githubusercontent.com/3082655/131818834-75b035d6-4981-4c31-adc2-c482a0bc58b5.png">

Working on fixing publishing to Open VSX.

**Comment by Mjboothaus** [comment]
👍🏻
