### ISSUE TITLE
Press "." on the workspace stopping/stopped screen to navigate to the context / git repo

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5470]
If we start adding keyboard shortcuts then this is high up on my wish list.

**Comment by svenefftinge** [comment]
Seems a bit arbitrary to me. Would love to hear more voices on this. FWIW I usually start the workspace again when I go to a tab that is in stopping mode.

**Comment by gtsiolis** [comment]
The `.` character does seem a bit arbitrary. If we want to dive into shortcuts a more sensible one, like `g` + `c`, could work.

Using `g` + `c` opens **commits** in GitLab and **code** in GitHub. We could use `g` + `c` for opening **context** in Gitpod.

**Comment by ghuntley** [comment]
`.` was chosen to mimic the GitHub.dev convention. Making it a universal way to go backwards/forwards between code+editing. Have been thinking about adding a user-configurable toggle override to the Gitpod browser extension that makes `.` open in Gitpod instead of github.dev

**Comment by ghuntley** [comment]
> I usually don't see stopping at all (because they time out, or I have closed them)

I see stopping all the time because my development loop often involves restarting the workspace when doing initial template bootstrapping:

1. ctrl+shift+p -> stop workspace
2. click the context link with mouse
3. click edit in gitpod button again

Thus some form of "rebuild workspace, execute gitpod yml, do a prebuild" option from ctrl+shift+p would speed up my loop. Codespaces has similar functionality.
