### ISSUE TITLE
Write down Gitpod's take on Security

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/gitpod#5472]
Large customers and the community are asking for a summary on how we secure our containers at Gitpod. 

Things that should be addressed:
- Namespace isolation (related to this talk: https://www.youtube.com/watch?v=l4I2TVAnBuw)
- Network policies 
- Source code encryption at rest
- Encryption of variables
- Organizations that stress/pen-test our system (e.g. GitLab's Security Team)

Context: https://gitpod.slack.com/archives/C01MLB7J24T/p1630443151009700

**Comment by svenefftinge** [comment]
Since engineering is swamped atm, it would be great if someone else could draft a first version with feedback from engineering.

**Comment by JohannesLandgraf** [comment]
cc @phimae @ghuntley maybe you can pair with Andre and then get feedback on the draft from engineering?

**Comment by ghuntley** [comment]
Confirmed. Let's continue at [internal link](https://docs.google.com/document/d/18P_Wd4ax5eUi9ePeoulKoEmQfrPLRGfr_upcnueFMZc/edit?usp=sharing).

**Comment by JohannesLandgraf** [comment]
Great! Any ETA on this that I can communicate externally?

**Comment by atduarte** [comment]
We (me, @ghuntley, and @phimae) are aiming to have the Notion page completed by tomorrow's EOD.

Draft structure of the document, for early feedback:
1. How Gitpod makes you more secure
   - No IP in employees’ laptops or BYOD devices
   - No arbitrary code running in devices with access to production
2. How we make Gitpod more secure
   - Compliance (SOC 2, GDPR)
   - Encryption (Backups, Env vars, …)
   - Container Isolation
   - Connections (authentication, … e.g. access to workspaces/ports…)
   - Open Source and building in public
   - Publicly documented VDP process for interfacing with security researchers
