### ISSUE TITLE
Invite more users to Teams & Projects

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#5476]
We want users to see Teams & Projects enabled as soon as they visit `/new` or follow the team invitation link.

Internal [pingback](https://gitpod.slack.com/archives/C021Q4BL8E8/p1630483304047400?thread_ts=1630483011.047300&cid=C021Q4BL8E8)

**Comment by svenefftinge** [comment]
We need to have a server-side signal from `/new` that lets us enable the flag on the server side and also reload the user. If that is too strange, we can move to an explicit call. But in that case it needs to move to a feature flag.
