### ISSUE TITLE
[code] open context command is broken

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5478]
### Bug description

Try to run this command.

### Steps to reproduce

See above.

**Comment by roboquat** [comment]
@akosyakov: Cannot schedule issue - no configuration for the IDE team available.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5478#issuecomment-910123252):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - no configuration for the IDE team available.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5478#issuecomment-910131999):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: The label(s) `team: ide` cannot be applied. These labels are supported: `team: IDE, team: meta, team: workspace`

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5478#issuecomment-910134091):

>/team IDE
>


Instructions for interacting with me are available [here](https://github.com/gitpod-io/gitbot/blob/main/plugins/customlabels/README.md). If you have questions or suggestions related to my behavior, please file an issue against the [gitbot](https://github.com/gitpod-io/gitbot/issues/new) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - no configuration for the IDE team available.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5478#issuecomment-910137000):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5478#issuecomment-910153936):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
