### ISSUE TITLE
Reduce noisy `Readiness probe failed` log error

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#5488]
### Bug description

workspace probes are too low.  Each workspace produces ~24 events about probes

### Steps to reproduce

Internal link https://cloudlogging.app.goo.gl/DmSXHBNyhnX5Z8Qx8

**Comment by roboquat** [comment]
@aledbf: The label(s) `team: groundwork` cannot be applied. These labels are supported: `team: IDE, team: meta, team: workspace`

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5488#issuecomment-910725802):

>/team groundwork


Instructions for interacting with me are available [here](https://github.com/gitpod-io/gitbot/blob/main/plugins/customlabels/README.md). If you have questions or suggestions related to my behavior, please file an issue against the [gitbot](https://github.com/gitpod-io/gitbot/issues/new) repository.
</details>
