### ISSUE TITLE
Target platforms

### ISSUE THREAD

**Issue by GuzioMG** [gitpod-io/gitpod#549]
On #548, I said I switched to C# because of Unity. But I also mentioned Java there. But didn't say, why I learned it. Do you know why I learned Java? To make Minecraft mods. It finally ended up in Android. Now, I'm learning C++, because I want to switch to Unreal Engine (not yet sure, because Unreal is damn difficult for scripting, but Unity is harder in Graphics).

I think, you now know, what I mean. I mean target platforms. And target platforms are key feature, you MUST implement, otherwise this IDE may die.

What do I mean by target platforms? Target build platforms. Android, Unreal Engine (don't worry, I don't want graphics designer in GitPod), Unity, UWP, Minecraft mods and plugins (why not?), qMods (Subnautica modding engine), and many more.

But speaking of modding. I think, you aren't going to scroll for every game on Steam and add modding support. Well, here comes #550!

**Comment by svenefftinge** [comment]
We should write small guides with examples and starter templates (boilerplates) for each platform / framework. I'd like to start out with some of the more popular web frameworks for which the setup is not straight forward and includes setup of DBs etc. So people get a full stack dev environment.

**Comment by GuzioMG** [comment]
Well, I don't mean that. Even if you get complete sample of Android app, how can you make an IDE compile to .APK? Or how can you tell an IDE to build Unity app instead of just compiling C# files delivered with example to assembly-cshap.dll and doing nothing with it (C# is yet not supported, but it's just an example)? You can't.

You know, what I (probably) hate most, when I comes to programming? Having tons of IDEs on my computer. I have:
- Visual Studio 2019 community (for big projects and most "heavy" development work)
- Visual Studio code (for small projects, "light" development work and quick editing of files, I can't open with Notepad++, such as VS projects configs) 
- Notepad++ (for quick files editing, that I can open with UWP version of Notepad++) 
- Eclipse (for Java development) 
- AIDE (on my phone) 
- Android Studio (for Android development) 
- Unity (for Unity designing) 
- Unreal Engine 4 (for UE4 designing) 
- Node.js (required for some JS development work) 
- Python (I think, it's pretty self-explaining) 
- Epic Games Store (it's unfortunately needed to launch and update UE4. It's not an IDE, but it is required to run IDE, that's why I added it here)
- Codeanywhere (I used it before it became paid)
- And finnaly... your Gitpod.io! (I don't actually need to install it, since it's online. Same with Codeanywhere)

Do you now see, what I mean? I had to install 10 on my computer itself (there is also 1 on my phone and 2 running in cloud) programs to do my development work. And there is only one Internet. So if you're making online IDE, you shouldn't make me install more IDEs. It's not a online (something) IDE. It's generally online IDE. Many things on PC came with Visual Studio. Only Notepad++, VScode, Eclipse and Android Studio were added separately. But what about it? Does it mean something? It means VS adds plenty of software to it. And what else? Didn't I just say "I had to install 10 things", even in the same paragraph? Well... VS and VS code are general IDEs. You can do many things in the same software. VScode doesn't ship with anything on board and passes everything to community by Marketplace, while VS have an installer attached, so you can pick components you need. But components are very different. They don't aims to some features connected to one thing - unlike for example Unity installer, when you just pick target platforms. Eclipse, is general Java IDE. It doesn't aims on something sceptical, such as Android Studio. You can build Android apps form it, but Android Studio preforms WAY better.

But still. What does it mean? Well, it means, that with that 10 programs, I achieved actually 4 things:
- General non-Java programming 
- General Java programming
- Android Java programming (plus C++, but I don't actually use it)
- Quick editing

My dream is to have all of these things in one place. And your IDE is perfect place. While quick editing isn't good thing for it, first 3 things makes sense. But right now makes nonsense. On general non-Java programming I mostly focus on Microsoft UWP and Unity. Which is impossible on Gitpod, because you can't select target platform and it's required to run UWP app or even build Unity app. I can write code, but to debug it I still need PC. On general Java programming, I mostly focus on Minecraft modding. This is actually even possible, but requires huge setup work and I think, it isn't worth it. By simply selecting target platform, this makes entire process easier. I think you know, what I make on Android Java programming. Impossible on Gitpod, because this uses Ant, Gradle and compiles to APK instead of JAR.

Even 500000 examples for almost any platform, still worth less, than just:
- R-click the file/Use as workspace/Android/Android Studio
- R-click the file/Use as workspace/Android/Eclipse extension
- R-click the file/Use as workspace/Unity/Editor
- R-click the file/Use as workspace/(anything)/Gitpod native

**Comment by GuzioMG** [comment]
Your IDE is general, but every modern general IDE support many languages and _and_  **many platforms**. For me and probably other people this IDE is for everything and for nothing right now. 

Things, you should focus on are:
- adding as much languages as possible (to attract devs using different programing languages)
- adding as many platforms as possible (to attract devs coding to other target platforms)

Keep in mind, that this is just my opinion. Focus on whatever you want. But I still think that targeted platforms are one of the key features.
