### ISSUE TITLE
[staging] missing db table

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5494]
Seems like [this migration](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/src/typeorm/migration/1628160315471-AddPrebuildInfo.ts) was not applied on staging.

```
 Error: Request findPrebuilds failed with message: ER_NO_SUCH_TABLE: Table 'gitpod.d_b_prebuild_info' doesn't exist
```

**Comment by AlexTugarev** [comment]
> Error: New migration found: AddPrebuildInfo1628160315471, however this migration's timestamp is not valid. Migration's timestamp should not be older then migrations already executed in the database.

Yeah, there was a newer migration created in the meantime.
