### ISSUE TITLE
[image-builder] mkIII: imagebuild workspaces seem to ignore "workspace templates"

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#5497]
While testing https://github.com/gitpod-io/gitpod/pull/5480 I was blocked because an `imagebuild` got scheduled to a NodePool where no suitable `ws-daemon` was running (context: https://github.com/gitpod-io/gitpod/pull/5432).

On inspection of the `imagebuild` it did not contain a `nodeAffinity`, but the `workspace-template` ConfigMap did:
 - not for `default`
 - but for all specific workspace types (incl. `imagebuild`)

I did not have time to investigate further. This should be easily reproduceable by triggering an image build in a preview env. (note that you might get lucky and the build succeeds if the workspaces ends up on the "right" node. Please check the pods yaml to verify that there's no nodeAffinity).

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5497#issuecomment-911364524):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by csweichel** [comment]
An additional test in [`create_test.go`](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager/pkg/manager/create_test.go) could also be used to verify this. Looks like we're missing the case for image-builds though.
