### ISSUE TITLE
Support Snapshot URLs

### ISSUE THREAD

**Issue by jlengstorf** [gitpod-io/gitpod#55]
Hey, team!

We're super impressed with gitpod.io, and we'd love to use it as part of our OSS process. Is there any way to share a gitpod.io link in an issue so OSS maintainers could access it to see e.g. minimal bug reproductions?

Thanks!

**Comment by svenefftinge** [comment]
Hi Jason, 
are you asking for creating a link for a specific workspace situation, i.e. a snapshot? That is planned but not yet available. 
For now, users would have to push the state to their fork and provide a gitpod.io#-link to it. So e.g. 
  https://gitpod.io#https://github.com/jlengstorf/gatsby/tree/fix/6980-remark-image-links

But I guess that is a bit too complicated to communicate. 
Could you elaborate a bit more on how you imagine users would file such issues?

**Comment by jlengstorf** [comment]
Hey, @svenefftinge!

### Here's the workflow we currently follow:

1. A contributor opens an issue on https://github.com/gatsbyjs/gatsby
2. In the issue template, we request a bug reproduction repo
3. The contributor creates a new repo on GitHub (or a Gist, etc.) and posts the link in the issue
4. A maintainer clones the reproduction, installs dependencies, starts it up, and validates that the bug is happening

### What we'd love to do instead:

1. A contributor opens an issue on https://github.com/gatsbyjs/gatsby
2. In the issue template, we request a bug reproduction repo
3. The contributor creates a gitpod reproduction and posts the link in the issue
4. A maintainer opens the link to see the running code and validates that the bug is happening

This would save us _tons_ of time, and also allow us to make any obvious fixes (e.g. misconfigured plugins, out-of-date dependencies) right in the gitpod — this would be extremely useful for future Googlers who hit the same issue and so on.

This could be done either by allowing outside access to the repos for review directly, or by allowing a share link to auto-copy the code to the new user's gitpod account (so it doesn't mess with billing, etc.).

Does this sound like what you've planned? If so, do you have an ETA?

Thanks!

**Comment by svenefftinge** [comment]
Sounds good. Just to make sure I understood correctly.
You are currently asking your users for a repository containing reproducing code. Such a repo can already today be started with Gitpod. Just prefix the URL, but I guess you are aware of that.

What we are working on now is a command that creates a snapshot of the current state (including opened editors and so on) and provides the user a link. Anyone clicking on that link would start her own copy of that workspace.

We have just started working on it. The plan is to ship it in two to three weeks. I will ping you once we have something for you to try.

**Comment by svenefftinge** [comment]
A user shall have a command in Theia that provides a shareable clone link for the current workspace state. It should capture
 - the workspace state
 - the UI state (editors, views, layout)

Any user clicking on such a link will get her own copy of it.

**Comment by svenefftinge** [comment]
For (re)storing the UI state we need to decorate the `ShellLayoutRestorer`. Such that we can `deflate` the UI layout and `inflate` at arbitrary times. It is currently done on load and unload.

Not necessarily part of the work done for this but related: We should share the UI layout state for shared workspaces as well. We could make it so that if no initial layout exists in the browser's storage we ask a service and only if that also doesn't have layout information we go back to the initial layout based on the context. We would store the layout once when starting sharing.

**Comment by svenefftinge** [comment]
Solved in master. Will be part with next week's deployment.

**Comment by svenefftinge** [comment]
More info on this
blog: https://medium.com/gitpod/code-never-lies-creating-reproducibles-for-any-programming-language-7946021a68f2
docs: https://docs.gitpod.io/33_Sharing_and_Collaboration.html#sharing-snapshots
