### ISSUE TITLE
Plugins support

### ISSUE THREAD

**Issue by GuzioMG** [gitpod-io/gitpod#550]
I think it's very self-explaining. Only thing, which came to my mind is security. Because IDE runs in cloud, security may be a problem. But way to resolve this may be forcing plugin creators to run their plugins on their own cloud. Gitpod will be only a reciver. Only getting syntax highlighting, autocompletion and error detection results. Not actually running the plugin itself.,

**Comment by svenefftinge** [comment]
Hey @GuzioMG, thanks for all the feedback. Really appreciated!
We will allow users to install VS Code extensions quite soon. It is tracked in #433.

**Comment by GuzioMG** [comment]
Oh, sorry I didn't find #433. But thank you for reply!

**Comment by svenefftinge** [comment]
No need to apologize. Better double than not at all.
