### ISSUE TITLE
[configurator] Buttons don't do anything

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5501]
When looking at the configurator of a git-configured project, the "Run Prebuild" button is disabled.
Also, the "Open Workspace" button doesn't do anything.

**Comment by jankeromnes** [comment]
Thanks for the feedback @svenefftinge!

Please note that the buttons in the Configurator are being heavily reworked in https://github.com/gitpod-io/gitpod/pull/5474

**Comment by svenefftinge** [comment]
does it mean this is solved then? in that case please assign the issue (and all others that are reflected in your PR).
