### ISSUE TITLE
Persist team selection on reload

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5519]
### Problem to solve

Currently, clicking on the Gitpod logo or (re)loading `gitpod.io` redirects to the personal account default page.

### Proposal

Let's persist team selection when clicking on the Gitpod logo or reloading `gitpod.io`.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5519#issuecomment-924744640):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by AlexTugarev** [comment]
@gtsiolis, I created https://github.com/gitpod-io/gitpod/pull/5854 for the Gitpod icon part of this issue. 

Please verify, that reloading from any team page redirects to gitpod.io. I could not reproduce it.
