### ISSUE TITLE
Launch workspace with open preview of a markdown file

### ISSUE THREAD

**Issue by chuck-alt-delete** [gitpod-io/gitpod#5520]
Hey folks, big fan! Small request:

## Feature request

I’d like my students to click the “Open in Gitpod” button and have the workspace IDE show the preview of the readme.md file on launch. This could include options to have the preview open on left, right, or whole pane.

## Use Case

The idea is that students open the workspace and then the directions in the readme are right there for them to follow. This reduces friction for the learner.

**Comment by chuck-alt-delete** [comment]
This works at least with a readme file using VS code’s `startupEditor` setting. I’ll close this. See https://community.gitpod.io/t/open-readme-in-preview-on-start-launch/4892 for more details

**Comment by julienbusset** [comment]
I can’t find doc about how to use it: do you know where it is available?

**Comment by julienbusset** [comment]
Here is my detailed solution:
- in gitpod.yml, in tasks:
```
  - name: Open readme
    init: gp open README.md
```
- in .vscode/settings.json:
```
{
    "workbench.editorAssociations": 
        {
            "README.md": "vscode.markdown.preview.editor",
        }
}
```

**Comment by axonasif** [comment]
Thanks for sharing @julienbusset, clever solution there on the `.vscode/settings.json` 😁

**Comment by julienbusset** [comment]
You're welcome @axonasif :-) I also shared it on the Gitpod's Discord server (as Beuj).

**Comment by axonasif** [comment]
I saw 😉
