### ISSUE TITLE
When starting a new workspace from the Project Configurator, sometimes the config file is not present in the workspace

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#5522]
### Bug description

When a Project has a configuration saved in the Project DB, and there is no `.gitpod.yml` in the repository, the Project DB configuration should always be added into workspaces for that repository (as an untracked `.gitpod.yml` file).

However, in some cases, it seems that the Project DB config is not added to the workspaces.

### Steps to reproduce

The expected flow is:

1. Add a Project, and get to the Configuration step
2. Edit the config, and click on `Run Prebuild`
3. Once the Prebuild is complete, click on `New Workspace`

### Expected behavior

If the repository does not have a committed `.gitpod.yml`, the new workspace should have an untracked `.gitpod.yml` containing the config from the Project DB.

Additionally, all new workspaces for that repository should also have this untracked `.gitpod.yml` (until someone adds it to Git and starts versioning it).

However, sometimes the config is not present at all in the workspace.

### Anything else?

**Theory**: Maybe it's added in the Prebuild (from the Project Configurator), but not in un-prebuilt workspaces? That would explain why, if the Prebuild fails, there is no config in the workspace.

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5522#issuecomment-970203460):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by AlexTugarev** [comment]
We couldn't reproduce this issue. I also assume, some of this cases are linked to failed prebuilds, or to existing ones, so that it's not clear when to expect a dirty `.gitpod.yml` file to be contributed. 

Let's reopen when we can actually reproduce this issue.
