### ISSUE TITLE
Improve or remove `New Workspace` button in the Prebuild page

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#5523]
Follow-up to https://github.com/gitpod-io/gitpod/pull/5474

In the Prebuild page, there is a `New Workspace` button, with the intent to allow starting workspaces from a Prebuild.

<img width="1447" alt="Screen Shot 2021-09-03 at 11 09 34" src="https://user-images.githubusercontent.com/914497/131980841-41ba17a7-7034-4792-8eea-d2d78b73f0cb.png">

Currently, the button opens the original context URL of the Prebuild (e.g. a branch, or a Pull Request URL). However, this is no longer the correct link if new commits have been pushed to the original branch.

We could either:

- Better explain what the `New Workspace` button does and doesn't
- Point the `New Workspace` button more precisely to a specific Prebuild, e.g. by linking to the original full commit URL that this Prebuild was built for
- Remove the `New Workspace` button

### See also

Suggestion to remove: https://github.com/gitpod-io/gitpod/pull/5474#issuecomment-912387470

> One question to the `New Workspace` button on the Prebuild page: is it practical? You cannot start a workspace for old prebuilds anyways, so the page is more of a view. Wdyt of removing it from there? 

Suggestion to keep and rename the button: https://github.com/gitpod-io/gitpod/pull/5474#issuecomment-912463350

> I'd opt to leave it here. I was just using it and didn't have any doubts that it was handy there. It should maybe show what it does (Open workspace on branch `branch-name`) in the tooltip.

Suggestion to link to a commit context URL: https://github.com/gitpod-io/gitpod/pull/5474#issuecomment-912476273

> Or, we can still link to the exact (potentially outdated) prebuild by using the commit context URL.
> 
> But maybe after using it for a bit we'll know more about what's better here.

**Comment by JanKoehnlein** [comment]
@gtsiolis can you decide from the UX perspective and make this actionable?
