### ISSUE TITLE
WINE not working

### ISSUE THREAD

**Issue by M-Gonzalo** [gitpod-io/gitpod#5532]
### Bug description

I'm getting a `Bad system call` message every time I'm trying to run wine

### Steps to reproduce

```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt install --install-recommends  wine-development wine32-development -y
wine
```

**Comment by axonasif** [comment]
The issue seems to be with `/usr/lib/wine/wine`, which is wine32 for running 32bit programs. 64bit programs just work fine with wine64. Here are some logs:
```bash
gitpod@ws-85ba7317-988c-4c98-b4a0-90dae60e9968 /w/pts-tinype (master)> 
strace /usr/lib/wine/wine
execve("/usr/lib/wine/wine", ["/usr/lib/wine/wine"], 0x7ffe12ffeca0 /* 103 vars */) = 0
strace: [ Process PID=17326 runs in 32 bit mode. ]
brk(NULL)                               = ?
+++ killed by SIGSYS (core dumped) +++
fish: “strace /usr/lib/wine/wine” terminated by signal SIGSYS (Bad system call)
gitpod@ws-85ba7317-988c-4c98-b4a0-90dae60e9968 /w/pts-tinype (master)> 
```

**Comment by CompeyDev** [comment]
This same error occurs with me, except I'm unable to install it in the first place. 
![image](https://user-images.githubusercontent.com/74418041/167599693-b8177111-4ddb-47f0-b284-2b6774e8ef5a.png)
