### ISSUE TITLE
Gitpod Singapore (sg) region

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5534]
_edit: :wave: hey there, please refer to https://github.com/gitpod-io/gitpod/issues/7489 as the source of truth for supporting more regions than just EU and US._

We have discussed internally regarding creating a new region a few times since the team has expanded to include two employees in Australia but a feature request has never been logged.

I've always found Gitpod workable when connecting from the US or EU clusters from Australia but the experience could be better. 

This morning I received customer feedback which has prompted bringing this topic up once again:

>  I was playing with your GitPod Jetbrains Rider repo over the weekend as we're interested in this space for our development team as it would solve a number of challenges that we have, particularly in the longer term.
>
> I kind of got it working, but to be honest the latency was very noticeable and wouldn't lead to a productive development experience. Some of this is probably down to the workspace being hosted in the states and running Rider in the browser. 

I think the GCP Singapore region would be an appropriate choice for expansion for Gitpod. Singapore is also a region for GitHub Codepsaces btw.

nb. I was on 1 bar of Telstra 4G when performing this test.

<img width="613" alt="2021-09-06_13-57-24" src="https://user-images.githubusercontent.com/127353/132158706-84dd2d80-7786-46ed-a991-e6ed5051381f.png">

# Request for the Community

If you are from the South-East Asia Region:
1. Head to gcpping.com
2. Share a screenshot of the test result
3. Share which country/city you are from and insights about your network connectivity. 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3pvka)

**Comment by joshuabezaleel** [comment]
Hi Geoff, the name's Joshua from Indonesia. Been a fan of what Gitpod is working on for quite some time. All the best to the Gitpod team. Hope this helps.
![image](https://user-images.githubusercontent.com/7043511/132159857-f95edae9-f026-4f8b-9fe7-629135bdeade.png)
![image](https://user-images.githubusercontent.com/7043511/132159881-12bd87b9-25de-4baa-bfe5-51fe67472ac3.png)

**Comment by axonasif** [comment]
Hi, it feels awesome to know that gitpod is finally going to have a Singaporean cluster! I'm from Bangladesh and I have been using gitpod for a 4G mobile network.
Thanks!

> Gcpping.com
![Screenshot_20210906-102807](https://user-images.githubusercontent.com/39482679/132160828-57e10995-e7dc-4f6d-b823-e3be3b30605c.png)

> Speed test. Net
![Screenshot_20210906-103306](https://user-images.githubusercontent.com/39482679/132161155-ab822599-e8a5-4fc3-95e9-2b6af4a2c1e2.png)

**Comment by glennsarti** [comment]
From Perth, Western Australia

Wired VDSL (17/7 down/up Mbps)

Appears my traffic is being routed via East Coast AU instead of direct to Singapore.  Rough speed test shows 53ms from me to NewMedia Express SG which is what I'd expect.

![image](https://user-images.githubusercontent.com/5819622/132163345-c59049e8-1148-4583-8148-43d3a76d7757.png)

**Comment by bigint** [comment]
![image](https://user-images.githubusercontent.com/69431456/132164909-e82d475e-c060-4587-85bf-addad22c690a.png)

![image](https://user-images.githubusercontent.com/69431456/132165007-1222683f-131a-417c-80ec-4b3bb81c658f.png)

**Comment by DevEnable** [comment]
Melbourne fibre connection (not NBN). 

![Screen Shot 2021-09-06 at 3 28 31 pm](https://user-images.githubusercontent.com/5424648/132165224-e1a17746-ad83-475a-9936-83d2b9306306.png)

**Comment by svenefftinge** [comment]
Cool! thanks for all the comments. Let's do this!
@meysholdt can you take over and share a plan for rolling this out?

**Comment by meysholdt** [comment]
happy to do so. There are two possible setups for this:
a) setup a workspace-cluster in Singapore, hook it up to the us-meta-cluster and have have our server component route starting workspaces to the geographically closest workspace cluster (Singapore or US).
b) setup a workspace-clusters, a meta-clusters, and a database in Singapore and have the GCP LoadBalancer route users to the geographically closest region. 

I'm in favour of (a) because it is the way to go if we want to support more than three regions: it has lower cloud costs, lower operational effort and more control over workspace-routing, etc. 

However, our server (or bridge) component does not yet support geography(e.g. latency) based routing and we need to decide if that's a feature we we wan to implement now.

**Comment by bigint** [comment]
> However, our server (or bridge) component does not yet support geography(e.g. latency) based routing and we need to decide if that's a feature we want to implement now.

@meysholdt If that sounds difficult, it would be great to add a preference in user settings to choose the data center they want. WDYT?

**Comment by meysholdt** [comment]
Here is a proposal on how we could do automated latency-based workspace-cluster-selection: https://github.com/gitpod-io/gitpod/issues/5596

**Comment by gtsiolis** [comment]
> I think it would be awesome if users would not need to make this decision.

Agree, this is something that would provide unnecessary complexity for the user. 🐼

**Comment by svenefftinge** [comment]
We discussed that we would want to go with the solution outline in #5596. Give our priorities atm this will have to wait a few weeks. Let's aim at scheduling this by mid October.

**Comment by jankeromnes** [comment]
FYI, one more data point from @tnir in https://community.gitpod.io/t/cannot-open-ide/3633/8?u=jan (from Japan, I believe) :

> asia-northeast1, asia-northeast2, asia-east1, asia-east2, asia-southeast1 are my top 5 (15-91ms). us-west1 (169ms) is coming next.
> 
> <img alt="gcping com_" width="300" src="https://user-images.githubusercontent.com/599268/133566791-d8556db1-4f29-43ae-a75d-603e6b829ca1.png" />

**Comment by cloudsbird** [comment]
Can we know when This Feature will be ready?

**Comment by bigint** [comment]
Yes we are loving to see it!

**Comment by meysholdt** [comment]
removing from Platform Inbox because this depends on https://github.com/gitpod-io/gitpod/issues/5596. See [Sven's comment](https://github.com/gitpod-io/gitpod/issues/5534#issuecomment-918067331) on how we should proceed.

**Comment by tnir** [comment]
@jankeromnes Any updates?

**Comment by bigint** [comment]
Waiting for this very hard 🤩

**Comment by joepurdy** [comment]
Our engineers in APAC would be your best friend if there was a Gitpod cluster local to them in either Singapore or Mumbai 😁

Here's the GCP Ping from one of our engineers in Hyderabad, India
![image](https://user-images.githubusercontent.com/6409227/140981381-ddf83ef3-1134-498a-ace2-9ba0de96433f.png)

**Comment by bigint** [comment]
+1  for Mumbai region 😎

**Comment by bigint** [comment]
@svenefftinge Any updates?

**Comment by Velua** [comment]
Can we pay extra to have a cluster get spun up in whatever GC supported area? Would love something in Sydney.

**Comment by joepurdy** [comment]
> Can we pay extra to have a cluster get spun up in whatever GC supported area? Would love something in Sydney.

Can't speak for Gitpod's team, but I think the more realistic answer that is to self-host: https://www.gitpod.io/self-hosted

Maybe I'm wrong though and they'd be willing to explore bespoke regions if the price was right.

**Comment by ghuntley** [comment]
> Can we pay extra to have a cluster get spun up in whatever GC supported area? Would love something in Sydney.

Me too. I'm in Sydney [1] as well (and I work at Gitpod). I find the latency workable but indeed it could be better. All in good time. Gitpod is right now working on getting underlying primitives for architecture solid to make it possible to deploy anywhere and keep operational support costs (human time) scalable. Hold on. It'll be worth it.

[1] https://www.ghuntley.com/anywhere

**Comment by JcdeA** [comment]
I live in Seoul, but somehow Hong Kong wins with the least latency. I assume the actual DC isn't located in Seoul, as that wouldn't make much sense economically.

I have pretty good internet connectivity (~400mbps).

![Screenshot_20211210-181713_Chrome](https://user-images.githubusercontent.com/31413538/145549229-187fe0dd-220b-4325-a7fe-8cef1bafe31c.png)

I would be satisfied with a Singapore cluster to be honest.

**Comment by cloudsbird** [comment]
any updates about it?

**Comment by vertusdster** [comment]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/61446504/160531001-bc34c00b-bbd6-4716-9f87-50197cbbc22f.png">

**Comment by smacintyre** [comment]
City: Krung Thep Maha Nakhon (formerly, "Bangkok")
Connection: AIS Fibre

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/361689/160534701-d87f00e6-95ff-4d27-8b38-9974ff0726b6.png">

**Comment by bigint** [comment]
Any updates @svenefftinge @ghuntley 🙇🏻  its been too long 😕

**Comment by meysholdt** [comment]
This issue was in the inbox of the platform team for some reason. However, there is not much the platform team can do here. Much rather
* the workspace team would need to set up a cluster in the desired region
* also, on the WebApp side newly starting workspaces would need to be routed to the new cluster based on latency. Not sure if this falls into the area of team workspace or team WebApp.

I'm moving the issue to the inbox of the workspace team so that they can handle prioritization/planning.

**Comment by aalcock** [comment]
Adding a "me too". I am considering Gitpod for my team in Singapore, Thailand and the Philippines - but the ping time to EU/US makes it extremely painful (I'm getting between 200-400ms and I am on gigabit fibre).

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/167788372-5ee9d60f-f0b2-4882-b370-39b1dec3cfd7.png)

**Comment by pan93412** [comment]
I'm from Taiwan, and I connect Internet with a Wi-Fi from a optical fiber network:

<img width="1440" alt="截圖 2022-05-26 上午9 27 04" src="https://user-images.githubusercontent.com/28441561/170396396-fe990710-6d15-45b6-b800-008d191f4495.png">

**Comment by bigint** [comment]
Still very slow in APAC region 😭

**Comment by chientrm** [comment]
<img width="992" alt="Screen Shot 2022-08-25 at 7 33 40 PM" src="https://user-images.githubusercontent.com/70304839/186665720-2a279449-204a-420d-8da5-69aeddb8d082.png">

**Comment by kylos101** [comment]
:wave:  hey there, please refer to https://github.com/gitpod-io/gitpod/issues/7489 as the source of truth for supporting more regions than just EU and US. We are closing this issue to consolidate to the single issue.

**Comment by loujaybee** [comment]
Please see [related comment](https://github.com/gitpod-io/gitpod/issues/7489#issuecomment-1240515469) on #[7489](https://github.com/gitpod-io/gitpod/issues/7489), copied below: 

---

There seems to be some confusion that is related to the closing of the following issues:

- https://github.com/gitpod-io/gitpod/issues/5534
- https://github.com/gitpod-io/gitpod/issues/6139

Please note: This is not a an update of the status of this issue (closing or opening). The reason for the consolidation is that we now have a proliferation of different regional issues being raised by users. It doesn't make sense for users to directly raising issues about specific required regions, as when it comes to rolling out new regions we'll need to review:

Costings
Latencies
Current + predicted future usage of Gitpod
...and many other factors.

It makes sense for this conversation to happen in a single issue, which is this one. Please continue to share any thoughts or feedback. We'll look to update the description soon as a consolidation of current thinking, as there are now multiple region related issues with many comments.

Thanks all 🙏
