### ISSUE TITLE
[content-service] nil deref on deleteusercontent

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#5535]
- `DeleteUserContent: failed`: https://console.cloud.google.com/errors/CJO2u-nKrbfI9gE?time=P7D&project=gitpod-191109
- `panic: runtime error: invalid memory address or nil pointer dereference`
  - https://console.cloud.google.com/errors/CMOphKWj6OOuYg?time=P7D&project=gitpod-191109
  - https://console.cloud.google.com/errors/CL2L5M22uqDOmwE?time=P7D&project=gitpod-191109

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5535#issuecomment-913440211):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
