### ISSUE TITLE
Switch to INFO log level by default

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5538]
We have too much noise in our logs. To curb this flood of data we'll switch to INFO by default.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5538#issuecomment-913449828):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
