### ISSUE TITLE
Set hostAliases via .gitpod.yml

### ISSUE THREAD

**Issue by davemecha** [gitpod-io/gitpod#554]
It is currently not possible to change the `/etc/hosts` file of a gitpod, as discussed in the [community](https://spectrum.chat/gitpod/general/how-can-i-add-a-host-to-a-gitpods-hostfile~d7c0f703-148f-4552-b4ce-972e892a0ad4) due to [Kubernetes limitations](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/#why-does-kubelet-manage-the-hosts-file).

In Kubernetes this can be solved with [`hostAliases`](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) that is currently not available to be configured in a gitpod.

I want to suggest to be able to set `hostAliases` via `.gitpod.yml`.

**Comment by mikenikles** [comment]
I run into the same challenge working on a web application that uses cookies which have "SameSite" set to true.

@davemecha Have you managed to find a workaround to update `/etc/hosts`?

**Comment by davemecha** [comment]
> I run into the same challenge working on a web application that uses cookies which have "SameSite" set to true.
> 
> @davemecha Have you managed to find a workaround to update `/etc/hosts`?

unfortunately not AFAIR

**Comment by mikenikles** [comment]
I'm curious to see if the new rootless workspaces will solve this issue. See https://youtu.be/l4I2TVAnBuw.

In my case with the cookie, I ended up using a `/api` endpoint with a redirect to my API service. It now all runs on the same domain and I no longer need to edit `/etc/hosts`.

Keeping my eyes open for the rootless workspaces, this looks promising.

**Comment by chuck-confluent** [comment]
I'd love this as well. Use case is education purposes where I'd like learners to use hostnames rather than `localhost` to connect to various containers running in docker compose. I want those applications to run inside and outside the docker-compose network without code changes or setting different environment variables.

**Comment by chuck-confluent** [comment]
It is possible to remove the `meta: stale` tag?

**Comment by mikenikles** [comment]
I removed the `meta: stale` label since this continues to be a valid issue with at least two people requesting it.

**Comment by sagor999** [comment]
@davemecha we recently made a change that allows you to modify `/etc/hosts` now. Can you give this a try and see if it resolved your issue?
https://github.com/gitpod-io/gitpod/pull/8061

**Comment by davemecha** [comment]
@sagor999 Thanks for the update.

I don't have the use case right now any more, but I tested changing `/etc/hosts`.

Since the change of `/etc/hosts` is not persistent, it must be done on every workspace startup. So I did it with:

``` yaml
tasks:
  - before: echo "127.0.0.1 myhost" | sudo tee -a /etc/hosts
    command: cat /etc/hosts
```

This works like charm. Thanks for implementing :)
