### ISSUE TITLE
[meta] revise levels of logging statements 

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#5551]
In the engineering sync we agreed on globally setting the log level to info in two weeks (20th of September).

To avoid we're losing important messages we should go through all meta-components and revise the log messages and their levels. 

- [x] server
- [ ] dashboard
- [x] content-service
- [x] payment-endpoint
- [ ] dbsync
- [ ] db-sync
- [x] ws-manager-bridge
- [ ] image-builder

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5551#issuecomment-914085136):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
I will start working on this, starting out with the `server` part (and all referenced libraries)

**Comment by geropl** [comment]
Closing now as I consider the first round of logging cleanup as finished. Needless to say that this is a process we have to keep repeating! :slightly_smiling_face:
