### ISSUE TITLE
It is not letting me get in the workspace

### ISSUE THREAD

**Issue by tommygonzaleza** [gitpod-io/gitpod#5553]
### Bug description

I'm trying to open a workspace but this shows up: 
```
An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: Time limit reached)
```

![image](https://user-images.githubusercontent.com/56565994/132247495-a758c402-462d-4472-ab0d-ac4b8e8e2c5a.png)

### Steps to reproduce

I'm just opening the workspaces

### Expected behavior

Open the workspace correctly

**Comment by svenefftinge** [comment]
Looks like internet connection issues. Can you share the repo you are trying to open?
