### ISSUE TITLE
Not able to install on single node cluster

### ISSUE THREAD

**Issue by firecraftgaming** [gitpod-io/gitpod#5554]
### Bug description

Hi I am not able to install gitpod self hosted on kubernetes on a 1 node cluster as I get `0/1 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.`

### Steps to reproduce

install gitpod self hosted on a 1 node kubernetes cluster

### Expected behavior

not getting the message at kubectl describe

**Comment by corneliusludmann** [comment]
In general, installing Gitpod on a single node cluster should work. Which Kubernetes distribution do you use? Have you configured something special in the `values.yaml` file?

**Comment by firecraftgaming** [comment]
I havent set anything special in `values.yaml` and I installed the latest kubernetes using `kubelet`, `kubeadm` on Ubuntu 20.10

**Comment by corneliusludmann** [comment]
Have you tried to remove the taint from the node to check if it would work then?

```
kubectl taint nodes  <your-node-name> node-role.kubernetes.io/master-
```

**Comment by firecraftgaming** [comment]
So that works now they arent pending anymore but it still timeouts on db migration but gonna have to debug that some more
