### ISSUE TITLE
Recharging Subscription Hours

### ISSUE THREAD

**Issue by madoar** [gitpod-io/gitpod#556]
I know that this is more of a theoretical question, but it just didn't leave my mind. Therefore:
- What happens if I use all my 100 subscription hours and I still require more? I would like to know the answer to this question both for public repositories (Open Source Subscription) and private repositories (Personal Subscription)

**Comment by svenefftinge** [comment]
You would need to upgrade to the unlimited subscription or wait for the next subscription cycle.

**Comment by madoar** [comment]
I agree to this assumption for the `Personal` subscription, but for the `Open Source` subscription I think more hours should be given. The issue is, that the name of the `Open Source` subscription doesn't necessarily mean that the project needs to be for non-commercial use, right? I mean there are a lot of companies who make money by providing open source, i.e. free of charge, software and then sell some kind of support around it. 

In such a scenario the developer would mostly fit in the `Open Source` developer category (in that he works with public repositories) with the divergence that he also provides commercial support around it.
If you don't think the `Open Source` subscription to be compatible with such developers, then I think you should give the `Open Source` subscription a different, more clear name.

**Comment by svenefftinge** [comment]
We thought about having an additional 'professional open-source' plan that is unlimited in hours but limited to public, but I feel that the targeted group is too small. Adding too many options can be confusing. I think if you get paid to work full time on open-source the unlimited subscription should work.
