### ISSUE TITLE
Running `brew update` is causing workspace to shut down 😱 

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#5560]
### Bug description

- Open any Gitpod workspace
- Run in terminal `brew update`

Workspace shuts down.

### Steps to reproduce

- Open any Gitpod workspace (ie. https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node)
- Run in terminal `brew update`

Workspace shuts down.

### Example repository

https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node

### Anything else?

I tested it on both Edge Chromium and Firefox browsers.

**Comment by AlexTugarev** [comment]
Duplicate of https://github.com/gitpod-io/gitpod/issues/5280
