### ISSUE TITLE
[workspacekit] Reduce log verbosity

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5561]
workspacekit logs a lot as `info` that should be `debug`, e.g. all of its syscall handling.

**Comment by roboquat** [comment]
@aledbf: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5561#issuecomment-916384296):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
