### ISSUE TITLE
[supervisor] Reduce log noise level during shutdown

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5562]
When supervisor shuts down it's very noisy about being unable to terminate child processes, e.g.
```
"error":"wait: no child processes","level":"warning","message":"cannot terminate child process"
```

This need not be an error because the child process no longer exists. It certainly should not be a warning.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5562#issuecomment-914088326):

>/schedule
>/assign


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
