### ISSUE TITLE
[ws-manager] modifyFinalizer is too loud if pod no longer exists

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5563]
If the pod no longer exists and we want to remove the finalizer that's not really an error, because the pod is actually gone and it's good that way.

**Comment by roboquat** [comment]
@aledbf: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5563#issuecomment-916381298):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
