### ISSUE TITLE
[ws-manager] Make config part of the API

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5564]
to help build future prototypes of e.g. the installer or CRD-based ws-manager.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5564#issuecomment-914048291):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
