### ISSUE TITLE
Improve "Configuring the Terminal" section

### ISSUE THREAD

**Issue by madoar** [gitpod-io/gitpod#557]
Inside the [Configuring the Terminal](https://www.gitpod.io/docs/44_Config_Start_Tasks/#configuring-the-terminal) section of your documentation you're explaining the different parameters, i.e. `openIn` and `openMode`. The contained tables look kind of out of place to me. 
I think a larger example would be better to understand how the parameters are to be used.

**Comment by justinmoon** [comment]
After reading these docs it's unclear to me how exactly you use these options

**Comment by jankeromnes** [comment]
Thanks for bringing this up again. I agree that it's unclear how to use these attributes, so I'll add an example to this section.

**Comment by jankeromnes** [comment]
@madoar @justinmoon Does this example make `openIn` / `openMode` a bit clearer?

https://github.com/gitpod-io/website/commit/c9d0e38da6bbf4ef8c6db45f6b100336826f8d75

(It should be deployed to www.gitpod.io/docs/ soon.)
