### ISSUE TITLE
No logs for short prebuilds

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#5573]
If a prebuild is very short, i.e. doesn't take a while to be built, it appears to not be shown with logs and logs are not persisted in the storage. 

How to reproduce? Just create a project for a not yet configured repo in your account and use the simples `echo something` template form the project configurator.

**Comment by AlexTugarev** [comment]
cc. @geropl, because he already had a suspicion about this.

**Comment by geropl** [comment]
Could https://github.com/gitpod-io/gitpod/commit/a1da634398a89ced4733e9fb568ecdd97272e86d be the cause?
We no longer wait for `c.State.Running == nil` for the workspace container, which includes proper shutdown of `supervisor`, including writing of terminal logs. @csweichel

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5573#issuecomment-924940521):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
Should be fixed with this one: https://github.com/gitpod-io/gitpod/pull/5897

**Comment by AlexTugarev** [comment]
@geropl, I'm afraid this is not the case

Should be fixed with this one: #5897
