### ISSUE TITLE
Add payment methods: PayPal and PaySafeCard

### ISSUE THREAD

**Issue by dragonDScript** [gitpod-io/gitpod#5577]
PayPal is a known payment method. Paysafecard is a way to pay with cash on the internet. I'd love to pay gitpod, however I'm underage and I don't own a PayPal or credit card.

**Comment by dragonDScript** [comment]
Pls don't close

**Comment by JanKoehnlein** [comment]
PaySafeCard is not suppoted by any of our payment providers/gateways (Stripe, Chargebee), so it is clearly out of reach ATM.

PayPal is, but requires some more investigation what that would mean for our backoffice. This is unlikely going to happen in Q1 2022.

**Comment by dragonDScript** [comment]
Consider PaySafeCard tho. It would allow hobby developers to pay for gitpod without providing their banking details or a paypal account.
