### ISSUE TITLE
[terminal] Add URL handler

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#558]
We should allow clicking links in terminal output.

**Comment by svenefftinge** [comment]
Should also rewrite localhost:port respectively

**Comment by alesanchezr** [comment]
Some other ideas for clicking links on a terminal:
![Screen Shot 2019-05-09 at 11 06 28 AM](https://user-images.githubusercontent.com/426452/57464356-908fcb80-724a-11e9-9f9a-36028b7cb962.png)

**Comment by jankeromnes** [comment]
I love c9.io's Terminal 😄 In Gitpod, I often try clicking on file names in `git status`, hoping for a one-click `git add` (I know that the `Git` left panel does that already, but... old habits die hard).

**Comment by svenefftinge** [comment]
deployed
