### ISSUE TITLE
`code .` hung up forever

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#5586]
Repo: https://github.com/gengjiawen/ts-scaffold

After wait `yarn test` init task finished. `cd sample_out/ && code .`

I have used this a few days ago. Looks like a regression.

**Comment by akosyakov** [comment]
It does work for me. Maybe it was caused by this incident: https://www.gitpodstatus.com/incidents/fk6prflgvvth Since code CLI relies on some env vars.

**Comment by gengjiawen** [comment]
Yeap. Works for me now too.
