### ISSUE TITLE
Cannot uninstall extensions

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5588]
I'm having issues with my vscode extensions. I realized that I have collected a lot of extensions that seem to sync to my account (I guess due to the bug we had in prod two weeks ago?).
Now I wanted to clean this up and uninstalled those extensions. But they are not gone. I see them again in fresh workspaces. Any idea?

**Comment by akosyakov** [comment]
It maybe related to unresponsiveness of Open VSX right now.

**Comment by akosyakov** [comment]
@svenefftinge could you try again?

**Comment by akosyakov** [comment]
I remove it from the groundwork, I think it is related to an incident. Please retry, and add again if it is not fixed yet.
