### ISSUE TITLE
The Undo (ctrl + Z) command is smashing text if it changed from outer service.

### ISSUE THREAD

**Issue by artalar** [gitpod-io/gitpod#559]
**Describe the bug**
The Undo (ctrl + Z) command is smashing text if it changed from outer service.

**To Reproduce**

I use prettier from the terminal, write code, save the file, prettier format it, then I use the undo and get something weird;

(my repo is https://github.com/artalar/redux-steroid)

Original code
![image](https://user-images.githubusercontent.com/27290320/57428805-a1344780-7232-11e9-9e48-248048e9e14a.png)

Edited code

![image](https://user-images.githubusercontent.com/27290320/57428836-bad58f00-7232-11e9-8dd6-abebe8ccffa7.png)

Formatted code after file save (`onchange '**/*.(j|t)s' -- prettier --write {{changed}}`)

![image](https://user-images.githubusercontent.com/27290320/57428894-f7a18600-7232-11e9-8bc5-985521e47593.png)

Undo (ctrl + Z)

![image](https://user-images.githubusercontent.com/27290320/57428910-04be7500-7233-11e9-8cdc-29e276a1c626.png)

**Expected behavior**
The undo operation return previous state of the file, not the editor (i think)

**Comment by svenefftinge** [comment]
The undo stack should be cleared when the contents has been reset.
