### ISSUE TITLE
Allow users to open a new workspace when configuration is Git-based

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5591]
### Bug description

When configuration is stored in git but is invalid, users importing the project cannot open a new workspace. See also [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1631085405146200) (internal).

### Steps to reproduce

1. Add a project with an invalid configuration (`.gitpod.yml`)
2. In the `/configuration` page you can not run a prebuild due to the configuration error or open a new workspace.

### Expected behavior

Allow users to open a new workspace when configuration is invalid.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5591#issuecomment-915032039):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by AlexTugarev** [comment]
'Cannot reproduce. See https://gitlab.com/AlexTugarev/empty-project, there is a typo in the config (`poart`) but the config is not validated at all: 

<img width="1447" alt="Screen Shot 2021-09-28 at 11 15 05" src="https://user-images.githubusercontent.com/914497/135060146-4b57ad3a-c1db-411c-afe7-6ffdde9dc07e.png">
