### ISSUE TITLE
Homebrew not working

### ISSUE THREAD

**Issue by DaveEvans-FanBox** [gitpod-io/gitpod#5593]
### Bug description

The `brew` command is no longer available from the terminal. It worked on Sept 7th '21 but not on Sept 8th '21.
https://www.gitpod.io/blog/brew

### Steps to reproduce

1. GitPod against https://github.com/gitpod-io/template-typescript-node
2. Open a new terminal.
3. Type `brew`

### Expected behavior

On opening a terminal, and typing `brew` I see
```
bash: pyenv: command not found
bash: pyenv: command not found
gitpod /workspace/template-typescript-node $ brew
bash: brew: command not found
gitpod /workspace/template-typescript-node $
```

### Example repository

https://github.com/gitpod-io/template-typescript-node

**Comment by DaveEvans-FanBox** [comment]
Might be related to this change? https://github.com/gitpod-io/workspace-images/commit/ec14e4dbfd953ce9d2baf9b4c6b166fc94052364

**Comment by DaveEvans-FanBox** [comment]
This line seems to install HomeBrew : (https://github.com/gitpod-io/workspace-images/blob/583181ebf3fd68f66f4c32a7d4e61d52362948a3/full/Dockerfile#L67)

I ran this command on it's own in the terminal
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

After about 30 seconds, the GitPod workspace self-terminated and dumped me back to the dashboard.

**Comment by corneliusludmann** [comment]
https://github.com/gitpod-com/gitpod/pull/5899

**Comment by corneliusludmann** [comment]
https://www.gitpodstatus.com/incidents/fk6prflgvvth

**Comment by DaveEvans-FanBox** [comment]
I've re-tested following the resolution of the above incident, and it works for me. Thanks for the quick turnaround.
