### ISSUE TITLE
[server] Offer API through gRPC and gRPC web

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5595]
Currently server offers it's API through JSON-RPC. While convenient at the beginning we're facing more and more issues with this approach:
1. we have to maintain the RPC stack ourselves, rather than just including someone else's work.
2. producing clients for different languages involves a lot of manual effort, e.g. for Go we once generated a stub out of TypeScript and maintained the client manually ever since. For Java we'd be facing a similar situation.
3. JSON-RPC is the odd one out. With the rest of the system using gRPC we have to learn yet another bit of RPC tech
4. API specification, especially with regards to backwards compatibility is much easier in protobuf than it is in TypeScript, just because it's a more reduced set of degrees of freedom. Also, type-safety on the wire is better compared to untyped, arbitrary JSON input.
5. Concerns like authentication and authorisation are difficult to handle orthogonally. Right now we have to check if a user is authorised to perform an action within every function. In gRPC we could centralise this orthogonal concern easily using annotations on the API definition.

## Proposal
Instead of using JSON-RPC, we'd use gRPC and [gRPC-web](https://github.com/grpc/grpc-web). The former would be offered by server directly and proxied by caddy (which [supports this out of the box](https://caddy.community/t/caddy-2-with-grpc/7813/8) because gRPC is essentially HTTP/2), while the latter would be produced by a gRPC-web proxy e.g. as Caddy plugin.

This way we'd have access to the server API from the web and other clients (e.g. supervisor). Authentication would be handled using gRPC metadata which contains cookies or a Gitpod token. The actual authentication would still be handled by server and tied into the session mechanism we have today.

## Migration path
Moving to a new RPC mechanism/API tech is no small feat. But, it's also not an all-or-nothing thing. We could follow a gradual migration path where we operate the JSON-RPC and gRPC interfaces in parallel - with an **agreement to add new functionality to the gRPC interface only**.

To do this, we'd follow these steps:
1. Initial lifting
    1. create a `server-api` package akin to the other `-api` packages, generating clients for TypeScript, Go and Java.
    2. add a gRPC server to server, tie it in with authentication and function scopes
2. Method migration: introduce methods on a per-case/need basis, e.g. we'll need `sendHeartbeat` from Java soon so we'd start with that
    - each of the existing methods would be implemented in parallel to the gitpod-server-impl. We'd move the actual functionality from the `GitpodServerImpl` into a different class using the TypeScript types we use today. The JSON-RPC implementation (`GitpodServerImpl`) would simply call those extracted functions - and because we're using the same types that's essentially just functionally equivalent refactoring. The gRPC service would convert the gRPC types to the old shapes, and also call the very same backing implementation.
 
Eventually we'd end up in a situation where we'd be left with say 50% of functionality in JSON-RPC only because there's been no non-web client that needed to consume it. When we we've reached this point we need to go for a deliberate effort to migrate the dashboard and this remainder of functionality to gRPC. At this point we should already have the gRPC-web integration in the dashboard due to new functionality that came in.

## Don't over-generalise/slice too thinly
**Beware**: we have to resist the urge to over-structure this new gRPC API. It's all too easy to introduce a host of services that are very finely cut - a mistake we made with content-service. Instead we should focus on large groups of functionality, e.g.
- `WorkspaceService`: everything that pertains to workspaces, creating new ones, starting them, stopping them, sending the heartbeat, controlling admission, opening ports
- `UserService`: everything that pertains to users, e.g. changing their settings
- `TeamsAndProjectsService` everything that pertains to teams and projects
- `AdminService` all admin related functionality (all functions starting with `admin`)

**Comment by akosyakov** [comment]
We decided that we don't go with it yet, but for now use https://github.com/eclipse/lsp4j/tree/master/org.eclipse.lsp4j.jsonrpc to expose sendHearbeat message for JetBrains integration.
