### ISSUE TITLE
Long env variables passed thru URL don't work

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#561]
**Describe the bug**
I'm using this URL to pass some env variables to the workspace:
https://gitpod.io/#BC_ERROR_HOOK=https%3A%2F%2Fassets.de%2Fapis%2Factivity%2Fcoding,BC_ASSETS_TOKEN=ey0eeXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCI6MjE5LCJpYXQiOjE1NTc0MTM5MDksImV4cCI6MzMxMTQzNjU5MDl9.tekd4Mr0iizX_QTAGm1h-Cxy1FU_UHUH7OEfplflsw4,BC_STUDENT_EMAIL=my%40email.com/https://github.com/4GeeksAcademy/html-hello.git

If I try printing on the container console  `echo $BC_ASSETS_TOKEN` the variable is empty.

However, if I use a smaller URL with just one variable like this one:
https://gitpod.io/#BC_ASSETS_TOKEN=ey0eeXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGllbnRJZCI6MjE5LCJpYXQiOjE1NTc0MTM5MDksImV4cCI6MzMxMTQzNjU5MDl9.tekd4Mr0iizX_QTAGm1h-Cxy1FU_UHUH7OEfplflsw4/https://github.com/4GeeksAcademy/html-hello.git

The variable is printed on the console correctly.

Is there any length limit for the variables? The URL standard limit on the web is 2000, but this URL that I am using has ~350 characters.

**To Reproduce**
Just click on both links and compare.

**Expected behavior**
All 3 env variables to be available inside the container.

**Comment by alesanchezr** [comment]
Well, now I don't think the URL limit is the problem because the other variables are being successfully passed to the container.

I don't know what it is.

**Comment by meysholdt** [comment]
This could also be related to URL-encoding. Maybe we do the decoding too late or too early during parsing.

**Comment by alesanchezr** [comment]
Hello @meysholdt I wanted to follow up on this, I have more information about this error, basically the error happens 30% of the times, when it happens I just tell the students to try again 2 or 3 times and then it works.
