### ISSUE TITLE
Some failed prebuilds use a wrong status label

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5611]
### Bug description

Some failed prebuilds use a wrong status label.

| Prebuilds List | Prebuild Page |
|-|-|
| <img width="1015" alt="Screenshot 2021-09-08 at 7 43 36 PM" src="https://user-images.githubusercontent.com/120486/132550714-424ee41f-3990-4f3c-90cb-e09c6a452278.png"> | <img width="936" alt="Screenshot 2021-09-08 at 7 43 48 PM" src="https://user-images.githubusercontent.com/120486/132550722-01d210f7-6cd2-41d1-80ff-720866b50ed2.png"> |

### Steps to reproduce

N/A

### Example repository

See [prebuild](https://gitpod.io/t/gitpod/gitpod/5a09fc7e-40c6-4549-b785-ece367564c96) for `gitpod-io/gitpod` in `gitpod.io`.

**Comment by AlexTugarev** [comment]
@gtsiolis does it stay like this on the Prebuild Page on reload after +10 seconds?

**Comment by gtsiolis** [comment]
@AlexTugarev yes, you can also try this using the example link above:

> https://gitpod.io/t/gitpod/gitpod/5a09fc7e-40c6-4549-b785-ece367564c96

**Comment by gtsiolis** [comment]
This seems to be still an issue, see another example:
> https://gitpod.io/t/gitpod/gitpod/bb33f016-55a3-43e7-a8a2-e875a74effe4

However, let's move this to the _Next Iteration_ in the relevant project board[[1](https://github.com/orgs/gitpod-io/projects/7/views/3)] as this affects a really small set of prebuilds.

| Prebuilds List | Prebuild |
|-|-|
| <img width="1093" alt="p-1" src="https://user-images.githubusercontent.com/120486/134693419-2248b00a-6745-4243-bb01-49c8c1af36f2.png"> | <img width="1093" alt="p-2" src="https://user-images.githubusercontent.com/120486/134693422-5d1e828a-3165-47e1-9fe0-a9ae2ada57a7.png"> |

**Comment by jankeromnes** [comment]
Indeed, good catch!

I think that in some cases, when the prebuild instance fails (i.e. the [WorkspaceInstance](https://github.com/gitpod-io/gitpod/blob/5885a2afb65b4d0ebbf0a99d489ee40872773cf2/components/gitpod-protocol/src/workspace-instance.ts#L9-L54) has a failure condition and stops), for some reason the prebuild status is not updated (i.e. [PrebuiltWorkspace](https://github.com/gitpod-io/gitpod/blob/5885a2afb65b4d0ebbf0a99d489ee40872773cf2/components/gitpod-protocol/src/protocol.ts#L634-L645) remains in `state = 'building'`?).

**Comment by gtsiolis** [comment]
No longer relevant as we do not include the second status label in the header.

However, we still need to handle links to :a: deleted prebuilds like the one linked in the issue description and :b: non-existent prebuilds. Cc @jldec

**Comment by easyCZ** [comment]
This issue has been resolved in https://github.com/gitpod-io/gitpod/pull/8805
