### ISSUE TITLE
Allow specifying Gitpod Environment Variables inside PR descriptions

### ISSUE THREAD

**Issue by madoar** [gitpod-io/gitpod#563]
Sometimes you want to specify some gitpod environment variables on a single PR basis without performing changes to the repository itself (i.e. without modifying the `.gitpod.yml` file).

The environment variables could be defined in a code environment ("\`\`\`gitpod") inside the PR. Whenever gitpod builds the workspace it searches for a "\`\`\`gitpod" code environment in the PR description. In case such an environment is found it is parsed and the included environment variables are applied.

### Example
Let us assume we have a repository with a [library](https://github.com/madoar/angular-archwizard) and a separate [example repository](https://github.com/madoar/angular-archwizard-demo) (which doesn't include the library itself).

Whenever a new feature is added to development branch of the library repository a new example should be added to the example repository, which illustrates the new feature. Because the library is not released with every new feature it is hard to build the example repository against the library. 

To allow for the correct commit of the library repository to be used at all times it would be nice to be able to specify the to be used library commit inside the feature PR in the example repository.

**Comment by meysholdt** [comment]
Interesting idea. Let's do some thought experiments on it. 

First I want to point out that we already allow passing env [variables via URL](https://www.gitpod.io/docs/47_Environment_Variables/#passing-environment-variables), so you could include one or more hyperlinks to launch new Gitpod workspaces with your env variables. 

While I think this could solve your use-case, it has the drawback that the env variable are not available in prebuilds and therefore your example repository could not use prebuilds. This may be ok, depending on how long a build takes :)

In your example, you mention that a feature-example should be aware of the commit-sha1 from the library that it compiles with. Maybe it would be useful when that information would also be available when building the feature-example with CI/CD (Travis, Jenkins, etc. ) or when building it locally. Would it be an option to use git submodules in the example repository to include the library repository at exactly the right version? This way, the library would be available in the right version in Gitpod-prebuilds, CI/CD, and when developing locally.

**Comment by madoar** [comment]
> First I want to point out that we already allow passing env variables via URL, so you could include one or more hyperlinks to launch new Gitpod workspaces with your env variables.

Yes, I saw them in your documentation. 

> While I think this could solve your use-case, it has the drawback that the env variable are not available in prebuilds and therefore your example repository could not use prebuilds. This may be ok, depending on how long a build takes :)

The main issue with environment variables in my opinion is that the user needs to add them manually to the URL. This becomes even more problematic when you think about encoding problems (for example space characters inside variables etc.)

> In your example, you mention that a feature-example should be aware of the commit-sha1 from the library that it compiles with.

Ideally it is not only the commit-sha1 about which the example should be aware of but also other information. For example it could be useful to allow changing the used library git repository to your fork to show how a change done to your fork allows a new feature.

> Maybe it would be useful when that information would also be available when building the feature-example with CI/CD (Travis, Jenkins, etc. ) or when building it locally. 

Yes, it would definitely be useful if Travis and others are able to interpret environment variables specified the same way.

> Would it be an option to use git submodules in the example repository to include the library repository at exactly the right version? This way, the library would be available in the right version in Gitpod-prebuilds, CI/CD, and when developing locally.

Truthfully I'm not sure. I've never used git submodules before but as far as I know it is not possible to replace an entire submodule with another (by changing the repository to your fork for example), right?
