### ISSUE TITLE
Public Ports are returning 401

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#5638]
### Bug description

All public ports are returning 401

### Steps to reproduce

Run a web server, say node, make the port public. Try to visit using another browser

You will get a 401

### Expected behavior

The other browser should be able to visit it

**Comment by akosyakov** [comment]
I just tried and could not reproduce. Could it be that the app itself has some auth?

**Comment by smacintyre** [comment]
@akosyakov It seems to be working properly again. There is no authentication on the endpoints. It was failing this morning, but now all good.

**Comment by ajimix** [comment]
I'm running into the same issue.

This is the `.gitpod.yml` config:

```yml
ports:
  - port: 4000
    onOpen: open-browser
    visibility: public
```

And the url works fine if I'm logged in, but opening in incognito returns 401

**Comment by akosyakov** [comment]
@ajimix Could you share the workspace id and time when it happened?

**Comment by ajimix** [comment]
@akosyakov I tried again now and now it works. I did nothing other than just starting the workspace again (which was automatically stopped due to timeout). Strangely enough, is the same that @smacintyre experienced. First, it didn't work, some hours later it worked 🤨

**Comment by akosyakov** [comment]
@ajimix When it happens next time please have a look at the remote explorer view and state of ports there. Maybe it was not exposed at all yet, also remember the workspace id and your local time. If you share them I can check what was going in your workspace and the system at that time.
