### ISSUE TITLE
Gitpod extension for the GitHub CLI 

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#5639]
👋 @gitpod-io/product and @gitpod-io/engineering-ide over at https://github.com/gitpod-io/gh-gp you will find an extension for https://github.blog/2021-08-24-github-cli-2-0-includes-extensions/.

I'd like to open it up to the public but before doing so let's run it through a review phase:

# review 

1. naming of the extension and CLI method of invoking "gh gp" (current) vs "gh gitpod"
1. when you are in a github repository on a local computer `gh gp` by default will open. Do we want open to be the default verb?
1. discuss other verbs/input for ideas for future expansion (ie. gitpod local app?).
1. anything else!

# typical usecase

A user has cloned a GitHub repository on their local computer and desires a command to open the repository in Gitpod.

**Comment by svenefftinge** [comment]
Sounds all fine to me.
