### ISSUE TITLE
Add local IDEs (vscode and jetbrains) options to the user settings

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#5641]
The user should be able to select what IDE they prefer and the options should be:
* vscode in the browser
* vscode in the desktop + vscode in the browser (fallback)
* pycharm + vscode in the browser (fallback)
* webstorm + vscode in the browser (fallback)
* intellij + vscode in the browser (fallback)
* ...

Additionally, the user should be able to select the version for each IDE. (e.g. desktop vscode latest + browser vscode stable as fallback). 

@gtsiolis Do you have any ideas on how to visually present these options?

cc @corneliusludmann @akosyakov

**Comment by loujaybee** [comment]
Given that JetBrains is now showing in the dashboard, I've extracted @akosyakov's point about the VSCode Desktop IDE's here: https://github.com/gitpod-io/gitpod/issues/6488 so I'll go ahead and close this issue for now.
