### ISSUE TITLE
[self-hosted] Workspace will not start with error: cannot mount proc

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#5647]
### Bug description

When starting a workspace it hangs at the "pulling container image..." screen and fails to start with the error message "cannot mount proc" reported by both the `ws-daemon` and the workspace pod.

**ws-daemon**
```
{
  "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
  "error": "cannot open tree:
    github.com/gitpod-io/gitpod/ws-daemon/pkg/iws.moveMount
        github.com/gitpod-io/gitpod/ws-daemon/pkg/iws/iws.go:512
  - function not implemented",
  "level": "error",
  "message": "cannot mount proc",
  "procPID": 29095,
  "reqPID": 27,
  "serviceContext": {
    "service": "ws-daemon",
    "version": ""
  },
  "severity": "ERROR",
  "time": "2021-09-10T04:42:05Z"
}
```
**workspace**
```
{
  "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
  "error": "rpc error: code = Internal desc = cannot mount proc",
  "level": "error",
  "message": "cannot mount proc",
  "ring": 1,
  "serviceContext": {
    "service": "workspacekit",
    "version": ""
  },
  "severity": "ERROR",
  "time": "2021-09-10T04:42:05Z"
}
```

### Steps to reproduce

1. Deploy Gitpod on self-hosted k8s cluster
2. Launch new workspace

### Expected behavior

Workspace successfully launches

### Example repository

n/a

### Anything else?

Gitpod v0.10.0
RKE 1.20.10 (using `cri-containerd` and not `dockershim`)
containerd 1.4.9 (installed via Docker CE 20.10.7)
Red Hat Enterprise Linux 8.3

NOTE: Docker CE is installed, but the RKE kubelet is configured to use containerd, bypassing Docker. This gets past the `ring0` problem described in https://github.com/gitpod-io/gitpod/issues/3909

**Comment by jgallucci32** [comment]
This might be caused by the same issue with runc 1.0.1 fixed in PR https://github.com/gitpod-io/gitpod/pull/5139.

**Comment by jgallucci32** [comment]
Still getting the same error message with `0.10.0-nightly`. The iws.go module is still throwing the error "cannot mount proc". The PR mentioned above only fixes the notification from the workspacekit, but ws-daemon is still throwing an error in this case.

**Comment by jgallucci32** [comment]
The offending line of code is here https://github.com/gitpod-io/gitpod/blob/f496a745a08e9b8a2be23d8c0b5a326af09b69bc/components/ws-daemon/nsinsider/main.go#L286

Per the Linux manuals, the syscall `open_tree()` required Linux kernel version 5.2 or greater. This means CentOS and older Ubuntu distros will be unsupported for Gitpod.
https://man7.org/linux/man-pages/man2/syscalls.2.html

**Comment by aledbf** [comment]
> This means CentOS and older Ubuntu distros will be unsupported for Gitpod.

Yes, this is documented https://www.gitpod.io/docs/self-hosted/latest/requirements#minimum-kubernetes-requirements
Also, keep in mind components as `agent-smith` uses eBPF (one of the reasons for the kernel version)

**Comment by jgallucci32** [comment]
@aledbf Thanks for theinfo. What besides the `SYS_OPEN_TREE` system call is driving the newer kernel requirements?

**Comment by aledbf** [comment]
two things are user namespace support for FUSE > v4.18 and OverlayFS > v3.18

@csweichel ping for additional info

**Comment by ghuntley** [comment]
> two things are user namespace support for FUSE > v4.18 and OverlayFS > v3.18

Added to https://github.com/gitpod-io/website/pull/955

**Comment by aledbf** [comment]
@ghuntley not sure that is necessary. Requiring a kernel >  v5.4 is enough.

**Comment by jgallucci32** [comment]
After upgrading from RHEL 8.3 to Ubuntu 20.04 (with no other changes to components) the workspaces now launch successfully. This confirms later version of Gitpod will not run on RHEL 8 and you must have at least Kernel 5.2 to operate.

/close
