### ISSUE TITLE
respect maintainers rights to push to PRs from forks

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#565]
GitHub allows maintainers to push to a PR from a fork by default. It is possible via terminal in Gitpod but one gets unnecessary notification.

<img width="1212" alt="Screen Shot 2019-05-10 at 08 43 01" src="https://user-images.githubusercontent.com/3082655/57507643-a7442a00-72ff-11e9-83b5-94d38c566c26.png">

**Comment by AlexTugarev** [comment]
@akosyakov, isn't it same as https://github.com/gitpod-io/gitpod/issues/413?

**Comment by akosyakov** [comment]
@AlexTugarev indeed
