### ISSUE TITLE
Prevent navigation when using backwards/forwards mouse buttons

### ISSUE THREAD

**Issue by ThomasOrlita** [gitpod-io/gitpod#5657]
### Bug description

In VS Code you can navigate through cursor history using `alt+left` and `alt+right`. The same behaviour is possible with Button 4 and Button 5 on mouses that support it.
In GitPod, the editor navigates correctly after the mouse button presses, but then Chrome immediately navigates the page away.

### Steps to reproduce

Press mouse button 4 or 5 to navigate through code

### Expected behavior

Chrome navigates the page away instead

### Anything else?

Relevant: https://community.gitpod.io/t/feature-request-support-mouses-4th-and-5th-button/4841

Temporary fix by preventing page navigation (this also disables navigation UI buttons): https://stackoverflow.com/a/34337617/4227998

**Comment by akosyakov** [comment]
I think you need to raise this issue in the upstream: https://github.com/microsoft/vscode

**Comment by ThomasOrlita** [comment]
Please reopen, this is still a bug
