### ISSUE TITLE
Text of definitions overlap

### ISSUE THREAD

**Issue by JonasRech** [gitpod-io/gitpod#567]
**Describe the bug**
The definition of a method, in this case e.g: Map overlaps the container, also the referenced graphic which belongs to the definition seems not to be loaded correctly (see screenshot)

**To Reproduce**
- Auto Import a method e.g. Map (rxjs)
- The definition of this method is displayed

**Expected behavior**
The definition should be scrollable in the provided black container (see screenshot), and all referenced graphics should be loaded correctly.

![image](https://user-images.githubusercontent.com/20480449/57573785-dce73100-742d-11e9-94c6-1043a1744e97.png)

**Comment by svenefftinge** [comment]
Can you provide an example project with which I can reproduce it?

**Comment by svenefftinge** [comment]
Ok, was able to reproduce with https://github.com/Brooooooklyn/learning-rxjs

**Comment by JonasRech** [comment]
Okay, great to hear you were able to reproduce it, in a way ;)
Sorry I was late in answering.
