### ISSUE TITLE
Create email unsubscribe link for onboarding emails

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#5672]
The unsubscribe link is necessary for users to unsubscribe from emails with a single click. This is required according to GDPR. We already have email unsubscribe links for DevX and Changelog. And we'd need another link for the onboarding email. When clicking on the unsubscribe link the notification preferences need to be updated and the updates need to be forwarded to customer.io.

The format would be something like this:
` https://gitpod.io/api/unsubscribe?email=christin@gitpod.io&type=onboarding` 

cc @laushinka

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5672#issuecomment-917966892):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
