### ISSUE TITLE
Handle / fix failing `git stash` in `prebuild.go`

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#5675]
### Bug description

There are cases where content initializer for prebuilds fails during `git stash` here:

https://github.com/gitpod-io/gitpod/blob/6e5b4c719b396e0affd4e9ca7f09700398c6b6be/components/content-service/pkg/initializer/prebuild.go#L96

For example this error (see how to reproduce below):
```
git stash push -u failed (exit status 1): error: invalid path 'dependencies/nng/'\nerror: dependencies/nng/: cannot add to the index - missing --add option?
fatal: Unable to process path dependencies/nng/
Cannot save the untracked files
```

This seems to be related: https://github.com/gitpod-io/gitpod/issues/4203#issuecomment-838801174

Workspace starts just fail and the user sees:

```
cannot initialize workspace: cannot initialize workspace: content initializer failed
```

We need to fix the error and think about how to improve the error message for the user.

### Steps to reproduce

Open this commit in Gitpod: https://github.com/MontiCore/montithings/commit/38e9b9b8351fd66d9de8586d96c6ebc5f8571dfa

**Comment by roboquat** [comment]
@csweichel: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5675#issuecomment-918916766):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5675#issuecomment-918917137):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by princerachit** [comment]
I manually reproduced the issue:
```
gitpod /workspace/montithings/dependencies $ git stash push -u
error: invalid path 'dependencies/nng/'
error: dependencies/nng/: cannot add to the index - missing --add option?
fatal: Unable to process path dependencies/nng/
Cannot save the untracked files
```

Upon inspecting the path it complained about I can see that the git repo nng is corrupted. This is the reason why we see above error, hence failure during prebuilds

```
gitpod /workspace/montithings/dependencies/nng $ git status
error: wrong index v2 file size in .git/objects/pack/pack-26ba023501f250b7100eaa5f390402524b7bc900.idx
error: wrong index v2 file size in .git/objects/pack/pack-26ba023501f250b7100eaa5f390402524b7bc900.idx
error: wrong index v2 file size in .git/objects/pack/pack-26ba023501f250b7100eaa5f390402524b7bc900.idx
error: wrong index v2 file size in .git/objects/pack/pack-26ba023501f250b7100eaa5f390402524b7bc900.idx
error: wrong index v2 file size in .git/objects/pack/pack-26ba023501f250b7100eaa5f390402524b7bc900.idx
error: wrong index v2 file size in .git/objects/pack/pack-26ba023501f250b7100eaa5f390402524b7bc900.idx
fatal: bad object HEAD
```


Above indicates that the git repo `nng` is corrupted. We cannot add a corrupted git repo to index.

**Comment by rl-gitpod** [comment]
This is looking like an issue between git version 2.30.1 (the current base image version) and the newer version installed in the ./installLinux.sh. v2.33.0

If I remove the git version update it does not error.

I can repro it other workspaces by apt-get update git, then git cloning a repo and trying to stash it.

**Comment by princerachit** [comment]
Thanks @rl-gitpod . Can we possibly do anything about it? IIUC the gitpod users can choose their own image for prebuilds, right?

For the default base image that we provide, we can downgrade the git version to a stable one.
We should also open an issue with `git` about this. WDYT?

**Comment by rl-gitpod** [comment]
Still digging, but that is what I'm thinking/planning.

Will update as soon as I have something concrete.

**Comment by rl-gitpod** [comment]
It is due to [this change in git](https://github.com/git/git/commit/6e773527b6b03976cefbb0f9571bd40dd5995e6c#diff-70525b6b89c7cac91e520085d954a68671038d218b77d22855e938ab075a68d8L1006) around the [sparse-index](https://fossies.org/linux/git/Documentation/technical/sparse-index.txt) introduced in v2.31+

It still exists in the current master and I've reported it to the git mailing list.

**Comment by rl-gitpod** [comment]
See also [this in Slack](https://gitpod.slack.com/archives/C01RC164G48/p1632967704012900)
