### ISSUE TITLE
Timeout connecting to API on another port

### ISSUE THREAD

**Issue by HorizonShadow** [gitpod-io/gitpod#568]
**Describe the bug**
I have a client on port 3000 and an api on port 4000. Hitting the api from the server on 3000 times out.

**To Reproduce**
1. [Open this workspace](https://gitpod.io/#https://github.com/HorizonShadow/apollo-next-now-test)
2. `cd server && yarn install`
3. `cd ../client && yarn install`
4. ` npm run dev`
5. open a new terminal, and `cd server && npm start`

Open up your browser to port 3000 and it will load for awhile before timing out.

If you open up port 4000 in your browser, you'll see graphiql, so the port's definitely working.

**Expected behavior**
It shouldn't time out.

**Comment by svenefftinge** [comment]
I cannot reproduce what you described. 
I see the site below:

<img width="493" alt="Screenshot 2019-05-15 at 08 51 04" src="https://user-images.githubusercontent.com/372735/57754395-9c6a0a80-76ee-11e9-83d8-440b8d552b0c.png">

**Comment by HorizonShadow** [comment]
Interesting. I'm also no longer running into it. 

Must have been a fluke
