### ISSUE TITLE
ide deployment in blobserve and registry facade

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5681]
- [ ] blobserve needs to hot-reload its entire configuration
- [ ] registry-facade already does that

@csweichel I assume that blobserve's k8s resources can be completely moved to the IDE application on Argo CD. It seems to be mainly all about ide images and supervisor. What about registry facade?

**Comment by csweichel** [comment]
It's not that clear cut I'm afraid. We should talk through how we think the interfaces should look like
