### ISSUE TITLE
New Pricing Plan Proposal: Pay-As-You-Go

### ISSUE THREAD

**Issue by riyaadazad** [gitpod-io/gitpod#569]
Discovering Gitpod has been one of the best things that have ever happened to me in my developer journey. However, I was wondering if it would be a good idea to one day support a "Pay-As-You-Go" pricing plan, such as (maybe) $1 an hour so that if I were to go over my open source 100 hours for the month, I could pay $X to get X more hours (I've never actually gone over the 100 hours, but this is only a suggestion). I got inspiration for this idea from the pricing plans at [MacInCloud](https://portal.macincloud.com/select/#/plans). Thanks again for the GREAT service!!!

**Comment by sr229** [comment]
I believe this is a better pricing model than what we have in Gitpod today. +1
