### ISSUE TITLE
[self-hosted] Allow unlimited users in free tier

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5690]
The free version of Gitpod self-hosted is currently limited to 10 users. This however limits adoption and purpose to contribute to our open-source code-base. Instead, we should allow all features for up to 10 users and simply disable the enterprise features (prebuilds, admin dashboard, workspace snapshots and sharing, flexible timeouts) when the 11th user joined. Best of both worlds.

**Comment by kevinraymond** [comment]
This sounds like a sensible path to consider - would the enterprise features instantly be disabled? I'm thinking about the scenario where a team of 10 adds an 11th member and all enterprise features suddenly turn off, which could upset workflow if prebuilds and sharing are being used heavily. As long as there is a way to transition smoothly (e.g., obvious warnings when adding the 11th user or a short grace period) this could be a great way to expose the enterprise features.

The responsibility still lies with whoever is hosting Gitpod to plan accordingly based on intended usage. In my case, having more users without enterprise features is more important (though I 🧡 prebuilds!) so I can socialize Gitpod and have people learn to use it internally, before taking it to clients for the real sell.

Regarding users and tracking licenses -
* How is licensing enforced presently (if it is)?
* What would the trigger be for that 11th user?
* What defines a user exactly?

One more thing 😄 ... Meet _Client X_, a large org with many internal groups. Many times these internal groups do their own thing so say five of them want Gitpod but they all implement it differently, different budgets, etc. On the self-hosted licensing page it shows licenses are bound to the domain; how would that apply to _Client X_? Is it limited to one license for `gitpod.x.org` or is something like `gitpod.group.x.org` supported?

Thanks! This is really great stuff and I applaud the community interaction.

**Comment by asthomasdk** [comment]
I also think it would be good if there was an easy way of definig users in groups for a given Gitpod installation. is that what Teakms are for - or is that a different feature all together?

**Comment by jgallucci32** [comment]
The best way to handle the mixed use is to offer a free license key for enterprise features by registering for a 10-user license. This allows you to ship a community build which defaults to unlimited users with enterprise features disabled and no license key requirements. This avoids any situation involving adding an 11th user which could cause disruption and confusion.

The registration method for a 10-user license is a great way for Gitpod to engage with a potential client interested in enterprise features while allowing the open source community to engage on their own terms.

**Comment by svenefftinge** [comment]
> As long as there is a way to transition smoothly (e.g., obvious warnings when adding the 11th user or a short grace period) this could be a great way to expose the enterprise features.

I agree this needs to be smooth, we should probably put in a warning starting with the 8th user or so.

> How is licensing enforced presently (if it is)?

You obtain a key where the domain and number of seats are encrypted.

> What would the trigger be for that 11th user?
> What defines a user exactly?

Someone doing oauth with the self-hosted instance. I.e. at the moment we really just count the number of users in the DB.
Might make sense to go for active users per month eventually.

> I also think it would be good if there was an easy way of definig users in groups for a given Gitpod installation. is that what Teakms are for - or is that a different feature all together?

'Teams' allow you to group people together and have them manage their shared project. Managing mostly means configuration, prebuilds and then in future additional project-wide and team-wide settings and environment variables.

**Comment by jgallucci32** [comment]
What happens now with the current version (v.0.10.0) when the 11th user is added? Is this a soft (warning) or a hard (cannot login) type failure?

Currently on 0.6.0 which has been pretty stable for half a year and looking to upgrade to 0.10.0 which in addition to some instability might restrict use of the product after upgrade.

**Comment by JanKoehnlein** [comment]
We're currently a bit swamped. Please bring this up again in a week or so

**Comment by metcalfc** [comment]
Too keep things as simple as possible for the small teams self hosting and the would be evaluation teams; It makes a lot of sense to allow the features by default for up to ten users and then hard shut them off at 11. If you cross over at 11 and want those features then both sides agree there is value and its time to pay.

I think that displaying the path to 10 users clearly makes a lot of sense. No one wants to be surprised. A larger warning at 50% or 80% and a clear if you add this 11th user X, Y, Z things happen. If that is ok with you because the value you want is the free tier have at it. If the value you want is the enterprise and you need that 11th user right now, well its time to talk to sales who can help you with that.

There is never a good time to take value from someone. No one wants features shutoff. The way to get ahead of that is to be crystal clear with expectations up front. Tell people they are approaching the limit as they grow. Offer them low friction, no sales, methods to obtain self hosted licenses. Folks can't hang out over limits, it becomes impossible to deal with. Even with sales in the middle.

**Comment by jgallucci32** [comment]
One thing I think might help is to rebrand self-hosted into 2 editions, something like Gitpod Community Edition (CE) and Gitpod Enterprise Edition (EE)? This might help clarify the AGPL binaries are the core product, without enterprise features, and for unlimited users. Then for Gitpod EE you get 10 users free, pay after the 11th user.

**Comment by Seenox** [comment]
On the verge of [changes](https://www.docker.com/blog/updating-product-subscriptions/) in Docker Desktop subscription model, a lot of companies are currently actively looking for a good, solid and even better replacement for their developers. I believe this a great time for GitPod to offer unlimited users in free tier with limited functionalities and by doing that, they will of course win a lot of paying customers soon. It's all about marketing! ;)

**Comment by jgallucci32** [comment]
The PR https://github.com/gitpod-io/website/pull/1218 will clarify the Open Source "Community Edition" which is unlimited users and no enterprise features and the "Free Tier" which has enterprise features and limited to 10 users. Once the PR is updated this ticket should be able to be closed as there are two separate editions. Asking for unlimited users AND enterprise features for Free isn't something which makes sense after this change.

**Comment by Merith-TK** [comment]
Any updates on this whole subject?
I am curious what the final verdict is as of this moment, as I personally am a fan of free teir having unlimited users, but enterprise features disabled.

**Comment by jgallucci32** [comment]
I just realized https://github.com/gitpod-io/website/pull/1218 was not linked to this issue. The PR has been merged and changes are now live at https://www.gitpod.io/self-hosted

The PR clarifies the Community Edition of Gitpod as being free, unlimited users, open source, and without enterprise features. The Enterprise Edition is still free for up to 10 users.
