### ISSUE TITLE
.gitpod.yml tasks not running

### ISSUE THREAD

**Issue by Kronifer** [gitpod-io/gitpod#5699]
### Bug description

Literally just the title. The workspace is created but the tasks in .gitpod.yml aren't run

### Steps to reproduce

Just create a new workspace.

### Example repository

github.com/kronifer/sir-lancebot/tree/gitpod

**Comment by akosyakov** [comment]
Indeed there is no task terminal while .gitpod.yml is valid.

**Comment by akosyakov** [comment]
On staging env I see following in logs:
```
cannot parse tasks:
    github.com/gitpod-io/gitpod/supervisor/pkg/supervisor.WorkspaceConfig.getGitpodTasks
        github.com/gitpod-io/gitpod/supervisor/pkg/supervisor/config.go:331
  - json: cannot unmarshal bool into Go struct field TaskConfig.env of type string
```

**Comment by akosyakov** [comment]
@Kronifer try: `PIP_USER: "false"` as a workaround

**Comment by akosyakov** [comment]
Now the local app is failing for me because I have a workspace with bogus envars when it tries to call `getWorkspaces`:
```
time="2021-09-15T09:36:06+02:00" level=warning msg="cannot get workspaces" error="json: cannot unmarshal bool into Go struct field TaskConfig.workspace.config.tasks.env of type string"
```

**Comment by roboquat** [comment]
@akosyakov: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5699#issuecomment-919804865):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
