### ISSUE TITLE
[Go] Consider opening Go projects on the actual project

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#57]
Currently, we open go projects on the `/workspace` folder. The idea was, that then you can easily browse all the dependencies. 
As a user that is not so familiar it is hard to find the actual project I was interested in.
Once we have multi-roots we could open the third party projects as secondary roots. 

Would be great to hear from Go users how they think about it.

**Comment by svenefftinge** [comment]
@32leaves @JanKoehnlein WDYT?

**Comment by svenefftinge** [comment]
Having worked on a couple of go projects I strongly prefer changing how go projects are opened, so I see the same as on Github in the navigator.

**Comment by meysholdt** [comment]
👍 for seeing the same in the Navigator View as on GitHub. Also I would very much like it if the Current Working Directory of new Terminals would be initialised to the git-repos root folder. This is prerequisite for the command that are usually listed in project's README to work.
