### ISSUE TITLE
[ws-manager-bridge] Logs DEADLOCK

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#5701]
Needs further investigation.

Source: https://console.cloud.google.com/errors/CIPaw6rG2q23mgE?service=ws-manager-bridge&time=P30D&project=gitpod-191109&folder&organizationId&supportedpurview=project

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5701#issuecomment-920945497):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
This seems to be caused by two "update d_b_workspace_instance" calls racing each other: we're not using locks/transactions on DB tables explicitly.

Innodb executes all singular statements insides transparent transaction. If those statements require to update the same row the "deadlock" message is thrown (cmp. [docs](https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks-handling.html), esp.: `InnoDB uses automatic row-level locking. You can get deadlocks even in the case of transactions that just insert or delete a single row. That is because these operations are not really “atomic”; they automatically set locks on the (possibly several) index records of the row inserted or deleted.`)

Example:
 - [log line](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-09-19T08:32:31.533Z;query=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22ws-manager-bridge%22%0AjsonPayload.context.instanceId%3D%22d88ce328-e9ad-4b9c-9e84-5fde17b2e42d%22%0Atimestamp%3D%222021-09-19T08:32:31.533Z%22%0AinsertId%3D%22aj0ypx8nlx8orfg4%22;timeRange=P5D?folder=true&organizationId=true&project=gitpod-191109)
 - instanceId: `d88ce328-e9ad-4b9c-9e84-5fde17b2e42d`
 - [bridge logs](https://cloudlogging.app.goo.gl/Eg2KuC5CGjDaQHor6)
 - [server logs](https://cloudlogging.app.goo.gl/GiWaWhCMVFYrwTBm6)

Observations:
 - there are no two places where two tasks should write to the same instance concurrently
 - bridges `handleStatusUpdate` is explicitly ordered, for instance
 - the log seems to be emitted [here](https://github.com/gitpod-io/gitpod/blob/b031cf3296931f383c60c47bcb6fa53557861bd1/components/ws-manager-bridge/src/bridge.ts#L108) (note that `context.instanceId` is set, but message from error)
 - the two timestamps related to the last write in `server` ([here](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-09-19T08:33:20.468Z;pinnedLogId=2021-09-19T08:32:31.533Z%2Faj0ypx8nlx8orfg4;query=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22server%22%0A%22d88ce328-e9ad-4b9c-9e84-5fde17b2e42d%22%0Atimestamp%3D%222021-09-19T08:32:31.425Z%22%0AinsertId%3D%224ryi9w5f6skunj6v%22;summaryFields=jsonPayload%252Fpayload%252Fid:false:32:beginning;timeRange=P5D?folder=true&organizationId=true&project=gitpod-191109), cmp. [source](https://github.com/gitpod-io/gitpod/blob/20be95b116d16222fb6602c5ef65954121245c74/components/server/src/workspace/workspace-starter.ts#L176-L187)) and the first write in `bridge` ([log](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-09-19T08:32:31.533Z;query=resource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22ws-manager-bridge%22%0AjsonPayload.context.instanceId%3D%22d88ce328-e9ad-4b9c-9e84-5fde17b2e42d%22%0Atimestamp%3D%222021-09-19T08:32:31.533Z%22%0AinsertId%3D%22aj0ypx8nlx8orfg4%22;timeRange=P5D?folder=true&organizationId=true&project=gitpod-191109)) are _very_ close together:
    - server: `2021-09-19 10:32:31.425 CEST`
    - bridge: `2021-09-19 10:32:31.533 CEST`

If there's sth that makes the DB slow the execution of the 1st statement might drag along into the execution of the other, leading to the deadlock.

It seems there is no immediate issue here. In theory we could loose data, but we don't because we always get multiple events on workspace startup.
