### ISSUE TITLE
Workspace stuck on "Building image" upon opening

### ISSUE THREAD

**Issue by bravoalpha79** [gitpod-io/gitpod#5703]
### Bug description

Trying to open an existing workspace, the workspace hangs in "Building image" state indefinitely.

Sample affected workspaces:
- https://gitpod.io/start/#crimson-tahr-4aem9tho
- https://gitpod.io/start/#aquamarine-urial-ux3oh178

Note: the issue appears to be random (or selective), as some workspaces opened without issues, e.g.: https://chocolate-salamander-7mfmle79.ws-eu16.gitpod.io/

### Steps to reproduce

From Gitpod Dashboard, try to open an existing workspace.

Result:

![image](https://user-images.githubusercontent.com/45522344/133404896-9a5ec813-d7a5-4a0f-bf42-b21c531e9eec.png)

### Expected behavior

Workspace builds and loads without delay or hanging.

**Comment by AmyOShea** [comment]
https://gitpod.io/start/#tan-reptile-pak1u3u8

Same issue

**Comment by daisygunn** [comment]
https://teal-cardinal-3kcfmnn2.ws-eu16.gitpod.io/ also having the same issue

**Comment by Joan-Amudu** [comment]
https://gitpod.io/start/#copper-fox-4ccmlt50 

same issue

**Comment by Franciskadtt** [comment]
My workspace is also stuck on "building image". https://gitpod.io/start/#tomato-sloth-tmnqobb5

**Comment by MaggieDaisy** [comment]
https://gitpod.io/start/#tan-gayal-yxzxw2ez      hi there, having the same issue

**Comment by Eva-Kuk** [comment]
Hi, I'm having the same issue https://gitpod.io/start/#violet-platypus-6zaw7721

**Comment by vinnieOrdobas** [comment]
HI, I'm having the same issue https://gitpod.io/start/#green-chicken-oed2sbr1

**Comment by ghuntley** [comment]
Hello 👋 everyone in this thread; we have heard you and can confirm that we are experiencing service interruptions currently related to deployment. An incident has been called and our best folks are investigating. Unfortunately, it appears the problem is related to the meta-cluster which spans across our deployments which makes rollback/mitigation trickier. Please accept our apologies and follow along at https://www.gitpodstatus.com/ for updates.

**Comment by ghuntley** [comment]
We have seen multiple issues and believe to have mitigated the one reported in this thread. I would love to hear back from @vinnieOrdobas, @Eva-Kuk, @MaggieDaisy, @Franciskadtt, @Joan-Amudu @daisygunn, @AmyOShea and @bravoalpha79 if you are still experiencing issues.

I’m hanging out over in www.gitpod.in/chat in the #build-in-the-open room if you wish to chat. I would love to see you there.

**Comment by ghuntley** [comment]
The incident has progressed to a [status of monitoring](https://www.gitpodstatus.com/incidents/63jf08vzf3nz). If you are still experiencing service issues please open a new GitHub issue. Thank-you for your patience and apologies for the outage. We have identified areas in our telemetry/tracing that need improvement and you’ll see pull-requests landing on trunk shortly.
