### ISSUE TITLE
Make lldb debug work to debug with cpp and rust

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#5705]
Repo: https://github.com/gengjiawen/node-debug
Gitpod: https://gitpod.io/#https://github.com/gengjiawen/node-debug

debug config:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "lldb",
            "initCommands":["settings set target.disable-aslr false"],
            "request": "launch",
            "name": "Debug",
            "program": "node",
            "args": ["hello.js"],
            "cwd": "${workspaceFolder}"
        }
    ]
}
```

Current status: not working
```console
'A' packet returned an error: 8
```

Working container config: `    "runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined" ],` https://github.com/gengjiawen/node-debug/blob/f1aaeea4aed61a037f28397aa11d907525ce35fc/.devcontainer/devcontainer.json#L13

I think fixing `vscode-lldb` on gitpods will bring debug native language (c, cpp, rust) to the next level.

Related: 
* https://github.com/gitpod-io/gitpod/issues/1331
* https://github.com/gitpod-io/gitpod/issues/544

**Comment by gengjiawen** [comment]
not stale

**Comment by sagor999** [comment]
@Furisto is this support with our runtime config? and if not, is this a complex task or an easy fix?

**Comment by Furisto** [comment]
@sagor999 Hard to say honestly. It looks we already tried to enable it, but it is obviously not working. We have to look into which layer in our stack causes the problem.

**Comment by sagor999** [comment]
@kylos101 added it to our inbox

**Comment by david-bakin** [comment]
@axonasif - any chance to mark this "never stale"?

**Comment by aledbf** [comment]
@gengjiawen please try again. Check the workspace lands in us60 or eu60.

**Comment by gengjiawen** [comment]
> @gengjiawen please try again. Check the workspace lands in us60 or eu60.

 the breakpoint not working on my side.

**Comment by gengjiawen** [comment]
Second try works, not sure why ?
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/3759816/184050806-0d78b083-df5a-4f7d-9392-b3a9e07c29d2.png">

**Comment by aledbf** [comment]
> the breakpoint not working on my side.

I cannot reproduce that behavior. That said, the `codelldb` process uses 100% of the CPU, and after ~15s the breakpoint is reached.

**Comment by gengjiawen** [comment]
I can't reproduce the bug. Thx for the great work.

**Comment by jenting** [comment]
Move the status to Done.

**Comment by kasperk81** [comment]
> 'A' packet returned an error: 8

still getting the same error in terminal. what is needed to make lldb work in gitlab terminal?

> Gitpod: https://gitpod.io/#https://github.com/gengjiawen/node-debug

ran `sudo apt install lldb` then `lldb ls` (or `lldb  node` or any binary you wish to run under debugger) and then `run` in lldb's repl:
```gdb
Current executable set to 'ls' (x86_64).
(lldb) run
error: process launch failed: 'A' packet returned an error: 8
```

otoh, gdb just works in the same terminal: `gdb ls` and `run` in its repl.
