### ISSUE TITLE
Logs: Log entries related content initialiser should be findable when searching for a workspace

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5706]
When searching for the log entries that explain why content init failed, they can be not found when searching for workspace name or ID.

**Comment by meysholdt** [comment]
[example log entry](https://console.cloud.google.com/logs/query;query=insertId%3D%22n81rhh2gq5tjlp8q%22;timeRange=PT1H;pinnedLogId=2021-09-15T09:51:17Z%2Finqgrrh1e7sz8dr2;cursorTimestamp=2021-09-15T09:51:16Z?project=gitpod-191109)

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5706#issuecomment-919913891):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
