### ISSUE TITLE
[image-builder-api] Enable client-side gRPC metrics for interacting with image-builder

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5707]
Implemented in TypeScript and Golang.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5707#issuecomment-919917399):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by JanKoehnlein** [comment]
Closed by #5726
