### ISSUE TITLE
Feedback Issue: VS Code Desktop Support 💬

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5712]
### Objective

The aim of this issue is to gather feedback on the **VS Code Desktop Support** feature to be released in September 2021. Any feedback is welcome! See [relevant docs](https://www.gitpod.io/docs/develop/vscode-desktop-support). 🔖 

### Background

The upcoming **VS Code Desktop Support** feature aims to enable software developers to use familiar local tools like [VS Code](https://code.visualstudio.com/) to work with Gitpod workspaces via SSH instead of switching to Web IDE running in browser.

See relevant roadmap items[[1](https://github.com/gitpod-io/roadmap/issues/11)][[2](https://github.com/gitpod-io/roadmap/issues/19)]. 🗺️

See also [`component: local companion app`](https://github.com/gitpod-io/gitpod/labels/component%3A%20local%20app) label and [relevant project](https://github.com/gitpod-io/gitpod/projects/4) in the issue tracker. 🍁 

Cc @akosyakov @svenefftinge @csweichel @JohannesLandgraf

### Feedback

Any feedback is welcome but we're primarily looking for the following types of feedback:

1. How could this new feature be improved? 💡 
2. What didn’t work as you expected it to? 💭 
3. What do you like best about this new feature? 🧡 

Feel free to send in any comments, thoughts, emojis, screenshots, or screencasts as well as open any new separate issues with a concrete [problem statement](https://en.wikipedia.org/wiki/Problem_statement#:~:text=A%20problem%20statement%20is%20a,of%20a%20process%20or%20product.) for further discussion. 💬

**Comment by cloudsbird** [comment]
Feedback:
1.  Isn't it better to open workspace in the dashboard so we don't need to wait till the gitpod workspaces is loaded in browser. So, we  just need to wait in VSCode Desktop
2. Inside of VSCode, will you allow to manage the workspace inside VSCode Desktop? for example I have workspaces pinned in the Gitpod Dashboard and I only open my VSCode and bam I open pinned workspaces!

anyway Nice Features!!!

**Comment by akosyakov** [comment]
> Isn't it better to open workspace in the dashboard so we don't need to wait till the gitpod workspaces is loaded in browser. So, we just need to wait in VSCode Desktop

Please follow https://github.com/gitpod-io/gitpod/issues/5641. We are targeting mid October to bring it.

> Inside of VSCode, will you allow to manage the workspace inside VSCode Desktop? for example I have workspaces pinned in the Gitpod Dashboard and I only need to open my VSCode. I see the pinned workspaces, and click it, it will load the workspaces

Could you file an issue? It makes sense but we decided against it because of time constraints for now.

> For the people who live pretty far from the Gitpod Server (SEA region). It makes the experiences better So the delay I do in terminal is still acceptable

Actually it is the same. It is just in the web version we disable the local echo by default, because it break docker run. You can still enable it: https://code.visualstudio.com/updates/v1_51#_local-echo But be aware that even in VS Code Desktop you may be need to disable local echo if you want to use docker.

**Comment by axonasif** [comment]
I'm waiting for the aarch64 build of `local-companion-app` binary for being able to use it on my ARM device.
Or would it be possible to use if I mange to compile https://github.com/gitpod-io/gitpod/tree/main/components/local-app for my CPU architecture?

I also created an [issue](https://github.com/gitpod-io/gitpod/issues/5320).
Thanks, waiting for it eagerly.

**Comment by axonasif** [comment]
Update:
So I was able to cross-compile `local-companion-app` component for aarch64(arm) directly from Gitpod itself and it works!
![2021-09-23-103539_1598x720_scrot](https://user-images.githubusercontent.com/39482679/134455942-d8e43542-5e16-4b8a-beb8-2b618ff8bfc1.png)

Although I'm a bit confused after reading [this page of Gitpod documentation](https://www.gitpod.io/docs/develop/vscode-desktop-support).
Is `local-companion-app` and `Open in VS Code` the same thing?

I also installed `Gitpod Remote Support` extension in my local VSCODE but whenever I click on `Open in VS Code` from Gitpod, it ends up like below:
![2021-09-23-102456_1598x720_scrot](https://user-images.githubusercontent.com/39482679/134455916-1420f7ce-ec9c-4c5b-ae22-21c3fa2379c6.png)
Note: On left I'm using `Remote - SSH` extension to connect via SSH with `/tmp/gitpod_ssh_config`(`local-companion-app`) which works but timeouts if I don't keep the browser window open for long. And the right VSCODE window was spawned by `Open in VS Code button` but something seems wrong.

**Comment by akosyakov** [comment]
> Is local-companion-app and Open in VS Code the same thing?

`Open in VS Code` brings own version of the local companion, it does not use own which is configured by a user. You don't need manually install the local companion when you are using VS Code Desktop, but it can still be used standalone for other use cases like for VIM users.

> So I was able to cross-compile local-companion-app component for aarch64(arm) directly from Gitpod itself and it works!
Please file an issue to support such architecture as well that VS Code Desktop downloads the proper version.

For now there is a setting `gitpod.installationPath` which you can point to your version of the local companion. Drawback that you need to maintain it yourself. VS Code Desktop auto updates the local companion otherwise.

**Comment by axonasif** [comment]
> `Open in VS Code` brings own version of the local companion, it does not use own which is configured by a user. You don't need manually install the local companion when you are using VS Code Desktop, but it can still be used standalone for other use cases like for VIM users.

Hi @akosyakov, thanks for clarifying it.



> Please file an issue to support such architecture as well that VS Code Desktop downloads the proper version!

I just bumped a pre-existing issue https://github.com/gitpod-io/gitpod/issues/5320#issuecomment-925557804



> For now there is a setting `gitpod.installationPath` which you can point to your version of the local companion.

I am unable to find this settings on my VSCODE. Also another odd thing is that there are two identical extensions available in the marketplace, which feels confusing.

![2021-09-23-131536_1598x720_scrot](https://user-images.githubusercontent.com/39482679/134468158-7c0e8003-4239-49de-9208-b56b25a0408e.png)

**Comment by akosyakov** [comment]
> I am unable to find this settings on my VSCODE. Also another odd thing is that there are two identical extensions available in the marketplace, which feels confusing.

This setting is not public, just open json file and add it.

One extension is running in your local VS Code to open SSH window, another is running in Gitpod workpsace to integrate with Gitpod tasks and so on. Do you think we can do something to clarify it? You actually does not need to install them, VS Code will do it for you at proper timing.

**Comment by axonasif** [comment]
> This setting is not public, open user settings json file and add it.

Got it.

> One extension is running in your local VS Code to open SSH window, another is running in Gitpod workpsace to integrate with Gitpod tasks and so on. Do you think we can do something to clarify it? You actually does not need to install them, VS Code will do it for you at proper timing.

Oh, these weren't automatically installed. I'm not sure, could be a issue on my side.

**Comment by akosyakov** [comment]
> Oh, these weren't automatically installed. I'm not sure, could be a issue on my side.

Did you do `Open in VS Code` from web version? VS Code Desktop should ask you then do you want to install Gitpod extension?

**Comment by axonasif** [comment]
> Did you do `Open in VS Code` from web version?

I did. I use Gitpod from Firefox. After clicking on the button a new empty file with some encoded gitpod.io url in the file-name opens up on my VSCODE.

Please take a look at the VSCODE window on right-side of this screenshot. For the left window I had to manually run `local-companion-app` and then connect via `Remote - SSH` extension in VSCODE.

![2021-09-23-102456_1598x720_scrot.png](https://user-images.githubusercontent.com/39482679/134472085-495411b1-50a9-4655-93ee-ce243cef3df7.png)

**Comment by akosyakov** [comment]
> I did. I use Gitpod from Firefox. A new empty file opens up with some encoded gitpod.io url in the file-name after clicking on Open in VS Code from Gitpod WEB IDE.

It looks wrong, maybe vscode URI system handler does not work on arch linux :(

**Comment by axonasif** [comment]
Okay so I finally made the `Open in VS Code` button to work on my ARM device. `--open-url` parameter was missing in my `vscode` installation `$HOME/.local/share/applications/code-url-handler.desktop`file. I also had to specify a custom path for `local-app` since this is an ARM device. Thanks to @akosyakov for providing me a tip above!

One thing I should mention is that I had to use `Open in VS Code` button twice for the **first time**(When `Gitpod-Desktop` extension is not installed locally in VS Code Desktop) to actually let the `Gitpod` extension establish a connection to my target workspace.

## Feedback
I think it would be awesome if the `Gitpod-Desktop` extension had an actual GUI front-end for managing everything gitpod **directly from VSCODE**. So that we don't have to rely on an external browser. I see that @cloudsbird already suggested something similar and this is pretty much the same idea.

**Comment by loujaybee** [comment]
I have temporarily unpinned to put up [the JetBrains issue](https://github.com/gitpod-io/gitpod/issues/6576), we'll get this issue back pinned following the JetBrains beta.

**Comment by vavdoshka** [comment]
please help, I got the "Open in VS Code" stuck on VS Code desktop side.

```
[11/8/2021, 11:19:03 PM] fetching the local app from https://gitpod.io/static/bin/gitpod-local-companion-darwin
[11/8/2021, 11:19:03 PM] starting the local app with the config: {
  "gitpodHost": "https://gitpod.io",
  "configFile": "file:///var/folders/__/k19xrs456tgdsyjp_4w35tcc0000gn/T/gitpod_ssh_config-7750-xDAoFHD0ziUu",
  "apiPort": 61686
}
[11/8/2021, 11:19:03 PM] the local app has been stared: {
  "pid": 10505,
  "log": "file:///var/folders/__/k19xrs456tgdsyjp_4w35tcc0000gn/T/gitpod-local-companion-7745-JXFKLIpiSsxx.log"
}
[11/8/2021, 11:19:03 PM] released lock: gitpod.io
[11/8/2021, 11:19:04 PM] the local app (pid: 10505) is running, but the api endpoint is not ready: Error: Response closed without headers
[11/8/2021, 11:19:04 PM] retying again after 1s delay...
[11/8/2021, 11:19:05 PM] the local app (pid: 10505) is running, but the api endpoint is not ready: Error: Response closed without headers

...this repeats until timeout
```

**Comment by akosyakov** [comment]
@vavdoshka Could you try to close VS Code and kill all processes with gitpod in name and they try again? If it does not help please collect logs and send them to anton@gitpod.io. Thank you.

**Comment by vavdoshka** [comment]
@akosyakov 
I've wiped out VS Code and installed the latest Version: 1.62.1 (Universal), also killed the companion process and removed gitpod.io key from keychain.
Then tried "Open in VS Code" it prompted to install extension and authenticated to Gitpod after and still same issue.
Also I tired with standard full-worksapce image, same issue.

I have gathered the logs and did send them to anton@gitpod.io .
What I found is that the configFile (ssh_config) is created empty, don't know if that lead to something.

**Comment by digiltd** [comment]
Loving the desktop support btw, the ability to use keyboard shortcuts to flick between browser and ide has saved my sanity, no more hunting through multiple tabs in multiple browser windows for me!

@vavdoshka I used to have this happen quite regularly, though it hasn't happened in a while. But to fix it I would open the ssh config, find the file in Finder, delete it and the other gitpod files in the folder, find the gitpod-companion app in Activity Monitor and kill it (not sure if this was required, but it wouldn't hurt). Then try to "open in VS Code" from the browser, and that would usually work.

![image](https://user-images.githubusercontent.com/5680968/141096389-09f7bd90-b0a3-40cc-9342-afbb628715ca.png)

![image](https://user-images.githubusercontent.com/5680968/141096414-066589bf-6295-4a21-a9f6-8e43c775c01a.png)

![image](https://user-images.githubusercontent.com/5680968/141096571-c3b251f7-4c16-4497-ac24-3bbfa492ea8c.png)

![image](https://user-images.githubusercontent.com/5680968/141096641-dddcd6ac-3be4-480d-a0fe-dae4099ed36b.png)

![T 2021-11-10 10-29-21](https://user-images.githubusercontent.com/5680968/141096940-29666d7d-7cf8-4cb0-b8d8-1933a1172ca1.png)


![T 2021-11-10 10-30-42](https://user-images.githubusercontent.com/5680968/141097108-152799be-08f6-4313-bd17-34ee0e7a9cb1.png)

**Comment by vavdoshka** [comment]
@digiltd

thank you for you help, unfortunately this did not work out for me, the "ssh_config" files created are just being empty on my side, nothing changes..

When I did a first pass on GitPod evaluation this Desktop Support worked well for me and I even used to it already and it is really hard to switch to browser due to that reason you mentioned already about dancing with the tabs, as well as I found that not all required extensions are supported in browser version, plus some console applications (like [k9s](https://github.com/derailed/k9s)) just feels really slow in browser.

@akosyakov please advice what could be the options to fix this

**Comment by vavdoshka** [comment]
oh I think I have some improvement after I allowed VSCode to "run software lcoally that does not meet system's security polciy"

<img width="780" alt="image" src="https://user-images.githubusercontent.com/11683992/155393675-4d6377cb-4b77-4ae9-bf9d-78b388980002.png">

to have "Developer tools" in Security & Privacy -> Privacy

```shell
sudo spctl developer-mode enable-terminal
````

the change helped after reboot

**Comment by mlvzk** [comment]
It would be nice if it was possible to open a new workspace in VS Code Desktop without opening the web VS Code.
I also get an error when I open the workspace in desktop VS Code Desktop too soon, I get a connection error (I think to ssh) and I have to click Retry.
