### ISSUE TITLE
[code] enable local echo

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5715]
We disabled local echo becuase it breaks output of docker exec. But we seen many complaints about bad perceived performance in terminals. So instead we enable it again and document in docs how to troubleshoot docker exec.

**Comment by akosyakov** [comment]
In the supervisor we also can figure out when a user going to use docker first time and notify VS Code about that it checks user settings and suggest to disable local echo. @svenefftinge wdyt?

**Comment by svenefftinge** [comment]
I have no data or feel on how big this problem actually is. Does it always break terminal output when running docker?

**Comment by akosyakov** [comment]
> I have no data or feel on how big this problem actually is. Does it always break terminal output when running docker?

Yes, I think it breaks any `docker run/exec`: https://github.com/microsoft/vscode/issues/110232

**Comment by jeanp413** [comment]
We tested this today with @akosyakov and we couldn't reproduce, so I'll make a PR enabling this by default.

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/5750
