### ISSUE TITLE
[dashboard/server] broken condition ensureWorkspaceAuth on start

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#5718]
The following screenshot shows how often the `auth/workspace-cookies` resource is fetched on workspace starts. 

The `ensureWorkspaceAuth` seems to have a [condition](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/start/StartWorkspace.tsx#L197) for fetching this, but it's broken because the cooke isn't accessible from JS (`httpOnly`)

⚠️  Each fetch of this resource causes `findByInstanceId` and `findInstanceById` to be executed. 

<img width="1502" alt="Screen Shot 2021-09-16 at 09 58 39" src="https://user-images.githubusercontent.com/914497/133574093-f8730e1f-eca7-41de-8114-46b1e1ff60b8.png">

cc. @csweichel

**Comment by csweichel** [comment]
Great find @AlexTugarev - we'll have a look

/team workspace

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5718#issuecomment-921919514):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by aledbf** [comment]
@AlexTugarev I think an easy fix to this situation is to add an additional route in server and instead of checking the cookie, send a request and do the check there, returning ok or error.
