### ISSUE TITLE
Use swot-js for checking student e-mail

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#572]
We should use https://github.com/theotow/swot-js in order to check if a person is applicable for the student's plan.

**Comment by geropl** [comment]
> You don't know if the email address belongs to a student, faculty, staff member, alumni, or a contractor.
> There may be a few false positives, missing institutions... maybe even a couple of typos. Contributions welcome!

Looks fine. I would `or` that with our DB. This way it'd stay easy to test stuff.

**Comment by geropl** [comment]
Has been deployed months ago.
