### ISSUE TITLE
update to VS Code 1.60.2 to cherry pick recovery fixes

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#5734]
### Bug description

Choosing 'Latest VSCode' (in preferences) - breaks debugging with VSCode

![image](https://user-images.githubusercontent.com/22901/133756350-ec70986b-ff0e-410a-aa70-402b4529bb13.png)

### Steps to reproduce

1. Go to https://gitpod.io/preferences
1. Under "Default IDE", choose 'VS Code - LATEST' option
1. Open any repo that can be debugged in VSCode, ie. https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node
1. Press Ctrl+C to break/stop the current process.
1. Open `src/app.ts` file
1. Add a breakpoint in line 38
1. Open `Run & Debug` panel
1. Choose `Jest Current File`
1. Press the green "Play" button

Instead of VSCode debugging of the breakpoint, you'll see this -
![image](https://user-images.githubusercontent.com/22901/133756470-30782e35-d8cb-4fb9-8a87-0811103b2969.png)

### Expected behavior

Being able to use VSCode debug as usual (can be done only if you **_don't_** choose VSCode Latest in the steps above)
When debugging does work as expected, it should look like this -
![image](https://user-images.githubusercontent.com/22901/133759565-9ebe90c4-52d7-482d-a709-7837c936cec2.png)

### Example repository

https://gitpod.io/#https://github.com/gitpod-io/template-typescript-node

**Comment by akosyakov** [comment]
@jeanp413 We need to fix it before aligning stable with latest. Could you have a look please?

**Comment by akosyakov** [comment]
It actually just bite me so I'm looking into it.

**Comment by akosyakov** [comment]
It is broken in the upstream. It will be part of VS Code 1.60.2: https://github.com/microsoft/vscode/milestone/165 So we should update once more before updating the latest.
