### ISSUE TITLE
License pertinent information on the Admin console 

### ISSUE THREAD

**Issue by iamulya** [gitpod-io/gitpod#5743]
Currently on the admin console, an admin can only see user related information. It would be necessary, especially for the self-hosted variant, to have license pertinent information as well, for e.g. license no., type of license, #seats available under license, #seats currently unused etc. Those would be the "mvp features" that the enterprise world is quite used to. 

As an extension of this feature - It would be great to be able to do an analysis through time, for e.g. how the license usage has changed over time, active users, roles etc. You can use the screenshot below as reference:

![image](https://user-images.githubusercontent.com/12005812/133818971-750e9e17-2437-4f41-9cc1-00940ef79b1c.png)

The mvp features are really important and would be critical for wider enterprise adoption - the analysis through time would be the cherry on top.

**Comment by gtsiolis** [comment]
Closing in favor of https://github.com/gitpod-io/gitpod/issues/8413 which contains more relevant information and it's already part of the 🏡 self hosted board[[1](https://github.com/orgs/gitpod-io/projects/22)]. See also https://github.com/gitpod-io/gitpod/issues/8413#issuecomment-1048903394. Feel free to reopen if needed. Cc @corneliusludmann

**Comment by corneliusludmann** [comment]
Thanks for always being around to clean up, @gtsiolis! :rocket: :+1: :partying_face:
