### ISSUE TITLE
Error: No Python Language Server Installed 

### ISSUE THREAD

**Issue by ivelin** [gitpod-io/gitpod#5746]
### Bug description

It is not clear which if any python language server works with gitpod at this time.

The Python extension available in the Gitpod marketplace suggests it comes with Pylance. However when a gitpot workspace launches it complaints that there is no Pylance installed. 

1. Accepting the Install option does not lead to any actual installs. If there is an install error, it does not manifest in the UI. The next time the workspace launches the same pylance error dialog comes up.
2. Accepting the Jedi option also does not seem to do anything. After accepting it, the Jedi settings are empty and restarting the Python Language Server leads to an error. 

Guidelines from Gitpod on installing a Python Language Server would be helpful.

See supporting screenshots below.

There is also a related [community discussion](https://community.gitpod.io/t/how-can-i-install-pylance/1574) .

![Screen Shot 2021-09-17 at 12 47 54 PM](https://user-images.githubusercontent.com/2234901/133832868-8c6df535-76d9-4ad1-8840-6a20b4b8195f.png)
![Screen Shot 2021-09-17 at 12 39 28 PM](https://user-images.githubusercontent.com/2234901/133832869-76f8bc49-263c-40ba-bc82-7a0ed5ecf43d.png)
![Screen Shot 2021-09-17 at 12 37 36 PM](https://user-images.githubusercontent.com/2234901/133832870-82428669-b429-4432-99b9-b9b338eedc7e.png)

### Steps to reproduce

Install Python extension and restart gitpod workspace.

### Expected behavior

Some Python Language Server should work. 

### Example repository

https://gitpod.io/#https://github.com/ivelin/ambianic-edge/tree/fork-master

**Comment by akosyakov** [comment]
Pylance is proprietary and cannot be installed in Gitpod. Jedi should work, at least I cannot reproduce issues in our example repo: https://github.com/gitpod-io/template-python-django

You can use VS Code Desktop btw to make use of Pylance: https://www.gitpod.io/docs/develop/vscode-desktop-support

**Comment by ivelin** [comment]
Thank you for the clarification. We are using a custom image based on `gitpod/workspace-full`
https://github.com/ambianic/ambianic-edge/blob/master/.gitpod.Dockerfile

**Comment by jefer94** [comment]
Not exists one way to install Pylance too? the Jedi language server is very bad and ends with many issues for the Junior developers, should be great can install Pylance or set the vscode version inside the docker image as insider for add the extension in `.gitpod.yml`
