### ISSUE TITLE
Support devcontainer.json as an alternative to .gitpod.yml

### ISSUE THREAD

**Issue by akaFTS** [gitpod-io/gitpod#5747]
Since both VSCode Development Containers and GitHub Codespaces are using devcontainer.json as their lingua franca for configuring images and extensions, it would be great if Gitpod could also adopt it so that we don't need to duplicate those settings in two different configuration files.

**Comment by shism2** [comment]
Good idea

**Comment by svenefftinge** [comment]
See also https://github.com/gitpod-io/roadmap/issues/16

**Comment by akaFTS** [comment]
Closing this issue since @svenefftinge's is pretty much exactly the same.
