### ISSUE TITLE
[ws-manager-bridge] Export status update received metric

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5754]
Such a metric is a good indicator for a broken connection to the workspace cluster. We would do well to establish an alert on this metric: if the rate drops to zero that's a problem, and we'll want an alert in addition to forcefully restart the bridge.

related: #5753

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5754#issuecomment-922232315):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
