### ISSUE TITLE
[cli] Open browser

### ISSUE THREAD

**Issue by domdomegg** [gitpod-io/gitpod#5759]
Similar to the `gp preview <url>` command, it'd be useful to have a `gp browser <url>` command that would open a new browser tab.

This would be similar to the `open-preview`/`open-browser` values possible for the `ports[n].onOpen` configuration in .gitpod.yml.

Use case: I am building a React app. I want to wait until the dev server is running before opening the browser (rather than just when the port opens, as otherwise the user is told the server is not yet running). When it is running, I want something to call to open the dev server in a browser tab, similar to `open-browser`.

Current alternative: Use the `open-browser` configuration for `ports[n].onOpen`. However, this results in displaying the page 'Port X Not Found, Please make sure this port is exposed and your application is up and running.' to be displayed as at the time the port is opened the server isn't yet running. Users have to wait a bit then refresh this page for it to work.

**Comment by akosyakov** [comment]
`preview $url --external` - previews URL with system wide URL opener
