### ISSUE TITLE
Gitpod API

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#576]
An API for creating and starting workspaces that allows to provide the required data.

We can allow a GET and POST interface as well as JSON/YAML sitting somewhere on the internet (e.g. a gist).

The information provided should allow to tell
 - standard meta data: name, description, etc.
 - initial workspace content: git, zip, etc. (possibly contained base64 encoded)
 - initial `.gitpod.yml`configuration

It would be great if I can ask the user to provide some of the data during start (especially the name).

Easy way to author a GET URL using a web form, where a user can provide all the data and get a link generated, that can then be put elsewhere.

This would generally allow others to find new ways of using Gitpod we'd especially would like supporting easily starting new projects based on boilerplates and cli wizards.

**Comment by XinYaanZyoy** [comment]
would this API be helpful in following;

POST to gitpod API to run certain CLI commands and the result url of that output (which is served on certain port, so gitpod url of port) sent back as response!

## e.g;
>
>POST
>gitpod API this json { RUN jupyter notebook [--options] [subcommands]}
>
>200
>{porturl_localhost_8888}
>
>now user can just iframe this url!

it'd be useful for project [Xbooks](https://github.com/xsoft-technologies/Xbooks)

**Comment by svenefftinge** [comment]
We have a CLI that does that. https://www.gitpod.io/docs/34_command_line_interface/#url
Try :
```sh
gp url 8888
````
Does that solve your use case?

**Comment by XinYaanZyoy** [comment]
i meant without landing on gitpod, how do i run,

> `gp url 8888`

using some POST request, the 200 res shoulld be the actual url where 'gp url 8888' lands!

so in short, i can run jupyter notebooks (live) on gitpod, but the url given by gp url, will now be used as a iframe!

security  problem?

**Comment by svenefftinge** [comment]
I don't quite understand why people would know your workspace URL but not the port-url?
If we were putting something like that in an API, the client would still need to be authenticated and provide the workspace id for which it wants to retrieve the URL. That still would be inconvenient enough, right?

**Comment by XinYaanZyoy** [comment]
let me elaborate...

- i'd like to have a button on my website, this website, however, is full of static jupyter notebooks hosted on github.com.
- when my reader clicks on this button, the reader would see that the static notebook is now has become "LIVE"!

i thought, if there's gitpod API to create a workspace on gitpod using user's Github credentials, i then just need to get a url of port 8888 (on which jupyter notebook by default runs) and set that url as an iframe source!


apologize, but am i being relevant to Gitpod API, or am i lacking my knowledge?

i know (but don't know how) we could solve this problem using binder, inteeract, docker and so on.

first priority here being that "the LIVE notebook should be an iframe or object but not new tab" and reader should be able to send PR for changes! (so pushing back to author's repo)

plus, to do this on docker, i need server; which i don't have, if i do by binder there's security problem(or at least i don't know  how to solve), now my question was, "can(or will i be able to) i iframe $(gp url 8000)"
this way?

> would this API be helpful in following;
> 
> POST to gitpod API to run certain CLI commands and the result url of that output (which is served on certain port, so gitpod url of port) sent back as response!
> 
> ## e.g;
> > POST
> > gitpod API this json { RUN jupyter notebook [--options] [subcommands]}
> > 200
> > {porturl_localhost_8888}
> > now user can just iframe this url!
> 
> it'd be useful for project [Xbooks](https://github.com/xsoft-technologies/Xbooks)

**Comment by bitsnaps** [comment]
How about something like:
```
gp login -u gitpod -p
gp build -t alpine-remote:1 --from=workspace-full /.
gp run -it bash alpine-remote:1
gp ps -a
gp rmi alpine-remote:1
```
Well, you don't need to re-created docker... this will save tons of developer's resources, reusable layers..., processes...,  and allows many automation processes to be done interactively without messing with UI and js, browser's philosophy...
The`gp` is the `gitpod-cli` under your localhost!

**Comment by Davidffry** [comment]
I agree with you, I would like to have a cli-tools or an API endpoint outside the gitpod var.
I would automating update the envs vars for exemple.
