### ISSUE TITLE
[ws-manager] Maintains stale connections to ws-daemon

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5763]
### Bug description

ws-manager might maintain connections to endpoints which are no longer valid/available, because it doesn't re-validate that connections in its pool. This causes stray error messages and memory leaks.

### Steps to reproduce

not sure

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5763#issuecomment-922667390):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
