### ISSUE TITLE
[dev] Fix broken integration test execution on staging

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#5764]
We regularly executed integration tests but those are broken at the moment. This effort is meant to fix this for staging.

This might also include grouping the existing tests by what kind of cluster (full/workspace) they can be executed against.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5764#issuecomment-922702746):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
This is already been worked on: https://github.com/gitpod-io/gitpod/pull/5572
