### ISSUE TITLE
smart install extension 

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#5765]
Latest jest-runner only support 1.60.

Currently is 1.59, maybe we can automatically install supported version for vs 1.59 instead of popup an install error.

https://github.com/firsttris/vscode-jest-runner

### Current gitpod behavior

![image](https://user-images.githubusercontent.com/3759816/133971093-086a8412-7bd4-4b88-bd00-fd103207f6b4.png)

### local vscode(1.58) install proper version
![image](https://user-images.githubusercontent.com/3759816/133970813-644a1d5a-1b46-4667-9d5e-1cc091da5ba5.png)

**Comment by akosyakov** [comment]
If there is a compatible version with 1.59 in Open VSX it would be already installed automatically.

**Comment by gengjiawen** [comment]
> If there is a compatible version with 1.59 in Open VSX it would be already installed automatically.

I am afraid it's not current behavior, I have to manually specific the version, see https://github.com/gengjiawen/crawler-toolbox/blob/0ad0dbdbb8930a945a3c0c6bc730e2e58b25b7a1/.gitpod.yml#L13.

Otherwise the install will fail as the pic show.

**Comment by akosyakov** [comment]
> I am afraid it's not current behavior, I have to manually specific the version, see https://github.com/gengjiawen/crawler-toolbox/blob/0ad0dbdbb8930a945a3c0c6bc730e2e58b25b7a1/.gitpod.yml#L13.

Most likely the extension is not published properly to Open VSX, i.e. metadata don't have proper engine or something like that. Someone can debug and try to understand what is missing, but I don't think it makes sense since we are targeting to bring 1.60 for everybody this week anyway.

**Comment by gengjiawen** [comment]
> > I am afraid it's not current behavior, I have to manually specific the version, see [gengjiawen/crawler-toolbox@`0ad0dbd`/.gitpod.yml#L13](https://github.com/gengjiawen/crawler-toolbox/blob/0ad0dbdbb8930a945a3c0c6bc730e2e58b25b7a1/.gitpod.yml#L13).
> 
> Most likely the extension is not published properly to Open VSX, i.e. metadata don't have proper engine or something like that. 

Not likely: https://github.com/firsttris/vscode-jest-runner/blob/41a2a1e2b4a700b9832d49738dd2c767745038ef/package.json#L15

> Someone can debug and try to understand what is missing, but I don't think it makes sense since we are targeting to bring 1.60 for everybody this week anyway.

I am not saying this extension. But this default install feature has flaws when find plugin matching with current vscode.

**Comment by akosyakov** [comment]
> I am not saying this extension. But this default install feature has flaws when find plugin matching with current vscode.

It is the same code which is used in VS Code Desktop which is used by all installations. We don't have any special handling in Gitpod.

**Comment by gengjiawen** [comment]
not stale

**Comment by gengjiawen** [comment]
not stale

**Comment by loujaybee** [comment]
@filiptronicek could you take a look into this one?

**Comment by filiptronicek** [comment]
Hey @gengjiawen, so sorry for the delay here. I think the issue here could be as well because of Gitpod not being on the latest web version of VS Code, which should no longer be. I've tried installing the [firsttris/vscode-jest-runner](https://github.com/firsttris/vscode-jest-runner) extension today and it seems to work just fine. Could you try again please?
