### ISSUE TITLE
No logs when visiting a running prebuild

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5770]
Reproduce:
 - start prebuild
 - go to prebuild page and follow logs
 - at a later point (during uploading image) reload page and see that there are no logs.

**Comment by geropl** [comment]
> at a later point (during uploading image) reload page and see that there are no logs.

During upload of the backup you mean? We should have the log uploaded by then, and also serve it. Sounds a bit like a broken re-try or sth.

Could also be a consequence of https://github.com/gitpod-io/gitpod/pull/5688: I noticed that this caused some prebuilds to not properly upload logs and backups.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5770#issuecomment-924744164):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
I'm having a hard time reproducing this.

What could indeed be improved is the status indicator on the "View Prebuild" view: It shows "Running/Prebuild in progress..." when the pod is not even deployed.

**Comment by geropl** [comment]
Now it seems we found a case where the `supervisor` api won't respond while the pod is running, not allowing to list the available streams and thus preventing the logs from being shown, until the prebuild is done (when we are presented the offline logs).

**Comment by geropl** [comment]
Created https://github.com/gitpod-io/gitpod/issues/5904 ("Distinguish between prebuild "Running" and "Preparing"")

**Comment by geropl** [comment]
new hint: could incremental prebuilds be involved?
