### ISSUE TITLE
Rerunning Prebuild does nothing

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5771]
When clicking "Rerun Prebuild" on a branch (or "retrigger" on prebuild list the action name should be the same as on branches I think) nothing seam to happen.
<img width="1125" alt="Screenshot 2021-09-20 at 15 59 15" src="https://user-images.githubusercontent.com/372735/134015540-1c1d0057-3b7d-4ae4-b960-a3843c03c210.png">

**Comment by jankeromnes** [comment]
Happy to take a look at this after https://github.com/gitpod-io/gitpod/issues/5374 and https://github.com/gitpod-io/gitpod/issues/5612 (but not assigning myself right now in order to limit work-in-progress -- please feel free to take this issue if you want it 😊)

**Comment by bigint** [comment]
Can normal users able to see this option in gitpod.io?

**Comment by JanKoehnlein** [comment]
@bigint We are currently rolling out this feature to selected users for beta testing. Are you interested?

**Comment by bigint** [comment]
> @bigint We are currently rolling out this feature to selected users for beta testing. Are you interested?

Of course why not 😄 I DMd my Gitpod email do your Discord

**Comment by jankeromnes** [comment]
@bigint you can enable this new Teams & Projects UI by visiting `/new`, and then create teams & add projects 😁 notes:
- Some features are still a bit rough / may not work properly. If anything looks off, please report 😊🙏
- The new Teams are unrelated to the current Team Plans (i.e. you can create and manage them totally independently -- we're thinking about migrating legacy Team Plans to the new Teams & Projects UI, but this will happen much later)

**Comment by bigint** [comment]
Thanks @jankeromnes 

The first bug 😄 

![image](https://user-images.githubusercontent.com/69431456/134500738-71d4c6b4-9ca7-4318-983a-44c39144a684.png)

**Comment by bigint** [comment]
Created a new issue for this https://github.com/gitpod-io/gitpod/issues/5833
