### ISSUE TITLE
Prebuilds order is not stable

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5772]
Go to https://gitpod-staging.com/t/gitpod-io/gitpod/prebuilds
and see how the prebuilds are orderd by triggertime desc. Now go into the details of one prebuild and click on the project again (on the top). The prebuilds are now not sorted anymore.
<img width="1181" alt="Screenshot 2021-09-20 at 16 53 15" src="https://user-images.githubusercontent.com/372735/134023789-07c369c0-21f9-4326-99e0-69d31f86fcad.png">

**Comment by jankeromnes** [comment]
Should be fixed in https://github.com/gitpod-io/gitpod/pull/5809
