### ISSUE TITLE
Is not letting me open any workspace

### ISSUE THREAD

**Issue by tommygonzaleza** [gitpod-io/gitpod#5773]
### Bug description

When I try to open any workspace, this is showing up: 
![image](https://user-images.githubusercontent.com/56565994/134035831-13ce40c2-31f6-4dd5-abab-179b1566ca0e.png)

### Steps to reproduce

Go to workspaces, and click on the name to open it.

Or trying to opening them from github with the extension

### Expected behavior

Open the workspace

### Example repository

https://github.com/4GeeksAcademy/About-4Geeks-Academy

**Comment by jankeromnes** [comment]
Hi @tommygonzaleza! Thank you for reporting this problem.

We're currently investigating an incident in the US cluster (workspaces not starting, increasing failure rate): https://www.gitpodstatus.com/

This is likely related, and we're working on resolving this as soon as possible. Sorry for the disruption.

**Comment by jankeromnes** [comment]
We've identified and fixed a problem, and US service is recovering. We're continuing to monitor the situation, but Gitpod should now basically work again in the US.

**Comment by jankeromnes** [comment]
Incident resolved :) https://www.gitpodstatus.com/incidents/zvzg25zpw4g9 thanks again for the report!
