### ISSUE TITLE
Add a method to forward a specific port to local app api

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#5778]
When opening a workspace with Jetbrains IDEs, we will need to establish an SSH connection and forward the IDE backend port. Currently, the only options would be to:
1. Use the local app to auto-tunnel all ports of the workspace. Not ideal as the IDE will also port forward after the connection is established showing random ports to the users.
2. Implement port forwarding in the local IDE plugin. Not ideal as we would duplicate the logic and split the responsibility of establishing and managing the connection.

**Comment by atduarte** [comment]
We have another related issue. As the IDE backend port will be internal, the local app is incapable of tunneling it (see[ internal discussion](https://gitpod.slack.com/archives/C02CBKZEVS8/p1632226236132700?thread_ts=1632213062.126900&cid=C02CBKZEVS8)).

The plan is to proceed with https://github.com/gitpod-io/gitpod/issues/5642 first.

/cc @akosyakov

**Comment by akosyakov** [comment]
We need to verify it yet, but it seems that Gateway provides APIs capable to forward ports including of a tcp join link. We should use the local companion to establish a SSH tunnel to a workspace and then provide Gateway with SSH credentials and a tcp join link. I put the design here: https://www.notion.so/gitpod/JetBrains-server-to-client-flow-09a1262189054a21bcf7761ab0c54a64#5c5e814e4d68481d94d3dddd4f00fe68

**Comment by akosyakov** [comment]
Confirmed, managed to build a prototype with manually started local companion and tpc join link.

**Comment by akosyakov** [comment]
We don't use lcoal app for desktop IDEs integrations anymore but SSH gateway.
