### ISSUE TITLE
Accidental Git Folder Deletion

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#578]
Hi! We experienced an issue where someone was working with a gitpod project and accidentally closed their browser after removing the .git folder, but before setting to a new repository.

Is there a way to access a gitpod instance that does not contain a .git?

**Comment by svenefftinge** [comment]
Yes, of course. You can go to your dashboard https://gitpod.io/workspaces and start the respective workspace again.

**Comment by ColbyWTaylor** [comment]
Thank you @svenefftinge - unfortunately when we tried to start, it failed (the gitpod logo turns red and it returns to the available work spaces)- are there related items you know of that might keep it from starting correctly?

**Comment by svenefftinge** [comment]
Oh, that's a bug. Sorry, we are working on it.

**Comment by svenefftinge** [comment]
Was closed because we have merged the fix to master. Reopen because it was not yet deployed :)

**Comment by jferragut** [comment]
@svenefftinge Similar issue, we have students that are working on a file and gitpod blanks out entire files in the project. Deleting the content of the file but not the file itself. Is this related to the current issue or should I open a new issue?

**Comment by jferragut** [comment]
@svenefftinge actually, I just reread the original and see that they accidentally deleted it. I will create a new issue tracking for this.
