### ISSUE TITLE
[configurator] Show latest default branch prebuild

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5782]
When I go to the configurator, it should show me the logs of the latest prebuild. 
Currently it shows:
<img width="1130" alt="Screenshot 2021-09-21 at 12 41 44" src="https://user-images.githubusercontent.com/372735/134157213-61a4b558-73c4-4d20-9252-f29a9d9c96c3.png">

although there has been a recent prebuild.

**Comment by jldec** [comment]
This would be moot if logs were moved out of the configuration page - see #5785
