### ISSUE TITLE
Unable to change the side bar location.

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#579]
**Describe the bug**

I'm trying to change the Location of the sidebar but its not working 
**To Reproduce**

I have popped this line into User settings.json
`    "workbench.sideBar.location": "right",
`
**Expected behavior**

Its working perfectly in VS Code.

**Comment by Otoru** [comment]
I'm having the same difficulty.

**Comment by akosyakov** [comment]
Theia does not support such settings, since there are always 2 side-bars. You can drag and drop views which you need from one to another.

Alternatively you can switch to VS Code: https://www.gitpod.io/docs/feature-preview/#default-ide

**Comment by Otoru** [comment]
<div align="center">
<p>
"You can drag and drop views which you need from one to another"
</p>
<img src="https://media.tenor.com/images/1c44ea89efe8f2bfe44e6a0d3bf8051f/tenor.gif" />
</div>

Tanks @akosyakov !!!!

Can you tell me if I have an item layout as standard for all my workspaces?

When I change what to display or not in the IDE or where each item should be, it is saved in the workspace and I don't know how to make it fixed for all projects
