### ISSUE TITLE
Provide URL of workspace as environment variable

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#58]
request from [here](
https://twitter.com/mattstratton/status/1037009464396734465):
> it would be super rad if I could get the URL of the gitpod workspace as an environment value; my application needs to take what the base URL will be as an argument to start up (in this case, localhost won't work since that won't work from the outside).

**Comment by 32leaves** [comment]
for this particular case beware that the workspace URL is not the same as the URL on which the user's service will be served. The latter will have a `port-` prepended.

**Comment by pawlean** [comment]
Replying to the PR here

**Comment by pawlean** [comment]
testing reply<br>
