### ISSUE TITLE
Emmet is not working in JSX

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#580]
**Describe the bug**

Emmet is not working in JSX
**To Reproduce**

I have added this line in User settings.json
`"emmet.includeLanguages": {
    "javascript": "javascriptreact",
  }`

When i type div and hit tab nothing happens its working fine in HTML files

**Comment by jankeromnes** [comment]
Thanks for reporting this bug @nisarhassan12!

I invoke @akosyakov ✨
