### ISSUE TITLE
Inclusion of the Tomorrow Night Bright extension

### ISSUE THREAD

**Issue by gbraad** [gitpod-io/gitpod#5807]
Would it be possible to allow the use of

  * https://marketplace.visualstudio.com/items?itemName=ms-vscode.Theme-TomorrowKit

At the moment there is a Tomorrow Night Blue theme that does not do it for me ...

Note: [ref 1](https://twitter.com/gbraad/status/1435497212201504774), [ref 2](https://twitter.com/gbraad/status/1392374386062155776)

**Comment by akosyakov** [comment]
License looks good, but since it is MS i don't expect them publishing to Open VSX. You can file an issue and PR here to auto publish with service account: https://github.com/open-vsx/publish-extensions

cc @jankeromnes

**Comment by akosyakov** [comment]
> Note: ref 1, ref 2

Yeah, twitter is not the best support channel.

**Comment by gbraad** [comment]
> Yeah, twitter is not the best support channel.

It was a question ;-)

Will see what I can do to et this... so wondering how the blue theme got there.

**Comment by gbraad** [comment]
It seems the repository https://github.com/microsoft/vscode-themes/ is a shared one, and https://github.com/microsoft/vscode-themes/tree/main/tomorrow is specific for the packaging of the Tomorrow Theme. Not sure about the format:

https://github.com/gbraad/open-vsx-publish-extensions/commit/08f7f6f5c05032beecb1f3f24bc8925d9bea2e7e

```diff
+    },
+    {
+      "id": "ms-vscode.Theme-TomorrowKit",
+      "repository": "https://github.com/microsoft/vscode-themes/",
+      "location": "tomorrow"
```

**Comment by gbraad** [comment]
https://github.com/open-vsx/publish-extensions/pull/445
