### ISSUE TITLE
Support ports lower than 1024

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#581]
Currently, this gives an error message similar to "permission denied".

Allowing port 80, for example, would allow to use images of Apache, Nginx, PHP-Apache in their default configs.

**Comment by meysholdt** [comment]
Steps to reproduce:

1. open gitpod.io/#https://github.com/gitpod-io/nginx-example
2. `/nginx/nginx.conf`, change `listen 0.0.0.0:8080;` to `listen 0.0.0.0:80;`
3. run `nginx -s stop`
4. run `nginx -c $(pwd)/nginx/nginx.conf`

see output 
```
$ nginx -c $(pwd)/nginx/nginx.conf
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```

**Comment by geropl** [comment]
We do grant `CAP_NET_BIND_SERVICE` to workspaces. But maybe those webservers also need `CAP_NET_ADMIN`..
[Linux capabilities](http://man7.org/linux/man-pages/man7/capabilities.7.html)
