### ISSUE TITLE
Enable (or unblock) Web APIs for interacting with devices such as WebUSB, Web Serial & Web Bluetooth

### ISSUE THREAD

**Issue by beriberikix** [gitpod-io/gitpod#5814]
Hello! We're in the hardware/IoT space and for our use case we need to interact with physical devices on a users machine for programming & debugging. One straightforward approach is to leverage W3C APIs for [WebUSB](https://wicg.github.io/webusb/), [Web Serial](https://wicg.github.io/serial/) & [Web Bluetooth](https://webbluetoothcg.github.io/web-bluetooth/) that are currently available in Chromium-based browser. As I understand it, VSCode by default blocks these APIs even if the browser supports them (see microsoft/vscode#116761.) So if 116761 is correct, the request is to allow the appropriate permissions on the iFrame.

I originally posted this gitpod-io/gitpod#3463 but @csweichel suggested that this would be a better place to raise it :)

An alternative we're considering is creating a desktop agent like the Local Companion but using the browser APIs would be preferred for performance reasons.

/cc @0grit @alvarowolfx

**Comment by akosyakov** [comment]
We could try to contribute to VS Code to resolve it. Adding to prod inbox to decide.

**Comment by 0Grit** [comment]
https://github.com/microsoft/vscode/pull/117786

**Comment by akosyakov** [comment]
/schedule 

We agreed to try to move https://github.com/microsoft/vscode/pull/117786 forward.

**Comment by roboquat** [comment]
@akosyakov: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5814#issuecomment-925614000):

>/schedule 
>
>We agreed to try to move https://github.com/microsoft/vscode/pull/117786 forward.


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
Unfortunately after team discussions we realised that we don't have capacity for upstream issues and have to focus more on bug fixes and robust deployments. I removed it from the scheduled for now.

**Comment by 0Grit** [comment]
Totally get it.

**Comment by akosyakov** [comment]
I tend to close it, since there is a work around and it is upstream issue.

**Comment by beriberikix** [comment]
VSCode recently introduced a way to allow WebUSB from webviews - see https://github.com/microsoft/vscode/pull/152310 & https://github.com/thegecko/webusb-web-extension. Does this carry through to Gitpod as well?

**Comment by LeoDog896** [comment]
I'm trying to connect a camera to gitpod for a robot project -- having these types of APIs exposed can really help!
