### ISSUE TITLE
Gitpod not working properly in the US

### ISSUE THREAD

**Issue by Moritz-Hoeppner** [gitpod-io/gitpod#5816]
### Bug description

This morning I could not start any workspaces in gitpod. I am accessing from the US. 
Now the extension store seems to be down.
![image](https://user-images.githubusercontent.com/43564759/134384940-a292046a-5731-41cd-b696-bbe9740bc9c6.png)

### Steps to reproduce

Open a workspace from the US.

**Comment by piniondevs** [comment]
Yeah same thing happened to me too.

**Comment by tahlilma** [comment]
I actually made opened the same issue a few months ago which you can read right here.
[https://github.com/gitpod-io/gitpod/issues/4600](url)
Last time it fixed itself and hopefully that happens this time too.

**Comment by meysholdt** [comment]
Thank you for bringing this up and apologies for the trouble. The issue has also been reported here: https://github.com/gitpod-io/gitpod/issues/5817

**Comment by Moritz-Hoeppner** [comment]
Everything works again. Thank you. Greeting from Nordakademie :)
