### ISSUE TITLE
Gitpod prebuilds don't support `gp preview` in `init`

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#582]
**Describe the bug**
When you have a `gp preview <url>` in your `init` step, it should open a preview pane with the requested URL.

But when it's a prebuilt workspace, the preview pane doesn't open.

**To Reproduce**
Have `gp preview` in your `init` task + prebuilds enabled, like [this repo](https://github.com/jankeromnes/edgedb).

**Expected behavior**
I think the preview should always open, even if it was opened in `init`.

You can work around this bug by calling `gp preview <url>` in the `command` step instead.

**Comment by svenefftinge** [comment]
I think we should tell users that it doesn't make sense to put IDE dependent tasks into init.
