### ISSUE TITLE
archlinux support for containers

### ISSUE THREAD

**Issue by Merith-TK** [gitpod-io/gitpod#5821]
I have been trying to get gitpod to launch a archlinux base container
https://github.com/Merith-TK/gitpod-workspace
And have had *somewhat* sucess outside of errors such as `/etc/pacman.conf` not actually existing, yet existing at the same time for some weird reason, along with `alpm` failing to load.

Do note, this container starts just fine when using docker build so I have zero clue wtf the gitpod layer is doing to break it

**Comment by carlosal1015** [comment]
Hi @Merith-TK, maybe you will be interested to look this pull request.

Since I do no see the logs, I suspect that is related with [this solution](https://github.com/the-ashh/build-arch-action/blob/master/Dockerfile#L6).

**Comment by carlosal1015** [comment]
Hi @Merith-TK, right now is building succesfully https://github.com/Merith-TK/gitpod-workspace
Consider closing the issue.

**Comment by Merith-TK** [comment]
oh neat, thanks!
