### ISSUE TITLE
[proxy] Disable debug logging for OpenVSX cache proxy

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#5823]
Currently, the logging of the OpenVSX cache proxy in production is pretty loud. It's good to have this in production for some weeks to make sure the proxy works as expected but in the long term, we should remove the debug logs.

I would propose we keep the logs until Oct 29th and remove them afterward.

**Comment by akosyakov** [comment]
@corneliusludmann Is it still something actionable or it is invalid since we have a new proxy now?
