### ISSUE TITLE
Fix HTTP metrics in "server" dashboard

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5825]
Our metric endpoint gitpod_server_http_requests_total should not export the "query" part of the URL inside the route label, because it leads to too many different values for the "route" label and break the HTTP metrics in the "server" dashboard.

See https://github.com/gitpod-io/observability/issues/260 for details and examples.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5825#issuecomment-925621588):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
