### ISSUE TITLE
Enable XFS for preview envs

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5826]
Just like we have it in prod already. 

This is needed to implement https://github.com/gitpod-io/gitpod/issues/4938.

**Comment by meysholdt** [comment]
Q: fastest way to kick this off? 

Proposal: 
* add a new node pool to the `code-dev` cluster that has the same localSSD configuration the workspace-pool in staging and prod.
* in values.yaml, [set `setupSSDRaid: true` for `wsDaemon`](https://github.com/gitpod-io/ops/blob/771d9029598feebb66cc2805a5287c9f0857d62a/charts/gitpod_io/values.ws-cluster.yaml#L33)
* tweak the Werft job to get your preview envs onto the new pool: https://github.com/gitpod-io/gitpod/blob/main/.werft/build.ts#L446

Considerations:
* I assume that `setupSSDRaid` will work even if multiple gitpod installations run on the same nodes: The ws-daemon will create the raid+xfs and the other ws-Daemons will find+use it.
* adding a new node pool leaves existing node pools workspace-0 and workspace-1 intact and therefore does not impact existing preview envs. We can phase out those node pools later or keep them.

**Comment by wulfthimm** [comment]
That is the fastest way to implement a XFS in GKE although I am interested in going a bit deeper on how using XFS on top of an already ext4 formated disk.

**Comment by meysholdt** [comment]
@wulfthimm is there something left to do here?
