### ISSUE TITLE
`gp preview <url>` picks a too small / random width for the Preview pane

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#583]
**Describe the bug**
<img width="1552" alt="Screenshot 2019-05-22 at 09 52 34" src="https://user-images.githubusercontent.com/599268/58159905-b58a3280-7c7d-11e9-9a36-3554334f1e0b.png">
**To Reproduce**
1. Open any project in Gitpod
2. Run `gp preview <any url>`

**Expected behavior**

The preview pane should have a good width by default.

Also, if you run the same command multiple times, you'll notice that the width changes randomly.

**Comment by jankeromnes** [comment]
cc @svenefftinge

**Comment by svenefftinge** [comment]
Fixed in Theia.

**Comment by svenefftinge** [comment]
deployed
