### ISSUE TITLE
[Epic] Jetbrains Remote Development Support

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#5831]
Implementation epic of https://github.com/gitpod-io/roadmap/issues/20

## Plan

- [x] #5603 
- [x] #5643 
- [ ] clean up the backed plugin to rely on supervisor info endpoint, see https://github.com/gitpod-io/gitpod/pull/6152#discussion_r728641112
- [x] #5642 
- [ ] #5644 
- [x] #5641 
- [ ] #5778

**Comment by loujaybee** [comment]
We can now track this work as part of the IDE project board: https://github.com/orgs/gitpod-io/projects/13/views/1

So will close this epic 🙏  thanks @atduarte ! 🚀
