### ISSUE TITLE
Gitpod GitHub app error when configuring existing organization

### ISSUE THREAD

**Issue by shafy** [gitpod-io/gitpod#5834]
### Bug description

When configuring the [Gitpod GitHub app](https://github.com/apps/gitpod-io) with a profile or organization that already was given access to single repos before, the following error appears after clicking "Save".

"Request registerGithubApp failed with message: ER_DUP_ENTRY: Duplicate entry 'github-1234-claimed.user' for key 'PRIMARY'".

Despite this error, the app is correctly configured.

### Steps to reproduce

1. Go to the [Gitpod GitHub app](https://github.com/apps/gitpod-io)
2. Click "Configure"
3. Select your profile or an organization that already has min. one repo configured with the Gitpod app
4. Add a new repository
5. Click "Save"
6. Marvel at the error message

**Comment by gtsiolis** [comment]
Thanks, @shafy! Closing this as a duplicate of https://github.com/gitpod-io/gitpod/issues/6421 as it contains some more information. 📕
