### ISSUE TITLE
Unable to set the Default Editor in terminal from vim to nano

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#584]
**Describe the bug**

Unable to set the Default Editor in terminal from vim to nano
**To Reproduce**

On this page [https://gitpod.io/environment-variables/](url) I have added EDITOR with the value nano

**Comment by jankeromnes** [comment]
@nisarhassan12 Setting the `EDITOR` variable in https://gitpod.io/environment-variables/ is now supported! 🎉

**Comment by svenefftinge** [comment]
The fix/change is now deployed in production.
