### ISSUE TITLE
Extensions fail on latest VSCode

### ISSUE THREAD

**Issue by Decipher** [gitpod-io/gitpod#5845]
### Bug description

When using the Latest VS code, extensions fail to initialise, tasks fail to run and there are no source control plugins available.

![image](https://user-images.githubusercontent.com/161090/134602478-2f329be7-24d6-4718-9cd0-c63359f2c4dd.png)

### Steps to reproduce

1. https://gitpod.io/preferences
2. Set to Latest VS Code
3. Run a GitPod: https://gitpod.io/#github.com/druxt/druxt.js
4. Wait
5. See error

### Expected behavior

Tasks should run, extensions should be active, source control plugin should work

### Example repository

https://github.com/druxt/druxt.js

**Comment by shaal** [comment]
I noticed that today as well.
I don't think it was like that yesterday (not sure what changed)

**Comment by pawlean** [comment]
Yeah, we've been seeing this across the board (internally too) I think @akosyakov is looking into this right now.

**Comment by akosyakov** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/5824

**Comment by akosyakov** [comment]
It was resolved, please try again.
