### ISSUE TITLE
Add 'out-of-band' workspace backup

### ISSUE THREAD

**Issue by rl-gitpod** [gitpod-io/gitpod#5846]
## The original description
Following on from #5751 which assumes that most of the Gitpod infrastructure is running effectively we should have the ability to backup from outside that infra i.e. from the nodes directly in the unlikely event that the Gitpod infrastructure is in a poor state.

This is achievable using a script to `gcloud compute ssh/scp` to log onto each node, find the required workspace mount(s), tar-ing it/them, copying them from the node and using 'gsutil' to upload to the appropriate storage location.

## Is your feature request related to a problem? Please describe

We drafted scripts in [this incident](https://gitpod.slack.com/archives/C02T4QE5T3J) which:
1. Do the backup from a node
2. Do the backup upload from a Gitpod workspace (assuming you've SCP'd the backup, extracted it, and followed some other steps)
3. If the pods are running, after the backup is done, we'll need to remove the finalizer.
4. If the pods are not running, we must consider Force Stopping related workspaces via the DB (only if they are stuck in a Stopping state)
   * If the workspace is "stopped", this step is not necessary. [Related Notion page.](https://www.notion.so/gitpod/Mark-workspace-instance-as-stopped-in-the-DB-994a1d21e06c41378feff5c784b49674)

They are also referenced in [the issue to update the related runbook](https://github.com/gitpod-io/runbooks/issues/316).

## Describe the behaviour you'd like

Add the scripts from the incident to our [workspace clusters image](https://github.com/gitpod-io/gitpod-packer-gcp-image), and then update our runbook for [GitpodWorkspaceStuckOnStopping](https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodWorkspaceStuckOnStopping.md) so they can be easily referenced and used. It may also be required to add other utilities to our image, such as gcloud.

## Describe alternatives you've considered

Add the command to `gpctl`. Too heavy, use bash scripts (for now) and reevaluate other options depending on need. The bash scripts, and binaries need to execute on them, can be added to the packer image for workspace nodes on our K3s cluster.

## Additional context

[The incident](https://app.incident.io/incidents/93) impacted the eu25 cluster, where we accumulated workspaces stuck in Stopping, some of which we were not able to backup because the supporting node was garbage collected.

**Comment by kylos101** [comment]
When setting up the out of band backup, it may:
1. Make sense to have the utilities accessible from the node, so they do not have to be downloaded
2. To implement using mage

CC: @aledbf and https://github.com/gitpod-io/runbooks/issues/316#issuecomment-1007456424

**Comment by kylos101** [comment]
backup script
```shell
#!/bin/bash

set -euo pipefail

mkdir /tmp/wsbackup

function backupWS() {
    wsID=$1
    cd /mnt/disks/raid0/workspaces/$wsID
    tar vcf /tmp/wsbackup/full-$wsID.tar .
    cd ..
    cp $wsID.workspace.json /tmp/wsbackup/full-$wsID.workspace.json
}

backupWS 02e43f01-be34-4383-82c5-4b6427ce00af
backupWS 13c57d6c-b110-430f-8de1-3c6feb5c59ee
backupWS 24294470-36af-4568-96ac-dbb48c90591c
backupWS 29ebde73-f9ba-49cc-84d1-5bec84825843
backupWS 2aa137c2-d863-4441-ad5e-3c05ada26f55
backupWS 2d9febbe-a464-40a6-9b46-c637dee54494
backupWS 2e0e2614-66e1-47f3-8ecf-675143ebcb31
backupWS 2e38fe61-eb2a-4438-9022-a27ae3b58d3a
backupWS 5a51f56b-1443-418d-b2de-24eb1cd673f6
backupWS 64fa45e1-f383-4ceb-b582-25238d00af5e
backupWS 788e6991-f42b-41f6-8716-4600c9243320
backupWS 8095b1b2-dd54-45c0-a5e0-c345f0f1d4a1
backupWS 99014c2f-adc4-42d5-8333-5389832931d5
#backupWS 9c46a987-cdd7-474b-afa7-ac0bc44b9002
backupWS ae0dc60b-37f0-4429-9f19-5d8962d5e478
backupWS d4dc45fa-b278-4658-8ab1-8c94b9977c6a
backupWS da61176f-207e-4c39-88df-56cb89bb761e
backupWS fdc02f87-a991-49f8-b14a-22695c93e063

tar vcf /tmp/wsbackup.tar /tmp/wsbackup
```

upload script
```shell
#!/bin/bash

set -euo pipefail

# There are three sets of manual steps needed before you can run this script to upload workspace backups.

# 1. From the node in question, where workspace pods are stuck terminiating, where we suspect backups are lacking, run backup.sh

# 2. From a gitpod workspace, the following manual steps must be run to retrieve the backup from #1
# gcloud auth login --no-launch-browser
# gcloud config set project workspace-clusters
# cd /workspace
# gcloud compute scp workspace-ws-eu25-pool-cxmn:/tmp/wsbackup.tar .
# cp wsbackup.tar wsbackup.tar.backup
# tar -xf wsbackup.tar -C /workspace/incident
## FYI, the above backs up the backup, and extracts the backup to an incident sub-folder
## The contents of /workspace/incident has many pairs of files (1) TAR = backed up files (2) JSON = workspace metadata

# 3. Prepare to work with Google Cloud storage by setting your project context
# gcloud config set project gitpod-191109

function uploadBackup() {
    # given the workspace instance ID
    wsInstanceID=$1

    if [ -f "full-$wsInstanceID.tar.uploaded" ]; then
        echo "backup already uploaded for $wsInstanceID"
        return
    fi

    # get the owner ID from the related json file
    wsOwner=$(cat full-$wsInstanceID.workspace.json | jq .owner -r)
    wsMetaID=$(cat full-$wsInstanceID.workspace.json | jq .metaID -r)    
    
    # what is the vintage of the existing backup?    
    wsVintage=$(gsutil ls -l gs://gitpod-prod-user-$wsOwner/workspaces/$wsMetaID/full.tar | head -n 1 | awk '{print $2}' || echo 'none')
    echo "For $wsInstanceID, $wsOwner, $wsMetaID, with $wsVintage ..."
    
    # handle situation where there is no backup, and potentially no bucket
    if [ "$wsVintage" == "none" ]; then        
        bucket_test=$(gsutil ls -l -b gs://gitpod-prod-user-$wsOwner || echo 'no_bucket')
        if [ "$bucket_test" == "no_bucket" ]; then
            echo "There is no bucket for $wsOwner; cannot upload backup for $wsMetaID."
            # TODO: what do we do in this situation? Not sure how to create the bucket...
            return
        fi

        echo "Creating folder for $wsMetaID and adding backup for $wsOwner."       
                
        uploadNewBackupFile gitpod-prod-user-$wsOwner $wsMetaID full-$wsInstanceID.tar
        return  
    fi    
    
    # there is a backup older than the manual one we made
    # get now in ISO-8601, date -u +"%Y-%m-%dT%H:%M:%SZ"    
    # get now in seconds as of epoch, date --date="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" +%s
    # TODO: replace the hard coded date value, which represents when we manually prepared the workspace backups. 
    # Use the create date of tar files we created? Get via stat? Not UTC friendly...
    backupVintage=$(date --date="2022-01-02T17:10:00Z" +%s)
    backupVintageDate=$(date --date="2022-01-02T17:10:00Z" +"%Y-%m-%dT%H:%M:%SZ")
    wsBackupVintage=$(date --date="$wsVintage" +%s)
    wsBackupVintageDate=$(date --date="$wsVintage" +"%Y-%m-%dT%H:%M:%SZ")
    if [ $backupVintage -gt $wsBackupVintage ]; then
        echo "backup: $backupVintageDate is greater than wsBackup: $wsBackupVintageDate, replacing existing backup for $wsOwner and $wsMetaID"
        uploadExistingBackupFile gitpod-prod-user-$wsOwner $wsMetaID full-$wsInstanceID.tar
        return
    fi
    if [ $wsBackupVintage -gt $backupVintage  ]; then
        echo "backup: $backupVintageDate is less than wsBackup: $wsBackupVintageDate, no uploading for $wsOwner and $wsMetaID"
        return
    fi
}

function uploadNewBackupFile() {
    bucket=$1
    folder=$2
    file=$3
    cp $file $file.uploaded
    gsutil cp -n $file gs://$bucket/workspaces/$folder/full.tar
}

function uploadExistingBackupFile() {
    bucket=$1
    folder=$2
    file=$3
    cp $file $file.uploaded
    gsutil cp $file gs://$bucket/workspaces/$folder/full.tar
}

# workspace instances with existing backups
uploadBackup 02e43f01-be34-4383-82c5-4b6427ce00af
uploadBackup 29ebde73-f9ba-49cc-84d1-5bec84825843
uploadBackup 2d9febbe-a464-40a6-9b46-c637dee54494
uploadBackup 2e0e2614-66e1-47f3-8ecf-675143ebcb31
uploadBackup 2e38fe61-eb2a-4438-9022-a27ae3b58d3a
uploadBackup 8095b1b2-dd54-45c0-a5e0-c345f0f1d4a1
uploadBackup ae0dc60b-37f0-4429-9f19-5d8962d5e478
uploadBackup da61176f-207e-4c39-88df-56cb89bb761e
# uploaded on its own, as a test
uploadBackup fdc02f87-a991-49f8-b14a-22695c93e063

# workspace instances that lack backups, these may not have buckets
# # 2aa137c2-d863-4441-ad5e-3c05ada26f55 03d58344-d61d-4c01-a7b1-f0e062c7481d moccasin-mink-ganbt76j
uploadBackup 2aa137c2-d863-4441-ad5e-3c05ada26f55
# # 5a51f56b-1443-418d-b2de-24eb1cd673f6 30ae3044-ada3-44d8-bea7-6c74d2a9b201 teal-tyrannosaurus-4ygzv2a7
uploadBackup 5a51f56b-1443-418d-b2de-24eb1cd673f6
# # # 64fa45e1-f383-4ceb-b582-25238d00af5e f015b9eb-6f9c-4918-81fc-547ed153f5f1 coral-whippet-9prs7qb7
uploadBackup 64fa45e1-f383-4ceb-b582-25238d00af5e
# # # 788e6991-f42b-41f6-8716-4600c9243320 3e7a6ef2-6429-4047-81c0-183990916628 amaranth-aphid-ozzeaq0c
uploadBackup 788e6991-f42b-41f6-8716-4600c9243320
# # # 99014c2f-adc4-42d5-8333-5389832931d5 82fa0f95-0cf8-4bd9-b209-189df266b12a purple-krill-3x338vvv
uploadBackup 99014c2f-adc4-42d5-8333-5389832931d5
# # # d4dc45fa-b278-4658-8ab1-8c94b9977c6a d1d6cbb7-272c-4358-8b47-c7c1b53109d7 tan-newt-vh0g2v6w
uploadBackup d4dc45fa-b278-4658-8ab1-8c94b9977c6a
# # 24294470-36af-4568-96ac-dbb48c90591c d403e513-df9c-42e2-8b01-d0b10adb5b44 red-walrus-8ye7oou7
uploadBackup 24294470-36af-4568-96ac-dbb48c90591c
# # 13c57d6c-b110-430f-8de1-3c6feb5c59ee c095edf6-adc4-46dd-b2f5-9617e4010b9f harlequin-shrew-zn66g4hi
# uploaded on its own, as a test
uploadBackup 13c57d6c-b110-430f-8de1-3c6feb5c59ee
```

**Comment by sagor999** [comment]
@kylos101 with us transitioning to PVC\Snapshots for data storage, I think this is no longer relevant. 
And to create an out of band snapshot, you would just create new `snapshot` object in the cluster, reference PVC of the workspace that you want to backup, and snapshot will be created for you.

**Comment by kylos101** [comment]
> @kylos101 with us transitioning to PVC\Snapshots for data storage, I think this is no longer relevant. And to create an out of band snapshot, you would just create new `snapshot` object in the cluster, reference PVC of the workspace that you want to backup, and snapshot will be created for you. (I will remove this from our groundwork for now)

Thank you! Sounds good. 

Might be a good dimension to reference in the design doc, too. Basically the same comment you shared (above).

**Comment by kylos101** [comment]
@sagor999 @jenting Can you think of any scenario where we might need to do manual (out of band) backup manually once we're using PVC? :thinking:

**Comment by jenting** [comment]
> @sagor999 @jenting Can you think of any scenario where we might need to do manual (out of band) backup manually once we're using PVC? 🤔

We need to consider a case where the user was launching a workspace at `eu` cluster, stopped the workspace, and launched the workspace but at the `us` cluster now. (Probably because the `eu` cluster is down 🔥).

In this scenario, we could either (both in script way)
- backs up the snapshots from the `eu` cluster to the `us` cluster.
- mount the snapshot, and upload the snapshot content to GCS.

We need to consider which approach is good for the self-hosted.

**Comment by kylos101** [comment]
@jenting this is talking about a scenario where the PVC cannot be snapshotted by the existing cluster (say it is corrupt/down). What would we do in that scenario, with many PVCs that lack snapshots, but all their pods are gone.

**Comment by sagor999** [comment]
Their pods will not be gone. Those WS should be stuck in terminating state until we can do snapshot. 
Or at least we should double check that assumption :)

**Comment by kylos101** [comment]
@sagor999 @jenting  [check out this thread.](https://gitpod.slack.com/archives/C03L5B9N6BA/p1655997171196379)

It looks like it is possible for the cluster autoscaler to evict a node. In that example, the PVCs would be dangling.
