### ISSUE TITLE
Project URL is not slugified for GitLab repos

### ISSUE THREAD

**Issue by bigint** [gitpod-io/gitpod#5847]
### Bug description

![image](https://user-images.githubusercontent.com/69431456/134605314-24aa2e2a-da0c-4e3d-bd34-2cf98ea38b10.png)

Here is how the URL looks like `https://gitpod.io/projects/Timesheet%20Remainder`

### Steps to reproduce

- Create new GitLab Repo with the name `Gitpod Test`
- Connect it to Gitpod projects
- Open the project and check the URL

### Expected behavior

https://gitpod.io/projects/timesheet-remainder

It should take the GitLab repo slug instead of the name

**Comment by gtsiolis** [comment]
Thanks for bringing this up @bigint! This makes sense!

Looping in @jankeromnes and @AlexTugarev who also brought up this issue in a [recent discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1632842370226700) (internal).

**Comment by jankeromnes** [comment]
Nice catch! Thanks for reporting this @bigint (and thanks @gtsiolis for pointing me to it when I also complained about this 😁).

I believe the current situation is:
- There is only `project.name`, which is used in URLs and displayed in the UI
- For GitHub projects, we import the slug as `project.name`
- For GitLab projects, we import the full-text name as `project.name`

Instead, it would be better to:
- Have a (new) specific `project.slug` property for URLs (similar to `team.slug`) in addition to the `project.name` (which can be all nice with capital letters, spaces, varied characters, etc)
- For GitHub projects, import both the slug and the full-text name
- Same as above for GitLab

**Comment by JanKoehnlein** [comment]
I think this is not needed for the launch. Let's bring this up later

**Comment by jldec** [comment]
see https://github.com/gitpod-io/gitpod/pull/6376#discussion_r744337324 regarding why we are not fixing the slugs for existing GitLab repos at this point.
