### ISSUE TITLE
Ui in startup screen broken on hover

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#585]
reported here: https://github.com/PhoenicisOrg/phoenicis/issues/1941#issuecomment-493635810. 

Our UI flickers in a weird way when you hover over a button. See video for details.

>  fix your css for `Go to dashboard` button https://youtu.be/kakVZIjxxEw
> 
> ```
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
> ```
> 
> To reproduce open gitpot repository with issue presented.

**Comment by Kreyren** [comment]
Ware you able to reproduce it?

**Comment by svenefftinge** [comment]
No, I cannot. 
Any tips on how to do that?

**Comment by Kreyren** [comment]
@svenefftinge can you setup a test repo that results in fatal on open (phoenicis had misconfigured java from what i understand for me to reproduce the issue)? I can't reproduce it on fixed phoenicis gitpot repo

**Comment by svenefftinge** [comment]
Sure, I tested it with this https://gitpod.io/#https://github.com/svenefftinge/academic-kickstart

**Comment by Kreyren** [comment]
I think the output is not long enough it seems to scroll through it 

![image](https://user-images.githubusercontent.com/11302521/59500081-54a9e080-8e5e-11e9-9aaf-81194f082888.png)

**Comment by svenefftinge** [comment]
Thank you for trying! I added a bunch of commands, so that the log is loonger and scollable. 
Can you reproduce now?
https://gitpod.io/#https://github.com/svenefftinge/academic-kickstart/blob/master/Dockerfile

**Comment by Kreyren** [comment]
Still unable to reproduce, can you try adding output which is longer in vertical lenght? I'm unable to change it from user-side.

**Comment by svenefftinge** [comment]
done, please try (worked for me, i.e. no flickering)

**Comment by Kreyren** [comment]
@svenefftinge 
![image](https://user-images.githubusercontent.com/11302521/59504340-5d071900-8e68-11e9-9769-1a4152cdbd54.png)

https://gitpod.io/#https://github.com/svenefftinge/academic-kickstart/blob/master/Dockerfile It won't result in fatal now.

https://gitpod.io/#https://github.com/svenefftinge/academic-kickstart does, trying

Firefox doesn't seem to be affected, but i can reproduce it on chromium (`Chromium 73.0.3683.75 built on Debian buster/sid, running on Debian 10.0`). 

Lines expanding past visible console seems to be important for this issue.
