### ISSUE TITLE
gitpod.yml validation and/or execution using the gp command

### ISSUE THREAD

**Issue by DaveAuld** [gitpod-io/gitpod#5850]
I recently used `gp` to create the template `.gitpod.yml` file.
After editing I was looking at how I could validate or test the file, and found the process of stop and starting the workspace or creating a new workspace after pushing the file to the repo pretty tedious, especially after a few attempts of trying to achieve what I wanted.

It would be great if the `gp` command had an `--execute` and/or `--validate` option that could be used to do just that on the `.gitpod.yml` file, without the need to actually stop/restart/or recreate the workspaces.

Associated posts on gitpod community at:
https://community.gitpod.io/t/feature-request-gitpod-yml-validate-or-execute-with-gp/5117
https://community.gitpod.io/t/how-to-manually-execute-gitpod-yml-file/4464

Thanks,
Dave

**Comment by akosyakov** [comment]
Unfortunately after team discussions we realised that we don't have capacity for new features and have to focus more on bug fixes and robust deployments for now.

**Comment by RyzeNGrind** [comment]
Is there any way to use the `gp validate` command as a pre-commit hook in my Github Actions workflow? It would be a very useful feature when testing or building your own workspaces.

**Comment by akosyakov** [comment]
> Is there any way to use the gp validate command as a pre-commit hook in my Github Actions workflow? It would be a very useful feature when testing or building your own workspaces.

As for now `gp validate` can work only within a Gitpod workspace. If you are interested only in validating the image then you should be able to use `docker build` though.
