### ISSUE TITLE
[server] Move `vsxRegistryUrl` config value from `server-configmap.yaml` to `server-ide-configmap.yaml`

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#5852]
~~@akosyakov: What is about the config value `codeSync`? Is it under IDE team responsibility as well?~~

**Comment by akosyakov** [comment]
Yes, it is too. But maybe with another issue, there we maybe need a restart of express application to pick up new settings.

**Comment by akosyakov** [comment]
@corneliusludmann I'm accepting it. Hope you can take care of it. We should also think how it is configurable for different versions of IDE.

/schedule

**Comment by roboquat** [comment]
@akosyakov: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5852#issuecomment-930114395):

>@corneliusludmann I'm accepting it. Hope you can take care of it. We should also think how it is configurable for different versions of IDE.
>
>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
