### ISSUE TITLE
[server] Move `codeSync` config value from `server-configmap.yaml` to `server-ide-configmap.yaml`

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#5853]
> there we maybe need a restart of express application to pick up new settings.

https://github.com/gitpod-io/gitpod/issues/5852#issuecomment-926410072

**Comment by akosyakov** [comment]
`codeSync` seems to be quite stable component, i.e. we did not deploy it since march, so i remove it from inbox for now. Let's do after we decoupled other IDE components.
