### ISSUE TITLE
Extension version on .gitpod.yml not honored

### ISSUE THREAD

**Issue by doppeldenken** [gitpod-io/gitpod#5856]
### Bug description

The version specified in the `.gitpod.yml` is not honored by default.

### Steps to reproduce

For example:

```
vscode:
  extensions:
    - ms-python.python@2021.9.1218897484
    - ms-toolsai.jupyter@2021.8.12
    - ms-azuretools.vscode-docker@1.16.1
    - hashicorp.terraform@2.14.0
````

Gitpod sometimes starts with the latest version, not the one specified, sometimes it starts with the specified version, but it updates after Gitpod is up and running:

![image](https://user-images.githubusercontent.com/59898907/134651194-b83926e1-7fc7-43a7-b5c7-fc7fd41dbf3f.png)

### Expected behavior

To have Gitpod install the specified versions and having them not changing unless specified by the user.

### Anything else?

As described in [this](https://community.gitpod.io/t/extension-version-on-gitpod-yml-not-honored/5115/3) community post, I was able to fix the issue by tweaking two VSCode settings:

`"update.mode": "manual"` and `"extensions.autoUpdate": false`

![image](https://user-images.githubusercontent.com/59898907/134651656-b6ea0463-ce3e-475f-8582-168edf4f31d0.png)

I'm filling this issue per a request of the admins of the Gitpod community.

**Comment by eduardoaemunoz** [comment]
Actually the behaviour is back..

Just after starting Gitpod:

![image](https://user-images.githubusercontent.com/59898907/134681661-cd3c7249-52a9-453b-95b1-e7a779b84710.png)

As before, my .gitpod.yml:

```
vscode:
  extensions:
    - ms-python.python@2021.9.1218897484
    - ms-toolsai.jupyter@2021.8.12
    - ms-azuretools.vscode-docker@1.16.1
    - hashicorp.terraform@2.14.0
```

It seems the right version is installed first, then the latest?

My settings in VSCode (are there other settings that could potentially help with this?):

`"update.mode": "none"`

`"extensions.autoCheckUpdates": false`

`"extensions.autoUpdate": false`

**Comment by eduardoaemunoz** [comment]
It's weird because in a different repository the correct version extension is installed. In this case, I have an init task. Could that have any impact at all? I'm going to trigger pre builds for the Gitpod that is buggy.
