### ISSUE TITLE
Terminal does not load

### ISSUE THREAD

**Issue by Sxpherr** [gitpod-io/gitpod#5858]
I have this issue for two days now, it always shows me that (I tried and different workspaces)![image](https://user-images.githubusercontent.com/66752592/134672339-f919a411-3c63-4fbe-882a-1cd0efb5aa4d.jpeg)

**Comment by akosyakov** [comment]
Which version of VS Code do use latest or stable? Which versions of device, operating system, browser?

**Comment by Sxpherr** [comment]
> Which 
I'm using ipados 15, firefox and the latest version

**Comment by akosyakov** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/5040
