### ISSUE TITLE
Requests are rejected when made to the same application URL

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#586]
**Describe the bug**
I have a PHP script running on a gitpod instance that is trying to request to the same gitpod instance but to another URL.

The connection gets refused and times out.

I tried also in Python and Node.js, it always times out.

**To Reproduce**
On any language, you can replicate it.
Here is a very simple example that I made for you guys:
https://github.com/alesanchezr/nodejs-hello-world

The enpoint /test is trying to fetch for /data and it never gets the response.

**Comment by svenefftinge** [comment]
For the example the error is logged.
```
(node:4120) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/workspace/nodejs-hello-world/node_modules/node-fetch/lib/index.js:1299:9)
    at /workspace/nodejs-hello-world/node_modules/node-fetch/lib/index.js:1404:19
    at new Promise (<anonymous>)
    at fetch (/workspace/nodejs-hello-world/node_modules/node-fetch/lib/index.js:1401:9)
    at /workspace/nodejs-hello-world/index.js:12:3
```
[node-fetch doesn't support relative URLs](https://github.com/bitinn/node-fetch/issues/481). Changing it to `http://localhost:8080/data`works.

**Comment by svenefftinge** [comment]
@alesanchezr do you have more information for the original PHP case or can we close this issue?

**Comment by alesanchezr** [comment]
It was a problem only happening on apache, I solve it by adding this into the .htaccess file:
```
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
```

Basically there was an infinite redirect loop between http and https.
