### ISSUE TITLE
[ws-manager-bridge metrics] Cluster score and cordoned metrics don't work

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5866]
### Bug description

The ws-manager-bridge cluster score metric does not change its value. The metrics are present though.

### Steps to reproduce

Observe this in production

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5866#issuecomment-926752048):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
