### ISSUE TITLE
Blank Terminal on iPad OS 15

### ISSUE THREAD

**Issue by jappyjan** [gitpod-io/gitpod#5870]
### Bug description

The Terminal stays blank on an iPad

Actual Behaviour:
Terminal Shows "Invisible" Characters and a blinking Cursor.
I can select stuff but i dont see a single character.
I can type but i dont see what i type
see screenshot for reference

![IMG_3174FC3941D1-1](https://user-images.githubusercontent.com/10154260/134746421-f1416d9f-a5b4-4c1f-8691-162003bd07b1.jpeg)
d.

### Steps to reproduce

Open Gitpod.io on an iPad
Open a new Terminal

### Expected behavior

I see text in the terminal
I see text that i type in the terminal

**Comment by aledbf** [comment]
Closing. Duplicate https://github.com/gitpod-io/gitpod/issues/5040

Please check comment https://github.com/gitpod-io/gitpod/issues/5040#issuecomment-892376295 for a workaround
