### ISSUE TITLE
Resuming a timed-out container does not rerun `gitpod.yml`

### ISSUE THREAD

**Issue by LinqLover** [gitpod-io/gitpod#5873]
### Bug description

I have experienced this issue several times: I am working in a container for some time (gitpod.io, no subscriptions), after some time of inactivity, it goes to sleep, and when I return to it, the `gitpod.yml` contents seem not to be re-run correctly. Concretely, my `gitpod.yml` contains a single task for installing node v16 (`nvm install 16`), but when I resume the container, node version 14 is installed again and I need to manually type `nvm install 16` into the console.

Is this a known issue? :-)

### Steps to reproduce

- Set up a gitpod.yml with `nvm install 16` task
- Start a new instance of the container, make sure node v 16 is installed
- Wait until the container goes to sleep
- Reopen it
- node v14 is installed now!

### Expected behavior

- Node v16 should be installed again

### Example repository

Not an MWE, but this is the repo I am working with:

https://github.com/LinqLover/downstream-repository-mining

**Comment by pawlean** [comment]
Hi @LinqLover! I've been unable to reproduce this. Can you maybe share some before and after screenshots or perhaps record a short video demonstrating this? That certainly doesn't seem right!

**Comment by LinqLover** [comment]
Ah, seems as if this is not related to time-outs but to terminal sessions. Simple steps to reproduce:

1. Open https://github.com/LinqLover/downstream-repository-mining/tree/102882a89864f25eab5c2e54843b175d32dd9e01 in a new gitpod container
2. In the terminal, you can see that node v16 has been installed via the `.gitpod.yml` file. Assert that by typing `nvm version` and seeing `v16.10.0`.
3. Open a second terminal and type `nvm version` again. Instead of `v16.10.0`, you now can see `v14.17.6`.

Not sure whether this is an issue with my [`.gitpod.yml`](https://github.com/LinqLover/downstream-repository-mining/blob/b51fa417fcb572133f2591301e72636c5a55d0a7/.gitpod.yml#L3-L3). I have deviated from the exact steps recommended in the [docs](https://www.gitpod.io/docs/languages/javascript#node-versions) because starting a gitpod container becomes significantly slower [when I specify my own Dockerfile](https://github.com/LinqLover/downstream-repository-mining/tree/9d708b0c8d70fb1bd2d2a07e2711d1a8d4a8be3b). I don't see a reason however why initializing nvm from an init script should not work. In case this is relevant, [here](https://stackoverflow.com/questions/24585261/nvm-keeps-forgetting-node-in-new-terminal-session) is a related question on SO, but I don't see anything I would be doing wrong according to these answers.
