### ISSUE TITLE
New ws-eu18 cluster is missing persistent state for extensions from session to session

### ISSUE THREAD

**Issue by AjXUthaya** [gitpod-io/gitpod#5877]
### Bug description

I noticed i was switched from eu16 to eu18 if i remember correctly, ever since i have to install vscode extensions every time i start up the workspace

### Steps to reproduce

1. Spin up a workspace on the eu18 server
2. Install a vscode extensions
3. Fully stop & restart the workspace and check your extensions, all extensions installed in the previous session is gone

**Comment by pawlean** [comment]
Hi @AjXUthaya! I was unable to reproduce this. Can you just check you've got Settings Sync switched On?

<img width="339" alt="2021-09-27 at 13 26 12 - Google Chrome" src="https://user-images.githubusercontent.com/17087373/134907749-f9d923ff-924f-4d9b-87ee-d65ea2fb442c.png">

**Comment by AjXUthaya** [comment]
Sync is active and the packages are listed in the gitpod config, for some reason the "pkief.material-icon-theme" package is the only one that manages to install. Added some screenshots that show extensions being installed + sync is active + listed in gitlab config -> stoping workspace -> starting workspace -> all extensions but material icon theme is gone/uninstalled for the workspace
![Screenshot 2021-09-28 at 10 22 51](https://user-images.githubusercontent.com/53090349/135051742-6a2b7587-5d33-472b-82cf-5fb813eacdbe.png)
![Screenshot 2021-09-28 at 10 22 59](https://user-images.githubusercontent.com/53090349/135051751-e8dce250-8fff-4653-92ce-f0f7d64fb3b8.png)
![Screenshot 2021-09-28 at 10 24 34](https://user-images.githubusercontent.com/53090349/135051759-2d233a4c-3338-4a91-93de-0d1b5c8a21d2.png)
![Screenshot 2021-09-28 at 10 25 31](https://user-images.githubusercontent.com/53090349/135051764-9cb9df36-35bc-4525-b93a-67ab5644001c.png)
![Screenshot 2021-09-28 at 10 25 40](https://user-images.githubusercontent.com/53090349/135051767-3c7c9dd4-0415-41fc-b0df-d670620335c7.png)
l
![Screenshot 2021-09-28 at 10 26 29](https://user-images.githubusercontent.com/53090349/135051786-4b4ce105-ad51-4823-a1d0-57a29a6907e1.png)
![Screenshot 2021-09-28 at 10 26 37](https://user-images.githubusercontent.com/53090349/135051796-330fa4d0-b78d-46b3-bfa5-60df69382f6e.png)
.

**Comment by AjXUthaya** [comment]
No longer an issue so closing this case
