### ISSUE TITLE
Add ability to create gitpod instance in subdirectories

### ISSUE THREAD

**Issue by Decipher** [gitpod-io/gitpod#5878]
**As a project maintainer I want the ability to have multiple Gitpod configuration files within subdirectories so I can demonstrate multiple examples of my project.**

This is something already available with Codesandbox.io, using the following format:
https://codesandbox.io/s/github/[USER/REPO]/tree/[BRANCH]/[DIRECTORIES]

e.g.:
- https://codesandbox.io/s/github/nuxtlabs/examples/tree/master/routing/hello-world
- https://codesandbox.io/s/github/nuxtlabs/examples/tree/master/loading/custom-loading-component

**Comment by shaal** [comment]
@Decipher is this feature still needed?

**Comment by Decipher** [comment]
Yes, I would still find this a very useful feature.

**Comment by shaal** [comment]
@Decipher does this new feature solve the issue?
https://www.gitpod.io/docs/multi-repo-workspaces#multi-repo-workspaces
