### ISSUE TITLE
Python extension is not running

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/gitpod#5884]
### Bug description

A community member has reported that they cannot run their Python extension on their workspace. Their first occurrence of this was September 23rd. The user is still experiencing this same issue today. 

See below screenshot of what they are seeing. They cannot use the Python extension because it says "Reload required" but I'm assuming that when the user has tried to reload, this doesn't do anything. 

![Screenshot1](https://user-images.githubusercontent.com/17087373/134910110-9eef33a4-3e12-419d-be71-21f0890f026d.png)

[Internal discussion.](https://gitpod.slack.com/archives/C020VCB0U5A/p1632745090214800) It was suggested that they try using VS Code Desktop, but even on there, they have the same issue. See screenshot:

![Screenshot from 2021-09-27 18-18-06](https://user-images.githubusercontent.com/17087373/134911151-a7d63f0a-eb45-46a0-9ff4-efcc964c56e2.png)

User is not using VS Code LATEST, but on the stable build (VS Code).

### Steps to reproduce

I've not been able to reproduce this myself on my workspace - but the steps I followed are:

- Open new workspace
- Head over to Extensions
- Search for Python
- Install Python extension
- Python extension doesn't work (and has the "reload required" message)

### Expected behavior

Python extension should be working. 

### Example repository

I've been unable to replicate this issue, but it was reported by a community member who has provided us with the screenshot above. If you'd like more information, please refer to internal discussion and Front emails.

**Comment by roboquat** [comment]
@akosyakov: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5884#issuecomment-927896803):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
We updated python and jupyter extension in Open VSX and it resolved the issue.

**Comment by divyaishafoundation** [comment]
Yeah it is working now. thank you
