### ISSUE TITLE
[gitpod-db] use testcontainers for DB tests

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#5886]
At the moment the gitpod-db DB tests expect a database to be available in the environment. Instead, they could assume there's Docker available which is an easier assumption to make. Using [testcontainers](https://github.com/testcontainers/testcontainers-node) they could start a database if need be.

This would let us remove the `testdb` container from the build pod and simplify the workspace setup.

**Comment by JanKoehnlein** [comment]
Thanks for the recommendation. Would you mind bringing this up again ~1 week?

**Comment by bsideup** [comment]
Hey folks! I am one of the Testcontainers maintainers - feel free to ping me if you need an assistance or some questions to be answered 👍 

P.S. I would like to use this opportunity to say thank you for working on Gitpod - it is great, and I am one of the believers in Cloud IDEs being the future of modern development environments 💯

**Comment by jldec** [comment]
Thanks for that feedback @bsideup !
