### ISSUE TITLE
[projects] New configuration is not present when opening the first workspace

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#5888]
How to reproduce: 

1. Follow the `/new` wizard and create a new project without an existing config in the repo. 
2. On the configuration page: add any config and hit `Run Prebuild`, then wait for it to finish.
3. Now select `New Workspace` and see the new workspace is started from the prebuild.
4. Expected: see uncommited changes in Git view representing the config from the dashboard
5. Actual: no changes in Git

**Comment by roboquat** [comment]
@svenefftinge: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5888#issuecomment-929946893):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by AlexTugarev** [comment]
Perhaps this is related to the bogus status problem. I'm trying to reproduce once more and update the details. 
What I checked few minutes ago with https://gitlab.com/AlexTugarev/demo123 which is simply an instance of the Express template on GitLab, and there I started a prebuild with the detected project configuration. After a few seconds the state was reported as `READY` this remained for a couple of minutes and the opened workspaces wasn't actually loaded from any prebuild. Instead after a few minutes the state of the prebuild (still on the config page) went to `Prebuild in progress ...`

**Comment by AlexTugarev** [comment]
<img width="1269" alt="Screen Shot 2021-10-06 at 13 28 12" src="https://user-images.githubusercontent.com/914497/136194178-8cf608fe-f963-4691-b004-4ad602f6316c.png">

It really looks like the prebuild workspace is finished OK and ws-manager reports the STOPPED phase as it supposed to.

**Comment by jankeromnes** [comment]
Aha, many thanks for confirming @AlexTugarev ! I also started suspecting this this morning when seeing a finished Prebuild randomly become running again (only in the instance-based status)
