### ISSUE TITLE
Document proxy caddy configuration and make it configurable

### ISSUE THREAD

**Issue by asthomasdk** [gitpod-io/gitpod#5890]
I had to work around an issue with headers not being set correctly for previeweing an aplication we are developing and testing in Gitpod. To do that I ended up hacking the Caddyfile in the proxy pod - which seems to have done the trick. 

To make it easier to to this and also persist the changes, without havinng to build new customo images, I think it would work to adjust the proxy deployment so that it uses a configmap for the Cadyyfile. This could then be adjusted from kubernetes (e.g. Rancher) instead of having to log into the pod and modify the config file directly. 

Atthe same timem, the documentation should be updated with info on what it is in the Caddyfile and how it can be tweaked if needed.

**Comment by aledbf** [comment]
> I had to work around an issue with headers not being set correctly for previeweing an aplication we are developing and testing in Gitpod. 

Can you share details about the changes?

Right now, the Caddyfile contains the mandatory config for Gitpod, and we also have a configmap for optional/configurable things
https://github.com/gitpod-io/gitpod/blob/main/chart/templates/proxy-configmap.yaml

**Comment by asthomasdk** [comment]
Sure - I was having problems with proxied requests getting mixed https/http headers and getting blocked by the browser. 

So I ended up adjusting the `security_headers` sesction to : 
`Content-Security-Policy    "upgrade-insecure-requests; frame-ancestors self https://*.{$GITPOD_DOMAIN} https://{$GITPOD_DOMAIN}"`
