### ISSUE TITLE
Confusing `Create` button UX when creating a fresh workspace

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#59]
**Describe the bug**

When I click on `Create` in my workspace list on https://gitpod.io, there is no "pending" or "loading" indication, so it looks like nothing is happening and the UI isn't responding for a while.

(This problem also applies to the `Stop` button. A pending animation would be generally helpful on such buttons, e.g. a spinner or throbber or anything like that. But I think the `Create` button can even be removed entirely.)

**To Reproduce**
Steps to reproduce the behavior.

- On the https://github.com/mozilla/gecko-dev repository, I click on the `Gitpod` button
- I'm given the choice to open an old workspace, or to create a fresh one
- I click on `Create`, to create a fresh workspace
- The `Create` button is then greyed out, but nothing seems to happen (no "loading" icon, no screen change) for a long while
- (Then I eventually see the Gitpod splash/loading screen appear, but I was worried the app wasn't doing what I requested)

**Expected behavior**

- Instead of greying out the `Create` button, and showing no change for a long while, I'd expect to instantly see the Gitpod splash/loading screen when clicking `Create` (just like when you click `Start`)

(Actually, I believe in such a situation, I'll never want to re-use an old workspace, so the question is pointless. And since it's in your best interest that people create fresh workspaces all the time, I'd suggest not giving the user a choice, and always create a fresh workspace in this situation even if there is an old one around. To re-open old workspaces, users can always head to https://gitpod.io and resume them from there.)

**Comment by svenefftinge** [comment]
> (Actually, I believe in such a situation, I'll never want to re-use an old workspace, so the question is pointless. And since it's in your best interest that people create fresh workspaces all the time, I'd suggest not giving the user a choice, and always create a fresh workspace in this situation even if there is an old one around. To re-open old workspaces, users can always head to https://gitpod.io and resume them from there.)

I agree. I think we are trying to be a bit too smart here.
