### ISSUE TITLE
Prebuild status indicator on "Branches" can be misleading

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#5908]
Situation: Th status indicator for the branch says "Ready" (because a prebuild for a former commit exists), but the current HEAD has none (yet). Because the branch details contain a commit (short) hash I as a user assume the commit and prebuild are connected (and wonder why I can a workspace build on the wrong commit), while they aren't.
![image](https://user-images.githubusercontent.com/32448529/135098414-765598e6-3941-4960-be6e-0498e7d69716.png)

Possible solutions:
 - shows status indicator for latest commit only (incl. none if for whatever reasons there is no prebuild for the latest commit, yet)
 - remove commit details, and make the view about branches only
 - somehow make transparent that here possibly is are a lot of prebuilds, one for each commit (no idea how to display that)

**Comment by JanKoehnlein** [comment]
@gtsiolis What do you think?

**Comment by gtsiolis** [comment]
Thanks @geropl! Going with the first proposal to show status indicator for latest commit only sounds a good step forward.

FWIW, We do have design specs most prebuild status phases including PENDING, RUNNING, etc. and I can see the RUNNING state popping up when a new prebuild is triggered.

❓ **question**: Are we not surfacing a prebuild phase here?

| Branches with prebuilds status |
|-|
| <img width="1099" alt="Screenshot 2021-09-30 at 1 17 36 PM" src="https://user-images.githubusercontent.com/120486/135437546-a9928ecb-777f-4614-9b46-34df5c8084ed.png"> |

**Comment by laushinka** [comment]
@geropl I tested this and couldn't reproduce it. I committed to both a new and an existing branch, and the prebuild statuses were consistent in both the "Branches" and "Prebuilds" tabs. I can show you sync or create a Loom, to make sure I understand the supposed bug.

**Comment by geropl** [comment]
@laushinka The problem here is that on the "Branches" view, the "Prebuild" column is filled if we have _any_ prebuild for the respective branch. But the "Commit" column always shows the _latest_ commit.

Not sure how to reproduce, though. But should be fairly straight forward to find in the code. Happy to sync after the meeting! :+1:
