### ISSUE TITLE
Extremely long startup time for large repositories

### ISSUE THREAD

**Issue by Terra316** [gitpod-io/gitpod#5910]
I'm working on a particularly large repository, and I'm in the process of the image build. I've been waiting half an hour for the workspace logs to load, and it's eating up time. Gitpod has been very, very fast and helpful with many projects, and I love using it. But, actually, a while ago when I used it in the past with the same repository, and it built the image fairly easily. Is there anything I can do to fix the slowness?

**Comment by Terra316** [comment]
I managed to reconfigure it so that it gets all the way to Initializing Base Image context, but not any farther.

**Comment by jankeromnes** [comment]
Hi @Terra316! Sorry for the waiting time on these builds. Gitpod tries to keep waiting times to a minimum.

Could you please share your repository URL if it's public, or some workspace IDs, so that we can investigate what went wrong?
