### ISSUE TITLE
Add Folder to Workspace...is not working

### ISSUE THREAD

**Issue by pmverma** [gitpod-io/gitpod#592]
**Describe the bug**

I want to add a folder from `~/mysrc` to current workspace so that it is displayed in explorer.
But no folder from 'home' is displayed under the dialog box.
![image](https://user-images.githubusercontent.com/5289123/58530364-7d966880-8204-11e9-865b-e82a81b82a46.png)

**To Reproduce**

1. Create a folder under home
2. Right click in explorer and choose "Add Folder to Workspace..."
3. No directory will be displayed there

**Expected behavior**

Directory tree structure is expected to be displayed if I am not wrong.

**Comment by pmverma** [comment]
Closing this as it is working now!

**Comment by svenefftinge** [comment]
Be aware that changes outside `/workspace` are not persisted between workspace restarts.

**Comment by pmverma** [comment]
Thanks, @svenefftinge for the information.
Is there any way that directories under `/workspace` can be displayed in explorer.

**Comment by svenefftinge** [comment]
You could set the workspace location to /workspace. 
You can do that either manually using the command "File:Open..." or through configuration in your gitpod.yml:
```yml
workspaceLocation: "."
```
