### ISSUE TITLE
[local-app] don't produce new version only if build version is changed

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5921]
Otherwise VS Code Desktop users download new version each day.

**Comment by roboquat** [comment]
@akosyakov: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5921#issuecomment-930114999):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
