### ISSUE TITLE
[supervisor] Enable access to task output in CLOSED state

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#5922]
Context: https://github.com/gitpod-io/gitpod/pull/5918#pullrequestreview-766352251

Until now we use a combination of `supervisor` APIs to get hold of headless logs:
 - `tasks.tasksStatus`: to list all available tasks and their terminals
 - `terminals.listen`: get the actual terminal output

But `terminals.listen` will only work for terminal that are in `RUNNING` state; if one goes into `CLOSED` we atm can no longer access it's logs.

Note that this is not a big problem atm because:
 - we don't show more than 1 terminal in the UI, yet
 - most repositories don't use more than one task
 - if they do: the longest-running terminal is always the most relevant one 

@akosyakov suggested to introduce sth ala `getTaskOutout` which instead streams the content directly from the file we use to store the termial output in. This could also be used for live terminals, so we no longer need `terminals.listen` in the first place.

**Comment by akosyakov** [comment]
I will remove it from the inbox. We don't accept feature requests for now. Focus on bug fixes and reliable deployments.
