### ISSUE TITLE
Redirect users to the members list when trying to join a team they have already joined

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5925]
### Problem to solve

When a user is trying to join a team you've already joined they see the following error page.

> Redirect users to the members list when trying to join a team they have already joined

See also [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1631009839127300) (internal). Cc @AlexTugarev 

> This was also brought up while adding this in https://github.com/gitpod-io/gitpod/pull/4490#discussion_r650154442. Cc @jankeromnes 

| Joining a team you've already joined |
|-|
| ![gitpod io_teams_join_inviteId=f2c69638-1d9b-483e-bad0-61a0e81204a8](https://user-images.githubusercontent.com/120486/135292111-178f0cfa-a889-4948-ba78-cf0bfda899d4.png) |

### Proposal

Cross-posting from the [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1631009839127300) (internal):

> Ideally, this would also include some feedback to the user using a toast component (see https://github.com/gitpod-io/gitpod/issues/3530).

> However, redirecting to the team or members list sounds like a good MVC.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5925#issuecomment-931179217):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
