### ISSUE TITLE
"Error: Not connected to message bus" when starting workspaces

### ISSUE THREAD

**Issue by lechien73** [gitpod-io/gitpod#5928]
### Bug description

When starting workspaces, Gitpod is failing to load with the error "Not connected to message bus"
![Screenshot 2021-09-29 at 16 38 58](https://user-images.githubusercontent.com/21156053/135302487-5830c518-1a66-41c8-a279-e4067a1d7f6e.png)

### Steps to reproduce

Attempt to start a workspace and it will either spin forever or return the above error.

### Expected behavior

Normal starting workspace

**Comment by gtsiolis** [comment]
Thanks for reporting @lechien73! The team is already on it. ⚡ 

We're currently investigating, see https://www.gitpodstatus.com/incidents/bptcrqdnw7sz. 💡 

Let's also keep this issue open in favor of https://github.com/gitpod-io/gitpod/issues/5927 as the issue title is more descriptive here. Cc @dnlbowers

**Comment by vinnieOrdobas** [comment]
experiencing the same issue over here:
https://screenshot.click/29-42-62035-8871.png

**Comment by C-Undritz** [comment]
Experiencing the same here.  In addition; within the workspaces menu I get the additional when hovering above the red dot
![gitpod_fail_message](https://user-images.githubusercontent.com/72443150/135304660-bc872697-801e-4443-8057-21c76caa297a.png)

**Comment by jankeromnes** [comment]
The incident is now resolved (workspaces can start again), but we're continuing to investigate what happened to `message-bus` and are closely monitoring the EU cluster.

Sorry for the disruption!

**Comment by C-Undritz** [comment]
Thank you for the speedy resolution!

**Comment by meysholdt** [comment]
closing, because it's resolved.
