### ISSUE TITLE
pre build logs with wrong terminal width

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#5933]
### Bug description

Hi,

if I look at the prebuild logs they look really ugly:

![Uploading image.png…]()

### Steps to reproduce

add an init with npm ci & maybe some docker pull
and look at the logs after the prebuild is done

**Comment by TheBestMoshe** [comment]
![961250bd6c9f3c7eaa4a7e615cf88b8b662114f9_2_690x367](https://user-images.githubusercontent.com/34072688/135517166-820446ee-84fa-482c-9173-137fef7b8323.png)

I'm just reposting @konne's screenshot as it seems to have not uploaded properly.

I also have the same issue.
