### ISSUE TITLE
[self-hosted] Starting workspace immediately stops with error "cannot mknod fuse...file exists"

### ISSUE THREAD

**Issue by dtate-wave** [gitpod-io/gitpod#5937]
### Bug description

When starting a new workspace, after the image is built the workspace immediately stops. The workspace pod is then immediately deleted. Looking into the `ws-daemon` logs this seems to be an issue with `/app/nsinsider` failing due to a file already existing.

`ws-daemon` logs:
```json
{
   "args":[
      "/app/nsinsider",
      "mknod-fuse",
      "--uid",
      "33333",
      "--gid",
      "33333"
   ],
   "instanceId":"<>",
   "level":"fatal",
   "message":"file exists",
   "serviceContext":{
      "service":"nsinsider",
      "version":""
   },
   "severity":"CRITICAL",
   "time":"<>"
}{
   "@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
   "error":"cannot run nsinsider: exit status 1",
   "instanceId":"<>",
   "level":"error",
   "message":"PrepareForUserNS: cannot mknod fuse",
   "serviceContext":{
      "service":"ws-daemon",
      "version":""
   },
   "severity":"ERROR",
   "time":"2021-09-29T20:52:20Z",
   "userId":"<>",
   "workspaceId":"<>"
}
```
Remediation actions tried:

1. Created new GKE meta and workspace nodes
2. Updated GKE cluster from 1.18 to 1.21

### Steps to reproduce

1. Deploy Gitpod 0.10.0 to GKE 1.21 cluster. 
2. Create workspce using an example Github repo

### Expected behavior

Workspace starts successfully.

### Example repository

Any of the default example repositories will reproduce this issue.

### Anything else?

Environment:
GKE: 1.21 (rapid channel)
Runtime: Ubuntu 20.04 | containerd 1.4.3-0ubuntu0~20.04.1
Gitpod: 0.10.0 (release)

**Comment by mjaindwave** [comment]
Dear Gitpod developers,

Without getting this issue resolved, we are unable to continue with Gitpod's self-hosted option at D-Wave systems. This is a top blocker for us and we could really use your attention on this.

Is there any supported environment configuration that worked for you successfully in using the self-hosted model of Gitpod? Also, do you have any troubleshooting suggestions?

As mentioned above, we are using:

GKE: 1.21 (rapid channel)
Runtime: Ubuntu 20.04 | containerd 1.4.3-0ubuntu0~20.04.1
Gitpod: 0.10.0 (release)
