### ISSUE TITLE
No tasks found.

### ISSUE THREAD

**Issue by JamesGreenaway** [gitpod-io/gitpod#594]
How do I add a task to Terminal > Run Task. 

I have a task added to my .gitpod.yml but it is not recognised as a task in this menu? 

Thanks

**Comment by svenefftinge** [comment]
They are not yet synced. See https://github.com/gitpod-io/gitpod/issues/247.

**Comment by akosyakov** [comment]
You can switch to VS Code now https://www.gitpod.io/docs/feature-preview/#default-ide
