### ISSUE TITLE
MySQL port get disconnected not sure why

### ISSUE THREAD

**Issue by bigint** [gitpod-io/gitpod#5943]
### Bug description

Whenever a new workspace is fired, sometimes MySQL connection get lost but it worked fine in prebuild

![image](https://user-images.githubusercontent.com/69431456/135382811-848078f2-b052-43f8-9508-9425478d776d.png)

### Steps to reproduce

Here is the repo https://gitlab.com/yo/devparty

There are no such steps, it is happening only sometimes

### Expected behavior

Connection should be available in both prebuild and in workspace too

### Example repository

https://gitlab.com/yo/devparty

**Comment by csweichel** [comment]
We had an incident in the eu18 cluster earlier today that still affects the port exposure.
Service should resume as normal over the course of today.

Can you confirm that your workspace ran in eu18? You'd see this based on the workspace URL.

**Comment by bigint** [comment]
@csweichel This happened in us18, and this is happening for past one week 🤔

**Comment by bigint** [comment]
Also now sometimes getting failed in prebuilds too 🤔 

![image](https://user-images.githubusercontent.com/69431456/135561488-345def6c-fe94-4d2a-8e39-b5e188a52853.png)
