### ISSUE TITLE
"Not enough credits. Please book more." user error

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/gitpod#5946]
### Bug description

One of our users have come across this error when they are trying to open their Gitpod workspace. 

![image001](https://user-images.githubusercontent.com/17087373/135410238-6509e2b8-4f76-411d-95c0-c430496de49a.png)

They are currently part of the Professional Plan and have a team seat assigned to them. We've checked if the owner's payment is up-to-date which it is. 

### Steps to reproduce

N/a

### Expected behavior

User should be able to open workspace without being asked about credits.

### Anything else?

We have an internal discussion on Front.

**Comment by jankeromnes** [comment]
Oops 🙈 this looks indeed like a bug (firstly, this error should not be displayed like that, and secondly, it shouldn't even occur if you're on the Professional plan).

@pawlean could you please share the user ID and workspace ID if you have access to them?

**Comment by pawlean** [comment]
> @pawlean could you please share the user ID and workspace ID if you have access to them?

user ID: c3cce350-9b54-4762-99e1-d4835f7f6183
workspace ID: indigo-scallop-oz5nyyei

**Comment by pawlean** [comment]
Update: @jankeromnes added 100 extra credits to this user, which seemed to be a temporary fix. Because they have this same issue again:

<img width="753" alt="2021-10-04 at 09 17 53 - Google Chrome" src="https://user-images.githubusercontent.com/17087373/135817268-69c9bc5a-66b1-4073-90e8-1a1e4289b85c.png">
