### ISSUE TITLE
don't share ignored ports in local companian app

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#5950]
at the moment just all ports are share from the remote system to the local system.
We need to control this, that only some ports that shared.

The port control options needs more options:

hidden ... fully hidden even not visible in the vscode remote explorer
notshared ... not available via local Companion app
onlylocalhost ... only bound to localhost in Companion app

**Comment by akosyakov** [comment]
Eventually we would like to provide CLI which allows to control auto tunnelling as well as tunnelling of individual ports.

**Comment by konne** [comment]
The biggest USP that I see in tools like gitpod is to have a centralized managed developer experience.
So if you only add these features to the CLI client this is again not centralized managed.
Can you please add this argument into your local internal PM discussion?

thx
