### ISSUE TITLE
Enable T&P for everyone

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#5953]
The T&P UI layout has been hidden during development. We can remove it now so people can discover it.
For existing users, this will change the dashboard from:

<img width="1452" alt="Screenshot 2021-09-30 at 11 52 39" src="https://user-images.githubusercontent.com/372735/135430525-1c00252e-3620-4e52-9a94-0d1711e358fd.png">

to

<img width="1390" alt="Screenshot 2021-09-30 at 11 53 11" src="https://user-images.githubusercontent.com/372735/135430542-2acca315-9234-43c3-b95e-5a89ba0520f6.png">

So they see there is something like projects and can try setting their projects up.

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5953#issuecomment-931170405):

>/team meta
>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5953#issuecomment-931170865):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
