### ISSUE TITLE
Have graphs for number of open / closed connections

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5954]
During yesterdays incident we were on the wrong track for a while because connection counts are not surfaced in Grafana. The metric endpoints are there, just graphs in Grafana are missing.

Metrics:
https://github.com/gitpod-io/gitpod/blob/eed37839c4b1da0c9760dad40a27b7a81b5c1456/components/server/src/server.ts#L309-L310
https://github.com/gitpod-io/gitpod/blob/a1dc90b927c89524def92e7c542b90eaac1124fc/components/server/src/prometheus-metrics.ts#L28-L29
https://github.com/gitpod-io/gitpod/blob/a1dc90b927c89524def92e7c542b90eaac1124fc/components/server/src/prometheus-metrics.ts#L38-L39

Proposal: When https://github.com/gitpod-io/gitpod/pull/5843 is fixed, follow the "[how we develop](https://www.notion.so/gitpod/How-we-develop-e8ce7e562478458a9223eb9b797415b2#ad129cb2c9af4ac48620de4f51672931)" manual to add new graphs to the "[gitpod / components / server](https://grafana.gitpod.io/d/server/gitpod-component-server?orgId=1&refresh=30s)" dashboard.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5954#issuecomment-931180839):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by ArthurSens** [comment]
> During yesterdays incident we were on the wrong track for a while because connection counts are not surfaced in Grafana

Just wanted to point out that Grafana's Explore is always there for you to query metrics that are not shown in a dashboard 😬

**Comment by geropl** [comment]
@meysholdt Do we have a way now to add dashboards to Grafana from within the gitpod-io/gitpod repository? Or are we supposed to make the changes to the gitpod-io/ops repo? :thinking:

**Comment by laushinka** [comment]
I'll pick this up to learn the ropes.
