### ISSUE TITLE
Add integration test for workspace backup

### ISSUE THREAD

**Issue by rl-gitpod** [gitpod-io/gitpod#5970]
Once the refactoring #5572 is merged add a test for workspace backup #5751

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5970#issuecomment-934294348):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
