### ISSUE TITLE
[teams] Reword header to meed current features

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#5974]
<img width="495" alt="Screen Shot 2021-09-30 at 16 01 42" src="https://user-images.githubusercontent.com/914497/135579943-d1e95b5e-9e73-4783-a42f-a932734105a7.png">

We should leave out subscriptions for now and adjust link to the docs.

**Comment by gtsiolis** [comment]
Thanks for noticing and opening this @AlexTugarev! I'll pick up this minor issue! 🧺
