### ISSUE TITLE
Users don't understand how to change Git providers

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#5975]
We get several support requests because users don't understand how to change git providers.

**Common steps:**
- they try to log in with another Git provider than they used the first time.
- they get the error "Email address already exists. Log in using a different provider."
- they are confused and contact support. Some are thinking the solution is deleting the account and creating a new one. So we could assume that some do that without contacting support.

https://gitpod.io/integrations doesn't seem to be obvious

**possible solution:**
- adjust error message
- allow login with another git provider as well (similar to how Vercel is doing it)

cc @gtsiolis

**Comment by AlexTugarev** [comment]
> allow login with another git provider as well (similar to how Vercel is doing it)

@ChristinFrohne, do you have a story/description for that case?

**Comment by AlexTugarev** [comment]
@ChristinFrohne, I just checked with vercel. 

The thing is, they are storing any Login Connections on backend indefinitely, i.e. even if you disconnect once and try to login, they remember your previous connection and let you in.

**Comment by JanKoehnlein** [comment]
Sounds like we can only do 1) 

@gtsiolis can you provide us with a better error message?

/schedule

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5975#issuecomment-933542907):

>Sounds like we can only do 1) 
>
>@gtsiolis can you provide us with a better error message?
>
>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
