### ISSUE TITLE
Users don't know how to cancel their subscription

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#5976]
We get several support requests from users asking how they can cancel their subscription

**Possible issue:**
there is no `cancel subscription` button on https://gitpod.io/plans. The only way to cancel a subscription is to downgrade. But this doesn't seem to be obvious.

**Possible solution:**
Add a `cancel subscription` button that would automatically move the user to the open source plan. 

cc @gtsiolis

**Comment by gtsiolis** [comment]
@ChristinFrohne I'm closing this in favor of https://github.com/gitpod-io/gitpod/issues/4453 which links back to https://github.com/gitpod-io/gitpod/issues/3948#issuecomment-869453517 that suggests we add an action button for managing subscription as described in this issue.

Feel free to reopen this issue in case I'm missing something and this is not a duplicate but describes a different issue. 🏓 

Cross-posting from https://github.com/gitpod-io/gitpod/issues/4453#issuecomment-914315478:
> A good improvement here could be to a) separating teams and individual plans which are currently mixed and b) surfacing a more clear acton button for managing individual subscription as described in #3948 (comment). Cc @JanKoehnlein

Cross-posting from https://github.com/gitpod-io/gitpod/issues/4453#issuecomment-914352900:
> However, surfacing a more clear action to manage the subscription could be a small nice improvement.

**Comment by ChristinFrohne** [comment]
Great, thanks! Would it make sense to move #4453 back to the engineer inbox so we don't forget about it @gtsiolis ?

**Comment by gtsiolis** [comment]
@ChristinFrohne absolutely! Although we probably won't be able to take a closer look before the launch of teams and proejct next week. I've added #4453 to groundwork, feel free to add there any further comments. 🏓
