### ISSUE TITLE
users have multiple active plans without knowing

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/gitpod#5977]
We got a few support requests about users not understanding why they are billed for multiple subscriptions.

Issue: 
users have one active personal subscription and two active team subscriptions. After canceling one, they don't understand why they are keep being billed for it. 

Wouldn't it make sense to allow only one active subscription per user?
Could the UI reflect better which subscriptions are active?

**Comment by gtsiolis** [comment]
@ChristinFrohne the proposal in https://github.com/gitpod-io/gitpod/issues/3948#issuecomment-869453517 could also help here. WDYT?  💡 

Cross-posting below the design sepcs for visibility. Feel free to close any of these issues as duplicates and update the issue description with the proposal if it makes sense.

> | Plans without a team subscirption | Plans with a team subscirption |
> |-|-|
> | <img width="1440" alt="Plans" src="https://user-images.githubusercontent.com/120486/123598995-c236c880-d7fd-11eb-987e-7eeb63be614f.png"> | <img width="1440" alt="Plans-1" src="https://user-images.githubusercontent.com/120486/123598998-c367f580-d7fd-11eb-8b40-46dfe1abac61.png"> |

> See [design specs](https://www.figma.com/file/1sviSVuORjErWfUEOBH2cr/Improve-Plans-Individual-v.-Team-3948?node-id=0%3A1 ). 🎨

**Comment by ChristinFrohne** [comment]
The issue is still relevant. Are there any updates on the UI planned @gtsiolis ? :)

**Comment by JanKoehnlein** [comment]
This should be part of the aftermath of the team / team subscription alignment. I added it to the respective epic. We try to address that in this quarter.

**Comment by chrifro** [comment]
The issue still persists. cc @jankeromnes as you were working on updating the team subscription logic 🙂
