### ISSUE TITLE
Last prebuild timestamp is misaligned and breaks layout

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5978]
### Bug description

:a: The last prebuild timestamp is not aligned next to the branch name on the project cards. This was an issue since https://github.com/gitpod-io/gitpod/pull/5098.

:b: Also, back in https://github.com/gitpod-io/gitpod/pull/5961 where the last prebuild timestamp was updated it surfaced the state _a few seconds ago_ which breaks the card layout.

### Steps to reproduce

1. Add a project in personal account or a new team
2. Trigger a prebuild
3. Go to the projects page and notice the project cards

<img width="733" alt="Screenshot 2021-10-01 at 10 37 32 AM" src="https://user-images.githubusercontent.com/120486/135585156-5d47325c-4b2d-423d-a036-489e09d2f29a.png">

**Comment by gtsiolis** [comment]
Looking for a flexpert[[1](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox)] to help here!

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5978#issuecomment-937643572):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
