### ISSUE TITLE
Improve "gp open"

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#598]
Currently, we have terminal commands `gp open` and `gp preview`. I think they can be merged and improved. 

idea:
`gp open [flags] URL|FILE`

with flags:
`--browser` opens URL in new browser tab
`--preview-browser` opens a URL in the Preview View
`--editor` opens a FILE in an editor
`--preview-file` opens a FILE in the in preview-readonly-editor, the one that renders markdown.

If *no* flags are provided, the default should be:
```
if $0 is file {
   gp open --editor
} else {
  gp open --preview-browser
}
```

Also, when a URL is provided, the command should check if it's pointing to `localhost` or an internal Ip address and if so, re-write the URL to its public format with the logic of `gp url <port>`. This would solve https://github.com/gitpod-io/gitpod/issues/596.

On second thought, `gp open` and `gp preview` have no intersecting functionality, so it may be better to keep them separate commands. However, the terminology does overlap, because we have a "preview" for files (the markdown renderer). 

This could be solved by instead having the commands:
`gp open FILE` opens editor
`gp open --preview FILE` opens rendered markdown in read-only editor
`gp browse URL` opens preview view
`gp browse --external URL` opens URL in external browser window

**Comment by svenefftinge** [comment]
I like the idea to reuse open. Also we should not open non-localhost (or workspace) http URLs in preview as they are most likely don't work.

**Comment by meysholdt** [comment]
another idea: allow `gp open [flags] PORT` as a shortcut for `gp open [flags] $(gp url PORT)`.

While there is the unlikely possibility that a number is a valid port and a valid file, this ambiguity can be resolved by specifying one of the `[flags]` that we already have. When a flag is specified, it's clear if a number should be translated into a URL or FILENAME.

**Comment by meysholdt** [comment]
Should `gp open` also be able to focus folders/files in the File View?

I'd find this very useful when I navigated deep into some folder structure in the Terminal and want to continue in that context in the File View.

currently, I get 

```
gp open .
2019/06/14 06:57:14 /workspace/foobar/node_modules/@theia/php is a directory - can only open files`
```

**Comment by meysholdt** [comment]
Idea to use `gp open` also to open diffs: #678

**Comment by svenefftinge** [comment]
We have `gp preview` for opening a URL in the preview. We could support an optional argument to tell it should open in a new tab, but it would be prohibited by browser's pop up blocker. So not sure how useful that is.

So the other options to `gp open` it would be good to align with the options from `code` (see [here](https://code.visualstudio.com/docs/editor/command-line#_command-line-help))

**Comment by axonasif** [comment]
> 

I wonder if we can have something for opening files from `.gitpod.yml` in the same manner as with terminals. Please create a new issue if you also have something like that in your mind.
