### ISSUE TITLE
Add support for adding projects from Bitbucket.org git provider

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#5980]
### Problem to solve

In the first iteration of Teams & Projects we've added support for adding projects from GitLab.com and GitHub.com git providers.

![Screenshot 2021-11-22 at 00 00 56](https://user-images.githubusercontent.com/849592/142784411-78aaffaf-3cff-449e-b363-9e93819d6876.png)

### Proposal

The natural next step here is to add support for adding projects from Bitbucket.org git provider. 👣

**Comment by JanKoehnlein** [comment]
Given our current workload, I would not prioritize this ATM. Feel free to bring it up again

**Comment by aangelinsf** [comment]
I don't understand why there an option for bitbucket integration on the Integration pages if there is no way to add a project.

Is there a way to use BB that isn't obvious to use BB users?

**Comment by JanKoehnlein** [comment]
Sure, you can still prefix the repository URLs with `gitpod.io/#` or use the Gitpod browser extension to start workspaces on BitBucket repos. They also show up in the "Workspaces" list of your individual account as before. 

Just the new Teams and Projects UI doesn't work with BitBucket projects yet.

**Comment by jldec** [comment]
@AlexTugarev would you be able to give us an idea of how much work this is? That would help us to prioritize this relative to other work. Thanks.

**Comment by jldec** [comment]
Scope of effort is comparable with GitLab - see PR  https://github.com/gitpod-io/gitpod/pull/5120 
fyi - Bitbucket has introduced groups ==> even more like GitLab
