### ISSUE TITLE
Self hosted GitLab pull / push not possible - CA verification failure with workspace-full image 

### ISSUE THREAD

**Issue by davemecha** [gitpod-io/gitpod#5984]
### Bug description

Some problems working with my self hosted GitLab emerged.

Starting the workspace runs fine, so the repo is perfectly cloned. But when I try to pull or push, I get an error (and a warning, that is also new):

```
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: unable to access 'https://PATH_TO_MY_REPO.git/': server certificate verification failed. CAfile: none CRLfile: none
```

2 days ago I was able to work with the same repo without any problems. The GitLab instance is hosted on Google Cloud with letsencrypt certs. When I access the GitLab instance with my browser, there are no issues with the cert and the browser says the cert is valid. The admin did not change anything on the instance.

I found a [workaround](https://stackoverflow.com/a/21181447/2258093), but that’s obviously no long term solution and has to be done for each repo separately.

### Steps to reproduce

Unfortunately I can't provide reproduction steps, since it is a private GitLab instance, I'm not allowed to share here.

I tried to reproduce the problem with another GitLab instance but the cert error is not reproducible there. The warning is also occurring on GitHub repos.

**Comment by hm2075** [comment]
i see the same in self hosted gitpod together with self hosted gitlab

comes up with operation requires additional permissions,  read_repository even though it has been explicitly set

**Comment by AjXUthaya** [comment]
Same issue here, assuming it has something to do with [Let's Encrypt's Root Certificate is expiring!](https://scotthelme.co.uk/lets-encrypt-old-root-expiration/). Is there a simple workaround that we need to do or will this be fixed automatically after a patch?

**Comment by davemecha** [comment]
> Same issue here, assuming it has something to do with [Let's Encrypt's Root Certificate is expiring!](https://scotthelme.co.uk/lets-encrypt-old-root-expiration/). Is there a simple workaround that we need to do or will this be fixed automatically after a patch?

Yeah, I saw this too. As mentioned above, there is the [workaround](https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c/21181447#21181447) to allow all certificates for the domain. Unfortunately this a security issue.

I wonder whether the GitLab server needs to be updated somehow or if the problem needs to be fixed by GitPod.

**Comment by jimmybrancaccio** [comment]
I can confirm that running `sudo apt-get update && sudo apt-get -y upgrade` worked for me. I am using the `gitpod/workspace-mysql:latest`. There actually seems to be quite a lot of outdated packages at the moment.

```
The following packages will be upgraded:
  apt base-files binutils binutils-common binutils-x86-64-linux-gnu ca-certificates curl distro-info-data gcc-10-base git git-man icu-devtools
  imagemagick imagemagick-6-common imagemagick-6.q16 libapache2-mod-php8.0 libapt-pkg6.0 libargon2-1 libasound2 libasound2-data libatomic1
  libbinutils libcc1-0 libctf-nobfd0 libctf0 libcurl3-gnutls libcurl4 libcurl4-openssl-dev libdjvulibre-dev libdjvulibre-text libdjvulibre21
  libgcc-s1 libgcrypt20 libglib2.0-0 libglib2.0-bin libglib2.0-data libglib2.0-dev libglib2.0-dev-bin libgnutls30 libgomp1 libhogweed5 libicu-dev
  libicu66 libidn2-0 libitm1 libldap-2.4-2 libldap-common liblsan0 liblz4-1 libmagickcore-6-arch-config libmagickcore-6-headers
  libmagickcore-6.q16-6 libmagickcore-6.q16-6-extra libmagickcore-6.q16-dev libmagickcore-dev libmagickwand-6-headers libmagickwand-6.q16-6
  libmagickwand-6.q16-dev libmagickwand-dev libmysqlclient-dev libmysqlclient21 libnettle7 libopenexr-dev libopenexr24 libpam-modules
  libpam-modules-bin libpam-runtime libpam-systemd libpam0g libpcre16-3 libpcre2-16-0 libpcre2-32-0 libpcre2-8-0 libpcre2-dev libpcre2-posix2
  libpcre3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpolkit-agent-1-0 libpolkit-gobject-1-0 libpq-dev libpq5 libprocps8 libpython2.7-minimal
  libpython2.7-stdlib libpython3.8 libpython3.8-minimal libpython3.8-stdlib libquadmath0 libseccomp2 libssh-4 libssl-dev libssl1.1 libstdc++6
  libsystemd0 libtdb1 libtiff-dev libtiff5 libtiffxx5 libtsan0 libubsan1 libudev1 libwebp-dev libwebp6 libwebpdemux2 libwebpmux3 libx11-6
  libx11-data libx11-dev libxml2 libxml2-dev libzstd1 linux-libc-dev login openssh-client openssl passwd php-cli php-common php8.0 php8.0-bcmath
  php8.0-cli php8.0-common php8.0-curl php8.0-dev php8.0-gd php8.0-intl php8.0-mbstring php8.0-mysql php8.0-opcache php8.0-pgsql php8.0-readline
  php8.0-sqlite3 php8.0-xml php8.0-zip policykit-1 procps python-apt-common python2.7 python2.7-minimal python3-apt python3-distutils
  python3-lib2to3 python3-software-properties python3.8 python3.8-minimal software-properties-common systemd systemd-sysv systemd-timesyncd tzdata
  ubuntu-keyring vim vim-common vim-runtime wget xxd
```

**Comment by jimmybrancaccio** [comment]
For what it's worth the `workspace-full` image is still using the older `ca-certificates` package:

```
$ sudo apt list --installed |grep ca-certificates
ca-certificates/now 20210119~20.04.1 all [installed,upgradable to: 20210119~20.04.2]
```

**Comment by jldec** [comment]
Root cause gitpod-io/workspace-images#599

**Comment by webermax** [comment]
(sudo apt-get update && sudo apt-get -y upgrade indeed resolves it)

**Comment by appcoders** [comment]
@webermax  This is right. But the image should be updated by gitpod team regularly and not by every user.

**Comment by webermax** [comment]
@appcoders Sure :+1:  (how long?)

In the meantime one can very easy work around this via .gitpod.Dockerfile:

```dockerfile
FROM gitpod/workspace-base

RUN sudo apt-get update && sudo apt-get install ca-certificates
```

**Comment by kylos101** [comment]
Hey there, we're testing a new version of the `workspace-full` image, and should have it ready to ship soon. We're also planning to regularly rebuild a layer or chunk that'll keep ca-certificates up-to-date. Thank you for the feedback!

**Comment by kylos101** [comment]
Hey there, this is being tracked in https://github.com/gitpod-io/workspace-images/issues/599, as such, I will close this issue (its duplicate). 

Also, you're welcome to use this image:
`gitpod/workspace-full:2022-01-28-21-33-52`

We haven't tagged it latest (yet), but will very soon.
