### ISSUE TITLE
Extensions management

### ISSUE THREAD

**Issue by hm2075** [gitpod-io/gitpod#5995]
Self hosted 0.10 -nightly

extensions are not stored locally,  only a reference to the open vsx entry exists in storage

upon creation of new workspaces,  extensions are re-downloaded to user's workspace,   the version is not maintained and users are updated to the latest version of those extensions.   Developers may require certain versions of the extension due to compatibility issues.

**Comment by hm2075** [comment]
"extensions.autoUpdate": false 

didnt know u could do that

**Comment by akosyakov** [comment]
sounds like a dup of https://github.com/gitpod-io/gitpod/issues/5856
