### ISSUE TITLE
Check Browser Version

### ISSUE THREAD

**Issue by TristanFAURE** [gitpod-io/gitpod#60]
**Describe the bug**
using a workspace on palantir/tslint (example : c991da63-82a3-473a-9897-b33c5f8fb4e5.ws-eu.gitpod.io) typescript files are not coloured and there are no auto completion

**To Reproduce**
workspace with palantir/ts, open a ts file, the file is displayed in a basic editor

**Expected behavior**
Syntaxic coloration and auto completion

**Comment by akosyakov** [comment]
@TristanFAURE Hi, I've just tried and I can get content assist:
![contentassist](https://user-images.githubusercontent.com/3082655/45079539-1aebc280-b0f3-11e8-8850-39624c09fedc.gif)

Could you clarify which file you are trying to edit? Also, did you run yarn before? It could be that dependencies are missing and tsserver cannot provide items for them. Does it behave differently in VS Code?

I've found that editorconfig extension is bogusly format a file: https://github.com/theia-ide/theia/issues/2778 Will have a look at it.

**Comment by TristanFAURE** [comment]
Yes I have run yarn 
I tried to open the file in your capture, It is plain text with white text and no colors

Yes it behaves differently in VS Code

**Comment by akosyakov** [comment]
Can you report a bit about your environments, i.e. browser, does it support WASM?

**Comment by TristanFAURE** [comment]
Yes sorry, for information I tried a java workspace and everything worked fine
Firefox 52.1.2 (32 bits)

**Comment by svenefftinge** [comment]
Hi Tristan, thanks for reporting it. the issue is that your version of Firefox is too old.
We will have to add a check, to tell users.
Can you update your browser?

**Comment by TristanFAURE** [comment]
Actually no because it is the browser at my office. 
The most disturbing point is that other languages work like java

**Comment by svenefftinge** [comment]
> The most disturbing point is that other languages work like java

It might be that we have fall-back coloring for Java but not for TypeScript. But the 'good' coloring requires WASM, which is not supported by your browser version.

**Comment by TristanFAURE** [comment]
Ok thank you !
