### ISSUE TITLE
Subfolder instead of subdomain

### ISSUE THREAD

**Issue by dominik4545** [gitpod-io/gitpod#6003]
Dear gitpod-team,

I wanted to use your self-hosted environment and would be very happy if you would support subfolders (e.g. https://ide.mydomain.com/ws/asdf) instead of subdomains (e.g. https://asdf.ws.ide.mydomain.com).

Could you please think of this feature? It would help me (and maybe others as well) :)

Thanks & best regards,
Dominik

**Comment by konne** [comment]
Hi, 

this would also solve the auth0 problem here: https://community.gitpod.io/t/auth0-and-gitpod/2392 if you would support that also for your gitpod provided service.

If you search with auth0 in the issue you will find another two more with the same problem, which could be then solved.

bye

**Comment by dominik4545** [comment]
> If you search with auth0 in the issue you will find another two more with the same problem, which could be then solved.
good to hear, that I am not the only one with this issue - which leads me to the point, that this feature becomes more priority? ;)
