### ISSUE TITLE
gitpod.io fails to build Eclipse Jersey

### ISSUE THREAD

**Issue by mkarg** [gitpod-io/gitpod#601]
**Describe the bug**
gitpod.io fails to build Eclipse Jersey, while all other environments and IDEs, including Jenkins and Travis, can build it without problem

**To Reproduce**
* https://gitpod.io/#https://github.com/eclipse-ee4j/jersey
* In the console, type `mvn -DskipTests=true clean install`

**Expected behavior**
Maven reports success.

**Actual behavior**
Maven reports compilation failures.

**Comment by meysholdt** [comment]
Hi Markus,

I tried...
**Attempt 1:**
* as you said. 
* `mvn` suddenly dies with `Killed` being the last output in the terminal. The Kernel's Out-Of-Memory-Counter increased to 1.

**Attempt 1:**
1. open new workspace
2. stop the Java Language Server (press CMD+SHIFT+P for commands and search "java")
3. run `git clean -xfd` to remove everything the language server has produced. 
4. run `mvn -DskipTests=true clean install`
5. I get 
```
INFO] jersey-examples-system-properties .................. SUCCESS [  0.672 s]
[INFO] jersey-examples-moxy ............................... SUCCESS [  0.684 s]
[INFO] jersey-test-framework-maven-custom-enforcer-rules .. SUCCESS [  1.071 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:55 min
[INFO] Finished at: 2019-05-31T16:29:32Z
[INFO] ------------------------------------------------------------------------
```

:-D

Hypothesis: Both the Language Server and Maven are JVMs, both configured to use the max memory available in the workspace container. And that, well, doesn't work.

Not sure yet what's the best strategy to deal with this
a) reduce memory per JVM
b) run only one JVM at a time
c) make more memory available

**Comment by svenefftinge** [comment]
> Hypothesis: Both the Language Server and Maven are JVMs, both configured to use the max memory available in the workspace container. And that, well, doesn't work.

If that was the case no maven or gradle build would work. Couldn't it be that there was just too much memory consumed (i.e. really consumed not just reserved by the JVM)?

**Comment by meysholdt** [comment]
yes, certainly a lot of memory was consumed. It's a large repo. It's quite likely that both JVMs tried to max out their `-Xmx` (max memory) setting. I didn't check if any JVM had `-Xms` (initially reserved memory) configured.

**Comment by svenefftinge** [comment]
Tested and worked in our staging environment.

**Comment by svenefftinge** [comment]
deployed

**Comment by mkarg** [comment]
Thanks a lot! :-)
