### ISSUE TITLE
Not able to make ports public

### ISSUE THREAD

**Issue by Kaushik-Kalesh** [gitpod-io/gitpod#6019]
### Bug description

I tried making ports of my web servers public in my gitpod workspace (like I do everyday for testing) But now the button (in Remote Explorer) to make it public (Make Public) doesn't seem to be working. Also, I am getting this error in the notifications (`Error running command gitpod.ports.makePublic: Running the contributed command: 'gitpod.ports.makePublic' failed.. This is likely caused by the extension that contributes gitpod.ports.makePublic.`)

### Steps to reproduce

1) Open a gitpod workspace,
2) Go to Remote Explorer
3) Then try to make a port public

### Expected behavior

I should be able to make ports public 

### Anything else?

Hope to get this fixed asap

**Comment by corneliusludmann** [comment]
Is it just a specific workspace that is affected? If yes, could you please provide the workspace ID?

I tried it with a fresh workspace and I'm not able to reproduce the problem.
