### ISSUE TITLE
[self-hosted] Support for Docker 20.10

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#6021]
This issue is to track the required changes to make Docker 20.10 work for self-hosted installation. It was fixed in production and reported in issue https://github.com/gitpod-io/gitpod/issues/3051 but does not work for self-hosted (yet).

Error when running Docker 20.10 on Gitpod 0.10.0
```
$ docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted: unknown.
ERRO[0003] error waiting for container: context canceled
```

Current workaround is to downgrade to Docker 19.03. This can be done with the following custom workspace image
```Dockerfile
FROM gitpod/workspace-full

RUN sudo apt-get update && sudo apt-get purge -y \
         docker-ce \
         docker-ce-cli \
         containerd.io && \
    sudo apt-get install -y \
         docker-ce=5:19.03.15~3-0~ubuntu-focal \
         docker-ce-cli=5:19.03.15~3-0~ubuntu-focal && \
    sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/* && \
    sudo curl -fsSL -o /usr/bin/runc https://github.com/opencontainers/runc/releases/download/v1.0.0-rc93/runc.amd64
```
Thanks to @asthomasdk for posting this workaround on Discord.

**Comment by MasonM** [comment]
I ran into this issue too on EKS, but the workaround didn't seem to work. This seems to be the same bug as https://github.com/gitpod-io/gitpod-eks-guide/issues/25

**Comment by jgallucci32** [comment]
@MasonM Try adding this to your answers.yaml for the chart
```yaml
defaults:
  dnsPolicy: ClusterFirstWithHostNet
```
I added this some time ago to the self-hosted install on RKE to address the issue with NodePorts and HostPorts and incorrect DNS resolution. Not sure if it is related, but I thought it might be worth a try.
