### ISSUE TITLE
Trying to open repo and get error/warning Limit Reached and asked to upgrade??

### ISSUE THREAD

**Issue by Mjboothaus** [gitpod-io/gitpod#6024]
### Bug description

Trying to open repo and get error/warning to upgrade??

### Steps to reproduce

Trying to open the following in Safari - Version 15.0 (16612.1.29.41.4, 16612) / macOS Big Sur 11.6

https://gitpod.io/#https://github.com/DataBooth/data-beach

and it is failing with the following error screen shot (it used to work 4 weeks ago on Safari) and I tested in Chrome and it works fine (as expected).

![Screen Shot 2021-10-05 at 6 38 10 am](https://user-images.githubusercontent.com/956433/135914218-eced8a1b-08c5-42b5-9e12-e87d1406ab3d.png)

### Expected behavior

See above

### Example repository

https://github.com/DataBooth/data-beach

### Anything else?

Keep up the great work!

**Comment by gtsiolis** [comment]
Hey @Mjboothaus! Could not reproduce this with a private repository on GitHub.com. Are you sure there no typo in the example repository you linked in the issue description? 💭

**Comment by Mjboothaus** [comment]
Thanks George — I was doing it 5am local time - so will retest & report back
