### ISSUE TITLE
[local app} Add an option to regenerate SSH configuration

### ISSUE THREAD

**Issue by ajhalili2006** [gitpod-io/gitpod#6032]
## About this Issue

In the current situation where the Gitpod Remote extension jsut modifies `remote.SSH.configFile` (which is currently there's no Windows or Linux-specific way to configure it, lemme find that issue in `Microsoft/vscode-remote-release` repo) instead of dumping configuration to `~/.ssh/config`, sometimes that configuration in `/tmp` directory (`%USERPROFILE%\AppData\Local\Temp` in Windows) can either get deleted by the local-companion app, the user itself as do some cleanup or worst some process who just do `rm -rfv /tmp`.

In case the config is probably erased or borked, I should have the option to regenerate the contents of config file as possible, through an option in Command Palette to re-add SSH configuration back.

## Possibly Related Issues

* https://github.com/gitpod-io/gitpod/issues/5767
* https://github.com/gitpod-io/gitpod/issues/5889

**Comment by akosyakov** [comment]
Is not it a dup of https://github.com/gitpod-io/gitpod/issues/5889 The answer is the same like here https://github.com/gitpod-io/gitpod/issues/5889#issuecomment-928932036 We should not override `remote.SSH.configFile`.

**Comment by ajhalili2006** [comment]
Closing due to https://github.com/gitpod-io/gitpod/issues/6032#issuecomment-934158867 and to be nice to stale-bot.
