### ISSUE TITLE
brew update in running workspace kills the workspace

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#6033]
### Bug description

If I open any even a nearly empty repo and put into the terminal:

`brew update`
It prints out some lines and then just stopping the workspace. Example in your logs. 05/10/21 08:29 CET

![image](https://user-images.githubusercontent.com/1100969/135971777-263184e8-245a-42eb-8c1f-73267606a1b5.png)

bye

### Steps to reproduce

see desc

**Comment by princerachit** [comment]
Hi please refer to the duplicate issue which is awaiting deployment https://github.com/gitpod-io/gitpod/issues/5280
