### ISSUE TITLE
Team member count is missing for some users

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#6035]
### Bug description

In some cases, the team scope selector dropdown cannot surface the team count. See also [relevant discussion](https://gitpod.slack.com/archives/C021Q4BL8E8/p1629112257217400) (internal).

<img width="346" alt="teams-missing-count-issue" src="https://user-images.githubusercontent.com/120486/135982308-abeb8300-aaa1-42b2-abc6-ffbd1da5db94.png">

Also, the following console error pops-up every time you load the dashboard:

```js
Uncaught (in promise) Error: Request getTeamMembers failed with message: No identity with primary email for user: AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEE!
```

### Steps to reproduce

N/A

**Comment by jankeromnes** [comment]
Many thanks for filing this issue @gtsiolis! I can take a look at this.

**Comment by jankeromnes** [comment]
@gtsiolis I notice that you've censored out the user ID. Could you please share it? (I wonder if this has something to do about a member in one of your teams deleting their account...)

**Comment by gtsiolis** [comment]
@jankeromnes the user ID is visible in the linked discussion above, see [relevant message](https://gitpod.slack.com/archives/C021Q4BL8E8/p1629112265217500?thread_ts=1629112257.217400&cid=C021Q4BL8E8) (internal).

**Comment by jankeromnes** [comment]
@gtsiolis Thanks! I can confirm that this user has since been deleted.

I believe we should chain-delete all team memberships when a user account is deleted.

Also, maybe it's a good idea to make the Teams UI more resilient to errors (i.e. don't break all your Team pages when a single member in one of your teams throws an error).

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6035#issuecomment-934221580):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
