### ISSUE TITLE
Cannot switch between team projects

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#6037]
### Bug description

In the latest deployment, I can not switch between or browse any team pages including Projects, Workspaces, etc. The menu does to get updated and every tab links back to the personal account.

| Personal Account | Team |
|-|-|
| <img width="386" alt="scope-1" src="https://user-images.githubusercontent.com/120486/135983268-7e32567b-491f-4ce2-b05c-e5fbf9553f3e.png"> | <img width="386" alt="scope-2" src="https://user-images.githubusercontent.com/120486/135983271-bf2fef33-8835-4582-b7f4-4214bacb0c60.png"> |

### Steps to reproduce

N/A

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6037#issuecomment-934220881):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jankeromnes** [comment]
This is another symptom for the same underlying problem of https://github.com/gitpod-io/gitpod/issues/6035 (fixed in https://github.com/gitpod-io/gitpod/pull/6041)
