### ISSUE TITLE
Too many workspaces running when i have no one running

### ISSUE THREAD

**Issue by diessetechnology** [gitpod-io/gitpod#604]
**Describe the bug**
Pratically i have created and deleted too quickly some workspaces and now says:

Too many running workspaces
Error: You cannot run more than 8 workspaces at the same time. Please stop a workspace before starting another one.

![issue](https://user-images.githubusercontent.com/47757505/58768509-a8821300-859c-11e9-85f7-c5d2b652190c.png)

**To Reproduce**
Create and delete some workspace in few seconds...

**Expected behavior**
Deleted workspaces shall not be counted as running workspaces

**Comment by diessetechnology** [comment]
Ok...seems the problem is now gone away,but remains strange...
I have waited an hour before the problem have disappeared...

**Comment by meysholdt** [comment]
There was a major [network outage in google cloud](https://status.cloud.google.com/incident/cloud-networking/19009), but now all systems are back to normal.

**Comment by justinmoon** [comment]
I'm having that problem right now. `https://gitpod.io/workspaces/` shows 1 workspace running, and another "off". I've been creating and destroying workspaces furiously fighting my .bashrc so it's partially my fault! :wink:
