### ISSUE TITLE
Error “The process tried to write to a nonexistent pipe.” When openning with VSCode Desktop

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [gitpod-io/gitpod#6040]
### Bug description

When I click open on VSCode Desktop it shows “The process tried to write to a nonexistent pipe.” 

### Steps to reproduce

1) Click Open on VSCode Desktop
2) Allow site to open vscode3
3) When VSCode opens it asks for operating system and I click linux. ( Have also tried mac and windows )
4) Error

### Expected behavior

Connect to GitPod and work as a project

### Anything else?

I have already installed the extension that is asked.
Here is the log:

**Comment by akosyakov** [comment]
Could you attach logs please? They were helpful, there was something about broken permissions for a file which we generate.

**Comment by GalaxyGamingBoy** [comment]
> Could you attach logs please? They were helpful, there was something about broken permissions for a file which we generate.

https://pastebin.com/y25MjaUb

**Comment by akosyakov** [comment]
Which operating system is installed on your machine?

**Comment by GalaxyGamingBoy** [comment]
> Which operating system is installed on your machine?

Windows

**Comment by akosyakov** [comment]
> Windows

Windows 10 or 11?

**Comment by GalaxyGamingBoy** [comment]
> > Windows
> 
> Windows 10 or 11?

10
