### ISSUE TITLE
Rename "Workspaces" to "My Workspaces" in Team pages

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#6045]
Currently, Team menus have these pages:
- Projects (of the entire team)
- Workspaces (of just you)
- Members (of the entire team)
- Settings (of the entire team)

As you can see, Workspaces is the only one that is special (they're not the Workspaces of the entire team, just your own Workspaces for Projects that happen to be in the Team).

Hence, it would make the UI less confusing to call the tab & page "My Workspaces" instead of just "Workspaces".

---

For users, we could also call them "My Workspaces", even if "Workspaces" isn't really ambiguous. Just for consistency.

**Comment by jldec** [comment]
Yes please - I would suggest doing this for both teams and users to help reinforce the idea that workspaces are always something you create and "own" for yourself, and only share under special circumstances.
