### ISSUE TITLE
[ws-scheduler] ws-scaler has wrong ghost count

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6056]
ws-scaler's state on how many ghosts we have running is wrong.
See [monitoring](https://grafana.gitpod.io/explore?orgId=1&left=%5B%221632846602029%22,%221633451062446%22,%22VictoriaMetrics%22,%7B%22exemplar%22:true,%22expr%22:%22gitpod_ws_scaler_driver_setpoint%7Bcluster%3D%5C%22prod-ws-us18%5C%22%7D%22,%22hide%22:true%7D,%7B%22exemplar%22:true,%22expr%22:%22gitpod_ws_scaler_ghost_count%7Bcluster%3D%5C%22prod-ws-us18%5C%22%7D%22,%22hide%22:false%7D,%7B%22exemplar%22:true,%22expr%22:%22sum(gitpod_ws_manager_workspace_phase_total%7Bcluster%3D~%5C%22prod-ws-us18%5C%22,%20type%3D%5C%22GHOST%5C%22,%20phase%3D%5C%22RUNNING%5C%22%7D)%20by%20(phase)%22%7D%5D) for an example

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6056#issuecomment-934557339):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
