### ISSUE TITLE
Ability to make terminal full screen

### ISSUE THREAD

**Issue by tailuge** [gitpod-io/gitpod#606]
Double clicking the tab (like in eclipse) should make any window full area/screen.

**Comment by AlexTugarev** [comment]
This feature was [merged](https://github.com/theia-ide/theia/pull/4744) in Theia recently and will land in Gitpod soon 🎉 
Right, @akosyakov?

**Comment by tailuge** [comment]
Great - happy to close out the issue then.

**Comment by jankeromnes** [comment]
The fix was since deployed to production, and double-clicking on a Terminal tab handle works great! 🎉
