### ISSUE TITLE
Sort projects by activity

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#6062]
Currently, the projects on the projects list don't seem to be ordered. 
I think they should be ordered by the least recent activity.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6062#issuecomment-935897597):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
