### ISSUE TITLE
Cannot fetch branches, trigger prebuilds, and configure projects in a subgroup for GitLab

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#6068]
### Bug description

This prevents users from a) loading branches for a project, b) triggering prebuilds from the dashboard, and c) configuring the project from the dashboard.

🅰️  No error or feedback is returned when trying to load projects branches.

🅱️  The following error is returned in the browser console when trying to trigger a prebuild from the prebuilds page or the configuration page:

```js
Error: Could not find a default branch in repository
```

| Branches | Configuration |
|-|-|
| <img width="1123" alt="Screenshot 2021-10-06 at 3 51 48 PM" src="https://user-images.githubusercontent.com/120486/136207421-390752a3-a8ef-466b-bdd8-ceda8ca1513f.png"> | <img width="1112" alt="Screenshot 2021-10-06 at 3 51 09 PM" src="https://user-images.githubusercontent.com/120486/136207426-cc3998df-91b7-4866-8f50-16b296a0a87c.png"> |

### Steps to reproduce

Create a project in a subgroup at GitLab.com and try adding this as a project in Gitpod.io.

**Comment by jwaldrip** [comment]
Running into this as well. :-( without prebuilds, spinning things up is rather slow.
