### ISSUE TITLE
Shutdown tasks

### ISSUE THREAD

**Issue by justinmoon** [gitpod-io/gitpod#607]
There doesn't seem to be a way to run scripts on container shutdown. I was running a database that was corrupted between restarts. I assume the process must have been killed before it could properly shutdown, but am not sure.

It would be nice if I could run a little bash script on shutdown that could gracefully stop this service.

**Comment by justinmoon** [comment]
I tried adding a script as a `CMD` in the dockerfile which could trap kill signals. 

It works locally (to test I change the `CMD` to run a script that just prints on a loop: `while true; do echo "hello"; sleep 1; done`)

But when I attempt to build a GitPod workspace I get an error: `Error while adding GitPod layer`

I mention this because I'm happy to use a hack like this for a while, but I just can't figure out how to get it to work ...

**Comment by meysholdt** [comment]
Hi Justin! 

Thx for bringing this up. Your `demo` link, unfortunately, is a 404. 

I agree that it makes sense to have shutdown hooks. Using traps seems like a good workaround. 

Can you say which database you used and which command the database would have required to run for a clean shutdown?

**Comment by gjsjohnmurray** [comment]
I too have a case where I'd like to run a command during container stop, so I can close down a database cleanly and avoid recovery steps being triggered on subsequent container start.

**Comment by chlbri** [comment]
Yes it will be nice

**Comment by svenefftinge** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/3966
