### ISSUE TITLE
active workspace is not shown if repo belongs to a project

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6071]
### Bug description

I have a running workspace `azure-manatee-c68g905h`, but I cannot find among workspaces in the dahsboard.

### Steps to reproduce

(at:) as a user which is NOT a member of a team A do the following
1. create a workspace for a repo which is set up as a project of team A
2. see the workspace running
3. go to gitpod.io/workspaces and see no active workspace

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6071#issuecomment-936299953):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
