### ISSUE TITLE
Suppressing notifications using port ranges does not work

### ISSUE THREAD

**Issue by chuck-confluent** [gitpod-io/gitpod#6078]
### Bug description

See https://github.com/gitpod-io/gitpod/issues/1484

### Steps to reproduce

See https://github.com/gitpod-io/gitpod/issues/1484 and for another example, see https://github.com/confluentinc/cp-demo/pull/390/files/e0fe5903a9ab2ff439abb262554238058d97c9ac#r723075729

### Expected behavior

`onOpen: ignore` should work for port ranges. Instead, you have to set ignore on individual ports.

### Example repository

https://github.com/confluentinc/cp-demo/pull/390/files/e0fe5903a9ab2ff439abb262554238058d97c9ac#r723075729

**Comment by akosyakov** [comment]
dup of https://github.com/gitpod-io/gitpod/issues/5929
