### ISSUE TITLE
eMail identity does not reflect my primary GitHub eMail address 

### ISSUE THREAD

**Issue by MarkusTiede** [gitpod-io/gitpod#608]
**Describe the bug**
After changing my primary GitHub eMail address newly created worspaces do not reflect this. 

I've stopped and also delete all (even archived) workspaces I had so far.

**To Reproduce**
Use eMail-A as primary adress on GH - create gitpod workspace instance
Change to eMail-B as primary adress on GH - create gitpod workspace instance
--> eMail-A is still used.

**Expected behavior**
eMail-B would b e used

**Comment by AlexTugarev** [comment]
Hi @MarkusTiede! We currently update the primary email on each login to Gitpod. Just checked it works properly after re-login any newly started workspace is aware of this change, e.g. `git config --all` and the git sign-off feature show the changed email.

**Comment by MarkusTiede** [comment]
It's been a while and it's no longer occurring - resolving accordingly "worksforme(now)".
