### ISSUE TITLE
Add extensions to .gitpod.yml by default when installing them

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#6093]
Today I discovered the “add to .gitpod.yml” context menu by accident. Can we hook the installation feature, remove the “add to .gitpod.yml” context menu and instead add the extension to the .gitpod.yml by default?

![009D647D-001F-4397-8E3E-7C5E494CBC40](https://user-images.githubusercontent.com/127353/136315616-b0b4eac3-bf49-4630-b213-5081b9490f4e.png)

**Comment by akosyakov** [comment]
I think we discussed it in the past and decided that installing extension and adding to .gitpod.yml are 2 different things. The same way like running apt-get and adding it to Dockerfile. Instead we added a validation to .gitpod.yml to show if some extensions are installed as no sync but missing in .gitpod.yml. cc @svenefftinge @loujaybee 

Besides that we don't take new feature requests for now.
