### ISSUE TITLE
YO generator not working

### ISSUE THREAD

**Issue by GuzioMG** [gitpod-io/gitpod#610]
**Describe the bug**

OK, so I wanted to start a new VS code extension project in GitPod. I know, I couldn't debug it anyway, but I like GitPod and wanted to keep most development actions there. However, when I launched mnp, than I got an error saying, it's not installed. After a few tries later, I noticed, that it's npm, not mnp. So I installed Yeoman. And It's not working! Then, I installed vsCode SDK and decided to launch yeoman with the generation task already set. And guess what. It's not working, too!

**To Reproduce**

Actually, there is nothing to reproduce. Just look at me desperately trying to generate vsCode boilerplate. No matter, what I do (global installation, private installation; yo, yeoman-doctor, yo-doctor; with vsCode SDK and without), I ALWAYS get the same error. So, here is the log. I know, that no one likes walls of text (with MD, which is definitely not helping), but there is probably no other way. But look:
`gitpod /workspace/McIDE.js $ nmp`
`bash: nmp: command not found`
`gitpod /workspace/McIDE.js $ node.js`
`bash: node.js: command not found`
`gitpod /workspace/McIDE.js $ node`
`> nmp`
`ReferenceError: nmp is not defined`
`> exit`
`ReferenceError: exit is not defined`
`> exit()`
`ReferenceError: exit is not defined`
`>`
`(To exit, press ^C again or type .exit)`
`> .exit`
`gitpod /workspace/McIDE.js $ npm`
`Usage: npm <command>`
`where <command> is one of:`
`access, adduser, audit, bin, bugs, c, cache, ci, cit, completion, config, create, ddp, dedupe, deprecate, dist-tag, docs, doctor, edit, explore, get, help, help-search, hook, i, init, install, install-test, it, link, list, ln, login, logout, ls, outdated, owner, pack, ping, prefix, profile, prune, publish, rb, rebuild, repo, restart, root, run, run-script, s, se, search, set, shrinkwrap, star, stars, start, stop, t, team, test, token, tst, un, uninstall, unpublish, unstar, up, update, v, version, view, whoami`
`npm <command> -h  quick help on <command>`
`npm -l            display full usage info`
`npm help <term>   search for help on <term>`
`npm help npm      involved overview`
`Specify configs in the ini-formatted file: /home/gitpod/.npmrc or on the command line via: npm <command> --key value`
`Config info can be viewed via: npm help config`

`npm@6.4.1 /home/gitpod/.nvm/versions/node/v10.15.3/lib/node_modules/npm`
`gitpod /workspace/McIDE.js $ yo`
`bash: yo: command not found`
`gitpod /workspace/McIDE.js $ npm install -g yeoman-doctor`
`npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead`
`/home/gitpod/.nvm/versions/node/v10.15.3/bin/yodoctor -> /home/gitpod/.nvm/versions/node/v10.15.3/lib/node_modules/yeoman-doctor/lib/cli.js`
`+ yeoman-doctor@3.0.3`

> OK, it's taking WAAAY to long to add `` tag everywhere... Enjoy wall of text!

added 70 packages from 30 contributors in 3.105s
gitpod /workspace/McIDE.js $ yo
bash: yo: command not found
gitpod /workspace/McIDE.js $ npm install yeoman-doctor
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN saveError ENOENT: no such file or directory, open '/workspace/McIDE.js/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/workspace/McIDE.js/package.json'
npm WARN McIDE.js No description
npm WARN McIDE.js No repository field.
npm WARN McIDE.js No README data
npm WARN McIDE.js No license field.

+ yeoman-doctor@3.0.3
added 70 packages from 30 contributors and audited 90 packages in 1.576s
found 0 vulnerabilities

gitpod /workspace/McIDE.js $ yo
bash: yo: command not found
gitpod /workspace/McIDE.js $ node yo
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/workspace/McIDE.js/yo'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
gitpod /workspace/McIDE.js $ cd node_modules/
gitpod /workspace/McIDE.js/node_modules $ node yo
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/workspace/McIDE.js/node_modules/yo'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
gitpod /workspace/McIDE.js/node_modules $ yeoman-doctor
bash: yeoman-doctor: command not found
gitpod /workspace/McIDE.js/node_modules $ node yeoman-doctor
gitpod /workspace/McIDE.js/node_modules $ node yodoctor
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/workspace/McIDE.js/node_modules/yodoctor'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
gitpod /workspace/McIDE.js/node_modules $ node yeoman-doctor
gitpod /workspace/McIDE.js/node_modules $ node yeoman-doctor help
gitpod /workspace/McIDE.js/node_modules $ node yeoman-doctor code
gitpod /workspace/McIDE.js/node_modules $ yeoman-doctor code
bash: yeoman-doctor: command not found
gitpod /workspace/McIDE.js/node_modules $ ./yeoman-doctor code
bash: ./yeoman-doctor: Is a directory
gitpod /workspace/McIDE.js/node_modules $ yo
bash: yo: command not found
gitpod /workspace/McIDE.js/node_modules $ cd ..
gitpod /workspace/McIDE.js $ npm install generator-code
npm WARN saveError ENOENT: no such file or directory, open '/workspace/McIDE.js/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/workspace/McIDE.js/package.json'
npm WARN McIDE.js No description
npm WARN McIDE.js No repository field.
npm WARN McIDE.js No README data
npm WARN McIDE.js No license field.

+ generator-code@1.1.50
added 356 packages from 277 contributors and audited 2666 packages in 14.374s
found 0 vulnerabilities

gitpod /workspace/McIDE.js $ ./yeoman-doctor code
bash: ./yeoman-doctor: No such file or directory
gitpod /workspace/McIDE.js $ cd node_modules/
gitpod /workspace/McIDE.js/node_modules $ node yeoman-doctor code
gitpod /workspace/McIDE.js/node_modules $ node yo
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/workspace/McIDE.js/node_modules/yo'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
gitpod /workspace/McIDE.js/node_modules $ node yo code
internal/modules/cjs/loader.js:584
    throw err;
    ^

`Error: Cannot find module '/workspace/McIDE.js/node_modules/yo'`
`    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)`
`    at Function.Module._load (internal/modules/cjs/loader.js:508:25)`
`    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)`
`    at startup (internal/bootstrap/node.js:283:19)`
`    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`
`gitpod /workspace/McIDE.js/node_modules $`

**Expected behavior**

Well, I guess, it's logic, right? I expect this to work. I just need to add this paragraph, because it's in the issue template. Anyway, this bug is not a big deal for me since I can generate boilerplate locally and then upload it, but generally, this bug is worth posting somewhere, so you can fix it.

**Comment by meysholdt** [comment]
Hi Guzio!

thank you for bringing this up. I parsed through your wall of text and now I want to try myself:

1. open https://gitpod.io/#https://github.com/GuzioMG/McIDE.js
2. in terminal, type [`npm install -g yo`](https://yeoman.io/learning/)
3. in terminal, type `$ yo --help` and I get 

```
Usage: yo GENERATOR [args] [options]

General options:
  --help         # Print this info and generator's options and usage
  -f, --force    # Overwrite files that already exist
  --version      # Print version
  --no-color     # Disable colors
  --[no-]insight # Toggle anonymous tracking
  --generators   # Print available generators

Install a generator:

  Generators can be installed through npm.

  $ npm install generator-angular
  $ yo angular --help

Run local generators:

  Additionally, you can also run local generators without installing via npm.

  $ yo ./path/to/some/generator

Completion:

  To enable shell completion for the yo command, try running

  $ yo completion

Troubleshooting:

  For any issues, try running

  $ yo doctor

Full Documentation: http://yeoman.io

Available Generators:

  Couldn't find any generators, did you install any? Troubleshoot issues by running

  $ yo doctor
```

This seems to work and should be perfectly fine to scaffold a new project (vs code extension?). 

After restarting the workspace, however, `yo` will be gone again because `npm -g` installs it outseide the `/workspace` folder. To have `yo` available permanently, you'll need to install it via Dockerfile.

does this solve what you wanted to do? let me know :)

**Comment by svenefftinge** [comment]
@GuzioMG I will close this for now. Happy to reopen if there is something to do for us. Just let us know.

**Comment by GuzioMG** [comment]
Thank you so much for help. Actually, I arleady generated it on my local PC. I'm just curious about one thing: why do I need to install yo package and not yeoman-doctor? Isn't it the same? I'm not reopening, since issue is fixed (thank you again), but it's just typical human curiosity.

**Comment by meysholdt** [comment]
you're welcome! 

I have to admit I don't know the differences between the packages `yo` and `yeoman-doctor`, I just followed the instructions from https://yeoman.io/learning/

**Comment by GuzioMG** [comment]
Thanks!
