### ISSUE TITLE
Select Running Workspace doesn't work

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#6119]
### Bug description

When you start a workspace for a context where you already have a workspace running, clicking on the running workspace doesn't work (it takes you back to dashboard)

### Steps to reproduce

1. Start a workspace for a context
2. Start another workspace for the same context
3. In the "Select Running Workspace" pop-up, try to open the already-running workspace

### Expected behavior

It should open the running workspace (not go back to dashboard)

**Comment by gtsiolis** [comment]
Could not reproduce this. 🤷

**Comment by jankeromnes** [comment]
Hmm, I know this happened to me in the past, but I also couldn't reproduce it just now. 🤔

**Comment by JanKoehnlein** [comment]
Cannot reproduce either.
