### ISSUE TITLE
Make project order stable

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#6121]
The project sorting needs to be stable currently one can watch projects jumping around when loading because information needed is fetched asynchronously. Maybe getting the projects sorted from the backend is the way to go.

https://user-images.githubusercontent.com/372735/136544025-6d9546c0-fcbe-4fac-87ac-25d201704846.mov

follow up of https://github.com/gitpod-io/gitpod/issues/6062

**Comment by AlexTugarev** [comment]
Addressed in https://github.com/gitpod-io/gitpod/pull/6118 🤞🏻
