### ISSUE TITLE
[monitoring] create a Team Meta ops dashboard

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#6126]
Now that we took over ops responsibility for our components, we should create one (or more, but a good primary one) Grafana dashboard for monitoring meta. 

Let's collect ideas here.

**Comment by geropl** [comment]
Question on slack:
> Do we already have an API response time metric somewhere?

We have some pieces, but need to:
 1. defined what "API" means and
 2. stitch sth. together (incl. filter for non-relevant stuff, etc.).

For instance, we do measure response times for HTTP responses ([gitpod_server_http_request_duration_seconds](https://github.com/gitpod-io/gitpod/blob/eed37839c4b1da0c9760dad40a27b7a81b5c1456/components/server/src/server.ts#L103-L104)) but that also includes websocket connection which are _meant_ to take long.
We can also argue whether HTTP connections are that relevant to us, as 95% of the functionality is serves via websocket connection. For that [here](https://github.com/gitpod-io/gitpod/blob/3f3ca7c01d96c16b7b68b04c36c22400f9d3efa0/components/server/src/websocket-connection-manager.ts#L100-L106) would be a good place to add measurement code.

In general, I think the API response/API request error rate topic deserves a separate (sub?) issue, as that is a whole discussion on it's own.
