### ISSUE TITLE
Build finished before we established a listener. Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#613]
**Describe the bug**

Upon trying to open a project:
"Build finished before we established a listener.
Please file an issue if you think this is a bug."

**To Reproduce**

Open using chrome extension: https://gitpod.io/#https://github.com/jhcxavier/Todo-list-Back-End

**Expected behavior**

Project to open!

I noticed a couple of other users having a similar experience, but nothing more recent. Thank you for your help!

**Comment by ColbyWTaylor** [comment]
It is working now- do you know the cause?

**Comment by svenefftinge** [comment]
Sorry, yes there was an issue with the US cluster. It is fixed now.
