### ISSUE TITLE
dotnet development completely broken

### ISSUE THREAD

**Issue by empz** [gitpod-io/gitpod#6130]
### Bug description

Trying to build/run any dotnet project results in the following error:

```
/home/gitpod/dotnet/sdk/5.0.205/Roslyn/Microsoft.CSharp.Core.targets(71,5): error MSB6004: The specified task executable location "/run/containerd/io.containerd.runtime.v2.task/k8s.io/19e24513300952eb64f6c6399cf3f63b05eb284c8e26e196cf542b46dd5f146b/rootfs/home/gitpod/dotnet/dotnet" is invalid. [/workspace/template-dotnet-core-cli-csharp/dotnetcore.csproj]
```

### Steps to reproduce

Open official template in Gitpod: https://gitpod.io/#https://github.com/gitpod-io/template-dotnet-core-cli-csharp

**Comment by hm2075** [comment]
https://community.gitpod.io/t/dotnet-core-on-self-hosted/5265

That should help

**Comment by ghuntley** [comment]
Howdy @empz, indeed .NET is currently broken (😕). We are tracking this over at https://github.com/gitpod-io/gitpod/issues/5090.
