### ISSUE TITLE
Exit in init task causing prebuild to fail without true failure indication

### ISSUE THREAD

**Issue by 0Grit** [gitpod-io/gitpod#6135]
### Bug description

Prebuild saved 3 minutes. But the init task didn't complete fully

![image](https://user-images.githubusercontent.com/24318071/136673184-fcaa2ecd-db95-4788-9318-5a4bdda96850.png)

Also the pre-build apparently doesn't exist

![image](https://user-images.githubusercontent.com/24318071/136673164-f77d94d0-4a87-4362-9920-8fd52a7a7dd8.png)

### Steps to reproduce

Dealing with this issue over the past couple weeks...  $$$

Being able to reproduce the issue for you with a single link... [Priceless](https://github.com/golioth/example-application/tree/ee446e2e5f7d37f23bcc11883fbd1537c713af06)

I appreciate your product. Thank you.

### Expected behavior

I guess I'd like to be told explicitly that the init task failed to avoid lots of troubleshooting and superstition.

### Example repository

https://blush-earwig-3y5sf0pc.ws-us18.gitpod.io/
https://github.com/golioth/example-application/tree/ee446e2e5f7d37f23bcc11883fbd1537c713af06

**Comment by loujaybee** [comment]
Temporarily removing this from Groundwork, we will pick this one up at some point, but we need to do some investigation/thinking on how we need this to work, first.
