### ISSUE TITLE
Gitpod in Mumbai region

### ISSUE THREAD

**Issue by hinddeep** [gitpod-io/gitpod#6139]
_Issue tracked as part of https://github.com/gitpod-io/gitpod/issues/7489._

The latency experienced by me in Rajkot, Gujarat, India is about 300ms. This leads to a subpar experience. I'm on an FTTH connection whose bandwidth is 80Mbps down and 40Mbps up. Please refer to the attached screenshots. I've also attached a screenshot showing the latency of various GCP regions from my location. 

It would be nice to see Gitpod deploying a cluster in India as India houses a sizeable proportion of developers and is one of the largest markets for off-shore development. 

![Screenshot 2021-10-10 at 9 55 18 PM](https://user-images.githubusercontent.com/22722365/136705650-30ee293e-4c0f-4479-9eb7-f8a815901d3d.jpeg)
![gcp_latency](https://user-images.githubusercontent.com/22722365/136705652-c728b0bd-4516-4207-a932-78e9107293cf.jpg)
<img width="395" alt="Screenshot 2021-10-10 at 10 13 08 PM" src="https://user-images.githubusercontent.com/22722365/136705651-e2af10de-8889-419e-9ec4-941411e3e0c7.png">

**Comment by ghuntley** [comment]
Adding more regions is something we desire and intend to do. Currently we operate clusters in the US and EU with future expansion plans for Singapore. There’s some engineering work that needs to happen first - see https://github.com/gitpod-io/gitpod/issues/5534#issuecomment-935949050.

**Comment by kylos101** [comment]
:wave:  hey there, please refer to https://github.com/gitpod-io/gitpod/issues/7489 as the source of truth for supporting more regions than just EU and US. We are closing this issue to consolidate to the single issue.

**Comment by ghuntley** [comment]
This need reopening

**Comment by loujaybee** [comment]
Please see [related comment](https://github.com/gitpod-io/gitpod/issues/7489#issuecomment-1240515469) on #[7489](https://github.com/gitpod-io/gitpod/issues/7489), copied below: 

---

There seems to be some confusion that is related to the closing of the following issues:

https://github.com/gitpod-io/gitpod/issues/5534
https://github.com/gitpod-io/gitpod/issues/6139
Please note: This is not a an update of the status of this issue (closing or opening). The reason for the consolidation is that we now have a proliferation of different regional issues being raised by users. It doesn't make sense for users to directly raising issues about specific required regions, as when it comes to rolling out new regions we'll need to review:

Costings
Latencies
Current + predicted future usage of Gitpod
...and many other factors.

It makes sense for this conversation to happen in a single issue, which is this one. Please continue to share any thoughts or feedback. We'll look to update the description soon as a consolidation of current thinking, as there are now multiple region related issues with many comments.

Thanks all 🙏
