### ISSUE TITLE
Build finished before we established a listener.

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#614]
I'm out of ideas, I tested all combinations and its imposible to use the `.gitpod.yml` with `.gitpod.dockerfile` for this repository. Is there something wrong on my syntax for those 2 files??

This is the repostiory
https://gitpod.io/#https://github.com/4GeeksAcademy/wordpress-hello

<img width="412" alt="Screen Shot 2019-06-14 at 8 54 41 PM" src="https://user-images.githubusercontent.com/426452/59545053-f70da680-8ee6-11e9-8631-baa95d3f7e79.png">

**Comment by svenefftinge** [comment]
There seems to be an issue in the US cluster. We are looking into it.

**Comment by svenefftinge** [comment]
It is fixed now. Sorry again.

**Comment by alesanchezr** [comment]
Thanks @svenefftinge !
