### ISSUE TITLE
Flask redirect doesn't work with in-browser IDE

### ISSUE THREAD

**Issue by dsbowen** [gitpod-io/gitpod#6151]
### Bug description

Flask's `redirect` function doesn't work in the in-browser IDE.

### Steps to reproduce

Using gitpod's flask template, add `app.py` in the root directory.

```python
from flask import Flask, redirect, url_for

app = Flask(__name__)

@app.route("/")
def index():
    return "Index"

@app.route("/redirect")
def redirect_client():
    return redirect(url_for("endpoint"))

@app.route("/endpoint")
def endpoint():
    return "Endpoint"

if __name__ == "__main__":
    app.run()
```

Run the app and navigate to "/redirect" in the browser.

### Expected behavior

You should be redirected to the "/endpoint" URL. Actual behavior: You get the 302 response but are not redirected (no subsequent 200 response).

### Example repository

[Repo](https://github.com/dsbowen/flask-redirect-test). [Snapshot](https://gitpod.io#snapshot/296a13ec-2890-4a54-924c-50b37fdfb3c6)

### Anything else?

The problem goes away if you do the same thing in VS code remote desktop. This is a nice temporary workaround.

**Comment by akosyakov** [comment]
It has hardcoded localhost somewhere:
<img width="834" alt="Screenshot 2021-10-11 at 15 23 25" src="https://user-images.githubusercontent.com/3082655/136797543-475cded8-4c7a-44cd-af48-e44c653e8d71.png">

You should reconfigure the project using exposed ports, i.e.  the value from `gp url 5000`.
Or use [the local companion](https://www.gitpod.io/blog/local-app) to access everything from localhost as usual.

**Comment by dsbowen** [comment]
I fixed the issue by writing a custom `redirect` function.

```python
def redirect(url):
    if url.startswith("/") and "GITPOD_HOST" in os.environ:
        port = request.url_root.lstrip("http://localhost:")[:4]
        gp_url_port = subprocess.check_output(f"gp url {port}", shell=True)
        return flask.redirect(gp_url_port.decode("utf-8").strip() + url)

    return flask.redirect(url)
```

So the entire `app.py` file is

```python
import os
import subprocess

import flask
from flask import Flask, request, url_for

def redirect(url):
    if url.startswith("/") and "GITPOD_HOST" in os.environ:
        port = request.url_root.lstrip("http://localhost:")[:4]
        gp_url_port = subprocess.check_output(f"gp url {port}", shell=True)
        return flask.redirect(gp_url_port.decode("utf-8").strip() + url)

    return flask.redirect(url)

app = Flask(__name__)

@app.route("/")
def index():
    return "Index"

@app.route("/redirect")
def redirect_client():
    return redirect(url_for("endpoint"))

@app.route("/endpoint")
def endpoint():
    return "Endpoint"

if __name__ == "__main__":
    app.run()
```

[Snapshot](https://gitpod.io#snapshot/67e15a3a-2db8-42a7-931b-1b2cbe557c2a). [Repo](https://github.com/dsbowen/flask-redirect-test).
