### ISSUE TITLE
Project missing when I was added as contributor, but repo doesn't belong to a team

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#6156]
### Bug description

My brother created a private project - https://github.com/ashaal/electronil
He added me as contributor, and I can push code to that repo.

When I try to add that repo in https://gitpod.io/new, I cannot find it there.
I can see all the repos I created; I can also see all repos that teams/companies shared with me.
But I cannot choose my brother's Github user, in order to find the private repo that was shared with me.

![image](https://user-images.githubusercontent.com/22901/136825011-5ad8bba7-151d-4f37-8be0-c9e15d6a6315.png)

### Steps to reproduce

Developer1 (not a team) should create a private repo, and give permissions to Developer2.
Developer 2 should go to https://gitpod.io/new, and find that private repo that was shared with them.

### Expected behavior

I should be able to add any repo that I can push code to.

**Comment by AlexTugarev** [comment]
That's true, we missed to communicated this. You need to be an owner of an organization/account on GitHub/GitLab in order to create projects, as this requires setting up webhooks for prebuild events.

**Comment by jankeromnes** [comment]
Based on https://github.com/gitpod-io/gitpod/issues/6156#issuecomment-951652677, removing this again from groundwork, for now.

**Comment by jldec** [comment]
The /new project page now explains projects better and links to the docs which state that:

> 3. You will need to install the GitHub app or have proper permissions to install a webhook for GitLab and Bitbucket before selecting a repository.

---

![Screenshot 2022-01-01 at 20 46 34](https://user-images.githubusercontent.com/849592/147859902-b6f67887-fcc5-4534-88b5-6d2a2000b8f7.png)
