### ISSUE TITLE
[Ruby] No language support

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#616]
The language support for Ruby is broken, as solargraph is no longer automatically installed.

Workaround:
Run the following command in the terminal:
```
gem install solargraph
```

**Comment by jankeromnes** [comment]
It seems that we accidentally removed Ruby's language server `solargraph` from our workspace images during a recent refactor.

It was added back in https://github.com/gitpod-io/workspace-images/commit/7483dba33257382d28418f235329fdef12b0d31b, and we're now waiting for the CircleCI build + Docker Hub push to complete before we can deploy to production again.

**Comment by svenefftinge** [comment]
deployed

**Comment by kevinhq** [comment]
Hi.

I am using ubuntu 16.04 image and didn't install solargraph gem. Ruby 2.3.8 works fine there except there's always an alert about solargraph.

Can I disable this alert? I don't think Ubuntu needs solargraph for Ruby.

**Comment by svenefftinge** [comment]
The Ruby extension needs solargraph, so without it you won't get any editing support.
