### ISSUE TITLE
swap space

### ISSUE THREAD

**Issue by agocorona** [gitpod-io/gitpod#617]
I want to enable swap space for compiling some haskell files, but it is currently not possible either at docker image creation (operation not permitted) neither at runtime (no superuser available)

codenvy for example enables a swap partition by default, as far as I remember.

**Comment by meysholdt** [comment]
We increased the memory available to workspaces about an hour ago. When did you try to compile the Haskell files the last time? Does the available memory suffice now?

**Comment by agocorona** [comment]
Thanks. I tried weeks ago. I will try now. The memory was more than enough even for heavy compilations with GHC, with the exeception of some peaks.
