### ISSUE TITLE
Improve discoverability of GitHub repos for New Project

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#6172]
In cases where my team member already added Gitpod's GItHub App on some organization, I'd like to see its repositories in the New Project wizard in order to select/add them as a new project.

Currently this is not possible due to the limitations of the OAuth/organization rule set. 

Let's consider privacy and security here, just to make sure this isn't a loophole of any kind. A team is founded on trust, so we can assume no one from a team is meant to be excluded from seeing repositories of a GitHub App installation. Further, installations can be limited to particular repositories of an organization/account, which works nicely for protection in general and does limit GItpod's access effectively.

**Comment by JanKoehnlein** [comment]
Do you want to see all projects of the org or just the ones for which the app has been enabled?

**Comment by JanKoehnlein** [comment]
Thanks for clarifying. What change do you propose?

**Comment by AlexTugarev** [comment]
I propose to unschedule this for now and await current changes to the onboarding flow. We can think of optimizing this steps later on.
