### ISSUE TITLE
[Installer]: PodSecurityPolicies now deprecated - explore replacements

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#6176]
PodSecurityPolicies are [now deprecated](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) in Kubernetes v1.21 and will be removed in v1.25. As we have a lot of these in our Kubernetes files, we will need to make appropriate changes.

As this is a wide-ranging and potentially breaking change, we will need representation from all Gitpod teams

The v1.25 release is [currently scheduled for August 2022](https://kubernetes.io/blog/2021/07/20/new-kubernetes-release-cadence/) so we will need to have a replacement in and tested by then.

See [docs](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/) for alternatives

cc @csweichel @meysholdt @svenefftinge

**Comment by MrSimonEmms** [comment]
@aledbf that's good advice.

My guess is that we'd start looking at this ticket in about March of 2022 with a view to getting something released by about June so that we're just ahead of the August deadline.

**Comment by MrSimonEmms** [comment]
It looks like the recommended replacement is [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/) which is graduating to `stable` with v1.25.

**Comment by corneliusludmann** [comment]
On June 4th, we spoked about this in the product engineering sync. @csweichel said we can simply drop them but at the end of the day it's a team workspace decision ([recording (internal)](https://drive.google.com/file/d/1LxALcuHBkW--sddZrTa5E4cnHUI_Xf_j/view)).

**Comment by jenting** [comment]
Reopen it because #12313.
