### ISSUE TITLE
Messed keyboard inputs when digiting

### ISSUE THREAD

**Issue by RpxdYTX** [gitpod-io/gitpod#6184]
### Bug description

Whenever you try to digit something it can sometimes appear really messed up, such as this in c++: `const` appearing as this while you digit: `stcon`, this however goes back to normal if you press space.

On terminal it is a different story, digiting these characters: `.`, `/`, ` ` and others, just surround whatever you are doing in them: normal -> `cd src/Build` in gitpod terminal -> ` cd  /src/ Build`, Notice the spaces, they are important, since when you type those, these surround them aswell.

### Steps to reproduce

Simply try to run these commands normally from the phone-web app. I am running it from phone to be more productive whilst not able to use the pc.

### Expected behavior

Any command could be done normally: `cd src/Build/CMakeFiles`, but these appear like so: ` cd. /src/ /Build/ CMakeFiles`.

**Comment by akosyakov** [comment]
Could you provide info about versions of device, os?

**Comment by RpxdYTX** [comment]
I Toke advantage of the doubled characters, it only lower my productivity, but it is still usable.
