### ISSUE TITLE
Unnecessary extra Terminal in IDE

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#6186]
### Bug description

When your `.gitpod.yml` implements a certain number of `tasks`, there is now always an extra Terminal open in VS Code.

For example, the Gitpod repository specifies **three** tasks (also known as Terminals):

https://github.com/gitpod-io/gitpod/blob/9d4bfb577bc3fe76534fef16aad6c0664357b0b0/.gitpod.yml#L38-L46

However, when opening Gitpod in Gitpod, we observe **four** Terminals (the top-most one is empty):

<img width="1093" alt="Screenshot 2021-10-13 at 10 35 06" src="https://user-images.githubusercontent.com/599268/137097658-0c8591e6-d3b7-45fa-9fe0-de5a11f72256.png">
<img width="1095" alt="Screenshot 2021-10-13 at 10 35 18" src="https://user-images.githubusercontent.com/599268/137097665-933d94de-a65d-4472-9a4c-cd73e122bc96.png">

### Steps to reproduce

1. Open https://gitpod.io/#https://github.com/gitpod-io/gitpod
2. Count the number of Terminals open in VS Code

### Expected behavior

There shouldn't be an unnecessary extra empty Terminal open in VS Code:

- Either we re-use the first empty Terminal for the first task
- Or we close the first empty Terminal when there are `tasks` in `.gitpod.yml`

(Note: It is fine to have an empty Terminal open by default when there are no `tasks` in `.gitpod.yml`)

### Example repository

https://github.com/gitpod-io/gitpod

**Comment by johndunderhill** [comment]
FWIW, I'm having the same problem: I run a setup script when the workspace is started or restarted.  This script detects Gitpod, and sets up the environment for development and testing.  On bare metal, the script configures the environment for staging/production, loading a bunch of additional drivers that don't work on Gitpod.  The configuration is reflected in a collection of environment variables that need to be added to the shell.  I do this by appending a few lines to .bashrc.  This works beautifully everywhere, except for that extra phantom terminal, which is confusing my developers and causing other problems.

**Comment by 0Grit** [comment]
@akosyakov my workspace is struggling to start...

**Comment by johndunderhill** [comment]
@akosyakov Thanks for your help with this.  I switched to the 'Insider' track in preferences and created a new workspace for an affected repo.  This seems to work--no extra terminal, and the environment variables are present.

![startup](https://user-images.githubusercontent.com/25628891/138356864-729f450f-d1b9-4e14-a5ee-c15a4640180d.png)

**Comment by jeanp413** [comment]
Removing from groundwork as the main issue is fixed except for this edge case that will require changes in core vscode
> You'll still see an extra terminal if you reload or access a workspace with a stored workbench state with the panel already open
