### ISSUE TITLE
Stays forever in "Acquiring Node"

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#619]
Some of the academy students are experiencing issues when creating a repository from scratch.

It says "Acquiring Node (1/3)" and it stays forever like that, the repositories are new and empty (or with just a readme).

Here is an example:
https://gitpod.io/#https://github.com/alesanchezr/todelete-2

![Screen Shot 2019-06-17 at 12 19 21 PM](https://user-images.githubusercontent.com/426452/59620322-8939c880-90fa-11e9-83a2-c79685318b5f.png)

**Comment by meysholdt** [comment]
There was indeed an issue, but it's fixed now. Can you try again?

**Comment by alesanchezr** [comment]
Now its working, thanks!

**Comment by svenefftinge** [comment]
hey @alesanchezr sorry for the issues you've faced the last days. Wanted to let you know that we are working on an improved monitoring and self-healing system.

**Comment by alesanchezr** [comment]
Hey @svenefftinge thanks a lot, anything I can with help just tell me.
