### ISSUE TITLE
Can't start workspace due to `content initializer failed`

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#6194]
### Bug description

I ran a prebuild for https://github.com/mikenikles/example-application/tree/gitpod. Since then, I can't open new workspaces due to a `Oh, no! Something went wrong! cannot initialize workspace: cannot initialize workspace: content initializer failed` error.

### Steps to reproduce

1. Open the `gitpod` branch at https://github.com/mikenikles/example-application/tree/gitpod in Gitpod

### Workspace affected

blue-whippet-xg83d6ij

### Expected behavior

The workspace opens and loads the prebuild.

### Example repository

The `gitpod` branch at https://github.com/mikenikles/example-application/tree/gitpod

### Anything else?

If I comment out `west update` in the `init` start task, the workspace loads. If I run `west update` on a workspace manually, it works too.

Could it be that `west update` pulls down too many dependencies, hitting some max limit in terms of prebuild disk space used?

**Comment by meysholdt** [comment]
[Is this the cause](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-10-13T17:35:40Z;query=%22brown-swordtail-wojm47aq%22%0Atimestamp%3D%222021-10-13T17:35:40Z%22%0AinsertId%3D%2293i9yfgh46k5j0bz%22;summaryFields=resource%252Flabels%252Fcluster_name:false:32:beginning;timeRange=PT30M?project=gitpod-191109)?

```
cannot initialize workspace:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.InitializeWorkspace
        github.com/gitpod-io/gitpod/content-service@v0.0.0-00010101000000-000000000000/pkg/initializer/initializer.go:427
  - prebuild initializer:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.(*PrebuildInitializer).Run
        github.com/gitpod-io/gitpod/content-service@v0.0.0-00010101000000-000000000000/pkg/initializer/prebuild.go:96
  - git stash push -u failed (exit status 1): error: invalid path 'bootloader/mcuboot/'
error: bootloader/mcuboot/: cannot add to the index - missing --add option?
fatal: Unable to process path bootloader/mcuboot/
Cannot save the untracked files

```

**Comment by 0Grit** [comment]
Related to #5675 ?
