### ISSUE TITLE
Support Dockerfiles instead of Docker Images for workspaces

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#62]
It is already possible to configure a custom Docker Image for a project [by using a `.gitpod` file](http://docs.gitpod.io/40_Configuration.html#docker-image).

To create a custom Docker Image, however, it is currently necessary to host the image in a public docker registry. 

It would be more convenient if one could specify a `Dockerfile` via `.gitpod` file and Gitpod would on-the-fly create the Docker Image from it when needed.

This feature was requested [here](
https://twitter.com/iitenkida7/status/1037373864202752000).

**Comment by geropl** [comment]
We just deployed this feature to gitpod.io. See here for [an introduction](https://medium.com/gitpod/bring-your-own-docker-image-to-gitpod-52db1aa861de), or head directly to [the docs](http://docs.gitpod.io/40_Configuration.html#docker-image).
