### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by shannonhorn** [gitpod-io/gitpod#620]
Hi, how can I install a different syntax color theme? Thx.

**Comment by svenefftinge** [comment]
We currently only have two themes: light and dark.
You can switch between them by pressing F1 and then choose
`Settings: Change Color Theme`

**Comment by jankeromnes** [comment]
Hi @shannonhorn, which additional syntax coloring would you like to add?

Note that you'll soon be able to install any VS Code extension in Gitpod, and thus add support for almost any desired programming language syntax.

**Comment by shannonhorn** [comment]
Adding any extension would really be nice. I don't have a theme in mind, just looking to spice things up. I am using Nord theme in VS code locally right now. Thx.

**Comment by felixfbecker** [comment]
It seems like there is now support for extensions, but I still cannot switch the theme after installing one

**Comment by JesterOrNot** [comment]
@felixfbecker themes aren't working yet https://github.com/eclipse-theia/theia/issues/6300
https://github.com/gitpod-io/gitpod/issues/818

**Comment by jankeromnes** [comment]
Update: Theme support has now landed in Theia: https://github.com/eclipse-theia/theia/pull/6475

Next we need to update Theia in Gitpod, and deploy Gitpod to production. ETA: early January. 🤞

**Comment by akosyakov** [comment]
@svenefftinge Should we include all built-in Themes from VS Code by default? as far as I understood @shannonhorn use for example Nord. Otherwise users have to download them from https://github.com/theia-ide/vscode-builtin-extensions/releases/tag/v1.39.1-prel and upload to Gitpod.

**Comment by akosyakov** [comment]
Discussed with @svenefftinge that we include all VS Code built-in themes as built-in as well.

**Comment by svenefftinge** [comment]
deployed
