### ISSUE TITLE
Unable to open workspace: Error: build failed: rpc error: code = Internal desc

### ISSUE THREAD

**Issue by C-Undritz** [gitpod-io/gitpod#6203]
### Bug description

Opening workspace, screen displays 'building image' for a few seconds, then followed by a message in red text: 
"Error: build failed: rpc error: code = Internal desc = cannot create build volume: cannot create build volume:"

Button available below that 'Continue with default image'.  When clicked, same message display.  
![Screenshot 2021-10-14 093923](https://user-images.githubusercontent.com/72443150/137282338-3b116537-6249-4971-9108-1d52d1589f73.png)
s
![Screenshot 2021-10-14 094025_2](https://user-images.githubusercontent.com/72443150/137282472-06c8f9ad-1ccb-46d6-a318-647e4bcee9a0.png)
.

### Steps to reproduce

As above

### Workspace affected

tan-grasshopper-p8d6u8hl

### Expected behavior

I would normally expect my workspace to open.

**Comment by jojo157** [comment]
I am having the exact same issue

**Comment by jankeromnes** [comment]
Hi all, thank you for these reports. We've opened an incident and are currently investigating: https://www.gitpodstatus.com/incidents/b01t094hrzlq

**Comment by C-Undritz** [comment]
Yes the workspace is working now.   Thank you for the swift response.

**Comment by bravoalpha79** [comment]
It is working at my end now too. Thank you @jankeromnes!
