### ISSUE TITLE
Cmd+Shift+P on Firefox on MacOS opens a private navigation window instead of the command palette

### ISSUE THREAD

**Issue by magopian** [gitpod-io/gitpod#621]
This was first (wrongly?) opened as https://github.com/theia-ide/theia/issues/5511

### Description
`Cmd+Shift+P` on Firefox on MacOS opens a private navigation window instead of the command palette. This keyboard shortcut is the very first one listed on https://www.gitpod.io/docs/52_Tips_and_Tricks/

### Reproduction Steps
Focus anywhere in the editor and press `Cmd+Shift+P` while in Firefox on MacOS, and it'll open a new Firefox private navigation window.
Pressing `F1` (keyboard shortcut from the `Find Command...` in the `View` menu) works as expected (opens what i believe is the command palette)

**Comment by svenefftinge** [comment]
Ah, I now realized it was a documentation issue. Fixed it. Thank you!
