### ISSUE TITLE
Allow using deleted team name

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#6211]
Currently, in the context of the new Teams & Projects UI, there are two problems related to the deletion of a Team:

- [ ] When you delete a Team, it is not possible to create a new Team that has the same slug as the deleted Team (e.g. a Team with the same name)

To fix this, the TeamsDB should ignore all teams that have `markedDeleted: true` when looking at existing teams / existing team slugs / etc (the same way as it currently ignores all teams that have `deleted: true`):

https://github.com/gitpod-io/gitpod/blob/6bf6485369f2d63e15b4c988f86110132b38c4e5/components/gitpod-db/src/typeorm/team-db-impl.ts#L126-L129

Note: This also applies to all locations in TeamsDB where `deleted: false` is required.

---

~~- [ ] When you are the last person to leave a Team, the team ends up having 0 members (hence no longer being accessible to anyone)~~ Issue exists in https://github.com/gitpod-io/gitpod/issues/4623
 
~~In this case (when the last person leaves), the Team should also get `markedDeleted`:~~

https://github.com/gitpod-io/gitpod/blob/6bf6485369f2d63e15b4c988f86110132b38c4e5/components/gitpod-db/src/typeorm/team-db-impl.ts#L203-L204

**Comment by jldec** [comment]
@laushinka I have scheduled #4623 since there was already some work done there on the last-member deletion UX.

cc: @gtsiolis
