### ISSUE TITLE
Add new workspace condition "stoppedByRequest"

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#6213]
### Bug description

When we call `stopWorkspace` with a `StopWorkspaceRequest` on some workspace, the stopped workspace should come back to the bridge with a new type of condition attached: for example called `conditions.stoppedByRequest` (in addition to the existing conditions `timeout`, `failed` and `headlessTaskFailed`).

This would allow cancelling prebuilds (because when a `StopWorkspaceRequest` is called on a prebuild a.k.a. headless workspace, we know that this is a manual cancellation, as the prebuild workspace wasn't left to run until completion or timeout).

This would help unblock the cancellable prebuilds PR: https://github.com/gitpod-io/gitpod/pull/5865 where we currently:
- [x] Stop the workspace (but just doing that currently leads to a "successful" Prebuild, which shows up in green in the UI and not in red as expected)
- [x] Set `prebuild.state = 'aborted'` immediately from the `server`, which seems to work on the surface, but is risky (because `prebuild.state` could get modified again by the bridge later when the workspace eventually stops)
- [ ] Once the new `stoppedByRequest` condition is implemented, we'd be able to look out for that on prebuild workspaces [in the bridge](https://github.com/gitpod-io/gitpod/blob/9f5270c694a4384853c957d29db84d3767a5a8d0/components/ws-manager-bridge/ee/src/bridge.ts#L73-L90) and set the correct `prebuild.state`.

### Steps to reproduce

N/A

**Comment by AlexTugarev** [comment]
Just for completeness, let's not call this "manual cancellation" but just generic "cancellation" in code, or prepare a field for a reason. Any further improvements towards of prebuild queues would also require to "skip" even potentially running prebuilds, thus cancellation might be requested.
