### ISSUE TITLE
When snapshots take > 60 seconds to create, Gitpod will wrongly report them as pending forever

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#622]
**Describe the bug**
I'd like to create a snapshot, but it doesn't work (modal remains pending in Firefox and Chrome).

**To Reproduce**
1. Open https://github.com/jankeromnes/servo in Gitpod
2. Run `./mach build -r` to build Servo (takes a few minutes, may get OOM-killed, just try again once and it'll finish successfully)
3. Then try to create a snapshot

But the snapshot modal remains pending forever (I never get a snapshot link). Also, the console says this:

```
Uncaught (in promise) Error: Request createSnapshot failed with message: ER_DATA_TOO_LONG: Data too long for column 'bucketId' at row 1
```

By the way, the `/workspace` directory is 8.5GB large:

```
$ du -sh /workspace/
8.5G    /workspace/
```

**Expected behavior**

The snapshot modal should give me a snapshot link, or tell me when there was an error, so that I don't keep on waiting.

**Comment by jankeromnes** [comment]
The workspace is `fb5c42b2-d31f-4c1e-9394-8afe66b0e949` in cluster `ws-eu0`.

**Comment by jankeromnes** [comment]
In Firefox, requesting a snapshot triggers a network request to:

```
https://fb5c42b2-d31f-4c1e-9394-8afe66b0e949.ws-eu0.gitpod.io/gitpod/takesnapshot
```

It remains pending for a little, and then returns:

```
Status: 302 Found
Location: https://gitpod.io/start/#fb5c42b2-d31f-4c1e-9394-8afe66b0e949
```

And the snapshot modal remains pending forever.

**Comment by jankeromnes** [comment]
Also happens with a 7.3G `/workspace`.

I don't see why this would be "too large" for a snapshot, since we're able to create backups every 30 seconds without any issue.

**Comment by jankeromnes** [comment]
Ok, I was able to get a better idea of what happens:

1. `T+00s` Click on "Share Workspace Snapshot"
2. `T+00s` Browser issues HTTP request to `https://<WS_ID>.ws-eu0.gitpod.io/gitpod/takesnapshot`
3. `T+00s` sync container reports `"Handling /snapshot"`
4. `T+60s` Browser received HTTP response `302 Found` with `location: https://gitpod.io/start/#<WS_ID>` (but snapshot UI still says `Taking snapshot, please wait ...`)
5. `T+94s` sync container reports `"Created new snapshot"` (but snapshot UI still says `Taking snapshot, please wait ...`)

It seems that after 60 seconds, the network request gets "cancelled" in the strangest way (why `302` redirect to `https://gitpod.io/start/#ID` ?), causing the snapshot UI to remain pending forever, even after the snapshot is created.

I see two bugs to fix here:
- [ ] `/gitpod/takesnapshot` has a bogus `302` redirect to `gitpod.io/start/` after 60 seconds
- [ ] the snapshot UI tells users to `please wait ...` indefinitely, even when there are errors or timeouts

**Comment by svenefftinge** [comment]
We are moving the snapshot communication to go through the main server using the websocket API. So the timeout issue should be solved with that.
