### ISSUE TITLE
port 4200 exposed, preview not working 

### ISSUE THREAD

**Issue by dev-sharan** [gitpod-io/gitpod#623]
**Describe the bug**
port 4200 exposed, preview not working 

![image](https://user-images.githubusercontent.com/18690573/59738686-be235800-927f-11e9-95ca-36afee8b2979.png)

**To Reproduce**
npm install -g @angular/cli
ng new myapp
ng serve --disable-host-check

**Expected behavior**
preview on port 4200 should work

**Comment by svenefftinge** [comment]
You need to do:
```
ng serve --disable-host-check --host 0.0.0.0 
```

**Comment by dev-sharan** [comment]
Thanks @svenefftinge  it worked . closing this issue now
