### ISSUE TITLE
[code] create slack notification when a new release branch is created in upstream

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6233]
There should a nightly job which checks whether there is a new feature branch in upstream which is missing in openvscode-server repo.

We can create such job in https://github.com/gitpod-io/openvscode-releases

**Comment by akosyakov** [comment]
I think it is already done by @jeanp413 ?

**Comment by jeanp413** [comment]
Yes, this is done, I'm close this.
