### ISSUE TITLE
Command links don't work in the in-workspace onboarding

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#6246]
### Bug description

Links such as `command:gitpod.ports.reveal` have their href elements stripped. Thanks @filiptronicek for investigating that.

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/788827/137549109-7116cc5e-299e-4791-bc17-2456a59d7451.png" alt="A screenshot of the HTML anchor without href tag"/>
</details>

### Steps to reproduce

1. Select "VS Code Insiders" as your preferred IDE at https://gitpod.io/preferences
2. Open a new Gitpod workspace
3. Notice the new "Get Started" onboarding experience
4. Click "Open ports" on the left-side
5. In the content that opens to the right, click the "Click here to open the panel" link

Other places with command links:
* Full access to a terminal
* VS Code desktop support

### Expected behavior

The commands execute, i.e. the "Remote Explorer" panel opens and displays the ports.

### Example repository

All

**Comment by filiptronicek** [comment]
Wondering if maybe it's a problem with our build step, with it stripping any invalid links.

**Comment by filiptronicek** [comment]
Tested a bunch of things today and this issue occurs with the [official example for Walkthroughs](https://github.com/microsoft/vscode-extension-samples/tree/main/getting-started-sample). I reported this issue to https://github.com/microsoft/vscode/issues/135505.
