### ISSUE TITLE
Cmd+Z does not work

### ISSUE THREAD

**Issue by flisanp** [gitpod-io/gitpod#6249]
### Bug description

cmd+z does not work properly.
<img width="933" alt="2021-10-16 kl  13 37 04" src="https://user-images.githubusercontent.com/70511857/137586507-a94119d5-c42c-4eba-9929-18abfdc61e09.png">

### Steps to reproduce

It's working if I write something and I immidiately want to erase it, but if I erase a block of text and I want to undo, then it's not working. 

### Expected behavior

To undo if I erase something accidentally. It has worked fine before.

**Comment by etienne1911** [comment]
very annoying bug, making the editor a real nightmare to use
I'm using chromium 96 on linux and all ctrl- command (like ctrl-z for undo, ctrl-/ for comment, ctrl-A for select all) are misinterpreted.
Is there any update on this issue?
