### ISSUE TITLE
gitpod is very slow today . 

### ISSUE THREAD

**Issue by DDproducts2** [gitpod-io/gitpod#6251]
### Bug description

Today Gitpod is very slow in creating apps or adding depedencies from yarn or npm please fix it as soon as possible 

When i creates react apps on gitpod it takes only 40 to 50 sec but today it takes almost 25min . adding depedencies takes only 5 to 10 sec but today it taken 15min . please fix it as soon as possible
### Steps to reproduce

Performance should be increased internet speed should be increased
CPU IS ALSO SLOWER TODAY 

### HERE IS THE PROOF

![image](https://user-images.githubusercontent.com/90947621/137623621-ae3c8d2a-5a75-4a62-a691-ebd4f516f73a.png)
 ONLY ADDED LARAVEL MIX  IN MY PROJECT . 

SEE THE DONE IN MESSAGE IN THE UPPER IMAGE

**Comment by csweichel** [comment]
Hi, sorry for these issues. We've just brought a change online which should help matters.
