### ISSUE TITLE
BitBucket Support

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#626]
Gitpod should integrate with BitBucket the same it does with GitHub and GitLab.

**Comment by Pilatch** [comment]
Yea baby. Would love some bitbucket support.

**Comment by Kreyren** [comment]
Can't contrib, bcs the code is..

![image](https://user-images.githubusercontent.com/11302521/81795959-1228d200-950d-11ea-8190-c22682217aee.png)

**Comment by jankeromnes** [comment]
FYI Gitpod is starting to understand Bitbucket URLs in private staging environment, and "Login with Bitbucket" is being implemented. Barring any unforeseen blockers, I think Bitbucket support in Gitpod is on track for deployment in a few weeks.

Thanks for working on this @corneliusludmann! 💯
