### ISSUE TITLE
[agent-smith] Better detect miner binaries by scanning strings, too

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6267]
Today again we saw running miners that built their binaries with "stripped" symbols, making it impossible for AS to detect them.

A solution would be to look for hardcoded strings as well, which are hard to remove from the binary without breaking it.

Miner repo: https://bitbucket.org/jkhjkhgkj/resa/src/master/.gitpod.yml
Draft PR that impls that for older AS: https://github.com/gitpod-io/gitpod/pull/5238

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6267#issuecomment-946505223):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
