### ISSUE TITLE
Cannot add a new project when having two accounts

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#6268]
### Bug description

When trying to add a new GitLab project under gitpod.io/new, I could not move forward and received no error messages. Supposedly this is caused by having two Gitpod accounts.

https://www.loom.com/share/ba9d0b291d1e491baafe7a1bd7db9ed3

### Steps to reproduce

As the above video:
 1. Have GitHub and GitLab accounts.
 2. Log in via GitHub.
 3. Go to https://gitpod.io/projects and click "New Project"
 4. Click on the "change" link (to add a GitLab project)
 5. Click on "Continue with GitLab" 
 6. You should see a modal pop up and then disappear. Nothing else will happen.

### Expected behavior

I expect to be able to add a project, or see a helpful error message.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6268#issuecomment-945775347):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
