### ISSUE TITLE
[FEATURE] User Specific Default gitpod configs

### ISSUE THREAD

**Issue by Merith-TK** [gitpod-io/gitpod#6275]
So this stems from an issue I recently encountered where I found myself having to do alot of configuration every time I open a repo just to make it work, (usually involves a fork+pr to add gitpod config)

So why not just give a user the option to setup a default gitpod.yml in their `github.com/username/username` repo or in a repo called `github.com/username/gitpod-default-config` (allow this repo to be private)

so this way, some poeple who dont like the default base image can have more fine control over it when opening repos that are not their own!

**Comment by Merith-TK** [comment]
Stalebot no

**Comment by axonasif** [comment]
@Merith-TK this is doable with the brand new dotfiles support.
I made you a dotfiles repo to get started from, simply use the link: https://github.com/gitpod-dotfiles/default_gitpod_yml on your https://gitpod.io/preferences

Also please close the issue if you feel that this resolves your need.

**Comment by Merith-TK** [comment]
What if i were to open a repo with a preset gitpod dotfiles? and my dotfiles utilized their own image seperate from the repos

**Comment by axonasif** [comment]
You mean a custom docker image?

**Comment by Merith-TK** [comment]
Yes a custom default docker image.

**Comment by axonasif** [comment]
Can you share me the dockerfile you have?

**Comment by Merith-TK** [comment]
https://github.com/Merith-TK/gitpod-workspace

**Comment by axonasif** [comment]
> https://github.com/Merith-TK/gitpod-workspace
> 
> inprocess of seeing if I can make it work like how your example shows

I see that you're using an archlinux base, you indeed can convert a dockerfile to a shellscript and put that in your `install.sh` but directly changing the base image would not be possible.

You can make changes to the template repository that I had shared to copy your dockerfile too, but this process will require you to commit and push the changes, then opening a new workspace.
