### ISSUE TITLE
Keys randomly stop working on iPadOS

### ISSUE THREAD

**Issue by akaFTS** [gitpod-io/gitpod#6279]
### Bug description

iPadOS support has improved significantly in the last few weeks, thanks to some fixes in VS Code upstream (likely due to GitHub Codespaces launch) and to these new persisting workspaces in Gitpod where your uncommited work is saved until your next session (was it always like that? I remember having to clone the repo from scratch on every session start).

However, there are still some pesky bugs in VS Code. The worst of them is that sometimes, randomly, some keys decide not to work anymore. Sometimes it is the Enter key, sometimes Cmd+A or Cmd+C, and a page refresh is needed to get rid of it.

### Steps to reproduce

Open a workspace in iPad Safari and interact with it by hopping between files, dismissing toasts, switching to other apps, and very soon some keys will stop working.

### Expected behavior

Should work as intended.

**Comment by ghuntley** [comment]
> The worst of them is that sometimes, randomly, some keys decide not to work anymore.

I've seen this over the last couple days on arrow keys in vscode and terminal. I'm using the insider release of VSCode on Gitpod (see account settings). Are you using the magic keyboard? I've found disconnecting the keyboard and reconnecting fixes. Strange huh?

**Comment by ghuntley** [comment]
I'm using insiders. Space in terminal would not work until attach and detach keyboard.

 https://user-images.githubusercontent.com/127353/140011755-39585fe3-00d4-4c03-b548-c5a220b5fed1.MOV

**Comment by akaFTS** [comment]
I'm using the smart (not magic) keyboard. I haven't spotted the issue in the last few days though, but I'm also not coding much on the iPad. Let's keep an eye out for it.
