### ISSUE TITLE
React-App: "Invalid Host header" 

### ISSUE THREAD

**Issue by Funory** [gitpod-io/gitpod#628]
How to fix #26 with a React Project?

**Comment by jankeromnes** [comment]
Hi @Funory! Thank you for reaching out.

As mentioned in https://www.gitpod.io/blog/gitpodify/#invalid-host-header, you can try several things:

- Use the `--host 0.0.0.0 --disable-host-check` flags with your `webpack-dev-server` or `ng serve` CLI
- Add `devServer: { host: '0.0.0.0', disableHostCheck: true }` to your `webpack.config.js` or `vue.config.js` file
- Set the `DANGEROUSLY_DISABLE_HOST_CHECK` env variable to `true` in your project

Hope this helps!

**Comment by Funory** [comment]
Setting the `DANGEROUSLY_DISABLE_HOST_CHECK=true` does it, thanks.

**Comment by LuisTheDeveloper** [comment]
> Setting the `DANGEROUSLY_DISABLE_HOST_CHECK=true` does it, thanks.

Hi, where did you find that flag in react project? What source file?
Thanks.

**Comment by jankeromnes** [comment]
@LuisTheDeveloper The `DANGEROUSLY_DISABLE_HOST_CHECK` environment variable is specific to `create-react-app`:

https://github.com/facebook/create-react-app/blob/f5c3bdb65480f93b2d4a4c2f3214fc50753de434/packages/react-scripts/config/webpackDevServer.config.js#L43-L44

It's useful when you're using `create-react-app` but you have no control over what options are passed to `webpack-dev-server`.

**Comment by SergioVzqz** [comment]
To those who were a little lost, like me, the solution is, in your react app root folder create a file with the name `.env.development.local` then add the `DANGEROUSLY_DISABLE_HOST_CHECK=true` in that file.
