### ISSUE TITLE
Gitpod integrations in Raycast

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#6282]
As part of https://github.com/raycast/extensions/pull/32 Gitpod was added into the GitLab extension. How else could Gitpod be integrated with Raycast (and similar things such as Alfred?). Does it make sense to build our own extension and list in the store? Let's discuss!

**Comment by sualehasif** [comment]
I want to really bump this! I think an extension that allows users to quickly spin up their workspaces would be amazing!

I would be able to help if needed but it seems the gitpod team (cc @ghuntley) are already there to help.
