### ISSUE TITLE
Minio sub chart

### ISSUE THREAD

**Issue by hrpatel** [gitpod-io/gitpod#6284]
Hi,

I notice that the minio sub chart has now been deprecated in favour of the operator based chart. See: https://github.com/minio/charts

The current sub chart now deploys an 8 month old version of minio. 

Are there plans to move to the operator based minio charts?

Thank you in advance!

**Comment by MrSimonEmms** [comment]
Closing in favour of #6876 as the chart is now unavailable.

In answer to your question @hrpatel, we've switched over to the [Bitnami version](https://github.com/bitnami/charts/tree/master/bitnami/minio) of this chart in the [Installer](https://github.com/gitpod-io/gitpod/tree/main/installer) which is not deprecated and is a near-exact drop in replacement

**Comment by hrpatel** [comment]
Thank you!
