### ISSUE TITLE
Filtered email domains are not working

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#6285]
### Bug description

I added entry to `d_b_email_domain_filter`. The entry was synced across DBs. However, new users from that domain name were able to signup.

### Steps to reproduce

I haven't reproduced it by explicitly adding a domain but I believe it should be:
1. Add an entry to the table
2. Try signing up with that domain email id

### Expected behavior

Users are not allowed to signup

**Comment by kylos101** [comment]
Hi @geropl I just added this to the WebApp inbox. Do you have an upcoming admin epic where this could be included? For example, to validate that it is working? I would ask for it to also be added to the admin UI, but that seems like it'd be a lot more work, so just having it work with an `insert` would be okay for now.
