### ISSUE TITLE
Markdown preview does not load image

### ISSUE THREAD

**Issue by koppor** [gitpod-io/gitpod#629]
**Describe the bug**

I edit a markdown file (`.md`). I have the markdown preview opened. The markdown code shows

    ![ADR](ADR.png)

The file `ADR.png` is existent in the same folder as the `.md` file. It renders properly on GitHub pages.

However, it does not render properly in gitpod.io:

![Screenshot 2019-06-19 at 18 45 32](https://user-images.githubusercontent.com/1366654/59784361-82f64880-92c2-11e9-86e5-12e360fa4ad8.png)

**To Reproduce**

- Variant 1: Open <https://gitpod.io/#https://github.com/adr/adr.github.io/>.
- Variant 2: In a gitpod.io workspace, upload `img.png`. Create `test.md`. Add `![](img.png)`. Save. Open Markdown preview.

**Expected behavior**

The image should be shown in the preview instead of a "broken image" symbol.

**Comment by paulk-asert** [comment]
Image preview was working fine for me yesterday but stopped working today.
![image](https://user-images.githubusercontent.com/280016/101874902-72800f00-3bd5-11eb-8128-dd71ce4a61b3.png)
Is this expected due to recent changes or should I file another issue?

**Comment by akosyakov** [comment]
It is a regression after today deployment.

**Comment by akosyakov** [comment]
The fix was deployed.
