### ISSUE TITLE
[preview-envs] avoid letsencrypt rate limit error

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#6291]
we sometimes see the following error in Werft:
> Failed to create Order: 429 urn:ietf:params:acme:error:rateLimited: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours:
src: https://gitpod.slack.com/archives/C01KGM9EBD4/p1634246511455700?thread_ts=1634228500.454400&cid=C01KGM9EBD4
discussion: https://community.letsencrypt.org/t/5-already-issued-for-this-exact-set-of-domains-in-the-last-168-hours/153169

On https://crt.sh/?CN=gitpod-dev.com we can see wich certificates have been issues to us. Advanced Search -> mark "common name" -> search for "gitpod-dev.com". 

There I can see that we request certs for the same domains several times for grafana and prometheus:
![image](https://user-images.githubusercontent.com/239422/137929251-3e560405-73db-4257-a5a9-4f4920ce6b71.png)

Thus I assume that we're not running into the "max cert per week" rate limit for which we have an increase quota. 

We run into the "max certs for same domain" rate limit, which we could avoid, if we would not request certs redundantly.

**Comment by ArthurSens** [comment]
Preview environments are now live for 2 days thanks to https://github.com/gitpod-io/gitpod/pull/6440, so maybe this issue does not exist anymore because we were hitting the "daily rate limit".

Let's keep an eye open, and continue the work if we see this problem happening again

**Comment by meysholdt** [comment]
> maybe this issue does not exist anymore because we were hitting the "daily rate limit".

closing for now. Will re-open if the limit becomes a problem again.
