### ISSUE TITLE
[agent-smith] Too many memory allocations thanks to procfs

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6297]
The use of prometheus/procfs leads to too many memory allocations. We should rewrite this bit with more targeted implementations.

![image](https://user-images.githubusercontent.com/3210701/137980747-9ad2ca2e-e7f6-40db-8daf-1d6a3811667e.png)

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6297#issuecomment-947056041):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
