### ISSUE TITLE
Port not found (no matter the port)

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#630]
Since yesterday when I create a new workspace and I try to `run a web server -> expose port-> open browser` I get the error "port not found". I have tried with several workspaces and none of them seem to work.

https://gitpod.io/port-not-found/#8081

Here is one of the projects:
https://d032d894-cc4c-426e-9c33-c2d924b4486f.ws-us0.gitpod.io/#/workspace/api

**Comment by svenefftinge** [comment]
Will look into it. You shared the link to the running workspace.
Could you instead share a snapshot link, please?

**Comment by svenefftinge** [comment]
Looked it up in the DB. What's the command you run to start a server?

**Comment by alesanchezr** [comment]
The command for that one is `python3 manage.py runserver`

I'm sorry for the delay on the response!

**Comment by espvtes** [comment]
I'm haven this issue too this is my snapshot:
https://gitpod.io#snapshot/0a051c2b-04d5-4eae-b0f5-06d01d20f814


for to run the project npm run start

**Comment by jankeromnes** [comment]
Hi @alesanchezr! I think I found the problem:

```bash
$ python3 manage.py runserver
# ...
Starting development server at http://127.0.0.1:8000/
```

Your server is bound to `127.0.0.1`, which means that it will only accept requests coming from `localhost`, and will refuse any connections coming from outside the container (e.g. the Gitpod preview).

The solution is to bind it on `0.0.0.0` instead, to accept remote connections:

```bash
$ python3 manage.py runserver 0.0.0.0:8000
# ...
Starting development server at http://0.0.0.0:8000/
```

<img width="1552" alt="Screenshot 2019-06-20 at 08 27 29" src="https://user-images.githubusercontent.com/599268/59825849-647d6500-9335-11e9-8519-fe9b5980da82.png">

Note: By default, the preview will open `/`, which shows a Django error page. Then you can either navigate to the right URL, or use something like:

```bash
gp preview $(gp url 8000)/docs/
```

**Comment by jankeromnes** [comment]
@espvtes you indeed seem to be having the same problem:

```bash
$ npm start

# ...

You can now view gatsby-starter-hello-world in the browser.

  http://localhost:8000/
```

One solution to tell Gatsby that the `host` should be `0.0.0.0` instead of `localhost` is to run:

```bash
$ IP=0.0.0.0 PORT=8000 npm run c9
```

<img width="1552" alt="Screenshot 2019-06-20 at 08 35 07" src="https://user-images.githubusercontent.com/599268/59826322-61cf3f80-9336-11e9-9e58-30a94af689d1.png">

(Unfortunately, there was a React error that I didn't have time to investigate for you, but at least you have a preview now.)

**Comment by svenefftinge** [comment]
We figured there is an issue with the hot exposure of ports, which doesn't work properly.
It doesn't affect any workspaces that have the ports configured in their `.gitpod.yml`. The fix is on its way to staging and will be deployed to production ASAP.

**Comment by svenefftinge** [comment]
This is now fixed and deployed

**Comment by alesanchezr** [comment]
Amazing support as always guys, thank you! 😄

**Comment by swex1** [comment]
hello , Port 3000 Not Found
Please make sure this port is exposed and your application is up and running. its not work hope you soon as soon help me

**Comment by axonasif** [comment]
@swex1 please send us a message at https://www.gitpod.io/contact/support instead.
