### ISSUE TITLE
Project Configuration - Run Prebuild always shows "Connecting to workspace Logs..."

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6305]
This is possibly a duplicate of #5573 

Successful prebuilds should either show a log, or a message that there was no stdout.

Users are confused by the message "Connecting to workspace logs..." which persists even if the prebuild succeeds.

![Screenshot 2021-10-20 at 00 15 48](https://user-images.githubusercontent.com/849592/138003435-079c66d1-0635-4eec-876e-3ad6153484d5.png)

![Screenshot 2021-10-20 at 00 15 57](https://user-images.githubusercontent.com/849592/138003439-7cfd87e3-ee6f-461a-a842-4e935860ef10.png)

**Comment by jldec** [comment]
Scheduled.
The inconsistent behavior of prebuild status and logs is adding to the perception of prebuild unreliability.

**Comment by jankeromnes** [comment]
"Connecting to workspace logs..." was a pure front-end thing, which got removed in https://github.com/gitpod-io/gitpod/pull/8558:

> Don't always print 'Connecting to workspace logs...' (it's somewhat misleading)
> 
> Context: We initially added it to show the user that the front-end is loaded, and now the backend is working to fetch what the user wants. However, we've observed that the backend is unreliable, and can fail in various different stages, so it's not always actually connecting (e.g. sometimes there is no workspace to connect to, other times it cannot find the logs for some reason).
> 
> Maybe showing a blank logs view is better than a somewhat misleading message.
> 
> A better, long-term fix would be to implement the [Headless Logs (again) RFC](https://www.notion.so/gitpod/Headless-Logs-again-a0dab5e5dd244feba5d147fca9fd29a4), i.e. "central log ingestion service to content-service, make supervisor a writing client to this service".
