### ISSUE TITLE
Support .env files in profile settings variables

### ISSUE THREAD

**Issue by chuck-alt-delete** [gitpod-io/gitpod#6308]
It’s tedious to create a new variable entry in my profile settings for each variable I want to define. I’d love to paste in a “.env style” text file, like 

```
MY_VAR1=cool
MY_VAR2=awesome
…
```

The use case I have is setting up secrets to access managed services. If my managed service has a bunch of different api keys and such, I want one simple way to define them all at once rather than one at a time.

**Comment by loujaybee** [comment]
If you want, you could programatically by copying your environment variables to a workspace then running [`gp env`](https://www.gitpod.io/docs/environment-variables#using-the-command-line) for each line (example below). Use carefully, though as this will overwrite any named existing variables 🙏 

```bash
#!/bin/bash

while read -r ENV_VAR; do
    gp env $ENV_VAR
done < .env
```

Are your secrets coming from a single secrets source, if so which app/service are you using?

**Comment by chuck-alt-delete** [comment]
Please don’t close! This issue is still causing friction for me. Surely others are finding it tedious to manage individual environment variables in gitpod.io/variables?

Also, the workaround is never really going to be sufficient because I need environment variables available in the workspace on launch. I can’t wait for the user to input them manually. Why? Because the whole idea is for a user to launch a workspace and so it will dynamically and securely load that user’s API keys.

**Comment by axonasif** [comment]
@chuck-alt-delete You can pretty much get this done with the dotfiles support.
See https://www.gitpod.io/docs/config-dotfiles
If you need help regarding it, let me know 👍

**Comment by chuck-alt-delete** [comment]
I don’t think this will work. Dot files are applied to all workspaces, and I don’t think they are meant to store secret credentials like gitpod.io/variables. Am I misunderstanding the dotfiles implementation?

**Comment by chuck-alt-delete** [comment]
I suppose we can close this as long as these are addressed:
- https://github.com/gitpod-io/gitpod/issues/6339
- https://github.com/gitpod-io/gitpod/issues/6316

**Comment by axonasif** [comment]
> I don’t think this will work. Dot files are applied to all workspaces, and I don’t think they are meant to store secret credentials like gitpod.io/variables. Am I misunderstanding the dotfiles implementation?

What if you can store your `.env` file in a private repo and load the variables from that in all of **your** workspaces?
Does that sound good?

**Comment by chuck-alt-delete** [comment]
Thanks for your help, but no that does not fit my use case very well. There are several drawbacks. 
- First, I don’t want to require each user create their own private dotfiles repo (and docs say the repo must be public, but either way it doesn’t work). 
- Second, I don’t want to encourage the practice of committing credentials to git in learning materials, even if it might be ok in this instance.
- Third, I don’t want these variables available in all repos. Only the ones that require them. Otherwise it makes it too easy for someone to forget later and share workspaces with sensitive credentials.

**Comment by axonasif** [comment]
> and docs say the repo must be public, but either way it doesn’t work

You can clone a private repo under your org through a public dotfiles repo, only members in your org will be able to clone such private repos. That was the idea 😅 

> Second, I don’t want to encourage the practice of committing credentials to git in learning materials, even if it might be ok in this instance.

Fair enough. Perhaps https://github.com/gitpod-io/gitpod/issues/7881 would be a better fit for your use-case.

> Third, I don’t want these variables available in all repos. Only the ones that require them. Otherwise it makes it too easy for someone to forget later and share workspaces with sensitive credentials.

It essentially shouldn't get leaked. Although there is always a risk when you "Share Workspace" from the dashboard, which also gives away your git credentials and **everything else**. So one must use `gp snapshot` command instead for sharing a workspace.[^1]

[^1]: https://www.gitpod.io/docs/sharing-and-collaboration#how-to-take-a-snapshot-url

**Comment by chuck-alt-delete** [comment]
Thanks again for the lengths you are going to help! I realize I mentee more about my use case in those other linked issues but not here. I’m not just working with other engineers in my org. I’m creating labs and demos for learners and prospective customers. The goal is to have a 1 time setup for the users where they enter their credentials. Then after that, every lab should be able to automatically connect to each user’s SaaS account. For example:
- https://github.com/chuck-confluent/ccloud-gitpod-demo/blob/main/.gitpod.yml#L41

**Comment by loujaybee** [comment]
> I wish I could use Hashicorp Vault or something, where I could have a single access key and use it to programmatically retrieve secrets at runtime. I personally am using Confluent Cloud, where I have two API keys, two URL endpoints, email, password, and a Confluent cloud environment ID. If I were integrating Confluent cloud with Mongo Atlas, then I would add additional variables to access my MongoDB instance, for example. Not all of these are secrets, but they are all related and I want to define them only once in settings -> variables.

@chuck-alt-delete We are now currently looking at enabling something as you described.

- Also as described here: https://github.com/gitpod-io/gitpod/issues/9412

If you (or anyone else stumbling on this issue) would like to [chat to see how this does/could work in Gitpod](https://calendly.com/lou-gitpod/product-feedback), I'd be happy to talk you through it, and see what we'd need to do to get things setup for you.
