### ISSUE TITLE
[Docker] UnauthorizedError on unknown image

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#631]
If I specify an unknown docker image (example `image: gitpod/mysql`) I see
<img width="500" alt="Screenshot 2019-06-21 at 08 59 09" src="https://user-images.githubusercontent.com/372735/59904135-1040b680-9403-11e9-8c5a-87a9d6bed102.png">

which is not helpful.

**Comment by JesterOrNot** [comment]
Yea the message has changed since but the issue is still present. Will take a look.
