### ISSUE TITLE
Clean up member-less teams

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#6311]
### Bug description

While we now delete teams from the database when a user deletes a team (see https://github.com/gitpod-io/gitpod/pull/6273) we still have not resolved what happens to teams when the last team ~owner~ member tries to leave the team (see #4623).

This causes some confusion as users can not reuse a team name after leaving a team as the last team member, see https://github.com/gitpod-io/gitpod/pull/6273#issuecomment-947358186.

Some of these teams also surface on the team scope selector.

<img width="251" alt="Screenshot 2021-10-20 at 9 24 02 AM" src="https://user-images.githubusercontent.com/120486/138039189-8206e60d-2f9f-43b9-a62b-74c2b8fd1783.png">

We should probably resolve #4623 first and then clean up the the database and remove member-less teams. 🗺️ 

### Steps to reproduce

1. Create a team
2. Go to team members
3. Leave the team
4. Try creating a new team with the same name

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6311#issuecomment-998845423):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by gtsiolis** [comment]
> Maybe we should not allow an owner to switch role as a member, when they are the last one remaining.

It makes sense to never allow users to change their own role in a team regardless if they are the last remaining member, right?

**Comment by jldec** [comment]
It's reasonable for an owner to reduce their role to member, after they delegate ownership to someone else.
It's a problem if this leaves the team without any owners.
Since this is unlikely we're not going to work on this a.t.m.

**Comment by gtsiolis** [comment]
> It's reasonable for an owner to reduce their role to member, after they delegate ownership to someone else.

**thought**: Not sure if this is a common flow though. In such cases, usually, users are removed from a team following a process or  they manually leave a team to clean up non-longer relevant information and teams. 💭 

**issue**: Besides this, the cost of allowing users to lower their permissions keeps two issue around: a) orphaned teams without owners and b) empty teams as the last member can leave a team although we do not allow this for owners, see screenshot below.

**issue**: Also, this issue was originally created at the early days of teams and projects which has led to having empty and non-accessible teams listed in the team scope selector. Here's what I see on production for my account, see screenshot below. However, this could be individually resolved for users by introducing a way to delete teams from the admin dashboard, see https://github.com/gitpod-io/gitpod/issues/8523. 

| Last owner trying to leave a team | Member-less teams |
|-|-|
| <img width="502" alt="Screenshot 2022-03-14 at 5 01 36 PM" src="https://user-images.githubusercontent.com/120486/158211212-aca371ee-3d01-4f9f-8983-669f693071da.png"> | <img width="288" alt="Screenshot 2022-03-14 at 5 57 41 PM" src="https://user-images.githubusercontent.com/120486/158211987-92b8a254-5971-4302-909b-cc32ce0ef385.png"> |

**suggestion**: I agree this is an edge case and fixing this would have a low impact as the issue affects a very small fraction of users. Disallowing team owners to change their role to member could help avoid introducing more member-less teams or confusion.

**Comment by gtsiolis** [comment]
Closing as this is not relevant anymore.

However, there's a closely related and follow-up issue in https://github.com/gitpod-io/gitpod/issues/10166. Cc @jldec

**Comment by nidhinmanu** [comment]
@gtsiolis This problem still persists as I have ran into it today. Created a team, demoted myself to member accidentally, left the team hoping it would get deleted(I was the only member). And now locked out of using the team name as error outputs "Team name already in use".

**Comment by gtsiolis** [comment]
Thanks for noticing, @nidhinmanu!

[FWIW](https://en.wiktionary.org/wiki/FWIW), I've opened a new issue for this specific bug, as this has been brought up a couple of times in the past.
