### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by 7sharp9** [gitpod-io/gitpod#632]
Add F# Extension and make it available in Gitpod.

**Comment by JesterOrNot** [comment]
I'll get a dockerfile going

**Comment by JesterOrNot** [comment]
Here is the repo!
https://github.com/JesterOrNot/Gitpod-FSharp

**Comment by 7sharp9** [comment]
I found there was a bug in theia that stopped the ionide extension loading,
it was waiting for release last I checked.

**Comment by JesterOrNot** [comment]
ok got it!

**Comment by JesterOrNot** [comment]
Give it a try though

**Comment by spillsthrills** [comment]
I have it compiling a dll for a simple F# console app in Gitpod.io but can't seem to get it to debug can you please show the task/launch configuration that works? I am relatively new to the F# world so apologize if this really obvious but, same setup that works on Ionide Mac Desktop fails to debug on Gitpod.io.
