### ISSUE TITLE
onOpen: open-preview doesn't work as intended with noVNC image

### ISSUE THREAD

**Issue by anudeepreddy** [gitpod-io/gitpod#633]
**Describe the bug**
`onOpen: open-preview` in the .gitpod.yml file doesn't work as intended for noVNC images. Sometimes it does open the preview but most of the times it doesn't.

**To Reproduce**
Just start the workspace with this :
https://gitpod.io/#https://github.com/anudeepreddy/hyper

**Expected behavior**
The preview should launch when the workspace starts.

**Comment by svenefftinge** [comment]
Worked on first try. :-|

**Comment by svenefftinge** [comment]
I only opens if the frontend receives the event. That is if the port gets opened before the frontend is loaded, the event gets lost.

**Comment by meysholdt** [comment]
I can reproduce this via https://gitpod.io/#https://github.com/meysholdt/tutorial-selenium-java-basic

**Comment by jankeromnes** [comment]
So, in theory we've fixed this, but I just noticed another bug with noVNC image ports: https://github.com/gitpod-io/gitpod/issues/742

Closing this in favour of the new bug (since it's a slightly different bug, and this one here we've fixed.)
