### ISSUE TITLE
Build stuck on installing node-exporter

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#6330]
[A build](https://werft.gitpod-dev.com/job/gitpod-build-laushinka-meta-dashboard-6126.6) was running for around one hour and stuck in installing node-exporter phase. 

It was unstuck after [all the pods in the same namespace were removed](https://gitpod.slack.com/archives/C020VCB0U5A/p1634804805003000?thread_ts=1634803616.001800&cid=C020VCB0U5A).

**Comment by meysholdt** [comment]
Closing for now; We'll look at builds being stuck again in about at week when we have traces in Honeycomb.
