### ISSUE TITLE
[ws-deployment] Make workspace cluster creation automated

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#6331]
Creating a workspace cluster should be as simple as running a cli with config

**Comment by roboquat** [comment]
@princerachit: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6331#issuecomment-948439315):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
