### ISSUE TITLE
[self-hosted] Unable to install 'ms-toolsai.jupyter' extension because it is not compatible with the current version of VS Code (version 1.57.1)

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#6341]
### Bug description

When installing the extension `ms-toolsai.jupyter` in Gitpod self-hosted, the following error given
![image](https://user-images.githubusercontent.com/9018897/138298297-bcc76fcc-b1a4-40cd-b70c-7e3a0838a203.png)

### Steps to reproduce

1. Deploy Gitpod self-hosted
2. Launch workspace
3. Install extension `ms-toolsai.jupyter`

### Workspace affected

n/a

### Expected behavior

Extension installed

### Example repository

n/a

### Anything else?

Gitpod Self-Hosted v0.10.0

**Comment by enriquecaballero** [comment]
Having the same issue 🤔
