### ISSUE TITLE
Compile a spreadsheet of emails for the private BETA of Jetbrains

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6342]
Seems that people have found their way to this issue already 😆 

If you're interested, stick a comment on the issue👇  and we'll get in touch 🙏  

**EDIT:** Please also leave your Discord username, see [this message below](https://github.com/gitpod-io/gitpod/issues/6342#issuecomment-967006894)

Note: We already have an internal list of people who expressed interest, so we may already have your name/contact, however if you want to be sure, feel free to comment, also 🙏

**Comment by anugrahsinghal** [comment]
Please add me !! ♥️

**Comment by ankushg** [comment]
interested as well 😄

**Comment by mbildner** [comment]
Please add me!

**Comment by smeijer** [comment]
Sweet! Sign me up!

**Comment by bigint** [comment]
Add me to the queue 🤗

**Comment by buggtb** [comment]
Hook me up!

**Comment by loujaybee** [comment]
A note that: https://twitter.com/yogicodes sent me a message on Twitter, so I have his contact separately.

**Comment by normcrandall** [comment]
Please add me.

**Comment by jdiala** [comment]
Please add me. Thanks!

**Comment by exemaitch** [comment]
Would love to get in on this!  Thanks!

**Comment by Koch** [comment]
Very very interested :)

**Comment by rm-jamotion** [comment]
Please add 🤝

**Comment by Dev-Time** [comment]
Very interested in this feature.

**Comment by adrian-goe** [comment]
i'm interested 😊

**Comment by Auft-Community** [comment]
Using Gitpod with Jetbrains would far increase my workflow, I love Gitpod, but don't want to have to migrate to VSCode. Let me know if I can try out this Beta.

**Comment by ionutale** [comment]
I'm interested

**Comment by cortinico** [comment]
Same ✋

**Comment by Johnzzon** [comment]
Sign me up, this is very interesting!

**Comment by titimoby** [comment]
Oh my... 🤘

**Comment by ruuds** [comment]
Please sign me up!

**Comment by JeromeRauline** [comment]
+1

**Comment by rgbrizzlehizzle** [comment]
Sign me up pls :)

**Comment by jimmyp** [comment]
Keen

**Comment by mattalexx** [comment]
Keen times infinity

**Comment by cyppan** [comment]
I'm interested, thanks!

**Comment by ChristianHuff-DEV** [comment]
I'm interested to try Goland.

**Comment by andymac4182** [comment]
This will be awesome. Super interested

**Comment by philip-weber** [comment]
I am very interested in trying out the interaction between JetBrains IDEs and GitPod. Please put me on the waiting list. Thank you!

**Comment by penja** [comment]
I wanna play a game!

**Comment by jbduncan** [comment]
I'd love to try out the Gitpod-JetBrains integration too. Thanks in advance. :)

**Comment by Rtinox** [comment]
Me too if possible, thanks in advance 😅

**Comment by ciurte-freelance** [comment]
I`d love to be able to join!

**Comment by szab100** [comment]
+1, add me pls

**Comment by misterjoshua** [comment]
Please add me to the list!

**Comment by cwurtz** [comment]
Please sign me up, thanks!

**Comment by ItCameFr0mMars** [comment]
I would love to help test this!

**Comment by coderroggie** [comment]
Please add me to the list. Thanks!!!!

**Comment by loujaybee** [comment]
Thanks to everyone for your patience—**we're super pumped about this feature!** 🚀🚀🚀

**UPDATE:** So I've added a few of you here into a private Discord channel with instructions for the beta (it's those with the 👀  reaction emojis from me—it's not everyone yet, see below!).

I need to figure out the GitHub username <> Discord username mapping for the rest of you 🤪  so that I can get you added. If you're not part of Discord already: [gitpod.io/chat](https://www.gitpod.io/chat) go ahead and sign up if you want. For those who don't want to/cannot get into Discord, I'll send an email 📧 with instructions shortly 🙏  

If you want to send me (or any of the other gitpodders a message) on Discord and ask to be added to the `beta-testers` role, you'll get added to that chat with more details. Or, you can continue to drop your names here (preferably with your Discord username and we'll get you invited) 🙏 

Thanks all!

**Comment by ryangoodrich** [comment]
please add me to beta!

discord: ryangoodrich
gitpod email: gitlab@ryangoodrich.com

**Comment by CaptainKnuddel** [comment]
Please sign me up

**Comment by fiorenzino** [comment]
Please add me!

**Comment by nitrotol** [comment]
Me too!

**Comment by trakos** [comment]
I'd like to try this, if you're still sending invites.

**Comment by gengjiawen** [comment]
count me in. Also I have been trying using this https://github.com/gengjiawen/cmake-showcase.
Glad official supports it.

**Comment by tim-cts** [comment]
Please sign me up

**Comment by tnb24** [comment]
+1, add me

**Comment by JanSeW** [comment]
Wait, this is a thing? Count me in 🤩
DC: JanSe

**Comment by U1F984** [comment]
Please add me as well. Discord: Leo#2359.

**Comment by flexzuu** [comment]
Hey, Please add me too, Discord user name: flexzuu#4571

**Comment by abkunal** [comment]
Please add me!
Discord username - abkunal#7658

**Comment by muthuishere** [comment]
+1 sign me up

**Comment by ZRDK** [comment]
> Please add me! Discord username - abkunal#7658

**Comment by TSGeek** [comment]
Hi there, i would be happy to try the beta. (discord tag : TheSuperGeek#7885)

**Comment by CalebDelbridge** [comment]
I would like access (Jax#6986)

**Comment by Johnzzon** [comment]
Updating with discord tag: `johnzzon#7058`

**Comment by kiview** [comment]
Please add me: `Kiview#1902`

**Comment by fiveable-jferg** [comment]
I would love to try this out: fiveable-jferg@9866

**Comment by josepjaume** [comment]
I'd like to be part of the beta, please: 

josepjaume#0870

**Comment by sakurayang** [comment]
I am also interested in it, please:

`Gerardyang#7694`

**Comment by yeongsheng-tan** [comment]
I would like to be in the game toooooooo…

**Comment by rjayasinghe** [comment]
Please add me ☺️

**Comment by edwarnicke** [comment]
Please add me :)

Discord username: edwarnicke#0840

**Comment by ItCameFr0mMars** [comment]
Guys you can try it out here:
https://github.com/gitpod-io/template-jetbrains-intellij-idea
it works pretty well.

**Comment by csamak** [comment]
I'd also like to try it: `Quail#6102`

**Comment by JohannesLandgraf** [comment]
> Guys you can try it out here:
> https://github.com/gitpod-io/template-jetbrains-intellij-idea

Not quite correct :) In the private beta you can connect a Gitpod container via Jetbrains' Gateway product to your local Jetbrains IDEs. The link you are referencing refers to their Projector implementation.

**Comment by ItCameFr0mMars** [comment]
I see, I thought that everyone was missing out lol. Anyways I'd love to test the beta
My discord: `ItCameFr0mMars#6559`

**Comment by inistor** [comment]
I'd love to git it a try, too. Please add me - thanks!

**Comment by loujaybee** [comment]
Hey folks! It seems the cat is well and truly out of the bag on this one! [[1](https://en.wikipedia.org/wiki/Letting_the_cat_out_of_the_bag)] 😆 , with the recent JetBrains announcements for remote development: https://www.jetbrains.com/remote-development 🚀 

Also see our Tweet: https://twitter.com/gitpod/status/1465324008950353926?s=20

You'll be pleased to know that the JetBrains beta is available to all Gitpod users (currently IntelliJ and GoLand). There are some things you should be aware of, though before you use the integration. So please read documentation carefully ([you can find documentation on the private beta here](https://www.gitpod.io/docs/editors/jetbrains-private-beta)). Feel free to leave any of your questions on the GitHub issue: https://github.com/gitpod-io/gitpod/issues/6576, and why not come join us in Gitpod in the "jetbrains-private-beta" channel over on Discord to chat: https://www.gitpod.io/chat

**Comment by pocky** [comment]
Hello,

If you want to add phpstorm to the list, I will happily test it! :smile: 

My discord username: pocky#2708

**Comment by Johnzzon** [comment]
Another PhpStorm user here, would love to try this!

**Comment by colin-grapl** [comment]
Intellij Ultimate user, would be interested.
```
email:     colin@graplsecurity.com
discord:  insanitybit#9443
```

**Comment by Vaibhav-Lodha** [comment]
Interested in Pycharm, discord : Vaibhav#2151

**Comment by Dragomeat** [comment]
PhpStorm user. Please add me

Email:      i@dragomeat.com
Discord:  Dragomeat#2308

**Comment by gtlovett** [comment]
Please add me!

**Comment by tkislan** [comment]
Interested here: Pycharm, Webstorm, Datagrip
email: kislan.tomas@gmail.com

**Comment by PaulFWatts** [comment]
I would like to join the beta for Rider. I have a license for all the JetBrains products and use Rider to code F#. Thanks!

**Comment by sualehasif** [comment]
Hi Hi I would really love to be on the private beta for CLion. 
Email sualeh@anysphere.net

**Comment by scopsy** [comment]
Hi! would love to join the private beta for webstorm 

Discord username: scopsy

**Comment by ZRDKPoWeR** [comment]
Zrdk76

**Comment by sr229** [comment]
Heya, sign me up! I'm Ayane#8660 on Discord.

**Comment by pawlean** [comment]
Hi folks, I see so many people wanting to be added to this but it is now, in fact, public to everyone. See [Lou's comment](https://github.com/gitpod-io/gitpod/issues/6342#issuecomment-981957772) above.

See the docs [here](https://www.gitpod.io/docs/editors/intellij) too.

**Comment by axonasif** [comment]
> Hi folks, I see so many people wanting to be added to this but it is now, in fact, public to everyone. See [Lou's comment](https://github.com/gitpod-io/gitpod/issues/6342#issuecomment-981957772) above.
> 
> See the docs [here](https://www.gitpod.io/docs/editors/intellij) too.

Thanks for the clarification, I was still confused on it ahahah 😅
