### ISSUE TITLE
New Project page should show message and link to /workspaces when authorized only with Bitbucket

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#6345]
### Bug description

Teams & Projects rolled out with support for GitLab and GitHub projects. The natural next step here is to add support for adding projects from Bitbucket.org git provider, see https://github.com/gitpod-io/gitpod/issues/5980.

However, if you have a Gitpod account that is only connected with a Bitbucket account, adding a project is not possible, see screenshot below.

![Screenshot 2021-11-04 at 14 26 39](https://user-images.githubusercontent.com/849592/140332003-59cda0e7-0959-44a3-aeff-c67226f20563.png)

### Steps to reproduce

1. Create an account on Gitpod with Bitbucket
2. Try adding a project

### Expected behavior

Instead of the error while showing loading, show the following message

> We are still working working on Bitbucket support for Projects.
> Continue to [workspaces](), or login with GitHub or GitLab to use Projects.   

This ☝️ is a variant of what was proposed originally. 👇 -- thanks  @gtsiolis

> Possibly, if we move forward with fixing this before https://github.com/gitpod-io/gitpod/issues/5980, we could redirect to an error page and informing the user to connect a supported git provider for adding projects. 💡 ~~

**Comment by JanKoehnlein** [comment]
To test it, we have to re-enable Bitbucket auth on core-dev. Waiting for team platform to [deploy the new secrets](https://gitpod.slack.com/archives/C01KGM9EBD4/p1636993758304200)
