### ISSUE TITLE
Allow admin users to download workspaces

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6351]
We once had a "Download workspace content" button on the admin dashboard which was quite handy when trying to analyze abuse. Would be nice to have it again!

![missing-button](https://user-images.githubusercontent.com/32448529/138421008-57e8593e-a290-4334-b775-24ca679c2f4a.png)

- [x] Add download button to admin dashboard
- [ ] Adjust the [workspace download route config](https://github.com/gitpod-io/gitpod/issues/6351#issuecomment-982373095)

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6351#issuecomment-957780283):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
> In the scope of this issue, to avoid having another secondary button with the same weight next to the _Reload Data_ button, I'd suggest to 🅰️ replace that button with the _Download Workspace_ button or 🅱️ introduce a more actions button that groups _Reload Data_ and _Download Workspace_ actions. What do you think?

@gtsiolis Is the "Reload Data" button used a lot / helpful? Maybe related to the previous point? 👇🏼

> 2. Automatically refresh page data for user pages in the admin dashboard which is not hapening at the moment, see [[dashboard] Admin dashboard #3723 (comment)](https://github.com/gitpod-

@gtsiolis The link didn't direct me to a comment regarding reload data, though.

**Comment by gtsiolis** [comment]
> Is the "Reload Data" button used a lot / helpful? Maybe related to the previous point? 

@laushinka the button was added because we currently do not fetch in background new data in the page, see comment in https://github.com/gitpod-io/gitpod/pull/3723#discussion_r606983903. Oh, just noticed the link is not working. It seems there are some console log errors when loading https://github.com/gitpod-io/gitpod/pull/3723#discussion_r606983903 which could be related. I'm attaching the screenshot below to the relevant discussion.

| Screenshot of https://github.com/gitpod-io/gitpod/pull/3723#discussion_r606983903 | 
|-|
| <img width="827" alt="Screenshot 2021-11-29 at 2 46 24 PM" src="https://user-images.githubusercontent.com/120486/143871734-8374941a-5041-49de-b1db-7032b6028be5.png"> |

> Also, would we have more actions in the future?

Yes, I'd expect us to add more actions in the future. 🗺️ 

> If yes, an actions button would probably make more sense. However option A also makes sense below.

I'd vote to go with option :a: for now unless we need the reload button. 🗳️ 

🍊 🍊 🍊 🍊 

> The link didn't direct me to a comment regarding reloading data.

You're right, see comment and screenshot above. 🆙 

> I assume the data reload would happen in every page visit/refresh. Is there another issue where a manual reloading would have to be triggered? Not meaning to go very deep into the issue - just to know whether that button is crucial. If not then for now we can go with option A.

❗ **issue:** Reloading to fetch new data like remaining hours,, roles, etc sounds ok here. The only anti-pattern here is that the workspaces list of a user is not auto-updated as the workspaces list within the dashboard.

**Comment by laushinka** [comment]
> I'd vote to go with option 🅰️ for now unless we need the reload button. Replacing the reload button with the download button sounds like a good MVC (minimum viable change) and will bring in value on the deployment. 🗳️

Yes, agree! Did that [in the PR](https://github.com/gitpod-io/gitpod/pull/6962) 🙏🏼

**Comment by geropl** [comment]
(context: [PR review](https://github.com/gitpod-io/gitpod/pull/6962#pullrequestreview-818660469))

Besides the button will also need to adjust the proxy route `/workspace-download/get/<wsId>`. Because of CORS we need it to be a transparent proxy, but atm it only does "lookup + redirect" ([config](https://github.com/gitpod-io/gitpod/blob/6954bbdfe70f531625af16cb5ebb2b37ee52b974/components/proxy/conf/Caddyfile#L150-L165), [plugin](https://github.com/gitpod-io/gitpod/blob/6954bbdfe70f531625af16cb5ebb2b37ee52b974/components/proxy/plugins/workspacedownload/workspace_download.go#L45)). This works for storages that are hosted under the deployments base domain (true for minio in `devstaging` for example!), but not GCloud, AWS, etc., which are hosted on a different base domain.

We already implemented something very similar for headless logs ([config](https://github.com/gitpod-io/gitpod/blob/6954bbdfe70f531625af16cb5ebb2b37ee52b974/components/proxy/conf/Caddyfile#L167-L178), [plugin](https://github.com/gitpod-io/gitpod/blob/6954bbdfe70f531625af16cb5ebb2b37ee52b974/components/proxy/plugins/headlesslogdownload/headless_log_download.go#L1-L174)) which we could copy over.

@laushinka  Happy to pair on this/review if that might help.

**Comment by laushinka** [comment]
> @laushinka Happy to pair on this/review if that might help.

@geropl Sounds great! Let's have a quick call on this 🙏🏽

**Comment by laushinka** [comment]
After discussion with @geropl, we have two tasks for this issue:

- [ ] Add download button to admin dashboard
- [ ] Adjust the [workspace download route config](https://github.com/gitpod-io/gitpod/issues/6351#issuecomment-982373095)
