### ISSUE TITLE
[Installer]: add the number of replicas required for a deployment in the config

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6357]
Currently, all of the deployments have a replica value of `1` (with a `todo` above them). This needs to be configurable.

Config change proposal:
 - Add a default number of replicas, which should default to `2`. Suggest putting this under `workspace.replicas.default`
 - Add in an optional map of key/value pairs under `workspace.components[$componentName].replicas`. This would then be extensible for any future configuration we need for components that cannot be inferred

**Comment by csweichel** [comment]
> This needs to be configurable.

Please outline why this needs to be configurable. Which use-cases do we need to support?

---

Pasting the PR comment for future reference:

> 1. The motivation that we need to add this "for debugging" does not warrant a config change. There are indeed cases where an increased replica-count of some components makes sense (e.g. SaaS prod), but for now the vast majority of installations will happily run with a replica count of 1.
> 2. Not all components can run with a replica count > 1. E.g. `ws-manager`, `ws-manager-bridge` or `ws-scheduler`.
> 3. Having this setting under `workspace` in the configuration seems odd. These replica counts do not affect workspaces, but rather other components which service workspaces.
> 
> Lastly - and as discussed before - configuration format like `components: map[string]struct{}` is a slippery slope; one that we're just trying escape with this installer effort. It quickly leads to a haphazard expansion of options, most of which make sense to us, but not to our users. We must design the configuration surface with our users and their use-cases in mind, not with our technical perspective on Gitpod.
> 
>  I'd propose that all changes to the configuration surface in the future need to outline/describe the use-case they aim to support from a user perspective. If the user is us, there needs to be a discussion on the impact, potential confusion and way of documentation towards our users.

**Comment by csweichel** [comment]
I'm not sure this change makes sense this way - and I'm sorry for not reacting on the issue sooner.

1. The motivation that we need to add this "for debugging" does not warrant a config change. There are indeed cases where an increased replica-count of some components makes sense (e.g. SaaS prod), but for now the vast majority of installations will happily run with a replica count of 1.
2. Not all components can run with a replica count > 1. E.g. `ws-manager`, `ws-manager-bridge` or `ws-scheduler`.
3. Having this setting under `workspace` in the configuration seems odd. These replica counts do not affect workspaces, but rather other components which service workspaces.

Lastly - and as discussed before - a configuration format like `components: map[string]struct{}` is a slippery slope; one that we're just trying escape with this installer effort. It quickly leads to a haphazard expansion of options, most of which make sense to us, but not to our users. We must design the configuration surface with our users and their use-cases in mind, not with our technical perspective on Gitpod.

I'd propose that all changes to the configuration surface in the future need to outline/describe the use-case they aim to support from a user perspective. If the user is us, there needs to be a discussion on the impact, potential confusion and way of documentation towards our users.

For this specific instance issue, i.e. replica count, we could:
- change to more sensible defaults ourselves, e.g. 2x `server` and `{openvsx-, ws-, cloudsql, }proxy`
    - 👍  requires no config change, but makes the installation more resilient
    - 👎  increases TCO of the installation
    - 👎  ships with an increased cost in situations where the extra reliability is not required, e.g. core-dev or a "playground self-hosted installation"
- introduce a top-level `replicas` configuration setting like:
    ```Go
    type Configuration {
        Replicas ReplicasConfiguration `json:"replicas,omitempty"`
    }
    
    type ReplicasConfiguration {
        Server  int `json:"server,omitempty"`
        Proxy   int `json:"proxy,omitempty"`
        WSProxy int `json:"ws-proxy,omitempty"`
    }
    ```
    - 👍  does (not yet) introduce `components` field and is easy to auto-migrate if we ever need to
    - 👍  is very explicit and does not have "hidden defaults". We could auto-fill our default choices on `installer init`
    - 👍  supports scaling the installation, because specifically `server` only scales through an increased replica-count
    - 👎  is rather verbose and "first-time users" might feel the need to change these values

**Comment by corneliusludmann** [comment]
Consider this as closed with https://github.com/gitpod-io/gitpod/pull/9495. Please re-open if not.
