### ISSUE TITLE
Environment variables in Dockerfile no longer persist

### ISSUE THREAD

**Issue by HorizonShadow** [gitpod-io/gitpod#637]
**Describe the bug**
I have this line in my Dockerfile.gitpod
```
ENV RACK_ENV=gitpod
```
In the past, this correctly set the RACK_ENV env var. It no longer does.

**To Reproduce**
Set an environment variable in a Docker file that the gitpod is built from

**Expected behavior**
It should set the environment variable.

**Comment by AlexTugarev** [comment]
@HorizonShadow thanks for reporting this! I'm taking care of this.

**Comment by AlexTugarev** [comment]
@HorizonShadow we deployed a fix for this issue 🎉

Please have a look!

**Comment by HorizonShadow** [comment]
@AlexTugarev Works great, thanks!
