### ISSUE TITLE
Visual bug with underlines

### ISSUE THREAD

**Issue by tiagodinis33** [gitpod-io/gitpod#6370]
### Bug description

the background color of underlines and the next character becomes black
![imagem](https://user-images.githubusercontent.com/92828847/138522279-89ec7254-c0cd-41b9-b9d6-1148b09e461a.png)

### Steps to reproduce

write a underline followed by a character

### Expected behavior

normal background color

**Comment by axonasif** [comment]
@tiagodinis33 I am unable to reproduce this, what's your operating system configuration?
