### ISSUE TITLE
0.11.0 release

### ISSUE THREAD

**Issue by yusufali94** [gitpod-io/gitpod#6373]
So it has been on 0.10.0 for quite some time now and I see alot of new features. When can we expect the next release onto selfhosted?

**Comment by MrSimonEmms** [comment]
The [Installer](https://github.com/gitpod-io/gitpod/tree/main/installer) has now been released. Anyone after a more recent self-hosted release than the 0.10.0 Helm release should go there in the first instance.

Please raise any tickets dealing with issues you may have.

The Installer is brand new (the first release was just over 2 weeks ago) and, whilst stable and effective, may not work for every scenario. As self-hosted conceivably has to cater for every single developer and company in the world, there are many permutations to what we need to support. Whilst we have endeavoured to capture every possible permutation, there will be many that we've not thought of or (more likely) not been aware of Gitpod being used in that way. Please raise tickets or join in the [community](https://www.gitpod.io/community) if the Installer doesn't quite meet your needs and we'll do what we can to support it.

Remember, we can only help on scenarios that we know about - the more we know about, the better the Installer will be
