### ISSUE TITLE
Error: 4 DEADLINE_EXCEEDED: Deadline exceeded

### ISSUE THREAD

**Issue by tnir** [gitpod-io/gitpod#6377]
In some cases, we see the following error:

![](https://community.gitpod.io/uploads/default/optimized/2X/5/544da6d26783f4cf761dd84f153be6611c39c526_2_690x388.jpeg)

Image courtesy of https://community.gitpod.io/u/coder2195text

That does not provide any information worth resolving the problem.

## Solution

Update the (error) message to make (end) users take some actions to resolve the problem.

## Ref.

- https://community.gitpod.io/t/error-4-deadline-exceeded-deadline-exceeded/4870

**Comment by kylos101** [comment]
We can do better here with the messaging, thank you for the report, we'll discuss what phrasing would make sense and update accordingly.

**Comment by sagor999** [comment]
I believe we made improvements to our error messaging in the last months. @kylos101 can you confirm? If so, we can close this issue.

**Comment by kylos101** [comment]
> I believe we made improvements to our error messaging in the last months. @kylos101 can you confirm? If so, we can close this issue.

Hey @sagor999 , is it still possible to return this message to the user?

**Comment by sagor999** [comment]
Unfortunately it is not clear where this error even came from. And since it was created back in October, I cannot even find logs related to that workspace.
But I do know that we improved error reporting since then.
I will close this, and in case if it ever pops up again, we can re-open and investigate.

**Comment by tnir** [comment]
@sagor999 Thanks for checking. I think we can close this now.
