### ISSUE TITLE
Show invited users

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#6379]
If we add users and add for them a license we can not easily check who has not signed in and ping him again.
In the manage Team we just have this fields.
On top, it would be great to just see the last used date for the license.

![image](https://user-images.githubusercontent.com/1100969/138647252-96bd9f33-e437-4cc4-b93f-e81ad03d1348.png)

**Comment by gtsiolis** [comment]
Cross-linking https://github.com/gitpod-io/gitpod/issues/7759.

**Comment by gtsiolis** [comment]
Keeping this closed as #7759 has been completed, and we're moving towards the new usage based pricing and teams.

Instead, we can work on surfacing the pending invitations (invited members) in the new teams after allowing users to invite team members by email, see https://github.com/gitpod-io/gitpod/issues/6154.

Cc @geropl @jldec
