### ISSUE TITLE
Add Ctrl+K shortcut for the built-in shell

### ISSUE THREAD

**Issue by koppor** [gitpod-io/gitpod#638]
The built-in shell supports <kbd>Ctrl</kbd>+<kbd>A</kbd> to go to the beginning of a line and <kbd>Ctrl</kbd>+<kbd>E</kbd> to go to the end of the line.

I am used to <kbd>Ctrl</kbd>+<kbd>K</kbd> to kill everything from the cursor to the end. In my setting, my muscle memory pressues <kbd>Ctrl</kbd>+<kbd>A</kbd> and then <kbd>Ctrl</kbd>+<kbd>K</kbd> to empty the prompt (and not <kbd>Ctrl</kbd>+<kbd>C</kbd>).

Would it be possible to add support for <kbd>Ctrl</kbd>+<kbd>K</kbd>, too?

**Comment by svenefftinge** [comment]
We'd need to check why we are not forwarding CTRL+K atm.

**Comment by koppor** [comment]
checked with https://gitpod.io as of today and the issue persists.
