### ISSUE TITLE
Do not submit form on enter when there's no focus when deleting user or team

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#6383]
### Bug description

Users can delete their account by going to [`/account`](https://gitpod.io/account), clicking _Delete Account_, and then clicking enter without even focusing on the modal or on any input or button within the modal. ⚠️ 

This is also bypassing the disabled state of the primary action button within the confirmation modal that requires the user to type their email to confirm. ❗ 

This affects :a: user and :b: team deletion.

See also https://github.com/gitpod-io/gitpod/issues/6371.

Cc @laushinka because https://github.com/gitpod-io/gitpod/pull/6058 in case this is related.

### Steps to reproduce

For user deletion bug:

1. Create a team
2. Go to team settings
3. Click Delete Team
4. Press enter without focusing on the modal or typing the team name

For user deletion bug:

1. Go to account settings
2. Click Delete Account
3. Press enter without focusing on the modal or typing the team name

**Comment by laushinka** [comment]
Wow great catch, @gtsiolis 😨
