### ISSUE TITLE
Installing pari using brew and giving linuxbrew priority in $PATH breaks new bash console

### ISSUE THREAD

**Issue by tobiasdiez** [gitpod-io/gitpod#6388]
### Bug description

Installing pari using brew and giving linuxbrew priority in `$PATH` breaks the creation of the bash console.

### Steps to reproduce

- `brew install pari`
- PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
- Create a new bash console
- Get the following error
```
Reading GPRC: /etc/gprc
GPRC Done.

  ***   error opening input file: `completion'.  ***   syntax error, unexpected real number, expecting $end:
```
Reason is that 
https://github.com/gitpod-io/gitpod/blob/4dd5268d6889f0f01c34af37cda7ce521b49143a/components/image-builder/workspace-image-layer/gitpod-layer/debian/gitpod/.bashrc-prepend#L27-L28
executes pari/gp (https://pari.math.u-bordeaux.fr/) instead of gitpods `gp` command.

### Expected behavior

No error

**Comment by kylos101** [comment]
Thank you for the report, @tobiasdiez , I've scheduled this work accordingly. :smile:

**Comment by csweichel** [comment]
I'm afraid we cannot rename `gp` at this point - it would break the experience of many users who, in their scripts, rely on the existence and behaviour of `gp`.

**Comment by tobiasdiez** [comment]
Backwards compatibility is indeed an issue. What would however already help if all gitpod-owned scripts (e.g. bashrc in the docker image) would use a new `gitpod` command. Then one could install an alias from `gitpod` to `gp` for backwards compatibility and installing pari wouldn't break anything (except one's own scripts which one then has to migrate to use `gitpod` as well).

**Comment by kylos101** [comment]
Hey @tobiasdiez , in the the meantime, how are you running your workload? Are you able to run it within a docker container (that way, the path wouldn't need to have priority for pari)?

**Comment by tobiasdiez** [comment]
For now I install pari manually (not using brew) and don't put it in path.

**Comment by kylos101** [comment]
Okay, thanks for the heads up, @tobiasdiez . I wanted to leave this issue open until we received confirmation that you were able to run your workload. For now, I am going to close this issue (as we won't be renaming `gp`, and it should generally have priority on the path).
