### ISSUE TITLE
Docker images based on microsoft/dotnet (like lambci/lambda) don't work in Gitpod

### ISSUE THREAD

**Issue by sudeepcv** [gitpod-io/gitpod#639]
**Describe the bug**
using lambci/lambda dockerfile not working
https://hub.docker.com/r/lambci/lambda/dockerfile

**Comment by jankeromnes** [comment]
Hi @sudeepcv, indeed you're right, trying with this as my `.gitpod.yml`:

```yaml
image: lambci/lambda
```

Results in this Gitpod error:

<img width="324" alt="Screenshot 2019-06-27 at 10 54 23" src="https://user-images.githubusercontent.com/599268/60252138-079c2480-98ca-11e9-9759-e791704f6034.png">

Actually, we currently only support images based on Ubuntu, Debian or Alpine.

Could you please tell me more about what you're trying to achieve? Maybe I can help you in spite of this limitation.

**Comment by meysholdt** [comment]
What's `lambci/lambda` based on?

**Comment by jankeromnes** [comment]
Docker Hub says

> FROM microsoft/dotnet:2.1-sdk
