### ISSUE TITLE
Add a feature banner to hosted VSCode

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6392]
The release of [https://vscode.dev/](https://vscode.dev/) came with an update banner shown above the IDE. 

![Screenshot 2021-10-25 at 19 08 29](https://user-images.githubusercontent.com/5528307/138747643-685c0c6f-1d6f-4ab6-bc19-cd6ba8b6ff46.png)

This would be useful functionality to have in Gitpod to surface news, features, or general announcements. 

We have [similar functionality in the Gitpod website](https://github.com/gitpod-io/website/blob/ba9dd1864f61a7b6537c69189bdd0128ef5ae75a/src/components/banners/announcement.svelte) used for announcements. We should also consider the banner to have a start and/or end date so that it does not need to be manually added or removed / deployed. 

See ([internal link](https://gitpod.slack.com/archives/C01KGM9BH54/p1634746088346300))

CC: @mikenikles (incase you have additional notes to add 🙏 )

**Comment by loujaybee** [comment]
This could actually be used for different use-cases, such as providing: 

1. A logical path back to the dashboard (this was an issue observed in usability testing)
2. Helping users to understand their workspace context, e.g. https://github.com/gitpod-io/gitpod/issues/4129 and https://github.com/gitpod-io/gitpod/issues/6227

**Comment by imskr** [comment]
Can I work on this?

**Comment by loujaybee** [comment]
@imskr - Sure, if you want to provide some details here of what you plan, we can try to collaborate before you spend invest too much time in a PR. 🙏 Also linking related roadmap item: https://github.com/gitpod-io/gitpod/issues/7537
