### ISSUE TITLE
Change dashboard default theme to system for new users

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#6395]
### Problem to solve

The default dashboard theme currently is set to _Light_.

However, the dashboard supports syncing the theme with the dashboard, including workspace loading and login pages, using [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

This setting could be hard to discover and automatically using the system theme can improve UX for users that also prefer syncing system theme with light or time conditions. For example, see [relevant macOS settings](https://support.apple.com/en-gb/guide/mac-help/mchl52e1c2d2/mac).

### Proposal

Change dashboard default theme to system. 🌔 

Things to consider:

1. There's no dark theme for `gitpod-io/website`.
2. There's no option to automatically sync editor theme. See also https://github.com/gitpod-io/gitpod/issues/3982.
3. We only use local storage and do not persist theme selection for users.

**Comment by jankeromnes** [comment]
> ### Proposal
> 
> Change dashboard default theme to system. 🌔 

Yes 💯 💯 💯 

I've wanted to do this for a while. @JanKoehnlein / @jldec cool to schedule?

**Comment by gtsiolis** [comment]
Taking a **bias-for-action** and scheduling this in groundwork. @jldec feel free to remove if needed. Cc @JanKoehnlein 

/schedule

**Comment by jldec** [comment]
👍 to self-scheduling
