### ISSUE TITLE
[Terminal] On some systems the fonts look odd

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#64]
I never saw it in reality but on pictures in tweets from Asian (only Japanese?) users and also this blog post [1].

http://www.ksakae1216.com/entry/2018/09/06/090000

![image](https://user-images.githubusercontent.com/372735/45139262-77141c80-b1af-11e8-9330-ab8db0a0cecf.png)

**Comment by hidehiro98** [comment]
I got the same issue with the Japanese environment.
OS: macOS High Sierra
Browser: Google Chrome
<img width="1493" alt="2019-02-12 20 50 37" src="https://user-images.githubusercontent.com/5709877/52633564-33fd6880-2f08-11e9-831b-a99ca7730f83.png">

**Comment by svenefftinge** [comment]
@hidehiro98 I tried to reproduce it by using a Japanese keyboard layout but couldn't.
I'm on a OS X and tried with Chrome. Any idea how to reproduce it?
Also do you see this in the demo on https://xtermjs.org/ as well?

**Comment by AlexTugarev** [comment]
@svenefftinge, it might be the [`monospace` font-family](https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/style/variables-dark.useable.css#L78), which is specific to the desktop env, e.g. 
<img src="https://i.stack.imgur.com/7N5XB.png" />

In that case we need to define proper fonts before `monospace` for terminals.

**Comment by svenefftinge** [comment]
@AlexTugarev are you able to reproduce the issue? I don't understand what the screenshot should tell me.

**Comment by svenefftinge** [comment]
Ah I think I got it. I will introduce an `editor.fontFamily` preference and use it in terminal and editor.

**Comment by AlexTugarev** [comment]
@svenefftinge, it's tricky to find a unsuited font, but eventually I could reproduce it with `Meiryo UI Regular`. You can set it at `chrome://settings/fonts` for `monospace` font-family. (the screenshot from above was showing IE equivalent of the same kind of settings.)

![screen shot 2019-02-19 at 08 38 16](https://user-images.githubusercontent.com/914497/52997838-edd16900-3421-11e9-899f-da1b835fc763.png)


> I will introduce an `editor.fontFamily` preference and also `terminal.integrated.fontFamily` which defaults to `editor.fontFamily`

👍 I think that will to the trick. ;-)

**Comment by svenefftinge** [comment]
See https://github.com/theia-ide/theia/pull/4369

**Comment by AlexTugarev** [comment]
I think this issues has to be fixed for the terminals showing workspace builds as well.

**Comment by svenefftinge** [comment]
> I think this issues has to be fixed for the terminals showing workspace builds as well.

The other terminals go with the default `fontFamily`which I think should work fine. Did you test it?

**Comment by AlexTugarev** [comment]
![screen shot 2019-02-21 at 10 28 47](https://user-images.githubusercontent.com/914497/53158284-85ba8880-35c3-11e9-9273-4ed6dbc55c97.png)

'Confirming this. Other terminals look good.
