### ISSUE TITLE
How to turn off linters?

### ISSUE THREAD

**Issue by justinmoon** [gitpod-io/gitpod#640]
The python linters are very loud. How can I turn them off?

I tried uninstalling all of the linting packages for pytho2 and python3 in my `Dockerfile` as well as creating a `setup.cfg` file in my project directory. The `setup.cfg` effectively muted output when running the linters in the command line, but had no effect on the linters running in the editor. Is a different python installation responsible for these?

Thanks.

**Comment by justinmoon** [comment]
The first time I save a python file after rebooting my workspaces a bunch of binaries are copied to `/workspace/.pip-modules/bin`. I see the point of this folder: to persist packages between installations. But how can I remove them? I can't get rid of these nasty files for good!

**Comment by justinmoon** [comment]
Sometimes they're even copied to `~/.pyenv/shims` ...

**Comment by justinmoon** [comment]
There a "stop python language server" option in the command pallet that worked. 

Not going to close the I would like `python-language-server` to stay running because I want to make use of the "Go to Definition"  -- would just like to turn off or at least configure the linter to be quieter.

**Comment by AlexTugarev** [comment]
Hi @justinmoon! You can [create a `setup.cfg` or a `pycodestyle.cfg` in the project root](https://github.com/palantir/python-language-server#configuration) and [adjust pycodestyle](http://pycodestyle.pycqa.org/en/latest/intro.html#configuration) rules there like this:

```
[pycodestyle]
ignore = E226,E302,E41
max-line-length = 160
statistics = True
```

**Comment by AlexTugarev** [comment]
> The first time I save a python file after rebooting my workspaces a bunch of binaries are copied to /workspace/.pip-modules/bin. I see the point of this folder: to persist packages between installations. But how can I remove them? I can't get rid of these nasty files for good!

By default all packages are installed into a user site sitting in the workspace directory, which allows us to persist the packages between workspace restarts. Those binaries belong to the installed modules, thus they are removed on `pip uninstall ...` as well.

**Comment by JesterOrNot** [comment]
aren't there global user settings now? can't you turn them off globally like that now?
