### ISSUE TITLE
[self-hosted] Unable to load schema from 'https://gitpod.io/schemas/gitpod-schema.json': No content.

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#6402]
### Bug description

When launching a Gitpod workspace, the `.gitpod.yml` file will sometimes report this error in VS Code
![image](https://user-images.githubusercontent.com/9018897/138895996-44bd165f-e8ce-4a7f-b8fa-8aed92bfd043.png)

This was previously mentioned in https://github.com/gitpod-io/gitpod/issues/4967 but was not reproduceable.

It is worth noting the endpoint is actually available with the self-hosted Dashboard at `https://gitpod.<gitpod_domain>/schemas/gitpod-schema.json`. Perhaps with self-hosted installations it would be better to use the custom domain endpoint rather than the public internet service.

### Steps to reproduce

This is VERY difficult to reproduce. It occurs occasionally when launching a workspace and viewing the `.gitpod.yml` file and its contents. It has been happening consistently enough over the past few weeks with a 0.10.0 self-hosted deployment to warrant an issue.

### Workspace affected

n/a

### Expected behavior

Gitpod schema is loaded for the YAML parser.

### Example repository

n/a

## Environment
Gitpod v0.10.0 (self-hosted)
Ubuntu LTS 20.04.3
RKE 1.20.11
containerd 1.4.9

**Comment by csweichel** [comment]
This strikes me as either a CORS issue on the endpoint (@gitpod-io/engineering-meta) or something we should change in the IDE (@gitpod-io/engineering-ide).

@akosyakov wdyt?

**Comment by akosyakov** [comment]
We are running quite outdated yaml extension in VS Code (3 months old). It would be good first to update it.

**Comment by akosyakov** [comment]
What interesting though that this error reported only if content was not empty, on network error there will be another error: https://github.com/redhat-developer/yaml-language-server/blob/6df37d38dfe7bedce12aee4175fbe7da05b8e333/src/languageservice/services/yamlSchemaService.ts#L601-L634 I am not sure how that can be happen.

**Comment by JanKoehnlein** [comment]
Nit: Removing all team labels moves an issue into Nirvana from my perspective

**Comment by jgallucci32** [comment]
@csweichel I enabled debugging tools in the browser and do not see any errors relating to CORS. In fact I am not seeing any browser-based errors with regards to the schema not loading properly.

@akosyakov What is the best way to get more detailed logs for this error?

**Comment by akosyakov** [comment]
@jgallucci32 It is done by yaml vscode extension in the remote extension host process. You can go to the output view and inspect channels for yaml, remote extension host process, remote server and window.
