### ISSUE TITLE
Change workbench preferred color themes

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#6403]
### Problem to solve

1. We currently default to Gitpod Light theme for VS Code.

2. VS Code 1.42 introduced[[1](https://code.visualstudio.com/updates/v1_42#_auto-switch-theme-based-on-os-color-scheme)] the ability to auto switch theme based on OS color scheme, using the following settings:

```
workbench.preferredLightColorTheme
workbench.preferredDarkColorTheme
```

3. Current workbench defaults for preferred color themes still use the default Light+ and Dark+ themes that come with VS Code.

<img width="739" alt="Screenshot 2021-10-26 at 4 25 54 PM" src="https://user-images.githubusercontent.com/120486/138895890-00ab5a3c-dd8e-443b-9dab-424d67cc390a.png">

4.  Automatically using the system theme for VS Code can improve UX for users that also prefer syncing system theme with light or time conditions. This is also under consideration for Gitpod's dashboard theme, see https://github.com/gitpod-io/gitpod/issues/6395.

5. Once this changes is live it could make syncing the theme between dashboard and editor obsolete, see https://github.com/gitpod-io/gitpod/issues/3982.

See [relevant discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1635187855111600) (internal).

### Proposal

Change workbench preferred color themes so that the editor automatically switches to Gitpod Light or Gitpod Dark if the user never changed their theme.

**Comment by Shulammite-Aso** [comment]
Hi @gtsiolis @loujaybee  @akosyakov @ghuntley I'd like to take this up if no one is yet working on it. 

I think defaulting workspace and dashboard color themes with system theme is great idea too.

If I'm free to take it up, would just need clarification on what is meant by "workbench"? I feel i have a very high level idea of what it might mean; the development environment allocated to each user, where workspaces gets created? correct me please if i'm wrong, and perhaps any other smaller details that would help me better understand and work on this feature.

Also what files or folder would i find the code that i need to make changes to?

**Comment by gtsiolis** [comment]
Hey @Shulammite-Aso! Every contribution is welcome! 

Since :a: this has been removed from the **[Product Engineering Groundwork](https://github.com/orgs/gitpod-io/projects/3)** and :b: there's no assignee, no one from the team is actively working on this, so feel free to open a pull request for this. 🏓 

Pasting from the [relevant docs](https://code.visualstudio.com/api/extension-capabilities/extending-workbench) in VS Code:
> "Workbench" refers to the overall Visual Studio Code UI that encompasses the following UI components:

> Also what files or folder would i find the code that i need to make changes to?
Haven't checked what files should be changed but overall the idea is to set the following two settings:

```
...
    "workbench.preferredLightColorTheme": "Gitpod Light",
    "workbench.preferredDarkColorTheme": "Gitpod Dark"
...
```

Looping in @jeanp413 and @akosyakov in case they have any pointers to share.

**Comment by akosyakov** [comment]
@jeanp413 I looked through VS Code and could not find an easy way to customize default settings, i.e. like via workbench.ts. Maybe you have an idea whether it is possible? The only way I see is to change default values [here](https://github.com/gitpod-io/openvscode-server/blob/9d092bc97a8ec1050dc83bdb43ed3603aa74fccb/src/vs/workbench/services/themes/common/themeConfiguration.ts#L43-L71). Does it look good?

**Comment by jeanp413** [comment]
@akosyakov Why is not possible not set it in `configurationDefaults` in `workbench.ts`? Or is vscode just ignoring it?

**Comment by akosyakov** [comment]
@jeanp413 oh, thanks! I overlooked it.

**Comment by akosyakov** [comment]
@Shulammite-Aso You can contribute it here: https://github.com/gitpod-io/openvscode-server/blob/7a7d2cc5a46293eec48f9d1c619c95ce9c78640c/src/vs/gitpod/browser/workbench/workbench.ts#L834-L836, PR should be opened against gp-code/main branch.

**Comment by Shulammite-Aso** [comment]
Okay @akosyakov, would do just that!

**Comment by jeanp413** [comment]
@gtsiolis should be in tomorrow's insiders so you can do quick check

**Comment by gtsiolis** [comment]
That's great to hear, @jeanp413!

Also, thanks @Shulammite-Aso for contributing! 🧡

**Comment by gtsiolis** [comment]
Closing as this has been resolved in https://github.com/gitpod-io/gitpod/issues/6403. Thanks again, @Shulammite-Aso!
