### ISSUE TITLE
Unable to open workspace

### ISSUE THREAD

**Issue by James-VT** [gitpod-io/gitpod#6429]
### Bug description

My workspace is currently "hanging." First it was stuck in stopping, now it's stuck in starting.

### Steps to reproduce

It made the transition from "stopping" to "starting" when I tried closing the tab for it and reopening via Github which I now realise I should not have done, but having done that, it's now stuck in "Starting" instead of "stopping." Fortunately the workspace is pinned so it should be retrievable, I hope? As to how it got stuck in "stopping" in the first place, I couldn't really tell you. I opened up Chrome to that tab and there it was: "stopping."

### Workspace affected

https://gitpod.io/start/#apricot-ape-m93uez1t

### Expected behavior

The workspace, working.

### Example repository

I'm afraid I can't do that as I can't get it to open.

### Anything else?

This happened once before during my last project but I can't for the life of me remember how it got fixed. I don't recall filling in this form, so apologies if this isn't the way to go about it for this issue.

**Comment by csweichel** [comment]
> I've seen your Discourse message @James-VT, let's continue the conversation there? Feel free to close this.
