### ISSUE TITLE
Error: Cannot read property 'sha' of undefined

### ISSUE THREAD

**Issue by nico-abram** [gitpod-io/gitpod#643]
When attempting to open https://gitpod.io/#https://github.com/nico-abram/rusty-boy-advance/ , I get the following: https://i.imgur.com/uBmFwI4.png

**Comment by nico-abram** [comment]
I think the issue was I had `file: Dockerfile` and it was called `dockerfile`. However, a better error message would be nice.

**Comment by JesterOrNot** [comment]
see #692

**Comment by jankeromnes** [comment]
Ah, sorry about the misleading error message. I'm glad that you found the root cause anyway! 💯 

I'll close this issue, because the original problem was solved, and there is already #717 requesting a better error message.

**Comment by flamecopper** [comment]
I just faced this issues today, has it been fixed? It has been over a year
