### ISSUE TITLE
All terminals in a workspace open to the side

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#6434]
### Bug description

Gitpod opens all configured terminals in one tab, although they should be in separate ones.

![image](https://user-images.githubusercontent.com/29888641/139214241-c98b2849-e8c0-4aa1-bf7a-289074052410.png)

Also applicable to the Insiders build of desktop VS Code via the local app: (thanks to @bigint for the recording and reporting the issue in [our Discord](https://gitpod.io/chat)).
https://www.loom.com/share/4c107d2e7d83418f8ee58f2bc81af57d

### Steps to reproduce

1. Open a repository with multiple terminals set up (e.g. https://github.com/gitpod-io/template-nixos) in Gitpod
2. Observe that the two terminals (configured to be in different tabs) are group

### Workspace affected

all

### Expected behavior

VS Code should respect the gitpod.yml configuration

### Example repository

https://github.com/gitpod-io/template-nixos

### Anything else?

Happening on 1.62.0-insider (https://github.com/microsoft/vscode/commit/f14b5f5730b57a05656c1fef9de2f2c22ee8a0c1)

**Comment by jeanp413** [comment]
I cherry picked it and pushed it to `gp-code/main` as it seems it won't me merge for this release

**Comment by akosyakov** [comment]
confirmed that it works now
