### ISSUE TITLE
[ws-proxy] Don't use DNS but service endpoints

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6441]
Right now we use the kubernetes internal DNS to resolve endpoints for workspaces. This incurs the DNS propagation delays and is a bit fickle. Instead we could use the service endpoints, or even pods directly to determine where a request should go.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6441#issuecomment-955705728):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
