### ISSUE TITLE
A Gitpod experience via Native Mobile Applications (iOS, iPadOS, Android)

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#6447]
👋 I'm putting together an RFC within Gitpod for engaging a mobile development freelancer to potentially build native wrappers for Android and iOS which if built would be open-source. 

If a native experience with Gitpod for mobile was to happen it would likely be:

- App startup time matters thus likely ruling out x-plat solutions.
- Android via Kotlin
- iOS via Swift
- Keyboard hooked so all hotkeys work (think CTRL+R does not reload a webview)
- Tabs of WebViews.
- SSH/Mosh Terminal support.
- Deep linking "Open In Gitpod" should "Open in Mobile App"
- CI/CD backed by Fastlane w/automatic integration testing (Calabash? + Visual Studio App Center?).

See https://github.com/orgs/gitpod-io/projects/18/ for specifics.

If you wanna build this then geoff@gitpod.io. Again, there is no internal proposal yet or budget allocated yet but this could become a full-time contract (remote/any country/in a forest) to get it off the ground then maintenance activities. Thus attn: freelancers.

If you use Gitpod on Android, iOS, or iPadOS I invite you to comment below with your product feature ideas to help shape the future of this initiative. 🧡

**Comment by ghuntley** [comment]
Safari extension is coming. In the iPadOS and iOS ecosystem browser extensions are distributed as applications and that paves the way to future expansion.

https://twitter.com/GeoffreyHuntley/status/1463492555878719502

**Comment by loujaybee** [comment]
Linking related roadmap item: https://github.com/gitpod-io/gitpod/issues/7720
