### ISSUE TITLE
Add support for Fedora and EL (RHEL, CentOS) based workspace images 

### ISSUE THREAD

**Issue by gbraad** [gitpod-io/gitpod#6449]
Adding support for Fedora and EL, like CentOS/RHEL should be easy, as the detection already handles Amazon Linux. Changes would need to be made to https://github.com/gitpod-io/gitpod/tree/1cf441ab78ef5d9d23eb5ef31ffaaf5f330da1e5/components/image-builder/workspace-image-layer to detect the distro type and pick the correct appended dockerfile.

https://github.com/gitpod-io/gitpod/blob/1cf441ab78ef5d9d23eb5ef31ffaaf5f330da1e5/components/image-builder/workspace-image-layer/scripts/detect-distro.sh#L26-L44

and adding a distro folder to https://github.com/gitpod-io/gitpod/tree/1cf441ab78ef5d9d23eb5ef31ffaaf5f330da1e5/components/image-builder/workspace-image-layer/gitpod-layer

I am willing to add a PR, but was wondering how to test this properly. This is a duplicate/re-request of #2456

**Comment by gbraad** [comment]
I made a PR with mostly symlinking, as the files would be identical for amazon, centos/rhel and fedora. the different detection might benefit the identifying process, but the copying would not be.

**Comment by gbraad** [comment]
https://github.com/gitpod-io/gitpod/pull/6472#issuecomment-961691344
Waiting for image builder mk3

**Comment by kylos101** [comment]
Hey @gbraad and @csweichel , seeing as we've got image builder mk3 in production now, do we want to give this another go, or was this already resolved?

**Comment by gbraad** [comment]
Resolved with:
  * https://github.com/gbraad/gitpod-template-fedora
  * https://github.com/gitpod-io/template-fedora

**Comment by ggbecker** [comment]
> Resolved with:
> 
>     * https://github.com/gbraad/gitpod-template-fedora
> 
>     * https://github.com/gitpod-io/template-fedora

I've tried to start instances using the above but with no success. Does anyone has any update if that is really working?

**Comment by gbraad** [comment]
It should work. I use this daily.
