### ISSUE TITLE
[tailscale] MagicDNS doesn't work

### ISSUE THREAD

**Issue by fjolne** [gitpod-io/gitpod#6457]
### Bug description

Tailscale MagicDNS doesn't work inside Gitpod workspace. 

### Steps to reproduce

```bash
gitpod /workspace/budu $ tailscale status
# Health check:
#     - dns: rename /etc/resolv.conf /etc/resolv.pre-tailscale-backup.conf: device or resource busy

100.85.145.199  gitpod-cyan-tuna-u17vs9pt oleg@        linux   -
...

## ping by Tailscale IP => OK
gitpod /workspace/budu $ ping 100.85.145.199
PING 100.85.145.199 (100.85.145.199) 56(84) bytes of data.
64 bytes from 100.85.145.199: icmp_seq=1 ttl=64 time=0.031 ms

## ping by search domain => ERROR
gitpod /workspace/budu $ ping gitpod-cyan-tuna-u17vs9pt
ping: gitpod-cyan-tuna-u17vs9pt: Name or service not known

## ping by full domain => ERROR
gitpod /workspace/budu $ ping gitpod-cyan-tuna-u17vs9pt.budu.jobs.beta.tailscale.net
ping: gitpod-cyan-tuna-u17vs9pt.budu.jobs.beta.tailscale.net: Name or service not known
```

### Workspace affected

https://cyan-tuna-u17vs9pt.ws-eu18.gitpod.io/

### Expected behavior

```bash
## ping from localhost
> ping gitpod-cyan-tuna-u17vs9pt
PING gitpod-cyan-tuna-u17vs9pt.budu.jobs.beta.tailscale.net (100.85.145.199) 56(84) bytes of data.
64 bytes from gitpod-cyan-tuna-u17vs9pt.budu.jobs.beta.tailscale.net (100.85.145.199): icmp_seq=1 ttl=63 time=303 ms
...
```

**Comment by DentonGentry** [comment]
Odd: I had checked MagicDNS at one point, but a lot happened in a very short period of time and I don't know how this happened.

Anyway, this:

`- dns: rename /etc/resolv.conf /etc/resolv.pre-tailscale-backup.conf: device or resource busy`

should be fixed by this: https://github.com/tailscale/tailscale/pull/3015

which you can get by changing the Dockerfile from the stable channel:
`RUN curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.gpg | sudo apt-key add - \`
to unstable:
`RUN curl -fsSL https://pkgs.tailscale.com/unstable/ubuntu/focal.gpg | sudo apt-key add - \`

The support will be in the 1.18 release, after which the Dockerfile could switch back to the stable channel.

**Comment by DentonGentry** [comment]
Oh: I think it probably happened because I was [building from source for a while](https://github.com/tailscale/gitpod/commit/73c6374bb99d7e34db61710e4a5f47a471f6bda1) from a branch which contained the /etc/resolv.conf fix.

**Comment by fjolne** [comment]
@DentonGentry Thanks! Unfortunately, the solution with `unstable` branch doesn't appear to work as it fetches a Tailscale version [right before](https://github.com/tailscale/tailscale/commit/85fa1b0d616b27fd294316d66178730feae33680) the [merge commit](https://github.com/tailscale/tailscale/commit/a320d706141d8da93e158c5b54c229a0acc417f5) of the mentioned PR.
```bash
gitpod /workspace/budu $ tailscale version
1.17.91
  tailscale commit: 85fa1b0d616b27fd294316d66178730feae33680
  other commit: deb569e87bbd44f56cf6ff720f97beb163236a02
  go version: go1.17.2-ts7037d3ea51
gitpod /workspace/budu $ tailscale status
# Health check:
#     - dns: rename /etc/resolv.conf /etc/resolv.pre-tailscale-backup.conf: device or resource busy

100.101.197.226 gitpod-aquamarine-dove-6s32oiig oleg@        linux   -
...
```

Building from source seems to be a bit overkill in my case, as I'm fine just to wait a bit for the stable release, thank you <3

**Comment by DentonGentry** [comment]
I built a new unstable release from today's HEAD, which includes tailscale/tailscale#3015
https://pkgs.tailscale.com/unstable/

**Comment by fjolne** [comment]
Still no luck:
```bash
gitpod /workspace/budu $ tailscale version
1.17.169
  tailscale commit: 8d14bc32d182f8951ff080357a4838aff5b2bdef
  other commit: 6536d93f9d38d1aa0a74e015b5c2f9566f56dbac
  go version: go1.17.2-ts7037d3ea51

gitpod /workspace/budu $ tailscale status
# Health check:
#     - dns: remove of "/etc/resolv.conf" failed (remove /etc/resolv.conf: device or resource busy) and so did truncate: truncate /etc/resolv.conf: permission denied

100.121.246.150 gitpod-amber-mongoose-9x9ykmbi oleg@        linux   -

gitpod /workspace/budu $ ping gitpod-amber-mongoose-9x9ykmbi 
ping: gitpod-amber-mongoose-9x9ykmbi: Name or service not known
```

**Comment by csweichel** [comment]
In a Gitpod workspace `/etc/resolve.conf` is provided by Kubernetes can hence cannot be overwritten. We could add a feature that makes it writable though: instead of just bind-mounting the "outer" `resolv.conf`, we'd copy its content into a writeable file in the ring2 mount namespace.

I'll prep a change to evaluate this option.

**Comment by roboquat** [comment]
@csweichel: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6457#issuecomment-955707780):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6457#issuecomment-955707849):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by DentonGentry** [comment]
tailscaled reads in /etc/resolv.conf to determine if the system is using a DNS system capable of handling Split-DNS (i.e. able to configure one set of DNS servers to be used for example.com queries, and a different set of servers to use for everything else). This includes:
- systemd-resolved
- NetworkManager

If neither of those appears to be in use, we assume libc resolv support is being used which has no way to express Split-DNS configurations. That is when tailscaled will try to overwrite /etc/resolv.conf to set its own 100.100.100.100 DNS server, so it can handle Split-DNS internally.

If there is another DNS service running within the GitPod and tailscaled isn't detecting it correctly, we can try to fix that.
If there is not another DNS service, yes we'd need the ability to write to /etc/resolv.conf.

**Comment by csweichel** [comment]
> If there is another DNS service running within the GitPod and tailscaled isn't detecting it correctly, we can try to fix that. If there is not another DNS service, yes we'd need the ability to write to /etc/resolv.conf.

That explains this case perfectly, as running systemd in workspaces would be highly unusual. AFAIK systemd expects to be PID 1, which for Gitpod workspaces is always supervisor. I also haven't seen anyone use NetworkManager yet.

**Comment by csweichel** [comment]
Making `resolv.conf` writeable indeed does the trick:
![image](https://user-images.githubusercontent.com/3210701/139589560-3310e6d6-2c38-4be3-97c0-a426a9338542.png)
