### ISSUE TITLE
Ability to add custom hosts (via e.g. /etc/hosts)

### ISSUE THREAD

**Issue by fjolne** [gitpod-io/gitpod#6459]
Related to https://github.com/gitpod-io/gitpod/issues/2739, but the `tasks` solution doesn't currently work for not self-hosted workspaces:
```bash
# .gitpod.yml
tasks:
  - init: sudo sh -c "echo 1.2.3.4 myhost.com >> /etc/hosts"
...
sh: 1: cannot create /etc/hosts: Permission denied
```
and `hostAliases` solution isn't applicable.

It's possible to write to `/etc/hosts` from `USER root` via custom Docker image, but it gets overwritten by Kubernetes (as it [rightfully should](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/#why-does-kubelet-manage-the-hosts-file)).

**Comment by fjolne** [comment]
Mitigated by the added ability to write to `/etc/resolv.conf` https://github.com/gitpod-io/gitpod/issues/6457#issuecomment-955716047, so one can setup custom DNS (e.g. Tailscale's MagicDNS).

**Comment by chuck-confluent** [comment]
I am interested in this as well

another related issue:
- https://github.com/gitpod-io/gitpod/issues/554

**Comment by JRedOW** [comment]
I really need some way to change dns resolution within a workspace.  Many monorepos I work with hardcode the values of urls to prevent possible mistakes and security flaws (ex. Hardcoded Call To API in Svelte).  Without editing the hosts file, everything goes horribly wrong.  There should be some extremely easy way to edit hosts in the gitpod config (This would also give gitpod another advantage over Codespaces, which has no easy way to do this).

ex.
```
hosts:
    example.com:127.0.0.1
    foo.example.com:100.100.100.100
```

**Comment by danielmhair** [comment]
Hey guys, thanks to one of our devs, we were able to add a host to /etc/hosts in a non-self-hosted workspace. Try using:
```
echo 127.0.0.1 <your-url> | sudo tee -a /etc/hosts
```

Using `sudo tee -a` did the trick with permissions.
