### ISSUE TITLE
[.gitpod.yml] Improve Error handling with bad `workspaceLocation`

### ISSUE THREAD

**Issue by vorburger** [gitpod-io/gitpod#646]
https://gitpod.io#github.com/apache/fineract/ works..

.. but https://gitpod.io#https://github.com/apache/fineract/pull/525/files does not, it says:

> You have not yet opened a workspace.

but _Open Workspace_ does nothing.

**Comment by svenefftinge** [comment]
In your PR you have a `.gitpod.yml` with a  workspaceLocation https://github.com/apache/fineract/pull/525/files#diff-4e0c28ccf9ba5766935eb3f7e564693dR26

It points to a non existing directory. What was the intend behind using that property?

**Comment by vorburger** [comment]
> In your PR you have a `.gitpod.yml` with a workspaceLocation https://github.com/apache/fineract/pull/525/files#diff-4e0c28ccf9ba5766935eb3f7e564693dR26

Oh! FYI To not mix up several things I'm doing at the same time, I've just removed that (the original `.gitpod.yml`) from https://gitpod.io/#https://github.com/apache/fineract/pull/525/files, and https://gitpod.io/#https://github.com/apache/fineract/pull/525/files works now.

Therefore this probably can't be reproduced as described above anymore; but I've now kept a copy on https://github.com/apache/fineract/compare/develop...vorburger:gitpod_issue-646, if you like to reproduce / investigate on your end... (BTW: how do you open GitPod on a branch?)

> It points to a non existing directory. What was the intend behind using that property?

That was related to https://spectrum.chat/gitpod/general/how-to-make-gradle-based-java-with-code-in-sub-directory-work-e-g-apache-fineract~e56b7671-0eea-44c7-86bb-fdf07d1e1dfb (and then https://github.com/svenefftinge/fineract/commit/da888d808d37abcc10f7bd3548c6283965bff244#commitcomment-34035180) and probably just wrong - sorry for the noise. (I'll pursue that on https://github.com/apache/fineract/compare/develop...vorburger:gitpod)

In an ideal world, it would probably be nice if it provided a more helpful message - but not critical, for me.

**Comment by svenefftinge** [comment]
> (BTW: how do you open GitPod on a branch?)

You would go to the branch on GitHub and prefix the URL with `gitpod.io/#`. Same works for PRs, issues and files (will open the editor).
