### ISSUE TITLE
Support for remote workspaces on nova

### ISSUE THREAD

**Issue by somehowchris** [gitpod-io/gitpod#6469]
Hey there,

I came across nova.app cause its a macOS native app and uses a hell of a lot less resources as vs code, it has built in support for remote bound workspaces, according to their webpage.

It would be lovely if we could have a setup just like the ones for jet brain tools

**Comment by ghuntley** [comment]
First time I've heard of Nova.app! 

Looks like it supports extensions (here's the source code of [TabNine](https://github.com/alexanderflink/nova-tabnine)). The path would involve something like...

- community/nova authors implementing an extension that connects into Gitpod via SSH and remotely editing files (similar to a SFP fuse mount).
- community/nova authors integrating https://www.gitpod.io/blog/local-app into the extensions
- Gitpod exposing configuration option in the dashboard

**Comment by jonathan-wondereur** [comment]
I would also ❤️ this, I have been using nova.app and would like to continue using it instead of switching to VS Code ... I wonder why this issue was closed?

**Comment by somehowchris** [comment]
Sry, I closed it as it seemed that gitpod was moving into "only vscode" waters and many of the devs seem to work on core or additional features to gitpod but I haven't seen yet any enthusiasm around adding a further IDE

**Comment by jonathan-wondereur** [comment]
Interesting, on the [roadmap](https://github.com/gitpod-io/roadmap/projects/1) and their [website](https://www.gitpod.io) Gitpod is saying that they are bringing out support for the JetBrains IDEs soon... 

![image](https://user-images.githubusercontent.com/38539725/153208734-05029056-3007-476b-a9ca-185a7d0c7162.png)

**Comment by axonasif** [comment]
> Interesting, on the [roadmap](https://github.com/gitpod-io/roadmap/projects/1) and their [website](https://www.gitpod.io) Gitpod is saying that they are bringing out support for the JetBrains IDEs soon...
> 
> ![image](https://user-images.githubusercontent.com/38539725/153208734-05029056-3007-476b-a9ca-185a7d0c7162.png)

Actually, people have been using gitpod with jetbrain IDEs for some time, although it's still in beta. We're definitely open to adding more IDE support, it's just our engineers need more time to finish something and pick up what's next.
