### ISSUE TITLE
Minor: Open in GitPod badge (open-in-gitpod.svg) is a bit too narrow

### ISSUE THREAD

**Issue by vorburger** [gitpod-io/gitpod#647]
It would like nicer if [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](#) didn't look so... "cut off", on the right.

This ^^^ is the SVG from source, here's a bitmap of how it currently looks like, for me on Firefox on Linux at regular 100% Zoom:

![gitpod-badge](https://user-images.githubusercontent.com/298598/60469983-fb63ee80-9c5e-11e9-83d8-e68b07c0f005.png)

**Comment by jankeromnes** [comment]
Good catch! Thank you for the screenshot. I guess this is a platform-specific font problem, because on Firefox on Mac I see:

<img width="537" alt="Screenshot 2019-07-02 at 09 07 56" src="https://user-images.githubusercontent.com/599268/60491361-e8760c00-9ca8-11e9-869d-958fd625a4ec.png">

Maybe the SVG can specify a better default font.

**Comment by svenefftinge** [comment]
I enhanced the list of font-families a bit.

https://jsfiddle.net/j1b0szxo/1/

Need to test with windows and linux

**Comment by svenefftinge** [comment]
Anyone with windows or linux could share a screenshot of what the button looks like on their platform?

**Comment by mouse484** [comment]
Windows(10  Chrome)
![image](https://user-images.githubusercontent.com/38714187/60747525-b3c3c680-9fc0-11e9-8824-e8a54efd5208.png)
Windows(10 Firefox)
![image](https://user-images.githubusercontent.com/38714187/60747556-d655df80-9fc0-11e9-9f89-9920e2b3e99b.png)
Linux(Ubuntu Chrome)
![image](https://user-images.githubusercontent.com/38714187/60748507-a3fcb000-9fc9-11e9-958a-da1c08820904.png)
Linux(Ubuntu Firefox)
![image](https://user-images.githubusercontent.com/38714187/60748428-c6da9480-9fc8-11e9-88d5-b5e5c5deadcb.png)

**Comment by koppor** [comment]
I encounter the same issue here:

![grafik](https://user-images.githubusercontent.com/1366654/175812755-ea9fb26e-ef80-455e-9622-33d7af17d893.png)

With labels from https://shields.io/, it looks even more wired:

![grafik](https://user-images.githubusercontent.com/1366654/175812778-9c0f253f-3df1-4424-93a9-a9ed2f477364.png)

Source:

```markdown
# Markdown Any Decision Records [![part of ADR](https://img.shields.io/badge/part_of-ADR-blue.svg)](https://adr.github.io) [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/adr/madr)
```

**Comment by ghuntley** [comment]
@koppor use this

```html
<a href="https://gitpod.io/from-referrer/">
  <img src="https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod" alt="Contribute with Gitpod" />
</a>
```

Which looks like this

<a href="https://gitpod.io/from-referrer/">
  <img src="https://img.shields.io/badge/Contribute%20with-Gitpod-908a85?logo=gitpod" alt="Contribute with Gitpod" />
</a>
