### ISSUE TITLE
Keyboard shortcut to open exposed port in a browser

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#6471]
Crtl+Shift+P should yield a dropdown like this

<img width="1195" alt="2021-11-01_11-08-23" src="https://user-images.githubusercontent.com/127353/139608410-07298244-1f30-4ab5-b93d-b292fb014d7b.png">

Searching for "port" should present an option

A user would then press enter at which point an a list of forwarded ports are displayed

When a user presses enter on a port a new browser window is opened at that port.

# Why

- "don't make me use my mouse"

**Comment by akosyakov** [comment]
Just fyi:
- F1
- Focus on Gitpod Workspaces View
- Select a port with up/arrow and press enter to select, then tab to focus inline actions
- Use left/right arrow to select action and press enter

The command palette would be nice, also when the port is selected the command palette could provide commands for inline actions.

**Comment by ghuntley** [comment]
I’m on an iPad that doesn’t have F1 :/

**Comment by akosyakov** [comment]
> I’m on an iPad that doesn’t have F1 :/

then `Crtl+Shift+P` 😄
