### ISSUE TITLE
[extensions] tailwind CSS extension crashes

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#6474]
### Bug description

Starting the a workspace on the gitpod repo, I get the following error in the IDE 
<img width="444" alt="Screen Shot 2021-11-01 at 09 13 29" src="https://user-images.githubusercontent.com/377752/139642079-046dba3d-ff50-43e1-b5d1-f7226b6d7a71.png">

### Steps to reproduce

Open https://gitpod.io/#https://github.com/gitpod-io/gitpod and wait for the IDE to initialize (VS Code Insiders)

### Workspace affected

https://copper-whale-iwmu9k74.ws-eu18.gitpod.io/

**Comment by akosyakov** [comment]
Did you capture any logs from browser or the output channel?

I tried the link and it works for me on Insiders:
<img width="1904" alt="Screenshot 2021-11-01 at 09 40 35" src="https://user-images.githubusercontent.com/3082655/139645037-31159d3d-bd94-4366-ad27-b2951c721e98.png">

**Comment by JanKoehnlein** [comment]
Nope unfortunately I already closed the WS tab

Sent via Superhuman iOS ***@***.***>
