### ISSUE TITLE
Ability to rotate certs for pluggable workspace clusters

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#6475]
For the connection between meta and workspace, we use two certs to secure the gRPC connection: ws-manager-tls, ws-manager-client-tls.  They're signed with self-signed root CA which will expire next year.

What would be the process to rotate these certs without imposing downtime?

If there is a process that I'm not aware of: awesome!
if there is no process yet: Maybe ws-manager-bridge can hold a cert specific to every ws-cluster (instead of one cert for all clusters) so that a new ws-cluster could bring a new cert.

Preceding discussion: https://github.com/gitpod-io/ops/issues/156

**Comment by JanKoehnlein** [comment]
I'm not aware of any such process either.

Another solution could be to enable multiple CA certs on both ends first, which would allow to make the switch later in any order (not requiring a certain a deployment order).

But as the preceding discussion already brought up, we might want to tackle this in a larger attempt to manage secrets. 

Maybe team-workspace has other ideas as well.

**Comment by csweichel** [comment]
Bridge already holds certs specific to the cluster they connect to. I reckon we could just produce a new CA and certs and register the cluster that way.

**Comment by csweichel** [comment]
Have we tried to do this? I would not expect this to be an issue.

**Comment by csweichel** [comment]
removing from groundwork
