### ISSUE TITLE
[code] update product.json

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6476]
It should run latest yaml extension, also other attributes should be checked, [see](https://www.notion.so/gitpod/Gitpod-VS-Code-1aa1dfcfdc5147869ec5ffcf86f430a6#4300cbdff6444d9fa92786cb36bc56c2). Please also add `genuitecllc.codetogether` in a list of extensions allowed to use proposed APIs.

**Comment by roboquat** [comment]
@akosyakov: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6476#issuecomment-956035548):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
fixed in Insiders
