### ISSUE TITLE
[supervisor] Disable gRPC debug logs for the status server

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6478]
Right now the supervisor logs are littered with messages like
```
{"grpc.code":"OK","grpc.method":"ContentStatus","grpc.service":"supervisor.StatusService","grpc.start_time":"2021-11-01T08:40:21Z","grpc.time_ms":0.03,"level":"info","message":"finished unary call with code OK","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","span.kind":"server","system":"grpc","time":"2021-11-01T08:40:21Z"}
```

We should disable them or only print them when `SUPERVISOR_DEBUG` is enabled

**Comment by akosyakov** [comment]
It is the case right now, not?

**Comment by akosyakov** [comment]
I removed for now from the groundwork, I am not sure what else should be done. As far as I know it is already implemented. We see them indeed in prev env, but only because debug is always on there on purporse.
