### ISSUE TITLE
Add `gpctl debug <component>` which enables the debug log level for a component

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6479]
For most components that would be equivalent to
```bash
kubectl port-forward <pod> 6060
curl -XPOST -d '{"level":"debug"}' localhost:6060/debug/logging
```

For supervisor we'd modify the default workspacetemplate and set `SUPERVISOR_DEBUG` to `true`.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6479#issuecomment-956044236):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
