### ISSUE TITLE
[supervisor] Only ports listening in 0.0.0.0 should be auto exposed

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#6482]
### Bug description

If an application uses 127.0.0.1 to bind some port, we should not see the expose port dialog

### Steps to reproduce

Open https://gitpod.io/#https://github.com/gitpod-io/template-sveltejs
After the workspace starts we should not see port 5000 exposed

**Comment by akosyakov** [comment]
Why? many setups expose by default on localhost and 127.0.0.1. We install local proxy on purpose to make them work.
