### ISSUE TITLE
Implement logos for Jetbrains IDEs

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6486]
The JetBrains logos should be updated to use the official JetBrains ones within the dashboard.

**Comment by loujaybee** [comment]
It looks like this one is already complete? 

CC: @corneliusludmann / @atduarte could you confirm there's nothing else required, if so let's close the issue 🙏

**Comment by roboquat** [comment]
@loujaybee: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6486#issuecomment-957231449):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by corneliusludmann** [comment]
> could you confirm there's nothing else required, if so let's close the issue pray

Yes, it's fixed already.
