### ISSUE TITLE
Add VSCode Desktop and VSCode Insiders to Desktop IDE's configuration

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6488]
Currently we only have the two JetBrains IDE's showing as desktop IDE's, but we need to add Desktop VSCode and Desktop VSCode insiders to this list, also. 

![Screenshot 2021-11-01 at 14 28 04](https://user-images.githubusercontent.com/5528307/139689340-72a91800-fef1-4d92-8878-3f1905c6b01e.png)

**Comment by GitMensch** [comment]
@corneliusludmann Is there any chance that you could replicate that for VSCodium #10667?

**Comment by axonasif** [comment]
@GitMensch I suggest following up on the original ticket instead of this one.
