### ISSUE TITLE
Announcement blog post VSCode 1.62

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6490]
Discussing the changes we made to our server implementation in [openvscode-server](https://github.com/gitpod-io/openvscode-server) in response to [the open-sourced server implementation from Microsoft](https://github.com/microsoft/vscode/commit/822f995357f725216cdee6e05f1f1552ccbbd882). 

Give some background to OpenVSCode Server, and Gitpod's role in the community and how we got to the current state that we're in now. 

We should also include some information on how we're doing nightly builds and the insiders build which allows us to react quick to the changes, allowing us to release a stable version in tandem with MS Code repo.

**Comment by roboquat** [comment]
@loujaybee: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6490#issuecomment-957231098):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by loujaybee** [comment]
Will assign you to this one as well as me @jeanp413 ! 🙏
