### ISSUE TITLE
[Installer]: ws-daemon service account error

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6491]
```json 
{
  "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
  "error": "nodes \"gke-sje-europe-west2-prima-workspaces-7dcc2341-d6fr\" is forbidden: User \"system:serviceaccount:default:ws-daemon\" cannot get resource \"nodes\" in API group \"\" at the cluster scope",
  "level": "error",
  "message": "cannot update node label",
  "serviceContext": {
    "service": "ws-daemon",
    "version": ""
  },
  "severity": "ERROR",
  "time": "2021-11-01T15:24:39Z"
}
```

**Comment by MrSimonEmms** [comment]
I closed this issue because I couldn't recreate it and I didn't add enough detail to make it a useful issue. If you can add some more stuff to the ticket, I'll reopen it (please tag me)

**Comment by sedattanir** [comment]
![image](https://user-images.githubusercontent.com/17693925/147689936-474d07a7-0d1d-4f30-a56f-97f912b16636.png)
I am getting the same error. what is the problem caused by?
If there's anything you want me to look at (logs, pods, etc), I can help you.

**Comment by sedattanir** [comment]
@MrSimonEmms Can you help me?
