### ISSUE TITLE
Local Companion App cannot bind ports due to Windows reserved and command line argument not work

### ISSUE THREAD

**Issue by huweiATgithub** [gitpod-io/gitpod#6494]
### Bug description

Both the Open in VS Code and the standalone local-companion app (it seems vscode extension also download and use this app) cannot bind its default ports.
local-companion app's logs show:
`
time="2021-11-02T03:02:29+08:00" level=info msg="Could not open port:n got error:listen tcp4 127.0.0.1:63329: bind: An attempt was made to access a socket in a way forbidden by its access permissions.\nTrying next port\n" 
`
where n range from 63110 to 63329 continuously.

This is not due to a firewall issue as I tried shutdown all firewalls.
Later I test these ports with a simple program, which success for low ports (<4x,xxx) but failed for high ports (yes, local companion ports lie in this range). 

It then has come to my attention the following issues:
https://github.com/docker/for-win/issues/3188
https://stackoverflow.com/questions/48478869/cannot-bind-to-some-ports-due-to-permission-denied
https://github.com/docker/for-win/issues/3171
and the reply: https://github.com/docker/for-win/issues/3171#issuecomment-554587817
the Microsoft Doc: https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/default-dynamic-port-range-tcpip-chang

It seems that those ports from 49152 - 65535 are dynamic ports reserved for windows. 
I tried to force the local companion to use other available ports by passing the --api-port argument which didn't work.
It still tried to bind those ports from 63110 to 63329. 
`.\gitpod-local-companion-windows.exe --api-port 42123`

I think this can be resolved in one (or all) of the following ways,

- default ports to those relatively low ports < 49152 
- bind ports dynamically
- make port binding configurable [extension settings, config file, etc] currently passing arguments not working 

### Steps to reproduce

1. On a Windows 10 21H1 19043.1288 PC.
2. Download the gitpod-local-companion-windows.exe and run

**Comment by akosyakov** [comment]
@filiptronicek @ghuntley It was not the issue for you when you tried on windows? The thing here that we need to hardcode redirect URL in Gitpod Server, we cannot allow a user to reconfigure them.

**Comment by filiptronicek** [comment]
Tried running the local app on Windows 11 [22494.1000] and the server seems to be listening on ports ~51900
![image](https://user-images.githubusercontent.com/29888641/142757585-62765eca-9ddc-42b4-8ccc-d26d9ef35f9f.png)

Looks like this port range is set in the local app's source though: 
https://github.com/gitpod-io/gitpod/blob/a30a1bff483b02df67e01791b44dfb5bf025d344/components/local-app/main.go#L73-L80

**Comment by akosyakov** [comment]
> @akosyakov I am puzzled as to why this works and listens on a port like 51894 on Windows, when the port range is set differently. It sounds to me like this shouldn't work on Windows, but for some reason it does 😄.

It says that supervisor from some workspace is forwarded on 51894.

**Comment by huweiATgithub** [comment]
@filiptronicek Would you share your windows dynamics range: `netsh int ipv4 show dynamicport tcp`

For those who also have this problem, you can change the dynamics ports range in windows to make the local-companion app works. For example,
```
netsh int ipv4 set dynamicport tcp start=49152 num=10000
```
so that the port used by local-companion is not in the range. (restart needed)

After setting this, I can confirm everything works smoothly.
