### ISSUE TITLE
Heuristic for "workspace engagement" - PLG phase 3.1 (VS Code browser)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6499]
### Context

As part of the funnel 2.0 ([internal link](https://www.notion.so/gitpod/Funnel-2-0-Dev-Turns-Champion-Turns-Superteam-19a2574eb4bc4499b0a78250310378c0) - phase 3.1), we need to establish, and implement a metric that defines when a user has "explored the workspace". 

**Challenges:**
* We have multiple IDE's, how do we include this in our metric? (Option: make this issue about VS Code adoption)
* We only have some metrics currently implemented
* What action will define when the workspace engagement is completed? 

---

### Value

Allows us to understand how, and which users have fully explored the workspace. 

---

### Acceptance criteria

* Any metrics that are required are set-up / instrumented
* The metric is viewable within Mixpanel

**Comment by roboquat** [comment]
@loujaybee: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6499#issuecomment-957231010):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by loujaybee** [comment]
Duplicated by: https://github.com/gitpod-io/gitpod/issues/7326
