### ISSUE TITLE
Allow to specify a user env variables per a repo

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#65]
For example in order to develop the probot app: https://probot.github.io/docs/development/#configuring-a-github-app

**Comment by svenefftinge** [comment]
We should encrypt all values so users could store passwords or tokens.
E.g. NPM_Token for publishing

**Comment by svenefftinge** [comment]
We'll need this for a convenient integration with other tools, such as platform.sh, netlify, now's zeit, etc.

**Comment by svenefftinge** [comment]
fixed https://www.gitpod.io/docs/47_Environment_Variables/
