### ISSUE TITLE
Heuristic for "first meaningful action" - PLG phase 4.1 (VS Code browser)

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6501]
### Context

As part of the funnel 2.0 ([internal link](https://www.notion.so/gitpod/Funnel-2-0-Dev-Turns-Champion-Turns-Superteam-19a2574eb4bc4499b0a78250310378c0) - phase 4.1), we need to establish and implement a metric that defines when a user has achieved "value adoption". 

**Open Questions:**
* How often does a user need to use Gitpod in order for it to be considered value adoption? 
* Can we re-use the Gitpod love score for this? 

---

### Value

Allows us to understand which of our users have reached value adoption of Gitpod.

---

### Acceptance criteria

* Any metrics that are required are set-up / instrumented
* The metric is viewable within Mixpanel

**Comment by roboquat** [comment]
@loujaybee: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6501#issuecomment-957231062):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by loujaybee** [comment]
Temporarily removing from groundwork whilst we work on: #6499

**Comment by loujaybee** [comment]
Duplicated by: https://github.com/gitpod-io/gitpod/issues/7182
