### ISSUE TITLE
Integrate gp cli (open, preview) with IntelliJ

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6506]
We need some way to open a file or preview in the current thin client, or a new browser window. 

The `gp cli` delegates to a program configured via env vars ([see this file](https://github.com/gitpod-io/gitpod/blob/5f84be7c096ea6aa1edf5aa674d98a02aff719b6/components/ide/code/leeway.Dockerfile)).

The 3 use-cases: 

1. Open a file -> Can be done via `idea $FILE`
2. Open an embedded browser -> ??
3. Open the external browser -> ??

Quote from a conversation with JetBrains:

> It works the same way with files in ordinary IDE setup, e.g. idea $FILE will open a file, no such thing for opening urls in embedded or external browser. It’s easy to write though, intellij has a mechanism for registering so called ApplicationStarter that can be used to customize the behavior of IDE based on the arguments supplied to the command line.

Also, see this conversation [internal link](https://gitpod.slack.com/archives/C02BRJLGPGF/p1635850800016900)

**Comment by atduarte** [comment]
According to Jetbrains, currently there is no way to "Open an embedded browser" or "Open the external browser" using links. [[1](https://gitpod.slack.com/archives/C02BRJLGPGF/p1635968246037100?thread_ts=1635850800.016900&cid=C02BRJLGPGF)]
Relevant issue from their side: https://youtrack.jetbrains.com/issue/CWM-3678

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/gitpod/issues/6525

**Comment by akosyakov** [comment]
it is resolved already, `open` opens a file, `preview` opens a browser.
