### ISSUE TITLE
Allow users to define Jetbrains plugins to be installed on a given project 

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#6508]
When using Jetbrains Remote Dev what runs locally is just a Thin Client. If you want to install plugins you must install them in the backend—that runs in Gitpod.

As some plugins require the IDE to restart we should have them installed during the initialization of the workspace.

To do so, and focusing for now on the plugins that are directly associated with a project (not the user), we will need to change the gitpod.yml spec.

_Note that a given plugin may be compatible with only some Jetbrains IDE "flavours" (e.g. Scala plugin only works on IDEA)._

----

To install a plugin, run `bin/remote-dev-server.sh installPlugins PROJECT_PATH pluginId`. [[1](https://gitpod.slack.com/archives/C02BRJLGPGF/p1634730624135200?thread_ts=1634730309.134900&cid=C02BRJLGPGF)]

**Comment by loujaybee** [comment]
Relates to: 

https://github.com/gitpod-io/gitpod/issues/6706
https://github.com/gitpod-io/gitpod/issues/6576#issuecomment-1006566022

**Comment by akosyakov** [comment]
As far as I understand JB has a canonical way for that:
- https://www.jetbrains.com/help/idea/managing-plugins.html#required-plugins
- and then check in .idea folder

**Comment by atduarte** [comment]
Found this page that might be useful: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

**Comment by akosyakov** [comment]
It turned out that required plugins are not installed, but rather IDE complain if they are missing:
<img width="655" alt="Screenshot 2022-02-13 at 07 23 11" src="https://user-images.githubusercontent.com/3082655/153817355-18ebbdda-5813-4d2e-9891-23befd3bb79a.png">
