### ISSUE TITLE
Newsletter sign up integration

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#6509]
Instead of collecting newsletter signups separately (which would include Google Sheet, Zapier, customer.io and DB updates), we decided that the user needs to log in in order to subscribe for the newsletter. By that we can use the existing data flow. This should reduce the implementation effort a lot. 
Note: I randomly researched a few newsletter signups and most of them are already existing users. See [current list](https://docs.google.com/spreadsheets/d/1DrgFXvDsLmu6kUoBHMfgYqBtqyT9kr4OHqcKX31FbXw/edit#gid=722237941)

Users can sign up either for the Changelog email [[1](https://www.gitpod.io/changelog)] or for the DevX Digest [[2](https://www.gitpod.io/blog/ephemeral-dev-envs)]. 

### User flow:
<details>
<summary>1. user clicks on "signup for the newsletter" (already exists)</summary>
<img width="635" alt="Bildschirmfoto 2021-11-02 um 11 35 58" src="https://user-images.githubusercontent.com/46345125/139831150-69707761-d831-43f4-a258-65aef310ac3e.png">
</details> 
<details>
<summary>2. Link to a page confirming the updated email settings(needs to be created)</summary>
it's the same layout as for the email unsubscribe screen 
<img width="642" alt="Bildschirmfoto 2021-11-02 um 12 12 23" src="https://user-images.githubusercontent.com/46345125/139836256-27631c08-50ff-4409-9313-a230553977aa.png">

</details> 

In case the user is not registered or logged in yet, they would need to sign up/login first and then be redirected to the "confirm subscribe page"

### To do's
- create 2x "confirm subscribe page" (once for Changelog and once for DevX Digest).
- link both "newsletter sign up button" to the dedicated "confirm subscribed page"
- require a login or signup if the user is not logged in yet
- update [notification preferences](https://gitpod.io/notifications) according to the "newsletter signup" (DevX or Changelog)

Context:
[Slack](https://gitpod.slack.com/archives/C022DFDLAQL/p1635242795001400?thread_ts=1634289979.010200&cid=C022DFDLAQL)
#5598

cc @atduarte @jakobhero because you were involved in the discussions before
@laushinka as you implemented a similar screen before https://github.com/gitpod-io/gitpod/issues/4761#issuecomment-898242167

**Comment by JanKoehnlein** [comment]
From a (potential) customer's perspective, I find it odd to first log in (or even create an account) just to subscribe to a newsletter. There is no use for the newsletter subscription information within the product. It's only in the product's DB at the moment because we used to not have an external service for customer emails. A specialized tool like customer.io can also probably comply much better with things like GDPR than we do. So from a product perspective, I'd really prefer to move the entire newsletter registration from Gitpod to customer.io.

For the meta team, it looks much easier to push into that direction. If you're afraid of big efforts on the DCS side, it'd be good to understand where you think these are and whether we can provide help. In the end, we should find a viable and minimum effort solution for the entire company. As we're already pretty booked, it would also be interesting how urgent this is.

**Comment by ChristinFrohne** [comment]
Alternatively, @atduarte suggested these steps:
1. Change the subscription settings page in Gitpod as @Jan mentioned to show the subscription information that exists in Customer.io (note: this needs to be aligned with the unsubscribe logic)
2. Change customer.io to use email and id as identifiers. This requires removing the duplicates first, which is tricky.
3. Change newsletter form on website to trigger a netlify function that triggers segment that ends up in customer.io, which will create a user or update an existing one’s subscription status (Note: netlify hop is because we are still having issues with ad-blockers blocking segment).
4. Use customer.io segments as we would before.
5. The double opt in can be executed in parallel if needed. It requires changes in all signups, creating new campaigns, etc

I thought just requesting signup would simplify things. It would be great if someone else with a more technical background could take the lead on this. 

Since June, we are collecting email addresses (+160 so far) that haven't been used.

**Comment by JanKoehnlein** [comment]
Team meta could do 1). The unsubscribe link of future emails should point to customer.io as well. We can add a temporary redirection on our server for existing emails.

We haven't touched customer.io yet, so 2), 4) and 5) sound like tasks for DCS. 3 could be done by DCS, too (@nisarhassan12 ?)

**Comment by ChristinFrohne** [comment]
I discussed the issue again with @JohannesLandgraf and he agreed with the previous suggestion to only allow newsletter signups if the user signs in. Additionally, he had the simple and great idea to just link the newsletter signup button to [https://gitpod.io/notifications](https://gitpod.io/notifications). By that the users can adjust the settings themselves and we don't have any technical work.

Let me know if you disagree otherwise I will push this MVC forward

**Comment by laushinka** [comment]
Is there a reason why we would want to ask users to sign up to Gitpod to
sign up to our newsletters?
Also, we had tickets before to make sure that users don't have to sign in
in order to unsubscribe - but to subscribe they will have to? Essentially
we're making it easier for people to leave our newsletters than to sign up
to them.

Just a thought..

**Comment by ChristinFrohne** [comment]
I agree it's not optimal, but as we are discussing this issue since June, I'd like some progress done so that the signups don't just end in a Google Sheet. Since June we have 160 sign-ups which is nice, but also not that many. I randomly checked some email addresses and most of them already had a Gitpod account, so for them, the signup wouldn't be a hurdle. 

I'm happy if someone else picks up this issue again to further improve on it. For now, I'd go with this MVC.

**Comment by JanKoehnlein** [comment]
So the MVC is website only, isn't it? I'll unschedule this ticket from groundwork then.

> Essentially we're making it easier for people to leave our newsletters than to sign up to them.

Yes, that's what GDPR forces us to do. Consent has to be proved, while unsubscribe has to be one-click.

**Comment by laushinka** [comment]
>
> Yes, that's what GDPR forces us to do. Consent has to be proved, while
> unsubscribe has to be one-click.


Ah, got it. Thanks for the explanation.
