### ISSUE TITLE
deploy supervisor image via server ide config

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6512]
We should move configuration of the supervisor image to the IDE service in Gitpod Server.

**Comment by csweichel** [comment]
We need to make this change backwards compatible, i.e. an old server (which does not send the supervisor image ref) needs to work with a new workspace cluster (which might expect the supervisor image ref). To do that, we could just overwrite the static layer we currently add by changing the order of the [layer sources in registry facade](https://github.com/gitpod-io/gitpod/blob/56fe86ff90a5c0bb652d2ab8a41bb22545a5b34c/components/registry-facade/pkg/registry/registry.go#L97-L126):

```Go
	var layerSources []LayerSource

        // add static layer first, so that they can be overwritten by the layers that come afterwards

	log.Info("preparing static layer")
	staticLayer := NewRevisioningLayerSource(CompositeLayerSource{})
	layerSources = append(layerSources, staticLayer)
	if len(cfg.StaticLayer) > 0 {
		l, err := buildStaticLayer(ctx, cfg.StaticLayer, newResolver)
		if err != nil {
			return nil, err
		}
		staticLayer.Update(l)
	}

	ideRefSource := func(s *api.ImageSpec) (ref string, err error) {
		return s.IdeRef, nil
	}
	ideLayerSource, err := NewSpecMappedImageSource(newResolver, ideRefSource)
	if err != nil {
		return nil, err
	}
	layerSources = append(layerSources, ideLayerSource)

	desktopIdeRefSource := func(s *api.ImageSpec) (ref string, err error) {
		return s.DesktopIdeRef, nil
	}
	desktopIdeLayerSource, err := NewSpecMappedImageSource(newResolver, desktopIdeRefSource)
	if err != nil {
		return nil, err
	}
	layerSources = append(layerSources, desktopIdeLayerSource)

	// introduce new supervisor layer source. It's ok if the ref returned is an empty string, the spec mapped
        // layer source handles this case gracefully.

	supervisorRefSource := func(s *api.ImageSpec) (ref string, err error) {
		return s.SupervisorRef, nil
	}
	supervisorLayerSource, err := NewSpecMappedImageSource(newResolver, supervisorRefSource)
	if err != nil {
		return nil, err
	}
	layerSources = append(layerSources, supervisorLayerSource)

	// content layer source needs to remain where it is and must not be overwritten by the spec mapped stuff

	clsrc, err := NewContentLayerSource()
	if err != nil {
		return nil, xerrors.Errorf("cannot create content layer source: %w", err)
	}
	layerSources = append(layerSources, clsrc)
```

**Comment by corneliusludmann** [comment]
One part of this issue is to add the supervisor ref to the ImageSpec of the registry facade. That's obvious.

But the supervisor image ref is also part of the `ws-proxy` config:

https://github.com/gitpod-io/gitpod/blob/a30a1bff483b02df67e01791b44dfb5bf025d344/chart/templates/ws-proxy-configmap.yaml#L50

This seems to be used to handle supervisor frontend URLs via `blobserve`.

@csweichel How could we get this dynamic so that we can change the supervisor image in the `server-ide-configmap` only? Is it possible?
