### ISSUE TITLE
Clean up the heartbeat Jetbrains's plugin

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6513]
It should use the supervisor info endpoint instead of env vars to get information about workspace.

**Comment by loujaybee** [comment]
Since we've got it tracked in the GA epic, let's drop from Groundwork for now, and we can move in when we finish private + open beta 🙏

**Comment by corneliusludmann** [comment]
> If for some reason we were able to fetch the status but for a moment aren't able, we will send a heartbeat(wasClosed=true) reducing the timeout to a few minutes.
> 
> For that reason I would argue it would be better to handle the exception in the HeartbeatService, retrying and being careful about setting the this.status only after successful execution.

https://github.com/gitpod-io/gitpod/pull/6551#issuecomment-960547956
