### ISSUE TITLE
A colon in URL params silently breaks Gitpod interface in VSCode

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#6514]
### Bug description

When opening URL of a repo where there's a colon in the URL params, it silently breaks Gitpod interface in VSCode:
* Gitpod menu items in main hamburger menu
* Ability to run `code` in terminal
* Ports panel
* etc...

![image](https://user-images.githubusercontent.com/22901/139871008-7a8f085a-f47b-40a7-a728-b7f9cf451f10.png)

### Steps to reproduce

1. Add URL params to any Gitpod repo
1. Create any variable with `=`, but make sure to add `:` in the value.

Example:
https://gitpod.io/#TESTING_URL_PARAMS_WITH_COLON=:/https://github.com/shaal/testing--gitpod-url-params-with_colon

### Expected behavior

This should either caught as parsing error before the workspace opens, or allow colons that are not encoded, but make sure the Gitpod interface in VSCode doesn't break.

### Example repository

https://gitpod.io/#TESTING_URL_PARAMS_WITH_COLON=:/https://github.com/shaal/testing--gitpod-url-params-with_colon

### Anything else?

This was discovered thanks to @rfay

There's no specific need for a colon that is not encoded (`%3A`), Gitpod workspace receive the `colon` correctly, but the interface is broken.

**Comment by pawlean** [comment]
Reproducible on my end, thanks for highlighting this @shaal.

**Comment by akosyakov** [comment]
@JanKoehnlein @geropl wdyt? I'm not sure whether it is an issue in VS Code. I assign team ide for now that we don't have dangling bugs, but feel free to reassign if it should be resolved before redirecting to IDE.

**Comment by geropl** [comment]
@akosyakov The context URL is correctly parsed in `server`/written to DB. I bet we re-construct it somewhere in the Gitpod extension...?

**Comment by akosyakov** [comment]
Yes, it looks that only gitpod extension is broken, not even VS Code. I could not find anything from logs though.

**Comment by rfay** [comment]
Thanks for the fix.

**Comment by shaal** [comment]
I tested it by going to https://gitpod.io/#TESTING_URL_PARAMS_WITH_COLON=:/https://github.com/shaal/testing--gitpod-url-params-with_colon
I see the same issue as before.
Do we need to wait until the fix is deployed?

**Comment by gtsiolis** [comment]
Hey @shaal! Yes, this will be available in the next week or so after deploying the fix, see https://github.com/gitpod-io/gitpod/issues/6514#event-5602761042.

**Comment by shaal** [comment]
@gtsiolis I thought `moved this from Awaiting Deployment to Done` would mean it was deployed.
Is there a way to track what was deployed already vs. not ?

**Comment by gtsiolis** [comment]
@shaal Oh, wait! You're right! I thought this was still in _Awaiting Deployment_ but it seems the issue was moved from review to done in one step. Maybe this is an issue with any recent changes with the automation in place.

Let me loop in @JanKoehnlein and @ArthurSens in case they have more insights on this.

**Comment by loujaybee** [comment]
@jeanp413 are you able to confirm if this one is deployed / working?

**Comment by rfay** [comment]
It's always a guessing game for those of us in the bleachers wondering when these things get deployed. I love how fast you work and how responsive you are, but there's lots of insecurity and wasted time trying things out and finding out they're either not deployed yet or don't show up until you use a new fresh workspace.

**Comment by shaal** [comment]
What @rfay said.

Also, I did test it again now, and can confirm it was deployed, because this test repo now works as expected -
https://gitpod.io/#TESTING_URL_PARAMS_WITH_COLON=:/https://github.com/shaal/testing--gitpod-url-params-with_colon

**Comment by jeanp413** [comment]
@loujaybee I also tested it and can confirm it's deployed, but it would be good to now why roboquat moved this to done directly

**Comment by loujaybee** [comment]
@rfay / @shaal - 100% we feel your pain too, and I hear you. 

I've made a GitHub issue to track this: https://github.com/gitpod-io/gitpod/issues/6735 so we're public about progress here. 

🙏 Thanks for the feedback, and hopefully we can make some improvements to the situation soon!
