### ISSUE TITLE
Make workspaces start

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6519]

**Comment by roboquat** [comment]
@csweichel: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6519#issuecomment-959734704):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
