### ISSUE TITLE
JetBrains IntelliJ IDE workspace times out

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6523]
### Bug description

The current heartbeat implementation seems to not be working with the IntelliJ IDE. 

### Steps to reproduce

1. Open an IntelliJ IDE session
2. Work for ~30 minutes (until workspace timeout)
3. The workspace will close

### Expected behavior

The workspace remains open whilst actively working within IntelliJ

Also, see this [Internal conversation](https://gitpod.slack.com/archives/C02BRJLGPGF/p1635860476029500)

**Comment by corneliusludmann** [comment]
**Remark:** If you close the Gitpod browser tab after you started the IntelliJ desktop IDE your workspace will even timeout after only 5 minutes due to this bug.

**Comment by atduarte** [comment]
@corneliusludmann in this situation are the 5 minutes time out intended? Asking because you need to leave the page to proceed with the IntelliJ IDE and may take a while to connect (e.g., in the first time you have to download the IDE).

**Comment by corneliusludmann** [comment]
Still an issue, see https://github.com/gitpod-io/gitpod/pull/6527#issuecomment-959595483.
