### ISSUE TITLE
Build the `tasks` command API (.gitpod.yml) into JetBrains integration

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6525]
In Gitpod a user can [specify tasks](https://www.gitpod.io/docs/config-start-tasks) which are shell scripts executed on workspace container startup. We would like to allow users to interact with their terminal using the commands they specific in their `tasks` command them from within the thin client. In VS Code we are [using pseudo terminal API](https://code.visualstudio.com/api/references/vscode-api#Pseudoterminal) allowing to connect tasks. 

See: [Internal link](https://gitpod.slack.com/archives/C02BRJLGPGF/p1635854581021000)

**Comment by loujaybee** [comment]
This will require some investigation, and discussions with JetBrains. @akosyakov can help here.

**Comment by felladrin** [comment]
I started looking into it today and will leave here some notes as reminders for later:

On [jetbrains/backend-plugin](https://github.com/gitpod-io/gitpod/tree/8bdd0ca581eea5fd361c40b562cdc2eb345005fe/components/ide/jetbrains/backend-plugin), we should mimic what we're doing on [openvscode-server's registerTask method](https://github.com/gitpod-io/openvscode-server/blob/6ee8dc4c04033fa549b2a2ce563434b5015bab9d/extensions/gitpod-shared/src/features.ts#L784) (see [usage example](https://github.com/gitpod-io/openvscode-server/blob/6ee8dc4c04033fa549b2a2ce563434b5015bab9d/extensions/gitpod-web/src/extension.ts#L37)). For this, we need to use [JB's TerminalView](https://github.com/JetBrains/intellij-community/blob/master/plugins/terminal/src/org/jetbrains/plugins/terminal/TerminalView.java#L67) (which is part of the built-in plugin Terminal) and the [TerminalServiceGrpc](https://github.com/gitpod-io/gitpod/blob/8bdd0ca581eea5fd361c40b562cdc2eb345005fe/components/supervisor-api/java/src/main/java/io/gitpod/supervisor/api/TerminalServiceGrpc.java#L15).

**Comment by felladrin** [comment]
@loujaybee, do you think we can close this, now that https://github.com/gitpod-io/gitpod/pull/9443 has been merged?

**Comment by akosyakov** [comment]
yes, let's close it
