### ISSUE TITLE
the git view show bogus info about access to a fork

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#653]
I've switched my local branch from the fork theia repo to which i don't have access to upstream via terminal wtih `git push -u upstream HEAD`. The git view keeps showing that i don't have an access to the fork nevertheless.

<img width="569" alt="Screen Shot 2019-07-02 at 11 26 15" src="https://user-images.githubusercontent.com/3082655/60502351-ef5b4980-9cbd-11e9-8f0a-9a3b649a141b.png">

**Comment by AlexTugarev** [comment]
interesting. how did you switch the remotes exactly?
what does `git remove -v` show you?

**Comment by AlexTugarev** [comment]
@akosyakov, I just tested and after switching to a fork with write access, the message is gone.

**Comment by akosyakov** [comment]
I don't switch remotes, i only switch remote branch for my local branch. I do it simply by `git push -u upstream HEAD`, so a new branch in upstream is create and my branch now points to it. After that i can push.
