### ISSUE TITLE
deploy gp cli independent

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6533]
In prod we still build images with mk2, which ships `gp` as part of the Gitpod layer. In preparation for mk3 we started to ship `gp` with supervisor:
https://github.com/gitpod-io/gitpod/blob/d3ce797ae7159a30b22b8c1436d3398435299c62/components/supervisor/pkg/supervisor/supervisor.go#L390-L399

If the gitpod-layer is present, `/usr/bin/gp` will be present which makes the symlink operation fail.

To ship the `gitpod-cli` independently of the gitpod-layer even with mk2, we could just delete the `to` path prior to symlinking, i.e.

```Go
	 for k, v := range binaries {
		var (
			from = filepath.Join(base, k)
			to   = filepath.Join("/usr/bin", v)
		)

		// New code
		_ = os.Remove(to)
		// ends here

		err = os.Symlink(from, to)
		if err != nil && !os.IsExist(err) {
			log.WithError(err).WithField("from", from).WithField("to", to).Warn("cannot create symlink")
		}
	}
```

Error checking is left as an exercise to the reader. Beware that `os.IsNotExist(err)` is a valid case if there's no gitpod-layer.

**Comment by loujaybee** [comment]
🤔  This is an interesting one, what would the deploy path/process look like by the end of the changes? Where would the prod artifact be stored/fetched from?

**Comment by csweichel** [comment]
It would mean that `gitpod-cli` changes are subject to the same lifecycle as supervisor changes
