### ISSUE TITLE
Some installed extensions got removed and preferences were reverted

### ISSUE THREAD

**Issue by wisammechano** [gitpod-io/gitpod#6535]
### Bug description

I was working on gitpod, and suddenly, I opened a workspace to find out some themes, extensions, and preferences were removed and reverted to fresh gitpod workspace. I tried another workspace and it is the same.

Example extensions that were removed:
- [Tomorrow and Tomorrow Night Theme Kit](https://open-vsx.gitpod.io/vscode/item?itemName=ms-vscode.Theme-TomorrowKit)
- [EJS language support](https://open-vsx.gitpod.io/vscode/item?itemName=DigitalBrainstem.javascript-ejs-support)
- [ESLint](https://open-vsx.gitpod.io/vscode/item?itemName=dbaeumer.vscode-eslint)

Example workspace: azure-sloth-bztnmd5l

### Steps to reproduce

I am not sure what happened that caused this to happen, could be an update? though I am always getting the new version installed notification so not quite sure.

### Workspace affected

all

**Comment by akosyakov** [comment]
Hi @wisammechano Could you use `Developer: Open Window Log File...` command and collect them for 2 use cases: (1) install a new extension with sync, and then (2) start a new workspace to check that it is sycned. We don't start frontend logs and they would be helpful to investigate. You can send them to anton@gitpod.io Thank you!
