### ISSUE TITLE
Couldn't find issue or pull request error

### ISSUE THREAD

**Issue by vdesabou** [gitpod-io/gitpod#6536]
### Bug description

I wanted to try to open this PR https://github.com/confluentinc/cp-demo/pull/401, but I get:

![140043797-2a13e7a6-5780-4547-84bc-861ae858873a](https://user-images.githubusercontent.com/4061923/140044776-50ac9186-aad1-4e70-b8f4-8ce6e756d83d.jpg)

whereas it works for other colleagues, see https://github.com/confluentinc/cp-demo/pull/401#issuecomment-958842924

Any idea why it doesn't work for my account ?
I've tryied to logout/login from my gitpod account
I've tried with multiple browsers (Safari, Firefox and Brave)

### Steps to reproduce

Click on this link https://github.com/confluentinc/cp-demo/pull/401

### Expected behavior

Open a workspace as expected

**Comment by chuck-confluent** [comment]
Welp, this wasn't happening for my other pull request, but here it is again:
- https://github.com/confluentinc/cp-demo/pull/421

![image](https://user-images.githubusercontent.com/48225759/163232226-319ee637-a5b7-4a93-b93c-abda383b4a9c.png)

**Comment by axonasif** [comment]
@chuck-confluent it might have something to do with the recent incidents: https://www.gitpodstatus.com/
I wasn't able to reproduce when I open your specified PR on Gitpod, I'm landing on `US` servers BTW.

**Comment by chuck-confluent** [comment]
Issue sometimes seems to be fixed by logging out and back in (incognito window), but other times not. Same with this error when prebuilding:

![image](https://user-images.githubusercontent.com/48225759/163251705-cf935eb0-d6f2-44a0-8eab-c3228a8016af.png)

**Comment by dustin-cowles** [comment]
> Issue sometimes seems to be fixed by logging out and back in

I just ran into this issue as well and that fixed it for me.
