### ISSUE TITLE
Nicely handle OOM killed IDE processes

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#6545]
For VS Code I also test what happens if IDE process gets OOM killed and it does not work with IntelliJ:
- if i kill launcher.sh workspace crashes
- if i kill startup.sh (which is unlikely) then it tries to start forever more and more instances and they crash immediately

_Originally posted by @akosyakov in https://github.com/gitpod-io/gitpod/pull/6538#issuecomment-959503542_

**Comment by loujaybee** [comment]
Added to the Open BETA epic of JetBrains, removed from inbox, we can pull through all the open beta items when the private beta is opened up and feedback starts to come in 🙏

**Comment by akosyakov** [comment]
Please don't wok on this issue. I keep it for a candidate.

**Comment by akosyakov** [comment]
It also turned out that backend restart itself for instance if a user install a new plugin. We should make sure that in such case we won't run 2 backends afterwards.
