### ISSUE TITLE
Run Prebuild error: operation not permitted! missing get permission on workspace

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6549]
I created a [new project](https://gitpod.io/t/gitpod/projects) for a [repo](https://github.com/gitpod-io/template-typescript-node) which already had existing workspaces used by other users, but no project yet. 

The GitHub app was installed on the org by a different team admin.

I navigated to the [project configuration page](https://gitpod.io/t/gitpod/template-typescript-node/configure) in the gitpod.io dashboard, and clicked on "Run Prebuild"

Error: `operation not permitted! missing get permission on workspace`

![Screenshot 2021-11-03 at 16 11 00](https://user-images.githubusercontent.com/849592/140147007-88b67ba1-8d73-414b-93b3-a7da3e9a41df.png)

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6549#issuecomment-960563017):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
> The GitHub app was installed on the org by a different team admin.

@jldec  To clarify: Was the user who installed the GitHub app part of your new team or not? (I interpret as: no)

Not sure if "T&P" has touched that yet, but: Before the user who installed the GitHub app was the one we used to run the prebuilds with. If he's not part of the team, the prebuild likely won't get `projectId` set.

**Comment by AlexTugarev** [comment]
> @jldec To clarify: Was the user who installed the GitHub app part of your new team or not? (I interpret as: no)

the answer is actually yes. otherwise I'd not be able to see the logs.

**Comment by jldec** [comment]
### To Reproduce
- open the [Gitpod team](https://gitpod.io/t/gitpod) in the dashboard
- add a new project with the repo `template-typescript-node`
- click on "Run Prebuild" in the configuration page

For reasons I don't understand the problem is not reproducible with the repo `template-astro`

**Comment by jankeromnes** [comment]
Hmm, this reminds me of a `TODO` I left for myself in the `cancelPrebuild` code:

https://github.com/gitpod-io/gitpod/blob/c715b3521f2a2d68937cdd44ecfa35674b3c10c5/components/server/ee/src/workspace/gitpod-server-impl.ts#L1600

If this problem is what I think it is, it has never been possible to cancel a prebuild that you don't directly own.

To make it possible to cancel team prebuilds, the access guards of all `server` methods involved need to be made compatible with teams.

I can give this a go this week:

/assign

**Comment by geropl** [comment]
@jankeromnes I'd love to review, especially to learn what the underlying problem is :smile:

**Comment by jankeromnes** [comment]
@geropl Thanks for the offer! 🙏 (TL;DR I think it's "stop workspace" that isn't allowed for non-personal team workspaces, but I was planning to double-check these access guards anyway)
