### ISSUE TITLE
Repository name in environment variable can not contain "."

### ISSUE THREAD

**Issue by mouse484** [gitpod-io/gitpod#655]
We can include "." In GitHub's repository name.
But not with Gitpod's environment variable.

Do you have any reason?

**Comment by jankeromnes** [comment]
Hi @mouse484, great catch!

We don't have this restriction when using the command `gp env MY_VAR=yolo` in a workspace Terminal, but for some reason, we do have the restriction in https://gitpod/environment-variables/ :

<img width="1028" alt="Screenshot 2019-07-04 at 16 26 12" src="https://user-images.githubusercontent.com/599268/60673670-91bf2c80-9e78-11e9-9ca1-77f68a0ae39f.png">

I think that's a bug.

**Comment by jankeromnes** [comment]
I've located the regex that causes this problem, and made it support the `.` character. 🙂 

Hopefully my fix will get merged & deployed soon! 🤞

And on a personal note, I'll be on vacation for one week, starting tomorrow. 🌻
