### ISSUE TITLE
Flutter install requires user input -- fail

### ISSUE THREAD

**Issue by oravecz** [gitpod-io/gitpod#6552]
### Bug description

When trying the documented [Flutter Quickstart](https://www.gitpod.io/docs/quickstart/flutter#flutter-quickstart), the prebuild process requires user input to accept the Android SDK license agreement. As far as I can tell, there is no way to provide user input during the prebuild process. This causes this step to timeout after an hour, and the prebuild fails.

### Steps to reproduce

Follow the directions on https://www.gitpod.io/docs/quickstart/flutter#flutter-quickstart.

Step 3 fails.

```
You may need to restart any open editors for them to read new settings.
Downloading package sky_engine...                                  464ms
Downloading flutter_patched_sdk tools...                           415ms
Downloading flutter_patched_sdk_product tools...                   371ms
Downloading linux-x64 tools...                                   1,873ms
Downloading linux-x64/font-subset tools...                         154ms
Picked up JAVA_TOOL_OPTIONS: -Xmx2576m
5 of 6 SDK package licenses not accepted. 100% Computing updates...
Review licenses that have not been accepted (y/N)?
1/5: License android-googletv-license:
---------------------------------------
Terms and Conditions

This is the Google TV Add-on for the Android Software Development Kit License Agreement.
[...]
August 15, 2011
---------------------------------------
Accept? (y/N): 
```

### Workspace affected

emerald-goldfish-nj3web2k

### Example repository

https://github.com/gitpod-io/template-flutter

**Comment by ghuntley** [comment]
👋 Resolved via https://github.com/gitpod-io/template-flutter/pull/1
