### ISSUE TITLE
Support pass-listing emails for preview envs

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#6554]
Currently, in preview environments new users that don't have an `@gitpod.io` email address automatically get blocked. 

In this case @shaal got blocked by this :(

![image](https://user-images.githubusercontent.com/239422/140273408-0948bbf4-d75f-433f-9e5f-b8d19049ecaf.png)

There are two ways to solve this:
a) `kubectx exec` into the `mysql` pod and edit `blocked` column in the `d_b_identity` table for your user.
b) pass-list the email in 

https://github.com/gitpod-io/gitpod/blob/7af2c7328ef6ffb30dbe9f8b3f5664e0c0f79270/.werft/values.dev.yaml#L49-L52

However, I believe the pass-list currently only supports email domains and not individual email addresses. See the `@` in `@{e}`:

https://github.com/gitpod-io/gitpod/blob/7abe78c91792c18b0c22103c890b25ea3a4cdf05/components/server/src/user/user-service.ts#L142-L143

Proposed solution: Support individual email addresses on the pass-list.

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6554#issuecomment-960524117):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6554#issuecomment-960524820):

>/team meta
>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6554#issuecomment-960524921):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by JanKoehnlein** [comment]
TIL from @corneliusludmann: 
>When he has access to the core-dev cluster, can't he just unblock himself with the DB, e.g. by running this?
```
leeway run components:unblock-user
```

**Comment by corneliusludmann** [comment]
More info: https://www.notion.so/gitpod/How-we-develop-e8ce7e562478458a9223eb9b797415b2#4b664647f18f4ceb89f084e0b5073757
