### ISSUE TITLE
Reduce confusion between Team plans and new Teams

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6557]
Users of teams are concerned about how older Team plans interact with the new Teams.

- are memberships automically shared? (no)
- does deleting one kind of team affect the other kind? (also no)

While we work on consolidating the 2 kinds of teams and their memberships, it would be helpful to offer reassurances or clarifications in the UI and the documentation.

**Comment by jldec** [comment]
/unschedule
needs more clarification/design.

**Comment by gtsiolis** [comment]
Removing assignment for now.
