### ISSUE TITLE
ESLint plugin doesn't work in the editor

### ISSUE THREAD

**Issue by maksimr** [gitpod-io/gitpod#6558]
### Bug description

ESLint plugin doesn't show problems in the editor

### Steps to reproduce

- Open [this project](https://github.com/maksimr/uikit)
- Type expression without `;`

ER: Editor show the lint problem
AR: No errors

### Expected behavior

Editor shows the lint problem

### Example repository

https://github.com/maksimr/uikit

### Anything else?

Selected editor is the latest Visual Studio Code

ESLint plugin `v2.1.20`
Error lens plugin `v3.4.0`
ESLint npm package used in the project `8.1.0`

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/616193/140303666-c0180629-de4e-4c11-b5c2-30ee0f39123a.png">

If run `lint` using terminal, all works fine

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/616193/140303779-4cc4238c-76b0-4d19-b036-b732c953668c.png">

On desktop version of VSCode all works fine in the example project

Settings:

```json
{
  "workbench.colorTheme": "Default Dark+",
  "workbench.iconTheme": "vs-seti",
  "workbench.activityBar.visible": false,
  "zenMode.centerLayout": false,
  "zenMode.fullScreen": true,
  "editor.fontSize": 24,
  "editor.lineNumbers": "off",
  "editor.minimap.enabled": false,
  "editor.wordBasedSuggestions": true,
  "editor.tabSize": 2,
  "editor.fontLigatures": true,
  "editor.quickSuggestions": {
    "other": true,
    "comments": true,
    "strings": true
  },
  "editor.formatOnSave": true,
  "editor.suggestSelection": "first",
  "editor.fontFamily": "Menlo, Monaco, 'Courier New', monospace",
  "editor.multiCursorModifier": "ctrlCmd",
  "terminal.integrated.fontSize": 22,
  "terminal.integrated.gpuAcceleration": "canvas",
  "javascript.suggest.autoImports": true,
  "javascript.format.insertSpaceBeforeFunctionParenthesis": false,
  "javascript.format.semicolons": "insert",
  "javascript.suggest.completeFunctionCalls": true,
  "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true,
  "javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "typescript.tsserver.experimental.enableProjectDiagnostics": true,
  "typescript.referencesCodeLens.enabled": true,
  "quokka.suppressExpirationNotifications": true,
  "quokka.suppressGlyphMarginNotifications": true,
  "errorLens.enabledDiagnosticLevels": [
    "error",
    "warning",
    "info",
    "hint"
  ],
  "prettier.singleQuote": true,
  "prettier.trailingComma": "none",
  "prettier.jsxSingleQuote": true,
  "gitlens.codeLens.enabled": false,
  "gitlens.currentLine.enabled": false,
  "git.autofetch": true,
  "git.confirmSync": false,
  "git.enableSmartCommit": true,
  "calva.enableJSCompletions": true,
  "redhat.telemetry.enabled": true,
  "vim.easymotion": true,
  "vim.handleKeys": {
    "<C-d>": true,
  },
  "vim.leader": ",",
  "vim.insertModeKeyBindings": [
    {
      "before": [
        "j",
        "k"
      ],
      "after": [
        "<Esc>"
      ]
    }
  ],
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": [
        "<leader>",
        "f"
      ],
      "commands": [
        "workbench.action.findInFiles"
      ]
    },
    {
      "before": [
        "<leader>",
        "b"
      ],
      "commands": [
        "editor.debug.action.toggleBreakpoint"
      ]
    }
  ]
}
```

**Comment by akosyakov** [comment]
I think eslint has some kind of trust mode in new versions. So you should click on eslint status bar entry and allow it execution of code from workspace. Maybe it can be configured to be always on per user.

**Comment by maksimr** [comment]
@akosyakov Hm... interesting. Before I saw modal dialogue with such kind of text and yup after accept it worked. But now no dialogue and if click on "ESLint" in bottom status bar it open output panel so I don't see where to enable it.

**Comment by hm2075** [comment]
might be something to do with this

https://github.com/neoclide/coc-eslint/issues/117


i struggled with v8 too so I just dropped back to version 7

**Comment by maksimr** [comment]
@hm2075 looks like you are right. I guess that ESLint version from open vsx is out of date. Visual studio marketplace contains ESLint plugin with latest version **2.2.2** and on open vsx only **2.1.20**

**Comment by akosyakov** [comment]
Thanks for discovering it. We are working on better testing and updates for major extensions.

**Comment by akosyakov** [comment]
Could you try again please? It should be fixed.

**Comment by maksimr** [comment]
@akosyakov works perfectly now! Thanks a lot
