### ISSUE TITLE
 /usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by XinYaanZyoy** [gitpod-io/gitpod#656]
when I run 
`$node_package`

note: the PATH to node package is set; which is installed globally but the package is local(i.e, `workspace/node_package`); the global one being `/home/gitpod/.nvm/versions/node/v10.15.3/bin/node`

I get the error...
`/usr/bin/env: ‘node\r’: No such file or directory`

note that running;
`node ./bin/node_package_entry_file`
works fine from workspace/node_package

what causes this error??
i've read many gitpod but couldn't resolve my issue; the kind of similar issues(suggested by github) #165 #323

**Comment by XinYaanZyoy** [comment]
oopz!
it's working now!

the problem was about something related to LF/CRLF

in my project there's .editorconfig and there was a key end_of_line = crlf!!

i just changed it to lf and now it goes!

**Comment by jankeromnes** [comment]
Cool, thanks a lot @XinYaanZyoy for sharing the solution to this problem! 💯 

I'm glad it's now working for you, and I'm sure future users who run into the same bug will be very thankful to see your solution here. 👍
