### ISSUE TITLE
Cannot paste text in terminal using gesture in android

### ISSUE THREAD

**Issue by vcyzteen** [gitpod-io/gitpod#6568]
Does this issue occur when all extensions are disabled?: Yes/No
A: No

- VS Code Version: Latest
- OS Version: Android 10
- Briwser: Chrome

The Problem:

https://user-images.githubusercontent.com/25115070/140428981-e519baeb-4e32-47a7-bdc6-6fe2e6d7201e.mp4

Hello sir I want to ask if I use android to open vscode gitpod if I want to copy text it can't. (like the video above) and if I space my command it will be weird like the video above. does this really not work 100% on the android web browser sir. Or is ink only valid on linux, windows, macos web browsers?. Thanks

**Comment by jeanp413** [comment]
@vcyzteen I fixed your video now it displays correctly, also I transferred the issue to the gitpod repo as you are using Gitpod.
Regarding your issue, that's indeed a bug with vscode/xterm.js, maybe you can workaround it by invoking paste using the keyboard.

**Comment by vcyzteen** [comment]
> @vcyzteen I fixed your video now it displays correctly, also I transferred the issue to the gitpod repo as you are using Gitpod. Regarding your issue, that's indeed a bug with vscode/xterm.js, maybe you can workaround it by invoking paste using the keyboard.

okay sir. thanks for thr answer
