### ISSUE TITLE
Pushing new commits to a branch, does not stop a prebuild from a previous commit of the same branch.

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#6569]
### Bug description

I think a previously running prebuild should be cancelled if new commits are pushed to the same branch. 

I noticed it after I pushed changes to a branch, and realized I forgot to make a small change.
![image](https://user-images.githubusercontent.com/22901/140465603-a8bb0de6-3c34-483a-83f2-b44ef3da4458.png)

### Steps to reproduce

Create long init task in `.gitpod.yml`.
After pushing a commit that will trigger the prebuild, push another commit to the same branch, and go to Prebuilds page on your gitpod.io account.

### Expected behavior

Seems like waste of resources to keep the previous prebuild running.
Not sure if this might cause other issues (like an old prebuild finish running after the latest prebuild, and perhaps override things?)

**Comment by loujaybee** [comment]
Thanks for adding @shaal ! 

Just came here to note that this behavior is how most CI tools also work, and the workflow would be to cancel any unwanted jobs. Might be quite difficult to work out whether or not a commit should or shouldn't be built 🤔

**Comment by jldec** [comment]
Perhaps some options to consider (for any branch with prebuilds)

- only serve workspaces with prebuilds for HEAD
- let users who are starting a new workspace know when a new prebuild on HEAD is pending
- scavenge and delete old prebuilds

OR 

- serve workspaces with prebuilds for any commit
- keep older prebuilds available for some time

#### for additional awareness of prebuilds 
- let users know which prebuild (for which commit) they are on inside the workspace.
- this would help users working on branches on busy projects to know when a new prebuild is available

**Comment by svenefftinge** [comment]
> And that it might be quite difficult to work out whether or not a commit should or shouldn't be built 🤔

Can you elaborate on what challenges you expect here? I'm currently believing that just building the latest change per branch would do 😇 .
