### ISSUE TITLE
[Installer]: jobs cannot be updated

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6573]
Context: the installer uses Kubernetes jobs to run the database migration. Each time the rendered output of the installer is `kubectl apply`'ed, the job resource is re-created.

> This is part of a bigger migration piece, but capturing for testing purposes

Deploy a version of the application (eg, `main.1732`) and then deploy an update (eg, `main.1779`). The job fails because jobs are immutable, even though the previous job has run to completion

We need something that can destroy old jobs (like Helm hooks) so that migrations can be applied properly

**Comment by csweichel** [comment]
As Jenting pointed out, this is the right way to go: https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs

**Comment by MrSimonEmms** [comment]
Predictably, it appears that `TTLAfterFinished` alpha features are not enabled in Azure. Whilst it's the right way to go long term, we need to have something that is able to work if the alpha feature is not enabled, regardless of cloud

**Comment by MrSimonEmms** [comment]
This does work in Azure 1.21 as @aledbf said 🎆
