### ISSUE TITLE
Open Workspace from team context should preserve team context when returning to dashboard

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6575]
This applies to any workspace which has a project under a team in Gitpod.

When navigating in the browser from the workspace back to the dashboard, users should not have to search for the team again, before seeing the workspace or project which they just came from. 

One example of this the **/new project** flow:

- create a project on a repo
- open the workspace e.g. from the project configuration page
- exit the workspace and click on "Go to Dashboard"
- This should go to `https://gitpod.io/t/<team>/projects` not `https://gitpod.io/projects`

**Comment by gtsiolis** [comment]
Clicking _Open Dashboard_ from the VS Code application menu goes back to `/` which redirects to the last selected team. I assume by _exit the workspace_, you mean stopping the workspace, right? ⚾ 

I've opened https://github.com/gitpod-io/gitpod/pull/6577 to try fixing this.

/schedule
