### ISSUE TITLE
Unable to create a team plan on gitpod-staging

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6588]
This applies only to gitpod-staging.

After entering payment information, the new team plan in the dashboard stays stuck on `Payment in Progress` until what looks like a 15 minute timeout, when it disappears.

Clicking on the `Billing` button in the dashboard brings up the what looks like a successful subscription, and  provides links for the account, invoice etc.

![Screenshot 2021-11-05 at 13 45 09](https://user-images.githubusercontent.com/849592/140573879-628800cc-3575-4851-af96-e75b0825c329.png)

![Screenshot 2021-11-05 at 13 49 39](https://user-images.githubusercontent.com/849592/140573910-f6682aa4-5274-496f-a7ca-d4ba3f9096e7.png)

**Comment by roboquat** [comment]
@geropl: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6588#issuecomment-964883709):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
Looks like our staging payment endpoint cannot be resolved.

internal discussion: https://gitpod.slack.com/archives/C01KGM9EBD4/p1636534393234000

**Comment by geropl** [comment]
New DNS entry is up and first events are fine.
