### ISSUE TITLE
Cannot open workspace on git-lfs repository, where git-lfs is used in prebuild

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6598]
`git-lfs` does not appear to be available in the default image on Gitpod.
See https://github.com/gitpod-io/workspace-images/pull/553 and https://github.com/gitpod-io/workspace-images/pull/450 

[Users](https://community.gitpod.io/t/cannot-start-a-gitpod-prebuild-unable-to-find-workspace-starting-logs/5554) are resorting to `brew install git-lfs` to get past this issue. 

This works inside a workspace command - E.g. https://github.com/jldec/lfs-test/pull/3/files or [open workspace](https://gitpod.io/#https://github.com/jldec/lfs-test/pull/3)
But this does not work inside a prebuild - E.g. https://github.com/jldec/lfs-test/pull/2/files or [open workspace](https://gitpod.io/#https://github.com/jldec/lfs-test/pull/2)

The latter produces the following error
![Screenshot 2021-11-07 at 18 43 03](https://user-images.githubusercontent.com/849592/140658176-7cef3902-bfac-444e-aa67-80ff8749e7e1.png)

Ideally git-lfs should be available in the default image so that repos which depend on git-lfs "just work" ™️, without installing git-lfs or having to run git lfs pull

**Comment by ghuntley** [comment]
Observations:

```
gitpod /workspace/workspace-full $ git lfs
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
        log
gitpod /workspace/workspace-full $ cat /etc/gitconfig
cat: /etc/gitconfig: No such file or directory
gitpod /workspace/workspace-full $ 
```

**Comment by cfoust** [comment]
Running `git lfs uninstall` at the end of `init` makes this not happen.

**Comment by sagor999** [comment]
@jldec we added support for git-lfs here: https://github.com/gitpod-io/gitpod/pull/8119
give it a try and please re-open if it doesn't work for you.
