### ISSUE TITLE
[Release Notes] Broken images

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#660]
Images are not shown in the Release Notes 😞

**Comment by 32leaves** [comment]
Is this still the case?
In which version did this happen (1592)?

**Comment by AlexTugarev** [comment]
Yes.

**Comment by corneliusludmann** [comment]
FYI: Still is. Also the background color does not adapt to the light theme.

![image](https://user-images.githubusercontent.com/24960040/68138307-a4319b80-ff28-11e9-87df-90d26bf3fceb.png)
