### ISSUE TITLE
[test] 9 tests fail with "error parsing DB_PORT" for self-hosted

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#6604]
### Bug description

We'll need to [extend the test framework](https://github.com/gitpod-io/gitpod/blob/a9dca2a2bf7f1562ee90e53b038d63f9cbba824f/test/pkg/integration/apis.go#L432) as the DB port comes from a secret now.

### Steps to reproduce

[Follow these steps](https://github.com/gitpod-io/gitpod/tree/main/test#manually-against-a-kubernetes-cluster) against a self-hosted installation of Gitpod.

### Workspace affected

n/a

### Expected behavior

The tests should pass.

### Anything else?

Will require a cluster in GCP to do testing. 

1 test was failing due to `minio.default.svc.cluster.local: no such host`. This may have been resolved in a recent commit, but double check. If not, see if it can be resolved.

4 tests were failing (even with the saas) due to `cannot start workspace`. This may have been resolved in a recent commit, but double check.

The failures were found in #6518.

**Comment by roboquat** [comment]
@kylos101: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6604#issuecomment-963490012):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by kylos101** [comment]
In d2e9f27451cb7d5e77e4b041e57c3a741db85ec0, the installer was updated to populate ENV VARs from secret references.

[corev1.EnvVar](https://pkg.go.dev/k8s.io/api/core/v1#EnvVar) has various fields (Name, Value, and ValueFrom). The value field returns "" when trying to get a value that is backed by a secret reference. 

We'll need a small code change to fix our integration tests to work with the installer. It will try to extract the data first from the `value`, and if "", will then try using the details in `valueFrom` and its `secretKeyRef` to get the data from the actual secret.

Here is a sample of what the data structure looks like when `corev1.EnvVar` is used to access an env var backed by a secret ref.
```go
'{"name":"DB_PORT","valueFrom":{"secretKeyRef":{"name":"mysql","key":"port"}}}'
```

**Comment by roboquat** [comment]
@kylos101: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6604#issuecomment-965822220):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
