### ISSUE TITLE
Large package like pip rasa not installing

### ISSUE THREAD

**Issue by skylacking04** [gitpod-io/gitpod#6614]
### Bug description

trying to install from a prebuild, or regular build for a python package rasa. I get error messages like 

  Downloading sniffio-1.1.0-py3-none-any.whl (4.5 kB)
INFO: pip is looking at multiple versions of aiofiles to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking

Then the operation just times out, and the package does not install

### Steps to reproduce

create a new repo

open repo with gitpod

open a terminal

enter command : pip install rasa

### Expected behavior

expect package to install

**Comment by pawlean** [comment]
Thanks for leaving this bug report! I can confirm that I was able to replicate this. Our team will look into this when they can, thanks for supporting Gitpod!
