### ISSUE TITLE
No margin or footer below preferences page

### ISSUE THREAD

**Issue by mteam88** [gitpod-io/gitpod#6630]
I see that there is no margin or preference below the selection for theme.
![image](https://user-images.githubusercontent.com/84196639/140942702-6dbf7ee1-9c23-43ad-953b-5cadd1c288fe.png)
This is scrolled all the way down. 

This could easily be solved by including the Gitpod footer there or adding a margin to the bottom of the page.

**Comment by gtsiolis** [comment]
Thanks @mteam88 for noticing! This is known, closing this in favor of https://github.com/gitpod-io/gitpod/issues/4634.
