### ISSUE TITLE
[image-builder-mk3] Keep credentials out of the workspace

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6631]
In image-builder-mk3 image-builds happen in headless Gitpod workspaces. Those workspaces are well isolated from each other and the node they run on. However, there's no such isolation between things that run inside a workspace, e.g. buildkit. If we placed the credentials required to push the image inside the workspace, users could potentially access those credentials during the image build.

We need to find a way so that we can push the image, but don't give users access to those credentials at build time.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6631#issuecomment-964213392):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
