### ISSUE TITLE
Gitpod badge in README.md doesn't work in Brave browser

### ISSUE THREAD

**Issue by alkoclick** [gitpod-io/gitpod#6632]
### Bug description

The "Gitpod: Ready to code badge" does not work on the Brave browser (perhaps other privacy-minded browsers too?) in Mac and Android.

### Steps to reproduce

- Using Brave browser on MacOS Catalina 
- Go to https://github.com/gitpod-io/gitpod#readme
- Click the GitPod badge
- You will get the following:

<img width="548" alt="Screenshot 2021-11-09 at 14 44 35" src="https://user-images.githubusercontent.com/9469549/140934941-b05f16c2-1d2f-490c-8c1b-2bc0528031f5.png">

### Expected behavior

A Gitpod environment opens up a workspace on the Gitpod Github repository

### Example repository

https://github.com/gitpod-io/gitpod#readme

### Anything else?

Brave version: Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)
OS version: MacOS Catalina 10.15.7

In my understanding, the bug is probably caused by the badge using the "referrer" header. The policy appears to be "No referrer when downgrade" which means that going from https://github.com/gitpod-io/gitpod to https://github.com/gitpod-io/gitpod, the referrer header should be sent. In my request headers I see that the following was sent:
```
referer: https://github.com/
```

This is clearly not enough to open a workspace on the right repo, so the failure after that makes sense. The problem can obviously be worked around by changing the link to https://gitpod.io/github.com/gitpod-io/gitpod/ but I don't think that's the ideal fix?

**Comment by pawlean** [comment]
Thanks for bringing this up, @alkoclick! I can reproduce this on Brave. 

cc @mikenikles as a regular Brave Browser user. Any ideas on this fix?

**Comment by shaal** [comment]
See https://github.com/gitpod-io/gitpod/issues/6410

**Comment by mikenikles** [comment]
As per Ofer's link, the fix is not to use the `/from-referrer` link.
