### ISSUE TITLE
[dashboard] GitHub app installation: parameter 'installation_id' is undefined

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6633]
internal discussion: https://gitpod.slack.com/archives/C020VCB0U5A/p1636466199191100

When a user wants to install the Gitpod GitHub app it may happen that the `installation_id` URL parameter is `undefined`, resulting in a modal saying "Failed to install" which shows a DB error (duplicate primary key).

We should:
 - find out how this might happen
 - make the `installation_id=undefined` case nicer

**Comment by jldec** [comment]
#6421 is similar, but not exactly the same

After changing auth settings for the GitHub App (from all-repos to specific repos), @JanKoehnlein also saw a ER_DUP_ENTRY message.
