### ISSUE TITLE
Unresponsive Select action in repo selection in New Project form 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6635]
A user [reported](https://community.gitpod.io/t/new-project-select-not-working/5579) that a `Select` button was not working for them when selecting a repo to create a Project.

In this case the repo lives under a GitHub org, and the user mentioned that the authorizations in the org appear to be correct.

We are following up to investigate further, and are tracking in this Issue for reference.

**Comment by laushinka** [comment]
This happened during the incident and we rolled back. Looking at when the user reported it, it seems to coincide with when the incident happened.
