### ISSUE TITLE
Actually share the workspace when clicking on "Share Workspace"

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#665]
Currently, when I want to share my running workspace, I click on my top-right avatar, and select "Share Running Workspace". This gives me a URL.

However, the URL doesn't work, and people I send it to can't access my workspace. The reason is that, in addition to clicking "Share Running Workspace", I also need to click on a small "Share" button.

This is confusing, as I believe my intent to share was already implied when I clicked on "Share Running Workspace". I think Gitpod should automatically "Share" the workspace when I request the URL, just like other common sharing systems (e.g. Google Docs).

It's cool to have the option to "Unshared" it again later, but the current default state when requesting the URL doesn't make sense.

**Comment by svenefftinge** [comment]
Fixed in production
