### ISSUE TITLE
[jetbrains] Wait for content to prevent “Path does not exist” errors

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#6651]
### Bug description

The JetBrains IDE backend service fails from time to time and we see the following error in the logs:

```
JetBrains remote-dev-server.sh (err): Path does not exist: /workspace/gitpod
```

The reason could be that we don't wait for content readiness before we start the IDEs.

We could wait for the project folder in the script that starts the JetBrains IDE backend to fix this.

(see also [internal discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1636549139465600))

### Steps to reproduce

Start workspaces with JetBrains IDE enabled.

**Comment by roboquat** [comment]
@corneliusludmann: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6651#issuecomment-970121552):

>/schedule
>/assign


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
