### ISSUE TITLE
Publish script should resolve VSIX files from GitHub releases for outdated extensions

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6653]

**Comment by akosyakov** [comment]
resolved by https://github.com/open-vsx/publish-extensions/pull/494

**Comment by GitMensch** [comment]
What about Gitlab or otherwise hosted extensions?

**Comment by filiptronicek** [comment]
@GitMensch we are currently looking into that, please see https://github.com/open-vsx/publish-extensions/issues/503.
