### ISSUE TITLE
Need a loading indicator when switching git providers to add new project

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#6654]
There is no indication that something is happening when switching git providers - this can be taken as if the request did not work.
Currently for me it takes ~6 seconds when switching from GitLab to GitHub.

https://www.loom.com/share/83ad367219174b0ea660cd2a9677783d

**Comment by jankeromnes** [comment]
Agreed! This has been bugging me as well. I'd be interested in working on it if nobody else wants to. 😊

**Comment by laushinka** [comment]
> Agreed! This has been bugging me as well. I'd be interested in working on it if nobody else wants to. 😊

@jankeromnes Yas, please! I don't know why but for some reason in my head you're the loading indicator person.. 🤣

**Comment by jankeromnes** [comment]
Haha, sure! 😂 (I get annoyed when our app is being slow, and if I can't make it faster, at least building a loading indicator is therapeutic -- at least I can make _something_ show up really fast)

/assign

**Comment by roboquat** [comment]
@jankeromnes: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6654#issuecomment-968926155):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jankeromnes** [comment]
But why move it back? 🤔

<img width="809" alt="Screenshot 2021-11-15 at 14 47 30" src="https://user-images.githubusercontent.com/599268/141792724-c3645033-6a20-48cd-b633-93df342286ea.png">

**Comment by jankeromnes** [comment]
Don't doubt yourself @roboquat 🤗 first move was correct!

<img width="831" alt="Screenshot 2021-11-15 at 16 32 33" src="https://user-images.githubusercontent.com/599268/141809117-3194e2cb-88a1-4575-a61d-a30e8a695ee0.png">
