### ISSUE TITLE
Underscores are not visible in the terminal while Brave "Shields" are "Up"

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#6658]
### Bug description

As a developer who is working in a Gitpod workspace in the VS Code IDE, when viewing content in the terminal, then I should be able to see underscores. Underscores are not visible in the terminal while Brave "Shields" are "Up".

### Steps to reproduce

[Please refer to this video for a short demo. ](https://www.loom.com/share/eab01a39ddd047ce89c776232f50a32c)

For this, I created a new workspace using our Python Flask template with the Brave web browser with the Shields set to Up (a default).

### Workspace affected

moccasin-tapir-xb6etwed

### Expected behavior

I should be able to see underscores, even with the Shields Up.

### Example repository

n/a

### Anything else?

Other special characters appear to be okay.

![image](https://user-images.githubusercontent.com/1272076/141178442-93930822-bdb8-42dc-b72f-1bbf8fad2190.png)

**Comment by akosyakov** [comment]
Firefox?

**Comment by akosyakov** [comment]
Have you reported it in https://github.com/microsoft/vscode/issues It is most likely an upstream issue.
