### ISSUE TITLE
GitpodMetaMessagebusTotalQueues firing too often

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6662]
Investigate if either:
 - the query is wrong
 - the limit is too conservative
 - we have a real problem that requires fixing

**Comment by ghuntley** [comment]
Appears to be a pattern between 9AM to 10:30AM AEST.

[Internal link](https://gitpod.slack.com/archives/C01TNS8EVQT/p1636763214027500)

**Comment by roboquat** [comment]
@geropl: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6662#issuecomment-968689707):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
Query is fine, we have a real issue: 
![image](https://user-images.githubusercontent.com/32448529/141781264-0bcc751d-8012-43e0-b73b-437a52915382.png)

We had the same issue for some time, but for whatever reason it intensified lately.
