### ISSUE TITLE
Automatically scan dependencies for vulnerabilities

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6664]
To be able to maintain our current good patch-level we need an automatic detection of regressions and signalling of those. This might be either part of our CI pipeline, or a bot on the repository (or sth else).

**Comment by geropl** [comment]
/schedule

Required for SOC2 compliane

**Comment by roboquat** [comment]
@geropl: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6664#issuecomment-968742047):

>/schedule
>
>Required for SOC2 compliane


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
@JanKoehnlein plans to raise this cross-team with the goal to have a per-repo solution.

**Comment by JanKoehnlein** [comment]
Talked to @meysholdt and the platform team is figuring out a way how to do that on the repo, cross-team and cross-language. We discussed shortly whether we should have that as a merge gate in the build, but as I expect that to be triggered on existing old dependencies rather than newly added ones, this would always interfere with the normal dev workflow.

**Comment by mads-hartmann** [comment]
@meysholdt Is this something we want to write a brief RFC for?

**Comment by meysholdt** [comment]
yes, an RFC is a good idea because it could help to brainstorm/discuss what scanning tech we want to use.

**Comment by mads-hartmann** [comment]
I have created a separate issue to write an RFC and scheduled it for the Platform team here https://github.com/gitpod-io/ops/issues/589. I'm closing this issue.
