### ISSUE TITLE
review dev-environment and slim it down

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6665]
Currently `dev-environment` weights in at 15.2 GB (`docker images`).

`docker pull eu.gcr.io/gitpod-core-dev/dev/dev-environment:gpl-dev-reliable-wipe.19`

Depending if you happen to work on a fresh node or not, this considerably slows down workspaces starts (up to minutes!), which slows down cycles times. Also, _updating_ the dev image takes ~20mins atm.

There should be some easy targets, like removing the QEMU VM for eBPF development (if really needed we can still leave the scripts but don't execute them during image build).

[dive](https://github.com/wagoodman/dive/releases/tag/v0.10.0) might be useful as well. We could also review our decision to use `workspace-full-vnc` as base image.

/cc @JanKoehnlein @csweichel @akosyakov

**Comment by roboquat** [comment]
@geropl: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6665#issuecomment-972970873):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
