### ISSUE TITLE
Make it easier to restart a remote session from desktop VSCode

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6672]
When using VS Code Desktop, the user typically goes to Gitpod, uses the command pallette, and opens their changes on their local machine to make edits, however if you go away and come back, the workspace will have closed, and it might not be transparent to the user about the best way to restart their session, regain their code and continue working. 

[Source](https://twitter.com/rothgar/status/1458681588342943744?s=20)

I don't have a particular solution in mind, we could potentially enable this workflow via the local companion app, to list the running workspaces and tab through to restart, we could do it via a command in the pallette on the local VS Code, or provide better pop-up notifications on VSCode to re-establish the remote session. 

Similar to #6679 for JetBrains. 

Also related: #6602

**Comment by svenefftinge** [comment]
I think a frontend extension in VS Code that shows a notification when the workspace timed out (or alters the status bar color) would be great including a command to start the workspace again.

**Comment by loujaybee** [comment]
Removing from inbox, quite likely the solution here will be dependent on work on the public API

See: https://github.com/gitpod-io/gitpod/issues/8512 and https://github.com/gitpod-io/gitpod/issues/7900

**Comment by laushinka** [comment]
@loujaybee Shouldn't this issue be part of https://github.com/gitpod-io/gitpod/issues/9221?

**Comment by loujaybee** [comment]
Good catch, @laushinka ! Yes, it looks duplicated. The other started as "create workspaces" but was scoped down to restart. Let me close this one to avoid confusion!
