### ISSUE TITLE
Suppress VS Code notification to open in VS Code Dekstop on tablets or platforms where VS Code Desktop is not supported

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#6674]
### Problem to solve

Currently, you open a new workspace using VS Code in Browsier you get a VS Code notification to open a workspac in VS Code Dekstop. However, this is not applicable when using Gitpod on tablets or platforms where VS Code Desktop is not supported.

<img width="493" alt="Screenshot 2021-11-04 at 11 00 24 PM" src="https://user-images.githubusercontent.com/120486/141359112-57e123f4-6b38-4d20-93dd-329e56705813.png">

## Proposal

Supress VS Code notification to open in VS Code Dekstop on tablets or platforms where VS Code Desktop is not supported

**Comment by shaal** [comment]
+1
Yes please.

But also, I'd like to permanently dismiss the popup when I open Gitpod in browser (on a desktop computer).

**Comment by gtsiolis** [comment]
Thinking out loud, we could probably also drop that notification all together in the future :a: after improving the UX for opening desktop IDE's (https://github.com/gitpod-io/gitpod/issues/6602) and :b: since this notification was originally added to improve visibility of the only desktop editor that was initially supported, VS Code. Cc @loujaybee

**Comment by akosyakov** [comment]
> But also, I'd like to permanently dismiss the popup when I open Gitpod in browser (on a desktop computer).

@shaal I probably misunderstand something but clicking `Don't show again` in this notification forever disables this notification. If it is not the case it is a bug.

**Comment by shaal** [comment]
@akosyakov you are absolutely right!
🤦‍♂️ I don't know how I missed that obvious button 😁
Thank you!
