### ISSUE TITLE
Add a "name" attribute to ports in .gitpod.yml

### ISSUE THREAD

**Issue by davemecha** [gitpod-io/gitpod#6678]
## Is your feature request related to a problem? Please describe

When I have multiple Ports (more than 5, sometimes up to 10) on a project I get confused about which service is behind which port.

## Describe the behaviour you'd like

It would be so awesome to be able to add a `name` attribute to the port like I can do with commands. The name should be displayed right next to the port in the Remote Explorer.

## Describe alternatives you've considered

I don't have a good workaround. Additionally it could help to display the shell command as well, but this is no alternative. If only the service name would be displayed, it might be too little information (e.g. `node`). If you would display the whole command line, it might be too long to display in this narrow space. But the full command might be a helpful additional info to be displayed e.g. in a tooltip.
To display the corresponding `.gitpod.yml` command would not help either, since one command might fire up multiple services.

## Additional context

Example:

``` yaml
ports:
  - port: 3000
    name: frontend
    onOpen: ignore
```

**Comment by akosyakov** [comment]
dup of https://github.com/gitpod-io/gitpod/issues/3059
