### ISSUE TITLE
Make Gitpod report un-pushed workspace-only commits as changes

### ISSUE THREAD

**Issue by Dominic-Hoe** [gitpod-io/gitpod#6684]
## Is your feature request related to a problem? Please describe
I find it a little awkward when I'm working in Gitpod, then I push a local commit to finish later on, and I stop the workspace, because sometimes I later on forget that I have pushed local commits and remove the workspace, losing potentially hours of work.

## Describe the behaviour you'd like
An option in the Gitpod settings to allow for Gitpod to detect local commits in the workspace and report them as changes.

## Describe alternatives you've considered
I have considered just not deleting workspaces, however I feel like with the amount of time I spend on Gitpod, this would not be an efficient solution as I sometimes am working on multiple projects at a time and switch between projects throughout the day, so this would not be a viable option based on my workload.

**Comment by jldec** [comment]
Thanks for reporting this @Dominic-Hoe - I can see how accidentally deleting a workspace with commits can be frustrating. 

There is a red indicator showing a count of changes in the workspaces list in the dashboard, and also something similar in the workspace browser window after you close it. 

Where do you go to remove remove workspaces?

![Screenshot 2021-11-12 at 22 35 06](https://user-images.githubusercontent.com/849592/141561146-1f8d482e-9745-44ec-a9bd-0de13d596f2c.png)

![Screenshot 2021-11-12 at 22 34 46](https://user-images.githubusercontent.com/849592/141562574-74e2798a-0cd6-4fbf-a396-b6f79c74aa31.png)

**Comment by Dominic-Hoe** [comment]
> 
> 
> Thanks for reporting this @Dominic-Hoe - I can see how accidentally deleting a workspace with commits can be frustrating.
> 
> There is a red indicator showing a count of changes in the workspaces list in the dashboard, and also something similar in the workspace browser window after you close it.
> 
> Where do you go to remove workspaces?
> 
> ![Screenshot 2021-11-12 at 22 35 06](https://user-images.githubusercontent.com/849592/141561146-1f8d482e-9745-44ec-a9bd-0de13d596f2c.png)
> 
> ![Screenshot 2021-11-12 at 22 34 46](https://user-images.githubusercontent.com/849592/141562574-74e2798a-0cd6-4fbf-a396-b6f79c74aa31.png)

Hi, thanks for the response. I'm aware of this feature however from my testing it does not show changes from local commits, only uncommitted changes. That was the point of my feature request.

**Comment by jldec** [comment]
Aah - that makes a lot of sense @Dominic-Hoe 
Thanks for that suggestion!

**Comment by Dominic-Hoe** [comment]
> 
> 
> Aah - that makes a lot of sense @Dominic-Hoe Thanks for that suggestion!

You're welcome. :)

**Comment by jldec** [comment]
Renamed issue because the word "local" can be confusing in the context of a hosted environment.

**Comment by kylos101** [comment]
Hey @Dominic-Hoe :wave:, what would you like for commits which have not been pushed? 

Are you looking for the ability to see them from the dashboard, much like you would uncommitted files?

Or, are you looking for a warning "before" you explicitly stop a running workspace , giving you an opportunity to avoid stopping, so that you can push the files? 

Either way, thank you for the suggestion! They both seem like helpful ideas (to me). 

@jldec the former seems like a web app solve, but the latter perhaps for IDE? @loujaybee what do you think?

**Comment by Dominic-Hoe** [comment]
> 

It would be ideal to have a modal popup warning about un-pushed workspace-only commits still within the workspace, and also the ability to see them from the dashboard.

If the former is not possible, then the latter would also be totally fine. Thanks for the response though :)
