### ISSUE TITLE
Folding of round brackets

### ISSUE THREAD

**Issue by davemecha** [gitpod-io/gitpod#669]
I have services and components with member observables like this one.

```
export class MyService {

  // ...

  private _entities$: Observable<Data[]> = this._fetchData$
    .pipe(
      filter(data => !!data && isArray(data)),
      map((data: any[]) => data.map(entry => new Entity(entry))),
      shareReplay(1),
      takeUntil(this.destroy$)
    );

  // ...

```

My suggestion is to add the option for code folding for multi line round brackets as well. Esp. in function calls but there might be other useful situations such as angular typescript constructors with multiple injections like this:

```
  constructor(
    private http: HttpClient,
    private translate: TranslateService,
    private auth: AuthService,
    private language: LanguageService
  ) {

  // ...
```

**Comment by akosyakov** [comment]
We are working on support of VS Code extensions which will allow install formatting extensions (Pretties) or other to configure formatting settings for your project or reuse existing vscode settings.

typescript/javascript extension which we use right now unfortunately does not provide such capabilities. You can file an issue in Theia repo to support ts/js formatting settings: https://github.com/theia-ide/theia/issues/new

You can also try to configure something like eslint/tslint to check formatting and apply formatting on the commit then it will work independent from the editor.

**Comment by davemecha** [comment]
@akosyakov Is the code folding capability part of the formatting logic? I would have assumed this separate. But when VS Code extensions are possible, a more versatile code folding should hopefully be possible to implement. At least I found extensions for custom code folding.

I'm also opening an issue on the Theia project.

I can't see how I could improve code folding with eslint/tslint.

**Comment by akosyakov** [comment]
@davemecha sorry I've confused, thanks for the issue in Theia
