### ISSUE TITLE
Self hosted gitpod workspace-full image's environment variables set in Dockerfile gone

### ISSUE THREAD

**Issue by huweiATgithub** [gitpod-io/gitpod#6691]
### Bug description

After following this guide: https://github.com/gitpod-io/gitpod-gke-guide
and start workspace. Everything looks fine at the beginning. Later I found that almost all commands were not found in the workspace. 
It turns out that the binaries are there but the environment variables are not set as expected as in the Dockerfile https://github.com/gitpod-io/workspace-images/blob/master/full/Dockerfile

Besides, I found that the gitpod layers did not append scripts into ~/.bashrc. [now the PYTHONPATH env which unset by gitpod layer can be set now, #6561 ]

### Steps to reproduce

1. Deploy gitpod follows https://github.com/gitpod-io/gitpod-gke-guide
2. Create a minimal Github Repo with a single .gitpod.yml file which containg only one line
    > image: gitpod/workspace-full
3. Run a workspace from that repo by prepending your_gitpod_domain/#
4. export | grep -> to see those environment variables are not set.
5. cat ~/.bashrc | grep -> to see gitpod layer is not modifying bashrc file

**Comment by kylos101** [comment]
Greetings @huweiATgithub , thank you very much for sharing this issue. I've shared this with a teammate, @corneliusludmann , who will be able to help set your expectations.
