### ISSUE TITLE
Open in VS Code doesn't work with Codium

### ISSUE THREAD

**Issue by mahmoudajawad** [gitpod-io/gitpod#6692]
## Is your feature request related to a problem? Please describe
When using Gitpod, it is possible to switch from web browser to installed VS Code and work on the local application, however, some GNU/Linux do provide the free distribution of it; namely VS Codium only. Attempting to action with it doesn't provide any results.

## Describe the behaviour you'd like

Being able to use VS Codium as target to "Open in VS Code" from Gitpod workspace.

## Describe alternatives you've considered

N/A

## Additional context

I'm not sure if this is related or not, but the remote extensiosns, as well as gitpod extension aren't available in VS Codium.

**Comment by akosyakov** [comment]
We rely on Remote SSH which is not allowed in VS Codium. I don't think it is feasible as for now without building another integration.

cc @loujaybee

**Comment by mahmoudajawad** [comment]
@akosyakov, Just a last thought, can the SSH functionality be built-in in Gitpod extension, then make Gitpod extension available to Codium?

**Comment by akosyakov** [comment]
> Just a last thought, can the SSH functionality be built-in in Gitpod extension, then make Gitpod extension available to Codium?

If VS Codium makes [remote API](https://github.com/microsoft/vscode/issues/128820#issuecomment-881289127) stable and provide a way to provision VS Code server compatible with a version of VS Coduim then yes.
