### ISSUE TITLE
Prebuilds are stuck for a long time

### ISSUE THREAD

**Issue by bigint** [gitpod-io/gitpod#6694]
### Bug description

![image](https://user-images.githubusercontent.com/69431456/141681737-9aa5973c-a1fe-450e-8779-240766f7f534.png)

![image](https://user-images.githubusercontent.com/69431456/141681769-58d7f503-5089-4ec7-96e3-cc4e696ef408.png)

### Steps to reproduce

https://gitpod.io/projects/Devparty/prebuilds

**Comment by AlexTugarev** [comment]
Thanks for reporting!

We are working on a solution for this.

**Comment by AlexTugarev** [comment]
Prebuilds should work again after a faulty node was cordoned.

Happy coding!

**Comment by bigint** [comment]
Hmm let me wait 🤞🏻 

![image](https://user-images.githubusercontent.com/69431456/141754107-2d3bec53-bc98-4c49-a0aa-5da1e4fda84d.png)

**Comment by AlexTugarev** [comment]
@bigint, I'm afraid that's an obsolete `RUNNING` state. Please try to cancel and re-trigger the prebuild. Also, the next update on a branch will trigger a new prebuild 🤞🏻

**Comment by rfay** [comment]
I'm unable to cancel prebuild. Using the UI doesn't do anything. Suggestions?

**Comment by jankeromnes** [comment]
Hi @rfay! If you open the browser console, does it show any relevant error when you try to cancel the prebuild?

Spoilers: If it says "operation not permitted! missing get permission on workspace" we're already working on a fix. If not, it might be a different/new bug.

**Comment by rfay** [comment]
No, it shows nothing. Just shows a momentary circle-wait icon and comes back to the red "Cancel Prebuild" button. No errors shown.

**Comment by rfay** [comment]
Pushing a new commit to the branch sorted this out, but it was definitely ugly.
