### ISSUE TITLE
Update server-ide-configmap in installer

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#6700]
The server-ide-configmap helm template has been changed recently with these PRs:
- #6669
- #6367
- https://github.com/gitpod-io/gitpod/pull/6671

These changes need to be added to the installer as well.

See also:

> We haven't really introduced the installer to the teams yet, but it would probably make sense to update [that part](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/ide-configmap.go) accordingly.

_Originally posted by @csweichel in https://github.com/gitpod-io/gitpod/issues/6669#issuecomment-966986937_

**Comment by roboquat** [comment]
@corneliusludmann: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6700#issuecomment-971382624):

>/schedule
>/assign


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
