### ISSUE TITLE
Features for Admin page

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/gitpod#6705]
Instead of going directly into the database to fix / update queries (_which is error-prone_), we should have actions available from the admin page. Some examples:

- Force stop / Mark as Stopped button when users workspaces are stuck in `stopping` state

See internal discussion [1](https://gitpod.slack.com/archives/C01KGM9AW4W/p1636971012136100?thread_ts=1636968588.135800&cid=C01KGM9AW4W)  and [2](https://gitpod.slack.com/archives/C02EN94AEPL/p1636734314352000?thread_ts=1636728516.348800&cid=C02EN94AEPL)

**Comment by pawlean** [comment]
I'll update this issue with more features that come up, but force stopping workspaces is a very frequent occurrence.

**Comment by loujaybee** [comment]
Pardon my ignorance, as I'm not fully clued up here. 

But I wonder if we can use DB migration scripts for this flow (or re-use existing scripts) for this purpose. 

See [internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1637051082391300?thread_ts=1636985355.375000&cid=C02EN94AEPL). 

That said, force stopping a workspace does seems valid/frequent enough to promote to the admin dashboard 😆

**Comment by jldec** [comment]
Closing this in favor of https://github.com/gitpod-io/gitpod/issues/7597
