### ISSUE TITLE
Allow desktop IDE preferences (e.g. plugins) to be set via the `.gitpod.yml`

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6706]
Currently, the user can set their preferences for which IDE to open a global/user level, this issue/feature request is to track the ability to set IDE preferences via `.gitpod.yml`, e.g. extensions.

Related to: #6602

Related [discussion in Discord](https://discord.com/channels/816244985187008514/908754635999838239/908809451568529408)

Related JetBrains issue: https://youtrack.jetbrains.com/issue/CWM-4987

**Comment by csweichel** [comment]
Which one would take preference? User or .gitpod.yml setting?

**Comment by svenefftinge** [comment]
I don't think the configuration for what IDE I want to use is something that should be configured on the repo (gitpod.yml) but is rather a user preference.

**Comment by gtsiolis** [comment]
> ...  but is rather a user preference.

+1. See also relevant past discussion in https://github.com/gitpod-io/gitpod/issues/4258.

**Comment by titimoby** [comment]
I use Gitpod for the ability to have really various environment.
So when I start a python project, I'm more willing to use PyCharm but if I work on some of my Go or TinyGo project, I will prefer Goland.
And as I also need to work on the main product, I need Kotlin/Java in IntelliJ.

This is especially true if a developer is working at day with IntelliJ but wants to collaborate to Open source project based on another IDE and language

**Comment by gtsiolis** [comment]
Thanks for the feedback, @titimoby! 🧡 

**thought**: Relying on `.gitpod.yml` for selecting the editor sounds interesting but could easily break user experience as editor options can change in the long run, editors can be deprecated, self hosted instances could run earlier versions which don't necessarily support more editors, and more.

**suggestion**: Instead, what we could do is make this a project[[1](https://www.gitpod.io/blog/teams-and-projects)][[2](https://www.gitpod.io/changelog/introducing-teams-&-projects)] setting which would also resolve the issue you describe in https://github.com/gitpod-io/gitpod/issues/6706#issuecomment-970416100 as project settings would always rely on the available options per instance.

**risk**: Things to consider if we make this a project setting include having a fallback when an editor is replaced or removed.

**thought**: If we go down this road, nudging users to enable desktop IDEs or switch to a specific editor like PyCharm could be also interesting.

**Comment by loujaybee** [comment]
**Disclaimer:** This issue was also/mainly about extensions / customisations for the editor. Sorry, I put it together quite hastily, however the above discussion is also quite interesting! 🙏 I was referring mostly to having features/integrations as we do in the current [vscode namespace](https://www.gitpod.io/docs/references/gitpod-yml#vscode) in our YAML and `.gitpod.yml`, and/or [features like opening previews](https://www.gitpod.io/docs/references/gitpod-yml#ports%5Bn%5D.onopen). This also relates to the open issue that we have to support `gitpod` some IDE actions via gitpod CLI where necessary: https://github.com/gitpod-io/gitpod/issues/6506

With regards to: 

> Relying on .gitpod.yml for selecting the editor

It's worth linking to [this Discord poll](https://discord.com/channels/816244985187008514/839379835662368768/907240495145693185) where I was asking for some feedback on how IDE's should be configured e.g per-project etc, including this comment: 

> I want to provide a happy path for users of my workspace/project but also enable them to customize and configure the default workspace to their needs.

Which I think is a nice summary/request, e.g. to have happy-path configurations for IDE's on a per-project basis, but whilst allowing the user to over-ride configurations with their own personal preferences. Discussion about configurations per-project/per-user also relate to roadmap items like having dotfiles for users: https://github.com/gitpod-io/roadmap/issues/21

> Yeah this is true. I'm really looking for a terrible place where on a single repo, developers can use VSCode locally, or remotely, and IntelliJ locally, and remotely. You know, like in a non web based development environment where people pick their favourite IDE 😉 (source: a [similar discussion in Discord](https://discord.com/channels/816244985187008514/908754635999838239/908809451568529408))

**Comment by dragonDScript** [comment]
Personally, I was thinking of something similar to Windows' open with dialog + overridable per project config + per user config.

You could open the workspace with vscode, jetbrains, your config or the project config.

**Comment by 0Grit** [comment]
_Note: This is a rats nets of a concept that I'd personally love to avoid thinking about.
I'm not a pragmatist developer though, I am an early adopter. And this could be important for gitpod to cross reach the majority of the market. At the same time I wonder if it can wait until after you have a foothold in a niche market._


In my opinion the success of VSCode lies in the standards based approach that was taken.
Language server, MS Debug Adapter Protocol, there are probably others I'm unaware of.

Did MS create a standard for IDE configuration? 
Without a standard like that I'd fear for Giptod's ability to maintain various IDE configurations.

My main requirement for a feature like this is that somewhere somehow the "Project settings" which end up being separate from the workspace repository will be version controlled, and exist in human readable format.

I am envisioning a concept where I point gitpod to a git repository which contains my global workspace preferences. And each gitpod project can also point to a git repository containing project specific preferences.
Abstracting this paradigm from the pragmatist user though would require managing the git repositories for them. I think this sounds pretty cool, but I'm not going to put much more thought into it. I don't need it yet.

**Comment by akosyakov** [comment]
I don't think it is feasible and worth doing conceptually. We will need to customize each editor to respect settings from .gitpod.yml which is rather hard task in first place and will require maintenance. I would prefer clean separation of concerns:
- .gitpoy.yml for workspace specific configurations, tasks, ports, and so on
- editor specific configurations via settings files of corresponding editors.

**Comment by loujaybee** [comment]
I think some of these comments also apply to: https://github.com/gitpod-io/gitpod/issues/6602

**Comment by loujaybee** [comment]
Closing, as duplicate with other work https://github.com/gitpod-io/gitpod/pull/9445
