### ISSUE TITLE
Vim extension doesn't work with system clipboard in Safari

### ISSUE THREAD

**Issue by schickling** [gitpod-io/gitpod#6709]
### Bug description

When using the https://github.com/VSCodeVim/Vim extension in Gitpod the following should work but doesn't:

- A) select some text -> copy via y and paste via CMD + V somewhere else
- B) copy some text via CMD + C and paste via p

Note: The above works perfectly in VSC locally.

### Steps to reproduce

See above

### Anything else?

Related Discord chat: https://discord.com/channels/816244985187008514/816246578594840586/909795486951686145

**Comment by jeanp413** [comment]
@schickling Have you tried using this in your settings `"vim.useSystemClipboard": true`?

**Comment by schickling** [comment]
@jeanp413 yes but I had to disable it since when using it even yanking and pasting within the VIM mode didn't work anymore - so it only made things worse.

**Comment by jeanp413** [comment]
mmm I'm using `"vim.useSystemClipboard": true` and it works fine for me, did you enabled clipboard access in your browser?
In chrome, a popup should appear asking for clipboard access.

**Comment by akosyakov** [comment]
@schickling Could you share which browser do you use?

**Comment by schickling** [comment]
Update: Seems like this is a Safari limitation. Using `"vim.useSystemClipboard": true` in Chrome works but doesn't work in Safari in Big Sur. That's a bummer since Safari is my primary browser.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1567498/141959504-f750978a-81e7-4ed5-8c02-59ab47bf927a.png">
