### ISSUE TITLE
Gitpod VSC loading screen should respect my dark theme setting

### ISSUE THREAD

**Issue by schickling** [gitpod-io/gitpod#6710]
The Gitpod loading screen (before VSC is loaded) should respect my dark theme setting.

https://user-images.githubusercontent.com/1567498/141802524-f87b3199-09b2-4cc6-9263-da9300da1879.mp4

**Comment by schickling** [comment]
![](https://media0.giphy.com/media/lqVVqkqMolh9S/giphy.gif?cid=ecf05e476b4cs2ixhb7wbxnkyn9hcdisgu0s7iig7digvl69&rid=giphy.gif&ct=g)

**Comment by gtsiolis** [comment]
Thanks for noticing @schickling! Could not agree more. I also noticed this earlier last week but could not reliably reproduce. Looping in @jankeromnes in case they have any insights on why this is happening. ❓ 

FYI, we've recently added system theme support for the editor, see https://github.com/gitpod-io/gitpod/issues/6403 and we're also considering changing dashboard default theme to system for new users, see #6395. 🗺️

**Comment by pawlean** [comment]
Honestly, this issue should be prioritised alone after the use of that GIF. Thanks for the laugh @schickling!

**Comment by jankeromnes** [comment]
Agree, thanks for this issue!

I'm just confused as to why "Checking" is in Dark theme while "Creating" is in Light theme 🤔

@schickling Which dashboard "Theme" do you currently have selected in https://gitpod.io/preferences ? (This is what controls the color of non-workspace Gitpod pages, and as @gtsiolis mentioned it's currently Light by default, but should instead be System by default -- will fix this soon)

**Comment by schickling** [comment]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1567498/141816979-fc724e9e-2c20-4a7f-b2bc-f826ca92a32a.png">

**Comment by gtsiolis** [comment]
@jankeromnes is this also resolved with https://github.com/gitpod-io/gitpod/pull/6747? Cc @AlexTugarev

**Comment by jankeromnes** [comment]
Probably yes, but if both dashboard and OS preference were already dark, and the loading screen still flashed white, I suspect there could also be a different bug hidden here.

Maybe safer to wait a bit and see if this issue still reproduces now that #6747 got merged and deployed?

**Comment by gtsiolis** [comment]
Closing this as seems to be resolved with the deployed changes in https://github.com/gitpod-io/gitpod/pull/6747.
