### ISSUE TITLE
Unable to auth when using Gitpod Local Companion

### ISSUE THREAD

**Issue by akoenig** [gitpod-io/gitpod#6712]
### Bug description

Hello everybody 🙂,

first of all, sorry for crossposting, but I think it is more a bug than a general question (I asked in https://community.gitpod.io/t/gitpod-local-companion-oauth2-failure/5604).

During the process of migrating our projects to Gitpod we encountered a project where we need the tunneling capabilities of the Gitpod Local Companion. Unfortunately, right now, when trying to start the local companion, the OAuth2 flow fails with the following message:

```json
{
  "status": 400,
  "message": "The requested scope is invalid, unknown, or malformed: Check the `resource:workspace::*::get, resource:workspaceInstance::*::get` scope(s)",
  "stack": "t: The requested scope is invalid, unknown, or malformed: Check the `resource:workspace::*::get, resource:workspaceInstance::*::get` scope(s)\n    at Function.t.invalidScope (/app/node_modules/@jmondi/oauth2-server/dist/oauth2-server.cjs.production.min.js:1:10180)\n    at t.<anonymous> (/app/node_modules/@jmondi/oauth2-server/dist/oauth2-server.cjs.production.min.js:1:16367)\n    at u (/app/node_modules/@jmondi/oauth2-server/dist/oauth2-server.cjs.production.min.js:1:3282)\n    at Generator._invoke (/app/node_modules/@jmondi/oauth2-server/dist/oauth2-server.cjs.production.min.js:1:3035)\n    at Generator.next (/app/node_modules/@jmondi/oauth2-server/dist/oauth2-server.cjs.production.min.js:1:3641)\n    at s (/app/node_modules/@jmondi/oauth2-server/dist/oauth2-server.cjs.production.min.js:1:302)\n    at a (/app/node_modules/@jmondi/oauth2-server/dist/oauth2-server.cjs.production.min.js:1:505)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}

```

### Steps to reproduce

`./gitpod-local-companion-linux --mock-keyring`

### Expected behavior

The OAuth2 flow should be successful.

**Comment by akosyakov** [comment]
Could you run `./gitpod-local-companion-linux --version`? Maybe it is outdated.

**Comment by akoenig** [comment]
@akosyakov Thanks for your response. We tested with a fresh install:

```
gitpod-local-companion version main.1254
```

**Comment by akosyakov** [comment]
It looks outdated, my returns `main.1817`.

Could you delete and download a new one: https://www.gitpod.io/blog/local-app#installation

Could it be also that you changed Gitpod account? There is a following bug: https://github.com/gitpod-io/gitpod/issues/6452

**Comment by akoenig** [comment]
Ahh, that was my fault. Thanks for the heads up, @akosyakov. I followed the link from the initial blog post and downloaded it from there.
