### ISSUE TITLE
can not access bundle.js in China

### ISSUE THREAD

**Issue by ginhton** [gitpod-io/gitpod#672]
When I opened a project, it stucked in the loading page.

I checked the chromium dev panel, found that the `bundle.js` is not loaded. (I am in **China**)

Here is the link: https://cdn.gitpod.io/theia/d6bb72857cb6b599c90e4e9b12d790e2/bundle.js

Can I redirect this link to another cdn or something like that?

Or if there are some other way to solve this problem.

Every suggestion will be appreciated!

Thank all genius guys here!

**Comment by 32leaves** [comment]
Hi @ginhton ,

we have investigated that issue in the past. Unfortunately it's somewhat intractable as the CDN seems to work for some users in China, and not for others. We have been unable to find a solution as of now that would work reliably on mainland China and integrate with our infrastructure.

Would you be able to recommend a CDN's which provides reliable service in China?

**Comment by ginhton** [comment]
Thank you for your reply!

To the best of my knowledge, aliyun CDN is well known in China, and is accessable in every part of China, but is not free.
here are some link:
[aliyun CDN documentation](https://help.aliyun.com/product/27099.html)
[aliyun CDN main page](https://www.aliyun.com/product/cdn)

Another thing, I am in LiaoNing province, and I can access [cdnjs](https://cdnjs.com/) and its contents. Maybe you can just put `bundle.js` to that. And I don't know if it is acceessable in other province.

I am very appreciated about what you guys are doing! Thank you for all of your hard work and passion!
Have a good day!

**Comment by ginhton** [comment]
Can I download `bundle.js` and offer it in my server or somewhere else? Does it works?

**Comment by sr229** [comment]
@ginhton `bundle.js` is referenced only at build time, so I don't think that works.

I say we need to investigate further on what Gitpod can do so it cn be brought to Chinese audience.

**Comment by ginhton** [comment]
Thank you for reply! @sr229

**Comment by WUID** [comment]
科学上网好像能解决这个问题（我是广东的）

**Comment by 32leaves** [comment]
> To the best of my knowledge, aliyun CDN is well known in China, and is accessable in every part of China, but is not free.

@ginhton Thank  you for the links - we'll check if we can integrate that CDN  (i.e. how  much effort that would be).

Does the DNS name resolution of gitpod.io work for you?

**Comment by ginhton** [comment]
@32leaves The DNS resolution works for me or for my school in DaLian.

Here is something intesting and maybe helpful. 
[link of https gitpod domain](http://tool.chinaz.com/speedtest/https://www.gitpod.io/)
[link of http gitpod domain](http://tool.chinaz.com/speedtest/www.gitpod.io/)
This web tool calculate the response time from each part of China. 

Thank for your hard work!

**Comment by ginhton** [comment]
Another thing, if it is really accessible in most part of China.
It will be a HUGE BURDEN and RISK for Gitpod, I think.
Maybe you should prepare for that.

**Comment by sr229** [comment]
I don't think it would be a huge risk especially if we're only making a cloud IDE service accessible to China. Checking Gitpod's legal obligations there, I think its in line along with the Cloud IDEs natively hosted in China as well.

**Comment by WUID** [comment]
Someone may use gitpod to bypass GFW, but the government of China doesn't allow that.

**Comment by WUID** [comment]
It's a pity it doesn't work for me without proxy.
And I'm in Guangdong Province.
![img](https://i.loli.net/2019/08/02/5d43b4472ce9879735.png)

**Comment by AlexTugarev** [comment]
Theia is no longer used. Closing as obsolete.
