### ISSUE TITLE
Project Configuration: No indication when or where config file was saved

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6724]
Users have a hard time forming a picture of what is happening to the config shown in the Project Configuration page. It would be really helpful to have a indication which tells users what the state is.  Suggestions below:

- Suggested configuration, will be saved in Gitpod and included as uncommitted file in workspace.
- Saved in Gitpod, suggest committing to repository.
- Saved in repository.

**Comment by jldec** [comment]
Related to #5522

**Comment by jldec** [comment]
See also [#slack](https://gitpod.slack.com/archives/C01KPEPNBD0/p1634748754181500) (internal)

**Comment by jldec** [comment]
/schedule
/assign @AlexTugarev 

Given that you are working on #5785 
This would leave only 2 states to worry about to explain with a message to the user

1. The configuration above will be used for the first prebuild or other start tasks, and included as an uncommited file in the workspace. Committing the file to your repository will allow Gitpod to use it for future workspaces.

2. This repository has a .gitpod.yml configuration file. (edited)

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6724#issuecomment-977774979):

>/schedule
>/assign @AlexTugarev 
>
>Given that you are working on #5785 
>This would leave only 2 states to worry about to explain with a message to the user
>
>1. The configuration above will be used for the first prebuild or other start tasks, and included as an uncommited file in the workspace. Committing the file to your repository will allow Gitpod to use it for future workspaces.
>
>2. This repository has a .gitpod.yml configuration file. (edited) 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by AlexTugarev** [comment]
@jldec, I think this can be closed now, right? It's no longer relevant, if we remove the config page.

**Comment by jldec** [comment]
Let's keep it to help those users who use the config page from the project dashboard.

**Comment by jankeromnes** [comment]
I think we can close this page, as the Project Configuration page has been moved out of the onboarding flow, and will soon be removed entirely, because the Project Configuration feature itself is now deprecated in favour of the auto-generated `.gitpod.yml` that is now added to every unconfigured workspace.
