### ISSUE TITLE
Remove outdated subscription plans from Chargebee

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/gitpod#6725]
There are 4 outed subscription plans with no active users on Chargebee [[1](https://gitpod.chargebee.com/plans)]
- Standard (USD) [accidentally renamed to Basic]
- Standard (EUR) [accidentally renamed to Basic]
- Standard Team (USD)
- Standard  Team (USD) 

**Action items**

- [ ] delete supcriptions in Chargebee

- [ ] remove it from/deprecate it in the code

Previous discussions [[1](https://gitpod.slack.com/archives/C01KPEPNBD0/p1637054498116800?thread_ts=1637047866.116000&cid=C01KPEPNBD0)]

**Comment by JanKoehnlein** [comment]
We're swamped. Added to backlog
