### ISSUE TITLE
[jetbrains] Track new JetBrains IDE version

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#6726]
Add a cron job that tracks (and prepares PRs) when new versions of the JetBrains IDEs are published.

**Proposal:** Crawl the following pages:
- https://www.jetbrains.com/idea/nextversion/
- https://www.jetbrains.com/go/nextversion/

**Comment by akosyakov** [comment]
Sounds like we can have [Early Access](https://www.jetbrains.com/resources/eap/) for each JetBrains IDEs as well and probably bring them automatically similarly to VS Code Insiders.

For stable releases it seems JetBrains releases 3-4 times a year.
