### ISSUE TITLE
Can't open any workspace on drud/ddev" "Cannot initialize workspace; exit status 1"

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#6729]
### Bug description

github.com/drud/ddev: Can't open any workspace (PR, master, branch, fork, etc)

It just starts out and then says "cannot initialize workspace: cannot initialize workspace; exit status 1"

<img width="879" alt="Gitpod_integration_for_website_projects" src="https://user-images.githubusercontent.com/112444/142007093-0cf7915b-0001-478b-82bf-700162b3c447.png">

I've been using this project with gitpod for some time, the last commit that affected .gitpod.yaml or the custom image was Oct 30.

### Steps to reproduce

Try to open a gitpod workspace on https://github.com/drud/ddev

### Workspace affected

https://orange-newt-lj0jscr8.ws-us18.gitpod.io/

### Expected behavior

It should be able to start

### Example repository

https://github.com/drud/ddev

**Comment by pawlean** [comment]
Thanks for reporting! We're on it. :) Thanks for your patience! Related [here](https://community.gitpod.io/t/cannot-initialize-workspace-again/5616).

**Comment by rfay** [comment]
Could you please add monitoring to your system so you don't have to find things like this out from people like us? That seems like a hugely important task!
