### ISSUE TITLE
Explain error status better and alert Gitpod of a bigger problem

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#6730]
## Is your feature request related to a problem? Please describe

This morning, repos stopped opening in Gitpod.
![image](https://user-images.githubusercontent.com/22901/142006532-cd93928e-e32a-4695-a329-8f58e4e95251.png)

The error message is very vague.
At first, I thought it's something I've done wrong in my last prebuild, only then I realized it happens in every repo (but affecting only US cluster, and not EU cluster)

I went on Discord and post a message in 'Support' channel, but it didn't get any response, half an hour later I pinged @Gitpodders, which got more attention and the response of "cannot reproduce". A community member suggested it might be a problem in US cluster, that doesn't affect EU cluster.

## Describe the behaviour you'd like

I wish error messages would offer much more details (even if at first it is displayed in a concise way, and a dropdown reveal a detailed message), perhaps something that can be copy/paste to support.

I wish there was a button that led to support on the error page itself, and a button that led to support on https://www.gitpodstatus.com/

I wish Gitpod would have internal processes to know in real time about failures in the system, and would alert people in advance (Discord/Twitter message?) that there's an issue that is being worked on.

**Comment by pawlean** [comment]
Thanks for this feedback! I totally agree and hear you. I'm OOO right now, but I was thinking maybe a Twitter integration on Discord for our @gitpodstatus account as a starting point. I've also briefly looking at Statuspage Discord bots, but let me investigate this a bit more!

**Comment by shaal** [comment]
Can we please add `meta: never-stale` to this issue?

**Comment by geropl** [comment]
@jldec It feels this does not fit into a single issue. IMO we could lift this into an epic, and try to fit this into the company wide "better explain workspace states to user" theme that we heard about this week - this also requires some work from workspace. And maybe have that on the roadmap for Q2.

**Comment by jldec** [comment]
Thanks all - the feedback is 100% valid
But I'm going to close this now for lack of specificity.
We will try to address feedback on specific errors after we ship https://github.com/gitpod-io/gitpod/issues/7925
