### ISSUE TITLE
[ws-daemon] proc mount leaks masking tmpfs mounts

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6732]
### Bug description

When we produce a proc mount in ws-daemon, we mask the mount prior to moving it in place. It would seem that the `move_mount` operation leaves the masks dangling in the "proc mount staging". 

This is most likely because of [`OPEN_TREE_CLONE` flag](https://github.com/gitpod-io/gitpod/blob/a30a1bff483b02df67e01791b44dfb5bf025d344/components/ws-daemon/pkg/iws/iws.go#L578). We need `OPEN_TREE_CLONE ` so that we can use `AT_RECURSIVE`. We need `AT_RECURSIVE` to move the mask mounts as well.

When we have too many of those dangling mask mounts, at some point we fail to mount more and proc mounts start to fail. This affects content init and workspace startup.

### Steps to reproduce

Start a workspace.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6732#issuecomment-972778161):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
