### ISSUE TITLE
Add additional monitoring alert to capture /proc mount out of disk space

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6734]
### Bug description

As part of [the incident today](https://app.incident.io/incidents/68), discovered that there were errors on the node discovered. These errors didn't trigger a PagerDuty alert and required a manual incident to be created.

Log in question

```
{"level":"error","msg":"container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting \"proc\" to rootfs at \"/proc\" caused: mount through procfd: no space left on device","time":"2021-11-16T15:16:03Z"}
```

### Steps to reproduce

Not really reproducable now. Issue likely to be fixed by #6732

**Comment by csweichel** [comment]
We should rather fix the issue (see https://github.com/gitpod-io/gitpod/issues/6732)

**Comment by MrSimonEmms** [comment]
Should there not also be additional monitoring as we've now had two incidents this week that haven't been automatically alerted?
