### ISSUE TITLE
Please update/refresh gitpod/workspace-full (old homebrew version)

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#6736]
### Bug description

gitpod/workspace-full is getting really old, needs a refresh.

The homebrew in there is 3.2.14, but homebrew is now at 3.3.4. More than that, in the meantime they've changed from using linuxbrew-core to homebrew-core, which means that any attempt to update (and get current recipes) takes forever. And of course, since gitpod aims at "disposable workspaces", this means you have to do it every time (or take a long time building your own image).

Anyway, please update gitpod/workspace-full and especially get it updated with homebrew.

It would probably be good to have this automated every week or something?

Thanks!

### Steps to reproduce

Start a workspace, `brew --version`

### Workspace affected

All

### Expected behavior

The homebrew version should not be months old.

### Anything else?

Likely related to https://github.com/gitpod-io/gitpod/issues/5251

**Comment by shaal** [comment]
Yes please!

**Comment by ghuntley** [comment]
Baking and deploying now. New workspaces created in a couple hours (depending how long the pipeline takes) will use the latest version.

**Comment by rfay** [comment]
Thanks!

**Comment by rfay** [comment]
Confirmed updated, thanks! 

Can this be automated to it happens regularly?

**Comment by mickmister** [comment]
+1 for @rfay's request for this to automate this!
