### ISSUE TITLE
Support: Lost control of team for rfay/ddev

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#6738]
### Bug description

I use both github.com/drud/ddev and the fork github.com/rfay/ddev. 

However, I can't manage prebuilds for rfay/ddev, and can't create/add a team for that.  The flyover says "Taken"

<img width="681" alt="Projects_—_Gitpod" src="https://user-images.githubusercontent.com/112444/142064307-d34bd4ec-2a2b-4ecd-b386-ab9fbab1c648.png">

I wouldn't be surprised if this was a result of me having previously had a separate (confusing?) "team" that was owning rfay/ddev. And it was named "junk". And I tried to get rid of it. Maybe I succeeded. I don't completely understand "team" yet, but I sure understand managing prebuilds, and I'd like to be able to manage rfay/ddev prebuilds. Would appreciate if you could get me fixed on this.  Thanks!

### Steps to reproduce

You aren't me, but You could visit "Projects" and "New project", and try to manage rfay/ddev

### Expected behavior

Should be able to manage prebuilds for my own repo

**Comment by roboquat** [comment]
@jankeromnes: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6738#issuecomment-971467674):

>/schedule
>
>/assign


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jldec** [comment]
Possibly related to https://github.com/gitpod-io/gitpod/issues/6655

**Comment by jankeromnes** [comment]
Hi @rfay!

Thanks for reporting this problem and providing helpful details.

Teams & Projects are still somewhat new features in Gitpod, and we're still iterating on making them more intuitive.

I can confirm that the Project linked to https://github.com/rfay/ddev still lives under the team called "junk", which has currently 0 members (that's it's even possible to get into this situation is a bug on our side: https://github.com/gitpod-io/gitpod/issues/6311)

I see two potential fixes here:

- If you're the only person who works on https://github.com/rfay/ddev and manages prebuilds, I can move the "stranded" project over to your user account

- If there are multiple people working on https://github.com/rfay/ddev and that should be able to manage its prebuilds, then I could add you back to the team called "junk", and you'll be able to invite more people to this team

Or, I could also delete the existing Teams and Projects, and let you create a new Project as you see fit.

**Comment by rfay** [comment]
Thanks for the quick response. 

I am the only person who works on rfay/ddev. Please just move rfay/ddev over to my user account and kill off the junk team.

**Comment by jankeromnes** [comment]
> I am the only person who works on rfay/ddev. Please just move rfay/ddev over to my user account and kill off the junk team.

@rfay Done. Please confirm that you now see the rfay/ddev project in https://gitpod.io/projects and can access it again 🙏

**Comment by rfay** [comment]
Perfect, thanks so much!
