### ISSUE TITLE
[payment endpoint] Have sanity check and error on large seats numbers instead of OOM

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6746]

**Comment by roboquat** [comment]
@geropl: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6746#issuecomment-972821394):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
