### ISSUE TITLE
Failed to delete a workspace

### ISSUE THREAD

**Issue by waleedhammam** [gitpod-io/gitpod#6749]
### Bug description

Failing to delete workspace
![Screenshot from 2021-11-17 17-19-27](https://user-images.githubusercontent.com/10658229/142228346-f4c1515d-c8f5-4462-895d-0583d348b902.png)

### Steps to reproduce

- Create new workspace
- Try to delete it

### Workspace affected

 turquoise-marsupial-bb9bsba9

### Expected behavior

workspace is deleted when i click delete

**Comment by atduarte** [comment]
Same happened to me while a workspace was building an image.
