### ISSUE TITLE
Show Git stats for each workspace on the dashboard

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#675]
Brought up [krainboltgreene](https://twitter.com/krainboltgreene) by [here](https://twitter.com/krainboltgreene/status/1150582201412534272).

> @gitpod While I'm begging, can we get any git diff stats on the dashboard? I don't feel comfortable trashing a workstation because I can't know if it's committed+pushed

This would allow users to be more confident whether all content is pushed before deleting them.

**Comment by 32leaves** [comment]
dup of #676
