### ISSUE TITLE
websocket not working on gitpod

### ISSUE THREAD

**Issue by trusktr** [gitpod-io/gitpod#6761]
### Bug description

![unknown](https://user-images.githubusercontent.com/297678/142280068-21795041-d7c4-41c4-ba82-c4b83e3851da.png)

```
WebSocket connection to 'ws://localhost:63100/localapp.LocalApp/TunnelStatus' failed: 
```

### Steps to reproduce

https://gitpod.io/#https://github.com/trusktr/solid-lume-starter/commit/35c342675ca82244027be2f309edea615ba4c051

```
npm install
npm run dev
```

then see the error in the console. Edit any file and expect hot module reload to update the app. It seems to do a full page refresh once in a while due to the missing websocket connection.

### Workspace affected

amethyst-tortoise-jsvtclkh

### Expected behavior

No websocket error

### Example repository

See repo commit linked in the example.

**Comment by akosyakov** [comment]
> WebSocket connection to 'ws://localhost:63100/localapp.LocalApp/TunnelStatus' failed: 

This one is expected if you don't have the local companion running.

**Comment by akosyakov** [comment]
I could not reproduce it:
<img width="1904" alt="Screenshot 2021-11-22 at 09 27 07" src="https://user-images.githubusercontent.com/3082655/142827726-3a8cfbb5-1184-4c10-9f74-e25e042810b3.png">

**Comment by abngal** [comment]
I'm trying to run a websocket server inside gitpod and what I'm getting the same SSL error.
Used wscat inside gitpod terminal: `npm i -g wscat`

> gitpod /workspace/solid-lume-starter $ wscat -c "wss://localhost:24678"

>> error: write EPROTO 140632130508736:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

External ws server looks ok

> gitpod /workspace/solid-lume-starter $ wscat -c "wss://ws.ifelse.io"

>> Connected (press CTRL+C to quit)
< Request served by 125363a3

**Comment by akosyakov** [comment]
> Replicated the bug description, websocket request is stuck on initializing and page reloads on error after about 20seconds.

Could you provide exact steps please? 🙏

**Comment by abngal** [comment]
My bad, sorry it seems wss port is correctly done/forwarded by gitpod.
I have created a [simple websocket server](https://www.js-tutorials.com/nodejs-tutorial/simple-websocket-example-with-nodejs/) and I can access it from outside gitpod.
I have to use `wss://` though, using `ws://SERVER` resulted on my error above.
This works:

> wscat -c "wss://8080-WORKSPACE.gitpod.io"
Connected (press CTRL+C to quit)
< Hello! Message From Server!!

I think his error is partially on the port that was added at the end :
> wss://3000-WORKSPACE.gitpod.io:24678
I think it should be 
> wss://24678-WORKSPACE.gitpod.io

When I run `npm install & npm run dev` on OP's gitpod link, locally, the following is successful:
> wscat -c "ws://localhost:24678"
Connected (press CTRL+C to quit)
< {"type":"connected"}

I think it means his local on gitpod is ok but when I try to access it from outside I get a response but a 401:
> wscat -c "wss://24678-moccasin-bee-5m05y6co.ws-us17.gitpod.io"
error: Unexpected server response: 401

I also added the port below at .gitpod.yml, but I still get the error 401: 
>ports:
>  - port: 24678
>   visibility: public

I'm guessing the error is unique to his server setup.

**Comment by akosyakov** [comment]
@abngal Good call! I only now see it.

@trusktr URL does not look correct, Gitpod supports only 2 ports: 8080 and 443. All other ports are emulated via prefixing. On your image port is `:24678`. You should drop it and then it will work.

**Comment by neu-ma-tic** [comment]
Hey, now I'm experiencing this issue a little bit late to the party, but I've found a solution that works for me

With ssh, you can make a "poor man's" tcp tunnel, so that stuff is accessible on your local network

Just add:
```bash
tunnel() {
     ssh -L 0.0.0.0:$1:localhost:$1 "$2"
}
```
to your [$SHELL]rc file, then run

```bash
# tunnel <port> <user@host>
tunnel 8080 "xxxxxxxx@xxxxx.ssh.ws-usXX.gitpod.io"
```

then navigate to that port on your local machine
