### ISSUE TITLE
[Installer]: improve distrubtion of gitpod-installer binaries

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6766]
> Suggestions welcome - we want to hear from the community as to what works for you
> Gitpodders - [an RFC](https://www.notion.so/gitpod/RFC-Installer-release-cadence-and-distribution-7dafa7dc28e942efa9a70ae104cef816) has been created for this

## Is your feature request related to a problem? Please describe

As the future of Gitpod self-hosted, the Installer must be easily accessible. Currently, users need to search through werft for a build, pull the Docker image and run inside that.

## Describe the behaviour you'd like

A regular release cadence, appropriately numbered and released as GitHub packages.

## Additional context

Ensure that there are binaries for multiple different platforms. As a first pass, we should include:
 - linux-amd64
 - linux-armhf
 - linux-arm64
 - MacOS
 - Win64
 - Win32

**Comment by metcalfc** [comment]
Its possible that the rate of installers is going to be frustrating without an auto update function. Should we consider imagining more of a stream than point releases?

```
gitpod-installer render --file foo.yaml --channel unstable   # nightlies
gitpod-installer render --file foo.yaml --channel beta       # nightly that is promoted to burn in testing
gitpod-installer render --file foo.yaml --channel stable     # current stable release
gitpod-installer render --file foo.yaml --version 1864       # specific release for testing or reproduction
```

**Comment by MrSimonEmms** [comment]
@metcalfc possibly. We consciously decided against that so we could bake in the image tags into the binary so we could make the release management "here's the binary - install Gitpod and we guarantee it'll work". The other advantage of that is that we can lock down the config API versions.

I guess there's the possibility that it was the wrong decision, but it was actually a thought-out decision rather than "let's start building and we've painted ourselves into a corner"

**Comment by MrSimonEmms** [comment]
I think what we have with KOTS have fulfilled this ticket
