### ISSUE TITLE
Authentication is broken. I cannot push to my fork.

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#677]
- Fork a GH repo.
 - Open the fork in Gtipod.
 - Try to sync your branch by pushing your local branch to the origin.
 - It fails.

```
gitpod /workspace/theia-backend $ git remote -v
origin  https://github.com/kittaakos/theia-backend.git (fetch)
origin  https://github.com/kittaakos/theia-backend.git (push)
upstream        https://github.com/wonjooncho/theia-backend.git (fetch)
upstream        https://github.com/wonjooncho/theia-backend.git (push)
```

![Screen Shot 2019-07-16 at 11 09 40](https://user-images.githubusercontent.com/1405703/61281749-73332c80-a7ba-11e9-8f98-14a2855703ae.jpg)

![screencast 2019-07-16 11-12-39](https://user-images.githubusercontent.com/1405703/61281967-d1f8a600-a7ba-11e9-879e-a1a9cdfe692e.gif)

**Comment by kittaakos** [comment]
As a workaround, I could unset the credential helper, and do it manually.

```
git config --global --unset credential.helper
```

**Comment by davelavoie** [comment]
I had the same issue, your workaround helped me to unset the credentials, thanks!

**Comment by kittaakos** [comment]
@davelavoie, it should work if you click on the `Grant Permissions`. See [this thread](https://github.com/gitpod-io/gitpod/issues/685#issuecomment-513122396).

**Comment by AlexTugarev** [comment]
`Gran Permissions` is the way how to grant write permissions. Allowing Gitpod to push on your behalf.
