### ISSUE TITLE
Make content initialisation failures more explicit

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6771]
## Is your feature request related to a problem? Please describe
When a workspace fails due to content initialisation issues, users only see something like this:
![image](https://user-images.githubusercontent.com/3210701/142411413-ebe71463-f8e5-4ef4-a0c8-0cf976e31fa0.png)

That's not a particularly helpful error message.

## Describe the behaviour you'd like
Users should receive an actionable and informative message, based on which they can decide on a further course of action.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6771#issuecomment-977810196):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
