### ISSUE TITLE
[Installer]: Cannot use S3 object storage in DigitalOcean

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6776]
> See [example](https://gist.github.com/MrSimonEmms/a770d6e36e3fdf8222b54626f2ae9d7d) to demonstrate the problem

DigitalOcean provides "Spaces", which is their version of S3-compatible storage. Despite having an identical API to S3, this works slightly differently to AWS S3 due to how the regions and endpoints are configured - the `endpoint` is "<regions>.digitaloceanspaces.com" - examples use `ams3`, but is the same for all regions. This is different AWS S3 which use a common `s3.amazonaws.com` and then sets the region separately.

# Attempt 1 - remove region from the URL

`endpoint := "digitaloceanspaces.com"`

This results in `XML syntax error on line 2: invalid character entity & (no semicolon)`. Likely because nothing exists on this URL

# Attempt 2 - setting region in URL and MakeBucket `Region`

The `MakeBucket` call cannot calculate the SHA256 header correctly, resulting in `The provided 'x-amz-content-sha256' header does not match what was computed`. Likely this is because DigitalOcean don't calculate the region as part of the header on their side because you cannot create, for example, an `fra1` resource on the URL `ams3`

# What works - setting region URL but not MakeBucket

If you remove the `Region` from the `MakeBucket` options, this works fine.

However, every part of Gitpod (the Installer, the ContentService etc) expects the `Region` to be set.

---

We get the same problem using Minio Gateway

# Suggested solutions

1. make `Region` an optional parameter. Theoretically, this would work, but it may have unintended consequences elsewhere especially for non-DO S3 configuration
2. don't support DigitalOcean Spaces - this would limit our self-hosted options. Furthermore, it may also be an issue with other non-AWS S3-compatible providers.

In additional to these, we could ask DigitalOcean for help and see if there's anything they can suggest.

---

# Workaround for today

Use Minio in-cluster

**Comment by lucasvaltl** [comment]
Unlikely to be done soon - please raise this again if you require Digital Ocean as a storage provider
