### ISSUE TITLE
Disable /#prebuild/ prefix

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6779]
The easiest way to deal with #6688 appears to be to disable the `/#prebuild/` prefix.

Suggested wording

> The /#prebuild/ prefix has been disabled. Please use a Project in the Dashboard to trigger a prebuild manually.

![Screenshot 2021-11-18 at 14 41 35](https://user-images.githubusercontent.com/849592/142436716-c580d871-2286-4f0e-920b-c59494ebb0da.png)
 
See #6688 and #6688

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6779#issuecomment-972933264):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jldec** [comment]
/unschedule
/unassign @jankeromnes 

Based on discussion in https://github.com/gitpod-io/gitpod/issues/6688#issuecomment-973863958 this is not doable without providing an alternative to trigger prebuilds for Bitbucket and self-hosted users first. 

Thanks @shaal for pointing out.

**Comment by jankeromnes** [comment]
Now that https://github.com/gitpod-io/gitpod/issues/4353 has been renamed, closing this one as duplicate.
