### ISSUE TITLE
CLI support for diff viewer

### ISSUE THREAD

**Issue by davemecha** [gitpod-io/gitpod#678]
**As a User 
I want to open the gitpod diff viewer via CLI 
to browse the output of `git diff` from the command line.**

I'd suggest to add this support to the `gp open` command and to make the command "pipeable".

### Preferred usage options:

From CLI

```
$ git diff HEAD~ HEAD | gp open
$ gp open my.diff
$ gp open my.patch
```

From UI

By opening a `diff` or `patch` file from the gitpod file browser.

**Comment by geropl** [comment]
@32leaves also had the idea to use Theia as git diff editor (as opposed to vim, the current config) via `gp`, maybe that can be integrated with this proposal.

**Comment by 32leaves** [comment]
I like the idea. It's slightly different than making it a drop-in replacement for say vim. 

If I understand this proposal correctly, you'd like to be able to pipe to `gp open` and show the content in an editor, similar to how you'd use `cat`, no?

**Comment by svenefftinge** [comment]
We should use the same arg used by vs code's cli (as we have an alias for it already).
```
-d --diff <file> <file>           Compare two files with each other.
```

**Comment by akosyakov** [comment]
resolved by https://github.com/gitpod-io/gitpod/pull/2577 I doubt we will do it for Theia cc @svenefftinge @csweichel ?
