### ISSUE TITLE
[jetbrains] Remove werft secret

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#6787]
We used to store the download links for the Jetbrains images in a secret for werft. Since they are publicly available now, we can remove the werft secret from the build process.

**Comment by roboquat** [comment]
@corneliusludmann: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6787#issuecomment-973118280):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
