### ISSUE TITLE
[self hosted] Update the "Kubernetes" guide for the installer / single host path

### ISSUE THREAD

**Issue by metcalfc** [gitpod-io/gitpod#6791]
- [ ] Document required default storage class (related #6789)
- [ ] Automate external IP for the proxy service since there is no load balancer / cloud
- [ ] Update docs on gitpod.io (https://www.gitpod.io/docs/self-hosted/latest/installation/on-kubernetes)
- [ ] Publish VMware base VM/vagrant with Ubuntu and base requirements
- [ ] Publish script with installer customization

**Comment by lucasvaltl** [comment]
Given the updates to our documentation, we think this is now out of date.
