### ISSUE TITLE
[oauth] Allow hosts on non standard ports

### ISSUE THREAD

**Issue by metcalfc** [gitpod-io/gitpod#6793]
GitLab happily runs on ports other than 443. Allow the hostname to use other ports.

![image](https://user-images.githubusercontent.com/31925/142521234-ad59c332-89ad-4eae-b19e-44a8b2568801.png)

**Comment by gtsiolis** [comment]
Nice catch, @metcalfc! Possibly a duplicate of https://github.com/gitpod-io/gitpod/issues/5305?

**Comment by metcalfc** [comment]
@gtsiolis Seems like it. I'll have more info tomorrow.

**Comment by gtsiolis** [comment]
Closing this as duplicate of https://github.com/gitpod-io/gitpod/issues/5305. @metcalfc Feel free to re-open if this describes a different issue or feature request.
