### ISSUE TITLE
Unable to save gitpod workspace

### ISSUE THREAD

**Issue by Tawnygoody** [gitpod-io/gitpod#6798]
### Bug description

I am unable to save any changes made in my gitpod workspace. This has been a re-occuring issue this week. I can open the workspace but as soon as i try to save any changes then the blue clock on the explorer tab appears as if its trying to load something. 

### Steps to reproduce

I've cleared the cache and history in my browser and re-opened the workspace - same issue. 

### Workspace affected

https://amaranth-cow-2v4vsfat.ws-eu18.gitpod.io/

### Example repository

<img width="1440" alt="Screenshot 2021-11-18 at 08 48 06" src="https://user-images.githubusercontent.com/75432196/142594323-6877cb97-bc9f-4344-8f6a-a8bf0f81d786.png">

**Comment by Tawnygoody** [comment]
It appears that this is only a problem when trying to make changes to the TESTING.md file

**Comment by akosyakov** [comment]
Could you share the repo please?

**Comment by loujaybee** [comment]
Moving "to investigate" removing from groundwork until we have further replication steps.
