### ISSUE TITLE
issue with connecting

### ISSUE THREAD

**Issue by WhitneyE** [gitpod-io/gitpod#680]
Sorry, something went wrong 😓
Authorization with GitHub failed. Please try again.
Please file an issue if you think this is a bug.

this is after we've authorized

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by jankeromnes** [comment]
Hi @WhitneyE, thanks for reporting this bug, and sorry that it happened to you.

Occasionally, GitHub's API rejects our authentication calls, but it's almost always a temporary issue on GitHub's side.

If you try again, hopefully it should work fine. But please report back if you see this problem again, or if it becomes more frequent.

**Comment by jankeromnes** [comment]
Hopefully you've been able to log in by now. 🙂

Closing this for now, but please comment and/or reopen if you think we should do something more here.
