### ISSUE TITLE
Add first class support for editing files remotely in Sublime Text

### ISSUE THREAD

**Issue by ad-si** [gitpod-io/gitpod#6800]
## Is your feature request related to a problem? Please describe

While VSCode has come a long way, I think Sublime Text is still the better text editor and I would like to use it for editing files in Gitpod.

## Describe the behaviour you'd like

An `Open in Sublime Text` command

## Describe alternatives you've considered

Some easy way of mounting the workspace locally maybe?

## Additional context

https://github.com/randy3k/RemoteSubl could be used to implement it.

**Comment by akosyakov** [comment]
I think for such editors we should open up Gitpod for external contributions, similar to https://github.com/gitpod-io/gitpod/issues/2419.  It is certainly possible already, but very far from current focus.

For now you can do following:
- install the local companion to enable SSH: https://www.gitpod.io/blog/local-app
- use sftp to mount Gitpod workspace into your filesystem
- use Sublime

As far as I know Sublime does not have a concept like a virtual filesystem, so mounting is required (although it is not efficient).

In the final solution I would imagine that one can implement a plugin for Sublime which makes use of the local companion and mount filesystem automatically. Sublime will also need to register a special URI handler that browser can redirect to it, i.e. something like `sublime://gitpod+workspace_id/workspace_path`
