### ISSUE TITLE
Have an envvar with the IDE value

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6803]
## Is your feature request related to a problem? Please describe

Multi-user teams would like to automate tasks based on which IDE are being used for development. Depending upon which IDE in use, certain tasks will need to be differentiated.

## Describe the behaviour you'd like

Have an envvar set with an enum of the values. For example, `GITPOD_IDE` with values `VSCODE_BROWSER`, `VSCODE_EXTERNAL`, `INTELLIJ_PROJECTOR` and `INTELLIJ_CWM`

## Additional context

Request from a user managing multiple developers with different preferences for VSCode in browser, VSCode external, IntelliJ projector and IntelliJ Code-With-Me

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/gitpod/issues/6602

**Comment by akosyakov** [comment]
> Have an envvar set with an enum of the values. For example, GITPOD_IDE with values VSCODE_BROWSER, VSCODE_EXTERNAL, INTELLIJ_PROJECTOR and INTELLIJ_CWM

In the case with desktop we actually run 2 ides. There is already an env variable for web: `GITPOD_IDE_ALIAS` which is either `code` or `code-latest`. We can add `GITPOD_DESKTOP_IDE_ALIAS` by analogy.

One thing is that we don' want env var to be an api, but instead one should use supervisor info endpoint to read such data or maybe we can add it to `gp` for end users, i.e. `gp info ide` and `gp info desktop-ide`?  @csweichel wdyt?

**Comment by loujaybee** [comment]
I don't think this one is required any more, will close 🙏
