### ISSUE TITLE
[core-dev] - Prepare environment for Installer

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#6806]
- [ ] Validate we have core-dev backups for the core-dev cluster...just in case applying Installer yaml destroys state we need for it to function
- [ ] [Add Installer affinity labels to nodes](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/cluster/affinity.go#L9-L13) (Terraform code change)

<strike>
- [ ] Create two namespaces to be used for manual testing of the installer
- [ ] Create TLS certificates for the above two namespaces
- [ ] Create a config file to work in core-dev for the installer and validate it
- [ ] Validate the core-dev cluster with the installer
- [ ] Render with the Installer for one namespace & update for hostPort/node pool affinity
- [ ]  Apply the YAML and get the first namespace working
- [ ] Configure, Render, Update and Apply YAML for 2nd namespace
- [ ] Test both environments, do they still work? Fix if not.
</strike>

**Comment by kylos101** [comment]
@ArthurSens I updated this issue to simplify.

Given the head start Chris gave us with the automation on Friday, I think it would be best if we proceeded with these two tasks. 

What do you think?

**Comment by kylos101** [comment]
@ArthurSens can you start a draft PR for the Terraform changes? 

I'll start a draft PR for the werft job changes in #6808

**Comment by roboquat** [comment]
@kylos101: The label(s) `team: platform` cannot be applied. These labels are supported: `team: IDE, team: meta, team: workspace`

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6806#issuecomment-975767856):

>/team platform


Instructions for interacting with me are available [here](https://github.com/gitpod-io/gitbot/blob/main/plugins/customlabels/README.md). If you have questions or suggestions related to my behavior, please file an issue against the [gitbot](https://github.com/gitpod-io/gitbot/issues/new) repository.
</details>

**Comment by mads-hartmann** [comment]
I'm unassigning @ArthurSens from this and removing it from the Platfrom Groundwork project. @ArthurSens is available to help in any way he can and answer any questions you have but if there's some code changes that we (Platform) need to make we should create separate issues for that so we can get an overview of what Platform needs to help with ☺️

**Comment by kylos101** [comment]
Resolved in #323
