### ISSUE TITLE
[Werft] - Update build to support Installer

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#6808]
Dev
- [x] Update werft CI to use cached Installer (thanks @csweichel! [kick started here](https://github.com/gitpod-io/gitpod/tree/cw/werft-demo))
- [x] Update werft CI to use Installer binary to init config
- [x] Update typical config values and render K8s yaml
- [x] Post process K8s yaml for expected changes (node pool assignments, host port)
- [x] Post process K8s yaml for unexpected changes in Server config (enableLocalApp and theiaPluginsBucketNameOverride)
- [x] Add validation for config and cluster
- [x] Compare rendered and post-processed K8s yaml with in cluster resources - any conflicts with cluster wide resources?
- [x] Update werft CI to include an opt-out parameter, so folks can use Helm charts, avoiding Installer
- [x] Created observation for ghosts #6936
- [x] Can log in post install
- [ ] Validate Sweeper is working

Testing
- [x] Start and stop a workspace
- [x] Download changed workspace files from the dashboard
- [x] with clean slate deploy works (Installer)
- [x] with clean slate deploy works with-helm (Helm)
- [ ] with-observability works (with-helm never loads on all pods...is this a current issue or did I break it?)
- [x] works in GKE (test due to code changes to honor PSP)
- [x] test jetbrains IDE

FYI
* Work to validate cluster backups and prepare the nodes with new labels is in #6806

**Comment by kylos101** [comment]
@csweichel @MrSimonEmms there are many properties in [values.dev.yaml](https://github.com/gitpod-io/gitpod/blob/main/.werft/values.dev.yaml), which we don't generally specify with out of the box configuration (at least I did not when testing in GCP playground). 

I am going to start merging them

**Comment by kylos101** [comment]
As next steps I'm going to:
1. Test to see if a component's yaml (like `agent-smith`) impacts the rendering process
2. Check to see if we have [configuration](https://github.com/gitpod-io/gitpod/blob/sje/installer-readme/installer/pkg/config/v1/config.go) in the Installer that cover top level settings such as [these resource ones](https://github.com/gitpod-io/gitpod/blob/main/.werft/values.dev.yaml#L24-L30)

**Comment by kylos101** [comment]
> 1. Test to see if a component's yaml (like agent-smith) impacts the rendering process

Adding YAML for our agent-smith component from install.dev.yaml to our Installer config does not impact the rendering process.

> 2. Check to see if we have [configuration](https://github.com/gitpod-io/gitpod/blob/sje/installer-readme/installer/pkg/config/v1/config.go) in the Installer that cover top level settings such as [these resource ones](https://github.com/gitpod-io/gitpod/blob/main/.werft/values.dev.yaml#L24-L30)

[The configuration available to us is in this struct.](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/config/v1/config.go#L61-L86) There are many options which are overridden in core-dev.

### For discussion

I think our options are:
* Update the installer to include those things as overrides
* Do additional post processing on the k8s manifests <-- I think this makes sense, its just more post processing than we originally intended.

But maybe I am missing something that will make it easier to reuse values from install.dev.yaml.

**Comment by kylos101** [comment]
@MrSimonEmms what do you think Re: [this comment](https://github.com/gitpod-io/gitpod/issues/6808#issuecomment-975781444)?

**Comment by kylos101** [comment]
> @MrSimonEmms what do you think Re: [this comment](https://github.com/gitpod-io/gitpod/issues/6808#issuecomment-975781444)?

@MrSimonEmms I am all set, please ignore, I spoke with @csweichel, and will create some follow-up issues (some for the Installer to set new affinity values, and others to remove deprecated settings from server).

**Comment by mads-hartmann** [comment]
I'm unassigning @ArthurSens from this and removing it from the Platfrom Groundwork project. @ArthurSens is available to help in any way he can and answer any questions you have but if there's some code changes that we (Platform) need to make we should create separate issues for that so we can get an overview of what Platform needs to help with ☺️

**Comment by kylos101** [comment]
Hi, we're functional in #6827 now as of the latest commit. There are some loose ends to clean-up (tasks in this issue, and TODOs int he code), but the good news is we can run a build in werft and get an environment now.
