### ISSUE TITLE
Trackpad scrolling not working on iPad

### ISSUE THREAD

**Issue by marriaymalik** [gitpod-io/gitpod#6814]
### Bug description

Currently using Gitpod on a iPad Pro (M1), with the magic keyboard that comes with a trackpad. I’ve found that I can’t use the trackpad to scroll through the files, and the only means of scrolling is by using the scroll bar on the side or by using the touch screen. 

### Steps to reproduce

- Open a repo in Gitpod
- Using the magic keyboard trackpad, try and scroll down

**Comment by akosyakov** [comment]
Could you file an issue in upstream please: https://github.com/microsoft/vscode

**Comment by marriaymalik** [comment]
@akosyakov Please can this issue be removed and deleted. Thank you.
