### ISSUE TITLE
Issue at Opening a Repository

### ISSUE THREAD

**Issue by Jtoledo88** [gitpod-io/gitpod#682]
When I want to open this repository https://github.com/breatheco-de/exercise-queue-management-django with gitpod, this happen:

https://user-images.githubusercontent.com/32654829/61415713-7cf28800-a8bf-11e9-9155-19a2a159ff20.png

Please tell me how to solve it. 

Regards

**Comment by alesanchezr** [comment]
Hey I'm having this issue as well.

This repository was working perfect on gitpod last month and we have not made any changes, is there a way to get feedback about the error @jankeromnes ?

**Comment by geropl** [comment]
Hey,
I tried the repo and could not reproduce, it worked fine for me. Will vet the logs.

**Comment by geropl** [comment]
This is a regression we introduced yesterday with a hotfix: https://status.gitpod.io/incidents/430e869b
We just deployed the fix for that.

**Comment by alesanchezr** [comment]
Thanks man!
