### ISSUE TITLE
Enable use of internal SSL self-signed certificates to pull images

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#6823]
/team workspace
/assign
/schedule

**Comment by stefanstoeckigt** [comment]
@aledbf , @MrSimonEmms how do i go about setting the self-signed CA, i can see where to set in in the helm chart value.yml, however i don't know how to set this with the new installer method?

**Comment by MrSimonEmms** [comment]
@stefanstoeckigt this is supported by default with the [Installer](https://github.com/gitpod-io/gitpod/tree/main/installer) - please use that.

Latest release is [2022.01](https://github.com/gitpod-io/gitpod/releases/tag/2022.01)

**Comment by stefanstoeckigt** [comment]
@MrSimonEmms, many thanks for the quick reply. 
I been going through the setup process with the Installer, however where do i set the private certificate authority secret in the config.gitpod.yml? 
The installer readme only refers to [how-do-i-use-my-own-tls-certificate](https://github.com/gitpod-io/gitpod/tree/main/installer#how-do-i-use-my-own-tls-certificate) with a public CA. I need to use a private CA.

**Comment by MrSimonEmms** [comment]
@stefanstoeckigt you don't. You create the secret separately as per the instructions and then add the name to your `gitpod.config.yaml`. The default value is `https-certificates` and the example link you sent uses that name.

Please join the self-hosted channel on [Discord](https://www.gitpod.io/community) and we can help further in there
