### ISSUE TITLE
Customize the Login page for unauthenticated users arriving from an "Open in Gitpod" context     

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#6826]
This only applies to the login/signup page presented to unauthenticated users, landing at gitpod.io with a #-prefixed git repo context. Using the repo context we should present those users with a simpler, less-generic Login page to improve the conversion rate for new signups arriving from this source.

- Remove the welcome section on the left
- Show the Gitpod logo and name
- Change "Log in" to "Log in / Sign up"
- Customized message: `Open a cloud based development environment for <repo XXX>`
- Single `Continue` button leading to the git provider matching repo ☝️, usable with the Enter key.

![Screenshot 2021-11-21 at 22 06 01](https://user-images.githubusercontent.com/849592/142780645-c7dbc279-cead-45d3-8ac3-e8bc2c05e68d.png)

If possible, we would like to implement this in way that will allow us to present either the existing OR the new design, and measure the aggregate signup rates for both versions.   

For further background see [Notion RFC](https://www.notion.so/gitpod/Unqualified-leaky-bucket-d02f1a47aaf44621b5a87e1dcac90de8#6472fae609f040be984bf19ec1a68b1a) (internal)

**Comment by svenefftinge** [comment]
💯 Three small suggestions:
1) Can we remove the "Log in / Sign up" headline? I don't think it adds any value, as the main action is to "Continue" and it tones down the "what" (i.e. "Open a cloud based development environment for ..."
2) The repo URL should be shortened to the usual `group/name` pattern.
3) Let's keep the "Continue with GitHub" resp. "Continue with GitLab" buttons, as they not only look nicer but also prepare users for the upcoming oauth.

**Comment by jldec** [comment]
Thanks @svenefftinge - good suggestions - How about this (see screenshot below)?

- We could make the user/repo name link back to github
- We could also shorten `for the repository <user/repo>` to just `for <user/repo>` 

![Screenshot 2021-11-22 at 12 23 22](https://user-images.githubusercontent.com/849592/142861310-c32ae967-93ed-4055-995e-d03ff7ffd21e.png)

**Comment by jakobhero** [comment]
Great suggestions! In order to attribute events to their respective groups in A/B testing, it would be sufficient to pass a property for those users that are shown the new change, e.g. `test_group: 'A'`. The events itself should be captured in the same way as they currently are, i.e. `page` call for a first time visitor, `path_changed` call for a visitor who has been redirected from the dashboard internally (which might never happen if the user is not signed up in the first place) and a `dashboard_clicked` call when the user clicks on _Continue with ..._ (the call is made automatically). We just need to make sure that the test group property is attached to both, the call when the user enters this screen (`page` / `path_changed`) and when she converts to the next (`dashboard_clicked`). Let me know how I can help in the implementation and testing:)

**Comment by svenefftinge** [comment]
Do we need to roll this out in A/B mode? FWIW I'm super confident it is an improvement over the current situation.

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-981474239):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jldec** [comment]
Related issue https://github.com/gitpod-io/gitpod/issues/4696 brought up 2 edge-cases

1. user with integrations for 2 providers, arrives at login for prefixed repo on provider1, chooses provider2 in login UI 
2. user with integration for provider1, arrive at login for prefixed repo on provider2

**Comment by jldec** [comment]
edge case 1: mitigated by only showing the button for matching provider

edge case 2: this is problematic, because with the change as proposed by this issue, you'll be encouraged to create a new account with the matching provider2  - which will lead to an error if you use the same email, or 2 Gitpod accounts if you use a different email.

**Comment by jldec** [comment]
Let's proceed with the design as shown, and try to mitigate edge case 2 in #4696

**Comment by laushinka** [comment]
@jldec Is there a case where we would still show this image?

<img width="462" alt="Screenshot 2021-12-01 at 17 46 57" src="https://user-images.githubusercontent.com/8015191/144276719-5d4584fa-ba10-49b8-97a1-0333e213760e.png">
e?

**Comment by jldec** [comment]
We show the login with this left-pane for any action on the dashboard when unauthed and missing cookies.
E.g. I was able to bring it up by deleting all browser history/cookies and then going to any of the following
https://gitpod.io/login
https://gitpod.io/new
https://gitpod.io/projects

This change should only apply when landing unauthed at `gitpod.io/#<git-repo-URL>` to start a workspace on that repo.

**Comment by gtsiolis** [comment]
FYI, regarding the left section there, cross-posting from https://github.com/gitpod-io/website/issues/907#issuecomment-910301281:

> ... automatically removes the left section if a user has logged in the dashboard before. 💜

Cc @laushinka @jldec

**Comment by gtsiolis** [comment]
@jldec what do you think of the following proposal? Cc @laushinka 

| CURRENT | DRAFT | PROPOSAL |
|-|-|-| 
| <img width="1440" alt="Screenshot 2021-12-03 at 12 05 01 AM (2)" src="https://user-images.githubusercontent.com/120486/144510654-084a22fc-306f-4156-a762-9eff2796ff2e.png"> | <img width="1440" alt="2" src="https://user-images.githubusercontent.com/120486/144510435-7c449d38-8dc9-417f-9a2b-6c288ccd6870.png"> | <img width="1440" alt="Full" src="https://user-images.githubusercontent.com/120486/144510439-81e8475e-45fe-4f42-b264-fd5de48cadd3.png"> |

**Comment by laushinka** [comment]
@gtsiolis Sorry I only saw you posted this after I created a PR! 😵 I was going with the previous ones I saw on Figma.. I won't mind continuing the discussion of course. Also feel free to take a look at the [PR](https://github.com/gitpod-io/gitpod/pull/7046) if you think it would be useful..

**Comment by gtsiolis** [comment]
No worries, @laushinka! Let's wait for some feedback from @jldec first but we could move forward with the proposed designs[[1](https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-975469912)] in this iteration as this is already an improvement and improve later. Terima kasih!

**Comment by laushinka** [comment]
@gtsiolis [Your points](https://gitpod.slack.com/archives/C02EN94AEPL/p1638479686320100?thread_ts=1638453834.313000&cid=C02EN94AEPL) are very valid, and @jldec and I discussed this at length as it's not a straightforward. We ended up going with [this approach](https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-983582329) for this ticket. As this is an important ticket, I'm also down to discussing it again together synchronously 🤗

**Comment by laushinka** [comment]
@gtsiolis Just saw your reply againnn.. 🙈 Time for bed maybe for both of us

**Comment by jankeromnes** [comment]
Many thanks for improving the login UX! 🙏

In response to https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-985039468:

> what do you think of the following proposal?
> [...]
> | CURRENT | DRAFT | PROPOSAL |
> |-|-|-| 
> | <img width="1440" alt="Screenshot 2021-12-03 at 12 05 01 AM (2)" src="https://user-images.githubusercontent.com/120486/144510654-084a22fc-306f-4156-a762-9eff2796ff2e.png"> | <img width="1440" alt="2" src="https://user-images.githubusercontent.com/120486/144510435-7c449d38-8dc9-417f-9a2b-6c288ccd6870.png"> | <img width="1440" alt="Full" src="https://user-images.githubusercontent.com/120486/144517196-a467bc74-37e0-428e-9d64-18f712627774.png"> |

I know I wasn't specifically asked, but I felt like adding my 2 cents 😇 please ignore if unhelpful.

- `CURRENT` I like how obvious this screen is (it's clearly a login screen -- not sure what's after it, but I'm 0% confused regarding what to do)

- `DRAFT` I like how crisp and to-the-point this screen is (it somewhat looks like a login/auth screen, and it's telling me what's after it -- although, I'd still find the word "login" re-assuring here, i.e. this is not "completely take over my GitHub account")

- `PROPOSAL` I'm immediately confused by:
  - there is way too much going on: many different texts, sizes, colors, visual elements -- I have no idea where to look or what to do and want to run away 😅
  - the huge orange button thing is particularly overwhelming, and 100% distracts from the primary login button

---

All-in-all, I really like `CURRENT` and `DRAFT`, but I agree that in `DRAFT` the `Continue with GitHub` button could have a little dropdown element to still allow logging in with another provider.

**Comment by loujaybee** [comment]
Hey folks 👋   Firstly, I _love the collaboration going on_ with these changes 😍 ! I don't have direct feedback, as I agree with much of what has already been said, and do not think more chefs will help 👩‍🍳  

But I wanted to make a few remarks based on findings from usability testing, as I think it's important to keep the user and specifically, the users frame of mind front-and-center when we make decisions about this page. 

This is not just an exercise in making an optimal login (from a clicks/design perspective) 👇

1. **Gitpod terminology**. We should consider that users might not yet know what terminology such as a "workspace" is. A question that came up a few times in usability testing from users was: "what's the difference between a project and a workspace", for instance. 
2. **Gitpod concepts**. We should be careful making assumptions that it's transparent to a user some assumptions about how Gitpod works, e.g. that a repository, workspace and project area all 1<>1. Let's try and lean on any existing mental models the user might have, or terminology the user might be most familiar with... and on the flip side, be judicious with new, or gitpod-specific terminology, such as "workspace", "project", etc. 
3. **At this stage, we're dealing with a users sensitive data (code)** - The user should here be assumed to have _no idea_ who (Gitpod) are, and we should treat this interface with the same level of skepticism that a user would when being asked to login and hand over sensitive data to a third party. It's _important that we build trust here_. Any signals we can give the user that we're trustworthy, and transparent about what is going to happen after they click the login button could help. 

A user coming to Gitpod for the first time is likely to be cautious/skeptical about logging in with us, and giving us their data. This is not just a functional journey (i.e login as quickly as possible) but also an emotional one. If we find that more "clicks" or "screens" to guide the user a little and build trust here works, let's also consider that. 🙏 🙏🙏

**Caveat/warning:** If I've found anything to be true in UI design, it's that we cannot safely assume that users will read things. So incorporating the above ideas might require subtlety, branding, iconography, etc. 

As with @jankeromnes's comments above, take what's useful from my feedback, and discard the rest. You have all the context to make the decisions. If we want to re-run any usability testing over mock-ups or designs before we cast this in code, let's also consider that if needs be, I can help you here 🙏 .

**Comment by loujaybee** [comment]
> Do we need to roll this out in A/B mode? FWIW I'm super confident it is an improvement over the current situation.

**Separate note:** A pragmatic option here could be to roll out the change out (for a week or so) measure the impact, and then be prepared to roll back if changes are seen to be detrimental, if they're positive, then we fix forward! 🚀

**Comment by gtsiolis** [comment]
Thanks @jankeromnes and @loujaybee for you feedback! 🙏 

@jankeromnes you're right about the orange element thing is particularly overwhelming. I've added https://github.com/gitpod-io/gitpod/issues/7061 to improve the login action buttons, etc.

What do you think of the following drafts? Cc @laushinka @AlexTugarev @geropl @jldec @svenefftinge 

| Early draft for the long run | Early draft for this iteration |
|-|-|
| <img width="1440" alt="Full" src="https://user-images.githubusercontent.com/120486/144687959-0f6aef3f-46f7-4128-8a71-f61600b7f01f.png"> | <img width="1440" alt="Full" src="https://user-images.githubusercontent.com/120486/144688252-a2383429-e6f7-4802-94f4-90f9b0239350.png"> |

**Comment by svenefftinge** [comment]
The point of this change was to reduce the noise and just tell people what is going to happen next. No side-tracking explaining Gitpod concepts or providing confusing choices. I think we have discussed that at length already. 
So could we please just put in what @jldec proposed in https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-975469912 and see how it moves the needle?

**Comment by jldec** [comment]
Thanks for all the feedback everyone - This page is an important step in our onboarding experience so the thoughtful comments and suggestions are appreciated.

In an effort tilt the bias toward action and simplicity, let move forward with proposal (screenshot below)

NOTE We recognize that reducing the auth-button choices does mean a slightly higher possibility of existing (already-signed-up) users creating another Gitpod account, but it also stops erroneoous signup with one git provider when opening a workspace for a different git provider.

I will put additional comments in PR #7046 .

![142861310-c32ae967-93ed-4055-995e-d03ff7ffd21e](https://user-images.githubusercontent.com/849592/144829246-2ebc137f-9010-4073-a6cd-d243ef4929fe.png)

**Comment by gtsiolis** [comment]
Thanks everyone and sorry for sidetracking the discussion with more designs in https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-985039468 and https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-985922724. 🙏 

💭 **thought**: The proposed design from @jldec in https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-986645193 is certainly an improvement we can ship[[1](https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-985087312)].

❗ **issue**: The only caveat that comes with the proposal in https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-986645193 is the small risk of blocking users. Cross-posting from the [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1638479686320100?thread_ts=1638453834.313000&cid=C02EN94AEPL) (internal):
> For example, GitLab only users would be blocked from logging in for a GitHub repository. Currently, we handle this with [proper feedback](https://github.com/gitpod-io/gitpod/pull/6484). 

**suggestion**: However, let's not worry for problem that may not exist. This can be resolved with https://github.com/gitpod-io/gitpod/issues/7061 or by simply listing back all provider options. Maybe we could cross-check with data if this is an issue. Otherwise, this will probably surface as an issue from the community.

🍊 🍊 🍊 🍊 

To help make consensus and actions needed more visible, I'd suggest to:
1. Use the issue description as the single source of truth (SSOT) for any consensus or design decisions
2. Remove remove labels like "~needs visual design 💄" when needed

**Comment by jldec** [comment]
Reminder to prioritize https://github.com/gitpod-io/gitpod/issues/4696 - 
Show helpful explanation when opening a workspace and the git provider integration is missing

**Comment by laushinka** [comment]
In order to have better analytics and a data-driven decision-making, after a [discussion](https://www.notion.so/gitpod/Meta-Sync-Dec-6-2021-4ee3c5ddae594d209cbf6dff52ed043f#bdff668e9e7a47b59e0c426c642423ac) in the Meta team, we will enable A/B testing for this page with a 50:50 ratio for each group once [this](https://github.com/gitpod-io/gitpod/pull/7081) is merged. This will be the first time we try A/B testing for the Dashboard.
