### ISSUE TITLE
[db] High DB CPU load due to Team Subscriptions (it seems)

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6833]
We have a near-perfect correlation between alerts firing ([internal link](https://gitpod.pagerduty.com/incidents/Q24UOVGN0Q7YCL?utm_source=slack&utm_campaign=channel)) and [TS methods calls](https://grafana.gitpod.io/d/server/gitpod-component-server?orgId=1&refresh=30s&from=1637572530619&to=1637583330619&viewPanel=62) (US).

**Comment by geropl** [comment]
Fix might be as easy as to fix https://github.com/gitpod-io/gitpod/issues/6807

**Comment by roboquat** [comment]
@geropl: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6833#issuecomment-976375014):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
Seems to be fixed with https://github.com/gitpod-io/gitpod/issues/6807, closing for now.
