### ISSUE TITLE
Error: Unknown docker image. Cannot access image manifest for: eu.gcr.io/gitpod-dev/workspace-full:hotfix-gh-2732.1

### ISSUE THREAD

**Issue by frenck** [gitpod-io/gitpod#684]
**Describe the bug**

Any repository that I want to open in a pod, reports:

"Error: Unknown docker image. Cannot access image manifest for: eu.gcr.io/gitpod-dev/workspace-full:hotfix-gh-2732.1"

![image](https://user-images.githubusercontent.com/195327/61455985-4d965680-a965-11e9-8006-18c7bc40d515.png)

E.g., <https://gitpod.io/#https://github.com/gitpod-io/rails_sample_app>

**To Reproduce**

Open up any repo. (e.g., the one listed above).

**Expected behavior**

To be able to work on projects.

**Comment by geropl** [comment]
Hi @frenck,

thanks for reporting! :+1:  We're on it.

**Comment by geropl** [comment]
**Update:** Fixed and deployed. @frenck Could you verify?

**Comment by frenck** [comment]
Works like a charm! 🎉 

Thanks for addressing it so quickly 👍 

../Frenck
