### ISSUE TITLE
`/#get-started` redirects to `/new` instead of dashboard for authenticated users

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6840]
### Bug description

Going to `/#get-started` redirects to `/new` instead of the dashboard for authenticated users. 

This can be [viewed in this usability study (internal link)](https://www.notion.so/gitpod/Vinny-Ruia-f687beea5c79434aa3c3bbc66dc16f9a) @ 31:48 

### Steps to reproduce

* Login to Gitpod
* Go to: https://www.gitpod.io/#get-started
* Click "continue with GitHub" 
* Redirects to: https://gitpod.io/new

### Expected behavior

* User is directed to the dashboard (this behaviour happens if you click the dashboard button)

**Comment by jldec** [comment]
I believe this is by design - "Connect Git repository" should mean the same thing to authed vs. unauthed users.

**Comment by jldec** [comment]
![Screenshot 2021-11-29 at 23 49 12](https://user-images.githubusercontent.com/849592/143960631-8ffa8655-f77f-4132-b8c2-18be67c0994f.png)
