### ISSUE TITLE
Return to Dashboard link on the Your Workspace is Ready screen

### ISSUE THREAD

**Issue by zpthree** [gitpod-io/gitpod#6841]
## Is your feature request related to a problem? Please describe

No
## Describe the behaviour you'd like

It would be nice to have a "Return to Dashboard" button on the "Your Workspace is Ready!" screen.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/28521478/142929197-e1906332-c6bc-4157-9301-bafe2b05f0a8.png">

**Comment by akosyakov** [comment]
@gtsiolis @loujaybee @corneliusludmann I think something like that was discussed somewhere, like having stop workspace button?

**Comment by corneliusludmann** [comment]
Indeed. What do you think about something like this:

![image](https://user-images.githubusercontent.com/24960040/142996537-89552653-67ea-4622-833c-f1ea756c8388.png)

@gtsiolis Any ideas for UX/wording improvements?

Related issue: https://github.com/gitpod-io/gitpod/issues/6769
