### ISSUE TITLE
Request createWorkspace failed with message: 14 ... Unknown Error: { "code": -32603 }

### ISSUE THREAD

**Issue by z3ky** [gitpod-io/gitpod#6848]
### Bug description

Get this error on a new self-hosted installation of gitpod v0.10.0 on ubuntu 20

Request createWorkspace failed with message: 14 UNAVAILABLE: No connection established
Unknown Error: { "code": -32603 }

After calling gitpod with a repo url, the browser shortly shows "checking" then the error message from above.
All pods are running and I got no erroneous kubernetes events.
Same config file works on another server.

Which pods are in charge at this early stage? so I could have a look into their logs.

### Steps to reproduce

- new installation of gitpod v0.10.0
- standard configuration settings from docs
- call https://mygitpod.com/#https://mygit.com/test.git

**Comment by ghuntley** [comment]
Howdy z3ky, when you say "on Ubuntu" can you please expand what that means?

Which guide from https://www.gitpod.io/docs/self-hosted/latest/requirements did you follow?

ps. Maybe it's best to continue this discussion over in the Gitpod Self Hosted room in https://www.gitpod.io/chat

**Comment by z3ky** [comment]
Thanks for the fast response. After some further testing I decided to reinstall K3s. Now, Gitpod works :)
I don't now why, I just enjoy.

For others having this issue, I don't think that Gitpod was the cause.

For installation, I followed
https://www.gitpod.io/docs/self-hosted/latest/installation/on-kubernetes
on a regular Rancher K3s Cluster without any custom configuration on Ubuntu 20.04 LTS
