### ISSUE TITLE
[installer] default for enableLocalApp

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#6851]
## Is your feature request related to a problem? Please describe

enableLocalApp currently defaults to false (for the helm charts and Installer).

## Describe the behaviour you'd like

Consider defaulting to true in Installer source code, as the Installer is intended to be used for future installs. [This way this feature is always available with new installs.](https://www.gitpod.io/blog/local-app)

## Describe alternatives you've considered

Leave it set to false.

## Additional context

It defaults to false in the helm chart's config map.
It defaults to false in the installer.
It is set to true for core-dev.
[Where is enableLocalApp used? Check out these results.](https://github.com/gitpod-io/gitpod/search?q=enableLocalApp)

**Comment by roboquat** [comment]
@kylos101: The label(s) `team: ide` cannot be applied. These labels are supported: `team: IDE, team: meta, team: workspace`

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6851#issuecomment-976924222):

>/team IDE


Instructions for interacting with me are available [here](https://github.com/gitpod-io/gitbot/blob/main/plugins/customlabels/README.md). If you have questions or suggestions related to my behavior, please file an issue against the [gitbot](https://github.com/gitpod-io/gitbot/issues/new) repository.
</details>

**Comment by csweichel** [comment]
This should always be true. We introduced the flag during development of the local app.

**Comment by kylos101** [comment]
> This should always be true. We introduced the flag during development of the local app.

Okay, I'll include in #6827 and set it [here](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/configmap.go#L52). Thanks!

**Comment by akosyakov** [comment]
@kylos101 What are expectations from IDE team here?

**Comment by kylos101** [comment]
Hey @akosyakov , this is an old issue and can be closed. At the time of authoring this issue, the installer was new, and creating this issue was our way of introducing you to it. [As you can see here](https://github.com/gitpod-io/gitpod/blob/8e79e27d1d32b8646bbfad78fede790004ba5080/installer/pkg/components/server/configmap.go#L58), the setting is defaulting to true now.
