### ISSUE TITLE
[server] Mem leak: @grpc/grpc-js channels

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6852]
[Todays work on dashboards](https://github.com/gitpod-io/gitpod/pull/6845) revealed that we have a memory leak in `server`.
The following screenshot shows before and after deployment. (The steep increase on one instance was me taking a heapsnapshot).
![image](https://user-images.githubusercontent.com/32448529/143057518-cff8e304-793d-4386-a6d5-9e194ab607ed.png)

After taking heapsnapshots and investigating it seems that it's around grpc-connections, and how we handle cache them/reconnects. There are at least three leaks:
 - we create 4 new clients to `content-service` for each new websocket connection ([link](https://github.com/gitpod-io/gitpod/blob/c494a0ba63e7d167079568f70519004d4f5a3cab/components/server/src/container-module.ts#L200-L219))
 - we leak ws-manager clients/channels [here](https://github.com/gitpod-io/gitpod/blob/9605e0b386e9216719cbbda377bef2e0e8738b36/components/ws-manager-api/typescript/src/client-provider.ts#L92-L104) in cases where old clusters go offline (it seems)
 -  we never close image builder clients that [are not connected anymore](https://github.com/gitpod-io/gitpod/blob/353ddc20fb8703147903de0c1240a128fcc3c5a3/components/image-builder-api/typescript/src/sugar.ts#L56-L69)

What triggered this seems to have been the version bump to [`@grpc/grpc-js 1.4.2`](https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.4.2) which introduce "channelz" (looks like channel statistics or so) which seems to increase the footprint per channel, and also causes channel to leak if they're not explicitly `close()`d.

A general question would be how to handle channel reconnects at all. There seems to be no auto-reconnect like in other languages (grpc docs mention it's language-specific).

**Comment by csweichel** [comment]
> A general question would be how to handle channel reconnects at all. There seems to be no auto-reconnect like in other languages (grpc docs mention it's language-specific).

Indeed there isn't, e.g. the transparent retry when `UNAVAILABLE` does not work in grpc-js. We have manual [retry mechanisms for this in some places](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/typescript/src/promisified-client.ts#L32-L61) and [manual connection management in others](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/typescript/src/client-provider.ts#L97-L104).

**Comment by roboquat** [comment]
@geropl: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6852#issuecomment-977608900):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
> Indeed there isn't, e.g. the transparent retry when UNAVAILABLE does not work in grpc-js. We have manual retry mechanisms for this in some places and manual connection management in others.

Saw those. Mentioned it to verify it's still like that after the upgrade. Conclusion: it is :-)
