### ISSUE TITLE
Extensions re-downloaded

### ISSUE THREAD

**Issue by hm2075** [gitpod-io/gitpod#6858]
### Bug description

Extensions are downloaded each time a workspace is started,   if for some reason an extension is no longer available for example
angular language services which has been down on open vsx for a few days users are unable to use the extension

this is not the first time this has happened,   previously it was the omnisharp plugin that was broken.    

We shouldn't allow gitpod to go and fetch the latest version of an extension each time a workspace is started,   

### Steps to reproduce

open a workspace with an extension that has been removed that was previously installed

### Expected behavior

dont re-download extensions,   store them in storage instead as was the case on previous versions of gitpod

**Comment by akosyakov** [comment]
Please see the answer here: https://community.gitpod.io/t/java-plugins-not-working/5640/15?u=akosyakov

An issue for angular: https://github.com/open-vsx/publish-extensions/issues/506
