### ISSUE TITLE
[observability] Add alert when workspace failure rate increases

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6859]
We need an alert when the workspace failure rate in any cluster exceeds 1 failure per second for at least 5 minutes.
As a follow up, we'll want to write a runbook for this case.

**Comment by kylos101** [comment]
@princerachit as you're knee deep in alerts now, may I ask you to queue this one as well? It'll also need a related runbook as Chris mentions.

This will complete what @sagor999 mentioned a few days ago to me in a conversation as to what he looks for:
1. High normalized averages <-- covered now with warnings and on-call
2. High error rate <-- not covered, but this issue will do
3. Regular not active coupled with no workspaces starting <-- you are working this now in another issue

Are the trends we look for.

**Comment by princerachit** [comment]
When did we such an issue last time? I want to understand how did we decided on 1failure per second. I have raised this PR to address the issue https://github.com/gitpod-io/gitpod/pull/9220

**Comment by kylos101** [comment]
Hmm, good question, @princerachit ! 

What do you see over the last 60 days in Gitpod for how often this rule would have fired, if it were configured at 1 per second? Depending on the frequency you see, you might want to change the condition higher or lower.

What else can you check for clues? I am thinking description in incident.io, and maybe Slack threads for strings like "high failure rate" or "failures per second".
