### ISSUE TITLE
[terminal] Error: terminal is not started

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#686]
**Describe the bug**

I can see the following error in the browser's console every time I open a new terminal with <kbd>Ctrl</kbd>+<kbd>`</kbd>.

```
Uncaught (in promise) Error: terminal is not started
    at t.get [as processId] (terminal-widget-impl.ts:219)
    at n (terminal-main.ts:60)
    at e.<anonymous> (terminal-main.ts:62)
    at output-channel-registry-main.ts:23
    at Object.next (output-channel-registry-main.ts:23)
    at output-channel-registry-main.ts:23
    at new Promise (<anonymous>)
    at r (output-channel-registry-main.ts:23)
    at e.trackTerminal (terminal-main.ts:51)
    at terminal-main.ts:38
get @ terminal-widget-impl.ts:219
n @ terminal-main.ts:60
(anonymous) @ terminal-main.ts:62
(anonymous) @ output-channel-registry-main.ts:23
(anonymous) @ output-channel-registry-main.ts:23
(anonymous) @ output-channel-registry-main.ts:23
r @ output-channel-registry-main.ts:23
e.trackTerminal @ terminal-main.ts:51
(anonymous) @ terminal-main.ts:38
(anonymous) @ event.ts:119
e.invoke @ event.ts:127
e.fire @ event.ts:220
(anonymous) @ terminal-frontend-contribution.ts:118
(anonymous) @ event.ts:119
e.invoke @ event.ts:127
e.fire @ event.ts:220
(anonymous) @ widget-manager.ts:140
(anonymous) @ main.js:870
(anonymous) @ main.js:870
a @ main.js:870
Promise.then (async)
c @ main.js:870
(anonymous) @ main.js:870
o @ main.js:870
e.getOrCreateWidget @ widget-manager.ts:120
(anonymous) @ terminal-frontend-contribution.ts:320
(anonymous) @ preferences-menu-factory.ts:24
(anonymous) @ preferences-menu-factory.ts:24
(anonymous) @ preferences-menu-factory.ts:24
s @ preferences-menu-factory.ts:24
e.newTerminal @ terminal-frontend-contribution.ts:319
(anonymous) @ terminal-frontend-contribution.ts:378
(anonymous) @ preferences-menu-factory.ts:24
(anonymous) @ preferences-menu-factory.ts:24
(anonymous) @ preferences-menu-factory.ts:24
s @ preferences-menu-factory.ts:24
e.openActiveWorkspaceTerminal @ terminal-frontend-contribution.ts:377
execute @ terminal-frontend-contribution.ts:160
e.tryKeybindingExecution @ keybinding.ts:570
e.run @ keybinding.ts:619
(anonymous) @ frontend-application.ts:164
```

**To Reproduce**

 - Open a PR in Gitpod. I picked this one: https://github.com/theia-ide/theia/pull/5665
 - Open a new terminal with a keybinding.
 - See the error in the browser's console.

**Expected behavior**

 - I do not have an error.

Note: the terminal works although I see the error.

**Comment by jankeromnes** [comment]
I'm not sure what happened here, and I'm not able to reproduce, as I'm able to reliably open https://github.com/theia-ide/theia/pull/5665 in Gitpod and open a new Terminal with <kbd>Ctrl</kbd> + <kbd>`</kbd>.

**Comment by kittaakos** [comment]
> and I'm not able to reproduce, as I'm able to reliably open [theia-ide/theia#5665](https://github.com/theia-ide/theia/pull/5665)

I have just tried it; it's the same.

Open the referenced PR, wait until the workbench is up, refresh your browser:
```
terminal-widget-impl.ts:219 Uncaught (in promise) Error: terminal is not started
    at t.get [as processId] (terminal-widget-impl.ts:219)
    at n (terminal-main.ts:60)
    at e.<anonymous> (terminal-main.ts:62)
    at output-channel-registry-main.ts:23
    at Object.next (output-channel-registry-main.ts:23)
    at output-channel-registry-main.ts:23
    at new Promise (<anonymous>)
    at r (output-channel-registry-main.ts:23)
    at e.trackTerminal (terminal-main.ts:51)
    at terminal-main.ts:38
```

I hope this helps.

**Comment by jankeromnes** [comment]
Thanks for confirming that you're still seeing this problem.

Here is a screencast where I open the referenced PR, wait until the workbench is up, refresh my browser, and then try to open Terminals:

https://youtu.be/J7wIA97W5Ls

As you can see, opening the Terminals is successful for me (Firefox Nightly on MacBook Pro), but there are indeed a few errors logged in the Browser Console. They don't seem to affect functionality though.

When you do the same thing, the Terminals that you try to open don't work at all?

**Comment by kittaakos** [comment]
> the Terminals that you try to open don't work at all

They work. See [above](https://github.com/gitpod-io/gitpod/issues/686#issue-470169944):
> the terminal works although I see the error.

**Comment by jankeromnes** [comment]
Aha, indeed, sorry for missing this important piece of information.

Thanks for catching this stray console error. I agree that we should probably fix any console errors in Theia, as even if the IDE still appears to work, they might be symptoms of things that misbehave in more subtle ways.
