### ISSUE TITLE
Update public docs to reference the private beta instructions

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6861]
As a step towards opening the BETA for JetBrains, we need to [update the public docs](https://www.gitpod.io/docs/editors) so that we have public-facing documentation on how the private Beta works. 

This means taking: https://www.gitpod.io/docs/editors/jetbrains-private-beta

And integrating it with: 
* https://www.gitpod.io/docs/editors/goland
* https://www.gitpod.io/docs/editors/intellij
* https://www.gitpod.io/docs/editors/pycharm

Additions: 
* Update with details about how JetBrains extensions work (see [internal discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1637762361227900?thread_ts=1637612113.198000&cid=C01KGM9BH54))
    * The original architecture document (JetBrains) is different to our understanding, we need to clarify it. 
* Move VS Code Desktop Extensions file into editor space

(and any other IDE's that we have available)

Ideally, we'll embed some screenshots and/or GIF's where necessary to explain to users how to set up the beta IDE's.

**Comment by loujaybee** [comment]
Maybe one for you @filiptronicek if you want to help us out with some of the website documentation 🚀

**Comment by akosyakov** [comment]
@loujaybee I removed it from the groundwork, since it was partly done by https://github.com/gitpod-io/gitpod/issues/6899

Should we keep it for additional points?
