### ISSUE TITLE
[question] Why do I see `A service is listening on port` but I cannot see this port in the `Ports` view

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#687]
- I started Gitpod on this PR: https://github.com/theia-ide/theia/pull/5665
 - I opened Theia with the changes from the PR.
 - I run `Reset Workbench Layout` in Theia.
 - I can see this in my Gitpod workspace.

![Screen Shot 2019-07-19 at 08 45 27](https://user-images.githubusercontent.com/1405703/61516960-673baa80-aa06-11e9-8c61-df913a31c0d6.jpg)
![Screen Shot 2019-07-19 at 08 48 15](https://user-images.githubusercontent.com/1405703/61517020-8cc8b400-aa06-11e9-87fa-0bf0d0131792.jpg)

 - The notification is misleading as I do not have that port in the `Ports` view.
 - I would like to see what is that _service_ as I did not start anything on my own.

**Comment by jankeromnes** [comment]
Hi @kittaakos, is it possible that some random background process briefly started a server on port 11265, causing the notification to show up, but then stopped the server again?

I think this would cause such a notification to show up, without remove it again, and would explain why the `Open Ports` view doesn't have a port 11265.

**Comment by jankeromnes** [comment]
Hi @kittaakos, was my reply helpful? Or is this a problem you're still facing? 🙂

**Comment by kittaakos** [comment]
> is it possible that some random background process briefly started a server on port 11265

I am not aware of any spawned processes from Theia.

> Or is this a problem you're still facing?

I have not tried it since then.

**Comment by kittaakos** [comment]
Feel free closing it.
