### ISSUE TITLE
Gitpod "open in" should be set-able per project, not just per-user

### ISSUE THREAD

**Issue by rfay** [gitpod-io/gitpod#6874]
## Is your feature request related to a problem? Please describe

The new Jetbrains open-in-local feature is great, but you have to choose it for the whole user. I work in GoLand for many projects, but PhpStorm for many others. 

## Describe the behaviour you'd like

I'd want to be able to configure the "open in" at the project level, not the user level.

Currently it's all-in for one tool, and that doesn't fit what I'd do.

Relates to:
- https://github.com/gitpod-io/gitpod/issues/8573
- https://github.com/gitpod-io/gitpod/issues/6706
- https://github.com/gitpod-io/gitpod/issues/6602
- https://github.com/gitpod-io/gitpod/issues/6874
- https://github.com/gitpod-io/gitpod/issues/9434
- https://github.com/gitpod-io/browser-extension/pull/59
- https://github.com/gitpod-io/gitpod/issues/7525

**Comment by akosyakov** [comment]
> I'd want to be able to configure the "open in" at the project level, not the user level.

I guess you mean per project but on user level, i.e. each user can decide which project he wants to use for different repos. It is very typical in java world for instance to only commit gradle or maven setup but let devs use IDE of preference.

**Comment by rfay** [comment]
Yes, I do mean project-level and of course under control of the user. I guess because I don't have anybody else in the project I use I forget that. That does make it more complicated.

**Comment by MrSimonEmms** [comment]
I would love to see it being even more granular than that and being able to decide which Jetbrains IDE I use at runtime.

Real world usecase - I tend to want to use Goland when working with Go projects but IntelliJ when working on JS projects. When doing work on the Gitpod repo, this has both projects so I tend to switch between the two.

In my mind, this could work as a [split button](https://daemonite.github.io/material/docs/4.0/components/dropdowns/#split-button) showing all the different available IDEs (defaulting to whatever is set as your default browser in settings)

**Comment by loujaybee** [comment]
Associated with: https://github.com/gitpod-io/gitpod/issues/8573

**Comment by loujaybee** [comment]
A couple of additional thoughts: 

1. Dotfiles is the current method of modifying a workspace for a users configurations
1. Implementing in the open in the dashboard will facilitate just that flow (not from "Open in Gitpod" buttons, etc)
1. Implementing as URL param would allow us to facilitate from JetBrains, VS Code, local CLI on an ad-hoc basis

The only "viable" option here seems to be having this per project, however, it would be good to have a "global" view of your overrides to default, as going through and managing each setting on a per-project basis could be cumbersome. Something like GitHub does with repository selection. 

![image](https://user-images.githubusercontent.com/5528307/171145845-26729886-8d5c-42e8-a107-8d142e132531.png)

**Comment by loujaybee** [comment]
Given some of the limitations of adding on a project level, I suggest starting with https://github.com/gitpod-io/gitpod/issues/8573, and implemented as an "ask me for all workspaces" would be a good point to start with getting movement on this. 

With the longer term solution looking like...

1. Global preference - Only one IDE always - as current
2. Ask me everytime - Allowing easier folks who swap more frequently (Use cases I've heard ard: bouncing between work/personal, for open-source folks, or for leveraging browser VS Code for "quick edit" type work)
3. Pin for project - Allow the user to pin an IDE preference on a per-project basis (this is not perfect, as not all repo’s are projects, but if you have #2 set, this mitigates that issue).

**Comment by huweiATgithub** [comment]
I think a per-project setting might make the most sense - a project has an IDE that fits it the best. 
For a repo having many components that require different IDEs, a better way might be to create multiple projects for the same repo.
Of course, there might be the case that a user wants to open the project in another IDE occasionally. 

Considering all these, it is good for a project to have the following radio button for choosing IDE:
- **follow user preference** - the default one
- **ask everytime** - for workspace started from this project, ask every time.
- **specific IDE** - start the selected IDE

In per-User preference, it could have the above options except **follow user preference**.

Regarding those workspaces which are not from a project, one can either modify the user preference (switch IDE or select **ask everytime**) or specify it through the link, e.g. https://gitpod.io/#referrer:jetbrains-gateway:intellij/https://github.com/gitpod-io/spring-petclinic.
The latter is even working now.

**Comment by loujaybee** [comment]
Adding additional user feedback: 

>  I am looking to configure a different Editor by project other than going to the setting and changing the editor before launching a new gitpod.   We use different editors depending on the project, for Go Projects we want to use GoLand, but for Java we use IntelliJ.  We don't have a preferred editor, we have a preferred editor depending on the project.

**Comment by mbrevoort** [comment]
Another option would be to combine of **Ask me every time** with select and  **Never ask again**, saving a per user, per project setting. However, we would need to show these settings somewhere for each user, allowing them to delete them (oops, how do I undo that?).

**Comment by gtsiolis** [comment]
The new start with options feature recently merged could help here, see https://github.com/gitpod-io/gitpod/pull/15389, https://github.com/gitpod-io/gitpod/pull/15567, and https://github.com/gitpod-io/gitpod/pull/15668. Cc @svenefftinge 

For example, you can now prompt users to select an editor and workspace class when opening a workspace for any repository, like `gitpod-io/gitpod`, by using the following URL:
> https://gitpod.io/?showOptions=true&editor=intellij#https://github.com/gitpod-io/gitpod

Using the default options can be done by only using the `showOptions` parameter.
> https://gitpod.io/?showOptions=true#https://github.com/gitpod-io/gitpod

---

In any case, although the workspace class selection makes sense in the project-scope where the setting has moved, I'm not sure if having the editor selection per-project is ideal as developers have strong opinions about their editor choice, dotfiles setup, etc. regardless the type of the project. Maybe if we allowed users to opt-out from the project setting and use their choice every time could help. Alternatively, I'd suggest improving the flexibility or ways to select a different editor. 💭

**Comment by loujaybee** [comment]
> I'm not sure if having the editor selection per-project is ideal as developers have strong opinions about their editor choice, dotfiles setup, etc. @gtsiolis 

Noting that for some users/customers having an IDE org wide policy is beneficial, see: 

- https://github.com/gitpod-io/gitpod/issues/11073
