### ISSUE TITLE
Minio Helm chart dependency no longer available (or is offline)

### ISSUE THREAD

**Issue by dtate-wave** [gitpod-io/gitpod#6876]
### Bug description

When running a `helm repo update`, the minio helm chart that is defined in `chart.yaml` is no longer available and returns a 404:
```
- name: minio
  version: 8.0.10
  repository: https://helm.min.io/
  condition: minio.enabled
```
May be related to https://github.com/gitpod-io/gitpod/issues/6284, where minio has deprecated this chart in favor for an operator-based chart.

### Steps to reproduce

```
$ helm dep update
Getting updates for unmanaged Helm repositories...
...Unable to get an update from the "https://helm.min.io/" chart repository:
	failed to fetch https://helm.min.io/index.yaml : 404 Not Found
```

### Expected behavior

`helm dep update` succeeds.

**Comment by MrSimonEmms** [comment]
Thanks for reporting this @dtate-wave. We'll schedule some time to switch it over.

As an aside, the [Installer](https://github.com/gitpod-io/gitpod/tree/main/installer) uses the [Bitnami version of this chart](https://github.com/bitnami/charts/tree/master/bitnami/minio) which is not deprecated and is a drop-in replacement for this chart
