### ISSUE TITLE
[code-insider] No view is registered with id: gitpod.workspace

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6887]
### Bug description

Start any workspace with VS Code insider. It seems not all Gitpod views are registered anymore.

### Steps to reproduce

See above.

**Comment by jeanp413** [comment]
Insider build is fixed now

**Comment by akosyakov** [comment]
@jeanp413 It's still hapenning.

**Comment by jeanp413** [comment]
It was(or is? taking a look again) because of the migration of proposed API https://github.com/microsoft/vscode/pull/137724
`enableProposedApi` is now deprecated and from now on extensions should use `enabledApiProposals`

**Comment by jeanp413** [comment]
Fixed it, I missed to include some proposed api for the remote view, the new approach to include proposed api is not really good as you need to ask one by one explicitly and it does not throw any error during compilation for apis that only require to update the package.json like the views api
