### ISSUE TITLE
Implement analytics on changes to the `.gitpod.yml`

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6894]
**Context:** This one is important as it will give us data around when a user is updating this file as part of their onboarding journey. e.g. are users updating the file on their first visit? second visit? etc

We would like to know: if / when a user is changing or updating their gitpod.yml. 

Ideally, we would gather fine-grained data on which properties the user is updating on the YAML file. This is so we can optimize how and when we present certain features to our users. 

Considerations: 
* We could possibly implement this via a keystroke event within VS Code, but we'll need to set a reasonable debounce/throttle on the event to ensure we do not send many events. 
* We will need to decide which attributes/aspects of the `gitpod.yml` that are interesting for us to track and why. 

**Note:** If necessary we can break this ticket down, simply knowing that the user has changed the file / added it would deliver value at this stage.

**Comment by filiptronicek** [comment]
@loujaybee this is a very interesting concept. I wonder if we could do more things on the client by just adding a tailored extension, which would take care of the whole `gitpod.yml` walkthrough process. This would mean nothing is sent back - good for our servers and also 0 latency. I imagine in this process there won't be too many features which we couldn't implement via an extension, but just a thought 💡!

**Comment by loujaybee** [comment]
This one is a little tricky, so probably best if @akosyakov is able to collaborate with whoever picks this up to come up with a plan. As with all of the analytics tickets, having something working initially is better than trying to overthink it, and come up with something super comprehensive.

**Comment by loujaybee** [comment]
There is potentially some tracking added here [[1](https://github.com/gitpod-io/gitpod/blob/da3991c94b08365b6de71b9337ee69a338b21dfc/components/supervisor/pkg/supervisor/supervisor.go#L1306)], let's investigate if we have that data, and if those events are working as expected.

**Comment by akosyakov** [comment]
> There is potentially some tracking added already here in the supervisor [1].

@jakobhero Could you check please whether we have `config-changed` in Segment, but which does not make to BigQuery for some reasons?

**Comment by jakobhero** [comment]
> whether we have config-changed in Segment, but which does not make to BigQuery for some reasons?

Hi @akosyakov, i had another look at the events coming into Segment and `config-changed` never makes it there. Also, the BigQuery destination is not configured to block any of the events. Are we sending the events to the source with the write key of [production trusted](https://app.segment.com/gitpod/sources/production_trusted/overview)?

**Comment by akosyakov** [comment]
I think it is configured here: https://github.com/gitpod-io/gitpod/blob/0851301c528287ad2a7b62deb40e0cb332585166/components/common-go/analytics/analytics.go#L42-L46 and sent here: https://github.com/gitpod-io/gitpod/blob/0851301c528287ad2a7b62deb40e0cb332585166/components/common-go/analytics/analytics.go#L92-L102

@csweichel Could it be that `GITPOD_ANALYTICS_WRITER` and `GITPOD_ANALYTICS_SEGMENT_KEY` not configured in production?

**Comment by jakobhero** [comment]
> Could it be that GITPOD_ANALYTICS_WRITER and GITPOD_ANALYTICS_SEGMENT_KEY not configured in production?

For what it's worth, dashboard and server side analytics calls also depend on the configuration of those as far as i know and they don't seem to be affected.

**Comment by akosyakov** [comment]
> For what it's worth, dashboard and server side analytics calls also depend on the configuration of those as far as i know and they don't seem to be affected.

yes, i see it in each workspace

**Comment by jeanp413** [comment]
@akosyakov are you working on this if not what still needs to be done?

**Comment by akosyakov** [comment]
@jeanp413 not actively

I wanted to sync with @csweichel with how generally we can get analytics directly from workspace to Segment in secure way. If it is not possible then the fix is rather simple, use GitpodServer in supervisor to track this event. You can make a PR for it, but we delay merging after talking to Chris.

**Comment by jeanp413** [comment]
@akosyakov is that related to this https://github.com/gitpod-io/gitpod/issues/7257#issuecomment-998117176. If so I'd be fine waiting as that would also help make straightforward sending telemetry in vscode core (instead of creating a web socket  connection)

**Comment by akosyakov** [comment]
@jeanp413 since we are fine to use untrusted, it would be good to investigate why supervisor cannot send to segment, we don't log any errors there to avoid spamming logs, but maybe it is good to enable them temporarily

**Comment by loujaybee** [comment]
Removing from scheduled as not a great deal we can do whilst we're waiting for visualisation dashboards to be created. 

Since I've now closed the following epic (which used to contain this ticket). I'll now move this out of groundwork. 
- https://github.com/gitpod-io/gitpod/issues/7326
