### ISSUE TITLE
Implement analytics on generic VS Code pop-up / toast notifications

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6895]
Currently, in VS Code we have a lot of pop-up notifications appearing, that have caused some frustrations / difficulties for users (as shown during usability). It would be useful information to see what users are going with regards to these pop-ups, which ones are users suppressing, when, and why? This ticket is to implement tracking events on the pop-up notifications. Some notifications include CTA's as well as dismissals, we should try to gather metrics on both of these (if possible). 

![image](https://user-images.githubusercontent.com/5528307/143438067-e8c6fbb4-c5ae-4c96-a644-3d537ed715ab.png)

**Comment by loujaybee** [comment]
@akosyakov noted some challenges: 

* This might only work on web, not on desktop. 
* This might be easiest / only possible for our own extensions 

Both of these are fine as a first iteration if we cannot get data on the other pop-ups.

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/openvscode-server/pull/257

**Comment by jeanp413** [comment]
From vscode telemetry:
- event name `notification:show` logs id (number) and source (`core`, extension id)
- event name `notification:close` logs id (number) and source (`core`, extension id)
- event name `notification:hide` logs id (number) and source (`core`, extension id)
- event name `notification:actionExecuted` logs id (number), source (`core`, extension id) and `actionLabel`

**Comment by loujaybee** [comment]
I've updated the title for this to be only the "generic" popup events. @akosyakov mentioned it might be useful to track our actual extensions, and have more specific events, however for now/this issue, let's only track the generic ones.

**Comment by akosyakov** [comment]
closing and moving into awaiting deployment since it is not in stable yer
