### ISSUE TITLE
None of my repositories are working

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#690]
Hello! We woke up this morning (Miami) to see that none of the repositories are working on gitpod, the initialization gets stuck at `Initializing workspace (1/3)` or 3/3 some other times.
![Screen Shot 2019-07-22 at 11 36 32 AM](https://user-images.githubusercontent.com/426452/61645601-f8b05400-ac74-11e9-9ff6-df04d4ff727b.png)

@jankeromnes

**Comment by jankeromnes** [comment]
Oh oh, this doesn't sound good. 😐 Thanks for reporting!

My initial suspicion is that it may be related to GitHub's current incident: https://www.githubstatus.com/

**Comment by alesanchezr** [comment]
Ok yes, confirmed. Now I can't even see the repository page anymore. 😭

**Comment by jankeromnes** [comment]
Thanks for confirming! Our thoughts are with the GitHub incident response team.

We're also investigating this issue from our side, to make sure that everything looks right / can recover quickly.

**Comment by jankeromnes** [comment]
@alesanchezr this should hopefully be resolved now. Please confirm that everything is working again. 🙂

**Comment by alesanchezr** [comment]
yes it is, thanks @jankeromnes 😀

**Comment by svenefftinge** [comment]
see https://github.com/gitpod-io/gitpod/issues/691
