### ISSUE TITLE
Epic(experiment): Allow creating a new repository from within the IDE

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#6904]
It would be cool to have a quick & convenient way to create a new repository from inside the IDE.

This would play particularly well when combined with this other feature request: https://github.com/gitpod-io/gitpod/issues/6903, as opening a workspace based on an archive will give you a workspace without any repository (i.e. no `git init` was run).

Maybe the IDE could even detect that you currently don't have a repository, and proactively propose that you create one (either immediately, or if you try to push). I imagine that it could simply prompt the user for a repository name, and then automatically initialize the local repository & create the remote repository.

Alternatively, maybe there are already good VS Code extensions to accomplish this (e.g. maybe the GitHub and GitLab extensions we already have can do that?). Then it would just be a matter of making sure they are installed by default and pre-authenticated in Gitpod.

**Comment by akosyakov** [comment]
Also a user can go to GitHub create a repo and follow GH guidance as he will do on local machine? Should not we ship rather than `gh` cli instead: https://cli.github.com/manual/gh_repo_create

**Comment by akosyakov** [comment]
Actually VS Code already have something built-in:
- if you don't have git repo yet:
<img width="1904" alt="Screenshot 2021-11-26 at 10 22 45" src="https://user-images.githubusercontent.com/3082655/143557698-3d8a4963-c0ff-4b1d-b7d7-6684660ce7bb.png">
<img width="1904" alt="Screenshot 2021-11-26 at 10 22 55" src="https://user-images.githubusercontent.com/3082655/143557717-d637366b-927c-4d9b-8861-0ffce9ff1340.png">

- if you have repo and try to push:
<img width="511" alt="Screenshot 2021-11-26 at 10 23 21" src="https://user-images.githubusercontent.com/3082655/143557715-a5551d68-6807-4e84-842d-3a21e13c8bae.png">
<img width="932" alt="Screenshot 2021-11-26 at 10 23 25" src="https://user-images.githubusercontent.com/3082655/143557714-bdd34429-904d-447f-9ee6-85fb8855e86a.png">

**Comment by akosyakov** [comment]
For GitLab though. We will need to enhance built-in git vscode extension.

**Comment by loujaybee** [comment]
Thanks for raising @jankeromnes ! 

This feels a little like we're solving a problem we think users will have. I agree with @akosyakov here that there are ways to do this within VS Code (if the user is versed) or via the old-school terminal approach. 

I think it's best to proceed with this issue by lifting the restriction around requiring a repo to clone, and then assess if users do struggle with this repo set up before implementing a solution.
