### ISSUE TITLE
Attach workspace ID to all IDE analytics events

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6905]
Currently, it's hard to see what's going on within users sessions, as we can not distinguish whether events occur as part of the same "session" or not. This issue is to add workspace ID's to all IDE generated events. In a workspace context, the workspace ID serves as a good proxy for a session.

**Comment by akosyakov** [comment]
Hm, are you sure that we don't have it. In code it looks like all events in VS Code already have it.

**Comment by loujaybee** [comment]
Yep, I think this was a mistake, will close 🙏
