### ISSUE TITLE
Allow whitelisting github profiles for prof open-source

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#6918]
We'd like to proactively whitelist open-source developers, so that when they sign up they are already on the professional open-source plan. The list would probably grow to max 50k entries. It should be enough to update the list through code PRs and deployments. So can be either DB migrations or in-memory (haven't done the math). This should also work for existing sign-ups so I guess we'd basically need to check the list whenever a user logs in.

cc @ghuntley please add context if you like.

**Comment by ghuntley** [comment]
Hey @gitpod-io/engineering-meta. I need your help with getting this shipped by the 13th and am looking for a volunteer to own the technical implementation so I can focus on the community side of things.

Meta responsibilities:

1. Gitpod will have a whitelist of open-source maintainers (Geoff to supply the list) in the form of GitHub handles.
1. Gitpod will automatically upgrade the user's plan to the professional opensource if the GitHub handle is a match.

Geoff's responsibilities:

1. Sending in a commit with the full dataset onto meta's pull-request when the PR is ready for review.

Thanks 🧡

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6918#issuecomment-988617971):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
> So can be either DB migrations or in-memory (haven't done the math).

IMO we should try to keep PII (GitHub handles/profile ids) out of the source code. Either we use a file (ConfigMap) that we regularly poll and keep in memory, or a DB table that we update by hands at first, maybe with a simple view later.

**Comment by ghuntley** [comment]
> Either we use a file (ConfigMap) that we regularly poll and keep in memory

ConfigMap/File means changes go through pull-request reviews which is very desirable. Can we head down this route?

**Comment by geropl** [comment]
> ConfigMap/File means changes go through pull-request reviews which is very desirable. Can we head down this route?

I did go with a DB approach because it better fits how we use DB (all data, and PII) and ConfigMaps (just one, for genereal configuration). A ConfigMap is a somewhat strange extension point (with edge cases for SH), and would mean we'd need to either a) rollout each time we want to update that list or b), poll the filesystem (which recently showed to be slowing `server`s down).

**Comment by geropl** [comment]
@ghuntley The "input format" now would be a list of GitHub profile names a la:

```
github.com/geropl
github.com/ghuntley
....
```
That we turn into an `INSERT` (manually for now) and execute that against the DB.

The change did not land today, sadly, but I'm inclined to deploy it tomorrow morning (if there's no strong votum against it, and there's enough motivation to do so). Thursday at latest, that's our next regular deployment.

If you share the list of handles I can also insert them after deployment. :+1:

**Comment by ghuntley** [comment]
Thank you Gero!
