### ISSUE TITLE
remove logging of bearer token from reconnecting websocket 

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#6919]
### Bug description

Right now they are logged as a part of https://github.com/gitpod-io/gitpod/blob/d86242978d0a23efeac7d6c7e5fe6b97d0e69c9f/components/gitpod-protocol/go/reconnecting-ws.go#L221

### Steps to reproduce

See above.

**Comment by corneliusludmann** [comment]
@akosyakov Do we need the header in the logs at all? Could we remove it entirely? Or should we just remove the bearer token from the header?

**Comment by akosyakov** [comment]
I think we should remove it.

@aledbf i think you added it, do you know which info is interesting?
