### ISSUE TITLE
Always Infer `.gitpod.yml`

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#6921]
Since we now have the possibility to infer a `.gitpod.yml` and start a workspace with it so that the derived config file is added to the workspace's project folder. I think we can do this always if there is no `.gitpod.yml`.

see also #6922

**Comment by jankeromnes** [comment]
On second thought, it's probably a bit too early to put this into Groundwork.

Let's revisit this in a few weeks.
