### ISSUE TITLE
Docker Images not being built after merge back to master

### ISSUE THREAD

**Issue by j0nes2k** [gitpod-io/gitpod#6927]
### Bug description

When making changes to the gitpod.Dockerfile in branches, docker containers are being built for each change in this file. When merging this branch back to master, the docker containers are not being built on master. 

We are using a hosted environment on gitlab.com, if that makes a difference.

### Steps to reproduce

- create new branch from master
- change something in `.gitpod.Dockerfile`, e.g. install something globally
- (docker builds are being run on this branch, everything is fine)
- merge back this branch to master

- expected result: changes are available in subsequent workspaces based on master (e.g. installed tools from Dockerfile are usable)
- actual results: the docker build does not get build, therefore the installed tools from Dockerfile are not available

### Workspace affected

Example: crimson-guan-qoy0luua

**Comment by jldec** [comment]
Hi @j0nes2k
We have not been able to reproduce this. When you merge a branch with a Dockerfile change, the commit on the default (master/main) branch should trigger a new prebuild AND a new docker build before that.
  
Would you mind sharing your Dockerfile and .gitpod.yml (or even better, a public repo reproducing the issue) so that we can investigate further?

Thanks

**Comment by j0nes2k** [comment]
I have tried to reproduce this issue, but I am already running into errors trying to create a setup. Here is the public repository where I tried to reproduce as much as of our work setup as possible. 

https://gitlab.com/j0nes2k/gitpod-issue-6927/-/tree/main/

You can find two branches - `main` and `feature/add_phrase_via_brew`. When merging back the feature branch to main, the Docker image for use on Gitpod was not built, resulting in the `phrase` command not being installed on new workspaces on `main`. I have not merged back yet though.

Now I am not sure if I am running into another issue or if I am doing something wrong: here is the output of the Gitpod log when building on `main` - note that this kept on failing, even when adding the missing files as you can see in the repo. A build on the feature branch is just running and seems to be working fine so far. 

```
Connecting to workspace logs...
Connecting to log output ...
Connected to log output ...
{
sudo -E /app/bob build
}; exit
bash-5.1$ {
> sudo -E /app/bob build
> }; exit
{"level":"debug","message":"buildkitd started","serviceContext":{"service":"bob","version":""},"severity":"DEBUG","stderr":"/tmp/buildkitd_stderr3151744323","stdout":"/tmp/buildkitd_stdout3982921918","time":"2021-12-09T16:24:45Z"}
{"attempt":0,"level":"debug","message":"attempting to connect to buildkitd","serviceContext":{"service":"bob","version":""},"severity":"DEBUG","time":"2021-12-09T16:24:45Z"}
{"attempt":1,"level":"debug","message":"attempting to connect to buildkitd","serviceContext":{"service":"bob","version":""},"severity":"DEBUG","time":"2021-12-09T16:24:46Z"}
{"level":"info","message":"building base image","serviceContext":{"service":"bob","version":""},"severity":"INFO","time":"2021-12-09T16:24:46Z"}
{"level":"info","message":"waiting for build context","serviceContext":{"service":"bob","version":""},"severity":"INFO","time":"2021-12-09T16:24:46Z"}
#1 [internal] load build definition from .gitpod.Dockerfile
#1 transferring dockerfile:
#1 transferring dockerfile: 5.18kB 0.0s done
#1 DONE 0.4s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.3s

#3 [internal] load metadata for docker.io/gitpod/workspace-full-vnc:latest
#3 DONE 1.6s

#6 [internal] load build context
#6 DONE 0.0s

#4 [ 1/10] FROM docker.io/gitpod/workspace-full-vnc@sha256:34483c92a47baa16213a873446dfdd0bb900967d9ac455bd0409de699bb7816c
#4 resolve docker.io/gitpod/workspace-full-vnc@sha256:34483c92a47baa16213a873446dfdd0bb900967d9ac455bd0409de699bb7816c 0.1s done
#4 CACHED

#6 [internal] load build context
#6 transferring context: 29B done
#6 DONE 0.9s

#5 [ 2/10] RUN apt-get -yq update     && apt-get -yq install mysql-server     && mkdir -p /var/run/mysqld /var/log/mysql     && chown -R gitpod:gitpod /etc/mysql /var/run/mysqld /var/log/mysql /var/lib/mysql /var/lib/mysql-files /var/lib/mysql-keyring /var/lib/mysql-upgrade
#5 CACHED

#7 [ 3/10] COPY .gitpod/image/mysql.cnf /etc/mysql/mysql.conf.d/mysqld.cnf
#7 ERROR: "/.gitpod/image/mysql.cnf": not found

#9 [ 5/10] COPY .gitpod/image/mysql-bashrc-launch.sh /etc/mysql/mysql-bashrc-launch.sh
#9 ERROR: "/.gitpod/image/mysql-bashrc-launch.sh": not found

#8 [ 4/10] COPY .gitpod/image/client.cnf /etc/mysql/mysql.conf.d/client.cnf
#8 ERROR: "/.gitpod/image/client.cnf": not found

#4 [ 1/10] FROM docker.io/gitpod/workspace-full-vnc@sha256:34483c92a47baa16213a873446dfdd0bb900967d9ac455bd0409de699bb7816c
#4 DONE 15.5s
------
 > [ 3/10] COPY .gitpod/image/mysql.cnf /etc/mysql/mysql.conf.d/mysqld.cnf:
------
------
 > [ 4/10] COPY .gitpod/image/client.cnf /etc/mysql/mysql.conf.d/client.cnf:
------
------
 > [ 5/10] COPY .gitpod/image/mysql-bashrc-launch.sh /etc/mysql/mysql-bashrc-launch.sh:
------
.gitpod.Dockerfile:15
--------------------
  13 |     # Install default-login for MySQL clients
  14 |     COPY .gitpod/image/client.cnf /etc/mysql/mysql.conf.d/client.cnf
  15 | >>> COPY .gitpod/image/mysql-bashrc-launch.sh /etc/mysql/mysql-bashrc-launch.sh
  16 |     RUN echo "sh /etc/mysql/mysql-bashrc-launch.sh" >> ~/.bashrc
  17 |     
--------------------
error: failed to solve: failed to compute cache key: "/.gitpod/image/mysql-bashrc-launch.sh": not found
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","command":"build","error":"exit status 1","level":"error","message":"build failed","serviceContext":{"service":"bob","version":""},"severity":"ERROR","time":"2021-12-09T16:25:05Z"}
exit
exit

Error: headless task failed: exit status 1
```


Please let me know if you need any additional information. I will also keep you updated when I merged this branch back and let you know about the results.
