### ISSUE TITLE
Possible to start Gitpod with our DSL?

### ISSUE THREAD

**Issue by DamianRivas** [gitpod-io/gitpod#693]
Hi,

We wrote a DSL, a language server for it, and a sprotty extension for Theia. Is it possible to start a Gitpod workspace with our extension and language server running? It would be great if our developers could start up a Gitpod session and go straight to working with our dsl with no set up on their part.

Thank you,
Damian

**Comment by svenefftinge** [comment]
Hi Damian, if it is a VS Code extension (probably not because it's quite hard to integrate Sprotty there) you can soon install it your workspaces. If it is a Theia extension, then you would need to have your own gitpod instance, which we could provide you.

**Comment by svenefftinge** [comment]
Either ways are possible and we would be happy to help get this working.

**Comment by DamianRivas** [comment]
Hi Sven, that sounds great! We only have a Theia extension. What do I need to do?

**Comment by melaasar** [comment]
Hi Sven. We actually also have a VS extension, but only with the textual editor, no diagrams yet.

**Comment by svenefftinge** [comment]
Installing Theia extensions is supported in Gitpod Business, only. I'd be happy to send you a quote for that (my email is sven.efftinge@typefox.io).

**Comment by melaasar** [comment]
@svenefftinge This is good news. You mentioned above that Sprotty diagrams are not possible in VS Code yet. Is this in progress?

**Comment by svenefftinge** [comment]
VS Code extensions are very limiting when it comes to rich views. I guess one can hack something together using their web views and AFAIK @JanKoehnlein did a prototype for that. Not sure what the current state is there, though.

**Comment by JanKoehnlein** [comment]
There is a prototype at https://github.com/TypeFox/sprotty-vscode
