### ISSUE TITLE
Struggling to turn making port private on and off

### ISSUE THREAD

**Issue by codemzy** [gitpod-io/gitpod#6930]
### Bug description

Sometimes I need to make a port public just for a short time, the only way I have found to do this (once the port has been exposed after the first time and the pop-up in the bottom right doesn't appear anymore) is the little padlock symbol next to the port. Clicking it off and on rarely works for me, it will just stay the same status. And sometime it will say it's public but it will still be private (trying to access the url in an incognito window gives 401).

I've tried this in a couple of different workspaces and get the same issue.

### Steps to reproduce

Expose a port and try to toggle private on and off with the padlock icon.

### Expected behavior

I would expect the toggle to be more reliable :grim

### Anything else?

Thanks for an amazing service!

**Comment by csweichel** [comment]
May be related to https://github.com/gitpod-io/gitpod/issues/6778
Looks like the `openPort` request does not always succeed.
