### ISSUE TITLE
Closing workspace UX seems to be broken

### ISSUE THREAD

**Issue by codemzy** [gitpod-io/gitpod#6931]
### Bug description

For the last week or so, closing a workspace seems to be buggy, sometimes, the status page that comes up will say something like 'Starting workspace' when it's actually closing it. And if I go to my workspace dashboard it will say it has stopped running but that workspace status page won't update to 'stopping' or 'stopped' like it used to.

### Steps to reproduce

Close a workspace using the gitpod button then 'Stop workspace'.

### Expected behavior

The flow that used to happen where it would display a page that says 'stopping' and then 'stopped'. I think this still does sometimes happen, but often I get no status page or the initialising one instead.

### Anything else?

Gitpod is awesome 😎

**Comment by gtsiolis** [comment]
I could reproduce this when using network throttling. Cc @shaal 

https://user-images.githubusercontent.com/120486/144283976-f41b302d-f074-42bc-8563-c0a269c94340.mov

g

**Comment by shaal** [comment]
Thank you, and yes - that's what I'm seeing.
Last few days - Close Workspace, became slow / unpredicted.

**Comment by akosyakov** [comment]
should be fixed by https://github.com/gitpod-io/gitpod/pull/7621
