### ISSUE TITLE
[Self-hosted]: cannot search users/workspaces without enterprise license and error is console only

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6932]
### Bug description

When I go to `/admin/users` in my self-hosted instance and click "search", I'm not able to search without an enterprise license. Whilst this is fine, the error only appears in the console.

It would be nice to have the error in the actual dashboard - an alert-style error

![image](https://user-images.githubusercontent.com/275848/143614298-4d311531-147e-452a-8dc0-1a17b1210a07.png)

### Steps to reproduce

Install self-hosted, go to admin and click "search"

### Expected behavior

Should display the "enterprise license required" in the dashboard, not just the console

**Comment by JanKoehnlein** [comment]
@jldec Shouldn't we rather disable the `admin` routes for non enterprise installs?

**Comment by jldec** [comment]
Either way works - a visible nudge can help to make users aware that they need a license :)

Silent browser console errors should be treated more like bugs. It would be helpful from an operations perspective if we had a way to collect those, just like server-side logs.

**Comment by laushinka** [comment]
Initially I would go for removing the Admin tab from non-enterprise users, but a visible nudge also makes sense.
How about showing a disabled Admin tab with a locked icon, and a tooltip saying that it's only for Professional users? Probably there are better ideas, but something along this line?

**Comment by jldec** [comment]
Note discussion in #8328 

could render this issue moot:  
> I would suggest that the admin dashboard is enabled for all license levels. This will allow us to put useful things in here in future

Even if we do keep limiting the use of the admin dashboard, the check should allow evaluation use when there are < 10 users.

**Comment by MrSimonEmms** [comment]
As part of #8593, I've made the admin dashboard available to all licence levels. Once accepted, I think that solves this ticket
