### ISSUE TITLE
Adding Atom as One of the Available Editor Choices for Gitpod

### ISSUE THREAD

**Issue by UnrealApex** [gitpod-io/gitpod#6934]
It would be nice if Atom could be one of the editor choices for Gitpod.

**Comment by pawlean** [comment]
> It would be nice if Atom could be one of the editor choices for Gitpod. 

Thanks for the feature request!

I don't think we'll be supporting Atom any time soon, but we appreciate your feedback and support. 

FWIW, you might want to check out what else is coming up for Gitpod support [here](https://www.gitpod.io/docs/editors).

**Comment by akosyakov** [comment]
@UnrealApex as far as I know atom does not have support for remote development like VS Code. I can only imagine that you use sftp to mount filsystem locally and work on it. You can already achieve it via the local companion: https://www.gitpod.io/blog/local-app
