### ISSUE TITLE
Request registerGithubApp failed with message: ER_DUP_ENTRY: Duplicate entry 'github-20960233-claimed.user' for key 'PRIMARY'

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#6939]
### Bug description

Request registerGithubApp failed with message: ER_DUP_ENTRY: Duplicate entry 'github-20960233-claimed.user' for key 'PRIMARY'

### Steps to reproduce

1. Created new GitHub Org (securitytxt)
2. Installed Gitpod app into securitytxt
3. This happend

<img width="1151" alt="2021-11-27_21-18-16" src="https://user-images.githubusercontent.com/127353/143679042-19abb44d-541e-4d00-b6d3-3431af75f800.png">

**Comment by JanKoehnlein** [comment]
Dupe of #6421
