### ISSUE TITLE
React

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#694]
Hi! A couple questions regarding React- is it possible to add .js files to be used with emmet? Also, can extensions, such as react snippets, be used currently, or in the works?

**Comment by svenefftinge** [comment]
Adding Vs Code extensions is going to be released in a couple of days already. That release will include emmet support as well.

**Comment by akosyakov** [comment]
@ColbyWTaylor We reuse vscode emmet extension. You will need to open a feature request for vscode. Right now it is only possible in `jsx` and `tsx` files.
