### ISSUE TITLE
.NET Core "blazor server" project exits on debugging

### ISSUE THREAD

**Issue by bxthomas** [gitpod-io/gitpod#6950]
### Bug description

Using a basic blazorserver project created with the command "dotnet new blazorserver" and with the standard .NET 6 .gitpod.Dockerfile and .gitpod.yml added to the project, everything works correctly except for when launching with VS Code's inbuilt debugging.  The debugging proceeds as normally until "app.Run" and then the process exits.  Note that launching the process from the terminal and then attaching to the process does allow debugging.  Launching the same program for debugging from a local VS Code works correctly.

### Steps to reproduce

Create a new .NET Core project using "dotnet new blazorserver"
Add .gitpod.Dockerfile and .gitpod.yml
Push to new git repository
Launch a gitpod workspace against this repository
Note that the c# extension will fail to install properly.  Refresh the page and note the extension loads properly
Go to the debugging tab and press the run button
Allow the c# extension to autocreate the launch.json and task.json files
Note how the program starts and soon after exits

### Workspace affected

amber-sturgeon-8ndnupkn

**Comment by ghuntley** [comment]
👋 @bxthomas have you applied the workarounds at https://github.com/gitpod-io/gitpod/issues/5090#issuecomment-981054892? By the end of the week you won't need them but for now it's needed.

**Comment by aledbf** [comment]
Closing. We are now 100% out of GKE. So this is not an issue anymore.
No workaround is needed.

**Comment by bxthomas** [comment]
@aledbf , I tried again with (what I think is the new version of gitpod) but the behavior is identical :-(

https://lavender-rabbit-m7uwq2t4.ws-us21.gitpod.io/
