### ISSUE TITLE
Enable ephemeral storage limits

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#6956]
Enable ephemeral storage limits using XFS and `LocalStorageCapacityIsolationFSQuotaMonitoring` feature gate. See [here](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-emphemeralstorage-measurement-1) for more details.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/6956#issuecomment-981897509):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
