### ISSUE TITLE
[openvsx-proxy] Remove `/debug/vars` endpoint

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#6957]
The OpenVSX proxy exposes the endpoint `/debug/vars`. It seems that the `expvar` package that is used by the Prometheus go client library automatically exposes this [[1](https://groups.google.com/g/golang-codereviews/c/RSef7RQq9F4), [2](https://github.com/dgraph-io/badger/issues/1002)].

In production, we currently prevent exposing this endpoint via the load balancer. However, on the long term, it would be good to solve this in the OpenVSX proxy component. That means, we shouldn't use the default HTTP mux as we do this in the `registry-facade`: https://github.com/gitpod-io/gitpod/blob/915cd416d223cbc353f0ae98cecfae35c4cedb1f/components/registry-facade/pkg/registry/registry.go#L230-L233

**Further discussions (internal):** [slack](https://gitpod.slack.com/archives/C01LDA29VTJ/p1637853563003300), https://github.com/gitpod-io/security/issues/16

**Priority:** Rather low since we mitigated this in production with the [load balancer changes](https://github.com/gitpod-io/ops/pull/358) already.

**Comment by akosyakov** [comment]
Does it go away if we put OpeVSX Proxy behind caddy proxy eventually? i.e. we could prohibit debug endpoint there?
