### ISSUE TITLE
`code new-file` no longer creates a new file and opens an editor

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#6965]
I as a user expect `code new-file` to create `new-file` and open an editor on it like it did in the past.

![image](https://user-images.githubusercontent.com/32448529/143904462-8b027bb6-8269-4c70-a497-04a3663fb08a.png)

**Comment by jeanp413** [comment]
Took a look and it seems it's a regression from this PR https://github.com/microsoft/vscode/pull/136359
Will create an issue upstream later today maybe with fix

**Comment by jeanp413** [comment]
This is already fixed upstream https://github.com/microsoft/vscode/commit/950423beced7ceb28062c7377c8271bbfd54b762
Should be fixed in tomorrow's insiders.

**Comment by akosyakov** [comment]
verified it works in Insiders.
