### ISSUE TITLE
Rearrange `/new` team page to make "option" between personal/team more prominent

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6969]
Currently, when creating a project via the `/new` flow, the user is given a choice about whether to create a new team or not. 

Findings from usability testing: 
* Users are not aware that this page is a choice (most did not notice/find the personal project option)
* Users are not aware of the benefits that a team brings them
* Users are entering arbitrary / random team names to "speed up" the step

It seems like we could land some quick usability wins by restructuring this page...

### Current

![image](https://user-images.githubusercontent.com/5528307/143923518-334fe611-5f76-4bd8-9ca7-5eb67c523d87.png)

### Proposed

**Disclaimer:** Intentionally low-fidelity / crude. Suggestions are more about the structure / UX than the UI. 

![image](https://user-images.githubusercontent.com/5528307/143923445-0e57f0a2-5e85-465f-8e12-aabb9fcdd29f.png)

**Comment by gtsiolis** [comment]
Thanks for opening this and providing the low-fidelity mockup, @loujaybee!

FYI, we're currently working on updating this page in https://github.com/gitpod-io/gitpod/issues/6686. Posting below an early draft in case it helps that is also using familiar patterns and components across the product. Feedback is welcome. Cc @jankeromnes @jldec 

| Early draft for team selection designs |
|-|
| <img width="1008" alt="Frame 352" src="https://user-images.githubusercontent.com/120486/143929149-bb38898a-6618-4396-a4be-8680b7254187.png"> |

Benefits of the above design proposal:
1. Making it easier and more obvious you can select the personal account
2. Toning down a bit the option to create a team
3. Improving visual and accessibility design for selecting an option
4. Reusing the item component as this pattern is used elsewhere (see parallel workspaces modal, etc)

**Comment by loujaybee** [comment]
@gtsiolis ! Thanks so much for iterating on the design 🙏 Yeah 100% I tried to deliberately make the mock up low(er) fidelity (on reflection: using hand-drawn UI components would make this distinction clearer). 

The mockup you provided does meet most of my original ideas / thoughts 🚀

One area that it doesn't meet though, is that we're still not providing any context to the user about _why_ they should create a team (i.e what's in it for the user). And I have a hunch (based on sitting in on the user tests) that very few users will follow that flow if they don't have an incentive or reason to do so (I'm happy to test this and adjust based on data). 

Note: I think it's okay if we want to nudge users towards creating a team, provided that the user has a clear fall-back option (for attaching the project to their personal account). I think whichever choice is the default on this screen should be considered closely, as it will bias/influence the choice that users make.

**Comment by jldec** [comment]
Most of this was addressed in #6686 - removed from Groundwork but keeping in backlog for future reference.

**Comment by jldec** [comment]
Closing this since /new project users are far less exposed to team creation now.

I would suggest adding further comments or tracking the "Team Creation" UX in #4951
