### ISSUE TITLE
blocked

### ISSUE THREAD

**Issue by goalachiever56** [gitpod-io/gitpod#698]
I got blocked out after not using it for a while, what is happening ?

**Comment by meysholdt** [comment]
hi! You were involved in an incident related to sending spam from Gitpod. I reached out to you via email when the block was installed. 

It's important to understand that Gitpod is for developing software: Read code, write code, run your code, test it, demo it to friends, colleagues and customers, etc. Sending spam from our platform is a violation of our [Terms of Services](https://www.gitpod.io/terms) and we can not allow it. See the "Fair Use" clause.

To continue the conversation please respond to my email. If you want to use Gitpod for software development I'm happy to unblock your account.
