### ISSUE TITLE
Add analytics to understand user-based configurations

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6980]
This ticket is to track the configurations a user might make to their own editor when they get set up. This is interesting as we'll be able to see:

* Do users bounce before installing extensions? 
* Do users realise they can configure their environment? 
* Can the users find all the extensions that they want/need?

## User settings (settings.json)

This covers things like: fonts, themes, etc. 

## Extensions

Currently, we're able to see the delta between Open VSX extensions and the MS marketplace extensions. To better prioritise our efforts around stabilising the publishing of VS Code plugins, we need better analytics / data on which extensions Gitpod users are requesting, and how frequently these extensions are failing / not available. 

Some suggestions on where we could gather this data from: 

1. Any requests which return 4XX when requesting an extension
2. A modification to the VS Code UI where a user can report "their extension is missing"
3. Any changes to a `.gitpod.yml` that reference an extension that is not supported (this might duplicate with bullet 1)

**Comment by loujaybee** [comment]
@filiptronicek, @jeanp413, @akosyakov, @corneliusludmann do you have thoughts you can add here? How possible are the above data points to gather? Are there any solutions I'm overlooking?

**Comment by akosyakov** [comment]
Maybe we can instrument OpenVSX proxy instead to analyze query requests? The thing is that OpenVSX is not complete, i.e. we have extensions in the service account which are still not published because of build failure, but they are popular in MS marketplace like `vsciot-vscode.vscode-arduino`. I think we would like to know whether even user tried to search for extension.

**Comment by akosyakov** [comment]
> A modification to the VS Code UI where a user can report "their extension is missing"

Sounds like https://github.com/gitpod-io/gitpod/issues/5601.

**Comment by jeanp413** [comment]
From vscode telemetry:
- event name `updateConfiguration` logs all setting ids from the user but not their values
- event name `settingsEditor.settingModified` logs the setting id modified by the user but not the value
- event name `extensionGallery:install ` logs extension id
- event name `galleryService:downloadVSIX` logs extension id
- event name `extensionGallery:openExtension` logs extension id when user clicks on extension in extension viewlet
- event name `extensionGallery:uninstall` logs extension id
- event name `galleryService:query ` logs info about request (status code, count, requestBodySize, etc)

**Comment by akosyakov** [comment]
closing and moving into awaiting deployment since it is not in stable yer
