### ISSUE TITLE
Implement analytics on file opening events in VS Code

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#6981]
As part of onboarding, we need events that define when a user has achieved recognition of the "read-only" aspects of Gitpod. A reasonable heuristic at this point would be to see if the user has interacted with the directory structure and/or the file system. This ticket is to instrument these events within VSCode to see when a user has opened a workspace and explored the internal file structures. 

This metric is a candidate for an "end" point of the user onboarding funnel. However, https://github.com/gitpod-io/gitpod/issues/6896, would be a stronger metric for the onboarding funnel, however, this metric would be useful as a fallback for #6896 if we find that tracking commits prove to be challenging.

**Comment by loujaybee** [comment]
@akosyakov will update here with some more thoughts/notes on a technical solution.

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/openvscode-server/pull/257

**Comment by jeanp413** [comment]
From vscode telemetry:
- event name `activityBarAction` logs viewlet Id and whether it is shown or hidden
- event name `workbenchActionExecuted` logs command id (`workbench.files.openFile`, `workbench.action.files.save`) and context (`explorer`, `keybinding`)
- event name `editorOpened` logs mime type, scheme, file extension 
- event name `fileGet` logs mime type and file extension
- event name `filePUT` logs mime type and file extension

**Comment by loujaybee** [comment]
Hey @jeanp413! Looks like we are thinking pretty much the the same thing [[1](https://github.com/gitpod-io/openvscode-server/pull/257#issuecomment-994405752)]. 

The events you suggest are pretty much the same ones I suggested on the telemetry PR. But... I didn't manage to initiate/see the `editorOpened` event. I think those events you suggested make sense, let's go ahead with those, and convert them into analytics requests [[1](https://github.com/gitpod-io/openvscode-server/blob/gp-code/main/extensions/gitpod-shared/src/analytics.ts)]

We'll need to find a mechanism to throttle / debounce the very frequent events though, like `fileGet/filePut`

**Comment by loujaybee** [comment]
Let's consider this ticket done, and we can see where file events might be relevant in relation to the other epic: #7326

**Comment by akosyakov** [comment]
@loujaybee next VS Code stable release will be only in Feb, if you need it early please ask @jeanp413 to cherry pick changes into release branch and do a proper release.

**Comment by akosyakov** [comment]
I'm cloing it, but keep in awaitting deployment since it is not in stable.
