### ISSUE TITLE
Google Deep Learning Container fail in Gitpod Layer

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#699]
see https://cloud.google.com/blog/products/ai-machine-learning/introducing-deep-learning-containers-consistent-and-portable-environments

reported here: https://spectrum.chat/gitpod/general/gcp-deep-learning-containers~7b262686-d905-4183-ba82-b3f10d349493

**Comment by JesterOrNot** [comment]
this is also being addressed in #813, should this issue be closed?
