### ISSUE TITLE
Gist support

### ISSUE THREAD

**Issue by coolreader18** [gitpod-io/gitpod#70]
It'd be cool if gitpod had gist support; as far as I can tell it currently doesn't. Prefixing a gist.github.com url with `gitpod.io#` brings you to a page with the error message "username/xxxxxxxxxxxxx could not be found!"

Thanks!

**Comment by bitsnaps** [comment]
If this feature is not possible to implement, consider [converting a github gist to repo](https://gist.github.com/ishu3101/830b556b487de5d69690) then push it to a Gitpod.
I'm not sure what would be the best possible way to automate this action though!
