### ISSUE TITLE
Can not open gitpod for a repository on github

### ISSUE THREAD

**Issue by pynickle** [gitpod-io/gitpod#700]
l try to open my repository on github. But it did not work, it just shows just like the picture shows. How can l solve this problem?
![ACB83429-28BB-44FC-B68F-FB3CD2EB735E](https://user-images.githubusercontent.com/47242104/61989042-4dc8dd00-b05c-11e9-9a85-d17a9c5a71a8.jpeg)

**Comment by pynickle** [comment]
l try on both computer and iPad, others’ repo and mine. None is ok.

**Comment by meysholdt** [comment]
Your profile says you are from China. Maybe you are affected by this bug? https://github.com/gitpod-io/gitpod/issues/672 You could verify this by using your web browser's debug tools to see if all http-requests succeed.

In case your repo is a public repo, you could let us know its name and we can check is there if there is anything else causing trouble.

**Comment by pynickle** [comment]
Yes, l am from China. l also find bundle.js not loaded by using my web browser's debug tools like issue#672.

**Comment by pynickle** [comment]
Thank you very much for help. l have solved my problem by using vpn.
