### ISSUE TITLE
Prompt users to create a new team when adding a repository from an non-personal account

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7008]
### Problem to solve

Currently, when going through `/new` prompt users to select a team after selecting a repository. We recently removed this prompt when a user is trying to add a repository from the personal account, see https://github.com/gitpod-io/gitpod/pull/6966. 

However, a) creating a team for repositories from personal accounts does not sound helpful and b) users could go through adding a new project when viewing personal account projects which is the default dashboard page in [`/`](https://gitpod.io/) and [`/projects`](https://gitpod.io/projects) as we allow users to switch between personal accounts and orgs for GitHub, groups for GitLab, etc.

This is more relevant as adding a project you collaborate on with others on your personal account is not making it possible to invite other team members or allows others to request access to your personal account. 💡 

### Proposal

Revert the change in https://github.com/gitpod-io/gitpod/pull/6966 and prompt users to create a new team when adding a repository from an non-personal account.

**Comment by jldec** [comment]
(removed in-progress status)

**Comment by gtsiolis** [comment]
Closing this as it will no longer be relevant after the changes in WEB-218.
