### ISSUE TITLE
Show feedback on the prebuilds page when there's need to reconfigure the app for GitHub or reinstall the webhook for GitLab

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7011]
Following the proposal in https://github.com/gitpod-io/gitpod/issues/7010, we could probably some some feedback on the prebuilds page the project needs to be reconfigured, whether this is GitHub app reconfiguration or adding the webhook back.

![5wa8sv](https://user-images.githubusercontent.com/120486/144336571-60bfffa1-f29c-4cbc-ae89-076fa0757ad4.jpg)

**Comment by jldec** [comment]
Thanks @gtsiolis - Given how many other prebuilds issues there are, I'd prefer to track this case in just one issue for now.
Closing in favor of #7010.
