### ISSUE TITLE
cgroups v2 breaks fuse support

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#7013]
### Bug description

When cgroups v2 is not explicitly disabled using the setting `systemd.unified_cgroup_hierarchy=0` fuse does not works anymore.

To verify if cgroups v1 is enabled check `cat /sys/fs/cgroup/devices/devices.list` does not returns an error.

### Steps to reproduce

N/A

**Comment by MrSimonEmms** [comment]
Is this what's happening in #6992 I wonder
