### ISSUE TITLE
[installer] Add additional check verifying cgroups v2 is disabled

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#7014]
xref: https://github.com/gitpod-io/gitpod/issues/7013

**Comment by MrSimonEmms** [comment]
I can see the check using `cat /sys/fs/cgroup/devices/devices.list`, but how do we confirm this from the Kubernetes API?

**Comment by MrSimonEmms** [comment]
Had a conversation about this with @aledbf. Verification won't be able to be done via the KubeAPI/Client-go. A validation check we could perform is to deploy a pod/job to the cluster to run this script and then return the value from there.

```shell
if [ ! -f "/sys/fs/cgroup/cgroup.controllers" ]; then
  echo >&2 "ERROR: Needs cgroup v2"
  exit 1
fi
```

See also:
 - https://github.com/kubernetes/system-validators/blob/ca2e257c13e6d6e49e0de2a31d08c03c790f548f/validators/cgroup_validator_linux.go#L50
