### ISSUE TITLE
Firefox: Ctrl + Shift + {Left, Right, Home, End} is broken after a terminal is opened & closed

### ISSUE THREAD

**Issue by peat-psuwit** [gitpod-io/gitpod#7015]
### Bug description

On Linux running Firefox, Ctrl + Shift + {Left, Right, Home, End} will stop working after terminal has been opened & close. One use these key binding to select words at word boundaries or until the start/end of line.

### Steps to reproduce

1. With a freshly opened window, open a file with some text in it (or just type some).
    - Try using Ctrl + Shift + Right, text should be selected at word boundaries.
2. Open a terminal, then close it using `exit` command.
3. Try using Ctrl + Shift + Right again. Nothing happens this time.

### Workspace affected

(This issue is not workspace-specific)

### Expected behavior

Text should be selected at word boundaries.

### Anything else?

This is the same issue filed against cdr/code-server [1], so it's been suggested in a related issue that this might be an upstream issue. But because there's no "VSCode server" from upstream, I'm not sure it's appropriate to file an issue at [microsoft/vscode](https://github.com/microsoft/vscode).

[1] also contains interesting log, however captured using code-server, and a suggested workaround.

Note that the issue might not be reproducible on macOS due to difference in default keybindings. It should, however, be reproducible on Windows.

[1] https://github.com/cdr/code-server/issues/3504

**Comment by akosyakov** [comment]
> This is the same issue filed against cdr/code-server [1], so it's been suggested in a related issue that this might be an upstream issue. But because there's no "VSCode server" from upstream, I'm not sure it's appropriate to file an issue at microsoft/vscode.

It sounds like an issue in upstream indeed. Could you file in VS Code repo instead?

**Comment by akosyakov** [comment]
I'm going to close it please reopen if it is not upstream.
