### ISSUE TITLE
[gp cli] tasks support

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#7016]
[Gitpod CLI](https://github.com/gitpod-io/gitpod/tree/main/components/gitpod-cli) should provide following commands to access tasks:
- `gp task list` to list [workspace tasks](https://github.com/gitpod-io/gitpod/blob/fc0c0a613c354444056ff43dfcc55c5acc9052a6/components/supervisor-api/status.proto#L65-L75) and their state
- `go task attach <id>` to attach to a workspace task by [an id](https://github.com/gitpod-io/gitpod/blob/fc0c0a613c354444056ff43dfcc55c5acc9052a6/components/supervisor-api/status.proto#L200)

In order to attach we should use [supervisor terminal service](https://github.com/gitpod-io/gitpod/blob/fc0c0a613c354444056ff43dfcc55c5acc9052a6/components/supervisor-api/terminal.proto#L14) similar how it is done [here](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/cmd/terminal-attach.go) but always with resizable and interactive session.

**Comment by axonasif** [comment]
> gp task attach <id> to attach to a workspace task by an id

So this will be something like `tmux` I assume.
For that case I have a suggestion, I think it would be better to have a separate UI for the gitpod tasks, more like how the `Remote Explorer` works on Gitpod.

**Comment by akosyakov** [comment]
> For that case I have a suggestion, I think it would be better to have a separate UI for the gitpod tasks, more like how the Remote Explorer works on Gitpod.

It is for terminal users via SSH. Generally whatever we have in UI should be reflected in Gitpod CLI as well.

In VS Code we don't need UI, gitpod tasks are automatically opened in terminals on workspace startup.

**Comment by axonasif** [comment]
> It is for terminal users via SSH and for IDEs there we don't provide deep integration yet, i.e. JetBrains products. Generally whatever we have in UI should be reflected in Gitpod CLI as well.

I agree, I like to do most of my tasks from cli when possible.

> In VS Code we already have UI, Gitpod tasks are automatically opened in terminals on workspace startup.

Here I was thinking about an UI for the detached background gitpod `command` tasks in the web version of Gitpod. But if course, cli should be there too.

**Comment by axonasif** [comment]
@akosyakov I think it would be nice if the `tasks` subcommand had a restart/re-run task feature. Someone had asked about this in [Discord](https://discord.com/channels/816244985187008514/816246578594840586/902767340222025738). And I personally would find this feature useful too.

**Comment by akosyakov** [comment]
@axonasif yeah, i remember had same urge sometimes. How would it work? Rerun in the same terminal? Start a new terminal?

**Comment by axonasif** [comment]
> @axonasif yeah, i remember had same urge sometimes. How would it work? Rerun in the same terminal? Start a new terminal?

Maybe a flag to specify the behavior? Run it on the caller terminal by default. Similar to `gp preview` and `gp preview --external`

**Comment by akosyakov** [comment]
Oh, I mean I'm not even sure what should be default behaviour :)

**Comment by axonasif** [comment]
I'm not either, I was trying to compare it with such an existing implementation of another `gp` subcommand 🙂

**Comment by akosyakov** [comment]
@axonasif Could you create a separate issue about restarting a task please?
