### ISSUE TITLE
Gitpod Status / Issues

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#702]
Hi :)

We are currently experiencing issues opening gitpod with "acquiring node" - is there currently any server issue? Also, is there a way to see the current status of gitpod in future cases where there's a problem instead of requesting here (maybe a notification at the loading page?).

Once in, there is a report of the files within gitpod randomly closing as well- which of course has not been the typical behavior.

Also noticing in the terminal, in place of "gitpod /workspace/gitpod $ " I am getting:
(failed reverse-i-search)`':
unless I open up a new terminal, which then acts as normal.

**Comment by jankeromnes** [comment]
Hi @ColbyWTaylor, thanks for filing this issue!

> We are currently experiencing issues opening gitpod with "acquiring node" - is there currently any server issue?

So, our Kubernetes cluster automatically scales up and down to follow demand. And typically, when you see "acquiring node" for a long time, it means that your workspace got started on a brand new server, which is still getting ready.

This is bad UX (sorry about that) and something we'd like to fix, e.g. by optimizing how fast new servers initialize themselves, or by not allocating workspaces on servers that aren't fully ready yet, or by generally improving our auto-scale mechanism (or a combination of these ideas).

> Also, is there a way to see the current status of gitpod in future cases where there's a problem instead of requesting here (maybe a notification at the loading page?)

We try to report ongoing issues at https://status.gitpod.io and on our Twitter account https://twitter.com/gitpod.

I believe we're also able to show a notification/banner on some Gitpod pages, but we haven't done that in a while. It's a good idea -- thanks! 👍 

> Once in, there is a report of the files within gitpod randomly closing as well- which of course has not been the typical behavior.

This doesn't sound good -- could you please explain what you see happening there exactly? Are you able to reproduce this issue by always following a series of specific steps?

> Also noticing in the terminal, in place of "gitpod /workspace/gitpod $ " I am getting:
(failed reverse-i-search)`

This also shouldn't happen, and I'm not sure whether it's related to the problem above or if it's something else.

Do the two latter problems happen consistently, and always with the same repository? If so, could you please share the URL here, so we can try reproducing & investigating this?

**Comment by ColbyWTaylor** [comment]
Thank you @jankeromnes for your quick response!

I was not able to replicate the last two points after this morning, but if it happens again I'll try to see if there's anything that stands out. "(failed reverse-i-search)`" seems to be a Ubuntu/Linux server issue from a quick search, but I'm not too familiar with anything there- maybe it was a temporary issue associated with the new server as you mentioned above.

**Comment by jankeromnes** [comment]
Thanks a lot for trying again! Hopefully you won't get long "acquiring node" events again anytime soon, nor see further strange IDE behavior. But if you do, please report back here if you can.

Another thought: Is it possible that you accidentally triggered some key bindings while the IDE was loading?

- On Mac OS, pressing <kbd>Option</kbd> + <kbd>W</kbd> would close a file, and <kbd>Option</kbd> + <kbd>Shift</kbd> + <kbd>W</kbd> would close all open files
- Pressing <kbd>Command</kbd> + <kbd>R</kbd> would start a reverse search in a Terminal, and typing a few additional letters would then show `(failed reverse-i-search)`

Some of these are quite similar to the `Reload` key binding, which would be my reflex as well if the IDE doesn't seem to do anything for a while.

**Comment by ColbyWTaylor** [comment]
Hi- I will report back on the keys if I can replicate, but I don't believe anything on the keyboard was being touched!

Also, this morning, we started encountering the "acquiring node" issue again (though it was working previously). Definitely waited more than a minute. For reference, one of the project urls was here:

https://gitpod.io/start/#b026d331-13b6-4df1-a5fb-c613c89a3b38

**Comment by Alaboudi1** [comment]
Hi, I am also experiencing the "acquiring node" issue in all my projects.

**Comment by ColbyWTaylor** [comment]
We are also still experiencing this (A classroom of 6 students are experiencing the same thing).
![screenshot__28_](https://user-images.githubusercontent.com/16373392/62302512-7c71f980-b448-11e9-87a8-f7bc4048aac9.png)

**Comment by svenefftinge** [comment]
Outch! This sounds bad and we are investigating how this can be improved. 
This happens usually when there is a spike in workspace demand and the already running nodes are not sufficient to serve that demand. We have seen such situations with large workshops (> 50 people). In that case we have to start new nodes which unfortunately sometimes takes some time. We are looking into optimizing for and predicting such spikes and generally make the creation of new nodes faster. 
It would be really helpful if you could share the exact time of when it happened, so we can check what happened at that time.

**Comment by XuanmoFeng** [comment]
> We are also still experiencing this (A classroom of 6 students are experiencing the same thing).
> ![screenshot__28_](https://user-images.githubusercontent.com/16373392/62302512-7c71f980-b448-11e9-87a8-f7bc4048aac9.png)
> 
> Update: We all finally got in- but it took about 10 minutes for everyone.

hahaaa I met the same question

**Comment by svenefftinge** [comment]
We have improved the scheduling logic. When there are huge spikes in demand, there are still times in which we are facing this. We are going to continuously improve, of course.
