### ISSUE TITLE
Persistent state between workspaces

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7025]
**Note:** If we had discussions set up, this issue is more of a discussion than an issue/solution. 

There are some situations where users need to have an element of persistence between their workspaces for the purpose of user configurations, and general continuity between the UX of a local env, and an ephemeral environment. 

Some notable examples: 

1. Bash history for auto-complete
2. IDE/plugin configuration files that aren't configurable [[1](https://community.gitpod.io/t/gitpod-and-tabnine-preferences-keep-getting-nuked/5693/11?u=akosyakov)]

This feels like a similar challenge that serverless applications had to overcome, by allowing mounting of file systems as a temporary solutions "bridge" to allow users to move from a stateful paradigm to a serverless/ephemeral one [[1](https://aws.amazon.com/blogs/compute/using-amazon-efs-for-aws-lambda-in-your-serverless-applications/)].

**Comment by MrSimonEmms** [comment]
There's a couple of things I'd love to see:
 - persisting files between workspaces to allow use of [Oh My ZSH](https://ohmyz.sh/) (this is a community-favourite request)
 - in addition to allowing mounting of envvars to workspaces, allow mounting of files, similar perhaps to how GitLab does it with CI/CD variables. I'd find this incredibly useful as I regularly have different Kubeconfig files that I need - currently I have to store them as envvars and then `echo $KUBECONFIG_NAME > ~/.kube/config`. So much easier to be able to store the file and then override the `$KUBECONFIG` variable to point to it
![image](https://user-images.githubusercontent.com/275848/145962246-c8a876fd-3203-425e-ba9b-13420c004d79.png)

**Comment by abkunal** [comment]
We are looking to adopt Gitpod with Pycharm for onboarding + development. The biggest friction seems to be that the IDE configuration doesn't persist on workspace restart.

**Features surviving workspace restart**
- IDE theme
- Debug and Test configuration

**Features not surviving workspace restart**
- Python interpreter configuration with Docker
- Modules indexing

Every time we restart a workspace, we need to configure the Python interpreter manually which in turn indexes the modules for this interpreter. It takes a total of 2 mins each time.

I was able to persist Debug and Test configuration using the `workspace.xml` file under the `.idea` folder but couldn't figure out any such configuration file for the interpreter config. I even checked the `.cache` and `.config` folder in home directory.

**Comment by akosyakov** [comment]
@abkunal Sorry for the late reply. I checked and these settings are stored as part of system config folder, so checking in of .idea folder is not enough. Could you try to follow https://www.jetbrains.com/help/idea/sharing-your-ide-settings.html to enable Settings Sync with JB account?

**Comment by loujaybee** [comment]
Going to close this one, I think it duplicates 

- https://github.com/gitpod-io/gitpod/issues/340
- https://github.com/gitpod-io/gitpod/issues/9019

So let's continue our discussion in those issues 🙏

**Comment by loujaybee** [comment]
@abkunal, thanks a lot for your feedback! 🙏 

> Python interpreter configuration with Docker

Yep, this one is an issue, created a dedicated one here for us to look into! 🙏  

- https://github.com/gitpod-io/gitpod/issues/9264

> Modules indexing

For this one, check out the dedicated issue, and current workaround we're using on Gitpod right now.

- https://github.com/gitpod-io/gitpod/pull/9193
- https://github.com/gitpod-io/gitpod/issues/6740
