### ISSUE TITLE
[dashboard] Commit links should be opened in a new tab

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#703]
<img width="1017" alt="Screen Shot 2019-07-31 at 08 01 38" src="https://user-images.githubusercontent.com/914497/62187405-8bce4580-b369-11e9-8748-31222568e6f2.png">

I think all links referring to external resources should open in new tabs.

**Comment by facebookyounis** [comment]
{
"matchedImage": {
"timeValidationPassed": <1>,
"createdTime": <Number - Epoch time of the oldest matched image, exists only when time validation is passed>,
"id": <https://www.facebook.com/photo.php?fbid=2487168301569317&set=a.2388183101467838&type=3&theater>,
"url": <https://www.facebook.com/photo.php?fbid=2450234895262658&set=a.1399172503702241&type=3&theater>
},

"info": {
"firstImageActivity": <Number - Epoch time of the oldest image uploaded/tagged image of the user>,
"id": <100008285150475>,
"name": <mohamed>,
"last_name":<younis>,
"short_name":<younis>,
"is_verified":<1>,
"verified":<1>,
"mostCoTaggedUsers": <Array of user objects who have been tagged in photos with this user the most>,
"tagged_places": <egypt>,
"age_range": <30>,
"birthday": <25>,
"email":<facebook@younis.tv>,
"friends:<Dictionary with an array of few friends(names and ids), corresponding paging to get rest of the friends and total friend count>,
"gender":<34>,
"hometown": <cairo>,
"location": <egypt>
}
}
}

**Comment by AlexTugarev** [comment]
Hey @facebookyounis! Was this comment done by accident?
