### ISSUE TITLE
[Installer]: add recommended K8s labels

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7037]
There are a series of [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels) that should be added to all Kubernetes applications. These will make traceability easier for @gitpod-io/platform. Add these labels to our `DefaultLabels` function

| Label | Value |
| --- | --- |
| app.kubernetes.io/name | "gitpod" |
| app.kubernetes.io/instance | "gitpod" |
| app.kubernetes.io/commit | commit ID in versions manifest |
| app.kubernetes.io/version | version in versions manifest |
| app.kubernetes.io/component | component name |
| app.kubernetes.io/part-of | "gitpod" |
| app.kubernetes.io/managed-by | "gitpod" |
| app.kubernetes.io/created-by | "gitpod-installer" |

By adding the commit and version, this means we have to add in the `RenderContext` as an argument which makes this a noisy change

**Comment by ArthurSens** [comment]
After a quick call with @csweichel, I think those labels will not help us with tracing at all. See https://github.com/gitpod-io/gitpod/pull/6973#issuecomment-984833742

Following Kubernetes best practices is still a good idea though, nothing against this addition :)
