### ISSUE TITLE
Stopped - Started a minute ago: Error: Error while adding Gitpod layer.

### ISSUE THREAD

**Issue by sparkskapil** [gitpod-io/gitpod#704]
**Describe the bug**
I have a workspace which I am using for 2 months. 
Now it has started giving me this error on start
_Stopped - Started a minute ago: Error: Error while adding Gitpod layer._

**Comment by geropl** [comment]
Thanks @sparkskapil , we saw the same. It'd help greatly if you share the GitHub URL you tried. Thx!

**Comment by sparkskapil** [comment]
Thanks for the reply. 
The issue got fixed. Don't know how.

**Comment by geropl** [comment]
Thanks for the fast feedback! We implemented a workaround. Please head back here if it fails again for you.
The fix will be deployed in the next hours.

**Comment by sparkskapil** [comment]
Thanks a lot.
