### ISSUE TITLE
[image-builder] bob proxy does not handle digest references

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#7043]
### Bug description

[We've seen reports](jelaniwoods/appdev2021-base-rails@sha256:91427ecf043c8cdd8040bbd3626eb9bbbf3bee99d44ed3d1281504f71681d661) of workspace images no longer working with mk3 when are specified as digested reference, e.g. `jelaniwoods/appdev2021-base-rails@sha256:91427ecf043c8cdd8040bbd3626eb9bbbf3bee99d44ed3d1281504f71681d661`.

The screenshot indicates that the bob proxy is not running, because the connection to `localhost:8080` is refused. Most likely the proxy fails during startup because of the base ref being in digest form.

### Steps to reproduce

Try to start a workspace using `jelaniwoods/appdev2021-base-rails@sha256:91427ecf043c8cdd8040bbd3626eb9bbbf3bee99d44ed3d1281504f71681d661` as base-image.

### Expected behavior

The workspace should just start, i.e. image-builder should build the workspace image.

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7043#issuecomment-984999024):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
