### ISSUE TITLE
14 UNAVAILABLE: No connection established

### ISSUE THREAD

**Issue by stephenavocado** [gitpod-io/gitpod#7048]
### Bug description

14 UNAVAILABLE: No connection established

![image](https://user-images.githubusercontent.com/81815137/144523532-25b2aac3-a5e9-438c-8099-f7fbb2242fd4.png)

### Steps to reproduce

Opened workspace 

For 30 minutes prior, workspace did open, but was producing errors related to ruby version and server connection

![image](https://user-images.githubusercontent.com/81815137/144523640-0479d8be-0368-405d-bb18-27fbb8fcf33d.png)

### Workspace affected

https://gitpod.io/start/#teal-armadillo-3asc7h4s

### Expected behavior

Workspace opens, server runs with "bin/server" command

**Comment by stephenavocado** [comment]
Also will not allow me to create new workspaces from my repo

**Comment by ghuntley** [comment]
> Also will not allow me to create new workspaces from my repo

Howdy @stephenavocado; I've been unable to replicate this but there has been one other report recently. Can you please reconfirm If you are experiencing issues?

[1] https://twitter.com/GeoffreyHuntley/status/1466571997807136768?s=20

**Comment by stephenavocado** [comment]
Hello - yes still experiencing the issue. I believe the source of the issue is being discussed here: 

https://community.gitpod.io/t/unable-to-open-workspaces-that-use-custom-docker-image/5707/3

**Comment by ghuntley** [comment]
Hmm unable to replicate and logs don't show anything that sticks out.

- [x] Launched base-rails via https://gitpod.io#https://github.com/appdev-projects/base-rails and routed to US cluster

<img width="1440" alt="2021-12-03_12-43-03" src="https://user-images.githubusercontent.com/127353/144535885-d1ce68ec-f4b4-4f72-b39b-35d95123d1d9.png">

- [ ] launched https://ghuntley.com/new and routed to us cluster

<img width="1440" alt="2021-12-03_12-43-03" src="https://user-images.githubusercontent.com/127353/144535983-039c236f-91c3-46e1-be33-7e00a74315a1.png">
 
Going to test on EU cluster as well. 

@stephenavocado do you have a repository I can try?

**Comment by ghuntley** [comment]
@stephenavocado can you please confirm if you are using vscode or vscode insiders?

<img width="1345" alt="Screen Shot 2021-12-03 at 12 46 12 pm" src="https://user-images.githubusercontent.com/127353/144536215-ed3f7de6-22a1-4041-856a-3e6fc5c2fbf9.png">

**Comment by stephenavocado** [comment]
This is the affected repo: https://github.com/stephenavocado/PainNavigator

I am using VS Code

**Comment by stephenavocado** [comment]
Workspace: https://gitpod.io/start/#teal-armadillo-3asc7h4s

**Comment by ghuntley** [comment]
**update:** I've identified elevators errors in telemetry related to prebuilds circa 2h-3h hours ago but service is now within acceptable ranges. Moving on to looking into workspace logs - thanks for supplying the identifier.

<img width="745" alt="Screen Shot 2021-12-03 at 1 11 03 pm" src="https://user-images.githubusercontent.com/127353/144538597-3f96260c-e4b4-4f11-a283-51f3b95ee753.png">
t

**Comment by stephenavocado** [comment]
Appreciate your assistance!

**Comment by ghuntley** [comment]
> Appreciate your assistance!

Got it. Starting incident response. Apologies for the inconvenience and bringing in some additional minds to look at this. The key to reproducing is the that repository needs to be private (need to reconfirm) and trigger a rebuild of a docker container (confirmed). 

<img width="718" alt="Screen Shot 2021-12-03 at 1 31 26 pm" src="https://user-images.githubusercontent.com/127353/144540532-a4bb78f7-db98-4c48-a67b-7eae9c810299.png">
e.

Can you please share a screenshot of your browser console?

**Comment by jankeromnes** [comment]
I think we're talking about several different, probably unrelated problems here:

- The error `UNAVAILABLE: No connection established.` seems to indicate a connection problem in our cluster. Might have been temporary, would be good to investigate.

- Pulling an image with a SHA pulls a slightly different image: https://community.gitpod.io/t/unable-to-open-workspaces-that-use-custom-docker-image/5707/10 (related to this recent fix: https://github.com/gitpod-io/gitpod/pull/7045 -- maybe it needs an additional fix)

- Supervisor `responded with a status of 502`: I think this is normal in the creation phase of a workspace, and means that the IDE isn't ready yet (but should be after a brief time). Seems unrelated to the other two problems.

**Comment by wilj** [comment]
I'm experiencing the same problem starting workspaces in the US cluster:

```
Request createWorkspace failed with message: 14 UNAVAILABLE: No connection established

Unknown Error: { "code": -32603 }
```

Mine is also a private project with custom Dockerfile, but the Dockerfile does not reference the image by the SHA hash.

**Comment by stephenavocado** [comment]
> > Appreciate your assistance!
> 
> Got it. Starting incident response. Apologies for the inconvenience and bringing in some additional minds to look at this. The key to reproducing is the that repository needs to be private (need to reconfirm) and trigger a rebuild of a docker container (confirmed).
> 
> <img alt="Screen Shot 2021-12-03 at 1 31 26 pm" width="718" src="https://user-images.githubusercontent.com/127353/144540532-a4bb78f7-db98-4c48-a67b-7eae9c810299.png">
> 
> Can you please share a screenshot of your browser console?
> 
> edit: https://www.gitpodstatus.com/incidents/r30dh4kly01v

Sorry I missed the question at the end - here is my browser console: 

![image](https://user-images.githubusercontent.com/81815137/144721274-d5b71ad9-45de-4237-b635-46118a097440.png)

**Comment by kylos101** [comment]
Hi @stephenavocado , are you still experiencing trouble with this repo? If yes, may I ask you to reopen this issue?
