### ISSUE TITLE
my account was blocked 

### ISSUE THREAD

**Issue by paul-wie-dot** [gitpod-io/gitpod#705]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by meysholdt** [comment]
hi! You were involved in an incident related to sending spam from Gitpod. I reached out to you via email when the block was installed. Let me know if you didn't receive the email. I can send it again.

It's important to understand that Gitpod is for developing software: Read code, write code, run your code, test it, demo it to friends, colleagues and customers, etc. Sending spam from our platform is a violation of our [Terms of Services](https://www.gitpod.io/terms) and we can not allow it. See the "Fair Use" clause.

To continue the conversation please respond to my email. If you want to use Gitpod for software development I'm happy to unblock your account.

**Comment by fbigun** [comment]
```
Your account has been blocked.
If you have questions please contact us.
```

I encountered such a problem

**Comment by neduboi** [comment]
Same here.. My account was blocked and I dont know what I did that got it blocked
