### ISSUE TITLE
bob proxy ignores digest

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#7050]
### Bug description

When users specify a digested base image ref, we ignore the digest wile building the workspace image.

### Steps to reproduce

Open a workspace from `jelaniwoods/appdev2021-base-rails@sha256:91427ecf043c8cdd8040bbd3626eb9bbbf3bee99d44ed3d1281504f71681d661`

**Comment by roboquat** [comment]
@csweichel: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7050#issuecomment-985286847):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
