### ISSUE TITLE
[desktop] workspace timeouts if you close the browser tab prematurely

### ISSUE THREAD

**Issue by dragonDScript** [gitpod-io/gitpod#7057]
### Bug description

If you open a workspace in vscode and immediately close the tab it won't let you to connect.

### Steps to reproduce

1. Open a workspace.
2. Open the workspace in VSCode. When vscode is open and prompts you to "Continue", close the gitpod tab.
3. See error.

### Expected behavior

Workspace should open no matter if the tab is open or closed.

### Example repository

Any repo is valid

### Anything else?

See the discord for more info

**Comment by akosyakov** [comment]
It is going to be a problem for all desktop apps. Maybe we should avoid sending close event from ready screen if desktop app was opened. Or have a special one.

**Comment by dragonDScript** [comment]
> It is going to be a problem for all desktop apps. Maybe we should avoid sending close event from ready screen if desktop app was opened. Or have a special one.

Probably just vscode, due to how it works.

**Comment by dragonDScript** [comment]
don't stale

**Comment by loujaybee** [comment]
Thanks for raising @dragonDScript, I think this issue is a duplicate of: 

- https://github.com/gitpod-io/gitpod/issues/10373

Please watch that one for updates, we're actively looking into this one currently.
