### ISSUE TITLE
pylint fails to work

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#706]
**Describe the bug**
`pylint` fails to work on a simple Python script.

**To Reproduce**
1. Open this GitHub repository using GitPod.
2. Upload the file linstall.py into the workspace.
3. Run the command `pylint linstall.py` and you will see the following error message.
![image](https://user-images.githubusercontent.com/824507/62320120-18116300-b465-11e9-9584-61e64c91484d.png)

To make things easier, I've shared a snapshot of the workspace at https://gitpod.io#snapshot/2cf8e203-b20b-4556-9dc3-938c7ff37e16. You can [![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/2cf8e203-b20b-4556-9dc3-938c7ff37e16).

**Expected behavior**
The `pylint` command shouldn't give the above error messages.

**Comment by AlexTugarev** [comment]
Hey @dclong! Thanks for sharing the snapshot, which makes investigation super easy by the way!

The default `python` is a `py2`, which is the underlying issue. In your script, you're using `py3` language features like [`f-strings`](https://docs.python.org/3/whatsnew/3.6.html#new-features).

Please configure your workspace to use `py3` tools, i.e. `pip3 install pylint && python3 -m pylint ...`

**Comment by dclong** [comment]
Thank you, @AlexTugarev!
