### ISSUE TITLE
Fix ownership of installer files that belong to team IDE

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#7060]
[This PR](https://github.com/gitpod-io/gitpod/pull/7059) needs approval from team IDE, meta, and workspace but should only need approval from the IDE team. That should be fixed.

_([internal discussion](https://gitpod.slack.com/archives/C02F19UUW6S/p1638548068040600))_

**Comment by MrSimonEmms** [comment]
As #7059 has been merged, can this be closed?

**Comment by corneliusludmann** [comment]
Hmm … #7059 doesn't fix the ownership, does it? The actual issue here is that every change in `ide-configmap.go` needs to be approved by the meta team but should be approved by the IDE team only.

Same applies to:
- `installer/pkg/components/workspace/constants.go`
- `installer/pkg/config/versions/versions.go`

which has IDE-specific constants. It would be great when they can be separated somehow so that the IDE team can change them on their own.

**Comment by MrSimonEmms** [comment]
Oh yes, I recall us chatting about that. I'll put a proposal in for that

**Comment by MrSimonEmms** [comment]
@corneliusludmann I think that the PR meets the brief
