### ISSUE TITLE
Vscode-textmate to do syntax coloring

### ISSUE THREAD

**Issue by oldrich-s** [gitpod-io/gitpod#7070]
## Describe the behaviour you'd like
If I am not mistaken, Gitpod currently does not use vscode-textmate to do the syntax coloring. Is there a technical reason for that or is it just go and do it?

![image](https://user-images.githubusercontent.com/37391/144792404-d2fb739a-38da-4860-ab57-9fb8a2b1b616.png)

vs

![image](https://user-images.githubusercontent.com/37391/144792495-9d5c851b-dc79-41b4-a4e8-381ab9a18581.png)

**Comment by akosyakov** [comment]
Gitpod is using VS Code Web, and it does use textmate:

<img width="1904" alt="Screenshot 2021-12-06 at 11 19 28" src="https://user-images.githubusercontent.com/3082655/144829091-e1fe1f0e-ee75-482c-926d-36c6d4e4a585.png">

Could you check that your browser has WASM support. Otherwise it won't work. You can open devtools and see for errors related to wasm.

**Comment by oldrich-s** [comment]
I use the latest Chrome on Win10 - so WASM should not be a problem.

I have tried to run https://gitpod.io/#https://github.com/oldrich-s/musicope which is my old personal project and open server.js and got syntax coloring without textmate.

Doing the same via vscode.dev (https://vscode.dev/github/oldrich-s/musicope) provides the textmate syntax coloring as expected.

**Comment by akosyakov** [comment]
> I have tried to run https://gitpod.io/#https://github.com/oldrich-s/musicope which is my old personal project and open server.js and got syntax coloring without textmate.

It looks alright now:
<img width="1904" alt="Screenshot 2021-12-06 at 13 04 42" src="https://user-images.githubusercontent.com/3082655/144843011-2760c5ae-e2bd-4f20-a61a-73dbe934ad0e.png">

Maybe there was some hiccup with loading this wasm file. Can you still reproduce it?

**Comment by oldrich-s** [comment]
Unfortunately still the same. WASM loads properly but it seems that the languageId is wrong (plaintext).

![image](https://user-images.githubusercontent.com/37391/144845294-ff60ff22-8878-414b-a2dc-d2b890df44ca.png)

BTW: Nice that you provide source-maps. That helps to troubleshoot a lot 👍.

**Comment by akosyakov** [comment]
Do you have any special user extensions/settings?

**Comment by oldrich-s** [comment]
So far I traced it to the order `registerTextMime` and `_registerDefinitionIfAvailable` is being executed in, which is like:

```
registerTextMime(plaintext)
_registerDefinitionIfAvailable()
registerTextMime(javascript)
registerTextMime(typescript)
...
```

so by the time the textmate is being built `nonUserRegisteredAssociations` contains only `plaintext`

**Comment by akosyakov** [comment]
Sorry, I does not really follow, could you provide a code pointer? Did you try disable user extensions/settings?

**Comment by oldrich-s** [comment]
Sorry for not answering your question 😊.

I have tried to run the webpage in Chrome, Chrome with private mode and in MS Edge - all with the same result.

I am on 4g and I beleive that the issue happens because both the various languages and the texmate are being loaded async so on fast connection the languages load first and on slow connection the wasm loads first. 

I am not on my pc but I can try to disable extensions and send you code pointer tomorrow.

**Comment by akosyakov** [comment]
> I have tried to run the webpage in Chrome, Chrome with private mode and in MS Edge - all with the same result.

I meant VS Code extensions/settings. I thought maybe you installed something.

> I am not on my pc but I can try to disable extensions and send you code pointer tomorrow.

👍

**Comment by oldrich-s** [comment]
I have just tried it this morning and everything works 👍. Probably some issue yesterday between the chair and the table 😇.
