### ISSUE TITLE
Unable to use Fedora with Image builder mk3

### ISSUE THREAD

**Issue by gbraad** [gitpod-io/gitpod#7071]
### Bug description

Formerly it was necessary to setup the user environment for the image, which meant that the image took responsibility to create the `gitpod` user and the necessary `CMD` to run.

Since the move to Image builder mk3 it should be possible to use a Fedora image (upstream for Amazon Linux) as a base. However, I run into issues. When I create the user beforehand it complains there already is one... and when I let the builder take care of this, it is unable to locate `goupdadd` as on path. Modifying this has no use

### Steps to reproduce

 `.gitpod.Dockerfile`

```dockerfile
FROM registry.fedoraproject.org/fedora:latest
```

will result in the issue to not able to locate `/usr/sbin/groupadd`
adding `env PATH="/usr/sbin/:${PATH}"` make no difference

----

Running `groupadd` and/or user add will result in a conflict

```dockerfile
# Install user environment
RUN groupadd gitpod && adduser -g gitpod gitpod
```

This will run on the image buillder, but after the image is pulled it will fail as the group already exists.

### Expected behavior

Being able to use any Fedora/RHEL/CentOS/Rocky/AlmaLinux/AmazonLinux based image,

### Example repository

Have been going back and forth on this already for quite some time: https://github.com/gbraad/gitpod-template-fedora/

**Comment by gbraad** [comment]
### Solution

You need to add the user explicitly as:

```
RUN useradd -l -u 33333 -G wheel -md /home/gitpod -s /bin/bash -p gitpod gitpod
```

**Comment by gbraad** [comment]
It would be ideal if the process would work and `useradd` and `groupadd` are also looked for in `/usr/sbin` by default.

**Comment by csweichel** [comment]
> It would be ideal if the process would work and `useradd` and `groupadd` are also looked for in `/usr/sbin` by default.

Good point. We're not actually starting the container as `root` (for obvious reasons), hence the process will respect only the `PATH` environment variable of the image. We could add a special casefor `/usr/sbin` here.

**Comment by gbraad** [comment]
This got fixed and works: template images exists
