### ISSUE TITLE
[server] Investigate server event loop lag

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#7082]
We see an accumulating node.js event loop lag increase:
This is bad, because it is a min. (!!!) static addition to every API call.
![image](https://user-images.githubusercontent.com/32448529/144859517-46dcfd15-adf3-4151-94a9-274c117231c6.png)
(Source: [Grafana](https://grafana.gitpod.io/d/server/gitpod-component-server?orgId=1&viewPanel=24))

**Comment by roboquat** [comment]
@geropl: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7082#issuecomment-986805390):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
Not fixed yet.

**Comment by geropl** [comment]
Will pause work on this, and see if it got better with the PRs linked above after tomorrows deployment.

**Comment by geropl** [comment]
Taking CPU profiles reveals some candidates for improvements, but nothing explaining the accumulating lag, yet:
 - [ ] HostContextProviderImpl (38ms): `setTimeout(..., 2000)` does `O(n²)` sync work rather often ([source](https://github.com/gitpod-io/gitpod/blob/757a1594c6e5f14a268833b75411e449637c9d40/components/server/src/auth/host-context-provider-impl.ts#L48-L56)). Also, uses encrypted columns, which is expensive
 - [ ] `strategy.pass` (7.7ms): two calls here, sees to be too expensive
 - [ ] `guessGitTokenScopes`
 - [ ] `CodeSyncService` fetch
 - [ ] spawning `oci-tool` (40ms)
 - [ ] prometheus metrics (17ms)

**Comment by AlexTugarev** [comment]
@geropl, happy to discuss findings and provide any details on the first two.

**Comment by geropl** [comment]
There is now a draft PR for the biggest issues [mentioned above](https://github.com/gitpod-io/gitpod/issues/7082#issuecomment-992384108).

But the root cause remains unidentified. :confused: For the sake of making the holidays safe, I will add an alert to ensure we're not missing anything bad here.

**Comment by geropl** [comment]
I happened to find a super-linear relationship between:
 - accumulated count of websockets created since `server` start
 - (naturally accumulating) node.js event loop lag

(steadily lines are connections, spiky lag. Note how those match so good they are hard to tell apart visually :see_no_evil: )
![image](https://user-images.githubusercontent.com/32448529/146570238-79640c16-b35b-466b-9333-30c76ff8f448.png)

Prometheus queries:
```
gitpod_server_api_connections_total{cluster=~"$cluster", pod=~"$pod"}
```
```
avg_over_time(nodejs_eventloop_lag_seconds{cluster=~"$cluster", pod=~"$pod"}[20m]) * 1000000  # random constant factor to make graphs overlap
```

Also, the only way I could reproduce this "accumulating event loop lag" behavior in minimal tests was with accumulating `setTimeout`s:
```js
const { monitorEventLoopDelay } = require('perf_hooks');
const h = monitorEventLoopDelay({ resolution: 2 });

const doWork = async () => {
    while (true) {
        for (let i = 0; i < 250000; i++) {
            setTimeout(() => {}, Math.random() * 5 * 1000);
        }

        h.enable();
        for (let i = 0; i < 5; i++) {
            await new Promise((resolve) => setTimeout(resolve, 5 * 1000));
            console.log("min: " + h.min);
            console.log("max: " + h.max);
            console.log("mean: " + h.mean);
            console.log("stddev: " + h.stddev);
            console.log("percentiles: " + h.percentiles);
            console.log("percentiles(50): " + h.percentile(50));
            console.log("percentiles(99): " + h.percentile(99));
        }
        h.disable();
    }
};

doWork().catch(console.error);
```

That spurred investigation into where we might fail to `clearTimeout`:
 - maybe in websocket pingpong (debug PR: https://github.com/gitpod-io/gitpod/pull/7292): unable to reproduce in devstaging, so added debug output
 - maybe in libs we use: no idea how to debug this atm :thinking:

**Comment by jldec** [comment]
Not fixed yet.

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7082#issuecomment-999096537):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
Thx to #7292 it's now clear that we leak the pingpong timer :see_no_evil: 
![image](https://user-images.githubusercontent.com/32448529/147092531-3c5f9a0f-4971-4ffc-a733-ea40b77f9e95.png)

This line should fix it: https://github.com/gitpod-io/gitpod/pull/7292/files#diff-afb02a2ba5397f62d4eaf365273e0336e8b20fe0fb39ee0f8276573e72d016e0R27

**Comment by geropl** [comment]
The change did not fix it. Will try sth else.

**Comment by JanKoehnlein** [comment]
Let's not close this before the lag has disappeared.

**Comment by JanKoehnlein** [comment]
Removed priority label, because the user impact is currently mitigated by on-call. Doesn't mean we're not working on this.

**Comment by geropl** [comment]
Dropping assignment, as I'm not actively working on this.

**Comment by geropl** [comment]
### Update

For what has happened during the last weeks on this:
 - we identified several source of bad performance/CPU spikes/long sync blocks and merged/shipped fixes [[1](https://github.com/gitpod-io/gitpod/pull/7847), [2](https://github.com/gitpod-io/gitpod/pull/8227)]
   - [some](https://github.com/gitpod-io/gitpod/pull/8201) are still outstanding, but can be continued after [blockers](https://github.com/gitpod-io/ops/pull/1219) have been addressed by platform
 - @geropl: investigated of setTimeout/setInterval calls might be causing the slowly accumulating event loop lag. tl;dr: no, those are constant over time, or linear to #of API calls and did not accumulate (measured over the course of one day)
   - code: https://github.com/gitpod-io/gitpod/tree/gpl/lag-timeout
 - increased # of pods (and nodes, we're running on smallish n4 nodes): https://github.com/gitpod-io/ops/pull/1230
 - @AlexTugarev: merged a way to gather CPU profiles at runtime: https://github.com/gitpod-io/gitpod/pull/8284
 - @geropl and @AlexTugarev: looked at recent (18.02) CPU profiles captured by attaching the Chrome debugger to the pod for ~5mins at runtime
   - the Chrome remote debugger does not show anything, and looks rather empty apart from known short spikes, which are partly already addressed above. Those are a problem in itself, but not the general problem we're looking at. The biggest time consumer seems to be the GC:
![image](https://user-images.githubusercontent.com/32448529/154959740-41963d4c-ec98-4944-868d-49f4968918d6.png)

   - opening the same profile with the new, in-page Devtools visualization shows a big of a different picture (happened by accident :roll_eyes: ):
![image](https://user-images.githubusercontent.com/32448529/154958885-fee2a8ab-9272-4237-a26e-fddad713bbbe.png)
      All long-running calls are ending in I/O bounds methods (writev, send, etc.): in the first visualization this were all shown to be blocked by the GC
   - this lead us to believe we might have a problem not (so much) with our code, but with the small VMs we're running on. We know from past experience that high I/O results in high CPU traffic/usage on VMs, especially small VMs :grimacing: 

### Suggestions:
   - bigger nodes: maybe 2 x n2-standard-16 (instead of 6 x n1-standard-4) with _bigger caches_
   - increase the size of the node.js threadpool [`UV_THREADPOOL_SIZE`](https://medium.com/@joydipand/how-does-thread-pool-work-in-node-js-c48f3b3662a9) (this is responsible for performing all I/O) from default 4 to sth higher (depending on actual # of cores/pod)

**Comment by ghuntley** [comment]
Received a page moments ago about eventloop lag ([internal link](https://gitpod.slack.com/archives/C02EN94AEPL/p1646716071874859)) which self-healed.

<img width="1379" alt="2022-03-08_15-43-54" src="https://user-images.githubusercontent.com/127353/157170733-e88b09ff-b4f7-437f-9027-1d2a466d9c91.png">

**Comment by geropl** [comment]
> Received a page moments ago about eventloop lag ([internal link](https://gitpod.slack.com/archives/C02EN94AEPL/p1646716071874859)) which self-healed.

This is more of an alerting/PagerDuty artifact.

**Comment by geropl** [comment]
Closing this issue, because it represents old behavior and based on old code. It does not make sense to continue here, especially as we can always go back and read up on the history/prior investigation.
