### ISSUE TITLE
hitting a breakpoints freezes the entire IDE. 

### ISSUE THREAD

**Issue by Alaboudi1** [gitpod-io/gitpod#709]
Why hitting a `debugger;` statement in js code from the preview window also freezes the IDE? Is this the expected behavior?

**Comment by svenefftinge** [comment]
Yes, websites with iframes run in a single loop. You need to open the preview in a new browser tab to get around that.

**Comment by svenefftinge** [comment]
Sorry, I don't think we can do anything about it.

**Comment by svenefftinge** [comment]
To open the preview in a browser tab click the icon on the top right.

**Comment by svenefftinge** [comment]
@akosyakov could you verify?

**Comment by akosyakov** [comment]
> All windows on the same origin share an event loop as they can synchronously communicate

From http://hassansin.github.io/shared-event-loop-among-same-origin-windows

Because of it, I'm not sure that opening another window will happen. It should use still the same event loop if it comes from the same origin.

**Comment by AlexTugarev** [comment]
@akosyakov see last paragraph:

> It turns out we can pass an option noopener in window.open()

**Comment by akosyakov** [comment]
@AlexTugarev but then we won't be able to communicate with that window? i.e. right now there is no way to detect iframe focus except installing a listener inside iframe and forward them to host window. I hope we will fix it in this way that focus given properly.

**Comment by svenefftinge** [comment]
So sounds like adding `rel=noopener` is still missing for our open in browser command?

**Comment by akosyakov** [comment]
An issue in upstream: https://github.com/theia-ide/theia/issues/5857

**Comment by Alaboudi1** [comment]
I believe this has been fixed 👍.

**Comment by jankeromnes** [comment]
@Alaboudi1 indeed thanks, good catch! 💯 

The fix was merged 21 days ago and deployed as a hotfix 16 days ago. 🎉

**Comment by DanTup** [comment]
I'm hitting this issue today, it doesn't seem fixed?

**Comment by svenefftinge** [comment]
It was reintroduced lately by some changes we made in Theia. Thanks for the PR you provided, we will put it into production ASAP.

**Comment by svenefftinge** [comment]
In production now
