### ISSUE TITLE
Pushing a new branch to a fork is successful but displays an error message

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#7092]
### Bug description

After opening a repo in Gitpod, adding a fork of that repo, create a new branch and push that branch to the fork.
The push is successful, but there's an error message displayed:
![image](https://user-images.githubusercontent.com/22901/144968599-62c054dc-ea6f-4061-834c-284ed3f2a7fb.png)

### Steps to reproduce

1. Opening a repo in Gitpod - https://gitpod.io/#https://github.com/drud/ddev

1. In Gitpod interface, add a fork of the repo - `git remote add fork https://github.com/shaal/ddev.git`

1. Create a new branch - `git checkout -b new-branch`

1. Push the new branch to the fork - `git push fork`

The push is successful, but there's an error message displayed:
![image](https://user-images.githubusercontent.com/22901/144968599-62c054dc-ea6f-4061-834c-284ed3f2a7fb.png)

**Comment by AlexTugarev** [comment]
I'm actually not sure about the component. @JanKoehnlein, please correct me if I'm wrong here. 

It's the caller of `guessGitTokenScopes` API method which doesn't provide a `repoURL` to be parsed here when `git push REMOTE_NAME` is executed.

**Comment by shaal** [comment]
I think this issue should remain open, and add the label `meta: never-stale`

**Comment by axonasif** [comment]
> I think this issue should remain open, and add the label `meta: never-stale`

Can you please confirm if this is still happening?

I usually do `git push <remote> <branch>`, so maybe that's why I never noticed this, but worth knowing if this issue is still effective 🙏

**Comment by lem0n4id** [comment]
> Can you please confirm if this is still happening?

I tried this on Gitpod (browser) and it works perfectly fine.

<details>
<summary>Here's what i did</summary>
Note-  this is in <a href="https://github.com/freecodecamp/freecodecamp">freecodecamp repo</a>

```bash
gitpod /workspace/freeCodeCamp (main) $ git remote add fork https://github.com/lem0n4id/freecodecamp.git
gitpod /workspace/freeCodeCamp (radio-button-RWD) $ git checkout -b patch-2
Switched to a new branch 'patch-2'
gitpod /workspace/freeCodeCamp (patch-2) $ git push fork
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: This repository moved. Please use the new location:
remote:   https://github.com/lem0n4id/freeCodeCamp.git
remote: 
remote: Create a pull request for 'patch-2' on GitHub by visiting:
remote:      https://github.com/lem0n4id/freeCodeCamp/pull/new/patch-2
remote: 
To https://github.com/lem0n4id/freecodecamp.git
 * [new branch]            patch-2 -> patch-2
```
</details>

**Comment by 7malikk** [comment]
> 

Thanks @lem0n4id This just helped me in another project i'm working on.
