### ISSUE TITLE
major security issue when pushing to github

### ISSUE THREAD

**Issue by leopascual** [gitpod-io/gitpod#7093]
### Bug description

Because when creating a workspace, name may stay as created (from template), after pushing branch created from my main br gh account. 
I found out in the pull request I was asking to merged my branch into a main branch with the same repo name of the template workspace created, this repo was full of people where my branch was pushed with out my security. gitpod-io/template-python-django

### Steps to reproduce

1. create a template (my case django)  
2. work in main 
3. update to github - push changes
4. create a branch
5. push branch work 
6. from gitpod vcode in source control click in branches and ask to merge it, 
7. creates a pull request and branch in repo gitpod-io/template-python-django
8. Out of my account. 

### Workspace affected

DELETED

**Comment by ghuntley** [comment]
Is this the pull request? https://github.com/gitpod-io/template-python-django/pull/5

**Comment by sagor999** [comment]
I think this is an issue with github extension, rather then with gitpod. 
Github quite often asks me to merge PR into parent repo when forked, instead of my forked repo.
