### ISSUE TITLE
[gp-cli] allow to extend timeout

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#7096]
[Gitpod CLI](https://github.com/gitpod-io/gitpod/tree/main/components/gitpod-cli) should have a new command `timeout extend` which will [boost a workspace timeout](https://www.gitpod.io/docs/life-of-workspace#timeouts).

To extend a timeout we should use [Gitpod Server APIs](https://github.com/gitpod-io/gitpod/blob/5bd176bfe71d86db9ec834881ef1bcd84263556e/components/gitpod-cli/pkg/gitpod/server.go#L35) similarly how it is done [in VS Code extension](https://github.com/gitpod-io/openvscode-server/blob/a447d759623ea02ade42828f7b2f7b4126492cff/extensions/gitpod-shared/src/features.ts#L606-L623).

**Comment by loujaybee** [comment]
We should probably wait for: https://github.com/gitpod-io/gitpod/issues/9038 before implementing this. 🙏

**Comment by andreafalzetti** [comment]
Closed with https://github.com/gitpod-io/gitpod/pull/10619
