### ISSUE TITLE
vscode Extensions are not persistent

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#710]
**Describe the bug**
vscode Extensions are not persistent when starting the workspace backup all extensions uninstalled
**To Reproduce**
1 install extension 2 stop workspace 3 startup same workspace
**Expected behavior**
have the extensions I installed to still be there

**Comment by AlexTugarev** [comment]
Thanks @JesterOrNot for reporting this issue! We're looking into it.

**Comment by AlexTugarev** [comment]
@JesterOrNot, we've just deployed a fix for this issue.
