### ISSUE TITLE
[tracing] Move Auth-/TOS-flow extensive logging to tracing

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#7108]
Currently `server` traces more than it should around the auth and TOS flows which litters the logs (`grep` for "Auth-With", "Auth Provider Callback" and "(TOS)"). This has been necessary in the past to enable debugging.

Now that we have tracing available (soon), we should:
 - revise the information we're logging (should not contain PII)
 - move it over to tracing instead

We might need to setup tracing for `express.Request`, happy to help with that.

/cc @AlexTugarev

**Comment by roboquat** [comment]
@geropl: Cannot schedule issue - issue does not belong to a team. Use /team to specify one.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7108#issuecomment-988060658):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by AlexTugarev** [comment]
Reducing technical debt with this auth would be a great thing!

**Comment by geropl** [comment]
IMO in the meantime we learned that:
 - it might be nice to add tracing for login (all HTTP requests in general!)
 - we don't want to remove the logging we have in place to maintain the "totality" quality of loggin
