### ISSUE TITLE
Items in bottom of vscode are unclickable on touchscreens

### ISSUE THREAD

**Issue by jwpjrdev** [gitpod-io/gitpod#7129]
### Bug description

Buttons down at the bottom of VS Code are unclickable on touchscreens. In the attached screenshot, "YAML" and "Layout: U.S." are examples. When tapped/clicked, their background turns grey but nothing is shown. On a laptop, these work just fine.

![24F597B5-28E4-4D6C-AFD9-7B7284F405C2](https://user-images.githubusercontent.com/39033698/145255703-3ca9ebdc-eb0b-4231-9f3c-7263f6db60f1.jpeg)

### Steps to reproduce

1. Open a workspace on an iPad or similar
2. Try tapping one of the buttons
3. Be sad

### Expected behavior

It should show the relevant content!

**Comment by pawlean** [comment]
I can replicate this. As a workaround, can you connect a mouse/touch pad whilst you use your iPad? That usually works for me.

**Comment by pabloa40** [comment]
vscode.dev has the same problem on ipad.

**Comment by jwpjrdev** [comment]
Good. This hasn't been an issue lately. Might've been a VS Code bug fix.
