### ISSUE TITLE
Fix "Flash Of Unstyled Content" in new login screen

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#7138]
### Bug description

There is a "Flash Of Unstyled Content" in Gitpod's new context-aware login screen.

Screencast (where I reload multiple times to show the problem):
https://youtu.be/Z8RAFGaXHuY

### Steps to reproduce

1. Make sure you're rolled into the new login screen experiment (in a browser console on gitpod.io)

```js
localStorage['gitpod-ui-experiments'] = '{"login-from-context-6826":true}';
```

2. Log out of gitpod.io

3. Visit https://gitpod.io/#https://github.com/gitpod-io/gitpod and see the new login screen

There is a "Flash Of Unstyled Content" when you (re)load it (i.e. it first renders something, then re-renders something different, causing a briefly unstable UI).

Here is a screencast where I refresh multiple times to show the problem:
https://youtu.be/Z8RAFGaXHuY

### Expected behavior

The initial rendering should be stable (i.e. render the correct UI in one shot).

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7138#issuecomment-991995191):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
