### ISSUE TITLE
Wrong Release Notes in the IDE (April)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#714]
**Describe the bug**
In the IDE, when I open Help > Release Notes, I get the ones from April (and the only other notes available are from February):

https://youtu.be/bqVcFspDxRk

Instead, I should see the most recent one from July, and also see the one from June.

**To Reproduce**
1. Open Help > Release Notes

**Expected behavior**
I should see the latest Release Notes by default (July), and also have the ones from June, in addition to April and February.

**Comment by jankeromnes** [comment]
Found the issue: The Release Notes viewer fetches https://www.gitpod.io/release-notes/all.json, which doesn't get updated.

**Comment by svenefftinge** [comment]
IIRC there was an issue with the images
