### ISSUE TITLE
Unify all my workspaces on gitpod.io/workspaces

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#7140]
When visiting `gitpod.io/workspaces`, it happens quite often that it get's unclear where I find a recent workspace item.

<img width="1356" alt="Screen Shot 2021-12-09 at 10 09 07" src="https://user-images.githubusercontent.com/914497/145366994-f8984219-a3b9-4618-9cde-7e38f03292f6.png">

It takes 4 clicks and page loadings to find the list of workspaces for the Gitpod project. This I have to repeat each time I navigate to the personal list of workspaces, and it slows down the navigation a lot. 

I'd like to propose merging all my workspace items from all projects under `/workspaces`. Perhaps it would then make sense to have another tag on the workspace item to make clear which project this workspace belongs to, but that might also be unnecessary as there is a repo URL in there.

**Comment by jankeromnes** [comment]
> It takes 4 clicks and page loadings to find the list of workspaces for the Gitpod project.

Isn't it just 1 click?

<img width="1356" alt="active-in-team" src="https://user-images.githubusercontent.com/599268/145368862-66c0ee14-19e0-4273-ac71-2d7e59341c31.png">

**Comment by AlexTugarev** [comment]
> Isn't it just 1 click?

TBH, that 1-liner is usually ignored by me, especially as there is a green dot, which somehow indicates a state to me and I'm not expecting navigation to be included.

**Comment by jankeromnes** [comment]
> TBH, that 1-liner is usually ignored by me, especially as there is a green dot, which somehow indicates a state to me and I'm not expecting navigation to be included.

Thanks a lot for the feedback 🙏 then I think we should make this message more obvious / visible.

**Comment by gtsiolis** [comment]
Closing this as it has been resolved in https://github.com/gitpod-io/gitpod/pull/7606.
