### ISSUE TITLE
We encountered a lot of problems in offline deployment

### ISSUE THREAD

**Issue by Hyakusenrenma** [gitpod-io/gitpod#7143]
### Bug description

![image](https://user-images.githubusercontent.com/24557078/145371666-e0c81c9c-56b1-4311-bbd5-a934f3679f77.png)
kubectl  logs ws-manager-7db4f76577-bmjh9 -n gitpod ws-manager
![image](https://user-images.githubusercontent.com/24557078/145371902-a7f8bb11-7f7c-4df2-a988-2705045bfd57.png)
![image](https://user-images.githubusercontent.com/24557078/145372226-b5221966-6d22-4b05-ae97-383693742e32.png)
![image](https://user-images.githubusercontent.com/24557078/145373742-b4aa3afe-afcc-4de6-bd13-8d9ed10f0784.png)

### Steps to reproduce

on offline 
helm install -f values.custom.yaml gitpod ./ --version=0.10.0 -n gitpod --debug

### Anything else?

Whether to provide offline deployment plan？

**Comment by sagor999** [comment]
Can you share your `values.custom.yaml` file?
