### ISSUE TITLE
Feedback Issue: Local Companion App

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7146]
An issue for collecting feedback on the local companion app: https://www.gitpod.io/docs/develop/local-companion

**Comment by loujaybee** [comment]
Explore whether it's possible to use local companion to integrate with client git apps like git_fork and git_extensions [[1](https://twitter.com/andymac4182/status/1468900406713479176?s=20)]

**Comment by akosyakov** [comment]
> Explore whether it's possible to use local companion to integrate with client git apps like git_fork and git_extensions [1]

You can mount Gitpod workspace into your local machine, but it can be slow.
