### ISSUE TITLE
Dialog not always shown after timeout

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#715]
When a workspace times out while I have closed my laptop (and sometimes also when the tab didn't have focus) I see no dialog, but only the offline status bar.

Reloading the page will start the workspace again, but users are probably not aware of that.
We should check the status and show the dialog when the window gets activated again.

**Comment by alesanchezr** [comment]
It happens all the time to 4Geeks students, the just close the laptop and go to sleep.

The next day they start working without noticing the yellow bar. 

After a while they realize is offline and they to refresh the website to reconnect and they loose all the updates they did while the yellow bar was showing.

**Comment by jankeromnes** [comment]
So sorry about that, losing your work is the worst experience. 😞 Hopefully we'll be able to improve the UX here soon.

A workaround that I use in order not to lose work in such an offline workspace tab is to:
1. keep the no-dialog offline tab open (and note the workspace ID)
2. open https://gitpod.io/workspaces/ in a new tab
3. find the workspace (using the ID), and click `Start`
4. once it's starting, you can close the new tab that was just opened, and return to the old offline tab

You'll notice that the offline tab now shows a dialog, indicating that it noticed the workspace is starting again. You'll then be able to use it to continue your work online.
