### ISSUE TITLE
launch of US workspaces stuck in "Pending" or "Unknown"

### ISSUE THREAD

**Issue by cjensenius** [gitpod-io/gitpod#7152]
### Bug description

As of 9:24a eastern timezone I am unable to launch new or existing workspaces. Existing ones are stuck in "Pending" and new ones only get to "Unknown".

Example new:
salmon-tortoise-4nmjrvtx

Example existing:
sapphire-dog-thlb9719
silver-swallow-av50bjny

Receiving the following error in the console for one of the affected workspaces:
XHR GET https://silver-swallow-av50bjny.ws-us21.gitpod.io/_supervisor/v1/status/supervisor
[HTTP/2 502 Bad Gateway 77ms]

failed to check whether supervisor is ready, trying again... 502 Bad Gateway undefined

![image](https://user-images.githubusercontent.com/1717750/145414674-fff3d6ca-1235-4fd8-b423-dbe091add9d6.png)

### Steps to reproduce

Launch new or existing workspace in US region

### Workspace affected

silver-swallow-av50bjny, sapphire-dog-thlb9719, salmon-tortoise-4nmjrvtx

### Expected behavior

I should see my workspaces launch normally

**Comment by cjensenius** [comment]
Update: Issue may have been transient, I was able to launch a workspace successfully

**Comment by cjensenius** [comment]
I left sapphire-dog-thlb9719 and it eventually launched, so persistence seems to allow a window of opportunity to connect to the gateway successfully and proceed with the workspace launch.

**Comment by aledbf** [comment]
Closing. This was a scale-up issue in the US cluster. Please check https://www.gitpodstatus.com/incidents/pzqk00yk44pp
