### ISSUE TITLE
[dashboard] Disable UI experiments for self-hosted

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#7167]
UI experiments (#7081) allow us to gather user data on alternatives for the UI. But they for self-hosted installations, we should rather provide a single UI flow. Let's disable experiments for SH.

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7167#issuecomment-990742578):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by geropl** [comment]
One way would be to have a `enableUiExperiments` API call that defaults to `false`, and is configurable per `Config`.

To not force every client to ask for this on every page load we could cache this in `localStorage` (together with a timestamp), e.g., and only refresh every day or so.

**Comment by JanKoehnlein** [comment]
I think we implement do that in a simpler way. As these experiments really only make sense for us to drive product decisions. So checking the URL should be sufficient.

**Comment by AlexTugarev** [comment]
works as advertised!

/lgtm
