### ISSUE TITLE
Better feedback when .gitpod.dockerfile is missing

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#717]
I forgot to commit the dockerfile and the error gitpod gave me was:

`Error: Cannot read property 'sha' of undefined`

It should be something like:

`Error: missing .gitpod.dockerfile referenced on the .gitpod.yml`

Here is the repository commit with the error: 
https://github.com/4GeeksAcademy/html-exercises/tree/023b2c9672a64fe792696d0ae0e21fa128bbbcf5

**Comment by jankeromnes** [comment]
Thanks a lot for filing this issue! I totally agree with you.

I also saw this happen once with a repo where the `.gitpod.yml` mentioned `file: .gitpod.dockerfile` and the actual file was called `.gitpod.Dockerfile`... 😐

**Comment by meysholdt** [comment]
I ran into this, too, today. had a type in my dockerfile name.
