### ISSUE TITLE
[vscode-insiders] fix nightly tag resolution

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#7174]
### Bug description

We need to pin oci-tool in server dockerimage and check that it works for VS Code Insiders. After this change is deployed by meta, we will revert pinning of insider image.

### Steps to reproduce

See above.

**Comment by akosyakov** [comment]
@jeanp413 will you revert changes to config map for latest version and we deploy it in 1 hour?

**Comment by jeanp413** [comment]
yes, already created a PR https://github.com/gitpod-io/gitpod/pull/7209
