### ISSUE TITLE
.gitpod.yml doesn't respect the SHA of a custom Docker image

### ISSUE THREAD

**Issue by jelaniwoods** [gitpod-io/gitpod#7179]
### Bug description

I mentioned this issue previously on the [community forum](https://community.gitpod.io/t/unable-to-open-workspaces-that-use-custom-docker-image/5707/12) but it hasn't been resolved despite the fix in https://github.com/gitpod-io/gitpod/pull/7052.

Previously, I was able to reference a Docker image by using the commit SHA in the `.gitpod.yml` file.

```yml
image: jelaniwoods/appdev2021-vanilla-rails@sha256:35d5756428cbae11f43a94c92d6c384626b1ead2287738299b6010c4e588e781

```

Now it appears the SHA is ignored when the workspace is created. This is apparent because the `latest` tag for the Docker image has Ruby version `2.7.2` installed and the image referenced by the SHA has Ruby `2.7.3` installed.

<img width="945" alt="Screen Shot 2021-12-10 at 5 18 23 PM" src="https://user-images.githubusercontent.com/17581658/145652965-8d4f37df-aa1c-4ed1-8d2c-22217c53a47a.png">

I've narrowed it down to the SHA in the `.gitpod.yml` file because if I tag the docker image with a different name (`jelaniwoods/appdev2021-vanilla-rails-hotfix` in my screenshot) the workspace creates and references the correct image.

![same-mg](https://user-images.githubusercontent.com/17581658/145653220-38e8bb29-cb93-4816-b8f4-77ca53ae0729.png)

You can reproduce this by creating a workspace from this repository: https://github.com/jelaniwoods/vanilla-rails

 

### Steps to reproduce

Create a workspace from this repository: https://github.com/appdev-projects/vanilla-rails

See the error message:
> Your Ruby version is 2.7.2, but your Gemfile specified 2.7.3

### Expected behavior

I expect to be able to specify the SHA of a Docker image in the `.gitpod.yml` file and have that effect the workspace environment.

### Example repository

This repository uses a SHA in the `.gitpod.yml` and the correct version of the image is not used : https://github.com/appdev-projects/vanilla-rails

This repository uses a tagged version of the same image **without** a SHA and the there is no issue fetching the correct version of the image: https://github.com/jelaniwoods/vanilla-rails

**Comment by ajhalili2006** [comment]
There's also a related feature request regarding that, which cache validation can sometimes be a pain: https://github.com/gitpod-io/gitpod/issues/7149
