### ISSUE TITLE
[CLI] Update `gp init`.

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#719]
- It should propose Dockerfile first.
 - the proposed name should be `.gitpod.Dockerfile`
 - leave out the checkout and workspace location.

**Comment by jankeromnes** [comment]
Totally agree!

Also we could make the suggested defaults smarter (detecting the type of project with a few simple heuristics), and add a `gp init --auto` mode.

But don't you mean `.gitpod.Dockerfile` instead of `gitpod.Dockerfile`?
