### ISSUE TITLE
Epic: First-class Command Line

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7193]
This is a placeholder for a future epic/bet, more details coming soon: 

Notes: 
* Completing this likely gives us a much better experience for Vim / Emac users also. 

Related: 
* https://blog.console.dev/cli-first-devtools/
* https://clig.dev/
* Local companion GA https://github.com/gitpod-io/gitpod/issues/7185

**Comment by buggtb** [comment]
Would certainly be useful, personally I'd vote for spacemacs to give you a vim/emacs hybrid, but whatever, some form of Mosh/SSH & Terminal IDE support would be nice.

**Comment by loujaybee** [comment]
Closing this, as overlapped heavily with https://github.com/gitpod-io/gitpod/issues/7185, will use that epic / issue to track introduction of command line, etc going forward.
