### ISSUE TITLE
Bitbucket integration - Permissions expire at least once per day automatically

### ISSUE THREAD

**Issue by fr-esco** [gitpod-io/gitpod#7196]
### Bug description

At least once per day, permissions granted to Gitpod for Bitbucket integration get reset for no apparent reason.

Usually, I become aware of this because of an auth error I get when I try to push my work.

So, I have to disconnect and reconnect Bitbucket from the Integration dashboard. This step is pretty fast, because credentials are not required again and no new tokens are issued by Bitbucket.

### Steps to reproduce

1. Connect Bitbucket
2. Create or Open any Workspace
3. Wait at most 24 hours
4. Try to push any commit

### Workspace affected

cyan-echidna-eskb066m.ws-eu23.gitpod.io

**Comment by AlexTugarev** [comment]
Thanks for reporting @fr-esco!

I'm trying to reproduce and see what's happening there. 

OAuth token from bitbucket.org are supposed to get refreshed automatically, so there might be a new issue or a regression happening here.

**Comment by AlexTugarev** [comment]
Hi @fr-esco! I tried to reproduce and followed the description. Just a couple of minutes ago I did the last step after not using BB for +1 day. And I cannot see any issues. 

Checking the logs shows, that it seems to work nicely in general. Last entry is for my account BTW
<img width="777" alt="Screen Shot 2021-12-15 at 07 27 51" src="https://user-images.githubusercontent.com/914497/146135147-d79bb569-01e4-42a2-88ef-2ce72cdade1f.png">

Could you provide more details on your workflow, please? Is it a repo in your account that you are working on? Which git operations are affected? Perhaps a screenshot and the timestamp of such an event?

**Comment by fr-esco** [comment]
- I use Bitbucket on cloud, the one provided directly by Atlassian at bitbucket.org.
- My organization has no customizations nor policies in place.
- I use Google SSO to sign in Bitbucket
- No particular operations are involved.. sometimes _push_, sometimes _fetch_, ...

I don't know if it can be useful, but I remember that I started to experience this issue some time ago, when I added my GitHub account to Gitpod Integrations. GitHub credentials are refreshed automatically without problems, but Bitbucket sometimes expires.

**Comment by fr-esco** [comment]
It's just happened again while pushing 3 commits at once:
- workspace lavender-rodent-f3uirenb.ws-eu23.gitpod.io
- remote: Invalid username or password   fatal: Authentication failed for 'https://bitbucket.org/<workspace>/<repo>.git/'
- timestamp: about 2021-12-16T08:31 Z

**Comment by JanKoehnlein** [comment]
@fr-esco Did you experience this again?

**Comment by fr-esco** [comment]
Yes, more than once per day.

**Comment by AlexTugarev** [comment]
Thanks for reporting the new timestamp. I could indeed find an issue with your tokens. 

```
"Error: Found more than one active token for Public-Bitbucket and user (...)
    at TypeORMUserDBImpl.<anonymous> (/app/node_modules/@gitpod/gitpod-db/lib/typeorm/user-db-impl.js:328:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@gitpod/gitpod-db/lib/typeorm/user-db-impl.js:19:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
```

That's an unexpected situation where no token is returned.

**Comment by AlexTugarev** [comment]
@fr-esco, one thing I just spotted is that there were two server instances from both clusters (US and EU) handling related requests at that time. is there any chance you've been using any VPN service, etc.?

**Comment by fr-esco** [comment]
@AlexTugarev , I use the same PC on the same Internet connection and don't activate any firewall or VPN.

No filters are configured on Bitbucket.
