### ISSUE TITLE
Epic: Alert users of new Gitpod features

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7203]
Some features, like JetBrains are introduced into the application without users knowing. This feature would be to notify users about new product features from within Gitpod.

**Comment by gtsiolis** [comment]
See also https://github.com/gitpod-io/gitpod/issues/3956 and some relevant early drafts in https://github.com/gitpod-io/gitpod/pull/5806#issuecomment-926501804.

**Comment by loujaybee** [comment]
Closing as duplicate of: https://github.com/gitpod-io/gitpod/issues/7537
