### ISSUE TITLE
List all third-party components and licenses

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7214]
We need to list all Third-Party components. In a next step we should check the OS licenses to ensure we’re not promising our customers a Gitpod that they need to purchase licenses for tools like MySQL.

Perhaps adding a `gitpod-installer licenses` command that exports all the licenses used. This should include all Golang/Helm dependencies used in the Installer and potentially any other dependencies used in the Gitpod project

cc @KlasenK @corneliusludmann @metcalfc @atduarte
Thread https://gitpod.slack.com/archives/C01KLC56NP7/p1639410862397000

**Comment by corneliusludmann** [comment]
Is this still an issue? Based on the internal Slack discussion linked above, I would say that this is not important anymore!?
