### ISSUE TITLE
H2 database console is not shown on Gitpod link

### ISSUE THREAD

**Issue by dahamv** [gitpod-io/gitpod#722]
This is related to the issue https://github.com/gitpod-io/gitpod/issues/721
My Spring Boot project has an H2 in-memory database. And tomcat should show the console for the H2 DB in this link https://localhost:3000/h2-console
But when I add the /h2-console part in the link provided by Gitpod like this
https://3000-ef220492-ca32-4ade-80d7-501725160057.ws-ap0.gitpod.io/h2-console
I get a 404 - Not Found Error

Thanks

**Comment by jankeromnes** [comment]
Thanks for this report @dahamv!

I'm stealing this issue as I think I've found the root cause: `application.properties` seems to be missing `spring.h2.console.enabled=true`.

I'll send a Pull Request to your repository directly. 🙂
