### ISSUE TITLE
Commenting in .jsx files (facebook react) not working correctly with cntrl + /

### ISSUE THREAD

**Issue by hotelbuddy-online** [gitpod-io/gitpod#724]
**Describe the bug**
When you try to comment out a html tag in the render function of a react component using cntrl + /, it tries to comment it using js syntax (// at the beginning of the line) as opposed to react html commenting - `{/* <p>hello world</p> */}`

**To Reproduce**
In any react project, for example 
https://gitpod.io/#https://github.com/simonqian/react-helloworld
open App.jsx
place cursor before `<div>simon, helloworld!!!</div>`
press cntrl and / to comment

**Expected behavior**
`{/* <div>simon, helloworld!!!</div> */}`

**Comment by akosyakov** [comment]
`ctrl + /` stands for `Toggle Line Comment`, why would you expect `Block Comment`?

You should use `Toggle Block Comment` command instead.

**Comment by hotelbuddy-online** [comment]
@akosyakov This doesn't really work if tag is over multiple lines.  e.g.
`<div
      id="hw"
  >simon, helloworld!!!</div>`
There doesn't really seem to be a way of commenting this using Toggle block Comment.  Straight VS Code works fine using cntrl + /

**Comment by svenefftinge** [comment]
We have switched to the VS Code extension for typescript.
