### ISSUE TITLE
Route users to Discord for support

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7240]
[We're moving away from Discourse](https://community.gitpod.io/t/announcement-were-moving-away-from-discourse-forum/5698?u=kbrennan).

There are a few areas where we still route users to the Discourse forum and should update to Discord:
1. [Bug report](https://github.com/gitpod-io/gitpod/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml)
2. [Issue template](https://github.com/gitpod-io/gitpod/blob/main/.github/ISSUE_TEMPLATE/config.yml)
3. [Readme](https://github.com/gitpod-io/gitpod/blob/main/README.md)

There are also a couple places where it's tracked as data, I'm not sure if it's being used, we'll need @gitpod-io/engineering-meta to confirm:
1. [Helm chart](https://github.com/gitpod-io/gitpod/blob/main/chart/values.yaml)
2. [Installer](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/server/configmap.go)
* both write data to a [server-configmap](https://github.com/gitpod-io/gitpod/blob/3e628a011441a704ce724d9a83cde787109e6201/components/server/src/config.ts#L179)

**Comment by ghuntley** [comment]
- [ ] Also gitpod/vscode needs updating to remove the references in the context menus.

**Comment by roboquat** [comment]
@ghuntley: The label(s) `team: ide` cannot be applied. These labels are supported: `team: IDE, team: meta, team: workspace`

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7240#issuecomment-994565876):

>- [ ] Also gitpod/vscode needs updating to remove the references in the context menus.
>
>/team ide


Instructions for interacting with me are available [here](https://github.com/gitpod-io/gitbot/blob/main/plugins/customlabels/README.md). If you have questions or suggestions related to my behavior, please file an issue against the [gitbot](https://github.com/gitpod-io/gitbot/issues/new) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7240#issuecomment-994681201):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
> Also gitpod/vscode needs updating to remove the references in the context menus.

I believe it was done last week. cc @filiptronicek ?

**Comment by filiptronicek** [comment]
@akosyakov correct, we have made the changed in https://github.com/gitpod-io/openvscode-server/pull/256. It should already be fixed in VS Code Insiders, @ghuntley

**Comment by roboquat** [comment]
@ghuntley: The label(s) `team: ide` cannot be applied. These labels are supported: `team: IDE, team: meta, team: workspace`

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7240#issuecomment-994565876):

>- [x] Also gitpod/vscode needs updating to remove the references in the context menus.
>
>/team ide


Instructions for interacting with me are available [here](https://github.com/gitpod-io/gitbot/blob/main/plugins/customlabels/README.md). If you have questions or suggestions related to my behavior, please file an issue against the [gitbot](https://github.com/gitpod-io/gitbot/issues/new) repository.
</details>
