### ISSUE TITLE
Workspace stuck in "stopping"

### ISSUE THREAD

**Issue by AnaG0307** [gitpod-io/gitpod#7255]
### Bug description

I was working on gitpod and the workspace stopped working and requested to refresh the page. I did but then it was not loaded properly. I did try to open it again through the dashboard but when clicking on the workspace it got stuck on "stopping". After a while, the message changed to "preparing" but it doesn't get any further and the pages refreshes itself over and over

### Steps to reproduce

click on the workspace link in the dashboard

### Workspace affected

https://violet-newt-0d2gkakl.ws-eu23.gitpod.io/

### Expected behavior

open the workspace to be able to work on my project

**Comment by John-wallace89** [comment]
Hi I'm seeing the same issue as well with my workspace:
https://gitpod.io/sapphire-chickadee-v75mlfae.gitpod.io/

**Comment by Jbachtiger** [comment]
Hi, I have experience the same issue. My workspace link is https://gitpod.io/start/#maroon-woodpecker-g6aa7v66

**Comment by finnsterfran** [comment]
I'm have the same issue [workspace](https://gitpod.io/start/#silver-horse-gmesmakg)

**Comment by pawlean** [comment]
Thanks all for flagging! I've pinged folks internally 🙏🏼

**Comment by lukaszkukla** [comment]
Hi Guys,
I am having this issue over 2 days now: [workspacy](https://gitpod.io/start/#aqua-boa-vowmhc0h)

**Comment by axonasif** [comment]
> Hi Guys,
> I am having this issue over 2 days now: [workspace](https://gitpod.io/start/#aqua-boa-vowmhc0h)

@pawlean can you please forward his case 😁?

**Comment by princerachit** [comment]
All workspaces mentioned above are stopped now. Closing this issue

**Comment by axonasif** [comment]
@xwjisfather your workspace appears to have successfully stopped. Sometimes it can take long if your /workspace directory has lots of file.

**Comment by Three000** [comment]
https://three000-epalssrgithub-bziblp2tfge.ws-eu118.gitpod.io/
same issue, has been five hours. Thanks!
