### ISSUE TITLE
No selection state in Project Settings for older GitLab Projects

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#7258]
### Bug description

In the newly-introduced Project Settings page, there is a sub-menu with two sub-sections:
- General
- Configuration

Clicking on them works reliably, however, for older GitLab Projects (added before the support of both Project slug _and_ Project name), the selected sub-section doesn't show as selected:

| Old GitLab Project (no selection state) | New Project (works fine) |
| --- | --- |
| <img width="1439" alt="Screenshot 2021-12-15 at 18 36 11" src="https://user-images.githubusercontent.com/599268/146236738-59baf892-79f7-492e-b9d9-a53a31eb9335.png"> | <img width="1440" alt="Screenshot 2021-12-15 at 18 36 30" src="https://user-images.githubusercontent.com/599268/146236763-c52d6297-6a3f-412e-a48a-ece03350c575.png"> |
| <img width="1440" alt="Screenshot 2021-12-15 at 18 36 20" src="https://user-images.githubusercontent.com/599268/146236758-062dcd25-e710-4133-8bd7-fb7b4fe93443.png"> | <img width="1440" alt="Screenshot 2021-12-15 at 18 36 38" src="https://user-images.githubusercontent.com/599268/146236770-e407fb17-a41d-4b58-8989-8c7cf4bd033e.png"> |

### Steps to reproduce

- Open the Project Settings for a Project that was added before Project slug + name support

**Comment by gtsiolis** [comment]
Duplicate of https://github.com/gitpod-io/gitpod/issues/7231? I should have cc'ed you in that issue. 🙈

**Comment by jankeromnes** [comment]
Woops! Indeed duplicate 😅 (I seem to never learn about searching issues before filing a new one 🙈 it was so much better when GitHub just showed you similar issues...)
