### ISSUE TITLE
Move project removal action under project settings

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7273]
### Problem 

Project settings were recently introduced with incremental prebuilds settings in https://github.com/gitpod-io/gitpod/pull/7031 (Cc @jankeromnes @geropl) but currently the only way to remove a project can happen through the project more actions button on the projects list as the product didn't have project settings when the project removal action was added in https://github.com/gitpod-io/gitpod/pull/6185.

### Proposal

Naturally, such actions are better fit under project settings, so moving this action under project settings seems optimal. 

Let's add this below incremental prebuilds section under general settings.

> Section title: Remove Project
> Section description: Removing this project will also remove all associated data with this project, including workspaces. 

Ideally, once we implement https://github.com/gitpod-io/gitpod/issues/5517, prebuilds and prebuilds configuration could be also removed and disabled. See also https://github.com/gitpod-io/gitpod/issues/7009. 💡

**Comment by jankeromnes** [comment]
Should the project removal also have a confirmation prompt (e.g. where it says "Type `my-project`:"), or can it happen immediately like the current removal feature?

**Comment by JanKoehnlein** [comment]
@jldec do we need visual design for this or can this be scheduled as is?

**Comment by geropl** [comment]
@gtsiolis I'm trying to understand what status this is in. Do I understand correctly that:
 - the design thinking is done
 - we "just" need to execute on it? :thinking: 
If yes: Then I'd like to move it from "In progress" to our (grouped) Backlog, so a) it does not clutter groundwork, and b) still remains visible.

**Comment by gtsiolis** [comment]
@geropl you're right on the comment in https://github.com/gitpod-io/gitpod/issues/7273#issuecomment-1096288654! Let me also grab this opportunity to break down the design thinking behind the current status from UX perspective in case it helps. 💭 

1️⃣  The issue does _not_ have the ~**[needs visual design](https://github.com/gitpod-io/gitpod/issues?q=is%3Aissue+is%3Aopen+label%3A%22needs+visual+design%22)** label or exist in the **[product design board](https://github.com/orgs/gitpod-io/projects/29)**, which helps make it clearer that this issue does not require any further design input before picking it up for implementation, unless you think it could use some clarification before opening a PR.

2️⃣  IMO, This is one of the issues that does not necesarily need design specs in Figma as :a: it specs can be clearly expressed using text by reusing existing patterns (see proposal in the issue description) and :b: it allows some room for improvization or creative thinking from engineering perspective for things that could have been also missed from design perspective. In the past, we've picked up many issues without a design spec file or clear proposal in the issue before which is ok, as long as the overhead during the code review is not expected to keep the PR open for long.

3️⃣ From design perspective the first iteration (skateboard) of this is clearly outlined in the proposal in the issue description:

> Let's add this below incremental prebuilds section under general settings.
>
> Section title: Remove Project
> Section description: Removing this project will also remove all associated data with this project, including workspaces.

4️⃣ The last point in the proposal can be considered out of the scope of the issue or could up for discussion. Open to feedback or thoughts!

> Ideally, once we implement https://github.com/gitpod-io/gitpod/issues/5517, prebuilds and prebuilds configuration could be also removed and disabled.

---

To add some clarification for points 1️⃣ and 2️⃣, this is what the final design could look like. **Everyone is encouraged to ask questions for clarifications if a text-based proposal is not clear enough or not easy to visualize beforehand**. See [relevant section](https://www.notion.so/gitpod/Enabling-Team-Product-Design-33f7d217be0d4db5a0666e7c99aece19#8c019a5f02104fd9ba8bc9ca44d77b57) in the product design team page (internal).

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="Screenshot 2022-04-12 at 1 49 06 PM" src="https://user-images.githubusercontent.com/120486/162958917-34173811-63a2-466a-a9aa-401450eabf06.png"> | <img width="1440" alt="Screenshot 2022-04-12 at 1 52 24 PM" src="https://user-images.githubusercontent.com/120486/162958920-ab64a681-ee9b-4c52-8368-cad1532113f7.png"> |

Also, the confirmation modal on project removal already exists when removing a project from the team page which contains the projects cards. We can safely re-use the same confirmation modal here.

| Remove project from team page | Remove project from project settings |
|-|-|
| <img width="1440" alt="Screenshot 2022-04-12 at 2 08 30 PM" src="https://user-images.githubusercontent.com/120486/162959444-348601aa-e8f8-4509-9eec-50b7b82120ea.png"> | <img width="1440" alt="Screenshot 2022-04-12 at 2 08 20 PM" src="https://user-images.githubusercontent.com/120486/162959445-d550bd9b-ce73-4c56-af49-f4407645ae9f.png"> |

--- 

Looping in (**no-action-required**) the following product teams that have worked in the past with @gitpod-io/product-design as the above could help add some clarification on how we work: 
- @gitpod-io/engineering-webapp 
- @gitpod-io/engineering-ide 
- @gitpod-io/engineering-self-hosted 
- @gitpod-io/engineering-workspace

---

**fyi**: In the spirit of adding more clarification on point 2️⃣, I've added the [following section](https://www.notion.so/gitpod/Enabling-Team-Product-Design-33f7d217be0d4db5a0666e7c99aece19#4678001ac66f430ea8e736ed93566970) (internal) about design specifications on the product design team page.

> ### Specifications
>
> When working with design specifications for a solution, the contents of the design file are considered to be the [single source of truth (SSOT)](https://en.wikipedia.org/wiki/Single_source_of_truth) of the proposal which can be also exported and uploaded in an issue comment or within the issue description.
> 
 >In the spirit of our core value to [ship skateboards](https://www.notion.so/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e), we lean towards shipping the [minimum viable change (MVC)](https://www.notion.so/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e) to improve the user's outcome. This includes also [trusting each other](https://www.notion.so/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e) to pick up issues to work on with minimal design specifications that may contain only a brief outline of the solution using a text-based description by referring to existing and reusable patterns or components. In such cases, designs can be evaluated during code review and help avoid blocking the team from implementing a solution that adds value and can be shipped to users.

**Comment by gtsiolis** [comment]
Closing this as it has been resolved in https://github.com/gitpod-io/gitpod/pull/15316. Cc @selfcontained @jldec
