### ISSUE TITLE
Opening upstream repo directly uses fork config

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#7278]
### Bug description

When I open the vscode or a PR in vscode repo in gitpod it uses the dockerfile from openvscode-server, it should use the default image

### Steps to reproduce

1. open vscode repo or a PR in vscode repo in gitpod
2. :bug: observe it starts to build a docker image configured in openvscode server (fork) instead of using the default image

**Comment by akosyakov** [comment]
It is not a bug, one can configure repos externally. You can find a configuration here: https://github.com/gitpod-io/definitely-gp/tree/master/vscode I guess it is outdated already.

**Comment by jeanp413** [comment]
I see, Is there a way to disable it? I think there should be at least a checkbox in the dashboard

**Comment by jeanp413** [comment]
@akosyakov does it make sense that I want to disable this feature (as you said the image is outdated and I can see repeating in the future) so I can create a new issue as a feature request?

**Comment by akosyakov** [comment]
> @akosyakov does it make sense that I want to disable this feature (as you said the image is outdated and I can see repeating in the future) so I can create a new issue as a feature request?

yes, please open a PR
