### ISSUE TITLE
Codicons Not Working In Simple Browser

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#7293]
### Bug description

This is similar to or the same as #3758 however that issue is closed and the issue is still persistent on `main.2055` and on gitpod.io.

When using Simple Browser or anything else which uses Codicons they don't work. They show up as squares.

<img width="318" alt="Screen Shot 2021-12-15 at 10 37 51AM" src="https://user-images.githubusercontent.com/405585/146569313-571fbb72-fbac-4b24-8ff4-55ff6c27e529.png">

<img width="447" alt="Screen Shot 2021-12-17 at 09 36 18AM" src="https://user-images.githubusercontent.com/405585/146569370-e7bfd2d5-3b20-4a75-a967-883bebc6d65e.png">

This appears to be due to a bad link to the `ttf` file for the font inside the `codicon.css` file.

<img width="1206" alt="codicons_-_bad_link" src="https://user-images.githubusercontent.com/405585/146569651-b9a87162-7c9a-4cd1-8f37-3f139c8bfd68.png">

When I manually edit the `codicon.css` file in my web browser developer tab, and change the URL to a valid one, then the icons show up properly.

<img width="1661" alt="codicons_-_fix_url" src="https://user-images.githubusercontent.com/405585/146570497-88bdc457-38a4-4c57-b474-da8619fdbaeb.png">

### Steps to reproduce

1. Login to gitpod.io
2. Create a new Workspace
3. Once the new workspace has spun up and you're in VS Code hit Apple+Shift+P to bring up the Command Palette, type in Simple Browser and hit Enter.
4. Provide a URL, any URL should work and hit Enter again.
5. Observe the Back, Forward and Reload icons are showing up as squares.

### Expected behavior

I expect that where Codicons icons are used that they show up properly instead of as squares.

**Comment by jeanp413** [comment]
@jimmybrancaccio are you still seeing this? I cannot repo in stable 1.63.2 nor 1.64 insiders

**Comment by jimmybrancaccio** [comment]
Hey @jeanp413, I have 1.63.2 (`main.2085`) and it's still showing squares for me. I made sure to clear out my browsers cache as well. I wonder if being on self-hosted has anything to do with it?

<img width="649" alt="Screen Shot 2021-12-21 at 11 32 59AM" src="https://user-images.githubusercontent.com/405585/146973608-2a6c746d-f58e-44bc-8087-577d21b4aa25.png">

<img width="567" alt="Screen Shot 2021-12-21 at 11 33 09AM" src="https://user-images.githubusercontent.com/405585/146973622-7c97d6b1-c094-4cbb-8280-116d7de69a53.png">

**Comment by jeanp413** [comment]
@jimmybrancaccio on what browser are you seeing this? I tested on chrome

**Comment by jimmybrancaccio** [comment]
@jeanp413 I am on Safari but as noted in my original post it looks like the CSS file may not be using the right path to the `ttf` file.

**Comment by jeanp413** [comment]
I see thanks for the pointer :+1:  I'll check on safari

**Comment by jeanp413** [comment]
I can repro only in safari, chrome and firefox work fine

**Comment by jimmybrancaccio** [comment]
LOL Of course it only happens in the one browser I use 🤦🏼 haha

**Comment by akosyakov** [comment]
@jeanp413 maybe it should be simply reported to upstream?

**Comment by jimmybrancaccio** [comment]
I almost thought it was one of my extensions in Safari but then remembered you replicated the issue in Safari too Jean. I tested within Firefox on my MacPro and I was able to see the icons. That's weird, I wonder what is causing the issue to occur in Safari only... 🤔 

<img width="664" alt="Screen Shot 2021-12-22 at 5 47 24 AM" src="https://user-images.githubusercontent.com/405585/147088641-5a3130c0-6f0d-4113-986d-7dcc89561431.png">

**Comment by jeanp413** [comment]
yeah I'll create an issue upstream, I think it's a CSP issue (only in safari) that it blocks the font to be served by the service worker

**Comment by jimmybrancaccio** [comment]
I think you're right @jeanp413 if CSP is the same as CORS (I'm not sure haha). I just noticed under the Develop menu in Safari there's an option to disable Cross Origin Restrictions, I checked that off and sure enough, the icons are now showing up properly 😁 

<img width="512" alt="Screen Shot 2021-12-23 at 09 11 06AM" src="https://user-images.githubusercontent.com/405585/147259132-39c7c8a6-da11-41a7-be9a-c8aaf3f01283.png">

<img width="861" alt="Screen_Shot_2021-12-23_at_09_10_32AM" src="https://user-images.githubusercontent.com/405585/147259237-0795772d-ae2e-4680-85b7-6eb7a06d110e.png">

**Comment by jeanp413** [comment]
Forgot to linked the upstream issue https://github.com/microsoft/vscode/issues/139674

**Comment by felladrin** [comment]
> Forgot to link the upstream issue: [microsoft/vscode#139674](https://github.com/microsoft/vscode/issues/139674)

I suggest we change the title of this issue to the same used on the issue @jeanp413 created.
- https://github.com/microsoft/vscode/issues/139674

**Comment by jeanp413** [comment]
Fixed in insiders, will be available next stable release

**Comment by devAbreu** [comment]
Thanks to @jimmybrancaccio  answer, I realized that it was the [Allow Cors](https://microsoftedge.microsoft.com/addons/detail/allow-cors-accesscontro/bhjepjpgngghppolkjdhckmnfphffdag) extension that was giving me problems. I disabled it and the icons loaded without problems.

I was working on VS Code 1.89.0 Editor - Browser
