### ISSUE TITLE
[local-companion] support self updating

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#7299]
Right now: 
- either the user should update manually
- or In VS Code Desktop Gitpod extension manages it somehow.

Instead the local companion should support self-updating.

Here is the golang module which can be used a start: https://github.com/sanbornm/go-selfupdate
One can have a look how it was adopted by https://pkg.go.dev/github.com/arduino/arduino-create-agent/updater
It looks we will need to provide new endpoints to enable self updating on `ide.gitpod.io`, so it depends on running the ide proxy.

**Comment by ajhalili2006** [comment]
Question is how do self-updates work if I compiled the Local App from source by myself?
