### ISSUE TITLE
extension massive failed

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#7304]
![image](https://user-images.githubusercontent.com/3759816/146678675-5ff0d81c-3cc6-4849-9859-414ad9b3aaa9.png)

repo: https://azure-heron-4xtibqkx.ws-us23.gitpod.io/

**Comment by corneliusludmann** [comment]
https://www.gitpodstatus.com/incidents/bhv99dsg3pj0

**Comment by gengjiawen** [comment]
Looks fixed now.
