### ISSUE TITLE
Processes spawned by extensions are not stopped on refresh of browser tabs

### ISSUE THREAD

**Issue by timokrae** [gitpod-io/gitpod#7305]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: Version: 1.63.0
- OS Version: Ubuntu 20.04.2 LTS (on gitpod.io)

Steps to Reproduce:

1. Install and activate extension which spawns a .NET process (e.g. omnisharp language server)
2. Refresh the browser tab
3. The old .NET process stays alive but when the extension is activated again a new .NET process is spawned --> now there are two running
4. If you repeat `n` times you can spawn `n` processes

Additional info:

- We are unsure if this only affects .NET processes spawned by `vscode-languageclient`
- The error is not reproducible with a local VS Code on Windows when using the `Developer: Reload Window` command
- We did not find a public extension with this issue. Here is some sample code to trigger this behavior:
  ```ts
  import { ExtensionContext } from "vscode";
  import { LanguageClient, ServerOptions } from "vscode-languageclient/node";

  export function activate(context: ExtensionContext) {
    let serverOptions: ServerOptions = {
      run: { command: "dotnet", args: ["path/to/my.dll"] },
      debug: { command: "dotnet", args: ["path/to/my.dll", "--debug"] },
    };
  
    const client = new LanguageClient("name", serverOptions, {});
    let disposable = client.start();
    context.subscriptions.push(disposable);
  }
  ```

**Comment by timokrae** [comment]
@jeanp413 I tryed that but it did not help.

**Comment by Livven** [comment]
@akosyakov It happens on gitpod.io, but also with our (slightly customized version of) openvscode-server, so it's not specific to Gitpod.

**Comment by jeanp413** [comment]
@timokrae I tested other extension using `LanguageClient` and couldn't reproduce the issue. 
Could you share a repo containing a working extension so I can test directly? or be more explicit about what should I put in `"path/to/my.dll"` in the snippet above as I'm not really familiar with .NET
Thanks.

**Comment by Stefan-J-Hanke** [comment]
maybe related: https://github.com/microsoft/vscode/issues/140697

**Comment by timokrae** [comment]
I fixed the wrong behaviour inside of the extension by memorizing the pid of the spawned dotnet process and killing it if its parent process is killed. Dont know if thats the best solution but it works.
