### ISSUE TITLE
Stuck forever in Acquiring Node (1/3)

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#731]
**Describe the bug**
Today we were about to start class and it seems to be imposible to start an old or new workspace, it gets stuck forever in Acquiring Node.

**To Reproduce**
We are in Florida, USA: Just open any of your current workspaces or create a new one.

**Expected behavior**
Create the workspace and open the IDE.

**Comment by svenefftinge** [comment]
Sorry, we are looking into it for 30 min already. Will tweet and update the status ASAP.
It looks like the two regions our US cluster runs in ran out of resources (GCloud). At least that's the error message we see.

**Comment by svenefftinge** [comment]
We have disabled the load balancing for the US cluster. Which means that users from north America will be forwarded to Europe or Asia. It might all be a little slower, but it works.

**Comment by jankeromnes** [comment]
Thanks a lot! Update re-posted on Twitter: https://twitter.com/gitpod/status/1161657035223683072

**Comment by alesanchezr** [comment]
Thanks for the fast response man 👍 😄

**Comment by svenefftinge** [comment]
Thank you for the patience.

**Comment by PEZ** [comment]
This seems to be happening now again. I'm in Stockholm, if that's relevant to the issue.

**Comment by jankeromnes** [comment]
@PEZ Thanks for reporting this, and sorry about the disruption. I think you were affected by https://github.com/gitpod-io/gitpod/issues/1383.

**Comment by Kronifer** [comment]
Not exactly happening, but slows to a crawl and takes around 5-10 minutes
