### ISSUE TITLE
Link the username that added the project

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#7310]
As a follow-up to https://github.com/gitpod-io/gitpod/issues/5119, there should be a link to the Git provider profile of the username that added the project.

This was mentioned here[[1](https://github.com/gitpod-io/gitpod/pull/5128#discussion_r751438719)] and here[[2](https://github.com/gitpod-io/gitpod/pull/5128#discussion_r771569685_)] with a description: 

> Users with multiple integrations will be shown using the user-id of the first signup, which is not necessarily the user-id for the integration of the repo in question. E.g I used a different username for GitHub vs. GitLab and the "already added" message is showing my GitHub userid even though the repo is on GitLab.

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7310#issuecomment-997743074):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
(Should've assigned myself using prow.)
