### ISSUE TITLE
Document experimentalNetwork: true for .gitpod.yml on the Gitpod website.

### ISSUE THREAD

**Issue by apolopena** [gitpod-io/gitpod#7323]
### Bug description

Currently at the time of writing this, searching the Gitpod documentation for the string `experimentalNetwork: true` only turns up documentation on implementing tailscale and nothing else. 

### Steps to reproduce

 Search the [Gitpod Docs](https://www.gitpod.io/docs/) for the string `experimentalNetwork: true`

### Expected behavior

The documentation on the Gitpod website should describe what setting `experimentalNetwork: true` in `.gitpod.yml` actually does.

**Comment by nooobcoder** [comment]
@apolopena 
[Reference](https://github.com/gitpod-io/gitpod/pull/6409), if the workspace had a new experimentalNetwork: true [config flag set.](https://github.com/gitpod-io/template-tailscale/blob/1091c778c7e608d58e6e3cb1d494c73d5b255558/.gitpod.yml#L12)
