### ISSUE TITLE
Bitbucket provider does not return isDefault 

### ISSUE THREAD

**Issue by jmls** [gitpod-io/gitpod#7325]
### Bug description

when trying to run a prebuild in the dashboard , a bitbucket repo returns the error 

**"Error: Could not find a default branch in repository"**

### Steps to reproduce

![image](https://user-images.githubusercontent.com/929523/146903438-63ae42a8-83eb-4d4f-bc76-8c4ea7c0cff9.png)

press the "run preview" button and you get this error

![image](https://user-images.githubusercontent.com/929523/146903663-53eda108-bd03-4dd5-8059-ac0def555633.png)

### Workspace affected

any bitbucket repo

### Expected behavior

it should behave the same way as gitlab and github - ie run a prebuild

### Anything else?

It looks like the Bitbucket API on a repo / branch does not return the information needed to check if the branch is the default.

the gitlab code is 

`return { host, owner, name, cloneUrl, description, avatarUrl, webUrl, defaultBranch };`

the bitbucket code is

`return { host, owner, name, cloneUrl, description, avatarUrl, webUrl };`

There is an api call in BitBucket to obtain the default branch , but this is not implemented in the BitBucket provider code from gitpod.

**Comment by gtsiolis** [comment]
Thanks for reporting this, @jmls!

This is probably related to https://github.com/gitpod-io/gitpod/issues/7366 as the default branch is also not detected in the _Branches_ page.

Cc @AlexTugarev @jldec because https://github.com/gitpod-io/gitpod/pull/7251

**Comment by roboquat** [comment]
@gtsiolis: GitHub didn't allow me to assign the following users: trumbitta.

Note that only [gitpod-io members](https://github.com/orgs/gitpod-io/people), repo collaborators and people who have commented on this issue/PR can be assigned. Additionally, issues/PRs can only have 10 assignees at the same time.
For more information please see [the contributor guide](https://git.k8s.io/community/contributors/guide/first-contribution.md#issue-assignment-in-github)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7325#issuecomment-1001666341):

>/assign @trumbitta


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
