### ISSUE TITLE
Remove UI experiment for prefixed login - adopt change for all users

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7329]
https://github.com/gitpod-io/gitpod/issues/6826#issuecomment-987786422 was implemented as an A/B test.
The test showed that the change improved conversion to signup.

We can remove the experiment and make the change available to 100% of users who are presented with a login via this route.

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7329#issuecomment-998748343):

>/schedule
>/assign @laushinka 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by laushinka** [comment]
/assign 
(Curious if another assign command will make roboquat move this to in progress.)
