### ISSUE TITLE
I deleted my gitpod user by mistake, can't get back in

### ISSUE THREAD

**Issue by julioLondono** [gitpod-io/gitpod#733]
If i try to clone a repository with Github it gives me a message `Error: User has been deleted.`

How can I get back in?

**Comment by julioLondono** [comment]
@jankeromnes Hi, could you help me with thi issue.

Thanks,

**Comment by jankeromnes** [comment]
Hi @julioLondono, sorry that you're seeing this issue. Could you please describe exactly what you're trying to do? (E.g. "opening repository XYZ in Gitpod by doing ABC"), and where this error is being displayed? (A screenshot would be helpful.)

Now, looking into our database, your user is still there, and in fact it seems that you have two distinct users for the same GitHub account. I didn't think this was possible:

```
+--------------+--------------------------+
| name         | creationDate             |
+--------------+--------------------------+
| julioLondono | 2019-08-13T23:57:51.294Z |
| julioLondono | 2019-08-14T00:00:51.106Z |
+--------------+--------------------------+
```

Maybe that's a bug on our side. By the way, it seems like the first user doesn't have any workspaces (or they deleted all their workspaces), while the second user has 2 workspaces.

**Comment by jankeromnes** [comment]
We can help you recover any work that wasn't deleted, but I'm also curious to learn more about the `Error: User has been deleted.` message, and about the duplicate Gitpod user entry.

**Comment by julioLondono** [comment]
@jankeromnes thanks for your reply, I created a second account in Github with a different email to be able to create a new Gitpod repo, but when I cloned the repo from the old account it got connected back to the old account and displayed the same error message, I fixed the problem by deleting all my history and cookies on my browser.
The problem started when Gitpod froze up and I thought I had a bad file that was causing problems so I deleted everything to start over, that is when I got the message.

**Comment by FreePhoenix888** [comment]
Login into your account with github in incognito
