### ISSUE TITLE
[observability] Team Workspace / Success Criteria dashboard -> no data

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7335]
### Bug description

The dashboard is empty, panes should display data.

### Steps to reproduce

[Browse here](https://grafana.gitpod.io/d/jgjwvIc7k/success-criteria?orgId=1)

### Workspace affected

n/a

### Expected behavior

Should contain data

### Example repository

n/a

### Anything else?

Is the datasource set correctly [here](https://github.com/gitpod-io/gitpod/blob/93ed40d14ad2fe166a9f2594e920adec48c0718f/operations/observability/mixins/workspace/dashboards/success-criteria.json)?

**Comment by roboquat** [comment]
@kylos101: Issue scheduled in the workspace team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7335#issuecomment-998811395):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
