### ISSUE TITLE
Add a way to opt-out of using definitely-gp for workspaces

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#7336]
## Is your feature request related to a problem? Please describe

I was trying to open a new workspace of upstream vscode repo and got surprised that it was using some custom docker image instead of the default image, furthemore this custom image is broken and I couldn't open the workspace at all.
Later I found there's this global configuration repo `definitely-gp` https://github.com/gitpod-io/gitpod/issues/7278#issuecomment-996532619

## Describe the behaviour you'd like

Add an option (in the dashboard?) to opt-out of using `definitely-gp`, I don't want a custom image to avoid wasting time waiting for it to build plus it's broken currently and I can see it breaking again in the future

**Comment by svenefftinge** [comment]
will be resolved by #8473
