### ISSUE TITLE
cannot resolve workspace image: hostname required

### ISSUE THREAD

**Issue by sedattanir** [gitpod-io/gitpod#7338]
### Bug description

Request startWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: hostname required

I didn't solve this error.

Ubuntu Server 20.04.3(1 master, 2 node), k3s latest, main.2071

https://media.discordapp.net/attachments/902831061220851712/922923814726295572/unknown.png?width=1440&height=638

### Steps to reproduce

After the installation is completed, the new project creation page is stuck. It gives this error when I create workspace.

**Comment by apolopena** [comment]
I have the same issue.

**Comment by Mr-Pete** [comment]
Same here

**Comment by carlosal1015** [comment]
Me too with [this configuration](https://github.com/cpp-review-dune/introductory-review/blob/main/.gitpod.yml) and [both](https://github.com/cpp-review-dune/introductory-review/blob/main/src/Docker/TeXLive.Dockerfile) [images](https://github.com/cpp-review-dune/introductory-review/blob/main/src/Docker/AUR.Dockerfile).

**Comment by Mr-Pete** [comment]
Try again Lads, up and running for me again

**Comment by aledbf** [comment]
Please check https://www.gitpodstatus.com/incidents/ygpkvrkl2nkf

We see sporadic 503 responses from docker hub pulling images.

**Comment by apolopena** [comment]
yeah back up for me

**Comment by kylos101** [comment]
Hey @sedattanir thank you so much for reporting the issue! You should be all set now. Please check, and let us know if you're still having trouble?

**Comment by apolopena** [comment]
Please re open or make a new issue. This issue is back.
