### ISSUE TITLE
workplaces don't open

### ISSUE THREAD

**Issue by georg480** [gitpod-io/gitpod#7344]
### Bug description

![image](https://user-images.githubusercontent.com/79664365/147055592-767ed614-6d9c-42e4-b7b9-4e969d22cfb9.png)

### Steps to reproduce

http://gitpod.io/#https://gitpod.io/workspaces

**Comment by John-wallace89** [comment]
My workspace is also not opening, although i'm getting a different error message 
![image](https://user-images.githubusercontent.com/75330172/147059689-cce3394c-2fb0-4939-bccd-82ee95002fc5.png)
work space https://sapphire-chickadee-v75mlfae.ws-eu23.gitpod.io/

**Comment by parasop** [comment]
![image](https://user-images.githubusercontent.com/63485824/147060054-7838c03b-2ba1-4524-80bc-263324007c6b.png)

**Comment by axonasif** [comment]
This is a ongoing issue, we can keep an eye on https://www.gitpodstatus.com/incidents/g0kjpr3lbvbwband

**Comment by bravoalpha79** [comment]
Same thing on my end:

![image](https://user-images.githubusercontent.com/45522344/147060593-bcb8e161-ef2c-45ff-a81d-35a89f6d45dc.png)


Note: I am located in the EU, so it's not just US clusters being affected as the Status page seems to state.

**Comment by John-wallace89** [comment]
@axonasif  - the above link doesn't seem to be working? i'm getting a 404.

**Comment by axonasif** [comment]
> @axonasif  - the above link doesn't seem to be working? i'm getting a 404.

Sorry, maybe it was changed, edited my message.

**Comment by parasop** [comment]
how much time it will take for fix?

**Comment by RyanRayn** [comment]
Same here..
<img width="733" alt="Screen Shot 2021-12-22 at 9 29 52 AM" src="https://user-images.githubusercontent.com/65997202/147061214-a7bef272-6cd8-465a-9753-c151471e7261.png">
.

**Comment by JamieT966** [comment]
<img width="297" alt="Gitpod not working" src="https://user-images.githubusercontent.com/93391397/147063037-371df5be-f387-48d5-8ac8-73722a554c9a.PNG">

Same.

**Comment by kylos101** [comment]
Appreciate the help, @axonasif! As [this incident](https://www.gitpodstatus.com/incidents/g0kjpr3lbvbw) is resolved, I am closing the issue.

As a heads up, we just had [an incident in the EU region](https://www.gitpodstatus.com/incidents/4f25shfbb632) that may have impacted some of you.
