### ISSUE TITLE
Preview is directly referring to git

### ISSUE THREAD

**Issue by Suresh3d** [gitpod-io/gitpod#735]
Hi,

I am using gitpod for threejs development. Recently I pushed my changes to  git. But after I pushed my changes , if I edit my existing js files and trying to see the preview , it directly shows preview of what I pushed last time . I am not able to see the new changes in preview . Can anyone help me with this issue?

Thanks in advance.

**Comment by jankeromnes** [comment]
Hi @Suresh3d, is it possible that your preview or web server is not live-reloading? If that's the case, you'd need to:

1. save any changes to disk
2. kill and restart the web server
3. refresh or close and reopen the preview

This should show your latest changes. Also, I don't think it is related to what you pushed or didn't push to GitHub.

**Comment by Suresh3d** [comment]
Hi @jankeromnes , The problem is not with Git. I guess some thing went wrong in GitPod. Now I am using npm to run server. It is working fine .Thanks for the notes.

**Comment by svenefftinge** [comment]
I think you just had expected that changes would be updated, but it doesn't work if you don't run the dev mode in three.js. Neither in gitpod nor locally. Glad you've solved your issue and can work now.
