### ISSUE TITLE
WebSocket connection to 'gitpod-workspace-url' failed. Webpack dev server issue

### ISSUE THREAD

**Issue by Adityak4201** [gitpod-io/gitpod#7357]
### Bug description

I have setup the react app using webpack dev server configuration. When I run the react app, it runs successfully. But fter a few seconds, I see error message in the console and react app UI does not update automatically on saving the code
`WebSocket connection to 'wss://3000-amethyst-chinchilla-dtjvlkn4.ws-us25.gitpod.io:3000/ws' failed: `
`[webpack-dev-server] Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}`

[Error snapshot link](https://ibb.co/sHnJ2JK)

### Steps to reproduce

Just setup react app using webpack and you will find the bug yourself. For reference, I am attaching my webpack configuration:

```
const path = require('path');
const HtmlWebPackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  mode: 'development',
  stats: {
    errorDetails: true
  },
  entry: './src/App.jsx',
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  devServer: {
    port: 3000,
    hot: true,
    allowedHosts: ['localhost', '.gitpod.io']
  },
  resolve: {
    alias: {
      '@pages': path.resolve(__dirname, 'src/pages/'),
      '@components': path.resolve(__dirname, 'src/components/')
    },
    mainFiles: ['index'],
    extensions: ['.jsx', '.js', '...']
  },
  module: {
    rules: [
      {
        test: /\.jsx$/,
        use: 'babel-loader'
      },
      {
        test: /\.scss$/,
        use: [
          MiniCssExtractPlugin.loader,
          { loader: 'css-loader', options: { modules: true } },
          'sass-loader'
        ]
      }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin(),
    new HtmlWebPackPlugin({
      template: './public/index.html'
    })
  ]
};

```

### Workspace affected

https://amethyst-chinchilla-dtjvlkn4.ws-us25.gitpod.io/

### Expected behavior

Error should not be visible and react app should get auto updated like the case with apps built using create-react-app.

### Example repository

https://gitpod.io#snapshot/83dd5d10-43ac-4c7f-8868-3a35656cdf0a

**Comment by akosyakov** [comment]
`wss://3000-amethyst-chinchilla-dtjvlkn4.ws-us25.gitpod.io:3000/ws` is not valid Gitpod port url, you should remove 3000 from port part, i.e. `wss://3000-amethyst-chinchilla-dtjvlkn4.ws-us25.gitpod.io/ws`

Use `gp url 3000` to get a proper URL. You can also try [the local companion](https://www.gitpod.io/blog/local-app) instead for interoperability with localhost.

**Comment by Adityak4201** [comment]
> `wss://3000-amethyst-chinchilla-dtjvlkn4.ws-us25.gitpod.io:3000/ws` is not valid Gitpod port url, you should remove 3000 from port part, i.e. `wss://3000-amethyst-chinchilla-dtjvlkn4.ws-us25.gitpod.io/ws`
> 
> Use `gp url 3000` to get a proper URL. You can also try [the local companion](https://www.gitpod.io/blog/local-app) instead for interoperability with localhost.

Thanks for the answer. But it has not solved my problem. In browser, the URL open is `https://3000-amethyst-chinchilla-dtjvlkn4.ws-us25.gitpod.io/` which is a valid gitpod URL but I don't know why web socket is trying to connect to `wss://3000-amethyst-chinchilla-dtjvlkn4.ws-us25.gitpod.io:3000/ws`. 

This is error snapshot:
[Error image](https://ibb.co/sHnJ2JK)

Also, please tell me how can I remove the port part.

**Comment by akosyakov** [comment]
You need to tell webpack that it should use such url like here: https://community.gitpod.io/t/setting-up-webpack-dev-server-on-gitpod/1648/2
