### ISSUE TITLE
Remote connection to MySQL from my local computer

### ISSUE THREAD

**Issue by sebastianpd1** [gitpod-io/gitpod#736]
Hello, I'm using a gitpod container to run a database, is it possible to connect using something like SequelPro or MySQL workbench??

This is my connection string inside gitpod:
```
mysql://root@localhost/example
```

**Comment by jankeromnes** [comment]
Hi @sebastianpd1, thanks for your interesting question!

This use case would also be useful for our dedicated [`gitpod/workspace-mysql`](https://github.com/gitpod-io/workspace-images/tree/master/mysql) image.

I have no experience with SequelPro or MySQL Workbench, but I'd say that you have two options:
- Install one of these inside your Gitpod container, and have it connect to the local MySQL
- Expose the MySQL port (by adding `- port: 3306` to your `.gitpod.yml`, in the `ports` section) and run the following command in a Gitpod terminal to know the external connection string:

```bash
echo "mysql://root@$(gp url 3306 | sed 's_https://__')/example"
```

I haven't tested this yet. Please let me know if you're able to get it to work, or if you'd like further help. 🙂 Good luck!

**Comment by kunxin-chor** [comment]
Hi,

I have tried generating the connection string via the method above, and it doesn't seem to work. Here's my sample connection string:

mysql://remote@3306-b56c270d-9f91-4154-a6ac-df568bdee40c.ws-us02.gitpod.io/test

I keep getting a timed out error, using DBeaver. I have make sure to create the remote user and the test database. The port 3306 is also public.

**Comment by beyerph** [comment]
Same Problem here .. any News about Connecting to the remote MySQL-Database with Sequel Pro?
![Monosnap 2020-07-13 14-09-46](https://user-images.githubusercontent.com/1206619/87302960-9e0da900-c512-11ea-9ce0-0bfc2d7b238a.png)

**Comment by geropl** [comment]
> mysql://remote@3306-b56c270d-9f91-4154-a6ac-df568bdee40c.ws-us02.gitpod.io:3306/test
The problem here is that Gitpod supports only HTTP traffic into workspaces atm. There might still be a way (by proxying mysql/socket over HTTP) but that's a tad more work I guess.

**Comment by jankeromnes** [comment]
Note: There are MySQL extensions available in Gitpod (simply find the Extensions panel in the IDE's left vertical menu, and search for "mysql").

I've never tried to use them, but I know we install the "VSCode Database" extension in some of our repos.

**Comment by aslafy-z** [comment]
Here are two ways of achieving what you want.

## Use `ngrok` - only server needed
- Signup at https://ngrok.com/signup
- Copy authtoken from https://dashboard.ngrok.com/auth/your-authtoken
- Install ngrok in your GitPod workspace
	```
	wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && unzip ngrok-stable-linux-amd64.zip && rm ngrok-stable-linux-amd64.zip
	```
- Register your authtoken
    ```
    ./ngrok authtoken "YOUR-AUTH-TOKEN"
    ```
- Forward mysql TCP port
    ```
    ./ngrok tcp 3306
    ```
- Use the given hostname to connect to your mysql instance running inside GitPod from your local workstation
## Use `inlets` - client / server needed
You can use follow this tutorial to expose services. https://www.gitpod.io/blog/local-services-in-gitpod/

**Comment by akosyakov** [comment]
We just announced preview version of Gitpod local companion which allows to tunnel any tcp port: https://www.gitpod.io/blog/local-app particularly it allows you access everything on localhost on proper port, similarly how you will do it in the local env, please try and give us feedback 🙏🏻

**Comment by svolence** [comment]
I encountered the same problem, is there any solution now?
