### ISSUE TITLE
Highlight and pin the default branch for projects from Bitbucket

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7366]
### Problem to solve

Following up from https://github.com/gitpod-io/gitpod/pull/7251#discussion_r771400058:

> ... we 🅰️ don't have the default label for the default branch and 🅱️ we don't pin the default branch at the top of the branches list.

| Branches for a GitHub repository |  Branches for a Bitbucket repository |
|-|-|
| <img width="1440" alt="Screenshot 2021-12-27 at 1 51 01 PM (2)" src="https://user-images.githubusercontent.com/120486/147469411-aadf8494-0f21-4f39-972e-1d20d089d96d.png"> | <img width="1440" alt="Screenshot 2021-12-27 at 1 50 56 PM (2)" src="https://user-images.githubusercontent.com/120486/147469412-7792e60f-faa0-4d74-b614-6af6a953fd09.png"> |

### Proposal

Let's :a: introduce a label for the default branch for Bitbucket repositories and :b: pin the default branch at the top of the list as done with GitLab and GitHub repositories.

**Comment by roboquat** [comment]
@gtsiolis: GitHub didn't allow me to assign the following users: trumbitta.

Note that only [gitpod-io members](https://github.com/orgs/gitpod-io/people), repo collaborators and people who have commented on this issue/PR can be assigned. Additionally, issues/PRs can only have 10 assignees at the same time.
For more information please see [the contributor guide](https://git.k8s.io/community/contributors/guide/first-contribution.md#issue-assignment-in-github)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7366#issuecomment-1004019847):

>/assign @trumbitta


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by trumbitta** [comment]
![image](https://user-images.githubusercontent.com/462705/147924972-10dcd880-3f42-40e8-a51c-09d46d9191d5.jpeg)

I mean, @gtsiolis, let's fix that 🤷😉😉😉😇
