### ISSUE TITLE
Adding a project for a Bitbucket repository will not trigger any prebuilds or add any webhooks

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7367]
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/pull/7251, we've added support for Bitbucket projects. 

However, when adding a project for a Bitbucket repository will not trigger any prebuilds or add any webhooks. See relevant comment in https://github.com/gitpod-io/gitpod/pull/7251#discussion_r771406266:

> ... in contrast with GitLab and GitHub repositories, adding a Bitbucket repository 🅰️ does not add a webhook for enabling prebuilds and 🅱️ does not automatically trigger a first prebuilds after adding the project.

### Proposal

Let's :a: add a webhook when adding a Bitbucket repository and :b: trigger a prebuild when adding the project to follow the behavior of the product when adding GitLab and GitHub repositories as projects.

Cc @AlexTugarev in case adding the webhook is not the best way forward here.

**Comment by jldec** [comment]
Thanks for opening this followup issue @gtsiolis
We should (within reason) try to offer a consistent UX for projects across git providers.  
/schedule

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7367#issuecomment-1001666311):

>Thanks for opening this followup issue @gtsiolis
>We should (within reason) try to offer a consistent UX for projects across git providers.  
>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jldec** [comment]
The fix for this issue should result in the equivalent of enabling prebuilds with a prefixed /#prebuild URL.

Users should not have to use the manually prefixed URL for prebuilds. This is important because (from https://github.com/gitpod-io/gitpod/issues/6688#issuecomment-972766653)

> Also, the manual prefix implementation is no longer correct (it doesn't associate Projects to prebuilds, doesn't use Incremental Prebuilds if enabled, etc).

cc: @gtsiolis @AlexTugarev

**Comment by AlexTugarev** [comment]
@jldec and @gtsiolis, just to clarify what enablement of prebulids means as it is implemented currently: two things needs to be true in order for a prebuild to start on a new commit. first the app/webhook needs to be installed to get the push event into Gitpod, and then the event handler needs to find/evaluate a Gitpod config for this repo to [decide](https://github.com/gitpod-io/gitpod/blob/24f7b609bf79b247d72d1841282639726bcd5891/components/server/ee/src/prebuilds/prebuild-manager.ts#L124) if a prebuild should be started. 

PR https://github.com/gitpod-io/gitpod/pull/7422 targets only the creation of a missing webhook. if the config+tasks do not exist in the repo, prebuilds won't be triggered automatically.

**Comment by jldec** [comment]
> PR #7422 targets only the creation of a missing webhook. if the config+tasks do not exist in the repo, prebuilds won't be triggered automatically.

That matches my expectations @AlexTugarev  
_I was just a bit confused by comments in the PR and in #7424. - sorry about that_
