### ISSUE TITLE
julia

### ISSUE THREAD

**Issue by Gab7** [gitpod-io/gitpod#737]

**Comment by meysholdt** [comment]
congrats on your first issue! We need a bit more description from you to understand what you want to tell us. Feel free to comment and re-open this issue.

**Comment by svenefftinge** [comment]
I think it's support for Julia which you can add through the VS Code extension.
Please download the `*.vsix` file from [here](https://github.com/julia-vscode/julia-vscode/releases) and [upload it to your workspace](https://www.gitpod.io/docs/vscode-extensions/).
Also to configure your container with proper Julia CLI tools, you need to create a `.gitpod.yml` and corresponding Dockerfile. Then install it via apt-get.

**Comment by jankeromnes** [comment]
Hi @Gab7, if you need help with any of the above, please provide your repository URL. I'd be happy to send you a Pull Request. 🙂

**Comment by hossein-pourbozorg** [comment]
Related issue #812
