### ISSUE TITLE
Bogus reload button shows in extensions view for built-in extensions

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#7376]
### Bug description

A reload button appears in extensions view for built-in extensions, this is caused because we copy vscode-web and vscode-reh in the same folder `/ide`, built-in extension are inlined in vscode-web but are also scanned again by the server causing the issue. 

### Steps to reproduce

1. open workspace
2. open extensions view
3. select to show built-in extensions
4. :bug: observe reload button next to built-in extensions

**Comment by jeanp413** [comment]
hey @csweichel, need you input here, the proper way to fix this is to separate the front part of vscode from the server part (this is also done by codespaces), right now we have both front and server in the same folder `/ide` in the workspace we should decouple them, ideally only the server part should be in the `/ide` folder inside the workspace, while the front end part could live in the blobserve image? Or we could just move them into different folders inside `/ide` (/ide/front/ and /ide/server). Let me know what you think.

**Comment by csweichel** [comment]
Moving them to separate folders is easier and less complex to implement. The relevant paths are already configurable:
- supervisor: [supervisor-ide-config.json](https://github.com/gitpod-io/gitpod/blob/7fc7fbd82850ba571ee3a2fe06c9c96af6d120f6/components/ide/code/supervisor-ide-config.json#L2) respectively [config.go](https://github.com/gitpod-io/gitpod/blob/d70eb530702440ac8c0eb91dd30270eebe7e9c1d/components/supervisor/pkg/supervisor/config.go#L125)
- blobserve: [configmap.go](https://github.com/gitpod-io/gitpod/blob/55549e86ac8fb55a8dbb2f6a44a8a3cf4889878b/installer/pkg/components/blobserve/configmap.go#L39-L71) respectively [blobserve.go](https://github.com/gitpod-io/gitpod/blob/291bcd9f259ae5e48ab73311e68a4970ea89a432/components/blobserve/pkg/blobserve/blobserve.go#L53-L58)

**Comment by jeanp413** [comment]
This got fixed while fixing another issue upstream https://github.com/microsoft/vscode/issues/141322
