### ISSUE TITLE
.mp3 files not served properly in HTML editor live preview

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#738]
**Describe the bug**
When trying to view an HTML demo page with .mp3 resources, the sounds properly in the Preview pane and Browser tab, but not in the Editor's HTML live preview.

**To Reproduce**
1. Open https://gitpod.io/#https://github.com/jankeromnes/wes-bos-javascript-30
2. Open `javascript drumkit/index.html` in the Editor
3. Click on the Preview icon (top-right of Editor)
4. Type any letters from `a s d f g h j k l`: visual effects work, but there is no sound
5. Now go to the Terminal and run `python3 -m http.server 8080`, then "Expose" and "Open Preview"
6. Now the letters `a s d f g h j k l` are able to produce sounds

**Expected behavior**
The sounds should also work in the Editor live preview

**Comment by jankeromnes** [comment]
Investigating this bug with the browser devtools, I'm able to spot a few differences between how the .mp3 resources are served in the Editor Preview vs the Web Preview, notably:

- `https://ef5552f8-80c2-4259-9af2-b445da4dab1d.ws-eu0.gitpod.io/mini-browser/workspace/web-developers-bootcamp/assets/sounds/strike.mp3` doesn't work, and has the suspicious header `content-type: audio/mpeg; charset=utf-8` (binary content as unicode text?!)
- `https://8080-ef5552f8-80c2-4259-9af2-b445da4dab1d.ws-eu0.gitpod.io/assets/sounds/strike.mp3` works well, and has the more reassuring header `content-type: audio/mpeg`

## Editor Preview headers (not working)

**General**

```
Request URL: https://ef5552f8-80c2-4259-9af2-b445da4dab1d.ws-eu0.gitpod.io/mini-browser/workspace/web-developers-bootcamp/assets/sounds/strike.mp3
Request Method: GET
Status Code: 200 
Remote Address: 34.76.156.35:443
Referrer Policy: no-referrer-when-downgrade
```

**Response Headers**

```
access-control-allow-credentials: true
access-control-allow-origin: https://gitpod.io
access-control-expose-headers: Authorization
content-length: 39839
content-type: audio/mpeg; charset=utf-8
date: Sun, 18 Aug 2019 14:09:53 GMT
etag: W/"9b9f-6A/LBlmxF7WXaYf2J1Vsn4pIB9g"
server: nginx/1.14.1
status: 200
x-gitpod-region: europe-west1
```

**Request Headers**

```
x-powered-by: Express
:authority: ef5552f8-80c2-4259-9af2-b445da4dab1d.ws-eu0.gitpod.io
:method: GET
:path: /mini-browser/workspace/web-developers-bootcamp/assets/sounds/strike.mp3
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,fr-FR;q=0.6,fr;q=0.5
cookie: [censored]
referer: https://ef5552f8-80c2-4259-9af2-b445da4dab1d.ws-eu0.gitpod.io/mini-browser/workspace/web-developers-bootcamp/circles/index.html
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
```

## Web Preview headers (working)

**General**

```
Request URL: https://8080-ef5552f8-80c2-4259-9af2-b445da4dab1d.ws-eu0.gitpod.io/assets/sounds/strike.mp3
Request Method: GET
Status Code: 200 
Remote Address: 34.76.156.35:443
Referrer Policy: no-referrer-when-downgrade
```

**Response Headers**

```
content-length: 21594
content-type: audio/mpeg
date: Sun, 18 Aug 2019 14:06:55 GMT
last-modified: Sun, 18 Aug 2019 13:24:31 GMT
server: nginx/1.14.1
status: 200
x-gitpod-port: 8080
x-gitpod-region: europe-west1
x-gitpod-workspaceid: ef5552f8-80c2-4259-9af2-b445da4dab1d
```

**Request Headers**

```
:authority: 8080-ef5552f8-80c2-4259-9af2-b445da4dab1d.ws-eu0.gitpod.io
:method: GET
:path: /assets/sounds/strike.mp3
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,fr-FR;q=0.6,fr;q=0.5
cache-control: no-cache
cookie: [censored]
pragma: no-cache
referer: https://8080-ef5552f8-80c2-4259-9af2-b445da4dab1d.ws-eu0.gitpod.io/circles/
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
```

**Comment by svenefftinge** [comment]
Could be due to restrictions on iframe.

**Comment by jankeromnes** [comment]
> Could be due to restrictions on iframe.

It's broken in the HTML Editor's live-preview iframe, but it works in the Preview side panel iframe.

I think it's an encoding problem (i.e. we're serving it as `utf-8` text instead of `binary`).
