### ISSUE TITLE
Der Prebuild wird erfolgreich erzeugt. Aber trotzdem werden die was bei before ausgeführt werden soll zwei mal ausgeführt einmal beim prebuild bauen und einmal beim Workspace öffnen. Ich will das es im prebuild alles ausgeführt wird und dann beim starten "direkt" verfügbar ist.

### ISSUE THREAD

**Issue by georg480** [gitpod-io/gitpod#7382]
### Bug description

Der Prebuild wird erfolgreich erzeugt. Aber trotzdem werden die was bei before ausgeführt werden soll zwei mal ausgeführt einmal beim Prebuild bauen und einmal beim Workspace öffnen. Ich will das es im Prebuild alles ausgeführt wird und dann beim starten "direkt" verfügbar ist.

https://gitpod.io/#https://github.com/georg480/gitpod

### Steps to reproduce

Ist immer wieder gleich.

### Example repository

![image](https://user-images.githubusercontent.com/79664365/147661213-bda897fc-2dcd-49bf-a29e-28ac708dd059.png)

**Comment by svenefftinge** [comment]
That is intended behavior. "before" is executed first on every workspace start no matter its a rebuild or a regular workspace start. Please use the `init` phase to run commands only during prebuild and not on workspace start.
See also: https://www.gitpod.io/docs/config-start-tasks#execution-order

If this doesn't help, feel free to open another issue.
