### ISSUE TITLE
Some prebuilds use different status on project cards and prebuild page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7384]
### Problem to solve

Some prebuilds use different status on project cards and prebuild page. See examples below:

| Project Card | Prebuild Page |
|-|-|
| <img width="357" alt="project-1" src="https://user-images.githubusercontent.com/120486/147668456-ae4108a4-92c7-4396-8acc-91940a1e1dff.png"> | <img width="1096" alt="project-3" src="https://user-images.githubusercontent.com/120486/147668461-adfcb2d6-f923-48ec-bbb8-18e86235e823.png"> |
| <img width="357" alt="project-2" src="https://user-images.githubusercontent.com/120486/147668466-a45da108-6b8e-4058-8c74-2286a6001206.png"> | <img width="1096" alt="project-4" src="https://user-images.githubusercontent.com/120486/147668469-5fe66118-cb33-47cf-a332-f7c02b06decf.png"> |

**Comment by jmls** [comment]
yah I confirm I see this as well

**Comment by gtsiolis** [comment]
Closing this as seems to be resolved from what I checked. Feel free to re-open if still relevant.

Cc @easyCZ @jankeromnes @AlexTugarev because https://github.com/gitpod-io/gitpod/pull/8805#issuecomment-1087452753
