### ISSUE TITLE
[self-hosted] ws-daemon service account error - cannot update node label

### ISSUE THREAD

**Issue by sedattanir** [gitpod-io/gitpod#7396]
### Bug description

![147689936-474d07a7-0d1d-4f30-a56f-97f912b16636 1](https://user-images.githubusercontent.com/17693925/147777252-324e7105-6386-4152-95a8-1d72d395a87f.png)

```
{
"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
"error":"nodes "master.example.xyz" is forbidden: User "system:serviceaccount:gitpod:ws-daemon" cannot get resource "nodes" in API group "\" at the cluster scope",
"level":"error",
"message":"cannot update node label",
"serviceContext":{"service":"ws-daemon","version":"commit-37c2d1ea772ac6f2f59a243f43b61d3480e1385b"},
"severity":"ERROR",
"time":"2021-12-30T18:02:18Z"
}
```

Vmware Workstation on ubuntu 20.04.3 LTS (latest) - 1 node
k3s - cloudflare
kubectl namespace gitpod
main.2090
#6491

### Steps to reproduce

I installed gitpod using installer. Other than that, I didn't do anything.

**Comment by MrSimonEmms** [comment]
@sedattanir does your installation allow you to run a workspace? In my experience, this is noise in the logs but doesn't actually stop it from working

**Comment by corneliusludmann** [comment]
Closing due to innactivity. Please feel free to open a new issue with more information when the error still exists.
