### ISSUE TITLE
Prevent users who register a self-hosted GitLab from disconnecting all other git integrations

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7399]
Users who register an integration with a self-hosted Gitlab instance can get into trouble by disconnecting all other git integrations.

E.g. A user who did this was cut off from their team plan subscription. (see [support ticket](https://app.frontapp.com/open/cnv_ildx6oa) internal). When the user tried to login again, a new account was created (without any indication) and the original account became inaccessible.

**Comment by jldec** [comment]
### Proposal
Don't count self-hosted integrations toward logic of whether of not to show the "Disconnect" action.
The 2nd screenshot below should _not_ show a Disconnect action, just like the first 1st screenshot below.

---

![Screenshot 2022-01-02 at 13 29 45](https://user-images.githubusercontent.com/849592/147878250-44950074-9e4a-4a7f-993c-a578ac72e411.png)

---
![Screenshot 2022-01-02 at 12 31 03](https://user-images.githubusercontent.com/849592/147878273-e8c99dde-7718-493e-93ea-e2f29ae9198d.png)

**Comment by roboquat** [comment]
@jldec: Issue scheduled in the meta team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7399#issuecomment-1003721609):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by jldec** [comment]
After discussion - let's leave the Disconnent action, but show users an error instead of simply disallowing the disconnect.
Error can say: `This git integration is required for authentication and cannot be removed.`

**Comment by laushinka** [comment]
Ah, I saw that @JanKoehnlein has picked it up. Sorry, was going to assign myself again but too late 🙈
Just for me to know next time, how does one test with a self-hosted git provider?
