### ISSUE TITLE
Local Vscode Gitpod extension Apple M1 not active

### ISSUE THREAD

**Issue by danutzcodrescu** [gitpod-io/gitpod#7404]
### Bug description

local vscode gitpod extension is not working on Apple M1 Macbook Pro 2020 (Big Sur). I tried multiple repos, but once the protocol links are triggered nothing happens (no ssh notification is happening, nor anything else). If I check the runtime status of the extension it says: `not yet active`.

The extension works fine for Vscode running on Windows PC or Macbook Pro Intel 16inch.

### Steps to reproduce

- pick any repo
- open a workspace
- open in vscode

### Workspace affected

https://kumquat-beaver-0owl5tyl.ws-eu25.gitpod.io/

### Expected behavior

it should open the workspace in local vscode on Apple M1 Macbook Pro 2020

### Example repository

https://kumquat-beaver-0owl5tyl.ws-eu25.gitpod.io/
https://amaranth-warbler-9x60nqvx.ws-eu25.gitpod.io/

I tried on both workspaces and it works fine on 2 other computers (Windows and Intel Macbook Pro), but not on the M1

### Anything else?

I restarted VScode and the M1 Macbook pro, but the extension is still not working and marked `not yet active`

**Comment by axonasif** [comment]
@danutzcodrescu could you try running gitpod-companion-app separately?

Run these commands on your terminal:
```bash
curl -OL https://gitpod.io/static/bin/gitpod-local-companion-darwin-arm64 && chmod +x ./gitpod-local-companion-darwin-arm64 && ./gitpod-local-companion-darwin-arm64
```

**Comment by danutzcodrescu** [comment]
@axonasif thanks for coming back. 

I managed to make it work by completely removing vscode, reinstalled it, open a workspace from gitpod on stock vscode and then apply settings sync. It seems that if I run settings sync before installing gitpod extension, something gets messed up and the extension no longer activates (maybe it conflicts with another extension). 

In any case it works! Thanks for looking into it and really excited to start playing with gitpod and customize it. 😍
