### ISSUE TITLE
Port8000 stuck on detecting

### ISSUE THREAD

**Issue by MichelleCoffey** [gitpod-io/gitpod#7405]
### Bug description

Port 8000 is stuck on detecting

### Steps to reproduce

type python3 manage.py  runserver to open port

### Workspace affected

https://magenta-finch-44p7dax0.ws-us25.gitpod.io/

### Expected behavior

Port message should open

**Comment by pawlean** [comment]
I've been unable to replicate this, is this still an issue?

**Comment by MichelleCoffey** [comment]
Yes, I’ve fixed it. Thank you

**Comment by pawlean** [comment]
Awesome, thanks @MichelleCoffey. Can you close this issue?
