### ISSUE TITLE
Clean up initial extension installation on vscode web 

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#7409]
Now that theia integration is being removed https://github.com/gitpod-io/gitpod/pull/7395, we should do some cleanup when we do the initial extension installation in vscode web.
Right now, we have some custom logic inside gp-code branch to do the extension installation, we need to simplify and move this logic to  the supervisor and install the needed extension using the server argument `--install-entension` and `install-builtin-extension`

**Comment by akosyakov** [comment]
Supervisor should be kept agnostic to concrete IDEs. We have though startup.sh and we could move this logic there.
