### ISSUE TITLE
Manually prebuild errors with 502 Server Error

### ISSUE THREAD

**Issue by tobiasdiez** [gitpod-io/gitpod#7413]
### Bug description

Triggering a manual prebuild (using the `#prebuild` context) after some time prints the following error message. After this, no further updates are displayed (so it's unclear if there is still something happening) and after the 1h timeout one is redirected to the workspace IDE, where it appears that no prebuild has been taken place.

```
<html><head>
            <meta http-equiv="content-type" content="text/html;charset=utf-8">
                                                                              <title>502 Server Error</title>
                                                                                                             </head>
                                                                                                                    <body text=#000000 bgcolor=#ffffff>
                                <h1>Error: Server Error</h1>
                                                            <h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
                                                             <h2></h2>
                                                                      </body></html>
```

### Steps to reproduce

Go to https://gitpod.io/#prebuild/https://github.com/sagemath/sagetrac-mirror/tree/public/build/gitpod and wait some time. I retried it a few times now, and I got the error everytime although at different times. If I skip the prebuild, then the build in the workspace succeeds.

The prebuild log also often stops working for me, either showing "Connecting to workspace logs..." or simply not updating after some time. Sometimes it works to reload the browser window, but not always.

### Workspace affected

https://jade-turtle-r4461lee.ws-eu25.gitpod.io/ (maybe, the build log is not showing)

### Expected behavior

No error message and successful prebuild.

### Example repository

https://github.com/sagemath/sagetrac-mirror/tree/public/build/gitpod

**Comment by svenefftinge** [comment]
You can retrigger prebuilds from within the dashboard now. You'd need to create a project fro your repo and then should see the prebuilds. We are probably going to deprecate the `prebuild#` context URL.

**Comment by tobiasdiez** [comment]
Thanks! I'd later activated the github app and used the dashboard to trigger and monitor builds. The same problem occurred (i.e. the logs stopped working and after 1h the prebuild timed out). See for example https://gitpod.io/t/sagemath/sagetrac-mirror/0724903d-6879-422b-8d65-89659d9de03c After more changes to the gitpod.yml file the error disappeared, but I don't know what changes helped.
