### ISSUE TITLE
Enable prebuilds for all branches when adding a project

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7425]
### Problem to solve

For GitHub repositories, when installing the GitHub App, prebuilds are enabled by default for the default branch. For enabling prebuilds for all branches, a user will need to defien this in `.gitpod.yml`, see [relevant docs](https://www.gitpod.io/docs/references/gitpod-yml#prebuildsbranches).

For GitLab and Bitbucket repositories, when adding aproject a webhook is installed. However, enabled are not enabled, see https://github.com/gitpod-io/gitpod/issues/7424 and pending PR in https://github.com/gitpod-io/gitpod/pull/7422. Prebuilds are also not enabled when adding a project, following the pattern used for GitHub repositories.

This makes enabling prebuilds for all branches a less discoverable option and more difficult to set up.

### Proposal

To make prebuilds more useful, we could consider :a: enabling prebuilds for all branches by default or :b: introduce a preference in project settings that allows enabling or disabling prebuilds for branches, pull requests, etc.

In the spirit of MVC (minimum viable change), enabling prebuilds for all branches could a good MVC step. ➿

**Comment by jldec** [comment]
Closing as non-reproducible. Please file a new issue with repro steps if you believe this is still a problem. Thanks.
