### ISSUE TITLE
pytest runs significantly slower than on travisci

### ISSUE THREAD

**Issue by koaning** [gitpod-io/gitpod#743]
**Describe the bug**
I've been playing around with gitpod yesterday and I love the idea but it seems like running pytest on [this](https://github.com/koaning/scikit-lego) project runs 5x as slow as travis ci. It might have been a one-off so I'll try again tonight but it feels like something is up. 

**To Reproduce**
Run gitpod and run pytest.

**Expected behavior**
Pytest running as fast as travis ci.

**Comment by jankeromnes** [comment]
Thanks for reporting this bug @koaning! I'll take a look at your project and try to benchmark what's making `pytest` slow there.

Also I've noticed a problem in your `.gitpod.yml`, and am proposing a fix in https://github.com/koaning/scikit-lego/pull/174

**Comment by koaning** [comment]
I've merged it. 

One thing I wonder; why can't I use that container? It's a small thing but the `Makefile` assumes that there is no python2 and it uses the `python` keyword instead of `python3`.

**Comment by jankeromnes** [comment]
@koaning Cool, thanks! The reason Gitpod didn't like that image is probably that it expects an Ubuntu/Debian/Alpine image with a few specific traits, like a user called `gitpod`. We could look into exactly what the image you tried is based on, and whether we can teach Gitpod to accept it, but for now I'd like to focus on the `pytest` issue.

> It's a small thing but the `Makefile` assumes that there is no python2 and it uses the `python` keyword instead of `python3`.

Thankfully this is relatively simple to fix: we use `pyenv` to manage Python versions, and you can simply run `pyenv local 3.7.2` once in your workspace to specify Python 3 as the default (this will create a `.python-version` file, you can either commit it, or add the `pyenv local 3.7.2` to your `.gitpod.yml` tasks).

**Comment by koaning** [comment]
My hypothesis is now that it might be due to BLAS. It seems to take extremely long to load numerical packages. I've set some algorithms to use only one iteration. The first deadzone regressor takes 52 seconds while the next two take 0.1 seconds.
