### ISSUE TITLE
[self-hosted] werft job to install a nightly Gitpod installation

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#7433]
Create a job that installs a Gitpod self-hosted installation as a nightly job and run the existing integration tests. Send a notification to Slack if the integration tests or the installation fails.

## See also
- https://github.com/gitpod-io/gitpod/issues/7316
- https://github.com/gitpod-io/gitpod-eks-guide

**Comment by nandajavarma** [comment]
The current WIP of this task can be [found here](https://github.com/gitpod-io/gitpod/tree/clu/gcp-vm-k3s/.werft), done by @corneliusludmann. The next step for us is to try and have a `werft` phase for this job, along with finding a way to run the integration tests on the created cluster. From here, we can iterate and see what might be the right tools to create the managed clusters.

**Comment by nandajavarma** [comment]
Closing this issue in favor of https://github.com/gitpod-io/gitpod/issues/10620
