### ISSUE TITLE
Dashboard: Could not delete your workspace

### ISSUE THREAD

**Issue by jbicker** [gitpod-io/gitpod#744]
**Describe the bug**
When I delete a workspace an alert message pops up:
`Could not delete your workspace - please try again or contact support`
Actually the workspace is still shown in the list. 
But after I reload the dashboard it is gone.
![WS-Deletion-Bug](https://user-images.githubusercontent.com/28291421/63497230-a48ece80-c4c3-11e9-9c7f-4ab67e0f1378.gif)
 
**To Reproduce**
Delete a Workspace in dashboard.

**Expected behavior**
That the Workspace is gone after I've confirmed that it really should be deleted.

**Comment by AlexTugarev** [comment]
@32leaves this looks like the 🐛 you squashed recently, no?

**Comment by 7sharp9** [comment]
I tied this earlier and this looks to be resolved.

**Comment by AlexTugarev** [comment]
@jbicker and @7sharp9 this fix was part of the recent update! 🎉

**Comment by jbicker** [comment]
> @jbicker and @7sharp9 this fix was part of the recent update! 🎉

Confirmed! I close this one.
