### ISSUE TITLE
Commits are Undetected

### ISSUE THREAD

**Issue by xootkama** [gitpod-io/gitpod#7450]
### Bug description

When i want to merge or cherry pick something it shows accept incoming change ..etc in the file
but sometimes it does not show like that and mix with the code

### Steps to reproduce

?

### Workspace affected

No

### Expected behavior

Options as before

### Example repository

Maximum every repository

**Comment by pawlean** [comment]
Hi @xootkama! Let me try and help you here. Have you got any screenshots that I can look at? I'm finding it difficult to understand what you mean.

**Comment by axonasif** [comment]
@xootkama I believe this is specific to the `git` usage you're making. We can try to help you further if you can provide us some reproducible steps from within Gitpod 🙂

**Comment by xootkama** [comment]
> Hi @xootkama! Let me try and help you here. Have you got any screenshots that I can look at? I'm finding it difficult to understand what you mean.

ok i will take the screenshot when i get that again

**Comment by xootkama** [comment]
![image](https://user-images.githubusercontent.com/88646493/150618493-484859f7-950a-44c9-bf96-1a673abb2f4c.png)

**Comment by xootkama** [comment]
> 

Screenshot

**Comment by xootkama** [comment]
Thanks .I hope u guys fix it well soon

**Comment by axonasif** [comment]
> Thanks .I hope u guys fix it well soon

I'm a bit confused but what are we supposed to look for 😅 ?

**Comment by akosyakov** [comment]
We rely on VS Code for that functionality. Please file an issue in upstream: https://github.com/microsoft/vscode
