### ISSUE TITLE
Error: stream unexpectedly closed  in meteor project

### ISSUE THREAD

**Issue by sunhaolin** [gitpod-io/gitpod#7455]
### Bug description

i run my project in gitpod, it shows
```bash
Error: stream unexpectedly closed
W20211231-15:29:10.414(0)? (STDERR)     at Socket.onClose (packages/shell-server/shell-server.js:383:12)
W20211231-15:29:10.414(0)? (STDERR)     at Socket.emit (events.js:323:22)
W20211231-15:29:10.414(0)? (STDERR)     at Socket.EventEmitter.emit (domain.js:482:12)
W20211231-15:29:10.415(0)? (STDERR)     at TCP.<anonymous> (net.js:668:12)
```
in terminal

### Steps to reproduce

project address: https://gitpod.io/#https://github.com/sunhaolin/meteor-myapp
meteor version 2.5.2 

### Expected behavior

not show Error: stream unexpectedly closed

### Example repository

https://gitpod.io#snapshot/8a5f1a5a-e568-4eb7-9a19-11864981d978

### Anything else?

any help will be grateful

**Comment by pawlean** [comment]
Hey @sunhaolin! To help debug, maybe it's worth checking out if you can reproduce this error locally? It'd help us know if this is a Gitpod error or something in your code.

**Comment by sunhaolin** [comment]
```bash
sunhaolin@sundeAir GitHub % cd meteor-myapp 
sunhaolin@sundeAir meteor-myapp % meteor
[[[[[ ~/Documents/GitHub/meteor-myapp ]]]]]   

=> Started proxy.                             
=> Started HMR server.                        
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
```
local is ok.

**Comment by axonasif** [comment]
@sunhaolin apparently this is working perfectly. I just opened your snapshot.
<img width="1280" alt="Screenshot 2022-01-24 at 8 21 39 PM" src="https://user-images.githubusercontent.com/39482679/150800399-5616ef6a-8422-4a71-b1e6-fb32313b9974.png">

**Comment by sagor999** [comment]
@sunhaolin will close this, but please re-open if it is still occurs.
