### ISSUE TITLE
Text in Terminal blurred on Safari with zoom

### ISSUE THREAD

**Issue by 7sharp9** [gitpod-io/gitpod#746]
**Describe the bug**
If you zoom in on safari (Cmd+) then the terminal text blurs

**To Reproduce**
Open a workspace in safari and zoom (Cmd +)

**Expected behavior**
No blurring of text

**Comment by 7sharp9** [comment]
![Screenshot 2019-08-22 at 12 09 26](https://user-images.githubusercontent.com/588746/63510211-f17ba080-c4d5-11e9-8b24-536b545339f8.png)

Notice the terminal text is blurred on zoom.

**Comment by 7sharp9** [comment]
![Screenshot 2019-08-22 at 12 12 38](https://user-images.githubusercontent.com/588746/63510316-2be53d80-c4d6-11e9-993c-183fa3d6bca5.png)

**Comment by AlexTugarev** [comment]
@svenefftinge this is reproducible with the examples provided by xterm.js as well. 

WDYT of switching to DOM renderer on Safari? I looks much nicer then.
