### ISSUE TITLE
Changing vscode web editor keyboard layout is broken

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#7460]
### Bug description

Changing vscode web editor keyboard layout is broken when switching between different layouts

### Steps to reproduce

1. Start a workspace
2. Click on the keyboard layout entry in the status bar
3. Select a different layout
4. Click again in the keyboard layout entry in the status bar
5. Select a different layout
6. :bug: Observe keyboard layout doesn't get updated

**Comment by juliusv** [comment]
Btw. my layout was never correct in the first place, it started out as "us" and couldn't be changed even initially - or maybe I changed it accidentally via some keyboard combo.

**Comment by juliusv** [comment]
For background, I'm on Ubuntu Linux with the latest Chrome (97.0.4692.71), though now with that latest Chrome it does allow me to change it once, but not after that first change anymore.

**Comment by jeanp413** [comment]
Created a PR upstream https://github.com/microsoft/vscode/pull/140295

**Comment by jeanp413** [comment]
This is fixed upstream, you can test in vscode web insiders, select it in your gitpod preferences.
Closing this.
