### ISSUE TITLE
Cannot connect to a postgres instance through tailscale

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#7461]
### Bug description

I'm trying to connect to a postgres instance through tailscale. The DNS name resolves just fine, but `psql` cannot connect. Unsetting `PGHOSTADDR` has no effect. When using the IP instead of the name things work well. When I attempt the same connection from a VM outside of Gitpod but through tailscale, everything works as expected.

**Comment by kylos101** [comment]
Hey @csweichel , I recreated the problem [here](https://github.com/kylos101/tailscale-test). 

I'm having trouble resolving DNS from Gitpod when using Tailscale Magic DNS for machines on my tailscale network. Interesting how when I `netcat -u 100.100.100.100 -v`, I get different results from both environments:

**VM**
ubuntu@database:~$ netcat -u 100.100.100.100 53 -v
Connection to 100.100.100.100 53 port [udp/domain] succeeded!
�"gitpod-kyle-brennan-tailscale-teskylos101githubbeta   tailscalenet�"gitpod-kyle-brennan-tailscale-teskylos101githubbeta       tailscalenet�"gitpod-kyle-brennan-tailscale-teskylos101githubbeta    tailscalenet�"gitpod-kyle-brennan-tailscale-teskylos101githubbeta       tailscalenet�"gitpod-kyle-brennan-tailscale-teskylos101githubbeta       tailscalenet

**Gitpod**
gitpod /workspace/tailscale-test $ netcat -u 100.100.100.100 53 -v
Connection to 100.100.100.100 53 port [udp/domain] succeeded!
�����^C

Almost like the Tailscale response (for Gitpod) was lacking data, was stripped out...or something silly is happening in my terminal. :laughing:

**Comment by csweichel** [comment]
I've created a local VM, ran postgres and dnsmasq to provide name resolution. I was successfully able to connect to the postgres instance from my workspace through tailscale.

![image](https://user-images.githubusercontent.com/3210701/149326512-66c1fac6-9f28-4266-b3e3-3c44636f8635.png)

The next thing to try is to replicate the RDS setup directly.

**Comment by sagor999** [comment]
I believe this was due to blocking all UDP traffic, which tailscale relies upon.
Since we disabled UDP firewall block, this should work now.
I will close this, but please re-open if it is not resolved.
