### ISSUE TITLE
vscode launch.json console integratedTerminal doesn't work

### ISSUE THREAD

**Issue by haefele** [gitpod-io/gitpod#7462]
### Bug description

I'm trying to use gitpod for a console application I'm developing.
It's a .NET 6 application, and I try to use the launch.json setting *integratedTerminal* so I can use `Console.ReadLine()` to read console input (see [here](https://github.com/haefele/CTime3/blob/try_gitpod/.vscode/launch.json#L15))

But my console application is not run in the integratedTerminal, but still in the internalConsole, which doesn't allow inputs.

It does work in my installed VSCode, when I open the gitpod workspace there.

### Steps to reproduce

1. Open http://gitpod.io/#https://github.com/haefele/CTime3/pull/3 in your browser
2. Wait for the C# extension and all dependencies are installed (Output window)
3. Press F5 to debug the application
4. The output of my console application (The text "Please enter your c-Time email address:") is shown in the VSCode Debug Console
5. Because it is in the Debug Console, I can't type in my email address

### Expected behavior

My application console output should not be shown in the VSCode debug console, but in an integrated terminal.

Screenshot from the gitpod.io website:
![image](https://user-images.githubusercontent.com/2983790/148261228-fc22b587-80b9-4f16-8521-28eb166c3d48.png)

Screenshot from VSCode (I have to install the official C# extension for it to work):
![image](https://user-images.githubusercontent.com/2983790/148261502-f6ec7fd2-d8eb-44fa-8f5f-a58565109ca0.png)

### Example repository

http://gitpod.io/#https://github.com/haefele/CTime3/pull/3

**Comment by axonasif** [comment]
Hi @haefele , is this working fine in your local VSCODE IDE?

**Comment by haefele** [comment]
Yes it does work in my local VSCode IDE when I open the gitpod workspace there.
Or do you mean, with all local source-code and launch.json?

**Comment by axonasif** [comment]
> Yes it does work in my local VSCode IDE when I open the gitpod workspace there.
> Or do you mean, with all local source-code and launch.json?

Thanks for the clarification, so indeed this is a bug related with the web version of VSCODE that Gitpod is using.

**Comment by jeanp413** [comment]
This is an issue from the C# extension https://github.com/muhammadsammy/free-omnisharp-vscode (maybe https://github.com/Samsung/netcoredbg too).
Right now `free-omnisharp-vscode` just swaps the proprietary C# debugger with netcoredbg, the debug adapter is the same and some features are not compatible with netcoredbg. More info https://github.com/Samsung/netcoredbg/issues/80#issuecomment-1009072635

**Comment by loujaybee** [comment]
Given @jeanp413's comment above, please raise with the upstream plugin maintainers, if you have further issues, feel free to re-open the issue 🙏
