### ISSUE TITLE
Node Version instructions cause failure

### ISSUE THREAD

**Issue by borisyordanov** [gitpod-io/gitpod#7478]
### Bug description

Following [these instructions](https://www.gitpod.io/docs/languages/javascript#node-versions) causes all workspaces to fail

### Steps to reproduce

Open [this PR/branch](https://github.com/borisyordanov/Gitpod-Node-Example/pull/2) in a gitpod workspace 

### Expected behavior

Official documentation recommends a way to change node versions that doesn't completely break gitpod and successfully changes the node version.

### Example repository

https://github.com/borisyordanov/Gitpod-Node-Example/pull/2

### Anything else?

```
.gitpod.Dockerfile:3
--------------------
   1 |     FROM gitpod/workspace-full:latest
   2 |     
   3 | >>> RUN bash -c ". .nvm/nvm.sh && nvm install 14.08 && nvm use 14.08 && nvm alias default 14.08"
   4 |     
   5 |     RUN echo "nvm use default &>/dev/null" >> ~/.bashrc.d/51-nvm-fix
--------------------
error: failed to solve: process "/bin/sh -c bash -c \". .nvm/nvm.sh && nvm install 14.08 && nvm use 14.08 && nvm alias default 14.08\"" did not complete successfully: exit code: 3
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","command":"build","error":"exit status 1","level":"error","message":"build failed","serviceContext":{"service":"bob","version":""},"severity":"ERROR","time":"2022-01-06T14:48:03Z"}
exit
exit

Error: headless task failed: exit status 1
````

**Comment by borisyordanov** [comment]
I adjusted the recommended syntax slightly to resolve the error, but the node version remains unchanged, despite the Dockerfile being executed correctly.

Link to changes - https://github.com/borisyordanov/Gitpod-Node-Example/pull/1/files

![image](https://user-images.githubusercontent.com/12392666/148406465-b3a69fbe-bd5f-4414-966b-6e4f597b5762.png)

![image](https://user-images.githubusercontent.com/12392666/148406804-d9890276-9643-49aa-8bda-386c69533cca.png)

**Comment by axonasif** [comment]
Hi @borisyordanov, try the following code in your dockerfile.
```dockerfile
FROM gitpod/workspace-full:latest

RUN bash -c 'VERSION="14.8.0" \
    && source $HOME/.nvm/nvm.sh && nvm install $VERSION \
    && nvm use $VERSION && nvm alias default $VERSION'

RUN printf '%s\n' "nvm use default &>/dev/null" >> ~/.bashrc.d/51-nvm-fix
```

Ref: https://github.com/gitpod-io/website/blob/752e34d17e48f84284c109958ca224ae7c7a0f22/gitpod/docs/languages/javascript.md#node-versions

**Comment by borisyordanov** [comment]
@axonasif It works! Thank you!

**Comment by axonasif** [comment]
> Can you suggest how we can also change the npm version (in case we don't want to use the one that comes with node)?
> 
> Doing it with a task doesn't work
> ```
> tasks:
>   - name: Setup npm
>     init: npm i -g npm@7
> ```

Please keep in mind that `init:` task file changes are only persisted for changes under `/workspace` dir. While that command I believe modifies files under `/home/gitpod`.

You can either use a `before:` task spec or just do from your Dockerfile? 🙂

**Comment by borisyordanov** [comment]
Using `before` worked, but for some reason, I couldn't get it installed in the Dockerfile. Thanks again!
