### ISSUE TITLE
Sweeper should clean up preview envs on Harvester, too

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#7479]
## Is your feature request related to a problem? Please describe
today VMs on harvester do not clean up.

## Describe the behaviour you'd like
Sweeper should remove the preview-env-namespace on Harvester, just like it removes namespaces in core-dev today.

## Describe alternatives you've considered
none.

## Additional context
none.

**Comment by wulfthimm** [comment]
That would mean that sweeper running on k3s in a VM inside harvester has access to Harvester and the permission to remove namespaces. We would also need a way give a service account in k3s access to Harvester. That is a security risk unless we put much effort in it to create a separate service-account for each preview-environment on Harvester itself with the restrictions to remove only a specific namespace.
I would rather use a different script that is started by a cronjob to check which branches are still active and remove all namespaces with no branch on GitHub. The downside is that we do not track the activity and if branches are not removed we would accumulate VMs on Harvester.

**Comment by ArthurSens** [comment]
> That would mean that sweeper running on k3s in a VM inside harvester has access to Harvester and the permission to remove namespaces. We would also need a way give a service account in k3s access to Harvester. That is a security risk unless we put much effort in it to create a separate service-account for each preview-environment on Harvester itself with the restrictions to remove only a specific namespace. I would rather use a different script that is started by a cronjob to check which branches are still active and remove all namespaces with no branch on GitHub. The downside is that we do not track the activity and if branches are not removed we would accumulate VMs on Harvester.

Why does sweeper need to run inside k3s? Can't we just deploy it to the Harvester cluster instead?

**Comment by wulfthimm** [comment]
> Why does sweeper need to run inside k3s? Can't we just deploy it to the Harvester cluster instead?

Sweeper is bound to the preview-environment and has to run inside k3s as it checks the activity by accessing the local database. If the branch does not exist and the workspace is not frequently used sweeper will initialize the removal process.

Suggestion: We could add a cronjob that checks if a preview-namespace has no Gitpod installation and is older than a day. This way we do not interfer with sweeper.

**Comment by mads-hartmann** [comment]
@ArthurSens assigning to you and moving to in-progress based on our conversation in Slack ☺️

**Comment by ArthurSens** [comment]
Oh yes, sorry for not doing that myself 😬

**Comment by ArthurSens** [comment]
Sweeper is finally running as a cronjob inside the harvester cluster.

A simple documentation was added [to Notion](https://www.notion.so/gitpod/Sweeper-a40e276bf78e45d3ab77e82feb180c17).

**Comment by mads-hartmann** [comment]
@ArthurSens was sweeper added it IaC anywhere? ☺️ If not, let's reopen this issue and discuss where to put it so we have it in IaC

**Comment by ArthurSens** [comment]
I discussed that with @wulfthimm, it looks like that the entire harvester environment was created manually, so there was no place that I could add the yaml manufests.

I added it to notion to make sure we don't lose it, but would prefer to have as IaC as well 🙂

**Comment by mads-hartmann** [comment]
@ArthurSens Thanks! I'm reopening this issue, could you change the notion page to point to the Harvester repo yaml files instead and then close the issue again? 🙂

**Comment by ArthurSens** [comment]
Done!
