### ISSUE TITLE
Java support not working anymore

### ISSUE THREAD

**Issue by isontheline** [gitpod-io/gitpod#748]
**Describe the bug**
Java support is not working anymore since 7-10 days (was resolved in #528).

**To Reproduce**
1) Clone on Gitpod : https://github.com/isontheline/smdr-parser
2) Try to play with java autocompletion
3) No autocompletion and no live compiling

**Expected behavior**
Live autocompletion and compiling

**Comment by svenefftinge** [comment]
The maven configuration was bad (nested sourcefolders). The error message is hiding in the Output View (View -> Output). I have created a PR that should fix it for you: 
https://github.com/isontheline/smdr-parser/pull/1

**Comment by isontheline** [comment]
@svenefftinge you rock! 👍
