### ISSUE TITLE
Unexpected result/error message on forked project from private repo in different org

### ISSUE THREAD

**Issue by stockholmux** [gitpod-io/gitpod#7482]
### Bug description

I forked a private repo from an organization in Github. This organization has *not* granted GitPod permission for private repos. I have granted permission for GitPod to see private repos in my personal account.

When I try to get use gitpod on this private fork, I get the message `Repository not found.` / `The repository 'stockholmux/<repo name>' is not found in your account.` And it totally does! It took quite a while to understand what was going on.

I'm not sure if this is by-design and it makes some sense given the permission on the original organization, but the error message is really unhelpful.

### Steps to reproduce

1. Create a private repo in an organization that hasn't granted permissions for Gitpod 
2. Fork the private repo into your personal github account
3. Grant access for gitpod to your personal account
4. Attempt to access the forked repo via `https://gitpod.io/#<repo url>` 
5. See the error message.

### Expected behavior

Either gitpod can access the the forked private repo or show an error message similar to the origin repo which makes sense:  (e.g.`Repository not found.` / `Permission to access private repositories has been granted. If you are a member of '<org name>', please try to request access for Gitpod.`)

**Comment by axonasif** [comment]
I agree with you. I'm not sure but there can be some technical challenges here.

**Comment by stockholmux** [comment]
@axonasif To my knowledge this is also not documented as a known issue. It would be nice to have something to preserve my hair - that shouldn't be a technical challenge.

**Comment by axonasif** [comment]
> that shouldn't be a technical challenge.

@stockholmux I meant that it could be a technical challenge to detect whether the private repo actually exists without having the necessary permissions granted beforehand. Sorry for not being clear enough 😅

**Comment by jldec** [comment]
Thank you for reporting this @stockholmux - we will investigate from the Gitpod side.

_(I wonder if this may not be a bug on the GitHub api)_

**Comment by jldec** [comment]
Scheduled.

A number of users have reported issues opening workspaces on private repos in the last week or so.
E.g https://discord.com/channels/816244985187008514/928500420966510702
cc: @axonasif

**Comment by jldec** [comment]
### notes
1. Allowing forking of private repos is a (fairly recent) feature that needs to be enabled in the GitHub org settings, before a fork is even possible.
![Screenshot 2022-01-10 at 21 55 44](https://user-images.githubusercontent.com/849592/148845348-9add61a9-e1ab-4725-ac3d-2cd8e717e4e3.png)

2. Granting third-party applications access to act on behalf of organization members (also in the org settings) is one way to get around the problem described above.
![Screenshot 2022-01-10 at 21 48 56](https://user-images.githubusercontent.com/849592/148845248-aa1e27b1-5f0c-4253-a4b2-d96eff98da9a.png)

**Comment by stockholmux** [comment]
@jldec Yeah, note 2 is unlikely in my organization (bummer, but not a blocker) but the error message was my big issue.

**Comment by jldec** [comment]
pushing for a fix for this also in #8076 since there are issues working directly with private repos on orgs.

**Comment by mittallakshayy** [comment]
Is there an update on this ? I was trying to use Gitpod with one of my forked repositories but the page says that the repository was not found on my account.
