### ISSUE TITLE
[observability] alerts for when ws-daemon garbage collection is excessive

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7485]
## Is your feature request related to a problem? Please describe

When garbage collection is excessive, it can cause workspaces to unexpectedly stop and backups to not work - resulting in data loss. This impacts customers because (1) they were not expecting a stop and (2) they lose data (which is their time and effort).

## Describe the behaviour you'd like

1. Send a warning alert if the duration exceeds `1 second`, so no page, just informational.
   * This would have warned us of the [incident](https://app.incident.io/incidents/93) 42 minutes before the incident was created.
   * This will have warned us 11 other times in the last 30 days, which would have been good opportunities to inspect usage
   * The promQL would look similar to `go_gc_duration_seconds{cluster=~"(us25|eu25)", job="ws-daemon", quantile="1"} > 1`
2. Send a critical alert (which pages), if the duration exceeds 60s.
   * This would have alerted us 2 minutes before the [incident](https://app.incident.io/incidents/93) was created.
   * This would have paged (which we did not create an incident) on January 4 at 1:40pm UTC.
   * The promQL would look similar to `go_gc_duration_seconds{cluster=~"(us25|eu25)", job="ws-daemon", quantile="1"} > 60`

Warnings this would have generated in the last 30 days:
![image](https://user-images.githubusercontent.com/1272076/148426510-d7ee4d11-ef8d-463c-824a-3b2831a4b4f2.png)

Paging events this would have generated in the last 30 days:
![image](https://user-images.githubusercontent.com/1272076/148426630-f4aeb3e0-699c-4b55-9c03-e7c0e9049571.png)

## Describe alternatives you've considered

1. [Do profiling](https://github.com/google/pprof)
2. When GC is excessive, capture a stack trace and archive it so it can be examined in the future.

## Additional context

[Related Slack channel for the incident](https://gitpod.slack.com/archives/C02SZ57PLJY)

**Comment by kylos101** [comment]
@aledbf @csweichel I listed a couple alternatives, not sure if there's anything else you'd consider?

**Comment by aledbf** [comment]
@kylos101 the proposed alerts make sense. That said :P, not sure what actions we could take besides running a profiler (that would not avoid an incident).

**Comment by kylos101** [comment]
> Would it make sense to just restart ws-daemon in that case? and let new one take over? and before restarting grabbing a profiler stack trace to analyze later why it was doing so much GC.

Yes, I think that makes sense.

> I assume restarting ws-daemon is non destructive and shouldn't affect existing workspaces on that node? is that correct?

I believe it is destructive, but the high garbage collection was too. I wouldn't advocate for restarting ws-daemon (if we think the workspaces are healthy and running) without running a test to confirm impact to running workspaces (like in core-dev or workspace-preview).

Also, if we did have to act on this runbook, we'd have to restore user data, too (assuming we still have access to the node).
