### ISSUE TITLE
VScode native liveshare issues

### ISSUE THREAD

**Issue by sualehasif** [gitpod-io/gitpod#7486]
### Bug description

Here is a bug report posted at the live share:
https://github.com/MicrosoftDocs/live-share/issues/4558

### Steps to reproduce

When I try to launch a session I get the error described above.

### Workspace affected

every workspace

**Comment by akosyakov** [comment]
We don't provide any special integration for LiveShare in Gitpod. You can use VS Code Desktop to make use of Gitpod via Remote Development and Live Share. For LIveShare bugs please reach out to maintainers.
