### ISSUE TITLE
Epic: Workspaces with higher CPU capacity for Pro+ customers

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7487]
## Summary
We aim to mitigate issues that current paying customers are having with longer building/testing times, by providing all _Professional_ and _Unleashed_ customers with workspaces that have more CPU resources. This is to be achieved by running the workspaces in separate clusters where workspace density is cut in half. 

## Context
Professional SaaS customers are experiencing slower building and testing times in Gitpod than locally due to lack of CPU capacity. We want to mitigate this issue asap, and therefore will focus only on the CPU capacity and follow an iterative MVC approach.

[Original RFC](https://www.notion.so/gitpod/Offer-Larger-Workspaces-9591f0607e074ea9920d3b843766c90f)

## Value
Resolving an immediate and major problem that some of our customers are facing.

## Acceptance criteria
1. Reduced load average in the workspaces of the new cluster
2. Pertaining customers validate that their testing and building times dropped to reasonable values, closer to what they are able to get locally.

## Measurement
1. Load average.

## Growth Area
Adoption & Retention

## Persona(s)
Teams serious about wanting to adopt Gitpod SaaS

## Hypothesis
1. Reducing CPU overcommitment in half is appropriate and sufficient.
2. CPU capacity is the only factor affecting computation times on the cases we observed and that led us to create this epic.

## Open Questions
1. Some performance concerns were also shared regarding prebuilds. How easy and quick would it be to apply the same strategy?
2. Are there any other technical approaches we should consider—having in consideration that we are looking for a MVC?
3. Would we need to coordinate any changes with the WebApp team in order for workspaces to be started differently for _Unleashed_ users?

## Issues
- [x] Deploy first iteration (gen34) and measure
- [ ] #8977

**Comment by BrandiATMuhkuh** [comment]
I would like to add my 50 cents to this. Since I'm currently evaluating Gitpod for my company. Here are the things I would like to know when choosing a web-ide like Gitpod

- How much ram and cpu power do machines have? I expect 16GB ram and >2.4GHz.
- Can it connect to VSCode? Or does it have an online VSCode. 
- Is port forwarding working properly? We use the firebase emulator which open many ports.
   - btw: Gitpods' port-forwarding only works via local VSCode. Sadly, a lot of systems have localhost hard coded in :/ Maybe it's possible to open real ports with chrome-plugin?!

**Comment by pawlean** [comment]
Hey @BrandiATMuhkuh!

Thanks for checking out Gitpod. Let me see if I can help you out here.

> How much ram and cpu power do machines have?

The specs for one workspace are the following:
- 7 vCPUs
- 12 GB RAM 
- 30GB disk 

This may change in the future.

> Can it connect to VSCode? Or does it have to be online VSCode?

You're able to use local VSCode, see the relevant docs [here](https://www.gitpod.io/docs/ides-and-editors/vscode).

> Is port forwarding working properly? We use the firebase emulator which open many ports.

Yes! I'm unsure of your exact set-up but port-forwarding does work. 

It's worth giving it a go, spinning up a workspace and if there's anything specific that doesn't work... Let us know and we'll try and help you out! If you're not aware, we also have a [Discord community server](https://www.gitpod.io/chat) where most of us hang out. Feel free to drop by as you set up Gitpod, we'd be more than happy to help.
