### ISSUE TITLE
VIM extension double input in Safari

### ISSUE THREAD

**Issue by maksimr** [gitpod-io/gitpod#7491]
### Bug description

Input doubled. For example, if press `a` it would set `aa` etc.
The problem appear only in editor. Terminal, dialogue inputs works fine.
Also, looks like the issue goes from editor itself because version of VIM extension doesn't change since https://github.com/gitpod-io/gitpod/issues/6220.

Works properly in Chrome

### Steps to reproduce

STR:

- Open Safari
- Open a workspace
- Install Vim extension (v1.21.10)
- Start typing

ER: Input not doubled
AR: Input doubled. For example, if press `a` it would set `aa` etc.

https://user-images.githubusercontent.com/616193/148444828-9cc553ac-f19e-4435-867d-33e920003175.mov

### Example repository

https://gitpod.io/#https://github.com/maksimr/playground

Extensions
<img width="302" alt="image" src="https://user-images.githubusercontent.com/616193/148444082-a4607ff1-2569-4ec9-9c4a-497905ec619f.png">

**Comment by akosyakov** [comment]
@maksimr I think it should be reported to the upstream.
