### ISSUE TITLE
Properly handle provider host name when using http(s) prefix when adding a new integration

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7492]
### Bug description

When a user tries to add a Git integration, using a URL with the http(s) prefix leads to inproperly configured URL, Redirect URL, etc.

### Steps to reproduce

1. Go to [`/integrations`](https://gitpod.io/integrations)
2. Try adding a GitLab or Github integration using a URL including the http(s) prefix

**Comment by Shulammite-Aso** [comment]
Hi @gtsiolis can I work on this? I just looked it up in the code and I think the user-provided URI needs to be stripped of any http(s) if they contain it.

**Comment by gtsiolis** [comment]
@Shulammite-Aso Absolutely! Feel free to open a pull request and cross-link this issue there. 🏓

**Comment by Shulammite-Aso** [comment]
I just made a PR for this @gtsiolis. Sorry this has taken time from when I commented, I suddenly had a lot on my plate.

**Comment by gtsiolis** [comment]
No need to apologize, @Shulammite-Aso! That's partially why we refrain from assigning an issue to a community contributor before opening a PR. Again, thanks for contributing!

**Comment by AlexTugarev** [comment]
Just for completeness, Gitpod only supports **https** connections to identity providers. Sensitive information and credentials should not be transmitted without encryption.

**Comment by gtsiolis** [comment]
Thanks for the reminder, @AlexTugarev! 💡
