### ISSUE TITLE
Port 8000 Not found

### ISSUE THREAD

**Issue by MichelleCoffey** [gitpod-io/gitpod#7496]
### Bug description

Port 8000 is not opening. Port 8000 not found.

### Steps to reproduce

try to create workspace and it does not open

### Workspace affected

https://magenta-finch-44p7dax0.ws-us25.gitpod.io/

### Expected behavior

Should open freely so I can see my site.

**Comment by axonasif** [comment]
Hi @MichelleCoffey , do you have a public repository I can take a look at?

**Comment by sagor999** [comment]
@MichelleCoffey let us know if you can provide a repro repo, in the meantime will close this issue for now.
