### ISSUE TITLE
Epic: Telemetry

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7498]
## Summary

For product improvement and growth measurement, we need to provide evidence of the adoption rate of self-hosted installations. To do this, we must provide an opt-out telemetry service that is able to "phone home" to provide anonymised statistical data.

This should be achieved via a screen when first loading up your Gitpod self-hosted instance (similar to connecting to an OAuth provider/accepting T&Cs) rather than via the Installer configuration.

Future iterations should cater for status queries, such as "is there a channel update available?"

## Context

All Gitpod installations are currently independent, with no server to phone home.

## Value

At the moment, we have no idea how many self-hosted installations are out there. By getting that information, we can provide a better service for users, developers and investors.

## Acceptance Criteria

 - server to receive telemetry data
 - client to send telemetry data

## In Scope

 - name (it could be more than just telemetry/update info)
 - system architecture
 - data structure and interfaces
 - opt-out
 - admin panel screens

## Out of Scope

 - update information

**Comment by Pothulapati** [comment]
👋🏼,

As this issues talks mainly about the telemetry infrastructure i.e client and server,  toggle, and the admin panel screens. This is done with https://github.com/gitpod-io/gitpod/pull/7503 , https://github.com/gitpod-io/gitpod/pull/7591 , https://github.com/gitpod-io/gitpod/pull/8915 , https://github.com/gitpod-io/gitpod/pull/8858 , https://github.com/gitpod-io/gitpod/pull/8272 , https://github.com/gitpod-io/gitpod/pull/8067 , https://github.com/gitpod-io/gitpod/pull/7732. 

Improvements to telemetry metrics, etc will be part of a separate Issue/Epic. Closing this, Hence.
