### ISSUE TITLE
Use kube-api proxy instead of port-forwarding

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/gitpod#7519]
In https://github.com/gitpod-io/harvester/pull/10 we implemented a kube api proxy for VMs using <preview>.kube.gitpod-dev.com. We should use this instead of port-forwarding in our Werft job.

Currently the proxy doesn't appear to work. To reproduce take the following steps

1. Start a VM off a branch in gitpod-io/gitpiod, see [Using VM-based preview environments](https://www.notion.so/gitpod/Using-VM-based-preview-environments-736d8128193849a7a292f9353b18bb6d)
2. Get SSH access to the VM, see [Getting SSH access to preview VM](https://www.notion.so/gitpod/Getting-SSH-access-to-preview-VM-1f03679ea5074bdcb3802cd3ed1499d1)
3. Download the k3s kubeconfig [Getting kubectl access to preview environment](https://www.notion.so/gitpod/Getting-kubectl-access-to-preview-environment-9573ca0778954f6bbea37fa56d435009)
4. Update the k3s kubeconfig to use the proxy. Modify sever to e.g. `server: https://preview-mads-test-kubeapi.kube.gitpod-dev.com:6443/`
5. See if it works by running `kubectl --kubeconfig=k3s-kubeconfig.yam get ns`

When using `https://preview-mads-test-kubeapi.kube.gitpod-dev.com:6443/` it times out, when using `https://preview-mads-test-kubeapi.kube.gitpod-dev.com` I get 

```
Unable to connect to the server: x509: certificate is valid for ingress.local, not preview-mads-test-kubeapi.kube.gitpod-dev.com
```

**Comment by meysholdt** [comment]
related: https://github.com/gitpod-io/gitpod/issues/7519

**Comment by wulfthimm** [comment]
I did not change the ingress settings and used the same convention as on staging. That means that the URL https://preview-<NAMESPACE>.kube.gitpod-dev.com:6443 is wrong. https://<NAMESPACE>.kube.gitpod-dev.com:6443 works without problems.
It is analog to accessing the preview-environment. You only exchange *.preview.* with *.kube.*.
![image](https://user-images.githubusercontent.com/12035025/149144316-34b222d4-6e4a-4a95-9b95-901509f939a8.png)
