### ISSUE TITLE
Create "Open In Gitpod (JetBrains)" button

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7525]
Create an "Open In JetBrains" button, which allows users to force open a project within JetBrains. This UX would be useful to support our work on the JetBrains integration. In terms of solution, I believe this can be done via URL parameters. 

Related to: 
- https://github.com/gitpod-io/gitpod/pull/9467

**Comment by akosyakov** [comment]
I reopen it, since i thought to reuse new referrer prefix for that, but it is not really great, since it will disturb our data about local clients. I will add a dedicated prefix for that instead.

**Comment by loujaybee** [comment]
Removing from scheduled, unlikely to be completed as part of the next release, but could be picked up in future.

**Comment by mustard-mh** [comment]
close, will continue with this issue https://github.com/gitpod-io/gitpod/issues/9434

**Comment by akosyakov** [comment]
@mustard-mh I don't think it is a duplicate of https://github.com/gitpod-io/gitpod/issues/9434.

**Comment by svenefftinge** [comment]
not sure where that button should appear, but I think this has been somewhat fixed by https://github.com/gitpod-io/gitpod/pull/15389
