### ISSUE TITLE
Code (desktop): Blank window is opened in background

### ISSUE THREAD

**Issue by slashequip** [gitpod-io/gitpod#7527]
### Bug description

When opening a workspace in VS Code (Desktop) a blank/empty window is opened (at best guess as part of initilization), a new window is used to open the connection to the workspace and this blank window is left in the background.

### Steps to reproduce

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
```

1. VS Code is fully quit.
2. Open any workspace, in Code Desktop, from the browser.
3. 2 windows will be opened, in the background a blank window, in the foreground the connected workspace window.

### Expected behavior

Ideally, I would expect one of these two outcomes;

1. The workspace is opened in the initial/first window rather than a new one.
2. I would expect the blank window to close after being used (presumably) to open the window with the connection to the workspace.

### Anything else?

I'm not sure where the cause of this issue lies and whether it is _anything_ to do with Gitpod or just how VS Code handles this scenario.

It's only a small issue but it'd be nice to not have empty windows hanging about!

![Screenshot 2022-01-10 at 18 00 40](https://user-images.githubusercontent.com/2316916/148818069-3a753147-6ff8-49e4-9ed2-20f254de5c8c.png)

**Comment by axonasif** [comment]
This is still and issue.
Recent report at discord:
- https://discord.com/channels/816244985187008514/1032294771106005022

**Comment by david-bakin** [comment]
But ... only close that first window _if and only if it was created by clicking the link!_ Because if you have a VSCode window _already open_ it uses _that_ one, no harm done, so _don't close it!_

**Comment by Phxntxm** [comment]
> But ... only close that first window _if and only if it was created by clicking the link!_ Because if you have a VSCode window _already open_ it bounces through _that_ one, no harm done, so _don't close it!_

Yes, ideally the first option would be used. The Remote SSH extension used has a "Connect to host" option and a "Connect current window to host" option.... idk the inner workings of gitpod code, but I imagine it'd be something like (psuedocode obviously):

```
if window.was_already_open:
    remote.connect_to_host()
else:
    remote.connect_current_window_to_host()
```

**Comment by mustard-mh** [comment]
@loujaybee Could you create an Epic for this issue (VSCode flow improvement)? 🙏

**Comment by axonasif** [comment]
Not stale.

**Comment by loujaybee** [comment]
Related [internal discussion](https://gitpod.slack.com/archives/C045J13P8A1/p1677659721388919).

**Comment by loujaybee** [comment]
This limitation is being documented. If we find workarounds, or the situation changes, we'll come back to update. 

https://github.com/gitpod-io/website/pull/3593/files
