### ISSUE TITLE
Prebuilds are not working on my fork

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#753]
**Describe the bug**
I have enabled prebuilds for my fork, but it doesn't work (I don't get a prebuild).

Screencast: https://youtu.be/FPEx5O5nhrI

**To Reproduce**
1. Open https://gitpod.io/#https://github.com/jankeromnes/freeCodeCamp
2. There is no prebuild

**Expected behavior**
1. There should be a prebuild, saving 87 precious seconds of my life on every start-up.

Additionally, I tried forcing a prebuild by using the secret prefix:
https://gitpod.io/#prebuildhttps://github.com/jankeromnes/freeCodeCamp

- Yesterday, it showed `Workspace prebuild is running...`, but nothing ever happened, and the repo eventually "forgot" about the prebuild
- Today, it says `Error: Workspace is already pre-built`, but there is still no prebuild

**Comment by jankeromnes** [comment]
I'm investigating this issue. The US server logs have this entry:

```
2019-08-26 18:39:18.903 CEST
Registered workspace prebuild: 5b37cd53-54ff-4644-9856-de8e80fa9d22 for https://github.com/jankeromnes/freeCodeCamp.git:a6e1852de6231f62e3614af81610013658419c98
```

Looking for this prebuild ID in the DB, I get:

```
+--------------------------------------+---------+------------------------------------------------------------------------+-------------------------------------------------+
| id                                   | state   | error                                                                  | cloneURL                                        |
+--------------------------------------+---------+------------------------------------------------------------------------+-------------------------------------------------+
| 5b37cd53-54ff-4644-9856-de8e80fa9d22 | timeout | workspace timed out after period of inactivity took longer than 00h30m | https://github.com/jankeromnes/freeCodeCamp.git |
+--------------------------------------+---------+------------------------------------------------------------------------+-------------------------------------------------+
```

So we know that the prebuild timed out after 30min. This is probably why I don't get a prebuild, even though it's enabled.

- This error should probably not remain silently hidden in the DB. But where should it be shown?

- Why does the prebuild take longer than 30min when the non-prebuild init takes 2-3 minutes?

**Comment by svenefftinge** [comment]
I think this was resolved. (Please reopen if I missed something)
