### ISSUE TITLE
Introduce a way to opt out from sending anonymous usage data through the admin dashboard

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7531]
### Problem to solve

Following the proposal in https://github.com/gitpod-io/gitpod/issues/7530, opting out from sending anonymous usage data through the admin dashboard is not possible.

### Proposal

Introduce a way to opt out from sending anonymous usage data through the admin dashboard.

TBD (To be discussed)

**Comment by MrSimonEmms** [comment]
Duplicate of #7498
