### ISSUE TITLE
Surface inherited user-specific environment variables in project-specific environment variables

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7532]
### Problem to solve

Following the work in https://github.com/gitpod-io/gitpod/pull/7295 to add project-specific environment variables, user-specific environment variables are _**not**_ visible when a users adds project-specific environment variables.

Food for thought and certainly out of the scope here: This could be also interesting for team-level variables that could be inherited on the project level. However, this could leak variables set at the team level and could impact collaboration and sharing as secrets could leak to team members that only have access to specific repositories linked as projects. 🍔 

### Proposal

To provide better visibility and user control, we could surface inherited user-specific environment variables in project-specific environment variables.

TBD (To be discussed)

**Comment by jankeromnes** [comment]
Thanks for filing a follow-up issue! 🙏

> user-specific environment variables are visible when a users adds project-specific environment variables.

Sorry, I don't understand this part. Could you please elaborate on this problem?

**Comment by gtsiolis** [comment]
Oh, I skipped _not_ there. 😬 

Updated the description. Do you think this feature request still makes sense to discuss further? I'm probably missing something here.

**Comment by jankeromnes** [comment]
Aha, makes a lot more sense now 😅 I feel like I should have been able to guess the missing _not_.

I'm still a bit confused about the second part though (🙈):

> This could leak variable set at the user level and also impacts collaboration and sharing.

- I'm not 100% sure what you mean by "leak" here. I guess user-level variables that have a repositoryPattern which matches the project will also get exposed in project workspaces. But, this only happens for project workspaces _belonging to that specific user_ (i.e. user values never "leak" to other users of the project, right?). Also, it's worth noting that we would like to deprecate the repositoryPattern in the future, and it's not yet fully clear what the user-level variables feature looks like without the repositoryPattern.

- I also don't understand the relationship with collaboration and sharing here (sorry for needing so much explaining/handholding 🙈)

**Comment by gtsiolis** [comment]
Looping in @jldec because https://github.com/gitpod-io/gitpod/issues/7881.

**Comment by svenefftinge** [comment]
What does " are not visible" mean? Not visible in the dashboard's project env page (why should they?) or are user-level variables are not passed to a started workspace (which would be a bad bug)?

**Comment by gtsiolis** [comment]
Re-posting from the updated description in https://github.com/gitpod-io/gitpod/issues/7532#issuecomment-1013159175 as this would be more useful for team-level environment variables:

> This could be also interesting for team-level variables that could be inherited on the project level.

The intent of this feature request was to provide better visibility of variables that could potentially leak upon sharing a snapshot or a running workspace. However, this could be resolved with better information upon sharing, shared workspace information, etc.

This also could become a valid issue for team-level environment variables but let's close this until :a: this becomes an issue and :b: there's more demand for team-level variables (see https://github.com/gitpod-io/gitpod/issues/7881). Thanks, everone for chiming in!
