### ISSUE TITLE
List of ports is too long

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#754]
![Screen Shot 2019-08-27 at 10 29 36](https://user-images.githubusercontent.com/914497/63754731-a71f6880-c8b5-11e9-9fbe-35369dd4d327.png)

In such cases it would be nice to show an ellipsis for the long list of closed ports, e.g. `12345, 12346, ...`.

**Comment by jankeromnes** [comment]
Also, several ports are wrongly shown multiple times:

- 5900 x 2
- 8080 x 2
- 34603 x 2
- 42767 x 2

**Comment by jankeromnes** [comment]
See also: #742 has "No open ports" in the bottom bar, but several open ports in the "Open Ports" view.
