### ISSUE TITLE
Question - should we log the data we send to console?

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7540]
> **tl;dr** I'm in favour of this as a point of transparency and in gaining/maintaining the trust of the community

To further prove that we are not collecting anything more than the anonymous data, is it worth displaying what we send as a log message? Normally, it's bad practice to log what you're sending to a data store, but this would transparently display what we're sending so users can see exactly what we're collecting.

The `analytics.Track` object we're sending in the [send](https://github.com/gitpod-io/gitpod/blob/sje/telemetry-client/components/installation-telemetry/cmd/send.go#L48) command would be what's sent to the logs.

/cc @gitpod-io/engineering-self-hosted

**Comment by corneliusludmann** [comment]
Makes sense to log these data to be transparent here. Since they are anonymous anyway, it's safe to log them. Let's do this.
