### ISSUE TITLE
Support `with-Observability`

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#7544]
Preview environments on Harvester should support "observability" (aka have monitoring-satellite installed).

Proposed Solution:
a) always install monitoring-satellite
b) install monitoring-satellite only when the flag `with-Observability` is passed to the Werft job.

**Comment by mads-hartmann** [comment]
Keep in mind, this will be the first time we use tracing together with the Gitpod Installer. The tracing endpoint should be configurable, so it is hopefully straightforward.

**Comment by mads-hartmann** [comment]
@ArthurSens As we talked about I have created an empty Notion How-To ["Getting access to Grafana and Prometheus in preview environments"](https://www.notion.so/gitpod/How-Tos-f70facf5032345fe975413e4c101f52d?p=f2938b2bcb0c4c8c99afe1d2b872380e) which a section both for VM-based preview environments and core-dev ones (as part of gitpod-io/observability#56)

**Comment by ArthurSens** [comment]
[Notion page updated](https://www.notion.so/gitpod/Getting-access-to-Grafana-and-Prometheus-in-preview-environments-f2938b2bcb0c4c8c99afe1d2b872380e)

**Comment by mads-hartmann** [comment]
@ArthurSens Notion page looks good, thanks!
