### ISSUE TITLE
Support `with-payment`

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#7545]
The flag `with-payment` should work in preview envs in Harvester as well as it does today for preview envs in core-dev.

This is for the ChargeBee integration (I think the webapp team has a notion page on it)

**Comment by wulfthimm** [comment]
The payment configuration is set up in the harvester-proxy [here](https://github.com/gitpod-io/harvester/blob/92fc606bace315a4b6bfd6b01f9eaa6070a65a48/charts/ingress/conf-cm.yaml#L99).

**Comment by wulfthimm** [comment]
The installer does not support the installation of the payment endpoint. `core-dev` preview environments do not support it neither as far as I saw it. We should discuss how and when the payment endpoint should be supported. In this state we might put too much work into it. I am adding the `blocked` label. It can be removed when there is plan how to support the payment endpoint. Maybe we should remove the endpoint from the Harvester `ingress` proxy to avoid confusion.

**Comment by wulfthimm** [comment]
The `werft` argument `with-payment` will only add flags to the Helm installation ([ref](https://github.com/gitpod-io/gitpod/blob/ed8a3dc4f8007fde60e48934449d27ac2e2f5f43/.werft/build.ts#L887)). The installer does not support the deployment with a payment provider yet.

**Comment by wulfthimm** [comment]
I suggest that we remove the outdated configuration from the proxy and discuss the support with the WebApp-Team.

**Comment by mads-hartmann** [comment]
@wulfthimm Thank for taking a look. Don't remove anything yet, but please reach out to the webapp team to understand what the state is for testing payments when using the installer.

**Comment by wulfthimm** [comment]
I have already reached out to Gero to make sure that we do not need the proxy anymore.

**Comment by wulfthimm** [comment]
I spoke with Gero and he confirmed that there is no working solution with the installer. The proxy configuration is also outdated as the payment endpoint is using the same forwarding as the workspace URLs. I would close the issue and remove the outdated config from the proxy which also contains some forwarding for Jaeger as well.

**Comment by mads-hartmann** [comment]
@wulfthimm Alright, please do the cleanup as part of this issue and then close it ☺️ Once the WebApp team moves to the installer we can assist them if there are any changes required from the VM side of things.

**Comment by wulfthimm** [comment]
I told Gero the same. If the process which is described in notion stays this way the support is already in place.
