### ISSUE TITLE
Support "Login using Gitlab"

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#7547]
For preview envs on Harvester, "login with GitLab" should work as well as it does today on core-dev.

We can test with gitlab.com, we don't need to use self-hosted GitLab

**Comment by wulfthimm** [comment]
We need to set up a new application in Gitlab with the callback-url `https://preview.gitpod-dev.com/auth/gitlab/callback`. I can not find any Gitlab account that can be used for that purpose in 1Password.

**Comment by meysholdt** [comment]
I don't have an account for the Gitlab application either. 

@wulfthimm do the credentials on core-dev unveil which account we use there? If not, maybe the @gitpod-io/engineering-Webapp team can clarify which account should be used. Is it a shared account? Or just a random personal account?

**Comment by wulfthimm** [comment]
> I don't have an account for the Gitlab application either.
> 
> @wulfthimm do the credentials on core-dev unveil which account we use there? If not, maybe the @gitpod-io/engineering-webapp team can clarify which account should be used. Is it a shared account? Or just a random personal account?

I can only see a client id and secret. My guess would be that it is a random presonal account. I will ask.

**Comment by AlexTugarev** [comment]
Need to admit, it's still my personal account which is used for the `GitpodDevStaging` OAuth App, and I recall we were not able to find out who maintains the official Gitpod account on gitlab.com to change this when we tried once.

**Comment by wulfthimm** [comment]
There is already a group for [Gitpod on gitlab.com](https://gitlab.com/groups/gitpod-io) and it would be benefitial if we could be at least a maintainer of that group.  @svenefftinge, @gtsiolis, @jankeromnes

**Comment by gtsiolis** [comment]
FYI, only group owners can invite others, see [relevant docs](https://docs.gitlab.com/ee/user/permissions.html#group-members-permissions). Cc @svenefftinge

Thanks for the ping @wulfthimm! 🏓

**Comment by gtsiolis** [comment]
Also, there's a separate user account ([`@gitpod`](https://gitlab.com/gitpod)) which could be also helpful here. Maybe we could share the credentials for that account in 1Password if this is preferred. 💡

**Comment by wulfthimm** [comment]
I have added a new [application to gitlab.com](https://gitlab.com/oauth/applications) using the `gitpod` account and copied the credentials directly to the secret in `core-dev`.

**Comment by wulfthimm** [comment]
I successfully created a preview-environment on Harvester and was able to login using Gitlab.com ([1](https://wth-test.preview.gitpod-dev.com/)). There is an issue that covers the problem that the credentials saved in the secret on `core-dev` are not persisted in our IAC ([2](https://github.com/gitpod-io/ops/issues/1024)).
