### ISSUE TITLE
Support "Login using Bitbucket"

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#7548]
For preview envs on Harvester, "login with BitBucket" should work as well as it does today on core-dev.

We can test using bitbucket.org

**Comment by wulfthimm** [comment]
I have created a new application in bitbucket and changed the secret `preview-envs-authproviders-harvester` in `core-dev` accordingly. As it is not part of our IAC I created a new issue as it also includes other provider ([ref](https://github.com/gitpod-io/ops/issues/1024)).

**Comment by wulfthimm** [comment]
The login does work and can be tested by starting a new preview-environment on a VM.

**Comment by mads-hartmann** [comment]
@wulfthimm Did you reopen this on purpose? :)

**Comment by wulfthimm** [comment]
Yes, because I do not know if changing the secret manually is sufficient to close the issue.

**Comment by mads-hartmann** [comment]
@wulfthimm As you created a follow up issue to move it into IaC I think that's okay and we can close this ☺️
