### ISSUE TITLE
Websocket notification get lost sometimes - improve tracing

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#7550]
Follow up for this issue: #7054 

I managed to a) bump into some occurrences and b) was able to dig up the relevant traces [[1](https://ui.honeycomb.io/gitpod/datasets/gitpod-production/result/pUajfjBhPa9/trace/3NfPvQHynZu?span=662a1db2645919bb), [2](https://ui.honeycomb.io/gitpod/datasets/gitpod-production/result/dE1HJviFyNg/trace/AAT7c6zxrqM?span=1437f7d4385a0c80)]. These show that:
 - `openPort` is executed by `ws-manager`
 - the updates are definitely deliver to `server`
 - `server` tries to forward this to _some_ clients

We don't know if:
 - this includes the client we expect
 - the delivery is successful

On the server side, we be able to tell apart which websocket connection we send notifications to.

**Comment by svenefftinge** [comment]
@geropl sounds like https://github.com/gitpod-io/gitpod/issues/7553 is the same? 
If so please close as duplicate 🙏

**Comment by geropl** [comment]
Keeping this issue for the "improve tracing" part.

**Comment by geropl** [comment]
Note: #7054 is still unresolved, and actively being worked on (again).
