### ISSUE TITLE
Workspace open splash screen gets stuck when pulling container image

### ISSUE THREAD

**Issue by borisyordanov** [gitpod-io/gitpod#7553]
### Bug description

When a workspace is being opened (it doesn't matter if it's a new one or an existing one) the splash screen is not dismissed quickly enough. Quiet frequently it's never dismissed at all and the user is left looking at the "Pulling container" message. Reloading the page resolves this and takes the user straight to the open workspace options.

![image](https://user-images.githubusercontent.com/12392666/149024324-b322ba63-ec94-40cc-9d72-be0945cb6ece.png)

### Steps to reproduce

1. Open any workspace and find it in `/workspaces`
2. Verify the status icon in `/workspaces` changes before the workspace is loaded
3. If you reload the page after the status icon in `/workspaces` changes then you'd see the option to open the workspace

### Expected behavior

The page is updated as soon as the workspace is ready to be opened.

### Anything else?

This bug report should contain a form to specify user agents. I'm using Windows 10 and Firefox 95.0.2. I haven't tried to reproduce in other browsers/OS

**Comment by svenefftinge** [comment]
I have seen this on prebuilds and workspace image builds. It seems like a connection loss issue on long waits.

**Comment by geropl** [comment]
@borisyordanov Thx for reporting. This seems to be another symptom of https://github.com/gitpod-io/gitpod/issues/7054. Will re-open that one and close this as duplicate.
