### ISSUE TITLE
[Installer]: publish named Docker tags for Installer

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7566]
It would be helpful to have named tags for the Installer Docker images. Whilst it wouldn't be used in a productionised installation, it would be helpful when speaking to the community, writing documentation and guides.

Suggested named tags:

 - `latest`: this would track the stable releases, changing slowing
 - `unstable`: this would track the latest build in the `main` branch, changing rapidly

See [Slack discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1641993972091500) for context

**Comment by csweichel** [comment]
Is this really something we want to do? 
- "moving" tags like this suggest release channels, I don't think this is our release channel mechanism
- `latest` is not `latest`, but just what the user has pulled last
- it's unclear who would use those tags and how
- once we have them in place they're hard to take back

**Comment by MrSimonEmms** [comment]
Yeah, I know that named tags can be problematic but I think they can have merit in a couple of scenarios.
 - in the guides, I'd like to avoid having to manually submit a new commit to them every month/release. If we had `latest`, we could avoid having to write the script every month - there would be a `docker pull installer:latest` before it was used so that would avoid a previous version
 - we would always have a `latest` version we could send out in community support. Perhaps less used, but I think it could still be handy
 
 It absolutely is not our release channel mechanism - that will 100% be via GitHub releases (community) and Replicated (enterprise). This exists more as a convenience

**Comment by csweichel** [comment]
> in the guides

we'd hopefully use replicated

> that will 100% be via GitHub releases (community) 

are we really going to introduce separate release channels? If so, why bother buy a solution if we have to build one after all?

**Comment by metcalfc** [comment]
It is more work on the release management side to automate tags. In the long run it is less work though. Troubleshooting against opaque tags is no fun. Yes you can dig in and get more. But through the `docker inspect` you still will lose what it was called. You'll just have a sha and you've got to whack a mole that back into something useful. You don't know what you'll get with `latest`. Or the other mutable tags. 

The guides will move to replicated and pull via the channels. Maybe we're pre-optimzing. Lets get the release automation rolling and see whats hard.
