### ISSUE TITLE
Update preferences page for desktop IDE's

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7568]
On the preferences page for IDE's, currently the user is presented with the default browser editor, and the desktop one is behind a toggle. This update is to make the desktop IDE's more prominent in the UI, so they don't appear hierarchically as a second-class citizen. 

**Note:** there are many more changes required to make the desktop IDE UX smoother https://github.com/gitpod-io/gitpod/issues/6602, this is a small incremental change to make steps towards a better desktop UX. 

**Main proposed changes:** 
* Remove toggle for browser/desktop so all IDE's/editors are viewable by default
* Introduces a "none" preference for desktop IDE's (instead of the toggle)

|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/5528307/149158061-519f8f52-8491-4bcb-997a-ea7a77ed4841.png)|![image](https://user-images.githubusercontent.com/5528307/149157837-c4df9338-bc61-49ff-a455-460c5188e036.png)|

Link to [Figma design](https://www.figma.com/file/zgiOqtQm3AH3HOCSnd4jK2/Editor-preferences-page-%237568?node-id=0%3A1)

**Comment by mustard-mh** [comment]
@gtsiolis 
1. Wondering if we have prepared an image for Desktop None? 
2. Subtitle like INSIDERS has a margin-left 2, is it designed like this?
![image](https://user-images.githubusercontent.com/20944364/149933900-05231e4f-f197-44c3-a1d3-4bce8d371e79.png)

**Comment by gtsiolis** [comment]
@mustard-mh 

> Wondering if we have prepared an image for Desktop None?

We did not have one but posted a possibly good option in https://github.com/gitpod-io/gitpod/pull/7653#discussion_r786745763. Feedback is welcome!

> Subtitle like INSIDERS has a margin-left 2, is it designed like this?

Probably a leftover froma previous PR. We can probably remove this, see https://github.com/gitpod-io/gitpod/pull/7653#discussion_r786746504.
