### ISSUE TITLE
Create admin data table and store the telemetry status

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7571]
The installation-telemetry is an opt-out service where the status will be stored in a database. A database is use to allow for the admin users to opt in or out without having to reconfigure the application at cluster-level.

This will likely be more of an admin data table where the telemetry status is one part. It may require key/value pair support as well.

As a first iteration, suggest calling this `d_b_installation_admin` with a boolean type for `telemetry`, defaulting to `true`

## Potential problems:

- ~we use NodeJS TypeORM to generate the migration scripts. This will be (I believe) the first Golang component that will access the MySQL database so the established pattern will need thinking about. It will also need NodeJS support as the dashboard will have to access this.~ Having talked through the problem with @corneliusludmann, we've suggested that creating an API endpoint in `server` and having the `installation-telemetry` component call it would be the best solution to this. This requires an API endpoint (and appropriate authentication) inside `server`

**Comment by roboquat** [comment]
@MrSimonEmms: The label(s) `team: self-hosted` cannot be applied. These labels are supported: `team: IDE, team: meta, team: workspace`

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7571#issuecomment-1011181108):

>/team self-hosted


Instructions for interacting with me are available [here](https://github.com/gitpod-io/gitbot/blob/main/plugins/customlabels/README.md). If you have questions or suggestions related to my behavior, please file an issue against the [gitbot](https://github.com/gitpod-io/gitbot/issues/new) repository.
</details>

**Comment by roboquat** [comment]
@MrSimonEmms: The label(s) `team: self-hosted` cannot be applied. These labels are supported: `team: IDE, team: meta, team: workspace`

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/7571#issuecomment-1011923754):

>/team self-hosted


Instructions for interacting with me are available [here](https://github.com/gitpod-io/gitbot/blob/main/plugins/customlabels/README.md). If you have questions or suggestions related to my behavior, please file an issue against the [gitbot](https://github.com/gitpod-io/gitbot/issues/new) repository.
</details>
