### ISSUE TITLE
how to open jupyter notebook from gitpod terminal?

### ISSUE THREAD

**Issue by XinYaanZyoy** [gitpod-io/gitpod#758]
when I run
`jupyter notebook`

it runs but there's kernel error!

so, instead of using pyenv(which is installed by default gitpod image) i installed anaconda!

but even in this case there's something wrong either in access permission or kernel thing!

have anybody opened, edited and pushed a ipynb from gitpod??

**Comment by AlexTugarev** [comment]
Hi @XinYaanZyoy! Running the notebook server in a workspace, or at least being able to connect to a hub is a nice idea.

Can you share a repo with the dockerfile included?

**Comment by XinYaanZyoy** [comment]
you mean, repo with notebooks and dockerfile?
which dockerfile are we actually pointing to here btw!?

i've .gitpod.dockerfile and dockerfile(repo app)
is it sufficient?

https://github.com/xsoft-technologies/Xbooks

**Comment by AlexTugarev** [comment]
I missed the repo URL. 

Looking at the notebook server logs I see the default config of the notebook server has strict CORS rules. cf. `[W 11:37:21.661 NotebookApp] Blocking Cross Origin API request for /api/terminals.  Origin: https://8888-e0e6622d-1fda-4c01-a335-86765b453364.ws-eu0.gitpod.io, Host: localhost`

You can use this command to tell the notebook server to allow your workspace location to access the API: 
```
jupyter notebook --NotebookApp.allow_origin=\'$(gp url 8888)\'
```

**Comment by AlexTugarev** [comment]
Another issues is that you actually should get to the proper workspace URL when following the localhost URL from 

```
[C 11:36:55.355 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=a374b15a80549c0462aedad483ff897ed450c89913bdecdc
```

Checking this separately.

**Comment by AlexTugarev** [comment]
@XinYaanZyoy you might be interested in following https://github.com/gitpod-io/gitpod/issues/711

**Comment by XinYaanZyoy** [comment]
@AlexTugarev thanks for your reply!
i don't think there's any problem with localhost URL!
i think the problem is in the way gitpod is configured for python!
i'm totally naive, i've no idea what the actual causer is!

**Comment by XinYaanZyoy** [comment]
@AlexTugarev thank you so much!
this solves it!

by the way is there any config file to configure Notebook.allow_origin??

**Comment by AlexTugarev** [comment]
> i think the problem is in the way gitpod is configured for python!

Can you tell me, what's wrong with it? What do you miss there? We're happy improve.

Regarding the localhost URL which get clear in #711: we want to make `ctrl + click` on `localhost:8888` open the actual workspace port URL.

**Comment by AlexTugarev** [comment]
> by the way is there any config file to configure Notebook.allow_origin??

Please configure the notebook server to you needs as described in https://jupyter-notebook.readthedocs.io/en/stable/config.html

Starting with ...
```
jupyter notebook --generate-config
```

**Comment by AlexTugarev** [comment]
Closing this as there is no action required. Open new issues if something is unclear 🙏 

BTW with newly added python extension and installing notebook server by default in the workspace-full image we're getting closer to a nice OOTB experience 🎉

**Comment by arita37** [comment]
any workaround ?

**Comment by alesanchezr** [comment]
Hello! Microsoft released a jupyter notebook extension that works great with VSCode and Gitpod.
I created a sample repo that I always use as a template here: 

https://github.com/breatheco-de/jupyter-notebook-template
