### ISSUE TITLE
Make View Account Statement more usable

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#7583]
The View Account Statement feature in the Admin dashboard is currently not readable, and even copying the JSON to a clipboard is painful because of a lack of scrolling.

| Current view | Proposed |
| - | - |
|<img width="273" alt="Screenshot 2022-01-13 at 11 13 30" src="https://user-images.githubusercontent.com/8015191/149310995-30504f2c-4f26-41ad-b2b3-29534ce1defd.png"> | No UI at all, just return a content-type JSON response, and a content-disposition header so that you can save it it in a file. |

The JSON response should be downloadable.

**Comment by laushinka** [comment]
Would there be a download button? Where would it be? @jldec @gtsiolis
Or instead of "View Account Statement" it becomes "Download Account Statement"?

**Comment by jldec** [comment]
this 👇 
>  "View Account Statement" becomes "Download Account Statement"?
