### ISSUE TITLE
Integrate yara into agent-smith

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#7584]
## Is your feature request related to a problem? Please describe
Right now agent-smith runs its own set of classifiers (rule matchers). We should add [Yara](http://virustotal.github.io/yara/) to the mix so that we can rely on existing rule sets.

## Describe the behaviour you'd like
I'd like agent-smith to be able to consume yara signatures. We could use [go-yara](https://github.com/hillu/go-yara) although that would introduce a CGO dependency to agent-smith.

**Comment by atduarte** [comment]
@aledbf this was closed in favour of the referenced epic

**Comment by aledbf** [comment]
oops, sorry.
