### ISSUE TITLE
Unable to start Gitpod with custom Docker Image

### ISSUE THREAD

**Issue by trieloff** [gitpod-io/gitpod#76]
**Describe the bug**
I am trying to open https://gitpod.io/#https://github.com/trieloff/helix-helpx which injects a custom `.gitpod` file here: https://github.com/trieloff/helix-helpx/blob/master/.gitpod

The `Dockerfile` for the image is: https://github.com/adobe/helix-dockerimage/blob/gitpod/gitpod.Dockerfile

When launching Gitpod with https://gitpod.io/#https://github.com/trieloff/helix-helpx it seems to be stuck on status

> Building Workspace Image ... (1/5)

for a while before getting the error message

> Build a69de77c-9bfd-4c5b-aa04-3f3837903f48 has status FAILURE!

**To Reproduce**

Open https://gitpod.io/#https://github.com/trieloff/helix-helpx and wait.

**Expected behavior**

I expect the gitpod IDE to load using the Docker image specified in the `.gitpod` file.

**Comment by geropl** [comment]
Hi @trieloff, thanks for your feedback!

We're actually working on making that process a lot less painful and provide more feedback during the build process (#62). We expect to have something there in the next few days, I'll keep you posted!

Back to your concrete example: I think an additional line with `USER root` at the end should fix it.

**Comment by trieloff** [comment]
Thanks, it's working now.

**Comment by trieloff** [comment]
I've added a few words to the documentation.
