### ISSUE TITLE
Feedback Issue: Dotfiles Support

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#7603]
## Objective

This issue is to track feedback related to Dotfiles Support.

See related roadmap item [[21](https://github.com/gitpod-io/roadmap/issues/21)]

**Comment by trumbitta** [comment]
https://github.com/trumbitta/dotfiles didn't 100% work for me

A `README.md` was indeed symlinked, but my customized `.gitconfig` wasn't

[I understand](https://discord.com/channels/816244985187008514/932639935473811486) this is due to the file already existing in the workspace.
Here's my reply to a suggested workaround (merging via install script):

> thanks but I'm hesitant to do that in an install script, because I need to use this same repo in my work machine and in my personal machine, where I have already an "inversion of control" situation with: 
>
> ```
> [include]
>        path = ~/.gitconfig-local
> ```
>
> I use .gitconfig-local to make git merge its own configurations when needed, without my intervention with a script

**Comment by axonasif** [comment]
A user wished to have a feature that would allow them set a default `.gitpod.yml` and `Dockerfile`(if specified in `.gitpod.yml`) https://github.com/gitpod-io/gitpod/issues/6275. We surely can script up something on `install.sh` from our dotfiles repo to automatically copy these files but that would require the user to create a new workspace to see the changes. I think it will be nice if somehow we could supply custom `.gitpod.yml` and `Dockerfile` on condition from our dotfiles repo and that Gitpod would pick them up.

cc @csweichel

**Comment by filiptronicek** [comment]
Linking https://github.com/gitpod-io/gitpod/issues/7639 because it is related to dotfiles 🙂.

**Comment by axonasif** [comment]
Cross-linking https://github.com/gitpod-io/gitpod/issues/7592 here.

**Comment by draxaris1010** [comment]
Maybe it would be handy for setup scripts to clone submods if the .dotfiles dir is not owned by root

**Comment by parched** [comment]
How does this work with VS Code User settings? My settings in `~/.config/Code/User/settings.json` don't seem to be applied. The User settings that gitpod lets you edit appears to be some virtual file?

**Comment by axonasif** [comment]
> How does this work with VS Code User settings? My settings in `~/.config/Code/User/settings.json` don't seem to be applied. The User settings that gitpod lets you edit appears to be some virtual file?

Yes, it's stored on your browser.

**Comment by parched** [comment]
Ok, would it be possible to make gitpod use the file in .config instead if it's present? Or, as a workaround, is there a way to write to the in browser file, so I can sync  it in the install script?

**Comment by weitzman** [comment]
FYI I wasnt getting my dotfiles repo but the logs gave a clue at `~/.dotfiles.log`. I hadnt given Gitpod access to my private repos at Github. I fixed that and it now works as documented. Thanks for this feature.

**Comment by tommydrum** [comment]
Another small feature request: automatic execution of `.install.sh` and other variants prepended with the `.`

Reason being: this being dotfiles, I try to keep everything in this repo.. a dotfile. (Feels cleaner for me, but that's subjective).

**Comment by axonasif** [comment]
> Another small feature request: automatic execution of `.install.sh` and other variants prepended with the `.`
> 
> Reason being: this being dotfiles, I try to keep everything in this repo.. a dotfile. (Feels cleaner for me, but that's subjective).

You can always call your other scripts from your main `install.sh`.

**Comment by christian-bromann** [comment]
> Yes, it's stored on your browser.

@axonasif I don't understand the answer. I am trying to get my `zsh4humans` set up and need the default shell for the `gitpod` user to be `$(which zsh)` and not `bash`. Is there a way to define user custom vscode settings? (btw: I use the VSCode app not the browser).

**Comment by trumbitta** [comment]
@christian-bromann IIRC in order to have zsh as my default shell I set up the `$SHELL` environment variable in my user settings in Gitpod.

<img width="514" alt="image" src="https://user-images.githubusercontent.com/462705/169336735-7fe88ae8-aacb-4487-96f0-e12b6c80ae0e.png">

**Comment by christian-bromann** [comment]
@trumbitta thanks, this works when I create a new terminal within VSCode but fails when executing tasks. I could workaround it by modifying them but the idea of dot files is to create custom settings. So I guess a suggestion would be to have a Gitpod user allow to set the default shell for all their tasks.

**Comment by christian-bromann** [comment]
Ok, I have to correct myself: it seems that zsh is now used everywhere but all tasks started by gitpod come with this terminal UI:
![Screenshot 2022-05-19 at 18 19 41](https://user-images.githubusercontent.com/731337/169349520-07cb1e54-b1ff-4cd3-a37c-5b991d641fe1.png)
While a new shell correctly starts like this:
![Screenshot 2022-05-19 at 18 19 56](https://user-images.githubusercontent.com/731337/169349569-39fdc5d5-c7c0-437c-b386-09849f288315.png)

Even an `exec zsh` doesn't help.

**Comment by christian-bromann** [comment]
fyi: behavior between using VSCode as application where
```sh
❯ echo $SHELL
/usr/bin/zsh
```
vs browser:
```sh
 $ echo $SHELL
/bin/bash
```

differs

**Comment by trumbitta** [comment]
Idk what to say... my shell is `zsh` everywhere and it works via the `SHELL` env variable without `/usr/bin` 🤷 

You can also find my dotfiles repo some comments above.

**Comment by tommydrum** [comment]
> > Another small feature request: automatic execution of `.install.sh` and other variants prepended with the `.`
> > Reason being: this being dotfiles, I try to keep everything in this repo.. a dotfile. (Feels cleaner for me, but that's subjective).
> 
> You can always call your other scripts from your main `install.sh`.

Yea, this would be a pretty obvious solution, but also defeats the purpose of why people like me have the install script include a prepending dot. The point of the setup is that the `.install.sh` is the main setup file, and is hidden by `ls` or `ll`, leaving only the data as listable, not configuration or installation scripts. And if someone were to say "just delete the installer afterwords".. then it creates a change to `.git`, leaving git conscious shells to be a bit annoying. Just deleting the `.git` as well.. just makes managing/updating the dotfiles itself more work.

(Not meaning to be condescending, just trying to explain the usecase and the other mitigation's problems.)

**Comment by quangv** [comment]
I was getting the error `error: This script is meant to be run on Gitpod, quiting...` tweaked the `setup.sh` by @axonasif, @trumbitta 🙏 to copy over `.gitconfig` as follows:

```
#!/usr/bin/env bash

set -eu;

if test ! -v GITPOD_REPO_ROOT; then {
    printf 'error: This script is meant to be run on Gitpod, quiting...\n' && exit 1;
} fi

_source_dir="$(readlink -f "$0")" && _source_dir="${_source_dir%/*}";
printf '%s\n' "$(< "$_source_dir/.gitconfig")" >> $HOME/.gitconfig
```

**Comment by axonasif** [comment]
> Ok, I have to correct myself: it seems that zsh is now used everywhere but all tasks started by gitpod come with this terminal UI: ![Screenshot 2022-05-19 at 18 19 41](https://user-images.githubusercontent.com/731337/169349520-07cb1e54-b1ff-4cd3-a37c-5b991d641fe1.png) While a new shell correctly starts like this: ![Screenshot 2022-05-19 at 18 19 56](https://user-images.githubusercontent.com/731337/169349569-39fdc5d5-c7c0-437c-b386-09849f288315.png)
> 
> Even an `exec zsh` doesn't help.

Hey @christian-bromann, it should be fixed now, it was probably related with `TERM` variable having `xterm-color`.

**Comment by axonasif** [comment]
> Idk what to say... my shell is `zsh` everywhere and it works via the `SHELL` env variable without `/usr/bin` 🤷
> 
> You can also find my dotfiles repo some comments above.

I forgot why I said that, but it was likely because something wasn't working for me 😅
