### ISSUE TITLE
[Dashboard] Single View for *My* Workspaces

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#7604]
## Context & Issue

The dashboard has gone through some major changes during the last two quarters. We have introduced the notion of teams, projects and now finally also surface prebuilds. 

We (I 🙄) have pushed for making projects center, so that it becomes the default start page as well as the default first thing to do for new users. I today think that both decisions didn’t improve the user experience. I find myself landing on the projects page just to go to the workspaces page because I want to start a workspace.

I believe starting workspaces is the primary thing users do on the dashboard, so we should revert the workspaces page to be the default (at least as long as that is the place to start workspaces from).

Well, there is currently more than one workspace page, which leads to another change that I think we should revert. The teams/projects/prebuilds structure is all about configuration and checking the state of prebuilds, the information here is also shared with everyone who has access (team members). Having a workspaces tab below a project, that only shows workspaces for that project has turned out to be pretty useless and it violates the expectation that the UI below teams and projects is the same for everyone.

I think a user should have one global workspaces list again. I’m not sure how to model that, as we have the user/team hierarchy on the top left. But I’m sure our creative meta team can come up with a model for that 😁.

## Proposed solution

- **Remove the workspace tabs under projects.**
- **Remove the workspace tabs under teams.**
- **Move the ‘workspaces’ tab to the left and redirect to it from gitpod.io/**

**Comment by geropl** [comment]
FWIW: I personally like:
 - Move the ‘workspaces’ tab to the left and redirect to it from gitpod.io/ (until we have a better replacement, e.g. a "create workspace page, or so)
 - Make `/workspaces` show _all_ my workspaces (again)

Having workspaces tabs under "teams" and "projects" might still be useful, but I'm not too involved and it might not be worth the additional complexity. Also, never used them until now (not accessible enough, not immediate benefit)

**Thought**:
 - having a "team" column on the "workspace list" might be a way to model T&P
 - separate: making that column clickable could lead to the team-specific workspace list (useful? not sure)

**Comment by jldec** [comment]
Here's an example from the [preview environment](https://sefftinge-my-workspaces-7604.staging.gitpod-dev.com/) of #7606 

- Of the 3 workspaces, the first was started from a prefixed URL, the 2nd from a project under my personal account and the the 3rd from a project under a team. For me, seeing all 3 in one list reduces mental load and makes things easier. 👍 
- The content and layout of the rows in the list could be improved E.g. include project (and team) info, and less duplicate information with better spacing.
-  Seeing the workspace names with recognizable user-repo-xxxx prefixes also helps to make things easier.

![Screenshot 2022-01-14 at 12 33 05](https://user-images.githubusercontent.com/849592/149516383-4e19373e-d0b1-412d-bb78-7e9415a2bebb.png)
