### ISSUE TITLE
jsonnet support

### ISSUE THREAD

**Issue by irizzant** [gitpod-io/gitpod#761]
Could we have [jsonnet](https://jsonnet.org) support?

Currently they have a visual studio and IntelliJ support which could help. Supported tools are reported [here](https://jsonnet.org/learning/tools.html)

**Comment by svenefftinge** [comment]
Did you try downloading and installing the [VS Code extension](https://github.com/heptio/vscode-jsonnet)?
See also https://www.gitpod.io/docs/vscode-extensions/

**Comment by irizzant** [comment]
No I didn't know about [VS Code extension](https://github.com/heptio/vscode-jsonnet), thanks for the update.

I see it provides syntax coloring, I was wondering if there could be anything more advances for refactoring, jumping to files and the like.

Thank you
