### ISSUE TITLE
Improve warning alert component design

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7613]
### Problem to solve

:a: The first version of the warning alert component design was based on high saturated colors[[1](https://en.wikipedia.org/wiki/Colorfulness)] and didn't adapt on dark theme colors (see screenshots below) as we did with labels in https://github.com/gitpod-io/gitpod/pull/4607.

| Delete deletion modal on light theme ☀️ | Delete deletion modal on dark theme  🌔 |
|-|-|
| <img width="1440" alt="Screenshot 2022-01-14 at 6 02 14 PM (2)" src="https://user-images.githubusercontent.com/120486/149554777-9874372f-1280-4840-b7a9-9ddb4ca198db.png"> | <img width="1440" alt="Screenshot 2022-01-14 at 6 02 04 PM (2)" src="https://user-images.githubusercontent.com/120486/149554780-28004770-4e00-43c2-9fcb-f59d349c0931.png"> |

| Labels on light theme ☀️ | Labels on dark theme ☀️ |
|-|-|
| ![image](https://user-images.githubusercontent.com/24960040/123451112-b2409e00-d5dd-11eb-8ae2-f2d581a7572d.png) | ![image](https://user-images.githubusercontent.com/24960040/123451032-9ccb7400-d5dd-11eb-9b96-57f48128eedc.png) |

:b: In the latest design specs using ther warning alert component, we've tried to improve the colors of the warning alert component, see example in https://github.com/gitpod-io/gitpod/pull/7295#discussion_r781620284.

| Proposed design for the warning alert component |
|-|
|  <img width="1440" alt="148848588-dddd6c66-8e7f-4a48-a0c6-61e8055d8574" src="https://user-images.githubusercontent.com/120486/149555791-b6d53963-ba36-467d-9832-e7119f1f77fe.png"> |

### Proposal

Since this is using the [`AlertBox`](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/AlertBox.tsx) component, we could update this once and improve the UX of this component across the product.

Next steps could include improving the rest of alerts by clearly defining the available types (info, warning, error, etc) and documenting when to use which.

**Comment by jldec** [comment]
Assigned to @jankeromnes per https://github.com/gitpod-io/gitpod/pull/7295#discussion_r786166821

**Comment by jldec** [comment]
Removing from groundwork for now.

**Comment by gtsiolis** [comment]
Closing this as the first iteration of the new alert component was added in https://github.com/gitpod-io/gitpod/pull/8783. Thanks, @mustard-mh!
