### ISSUE TITLE
Unexpected connections to processes listening on localhost

### ISSUE THREAD

**Issue by JonMerlevede** [gitpod-io/gitpod#7628]
### Bug description

When opening a TCP socket on `127.0.0.1`, some local process establishes a connection to it every second (source is 127.0.0.1, random port). This causes issues e.g. with PySpark, which opens a socket and complains about bad data being sent to it. The same problem does not occur when listening to `0.0.0.0` or e.g. `127.0.0.2`.

I've also noticed that when listening on `127.0.0.1`, then `supervisor` starts listening on the same port, but on the local tap interface, and would like to understand why.

### Steps to reproduce

Start a process that listens on `127.0.0.1` (port 12989 here is a random port), e.g. using `socat`:
```
socat -d -d TCP4-LISTEN:12989,bind=127.0.0.1,reuseaddr,keepalive,fork STDOUT
```
Socat will print something to the screen every time a connection is established.

To verify that this interferes with `pyspark`, run the PySpark shell `pyspark`. PySpark in local mode will open up a socket on `127.0.0.1` and a random port. You will see a stream of messages:
```
ValueError: The value of the provided token to the AccumulatorServer is not correct.
```

Verify that `supervisor` starts listening, e.g. using `netstat`:
```
netstat -tulpn
```

### Expected behavior

I expect the socket to receive no connections

### Example repository

The issue can be reproduced on any workspace. I created a workspace that has PySpark, socat and netstat installed for easy verification here: https://gitpod.io/#https://github.com/JonMerlevede/gitpodissue.

**Comment by aledbf** [comment]
@JonMerlevede the source of the connection is a local test of the port availability. This behavior is being refactored to avoid connections.
