### ISSUE TITLE
[Admin] Search for projects and show project details

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#7636]
Admin page should allow searching of projects by entering the repo or the slug.

(The following screenshot is just a placeholder - this will need more design decisions)
<img width="483" alt="Screenshot 2022-01-17 at 11 13 21" src="https://user-images.githubusercontent.com/8015191/149750673-9c2d66de-8adf-48ce-a04e-eeb895613fe1.png">

#### Search

- [x] sub-string match anywhere in the cloneUrl (assuming this is possible, and OK for DB performance)
- [x] nice-to-have: match on slug 

#### Search results
- [x] list entries show name (link to project detail), cloneUrl (link to git provider)
- [x] list ordered by created date
- [ ] ~list ordered by updated date~

#### Project details
- [x] page URL is /admin/projects/project-id
- [x] name
- [x] repository (from cloneUrl)
- [x] incremental prebuilds (from settings)
- [x] owner
- [x] team
- [x] created date
- [x] list of prebuilds

#### ~Prebuild details~
- [ ] ~page URL is /admin/prebuilds/prebuild-id~
- [ ] ~same content (with prebuild log) as in projects UI~

**Comment by laushinka** [comment]
| With Prebuilds | No Prebuilds |
| - | - |
| <img width="515" alt="Screenshot 2022-01-27 at 12 33 38" src="https://user-images.githubusercontent.com/8015191/151351078-93eebf8f-f431-4b83-b47b-9fdee7a81532.png"> | <img width="582" alt="Screenshot 2022-01-27 at 12 33 31" src="https://user-images.githubusercontent.com/8015191/151351123-0cfc41c5-7e08-4c7b-9385-15c9ca3cb9fc.png"> |

**Comment by laushinka** [comment]
@jldec @gtsiolis How it looks like in progress 👆🏼

**Comment by laushinka** [comment]
@jldec @gtsiolis And this is what the search list looks like in progress: 
<img width="557" alt="Screenshot 2022-01-27 at 12 35 53" src="https://user-images.githubusercontent.com/8015191/151351334-e1982f22-c49d-44c5-aeb0-6b7455652569.png">

**Comment by gtsiolis** [comment]
Thanks for the update, @laushinka! I'm posting below the current state of the designs, after catching up with @jldec earlier today, see [relevant document](https://www.notion.so/gitpod/WebApp-Design-Sync-8c61b5f0cd2840e394fbe15f8f25099d) (internal). Feedback is welcome!

| Projects List | Project Details |
|-|-|
| <img width="1440" alt="Projects (List)" src="https://user-images.githubusercontent.com/120486/151411916-76b54c90-06cf-434a-b590-c8a3166170dc.png"> | <img width="1440" alt="Projects (Entry)" src="https://user-images.githubusercontent.com/120486/151411918-3797a740-2830-4325-87d4-1ebc9c6ff469.png"> |

**Comment by laushinka** [comment]
> I'm posting below the current state of the designs, after catching up with @jldec earlier today

@gtsiolis Thanks! Some questions:
1. Where would we put the information on incremental prebuilds and whether it's deleted?
2. Do teams also have an avatar? In case the owner is a team?

@jldec In the tasks list in the description, we have the prebuild details as well. Do we want this in this ticket too? Or should this ticket be the MVC for the project search? Reusing the components are not that straightforward, as every method call needs to be created and adjusted for admin actions as well. I'm fine with working on them, but also would be happy to see the most important things shipped.

**Comment by jldec** [comment]
I looked at the current implementation with @laushinka using the implementation in #7882
- The project list with 3 columns: name, cloneUrl, and created, works well
  Let's keep that design for now, and switch to name-above-with-git-provider/org-below in a separate ticket when we have a consistent way to do that across lists.
- Similarly, the project detail which follows the layout from workspaces, and includes user and team in 2 separate values, works well. We can upgrade to a user-or-team pattern later. 
- The prebuild detail can be added separately - for this first implementation just showing the prebuild list below the project is already a big step forward for admins.

**Comment by gtsiolis** [comment]
Thanks, @laushinka @jldec! Agree with https://github.com/gitpod-io/gitpod/issues/7636#issuecomment-1024096006. Just posted some review comments in https://github.com/gitpod-io/gitpod/pull/7882#pullrequestreview-867809190.
