### ISSUE TITLE
[dashboard] Make functionality of the dotfiles settings button more clear

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#7639]
## Is your feature request related to a problem? Please describe
In the user preferences you can now set a repository for your dotfiles, which is great, **but** when you put in your desired dotfiles repository and you click <kbd>Save Changes</kbd>, it makes you question if you need to use this button for all settings (it really doesn't, [I checked](https://github.com/gitpod-io/gitpod/blob/4bdcf8c8f203795c2951a19940e3151a57795f1e/components/dashboard/src/settings/Preferences.tsx#L196)). It is the only setting that does not autosave after the user makes a selection and that makes it look like the button below it should be used for all preference changes the user initiates.

## Describe the behavior you'd like
It would probably make sense to separate the different sections of the preferences page (maybe add some horizontal rules) and/or change the text of the button to something more indicative of the setting which is actually saved or maybe even borrow something from GitHub's repository settings and add make the button appear a horizontal flexbox with the text input: 
![image](https://user-images.githubusercontent.com/29888641/149783948-e0cf75ba-06dd-4d29-93c1-b99acbed252a.png)

## Describe alternatives you've considered
Autosave, but that would not be ideal, ever, maybe only after an `onpaste` event.

**Comment by gtsiolis** [comment]
Thanks for noticing, @filiptronicek! Improving the dotfiles repository selection is something we also track in https://github.com/gitpod-io/gitpod/issues/7385.

However, I agree that moving that _Save Changes_ button next to the text input element as an inline form could help avoid some confusion as users could assume that button is required for persisting all changes inside the preferences page.

Marking this also as a **good-first-issue**.

🍊 🍊 🍊 🍊 

An additional good intermediate step could be to either introduce a better user feedback upon save as described in https://github.com/gitpod-io/gitpod/pull/7337#discussion_r777479053:

> Auto-saving the input here happens in the background but is lacking 🅰️ call to action and 🅱️ some user feedback upon save which both will probably be resolved in the second iteration in #7385.

> For 🅰️, we could add an action button below to save changes so that users won't be surprized when they accidentally change this input and dotfiles configuration fails, etc. Alternatively, we could introduce a new auto-save pattern that makes it visible to the user that we auto-save on every key press.

> For 🅱️, ideally this manual save action would also need some feedback in the user interface so that users can safely acknowledge that the setting has been updated. This could be done with a subtle loading indicator (spinner) inside the button when saving changes that remains visible for a noticeable period of time or using a toast notification (#3530) which can be considered out of the scope of this PR.

**Comment by andreafalzetti** [comment]
I was about to create an issue for this, but it already exists, so +1 from me too :)

**Comment by loujaybee** [comment]
This is not just an issue with dotfiles, but when adjusting the IDE preferences (which is auto-saved) this button also appears to be necessary (as it's at the end of the form, when in fact it's unrelated to the IDE preferences)

**Comment by gtsiolis** [comment]
Thanks @loujaybee, @andreafalzetti, @sagor999, and @filiptronicek for the feedback! Could not agree more with all the points you listed. 

In the spirit of [minimum viable changes](https://www.notion.so/gitpod/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e#0c2e0d6c8a99404b97ccdc206b573d72) and [shipping](https://www.notion.so/gitpod/Core-Values-Differentiators-2ed4c2f93c84499b98e3b5389980992e#d766b4a2f4664dea9905ac29e65a5ccf), I've opened https://github.com/gitpod-io/gitpod/pull/10136 to improve the current state until we pick up https://github.com/gitpod-io/gitpod/issues/7385 which will take into account improvement on the new workspace input modal.
