### ISSUE TITLE
Epic: automate deploy of workspace clusters

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7644]
## Summary

Automated deploys of workspace clusters happen weekly

## Context

We do not deploy automatically on a regular, scheduled basis. Therefore, it requires human hours to orchestrate the related deploy test and eventual execution (or backout). 

## Value

We want to continuously deploy workspace clusters automatically, to regain those hours. Why? So we can spend more time shipping features and bug fixes, and less time with operational/maintenance tasks.

## Acceptance criteria

1. Build [packer image](https://github.com/gitpod-io/gitpod-packer-gcp-image) 
2. Stand up a K3s cluster with `workspace-preview` using latest packer image
3. Run tests, on pass, update [ops image](https://github.com/gitpod-io/ops/blob/main/deploy/workspace/common.sh#L13), and teardown `workspace-preview`
4. [Automation](https://github.com/gitpod-io/ops/blob/main/.werft/workspace-cluster-new.yaml#L109) deploys real clusters to regions, joining them to meta
5. Automation [runs a loop where we shift load up, and run integration tests, and result from prior test informs whether we continue shifting load](https://github.com/gitpod-io/ops/blob/main/.werft/shift-traffic.yaml); sad path we handle manually 

## Measurement

1. New deploys are successful without human intervention. (we'll plan to use Werft, rather than Github Actions)

## Hypothesis

If we automate workspace cluster deploys, we'll have more time to focus on other work, and incrementally release values to customers.

## In scope

The image we use for nodes, test automation, integration tests (currently fails), werft jobs to trigger deploys, joining to meta, and shifting load. Also, some shell scripts will be partially replaced (have complexity reduced) with the introduction of [mage](https://magefile.org/).

## Out of scope

Workspace cluster disposal
Authoring entirely new test suites

## Complexities

The integrations tests are considered as first class product.

**Comment by sagor999** [comment]
As a note:
When we switch to PVC, I think we will no longer require ws-daemon to be up 100% of the time. 
In that case, we might be able to deploy faster\often by deploying new images and performing restart rollout of the updated component. (this might not work for all changes, but it might be enough for 95% of changes). And for remainder of 5% we can perform full cluster rotation.

Currently deploying new cluster and shifting traffic is very cumbersome and slow operation.
But if we can just perform restart and pull of new image, then we can technically push to main -> and rollout into prod automatically.

**Comment by atduarte** [comment]
Closed in favour or https://github.com/gitpod-io/gitpod/issues/15065 and https://github.com/gitpod-io/gitpod/issues/15068
