### ISSUE TITLE
[observability] Get better insight to disk I/O

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7645]
## Is your feature request related to a problem? Please describe

[Our current node overview lacks read/write specs for node disk I/O.](https://grafana.gitpod.io/d/gitpod-nodes-overview/gitpod-nodes-overview?orgId=1&refresh=30s). This makes it difficult to tell if we're stressing disks when troubleshooting, but also in general, from a planning standpoint.

## Describe the behaviour you'd like

[See this existing dashboard for workspace and meta clusters, with the ability to filter by cluster, node pool, and node.](https://grafana.com/grafana/dashboards/11074/revisions). If you watch the video (below), Arthur shows how to update an existing dashboard to work with variables, so it can be used at Gitpod. Add variables so that we can filter by cluster, node pool, and node.

## Additional context

This will help, for example, when troubleshooting issues related to heavy I/O like backup failures, or many backups happening at the same time.

**Comment by kylos101** [comment]
@gitpod-io/platform hey there, can you help me? I want to schedule this work for the workspace team, so that we can have this new dashboard for workspace clusters (which I think will benefit all of our clusters), but have some concerns.

1. Can we consume external dashboards, given our libjsonnet configuration at Gitpod? Given the picture below, I assume yes, we should just have to import it (in a preview environment), alter it, export the JSON, and persist it.
2. It seems like we'll have to modify the dashboard, to support cluster filtering, but it appears to already support node and node pool, which is great!
3. Can you think of anything else we should change with this dashboard, if we decide to use it?

As a test, I did:
![image](https://user-images.githubusercontent.com/1272076/149838557-950d05a5-efc2-4137-8960-48283462b979.png)

**Comment by kylos101** [comment]
@aledbf I am [soliciting feedback](https://github.com/gitpod-io/gitpod/issues/7645#issuecomment-1014898000) from the Platform team.

It seems like this dashboard would help with minimal customization (we could add cluster)! :heart_eyes:

**Comment by mads-hartmann** [comment]
@ArthurSens can you follow up with @kylos101 to clarify how to approach this best.

**Comment by ArthurSens** [comment]
Hey @kylos101, I've recorded a loom trying to explain how I'd get the mentioned dashboard into production:

https://www.loom.com/share/ca15ea6ab12c465f9a72ff75e8f80ad6

We also have some written documentation [here](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/README.md), but please ping us if anything isn't clear 🙂

**Comment by mads-hartmann** [comment]
Thanks @ArthurSens - @kylos101 I'm removing this from the platform project, but please re-add if you need more input from us.

**Comment by kylos101** [comment]
That's perfect, thank you both! @ArthurSens I appreciate the video and promise to carve out time to look at it soon.

**Comment by kylos101** [comment]
@princerachit I am not seeing `node pool` as a parameter in the report, can you add in a follow-on PR? It can with node (host) and you added cluster. Let me know if I am missing `node pool` under another name?

**Comment by princerachit** [comment]
We decided that we can live with magnifiers button not working in the dashboard. So marking this as done. See the relevant internal [slack thread ](https://gitpod.slack.com/archives/C01KGM9D8LE/p1651456291807269?thread_ts=1651136493.159209&cid=C01KGM9D8LE)for more details
