### ISSUE TITLE
Keyboard shortcuts don't work with non-QWERTY keyboard layout

### ISSUE THREAD

**Issue by rothgar** [gitpod-io/gitpod#7649]
### Bug description

When editing a file with gitpod no keyboard shortcuts work because the gitpod interface captures the QWERTY keys while the browser sends the correct operating system layout.

An example is Ctrl+s to save a file Gitpod says it sees ctrl+; (where the s key is)

Other keyboard shortcuts like copy/paste and command palette keys activate different keyboard shortcuts. I also saw #5740 but that requires changing settings each time gitpod is launched and not really a solution.

### Steps to reproduce

Change operating keyboard layout to anything except QWERTY. Open gitpod and press ctrl+s to save a file

### Expected behavior

Keyboard shortcuts should respect the OS keyboard layout.

### Example repository

It happens with any repo I've tried launched from gitlab or github.

### Anything else?

This works properly in GitHub Workspaces

**Comment by jeanp413** [comment]
Hi @rothgar, couple of questions:
- Can you share what version of gitpod vscode you are using, press `f1` -> `Help: About`
- What OS and browser are you using?
- What keyboard layout gets detected for you? (you can click on the layout entry in the status bar and select the appropiate layout for now)
![image](https://user-images.githubusercontent.com/25115070/149959398-72afedaf-d8fb-415a-b3bf-c84189ac15b2.png)
- What's the proper layout that should be detected (what layout gets in codespaces)?

**Comment by rothgar** [comment]
So I tried again on a Windows computer and it works fine
```
Version: 1.63.2
Commit: 16d43d2bb89bb32b58ff0c84bef55486269760d6
Date: 2022-01-12T05:43:47.372Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
```
Here's the user-agent from my Ubuntu 20.04 laptop where it fails
```
Version: 1.63.2
Commit: 16d43d2bb89bb32b58ff0c84bef55486269760d6
Date: 2022-01-12T05:43:47.372Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
```
I also tried from Fedora and it appears that this problem is only with Linux host OS (I've tried Ubuntu 20.04 and Fedora 35)

In each case I'm using Chrome but have also tried Firefox.

The detected layout in the status bar for each computer is US.

Codespaces also detects US as the keyboard layout but keyboard shortcuts work there.

**Comment by nyurik** [comment]
Same issue when running on Chrome on Ubuntu using Dvorak keyboard layout.

```
Version: 1.66.1
Commit: e7430877d63066eb812360b3ec2b82f1fae9d558
Date: 2022-04-07T16:57:49.400Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
```

**Comment by fweth** [comment]
Same with ChromeOS (which is technically Linux, but still wanted to mention).

**Comment by jeanp413** [comment]
Duplicate of https://github.com/gitpod-io/gitpod/issues/13662

Please follow https://github.com/gitpod-io/gitpod/issues/13662#issuecomment-1276607009 or alternatively try updating `"keyboard.dispatch": "keyCode"` in your settings.json
