### ISSUE TITLE
Fork command should ask for write permissions on demand

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#765]
The `Fork ...` command shows a menu to allow creating a fork or switching to an existing fork based on the current repo on GitHub. We try to reproduce the functionality provided by GitHub on any repo. There are basically two phases to this command:
 1. gathering information about the repo and the fork network to show a list of choices
 2. creating a fork into a selected account

If you start with initial `read:email` permissions and call the `Fork ...` command, it will fails right after calling the GitHub API to compile the list for 1.)
Unfortunately, we only mention the missing `read:org` permission, but to the auth request for `public_repo` as well to be able to do the step 2.) afterwards.

This is at least confusing, especially if you just want to switch to an existing fork and don not plan to do write operations when started using Gitpod.

**Comment by Kreyren** [comment]
@AlexTugarev Why did you close it?

**Comment by AlexTugarev** [comment]
Reopening, as it was not yet deployed.

**Comment by AlexTugarev** [comment]
The fix was deployed by now 🎉
