### ISSUE TITLE
Workspace stopped suddenly

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#766]
> I was working in a project and suddently the workspace was stopped and dissapeared from my list of repositories. Another one appears to be running "two days ago" but I stopped it this week.

Bug report through twitter:

https://twitter.com/developerbedoya/status/1167429411995574273

**Comment by geropl** [comment]
Hi @developerbedoya,

I quickly checked our logs but found nothing suspicious. Could you share the ID of the workspace that got stopped?

**Comment by developerbedoya** [comment]
It resolved spontaneously around two hours later. Thanks!

**Comment by geropl** [comment]
Glad to hear that!

If you find anything that's not working as expected please report here. Thank you!
