### ISSUE TITLE
Interchage private and public port visibility icon on the editor

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7662]
###  Problem to solve

Currently, the icon of the port visibility button on the on the Remote Explorer panel for VS Code, is confusing as a user has to click the unlocked button to make a port private.

See relevant discussions from the 🍊 Gitpod[[1](https://gitpod.slack.com/archives/C01KGM9BH54/p1629186714007100)] (internal) and 🦊 GitLab[[2](https://gitlab.slack.com/archives/C01BHLELZKK/p1642363368002000)] (internal).

Cc @akosyakov @loujaybee 

<img width="363" alt="Screenshot 2021-08-17 at 10 46 02 AM" src="https://user-images.githubusercontent.com/120486/149963468-be1e61fa-5c37-4e8c-a2db-cbbbf293dbf4.png">

### Proposal

Interchage private and public port visibility icon, so that public ports are using the unlocked icon. 🔒

**Comment by gtsiolis** [comment]
Looping in @loujaybee in case this could be a easy fix that's also confusing to others, too.

**Comment by loujaybee** [comment]
Thanks @gtsiolis ! For sure does look like a small fix, let's see if we can get it updated soon! 🙏

**Comment by shaal** [comment]
Yes please 😍

**Comment by gtsiolis** [comment]
Closing as this has been resolved. Cc @shaal @loujaybee

**Comment by shaal** [comment]
🎉 THANK YOU @gtsiolis !!!!
