### ISSUE TITLE
Remove secondary navigation on the admin dashboard

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7668]
### Problem to solve

When an admin user visits the admin dashboard, the secondary navigation is visible while none of the options is selected since we're currently using a page layout with the left sidebar for selecting Users and Workspaces sub-pages.

### Proposal

While we could eventually re-use that secondary navigation as we work towards improving the admin dashboard (https://github.com/gitpod-io/gitpod/issues/7597), a good MVC (minimum viable change) could be to remove secondary navigation on the admin dashboard.

| BEFORE | AFTER | 
|-|-|
| <img width="1440" alt="Screenshot 2022-01-18 at 11 29 15 PM (2)" src="https://user-images.githubusercontent.com/120486/150022019-44897e06-11e5-4366-92c3-6613262387c5.png"> | <img width="1440" alt="Screenshot 2022-01-18 at 11 29 31 PM (2)" src="https://user-images.githubusercontent.com/120486/150022022-4ccddb8a-6b5a-4d02-824b-e50720d55e04.png"> |

**Comment by SangameshItagi** [comment]
Hi @gtsiolis 
I am interested working on this issue. Can you assign it to me?

**Comment by gtsiolis** [comment]
Hey @SangameshItagi! Yes, feel free to open a pull request (PR) for any open issue without an assignee. 🏓

**Comment by gtsiolis** [comment]
@SangameshItagi While removing the extra tabs is a great MVC (minimum viable change) and you are more than welcome to open a PR about this,  just wanted to give a heads-up about what's changed and the long-term direction of the navigation inside the admin dashboard.

Given the recent additions of the settings (https://github.com/gitpod-io/gitpod/pull/7732) and upcoming addition of projects (https://github.com/gitpod-io/gitpod/issues/7636) in the admin dashboard, now that we have tabs, which were not preset during the initial dashboard redesign, long-term we'd like to use the tabs and replace the pills we currently have in the admin dashboard as this pattern fits and scales better for this need. I've opened https://github.com/gitpod-io/gitpod/issues/7879 to track this in case you'd like to pick that issue up instead of this one. Your call. 🏀

**Comment by SangameshItagi** [comment]
@gtsiolis Sure will pick #7879  issue, instead of this.

**Comment by gtsiolis** [comment]
Closing this in favor of https://github.com/gitpod-io/gitpod/issues/8385.
