### ISSUE TITLE
Gitpod workspace running continuosly and consuming my remaining time

### ISSUE THREAD

**Issue by developerbedoya** [gitpod-io/gitpod#767]
**Describe the bug**
Gitpod started the workspace "cee2b6c8-fc06-4c9f-ab76-25bfde231582" (which I stopped days ago) and is running continuously and consuming my remaining time. Now I cannot stop the workspace nor using gitpod because the time allocated was consumed by that workspace. See screenshot.
![gitpod](https://user-images.githubusercontent.com/7063448/64169624-95dddb00-ce24-11e9-9752-b1b89ae26653.png)

**To Reproduce**

**Expected behavior**

**Comment by svenefftinge** [comment]
All your workspaces are marked as stopped in the database. Also there are no suspicious times.
Is the app still telling you the same?

**Comment by svenefftinge** [comment]
This seems to be an issue with a new cluster. We are investigating.

**Comment by svenefftinge** [comment]
The issue has been resolved. Please verify and thanks for reaching out and reporting it.
