### ISSUE TITLE
Template that supports Amazon Linux2 AMI(Amazon Machine Image)

### ISSUE THREAD

**Issue by gurreriamzn** [gitpod-io/gitpod#7672]
## Is your feature request related to a problem? Please describe
Not related to problem, related to enabling.  I'm an engineer at Amazon and develop native AWS services on Amazon Linux2 images exclusively.  The Gitpod platform is fits our development/deployment patterns so well and we wished there were more components/apps/templates etc supporting AWS development.   Currently I can use gitpod for some minor sandboxed testing/deployment/devops.  Without an Amazon Linux2 template, that's where it ends for the engineers here.  I looked in your docker repo and AL2 is not amongst the available underlying distros  

## Describe the behaviour you'd like
I read quite a bit of your docs, maybe I missed it, but we'd like the ability to create AMI's for use on Gitpod from scratch.  Amazon Linux2 AMI with customized AWS services baked in.  Is this currently possible?

## Describe alternatives you've considered
looked into building docket images but not sure how to use AL2

## Additional context

Thank you!

**Comment by csweichel** [comment]
Gitpod is container-based, hence users cannot bring their own kernel and we don't have systemd support. Are there container images that are based on AL2?
