### ISSUE TITLE
live reload in preview window?

### ISSUE THREAD

**Issue by DavidGriswoldTeacher** [gitpod-io/gitpod#768]
Hi,

I'm trying to get a Live Reload server working in the preview window with GitPod. I have tried using the npm package 'light-server' which works fantastically on my computer, but the reload doesn't work. When I inspect, I get this in the console:

```
Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

I do not know enough about websockets to know if there is any way I can fix this, perhaps with a more capable live-reloading server?

**Comment by svenefftinge** [comment]
Live reload servers are often done through a separate endpoint (port). You need to make sure that one is exposed as well and that the frontend uses the right URL. You can obtain the url using the gp cli: 
```sh
gp url <portnumber>
```
If you can provide a concrete project (or snapshot) I'm happy to take a look.

**Comment by DavidGriswoldTeacher** [comment]
https://gitpod.io#https://github.com/graded-cs-resources/p5js-starter-with-typings will open up a simple example. In that example I switched to browser-sync instead of light-server, and it seems to work about half the time. I set up a task in the tasks.json to run browser-sync, so you can start there to see my current command.

If I change the port browser-sync uses  from 3000 to 4000, it stops working for me, and my students had mixed success getting it to work for them. If you could help me figure out how to configure browser-sync so it works more consistently I'd really appreciate it!

**Comment by svenefftinge** [comment]
You need to allow listening on all interfaces by providing the option `--listen 0.0.0.0`.
I.e.:
```
browser-sync -f *.html -f *.js --no-open --no-ui --listen 0.0.0.0
```

**Comment by bwklein** [comment]
This hugo server command enables live reload for me on Gitpod.

`hugo server -D -F --baseUrl $(gp url 1313) --liveReloadPort=443 --appendPort=false --bind=0.0.0.0`

**Comment by pawlean** [comment]
Thank you @bwklein for the contribution! If anyone is reading this thread, we also have a Hugo x Gitpod template that works ✨ https://github.com/gitpod-io/template-hugo
