### ISSUE TITLE
Error on workspace start: "Cannot connect to ws-daemon"

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#7688]
I just got the error below and had to just try again in order to start a workspace. 

<img width="468" alt="Screenshot 2022-01-19 at 15 09 34" src="https://user-images.githubusercontent.com/372735/150147260-15102295-6c96-447f-b3ee-3946b42671b5.png">

So I looked into the logs and found that there are regular spikes of this error. Here's the diagram of the last three hours, filtering for `"cannot connect to ws-daemon"`:

<img width="695" alt="Screenshot 2022-01-19 at 15 14 56" src="https://user-images.githubusercontent.com/372735/150148238-1115d276-1bbd-4682-9d2c-36e0fc9857bc.png">

These are the number of workspace instances that failed with this error so far this year:

 | instances | day |
 | ----------|-----|
 | 148	 | 2022-01-19 00:00:00
 | 222 |	2022-01-18 00:00:00
 | 148 |	2022-01-17 00:00:00
 | 45 | 	2022-01-16 00:00:00
 | 83 | 	2022-01-15 00:00:00
 | 109 |	2022-01-14 00:00:00
 | 133 |	2022-01-13 00:00:00
 | 3 |	2022-01-12 00:00:00
 | 7 |	2022-01-11 00:00:00
 | 12 |	2022-01-10 00:00:00
 | 1 |	2022-01-07 00:00:00
 | 6 |	2022-01-06 00:00:00
 | 1 |	2022-01-05 00:00:00
 | 5 |	2022-01-04 00:00:00
 | 4 |	2022-01-03 00:00:00
 | 2 |	2022-01-02 00:00:00
 | 1 |	2022-01-01 00:00:00

**Comment by svenefftinge** [comment]
Some of those workspaces ran for longer, so it doesn't seem to be an exclusive starting issue.

**Comment by kylos101** [comment]
Thank you, @svenefftinge !

For posterity and transparency, we are executing on a release for today which should help mitigate this issue. Today's deployment includes a fix for CPU limiting, which is a factor. 

If it does not solve this issue, we will schedule this issue right away. 

Also, we're adjusting an existing warning, to notify us when this condition manifests in the future. The problem now is we learn too late when this problem is happening, which prevents us from collecting meaningful data from the suffering node(s).

**Comment by kylos101** [comment]
Hello, we hit a couple bumps in today's deployment, and decided to post pone until tomorrow (Friday, January 21).

CC: @aledbf

**Comment by utam0k** [comment]
This is probably due to the fact that the pod of `ws-daemon` is not registered in the `ws-daemon` service. I'll think of some countermeasures.

**Comment by kylos101** [comment]
Hey @utam0k , may we ask you to close #7918, and pair with @csweichel to own #7926? He can walk you through the code and test in a preview environment.

**Comment by utam0k** [comment]
> Hey @utam0k , may we ask you to close #7918, and pair with @csweichel to own #7926? He can walk you through the code and test in a preview environment.

@kylos101 I understand. Thank you for the adjustment.

**Comment by utam0k** [comment]
> Hey @utam0k , may we ask you to close #7918, and pair with @csweichel to own #7926? He can walk you through the code and test in a preview environment.

@kylos101 I understand. Thank you for the adjustment.

**Comment by kylos101** [comment]
> > Hey @utam0k , may we ask you to close #7918, and pair with @csweichel to own #7926? He can walk you through the code and test in a preview environment.
> 
> @kylos101 I understand. Thank you for the adjustment.

I'm certain you'll enjoy yourself, but seeing the code, but also discussing and testing with @csweichel ! Thank you for being flexible. :smiley:

**Comment by utam0k** [comment]
After this PR is applied to the production environment, I will look at the log.
https://github.com/gitpod-io/gitpod/pull/7926
