### ISSUE TITLE
[installer] Make the Kubernetes objects subject to per-team approval

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#7690]
When making changes to components in the installer today, one needs the approval of the team which owns that component. That does not hold for the set of objects that make up the environment, e.g.

https://github.com/gitpod-io/gitpod/blob/e6924d94369df23af8611a33f59a93ebdb67e76b/installer/pkg/components/components.go#L35-L64

This has broken things in the past, e.g. https://github.com/gitpod-io/gitpod/issues/7686

**Comment by MrSimonEmms** [comment]
@MrSimonEmms This may slip to 2022.02, but check how difficult
