### ISSUE TITLE
[Installer]: add tests to ensure that code coverage doesn't fail

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7695]
If you look at (nearly) any PR, the `codecov/project` job fails due to the Installer having only scant unit tests, eg #7693

- [ ] Add enough unit tests to ensure that this job passes.
- [ ] Update the development expectation that this is enforced for all future PRs

**Comment by lucasvaltl** [comment]
@MrSimonEmms is this still relevant?

**Comment by MrSimonEmms** [comment]
I mean, we should have improved test coverage in the Installer but it'll likely never be of a higher priority than new features

**Comment by lucasvaltl** [comment]
Ok - I will close this. Increasing test coverage should always be something we do though.
