### ISSUE TITLE
Add JetBrains Gateway download "ready page"

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#7708]
Currently, when a user sets up their JetBrains IDE, they are presented with a Code With Me splash page (**Figure 1**), which instructs the user of the instructions to setup JetBrains using the Code With Me download. With the new solution where Code With Me is removed, and the user does not have the gateway application installed, the redirect will not work, and the user should be prompted to download gateway. **Options:** Directly link the gateway asset, link to the JetBrains toolbox, or link to our documentation where there are instructions on how to perform the gateway download. Also, see how this UX is already implemented in JetBrains spaces (**figure 2**). 

| Figure 1      | Figure 2 |
| ----------- |  ----------- |
| ![image](https://user-images.githubusercontent.com/5528307/150309994-5dda2529-f32e-4af7-a069-a2c013514b49.png)      | ![image](https://user-images.githubusercontent.com/5528307/150309886-53ed4460-1ab3-4fbc-8380-e22c7d3efa00.png) |

**Comment by loujaybee** [comment]
Let me know if you have thoughts or feedback on this @gtsiolis from a UI/UX point of view ! 🙏

**Comment by akosyakov** [comment]
How can I make following nicer?
<img width="1904" alt="Screenshot 2022-01-20 at 16 39 23" src="https://user-images.githubusercontent.com/3082655/150372158-64752755-6f00-4152-b8b5-d919852696c1.png">

cc @loujaybee @gtsiolis

**Comment by gtsiolis** [comment]
@akosyakov I've posted a proposal on how this could look like in https://github.com/gitpod-io/gitpod/pull/7711#pullrequestreview-859556119 and a suggestion to consolidate these instructions for all IDEs in https://github.com/gitpod-io/gitpod/pull/7711#discussion_r789702366.

**Comment by loujaybee** [comment]
Looks like this will be closed with: https://github.com/gitpod-io/gitpod/pull/7711#pullrequestreview-859556119
