### ISSUE TITLE
open local links as workspace links

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#771]
Some links can be local in markdown files and in PR descriptions and so on: http://localhost:8080/monaco-editor/test/?editor=src&monaco-typescript=src

By clicking on it nothing will be opened, it would be good if such a link is transformed in a proper workspace link before opening.

**Comment by svenefftinge** [comment]
I think it's a regression and that it used to be like that.

**Comment by svenefftinge** [comment]
this has landed in production by now.
