### ISSUE TITLE
Remove redirection to team context when previous context was a team

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7716]
### Problem to solve

Back in https://github.com/gitpod-io/gitpod/pull/5854 and https://github.com/gitpod-io/gitpod/pull/5894, we redirected users to the last selected team when loading `gitpod.io`. Cc @AlexTugarev @jankeromnes 

Also, we recently merged all workspaces lists into a single list in https://github.com/gitpod-io/gitpod/pull/7606. Cc @svenefftinge 

This makes redirecting to the last selected team, less useful or practical, especially with the upcoming changes to allow users to start workspaces for any project or team from the workspaces and other pages, see https://github.com/gitpod-io/gitpod/issues/7564. 💡 

See [relevant discussion](https://discord.com/channels/816244985187008514/839379835662368768/933687558309826560) from discord. Cc @jacobPARIS

### Proposal

Redirect to the new single workspaces list when loading gitpod.io.

**Comment by jacobPARIS** [comment]
> Redirect to the new single workspaces list when loading gitpod.io.

This would effectively solve the problem for me and remove the need for any dedicated "workspaces" nav items. As long as there is a gitpod logo within arms reach I can click that and get where I want to be

**Comment by svenefftinge** [comment]
> Redirect to the new single workspaces list when loading gitpod.io.

I think this is already the case.

FWIW, I like @jacobPARIS proposal to add a `workspaces` button to the global nav on the right. 
What do you think, @gtsiolis?

**Comment by gtsiolis** [comment]
> I think this is already the case.

@svenefftinge There's a small edge case where if the exit page is a team or a project page, openining `gitpod.io` will redirect back to the team page (projects list) instead of the new single workspaces list.

Besides this, adding a global workspaces menu sounds great! 💯 

🍊 🍊 🍊 🍊 

Things to consider while making this change:
1. If _Workspaces_ link is added on the right, consider hiding help links (_Docs_, _Help_) in their own dropdown menu or insie the user menu so that link weight remains balanced.
2. Consider moving the _Workspaces_ towards the left side of the navigation if possible as usually more important elements are placed on this side. See F-Pattern[[1](https://en.wikipedia.org/wiki/Screen_reading#F-Pattern)][[2](https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content-discovered/)][[3](https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content/)][...]

**Comment by gtsiolis** [comment]
The existing behavior will become irrelevant and actually helpful once we make the changes in https://github.com/gitpod-io/gitpod/issues/8385. Cc @jldec
