### ISSUE TITLE
Open in VS Code on Desktop not working anymore

### ISSUE THREAD

**Issue by vangel75** [gitpod-io/gitpod#7718]
### Bug description

Since 18/01, trying to open the workspace on my local Visual Studio Code gives the following error :

```
[1/20/2022, 1:47:58 PM] open workspace window: vscode://gitpod.gitpod-desktop/workspace/shares?%7B%22instanceId%22%3A%2253182045-55d3-4286-ad15-e78194a5d84a%22%2C%22workspaceId%22%3A%22sh4res-shares-z73s2wlgh0p%22%2C%22gitpodHost%22%3A%22https%3A%2F%2Fgitpod.io%22%7D
[1/20/2022, 1:47:58 PM] acquiring lock: gitpod.io
[1/20/2022, 1:47:58 PM] acquired lock: gitpod.io
[1/20/2022, 1:47:58 PM] fetching the local app from https://gitpod.io/static/bin/gitpod-local-companion-darwin-arm64
[1/20/2022, 1:47:58 PM] released lock: gitpod.io
[1/20/2022, 1:47:58 PM] failed to access the local app: Error: workspace not found
[1/20/2022, 1:47:58 PM] failed to open uri: Error: workspace not found
```

Detailed log is full of : 

`time="2022-01-20T13:51:07+01:00" level=warning msg="cannot get workspaces" error="json: cannot unmarshal string into Go struct field GithubAppPrebuildConfig.workspace.config.github.prebuilds.addCheck of type bool"
`

### Steps to reproduce

- Create workspace
- When workspace is ready, click on "Open in VS Code on Desktop" on gitpod interface.

### Workspace affected

sh4res-shares-z73s2wlgh0p

### Expected behavior

Open code in Visual Studio Code, like it used to do.

### Anything else?

OS : MacOS 12.1
Browser : Chrome
VS Code : 1.63.2

**Comment by jeanp413** [comment]
Hi @vangel75 could you share your `gitpod.yml` config? From the logs I think it's something wrong with it

**Comment by vangel75** [comment]
Hi @jeanp413 , here it is (I've removed the tasks part as I dont't think it matters) :
`image:
  file: ./.gitpod.Dockerfile

# Allow a failed build to fail CI
github:
  prebuilds:
    addCheck: prevent-merge-on-error

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
[...]

experimentalNetwork: true

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3010
    visibility: public
  - port: 8081
    onOpen: open-browser
    visibility: public
  - port: 3000
    onOpen: open-browser
    visibility: public

# Add common useful extensions in VSCode
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - EditorConfig.EditorConfig
    - shardulm94.trailing-spaces
    - oouo-diogo-perdigao.docthis
`

**Comment by jeanp413** [comment]
@vangel75 the error is caused by the `addCheck: prevent-merge-on-error` in the .gitpod.yml, I created a PR fixing it in the meantime you can remove it to open your workspace in vscode desktop

**Comment by vangel75** [comment]
@jeanp413 ok, many thanks.

**Comment by vangel75** [comment]
@jeanp413 do you have an estimated time of when the fix will be released ? Thanks

**Comment by jeanp413** [comment]
@vangel75 I think I'll be deployed tomorrow https://github.com/gitpod-io/gitpod/issues/7794#issuecomment-1020058554
