### ISSUE TITLE
Ask if you want to open a new workspace for the same repository

### ISSUE THREAD

**Issue by dantehemerson** [gitpod-io/gitpod#772]
Sometimes I forget that repositories already have a workspace in **Gitpod**. And when I click on the **Gitpod** button (google-chrome plugin) a new workspace is created for the same repository.

I suggest (for example) that there is a popup that asks:

>There is already a workspace with this repository.
>Do you want to create a new workspace or enter one of these workspaces?

**Comment by svenefftinge** [comment]
In Gitpod workspaces are intended to be used once per task, so you'd only go back to an existing workspace if you want to continue on that task (i.e. a new feature or so). 
For new tasks you should create a fresh workspace, so you are starting off from a clean state.

**Comment by jankeromnes** [comment]
FYI Gitpod already has such a “workspace already exists” pop-up, but it only shows up if you’re trying to open the same commit again (e.g. if you re-open a branch or PR that hasn’t changed, you’ll see this pop-up, but not if new commits were pushed in the mean time).

Also, while we do encourage to create fresh workspaces for every task, some people are indeed used to creating one workspace and always returning to it. Maybe we could make the “workspace already exists” behavior configurable? E.g. never show / check per commit (current/default) / check per repository (requested in this issue).

And finally, note that you can always see and manage all your workspaces from https://gitpod.io/workspaces/
