### ISSUE TITLE
Wildcard subdomains on public workspace URLs

### ISSUE THREAD

**Issue by ThePaulMcBride** [gitpod-io/gitpod#7733]
## Is your feature request related to a problem? Please describe
Building an app that uses multiple subdomain is hard. This isn't unique to Gitpod, it's equally challenging when building in localhost.

## Describe the behaviour you'd like
I am building an app that gives signed up users their own subdomain. Let's say my domain is `example.com`. When a user signs up or signs in, they will be redirected to their own unique subdomain like `user1.example.com`. Now let's say while developing that app on Gitpod, it runs on port `5050`. I can access it at `5050-my-repo.ws-eu27.gitpod.io`. When I sign up to the app, I'll be redirected to `user-1.5050-my-repo.ws-eu27.gitpod.io`, which isn't routed to my app and its game over.

I would love for Gitpod to route all traffic that arrive at `*.5050-my-repo.ws-eu27.gitpod.io` to the app running on port 5050. Optionally, this could be enabled or disabled with a setting in the `gitpod.yaml` file.

## Describe alternatives you've considered
I can work around this locally. If I proxy my app to localhost:5050 on my machine and use a tool like `dnsmasq` to route all .localhost domains to localhost then it can work. With this setup my request to `my-project.localhost:5050` will be routed to the app running on Gitpod. But more importantly `some-subdomain.my-project.localhost:5050` will also be routed correctly.

## Additional context
Sub domains are a big part of most saas projects. Enabling this would make build saas software easier for everyone.

**Comment by atduarte** [comment]
From #8784:

>  I have learned that we are quite limited in the number of SSL certificates we can generate [[1](https://letsencrypt.org/docs/rate-limits/)] and we wouldn't be able to implement this as described. 😞
> For now I don't see a clear and straightforward alternative that is better than the local companion app trick or proxying to different ports. I will research the topic, and in the meantime if you have any ideas please share 🙏
