### ISSUE TITLE
High idle resource usage

### ISSUE THREAD

**Issue by borisyordanov** [gitpod-io/gitpod#7736]
### Bug description

A fresh workspace with no tasks, scripts or anything else running has half of it's RAM being used up and 1/4 of CPU threads.
![image](https://user-images.githubusercontent.com/12392666/150412666-62342e38-270c-4632-a214-41ee62b2c10b.png)

### Steps to reproduce

1. Open https://github.com/borisyordanov/Gitpod-Node-Example in a new workspace
2. Run `htop` in a terminal
3. Observe high resource usage in a repo with 4 files
![image](https://user-images.githubusercontent.com/12392666/150412998-06699572-2847-40e7-962e-1607dec140c4.png)

**Comment by axonasif** [comment]
Hi @borisyordanov, I would say that's pretty normal at times.

**Comment by axonasif** [comment]
Yes indeed that would be cool!

**Comment by borisyordanov** [comment]
@axonasif @akosyakov Is [this information](https://community.gitpod.io/t/how-much-resources-does-one-workspace-have/1677/2) up-to-date?

**Comment by akosyakov** [comment]
> @axonasif @akosyakov Is this information up-to-date?

cc @jankeromnes

**Comment by jankeromnes** [comment]
Yes, I think [this](https://community.gitpod.io/t/how-much-resources-does-one-workspace-have/1677/2) is still up-to-date.
