### ISSUE TITLE
All VSCode Plugin Installs Fail

### ISSUE THREAD

**Issue by zaptrem** [gitpod-io/gitpod#774]
**Describe the bug**

When dragging and dropping to install any plugin file downloaded from MS VSCode plugin marketplace installation fails with "Failed to share esbenp.prettier-vscode@2.2.2 extension from esbenp.prettier-vscode-2.2.2.vsix. Try to upload again." 

**To Reproduce**

Download Prettier VSCode plugin from the marketplace, attempt to install using drag and drop. Reproduced on blank Gitpod file setup along with personal development setup. Reproduced on latest Chrome on latest Windows 10 build (non-Insiders), as well as iOS 13.1 dev beta 2. Reproduced with a random sampling of other plugins both large and small.

**Expected behavior**

The plugin should install successfully.

**Comment by geropl** [comment]
@zaptrem We just deployed the fix, it should be working now.

**Comment by zaptrem** [comment]
Plugin loads are broken again, startup scripts aren't running either.

**Comment by TheBotlyNoob** [comment]
same error... Is there a fix?
