### ISSUE TITLE
docker in gitpod and custom docker images error on self hosted

### ISSUE THREAD

**Issue by ttauchen** [gitpod-io/gitpod#7741]
### Bug description

Starting a workspace with a custom image results in this error on execution of the first `RUN` statement:

> #5 0.147 container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted

Using the default image starts the workspace. Inside the workspace running `docker run hello-world` results in an error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: operation not permitted: unknown.

### Steps to reproduce

Running with https://hetzner.com/ cloud. 

1. Provision a CPX41 instance in Nuremburg or Falkenstein with image `Ubuntu 20.04`
2. Open https://github.com/MrSimonEmms/gitpod-k3s-guide with gitpod.io
3. Run `./setup install` without Cloudflare api keys (tested for `main.2201`, `main.2218` and `main.2245`)
4. Create https-certificates secrets on machine once k3s is installed
5. Connect self hosted gitpod to an auth provider and start a sample workspace (tested GitLab EE and github.com)

### Expected behavior

Custom images and docker in gitpod should work like on gitpod.io.

### Anything else?

@MrSimonEmms helped me a lot in getting to this results. You can check out me wasting our time here: https://discord.com/channels/816244985187008514/932599176922017793

**Comment by kylos101** [comment]
Hey @ttauchen , may I ask you to try using `main.2245` as a version? 

If you look at the [related changelog](https://github.com/gitpod-io/gitpod/commit/c3bcf6355c3f281367c5499d0a692b15a8c09450), I suspect it will help solve this issue because of:

> - Revert "Bump libseccomp" ([#7714](https://github.com/gitpod-io/gitpod/pull/7714)) - [@csweichel]> (https://github.com/csweichel)

I just tested in a new cluster we're building, and it works well:

```shell
gitpod /workspace/workspace-images $ date
Sun 23 Jan 2022 04:57:31 PM UTC
gitpod /workspace/workspace-images $ docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

cc: @axonasif

**Comment by ttauchen** [comment]
Hi @kylos101,

thank you for your reply. Error still remains for me. Added the tag to the list of tested tags.

**Comment by kylos101** [comment]
Looping in the @gitpod-io/engineering-self-hosted team. 

@ttauchen may we ask you to share a copy of the config you're using to do the install? Please obfuscate anything sensitive, like auth keys, prior to sharing.

CC: @corneliusludmann I added this to your respective project in Github. @MrSimonEmms :wave: :smile:

**Comment by MrSimonEmms** [comment]
I'll pick this one up as I know the back story from Discord. I've found our Hetzner login so will have a look at recreating it in that

Apologies for the delay @ttauchen - I missed this notification.

**Comment by johnktims** [comment]
I'm seeing the same error using `main.2278` on EKS.

**Comment by MrSimonEmms** [comment]
@ttauchen  @johnktims can you check if this is still a problem with the [2022.01 release](https://github.com/gitpod-io/gitpod/releases/tag/2022.01) please? I changed the `fsShiftMethod` to `shiftfs` by default which is typically the cause of it

**Comment by ttauchen** [comment]
> @ttauchen @johnktims can you check if this is still a problem with the [2022.01 release](https://github.com/gitpod-io/gitpod/releases/tag/2022.01) please? I changed the `fsShiftMethod` to `shiftfs` by default which is typically the cause of it

Pod ws-daemon does not start using the new installer:

```
  Normal   Pulled     114s (x2 over 2m9s)   kubelet            Container image "eu.gcr.io/gitpod-core-dev/build/shiftfs-module-loader:commit-351c0a69a68ec4fa149cbc182f5cdd2dd99fdf62" already present on machine
  Normal   Created    114s (x3 over 2m10s)  kubelet            Created container shiftfs-module-loader
  Normal   Started    114s (x3 over 2m10s)  kubelet            Started container shiftfs-module-loader
  Warning  BackOff    113s (x3 over 2m8s)   kubelet            Back-off restarting failed container
```

I assume this is due to shiftfs beeing enabled.

Do i need to install additional dependecies?
