### ISSUE TITLE
I'm banned

### ISSUE THREAD

**Issue by bahadirarkan** [gitpod-io/gitpod#775]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by meysholdt** [comment]
you were involved in activity related to a DOS attack. That's a violation of our [ToS](https://www.gitpod.io/terms/) and we can't tolerate that on our platform. If you want to use Gitpod for software development, let us know by sending an email to contact@gitpod.io, and we'll be happy to unblock you gain.
