### ISSUE TITLE
Sometimes files are bad to open in the browser, but it locks the editor in offline

### ISSUE THREAD

**Issue by krainboltgreene** [gitpod-io/gitpod#776]
When you open a binary it "soft locks" the editor in offline mode (for good reason!) however instead, it'd be nice it opened a phantom tab that said "Hey, we can't open this file" instead of putting you in offline mode.

**Comment by akosyakov** [comment]
Similar issue in the upstream: https://github.com/theia-ide/theia/issues/3859
