### ISSUE TITLE
dotfiles import failure: github authentication issue

### ISSUE THREAD

**Issue by nberlette** [gitpod-io/gitpod#7768]
### Bug description

In attempting to use the newly-released integration for dotfiles, I noticed that gitpod fails to authenticate with the GitHub server and is unable to clone my dotfiles repo. For security reasons, I have my dotfiles repository setup as a private codebase, but it seems as of now I would only be able to use this functionality with a public repository.

### Steps to reproduce

1. Set the `dotfiles` preference's value to a private repository's URL
2. Start up a new workspace
3. Notice the expected files are missing
4. Discover `.dotfiles.log` in the `/home/gitpod` directory, which contains:

```log
Cloning into '/home/gitpod/.dotfiles'...
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/nberlette/dotfiles.git/'
# dotfile init failed: waitid: no child processes
```

### Expected behavior

I expected to see my cool terminal colors and stuff 😢

**Comment by axonasif** [comment]
It's being tracked at https://github.com/gitpod-io/gitpod/issues/7565
