### ISSUE TITLE
[installer] The rendered manifest does not contains the required env var KUBE_STAGE

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#7776]
### Bug description

Several components rely on the value. 

### Steps to reproduce

-

**Comment by csweichel** [comment]
This is particularly bad for ws-daemon and content-service because it impacts the naming convention for the buckets. This will break users down the road.

See also https://github.com/gitpod-io/gitpod/pull/7779#issuecomment-1019919785

**Comment by csweichel** [comment]
@corneliusludmann and I had a discussion about how to move forward. Proposal:

1. we change the content-service config and move from a `stage` to a `bucketPrefix`. This is less magical and makes it clear what the value is used for.
2. the installer would default to `dev` for the `bucketPrefix` to maintain the current behaviour.
3. we'd introduce an `Unsupported` (maybe `Internal`) struct as part of the installer config surface where we can burry Gitpod specific configuration. We would never want a user to set any value in here, but we as Gitpod can do this. Each team would get a slice of the unsupported config. This struct might look something like this:
    ```go
    type UnsupportedConfig struct {
        Workspace *UnsupportedWorkspaceConfig
        WebApp *UnsupportedWebAppConfig
        IDE *UnsupportedIDEConfig
    }

    type UnsupportedWorkspaceConfig struct {
        BucketPrefix string
    }
    ```
4. We can override the bucket prefix in the unsupported config section.

Benefits: 
- we get rid of the magic "kube stage". 
- we can incubate config surface without having to make it public right away, which gives us more freedom to try things out.
