### ISSUE TITLE
Cannot add self-hosted Gitlab repos as a Gitpod Project

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#7781]
### Bug description

When I want to add a new project in Gitpod (in https://gitpod.io/new)
![image](https://user-images.githubusercontent.com/22901/150664953-7f2639b1-df37-4532-b20e-7822f70f32cb.png)

and I choose a self-hosted Gitlab server (last option in the screenshot above)

It doesn't show any repos available
![image](https://user-images.githubusercontent.com/22901/150664405-0b3b6808-bad0-44f9-ae7e-5944904d5d4c.png)

### Steps to reproduce

1. Create a user in Drupal.org - https://www.drupal.org/user/register
1. Open https://gitpod.io/#https://git.drupalcode.org/project/drupalpod
You'll see this screen
![image](https://user-images.githubusercontent.com/22901/150666766-59361d38-0520-4c33-a97b-4ea76aca89f2.png)
1. Click on the button `Authorize with git.drupalcode.org`
(You can ignore the workspace that opens, the steps above was just to get the authorization in Gitpod)

1. Go to https://gitpod.io/new
1. Click on `(change)` button
![image](https://user-images.githubusercontent.com/22901/150666880-76dab583-bdbf-40e2-ac2f-65bbbf1363b3.png)
1. Choose the 4th option in the screen above (`Continue with git.drupalcode.org`)
1. You'll see that there are no repos to choose
![image](https://user-images.githubusercontent.com/22901/150666893-c530b9f4-b924-4d12-ad9c-cdd745b4e5d1.png)

### Expected behavior

I was expecting to see all the repos under `https://git.drupalcode.org/project/*`
Specifically - https://git.drupalcode.org/project/drupalpod

### Anything else?

This is what I have in Gitpod's `Integrations` page -
![image](https://user-images.githubusercontent.com/22901/150666987-5e6b4ca3-15cf-4874-90b9-3af7d896a9eb.png)

**Comment by AlexTugarev** [comment]
@shaal, please help us to sort out issues with the project integration of self-managed GitLabs. It seems to be some sort of incompatibility in the API, which blocks the reading of projects here. We've seen similar with a very old installation of GitLab, thus would you mind to provide the version number?

**Comment by jankeromnes** [comment]
Alternatively, maybe you could invite one of us to your Self-Managed GitLab instance? I think this could make debugging easier.

**Comment by AlexTugarev** [comment]
@jankeromnes, thanks for the hint!

Just signed up successfully to https://www.drupal.org/u/alextugarev

**Comment by AlexTugarev** [comment]
I should be able to reproduce now.

**Comment by AlexTugarev** [comment]
@shaal, please check with this URL https://git.drupalcode.org/api/v4/projects?min_access_level=40 and let me know, how many projects are accessible to your account having `Maintainer (40)` permissions. See https://docs.gitlab.com/ee/api/members.html#valid-access-levels for more details on the access levels in GitLab. 

For me this is empty, actually I'm not able to see any in there. 

GItLab projects/repos can only be added to Gitpod if you have `Maintainer (40)` permissions, because that's a requirement for adding the webook for prebuilds and servers also a natural authorization level.

**Comment by shaal** [comment]
@AlexTugarev i can see projects listed on that url https://git.drupalcode.org/api/v4/projects?min_access_level=40

But I could see them only after I went to https://git.drupalcode.org and logged in (with my Drupal account)

**Comment by AlexTugarev** [comment]
> But I could see them only after I went to https://git.drupalcode.org/ and logged in (with my Drupal account)

that is expected. 

> Also, I just tried to find relevant log entries, but couldn't spot any related errors. Would you mind trying again and posting the time, please?

☝🏻  could you do this, please?

**Comment by shaal** [comment]
@AlexTugarev sure, relevant log entries for what? What should I try doing?

I just tried adding again any project that is hosted on drupal.org (empty list) 
![Screenshot_20220209-082312](https://user-images.githubusercontent.com/22901/153210029-de1f0f8e-02d5-47ba-b88a-c58caeff4649.jpg)

If it's easier we can also discuss this on Gitpod discord.

**Comment by shaal** [comment]
@AlexTugarev please see my question above ^

**Comment by shaal** [comment]
@AlexTugarev @jankeromnes Is there any update on this issue? Anything I can do to help?

**Comment by jankeromnes** [comment]
Thanks for the ping @shaal!

@AlexTugarev is the issue status still up-to-date? (I.e. you are assigned, project says "In Progress")
- If you're still actively working on this, how can I help? 😊
- If you don't currently have time for this, could you please un-assign yourself, and reset the project status to "Scheduled", so that someone else can pick this up? 🙏

**Comment by AlexTugarev** [comment]
There were actually two issues in here, and one got resolved with integrating Bitbucket Server into the New Project page. 

The remaining issue seems to be that the `getProviderRepositoriesForUser` returns empty response.

@shaal, what does https://git.drupalcode.org/api/v4/projects?min_access_level=40 return for you? For me, it's an empty array, which is expected as I'm not maintainer of any of those projects. Does the response contain the wanted projects for you?

**Comment by AlexTugarev** [comment]
@shaal, thanks very much for the details. There was one thing we didn't see in tests apparently. 

```
"namespace": {
      "id": 2,
      "name": "project",
      "path": "project",
      "kind": "group",
      "full_path": "project",
      "parent_id": null,
      "avatar_url": null,
      "web_url": "https://git.drupalcode.org/groups/project"
    },
```

This `group` kind is the key to the problem. While the API returns all projects from Gitlab using the current session auth (via browser), it's not showing projects in groups when authorizing with OAuth 2.0.

We need to check and clarify with Gitlab on the expectations here.

**Comment by AlexTugarev** [comment]
@shaal, just one question on the UI. You are sure to have clicked the drop down to select the `project` group?

<img width="418" alt="Screen Shot 2022-04-27 at 09 38 32" src="https://user-images.githubusercontent.com/914497/165467181-98c71422-4a9f-4fab-8723-415a9049968e.png">

**Comment by shaal** [comment]
@AlexTugarev 
When I choose a git provider like Github itself, I can choose an organization, and then I see this list
![image](https://user-images.githubusercontent.com/22901/165516488-3c311c4e-df5a-4246-bdac-383f8aab2dcb.png)

When I choose Drupal Gitlab self-hosted as git provider, I see this
![image](https://user-images.githubusercontent.com/22901/165516684-f6fb78f5-ba0c-4783-a7fb-f38431cf7760.png)
When I choose `shaal`, the list is empty, and nothing else that I can select -
![image](https://user-images.githubusercontent.com/22901/165516774-05276445-6285-48c2-8f86-808b0fb1942f.png)

**Comment by shaal** [comment]
@AlexTugarev, I opened Devtools -> Network -> WS, 
The first orange arrow shows the result when I select Github, the response is about 130k.
The second orange arrow shows the result when I select Drupal self-hosted Gitlab, the response is an empty array.
![image](https://user-images.githubusercontent.com/22901/165518514-0a8459ce-f982-46a7-baec-a1783d95668b.png)

**Comment by gtsiolis** [comment]
In case it helps, the only changes that were made to the **/projects** API endpoint from the release of the 14.9.3[[1](https://about.gitlab.com/releases/2022/04/12/gitlab-14-9-3-released/)] in April 12, 2022 to the next major 15.0 release which is already deployed on GitLab.com are the following two commits but not sure if these are related to the issue here.
> 1. https://gitlab.com/gitlab-org/gitlab/-/commit/57691c52d878a93c4acfb1b8a88b2185d78062b8
> 2. https://gitlab.com/gitlab-org/gitlab/-/commit/b7396cd27824c7e994794de9fbe66455b659b141

**Comment by shaal** [comment]
@AlexTugarev Anything I can help with?

**Comment by AlexTugarev** [comment]
@shaal, can you check if there are any restrictions configured in the GitLab instance to the permission model? 

I'll try to verify with a test instance of GitLab, maybe starting same version of GitLab in a workspace. But I don't yet see a way to proceed 😢

**Comment by shaal** [comment]
@AlexTugarev Are you available for a chat / call on Gitpod Discord?
I don't know how to get access token to run `curl` commands like you did.
How can I tell if there are any restrictions configured in the GitLab instance to the permission model?

Also, we could ask/discuss some of these things with the people who are in charge of Drupal's infrastructure / Self-hosted Gitlab.

**Comment by shaal** [comment]
@AlexTugarev, great news!
Neil Drumm (Drupal Association) was able to resolve the issue and wrote -
```
We had been stripping authentication headers for that path, we are no longer doing that. Since drupal.org is the canonical list of projects, we are careful about what we allow.
```

So now I can see DrupalPod (from Drupal's self-hosted Gitlab) and add it to my projects.
I do get 1 more error when I do that (although it seems that everything actually works as expected)
![image](https://user-images.githubusercontent.com/22901/165847397-eea2f122-5905-4161-87ad-520cbc3082d9.png)

After clicking on the green `Select` button, I get a popup in the browser:
```
gitpod.io says:
Request createProject failed with message: Cannot read properties of undefined (reading 'project_access')
```

I asked Neil Drumm if he knew what it was, and he responded -
```
That error message doesn’t tell me what path they are requesting, if it is another similar thing. I will need to know what it’s requesting next. And ideally a list of all subsequent requests they expect to work, if possible.
```

**Comment by AlexTugarev** [comment]
@shaal, oh I missed the last paragraph of your last message. 

> That error message doesn’t tell me what path they are requesting, if it is another similar thing. I will need to know what it’s requesting next. And ideally a list of all subsequent requests they expect to work, if possible.

That's a pity, that basically means, we'd need to scan the API surface used in Gitpod to enable it, right? 
Just to make sure, is allow-listing of `GET /api/v4/*` no option at all?

**Comment by AlexTugarev** [comment]
From reading https://github.com/gitpod-io/gitpod/blob/main/components/server/src/gitlab/api.ts#L101-L112, I can tell it's at least the following list of request (query params omitted)

```
GET,PUT,DELETE /projects
GET,PUT,DELETE /projects/:id
GET,PUT,DELETE /projects/:id/hooks
GET /projects/:id/repository/files/:file_path
GET /projects/:id/repository/commits
GET /projects/:id/repository/tags
GET /projects/:id/merge_requests
```

**Comment by AlexTugarev** [comment]
@shaal, can we close this issue now?

I think, once the web application firewall is setup correctly on Drupal's self-hosted Gitlab it should be good. We've verified with 2 different GitLab installations by now.

Please reopen or create another more specific follow up.

**Comment by shaal** [comment]
I don't think this is resolved yet...
Previously (https://github.com/gitpod-io/gitpod/issues/7781#issuecomment-1112663491) I was able to see list of projects in self-hosted Gitlab.

But now, in https://gitpod.io/projects/new after choosing Drupal git here (the last option)
![image](https://github.com/gitpod-io/gitpod/assets/22901/c4f6462c-ac2f-4554-afe6-6633cad74520)

I get this screen
![image](https://github.com/gitpod-io/gitpod/assets/22901/78a71067-c4b9-48be-a274-7960b9be6c93)

with this error in console.
```
Error: Request getProviderRepositoriesForUser failed with message: Response code 401 (Unauthorized)
    at main.js:449:48
    at main.js:276:17
    at main.js:260:13
    at setImmediate.js:40:13
    at l (setImmediate.js:69:21)
    at n (setImmediate.js:109:17)
```

The git repo I am trying to add to my personal user in Gitpod, is https://git.drupalcode.org/project/drupalpod

**Comment by tyler36** [comment]
Just came across this issue and it seems to be working for git.drupalcode.org now:

## Steps to reproduce
1. Open https://gitpod.io/#https://git.drupalcode.org/project/drupalpod
It said I was unauthorized, but I click to authorize and it open an oauth permission popup.
After giving permissing, I was able to start a project host on `git.drupalcode.org`

Now, in https://gitpod.io/projects/new after choosing Drupal git here (the last option), I can see 1 project that I am currently the maintainer for.

**Comment by shaal** [comment]
@AlexTugarev @gtsiolis @axonasif

It is now possible to open https://gitpod.io/#https://git.drupalcode.org/project/drupalpod, but there seems to be a bug. When the warning displays that you are not authorized, and you click to authorize, you are brought back to the page with the warning that you are still not authorized. However, reloading the page solves this issue. 

When opening the above link, you only have read permissions. When I try to push changes, I get an error that I am not allowed to do so. When I check https://gitpod.io/user/integrations, I see that I am missing write permissions. When I try to add write permissions, I get a new error. 

You can see the thread below for all the details of what I tried doing and what the Drupal organization tried doing, following Gitpod's documentation:

https://www.drupal.org/project/infrastructure/issues/3404441#comment-15396581

Could you please clarify what is missing so that users can open the Drupal-hosted GitLab repository in Gitpod and get write permissions?
