### ISSUE TITLE
changes are not shown in workspace list

### ISSUE THREAD

**Issue by pmassizzo** [gitpod-io/gitpod#7782]
### Bug description

When I run 'git status' in my workspace it shows changes, but in my workspace list it shows 'no changes'. 

### Steps to reproduce

To show the changes I have included the output of git status:

gitpod /workspace/crimson $ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   crimson-hl7-server/src/bin/hl7_sender/mod.rs
        modified:   crimson-hl7-server/src/bin/print_hl7.rs
        modified:   crimson-hl7-server/src/bin/simulator.rs
        deleted:    crimson-hl7-server/src/bin/test.hl7
        modified:   crimson-hl7-server/src/hl7_listener.rs
        modified:   crimson-hl7-server/src/hl7_nack.rs
        modified:   crimson-hl7-server/src/hl7_query.rs
        modified:   crimson-hl7-server/src/hl7_traits/hl7_lab.rs
        modified:   crimson-hl7-server/src/n6000/labresult_test.rs
        modified:   crimson-hl7-server/src/n6000/mod.rs

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Rocket.toml
        crimson-hl7-server/src/bin/ivet5.hl7
        crimson-hl7-server/src/bin/n6000.hl7
        ivet5.hl7
        last_error_ack.hl7
        last_labresult.json
        last_message.hl7
        t/
        test.hl7

no changes added to commit (use "git add" and/or "git commit -a")

### Expected behavior

I would expect it to show something link "17 changes"
<img width="1792" alt="screenshot" src="https://user-images.githubusercontent.com/97696743/150667371-1f5ac99e-bb9f-4eee-86f4-5d0a78eca763.png">

### Example repository

the GitHub repo is private

**Comment by utam0k** [comment]
@pmassizzo Thanks for your report!
I tried to reproduce the situation but could not 😭 The command I ran was as follows, and the repository is [here](https://github.com/utam0k/gitpod-playground/tree/7782).
It's a curious phenomenon. Can you ask them to check the .gitignore? Also, if there is a way to reproduce the minimum, it would be helpful.

```console
$ mkdir crimson-hl7-server
$ cd crimson-hl7-server
$ cd crimson-hl7-server 
$ cargo init --bin
$ mkdir -p src/bin/hl7_sender
$ echo "bin/hl7_sender/mod.rs" > src/bin/hl7_sender/mod.rs
$ echo "bin/print_hl7.rs" > src/bin/print_hl7.rs
$ echo "bin/simulator.rs" > src/bin/simulator.rs
$ touch src/bin/test.hl7
$ rm src/bin/test.hl7 
$ echo "hl7_listener.rs" > src/hl7_listener.rs
$ echo "hl7_query.rs" > src/hl7_query.rs
$ mkdir src/hl7_traits
$ echo "hl7_traits/hl7_lab.rs" > src/hl7_traits/hl7_lab.rs
$ mkdir src/n6000
$ echo "n6000/labresult_test.rs" > src/n6000/labresult_test.rs
```
and I got
```console
gitpod /workspace/gitpod-playground/crimson-hl7-server $ git status
On branch 7782
Your branch is up to date with 'origin/7782'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        ./
```

**Comment by csweichel** [comment]
@pmassizzo could you please provide the ID of the workspace you saw this behaviour with?

**Comment by kylos101** [comment]
Hey @pmassizzo , I am going to close this issue for now, if you are still experiencing this trouble, please reopen and let us know? I could not find a record of your workspace (using this , or a log entry for your user around the time of this incident.
