### ISSUE TITLE
[installer] New gitpod installer validate command cannot specify a namespace

### ISSUE THREAD

**Issue by yevon** [gitpod-io/gitpod#7784]
### Bug description

The validate command of the installer doesn't allow to specify a namespace, so whe it tries to find the secrets and certificate issuers it can't find them.

### Steps to reproduce

For a k3s cluster, the command I used is:

./installer validate cluster --kubeconfig /etc/rancher/k3s/k3s.yaml --config gitpod.config.yaml

How do I specify a namespace in the validation?

Results in:

     "name": "cert-manager installed",
      "description": "cert-manager is installed and has available issuer",
      "status": "WARNING",
      "errors": [
        {
          "message": "no cluster issuers configured",
          "type": "WARNING"
        }
      ]
    },
    {
      "name": "https-certificates is present and valid",
      "description": "ensures the https-certificates secret is present and contains the required data",
      "status": "ERROR",
      "errors": [
        {
          "message": "secret https-certificates not found",
          "type": "ERROR"
        }
      ]
    }

But I already have issuers and the secret in the namespace

**Comment by corneliusludmann** [comment]
Thanks for reporting this issue. Is it the same as in this issue? https://github.com/gitpod-io/gitpod/issues/7497

**Comment by yevon** [comment]
Yes, it is the same, so I will close it.
