### ISSUE TITLE
[installer] Add correct values for containerdRuntimeDir and containerdSocket for k3s clusters in the documentation

### ISSUE THREAD

**Issue by yevon** [gitpod-io/gitpod#7787]
I just used the values suggested by the docs but they were not correct for k3s.

Proper values for k3s are:

containerdRuntimeDir: /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
containerdSocket: /run/k3s/containerd/containerd.sock

**Comment by corneliusludmann** [comment]
Solved with KOTS (Replicated) as recommended installation method.
