### ISSUE TITLE
Define acceptance tests

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7789]
Suggested acceptance tests:

- Create a workspace with `workspace-full` image
- Create a workspace with a custom image
- Start, stop, restart a workspace to ensure custom data is stored to Minio _et al_
- Do a `docker run` inside the workspace
- Check that ports are exposed
- ~Share a workspace~ (enterprise licence required)
- Check that Segment receives telemetry data
- Check that telemetry can be disabled

Checklist:
- [x] Azure - external dependencies
- [x] Azure - internal dependencies
- [x] AWS - external
- [x] AWS - internal
- [x] GCP - external
- [x] GCP - internal

**Comment by csweichel** [comment]
is that on top of what the individual teams do in their (future) integration tests, or are you aiming to define the minimum set of tests you'd like to see and diff that against what the teams provide?

**Comment by MrSimonEmms** [comment]
@csweichel this is more for this first release as we're not incorporating the automated tests in with it - it should act more as a checklist so we can say "yes, this release works" when doing the testing.

The longer-term plan (hopefully by Feb release) is to get the integration testing wired up for the release. I'm not sure what bearing this will have on the integration tests, but that will be a task for @corneliusludmann and I to do.
