### ISSUE TITLE
Access to organization repos with write permission (Github classroom)

### ISSUE THREAD

**Issue by DavidGriswoldTeacher** [gitpod-io/gitpod#779]
I am a teacher attempting to use Gitpod combined with Github Classroom to teach students the basics of git and coding. The automated features of Gitpod made it so easy to get them started in a coding environment far more supportive and powerful than, say, Codepen. It works great, except when students attempt to push their changes to their own copy of the repositories (made using Classroom) they get a write permission error, even though all of their access control checkboxes are checked.

Github classroom works by leveraging Github organizations. I am the owner and manager (and only member) of an organization @graded-cpp-2019 . When students click a link I provide them, Github Classroom automatically creates a copy of my starter repository with their name and adds them as a collaborator. The screenshot below shows the "Collaborators" section of the settings for one student; you can see that he has Write permission on the repository. But when he tries to push from gitpod, it doesn't work. 

![image](https://user-images.githubusercontent.com/49095734/64528445-ec449100-d2de-11e9-976a-88f4ccceffd7.png)

Is there something else I need to do to enable this, or is this a permissions bug? Is there a workaround? For now, we're still committing daily and just re-launching the workspace from the gitpod app, but I'd like them to be able to store their work permanently on github.

**Comment by AlexTugarev** [comment]
Hey @DavidGriswoldTeacher! It's great to hear that you using Gitpod 🎉 

Please check that you've allow Gitpod to be used the the  @graded-cpp-2019 organization. Visit  https://gitpod.io/access-control/ and click on the settings button next to `GitHub` in the table header, and check the status of `Connection with Gitpod` (it's a GitHub page.)

If you don't see a ✅ there, please click on `Request` next to your org, and as an owner of that you'll receive a notification to confirm.

**Comment by DavidGriswoldTeacher** [comment]
It is enabled right now, but I think I might have enabled it while testing this morning, so it's possible that was the problem! I will not see the students with this problem again until tomorrow, but I will try again with them then and see if it works now. I didn't realize I'd need to enable it through my account too.

**Comment by AlexTugarev** [comment]
Please let us know if that works for you 🙏 

We're planing to improve the guidances in such error cases, so it'd tell you that Gitpod should be allowed for the particular organization in the case the repository belongs to it.

**Comment by DavidGriswoldTeacher** [comment]
This seems to have fixed the problem. Thanks!

**Comment by AlexTugarev** [comment]
@DavidGriswoldTeacher good to hear that!

**Comment by riowaller** [comment]
Thanks for the question @DavidGriswoldTeacher and thanks for the answer @AlexTugarev!! I know I'm late to the party!
