### ISSUE TITLE
New commit check doesn't work

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#7794]
### Bug description

With these two PRs #7535, #7661 we have introduced the possibility prevent merging when the prebuild failed on a commit.

It [works well](https://github.com/svenefftinge/testing-gh-app/pull/2) for me in a preview environment, but unfortunately doesn't work in production.

### Steps to reproduce

Install the github app on a repo that has the checks set to `prevent-merge-on-fail`.
E.g. https://github.com/svenefftinge/testing-gh-app

Push a breaking change and create a PR. The commit check should fail, like in [this PR](https://github.com/svenefftinge/testing-gh-app/pull/2).

### Example repository

https://github.com/svenefftinge/testing-gh-app

**Comment by JanKoehnlein** [comment]
Probably fixed by #7738 which will be deployed tomorrow.

**Comment by csweichel** [comment]
This may be related to the status updater running in both clusters and the EU cluster reacting based on a messagebus message but old database state.

**Comment by svenefftinge** [comment]
> This may be related to the status updater running in both clusters and the EU cluster reacting based on a messagebus message but old database state.

Thanks, Chris. I'm pretty sure this is the reason behind it. Looks like atm in every server instance we listen for all workspace events are handling them.
