### ISSUE TITLE
Unable to connect to outgoing port 2525

### ISSUE THREAD

**Issue by vseager** [gitpod-io/gitpod#7795]
### Bug description

Cannot connect to port 2525. This causes issue when testing outgoing email via SMTP. We have only started experiencing this issue  recently. It causes issue when trying to test outgoing mail.

### Steps to reproduce

`telnet smtp.mailtrap.io 2525`

### Expected behavior

```
telnet smtp.mailtrap.io 2525
Trying 54.158.84.126...
Connected to smtp.mailtrap.io.
Escape character is '^]'.
220 smtp.mailtrap.io ESMTP ready
```

**Comment by jordeu** [comment]
Any news on this? It also affect us.

**Comment by atduarte** [comment]
It is also happening with port 587 and 25. Validated with another domain (http://portquiz.net/).

**Comment by atduarte** [comment]
I talked to the team to understand the cause of this issue and learned that this is related with a change (i.e., adding two new ports to a block list) we had to make to mitigate abuse. We are sorry this affected your workflows, will revert the change and will seek better mitigation strategies.

**Comment by kylos101** [comment]
@vseager @jordeu `2525` should be available to you now, may I ask you to try again? If the issue is continuing, let us know and we'll reopen this issue.

**Comment by jordeu** [comment]
@kylos101 I can confirm that port 2525 is working again. But in fact we were using port 587 that it is still blocked. We've moved this test to use a local smtpd server, so it is not affecting us anymore. Thanks.

**Comment by kektuto** [comment]
Hello, I'm having the same issue as the outgoing mail on my local environment through 465, 587 and 25 is working but not inside the gitpod workspace. Is there a solution to it or is it still a bug?

**Comment by axonasif** [comment]
Hi @kektuto, we recommend performing such a workflow this outside of Gitpod workspaces.
