### ISSUE TITLE
Support opening Gitpod using HTTP Referrer

### ISSUE THREAD

**Issue by trieloff** [gitpod-io/gitpod#78]
For my example project (https://github.com/trieloff/helix-helpx/blob/master/README.md) I've added an "edit in gitpod.io" button to the `README.md`.

While it is nice to have, the URL right now is hardcoded:

```markdown
[![Gitpod](https://img.shields.io/badge/edit%20in-gitpod.io-blue.svg)](https://gitpod.io#https://github.com/trieloff/helix-helpx)
```

It would be great if I could just link to `https://gitpod.io/referrer` and GitPod would open the referring repository, so that the button could work across forks (and give you an easy way to ensure viral distribution)

**Comment by geropl** [comment]
That'd be a cool feature. We thought in the same direction but discovered that GitHub does not send URL paths but a plain `https://github.com` instead.

**Comment by trieloff** [comment]
Hm. Seems to be browser-dependent. I tried it in Safari (read Referrer using Javascript, not HTTP header) and got the full URL.

**Comment by svenefftinge** [comment]
> Hm. Seems to be browser-dependent. I tried it in Safari (read Referrer using Javascript, not HTTP header) and got the full URL.

Oh, that's cool. Let's re-check for firefox and chrome.

**Comment by geropl** [comment]
I did a quick test with a `README.md` on a GitHub repository and `console.log(document.referrer)` (Chromium and Firefox). Both returned `https://github.com/`, which is correct as `github.com` responds with the [Referrer-Policy](https://www.w3.org/TR/referrer-policy/#referrer-policies): `origin-when-cross-origin, strict-origin-when-cross-origin`.

**Comment by svenefftinge** [comment]
Closing this as we don't seem to get the needed information :(

**Comment by svenefftinge** [comment]
Good news! It seems like GH have changed the referrer-policy. See #688
