### ISSUE TITLE
How to add gitpod user to a supplementary group

### ISSUE THREAD

**Issue by gjsjohnmurray** [gitpod-io/gitpod#780]
I'm trying to gitpodify an image from Docker Hub. I made some progress, but when my workspace started up the gitpod user wasn't able to run some of the commands packaged in the image. I suspect I need to add the gitpod user to a specific group that's defined in the image.

I tried this in my dockerfile:
```
USER root
RUN useradd gitpod
RUN usermod -a -G gitpod irisusr
```
During workspace startup those commands seemed to succeed, but at step 9/12 I got this failure:
```
Error while adding Gitpod layer.Step 9/12

Error: Error while adding Gitpod layer.
```

Without my useradd and usermod there was no problem at step 9 and everything started up. But the gitpod user didn't belong to the required group, so the app environment doesn't work.

Please advise.

**Comment by geropl** [comment]
Hi @gjsjohnmurray,

the lines we use to setup the `gitpod` user are:

```
addgroup --gid 33333 gitpod
useradd --no-log-init --create-home --home-dir /home/gitpod --shell /bin/bash --uid 33333 --gid 33333 gitpod
```

Does that work for you?

Also, can you share more about your setup? We very rarely see people take this path and are always interested in feedback and learning more about the usecases. We experienced that existing docker images were often tied to a very specific usecase and would not fit for Gitpod/as dev environment.
Thanks!

**Comment by gjsjohnmurray** [comment]
@svenefftinge thanks for that info. Elsewhere I'm now trying to overcome the base image's default need for root access. I'll come back if there's more to share here. Closing this issue now.
