### ISSUE TITLE
[Team Plans] Clarify Add Members Dialog

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#7806]
We repeatedly get reports from confused users, who wanted to add members but interpreted the dialog to display the total amount of members.

<img width="528" alt="Screenshot 2022-01-25 at 10 47 39" src="https://user-images.githubusercontent.com/372735/150953258-3bdc271c-a81a-4f6d-ab02-aeb0dfe9ead4.png">

Although we are moving towards a [simplified design for team subscriptions](https://github.com/gitpod-io/gitpod/issues/7759), this happens often enough to be improved.

### Possible Solution

I think the big "total: xxx.xx EUR" below could be one cause of confusion.
Showing the total number like:
 `<current> + [DROP DOWN] = <total>  `
could help. 
@gtsiolis @jldec can you help? The solution should focus on changing the UI / messaging and be easy to implement.

**Comment by jldec** [comment]
I think all you need is wording changes 

![Screenshot 2022-01-25 at 11 49 43](https://user-images.githubusercontent.com/849592/150971882-1382bec6-7e21-4616-a505-077d2b9b2105.png)
