### ISSUE TITLE
why is it blocked

### ISSUE THREAD

**Issue by dt234** [gitpod-io/gitpod#781]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by meysholdt** [comment]
hi! You were involved in an incident related to sending spam from Gitpod. 

It's important to understand that Gitpod is for developing software: Read code, write code, run your code, test it, demo it to friends, colleagues and customers, etc. Sending spam from our platform is a violation of our [Terms of Services](https://www.gitpod.io/terms) and we can not allow it. See the "Fair Use" clause.

To continue the conversation please contact us via contact@gitpod.io. If you want to use Gitpod for software development I'm happy to unblock your account.
