### ISSUE TITLE
Gitbucket Support

### ISSUE THREAD

**Issue by Starkmann** [gitpod-io/gitpod#7814]
GitBucket is a Git web platform powered by Scala offering:

Easy installation
Intuitive UI
High extensibility by plugins
API compatibility with GitHub
https://github.com/gitbucket/gitbucket

I not sure if gitpod is the right place for this since it (api) should be compatible with github, but it leaks oauth support.

**Comment by katorly** [comment]
Then add [Gitee](https://gitee.com/language/en) too XD (just for kidding)   
(It's the biggest Git provider in China, used by millions of Chinese.)
