### ISSUE TITLE
Prebuilds marking as failed but seem to have succeeded

### ISSUE THREAD

**Issue by CarterQC** [gitpod-io/gitpod#7819]
### Bug description

I have a repo that runs webpack as it's last step in a prebuild. Every step succeeds, and the logs show `exit` at the end and a successful prebuild message, but the prebuild is marked as a failure in the dashboard.

Example log:
```
gitpod /workspace/myapp $ {
> asdf install && mix local.rebar --force && mix local.hex --force
> 
> } && {
> gp await-port 5432 && sleep 5 && psql --command "CREATE USER dbuser WITH SUPERUSER PASSWORD '1234';" > /dev/null 2>&1 && mix deps.get && mix ecto.setup && MIX_ENV=test mix compile && cd assets && npm install && node node_modules/webpack/bin/webpack.js --mode=development
> 
> }; exit
elixir 1.11.4-otp-23 is already installed
==> Checking whether specified erlang release exists...
==> Downloading 23.3.4.7 to /home/gitpod/.asdf/downloads/erlang/23.3.4.7/OTP-23.3.4.7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 62.0M  100 62.0M    0     0   107M      0 --:--:-- --:--:-- --:--:--  107M
==> Copying release into place

nodejs 14.17.6 is already installed
* creating /home/gitpod/.asdf/installs/elixir/1.11.4-otp-23/.mix/rebar
* creating /home/gitpod/.asdf/installs/elixir/1.11.4-otp-23/.mix/rebar3
* creating /home/gitpod/.asdf/installs/elixir/1.11.4-otp-23/.mix/archives/hex-1.0.1
Awaiting port 5432... ok
exit

🤙 This task ran as a workspace prebuild
🎉 Well done on saving 7 minutes
```

### Steps to reproduce

- Have a repo that runs `node node_modules/webpack/bin/webpack.js --mode=development` as the last step in init. 
- I have incremental prebuilds turned on too. 
- It seems like it might be waiting for some kind of signal from the webpack command that it's finished?
- It does seem that if I add another step after, like `echo "Init complete!"`, then it marks it as prebuilding successfully.

### Workspace affected

No, it was all for this project

### Expected behavior

I would expect it to show a successful prebuild.

### Example repository

I'm sorry, I can't give an example as it's a private work repository, but here are the .gitpod.yml steps:

```
- name: phoenix
    before: >
      asdf install &&
      mix local.rebar --force &&
      mix local.hex --force
    init: >
      gp await-port 5432 &&
      sleep 5 &&
      psql --command "CREATE USER dbuser WITH SUPERUSER PASSWORD '1234';" > /dev/null 2>&1 &&
      mix deps.get &&
      mix ecto.setup &&
      MIX_ENV=test mix compile &&
      cd assets &&
      npm install &&
      node node_modules/webpack/bin/webpack.js --mode=development
    command: >
      gp await-port 5432 &&
      cd $GITPOD_REPO_ROOT &&
      iex -S mix phx.server
```

### Anything else?

Not sure if this is an incremental prebuild issue.

**Comment by CarterQC** [comment]
Linking to #7812 as recommended by Pauline

**Comment by geropl** [comment]
@CarterQC Just found your issue. It looks like your last command `node node_modules/webpack/bin/webpack.js --mode=development` returns with an exit code other than `0` (cmp. [code](https://github.com/gitpod-io/gitpod/blob/d98d7abfe54fb28eff9bce805736c17642a56c01/components/supervisor/pkg/supervisor/supervisor.go#L299-L306)). This leads to the "failed" state. (that we report prebuild timings - and not mention the returnc code of your task - is bad UX here)

If you append another command - depending on how you do that - the end result might be return code `0`, effectively fixing the preuilds.

Could this explain your issue? Could you try to print the return code webpack returns?

**Comment by geropl** [comment]
Closing this because likely a configuration error (cmp. comment above).
