### ISSUE TITLE
regex support for environment variable scope

### ISSUE THREAD

**Issue by mike-seagull** [gitpod-io/gitpod#7822]
## Describe the behaviour you'd like
I would like to be able to specify a scope for an environment variable like this:

owner/prefix-*

where all repos for an owner that have the prefix will get access to the environment variable

## Describe alternatives you've considered
the only workaround currently is to give access using:

owner/*

but I don't want my secrets accessible in all my repos :(

**Comment by chuck-alt-delete** [comment]
- https://github.com/gitpod-io/gitpod/issues/6316

**Comment by axonasif** [comment]
Closing due to being duplicate.
