### ISSUE TITLE
Gitpod will not launch error 401.

### ISSUE THREAD

**Issue by Kittencode91** [gitpod-io/gitpod#7823]
### Bug description

I have tried to launch several of my workspaces but I keep getting a 401 Error. It states "preparing workspace", then goes on to say "This page isn’t working.
If the problem continues, contact the site owner.
HTTP ERROR 401". 

I have logged in again to both GitHub and GitPod. Please advise.

### Steps to reproduce

Click the "GitPod" button on a repository.

### Workspace affected

All of them

### Expected behavior

Gitpod should launch and present the saved files on the IDE.

### Example repository

![image](https://user-images.githubusercontent.com/62710872/151031902-f3130acd-5318-4ea0-8e1d-f337a3b62877.png)
![image](https://user-images.githubusercontent.com/62710872/151032022-09451c51-a255-46c6-8cae-963553629679.png)

### Anything else?

It always seems to be one bug or another with GitPod. I'm starting to see why people use TypeScript etc. Please advise ASAP as Ihave alot of projects to complete.

**Comment by gtsiolis** [comment]
Thanks for reporting this, @Kittencode91!

The team is already on it, feel free to track the following incident for more updates:
> https://www.gitpodstatus.com/incidents/tk0f7xcw8q94

**Comment by PaytonTheMartian** [comment]
Note, this is occurring in the Eastern US as well, no just the EU. Not sure if Gitpod is just making me use servers affected or all servers are.

**Comment by gtsiolis** [comment]
Hey everyone, re-posting the following update from the incident report[[1](https://www.gitpodstatus.com/incidents/tk0f7xcw8q94)]:
> We've created new clusters for both the EU and US regions, and are able to start workspaces.

Cc @PaytonTheMartian @Kittencode91

**Comment by gtsiolis** [comment]
Closing this as all systems are now fully operational. 📕
