### ISSUE TITLE
Automate builds of self-hosted Gitpod for preview environments 

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7824]
For validating features like self-hosted admin and auth integrations, it would be useful if developers could build and deploy dedicated preview environments with a self-hosted Gitpod installation, the same way we currently do for SaaS.

Maybe this could be controlled with a label or /command in the PR description, to override the default preview build and deployment.

**Typical use-case**  
- Create a PR with new self-hosted admin dashboard feature to configure auth integration.
- This triggers werft jobs to build and deploy a self-hosted instance in a preview environment.
- On commit, re-run the build and redeploy self-hosted to the same preview environment.

cc: @svenefftinge

**Comment by lucasvaltl** [comment]
Should be (indirectly) enabled via #7316.

**Comment by corneliusludmann** [comment]
[See also](https://www.notion.so/gitpod/Self-hosted-automated-nightly-test-pipelines-fdc5a202e67b4197aa00d93b98d57927 ) (internal)

**Comment by lucasvaltl** [comment]
Team platform is writing an RFC about this by end of this week. Then we can refine this ticket.
