### ISSUE TITLE
Dashboard and Alerts for CoreDNS

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7826]
## Is your feature request related to a problem? Please describe

We lack the ability to get insight to CoreDNS easily over time.
Also, CoreDNS has metrics that are visible now in Grafana, but we lack triggers to create alerts and warnings.

## Describe the behaviour you'd like

We currently use image `rancher/mirrored-coredns-coredns:1.8.4`.
Use a recent version of a community dashboard to gain insight to CoreDNS.
Options [[1](https://grafana.com/grafana/dashboards/12539)][[2](https://grafana.com/grafana/dashboards/7279)][[3](https://grafana.com/grafana/dashboards/5926)], ranked in order of most recent, to oldest.

## Describe alternatives you've considered

[Other options here.](https://grafana.com/grafana/dashboards/?search=CoreDNS)

## Additional context

This video shows how to take an community dashboard and Gitpodify it. Thanks, @ArthurSens !

https://www.loom.com/share/ca15ea6ab12c465f9a72ff75e8f80ad6

In addition to customizing a community dashboard, you'll also need to simulate DNS failures, to assert that the alerts and warnings you build are triggered accordingly.

**Comment by sagor999** [comment]
https://github.com/gitpod-io/observability/issues/75

**Comment by ArthurSens** [comment]
As a suggestion, kubernetes-mixin maintainer also has a [mixin for coreDNS](https://github.com/povilasv/coredns-mixin).

This can be imported to our jsonnet set up without much effort :)
