### ISSUE TITLE
Improve monitoring and feedback for errors during workspace cluster selection

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7829]
### Bug description

On start, some workspaces get stuck on "[Allocating resources (from Discord)](https://discord.com/channels/816244985187008514/839379835662368768/935668444924350475)".

[Another example from Twitter.](https://twitter.com/jahilliar/status/1486108607103991812?s=21)

### Steps to reproduce

Unconfirmed, but, try to start a workspace when prebuild load is very high.

### Workspace affected

vipertools-css-eamifbfe80m

### Expected behavior

It should start, instead of getting stuck.

### Example repository

n/a

### Anything else?

The issue occurred for some users on January 25 @ 10:52pm UTC.

**Comment by thisisommore** [comment]
I can confirm this, in my case every first workspace of the same context is stuck

**Comment by xLeighlightx** [comment]
Fuck off dude

**Comment by kylos101** [comment]
This may be an issue with `server` and the # of socket connections, and live on the WebApp side of the house. 

To start, let's gauge the frequency for this error by searching in the logs. Do the entries for the error line up with peeks in our volume? If yes, a simple mitigation may be to scale up server (+1 replica).

This may be difficult to recreate, but please try, and report the result here.

cc: @jldec @JanKoehnlein as a heads up. I am going to add this to your inbox as well, to get your thoughts.

**Comment by JanKoehnlein** [comment]
Thanks for the heads up. Let us know if you have a bit more information.

**Comment by princerachit** [comment]
I looked for the warning `"websocket in strange state"` but it seems to be [not too bad during that time](https://console.cloud.google.com/logs/query;query=%22websocket%20in%20strange%20state%22;timeRange=2022-01-25T10:18:21.569Z%2F2022-01-31T10:18:21.569Z;cursorTimestamp=2022-01-25T16:00:03.052Z?project=gitpod-191109).

**Comment by princerachit** [comment]
I cannot interpret anything in [the dashboard](https://grafana.gitpod.io/d/server/gitpod-component-server?orgId=1&from=1643141354222&to=1643328695720&var-cluster=prod-meta-eu01&var-node=All&var-pod=All&var-method=All&var-datasource=VictoriaMetrics&var-http_route=All) that can establish the relation bw server and the error.

**Comment by kylos101** [comment]
Hey @princerachit, @sagor999 and I observed this behavior yesterday while server event loop lag was high.

@geropl @JanKoehnlein can you think of a way for us to artificially cause server event loop lag to increase, so we can test this hypothesis?

**Comment by kylos101** [comment]
> Hey @princerachit, @sagor999 and I observed this behavior yesterday while server event loop lag was high.
> 
> @geropl @JanKoehnlein can you think of a way for us to artificially cause server event loop lag to increase (not in production), so we can test this hypothesis?

Another potential culprit is ws-manager-bridge, if you can think of a way to make it perform poorly, that would be an ideal scenario to see if it causes this condition to occur.

**Comment by geropl** [comment]
@kylos101 
Regarding reproducing event-loop lag high: No, I don't know of any way to do so, sorry. And it might be related to general slowness, but involvement in persistent problems (longer than 1-2s) is more unlikely.

> Another potential culprit is ws-manager-bridge

This, in turn, is very likely. First of all, you should see either a) high DB CPU usage, or b) high ws-manager-bridge CPU usage.
If both is not the case, you could also c) look for "deadlock" in the (ws-manager-)bridge logs.

Also, not sure how to reproduce it. If you want to do it artificially to inspect the effect on the system you could try insert a `await new Promise(resolve => setTimeout(resolve, 2000));` [here](https://github.com/gitpod-io/gitpod/blob/4a564067cdb53e60ac7b2a527304abba373d3280/components/ws-manager-bridge/src/bridge.ts#L113).

**Comment by geropl** [comment]
[This](https://github.com/gitpod-io/gitpod/issues/7829#issuecomment-1032433427) message from @princerachit looks interesting as well: 

> I see that usually when this error occurred it was preceeded by {"phase": "stopped", "message": "Workspace cannot be started: Error: no available workspace cluster to choose from!", "conditions": {"failed": "Error: no available workspace cluster to choose from!"}}

This could happen if workspaceClusters are not registered properly (for whatever reason, cannot imagine one :shrug: ).

**Comment by kylos101** [comment]
Hi @JanKoehnlein and @jldec :wave: , #8173 was [closed in favor](https://github.com/gitpod-io/gitpod/issues/8173#issuecomment-1041285181) of this issue. I wanted to give you a heads up, because, I know you had #8173 scheduled - and might be wondering what happened. :smile: 

Also, @csweichel shared some feedback, for [related metrics on the WebApp side, which could help with alerting](https://github.com/gitpod-io/gitpod/issues/8173#issuecomment-1038981983).

CC: @princerachit

**Comment by geropl** [comment]
@JanKoehnlein IMO it make sense to schedule this, and add metric for and alert on the scheduling success rate

**Comment by kylos101** [comment]
Hey @JanKoehnlein @geropl and @jldec :wave: ,

I spent some time researching this issue today for workspace `shaal-drupalpod-wp2k1qd0khc` and [this report in Discord](https://discord.com/channels/816244985187008514/939715845934968864/939716765838106694).

May I ask you to review and let us know if there's anything else we can do to help?

1. [This log from the gitpod project indicates `server` tried starting the workspace instance ID, but could not find a workspace-cluster.](https://cloudlogging.app.goo.gl/JybNQtGHghjQUSRn6) 
   * It seems like server tried starting one time.
   * Would it make sense to exponential back-off for up to 3-5 minutes? :thinking: Perhaps even sharing the attempt with the user?
   * [Related traces.](https://ui.honeycomb.io/gitpod/datasets/gitpod-production/result/2tbiGaFvJM9?tab=raw) It doesn't look like this instance ever actually made it to a workspace cluster.
2. [I found zero entries for this workspace instance ID, but was able to find owner IDs in the workspace-clusters project at this same timeframe.](https://cloudlogging.app.goo.gl/D2smFermqF27j5hi6) So this tells us they were able to run other workspaces, just not this one.
3. While doing this research, I realized it is hard for us to compare startWorkspace requests with web app, and we don't log them (unless debug is enabled), [so I made this issue to help](https://github.com/gitpod-io/gitpod/issues/8449).

CC: @aledbf @sagor999

**Comment by geropl** [comment]
@kylos101 Thx for the analysis, and I :100:% agree.

> Would it make sense to exponential back-off for up to 3-5 minutes

I think we should re-try, but not over such a long time period, but more in the order of a couple of seconds. Longer outages like [this one](https://cloudlogging.app.goo.gl/JrW4893xPRUMZnR69) should escalate instead, triggered by metrics and alerts.

To users, if the re-try fails as well because of "no cluster available", we should present a message that explains:
 - 1.) this is a temporary issue
 - 2.) we're already aware (due to alerts).

IMO the best way to transport this message is to update `WorkspaceInstance` and set a special `condition` `startFailed`. :+1: 

Suggestions for metrics names:
 - `gitpod_server_start_workspace_total_success`
 - `gitpod_server_start_workspace_total_retries`
 - `gitpod_server_start_workspace_total_failure`

**Comment by eliezedeck** [comment]
I'm still getting this issue right now: `https://eliezedeck-workspace-yb0kjyp3sio.ws-eu67.gitpod.io/`

You should be able to see the actual project on your end. But currently, I consistently get stuck at **"Allocation resources ..."**

**Comment by pawlean** [comment]
Hey @eliezedeck! I saw your message on Discord and wanted to close this loop 🔁 Everything should be good again, but let us know if you see any other issues.
