### ISSUE TITLE
My workspace is very slow and has a high load average

### ISSUE THREAD

**Issue by isontheline** [gitpod-io/gitpod#783]
**Describe the bug**
Dear Gitpod team, my workspace e892babb-xxxx-xxxx-xxxx-85e3e8236aeb is blocked in "stopping" state and I can't start it again (I have unpushed changes :(
I was developing and the workspace has been slow a few minutes before the block.

**To Reproduce**
- Start the workspace
- Develop as usual

**Expected behavior**
Developing all the night :)

**Comment by isontheline** [comment]
The workspace is now stopped :)
When live again I was able to push my commits :)

The workspace is so slow however...

**Comment by jankeromnes** [comment]
Hi @isontheline! So sorry that your workspace was blocked in "stopping" state, and that it was slow. :(

Please re-open this issue if a workspace is blocked or slow again, there may be an underlying problem we need to fix.

@geropl could this somehow be related to our recent workspace manager changes?

**Comment by isontheline** [comment]
@jankeromnes It's difficult to work this night again :(

Check the load average linked to this picture :

![uptime](https://user-images.githubusercontent.com/44212923/64725911-d51bc400-d4d5-11e9-9760-c0b72e1f0576.png)

Sometimes load can grow up to 20-24

I'm here if you want I launch any tests on my workspace/container

**Comment by isontheline** [comment]
Load is stabilized on average 1.5-2.3, so it's usable right now :)

**Comment by isontheline** [comment]
I think the fix of #789 have now resolved my issue too
The last 20 days my workspace loaded in 5 minutes (yes 5) and now it's less than 20 seconds.

Thank you Gitpod Team !

**Comment by isontheline** [comment]
Hello folks,

Problem is here again since several weeks :
![solong2](https://user-images.githubusercontent.com/44212923/70656380-48aaaa00-1c5a-11ea-87e6-ecf87f6ad47f.png)

Launching my maven project (17 seconds before) take 4 to 6 minutes... I can't develop anymore on Gitpod (paid user) :(

**Comment by jankeromnes** [comment]
Note for posterity: this happened again yesterday because of some crypto-miners we caught. (#993)
