### ISSUE TITLE
Workspace pods stuck in Terminating when they could not get scheduled

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#7836]
### Bug description

While investigating problems with Gitpod's staging deployments, @geropl found the following problem:

A workspace pod could not get scheduled for some reason, and eventually became "stuck in Terminating" (for over an hour) when it got deleted per timeout.

Our suspicion is that the pod finalizer is waiting for a backup to be made, but no `ws-daemon` feels responsible for doing a backup, since the pod could not get scheduled in the first place.

We noticed this with imagebuilds, prebuild as well as regular workspaces.

### Steps to reproduce

1. Start a workspace pod that cannot get scheduled
2. It remains stuck in Terminating for more than an hour

**Comment by aledbf** [comment]
> Our suspicion is that the pod finalizer is waiting for a backup to be made, but no ws-daemon feels responsible for doing a backup, since the pod could not get scheduled in the first place.

Only the `ws-daemon` running in the same node as the workspace can do the backup. Did you check the logs?

**Comment by geropl** [comment]
> Only the ws-daemon running in the same node as the workspace can do the backup. Did you check the logs?

Yes. But for pods that never reached "running" but were stuck in "pending" we should shortcut the finalizer somehow.

> Did you check the logs?

Unfortunately not. You should be able to reproduce by adding a random static label in `create.go` that is not present on core-dev, which provokes this situation.

**Comment by geropl** [comment]
It seems that even if we manually remove these pods, no `stopped` events are ever emitted by `ws-manager` :thinking: Not sure this is expected, though.

**Comment by sagor999** [comment]
I cannot reproduce this anymore. I think we fixed this when we were fixing an issue with OutOfMemory error.
Now when pod cannot be scheduled, ws-manager will delete it and try again. 
I did notice a different type of error though:
workspace keep cycling from Stopped to Pending and back. 
I think server keeps on trying to start it and there is no circuit breaker?
@geropl @jankeromnes 
(to repro add a non existent node node selector in create.go)
(I will remove this from workspace and assign to webapp team instead)

**Comment by geropl** [comment]
> I cannot reproduce this anymore. I think we fixed this when we were fixing an issue with OutOfMemory error.

That's my line of thinking as well.

> I did notice a different type of error though:
> workspace keep cycling from Stopped to Pending and back.

Yes, there was an regression introduced ~1,5-2 weeks ago that made this possible again. IDE has an issue for it, but can't find now, will link tomorrow.

Let's close this issue, as the original issue is fixed by now.

One question:
> Now when pod cannot be scheduled, ws-manager will delete it and try again.
Do you ensure somehow that we're not moving back and forth through ws lifecycle stages? :thinking:
