### ISSUE TITLE
not able to start workspace

### ISSUE THREAD

**Issue by sukhifive5** [gitpod-io/gitpod#784]
**Describe the bug**

OutOfmemory: Pod Node didn't have enough resource: memory, requested: 3543138304, used: 54141124608, capacity: 57633726464

**To Reproduce**

start project from workspace.  i believe it is due that i added prettier vs extension.   once i take it out it start fine.  however i have some not committed code that i need to get out this workspace.   i added this extension few weeks back and not issue till today.
**Expected behavior**

start workspace

**Comment by geropl** [comment]
Hi @sukhifive5,

thank you for reporting this. We deployed new functionality that did not work as intended under pressure. We disabled it for now and are working on a fix.

You should be able to start your old workspace as expected. Sorry for the inconvenience!

**Comment by sukhifive5** [comment]
thanks
