### ISSUE TITLE
eu29 not registered in US database

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#7846]
This leads to workspaces time out if:
 - the workspaces runs in EU
 - the browser clients is connected to US

Happened to @iQQBot 

InstanceId: 93b8730c-08e5-47cb-9dd0-9c1902340f54
Example trace missing the `wsManager.setActive` call: https://ui.honeycomb.io/gitpod/datasets/gitpod-production/result/4WGKQNHyK7T/trace/2WKkyEZ4zQs?span=missing%20root

List of workspace clusters in US DB missing the `eu29` entry:
![image](https://user-images.githubusercontent.com/32448529/151200689-dae10d9c-40a1-49e3-8810-d98366bb9ff4.png)

/cc @akosyakov

**Comment by aledbf** [comment]
Closing. Fixed using `gpctl`
