### ISSUE TITLE
Some gp-cli commands do not integration/work with JetBrains IDE

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#7848]
### Bug description

Commands like `gp open <file_name>`, `code ./`, `open ./` not work with JetBrains Gateway, stuck, no return

### Steps to reproduce

1. Open a workspace with JetBrains IDE
2. Execute command mentioned above

### Expected behavior

Work or return some error

**Comment by akosyakov** [comment]
It has to be done to enable https://github.com/gitpod-io/gitpod/issues/7980
