### ISSUE TITLE
Web Debugger

### ISSUE THREAD

**Issue by DavidGriswoldTeacher** [gitpod-io/gitpod#785]
If Gitpod could enable its debugger to talk to the local server previe in the same way I can use the Chrome Debugger extension in VS Code, it would be game changing. I imagine this would be herculean task, but it would be so cool.

**Comment by jankeromnes** [comment]
Interesting idea! Thanks for suggesting it. 💯 

Have you tried to install the Chrome Debugger extension [in Gitpod](https://www.gitpod.io/docs/vscode-extensions/)? If that doesn't work, please file a bug against [Theia](https://github.com/theia-ide/theia/issues/new), specifying which extension you tried to install, and what problems/bugs you encountered.

With a bit of luck, getting it work might turn out less herculean than expected. 😄

**Comment by svenefftinge** [comment]
The issue is that we don't have access to the local chrome process from within Gitpod. 
So we would need to route the debug protocol somehow.
I know that, for instance, Arduino does that by launching a small proxy locally that the website can connect to through a websocket.

**Comment by svenefftinge** [comment]
That sounds like a pretty good idea.
