### ISSUE TITLE
Cannot create Pull Requests without giving GitPod user-level permissions

### ISSUE THREAD

**Issue by mortenson** [gitpod-io/gitpod#7850]
### Bug description

I used to be able to create pull requests by only granting Gitpod access to specific repositories. This was nice because otherwise I would have to grant Gitpod permissions on my account which is less secure in general.

### Steps to reproduce

1. Only give Gitpod the "user:email" permission at https://gitpod.io/integrations
2. Connect a new repository at https://github.com/settings/installations/<your gitpod installtion>
3. Add the new repository as a project at https://gitpod.io/projects
4. Launch a new workspace of the default branch (ex: master)
5. Make code changes
6. Attempt to create a pull request in VSCode
7. See a permission error requesting user-level permissions

Screenshots of installation page and error:
![gitpod-access](https://user-images.githubusercontent.com/2091002/151213365-e9b062ec-adbb-4af9-8f69-33a40a39c450.PNG)
![pr-access-error](https://user-images.githubusercontent.com/2091002/151213370-97670936-518e-4b80-8f13-6aff6af69dac.PNG)

### Workspace affected

mortenson-tomeprojecttes-tuciot1wkbe

### Expected behavior

I can use Gitpod while only granting repository level permissions.

### Example repository

Here's my repository: https://github.com/mortenson/tome-project-test

**Comment by akosyakov** [comment]
We rely on this extension for reviews right now: https://github.com/Microsoft/vscode-pull-request-github
And they response was: https://github.com/microsoft/vscode-pull-request-github/issues/2555#issuecomment-974204632

Please feel free to create a new issue there.

**Comment by mortenson** [comment]
@akosyakov Thanks for responding - I think that issue is different right? This was working for me just earlier this month, the issue isn't when the notification is shown it's that I can't make pull requests without giving Gitpod full access to my account. Giving it the repository access in my screenshot above should (and was) enough previously.

**Comment by mortenson** [comment]
@akosyakov Maybe a better way to phrase this is:

1. Can you use Gitpod to create pull requests repositories without granting the "repo/public_repo" permissions? In other words, can you only grant Gitpod write access to a single repository?
2. If so, how do you do this?

**Comment by akosyakov** [comment]
I’m not sure what you mean by can we create a PR. We don’t implement such functionality but only install referenced extensions. This extensions calls us to ask for a token with given scopes. And as far as i know this extension wants repo scope and cannot work without it. An issue which I filed was about removing such requirement.

**Comment by mortenson** [comment]
Thanks again @akosyakov - I must have been mistaken that I was able to do this earlier this month.
