### ISSUE TITLE
[installer] Disabling components does not remove corresponding deployments and pods or resources

### ISSUE THREAD

**Issue by yevon** [gitpod-io/gitpod#7853]
### Bug description

When you disable a component, for example migrating it to an external one, the installer does not uninstall already deployed resources on the cluster.

### Steps to reproduce

Disable a component in the config and apply the installer again.

### Expected behavior

It should remove all related resources when disabling a component.

**Comment by corneliusludmann** [comment]
Solved with KOTS (Replicated) as recommended installation method.
