### ISSUE TITLE
Audit usage of gpctl clusters and related sub-commands

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7858]
`gpctl` talks with `ws-manager-bridge`. 

To audit usage, we'd put an interceptor onto `ws-manager-bridge`, and log the related events.

This way (1) it becomes visible in logs and (2) it's tamper proof (not in a database).

**Comment by utam0k** [comment]
@kylos101 Could you tell me if I'm understanding this correctly? Is this issue about making it possible to check the grpc request events from ws-manager-bridge to ws-manager with the `gpctl` command?

**Comment by sagor999** [comment]
@utam0k not quite. What Kyle wants is every time there is any change done via `gpctl` that we would log that in `ws-manager-bridge` (maybe like this: `gpctl audit: <cluster> <what was changed>`). That way we can go into log viewer in gcp and check if there were any changes done.

**Comment by utam0k** [comment]
@sagor999 Oh I see, thank you very much 🙏   However, I have removed myself from the assignee because I got an issue to focus on.

**Comment by princerachit** [comment]
We use [grpc-js](https://www.npmjs.com/package/@grpc/grpc-js) library for the GRPC server in ws-manager-bridge, it does not support server interceptors. I am evaluating other option to add logging on each request that the server receives.
