### ISSUE TITLE
Add number of users to the telemetry data

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#7866]
Currently, [the telemetry](https://github.com/gitpod-io/gitpod/blob/main/components/installation-telemetry/cmd/send.go#L53) only provides a randomly generated unique ID and the version number.

To this, we should add the number of registered users. The Segment data should be named something like `totalUsers` so we can expand this to include active/inactive users in the future

This will likely need some liaison from @gitpod-io/engineering-webapp to understand how best to get the total number of users from the database

**Comment by JanKoehnlein** [comment]
This is what we do in the server: https://github.com/gitpod-io/gitpod/blob/fa62003417248d638df419b90e35847b037e56f9/components/server/ee/src/user/user-service.ts#L44-L45
