### ISSUE TITLE
Save Color Theme as Light

### ISSUE THREAD

**Issue by wadeziegler** [gitpod-io/gitpod#787]
**Describe the bug**

Change Color Theme to Light does not save anywhere that can be checked into Git. So, Gitpod always reverts to the default dark theme. 

**To Reproduce**

1. Open File -> Settings -> Change Color Theme
2. Select Light Theme
3. Stop and open a new Gitpod instance
4. Theme is dark again

**Expected behavior**

I would expect some way to set the default theme even when a new docker instance is started. I tried using the the Theia settings in package.json referenced by this PR, but it did not work.

https://github.com/eclipse-theia/theia/pull/2442

**Comment by JesterOrNot** [comment]
Hey have we considered localstorage for this?

**Comment by JesterOrNot** [comment]
or better yet something in the .gitpod.yml file
maybe a section for it
```yaml
theming:
    - editor-theme: light 
```
that way it also paves the way for future customization!

**Comment by svenefftinge** [comment]
Theming is a user-specific setting not workspace specific so putting it into the .gitpod.yml would be the wrong place. But I have good news, as we are going to roll this out next week.

**Comment by JesterOrNot** [comment]
Awesome!

**Comment by laike9m** [comment]
Hi Sven, may I ask what is the correct way to configure (and share) theme as of now?
