### ISSUE TITLE
MacOS GitPod Local Companion gives problem

### ISSUE THREAD

**Issue by hrishirc** [gitpod-io/gitpod#7875]
### Bug description

INFO[0000] writing workspace ssh_config file             ssh_config=/tmp/gitpod_ssh_config
INFO[0032] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0032] failed to connect, trying again in 2 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"
INFO[0036] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0036] failed to connect, trying again in 3 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"
INFO[0041] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0041] failed to connect, trying again in 4 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"
INFO[0047] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0047] failed to connect, trying again in 6 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"
INFO[0056] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0056] failed to connect, trying again in 10 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"
INFO[0068] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0068] failed to connect, trying again in 15 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"
INFO[0085] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0085] failed to connect, trying again in 22 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"
INFO[0110] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0110] failed to connect, trying again in 30 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"
INFO[0142] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0142] failed to connect, trying again in 30 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"
INFO[0174] websocket handshake                           url="wss://gitpod.io/api/v1"
ERRO[0174] failed to connect, trying again in 30 seconds...  badHandshakeCount=0/15 error="dial tcp: i/o timeout" statusCode=0 url="wss://gitpod.io/api/v1"

### Steps to reproduce

Try working on GitPod Local Companion on Mac

### Workspace affected

MacOS

**Comment by akosyakov** [comment]
It sounds like gitpod.io cannot be reached from your network? Can you ping it?

**Comment by hrishirc** [comment]
it is reachable... it's my local machine... just tried now...

deleted the autos and tried again as well... some firewall issue, but how do I debug further. Tried the macOS logs as well, couldn't find anything...

**Comment by hrishirc** [comment]
also the dynamically generated SSH configs, can't I generate them myself and use them?

also does Gitpod have a restriction that it allows only http connections? 

installed a VNC server on the pod, but at a loss as to how to reach it....

I'll tell you what I'm trying. I'm installing an IntelliJ IDEA CE on the pod and then VNCing to the machine....

**Comment by hrishirc** [comment]
If this is successful, I'll convert everyone in my company to Gitpod
