### ISSUE TITLE
Oh, no! Something went wrong! OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2576980378, used: 65006469130, capacity: 66388508672

### ISSUE THREAD

**Issue by dkelly255** [gitpod-io/gitpod#7877]
### Bug description

Oh, no! Something went wrong!
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2576980378, used: 65006469130, capacity: 66388508672

### Steps to reproduce

Attempting to launch my existing Gitpod workspace.

### Expected behavior

Have my existing Gitpod workspace launch without any errors.

### Anything else?

repository link & name - https://dkelly255-4antasyootball-x5dfnf9rm5f.ws-eu29.gitpod.io/

**Comment by svenefftinge** [comment]
Removing priority as I see you were able to start the workspace again. Please confirm.

**Comment by dkelly255** [comment]
Hi Sven, thanks yes I was able to start the workspace again
