### ISSUE TITLE
Remove the sidebar menu and use the tabs for the admin dashboard

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7879]
### Problem to solve

Given the recent additions of the settings (https://github.com/gitpod-io/gitpod/pull/7732) and upcoming addition of projects (https://github.com/gitpod-io/gitpod/issues/7636) in the admin dashboard, now that we have tabs, which were not preset during the initial dashboard redesign, long-term we'd like to use the tabs and replace the pills we currently have in the admin dashboard as this pattern fits and scales better for this need.

### Proposal

Remove the sidebar (pills) menu and use the navigation at the top (tabs) for the admin dashboard navigation. Preferrably, re-using the order from teams: _Users_, _Workspaces_, _Projects_, _Settings_.

This will also match the pattern used for surfacing workspaces, projects, and settings for personal accounts and teams.

Cc @jldec based on our [discussion](https://www.notion.so/gitpod/WebApp-Design-Sync-8c61b5f0cd2840e394fbe15f8f25099d) (internal) earlier today and https://github.com/gitpod-io/gitpod/issues/7597.

See also [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1643298717497700?thread_ts=1643283947.483100&cid=C02EN94AEPL) (internal). Cc @laushinka 

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="Screenshot 2022-06-28 at 5 52 19 PM (2)" src="https://user-images.githubusercontent.com/120486/176211141-115726e7-bd9d-41be-97c5-28681d9b6812.png"> | <img width="1440" alt="Screenshot 2022-06-28 at 5 54 15 PM (2)" src="https://user-images.githubusercontent.com/120486/176211196-b72e221e-5a4f-407e-90ac-f545c557ce75.png"> |

See [design specs](https://www.figma.com/file/4zbw802MFwPUyHxAM8m27B/Remove-the-sidebar-menu-and-use-the-tabs-for-the-admin-dashboard-%237879?node-id=0%3A1).

**Comment by SangameshItagi** [comment]
@gtsiolis Will work in this issue.

**Comment by gtsiolis** [comment]
Closing this in favor of https://github.com/gitpod-io/gitpod/issues/8385.

**Comment by gtsiolis** [comment]
Let's reopen this as a follow-up issue and leftover from #8385. 

This still needs some UX input before picking up, as admin pages may look visually unbalanced after removing the sidebar. Alternatively, we could decide to leave the sidebar as is and instead improve the admin pages.

**Comment by gtsiolis** [comment]
Resolved in https://github.com/gitpod-io/gitpod/pull/16307. Thanks, @Devansu-Yadav!
