### ISSUE TITLE
[telemetry] Document how telemetry works and what data is sent

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#7890]
Self-hosted installations ping Gitpod every night and sent an anonymous, random generated installation ID as well as the installed Gitpod version. In the future, we will most probably add additional data. We will always send anonymous data only.

Telemetry can be disabled in the admin settings.

You can see which data has been sent in the logs of the telemetry cronjob: `kubectl logs gitpod-telemetry-<id>`

We should add a page to our docs that documents this.

**Comment by gtsiolis** [comment]
See also https://github.com/gitpod-io/gitpod/issues/7820 and https://github.com/gitpod-io/gitpod/pull/7732#discussion_r791722700 in case these are related or duplicates. 🏓

**Comment by corneliusludmann** [comment]
Fixed by https://github.com/gitpod-io/website/pull/1942
