### ISSUE TITLE
Switch CNI from Calico to Cilium

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#7902]
## Is your feature request related to a problem? Please describe

Currently we are using Calico for CNI. 
I propose switch to Cilium for following reasons:
1. eBPF routing (they are leading that space currently). Calico also has eBPF mode though, but I did have issues with it in the past. eBPF routing is much faster, skips kube-proxy completely, and also bypasses conntrack. 
2. Hubble for network observability is great and a real life saver for debugging networking issues.
3. NetworkPolicyEditor (can be used without cilium though). Even though we don't use NetworkPolicy currently, we might in the future.

## Describe alternatives you've considered

We could stay with Calico and instead use their eBPF implementation.

**Comment by sagor999** [comment]
cc @aledbf (i did not find existing issue for this)

**Comment by kylos101** [comment]
@sagor999 we have some [existing NetworkPolicy](https://github.com/gitpod-io/gitpod/blob/main/installer/pkg/components/workspace/networkpolicy.go), is this what you were referring to in point 3, or do you mean something else?

**Comment by sagor999** [comment]
yeah.

**Comment by sagor999** [comment]
not stale.

**Comment by sagor999** [comment]
@aledbf FYI ^

**Comment by aledbf** [comment]
@scasei yes, the portmap CNI plugin is not enabled by default because it depends if you are using the eBPF-based kube-proxy replacement or not.

**Comment by scasei** [comment]
And I'm having more trouble with network policies. Than disabled this feature for cilium [1] and deleted most of them in gitpod namespace, but no real success.
Because also the pods have problems with readiness / liveness probes and timeouts only 1 sec. 
Here is already a patch around, does it fix that and do I have any chance to use that without compiling the distribution?
[1] https://docs.cilium.io/en/stable/policy/intro/#rule-basics

**Comment by scasei** [comment]
And last question. :)
From my registry-facade logs, is that CNI related or can I ignore?
`registry-facade {"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"lookup eu.gcr.io on 10.96.0.10:53: dial udp 10.96.0.10:53: i/o timeout","host":"eu.gcr.io","level":"error","message":"NetworkIsReachableProbe: unexpected error resolving host","serviceContext":{"service":"registry-facade","version":"commit-1f43c3588823dfe79a3b49dc9623a687a0da17dd"},"severity":"ERROR","time":"2022-05-24T18:56:31Z"} `

**Comment by aledbf** [comment]
> From my registry-facade logs, is that CNI related or can I ignore?

That's a CNI issue. Please check the coredns pod is running and can resolve queries 
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by scasei** [comment]
Tried with `nslookup eu.gcr.io 10.96.0.10` on registry-facade pod shell, with out problems:
```

bash-5.1$ nslookup eu.gcr.io 10.96.0.10
Server:         10.96.0.10
Address:        10.96.0.10:53

eu.gcr.io       canonical name = googlecode.l.googleusercontent.com
Name:   googlecode.l.googleusercontent.com
Address: 2a00:1450:400c:c04::52

eu.gcr.io       canonical name = googlecode.l.googleusercontent.com
Name:   googlecode.l.googleusercontent.com
Address: 66.102.1.82

```

**Comment by scasei** [comment]
Switched to calico [1], redeployed, same problem: 

`registry-facade {"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"lookup eu.gcr.io on 10.96.0.10:53: dial udp 10.96.0.10:53: i/o timeout","host":"eu.gcr.io","level":"error","message":"NetworkIsReachableProbe: unexpected error resolving host","serviceContext":{"service":"registry-facade","version":"commit-1f43c3588823dfe79a3b49dc9623a687a0da17dd"},"severity":"ERROR","time":"2022-05-24T18:56:31Z"} `

[1] https://projectcalico.docs.tigera.io/getting-started/kubernetes/helm

**Comment by aledbf** [comment]
Closing. Moving the issue to the ops repository.

**Comment by aledbf** [comment]
@scasei please reach the Cilium support channels. The issue you are having is not related to Gitpod itself and unfortunately, we cannot help you configure/troubleshoot the CNI provider.
