### ISSUE TITLE
Local VSCode Desktop extensions have to be installed manually (Install in SSH) on workspace open

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#7906]
### Bug description

When you have local VSCode extensions installed, and you open a Gitpod workspace locally.
You'll get this action button next to some extensions (e.g. Composer, Gitlens, etc)
`Install in SSH: <name_of_workspace>`
Clicking on that button works as expected.
But it's very annoying that the on every new Gitpod workspace I open locally, I have to repeat the whole process on dozens of extensions.

![image](https://user-images.githubusercontent.com/22901/151615720-90ab0d64-a92b-41b3-bd8d-0469cc668047.png)

cc: @JSchreff

### Steps to reproduce

1. Install `Gitlens` VSCode extension locally on your computer.
1. Open any Gitpod workspace, and choose to open it locally in VSCode
1. Under `Extensions` -> `Local - Installed` section, find `Gitlens` extension.
1. Click on the button `Install in SSH: <name_of_workspace>`
1. Close this workspace and open a new workspace.
1. Repeat all the steps above, you'll see that you have to reinstall `Gitlens` extension again.

### Expected behavior

Similar to how Gitpod 'remembers' the VSCode extensions I like to use when I open a workspace in the browser, I'd like it to rememebr and carry over all my installed extensions when I work locally on my computer.

**Comment by sagor999** [comment]
Does it happen to all of your local extensions?
I have a feeling this is due to extension wanting to run on the host itself, hence a prompt to install it on the host via ssh.

**Comment by mustard-mh** [comment]
You can add these extension to .gitpod.yaml then they will automatic install

**Comment by axonasif** [comment]
@shaal do you have this button?
<img width="760" alt="Screenshot 2022-01-30 at 6 12 41 PM" src="https://user-images.githubusercontent.com/39482679/151699256-bfef1225-933d-4674-95aa-19faaeda0e73.png">

Other than that, what @mustard-mh said is correct, you can list your extensions in `.gitpod.yml` since `remote.SSH.defaultExtensions`[^1] vscode-settings gets automatically set to `gitpod.gitpod-remote-ssh`.

[^1]: https://code.visualstudio.com/docs/remote/ssh#_always-installed-extensions

**Comment by shaal** [comment]
@axonasif @mustard-mh thank you, but I think it's missing the point of this bug/feature request, what you suggested is a workaround and not solving the actual problem.

Gitpod is a service that improves developer experience. 
When working on Gitpod workspaces (without any special setup (ie. dotfiles), every extension I add will be installed for me the new workspace I open, without updating `.gitpod.yml` file.
It's nice because I don't need to remember to do it, it just "does it for me", it improves the developer experience by providing a workflow automate some of the things without requiring additional manual steps.

That behavior is different when opening a workspace in a local VSCode, because all of a sudden, my favorite VSCode extension do not "carry over" to the project that runs on Gitpod workspace.
The desired developer experience would be that when I work locally, my favorite VSCode extensions are available.
In the current state, I have 20 VSCode extensions on my local that I have to manually click to install each and every time I open a Gitpod workspace.

**Comment by axonasif** [comment]
> @shaal: thank you, but I think it's missing the point of this bug/feature request, what you suggested is a workaround and not solving the actual problem.

Yeah, that's true, if it was then we'd be already closing the issue you know.
Perhaps all we can do is wait for this to become a reality in the future when one of our engineers pick up this issue for making this process convenient 😄

**Comment by sagor999** [comment]
@akosyakov is that something that can be added? or not possible? 
maybe via local companion app that can detect those extensions and send an event to install them on remote?

**Comment by akosyakov** [comment]
What is wrong with `remote.SSH.defaultExtensions` ? We do change it to add one extension, but if you have others there they should be installed in each remote machine regardless whether it is Gitpod container or not.

**Comment by akosyakov** [comment]
There is also a command `Install local extension on remote` where you can check box all extensions. We could consider to add an option to run this command programatically.

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/gitpod/issues/9136

**Comment by loujaybee** [comment]
@shaal - Have you tried the recently introduced settings sync: https://www.gitpod.io/changelog/vs-code-desktop-settings-sync - I think that + the gitpod.yml definitions should cover your needs? Can you give it a try, if you're still having issues, feel free to re-open! 🙏

**Comment by shaal** [comment]
@loujaybee I enabled VSCode sync (and restarted VSCode).

When I open Gitpod workspace in a local VSCode, it's not that VSCode is not aware of the extension I wanted installed (in my example - CoPilot, and Gitlens). It's that there's an additional manual step, every time I open a workspace.
![image](https://user-images.githubusercontent.com/22901/170545868-fee5d267-9031-4ec2-9e54-a8b61c224fbe.png)
![image](https://user-images.githubusercontent.com/22901/170546092-7e88063d-8dfb-43cb-b7c7-070f557e67cb.png)
I have to click the button `Install in SSH`, for each and every extension that has that requirement.

**Comment by loujaybee** [comment]
Related VS Code issue: 
- https://github.com/microsoft/vscode/issues/136424

**Comment by shaal** [comment]
@loujaybee just to confirm, I am still seeing this issue.

**Comment by akosyakov** [comment]
I think we should fetch setting sync endpoint and install extensions from there automatically and then nudge people to configure Setting Sync with Gitpod. I am not sure we can access extension which are not installed from VS Code Desktop core. cc @jeanp413

**Comment by akosyakov** [comment]
@jeanp413 Could you link a corresponding PR please?

**Comment by jeanp413** [comment]
Here's the PR https://github.com/gitpod-io/gitpod-vscode-desktop/pull/16

**Comment by jeanp413** [comment]
Released a new pre-release version gitpod.gitpod-desktop `v0.1.2022082421`, you can update `gitpod.remote.syncExtensions` in your settings.json to disable it

**Comment by akosyakov** [comment]
@shaal Could you give it a try in VS Code insiders?

**Comment by akosyakov** [comment]
@jeanp413 I tried in VS Code Insiders and it did not work for me, see [internal](https://gitpod.slack.com/archives/C01KGM9BH54/p1661420389114129?thread_ts=1661336917.005249&cid=C01KGM9BH54)

Please also change notification to `Could not install local extensions, please enable Settings Sync with Gitpod. `. I don't think anyone understands `user sync extensions`.

**Comment by shaal** [comment]
I tried it with VS Code Insiders. I opened a repo with the online IDE (VSCode insiders), then click on the menu, to open the Desktop version of VSCode Insiders.
I still see the `Install in SSH` message
![image](https://user-images.githubusercontent.com/22901/187243145-fb1a06da-01c1-4aa6-960b-c8fb795dddd2.png)

**Comment by jeanp413** [comment]
@shaal did you enable settings sync with gitpod? 
![image](https://user-images.githubusercontent.com/25115070/187254356-df8e3fa2-6ae8-4d03-a843-e73fb892d1b6.png)

**Comment by shaal** [comment]
@jeanp413 I found out what was missing.
I had to open Gitpod's VSCode extension, and choose "use pre-release".
Now it's installing my extensions!

**Comment by loujaybee** [comment]
Deployed currently in pre-release, we need to move this now to an experimental rollout: 

1. Setup for a phased release and rollout
2. Add analytics to track success during rollout

**Comment by loujaybee** [comment]
The [changelog is updated with documentation](https://www.gitpod.io/changelog#sync-local-vs-code-extensions). 

Will start to begin phased release to users.

**Comment by loujaybee** [comment]
Currently on hold as we're reviewing the data, and it seems that some users are not able to enable properly. 

It's possible to enable manually, but we won't yet roll out to all users.

**Comment by jeanp413** [comment]
Let's just leave it as an opt in setting and remove the cofig cat key, also update docs.

**Comment by shaal** [comment]
@loujaybee This problem still exists when running VSCode on Windows.
![image](https://user-images.githubusercontent.com/22901/211397858-8d4a6ac8-b7e1-4fde-9bad-6a6048c79f7a.png)

**Comment by axonasif** [comment]
@shaal do you have `gitpod.remote.syncExtensions` set to `true` on your settings.json? Not sure if this option is still valid.

**Comment by axonasif** [comment]
Could you please also share [logs](https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop) through email 🙏 ?

**Comment by shaal** [comment]
Sure, I'll send the logs.
The issue is that the same setup works on Mac, but doesn't work on Windows.

**Comment by shaal** [comment]
@axonasif @loujaybee logs sent to troubleshooting@gitpod.io

**Comment by jeanp413** [comment]
@shaal could you share the logs from `settings sync` from the `output` panel too :pray: , also could you run `Settings Sync: Show Synced Data` command and share the contents of the latest extensions entry in the `sync activity (remote)` view

**Comment by jeanp413** [comment]
@shaal do you still have this issue? if so please share the following logs
> could you share the logs from settings sync from the output panel too , also could you run Settings Sync: Show Synced Data command and share the contents of the latest extensions entry in the sync activity (remote) view

**Comment by shaal** [comment]
Yes, I still have this issue, I'll share the logs next time I'm opening Gitpod in vscode.

**Comment by jeanp413** [comment]
Hi @shaal, if you are using using vscode version 1.81.0 or greater then this is related to https://github.com/gitpod-io/gitpod/issues/18573, I just released version `v0.0.153` of the gitpod extension addressing installation of local extensions on the remote, please update and let me know if you still find any issues :pray:

**Comment by shaal** [comment]
@jeanp413 thank you.
I am using Windows + VSCode-insiders v1.82.0-insider + Gitpod v0.0.154.
I still have to manually click on that button `Install in SSH` in order to install these extensions (e.g. Github Copilot, Total Typescript, Gitlens, and more) -
![image](https://github.com/gitpod-io/gitpod/assets/22901/36afeac9-d3e0-42e6-b4e6-e340677fe98f)

**Comment by jeanp413** [comment]
@shaal what's the version of the remote-ssh extension, it was buggy in insiders and you need to update it to latest version `v0.106.2023083015`
If remote-ssh extension is updated then could you enable trace logs in gitpod extension and share the logs.
- Run `Developer: Set Log Level...` command
- Select Gitpod
- And then select trace as default
![image](https://github.com/gitpod-io/gitpod/assets/25115070/61f447b4-a3d1-4138-b585-c060610b28cb)
- Run `Gitpod: Install Local Extensions...` command
- Share Gitpod logs

**Comment by shaal** [comment]
@jeanp413 thank you! That was it! I had to switch `remote-ssh` extension to pre-release version, and now it's v0.106.2023083015

I can confirm Gitpod workspace that opens in local VSCode - loads all local VSCode extension as expected, no manual steps required.

🎉
