### ISSUE TITLE
make local companion app expose ports on all interfaces instead of 127.0.0.1

### ISSUE THREAD

**Issue by pseudozach** [gitpod-io/gitpod#7909]
is there anyway to forward gitpod instance ports to 0.0.0.0 on my local machine so I can access it from local network IP?

local companion app works but it makes it available on 127.0.0.1:port, I want these ports to be available at 192.168.0.x:port (local network IP)

is this possible as a config option on local companion app, I haven't found it...

**Comment by mustard-mh** [comment]
when you start a local-companion, you can find this button on remote explorer

<img width="508" alt="image" src="https://user-images.githubusercontent.com/20944364/151664021-ae110132-640e-4964-ad56-2660f1b89045.png">

**Comment by pseudozach** [comment]
I don't see this in remote explorer view. I start the companion app but
this doesn't come up. Do I need to restart the workspace?

**Comment by mustard-mh** [comment]
Maybe you need refresh workspace page

**Comment by pseudozach** [comment]
> Maybe you need refresh workspace page

no, refresh doesn't help. still don't see it. Do I need to use local ms visual studio? Because I'm using the one on gitpod.io.

![Screen Shot 2022-02-01 at 10 13 53 PM](https://user-images.githubusercontent.com/3731591/152102344-2deba482-e7ff-4a5c-ab82-a2c0d8a677d2.png)

**Comment by pawlean** [comment]
@pseudozach Are you using the Local Companion App with your local VS Code? You should be looking at your local VS Code, not gitpod.io.

**Comment by pseudozach** [comment]
I tried both. refreshed and opened it in local VS code. I still don't see
the option to tunnel all interfaces.

**Comment by pseudozach** [comment]
I don't even see the ports in the `remote explorer` view in local VS Code
![Screen Shot 2022-02-02 at 10 38 54 AM](https://user-images.githubusercontent.com/3731591/152217090-b0d816b1-f75c-4360-a22e-d6a30fc14b06.png)

**Comment by axonasif** [comment]
@pseudozach are you using windows/mac/linux?

**Comment by pseudozach** [comment]
macos m1

**Comment by akosyakov** [comment]
Local companion only works with VS Code Web. For VS Code Desktop we rely on Remote SSH from MS. Please consult: https://code.visualstudio.com/docs/remote/ssh#_forwarding-a-port-creating-ssh-tunnel
