### ISSUE TITLE
Bug: Incorrect Context parsing for bitbucket

### ISSUE THREAD

**Issue by ramank775** [gitpod-io/gitpod#7922]
### Bug description

There is an issue with gitpod context parsing with bitbucket.. basically in bitbucket at  source. If you switch branch using filter branch.. bitbucket will redirect you to the url in format `bitbucket.org/<org>/<repo>/src/commit-hash/?at=<branch-name>`

When appended gitpod.io/# in front of the url.. it open the workspace with that commit-hash in detached mode..

But when you simply switch the branch from drop down without using filter it switch to the url as `bitbucket.org/<org>/<repo>/src/<branch-name>`.

### Steps to reproduce

- Browse to bitbucket repository
- Navigate to `<> Source` section from left navigation.
- Click on the branch name to switch branch.
- use filter branches to search for any branch.
- open gitpod

### Expected behavior

Workspace should open on selected branch instead of the commit.

**Comment by ramank775** [comment]
Hey gitpod team,

I am willing to work on this issue. If anyone for help me with the starting point and little guidance that will be great.

**Comment by JanKoehnlein** [comment]
Thanks @ramank775 for this issue and for your offer to look at this. My first guess would be to look [here](https://github.com/gitpod-io/gitpod/blob/0cb0f38cadc880a99df34a99757f742684a644b4/components/server/src/bitbucket/bitbucket-context-parser.ts#L29). There is also a [test](https://github.com/gitpod-io/gitpod/blob/0bb6650e35a9a44962599a78a328fdea4716d143/components/server/src/bitbucket/bitbucket-context-parser.spec.ts#L111) for this case.

Paging @AlexTugarev here as it looks we parse both `revision` and `branch` here on purpose.

**Comment by ramank775** [comment]
Thanks @JanKoehnlein 
I runs the integration testing with some hacks (avoid making calls to bitbucket). Context parsing seems to be working as expected. The ref is the branch name value match with the URL searchParams `at` and refType is `branch`.

**Comment by ramank775** [comment]
Update

The issue seems to be with the gitpod browser extension. When we open the workspace from the button generated by the gitpod extension it doesn't consider the search params when creating redirection url.

Missed that completely on the first glance.

**Comment by JanKoehnlein** [comment]
Good catch, @ramank775!

The `browser-extension` repo shares the same issues, so you can just create a PR there and link it to this issue.

**Comment by ramank775** [comment]
Hi @JanKoehnlein I have open an PR https://github.com/gitpod-io/browser-extension/pull/53 please have a look

**Comment by JanKoehnlein** [comment]
Thanks a lot @ramank775 for the contribution!

We are trying to release that ASAP.
