### ISSUE TITLE
Epic: Low-friction dashboard form to collect feedback

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7925]
**Summary**

Users are more likely to provide feedback, the easier we make it for them.

Inspired by the feedback form for Gitpod [docs pages](https://www.gitpod.io/docs/configure), we'd like offer a similar form in the dashboard. (see below)

#### Requirements
- Needs to work for errors as well as all dashboard pages
- Offer the same emoji, and an input prompting for feedback.
- Send responses to Segment
- Include the page context and any error state

### Proposed Interaction
- Dashboard: replace `Help` -> `Feedback` which opens Modal (move `Help` under user dropdown) 
- Errors: Ask `Was this helpful?` with emojis, then open same Modal

| Modal (Non selected) | Modal (Active) |
|-|-|
| <img width="1440" alt="Modal-1" src="https://user-images.githubusercontent.com/120486/154722187-714064a1-7720-4b25-9f36-e4c31e7f3654.png"> | <img width="1440" alt="Modal-2" src="https://user-images.githubusercontent.com/120486/154722195-8fbfc38e-df99-492e-aade-83c6c2c38116.png"> |

| Login Error | Workspace Error |
| - | - |
| ![Screenshot 2022-05-08 at 13 07 17](https://user-images.githubusercontent.com/849592/167295511-229206cf-dd79-4bbc-a9cc-a5defbd825ab.png) | ![Screenshot 2022-05-08 at 12 29 32](https://user-images.githubusercontent.com/849592/167295510-68d210af-66fd-4387-90b9-6e7654488145.png) |

### Existing form in docs
| On every page | Emoji opens form |
| - | - |
| ![Screenshot 2022-05-08 at 11 34 14](https://user-images.githubusercontent.com/849592/167292247-d163233c-b829-468f-a4a4-82b40b41fcfd.png) | ![Screenshot 2022-05-08 at 11 34 30](https://user-images.githubusercontent.com/849592/167292249-614b9895-1afd-4cf9-9368-9e00a28820e2.png) |

cc: @jakobhero 

### Tasks
- [x] #9928
~~- [ ] Hide behind feature flag~~
- [x] Adjust top nav
- [x] #10062
- [x] #10296

**Comment by gtsiolis** [comment]
Thanks for the ping, @jldec! 🏓 

Cross-linking also a past issue related to this in https://github.com/gitpod-io/gitpod/issues/4196 in case it contains any helpful content. Feel free to also close of these if needed. 📕 

While I'm in favor of making it easier to collect user feedback from within the product, there're multiple ways to approach this. For example, building better issue template forms for feature requests or bug reports, and potentially linking directly to those could be a good MVC (minimum viable change) step, etc. Also, it could be worth discussing what feedback points or types could help or bring in more impact for the product before proceeding with any design proposals. 💭 

FWIW, there was also a relevant issue in https://github.com/gitpod-io/gitpod/issues/3564 which surfaced the need to have a system status indicator for service availability which could be also related here. See https://github.com/gitpod-io/gitpod/issues/4160 and early design drafts in https://github.com/gitpod-io/gitpod/issues/4160#issuecomment-907205163. 🟠 

I'm adding this as a discussion point for our next sync meeting but let me know if you think this is something I could start actively work on in terms of design. Unassigning for now.

**Comment by jldec** [comment]
Thanks @gtsiolis 🏓 

The suggestions to link to feedback issues or another form are helpful, but they are not low friction enough. We need a way for users to provide their sentiment and a very quick bit of text without changing context or being faced with a myriad of questions (which tends to happen with issues).  

I don't think we should rely on the same mechanism for system status (we need well-instrumented alerts for that).

I think the docs feedback has been quite successful and we can use it as a model, so yes, you can go ahead with ideas for how / where to enable something similar in the dashboard.

**Comment by jldec** [comment]
MVC outline - following [internal discussion](https://www.notion.so/gitpod/WebApp-Design-Sync-Feb-3-2022-c36014b1796b49f1bc515264da405ab3)

- "Send feedback" text link
- The link should be unobtrusive, but visible on every dashboard page, including admin pages
- The link should open a modal popup with a feedback form, very similar to the docs feedback form
- Use the same emojis for collecting sentiment
- Offer a single text input, for entering feedback
- The form captures the dashboard page name and other state like user context and any errors 

**Nice to have**

- Offer this feedback also on the start-workspace and start-workspace-error pages
- If used while starting a workspace, bouncy G continues in background, but IDE is not opened until modal is dismissed.

@gtsiolis - feel free to adjust the above description.

**Comment by gtsiolis** [comment]
Posting below a proposal for adding a feedback widget within the dashboard. Cc @jldec 

Going through the navigation:

| Current | Breakdown | Scaling | Proposal |
|-|-|-|-|
| <img width="600" alt="Link-3" src="https://user-images.githubusercontent.com/120486/154721870-76ebf4e4-b453-483c-9ee2-35af1c5d96b8.png"> | <img width="600" alt="Link" src="https://user-images.githubusercontent.com/120486/154721868-15902ec9-10ce-4c44-99e1-cd37ef7076a0.png"> | <img width="600" alt="Link-1" src="https://user-images.githubusercontent.com/120486/154721877-c8ea761a-d155-41c2-8af1-ee3b31d35e31.png"> | <img width="600" alt="Link-2" src="https://user-images.githubusercontent.com/120486/154721884-02586d29-7ba5-4a2a-9776-f369036c4451.png"> |

Going with a visible menu item that trriggers a modal on click, depending on whether we'd like to include the emojis on this iteration, here's how the modal could look like:

| Modal (Iteration 1) | Modal (Iteration 2 - Non selected) | Modal (Iteration 2 - Hover & Active) |
|-|-|-|
| <img width="1440" alt="Modal" src="https://user-images.githubusercontent.com/120486/154722178-5ecf694b-f3a9-47e5-982f-598d820eb23f.png"> | <img width="1440" alt="Modal-1" src="https://user-images.githubusercontent.com/120486/154722187-714064a1-7720-4b25-9f36-e4c31e7f3654.png"> | <img width="1440" alt="Modal-2" src="https://user-images.githubusercontent.com/120486/154722195-8fbfc38e-df99-492e-aade-83c6c2c38116.png"> |

See [design specs](https://www.figma.com/file/HknoZvF952qXt3Sk4wLdrq/Low-friction-dashboard-form-to-collect-feedback-about-Gitpod-features-%237925?node-id=0%3A1).

**Comment by jldec** [comment]
Hi @gtsiolis, I have a couple more suggestions.

1. I have changed the description to include this feature on Error screens as well (to match our G&Rs)
1. I would prefer to keep the `Docs` link visible in Dashboard (not move into user dropdown menu)
1. Let's not link to issue tracker - but I think we do have to mention privacy policy (as in docs)

If you are ok with these changes, could you update your designs?

**Comment by gtsiolis** [comment]
@jldec 

1. ❗ I'm trying to understand the value of having the feedback functionality on the error pages given this will also introduce a separate system to maintain and monitor for user feedback. Posting some thoughts and questions below, let me know what you think.
    - Regarding using the emojis on the error pages, do we expect to ever see any positive feedback submissions on workspace or login _errors_?
    - In these error cases it sounds we need to improve **system status visibility** or **provide better actions** to users.
    - Also, in the error cases, it could be beneficial to redirect users to our issue tracker as a single source of truth (SSOT) to help avoid duplicate reports from other community members, etc.
    - In any case, using a similar tertiary action button with the same label to trigger the same feedback modal could be a good approach to try this in action without overloading the error pages, see screenshots below.
3. ✔️ Since we have not made any changes to the navigation yet per https://github.com/gitpod-io/gitpod/issues/8385, keeping the _Docs_ in the help menu sounds ok. In the long, I'd expect keeping _Docs_ and _Feedback_ link in the help menu along with _Workspaces_ to become slightly problematic, especially as more links could race for a spot in the menu like _Help_, _What's New_, _Changelog_, and more. However, this is not an issue in the current state of the navigation. 
4. ✔️ Sounds ok to drop the links to the issue tracker, however, I don't think we need to mention the privacy policy as dashboard usage is already covered by the browse-wrap consent of the privacy policy from the login page. Let me know if you think it's still necessary to include the privacy policy.

| Login Error | Login Error (Hover) | Workspace Error |
|-|-|-|
| ![Frame 323](https://user-images.githubusercontent.com/120486/167508460-53d4d47f-46e2-4ed5-97be-3633e19b9d32.png) | ![Frame 321](https://user-images.githubusercontent.com/120486/167508466-6b97efe3-c566-4e5d-b75c-dc3b1059ebe9.png) | ![Frame 322](https://user-images.githubusercontent.com/120486/167508472-d4238fb4-a370-4ea5-9c88-093c8c0a5da6.png) |

**Comment by laushinka** [comment]
>    * Regarding using the emojis on the error pages, do we expect to ever see any positive feedback submissions on workspace or login _errors_?

We can ask "Was this error message helpful?"

**Comment by jldec** [comment]
@gtsiolis 
- I think feedback on our error messages will be useful (we included this in our G&Rs)
- Thank you for confirming that the top nav is ok with Docs and Feedback for now.
- I prefer to keep the privacy policy link in the form for consistency with the docs feedback. (see https://github.com/gitpod-io/website/issues/1709) - cc: @MircoatGitpod 
- I very much like @laushinka's suggestion to ask "Was this error message helpful?" with the emojis below that (like docs). What do you think about doing something similar (3-step click on feedback, click on emoji, submit form) for the dashboard link instead of going straight to the modal. This will address the ambiguity in the current design about whether selecting an emoji is required or not.

**Comment by laushinka** [comment]
@jldec @gtsiolis After seeing the changes it would require, I propose implementing the feedback in error messages to be a separate PR - otherwise it would be too big.

**Comment by jakobhero** [comment]
> 

💯! also, it would be great if we could use the same event name as on the website, i.e. `feedback_submitted` for consistent data!
