### ISSUE TITLE
Update card selector component and sidebar design

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#7932]
### Problem to solve

The current card selector component can feel a bit distracting due to bordered layout. This becomes for visible with the growing list of available editors.

### Proposal

Following the designs in https://github.com/gitpod-io/gitpod/pull/7852#issuecomment-1026155557 and the design exploration happening in the backstage for https://github.com/gitpod-io/gitpod/issues/7564, here're some early design drafts how we could update the card selector component design. This can affect the editor selection, as well as, theme and plans sections in user settings. Cc @akosyakov @loujaybee 

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="Editors" src="https://user-images.githubusercontent.com/120486/151875851-d5e60ad3-8b6e-47f5-9d8b-d3e8fc09e751.png"> | <img width="1440" alt="Editors-1" src="https://user-images.githubusercontent.com/120486/151875856-c7e155f7-68fb-4752-8340-95f609f6115a.png"> |

To this extend, we could also include the version as mentioned in https://github.com/gitpod-io/gitpod/pull/7852#issuecomment-1024048382.

| Using stable version | Using latest version |
|-|-|
| <img width="1440" alt="Editors-2" src="https://user-images.githubusercontent.com/120486/151875872-9d6c55d9-baf5-4803-8402-ea7a6c96e542.png"> | <img width="1440" alt="Editors-3" src="https://user-images.githubusercontent.com/120486/151875898-72dda557-159b-4100-a928-b64f66d19d67.png"> |

TBD (To be discussed)

**Comment by gtsiolis** [comment]
To explain further this design approach, see below how this could help information hierarchy and overall UX.

| Low fidelity design | Low fidelity design in perspective | Layer design |
|-|-|-|
| <img width="1440" alt="Editors" src="https://user-images.githubusercontent.com/120486/151882418-341a4293-cd4b-48c8-9392-6927f2017038.png"> | <img width="2114" alt="Editors-1" src="https://user-images.githubusercontent.com/120486/151882419-c4b3621c-f3bc-4c69-83ac-6ff8fe33201f.png"> | <img width="1440" alt="Editors-2" src="https://user-images.githubusercontent.com/120486/151882420-a8fcb258-b183-427d-a359-9d3ee30ca483.png"> |

**Comment by akosyakov** [comment]
> To this extend, we could also include the version as mentioned in #7852 (comment).

I really like to see versions too :) There are actually numbers too, i.e. 1.64-insiders, eap-213.103.14 and so on

**Comment by loujaybee** [comment]
I think this is a really important issue. 

1. Gives desktop and browser equal weighting in the app

We should mention this would resolve the inconsistency in

**Comment by loujaybee** [comment]
I think this is a (seemingly) small but really important issue—thanks for raising @gtsiolis ! 

1. It gives both desktop and browser more of a feeling to the user of equal weighting in Gitpod, which aligns best with having an orthogonal product [[1](https://www.notion.so/gitpod/Values-Attributes-2ed4c2f93c84499b98e3b5389980992e#10e6a778877949728fc17e6ce939c1ba)] and our IDE / product ambitions! 🚀 
2. This will resolve inconsistencies with selecting early access/insider versions for both VS Code and JetBrains IDE's [[1](https://github.com/gitpod-io/gitpod/pull/7852#issuecomment-1026652365)]

A couple thoughts on current design: 
1. The black square is not entirely obvious to me as a selected state, is there any way we could make the selected state stronger/more obvious, somehow? Maybe reintroducing the tick, or some other visual cue?
2. "Latest release" doesn't necessarily signify to me that the version is potentially unstable. We should review the copy text, and/or add some disclaimers. But, of course the challenge is to have copy text which applies to both VS Code Insiders, and also JetBrains EAP without overloading the UI.

**Comment by gtsiolis** [comment]
Thanks for the feedback, @loujaybee!

> The black square is not entirely obvious to me as a selected state

This is currently an early design. We could probably improve the colors, keep the thick border or the tick, etc.

> "Latest release" doesn't necessarily signify to me that the version is potentially unstable.

Completely agree. UX copy is also work in progress and you're right about the version is potentially unstable. We should probably include a hint about this.

**Comment by gtsiolis** [comment]
Picking this up to finish the sidebar menu color changes. Card component and copy updates are taking place in https://github.com/gitpod-io/gitpod/pull/8783, see also https://github.com/gitpod-io/gitpod/issues/8786 for the single option for editor selection.
