### ISSUE TITLE
Feature Request: Be able to specify fallback gitpod.yml file(s) for repos missing this file

### ISSUE THREAD

**Issue by mickmister** [gitpod-io/gitpod#7939]
## Describe the behaviour you'd like

Similar to environment variable settings in that you can provide matcher for different repositories to apply the variable to, I would like to be able to set a default `gitpod.yml` file for certain repositories that do not have the `gitpod.yml` file in the repository at the moment.

**Comment by mickmister** [comment]
Seems like a duplicate of https://github.com/gitpod-io/gitpod/issues/7608, since both issues are trying to solve the same problem of letting multiple repositories use the same `gitpod.yml`

**Comment by pawlean** [comment]
You're right @mickmister! Will close this.

**Comment by mickmister** [comment]
The linked ticket is actually an epic, and this ticket could be included in that epic since this ticket is after the same goal. I'm thinking this would give a user more power within the Gitpod user settings, when a given repository hasn't been converted to use Gitpod yet.
