### ISSUE TITLE
Webpack Dev Server: [WDS] Disconnected

### ISSUE THREAD

**Issue by JamesGreenaway** [gitpod-io/gitpod#794]
**Describe the bug**

When running `webpack-dev-server` I am currently getting an error in the console like this: 

<img width="882" alt="Screenshot 2019-09-16 at 10 44 12" src="https://user-images.githubusercontent.com/16066511/64948436-f9c5c200-d86e-11e9-9c56-a5ca8ba41bb7.png">

**To Reproduce**
* npm i -D webpack webpack-dev-server 
* add this to webpack.config.js: 
    ```
    devServer: {
        contentBase: './dist',
        host: '0.0.0.0',
        disableHostCheck: true,
    },
    ```
* add this to npm scripts: 
    ```
    "start": "webpack-dev-server"
    ```
* run `npm start`

**Expected behavior**

Start web server and the ability to use live reloading.

**Comment by jankeromnes** [comment]
Hi @JamesGreenaway, thank you for filing this issue, and sorry about this problem.

The live-reload URL in the error log looks almost correct, except that it's actually using port `:8080`:

```
https://8080-abc-123.ws-eu0.gitpod.io:8080/sockjs-node/...
```

This won't work, as our workspace nodes only work via the normal HTTPS port 443 (and connection to various ports are actually routed via the domain name).

The correct URL should be:

```
https://8080-abc-123.ws-eu0.gitpod.io/sockjs-node/...
```

(without the `:8080`)

Would you be able to configure live-reload to run on port 8080, but make the front-end use the correct URL format above?

**Comment by JamesGreenaway** [comment]
excellent it now works when I added the following options: 
```
public: 'https://8080-abc-123.ws-eu0.gitpod.io',
port: '8080',
```
🎉thanks!!

**Comment by jankeromnes** [comment]
That's great! Thanks for the update.

Note that the value for `public` can be given programmatically in any workspace by the bash command:

```
go url 8080
```
