### ISSUE TITLE
Matplotlib support

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#795]
It would be nice if in matplotlib you could show graphs with the whole native ui thing like you would on a desktop

**Comment by jankeromnes** [comment]
@JesterOrNot Thanks a lot for the great suggestion!

Quick question: Maybe basing your `.gitpod.yml` on `image: gitpod/workspace-full-vnc` would be sufficient?

This will give you a VNC Remote Desktop, and I suspect that Matplotlib will then detect the X server and show its native windows in there.

**Comment by JesterOrNot** [comment]
graphQuadMod.py:23: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
https://gitpod.io/#github.com/JesterOrNot/pycalc

**Comment by jankeromnes** [comment]
@JesterOrNot Hi again, sorry for the delayed reply. I'm looking into getting Matplotlib to work.

What specific steps do you follow in order to trigger the Matplotlib graphing code? I tried:

```bash
cd algeb/graph/
python3 main.py
```

but I'm not sure what values to give it so that it plots a graph?

**Comment by jankeromnes** [comment]
Also, FYI, I had to make a few changes to the Gitpod setup in my fork to make it work: https://github.com/jankeromnes/Python-Calc/commit/8e134dc561cbecb3ccb9a5cfb2ec04c41dde9cef

Maybe this can be useful to you. 🙂 I'm happy to send you a Pull Request.

**Comment by JesterOrNot** [comment]
1. cd algeb/graph
	python3 graphQuadMod.py
2. Thank you please send the PR

**Comment by jankeromnes** [comment]
Thanks a lot @JesterOrNot! I was now able to reproduce the problem:

```
gitpod /workspace/Python-Calc/algeb/graph $ python3 graphQuadMod.py
What is the equasion type vertex form or standard form
Which one do you want?: vertex
What is a?: 1
What is h?: 1
What is k?: 1
graphQuadMod.py:41: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
```

Will look into making Matplotlib use the graphical environment instead.

**Comment by jankeromnes** [comment]
@JesterOrNot It finally worked!

<img width="1552" alt="Screenshot 2019-10-01 at 16 37 02" src="https://user-images.githubusercontent.com/599268/65973201-3565ac00-e46b-11e9-978c-7cd10d29e0b4.png">

And here is the PR with my changes: https://github.com/JesterOrNot/pycalc/pull/15

**Comment by JesterOrNot** [comment]
Great it works perfectly thank-you I'm Going to close this issue
