### ISSUE TITLE
Downloaded workspace file does not have any valid file extension specified

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#7955]
### Bug description

A downloaded workspace file is a tarball(`.tar`) but it's causing confusion among users since it's not reflected in the downloaded file name. A user will normally have to figure out themselves what is kind of file they downloaded and how to deal with it, resulting in an even bad experience on top of whatever the incident led them towards downloading their workspace.

### Steps to reproduce

- Go to https://gitpod.io/workspaces
- Toggle the right options menu of a workspace in the list
- Select `Download Workspace`

### Expected behavior

The downloaded file should have an explicit file extension, in this case, `.tar`

### Anything else?

Nothing more, but thanks for paying attention here 😄

**Comment by gtsiolis** [comment]
Oh, this is new.  Nice catch, probably a regression since this used to work ok by using the `.tar` file extension. ⚾

**Comment by mcgrealife** [comment]
+1 Without discord support, I would have not known it was a `.tar` file.

**Comment by gtsiolis** [comment]
Thanks for tackling this, @ghostdevv! 💯
