### ISSUE TITLE
OAuth integration and Workspace starts with Bitbucket Server v7.20

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7957]
This is the first step toward enabling integration of Gitpod with self-hosted BItbucket Server and Bitbucket Datacenter installations.

With their [v7.20 release](https://confluence.atlassian.com/bitbucketserver/bitbucket-data-center-and-server-7-20-release-notes-1101934428.html), Bitbucket Server and Datacenter now support OAuth2.

- [ ] Enable OAuth logins between Gitpod and a Bitbucket Server v7.20 Server instance
- [ ] Extend the context parser and enable workspace starts with prefixed URLs

**Comment by gtsiolis** [comment]
@jldec see also https://github.com/gitpod-io/gitpod/issues/1965.

**Comment by jankeromnes** [comment]
(FYI, undoing the latest title change to "pre" because it doesn't look intentional 👀)
