### ISSUE TITLE
Plugin loads are broken again, startup scripts aren't running either.

### ISSUE THREAD

**Issue by zaptrem** [gitpod-io/gitpod#796]
Startup scripts don't run and plugins that were already added to gitpod.yml do not show up. Plugin installs fail as well.

**Comment by svenefftinge** [comment]
I cannot reproduce. Please share a project where you are seeing the issue.

**Comment by zaptrem** [comment]
https://github.com/zaptrem/ReLearnApp

**Comment by svenefftinge** [comment]
The config was broken. That should definitely be made more clear.
I have created a PR https://github.com/zaptrem/ReLearnApp/pull/1
Thanks for reporting!

**Comment by zaptrem** [comment]
Thanks for the help. Sorry about that! I have no idea how I went so long without noticing to where I just assumed it was a new problem.

**Comment by svenefftinge** [comment]
You are welcome. It definitely is Gitpod that should tell you about a broken config.
