### ISSUE TITLE
[ws-daemon] cannot set CFS quota

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#7963]
### Bug description

seeing this in log spamming non stop:
```
"cannot set CFS quota:
    github.com/gitpod-io/gitpod/ws-daemon/pkg/resources.cgroupCFSController.SetQuota
        github.com/gitpod-io/gitpod/ws-daemon/pkg/resources/controller.go:420
  - write /mnt/node-cgroups/cpu/kubepods/burstable/pod4c349442-a7f3-401b-a667-4bc68ee5ba45/f87cae5fd4e0fb23571a777086c3be55f564cabdf3fe256e650aafdf9a2b589e/cpu.cfs_quota_us: invalid argument"
```

might be related to this: https://github.com/gitpod-io/gitpod/issues/5326

customer reported following:
```
One of my workspaces times out on startup after 3-4 minutes with the following error message:

Oh, no! Something went wrong!
Error: no available workspace cluster to choose from!

(This is harlequin-limpet-1t9g3dau.). The error has been going for the last 45 mins or so, and I've noticed increasing intermittent errors over the last few days.
```

Not sure if timeout related to error that I am seeing in logs.

### Steps to reproduce

search for affected workspace in logs.

### Workspace affected

harlequin-limpet-1t9g3dau

**Comment by sagor999** [comment]
@csweichel do you know what might be going on here?

**Comment by aledbf** [comment]
@sagor999 please continue working on https://github.com/gitpod-io/gitpod/pull/7797

**Comment by Furisto** [comment]
I do not see this in the logs for eu34 and us34.
