### ISSUE TITLE
Jetbrains plugin fails in windows

### ISSUE THREAD

**Issue by buggtb** [gitpod-io/gitpod#7965]
### Bug description

When you follow the Gateway instructions for Jetbrains on a Windows computer it fails with:

Can not find connection provider

But launching the same workspace on my Fedora laptop caused the Gateway to work and everything come to life as expected.

### Steps to reproduce

Just launch an intellij backed workspace in Windows.

### Anything else?

This user reported it and then I tried tonight and it failed. https://discord.com/channels/816244985187008514/905926786339188746/937392814499704973

**Comment by akosyakov** [comment]
PR is here: https://github.com/gitpod-io/gitpod/pull/7952 We are going to test and deploy it today.
