### ISSUE TITLE
Workspace shutdown unexpectedly

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#7983]
### Bug description

On February 1 @ 11:02pm UTC, the workspace shutdown unexpectedly after a minute.

[Related discord thread.](https://discord.com/channels/816244985187008514/938192626543362140)

### Steps to reproduce

@shaal are you able to recreate this with any particular public repos?

### Workspace affected

https://phase2-hfdrupal-s60ok2xajnq.ws-us30.gitpod.io/

### Expected behavior

The workspace does not unexpectly stop a minute after starting.

### Example repository

n/a

### Anything else?

[The related logs](https://cloudlogging.app.goo.gl/aJwijQ9mJ1Hvn86k6)

**Comment by kylos101** [comment]
@shaal can you share if this has happened more than once, or just the one time? If more than once, how frequent is it?

**Comment by shaal** [comment]
I created a small public repo that reproduces the issue.
https://github.com/shaal/gitpod--custom-docker-image-tester

You'll see that it cannot find `docker` in terminal, and after a couple of minutes - it shuts off

**Comment by shaal** [comment]
I noticed this error in console, after running in that small repo `sudo apt-get update`

![image](https://user-images.githubusercontent.com/22901/152183736-72722a7b-c66b-4b60-9745-2aebacdf57aa.png)

Full console error - https://gist.github.com/shaal/6faf4687253964a1e2e0f03157ce974e

**Comment by kylos101** [comment]
@csweichel @sagor999 when you free up, may I ask [you to inspect the logs](https://cloudlogging.app.goo.gl/aJwijQ9mJ1Hvn86k6), to see why @shaal 's workspace stopped unexpectedly after a minute?

@shaal it seems like you're also having a prebuild issue. May I ask you to create a separate issue, moving the related content from this issue to that new one? The `workspace-base` image hasn't changed recently (the digest for latest is from 2 months ago), `9ec820459a27`, is that what you're using as your base?

**Comment by sagor999** [comment]
@shaal when #7989 will get deployed into prod (sometime next week I believe) you should now see a proper error as to why docker was not able to start up, instead of crash.
