### ISSUE TITLE
Error when creating a new workspace 

### ISSUE THREAD

**Issue by averycho** [gitpod-io/gitpod#7988]
### Bug description

I am receiving an error when trying to create any new workspace and am unable to open a previously created workspace. Below is a screenshot of the error I am seeing. Even when deleting existing workspaces and trying to start a new one I see the same error. 

<img width="511" alt="Screen Shot 2022-02-01 at 5 19 28 PM" src="https://user-images.githubusercontent.com/62025193/152208751-6b26b9b5-17c5-454d-be4a-4cf63e08ce75.png">
 

### Steps to reproduce

I'm not sure how this error initially occurred, so it's not clear how to reproduce this issue.

**Comment by axonasif** [comment]
Hi @averycho, can you share your `.gitpod.Dockerfile` and `.gitpod.yml` contents? It would be also helpful if you could share your repo if it's public.

**Comment by sagor999** [comment]
Try to install this in your `.gitpod.Dockerfile`:
https://git-lfs.github.com/

**Comment by atduarte** [comment]
@averycho did @sagor999 suggestion solve the issue?

Will remove `priority: highest (user impact)` for now, given a potential solution was provided.

**Comment by jldec** [comment]
Closing in favor of https://github.com/gitpod-io/gitpod/issues/8117 which explains the cause of this.
