### ISSUE TITLE
Python Jupyter code lenses rendered twice

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#799]
See 
![image](https://user-images.githubusercontent.com/239422/65149109-cd05dc00-da21-11e9-85ba-6e45b6ee1e86.png)

Code snippet to try:
```python
#%%
msg = "Hello World"
print(msg)

#%%
msg = "Hello again1"
print(msg)
```

Expectation: adornments such as "Run Cell" should only be rendered once.

**Comment by AlexTugarev** [comment]
<img width="317" alt="Screen Shot 2019-09-27 at 11 12 50" src="https://user-images.githubusercontent.com/914497/65757596-c8bf7a00-e117-11e9-85bb-4368c7af5519.png">

this doesn't appear to happen with recent Theia. I think this will be solved then with next update 👍
