### ISSUE TITLE
Internal Authentication Database

### ISSUE THREAD

**Issue by RedstoneWizard08** [gitpod-io/gitpod#7992]
## Is your feature request related to a problem? Please describe

It is not related to a problem.

## Describe the behaviour you'd like

I would like for GitPod to allow people to sign up with email and use workspaces there without a GitHub, GitLab, or Bitbucket account. It would allow people to link those accounts later but just try GitPod without any of that.

## Describe alternatives you've considered

None.

**Comment by axonasif** [comment]
@RedstoneWizard08 I think you should share your feedback regarding email auth at here instead https://github.com/gitpod-io/gitpod/issues/6967

Closing this for now.
