### ISSUE TITLE
You are about to authorize Gitpod local control client to access your Gitpod account including data for all workspaces.

### ISSUE THREAD

**Issue by ghuntley** [gitpod-io/gitpod#7994]
## Scenario

On a fresh install of macOS with VSCode.

1. Open workspace in Gitpod via web
2. Ctrl+Shift+P -> Open in VS Code
3. VS Code prompts to install Gitpod extension which I press yes to.
4. Browser is opened up with a consent screen pictured below

<img width="723" alt="2022-02-03_16-52-13" src="https://user-images.githubusercontent.com/127353/152288922-c209ef61-5e7b-4d09-b9bd-888d8e25b3ef.png">

## Feedback

1. From a user perspective what is a "Gitpod local control client"? It left me confused...

## Suggestion 

Change to be as follows:

title: Authorize Visual Studio Code [Insiders]
body: You are about to authorize Visual Studio Code [Insiders] to access your Gitpod account including data for all workspaces.

## Tech details

<code>https://gitpod.io/oauth-approval?clientID=gplctl-1.0&clientName=Gitpod%20local%20control%20client&returnTo=https%3A%2F%2Fgitpod.io%2Fapi%2Foauth%2Fauthorize%3Fclient_id%3Dgplctl-1.0%26code_challenge-redacted</code>

## Comparison

The auth consent flow screen when signing into GitHub with VS Code looks as follows. Things that are nice:

1. Authorize Client (that the user is using) to access resource (GitHub)
2. _If you_ initiated this request (using client that the user expects) click continue.

<img width="941" alt="2022-02-03_17-01-13" src="https://user-images.githubusercontent.com/127353/152289663-5998104a-5a49-4cdc-b9e8-e4eb9c1c8d01.png">

**Comment by akosyakov** [comment]
We are going to rework VS Code Desktop integration with usage of SSH Gaetway at some point and then there won't be local app auth anymore. A user will need to authotize Gitpod VS Code extensions still, but I think then it will sound more familiar.
