### ISSUE TITLE
opening PR for first time, gitpod opens my "workspaces" page

### ISSUE THREAD

**Issue by marcdumais-work** [gitpod-io/gitpod#8]
This has happened a couple of times recently, but not every time. 

I start from a GH PR URL, "converting" it to use it with gitpod (opening that PR for the first time with gitpod).  Gitpod then takes me to my workspaces page, where I see previously used workspaces, for different PRs.

Re-starting from the PR URL, a new gitpod workspace is created and opened, as originally expected.

**Comment by svenefftinge** [comment]
Thank you so much for reporting it. 
We have seen that, too and are already working on it.

**Comment by svenefftinge** [comment]
Fixed in the meantime
