### ISSUE TITLE
Searches for workspaces never return

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#8005]
### Bug description

When searching for a workspaceID (e.g. `0a88a641-6bfb-4fe1-8924-84c7e98bff07`) on https://gitpod.io/admin/workspaces, the icon (magnification glass) keeps spinning for 10min+ and I never get search results. 

### Steps to reproduce

(see above)

### Expected behavior

The search should return in less than a second.

### Anything else?

Is there maybe an index on the DB missing? I assume this would need to be a full-text index over multiple columns. Not sure if MySQL can do that or if this has other unwanted side-effects.

**Comment by laushinka** [comment]
Yes, currently we search on the contextURL and we have no index there. We should work on this soon as this is an ongoing problem. @jldec

**Comment by laushinka** [comment]
Current Honeycomb duration tracing[[1](https://ui.honeycomb.io/gitpod/datasets/gitpod-production/result/nZ7mf4rWHDW?hideCompare)] (thanks, @mads-hartmann!)

**Comment by laushinka** [comment]
Comparison tracing[[1](https://ui.honeycomb.io/gitpod/datasets/gitpod-production/result/hm2LRsu4iLi)]
