### ISSUE TITLE
~/.ssh/ is cleared between runs

### ISSUE THREAD

**Issue by 0xJem** [gitpod-io/gitpod#8006]
### Bug description

If a workspace encounters a timeout and is relaunched, the contents of the `~/.ssh/` directory are cleared. This makes it cumbersome to get running again, as the keys need to be copied over.

### Steps to reproduce

1. Open a workspace in VSCode (probably on the web too, but I've only tested VSCode)
2. Copy across keys into `~/.ssh/`
3. Let the workspace timeout. VSCode won't re-connect.
4. Open Gitpod.io, launch the same workspace.
5. `~/.ssh/` will only contain `authorized_keys` and `supervisor_env`

### Workspace affected

magenta-prawn-qs8g067f

### Expected behavior

The contents of the `~/.ssh/` directory should persist.

**Comment by atduarte** [comment]
Currently, only the `/workspace/` folder is backed up and therefore preserved. 

We are planning to tackle this issue by implementing a "full backup of the workspace". See https://github.com/gitpod-io/gitpod/issues/7719. Given that, will mark this as a duplicate.

**Comment by axonasif** [comment]
@atduarte in your `.gitpod.yml` `before:` task you can do such a thing:
```bash
tasks:
  - before: rm -rf $HOME/.ssh; mkdir -p /workspace/.ssh; ln -sf /workspace/.ssh $HOME/.ssh
```

Also, you can utilize the dotfiles[^1] `install.sh` if you want to avoid doing this for each and every repo via `.gitpod.yml`.
And in fact, you can save your ssh keys as an env var on https://gitpod.io/variables and use that to configure them for each workspace via scripting `install.sh` of the dotfiles feature. Although I wouldn't recommend you doing so.

[^1]: https://www.gitpod.io/docs/config-dotfiles

**Comment by 0xJem** [comment]
Thanks all for the feedback/suggestions!

Not entirely comfortable putting SSH keys into the variables, so the `before` task will have to do.
