### ISSUE TITLE
Last Backup Failed

### ISSUE THREAD

**Issue by ColbyWTaylor** [gitpod-io/gitpod#801]
**Describe the bug**
Tried opening. failed:

https://gitpod.io/start/#c546cbf4-c882-443b-862b-827d3205bab5

Expected the project to open (have not had an issue with this project prior)

**Comment by jankeromnes** [comment]
Hi @ColbyWTaylor, sorry about that.

Please note that, as long as you don't delete a workspace, we can retrieve a backup of the file system for you, even if the workspace is somehow broken / won't start. Please send us an email if you'd like that.

I'll take a look at the workspace you linked, to see if I spot anything suspicious.

**Comment by jankeromnes** [comment]
Oh oh, I found two instances for this workspace, and they show errors:

```
+--------------------------+--------------------------+---------+-------------------------------------------------------------------------------------------------------------+
| creationTime             | stoppedTime              | phase   | conditions                                                                                                  |
+--------------------------+--------------------------+---------+-------------------------------------------------------------------------------------------------------------+
| 2019-09-19T13:12:45.349Z | 2019-09-19T13:15:11.551Z | stopped | {"failed": "last backup failed: pod has no hostIP. Please contact support if you need the workspace data."} |
| 2019-09-19T13:20:18.827Z | 2019-09-19T14:00:22.941Z | stopped | {"timeout": "workspace timed out after after being closed took longer than 00h02m"}                         |
+--------------------------+--------------------------+---------+-------------------------------------------------------------------------------------------------------------+
```

**Comment by ColbyWTaylor** [comment]
Thank you @jankeromnes- initially had issues opening, so I restarted, and again after that I was able to get in as normal :)

**Comment by jankeromnes** [comment]
A colleague explained it to me like this:

> This is basically a false error message. it means that `ws-sync` tried to make a backup of a pod that had never been scheduled (and thus never received a hostIP). We should definitely improve the error message here (we shadow it with this wrong one).

So I think it was a rare occurrence where the pod wasn't properly scheduled? I'm glad that it worked again as normal afterwards! 🙂
