### ISSUE TITLE
Enhance Admin Node dashboard

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8013]
## Is your feature request related to a problem? Please describe

We could not view detailed info about a node in GCE during [this incident](https://gitpod.slack.com/archives/C0312QU68A3).

[We can see some data in Grafana](https://grafana.gitpod.io/d/gitpod-admin-nodes/gitpod-admin-node?orgId=1&refresh=30s), but it doesn't give us insight to what the node is doing "now". 

## Describe the behaviour you'd like

Add more content to the [existing Node dashboard](https://grafana.gitpod.io/d/gitpod-admin-nodes/gitpod-admin-node?orgId=1&refresh=30s) in Grafana using metrics from Node Exporter. To choose which metrics to display, compare with the data that is visible in GCE for a VM given its observability tab, and its many graphs. A list of running processes and supporting info would be ideal, as an example.

## Describe alternatives you've considered

Install the ops agent on our VMs, so we have the ability to see more observability data about a node in GCE. A lot of our observability study is done in Grafana, so that would be preferred.

## Additional context

During this incident, we lacked remote access to the node, lacked detail for the VM in GCE for observability, and in Grafana.

**Comment by csweichel** [comment]
Does this really have direct user impact? It's about our own visibility, not about user-facing system behaviour, no?

**Comment by kylos101** [comment]
> Does this really have direct user impact? It's about our own visibility, not about user-facing system behaviour, no?

No, [but, it's post-incident related](https://github.com/gitpod-io/gitpod/labels?q=directly), which is the second half of the label description. 

Would it help if we separate the label from post-incident related work?

**Comment by csweichel** [comment]
I think so - I was under the (mistaken) impression that we had a priority label for this case already

**Comment by kylos101** [comment]
Closing in favor of https://github.com/gitpod-io/gitpod/issues/7645 (which leverages an existing dashboard, saving us time).
