### ISSUE TITLE
Disable the Open IntelliJ button for a small period of time to stop users opening workspace twice

### ISSUE THREAD

**Issue by buggtb** [gitpod-io/gitpod#8014]
When I go to open a workspace, there is a button that says Open IntelliJ, but in the time my brain has processed that, its also started the automatic opening of the workspace, and so I've on occasion clicked the button and had it open both at the same time, which of course tries to launch the same thing twice.

The end result is IntelliJ opening, so its not broken, but it would make sense, to do similar to when a user downloads a file from a mirror or whatever and it highlights that the workspace should open automatically and that the button is a last resort. Maybe make it less obvious as it should happen by itself, or disable it for a few seconds to stop a user habitually clicking on the big green button when they don't need to.

**Comment by gtsiolis** [comment]
> I think we agreed that we shoudl allow to click

Agree, this sounds good also from UX perspective. 

I'll close this for now. Cc @loujaybee 

Thanks, @akosyakov! 🏀
