### ISSUE TITLE
Unable to open workspace

### ISSUE THREAD

**Issue by manni8436** [gitpod-io/gitpod#8029]
### Bug description

When I try to open the workspace, it says opening for a few seconds and then changes to stopping and stays there constantly, 

hard refresh and reload does not fix it.

### Steps to reproduce

attempt to open workspace

### Workspace affected

azure-butterfly-abg0ankl

### Expected behavior

the workspace should open and I would be able to access my code and project

**Comment by pawlean** [comment]
Do you have an example repo we can look at?

**Comment by manni8436** [comment]
Good afternoon,

Sorry I didn’t see your comment notification.

The browser editor is already set to VS Code as you asked me to do

Many thanks
Emanuel

**Comment by manni8436** [comment]
I had a look at the settings to do what yob adviced me and the setting is already on VS Code

**Comment by manni8436** [comment]
Hi, 

I tried to open my workspace again and it didn't work
