### ISSUE TITLE
Provide "Open in Gitpod" button as png

### ISSUE THREAD

**Issue by ChristianKohler** [gitpod-io/gitpod#8030]
## Is your feature request related to a problem? Please describe
VS Code extensions don't allow svgs in the readme:

![image](https://user-images.githubusercontent.com/4374178/152515969-af81edc7-e8b5-4fe9-ba83-32b792b87acd.png)

## Describe the behaviour you'd like
Provide a  `https://gitpod.io/button/open-in-gitpod.png` next to the `https://gitpod.io/button/open-in-gitpod.svg`

## Describe alternatives you've considered
no alternative 

## Additional context
Error: https://github.com/ChristianKohler/PathIntellisense/runs/5065227821?check_suite_focus=true

**Comment by Cahllagerfeld** [comment]
The Buttons live in the [`dashboard`](https://github.com/gitpod-io/gitpod/blob/30da76375c996109f243491b23e47feefab7217f/components/dashboard/public/button/open-in-gitpod.svg).
Our workflow is converting the svg to png and open PR in the `main`-repo.
Do we need to rebuild the button as `png` or can we just convert it from `svg` to `png` @ChristinFrohne

**Comment by ChristinFrohne** [comment]
Isn't it the same button as in the [component library](https://www.figma.com/file/VL0CJpHqcDJVJ4BEkoyRFV/Gitpod-Website-Component-Library?node-id=513%3A527)? If you need a .png file, you can select` .png `in the export settings and set the size to 3x. 
<img width="207" alt="Bildschirmfoto 2022-02-16 um 09 12 13" src="https://user-images.githubusercontent.com/46345125/154222789-4d77b00a-21bd-449e-9116-43665b01fa34.png">

So converting svg to png works fine. Hope that helps :)

**Comment by mikenikles** [comment]
Not allowing untrusted SVGs in VS Code extensions is a security feature introduced by VS Code in summer of 2017 [[1](https://github.com/Microsoft/vscode-vsce/issues/183#issuecomment-311577587)].

There is a feature request to sanitize instead of banning SVGs in VS Code extensions [[2](https://github.com/microsoft/vsmarketplace/issues/38)].

I'm closing this based on research summarized in [this comment](https://github.com/gitpod-io/gitpod/pull/8237#issuecomment-1042922882).

**Comment by ChristianKohler** [comment]
Hey @mikenikles 

Very well researched and a super transparent communication 💪

Thank you for looking into it. I understand the limitations.

**Comment by mikenikles** [comment]
You're welcome. It initially looked like a simple task, but as is often the case in our industry, the devil is in the details 😅.

Btw feel free to use any of the png assets in [this comment](https://github.com/gitpod-io/gitpod/pull/8237#issuecomment-1042685296) if they fit your needs.
