### ISSUE TITLE
Handling of untitled file is not right

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#804]
steps to reproduce

1. open a repo with a jupyter notebook (`.ipynb`)
2. in the context menu on the file, select "import jupyter notebook"
3. see a new editor named `Untitled-1.py`

Lots of things are "not right" around this file:
a) `File -> Save` does noting
b) `File -> Save as...` does nothing
c) "Reveal in Explorer" selects the `.ipynb` file
d) "Run in Terminal" tries to run `/opt/conda/bin/python /Untitled-2.py` and fails because `/Untitled-2.py` does not exist.

**Comment by jankeromnes** [comment]
@meysholdt Might this be a bug with a VS Code extension? Maybe it should be filed against https://github.com/eclipse-theia/theia?
