### ISSUE TITLE
Gitpod workspace unable to start

### ISSUE THREAD

**Issue by domsq** [gitpod-io/gitpod#8042]
### Bug description

When trying to load a workspace, I'm getting the error "Oh, no! Something went wrong!
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2576980378, used: 65006469130, capacity: 66388508672".

### Steps to reproduce

Navigate to https://gitpod.io/workspaces, locate workspace "blue-condor-ttglki79" and click it to try get it to load. I only have the option to "Open" the workspace, I'm unable to "Stop" it and then try opening it again. 

### Workspace affected

blue-condor-ttglki79

### Expected behavior

The workspace should go through loading up and then open.

### Example repository

![Gitpod error (boutique ado)](https://user-images.githubusercontent.com/80973656/152566953-2480c403-1f2e-42be-a658-614703f97076.JPG)

**Comment by pawlean** [comment]
Can you open a new workspace from that same context by any chance?

**Comment by atduarte** [comment]
Looks like another occurrence of https://github.com/gitpod-io/gitpod/issues/7969 😞 

Will close to avoid duplication, but feel free to reopen in case I missed something
