### ISSUE TITLE
Unable to ssh via magicdns name using tailscale

### ISSUE THREAD

**Issue by johnnyfleet** [gitpod-io/gitpod#8049]
### Bug description

I have been using tailscale for a while now from gitpod and working well. However I noticed today that I'm unable to ssh using the dns names - only tailscale ip. 

I've checked using tailscale set up on local vm and that works fine so suggests something wrong with how it is running in gitpod? 

### Actual behaviour

```bash 
gitpod /workspace/template-tailscale $ ssh <user>@<tailscale-machine-name>
ssh: Could not resolve hostname <tailscale-machine-name>: Name or service not known
gitpod /workspace/template-tailscale $ ping <tailscale-machine-name>
ping: <tailscale-machine-name>: Name or service not known
gitpod /workspace/template-tailscale $ tailscale ping <tailscale-machine-name>
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 454ms
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 167ms
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 168ms
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 168ms
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 168ms
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 165ms
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 168ms
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 168ms
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 166ms
pong from <tailscale-machine-name> (<tailscale-ip>) via DERP(syd) in 168ms
direct connection not established
```

### Steps to reproduce

Navigate to [https://github.com/gitpod-io/template-tailscale](https://github.com/gitpod-io/template-tailscale) and fire up an instance of gitpod.
Log in to tailscale using the auth link in the terminal.
`tailscale status` shows connected and list of machines connected.
Attempt to ssh into another machine. 

### Workspace affected

https://gitpodio-templatetailsca-c3sjdf8e9ou.ws-us30.gitpod.io/

### Expected behavior

`ssh <user>@<tailscale-machine-name>` successful
`ping <tailscale-machine-name>` successful
`tailscale ping <tailscale-machine-name>` successful

### Example repository

See steps to reproduce above

**Comment by DentonGentry** [comment]
I doubt the fix for https://github.com/tailscale/tailscale/issues/3531 will be applicable here, that one is very specific to systemd-resolved which I don't think gitpod uses.

A couple things would be useful:
- during a time when MagicDNS isn't working, please run "tailscale bugreport" from a shell and send the output to support@tailscale.com. That gives us a point in telemetry to look at.
- what are the contents of /etc/resolv.conf when the problem is happening? We'd expect to see `nameserver 100.100.100.100`

**Comment by johnnyfleet** [comment]
Hi there @DentonGentry - I've just tried again using the steps I outlined in the issue summary. 

I've emailed the bug report to the support email. 

RE: The contents of /etc/resolv.conf:

```bash
gitpod /workspace/template-tailscale $ cat /etc/resolv.conf 
nameserver 1.1.1.1
nameserver 8.8.8.8
```

**Comment by DentonGentry** [comment]
I started a gitpod from https://gitpod.io/#https://github.com/gitpod-io/template-tailscale and see similar behavior, the /etc/resolv.conf file contains:
```
nameserver 1.1.1.1
nameserver 8.8.8.8
```

The tailnet configuration has a Split DNS domain configured, which the basic Linux /etc/resolv.conf cannot express, so it should contain:
```
nameserver 100.100.100.100
```
and have tailscaled functioning as a recursive proxy.

In the tailscaled tab I see an error: `health("router"): error: setting up filter/ts-input: running [/usr/sbin/ip6tables -t filter -N ts-input --wait]: exit status 3: ip6tables v1.8.4 (legacy): can't initialize ip6tables table 'filter': Table does not exist (do you need to insmod?)`

and I wonder if this is making a routine within tailscaled return early before finishing configuration of the local system.

**Comment by johnnyfleet** [comment]
Hi all - I've just checked after the prompt above and still seem to have the same behaviour.

**Comment by WesleyMConner** [comment]
I too am unable to ssh from Gitpod to non-Gitpod with MagicDNS. I had abandoned MagicDNS, but am giving it one more try to see if I can work past the issues. If helpful, note that I am using `tailscaled` on the macOS hosts below.

Steps

(1) I re-enabled Magic DNS.

(2) I **AM ABLE** to ssh (in either direction) between an iMac and M1 Mini (i.e., from Mac-to-Mac). In `.ssh/known_hosts`, I see fresh `ecdsa-sha2-nistp256` entries which differ from what I see when pushing SSH credentials manually between the two hosts.

(3) I **AM NOT ABLE** to ssh from a Gitpod shell to either macOS.

    (a) `$ ssh x@y`
        ssh: Could not resolve hostname y: Name or service not known
        No change if I use the fully-resolved hostname.

    (b) `tailscale ssh x@y`
        No ECDSA host key is known for `y.<fully-scoped-name-here>` and you have requested strict checking.
        Host key verification failed.
        No change if I use the fully-resolved hostname.

In both cases, no new files or entries appear in `/home/gitpod/.ssh`.

The inability to ssh from gitpod to macOS persists:

  * Across stop/start of a Gitpod instance, with a fresh Tailscale approval.
  * For newly-generated Gitpod instances (where the Gitpod workspace is built from scratch).

Consistent across all of the above, `etc/resolve.conf` has Google DNS entries, but no entry for `100.100.100.100`.

  nameserver 1.1.1.1
  nameserver 8.8.8.8

I have bug dumps from step 3 above and the latest Gitpod workspace if helpful.

**Comment by WesleyMConner** [comment]
Updated re: recommended `.gitpod.Dockerfile` and `.gitpod.yml`.

**Comment by WesleyMConner** [comment]
As noted by [DentonGentry](https://github.com/DentonGentry), I too see the "can't initialize ip6tables table 'filter'" message. That could tie back to the Tailscale issue - https://github.com/tailscale/tailscale/issues/391.

I have also noticed that calls to `ssh-keyscan -t ed25519 <hostname>` produce consistent results on all participating Tailscale nodes with the exception of Gitpod. So, perhaps ssh itself has config issues in Gitpod.

**Comment by DentonGentry** [comment]
Fixing ip6tables allows MagicDNS to work again: https://github.com/gitpod-io/template-tailscale/pull/7
