### ISSUE TITLE
[jetbrains] don't infer vscode section

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#8050]
For JB users (has JB product as default editor) or JB workspaces (started with JB product as default) we should NOT infer any vscode configurations in .gitpod.yml.

cc @svenefftinge

**Comment by jldec** [comment]
@akosyakov confirming that this is a perception issue only - including vscode extensions does not create any problems besides noise in the file and a bit of "what the hey is that doing there??" for some users.

cc @loujaybee

**Comment by akosyakov** [comment]
Yes, it is not about technical issues, but respecting user preferences: JB user opens the project and then he see that we put a file in his project with VS Code configurations.

**Comment by jldec** [comment]
Scheduled this assuming it is a simple enhancement to our gitpod.yml inference logic.

**Comment by geropl** [comment]
@akosyakov This would also include storing info about the IDE in `WorkspaceInstance`, right? AFAIK we only store docker image digests so far.

**Comment by akosyakov** [comment]
> @akosyakov This would also include storing info about the IDE in WorkspaceInstance, right? AFAIK we only store docker image digests so far.

I have not looked at the code honestly. It is just bound to a user then you can check user settings. If it is bound to a workspace on the startup it should be possible to figure out what will be injected, if it is bound to already created workspace instance then yes we need this information then.

**Comment by svenefftinge** [comment]
In case it turns out to be hard to pass the information down the inferred, we can generally disable the extension inference for now.
