### ISSUE TITLE
Change GitpodWorkspaceTooManyRegularNotActive to an alert and update criteria

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8051]
## Is your feature request related to a problem? Please describe

[The current warning](https://github.com/gitpod-io/gitpod/blob/main/operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet#L62) goes unnoticed (as it is a warning and does not page), and fires too frequently.

## Describe the behaviour you'd like

Change the warning to an alert (which pages), and alter the criteria so it triggers well, and create a related runbook.

## Describe alternatives you've considered

This seems like it might work well `rate(gitpod_ws_manager_workspace_activity_total{active="false"}[1h]) > .3`

## Additional context

Look at the last 14 days in Grafana to get a feel for what that might look like.

**Comment by princerachit** [comment]
We had a spike today which was followed by stuck in stopping state 
![image](https://user-images.githubusercontent.com/32481722/152991415-fc71bd6c-ae38-4b13-9fd5-d66b3ef2ec16.png)
