### ISSUE TITLE
Workspace won't load 

### ISSUE THREAD

**Issue by gemmaellis16** [gitpod-io/gitpod#8058]
### Bug description

HI there, my workspace is stuck on this, this morning can you help me please? 
It says - 

Oh, no! Something went wrong!
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2576980378, used: 65006469130, capacity: 66388508672

### Steps to reproduce

Not sure 

### Workspace affected

lavender-mockingbird-lwvgnui0

### Expected behavior

![Screenshot 2022-02-07 at 08 42 21](https://user-images.githubusercontent.com/86297440/152753728-f381a98b-caf4-42ad-a5ab-bf4a8d8a66da.png)

**Comment by kylos101** [comment]
Hey @gemmaellis16 , thank you for sharing this report, we're actively looking into this issue in #7969, therefore I am going to close this as a duplicate. May I ask you to subscribe in #7969?

CC: @princerachit
