### ISSUE TITLE
intellisense support

### ISSUE THREAD

**Issue by ghost** [gitpod-io/gitpod#806]
Add support for IntelliSense from vscode
I expected the suggestions that pop up as you type
![Screenshot 2019-09-23 at 4 43 34 PM](https://user-images.githubusercontent.com/54449647/65465251-661d6400-de21-11e9-9dac-70798da7c805.png)

**Comment by svenefftinge** [comment]
It is supported. Please explain what you tried and expected.

**Comment by Blurryface05** [comment]
I expected the suggestions that pop up as you type

**Comment by jankeromnes** [comment]
@Blurryface05 in theory, if you open the same project and file in Gitpod as in VS Code, the same suggestions should pop up as you type.

If they don't, that's a bug -- in that case please give us a way to reproduce the bug, e.g. by providing a link to a repository, and with a specific file name, and specific place in the code where you type and nothing pops up (you could also make a screenshot or screencast to demonstrate the problem).

**Comment by jankeromnes** [comment]
Closing as duplicate in favor of #820.
