### ISSUE TITLE
Users can not re-add git integrations that have been removed

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#8063]
### Bug description

When a Git integration with a self hosted GitLab instance gets removed, users cannot add the same Git integration back.

Cc @laushinka because we ran into this while testing https://github.com/gitpod-io/gitpod/pull/7946.

<img width="529" alt="Screenshot 2022-02-07 at 12 17 50 PM (2)" src="https://user-images.githubusercontent.com/120486/152774752-52876162-b588-4dc7-83a9-517333980cd9.png">

### Steps to reproduce

1. Add a new integration with a self hosted GitLab instance in `/integrations`
2. Remove the newly added integration
3. Try re-adding the same integration

**Comment by gtsiolis** [comment]
@laushinka I could not reproduce this again, feel free to close this if you also cannot reproduce it. 🏓

**Comment by laushinka** [comment]
> @laushinka I could not reproduce this again. Closing this, but feel free to re-open this if you also reproduce the issue. 🏓

Oh, good to know, thanks! Hope I don't run into it again 🤗
