### ISSUE TITLE
preview not correctly updating

### ISSUE THREAD

**Issue by Kamicoda** [gitpod-io/gitpod#807]
**Describe the bug**
i changed my .css file and the preview is still showing the old unchanged version

**To Reproduce**
load up a simple website makes changes to the css file and hit preview, then go backinto your css file chang somthign and hit refresh, nothing changes and the google dev tools still show you the old changes

**Expected behavior**
a refresh should load the new changes on the google dev tools
![Capturebug](https://user-images.githubusercontent.com/49691906/65423832-ef24a300-de01-11e9-9ada-1372424ea84b.PNG)

**Comment by svenefftinge** [comment]
You should use a small web server that does the hot reloading on file change.
See for instance: https://github.com/tapio/live-server#installation
