### ISSUE TITLE
Error "Could not find git on the PATH"

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#808]
I get Error "Could not find git on the PATH"

<img width="511" alt="image" src="https://user-images.githubusercontent.com/239422/65509103-ffa44e80-ded1-11e9-996d-129caf7661ae.png">

when opening https://github.com/surevine/metre in gitpod.

In the Terminal, git is available. The repo uses standard `workspace-full` (no `.gitpod.yml`) and has a `.gitmodules`.

**Comment by geropl** [comment]
Workaround for now: Reload the page (`F5`).

**Comment by jankeromnes** [comment]
Yes, this seems to happen intermittently. I've seen it with the Theia repository once, but it was on a train (so intermittent connectivity via my phone), and during a Gitpod stress-test, so I'm not sure what actually triggered it.

**Comment by jankeromnes** [comment]
Just happened to me again in Theia. Also, I wasn't able to fork, maybe that's related? (Couldn't reproduce the fork problem otherwise, but the error message in the console was something like "couldn't read origin".)

**Comment by svenefftinge** [comment]
In production now
