### ISSUE TITLE
Design improvements for the new "New Workspace" modal

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8088]
## Suggested improvements
Based on [discussion](https://www.notion.so/gitpod/WebApp-design-sync-Feb-10-2022-0b45d55d7a2749beb9325a5b0fa28b11#14c19ede17794925951bafe1f971ab1a) (internal)

1. **Recover behavior to show recents by default** ([#8380](https://github.com/gitpod-io/gitpod/pull/8380) ✅)
    - Autopopulate results even when input is empty
    - Tweak result ranking to show recents first
    - Remove current help text
    - Set placeholder = “Paste repository URL or type for suggestions”

2. **Result rendering** - visually break down repo URLs into multiple lines
    
    For results based on existing repositories: 
    
    > `repo-name`
    > `<git provider>/<org-or-user-or gitlab-group...>` (wrapped?)
    > `issue-pr-commit-context` (optional?)
    > 
    
    For pasted URLS:
    
    > `https://pasted-url/...`
    > 
    
3. **Modal UX and styles**
    - grey background [[1](https://github.com/gitpod-io/gitpod/pull/7715#discussion_r797552602)]. 
    - text input consistency: focus/active state colors
    - bold grey vs soft grey selection
    - tweak modal size (may affect all modals - ok)
    - (lower priority - only if time permits) results found at bottom vs. infinite scroll
    - make sure the scrolling area is clear to the user[[1](https://github.com/gitpod-io/gitpod/pull/7715#discussion_r797552602)]
    
4. (Optional) Results visual differentiation 
    - history / recent worspaces
    - own repos
    - examples

## Current design

<table><tr><td>
<img width="524" alt="Screenshot 2022-02-08 at 12 10 53" src="https://user-images.githubusercontent.com/599268/152976080-bedf06cb-cc76-46ac-927d-1e0927a76217.png">
</td><td>
<img width="521" alt="Screenshot 2022-02-08 at 12 13 43" src="https://user-images.githubusercontent.com/599268/152976236-8ab5eccf-b181-4ab1-82fb-9c83ef6eab31.png">
</td><td>
<img width="521" alt="Screenshot 2022-02-08 at 12 12 49" src="https://user-images.githubusercontent.com/599268/152976084-6b6f5f86-428d-405b-9c99-d1a10668cac2.png">
</td><td>
<img width="517" alt="Screenshot 2022-02-08 at 12 14 10" src="https://user-images.githubusercontent.com/599268/152976240-790376df-875f-4507-86ef-32e9dac64733.png">
</td></tr></table>

**Comment by jankeromnes** [comment]
We could also bake in [this requirement](https://github.com/gitpod-io/gitpod/issues/7554#issue-1099658469):

> - [ ] A larger, cleaner user interface

I think we could even make all modals a bit larger, as [suggested](https://gitpod.slack.com/archives/C02EN94AEPL/p1643971961919849) (internal) by @geropl:

> :thread:  While having a look at https://github.com/gitpod-io/gitpod/pull/7715 in noticed something that is tickling me for a while now: Can we make our modals a tad bigger? :upside_down_face:
> 
> IMO that would help with:
> settings focus on the modal
> auto-wrap of context URLs in various places
> the "cramped" feeling the modal gives

**Comment by jankeromnes** [comment]
Cool suggestion from @felladrin on [Slack](https://gitpod.slack.com/archives/C02EN94AEPL/p1644420170539039) (internal):

In the modal's current empty state, the text "Example repositories" could be a link, which either:

- 🅰️ pre-fills the input with `gitpod-io/template-` to show all example repos, or

- 🅱️ links to our public index of example repos: https://www.gitpod.io/docs/quickstart#templates

| Current empty state | Proposal 🅰️ (pre-fill) | Proposal 🅱️ (link) |
| --- | --- | --- |
| <img width="528" alt="Screenshot 2022-02-09 at 17 05 33" src="https://user-images.githubusercontent.com/599268/153235130-3b3532cd-1a38-4fe1-8012-8c4629e8b6ea.png"> | <img width="521" alt="Screenshot 2022-02-09 at 17 31 38" src="https://user-images.githubusercontent.com/599268/153235136-97891a29-fdec-421b-afdf-b7c2622ec8b2.png"> | <img width="754" alt="Screenshot 2022-02-09 at 17 34 50" src="https://user-images.githubusercontent.com/599268/153235139-870569a4-58b0-49a1-868e-be52ba5af156.png"> |

**Comment by felladrin** [comment]
Another suggestion: disable spell checking, autocomplete, and autocorrect on the input field, by adding these attributes to the html input tag:  `autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"`

**Comment by jldec** [comment]
@jankeromnes  - I have updated the description above based on our discussion.
@gtsiolis - If you have a figma design which which matches the new outlined changes, please add image inline above.

**Comment by gtsiolis** [comment]
Closing this as the next iteration for improving the new workspace modal has been added in https://github.com/gitpod-io/gitpod/pull/15389. Cc @svenefftinge 

There are still lots of improvements we could make like structure and visual improvements, but I'll close this as this issue lacks a clear problem statement and proposal.
