### ISSUE TITLE
[integration-test] Load test proc mount in a workspace

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#8098]
## Is your feature request related to a problem? Please describe
On several occasions we have broken Docker containers in a workspace due to intermittently failing proc mounts, e.g. due to libseccomp issues (see #7793). We've seen reports that the problem seems to persist https://github.com/gitpod-io/gitpod/issues/8070.

We must add an integration test which runs the proc stress test (mount `/proc` in a mount namespace) to detect this issue before bringing it to prod.

**Comment by kylos101** [comment]
Once this is implemented, assuming you can now recreate proc mount failures roughly 10% of the time, schedule #8070.
