### ISSUE TITLE
Add Xtend support

### ISSUE THREAD

**Issue by kuniss** [gitpod-io/gitpod#81]
Please!

**Comment by kuniss** [comment]
You may check adding Xtend highlighting support, I created as VS code extension:  https://marketplace.visualstudio.com/items?itemName=Grammarcraft.xtend-lang
:-)

**Comment by kuniss** [comment]
@svenefftinge, @akosyakov, you may update to version 0.4.0. It now comes with an embedded, simple Xtext LS which allows better grammar file-internal navigation, hovering and so on. 

However, external reference resolving is not supported. To avoid an overwhelming error message flood due to that, the linking diagnostic is disabled (by configuration).
Nevertheless, worth to be integrated due to the other features, I think.

**Comment by svenefftinge** [comment]
Cool you keep working on it. We hope we can publish a first version with Vs code extension support pretty soon. So you can always update to the latest version yourself.

**Comment by kuniss** [comment]
Every one can add the Xtend syntax highlighting extension by him/herself: Available via  https://open-vsx.org/extension/grammarcraft/xtend-lang

Implementing an Xtend language server is by far more difficult according to @svenefftinge as workspace sharing between LS is not supported yet. However, as Xtend transpiles to Java something similar would be needed.

Therefore, going to close this issue.
