### ISSUE TITLE
No ports open on `workspace-full-vnc`

### ISSUE THREAD

**Issue by sasdallas** [gitpod-io/gitpod#8102]
### Bug description

I cannot access the VNC server in my gitpod workspace. `.gitpod.yml` is configured to run image `workspace-full-VNC`, but no open ports are listed. This is really weird, because it was working before.

### Steps to reproduce

1. Stop your GitPod workspace
2. Start your GitPod workspace
3. No open ports

### Workspace affected

workspace-full-vnc

### Expected behavior

VS code should point out that port 6080 is open.

### Example repository

[My repository](https://github.com/sasdallas/reduceOS)

[Workspace snapshot](https://blue-frog-6x8aotm1yqp.ws-us30.gitpod.io/)

### Anything else?

I have tried running it in `.gitpod.Dockerfile`.

The code for `.gitpod.yml`:
```
[gitpod generated code]

Image: gitpod/workspace-full-vnc

```

**Comment by jankeromnes** [comment]
Hi @sasdallas!

Looking at your repository's [`.gitpod.yml` commit history](https://github.com/sasdallas/reduceOS/commits/main/.gitpod.yml), I see three relevant changes (from oldest to latest):

1. Use base image `gitpod/workspace-full` (no VNC): https://github.com/sasdallas/reduceOS/commit/72c11b5595eb92b3d8ac03d3f99976ddfa968da0
2. Use base image `gitpod/workspace-full-vnc` (with VNC, i.e. should work as expected): https://github.com/sasdallas/reduceOS/commit/031e089b8d25900dcec1d07464853dd73f4db437
3. Delete `.gitpod.yml` (revert back to Gitpod's default image): https://github.com/sasdallas/reduceOS/commit/93a6bcd703e6f9743945701db8157aac77fa7e8c

So, at the time of commits 1. and 3., your repository was/is not using VNC.

However, at the time of commit 2., your repository was supposed to use `gitpod/workspace-full-vnc` and get the VNC port 6080 as open.

When I test this by opening that specific commit in Gitpod:

https://gitpod.io/#https://github.com/sasdallas/reduceOS/commit/031e089b8d25900dcec1d07464853dd73f4db437

It seems to work as expected (i.e. port 6080 is open, and opening a preview shows the noVNC graphical interface):

<img width="1440" alt="Screenshot 2022-02-08 at 18 36 34" src="https://user-images.githubusercontent.com/599268/153044591-65c9baf1-4ffd-4020-95aa-e10b9b8f2ccf.png">

I would suggest restoring `.gitpod.yml` and `.gitpod.Dockerfile` to the same state they were in commit https://github.com/sasdallas/reduceOS/commit/031e089b8d25900dcec1d07464853dd73f4db437

**Comment by sasdallas** [comment]
Hi, @jankeromnes.\
Thanks for reaching out!

I tried to restore `.gitpod.yml` and `.gitpod.Dockerfile` from that commit, then stopped and started the workspace again, but it didn’t update. I’m not sure why.

**Comment by sasdallas** [comment]
Oh, and also, those files were removed because of `.gitignore` I think.

**Comment by jankeromnes** [comment]
Hi @sasdallas!

> I tried to restore `.gitpod.yml` and `.gitpod.Dockerfile` from that commit, then stopped and started the workspace again, but it didn’t update. I’m not sure why.

Ah, simply restarting an existing workspace won't work for Dockerfile changes -- for this, you'll need to actually:

1. commit the `.gitpod.yml` and `.gitpod.Dockerfile` files again (you may indeed need to remove them from `.gitignore` first)
2. push this commit to your repository
3. create a new workspace based on the new changes

(For stability reasons, restarting an old workspace will always give you the original configuration from when it was created -- no matter if your repository has a different Dockerfile now.)

**Comment by sasdallas** [comment]
@jankeromnes ah, that makes sense! I will try that right now.

**Comment by sasdallas** [comment]
@jankeromnes Thanks so much!\
Can’t believe all I had to do was make a new workspace on the branch.

**Comment by jankeromnes** [comment]
@sasdallas You're quite welcome! Hope this helps 🙂

Also, I took the liberty to send you a [Pull Request](https://github.com/sasdallas/reduceOS/pull/2) with what a fully-automated dev setup might look like for your project. Feel free to use it for inspiration or to discard it as seems best. 😁
