### ISSUE TITLE
[docker] Support arguments to Docker daemon

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#8103]
## Is your feature request related to a problem? Please describe
We automatically start the Docker daemon when it's needed in the workspace. Currently users cannot provide their own arguments to that daemon, which bars them from using things like [userns-remap](https://docs.docker.com/storage/storagedriver/vfs-driver/). We should provide a way for folks to add those arguments.

## Describe the behaviour you'd like
One of those options:

1. A special environment variable which we consume and add, e.g. `DOCKER_ARGS`
2. Part of the `.gitpod.yml`
3. A magic file that we read prior to starting the Docker daemon

**Comment by kylos101** [comment]
[This is a nice reference PR which @Furisto and I found](https://github.com/gitpod-io/gitpod/pull/7063/files), which shows how to add data to the `.gitpod.yml`, and then make it possible to use that related data in a workspace as an environment variable.

[Also, here are the args supported by dockerd.](https://docs.docker.com/engine/reference/commandline/dockerd/) Some of the args can repeat (ones with `[]`), and others cannot. If we want to support args that can repeat, I think that means the value for `DOCKER_ARGS` must be an array of key value pair objects.

To start, I think it would be good to support the `userns-remap` arg. And if there is demand to set additional args, circle back to this and add that additional support based on the related demand.

**Comment by utam0k** [comment]
I reopened this issue because we have to add the documentation about how to use the new `DOCKERD_ARGS` .
https://github.com/gitpod-io/gitpod/pull/8435#issuecomment-1051546203

**Comment by kylos101** [comment]
Thank you, @utam0k !  I've also moved this issue's status back to in-progress. Good catch.

@Furisto can you look at Mike's comment about adding documentation? My preference would be to add a new section on the existing environment variables page (for now).

**Comment by utam0k** [comment]
How about a field to pass arguments directly to dockerd without any conversion?
e.g. `{ "userns-remap": "gitpod:gitpod", "direct": ["--add-runtime", "gitpod", "--debug"]  }`
(I want to get a better field name 😭 )
