### ISSUE TITLE
Support Git LFS during content init

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#8105]
## Is your feature request related to a problem? Please describe
During content initialisation we should support Git LFS, i.e. install it [here](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/leeway.Dockerfile#L17)

## Describe the behaviour you'd like
Git LFS should just work

**Comment by jmls** [comment]
this is a serious roadblock for us :(
