### ISSUE TITLE
[installer] Rename and print OR remove `--danger-use-unsupported-config` flag

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#8107]
### Bug description

when using experimental settings in installer, error message is not very helpful. 
would be good to tell user how to enable experimental options in that message.
Also, after digging through source code I did find the switch for it: 
`-danger-use-unsupported-config   enable use of unsupported config`
which doesn't mention anything that it enables experimental settings.

### Steps to reproduce

```
./gitpod-installer render --config overrride-values.yaml > manifests.yaml
config contains experimental options - ignoring them
```

**Comment by metcalfc** [comment]
This is a rough UX. Can we change to flag to something that connects it to `experimental` ? 

```--enable-experimental-config```

The user of the installer is considered someone who is ok with low-level access and is often other Gitpod folks. I think the safety is good but we should still make it easy. To go with this, when we warn folks lets tell them how to fix it, ie add the flag vs just ignore it.

If folks have experimental config sections in their YAML, chances are they want to use them. Should we just bail at this point and emit the warning that they should re-run with the flag or remove the experimental config?

**Comment by corneliusludmann** [comment]
> If folks have experimental config sections in their YAML, chances are they want to use them. Should we just bail at this point and emit the warning that they should re-run with the flag or remove the experimental config?

Given that the main config surface for most people out there should be the Replicated UI and that the term “experimental” in the config file should be warning enough, I would also vote for removing the flag entirely.

**Comment by MrSimonEmms** [comment]
> I would also vote for removing the flag entirely.

I think I would respectfully disagree. The experimental config is not for most users (truthfully, it's mostly for SaaS) and there's a danger that people read "experimental" as "beta" or "this is some brilliant stuff that's coming in the future - use it now to be bleeding-edge" which it absolutely isn't.

It's unsupported configuration which allows users to go outside the tracks of the Installer's framework

**Comment by corneliusludmann** [comment]
OK, convinced me. In particular, I think @csweichel's [argument](https://github.com/gitpod-io/gitpod/pull/8477#issuecomment-1053985130) is key:
> Say you get config sent to you, don't really understand it in detail, then this flag will make (hopefully) make you stop and think for a second.
