### ISSUE TITLE
Error while adding gitpod layer

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#813]
**Describe the bug**
After a successful workspace build got an unfamiliar error Error: Error while adding Gitpod layer.
**To Reproduce**
 here is the URL https://gitpod.io/#https://github.com/JesterOrNot/nushell just open it.
**Expected behavior**
start workspace normally

**Comment by JesterOrNot** [comment]
fixed it sorry

**Comment by jankeromnes** [comment]
@JesterOrNot Cool that you fixed it! Just curious, what was the problem? (Maybe others will run into the same situation in the future, and stumble upon this issue.)

**Comment by JesterOrNot** [comment]
I was trying to create a gitpod area for a project I was starting and I noticed they had some docker images already created so I tried to use the docker image they had and when I tried it built the image successfully but gave an error saying failed to build on gitpod layer here is the URL to the project github.com/nushell/nushell

**Comment by jankeromnes** [comment]
Thanks a lot for the additional infos @JesterOrNot!

I see that nushell's [Dockerfile](https://github.com/nushell/nushell/blob/master/docker/Dockerfile) is based on `FROM ubuntu:18.04`, which should in theory be supported by Gitpod.

So this looks indeed like a bug in Gitpod! Thank you for reporting it.

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/66274389-c231b080-e843-11e9-8fa2-143785dca588.png)
This happened with google cloud shell image here is the image URL
https://github.com/JesterOrNot/Gitpod-Test

**Comment by jankeromnes** [comment]
@JesterOrNot Thanks for reporting this. These problems happen when the underlying Docker image differs from what Gitpod expects, i.e. a Ubuntu or Debian image, with a user called `gitpod`, and I think there are a few other assumptions that we haven't documented yet.

Do you know what OS the `gcr.io/cloudshell-images/cloudshell:latest` image is based on? I noticed a few `apt-get` occurrences, so probably an Ubuntu/Debian-like, but I couldn't find more info.

**Comment by JesterOrNot** [comment]
Here is the uname -a output: Linux cs-6000-devshell-vm-1a7247f9-8133-45f1-a247-ca0f33402e7a 4.19.72+ #1 SMP Thu Sep 26 23:10:22 PDT 2019 x86_64 GNU/Linux

**Comment by JesterOrNot** [comment]
https://gitpod.io/#https://github.com/JesterOrNot/android-test
FROM ubuntu:17.10
in base image

**Comment by JesterOrNot** [comment]
another one here
https://gitpod.io/#https://github.com/JesterOrNot/Gitpod-Docker

**Comment by JesterOrNot** [comment]
What can be done about these issues?

**Comment by JesterOrNot** [comment]
Ooh heres one where the base image is gitpod/workspace-full
https://github.com/JesterOrNot/gosh/tree/test

**Comment by svenefftinge** [comment]
> @svenefftinge @jankeromnes Ooh heres one where the base image is gitpod/workspace-full
> https://github.com/JesterOrNot/gosh/tree/test

This one seem to work nicely, though.

**Comment by JesterOrNot** [comment]
oh sorry at the time of writing, it had failed

**Comment by bangyogesh** [comment]
I have been experimenting with kalilinux and trying to create the environment in gitpod using base image of kalilinux.
During the container image build, it fails with the error
"Error: Error while adding Gitpod layer."

The URL to create the container is https://gitpod.io/#https://github.com/bangyogesh/kalilinuxdev .

The screenshot of the error is attached herewith
![image](https://user-images.githubusercontent.com/2494368/68004507-c9f44180-fc97-11e9-966a-823c3faf3a1b.png)

**Comment by JesterOrNot** [comment]
So say the issue is with the base image what do we do about it?

**Comment by bangyogesh** [comment]
@JesterOrNot 
> So say the issue is with the base image what do we do about it?

I tried building the docker image using the same dockerfile and it worked perfectly on my local Ubuntu box (as explained in above post, it fails with gitpod). 
How to know if Gitpod layer has issue with base-image and what corrective action needs to be taken ?

**Comment by JesterOrNot** [comment]
here is a link to an alpine based image that works
https://hub.docker.com/r/szczepano/v-alpine/dockerfile
and a example repo
https://github.com/JesterOrNot/Gitpod-V/

**Comment by JesterOrNot** [comment]
So to solve this we could try to get the gitpod image builder to recognize other distros how does the builder do that @svenefftinge

**Comment by RossComputerGuy** [comment]
![image](https://user-images.githubusercontent.com/19699320/68709677-0a32aa00-054b-11ea-9ec0-ca345c80d8cc.png)
My repository is failing which uses `archlinux/base`. (https://github.com/RossComputerGuy/stardustos)

**Comment by geropl** [comment]
@RossComputerGuy We currently support debian and alpine based distros only.

**Comment by meysholdt** [comment]
Can we close this issue and create "Support distro foobar" issues instead for the linux distros we could potentially support?

**Comment by RossComputerGuy** [comment]
Why only debian and alpine? There'll be some cases where Arch based ones are needed and this is one.

**Comment by jankeromnes** [comment]
> Why only debian and alpine? There'll be some cases where Arch based ones are needed and this is one.

Gitpod needs to make a few changes to Docker images to ensure that they work properly (i.e. checking that there is a non-root `gitpod` user, that required tools and language servers are installed, things like that).

Since we're familiar with Debian and Alpine, we maintain Gitpod-specific instructions for both distros (i.e. we adapt the instructions when we notice bugs with them), but we haven't done that work for other distros yet.

I think we could support more distros though. A good way to request it would be to create a "Support distro X" issue, as suggested by Moritz.

**Comment by JesterOrNot** [comment]
How can the community help bring this support to gitpod?

**Comment by Kreyren** [comment]
any info on this? I'm very slowly losing my mind and table over using apt >.<

**Comment by JesterOrNot** [comment]
I will ask my colleagues when they are back @Kreyren

**Comment by Kreyren** [comment]
@JesterOrNot any info on this? I would like to use paludis docker for paludis downstream development

**Comment by JesterOrNot** [comment]
We don't have the resources right now. However, if you don't like APT you can use some Alpine based images where you can use APK.

**Comment by Kreyren** [comment]
@JesterOrNot Elaborate on the resources?
