### ISSUE TITLE
Timeout Limit Increase /w Mutiple GitPod Instances

### ISSUE THREAD

**Issue by jonathan-wondereur** [gitpod-io/gitpod#8138]
## Is your feature request related to a problem? Please describe
I am frustrated that I can not extend the workspace timeout on two projects at the same time. I work on one project that has two GitPod instances, one for the front end and one for the backend. When I toggle on the extended timeout for one project it disables it for the other. This can be quite frustrating, especially if I am doing a lot of work on one of them and the other times out.

## Describe the behaviour you'd like
I would like to be able to configure the timeout for the projects to always be three hours, and to have at least two open projects with a workspace timeout of three hours.

**Comment by jonathan-wondereur** [comment]
@atduarte this new feature is indeed interesting, I will take a look once it is out of beta.

However, I am still having issues where I do not think the timeouts are working as intended.

It seems to work okay for the morning, but when I come back after lunch I start working and within 5-10 min the workspace that I am actively working on times out.

**Comment by atduarte** [comment]
That should not be happening. Could you please open a separate issue with details on how to reproduce? 🙏
