### ISSUE TITLE
Better debug support

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#814]
Add better debugger support for different languages like java and python and go at this time I can't get it to work

**Comment by jankeromnes** [comment]
Hi @JesterOrNot, sorry that debugging didn't work for you. Could you please let us know what exactly you tried; what you expected; and what you saw instead?

Debugging should already work well for Java, and here is a screencast showing it in action: https://youtu.be/Q8ybNNkMtZ0?t=1530

It should also work well with Python and Go, although I don't currently know good screencasts or tutorials for that. We're also working on bringing debugging to more languages.

See also #156, #161, #370, #488, #544, #785.

**Comment by JesterOrNot** [comment]
Using this configuration
      {
          "type": "java",
          "name": "debug java",
          "request": "attach",
          "hostname": "localhost",
          "port": 9
      }
I tried starting the debug and nothiing happened can you give me the configuratin that is working for you

**Comment by jankeromnes** [comment]
I believe the configuration used in the video is https://github.com/gitpod-io/spring-petclinic/blob/master/.vscode/launch.json

Hope it helps! I can take a closer look at the differences tomorrow.

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/65921593-4bf6ff00-e3a8-11e9-9b7f-8705753812d9.png)

**Comment by JesterOrNot** [comment]
Nevermind I got it working for future reference to anybody reading this the configuration that worked was 
      {
          "type": "java",
          "name": "Java Debugger",
          "request": "launch",
          "mainClass": "",
          "console": "internalConsole"
      },

**Comment by mikku489** [comment]
This still does not work . 

At times I see the "Run | Debug" over main method, and at times it disappears for random reasons (without any config or code changes). Please fix this properly and provide an official config, it's a big reason why I use GitPod.

**Comment by svenefftinge** [comment]
@mikku489 can you provide the language you are using? Is it Java or Go?

**Comment by mikku489** [comment]
Using Java

**Comment by JesterOrNot** [comment]
An issue with the go debugger
repo https://github.com/JesterOrNot/gosh/tree/debugger
![image](https://user-images.githubusercontent.com/50386709/70819380-b90d1480-1d9b-11ea-8673-707011f36275.png)

**Comment by entibo** [comment]
See https://github.com/MicrosoftDocs/vsonline/issues/140 for the Go debugger problem

**Comment by akosyakov** [comment]
Just fyi please start switching to VS Code: https://www.gitpod.io/docs/feature-preview/#default-ide It is going to become default rather soon.
