### ISSUE TITLE
The terminal looks weird sometime

### ISSUE THREAD

**Issue by jefer94** [gitpod-io/gitpod#8145]
### Bug description

In some time I open a gitpod and the terminal look weird
![image](https://user-images.githubusercontent.com/3018142/153492255-41d34d47-9a80-4f84-ba59-ff3876fbb08a.png)

### Steps to reproduce

I don't know

### Workspace affected

jefer94-apiv2-l5rbzma219o.ws-us31

### Expected behavior

The terminal look normal

### Example repository

https://github.com/jefer94/apiv2/tree/development

### Anything else?

No

**Comment by jefer94** [comment]
![image](https://user-images.githubusercontent.com/3018142/153493176-9ae44548-02e4-4326-b0a6-cce59fcd9ec1.png)

**Comment by axonasif** [comment]
> Duplicate of #4130?

Could be, it's either his browser config or `terminal.integrated.gpuAcceleration`

**Comment by jefer94** [comment]
Many of this configs help to resolve the problem, but this still being a bad behavior of console

**Comment by loujaybee** [comment]
Moving to scheduled to assess if the bug is in Gitpod, or an upstream issue (as before).

**Comment by alexanderkoh** [comment]
I am facing the same situation since last week. Is there any interim fix?

**Comment by jeanp413** [comment]
This is duplicate of https://github.com/gitpod-io/gitpod/issues/5014
@alexanderkoh you can try disabling brave adblocker

**Comment by kellySmi** [comment]
Is there an open ticket for this issue, as I am still experiencing it. I noticed when viewing the browser in a second monitor is when this issue occurs. Viewing the browser in my laptop display, it looks as expected.
