### ISSUE TITLE
Can I use PyQt5 with GitPod?

### ISSUE THREAD

**Issue by hidehiro98** [gitpod-io/gitpod#815]
I try to use PyQt5 in this Repo.
https://github.com/hidehiro98/alife_book_src

But got this warning.
```
WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-gitpod'
```

This looks not an error, but nothing happened.

Is there a way to solve this?

**Comment by jankeromnes** [comment]
Hi @hidehiro98, thank you for filing this issue. I believe that the warning is indeed not an error.

The reason that you don't see anything happening is that a graphical window is opened in the Virtual Desktop on port 6080.

When I opened https://github.com/hidehiro98/alife_book_src and tried these commands:

```bash
pip3 install pyglet pymunk vispy keras tensorflow pyqt5
cd chap02
python3 game_of_life.py
```

and also configured port 6080 to automatically open a preview:

```yml
ports:
  - port: 6080
    onOpen: open-preview
```

(But you can also Expose and Preview ports manually instead, directly from the bottom bar.)

I then was able to see the graphical PyQt5 window:

<img width="1552" alt="Screenshot 2019-09-30 at 12 40 30" src="https://user-images.githubusercontent.com/599268/65872045-fd356f00-e37f-11e9-8ec0-3a09f37955ab.png">

(It didn't show anything that looked like a game of life, but probably that's a different issue.)

I'll send a Pull Request to your fork, with the changes that made it work for me.

**Comment by hidehiro98** [comment]
Thank you so much @jankeromnes !
I tried it and got the same window. I'll try to display what I want to see.
I think almost there...

**Comment by jankeromnes** [comment]
I believe this can be closed now. 🎉

Please reply here if this is still an issue.
