### ISSUE TITLE
[ws-manager] Remove trailing "Please contact support..." from error messages

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#8154]
This is a dashboard/UI concern, and should not be part of the error message.

Source: https://github.com/gitpod-io/gitpod/blob/6509092ad43c0253e541b05882cab1a033da3cec/components/ws-manager/pkg/manager/status.go#L377-L378

Context: https://github.com/gitpod-io/gitpod/pull/8125#pullrequestreview-880089702

**Comment by gtsiolis** [comment]
Thanks @geropl for opening this and @sagor999 for picking this up! 🏀
