### ISSUE TITLE
Enable billing emails again with attached invoice for accounting automation

### ISSUE THREAD

**Issue by davemecha** [gitpod-io/gitpod#8165]
## Is your feature request related to a problem? Please describe

Since January 2022 you discontinued sending billing emails with the invoice attached. (In discord you mentioned this change is to reduce "spam".)

Due to this change I cannot automate my accounting for Gitpod any more. E.g. forwarding the email to my accounting tool (like kontist.com or papierkram.de) or triggering cloud functions to upload data to a drive folder. This adds manual work for me that I'd like to avoid.

## Describe the behavior you'd like

I'd like to receive emails with attached invoices again. Most of the services I work with do that and I don't understand why you consider accounting mails as spam. I'd be happy if you could restore the old behavior as soon as possible as a quick fix.

A persistent solution could be an option in the account settings to set a separate accounting email address. And additionally an option to opt out of getting invoice / accounting mails (for people who consider this as spam).

## Describe alternatives you've considered

As an alternative you could provide an API to fetch those accounting documents. But this would be less favorable since I would have to do a separate implementation for fetching Gitpod docs. Another option would be a web scraper of the Gitpod billing website. This is bad in terms of security and complexity.

## Additional context

Discord thread: https://discord.com/channels/816244985187008514/816246578594840586/940374224445534258

**Comment by JanKoehnlein** [comment]
Thanks for reporting this issue. It seems like we have customers who need these emails and others who dislike them. So we switched defaults to and fro. To account for both cases, I've added a flag in _(Team) Plans > Billing > Account Details_ ([video](https://www.loom.com/share/29e18fbf7de44a0fa669388fe26101a9)) and enabled that for you.

**Comment by davemecha** [comment]
Thanks a lot for this change. 🥳
