### ISSUE TITLE
[core-dev] registry facade in crash loop due to namespace name being too long

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#8169]
### Bug description

https://github.com/gitpod-io/gitpod/blob/8f370dc4c3da2df09c357679c5471be08799fa74/chart/templates/registry-facade-daemonset.yaml#L84

```
  Warning  FailedPostStartHook  3m33s (x3 over 3m48s)  kubelet                                Exec lifecycle hook ([/bin/bash -c kubectl label --overwrite nodes ${NODENAME} gitpod.io/registry-facade_ready_ns_${KUBE_NAMESPACE}=true]) for Container "registry-facade" in Pod "registry-facade-4s9xq_staging-sagor999-workspace-crash-loops-7754(45eff485-2c1b-416d-8665-70016b990c58)" failed - error: command '/bin/bash -c kubectl label --overwrite nodes ${NODENAME} gitpod.io/registry-facade_ready_ns_${KUBE_NAMESPACE}=true' exited with 1: The Node "gke-core-dev-workspace-2-397a333b-3fyh" is invalid: metadata.labels: Invalid value: "gitpod.io/registry-facade_ready_ns_staging-sagor999-workspace-crash-loops-7754": name part must be no more than 63 characters
, message: "The Node \"gke-core-dev-workspace-2-397a333b-3fyh\" is invalid: metadata.labels: Invalid value: \"gitpod.io/registry-facade_ready_ns_staging-sagor999-workspace-crash-loops-7754\": name part must be no more than 63 characters\n"
```

KUBE_NAMESPACE env variable has to be trimmed to make sure that resulting label name is not longer than 63 characters

### Steps to reproduce

Open the workspace from an issue with a very long name.
Observe that registry facade is in crash loop.

this is the namespace that was generated for my workspace:
`staging-sagor999-workspace-crash-loops-7754`

### Workspace affected

gitpodio-gitpod-y9237ppnuc5

**Comment by wulfthimm** [comment]
This problem is not only for namespaces but also for domain names. Both are using the branch name as basis.

**Comment by svenefftinge** [comment]
How about just cutting it off to make it fit into the 63 chars?
