### ISSUE TITLE
How do I save the workspace settings permanently?

### ISSUE THREAD

**Issue by oanstein** [gitpod-io/gitpod#817]
Whenever I open the environment again, the settings are reset.

**Comment by svenefftinge** [comment]
Hi @oanstein, workspace settings are stored as part of your repository. So you need to commit the changes in order to have them. User settings are stored with your user account and will be there in any workspace your start. Hope that helps.

**Comment by fsanterva** [comment]
I installed yarn, curl, git and neovim via sudo apt, but when timeout and open it up, all install apt are gone :( how do we solve this?

**Comment by fsanterva** [comment]
> Hi @oanstein, workspace settings are stored as part of your repository. So you need to commit the changes in order to have them. User settings are stored with your user account and will be there in any workspace your start. Hope that helps.


I installed yarn, curl, git and neovim via sudo apt, but when timeout and open it up, all install apt are gone :( how do we solve this?
