### ISSUE TITLE
Gitpod button showing inside the security vulnerability alert in GitHub

### ISSUE THREAD

**Issue by MaikoTan** [gitpod-io/gitpod#8171]
### Bug description

When the owner enabled "Dependabot alert" on Github, and open a repository that contains potential security vulnerabilities, the "Gitpod" button would be added to that alert notification instead of the right side behind other buttons.

See the screenshot:
![image](https://user-images.githubusercontent.com/19927330/153696551-94c0ed7f-3b98-4c7d-96a7-5094f9a648b2.png)

This notification seems only to show to the owner of the repo, so I can't provide any repo.

### Steps to reproduce

1. Log in to Github
2. Open a repository that contains potential security vulnerabilities
3. Open any file in Github
4. The button fly up :-)

### Workspace affected

No

### Expected behavior

Stay the button beside others.

**Comment by pawlean** [comment]
I wasn't entirely sure where this would live, my gut was to the WebApp team but please let me know if it's another one! cc @jldec

**Comment by gtsiolis** [comment]
@Siddhant-K-code Can you still reproduce this?

Looping in @alesanchezr who mentioned this is still an issue in #10360.

**Comment by alesanchezr** [comment]
I still see it inside the dependabot alert (even after re-installing the plugin and updating brave browser).

[Version 1.38.119 Chromium: 101.0.4951.67 (Official Build) (x86_64)](https://brave.com/latest/)

**Comment by sanjay-singh-patel** [comment]
Root Directory:
![image](https://user-images.githubusercontent.com/57282318/171247187-26279e7f-8ee1-4089-91b8-6689bba62cf3.png)
Inside a file:
![image](https://user-images.githubusercontent.com/57282318/171248032-d47dd2dc-9cd4-45ed-82f4-d1f5f62c7ad2.png)

Browser name = Brave
Full version = 1.39.111

**Comment by gtsiolis** [comment]
Thanks for checking, @sanjay-singh-patel and @Siddhant-K-code!

**Comment by Siddhant-K-code** [comment]
I think, We need to handle a case for `FileInjector` when there are `warn-alerts` separately.

**Comment by MaikoTan** [comment]
![image](https://user-images.githubusercontent.com/19927330/188541310-c83ae815-dcb6-4503-8f57-c7091d1f25e8.png)

Is this resolved? Still it happens on my side, I tested with Chrome / Vivaldi / FireFox, all got the same result.

**Comment by gtsiolis** [comment]
This is still an issue, @MaikoTan!

**Comment by filiptronicek** [comment]
We have not received reports since our complete rewrite for v2. Closing this for now 🙏
