### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#819]
**Describe the bug**
When trying to use the shortcut alt up instead of moving the line up like it's supposed to it moves the cursor to the top of the document 
**To Reproduce**
try using alt-up in any gitpod workspace environment
**Expected behavior**
moves line up

**Comment by jankeromnes** [comment]
@akosyakov Maybe a keyboard shortcut difference between Gitpod and VS Code? Should this be filed against https://github.com/eclipse-theia/theia/issues ?

**Comment by JesterOrNot** [comment]
Nope no difference look
![image](https://user-images.githubusercontent.com/50386709/65954010-cd7f7900-e40a-11e9-9872-47947d0dd43d.png)

**Comment by jankeromnes** [comment]
Ah, indeed thanks, so the bug is that it just doesn't work.

**Comment by JesterOrNot** [comment]
Yep!

**Comment by JesterOrNot** [comment]
Could this be because of conflicting keyboard shortcuts?

**Comment by jankeromnes** [comment]
> Could this be because of conflicting keyboard shortcuts?

Indeed, that could be the reason. Does it also not work in other browsers, e.g. Firefox?

I'll re-file this issue against the Theia IDE project, at https://github.com/eclipse-theia/theia/issues.

**Comment by jankeromnes** [comment]
Closing as duplicate in favor of https://github.com/eclipse-theia/theia/issues/6346.
