### ISSUE TITLE
VS Code Desktop Timeout Too Quickly

### ISSUE THREAD

**Issue by jonathan-wondereur** [gitpod-io/gitpod#8190]
### Bug description

Often when I am trying to connect VS Code desktop I get a timeout error with the connection before I get the prompt to accept the fingerprint of the server.

(Note the overlay that prevents me from selecting continue shows up before the notice of the fingerprint).

![image](https://user-images.githubusercontent.com/38539725/153865565-182b5f43-f867-41f3-b9b3-da0946b620af.png)

### Steps to reproduce

Connect to a new GitPod instance from VS Code desktop.

### Workspace affected

cicn3jv5gdx

### Expected behavior

Timeout to not happen before prompt to accept fingerprint.

**Comment by loujaybee** [comment]
Thanks for raising @jonathan-wondereur ! We'll be updating the connection method of VS Code desktop soon, hopefully this should resolve the issue. We'll investigate this as part of the work to bring VS Code to GA. 🙏 

- https://github.com/gitpod-io/gitpod/issues/7184

**Comment by axonasif** [comment]
> FYI: I changed the setting remote ssh use local server to false (`"remote.SSH.useLocalServer": false`) and this seems to have resolved my connection timeout issues.

Perhaps can we close the issue 🙏 ?

**Comment by loujaybee** [comment]
Linking related issue: 

- https://github.com/gitpod-io/gitpod/issues/10373

And: 

- https://github.com/gitpod-io/gitpod/issues/10288

Which would help lessen the impact of timeout issues.

**Comment by loujaybee** [comment]
As @jonathan-wondereur has confirmed the issue fixes for him, I will close the issue. @jkaye2012 if you experience similar or related issues, please re-open or add a new issue 🙏 The method for `remote.SSH.useLocalServer` is currently behind a configuration flag, but this will eventually be rolled out as default.
