### ISSUE TITLE
[jetbrains] extend IDE backend label

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#8192]
Instead we should show there Gitpod logo and workspace id. In the dropdown menu we can add common actions, see https://github.com/gitpod-io/gitpod/issues/8024

We should override com.jetbrains.rdserver.unattendedHost.customization.GatewayClientCustomization for it. It is also possible to add actions to the dropdown menu by adding your actions to the UnattendedHostDropdownGroup action group.

**Comment by akosyakov** [comment]
We had to revert it for now, since branding can cause JB backend freeze as for now: https://github.com/gitpod-io/gitpod/pull/8542 It will be improved in future versions and we can try again.

**Comment by felladrin** [comment]
Recently, JetBrains team indicated us how to make it work, so I'll note it here for us to work on it later:

On [plugin.xml](https://github.com/gitpod-io/gitpod/blob/main/components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml) add the following line inside `<extensions defaultExtensionNs="com.intellij">`:
```xml
<gateway.customization.name implementation="io.gitpod.jetbrains.remote.GitpodGatewayClientCustomizationProvider"/>
```

Then create a `GitpodGatewayClientCustomizationProvider.kt` file with the following content:
```kotlin
class GitpodGatewayClientCustomizationProvider : GatewayClientCustomizationProvider {
  override val icon: Icon = GitpodIcons.Logo
  override val title: String = "Gitpod"

  override val controlCenter: GatewayControlCenterProvider = object : GatewayControlCenterProvider {
    override fun getHostnameDisplayKind() = GatewayHostnameDisplayKind.ShowHostnameOnNavbar
    override fun getHostnameShort() = System.getenv("GITPOD_WORKSPACE_ID") ?: "Gitpod"
    override fun getHostnameLong() = getHostnameShort()
  }
}
```

Note: `GitpodIcons` is imported from [here](https://github.com/gitpod-io/gitpod/blob/main/components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/icons/GitpodIcons.kt).
