### ISSUE TITLE
[preview environment] Support combination of: with-observability + installer

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#8193]
Currently we have to use the helm chart in preview environments if we want to tests sth wrt observability.

As we're moving closer to installer being our only install option, we should support the combination `with-observability` + installer in our deploy scripts as well.

**Comment by mads-hartmann** [comment]
Scheduled this as we're going to be Installer-only in our VM environments, so might as well get this fixed now :)

**Comment by mads-hartmann** [comment]
Once this is fixed we should update [Sending traces to Honeycomb from preview environments](https://www.notion.so/gitpod/Sending-traces-to-Honeycomb-from-preview-environments-ab5c18cd588242cca9105e3e40c4c1e8)

**Comment by ArthurSens** [comment]
@mads-hartmann you have quite a [big one](https://github.com/gitpod-io/gitpod/issues/8065) refactoring our whole CI pipeline, should we wait for you to get that done? I'm afraid of merge conflicts getting in your way 😬 

Happy to help get your PR merged as soon as possible

**Comment by mads-hartmann** [comment]
@ArthurSens I'll try to get that PR merged today 🤞
