### ISSUE TITLE
[observability] node-exporter insufficient capabilities

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#8194]
I see this error when deploying with-observability: https://werft.gitpod-dev.com/job/gitpod-build-gpl-tracing-disable-errors.7#deploy:deploy
```
Error: kubectl rollout status -n staging-gpl-tracing-disable-errors daemonset node-exporter exit with non-zero status code
```
`kubectl describe ds node-exporter` shows:
```
Warning  FailedCreate  13s (x15 over 31m)  daemonset-controller  Error creating: pods "node-exporter-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.capabilities.add: Invalid value: "CAP_SYS_TIME": capability may not be added]
```
The PSP is there, but not namespaced (so overriden/re-used by every monitoring-satellite installation) and has
```
RequiredDropCapabilities:
- All
```
configured.

**Comment by ArthurSens** [comment]
I believe this is an issue from upstream. We're making kube-prometheus adopt security best practices, like [dropping unnecessary capabilities](https://github.com/prometheus-operator/kube-prometheus/pull/1610), but looks like we forgot to update the [pod-security policies](https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/addons/podsecuritypolicies.libsonnet)

**Comment by wulfthimm** [comment]
Here is the PR that should fix the problem. https://github.com/prometheus-operator/kube-prometheus/pull/1642

**Comment by ArthurSens** [comment]
Confirmed that it is running!
![image](https://user-images.githubusercontent.com/24193764/153890887-20bcf872-ad11-4997-8b7e-c0a5ba709b5d.png)
