### ISSUE TITLE
[prebuild] Not starting workspace once the prebuild is done

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#8195]
Instead, user is left handing with prebuild log, reading "exit" at the end. Reload starts the workspace properly.

Screenshot:
![image](https://user-images.githubusercontent.com/32448529/154690797-4b21f4c4-a4a3-448e-a5fe-292ca169d003.png)

Idea: Might be triggered by us [fixing the status updates recently](https://github.com/gitpod-io/gitpod/pull/7968).

/cc @jldec not the issue I had in mind during our meeting, but annoying nonetheless

**Comment by jldec** [comment]
@geropl can you clarify how to to repro this?

What do you have to do, to see a prebuild log (I assume in the dashboard) when you are expecting to start a workspace?

**Comment by geropl** [comment]
> can you clarify how to to repro this?

This happened to me a couple of times last days (1 week) now on the gitpod-io/gitpod repo. I started a workspace, and was show the "Prebuild in progress" view with logs flowing in. I left the tab as this usually takes a couples of minutes.
When I came back the prebuild had clearly finished (noticable because of the last line saying "exit"). Now, because we don't show the actual status of that prebuild, I'm not sure if a) the prebuild was completed, or b) just the execution was finished, but it was still uploading the result.
But when I hit "F5", the workspace started immediately based on this (another?) prebuild.

**Comment by geropl** [comment]
Here's a screenshot, finally: 
![image](https://user-images.githubusercontent.com/32448529/154690694-6e5aeb22-9f9a-4e78-814c-10a4e8689e20.png)

**Comment by geropl** [comment]
> Could it be that we don't properly handle websocket reconnections?

Exactly my suspicion, at the code change seems to prove it. Will try to verify. :upside_down_face:

**Comment by AlexTugarev** [comment]
I was just hitting the same issue. I forgot to take a screenshot, but I verified that the `onPrebuildUpdated` (`available`) event  was received on 2nd or 3rd websocket connection and not on the initially created one.

**Comment by geropl** [comment]
This did not see much work due to installer, and I'm on sick leave, so moving back to "scheduled".

**Comment by josepjaume** [comment]
Hi! Sorry to chime in - this is a major blocker for us at Factorial, and probably the first source of frustration to transition to Gitpod. It gives people a sense of "unstability". In big repos with lots of activity, having to start over again makes people nervous 🙃. People end up understanding that they need to refresh at the end of the process, but that's far from ideal (especially given that from that moment on, everything works flawlessly).

That said, I love the product and I think you're doing an amazing job. Take care @geropl, and sorry to bother you while on sick leave!

**Comment by geropl** [comment]
@AlexTugarev Was just able to reprodue this on staging. :+1:
