### ISSUE TITLE
[dashboard, (server?)] Inconsistent derivation of prebuild status

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#8197]
This leads to inconsistencies in our UI (prebuild says "FAILED", but re-triggering yields "cannot start - still running") and strange errors ([hanging on prebuild logs](https://github.com/gitpod-io/gitpod/issues/8195)).

Examples where we're interested in the state/properties of a prebuild, but use different sources:
 - [PrebuildLogs](https://github.com/gitpod-io/gitpod/blob/945a8080cc8b5be4a83e899f049f1dfa5d86860c/components/dashboard/src/components/PrebuildLogs.tsx#L54)
 - [Prebuilds](https://github.com/gitpod-io/gitpod/blob/4d9d49d81c7cecb29b906563c8e90094e2ec19b8/components/dashboard/src/projects/Prebuilds.tsx#L285-L353), [2](https://github.com/gitpod-io/gitpod/blob/4d9d49d81c7cecb29b906563c8e90094e2ec19b8/components/dashboard/src/projects/Prebuilds.tsx#L106-L123), 
 - [protocol](https://github.com/gitpod-io/gitpod/blob/07e013ecc2808240b768710886ff52fac0f921bd/components/gitpod-protocol/src/protocol.ts#L668-L680)
 - [bridge](https://github.com/gitpod-io/gitpod/blob/4a564067cdb53e60ac7b2a527304abba373d3280/components/ws-manager-bridge/ee/src/bridge.ts#L71-L100)
 - [PrebuildLogs](https://github.com/gitpod-io/gitpod/blob/945a8080cc8b5be4a83e899f049f1dfa5d86860c/components/dashboard/src/components/PrebuildLogs.tsx#L118-L120)
 - [PrebuildLogs](https://github.com/gitpod-io/gitpod/blob/945a8080cc8b5be4a83e899f049f1dfa5d86860c/components/dashboard/src/components/PrebuildLogs.tsx#L121-L123)
 - [PrebuildStatusMaintainer](https://github.com/gitpod-io/gitpod/blob/4d47f0b7610c1ccfda884019fb3e45ccc7e6c42f/components/server/ee/src/prebuilds/prebuilt-status-maintainer.ts#L101-L119)

I don't think that all of those usages are wrong per-se, but I think the fact that we see such a variety of ways to answer the same question is a strong hint that our data model/API lags functionality or reliability.
IMO it's worth going through all cases and understand the motivation and problems that the current API poses and fix those.

**Comment by jldec** [comment]
Thanks @geropl - I agree and made a similar [comment](https://github.com/gitpod-io/gitpod/issues/6305#issuecomment-1041295238) earlier today.

> The inconsistent behavior of prebuild status and logs is adding to the perception of prebuild unreliability.

**Comment by geropl** [comment]
A concrete bug caused by this: https://github.com/gitpod-io/gitpod/issues/8592

**Comment by easyCZ** [comment]
Out of the instances listed, only the following remain:
- [ ] https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/PrebuildLogs.tsx#L87
- [ ] https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/ee/src/bridge.ts#L82 This one is less of a concern as it is a derivation from the underlying Workspace Instance Status which has to happen
- [ ] https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/projects/Prebuild.tsx#L188 which is being tackled in https://github.com/gitpod-io/gitpod/pull/8841
