### ISSUE TITLE
IntelliCode Suggestions

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#820]
It would be really nice to have the IntelliSense suggestions you know the ones with the stars by them in vscode

**Comment by jankeromnes** [comment]
@JesterOrNot Thanks for the suggestion! But I don't understand what you mean. Could you please be more specific regarding what you tried; what you expected (e.g. with a screenshot from VS Code); and what happened instead?

See also https://github.com/gitpod-io/gitpod/issues/806

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/66258030-fcc51b80-e765-11e9-8cf7-c3b5e2d9222d.png)
https://www.makeuseof.com/tag/extensions-visual-studio-code/

**Comment by jankeromnes** [comment]
I suppose the extension is https://github.com/MicrosoftDocs/intellicode

We should try installing it in Gitpod, to see if it works.

If it doesn't work, we should file an issue against https://github.com/eclipse-theia/theia/issues, requesting support for that extension.

**Comment by JesterOrNot** [comment]
Here: https://gitpod.io/#https://github.com/JesterOrNot/Gitpod-Intellicode
And Here: https://github.com/JesterOrNot/Gitpod-Intellicode
