### ISSUE TITLE
Allow customization of the workspace with user specific tools

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#8200]
## Is your feature request related to a problem? Please describe
As a developer I have a bunch of favorite tools that I would like to be available in every one of my workspaces but these tools are not necessarily relevant for every developer working on the project so I would not want to add them to the docker image for the project. As an example, I might prefer using ripgrep instead of grep or bat instead of cat but other developers are fine using the default tools.

I should be able to specify a docker image in my user settings (similar to how I can specify a repository for dotfiles today). This docker image would be like a dazzle chunk that is transparently added to the workspace image by the registry facade whenever a new workspace is created for me. 

This docker image would contain my personal tools in e.g. a /tools directory. When we detect that the user has configured a tools docker image we would adapt the PATH of the gitpod user to include that directory so that the tools are available in PATH.

**Comment by axonasif** [comment]
Cross-related: https://github.com/gitpod-io/gitpod/issues/8184
