### ISSUE TITLE
Research a possibility of using pd disks with auto-delete=false to prevent loss of backups

### ISSUE THREAD

**Issue by sagor999** [gitpod-io/gitpod#8202]
Currently we are attaching gcp disks to the VM directly, and those disks are created using `auto-delete=true`. 
Whenever node is experiencing health issues and gets deleted, those disks are deleted as well, causing loss of user data.
As part of RFC: https://www.notion.so/gitpod/Ensure-durability-and-availability-of-user-workspace-files-9edff6bbf87248d5ac73a7d4548ee4b3 this github issue would explore a possibility of switching `auto-delete` to `false`. That way disk will remain when node is deleted.
This means that we need to have a solution for:
1. Ability to detect when we have a disk that is no longer attached to VM
2. Be able to attach that disk to the cluster (we could be able to attach it as PVC, need research). If we can attach it as PVC, then we would have a service that would scan that disk for remaining workspaces and backup them if found. 
3. Once verified that disk is empty, it would then be deleted.

So this task is concentrated on validating idea on how we can accomplish above.
First approach is to try to attach that disk via PVC. That would be easiest solution. 
If that wouldn't work for some reason, other approach would be to spin up a VM that would attach that disk, perform backup, and then spin down and delete the disk. But it is more complicated and a bit cumbersome. 
(There might be some other approach as well)

This approach in general would still not be very compatible with self hosted solution and would be used only in our SaaS offering. 

Related issue: #8104

**Comment by sagor999** [comment]
So we can mount existing disk as PVC into the cluster. 
Here is the plan, broken up into several issues:
1. In workspace preview env, add support for adding a new VM to the cluster (to simulate scale up): https://github.com/gitpod-io/workspace-preview/issues/12
2. In workspace preview env, add support for installing GCP CSI driver (for PVC support from disk): https://github.com/gitpod-io/workspace-preview/issues/13
3. Create new controller (node-backup-watcher?), whose job will be to scan PD disks and find one that are not attached to any node (we need to add labels to disks to make sure controller from one cluster doesn't touch disks from another cluster). Once it finds one, it will create PV and PVC (for that disk) (special storage class) and create a pod (new component?) whose job will be to scan PVC and backup any remaining workspaces. Once done, it will add a label to the disk. Once controller sees that label, it will delete the disk. Issue: #8205 
There is a problem though: We are creating raid0 out of two disks. This wouldn't work with the above approach. Issue to disable raid0: https://github.com/gitpod-io/ops/issues/1166
(though it is not a show stopper to prototype this approach, only will be a show stopper when we need to deploy this into prod).
And issue to make sure we add proper disk labeling: https://github.com/gitpod-io/ops/issues/1167

Once this is done and tested, we will need to  work on rolling it out to production clusters (specifically GCP CSI driver installation).
Controller and pod will have tight coupling to GCP (using gcloud\sdk), which means migrating this to a different cloud will be cumbersome in the future.

Result:
we should be able to recover workspaces that are lost due to failed node within 2+X minutes (1 min scan internal, 1 min to create and attach pod, and then X amount of minutes that are needed to run backup).

Both controller and pod will be stateless.

**Comment by sagor999** [comment]
After talking to @csweichel, we decided to drop PVC approach for disk mounting, and instead mount disk directly to a dedicated VM (in a separate node pool) via `gcloud compute instances attach-disk`. This will simplify the overall process, as now we don't need to spawn special pod to handle backups, it all can be done inside the new controller instead.

**Comment by aledbf** [comment]
> There is a problem though: We are creating raid0 out of two disks. This wouldn't work with the above approach. Issue to disable raid0:

This was migrated from the previous approach (GKE). I am not sure if one disk can handle all workspaces IOPS or we need to switch back to SSDs (70% increase cost in storage)

**Comment by sagor999** [comment]
re: raid0
yes, that is definitely a concern. I will do tests first (synthetic though)

https://cloud.google.com/compute/docs/disks/performance
I am not sure if raid0 gets even close to ssd perf though.
we could also allocate a disk per several ws, instead of one per node to better spread the load.

**Comment by aledbf** [comment]
> 3. Create new controller (node-backup-watcher?), .....

What you are describing here is very similar to github.com/kubernetes-csi/external-snapshotter  (that project has the advantage that is not tied to GCP)
https://kubernetes.io/es/docs/concepts/storage/volume-snapshots/

**Comment by sagor999** [comment]
We decided to go with PVC\Snapshot approach after all. Design doc will be drafted and later converted into issues.
