### ISSUE TITLE
Port XXXX Not Found -- The constant need to clear gitpod cookies

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#8206]
### Bug description

The past couple months my team has been seeing constant "Port XXXX Not Found" errors when opening previews in the browser. The application is running and the port is being served; the work around is clearing **all** `gitpod.io` cookies and stored data and reopening the workspace then it will be served.

- The majority of the it works, but this is happening 2-3 per team member per week, it adds up
- Clearing gitpod.io cookies always resolves the problem
- Often, not always, it happens the first time a workspace is open on a new cluster: i.e., the first time opening on `ws-us31.gitpod.io` -- it's pretty much 100% when a new cluster is opened

### Steps to reproduce

- Use gitpod regularly
- Open a workspace on a new cluster
- Open a port
- Attempt to browse to it

### Expected behavior

I should see the content served at the port

**Comment by sagor999** [comment]
@smacintyre would you be able to open developer console in your browser when this happens and copy paste errors from it in here? 
That will help to track this down. 
I tried to repro this locally but had no luck so far.

**Comment by smacintyre** [comment]
@sagor999 Will do. It happens really randomly.

**Comment by kylos101** [comment]
Hey @smacintyre we're switching to a new cluster now, over the next 3 hours it'll be come more likely that you'll land on `ws-us34.gitpod.io`. If you encounter trouble, and are able to share any errors, that'd be great!

**Comment by smacintyre** [comment]
@sagor999 @kylos101 Thank you for your response. Unfortunately (fortunately?) the problem has not reoccurred and there were no issues with the move to `ws-us34`.  So I don't have any more feedback. It seems since I opened this issue it has largely stopped. I'm sorry I haven't been able to provide any more details. Thank you for your help. If you wish to close this ticket, please go ahead. 

Oh, any word on when the promised Asian zone will be online?

**Comment by kylos101** [comment]
Hey @smacintyre okay, we'll close this issue, but, you're welcome to reopen if it rears its head again. :slightly_smiling_face: 

[You may wish to subscribe to this issue](https://github.com/gitpod-io/gitpod/issues/7489). I cannot share an ETA now, but, if you subscribe to it that help you keep track of the related conversation.
