### ISSUE TITLE
Load zfs kernel module for workspaces

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#8208]
## Is your feature request related to a problem? Please describe

`zpool` cli is not fully functional without the `zfs` kernel module

## Describe the behaviour you'd like
Have the `zfs` kernel module loaded along other standard modules that we have currently.

## Describe alternatives you've considered

One could run a separate system via `QEMU` but that might not be so ideal.

## Additional context

https://app.frontapp.com/open/cnv_iri9f9m
cc @NikolayS

**Comment by sagor999** [comment]
@csweichel any concerns with adding that module? and I assume we have to add it to k3s VM image? Or do we add it in supervisor\ws-daemon? :thinking:

**Comment by csweichel** [comment]
I reckon we'd add it in the VM image.
We'd then need to an integration test to make sure we keep the module around

**Comment by NikolayS** [comment]
@axonasif this is marked as "completed" but I cannot find anything related to implementation. Are there any plans to implement it? Thanks.

**Comment by axonasif** [comment]
Hi @NikolayS, it was auto closed by stale bot. It won't close again now.

**Comment by sagor999** [comment]
Added zfs kernel module support into our VM image. If that will be merged soon, then it should roll out later this week.
