### ISSUE TITLE
User based debug settings

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#821]
add the capability to create global debug settings

**Comment by JesterOrNot** [comment]
Maybe adding something to the .thiea directory

**Comment by jankeromnes** [comment]
@JesterOrNot Great suggestion! But actually, you should already be able to use the top menu bar to go into:

```
File > Settings > Open Preferences
```

In there, there are a few Debug options that you can change, and if you override them in the `User` tab, these overrides should follow you globally across all workspaces:

<img width="725" alt="Screenshot 2019-10-03 at 08 37 23" src="https://user-images.githubusercontent.com/599268/66104506-0e1cf500-e5b9-11e9-8a7e-692c6e4deaaf.png">

But maybe this is too limited for what you intended to set up / configure globally?

**Comment by svenefftinge** [comment]
Or are you looking for debug configuration (aka launch.json)?
You can open the debug view on the left and click the gear to open/create that file.

**Comment by JesterOrNot** [comment]
Yea I meant debug configurations so you can make it global across workspaces?

**Comment by svenefftinge** [comment]
I'm not quite sure why you would want to make a debug configuration global across projects? 
I think they are usually specific to a project, no?

**Comment by JesterOrNot** [comment]
I suppose but I think it should be an option say one has a specific debug setting its a pain to rewrite the launch.json file

**Comment by jankeromnes** [comment]
> say one has a specific debug setting its a pain to rewrite the launch.json file

What kind of specific debug setting do you have in mind?

Also, I think Sven is right, you'd have to rewrite the launch.json for every project anyway, right?

I think the solution here is to write `launch.json` only once, and then commit it to the project's repository (that way everyone will have it in all their workspaces for that particular project).

**Comment by JesterOrNot** [comment]
Alright, thanks!
