### ISSUE TITLE
Database error ER_BAD_FIELD_ERROR

### ISSUE THREAD

**Issue by tomvdbussche** [gitpod-io/gitpod#822]
**Describe the bug**
Loading Gitpod results in the following error:

> Error: ER_BAD_FIELD_ERROR: Unknown column 'ws.headless' in 'field list'

**To Reproduce**
1. Go to any Gitpod environment (e.g. https://gitpod.io/#https://github.com/eclipse/sprotty)
2. Error is shown

**Expected behavior**
Environment loads up as usual

**Comment by geropl** [comment]
Thank you for reporting @tomvdbussche. We're very sorry for this. Sth. slipped through in review + some DB update take way longer than expected.

Expect everything to work again in the next 5mins.

**Comment by jankeromnes** [comment]
This should be fixed in Europe and North America. Asia Pacific cluster is still being worked on.

**Comment by tomvdbussche** [comment]
Can confirm all is well again in the EU

**Comment by jankeromnes** [comment]
Problem solved: https://twitter.com/gitpod/status/1178958572903915520

Thanks a lot for bearing with us! 💯
