### ISSUE TITLE
[supervisor] Ensure we fetch IDEOptions/desktopIDEConfig on re-start

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#8226]
So far we set [dekstopIDEConfig](https://github.com/gitpod-io/gitpod/blob/c0bbf911db3a13c23cd7da8a124c17b5046e245c/components/supervisor/frontend/src/index.ts#L119-L123) and [IDEOptions](https://github.com/gitpod-io/gitpod/blob/0fa9200ac83835463267630ab01f79a01a1db5fb/components/dashboard/src/start/StartWorkspace.tsx#L131-L132) onload. With the [recent change away from auto-reload behavior](https://github.com/gitpod-io/gitpod/pull/8125#issuecomment-1038846404) this does no longer show "Open in < desktopIDE >" in cases where:
 - you open a workspace in tab 1
 - stop it in tab 2 (dashboard, for example)
 - re-start it in tab 2 (dashboard, for example)

We should see
![image](https://user-images.githubusercontent.com/32448529/154085666-6f8bfa7c-6e49-4121-aaa4-90faf2f456d1.png)
but instead see this:
![image](https://user-images.githubusercontent.com/32448529/154086587-338c7b20-b36f-432f-bef3-f5fd89e5b5b2.png)

The dashboard change is quite [straight forward](https://github.com/gitpod-io/gitpod/pull/8188). In supervisor-frontend we'd need to re-fetch the desktopIDEConfig on re-start as well.

/cc @akosyakov

**Comment by geropl** [comment]
This might also be the cause an issue where we do not reveal the IDE of a running workspace after the tab lost focus on laptop suspension ([issue](https://github.com/gitpod-io/gitpod/issues/8246)):
 - we now do not auto-start if runsInFrame
 - but we have a special case for revealing for the first time a workspace becomes RUNNING
 - this breaks for re-started workspaces or laptop suspenion

I think we need to change the supervisor index to always:
 - reveal (RUNNING x browser)
 - show recent IDE options (RUNNING x desktopIDE)
not just the "first time we see RUNNING after onload".

Internal discussion: [slack](https://github.com/gitpod-io/gitpod/issues/8226)

**Comment by loujaybee** [comment]
Thanks @geropl — given that this looks to be a smallish fix, let's pull into scheduled. 🙏

**Comment by akosyakov** [comment]
@geropl I thought we fixed it already 🤔 ?

**Comment by geropl** [comment]
@loujaybee just popped up again yesterday on [slack](https://gitpod.slack.com/archives/C02EN94AEPL/p1646945916867229).

**Comment by akosyakov** [comment]
@mustard-mh Can you have a look please? 🙏

**Comment by mustard-mh** [comment]
We only update `ideStatus` in `supervisor/frontend` when [ideReady](https://github.com/gitpod-io/gitpod/blob/37916d402508a9e83ef18b22d1af57e01d4e05e1/components/supervisor/frontend/src/index.ts#L212-L216), now the easiest solution is to listen to some other phase and re-listen `ideReady`. But this is not smart, because we don't know what phases need to wait for ideReady again, and if those phases may be missed due to other situations.

So I think the best way to do is to pass ide configuration of current instance when the instance is updated.

cc @geropl @akosyakov

**Comment by mustard-mh** [comment]
> So far we set [dekstopIDEConfig](https://github.com/gitpod-io/gitpod/blob/c0bbf911db3a13c23cd7da8a124c17b5046e245c/components/supervisor/frontend/src/index.ts#L119-L123) and [IDEOptions](https://github.com/gitpod-io/gitpod/blob/0fa9200ac83835463267630ab01f79a01a1db5fb/components/dashboard/src/start/StartWorkspace.tsx#L131-L132) onload.

Thanks for guide here👍, I really don't know supervisor/frontend before
