### ISSUE TITLE
All my workspaces are gone. And also I'm not able to create new workspace

### ISSUE THREAD

**Issue by pawankp550** [gitpod-io/gitpod#823]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by jankeromnes** [comment]
Hi @pawankp550, we're very sorry about that, but we believe that it's a temporary issue which will be resolved soon.

There was a DB migration bug during this morning's production deployment, and we're working on fixing it as soon as possible.

**Comment by jankeromnes** [comment]
This should be fixed in Europe and North America. Asia Pacific cluster is still being worked on.

**Comment by jankeromnes** [comment]
Problem solved: https://twitter.com/gitpod/status/1178958572903915520

Sorry for the disruption, and thanks a lot for your patience and understanding. 🙏
