### ISSUE TITLE
[jb] support EAP of Gateway (v. 221)

### ISSUE THREAD

**Issue by buggtb** [gitpod-io/gitpod#8247]
### Bug description

I don't believe this was a glitch in the matrix, but I've not tested it this week.

When setting up a new machine over the weekend, I grabbed the gateway plugin from the Jetbrains website, installed it and couldn't find the Gitpod plugin. I realised the download offered was some 2022 build which didn't work with the plugin.

i dug around and found a link where I could cobble together the gateway download link that would work, which was https://download-cdn.jetbrains.com/idea/gateway/JetBrainsGateway-213.6777.25.exe so I got that one and the plugin was visible from there.

### Steps to reproduce

Install fresh gateway, look for Gitpod plugin

### Expected behavior

Should see the gitpod plugin

**Comment by akosyakov** [comment]
@buggtb please use stable version, for now we don't support EAP yet

**Comment by buggtb** [comment]
Yeah, but the link literally on their website from the link from your website, got me that version. I was just following the prescribed installation flow

**Comment by buggtb** [comment]
https://www.jetbrains.com/remote-development/gateway/ If I download the gateway from here, I get a 221 build not a 213 build.

**Comment by akosyakov** [comment]
@buggtb The instruction should be updated now to point out that Release version should be used and provide a link explaining to use Toolbox instead.

I will keep an issue around to support EAP too. We do it at the beginning of March.

**Comment by eiswind** [comment]
HI @akosyakov 
Could you please add a link to the mentioned issue? I depend on some feature that only works with the EAP. So I'd like to check back on that.

**Comment by akosyakov** [comment]
@eiswind Do you mean in docs? Sorry I am not quite sure where we should mention this issue.

**Comment by eiswind** [comment]
@akosyakov I thought there was a separate issue regarding the Gateway EAP Support, but I could not find any.
