### ISSUE TITLE
Track keybinding usage/exploration in oder to make the dashboard more intuitive

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8251]
## Is your feature request related to a problem? Please describe

https://github.com/gitpod-io/gitpod/pull/7715 introduced a new dashboard-wide keybinding: `Ctrl/Cmd + O` (for "Open in Gitpod")

However, we're unsure whether this is the most intuitive keybinding for our users, who might also want to use `Ctrl/Cmd + K` or `Ctrl/Cmd + P` for example.

Getting insights into which keybindings are actually being tried by users on dashboard pages could help inform future keybindings & potentially new features.

## Describe the behaviour you'd like

Ping analytics when a user tries one of these keybindings:
- `Ctrl/Cmd + O` (currently opens the new `Open in Gitpod` modal)
- `Ctrl/Cmd + K` (currently focuses the Firefox search bar / does nothing in Chrome)
- `Ctrl/Cmd + P` (currently opens the print dialog 🖨️ 🧓)
- `Ctrl/Cmd + Z` (currently does nothing -- except if an input is focused, then it undoes the latest edit)
- `.`?
- `t`?
- ([konami code](https://en.wikipedia.org/wiki/Konami_Code) could be fun 😛)

However, we shouldn't track any keybindings that we're unlikely to ever use, e.g.:
- `Ctrl/Cmd + W` (closes browser tab)
- `Ctrl/Cmd + L` (focuses browser URL bar)
- `Ctrl/Cmd + N` (opens new browser window)
- `Ctrl/Cmd + T` (opens new browser tab)
- `Ctrl/Cmd + Q` (quits the browser? too scared to try 😝)
- `Ctrl/Cmd + J` (opens browser downloads)
- `Ctrl/Cmd + F` (in-page search -- some websites choose to override this, but I almost always dislike what they have instead)
- `Ctrl/Cmd + Tab` (switches between browser tabs)
- `Ctrl/Cmd + +/-` (controls page zoom level)
- etc

**Comment by geropl** [comment]
@jankeromnes Is this still relevant? If yes: can we fit this into 0.25 day effort? Does not want to block this per-se if we gain insight, but I don't see a huge overlap with the current priorities, and would opt for "close for now", then. :pray:

**Comment by jankeromnes** [comment]
@geropl Still relevant, and yes I believe I could implement this in 0.25 day. Maybe schedule, assign to me, and I'll implement it next week?

**Comment by geropl** [comment]
@jankeromnes Ok then. Fine with scheduling, but definitely lower prio then GHE - let's tick that box first. :white_check_mark:
