### ISSUE TITLE
Some headless workspaces get stuck in a Stopping status (Terminating in Kubernetes)

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8254]
## Is your feature request related to a problem? Please describe

The scheduler does not consider pods having a Terminating status, and when the Kubelet receives a new workload to run a headless workspace, depending on the node's resources, it may fail with OutOfMemory...growing the number of headless workspaces stuck in Stopping (Terminating) on that node.

## Describe the behaviour you'd like

One idea is to only add the finalizer after a headless workspace is started. The failure mode without a finalizer might be that the user would not be able to see "why" the prebuild or image build failed (depending on when the pod stops), just that it failed. From a user experience standpoint, that does not seems ideal though (not knowing why a headless workload failed).

## Describe alternatives you've considered

Triage a variety of headless workspaces stuck in stopping, identify where they may have waited too long to stop, and socialize fixes for those issues instead.

## Additional context

https://gitpod.slack.com/archives/C02F19UUW6S/p1645013258718659?thread_ts=1645005653.831739&cid=C02F19UUW6S

**Comment by sagor999** [comment]
>One idea is to remove the finalizer after a headless workspace is started. 
Opposite. Only add finalizer when headless workspace has actually started.

Currently we have a bunch of them in terminating state stuck forever, because they are actually never started (kubelet killed it with oom and did not allow it to start) but because we added finalizer at creation, that finalizer is now not removed. so pod is stuck in permanent terminating state.

**Comment by sagor999** [comment]
Our fixes to OOM actually apply here as well, since now if headless (or any) workspace did not start, it will remove finalizer and delete the pod. 
So I think we can close this issue.
