### ISSUE TITLE
Fixes are not working anymore

### ISSUE THREAD

**Issue by mrussmann** [gitpod-io/gitpod#826]
**Describe the bug**
Quick Fix appears, click on it has no effect anymore. 

**To Reproduce**
Java Environment, Missing Import Statement, Quick Fix appears and shows the correct suggestions, click on it -> no effect
Other example
Missing exception - Quick Fix appears and offers add the method and surround - 
choose an option has no effect

**Expected behavior**
Click on the quick fix and the import of the missing package is added in the source code.

**Comment by svenefftinge** [comment]
See https://github.com/eclipse-theia/theia/pull/6304

**Comment by AlexTugarev** [comment]
@mrussmann thanks for reporting this! the underlying issue is the same as for rename of symbols. we'll need to update Theia asap 🙏

**Comment by AlexTugarev** [comment]
just verified, eclipse-theia/theia#6304 also fixes this issues.

**Comment by svenefftinge** [comment]
Fixed and deployed.
