### ISSUE TITLE
[jb] workspace timeout if browser page is closed before client connects

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#8263]
### Bug description

Feedback:
> Often (but not always) after 10 minutes of inactivity the workspace becomes inactive and the client closes, but not in a very obvious way.

I suspect that a user closes the browser page and it triggers reducing timeout to 3 mins. We should rethink how to approach it. Disabling timeout there can backfire in the case if a client did not open thin client but only close the page, then we will spend user hours for 30 mins.

### Steps to reproduce

Start a workspace, open thin client and wait that it times out in 30 mins without touching a window anymore. If not it is a bug.

**Comment by akosyakov** [comment]
A user confirmed that a browse page was closed.

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/gitpod/issues/10373
