### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#828]
add java maven extension to gitpod workspace

**Comment by jankeromnes** [comment]
Thanks for the suggestion! I believe you're talking about https://github.com/microsoft/vscode-maven/releases

Out of curiosity, have you already tried it in a Java repository? Did it work well? 🙂

**Comment by JesterOrNot** [comment]
here is a repo sorry for the delayed response https://github.com/JesterOrNot/Gitpod-Maven

**Comment by jankeromnes** [comment]
Cool, thanks a lot @JesterOrNot!

I see that it adds this widget in the bottom left:

<img width="332" alt="Screenshot 2019-10-15 at 10 43 57" src="https://user-images.githubusercontent.com/599268/66815557-c55e2800-ef38-11e9-972e-1209fa3466e7.png">

However, I'm not quite sure how it works / what it's supposed to do. If you have time, could you please include a demo Maven project in the repository, so that we can see the extension in action?

**Comment by JesterOrNot** [comment]
See it in action:
https://www.loom.com/share/3c04a55a982e41f5b8210953211a6d9e

**Comment by jankeromnes** [comment]
Wow, I missed the `+` button. Really cool stuff! Thank you @JesterOrNot for setting up the Maven demo repository and walking me through how to use the Maven VS Code extension.

I think this should totally be mentioned in https://github.com/gitpod-io/website/blob/master/src/docs/java_in_gitpod.md cc @svenefftinge.

**Comment by JesterOrNot** [comment]
Should this be added to the default image given Maven's popularity?

**Comment by jankeromnes** [comment]
That's a good question. I agree that Maven is quite popular, however it may be confusing to developers of every other programming language to see a "Maven" section on Gitpod.

Maybe it should be installed in Gitpod's default Java example repo? https://github.com/gitpod-io/spring-petclinic

**Comment by JesterOrNot** [comment]
We could make a different build for the docker image in which it is installed and the FROM statement would go something like: `FROM gitpod/workspace-full:maven` and that image would have maven and maybe some other build tools available and then just talk about it in the docs

**Comment by svenefftinge** [comment]
We need to reduce the amount of default extensions to a minimum so let's not add it. Also Gradle is another popular build system for Java. But we could include a detection/suggestion in the setup assistant.

> I think this should totally be mentioned in https://github.com/gitpod-io/website/blob/master/src/docs/java_in_gitpod.md cc @svenefftinge.

please do :-)
