### ISSUE TITLE
Gitlens issue

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#829]
**Describe the bug**
Got the error:
![Screenshot 2019-10-04 at 6 56 51 PM](https://user-images.githubusercontent.com/50386709/66246461-cf329080-e6d9-11e9-8899-717f58f1e092.png)

**To Reproduce**
Install gitlens extension
or open my workspace https://github.com/JesterOrNot/pycalc
**Expected behavior**
Works normally

**Comment by jankeromnes** [comment]
Oh oh, sorry about this problem.

For VS Code extension related bugs, could you please file them directly against https://github.com/eclipse-theia/theia ? (It's Gitpod's IDE, and that's where VS Code extension support is implemented or fixed.)

**Comment by JesterOrNot** [comment]
Close in favor of
https://github.com/eclipse-theia/theia/issues/6347
