### ISSUE TITLE
Ability to tag & group workspaces

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#8291]
## Is your feature request related to a problem? Please describe

A customer I work with asks for a way to tag / group workspaces.

## Describe the behaviour you'd like

Instead of a list of all workspaces, the customer would like the ability to tag workspaces and see them grouped in the dashboard.

## Describe alternatives you've considered

N/A

**Comment by JanKoehnlein** [comment]
Do they know you can _pin_ workspaces (from the hamburger menu)?

Tagging them sounds a bit too much like re-use (as opposed to ephemeral workspaces). Grouping _Projects_ sounds a bit better in that regard. But that's more a product question (cc @jldec)
