### ISSUE TITLE
Regression for "operation not permitted: missing get permission on workspace"

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#8292]
### Bug description

The same as #6549.

This happens for a customer I work with. Out of 150+ projects, some show this error while others don't. For the ones where the error shows up, some people see the error and others can start Prebuilds without error.

### Steps to reproduce

1. Create a project
2. Open the "Configuration" settings
3. Kick off a Prebuild

### Expected behavior

All team members can start Prebuilds for all projects.

### Anything else?

Please contact me internally for an intro to the customer for troubleshooting.

**Comment by mikenikles** [comment]
New report on Twitter: https://twitter.com/erctldysfnction/status/1496102049372684289

**Comment by chuck-confluent** [comment]
Seeing this on prebuilds as well:
![image](https://user-images.githubusercontent.com/48225759/162328510-4e244819-33d1-4eb7-a5da-d09b1cb2e904.png)

I can run a prebuild manually via URL and see the logs though.
