### ISSUE TITLE
Parse context from `.gitpod.YAML` as well (not `.YML` only)

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#8294]
### Bug description

For projects that already contain a `.gitpod.yaml` configuration file, the new project onboarding (gitpod.io/new) process ignores that existing file and adds a second config file, `.gitpod.yml`. When the workspace starts, the already existing `.gitpod.yaml` file is ignored.

### Steps to reproduce

1. Create a new repo
2. Add a `.gitpod.yaml` config file with a `command` task
3. Navigate to https://gitpod.io/new
4. Configure the newly created project
5. Start a new workspace

### Expected behavior

Gitpod respects the existing `.gitpod.yaml`.

A warning may be displayed encouraging me to migrate the file extension to `.yml`.

**Comment by JanKoehnlein** [comment]
From the code, I don't see that we fall back to `.gitpod.yaml` anywhere, so I am switching this to _improvement_.

**Comment by rfay** [comment]
This is a serious problem - The existing .gitpod.yml should be respected. This completely breaks everything that has a .gitpod.yml. Is there any workaround? This completely breaks https://github.com/drud/ddev-gitpod-launcher and really... everybody that ever had a .gitpod.yaml. I don't need this silly replacement .gitpod.yml:

```yaml
tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'
```

This is  a super-critical bug, not an "improvement" as far as I can tell. In fact, gitpod should never be replacing existing files.
