### ISSUE TITLE
Please add Kotlin support

### ISSUE THREAD

**Issue by zambrovski** [gitpod-io/gitpod#83]
If I'm using Kotlin as programming language, the files are opened as text-only.

Please add support for Kotlin.

Here is the language server link: https://github.com/fwcd/KotlinLanguageServer

**Comment by ParHandler** [comment]
Please add support for Kotlin.

**Comment by YassinHajaj** [comment]
Hi, is there any advancement on this issue? It would be great to have Kotlin support. I use it quite frequently.

**Comment by jankeromnes** [comment]
Hi all! Gitpod can now install VS Code extensions, so hopefully this means you can get Kotlin support relatively easily.

Simply download the Kotlin extension's `.vsix` file, then drag-and-drop it into the extensions panel in Gitpod (on the left vertical bar, lowest icon), and it should hopefully install & activate automatically.

If it doesn't work, please report any failures, and we'll try to fix them as fast as we can. 🙂 🤞

**Comment by YassinHajaj** [comment]
> Hi all! Gitpod now supports VS Code extensions, so hopefully, this means you can get Kotlin support relatively easily.
> 
> Simply download the Kotlin extension's `.vsix` file, then drag-and-drop it into the extensions panel in Gitpod (on the left vertical bar, lowest icon), and it should hopefully install & activate automatically.
> 
> If it doesn't work, please report any failures, and we'll try to fix them as fast as we can. 🙂 🤞

Great, this works! Maybe its time to add it to the [supported programming languages list](https://www.gitpod.io/features/), or at least mention the extensions (even though it's still a beta feature).

**Comment by jankeromnes** [comment]
@YassinHajaj awesome, thanks a lot for trying!

Which extension did you try by the way?

Also, excellent point about updating the list of supported programming languages. FYI, we've mentioned VS Code extensions support in our [blog](https://www.gitpod.io/blog/vscode-extension-in-online-ide/), [docs](https://www.gitpod.io/docs/vscode-extensions/) and [on twitter](https://twitter.com/gitpod/status/1157263981482000387), but I agree that it would make sense to display it more prominently, e.g. in the Features page.

**Comment by YassinHajaj** [comment]
Hey @jankeromnes, I tried the following extension: https://marketplace.visualstudio.com/items?itemName=mathiasfrohlich.Kotlin

I just typed "kotlin vsix" on google and it was the first result.

It was certainly not a bad remark of course, but I would have found it easier I think in the features indeed.  You guys are still doing a great job and thanks for this awesome techno

**Comment by svenefftinge** [comment]
I'm closing this issue as Kotlin is now supported through the extension.
Btw. the extension can be downloaded directly from GitHub:
https://github.com/mathiasfrohlich/vscode-kotlin/releases
