### ISSUE TITLE
Support a Desktop App

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#830]
add the ability to go full screen so that you can use ctrl-tab to swap views from file to file

**Comment by jankeromnes** [comment]
@JesterOrNot You can already double-click on the tab handle of an Editor to make it go full screen (thus hiding the side and bottom panels). Was that what you meant?

Also, ctrl-tab won't work to switch between Editor tabs, and I didn't find a keystroke that could do that.

**Comment by JesterOrNot** [comment]
No, I meant something that would allow vscode keybindings that conflict with browser keybindings

**Comment by svenefftinge** [comment]
Hey @JesterOrNot I have changed the title, to make your intent clearer. The point is that going for an electron based desktop version is the simplest way to work around limitations in browsers.

**Comment by JesterOrNot** [comment]
I was talking about something similar to the 'full-screen mode' like chrome-remote-desktop

**Comment by JesterOrNot** [comment]
Was this implemented by gitpod self hosted?
