### ISSUE TITLE
[admin] Improve admin settings (telemetry) UX

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#8300]
**issue**: Using the alert component[[1](https://github.com/gitpod-io/gitpod/blob/bb809461b56dcc13a74d21faa1ec943fb0b8639b/components/dashboard/src/components/AlertBox.tsx)][[2](https://github.com/gitpod-io/gitpod/blob/bb809461b56dcc13a74d21faa1ec943fb0b8639b/components/dashboard/src/components/InfoBox.tsx)], also known as`InfoBox`, feels a bit misleading. Also, including the payload expanded looks a bit verbose and will not scale well in the long run as we add more information encapsulated in the payload. Lastly although a minor issue, the help links pattern (_Learn more_, _Read our Privacy Policy_, etc) is used at the end of sentences without any following text. Also, yes using a `monospaced` font for depicting such information sounds ideal.

**suggestion**: What do you think of using a modal to encapsulate this information to avoid injecting this kind of verbose information in the dashboard layout?

**thought**: We could also :a: drop the gray background and default to the white background as well as :b: re-use the cancel action button if that's easier to do in the spirit of MVC (minimum viable change) using the existing modal component[[1](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/Modal.tsx)]. Ideally, in the long run, this could use a markdown component which we could either show under a toggle element or within a modal like the proposal below. 💭 

| Button | Modal |
|-|-|
| <img width="1440" alt="Button" src="https://user-images.githubusercontent.com/120486/154547527-b2a70d03-0a89-49c7-8323-cb1536866186.png"> | <img width="1440" alt="Modal" src="https://user-images.githubusercontent.com/120486/154547598-6261df81-39d4-493e-92e4-374657a0bd57.png"> |

Thanks for the ping @corneliusludmann! 🏓

_Originally posted by @gtsiolis in https://github.com/gitpod-io/gitpod/pull/8272#discussion_r809358300_

**Comment by gtsiolis** [comment]
Removing this from the [product design board](https://github.com/orgs/gitpod-io/projects/29/views/4) as the proposal already includes specs ready for implementation.

One thing that can be considered when picking this up is re-using the same modal structure we already have. To this extend, re-posting from https://github.com/gitpod-io/gitpod/pull/8272#discussion_r809358300:

> We could also 🅰️ drop the gray background and default to the white background as well as 🅱️ re-use the cancel action button if that's easier to do in the spirit of MVC (minimum viable change) using the existing modal component[[1](https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/components/Modal.tsx)].

**Comment by lucasvaltl** [comment]
This is unlikely to get prioritised any time soon - will close this for now.
