### ISSUE TITLE
Cannot open snapshot for some GitLab repositories

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8309]
### Bug description

Taking snapshots no longer seems to work with private GitLab repositories.

Trying to open a snapshot that you took fails with:

<img width="479" alt="Screenshot 2022-02-18 at 13 02 22" src="https://user-images.githubusercontent.com/599268/154679756-cc219771-eb39-4070-8fec-cfcb7ad00bfc.png">

### Steps to reproduce

1. Open a private GitLab repository in Gitpod
2. Take a snapshot
3. Try to open the snapshot you took

### Workspace affected

indigo-vulture-05es8aq571n

**Comment by kylos101** [comment]
Thanks for the heads up, @jankeromnes ! When we fix this, we should be certain to add a related integration test.

**Comment by gtsiolis** [comment]
Updated the title as this seems to work for some repositories but not for others regardless if they are private. See also [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1646838882508579) (internal).

**Comment by sagor999** [comment]
This particular error is fixed with this: https://github.com/gitpod-io/gitpod/pull/9803
