### ISSUE TITLE
Simple Browser Preview doesn't show changes

### ISSUE THREAD

**Issue by Volodsher** [gitpod-io/gitpod#8311]
### Bug description

I have just one simple html file. When I run $ python -m http.server 8000 it works for this session. But it doesn't wont to work properly for the next ones, showing old versions of the html file.

### Steps to reproduce

1. open the workspace.
2. create a simple html file.
3. put sum tags and text.
4. start server $ python -m http.server 8000.
5. Open Simple Browser. It shows html as normal.
6. Close and open workspace several times with starting server.
7. Again open your workspace. 
8. Start the server. 
9. Make some changes to html file, save. 
10. Refresh Simple Browser and you'll see the previous file version. The server doesn't wont to show changes.

### Expected behavior

Http.server should show saved in file changes.

### Example repository

https://github.com/Volodsher/01-1-html-css-/blob/main/hello_world.html

### Anything else?

Thank you

**Comment by axonasif** [comment]
I'm unable to reproduce your error, could you share a screen recording and your browser console logs after that happens?

**Comment by Volodsher** [comment]
Thank you for reply! Would you pleas tell me what format of screen recording? thanks

**Comment by Volodsher** [comment]
It's weird but now everything is working fine. But if I have again this problem is there any command to clear cache on the server or something else? also one more question, if I use simple preview do I have to refresh the page every time from the server root directory or it should be live: when I safe changes they automatically refresh on the Simple Browser page?

**Comment by Volodsher** [comment]
https://user-images.githubusercontent.com/19806253/154800880-c2caf11a-b224-4fb7-bbad-7a1a80c3bf29.mp4

**Comment by richard-owen-dev** [comment]
I'm having the exact same issue as you. basically 1 for 1 based on your video share.

**Comment by Volodsher** [comment]
> I'm having the exact same issue as you. basically 1 for 1 based on your video share.
Hi Richard-owen-dev, I was using it 6 months ago (I'm using VSC on my machine) so do not remember exactly how I solved it. It was working some times. But probably I was just using browser window.
