### ISSUE TITLE
Prebuilds don't run due to `last backup failed: workspace does not exist.`

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#8326]
### Bug description

The Prebuild logs display the following console output in the dashboard:

```
Connecting to workspace logs...

last backup failed: workspace does not exist.
```

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/788827/154807097-4e146d08-41ac-4ea0-983b-289d45e7624b.png" />
</details>

However, the list of Prebuilds for that project lists the above Prebuild as "READY".

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/788827/154807172-b31afcf8-ca4c-4399-8cf1-b4586dd5be65.png" />
</details>

### Steps to reproduce

1. Create a new repository in GitHub
2. Commit a `.gitpod.yml` file with the following content
    ```yaml
    image: gitpod/workspace-postgres

    tasks:
      - command: echo ""
    ```
3. Connect the project to Gitpod via https://gitpod.io/new
4. Check the Prebuild that was started automatically

### Workspace affected

N/A

### Expected behavior

The Prebuild runs, shows the workspace logs and is reported as READY on the relevant screens in the dashboard.

### Example repository

https://github.com/mikenikles/gitpod-test-postgresql

**Comment by kylos101** [comment]
There are actually two problems here:
1. The prebuild failed, hinting `last backup failed: workspace does not exist`.
2. The prebuild is indicated as Ready, but, no workspace can be started from it. @geropl does this warrant a separate issue, or is it already solved with ongoing prebuild work you have in-flight?

**Comment by kylos101** [comment]
This appears to heavily impact prebuilds, [753 in the last day.](https://cloudlogging.app.goo.gl/zcQEx67QCaMFXjxG7)

We'll want to see if we can recreate the problem (i.e. is it related or not to incremental prebuilds, and socialize next steps).

This is a research issue. The output isn't necessarily a code fix - but it could be - it depends what is found.

**Comment by geropl** [comment]
> @geropl does this warrant a separate issue, or is it already solved with ongoing prebuild work you have in-flight?

@kylos101 That's something we just fixed. First part will roll out today, 2nd end of week (I think).

**Comment by kylos101** [comment]
I am going to close this, in favor of https://github.com/gitpod-io/gitpod/issues/8326 (which is the same issue), and add that back to the webapp inbox.

@mikenikles please subscribe to 8326 for continued discussion?

**Comment by kylos101** [comment]
I was a bit hasty there, this is for prebuilds, which won't have a backup like a regular workspace...
