### ISSUE TITLE
Allow additional users for providers of telemetry data

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#8331]
As a quid pro quo, we should offer additional users to those who provide data. As a starting point, we should add an additional 10 users to those who provide data.

To ensure that this doesn't it doesn't cause unexpected behaviour when a user declines to send data, we need to include tests when there are 10+ users. We have two options for the correct behaviour - we need to decide which one we want:
 - prevent users 10+ from logging in (with an appropriate error message)
 - only allow disabling of telemetry when additional seats have been added

**Comment by lucasvaltl** [comment]
I would close this because I think this will not get done soon. We can re-open if this becomes relevant.
