### ISSUE TITLE
VS Code typing errors on Android

### ISSUE THREAD

**Issue by alan-christian** [gitpod-io/gitpod#8333]
### Bug description

when I open gitpod on android it does not type correctly in the file it keeps bugging and deleting things

### Steps to reproduce

- open gitpod on android
- type something on a file

### Expected behavior

to type normally

**Comment by jankeromnes** [comment]
Thanks for reporting this problem @Nerd00F!

I can confirm that Gitpod's VS Code editing experience is erratic on Android. Both the editor and the terminal are affected.

Sending this issue to team IDE for consideration.

**Comment by Nerd00F** [comment]
Thanks.

**Comment by axonasif** [comment]
Hi @Nerd00F 
- I recommend using [Kiwi](https://kiwibrowser.com/) browser(android), it features a full-blown Dev-console like desktop, chromium based and OSS.
- Visit https://gitpod.io/ and from your browser menu use `Add to Homescreen` button. (Works for most chromium browsers such as Google-Chrome, Brave, Opera, Kiwi, Vivaldi etc.)
- Your browser will detect it as PWA and install the app.
![Screenshot_20220203-134013](https://user-images.githubusercontent.com/39482679/152304135-fca0e248-ff92-4f89-a5f7-522e20638eb0.png)

Tip: Use [CodeBoard](https://play.google.com/store/apps/details?id=com.gazlaws.codeboard&hl=en_US&gl=US) if you don't have a physical keyboard and mouse(which is nice if you wanna do some serious stuff) and it won't bug you while typing in terminal or anywhere else in VSCODE :wink:
cc @jankeromnes

**Comment by Nerd00F** [comment]
that's a lot of tools, he he

**Comment by axonasif** [comment]
Not a lot I think, hardly 3 😬
