### ISSUE TITLE
"Open in VS Code" creates an empty `gitpod_ssh_config-*` file

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#8337]
### Bug description

When I click "Gitpod: Open in VS Code" in a running workspace, local VS Code starts and times out after 30 seconds.

I notice three files were created:

```
mike@a:~$ ll /tmp/gitpod*
-rwxr-xr-x 1 mike mike 17600828 Feb 20 21:02 /tmp/gitpod-local-companion-131899-PlTM5iUMIU3H*
-rw-rw-r-- 1 mike mike      188 Feb 20 21:02 /tmp/gitpod-local-companion-131899-PlTM5iUMIU3H.log
-rw------- 1 mike mike        0 Feb 20 21:02 /tmp/gitpod_ssh_config-131899-09rps1bh3aqL
```

I suspect local VS Code can't connect to the Gitpod workspace because the ssh config file is empty.

OS: Ubuntu 21.10

VS Code
```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:29.527Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.0-28-generic snap
```

### Steps to reproduce

1. Start a workspace
2. Click "Gitpod: Open in VS Code"
3. Check VS Code output
4. Run `ll /tmp/gitpod*` in the terminal

### Expected behavior

Local VS Code connects to the running Gitpod workspace

**Comment by axonasif** [comment]
Thanks for raising @mikenikles! Our ide-team will be updating the connection method of VS Code desktop soon to direct SSH without any helper program, hopefully that would resolve the issue.

- https://github.com/gitpod-io/gitpod/issues/7184
