### ISSUE TITLE
500

### ISSUE THREAD

**Issue by naveen1749** [gitpod-io/gitpod#834]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by jankeromnes** [comment]
Hi @naveen1749, thank you for filing this issue.

If you encountered a bug with https://gitpod.io, please reply by describing what exactly you tried; what you expected to happen; and what happened instead.

If you just had a question, please feel free to ask.

Thanks!

**Comment by naveen1749** [comment]
It's will not be open when i open 500 msg displayed

**Comment by jankeromnes** [comment]
Thanks @naveen1749, and sorry about that problem.

What Gitpod URL are you trying to open? And could you please share a screenshot of the error message? (It may contain additional hints that may help us reproduce and troubleshoot this problem.)
