### ISSUE TITLE
Track snapshot usage with success and access-error events

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#8340]
This is a followup issue to #8257.

Since this change may break some existing workflows, it would be good to add usage tracking for workspace starts with snapshot URLs so that we can monitor both success and (importanly) the error cases.

**Comment by jldec** [comment]
@jankeromnes do you know if there is already a log event we could track for these errors (in which case the urgency of this issue may be lower?)

**Comment by jankeromnes** [comment]
I think there is no such log event. Will try to send a quick Pull Request here.
