### ISSUE TITLE
Address versioning format of gp CLI

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#8342]
The GP CLI output for the `version` command "appears" incorrect. It is non-obvious for an end-user to use this metadata to be able to trace back this version and understand what it's referencing. 

![image](https://user-images.githubusercontent.com/5528307/154938671-50d7d561-3edc-4683-909c-b74ee1484f03.png)

**Comment by akosyakov** [comment]
We version as all other components in Gitpod to track back to CI and commit, i.e. it reflects with which CI job is was built built from which we can track a commit. What do you want to change?

**Comment by loujaybee** [comment]
I don't think that's will be obvious to a user.

If this output is used mostly by Gitpod staff for debugging purposes, I suggest we 

1. Rename it and hide the command from the help page of the CLI [[1](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-cli/cmd/version.go#L19)]
2. Swap the output to key-value/formatted output to make it more clear what the metadata is:
```sh
Branch name: original-branch-build-name
Commit hash: 2d443923f2c1e59d926fc441d87d11ae354b51b5
..etc
```
3. Swap the public `gp version` for something more standard e.g. a commit hash / semver version.

**Comment by akosyakov** [comment]
Yes, I think we can hide from the help page. We introduce this option only to verify that we provide proper x-version header in request to server. Other options are more involving and I don't think very valuable to a user. A user can usually assume that everything is up-to-date. We deploy as soon as possible and workspace get cycled daily, as soon as you restart a workspace you get a latest gp-cli.
