### ISSUE TITLE
Font broken on ubuntu 20.10 

### ISSUE THREAD

**Issue by veritem** [gitpod-io/gitpod#8343]
### Bug description

![image](https://user-images.githubusercontent.com/53856673/154950740-3a950199-67e2-4a17-82ad-58aeb1c29c7c.png)

### Steps to reproduce

Open gitpod on ubuntu 20.10

**Comment by axonasif** [comment]
@veritem can you please provide more info and share some steps that we can follow to reproduce your issue?

**Comment by veritem** [comment]
Open any repo on a fresh install of ubuntu 20.04.  Font's looks broken  in gitpod same as like this.
![image](https://user-images.githubusercontent.com/53856673/154959058-9350ed09-af25-4e8c-b7a3-450334a0d8f4.png)
