### ISSUE TITLE
applying cgroup configuration for process caused: failed to write "0-15"

### ISSUE THREAD

**Issue by Meldiron** [gitpod-io/gitpod#8347]
### Bug description

When I created a new workspace, I got this error:

![image](https://user-images.githubusercontent.com/19310830/154965653-1a46fb97-195b-4cf4-aee7-3195e6604b6e.png)
Text:
```javascript
failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:385: applying cgroup configuration for process caused: failed to write "0-15": write /sys/fs/cgroup/cpuset/kubepods/burstable/pod40596c03-6f9f-4f3d-b9ec-ca8030e39ada/5de8e929a0db52557d8bb89f6b70a00cb8b6428ce2a47717b7c0d97d76b60429/cpuset.cpus: invalid argument: unknown; last backup failed: workspace does not exist.
```

It happened 3 times, but fourth one was fine. I can see my workspaces in Gitpod dashboard:

![image](https://user-images.githubusercontent.com/19310830/154965941-c2570761-0e9c-4a37-9a3b-ffb20a3ce148.png)

Successful: `appwrite-functionsstarte-4xcd0c4dpfq`
Failed: `appwrite-functionsstarte-nlwnzo2s6qb` `appwrite-functionsstarte-ifubr51x9fe`

### Steps to reproduce

1. Visit repository https://github.com/appwrite/functions-starter/tree/dev
2. Click `Gitpod`from browser extension

### Workspace affected

appwrite-functionsstarte-ifubr51x9fe,  appwrite-functionsstarte-nlwnzo2s6qb

### Expected behavior

Successfully open workspace.

### Example repository

https://github.com/appwrite/functions-starter/tree/dev

### Anything else?

If I went into Gitpod dashboard and clicked the workspace that was red (failed initially), I was able to enter it, and it went to green.

The error occurred 3 times in a row, but 4rth time it worked fine.

**Comment by axonasif** [comment]
2 more reports:
- @Dragondscript on [discord](https://canary.discord.com/channels/816244985187008514/839379835662368768/945313058027343942), ws id: gameplexlaunche-api-1829qwitao5.ws-eu33
- mechad on [discord](https://canary.discord.com/channels/816244985187008514/945313233819029574/945314410220617811), ws id: ?

**Comment by Furisto** [comment]
We had a misconfigured node. We removed it from the node pool. Please post here if you are still seeing problems.

**Comment by dragonDScript** [comment]
Thanks for the quick response. Working now

**Comment by axonasif** [comment]
Perhaps we can close it now.
