### ISSUE TITLE
Gitpod commit author

### ISSUE THREAD

**Issue by mihairaulea** [gitpod-io/gitpod#8349]
Hi,

I see that sharing my Gitpod link to other team members makes all the commits be under my name. How can i share my workspace with others (ideally, without them having to open an account with gitpod), and get the correct github/gitlab credentials for the commit?

Is this even possible? Thanks.

**Comment by axonasif** [comment]
Duplicate of https://canary.discord.com/channels/816244985187008514/945336704812863569/945337294498439219
