### ISSUE TITLE
Open issues from gitpod

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#835]
It would be awesome if you could check up on issues from the repo you're working on without leaving gitpod

**Comment by jankeromnes** [comment]
That's a great idea, and currently one of the biggest pain points when automating a repository.

See also #726.

**Comment by JesterOrNot** [comment]
So should I close this in favor of #726?

**Comment by jankeromnes** [comment]
Good idea, I think this request is included in the scope of #726. I hope we can make some progress there soon. 🙂
