### ISSUE TITLE
[Design] Team Plans v2

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8352]
## Context

- Part of [Epic: Simplify team plans and align with project teams](https://github.com/gitpod-io/gitpod/issues/7759)
- See also [User's Perspective](https://www.notion.so/gitpod/Aligning-Team-Plans-and-Teams-9073db94359549918ab5c85cc364de46#86e9dbfeaf1e40808fd822a15e902bcb) in the RFC

## Goals

We would like to implement a new "**Paid Plans**" page under Team Settings that allows:
- Seeing **how much your team costs per month**: Show whether or not your team currently has a paid plan, which one it is, and what its monthly price is based the current number of members in your team
- **Buying a paid plan** (either "Professional" or "Unleashed") for all members of the team
- Accessing the "Chargebee portal" (having a simple "Billing" link or button somewhere does the job)

### Non-goals

- **Managing seats and members**: Members are already managed via the Members page, Seats is a concept we no longer wish to show in the UI
- **Student Unleashed**: This plan adds too much complexity (having to check for student status on members and/or owner) and gets barely used (most University contracts actually use a regular "Unleashed" team plan with a customized price in Chargebee)
- **Upgrade/Downgrade flows?** Technically, the "Chargebee portal" already allows users to cancel any paid plan -- thus users can already cancel one plan and pick up another easily, without us implementing even a "Cancel" flow -- however, maybe having a "Cancel" option in the UI seems like a nice-to-have. Upgrade/Downgrade on the other hand sounds high-effort low-value.

### Card-based UI?

Maybe we could have a simple card-based UI like our current [Individual Plans](https://gitpod.io/plans)? E.g. with the cards:
- Free: 10 members x 0€ = 0€ / month
- Professional: 10 members x 23€ = 230€ / month
- Unleashed: 10 members x 35€ = 350€ / month 

### Legacy Team Plans

<table><tr><td>
<img width="1435" alt="Screenshot 2022-02-21 at 16 14 57" src="https://user-images.githubusercontent.com/599268/154982828-d4b692e5-df29-4df7-8fa0-351dd472ece8.png">
</td><td>
<img width="1437" alt="Screenshot 2022-02-21 at 16 15 16" src="https://user-images.githubusercontent.com/599268/154982840-332d4b2d-3eae-42b5-9559-d235b15bb42c.png">
</td></tr></table>

- Shows a list of all your Team Plans (not needed for Team Plans v2, since one team can only have 0 or 1 paid plan)
- Allows managing members and seats (not needed for v2, see [Non-goals](#non-goals))

### Individual Plans

<table><tr><td>
<img width="1439" alt="Screenshot 2022-02-21 at 16 15 35" src="https://user-images.githubusercontent.com/599268/154982921-3aad30f2-7b77-43e0-9058-7d2ec65fc5cf.png">
</td><td>
<img width="1435" alt="Screenshot 2022-02-21 at 16 15 51" src="https://user-images.githubusercontent.com/599268/154982936-ff8dad7c-c2eb-42ea-a93f-a034879b11fc.png">
</td></tr></table>

- Shows your currently active Individual Plan (with variations like Free / Professional Open-Source, and Unleashed / Student Unleashed -- but such variations are currently not needed in the Team Plans v2 UI)
- Allows upgrading (immediately) or downgrading (at the end of the billing cycle) with complicated explainers (maybe not needed for Team Plans v2 if we go with the easy "just cancel & re-purchase" solution)

**Comment by gtsiolis** [comment]
Looping in @jankeromnes @geropl @jldec in case we need to keep this issue open or open any follow up smaller issues with more concrete action items.
