### ISSUE TITLE
Prebuild fails when trying to use pnpm

### ISSUE THREAD

**Issue by akoenig** [gitpod-io/gitpod#8353]
### Bug description

When using `pnpm` in the `init` task, the prebuild fails with:

![image](https://user-images.githubusercontent.com/224910/154988093-9a7a30ff-6148-4d54-b359-1a621527a277.png)

### Steps to reproduce

Add the following `init` task and trigger a prebuild:

```yml
tasks:
  - init: pnpm install && pnpm run compile
``` 

### Expected behavior

Should be possible to use `pnpm` within a prebuild.

**Comment by JanKoehnlein** [comment]
Thanks for reporting. Unfortunately, I didn't manage to reproduce this. Can you provide a (minimum) example repository?
