### ISSUE TITLE
Request getWorkspace failed with message: No identity with primary email for user: [...]!

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8359]
### Bug description

A recent incident affected all members of the Gitpod team and caused starting workspaces to fail with:

```
Request getWorkspace failed with message: No identity with primary email for user: [...]!
```

<img width="400" alt="No identity with primary email for user" src="https://user-images.githubusercontent.com/599268/154998921-644148ca-322c-42e0-9784-c16f5cbcc423.png">

This looks like a come back of this issue: https://github.com/gitpod-io/gitpod/issues/6035

### Steps to reproduce

1. Be part of a team where another team member has no identity in `d_b_identity` (which should itself not really happen)
2. Starting a workspace always fails with the above error until the no-identity member is removed again

### Expected behavior

Several expectations were unmet:
- A user should never have zero identities in `d_b_identity` (already mostly addressed by https://github.com/gitpod-io/gitpod/pull/7946, but I believe this issue reveals another way this can happen)
- If `User.getPrimaryEmail(member)` throws an error for even just one member in `TeamDB.findMembersByTeam(teamId)`, it should not make the entire method fail. Instead, it should probably catch the error, and set `primaryEmail` to `(unknown)`.

https://github.com/gitpod-io/gitpod/blob/2479e485496cd29af37870f1be5bd4e56561d56d/components/gitpod-db/src/typeorm/team-db-impl.ts#L59

### Anything else?

The user doesn't remember doing anything in [/integrations](https://gitpod.io/integrations).

Instead, here is what we believe happened:
1. User created a Gitpod account (let's call it `5773b3a1`)
2. User joined the Gitpod team
3. User noticed the wrong primary email displayed in the Members list
4. User removed themselves from the team again
5. User changed their primary email on GitHub, and added their `@gitpod.io` email as well
6. User tried to join the team again, which seems to have worked
7. (User added some user environment variables)

However, for some reason:
- Somewhere along this flow, a new Gitpod account was created (let's call it `71f05ca8`), and it somehow "took over" or "stole" the GitHub identity of the account `5773b3a1` (which was itself left with zero identities in the DB)
- We know steps 6. and 7. were completed as the old account (`5773b3a1`), thus adding a member without any identity or email address to the Gitpod team (breaking getWorkspace for everyone in the Gitpod team)

Questions:
- Why did Gitpod create a new account?
- Can this possibly happen if you create an account, then log out, then change your primary email in GitHub, then log in again? 🤔
- Or maybe if you use a different browser to change the GitHub primary email and log into Gitpod, thus leaving your other browser still logged into the now-identity-less account?

**Comment by jldec** [comment]
Scheduled.

Let's improve resilience first to scenarios where an account has no identities.
The 2 known places that break are:

1. If the account with no identy is part of a team, starting a workspace (for a project in the team?) fails.
2. The admin/users detail page is blank with the same error message e.g. https://gitpod.io/admin/users/

Reproducing (and preventing) this situation could be tricky. I suspect that your theory of leaving the browser open and logged in while modifying identities is very close - I spent quite a bit of time trying to repro exactly this recently, but was unable to find a reliable repro for the identityless account. I think that the repro may involve using GitLab (not just GitHub). 

see [slack](https://gitpod.slack.com/archives/C02EN94AEPL/p1639775848125900) (internal) and
