### ISSUE TITLE
Workspace startup screen stuck in "Running"

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#8369]
### Bug description

When I come back to a workspace that previously timed out, I see the usual workspace startup screen (e.g. pulling container image, etc.). At the end, the screen is stuck in the "Running" state.

I have to manually stop and restart the workspace to access it again. No browser console errors.

![image](https://user-images.githubusercontent.com/788827/155046220-032a9275-efe9-4fde-a192-64706b2b0003.png)

### Steps to reproduce

These steps are what has caused the bug twice over the weekend.

1. Start a workspace & work in it for a while
2. Close the laptop lid
3. Come back a few hours later (to test, it's likely enough to wait until the timeout kicks in and the workspace stops)
4. Start the workspace from the same tab you used in step 1
5. Wait until the workspace startup screen shows "Running"

### Expected behavior

Once the workspace is running, VS Code loads and I can continue to work in the workspace.

### Anything else?

**Workaround**
1. Open the Gitpod dashboard
2. Manually stop the workspace
3. Manually start the workspace

**Browser**

Brave: Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)

**Comment by axonasif** [comment]
I've been seeing this before it switches to the VSCODE interface. Although it doesn't stay stuck for me.

**Comment by mikenikles** [comment]
I started a brand-new workspace moments ago and it is now also stuck on that screen. A page reload or a click on "Open Workspace" results in the same situation.

If a workspace ID helps troubleshoot this, the most recent one with the issue is `webstonehq-platform-4801jrx8ut5`

**Comment by jccalvojackson** [comment]
same here

**Comment by geropl** [comment]
This is another instance of https://github.com/gitpod-io/gitpod/issues/8226

Closing here. :pray:
