### ISSUE TITLE
VS Code Desktop: Auto forward ports from .gitpod.yml (sometimes ports are not detected or shown)

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#8377]
Right now we rely on Remote SSH for VS Code Desktop support for port forwarding. It seems to have some auto forwarding built-in but it does not work always. We also observed that some extensions seem to be able to forward ports as well. Since we have a Gitpod extension running in their server we could investigate auto forwarding of ports from .gitpod.yml as well.

**Comment by axonasif** [comment]
I discovered a vscode settings 👀 
```json
"remote.SSH.defaultForwardedPorts": [
    {
        "localPort": 8080,
        "name": "example",
        "remotePort": 8080
    }
],
```

**Comment by BrandiATMuhkuh** [comment]
Thank you for the `"remote.SSH.defaultForwardedPorts` trip. This solved my problem. While I did set the ports in the gitpod.yml, it seems to not pick them up in VSCode after I restarted VSCode. Now it all works!

**Comment by loujaybee** [comment]
Cross referencing this comment, with user also mentioning that they don't see ports: 

- https://github.com/gitpod-io/gitpod/issues/9262#issuecomment-1144391518

**Comment by akosyakov** [comment]
@mustard-mh tried to reconfigure machine settings of VS Code to scan for all ports, but it does not seem to work
