### ISSUE TITLE
Oh, no! Something went wrong! OutOfmemory: Pod Node didn't have enough resource: memory, requested: 3435973837, used: 65865462583, capacity: 66388008960

### ISSUE THREAD

**Issue by JakubKocerha** [gitpod-io/gitpod#8381]
### Bug description

Oh, no! Something went wrong!
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 3435973837, used: 65865462583, capacity: 66388008960

### Steps to reproduce

Attempting to launch my existing Gitpod workspace.

### Workspace affected

https://gitpod.io/start/#jakubkocerha-boutiqueado-k5hjwzpdov4

### Expected behavior

Have my existing Gitpod workspace launch without any errors.

### Anything else?

https://gitpod.io/start/#jakubkocerha-boutiqueado-k5hjwzpdov4

**Comment by sagor999** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/8238
