### ISSUE TITLE
Prebuild is running but I cannot see the log

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#8394]
### Bug description

It seems that the headless log server is not able to find the prebuild?

![image](https://user-images.githubusercontent.com/22901/155166758-2753e60d-4a6c-41eb-8730-2fb681e87830.png)

### Steps to reproduce

Start a prebuild, check the log?

**Comment by kylos101** [comment]
Hi @shaal , this is a duplicate of #8446 and item number 1. I am going to close this, and recommend you subscribe to that issue.
