### ISSUE TITLE
Cannot start elasticsearch service due to kernel settings

### ISSUE THREAD

**Issue by miketheman** [gitpod-io/gitpod#8399]
### Bug description

I've been searching high and low, and can't really figure out the right way to do this.

To run a docker-compose stack with an elasticsearch container alongside application containers, ES complains and exits with:

```console
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

The usual (non Docker-in-Docker) remediation for this is:
```console
$ sudo sysctl -w vm.max_map_count=262144
```
or persisting a change in `/etc/sysctl.conf` and rebooting ([docs ref](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/vm-max-map-count.html))

Where am I going wrong?

### Steps to reproduce

On Gitpod, I get:

```console
$ sudo sysctl -w vm.max_map_count=262144
sysctl: setting key "vm.max_map_count", ignoring: Read-only file system
```

See example repo for a real-life service run and fail.

### Expected behavior

The service should start up and remain up, not exit.

### Example repository

https://github.com/miketheman/gitpod-es-repro

**Comment by sagor999** [comment]
@csweichel @aledbf we can probably set this on base VM image. Any concerns?

**Comment by aledbf** [comment]
> Any concerns?

I think doing this at the node level could potentially increase the memory consumption of all applications running, not only in the workspace.

**Comment by miketheman** [comment]
My understanding is that this setting tells the kernel how much the maximum memory for a single process is allowed to consume, regardless of the actual amount of memory in use.
I might be wrong!

How would this setting increase memory consumption? Maybe it would allow memory-hungry applications to use more memfs/malloc memory, but it can never exceed the amount of memory configured for the container or the node, right?

**Comment by sagor999** [comment]
@miketheman alternatively have you considered switching elastic into development mode? it should log that as warning in that case instead of exception: https://www.elastic.co/guide/en/elasticsearch/reference/master/system-config.html#dev-vs-prod

**Comment by miketheman** [comment]
@sagor999 I hadn't, but it's unclear how to set development mode from that page, or even from these docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html#dev-vs-prod-mode

Were you able to use my reproduction repo (linked in original report) to start the service successfully somehow?

**Comment by csweichel** [comment]
The value seems to control the number of pages a process can malloc: https://sysctl-explorer.net/vm/max_map_count/. The effect on node stability is unclear though. I'd also much prefer we try the development mode first, prior to making such changes with unknown outcome.

**Comment by sagor999** [comment]
@miketheman just tried your repo and elastic seems to be working fine? I noticed you made a change to switch it to single-node mode which I believe is what switching it into development mode. 
Let me know if this issue is resolved for you now.

**Comment by miketheman** [comment]
Thanks for the pointers. I went ahead and tried out the [single-node (development) mode](https://github.com/miketheman/gitpod-es-repro/commit/e7aeca60f695913a401c98663e8f94e16652ccba), and it looks like that works for now.
If I ever needed to run a multi-node cluster for testing, we'd be back in the same spot, but that's a problem for another day.
