### ISSUE TITLE
Support LaTeX 

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#84]
Idea: detect if LaTeX is used in a project and use a Docker Image for the workspace that has a LaTeX distribution installed. If I remember correctly, a LaTeX distribution is easily 1GB in size, so maybe we don't want to add it on top of workspace-full.

There is a great example from @rjkerrison on how this can look like with pandoc: https://github.com/rjkerrison/pandoc-publishing/blob/master/gitpod.Dockerfile

**Comment by Kreijstal** [comment]
is there a docker for this?
