### ISSUE TITLE
Workspaces created via browser opened from Gateway go to VS Code, not the splash page. 

### ISSUE THREAD

**Issue by AnnaPrints** [gitpod-io/gitpod#8409]
### Bug description

There are some scenarios of using Gateway+GitPod which can confuse users.
When user create the first workspace via Dashboard in a browser, default preferences are:
Browser Editor: VS Code, Desktop Editor: None

### Steps to reproduce

**Steps:**

1. Launch Gateway, connect GitPod plugin
2. Click on “Connect to GitPod” option
3. Click on “Connect in Browser”
4. Connect GitHub/GitLab/Bitbucket
5. Go to Dashboard and create a new workspace
6. Try to connect it

See the **result**: https://drive.google.com/file/d/1wOFuhtiBLMfs930iNl7SMka3W-ZuA5kv/view?usp=sharing
What helps in this situation: to change Desktop Editor from None to a JetBrains IDE and create a new workspace with these settings.
But I don’t really think that users would guess what to do.
I think we should handle such situations and add some tips or change the flow.

**Comment by loujaybee** [comment]
Hey @AnnaPrints! Thanks a lot for the feedback! 

Yeah, the complication here is that workspaces are created based on preferences and the IDE / backend is baked into the workspace on start (at least, currently). JetBrains gateway is (currently) just a list of those workspaces, and so it will respect your user preferences... however you are right, if you're coming from gateway you quite likely want a JetBrains IDE, and not VS Code in the browser. A couple of solutions on our side: 

1. Provide IDE settings that allow a user to open their workspace with an ad-hoc IDE from within the JetBrains Gateway, something similar to: (https://github.com/gitpod-io/gitpod/issues/8573) 
2. Add an "indicator" into the Gateway about what IDE the current workspace preference is set to, and allow the user to directly override / update their preferences from within JetBrains (**figure 1**). 
3. Not a fix, but an additional nice-to-have, would be a prominent link to your Gitpod preferences to update the preferred / default IDE directly, possibly from within the existing cogs menu (**figure 2**).

| Figure 1      | Figure 2 |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/5528307/156601505-4d9bae21-5f77-4759-b776-b5dfbe962d52.png)      | ![image](https://user-images.githubusercontent.com/5528307/156601649-e2de2f5e-a121-45f7-8e35-79b842d465d9.png)       |

Relates to: https://github.com/gitpod-io/gitpod/issues/6874
