### ISSUE TITLE
unable to parse URL from normalized contextURL: 'snapshot/1234-abcd' TypeError: URL constructor: snapshot/1234-abcd is not a valid URL.

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8411]
### Bug description

There is a new error being logged in workspaces list when you've opened a snapshot before. This also causes the displayed workspace context URL to be `undefined`:

<img width="555" alt="Screenshot 2022-02-23 at 15 21 18" src="https://user-images.githubusercontent.com/599268/155343918-3f038b92-1790-4833-93f5-eae27871a665.png">
<img width="707" alt="Screenshot 2022-02-23 at 15 21 06" src="https://user-images.githubusercontent.com/599268/155343912-1786df45-c9a8-44b4-88aa-6d8c916fab1c.png">

### Steps to reproduce

1. Open a snapshot in Gitpod
2. Open your Workspaces list

### Expected behavior

Instead of trying to parse the `snapshot/1234-abcd` context as a URL, and showing `undefined` as the context, the workspaces list should just show `snapshot/1234-abcd` as plain text (not a link) for snapshots here:

https://github.com/gitpod-io/gitpod/blob/5ff578ed67e45f62932c6ac148324f015b9104ae/components/dashboard/src/workspaces/WorkspaceEntry.tsx#L132

https://github.com/gitpod-io/gitpod/blob/5ff578ed67e45f62932c6ac148324f015b9104ae/components/dashboard/src/workspaces/WorkspaceEntry.tsx#L145-L147

**Comment by jankeromnes** [comment]
Looks like [ContextURL.getNormalizedURL](https://github.com/gitpod-io/gitpod/blob/5ff578ed67e45f62932c6ac148324f015b9104ae/components/gitpod-protocol/src/context-url.ts#L32) doesn't actually support snapshot URLs: it will remove the `snapshot/` prefix, then try to parse the rest as a URL, which fails:

https://github.com/gitpod-io/gitpod/blob/5ff578ed67e45f62932c6ac148324f015b9104ae/components/gitpod-protocol/src/context-url.ts#L91-L98

**Comment by geropl** [comment]
> However, I think it would be more helpful to show the actual value of ws.contextURL instead of "undefined", right?

@jankeromnes As it turns out: yes. But most importantly, we should review the usage og `getNormalizedContextURL` in `server`: I recall we used it there, and assumed it to always be an URL.

In general this issues shows our problems with our data model and how we treat `contextURL`. :confused:

**Comment by geropl** [comment]
To expand a bit: The motivation with `"undefined"` was for us not to feel "safe" again with the current state, but press for a fix of the data model until we don't see something like this again.
