### ISSUE TITLE
[licensing] Treat any case where we do not have a valid license as if no license is installed

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#8412]
Currently, an invalid license prevents any users to sign up. An installation with an invalid license should not be in a worse position than an installation with no license at all.

We have this behavior already to some extent so that we don't return an invalid license but a default license for some cases, e.g. here:

https://github.com/gitpod-io/gitpod/blob/896fe39ccf456e132a4c7dba968c18f7394e6fc8/components/licensor/ee/pkg/licensor/replicated.go#L117-L119

However, there are some cases where we don't have a valid license, e.g. when the license server from Replicated is not reachable etc.

I would propose to change the implementation like this:
- Don't return the default license in `newReplicatedEvaluator()` but return the invalid license with the proper reason/explanation why the license is invalid.
- In the function `HasEnoughSeats`, don't respond with `false` when the license is invalid but call `HasEnoughSeats` from the default license in that case (same for other methods like `Enabled(...)`).

That has the following advantages:
- We still have the proper (invalid) license in place and could e.g. log why the license is invalid.
- We could add a dashboard that shows the (invalid) license (see #8413) .
- No installation acts worse than the default license behavior.

**Comment by gtsiolis** [comment]
See also https://github.com/gitpod-io/gitpod/issues/3918 for historical context and in case we can close one of these two issues as duplicate. Cc @corneliusludmann @AlexTugarev

**Comment by corneliusludmann** [comment]
Thanks, @gtsiolis. I think the other issue is more about handling error messages. I added this to our project board since this is something that I had on my radar as well.

**Comment by MrSimonEmms** [comment]
See https://github.com/gitpod-io/gitpod/pull/8593#issuecomment-1062851893

**Comment by gtsiolis** [comment]
Closing as the `licensor` component has been removed in https://github.com/gitpod-io/gitpod/pull/16983. Cc @aledbf @AlexTugarev @geropl
