### ISSUE TITLE
[licensing] Add a license page to the admin dashboard

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#8413]
Add a page to the admin dashboard that shows the installed license with properties (number allowed users, actual users, domain restriction etc.).

**Comment by gtsiolis** [comment]
This is also a customer request, see https://github.com/gitpod-io/gitpod/issues/5743#issuecomment-942284202 and [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1634129886345000) (internal). Cc @JohannesLandgraf 

Feel free to add this to the 🥯 product design board[[1](https://github.com/orgs/gitpod-io/projects/29)] if this is something we'd like to work on soon. Cc @corneliusludmann

**Comment by MrSimonEmms** [comment]
## Proposed approach

The licensor component doesn't currently have any way of reading the license data - at the moment it's "check _x_ is available" and returns a boolean.

1. Add a `getLicense` type method to the [LicenseEvaluator](https://github.com/gitpod-io/gitpod/blob/main/components/licensor/typescript/ee/src/index.ts#L22) which will return the relevant information (seats, license type, domain etc) from the licensor. This may be the Gitpod, Replicated, default or fallback license depending upon what's loaded/validated. This would also need adding to the C and Golang modules that this talks to
2. Add a "License" section to the dashboard. See [this PR](https://github.com/gitpod-io/gitpod/commit/f9ec0f8cc6a137aaa05b746ca63724c12e040198) for one way of adding a section to the React app

**Comment by nandajavarma** [comment]
We should also be able to list the occupied and remaining seats

**Comment by gtsiolis** [comment]
Moved this to to [_Scheduled_](https://github.com/orgs/gitpod-io/projects/29). Cc @nandajavarma 

[ETA](https://en.wikipedia.org/wiki/Estimated_time_of_arrival): Will starting working on the understanding the problem and designs for this, tomorrow. Designs specs will probably land before the end of this week. ⏱️

**Comment by gtsiolis** [comment]
Adding below the first design specs for this feature. Elements can change accordingly per need. Feedback is welcome!

| Community | Free | Free (Limits Reached | Professional | 
|-|-|-|-|
| <img width="1440" alt="Community" src="https://user-images.githubusercontent.com/120486/161831724-56d329ce-5d43-4293-8aa5-1ea3df19d69a.png"> | <img width="1440" alt="Free" src="https://user-images.githubusercontent.com/120486/161831729-44457d71-78fd-4ee9-86c1-11b804a42847.png"> | <img width="1440" alt="Limits" src="https://user-images.githubusercontent.com/120486/161831731-fd05d6f7-0ddc-4efb-b106-7da9c9b1ff02.png"> | <img width="1440" alt="Profressional" src="https://user-images.githubusercontent.com/120486/161831735-a2ef6ff2-052a-4613-bde2-515e263e80a8.png"> |

**Comment by MrSimonEmms** [comment]
@gtsiolis I love these. I genuinely wish I could do simple, elegant designs like that.

I think these swatches capture all of the different elements and combinations 👍🏻

**Comment by gtsiolis** [comment]
@nandajavarma I'm adding below some specs for the dark theme color scheme, you can find the specs also in the Figma file linked above in https://github.com/gitpod-io/gitpod/issues/8413#issuecomment-1089213673.

| No License | License Limits | Active License |
|-|-|-|
| <img width="1440" alt="Community" src="https://user-images.githubusercontent.com/120486/163012848-b243b63e-0eec-413a-b94d-724c0165fba5.png"> | <img width="1440" alt="Community-1" src="https://user-images.githubusercontent.com/120486/163012858-3687abf4-74a9-4024-b53b-51a0a8e83d44.png"> | <img width="1440" alt="Community-2" src="https://user-images.githubusercontent.com/120486/163012860-80778f67-5eaa-4e04-bcb0-eb49a2b7d8e6.png"> |
