### ISSUE TITLE
Installing Java via SDK does not stay after one session

### ISSUE THREAD

**Issue by GamerCoder215** [gitpod-io/gitpod#8425]
### Bug description

I'm working on a Java Project, and I need Java 17. When I run `sdk install java`, it installs Java 17 (Termux).

However, after the session ends (Times out / Workspace Stops), Java 17 is gone, and I have to redo `sdk install java`.

I think it is also worth mentioning that my WakaTime plugin also asks for my API Key when this happens as well, showing that it affects extensions.

### Steps to reproduce

1. Open a workspace, not having Java 17 (optionally WakaTime)
2. Install Java 17 via `sdk install java` (optionally add WakaTime and input an API key).
3. Reload session (stop workspace and restart)

Java 17 does not exist anymore and WakaTime asks again for an API Key.

From my experience, this happens around 80% of the time, sometimes it saves, other times it does not.

### Workspace affected

teaminceptus-noobysmp-4gzepvsqibn

### Expected behavior

Java 17 and WakaTime should be installed and be working properly.

**Comment by kylos101** [comment]
Hey @GamerCoder215 :wave: ,

Have you tried our [Java 17 image](https://hub.docker.com/r/gitpod/workspace-java-17) as a base image? [These instructions](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile) will help you configure and build a custom dockerfile for your project.

Also, you're encouraged to build custom docker files, using our [base images](https://hub.docker.com/u/gitpod) as a starting point. 

Lastly, anything you persist to `/workspace` in a given workspace will be available to you the next time you start that workspace. When you install things (like with `apt`) they don't persist, unless they were installed as part of your custom dockerfile.

Please let us know if you need anything else? I'm going to close this for now, but, you're welcome to comment and I'll gladly reopen. Cheers!
