### ISSUE TITLE
Externally loaded images are manipulated

### ISSUE THREAD

**Issue by dword-design** [gitpod-io/gitpod#8426]
### Bug description

When I load an image from an external URL, it seems to be manipulated in some way, there is a different image coming through than the original one.

### Steps to reproduce

See this minimal example and its readme:
https://github.com/dword-design/try-gitpod-git-lfs

It has an image stored in the repo and when downloading it via `wget`, the Git status will be modified. Works locally, works in Docker but not in GitPod.

It looks a bit like there is some image manipulation service going on that optimizes images but which will lead to failing tests.

### Expected behavior

Images are not modified when loading them from an external URL.

### Example repository

https://github.com/dword-design/try-gitpod-git-lfs

### Anything else?

There is a [Discord discussion](https://discord.com/channels/816244985187008514/816246578594840586/943193473509650482) and an open email.

**Comment by dword-design** [comment]
Any news on this? This is a blocker for visual tests inside GitPod.

**Comment by sagor999** [comment]
@dword-design I just tried it out... but do not see `file.png` being modified. unless I am missing something?
Output from gitpod:
```
gitpod /workspace/try-gitpod-git-lfs (master) $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> yarn start
> }
yarn run v1.22.17
$ wget https://github.blog/wp-content/uploads/2019/01/cropped-github-favicon-512.png?fit=32%2C32 -O file.png && git diff --exit-code
--2022-04-04 23:52:00--  https://github.blog/wp-content/uploads/2019/01/cropped-github-favicon-512.png?fit=32%2C32
Resolving github.blog (github.blog)... 192.0.66.2
Connecting to github.blog (github.blog)|192.0.66.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1068 (1.0K) [image/png]
Saving to: ‘file.png’

file.png            100%[===================>]   1.04K  --.-KB/s    in 0s      

2022-04-04 23:52:00 (16.6 MB/s) - ‘file.png’ saved [1068/1068]

Done in 0.20s.
```

git status:
```
gitpod /workspace/try-gitpod-git-lfs (master) $ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by dword-design** [comment]
Weird, wenn I run the project, I still get the following output:

```bash
gitpod /workspace/try-gitpod-git-lfs (master) $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> yarn start
> }
yarn run v1.22.17
$ wget https://github.blog/wp-content/uploads/2019/01/cropped-github-favicon-512.png?fit=32%2C32 -O file.png && git diff --exit-code
--2022-04-06 00:11:36--  https://github.blog/wp-content/uploads/2019/01/cropped-github-favicon-512.png?fit=32%2C32
Resolving github.blog (github.blog)... 192.0.66.2
Connecting to github.blog (github.blog)|192.0.66.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1280 (1.2K) [image/png]
Saving to: ‘file.png’

file.png            100%[===================>]   1.25K  --.-KB/s    in 0s      

2022-04-06 00:11:36 (23.1 MB/s) - ‘file.png’ saved [1280/1280]

diff --git a/file.png b/file.png
index 11527f9..0786b1d 100644
Binary files a/file.png and b/file.png differ
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any differences in our setup?

**Comment by sagor999** [comment]
```
 HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
yarn start
}
gitpod /workspace/try-gitpod-git-lfs (master) $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> yarn start
> }
yarn run v1.22.17
$ wget https://github.blog/wp-content/uploads/2019/01/cropped-github-favicon-512.png?fit=32%2C32 -O file.png && git diff --exit-code
--2022-04-06 00:18:05--  https://github.blog/wp-content/uploads/2019/01/cropped-github-favicon-512.png?fit=32%2C32
Resolving github.blog (github.blog)... 192.0.66.2
Connecting to github.blog (github.blog)|192.0.66.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1068 (1.0K) [image/png]
Saving to: ‘file.png’

file.png            100%[===================>]   1.04K  --.-KB/s    in 0s      

2022-04-06 00:18:05 (21.2 MB/s) - ‘file.png’ saved [1068/1068]

Done in 0.16s.
```
Hm. Github.blog resolves to the same IP.
I am connecting to US gitpod cluster though. What about you? (If you look at your workspace URL, it is a subdomain name right before `gitpod.io`)

**Comment by dword-design** [comment]
I'm connecting to a European GitPod cluster, in my case `ws-eu38`.

**Comment by sagor999** [comment]
I connected through EU cluster and got the same error.
But we don't have anything on our end that would manipulate an image or do any sort of proxy that would modify content.
I am thinking that an image on github.blog might have a different meta information when downloaded from CDN that is hit from EU.

Consider trying to do the same test but by downloading an image from a different source, that is guaranteed to be the same.

**Comment by dword-design** [comment]
Ok might be the case that it is some strange behavior on GitHub side. I wasn't sure if GitPod is doing any image processing, but if you say it isn't, I'd say we can close this issue and I'll rewrite my tests to not use the GitHub icon. Others can feel free to reopen in case a similar error occurs.
