### ISSUE TITLE
No Workspace is starting. 

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/gitpod#843]
**Describe the bug**

I'm trying to open both new and existing workspaces but I'm not able to do so.

This is what I get when I try to start a new workspace from any repository:
 
![image](https://user-images.githubusercontent.com/46004116/66536488-8b56e580-eb36-11e9-9783-fb2fb8db0ea6.png)

This is what I get when I try to open an existing workspace:

![image](https://user-images.githubusercontent.com/46004116/66536514-a75a8700-eb36-11e9-8774-8c5eb14ca2ad.png)

**To Reproduce**

**Expected behavior**

**Comment by nisarhassan12** [comment]
Thanks! This is fixed now.

**Comment by jankeromnes** [comment]
Yes, sorry about that, one of our servers had disk problems and we had to remove it from our cluster. Service should be back to normal now.

Thank you for reporting this problem, and for the useful screenshots!
