### ISSUE TITLE
Some workspaces show up with a null context URL in the JetBrains Gateway

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#8434]
### Bug description

Some workspaces show up with a null context URL on the workspaces list inside the JetBrains Gateway.

Could not figure out how to reproduce the issue. However, it seems that switching between tabs (SSH, Gitpod, JetBrains Space) always replaces the null context URLs with valid context URLs.

| Example list (A) | Example list (B) |
|-|-|
| <img width="500" alt="155538160-d84d1ef2-02dd-42dd-a8b7-13d953924770" src="https://user-images.githubusercontent.com/120486/155540111-8af6b39c-778e-442e-b024-d3d2e01094eb.png"> | <img width="500" alt="155538180-16b8927b-d946-4d6d-9684-11443f2573a5" src="https://user-images.githubusercontent.com/120486/155540123-c46adc91-9966-4de7-97af-5a46fcb89345.png"> |

| Before tab switch | After tab switch |
|-|-|
| <img width="595" alt="155538806-a7633741-53e2-4af0-ace0-b96f981a8d7d" src="https://user-images.githubusercontent.com/120486/155539824-78a70761-1fb9-4fdf-ac47-78f93a2bdae5.png"> | <img width="595" alt="155538818-1ebf21c8-38f8-47dd-a7d6-9b0ac0d593f6" src="https://user-images.githubusercontent.com/120486/155539841-49e2f11d-b2da-412a-aff2-606e488c3ca6.png"> |

### Steps to reproduce

N/A

**Comment by felladrin** [comment]
Thanks for the heads-up, @gtsiolis!

In a recent PR (https://github.com/gitpod-io/gitpod/pull/10596) we've addressed the possibility of context URL coming null, so this shouldn't happen anymore.

Let's close this issue.
