### ISSUE TITLE
Can not connect to workspace when opening using a JetBrains IDE from the workspace start page

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#8437]
### Bug description

When users are using a JetBrains IDEs, opening a workspace using a JetBrains IDE from the workspace start never connects.

<img width="1440" alt="Screenshot 2022-02-24 at 4 35 29 PM" src="https://user-images.githubusercontent.com/120486/155544797-013c8e6f-76ed-4c7d-96a3-feb01b3069c0.png">

### Steps to reproduce

1. Use a JetBrains IDE in the Desktop Editor section in [`/preferences`](https://gitpod.io/preferences)
2. Open a new workpace and wait for the workspace start page to prompt you to open using JetBrains Gateway.
3. Click to open using JetBrains Gateway.
4. New window never connects.

### Workspace affected

gitpodio-springpetclinic-7t7oo52cbv5

**Comment by akosyakov** [comment]
> When users are using a JetBrains IDEs, opening a workspace a JetBrains IDE from the workspace start page triggers a new window every time.

That's expected. It is logic of Gateway. 

What is not expected that window can never connect.

**Comment by gtsiolis** [comment]
> That's expected. It is logic of Gateway.

Ok, makes sense. I've updated the issue title and description.

**Comment by akosyakov** [comment]
A log of such backend
[idea.log](https://github.com/gitpod-io/gitpod/files/8140961/idea.log)
:

**Comment by gtsiolis** [comment]
Thanks @akosyakov for the heads-up and @felladrin for fixing this! 💯
