### ISSUE TITLE
"Prebuild in Progress" is often misleading or misbehaves.

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#8446]
When a prebuild is in progress, users who open a workspace on that branch see a screen showing "Prebuild in Progress" (example below),

1. Connecting to workspace logs... often fails so there is no way to see progress

1. While preparing the prebuild (e.g. pulling a large base image) there are no workspace logs to connect to. It would be better to show the actual status (with progress if possible).

1. When the prebuild is done (and showing as READY in the project), even if the "Prebuild in Progress" showed real logs, the screen often does not open a workspace, or show that the prebuild is ready, and there is no button to start a workspace using the new prebuild.

1. Using browser refresh to start the workspace (after seeing the prebuild as READY in another browser tab) often still runs a new prebuild inside the workspace. It feels like the READY prebuild is often not used. 

1. If the prebuild fails for some reason e.g. a network timeout during npm install, this can result in all users seeing the "Prebuild in Progress" page until the prebuild timeout is reached (1 hour), or a new commit is triggered. I have not been able to reproduce this myself, but it was reported in #8324.

![Screenshot 2022-02-24 at 17 28 07](https://user-images.githubusercontent.com/849592/155576318-36453f3d-1999-4b75-b76a-dbd82ddd94ef.png)

---

![Screenshot 2022-02-24 at 17 35 16](https://user-images.githubusercontent.com/849592/155582948-9db5457e-41f8-4714-8bb0-43141079711c.png)

**Comment by jldec** [comment]
cc: @jmls - related to https://github.com/gitpod-io/gitpod/issues/8324

**Comment by geropl** [comment]
I labelled this with `good-first-issue` not because it's easy to fix or of limited scope (more the opposite) but because it's relevant, yet a nice entry point to drill down into how our system works. Especially the webapp/IDE/workspace interaction.

**Comment by jldec** [comment]
See also investigation by @kylos101 in https://github.com/gitpod-io/gitpod/issues/8324#issuecomment-1054777290

**Comment by geropl** [comment]
Closing because of braod scope:
 - UI parts are covered here: https://github.com/gitpod-io/gitpod/issues/9132
 - log parts are covered here: https://github.com/gitpod-io/gitpod/issues/8324
