### ISSUE TITLE
Alert when workspaces starting is zero but there are requests to start

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8448]
## Is your feature request related to a problem? Please describe
There could be requests to start workspaces, but no workspaces may be starting.

## Describe the behaviour you'd like

If webapp requests to start a workspace, and workspaces haven't been started after some criteria is met, we must send an alert to page on-call staff.

## Describe alternatives you've considered

If there are [requests to startWorkspaces in this region's meta cluster](https://grafana.gitpod.io/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22VictoriaMetrics%22,%7B%22refId%22:%22A%22,%22exemplar%22:false,%22instant%22:true,%22range%22:true,%22expr%22:%22histogram_quantile(0.55,%20sum%20(rate(gitpod_server_api_calls_duration_seconds_bucket%7Bmethod%3D~%5C%22startWorkspace%5C%22%7D%5B5m%5D))%20by%20(cluster,%20method,%20le))%22%7D%5D), and there are [no recent startup seconds](https://grafana.gitpod.io/explore?left=%5B%22now-1h%22,%22now%22,%22VictoriaMetrics%22,%7B%22expr%22:%22sum(rate(gitpod_ws_manager_workspace_startup_seconds_bucket%7Bcluster%3D~%5C%22us34%5C%22,type%3D%5C%22REGULAR%5C%22%7D%5B$__rate_interval%5D))%20by%20(le)%22,%22format%22:%22heatmap%22,%22intervalFactor%22:2,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22interval%22:%22%22,%22exemplar%22:false%7D%5D&orgId=1), send an alert.

## Additional context

https://gitpod.slack.com/archives/C0345L4CGHM

**Comment by princerachit** [comment]
>If webapp requests to start a workspace, and workspaces haven't been started after some criteria is met, we must send an alert to page on-call staff.

What do you mean by `workspaces haven't been started after some criteria is met`? We cannot map 1:1 each request from webapp to a workspace being started in workspace cluster.



### I find the alternative you mentioned better with slight modification

>If there are startWorkspaces requests, and there are no recent workspace startups, send an alert.

WDYT?

###  We can use the following alert query with above approach
```promql
sum(rate(gitpod_server_api_calls_duration_seconds_bucket{method=~"startWorkspace"}[5m])) > 0
and
sum(rate(gitpod_ws_manager_workspace_startup_seconds_bucket{type="REGULAR",le="+Inf"}[5m])) == 0
```

This will check if there were any startWorkspace requests from any of the webapp servers and if there were then fire an alert if no regular workspace was started in 5m window

**Comment by kylos101** [comment]
@princerachit may I ask you to mention me next time? :pray: I almost missed this comment. I ask because I participate in a lot of issues (because I create them) so it gets noisy. :slightly_smiling_face: 

The signals mentioned in the [linked Slack thread](https://gitpod.slack.com/archives/C0345L4CGHM/p1645746001300779) were:
* regular not active was increasing (think of the yellow line going up on our overview dashboard)
* workspaces were not starting (think of the green and white bricks not appearing on our workspace start time on the overview dashboard)

Given that context Slack thread, the request from `server` to `startWorkspace` made it to the workspace cluster, but they were unable to start, and died on the workspace cluster due to issues with Calico. That is the primary reason for this issue, so for this particular case, I think including server may be unnecessary, and potentially complicate things.
