### ISSUE TITLE
Nimlang support

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#845]
Nim is a cool new programming language I took the liberty of starting the repo https://github.com/JesterOrNot/Gitpod-nim

**Comment by jankeromnes** [comment]
> but rather have automated setup/guides on configure Gitpod for a language

See also https://www.gitpod.io/docs/languages_and_frameworks/ 😊 (unfortunately, it only has Java for now. I have a PR up for Julia: https://github.com/gitpod-io/website/pull/261)

**Comment by GarnicaJR** [comment]
Thanks Sir, i appreciate  your efforts to create  those amazing repos :),  i will this one  and back with the feedback.

Best regards .....

**Comment by JesterOrNot** [comment]
any thoughts on this?

**Comment by aggsol** [comment]
So, what is the best way to use Nim on gitpod?

**Comment by Kreyren** [comment]
@aggsol Jester's solution should work:

```
FROM gitpod/workspace-full

USER gitpod
RUN sudo apt-get update && sudo apt-get install nim
```

**Comment by jankeromnes** [comment]
Nimlang is now officially supported in Gitpod! 🎉

Install it with either of:
- `sudo apt-get install nim`
- `brew install nim`

(e.g. in your [.gitpod.Dockerfile](https://www.gitpod.io/docs/config-docker/))

Also install the Nim extension:
- https://open-vsx.org/extension/nimsaem/nimvscode

(e.g. by searching "nim" in the IDE's Extensions panel and clicking "install")
