### ISSUE TITLE
Can't restart a stopped workspace in some case

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#8450]
### Bug description

Can't restart a stopped workspace in some case

After refresh, click  **Open Workspace** works
|Failed|After Refresh|
|:-:|:-:|
|<img width="1511" alt="image" src="https://user-images.githubusercontent.com/20944364/155685436-4e5519e7-ae18-40ac-8572-8ad8031bca67.png">|<img width="1511" alt="image" src="https://user-images.githubusercontent.com/20944364/155685555-9d6c65cc-92c8-4137-9fc1-deb8fd87707b.png">|

### Steps to reproduce

Click  **Open Workspace** with a **Timed Out** workspace

(can't repro every time)

**Comment by sagor999** [comment]
Was fixed in: https://github.com/gitpod-io/gitpod/pull/8519
