### ISSUE TITLE
Request push failed with message: Authentication failed

### ISSUE THREAD

**Issue by artalar** [gitpod-io/gitpod#846]
**Describe the bug**
Can't push to the GitHub from workspace

**To Reproduce**
https://f9b0ecb9-7195-4b52-8ba9-2d59f5b0255b.ws-eu0.gitpod.io/#/workspace/runtypes

**Expected behavior**
Can't push to the GitHub from workspace

---

I try to remove and get again permissions, but it doesn't change anything...

![example](https://user-images.githubusercontent.com/27290320/66707824-c2541380-ed4f-11e9-9cf8-9c175f5b1d1d.png)
![example](https://user-images.githubusercontent.com/27290320/66707828-caac4e80-ed4f-11e9-8b95-d9c4f621be27.png)
![example](https://user-images.githubusercontent.com/27290320/66707830-d566e380-ed4f-11e9-80ae-588ba9d3442b.png)
![example](https://user-images.githubusercontent.com/27290320/66707833-e9aae080-ed4f-11e9-81e9-9775aa71415a.png)

P.S. it is a really sad bug, it blocking my job =(
(apparently, I must to clone the repo locally, download changes from the gitpod and retry the commit)

**Comment by JesterOrNot** [comment]
I've been able to reproduce this issue https://www.loom.com/share/05586fef0eef41699a2b86d9b055cf73
I'm running chrome os what are you running?

**Comment by artalar** [comment]
firefox developer edition 70.0b14 (64)
MacOS 10.14.6 (18G95)

**Comment by AlexTugarev** [comment]
Hi @artalar! Could it be that you're trying to push to the remote using SSH? At least that's what the first screenshot is suggesting. 

Gitpod is currently not supporting SSH-URLs (https://github.com/gitpod-io/gitpod/issues/336) please replace with HTTPS URLs in that case.

**Comment by artalar** [comment]
Yes! I was use ssh-url. Thanks.
Try to push to http-url some time later.
