### ISSUE TITLE
Decouple gitpod extension release from gp-code release

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#8465]
## Is your feature request related to a problem? Please describe

Right now gitpod extension lives in the gp-code branch as a built in extension, this is troublesome when we want to do a new release of the gitpod extension as it implies we also need to do a full release of gp-code

## Describe the behaviour you'd like

We should be able to release a new version of gitpod extension independently of gp-code release

## Describe alternatives you've considered

An option would be to publish it to openvsx and install in as a built-in extension when we launch the server

**Comment by akosyakov** [comment]
We should think well about it, there are good properties right now that we can cherry pick some changes to old release and so on. Will we publish 2 different version to Marketplace? One for stable, another for nightly?

**Comment by jeanp413** [comment]
I think most changes in gitpod extension are independent of the gp-code release (the only exception being our custom cli changes) so just one version would be enough, also we can use the engine property in package.json to specify a minimun vscode version

**Comment by akosyakov** [comment]
@csweichel @corneliusludmann If we do it it will mean that connection to OpenVSX is required to get properly working workspace. I wonder about the same approach with JB backends, i.e. decouple release of JB backends and plugins. It has benefits but probably will complicate self-hosted setup. WDYT?

**Comment by corneliusludmann** [comment]
The requirement of having a connection to an OpenVSX instance would make an air-gap installation much more complicated. If we could somehow prevent that, I would be strongly in favor of it. Couldn't we bring the Gitpod extension into the workspace image as an image layer or serve the Gitpod extension from a Gitpod component to fetch it from within a workspace?

**Comment by jeanp413** [comment]
> Couldn't we bring the Gitpod extension into the workspace image as an image layer

This sounds good too, we could package extension into a vsix file in an image and then mount that layer into `/ide` folder and then install it passing the vsix file path to the server cli

**Comment by jeanp413** [comment]
> The requirement of having a connection to an OpenVSX instance would make an air-gap installation much more complicated.

This is not an issue as we just pin the latest gitpo-web version in [product.json](https://github.com/gitpod-io/openvscode-server/blob/8225b8cac374140ae82cbc8353a61c8d2650f6af/product.json#L683) it will be downloaded when building the release version. Just need to remember to update it if needed before self-hosted release. We already do this for gitpod-theme extension

**Comment by jeanp413** [comment]
To move gitpod-web to it's own repo it would be good to mockup some of the supervisor API so we can test some features like ports while developing, then we can just package the extension and test it in production manually as we do for gitpod-remote currently

**Comment by jeanp413** [comment]
We have some custom changes in gitpod-code specifically custom menu contribution points (e.g. used to add menu options in help menu) that could make this a little troublesome, we need to test if the extension can activate even if this contributions points are not preset otherwise commenting/uncommenting these while developing will be annoying

**Comment by akosyakov** [comment]
I removed it from inbox, since we are focusing on getting VS Code Desktop GA out.

**Comment by jeanp413** [comment]
This is done now, extensions are moved to https://github.com/gitpod-io/gitpod-code
