### ISSUE TITLE
Workspace stuck in 'stopping' procese

### ISSUE THREAD

**Issue by FacundoGdS** [gitpod-io/gitpod#8468]
### Bug description

Hello, as I see, this problem is already old but it is happening to me with this workspace:
https://4geeksacademy-masterjava-ysg3y6nfc2n.ws-us34xl.gitpod.io/

What is happening to me is that I go to the dashboard and I click on my workspace, then it won't open, instead of it, it stucks in a non-stop 'stopping' process...

What can I do for stopping this 'stopping' procese? Because It's taking forever and I can't work on it.
Thanks in advance!

### Steps to reproduce

1. Go to the dashboard.
2. Click on my workspace.
3. It doesn't open or stop. It's frozen in an eternal 'stopping' step.
4. Then nothing, I can't do anything else after the last step.

### Workspace affected

https://4geeksacademy-masterjava-ysg3y6nfc2n.ws-us34xl.gitpod.io/

### Expected behavior

To open this workspace and start working on it, opening the terminal and then do git commands...

**Comment by sagor999** [comment]
We had an issue with some workspaces not stopping correctly but it was resolved. Sorry about that!
I will close this issue for now.
