### ISSUE TITLE
Custom docker image creation fails

### ISSUE THREAD

**Issue by bangyogesh** [gitpod-io/gitpod#847]
I have been trying to create a custom docker image for development environment as a part of exploring GitPod. Earlier I created custom docker image for data-science related dev environment.

This time I was trying to create it for node,angular,typescript etc using custom docker file. However during the docker image creation the docker build fails showing the error related to package 'apt-utils' (please check the screenshot of the error as attachment). 
On the other note, when I run this dockerfile on my local Ubuntu instance, its able to create the custom docker image.
Alternately it can be tried using the URL : https://gitpod.io/#https://github.com/bangyogesh/AngularDevContainer

**************************************************
Dockerfile
**************************************************
FROM node:8 
USER root
#Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive
RUN dpkg -r --force-all doc-base

#avoid permission issues with bind mounts. Update USER_UID / USER_GID 
ARG USER_UID=1000
ARG USER_GID=$USER_UID

#Configure apt and install packages
RUN apt-get update 
RUN apt-get -y install --no-install-recommends apt-utils 
RUN apt-get -y install --no-install-recommends dialog  
RUN apt-get install -y apt-transport-https
#
    #Verify git and needed tools are installed
RUN apt-get -y install git iproute2 procps     
    #
    #Remove outdated yarn from /opt and install via package 
    #so it can be easily updated via apt-get upgrade yarn
RUN rm -rf /opt/yarn-* \
    && rm -f /usr/local/bin/yarn \
    && rm -f /usr/local/bin/yarnpkg \
    && apt-get install -y curl apt-transport-https lsb-release \
    && curl -sS https://dl.yarnpkg.com/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/pubkey.gpg | apt-key add - 2>/dev/null \
    && echo "deb https://dl.yarnpkg.com/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/ stable main" | tee /etc/apt/sources.list.d/yarn.list 
   
RUN apt-get update 
RUN apt-get -y install --no-install-recommends yarn 
    #
    #Install tslint and typescript globally
RUN npm install -g tslint typescript 
    #&& if [ "$USER_GID" != "1000" ]; then groupmod node --gid $USER_GID; fi \
    #&& if [ "$USER_UID" != "1000" ]; then usermod --uid $USER_UID node; fi \
    # [Optional] Add add sudo support for non-root user
    #&& apt-get install -y sudo \
    #&& echo node ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/node \
    #&& chmod 0440 /etc/sudoers.d/node \
    #
    #Clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

#Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=
USER root
********************************************

![image](https://user-images.githubusercontent.com/2494368/66712634-3d9fde80-edbd-11e9-941f-4f889a6b8d23.png)

**Comment by JesterOrNot** [comment]
here is a pull request with the fix https://github.com/bangyogesh/AngularDevContainer/pull/1
what you did wrong was that you separated the apt-get update and apt-get install docker needs them to be chained

**Comment by bangyogesh** [comment]
Thanks a lot @JesterOrNot . I have merged your PR into my repository now. It works perfectly !!!

However I still wonder how come the above Dockerfile was able to build the docker image on my Ubuntu VM when the docker needed then apt-get update and apt-get install chained ?

Thank you once again for your timely help and support.

**Comment by bangyogesh** [comment]
@JesterOrNot  I tested with https://gitpod.io/#https://github.com/JesterOrNot/AngularDevContainer and it works perfectly.

However after your PR merge I tried with
https://gitpod.io/#https://github.com/bangyogesh/AngularDevContainer and it failed with the same errors.

Not sure if I am doing it correctly.

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/66722939-2c64cb00-edd9-11e9-93e9-318b8eeceb07.png)
it seems to work

**Comment by bangyogesh** [comment]
@JesterOrNot , Not sure why it was failing earlier. I tried it using 'Incognito' mode of Chrome and it worked well.  May be some Cache, WebSocket connection issues ? Not sure.

But the good part is I can now continue with the custom image for Angular Dev environment.
Thanks a lot for the timely help and guidance.

With Warm Regards,
Yogesh
![image](https://user-images.githubusercontent.com/2494368/66733572-9e8eeb80-ee7d-11e9-9a54-73e379849c88.png)
