### ISSUE TITLE
Provide an icon to copy a port URL

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/gitpod#8474]
## Is your feature request related to a problem? Please describe

To copy a port URL, I have to either open it in a new browser tab, copy the URL and close the browser tab or use `gp url <port>`, then select the output and copy it.

## Describe the behaviour you'd like

It would be nice if the VS Code Remote Explorer allowed individual port URLs to be copied to the clipboard. I imagine an icon next to the existing ones which allowed me to copy the port URL.

![image](https://user-images.githubusercontent.com/788827/155909635-817499ef-caa1-4b88-bf47-c12995d63dfd.png)

## Describe alternatives you've considered

See answer to the first question above.

**Comment by loujaybee** [comment]
Aside, I do miss having `pbcopy` available in workspace-full, my usual workflow is usually `gp url | pbcopy`

**Comment by andreafalzetti** [comment]
<img width="804" alt="Screenshot 2022-10-11 at 11 45 53" src="https://user-images.githubusercontent.com/2318450/195070354-be1a8f69-60e7-401d-8906-3f7078947885.png">

This is now available, am I missing anything or shall we close the issue? 

cc @loujaybee @mikenikles

**Comment by mikenikles** [comment]
The new ports UI is great and resolves this. It doesn't work in Firefox though, that's tracked in #13377.
