### ISSUE TITLE
headless task failed

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#8475]
### Bug description

https://gitpod.io/#https://github.com/csweichel/gitpod-hello-ui-demo

### Steps to reproduce

Open the link

```console
error: failed to solve: process "/bin/sh -c apt-get update     && apt-get install -y libgtk-3-dev     && apt-get clean && rm -rf /var/cache/apt/* && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*" did not complete successfully: exit code: 100
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","command":"build","error":"exit status 1","level":"error","message":"build failed","serviceContext":{"service":"bob","version":""},"severity":"ERROR","time":"2022-02-28T01:53:26Z"}
exit

Error: headless task failed: exit status 1
```

**Comment by atduarte** [comment]
Hi @gengjiawen! There are a few issues in that project. The `.gitpod` file should be named `.gitpod.yml` and the commands in the Dockerfile should be executed as the `root` or with `sudo`, but they run with the user `gitpod`. 

@csweichel created a PR for your project.

In the meantime, here's a working forked version of the project: https://github.com/atduarte/gitpod-hello-ui-demo
