### ISSUE TITLE
(Automated) Deleting of S3 Objects

### ISSUE THREAD

**Issue by fritterhoff** [gitpod-io/gitpod#8481]
### Bug description

We're evaluating the use of a selfhosted gitpod instance. (Base OS Ubuntu 20.04, using the latest installer version on k3s, all components are in-cluster)
Obviously, at the moment S3 objects are kept forever, even if I delete the workspace.

It seems like the source code provides some functionality to delete the objects but I'm unsure how to trigger them or how they should be triggered by an existing functionality. 

https://github.com/gitpod-io/gitpod/blob/3299c159b83ce5fff119f4c29b0f52064044ea04/components/content-service/pkg/service/workspace-service.go#L93

### Steps to reproduce

- Open Minio Interface (e.g. using portforwarding, creating an extra ingress,...)
- Open a workspace for a repo -> Object should exist now
- Stop and delete workspace -> Object will still exist
- Start new workspace for the same repo -> New object is created ;)

### Expected behavior

Objects get deleted on deletion of workspace (or automated after time X)

**Comment by sagor999** [comment]
We will be working on changing how we store workspace data and this might be obsolete in the near future.
So most probably we will not be looking to fix this currently, as this seems to be a low impact bug.

**Comment by fritterhoff** [comment]
@sagor999: Out of curiosity why is data kept multiple times? Once on the host stored in `/var/gitpod/workspaces` and once in the S3 Bucket? Sure, disk storage is not a real problem, but from my point of view that is sort of redundant.
