### ISSUE TITLE
Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.

### ISSUE THREAD

**Issue by semiribrahim** [gitpod-io/gitpod#8487]
### Bug description

On starting a new workspace, an error alert keeps getting displayed VS code with the error below:

**Activating the Pull Requests and Issues extension failed. Please make sure you have git installed.**

**GitHub Pull Requests and Issues** plugin seem to be shipped by default in VS code, would be useful if it could be optional. 

![Screen Shot 2022-02-28 at 1 58 27 PM](https://user-images.githubusercontent.com/89976046/155995703-b431f736-79c9-469a-9487-70052ce56b86.png)
 

### Steps to reproduce

Go to:

https://developer.couchbase.com/tutorial-quickstart-java-springboot 

And after some time, the error alert get displayded.

**Comment by loujaybee** [comment]
Thanks @mustard-mh, please try the above @semiribrahim, feel free to re-open if you still have troubles 🙏
