### ISSUE TITLE
Can't click on any button using apple pencil on the iPad Pro

### ISSUE THREAD

**Issue by studentIvan** [gitpod-io/gitpod#849]
**Describe the bug**
Can't click on any button using apple pencil on the iPad Pro

**To Reproduce**
Click by apple pencil on any button

**Expected behavior**
Click action on short screen touch by the apple pencil

**Comment by jankeromnes** [comment]
Hi @studentIvan, thanks for reporting this issue! I also noticed this problem on my (regular) iPad a while back, and I agree that it should be fixed.

**Comment by jankeromnes** [comment]
I've moved this issue to the Theia IDE repository (Theia is the IDE used by Gitpod):

https://github.com/eclipse-theia/theia/issues/6389
