### ISSUE TITLE
SEO: Google search console: Server error (5xx) 

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/gitpod#8508]
According to Google Search Console, there are 64 pages that return a 5xx error. [[1](https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Agitpod.io&item_key=CAMYEyAE)]

Most affected URLs are: https://gitpod.io/api/xyz
<img width="884" alt="Bildschirmfoto 2022-03-01 um 11 30 21" src="https://user-images.githubusercontent.com/46345125/156189644-6110133b-56a2-4af4-a6c5-db8b9db3f262.png">

**Comment by filiptronicek** [comment]
@ChristinFrohne should these endpoints even be indexed? I am guessing they are not needed for SEO and shouldn't be in anyone's search results 😄, maybe we should add the `/api/` route to https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/public/robots.txt?

I'm not sure who to cc / mention here though, maybe @jankeromnes?
