### ISSUE TITLE
ARM64 support not working

### ISSUE THREAD

**Issue by cafsenra** [gitpod-io/gitpod#8509]
### Bug description

On installing Gitpod on ARM64 k3s cluster with [gitpod installer](https://github.com/gitpod-io/gitpod/releases/tag/2022.02.0), I am getting the following error:
standard_init_linux.go:228: exec user process caused: exec format error

This error appears when the containers doesn't support ARM64. As I am using Gitpod arm64 installer, I would expect that this issue doesn't occurs!

### Steps to reproduce

1 - Install Gitpod with arm64 [gitpod installer](https://github.com/gitpod-io/gitpod/releases/tag/2022.02.0) tool.

1A - Disable LoadBalancer:
```shell
yq eval-all --inplace \
  '(select(.kind == "Service" and .metadata.name == "proxy") | .spec.type) |= "ClusterIP"' \
  gitpod.yaml
```

1B - Apply generated gitpod.yaml file

### Expected behavior

Gitpod installer tool should install ARM64 docker images on ARM64 Nodes. The docker images should be multiarch at minimum ARM64 and AMD64.

### Anything else?

[docker build multi platform images](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images)

Docker documentation for multi platform images aren't well documented, but there are several guides in internet, as an example, I will share my gitlab pipeline for multi platform docker buildx:

```shell
build-docker-buildx:
  image: registry.domain.com/homelab/docker-buildx:latest # docker:20.10.12 with buildx
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    FF_NETWORK_PER_BUILD: 1
  stage: build
  services:
    - name: registry.domain.com/homelab/docker-dind:latest # docker:20.10.12-dind with buildx
      alias: docker
      command: ["--experimental"]
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker buildx ls
    - docker context create tls-environment
    - docker context ls
    - docker buildx create --name mybuilder --use tls-environment
    # - docker buildx inspect --bootstrap
    - docker buildx build --cache-from="${CI_REGISTRY_IMAGE}:latest" --cache-to=type=inline --platform linux/amd64,linux/arm64 --push -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}" -t "${CI_REGISTRY_IMAGE}:latest" .
  tags:
    - docker-runner      
  rules:
    - if: $CI_COMMIT_TAG
  when: manual
```

**Comment by axonasif** [comment]
I wonder if this is related: https://github.com/gitpod-io/gitpod/pull/7937#issuecomment-1042718737 ?

**Comment by lucasvaltl** [comment]
We [do not have plans](https://github.com/gitpod-io/gitpod/pull/7937#issuecomment-1042718737)  to support arm64 in near future at least. Closing this for now.
