### ISSUE TITLE
Enable faster and cleaner rollouts for server pods

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#8525]
We deploy `n` `server` pods in our clusters to enable basic scalability. The rollout strategy is `n-1+1` (stop old & start new, one-by-one).

What makes this slow atm, and also might lead to more user-facing errors than necessary, is that we do not properly handle the kubernetes lifecycle, especially the [termination parts](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination). This is one of things we need to fix on our way to (more) automated rollouts.

We should handle pod termination signaled by either preStop hook or SIGTERM and:
 - stop accepting new requests (websocket, HTTP): this _should_ already be done by kubernetes (cmp. [pod-termination](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)); we should verify
 - stop accepting new RPCs: easiest is to introduce a notification that signals clients to re-connect so they end up on a new client
 - exit the server process once all websocket connections have been terminated

**Comment by AllMight2099** [comment]
Hey there!
I'm Nishanth and I want to contribute to GitPod.I was hoping I could take this issue up.
