### ISSUE TITLE
Disable Workspace Timeout When Running in a Self-Hosted Manner

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#8528]
## Is your feature request related to a problem? Please describe
I'm having the issue of workspaces timing out and thus shutting down even though I still want to use it.

## Describe the behaviour you'd like
Interactive way to change the timeout of a workspace to allow it to run continuously even after a script has finished and/or there is no user input/activity.

## Describe alternatives you've considered
Put a sleep at the end of the script, which is more of a hack

## Additional context
Connecting to the workspace via SSH & using self-hosted Gitpod

**Comment by corneliusludmann** [comment]
A pretty simple fix would be to add a config value to the installer that allows setting the timeout timespan. With that, customers can set an outrageous amount of time as timeout (let's say 1 year or so).

Since the extending of timeouts is an enterprise feature, the values are set here:

https://github.com/gitpod-io/gitpod/blob/5b74af751837f95839e0a645b42bbdd10748fc40/components/server/ee/src/user/user-service.ts#L25-L37

The `60m` in line 36 is the default that is used for enterprise customers with a proper license.

In the installer config, I would propose to make clear that it's an enterprise feature that does not have any effect without a proper license (unless we decide that this should not be an enterprise feature anymore for some reason), e.g. by adding a section `enterpriseFeatures`:
```yaml
# changing values of enterprise features are only available with a proper license
enterpriseFeatures:
  defaultWorkspaceTimeout: 8760h   # 1 year
```

**Comment by kylos101** [comment]
> I'm having the issue of workspaces timing out and thus shutting down even though I still want to use it.

@lucasvaltl which timeout are you referring? 
1. The inactivity timeout (which is 1 hour, and depending on your plan, can be extended in VS Code by clicking a toggle in the bottom right, to 3 hours)?
2. The workspace total runtime timeout (36h)? After this timespan, we stop workloads, even if actively being used. [Introduced here as part of the installer config.](https://github.com/gitpod-io/gitpod/pull/8307/files#diff-a267927631f3f68122ca1393d43245ad1bc9ae6ddfbf86d1c50f647e2fda13a3R125-R126)
3. Something else?

CC: @corneliusludmann

**Comment by corneliusludmann** [comment]
Thanks for your comment, @kylos101. Didn't know that something like the workspace total runtime timeout exists. As far as I know, it's about the inactivity timeout. However, when they want to run workspaces longer than 36 hours, we need to make the total runtime timeout configurable as well.

@lucasvaltl: Could you take care that someone clarifies with the customer the actual use case and how long the workspaces actually need to run?

**Comment by corneliusludmann** [comment]
@charlevelz: Thanks for your feedback. Could you add more details about your use case? Gitpod is designed to run [ephemeral workspaces](https://www.gitpod.io/docs/workspaces) for software developing tasks. When you say that you're testing services, how exactly do you use Gitpod?

**Comment by charlevelz** [comment]
Hi @corneliusludmann thanks for your answer, i know perfectly the use ephemeral workspaces for software development tasks - however, i think that gitpod have multiple case uses. I like testing my "mini data-platform"  and - as a data engineer - I find gitpod a very useful platform for my use case -  but the timeout, it really hinders my goal.

![img](https://user-images.githubusercontent.com/88805866/156610642-8aef8e1f-1562-4e65-99e9-1589fe610751.png)

**Comment by MrSimonEmms** [comment]
According to https://www.gitpod.io/self-hosted, we're currently advertising all self-hosted instances without any timeout

So, options are:
1. change the webpage to say "30m or 60m timeout"
2. remove the timeout entirely (or, if that doesn't work, set to 1 year)

As I'm currently doing #8328, it makes sense to do this now. Personally, I favour option `2`

![image](https://user-images.githubusercontent.com/275848/156990855-0bcf242f-5707-47de-ac19-9c622b87bda6.png)

**Comment by shaoye** [comment]
> According to https://www.gitpod.io/self-hosted, we're currently advertising all self-hosted instances without any timeout
> 
> So, options are:
> 
> 1. change the webpage to say "30m or 60m timeout"
> 2. remove the timeout entirely (or, if that doesn't work, set to 1 year)
> 
> As I'm currently doing #8328, it makes sense to do this now. Personally, I favour option `2`
> 
> ![image](https://user-images.githubusercontent.com/275848/156990855-0bcf242f-5707-47de-ac19-9c622b87bda6.png)


Hi, it would be great if gitpod adopts option 2. 

But currently we are still unable to modify the timeout option (EE licence required https://github.com/gitpod-io/gitpod/blob/main/components/server/ee/src/workspace/gitpod-server-impl.ts#L295)

Do we have an open issue for tracking this? thanks!
