### ISSUE TITLE
[installer/openvsx-proxy/statefulset.go] StatefulSetStatus should not be rendered

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#8529]
When running `installer render`, the OpenVSX-Proxy statefulset is being rendered with the Status field populated.

The status field is something that is fully controlled by the Kubernetes API after a resource is applied, so having it populated doesn't make sense from the Installer point-of-view. Besides that, different Kubernetes versions might have different required fields and a invalid status might prevent us from installing Gitpod on more recent Kubernetes Versions

**Comment by lucasvaltl** [comment]
Triaged this. This is a relevant issue, but we are unlikely to work on this soon.

**Comment by corneliusludmann** [comment]
Fixed by https://github.com/gitpod-io/gitpod/pull/11391
