### ISSUE TITLE
Mouse wheel scrolling in editor is too slow on Firefox / Windows

### ISSUE THREAD

**Issue by spoenemann** [gitpod-io/gitpod#854]
**Describe the bug**
Scrolling up / down with the mouse wheel is too slow in the editor. It's fine in other views such as the file explorer.

**To Reproduce**
Open Gitpod with Firefox on Windows, open an editor.

**Expected behavior**
Scrolling speed should be natural, i.e. roughly the same as for the browser-native scrollbars.

**Comment by geropl** [comment]
:sweat_smile: Created the same issue yesterday on theia repo: https://github.com/eclipse-theia/theia/issues/6390

It's basically solved, we _just_ need to update Theia and Gitpod

**Comment by svenefftinge** [comment]
In production now

**Comment by geropl** [comment]
Sadly not, scrolling is still slow - and the issues upstream are open, too.

**Comment by randomir** [comment]
Any update on when will this fix be deployed to GitPod?

**Comment by akosyakov** [comment]
I don't think it was fixed, Theia needs new Monaco and update only was planned.

**Comment by imdigo** [comment]
Any update? 
Did it fixed on theia-ide?

**Comment by Kartikkman** [comment]
@svenefftinge  Hi thanks for Awesome product , but we are facing scroll issue , Can you fix it ? It makes hard to scroll through Code !!

**Comment by svenefftinge** [comment]
We are deploying the fix to this tomorrow.

**Comment by Kreyren** [comment]
FWIW I also found it annoying, but it seemed to me as intended design so i solved it by using:

```json
"editor.mouseWheelScrollSensitivity": 10,
```

**Comment by svenefftinge** [comment]
This has been fixed and deployed to production.
