### ISSUE TITLE
Epic: Gitpod KOTS (Kubernetes Off-The-Shelf) application (aka Replicated Installer)

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#8540]
### Problem 

Currently there are different ways to consume Gitpod - via our SaaS offering, and via a self hosted installation. We want to ensure that everyone, no matter how they are using Gitpod, is having a great experience. This is also true for larger customers with more stringent requirements. 

### Proposed Solution

Wrap the Gitpod Installer with KOTS to allow for a streamlined experience in terms of installation, licence management and support.

**Comment by MrSimonEmms** [comment]
Closed in favour of #9072
