### ISSUE TITLE
Incorrect git auth error

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#855]
**Describe the bug**
https://www.loom.com/share/cb698093207e4669886fd2a861a494c3
Says that there are auth errors but pushes to repo still
note this was on a chromebook
**To Reproduce**
follow instructions in video
**Expected behavior**
message does not display because it does have auth

**Comment by jankeromnes** [comment]
Whoops, indeed, thanks for reporting this!

@AlexTugarev it's the Git extension saying you don't have write access when in fact you actually do. Do we already track this issue somewhere?

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/67136459-10ec2c80-f1ec-11e9-910f-3b474440b03e.png)
The issue seems to be fixed!

**Comment by JesterOrNot** [comment]
error has returned
![image](https://user-images.githubusercontent.com/50386709/67611682-44d1cf80-f761-11e9-841e-e1cfc5a5a5da.png)

**Comment by JesterOrNot** [comment]
It has fixed it'self again

**Comment by JesterOrNot** [comment]
This issue is back
![image](https://user-images.githubusercontent.com/50386709/76111303-a58dd600-5fa5-11ea-87c8-72a93be56dab.png)

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/76114194-30bd9a80-5fab-11ea-94b5-ab20802524cf.png)

**Comment by jankeromnes** [comment]
Oops, thanks  for reporting this @JesterOrNot.

Does the browser devtools console show you any errors when this happens?

Cc @AlexTugarev

**Comment by AlexTugarev** [comment]
@JesterOrNot and @jankeromnes we forgot to update this GH issue after last deployment. This false negative was fixed.
