### ISSUE TITLE
Manually triggered prebuilds cannot be cancelled

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8551]
### Bug description

Manual triggered prebuilds cannot be cancelled, at least, given the example I've shared (which uses a loop to cause the prebuild to never finish and hit our 1 hour timeout). 

Here is a picture of what I see as a user running a manual prebuild:
![image](https://user-images.githubusercontent.com/1272076/156440440-46369e22-c734-4707-8492-c453a171e21c.png)

This is unlike typical prebuilds, which can be triggered when you push code, and then cancelled from the project view from `https://gitpod.io/projects/<project-name>/prebuilds`.

### Steps to reproduce

[Fork this](https://github.com/kylos101/prebuild-experiment), and then try to manually prebuild it using `https://gitpod.io/#prebuild/<your-fork>`.

### Workspace affected

https://kylos101-prebuildexperim-g7elbnft1ez.ws-us34xl.gitpod.io/

### Expected behavior

The user should be able to click cancel, and when they do, it terminates the prebuild. This will give them another opportunity to try another manual prebuild.

### Example repository

https://github.com/kylos101/prebuild-experiment

### Anything else?

You cannot run a prebuild for the same commit more than once, therefore, if you only start prebuilds manually, and encounter this error, you have to wait for a full hour before you can become productive again.

**Comment by easyCZ** [comment]
Related to https://github.com/gitpod-io/gitpod/issues/9132, using the same components would then allow us to also show action buttons.
