### ISSUE TITLE
Workspace failing to start - gitpod/never-ready

### ISSUE THREAD

**Issue by joepurdy** [gitpod-io/gitpod#8553]
### Bug description

Our engineers are seeing an elevated rate of errors starting new gitpod workspaces. The failures look like this:
![image](https://user-images.githubusercontent.com/6409227/156436725-76aeee02-6d7f-4251-83f7-6c84defe5e28.png)

The specific error about failing to mark the workspace seems like an issue with the k8s layer and outside our control. Is this a known issue?

### Steps to reproduce

1. Start a new workspace
2. Fails to start and gives an error

### Workspace affected

customerio-services-difsbln9l9k

### Anything else?

I've pinned one of the failing workspaces to preserve it (customerio-services-difsbln9l9k) in case that helps investigate!

**Comment by sagor999** [comment]
We already merged a fix for this: https://github.com/gitpod-io/gitpod/pull/8519
And this should be rolled out later this week into production. 
This should be a temporary failure, and retrying should resolve it, though I understand this is not ideal.

**Comment by joepurdy** [comment]
Awesome! Thanks @sagor999 for taking care of this for us! 🎊

**Comment by kylos101** [comment]
Hey @joepurdy :wave: , the fix has been pushed to all workspace clusters in US and EU regions and should be resolved now. 

I'm going to close the issue for now, but, if you happen to experience it again please do reopen?
