### ISSUE TITLE
Feature Request: Ability to rename terminals using shell commands

### ISSUE THREAD

**Issue by mickmister** [gitpod-io/gitpod#8557]
## Is your feature request related to a problem? Please describe

At the moment, terminal names must be name in the `.gitpod.yml` file. I want to share different gitpod setups among different projects, and a lot of the projects have overlap. I would to share functionality between the projects through scripts defined outside of the `.gitpod.yml` files. Each `.gitpod.yml` file basically has no logic is purely used to bootstrap scripts that initialize each terminal.

I would like to create a `.gitpod.yml` file in each project, and have it be one commit in the repository. Any Gitpod-related scripts will be stored in a separate repo, where we can iterate on the Gitpod configurations of these projects without adding commits to each individual projects.

I want to make the `.gitpod.yml` files future-proof, and not require an update unless it's something related to `prebuild` or something. Basically, I want the terminal inititalizers to be entirely external.

This is the system I have come up with:

```yaml
tasks:
  - name: Terminal1
    init: |
      cd /workspace
      git clone https://github.com/mickmister/gitpod-config.git
      gp sync-done config-repo-cloned
      cd /workspace/gitpod-config
      ./project1/terminal1-init.sh
    command: |
      ./project1/terminal1-command.sh

  - name: Terminal2
    init: |
      gp sync-wait config-repo-cloned
      cd /workspace/gitpod-config
      ./project1/terminal2-init.sh
    command: |
      ./project1/terminal2-command.sh
```

and so on for a total of 5 terminals. At the moment, I don't need 5 terminals for the projects, but like I said I want the `.gitpod.yml` file to be future-proof and require only one commit in each project. If any of the terminals are not needed, they can simply be `exit`'d by the script that is called.

## Describe the behaviour you'd like

In the `someproject/terminal1-init.sh` file, I want to be able to rename the terminal in the tabs to the right side of the terminal. Something like:

```sh
gp rename-terminal "Server"
```

**Comment by mickmister** [comment]
I want to say that if this was implemented, I would be all-in for using Gitpod. It's important that the management of each project can be done by common scripts in a repo dedicated to Gitpod configuration.

There is work being done to share configuration between projects https://github.com/gitpod-io/gitpod/issues/7608, but the system I've detailed above seems a little more flexible for my use cases, and should require much less code, if it's possible and deemed valuable to implement this. I'd be happy to look into this if someone thinks this is feasible.

**Comment by mickmister** [comment]
Another request for this piece is to make it so the config repo does not need to keep track of the repos running the config repo's scripts. It seems like the current direction relies on the repos  needing to be linked both ways in the epic https://github.com/gitpod-io/gitpod/issues/7608

**Comment by axonasif** [comment]
Hey @sagor999, I think this falls under IDE or webapp team, WDYT?

**Comment by sagor999** [comment]
@axonasif you are right. I will add it to IDE team inbox. :pray:
