### ISSUE TITLE
File name is not selected in "New File" dialog

### ISSUE THREAD

**Issue by spoenemann** [gitpod-io/gitpod#856]
**Describe the bug**
When I create a new file through the context menu of the Explorer or the _File_ main menu, a dialog pops up proposing the name `Untitled.txt`. The name is not selected, so I have to delete it myself before I can enter a new file name.

Tested on Firefox / Windows.

**Expected behavior**
The default file name should be selected because it's only a placeholder.

**Comment by JesterOrNot** [comment]
Can you send a screenshot of this?

**Comment by spoenemann** [comment]
![grafik](https://user-images.githubusercontent.com/4067210/66921036-b8b6fe00-f024-11e9-99bf-b8f6271eadf5.png)

**Comment by jankeromnes** [comment]
Thanks for reporting this annoying issue! 👍 

I think it should be filed against https://github.com/eclipse-theia/theia/issues instead.
