### ISSUE TITLE
Workspaces list under user fetches all workspaces

### ISSUE THREAD

**Issue by laushinka** [gitpod-io/gitpod#8561]
After this change[[1](https://github.com/gitpod-io/gitpod/pull/8503)], the user detail now fetches all workspaces instead of only the workspaces of the user.

**Comment by gtsiolis** [comment]
Thanks for opening this, @laushinka!

Cc @jldec as this was brought up in our last meeting.

**Comment by laushinka** [comment]
> Cc @jldec as this was brought up in our last meeting.

PR is ready 🙏🏽
