### ISSUE TITLE
[Documentation] Gitpod Self Hosted Monitoring Guide

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#8566]
## Is your feature request related to a problem? Please describe
As a user of the self-hosted version of Gitpod, once I have it running I need to be able to continuously monitor my installation in order to ensure a smooth operation. As such, I need to be able to see what is going on and especially what is going wrong and be able to drill into issues to then fix them. 

## Describe the behaviour you'd like
A high-level description in the docs on how Gitpod does monitoring and how you can do the same as a Self-Hosted user by providing the following pieces of documentation/guarantees:
- How to get observability data out of your installation?
- How to interpret said data - what is important? 
  - Provide a list of "public" that can be used to understand the health of your installation. We should commit to these being "public" and this should be regularly tested in order to ensure consistency. 
  - Also speak to which alerts we use to inform us of any potential issues.

We need to make clear that:
- We will not be able to support the monitoring stack of our users
- Our monitoring and metrics data is subject to change - outside of any officially supported metrics

## Describe alternatives you've considered
Ship monitoring components (e.g. Prometheus, Grafana) together with self-hosted Gitpod - this is not something we think we can support right now, and both the user and the Gitpod team would likely have a bad experience.

## Related Items
- (Internal) [RFC](https://www.notion.so/gitpod/How-do-we-help-Self-Hosted-Customers-Monitor-their-Gitpod-Instance-f9a7489223ba4e9cb49712e071d740d6) where this was first discussed

**Comment by lucasvaltl** [comment]
https://github.com/gitpod-io/customers/issues/29

**Comment by lucasvaltl** [comment]
customers/#29

**Comment by lucasvaltl** [comment]
gitpod-io/customers#29

**Comment by meysholdt** [comment]
Assigning you, @ArthurSens , since you already created PRs.
