### ISSUE TITLE
Open workspace in ad-hoc (per-workspace) editor or IDE

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#8573]
Currently, if a user wants to use a different editor they are required to: 

1. Go to preferences
2. Restart a workspace

**Example use cases:** 
1. You want to use VS Code (web) editor for making "smaller" changes to documentation, markdown etc and having the in-browser functionality makes more sense. 
2. You use a mono-repo with multiple languages or technology stacks and need or want an IDE for multiple aspects of that tech stack. 
3. You have a mono-repo with multiple languages, but you also need the ability to have two editors or IDE's open for the same workspace for doing two different types of work simultaneously. 

This issue is to add a method to directly open a workspace using X editor, overriding the general settings, allowing the user to choose an editor/IDE at workspace start time. This will also speed up the workflow for opening VS Code Desktop users, who currently have to go to the browser, but then use the command palette to open VS Code Desktop. 

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/6874
- https://github.com/gitpod-io/gitpod/issues/9434
- https://github.com/gitpod-io/browser-extension/pull/59
- https://github.com/gitpod-io/gitpod/issues/7525
- https://github.com/gitpod-io/gitpod/pull/9467

**Comment by loujaybee** [comment]
Closing as duplicate of: https://github.com/gitpod-io/gitpod/issues/6874

**Comment by loujaybee** [comment]
Since we now have the IDE preference check for new users, a simple way of implementing this could be to have an "always ask me" setting for IDE on workspace start, which is then shown for all new workspaces.

![image](https://user-images.githubusercontent.com/5528307/171586676-50fe7e8d-a8b8-4712-ab8f-b03d7aaaa4df.png)

**Comment by gtsiolis** [comment]
Thanks for reopening this, @loujaybee! I also think this is still relevant.

I’d :a: take into account the potential entry points to nudge or allow users to select a different editor and :b: try to understand the real user need here to decide whether a _remember me_ option or an _always ask me_ option may be better long-term or as a MVC (minimum viable change) solution. :thought_balloon:  

🍊 🍊 🍊 🍊 

The option to ad-hoc start a workspace from the dashboard or the editor with a different editor sounds interesting and useful. Re-posting from https://github.com/gitpod-io/gitpod/issues/9131#issuecomment-1093000858:

> 1. Introduce a command palette action with two steps that allow users to first select workpace restart using a different editor and then select the editor before restarting the workspace.
> 2. Make the command palette visible a) in the application menu, b) when clicking the branded status bar host, and c) by potentially introducing a new top-level menu item in the actions container above the status bar host, see screenshots `A` and `B`.
> 3. Improve more actions button on the workspace start page, see https://github.com/gitpod-io/gitpod/issues/6910 and screenshot `C`.
> 4. Allow users to change editor option on the fly while workspace is loading and remember their preference.
> 5. Allow users to change the editor after the workspace is loaded and restart the workspace with the new editor, see screenshot `D` and [relevant discussion point](https://www.notion.so/gitpod/All-Hands-632bcbb25bb54c44a3c15c89c1fc41ce#90d9a9dae8774b0abba551d226233c58) (internal) in a past all hands.

> | `A` | `B` | `C` | `D` |
> |-|-|-|-|
> | <img width="1440" alt="Frame 3722" src="https://user-images.githubusercontent.com/120486/162464556-1a29ea06-8c2a-4bb2-a7fd-8a0a7a0286d8.png"> | <img width="1440" alt="Frame 372" src="https://user-images.githubusercontent.com/120486/162464566-3df956ef-9abb-439e-bfb7-64b134e0f0cb.png"> | <img width="1440" alt="144521420-ea95b3ff-92d2-4cc0-aadf-035e2b47f12b (1)" src="https://user-images.githubusercontent.com/120486/162467388-d830f41c-f5f7-4436-8012-f6e8eb957495.png"> | <img width="955" alt="Frame 376" src="https://user-images.githubusercontent.com/120486/162464496-a6ef1352-a780-4210-97d1-32b00765d2bd.png"> |

To this extent, in a recent design exploration, a new _Open with …_ action in the workspace actions was explored, see [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1654156584703959) (internal).

🍋 🍋 🍋 🍋 

Also, this is the [raison d’être](https://en.wikipedia.org/wiki/Raison_d%27%C3%AAtre) of the proposal to introduce a catch-all-cases solution by allowing users to switch editor during the beginning of the workspace loading phase. This could eliminate the need to customize the browser extension or introduce a project or repository based configuration. See [relevant comment](https://github.com/gitpod-io/gitpod/pull/6270#discussion_r734699665) and [relevant discussion](https://gitpod.slack.com/archives/C01V4DL9Q2Z/p1629287635061400?thread_ts=1629284426.058100&cid=C01V4DL9Q2Z).

> We could later also include a dropdown option in the workspace start so that users can change this setting ad-hoc during workspace start in the loading phases where this is possible. 💡

> In contrast, a dropdown selection could allow the loading phase to proceed and only when ready and needed would prompt to open the local VS Code application, but I could be wrong here. This would also connect and surface the selection option from /settings.

> Thinking out loud here, I’d expect this option to be non-editable once the loading phase is near the end where we load the Web IDE.

Re-posting the screenshot below for future reference.

| Early design for allowing users to ad-hoc change editor during workspace start |
|-|
| <img width="1000" alt="138492883-d79a73e4-c824-43ac-b169-6419c7462e8c" src="https://user-images.githubusercontent.com/120486/171594882-9b9cab11-0dc1-4a45-8d64-b7844d337adf.png"> |

**Comment by loujaybee** [comment]
Copying through some context provided by @melaraj2 in: 

- https://github.com/gitpod-io/gitpod/issues/12490

As quite relevant here: 

> My team uses different editors depending on the project. We write applications in Go, Java, NodeJs, Rust. Depending on the language we use different Editors. For Example Java Projects we use IntelliJ, but for Go we typically use Goland, and for Rust, we use VS Code. Currently, we have to first navigate to GitPod preferences and change the editor prior to launching each Repository GitPod. Besides it being tedious, there is no way to store in the repository the appropriate editor configuration that the core team for the project intended. We can store all the other configurations such as databases, but a core thing is an editor that works best for this project.

> At a minimum, we should be able to select the editor at launch time, so that when we click on the GitPod button in github, that it would ask which editor we want to use for that session. Rather than launch a java project with VS Code, or pyCharm.

> A more robust solution is to store the preferred editor in the repository so that we have an en environment that is complete and is ready to use when you hit the button. Of course, we should be able to change it at launch, so this would be the preselected editor when you first launch the GitPod.

**Comment by loujaybee** [comment]
Related user feedback: 

> We need to open two different editors at the same time. We use Kotlin Multiplatform to share code between platforms. When working on web, devs expect to be able to make changes in Kotlin and update the web code at the same time to see how they interact. Devs use IntelliJ for KMP, and VSCode for web

Also shared in: 

- https://github.com/gitpod-io/gitpod/issues/6874

**Comment by svenefftinge** [comment]
done in https://github.com/gitpod-io/gitpod/pull/15389
