### ISSUE TITLE
[Java] `jshell` doesn't work (no user input possible)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#859]
**Describe the bug**
When you try to run `jshell`, the CLI starts, but then refuses to take any user input:

<img width="458" alt="Screenshot 2019-10-17 at 16 06 32" src="https://user-images.githubusercontent.com/599268/67016217-1d8f5880-f0f8-11e9-9954-dba543d5e2a6.png">

Even `^C` or `^D` don't work, the only way to kill it is to open another Terminal and run `killall jshell`.

Originally reported [here](https://spectrum.chat/gitpod/general/running-jshell-in-gitpod~0521cb27-1ebc-418a-989b-180f8dbefa2c).

**To Reproduce**
1. In any Gitpod workspace, run `sdk use java 9.0.4-open` (install if necessary)
2. Run `jshell`
3. Try to type anything into it. Nothing works.

**Expected behavior**
`jshell` should work.

I wonder if this is a bug with https://github.com/eclipse-theia/theia or even https://github.com/xtermjs/xterm.js.

**Comment by JesterOrNot** [comment]
can you send a repo with it installed

**Comment by jankeromnes** [comment]
@JesterOrNot `jshell` is part of Java by default (at least Java 9). The reproduction instructions work in every Gitpod workspace.

**Comment by JesterOrNot** [comment]
Sorry my bad!

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/67034097-ae583b00-f0dc-11e9-966f-964732069733.png)
It doesn't seem to be there

**Comment by jankeromnes** [comment]
Ah, so it's not in the default Java version.

But if you run `sdk use java 9.0.4-open` first, you'll have `jshell`.

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/67057217-3bb78180-f115-11e9-9f15-acba66bef7c2.png)

**Comment by jankeromnes** [comment]
Then you can press Enter to install Java 9. :)

**Comment by jaredblackjcb** [comment]
@jankeromnes did you ever find a solution to this? I'm experiencing the same problem where jshell opens but is unresponsive.

**Comment by ppnrao313** [comment]
I am using java jdk 21. I am facing the same issue. When I used java 17 Jshell was working.
With Java JDK 21 I tried with both cmd and powershell, but no luck.
I have Gitbash in my system, from gitbash I could  use Jshell
