### ISSUE TITLE
[prebuilds] Failed Prebuilds without Snapshot are marked as 'available'

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#8592]
There are many failing prebuilds without a snapshot that are still marked as `available` and therefore used for new workspace starts.
```SQL
SELECT * FROM d_b_prebuilt_workspace WHERE snapshot='' and state = 'available' order by creationTime DESC
```

- We need to figure out why these workspaces fail (many have an error message (Out of Memory) but some don't).
- Make sure they are marked as failed, so they are not considered when starting a workspace.

**Comment by svenefftinge** [comment]
I'm looking into filtering those prebuilds out.

**Comment by geropl** [comment]
Discovered yesterday [here](https://github.com/gitpod-io/gitpod/issues/8096#issuecomment-1058175304).

@svenefftinge I don#t think it's possible. Quick sync?

**Comment by geropl** [comment]
We figured out there are two issues here:
 - @svenefftinge figured that we're failing to check the `prebuild.error` state when trying to determine whether a snapshot is `available` or not
 - there is a problem with failing prebuilds overriding their failed state (#8096)

**Comment by geropl** [comment]
Removing the workspace label as the interpretation is webapps responsibility.
