### ISSUE TITLE
Support Zip Context

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#86]
It should be possible to create a workspace from any URL returning a zip, tar or similar.

Example: gitpod.io#https://gitlab.com/svenefftinge/sdfdfsdfd/-/archive/master/sdfdfsdfd-master.zip

This should allow for better integration with e.g. https://start.spring.io/ as well
Or let me have a command line utility that would zip the current contents of a directory and create a cloud workspace for it.

**Comment by felixfbecker** [comment]
I would love this! My use case is reviewing coding exercise submissions from candidates.
