### ISSUE TITLE
Include a button icon on the login page for Bitbucket Server provider

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#8603]
### Problem to solve

Bitbucket Server (https://github.com/gitpod-io/gitpod/issues/8499) support was added in https://github.com/gitpod-io/gitpod/pull/8086, however, the login button for this type of provider is not using the button layout as the rest of the providers.

See https://github.com/gitpod-io/gitpod/pull/8086#issuecomment-1036352689 and [relevant discussion](https://gitpod.slack.com/archives/C01LDA28WV6/p1646338858901439) (internal). Cc @metcalfc @corneliusludmann @jldec 

![153623370-f59601d5-1170-4133-9784-8d624b1cf589](https://user-images.githubusercontent.com/120486/156772384-4c183d66-9521-433b-b401-6ab72ccaa7b7.png)

### Proposal

This could be resolved by simply re-using the Bitbucket icon as the button icon for this type of provider.

**Comment by jldec** [comment]
@gtsiolis I think we need a button layout which is not truncated.  
E.g. something more like the wider error-page auth button below (but consistent with the other buttons)

![Screenshot 2022-03-15 at 08 08 08](https://user-images.githubusercontent.com/849592/158335098-aa714597-4acd-49b8-b44b-77931cf3fc48.png)

**Comment by AlexTugarev** [comment]
@gtsiolis are you working on this? it's a recurring thing mentioned on other PRs.

**Comment by AlexTugarev** [comment]
@gtsiolis, reusing the icon from Bitbucket seems fairly easy, right? The more interesting part is render the labels properly. Do you have a suggestion for that?

**Comment by gtsiolis** [comment]
@AlexTugarev I'm not actively working on any designs for this. Like you mentioned in https://github.com/gitpod-io/gitpod/issues/8603#issuecomment-1087303433, reusing the Bitbucket icon is a great MVC (minimum viable change) for this issue. 🛹 

**thought**: The truncation issue mentioned in https://github.com/gitpod-io/gitpod/issues/8603#issuecomment-1067691775 is a different issue and can probably be tackled separately. Also, feature requests like https://github.com/gitpod-io/gitpod/issues/7061 could make the truncation issue obsolete.

**suggestion**: For resolving this issue, I'd suggest to simply re-use the Bitbucket icon and optionally use a title attribute for making the button more accessible. We could open a follow up issue to tackle the truncation issue separately. ➿
