### ISSUE TITLE
Add additional DNS01 challenge resolvers

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#8604]
The current DNS01 challenge resolvers are Google and Azure, with an optional in-cluster (self-signed cert - see #8559). 

# Required
- [ ] [Route53](https://cert-manager.io/docs/configuration/acme/dns01/route53/)

# Recommended
- [ ] [DigitalOcean](https://cert-manager.io/docs/configuration/acme/dns01/digitalocean/)
- [ ] [CloudFlare](https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/)

# Optional
- [ ] [ACME-DNS](https://cert-manager.io/docs/configuration/acme/dns01/acme-dns/) - may be affected by the documented limitations as would require 3 domains (`$DOMAIN`, `*.$DOMAIN` and `*.ws.$DOMAIN`)
- [ ] [Akamai](https://cert-manager.io/docs/configuration/acme/dns01/akamai/)
- [ ] [RFC-2136](https://cert-manager.io/docs/configuration/acme/dns01/rfc2136/)
- [ ] [Webhook](https://cert-manager.io/docs/configuration/acme/dns01/webhook/)

**Comment by MrSimonEmms** [comment]
Closing as cert-manager is now no longer configured by KOTS /cc @gitpod-io/engineering-self-hosted

**Comment by Pothulapati** [comment]
@MrSimonEmms We don't want to install `cert-manager`  but we still create the `Certificate` object and there we need the DNS01 challenge right? 🤔 

Even #8785 doesn't remove the DNS101 config, right now!

**Comment by MrSimonEmms** [comment]
Good call @Pothulapati
