### ISSUE TITLE
Please make Werft support arbitrarily long branch names

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8605]
### Bug description

Currently, Werft spontaneously fails your Pull Request if your branch name is not extremely short:

https://github.com/gitpod-io/gitpod/blob/73cbeefeed30f5b74d5d0d9228a47305b7ea9a16/.werft/build.ts#L52-L55

The only solution is to pack up your work and move to a completely new branch / Pull Request.

This is becoming a significant tax on Gitpod's developer velocity and happiness:

- https://github.com/gitpod-io/gitpod/pull/8046#issuecomment-1041809653
- https://github.com/gitpod-io/gitpod/pull/8502#issuecomment-1055411229
- https://github.com/gitpod-io/gitpod/pull/8485#issuecomment-1054230044
- https://github.com/gitpod-io/gitpod/pull/8490#issuecomment-1054467653
- https://github.com/gitpod-io/gitpod/pull/8601#issuecomment-1059169619
- https://github.com/gitpod-io/gitpod/pull/8280#issuecomment-1046678841
- https://github.com/gitpod-io/gitpod/pull/7390#issuecomment-1002991206
- https://github.com/gitpod-io/gitpod/pull/7428#issuecomment-1004818649
- https://github.com/gitpod-io/gitpod/pull/8421#issuecomment-1049646499
- ...

Could we please find a way to support slightly longer branch names? 🙏 😍 (For example [like so](https://github.com/gitpod-io/gitpod/issues/8169#issuecomment-1044283920))

### Steps to reproduce

1. Contribute to Gitpod
2. Get frustrated 🤬

### Expected behavior

1. Contribute to Gitpod
2. Smooth sailing ⛵

### Example repository

https://github.com/gitpod-io/gitpod

**Comment by laushinka** [comment]
> ### Steps to reproduce
> 1. Contribute to Gitpod
> 2. Get frustrated 🤬
> 

🤣

**Comment by mads-hartmann** [comment]
@jankeromnes I know this is extremely frustrating. We have previously discussed possible solutions [here](https://github.com/gitpod-io/ops/issues/1252#issuecomment-1046815121) but as this entire problem will go away once we use VM-based preview environments we had so far prioritised getting that into a shape where we can ship them.

However as the beta deadline has slipped and we won't be able to delete core-dev until all teams have migrated to the Installer I believe it's worth trying to fix this. The team is currently split 3/4 working on VMs and 1/4 (me) trying to "keep the fort". I will close this issue in favour of https://github.com/gitpod-io/ops/issues/1252 as it already has all the context and then move it to the current iteration. However as it's only me and there's already a ton on my plate I can't promise that I'll get to it this week.
