### ISSUE TITLE
witchcraft

### ISSUE THREAD

**Issue by sammysimmons** [gitpod-io/gitpod#862]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by JesterOrNot** [comment]
What is the issue that you are having?

**Comment by sammysimmons** [comment]
Ive created a new repository via github and when i click gitpod, the page
doesnt load, im literally staring at this.......
[image: Screenshot 2019-10-20 at 20.06.36.png]

**Comment by JesterOrNot** [comment]
I am unable to see the screenshot can you give a link to the repo?

**Comment by AlexTugarev** [comment]
Hi @sammysimmons! Just tried to open https://github.com/sammysimmons/witchcraft in Gitpod. Could you describe the issue, please?

**Comment by svenefftinge** [comment]
Closing as of lack of information on what to solve here. Please open a new ticket with additional information if the problem still exists.
