### ISSUE TITLE
Have script to distribute a VM image to all Harvester nodes

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#8634]
When we roll out a new VM image to Harvester, it will get pulled onto a node (if it's not there yet)  when a VM gets started. 

However, for 200GB this can take up to 40min per node. 

<img width="290" alt="image" src="https://user-images.githubusercontent.com/239422/157015014-b884fc6b-8f5f-4aea-b081-0b781c3350e0.png">

To avoid a person waiting so long for their VM, we should run a script that distributes the image to all nodes. 

Proposed solution: Have a script that starts a VM using the new node to ensure the image gets replicated. The script can delete the VM afterward. NodeSelectos can be used to assign VMs to nodes. 
In the future, if there is a CI job to create images, the job can also run this scipt.

**Comment by mads-hartmann** [comment]
From our meeting: The script should live in `dev/preview` in gitpod-io/gitpod, .

Example invocation:

```sh
dev/preview/preload-vm-image.sh <image-id>
```

**Comment by meysholdt** [comment]
Fixed via https://github.com/gitpod-io/gitpod/pull/8898
