### ISSUE TITLE
VS Code does not use pyenv global Python version by default

### ISSUE THREAD

**Issue by jab** [gitpod-io/gitpod#8646]
### Bug description

The https://www.gitpod.io/docs/languages/python#python-versions docs explain how to use pyenv to install and use a different global version of Python from the system version, namely `pyenv install x.y.z && pyenv global x.y.z`. (This is particularly important because the system version of Python is 3.8, which is old enough to be in [security-fix-only status](https://www.python.org/downloads/), i.e. no longer receiving bugfixes.)

Even if you follow these docs, though, VS Code still starts up using Python 3.8 by default:

![](https://user-images.githubusercontent.com/64992/156382804-883bf53c-c7a6-4de1-8142-251b18e59e55.png)

Either the docs should be expanded to explain how to configure VS Code to use the global version of Python that the .gitpod.yml maintainer has chosen via `pyenv global x.y.z`, or better yet, GitPod should automatically configure VS Code to use the version that the .gitpod.yml maintainer has chosen via `pyenv global x.y.z`, so that it is not necessary for each .gitpod.yml maintainer who is following these docs to repeat all this extra boilerplate.

An example can be found in:
* https://gitpod.io/#https://github.com/jab/bidict
* Ref: https://github.com/jab/bidict/blob/062ccb6a72f181295be54adb1ebdafaaad5cd2a3/.gitpod.yml#L19-L28

### Steps to reproduce

1. Follow the https://www.gitpod.io/docs/languages/python#python-versions docs to use pyenv to install a different Python version and choose it as the global version in the `init` task, as in https://github.com/jab/bidict/blob/062ccb6a72f181295be54adb1ebdafaaad5cd2a3/.gitpod.yml#L19-L28
2. Open the resulting workspace
3. Observe that VS Code still starts up using the system Python version (3.8) rather than the configured pyenv global version.

### Example repository

https://github.com/jab/bidict

**Comment by pawlean** [comment]
👋🏼  Thanks for raising this, @jab.

It seems like a good next step is to expand the docs. Before I raise this, @akosyakov / @loujaybee I just wanted to check -- is there anything you can do here:

> should automatically configure VS Code to use the version that the .gitpod.yml maintainer has chosen via pyenv global x.y.z, so that it is not necessary for each .gitpod.yml maintainer who is following these docs to repeat all this extra boilerplate.

**Comment by axonasif** [comment]
I think this has something to do with how we setup python at here:
https://github.com/gitpod-io/workspace-images/blob/main/chunks/lang-python/Dockerfile

There have been other issues with this too that a good number of users had reported.

**Comment by huweiATgithub** [comment]
I guess this might be due to the process that the `pyenv global` call is invoked after vscode is started.
Namely, vscode loads the version set in Dockerfile before you set the version via init.
A vscode reload (Ctrl+Shift+P -> reload or close and reopen web) will fix the version (I tested).

Another workaround is to add a Dockerfile that builds on top of the gitpod image and do the `pyenv global` stuff there. Then the python version is set before the vscode start.

**Comment by jab** [comment]
Issue is still present and should not be closed if there is still interest in addressing it (including even just updating the docs as a start, as @pawlean agreed should be done).

**Comment by axonasif** [comment]
Hi @jab, https://github.com/gitpod-io/gitpod/issues/8646 should fix this issue.
However, the change was not pushed to our https://hub.docker.com/r/gitpod/workspace-full/tags yet. Someone from our workspace team will need to trigger the build+push, they'll do it next week probably.

If you need a fix asap, you could use `image: axonasif/workspace-python` for now on your `.gitpod.yml`.

**Comment by jab** [comment]
Awesome, thanks so much for taking care of this, @axonasif! Could you please ping this issue when the fix has made its way out to workspace-full? Then I'll be happy to post back here confirming the fix.

**Comment by axonasif** [comment]
@jab it has now, but you have to use the most recent `timestamped` tag from here: https://hub.docker.com/r/gitpod/workspace-full/tags
Because `latest` tag will be updated later.


By the time of writing this, it should be `image: gitpod/workspace-full:2022-08-13-08-17-48` or you could even use `image: gitpod/workspace-python:2022-08-13-08-17-48`

**Comment by jab** [comment]
Thanks @axonasif, though since this isn't urgent, I'm just waiting until this fix makes it out to `gitpod/workspace-python:latest`.

If you can, please ping this issue once the fix is on `latest`, and then I can test and report back here. Thanks again for fixing this.
