### ISSUE TITLE
Unable to run my server

### ISSUE THREAD

**Issue by IzzySoprano** [gitpod-io/gitpod#8656]
### Bug description

Source control and extension timer doesn't work and I'm unable to run my server. 

### Steps to reproduce

-

### Workspace affected

https://izzysoprano-wegloveboxin-behvqvxh5cu.ws-eu34xl.gitpod.io/

### Expected behavior

My workspace isn't working properly because of this

**Comment by pawlean** [comment]
Hey @IzzySoprano! Can you try and restart your workspace or start a new one to see if this still persists?

**Comment by IzzySoprano** [comment]
I have, I've tried refreshing my page, nothing

**Comment by pawlean** [comment]
Hey @IzzySoprano! Can you try starting a new workspace? https://gitpod.io/workspaces
