### ISSUE TITLE
Cleanup workspaces after a PR is merged

### ISSUE THREAD

**Issue by raisedadead** [gitpod-io/gitpod#866]
Hi,

I was wondering if it is possible to add a configuration or something to automatically cleanup the workspaces at https://gitpod.io/workspaces once a PR is merged?

Maybe there could be a threshold that we could set, post which they get removed?

At this minute this is just a minor nitpick for me personally, we review hundreds of PRs and these workspaces keep piling on the dashboard.

**Comment by svenefftinge** [comment]
The plan is delete all workspaces automatically after some time, as long as 
 - they have not been pinned (will replace the somewhat useless archive)
 - they don't have pending changes in git
 - they don't contain snapshots

**Comment by raisedadead** [comment]
Perfect, sounds reasonable.

**Comment by tony-shannon** [comment]
The pins sounds like a good idea, the one feature request I would add it the ability to add tags to those workspaces with (+/- without) pins
Happy to raise that as a seperate feature request here, its based on a conversation here;
https://spectrum.chat/gitpod/general/small-feature-suggestion-tags~ad8d124d-b856-4050-b541-0fcd65d09f5d

**Comment by svenefftinge** [comment]
@tony-shannon yes, please file an extra issue as I think it is orthogonal. I was pointing you to this issue because I hope it will already help you stay organised without tags.

**Comment by svenefftinge** [comment]
This will also remove and close https://github.com/gitpod-io/gitpod/issues/948

**Comment by svenefftinge** [comment]
in production.
