### ISSUE TITLE
Accelerate VM start speed

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#8662]
Analyze the time from VM-creation until the readiness probe is ready (because ssh is is-and-running):

Ideas:
* Confirm that the GCP Agent did never run. see https://github.com/gitpod-io/gitpod/pull/8639.
* run `systemd-analyze blame` so see where the time went.
* Confirm that the VM has no unneeded hardware that takes time to initialize

**Comment by ArthurSens** [comment]
A couple of extra efforts are being done here:
* Require less successful probes to make VM ready https://github.com/gitpod-io/gitpod/pull/8667
* Boot VM in parallel with `leeway build`
* Issue SSL certificate in parallel with `leeway build`

**Comment by meysholdt** [comment]
IMHO VM startup speed is good enough for now. The new bottlenecks are :
* https://github.com/gitpod-io/gitpod/issues/8663.
* https://github.com/gitpod-io/gitpod/pull/8690
