### ISSUE TITLE
Can't push to github with 2FA

### ISSUE THREAD

**Issue by buggtb** [gitpod-io/gitpod#8665]
### Bug description

I don't know whats happening but when I open a new workspace using IntelliJ I have to jump through many hoops to actually push it back to github.

In gitlab I can open a terminal and commit push and it works, in github I get:

remote: Permission to unity-sds/unity-cs-terraform-transformer.git denied to buggtb.
fatal: unable to access 'https://github.com/unity-sds/unity-cs-terraform-transformer.git/': The requested URL returned error: 403

which is ironic because I created that repo and I'm an admin on it.

If I use the VCS tooling inside IntelliJ I get the same error.

### Steps to reproduce

Create workspace via gitpod github button. 

Commit and push.

**Comment by axonasif** [comment]
Hey @buggtb, can you try in a new workspace? Not sure if this has to do something but worth a try. Other than that, our IDE team will be able to help if needed 🙏

**Comment by buggtb** [comment]
Oh this isn't new, this has been the same in various workspaces for a few weeks

**Comment by buggtb** [comment]
oooh, I suspect I know what it is, I have github 2FA enabled. Cause if I flip the url scheme and stick a key in the .ssh folder I can push to it.

**Comment by axonasif** [comment]
Is it happening on VSCODE too, can you please confirm?
If not:
Can you check if you have proper permissions granted for Github integration at https://gitpod.io/preferences ?
Also please see https://github.com/gitpod-io/gitpod/issues/8076 for more context.

**Comment by axonasif** [comment]
> oooh, I suspect I know what it is, I have github 2FA enabled. Cause if I flip the url scheme and stick a key in the .ssh folder I can push to it.

Maybe try removing the github integration and adding it back, I have 2FA on my account too, probably the github token needs a refresh 🤔

**Comment by axonasif** [comment]
> yeah its mega confusing, the gitpod integration isn't on the org, so its probably that, but its a public repo, so it doesn't look like the stuff on the other ticket. Also if I create a token inside IntelliJ it doesn't work there either, but also doesn't tell anyone why.
> 
> Github make this so much harder than Gitlab 😒

That ticket applies to both public and private repos in some aspects. Just make sure that you have a proper github integration and check that github is not blocking gitpod in `third-party-access` as per the linked ticket.
