### ISSUE TITLE
Implement `Gitpod: Collect Logs` comand

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#8672]
## Is your feature request related to a problem? Please describe

It would be really helpful to implement a `Gitpod: Collect Logs` command so users can easily collect logs and shared them with us when they encounter some issue

Investigate if this should be implemented in gitpod/workbench or as an extension command

**Comment by akosyakov** [comment]
It should collect as much as possible, i.e.:
- info from about dialog, which browser, version and so on
- info about workspace, which workspace id, which session id
- VS Code frontend logs, i.e. windows, data sync
- VS Code backend logs, i.e server, extension host
- content of output views?

Something else?

**Comment by shaal** [comment]
Yes please! We discussed this during today's Gitpod Office Hours

**Comment by jeanp413** [comment]
Fixed in https://github.com/gitpod-io/openvscode-server/pull/327
