### ISSUE TITLE
Preview Env: Can't copy certificate

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#8677]
When launching a preview env on Harvester, I got the following error:
```
[certificate] + cd /workspace/.werft/util/templates
[certificate] + cp cert-manager_certificate.tpl cert.yaml
[certificate] + yq w -i cert.yaml metadata.name proxy-config-certificates
[certificate] + yq w -i cert.yaml spec.secretName proxy-config-certificates
[certificate] + yq w -i cert.yaml metadata.namespace default
[certificate] + yq w -i cert.yaml spec.dnsNames[+] me-test5.preview.gitpod-dev.com
[certificate] + yq w -i cert.yaml spec.dnsNames[+] *.me-test5.preview.gitpod-dev.com
[certificate] + yq w -i cert.yaml spec.dnsNames[+] *.ws.me-test5.preview.gitpod-dev.com
[certificate] + kubectl apply -f cert.yaml
[certificate] error: unable to recognize "cert.yaml": no matches for kind "Certificate" in version "cert-manager.io/v1"
[certificate] 
[certificate|DONE]
```

Source: https://werft.gitpod-dev.com/job/gitpod-build-me-test5.1/raw

I assume this is a race condition: We tried to install the cert before the CRD (part of cert-manager) was installed properly.

**Comment by ArthurSens** [comment]
Does it make sense to install the CRD as part of cloud-init?

**Comment by meysholdt** [comment]
> Does it make sense to install the CRD as part of cloud-init?

We do that already :(

https://github.com/gitpod-io/gitpod/blob/fc320488f250220c908b5bb1453b800cbb706cc8/.werft/vm/manifests.ts#L223

**Comment by meysholdt** [comment]
Correction: The code that fails is the code that should issue the cert:
https://github.com/gitpod-io/gitpod/blob/fc320488f250220c908b5bb1453b800cbb706cc8/.werft/util/certs.ts#L26-L51

Thus no race condition. More likely it's the wrong kubectl context or something with core-dev. Cert-issuing is supposed to happen on core-dev.

**Comment by meysholdt** [comment]
We [request the certs](https://github.com/gitpod-io/gitpod/blob/fc320488f250220c908b5bb1453b800cbb706cc8/.werft/jobs/build/deploy-to-preview-environment.ts#L133) after we [change the kubectl-context to  k3s](https://github.com/gitpod-io/gitpod/blob/fc320488f250220c908b5bb1453b800cbb706cc8/.werft/jobs/build/deploy-to-preview-environment.ts#L123).

Thus it's the wrong kubectl context. However, we also [never copy the certs](https://github.com/gitpod-io/gitpod/blob/fc320488f250220c908b5bb1453b800cbb706cc8/.werft/jobs/build/deploy-to-preview-environment.ts#L230).

Two possible solutions:
a) keep the certificate request in k3s for now and fix the race condition by waiting until cert-manager is up-and-running.
b) implement the "start requesting certs at the very beginning of the job, i.e. before we run leeway" we discussed in the platform sync on monday.

**Comment by meysholdt** [comment]
I just noticed the the error also occurs two steps earlier in the Werft Job:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/239422/157427408-22041b36-30d7-49ea-ab1d-05e0404eef0e.png">

**Comment by meysholdt** [comment]
Fixed: Now we wait until the cert-manager is ready before we install Gitpod.
