### ISSUE TITLE
Gitpod Rebooting Automatically

### ISSUE THREAD

**Issue by VMORI0112** [gitpod-io/gitpod#868]
**Describe the bug**

While using "d6a998dd-c77f-4145-ac29-bb9e8c7a55fe", gitpod rebooted and opened a different repository (https://github.com/4GeeksAcademy/flask-rest-hello), which I did not use before.

**To Reproduce**

Not able to reproduce- there have been issues lately with the service properly saving changes while online (the status bar was blue). Not sure if related but wanted to mention.

**Expected behavior**

My project not to close until I close it!

**Comment by svenefftinge** [comment]
This sounds super weird. What do you mean with reboot, was also the browser reloading or would it just out of nothing show you the other project?

**Comment by svenefftinge** [comment]
It looks like you have started a workspace on that repo (id: cbf14d96-7772-4721-9001-8b5cdcd84221) at 2019-10-23T18:14:49.967Z. The context url seems to be generated by the breatheco.de app. Are you sure you didn't confuse tabs somehow or so?

**Comment by svenefftinge** [comment]
Cc @alesanchezr does this ring a bell somehow on your side?

**Comment by VMORI0112** [comment]
Hi Sven,
It was looked like when you open a project that you choose from you repository and click the gitpod button to get inside the code. But, the project that open was new and the other environment not requested.

Thanks in advance.

Sent from my iPhone

On Oct 25, 2019, at 10:00 AM, Sven Efftinge <notifications@github.com<mailto:notifications@github.com>> wrote:


Cc @alesanchezr<https://github.com/alesanchezr> does this ring a bell somehow on your side?
