### ISSUE TITLE
Workspace list tooltip annoyances

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#8686]
Small changes which would make the workspace list less annoying :)

1. The tooltip for the git repo URL should not obscure the workspace name (see below)
  ![Screenshot 2022-03-09 at 12 12 58](https://user-images.githubusercontent.com/849592/157439932-6b636209-c8ef-4db6-9701-4efd25449028.png)

2. Other truncated URLs like the context URL are missing tooltips, so you can't tell what the actual value is

3. Human-readable timestamps like "14 hours ago" are missing a tooltip to see the actual time
  The example below which does not have this problem (but is hard to read) is from GitHub
  ![Screenshot 2022-03-09 at 12 09 40](https://user-images.githubusercontent.com/849592/157439719-b57b2256-87a7-4fac-a547-758e7d1c950a.png)

cc: @gtsiolis

**Comment by jldec** [comment]
Some suggestions for fixes [here](https://app.frontapp.com/open/cnv_iv8eu4q) (internal)

**Comment by gtsiolis** [comment]
For points [1] and [2] I'd say improving the design of the Workspaces page is a good way forward. This could include removing duplicate information that is currently truncated, dropping any unnecessary elements, replacing long repository URLs with project links when possible, etc.

FWIW, the tooltip on the project (repository URL) was added back in https://github.com/gitpod-io/gitpod/pull/5323 as a **boring (simple) solution** and a **two-way door decision** which we can safely remove in the future, see https://github.com/gitpod-io/gitpod/issues/5122#issuecomment-903692584. 💭 

In some cases, middle truncation could help, see https://github.com/gitpod-io/gitpod/issues/5122#issuecomment-895863295. 💡 

🍊 🍊 🍊 🍊 

For point [3] I'd recommend to open a separate issue to tackle in a separate step as fixing this spans across multiple product areas.

🍋 🍋 🍋 🍋 

Thanks for the ping, @jldec! 🏓

**Comment by geropl** [comment]
@jldec putting this into "needs design" until it's minimal/as actionable as it can be.

**Comment by jldec** [comment]
Moved to Dashboard UX 
The issue was intended to focus only on improving tooltips in this context.

**Comment by gtsiolis** [comment]
Closed this as part of the work in #15716, for more context see https://github.com/gitpod-io/gitpod/pull/15716#pullrequestreview-1245982606.
