### ISSUE TITLE
[VS Code] 'add remotes' extension doesn't work

### ISSUE THREAD

**Issue by vadi2** [gitpod-io/gitpod#869]
Github was refusing authentication for me pushing to a branch I own in a repository, so Gitpod couldn't push any of the changes.

Since Gitpod out of the box can't add any other remotes, this presented a problem. I tried installing the vscode extension that allows you to [add remotes](https://marketplace.visualstudio.com/items?itemName=samschneller.git-add-remote&ssr=false#overview) - installation was fine, but the extension failed to work, giving a message of "added undefined to undefined".

This means that all my work in Gitpod was lost, since I couldn't push it anywhere, and I had to recreate it outside of Gitpod.

**Comment by svenefftinge** [comment]
Oh, I'm sorry. These kind of roadblocks are super annoying.
You can always use the command line, though:

```
git remote add [<options>] <name> <url>
```

See 
```
git remote add --help
```

But thanks for reporting that the extension doesn't work, we will look into it.

**Comment by vadi2** [comment]
Ah! I didn't know you can use it that way. Thanks!
