### ISSUE TITLE
[gp cli] restart tasks support

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#8691]
## Is your feature request related to a problem? Please describe

Being able to re-run/re-start a `.gitpod.yml` task from the `gp` CLI during workspace-user-session.

## Describe the behaviour you'd like

`gp task rerun all`
`gp task rerun <task-name>`

## Additional context

A user had wished to have such functionality. [^1]

[^1]: https://canary.discord.com/channels/816244985187008514/816246578594840586/902767340222025738

**Comment by akosyakov** [comment]
We need to distinguish initial tasks and tasks from .gitpod.yml, i.e. whether do you want to run task how it was configured before workspace start or after changes in .gitpod.yml?

**Comment by akosyakov** [comment]
I think it should be called `run` similarly how in other IDEs, i.e. tasks in VS Code and I won't do `run all` at the beginning.

**Comment by loujaybee** [comment]
Given the introduction of `gp validate`, I think we can consider this closed, what do you think? 

That is a way you can essentially restart all your tasks, which I think meets the needs of the original suggestion, here. 

See issue comment: https://github.com/gitpod-io/gitpod/issues/7671#issuecomment-1503186622
