### ISSUE TITLE
Workspaces stuck at building image - readiness probe failed: dial tcp x.x.x.x:22999: connect: connection refused

### ISSUE THREAD

**Issue by rbicker** [gitpod-io/gitpod#8693]
### Bug description

Hi

In a fresh self-hosted k3s based gitpod installation, we are unable to start workspaces. In the web UI, all workspaces get stuck at "building image".

We can see that the imagebuild pod never becomes ready.

```bash
[root@gitpod:~]# kubectl get po
NAME                                              READY   STATUS    RESTARTS   AGE
svclb-proxy-w55cc                                 3/3     Running   0          96m
openvsx-proxy-0                                   1/1     Running   0          96m
agent-smith-dkxfq                                 2/2     Running   0          96m
blobserve-694cc88889-zch28                        2/2     Running   0          96m
content-service-54747f8564-n48jn                  1/1     Running   0          96m
ws-manager-6f555b77b7-n5j82                       2/2     Running   0          96m
dashboard-74b899b845-44p8c                        1/1     Running   0          96m
registry-facade-tmlkv                             2/2     Running   0          96m
ide-proxy-64bb4dc76b-x2k9k                        1/1     Running   0          96m
proxy-5b9659d8d6-hgkmw                            2/2     Running   0          96m
image-builder-mk3-fd5585c7b-z7wxq                 2/2     Running   0          96m
ws-proxy-754cbbbc77-zmqt9                         1/1     Running   0          96m
registry-86f799b456-6tjcs                         1/1     Running   0          96m
minio-d67977b96-67dmh                             1/1     Running   0          96m
ws-daemon-qh7bh                                   2/2     Running   0          96m
mysql-0                                           1/1     Running   0          96m
messagebus-0                                      1/1     Running   0          96m
server-7759cc55bf-tztxn                           2/2     Running   0          96m
ws-manager-bridge-55b9948899-xmqk2                2/2     Running   0          96m
imagebuild-05a6a443-774b-44f1-b119-91b91bc38829   0/1     Running   0          17m
```

When describing the pod, we  can see that the readiness probe keeps failing.

```bash
[root@gitpod:~]# kubectl describe pod imagebuild-05a6a443-774b-44f1-b119-91b91bc38829 
Name:         imagebuild-05a6a443-774b-44f1-b119-91b91bc38829
Namespace:    default
Priority:     0
Node:         gitpod.example.com/10.100.112.48
Start Time:   Wed, 09 Mar 2022 15:41:06 +0100
Labels:       app=gitpod
              component=workspace
              gitpod.io/networkpolicy=default
              gpwsman=true
              headless=true
              metaID=05a6a443-774b-44f1-b119-91b91bc38829
              owner=image-builder
              workspaceID=05a6a443-774b-44f1-b119-91b91bc38829
              workspaceType=imagebuild
Annotations:  cluster-autoscaler.kubernetes.io/safe-to-evict: false
              container.apparmor.security.beta.kubernetes.io/workspace: unconfined
              gitpod.io/annotation.baseref: docker.io/gitpod/workspace-full@sha256:42c36a03ed9f1632dce28d4564c376416c77bcd1ea4f2cef509d2ee60d66357b
              gitpod.io/annotation.ref: registry.gitpod.example.com/workspace-images:68f415049cf6f3028c3427028d3699e5cc2ab3a915c4ddc623c4ec5d3e21369d
              gitpod.io/nodeName: gitpod.example.com
              gitpod.io/requiredNodeServices: ws-daemon,registry-facade
              gitpod/admission: admit_owner_only
              gitpod/contentInitializer: CgA=
              gitpod/customTimeout: 1h0m0s
              gitpod/id: 05a6a443-774b-44f1-b119-91b91bc38829
              gitpod/imageSpec:
                Cl5ldS5nY3IuaW8vZ2l0cG9kLWNvcmUtZGV2L2J1aWxkL2ltYWdlLWJ1aWxkZXItbWszL2JvYjpmYmIzZTFkN2NmMWFlOGMzMWE4ZGI0NDAyOWU5YTZkNjY2MGNiYmI5El5ldS5nY3...
              gitpod/never-ready: true
              gitpod/ownerToken: -G9zrJRtPYp9cbWBeq9VLHt2FqRg8q4u
              gitpod/servicePrefix: 05a6a443-774b-44f1-b119-91b91bc38829
              gitpod/url: https://05a6a443-774b-44f1-b119-91b91bc38829.ws.gitpod.example.com
              prometheus.io/path: /metrics
              prometheus.io/port: 23000
              prometheus.io/scrape: true
              seccomp.security.alpha.kubernetes.io/pod: localhost/workspace_default_release-2022.02.0.1.json
Status:       Running
IP:           10.42.0.33
IPs:
  IP:  10.42.0.33
Containers:
  workspace:
    Container ID:  containerd://113971ac8d363ad09b0745fd0f6f6ab85f5684ff76ba8e0196089a8a3312e840
    Image:         reg.gitpod.example.com:30000/remote/05a6a443-774b-44f1-b119-91b91bc38829
    Image ID:      reg.gitpod.example.com:30000/remote/05a6a443-774b-44f1-b119-91b91bc38829@sha256:02e261199d90fe1b33895c058fe0a89de1b118d9ec5868df73bfd779d2533f5b
    Port:          23000/TCP
    Host Port:     0/TCP
    Command:
      /.supervisor/workspacekit
      ring0
    State:          Running
      Started:      Wed, 09 Mar 2022 15:41:07 +0100
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      1
      memory:   2Gi
    Readiness:  http-get http://:22999/_supervisor/v1/status/content/wait/true delay=3s timeout=1s period=1s #success=1 #failure=600
    Environment:
      GITPOD_REPO_ROOT:                 /workspace
      GITPOD_CLI_APITOKEN:              tR_TkYNHyN7sGPcYC9MmEOmRfLZAzNeO
      GITPOD_WORKSPACE_ID:              05a6a443-774b-44f1-b119-91b91bc38829
      GITPOD_INSTANCE_ID:               05a6a443-774b-44f1-b119-91b91bc38829
      GITPOD_THEIA_PORT:                23000
      THEIA_WORKSPACE_ROOT:             /workspace
      GITPOD_HOST:                      https://gitpod.example.com
      GITPOD_WORKSPACE_URL:             https://05a6a443-774b-44f1-b119-91b91bc38829.ws.gitpod.example.com
      GITPOD_WORKSPACE_CLUSTER_HOST:    ws.gitpod.example.com
      THEIA_SUPERVISOR_ENDPOINT:        :22999
      THEIA_WEBVIEW_EXTERNAL_ENDPOINT:  webview-{{hostname}}
      THEIA_MINI_BROWSER_HOST_PATTERN:  browser-{{hostname}}
      BOB_TARGET_REF:                   localhost:8080/target:latest
      BOB_BASE_REF:                     localhost:8080/base@sha256:42c36a03ed9f1632dce28d4564c376416c77bcd1ea4f2cef509d2ee60d66357b
      BOB_BUILD_BASE:                   false
      BOB_DOCKERFILE_PATH:              /workspace/Dockerfile
      BOB_CONTEXT_DIR:                  /workspace
      GITPOD_TASKS:                     [{"name": "build", "init": "sudo -E /app/bob build"}]
      WORKSPACEKIT_RING2_ENCLAVE:       /app/bob proxy
      WORKSPACEKIT_BOBPROXY_BASEREF:    docker.io/gitpod/workspace-full@sha256:42c36a03ed9f1632dce28d4564c376416c77bcd1ea4f2cef509d2ee60d66357b
      WORKSPACEKIT_BOBPROXY_TARGETREF:  registry.gitpod.example.com/workspace-images:68f415049cf6f3028c3427028d3699e5cc2ab3a915c4ddc623c4ec5d3e21369d
      WORKSPACEKIT_BOBPROXY_AUTH:       <set to the key '.dockerconfigjson' in secret 'builtin-registry-auth'>  Optional: false
      SUPERVISOR_DEBUG_ENABLE:          false
      GITPOD_INTERVAL:                  30000
      GITPOD_MEMORY:                    2147
      GITPOD_HEADLESS:                  true
    Mounts:
      /.workspace from daemon-mount (rw)
      /usr/local/share/ca-certificates/gitpod-ca.crt from gitpod-ca-certificate (ro,path="ca.crt")
      /workspace from vol-this-workspace (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  vol-this-workspace:
    Type:          HostPath (bare host directory volume)
    Path:          /var/gitpod/workspaces/05a6a443-774b-44f1-b119-91b91bc38829
    HostPathType:  DirectoryOrCreate
  daemon-mount:
    Type:          HostPath (bare host directory volume)
    Path:          /var/gitpod/workspaces/05a6a443-774b-44f1-b119-91b91bc38829-daemon
    HostPathType:  DirectoryOrCreate
  gitpod-ca-certificate:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  builtin-registry-facade-cert
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoExecute op=Exists
                 node.kubernetes.io/memory-pressure:NoExecute op=Exists
                 node.kubernetes.io/network-unavailable:NoExecute op=Exists for 30s
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  11m                   default-scheduler  Successfully assigned default/imagebuild-05a6a443-774b-44f1-b119-91b91bc38829 to gitpod.example.com
  Normal   Pulling    11m                   kubelet            Pulling image "reg.gitpod.example.com:30000/remote/05a6a443-774b-44f1-b119-91b91bc38829"
  Normal   Pulled     11m                   kubelet            Successfully pulled image "reg.gitpod.example.com:30000/remote/05a6a443-774b-44f1-b119-91b91bc38829" in 657.076065ms
  Normal   Created    11m                   kubelet            Created container workspace
  Normal   Started    11m                   kubelet            Started container workspace
  Warning  Unhealthy  117s (x607 over 11m)  kubelet            Readiness probe failed: Get "http://10.42.0.33:22999/_supervisor/v1/status/content/wait/true": dial tcp 10.42.0.33:22999: connect: connection refused

```

In the container log, we can see a warning but no errors.
```bash
[root@gitpod:~]# kubectl logs imagebuild-05a6a443-774b-44f1-b119-91b91bc38829 
{"level":"info","message":"connected to parent socket","ring":2,"serviceContext":{"service":"workspacekit","version":"commit-96327582b7a1a32b69c70cfc7e32539bd3f8e20e"},"severity":"INFO","time":"2022-03-09T14:41:08Z"}
{"level":"info","message":"signaling to child process","ring":1,"serviceContext":{"service":"workspacekit","version":"commit-96327582b7a1a32b69c70cfc7e32539bd3f8e20e"},"severity":"INFO","time":"2022-03-09T14:41:08Z"}
{"level":"info","message":"awaiting seccomp fd","ring":1,"serviceContext":{"service":"workspacekit","version":"commit-96327582b7a1a32b69c70cfc7e32539bd3f8e20e"},"severity":"INFO","time":"2022-03-09T14:41:08Z"}
sent tapfd=5 for tap0
received tapfd=5
{"level":"debug", "msg": "nsexec started"}
{"level":"debug", "msg": "join mnt namespace: 5"}
{"level":"debug", "msg": "chroot: 3"}
{"level":"debug", "msg": "chcwd: 4"}
{"level":"debug", "msg": "join net namespace: 6"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"operation canceled","level":"warning","message":"syscall handler error","ring":1,"serviceContext":{"service":"workspacekit","version":"commit-96327582b7a1a32b69c70cfc7e32539bd3f8e20e"},"severity":"WARNING","time":"2022-03-09T14:41:08Z"}
{"command":"proxy","level":"info","message":"starting bob proxy on :8080","serviceContext":{"service":"bob","version":""},"severity":"INFO","time":"2022-03-09T14:41:08Z"}
```

### Steps to reproduce

not to sure, this is a summary of our setup:

- Fresh installation of k3s version v1.22.7+k3s1 (8432d7f2), with traefik disabled
- cert-manager installation, using acme-dns
- default gitpod config (adjusted domain, runtime and authproviders settings)
- self-hosted gitlab installation
- gitpod installation
- start a workspace from self-hosted gitlab

### Workspace affected

all

### Expected behavior

workspaces should spin up without any issues

**Comment by princerachit** [comment]
@kylos101 I have added this to our team inbox

**Comment by SimonHaas** [comment]
same problem.

- Fresh install of k3s
- traefik disabled
- certs obtained via certbot (not cert-manager)
- gitpod.config.yml: containerdRuntimeDir: /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
- self hosted gitlab
- gitpod/workspaces is accessible
- error in browser: Error: image build did not produce a workspace image

simon@ubuntu-proxmox:~/projects/gitpod$ kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml describe pod imagebuild
Name:         imagebuild-e620ef6f-fe05-409d-a870-d347f2d62fd4
Namespace:    default
Priority:     0
Node:         ubuntu-proxmox/192.168.155.209
Start Time:   Sat, 16 Apr 2022 18:38:37 +0200
Labels:       app=gitpod
              component=workspace
              gitpod.io/networkpolicy=default
              gpwsman=true
              headless=true
              metaID=e620ef6f-fe05-409d-a870-d347f2d62fd4
              owner=image-builder
              workspaceID=e620ef6f-fe05-409d-a870-d347f2d62fd4
              workspaceType=imagebuild
Annotations:  cluster-autoscaler.kubernetes.io/safe-to-evict: false
              container.apparmor.security.beta.kubernetes.io/workspace: unconfined
              gitpod.io/annotation.baseref: docker.io/gitpod/workspace-full@sha256:b484ad49d47bf70776de1d1333379d6b5f1d56c0a3fc1f31a24eb273ef772e3e
              gitpod.io/annotation.ref: registry.simon-gitpod.tk/workspace-images:37fa6b72cbb0b2b1459a59acbe862f31a820b2db62d740d3ac57fb93d357526a
              gitpod.io/nodeName: ubuntu-proxmox
              gitpod/admission: admit_owner_only
              gitpod/contentInitializer: CgA=
              gitpod/customTimeout: 1h0m0s
              gitpod/id: e620ef6f-fe05-409d-a870-d347f2d62fd4
              gitpod/imageSpec:
                Cl5ldS5nY3IuaW8vZ2l0cG9kLWNvcmUtZGV2L2J1aWxkL2ltYWdlLWJ1aWxkZXItbWszL2JvYjozMjg2NmFjMzU0Zjg5NjU2NmU5MGNlYjJmMzJhOWFhZjMxZWIxYjQyEl5ldS5nY3...
              gitpod/never-ready: true
              gitpod/ownerToken: mO77aQGgUTAc4hJuxw9z2NGuHA2l4lGo
              gitpod/servicePrefix: e620ef6f-fe05-409d-a870-d347f2d62fd4
              gitpod/url: https://e620ef6f-fe05-409d-a870-d347f2d62fd4.ws.simon-gitpod.tk
              prometheus.io/path: /metrics
              prometheus.io/port: 23000
              prometheus.io/scrape: true
              seccomp.security.alpha.kubernetes.io/pod: localhost/workspace_default_release-2022.03.2-rc0.0.json
Status:       Running
IP:           10.42.0.83
IPs:
  IP:  10.42.0.83
Containers:
  workspace:
    Container ID:  containerd://63fd5c68f75e9041e9fb36ada69e037ea7f989012ebbe41b9176db2b877c69be
    Image:         reg.simon-gitpod.tk:20000/remote/e620ef6f-fe05-409d-a870-d347f2d62fd4
    Image ID:      reg.simon-gitpod.tk:20000/remote/13a5aa83-4670-41ca-987c-5b6d54eb02be@sha256:f69e7a958d322124ea2b8fa13e485faa698d3313167cd07682b2e3cb459a16a6
    Port:          23000/TCP
    Host Port:     0/TCP
    Command:
      /.supervisor/workspacekit
      ring0
    State:          Running
      Started:      Sat, 16 Apr 2022 18:38:39 +0200
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      1
      memory:   2Gi
    Readiness:  http-get http://:22999/_supervisor/v1/status/content/wait/true delay=3s timeout=1s period=1s #success=1 #failure=600
    Environment:
      GITPOD_REPO_ROOT:                      /workspace
      GITPOD_CLI_APITOKEN:                   E.gwbqI4tHw-wVXfxxsxo5f6DDpoEUAI
      GITPOD_WORKSPACE_ID:                   e620ef6f-fe05-409d-a870-d347f2d62fd4
      GITPOD_INSTANCE_ID:                    e620ef6f-fe05-409d-a870-d347f2d62fd4
      GITPOD_THEIA_PORT:                     23000
      THEIA_WORKSPACE_ROOT:                  /workspace
      GITPOD_HOST:                           https://simon-gitpod.tk
      GITPOD_WORKSPACE_URL:                  https://e620ef6f-fe05-409d-a870-d347f2d62fd4.ws.simon-gitpod.tk
      GITPOD_WORKSPACE_CLUSTER_HOST:         ws.simon-gitpod.tk
      THEIA_SUPERVISOR_ENDPOINT:             :22999
      THEIA_WEBVIEW_EXTERNAL_ENDPOINT:       webview-{{hostname}}
      THEIA_MINI_BROWSER_HOST_PATTERN:       browser-{{hostname}}
      BOB_TARGET_REF:                        localhost:8080/target:latest
      BOB_BASE_REF:                          localhost:8080/base@sha256:b484ad49d47bf70776de1d1333379d6b5f1d56c0a3fc1f31a24eb273ef772e3e
      BOB_BUILD_BASE:                        false
      BOB_DOCKERFILE_PATH:                   /workspace/Dockerfile
      BOB_CONTEXT_DIR:                       /workspace
      GITPOD_TASKS:                          [{"name": "build", "init": "sudo -E /app/bob build"}]
      WORKSPACEKIT_RING2_ENCLAVE:            /app/bob proxy
      WORKSPACEKIT_BOBPROXY_BASEREF:         docker.io/gitpod/workspace-full@sha256:b484ad49d47bf70776de1d1333379d6b5f1d56c0a3fc1f31a24eb273ef772e3e
      WORKSPACEKIT_BOBPROXY_TARGETREF:       registry.simon-gitpod.tk/workspace-images:37fa6b72cbb0b2b1459a59acbe862f31a820b2db62d740d3ac57fb93d357526a
      WORKSPACEKIT_BOBPROXY_AUTH:            <set to the key '.dockerconfigjson' in secret 'builtin-registry-auth'>  Optional: false
      WORKSPACEKIT_BOBPROXY_ADDITIONALAUTH:  {}
      SUPERVISOR_DEBUG_ENABLE:               false
      GITPOD_INTERVAL:                       30000
      GITPOD_MEMORY:                         2147
      GITPOD_HEADLESS:                       true
    Mounts:
      /.workspace from daemon-mount (rw)
      /usr/local/share/ca-certificates/gitpod-ca.crt from gitpod-ca-certificate (ro,path="ca.crt")
      /workspace from vol-this-workspace (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  vol-this-workspace:
    Type:          HostPath (bare host directory volume)
    Path:          /var/gitpod/workspaces/e620ef6f-fe05-409d-a870-d347f2d62fd4
    HostPathType:  DirectoryOrCreate
  daemon-mount:
    Type:          HostPath (bare host directory volume)
    Path:          /var/gitpod/workspaces/e620ef6f-fe05-409d-a870-d347f2d62fd4-daemon
    HostPathType:  DirectoryOrCreate
  gitpod-ca-certificate:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  builtin-registry-facade-cert
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoExecute op=Exists
                 node.kubernetes.io/memory-pressure:NoExecute op=Exists
                 node.kubernetes.io/network-unavailable:NoExecute op=Exists for 30s
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age              From               Message
  ----     ------     ----             ----               -------
  Normal   Scheduled  10s              default-scheduler  Successfully assigned default/imagebuild-e620ef6f-fe05-409d-a870-d347f2d62fd4 to ubuntu-proxmox
  Normal   Pulling    10s              kubelet            Pulling image "reg.simon-gitpod.tk:20000/remote/e620ef6f-fe05-409d-a870-d347f2d62fd4"
  Normal   Pulled     9s               kubelet            Successfully pulled image "reg.simon-gitpod.tk:20000/remote/e620ef6f-fe05-409d-a870-d347f2d62fd4" in 1.309999247s
  Normal   Created    9s               kubelet            Created container workspace
  Normal   Started    9s               kubelet            Started container workspace
  Warning  Unhealthy  1s (x7 over 6s)  kubelet            Readiness probe failed: Get "http://10.42.0.83:22999/_supervisor/v1/status/content/wait/true": dial tcp 10.42.0.83:22999: connect: connection refused

**Comment by corneliusludmann** [comment]
@rbicker / @SimonHaas, in case it is still relevant for you: Could you please try to remove the network policies of blobserve?
```
kubectl delete networkpolicy blobserve
```

**Comment by SimonHaas** [comment]
Problem still there. Removing the network policies did not help.

I will try the new web-installer and give feedback later this week.

**Comment by corneliusludmann** [comment]
Are you using calico as CNI? See also: https://www.gitpod.io/docs/self-hosted/latest/cluster-set-up/on-k3s
