### ISSUE TITLE
Accessibility Statement

### ISSUE THREAD

**Issue by jhulance** [gitpod-io/gitpod#8695]
## Describe the behaviour you'd like
Could we have an "Accessibility Statement" on the main Gitpod.io pages, including for self-hosted?

## Describe alternatives you've considered
Have searched and checked the web site, but not found anything.

## Additional context
WCAG 2.0 maybe? https://www.w3.org/WAI/standards-guidelines/wcag/

**Comment by gtsiolis** [comment]
Hey @jhulance! Are you referring to the dashboard (`gitpod.io`) or the website (`www.gitpod.io`)?

**Comment by jhulance** [comment]
Ideally for all the main Gitpod.io screens that a programmer would interact with day-to-day, so maybe not so much the web site, but the workspace/settings/admin pages as well as the main editor screens.

**Comment by gtsiolis** [comment]
@jhulance For the dashboard, we generally aim for `WCAG AA` for all components or pages, see example issue in https://github.com/gitpod-io/gitpod/issues/7161. However, so far we've been doing this on a component level and per case. Long-term, we will probably run accessibility conformance reports to keep track of any issues related to accessibility. 💡 

In the meantime, if you notice any accessibility issue that you are running into, I'd encourage you to [open an issue](https://github.com/gitpod-io/gitpod/issues/new/choose) about this while narrowing down the scope of the issue and potential include any action items that could help resolving the issue if possible. 💭 

I'll close this in favor of #3717, which is still very vague to tackle but also contains some already existing accessibility issues. Also, let me re-post the following from https://github.com/gitpod-io/gitpod/issues/3717#issuecomment-812142935:

> We're approaching the development of the dashboard using an MVC (minimum viable change) approach and we plan to tackle these in future iterations. Ideally, we should split this issue into concrete smaller issues that tackle most of the points raised here in small batches focusing on specific product areas, so that code reviews are also faster and more efficient.

🍊 🍊 🍊 🍊 

For the website, I know there are already a few open issues[[1](https://github.com/gitpod-io/website/issues?q=is%3Aissue+is%3Aopen+accessibility)] related to accessibility but I'd suggest to open any issues related to the website to the relevant repository `[gitpod-io/website](https://github.com/gitpod-io/website)`. 🏓
