### ISSUE TITLE
Add extension block to YAML config

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#870]
Add block like this:
```yaml
extensions:
  - microsoft.vscode_python
  - some_other_extension_for_vscode
```
In `.gitpod.yml` so all the extensions you want get autoinstalled

**Comment by JesterOrNot** [comment]
microsoft.vscode_python
is preinstalled in gitpod

**Comment by RDIL** [comment]
I know it was just an example

**Comment by svenefftinge** [comment]
@RDIL the extensions already supports multiple entries. The file will be updated automatically if you add more than one extension. 
Example: https://github.com/meysholdt/spring-petclinic/blob/master/.gitpod.yml#L25
Do I missunderstand something here?

**Comment by RDIL** [comment]
Oh huh, I didn't realize this block already existed.
