### ISSUE TITLE
Accessing server API at gitpod.io from within workspaces might fail sometimes

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8703]
### Bug description

Sometimes, when you start a workspace ~~around the same time as a Gitpod WebApp deployment (typically on Tuesdays and Thursdays around ~08:30 UTC)~~, it can get into a bad state.

Symptoms:
- The IDE theme is always Light (quite noticeable if you normally use Dark theme)
- The Git credential-helper doesn't work (e.g. if you try to push to a new branch, it will ask you for username and password)
- Some Gitpod features are missing (e.g. if you look for `Gitpod: Stop Workspace` in `F1`, you won't find it)

The only solution is to stop the workspace (e.g. from your workspaces list) and restart it.

<img width="1439" alt="Screenshot 2022-03-10 at 09 29 12" src="https://user-images.githubusercontent.com/599268/157626614-ca0ba00e-97df-4ef1-a4fd-3791e6ad6cca.png">

### Steps to reproduce

1. Start a workspace ~~on a Tuesday or Thursday around ~08:30 UTC~~
2. Try to push something to a branch
3. It will ask for username and password

### Workspace affected

gitpodio-gitpod-ykfphcb8pwd

### Expected behavior

1. The workspace should not land into such a bad state or require a restart

**Comment by jankeromnes** [comment]
Copy/pasting some findings from [this Slack thread](https://gitpod.slack.com/archives/C01KGM9BH54/p1646727357113229) (internal):

> It seems that supevisor cannot access github token from server.

> Uh, it seems that workspace could not establish connection to server at all:
> <img width="1549" alt="Screenshot 2022-03-08 at 09 21 33" src="https://user-images.githubusercontent.com/599268/157627282-5f378ab8-3166-4b42-9a02-c3426fd475db.png">

> from logs server does not want to auth VS Code (actually everything in workspace) although it granted token

> > Is it because the traffic is going to the incorrect cluster?
> It mainly happened between the two spikes on the left: First is EU rollout, 2nd US. between those, db-sync is offline. Could be this is a combination of that plus the traffic being redirected to another cluster.

**Comment by jankeromnes** [comment]
Scheduling for Team WebApp due to [this request](https://gitpod.slack.com/archives/C01KGM9BH54/p1646903129372039?thread_ts=1646727357.113229&cid=C01KGM9BH54):

> It would be cool if someone can investigate before next webapp deployment, looks like something leads to inconsistent DB state which was not the case a week ago

**Comment by geropl** [comment]
I removed the workspace & IDe labels to avoid noise/cross chat. IMO we need to investigate first, and then maybe derive sth for IDE / workspace.

Also, moving this into "needs design", because it's not actionable, yet.

**Comment by jankeromnes** [comment]
Thanks Gero, I agree. 👍

> Also, moving this into "needs design", because it's not actionable, yet.

Interesting 💡 maybe we need a sort of "needs investigation" category too (or we could rename "needs design" -- not sure about this) 🤔 💭

**Comment by AlexTugarev** [comment]
I'm curious, how the reconnection behavior actually looks like for the workspace/supervisor and how the IDE is supposed to re-request data which might have failed due to rollout of new server instances.

**Comment by geropl** [comment]
@AlexTugarev The process is:
 - startWorkspace (instance)
   - create token 1
   - create OTS 1
 - wsManager.startWorkspace
 - ...
 - dashboard:
 - fetch OTS 1 from server, now holding a GP token 1    <-- @akosyakov reported that he saw frontend actually had a token
 - ... <-- what happens here???
 - dashboard tries to execute API call using GP token 1: :boom: 

Is there any way you could think of that we delete token 1 before it is actually retrieved? :thinking: 

**Hypothesis 1**: Maybe be creating another token, and deleting the old one? What could trigger this?

**Hypothesis 2**: During rollout the GLB decides that new connection go the other (US) cluster, where the token is not (yet) properly synced to. (do we retry here?)

**Comment by jankeromnes** [comment]
Actually, this seems to happen even without webapp deployments.

I just hit it this morning, while opening https://github.com/gitpod-io/gitpod/pull/8757 in Gitpod:

<img width="1439" alt="Screenshot 2022-03-14 at 09 51 46" src="https://user-images.githubusercontent.com/599268/158137635-51a96d39-793f-483c-a936-307eb1d94495.png">

- Light theme (expected: Dark)
- Broken Git authentication
- No `F1 > Gitpod: Stop Workspace` command

Will update the title & description.

**Comment by akosyakov** [comment]
I think we should put `priority: highest (user impact)`, deployments consistently breaking workspaces. It happened again: https://gitpod.slack.com/archives/C01KGM9BH54/p1647519959995009

**Comment by geropl** [comment]
From[ internal discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1647519959995009): 

Queries:
 - workspace logs: https://console.cloud.google.com/logs/query;query=resource.labels.container_name%3D%22workspace%22%0Aresource.labels.pod_name%3D%22ws-24799694-6c62-49ab-8128-bd21a9f0f03f%22;cursorTimestamp=2022-03-17T12:20:48Z?project=workspace-clusters&query=%0A
 - server logs: https://console.cloud.google.com/logs/query;cursorTimestamp=2022-03-17T12:20:48Z;query=resource.labels.container_name%3D%22workspace%22%0Aresource.labels.pod_name%3D%22ws-24799694-6c62-49ab-8128-bd21a9f0f03f%22%0Atimestamp%3D%222022-03-17T12:20:48.289878059Z%22%0AinsertId%3D%221ttl99sgbfmvb2sy%22?project=workspace-clusters
 - 
 
 @AlexTugarev metioned:
> also, could it be there are 2 gitpod tokens stored? I’m not familiar with the bearer token auth in the code, but it calls getOne on the user~token join, so if there would be more tokens stored in the db, that could also pick one which is not accepted.

>  from git history it looks like you could answer this: where is the GitpodTokenType.API_AUTH_TOKEN which is required/checked in the bearer auth actually written? I cannot find any places where this is written to db.

**Comment by AlexTugarev** [comment]
@geropl and I did review the auth flow of supervisor and do now assume that it very well might be an issue with server pods being not in-sync. the problem might be, when we start a workspace from a server in one cluster, but the supervisor's requests are handled by server in the other cluster, the tokens in the DB might not be sync'd yet. 

with https://github.com/gitpod-io/gitpod/pull/9130 (merged) we should be able to verify the assumption.

**Comment by jankeromnes** [comment]
This bug just happened to me again right now:

https://gitpodio-gitpod-4l1i0gza3k4.ws-eu38xl.gitpod.io/

<img width="1440" alt="Screenshot 2022-04-06 at 15 13 47" src="https://user-images.githubusercontent.com/599268/161983395-c82300b5-d911-4e83-a3cd-9c965b578252.png">

**Comment by svenefftinge** [comment]
Regarding #9130 the [logs](https://cloudlogging.app.goo.gl/XMh1iCjHywKqpwpr8) show that the region and the server location seem to match, so probably not a db-sync issue.

**Comment by geropl** [comment]
I looked at a single failing case, starting from the log message ["jsonrpc2: protocol error: reconnecting-ws: bad handshake: code 401"](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-20T15:35:30.831976036Z;query=%22protocol%20error:%20reconnecting-ws:%20bad%20handshake:%20code%20401%22%0A-%22prebuild%22%0Aresource.labels.container_name%3D%22workspace%22%0Atimestamp%3D%222022-04-20T15:35:30.831976036Z%22%0AinsertId%3D%224wcg3d2rfatyee16%22;summaryFields=jsonPayload%252FworkspaceId,resource%252Flabels%252Fpod_name:false:32:beginning:false;timeRange=PT2H?project=workspace-clusters). The respective workspace instance is still running, but the user has no token for that workspace instance, in _any_ database.

**Comment by kylos101** [comment]
I see that @sagor999 is looking at this now, he's definitely the right person. :+1: Do you think we're emitting status many times, while exponentially backing off, and that is causing this behavior?

**Comment by sagor999** [comment]
I think this might be due to retry logic. :thinking: 
Reason for thinking so:
In logs provided, I see few updates with this message: `pod is pending` 
When pod is pending and cannot get scheduled within 5 seconds, ws-manager will delete that pod and try to create a new one.
When it deletes the pod, it also removes the finalizer first. 
If at the same time call is made to `extractStatusFromPod`:
https://github.com/gitpod-io/gitpod/blob/4d48ccb997555c73150bb8fbccc80f824ca23b3d/components/ws-manager/pkg/manager/status.go#L329-L351
it will check if pod is being delete and if finalizer is removed, then it will update workspace status to stopped.

Back in ws-manager retry logic, it will now create a new pod, and subsequent call to `extractStatusFromPod` will now update the status back to pending:
https://github.com/gitpod-io/gitpod/blob/4d48ccb997555c73150bb8fbccc80f824ca23b3d/components/ws-manager/pkg/manager/status.go#L409

Let me think how to better fix this. In theory we would want to short circuit `extractStatusFromPod` if ws-manager is still attempting to create the pod... without introducing some other odd behavior. :smile:

**Comment by csweichel** [comment]
We could add an annotation when we create the pod and remove it once we're out of the retry logic. This annotation would inform the status updates we send out from ws-manager.

**Comment by sagor999** [comment]
That's what I was thinking as well ^ @csweichel 
I think it is fairly safe, with only exception is that if for some reason we fail to update the pod to remove that annotation after. But I guess we be very loud about that error if it happens.

**Comment by lucasvaltl** [comment]
fwiw, I also just ran into this issue within this workspace: https://gitpodio-website-kfjstnnof79.ws-eu34.gitpod.io/

My IDE theme is still dark though, contrary to what was said in the original issue description:
> The IDE theme is always Light (quite noticeable if you normally use Dark theme)

**Comment by lucasvaltl** [comment]
Ran into it again (today @11:02 GMT+2) here: https://gitpodio-website-8vw6v27o15p.ws-eu41.gitpod.io/ 

FYI @sagor999 

--> This time it switched my theme to white 🤔

**Comment by sagor999** [comment]
@lucasvaltl it is deployed with gen42 clusters. Yours was still on gen41.
