### ISSUE TITLE
[dashboard] Make loading sequence smoother

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#8710]
Since recently, the start workspace screen is showing a "started" state before forwarding to the IDE. 
This seems very busy and unnecessary. Would be cool to avoid that flickering.

**Comment by geropl** [comment]
@svenefftinge  There already is an issue for this: https://github.com/gitpod-io/gitpod/issues/8226
IMO it's more an IDE thing, as it also involves how we time fetching of options, and the team owns the supervisor frontend. :+1:
