### ISSUE TITLE
Create automated way of issuing Replicated licenses

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#8717]
In order to issue a Replicated license, you must use the Replicated CLI to generate the license.

## Community license

Assuming that the [Replicated feature request](https://gitpod.slack.com/archives/C02SWJ49JQ2/p1646414862345129) to allow for a license to be changed via the KOTS UI is accepted, we can issue a single community license to allow for anonymous use of Replicated.

 - Create a license for `stable`, `beta` and `unstable` - there is an appetite in the community to track the bleeding-edge releases.
 - Make the [domain optional](https://github.com/gitpod-io/gitpod/issues/8410) and keep this empty
 - Publish this license as part of the installation documentation

## Professional license

 - Create a license for `stable` only. Other channels can be added later if necessary.
 - Make the domain required
 - Make the number seats required
 - Create a payment gateway - @jankeromnes has made a [good start on an RFC for this](https://www.notion.so/gitpod/Orthogonal-replaceable-request-based-billing-component-c3e5b775ee5d427aba1839548e168466)
 - Create a license delivery mechanism. This would probably need to allow re-downloading for when users cannot find their license.

This license generator makes sense to be done as a serverless component. Replicated does not offer access to their API via the web, but does so via their CLI tool. As this would be our first (to my knowledge) serverless component, this would require some architectural thought.

How the license would be delivered would require some thought as well - downloading or emailing are the two basic options. Again, this would need doing from the Replicated CLI.

One question that needs answering is how to add values for the license fields (domain, levelId and seats) to the license via the CLI as it's not documented. I have [raised this with Replicated](https://gitpod.slack.com/archives/C02SWJ49JQ2/p1646919522993539).

**Comment by MrSimonEmms** [comment]
According to Replicated, Replicated provide a download portal for generating a custom URL for the customer to download their license. This will give them the license file, binaries (for airgap) and command for installation.

Replicated to provide documentation for this in due course

**Comment by lucasvaltl** [comment]
This is unlikely to be done soon - hence will close this for now.
