### ISSUE TITLE
IDE crashes whe searching for something

### ISSUE THREAD

**Issue by PostPollux** [gitpod-io/gitpod#872]
**Describe the bug**
When I use the search on the left and search for example for "test" the IDE crashes/disconnects (I get a yellow bar on the bottom instead of blue). The services exposed through the ports are still usable, but the IDE is not.
This is not the case with every gitpod workspace. But it is the case with the following two: 
- https://gitpod.io#https://github.com/PostPollux/Human-Connection/tree/gitpod_support
- https://gitpod.io/#https://github.com/zadam/trilium

**To Reproduce**
- start one of the following workspace: 
   - https://gitpod.io#https://github.com/PostPollux/Human-Connection/tree/gitpod_support
   - https://gitpod.io/#https://github.com/zadam/trilium
- go to search on the left
- now try to search for "test" or something else

**Expected behavior**
Search is working... no disconnecting

**Additional Information**
After a while I get the following message:
![gitpodbug](https://user-images.githubusercontent.com/9008901/67622224-97ba8e00-f818-11e9-9e48-3f5322fd3410.png)

**Comment by JesterOrNot** [comment]
What were you doing when this happened? if your wifi is unstable the WebSockets can crash see #789 could this be the case here?

**Comment by PostPollux** [comment]
Thanks for the tip. I just tried it again with a cable connection (150 Mbit) and it was the same. So I guess unstable Wifi is not the problem here.

**Comment by PostPollux** [comment]
It also happens with this environment (tested with Firefox and with Brave Browser):
https://gitpod.io/#https://github.com/zadam/trilium

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/68134594-f900f200-fee7-11e9-9ac2-2e9686f53345.png)
I was able to reproduce this issue

**Comment by 32leaves** [comment]
could be related to (and fixed by #902)

**Comment by PostPollux** [comment]
just tested it again right now. Still the same...

**Comment by svenefftinge** [comment]
deployed
