### ISSUE TITLE
Vetur extension causes error for suggestions

### ISSUE THREAD

**Issue by ArSn** [gitpod-io/gitpod#873]
**Describe the bug**
IDE interface shows the following error message:
![image](https://user-images.githubusercontent.com/2803693/67623350-4e703b80-f824-11e9-9c7a-f870b53ad5bb.png)

This also appears to be causing the suggestions feature of vetur not to work. (I am aware extensions are still in beta but after all reporting bugs on that is what a beta is for, right? 😉)

**To Reproduce**
1. Install Vetor extension https://marketplace.visualstudio.com/items?itemName=octref.vetur#overview
2. Reload your browser tab where the IDE is open and you will see the error message
3. Scaffolding does not work, should work when typing "vue" in a new `.vue` file and hitting enter.

**Expected behavior**
- No error should be shown
- Scaffolding / suggestions should work

**Comment by JesterOrNot** [comment]
Hello, @ArSn taking a look at the extension's page it seems that it depends on https://github.com/vuejs/vetur/tree/master/server have you installed it?

**Comment by ArSn** [comment]
@JesterOrNot I have not. How do you conclude that one has to install that in order for Vetur to work? I am following a guide from the folks over at Vue Mastery and at least with the offline version of VScode this does not seem to be true. I rather understand that it is using vue-language-server "under the hood".

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/67626692-9a1ae900-f814-11e9-95c8-e0c8d3d838f4.png)
it says Vue tooling for VS Code, powered by vue-language-server.

Doc: https://vuejs.github.io/vetur

Try it out with Veturpack!

**Comment by svenefftinge** [comment]
The error message is pretty likely a bug in the extension support of Theia. Thanks for reporting we will look into it.

**Comment by Sandared** [comment]
Any update on this issue yet? Unfortunately I neither couldn't get vetur to work with my project (see https://community.gitpod.io/t/vetur-extension-not-working/1960/2)

**Comment by svenefftinge** [comment]
Fixed in staging

**Comment by Sandared** [comment]
Awesome :) any time estimate when it will be available in production?

Sven Efftinge <notifications@github.com> schrieb am Di., 13. Okt. 2020,
16:01:

**Comment by jankeromnes** [comment]
The fix was deployed to production this morning. @ArSn @Sandared could you please kindly confirm that Vetur works as expected now?

**Comment by Sandared** [comment]
works perfectly :) Thank you! 
Awesome work. (again ;) )
