### ISSUE TITLE
GitHub API: check repository for null

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8733]
### Bug description

![image](https://user-images.githubusercontent.com/1272076/157752293-db1e03ca-1b27-43a5-ad78-9974aeeafe53.png)

### Steps to reproduce

Delete a branch in a PR.
Restore it.
Try opening this using the Gitpod browser extension.

[Originally discovered here](https://github.com/gitpod-io/workspace-images/pull/564)

### Workspace affected

n/a

### Expected behavior

Should be able to open Gitpod from a branch which was deleted and is now restored.

### Example repository

https://github.com/gitpod-io/workspace-images/pull/564

**Comment by kylos101** [comment]
I think it was just taking Github a long time to restore? Works now, ~26 minutes later.

**Comment by geropl** [comment]
@AlexTugarev I faintly recall you fixed a similar error in the past? What was it exactly?
@jankeromnes Could this have been re-introduced by the GHE changes? :thinking:

**Comment by jankeromnes** [comment]
Interesting, this looks like https://github.com/gitpod-io/gitpod/issues/3659, which we had fixed with https://github.com/gitpod-io/gitpod/pull/3869.

I wonder why it came back. Will have a quick look at where we possibly try to read `.repository` of `null`.

**Comment by jankeromnes** [comment]
> It's worth changing to check `result?.data?.repository` for `null`.

Aha, good idea! 🎯

> Also, it seems like GH API doesn't consistently return same in such cases. If you try again on the PR mentioned above, it's reports as expected.

Yes, as @kylos101 [reported](https://github.com/gitpod-io/gitpod/issues/8733#issuecomment-1064515081), this problem was only temporary:

> I think it was just taking Github a long time to restore? Works now, ~26 minutes later.
