### ISSUE TITLE
Automatically use newer github security practices

### ISSUE THREAD

**Issue by Milo123459** [gitpod-io/gitpod#8734]
## Describe the behaviour you'd like

Currently the git committer email address is the primary email. Some people (like I) have a setting enabled that means that you have to commit from a special no-reply GitHub email.

## Describe alternatives you've considered

Setting variables manually, but it's quite annoying.

**Comment by axonasif** [comment]
Hey @Milo123459, how are you setting the variables?

**Comment by Milo123459** [comment]
Changing GIT_COMMITTER_EMAIL

**Comment by geropl** [comment]
Thanks @Milo123459 for reporting. Could you elaborate what that settings is called? To "complete" this features request, and make it searchable for future reference? :pray: 

I have to admit we won't start working on this soon, though, as it does not overlap with our current priorities. :confused:

**Comment by geropl** [comment]
Closing because
 a) not overlapping with our current priorities
 b) there is a workaround.

Community contributions are always welcome, of course! :slightly_smiling_face:

**Comment by Milo123459** [comment]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/50248166/157826624-47b1d7bc-7947-4247-bc7e-20c551299f60.png">

Settings -> Accces -> Emails
