### ISSUE TITLE
Always-on workspaces

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#874]
For people with unlimited add the option for an "always-on" workspace that wouldn't timeout until the user said so maybe some toggle in the dashboard

**Comment by svenefftinge** [comment]
The 'unlimited' only works business-wise because of the timeout, but we are going to add a feature to increase the timeout to a couple of hours. This is only to remove the stress it a possible timeout could cause while doing other things, not to make Gitpod a hosting solution.

**Comment by JesterOrNot** [comment]
Ok cool

**Comment by Sal4cite** [comment]
How Can I Run Make My Codespace Nerver STOP ?

**Comment by axonasif** [comment]
@Sal4cite that's not possible but you can keep a workspace running upto 24 hours, for that you need to subscribe to PAYG.
