### ISSUE TITLE
We might reach the docker pull rate limit when we use individual clusters for preview-environments

### ISSUE THREAD

**Issue by wulfthimm** [gitpod-io/gitpod#8746]
### Bug description

During loadtests for our preview-environments on individual VMs we reached the rate limit to pull images from the docker registry [1]. This might happen if the number of developers grow. To prevent this from happening we could use a mirror that caches the docker images. k3s is already capable of using a mirror by setting it up in `/etc/rancher/k3s/registries.yaml` [[2](https://rancher.com/docs/k3s/latest/en/installation/private-registry/#with-tls)].
We can either create our own registry that might be useful in the future but would block progressing on this topic or we can use an already present public mirror like the one Google offers [[3](https://cloud.google.com/container-registry/docs/pulling-cached-images)]. Quick tests have show that some images are present to download but others are not. This makes the GCP mirror unreliable and we have to test if does work for the images we want to pull which is not practical.
```bash
gitpod /workspace/gitpod (wth/rancher-mirror) $ sudo docker pull mirror.gcr.io/library/ubuntu:xenial
xenial: Pulling from library/ubuntu
58690f9b18fc: Pull complete 
b51569e7c507: Pull complete 
da8ef40b9eca: Pull complete 
fb15d46c38dc: Pull complete 
Digest: sha256:0f71fa8d4d2d4292c3c617fda2b36f6dabe5c8b6e34c3dc5b0d17d4e704bd39c
Status: Downloaded newer image for mirror.gcr.io/library/ubuntu:xenial
mirror.gcr.io/library/ubuntu:xenial
gitpod /workspace/gitpod (wth/rancher-mirror) $ sudo docker pull mirror.gcr.io/library/ubuntu:impish
Error response from daemon: manifest for mirror.gcr.io/library/ubuntu:impish not found: manifest unknown: Failed to fetch "impish" from request "/v2/library/ubuntu/manifests/impish".
```

### Steps to reproduce

1. Open a new workspace
2. run `sudo docker pull mirror.gcr.io/library/ubuntu:xenial`. => download succeeds
3. run `sudo docker pull mirror.gcr.io/library/ubuntu:impish`. => download fails

### Expected behavior

We should not run into rate limits during loadtests for preview-environments on individual k3s-clusters.

**Comment by wulfthimm** [comment]
I did another test configuring the registry mirror in the docker daemon config [[1](https://docs.docker.com/registry/recipes/mirror/)] and tested the download of the images same images which does work. So I guess that the image cannot be found on the mirror and therefore has been downloaded directly from the docker hub [[2](https://cloud.google.com/container-registry/docs/pulling-cached-images)]. This will give us no benefit and we definitively should use our own pull-through cache.

**Comment by wulfthimm** [comment]
As we already discussed running an own registry on Harvester I suggest that I start working on it.
We could install either the docker-registry we already use in Gitpod which is maintained by a private person or we can use harbor as Arthur suggested which has support from bitnami. I am in favor of harbor because of the official support.
I am setting the `pending clarification` label until a decision is made.

**Comment by meysholdt** [comment]
hi Wulf, [in the spirit of an RFC](https://gitpod.slack.com/archives/C01KGM9EBD4/p1646993708732609?thread_ts=1646988282.490179&cid=C01KGM9EBD4), can you list what requirements the docker registry needs to fulfill and why a registry candidate is the best choice?

**Comment by wulfthimm** [comment]
https://github.com/gitpod-io/gitpod/issues/8724

**Comment by wulfthimm** [comment]
I added the `blocked` label until we have a decision on how to progress (see the [RFC](https://www.notion.so/gitpod/Using-a-docker-registry-on-Harvester-62d0308b1e4f4cbc8df77eb1c12c27ec) for more information).

**Comment by meysholdt** [comment]
fixed via https://github.com/gitpod-io/gitpod/pull/9671
