### ISSUE TITLE
Avatar access restriction causes overlaid text in project branch list.

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#8755]
- Connect gitpod.io to a self-hosted GitHub enterprise
- Create a project
- The branch list shows overlaid text where there are normally user avatars

![Screenshot 2022-03-11 at 13 41 23](https://user-images.githubusercontent.com/849592/157879816-1183e81d-0e5a-4674-9d07-d61b72c48c79.png)

**Comment by jldec** [comment]
The image GET on the avatar url returns a 302 redirecting to the the login screen.
The CSS should be fixed to set a max size on the avatar width.

**Comment by gtsiolis** [comment]
Nice catch, @jldec! ⚾

**Comment by jankeromnes** [comment]
Will take a look today 😁
