### ISSUE TITLE
ws-manager CA used for generating mTLS secrets needs to be cycled by April, 1st

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#8762]
The certificate we use as CA for generating our **cluster internal certificates will expire on 1st of April, 2022**.

A derivative (in-cluster secrets are called `ws-manager-tls` and `ws-manager-client-tls`) is used most prominently by `ws-manager` and all it's clients for mTLS on the `ws-manger` interface. This is important, because that's what we configure in the `DBWorkspaceCluster` database!

Steps we need to do before 1st of April, ideally within next week to not interfere with the Offsite:
 - [x] webapp: verify that we do not rely on those for (non-local) connections to `ws-manager`
 - [x] platform: create a new certificate, and place that in Google Secret manager
   - :warning: we must not run a TF script on the app clusters after this!
 - [x] workspace: deploy a new set of WorkspaceClusters, and register those in the DB
 - [x] workspace: shift workspace traffic to the new clusters
 - [x] platform: run TF scripts to update the CA in app clusters
 - [x] webapp: re-deploy webapp with new CA (incl. workspace components in app cluster)

@kylos101 For the new workspace cluster creation
@meysholdt @mads-hartmann for being aware of this, and the platform parts
@jldec @JanKoehnlein For team WebApp

@wulfthimm Thx for making us aware again! :pray:

**Comment by geropl** [comment]
Besides doing the actual migration we should also think about how to better handle this in the future.

**Comment by wulfthimm** [comment]
The secret in GCP which contains the certificate can be found at https://console.cloud.google.com/security/secret-manager/secret/gitpod-ws-manager-ca/versions?project=gitpod-191109

**Comment by wulfthimm** [comment]
The GCP secret is read in the Terraform [module gitpod](https://github.com/gitpod-io/ops/blob/8d205bf56c6cfccc650131e711cd80d1b3126177/terraform/modules/gitpod/main.tf#L11) which part of the [module gitpod-meta](https://github.com/gitpod-io/ops/blob/8d205bf56c6cfccc650131e711cd80d1b3126177/terraform/modules/gitpod-meta/main.tf#L136).

**Comment by wulfthimm** [comment]
I have not tested the behaviour changing the root-certificate in a `ca-issuer`. We have to make sure that the certificates that are generated by the `ca-issuer` updated after the exchange.
The `certificate` resources for certmanager are:
- messagebus-certificates-secret-gitpod
- ws-daemon-tls
- ws-manager-client-tls
- ws-manager-tls
After we verified that the newly created certificates are updated we can restart the services.

For clarification:
The ca-issuer uses the root-certificate, the certificate-resources request new certificates from the ca-issuer and the actual certificates are stored as secrets.

References:
- ca-issuer: https://cert-manager.io/docs/configuration/ca/
- certificate: https://cert-manager.io/docs/usage/certificate/

**Comment by wulfthimm** [comment]
@geropl Do we have a script to generate the root-certificate?

**Comment by geropl** [comment]
> I have not tested the behaviour changing the root-certificate in a ca-issuer

Yes, this is true. But also only relevant for the WebApp deployment. :+1:

**Comment by geropl** [comment]
Regarding

> Besides doing the actual migration we should also think about how to better handle this in the future.

In the future, we no longer require the certificate be shared between app and ws clusters because no longer statically configured ws-manager-bridge using the app-cluster client certs (assuming those validate against the ws-cluster cert chain as we did in the past).
Instead, we're using gpctl to configure workspace clusters at runtime. That automatically fetches the client certs from the ws cluster and puts them into the DB.

**Comment by wulfthimm** [comment]
I created a How-To which describes the process creating a new certificate. This will be valid for 10 years as Moritz suggested. Please make comments if something unclear or I missed certificate extensions that need to be added.

https://www.notion.so/gitpod/How-to-generate-gitpod-ws-manager-ca-certificates-267e7af2532b4f6490e9ad9ac4272c98

**Comment by wulfthimm** [comment]
I updated the certificate for gitpod-staging ([ref](https://gitpod.slack.com/archives/C021ENP4CEN/p1647270809273209)).

**Comment by wulfthimm** [comment]
I have updated to certificate for production. ([ref](https://gitpod.slack.com/archives/C021LT6GUJG/p1647274829845859)).

**Comment by kylos101** [comment]
Hi @geropl , once [this PR](https://github.com/gitpod-io/gitpod/pull/8777) is merged, we'll try another deploy of `workspace-clusters`. As a heads up, we could not ship today as originally planned.

CC: @aledbf

**Comment by geropl** [comment]
@kylos101 thx for the heads-up! 

Regardless of whether we do get a positive signal from you/Team Workspace today, we'll deploy webapp with the new certificate tomorrow morning. This works because we learned that [we're actually already independent](https://github.com/gitpod-io/gitpod/issues/8762#issuecomment-1065273846) (except for using the same source of truth in Google Secret manager). :+1:

**Comment by aledbf** [comment]
@geropl we deployed eu38 and us38 using the latest version of the certificate in secret manager

**Comment by wulfthimm** [comment]
The new certificates are not deployed to the clusters yet. I would like to test the certificate renewal process on staging by applying the Terraform changes which will copy the certificate to the clusters and monitor if the ca-issuer that manages the issuing process will update the leaf certificates automatically or if we need to trigger id manually.

**Comment by wulfthimm** [comment]
I am waiting for a confirmation from the WebApp Team to test the renewal process on staging ([1](https://gitpod.slack.com/archives/C02EN94AEPL/p1647507926933889)].

**Comment by wulfthimm** [comment]
The deployment of the application clusters was canceled this morning [[1](https://gitpod.slack.com/archives/C02EN94AEPL/p1647503231997419)].

**Comment by geropl** [comment]
Quick summary:
 - **staging**: has been test-deployed, and everything worked as expected. :tada: Thx @wulfthimm :pray: 
 - **production**: we delayed the actual roll-out until Mo, 28.03. (when we're back from the offsite). The exact plan is:
  1. run terraform to copy the certificate into the cluster
     1. make sure it actually re-generates all certificates by setting a renewBy date
  1. rollout messagebus
     1. `kubectl rollout restart deployment server`
     1. `kubectl rollout restart deployment messagebus`
     1. `kubectl rollout restart deployment ws-manager-bridge`
  2. rollout image-builder, and all local workspace components
     1. `kubectl rollout restart deployment ws-manager image-builder-mk3 ws-proxy`
     2. `kubectl rollout restart ds ws-daemon registr-facade`

**Comment by geropl** [comment]
Rolled out.
