### ISSUE TITLE
[dashboard] Remove action option to re-run prebuild from prebuild list view

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#8765]
## Is your feature request related to a problem? Please describe

We do not allow re-running prebuilds from older commits. This simplifies the UI and directs the user to run a prebuild for the branch list view.

When a user clicks "new prebuild" on the branch view, they should be redirected to a prebuild detail view with logs and status.

## Additional context
Internal links [[1](https://gitpod.slack.com/archives/C02EN94AEPL/p1647013743963169)] and [[2](https://www.notion.so/gitpod/WebApp-prebuild-sync-Mar-14-2022-7369d7c7807f44ac820011765b5b0c29#9f09e593f99a4b0b9ded0106fa7ab122)]

**Comment by easyCZ** [comment]
CC @laushinka

**Comment by laushinka** [comment]
After discussion with @jldec:
- Keep existing behaviour
- If we do not want to run an existing PB, tell the user
- If we do want to run something, redirect to the logs
