### ISSUE TITLE
Using Gatsby CLI

### ISSUE THREAD

**Issue by zzrez** [gitpod-io/gitpod#877]
I am testing out Gitpod, after doing most development (React & Gatsby) locally in VS Code. Each time I startup a container with a Gatsby starter already in place, I get the bash message "gatsby: command not found" after I enter "gatsby develop". So it looks like each time I must first enter "npm i -g gatsby-cli". Is this correct? (I tried previously to install locally but the command was still not found). Thanks.

**Comment by svenefftinge** [comment]
Globally installed npm packages are not preserved between workspace starts. You can either add a `before` task into your `.gitpod.yml` file or you add it to a docker file.
Creating a .gitpod.yml and docker file can be done by running `gp init` in the terminal.
