### ISSUE TITLE
Using Tailscale Exit Node Crashes Workspace

### ISSUE THREAD

**Issue by johannesdrescher** [gitpod-io/gitpod#8778]
### Bug description

I'd like to use a Tailscale [exit node](https://tailscale.com/kb/1103/exit-nodes/) from Gitpod. 

I used the [network bridging](https://www.gitpod.io/docs/configure/tailscale) instructions and added a `--exit-node=<exit-node-ip>` flag. 

Without the flag (original instructions from docs), it connects to my Tailnet as expected. But with the flag, the workspace freezes and disconnects shortly after.

### Steps to reproduce

- Open a workspace (with default image)
- Run `sudo tailscaled`
- Open a new terminal
- Run `sudo tailscale up --exit-node=<exit-node-ip>`
- Follow link and authorize
- Workspace is now frozen

### Expected behavior

After authorization, the `tailscale up` command prints `Success.`.

**Comment by johannesdrescher** [comment]
Hi @atduarte! I do believe changing this behavior would be useful. It would allow users to change their outbound IP within Gitpod.

My use case is accessing services which are protected with an IP whitelist (e.g. a GKE cluster with the [authorized networks](https://cloud.google.com/kubernetes-engine/docs/how-to/authorized-networks) feature enabled). It is impractical and insecure to whitelist the IP of every workspace instance. But you could whitelist a dedicated Tailscale exit node with a static IP. Then you could connect to that exit node from Gitpod and access the service. 

Another one I could think of is accessing geo-restricted services.

Hope this helps and would love to see it implemented!

**Comment by johannesdrescher** [comment]
Hi @atduarte, any decisions about this yet? I just ran into another situation where the ability to change the outbound IP would have been super useful.

**Comment by nVitius** [comment]
Running into the same issue. Starting tailscale w/ the exit-node flag crashes the workspace.

**Comment by nVitius** [comment]
The output from `ssh -vvv` when connecting to a workspace via ssh after trying to start tailscale with an `--exit-node` option:
![image](https://user-images.githubusercontent.com/3804041/195223773-ba3a155c-160e-4e37-b184-74e13056a048.png)

**Comment by aabkn301** [comment]
Any news on this? The issue is still reproducible.
