### ISSUE TITLE
Github hover link on workspaces page

### ISSUE THREAD

**Issue by octemist** [gitpod-io/gitpod#8779]
## Is your feature request related to a problem? Please describe
On the /workspaces page when I go to click my workspace there's a github link beneath it which has some kind of title which covers the link I'm trying to click. It happens nearly every time which can be several times a day. It's really annoying, particularly as the github link seems to be there twice which seems unnecessary.

## Describe the behaviour you'd like
Hopefully the hover-over can be removed, or the entire link for that matter.

## Describe alternatives you've considered
None.

## Additional context
Happens on desktop view.

**Comment by geropl** [comment]
@gtsiolis I faintly recall we're aware of this and already have an issue, but I cannot find it. Do you know where that was? If yes: Can you close this?

**Comment by gtsiolis** [comment]
@geropl I had a note somewhere to come back to this.

We added this tooltip (title) back in https://github.com/gitpod-io/gitpod/pull/5323 to avoid hiding with truncation the full repository URL, see https://github.com/gitpod-io/gitpod/issues/8686#issuecomment-1062885768:

> FWIW, the tooltip on the project (repository URL) was added back in https://github.com/gitpod-io/gitpod/pull/5323 as a boring (simple) solution and a two-way door decision which we can safely remove in the future, see https://github.com/gitpod-io/gitpod/issues/5122#issuecomment-903692584. 💭

> In some cases, middle truncation could help, see https://github.com/gitpod-io/gitpod/issues/5122#issuecomment-895863295. 💡

Re-posting from the same comment in https://github.com/gitpod-io/gitpod/issues/8686#issuecomment-1062885768:

> For points [1] and [2] I'd say improving the design of the Workspaces page is a good way forward. This could include removing duplicate information that is currently truncated, dropping any unnecessary elements, replacing long repository URLs with project links when possible, etc.

I'll close this in favor of https://github.com/gitpod-io/gitpod/issues/8686. Cc @octemist
