### ISSUE TITLE
Netlify & NetlifyCMS

### ISSUE THREAD

**Issue by zzrez** [gitpod-io/gitpod#878]
Please confirm these 2 can work without a problem, as this is crucial to our testing of gitpod.

For example, when the site of a Gitpod container launches after the command "gatsby develop", adding "/admin" at the end of the URL does bring up the NetlifyCMS login. So if I go through the normal steps of connected up the container's github repo to Netlify, I presume we can see OK in NetlifyCMS?

(assumes of course the previous steps of Identity, creating gateway, inviting user etc).

Thanks

**Comment by svenefftinge** [comment]
I did a quick test with https://github.com/svenefftinge/gatsby-starter-netlify-cms-1
and running
```
npm install -g gatsby-cli netlify-cli && netlify cli
```
allows me to open the app in preview.

**Comment by svenefftinge** [comment]
please file a new ticket if you find anything that doesn't work as expected.
