### ISSUE TITLE
subdomains for gitpod urls

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#8784]
We use in docker base apps different subdomains that we can access like:

app.product.io
auth.product.io

and use it locally with

app.localhost
auth.loclhost
...

The current gitpod URL syntax is that:

https://PORT-TENANT.wsREGION.gitpod.io/

we would like to allow also

https://myPrivateSubdomain.PORT-TENANT.wsREGION.gitpod.io/

**Comment by atduarte** [comment]
Hello @konne! Unfortunately, even though I believe this is something that makes sense for us to do, we don't have bandwidth in the next couple of weeks to consider this. We will get back and reconsider this in a couple of weeks.

May I ask in the meantime how are you mitigating the issue currently? Are you using the local companion app or proxying to a separate port?

**Comment by konne** [comment]
@atduarte we use the local companion app, but this app is not very "end"-user friendly like QAs, PMs,...

**Comment by atduarte** [comment]
@konne I have learned that we are quite limited in the number of SSL certificates we can generate [[1](https://letsencrypt.org/docs/rate-limits/)] and we wouldn't be able to implement this as described. 😞 

For now I don't see a clear and straightforward alternative that is better than the local companion app trick or proxying to different ports. I will research the topic, and in the meantime if you have any ideas please share 🙏

**Comment by atduarte** [comment]
Noticed there's another older issue with the same proposal: #7733. Will close this one.

**Comment by PhilippeVienne** [comment]
Hello,

Using subdomains like https://myprivatesubdomain.port-tenant.wsregion.gitpod.io/ can in fact be a nightmare on SSL certificate level, we still need to have multiple domains per port.

It may be possible to point any `https://<suburlpart>-<port>-<tenant>.ws<region>.gitpod.io` to the matching port. 
@atduarte we may event do it by just editing the file https://github.com/gitpod-io/gitpod/blob/main/components/proxy/conf/workspace-handler.full

I may fill a PR on the subject but I will need guidance to test.

**Comment by letmejustputthishere** [comment]
hey, is there any progress on this? i'd really need this as well :) can you share any workarounds for the issue?
