### ISSUE TITLE
Technical debt: Re-unify AuthProviderInfo and AuthProviderEntry

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8788]
## Is your feature request related to a problem? Please describe

We currently have two protocol shapes that are very similar:

https://github.com/gitpod-io/gitpod/blob/4e331313ad8787d6218639d94bf6dd4483c6aa7f/components/gitpod-protocol/src/protocol.ts#L1142-L1175

`AuthProviderInfo` vs `AuthProviderEntry`:

- `authProviderId` vs `id`
- `authProviderType` vs `type`
- `host` 👍
- `ownerId` 👍 (sometimes)
- `verified = true` vs `status = "verified"`
- (usage concerns) vs (oauth config)

## Describe the behaviour you'd like

It would be great to re-unify them. 🧹 ✨ 

## Additional context

For more context, see [Slack thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1646409734670089) (internal)

**Comment by geropl** [comment]
@AlexTugarev I wondered the same before, but kept it as-is for velocities sake. I wonder if this make sense from you perspective (in general)?
