### ISSUE TITLE
Error : Gitpod layer

### ISSUE THREAD

**Issue by bangyogesh** [gitpod-io/gitpod#879]
I have been experimenting with kalilinux and trying to create the environment in gitpod using base image of kalilinux.
During the container image build, it fails with the error
"Error: Error while adding Gitpod layer."

The URL to create the container is https://gitpod.io/#https://github.com/bangyogesh/kalilinuxdev .

The screenshot of the error is attached herewith

![image](https://user-images.githubusercontent.com/2494368/67869336-492c2d00-fb53-11e9-840f-bff978d10727.png)

**Comment by JesterOrNot** [comment]
see #813 similar issue

**Comment by bangyogesh** [comment]
@JesterOrNot Indeed it looks similar to issue #813 . Wondering is there any resolution for this ?
There will be need to use custom docker images based on the user needs. If Gitpod can't support those images ( not sure though ), there should be someway to know it. Ideally container images should run across Linux flavours built on the base image specific to processor family ( amd64, arm etc ).

**Comment by JesterOrNot** [comment]
Ideally yes but I have found images based on ubuntu that fail at the gitpod layer, also I think future discussions should take place on #813

**Comment by bangyogesh** [comment]
@JesterOrNot, Your suggestion is most welcome. It's good to reduce the clutter.
I shall close this issue & for further discussion, shall use issue #813. Many thanks.

**Comment by bangyogesh** [comment]
Closing this issue. For all similar discussions let's use #813 .
