### ISSUE TITLE
Epic: Workspace component integration tests

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8799]
## Summary

Workspace component integration tests are fixed to reliably pass, run daily against main, and report status in team channel.

## Context

The integration tests compile to separate binaries and can be executed individually [via this script](https://github.com/gitpod-io/gitpod/blob/main/test/entrypoint.sh). Additionally, Leeway builds them as an asset, and we can [run them in werft].

Tasks:
- Fix broken integration test
  - [x] #8800
  - [x] #9627
  - [x] #9575 
  - [x] #9782
  - [x] ~#9990~ (Moves to #7901)
- Enhance integration test
  - [x] #9953
- Add new integration test
  - [x] #8122
- Nightly integration test trigger by werft
  - [x] #9597 (on core-dev environment)
  - [x] #9749 (on preview environment)

## Value

We will know to the day (not necessarily which PR) if workspace components are passing or failing. This will help us have more confidence in the tests, ship with confidence (assuming tests are passing), and identify breakage before shipping to production.

## Acceptance criteria

Tests are run daily against default branch and results are shared in the team workspace Slack channel `#workspace-jobs`.

## Complexities

1. [Werft jobs for the Gitpod mono repo](https://github.com/gitpod-io/gitpod/tree/main/.werft) were recently refactored to accommodate the new `with-vm` annotation. Now, the default environment is preview environment (`with-vm` annotation enabled by default).
2. Tests are [compiled into separate binaries](https://github.com/gitpod-io/gitpod/blob/7ac5d9d3150dd6fb72f32915afd1923574b3811b/test/leeway-build.sh#L1).
3. The [entry point](https://github.com/gitpod-io/gitpod/blob/7ac5d9d3150dd6fb72f32915afd1923574b3811b/test/entrypoint.sh#L1) for tests will need to be modified, so that from a werft job, we can specify parameters that make test run conditional by component name. For example, this way, we can have an exclusive workspace team werft job that only runs workspace component tests.

**Comment by kylos101** [comment]
Hi @jenting :wave: , this is the epic tracking the issues (work breakdown) for our team workspace integration tests. May I ask you to review, and let me know if you have any questions?

It'd be ideal if you familiarized yourself with running the tests via go and werft, prior to getting started with https://github.com/gitpod-io/gitpod/issues/8800.

**Comment by jenting** [comment]
The integration test result https://werft.gitpod-dev.com/job/gitpod-custom-jenting-inte-test.0

@kylos101 should we close this issue?

**Comment by kylos101** [comment]
Amazing work, @jenting ! Thank you for looping in @princerachit and @utam0k to help support you on this effort, too. 

@jenting let's wait till the next scheduled run is complete and successful, so we can see success in Slack. That should be tomorrow, right?

@atduarte this is a tech debt epic, and almost done. We wanted to consult with you before closing. Is there anything else we need to do?

**Comment by atduarte** [comment]
@kylos101 agree with you that we should wait for tomorrow to validate that the scheduling is working and the run is successful. Will it continue to fail because of `TestMissingBackup/CreateWorkspace/it_can_run_workspace_tasks/pvc_backup_init`? Would be preferable to avoid broken windows.
