### ISSUE TITLE
[terminals] Don't auto cd into $GITPOD_REPO_ROOT

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#88]
Every `/bin/bash` session starts with the initial workspace root as the working directory.
This is because a cd is added to the `.bashrc`.
Instead the working directory should be respected.

**Comment by akosyakov** [comment]
`/bin/bash` fails with `/home/gitpod/.nvm/versions/node/v8.12.0/bin/node: cannot execute binary file` for the command in Theia repo:
```
/bin/bash /home/gitpod/.nvm/versions/node/v8.12.0/bin/node --inspect-brk=44441 _mocha /workspace/theia/packages/core/src/common/uri.spec.ts --no-timeouts --colors --opts /workspace/theia/configs/mocha.opts
```

Such command is generated by `ShellProcess`: https://github.com/theia-ide/theia/blob/e0ccd3ac7b182251aa5321004ab2f4387de0385f/packages/terminal/src/node/shell-process.ts#L66
