### ISSUE TITLE
Gitpod context parser doesn't understand hostnames with uppercase letters

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#8807]
### Bug description

From my understanding, uppercase letters are allowed in hostnames, and they're simply "ignored" (i.e. DNS resolution is case insensitive).

- https://github.com/gitpod-io/gitpod --> works ✅ (opens GitHub repo as usual)
- https://gitpod.io/#https://github.com/gitpod-io/gitpod --> works ✅ (opens GitHub repo in Gitpod as usual)
- https://GitHub.com/gitpod-io/gitpod --> works ✅ (caps are ignored, opens GitHub repo)
- https://gitpod.io/#https://GitHub.com/gitpod-io/gitpod --> fails ❌

<img width="1439" alt="Screenshot 2022-03-14 at 21 30 01" src="https://user-images.githubusercontent.com/599268/158256005-7bb3adef-9f23-4365-b76b-9cef6d794f02.png">

### Steps to reproduce

1. https://gitpod.io/#https://GitHub.com/gitpod-io/gitpod

### Expected behavior

I believe https://gitpod.io/#https://GitHub.com/gitpod-io/gitpod should also open GitHub repos as usual.

Maybe the Gitpod context parser could "ignore" caps in hostnames?

(⚠️ I believe the case-insensitiveness only applies to protocols & hostnames, but not to the entire URL -- i.e. the path should technically remain case-sensitive, even if most websites choose to consider uppercase and lowercase paths the same. We should check the relevant specifications for any security implications around handling caps in hostnames.)

**Comment by sujaikumar** [comment]
Thanks @gtsiolis . Sorry, I should have looked here for duplicates. But because I started this question in discord and that (seemingly) had nothing on this error, I went straight to an issue:bug here. Will look on github issues in future before posting anything :-)

**Comment by gtsiolis** [comment]
It's ok, @sujaikumar! I've moved this to our internal issue tracker with a low priority for now.

Thanks for catching this. ⚾

**Comment by gtsiolis** [comment]
Closing this in favor of EXP-512.
