### ISSUE TITLE
[VS Code extensions] Cannot add connection using MySQL extension

### ISSUE THREAD

**Issue by knutwannheden** [gitpod-io/gitpod#881]
I have a Gitpod workspace based on the `gitpod/workspace-mysql` Docker image (see https://github.com/knutwannheden/jOOQ-demo), where I also installed a MySQL VS Code extension I found (https://marketplace.visualstudio.com/items?itemName=formulahendry.vscode-mysql).

While the extension is visible in the bottom left of the Explorer, nothing appears to happen when I click the `+` button (to add a new connection). This could of course also be a problem with the extension itself.

![image](https://user-images.githubusercontent.com/408765/67898824-56e8af00-fb61-11e9-9f51-1692b420a0d0.png)

**Comment by knutwannheden** [comment]
I tried a few other VS Code extensions as well, but I frequently see errors like "Cannot edit in read-only editor" (when typing in editors created by the extension) or just blank editors opening up. I am wondering if I am doing something completely wrong...

**Comment by svenefftinge** [comment]
The VS Code extension support is still beta and while Gitpod supports most programming language extensions we are lacking behind with extensions heavily based on WebViews and some other APIs. We are working on it and target to be fully compatible early 2020.

**Comment by knutwannheden** [comment]
I understand. Some kind of indicator or log message would of course be nice, if a problem is detected or some unsupported API is called. But I suppose that would only cover some cases.

Anyway, you can close this issue again, if you don't want to keep it open for your own tracking.

**Comment by AlexTugarev** [comment]
Hi @knutwannheden! Usually there are errors logged in the JavaScript Console of your browser, but it good actually that users are reporting those extensions to us, like you did here 👍  We can then check and see what issues for Theia we can derive from here.

**Comment by mauricioszabo** [comment]
I'm also affected by this. In my case, my extension exposes a javascript file to a webview and gitpod isn't being able to resolve the URL for the file, and returns a 404 while resolving the URL:

` https://<some-uuid>.ws-us02.gitpod.io/webview/tmp/vscode-extensions/mauricioszabo.clover%400.0.2/extension/view/js/main.js`

I can confirm the file `/tmp/vscode-extensions/mauricioszabo.clover@0.0.2/extension/view/js/main.js` exist. Is it the same bug?

**Comment by svenefftinge** [comment]
We have a fix in the pipeline. We are testing and hope we can deploy tomorrow.
