### ISSUE TITLE
Cannot launch a workspace from a snapshot that was created from a workspace created from a snapshot

### ISSUE THREAD

**Issue by cjensenius** [gitpod-io/gitpod#8810]
### Bug description

In our workflow we often share workspace snapshots to facilitate troubleshooting or reviewing complex changes. One such workflow requires that one individual creates a workspace and configures it, then takes a snapshot and sends the image to another individual. That individual launches a workspace from the snapshot and makes data-integration related changes and takes another snapshot to share. An individual who attempts to launch a workspace from the second snapshot is presented with the following failure:
![image](https://user-images.githubusercontent.com/1717750/158283367-73288e85-32ad-4ea6-9ce0-9530c7fe64a8.png)

### Steps to reproduce

1. Launch a workspace
2. Take a snapshot from that workspace
3. Create another workspace from the snapshot
4. Take a snapshot of the newly created workspace
5. Attempts to launch the workspace URL improperly implies that I do not have read access to the repository
![image](https://user-images.githubusercontent.com/1717750/158283455-de2564d8-b0e5-4c9a-b033-6802dcb96f62.png)

### Expected behavior

I'm expecting that if I have the proper read access to the repository that I can create a workspace from any snapshot, regardless of if that snapshot was created originally from a snapshot.

### Anything else?

I am not certain, but I believe this workflow *may* have worked in the past, please take this assertion with a grain of salt.

**Comment by geropl** [comment]
@jldec Do you want to take this?

**Comment by cjensenius** [comment]
Reporting back, I created silver-mule-tjcnr87nn6f.ws-us40.gitpod.io from a snapshot, made changes and then took another snapshot. Launching from that snapshot created emerald-dove-p320icehvhn.ws-us40.gitpod.io which launched normally with no apparent problems.

Hope it's OK to close?
