### ISSUE TITLE
Select git provider button for GitHub Enterprise is truncated

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#8814]
This is related to #8603.  
The hostname of the GHE instance should not be truncated. 

![Screenshot 2022-03-15 at 08 12 20](https://user-images.githubusercontent.com/849592/158334274-347bc04f-054e-4862-b140-581fa92ce778.png)

**Comment by gtsiolis** [comment]
Closing this in favor of https://github.com/gitpod-io/gitpod/issues/9127. 📕  Cc @jldec
