### ISSUE TITLE
Display IDE detail versions

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#8816]
## Describe the behaviour you'd like

Display IDE detail versions, so that users know what Gitpod actually support now.

see also https://github.com/gitpod-io/gitpod/issues/7932#issuecomment-1026547718

**Comment by gtsiolis** [comment]
Re-posting from the [relevant discussion](https://gitpod.slack.com/archives/C02CBKZEVS8/p1649747176040459?thread_ts=1649691141.992889&cid=C02CBKZEVS8) (internal) (Cc @akosyakov) for visibility regarding the question mentioned [above](https://github.com/gitpod-io/gitpod/issues/8816#issuecomment-1095184129):

> - We have CI jobs which keep stable and latest versions up-to-date in Gitpod and we provision these versions in workspaces. These CI jobs should be improved to capture info about concrete versions.
> - JB Gateway while connecting to a workspace check which backend we are running and then provision a proper client to the local machine.

**Comment by akosyakov** [comment]
I like how versions displayed, but can we rather have VS Code Web and VS Code Desktop?

**Comment by gtsiolis** [comment]
Re-opening as this is still relevant.

**Comment by akosyakov** [comment]
We could put manifest file with version in first layer of IDE image under the same path and then use blobserve to resolve it in ide-service.

**Comment by gtsiolis** [comment]
Closing this as the first iteration has been added in https://github.com/gitpod-io/gitpod/pull/15139.

Cc @filiptronicek @mustard-mh @akosyakov @easyCZ
