### ISSUE TITLE
Limit on maximum parallel workspaces is not respected

### ISSUE THREAD

**Issue by mjaindwave** [gitpod-io/gitpod#8830]
### Bug description

We are working with GP 0.10 which has 16 as the max parallel workspaces limit that can be opened by a single user.

As per our testing, we are able to open more than 16 parallel workspaces. 

We would like to limit the number of parallel workspaces that can be opened by a single user.

### Steps to reproduce
export const MAX_PARALLEL_WORKSPACES = 16;
1. Set a limit on the max parallel workspaces for a single user
2. Open parallel workspaces > the max parallel workspaces limit.

### Expected behavior

User should get an error message about exceeding the max parallel workspaces limit.

**Comment by geropl** [comment]
This has likely been fixed in the meantime by the introduction of `EntitlementService`. We still need to verify whether expectations are aligned.

**Comment by jldec** [comment]
This works properly now with our new flexible billing.
