### ISSUE TITLE
Cant clone a repository

### ISSUE THREAD

**Issue by olleicua** [gitpod-io/gitpod#8834]
### Bug description

Cannot clone a git repository

### Steps to reproduce

- click `Clone Git Repository` 
- The bar at the top is highlighted
- I past in the git like
- select the option to clone
- A modal tells me I need more permissions so I click Allow
- A popup in the lower left says `An operation requires additional permissions: workflow. Please grant permissions and try again.`
- I click `open access controls`
- i get an error message saying `error 5 no token available`

### Workspace affected

https://futurepastimes-letterpie-smoexs7huwk.ws-us34.gitpod.io/

**Comment by pawlean** [comment]
Hey @olleicua! Can you check your permissions [here](https://gitpod.io/integrations)?

**Comment by olleicua** [comment]
under permissions it says: "public_repo, repo, user:email"

**Comment by pawlean** [comment]
Can you change your permissions to this?

<img width="489" alt="2022-03-21 at 11 32 30 - Google Chrome" src="https://user-images.githubusercontent.com/17087373/159252981-7d8c205c-062e-4bce-a25a-441cfd5ff8cc.png">
<img width="930" alt="2022-03-21 at 11 32 55 - Google Chrome" src="https://user-images.githubusercontent.com/17087373/159253025-75a7db37-442f-44c0-9587-7e6f006ae236.png">

**Comment by pawlean** [comment]
Can you change your permissions to this?

<img width="489" alt="2022-03-21 at 11 32 30 - Google Chrome" src="https://user-images.githubusercontent.com/17087373/159252981-7d8c205c-062e-4bce-a25a-441cfd5ff8cc.png">
<img width="930" alt="2022-03-21 at 11 32 55 - Google Chrome" src="https://user-images.githubusercontent.com/17087373/159253025-75a7db37-442f-44c0-9587-7e6f006ae236.png">
