### ISSUE TITLE
Outcome of best-practice conversation with Replicated

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#8840]
> Original doc in [shared drive](https://docs.google.com/document/d/1Haf-blIYzEH-NpQ64ywpEcHeeVaPDGkM_ai5dTeTwtw/edit#heading=h.hta3hqvpb0fy)

## Required

- [x] #8846
- [x] #8856
- [x] #8861
- [x] #8865

## Recommended

- [x] #8862
- [x] #8864
- [x] #8789

## Recommended (when air-gap available)

- [x] #9042
- [ ] Consider adding `requireMinimalRBACPriviledges: true`. This requires thought as may have unintended consequences
- [ ] Test with GitOps - will this even work as only publishes the stuff in `/manifests`?
- [x] Test air-gap
- [ ] Test embedded cluster

## Optional

- [ ] Add Prometheus - https://kots.io/vendor/config/dashboard-graphs/

**Comment by BarryWilliams** [comment]
Very nice!

**Comment by MrSimonEmms** [comment]
> Very nice!

All thanks to you

**Comment by MrSimonEmms** [comment]
Closing as the 🛹 is done
