### ISSUE TITLE
Can't run a docker container inside gitpod free tier

### ISSUE THREAD

**Issue by SandraAhlgrimm** [gitpod-io/gitpod#8868]
### Bug description

When I want to test a database integration locally, I was able to run a container and then connect and test my code. Today, I figured that this is not working any longer:

 $ docker run -d -p 5432:5432 -e POSTGRES_USER=coolstore -e POSTGRES_PASSWORD=coolstore123 -e POSTGRES_HOST_AUTH_METHOD=md5 -e POSTGRES_DB=monolith postgres
Unable to find image 'postgres:latest' locally
latest: Pulling from library/postgres
ae13dd578326: Pull complete 
723e40c35aaf: Extracting [==================================================>]  4.415MB/4.415MB
bf97ae6a09b4: Download complete 
2c965b3c8cbd: Download complete 
c3cefa46a015: Download complete 
64a7315fc25c: Download complete 
b9846b279f7d: Download complete 
ed988fb8e7d9: Download complete 
ed4bb4fd8bb5: Download complete 
ead27f1733c8: Download complete 
7d493bacd383: Download complete 
0920535e8417: Download complete 
db76d5bdbf2c: Download complete 
docker: failed to register layer: Error processing tar file(exit status 1): replaceDirWithOverlayOpaque("/etc/X11") failed: createDirWithOverlayOpaque("/etc/rdwoo460807435") failed: failed to mkdir /etc/rdwoo460807435/m/d: mkdir /etc/rdwoo460807435/m/d: input/output error.
See 'docker run --help'.

### Steps to reproduce

Go in the terminal and enter something like:

$ docker run -d -p 5432:5432 -e POSTGRES_USER=coolstore -e POSTGRES_PASSWORD=coolstore123 -e POSTGRES_HOST_AUTH_METHOD=md5 -e POSTGRES_DB=monolith postgres

### Workspace affected

all workspaces

### Expected behavior

I saw a started container instance and was able to connect with my code.

### Example repository

https://github.com/SandraAhlgrimm/workshop-migrate-jboss-on-app-service

### Anything else?

Thank you!

**Comment by aledbf** [comment]
@SandraAhlgrimm  I opened a pull request to update some dependencies in the docker image. It works now.
PR:https://github.com/SandraAhlgrimm/workshop-migrate-jboss-on-app-service/pull/1

You can see the working version https://gitpod.io/#https://github.com/aledbf/workshop-migrate-jboss-on-app-service/tree/aledbf/fix

**Comment by SandraAhlgrimm** [comment]
Thank you @aledbf for your quick help and fix!
