### ISSUE TITLE
[Harvester] improve disk read/write performance

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#8869]
## Is your feature request related to a problem? 
The new preview environments run on Harvester and use Longhorn for persistent volume storage. 
Due to Longhorn, the disk read/write performance is currently limited to the network throughput, because all reads/writes go over the network. 

## Describe the behaviour you'd like
Disk reads/writes should be operations local to the Harvester node and not go over the network.

## Solution1:
Reduce the number of replicas to 1 and enforce the replica is on the same node. 
As of writing this, I don't have a solution for the latter, but maybe we'll be helped here: https://github.com/harvester/harvester/issues/2027.

## Solution2:
Don't use Longhorn. 

Instead, use the standard KubeVirt for image handling:
https://kubevirt.io/2020/KubeVirt-VM-Image-Usage-Patterns.html

The Harvester people on the other hand don't seem to like alternatives to Longhorn very much:
https://github.com/harvester/harvester/issues/1469#issuecomment-948844455
> Having another storage class is against the general design of Harvester. The VM with local path has to be treated separately and cannot be migrated, snapshotted, backed up etc.

> If no replication is needed, Longhorn with a single replica might be the way to do it instead.

**Comment by mads-hartmann** [comment]
Moving to "Dedicated cluster for preview environments"

**Comment by jenting** [comment]
> Reduce the number of replicas to 1 and enforce the replica is on the same node.

You could change the default data locality to best effort. Although I don't know where is the setting in the Harvester, however you could change the Longhorn Setting CR `settings.longhorn.io` instead. Ref to https://longhorn.io/docs/1.2.4/references/settings/#default-data-locality

**Comment by fanlix** [comment]
prefer Solution1.
* make default `replias = 1`,  `locality = best effert`. get best performace within longhorn engine.
* for more data safty, user may change `replias = N` easily by longhorn ui to any existing pvc

for current version, v1.0.1
* very hard to set `default` replicas, easy for `existing` pvc handly
* easy to set locality by longhorn ui both `default` and `existing`

**Comment by meysholdt** [comment]
Thank you @jenting and @fanlix! 

> make default replias = 1, locality = best effert. get best performace within longhorn engine.

works well for us now.
