### ISSUE TITLE
GitPod completely down

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#8877]
### Bug description

- Can't login (with github) -- stuck loading forever
- Can't start workspaces from a PR or branch from github -- just a black page saying "Dashboard"
- Can't access the workspaces dashboard if already logged in (no responses from server)

My whole team is affect; was working fine until about 20min ago.

### Steps to reproduce

Go to login.
Login in with github
Watch the browser spin.

### Workspace affected

all

**Comment by corneliusludmann** [comment]
https://www.gitpodstatus.com/incidents/64g3zgffwz17

**Comment by smacintyre** [comment]
Thank you. It seems to be working now.
