### ISSUE TITLE
Add check to see if should use shiftfs or fuse

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#8883]
> See [internal discussion](https://gitpod.slack.com/archives/C02F19UUW6S/p1647600494757959)

By default, we use `fuse` over `shiftfs` for the file systems on the installation. ShiftFS has some performance advantages, but requires messing with the kernel module - Fuse is therefore easier to get set up with.

Add a test in the `gitpod-installer-job.yaml` to decide if `shiftfs` can be used and to fallback to `fuse` if not.

## Suggested approach

1. Run the [shiftfs-module-loader](https://github.com/gitpod-io/gitpod/tree/main/components/ws-daemon/shiftfs-module-loader).
2. If exits with code 0, add `shiftfs` in the `yq` amendment section
3. Else, do nothing (remaining with `fuse`)

**Comment by krauthosting** [comment]
@MrSimonEmms BTW Suggested approach covers common edge case with no kernel headers packages on Ubuntu hosts.  
The container hack in shiftfs-module-loader fails if this native dkms package dependency is missing on underlying hosts.
Good reasoning to default to fuse but still aim to activate shiftfs :+1: At least until migrate to idmapped after jammy release ...
