### ISSUE TITLE
Cant close workspace

### ISSUE THREAD

**Issue by alesanchezr** [gitpod-io/gitpod#8886]
### Bug description

- It never stops
- It cant be deleted
- Event though its running, i can open it.

### Steps to reproduce

Click here: https://gitpod.io/start/#breathecode-apiv2-7fj4qmqtnpm

### Workspace affected

breathecode-apiv2-7fj4qmqtnpm

**Comment by aledbf** [comment]
@alesanchezr the workspace should appear as stopped now.
