### ISSUE TITLE
gp init to create a new Gitpod file

### ISSUE THREAD

**Issue by 32leaves** [gitpod-io/gitpod#89]
When I want to create a `.gitpod` file, I find myself going back and forth between the documentation and my editor. It would be great if there were something like `gp init` (akin to `npm init`) which would guide me through creating a `.gitpod` file.

**Comment by 32leaves** [comment]
Tasks:

- [ ] Implement `gp init`
- [ ] Deploy
- [ ] Update documentation

**Comment by svenefftinge** [comment]
Also we should define a schema and configure the yaml language server with it.
