### ISSUE TITLE
Docker Error Gitpod

### ISSUE THREAD

**Issue by benjamink85** [gitpod-io/gitpod#890]
Using a Dockerfile from a private repository and ends up getting an error when launching the pod:

Error: (HTTP code 500) server error - stat /var/lib/docker/165536.165536/tmp: no such file or directory
Please file an issue if you think this is a bug.

**Comment by JesterOrNot** [comment]
Can you show us the gitpod.ymls' and the docker images' contents?

**Comment by benjamink85** [comment]
Here is a repository with those files:
https://github.com/benjamink85/Gitpod_demo/tree/master

**Comment by JesterOrNot** [comment]
Ok I can reasonably say that this is a bug with Gitpod specifically with the dependency

**Comment by JesterOrNot** [comment]
It seems that this is a common issue, I say for the sake of keeping the conversation centered that we close #891 and #888, fair?

**Comment by jrebey** [comment]
This just recently started happening when I tried to create a new workspace. We didn’t change our .gitpod.yml or .gitpod.dockerfile when it stopped working. I don’t care which issues get closed as duplicates as long as the issue is tracked.

**Comment by JesterOrNot** [comment]
Ok cool.

**Comment by JesterOrNot** [comment]
@robertPiro can you give an example repository?

**Comment by robertPiro** [comment]
Yes: https://github.com/robertPiro/parallelTrie

**Comment by JesterOrNot** [comment]
Could this be an issue with the Kubernetes Cluster? @svenefftinge

**Comment by jrebey** [comment]
That was my suspicion. It’s not reliably reproduced, and other workspaces didn’t need to build a new container when there were no changes to our dockerfile. That makes me think there’s an issue with a node in the cluster, but I have limited knowledge about the backend. When the container was readily available in the docker cache the workspace loads just fine.

**Comment by benjamink85** [comment]
Any ETA on when it's going to be solved? It's kind of limit the usage of the platform.

**Comment by geropl** [comment]
Hi @benjamink85 , thank you for reporting this. Will have a look.

**Comment by geropl** [comment]
So it seems one of the nodes in one of our clusters got in a bad state and would fail all docker builds. @benjamink85 @jrebey Can you confim that it works again? I tested some of the repos you posted and they seem to work.

**Comment by benjamink85** [comment]
Now it's just stuck on starting for 15 minutes without any progress.

**Comment by JesterOrNot** [comment]
have you made any changes to the Dockerfile @benjamink85

**Comment by benjamink85** [comment]
Not to the one in the repository that I shared with you.

**Comment by jrebey** [comment]
When launching Gitpod today it triggered a container build and it completed successfully. Works on my end.

FYI, I've noticed that you need to start Gitpod over again in a new tab if your session times out, etc. otherwise it just sits at the loading screen.

**Comment by benjamink85** [comment]
OK. Working now.
Thank you for fixing it.

**Comment by robertPiro** [comment]
Works for me too!

**Comment by JesterOrNot** [comment]
Should we close the issue?

**Comment by benjamink85** [comment]
Yes from me.

**Comment by JesterOrNot** [comment]
Yes from me.

**Comment by robertPiro** [comment]
yes please

**Comment by jrebey** [comment]
Fine by me to close. I’ve been using it all day without issue.

**Comment by geropl** [comment]
Ok, closing this.

> FYI, I've noticed that you need to start Gitpod over again in a new tab if your session times out, etc. otherwise it just sits at the loading screen.

@jrebey Could you create a new issue for this if it is reproducible? Thanks!
