### ISSUE TITLE
.Net broken again?

### ISSUE THREAD

**Issue by purkhusid** [gitpod-io/gitpod#8901]
### Bug description

Could it be that https://github.com/gitpod-io/gitpod/issues/5090 has regressed?
I get Permission denied errors when trying to run `dotnet restore` on my project. 

If I run `strace` to see what files the permission errors are coming from then I see:
```
4781  stat("/run/containerd/io.containerd.runtime.v2.task/k8s.io/40605c02680db3faa337f88157f7b60d42a663b7c96cab637e191602bf9b693c/rootfs/home/gitpod/dotnet/dotnet", 0x7f704bffdf40) = -1 EACCES (Permission denied)
4781  access("/run/containerd/io.containerd.runtime.v2.task/k8s.io/40605c02680db3faa337f88157f7b60d42a663b7c96cab637e191602bf9b693c/rootfs/home/gitpod/dotnet/dotnet", X_OK) = -1 EACCES (Permission denied)
```
I would have expected the files to have the path `/home/gitpod/dotnet/some/file` but instead they are prefixed with what appears to be a mount.

This can be fixed by installing the .Net installation on the `/workspace` mount instead of the `/home` mount. This is the same workaround as was used for #5090 and that seems to indicate that it has regressed.

Tagging @ghuntley since he is pretty knowledgeable about .Net related things. 

### Steps to reproduce

Open the following repo: https://gitpod.io/#https://github.com/purkhusid/gitpod-dotnet-repro

Run `dotnet tool restore` or `dotnet build`

### Expected behavior

All `dotnet` commands should work as they did a few days ago. 

### Example repository

https://gitpod.io/#https://github.com/purkhusid/gitpod-dotnet-repro

### Anything else?

If it does matter at all then I'm running on the eu38xl cluster.

**Comment by purkhusid** [comment]
I hope this can be looked into ASAP since this breaks the workspaces for everybody using .Net with Gitpod.

**Comment by silveredgold** [comment]
I just tried out Gitpod for the first time but since I'm working with a .NET project, it's a complete non-starter. Is there no way around this or does Gitpod just not fully support .NET projects?

**Comment by utam0k** [comment]
Perhaps this is a kernel version issue (possibly a bug). We updated our kernel version 8 days ago. Perhaps that is the cause. But we don't have an easy way to change to the mainstream linux kernel. So I suggest using docker as a workaround.
```console
$ docker run -it --rm -w /opt/app -v $PWD:/opt/app mcr.microsoft.com/dotnet/sdk:6.0 dotnet build
```

**Comment by utam0k** [comment]
Also, this is not a dotnet problem, but rather a corruption of `/proc/$pid/maps`.
```console
gitpod /workspace/gitpod-dotnet-repro (main) $ cat /proc/self/maps
55cdb90cb000-55cdb90cd000 r--p 00000000 08:01 90179955                   /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/bin/cat
55cdb90cd000-55cdb90d2000 r-xp 00002000 08:01 90179955                   /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/bin/cat
55cdb90d2000-55cdb90d5000 r--p 00007000 08:01 90179955                   /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/bin/cat
55cdb90d5000-55cdb90d6000 r--p 00009000 08:01 90179955                   /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/bin/cat
55cdb90d6000-55cdb90d7000 rw-p 0000a000 08:01 90179955                   /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/bin/cat
55cdb9def000-55cdb9e10000 rw-p 00000000 00:00 0                          [heap]
7f3c3c548000-7f3c3c56a000 rw-p 00000000 00:00 0 
7f3c3c56a000-7f3c3c850000 r--p 00000000 08:01 620770817                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/locale/locale-archive
7f3c3c850000-7f3c3c872000 r--p 00000000 08:01 174065948                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/libc-2.31.so
7f3c3c872000-7f3c3c9ea000 r-xp 00022000 08:01 174065948                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/libc-2.31.so
7f3c3c9ea000-7f3c3ca38000 r--p 0019a000 08:01 174065948                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/libc-2.31.so
7f3c3ca38000-7f3c3ca3c000 r--p 001e7000 08:01 174065948                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/libc-2.31.so
7f3c3ca3c000-7f3c3ca3e000 rw-p 001eb000 08:01 174065948                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/libc-2.31.so
7f3c3ca3e000-7f3c3ca44000 rw-p 00000000 00:00 0 
7f3c3ca4c000-7f3c3ca4d000 r--p 00000000 08:01 174065926                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/ld-2.31.so
7f3c3ca4d000-7f3c3ca70000 r-xp 00001000 08:01 174065926                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/ld-2.31.so
7f3c3ca70000-7f3c3ca78000 r--p 00024000 08:01 174065926                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/ld-2.31.so
7f3c3ca79000-7f3c3ca7a000 r--p 0002c000 08:01 174065926                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/ld-2.31.so
7f3c3ca7a000-7f3c3ca7b000 rw-p 0002d000 08:01 174065926                  /run/containerd/io.containerd.runtime.v2.task/k8s.io/910a04c72ec7878f9e9ff1aa9023d0ee4a292ccbd54954300ac97c81a7e6a141/rootfs/usr/lib/x86_64-linux-gnu/ld-2.31.so
7f3c3ca7b000-7f3c3ca7c000 rw-p 00000000 00:00 0 
7ffeede76000-7ffeede97000 rw-p 00000000 00:00 0                          [stack]
7ffeedee5000-7ffeedee9000 r--p 00000000 00:00 0                          [vvar]
7ffeedee9000-7ffeedeeb000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]
```

**Comment by yellowsink** [comment]
> This can be fixed by installing the .Net installation on the /workspace mount instead of the /home mount.

For those who want to try, I got a successful .NET install via:
```sh
wget "https://dot.net/v1/dotnet-install.sh"
chmod +x dotnet-install.sh
./dotnet-install.sh --install-dir /workspace/dotnet
rm dotnet-install.sh
sudo ln -s /workspace/dotnet/dotnet /usr/bin/dotnet
```

**Comment by purkhusid** [comment]
@utam0k Any updates on this?

**Comment by utam0k** [comment]
@purkhusid cc: @kylos101 
We are trying to update the kernel but have not been able to yet. We apologize for the inconvenience, but please wait a little longer.

**Comment by yellowsink** [comment]
> > This can be fixed by installing the .Net installation on the /workspace mount instead of the /home mount.
> 
> For those who want to try, I got a successful .NET install via:
> 
> ```shell
> wget "https://dot.net/v1/dotnet-install.sh"
> chmod +x dotnet-install.sh
> ./dotnet-install.sh --install-dir /workspace/dotnet
> rm dotnet-install.sh
> sudo ln -s /workspace/dotnet/dotnet /usr/bin/dotnet
> ```

For those interested I have a script [here](https://gist.github.com/yellowsink/79428ca1ef8dfa323315f914f1affd4f)

**Comment by aledbf** [comment]
@utam0k this could be related to shiftfs https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1968027

**Comment by purkhusid** [comment]
Any progress?

**Comment by murratore** [comment]
Another option is to create a .gitpod.yml file in your repo with the content below. This worked for me. Every time the workspace is initiated, dotnet is loaded and installed.

```
tasks:
  - init: |
      wget "https://dot.net/v1/dotnet-install.sh"
      chmod +x dotnet-install.sh
      ./dotnet-install.sh --install-dir /workspace/dotnet
      rm dotnet-install.sh
      sudo ln -s /workspace/dotnet/dotnet /usr/bin/dotnet
```

**Comment by utam0k** [comment]
> Any progress?

We are in the process of investigating. The cause may be in the kernel, which is a bit difficult to investigate.

**Comment by utam0k** [comment]
> It didn't work for me. Using a docker based on gitpod/workspace-full.

@cristopher-rodrigues Can I ask you to give me the error message?

**Comment by raghur** [comment]
> Another option is to create a .gitpod.yml file in your repo with the content below. This worked for me. Every time the workspace is initiated, dotnet is loaded and installed.
> 
> ```
> tasks:
>   - init: |
>       wget "https://dot.net/v1/dotnet-install.sh"
>       chmod +x dotnet-install.sh
>       ./dotnet-install.sh --install-dir /workspace/dotnet
>       rm dotnet-install.sh
>       sudo ln -s /workspace/dotnet/dotnet /usr/bin/dotnet
> ```

Just tried this - didn't work. 

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
Microsoft.Build.BackEnd.NodeFailedToLaunchException: An error occurred trying to start process '/run/containerd/io.containerd.runtime.v2.task/k8s.io/ca92ca57af4df8a0f8a661ea847612f152ee5f01fb7ce672776165d9f12499f6/rootfs/home/gitpod/dotnet/dotnet' with working directory '/workspace/<myworkspace>'. Permission denied
 ---> System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/run/containerd/io.containerd.runtime.v2.task/k8s.io/ca92ca57af4df8a0f8a661ea847612f152ee5f01fb7ce672776165d9f12499f6/rootfs/home/gitpod/dotnet/dotnet' with working directory '/workspace/<myworkspace>'. Permission denied
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
   --- End of inner exception stack trace ---
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.LaunchNode(String msbuildLocation, String commandLineArgs)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.GetNode(String msbuildLocation, String commandLineArgs, Int32 nodeId, INodePacketFactory factory, Handshake hostHandshake, NodeContextTerminateDelegate terminateNode)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNode(Int32 nodeId, INodePacketFactory factory, NodeConfiguration configuration)
   at Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode(INodeProvider nodeProvider, NodeConfiguration nodeConfiguration)
   at Microsoft.Build.BackEnd.NodeManager.CreateNode(NodeConfiguration configuration, NodeAffinity nodeAffinity)
   at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
   at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass76_0.<Microsoft.Build.BackEnd.INodePacketHandler.PacketReceived>b__0()
   at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
--- End of stack trace from previous location ---
   at Microsoft.Build.Execution.BuildManager.EndBuild()
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
```

**Comment by utam0k** [comment]
@purkhusid @silveredgold @yellowsink @cristopher-rodrigues @murratore @raghur cc: @pawlean 
I was on a journey to find a workaround for a little while. Thank you for your patience. 
First of all, this problem involves shiftfs[^1][^2](Thanks for sharing these, @aledbf); it worked fine with `fuse-overlayfs`, unfortunately, the users can't select the filesystem now. And changes to the linux kernel are tough and take even longer to be released.

It's a little ugly, but I have found that you can work around this problem if you use the below method. We will continue to look at ways to make it work without some workaround for users, but try this if you want to get it working right away.
https://github.com/gitpod-io/template-dotnet-core-cli-csharp/commit/bf206c0909095fc3d0747defba5c600ea04bf97f


[^1]: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1968027
[^2]: https://lists.ubuntu.com/archives/kernel-team/2019-September/103894.html

**Comment by cristopher-rodrigues** [comment]
> @purkhusid @silveredgold @yellowsink @cristopher-rodrigues @murratore @raghur cc: @pawlean I was on a journey to find a workaround for a little while. Thank you for your patience. First of all, this problem involves shiftfs[1](#user-content-fn-1-55b853bc35e879e93596fc52e31b37fe)[2](#user-content-fn-2-55b853bc35e879e93596fc52e31b37fe)(Thanks for sharing these, @aledbf); it worked fine with `fuse-overlayfs`, unfortunately, the users can't select the filesystem now. And changes to the linux kernel are tough and take even longer to be released.
> 
> It's a little ugly, but I have found that you can work around this problem if you use the below method. We will continue to look at ways to make it work without some workaround for users, but try this if you want to get it working right away. [gitpod-io/template-dotnet-core-cli-csharp@bf206c0](https://github.com/gitpod-io/template-dotnet-core-cli-csharp/commit/bf206c0909095fc3d0747defba5c600ea04bf97f)
> 
> ## Footnotes
> 1. https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1968027 [↩](#user-content-fnref-1-55b853bc35e879e93596fc52e31b37fe)
> 2. https://lists.ubuntu.com/archives/kernel-team/2019-September/103894.html [↩](#user-content-fnref-2-55b853bc35e879e93596fc52e31b37fe)

This worked for me! Thanks a lot! 🙏

**Comment by utam0k** [comment]
I updated the template repository for prebuild.
https://github.com/gitpod-io/template-dotnet-core-cli-csharp/compare/master...to/shiftfs

**Comment by kylos101** [comment]
@utam0k I changed the status for this issue to blocked. Am I correct that you've provided a workaround, but, now we need a fix for shiftfs? If we need a fix for shiftfs for a long term solution, can you share a related link to an issue for shiftfs?

**Comment by utam0k** [comment]
@kylos101 Support for ubuntu kernel is required. But it won't be a quick fix, how about planting a workaround for the dotnet image?

**Comment by purkhusid** [comment]
Does it not make sense to add this workaround to the gitpod/workspace-base image? This bug could be affecting other workloads without you knowing.

**Comment by kylos101** [comment]
@utam0k can you try adding your workaround to [a custom dockerfile](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile), using this as a [base image](https://hub.docker.com/r/gitpod/workspace-dotnet)?

You'll need to test in core-dev (fuse) and production (shiftfs), to see if workspaces using the custom base image with your workaround work with both overlay file systems.

**Comment by utam0k** [comment]
> @utam0k can you try adding your workaround to [a custom dockerfile](https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile), using this as a [base image](https://hub.docker.com/r/gitpod/workspace-dotnet)?
> 
> You'll need to test in core-dev (fuse) and production (shiftfs), to see if workspaces using the custom base image with your workaround work with both overlay file systems.

I've improved the custom image to work in both environments.
https://github.com/gitpod-io/template-dotnet-core-cli-csharp/blob/to/shiftfs/.gitpod.Dockerfile

**Comment by kylos101** [comment]
@utam0k can you help me? Would it make sense to put the workaround in our dotnet chunk/base image https://github.com/gitpod-io/workspace-images/blob/main/chunks/tool-dotnet/Dockerfile, too? What you shared is a template that customers use for dotnet, but they don't have to necessarily use the template.

**Comment by utam0k** [comment]
@kylos101 I think this workaround should be included because .Net uses will always run into this problem with using SaaS. And  We don't know when this problem will be solved. So I have already sent out the PR.
https://github.com/gitpod-io/workspace-images/pull/820

> @utam0k can you help me? Would it make sense to put the workaround in our dotnet chunk/base image https://github.com/gitpod-io/workspace-images/blob/main/chunks/tool-dotnet/Dockerfile, too? What you shared is a template that customers use for dotnet, but they don't have to necessarily use the template.

**Comment by utam0k** [comment]
The dotnet image has been included in the workaround I suggested, so this issue was closed at once. Please feel free to open, up if you encountered the related problem.

**Comment by Craftzman7** [comment]
Dotnet is still broken for me. Getting the following output when running `dotnet build`
```
/usr/share/dotnet/sdk/6.0.202/Roslyn/Microsoft.CSharp.Core.targets(75,5): error MSB6004: The specified task executable location "/run/containerd/io.containerd.runtime.v2.task/k8s.io/8035f69012dabb060f7d71eee9aef568184b2ecf0f142075ebf3fc1ffd959a2a/rootfs/usr/share/dotnet/dotnet" is invalid. [/workspace/xxxxx/xxxxx.csproj]
```

**Comment by utam0k** [comment]
@Craftzman7 Thanks for your report. What tag do you use? If you use the `latest`, please use `gitpod/workspace-dotnet:2022-05-08-14-31-53` and give it try again 🙏

**Comment by Craftzman7** [comment]
> @Craftzman7 Thanks for your report. What tag do you use? If you use the `latest`, please use `gitpod/workspace-dotnet:2022-05-08-14-31-53` and give it try again 🙏 

Was using latest, After trying with that tag it seems to have worked.

**Comment by utam0k** [comment]
@Craftzman7 I'm glad to hear that. Sorry for my explanation was a shortage.

**Comment by bbhxwl** [comment]
> @Craftzman7 I'm glad to hear that. Sorry for my explanation was a shortage.

My project is net core 3 1 can't be used. It seems that it can only be 6.0

**Comment by utam0k** [comment]
@bbhxwl Thanks for your information. Do you have trouble with .Net 3.1?

**Comment by bbhxwl** [comment]
> @bbhxwl Thanks for your information. Do you have trouble with .Net 3.1?

Yes, I haven't succeeded

**Comment by bbhxwl** [comment]
> @bbhxwl Thanks for your information. Do you have trouble with .Net 3.1?

I don't know what specific steps to use?

**Comment by purkhusid** [comment]
@bbhxwl You need to use a custom docker image:
```
FROM gitpod/workspace-base

USER gitpod
# Dazzle does not rebuild a layer until one of its lines are changed. Increase this counter to rebuild this layer.
ENV TRIGGER_REBUILD=1

# Install .NET SDK (Current channel)
# Source: https://docs.microsoft.com/dotnet/core/install/linux-scripted-manual#scripted-install
ENV DOTNET_VERSION=3.1.419
RUN mkdir -p /home/gitpod/dotnet && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION --install-dir /home/gitpod/dotnet
ENV DOTNET_ROOT=/home/gitpod/dotnet
ENV PATH=/home/gitpod/dotnet:$PATH

# TODO(toru): Remove this hack when the kernel bug is resolved.
#             ref. https://github.com/gitpod-io/gitpod/issues/8901
RUN bash \
    && { echo 'if [ ! -z $GITPOD_REPO_ROOT ]; then'; \
        echo '\tCONTAINER_DIR=$(awk '\''{ print $6 }'\'' /proc/self/maps | grep ^\/run\/containerd | head -n 1 | cut -d '\''/'\'' -f 1-6)'; \
        echo '\tif [ ! -z $CONTAINER_DIR ]; then'; \
        echo '\t\t[[ ! -d $CONTAINER_DIR ]] && sudo mkdir -p $CONTAINER_DIR && sudo ln -s / $CONTAINER_DIR/rootfs'; \
        echo '\tfi'; \
        echo 'fi'; } >> /home/gitpod/.bashrc.d/110-dotnet
RUN chmod +x /home/gitpod/.bashrc.d/110-dotnet
```

If you don't know how to use the custom dockerfile you can see how here: https://www.gitpod.io/docs/config-docker

**Comment by yellowsink** [comment]
My script still works A-OK for me https://gist.github.com/yellowsink/79428ca1ef8dfa323315f914f1affd4f

**Comment by bbhxwl** [comment]
> @bbhxwl You need to use a custom docker image:
> 
> ```
> FROM gitpod/workspace-base
> 
> USER gitpod
> # Dazzle does not rebuild a layer until one of its lines are changed. Increase this counter to rebuild this layer.
> ENV TRIGGER_REBUILD=1
> 
> # Install .NET SDK (Current channel)
> # Source: https://docs.microsoft.com/dotnet/core/install/linux-scripted-manual#scripted-install
> ENV DOTNET_VERSION=3.1.419
> RUN mkdir -p /home/gitpod/dotnet && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION --install-dir /home/gitpod/dotnet
> ENV DOTNET_ROOT=/home/gitpod/dotnet
> ENV PATH=/home/gitpod/dotnet:$PATH
> 
> # TODO(toru): Remove this hack when the kernel bug is resolved.
> #             ref. https://github.com/gitpod-io/gitpod/issues/8901
> RUN bash \
>     && { echo 'if [ ! -z $GITPOD_REPO_ROOT ]; then'; \
>         echo '\tCONTAINER_DIR=$(awk '\''{ print $6 }'\'' /proc/self/maps | grep ^\/run\/containerd | head -n 1 | cut -d '\''/'\'' -f 1-6)'; \
>         echo '\tif [ ! -z $CONTAINER_DIR ]; then'; \
>         echo '\t\t[[ ! -d $CONTAINER_DIR ]] && sudo mkdir -p $CONTAINER_DIR && sudo ln -s / $CONTAINER_DIR/rootfs'; \
>         echo '\tfi'; \
>         echo 'fi'; } >> /home/gitpod/.bashrc.d/110-dotnet
> RUN chmod +x /home/gitpod/.bashrc.d/110-dotnet
> ```
> 
> If you don't know how to use the custom dockerfile you can see how here: https://www.gitpod.io/docs/config-docker

It works for me, thank you.
If I change the version, just change here?



```
ENV DOTNET_VERSION=3.1.419
```

**Comment by bbhxwl** [comment]
> > @bbhxwl You need to use a custom docker image:
> > ```
> > FROM gitpod/workspace-base
> > 
> > USER gitpod
> > # Dazzle does not rebuild a layer until one of its lines are changed. Increase this counter to rebuild this layer.
> > ENV TRIGGER_REBUILD=1
> > 
> > # Install .NET SDK (Current channel)
> > # Source: https://docs.microsoft.com/dotnet/core/install/linux-scripted-manual#scripted-install
> > ENV DOTNET_VERSION=3.1.419
> > RUN mkdir -p /home/gitpod/dotnet && curl -fsSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION --install-dir /home/gitpod/dotnet
> > ENV DOTNET_ROOT=/home/gitpod/dotnet
> > ENV PATH=/home/gitpod/dotnet:$PATH
> > 
> > # TODO(toru): Remove this hack when the kernel bug is resolved.
> > #             ref. https://github.com/gitpod-io/gitpod/issues/8901
> > RUN bash \
> >     && { echo 'if [ ! -z $GITPOD_REPO_ROOT ]; then'; \
> >         echo '\tCONTAINER_DIR=$(awk '\''{ print $6 }'\'' /proc/self/maps | grep ^\/run\/containerd | head -n 1 | cut -d '\''/'\'' -f 1-6)'; \
> >         echo '\tif [ ! -z $CONTAINER_DIR ]; then'; \
> >         echo '\t\t[[ ! -d $CONTAINER_DIR ]] && sudo mkdir -p $CONTAINER_DIR && sudo ln -s / $CONTAINER_DIR/rootfs'; \
> >         echo '\tfi'; \
> >         echo 'fi'; } >> /home/gitpod/.bashrc.d/110-dotnet
> > RUN chmod +x /home/gitpod/.bashrc.d/110-dotnet
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you don't know how to use the custom dockerfile you can see how here: https://www.gitpod.io/docs/config-docker
> 
> It works for me, thank you. If I change the version, just change here?
> 
> ```
> ENV DOTNET_VERSION=3.1.419
> ```

https://docs.microsoft.com/zh-cn/dotnet/core/install/linux-ubuntu
Can I install it with this?

**Comment by Craftzman7** [comment]
I can't install .NET versions other then 6.0. Would this ever be changed?

**Comment by utam0k** [comment]
> I can't install .NET versions other then 6.0. Would this ever be changed?

@Craftzman7 Thanks for your request. If you want, please create the issue or PR on https://github.com/gitpod-io/workspace-images 🙏

**Comment by utam0k** [comment]
@bbhxwl Hi, Were other versions available with custom images? If so, please let me know on https://github.com/gitpod-io/workspace-images/issues/831 🙏
