### ISSUE TITLE
Gitpod unusable again: high load averages

### ISSUE THREAD

**Issue by smacintyre** [gitpod-io/gitpod#8904]
### Bug description

Second day in a row with high load averages during the middle of the day. See #8895 for yesterday.

```
gitpod /workspace/nxity $ uptime
 11:44:58 up 1 day, 15:35,  0 users,  load average: 134.30, 111.88, 99.43
```

Can't save or use gitpod. This is really frustrating as my team depends of gitpod and are paying customers. But the lack of monitoring and stability is really making me question gitpod's viability. 

### Steps to reproduce

Open any repo.

### Workspace affected

All

### Expected behavior

It to work

**Comment by geropl** [comment]
Thx @smacintyre for reporting again! :pray:  This helped to:
 - identify a problem with our on-call process (esp. for abuse cases like this)
 - identify a new abuse pattern which just got rolled out to all clusters to prevent this from happen again
