### ISSUE TITLE
Add option to configure authProviders

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#8905]
The `authProviders` section of the config sets the Git integrations that are accessible for all on the system. This should be configurable in the KOTS config.

## Problem

If the installation detects no auth providers, it prompts you to add one. However, this one allows you to add one - if you add any more, they're "integrations" meaning they're only accessible for the user. If you want to configure multiple repos for all (for example, public GitHub/GitLab/Bitbucket, or a self-hosted/private instance), this will be impossible with the Gitpod dashboard

**Comment by AlexTugarev** [comment]
I don’t think that the problem described here really exists. First user of an installation is an admin which may add more Git Integrations.

OTOH configuration of generic providers is something we want to add to the dashboard, preferably in the admin section. Need to look up the GH issue for that.

**Comment by MrSimonEmms** [comment]
@AlexTugarev you're right. When I initially added my GitLab integration via the UI, it only added it to the "Git Integrations" section. Now I've logged out, it appears in the "Git providers" section

![image](https://user-images.githubusercontent.com/275848/159226823-37d7b8a8-8a60-4c53-bf04-9da4986f9b95.png)

It's probably a nice-to-have for the configuration to be in KOTS (especially as we support it via the Installer), but it's now not as high priority

**Comment by MrSimonEmms** [comment]
I'm going to propose that, as this is covered by the dashboard, it's not needed yet
