### ISSUE TITLE
Starting up custom Docker image fails

### ISSUE THREAD

**Issue by robertPiro** [gitpod-io/gitpod#891]
**Describe the bug**
Starting custom Docker image fails:
The error message is
`Error: (HTTP code 500) server error - stat /var/lib/docker/165536.165536/tmp: no such file or directory
Please file an issue if you think this is a bug.`

**To Reproduce**
create `.gitpod.yml` file with a single line 
```
image: 
   file: .gitpod.dockerfile
``` 
in github repo.

**Expected behavior**
Start-up a container using the image. Present files:
`Dockerfile`, `dockerfile`, `.gitpod.dockerfile` all containing some docker commands.

**Additional Information**
Followed https://www.gitpod.io/docs/42_config_docker/

**Comment by JesterOrNot** [comment]
see #890 similar issue

**Comment by robertPiro** [comment]
I close the issue then. #890 sounds very much like my problem.
