### ISSUE TITLE
Unable to run Vue

### ISSUE THREAD

**Issue by kunxin-chor** [gitpod-io/gitpod#8910]
### Bug description

When attempting to run a Vue application with `npm run serve`, nothing is rendered and there's a websocket error in the console.

![image](https://user-images.githubusercontent.com/14900791/159205229-1c4aed52-b1c0-49d3-a0c4-223b2ba3b28f.png)

### Steps to reproduce

1. Create a new Github repo
2. Launch gitpod
3. Open terminal, and install Vue services with `npm install -g @vue/cli`
4. Create a new vue project with `vue create test`
5. Edit the `vue.config.js` to the following:
```
module.exports = {
  transpileDependencies: true,
  devServer: {
    historyApiFallback: true,
    allowedHosts: "all",
}}
```
6. Launch the app with `vue serve`
7. Open the console to see the error messages
8. Nothing will be rendered

### Workspace affected

https://kunxinchor-vuetesting-vc5qr62r5bu.ws-us38.gitpod.io/

### Expected behavior

Should see this:
![image](https://user-images.githubusercontent.com/14900791/159205555-d5bd6005-5c7e-49d1-87de-f5d56b304fd3.png)

### Example repository

Workspace: https://8080-kunxinchor-vuetesting-vc5qr62r5bu.ws-us38.gitpod.io/
Git repo:  https://github.com/kunxin-chor/vue-testing

**Comment by akosyakov** [comment]
You can also use the local app if you don't want to change project configuration: https://www.gitpod.io/blog/local-app It exposes services running in GItpod workspace on localhost as you will have them usually with local dev.

**Comment by felladrin** [comment]
Hey, @kunxin-chor. Did any of the solutions above work for you?

**Comment by kunxin-chor** [comment]
> The problem is that the WebSocket is trying to connect to the same port indicated by the Vue DevServer (by default 8080).
> 
> Because the app is loaded through HTTPS on Gitpod, Vue uses WSS protocol for the WebSocket connection. But the WebSocket is trying to connect to `wss://8080-kunxinchor-vuetesting-vc5qr62r5bu.ws-us38.gitpod.io:8080/ws` when it should be connecting to `wss://8080-kunxinchor-vuetesting-vc5qr62r5bu.ws-us38.gitpod.io:443/ws`.
> 
> So for it to run correctly, `vue.config.js` needs to have `client.webSocketURL.port` set to 443 when running on Gitpod. And one easy way to check if it's running on Gitpod is by checking for [an environment variable that is set automatically by Gitpod and is guaranteed to exist](https://www.gitpod.io/docs/environment-variables/#default-environment-variables) (e.g. `GITPOD_WORKSPACE_ID`). And for non-Gitpod environments, we leave the port as `undefined` to use the same port as the Vue HTTP DevServer.
> 
> ```js
> module.exports = {
>   devServer: {
>     allowedHosts: "all",
>     client: {
>       webSocketURL: {
>         port: process.env.GITPOD_WORKSPACE_ID ? 443 : undefined,
>       },
>     },
>   },
> };
> ```

Hi this works for me, thanks.
