### ISSUE TITLE
Remove "plans" section from the settings page in a self-hosted instance

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#8916]
The "plans" section exists for a self-hosted instance. Arguably, this makes no sense - the self-hosted advertising implies (and is my understanding) that there is no limitation placed on a user's hourly usage limitations.

If the current understanding is that this should remain, this should be made clearer in the self-hosting payment options page. However, I suspect that would be deeply unpopular with users working on the basis that they're paying for the cluster so shouldn't have usage time limited

![image](https://user-images.githubusercontent.com/275848/159281681-fe36e8f6-8ed6-4bb3-acfe-20fbde3e9b34.png)

**Comment by jankeromnes** [comment]
Stealing this issue as I've already started working on it in https://github.com/gitpod-io/gitpod/pull/8041

Also, since my PR is growing a bit too large, and some bits aren't finished yet, I'll splice out the fix into a separate PR.
