### ISSUE TITLE
Discover startup times for workspaces using old versions of workspace-full

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8922]
## Is your feature request related to a problem? Please describe

We use a variety of older versions of `workspace-full` in workspace images persisted to GCR. If they are used to restart workspaces often, chances are they will pull more (especially on new nodes) because new nodes only cache the latest workspace-full. 

## Describe the behaviour you'd like

Study data in our database, to produce info to help us consider whether a change is needed. For example, we may want to forcibly rebuild workspace images using a predictable version of workspace-full (perhaps stored in a config map?), so that we can leverage cached images on nodes in workspace clusters.

How many workspaces would benefit from this change in the last quarter?
How much time would they have saved on N - 1 starts (N = total number of starts, -1 because that one was old and would have incurred an image build with this proposed new feature).

## Additional context

The output of this issue is to be another issue, not an implementation of this change.

**Comment by princerachit** [comment]
>How many workspaces would benefit from this change in the last quarter?

We created multiple clusters in last quarter and also published multiple versions of docker images. It is very difficult to find which workspaces started in last quarter that did not use the workspace-full latest at the time when it started.

However, I think we can do that starting with the clusters that are running right now.

**Comment by princerachit** [comment]
This is the result of queries that I ran, the tag `37fa6b72cbb0b2b1459a59acbe862f31a820b2db62d740d3ac57fb93d357526a` is the current latest:

```sql
SELECT count(*) FROM d_b_workspace_instance where region like '%38%' and workspaceImage != 'eu.gcr.io/gitpod-dev/workspace-images:37fa6b72cbb0b2b1459a59acbe862f31a820b2db62d740d3ac57fb93d357526a' and workspaceImage like 'eu.gcr.io/gitpod-dev/workspace-images%'
```

#### Result: 150801

```sql
SELECT count(*) FROM d_b_workspace_instance where region like '%38%' and workspaceImage = 'eu.gcr.io/gitpod-dev/workspace-images:37fa6b72cbb0b2b1459a59acbe862f31a820b2db62d740d3ac57fb93d357526a'
```
#### Result: 272477


### Percent of workspaces that do not use latest image
`150801*100/(272477 + 150801) = 35%`


Since we cache older versions of workspace images too, the number of workspace images for which actual pull occurs is less.

**Comment by princerachit** [comment]
## Average Start Times
### 1. latest tag

```sql
SELECT AVG(DIFF) FROM ( SELECT TIMESTAMPDIFF(SECOND, creationTime, startedTime ) as DIFF from d_b_workspace_instance where region like '%38%' and workspaceImage = 'eu.gcr.io/gitpod-dev/workspace-images:37fa6b72cbb0b2b1459a59acbe862f31a820b2db62d740d3ac57fb93d357526a' ) MYTABLE;
```

#### Result 15.6665s

### 2. Other tags (includes cached)

```sql
SELECT AVG(DIFF) FROM ( SELECT TIMESTAMPDIFF(SECOND, creationTime, startedTime ) as DIFF from d_b_workspace_instance where region like '%38%' and workspaceImage != 'eu.gcr.io/gitpod-dev/workspace-images:37fa6b72cbb0b2b1459a59acbe862f31a820b2db62d740d3ac57fb93d357526a' and workspaceImage like 'eu.gcr.io/gitpod-dev/workspace-images%') MYTABLE;
```

#### Result 62.4983s

**Comment by princerachit** [comment]
# Average startup times

Note: The workspace ids with prefix `prince-` are the ones which were created using cached workspace-full images in VM.

## Workspace-full cached images in VM image

The below query is for past 15 days for all `gen-38` clusters
```sql
SELECT 
    AVG(TIMESTAMPDIFF(SECOND,
        wsi.creationTime,
        wsi.startedTime)) AS DIFF
FROM
    d_b_workspace ws,
    d_b_workspace_instance wsi
WHERE
    ws.creationTime > (NOW() - INTERVAL 15 DAY)
        AND wsi.workspaceId = ws.id
        AND wsi.region LIKE '%38%'
        AND ws.baseImageNameResolved LIKE 'docker.io/gitpod/workspace-full%'
        AND ws.baseImageNameResolved NOT IN (SELECT 
            baseImageNameResolved
        FROM
            d_b_workspace
        WHERE
            id IN ('princerachit-empty-wz4tdiq0ilm' , 'princerachit-empty-k21abpg6bnu',
                'princerachit-empty-rv86p0s16ad',
                'princerachit-empty-hn5oos6bntl',
                'princerachit-empty-fxo8x0j9wka',
                'princerachit-empty-qd2mkb1nak8'));
```
### Result
35.7353s

## Workspace-full non cached images in VM

```sql
SELECT 
    AVG(TIMESTAMPDIFF(SECOND,
        wsi.creationTime,
        wsi.startedTime)) AS DIFF
FROM
    d_b_workspace ws,
    d_b_workspace_instance wsi
WHERE
    ws.creationTime > (NOW() - INTERVAL 15 DAY)
        AND wsi.workspaceId = ws.id
        AND wsi.region LIKE '%38%'
        AND ws.baseImageNameResolved LIKE 'docker.io/gitpod/workspace-full%'
        AND ws.baseImageNameResolved IN (SELECT 
            baseImageNameResolved
        FROM
            d_b_workspace
        WHERE
            id IN ('princerachit-empty-wz4tdiq0ilm' , 'princerachit-empty-k21abpg6bnu',
                'princerachit-empty-rv86p0s16ad',
                'princerachit-empty-hn5oos6bntl',
                'princerachit-empty-fxo8x0j9wka',
                'princerachit-empty-qd2mkb1nak8'));
```

### Result
16.335s

## Conclusion
Non cached full images are taking twice the time to start on an average.

**Comment by kylos101** [comment]
Hi @princerachit :wave:  ,

Thank yous!

Can you share how you got the list of cached images, and which ones you used in the study? The query suggests we cached 6 workspace-full images, but I just want to double check.

Do you mean 16s for cached, and 35s for non-cached? If yes, it is currently backwards. 

I think it would help, if you included a count and standard deviation, so we can see total workspaces being included in the study, as well as how much fluctuation there is.

For example, for the life of gen38 (including 38, 38xl and 38xl2) how many workspaces did we start? What percentage of those were non-cached? I ask to get a feel for how many workspaces and user experiences have been impacted.

And lastly (but most important), can you create a [new issue](https://github.com/gitpod-io/gitpod/issues/new?assignees=&labels=&template=feature_request.md&title=) (referencing this one) for an enhancement to image-builder to remedy this? After which I think you're good and can close this issue. :smile:

**Comment by princerachit** [comment]
>Do you mean 16s for cached, and 35s for non-cached? If yes, it is currently backwards.

Fixed the heading

> Can you share how you got the list of cached images, and which ones you used in the study? The query suggests we cached 6 workspace-full images, but I just want to double check.

I got it from [our packer image repo](https://github.com/gitpod-io/gitpod-packer-gcp-image/blob/c76c07499dbe32bfc8f68f3b6197250b54bf5b79/airgap-from-stats.txt#L2-L7).


>I think it would help, if you included a count and standard deviation, so we can see total workspaces being included in the study, as well as how much fluctuation there is.
For example, for the life of gen38 (including 38, 38xl and 38xl2) how many workspaces did we start? What percentage of those were non-cached? I ask to get a feel for how many workspaces and user experiences have been impacted

Sure, I will include it.

**Comment by princerachit** [comment]
## Workspaces without cached image

```sql
SELECT 
    COUNT(wsi.id), wsi.region
FROM
    d_b_workspace AS ws,
    d_b_workspace_instance AS wsi
WHERE
    ws.creationTime > (NOW() - INTERVAL 15 DAY)
        AND wsi.workspaceId = ws.id
        AND wsi.region LIKE '%38%'
        AND ws.baseImageNameResolved LIKE 'docker.io/gitpod/workspace-full%'
        AND ws.baseImageNameResolved NOT IN (SELECT 
            baseImageNameResolved
        FROM
            d_b_workspace
        WHERE
            id IN ('princerachit-empty-wz4tdiq0ilm' , 'princerachit-empty-k21abpg6bnu',
                'princerachit-empty-rv86p0s16ad',
                'princerachit-empty-hn5oos6bntl',
                'princerachit-empty-fxo8x0j9wka',
                'princerachit-empty-qd2mkb1nak8'))
GROUP BY wsi.region;
```

### Result
```json
{  "COUNT_28_wsi_2e_id_29_": "890",  "region": "eu38"}
{  "COUNT_28_wsi_2e_id_29_": "17",  "region": "eu38xl"}
{  "COUNT_28_wsi_2e_id_29_": "3668",  "region": "us38"}
{  "COUNT_28_wsi_2e_id_29_": "175",  "region": "us38xl"}
{  "COUNT_28_wsi_2e_id_29_": "182",  "region": "us38xl2"}
```
4932
## Workspaces with cached image

```sql
SELECT 
    COUNT(wsi.id), wsi.region
FROM
    d_b_workspace AS ws,
    d_b_workspace_instance AS wsi
WHERE
    ws.creationTime > (NOW() - INTERVAL 15 DAY)
        AND wsi.workspaceId = ws.id
        AND wsi.region LIKE '%38%'
        AND ws.baseImageNameResolved IN (SELECT 
            baseImageNameResolved
        FROM
            d_b_workspace
        WHERE
            id IN ('princerachit-empty-wz4tdiq0ilm' , 'princerachit-empty-k21abpg6bnu',
                'princerachit-empty-rv86p0s16ad',
                'princerachit-empty-hn5oos6bntl',
                'princerachit-empty-fxo8x0j9wka',
                'princerachit-empty-qd2mkb1nak8'))
GROUP BY wsi.region;
```

### Result
```json
{  "COUNT_28_wsi_2e_id_29_": "29945",  "region": "eu38"}
{  "COUNT_28_wsi_2e_id_29_": "1635",  "region": "eu38xl"}
{  "COUNT_28_wsi_2e_id_29_": "243935",  "region": "us38"}
{  "COUNT_28_wsi_2e_id_29_": "4439",  "region": "us38xl"}
{  "COUNT_28_wsi_2e_id_29_": "7745",  "region": "us38xl2"}
```

287699

**Comment by princerachit** [comment]
## Images not using workspace full

```sql
SELECT 
    COUNT(wsi.id), wsi.region
FROM
    d_b_workspace AS ws,
    d_b_workspace_instance AS wsi
WHERE
    ws.creationTime > (NOW() - INTERVAL 15 DAY)
        AND wsi.workspaceId = ws.id
        AND wsi.region LIKE '%38%'
        AND ws.baseImageNameResolved NOT LIKE 'docker.io/gitpod/workspace-full%'
GROUP BY wsi.region;

```

### Result

```json
{  "COUNT_28_wsi_2e_id_29_": "24947",  "region": "eu38"}
{  "COUNT_28_wsi_2e_id_29_": "4501",  "region": "eu38xl"}
{  "COUNT_28_wsi_2e_id_29_": "63826",  "region": "us38"}
{  "COUNT_28_wsi_2e_id_29_": "7305",  "region": "us38xl"}
{  "COUNT_28_wsi_2e_id_29_": "12052",  "region": "us38xl2"}
```

**Comment by princerachit** [comment]
I am closing this issue @kylos101 as the number of workspaces dependent on workspace-full which is not cached is very less and I can;t think of any follow up work on this. This issue was for investigation and a follow up action would have been needed if there were significant % of workspaces being affected.
