### ISSUE TITLE
Workspace stopped working

### ISSUE THREAD

**Issue by spoenemann** [gitpod-io/gitpod#893]
**Describe the bug**
While working in a workspace, the Theia status bar turned yellow. I went to the Gitpod dashboard, but it was empty. After logging in again, I could see that the workspace was stopped, so I had to restart it.

**Expected behavior**
A workspace should not stop while working.

**Additional Information**
Workspace id: f5b9412f-ebd5-4f8d-b449-9ef095f5f330 (theia-ide/extension-registry - master)

**Comment by JesterOrNot** [comment]
Did you go offline?

**Comment by spoenemann** [comment]
No
