### ISSUE TITLE
Why does app bind to workspace name instead of 0.0.0.0 ?

### ISSUE THREAD

**Issue by kevinadhiguna** [gitpod-io/gitpod#8934]
### Bug description

Hi, I have a NodeJS-Express app that I try to bind to 0.0.0.0, but when I run it in Gitpod, the hostname becomes workspace name instead of 0.0.0.0 :

![code](https://user-images.githubusercontent.com/43397636/159661246-a3788eae-89b0-4b30-98f3-d930531c3937.png)

This is the `.env` in which I set hostname to 0.0.0.0 and port to 5000 :

![environment vairables](https://user-images.githubusercontent.com/43397636/159661651-03293574-36c6-4460-a075-b31c173ab8f3.png)

### Steps to reproduce

1. Create a new workspace using : `https://gitpod.io/#<repository_name>` (https://gitpod.io/#https://github.com/kevinadhiguna/jiyu).
2. Open the workspace.
3. Change directory to `ip-getter` :  `cd ip-getter`
4. Install dependencies (node_modules) : `yarn`
5. Start the app : `yarn start`
6. See the log above that says hostname is workspace name (`kevinadhiguna-jiyu-tyali2phkgh`) instead of `0.0.0.0`.

### Workspace affected

kevinadhiguna-jiyu-tyali2phkgh

### Expected behavior

I want my app to run on 0.0.0.0:5000 instead of binding to workspace name.

This is a successful screenshot of the app : 

![image](https://user-images.githubusercontent.com/43397636/159663131-6a6b5d36-9b20-4f97-b120-579cde8b3e74.png)

### Example repository

This is the source code : https://github.com/kevinadhiguna/jiyu/tree/master/ip-getter.

### Anything else?

It would be great if you tell me what I was doing wrong in order to solve this problem. Any suggestion is appreciated.

**Comment by kevinadhiguna** [comment]
In my opinion, this also causes trouble when running app using docker-compose as it can not get address :

![image](https://user-images.githubusercontent.com/43397636/159664462-9ef8c36d-ad46-434d-9bc7-819af506af69.png)

Here is the file : [docker-compose.yml](https://github.com/kevinadhiguna/jiyu/blob/master/ip-getter/docker-compose.yml).

**Comment by kevinadhiguna** [comment]
> Worth checking our out? https://www.gitpod.io/docs/command-line-interface#env

Thanks for your reply, but it still did not work for me..

![image](https://user-images.githubusercontent.com/43397636/159841594-dbec5161-67a6-4256-ba0b-1eff0253b89d.png)

**Comment by axonasif** [comment]
Hey @kevinadhiguna, you will need to install direnv, I took the moment to setup an starting point with Gitpod for you 😄 
https://github.com/kevinadhiguna/jiyu/pull/7

**Comment by kevinadhiguna** [comment]
Thanks @axonasif !

However, when I opened my workspace and ran `docker-compose -f .gitpod.yml up -d`, it displayed :
```bash
gitpod /workspace/jiyu (master) $ docker-compose -f .gitpod.yml up -d
WARN[0000] The "dir" variable is not set. Defaulting to a blank string. 
WARN[0000] The "dir" variable is not set. Defaulting to a blank string. 
(root) Additional property image is not allowed
```

**Comment by axonasif** [comment]
Hey @kevinadhiguna, again, it's not something to do with Gitpod. Please refer to the Docker reference docs 😄 
You will have to explicitly pass on HOST environment variables into your docker containers. It's just how docker is built by design to avoid unexpected changes in the containers.
