### ISSUE TITLE
Terminal character display issue in firefox

### ISSUE THREAD

**Issue by SimonSiefke** [gitpod-io/gitpod#8935]
### Bug description

![terminal-display-issue](https://user-images.githubusercontent.com/23744935/159673660-ab714d0b-c037-4ad4-95df-755bb0539920.png)

Some characters in the terminal have an odd font-family/font-color and a black background around them like `SOCKET_TIMEOUT` or `   /home/gitpod/.npm/_logs/2022-03-23T09_59_51_876Z-debug.log`

### Steps to reproduce

1. Use Firefox
2. Have an invalid package json, like `{`
3. Run `npm ci`
4. npm will fail and print the path to the debug log, the path looks weird like in the screenshot above

### Expected behavior

Terminal characters look normal.

### Anything else?

It seems to be related to underscores: When an underscore is before a letter, the letter is displayed weird.

**Comment by akosyakov** [comment]
moved to upstream: https://github.com/microsoft/vscode/issues/158497
