### ISSUE TITLE
Support json keys as credentials to access private registries

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#8938]
## Is your feature request related to a problem? Please describe

As a gitpod user who wants to use private registries to pull images, I want to use my json key instead of plain username:password to configure registry access. i.e. my password could be a json e.g. service account key of google cloud.

With https://github.com/gitpod-io/gitpod/pull/8550 a support for using username:password was added but it fails when the auth config passed is built using a json key e.g.
```console
echo $key | docker login -u _json_key --password-stdin
```

## Describe alternatives you've considered

NA

### Failure
<img width="2558" alt="image" src="https://user-images.githubusercontent.com/32481722/159685945-6ec1a05a-1c51-4a62-9487-ac24fc76b779.png">

### Private image

```console
europe-docker.pkg.dev/prince-tf-experiments/dazzle/workspace-images:base
```

**Comment by kylos101** [comment]
@princerachit can you add this to our inbox too?

**Comment by princerachit** [comment]
The issue is due to the way we decode and split the auth string in our code. In the image-builder-mk3 we split by colon which results the json to get split into multiple strings.
https://github.com/gitpod-io/gitpod/blob/6913b4fb2b6bfa4e1149efd5105e005d9d380d4c/components/image-builder-mk3/pkg/auth/auth.go#L210-L215

Due to the check at line 211 the password is never set. This result in the auth string being used for bearer token authentication method instead of basic authentication which results in a 401 error.

When I change above lines to the following to check if this string can be split into at least two string and then treat `segs[1] `as password. image-builder-mk3 succeeds in creation of imagebuild pods.
```go
	if err == nil {
		segs := strings.SplitN(string(dec), ":", 2)
		if len(segs) == 2 {
			res.Username = segs[0]
			res.Password = segs[1]
		}
	}
```

While creating the imagebuild pods mk3 sets the `WORKSPACEKIT_BOBPROXY_ADDITIONALAUTH` env variable which contains both user passs as well as the auth string.

https://github.com/gitpod-io/gitpod/blob/6913b4fb2b6bfa4e1149efd5105e005d9d380d4c/components/image-builder-mk3/pkg/orchestrator/orchestrator.go#L384-L385 

I suspect our credentials setting login involving above env var is causing an issue where it does not use the user and password but instead tries to use auth string for bearer token authentication.

I will debug this further. The [telepresence](https://github.com/gitpod-io/gitpod/blob/6913b4fb2b6bfa4e1149efd5105e005d9d380d4c/components/image-builder-mk3/telepresence.sh#L3) script is broken for image builder. Maybe fixing it then debugging is the right way to proceed

**Comment by princerachit** [comment]
I have created configuration to debug this issue locally: https://github.com/gitpod-io/gitpod/tree/prs/json-key/components/image-builder-bob#how-to-try-locally

**Comment by princerachit** [comment]
I found another bug with this implementation and have created a separate issue https://github.com/gitpod-io/gitpod/issues/10089
