### ISSUE TITLE
install gcloud tools to the default gitpod container

### ISSUE THREAD

**Issue by eng-dibo** [gitpod-io/gitpod#8939]
## Describe the behaviour you'd like
install google cloud tools in the default gitpod container, so projects could be deployed to the most used cloud platform

gcloud is needed for many services such as cloud storage, container registry, cloud run and many more. so it is needed by many developers

here is the installation guide from google
https://cloud.google.com/sdk/docs/install

**Comment by SAHRIYahyaAbdelkadouss** [comment]
tried running the commands of installation in the .gitpod.yaml but it didn't work

**Comment by salaboy** [comment]
I got it working here.. feel free to drop me a message if you are interested.. 
The main problem that I am finding is that there should be a way to do `gcloud init` without an interactive mode to login

**Comment by axonasif** [comment]
You could use [dotfiles](https://www.gitpod.io/docs/config-dotfiles) feature of to auto install gcloud cli on every workspace. I have it setup on my dotfiles this way:
- https://github.com/axonasif/dotsh/blob/main/docs/PERSISTING_AUTH.md#gcloud

**Comment by 0xJem** [comment]
> I got it working here.. feel free to drop me a message if you are interested.. The main problem that I am finding is that there should be a way to do `gcloud init` without an interactive mode to login

@salaboy : For the benefit of everyone who's coming across this issue, could you share the method you using to install the gcloud tools using gitpod.yaml? Thanks!

**Comment by 0xJem** [comment]
One approach I've seen is to use a Docker image, see: https://github.com/vfarcic/gitpod-production

**Comment by salaboy** [comment]
@0xJem yeah.. that's the way that I used.. just installing it using a Dockerfile but that sucks.. because you cannot automate the login. I would love to see a tutorial on how people can automate that login using Env variables
