### ISSUE TITLE
Not capable to open template to start working as new project

### ISSUE THREAD

**Issue by nitr-am** [gitpod-io/gitpod#894]
**Describe the bug**

Not capable to open template to start working as new project.

**To Reproduce**

It is supposed t work the way it is already.

**Expected behavior**

It should open as a new envioronment.

**Additional Information**

**Comment by svenefftinge** [comment]
Which project did you try?

**Comment by nitr-am** [comment]
hey,

It is solved already. It was a bug on code institute's template.

Thank you
________________________________
