### ISSUE TITLE
Dead link in Readme

### ISSUE THREAD

**Issue by jfowl** [gitpod-io/gitpod#8943]
### Bug description

The link "root & docker" is dead:

![image](https://user-images.githubusercontent.com/15788906/159784592-b3486616-fd09-4aef-86b5-880fe4969c58.png)

### Steps to reproduce

View Readme

**Comment by felladrin** [comment]
Thanks for reporting it, @jfowl!

I guess it should now point to https://www.gitpod.io/docs/config-docker#configure-a-custom-dockerfile, what do you think @jankeromnes?
