### ISSUE TITLE
Can't create new workspaces on a repo

### ISSUE THREAD

**Issue by tbfleming** [gitpod-io/gitpod#895]
**Describe the bug**

Starting a new workspace on a repo which was formerly working causes this error:

```
Error: Request createWorkspace failed with message: 5 NOT_FOUND: cannot resolve base image: not found
```

**To Reproduce**

Open https://gitpod.io/#https://github.com/EOSIO/eosio-web-ide

**Expected behavior**

**Additional Information**

**Comment by 32leaves** [comment]
Hi @tbfleming, this is indeed a bug on our end introduced with the latest update. We should have this fixed within the next few hours.

**Comment by 32leaves** [comment]
We have just deployed the fix and the repo works again as intended. Again, sorry for the inconvenience.
