### ISSUE TITLE
workspace prebuild not working

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#8954]
### Bug description

workspace prebuild show sucess, but actually not working

### Steps to reproduce

https://github.com/gengjiawen/ts-scaffold

```yml
  - init: echo "export CI=false" >> ~/.bashrc && source ~/.bashrc && yarn && yarn test
  - init: sudo npm i -g npm-check-updates esvu && yes | esvu && exit
```

second init script show success, but not working.

```console
XS ❯ Testing...
XS ✔ Installed with bin entries: xs
exit

🤙 This task ran as a workspace prebuild

gitpod /workspace/ts-scaffold (master) $ v8
bash: v8: command not found
```

**Comment by axonasif** [comment]
Hey @gengjiawen, please see https://www.gitpod.io/docs/prebuilds#workspace-directory-only

You should use a custom dockerfile instead and that's the recommended approach for this 👍

**Comment by gengjiawen** [comment]
> Hey @gengjiawen, please see [gitpod.io/docs/prebuilds#workspace-directory-only](https://www.gitpod.io/docs/prebuilds#workspace-directory-only)
> 
> You should use a custom dockerfile instead and that's the recommended approach for this 👍

To use global installs like ‘npm install -g’, we suggest using a custom Dockerfile or a before task, which runs before the init task, and runs again before the command task.

`before` also works ?

**Comment by axonasif** [comment]
Yeah, `before:` works.
