### ISSUE TITLE
Investigate Issue With 'make auth' Command in EKS Guide

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#8958]
### Bug description

This has been reported twice in the last few days in Discord.

* https://discord.com/channels/816244985187008514/816246578594840586/956764654791712858
* https://discord.com/channels/816244985187008514/931200235601023016/956192651244351600

It seems when running `make auth` you will get an error about the `configmap` not being found:

```
make auth

Installing auth providers...
Using the auth providers configuration file: auth-providers-patch.yaml
Error from server (NotFound): configmaps "auth-providers-config" not found
```

I've had one user run `kubectl --kubeconfig .kubeconfig get configmap` and we noticed the `auth-providers-config` configmap was nowhere to be found. This obviously presents a problem since the `make auth` command tries [to patch it](https://github.com/gitpod-io/gitpod-eks-guide/blob/1e87e66f2b054f836346f056f928814ec38149c6/setup.sh#L289).

My suggestion here is to ensure that the necessary `configmap` is created during the installation, or that instead of patching we create the `configmap` when `make auth` is run.

### Steps to reproduce

1. Go through [the EKS guide](https://github.com/gitpod-io/gitpod-eks-guide) to setup a new instance of Gitpod.
2. Once the instance is setup and fully provisioned setup your `[auth-providers-patch.yaml](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/auth-providers-patch.yaml)` file.
3. Run `make auth` and observe the error about the `auth-providers-config` configmap not being found.

### Expected behavior

I would expect that when running the command as noted in the guide that it would work and the authentication information be added.

### Anything else?

You can run the following:

```
kubectl --v=5 -n default create configmap auth-providers-config --from-file=configMap
```

and then run `make auth`. This workaround was noted in [this Discord thread](https://discord.com/channels/816244985187008514/816246578594840586/956764654791712858).

cc. @MrSimonEmms 🍊

**Comment by lucasvaltl** [comment]
We want to replace the EKS guide with [reference architectures](https://www.gitpod.io/docs/self-hosted/latest/reference-architecture) (EKS coming soon). Hence will close this ticket.
