### ISSUE TITLE
Add "help me" button when workspace errors

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#8959]
## Is your feature request related to a problem? Please describe

Whilst talking with @corneliusludmann and @easyCZ, we were talking about how often workspaces fail with unclear error messages. Having a "help me" button which could guide the user to support (Discord etc) and trigger a Replicated support bundle so we have relevant logs

This would primarily be a self-hosted trigger, but may have benefits for SaaS

## Describe the behaviour you'd like

A help me button that gives FAQs, advice for better support and auto-upload of logs

**Comment by axonasif** [comment]
Could we also make it detect if we have an active internal/gitpodstatus incident and let the user know about it on the error page 🙏 ?

This would hopefully prevent the mass duplicate issue opening and/or discord+email reports during big incidents.
