### ISSUE TITLE
White space is removed from line ending in Markdown

### ISSUE THREAD

**Issue by nicekiwi** [gitpod-io/gitpod#896]
**Describe the bug**
When saving a Markdown file the spaces at the end of a line that force a new line are removed. 

**To Reproduce**
Add two lines of text to a markdown file, one below the other with the first using 2 spaces to force a new line. Then save the file. The whitespace has been removed. 

**Expected behavior**
.md and .markdown files should retain their whitespace

**Comment by nicekiwi** [comment]
Whitespace removal is useful in other files, but not in .md files and I'm not sure there's a way to filter which file types have it removed or not.

**Comment by svenefftinge** [comment]
Can you share the project you are working on? It might have to do with the settings.

**Comment by nicekiwi** [comment]
https://gitpod.io/#https://github.com/nicekiwi/php-docker

**Comment by svenefftinge** [comment]
Sorry, I cannot reproduce it. Can you verify that it still happens and also check your user settings?

**Comment by nicekiwi** [comment]
Hmm, I'll make a screencast.

**Comment by unode** [comment]
Just experienced this in https://github.com/carpentries-incubator/building-websites-with-jekyll-and-github-or-gitlab/pull/100

The option:
```
Trim Auto Whitespace
- [x] Remove trailing auto inserted whitespace
```
was enabled. Seems to be a default.
Tried disabling it now to see if it helps.

If indeed this option controls the auto trimming behaviour, is there any way this can be disabled for specific file extensions or MIME types?

**Comment by akosyakov** [comment]
@unode It looks like the editor config is configured to remove whitespaces for all file types in this repo. If you want to disable it for `md` please add trim_trailing_whitespace = false in [*.md]  section.

There is also `editor.trimAutoWhitespace` setting in IDE, which can be configured per language, i.e.:
```json
"editor.trimAutoWhitespace": true, // default
"[markdown]": {
    "editor.trimAutoWhitespace": false
}
```

But it is overridden by the editor config extension in case of your repo.

**Comment by unode** [comment]
@akosyakov ah! that file was created long before gitpod started to be used. I wasn't aware it could have an effect.
I can confirm that adding `trim_trailing_whitespace = false` to the `[*.md]` section fixes the issue.

As for the IDE setting, I've added:
```
{
  "editor.trimAutoWhitespace": true, // default
  "[markdown]": {
    // Show invisibles
    "editor.renderWhitespace": "all",
    // Enable wordWrap for markdown files
    "editor.wordWrap": "on",
    "editor.trimAutoWhitespace": false
  }
}
```
to `~/.theia/settings.json` as per https://www.gitpod.io/docs/config-editor/ but it doesn't seem to be taking effect.
Does the presence of a `.editorconfig` override any existing setting?

**Comment by akosyakov** [comment]
> Does the presence of a .editorconfig override any existing setting?

Yes, i think it is the case.

> GitPod's documentation doesn't seem to mention .editorconfig...

That's a good point. It would be good to document that Gitpod is distributed with the editor config extension and it will override settings. You can contribute it by clicking the pencil icon in docs.
