### ISSUE TITLE
Gitpod-Button is misplaced for empty Repos

### ISSUE THREAD

**Issue by Cahllagerfeld** [gitpod-io/gitpod#8963]
### Bug description

When creating a new repo, the Gitpod-Button slips to the very right of the screen

### Steps to reproduce

1. Create a new Repo and leave it empty

### Expected behavior

Button should be aligned as usual

### Anything else?

<img width="1912" alt="grafik" src="https://user-images.githubusercontent.com/43843195/160243819-f9f82f9c-a606-4a3f-b83d-47dd82a6c3bb.png">

**Comment by gtsiolis** [comment]
Closing this as duplicate of https://github.com/gitpod-io/gitpod/issues/9435 which seems to include screenshots with more use cases.

Thanks, @Cahllagerfeld! Cc @jankeromnes
