### ISSUE TITLE
More options to lock down an instance (no public ports)

### ISSUE THREAD

**Issue by AuxiliumCDNG** [gitpod-io/gitpod#8964]
## Is your feature request related to a problem? Please describe
It could be dangerous for organizations to allow any user to host whatever they want. Especially in countries with strict regulations (like Germany; you could face fines in the ten-thousands if you don't have an imprint).

## Describe the behaviour you'd like
There should be an option in the config file to globally disable features like making ports public (main requests) (plus any other aspect that comes to mind; I could only come up with the port thing...).

## Describe alternatives you've considered
You could lock gitpod behind a private network or some kind of external authentication so that you can control access on the network level. That would be very impractical for inexperienced users, however, or when there are limiting factors in your network (e.g. another firewall you cannot control).

## Additional context
Nothing yet :)

**Comment by loujaybee** [comment]
Relates to: https://github.com/gitpod-io/gitpod/issues/6731

**Comment by atduarte** [comment]
@AuxiliumCDNG thanks for creating the issue. To make sure I didn't miss anything: Your request would be only applicable to self-hosted use cases, right?

**Comment by AuxiliumCDNG** [comment]
@atduarte  Yes, a simple toggle on the config page of the kots dashboard that allows or denies the usage of public ports but still allows for private ports would be enough for me...
I don't know how one would use such a feature with your hosted version so it's a purely self-hosted feature in my mind...
