### ISSUE TITLE
Workspace not running properly

### ISSUE THREAD

**Issue by sakshi1499** [gitpod-io/gitpod#897]
Hi, I have been working on gitpod for a week or so and it was running perfectly fine until last night. Now for some reason it isn't serving on port 3000 and other ports namely 6379 and 5432 even when exposed just show 'still loading' alert and empty page or that it did not respond. I went through the issues posted and so re clicked the preview a few more times to reload it but it fails to do so. 
https://f0f2ebac-26f1-45c6-9660-6ac3f01fd65c.ws-ap01.gitpod.io/#/workspace/CircuitVerse
To execute it again I ran rails db:migrate && bundle exec rails server, still not executing. What am I doing wrong?

**Comment by svenefftinge** [comment]
Hi @sakshi1499, we published a big update on Monday and that seems to have broken your experience. We are investigating.

**Comment by sakshi1499** [comment]
Hi, I told my organization about the same and they worked on a fix.
This is what they did https://github.com/CircuitVerse/CircuitVerse/commit/b6ea8a07252a54a37dc97aaa6a387f6a2356bc8f
Thank you for your efforts :)
