### ISSUE TITLE
Epic: Interact with VS Code Browser during workspace load

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#8971]
In our Q1 Hackathon, Anton and Jean-Pierre found out that we can serve the file-system from the content-store without starting the actual container. GitHub is doing a similar technic with github.dev, but use a filesystem that directly connects to GitHub. This isn't too cool in our case, because we want people to look at the state of a workspace (i.e. a prebuilt checkout and state of stopped workspace). Therefore using the content store instead of GitHub as the filesystem provider is much better 🎉 .

Ultimately, we could build a filesystem that first accesses from our content store (read-only), and when the container started delegates to the real filesystem.

Would be cool if this could work from local VS Code as well.

**Comment by atduarte** [comment]
Should we rename this epic to be more focused on the user outcome? E.g. "Epic: Instant edit mode"

**Comment by jeanp413** [comment]
Maybe related to the new [Continue Edit Session](https://github.com/microsoft/vscode/pull/151528) feature of vscode where added/modified/deleted files are stored in the setttings sync server

**Comment by loujaybee** [comment]
@atduarte / @jeanp413 - Updated, let me know if that makes sense. Having a feature name as you suggest @jeanp413 sounds good, but we can decide on that closer to the time! 🙏

**Comment by Siddhant-K-code** [comment]
> GitHub is doing a similar technic with github.dev

@svenefftinge you can take a look on some OG versions, **[GitHub1s](https://github.com/conwnet/github1s)** :)
