### ISSUE TITLE
Consolidate XL clusters into normal regional clusters

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8977]
<strike>Create a new werft job or alter the existing one to support a new optional parameter [workspace-cluster-new](https://github.com/gitpod-io/ops/blob/main/.werft/workspace-cluster-new.yaml). XL clusters (require alternate manifests and exclusive admission constraints and scoring) [as per this PR](https://github.com/gitpod-io/ops/pull/1354). We've been deploying them from a branch, and then setting admission constraints and score manually. </strike>

<strike> - [ ] @atduarte we need to turn this into an epic, a super tiny one, it'll have an ops change and a code change. Let's talk on Monday.

Traffic shifts have also been manual, and should be automated too.

- [ ] Need support for workspace classes, so we can add node labels, so that pods can be scheduled to be isolated from unleashed versus other
- [ ] ws-daemon config will vary by nodepool (might be naive)
- [ ] ws-manager pod yaml will vary by nodepool (might be naive)
- [ ] workspace-templates will vary by nodepool (might be naive) </strike>

This was done with the introduction of workspace classes in https://github.com/gitpod-io/gitpod/pull/9705

**Comment by atduarte** [comment]
@kylos101 this is progress right?

**Comment by kylos101** [comment]
Closing as this is resolved.
