### ISSUE TITLE
Ping command fails

### ISSUE THREAD

**Issue by mteam88** [gitpod-io/gitpod#8979]
### Bug description

Basically, I am trying to connect to an external website (smtp.gmail.com) in #8976 but there is a connection error. I am trying to debug it so I am using `ping`

On use, ping fails to connect. Similar openssl, telnet, and netcat commands do not work and just hang with no output.

### Steps to reproduce

Open a new, blank gitpod workspace. [(Here)](https://www.gitpod.io/#github.com/sarcasticadmin/empty-repo)

Install the ping command-line tool: `sudo apt-get install inetutils-ping`

### Expected behavior

I expect: 
![image](https://user-images.githubusercontent.com/84196639/160461560-b7b0aaf9-a446-4906-b8ba-0ab67ee2eeaf.png)
I get though: 
![image](https://user-images.githubusercontent.com/84196639/160461590-b0821667-dab7-4d05-a4e5-8faad77cadee.png)

### Anything else?

I think this is related to #8976

**Comment by kylos101** [comment]
Hi @axonasif , I've provided a couple workarounds in #8976 , and am therefore removing the priority: highest (user impact) label.

**Comment by sagor999** [comment]
I believe this is working now, since we used to have firewall rule that would block ICMP packets.
Running in workspace right now:
```
gitpod /workspace/gitpod (main) $ ping www.google.com
PING www.google.com (74.125.142.147): 56 data bytes
64 bytes from 74.125.142.147: icmp_seq=0 ttl=113 time=0.736 ms
64 bytes from 74.125.142.147: icmp_seq=1 ttl=113 time=0.841 ms
64 bytes from 74.125.142.147: icmp_seq=2 ttl=113 time=0.893 ms
64 bytes from 74.125.142.147: icmp_seq=3 ttl=113 time=0.884 ms
64 bytes from 74.125.142.147: icmp_seq=4 ttl=113 time=0.767 ms
```

Feel free to re-open if it still doesn't work.
