### ISSUE TITLE
Improve review process for Team Workspace API Components

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#8981]
## Is your feature request related to a problem? Please describe

A few folders for Workspace components require approval from explicit individuals. [[1](https://github.com/gitpod-io/gitpod/blob/37916d402508a9e83ef18b22d1af57e01d4e05e1/.github/CODEOWNERS#L56)][[2](https://github.com/gitpod-io/gitpod/blob/37916d402508a9e83ef18b22d1af57e01d4e05e1/.github/CODEOWNERS#L63)][[3](https://github.com/gitpod-io/gitpod/blob/37916d402508a9e83ef18b22d1af57e01d4e05e1/.github/CODEOWNERS#L65)]

This can create bottlenecks for the team. As an experiment, we'd like to try using [lazy consensus](https://community.apache.org/committers/lazyConsensus.html).

## Describe the behaviour you'd like

With great power comes great responsibility. :spider: :man: 

For the Team Workspace components mentioned above (APIs):
1. Replace @csweichel and @aledbf for 3 workspace APIs with @gitpod-io/engineering-workspace .
2. When teammates add approval for a PR containing API changes, the approval message must contain two things:
   *. `/LGTM` 
   *. `/hold for 28 hours as lazy consensus` <-- to allow time for the team to consider the PR as a whole. 

## Describe alternatives you've considered

Leave @aledbf as approver for the three components, but, replace approval from @csweichel with :
1. `ws-daemon-api` -> @Furisto
2. `ws-manager-api` -> @sagor999 

## Additional context

Ref: [Slack](https://gitpod.slack.com/archives/C01KGM9EBD4/p1648489524606009?thread_ts=1648477475.119129&cid=C01KGM9EBD4)

**Comment by aledbf** [comment]
> Leave @aledbf as approver for the three components, but, replace approval from @csweichel with :

This still creates a bottleneck and pressure for one person :(

**Comment by kylos101** [comment]
@aledbf touche. :pray:  I'll add to our call tomorrow to see what folks think about lazy consensus. Seems like the right approach, thank you for suggesting.

**Comment by utam0k** [comment]
I may be overthinking this, but wouldn't we need three people to take into account those on vacation?
With two people, if one person is on vacation and the other one created the PR for that API himself, can't anyone review it until the other one comes back from vacation?
