### ISSUE TITLE
Populate Users Page in Admin Dashboard

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#8982]
## Is your feature request related to a problem? Please describe

Showing nothing in the Admin Dashboard on the Users page has resulted in some confusion that no users exist on an instance or that there's a problem with the UI as one expects a list of users to show up when the page is loaded. At the moment this page is only populated when a search is performed. This action which must be performed manually is not clearly identified on the page.

## Describe the behaviour you'd like

I'd like the page to display a list of users perhaps 25 to 50 at a time in a paginated table.

## Describe alternatives you've considered

None as there is no other UI which displays a listing of users.

## Additional context

N/A.

**Comment by jldec** [comment]
merging into #8983
