### ISSUE TITLE
Provide Instance Administrators the Ability to Set Git Provider Information From Within the KOTS Admin Dashboard

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#8984]
## Is your feature request related to a problem? Please describe

Previously this configuration could be provided in the `gitpod.config.yaml` file and was included in Gitpod deployment. It wasn't necessary to deploy your Gitpod instance and then add this configuration by visiting the instance.

## Describe the behaviour you'd like

I believe having this setting moved to where other configuration settings (registry, object storage, MySQL, etc...) live and are managed from in the KOTS admin dashboard would be beneficial. At least providing it as an option on top of the present workflow would make for a good compromise if not eventually be the place where this configuration is managed.

## Describe alternatives you've considered

N/A

## Additional context

N/A.

**Comment by jimmybrancaccio** [comment]
cc. @MrSimonEmms

**Comment by Pothulapati** [comment]
Hey @jimmybrancaccio,

Thanks for raising the issue. I see that it's an important config option to have in `kots`. The config dashboard is still new, and we will be adding more options here.

In the mean while, Have you checked the `advanced` mode in the dashboard where you can pass a `gitpod.yaml` file with the current config. It is overrided on top of the config selected in the dashboard. This way you can also set options missing in the kots config dashboard.

**Comment by jimmybrancaccio** [comment]
Hi @Pothulapati!

This is really just a "would be nice to have some day sort of feature request" I had discussed with Simon a few days ago.

Thanks for the tip about being about to pass in `gitpod.yaml` file. That could definitely be useful!
