### ISSUE TITLE
Reloading a stopped workspace hangs

### ISSUE THREAD

**Issue by jrebey** [gitpod-io/gitpod#899]
**Describe the bug**
If I leave my workspace open in a tab and it idles out, I get a dialog telling me so. When I click refresh in the browser, it goes through all the motions of setting up workspace, etc. and then sits there.

**To Reproduce**
Start a workspace, allow it to timeout. Let it sit idle for some period of time... I allowed it to stay overnight. Reload the browser tab.

**Expected behavior**
The workspace should load. It doesn't. You need to reload the workspace in a new tab.

**Additional Information**
This happened on https://d3d1afe0-aa32-4026-90e4-02d242123919.ws-us02.gitpod.io/# at ~11:25am EST.

Console logs attached. It seems the websocket connection doesn't reestablish.

[d3d1afe0-aa32-4026-90e4-02d242123919.ws-us02.gitpod.io-157297134.io-157297134.txt](https://github.com/gitpod-io/gitpod/files/3810051/d3d1afe0-aa32-4026-90e4-02d242123919.ws-us02.gitpod.io-157297134.io-157297134.txt)

**Comment by svenefftinge** [comment]
It is not reproducible and could have been caused by some caching issues we experienced since our last deployment (Monday). Could you hard-reload and try again?
