### ISSUE TITLE
Epic: Lazy pull workspace container images

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#8992]
## Is your feature request related to a problem? Please describe
Image pull remains one of the most time-consuming tasks during workspace startup. Multiple optimizations were done already, but we continue to require the pull of all the image layers to start the workspace. Given the variety of images/layers (that makes it impossible to cache it all), the size of those, and the physical limits of data transfers this means we are not able to reach sub-10s workspace startup times on higher percentiles as we would like.

## Describe the behaviour you'd like
P90 workspace startup times under 10 seconds.

**Comment by kylos101** [comment]
@atduarte closing for now. 

FYI, if we want to do dynamic loading of chunks, we should be able to do w/o lazy loading, injecting chunks using registry-facade.
