### ISSUE TITLE
Upgrade Harvester to 1.0.1

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#8999]
Upgrade Harvester to 1.0.1, once version 1.0.1 is [released](https://github.com/harvester/harvester/releases). The [milestone says](https://github.com/harvester/harvester/milestone/10) it will be released today.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/239422/160603150-84e1b9be-2c3e-49bc-920d-d6015b54c1ad.png">

To be confirmed: This requires us to re-install the nodes because the one-click-upgrade feature made it into 1.0.1, but not 1.0.0

**Comment by meysholdt** [comment]
version [1.0.1-rc2](https://github.com/harvester/harvester/releases/tag/v1.0.1-rc2) got released 🤪

**Comment by meysholdt** [comment]
version [1.0.1](https://github.com/harvester/harvester/releases/tag/v1.0.1) final is available :-)

And there is an [upgrade guide](https://docs.harvesterhci.io/v1.0/upgrade/automatic/) according to which we do *not* need to re-install all nodes.

**Comment by meysholdt** [comment]
upgrade successful :)

**Comment by jenting** [comment]
v1.0.2 was out.
