### ISSUE TITLE
Ruby Support

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#9]
We should add support for Ruby.

**Comment by svenefftinge** [comment]
- [ ] https://github.com/theia-ide/theia-ruby-extension/issues/1
- [ ] https://github.com/theia-ide/theia-ruby-extension/issues/2
- [ ] https://github.com/theia-ide/theia-ruby-extension/issues/3

**Comment by svenefftinge** [comment]
Further more we need to 
 - [] update the Gitpod IDE
 - [] update its image to be able to run the language server
 - [] update docs.gitpod.io

**Comment by jbicker** [comment]
At least there is a theia-app for now. 
https://github.com/theia-ide/theia-apps/pull/67

**Comment by svenefftinge** [comment]
Done

**Comment by HorizonShadow** [comment]
Is there a way to debug ruby apps with this?

Using the gitpod/workspace-full:latest image, there only appears to be go, and node available to code. I don't see a way to install the ruby extension.

**Comment by svenefftinge** [comment]
For the time being we are shipping ruby support through the language server only.
We will switch to the full VS Code extension in the coming weeks.
