### ISSUE TITLE
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 57302581248, capacity: 57639780352 Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by Luis6969** [gitpod-io/gitpod#900]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by JesterOrNot** [comment]
Could you detail A: Tasked performed before the error and B: An example repo

**Comment by geropl** [comment]
Thanks @Luis6969 for reporting this. I could verify this is a real issue.

**Comment by geropl** [comment]
Outdated, fixed in the meantime.
