### ISSUE TITLE
[registry-facade] Manifest generation takes "a long time"

### ISSUE THREAD

**Issue by csweichel** [gitpod-io/gitpod#9006]
### Bug description

When [observing registry-facade](https://grafana.gitpod.io/d/registry-facade/gitpod-component-registry-facade?orgId=1&refresh=30s&from=now-12h&to=now) manifest assembly in production we notice that it's really rather slow (p50 is blue, p95 is yellow, p99 is green; Y-axis in seconds):  
<img width="1821" alt="image" src="https://user-images.githubusercontent.com/3210701/160676284-62674fa4-4a57-4d94-8c77-788b9dcd8e2b.png">

It seems that we're either being rate-limited by the downstream registry, or our manifest caching is broken. We see a lot of `cannot get manifest from store` warnings in registry-facade.

### Steps to reproduce

Run this in production

**Comment by kylos101** [comment]
@csweichel was this issue resolved in #9005? I ask because, it just so happens, @utam0k is looking to learn about `registry-facade`. 

If this issue is resolved, another opportunity for @utam0k could be #9162, which @aledbf started recently. 

Let us know?
