### ISSUE TITLE
Epic: Persisted Terminal History

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#9019]
### Context

* Currently, workspaces do not persist history. 
* When starting a new workspace you do not get history from all previous workspaces launched in Gitpod. 
* History is relied on by many developers to do their work.

### Context

A terminal history is a very important productivity tool in local dev environments. With ephemeral workspaces we only have a history per session, which is inconvenient. Gitpod should persist the terminal history between workspaces for the same project and user. It's the expectation of all users coming from a local dev environment with a heavy use of terminals.

### Acceptance Criteria

- [ ] Opening a new workspace will show bash history for previous workspaces
- [ ] Documentation is updated with history support

### Out of scope

* Shells other than bash. 

<details>
<summary><strong>Archive</strong></summary>
### Out of scope

* Other shells beyond bash. 

This feature doesn't necessarily need to be advertised, as it is an existing expectation when working with terminals. Users will be positively surprised to see that Gitpod finally keeps history state across multiple workspaces.

### Persona(s)

All users with a terminal heavy workflow.

### In scope

Keep history for our default shell (bash) for the same project and user.

### Out of scope

Supporting all possible shells.
</details>

**Comment by csweichel** [comment]
@akosyakov could we reuse what we built for VS Code user setting sync here?

**Comment by akosyakov** [comment]
> @akosyakov could we reuse what we built for VS Code user setting sync here?

It maybe easy to use blob API from server. User setting sync is scoped to a user and versioned. It looks like here it is scoped to the same workspace and does not need support multiple versions.

> keeps history state across multiple workspaces

@svenefftinge I'm not sure about these bit. If I start a completely new workspace I would expect that it is fresh. For me preserving history only between restarts of the same workspace actually makes sense. Maybe should be configurable.

**Comment by kylos101** [comment]
@akosyakov I would expect new workspaces to have empty history too. But, if I were to restart an existing one, having that history would be nice. If you "really" need something in a new workspace, I would argue that is what dotfiles are for. :sweat_smile: 

Another thing to consider is, how would a user delete history. Say for example, if it contained a secret they did not want persisted.

**Comment by akosyakov** [comment]
One thing which come up today that there are many clients controlling shell sessions, supervisor, VS Code, JetBrains, OpenSSH server and so on? Which one we are talking here? If all of them and we don't need to sync between different workspace then maybe the history should be preserved as a part of workspace backup? @csweichel

**Comment by csweichel** [comment]
> there are many clients controlling shell sessions

We would rely on the behaviour of the shell (e.g. `bash`) and just backup/restore the `$HISTFILE`. This way we're independent of the process/client controlling the shell session, and users can get creative how they want to [handle multiple sessions](https://www.baeldung.com/linux/preserve-history-multiple-windows).

> how would a user delete history. Say for example, if it contained a secret they did not want persisted.

If we just back up the histfile, users can modify this file to delete things from their history.

A few questions arise though:
- how do we know where the histfile is located? If the user is using e.g. `zsh` or `fish` the history will be stored elsewhere compared to e.g. `bash`. We could try and detect/guess which shell is used, look at the envvars of that shell to find the `HISTFILE` and in absence fall back to sensible defaults (`bash: ~/.history`, `zsh: ~/.zsh_history`).
- in what context to we restore the history? There doesn't seem to be consensus yet as to the "scope" of the terminal history. We could try and maintain history for a user, a project or a single workspace across restarts.

**Comment by akosyakov** [comment]
> how do we know where the histfile is located? If the user is using e.g. zsh or fish the history will be stored elsewhere compared to e.g. bash. We could try and detect/guess which shell is used, look at the envvars of that shell to find the HISTFILE and in absence fall back to sensible defaults (bash: ~/.history, zsh: ~/.zsh_history).

Detection is rather tricky, a user can overwrite shell configuration on level of editors as well. Could not we store all?

> in what context to we restore the history? There doesn't seem to be consensus yet as to the "scope" of the terminal history. We could try and maintain history for a user, a project or a single workspace across restarts.

I wonder for cross workspaces support how are we going to merge it? Last workspace wins and overwrites, always append? Should it sync in real time?

**Comment by akosyakov** [comment]
found https://github.com/rcaloras/bashhub-client maybe somebody tried

**Comment by loujaybee** [comment]
I do agree with keeping simple and limiting supported shells, but I must say that `zsh` is very popular. Looking into usage stats I think would be worthwhile here. Also the recent move from Apple might impact zsh adoption going forward [[1](https://support.apple.com/en-us/HT208050)].

**Comment by ghuntley** [comment]
👍 for using HISTFILE approach.

**Comment by arel** [comment]
As a heavy user of terminals and terminal history (especially Ctrl+R), I love this proposal. Like @svenefftinge, my expectation would be to keep history _per project_. (E.g., losing all my history when I open a workspace for a new branch would be inconvenient.)

> I wonder for cross workspaces support how are we going to merge it? Last workspace wins and overwrites, always append? Should it sync in real time?

"Last workspace wins and overwrites" makes sense since it is similar to how bash history already works with multiple terminals. Plus, it would make it easier to delete history if there's information I want to remove.

**Comment by mteam88** [comment]
Any updates on this? Specifically: any workaround in place or theoretically possible.

**Comment by axonasif** [comment]
@mteam88 if you wish to persist bash history only, then it's fairly simple. Just create a new env var called `HISTFILE` at https://gitpod.io/variables with the value of `/workspace/.bash_history` and set the scope to `*/*`.

**Comment by spearki** [comment]
@axonasif Unfortunately it looks like `HISTFILE` gets [truncated at workspace startup](https://github.com/gitpod-io/gitpod/blob/1d8fe14c23ee852db8234975b330dd365ea63357/components/ide/code/startup.sh#L12), so you only get history from the (n-1)th session, and only in task terminals (which happen to start early enough to load the history before the truncate happens).

Do you think it would be possible to fix that in lieu of an official solution here, so we have a workaround option?

**Comment by axonasif** [comment]
Hmm @spearki, wasn't aware of that line.

In that case, you could put [this file](https://github.com/gitpod-io/workspace-images/blob/584ad0b4e69c294116f5d099a4e2ede102ee2e90/base/bashrc.d/persist_hist.sh) to `$HOME/.bashrc` from your dotfiles to workaround, it's guaranteed to work. Just copy pasted from this [repo](https://github.com/axonasif/dotfiles-sh) with a few changes.

**Comment by spearki** [comment]
@axonasif We actually applied a very similar change to your draft PR to our own Docker image, and this is where we discovered the truncation problem. Doing it in dotfiles is also subject to the same truncation. We are now doing `sed -i '/truncate/d' /ide/startup.sh` as a workaround, but this is obviously an awful hack.

**Comment by axonasif** [comment]
@spearki ah, yeah, makes sense... I use `fish` for interactive use... so never noticed 😅

**Comment by mgenereu** [comment]
Does #17612 close this?  I just had it start working much to my surprise!

**Comment by akosyakov** [comment]
@mgenereu only for the same workspace. We would like to support it more generally, i.e. across all user shells for instance.

**Comment by loujaybee** [comment]
Should also note this is also enabled via 3rd parties like Atuin: https://www.gitpod.io/guides/persisted-terminal-history-atuin
