### ISSUE TITLE
Workspace Completed

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#902]
**Describe the bug**
Workspace completed!
![image](https://user-images.githubusercontent.com/50386709/68352371-d3ccd900-00cb-11ea-94f3-17b4769ef3cc.png)
**To Reproduce**
Here is the repo!
https://github.com/JesterOrNot/Gitpod-V
**Expected behavior**
Workspace open
**Additional Information**
I use a shell script in the build.

**Comment by 32leaves** [comment]
Thank you for reporting this.

We have deployed a fix that should prevent this from occurring under normal circumstances. Please do open a new issue if you come across this error again.
