### ISSUE TITLE
VS Code Release 1.66

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/gitpod#9020]
Endgame: https://github.com/microsoft/vscode/issues/145549
Release: https://github.com/microsoft/vscode/releases/tag/1.66.0

MS release date: March 30, 2022

DRI: @filiptronicek @mustard-mh 
Plan:

- [x]  Create corresponding release branches for `main` and `gp-code/main`
    - [x] Create release branch `release/1.66`
    	- Execute the rebase from upstream: `./scripts/sync-with-upstream.sh upstream/release/1.66 release/1.66`
    - [x] Create release branch `gp-code/release/1.66`
     	- Execute the rebase from upstream: `./scripts/sync-with-upstream.sh upstream/release/1.66 gp-code/release/1.66`
- [x]  Switch nightly jobs in https://github.com/gitpod-io/openvscode-releases and Gitpod Code-Nightly GitHub actions to point to the release branches
	- [x] https://github.com/gitpod-io/openvscode-releases/blob/1b60a53a1a34b61dfb41ca13b65bfbad4115bda4/.github/workflows/insiders-gp.yml#L19

    - [x] https://github.com/gitpod-io/openvscode-releases/blob/1b60a53a1a34b61dfb41ca13b65bfbad4115bda4/.github/workflows/insiders.yml#L19

    - [x] https://github.com/gitpod-io/gitpod/pull/9027 https://github.com/gitpod-io/gitpod/blob/4bdee21961c5390e1dc61606b7070af3b0f65971/.github/workflows/code-nightly.yaml#L34
- [x]  Create and merge PR in Gitpod repo to generate stable image for VS Code https://github.com/gitpod-io/gitpod/pull/9044
    - Use the template from https://gist.github.com/filiptronicek/be19dcab639a1cdf08089cc762377a41
    - [x]  [Smoke test](https://www.notion.so/Gitpod-VS-Code-1aa1dfcfdc5147869ec5ffcf86f430a6) version 1.66 in VS Code Insiders
- [x]  Create and merge PR in Gitpod repo updating VS Code stable image tags to image generated in previous step https://github.com/gitpod-io/gitpod/pull/9048
		https://github.com/gitpod-io/gitpod/blob/14a9636f476fc69294c5d0d9e7f831f16b39074f/chart/values.yaml#L361
		https://github.com/gitpod-io/gitpod/blob/866357d3743c875c56883189778492a4fafcca03/install/installer/pkg/components/workspace/ide/constants.go#L9
- [x]  Deploy VS Code Insiders as stable
- [x]  Release [OpenVSCode Server](https://github.com/gitpod-io/openvscode-server) https://github.com/gitpod-io/openvscode-server/releases/tag/openvscode-server-v1.66.0
- [x]  Port fixes from release/1.66 to main if any
- [x]  Switch nightly jobs in https://github.com/gitpod-io/openvscode-releases and Gitpod Code-Nightly GitHub actions to point back to `main` and `gp-code/main` branch
- [x]  Monitor for recovery releases and provide corresponding release in Gitpod and OpenVSCode if necessary

**Comment by mustard-mh** [comment]
Should we change this to `release/1.66` too?
https://github.com/gitpod-io/openvscode-releases/blob/99eaaf3f402d0decd16611be1a058c672c080e2f/.github/workflows/insiders-gp.yml#L18

Node version is 16 now
https://github.com/gitpod-io/openvscode-releases/blob/99eaaf3f402d0decd16611be1a058c672c080e2f/.github/workflows/insiders-gp.yml#L50

**Comment by jeanp413** [comment]
I bumped node version in this commit https://github.com/gitpod-io/openvscode-releases/commit/bb21e32228d1341e770c07af9736536cdf8e774e

**Comment by jeanp413** [comment]
Same in gitpod repo https://github.com/gitpod-io/gitpod/pull/9029
