### ISSUE TITLE
[gp-cli] Validate .gitpod.yml

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#9025]
## Is your feature request related to a problem? Please describe
Currently, using VSCode, yaml-schema validation helps reducing typos or indentation issues in `.gitpod.yml`. It would be useful to offer the same functionality from the gp CLI.

## Describe the behaviour you'd like
`gp validate` or `gp validate config`

## Describe alternatives you've considered
It'd be interesting if we could also validate `.gitpod.Dockerfile`

## Additional context
N/A

**Comment by mteam88** [comment]
Really like this! Great idea!

**Comment by filiptronicek** [comment]
We could leverage https://github.com/xeipuuv/gojsonschema and load https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/data/gitpod-schema.json to check against.

**Comment by filiptronicek** [comment]
Bad bot! *internal screaming*
<img width="525" alt="image" src="https://user-images.githubusercontent.com/29888641/204293670-8ae419e0-53b3-4fc8-8dac-97f3ca38e4c1.png">

**Comment by loujaybee** [comment]
Given the introduction of `gp validate`, I think we can consider this closed, what do you think? 

See issue comment: https://github.com/gitpod-io/gitpod/issues/7671#issuecomment-1503186622
