### ISSUE TITLE
Sorry, something went wrong 😓 Error 504

### ISSUE THREAD

**Issue by leo-from-spb** [gitpod-io/gitpod#903]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by JesterOrNot** [comment]
Could you give an example repo and detail what happened before you got the error

**Comment by svenefftinge** [comment]
We've had a hickup in the EU cluster. Sorry for that. See https://status.gitpod.io

**Comment by leo-from-spb** [comment]
I've just logged in (using Github) for the first time.
