### ISSUE TITLE
[supervisor] prebuild workspaces stop before content is fully loaded

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#9033]
### Bug description

It looks like we may be encountering a race condition when initializing some content.

In the below example, the pod thinks content isn't there, starts shutting down, and while shutting down we see that there is actually content. In checking the pod's corresponding backup, I can see that the content was cloned to the context folder, but the `.gitpod` folder is empty.

[The error mentioned below in the log snippet on the first line.](https://github.com/gitpod-io/gitpod/blob/c6cc1ab0fb45c6ac5dbc1d9a0144ded79044bc9b/components/supervisor/pkg/supervisor/supervisor.go#L1230)

```
2022-03-31 01:20:44.000 GMT - workspace "no content init descriptor found - not trying to run it"
2022-03-31 01:20:45.000 GMT - workspace "shutting down API endpoint"
2022-03-31 01:20:45.000 GMT - workspace "supervisor: workspace content available"
```

[Here are the complete logs.](https://cloudlogging.app.goo.gl/vFBC6xgXT4k8NNL79) [Here is a second set of logs for another instance.](https://cloudlogging.app.goo.gl/CEsx9yfZ2BbmwUTd7)

### Steps to reproduce

n/a :slightly_frowning_face: 

### Workspace affected

Refer to logs

### Expected behavior

Just avoid the race condition, that's all...

### Example repository

n/a :slightly_frowning_face: 

### Anything else?

The user in this case is using a private image registry.

**Comment by csweichel** [comment]
The `no content init descriptor found - not trying to run it` message has nothing to do with today's content init. It's a "leftover" from full workspace backup.
