### ISSUE TITLE
bundle install in init task doesn't persist

### ISSUE THREAD

**Issue by joshleblanc** [gitpod-io/gitpod#905]
**Describe the bug**
I'm running `bundle install` in the init task, followed by `bundle exec rackup` in the command task. It's throwing an error that rack isn't installed, even though it just ran the `bundle install`

**To Reproduce**
Open this: https://gitpod.io#https://github.com/joshleblanc/juiceboxify.me

**Expected behavior**
It should have the gems installed

**Additional Information**
Here's the log:

```
gitpod /workspace/juiceboxify.me $ {
> [ -r /workspace/.prebuild-log-0 ] && cat /workspace/.prebuild-log-0; [ -r /workspace/.gitpod/prebuild-log-0 ] && cat /workspace/.gitpod/prebuild-log-0; true
> } && {
> bundle exec rackup -p 4567 -o 0.0.0.0
> }; HISTFILE=/workspace/.gitpod/cmd-0 history -r
gitpod /workspace/juiceboxify.me $ {
> bundle install
> }; exit
Fetching gem metadata from https://rubygems.org/........
Using bundler 2.0.2
Fetching byebug 11.0.1
Installing byebug 11.0.1 with native extensions
Fetching unf_ext 0.0.7.6
Installing unf_ext 0.0.7.6 with native extensions
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching dotenv 2.7.5
Installing dotenv 2.7.5
Fetching http-accept 1.7.0
Installing http-accept 1.7.0
Fetching http-cookie 1.0.3
Installing http-cookie 1.0.3
Fetching mime-types-data 3.2019.0331
Installing mime-types-data 3.2019.0331
Fetching mime-types 3.2.2
Installing mime-types 3.2.2
Fetching mini_magick 4.9.5
Installing mini_magick 4.9.5
Fetching mustermann 1.0.3
Installing mustermann 1.0.3
Fetching netrc 0.11.0
Installing netrc 0.11.0
Fetching rack 2.0.7
Installing rack 2.0.7
Fetching rack-protection 2.0.7
Installing rack-protection 2.0.7
Fetching rest-client 2.1.0
Installing rest-client 2.1.0
Fetching tilt 2.0.9
Installing tilt 2.0.9
Fetching sinatra 2.0.7
Installing sinatra 2.0.7
Fetching sinatra-cross_origin 0.4.0
Installing sinatra-cross_origin 0.4.0
Bundle complete! 6 Gemfile dependencies, 19 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

🍌 This task ran as part of a workspace prebuild.


bundler: command not found: rackup
Install missing gem executables with `bundle install`
```

**Comment by joshleblanc** [comment]
Was this ever fixed? My workspaces still exhibit this issue

**Comment by tachyons** [comment]
Same issue here

**Comment by svenefftinge** [comment]
@tachyons @joshleblanc I just tried the project mentioned above and it seemed to work.
Also running `rackup -p 4567 -o 0.0.0.0` directly worked. Am I missing something?

**Comment by Ananthavijay** [comment]
Try this one: https://gitpod.io/#https://github.com/CircuitVerse/CircuitVerse
In this case, the problem is with rails.

**Comment by tachyons** [comment]
Turns out issue is gitpod tries to cache the build steps and skip running those to save time, but caching do not include changes outside the project dir, like gems installed in ~/.rvm folder in home directory. Workaround was to install gems in vendor/gems instead of default path

**Comment by sylhare** [comment]
A simple workaround would be to install the gems "locally", here is how I did it:
- Persist `bundle install` in prebuild:  https://github.com/sylhare/Type-on-Strap/pull/324
