### ISSUE TITLE
Dark theme makes the current setting wording on the Settings list is not visible

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#9057]
### Bug description

Change to the Dark theme, the current setting wording on the Settings list is not visible.

### Steps to reproduce

- Using the Google Chrome.
- In the Settings > Preferences, change to use the Dark Theme
- After that, the current setting wording on the list is not visible. For examples:
![image](https://user-images.githubusercontent.com/49380831/161217200-bd26bd73-5581-43d7-a6ab-d05dcb70e6d1.png) ![image](https://user-images.githubusercontent.com/49380831/161217258-35326abf-5fca-4fec-8284-0ee371bc8475.png)

### Expected behavior

The wording should be visible even change to use the Dark theme.

**Comment by mustard-mh** [comment]
Thanks for your feedback 🙏 , it was fixed here https://github.com/gitpod-io/gitpod/pull/9052, waiting for deploy.

**Comment by mustard-mh** [comment]
Ahh, it's you 🍊!!

**Comment by jenting** [comment]
Thank you all, super fast!!!
