### ISSUE TITLE
.werft/monitoring-satellite: Clean up logic

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#9059]
Following up from https://github.com/gitpod-io/gitpod/pull/9016#discussion_r838424340

The logic that deploys monitoring-satellite is getting pretty hard to read, and it's using `classes`, `types` and `interfaces` in unconventional ways.

We should clean that up 🙂

**Comment by mads-hartmann** [comment]
Moving to the "Reduce Technical Debt" epic and adding it to the next iteration.
