### ISSUE TITLE
GitPod Pages are a blank white screen. 

### ISSUE THREAD

**Issue by CompeyDev** [gitpod-io/gitpod#9069]
### Bug description

Every once in a while, be it close the GitPod tab or have it idle, once it reloads, the site is a blank white page. No matter what I do, restart, clear cookies, or anything, it is a white screen. The only fix is waiting for an from 15 minutes to an hour, and it fixes itself. Something interesting though is that the console logs certain websocket errors everytime this happens, and after a timeout of a minute, a prompt displaying a message appears. The prompt reads similar to this: "Unable to connect to websocket, make sure you are connected to a network."

### Steps to reproduce

No particular steps to reproduce, seemingly random.

**Comment by axonasif** [comment]
Hey @CompeyDev, I think it would be helpful if you grab your console logs when that error prompt shows up 🙏

**Comment by CompeyDev** [comment]
Oh, my bad, I forgot to add the logs here. Here:
![image](https://user-images.githubusercontent.com/74418041/161505899-62a26cfe-91ae-47de-8208-90b81838ca67.png)

**Comment by loujaybee** [comment]
I've not heard of this being reported before, thanks for raising @CompeyDev, we'll take a look to see if we can replicate.

**Comment by CompeyDev** [comment]
This error occurred again, same console errors, but this time I was able to grab the network logs (console is the same):
![image](https://user-images.githubusercontent.com/74418041/165544041-c964f884-7601-4821-a0e1-8c7defc8e29e.png)

**Comment by axonasif** [comment]
Hey @CompeyDev, can you try a different browser?

**Comment by CompeyDev** [comment]
Tried multiple times before, the same error applies for any chromium based browsers, never faced with gecko variants.

**Comment by CompeyDev** [comment]
Going to do that next time onwards, although I don't think I have any extensions enabled.

**Comment by loujaybee** [comment]
Will close this now, @CompeyDev unless others replicate or the issue persists. This might be something like a workspace misbehaving or an unfortunate workspace scheduling mishap. However, will continue to keep an eye out for reports, thanks a lot for raising 🙏

**Comment by CompeyDev** [comment]
It seems to happen with random workspaces though, it has nothing consistent to it.

**Comment by saravanakumarthamilselvi** [comment]
hi , same issue here. But difference is its not random . Not even successfull in creating the workspace once

**Comment by gtsiolis** [comment]
Thanks for chiming in, @CompeyDev! 🙏 

Also, @saravanakumarthamilselvi opening a [new bug report](https://github.com/gitpod-io/gitpod/issues/new?assignees=&labels=type%3A+bug&template=bug_report.yml) describing what you see could really help. Comments on closed issues can easily go unnoticed. 💡
