### ISSUE TITLE
It is unclear how long a billing cycle is - how much time is left until the hours reset

### ISSUE THREAD

**Issue by AstralJaeger** [gitpod-io/gitpod#9088]
## Is your feature request related to a problem? Please describe
I've hit some frustration when the user DevComp#0750 asked on Discord why her remaining monthly hours had not reset. 
The user was not able to find out why this was the issue.
It is very difficult to find out how long a billing cycle is and it is not transparent how many days remain until the remaining hours reset.

## Describe the behaviour you'd like
Currently the billing cycle is shown as a tooltip if the user hovers over the remaining hours, I would suggest it is moved into its own field, showing the full billing cycle (start and end date) aswell as a count down when the hours reset or rebelling is done.

## Describe alternatives you've considered
-

## Additional context
Current state (screenshot stone from Pauline) and a part of my suggestion.
![Current state by Pauline](https://user-images.githubusercontent.com/24294933/161398343-684aa743-3860-4a0c-9f20-47afc7f1070b.png)
![My suggestion](https://user-images.githubusercontent.com/24294933/161398347-67d7c63b-b931-403c-90de-9d2675fe9901.png)

**Comment by jwpjrdev** [comment]
It would be nice to have the hours remaining indicator in a more accessible location like the main dashboard page.

Alerts for when you're running low on hours (25, 10, 5, 2, 1, etc.) would also be nice. It's really janky to run out of hours mid-session and have no idea what happened until you look around and see you're out.

**Comment by geropl** [comment]
Thx for the input @AstralJaeger ! I think the "current billing cycle" is sth we can easily add.

@jwpjrdev We're currently focusing on new payment integration, and this is certainly an important requirement for that. But I don't think we'll find time to add that to the current implementation, sorry.
