### ISSUE TITLE
Feature Request: Add Input device support to Gitpod.

### ISSUE THREAD

**Issue by pauliesnug** [gitpod-io/gitpod#9089]
## Is your feature request related to a problem? Please describe
When testing certain types of applications like machine learning and other apps that use a video stream, I can’t use Gitpod to test and code for them.

## Describe the behaviour you'd like
The ability to use an input device (such as a webcam or microphone) in a Gitpod instance in a browser.

## Describe alternatives you've considered
Not using Gitpod for these projects (unfortunately 😞)

## Additional context
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

**Comment by mteam88** [comment]
I also want to do this for machine learning, specifically to read the values of dice. This would be a great feature to have, and it could open up a new type of developer to Gitpod. The user base for Gitpod is large, but I think additional features like these really set it apart from the usual.

Perhaps also creating workspaces dedicated to training AI and testing AI could be implemented with this feature (maybe in a paid plan.)

**Comment by loujaybee** [comment]
@EthanDevelops can you elaborate on what the restriction for you? ports? networking? a protocol issue? 

If it's a network issue, you could consider investigating using tailscale for that:
https://www.gitpod.io/docs/configure/tailscale#network-bridging

If it's a port you need to forward, you can do that via SSH on the command-line, also: 
https://www.gitpod.io/docs/ides-and-editors/command-line
