### ISSUE TITLE
Add a "super open source" plan

### ISSUE THREAD

**Issue by jrebey** [gitpod-io/gitpod#909]
I exclusively use GitPod in the OSS space. 100 hours is a lot for most people, and it's been working well for me so far. But, I feel like I'm going to approach the 100 hour limit soon. I don't mind paying for the service but I kinda need something in between the two existing plans. I'd gladly pay $9/mo for a 150-200 hour plan with Public repos only. I don't use it enough to justify the $39/mo unlimited plan.

Are there any plans (no pun intended) to add additional plan types to the product? I feel like you'd get a lot more paying customers with some middle-ground between Personal and Unlimited.

**Comment by svenefftinge** [comment]
Yes, we are going to add one for $25 with unlimited. We've though about an `open-source unlimited` plan but we feel the target group is not big enough to justify the extra plan.
Let us know when you run out of hours and we will sort it out.

**Comment by jrebey** [comment]
I hear you on the target group being too small.. I'm definitely in the minority here but the fact that Gitpod let's me work on Web stuff and have users test for bug fixes directly without having to know how to use git/code/build, etc. is super handy so I think my usage is a little more than others. It's fantastic!

I've got about 4 days left in my cycle and only have 9 hours or so left heading into the weekend. I'm gonna run out for sure. I'd rather not use a local git client... I got so used to gitpod :)

**Comment by JesterOrNot** [comment]
As a student who uses gitpod for development every day, I have mostly scrapped my dev-env at home and so I am paying out of pocket for open source work aswell. As such this plan would be awesome!

**Comment by jrebey** [comment]
I'm down to 1.2 hours... I guess I'm done until Monday :(

**Comment by tnir** [comment]
@svenefftinge Can you close this since Personal plan has 100 hour/mo limit only $9/mo?

**Comment by jankeromnes** [comment]
There is also a Professional Open-Source plan now: https://www.gitpod.io/docs/professional-open-source/
