### ISSUE TITLE
Workbench failed to connect to server (Websocket closed)

### ISSUE THREAD

**Issue by avinashupadhya99** [gitpod-io/gitpod#9090]
### Bug description

![image](https://user-images.githubusercontent.com/52544819/161423038-8c5e530f-6577-4c95-b26c-b6869b86a992.png)
Not able to use the workspace due to the above error. Releading, restarting, and deleting the workspace did not help.

### Steps to reproduce

Not sure, ran into it randomly

### Workspace affected

 avinashupadhya9-orderser-ve0q6ptot22

### Expected behavior

Should be able to use Gitpod without issues

### Example repository

Issue when running - https://github.com/avinashupadhya99/order-service on Gitpod. Used to work fine but ran into a weird issue

**Comment by avinashupadhya99** [comment]
Seems to be fixed now without any actions

**Comment by avinashupadhya99** [comment]
I have 2 workspaces active and opening a 3rd and 4th workspace causes the following error for the new workspaces - 
![image](https://user-images.githubusercontent.com/52544819/161425897-2ce8db9a-407d-4432-8f4b-de998cadfc03.png)

Error in console - 

```
Access to internal resource at 'https://blobserve.ws-us38.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-c5beb9076768e6ab3717db6e74bdab4b53304ad9/__files__/manifest.json' (redirected from 'https://avinashupadhya9-packages-pm78q8j8lxt.ws-us38.gitpod.io/manifest.json') from origin 'https://avinashupadhya9-packages-pm78q8j8lxt.ws-us38.gitpod.io' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

**Comment by mteam88** [comment]
It seems it may be a firewall or network issue, try it on a different device.

**Comment by loujaybee** [comment]
@avinashupadhya99 if you're able to re-replicate, could you [store the logs](https://www.gitpod.io/docs/troubleshooting) and [forward them to support](https://www.gitpod.io/contact/support)? 🙏
