### ISSUE TITLE
Dhall configuration files

### ISSUE THREAD

**Issue by jwpjrdev** [gitpod-io/gitpod#9091]
## Is your feature request related to a problem? Please describe
N/A

## Describe the behaviour you'd like
Gitpod currently allows configuration files in the YAML configuration format. It would be very nice to see Dhall (https://dhall-lang.org) configs supported.

## Describe alternatives you've considered
I don't think there are any real alternatives to Dhall—you can always run scripts from a normal Gitpod config but I feel like that's less fluid.

## Additional context
Dhall is a Turing-incomplete configuration language—see the above link for more info.

**Comment by jwpjrdev** [comment]
The implementation should be fairly straightforward–Dhall can target YAML.

If someone could point me to the module where configuration files are processed, I might be able to write up a PR.

**Comment by geropl** [comment]
Thx for sharing the idea @jwpjrdev ! But we're looking to reduce variance in a lot of corners of Gitpod where it does not add immediate value, and I fear this would be such a case.

E.g., yaml is a well-known, established and most users are somewhat familiar with it, so it serves as low-entry-barrier config format. While I personally looking forward to some of the more elaborate config language like Dhall gaining more traction in the wider developer community, I don't think it make sense to adopt it now for this purpose.
