### ISSUE TITLE
Deprecate gitpod.yml config stored in the DB

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#9102]
## Is your feature request related to a problem? Please describe

There are currently 3 ways that a `gitpod.yml` can be injected into a workspace:
* Repository contains a `.gitpod.yml` file
* Project has been configured with a Database level `gitpod.yml`. This config is stored on the Project level, and not in the repository
* Using definitely-gp, scheduled for deprecation in #8473

The existing solution  results in inconsistent handling of gitpod.yml definitions. The intention of this change is drive towards a single workflow for defining gitpod.yml specification.

This Issue desribes the what and acts as a tracking issue, the how is yet to be determined.

CC @jldec for filling more details on why and the product take on this.

**Comment by jldec** [comment]
Approve - the DB config is hard to control, and too magical.

NOTE: there is a 4th mechanism - auto-inferred gitpod.yml for repos which don't have one. - see PR https://github.com/gitpod-io/gitpod/pull/7383

Making this less mysterious was discussed also in https://github.com/gitpod-io/gitpod/issues/6724 (closed)
