### ISSUE TITLE
Fix table alignment in project prebuilds list

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#9103]
### Problem to solve

Commits and Branch columns in the project prebuilds list are not vertically aligned when the branch name overflows the column width.

| Prebuilds list for the `gitpod` project[[1](https://gitpod.io/t/gitpod/gitpod/prebuilds)] |
|-|
| <img width="1122" alt="Screenshot 2022-04-04 at 2 02 45 PM" src="https://user-images.githubusercontent.com/120486/161539884-5d2bba18-ecf9-445c-bdf0-5e521698b2df.png"> |

**Comment by trumbitta** [comment]
`truncate` + `title`? (Hello, `TruncatedText` component, old friend...)

**Comment by gtsiolis** [comment]
Closing this as it's no longer reproducible. 📕
