### ISSUE TITLE
Gitpod fails silently on bad `.gitpod.yml`

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#912]
This config file has mutliple `command` items in the same tasks entry.
There's no error in editor or on start.

https://github.com/FreezingMoon/AncientBeast/blob/8a42f6995c9b59447f632b5500cfb593e270cbe6/.gitpod.yml

**Comment by DreadKnight** [comment]
Oh I see. I have a talent at bumping into bugs xD

**Comment by ldettwy** [comment]
Can this stay open please?

**Comment by lovettchris** [comment]
I agree, I'm seeing the same thing and pulling my hair out trying to figure out why my .gitpod.yml file is being ignore, I even created it with "gp init"!

**Comment by pawlean** [comment]
Hey @lovettchris! Can you share a repo with your `.gitpod.yml` configuration? I'd like to see if I can replicate this.

**Comment by lovettchris** [comment]
This was my first attempt:
https://github.com/leanprover/lean4-samples/commit/f37fcef85dbeaa31222852413ece3ff59b9e26d7

If you try this you will see `which lean` fails after workspace comes up:
https://gitpod.io/#https://github.com/leanprover/lean4-samples/commit/f37fcef85dbeaa31222852413ece3ff59b9e26d7

So I stopped using `init` and so my latest version in `https://gitpod.io/#https://github.com/leanprover/lean4-samples/` works.

One thing it took a while to realize is that sometimes the "command" takes a while to actually popup, I've seen up to 10 or more seconds waiting for that.  I've decided that "command" is better anyway so the user can see the progress, whereas with "init" I think it is trying to be hidden so workspace doesn't show up until this is done, but that kind of "wait" is not as nice as showing them something is happening.

**Comment by axonasif** [comment]
Hey @lovettchris.

> So I stopped using init and so my latest version in https://gitpod.io/#https://github.com/leanprover/lean4-samples/ works.

Here's the reason why you needed to do that: https://www.gitpod.io/docs/prebuilds#workspace-directory-only

> One thing it took a while to realize is that sometimes the "command" takes a while to actually popup, I've seen up to 10 or more seconds waiting for that.

AFAIK `command` tasks are spawned in time, it could be your IDE lag to pop up the terminal in time.
Not sure but https://www.gitpod.io/docs/command-line-interface#sync-await might be interesting for you.

**Comment by lovettchris** [comment]
I see, the connection between prebuilds, init, and workspaces was not super clear in my mind, but on re-reading that page I can see it now.  It still would have been nice to include some sort of warning in the terminal window saying why my init task was being ignored. That would have prompted me to read this page more closely and understand the conneciton.
