### ISSUE TITLE
[Bitbucket Server] Open in Gitpod uses incorrect URLs for BBS repos previously opened on non-scm contexts

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#9128]
To reproduce (with Bitbucket Server)

- Open a workspace on a prefixed repo url like `https://at-bbs.staging.gitpod-dev.com/#https://bitbucket.gitpod-self-hosted.com/users/alextugarev/repos/yolo/browse` - this should open a Gitpod workspace IDE
- Go to dashboard and use Cmd-O to open another workspace
- Choose the first entry e.g. `https://bitbucket.gitpod-self-hosted.com/alextugarev/YOLO`
- Observe error
![Screenshot 2022-04-05 at 13 02 32](https://user-images.githubusercontent.com/849592/161750217-9e363626-36bc-4b89-8b5d-600074be1821.png)
![Screenshot 2022-04-05 at 13 02 46](https://user-images.githubusercontent.com/849592/161750220-0e6a21f8-4937-466b-b313-dcacccd7792b.png)

**Comment by AlexTugarev** [comment]
found this in `protocol.ts`

https://github.com/gitpod-io/gitpod/blob/24f7b609bf79b247d72d1841282639726bcd5891/components/gitpod-protocol/src/protocol.ts#L422-L434

we need to revise these kind of assumptions.
