### ISSUE TITLE
Use the same prebuild view for Workspace start as for Prebuild Details

### ISSUE THREAD

**Issue by easyCZ** [gitpod-io/gitpod#9132]
## Is your feature request related to a problem? Please describe

Originally raised in https://github.com/gitpod-io/gitpod/pull/8831#discussion_r842711075 by @gtsiolis.

| BEFORE | AFTER |
|-|-|
| <img width="1440" alt="Screenshot 2022-04-05 at 2 00 24 PM" src="https://user-images.githubusercontent.com/120486/161750940-28214fab-25d4-4306-bd85-2a1fe347b6a7.png"> | <img width="1440" alt="Screenshot 2022-04-05 at 2 09 51 PM" src="https://user-images.githubusercontent.com/120486/161750944-0304302b-bbf4-4479-91a0-c0857de35921.png"> |

Doing this would normalize the UI elements between prebuilds and workspace starts (which require a prebuild)

**Comment by jldec** [comment]
Is there any way to do this without narrowing the prebuild view?

I fully support re-using components and making elements consistent, but the image above looks like you are proposing that we squeeze the wider prebuild component into a narrow container. Why is that narrowing required?

**Comment by easyCZ** [comment]
IMO, we wouldn't narrow the view. I believe the reason for the narrowing was @gtsiolis's way to communicate that the two components should be the same (and re-using an existing view which happened to be narrower). The above image should be take more as a way to communicate the change, rather than the final design.

**Comment by geropl** [comment]
Relate to: #7812
