### ISSUE TITLE
You've been blocked. Please file an issue if you think this is a bug.

### ISSUE THREAD

**Issue by ChenMrChen** [gitpod-io/gitpod#914]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by JesterOrNot** [comment]
Could you give an example repo?

**Comment by svenefftinge** [comment]
We are blocking user that don't apply to our terms. Usually this means you were running a miner, tried doing a DoS from a workspace or something similar. If you feel the blocking is not justified, please rech out to info@gitpod.io.

**Comment by ChenMrChen** [comment]
I am sorry for trying to running a miner in the workspace. I did this because I was curious about that &nbsp;how a miner was&nbsp;running . So could u give me another chance to apply my personal workspace for free.


发自我的iPhone

------------------ Original ------------------

**Comment by jankeromnes** [comment]
Hi @ChenMrChen, sure, we have unblocked your account. Thank you for your honesty, and to prevent further blockage, please avoid running miners in the future (it's against our rules, even if it's just out of curiosity). Happy coding!

**Comment by ChenMrChen** [comment]
Thanks for your understanding. That siquation won't happen.



---Original---
