### ISSUE TITLE
installer: set movedImageBuilder at install time

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#9143]
`movedImageBuilder` should be removed as a configcat feature flag, and set as an experimental workspace configuration, that `server` happens to inspect and persist to a `server` configmap. The server configmap will be inspected, instead of the feature flag, to determine how to do related routing to image-builder-mk3.

Why? 
1. At this point, we should be running at 100% for image builds in the workspace cluster, but, still want the ability to fallback if needed. 
2. This way we can build and test with `workspace-preview`, using a webapp cluster, and a governed workspace cluster.
3. Self-hosted customers do not have configcat, but might need this ability in the future.

**Comment by WVerlaek** [comment]
@kylos101 created https://github.com/gitpod-io/gitpod/pull/15826 to remove the `movedImageBuilder` flag. I opted for not introducing an experimental flag to allow using the application cluster's image-builder API, as we're planning to remove/disable the API in application clusters soon, and e.g. for `full` install flavours the routing still works and uses the in-cluster image-builder API (by proxying over the ws-manager API).

Wdyt? If you feel we should still have an experimental flag I can add it

**Comment by kylos101** [comment]
@WVerlaek the [application clusters for gitpod.io are installed using a full flavor for webapp](https://github.com/gitpod-io/ops/blob/2cb784083130877ba96cfd9df5298fa015e15ac8/deploy/production/meta-us02/app/installer-config.yaml#L2). 

If there's a governed workspace cluster, we should try using it's image builder, over the one that is in-cluster. For example, how will this work in the case of gitpod.io, where [webapp is installed with full, and there are governed workspace clusters](https://github.com/gitpod-io/gitpod/pull/15826#issuecomment-1387711967)?
