### ISSUE TITLE
[StartWorkspace] Make sure ensureWorkspaceAuth is called

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#9145]
Today I reopened  two workspaces from yesterday which did not make into the IDE, but the workspace pod actually were there and reported readiness. After investigating with @geropl and @akosyakov, we came to the conclusion that the owner token might not have been set during the workspace startup flow, because all of the supervisor request were returned with code 403. 

Having a look at the StartWorkspace.tsx reveals that we might need to reiterate on the process `ensureWorkspaceAuth` is actually called. Cases to consider:
* workspace will be re-opened in a tab in background and browser window get blurred
* a timed-out workspace tab remained in background

**Comment by geropl** [comment]
Scheduled it.
