### ISSUE TITLE
Remove www.gitpod-staging.com website from Google

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#9149]
### Bug description

Before joining Gitpod, when googling for gitpod docs, I ended up multiple times on the staging domain [www.gitpod-staging.com](https://www.gitpod-staging.com/). It can be very confusing for a user, so I'd like to suggest deindexing the domain from search engines.

It should be possible either with `robots.txt` 
```
User-agent: *
Disallow: /
```
or specifically for google I've found [this](https://support.google.com/webmasters/answer/9689846?hl=en)

### Steps to reproduce

1. Open google
2. Search for `site:www.gitpod-staging.com`

**Comment by jldec** [comment]
I think the main issue is that www.gitpod-staging.com is still up, and being indexed. 

If we don't want take that down or redirect to the main website for some reason, I would recommend adding canonical links to all the pages on that old site so that they don't steal seo juice from www.gitpod.io.

`<link rel="canonical" href="https://www.gitpod.io/<matching-page-on-official-website>">`

**Comment by jldec** [comment]
https://www.google.com/search?q=gitpod+docs+domain%253Awww.gitpod-staging.com

**Comment by geropl** [comment]
@jldec Why not remove it completely? This being a DCS issue is correct I think.

@MichaelAring Happy to help out, though, with some historical context. :+1:

**Comment by jankeromnes** [comment]
FYI `gitpod-staging.com` is now already de-indexed via `robots.txt` (and `noindex` meta tag).

So only `www.gitpod-staging.com` remains to be taken down, or at least de-indexed.

**Comment by andreafalzetti** [comment]
> FYI `gitpod-staging.com` is now already de-indexed via `robots.txt` (and `noindex` meta tag).
> 
> So only `www.gitpod-staging.com` remains to be taken down, or at least de-indexed.

thanks @jankeromnes, I've updated the issue description

**Comment by jankeromnes** [comment]
FYI, this old website's source code is still available here https://github.com/gitpod-io/retired-gatsby-website (archived)

From the `netlify.toml`, it looks like it's hosted on Netlify. Who owns our Netlify hosting, and could take this old website down? (Maybe @svenefftinge?)

**Comment by chrifro** [comment]
>So only www.gitpod-staging.com remains to be taken down, or at least de-indexed.

If we can't take it down, could we at least de-index it? cc @nisarhassan12

**Comment by nisarhassan12** [comment]
> If we can't take it down, could we at least de-index it? cc @nisarhassan12

The repository is Archived so we can't make any changes there. Once un-archived I'll be able to make the changes. 

I don't have the rights/access to un-archive  https://github.com/gitpod-io/retired-gatsby-website Can someone with proper rights do that? Thanks
