### ISSUE TITLE
Can't get open my workspace

### ISSUE THREAD

**Issue by M1k3L1m3** [gitpod-io/gitpod#916]
**Describe the bug**
When I click open on my work space it loads and then says Evicted: Pod The node had condition: [DiskPressure].
Please file an issue if you think this is a bug.

**To Reproduce**
1. Open my workspace

**Expected behavior**
I expected for the code editor to open like normal and be able to edit my github repo

**Additional Information**
This is from google dev tools console:
www.googletagmanager.com/gtag/js?id=UA-71727855-2:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
start-workspace.tsx:116 /start: started workspace instance: 2e5a3259-01dd-42ba-a04a-fb164c6b62cb

**Comment by JesterOrNot** [comment]
My first guess is this is an issue with Kubernetes or maybe whoever is controlling the wifi is blocking it

**Comment by M1k3L1m3** [comment]
It is definitely not the WiFi as it is at home and there is no filtering on it

**Comment by JesterOrNot** [comment]
ok cool then can you send an example repo?

**Comment by M1k3L1m3** [comment]
Oh it looks like it’s working now

**Comment by JesterOrNot** [comment]
K cool then this was probably a Kubernetes issue

**Comment by svenefftinge** [comment]
Yes, this is an issues with the underlying node. We've improved the garbage-collection and the monitoring.
