### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by wizozz** [gitpod-io/gitpod#9160]
### Bug description

Can't install the wasm-pack. It gives me a "permission denied" error. Even doing the same thing with sudo gives me the same error. 

### Steps to reproduce

```
$ curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
info: downloading wasm-pack
failed to copy executable to `/snap/bin/wasm-pack`
Caused by: Permission denied (os error 13)
```
Same thing happens even with sudo

```
$ sudo curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
[sudo] password for ozert: 
info: downloading wasm-pack
failed to copy executable to `/snap/bin/wasm-pack`
Caused by: Permission denied (os error 13)
```

### Expected behavior

wasm-pack should install without an error.

### Anything else?

I don't understand why I get a "permission denied" error even when using sudo.

**Comment by wizozz** [comment]
"Can you provide repro repo?"

I don't know what that is, or how to provide it.

**Comment by sagor999** [comment]
>"Can you provide repro repo?"
>I don't know what that is, or how to provide it.

How can I reproduce the same behavior? Are you opening gitpod from public repo or private repo? If it is public, can you share link to it?
If it is private, can you create a minimum example of this problem in public repo?

**Comment by wizozz** [comment]
I'm doing this on my own local linux laptop, I'm not opening gitpod other than writing about this issue.

I don't know how you can replicate this without access to my laptop.

**Comment by sagor999** [comment]
@wizozz try this command instead: `curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sudo sh`

though if you are not using gitpod then I am not sure why you are opening an issue in gitpod repo then. :)

**Comment by wizozz** [comment]
You're right. Your last command worked, thanks, and it was my mistake to post it into wrong place. Sorry.
