### ISSUE TITLE
Epic: Admin page to configure OAuth connections

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#9164]
### Summary

Self-hosted Gitpod instances need to be configured with at least one git-provider for OAuth.
Currently this happens via a special prompt after installation (see image below)

It would be better to do this via an Admin page so that (multiple) git-providers can be configured and easily managed (added, modified, removed) over time.

![Screenshot 2022-04-06 at 14 47 38](https://user-images.githubusercontent.com/849592/162081318-aaa5cc16-cc4f-4af9-9acb-aaf5e7781fe4.png)

### Context
[discussion](https://gitpod.slack.com/archives/C01KLC56NP7/p1649233947286539) (internal)

### Value
- makes it possible to change/delete/add configurations later
- opens the possibility of replacing the OAuth step after install with an admin step that you can come back to e.g. to setup other SSO or auth mechanisms.
- gives us an eventual route to replace the awkward user-owned admin of git registrations which we have now (assuming we evolve to some kind of multi-tenant admin :wink:)

### Acceptance Criteria
As an admin, I can add, modify, or delete authoritative git providers for a Gitpod instance.

### Measurement
Measure usage.

**Comment by geropl** [comment]
We're putting this on hold, as it's unclear to what extend install-time config like this should be configurable from within the product vs. from the outside.

**Comment by atduarte** [comment]
@geropl is this in progress?

**Comment by geropl** [comment]
@atduarte I don't think we are using this one, and can close, It matches the current work around "Git auth for Orgs" close enough, but I think we have https://github.com/gitpod-io/gitpod/issues/15955 for this. :+1:
