### ISSUE TITLE
Adding > Removing > (re)Adding a project breaks prebuilds

### ISSUE THREAD

**Issue by NMichas** [gitpod-io/gitpod#9168]
### Bug description

If you add a project to prebuilds, let it run its prebuild phase, remove it, and then re-add it, seems to break the prebuilds functionality.

### Steps to reproduce

1. Add a project in prebuilds.
2. Let it run its prebuild phase.
3. Remove the  project from prebuilds.
4. Add the project back in prebuilds.

After re-adding the projects:
- On the Projects page, you see that "No recent prebuilds" exists:
![Projects_—_Gitpod](https://user-images.githubusercontent.com/2218296/162120128-81f948e1-9648-469f-84db-3631ba8e05ab.png)

- If you try to manually run a prebuild by clicking on the project, using the burger icon, and choosing "Run prebuild (master)" you get this:
![Cursor_and_Prebuild_—_Gitpod](https://user-images.githubusercontent.com/2218296/162121484-3f50ddb8-c38c-493a-8f00-db9e780cb135.png)

### Expected behavior

Prebuilds should continue working after re-adding the project.

### Example repository

https://github.com/NMichas/gitpod-test/blob/master/.gitpod.yml

I also tried it with other repos too and the behaviour seems to be the same.

### Anything else?

This seems to be somehow related to not properly deleting the project prebuild when removing the project from the prebuilds:

- After step (3) above, don't re-add the project in prebuilds.
- Try to start a new workspace for the project.
- The project uses the previously created (but now deleted) prebuild, although no prebuild should exist for this project anymore:
![Get_Started_—_gitpod-test_—_Gitpod_Code](https://user-images.githubusercontent.com/2218296/162123045-8547608b-282a-4ce7-b4b0-80a47018d1be.png)

**Comment by NMichas** [comment]
I pushed an addition to .gitpod.yaml which was picked up by Gitpod and created the prebuild correctly, so the prebuilds functionality is now restored in the test project.

I still feel there might be some small glitch here but feel free to close this issue now.

**Comment by pawlean** [comment]
Thank you for the update @NMichas! Please raise another issue if you see this again in the future.
