### ISSUE TITLE
GitPod fails to open workspace

### ISSUE THREAD

**Issue by RossComputerGuy** [gitpod-io/gitpod#917]
**Describe the bug**
SHA cannot be parsed for repository URL

**To Reproduce**
Open this: https://gitpod.io/#https://github.com/RossComputerGuy/stardustos

**Expected behavior**
A workspace to open

**Additional Information**

**Comment by JesterOrNot** [comment]
the Dockerfile specified in the .gitpod.dockerfile does not exist I've sent a PR
https://github.com/RossComputerGuy/stardustos/pull/8

**Comment by RossComputerGuy** [comment]
The docker file does exist https://github.com/RossComputerGuy/stardustos/blob/master/Dockerfile

**Comment by JesterOrNot** [comment]
no, you specified .gitpod.dockerfile in the .gitpod.yml my PR changes it to specify Dockerfile which is the dockerfile you wanted to be built

**Comment by RossComputerGuy** [comment]
Ah, I thought it was a prefix to tell it to use a file. Thanks for the fix.

**Comment by RossComputerGuy** [comment]
Ok, it failed to open
![image](https://user-images.githubusercontent.com/19699320/68707946-8d520100-0547-11ea-85be-2b8c3c392bbb.png)

**Comment by JesterOrNot** [comment]
this is being addressed in #813

**Comment by JesterOrNot** [comment]
please bring your example there

**Comment by svenefftinge** [comment]
closing this in favor of #813
