### ISSUE TITLE
[self-hosted] Add bitbucket.org to the list of auth providers configurable during Gitpod install  

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#9172]
There is currently no self-hosted configuration UI to setup OAuth for bitbucket.org. Only GitLab and GitHub are supported.

Self-hosted Gitpod users should be able to authenticate with bitbucket.org.

**Comment by Shaked** [comment]
Is there any workaround for that?

**Comment by jldec** [comment]
Scheduled
see discussion ([internal](https://gitpod.slack.com/archives/C02EN94AEPL/p1651738961035579?thread_ts=1651647251.829929&cid=C02EN94AEPL))

**Comment by Shaked** [comment]
> Scheduled see discussion ([internal](https://gitpod.slack.com/archives/C02EN94AEPL/p1651738961035579?thread_ts=1651647251.829929&cid=C02EN94AEPL))

Unfortunately Slack is only for gitpod domain or invites only. 

Is there a way to integrate bitbucket.org without the UI?

**Comment by anuragpathak21** [comment]
My Ticket #9750 was closed referencing this ticket, stating it can be tracked here. As you have moved the discussion internal, community cannot see what is going on. Can you please provide an update on what is the outcome of the discussion. Moreover, I also raised the misleading information on your site stating gitPod self-hosted integrates with BitBucket. It should be updated to "BitBucker Server" untill you provide option for BitBucket Cloud.
