### ISSUE TITLE
Extending workspace timeouts fails when workspaces are running in multiple regions

### ISSUE THREAD

**Issue by andrew-farries** [gitpod-io/gitpod#9174]
### Bug description

If I have workspaces running in multiple regions (eg one in the US and one in the EU), an attempt to extend the workspace timeout in either workspace will fail.

### Steps to reproduce

* Create a workspace in the US region
* Create a workspace in the EU region
* Attempt to extend the workspace timeout in the EU workspace

The attempt to extend the timeout fails with an error like:

![image](https://user-images.githubusercontent.com/8225907/162192910-a08fa6fa-d26f-4ec8-80e6-1f751ed9ffe0.png)

### Expected behavior

It should be possible to extend a workspace timeout regardless of which region my other workspaces are running in.

**Comment by andrew-farries** [comment]
The cause is here:

https://github.com/gitpod-io/gitpod/blob/b459f3a759b644dc40e17399d68f0550fae7bcfa/components/server/ee/src/workspace/gitpod-server-impl.ts#L308-L327

When extending the workspace timeout, we also attempt to extend the timeout in all other running workspaces (why?), but we do so with the wrong `client` - we reuse the one for the region of the workspace where we requested the extension.

**Comment by geropl** [comment]
Thanks for investigating @andrew-farries ! :muscle:  Moved to scheduled. :notebook:
