### ISSUE TITLE
Temp files persist when launching V Repl

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#918]
**Describe the bug**

temp files stay in the current directory when launching the v repl
![image](https://user-images.githubusercontent.com/50386709/68707023-926a7c80-0556-11ea-8dbd-c59fa784b239.png)
**To Reproduce**
https://gitpod.io/#https://github.com/JesterOrNot/Gitpod-V
and run the command `v`
**Expected behavior**
temp files are handled correctly
**Additional Information**
None

**Comment by svenefftinge** [comment]
I don't think this is an issue in Gitpod. Did you check if it behaves different locally?

**Comment by JesterOrNot** [comment]
I just confirmed this is a V issue not a Gitpod issue sorry for the inconvienence
