### ISSUE TITLE
[docker-up] remove experimental and upgrade to latest stable

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#9181]
## Is your feature request related to a problem? Please describe

We tried updating docker and disabling experimental for dockerd [here](https://github.com/gitpod-io/gitpod/pull/9157/files). 

We found that we could disable experimental on dockerd but not docker (it is enabled by default). We learned that Gitpod workspaces prefer the version of docker as specified by the workspace image, and docker-up's is only installed/used if not provided by the workspace image.

### Removed Experimental
1. Review which dockerd features are experimental. Do we depend on any? If yes, leave experimental and create new issue to socialize removing experimental separate from this one.
2. If we do not depend on them, proceed by removing the `experimental` argument for when we start `dockerd`.
3. Test to for breakage.

### Update Docker version
1. Update the [version](https://github.com/gitpod-io/gitpod/pull/9157/files#diff-1a98375c51d985554aee564cbdf04f3013b02e49957b060355b931f4ade6e293R8) of docker used in docker-up
2. Update the version of docker used in `workspace-images` tool-docker chunk. We likely need to [trigger a rebuild](https://github.com/gitpod-io/workspace-images/blob/main/chunks/tool-docker/Dockerfile#L7).
3. Test in a workspace image that does NOT have docker preloaded, docker-up should install docker.
4. Test in a workspace using `workspace-base` using the timestamped image.

## Describe alternatives you've considered

Continue running with experimental, but bump the version up in docker-up and workspace-images.

**Comment by utam0k** [comment]
@iQQBot We have a mechanism for users to pass arguments to docker. We may consider extending this.
https://www.gitpod.io/docs/environment-variables#user-specific-environment-variables

**Comment by atduarte** [comment]
@kylos101 is this still a problem? 🤔
