### ISSUE TITLE
extract IDE service from server

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#9189]
Right now IDE configuration of the workspace is controlled by the server. IDE configuration is maintained by @gitpod-io/engineering-ide, though the deployment of the server is maintained by @gitpod-io/engineering-webapp. Instead we should move IDE configuration (code and configmap) to a new component which can be deployed by the IDE team and establish the interface between server and such service to resolve IDE configuration.

**Comment by akosyakov** [comment]
It came up again while working on JB dev loop optimization we had to change different APIs and code of ws-manager and server. We should rather encapsulate such logic in our component and generalize APIs & internals of ws-manager and server.

It will allow us more fine grain optimization without relying on other teams.

**Comment by jeanp413** [comment]
This week we need to do migration

**Comment by loujaybee** [comment]
This one should be an epic according to @iQQBot, let's discuss and break this one down 🙏 

Assigning to myself to work with Pudong on that!
