### ISSUE TITLE
Error: ER_BAD_FIELD_ERROR: Unknown column 'ws.workspaceImage' in 'field list'

### ISSUE THREAD

**Issue by TJphonix** [gitpod-io/gitpod#920]
The error message in the title box appears when i launch the url:

https://gitpod.io/#https://github.com/benzino77/tasmocompiler

so the app doesn't start.

Can you check it?

Thank You

**Comment by meysholdt** [comment]
this should be fixed by now. Can you try again?

**Comment by TJphonix** [comment]
Now it works.Thank you 
-------- Messaggio originale --------Da: Moritz Eysholdt <notifications@github.com> Data: 13/11/19  11:16  (GMT+01:00) A: gitpod-io/gitpod <gitpod@noreply.github.com> Cc: TJphonix <tjphonix@libero.it>, Author <author@noreply.github.com> Oggetto: Re: [gitpod-io/gitpod] Error: ER_BAD_FIELD_ERROR: Unknown column 'ws.workspaceImage' in 'field list' (#920) this should be fixed by now. Can you try again?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/gitpod-io/gitpod/issues/920?email_source=notifications\u0026email_token=ACHCZIPLNG6XHFJW3F72KPLQTPHWRA5CNFSM4JMWTKA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED5TVGY#issuecomment-553335451",
"url": "https://github.com/gitpod-io/gitpod/issues/920?email_source=notifications\u0026email_token=ACHCZIPLNG6XHFJW3F72KPLQTPHWRA5CNFSM4JMWTKA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED5TVGY#issuecomment-553335451",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by meysholdt** [comment]
awesome! And sorry for the inconvenience.
