### ISSUE TITLE
Unable to create workspace pointing to GitHub package

### ISSUE THREAD

**Issue by pattacini** [gitpod-io/gitpod#921]
**Describe the bug**
I'm unable to spawn a Gitpod workspace based on a Docker image hosted on GitHub Package Registry.

**To Reproduce**
- Simply visit https://github.com/vvv-school/tutorial_cartesian-interface and click on the blue badge.
- The GitHub package is available at https://github.com/vvv-school/vvv-school.github.io/packages/54038.
- I can pull the docker image correctly on to my local machine.

**Expected behavior**
I should be able to create the workspace within Gitpod. Is there anything known I'm missing that prevents me from doing that?

**Additional Information**
Here's below the message I got from Gitpod while trying this out:
```
Error: Request createWorkspace failed with message: 13 INTERNAL: cannot resolve base image: Error response from daemon: Head https://docker.pkg.github.com/v2/vvv-school/vvv-school.github.io/gitpod/manifests/1.0: no basic auth credentials
```

Thanks in advance!

**Comment by pattacini** [comment]
It turned out that, differently from DockerHub, GitHub Package Registry forces users to be authenticated even only for pulling the image... 😞

**Comment by meysholdt** [comment]
Hi @pattacini, thank you for reporting this. I wasn't aware either that GitHub Package Registry does not allow anonymous pulls. Is this maybe going to change when it's going GA?

Let's leave this issue open to discuss if we can/want to authenticate with the GitHub Package Registry when we do a pull.

**Comment by pattacini** [comment]
Thanks @meysholdt for dealing with this 👍 

Actually, GitHub Package Registry is still in beta and I don't know what they have on their roadmap.

In my opinion, it would be really awesome to have Gitpod able to automatically authenticate with the Registry, given the native integration of Gitpod with GitHub 🚀

**Comment by pattacini** [comment]
Ref: https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32888/highlight/true#M1294.

**Comment by pattacini** [comment]
However, it seems GitHub will remove the need for authentication for the public container: https://github.com/robotology-dependencies/robotology-vcpkg-binary-ports/issues/3.

**Comment by pattacini** [comment]
Time has passed, GitHub Packages are now official, but we still need to authenticate to pull a public docker image.  
@meysholdt do you deem it would be useful to include such authentication within Gitpod?

**Comment by pattacini** [comment]
Just wanted to let you know that starting today it's possible to pull images hosted on [GitHub Container Registry][1] using anonymous access 🎉

[1]: https://github.blog/2020-09-01-introducing-github-container-registry/
