### ISSUE TITLE
GITPOD_REPO_ROOT ENV variable changed from expectation

### ISSUE THREAD

**Issue by cjensenius** [gitpod-io/gitpod#9223]
### Bug description

Our gitpod launch scripting uses certain GITPOD_ namespaced variables extensively, this morning we noticed no existing workspaces were functional. We traced the issue to this commit which appears to alter the content of GITPOD_REPO_ROOT - https://github.com/gitpod-io/gitpod/commit/3bf6664eac071a13076bb2cc2f356fa7b73ab610

This changed the variable output from `/workspace/myrepo` to `/workspace` and our launch scripts no longer `cd` into the directory properly to being initializing the development stack

### Steps to reproduce

Launch any existing workspace and the value returned by GITPOD_REPO_ROOT will be different than the newly launched workspace:

New launch:
![image](https://user-images.githubusercontent.com/1717750/162750990-93b20e4e-e4b8-4e9e-92de-f09674f614c1.png)
Existing workspace:
![image](https://user-images.githubusercontent.com/1717750/162751058-e05bf18f-5488-4a5f-9c2c-906cb7003355.png)

### Workspace affected

greenit-spower-w261s30hxpn

### Expected behavior

The $GITPOD_REPO_ROOT ENV var always returns the same value for new or existing workspaces

**Comment by cjensenius** [comment]
Old snapshots, or snapshots of newly launched (working) workspaces both exhibit the behavior of having a different GITPOD_REPO_ROOT value

**Comment by j0nes2k** [comment]
+1 on this, we are experiencing the same issue

**Comment by cjensenius** [comment]
@j0nes2k - We worked around the immediate issue by making a workspace variable of `GITPOD_REPO_ROOT` on https://gitpod.io/variables that has the path we normally expect scoped to the appropriate repo(s)

**Comment by davemecha** [comment]
This seems to be a new issue. I have startup scripts that depend on that env variable and they recently fail on restarted workspaces.

As another workaround: There is `$THEIA_WORKSPACE_ROOT` that also exists in vscode workspaces and contains the workspace root path.

**Comment by davemecha** [comment]
After my workspace restart of today, the problem seems to have vanished for me. `$GITPOD_REPO_ROOT` is on the expected value again.

**Comment by axonasif** [comment]
Perhaps we can close the issue, feel free to reopen if this happens again 😄

**Comment by shaal** [comment]
I experienced the same thing (GITPOD_REPO_ROOT value is `/workspace` instead of `/workspace/<name_of_repo>`) when loading a Gitpod snapshot, see https://github.com/gitpod-io/gitpod/issues/9804
