### ISSUE TITLE
Warn users that prebuilds have been paused for inactive projects

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#9232]
### Problem to solve

In https://github.com/gitpod-io/gitpod/pull/9219 (Cc @jankeromnes) we're introducing pausing prebuilds for inactive projects. While this automatic pause helps in being efficient in consumption, etc, it could be confusing for users when opening project prebuilds to see an empty list of prebuilds without any useful information or call-to-action. 

Cc @easyCZ because https://github.com/gitpod-io/gitpod/issues/8911

### Proposal

Show a warning alert when prebuilds have been paused for a project including the reasoning and a call-to-action to open a new workpace, trigger a prebuild, and enable prebuilds again.

The project card can reuse the same latest prebuild status as now with the label _No recent prebuilds_.

| Project prebuilds | Project card |
|-|-|
| <img width="1440" alt="Prebuilds" src="https://user-images.githubusercontent.com/120486/162792230-ed71a4e0-73a9-4490-a10e-47030404b336.png"> | <img width="432" alt="CARD-AFTER" src="https://user-images.githubusercontent.com/120486/162791468-2620381b-b59d-410e-b25b-f1aad01b4087.png"> |

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3rsi2)

**Comment by jankeromnes** [comment]
Thanks @gtsiolis! I really like your proposed UX (banner, wording).

> it could be confusing for users when opening project prebuilds to see an empty list of prebuilds without any useful information or call-to-action.

Just on a side note, the intent in https://github.com/gitpod-io/gitpod/pull/9219 is not to have an empty Prebuilds list, but a list of cancelled Prebuilds (one for every push you make to your repository), and when you open these cancelled Prebuilds, they should show:

```
(/) Cancelled
Project is inactive. Please start a new workspace for this project to re-enable prebuilds.
```

**Comment by gtsiolis** [comment]
> ... the intent in https://github.com/gitpod-io/gitpod/pull/9219 is not to have an empty Prebuilds list when the Project is inactive, but to have a list of cancelled Prebuilds ...

**question**: Ah, I see! Isn't this more confusing? What is the value of keeping a list of non-existing prebuilds or potentially to-be-created prebuilds in a list, especially since we also garbage collect existing prebuilds?
