### ISSUE TITLE
Error opening snapshot on some github repos - cannot initialize workspace: did not find snapshot

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#9244]
- start a workspace on this public github repo - https://github.com/jldec/date-plus
- share snapshot URL
- try to open the URL (tried with same user session or different Gitpod user)
- `cannot initialize workspace: did not find snapshot`
![Screenshot 2022-04-12 at 06 23 43](https://user-images.githubusercontent.com/849592/162886948-5c2d2c1a-26c6-4530-a8c1-83bfe26f492c.png)

####
- other repos are ok e.g. https://github.com/jldec/fullstack works
- may be related to #8309 
- suspect that this related to OTS but not sure

**Comment by geropl** [comment]
Hm, sounds it could be related to #9245 . Which in turn was triggered by #9007.
I will test quickly.

**Comment by geropl** [comment]
I reproduced again with:
 - original workspaceid: `jldec-dateplus-mahp1259cfh`
 - snapshot path: (can share in Slack: it's correctly set, and exists in the bucket :heavy_check_mark: )
 - workspace that failed when started on the snapshotlink: `copper-quokka-k3ku8nx6pfi`

@kylos101 Pulling Team Workspace in here to investigate the content init error (my current suspicion).

**Comment by jldec** [comment]
Confirmed that this still repro's with the repo https://github.com/jldec/date-plus

**Comment by kylos101** [comment]
Scheduled, thank you @geropl for the detective work, and @jldec for the repo detail.
