### ISSUE TITLE
there is a bug. i am unable to open gitpod.

### ISSUE THREAD

**Issue by CodingStudent2019** [gitpod-io/gitpod#925]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by JesterOrNot** [comment]
Can you provide more details and an example repository

**Comment by CodingStudent2019** [comment]
i have a brother in law who uses various different excuses to abuse me for any mistakes that i make in my life, whether its in jobs or with any other aspect of my life

and he uses these mistakes as an excuse to not only call me dumb but stop me from doing good things in life

but when it comes to his sister and his father or anyone else who hates me, my brother in law tells them "it's ok, people make mistakes, let me protect you from the police complaints or court cases that she is making/filing about you and you continue with your life as if you did nothing wrong."

when it comes to my inlaws, they say "we did this wrong in the past, so what, why are you reminding us of our past wrongdoings again and again, we will ignore such guilt tripping from you and continue with life as if we did nothing wrong."

but my inlaws keep accusing me of things that i have not even done and events where i was not even at fault. they say "how can you be so perfect that you do nothing wrong, please take some blame for us."

they guilt trip me all the time about things i have never even done

and when i remind them of the things they have actually done wrong, they say "so what, people do bad things and they move on with life, it doesn't mean we have to allow you to control us because of the bad things we do."

the reason why i am here is to share the audacity of my brother in law

he wants to be my best friend to take me under his control, use me to get freedom for his sister and his family and then abuse me

my inlaws say that i should tolerate abuse from them as well as others because i come from a violent family.

they are telling me "you are indian, you have to obey inlaws."

i said "no problem, i will obey, but your other son is married to an American and he paid her to stay married to her, pay me like her too, but my prices are much, much higher than hers."

if the inlaws are claiming to be indian and want to follow such types of obeying indian traditions why allow their son to marry an American woman?

if nigel is sooooooooooooooooooooooooooooooooo powerful, why are all these laws being introduced that contradict his ideologies?

in the process of saving bhattacharya, envid kutta kataa, envid kutta marr gayaa. envid bhadwa kat gaya.



________________________________

**Comment by Kreyren** [comment]
I don't see how is your life story relevant to gitpod unless you want to write a novel about it using gitpod where it still wouldn't be gitpod's issue unless you found a bug or something is not working as expected, recommends reporting @CodingStudent2019 for potentially compromised account or bot.

**Comment by CodingStudent2019** [comment]
oh wrong email. pls excuse me. my apologies.

________________________________

**Comment by Kreyren** [comment]
@CodingStudent2019 Note that you posted that whole thing on a github that is accesible to everyone on the internet.. O.o

You may want to remove it on https://github.com/gitpod-io/gitpod/issues/925#issuecomment-569432981

**Comment by CodingStudent2019** [comment]
Nigel had to pay his wife to sleep with her and buy her American passport. I don't associate with such people. 🤣🤣

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jankeromnes** [comment]
@CodingStudent2019 Hello. It seems you are posting private emails publicly again. I will lock this conversation to prevent such accidents from happening again.
