### ISSUE TITLE
Prebuild failed with OCI runtime error

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#9250]
### Bug description

Prebuild is failing with `Error response from daemon: OCI runtime create failed: runc create failed: unable to start container process: error closing exec fds: open /proc/self/fd: no such file or directory: unknown` [[internal](https://gitpod.slack.com/archives/C03145ZD98D/p1649754318968489)]

### Steps to reproduce

Unknown.

**Comment by sagor999** [comment]
This seems to have been due to https://www.gitpodstatus.com/incidents/12tvkhs2gyrg
