### ISSUE TITLE
Adjust URL Being Used To Fetch .gitpod.yml Files From GitHub Enterprise Instances

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#9253]
### Bug description

I currently have a self-hosted instance deployed which appears to be ignore the `image: image-name` line in my `.gitpod.yml` file within a repository. For example in my `.gitpod.yml` I've tried:

```yaml
image: node:16.14-buster
```

or

```yaml
image: jimmyb/workspace-laravel
```

but every time the `gitpod/workspace-full` image is loaded. I captured some logs from the build process and as you can see it's pulling the `workspace-full` image - https://ghostbin.linuxbox.ninja/paste/6jyt8

I've tested this on gitpod.io and I cannot replicate the issue there. @MrSimonEmms was also unable to replicate the issue on his self-hosted instance so it sounds like an issue specific to my instance.

Last night I tore down my Kubernetes cluster and rebuilt it from scratch, but the same issue occurs. I am currently on `main.2860` which I updated to from `main.2847` (where the issue existed for me) to no avail.

Is there some sort of setting I can look at that would force the `workspace-full` image to be used? I know if there is no `.gitpod.yml` or image set it will default to the `workspace-full` image, but that's definitely not the case here, I am setting the image to be used, it's just being ignored.

To further troubleshoot, I set my `.gitpod.yml` up as:

```yaml
image: jimmyb/workspace-laravel

vscode:
  extensions:
    - esbenp.prettier-vscode
```

I started a new workspace, it ignored the `image` line and used the `workspace-full` image, but it did install the extension. So it seems it's not completely ignoring the `.gitpod.yml` file.

My cluster is built from k3s, using 3 Ubuntu 20.04.x VMs (1 controller, 2 workers). If any other information about the cluster is needed, please don't hesitate to ask!

Any help on where to look next would be greatly appreciated!

### Steps to reproduce

So here's the thing, I/we can't seem to reproduce this 😩

### Expected behavior

I would expect that the image specified in my `.gitpod.yml` file be used for my workspace instead of the `gitpod/workspace-full` image.

**Comment by jimmybrancaccio** [comment]
Discord thread at - https://discord.com/channels/816244985187008514/963419914809528340

**Comment by corneliusludmann** [comment]
Anyone from team @gitpod-io/engineering-workspace some hints on how to debug this?

**Comment by princerachit** [comment]
@jimmybrancaccio I can't promise that I know the resolution but I can take a look if you share the following with me:
* Public repo on which you are able to reproduce this issue
* Installer generated yaml files (redacted), specifically I want to see configmaps related to image builder

**Comment by jimmybrancaccio** [comment]
Hey @princerachit!

- I don't have the repo public, it's sitting on my GitHub Enterprise instance. That said, there's nothing really special about the repo. I just have a single file in it, `gitpod.yml` with the contents:

```yaml
image: jimmyb/workspace-laravel
```

Hopefully this is the correct information for the configmap for the image-builder. If it's not don't hesitate to let me know, as well as if there's anything else I can provide!

```yaml
apiVersion: v1
data:
  image-builder.json: |-
    {
      "orchestrator": {
        "wsman": {
          "address": "ws-manager:8080",
          "tls": {
            "ca": "/wsman-certs/ca.crt",
            "crt": "/wsman-certs/tls.crt",
            "key": "/wsman-certs/tls.key"
          }
        },
        "pullSecret": "builtin-registry-auth",
        "pullSecretFile": "/config/pull-secret.json",
        "baseImageRepository": "registry.gitpod.fake/base-images",
        "workspaceImageRepository": "registry.gitpod.fake/workspace-images",
        "builderImage": "eu.gcr.io/gitpod-core-dev/build/image-builder-mk3/bob:0d7a2c9dd3c88afe9f843243c29595dcc8242757"
      },
      "refCache": {
        "interval": "6h0m0s",
        "refs": [
          "docker.io/gitpod/workspace-full:latest"
        ]
      },
      "service": {
        "address": ":8080",
        "tls": {
          "ca": "",
          "crt": "",
          "key": ""
        }
      },
      "prometheus": {
        "address": "127.0.0.1:9500",
        "tls": {
          "ca": "",
          "crt": "",
          "key": ""
        }
      },
      "pprof": {
        "address": ":6060"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: gitpod
    meta.helm.sh/release-namespace: gitpod
  creationTimestamp: "2022-04-11T22:13:36Z"
  labels:
    app: gitpod
    app.kubernetes.io/managed-by: Helm
    component: image-builder-mk3
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:image-builder.json: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:component: {}
    manager: helm
    operation: Update
    time: "2022-04-11T22:13:36Z"
  name: image-builder-mk3-config
  namespace: gitpod
  resourceVersion: "11395"
  uid: 20f4f313-61f7-4dac-a82e-05f46f7a0d2e
```

**Comment by princerachit** [comment]
@jimmybrancaccio I asked for a public repo because I suspected that a special character(hidden) might be causing the issue (totally wild guess). Can you create and share a public repo with same .gitpod.yml configuration just so that I don't miss anything.

Also, what do you see in d_b_workspace table for this workspace?

```sql
SELECT * from d_b_workspace where id = 'my-workspace-name'
```

**Comment by jimmybrancaccio** [comment]
@princerachit Ah, that's very interesting about the special character. I can confirm there are none, in fact I first noticed this issue with two different repositories that I know have worked in Gitpod and used the image I specified in the `.gitpod.yml` file. I had ended up creating the `gitpod-test` repository as part of my troubleshooting (so I could have the bare minimum to create a workspace).

I forgot I had created this test repository on GitHub - https://github.com/jimmybrancaccio/gitpod-test

For the entry in MySQL:

```
*************************** 3. row ***************************
                   id: jimmybrancaccio-gitpodte-iys8rb8wtqq
         creationTime: 2022-04-12T15:26:54.445Z
              ownerId: 083f755f-fe74-4779-85ea-2f2026256776
           contextURL: https://my-github-enterprise.com/jimmybrancaccio/gitpod-test
          description: jimmybrancaccio/gitpod-test - master
              context: {"isFile":false,"path":"","title":"jimmybrancaccio/gitpod-test - master","ref":"master","refType":"branch","revision":"92cd51664b067a4fe5b1ec7b54b79dae6149aca5","repository":{"cloneUrl":"https://my-github-enterprise.com/jimmybrancaccio/gitpod-test.git","host":"my-github-enterprise.com","name":"gitpod-test","owner":"jimmybrancaccio","private":false},"normalizedContextURL":"https://my-github-enterprise.com/jimmybrancaccio/gitpod-test","checkoutLocation":"gitpod-test"}
               config: {"ports":[{"port":3000}],"tasks":[],"image":"docker.io/gitpod/workspace-full:latest","_origin":"default"}
          imageSource: {"baseImageResolved":"docker.io/gitpod/workspace-full:latest"}
    imageNameResolved: registry.my-gitpod-instance.com/workspace-images:37fa6b72cbb0b2b1459a59acbe862f31a820b2db62d740d3ac57fb93d357526a
             archived: 0
            shareable: 0
        _lastModified: 2022-04-12 15:26:54.895996
              deleted: 0
                 type: regular
baseImageNameResolved: docker.io/gitpod/workspace-full@sha256:b484ad49d47bf70776de1d1333379d6b5f1d56c0a3fc1f31a24eb273ef772e3e
          softDeleted: NULL
               pinned: 0
      softDeletedTime: 
   contentDeletedTime: 
    basedOnPrebuildId: 
    basedOnSnapshotId: 
            projectId:
```

**Comment by jimmybrancaccio** [comment]
I took a look at server component logs today and I did notice this, I wonder if it could be related?

```
{"component":"server","severity":"DEBUG","time":"2022-04-14T16:14:27.658Z","context":{"userId":"083f755f-fe74-4779-85ea-2f2026256776"},"message":"Config string undefined, using default config","payload":{"repoCloneUrl":"https://github-enterprise-url.com/jimmybrancaccio/gitpod-test.git","revision":"92cd51664b067a4fe5b1ec7b54b79dae6149aca5"}}
```

**Comment by jimmybrancaccio** [comment]
Ok, so I'm thinking this is related to me using GitHub Enterprise. I created an app on GitHub.com and added that as an integration on my Gitpod instance. I then spun up a workspace using `https://github.com/jimmybrancaccio/gitpod-test` and what do you know, it worked fine and used the image I had defined in `.gitpod.yml`.

So now we need to figure out why... 🤔

**Comment by jimmybrancaccio** [comment]
Could it be related to #9126?

**Comment by princerachit** [comment]
@gitpod-io/engineering-webapp based on the findings above by @jimmybrancaccio  do you think this is something that is under your expertise?

**Comment by jimmybrancaccio** [comment]
Hey @jankeromnes! The URL looks like:

```
https://raw.my-github-enterprise.com/jimmybrancaccio/gitpod-test/master/.gitpod.yml
```

So it seems to be a bit different, and perhaps this is the cause? My GitHub Enterprise version is 3.4.1.

**Comment by jimmybrancaccio** [comment]
I just did a little more work and determined things work fine on `release-2022.02.0.1` in combination with my GitHub Enterprise instance (thankful I have a secondary instance!).

```
gitpod /workspace/gitpod-test (master) $ node -v
v16.14.2

gitpod /workspace/gitpod-test (master) $ ls -la ~/.config/composer/vendor/bin/
total 20
drwxr-xr-x 2 gitpod gitpod 4096 Apr 10 21:38 .
drwxr-xr-x 8 gitpod gitpod 4096 Apr 10 21:38 ..
-rwxr-xr-x 1 gitpod gitpod 3221 Apr 10 21:38 laravel
-rwxr-xr-x 1 gitpod gitpod 3242 Apr 10 21:38 phpcbf
-rwxr-xr-x 1 gitpod gitpod 3239 Apr 10 21:38 phpcs

gitpod /workspace/gitpod-test (master) $ cat .gitpod.yml 
image: jimmyb/workspace-laravel
```

So it looks like 9d4c6f2 may have broken things?

Ok, didn't submit comment cause I wanted to test more, so here's the outcome of testing more...

I change the image being used for the server component to to `eu.gcr.io/gitpod-core-dev/build/server:main.2630` and opened a workspace using my GitHub Enterprise repository. It worked fine..so my hunch is that something in #8574 perhaps 9d4c6f2 broke things.

**Comment by princerachit** [comment]
Thanks for taking a look @jankeromnes , I am removing this from workspace team's inbox

**Comment by jankeromnes** [comment]
> So it looks like https://github.com/gitpod-io/gitpod/commit/9d4c6f26b72fc9189640ea8bb506833bd73977fb may have broken things?

@jimmybrancaccio I don't believe that commit broke things, because it replaced an older format that also looks different from yours:

```
https://${host}/${org}/${name}/raw/${commitish}/${path}
```

In your case, it looks like your GitHub Enterprise uses a Raw URL format that is similar to what `github.com` uses today. I wonder if the correct solution is to maybe always use the `github.com` format, even for GitHub Enterprise (assuming that all modern GitHub Enterprises use that newer URL format)?

I.e. we could remove the `"github.com"` check from:

https://github.com/gitpod-io/gitpod/blob/1998a9809af2fa205306c60988c7ecd8ada1a586/components/server/src/github/api.ts#L52-L55

and always use the `raw.<domain>` format? 🤔

**Comment by jimmybrancaccio** [comment]
@jankeromnes It's definitely possible that _isn't_ the commit that broke things, I'm kind of guessing here / throwing things out hah.

I do have subdomain isolation enabled in my GitHub Enterprise instance.

<img width="792" alt="github-enterprise-settings-1" src="https://user-images.githubusercontent.com/405585/164278923-50d0ffd8-2c56-4012-b558-c162cd98d5e9.png">

<img width="464" alt="github-enterprise-settings-2" src="https://user-images.githubusercontent.com/405585/164278967-3debf4b5-6e70-4974-bb03-890b73300abf.png">

So I am not sure we should always use the format that `github.com` uses as I believe the URL schema would be different if I toggled off the subdomain isolation setting.

**Comment by AlexTugarev** [comment]
The proper way to solve this is to make a [contents](https://docs.github.com/en/rest/repos/contents) request to read the raw URL from response, or event use that request to fetch the content.
