### ISSUE TITLE
"You are not signed into any accounts" when opening a workspace

### ISSUE THREAD

**Issue by eric-wieser** [gitpod-io/gitpod#9257]
### Bug description

If I go to https://gitpod.io/workspaces, I am logged into gitpod, and https://gitpod.io/integrations shows a green dot next to github

However, if I open my workspace at https://leanprovercommu-mathlib-rtafbj57tv3.ws-eu39a.gitpod.io/, it:

* Does not respect my color theme setting
* Shows me as not logged in:
![image](https://user-images.githubusercontent.com/425260/162979565-2803d96c-c303-4364-8916-ee7882ec74fc.png)
* Does not allow me to `git push` as a result

### Steps to reproduce

Create a new workspace from a PR, the above behavior persists

### Workspace affected

leanprovercommu-mathlib-rtafbj57tv3

### Expected behavior

I should be logged into gitpod within the workspace like I usually am

**Comment by axonasif** [comment]
Hey @eric-wieser, are you still facing this issue? It might have been due to the incidents that happened recently: https://www.gitpodstatus.com

**Comment by eric-wieser** [comment]
I saw it a few more times sporadically yesterday, but all seemed fine today. I'll reopen if the problem returns.
