### ISSUE TITLE
OutOfmemory: Pod Node didn't have enough resource: memory

### ISSUE THREAD

**Issue by cjensenius** [gitpod-io/gitpod#9259]
### Bug description

I am attempting to launch a workspace I used yesterday and am receiving the following message and am redirected to https://gitpod.io/start/?not_found=true#beige-sawfish-fhz7d4b46sg

OutOfmemory: Pod Node didn't have enough resource: memory, requested: 3435973837, used: 83050574648, capacity: 66387656704

![image](https://user-images.githubusercontent.com/1717750/162983287-2938cbc8-b7e2-427f-b8d9-8e399c7a600c.png)

### Steps to reproduce

Click workspace URL https://gitpod.io/start/#beige-sawfish-fhz7d4b46sg
Wait short time
Receive error

### Workspace affected

beige-sawfish-fhz7d4b46sg

### Expected behavior

Workspace launches without error

**Comment by pawlean** [comment]
Hi @cjensenius! We currently have an ongoing incident that may be affecting this, please see [Gitpod Status.](https://www.gitpodstatus.com/)

**Comment by sagor999** [comment]
This has been fixed at least 2 weeks ago and shouldn't happen again (fix was in k8s 1.23.6 which we upgraded to)

**Comment by MouniR-123** [comment]
@sagor999 kubernetes version 1.22.6, we are seeing this issue "Pod Node didn't have enough resource: memory, requested: 8589934592, used: 10903093248, capacity: 13208985600"
