### ISSUE TITLE
Epic: Improve experience using ports with Gitpod

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#9262]
We will have almost parity of ports features between JetBrains, VS Code and CLI. 

Following the introduction of: 
1. https://github.com/gitpod-io/gitpod/issues/9700
1. https://github.com/gitpod-io/gitpod/issues/10581
1. https://github.com/gitpod-io/gitpod/issues/10835
1. https://github.com/gitpod-io/gitpod/issues/9286
1. https://github.com/gitpod-io/gitpod/issues/11616
1. https://github.com/gitpod-io/gitpod/issues/7408

Beyond those issues, we can look at introducing some "value add" features across all three main clients (JetBrains, VS Code and CLI) for things like grouping, hiding/showing ports) etc. For example:

1. Forwarded / exposed ports experience
1. Bi-directional port management (configuration drift)
1. https://github.com/gitpod-io/gitpod/issues/13777
1. https://github.com/gitpod-io/gitpod/issues/7764
1. https://github.com/gitpod-io/gitpod/issues/10294
1. https://github.com/gitpod-io/gitpod/issues/10275
1. https://github.com/gitpod-io/gitpod/issues/10408
1. https://github.com/gitpod-io/gitpod/issues/6687
1. https://github.com/gitpod-io/gitpod/issues/13069
1. https://github.com/gitpod-io/gitpod/issues/10448
1. https://github.com/gitpod-io/website/issues/2958

**Completed**
1. https://github.com/gitpod-io/gitpod/issues/9908
1. https://github.com/gitpod-io/gitpod/issues/6240
1. https://github.com/gitpod-io/gitpod/issues/10248
1. https://github.com/gitpod-io/gitpod/issues/9930
1. https://github.com/gitpod-io/gitpod/issues/6993
1. https://github.com/gitpod-io/gitpod/issues/10449
1. https://github.com/gitpod-io/gitpod/issues/11154
1. https://github.com/gitpod-io/gitpod/issues/7662

Related internal conversation(s) [[1](https://gitpod.slack.com/archives/C03372UP877/p1649788554906039)][[2](https://www.notion.so/gitpod/IDE-Discovery-Konrad-Lou-Vizlib-596bb89fe94c4d0f970f9dba53243b5e)] and feedback on Twitter [[1](https://twitter.com/mikepb78/status/1483705407075876864?s=20&t=jcSnhuRByuqQNexd53zMsw)]

**Comment by konne** [comment]
@loujaybee please add these issues to the epic 
https://github.com/gitpod-io/gitpod/issues/9285
https://github.com/gitpod-io/gitpod/issues/9286
https://github.com/gitpod-io/gitpod/issues/9287
https://github.com/gitpod-io/gitpod/issues/9289

**Comment by shaal** [comment]
Can #7012 be part of this improvement?
I tried using names and descriptions for ports but couldn't see it in the VSCode interface in the browser
https://github.com/shaal/DrupalPod/blob/port-descriptions/.gitpod.yml#L38

**Comment by akosyakov** [comment]
> I tried using names and descriptions for ports but couldn't see it in the VSCode interface in the browser
https://github.com/shaal/DrupalPod/blob/port-descriptions/.gitpod.yml#L38

@jeanp413 @felladrin a regression?

**Comment by felladrin** [comment]
🤔 The code I [added on openvscode-server](https://github.com/gitpod-io/openvscode-server/pull/258/files#diff-e609d3d4a25fd55a970f555aecdf223dffca767f4d373ea439058bb88244acf3) is [still on gp-code/main](https://github.com/gitpod-io/openvscode-server/blob/8df396bfb2e2f641dfabb7df615521d07c68832d/extensions/gitpod-web/src/extension.ts#L408-L412).

**Comment by sgarner** [comment]
If I can make a suggestion/feature request here... Would it be feasible to show open ports on the Gitpod "Running Workspace" page? i.e. the ports could be listed here:

<img width="606" alt="image" src="https://user-images.githubusercontent.com/904004/167513978-98b1ca46-04b0-4c5d-8ca9-221db0bf7264.png">

I imagine it's a common use case that people run a web server in Gitpod when developing web projects, and want to open up their development site in a browser when opening a workspace. 

When using Gitpod with a desktop IDE, whether VS Code or JetBrains, you currently lose the UI for "Ports" which only exists in the web version of VS Code. So I find I have to open the workspace in the desktop IDE and also select "Open in Browser" (to open the workspace in the web version of VS Code) just to access the port URL. This feels unnecessarily tedious - if the ports could be shown on the workspace page it would streamline things.

**Comment by loujaybee** [comment]
@sgarner, thanks for the feedback

> When using Gitpod with a desktop IDE, whether VS Code or JetBrains, you currently lose the UI for "Ports" which only exists in the web version of VS Code. 

**JetBrains** - Can show ports, but only when you use a run configuration (currently), they are working on a more generic ports view. There is a port forwarding view, but it doesn't auto-detect ports like VS Code on browser/desktop (yet). 

![image](https://user-images.githubusercontent.com/5528307/171455941-e9f784c6-541d-4f87-9d4e-d7d2564d1ea7.png)

**VS Code Desktop** - There is a ports view in VS Code Desktop, but it's at the bottom of the screen, next to terminal. We are looking to update this view so it's the same in both desktop and browser, soon, please see: https://github.com/gitpod-io/gitpod/issues/7408

![image](https://user-images.githubusercontent.com/5528307/171455910-36786f27-37d4-42ad-92bb-0f409cdae861.png)

**CLI**  - For the CLI (as a workaround in any IDE or editor, or for Vim / CLI users, you can now see ports using `gp ports list` => https://github.com/gitpod-io/gitpod/pull/10388 (docs update coming soon, and additions such as toggling visibility via CLI coming soon, also). 

For all of the above there are some improvements to the docs coming: https://github.com/gitpod-io/website/pull/2126, not released yet, but you can view the markdown and it should explain the above a bit more 🙏 

> I imagine it's a common use case that people run a web server in Gitpod when developing web projects, and want to open up their development site in a browser when opening a workspace.

Have you seen the `onOpen` flag in gitpod.yml, this should take effect in all IDE's, desktop and browser, however in JetBrains there is no preview option. Please see: https://www.gitpod.io/docs/references/gitpod-yml#portsnonopen

I think you might also be interested in: 

- https://github.com/gitpod-io/gitpod/issues/9017

Let me know if you have questions on the above! Lots more improvements coming for ports in the coming weeks 🙏

**Comment by sgarner** [comment]
@loujaybee thanks so much for the detailed response! 👋 

> I doubt we'll integrate ports into that view. I think having a dedicated preview feature is more likely #9017 to resolve this use case. 

Preview workspaces will be a nice feature for reviews but I don't think they relate to this use case at all. I need to open my site in the browser while I'm working on it in my development workspace.

> **JetBrains** - Can show ports, but only when you use a run configuration (currently), they are working on a more generic ports view. There is a port forwarding view, but it doesn't auto-detect ports like VS Code on browser/desktop (yet).

This seems to be a different thing as well. I just want to list the ports that are exposed on the Gitpod instance and get the preview link, not configure port forwarding.

> **VS Code Desktop** - There is a ports view in VS Code Desktop, but it's at the bottom of the screen, next to terminal. We are looking to update this view so it's the same in both desktop and browser, soon, please see: #7408

In VS Code Web, I see:

<img width="358" alt="image" src="https://user-images.githubusercontent.com/904004/171541006-75bc4008-5dd4-46c6-bec0-960874b7c2e5.png">

Whereas when I look at the Ports view in VS Code Desktop, it's always empty:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/904004/171540850-6ac2cfad-c9ba-4409-beaf-365484693828.png">

I can manually add a port here to forward it to localhost and then open `http://localhost:8002`, and this works, but it's different from the desired UX from Web where I can simply open the `https://8002-org-project-xxxxxxxxxx.ws-us00.gitpod.io/` URL directly.

If you can match the functionality of the Ports view from VS Code Web on Desktop, which seems to be the plan in #7408 , that would be a good solution.

> **CLI** - For the CLI (as a workaround in any IDE or editor, or for Vim / CLI users, you can now see ports using `gp ports list` => #10388 (docs update coming soon, and additions such as toggling visibility via CLI coming soon, also).

This is great news! I see that `gp preview $(gp url 8002) --external` would also be a useful command for me, which I didn't know before.

> Have you seen the `onOpen` flag in gitpod.yml, this should take effect in all IDE's, desktop and browser, however in JetBrains there is no preview option. Please see: https://www.gitpod.io/docs/references/gitpod-yml#portsnonopen

Yes, I've been using that for a while with `open-preview` and it works well in VS Code Web. But nothing happens when I launch my workspace in VS Code Desktop. Is support for `onOpen` on desktop a new feature or does it depend on something I'm missing?

I was going to say it doesn't work in JetBrains IDEs either - but while writing this I found there's an update to the JetBrains Gateway application (2022.2 EAP) and the Gitpod Gateway plugin, after installing those updates then launching my workspace again it offered to open the port marked with `open-preview` in a browser exactly as I was hoping for. 🚀

**Comment by loujaybee** [comment]
Adding some feedback from a user in the community. 

> VS Code Desktop ports view doesn't have a Make public option or a correct link to preview my website in the browser. 2. gp ports doesn't have a way to make a port public instead of private from what i can tell. 3. Myself. When logging into my web app while i'm developing, I need to change its port to public for next-auth to be able to login properly, and then I change it back to private. This is because, for some bizarre reason, the method to get the csrf token that you use on the server side is the same as the one you use on the client side and makes a fetch request using the nextauth_url, which IMO is rather idiotic, but then again, I think that about a few of their design decisions, but I need to use this method in my custom credentials provider. As I write this, it occurred to me that I could just get the token from the cookie in the request object and verify it's legitimacy, instead of using their dumb method that depends on a fetch request, so I have gone ahead and changed that. So this isn't necessarily an issue for me now that I just changed that, but this is an example of an edge case where the ability to toggle between public and private ports without opening up the browser IDE is beneficial.

**Comment by davemecha** [comment]
I'm really not happy with the new ports view but I'm not sure if I should open new tasks for them. I've got the following issues.

* The new ports view is sooo slow. When opened, I have to wait too long till I can use it. (I assume this is already reported in #11426) 
* I don't like the location of the new ports view. I often need to always see my terminal, but I also want to access the ports view. I tried various solutions, but none were helpful:
* The view is too wide to be displayed on more narrow parts of the UI and actions are not accessible.

![Screenshot 2022-10-09 14 27 13](https://user-images.githubusercontent.com/137976/194756852-ee9b2064-15fc-4f63-baf6-7e425200be9d.png)  ....... ![Screenshot 2022-10-09 14 17 30](https://user-images.githubusercontent.com/137976/194756857-ca887766-9c42-4dcf-8e8a-3d78e365d301.png)

* Please place address & actions in separate columns
* It would be helpful to be able to at least customize the view with options to:
  * remove the address
  * remove description column
  * remove state column (it's redundant info displayed in status & action icons)
  * adjust column widths
  * change column order

As an alternative, you could provide the option to activate the old ports view again (ports legacy). With this you could test how users are satisfied with the new experience or if users tend to switch back to the old view.

**Comment by akosyakov** [comment]
> As an alternative, you could provide the option to activate the old ports view again (ports legacy). With this you could test how users are satisfied with the new experience or if users tend to switch back to the old view.

Yeah, we had it like that for 2 months and hoped that all users provided feedback [[1](https://www.gitpod.io/changelog/new-ports-explorer-changelog-view-and-connection-improvements-for-vs-code)]. A bit sad that feedback come so late. Right now we should discuss whether reintroduce the setting or address issues for new view.

**Comment by davemecha** [comment]
> Yeah, we had it like that for 2 months and hoped that all users provided feedback [[1](https://www.gitpod.io/changelog/new-ports-explorer-changelog-view-and-connection-improvements-for-vs-code)]. A bit sad that feedback come so late. Right now we should discuss whether reintroduce the setting or address issues for new view.

Sorry I missed that. Unfortunately sometimes I don't check the changelog. Maybe you could add a feature to suggest new experimental features to users in the UI (with an option to easily toggle the features, like e.g. Google does this sometimes). With this users would get easier aware of changes, possibly trying stuff more often so you might get more feedback.

**Comment by akosyakov** [comment]
@davemecha Could you try again? Many improvements were done last week. Now ports UI should be responsive to width and location. Location also should be preserved between your workspaces, i.e. if you move it to left or right it will stay there.

@mustard-mh @jeanp413 all improvements have been deployed for VS Code Browser and Desktop correct?

**Comment by davemecha** [comment]
@akosyakov Thanks for this great visual improvement. :) - The responsiveness works great!

Unfortunately the performance dropped extremely. If I move the view or open it the first time after the workspace launch, It needs more than 20 seconds to be populated (at least on my chromebook).

Check the screen recording...

[Screen recording 2022-10-17 22.03.11.webm](https://user-images.githubusercontent.com/137976/196273844-705728c0-bf6a-492d-9050-6339b0df6363.webm)

**Comment by akosyakov** [comment]
@davemecha could you share console and network logs when it happens from your browser? We are not able to reproduce it on our machines unfortunately.

**Comment by davemecha** [comment]
@akosyakov I checked again and there is just a warning in the console.

![image](https://user-images.githubusercontent.com/137976/197335512-0c5b0b50-9605-43c5-bc09-2e4f42889791.png)

This was my testing repo: https://github.com/davemecha/nuxt-gitpod-test

I tried to reproduce the problem on a fast windows PC of a friend with a Core i7 4th gen (Haswell) and the delay was just about a second. My computer is a Chromebook with an 8th gen (Coffee Lake) m3. So my computer might be pretty slow and maybe low of ram too (due to a running linux VM, several tabs open, ...).

So to reproduce this, you could try a mid range chromebook. - I can't remember having such performance issues with Gitpod and I assume this has something to do with the new view implementation. The old ports view was always fast.

Should I create a separate bug for this? - Maybe this is not the right place for this issue.
