### ISSUE TITLE
Execute local commands (possibly via local companion) initiated by Gitpod

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#9265]
**Use case:** 
- Running a workspace that requires a connection to a local machine (e.g. for DB client, or headless testing browser)
- Executing some code or command to start something on local (e.g chrome headless browser controlled by Gitpod)
- Configured also with port forwarding from local to gitpod (https://github.com/gitpod-io/gitpod/issues/6240)

**Disclaimer:** There are some security ramifications from applying such a pattern, however let's track it incase there are ways that we can make this possible.

Related internal conversation [[1](https://gitpod.slack.com/archives/C03372UP877/p1648797942680059?thread_ts=1648737035.902059&cid=C03372UP877)]

**Comment by akosyakov** [comment]
It sounds like a reverse ssh session, i.e. we could allow a user specify a remote port forwarding in .gitpod.yml and then a user can use such port to open a ssh session to his local machine and do whatever he wants.
