### ISSUE TITLE
TypeScript: Organize Imports is missing

### ISSUE THREAD

**Issue by TPReal** [gitpod-io/gitpod#927]
**Describe the bug**
After VS Code TypeScript was updated to 3.7.2, the option to organize imports disappeared completely from the palette.

**Additional Information**
Original report: https://spectrum.chat/gitpod/general/some-things-broken-after-typescript-update-to-3-7-2~eca4fa9c-54eb-4263-b640-005910d4674e

**Comment by geropl** [comment]
We just deployed the downgrade to TS 3.6, thus I will close the issue.
Please re-open with more details on how to reproduce if the problem persists.
