### ISSUE TITLE
TypeScript formatting ignores tsfmt.json

### ISSUE THREAD

**Issue by TPReal** [gitpod-io/gitpod#928]
**Describe the bug**
With VS Code TypeScript updated to 3.7.2, the formatting uses a different set of rules (probably the defaults) than those defined in my tsfmt.json.

**Additional Information**
Original report: https://spectrum.chat/gitpod/general/some-things-broken-after-typescript-update-to-3-7-2~eca4fa9c-54eb-4263-b640-005910d4674e

**Comment by geropl** [comment]
We just deployed the downgrade to TS 3.6, thus I will close the issue.
Please re-open with more details on how to reproduce if the problem persists.
