### ISSUE TITLE
Prebuilds fail with error "cannot initialize workspace: prebuild initializer: git fetch -p -P . tags -f failed"

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#9280]
### Bug description

[Incremental Prebuilds (Beta)](https://www.gitpod.io/changelog/faster-incremental-prebuilds) fails for Projects which have repo that contains private submodules.

This happens when the submodules are update in the repo. The subsequent prebuild fails while trying to update the submodules.

### Error

Error looks similar to these

#### Example 1
When you start a workspace, it triggers a prebuild which results in the following error:

```
Oh, no! Something went wrong!
cannot initialize workspace: cannot initialize
workspace: prebuild initializer: git fetch -p -P .
tags -f failed (exit status 1): From
https://github.com/x/x-mean +
5096db13…b6a9d685 tests/y
-
origin/tests/y (forced update) Fetching
submodule a/b No user exists for uid
133332 fatal: Could not read from remote
repository. Please make sure you have the correct
access rights and the repository exists. No user
exists for id 133332 fatal: Could not read from
remote repository. Please make sure you have the
correct access rights and the repository exists.
Errors during submodule fetch: a/b
a/b
```

#### Example 2

```
No user exists for uid 133332
fatal: Could not read from remote repository.
Please make sure you have the correct access right and the repository exists.
```

#### Example 3
On the prebuild page of the project.

```console
Prebuild failed for system reasons. Please contact support. cannot initialize workspace: cannot initialize workspace: prebuild initializer: git fetch -p -P --tags -f failed (exit status 1): From https://github.com/princerachit/pub 9383449..529e501 main -> origin/main * [new branch] newbranch1 - ...
```

### Workaround

Since this problem is specific to Incremental Prebuilds as workaround we suggest users to do the following until we fix this issue.

1. Disable Incremental Prebuilds permanently
1. Trigger a new Prebuild on on your branch

Above seems to work for most cases but recently we encountered a customer who disabled prebuild but could still see the issue: [internal slack thread](https://gitpod.slack.com/archives/C030RL11VC3/p1649423767231889?thread_ts=1649343126.817899&cid=C030RL11VC3)

Please let us know if this workaround does not help.

### Steps to reproduce

1. Create a repo (`pub`) which has a private repo git submodule (`hidden`)
1. Create an ssh key from an account which has access to `hidden`
1. Encode the ssh key and set into your project environment variable. e.g. `cat id_rsa | base64`
1. Update your `.gitpod.yml` so that it uses that key to initialize `pub`'s submodules in prebuild- [ref](https://github.com/princerachit/pub/blob/0e84fa72844c6057af33c8271e3aa1c1ae196498/.gitpod.yml#L4-L7)
1. Create a project from this `pub` repo and enable incremental prebuilds
1. Add new commits to the submodule repo
1. Now create a branch `b1` from `pub` repo and push it to GH. Let the prebuild run and finish.
1. Update a few files locally (other than .gitpod.yml) and then also update the submodule to the HEAD in branch `b1` e.g. `cd hidden && GIT_SSH_COMMAND="ssh -i ../idkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git pull origin main`
1. Commit the change `git add -u && git commit -m "changes"`
1. Push the change `git push`
1. Navigate to the prebuild running on `b1` branch. Prebuild should be failing.

e.g. Refer to the prebuild [url here](https://gitpod.io/projects/pub/52173a12-4887-40b7-8f07-c83ddfc4fb76) and [logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-21T07:31:27Z;query=%22009358d..0e84fa7%22%0Atimestamp%3D%222022-04-21T07:31:27Z%22%0AinsertId%3D%22dw91ites6d31t5ng%22;timeRange=PT10M?project=workspace-clusters) (This is not accessible to public)

### Workspace affected

Several prebuilds have been affected resulting in workspace failure.

To find the current number of failed prebuilds by their repo run the following command:

```sql
SELECT 
    cloneURL,COUNT(*)
FROM
    d_b_prebuilt_workspace
WHERE
    error LIKE '%prebuild initializer: git fetch -p -P%'
    and creationTime > '2022-02-13 08:56:44.752194'
GROUP BY cloneURL;
```
 
### Expected behavior

Prebuilds should work without any issue.

### Example repository

https://github.com/princerachit/pub

### Root cause

During incremental prebuild snapshost is downloaded and then the local repo is updated.

The snapshot contains the hidden submodule which was initialized during last successful prebuild.

When the `git fetch -p -P --tags` [command](https://github.com/gitpod-io/gitpod/blob/3edaa627ccd431187ba988794511503006808e0e/components/content-service/pkg/git/git.go#L286-L286) is run git finds that there was an update in the hidden submodule's sha reference. It then tries to update the submodule. Since we preserve the userid/gid (133332 which is missing in the init container) mapping when untarring the snapshot, the git command complains about the user not exisiting.

Even after creating this user manually  the prebuild fails as the ssh-key required to fetch this submodule does not exists in the content-init container. 

### Plan to Resolve

- [x] Try Reproducing the Error
- [x] Triage the code responsible for the issue
- [x] Figure out possible fixes - This issue will be fixed with the[ migration to PVC based storage](https://github.com/gitpod-io/gitpod/issues/7901) where the git command will be run in the workspace container context. The work for PVC is under progress and being tracked in previous link. See internal [thread](https://gitpod.slack.com/archives/C02F19UUW6S/p1651490322450949).
- [ ] Test fixes

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3p07e)

**Comment by princerachit** [comment]
I could not reproduce this error. I tried the following.

1. Create several branches with prebuild enabled on all of them
2. Create several tags
3. Update all branches by pushing new commit
4. Force push tags
5. Force push new commits on few branches
6. Push new commits to all branches


Also, When I investigate DB I see that `juroteam` 142 prebuilds, `gitlab-org` 73 prebuilds, `embarktrucks` 56 prebuilds had these errors in past 2 months.

```sql
SELECT 
    cloneURL,COUNT(*)
FROM
    d_b_prebuilt_workspace
WHERE
    error LIKE '%prebuild initializer: git fetch -p -P%'
    and creationTime > '2022-02-13 08:56:44.752194'
GROUP BY cloneURL;
```

**Comment by kylos101** [comment]
Hi @princerachit , have you tried setting up a repo with a submodule, and then push to the repo and repo backing the submodule at different times?

**Comment by princerachit** [comment]
> Hi @princerachit , have you tried setting up a repo with a submodule, and then push to the repo and repo backing the submodule at different times?

Yes, I tried that too but did not work

**Comment by princerachit** [comment]
So far I tried these combinations could not reproduce the issue, in all these cases the submodule was a private module:

1. Push commit to branch b1 and then to branch b2
2. force push commit to b1 and then fresh commit to b2
3. Update submodule in b1 and then a new commit to b2
4. Force push commit updating submodule in b1 and then a new commit to b2


I suspect that these combinations are not working because my user has permission to access the private submodule and does not use an ssh key.

As a next set of steps I am going to create a private submodule in another account and then would use my account to perform above test.

I will also make sure that the `git submodule update --init` is executed in a prebuild so that it serves as a base for subsequent prebuilds.

**Comment by princerachit** [comment]
I have moved this to scheduled column as my prebuilds are stuck in pending state. Team webapp is investigating the problem, I will pick it up once the issue is resolved.

**Comment by princerachit** [comment]
# Reproducing the Error

I was able to reproduce this issue using incremental prebuild. Refer to the prebuild [url here](https://gitpod.io/projects/pub/52173a12-4887-40b7-8f07-c83ddfc4fb76) and [logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-21T07:31:27Z;query=%22009358d..0e84fa7%22%0Atimestamp%3D%222022-04-21T07:31:27Z%22%0AinsertId%3D%22dw91ites6d31t5ng%22;timeRange=PT10M?project=workspace-clusters) (This is not accessible to public)
1. Create a repo (`pub`) which has a private repo git submodule (`hidden`)
2. Your github account SHOULD NOT have access to `hidden` repo
3. Create an ssh key from an account which has access to `hidden`
4. Encode the ssh key and set into your project environment variable
5. Update your .gitpod.yml so that it uses that key to initialize `pub`'s submodules in prebuild- [ref](https://github.com/princerachit/pub/blob/0e84fa72844c6057af33c8271e3aa1c1ae196498/.gitpod.yml#L4-L7)
6. Now create a branch b1
7. Update the submodule commit (make sure there are new commits in the private repo) e.g. `cd hidden && GIT_SSH_COMMAND="ssh -i myssshidkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git pull origin main`
8. Commit the change
9. Push the change
10. Prebuild should failed

## Why previous attempts failed
1. The previous attempts failed because my github account being used in gitpod already had access to private repo
2. I was not using `git submodule update --init` in my prebuild command.

**Comment by princerachit** [comment]
## Cause
I am not exactly sure of the reason of this failure, I will add logs and try to reproduce this in development env.
Right now my hypothesis is that since the `git fetch` is run in ring2 and `git submodule --init` is run in ring3, the submodule has a different user as owner or something on similar lines which causes subsequent git fetch to fail during incremental prebuild.

**Comment by princerachit** [comment]
I added [logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-04-28T09:05:17Z;query=resource.labels.container_name%3D%22ws-daemon%22%0Aresource.labels.namespace_name%3D%22staging-prs-prebuilds%22%0Atimestamp%3D%222022-04-28T09:05:17Z%22%0AinsertId%3D%22ji3zcneenz9u0u0c%22;timeRange=PT5M?project=gitpod-core-dev) to the code path where we perform fetch. The file permission looks correct with all the files owned by user 133332:
```console
40K
-rw-r--r-- 1 133332 133332    2 Apr 28 07:02 there
-rw-r--r-- 1 133332 133332   21 Apr 28 07:02 afile
-rw-r--r-- 1 133332 133332   14 Apr 28 07:02 README.md
-rw-r--r-- 1 133332 133332  446 Apr 28 07:02 .gitpod.yml
-rw-r--r-- 1 133332 133332   82 Apr 28 07:02 .gitmodules
-rw-r--r-- 1 133332 133332    5 Apr 28 07:02 .gitignore
drwxr-xr-x 2 133332 133332 4.0K Apr 28 07:02 hidden
drwxr-x--- 4 133332 133332 4.0K Apr 28 07:02 .
drwxr-xr-x 5 133332 133332 4.0K Apr 28 09:05 ..
drwxr-xr-x 9 133332 133332 4.0K Apr 28 09:05 .git
```

But we still see the error:
```console
"cannot initialize workspace:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.InitializeWorkspace
        github.com/gitpod-io/gitpod/content-service@v0.0.0-00010101000000-000000000000/pkg/initializer/initializer.go:426
  - prebuild initializer:
    github.com/gitpod-io/gitpod/content-service/pkg/initializer.runGitInit
        github.com/gitpod-io/gitpod/content-service@v0.0.0-00010101000000-000000000000/pkg/initializer/prebuild.go:131
  - git fetch -p -P --tags -f failed (exit status 1): From https://github.com/princerachit/pub
   bb4a4d3..6ed10c5  main       -> origin/main
 * [new branch]      test1      -> origin/test1
 * [new branch]      test2      -> origin/test2
 * [new branch]      test3      -> origin/test3
Fetching submodule hidden
No user exists for uid 133332
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
No user exists for uid 133332
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Errors during submodule fetch:
	hidden
	hidden
"


```

**Comment by princerachit** [comment]
I am moving this issue into blocked state. See internal [slack thread](https://gitpod.slack.com/archives/C02F19UUW6S/p1651490322450949).

Gist: The snapshot contains the hidden submodule. When we run the git fetch -p --tags command, git finds that there was an update in the hidden submodule's sha reference. It then tries to update the submodule. However, the ssh-key required to fetch this submodule does not exists in the content-init container. Therefore, this fails.

This will likely get resolved as we migrate to PVC based snapshots, where the git commands will be run in workspace context.

**Comment by sagor999** [comment]
This seems to happen even when git submodule references public repo.
Slack thread: https://gitpod.slack.com/archives/C032GEUGV09/p1654277137835379

**Comment by sagor999** [comment]
@csweichel 
what if before we run git fetch we would do chown with 33333 uid\gid on all files to ensure there is no 133332 user referenced anywhere:
https://github.com/gitpod-io/gitpod/blob/2823606369b667188187b1e8ee9a75cbe968633b/components/content-service/pkg/initializer/prebuild.go#L130

**Comment by sagor999** [comment]
And just to confirm, this happens on prebuilds that have incremental build disabled.

**Comment by csweichel** [comment]
> @csweichel what if before we run git fetch we would do chown with 33333 uid\gid on all files to ensure there is no 133332 user referenced anywhere:
> 
> https://github.com/gitpod-io/gitpod/blob/2823606369b667188187b1e8ee9a75cbe968633b/components/content-service/pkg/initializer/prebuild.go#L130

That is one way indeed.

We could also add a special mode to the snapshot initialiser whereby we don't do the UID mapping. This way we'd safe a (potentially rather expensive) `chown`.

**Comment by csweichel** [comment]
> And just to confirm, this happens on prebuilds that have incremental build disabled.

That's odd and warrants some more investigation. Where do those UIDs come from if not from a snapshot restoration?

**Comment by sagor999** [comment]
I am moving this issue into scheduled state from blocked, since it does affect non incremental prebuilds as well and we need to investigate why.

**Comment by sagor999** [comment]
I suspect we might be using incremental prebuild when we are not supposed to?
@gitpod-io/engineering-webapp could you guys double check logic here:
https://github.com/gitpod-io/gitpod/blob/65259116838445c1e6b0e71dd91d7aa000f36b48/components/server/ee/src/workspace/workspace-factory.ts#L117
I cannot find anything that would disable incremental prebuild based on project config setting, but maybe that is done somewhere else? 
Here is the affected project:
https://gitpod.io/admin/projects/d2168919-f8ac-4c4c-8e6d-4fe9ac049911
It seems like its prebuilds are running based on previous prebuild, even though incremental prebuilds are disabled for that project.

**Comment by kylos101** [comment]
Added to webapp inbox and pinging @geropl because of @sagor999 's [comment here.](https://github.com/gitpod-io/gitpod/issues/9280#issuecomment-1155788364)

Thanks, @sagor999 , for the find! :pray:

**Comment by geropl** [comment]
Thx @sagor999 , will schedule for someone to investigate. :+1:

**Comment by kylos101** [comment]
Removing from Workspace project for now @geropl @sagor999 .

**Comment by jldec** [comment]
This has come up with matching error message in this [customer context here](https://gitpod.slack.com/archives/C033MA45L5S/p1662728987470089) (internal).

**Comment by AlexTugarev** [comment]
@sagor999, on https://github.com/gitpod-io/gitpod/issues/9280#issuecomment-1155788364

If incremental prebuilds are disabled in project settings, that code path wont be taken because the `context.commitHistory` isn't populated, see
https://github.com/gitpod-io/gitpod/blob/65259116838445c1e6b0e71dd91d7aa000f36b48/components/server/ee/src/workspace/workspace-factory.ts#L108

and the call site:
https://github.com/gitpod-io/gitpod/blob/cc2f3b30fed435ef623d164e9c131d9b887df73c/components/server/ee/src/prebuilds/prebuild-manager.ts#L88-L111

**Comment by axonasif** [comment]
Possible (new) duplicate:
- https://github.com/gitpod-io/gitpod/issues/13587

**Comment by kylos101** [comment]
Thank you for sharing, @axonasif!! [This](https://github.com/gitpod-io/gitpod/issues/13587#issuecomment-1277665040) is interesting. cc: @aledbf @csweichel

**Comment by aledbf** [comment]
Closing. The fix is deployed now

**Comment by kylos101** [comment]
:wave: exactly, thanks @aledbf ! :rocket:  Reference the fix in https://github.com/gitpod-io/gitpod/pull/13956, it is deployed to the saas in `us72` and `eu72`. Also, it'll be available in self-hosted as part of the October release.
