### ISSUE TITLE
change docker image location to fix space problem

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#9283]
## Is your feature request related to a problem? Please describe

Build this docker will result into no space error

https://github.com/gengjiawen/dockerfile/blob/main/gitpod-android/Dockerfile

## Describe the behaviour you'd like
Maybe change the docker location in other places.
Context: https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169

**Comment by gengjiawen** [comment]
not stale

**Comment by atduarte** [comment]
👋 @gengjiawen! Sorry for taking so long to get to this.

Disk space is limited 10GB in `/` plus 30GB in `/workspace`. A bigger option will be introduced with #8261. In the meantime, there's not much we can do :/
