### ISSUE TITLE
Gitpod port control via gp-cli

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#9286]
for me the current gp foreward-port is missleading it should be changed because it control the public mode

Please introduce a clear API for the port management via the gp cli with the following functions:

in the following text [local] means always a port that is accessibly from the local computer via local-companion / vscode / ...

1. make a port public accessibly or not: for example
   `gp port 8080 --public` or `gp port 8080 --private`
3. check if local-companion is available
   `gp port status` -> returns all ports with the current status and if local-companion is available
4. make a port local available or unavailable and define the port mapping
   `gp port -R 80:127.0.0.1:3000` 
   `gp port -L 80:127.0.0.1:3000`. ... use SSH logic because this is well known
5. delete a port forwarding
   `gp port -KR 80`
   `gp port -KL 80` ... again use SSH logic for deleting remote and local port forwards
   
This would allow having full control of the workspace.

**Comment by shaal** [comment]
Yes please!
Being able to change ports programmatically, after workspace already running would be a great feature!

**Comment by loujaybee** [comment]
Removing from project as associated to epic: https://github.com/gitpod-io/gitpod/issues/9262

**Comment by loujaybee** [comment]
> gp port status -> returns all ports with the current status and if local-companion is available

Please see: https://github.com/gitpod-io/gitpod/pull/10388 (documentation pending), however I'm not sure what you mean by "if local-companion" is available, in this context?

**Comment by konne** [comment]
@loujaybee can you please also add a possibility to fetch the port status as JSON result. The printed cli table is nice in the terminal, but hard to use in bash,... scripts (see #10388 implementation) for example with the --json argument

**Comment by loujaybee** [comment]
Thanks for the feedback @konne, I've added as a separate issue, as if we make that change, would be good to do it unilaterally across all commands - https://github.com/gitpod-io/gitpod/issues/10448
