### ISSUE TITLE
gp cli availble also on local computer (ssh/open workspace from desktop CLI / local app)

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#9287]
the user wants to use the gp cli also on the client computer.
The main difference is that if only one workspace is connected via local companion it just uses this workspace.
If the user has multiple workspaces running that workspace has to be defined with e.g. --workspace=NAME123

This would be first great to have a nice an consistent cli to add and remove port mappings and set environment variables,
but also all other features that will be added to the cli would be great to have them everywhere available.

**Comment by loujaybee** [comment]
Also potential duplicate of: https://github.com/gitpod-io/gitpod/issues/4782

**Comment by konne** [comment]
@loujaybee yeah look like a dup, but the other is already marked as stale
