### ISSUE TITLE
gp cli run external command

### ISSUE THREAD

**Issue by konne** [gitpod-io/gitpod#9289]
As a user, I want to have the possibility to run a command via gp cli for remotely connected systems.
This can be that I run gp cli from within a workspace that runs the command on the local computer and vice versa.
The stdout stderr is transported to the calling system.

Now our concrete use case.
We want to use gitpod also for our e2e development and need for example that we have a local chrome, safari, edge,... browser that needs to be started in a special mode so that this can be remote-controlled from the e2e test solution like a playwright.
With that feature, we could have a script in our gitpod environment that a user can start and all necessary steps will be done. (this also needs a feature https://github.com/gitpod-io/gitpod/issues/9286

The script would work like this:

```
gp run remote ...chrome --remote-debugging-port=9222
   this will output something like ws://127.0.0.1:9222/xxxxxxxxxxxxxxx
gp port -R 9222:127.0.0.1:9222
  create a reverse port mapping for port 9222 from the local computer into the gitpod workspace
npm run e2eTEST --option1=ws://127.0.0.1:9222/xxxxxxxxxxxxxxx
```

The same will be necessary for example what I have seen with people who make hardware development and like to start a local debugger software,...

**Comment by loujaybee** [comment]
The comment in https://github.com/gitpod-io/gitpod/issues/9770#issue-1225603045 is also similar to this request, e.g. launch a local desktop terminal at the same time as workspace start/open.
