### ISSUE TITLE
No import of an R project

### ISSUE THREAD

**Issue by av1611** [gitpod-io/gitpod#929]
**Describe the bug**

The import of my project located at https://github.com/av1611/ConfidenceBandsEnchanced was a failure.
**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by svenefftinge** [comment]
What exactly happened? I could start a workspace without problems.
But Gitpod doesn'T ship any R-related tools out-of-the-box, so you would have to install them through a custom dockerfile. Also adding related VS Code extensions would make sense.
