### ISSUE TITLE
Show productivity tips in the splash screen

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#93]
I have two problems when using Gitpod:

1. When I click on a `Gitpod` button, I have to watch a splash screen for a short while (because the IDE takes some time to be ready)
2. There are many neat productivity tricks and features in Gitpod that I'm not aware of (because I'm a new user, or I haven't read the docs / the code / watched videos, etc like for example typing `F1` or using `gp open`)

I see an opportunity to address both problems: Showing productivity tips in the splash screen. That way, every time I wait for the IDE to load, I potentially learn something new that will save my time later.

This is something that Cloud9 IDE already does:

https://github.com/c9/core/blob/e9490da4e721915df42d1c468ea7c98f879fbb11/plugins/c9.vfs.standalone/www/ide.html#L47-L72

To illustrate with an example, one day I discovered the Cloud9 tip about renaming variables with `Ctrl-Alt-R`, and I instantly loved it and adopted that feature, which saves me a ton of time since then.

Ideal Gitpod features for such a tip could be:
- [ ] Typing `F2` to rename a symbol (this feature was my favorite discovery in Cloud9 IDE)
- [ ] Typing `F1` to fork a repository (I absolutely didn't know `F1` existed until you told me about it in a bug report. Some of its features aren't even exposed in the context menus, so I was missing out on them)
- [ ] Using `gp open` to open a file in the IDE (same thing; I used to hunt for particular files using the file tree)
- [ ] Using `z` to jump around faster in the repository (if you install https://github.com/rupa/z which is amazing)
- [ ] Using `rg` or `fd` to find things (same, if you install https://github.com/BurntSushi/ripgrep and https://github.com/sharkdp/fd)
- ... any other feature that users don't know about but could be a huge time saver

**Comment by jankeromnes** [comment]
Hi Gitpod friends, what are some keyboard shortcuts / commands / quick workflows that you love and that save you a lot of time & effort when you use Gitpod?

For me it was discovering about `F1 + 'fork'` and `F2` to rename symbols.

If you have some time, I'd love your opinions: @AlexTugarev @sr229 @svenefftinge @akosyakov @spoenemann @geropl @32leaves @meysholdt @jbicker @JanKoehnlein 😊

**Comment by svenefftinge** [comment]
For shortcuts we need to have them OS dependent.

**Comment by jankeromnes** [comment]
We could also mention that you can prefix any GitHub URL with `gitpod.io#` to create a new workspace (it seems that many users still don't really know that you can do that).

**Comment by sr229** [comment]
Hey, we could also add some easter eggs and funny loading lines while we're at it, I mean, Cloud9 IDE does it!

**Comment by svenefftinge** [comment]
> Hey, we could also add some easter eggs and funny loading lines while we're at it, I mean, Cloud9 IDE does it!

Suggestions are very welcome!

**Comment by jankeromnes** [comment]
A few more great suggestions from Sven:

- "Questions? Join our community [on Spectrum](https://spectrum.chat/gitpod)."
- "Navigate to the previously shown editor with Cmd+-."
- "Questions? Check our [documentation](https://docs.gitpod.io/)."
- "Found a bug or have a feature request? Submit it [here](https://github.com/gitpod-io/gitpod/issues)."
- "Init a .gitpod.yml using the cli: `gp init`."

Regarding the last one, I already had it as "Run `gp init` to configure Gitpod for your project."... any preference?

**Comment by jankeromnes** [comment]
Maybe we could also mention the `gitpod.io#` URL prefix? I think it's a really cool / underrated feature.

**Comment by svenefftinge** [comment]
We need to make sure that everybody understands the `gitpod.io#` prefix. Just showing it from time to time in the productivity tips doesn't seem good enough to me.

**Comment by jankeromnes** [comment]
I agree, it's not the full answer. But maybe it can be part of the answer?

**Comment by sr229** [comment]
We can do something like this:

> Did you know you that every GitHub project can be a Gitpod workspace? Simply add `gitpod.io#` at the beginning of each GitHub link. Read the Documentation to find out more! 

what do you think @jankeromnes @svenefftinge

**Comment by jankeromnes** [comment]
Great phrasing, thanks! 🙂 Sven also had an interesting suggestion that we mention the URL prefix in the same message where we suggest installing the WebExtension, that way new users can learn about both options.

Maybe users who already have the WebExtension and created a few workspaces already know about the prefix, and don't need to be reminded?

**Comment by jankeromnes** [comment]
Another really cool "hidden" feature: right-click on selected lines in Editor and click "Open in GitHub".

**Comment by spoenemann** [comment]
AFAIK there is no command/keybinding for that.

**Comment by jankeromnes** [comment]
Maybe also something along the lines of `Run 'python3 -m http.server 8000' to easily serve static content`?

I know that there is also the HTML live-preview, but it has certain limitations (e.g. not able to open it in a new tab), to which a one-line static server could be a nice workaround.

**Comment by sr229** [comment]
I think people are not aware of the `gp` CLI for port forwarding, I think we should cover them as well.

**Comment by jankeromnes** [comment]
`gp forward-port` was originally in the list, but we removed it, since it's already mentioned in the prompt that appears when you start something on a localhost-bound port. Do you still think that we should also mention it in the splash screen?

**Comment by sr229** [comment]
yep, not everytime Gitpod can automatically forward the ports

**Comment by jankeromnes** [comment]
@jbicker, @svenefftinge and I implemented tips in the loading screen, and we're just about to release it this afternoon! 🎉 🤞 

It should look something like this:
<img width="1552" alt="screenshot 2019-02-15 at 11 49 14" src="https://user-images.githubusercontent.com/599268/52861577-32fc4f00-3133-11e9-985a-f00d6f84d562.png">
Amazing work team! And many thanks for all the cool ideas in this issue. 💯

**Comment by ChristinFrohne** [comment]
Looks great!! 
I just wanted to check, if the URL of the box still changes with your actual URL (as that's not the case on the screenshot) and on Firefox the white box is not displayed at all. Is that an other typical Firefox thing? 
I didn't manage to open this screen in Chrome another time

**Comment by jankeromnes** [comment]
Which white box is not being displayed? (Note: This is a Firefox screenshot.)

**Comment by ChristinFrohne** [comment]
oh sorry, I just talked with Jan B. he explained it to me. My mistake

**Comment by svenefftinge** [comment]
Let's push the release to Monday morning. :-)

![image](https://user-images.githubusercontent.com/372735/52864570-b7060500-313a-11e9-9099-354000047fb5.png)

**Comment by Furisto** [comment]
Hey @jankeromnes, currently we do not show any tips anymore. @julia-leyton and I were just discussing how she is creating a FAQ and we are thinking about displaying it during the splash screen. Can you give us some context on why this feature has been removed?
