### ISSUE TITLE
Endless redirect loop on workspace restart

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#9301]
After turning on the `new-workspace-cluster` switch in for my user account, I tried to restart a stopped workspace from the dashboard. That tab ended up in a redirect loop on `https://gitpod.io/start/?not_found=true#gitpodio-gitpod-8dx757mgats`.

I could not reproduce it in two other instances. Still, it would be great to investigate the `not_found` behavior.

**Comment by geropl** [comment]
This is outdated.
