### ISSUE TITLE
Investigate KOTS Preflight Checks Reporting Cluster Memory Incorrectly

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#9307]
### Bug description

The current preflight check which checks the memory of the cluster appears not to be working correctly. Initially when I installed Gitpod this check had no issues, but since then it has reported an issue.

<img width="1434" alt="Screen Shot 2022-04-13 at 14 57 02PM" src="https://user-images.githubusercontent.com/405585/163260029-bc460dc5-e0b8-4aea-8de2-ad47a3b58c57.png">

<img width="1653" alt="Screen Shot 2022-04-13 at 14 57 35PM" src="https://user-images.githubusercontent.com/405585/163260119-77e86103-bc30-44f4-ae56-838482dc6ff7.png">

According to Rancher I have plenty of memory available:

<img width="1428" alt="Screen Shot 2022-04-13 at 14 01 41PM" src="https://user-images.githubusercontent.com/405585/163260180-0537c4ea-0421-4422-9450-05e52193dfcb.png">

I don't believe there was any changes to the preflight checks since `main.2860`, but I could be wrong.

### Steps to reproduce

At this time I have not replicated the issue myself, however I would think you should be able to use the following steps:

1. Spin up a Gitpod instance using the KOTS installer.
2. Visit the KOTS admin dashboard and go through the install process. At this point you _may_ receive the failed preflight check for memory.
3. If you didn't get an issue with the initial preflight checks, you may need to wait until there's a new update available.

### Anything else?

If there is a command I could manually run that performs the memory check as done in the preflight check please let me know so I can run that to see what is returned.

**Comment by jimmybrancaccio** [comment]
I just thought of something, I wonder if the check is being performed again my controller node:

```
jimmy@kubemaster:~$ free -mh
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       1.7Gi       5.2Gi       1.0Mi       853Mi       5.8Gi
Swap:            0B          0B          0B
```

whereas my two worker nodes:

```
jimmy@kubenode1:~$ free -mh
              total        used        free      shared  buff/cache   available
Mem:           23Gi       1.8Gi        16Gi        48Mi       4.8Gi        21Gi
Swap:            0B          0B          0B


jimmy@kubenode2:~$ free -mh
              total        used        free      shared  buff/cache   available
Mem:           23Gi       1.3Gi        18Gi       3.0Mi       3.5Gi        21Gi
Swap:            0B          0B          0B
```

Could that be the case here?

**Comment by jimmybrancaccio** [comment]
I am not sure where the issue in this is, but I figured I would mention it still exists after updating to KOTS v1.70.0.

**Comment by lucasvaltl** [comment]
@MrSimonEmms would you mind taking a look at this and triage this?

**Comment by MrSimonEmms** [comment]
I'm not sure this is an issue. The check is for the memory on each node, not cumulative - as the screenshot in the Rancher dashboard appears to only show cumulative values for the cluster, this doesn't necessarily prove an error.

Without wishing to revert to "it works on my machine", this check has been in place for quite some time and appears to be reporting the correct figures. Of course, please reopen this ticket if not.

As of `2022.6.0`, the requirement has increased to 16GB RAM per node

**Comment by jimmybrancaccio** [comment]
@MrSimonEmms As noted above I think the issue is when KOTS is checking my controller node which has only 8GBs of RAM. This node is only used as a control-plane node and doesn't not have workspaces / I do not schedule anything to this node. I also just checked and saw that I have none of the 'gitpod' labels added to that node either. I only have the labels added to my other 3 nodes.

So I guess that brings me back to one of my questions, is this check being performed on _all_ nodes, even those without the 'gitpod' labels? It may be worth reviewing [this comment](https://github.com/gitpod-io/gitpod/issues/9307#issuecomment-1098527634) too.

**Comment by MrSimonEmms** [comment]
I've just looked at the [test](https://github.com/gitpod-io/gitpod/blob/main/install/kots/manifests/kots-preflight.yaml#L195,L213) and it's likely that it's not checking the correct nodes. I'll have a check putting a filter in
