### ISSUE TITLE
Make It Clear When a Deployment/Upgrade Fails in The KOTS Admin Dashboard

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#9308]
## Is your feature request related to a problem? Please describe

About 30 minutes ago, I attempted to update my Gitpod instance from `main.2860` to `main.2898`. I see the following:

<img width="614" alt="Screen Shot 2022-04-13 at 15 03 06PM" src="https://user-images.githubusercontent.com/405585/163260992-297bde34-11c1-4c30-aa88-38b2f0acf733.png">

If I hadn't also been running `watch -n5 kubectl get po -n gitpod` on my laptop, I wouldn't have known this had failed. It also does not properly reflect the actual version running on my cluster (which is still `main.2860`.

## Describe the behaviour you'd like

I would like to know if the upgrade process failed along with information on _why_ it failed and what needs to be done for it to successfully run.

## Describe alternatives you've considered

N/A

## Additional context

I was able to get a `describe` on the installer pod - https://ghostbin.linuxbox.ninja/paste/nr4wy

**Comment by corneliusludmann** [comment]
@MrSimonEmms: Is this fixed with the following pull requests?
- https://github.com/gitpod-io/gitpod/pull/9455
- https://github.com/gitpod-io/gitpod/pull/9471

**Comment by MrSimonEmms** [comment]
@corneliusludmann yes, this is _LARGELY_ achieved by these PRs. The only one that isn't is _why_ it failed, but there isn't an easy way how to get that out of KOTS. I'm going to proposing closing it, but I'm going to add a ticket to run DB/Storage/Registry connectivity checks in the pre-flight checks (I know Replicated say that's not what they're designed for, but I think they're essential for how we're using it)
