### ISSUE TITLE
[Question]: What components in the Docker image is required by theia/gitpod?

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#931]
I want to have my customized Docker image for gitpod for server reasons.

1. gitpod/workspace-full is bloated and I really don't need many of the components installed in the Docker image. Having a customized Docker image which is much smaller might help speed up loading of workspaces. 

2. My main development language is Python. However, I'm not a big fan of managing multiple Python versions (2 and 3) using pyenv in user's local directory. It has created several issues for me already.

I'd like to know which components in the Docker image gitpod/workspace-full is required by theia/gitpod. I don't found anything related to theia in the Dockerfile of gitpod/workspace-full. So I assume theia is some standalone app mounted in the Docker container at run time and none of the languages/tools installed is required by theia/gitpod?  We just need to make sure there is a user named gitpod and configure the correct permissions for it, right?

**Comment by JesterOrNot** [comment]
You can bring your docker image!
https://www.gitpod.io/docs/42_config_docker/
Customize it to your heart's desire!
Just note at this time only ubuntu and Debian base images are supported
(and some alpine images work as well)

**Comment by dclong** [comment]
@JesterOrNot Thank you very much! It turned out that I misunderstood the gitpod Docker images. I though one must extend from gitpod/workspace-full. Being able to use a customize Docker image as the base image is indeed very convenient!

I tried to use ubuntu:19.04 as the base image and it worked. However, it didn't work for me when I used my own customized image dclong/python. It is likely due to the fact that I have ENTRYPOINT ["/scripts/sys/init.sh"] in the Dockerfile. So may we document the detailed requirements (ENTRYPOINT and others) on the based Docker image?

**Comment by JesterOrNot** [comment]
Let's do it! I'll start a fork up to work on @dclong

**Comment by JesterOrNot** [comment]
here
https://github.com/JesterOrNot/website
send pull requests for this fork and we can pull request the real docs from there

**Comment by geropl** [comment]
>  So may we document the detailed requirements (ENTRYPOINT and others) on the based Docker image?

@dclong Yes, we should definitely do so. To help you advance here: Gitpod itself has not to much requirements: apt-get, bash, that's about it (in the Debian/Ubuntu case). And it will also add those in the Gitpod layer if not present. It's often useful/necessary to have a `gitpod` user in place to be able to `chown` files in the Dockerfile: You can copy the relevant lines from `workspace-full`.

But individual VSCode extensions like the one for [python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) might have [more requirements](https://code.visualstudio.com/docs/python/python-tutorial#_prerequisites).

**Comment by svenefftinge** [comment]
Also ENTRYPOINT is not executed on start. If you want to start something, you should add it to your gitpod.yml tasks list or start things in the background by adding commands to `.bashrc`.
