### ISSUE TITLE
Cannot use solr in gitpod: "Container ID 8983 cannot be mapped to a host ID."

### ISSUE THREAD

**Issue by cdrini** [gitpod-io/gitpod#9311]
### Bug description

I cannot up a solr container, because for some reason the ID the container users, 8983, causes an error.

### Steps to reproduce

Any workspace will probably have the same issue, but this is the one I was using: https://gitpod.io/#https://github.com/internetarchive/openlibrary/ . You'll see the error as it tries to startup. Manually running `docker run --rm solr:8.10.1 bash` also triggers the same error.

### Expected behavior

The solr image downloads and runs ok

### Anything else?

Related issue: #2649 . But this ID is well less than the upper limit for namespaces. I also check `/etc/passwd` in gitpod, and 8983 didn't clash with an existing UID.

**Comment by cdrini** [comment]
Running memcached seems to also be causing user-related errors:


```
$ docker run --rm memcached bash
```
`docker: Error response from daemon: OCI runtime create failed: runc create failed: unable to start container process: unable to setup user: cannot set uid to unmapped user in user namespace: unknown.`

**Comment by cdrini** [comment]
I tried running it on another workspace ( https://gitpod.io/#https://github.com/internetarchive/bookreader ), and `docker run -it --rm solr:8.10.1 bash` worked; so it seems like something isn't working with the openlibrary workspaces?

**Comment by axonasif** [comment]
Hey @cdrini, it seems to be a permission issue on `$GITPOD_REPO_ROOT`. I raised a PR on the upstream. You can try opening https://github.com/internetarchive/openlibrary/pull/6430 on Gitpod until it gets merged :wink:

I think it's also related with https://github.com/gitpod-io/workspace-images/issues/640

**Comment by cdrini** [comment]
Thank you so much @axonasif ! This was what fixed the issues: `chmod o+rx $GITPOD_REPO_ROOT`. Please feel free to close this! Or if you would like to investigate how the `other` permission was set to `---` and why that caused solr to fail, feel free to leave open :) Thanks again!

**Comment by cdrini** [comment]
Ugggh! But the PR that fixed the issue works? Even though there haven't been any changed to gitpod files since then??? https://gitpod.io/#https://github.com/internetarchive/openlibrary/pull/6430
