### ISSUE TITLE
docker_env not found on terminal startup

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#933]
**Describe the bug**
On the start of the terminal, it seems that it wants to run docker_env but it doesn't exist
![image](https://user-images.githubusercontent.com/50386709/68978009-4cfcb800-07bf-11ea-8aba-e1e698041474.png)

**To Reproduce**
open a terminal in gitpod/workspace-full
**Expected behavior**
This error is not displayed
**Additional Information**
here is an example repo
gitpod.io/#https://github.com/av1611/ConfidenceBandsEnchanced/tree/f197d35610a9f4b3458a7a16ff48af47dd34df8b

**Comment by AlexTugarev** [comment]
Thanks for reporting! 😢 we've seen that as well, and fixed it already. It's going to be deployed soon. 

Luckily, this doesn't break anything.

**Comment by svenefftinge** [comment]
deployed
