### ISSUE TITLE
IO limits are not applied

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#9341]
### Bug description

We are observing that IO limits are currently not applied to workpspaces. The config map for ws-daemon contains the correct configuration but no attempt seems to be made to enforce the limits via io.max.

### Steps to reproduce

- Open workspace
- SSH to the node the workspace is running on
- find /sys/fs/cgroup/kubepods -name io.max | xargs cat
- -> this should show devices that are limited, but currently nothing is there

The plugins can be found [here](https://github.com/gitpod-io/gitpod/tree/main/components/ws-daemon/pkg/cgroup).
The io limit plugin is [here](https://github.com/gitpod-io/gitpod/blob/main/components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go)
The plugin is called [here](https://github.com/gitpod-io/gitpod/blob/2a9c4dad14524ec3d4a620a02cc37ff7962ec5ce/components/ws-daemon/pkg/cgroup/cgroup.go#L93-L103) 

### Expected behavior

IO limits should be applied

**Comment by kylos101** [comment]
Hey @Furisto , may we ask for your help with this issue when you return to work? Also, you may find this [internal grafana comparison intersting.](https://grafana.gitpod.io/explore?left=%7B%22datasource%22:%22VictoriaMetrics%22,%22queries%22:%5B%7B%22expr%22:%22sum(rate(node_disk_read_bytes_total%7Binstance%3D~%5C%22.%2B38.%2B%5C%22,device%3D~%5C%22md42%7Cmd43%7Cmd44%7Csda%5C%22%7D%5B1h%5D))%20by%20(device)%20%2F%20(1024*1024)%22,%22format%22:%22time_series%22,%22interval%22:%22%22,%22intervalFactor%22:1,%22refId%22:%22B%22,%22step%22:10,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22hide%22:false%7D,%7B%22expr%22:%22sum(rate(node_disk_read_bytes_total%7Binstance%3D~%5C%22.%2B39.%2B%5C%22,device%3D~%5C%22md42%7Cmd43%7Cmd44%7Csda%5C%22%7D%5B1h%5D))%20by%20(device)%20%2F%20(1024*1024)%22,%22format%22:%22time_series%22,%22interval%22:%22%22,%22intervalFactor%22:1,%22refId%22:%22A%22,%22step%22:10,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22exemplar%22:false,%22hide%22:false%7D,%7B%22refId%22:%22C%22,%22exemplar%22:false,%22instant%22:true,%22range%22:true,%22expr%22:%22sum(rate(node_disk_read_bytes_total%7Binstance%3D~%5C%22.%2B40.%2B%5C%22,device%3D~%5C%22md42%7Cmd43%7Cmd44%7Csda%5C%22%7D%5B1h%5D))%20by%20(device)%20%2F%20(1024*1024)%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-15d%22,%22to%22:%22now%22%7D%7D&orgId=1&right=%7B%22datasource%22:%22VictoriaMetrics%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22exemplar%22:false,%22instant%22:true,%22range%22:true,%22expr%22:%22sum(rate(node_disk_written_bytes_total%7Binstance%3D~%5C%22.%2B38.%2B%5C%22,device%3D~%5C%22md42%7Cmd43%7Cmd44%7Csda%5C%22%7D%5B1h%5D))%20by%20(device)%20%2F%20(1024%20*%201024)%22,%22hide%22:false%7D,%7B%22refId%22:%22F%22,%22exemplar%22:false,%22instant%22:true,%22range%22:true,%22expr%22:%22sum(rate(node_disk_written_bytes_total%7Binstance%3D~%5C%22.%2B39.%2B%5C%22,device%3D~%5C%22md42%7Cmd43%7Cmd44%7Csda%5C%22%7D%5B1h%5D))%20by%20(device)%20%2F%20(1024%20*%201024)%22,%22hide%22:false%7D,%7B%22refId%22:%22A%22,%22exemplar%22:false,%22instant%22:true,%22range%22:true,%22expr%22:%22sum(rate(node_disk_written_bytes_total%7Binstance%3D~%5C%22.%2B40.%2B%5C%22,device%3D~%5C%22md42%7Cmd43%7Cmd44%7Csda%5C%22%7D%5B1h%5D))%20by%20(device)%20%2F%20(1024%20*%201024)%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-15d%22,%22to%22:%22now%22%7D%7D)

**Comment by stephenavocado** [comment]
This issue is still affecting me
