### ISSUE TITLE
docker-compose kill command does not behave properly

### ISSUE THREAD

**Issue by daveshook** [gitpod-io/gitpod#9346]
### Bug description

When `docker-compose kill SERVICE` is executed in a gitpod workspace, it kills all containers. It should only kill the named container, i.e. `SERVICE`. When this command is run on an ubuntu host, it behaves correctly.

### Steps to reproduce

1. Start several docker containers
2. Run `docker-compose kill SERVICE` where `SERVICE` is equal to the name of one container.
3. All running containers are killed. This is not the correct behavior of the command.

### Expected behavior

1. Start several docker containers
2. Run `docker-compose kill SERVICE` where `SERVICE` is equal to the name of one container.
3. The named container is killed but all other containers continue to run.

### Anything else?

This command behaved properly gitpod workspaces in the past.

**Comment by daveshook** [comment]
Upgrading `docker-compose` to version `2.4.1` corrects this issue.

**Comment by aledbf** [comment]
Closing. The upgrade to 2.4.1 is available in gitpod.io
