### ISSUE TITLE
Container does not rebuild even with #imagebuild

### ISSUE THREAD

**Issue by daveshook** [gitpod-io/gitpod#9351]
### Bug description

When launching a workspace based upon repo `https://github.com/confluentinc/learn-kafka-kraft`, the container never rebuilds. It seems to create the workspace using the existing custom public container defined by `gitpod.Dockerfile`. This is true even when using the `#imagebuild` option.

### Steps to reproduce

Launch the workspace with `https://gitpod.io/#imagebuild/https://github.com/confluentinc/learn-kafka-kraft`

### Expected behavior

The custom public container should be rebuilt based upon the contents of `https://github.com/confluentinc/learn-kafka-kraft/blob/main/.gitpod.Dockerfile`.

**Comment by daveshook** [comment]
I added a fork to `https://github.com/confluentinc/learn-kafka-kraft`. The fork `https://github.com/daveshook/learn-kafka-kraft` builds correctly but the build of `https://github.com/confluentinc/learn-kafka-kraft` continues to use the existing prebuilt workspace.

I would appreciate some attention to this issue.

**Comment by daveshook** [comment]
I also tried to launch the workspace using `https://gitpod.io/#prebuild/https://github.com/confluentinc/learn-kafka-kraft` and it still fails to rebuild the customer container.

**Comment by daveshook** [comment]
Issue has been resolved.

**Comment by sagor999** [comment]
@daveshook do you mind posting how you fixed this issue in case if someone else will experience similar?
