### ISSUE TITLE
Improve load testing for clusters

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#9352]
## Is your feature request related to a problem? Please describe
We need to ensure that new clusters are behaving correctly and are ready to serve traffic.

## Describe the behaviour you'd like
The load testing tool should be extended to
- Verify that started workspaces are entering running state
- The started workspaces should run a variety of workloads (io, memory, cpu) in order to verify that resource control is working and the cluster can handle the load

## Describe alternatives you've considered
n.a.

## Additional context
n.a.

**Comment by kylos101** [comment]
Closed in favor of https://github.com/gitpod-io/gitpod/issues/7934
