### ISSUE TITLE
Share multiple Terminals in a single workspace

### ISSUE THREAD

**Issue by mashuk999** [gitpod-io/gitpod#9364]
## Is your feature request related to a problem? Please describe
I am not able to share outputs when working on multiple terminals. Also, when using Run and Debug, It's a huddle to describe what is happening in the code and since we have to use specific port we cannot launch multiple instance on different ports

## Describe the behaviour you'd like
Share/Hide multiple terminals to other developers. Currently one terminal is shared when working on a collaborative workspace. A button next to terminal to make it shareable across team members to see the output or make terminal private will be awesome

## Describe alternatives you've considered
By default share all terminals will also be fine

**Comment by mteam88** [comment]
Good idea. This might be a part of a better workspace sharing UI and feature addition PR. +1

**Comment by loujaybee** [comment]
Thanks for the feedback, @mashuk999. We're not actively focusing on the collaboration features currently, but it is still an experience we really do want to improve. Whilst not a perfect workaround (and if you're happy with a 3rd party service, you could look into the different plugins to see if they meet your needs) in the mean time: https://www.gitpod.io/docs/sharing-and-collaboration#external-collaboration-plugins 🙏
