### ISSUE TITLE
Workspace keeps closing for no reason

### ISSUE THREAD

**Issue by stephenavocado** [gitpod-io/gitpod#9369]
### Bug description

About a minute or two after initializing my workspace, the workspace is stopping. 

### Steps to reproduce

Open workspace, follow normal steps - enter y to install expo cli, stop expo server, run yarn start --tunnel, which prompts you to install expo/ngrok globally. After the install, the server runs temporarily, then the whole workspace closes. 

### Workspace affected

https://stephenavocado-painnavig-1mu5jbg9rw0.ws-us40.gitpod.io/

### Expected behavior

Workspace stays open and expo server runs with tunnel.

**Comment by atduarte** [comment]
Because of recent abuse we had to temporarily block ngrok, which leads to the workspace being killed. We will revert this action as soon as we close this related issue https://github.com/gitpod-io/gitpod/issues/9341. cc @aledbf @kylos101

**Comment by stephenavocado** [comment]
Ok thanks!

**Comment by stephenavocado** [comment]
Hey @atduarte - this is still affecting my workspace. Can we please resolve? I'm not able to progress right now and it's a big deal.

**Comment by atduarte** [comment]
@stephenavocado we weren't able to lift the ngrok block yet, but are close to doing so. This issue is being followed at https://github.com/gitpod-io/gitpod/issues/9452.
