### ISSUE TITLE
Jedi Issue

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#937]
**Describe the bug**

![image](https://user-images.githubusercontent.com/50386709/69200815-ea2e5800-0b01-11ea-99dd-6d5e5d02fc38.png)
Unknown what cause was
**To Reproduce**
Unknown
**Expected behavior**
error does not occur
**Additional Information**
example repo
https://gitpod.io/#https://github.com/JesterOrNot/MostCommonWordInPDF

**Comment by AlexTugarev** [comment]
@JesterOrNot, @svenefftinge, the vscode extension for Python will download the LS package on demand, but it the download fails, there appears to be no automatic retry. In that case, you can try to reload the browser tab, use the `Python: switch to ... channel`, flip the `python.jediEnabled` setting.

**Comment by AlexTugarev** [comment]
@svenefftinge, I propose to make `jediEnabled: false` by default.

**Comment by JesterOrNot** [comment]
Sorry

**Comment by AlexTugarev** [comment]
We've updated the vscode extension for Python times since this report, and it wasn't mentioned afterwards, thus closing for now as outdated.
