### ISSUE TITLE
Add Team and Project to OWI metadata in ws-manager, so we can inspect metrics by customer

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#9374]
Example use cases: 
1. Understand better the performance requirements of certain teams and project, and support research of #8261.
2. Provide context whenever we need to assist a customer.

cc @kylos101

**Comment by atduarte** [comment]
@kylos101 added "Project". WDYT?

**Comment by kylos101** [comment]
> @kylos101 added "Project". WDYT?

Good clarification, thanks @atduarte !

**Comment by kylos101** [comment]
@atduarte good find ... scheduled!

**Comment by jankeromnes** [comment]
@atduarte In the context of Usage-Based Billing, we would like to allow "re-attributing" workspace usage.

**Use case**: One of your teams upgrades to Usage-Based Billing, and wants to cover 100% of your Gitpod usage (whether that usage is on team projects, or personal projects, or no projects at all just random workspaces).

If we do "re-attribute" usage to a specific team/customer, I guess you'd like the OWI metadata in ws-manager to also show the re-attributed `teamId`, right? (I.e. if team Gitpod covers all my usage, and I open a workspace for a project that's under a different team -- the logs should show Gitpod's teamId, not the other project's teamId, right?)
