### ISSUE TITLE
Workspace didn't automatically start after the prebuild finished

### ISSUE THREAD

**Issue by atduarte** [gitpod-io/gitpod#9375]
### Bug description

Started a gitpod-io/gitpod workspace, the prebuild was running, waited, but it never moved forward to starting the workspace even though the prebuild had finished.

<img width="983" alt="image" src="https://user-images.githubusercontent.com/666176/163817402-c09352a4-ef04-4923-b3b0-5a1dd38cb1cf.png">

### Steps to reproduce

Unsure.

### Expected behavior

Workspace should start automatically.

**Comment by geropl** [comment]
Dupe of: https://github.com/gitpod-io/gitpod/issues/8195
