### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by mrwillpenrose** [gitpod-io/gitpod#938]
How do we preview our projects in a completely seperate browser window rather than just a standard preview on the same page as the editor?

**Comment by svenefftinge** [comment]
Click either the link on top of the preview window.
<img width="557" alt="Screenshot 2019-11-21 at 16 25 30" src="https://user-images.githubusercontent.com/372735/69351561-d0b11b80-0c7b-11ea-94f7-07293bdbbd63.png">

or open the ports view in the bottom panel (next to the terminal)
<img width="831" alt="Screenshot 2019-11-21 at 16 25 53" src="https://user-images.githubusercontent.com/372735/69351575-d444a280-0c7b-11ea-85c3-bd67b84e87f6.png">

Finally, you can also use the cli to get the eternal URL for a certain port.
E.g. type the following in the terminal.
````
gp url <port>
```
