### ISSUE TITLE
GitHub.com: "Cannot read properties of undefined (reading 'id')"

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#9383]
### Bug description

![image](https://user-images.githubusercontent.com/32448529/163863927-6996d23f-293c-4f7d-9939-f7fcd5973954.png)

### Steps to reproduce

Open workspace on context: `https://gitpod.io/#github.com/gitpod-io/gitpod/tree/gpl/6285-edomains`

### Expected behavior

It should open the workspace

**Comment by aledbf** [comment]
I also see 
![Screenshot from 2022-04-18 14-30-54](https://user-images.githubusercontent.com/161571/163879614-fb0cda30-f2d3-43d8-a7e8-592b5ee181e3.png)

**Comment by NotNoah** [comment]
Also getting this when trying to load a new workspace with a queue'd prebuild

**Comment by CompeyDev** [comment]
Me too, here's my error:
![image](https://user-images.githubusercontent.com/74418041/163924907-b88c4316-cf1b-40b9-974e-cfb1e45f4f03.png)

**Comment by shaal** [comment]
I see it when I push a new commit, the prebuild status through projects page seems stuck.
When I open that branch in Gitpod workspace I see that error message like in the screenshot above, when I refresh the page the prebuild starts running.

**Comment by trumbitta** [comment]
😢

**Comment by jankeromnes** [comment]
Sorry about this new bug folks.

We believe this might have been a side effect of https://www.gitpodstatus.com/incidents/cpr3xxsw7dl6

However, let's still investigate it further, to make sure we're not missing any unrelated/new problems.

**Comment by jankeromnes** [comment]
Side note: The other mentioned error might be unrelated:

```
QueryFailedError: ER_DATA_TOO_LONG: Data too long for column 'id'
```

Looking at [HoneyComb](https://ui.honeycomb.io/gitpod/datasets/gitpod-production/result/wXnruEsyRCv/trace/qGYmdpdj5ra?span=17720c478bfb1016) (internal), it looks like this can happen in `WorkspaceFactory.createForCommit`, specifically when storing a new Workspace:

https://github.com/gitpod-io/gitpod/blob/2f0b9462b0451f0974434fa36bd757420ef04e34/components/server/src/workspace/workspace-factory.ts#L208-L221

According to the database, Workspace IDs should never be longer than 36 characters:

https://github.com/gitpod-io/gitpod/blob/2f0b9462b0451f0974434fa36bd757420ef04e34/components/gitpod-db/src/typeorm/migration/1592203031938-Baseline.ts#L43

Maybe it's possible that our (relatively) new workspace ID generator can sometimes generate IDs longer than 36 characters?

https://github.com/gitpod-io/gitpod/blob/2f0b9462b0451f0974434fa36bd757420ef04e34/components/gitpod-protocol/src/util/generate-workspace-id.ts#L8-L12

**Comment by jankeromnes** [comment]
Regarding the original error:

```
Cannot read properties of undefined (reading 'id')
```

When searching for occurrences in our logs, it looks like it might have stopped happening over an hour ago -- around the time we resolved the incident by deploying WebApp:

<img width="838" alt="Screenshot 2022-04-19 at 12 06 24" src="https://user-images.githubusercontent.com/599268/163980902-c6e34e90-2ab9-41e8-ab9d-9b1531b49a39.png">

**Comment by svenefftinge** [comment]
I wonder why those errors are logged without a stacktrace and with `info` severity.

**Comment by geropl** [comment]
Closing as this resolved after fixing our DB issues (cmp. [comment above](https://github.com/gitpod-io/gitpod/issues/9383#issuecomment-1102446816)).
