### ISSUE TITLE
Error loading webview: Error: Could not register service workers: SecurityError: The operation is insecure..

### ISSUE THREAD

**Issue by CarlosDomingues** [gitpod-io/gitpod#9386]
### Bug description

When opening a GitHub repository as a GitPod workspace, the following error is shown continuously: `Error loading webview: Error: Could not register service workers: SecurityError: The operation is insecure.`

Screenshot:

![unknown_001](https://user-images.githubusercontent.com/11181378/163873682-b78d82e7-5ae5-4c26-a13d-940b0d245f58.png)

I'm using:

- Fedora Linux 35
- Firefox 98.0.2(64 bit) (Flatpack version)

**Comment by axonasif** [comment]
Hey @CarlosDomingues, can you try in firefox safe mode?
https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode

**Comment by CarlosDomingues** [comment]
That works. Also, I cannot reproduce the issue again by turning Troubleshoot Mode off. Likely some weird interaction with an extension. Will close this issue. Thanks for the help!

**Comment by RV12R** [comment]
That didnt work for me.

**Comment by ararename** [comment]
Same here, i have this error "Could not register service" since the beginning when i started the "Full Stack Web Development in the Cloud Course - Svelte, Postgres, Vercel, Gitpod" tutorial from freecodecamp. I have it inside of the VS Code web interface Gitpod provides (no local editor connected).

**Comment by reeceyng** [comment]
If you are using firefox, try to click shield near the URL and disable Enhanced Tracking Protection.

**Comment by sivinnguyen** [comment]
> If you are using firefox, try to click shield near the URL and disable Enhanced Tracking Protection.

Thanks, it works for me

**Comment by alvarobartt** [comment]
> If you are using firefox, try to click shield near the URL and disable Enhanced Tracking Protection.

Thanks @reeceyng, that worked!

**Comment by HappySaila** [comment]
> If you are using firefox, try to click shield near the URL and disable Enhanced Tracking Protection.

Thank you!!
