### ISSUE TITLE
Will the concrete implementation of the IDE container be an abstract API in Gitpod's architecture?

### ISSUE THREAD

**Issue by inlann** [gitpod-io/gitpod#9387]
Hello:

Came from Gitpod discord community 😄 

Last year, my company was trying to find an IDE framework to customize an IDE for the embedded industry. Since our team is full of Javascript engineers, we started out focusing on VS Code, the industry's leading IDE. But when we studied VS Code's source architecture, we found it difficult and inappropriate for a team to develop it collaboratively. Then we found the Eclipse Theia. We quickly built our IDE using Theia, and since our company is a toolchain development company for RISCV, we added a lot of source code performance analysis functionality for C/C++ to it.

We found the awesome Gitpod framework 🚀  and tried to build a cloud version with it for our IDE😆. But when I tried to find some related documentation, I found a [blog](https://www.gitpod.io/blog/cloud-ide-history) that documented the history of the Gitpod IDE, which mentioned Gitpod switching from Theia to the OpenVSCode server to provide a better editing experience. I can understand the motivation for this change, but unfortunately I still need to find a cloud framework that is compatible with Theia. So I [posted](https://discord.com/channels/816244985187008514/879915120510267412/965444319811100733) to the Gitpod community for help and looked up the history of Theia related commits in the Gitpod repository.

I think the selection of IDE is to change the container's Dockerfile, since both OpenVSCode server and Theia are running in the container. Like the CNI or CSI of Kubenetes, should not the concrete implementation of the IDE container be an abstract API in the Gitpod architecture?

Really appreciate 😄

**Comment by loujaybee** [comment]
I believe this request is similar to: https://github.com/gitpod-io/gitpod/issues/2419 so I'm going to close the issue as a duplicate. The API for custom IDE's is not documented nor stable right now. If you want to share more details of your use case on the other issue, please do 🙏
