### ISSUE TITLE
Angular CLI Installs, but NG Does Not Work

### ISSUE THREAD

**Issue by eoscryptodev** [gitpod-io/gitpod#939]
**Describe the bug**
I can't install `npm install -g @angular/cli` because I get an error message in the terminal that says 

> Missing write access to /usr/lib/node_modules

> Error: EACCES: permission denied, access '/usr/lib/node_modules'

Even though I am in the root directory and this is on my Github repo. However, it **does** install when I remove the `-g` and simply run `npm install @angular/cli.` However, this is the source of my problem, because the package.json file shows that Angular CLI is installed, but when I try to do anything using ng it fails and gives and error. 

**To Reproduce**

1. npm install @angular/cli in root directory
2. **ng version**

> Command 'ng' not found, but can be installed with: sudo apt install ng-common

3. ng lint

> Command 'ng' not found, but can be installed with: sudo apt install ng-common

It's the same thing, as if Angular isn't actually installed and it wants me to install ng-common, which I can't do either because of a lack of permissions. This is what I get when I run sudo apt install ng-common...

> effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

I even tried to npm install ng-common and I got an error message as well. So I've hit a brick wall. I know I can use the Angular CLI in Gitpod and I really need it for a project I'm working on but for some reason it's not working with me.

**Expected behavior**
Install and use Angular within a decentralized application I'm building using Gitpod.

**Additional Information**
See Above

**Comment by eoscryptodev** [comment]
I got it to run by using 
`alias ng="/workspace/dappgame/dapp/phaser/angular/hackathon/node_modules/@angular/cli/bin/ng"`

Is there a way to make this permanent or do I have to run this each and every time I open my workspace?

**Comment by JesterOrNot** [comment]
one bandaid-ish fix you could use is making a start task in .gitpod.yml command:alias ng="/workspace/dappgame/dapp/phaser/angular/hackathon/node_modules/@angular/cli/bin/ng" while we figure out another issue

**Comment by RDIL** [comment]
Or, you can go into your environment variables on the menu in the dashboard, and have `$PATH` be `workspace/dappgame/dapp/phaser/angular/hackathon/node_modules/@angular/cli/bin:${PATH}`

**Comment by jankeromnes** [comment]
Hi @eoscryptodev, sorry for the late reply. For me, installing `@angular/cli` globally in Gitpod works fine:

```
$ npm install -g @angular/cli
/home/gitpod/.nvm/versions/node/v10.16.3/bin/ng -> /home/gitpod/.nvm/versions/node/v10.16.3/lib/node_modules/@angular/cli/bin/ng
[...]
+ @angular/cli@8.3.20
added 250 packages from 186 contributors in 58.75s

$ ng --version
[...]
Angular CLI: 8.3.20
Node: 10.16.3
OS: linux x64
```

Maybe there is something particular about your project that's breaking npm?

Please share a workspace snapshot or a link to your repository if it's public.

---

If I should hazard a guess at what the problem is, I'd bet that you have a `.gitpod.Dockerfile` that installs stuff as user `root`:

```Dockerfile
USER root
RUN npm install -g stuff
```

If that's the case, please run stuff as user `gitpod` instead:

```Dockerfile
USER gitpod
RUN npm install -g stuff
```
