### ISSUE TITLE
Server is leaking streams to supervisor terminal.

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#9393]
### Bug description

It is a follow up: https://github.com/gitpod-io/gitpod/pull/9331 Apparently server leaks clients which stops reading and never close leading to stale prebuilds.

### Steps to reproduce

See above.

**Comment by geropl** [comment]
This is one of the potential sources for our accumulating event loop lag :point_up:

**Comment by akosyakov** [comment]
Start a prebuild on https://github.com/gitpod-io/spring-petclinic You will see in logs of supervisor that at some point a client for prebuild page will be dropped after 5 secs of inactivity.

**Comment by geropl** [comment]
De-scheduled because we removed memory pressure. Keeping it around for future measurements.
