### ISSUE TITLE
Workspace Start Randomly Fails

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#9394]
### Bug description

Starting a workspace on gitpod-io/gitpod randomly fails. 
I started it and noticed that it turned into stopping on after start. Didn't see any errors on the UI.
Restarting it gave me the "no backup" error.

Starting another fresh workspace succeeded without problems.

Here are the logs for the first start:
https://cloudlogging.app.goo.gl/9NpHpMmpLnrDXiYW7

### Steps to reproduce

Start a workspace and maybe you are (un)lucky.

### Workspace affected

gitpodio-gitpod-spjv7qx5ewd

**Comment by atduarte** [comment]
@svenefftinge get no log entries on the link you shared. Did it happen again?
