### ISSUE TITLE
Prebuilds are stuck in 'queued'

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#9395]
### Bug description

The DB contains +6k entries of prebuilds in 'queued' state. Would be good to understand what happens, clean things up and prevent these from being created further.

#### Updating prebuilt.state on failed prebuild start
During [this incident](https://www.gitpodstatus.com/incidents/cpr3xxsw7dl6) we discovered that there seems to be an ongoing issue with updating state for prebuilds whose instances never reach `RUNNING` phase (note the empty `startedTime`):
```
SELECT wsi.id, wsi.creationTime, wsi.phasePersisted, wsi.status, wsi.startedTime, wsi.stoppingTime, wsi.stoppedTime
   FROM d_b_workspace_instance AS wsi
   JOIN d_b_prebuilt_workspace AS pws
      ON pws.buildWorkspaceId = wsi.workspaceId
   WHERE pws.state = 'queued'
	AND wsi.phasePersisted = 'stopped'
	ORDER BY wsi.creationTime DESC;
```

Note: Especially older entries could also be fallout from other incidents + cleanups, but there seems to be a couple of fresh ones every day.

### Steps to reproduce

`select * from d_b_prebuilt_workspace where state = 'queued' order by creationTime;`

**Comment by svenefftinge** [comment]
I noticed that the `stoppingTime`s are always around the same seconds and happen in chunks at the same time. So probably some clean-up mechanism. 👀

**Comment by geropl** [comment]
> The cases have in common that the phase is unknown (which has a timeout of 600 secs vs. 3600 secs for preparing).

This sounds related to a fix @andrew-farries is working on [here](https://github.com/gitpod-io/gitpod/pull/9453). At some point we seem to have started using `"unknown"` as the initial phase - which does not make sense to me, at all. We're seeking to fix this now, and 

@andrew-farries Can you make sure we [introduce separate timeouts](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-bridge/src/meta-instance-controller.ts#L43) for "building", and start out with the same value as "preparing"?

**Comment by svenefftinge** [comment]
Yes, that explains why they are no signs in workspace-cluster the workspaces are probably building and timing out in the meantime (after 10min).

**Comment by jldec** [comment]
Suspected [example](https://app.frontapp.com/open/cnv_j5h2rbe) of affected user (internal)
Is there a workaround or DB change we can use to mitigate?

**Comment by geropl** [comment]
Having had a look at the data we indeed leak a couple of prebuilds in `queued` every day.
There seem to be two constellations:
 1. image build timed out (after 1h): we currently have not (reliable) way to ensure that whenever an image build fails, we also fail the prebuild, because we assume we're watching the imagebuild from `server` from start -> end
 2. prebuild workspaces are stopped after 10mins: no image builds, and no idea why those are stopped and by whom (yet)
