### ISSUE TITLE
Renaming a Python symbol is very slow (7 seconds)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#94]
**Describe the bug**

When I rename a symbol using `F2` and hit `Enter`, it takes 7 seconds to take effect, which is too slow.

**To Reproduce**

1. Check out https://github.com/mozilla/release-services/pull/1579 in Gipod (using button or `gitpod.io#` prefix)
2. Open a Python file, e.g. `src/staticanalysis/bot/tests/test_reporter_mail.py`
3. Click on a symbol, e.g. `payload` (this quickly highlights all occurrences)
4. Hit `F2` to rename the symbol, and type some value (e.g. `hello`), then hit `Enter`

**Expected behavior**

All occurrences of the symbol `payload` should be renamed almost instantly.

**Actual behavior**

It takes several seconds (7 in my tests) to rename the symbol, which is confusing and a bit annoying.

**Comment by svenefftinge** [comment]
For the described case it took 2secs for me. But for renaming something referenced in more files I could reproduce the slowness. It is the pyls that is simply slow with larger projects.
We should show some sort of progress indicator for pending requests.

**Comment by AlexTugarev** [comment]
@jankeromnes I couldn't find that repro anymore ;-) and all places in the repo ☝️ I tried with the vscode extension were pretty fast. 
if you have time to test again, it would be awesome to have this verified 🙏

**Comment by jankeromnes** [comment]
Thanks for trying this again! 🙏 I believe you that the vscode extension fixed the extreme slowness. 😄

In general, it would be interesting to measure how fast various language server features respond, and to investigate/optimize the slowest actions. But this can be done in a future issue.
