### ISSUE TITLE
show disk pressure for gitpod I want to open

### ISSUE THREAD

**Issue by nepomnyashchiy** [gitpod-io/gitpod#940]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by jankeromnes** [comment]
Hi @nepomnyashchiy, sorry about this problem.

This was an incident with our Kubernetes cluster, where one of the nodes had a disk that was full. I believe this issue has been resolved.

Could you please try again and confirm that it works? Thanks again!

**Comment by nepomnyashchiy** [comment]
Everything is ok
Thanks
