### ISSUE TITLE
Workspace randomly stopped while actively coding

### ISSUE THREAD

**Issue by matthijs-relay** [gitpod-io/gitpod#9401]
### Bug description

I was coding actively in a workspace for a while (through VS Code desktop). Then I briefly switched to a browser window (couldn't have been more than 5 minutes). When switching back to the VS Code window, the workspace seemed to have timed out for no good reason. Checked in the dashboard and it was in the "Stopping" state.

### Steps to reproduce

(not consistently reproducible)

- Code in a workspace through VS Code desktop
- Briefly switch away from the workspace window (not even close to regular timeout duration)
- Go back to workspace window

### Workspace affected

collabai-collabai-td5dcj391sx

### Expected behavior

Workspace shouldn't stop when I'm actively using it

**Comment by axonasif** [comment]
Hey @matthijscollabai, can you grab your console logs when that happens again and email them to contact@gitpod.io with this issue as a reference 🙏 ?
