### ISSUE TITLE
Gitpod isn't loading correctly

### ISSUE THREAD

**Issue by aren0104** [gitpod-io/gitpod#941]
**Describe the bug**

When I try to access my dashboard, I get a blank screen. Also, when trying to create a workspace, the screen is stuck at loading indefinitely.
![Gitpod Loading Screen](https://user-images.githubusercontent.com/56135242/69287627-7c933200-0bbc-11ea-8973-c9602484f8a0.PNG)
![Gitpod Dashboard](https://user-images.githubusercontent.com/56135242/69287628-7c933200-0bbc-11ea-8a26-5d374bbafcbd.PNG)

**To Reproduce**

Navigate to https://gitpod.io/workspaces/. The dashboard doesn't load.

**Expected behavior**

There should be a dashboard on the screen.

**Additional Information**

**Comment by svenefftinge** [comment]
This happens when you cannot connect to our servers (no websocket connection). It should eventually (after a couple of tries) tell you in a dialog. Could it be that your connection was spotty or you were offline?

**Comment by devlocalhost** [comment]
i have the same issue, when i try to load a project, im stuck at the loading screen, and its not the internet fault, i have a poor wifi (6-7mbps) but still, i dont think its the internet...

**Comment by devlocalhost** [comment]
the workspace loads btw, i dont have any issue with the workspace

**Comment by geropl** [comment]
This should only happen if you have bad internet connection and/or your websocket connection terminates too often. Browser have a limit on max websocket reconnection attempts per time, which cools down after some time (~10 minutes).

What helps is to close as much gitpod.io tabs as possible (as the limit counts per (root-)domain).
