### ISSUE TITLE
Create a OIDC Provider for Vault JWT access on each Pod

### ISSUE THREAD

**Issue by unix-system** [gitpod-io/gitpod#9412]
## Is your feature request related to a problem? Please describe
If I host GitPod Self-Hosted, I want to have strong credential-less authentication that hooks into my Vault provider. Currently the only way to authenticate is to store some secret or environment variable and paste that into GitPod.

Likewise, if I wanted a higher security setup I could make it so the only way to access my development environment is through GitPod (rather than locally authenticating) which may help protect my dev infrastructure from compromise.

## Describe the behaviour you'd like
GitLab has a [fantastic pattern for achieving similar things](https://docs.gitlab.com/ee/ci/examples/authenticating-with-hashicorp-vault/) with their Runners. GitPod would expose a JWT endpoint, which would store the public key/certificate information, and in turn be used to create a JWT auth method. Vault could then create a JWT user against this provider with a bound_claim that limits access to the JWT user based on properties such as the Repository URL, the user who initiated the runner, or other useful information that could be included in a bound claim. The bound claim is in the form of a JSON Web Token ("JWT") which is signed by the private key of the GitPod OIDC provider and therefore provides assurance that it is genuine.

Vault could then have secrets engines that could generate credentials (i.e. GCP credentials), and access to individual credentials could be tied to JWT users (which in turn are restricted via bound_claims to individual Pods / repositories / projects / users, as required).

## Describe alternatives you've considered
Environment Variables (currently the only way to put in secrets) is really not ideal as these are hard coded credentials. In the spirit of ephemeral environments, I think instead credential access should not be required.

## Additional context
N/A

**Comment by AlexTugarev** [comment]
@csweichel, that sounds familiar, doesn't it?
