### ISSUE TITLE
Feature Request: Ability to add existing workspaces to projects

### ISSUE THREAD

**Issue by mteam88** [gitpod-io/gitpod#9414]
## Describe the behaviour you'd like
In the projects page of gitpod.io (`gitpod.io/projects`) When selecting the hamburger (three dots) menu, have an option to add an existing workspace to that project (something like "Add an existing workspace.") 

It may also be nice to add a way to add a workspace to a project from `gitpod.io/workspaces`

## Describe alternatives you've considered
It is currently necessary to create a new workspace, which is frankly annoying.

**Comment by svenefftinge** [comment]
Understandably this is annoying if you get very attached to your workspace. It would however, need a change in how we model the association between workspaces. What you can do, though is take a snapshot of your beloved workspace and open that one. It should be associated with the project automatically. Removing it from the inbox for now.

**Comment by mteam88** [comment]
@svenefftinge Thanks for replying, good workaround. The functionality though would be nice for all sorts of project related functions: adding, removing workspaces, multi-workspace environments etc.
It's a change that will make other changes easier...
