### ISSUE TITLE
Remote-explorer opens localhost instead of `gp url`

### ISSUE THREAD

**Issue by ArthurSens** [gitpod-io/gitpod#9419]
When opening a new port with remote-explorer I get redirected to localhost

https://www.loom.com/share/b3d4dd4758ae40f0a56580967d79e1e4

I'm not using VS Code insiders!

**Comment by jeanp413** [comment]
Hey @ArthurSens can you reproduce this consistently or it was a one time thing? From my investigation the url that gets opened in the browser is independent from vscode and supervisor, it just opens whatever url gets from [InstanceUpdates api](https://github.com/gitpod-io/gitpod/blob/de440410fb865d770bc33b135411e896a347323b/components/supervisor/pkg/ports/exposed-ports.go#L103-L124)
If you see it again, can you share the workspace instance id to look into gcp logs maybe something shows up in there

**Comment by ArthurSens** [comment]
I can still reproduce it :) 

Recorded a quick loom:
https://www.loom.com/share/e865979b2be94e3e825551ef31ecd23a

It does look like a very specific problem with the application itself that I'm trying to access

**Comment by jeanp413** [comment]
Does this happens only with this port 8080 or any port?

> It does look like a very specific problem with the application itself that I'm trying to access

Seems like it, can you reproduce in a preview environment so I can enable more logging in there or could you share the exact steps to get this `svc/argocd-server` running so I can reproduce myself?

**Comment by ArthurSens** [comment]
> Does this happens only with this port 8080 or any port?

Any port

> > It does look like a very specific problem with the application itself that I'm trying to access
> 
> Seems like it, can you reproduce in a preview environment so I can enable more logging in there or could you share the exact steps to get this `svc/argocd-server` running so I can reproduce myself?

I think the easiest way to do it is:

1. Open a workspace from this repo: https://github.com/gitpod-io/ops
2. Run the command `kubectl port-forward -n argocd svc/argocd-server <port>:80`. Changing `<port>` to any port you'd like

**Comment by jeanp413** [comment]
I could reproduce and yeah it's some config issue with the http server in svc/argocd-server, the port gets exposed correctly the thing is that the response from the server is a redirect to localhost as you said in your video

```
Request URL: https://9000-gitpodio-ops-mu6jh8fp3za.ws-us43xl.gitpod.io/
Request Method: GET
Status Code: 307 
Remote Address: 35.233.195.232:443
Referrer Policy: strict-origin-when-cross-origin

content-length: 59
content-type: text/html; charset=utf-8
date: Thu, 28 Apr 2022 07:48:18 GMT
location: https://localhost:9000/
```

**Comment by ArthurSens** [comment]
I'm more than happy to close this issue if there's nothing to be done here :)

I'm sorry for taking your time investigating a dead-end 😬

**Comment by jeanp413** [comment]
yeah I think it's fine to close it :+1:
