### ISSUE TITLE
How to edit php.ini file in gitpod?

### ISSUE THREAD

**Issue by marciodouglasIFRN** [gitpod-io/gitpod#943]
Estou trabalhando em um projeto php testando o gitpod, no projeto gostaria de usar o PDO para o mysql, mas não consigo editar o arquivo /etc/php/7.2/cli/php.ini para habilitar essa extençao devido as permições.

Alguem poderia me ajudar?

**Comment by JesterOrNot** [comment]
Você pode usar o bash para editar o arquivo, talvez algo como
 /etc/php/7.2/cli/php.ini << "O que eu quero escrever"

**Comment by marciodouglasIFRN** [comment]
### Tentei fazer dessa forma, mas nada foi alterado em meu arquivo
`RUN /etc/php/7.2/cli/php.ini << "extension=pdo_mysql"`
### Tentei outra trocar o trecho de código comentado pelo código descomentado com o seguinte comando 
`RUN sed -i 's/;extension=pdo_mysql/extension=pdo_mysql/g' /etc/php/7.2/cli/php.ini`
e tabem não funcionou

**Comment by svenefftinge** [comment]
You would need to change it with duso, which is only available dring docker build.
You can type `gp init` in your repo and add a corresponding `RUN` statement to the dockerfile.

**Comment by marciodouglasIFRN** [comment]
Aqui está meu dockerfile
`FROM gitpod/workspace-full

USER root

# Install custom tools, runtime, etc. using apt-get
# For example, the command below would install "bastet" - a command line tetris clone:
#
RUN apt-get update 
RUN apt-get install -y mysql-server 
RUN sed -i 's/;extension=pdo_mysql/extension=pdo_mysql/g' /etc/php/7.2/cli/php.ini
# RUN /etc/php/7.2/cli/php.ini << "extension=pdo_mysql"
#
# More information: https://www.gitpod.io/docs/42_config_docker/`

Aqui o trecho do arquivo php.ini que eu quero alterar trocando `;extension=pdo_pgsql` por `extension=pdo_pgsql`

`;extension=odbc
;extension=openssl
;extension=pdo_firebird
;extension=pdo_mysql
;extension=pdo_oci
;extension=pdo_odbc
;extension=pdo_pgsql
;extension=pdo_sqlite`

Mas o arquivo php.ini não mudou nada

**Comment by tutur0001** [comment]
Hello, i've this probleme in my gitpod can you help me

**Comment by Kreyren** [comment]
@tutur0001 elaborate on the problem?

***kreyren** would think that you can edit .ini file using the current editor*

**Comment by tutur0001** [comment]
@Kreyren thank's for your answser
I want edit php.ini in my gitpod but i don't have root permission 
but i can use the dockerfile and the gitpod.yml

**Comment by Kreyren** [comment]
@tutur0001 i see, do you have an example repo?

**Comment by tutur0001** [comment]
it's on my school repo 
i'm student's

**Comment by Kreyren** [comment]
@tutur0001 Could you make an example repository on github? i.e php with hello world or something

**Comment by tutur0001** [comment]
https://gitpod.io#snapshot/4e0dcbe9-0d28-4ded-a479-fcf2d73f4b7d

**Comment by Kreyren** [comment]
@tutur0001 Try this https://gitpod.io#snapshot/a16a0a93-8eeb-4c78-907e-685337983999

**Comment by Kreyren** [comment]
also `RUN addgroup gitpod ...` you don't need to add gitpod group, gitpod-layers appended to all dockerfiles on gitpod are doing this for you already (+ some other security related checks)

**Comment by tutur0001** [comment]
I do not understand everything
It’s our teachers who set up all this I’m never used as a docker in my life

**Comment by Kreyren** [comment]
@tutur0001 noted let me check it on my end then

**Comment by Kreyren** [comment]
@tutur0001 

```dockerfile
FROM gitpod/workspace-mysql

USER root

# Install required dependencies
RUN true \
	&& apt-get update \
	&& apt-get -y install \
		apache2 \
		php \
		libapache2-mod-php \
		php-mysql \
		php-curl \
		php-gd \
		php-mbstring \
		php-xml \
		php-xmlrpc

# Do something
RUN printf '%s\n' "include /workspace/apache/apache.conf" > /etc/apache2/apache2.conf
RUN printf '%s\n' ". /workspace/apache/envvars" > /etc/apache2/envvars

# Do something
RUN addgroup gitpod www-data

# Allow gitpod group to edit php backend
RUN true \
	&& chown -R root:gitpod /etc/php \
	&& chmod -R g+rw /etc/php
```

Works for me ^-^

**Comment by Kreyren** [comment]
Also these changes will not persist on each gitpod run unless you are using the same workspace i.e pinning it and then not letting it being removed after 14 days of inactivity:
![image](https://user-images.githubusercontent.com/11302521/80802682-8b383900-8b9f-11ea-8455-b2f5c2a57009.png)

If you expect these changes to be permanent you can make copy of `php.ini` in your `.gitpod` or `gitpod` directory and then use:

```Dockerfile
COPY .gitpod/php.ini /etc/php/7.4/cli/php.ini
```

In your defined dockerfile i.e
![image](https://user-images.githubusercontent.com/11302521/80802749-bae74100-8b9f-11ea-9b6b-baa6a50c83bc.png)

**Comment by tutur0001** [comment]
To apply these changes, I just need to turn off and restart my gitpod?
Ps: thanks a lot for your help

**Comment by Kreyren** [comment]
> To apply these changes, I just need to turn off and restart my gitpod?

You need to open a new gitpod instance so that it rebuilds the environment.

FWIW gitpod is working on root access tracked in https://github.com/gitpod-io/gitpod/issues/39 currently it's not allowed, because the staff needs to perform sanity checks (like you can get root if you know how linux works atm where the concern is that you might be able to access the other 3 workspaces in the node, but i personally wasn't able to get that far).

**Comment by tutur0001** [comment]
<img width="1440" alt="Capture d’écran 2020-05-01 à 13 38 10" src="https://user-images.githubusercontent.com/55830974/80802909-0f46ec80-8bb1-11ea-8195-6e6dff65386b.png">

**Comment by Kreyren** [comment]
@tutur0001 i can see that this is not the dockerfile that i've gave you 
![image](https://user-images.githubusercontent.com/11302521/80802958-67292780-8ba0-11ea-941c-13db8de8c3a2.png)

again you need to commit the changes to the repository for gitpod to see them, See https://github.com/gitpod-io/gitpod/issues/943#issuecomment-622355062 and proposed dockerfile in https://github.com/gitpod-io/gitpod/issues/943#issuecomment-622353175

**Comment by Kreyren** [comment]
@tutur0001 Did it work? ^-^

**Comment by tutur0001** [comment]
hm how to open a new gitpod instance ?

**Comment by Kreyren** [comment]
@tutur0001 Using https://gitpod-io/#path-to-your-repository with your expected dockerfile commited to the repository and pointed by `.gitpod.yml`'s `file` property

**Comment by Kreyren** [comment]
Alternatively you can give me access to the repository and i will make you a merge request ^-^

**Comment by tutur0001** [comment]
@Kreyren https://ecc7f582-e7ef-4eac-a1d2-5acc2b3031d4.ws-eu01.gitpod.io/
this my workspace access

**Comment by tutur0001** [comment]
you use branch dev

**Comment by Kreyren** [comment]
@tutur0001 

```
diff --git a/.gitpod.Dockerfile b/.gitpod.Dockerfile
index 223161b..fd0b583 100644
--- a/.gitpod.Dockerfile
+++ b/.gitpod.Dockerfile
@@ -2,28 +2,9 @@ FROM gitpod/workspace-mysql
 
 USER root
 
-# Install required dependencies
-RUN true \
-	&& apt-get update \
-	&& apt-get -y install \
-		apache2 \
-		php \
-		libapache2-mod-php \
-		php-mysql \
-		php-curl \
-		php-gd \
-		php-mbstring \
-		php-xml \
-		php-xmlrpc
+RUN apt-get update && apt-get -y install apache2 php libapache2-mod-php php-mysql php-curl php-gd php-mbstring php-xml php-xmlrpc
 
-# Do something
-RUN printf '%s\n' "include /workspace/apache/apache.conf" > /etc/apache2/apache2.conf
-RUN printf '%s\n' ". /workspace/apache/envvars" > /etc/apache2/envvars
+RUN echo "include /workspace/apache/apache.conf" > /etc/apache2/apache2.conf
+RUN echo ". /workspace/apache/envvars" > /etc/apache2/envvars
 
-# Do something
 RUN addgroup gitpod www-data
-
-# Allow gitpod group to edit php backend
-RUN true \
-	&& chown -R root:gitpod /etc/php \
-	&& chmod -R g+rw /etc/php
\ No newline at end of file
```

Patch also submitted to `dev` branch

**Comment by Kreyren** [comment]
Also note that sharing your workspace alike https://github.com/gitpod-io/gitpod/issues/943#issuecomment-622366739 is considered a security vulnerability and you should change your SSH keys.

**Comment by Kreyren** [comment]
@tutur0001 
![image](https://user-images.githubusercontent.com/11302521/80806568-8a58d480-8baa-11ea-8110-96162d1720be.png)

**Comment by tutur0001** [comment]
that's ok for me thanks for your help ^^

can you delete the picture with my link ? and my link ?

**Comment by tutur0001** [comment]
because i don't have the controle on my gitpod

**Comment by Kreyren** [comment]
Updated https://github.com/gitpod-io/gitpod/issues/943#issuecomment-622355487

**Comment by Kreyren** [comment]
Resending comment https://github.com/gitpod-io/gitpod/issues/943#issuecomment-622355487 above, because github preserves history of comments

---

@tutur0001 i can see that this is not the dockerfile that i've gave you 
![image](https://user-images.githubusercontent.com/11302521/80806797-2551ae80-8bab-11ea-9560-d55cdb1d78d3.png)

again you need to commit the changes to the repository for gitpod to see them, See https://github.com/gitpod-io/gitpod/issues/943#issuecomment-622355062 and proposed dockerfile in https://github.com/gitpod-io/gitpod/issues/943#issuecomment-622353175

**Comment by Kreyren** [comment]
@tutur0001 Did that solve the issue for you?

I will contrib the solution to https://github.com/gitpod-io/workspace-images to hotfix this issue until https://github.com/gitpod-io/gitpod/issues/39 is resolved if so ^-^

**Comment by tutur0001** [comment]
yes it's work for me thank's you !

**Comment by Kreyren** [comment]
@tutur0001 Ping me if you encounter any issues with it please ^-^
