### ISSUE TITLE
[code-desktop] Implement `Gitpod: Collect Logs` comand

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#9431]
It would be really helpful to implement a `Gitpod: Collect Logs` command so users can easily collect logs and shared them with us when they encounter some issue

This command should collect server and client logs and zip them in archive of a format `ws-${instance_id}-vscode-desktop-logs.zip`

**Comment by jeanp413** [comment]
Fixed in https://github.com/gitpod-io/openvscode-server/pull/344
