### ISSUE TITLE
Property aware users that they can choose IDEs with onboarding dashboard

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#9433]
Property aware users that they can choose IDEs with onboarding dashboard

Further opinion: Display recommended template project after they choose some IDE in this page (i.e Goland => template-golang-cli)

It's a IDE feature in our [workshop](https://www.notion.so/gitpod/IDE-Discovery-Increase-awareness-of-desktop-and-JetBrains-IDE-features-to-new-and-returning-users-c98914780b394101bde0fa4be4842de0#6d6dac56acae4054ae0e9ec0e98a7ae6)

See draft [Figma](https://www.figma.com/file/1ofpgCa3XI0F4zZKhcgiGg/%236707?node-id=0%3A1)

|Before|After (onboarding)| After 2(after onboarding)|
|:-:|:-:|:-:|
|<img width="662" alt="image" src="https://user-images.githubusercontent.com/20944364/164272038-3599388f-0652-4198-8e43-6e5a8d5e56ff.png">|<img width="662" alt="image" src="https://user-images.githubusercontent.com/20944364/164272074-4f241e0a-f136-4748-87f4-64cbd5019eae.png">| <img width="641" alt="image" src="https://user-images.githubusercontent.com/20944364/164272114-8bd3b728-be55-4605-8e95-78d2d79ef32b.png">|

**Comment by mustard-mh** [comment]
As a part of https://github.com/gitpod-io/gitpod/issues/6707

**Comment by mustard-mh** [comment]
We may need to discuss the UX and text content about IDE select (see Description Image **After (onboarding)**)

cc @gtsiolis @loujaybee

**Comment by svenefftinge** [comment]
Wouldn't it be good to ask users what IDE they want to use per project? I'm thinking of asking them in the startup flow, before starting the workspace with an option to "never ask again for project xxx/yyy" which is the enabled by default.
Then in the settings, we could provide means to manage this as well, in case you want to be asked again later.

**Comment by mustard-mh** [comment]
@svenefftinge  If you want to choose different IDEs per repo, this PR may be helpful https://github.com/gitpod-io/browser-extension/pull/59. 

For projects, maybe we can provide a context menu with IDE list

**Comment by andreafalzetti** [comment]
@svenefftinge the concept of having a user-preferred IDE per project makes a lot of sense, we should put it on the roadmap IMHO 👍 

At the same time it's still useful to have a default IDE for "everything" else not specified, I suppose.

I just want to highlight that with this issue we are trying to build a small analytics-driven experiment, very time-scoped, to see if we can increase awareness that Gitpod is not only VS Code, during the onboarding phase.

**Comment by loujaybee** [comment]
> Wouldn't it be good to ask users what IDE they want to use per project? - @svenefftinge 

IDE's per project settings is definitely something we want to experiment with (see #6874) there's been quite a lot of feedback from users that a per-project UX is needed on top of the global user preferences (CC: @andreafalzetti given your comment also about adding to the roadmap). However, at this stage, I wouldn't want to mix/merge the two: IDE visibility in onboard with per project IDE's just yet. Let's try and raise a minimal first-pass experiment to add IDE visibility during onboarding, and depending on the results of that experiment, we can adjust with other further experiments such as: 

1. Per project IDE's - #6874
2. Opening ad-hoc IDE's from the dashboard  - #8573 (possibly also in the browser extension [pull/59](https://github.com/gitpod-io/browser-extension/pull/59) as @mustard-mh shared above)
3. In workspace onboarding #9131

> That one is IMHO not generic enough as it requires me to go through the browser extension and there are many other ways to create workspace for a repo/project - @svenefftinge 

I agree. The browser extension is not assumed as a step of our current onboarding flow (see comment on the other PR [[1](https://github.com/gitpod-io/browser-extension/pull/59#issuecomment-1102272311)]). The main two onboarding flows are: login > dashboard > workspace, and/or direct from a repo, or via a context URL. This experiment should focus on impacting these two journeys as a priority.

**Comment by mustard-mh** [comment]
We can also provide a command open users are at Dashboard and going to open a workspace here
When user is pressing `cmd`, present IDEs for them to choose

notice them by showing `cmd` `ctrl` etc tag in repo list right side, and put a layer (with small icon IDEs) when in Projects / Workspaces page

|Dashboard|IDEs Layer (i.e)| notice (i.e from Alfred)
|:-:|:-:|:-:|
|<img width="811" alt="image" src="https://user-images.githubusercontent.com/20944364/164540302-ebb158ba-1222-4615-b3e1-8814368aed7f.png">|<img width="1104" alt="image" src="https://user-images.githubusercontent.com/20944364/164540965-5c7997de-8067-4b71-a1b0-4f9f2f447bc5.png">| <img width="565" alt="image" src="https://user-images.githubusercontent.com/20944364/164541205-3d508dc4-0f14-4e2b-8931-a8b045ce5ba5.png">|

|Present (when pressing) also| and here|
|:-:|:-:|
|<img width="1182" alt="image" src="https://user-images.githubusercontent.com/20944364/164541713-1b4a945b-8eee-48d8-8065-d504f6bb5d80.png">| <img width="1214" alt="image" src="https://user-images.githubusercontent.com/20944364/164541871-0def81e3-eca7-4f3d-aa82-f7c0eadaf993.png">|
