### ISSUE TITLE
Open workspace with custom IDE via URL

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#9434]
Open workspace with custom IDE via URL. related PR https://github.com/gitpod-io/browser-extension/pull/59#discussion_r853098135

**Comment by akosyakov** [comment]
A new prefix parser like `#editor:$editor(:$version)?` could work, not sure whether it can collide with env var prefix parser though. $editor should be alias from ide config map like code, intellij, and $version is stable or latest, by default stable.

**Comment by mustard-mh** [comment]
will add something like `via`, i.e `goland:latest:browser-extension`, for track

**Comment by mustard-mh** [comment]
I think I'm doing the same thing with `#referrer:`...

**Comment by akosyakov** [comment]
closed in favor fo https://github.com/gitpod-io/gitpod/issues/7525
