### ISSUE TITLE
Broken Gitpod button position in browser extension

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#9435]
### Bug description

Seems like GitHub changed their CSS again, causing the Gitpod button to be misplaced:

| Empty repository: broken padding | Specific file: button is now below file |
| --- | --- |
| <img width="1439" alt="Screenshot 2022-04-20 at 19 31 33" src="https://user-images.githubusercontent.com/599268/164289399-0a3a7a5f-bc10-4458-92cc-34b87b53fd64.png"> | <img width="1436" alt="Screenshot 2022-04-20 at 19 32 00" src="https://user-images.githubusercontent.com/599268/164289411-5dca5548-629f-48f8-ae05-a569356efda9.png"> |

### Steps to reproduce

1. Install the browser extension
2. Visit an empty repository or a specific file page on GitHub

**Comment by AllMight2099** [comment]
Hey there!
I fixed the browser extension issue here, but I can't push to the browser-extension repo because I guess I don't have the correct access rights to the repo, who do I contact for this?

**Comment by jankeromnes** [comment]
Hi @AllMight2099 -- many thanks for fixing this bug! 🎉

Would you be able to "fork" this repository, then push the fix to your fork, and then open a Pull Request here? 🙏 I'd be happy to review and approve it. 🚀 

Let me know if you have any questions. 😊

**Comment by AllMight2099** [comment]
Oh sure thing

**Comment by AllMight2099** [comment]
@jankeromnes The PR's up and it's ready to be merged
