### ISSUE TITLE
[Theia] Editor glitch

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#944]
In some editors the space left next to the editor is wider than expected and the collapse/expand-arrows are wrongly indented:
wrong:
<img src="https://user-images.githubusercontent.com/32448529/69428219-f9dfb380-0d30-11ea-978a-efe57411681f.png" height=200 />

correct:
<img src="https://user-images.githubusercontent.com/32448529/69428291-1e3b9000-0d31-11ea-9bc8-3021f6af776c.png" height=200 />

**Comment by akosyakov** [comment]
This happens in PR context for files from PR diff. Arrows are indented because of comment hints.
