### ISSUE TITLE
Is it possible to change Node.js version in a workspace?

### ISSUE THREAD

**Issue by Manish-Giri** [gitpod-io/gitpod#945]
Hello,

This is my first post here. Let me start by saying - I've really enjoyed using Gitpod for all my code contributions, it has saved me the hassle of dealing with different dev env requirements for different open source projects.

I'm currently working on a project which has a strict requirement of using a specific Node.js version, in this case - `12.13` (near the current LTS). Here's an excerpt from their `package.json` -

```json
"engine-strict": true,
  "engines": {
    "node": "12.13.0",
    "yarn": "^1.0.0"
  },

```

When I launch a Gitpod workspace for this project, I run into an error when using `yarn` to install the dependencies -
```
The engine "node" is incompatible with this module. Expected version "12.13.0". Got "10.16.3"
error Found incompatible module.
```

Is there any way I can change the Node version in the workspace to match the requirement?

PS - Just as an experiment, I tried manually adding Node LTS with installation instructions from [here](https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/), but I quickly got a lot of permission denied errors. 

EDIT - This is the [project ](https://github.com/taskcluster/taskcluster)in question, if it helps.

**Comment by JesterOrNot** [comment]
What repo are you working on?
Where are you installing NodeJS?
If in the editor don't do that install it in a dockerfile
(FYI NodeJS comes preinstalled in the Gitpod base image)
going with the experiment
```docker
FROM gitpod/workspace-full
USER root
RUN apt-get update && apt-get install #insert package here
```
hope this helps
see https://www.gitpod.io/docs/42_config_docker/ for more

**Comment by Manish-Giri** [comment]
@JesterOrNot Sorry, I must've missed your reply by a minute. I just edited my post to add the project in question.

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/69471649-21517300-0d67-11ea-8242-0aedacb7b123.png)
try this

**Comment by Manish-Giri** [comment]
@JesterOrNot Thanks! I tried that, and it seems to have fixed the node issue. Now, weirdly, `yarn` cannot be found, after using `nvm` -

<img width="736" alt="Untitled" src="https://user-images.githubusercontent.com/11348778/69471886-5f07c900-0d72-11ea-9956-7b5ac481846a.png">

**Comment by JesterOrNot** [comment]
I'm not sure if that is a node or gitpod issue I'll try it locally

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/69472057-4a740280-0d6b-11ea-8684-4f785ef14444.png)
This is an issue with either node or nvm we should refile issues there

**Comment by JesterOrNot** [comment]
see
https://github.com/nvm-sh/nvm/issues/2128

**Comment by Manish-Giri** [comment]
Thank You

**Comment by jankeromnes** [comment]
Indeed, `nvm` doesn't install `yarn` by default, so whenever you switch to a different Node version, you have to re-install `yarn` yourself, e.g. like so:

```
npm install -g yarn
```

Thanks a lot for your helpful replies @JesterOrNot! 💯

**Comment by studentIvan** [comment]
You can use --reinstall-packages-from param to save the installed packages:
`nvm install v12.16.3 --reinstall-packages-from=node`

**Comment by hotlong** [comment]
```
tasks:
  - name: UseNode14
    command: |
      nvm i 14
      nvm use 14
      nvm alias default  14
      echo "nvm use default &>/dev/null" >> ~/.bashrc.d/51-nvm-fix
```
