### ISSUE TITLE
Running ngrok autocloses workspace

### ISSUE THREAD

**Issue by devops-at-alinea** [gitpod-io/gitpod#9452]
### Bug description

I have been running [ngrok](https://ngrok.com) to provide stable urls for webhooks and callbacks.

This has been working for a long time, now suddenly when ngrok is run the workspace auto closes.

[Support stable URLs for endpoints](https://github.com/gitpod-io/gitpod/issues/898#issuecomment-1104071019)

### Steps to reproduce

Create a new workspace: https://gitpod.io/#https://github.com/gitpod-io/template-nix

Download ngrok
```bash
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip 
unzip ngrok-stable-linux-amd64.zip
```

Setup [ngrok using the authtoken in your dashboard](https://dashboard.ngrok.com/get-started/setup)
```bash
./ngrok authtoken <your auth token>
```

Run ngrok:
```bash
./ngrok http -region=eu 8080
```

### Expected behavior

The workspace should remain open.

**Comment by atduarte** [comment]
Hi @devops-at-alinea. I'm sorry we broke your experience. Given abuse and IO limiting issues, we had to temporarily block ngrok.

**Comment by DaniAkash** [comment]
@atduarte any timeline on when it can be unblocked?

**Comment by kylos101** [comment]
Hi @DaniAkash @devops-at-alinea and @stephenavocado you should be all set now, may we ask you to try starting workspaces again?

**Comment by kylos101** [comment]
Hi @ctrlaltdylan it looks like you may have been impacted by this issue, too. You should be able to start workspaces again, let us know if you're having trouble?

**Comment by kylos101** [comment]
Hello, dear reader, if you were blocked within the last 3 days and are still having trouble, please leave a comment here and we'll reopen the issue.

**Comment by stephenavocado** [comment]
> Hi @DaniAkash @devops-at-alinea and @stephenavocado you should be all set now, may we ask you to try starting workspaces again?

All seems to be working for me. Anything to look out for in the future?

**Comment by DaniAkash** [comment]
@stephenavocado I'm still getting the following error everytime I open my workspace with ngrok setup
<img width="589" alt="Screenshot 2022-04-25 at 12 38 09 PM" src="https://user-images.githubusercontent.com/6841445/165037979-5b2ea0a8-5954-41c1-ac9a-ebc00ca3aafa.png">

**Comment by enriquedecote** [comment]
this is not working on my side
