### ISSUE TITLE
Pixel experience build failed.

### ISSUE THREAD

**Issue by shivaay1234** [gitpod-io/gitpod#946]
I got this error:
FAILED: /Volumes/android/aicp/out/soong/build.ninja
/Volumes/android/aicp/out/soong/.bootstrap/bin/soong_build -t -l /Volumes/android/aicp/out/.module_paths/Android.bp.list -b /Volumes/android/aicp/out/soong -n /Volumes/android/aicp/out -d /Volumes/android/aicp/out/soong/build.ninja.d -globFile /Volumes/android/aicp/out/soong/.bootstrap/build-globs.ninja -o /Volumes/android/aicp/out/soong/build.ninja Android.bp
error: prebuilts/clang/host/darwin-x86/Android.bp:23:1: unrecognized module type "llvm_darwin_filegroup"
error: prebuilts/clang/host/darwin-x86/Android.bp:27:1: unrecognized module type "llvm_darwin_filegroup"
error: prebuilts/clang/host/darwin-x86/Android.bp:31:1: unrecognized module type "llvm_darwin_filegroup"
error: prebuilts/clang/host/darwin-x86/Android.bp:35:1: unrecognized module type "llvm_darwin_filegroup"
error: prebuilts/clang/host/linux-x86/Android.bp:17:1: unrecognized module type "llvm_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:25:1: unrecognized module type "llvm_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:34:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:51:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:68:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:85:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:103:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:117:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:131:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:145:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:165:1: unrecognized module type "libclang_rt_llndk_library"
error: prebuilts/clang/host/linux-x86/Android.bp:175:1: unrecognized module type "libclang_rt_llndk_library"
error: prebuilts/clang/host/linux-x86/Android.bp:185:1: unrecognized module type "libclang_rt_llndk_library"
error: prebuilts/clang/host/linux-x86/Android.bp:195:1: unrecognized module type "libclang_rt_llndk_library"
error: prebuilts/clang/host/linux-x86/Android.bp:205:1: unrecognized module type "libclang_rt_llndk_library"
error: prebuilts/clang/host/linux-x86/Android.bp:215:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:233:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:251:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:269:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:287:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:302:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:317:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:332:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:347:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:360:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:374:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:387:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:400:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:413:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:426:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:438:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:451:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:467:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:483:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:499:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:515:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:529:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:543:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:557:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:571:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:587:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:603:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:619:1: unrecognized module type "libclang_rt_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:635:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:649:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:663:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:677:1: unrecognized module type "libclang_rt_prebuilt_library_static"
error: prebuilts/clang/host/linux-x86/Android.bp:697:1: unrecognized module type "llvm_host_defaults"
error: prebuilts/clang/host/linux-x86/Android.bp:702:1: unrecognized module type "llvm_host_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:712:1: unrecognized module type "llvm_host_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:722:1: unrecognized module type "llvm_host_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:736:1: unrecognized module type "llvm_host_prebuilt_library_shared"
error: prebuilts/clang/host/linux-x86/Android.bp:744:1: unrecognized module type "clang_builtin_headers"
16:06:23 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.

#### failed to build some targets (18 seconds) ####

P.S: I'm building for redmi note 3 pro, AKA kenzo. I'm kinda new to building ROMs, so please help me out...

**Comment by kjjiffy** [comment]
Could you please leat me know how did you resolve this issue?
