### ISSUE TITLE
Failing to start electron

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#947]
**Describe the bug**
When trying to start an electron app I get
![image](https://user-images.githubusercontent.com/50386709/69502412-a9a15680-0ed4-11ea-8706-e30d0d46a7b6.png)
 > gitpod-electron@1.0.0 start /workspace/Gitpod-Electron
 > electron .

[1450:1124/220307.833744:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /workspace/Gitpod-Electron/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.

**To Reproduce**
open https://gitpod.io/#https://github.com/JesterOrNot/Gitpod-Electron
**Expected behavior**
Electron app starts as expected
**Additional Information**

**Comment by svenefftinge** [comment]
Are you using the workspace-vnc image? 
https://github.com/eclipse-theia/theia has a working setup for electron.

**Comment by JesterOrNot** [comment]
Yes it is
![image](https://user-images.githubusercontent.com/50386709/69909475-36f71600-13c1-11ea-8831-263b4f078231.png)

**Comment by JesterOrNot** [comment]
@svenefftinge any thoughts?

**Comment by jankeromnes** [comment]
I've noticed this error in the windows95 repo as well, which used to work fine. There may have been an electron or chromium change that breaks Gitpod. I'll take a look.

**Comment by jankeromnes** [comment]
The solution is to start Electron with `--no-sandbox`, like so:

https://github.com/JesterOrNot/ElectricMusic/blob/master/package.json#L12

See also https://community.gitpod.io/t/problem-setting-up-a-project-to-work-with-electron/278
