### ISSUE TITLE
Last terminal on gitpod.yml is not focused

### ISSUE THREAD

**Issue by sinansonmez** [gitpod-io/gitpod#9473]
### Bug description

There are three terminals listed on `.gitpod.yml`. One of the terminals include `openMode: split-right`
Expected behaviour is that last one should be in focus. However because of `openMode: split-right` the focus is on splitted terminals. When i remove `openMode: split-right`, it works as expected. 

### Steps to reproduce

Open [this repo ](https://github.com/mattermost/mattermost-gitpod-config) in Gitpod

### Workspace affected

https://github.com/mattermost/mattermost-gitpod-config

**Comment by loujaybee** [comment]
The ability to explicitly focus on a terminal could make sense as a gitpod.yml property. How often does this issue affect you? Is there a reason why opening up the editor and needing the focus is more important? Is this whilst stopping and starting a workspace to update `.gitpod.yml` or similar? Or just for general work?

**Comment by sinansonmez** [comment]
When starting workspace, I am opening multiple terminal (run server, run react based front end and others). 

In one of the terminal, I am asking user to enter some inputs such as github username. That is why I want to focus on this terminal so user see the request and enter the requested information.

**Comment by axonasif** [comment]
Hey @sinansonmez, currently you can just put the task below all and it should stay focused.
We're also doing it here: https://github.com/gitpod-io/template-flutter/blob/e4e1645db4a3035a5935344e65411eee913e35d3/.gitpod.yml#L57
You can also try opening the above template on Gitpod to see.

**Comment by sinansonmez** [comment]
Hey @axonasif,  this is actually the issue. 

Even though I put the terminal at end, it doesn't stay focused. 

The reason is that one of the terminals has `openMode: split-right`. It is focused on the terminal with `openMode: split-right` not on the last one. 

When I remove `openMode: split-right`, it works as expected: i.e. last one is focused.

**Comment by vickybiswas** [comment]
I am having the same problem.
The last tab is not getting the focus and instead, the last split-right tab is.
I need my user to be focusing on this and giving inputs.
Is there any known solution?

**Comment by jeanp413** [comment]
This is a peculiar vscode quirk on how it creates terminals, internally terminal creation is async and even though we focus each one in the order they appear in gitpod.yml it can happen that `terminal.show()` for a split terminal runs after other terminals created after it as it needs to await for it's parent terminal to completely resolve internally.

Pushed a fix https://github.com/gitpod-io/openvscode-server/commit/7a4435fd15e6de7cded42874f7737f859438dc42

**Comment by felladrin** [comment]
>cc @jeanp413 @felladrin How hard it would support in VS Code and JetBrains?

Currently, IntelliJ Remote Dev API has no method for controlling the focus on terminals running in JetBrains Client. We also can't control the order the terminals are displayed. Terminal splitting is also not possible at the moment.
