### ISSUE TITLE
'Stop Workspace' prompt is confusing

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#948]
**Describe the bug**

When you click on `File` > `Stop Workspace`, you see a complicated prompt with a countdown:

<img width="401" alt="Screenshot 2019-11-25 at 11 30 18" src="https://user-images.githubusercontent.com/599268/69532943-2ab12a00-0f77-11ea-95a7-761956f65114.png">

The countdown is not enough for me to read and understand the situation, let alone what my options are.

**To Reproduce**
1. Click on `File` > `Stop Workspace`
2. Be confused about what the prompt is asking you + be stressed out because of the countdown

Now I understand why users simply cancel this prompt and leave the workspace unstopped (wasting them precious Gitpod hours).

**Expected behavior**
The IDE should not ask me confusing questions (let alone with a countdown), and instead it should do the right thing without giving me mental overhead.

**Additional Information**

**Comment by JesterOrNot** [comment]
@jankeromnes what about a prompt like this?
---------------------------------------------------------------------------
                   What would you like to do                                 |
[Stay Here]  [Stop this workspace]  [Archive Workspace]     |

**Comment by JesterOrNot** [comment]
Where is Gitpod's source code hosted?

**Comment by RDIL** [comment]
I think its a private repository, looking at the staff members' profiles

**Comment by JesterOrNot** [comment]
Ok, I would have sent a PR for the source code :(

**Comment by jankeromnes** [comment]
Yes, sorry about that, the internal Gitpod infra code (workspaces / kubernetes / etc) is in a private repository. 😕

**Comment by svenefftinge** [comment]
fixed in the meantime.
