### ISSUE TITLE
Limit the scope access needed for S3/Blob storage

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#9484]
## Is your feature request related to a problem? Please describe
Currently, (self hosted) Gitpod requires fairly expansive permissions to your bucket when using a Bucket you bring yourself (i.e. not minio set up by the installer). This goes against guidelines of security conscious organisations and thus would be a blocker. For example, Gitpod needs almost admin level access to S3 and the ability to create new buckets. 

## Describe the behaviour you'd like
- Limit the scope needed by Gitpod to the bare minimum such that it complies with most guidelines (e.g. [these](https://www.cisecurity.org/cis-benchmarks/) and [these](https://www.notion.so/gitpod/Common-Customer-Mandated-Security-1db439eb4f304ab5aed919bce9e81c7c) (internal))
## Describe alternatives you've considered
(Discussed [internally](https://gitpod.slack.com/archives/C01LDA28WV6/p1650526866191959?thread_ts=1650491530.724799&cid=C01LDA28WV6)) One could set up their own Minio gateway to their required credentials/levels. This then has the limited access to their buckets/storage account. Then, Gitpod just makes an S3 connection to that Minio as normal.
It's can be thought of as an "external in-cluster dependency" in that it lives on the cluster (and the connection URL becomes minio-gateway.minio.svc.cluster.local but it's external to our configuration so the deployer can do what they need for it.

In theory, this is a pattern we could use for the registry and database as well. They all have the option to disable the in-cluster resource and the connection parameters can be configured. The only requirement is that the URL is accessible from the Gitpod installation - and something on another namespace on the machine fulfills that requirement.

**Comment by shaoye** [comment]
Instead of creating one bucket for each user, it would be great if we can put everything just under one bucket, which can directly solve the access scope issue

https://github.com/gitpod-io/gitpod/issues/2385
