### ISSUE TITLE
[Bitbucket] "Forbidden" error starting a workspace when user does not have access to upstream (forked) repo

### ISSUE THREAD

**Issue by jmls** [gitpod-io/gitpod#9486]
### Bug description

One, and only one, of my developers cannot start a workspace on any branch on a specific repository. 

![image](https://user-images.githubusercontent.com/929523/164673487-c1307aa0-06e6-41f3-8246-3daeaf312260.png)

I thought at first that it may be some sort of permissions on the project, but no matter what we try he always gets this error. He can, however, start a workspace in gitpod for every other repository.

Verified Facts:
This user is a member of a group. This group is assigned to all repositories with "write" permission
This user can start a workspace on any other repository
This user can push changes through git to the repository that fails to start
This user is a member of a team in gitpod assigned to the project
Other members of the same team have no issues starting a workspace

Steps we've tried:
User log out of gitpod
User log out of bitbucket
User removed from group and added directly to repo
Bitbucket / gitpod integration removed and re-added for that user
Different browsers tried (firefox and edge)
Different machines tried
Starting the workspace through bitbucket and dashboard

### Steps to reproduce

try to start a workspace

### Workspace affected

all branches of a workspace

### Expected behavior

gitpod to start ;)

**Comment by jmls** [comment]
related discord conversation:

https://discord.com/channels/816244985187008514/966653206782439444

**Comment by jankeromnes** [comment]
Hi @jmls! Thank you for filing this issue. The screenshot and details you've provided will be helpful to identify exactly what's going awry here.

I'll take a look this afternoon to see if I can track down this error in Gitpod's logs/tracing.

**Comment by jankeromnes** [comment]
Some progress: This seems to be an error that happens during Bitbucket context parsing:

```json
{
    "jsonPayload": {
        "message": "Error parsing Bitbucket navigator request context",
        "error": "HTTPError: Forbidden\n    at /app/node_modules/bitbucket/lib/index.umd.js:15:6585\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
    },
    "timestamp": "2022-04-21T14:06:53.792Z"
}
```

which means the error happens _somewhere_ in here:

https://github.com/gitpod-io/gitpod/blob/2f0b9462b0451f0974434fa36bd757420ef04e34/components/server/src/bitbucket/bitbucket-context-parser.ts#L151-L210

On a side note, there seem to be other token-related others affecting the same user, which may or may not be related.

**Comment by jankeromnes** [comment]
Okay, I think I found the problem:

- Your team member does indeed have access to the repository 👍 thus Gitpod is able to fetch relevant project details from the Bitbucket API

- However, when fetching these details, it sees that this repository has a **parent repository**, and so it also tries to fetch information for the parent repository:

https://github.com/gitpod-io/gitpod/blob/2f0b9462b0451f0974434fa36bd757420ef04e34/components/server/src/bitbucket/bitbucket-context-parser.ts#L331-L342

It seems that your team member does not have write or admin access to the parent repository, which causes the API to reject Gitpod's query (with status `Forbidden`, which is what ends up being displayed in Gitpod's UI).

Conclusions:
- You can work around this problem by granting the user write or admin access to the parent repository
- Gitpod should display a much better error message when querying the Bitbucket API fails
- Maybe Gitpod should also handle cases where a user has access to a repository, but not to the parent repository, more gracefully

**Comment by jmls** [comment]
I've done a little more digging. The repo is question was *forked* from demo, and the user in question was not part of any group that had access to demo.

I'll need to do some more digging in order to figure out why the other users (who were part of the same group)  did not have the same problem.

Many thanks

**Comment by jankeromnes** [comment]
> I've done a little more digging. The repo is question was _forked_ from demo, and the user in question was not part of any group that had access to demo.

Aha, thank you for clarifying. 👍 I've updated my comment above to say "upstream" instead of "parent" (to hint at upstream/fork relationship).

Also, a few updates:

- We've scheduled this issue for team WebApp so that anyone can pick this up when there is availability

- We've decided to change how Gitpod handles access problem on upstream repos: simply ignore/log such errors and omit the fork information, instead of letting an error interrupt the workspace start process
