### ISSUE TITLE
Keyboard shortcut to toggle between terminal window and open script window

### ISSUE THREAD

**Issue by dpurser-dev** [gitpod-io/gitpod#9497]
## Is your feature request related to a problem? Please describe
No

## Describe the behaviour you'd like
Keyboard shortcut to change active window from terminal to open script (and back)

## Describe alternatives you've considered
Using the mouse

## Additional context
This would speed up execution of code

**Comment by axonasif** [comment]
Hey @dpurser-dev, this is already possible, please see https://code.visualstudio.com/docs/editor/integrated-terminal
