### ISSUE TITLE
Proxy does not include port numbers in HTTP HOST header

### ISSUE THREAD

**Issue by DanTup** [gitpod-io/gitpod#950]
Not sure if this is the right repo, but I just hit an issue in Dart that seems to be cause by the HTTP proxy not including the port number in the HTTP `HOST` header. If I fetch using `curl` or similar, the `HOST` header includes the port, and dart's `requestUri` field is populated the the correct (internal) URL. However when requesting from my browser (which does through the proxy), the `HOST` header is missing the port. This means anything that reads this value expecting the real (internal, not exposed) URL will have the port missing.

![Screenshot 2019-11-25 at 5 03 07 pm](https://user-images.githubusercontent.com/1078012/69561853-015bc280-0fa6-11ea-97ec-d64a18861a3d.png)

My understanding from [the spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23) is that the port must be included for any request where it's not the default for that scheme (and my understanding is that this should be based on the actually URL being requested from the server, and not the publicly exposed URL).

@svenefftinge

**Comment by DanTup** [comment]
Er, this also says `https://localhost/`. I'm not sure where the `https` in the `requestedUri` came from 🤔

**Comment by DanTup** [comment]
Ok, based on [this doc](https://api.flutter.dev/flutter/dart-io/HttpRequest/requestedUri.html) I think Dart is trying to reconstruct the end-users URL. The reason it comes through weird here is that the proxy is passing `x-forwarded-proto` but *not* `x-forwarded-host`. If it provided both or neither, the constructed URL would be valid (which is best, I don't know).

**Comment by geropl** [comment]
I can confirm the misbehavior. Will try to pin it down and fix it.

**Comment by geropl** [comment]
Not yet deployed.

**Comment by DanTup** [comment]
I'm not familiar with how GitPod releases - do you know approximately when the theai change (`asExternalUri`) and this would be deployed?

(I was literally just preparing a repo to be able to test them when they are :-))

**Comment by DanTup** [comment]
@geropl also - can you shed any light on what "served on localhost only, thus cannot be exposed" means? Sometimes I can expose ports and sometimes I cannot (unless they're listed in gotpod.yml). If the proxy rewrites hostnames to localhost, I don't understand why they're not supported here.

Thanks!

**Comment by geropl** [comment]
@DanTup The fix got just deployed to gitpod.io.

> can you shed any light on what "served on localhost only, thus cannot be exposed" 
We're reworking that bit (as discussed earlier) and will track progress here: https://github.com/gitpod-io/gitpod/issues/968

**Comment by DanTup** [comment]
Great, thanks! Does the deployment include newer theai code too, or is the proxy deployment separate?
