### ISSUE TITLE
[workspace] allow use of multiplatform builds

### ISSUE THREAD

**Issue by RedstoneWizard08** [gitpod-io/gitpod#9500]
## Is your feature request related to a problem? Please describe

When I try to build a multiplatform docker image, it doesn't let me because it can't run privileged containers (like tonistiigi/binfmt), and it can't launch the buildkit container to start buildx.

## Describe the behaviour you'd like

I would like the ability to run these things so I can test building multiplatform images.

## Describe alternatives you've considered

Local OpenVSCode Server: Not as good or convenient.
Codespaces: Too expensive

**Comment by axonasif** [comment]
Hey @RedstoneWizard08, I don't think this is something we can support at the moment.
Please check this thread: https://github.com/gitpod-io/gitpod/issues/7358#issuecomment-1022951368
cc @utam0k

**Comment by RedstoneWizard08** [comment]
Okay. Thanks.
