### ISSUE TITLE
[workspace] add JetBrains IDEs

### ISSUE THREAD

**Issue by RedstoneWizard08** [gitpod-io/gitpod#9502]
## Is your feature request related to a problem? Please describe

I find vscode hard to use for coding in Java.

## Describe the behaviour you'd like

I would like JetBrains IDEs to be available with the use of Projector or something similar. This would allow for better development in a lot of languages.

## Describe alternatives you've considered

None

**Comment by mteam88** [comment]
I believe it is possible to turn on different IDEs in preferences. It is still in beta though.

1. Go here: https://gitpod.io/preferences
2. Select the IDE that you want. (There is JetBrains Pycharm, but I assume you will want the Java focused IntelliJ IDEA IDE).

**Comment by axonasif** [comment]
Hey @mteam88, thanks for helping!
Closing this assuming that @RedstoneWizard08 got a potential solution.
