### ISSUE TITLE
Can't open a workspace

### ISSUE THREAD

**Issue by BrenoLopes** [gitpod-io/gitpod#952]
**Describe the bug**
When I click open in an archived workspace this happens

**To Reproduce**
This is a node workspace with some extensions, like prettier, path intellisence, etc.

**Additional Information**
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 57302581248, capacity: 57639522304

**Comment by MatyiFKBT** [comment]
![kép](https://user-images.githubusercontent.com/6183867/69658795-28d18e80-107d-11ea-99fb-b2b35a4d6979.png)
Same goes for me... can't load any of my workspaces

**Comment by MatyiFKBT** [comment]
@BrenoLopes it's working for me, you should check the status and close the issue if you can open your workspace

**Comment by geropl** [comment]
Out of date, fixed in the meantime.
