### ISSUE TITLE
ws-daemon causes excessive logging costs

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#9530]
## Is your feature request related to a problem? Please describe
ws-daemon causes excessive logging cloud costs in preview environments (three-digit EUR/day) due to excessive logging (several instances with 1MB/s).

I suspect these logs on STDERR to be the cause:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/239422/165122231-aecc3885-3be2-40c1-8a02-ea04e483de22.png">

## Describe the behaviour you'd like
ws-daemon to be quieter.

## Additional context
* Cloud monitoring: [Log Bytes ingested / Container](https://console.cloud.google.com/monitoring/metrics-explorer?project=gitpod-core-dev&pageState=%7B%22xyChart%22:%7B%22dataSets%22:%5B%7B%22timeSeriesFilter%22:%7B%22filter%22:%22metric.type%3D%5C%22logging.googleapis.com%2Fbyte_count%5C%22%20resource.type%3D%5C%22k8s_container%5C%22%22,%22minAlignmentPeriod%22:%2260s%22,%22aggregations%22:%5B%7B%22perSeriesAligner%22:%22ALIGN_RATE%22,%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22alignmentPeriod%22:%2260s%22,%22groupByFields%22:%5B%5D%7D,%7B%22crossSeriesReducer%22:%22REDUCE_NONE%22,%22alignmentPeriod%22:%2260s%22,%22groupByFields%22:%5B%5D%7D%5D,%22pickTimeSeriesFilter%22:%7B%22rankingMethod%22:%22METHOD_MEAN%22,%22numTimeSeries%22:%2210%22,%22direction%22:%22TOP%22%7D%7D,%22targetAxis%22:%22Y1%22,%22plotType%22:%22LINE%22%7D%5D,%22options%22:%7B%22mode%22:%22COLOR%22%7D,%22constantLines%22:%5B%5D,%22timeshiftDuration%22:%220s%22,%22y1Axis%22:%7B%22label%22:%22y1Axis%22,%22scale%22:%22LINEAR%22%7D%7D,%22isAutoRefresh%22:true,%22timeSelection%22:%7B%22timeRange%22:%221h%22%7D%7D).
* [Cloud Billing](https://console.cloud.google.com/billing/01C05A-85FB6F-361061/reports;timeRange=LAST_90_DAYS;products=services%2F5490-F7B7-8DF6?organizationId=327752801919&project=gitpod-core-dev)
* [Example Logs](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%3D%22ws-daemon-2wbsj%22;cursorTimestamp=2022-04-25T15:19:15Z?project=gitpod-core-dev)

**Comment by kylos101** [comment]
@meysholdt @svenefftinge this was [resolved in production when we deleted `gen41` today at 10:00am GMT](https://cloudlogging.app.goo.gl/4eumfD3WkWVT1MdG7).

At this point, @meysholdt has removed all preview environments, which may not have been rebased from main.

Therefore, the only thing that is remaining, is that folks rebase from main before deploy a preview envirionment again. I'll send a reminder to folks in Slack.
