### ISSUE TITLE
VSCODE terminals are automatically created without any visible reason

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#9531]
### Bug description

If you open a workspace, an extra terminal is always created by the `supervisor` and ide-process(on workspace-restart) with `bash` as the shell regardless of your default shell settings on VSCODE (I have `fish` as the default shell, and it does get used if I manually create a terminal)

### Steps to reproduce

Please check the video below:
https://www.loom.com/share/5beb29c3548f45dcb9431f52a1e71539

### Example repository

https://github.com/axonasif/test

### Anything else?

cc @schickling

**Comment by schickling** [comment]
Still an issue

**Comment by akosyakov** [comment]
Unfortunately it is standard behaviour from VS Code. If there is no any terminals, it adds our. And since our terminals are added by extensions which is loaded after VS Code Core there is always one new regular terminal from VS Code. I'm not sure how it can be easily improved without changing internals of VS Code.

**Comment by schickling** [comment]
While I agree that this should be addressed in VSC longer term, can this be worked around via some sort of script by Gitpod? This issue causes me to add a manual step everything before I'm able to use a project on Gitpod.

**Comment by axonasif** [comment]
@schickling currently I'm doing it via my [dotfiles](https://github.com/axonasif/dotfiles) as a workaround. You can try it if you want.

All Gitpod/IDE created `bash`(`$SHELL`) terminals get transferred into a global `tmux` session after task completion.

**Comment by schickling** [comment]
This is a very common "papercut" for me as it's a manual step when opening any workspace in Gitpod. Hopefully this gets fixed soon :)

**Comment by schickling** [comment]
Still an issue

**Comment by jeanp413** [comment]
Note: ask in vscode if terminal can wait for extension to initialize so it checks whether or not it needs to create the new terminal in the panel

**Comment by jeanp413** [comment]
I pushed a commit https://github.com/gitpod-io/openvscode-server/commit/69d257ecaeb6eadee2de335e3c45bf8f9314c3f8
@axonasif could you test it in tomorrow's insiders

**Comment by jeanp413** [comment]
Closing this for now, for now it's available in insiders, will be available in the next stable release

**Comment by schickling** [comment]
> Closing this for now, for now it's available in insiders, will be available in the next stable release

What's the rough ETA for this?

**Comment by jeanp413** [comment]
> What's the rough ETA for this?

first week of February
