### ISSUE TITLE
Allow user to configure IDE configurations when onboarding start workspace

### ISSUE THREAD

**Issue by mustard-mh** [gitpod-io/gitpod#9534]
Allow user to configure IDE configurations when onboarding start workspace.

Works for aware users Gitpod not only works with VSCode Browser. We got many IDEs.

 See also https://github.com/gitpod-io/gitpod/issues/6707, [Draft Figma](https://www.figma.com/file/1ofpgCa3XI0F4zZKhcgiGg/%236707?node-id=41%3A277)

|Draft|
|:-:|
|<img width="930" alt="image" src="https://user-images.githubusercontent.com/20944364/165144629-9bf5b513-d0d7-433b-9b82-6897f14f45a4.png">|

**Comment by gtsiolis** [comment]
In the past, we've successfully used the modal component for nudging users for new product updates or selecting an option to proceed, see https://github.com/gitpod-io/gitpod/issues/3297 and https://github.com/gitpod-io/gitpod/pull/4607.

This seems like a good use case to reuse the modal component as this could be useful also in https://github.com/gitpod-io/gitpod/issues/9534. What do you think, @mustard-mh? Cc @andreafalzetti @loujaybee 

See also [relevant discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1650993992703369?thread_ts=1650970351.290919&cid=C01KGM9BH54) (internal).

| Workspaces List | Workspace Start |
|-|-|
| <img width="1440" alt="Workspaces" src="https://user-images.githubusercontent.com/120486/165364551-925f23c8-f2bb-45c3-8ae9-f7ef5519f38a.png"> | <img width="1440" alt="Start" src="https://user-images.githubusercontent.com/120486/165364556-39455143-39dc-49a5-9c7c-e5167df36ea7.png"> |
