### ISSUE TITLE
data lost when workspace timeout and pod is in the terminating state 

### ISSUE THREAD

**Issue by jeffrey-zhang** [gitpod-io/gitpod#9544]
### Bug description

Background, we are evaluating the gitpod and deployed it in our self-hosted AKS. The current deployed gitpod version is  2202.03.01.

We encountered the issue several times that the workspace will be timeout after 30 mins by default and it can't be opened again. The serious issue is that all data is lost once this issue occurred. And we try to find the lost data in the storage account, but it seems that it isn't sync-up the data in time.

We try to check this issue in our AKS and find the pod is in the interminating state. The error message is like this from our AKS log.
![image](https://user-images.githubusercontent.com/77430590/165265700-2ace7651-3fef-4a31-b04b-a07dba8938e8.png)

### Steps to reproduce

this issue isn't always occurred. But here are the steps that occurred today. 

step1: open the gitpod from the github repo.

step2: modify the code this morning about 2h

step3: keep the gitpod opened in the browser for about 2 hours of break time
> (left office to have lunch for about 2h)

step4: find gitpod workspace is a timeout
![00001](https://user-images.githubusercontent.com/77430590/165428961-692bc798-d623-48f4-a0d7-fd74d62c7861.png)

step5: try to open the workspace again and prompt another error
![002](https://user-images.githubusercontent.com/77430590/165424268-e740e262-4bcf-4907-8812-d6a2c85e0aee.png)

step6: click workspace again. it is opened again and all data are lost.

it seems that there is a bug to sync the data to the storage account. it doesn't sync data during the workspace is active by version control so that all data are lost once the final sync-up failed when the workspace is timeout.

### Expected behavior

This issue can be fixed and this function can be worked normally. 

in addition, it is better that we can design this feature to sync the data to the storage account by scheduling for version control when the workspace is active at least. this can avoid all data being lost once the final sync-up failed when the workspace is timeout.

**Comment by dwy2002** [comment]
related error log
`
{"failed":"last backup failed: workspace timed out after backup (01h00m) took longer than 01h00m.","timeout":"workspace timed out after backup (01h00m) took longer than 01h00m","final_backup_complete":1,"stopped_by_request":1}`

but we cannot find more detail why the backup time out .

**Comment by kylos101** [comment]
Hi @jeffrey-zhang , my apologies for the delay! 

May I ask you to try with this version of the installer? I think it will help you with the evaluation.

```
docker pull eu.gcr.io/gitpod-core-dev/build/installer:9544-patch.1
```

I branched from our [April release](https://github.com/gitpod-io/gitpod/releases/tag/2022.04.1), and [cherry-picked](https://github.com/gitpod-io/gitpod/tree/9544-patch) the relevant fixes for you. Let us know?

CC: @corneliusludmann

**Comment by jeffrey-zhang** [comment]
@corneliusludmann and @kylos101 , thanks for your support. let's try it first and feedback to you later.

**Comment by kylos101** [comment]
:pray: you should be able to get the binary like so:

```shell
docker run --entrypoint sh --rm eu.gcr.io/gitpod-core-dev/build/installer:9544-patch.1 -c "cat /app/installer" > /tmp/installer
```

**Comment by neilkuantm** [comment]
hi @kylos101 ~ 

we meet another issue about got this error.

But we still click `open workspace` it can be open successful.

I think `ws-manager` has some mistakes  at check if this workspace has last backup. 

![image](https://user-images.githubusercontent.com/98370258/169761147-4b83309a-792f-4d15-b510-2e513b8afd93.png)

**Comment by kylos101** [comment]
> hi @kylos101 ~
> 
> we meet another issue about got this error.
> 
> But we still click `open workspace` it can be open successful.
> 
> I think `ws-manager` has some mistakes at check if this workspace has last backup.
> 
> ![image](https://user-images.githubusercontent.com/98370258/169761147-4b83309a-792f-4d15-b510-2e513b8afd93.png)

Hi @neilkuantm , how did you install Gitpod? Do you work with @jeffrey-zhang ?

**Comment by kylos101** [comment]
Hi @neilkuan and @jeffrey-zhang , are you still experiencing data loss on workspace timeout or [did this fix solve](https://github.com/gitpod-io/gitpod/issues/9544#issuecomment-1124611382)? Let me know? That will help us understand if we can close this issue or not.

For the [new error](https://github.com/gitpod-io/gitpod/issues/9544#issuecomment-1134787465), may I ask you both to subscribe to [this issue](https://github.com/gitpod-io/gitpod/issues/10315). We will have to do a separate fix for that issue.

**Comment by neilkuantm** [comment]
Hi @kylos101 
> Hi @neilkuan and @jeffrey-zhang , are you still experiencing data loss on workspace timeout or [did this fix solve](https://github.com/gitpod-io/gitpod/issues/9544#issuecomment-1124611382)? Let me know? That will help us understand if we can close this issue or not. 

->  I think issue had been solve by version `release 2022.04`.

> For the [new error](https://github.com/gitpod-io/gitpod/issues/9544#issuecomment-1134787465), may I ask you both to subscribe to [this issue](https://github.com/gitpod-io/gitpod/issues/10315). We will have to do a separate fix for that issue.

-> okay, thanks~

**Comment by kylos101** [comment]
Excellent! Then I shall close this issue. :wave:

**Comment by jeffrey-zhang** [comment]
@kylos101 thanks.
