### ISSUE TITLE
Evicted workspace will not open, but cannot be closed

### ISSUE THREAD

**Issue by tristpc** [gitpod-io/gitpod#955]
**Describe the bug**
The workspace https://b04d41da-cd9a-47a9-808c-079ceea71be4.ws-us02.gitpod.io has a problem. After clicking Start this message appeared:-

> Evicted: Pod The node had condition: [DiskPressure].
> Please file an issue if you think this is a bug.

It continues to run, indicating the time since starting, but does not open. It cannot be deleted either. So it may be eating up hours.

**To Reproduce**
Not known. The workspace was left running by mistake. Before leaving it unattended all was working fine in the open space. On returning it indicated it was evicted.

**Comment by tristpc** [comment]
Today it was no longer running, so I could delete it and start a new workspace.

**Comment by jankeromnes** [comment]
Thanks for the update! And sorry about that. This temporary problem seems to happen occasionally (same as #940), and we're working on adjusting our Kubernetes clusters so that it doesn't happen anymore.
