### ISSUE TITLE
no internet connection on container if network used

### ISSUE THREAD

**Issue by valyc0** [gitpod-io/gitpod#9550]
### Bug description

if I create container with network, the is no internet connection inside it. If I start the same container without network it work

### Steps to reproduce

docker run --rm --name curl pstauffer/curl:latest curl http://www.google.com

#OK!

docker network create mynet

docker run --rm --net mynet --name curl pstauffer/curl:latest curl http://www.google.com

#KO!

**Comment by majorbird-team** [comment]
Facing the same issue today, exactly as mentioned by @valyc0 .
