### ISSUE TITLE
VS Code Decorations with gutterIconPath do not work because they reference filesystem paths

### ISSUE THREAD

**Issue by DanTup** [gitpod-io/gitpod#958]
In the Flutter extension we use `getterIconPath` in Decorations to render coloured icons in the editor gutter. Because we can't do dynamic images but we don't want to ship an image for every possible hex code, we generate them the first time they're seen and write them into a folder (we use `path.join(context.globalStoragePath, "flutterColors")`). We then use a file URI for the gutter icon:

```ts
vs.window.createTextEditorDecorationType({
	gutterIconPath: vs.Uri.file(filePath),
	gutterIconSize: "50%",
});
```

However these paths are not transformed in any way when being rendered in GitPod, so they don't show up and you see these errors in the dev console:

![Screenshot 2019-11-28 at 2 44 47 pm](https://user-images.githubusercontent.com/1078012/69815172-b0d6a600-11ed-11ea-9d52-6f4d2c505caf.png)

I don't know if this belongs in GitPod of theia, but I think `gutterIconPaths` should be transformed to some URL that is able to pass through files (at least those that have been explicitly added as `gutterIconPath`s or similar).

**Comment by geropl** [comment]
@akosyakov Can maybe you can help here?

**Comment by akosyakov** [comment]
I think we have to translate file paths to urls to fetch files from our endpoints.

**Comment by svenefftinge** [comment]
In production now

**Comment by DanTup** [comment]
The fix seems to work for some (our colours) but not others (icons). I think the difference is that one comes from the extensions `globalStorage` whereas the other one comes from the extensions own folder (eg. shipped inside the extension - `extensions.getExtension(dartCodeExtensionIdentifier)!.extensionPath`).

**Comment by DanTup** [comment]
If you need a test case, you can use this:

```
vscode:
  extensions:
    - Dart-Code.dart-code@3.7.0-beta.1:/xEXAh68CXrAM+0euRznVA==
```

Or the vsix from:

https://github.com/Dart-Code/Dart-Code/releases/tag/v3.7.0-beta.2

And there's an example repo here (you'll need to click "Get Packages" on the notification that pops up):

https://gitpod.io/#https://github.com/DanTup/gitpod-flutter-web

The colours are already in the file, and you can trigger the icon by including this in `lib/main.dart`:

```dart
var a = Icons.ac_unit;
```
