### ISSUE TITLE
[Python] 'Rename Symbol' renames the wrong symbol(!)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#959]
**Describe the bug**

When I try to rename a variable called `buttons`, Gitpod actually renames another variable 2 lines below!

Screencast: https://youtu.be/8U2OrpKjHQc

**To Reproduce**

1. https://gitpod.io/#https://github.com/techwithtim/Hangman
2. Open `hangman.py`
3. Click on the `buttons` variable, and press `F2` to rename it

**Expected behavior**

The variable `buttons` should be renamed. However, often it's another variable that gets renamed.

**Comment by AlexTugarev** [comment]
we should disable `jedi` by default: `"python.jediEnabled": false`

**Comment by jankeromnes** [comment]
Additional note: this `"python.jediEnabled": false` should be added to your preferences, e.g. by going to `File` > `Settings` > `Open Preferences`, and entering that line into your User Preferences (which is a JSON file).
