### ISSUE TITLE
Project environment variables not showing up

### ISSUE THREAD

**Issue by zpthree** [gitpod-io/gitpod#9591]
Are project environment variables not accessible in the same way that regular environment variables are? I set up a bunch of project environment variables and made them visible in workspaces but they are not showing up with my other variables.

_Originally posted by @zpthree in https://github.com/gitpod-io/gitpod/issues/7860#issuecomment-1110363950_

**Comment by axonasif** [comment]
Hey @zpthree, from where are you trying to access them?

**Comment by zpthree** [comment]
@axonasif Trying to access them in the before and command tasks. I don't now if they're showing up in the before task or not because I switched over to use the automatic .dotfiles directory but that doesn't  seem to be available in the before command.

If I try to access them from the workspace (command line) they're not there, even with Visibility in Workspaces set to Visible.

**Comment by jldec** [comment]
Can't repro this. Project env var is visible in all tasks and terminal

https://github.com/jldec/readme/pull/3/files 

<img width="1049" alt="Screenshot 2022-08-17 at 12 43 26" src="https://user-images.githubusercontent.com/849592/185110298-30c381b8-1f38-4bd0-8b41-d5a18ef1a175.png">

<img width="1134" alt="Screenshot 2022-08-17 at 12 45 10" src="https://user-images.githubusercontent.com/849592/185110619-ebc50686-c0d9-4650-bce7-defee5256593.png">

**Comment by ivelin** [comment]
I am bumping into this issue. Not sure if it was ever resolved. The thread shows it was closed as stale.
`gp env` shows all account level variables, but not the project settings variables. Here is the space I'm working with:
https://ivelin-canswim-o381n5rcbok.ws-us108.gitpod.io/

**Comment by axonasif** [comment]
Hi @ivelin, I couldn't find a project associated with the workspace your shared. Please create a support ticket from here so I can help you: https://www.gitpod.io/contact/support
