### ISSUE TITLE
Run integration tests nightly against main for workspace components

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#9597]
## Is your feature request related to a problem? Please describe
Run integration tests nightly against main for workspace components to make sure the latest main branch does not break the quality.

## Describe the behaviour you'd like
Run integration tests nightly against main for workspace components by werft job `with-vm` running on preview environment, after the job finish, send a slack notification to the team workspace slack channel.

## Describe alternatives you've considered

We could consider running integration per PR if the code change is related to workspace team components.

**Comment by jenting** [comment]
There is no werft deployed/installed in the preview environment, we can't run the integration test job which is deploying/running by the werft. That is, now we could only run the nightly integration test on the `core-dev` environment.

Besides that, sending the Slack notification to the workspace team slack channel might pollute the channel and I see the IDE team post the integration test result to channel #ide-jobs, I think we could create a new channel #workspace-jobs rather than using the existing #t_workspace, WDYT?

cc @kylos101

**Comment by kylos101** [comment]
`core-dev` is going away at some point, to be replaced by Hertzner. 

I believe when core-dev is gone, that main's preview environment should be generated by Hertzner. Can you ask Platform team what the plan is, for the main branch's preview environment? I hope it is Hertzner, but good to confirm.

#workspace-jobs is a good idea. :+1: We were talking about doing something similar for Front messages recently.
