### ISSUE TITLE
[self-hosted] Cannot use SCM (like GitLab) with a self-signed TLS cert

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#9604]
With the April release, we support certificates that are signed by custom CA certs (self-signed TLS certs). However, creating a workspace from code of an SCM (GitLab, GitHub, Bitbucket) with a self-signed TLS cert does not work yet.

```
cannot initialize workspace: cannot initialize workspace: git initializer: git clone --depth=1 --no-single-branch https://gitlab.tarun.gitpod-self-hosted.com/gitlab-instance-e8e6c7ee/Monitoring.git . failed (exit status 128): Cloning into '.'... fatal: unable to access 'https://gitlab.tarun.gitpod-self-hosted.com/gitlab-instance-e8e6c7ee/Monitoring.git/': SSL certificate problem: unable to get local issuer certificate
```

The error happens in the ws-daemon pod, specifically in the runc container used by ws-daemon to initialise the workspace content.

Possible solution:
```
git config --global http.sslCAInfo /path/to/ca
```

Internal discussion: https://gitpod.slack.com/archives/C01KLC56NP7/p1651035073540809

**Comment by csweichel** [comment]
PR is in the works
