### ISSUE TITLE
Gitpod dashboard messes with website SEO

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#9607]
### Bug description

As reported [on Twitter](https://twitter.com/codepawn/status/1519579376882524161) (thanks Michel!), Gitpod's dashboard is now the first result you get when you [search "gitpod" on Google](https://www.google.com/search?q=gitpod):

<img width="955" alt="Screenshot 2022-04-28 at 09 49 00" src="https://user-images.githubusercontent.com/599268/165704077-bfd63795-c429-48d2-b038-994a47afa728.png">

And unfortunately, the dashboard landing page is not SEO-optimized at all (see "You need to enable JavaScript to run this app.")

This is not a good SEO situation for Gitpod.

### Steps to reproduce

1. [Search for "gitpod" on Google](https://www.google.com/search?q=gitpod)

### Expected behavior

We have two options to fix this:

1. Fix the SEO of Gitpod's dashboard, and align things like title, description, etc. with the Gitpod website

2. Prevent the Google Search crawler from indexing the dashboard at all (might a bit heavy-handed, as some pages might actually be relevant for searches like "manage Gitpod environment variables" -- however, we could decide that we only want users to find documentation pages, and not the app pages)

**Comment by jankeromnes** [comment]
Update: We've decided to go with 2:

> 2. Prevent the Google Search crawler from indexing the dashboard at all

> At least today it makes sense as we don't have any public pages in dashboard yet.

Source: [Slack (internal)](https://gitpod.slack.com/archives/C02EN94AEPL/p1651135687524419?thread_ts=1651133047.433819&cid=C02EN94AEPL)

**Comment by jankeromnes** [comment]
I think this is a quick fix. Jumping on it as a quick break from #8041 😛

**Comment by geropl** [comment]
@jankeromnes Once done, please check with the other [seo issues](https://github.com/gitpod-io/gitpod/issues?q=is%3Aissue+is%3Aopen+label%3Aseo) and close/adjust if there is an overlap. :pray:

**Comment by jankeromnes** [comment]
> @jankeromnes Once done, please check with the other [seo issues](https://github.com/gitpod-io/gitpod/issues?q=is%3Aissue+is%3Aopen+label%3Aseo) and close/adjust if there is an overlap. 🙏

Good idea! Done ✅

**Comment by geropl** [comment]
Still seems to be the case, see [slack](https://gitpod.slack.com/archives/C01KGM9ETU6/p1652422933278919?thread_ts=1651131209.453549&cid=C01KGM9ETU6).

**Comment by jankeromnes** [comment]
I believe this is now resolved (at least in private browsing / when logged out) 🎉 :

<img width="500" alt="Screenshot 2022-05-23 at 08 16 36" src="https://user-images.githubusercontent.com/599268/169755422-a5815141-03bd-4c4e-bdea-4c3b95fec8f2.png">

(Although, for my logged in session, Google still gives the dashboard as first result -- maybe because I've visited that result before -- but now without a description 🙄 looking forward to this being fixed as well:

| First result has no description | When you click on "why" |
| --- | --- |
| <img width="518" alt="Screenshot 2022-05-23 at 08 16 19" src="https://user-images.githubusercontent.com/599268/169755563-f12ba09d-12e9-452b-81fc-6d7414d742cc.png"> | <img width="849" alt="Screenshot 2022-05-23 at 08 16 07" src="https://user-images.githubusercontent.com/599268/169755605-a5cf334a-ac56-4a43-918f-96821be71f34.png"> |

)
