### ISSUE TITLE
Running Tests in a (headless) Browser in Gitpod

### ISSUE THREAD

**Issue by madoar** [gitpod-io/gitpod#962]
I'm trying to get the tests of one of my projects to work in gitpod.
Because the project is written with angular (typescript) I need to use a webbrowser to process the tests. So I thought about using `gitpod/workspace-firefox`, but this container does not seem to set `firefox` for terminal/command line usage. Do you have any hints how to execute get a (headless) browser working in gitpod?

My experimenting branch/PR can be found at https://github.com/madoar/angular-archwizard/pull/245/files

**Comment by jankeromnes** [comment]
Hi @madoar,

- `gitpod/workspace-firefox` is a development environment for compiling projects like Firefox, Servo, Thunderbird etc (so it's not really meant for running headless tests)
- to run your tests, you can either use a headless Chrome, or base your workspace image on `gitpod/workspace-full-vnc` to get a Virtual Desktop (then you can install any browser and run it graphically)

I'll try to find some helpful example configurations for inspiration.

**Comment by madoar** [comment]
Sorry for my late answer.

Yes this is basically what I did in the meantime too. I have no issue with installing a browser separately using a dockerfile but I think it would be useful to provide an image that does this out of the box. It would also be useful if the `--no-sandbox` hack for karma would not be needed. I know that you mention  [here](https://www.gitpod.io/blog/gitpodify/#no-usable-sandbox) that gitpod provides no usable sandbox, but I believe this to be strange because travis for example does not require these settings.
