### ISSUE TITLE
Workspace stopping while I'm working with it

### ISSUE THREAD

**Issue by michaelcollabai** [gitpod-io/gitpod#9629]
### Bug description

This is one example for an issue I've seen a couple of times this week. 
I'm working with VS Code Desktop on a workspace and at some point notice that my files aren't saving anymore. The gitpod.io tab sill shows the workspace as running, but when I refresh after a while the workspace is "Stopping". It usually stays in that state far longer than if I stop the workspace myself.
After a while the workspace is stopped, I can restart it and everything works again.

### Steps to reproduce

Don't know if there any specific actions that trigger it, but it has happened ~once a day this week

### Workspace affected

collabai-collabai-po75ubar8fj

**Comment by jkaye2012** [comment]
Note that when this happens, the Pod says it timed out:

![image](https://user-images.githubusercontent.com/4085244/174086326-bb1d4fc8-6568-4b2c-a094-6d1dcd6040c1.png)

But I made changes to this Pod approximately two minutes before it stopped itself.

**Comment by jkaye2012** [comment]
Pod id: belvederetrading-tribe-e8owwqr3eju

**Comment by jkaye2012** [comment]
Is anyone looking at this? I don't think it's been resolved.

**Comment by atduarte** [comment]
@jkaye2012 sorry for taking so long to get to this.

@loujaybee @akosyakov could it be related with IDE integration or heart beating? Doesn't seem workspace related.

**Comment by jkaye2012** [comment]
They are shared above - that's all the information I have unfortunately (considering this was two months ago)

**Comment by akosyakov** [comment]
We reworked heartbeating in July [[1](https://github.com/gitpod-io/gitpod-vscode-desktop/commit/39353b7f0834fe46d6e78d7049049f8d6453ce2b)] for VS Code Desktop. Do you have issues now?

**Comment by jkaye2012** [comment]
I don't think I've had any issues this week. The original issue was in September, so well after that rework.

**Comment by Mosaab-Emam** [comment]
This is happening to me right now, its so frequent that it occurs at least once an hour!

**Comment by jkaye2012** [comment]
Definitely still happening, I just had a pod close after less than 10 minutes after opening

**Comment by akosyakov** [comment]
Any additional info would be helpful, at least workspace id and time stamp.

**Comment by jkaye2012** [comment]
Sure:

workspace id: belvederetrading-tribe-1dlbhi0lnj9
time: started around 7:59am Mountain time, stopped around 8:08am

**Comment by kendallroth** [comment]
Experiencing consistent timeouts within minutes of opening (or creating) a workspace. I nuked my workspaces in an attempt to fix (and do not have their IDs) but do have the ID of the currently broken one: `lims-lims-zevlyz86ynx` (not sure how to get timestamp).

**Comment by Phxntxm** [comment]
Hopefully more evidence'll help... I don't have exact timestamps for mine because it was in the past, but approximate:

Workspace ID: `lims-lims-o0z0c1hehgc`
Timeout times: 
- Around 6:32 PST about 5 minutes after it started
- Around 6:45 PST just about 2 minutes after it started
- Around 7:59 PST... this one wasn't right after it started, but timeout is supposed to be "from last working in it" right? In which case I had just stopped working in it 9 minutes prior


Unsure if it's relevant, since it seems to be the same EFFECT as originally submitted, but we've been experiencing this issue for months, just not that frequently. Today has been MUCH MUCH more frequent though. Could be the same effect but a different cause though :shrug:

**Comment by jacobparis** [comment]
I'm hitting this today and yesterday fairly often, `jacobparis-monorepo-lz1ac5j37xf` in eu90

**Comment by Foxhoundn** [comment]
Happened twice in the past hour literally while typing - nothing abnormal to report :)

**Comment by Assaf1978-boop** [comment]
I'd like,that!

**Comment by loujaybee** [comment]
Thank you all for the reports and information. 

We are tracking the investigation on the status page: https://www.gitpodstatus.com/incidents/pgvc69gq5p1n

**Comment by loujaybee** [comment]
> In case it helps debugging, the issue does not occur to me if I leave the browser tab open. If I close the browser tab, my workspace closes almost immediately (within 5 minutes generally)

This is expected behaviour, closing a client will trigger the workspace timeout to close after 5 minutes, _unless_ you have set an explicit (non default) custom timeout via `gp timeout set` or in the user preferences. 

https://www.gitpod.io/docs/configure/workspaces/workspace-lifecycle#editor-disconnect

**Comment by akosyakov** [comment]
Could you try to downgrade to 0.0.80 and see whether it fixes the issue?

**Comment by jkaye2012** [comment]
@loujaybee this is decidedly _not_ expected behavior from your users, and is not how GitPod has been working for months.

If VSCode is open, closing a browser tab should absolutely not close the workspace. If it does, this is a bug.

**Comment by jacobparis** [comment]
For what it's worth, I am also experiencing the issue while running the workspace in VS Code Desktop

**Comment by loujaybee** [comment]
> In case it helps debugging, the issue does not occur to me if I leave the browser tab open. If I close the browser tab, my workspace closes almost immediately (within 5 minutes generally) - @jkaye2012 

> @loujaybee this is decidedly not expected behaviour from your users, and is not how GitPod has been working for months. If VSCode is open, closing a browser tab should absolutely not close the workspace. If it does, this is a bug - @jkaye2012 

Apologies for the confusion, I think we could be talking about two topics. The 5 minute editor disconnecting timeout has been in place for quite some time, e.g. see conversations from last year to extend it from 2 to 5 minutes: https://github.com/gitpod-io/gitpod/issues/10373, and [docs on the behaviours](https://www.gitpod.io/docs/configure/workspaces/workspace-lifecycle#workspace-timeouts). For what it's worth, that functionality is being discussed to move to being user configurable (as it is not, currently): https://github.com/gitpod-io/gitpod/issues/16089. However, for the reports above of unexpected closing workspaces, the team are actively investigating currently right now, I hope I can get back to you soon when we have more information. 🙏

**Comment by akosyakov** [comment]
@jacobparis Could you share logs as described in https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop? 🙏

**Comment by jkaye2012** [comment]
@loujaybee I think there may be some confusion here. This is the workflow that has been working since last July:

1. Open GitPod in browser
2. Click "Open in VS Code" from browser
3. Click "Trust Authors" in VS Code
4. Close browser tab

This has never closed the workspace after 5 minutes before today. It is a regression.

**Comment by akosyakov** [comment]
@jkaye2012 Could you share logs according to https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop? and try also downgrade to 0.80

**Comment by sansari** [comment]
I'm experiencing the same issues as @jkaye2012. The workspace suddenly times out after a few minutes, even with active usage. This is a new issue that started today (haven't experienced this in the last 4-5 months of Gitpod usage.)

**Comment by jeanp413** [comment]
@sansari could you try downgrading to version `0.0.80` and check if you still can repro

**Comment by loujaybee** [comment]
> Monitoring - We have reverted an update for the Gitpod VS Code Desktop extension and released as a new version. If you are experiencing issues, please update your Gitpod VS Code Desktop extension to version: 0.0.84.

https://www.gitpodstatus.com/incidents/pgvc69gq5p1n

**Comment by epompeii** [comment]
This is continuing to happen to me @loujaybee . Would you suggest I open a new issue.

**Comment by Assaf1978-boop** [comment]
Nice.

**Comment by jkaye2012** [comment]
This is still happening as well: https://github.com/gitpod-io/gitpod/issues/9629#issuecomment-1468476611

**Comment by mustard-mh** [comment]
@epompeii @Assaf1978-boop @jkaye2012 Could you share your workspaceID and gitpod vscode extension version ? 🙏

**Comment by jkaye2012** [comment]
belvederetrading-tribe-5vy6yu86g3i

My experience was yesterday - I'm not 100% sure which version I was on at the time

**Comment by mustard-mh** [comment]
> I've been using this workspace: bencherdev-bencher-qea4vq8ub8b
> 
> My GitPod plugin version is: v0.0.87

@epompeii I checked that your current workspace is working well. Telemetry shows nothing with your previous workspace instance 😞 Maybe this telemetry problem is related to the network. 

We will appreciate if you could [`Export all Logs`](https://www.gitpod.io/docs/help/troubleshooting#gitpod-logs-in-vs-code-browser-and-desktop) and send it to us (troubleshooting@gitpod.io) next you hit it, to help debug with it 🙏

**Comment by kylos101** [comment]
:wave: hey there, we're rolling out a new generation of clusters in EU and US regions that should help resolve this issue. If you start a workspace on cluster `us91` or `eu91` and continue to experience this issue, let us know? :pray:

**Comment by sansari** [comment]
Hi @loujaybee, this issue just started happening again this morning (i.e. I open a workspace, start working with it in VS Code desktop, and then it times out **while I'm using it**). My coworkers on the same team are having the same issue.

The Gitpod extension in VS Code shows v0.0.93, so it seems well ahead of the recommended upgrade version to fix the issue.

**Comment by jeanp413** [comment]
Hi @sansari, sorry we we running some experiments as we weren't sure about the root cause last time, just released a new version `0.0.94` please update again :pray: 
Let me know if that doesn't solve it

**Comment by Assaf1978-boop** [comment]
General .

**Comment by kylos101** [comment]
:wave: @laushinka @jeanp413 I removed workspace team for now, let us know if you need to readd?

**Comment by lilnasy** [comment]
I've been running into this issue consistently, most recently in us98. I ssh into my workspaces and I have a 6h timeout set, but it stops anywhere from 5-25 minutes since starting.

**Comment by Assaf1978-boop** [comment]
Seems,nice!

**Comment by akosyakov** [comment]
@lilnasy @Assaf1978-boop Which version of Gitpod extension do you have running? Please update to the latest and try again.

**Comment by Assaf1978-boop** [comment]
Proggarming.-and,Computing.נשלח מה-iPhone שלי‫ב-5 ביוני 2023, בשעה 8:53, ‏‏Anton Kosyakov ***@***.***> כתב/ה:‬﻿
@lilnasy @Assaf1978-boop Which version of Gitpod extension do you have running? Please update to the latest and try again.

**Comment by lilnasy** [comment]
@akosyakov I am not using the gitpod extension or VSCode at all.  I ssh in and work using a terminal editor.

**Comment by akosyakov** [comment]
Thank you for the clarification, @lilnasy. It's helpful to know that SSH connections are only kept alive for pty sessions and that the [editor timeout](https://www.gitpod.io/docs/configure/workspaces/workspace-lifecycle#editor-or-ide-disconnect) can come into play under certain circumstances. If the editor timeout is causing problems, you can disable it by extending the inactivity timeout as described in this [section](https://www.gitpod.io/docs/configure/workspaces/workspace-lifecycle#extend-inactivity-timeouts) of the Gitpod documentation.

If you're comfortable with it, could you please share the workspace/instance IDs that you've been having issues with? You can find these by running the `gp info` command in your workspace or by checking the workspace URL.

With these IDs, I can look more closely at the specifics of what might be going wrong with your SSH connections.

**Comment by Assaf1978-boop** [comment]
The regular,version.נשלח מה-iPhone שלי‫ב-22 במאי 2024, בשעה 18:27, ‏‏github-actions[bot] ***@***.***> כתב/ה:‬﻿
Closed #9629 as not planned.

**Comment by Assaf1978-boop** [comment]
Hp.נשלח מה-iPhone שלי‫ב-5 ביוני 2023, בשעה 14:03, ‏‏Assaf Rosen ***@***.***> כתב/ה:‬﻿Proggarming.-and,Computing.נשלח מה-iPhone שלי‫ב-5 ביוני 2023, בשעה 8:53, ‏‏Anton Kosyakov ***@***.***> כתב/ה:‬﻿
@lilnasy @Assaf1978-boop Which version of Gitpod extension do you have running? Please update to the latest and try again.
