### ISSUE TITLE
Allow setting custom workspace `hostname`

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#9632]
## Is your feature request related to a problem? Please describe

It would be nice if one could specify what their workspace Linux `hostname` can be.

## Describe the behaviour you'd like

Configure `hostname` from `.gitpod.yml`

## Additional context

A user asked here internally: [frontapp](https://app.frontapp.com/open/cnv_j5aa2x6)

**Comment by geropl** [comment]
@axonasif Could you add more detail as to what's the motivation for this feature? :thinking: Is it about locally adjusting the hostname, or more about controlling a public DNS record? :thinking:

**Comment by axonasif** [comment]
@geropl it's about altering the linux hostname, I tried to do this as an experiment (also mentioned in the frontapp link above) 🙏 
https://github.com/axonasif/test/blob/test_hostname_change/.gitpod.yml
