### ISSUE TITLE
Abuse prevention: Ability to block workspaces by repository

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#9639]
We saw a lot of (unintentional?) abuse over the last two weeks, mainly induced by [this repository](https://github.com/h0nde/roblox-claimable-group-finder).

In general it would be nice to be able to quickly respond to abuse/performance issues by (temporarily) blocking certain repositories.

**Comment by jldec** [comment]
scheduled

**Comment by AlexTugarev** [comment]
Taking it from here.
