### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by Zartek-Technologies** [gitpod-io/gitpod#964]

**Comment by JesterOrNot** [comment]
see #114

**Comment by JesterOrNot** [comment]
![image](https://user-images.githubusercontent.com/50386709/69975822-86d2fb80-14ed-11ea-9e07-fe196dbbbb13.png)
nvm I see

**Comment by JesterOrNot** [comment]
@svenefftinge flutter broke
![image](https://user-images.githubusercontent.com/50386709/69975864-9f431600-14ed-11ea-9c5a-543b949d8a81.png)
![image](https://user-images.githubusercontent.com/50386709/69975916-bf72d500-14ed-11ea-908e-b89c6df100f3.png)

**Comment by hpssjellis** [comment]
I just found this out with my own version of flutter. My version is installing flutter but having troubles with the android sdk. Any ideas about what is happening?

**Comment by geropl** [comment]
I think we use the `master` branch of the flutter sdk which breaks dependencies sometimes.

**Comment by Kreyren** [comment]
Still relevant?
