### ISSUE TITLE
Remote ports 25 and 587 can't be reached

### ISSUE THREAD

**Issue by isontheline** [gitpod-io/gitpod#965]
**Describe the bug**
Hello Gitpod Team !
Since a few days Remote ports 25 and 587 can't be reached.
Perhaps it's for spamming reasons but I can't work anymore :(

**To Reproduce**
Port 25 isn't reachable :
(echo > /dev/tcp/email-smtp.us-east-1.amazonaws.com/25) >/dev/null 2>&1     && echo "It's up" || echo "It's down"

Port 587 isn't reachable :
(echo > /dev/tcp/email-smtp.us-east-1.amazonaws.com/587) >/dev/null 2>&1     && echo "It's up" || echo "It's down"

**Expected behavior**
Ports 25 and 587 must be reachable in order to do my work.

**Additional Information**
Amazon SES SMTP server is working outside Gitpod.io infrastructure :
https://mxtoolbox.com/SuperTool.aspx?action=smtp:email-smtp.us-east-1.amazonaws.com&newAppVersion=1

Have a nice day :)

Best Regards,

**Comment by meysholdt** [comment]
hi @isontheline!

yes, indeed we recently started blocking port 587 to prevent spammers from using it. 
Port 25 was never open, because it's blocked by default in Google Cloud Platform. 

Can you share with us why you would like to send emails?

**Comment by isontheline** [comment]
Hi @meysholdt 

I "need" to send emails because :
- I don't SPAM
- I pay each month Gitpod.io

I use Amazon SES and pay each email out so I never SPAM. My application need to send emails in order to create account, ask for passord reset, etc. I need to be able to do that even on development on Gitpod.io in order to be sure that production release will work.

I know some people spam, but Gitpod.io haven't send any email to their customers. I have lost a lot of hours to understand the new policy applied by Gitpod.io

I know that I can change the way to access AWS SES by using https requests, but Gitpod.io will perhaps or not block 443 port in a few weeks...

I'm disappointed as paid user.

**Comment by whitetigle** [comment]
Hi @meysholdt, I've go the same needs with smtps/465. 

I'm currently migrating my projects to gitpod and I've got several projects sending emails for internal/alerting systems. 

If I gave you a list, would it be possible to open ports for these specific projects? 
Thanks!

**Comment by isontheline** [comment]
@whitetigle The only way I have found is to use an email provider which allow you to send emails through HTTPs (like AWS).

**Comment by Kreyren** [comment]
I guess there should be some flag that can be added in `.gitpod.yml` that would be granted to trusted users to test these functionalities assuming that it's needed for a development and to prevent gitpod from being used for mass-spam.

**Comment by whitetigle** [comment]
Thanks!
It would be really cool since using any send email through http providers is a no-go.
Also I would be ok to sign any legal agreement against using these projects for spamming.

**Comment by Kreyren** [comment]
> Also I would be ok to sign any legal agreement against using these projects for spamming.

I think Terms of Service should be enough for that, depends on @meysholdt though (i would be willing to propose changes to Terms Of Service if that's helpful)

**Comment by Kreyren** [comment]
Also i guess these ports are required for submitting git patches through the email for repositories that requires these alike https://sr.ht

assigned Moritz since it's his decision to make (i believe)

**Comment by MrEisbaer** [comment]
Hey any updates on this? We are developing modules for an erp system and have to change mail templates etc for our customers. The only way to test custom-templates is to sending mails to us on the port 465 =/

**Comment by wulfthimm** [comment]
Unfortunately, we cannot support the forwarding of the SMTP standard port.

**Comment by jayhale** [comment]
Has this been reconsidered since 2020?

It seems reasonable that paid users would have control over outgoing networking, given app development almost always depends on external services.

**Comment by antcooper** [comment]
+1

I would like a way to send emails from a Gitpod environment. I use it for building websites (LAMP stack) and for some ecommerce projects need to be able to test transactional emails for order confirmation, forgotten password etc. Thanks

**Comment by ericklima-ca** [comment]
+1
I would also like a way to send emails from a Gitpod environment.

**Comment by codewithpom** [comment]
+1
I would also like a way to send emails from a Gitpod environment.

**Comment by b83s** [comment]
If you need to test your email you can use Mailhog.

docker run --restart always -d --name=mailhog -p 1025:1025 -p 8025:8025 mailhog/mailhog

SMTP localhost: 1025  

And the interface with all send email is on port 8025

**Comment by AklavyaXira** [comment]
> Has this been reconsidered since 2020?
> 
> It seems reasonable that paid users would have control over outgoing networking, given app development almost always depends on external services.

Like is there any way for new developer to send email via gipod port 587
