### ISSUE TITLE
[werft]: jobs fail often during "Flushing telemetry before stopping job"

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#9659]
### Bug description

Refer to [this build](https://werft.gitpod-dev.com/job/gitpod-build-main.3082) for an example. The build job fails often here. 

The [preview environment](https://main.staging.gitpod-dev.com/workspaces) for main is alive "now" (9 minutes after the build was done), therefore I'm not sure that this was an actual failure.

I ask because if this is not real breakage, we should fix the werft job, so that it doesn't look failed. Otherwise I feel folks might be less likely to respond to actual main build failures.

### Steps to reproduce

Not sure

### Expected behavior

Depends if this is an actual failure or not.

If its not really a failure, I'd argue it should exit with a zero status, so the job appears to have succeeded.

### Example repository

This one

### Anything else?

Thank yous!

**Comment by meysholdt** [comment]
([mention in Slack](https://gitpod.slack.com/archives/C01KGM9EBD4/p1651250691079339))

**Comment by mads-hartmann** [comment]
@kylos101 Thanks for the report Kyle. I have opened a PR that fixes a few things related to this, please see the PR for details https://github.com/gitpod-io/gitpod/pull/9837
