### ISSUE TITLE
Testing runtime of sw on gitpod?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#966]
### Context
I'm currently maintaining a fork of bedrock linux on https://github.com/Kreyrock/Kreyrock where i want to use gitpod for development to test runtime (basically the ability to break gitpod's dedicated system and restore it on demand)

### Issue
Afaik this is currently difficult to do since gitpod does not provide a root permission (basically making it useless for everything related to linux development)

Is there some way to adapt this workflow?

### References
- Tracking for root priviliges https://github.com/gitpod-io/gitpod/issues/39 (ignored for almost 2 years now)

**Comment by jankeromnes** [comment]
Hi @Kreyren, this sounds a bit tricky to achieve in a containerized development environment, but you _can_ use `sudo` & root privileges at Docker build time, i.e. in your `.gitpod.Dockerfile` (you can run `gp init` to generate stub config files).

Also, I'd love to get the ball rolling on allowing `sudo` inside containers. The team is still worried about potential container escapes or other vulnerabilities facilitated by `sudo`, but I believe that Docker's capabilities model makes enabling `sudo` safe enough today.

However, I don't have an authoritative source that says "today it's safe enough to allow `sudo` in containers", so I can't prove my point. Do you have such a reference, by any chance?

**Comment by Kreyren** [comment]
@jankeromnes sorry for the delay

> The team is still worried about potential container escapes or other vulnerabilities facilitated by `sudo`

Can you provide more info to the concerns so that they can be addressed? 

Disclaimer: i'm not familiar with your system to suggest anything valuable since it's closed-source afaik

If escaping the docker is a concern i would go step further and make sure that the system running the docker images is useless for any kind of abuse alike sandboxing it to a limited environment or LFS with bare minimum toolchain needed to run docker (i.e system without root, kernel built with bare minimum, etc..) assuming that docker doesn't need much for it's runtime afaik.

> this sounds a bit tricky to achieve in a containerized development environment, but you can use sudo & root privileges in Gitpod at Docker-build time,

Could you provide more info so that i'm not introducing an open-door by making workarounds to get root access assuming provided concerns?

**Comment by Kreyren** [comment]
Duplicate of https://github.com/gitpod-io/gitpod/issues/1265
