### ISSUE TITLE
`NetworkIsReachableProbe` for `registry` has hard-coded `http` protocol and fails if registry is not listening on port 80

### ISSUE THREAD

**Issue by corneliusludmann** [gitpod-io/gitpod#9660]
`registry-facade` [[1](https://github.com/gitpod-io/gitpod/blob/811be9b72c288e3770cf1d90eb8b20ec39103edd/components/registry-facade/cmd/run.go#L134), [2](https://github.com/gitpod-io/gitpod/blob/811be9b72c288e3770cf1d90eb8b20ec39103edd/components/registry-facade/cmd/run.go#L138)] and `blobserve` [[3](https://github.com/gitpod-io/gitpod/blob/97bdaa6498529c2cce24e7c348db8df926149c49/components/blobserve/cmd/run.go#L130)]. have readiness checks hardcoded with http protocol, e.g.:
```
health.AddReadinessCheck("registry", kubernetes.NetworkIsReachableProbe(fmt.Sprintf("http://%v", staticLayerRef)))
```

However, when the registry listens on port 443 only or the user specified a custom port in the Gitpod config like this:
```
repository: registry-1.testing.gitpod-self-hosted.com:5000/gitpod
```

The check fails because there is nothing listening on port 80 or the registry on the custom port speaks https only. The checks fail and the `registy-facade` would not start and would logs messages like this:
```
unexpected error checking URL http://registry-1.testing.gitpod-self-hosted.com/gitpod/supervisor:commit-2a82d5e93851dfddb79c28859509687da1858e33: Get \"http://registry-1.testing.gitpod-self-hosted.com/gitpod/supervisor:commit-2a82d5e93851dfddb79c28859509687da1858e33\": dial tcp 34.89.239.41:80: connect: connection refused
```

or 

```
NetworkIsReachableProbe: unexpected status code checking URL
```

([internal discussion](https://gitpod.slack.com/archives/C02F19UUW6S/p1651258680754529))

**Comment by corneliusludmann** [comment]
Hi @AllMight2099! Thank you very much for the initiative. Appreciate this!

Unfortunately, this has been fixed already by https://github.com/gitpod-io/gitpod/pull/9727 (sorry that we haven't closed this issue).

Are you interested in contributing something else? If you're interested, I'd be happy to help you to find another suitable issue.

**Comment by AllMight2099** [comment]
Oh, that's alright!
And yessssss! I would love to have your guidance. I want to work on Gitpod's infrastructure so I was thinking of picking up issues #9274 and #8021 cause it seems like it would give me a good opportunity to go through Gitpod's code. Would you recommend I take these issues up? Or are there other issues that you'd suggest I work on?  Also, there's another link to an internal discussion for issue #8021, which I'd like to get access to, if that's possible
