### ISSUE TITLE
[GitHub] List Forks is broken

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#967]
**Describe the bug**

I'm unable to make a new pull request in my repository using gitpod:
![image](https://user-images.githubusercontent.com/11302521/70050626-b9552500-15cf-11ea-8e50-d4e3b0a4001f.png)

The 'fork selector' just loads forever and it seems that it shows only the newest fork as an option instead of expected repository (https://github.com/gitpod-io/gitpod/issues/967#issuecomment-561282361)

**To Reproduce**

- Get any firefox from debian's release
- Fork https://github.com/bedrocklinux/bedrocklinux-userland
- Open a gitpod from that repository
- Try to make a new commit in master branch (expect failure, loads forever)

**Expected behavior**

Expecting to be able to make a commits from gitpod to the master branch of my repo

**Additional Information**

```
Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
```

Video of the issue: https://www.youtube.com/watch?v=NnRo7pbVN54&feature=youtu.be

**Comment by jankeromnes** [comment]
Seems to work fine in Firefox on OSX: https://youtu.be/JU1nG0tjUxE

**Comment by Kreyren** [comment]
> Ah, maybe you mean that the fork selector doesn't work..

Correct, the fork selector doesn't work properly on my end (Message 'Loading..." appears forever and i can not select my repository), but it seems that you forking bedrock's repository changed the behavior since now i can make a pull request in your repository -> I assume that gitpod doesn't update the metadata properly and just shows the newest repository instead of expected repository?

![image](https://user-images.githubusercontent.com/11302521/70075843-dc96c900-15fd-11ea-8c96-f3a881b330af.png)

**Comment by svenefftinge** [comment]
Ah! when you want to create a PR for Kreyrock it is not available. I can reproduce it.

1) https://gitpod.io/#https://github.com/Kreyrock/Kreyrock
2) do a change, commit and push
3) open PR view and try to propose that change to `Kreyrock/Kreyrock`

**Comment by svenefftinge** [comment]
Btw. your .gitpod.yml needs to start with a dot (https://github.com/Kreyrock/Kreyrock/pull/8)

**Comment by Kreyren** [comment]
> Btw. your .gitpod.yml needs to start with a dot ..

Thanks
