### ISSUE TITLE
Installer 2022.04.1   incorrectly sets openvsx  url

### ISSUE THREAD

**Issue by hm2075** [gitpod-io/gitpod#9670]
### Bug description

502 server error when finding extensions

### Steps to reproduce

install using 2022.04.1 installer

gitpod.config.yaml   contains 

 openVSX:
  url: https://open-vsx.org

however when rendered to gitpod.yaml  it does a replace incorrectly to   
"vsxRegistryUrl": "https://open-vsx.domain.com",

worked around this by manually replacing all these vsx urls

**Comment by MrSimonEmms** [comment]
See [Server configmap](https://github.com/gitpod-io/gitpod/blob/5362e2295e1b2e741d143cf3184937628e497194/install/installer/pkg/components/server/configmap.go#L180) for code location

**Comment by mustard-mh** [comment]
@hm2075  Gitpod has a component `openvsx-proxy` which will cache some requests from clients and respond them if `open-vsx.org` request failed (under maintenance etc)

> however when rendered to gitpod.yaml it does a replace incorrectly to
> "vsxRegistryUrl": "https://open-vsx.domain.com/",

so, this one `vsxRegistryUrl` is URL of `openvsx-proxy`

**Comment by mustard-mh** [comment]
> 502 server error when finding extensions

Response with 502 needs more input

**Comment by mustard-mh** [comment]
> 502 server error when finding extensions

Response with 502 needs more input

**Comment by hm2075** [comment]
yes but the pod for the vsx proxy doesnt actually startup  if using the installer

![image](https://user-images.githubusercontent.com/53794682/167209489-f8e06076-d66b-4a19-8cd0-1905daecd8bd.png)

**Comment by mustard-mh** [comment]
> You need to run kubectl delete statefulset openvsx-proxy before installing if you are using the [installer](https://github.com/gitpod-io/gitpod/tree/main/install/installer) unless you are upgrading from 2022.04

Have you tried this step? It works for my self-hosted one

**Comment by hm2075** [comment]
this looks to be resolved in latest installer
