### ISSUE TITLE
[observability] Create an alert when prebuilds are stuck in pending state

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#9674]
## Is your feature request related to a problem? Please describe

An alert should be triggered when there are prebuilds stuck in pending state.

## Describe the behaviour you'd like

An alert should be triggered when there are prebuilds stuck in pending state.
## Describe alternatives you've considered

NA

## Additional context

See https://github.com/gitpod-io/gitpod/issues/9673

**Comment by kylos101** [comment]
Hey @princerachit , wdyt of including regular workspaces too? I think excluding image builds makes sense, for now, as they're in the webapp cluster, but moving to workspace cluster soon.

**Comment by princerachit** [comment]
Hey @kylos101 sure, Let me check if GitpodWorkspaceTooManyRegularNotActive is any different. I will update this issue accordingly

**Comment by princerachit** [comment]
Regular not active looks different from pending state. As captured in this runbook. When regular not active then the phase is creating.

I will update the issue to capture both prebuilds and regular workspaces
