### ISSUE TITLE
clean-slate-deployment should behave gracefully if there is nothing to clean

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#9678]
## Is your feature request related to a problem? Please describe
Right now, the deploy-to-preview-environments on `main` fails, because the job has `clean-slate-deployment` enabled but there is no old preview environment to clean.

Example: https://werft.gitpod-dev.com/job/gitpod-build-main.3090

## Describe the behaviour you'd like
Don't fail if `clean-slate-deployment` is enabled but there is nothing to clean.

**Comment by mads-hartmann** [comment]
Latest build on main succeeded https://werft.gitpod-dev.com/job/gitpod-build-main.3092 ☺️
