### ISSUE TITLE
[code-desktop] hearbeating is broken

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#9680]
### Bug description

Users were reporting via support channel that hearbeating does not work anymore.
I tried to use as well and could not hearteating traces in `Gitpod Workspace` channel anymore.

### Steps to reproduce

See above.

**Comment by jeanp413** [comment]
Took a look and heartbeat is send successfully to the server, also added a few missing events to send heartbeats https://github.com/gitpod-io/openvscode-server/commit/e400c62d05b8c92cf591d2debe975313b7232c83 and published a new version of the extension.

P.S.: Heartbeat traces are not shown in the `Gitpod Workspace` as it's just too much noise to have them logged, instead we log if there's any error or if it's the last heartbeat.
