### ISSUE TITLE
Upgrade VM image

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#9684]
## Is your feature request related to a problem? Please describe
Upgrade to the latest image that workspace clusters are using. 

The instance template "[workspace-ws-eu43xl-pool](https://console.cloud.google.com/compute/instanceTemplates/details/workspace-ws-eu43xl-pool?project=workspace-clusters)" uses image "[gitpod-k3s-202204270643](https://console.cloud.google.com/compute/imagesDetail/projects/workspace-clusters/global/images/gitpod-k3s-202204270643?project=workspace-clusters)" 

Change Log: https://www.notion.so/gitpod/Workspace-clusters-changelog-b52c613d50d24e3bb1b5b5eba0e8b598

Howto on how to upgrade the image: https://www.notion.so/gitpod/Build-a-new-VM-image-for-preview-environments-50d2ec47ca1d4a65bc45a7efb877e3a0
(the Howto may need a review)

It looks like we can also reduce the size of the PV from 150GB to 100GB 🚀 
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/239422/166225591-55b489b9-b331-4765-a08f-331dac0b19ee.png">

**Comment by jenting** [comment]
The steps to update the image are:
1. export the current latest image [gitpod-k3s-202205250211](https://github.com/gitpod-io/gitpod-packer-gcp-image/releases/tag/gitpod-k3s-202205250211) from [here](https://console.cloud.google.com/compute/images?project=workspace-clusters) to a [storage bucket](https://console.cloud.google.com/storage/browser/workspace-clusters-daisy-bkt;tab=objects?forceOnBucketsSortingFiltering=false&project=workspace-clusters&prefix=&forceOnObjectsSortingFiltering=false)
1. import [the image in harvester](https://harvester.gitpod-dev.com/dashboard/c/local/harvester/harvesterhci.io.virtualmachineimage)
1. copy the storageClass in Harvester to set replicas=1 and enable dataLocality. [Example](https://harvester.gitpod-dev.com/dashboard/c/local/explorer/storage.k8s.io.storageclass/longhorn-image-xcx77-onereplica?as=yaml#parameters).
1. change the [imageID and storage-class here](https://github.com/gitpod-io/gitpod/blob/2bba4a6926c8e54e1047fc4da6e15e6d38a4df4e/.werft/vm/manifests.ts#L36).
1. run [distribute-images.sh](https://github.com/gitpod-io/gitpod/blob/main/dev/preview/test/distribute-images.sh) to force Longhorn to replicate the new image to all nodes.
