### ISSUE TITLE
Correctly display workspace's memory usage when running `free`

### ISSUE THREAD

**Issue by utam0k** [gitpod-io/gitpod#9688]
Old title: "Intercepting sysinfo using seccomp notify"

## Is your feature request related to a problem? Please describe

Running the `free` command or other commands in the current workspace will display the host's memory usage. We should be able to work around this by intercepting `sysinfo` with seccomp notify and getting it from the cgroup value.  Also, memory is just one example, but perhaps other metrics can be obtained as well.

Ref: https://github.com/lxc/lxd/blob/286284604290c7feb1c1f5b4c8bdacf54b220ce4/lxd/seccomp/seccomp.go#L1697

```console
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          64312       17645        1060         676       45606       45261
Swap:             0           0           0
```

## Describe the behaviour you'd like

`free` command displays workspace memory

**Comment by kylos101** [comment]
One thing to think about for this issue, is that in JetBrains we want to see resource usage for the container and the node. If we were to do this for the container, how would that impact our ability to share node details?

**Comment by akosyakov** [comment]
I don't think it is good idea. I just have a following case when VM crashed but from perspective of cgroups for particular workspace container it looked alright. A user should know consumption of node, container and for java user heap to really understand performance. I don't think hiding is a way.

Example just took in one workspace, memory consumption on Node is quite high, but from point of a container only half of limit is consumed. One won't expect a danger, but in reality processes are already close to be OOM killed.
<img width="619" alt="Screenshot 2022-05-11 at 09 05 50" src="https://user-images.githubusercontent.com/3082655/167851790-97f85feb-3831-4c8f-939f-b847d62d170c.png">
<img width="444" alt="Screenshot 2022-05-11 at 09 05 40" src="https://user-images.githubusercontent.com/3082655/167852118-5b05361f-9f9f-4d79-bcfc-8d929408b817.png">

If we do it we will need somehow not only respect cgroup, but update limit dynamically maybe as min between cgroup limit and really available memory. It sounds rather error prone.

**Comment by utam0k** [comment]
However, in cgroup v2, the JVM's container support will probably not work effectively, since in cgroup v2 the workspace will not be able to see the cgroup values restricted to pods. This also is the case with supervisor.

**Comment by atduarte** [comment]
@akosyakov in other cloud providers, that also overbook, you are unable to see the host's stats. 🤔 Showing host's stats kind of creates a bit of confusion. For us, it's useful but for others it should be just a technical detail they don't need to know about. wdyt?

**Comment by akosyakov** [comment]
@atduarte I'm fine to try, I just meant that we should be careful, cgroup does not show truth either and it can cause confusion. I think it will work if ability to reach limit is ensured, but we need to play with it maybe I'm overthinking.
