### ISSUE TITLE
Extension icon not properly rendered when using Safari

### ISSUE THREAD

**Issue by vince-fugnitto** [gitpod-io/gitpod#969]
**Describe the bug**

The sidebar icon for the [ionide-fsharp](https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp) extension is not rendered when using Safari.
The original issue was opened in Theia (https://github.com/eclipse-theia/theia/issues/6575), but after testing, the issue only occurs when using Gitpod.

<img width="185" alt="Screen Shot 2019-12-04 at 10 13 11 AM" src="https://user-images.githubusercontent.com/40359487/70154585-b82f0100-167e-11ea-8142-2a54e6650d41.png">

**To Reproduce**

As described in the original issue:
- go to https://gitpod.io/#https://github.com/Krzysztof-Cieslak/GitPodSample
- notice lack of F# icon in the activity bar
- click at the area under last visible icon to notice the button is there just without any icon

**Expected behavior**

The icon should be properly displayed across all browsers.

**Additional Information**

**Comment by svenefftinge** [comment]
For some reason safari doesn't send the cookies when requesting the icon, so the answer is 403 unauthorized. It works if I just copy paste the URL into a new safari window, so seems to have something to do with the way we are fetching those icons (i.e. setting the url in CSS).
