### ISSUE TITLE
plan remaining hours and progress bar

### ISSUE THREAD

**Issue by ionutale** [gitpod-io/gitpod#9702]
### Bug description

on the plan page, the text in combination with hours and colors needs a bit of improvement.

i mean this 
<img width="455" alt="Screenshot 2022-05-02 at 20 20 12" src="https://user-images.githubusercontent.com/2562455/166303325-c0c08d8b-add3-4d5b-abe1-61f872b3f9ea.png">

makes more sense than this at UX level
<img width="447" alt="Screenshot 2022-05-02 at 20 20 33" src="https://user-images.githubusercontent.com/2562455/166303372-ee471b15-5c5f-475a-8f85-88496b140cab.png">

colors perceptions:
    white, void, empty
    green, value, positive

so having the green color reflect the remaining hours actually makes sens 

### Steps to reproduce

go to this page
https://gitpod.io/plans

**Comment by gtsiolis** [comment]
Thanks for bringing this up, @ionutale! The proposal sounds like a good MVC (minimum viable change) with low impact.

We're currently working towards a usage-based pricing and will update this page in upcoming months, see https://github.com/gitpod-io/gitpod/issues/9036.

In the meantime, I've marked this as a ~good-first-time issue in case anyone from the community would like to pick this up.

**Comment by ashutoshdhande** [comment]
@gtsiolis may I work on this sir?

**Comment by ionutale** [comment]
@ashutoshdhande check this PR 
https://github.com/gitpod-io/gitpod/pull/9716

**Comment by gtsiolis** [comment]
No need to ask for permission, @ashutoshdhande! Feel free to open a PR for anything that you would like to contribute to. 

I'd just make sure there's no linked PR anywhere in the issue and there's no assignee. In this case, looks like @ionutale moved fast and opened a PR to resolve this.
