### ISSUE TITLE
Connecting to a workspace with ssh gives error as RSA/SHA1 is deprecated

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#9719]
RSA/SHA1 is deprecated https://www.openssh.com/txt/release-8.8

In the meantime we can add `-oHostKeyAlgorithms=+ssh-rsa` to the ssh command as a workaround

**Comment by mrzarquon** [comment]
the root is go/ssh and it looks to be almost done: https://github.com/golang/go/issues/49952
