### ISSUE TITLE
Unable to stop deleting partition

### ISSUE THREAD

**Issue by ITdesk01** [gitpod-io/gitpod#972]
I created a partition yesterday and it was not closed. I want to close it today, but I ca n’t stop it or delete it.

![image](https://user-images.githubusercontent.com/38835844/70287559-497eae80-180a-11ea-8042-6b0915114dcb.png)

**Comment by ITdesk01** [comment]
Only this partition will be like this, other new partitions are normal, you can stop deleting

**Comment by svenefftinge** [comment]
Two things to do here:
 - figure out why and when a workspace hands in running.
 - Allow deleting workspace no matter what state.

**Comment by ITdesk01** [comment]
I can delete it again after a few days

**Comment by ITdesk01** [comment]
I have n’t encountered this problem for the time being.

**Comment by ITdesk01** [comment]
Thanks for your reply
