### ISSUE TITLE
workspace-preview: test image build in governed workspace-preview cluster

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#9729]
Depends on: https://github.com/gitpod-io/gitpod/issues/9143

Setup a branch that:
1. allows all ingress for image-builder-mk3
2. at install time, sets the `movedImageBuilder` defaultFeatureFlag

To test:
  1. Create two single node clusters (webapp and workspace, govern the workspace one to webapp) using [workspace-preview](https://github.com/gitpod-io/workspace-preview)
  2. Image builds should work at this point

**Comment by kylos101** [comment]
@WVerlaek for Wednesday, after testing and shifting traffic to ship `gen78`, may I ask you to test the image build scenarios you had planned, knowing that they won't be able to start workspaces? I ask because you should be able to inspect the `/metrics` endpoint for `gitpod_image_builder_builds_done_total` to gauge success/failure. 

After which, I think you can close this issue and then focus on https://github.com/gitpod-io/workspace-preview/issues/71 (which'll help the Gitpod Dedicated team avoid unnecessary components on the application cluster), followed by https://github.com/gitpod-io/ops/issues/6905 (which'll help us move the image builder in gitpod.io).

cc: @aledbf you should be able to install Gitpod with a workspace installation type and get image builder in the workspace cluster, and no image builder in the application cluster with [this branch](https://github.com/gitpod-io/gitpod/tree/wv/workspace-image-builds). We haven't exposed the flag in the installer yet as an FYI, hence no PR or merging it back to main yet.

**Comment by kylos101** [comment]
@WVerlaek updated ☝ to factor in the installer changes 😄

**Comment by WVerlaek** [comment]
@kylos101 successfully tested the image build test scenarios in workspace-preview clusters.

Cleaned up the wv/workspace-image-builds branch as well, squashed+rebased on main, and raised as a draft PR here: https://github.com/gitpod-io/gitpod/pull/15276. Still need to configure installer experimental config to set the `movedImageBuilder` flag, and do more testing.

**Comment by WVerlaek** [comment]
Going to close this issue as the workspace-preview tests are done

**Comment by kylos101** [comment]
Thanks @WVerlaek ! I've added #15276 to our project for visibility.

Also, I've [asked](https://gitpod.slack.com/archives/C02F19UUW6S/p1670818624714899) @Furisto to help with https://github.com/gitpod-io/workspace-preview/issues/71, this way you can focus on https://github.com/gitpod-io/gitpod/pull/15276. 

After #15276 is done, then you can go back to https://github.com/gitpod-io/ops/issues/6905, to get us closer to running image builds in gitpod.io.
