### ISSUE TITLE
Share WorkSpace is broken when user has not logged into GitPod

### ISSUE THREAD

**Issue by ziahamza** [gitpod-io/gitpod#973]
**Describe the bug**

When a workspace is shared, it gives error when the user is not logged into GitPod

**To Reproduce**

1- Share a workspace
2- Open the shared link in browser in-cognito mode 
3- Shows Sorry promit and doesnt tell user to login into GitPod

**Expected behavior**

1- Prompt the user to login into GitPod and get access to workspace

**Additional Information**

**Comment by jankeromnes** [comment]
Thank you @ziahamza for reporting this issue! And sorry that it was broken during our demo.

I was able to reproduce the problem. Here is a screencast: https://youtu.be/zxs5KA0Hiww
