### ISSUE TITLE
Dockerfile multi stage support

### ISSUE THREAD

**Issue by anonymouse-jj** [gitpod-io/gitpod#9743]
I often have different stages in a single Dockerfile and I'd like the option to specify the target in .gitpod.yml

Example .gitpod.yml:

```
image:
  file: .gitpod.Dockerfile
  #  target: devstage
```

**Comment by cyclux** [comment]
This feature would be very useful and does not seem to require a significant implementation effort. Could you reconsider integrating the target stage?
