### ISSUE TITLE
`gp open` doesn't open file in desktop VSCode - just hangs

### ISSUE THREAD

**Issue by david-bakin** [gitpod-io/gitpod#9745]
### Bug description

Open some workspace using desktop VSCode.  Open a file, e.g., `gp open /home/gitpod/.bashrc`.  

Expected result:  `~/.bashrc` opens in VSCode.

Actual result: `gp` command hangs.  Nothing happens in VSCode.

### Steps to reproduce

Open some workspace using desktop VSCode.  Open a file, e.g., `gp open /home/gitpod/.bashrc`.   Observe that `gp` simply hangs.

### Workspace affected

bakinsbits-gitpodsetupf-eexyrtepf4j (though I suppose it isn't specific to this workspace)

### Expected behavior

Expected result:  `~/.bashrc` opens in VSCode.

### Anything else?

`gp version` ⮕ `main.3045`.

**Comment by mustard-mh** [comment]
Hi @david-bakin , I can't reproduce this issue, after investigate, I found some possible situation that may cause it

- Open desktop one, and browser one, but browser one ready after desktop one, use orgin tty(from gp tasks) to open file in desktop
- Open browser one, and desktop one, back to browser one, but do not switch browser tab

I'm not sure if they are your cases, please ping me if you want to add some additional description of your issue.

**Comment by david-bakin** [comment]
Neither is my use case since I never ever use the in-browser IDE.

Whatever it was that happened to me isn't happening anymore.  `gp open` works fine in other workspaces.  But thanks for taking the time to investigate!
