### ISSUE TITLE
Error: Couldn't parse context 'https://gitpod.io/#https://github.com/mikhail-cct/CA1-In-class-Demo'.

### ISSUE THREAD

**Issue by dricajulio** [gitpod-io/gitpod#976]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information**

**Comment by jankeromnes** [comment]
Hi @dricajulio, thank you for reporting this issue, and sorry that it didn't work!

I tried to reproduce the problem, but for me this context URL seems to work: https://youtu.be/vJvwRIuq3wY

Maybe this was a temporary issue? Could you please try again?

Also, what URL did you visit, or what did you click on just before arriving at this error? (This may give additional clues as to what went wrong.)
