### ISSUE TITLE
Admin license screen showing "exceeded usage limit" on unlimited user license

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#9763]
### Bug description

There is an error message on the admin license page saying that we've exceeded the number of users allotted by the license. 

![image](https://user-images.githubusercontent.com/275848/166704695-1f2d12db-bc13-436d-85b7-9b2ff37a053b.png)

### Steps to reproduce

Go to Admin panel, license on gitpod.io

### Expected behavior

The error message should not be visible for an unlimited user plan

**Comment by gtsiolis** [comment]
Nice catch, @MrSimonEmms! ⚾ 

It's also really great that now we surface this kind of information in the Gitpod.io instance. ✨ Cc @nandajavarma 

Thank you for also deducting sensitive information from the screenshots. 🙏

**Comment by gtsiolis** [comment]
@nandajavarma License type is missing but maybe that's expected in the case of Gitpod.io? Asking in case we could include a fallback here or adjust the layout (UX) in this case. Cc @MrSimonEmms
