### ISSUE TITLE
[bug] Handle the case when there is no expiry date on a professional plan

### ISSUE THREAD

**Issue by nandajavarma** [gitpod-io/gitpod#9772]
**Problem to solve**

In the admin dashboard, when the license is professional and if there is no expiry date, we get an unexpected behavior. The tagline under the license name says `Expires on Jan 1, 1` which instead should just say `Paid`.

**Comment by MrSimonEmms** [comment]
I've put this as the delivery for now, but there's a part of me that thinks this is in the WebApp team's remit
