### ISSUE TITLE
Support docker resource constraints

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#9776]
## Is your feature request related to a problem? Please describe

Docker containers are subject to the resource constraints for their Gitpod workspace. Some customers would like to limit the resources that containers can use. This is to support testing of their applications using resource limits, but also prevent the Docker container from starving the Gitpod workspace of resources. 

## Describe the behaviour you'd like

The ability for customers to [specify resource constraints when running docker containers](https://docs.docker.com/config/containers/resource_constraints/#cpu) in Gitpod workspaces.

## Describe alternatives you've considered

N/A

## Additional context

Presently, the resource constraints are not honored. So, if you start a container with ``cpu="0.5", it'll still try to use as many cores as are available to the Gitpod workspace.

**Comment by csweichel** [comment]
In a workspace running with cgroupv2, Docker/containerd actually creates a cgroup and correctly places the process in it. However, when running the container with `--cpus`, no `cpu.max` gets set.
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/3210701/177554203-1ed39197-e964-4d06-8ac3-0f03c23e3be6.png">

**Comment by csweichel** [comment]
Docker picks up `--cpus` correctly:
<img width="889" alt="image" src="https://user-images.githubusercontent.com/3210701/177562916-5100be97-24fb-4f50-a3eb-7774e49bfa1a.png">

But this entry doesn't get translated to `containerd` resources:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/3210701/177563126-db948dad-fc8a-4735-b27e-90e9ffcea57e.png">

Looking at the Moby code though, this is how Docker appears to set those resource limits:

1. [`ContainerStart` calls `containerStart`](https://github.com/moby/moby/blob/300c11c7c9143ca077890050deb83917e67fe250/daemon/start.go#L94)
2. [`containerStart` calls `createSpec`](https://github.com/moby/moby/blob/300c11c7c9143ca077890050deb83917e67fe250/daemon/start.go#L153)
3. [`createSpec` calls `WithResources`](https://github.com/moby/moby/blob/c3d7a0c6033a2764dd85c3863809ac498ef129f2/daemon/oci_linux.go#L1016)
4. [`WithResources` calls `getCPUResources'](https://github.com/moby/moby/blob/c3d7a0c6033a2764dd85c3863809ac498ef129f2/daemon/oci_linux.go#L958)
5. [`getCPUResources` translates `NanoCpus` to quota and period](https://github.com/moby/moby/blob/2c7a6d7bb1931f88d8d925c281f106f72c01b4c9/daemon/daemon_unix.go#L148-L154)

**Comment by utam0k** [comment]
Docker needs systemd when cgroup v2 runs with rootless. 
@csweichel Do you know any reason we continue to use rootless mode with cgroup v2?

**Comment by utam0k** [comment]
@Furisto @aledbf Do you know why we continue to use a rootless mode of dockerd?

**Comment by aledbf** [comment]
@utam0k we need to find a way to detect if we are using cgroups v1 or v2 and adapt dockerd flags

**Comment by utam0k** [comment]
> @utam0k we need to find a way to detect if we are using cgroups v1 or v2 and adapt dockerd flags

Thanks for your comment. I found the same thing. I have implemented that.
https://github.com/gitpod-io/gitpod/pull/11491/files#diff-39f21ac00b904269148785bf38d0d67aa3bd012ef024c43c4be9480ebdbe38edR112
