### ISSUE TITLE
There is a bug with starting a workspace

### ISSUE THREAD

**Issue by okikio** [gitpod-io/gitpod#978]
**Describe the bug**

There is a bug with starting a workspace, it seems to randomly crash.

**To Reproduce**

gitpod.io/#https://github.com/okikio/joseph

**Expected behavior**

It should start into the workspace, with extentions and prebuild done.

**Additional Information**

The devtools states: "Connection got disposed."

**Comment by JesterOrNot** [comment]
How is your WiFi often this will happen when web-sockets get closed if your WiFi is unstable then that would explain it!

**Comment by okikio** [comment]
My WiFi was a little shaky at the time but now that it's stabilized I
can't open the work space anymore. On my dashboard the work space
shows an "Open" button (instead of a "Start" button); when I try to
start the work space nothing happens. I have tried archiving,
deleting, etc... nothing is working on the work space. I don't know
what is wrong with it. Also, when I tried to start the work space
sometime earlier today, the pre-build kept crashing giving me an "nvm
not installed error..." for some reason (at this point in time I hadn'
t changed the dockerfile for a couple weeks so the problem was
unusual). Later today I added the nvm install commands into my
dockerfile to try to counter the error but I think it made it worse.
So, ... I don't know what to do?

**Comment by JesterOrNot** [comment]
Could you provide the link to the problematic repository and a screenshot of the issue?

**Comment by okikio** [comment]
The repository link is: github.com/okikio/joseph.

**Comment by JesterOrNot** [comment]
nvm comes preinstalled in gitpod's base image

**Comment by okikio** [comment]
I know but do you know why the pre-build crashed with an error.

**Comment by svenefftinge** [comment]
I have created a PR to fix the config. https://github.com/okikio/joseph/pull/1
The docker build was broken. Unfortunately the logs are swallowed during prebuild, but you'd see the error log when clicking 'skip prebuild'.
