### ISSUE TITLE
Feature Request: Skip prebuild loading

### ISSUE THREAD

**Issue by Meldiron** [gitpod-io/gitpod#9789]
## Is your feature request related to a problem? Please describe

My repository has prebuilds enabled, but the prebuild is pretty big and takes a few minutes to load. In a scenario when I am visiting PR to apply some changes as suggested in reviews, I want to open Gitpod to do it, but it takes minutes to spin up. I will end up cloning the repo locally instead of using Gitpod due to the long loading time.

## Describe the behaviour you'd like

In the last step of loading (3/3), there could be a button to `Skip preloading`. This would not load prebuilds, and will simply open the workspace without it.

## Describe alternatives you've considered

Maybe it would be possible to load prebuilds in the background. That way I can play around in the code while Gitpod is still loading preload for a successful application run.

## Additional context

This could possibly be all just a preload issue that takes too long. But I believe images I use can be up to a few GBs in size, and I don't think there is any way to load that as fast as a few seconds.

**Comment by kylos101** [comment]
@geropl adding to WebApp inbox, as the capability to bypass an active prebuild exists when prebuilds are in-progress. 

My assumption (which may be naive) is that we could also give users the ability to bypass the loading of content from a pre-existing prebuild.

**Comment by svenefftinge** [comment]
This is technically a feature that workspaces would need to allow. I.e. we'd need to tell ws-manager (and then ws-daemon) that the init from prebuild should be skipped and the regular git initialization should happen. Alternatively, we could detect the size of the prebuild snapshot and depending on that (i.e. if it's rather large, what ever that means) ask the user before we start a workspace. I would love to avoid both features and instead work on making workspace starts faster tbh.

**Comment by bitsnaps** [comment]
> This is technically a feature that workspaces would need to allow. I.e. we'd need to tell ws-manager (and then ws-daemon) that the init from prebuild should be skipped and the regular git initialization should happen. Alternatively, we could detect the size of the prebuild snapshot and depending on that (i.e. if it's rather large, what ever that means) ask the user before we start a workspace. I would love to avoid both features and instead work on making workspace starts faster tbh.

I wish to see that feature, before spin up a workspace (not during the starting), this make it easy for automation (e.g. from urlwith `?/skip-rebuild=0`), @svenefftinge I've just saw `Skip rebuild` button at the starting, is that feature already implemented?

**Comment by svenefftinge** [comment]
We could relatively easy add an additional context menu action on the projects branches list, that starts workspace from git.
Alternatively, a special context URL could do the trick as well.
