### ISSUE TITLE
[bug] unable to start workspaces in desktop VSCode

### ISSUE THREAD

**Issue by nberlette** [gitpod-io/gitpod#9798]
### Bug description

**All workspaces** fail to start when my settings are configured to open Gitpod in my desktop installation of VS Code or VS Code insiders, giving me a very cryptic error message. When my preferences are set to launch workspaces **in-browser**, everything works fine and as expected.

### Steps to reproduce

1. Change settings to launch in `VS Code`, not `in browser`. Insiders/Regular doesn't matter.
<img width="530" alt="Screen Shot 2022-05-04 at 9 28 40 AM" src="https://user-images.githubusercontent.com/11234104/167005183-a2842fba-5f7e-425a-95e7-d526229fac7c.png">

2. Open a new workspace. For me, **all workspaces** and all regions are affected by this.

3. Get this error message:
<img width="532" alt="Screen Shot 2022-05-04 at 9 31 06 AM" src="https://user-images.githubusercontent.com/11234104/167004930-e7cf5cfa-a486-41b6-bc61-0fa715da5640.png">

Clicking on Open Workspace cycles through the startup sequence with the bouncing Gitpod logo... and then just returns the same error message.

### Workspace affected

all

### Expected behavior

Be able to spin up a workspace and have Chrome (or whatever browser) use the `vscode://` protocol to open an SSH tunnel to the workspace in a local VS Code installation.

### Anything else?

This started between April 12-14, when the huge outage happened, and I've just been working around it thus far.

For now, I've just been launching in browser and then clicking on this option:
<img width="427" alt="Screen Shot 2022-05-05 at 11 42 42 AM" src="https://user-images.githubusercontent.com/11234104/167005216-30594b21-86b9-43bc-b9f8-c5949cf0eb7b.png">

It's quite frustrating 😔

**Comment by gtsiolis** [comment]
@nberlette I could _not_ reproduce this on Gitpod.io.

Here's what should be shown after workspace start (loading) page is complete, when using VS Code Desktop as the editor:

| Using latest release | Not using latest release |
|-|-|
| <img width="1440" alt="Screenshot 2022-05-06 at 12 43 02 PM" src="https://user-images.githubusercontent.com/120486/167107996-ac79ff2c-f9ac-4f3f-92af-2f20179717d2.png"> | <img width="1440" alt="Screenshot 2022-05-06 at 12 45 30 PM" src="https://user-images.githubusercontent.com/120486/167108306-2121e7c3-4eb7-42e4-a26c-aa635f18a3ba.png"> |

Looping in @gitpod-io/engineering-workspace in case this could be related to https://github.com/gitpod-io/gitpod/issues/7754.

**Comment by nberlette** [comment]
@gtsiolis that's the exact screen I'm expecting to see (just didn't have a screen grab of it). This started around the time of the blackout from April 12-14. 

I'll try to get a snapshot, or something that might have some logs you guys can look at. It's tricky though, as of now I haven't been able to get _into_ any stalled workspaces.. I've had to start a whole new one. 

Thanks George

**Comment by nberlette** [comment]
@gtsiolis Okay, made some progress tonight! It's got something to do with my dotfiles repository that I have setup with Gitpod... I cleared the dotfiles setting out, and the problem went away. However, after immediately re-applying the dotfiles repository I get the same error again.

### Without dotfiles
<img width="500" alt="gitpod-error-1" src="https://user-images.githubusercontent.com/11234104/167236808-3afe79ee-8e4b-4b43-9fb8-7a534da4b10c.png">

### With dotfiles ([`https://github.com/nberlette/dotfiles`](https://github.com/nberlette/dotfiles))
<img width="500" alt="gitpod-error-2" src="https://user-images.githubusercontent.com/11234104/167236817-3cbf0a8f-62fe-4885-9262-8d3e85500600.png">

I'm unable to figure out exactly _what_ it is about my dotfiles thats causing the failure.  The repository is public, however, and located at https://github.com/nberlette/dotfiles. 

I know you guys are busy over there (with more significant issues than mine), but if you or a teammate could possibly spare a few minutes of bandwidth one of these days, I can't tell you how much I'd appreciate you helping me get to the bottom of this. Feel free to shoot me an email at `nick at berlette.com`, if you'd like discussion to move away from the issue tracker. 

As always, first class customer service and support from Gitpod. Thanks again.

**Comment by sagor999** [comment]
@nberlette did you fix issue with your dotfiles? 
I just tried to use them and was able to open this project without any problems using my desktop VS code: 
https://github.com/gitpod-io/template-golang-cli

**Comment by josh-braid** [comment]
We have been having this exact issue as well, and nobody is using a dotfile repo currently on our team
