### ISSUE TITLE
Real-time linting?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#980]
Is there some way to get **real-time linting** on gitpod? 

## Current behavior
I have to configure Dockerimage with shellcheck and invoke `shellcheck path/to/file` in gitpod's terminal to get this behavior which is not an ideal. 

## Expected 
Something that scans the file that is currently being edited for syntaxes and spelling that would output an message if developer makes a mistake.

Example from Atom:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/11302521/70396107-2ae50700-1a06-11ea-85d2-784469be36cc.png">

Notice that if something is spelled incorrectly the editor informs the end-user about it.

---

Sidenotes: Usually linting of long complicated files fails (example above fails, but outputs the errors prior to failure) this should be somehow handled like adding a sleep for 5 seconds before next scan.

**Comment by jankeromnes** [comment]
Hi @Kreyren, Gitpod already has real-time linting for many languages (JS, TS, Python, Java, C++, etc.)

It doesn't have it for `shellcheck`, but since you've already installed the CLI tool in your Dockerfile, I suggest you try installing the corresponding VS Code extension. You can simply add this to your `.gitpod.yml` file:

```yml
vscode:
  extensions:
    - timonwong.shellcheck@0.8.1:16BMw7Jrwd/KkAhJrkHwqQ==
```

Hopefully this should give you real-time Bash linting.

**Comment by Kreyren** [comment]
@jankeromnes thanks that seems to get me the shellcheck, but it doesn't follow paths which i assume is issue on the extension side.. investigating it now

<img width="721" alt="image" src="https://user-images.githubusercontent.com/11302521/70464640-917a2b80-1abf-11ea-97b2-960ff2b5619d.png">

**Comment by svenefftinge** [comment]
> Apparently this extension needs shellcheck.customArgs": ["--external-sources"] added in VS-Code which seems to be in File -> Settings -> Open Preferences -> Can i somehow save this on GitPod per repository? (Expecting contributors to have an environment to make contribution easier if they don't have configured text editor and system)

Yes, gitpod will happily pick up `.vscode/settings.json` respecting the same format. Alternatively you can put them in `.theia/settings.json`.

**Comment by Kreyren** [comment]
Closing as fixed.
