### ISSUE TITLE
[dupe] Workspaces fail to start when configured to open in local VS Code install

### ISSUE THREAD

**Issue by nberlette** [gitpod-io/gitpod#9812]
### Bug description

Sorry if this is a dupe, I submitted an issue earlier regarding this but it's somehow just totally vanished as far as I can tell. 

Anyway, when I have my Gitpod settings configured to open workspaces in my local VS Code install (regardless of Insiders or not), **all** workspaces fail during the startup process. I also get  a weird, cryptic error message. When I click on "Open Workspace", it just cycles through the same failed start process. Takes about 2-5 minutes depending on prebuild complexity / custom dockerimage.

![Uploading Screen Shot 2022-05-04 at 9.31.06 AM.png…]()

### Steps to reproduce

1. Change settings to open in local VS Code instead of in-browser
<img width="530" alt="Screen Shot 2022-05-04 at 9 28 40 AM" src="https://user-images.githubusercontent.com/11234104/167045703-7d03c234-a1d1-4003-9ab2-88d890e0be86.png">

2. Open up a new workspace. For me, every workspace is affected by this.

3. Get that weird error message above. I'm able to get workspaces to hop over to the local install by using the in-browser editor's menu, and selecting "Open in VS Code". See below:

<img width="427" alt="Screen Shot 2022-05-05 at 11 42 42 AM" src="https://user-images.githubusercontent.com/11234104/167045798-cec86896-9360-4ccf-afd8-ee69d75aa12b.png">

### Workspace affected

all of them

### Expected behavior

I've been using this feature for a while (and I love it when it works). I expect the workspaces to open up my macOS Visual Studio Code app (or Insiders app), and connect to the remote workspace via SSH tunnel. None of that happens.

**Comment by nberlette** [comment]
Sorry, I'm able to locate the original issue now. Closing this one as it's a duplicate.

**Comment by gtsiolis** [comment]
Thanks for closing this as a duplicate, @nberlette! Cross-posting for visibility, the duplicate issue can be found in https://github.com/gitpod-io/gitpod/issues/9798.
