### ISSUE TITLE
Use a different button size for the browser extension on empty repositories in GitHub

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#9817]
### Problem to solve

Following up from https://github.com/gitpod-io/browser-extension/pull/60, although moving the button inside the empty state layout is a great improvement, the button style does not follow the rest of the nearby buttons.

### Proposal

:a: Ideally, in this case, the button should use the small button size to match the nearby buttons.

:b: Alternatively, a boring (simple) solution could be to move the button to a different area so that we could use the same button size everywhere.

| BEFORE | AFTER |
|-|-|
| <img width="1229" alt="btn-before" src="https://user-images.githubusercontent.com/120486/167103054-71d85b62-4109-4e9b-8a1d-8b7244854f7b.png"> | <img width="1229" alt="btn-after" src="https://user-images.githubusercontent.com/120486/167103055-ac1787b0-4b13-42bc-b73b-b66a4838b1de.png"> |

**Comment by andreafalzetti** [comment]
Fixed with https://github.com/gitpod-io/browser-extension/pull/61

Pending action: release extension
