### ISSUE TITLE
Investigate imagebuilds stuck in terminating

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#9826]
### Bug description

Imagebuilds are stuck in terminating. This does not seem related to the uninterruptible sleep problems we have seen recently as the containers are already gone, but Kubernetes still holds on to them. Removal of the finalizer and force deleting them is the only option to get rid of them.

### Steps to reproduce

Unknown at the moment

**Comment by atduarte** [comment]
@Furisto is this still happening?
