### ISSUE TITLE
VNC and ports closing randomly

### ISSUE THREAD

**Issue by sasdallas** [gitpod-io/gitpod#9832]
### Bug description

I work with QEMU a lot in my workspace, and sometimes when I’m in the middle of typing a command, all ports suddenly close, and “No ports open” displays in the bottom right. I have no choice but to close and reopen the workspace.

### Steps to reproduce

1. Code for a bit(average 30 mins)
2. Wait for ports to close

### Workspace affected

No, not a specific workspace.

### Expected behavior

I should be able to continue coding, but this hinders my work.

### Example repository

After performing a few qemu commands, I was in the middle of using `dd` when it happened, but it can happen anytime.

### Anything else?

No, but I love your platform.

**Comment by sasdallas** [comment]
This isn’t a critical bug, by the way, only happens sometimes.

**Comment by axonasif** [comment]
Hey, is it still happening?
