### ISSUE TITLE
Feature Request: Support renaming a workspace from the vscode editor view

### ISSUE THREAD

**Issue by mickmister** [gitpod-io/gitpod#9833]
## Is your feature request related to a problem? Please describe

I like to rename workspaces, but AFAIK I have to do this in the Dashboard.

## Describe the behaviour you'd like

In the command palette, I'd like an option to rename the current workspace.

**Comment by loujaybee** [comment]
Ideally if we add this, we start with `gp` CLI, and then update / extend this behaviour into the IDE / editor. 

We'd also need to make sure we show workspace name on the JetBrains Gateway list.
