### ISSUE TITLE
Cannot push changes in GitHub Actions workflows

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#984]
**Describe the bug**
can not push changes to GitHub Action workflows
**To Reproduce**
try to edit GitHub Actions workflow
https://www.loom.com/share/e356809fff3a4a62be4d66855090924b
**Expected behavior**
abe to edit and commit changes to GitHub Actions workflow
**Additional Information**
Example repo https://github.com/JesterOrNot/gosh
Idea: add permission to access control for GitHub actions

**Comment by svenefftinge** [comment]
It is a strange restriction of GitHub. AFAIU you can edit them only on GitHub.

**Comment by akosyakov** [comment]
Stumbled over it as well:
<img width="1552" alt="Screen Shot 2019-12-19 at 11 34 25" src="https://user-images.githubusercontent.com/3082655/71185025-f5001800-227a-11ea-92b0-447e3b1038e3.png">

It would be nice to detect it and grant `workspace` scope as we do for private repos.

**Comment by AlexTugarev** [comment]
@svenefftinge we should add the option to authorize with `workflow` scope, cf. https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes

**Comment by fbigun** [comment]
Is there any other way to bypass.

**Comment by AlexTugarev** [comment]
Hi @fbigun! We'll add the `workflow` scope soon.

The only known way to update a workflow file without this scope is if it already exists in the repo (could be on another branch)
> Workflow files can be committed without this scope if the same file (with both the same path and contents) exists on another branch in the same repository.

**Comment by RDIL** [comment]
Can you guys add it for the next deploy please

**Comment by Kreyren** [comment]
isn't this fixed already? works for me if set in access controls

**Comment by RDIL** [comment]
nope isn't working for me

**Comment by Kreyren** [comment]
Make sure that it is approved on https://gitpod.io/access-control/

![image](https://user-images.githubusercontent.com/11302521/73854173-59c70000-4832-11ea-8164-e5407c65573f.png)

**Comment by RDIL** [comment]
Oh thats new

ok ty

**Comment by JesterOrNot** [comment]
Since this is fixed I am closing this issue!

**Comment by mr-kelly** [comment]
> https://gitpod.io/access-control/

<img width="803" alt="image" src="https://user-images.githubusercontent.com/520852/184407474-0e79d2e8-4d13-40c8-96b6-ed525225d29a.png">

Fix by this. thanks
@Kreyren
