### ISSUE TITLE
Move db-init-scripts out of Helm chart

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#9843]
## Is your feature request related to a problem? Please describe
As a preparation to delete the helm chart (https://github.com/gitpod-io/gitpod/issues/9842) move the [chart/config/db/init](https://github.com/gitpod-io/gitpod/tree/main/chart/config/db/init) out of the helm chart because they are still needed elsewhere. 

They are needed by:
* The `db-migrations`:
https://github.com/gitpod-io/gitpod/blob/4e331313ad8787d6218639d94bf6dd4483c6aa7f/components/gitpod-db/BUILD.yaml#L50

* The installer also has references. Not sure if it consumes the scripts directly or just has references into the db-migrations component:
https://github.com/gitpod-io/gitpod/blob/4820e804bb86ecee9548ce9f1f9aca761d8436b9/install/installer/pkg/components/database/init/constants.go#L12
https://github.com/gitpod-io/gitpod/blob/4820e804bb86ecee9548ce9f1f9aca761d8436b9/install/installer/pkg/components/database/incluster/constants.go#L13
## Describe the behaviour you'd like
Remove files related to db-init from the chart/ folder so that the chart/folder can be safely deleted.

**Comment by geropl** [comment]
This has already been done with the helm chart removal PR.
