### ISSUE TITLE
Refresh workspace page or revisit it and you end up in jetbrains spawning hell

### ISSUE THREAD

**Issue by buggtb** [gitpod-io/gitpod#9848]
### Bug description

If you leave the workspace page and return to it, and, I beleive also just refresh the page. It starts spawning new instances to which there is no escaping.

### Steps to reproduce

Leave open workspace page, return to open workspace page 

![Screenshot 2022-05-08 015708](https://user-images.githubusercontent.com/103544/167277294-94fcded9-5b5c-4dae-ba84-4ee9c83fded5.png)

**Comment by loujaybee** [comment]
Thanks for raising this @buggtb, we are working with JetBrains to see if they can create an API so that we can re-target the thin clients, rather than spawning new ones ([internal link](https://gitpod.slack.com/archives/C02BRJLGPGF/p1653390122754189)).

**Comment by loujaybee** [comment]
Suggestion from @akosyakov: There are things we could do outside of a dedicated JetBrains API, e.g. we can also show when a thin client is connected, prompting the user to re-open an existing thin client, rather than opening a new window.

**Comment by andreafalzetti** [comment]
@buggtb A new version of the Gitpod plugin has been released which comes with a fix for this :)
