### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by FroggieMW** [gitpod-io/gitpod#985]
**Describe the bug**
The bug indicates:
OutOfmemory: Pod Node didn't have enough resource: memory, requested: 2254438400, used: 57302581248, capacity: 57639514112
Please file an issue if you think this is a bug.

**To Reproduce**
Logging into workspace 

**Expected behavior**
I should be able to get into my workspace

**Additional Information**
I have a student account, so I should have unlimited memory.

**Comment by geropl** [comment]
Outdated and fixed in the meantime.

**Comment by JimLynx** [comment]
I realise this is an older issue, but I have a student with the same issue. Could someone clarify how this was resolved?

![gitpod-memory-issue](https://user-images.githubusercontent.com/65254741/151395934-582b4ebf-3d61-41ec-87c9-4269e70fd235.jpg)
