### ISSUE TITLE
Self Hosted: Can add one more user than I should as per license

### ISSUE THREAD

**Issue by oss901** [gitpod-io/gitpod#9876]
### Bug description

This is specific to self-hosted. I was able to add one more user than I should have as per the seats on my license. Note that this occurred when I had 2 seats allowed on my license and then tried to add a third (which worked) and a fourth (which was blocked). 

### Steps to reproduce

Created a loom video to walk you through it: https://www.loom.com/share/6d1d3e1324cc40a389b936c13956714b

**Comment by lucasvaltl** [comment]
Closing this as I created this under the wrong account.
