### ISSUE TITLE
asExternalUri does not translate all expected URLs

### ISSUE THREAD

**Issue by DanTup** [gitpod-io/gitpod#988]
I noticed some issues with asExternalUri:

- Things without ports are not mapped (I think port 80/443 should be inferred from the protocol - VS Online has the same issue https://github.com/MicrosoftDocs/vsonline/issues/252)
- IPv6 loopback is not mapped (VS Online doesn't seem to have IPv6 so this isn't an issue there, but it seems to otherwise work here and is what was returned in Dart when I used the HttpMultiServer bound to `any`)

```
http://localhost/test      -> http://localhost/test
http://localhost:80/test   -> https://80-a0ab8730-f8a3-45ea-bd67-5735e252bd45.ws-eu01.gitpod.io/test
https://localhost/test     -> https://localhost/test
https://localhost:443/test -> https://443-a0ab8730-f8a3-45ea-bd67-5735e252bd45.ws-eu01.gitpod.io/test
http://127.0.0.1/test      -> http://127.0.0.1/test
http://127.0.0.1:80/test   -> https://80-a0ab8730-f8a3-45ea-bd67-5735e252bd45.ws-eu01.gitpod.io/test
https://127.0.0.1/test     -> https://127.0.0.1/test
https://127.0.0.1:443/test -> https://443-a0ab8730-f8a3-45ea-bd67-5735e252bd45.ws-eu01.gitpod.io/test
http://[::1]/test          -> http://%5B::1]/test
http://[::1]:80/test       -> http://%5B::1]:80/test
https://[::1]/test         -> https://%5B::1]/test
https://[::1]:443/test     -> https://%5B::1]:443/test
```

(Note: the encoding issue of `[` becoming `%5B` is a URL encoding issue that exists in VS Code too, and they're updating these functions to accept a `URL` in addition to their custom `Uri` class to allow working around this without breaking anybody - the Dart extension will move over when that's release to stable)

**Comment by akosyakov** [comment]
Here is a relevant code to fix: https://github.com/eclipse-theia/theia/blob/4070136dd5de6f22403ea2cfac25921ffa45e5ff/packages/core/src/browser/external-uri-service.ts#L50 

PRs are welcomed, mocha tests would be nice to check different cases.

**Comment by akosyakov** [comment]
Here is a regex for loopback addresses which we can use instead: https://stackoverflow.com/a/8426365/5988613 Although we should take optional port into the account.

**Comment by akosyakov** [comment]
It's fixed but not yet deployed to production.

**Comment by DanTup** [comment]
Awesome, thanks! I was going to take a look this week but you beat me to it.

I just accidentally tested it (I was testing something else and forgot it would now use IPv6 loopback) and it worked as expected :-)

```
[10:11:11 AM]: <== [{"method":"app.exposeUrl","params":{"url":"http://[::]:39759/$debug"},"id":"1"}]
[10:11:12 AM]: ==> [{"id":"1","result":{"url":"https://39759-cfa9294c-42ee-4ff2-b6e7-1128c935998e.ws-eu01.gitpod-staging.com/$debug"}}]
```

👍

**Comment by DanTup** [comment]
Awesome, thanks! I was going to take a look this week but you beat me to it.

I just accidentally tested it (I was testing something else and forgot it would now use IPv6 loopback) and it worked as expected :-)

```
[10:11:11 AM]: <== [{"method":"app.exposeUrl","params":{"url":"http://[::]:39759/$debug"},"id":"1"}]
[10:11:12 AM]: ==> [{"id":"1","result":{"url":"https://39759-cfa9294c-42ee-4ff2-b6e7-1128c935998e.ws-eu01...../$debug"}}]
```

👍

**Comment by akosyakov** [comment]
@DanTup 😊

**Comment by DanTup** [comment]
@akosyakov out of interest - what/where was the fix for this? Seeing the same issue on another Theia based editor and I'm not sure whether it's due to an old version of Theia or something else (like in hosting infrastructure-specific code). Thanks!

**Comment by akosyakov** [comment]
It is here: https://github.com/gitpod-io/gitpod/blob/master/components/theia/packages/gitpod-extension/src/browser/gitpod-parse-localhost.ts

**Comment by DanTup** [comment]
@akosyakov great, thanks!
