### ISSUE TITLE
Self Hosted: Can add one more users than my license allows me to

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#9888]
### Bug description

This is specific to self-hosted. I was able to add one more user than I should have as per the seats on my license. Note that this occurred when I had 2 seats allowed on my license and then tried to add a third (which worked) and a fourth (which was blocked).

### Steps to reproduce

Created a loom video to walk you through it: https://www.loom.com/share/6d1d3e1324cc40a389b936c13956714b

**Comment by gtsiolis** [comment]
Closing as the `licensor` component has been removed in https://github.com/gitpod-io/gitpod/pull/16983. Cc @aledbf @AlexTugarev @geropl
