### ISSUE TITLE
Gitpod Crashed - I need to recover the code in this

### ISSUE THREAD

**Issue by wendyfoo** [gitpod-io/gitpod#989]
**Describe the bug**

When I try to open the workspace for "tasks", it is showing a red icon with "Evicted: Pod The node had condition: [DiskPressure]. Please file an issue if you think this is a bug." I've tried logging out then logging in and restarting my computer. 

**To Reproduce**

**Expected behavior**

**Additional Information**

I need to at least recover the code in this. Please help.

**Comment by meysholdt** [comment]
Hi @wendyfoo ! I'll reach out to you via email to help.

**Comment by meysholdt** [comment]
Hi @wendyfoo! Find an email from me in your inbox. I believe the workspace should by now start just fine again. But even if there is any trouble with it, we can recover the files. I apologise for the trouble :(

Closing. Please reach out via email if there is more I can help.
