### ISSUE TITLE
Allow Gitpod to expose ports with tls on backend

### ISSUE THREAD

**Issue by krise86** [gitpod-io/gitpod#9897]
## Is your feature request related to a problem? Please describe
When a workspace i started and i want to expose ports on the container it always terminates the connection on the reverse proxy with tls and uses none tls connection to the pod port. this causes issues when backend service is running with TLS

`Client sent an HTTP request to an HTTPS server.`

## Describe the behaviour you'd like
allow to mark ports as tls/https in config or remote explorer. Adding an icon to flag the port as tls

## Describe alternatives you've considered
none

## Additional context
![image](https://user-images.githubusercontent.com/17857459/167609659-dac142fa-6172-4ff2-a05e-ddfe6f56f742.png)

**Comment by akosyakov** [comment]
@krise86 If you can provide a repo to reproduce with steps it would help please? 🙏
