### ISSUE TITLE
Consider making Preview Envs Opt-In

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#9899]
## Is your feature request related to a problem? Please describe
By eliminating unneeded preview envs, we can (either, or a mixture):
* save costs by running a smaller Harvester cluster
* increase developer velocity by running preview envs longer.

## Describe the behaviour you'd like
Add a `with-preview` flag to the Werft job to enable preview envs. 
Also, add a convenient checkbox to our PR template:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/239422/167616298-a593bc35-cee3-4c9e-9ac0-22c8daff80e9.png">

## Additional context
Discussion [in Slack](https://gitpod.slack.com/archives/C01KGM9EBD4/p1652177868093639?thread_ts=1652170979.367649&cid=C01KGM9EBD4).

**Comment by gtsiolis** [comment]
Yes, please! 💯 

This is also aligned with our async remote culture.

Sometimes there's no need to run a preview environment altogether depending on files changes (`README.md`, etc) and given how we work asynchronously keeping a preview environment alive until the reviewer can come back to it becomes unessasary as they have to trigger another deployment, which only takes a few minutes. ⏱️ 

This has been brought up in the past a few times, see [relevant discussion](https://gitpod.slack.com/archives/C01KGM9AW4W/p1643796567944719?thread_ts=1643794808.640739&cid=C01KGM9AW4W) (internal):

> Maybe alternatively, or additionally:
> 1. Introduce [push option](https://git-scm.com/docs/git-push#Documentation/git-push.txt--oltoptiongt) to skip CI
> 2. Allow [ci skip] in commit message to skip CI

**Comment by meysholdt** [comment]
prerequisite: https://github.com/csweichel/werft/issues/148
