### ISSUE TITLE
Track when Desktop IDE URI redirect fails

### ISSUE THREAD

**Issue by loujaybee** [gitpod-io/gitpod#9934]
When redirecting to JetBrains or other Desktop IDE's we use a redirect URI, however, it has been observed that on occasions that this redirect does not work as expected, sometimes where an exception is thrown with no user action implied. This is especially challenging during a users onboarding journey where they're likely to bounce/churn if they cannot easily set up a desktop IDE. 

The following information should be considered:
* Device
* OS/Hardware etc
* The URI the user is redirecting to
* The IDE the user is redirecting to

Relates to: 
- https://github.com/gitpod-io/gitpod/issues/12089

**Comment by akosyakov** [comment]
We actually can add some analytics into Gateway plugin as @jeanp413 does it right now for VS Code desktop extension. In order to track installations, attempts to connect, their success/failure and reasons.
