### ISSUE TITLE
Remove License <> Domain restriction

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#9937]
We want to remove the coupling of a license being tied to a domain to speed up sales cycles - see internal [here](https://www.notion.so/gitpod/Customer-Experience-Sync-dad831305b0a4577abafaa8df5afbb82#081bcdaac3e042a2af03ce66e4026749) and [here](https://gitpod.slack.com/archives/C035763SNSE/p1651855642520889?thread_ts=1651846315.350509&cid=C035763SNSE)

**Comment by MrSimonEmms** [comment]
Will this be just for the [Replicated licensor](https://github.com/gitpod-io/gitpod/blob/main/components/licensor/ee/pkg/licensor/replicated.go), or for the [Gitpod licensor](https://github.com/gitpod-io/gitpod/blob/main/components/licensor/ee/pkg/licensor/gitpod.go) as well?

If the former, this should be fairly straightforward. If the latter included, this may have unintended consequences.

**Comment by julia-leyton** [comment]
IMHO this should only apply to Replicated
