### ISSUE TITLE
Support config reload for ws-manager

### ISSUE THREAD

**Issue by Furisto** [gitpod-io/gitpod#9945]
## Is your feature request related to a problem? Please describe
ws-manager should reload its config, once changes are detected. Otherwise ws-manager needs to be restarted which breaks workspace success metrics.

## Describe the behaviour you'd like
ws-manager should pick up changes to the config map automatically instead of needing a restart.

**Comment by utam0k** [comment]
AFAIK, this feature was implemented.

**Comment by kylos101** [comment]
@utam0k closing as you mentioned this is done. 👍 🔍
