### ISSUE TITLE
Use the published gitpod theme in gitpod

### ISSUE THREAD

**Issue by gtsiolis** [gitpod-io/gitpod#9950]
### Bug description

Following up from https://github.com/gitpod-io/gitpod/issues/4281, when you install the newly published **Gitpod Theme**[[1](https://open-vsx.org/extension/gitpod/gitpod-theme)], users end up with duplicate theme entries.

<img width="619" alt="Screenshot 2022-05-12 at 1 19 14 AM" src="https://user-images.githubusercontent.com/120486/167957286-62da961c-6921-499a-a8fe-6bf00f38b4f7.png">

### Steps to reproduce

1. Open any workspace
2. Search and install the new Gitpod Theme
3. Set Gitpod Light or Gitpod Dark Theme
4. Open Color Theme Preferences
5. Notice the duplicate Gitpod Light and Gitpod Dark entries

**Comment by jeanp413** [comment]
Yes, I will remove the ones that are built-in inside gp-code
