### ISSUE TITLE
terminate IDEs gracefully on workspace shutdown

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#9955]
### Bug description

Right now we send SIGKILL to all process of IDE group. Here is a feedback about it from JB folks:

> SIGKILL is the furthest from graceful shutdown one can get - there's no way to trap it and do some work before dying, it's forced process termination without giving it the chance to finish any work or clean up. I would suggest using the shell command, waiting 15 seconds for that, and then sending it SIGKILL to be sure it's dead

Instead we should call `remote-dev-server.sh exit /path/to/project`. Not doing can lead to broken indexes and it is most likely a reason why we see reindexing sometime on workspace restart.

cc @csweichel 

### Steps to reproduce

see above

**Comment by loujaybee** [comment]
Seems related, or could possibly be implemented with the end task functionality: https://github.com/gitpod-io/gitpod/issues/3966

**Comment by jeanp413** [comment]
VS Code server have this arguments `enable-remote-auto-shutdown`, `remote-auto-shutdown-without-delay` to properly shutdown server

**Comment by mustard-mh** [comment]
@jeanp413 @akosyakov How to reproduce with Gateway and VSCode?

**Comment by akosyakov** [comment]
Stop a workspace and it will trigger interrupt signal: https://github.com/gitpod-io/gitpod/blob/93be74e1dff5e67bec7aacaa748c9b1818d4076d/components/supervisor/pkg/supervisor/supervisor.go#L718

We need to change go programs which are managing JB and VS Code react on interrupt and shutdown gracefully.

**Comment by mustard-mh** [comment]
Yes, I'm trying to figure out if passthrough `SIGTERM` will work or not

[exit](https://github.com/gitpod-io/gitpod/commit/03e16425364f693d4e158fe15a9c8f72e66fc63f) works or [passthrough](https://github.com/gitpod-io/gitpod/commit/57a24d8950f52044939f6286f6ff6762fbad26b5) works

Will try it, so I would like to know if there is a significant difference between reindexing or not

**Comment by akosyakov** [comment]
> Yes, I'm trying to figure out if passthrough SIGTERM will work or not

I think you will need to read from codebases. But from other side we already learned from JB folks that calling exit is the best and ensure that everything is preserved. Can we do it and be done with it? 😄

**Comment by mustard-mh** [comment]
I have tried `exit` command manually(both stable and EAP), but it seems not `exit` command here

<img width="849" alt="image" src="https://user-images.githubusercontent.com/20944364/169091099-9cc877ce-431b-4b3b-9166-465242678248.png">
