### ISSUE TITLE
Allow oppening files using text

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#996]
I'm working on contribution in https://github.com/RXT067/cheatsheets which has `docs/` directory full of markdown files. Editing this repository on GitPod is a not pleasant since i can never find the files that i need in the file explorer.

Requesting to add a method to type the file name for gitpod to open it.

**Comment by svenefftinge** [comment]
Not sure I fully understood the request.
There is "open file" command (it is  CMD+p on mac resp. CTRL+p on win/lin). (List all available commands, by pressing F1)
Also from the terminal you can use `open oath/to/MyFile.md`.

**Comment by svenefftinge** [comment]
Will happily reopen if I miss understood you, just let me know.
