### ISSUE TITLE
[Self-Hosted] Notify Self-Hosted Users when they lost features above 10 users

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#9971]
## Is your feature request related to a problem? Please describe
Currently, errors due to licensing issues are not handled. This means that:
- If a feature is not available to a use a feature (in the dashboard), there is a silent error in the javascript console but no notification to the user. Specifically, the EE_License_Required Error (see #3918)

## Describe the behaviour you'd like
- From a technical perspective: We should handle licensing errors that are currently silent and make them explicit to the user
- From a product perspective: We need to be able to gracefully communicate to the users of a self-hosted installation that they are losing features because they went over 10 users. This can be done via a notification, e.g. a toast. A regular developer should not have this in their face 100% of the time though - they should be able to disable this and continue developing on a reduced feature set. An admin should be able to always to see this information - and they already can via the newly introduce License tab.  

## Describe alternatives you've considered
- Do nothing - would result in a bad user experience.

## Additional context
- Replaces #3918 which has the exact same intent but was an old ticket with outdated wording.
- Internal [RFC](https://www.notion.so/gitpod/Polished-Self-Hosted-Licensing-User-Flow-b3028667f0c24b86b89753a67b1c3fa7) around this topic

Requires: https://github.com/gitpod-io/gitpod/issues/8933

**Comment by MrSimonEmms** [comment]
Initially I thought it might not be right to have this sent to every user, but I think I was wrong - admins may not be on Gitpod daily but users will be, so their the "front-line" who can notify the admins if necessary

**Comment by gtsiolis** [comment]
Similarly with https://github.com/gitpod-io/gitpod/issues/9974#issuecomment-1125023447, a global alert component could be used for informing admins or even users about the license status.

**Comment by geropl** [comment]
@lucasvaltl Would this be something Team Self-Hosted can tackle with some guidance from Team WebApp? E.g., there recently has been some work in this area ([AppNotifications](https://github.com/gitpod-io/gitpod/blob/9399771efdc8c70091d15dec1a02a27fa203c9a0/components/dashboard/src/AppNotifications.tsx#L13)), maybe there is potential to hook into that?

/cc @AlexTugarev

**Comment by lucasvaltl** [comment]
There is potential, but we would likely need a lot of guidance. We don't have as much experience with front end, as such if the webapp team can work on this it would be more efficient for Gitpod overall. Do let me know if you don't think Webapp would be able to work on this soon - then let's talk about this :)

**Comment by geropl** [comment]
Same as mentioned [here](https://github.com/gitpod-io/gitpod/issues/9974#issuecomment-1248092633): No UI work required, only thing required is to implement the check against the license on the backend.
