### ISSUE TITLE
[Self-Hosted] Proactive Admin notifications

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#9974]
## Is your feature request related to a problem? Please describe
Currently, an admin of a self-hosted installation can only see the state of their installation regarding license if they proactively look into the license tab of the admin age themselves, or the KOTS Installation UI. This means that they might only get notified of an issue (e.g. out of seats) when it is too late, potentially causing inefficiencies with onboarding new users / employees. 

## Describe the behaviour you'd like
- Implement a way to notify the admin of important events. This could be via email or via an in app notification/toast. 
- Proactively notify the admin when they are close to running out of seats (90%).
- Proactively notify admin if license is close to expiry date, at the one month befor, one week before and one day before point. 

## Describe alternatives you've considered
- Do nothing - this is not the end of the world, but having this in place would create a better experience for the admin. 

## Additional context
- Internal [RFC](https://www.notion.so/gitpod/Polished-Self-Hosted-Licensing-User-Flow-b3028667f0c24b86b89753a67b1c3fa7) around this topic. 
- #9971 
- #9972 
- #3918

**Comment by MrSimonEmms** [comment]
I like this. I guess we have to think about how we configure the broadcast medium.

In ascending order of difficulty, I'd suggest something like:
1. push notification from the browser. I think you can configure these to be sent, even if you don't have your browser open on the webpage
2. Slack/Teams notifications
3. Email - even though it's an old technology, it's always fiddly to set it up and we'd have to design templates. The above are just text/HTML sent somewhere

**Comment by gtsiolis** [comment]
Thanks for opening this, @lucasvaltl! This cought my attention!

Usually such notifications are :a: shown and persist directly in the product and :b: sent via email to (instance) admins, regardless if we'd like to show these on pro-actively or not.

Using the new alert component sounds ideal for such in-product notications. For example, this is how we could warn users that prebuilds have been paused for inactive projects (see https://github.com/gitpod-io/gitpod/issues/9232).

Given the upcoming navigation changes on the dashboard in https://github.com/gitpod-io/gitpod/issues/8385, a global alert component below the top navigations sounds ideal to host such notiications.

For example, here's a quick design draft how this could look like with a non-dismissible global alert that persists across all pages in the dashboard for admins. @MrSimonEmms 

| Early design with global non-dismissible alert component about license expiration |
|-|
| <img width="1440" alt="AdminWithWarning" src="https://user-images.githubusercontent.com/120486/168090904-6cd5c9a1-040b-4287-aa90-13bd7f27c8ec.png"> |

**Comment by geropl** [comment]
[AppNotifications](https://github.com/gitpod-io/gitpod/blob/9399771efdc8c70091d15dec1a02a27fa203c9a0/components/dashboard/src/AppNotifications.tsx#L13) might be useful here.

**Comment by geropl** [comment]
@lucasvaltl We further built out the `AppNotifications` mechanism. I think it should be able to handle all the usecases you described above. Would it work if you look into that for the license-related use-cases, and approach @AlexTugarev if you need assistance on the code?
