### ISSUE TITLE
Scss/Sass syntax highlighting

### ISSUE THREAD

**Issue by tyrale** [gitpod-io/gitpod#998]
It would be great to see some scss/sass syntax highlighting.

**Comment by tyrale** [comment]
bump

**Comment by jankeromnes** [comment]
@nisarhassan12 or @JesterOrNot would you have any ideas on how this could be achieved?

**Comment by JesterOrNot** [comment]
Haven't tested but try https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss

**Comment by svenefftinge** [comment]
Closing this, as it seems to be resolved. Please comment if anything is missing.
