### ISSUE TITLE
Investigate KOTS Preflight Check Warning - Kernel Version Showing "No matching files" Message

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#9982]
### Bug description

I have just recently noticed the preflight check for kernel version seems to not be working correctly. I am not positive what system it is checking the kernel of or the files for, but here is the `uname -a` output of my master node and two worker nodes:

```
jimmy@kubemaster.mydomain.com:~$ uname -a
Linux kubemaster.mydomain.com 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

jimmy@kubenode1.mydomain.com:~$ uname -a
Linux kubenode1.mydomain.com 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

jimmy@kubenode2.mydomain.com:~$ uname -a
Linux kubenode2.mydomain.com 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

They are above the pre-requisite of 5.4.0 however I am not sure what files its complaining about missing.

<img width="1200" alt="kots-preflight-kernel-version-warning" src="https://user-images.githubusercontent.com/405585/168128278-abecc6e8-12a0-4b3d-a01a-0a8b366c2f78.png">

### Steps to reproduce

1. Spin up a new instance of Gitpod using the KOTS installer. My instance is using `gitpod/unstable` if that makes any difference. During the initial install, I do not believe it reported the kernel version as being an issue, but I am not 100%. Ensure you're installing to a Kubernetes cluster where the kernel version is at least 5.4.0.
2. Await a new version to be released and for KOTS to "see" it.
3. Observe the kernel version preflight check showing as failed.

### Expected behavior

I would expect this check to show more information about why it's not passing and what needs to be done in order for it to pass.

**Comment by lucasvaltl** [comment]
from @MrSimonEmms - there is likely nothing we can do on this. This is an issue with replicated and we should raise it with them. @lucasvaltl to raise with replicated.

**Comment by MrSimonEmms** [comment]
This seems to be caught when the underlying collector fails. Because the preflight checks are (to the best of my knowledge) impossible to debug, I don't know what information we can give to make this better or help resolve the issue

**Comment by jimmybrancaccio** [comment]
@MrSimonEmms It looks like it's intermittent (which is no fun).

`main.3397`:

<img width="1480" alt="Screen Shot 2022-06-02 at 08 48 19AM" src="https://user-images.githubusercontent.com/405585/171644185-74c01f4d-4f0c-4981-8359-2a4617867341.png">

`main.3398`:

<img width="1526" alt="Screen Shot 2022-06-02 at 08 48 03AM" src="https://user-images.githubusercontent.com/405585/171644209-42e819fe-1aa7-45a2-ae9d-2b48f14efa56.png">

And then failed again in `main.3400`, didn't fail in `main.3401` but did fail in `main.3402`. 😵‍💫
