### ISSUE TITLE
Fix broken workspace integration test TestMissingBackup(PVC)

### ISSUE THREAD

**Issue by jenting** [gitpod-io/gitpod#9990]
### Bug description

Fix the broken workspace integration test TestMissingBackup of PVC test  https://github.com/gitpod-io/gitpod/blob/81c5a507fd14b27675a1907393539da0a885bc78/test/tests/components/ws-manager/content_test.go#L188

```
=== RUN   TestMissingBackup/CreateWorkspace/it_can_run_workspace_tasks/pvc_backup_init
    content_test.go:205: cannot start workspace: "rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference"
```

### Steps to reproduce

Run the integration test
```shell
./dev/preview/install-k3s-kubeconfig.sh
cd test
go test -v ./... \
  -kubeconfig=/home/gitpod/.kube/config \
  -namespace=default \
  -run=TestMissingBackup
```

**Comment by jenting** [comment]
cc @sagor999

**Comment by sagor999** [comment]
@jenting this is an interesting one.
In this PR it longer crashes: https://github.com/gitpod-io/gitpod/pull/9475
But, it still fails with context deadline. 
PVC is stuck in pending:
`no persistent volumes available for this claim and no storage class is set`
But looking at storage classes:
```
kubectl get storageclass
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  24h
```
It seems like local-path one is supposed to be a default one (meaning if PVC doesn't specify storage class, it should use that one). Though it doesn't seem to be the case.

:thinking: 

To fix this test in dev env, I think it will be best to do it as part of this task then: https://github.com/gitpod-io/gitpod/issues/10017

**Comment by jenting** [comment]
The current code, creating the PVC uses the "default" storageClass (which is empty) in ws-manager config.

According to https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reserving-a-persistentvolume, if we create the PVC with spec.storageClassName="", the Kubernetes will search the storage class name "" rather than using the default storage class in the cluster.

```go
        PVCConfig := m.Config.WorkspaceClasses[config.DefaultWorkspaceClass].PVC
	if startContext.Class != nil {
		PVCConfig = startContext.Class.PVC
	}
	storageClassName := PVCConfig.StorageClass

	PVC := &corev1.PersistentVolumeClaim{
		ObjectMeta: metav1.ObjectMeta{
			Name:      fmt.Sprintf("%s-%s", prefix, req.Id),
			Namespace: m.Config.Namespace,
		},
		Spec: corev1.PersistentVolumeClaimSpec{
			AccessModes:      []corev1.PersistentVolumeAccessMode{corev1.ReadWriteOnce},
			StorageClassName: &storageClassName,
			Resources: corev1.ResourceRequirements{
				Requests: corev1.ResourceList{
					corev1.ResourceName(corev1.ResourceStorage): PVCConfig.Size,
				},
			},
		},
	}
```

Therefore, we could either update the ws-manager config, "default" storageClass to `local-path` _or_ we could check if the "default" storageClass is empty, do not set the PVC spec.storageClassName.
